### ISSUE TITLE
[expo-media-library] Get assets - support for smart albums (iOS)

### ISSUE THREAD

**Issue by sevicbb** [expo/expo#10002]
Since there is a possibility to include smart albums while getting all albums from media library, is there currently a way to load assets from these albums by calling **getAssetsAsync**? This would allow us to load multiple pages from smart albums (and not only from the user created ones).

**Comment by yagudaev** [comment]
```javascript
let albums = await MediaLibrary.getAlbumsAsync({ includeSmartAlbums: true })
const albumsWithPhotos = await Promise.all(
  albums.map(async (album) => {
    const photos = await MediaLibrary.getAssetsAsync({ ...params, album: album })
    return { ...album, photos: photos.assets }
  })
```

@sevicbb wouldn't that pretty much accomplish what you want?

Getting the 'recents' album should also get you all the assets pretty much.

**Comment by kubanac95** [comment]
@yagudaev Maybe it should be documented, I came here seeing typescript types but having no idea what the property is about :)

**Comment by Joshandrews43** [comment]
Hi! 

I am trying to accomplish this, but for some reason photos saved into my Recents album on IOS are not showing up when using @yagudaev solution. I can see all my recents, but not photos saved into my recents from whatsapp.

Any idea?

**Comment by yagudaev** [comment]
@Joshandrews43 so whatsapp saves images into the `whatsapp` album. On the iOS photos app it won't show up in the Library > All Photos. However, it will show up in the Smart Album called Recents this on the photos app.

I can confirm it is missing from recents from my app as well. It appears to be a separate bug, can you file another bug? And link it here? We can continue the conversation there. Seems like images from "User's Albums" don't show up in the "Recents Smart Album".

**Comment by Joshandrews43** [comment]
@yagudaev i posted it as #13588, sorry if i am not so descriptive there, I tried to be
