### ISSUE TITLE
App crash on android on certain phone like samsung or asus but work fine on other phone

### ISSUE THREAD

**Issue by yueh80119** [expo/expo#10008]
![IMG_4256](https://user-images.githubusercontent.com/60495311/91702610-8d40f180-ebab-11ea-8455-68cf042554de.jpeg)

I have an app on tha play store and I found that it crash on Samsung and Asus only other phones work fine and iphone work fine. 
So I use a latest sdk 38 to init a new clean project,Samsung and Asus still crash and have the issue in the picture.
I dont know why cause this happen and can't find same issue.
Did anyone face this problem too ? Please help

**Comment by Redseb** [comment]
Hi, can you try to open the Expo client app (the app where you scan QR codes!) on the affected devices and scroll to the bottom of the main screen. You will see three numbers

Device Id: xxxxxx
Client version: <client version>
Supported SDKs: <sdk versions>

Send the client version and supported SDKs. Most likely you need to update your Expo app.

**Comment by yueh80119** [comment]
All the phone I use the latest version

Device ID:23c8-15af
Client Version:2.16.1
Supported SDKs:35,36,37,38

**Comment by Redseb** [comment]
That's strange, and the previous SDK versions worked without a problem? If so it must be an SDK 38 issue. Hope you get this resolved 🤞

**Comment by yueh80119** [comment]
nope SDK37 have the porblems too , so no one face this problem ?

**Comment by Redseb** [comment]
My in production app crashes maybe 1/10,000 randomly so I don't know what it could be

**Comment by Onibenjo** [comment]
facing same issue, any solution?
