### ISSUE TITLE
Add option in app.json to add the "Access WiFi Information" entitlement to managed standalone apps (required for @react-native-community/netinfo to access SSID)

### ISSUE THREAD

**Issue by AbdeenM** [expo/expo#10001]
## 🐛 Bug Report
The promise from fetching `details.ssid` always returns `null` instead of the device's connected ssid.

### Summary of Issue
The `details` object response shows null for SSID, although the location permission is granted for the expo application.
I went through the [requirements](https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo?language=objc#discussion) mentioned by apple on this matter and i believe my app and expo is at least following the first point which core location usage, however it is mentioned at the end (yellow box note)

> To use this function, an app linked against iOS 12 or later must enable the Access WiFi Information capability in Xcode.

Could this be the issue? if not has it been resolved or is there some sort of workaround? am developing an application and i need to use the SSID that the users device is currently connected too.

### Environment
```
Expo CLI 3.23.3 environment info:
System:
OS: Windows 10 10.0.18362
Binaries:
Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - C:\Users\Myself\AppData\Roaming\npm\yarn.CMD
npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
npmPackages:
expo: ^38.0.8 => 38.0.8
react: ~16.11.0 => 16.11.0
react-dom: ~16.11.0 => 16.11.0
react-native: ~0.62.2 => 0.62.2
react-native-web: ~0.11.7 => 0.11.7
```

### Reproducible Demo
```JavaScript
import NetInfo from '@react-native-community/netinfo'

NetInfo.fetch().then(state => {
  console.log('Connection type', state.type);
  console.log('Is connected?', state.isConnected);
  console.log('SSID is ', state.details.ssid);
});
```

### Steps to Reproduce
1. Install netinfo package by running `expo install @react-native-community/netinfo`.
2. Grant location permission for expo app from device settings.
3. Run code above on any component.
4. Last console log will always be null.

### Expected Behavior vs Actual Behavior
Last console log to print the devices current connected wifi network but rather null is always returned.

**Comment by brentvatne** [comment]
hi @AbdeenM! it sounds like we would need to enable the "Access WiFi Information" entitlement in xcode for this. we can certainly do this, but we will want it to default to disabled in standalone apps and provide an app.json field to explicitly enable it. at this point we have done a feature freeze for sdk39, but we might be able to fix this for you in sdk40. if you need to have this now, you might want to consider ejecting. i'm not sure if this would help you at all, but perhaps some of the information from https://docs.expo.io/versions/latest/sdk/network/ could be helpful.

**Comment by AbdeenM** [comment]
Hi @brentvatne ! Thanks for the prompt response.
Okay its great to hear the fix is manageable, and having it disabled by default and enabled through app.json sounds fantastic.
I believe SDK 39 should be released anytime soon correct? The feature is needed for our production release which is still TBA but i suspect should be sometime start of Jan 2021, so SDK 40 should be released by then am assuming since Expo is maintaining the quarterly release schedule.
Can you please confirm that this feature will be resolved on SDK 40 and if so it should be released by December this year?
If not let me know so i can act accordingly from my end, ejecting is an option but i am keeping it as my hail Mary if all fails.
Thank you for suggesting the network API i did have a look into it but it does not help since i only need the networks SSID string nothing else actually.
If you have any idea of how i can work around this please let me know!
Much appreciated.

**Comment by AbdeenM** [comment]
Hi @brentvatne hope you are doing well.
Hope you got a chance to review my last message

**Comment by brentvatne** [comment]
hi @AbdeenM! i can't guarantee that we will have the ability to do this in sdk40, but in the worst case you can eject and you will be good to go! i'll bring this up when scoping for the sdk40 and try to fit it in

**Comment by AbdeenM** [comment]
Hi @brentvatne !
Understood, i hope it does get released with SDK40 if not as you said i can always eject.
Closing now, have a good one.

**Comment by AbdeenM** [comment]
Greetings,

I just wanted to follow up on this issue and know if development adding the option in app.json would be available on next SDK release?

Thanks

**Comment by brentvatne** [comment]
we haven't built it yet, it may be possible to fit in but depends if someone at expo ends up having free time over the next few days

**Comment by AbdeenM** [comment]
okay, i hope so. thanks

**Comment by cruzach** [comment]
@AbdeenM you should be able to configure this now, the steps are:
- add 
```
"entitlements": {
        "com.apple.developer.networking.wifi-info": "true"
}
```
to the `ios` object in your app.json file
- Check the "access wifi information" capability in that particular apps "app identifier" [(you can find a list of all your app identifiers here)](https://developer.apple.com/account/resources/identifiers/list)
<img width="410" alt="Screen Shot 2020-12-08 at 10 59 23 AM" src="https://user-images.githubusercontent.com/35579283/101524968-a7cbf900-3958-11eb-9bfc-66c34229b4d8.png">

- rebuild your app with `expo build:ios`

Please note that you'll still need to request location permissions as well 

let me know if that works for you!

**Comment by AbdeenM** [comment]
Hello @cruzach !

Thank you very much for this, i am about to begin testing.
One last thing, will this also work in expo client app after updating it to sdk40 from testflight?

Thanks

**Comment by cruzach** [comment]
No we do not include this entitlement in the Expo client app

**Comment by brentvatne** [comment]
you can test it in simulator though - `expo build:ios -t simulator` will give you a build you can run in simulator, so you can try it before submitting
