### ISSUE TITLE
expo-camera returning bad base64

### ISSUE THREAD

**Issue by octaviotastico** [expo/expo#10003]
### Summary of Issue 
expo camera is not returning a valid base64 string on some devices

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I'm using the app on a Redmi Note 7, and a Redmi Mi A2

  Expo CLI 3.24.2 environment info:
    System:
      OS: Linux 5.4 Linux Mint 20 (Ulyana)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.2 - /usr/local/bin/npm
    npmPackages:
      expo: ^37.0.8 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.24.2

### Reproducible Demo

I'm using this exactly same code on my phone
https://snack.expo.io/@octaviotastico/expo-camera-bug-base64
 
### Steps to Reproduce

Just take a picture, and read the console logs, the "base64" string the camera returns it's not a valid base64 string.

### Expected Behavior vs Actual Behavior

The expected behaviour is that the camera actually returns a valid base64 string, so I can take pictures and upload them to firebase in base64 format, but the actual behaviour on both phones im testing the app, is that the string contains non-valid characters.
The snack demo works, for some reason, and returns a string with a "data:image/png;base64," prepended to it, while my phone doesn't (I have to prepend it manually). Anyways, prepending that string or not, when I pass it to the isBase64 function or to the firebase upload function (not in the snack), both of them returns an "not valid base64 string" error, because it has line breaks, and white spaces, etc. (I have to use trim and replace functions to delete them, but sometimes it won't work either)

**Comment by Nouhack** [comment]
it's the same thing with me  i try to return base64 of an image taken by takePictureAsync() to store this base64 file in firebase storage and the return value is null , That my function ==>
 const TakeImage=()=>{
       this.camera.takePictureAsync({quality:0.5,base64:true})
       .then({uri,base64}){
       console.log(base64) )=======> null return
        console.log(uri) =====> gives me the uri of the image taken
 }
 
 
 
 }

**Comment by fabriziobertoglio1987** [comment]
I tested and I think I fixed your example by using 

```javascript
Alert.alert('Is base64? (mime)' + isBase64(`data:image/jpg;base64,${photo.base64}`, {mimeRequired: true}))
```

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

```javascript
import React, { useState } from 'react'
import { StyleSheet, TouchableOpacity, View, Alert } from 'react-native'
import { Button } from 'react-native-elements'
import { Camera } from 'expo-camera'
import useCamera from './useCamera'
var isBase64 = require('is-base64');

const AssetExample = () => {

  const cameraHook = useCamera()
  const [ camRef, setCamRef ] = useState(0)

  const takePhoto = async () => {

    console.log('TAKING THE PICTURE!!!')
    const photo = await camRef.takePictureAsync({ quality: 0.5, base64: true })

    console.log(photo.base64.length)

    Alert.alert('Is base64? (no mime)' + isBase64(photo.base64, {mimeRequired: false}))
    Alert.alert('Is base64? (mime)' + isBase64(`data:image/jpg;base64,${photo.base64}`, {mimeRequired: true}))
  }

  return (
    <View style={styles.FullScreen}>

      {/*/////////////////// CAMERA ////////////////////////*/}

      <View style={styles.CameraContainer}>
        <Camera
          ref={ref => { setCamRef(ref) }}
          ratio={'4:3'}
          style={styles.FullScreen}
        />

      {/*///////////////// BOTTOM MENU ////////////////////*/}

        <View style={styles.BottomMenu}>
          <TouchableOpacity
            onPress={() => takePhoto()}
            style={{alignSelf: 'center'}}
          >
            <Button buttonStyle={styles.PhotoPreviewButton} title='Photo' onPress={() => takePhoto()} />
          </TouchableOpacity>
        </View>
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  FullScreen: {
    width: '100%',
    height: '100%'
  },
  CameraContainer: {
    width: '100%',
    height: '60%'
  },
  BottomMenu: {
    height: '20%',
    backgroundColor: '#1e1e1e',
    justifyContent: 'center'
  },
  PhotoPreviewButton: {
    width: 175,
    height: 50
  }
})

export default AssetExample
```

</p>
</details>
