### ISSUE TITLE
[android] sharing photos to other apps does not work on Android 11

### ISSUE THREAD

**Issue by esamelson** [expo/expo#10015]
This can be seen in the `expo-sharing` example in NCL, and the SMS tests (with photo attachment) in test-suite. Likely due to intent-related changes in Android API 30.

**Comment by barthap** [comment]
I tested `expo-sharing` some time ago on API 30 emulator when testing changes made in #9223 and it was working then 🤔 .

SMS module seems not to have `FLAG_GRANT_READ_URI_PERMISSION` set, which is [required now](https://developer.android.com/preview/behavior-changes-all#interaction-other-apps).
