### ISSUE TITLE
files" must be an array. when build and publish

### ISSUE THREAD

**Issue by Ahmadin29** [expo/expo#10017]
### Please note that Expo CLI issues opened in the core Expo repository will be closed.

I try to publish my app today but getting error like this

Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
Uploading /assets/images/event.png
Uploading /assets/images/splash.png
"files" must be an array.

is there any error because i successfull build and publush before?

**Comment by Wei102193** [comment]
experiencing the same issue for the whole day.

**Comment by brentvatne** [comment]
follow this issue for updates: https://github.com/expo/expo-cli/issues/2551

we are deploying a fix now
