### ISSUE TITLE
Always timeout when creating project in XDE in China, already tried with an proxy.

### ISSUE THREAD

**Issue by jaggerwang** [expo/expo#1001]
The timeout is limited to 60s, and the download speed is about 100KB/s. Also the previous downloading can ben resumed, but after tried three or four times, the download process back to 0% again!!!

![snip20171123_1](https://user-images.githubusercontent.com/1255011/33178187-3bce2ad0-d0a0-11e7-8989-373988a8b63d.png)

**Comment by brentvatne** [comment]
the latest release of xde removes the timeout: https://github.com/expo/xde/releases -- sorry for the hassle
