### ISSUE TITLE
Cannot form weak reference to instance (0x600003773b40) of class ABI38_0_0EXAVPlayerData.

### ISSUE THREAD

**Issue by SkyTreasure** [expo/expo#10014]
### Summary of Issue 
When many <Video/> component is re-rendered few times crashing in the iOS. 

### Environment 
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.9 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.13

### Steps to Reproduce
1. Create a flatlist of Videos. 
2. Create a button to show and hide the flatlist.
3. After few times of toggle it crashes. 

### Stack Trace
`
Application Specific Information:
Cannot form weak reference to instance (0x600001a00a80) of class ABI38_0_0EXAVPlayerData. It is possible that this object was over-released, or is in the process of deallocation.

CoreSimulator 704.12.2 - Device: iPhone 11 (11AC4F14-30A2-4C44-A433-8E68DAE15C16) - Runtime: iOS 13.6 (17G64) - DeviceType: iPhone 11

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0 libsystem_kernel.dylib 0x00007fff5220da76 __terminate_with_payload + 10
1 libsystem_kernel.dylib 0x00007fff52227406 abort_with_payload_wrapper_internal + 119
2 libsystem_kernel.dylib 0x00007fff5222738f abort_with_reason + 19
3 libobjc.A.dylib 0x00007fff5126bfdd _objc_fatalv(unsigned long long, unsigned long long, char const*, __va_list_tag*) + 108
4 libobjc.A.dylib 0x00007fff5126bf71 _objc_fatal(char const*, ...) + 111
5 libobjc.A.dylib 0x00007fff51268bff weak_register_no_lock + 283
6 libobjc.A.dylib 0x00007fff5126a175 objc_storeWeak + 488
7 host.exp.Exponent 0x0000000100ee29da -[ABI38_0_0EXAVPlayerData observeValueForKeyPath:ofObject:change:context:] + 132
8 com.apple.Foundation 0x00007fff25911257 NSKeyValueNotifyObserver + 329
9 com.apple.Foundation 0x00007fff259147f3 NSKeyValueDidChange + 502
10 com.apple.Foundation 0x00007fff25910803 NSKeyValueDidChangeWithPerThreadPendingNotifications + 146
11 com.apple.avfoundation 0x00007fff20992bba __avplayeritem_fpItemNotificationCallback_block_invoke + 2222
12 libdispatch.dylib 0x00007fff5208d951 _dispatch_call_block_and_release + 12
13 libdispatch.dylib 0x00007fff5208e8cb _dispatch_client_callout + 8
14 libdispatch.dylib 0x00007fff5209acdb _dispatch_main_queue_callback_4CF + 1042
15 com.apple.CoreFoundation 0x00007fff23da1869 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
16 com.apple.CoreFoundation 0x00007fff23d9c3b9 __CFRunLoopRun + 2041
17 com.apple.CoreFoundation 0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
18 com.apple.GeoServices 0x00007fff38c39bbe GSEventRunModal + 139
19 com.apple.UIKitCore 0x00007fff49325968 UIApplicationMain + 1605
20 host.exp.Exponent 0x000000010090ea05 main + 80
21 libdyld.dylib 0x00007fff520ce1fd start + 1
`

**Comment by IjzerenHein** [comment]
Hi! Can you provide a snack to reproduce the problem? Problems that are easily reproducible tend to get more attention and get fixed quicker. Thanks!
