### ISSUE TITLE
DocumentPicker crashes iPad Pro

### ISSUE THREAD

**Issue by kay-is** [expo/expo#1002]
I tried a very simple [example](https://snack.expo.io/S15i1JDJG) which works on my iPhone 6 and on my MiMax2.

But my iPad Pro 9.7" with iOS 11.1.2 always freezes and then exits the Expo client.

**Comment by brentvatne** [comment]
cc @charlesvinette

**Comment by charlesvinette** [comment]
Hello @kay-is ! Just wanted to report back as we found the issue. It will be included in the next Expo release (SDK 24). Thanks!

**Comment by kay-is** [comment]
@charlesvinette will this be released before christmas?

**Comment by charlesvinette** [comment]
Hey @kay-is ! Yes we are aiming for end of next week :D

**Comment by kay-is** [comment]
Noice!

**Comment by dillonhafer** [comment]
Will this fix be part of SDK 25?

**Comment by terribleben** [comment]
Yes.
