### ISSUE TITLE
Changing the icon from the application

### ISSUE THREAD

**Issue by batuhanoztrk** [expo/expo#10021]
Hello, I want to change the application icon when it is a birthday in my project. There is a library for React native but it doesn't work with expo. Is there an easy way to do this in Expo?

**Comment by Redseb** [comment]
Hi, as far as I know this is not possible within a managed workflow (you would have to eject from expo). Also, I believe only iOS supports dynamically changing the app icon, not Android. 

Perhaps sending a push notification or updating the app's badge count would be better?

**Comment by byCedric** [comment]
Hi @batuhanoztrk! Like Redseb mentioned, we don't support that for managed projects. To implement functionality like this, you'd have to eject to the bare workflow. Unfortunately, when you eject you can't use the Expo build service (yet). [Read more about the differences here](https://docs.expo.io/introduction/managed-vs-bare/#workflow-comparison).

But if you choose to eject, you might get this functionality working [with this library](https://github.com/idearockers/react-native-dynamic-app-icon). I haven't tried it myself, but it looks like it supports what you want to achieve.

Hope this helps!
