### ISSUE TITLE
Facebook Login access token doesn't match the App_id set in Facebook.initializeAsync

### ISSUE THREAD

**Issue by diamondback15** [expo/expo#10024]
## 🐛 Bug Report
I think this problem has been mentioned previously, but I still can't figure out why it's still not working.
I'm working on this problem for the past 4 days and it's blocking my whole project. It's just a basic firebase auth with Facebook and Firebase. The web app is currently running live with no issue. It's only when I get the access_token from expo that I'm getting the wrong token.

I initially thought the problem was related to firebase, but I can login perfectly in expo when I use the token generated from the web app. (instead of expo-facebook)

Facebook Login access token doesn't match the App_id
[Error: Unsuccessful debug_token response from Facebook: {"error":{"message":"(#100) The App_id in the input_token did not match the Viewing App","type":"OAuthException","code":100,"fbtrace_id":"AAMVAEGpWfkkzSz9j2UGLBi"}}]

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.10 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.13.9 => 0.13.9 
    npmGlobalPackages:
      expo-cli: 3.21.13

app.json
"facebookScheme": "fbappid",
"facebookAppId": "appid",
"facebookDisplayName": "displayname",

### Reproducible Demo

    async function logInFacebook() {
      await Facebook.initializeAsync(
         '987654321' // appid same as the one used in Firebase
      );

      const { type, token } = await Facebook.logInWithReadPermissionsAsync(
        { permissions: ['public_profile'] }
      );

      // const fbTokenFromWebApp = '12345678' // access token from my web app facebook login working perfectly
      
      if (type === 'success') {
        const credential = await auth.FacebookAuthProvider.credential(token);
      
        auth().signInWithCredential(credential)
        .then(res => console.log(res))
        .catch(err => console.log(err))
      }
    }

I've been looking at https://developers.facebook.com/tools/debug/accesstoken and the appId is the one from expo client, not from my actual firebase app

<img width="652" alt="Screen Shot 2020-09-01 at 1 17 28 PM" src="https://user-images.githubusercontent.com/655531/91850634-c2098300-ec55-11ea-8dc0-3f349c437add.png">

**Comment by diamondback15** [comment]
Update : This is working fine in when I execute after the app is built : `expo build:ios`

Is it possible to make it work in dev mode? on `expo start`

**Comment by byCedric** [comment]
Hi @diamondback15! Unfortunately, there isn't an easy way to make the Expo Client use your Facebook ID locally. There is a way by creating a custom iOS Expo Client to develop with, [described here](https://docs.expo.io/versions/latest/sdk/facebook/#configuration).

> No configuration is needed to use the Facebook SDK in the App Store Expo client, because all of your Facebook API calls will be made with Expo's Facebook App ID. The slight downside to this is that you can't customize which permissions your app requests from Facebook (like user_photos or user_friends), or integrate Facebook login with other services like Firebase auth. If you need that functionality, you have two options ...

Hope this helps!

**Comment by alisherk** [comment]
is there any other way to test it in development besides running expo build:ios?
