### ISSUE TITLE
[reanimated v2][iOS] interpolate from V1 has been renamed to interpolateNode

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#10027]
### Summary of Issue 

Linking with https://github.com/expo/expo/issues/9850
During [versioned QA]() on iOS I was testing `ncl/APIs/FileSystem` and encountered this error:

![Screen Shot 2020-09-01 at 16 06 18](https://user-images.githubusercontent.com/16623003/91861448-18ce8700-ec6d-11ea-9914-1807c63f3106.png)

```
Error: Reanimated: interpolate from V1 has been renamed to interpolateNode.
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
* /Users/bbarthec/Work/expo/packages/expo/build/environment/react-native-logs.fx.js:27:4 in error
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
* /Users/bbarthec/Work/expo/packages/expo-error-recovery/build/ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
* /Users/bbarthec/Work/expo/node_modules/regenerator-runtime/runtime.js:45:36 in tryCatch
* /Users/bbarthec/Work/expo/node_modules/regenerator-runtime/runtime.js:274:29 in invoke
* /Users/bbarthec/Work/expo/node_modules/regenerator-runtime/runtime.js:45:36 in tryCatch
* /Users/bbarthec/Work/expo/node_modules/regenerator-runtime/runtime.js:135:27 in invoke
* /Users/bbarthec/Work/expo/node_modules/regenerator-runtime/runtime.js:145:18 in PromiseImpl.resolve.then$argument_0
* /Users/bbarthec/Work/expo/react-native-lab/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
* /Users/bbarthec/Work/expo/react-native-lab/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
* /Users/bbarthec/Work/expo/react-native-lab/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.24.2 environment info:
```
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.24.2
```

#### Device:
```
	iOS version: OS 13.6
	Model: iPhone 11
```
 
### Steps to Reproduce

- Using https://github.com/expo/expo/tree/%40bbarthec/sdk-39-version-ios branch open `app.json` in `ncl` and change `sdkVersion = "39.0.0"`
- run `expo start -c`
- open the app in ExpoClient and navigate to `ncl/APIs/FileSystem`

**Comment by sjchmiela** [comment]
For me or anyone else who gets to work on this — the problem lies in `expo-progress` which still depends on Reanimated v1

https://github.com/EvanBacon/expo-progress/blob/5476b01a29fd92c4188ec70a9fe1e06592bbb0c5/src/Bar.tsx#L15

**Comment by mikeRChambers610** [comment]
Why was this closed? Im getting a warning every time I use navigation in my app (interpolate from V1 has been renamed to interpolateNode). 

I am also seeing animations glitching. Does not seem like this issue is resolved...

**Comment by bbarthec** [comment]
@mikeRChambers610, looks it's been closed due to GitHub's linking mechanisms. Reopening it now.

**Comment by LearnXtra2** [comment]
I upgraded to expo sdk 41 and I began to see this warning I believe expo has also changed the version of react-reanimated in their sdk so how do I update this library in expo sdk to the new version of this react-animated

**Comment by shravankumartalabhaktula** [comment]
Hi there, I have faced the very similar warning issue. The workaround what I did to mitigate this warning may not be the best solution  but it does the job. 

1. Go into node_modules/react-native-reanimated/reactanimated2 folder.
2. Open the interpolation.ts file.
3. In line number 119, just comment the console.warn line. 

This solution has solved the warning and glitching issue for me but still  I feel its not the best way. Lets hope for best optimal solution. Thanks.

![react-native-issue](https://user-images.githubusercontent.com/54760489/116279037-b2224e80-a7a4-11eb-91f1-c4884a1f373e.png)

**Comment by mikeRChambers610** [comment]
@bbarthec  thank you for reopening. Please let us know once you have any updates.

**Comment by LearnXtra2** [comment]
Thanks A lot it just worked like magic

**Comment by RyanTG** [comment]
I agree that commenting out a warning doesn't seem like the best way to deal with this.

I don't even know why I have react-reanimated in my modules! I'm not using it, nor am I using expo-progress (as mentioned above). I think I need to clear out unused modules or something :smile:

**Comment by TromeshChalodiya** [comment]
> Hi there, I have faced the very similar warning issue. The workaround what I did to mitigate this warning may not be the best solution but it does the job.
> 
> 1. Go into node_modules/react-native-reanimated/reactanimated2 folder.
> 2. Open the interpolation.ts file.
> 3. In line number 119, just comment the console.warn line.
> 
> This solution has solved the warning and glitching issue for me but still I feel its not the best way. Lets hope for best optimal solution. Thanks.
> 
> ![react-native-issue](https://user-images.githubusercontent.com/54760489/116279037-b2224e80-a7a4-11eb-91f1-c4884a1f373e.png)

good solution but as you said we need optimal one!!

**Comment by mikeRChambers610** [comment]
Commenting out the warning does not stop the glitching. When I move from a drawer screen -> main tab navigator, I am seeing a nasty glitch where the screen flashes to the  previous page then back to the current page. this glitching only started when the interpolate() warnings started to appear.

**Comment by RyanTG** [comment]
We downgraded reanimated to `"react-native-reanimated": "~1.13.0",` just to shut up the warning. The flicker issue you mentioned happens even with that earlier version of reanimated. I think that flicker issue is with react-navigation (from what I have seen, most 4.4.4 users are reporting it, though I saw at least one report from someone using 5.x). There are also issues in the react-native-screens repo for the flicker issue, as well. I tried 3 different version of screens (2.18, 3.0.0, 3.2.0) and the issue was present on all. Making me conclude (but I don't really know) that the issue stems from react-navigation.

**Comment by mikeRChambers610** [comment]
> We downgraded reanimated to `"react-native-reanimated": "~1.13.0",` just to shut up the warning.
> 
> The flicker issue you mentioned happens even with that earlier version of reanimated. I think that flicker issue is with react-navigation (from what I have seen, most 4.4.4 users are reporting it, though I saw at least one report from someone using 5.x). There are also issues in the react-native-screens repo for the flicker issue, as well. I tried 3 different version of screens (2.18, 3.0.0, 3.2.0) and the issue was present on all. Making me conclude (but I don't really know) that the issue stems from react-navigation. That said, users have reported the issue being fixed when screens is disabled (not a good solution, though). Waiting on maintainers to give their expert insights!

Thanks for the details that definitely helps narrow down the issue.
