### ISSUE TITLE
takeSnapshotAsync unable to take a snapshot of the View with Video Component

### ISSUE THREAD

**Issue by abhishek-raj** [expo/expo#1003]
takeSnapshotAsync unable to take a snapshot of the view with Video Component inside it on Android and in iOS 11.1.1. I was trying to make a thumbnail of the video using takeSnapshotAsync.

Here is the snack of what I was trying to do.
https://snack.expo.io/@abhishekraj/snapshot-video

This works for iOS 11.1 that appetize uses.

**Comment by nikki93** [comment]
@abhishek-raj For now this is unsupported in general for Video. It only works on Appetize because in a simulator the video is not rendered directly with hardware by OpenGL, unlike on a device. We may look into implementing this option in the future or you could look into [detaching to using ExpoKit](https://docs.expo.io/versions/latest/index.html) and extending `takeSnapshotAsync()` yourself if you want this feature sooner.

**Comment by dok** [comment]
@nikki93 does this work for <Camera/>?

**Comment by abhishek-raj** [comment]
@dok I think all video rendering on real hardware is by OpenGL, so it won't work there too.

**Comment by dok** [comment]
@abhishek-raj thanks for your response. It's a bit ugly but I ended up taking a picture with the camera, swapping the camera component with the image, then using this API.

**Comment by abhishek-raj** [comment]
@dok that works but I just wanted to make a thumbnail for my videos. For now I am using server side code to make a thumbnail from the uploaded video.

**Comment by thomprycejones** [comment]
Any update on this issue? :)

**Comment by nandorojo** [comment]
Any plans to add takeSnapshotAsynch support for Camera? Even for normal front-facing camera, it would be nice since the Camera takes a bit to take a real picture, and flips the resulting picture 180 degrees. Would be an amazing addition, thank you!!

**Comment by clems36** [comment]
@nikki93 any update on this ?

**Comment by AdamJNavarro** [comment]
Closing this issue in favor of this Feature Request on Canny: https://expo.canny.io/feature-requests/p/add-video-support-for-takesnapshotasync
