### ISSUE TITLE
[camera][android] takePictureAsync can take a long time to resolve

### ISSUE THREAD

**Issue by ShivanshJ** [expo/expo#10031]
1. Documentation has not provided how to click and preview images without delay.
  2. Images clicked only after second click (not reproduced everytime, but happens often)

Many people rely on expo-camera for images that click as fast as in Instagram / Snapchat without writing native-specific code in Android/ iOS. 

You can test this on your device. with this [snack link](https://snack.expo.io/J5U4NSjaK) 

---
This is similar to a few other issues like [this](https://github.com/expo/expo/issues/2288), these are issues from 2018 which are there to this day. Is this because of documentation error or some inherent flaw that can not be corrected ?

**Comment by brentvatne** [comment]
can you explain this in more detail? i don't quite understand the issue that you're encountering. i ran the example you provided on my iphone and it took maybe half a second for the image to save to disk and then load, which seems to be the norm for the camera in any app

**Comment by ShivanshJ** [comment]
> can you explain this in more detail? i don't quite understand the issue that you're encountering. i ran the example you provided on my iphone and it took maybe half a second for the image to save to disk and then load, which seems to be the norm for the camera in any app

I will post a gif/short video regarding the same. For my android phone (One Plus 5T)  it is giving an approx. 2 seconds delay. Also, after the button to click is pressed, the background color is shown before giving the image preview for about half a second too (could be white/black/ whatever you set it too). 

Whereas, the expected functionality is that as soon as I click the preview should be shown.  Like here, I set the BG to `dodgerblue` , which is shown after the image click before the transition to the preview.

```
return (
    <View style={{ flex: 1 }}>
      <ImageBackground source={{ uri: props.previewUri }} style={{
        flex: 1,
        backgroundColor: 'dodgerblue',
        justifyContent: 'flex-end',
      }} / >
       
    </View>
```

**Comment by eugali** [comment]
Same issue here. Too slow on Samsung Galaxy A520 2017

**Comment by camilopineda100** [comment]
Same issue here. It takes about 2 seconds to `takePictureAsync` resolve the promise, no matter pictureSize

**Comment by musangowope** [comment]
same here

**Comment by Fedeorlandau** [comment]
same here :(

**Comment by nicusbonannus** [comment]
I also have this problem, it takes almost 12 seconds on my Xiaomi Redmi Note 8 to process the image.

**Comment by rissois** [comment]
Try setting skipProcessing to true.

Prior issues: #706 #8296 
[takePictureAsync](https://docs.expo.dev/versions/latest/sdk/camera/#takepictureasyncoptions) 
[CameraPictureOptions](https://docs.expo.dev/versions/latest/sdk/camera/#camerapictureoptions)
`If set to true, camera skips orientation adjustment and returns an image straight from the device's camera. If enabled, quality option is discarded (processing pipeline is skipped as a whole). Although enabling this option reduces image delivery time significantly, it may cause the image to appear in a wrong orientation in the Image component (at the time of writing, it does not respect EXIF orientation of the images).`
`Note: Enabling skipProcessing would cause orientation uncertainty. Image component does not respect EXIF stored orientation information, that means obtained image would be displayed wrongly (rotated by 90°, 180° or 270°). Different devices provide different orientations. For example some Sony Xperia or Samsung devices don't provide correctly oriented images by default. To always obtain correctly oriented image disable skipProcessing option.`

**Comment by 2510subham** [comment]
takePictureasync takes a lot of time , and at that time if someone changes the camera position then picture becomes blurry
