### ISSUE TITLE
[AV] Playback stopped by Android when device locked and not charging

### ISSUE THREAD

**Issue by gianpietro-magiqapps** [expo/expo#10056]
### Summary of Issue 

In Android devices with latest expo-av (Exoplayer), if the device is locked and not charging, it seems that some power management feature literally "stops" the playback after playing for a while, until the app is opened again. This does not happen with iOS, nor in Android with other music playing apps subject to the same power management features (Spotify, TuneIn, etc)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Using expo-av 8.6.0 under the following environment:

```
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.21.13
```

### Reproducible Demo

Here's some sample code I'm using for my tests:
```
const initAudio = async () => {
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
      interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DUCK_OTHERS,
      playsInSilentModeIOS: true,
      interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS,
      shouldDuckAndroid: true,
      staysActiveInBackground: true,
      playThroughEarpieceAndroid: false,
    });

    let localPlaybackInstance = new Audio.Sound();
    let source = {
      uri: `https://streamer.radio.co/${activeRadioId}/listen`,
    };

    const status = {
      shouldPlay: isPlaying,
      volume: volume,
      androidImplementation: "MediaPlayer",
    };

    const onPlaybackStatusUpdate = async (status) => {
      setIsBuffering(status.isBuffering);
    };

    localPlaybackInstance.setOnPlaybackStatusUpdate(onPlaybackStatusUpdate);
    await localPlaybackInstance.loadAsync(source, status, false);
    await addPlaybackInstance(localPlaybackInstance);
  };
```
 
### Steps to Reproduce

- Reproduce this radio link with expo-av: https://streamer.radio.co/s06b196587/listen, playing in background activated.
- Lock the Android device, without charging it.
- The playback will eventually stop.

### Expected Behavior vs Actual Behavior

Just like in iOS or in other Android media playing apps, Android devices should let the expo-av playback continue in background even without needing to plug the charger.

**Comment by IjzerenHein** [comment]
> literally "stops" the playback after playing for a while
what exactly do you mean after a while? Can you give a ball park figure?

Also, did the app get terminated by Android entirely (which might happen if Android thinks the app is using too much cpu/mem), or did it only stop the audio?

**Comment by gianpietro-magiqapps** [comment]
Hi @IjzerenHein, this happens after 10-15min of the phone being locked and not charging.

The app is not terminated, it's just the audio that stops. When we visit back the app, audio restarts normally.
We have also noticed that the app appears as "stopped" in the "battery usage" view (attaching examples)

App running:
![appRunning](https://user-images.githubusercontent.com/70206439/92982541-2998ad00-f464-11ea-9044-9d55211c135b.png)

After 10-15 minutes of phone not charging:
![appStopped](https://user-images.githubusercontent.com/70206439/92982543-2ef5f780-f464-11ea-9cfe-92e7d339c508.png)

**Comment by chromacoma** [comment]
I can confirm that a similar thing is happening when recording. I've opened a separate issue here: #10501

**Comment by gianpietro-magiqapps** [comment]
Hi, I had to eject and use react-native-track-player, which Android and iOS do recognize as an audio player, so it got rid of the issue and also shows player information in the native widgets.

**Comment by garrett-gottlieb** [comment]
Can confirm this is stil happening on Expo v43 and v44 `expo-av: ~10.2.0`

**Comment by connorlindsey** [comment]
I'm currently experiencing this on iOS as well, even with different `setAudioModeAsync` settings like staysActiveInBackground. Would love some input from the Expo team on this.

**Comment by adamtsai1** [comment]
I am experiencing this issue as well (on Android). Expo 44, exp-av 10.2.0.

**Comment by aelxxs** [comment]
I'm also experiencing this issue. The audio stops after a minute or so. I'll be switching to `react-native-track-player`.
