### ISSUE TITLE
[AV] AndroidImplementation "MediaPlayer" not working with remote MP3 Playlist

### ISSUE THREAD

**Issue by gianpietro-magiqapps** [expo/expo#10052]
### Summary of Issue 

I have tested Exoplayer successfully with an mp3 radio stream (m3u), but now would like to try the MediaPlayer implementation, which is supposed to consume less resources (I have a separate issue with Android stopping my app due to resources consumption)
Thing is, when I change to MediaPlayer, it stops working, never loads the stream.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

expo-av version is 8.6.0, and here the platform info:
```
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.21.13
```

### Reproducible Demo

My function is something like this, you can replace the activeRadioId with "s06b196587" to test it out. If I remove the "androidImplementation" line, it works fine.

```
const initAudio = async () => {
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
      interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DUCK_OTHERS,
      playsInSilentModeIOS: true,
      interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS,
      shouldDuckAndroid: true,
      staysActiveInBackground: true,
      playThroughEarpieceAndroid: false,
    });

    let localPlaybackInstance = new Audio.Sound();
    let source = {
      uri: `https://streamer.radio.co/${activeRadioId}/listen`,
    };

    const status = {
      shouldPlay: isPlaying,
      volume: volume,
      androidImplementation: "MediaPlayer",
    };

    const onPlaybackStatusUpdate = async (status) => {
      setIsBuffering(status.isBuffering);
    };

    localPlaybackInstance.setOnPlaybackStatusUpdate(onPlaybackStatusUpdate);
    await localPlaybackInstance.loadAsync(source, status, false);
    await addPlaybackInstance(localPlaybackInstance);
  };
```
 
### Steps to Reproduce

Test the above URL with Exoplayer works fine, switch to androidImplementation "MediaPlayer", and stops working (on physical device)

### Expected Behavior vs Actual Behavior

Both Exoplayer and Mediaplayer should work with MP3 streams (m3u playlist), only Exoplayer works.

**Comment by IjzerenHein** [comment]
Hi! Can you provide a fully functional snack? Issues that are easily reproducible tend to get more attention and get solved quicker.
regards!

**Comment by brunolcarlos** [comment]
I have a similar problem, some times my videos stop to play and freeze.
I opened this issue but someone closed.
https://github.com/expo/expo/issues/16403
