### ISSUE TITLE
Error while implementing react-native-voice on Expo

### ISSUE THREAD

**Issue by rubencg195** [expo/expo#1005]
**I am trying to implement the following react native module
https://github.com/wenkesj/react-native-voice**

**I have added the following permissions, copy the exact example to my App.js from their docs.**
https://github.com/wenkesj/react-native-voice/tree/master/VoiceTest

**The only thing I haven't done is manually link to Android since my Expo generated app doesn't have an Android folder at all.**

----------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/25628940/33191708-ee1a634e-d0b3-11e7-939b-31a93b124d31.png)
------------------------------------------------------------------------------------------------------------------

**This is my source folder**

----------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/25628940/33191719-017b234c-d0b4-11e7-9327-13cf181e61a0.png)
----------------------------------------------------------------------------------------------------------------

**This is the view and the error thrown once I press the button to start the voice recognition**

----------------------------------------------------------------------------------------------------------------
![whatsapp image 2017-11-24 at 01 09 38](https://user-images.githubusercontent.com/25628940/33191753-601be77e-d0b4-11e7-87a6-9c31c2d9bb00.jpeg)
----------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------
![whatsapp image 2017-11-24 at 01 09 56](https://user-images.githubusercontent.com/25628940/33191752-5eba7580-d0b4-11e7-9218-d320ac2e823d.jpeg)
----------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------
**This is my code, as you will see is exactly the same as the example. Nothing else besides de App.js has being edited from the generated react native boilerplate from expo.**
----------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/25628940/33191799-c400f234-d0b4-11e7-990f-11de89d1305a.png)
----------------------------------------------------------------------------------------------------------------

**Comment by brentvatne** [comment]
hi there! this is because you need to detach your project if you want to add native modules. see: https://docs.expo.io/versions/latest/introduction/faq.html#how-do-i-add-custom-native-code-to-my-expo-project
