### ISSUE TITLE
Move expo admob Android ads to Google mobile ads SDK 18.1.0 to support user metrics

### ISSUE THREAD

**Issue by bculley** [expo/expo#10053]
Admob user metrics require Android Google mobile ads SDK 18.1.0 in order to function per Google https://support.google.com/admob/answer/9263723?hl=en-GB

unless I'm mistaken, this package seems to be using 17.2.1 https://github.com/expo/expo/blob/master/packages/expo-ads-admob/android/build.gradle

**Comment by cruzach** [comment]
Upgraded to 19.4.0 in https://github.com/expo/expo/pull/12125, and available in the SDK 41 beta- https://blog.expo.io/expo-sdk-41-beta-is-now-available-958edcd78991
