### ISSUE TITLE
[Expo Local Authentication] - FaceID not working in iPad Pro - iOS 13 and Bare Workflow - working on iPhone XR 

### ISSUE THREAD

**Issue by eugali** [expo/expo#10051]
### Summary of Issue 
Face ID enrolled and authorized works on iPhone XR but fallbacks to TouchID in iPad Pro
Furthermore the app recognises the Face ID hardware. 

### Steps to Reproduce
Face ID set and enrolled in an iPad Pro

### Expected Behavior vs Actual Behavior
Expected Behavior: Face ID prompt showing after being recognised, set and authorised
Actual Behavior: Face ID fallbacks to Touch ID

**Comment by byCedric** [comment]
Hi @eugeniogalioto, could you provide a small [repro](https://stackoverflow.com/help/minimal-reproducible-example) for this problem? With that, we can investigate this issue and find a solution 😄

**Comment by eugeniogalioto** [comment]
Hi @byCedric unfortunately I cannot reproduce in my dev environment (it works in my iPad Pro simulator). The error appears in a client's iPad Pro (with the same release build as the iPhone XR that works). In the same iPad Pro, other apps that require Face ID work. I appreciate there's not enough details, unfortunately I cannot further investigate myself since I don't have that physical device...

**Comment by salhotra** [comment]
I am facing a similar issue with iPhone 11. It works on my iPhone Xs flawlessly but is inconsistently on a teammate's iPhone 11. I can't physically test it on their device. But I do have the following information:

1) Firstly, `LocalAuthentication.supportedAuthenticationTypesAsync()` seems to return something other than 1, 2, or 3. I am showing a text in a menu based on this value (Text is "Use FaceID" for 1, and so on). When the value is not matched, I show "Use Phone passcode" just to handle a default case even though it was not needed. But on their phone, "Use Phone passcode" text shows up.

2) Then the second issue is sometimes the FaceID prompt doesn't show up at all. So they get stuck on the prompt's underlay (which I have built to overlay the app)
