### ISSUE TITLE
Axios API, work when development process, but failed after build apk and install on my device

### ISSUE THREAD

**Issue by fhdyt** [expo/expo#10074]
When i develop my app, api request work fine, but when i build to apk and install on my device, Network Error.

Can anyone help me, i deploy my server to heroku so url using HTTPS

**Comment by superyarik** [comment]
Need more information. We moved from fetch to axios our applications and its works perfect.

**Comment by dotfelixb** [comment]
Have you enable internet in your Manifest 

 <uses-permission android:name="android.permission.INTERNET" />

**Comment by byCedric** [comment]
Hi @fhdyt! Unfortunately, there are a lot of factors possibly causing this issue. If you can create a [small repro](https://stackoverflow.com/help/minimal-reproducible-example), we can help investigate. Right now, there is no context or example which makes it really hard to help you.

**Comment by alexeymolchan** [comment]
In my case the problem was with ssl certificates

**Comment by mukeshmadikai** [comment]
What was the issue with certificates?

**Comment by cruzach** [comment]
Closing since this isn't a bug with Expo
