### ISSUE TITLE
eslint-config-universe , typescript requirement missing from docs [docs] 

### ISSUE THREAD

**Issue by nikoloz110** [expo/expo#10073]
having typescript installed is a must, for linter to work, though it is not mentioned in the documentation.

**Comment by byCedric** [comment]
I'm not sure what you mean by missing from docs, I think it's [well documented in the repo](https://github.com/expo/expo/tree/master/packages/eslint-config-universe#installation) or am I missing something?

**Comment by nikoloz110** [comment]
you have to install typescript as a dependency otherwise the linter does not work.
"npm install typescript" - is missing from the docs.

**Comment by sadi304** [comment]
@nikoloz110 +1, docs should mention this.
