### ISSUE TITLE
IntentLauncher doesnt work on android builds if the `enableDangerousExperimentalLeanBuilds` flag is true 

### ISSUE THREAD

**Issue by rishav394** [expo/expo#10076]
## 🐛 Bug Report

`IntentLauncher.startActivityAsync` always throws `ERR_UNAVAILABLE` on android builds (not in expo client) if the `enableDangerousExperimentalLeanBuilds` flag is true.

Tried setting the experimental flag to false and the problem is resolved.
Done `expo install expo-intent-launcher`

### Environment
Platform - Android only
enableDangerousExperimentalLeanBuilds - true
SDK - 38

### Steps to Reproduce
1. Set `enableDangerousExperimentalLeanBuilds` flag under Android to true
2. Try to use `IntentLauncher` with android.intent.action.VIEW like so:
```
IntentLauncher.startActivityAsync("android.intent.action.VIEW", {
  data: cUri,
  flags: 1,
})
```

### Expected Behavior vs Actual Behavior
Expected - Intent to Work on production and Expo
Actual - Only works on Expo client. Fails with `ERR_UNAVAILABLE` on android builds *if enableDangerousExperimentalLeanBuilds is true*

**Comment by brentvatne** [comment]
can you link me to a build page for a build that included this package?

**Comment by rishav394** [comment]
Hi @brentvatne Sorry for the delay and thanks for replying. I didnt understand you very well, if you want the project expo link here you go https://expo.io/@rishav394/UPT

Nothing that uses INTENT internally (Sharing, Printing, WebBrowser) works **on builds** if I have `enableDangerousExperimentalLeanBuilds` enabled. Everything works fine in the expo client of course.

If you want the build logs, https://gist.github.com/rishav394/82ece9dd76c99649848a3e67c2029be6

**Comment by rishav394** [comment]
This was fixed in Expo SDK 42
