### ISSUE TITLE
Think about the best way for Expo Client to provide information about an app's release channel

### ISSUE THREAD

**Issue by kbrandwijk** [expo/expo#1007]
If you have the same app installed from multiple release channels, there's no way to see which is which.

**Comment by terribleben** [comment]
Updating title because I'm not sure doing it in the project list is what we want.

**Comment by slorber** [comment]
Might be a little related: https://github.com/expo/expo/issues/1039

**Comment by terribleben** [comment]
I believe Expo Client shows release channel in the project list ask of SDK 24.
