### ISSUE TITLE
Android Missing activity in Release build

### ISSUE THREAD

**Issue by Zapopozapopo** [expo/expo#10089]
### Summary of Issue =
About 30% of the app starts ends up with 'Activity not found ' error. Release build only

### Environment
Devices: Samsung Note 8, S on Android 9,10

Ejected expo v(36,37,38)
 
### Steps to Reproduce
My steps:

install expo-splash-screen

1) await SplashScreen.preventAutoHideAsync();

will return you '[Error: Current activity not found. Make sure to call this method while your application is in foreground.'

Project quite big, but issue related to only a few devices. If I remove ' SplashScreen.preventAutoHideAsync()' the app will start but UI will be unresponsive and all async code will be broken

**Comment by ibraude** [comment]
Hey @Zapopozapopo, 
I'm facing the same issue on Android, React-Native version 0.61.5 in an ejected Expo project.
Once every couple of times the app launches I will get the following error from `SplashScreen.preventAutoHideAsync()`:
`[Error: Current activity not found. Make sure to call this method while your application is in foreground.'`

Any luck resolving this issue? 

Thanks

**Comment by brentvatne** [comment]
https://stackoverflow.com/help/minimal-reproducible-example - provide one and we will be able to help! otherwise, please investigate the root cause in your project and report back here

**Comment by ibraude** [comment]
**Resolved**
Running `expo publish` and then rebuilding the app resolved the issue for me. 
This is related to expo-updates and a bare workflow.
Please see
https://github.com/expo/expo/issues/7899
https://github.com/expo/fyi/blob/master/release-builds-with-expo-updates.md

**Comment by rikur** [comment]
Not stale, occurring.

**Comment by BrodaNoel** [comment]
Yeap... Still.

**Comment by bondansebastian** [comment]
It's been 2022 and it's still occuring

**Comment by DanielAndrews43** [comment]
We're getting a few hundred of these errors per day, and each time it triggers 3-6 times

**Comment by YoshiYo** [comment]
We have the same problem here. It happens on our clients on Android.
We saw the logs in sentry directly.

```
SDK : 47
Method : SplashScreen.hideAsync()
Error : Current activity not found. Make sure to call this method while your application is in foreground.
```

Some devices crash : 

```
Smartphone : Samsung 6102H
Android version : 12
```

```
Smartphone : Wiko W-K211-EEA
Android version : 10
```

**Comment by YoshiYo** [comment]
We are trying a new config on our side according to the current docs : 
https://docs.expo.dev/versions/latest/sdk/splash-screen/#usage

So we moved `SplashScreen.hideAsync()` outside of our main react component, after the imports. I will let you now if we see less errors on our side.
