### ISSUE TITLE
Facebook SDK upgrade

### ISSUE THREAD

**Issue by AbdnhVmpr** [expo/expo#10081]
Please provide the following:
1. SDK Version: 38.0.8
2. Android

I am making react native expo app. I wanted to add FB ads to my app. But I get this error

**The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK**

When I run the app again, I get this one

error SyntheticEvent {
  "_dispatchInstances": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "_dispatchListeners": [Function onError],
  "_targetInst": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "bubbles": undefined,
  "cancelable": undefined,
  "currentTarget": 1575,
  "defaultPrevented": undefined,
  "dispatchConfig": Object {
    "registrationName": "onAdError",
  },
  "eventPhase": undefined,
  "isDefaultPrevented": [Function functionThatReturnsFalse],
  "isPropagationStopped": [Function functionThatReturnsFalse],
  "isTrusted": undefined,
  "nativeEvent": Object {
    "errorCode": 1002,
    "errorMessage": "Ad was re-loaded too frequently",
  },
  "target": undefined,
  "timeStamp": 1599433160964,
  "type": undefined,
}

**Comment by abudhia-oyo** [comment]
+1 this issue has been there for quite sometime. Completely blocked on this as this make Expo Facebook Ads completely unusable for Managed Workflows

**Comment by AbdnhVmpr** [comment]
I've been struggling with this for days. Still no solution :/

**Comment by brentvatne** [comment]
hi there! sorry this isn't working out for you. if you need to use facebook ads and the current setup in the expo managed workflow isn't working well for you then i would recommend using the bare workflow instead. you can run `expo eject` and have full control over your project and use any version of the facebook sdk that you like. https://docs.expo.io/workflow/customizing/

**Comment by abudhia-oyo** [comment]
@brentvatne the problem is that the Android build file is still using 5.1.1 version of Facebook SDK, while current is 6+.

Can we release a hotfix to make use of at-least the 5.10.0 version (assuming the contracts are same and doesn't require any development effort)?

We're not able to monetize app via In App Purchases already. At-least if the Facebook ads could get working, that'd be a relief. For multiple reasons, we are not in a position to eject expo.

**Comment by abudhia-oyo** [comment]
Thanks @cruzach for acting on this in a prompt manner.

It might be a naive question, however can you please share slight details on the release cycle? Basically how soon can I make use of this update, or I need to wait for it until the next expo SDK 40 release?
