### ISSUE TITLE
Expo.Facebook breaks with libc++abi.dylib: terminating with uncaught exception of type NSException (lldb) 

### ISSUE THREAD

**Issue by cellis** [expo/expo#1008]
I'm having trouble after detaching to ExpoKit and running a basic facebook login.

My code on a fresh project is as follows:

`App.js`
```javascript
import React from 'react';
import Expo from 'expo';
import { StyleSheet, Text, View } from 'react-native';
import getConfig from './utils/config';

export default class App extends React.Component {

  componentDidMount = async () => {
    const config = Expo.Constants.manifest.extra;
    const { production, development, facebookAppId } = config;
    console.log({ facebookAppId, production, development });

    const { type, token } = await Expo.Facebook.logInWithReadPermissionsAsync('***************', {
      permissions: ['public_profile'],
    });

    if (type === 'success') {
      // Get the user's name using Facebook's Graph API
      const response = await fetch(`https://graph.facebook.com/me?access_token=${token}`);

      console.log(
        'Logged in!',
        `Hi ${(await response.json()).name}!`,
      );
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

And my package.json ( excerpt ):

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^23.0.0",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz"
  }
}
```

When I detach this project

<img width="633" alt="screen shot 2017-11-24 at 4 07 29 pm" src="https://user-images.githubusercontent.com/202806/33225697-aa8063b2-d131-11e7-823d-893022a91e04.png">
<img width="187" alt="screen shot 2017-11-24 at 4 14 34 pm" src="https://user-images.githubusercontent.com/202806/33225754-9f52e4d2-d132-11e7-8370-ea9c9bfd158a.png">

What's wierd is that this code works fine with the Expo IDE and `exp build:ios` deployed apps work fine with this, but this project will need iAP and WebRTC so detaching is going to be necessary if I'm going to use expo...

**Comment by etamity** [comment]
I have some problem !

**Comment by cellis** [comment]
@etamity thanks will try this. Btw, how did you debug that?

**Comment by terribleben** [comment]
Super late followup here. I believe the fix is pending with our next release. Our tooling needs to be auto-adding Facebook's application queries schemes (both in standalone builds and detached ExpoKit apps). Tracking here in this [newer report](https://github.com/expo/expo/issues/1619).
