### ISSUE TITLE
BarCodeScanner - set initial camera orientation or make sure it adapts to parent view? How?

### ISSUE THREAD

**Issue by Inlesco** [expo/expo#1009]
Hello,

is there any way to set the BarCodeScanner orientation on first render? Or maybe a way to make it adapt to the parent's orientation (which, in my case, is landscape)?

Setting `Expo.ScreenOrientation.allow(Expo.ScreenOrientation.Orientation.LANDSCAPE_LEFT);` (currently, it's set before the declaration of `App` class, in `App.js`) seems to take effect on the entire app on first render, but it doesn't affect `BarCodeScanner` component.

Any solutions? Thanks!

**Comment by aalices** [comment]
@Inlesco which SDK are you using?

**Comment by Inlesco** [comment]
@aalices in app.json, `sdkVersion` is 22.0.0.

**Comment by aalices** [comment]
Give it a try with 23. `BarCodeScanner` is using `Camera` underneath since SDK 23

**Comment by Inlesco** [comment]
@aalices it worked. Problem solved. This can be closed now 👍
