### ISSUE TITLE
Handle Rejection for Remote Notification Permission

### ISSUE THREAD

**Issue by ChenLi0830** [expo/expo#101]
I am trying to handle the case when users "Don't Allow" push notifications when being asked for the permission. However, in the following code, the console.log only works if when users actually allow the permission. 
```
const { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);
console.log("status",status);
```
I am not sure what causes it. It seems to me the app just keep waiting when users reject the permission. 

"expo": "^15.1.2",

**Comment by jesseruder** [comment]
iOS or Android?

**Comment by ChenLi0830** [comment]
@jesseruder iOS.
Android seems to be working fine.

**Comment by terribleben** [comment]
@ChenLi0830 sorry about this, it's a combination of an annoyingly designed Apple API and some omissions in our SDK code as well.

- First, Apple doesn't distinguish between "permissions were rejected" and "we don't know what the permissions are yet."
- Second, Apple doesn't guarantee they will invoke any callback if the permissions were previously rejected.
- Third, we don't handle this possibility very well in our SDK right now.

As a result, rejection followed by subsequent calls to `askAsync` may lead to the promise hanging forever, as you've seen. This is something I'd like to fix soon or at least provide better docs for.

In the meantime, my recommendation is to use a key in `AsyncStorage` to manually keep track of whether you've ever asked for permissions before. Then your code would look something like this pseudocode:
```
const haveWeAskedBefore = await myGetPermissionsAskedBeforeMethod();
const { existingStatus } = await Permissions.getAsync(Permissions.REMOTE_NOTIFICATIONS);
let finalStatus = existingStatus;

if (existingStatus !== 'granted' && !haveWeAskedBefore) {
  const { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);
  await mySetPermissionsAskedBeforeMethod(true);
  finalStatus = status;
}
```

**Comment by ChenLi0830** [comment]
@terribleben Thank you Ben, I'm going to give it a try and let you know how it goes tonight.

**Comment by sonaye** [comment]
Wrap in a try/catch, and utilize the other status values.

```javascript
try {
  const response = await Permissions.getAsync(Permissions.REMOTE_NOTIFICATIONS);
  if (response.status !== 'granted') {
    if (response.status === 'denied' || response.status === 'undetermined') {
      alert('Please enable push notifications from your device settings.');
    } else {
      const { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);
      if (status === 'granted') this.setState({ notificationsGranted: true });
    }
  } else this.setState({ notificationsGranted: true });
} catch (error) {
  alert(error.message);
}
```

**Comment by terribleben** [comment]
Hey @sonaye thanks for the answer. I think until we address the aforementioned API problems, you'll get the best results using an approach closer to the one I already suggested.

(leaving this issue open until we can push an update which resolves the hanging promise bug.)

**Comment by sonaye** [comment]
I was also trying to open the settings app if the status was denied with `Linking.openURL('app-settings:')` but that didn't work, maybe you can look into adding https://github.com/lunarmayor/react-native-open-settings @terribleben.

**Comment by sonaye** [comment]
@terribleben The code I provided is working fine for me, it catches all the cases, but sure, I'll switch if that's you recommendation.

**Comment by sonaye** [comment]
Here is a quick demo, geo is granted in the simulator, but notifications are undetermined because you have to use a real device, and the code catches that properly. I am also implementing something analogous to your usage of AsyncStorage to avoid showing multiple warnings to the user every time the app starts.

![kapture 2017-04-09 at 21 49 42](https://cloud.githubusercontent.com/assets/23000873/24840293/43ffbe70-1d73-11e7-972e-6b79242308c5.gif)

**Comment by ChenLi0830** [comment]
Hey @sonaye thanks! However, it's a notification permission that suffers from this problem, the location permission is working fine for me as well. Try using it on a real device and you'll know what I mean. :)

**Comment by sonaye** [comment]
It's working just fine for me on an actual device too.

**Comment by ChenLi0830** [comment]
Thanks, @sonaye but it's still not working for me, unfortunately. If I deny the permission, the subsequent line would be not executed, and no error is caught either. I tried to use both async, await and promise, neither worked. 

I think I am experiencing the API problem @terribleben mentioned.

**Comment by ChenLi0830** [comment]
Hi @terribleben, really sorry for the delayed reply, I didn't get to work on the notification part in the past week. 

Just want to make sure I describe the problem I am experiencing clearly - In my case, when users open the app for the first time, if they deny the permission, the app would freeze. It seems the the program hang at `  const { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);`, and it seems no code below would be executed, including `await mySetPermissionsAskedBeforeMethod(true); `.

**Comment by terribleben** [comment]
I understand, and the original answer I posted should address this.

**Comment by ChenLi0830** [comment]
@terribleben It would be really great if you guys can fix this issue soon.

**Comment by jonas-arkulpa** [comment]
@terribleben 
I can confirm @ChenLi0830 findings.
The promise also hangs on the first try, if the user rejects the permission.
This way your suggested solution isn't working.
Is there any other workaround at the moment?

**Comment by thebigredgeek** [comment]
Any updates on this?

**Comment by terribleben** [comment]
Sorry for the radio silence here - this is a tentative fix which is shipping with next release: https://github.com/expo/expo/commit/7e47d585331101d013f2a5a3acf0b340fa9f92b9

**Comment by terribleben** [comment]
This came out with [SDK 18](https://blog.expo.io/expo-sdk-v18-0-0-is-now-available-38e62305283) - let me know if you are seeing an improvement.

**Comment by terribleben** [comment]
Haven't had further reports around this in the last week. Let me know if there is still an issue.

**Comment by rahls7** [comment]
Hey @terribleben. I am using expo sdk 18. If the user denies notification permission, he is not prompted again for permissions. I believe this has to be with the implementation apple's api. However, even when i manually go and change the notification settings, the const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS); still returns undetermined. Shouldn't it return granted in this case?

**Comment by madbean** [comment]
Heelo rahls7 is right,

still returns undetermined.
if you try to call anyway the get token method it's working if you have agree the notification permission.

**Comment by rajat1saxena** [comment]
Alert dialog is not shown, when user rejects a permission. How to handle this scenario?

**Comment by peferb** [comment]
Yeah, I also have the problem not being able to re-ask for notification permission if the user declines first time prompted with permission-dialog.

**Comment by corysimmons** [comment]
This is still an issue in Expo 25.

1. User denies permissions.
2. `Permissions.askAsync()` resolves `{ status: "denied", expires: "never" }`
3. Permissions get set iOS side and I assume they "never" expire, thus `askAsync()` can never trigger again (since I'm assuming `expires` is tested first).

**This is a problem with `askAsync()` auto-setting "never" (even if the permission is denied).** It needs to only do that if `status` resolves to `granted`. If `status` resolves to `denied` then just set the `expires` to now + 1ms, or something.

This way we constantly pester people to give us perms.

The `askAsync()` api could be expanded upon by accepting an expiration and just defaulting to now-or-never™ expiration.

**Comment by corysimmons** [comment]
https://github.com/expo/expo/issues/101#issuecomment-292803952 is a possible solution too. It'd offer an avenue to direct the non-tech-savvy users to their platform permissions and explicitly approve whichever perms they want on a granular level.

**Comment by corysimmons** [comment]
In the meantime, everyone can do a check for those perms up front and offer a helpful message to the user. Something like:

```js
handlePermRequest = () => {
  const { status } = await Permissions.askAsync(Permissions.CONTACTS)

  if (status !== 'granted') {
    Alert.alert(`You need to give us permission(s) for the ABC app to work! Go into your system settings, find the ABC app, and enable XYZ permissions.`)
  }
}
```

**Comment by rmushtaq21** [comment]
I'm still experiencing the same issue @ChenLi0830 originally mentioned. Using Expo SDK 25.

`const { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);` hangs the app indefinitely if the user denies permission and no lines of code are run after it. Hence, I'm unable to redirect the user to a notifications permission required screen. This is a major problem!

Has anyone found a fix/workaround?

**Comment by ide** [comment]
Hi - I'd recommend using SDK 26 as that has the latest code that's best maintained. One thing you could do to unblock your code path is to use Promise.race with a timeout, so that if you don't get a status back within 10 seconds, the app doesn't completely block at least. I understand that's not ideal but if you can't upgrade to SDK 26 it might work for you.

**Comment by rmushtaq21** [comment]
@ide Thanks so much for responding so promptly! I upgraded to SDK 26 and that fixed my problem!
