### ISSUE TITLE
AuthSessionResult is incorrectly typed

### ISSUE THREAD

**Issue by tiagob** [expo/expo#10104]
### Summary of Issue 
https://github.com/expo/expo/blob/65428d516b97c18a0494f715691194259f323fc7/packages/expo-auth-session/src/AuthSession.types.ts#L10-L19

I'm running into https://github.com/microsoft/TypeScript/issues/12815 when accessing any field that isn't defined in every union (ex. `errorCode`).

A preferable return type is

```typescript
type AuthSessionResult = {
  type: "cancel" | "dismiss" | "locked" | "error" | "success";
  errorCode?: string | null;
  error?: AuthSession.AuthError | null;
  params?: {
    [key: string]: string;
  };
  authentication?: TokenResponse | null; 
  url?: string;
};
```

**Comment by byCedric** [comment]
Hi @tiagob, thanks for the report and sorry for the delay. I think this is a convention on how we use TypeScript. Technically speaking, defining the result as ` { type: 'fail' } | { type: 'success', ... }` should be correct. We only return an object with `type` if it "successfully" failed (by user input for example). If it failed by non-user error, we return the `error` info within that object.

TypeScript is a bit weird in how it handles these cases. Generally speaking, if you have 1 shared object property name, you should be able to do something like the code below. Or use a type guard 😄 

```
if (result.type === 'cancel') {
  // typescript knows result can only contain `type`
  console.log(result.type); // works
  console.log(result.params); // doesn't work, because it's not returned for this type
}

if (result.type === 'success') {
  console.log(result.type); // works
  console.log(result.url); // works - because it matches the type property to the full object
}
```

I could be wrong here, but maybe @EvanBacon can provide more context on this?

Hope this helps!

**Comment by tiagob** [comment]
Ah yes, checking the type first works. Thank you!
