### ISSUE TITLE
Allow to use future SDK releases in expo android client

### ISSUE THREAD

**Issue by Joozty** [expo/expo#10109]
Hi first of all. Thanks for a great framework. 

I would like to ask about enabling future SDK releases in Android Expo client. The other day I wanted to use some feature which is introduced in SDK 39. I installed the SDK and run expo client. Unfortunately, when I tried to open my app on android I get a message that the SDK is not supported. 

I am not sure if it is technically possible but if that's not a big deal would it be possible to enable future releases? I am aware some things may not work properly and I am happy to take the risk. Or the other suggestion would be to shows just some warning message instead of not allowing to see the app?

Thanks

![Screenshot_20200909-123352](https://user-images.githubusercontent.com/12775440/92588277-0a99ef80-f299-11ea-92cb-f7af20588a73.png)

**Comment by cruzach** [comment]
Hi! You can't use SDK 39 until it is released, as the Expo client app has the native code you would need embedded inside of it

If you'd like to access to features and bug fixes before an SDK is released, your best option is to try them out in a bare workflow app 👍
