### ISSUE TITLE
Android - sendSMSAsync is not working properly (SDK 38)

### ISSUE THREAD

**Issue by manuellagrand** [expo/expo#10116]
### Summary of Issue 
I am trying to send sms to many users in the project I am working on by using **_sendSMSAsync_** function. On Android I'm facing some problems, I pass to **_sendSMSAsync_** a users number array like the documentation recommend to dot it but only the first user/contact of my array is opened by the native application.

### Environment

Expo CLI 3.21.9 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.6 - /usr/bin/npm
    npmPackages:
      expo: ^38.0.9 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^3.11.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.21.9

Tested on a Huawei Mate 20 Android 10.1
### Reproducible Demo

```
sendInvitation = async (item: Array<string>) => {
    const isAvailable = await SMS.isAvailableAsync();

    if (isAvailable) {
      const {result} = await SMS.sendSMSAsync(item, 'Message');
    } else {
      console.log("not available");
    }
  }; 
```
### Steps to Reproduce

Use an Android device. and try sending sms to many numbers, observe the behaviour

### Expected Behavior vs Actual Behavior

**Expected behaviour:**

the normal behaviour would be the opening of the native application of sending message with group message opened with the message ready to be sending to all contact present in the array passed to **_sendSMSAsync_** on Android

**Actual behaviour**

Currently the native application is correctly opened by the _**sendSMSAsync**_ but only the first number/element of the array is concerned

**Comment by jkobject** [comment]
It is specific to google's messaging app, where it seems to need a group name in order to create a group sms. 
Thus your `smsto:` is not working as it should. 

Maybe passing an empty attachment can be a quick fix?

**Comment by girishkr** [comment]
expo-sms is not working for Android. 
Issue 1 : you can't send sms to a list. It will pick only one number from the list.
Issue 2 : After sending SMS controlle does not come back to the application. User have to click on back button to go back to the application. 
So for not it is not usable at all specially for Andoroid.

**Comment by girishkr** [comment]
Issue 1 : you can't send sms to a list. It will pick only one number from the list.
Fix : Just send comma separated mobile number as a String in toList.
example : 
let smsResponse = await SMS.sendSMSAsync(
                                [**"**1234567890, 1122334455, 7782727827**"**],
                                "Message"
                            );

**Comment by manan-schmooze** [comment]
Still facing the issue

**Comment by likrot** [comment]
Hi, is there any plan to work with redirection back, or are there some "platform" restrictions?
