### ISSUE TITLE
Share package Instagram on iOS stopt working

### ISSUE THREAD

**Issue by tim-hanssen** [expo/expo#10113]
### Summary of Issue 

I created an app which includes sharing with expo-sharing package. After a long time the Instagram share option in the native share sheet doesn’t work anymore. (Android is still working as expected).

### Environment

SDK Version: ^37.0.0
Platforms(Android/iOS/web/all): iOS
Share package: “expo-sharing”: “~8.3.0”.

### Reproducible Demo

const assetUri = 'https://www.example.com/testfile.jpg', 
assetName = 'testfile.jpg';

const downloadResumable = FileSystem.createDownloadResumable(
      assetUri,
      FileSystem.documentDirectory + assetName,
      {},
      downloadProgress => this._downloadProgressHandler(downloadProgress)
);

const { uri } = await downloadResumable.downloadAsync();
await Sharing.shareAsync(uri);

Only the instagram share doesn’t work and you see a bottom sheet with “Send to” as title and placeholder box, a “Search” field and “Share” button and a text “Logged in username”.

**Comment by cruzach** [comment]
Can you provide more info around it not working anymore- did you update the app at all? either with a new IPA from `expo build:ios` or pushing out an ota update (with `expo publish`)?

**Comment by schaetz** [comment]
I have a similar issue. On Android sharing works fine, on iOS the tester got the hardly useful message "Error - Something went wrong" when trying to share on Instagram. Apparently it works fine with all other apps he tried. Unfortunately, I do not own an apple device myself, so it is very hard to reproduce, or even debug at the moment.

Versions:
expo: ^40.0.0
expo-sharing: ~8.5.0

Code:
`        const shareSelectedAsset = async () => {
        const selectedAsset = assets.filter(a => a.number === currentSlide)[0];

        const filename = selectedAsset.url.split('/').slice(-1)[0] || selectedAsset._id;
        const extension = filename.split('.').slice(-1)[0] || 'jpg';
        const mimeType = getMimeType(extension);
        
        const downloadResumable = FileSystem.createDownloadResumable(
            selectedAsset.url,
            FileSystem.documentDirectory + filename,
            {}
        );

        if (!(await Sharing.isAvailableAsync())) {
            alert("Sharing is not supported on your platform.");
            return;
        }

        try {
            const {uri} = await downloadResumable.downloadAsync();
            console.log('Finished downloading to ', uri);
          
            Sharing.shareAsync(uri, {
                mimeType: mimeType,
                dialogTitle: 'Share asset',
                UTI: mimeType
            }).then(() => {
                console.log("Sharing successful"); 
            })
            .catch(() => {
                alert("Sharing error");
            });
        } catch(error) {
            alert("An error occurred while trying to download the file from the server.");
        }
    };`
