### ISSUE TITLE
Linking.makeUrl does not contain -- after export

### ISSUE THREAD

**Issue by itsJASPERr** [expo/expo#10128]
### Summary of Issue 
After exporting an app for hosting on own servers, `Linking.makeUrl("path")` does not contain `--`. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Tested on iOS
```
Expo CLI 3.20.9 environment info:
    System:
      OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.0/bin/npm
    npmPackages:
      expo: ~38.0.8 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.9
```
### Reproducible Demo

https://github.com/itsJASPERr/expo-linking-makeurl-bug
```
git checkout git@github.com:itsJASPERr/expo-linking-makeurl-bug.git
cd expo-linking-makeurl-bug
yarn
yarn start
# see how url contains /--/
``` 
#### To see the bug 
Open in Expo:

iOS:

![image](https://user-images.githubusercontent.com/11521721/92664061-4a95bc80-f303-11ea-84c5-b6ed1ffb2572.png)

Android:

![image](https://user-images.githubusercontent.com/11521721/92664092-5c775f80-f303-11ea-9e41-d33accfc00d0.png)

### Steps to Reproduce
1. use `Linking.makeUrl` in an empty project
2. `expo export --public-url $MYURL`
3. host in gh pages
4. see wrong output 

### Expected Behavior vs Actual Behavior

**Expected Behavior**
`Linking.makeUrl("path")` always creates `$MYURL/--/path`

**Actual Behavior**
- `Linking.makeUrl("path")` creates `$MYURL/--/path` in development and expo published apps.
- `Linking.makeUrl("path")` creates `$MYURL//path` in exported apps

**Comment by barthap** [comment]
AFAIK, those URLs contain the `/--/` only for Expo-hosted links and that's correct behavior. For self-hosted apps this prefix is not added. See how `Linking.makeURL()` handles it:
https://github.com/expo/expo/blob/ec8bdb6c6373f81267f084478412b22151f19686/packages/expo-linking/src/Linking.ts#L137-L139

**Comment by swittk** [comment]
I can second that this behavior occurs.

I believe the behavior of having no /--/ in between the prefix and the path is behaving as intended, however, the Linking module doesn't recognize any events in the published managed app when the "--" part is missing in the app.

Example
````
Linking.addEventListener('url', (e) => {
  console.log('I got a URL event!', e.url)
});

// Opening the link app_prefix://path_1/path_2?_query1=sample1 would not cause the listener to be called at all

// Changing the link to app_prefix://--/path_1/path_2?_query1=sample1 would yield the expected results
````

This still occurs as tested on Expo SDK 40.
