### ISSUE TITLE
OTA Updates crashes app

### ISSUE THREAD

**Issue by special-character** [expo/expo#10121]
## 🐛 Bug Report

I ejected my iOS app and followed the instructions to set up OTA updates but the built app now crashes any time it gets an update and will not recover. The issue appears to be that the bare app gets OTA updates for publishes of a previous version.

### Environment

Targeting iOS only.
```
  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
```

### Reproducible Demo

Don't have one yet but can put one together
 
### Steps to Reproduce

1) Eject an iOS app
2) Follow instructions to set up OTA updates
3) Build new version
4) Publish to a previous version

### Expected Behavior vs Actual Behavior

The new ejected app does not receive the update for the previous version.

Has anyone else ran into this? I [posted on forums](https://forums.expo.io/t/app-gets-ota-updates-for-previous-versions/42623) but haven't seen anything other issues that match this. Am I missing something about bare OTA updates? I made sure they are enabled in my expo.plist but there is no `Updates.manifest` in the app.

I attempted to filter what OTA update gets loaded on the client side but that doesn't work because it will still update in the background when the user closes and opens the app. It might be worth noting that I had this issue starting after I ejected the app. Previously, `checkForUpdateAsync` wouldn't return updates for versions that didn't match the iOS app version

**Comment by brentvatne** [comment]
hi there!

can you elaborate on steps 3 and 4? it's not clear to me what those mean. as much information as necessary would be appreciated

**Comment by special-character** [comment]
Yeah absolutely, thanks for getting back. For step 3, I build a new version of the app (after bumping the patch version) with XCode and upload to the appstore (testing on TestFlight). For step 4 I am publishing the app for a previous version. 

For example the new build was `0.8.9` and my version that I am publishing to is `0.8.4`. When I test out `0.8.9` in TestFlight, the call from `checkForUpdateAsync` says it `isAvailable` but the `manifest.version` does not match `Constants.nativeAppVersion`. 

After `fetchUpdateAsync`, reloading the app crashes and I was guessing that it was the version.

I made sure all the config I have matches exactly from the docs for [installing](https://docs.expo.io/bare/installing-updates/) and for the [expo.plist config](https://github.com/expo/expo/blob/master/packages/expo-updates/README.md):

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EXUpdatesCheckOnLaunch</key>
	<string>ALWAYS</string>
	<key>EXUpdatesEnabled</key>
	<true/>
	<key>EXUpdatesLaunchWaitMs</key>
	<integer>0</integer>
	<key>EXUpdatesSDKVersion</key>
	<string>38.0.0</string>
	<key>EXUpdatesURL</key>
	<string>https://exp.host/@tiltshift/gather-staging</string>
	<key>EXUpdatesReleaseChannel</key>
	<string>staging</string>
</dict>
</plist>
```

**Comment by brentvatne** [comment]
gotcha. so the published `version` doesn't have an impact on whether an update is used - it's entirely based on release channels and sdk versions. if your binary points to sdk 38 and release channel staging, it will get whatever the most recently published release is that matches that criteria. you might want to point to a different release channel.

`Updates.manifest` is empty until a new build is running an update - i think we want to change this though. the reason for this is that the first time you do a build we embed the js and assets in the binary, and we don't generate a manifest. manifests are generated when you run `expo publish` and this isn't needed before running a build. more info in https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf

**Comment by special-character** [comment]
@brentvatne Thanks for the explanation on the manifest, I didn't realize a new build wouldn't have one initially which makes sense. I will try out pointing to a new release channel and build for the ejected app and see how that goes.

I thought that the published version made a difference because there might be additional native code that would make versions incompatible. Is that wrong? i.e. I thought `0.8.9` wouldn't get updates for `0.8.4` because those app versions might have different native code and therefore we couldn't load JS without knowing that.

In general, do you have any tips on debugging for OTA updates like this? It is hard to determine why the app is crashing after an update. It leads me to believe there might be some problem with native code-JS but that is just my next guess.

**Comment by brentvatne** [comment]
> I thought that the published version made a difference because there might be additional native code that would make versions incompatible. Is that wrong? i.e. I thought 0.8.9 wouldn't get updates for 0.8.4 because those app versions might have different native code and therefore we couldn't load JS without knowing that.

the SDK version is the field that is used for specifying native code - check out this flow chart: https://docs.expo.io/workflow/publishing/#what-version-of-the-app-will-my

> In general, do you have any tips on debugging for OTA updates like this? It is hard to determine why the app is crashing after an update. It leads me to believe there might be some problem with native code-JS but that is just my next guess.

based on the flow chart linked to above and your knowledge of what the app binary is pointing to, you can check publish history with `expo publish:history`

```
╰─$ expo publish:history --help

  Usage: publish:history|ph [options] [path]

  Log the project's releases

  Options:

    -c, --release-channel <channel-name>  Filter by release channel. If this flag is not included, the most recent publications will be shown.
    -count, --count <number-of-logs>      Number of logs to view, maximum 100, default 5.
    -p, --platform <ios|android>          Filter by platform, android or ios. Defaults to both platforms.
    -s, --sdk-version <version>           Filter by SDK version e.g. 35.0.0
    -r, --raw                             Produce some raw output.
    --config [file]                       Specify a path to app.json or app.config.js
    -h, --help                            output usage information
```

**Comment by special-character** [comment]
Thanks for the comments, I will do some more reading since I am still fuzzy on how the version of the app can be ignored for updates. I thought I read somewhere in the docs about updates only going to the same app version and wouldn't go to a different one but I guess I am wrong.

One use case that still doesn't make sense is: 

1) app is version `1.0.0` with custom native code. 
2) remove that native code in version `1.0.1`
3) have scripts/CI that publish to `1.0.0`

In that case, if `1.0.1` gets the JS update from `1.0.0`, I would expect it to crash or have fatal errors.

**Comment by brentvatne** [comment]
> I will do some more reading since I am still fuzzy on how the version of the app can be ignored for updates

it's just not factored in at all. it's not even sent to the server when checking for a new update. the app version is purely used by the app store and play store, expo-updates does not care about it. expo-updates sends: the platform (ios/android), the sdk version, and the release channel to our server. the server looks at those parameters and picks the latest update that matches

**Comment by alonroth** [comment]
@brentvatne when do you think the native runtime version could be used under Expo updates server?

**Comment by brentvatne** [comment]
@alonroth - i'm not sure what you mean. this is probably not the best place to discuss, you could post a more detailed question to https://forums.expo.io
