### ISSUE TITLE
[expo-location] Implement "stop on terminate" & make it the default

### ISSUE THREAD

**Issue by alexsegura** [expo/expo#10135]
Other background geolocation libs have a "stop on terminate" option, i.e an option to stop background geolocation when the app is killed. 

- [transistorsoft/react-native-background-geolocation](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#stoponterminate)
- [mauron85/react-native-background-geolocation](https://github.com/mauron85/react-native-background-geolocation#api)

Moreover, those libs have `stopOnTerminate = true` by default, which seems reasonable: currently with `expo-location`, on Android, there is no way to stop the background geolocation service. You have to add a button in the app to stop it, or stop the app via the Android application screen.

---

Right now I have implemented this **UGLY** 🤮 module to have the same behavior

```java
public class StopOnTerminateModule extends ReactContextBaseJavaModule implements LifecycleEventListener {

  private static final String TAG = "StopOnTerminateModule";

  private ReactApplicationContext mContext;

  public StopOnTerminateModule(ReactApplicationContext reactContext) {
    super(reactContext);
    mContext = reactContext;
    reactContext.addLifecycleEventListener(this);
  }

  @Override
  public String getName() {
    return "StopOnTerminate";
  }

  @Override
  public void onHostResume() {
  }

  @Override
  public void onHostPause() {
  }

  @Override
  public void onHostDestroy() {

    Log.d(TAG, "onHostDestroy");

    try {

      Collection<NativeModule> modules = mContext.getCatalystInstance().getNativeModules();

      for (NativeModule module : modules) {

        if (module instanceof NativeModulesProxy) {

          WritableNativeArray arguments = new WritableNativeArray();
          arguments.pushString("location-updates");

          Callback resolve = new Callback() {
            @Override
            public void invoke(Object... args) {
              Log.d(TAG, "Location updates stopped");
            }
          };
          Callback reject = new Callback() {
            @Override
            public void invoke(Object... args) {

            }
          };

          PromiseImpl cb = new PromiseImpl(resolve, reject);

          ((NativeModulesProxy) module).callMethod("ExpoLocation", new DynamicFromObject("stopLocationUpdatesAsync"), arguments, cb);

        }
      }

    } catch (Exception e) {
      Log.e(TAG, "Error while stopping location updates", e);
    }
  }
}

```

**Comment by colbygarland** [comment]
Any updates on this? I am currently trying to emulate this behaviour by returning the stopLocation updates in my useEffect on my app file, which works on Android but not iOS

**Comment by arabold** [comment]
@alexsegura, thanks a lot for your code snippet. This helped me implement the behavior in Android in the meantime. I wonder if and how you solved this for iOS as well? 

Also, I'm 100% in favor of this feature suggestion.

**Comment by alexsegura** [comment]
Still an issue

**Comment by alexandermckay** [comment]
(Docs)[https://docs.expo.dev/versions/latest/sdk/location/#locationtaskserviceoptions]
`killServiceOnDestory`

**Comment by Pjexaf** [comment]
The Issue is still persist.
I tried `stopLocationUpdatesAsync` \ `stopGeofencingAsync` but no luck.

`Location.startLocationUpdatesAsync(GPSTaskName, options)`

```
useEffect(() => {
    const unsubscribeFromLocations = async () => {
      await Location.stopLocationUpdatesAsync(GPSTaskName);
      await Location.stopGeofencingAsync(GPSTaskName);
    };
    return () => {
      unsubscribeFromLocations();
    };
  }, []);
```
This doesnt stop the task. After the app has been killed, the app starts up again and start to send locations. (I can see this from the logs and from the fact that the GPS icon appears again in the status bar). 
Has anyone find a workaround at least?
