### ISSUE TITLE
Where is my mainapplication.java, androidmanifest.xml, build.gradle, etc? (React native)

### ISSUE THREAD

**Issue by Rc85** [expo/expo#1013]
Hi, I'm new to using expo. Some npm modules require me to edit these files but I cannot find them in my project directory. I am using the "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz" for my react native.

The only mainapplication.java is in react-native for HelloWorld template and in react-native-permissions, in my node_modules directory.

**Comment by dikaiosune** [comment]
Hi, I'd recommend reading the [docs for ExpoKit](https://docs.expo.io/versions/latest/guides/detach.html).
