### ISSUE TITLE
Expo Push Notifications in background

### ISSUE THREAD

**Issue by AnishaChhatwani** [expo/expo#10148]
Is there a way to handle an expo push notification when the app is in background? like setNotificationHandler is called when a notification is generated and app is in foreground. I want to do the same thing when the app is in background.
I want this because of real-time updates without using sockets or polling for ex. I just want to update in real time (without refreshing).

**Comment by cruzach** [comment]
Hi! we don't currently support this (I think it's commonly referred to as 'silent notifications')

But we have a feature request you can upvote- https://expo.canny.io/feature-requests/p/handle-push-notifications-in-the-background

In the meantime, you'll need to use the bare workflow to add this feature
