### ISSUE TITLE
[docs] Guide to sending notifications directly with FCM is incomplete/contradictory

### ISSUE THREAD

**Issue by papb** [expo/expo#10142]
Page: https://docs.expo.io/push-notifications/sending-notifications-custom

This page says:

> The Expo platform does not lock you into using Expo's application services

And it goes on to explain how handle it on our own. However, it also says:

> **The `experienceId` field is required,** otherwise your notifications will not go through to your app.

Also according to that page, this `experienceId` is a string of the form `'@yourExpoUsername/yourProjectSlug'`. However, I don't have an expo account. So how can I use this? The docs are either contradictory or incomplete. I am trying to make this work without being locked into Expo's services.

**Comment by papb** [comment]
And I just found out that @awinograd [figured it out](https://github.com/expo/expo/issues/3411#issuecomment-461683210)! One must use `@anonymous/project-slug`  in that case.

I also found that we can get this via code by looking at `Constants.manifest.id` from the `expo-constants` package.

**Comment by cruzach** [comment]
By 
>The Expo platform does not lock you into using Expo's application services

we mean that using Expo doesn't mean you **have** to use the Expo notification service- you can use any notification service you want. However, you're correct that you do need an Expo account (the workaround you provided _will_ work, but I would recommend just creating an Expo account instead)
