### ISSUE TITLE
Clarify: `Updates.updateId`, `manifest.releaseId`, and expo publish:history's `publicationId`

### ISSUE THREAD

**Issue by gregfenton** [expo/expo#10140]
In the docs for [Updates.updateId](https://docs.expo.io/versions/v38.0.0/sdk/updates/#updatesupdateid), it describes the value as being a UUID but does not describe where that value comes from.  I am not seeing `updateId` described elsewhere in the Expo ecosystem.  Where does that UUID come from and what does it represent?  Does this refer to the `publicationId` seen in the output of `expo publish:history`?

A description or a link to further reading would be useful in this section of the docs.

**Comment by cruzach** [comment]
that should be the same as `releaseId` and `publicationId`

I'm changing the title of this issue to reflect that we should probably rename these in order to be consistent
