### ISSUE TITLE
iOS: Clear data from expo client

### ISSUE THREAD

**Issue by baw** [expo/expo#1015]
Is there anyway to delete the data (AsyncStorage in particular) for a particular project without deleting the data for other projects or changing the values in app.json?

**Comment by jesseruder** [comment]
On Android you can touch the app name in the Expo notification and then do "Clear Data". There's not a way to do this on iOS right now.

**Comment by sadan** [comment]
any command or any other thing to clear data on iOS???

**Comment by cowai** [comment]
+1

**Comment by colinwong** [comment]
+1

**Comment by baw** [comment]
If you store your data in AsyncStorage, you can put AsyncStorage.[clear](https://facebook.github.io/react-native/docs/asyncstorage.html#clear)() in your app and when you reload the app all the data will be deleted. This works ok for development, but has issues if you wanted to clear data on a published app you are using.

**Comment by ecstasy2** [comment]
+1
I sometime put an app data that I am developing in an invalid state which causes it to throw an exection and make it unusable. When that happen, the only way I can get the app to work again is to delete the Expo app and re-install. On Android I can clear the app data in the system setting, but not on iOS. It would be nice to be able to clear my app data from the expo menu.

**Comment by nicknovitski** [comment]
We think this is a good idea for a feature, and we've added it to our internal ticketing system.

**Comment by finekost** [comment]
any news on this one?

**Comment by jaulz** [comment]
Maybe it would make sense to add that option to the settings bundle so we would have that option for standalone apps as well?

**Comment by hszeto** [comment]
any news or update?

**Comment by tacomanator** [comment]
This would be a great feature, for documents as well. It's really difficult to test standalone app asset bundling and caching and such right now. I haven't figured out a reliable way to get Expo to remove documents, save for "debugging" code to delete each one manually or deleting and reinstalling expo.

**Comment by GitHubGreg** [comment]
Would love to have this as well, thanks.

**Comment by AdamJNavarro** [comment]
Hey all,

Closing this issue in favor of the Feature Request on Canny: https://expo.canny.io/feature-requests/p/clear-all-project-state-on-the-device
