### ISSUE TITLE
Expo publishing new APK into Playstore

### ISSUE THREAD

**Issue by mrodrigs** [expo/expo#10152]
Yesterday I generated a new APK of my app for local testing purposes, but it seems that it also "automaticly uploaded" this new APK into Playstore without my concern(I made sure accessing the playstore and the last update was months ago).

Whoever downloads the app from Playstore, on the second time he opens the app, it will be the App from yesterday build. How could it happen? I don't remember about enabling some kind of "on air updates" for this app.

**Comment by GabiruRyo** [comment]
Same here.

**Comment by cruzach** [comment]
OTA updates are automatically enabled in Expo apps, and whenever you run `expo build`, `expo publish` is run as part of that build process. [Release channels](https://docs.expo.io/distribution/release-channels/) are a really useful feature to avoid accidentally publishing to your production app

**Comment by mrodrigs** [comment]
Thanks a lot, I believe it should be well described on the bulding standalone apps session: https://docs.expo.io/distribution/building-standalone-apps/

**Comment by cruzach** [comment]
yep, I agree- I'll add that now!
