### ISSUE TITLE
Expo Location - Background Location Methods don't work in web and throws 'is not a function error'

### ISSUE THREAD

**Issue by sachinkoru** [expo/expo#10156]
### Summary of Issue 
The following background location methods throw a runtime 'is not a function error' when running on the web

`Location.startGeofencingAsync(taskName, regions)`
`Location.stopGeofencingAsync(taskName)`
`Location.hasStartedGeofencingAsync(taskName)`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```bash
  Expo CLI 3.27.4 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
      Yarn: 1.22.5 - ~/.nvm/versions/node/v10.20.1/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: managed
```

### Reproducible Demo

The example snippet from the docs trigger it on web
https://docs.expo.io/versions/v38.0.0/sdk/task-manager/#example
 
### Steps to Reproduce
As mentioned in the previous step, just running the example snippet from the docs on web triggers the error

### Expected Behavior vs Actual Behavior
Expected Behavior-
Background location methods should either work as intended or throw a better error (not implemented on web) when running on web

Actual Behavior -
Cryptic 'is not a function error' is thrown

**Comment by AdamJNavarro** [comment]
Hey @sachinkoru,

As the Platform Compatibility table indicates, `TaskManager` is not supported on Web so this expected behavior. https://docs.expo.io/versions/v38.0.0/sdk/task-manager/

Cheers,
Adam
