### ISSUE TITLE
expo-av : Player is accessed on the wrong thread (APK only)

### ISSUE THREAD

**Issue by Narduzzi** [expo/expo#10169]
### Summary of Issue

Hello,

I would like to keep the progress of a video from one screen to the other.
I want the video to play in a screen, and only play the audio of the corresponding video in the second screen.
My solution works fine in development mode, but when I try to build the APK, I run into the following issue:
`Player is accessed on the wrong thread`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

 Expo CLI 3.27.3 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      expo: ~38.0.8 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.3
    Expo Workflow: managed

Target : 
   System:
      OS: Android 9.0

### Reproducible Demo

Code is available in [this repository](https://github.com/Narduzzi/talk-bug).
 
### Steps to Reproduce

```bash

git clone https://github.com/Narduzzi/talk-bug
cd talk-bug/demo-app
npm install
npm start // should work fine at this point

expo build:android 
adb install [build artefact]
```

### Expected Behavior vs Actual Behavior

The sound starts on the first screen, but when going to the video screen, the app crashes with error:
`Player is accessed on the wrong thread`.

Only happens when compile to APK.

**Comment by Narduzzi** [comment]
Any update on this please?

**Comment by Narduzzi** [comment]
expo-av not fully supported for Vue Native. Migrating the project to React-Native solved the bug.

**Comment by amorimcode** [comment]
how to solve it on expo sdk 51?

**Comment by amorimcode** [comment]
switched to react-native-video with expo plugin
