### ISSUE TITLE
I can't give start date to local notification and repeat daily,,, there are only option in trigger for repeating 

### ISSUE THREAD

**Issue by seda1094** [expo/expo#10164]
### Please note that discussions opened as issues in the core Expo repository will be closed.

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂

**Comment by AdamJNavarro** [comment]
Hey @seda1094,

As the template said, please create a forum post so we can address your question. We try to reserve Github issues for reproducible and actionable bug reports.

Cheers,
Adam
