### ISSUE TITLE
[docs] expo payments stripe cannot read property init of undefined

### ISSUE THREAD

**Issue by ajkhatibi** [expo/expo#10166]
So it seems that there is something missing for the installation of the expo payments stripe module. When trying to initialize it I get an error that looks like this 👇And this is after following the instructions in the expo documentation which is just the "expo install ..." and the "npx pod-install". I'm assuming that none of the installations belonging to the tipsi documentation will work for this module. Does anything come across this before? Any suggestions? Is there a missing step? Thanks folks
![Simulator Screen Shot - iPhone 11 - 2020-09-12 at 17 10 17](https://user-images.githubusercontent.com/17955378/93007199-de8da100-f51a-11ea-877b-166a25cbd805.png)

**Comment by AdamJNavarro** [comment]
Hey @ajkhatibi,

Based on the error it seems like the module is not present. Can you make sure the appropriate files are present in your `ios/Pods/` directory. Also, can you let me know how you are going about running your code?

Cheers,
Adam

**Comment by MaazF94** [comment]
I have the same issue and I can confirm that Stripe is located under the ios/Pods/ directory. Here's what I have:

`const [walletPayEnabled, setWalletPayEnabled] = useState(false);
  useEffect(() => {
    async function checkDevice() {
      if(Stripe){
        console.log(Stripe)
        canUseWallet = await Stripe.deviceSupportsNativePayAsync();
      }
    }
    try {
      let canUseWallet = false;
      
      Stripe.setOptionsAsync({
        publishableKey:
          "{myPublicKey}",
        // androidPayMode: "test",
      });

      checkDevice();

      if(walletPayEnabled !== canUseWallet){
        setWalletPayEnabled(canUseWallet);
      }
    } catch (e) {
      console.log(e);
    }
  }, []);`
