### ISSUE TITLE
Dark Mode isn't working in Expo iOS client

### ISSUE THREAD

**Issue by filiptronicek** [expo/expo#10165]
### Summary of Issue 
When trying to get the preferred appearance with the Appearance module from `react-native`, it for some reason never changes from the `light` value when accessing `Appearance.getColorScheme()`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.27.4 environment info:
    System:
      OS: Windows 10 10.0.20206
    Binaries:
      Node: 14.10.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.2 - F:\Programy\yarm\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^38.0.10 => 38.0.10
      react: ^16.11.0 => 16.11.0
      react-dom: ^16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ^0.11.7 => 0.11.7
    Expo Workflow: managed
```
Tried on:
| Device name | Platform | OS version |
|--------------|----------|------------|
| iPhone Xs | via Expo client | iOS 14 developer beta 7 |
| Samsung Galaxy S20+ | Signed APK | Android v10 |

### Reproducible Demo
Just output 
```js
import { Appearance } from 'react-native';

Appearance.getColorScheme();
```

### Expected Behavior vs Actual Behavior
When I have dark mode enabled, I want to see the `dark` value returned, so I can implement dark mode features.

**Comment by filiptronicek** [comment]
Update:
it seems, that even if I build the app to a .apk, it still outputs `light`

Demo on Samsung Galaxy S20+ (Android 10): (with dark mode enabled, as obvious from the dark keyboard)
![image](https://user-images.githubusercontent.com/29888641/93005241-87ee8a00-f54f-11ea-89bd-cb8407bb5dcd.png)

**Comment by brentvatne** [comment]
it's locked to light by default, you can enable "automatic" mode in app.json https://docs.expo.io/versions/v38.0.0/config/app/#userinterfacestyle

**Comment by Slapbox** [comment]
@brentvatne what's the rationale for that choice? It seems odd. I don't think that's mentioned anywhere in the Appearance docs right now. Am I mistaken?

https://docs.expo.io/versions/latest/react-native/appearance/

If I'm not overlooking it, let me know and I'll submit a PR.

**Comment by brentvatne** [comment]
compatibility with existing apps

https://docs.expo.io/versions/v39.0.0/sdk/appearance/#configuration
