### ISSUE TITLE
async not working

### ISSUE THREAD

**Issue by mlukasch** [expo/expo#1016]
Hello, Im getting this error because of Font.loadAsync
It uses async and Im getting this error:
![bildschirmfoto 2017-11-28 um 12 06 45](https://user-images.githubusercontent.com/17597578/33316646-eeab47fe-d434-11e7-8ee5-719a56e263b0.png)
Would appreciate help since Im on time pressure.
Thanks

**Comment by fxfactorial** [comment]
Can you share your code of how you're using `Font.loadAsync`, and your `package.json`, and `.babelrc`

**Comment by mlukasch** [comment]
Thanks I solved it by creating a new create react native app and copying manually the .babelrc file and package.json entries

**Comment by mlukasch** [comment]
Into the "old" project created last friday. There have been some upgrades apparently.

**Comment by mlukasch** [comment]
Into the "old" project created last friday. There have been some upgrades apparently.
