### ISSUE TITLE
When is SDK 39 coming?

### ISSUE THREAD

**Issue by avin-kavish** [expo/expo#10161]
I have a dependency that says it will only work on 39 and higher.

**Comment by vpicone** [comment]
You can check the the umbrella issues here: https://github.com/expo/expo/issues/9850

**Comment by vpicone** [comment]
Also, this is discussed in [their SDK 39 roadmap blog](https://blog.expo.io/the-expo-sdk-39-roadmap-36bf5137e8db):



> ### SDK 39 Release Date
> We’re targeting sometime in September to release SDK 39. We don’t yet have an exact date and are also waiting to learn the iOS 14 release date so we can coordinate SDK 39 to come out on time.

> In general, we’ve been releasing new SDKs roughly once a quarter. This has been working well so we plan to keep this approximate cadence for SDKs in the future.
```

**Comment by cruzach** [comment]
What dependency says it will only work on SDK 39 or higher?

**Comment by avin-kavish** [comment]
https://github.com/LinusU/react-native-get-random-values

**Comment by avin-kavish** [comment]
@vpicone so basically it comes out when the issues listed on that ticket are crossed off?

**Comment by brentvatne** [comment]
we don't commit to exact dates, but we're working to release it sometime in the next couple of weeks assuming nothing changes

**Comment by jeffzh4ng** [comment]
@brentvatne I'm a web developer who's new to RN development. Are apps built with Expo SDK 38 currently broken on iOS 14?

**Comment by brentvatne** [comment]
@jeffzh4ng no

**Comment by jeffzh4ng** [comment]
@brentvatne Ah I took a closer read to https://blog.expo.io/the-expo-sdk-39-roadmap-36bf5137e8db. I guess the correct way of thinking of this is that SDK 39 will make better use of iOS14 features? For ex, LED privacy indicators.
