### ISSUE TITLE
[docs] expo-auth-session providers

### ISSUE THREAD

**Issue by humbertocruz** [expo/expo#10178]
I was trying to implement facebook and google auth following https://docs.expo.io/guides/authentication/ but on facebook and google guides we have to import: "import * as Facebook from 'expo-auth-session/providers/facebook';" and "import * as Google from 'expo-auth-session/providers/google';" but the package expo-auth-session version 1.4.1 ( latest ) does no have the providers folder. I found it on expo repository inside packages folders and on the sdk39 branch ( actual sdk38  dont have this folder too ).
I am trying to download the master expo branch and put the package expo-app-session manualy in the node_modules folder, this will work ? the repo is very large to download just got 12% until now on 400mbits connection.
Thanks

**Comment by abdullah-abunada** [comment]
1 - You can fork it, then download its zip, finally update the required changes at your repo and publish the edited package personally at npm.
2- download the personal package at your project at use it instead of expo one until skd39 released.

**Comment by byCedric** [comment]
Hi @humbertocruz! We have released the version using the `next` tag (`1.5.0`). cc @EvanBacon, can we switch this to latest? You can manually install this version by running either:

- `$ yarn add expo-auth-session@next`
- `$ npm install --save expo-auth-session@next`

Luckily, this package is a JS only dependency and doesn't include any native code. Which means, this should also work fine in older Expo SDKs or Expo Clients. You will get warnings about "newer packages installed than recommended", we hope to get this resolved ASAP (definitely with SDK 39 😄).

Hope this helps!

**Comment by humbertocruz** [comment]
Thanks, version 1.5.0 works with a few changes on my SDK38 project. I had to add expo-random in expo-auth-session/node_modules and webview didn't work but it open a normal webbrowser to auth and return to the app. 
Thanks
