### ISSUE TITLE
Notification not working in production

### ISSUE THREAD

**Issue by lslv1243** [expo/expo#1017]
I am having a problem with the expo notification. It works in development but does not work in production. Is there something I am missing?

I am testing on iOS.

Here is my app.json:
```
{
  "expo": {
    "name": "Thinkng",
    "icon": "./icon.png",
    "version": "1.0.0",
    "sdkVersion": "21.0.0",
    "slug": "thinkng",
    "orientation": "portrait",
    "ios": {
      "bundleIdentifier": "com.thinkr.thinkng"
    }
  }
}
```

**Comment by jesseruder** [comment]
By "production" do you mean a standalone app? And how are you installing the IPA to test?

**Comment by lslv1243** [comment]
Yes, it is a standalone app. I install it though TestFlight.

**Comment by Tyldar** [comment]
I have the same issue.

I build the application through "exp build:ios" then submit to TestFlight with Application Loader.
Application in dev mode (like running on iPhone plugged to the computer) works fine and notifications are received.

In production, I get the error "The recipient isn’t associated with any device"

Thanks

**Comment by AdamJNavarro** [comment]
Hey @Tyldar,

Sorry for this inconvenience. We've gotten a couple other reports of iOS push notifications not working properly. To help us figure out the root of the problem, can you let me know what SDK your app is running?

**Comment by justinobney** [comment]
I am having the same issue.

Platform Tested:
iPhone X

app.json:
`"sdkVersion": "25.0.0",`

package.json:
```
"react": "16.2.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
```

code in question:
```
Notifications.addListener(notification => {
  alertWithType('info', 'Notification', notification.origin);
});
```

When in expo app:
- Notification is received
- Listener callback runs and shows alert

When in stand-alone app installed via TestFlight:
- Notification is received
- Listener callback DOES NOT RUN

**Comment by terribleben** [comment]
https://status.expo.io/incidents/z2761rqdd4w1

**Comment by justinobney** [comment]
@terribleben Does this cover my issue as well? My device DOES receive the notification, but the callback in `Notifications.addListener(notification => {...})` does not run.

**Comment by ide** [comment]
@justinobney The incident above doesn't cover your issue. If you are affected by the linked incident, you'll get an error from the server when sending a notification (more details on the incident page).

**Comment by terribleben** [comment]
Closing because the incident was resolved last week. If you find this thread, and have a similarly generic symptom ("notification not working in production"), then please open a new issue. We added an issue template that will help provide some diagnostic information for future reports.
