### ISSUE TITLE
couldn't start project on android: error running adb:

### ISSUE THREAD

**Issue by boualizakaria** [expo/expo#10176]
when i run npm start command to run my app on android emulator this error appears

couldn't` start project on android: error running adb: error running app. error: activity not started, unable to resolve intent { act=android.intent.action.view dat=exp://192.168.1.2:19000 flg=0x10000000 }

**Comment by cruzach** [comment]
hi, I think reading through [this issue](https://github.com/expo/expo-cli/issues/694) will probably help you in debugging 👍 

If that doesn't help, and you believe this is a bug with expo-cli, please fill out the full bug report template, thanks!
