### ISSUE TITLE
After ejection, by default, iOS app does not render properly on Ipad

### ISSUE THREAD

**Issue by slorber** [expo/expo#1018]
The Expo client app does work nicely on Ipad, so after ejecting, it seems natural to expect the same behavior from ejected app (particularly if it has `"supportsTablet": true`).

This is not the case by default because the target device is iPhone instead of Universal

I think it makes sense to use Universal target by default

![image](https://user-images.githubusercontent.com/749374/33323004-69a91a2e-d44b-11e7-8124-b7409aee83f9.png)

**Comment by terribleben** [comment]
Thanks for the report. This is a limitation with how we render the detached project right now, but I agree we should do a better job rendering the device family setting, or at a minimum print a clearer warning explaining what's going on. For now I am going to close this as a duplicate of https://github.com/expo/expo/issues/444

**Comment by slorber** [comment]
as you didn't close I'll do it
