### ISSUE TITLE
[docs] Differentiate new and legacy notification methods in unversioned pages

### ISSUE THREAD

**Issue by Svarto** [expo/expo#10189]
The documentation is not consistent on notification setup and uses an (I assume) old command "createChannelAndroidAsync".

The old / not updated part of the documentation is here, see the last part of the code:
https://docs.expo.io/push-notifications/push-notifications-setup/

This is the old code, bold the old stuff:
```
  if (Platform.OS === 'android') {
    Notifications.**createChannelAndroidAsync**('default', {
      name: 'default',
      sound: true,
      **priority: 'max',**
      vibrate: [0, 250, 250, 250],
    });
  }
```
It should be this, I think according to other parts of the docs and what I have found works:
```
  if (Platform.OS === 'android') {
    Notifications.**setNotificationChannelAsync**('default', {
      name: 'default',
      **importance: Notifications.AndroidImportance.MAX,**
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });

```

**Comment by AdamJNavarro** [comment]
Hey @Svarto,

Thanks for bringing this to our attention. You're correct that it references the old method that is to be used with the `LegacyNotifications` module. There's some nuance to be handled here as with our docs, only the API Reference is versioned. So we'll have to make sure we provide both ways until the Legacy module is no longer supported.

I'm going to rename this issue to better reflect what needs to be changed here.

**Comment by byCedric** [comment]
A really good example that might help with this, is the usage of tabs. Just like the [functional vs class components](https://reactnative.dev/docs/accessibilityinfo#example) in the react native docs.
