### ISSUE TITLE
Android SDK 29 for Expo SDK 35

### ISSUE THREAD

**Issue by teeolendo** [expo/expo#10197]
I have a project that I built using Expo a few years ago. Since that time, I have had to be make minor changes every so often and pushed new releases, I think the project started way back in Expo SDK 16. My main challenge is that I need to publish the Android app and I can't because Play Store requires Android SDK 29 moving forward. The fix for this is only available in Expo SDK 38 #9446 . If we upgrade to Expo SDK 38, our whole system breaks. I can't even run the application if I try that.  

The app works just fine in Expo SDK 35 though. On the backend of this, I know this is a single line of code inside of the the Android project but I don't have access to the backend. What is a single line of code is weeks for a rewrite that the client will not pay for. We published the ios appand I'm afraid we can't keep the client as we have a strict deadline. The app needs to be ready yesterday. I'm at wits end. Ejecting isn't an option cause that will take time for us to stabilize the Android build. Is there no way around this?

**Comment by byCedric** [comment]
The only option left, if you rule out both the Bare workflow and upgrading, is to [setup an older version of Turtle yourself](https://github.com/expo/turtle). By doing that you manage the code we use for the build service, and keep it on SDK 35. 

But that being said, it still doesn't help you upgrading Android to SDK 29. The only option here is to use the Bare workflow and manually [change React Native to Android 29](https://stackoverflow.com/questions/50368371/react-native-change-targeted-sdk-version-for-play-store-upload).

Hope this helps!
