### ISSUE TITLE
[expo-apple-authentication] Project crashes when building for mac catalyst in Xcode 12 GM seed

### ISSUE THREAD

**Issue by cuttlas** [expo/expo#10198]
### Summary of Issue 

We have a running iOS application with a working implementation of Apple Sign In that we are try to make it work with Mac Catalyst. This library worked perfectly while developing with Xcode 12 Beta, but now that the stable Xcode 12 is out, we are getting the following error when trying to build our app:

![Screenshot 2020-09-16 at 13 03 33](https://user-images.githubusercontent.com/1228574/93330787-a094c380-f81f-11ea-91d3-c1e4e74aeafc.png)

I'm not sure if this is an issue with this library or with the latest Xcode version. Is there something that can be done? Thanks.

**Comment by mezod** [comment]
We hit the very same wall. A colleague found https://developer.apple.com/documentation/authenticationservices/asauthorizationproviderauthorizationoperation?language=objc which shows "Availability for Mac Catalyst 14.0 Beta". We aren't sure about that Beta there, it's like they removed it from the API on the xcode Gold Master :?

**Comment by cuttlas** [comment]
We get confirmation from Apple that "ASAuthorizationProviderAuthorizationOperation" will be added to Catalyst on macOS 11 Big Sur which will be released soon. Therefore, the current version of expo-apple-authentication is not compatible with macOS Catalina (or older).

**Comment by cruzach** [comment]
Unfortunately Expo doesn't support writing apps for Mac Catalyst yet ([here's the relevant feature request](https://expo.canny.io/feature-requests/p/support-for-ios-marzipanproject-catalyst-apps-that-can-run-on-macos) so you can upvote it)

We don't have tests for Mac Catalyst, nor do we perform QA against it, but we are more than happy to review any PRs submitted to fix issues like this one, so please feel free to do so and request a review 😄

For the time being, it looks like the best solution here is to upgrade to Big Sur
