### ISSUE TITLE
Location.watchPositionAsync() - timeInterval option is not working

### ISSUE THREAD

**Issue by ZachThomasAU** [expo/expo#10196]
### Summary of Issue
When using the `Location.watchPositionAsync` method, if you input a `timeInterval` option the callback function will never update. If you input both a `timeInterval` and a `distanceInterval` it seems like the `timeInterval` is ignored entirely. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.27.4 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^38.0.10 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed

Targeting both iOS and Android, tested on iOS 13.5.1.

### Reproducible Demo
````javascript
await Location.watchPositionAsync(
  {
    accuracy: Location.Accuracy.BestForNavigation,
    timeInterval: 1000,
    // distanceInterval: 0,  
   },
  (loc) => {console.log(loc)}
)
````
 
### Steps to Reproduce

- If you run the above 'Reproducible Demo' you should see your app print your location into the console once (or sometimes twice for a possibly unrelated bug) and then never update your location again. 
- If you comment out the `timeInterval` option you should experience the same behaviour. 
- If you enable the `distanceInterval` option you should now experience a regular stream of location updates into your console (the expected behaviour). 
- If you enable both the `timeInterval` and `distanceInterval` options you should experience the same behaviour as having only the `distanceInterval` option enabled.
- If you play with the `distanceInterval` values the option appears to behave as expected.

### Expected Behavior vs Actual Behavior
I would expect that when `timeInterval` is set to 1000 I experience a location update every one second. Instead it seems that the `timeInterval` option does nothing, behaving the same way as if I had not set the option at all.

**Comment by blazejczyk** [comment]
I can confirm the problem exists. The same happens with Expo 39 (tested on Android).

But... @ZachThomasAU - as far as I know, the timeInterval option works only for Android so if your target is iOS too then I'm not sure if you should use it. Also, if you tested this on iOS, it won't work there.

**Comment by dhcmega** [comment]
Hi
It's not working for me too. All tests on Android. timeInterval is ignored.
Thanks

**Comment by ShindoSensei** [comment]
Hi,

Tested on IOS too, timeinterval ignored for sure. The moment i put distanceinterval in it just works.

**Comment by Leo-mahesh** [comment]
I am also having the same issue, I am trying to get users latitude and longitude every 10 second but it's not behaving as I thought,

 `const LocationSetting = {
     accuracy: Location.Accuracy.High,
      timeInterval: 10000,
   };`

    `  let location = await Location.watchPositionAsync(
        LocationSetting,
        (location) => {
          setLocation(location);
        }`

**Comment by dhcmega** [comment]
Hi, no news on this?
Thanks

**Comment by dhcmega** [comment]
Hi @KatancicDenisz, in my case, I'm using background location without maps, so it's not my situation. thanks!

**Comment by KatancicDenisz** [comment]
> Hi @KatancicDenisz, in my case, I'm using background location without maps, so it's not my situation. thanks!

Than no idea, I have issues with watchposition too, but I still haven't found a decent example :/

**Comment by zachdixon** [comment]
Also having this issue in react-native-web. Seems to be called every 3-4 seconds despite increasing the `timeInterval` option

**Comment by wanderer878** [comment]
So I found a solution (type of !!)  , using distance and time interval both can skip the time interval , use distance ONLY or use time interval ONLY.

**Comment by dhcmega** [comment]
@wanderer878 hi, thanks for sharing. can you post and example? I'm not sure I fully understand what you mean. thanks!

**Comment by wanderer878** [comment]
![image](https://user-images.githubusercontent.com/91022829/133970960-c0d8eeba-d2a5-4c5c-9f61-e0833bce65ed.png)

**Comment by wanderer878** [comment]
> @wanderer878 hi, thanks for sharing. can you post and example? I'm not sure I fully understand what you mean. thanks!

![image](https://user-images.githubusercontent.com/91022829/133971075-4c69018b-2984-4757-bd4b-80430803488b.png)

**Comment by danielkv** [comment]
I'm having a similar issue, but for me it's the other way arround. The **distanceInterval** does not work, even if I comment **timeInterval**. At least on react-native-web

**Comment by danielkv** [comment]
> Have anyone tested it on SDK44? I'm still on SDK43.

I have already upgraded to SDK44, but did not test it specifically.

**Comment by dhcmega** [comment]
I think I will just use "distanceInterval" + a function that uses setTimeout 60secs to request the last location y if the user is no moving, thus, not sending new locations.

**Comment by danielkv** [comment]
Not sure it's solved, I'm not using rn for now, if someone can take a look and test it

**Comment by Cleymi** [comment]
Hola tengo el mismo problema, no funciona el intervalo de tiempos

**Comment by chakafasano88** [comment]
I am having the same issue and experiencing odd behavior. It appears that the default interval is 15 seconds. When I try to set the interval to another value it ignores and persists to tick at the default of 15 seconds.  
```
await startLocationUpdatesAsync(BACKGROUND_TASK_LOCATION_FETCH, {
   accuracy: Location.Accuracy.Balanced,
   timeInterval: 30000,
});

**Comment by R3D347HR4Y** [comment]
Still an issue in SDK 48, i believe both arguments do nothing on android at least
I just use a setInterval, with getCurrentPosition for the time being but it's not optimal

**Comment by iamwintrow** [comment]
Yeah, I'm still having this same issue. Using timeInterval in startLocationUpdatesAsync for background location does absolutely nothing. It fires once on the very first time when the app loads, and then never again. There is no interval at all; I wish I was having the previously mentioned problem where it was only updating every 15 seconds.

Any updates on this issue yet?

**Comment by da45** [comment]
expo sdk 49 still  not working !!

**Comment by markandrewcolocado** [comment]
> expo sdk 49 still not working !!

Can confirm this

**Comment by metalogica** [comment]
Did anyone manage to get this to work properly?

**Comment by dhcmega** [comment]
We just use distanceInterval + a timeout to manually check after 30secs of no new location.

**Comment by danmatlam** [comment]
Timeouts don't work because this task runs in the background. What worked for me was using the timestamp of each event to calculate the elapsed time
`let lastTimestamp: number | null = null;
let accumulatedTime: number = 0;

// 🚀 Define the task to handle location updates.
TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }: ITaskResponse) => {
    if (error) {
        // 🔴 Log errors if any occur while fetching location data.
        console.error(`Error fetching location: ${error.message}`);
        return;
    }
    if (data) {
        const { locations } = data;
        const { timestamp } = locations[0];

        if (lastTimestamp !== null) {
            // ⏰ Calculate the time difference between current and last timestamp.
            const timeDifference = (timestamp - lastTimestamp) / 1000;
            accumulatedTime += timeDifference;
            console.log({
                timeDifference: timeDifference.toFixed(1),
                accumulatedTime: accumulatedTime.toFixed(1),
            });

            // 📈 Check if accumulated time has reached or exceeded 60 seconds.
            if (accumulatedTime >= 60) {
                console.log('🎉 Reached 60 seconds! Sending data to server...');
                // Here, we'd trigger the logic to send data to the server.

                // 🔧 Adjust the accumulated time for any excess beyond 60 seconds.
                accumulatedTime -= 60;
            }
        }

        // 🔄 Update last timestamp for the next comparison.
        lastTimestamp = timestamp;
    }
});`

**Comment by danmatlam** [comment]
Timeouts don't work because this task runs in the background. What worked for me was using the timestamp of each event to calculate the elapsed time

```
let lastTimestamp: number | null = null;
let accumulatedTime: number = 0;

// 🚀 Define the task to handle location updates.
TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }: ITaskResponse) => {
    if (error) {
        // 🔴 Log errors if any occur while fetching location data.
        console.error(`Error fetching location: ${error.message}`);
        return;
    }
    if (data) {
        const { locations } = data;
        const { timestamp } = locations[0];

        if (lastTimestamp !== null) {
            // ⏰ Calculate the time difference between current and last timestamp.
            const timeDifference = (timestamp - lastTimestamp) / 1000;
            accumulatedTime += timeDifference;
            console.log({
                timeDifference: timeDifference.toFixed(1),
                accumulatedTime: accumulatedTime.toFixed(1),
            });

            // 📈 Check if accumulated time has reached or exceeded 60 seconds.
            if (accumulatedTime >= 60) {
                console.log('🎉 Reached 60 seconds! Sending data to server...');
                // Here, we'd trigger the logic to send data to the server.

                // 🔧 Adjust the accumulated time for any excess beyond 60 seconds.
                accumulatedTime -= 60;
            }
        }

        // 🔄 Update last timestamp for the next comparison.
        lastTimestamp = timestamp;
    }
});
```

**Comment by PaulSong213** [comment]
SDK 51 working on my end. But it triggers 3-5 times in timeInterval
