### ISSUE TITLE
Expo Push Notification  foreground is not working and notification.request.content console not shows any data

### ISSUE THREAD

**Issue by Anjani-prog** [expo/expo#10199]
### Reproducible Demo
https://snack.expo.io/

**Comment by byCedric** [comment]
Hi @Anjani-prog, thanks for the issue but without info/context and repro we can't do much to help you. If you think this is an issue with Expo, and not with your account (e.g. forgot to setup [Apple](https://docs.expo.io/push-notifications/push-notifications-setup/) or [Google](https://docs.expo.io/push-notifications/using-fcm/) credentials), please open a new issue with the questions from the template.
