### ISSUE TITLE
Multiple results with Location

### ISSUE THREAD

**Issue by allpwrfulroot** [expo/expo#102]
Location.watchPositionAsync is firing off four results immediately upon starting, regardless of distanceInterval or timeInterval. 'Mounted!' only appears once.

It's causing a few side effects in my app, am I doing something wrong or is there a bug in watchPositionAsync? 

```
componentDidMount() {
    console.log('Mounted!')
    Location.watchPositionAsync({
      enableHighAccuracy: false,
      distanceInterval: 800,
      timeInterval: 2000
    }, result => {
      console.log('result: ', result)
    })
  }
```

**Comment by terribleben** [comment]
cc @nikki93

**Comment by allpwrfulroot** [comment]
Been working with this obsessively, and the watchPositionAsync callback will explode (a counter will go into the hundreds in seconds) if Location.getCurrentPosition is also called in the same component? 

I think a lot of people are setting up low-accuracy location watches and then trying to verify changes with a getCurrentPosition({ enableHighAccuracy: true }) call as needed. Does anyone have some best practices for how this should work?

**Comment by nikki93** [comment]
@allpwrfulroot which platform do you have this happen on (iOS / Android)? If you have a minimal repro case that would be useful too but it seems like this can be repro'd with just the blank app then adding the code you wrote in `componentDidMount()`?

**Comment by allpwrfulroot** [comment]
Should happen if you set up a geolocation watch in componentWillMount/componentDidMount and then have a button that tries to also get the current location. Sorry, in transit today or would write a gist :/

**Comment by nikki93** [comment]
@allpwrfulroot we do this with separate `CLLocationManager` watches on iOS, and as it turns out, adding a `CLLocationManager` watch will trigger other watches too. So this interference is happening at the OS level. Do you think you can account for it at the app level or does it not make sense to? You can also jump on our slack at slack.expo.io and ping me (I'm 'nikki' on there) to discuss quicker.

**Comment by nikki93** [comment]
So the interference across watches and gets is due to the OS-level, not much we can do there unless we do a complex implementation. So going to deprioritize this for now, but open to more discussion.

**Comment by mlg87** [comment]
@akashbdj im doing something very similar with it seeming to only fire 3 times. im thinking that ill just write a timeout to call `getCurrentPosition` at the interval (5000 in my case) i need to get the desired effect

**Comment by mlg87** [comment]
@nikki93 do you know why `watchPositionAsync` would call the callback only three times?

**Comment by CSamuelLents** [comment]
In case anyone has this issue in the future - I was able to get around it with a simple debounce. For example:

```
    Location.watchPositionAsync(
      {
        enableHighAccuracy: true,
        timeInterval: 30000,
        distanceInterval: 150,
      },
      debounce(newLocation => updateLocation(newLocation), 5000, { leading: true })
    );
```

For the record, that's using the debounce function from lodash. If you're curious about the params, the documentation can be found [here](https://lodash.com/docs/#debounce). A little hacky maybe, but it works.

**Comment by sjchmiela** [comment]
I think debouncing the watcher is a good solution if you want to be sure that the location won't be updated too frequently. I've just submitted a pull request that will solve misconceptions by adding `(Android only)` label to `timeInterval` option in the docs.
