### ISSUE TITLE
Expo App crashes (EXC_CRASH (SIGABRT), EXC_CORPSE_NOTIFY)

### ISSUE THREAD

**Issue by yolpsoftware** [expo/expo#10203]
### Summary of Issue 

From time to time, the Expo app crashes while I'm testing my app (which is uploaded as an Expo project bundle). It is a native crash, the app just disappears.

See attachment for full stack dump.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

This is generated from the command line where I build the app:

```
  Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.1.0 => 4.1.0 
    npmGlobalPackages:
      expo-cli: 3.22.3
```

This is the package.json of the app in question:

```
{
  "scripts": {
    "ios": "expo start --ios",
    "android": "expo start --android",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest",
    "test:types": "tsc --project . --noEmit",
    "test:coverage": "npm test -- --coverage=false"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.2.0",
    "@react-native-community/masked-view": "0.1.10",
    "expo": "^38.0.0",
    "firebase": "7.9.0",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.9.0",
    "react-native-redash": "^14.2.4",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-navigation": "^4.1.0",
    "react-navigation-shared-element": "^1.0.0",
    "react-navigation-stack": "~1.10.3",
    "redux": "^4.0.5",
    "use-memo-one": "^1.1.1"
  },
  "devDependencies": {
    "@babel/core": "~7.6.0",
    "@types/jest": "^25.1.3",
    "@types/node": "^13.7.0",
    "@types/react": "~16.9.41",
    "@types/react-native": "~0.62.13",
    "@types/react-navigation": "^3.4.0",
    "babel-preset-expo": "^8.2.3",
    "jest": "^25.0.0",
    "jest-expo": "^38.0.0",
    "ts-jest": "^25.2.1",
    "typescript": "~3.9.5"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "private": true
}
```

### Reproducible Demo

Was not able to reproduce it. It happens sometimes, but there does not seem to be a clear condition that causes it. The only thing I can say is that every time the crash has happened so far, there were active `react-native-reanimated` animations running on the screen (version 1.9.0).

Maybe it is related to this issue: https://github.com/software-mansion/react-native-reanimated/issues/216. However, this is only a suspicion that I had some months ago when both issues were occuring. But reanimated 216 did not happen again since at least July.
 
### Steps to Reproduce

Was not able to reproduce it, see above.

### Expected Behavior vs Actual Behavior

Expecting no crashes.

[Exponent  16.09.20, 16-14.crash.zip](https://github.com/expo/expo/files/5233001/Exponent.16.09.20.16-14.crash.zip)

**Comment by cruzach** [comment]
@yolpsoftware this is with a bare workflow project, right? WIthout a reproducible demo, it's unlikely that this issue will get much attention 🙁 I think the best steps moving forward are to try and isolate the crash and reproduce it consistently

**Comment by yolpsoftware** [comment]
@cruzach no, this is a managed workflow project. It happens in the official Expo app.

**Comment by cruzach** [comment]
Your `react-native` dependency should point to our fork of react native, in that case:
```
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
```

**Comment by cruzach** [comment]
Hm, `expo init` and `expo upgrade` shouldn't change that dependency to a regular version, it should always point to our fork. Does `git blame` show when that dependency might've been changed?

**Comment by cruzach** [comment]
@yolpsoftware as [this comment in the issue you linked indicates](https://github.com/software-mansion/react-native-reanimated/issues/216#issuecomment-582449703), there's not much we can do without a complete and minimal reproducible demo, so I'm going to close this issue for now. We can always reopen once we have a reliable reproducible demo that we can use to investigate this further

**Comment by yolpsoftware** [comment]
Thanks, gonna switch to the `expo/react-native` fork and see whether it's still there.
