### ISSUE TITLE
Unable to resolve @expo/vector-icons/Ionicons after detaching the application

### ISSUE THREAD

**Issue by NdozHH** [expo/expo#1020]
My project was initially created with CRNA, I used vector-icons and it worked perfectly, I made the detach of my application and now I get this error, I clarify that vector-icons is in the package.json dependencies.

![captura](https://user-images.githubusercontent.com/25773289/33339636-d16a75da-d447-11e7-844d-8a0fd542da87.PNG)

**Comment by jesseruder** [comment]
Did you try following the instructions in the error message about clearing caches, etc.?
