### ISSUE TITLE
FirebaseRecaptcha, verification code

### ISSUE THREAD

**Issue by NarekSafaryan** [expo/expo#10218]
Received success on `Send verification code` but SMS not receiving.
Reproduced yesterday. It was works well until yesterday

**Comment by byCedric** [comment]
Hi @NarekSafaryan, thanks for writing in. But, without any context, info or [repro](https://stackoverflow.com/help/minimal-reproducible-example), we can't help you solve this. To investigate or solve an issue, we need to be able to reproduce it. If you think this is an issue with Expo, please create a new bug report with the questions filled in from the template.

Thanks

**Comment by NarekSafaryan** [comment]
https://snack.expo.io/@ijzerenhein/firebase-phone-full-auth-demo
It was reproduces on snack demo. Maybe it is carrier issue
Pls review

**Comment by NarekSafaryan** [comment]
Seems like it's a firebase issue, Thanks
