### ISSUE TITLE
Bare React Native Hello World app is 40MB on expo sdk 38

### ISSUE THREAD

**Issue by ta1bbty** [expo/expo#10219]
### Summary of Issue 
I tried bare react native flow and even that installs **all** the unimodules

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```bash
  Expo CLI 3.27.4 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    npmPackages:
      expo: ~38.0.8 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: bare
```

### Reproducible Demo
`expo init my-bare-notifs`

 
### Steps to Reproduce
Choose the bare react native flow in expo

### Expected Behavior vs Actual Behavior
The app should be in <10MB rather it has bloated to 40MB

**Comment by ta1bbty** [comment]
I expected this to be smaller, any suggestion on how that can be achieved.
This is my `package.json`
```json
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "expo": "~38.0.9",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

**Comment by brentvatne** [comment]
sorry, how did you measure this?

**Comment by ta1bbty** [comment]
I've manually removed these :
```
unimodules-barcode-scanner-interface@5.2.1
unimodules-face-detector-interface@5.2.1
```
And compiled, this time it wasn't included, which looks better.
So should I manually remove each of those unimodules and then remove permissions for the same in AndroidManifest.xml

**Comment by brentvatne** [comment]
@ta1bbty - those certainly would not be increasing the size of your binary. those are simple header files that define an interface for other modules to potentially use. anything ending with `-interface` has close to zero impact on your binary size. for example, here are the contents of the unimodules-barcode-scanner-interface on ios: https://github.com/expo/expo/tree/master/packages/unimodules-barcode-scanner-interface/ios/UMBarCodeScannerInterface

**Comment by ta1bbty** [comment]
Hi @brentvatne 
Thanks for the prompt reply.
I checked the size of the debug app that was built.

**Comment by ta1bbty** [comment]
How do you suggest I build a release apk and measure ( and/or debug apk )?
Sorry, my bad, I might've not seen that it was `-interface` and assumed the size is big, but yeah the size seems to be bigger.

**Comment by brentvatne** [comment]
that is not how to measure the binary size of an app. the only way to then know for sure what the size will be on the app store is to upload to the app store, but you can read more about other techniques on https://stackoverflow.com/a/26585279/659988

on android you would use app bundles and you need to upload to the play store to see what the size is on specific devices. same for ios with app thinning.

**Comment by brentvatne** [comment]
@ta1bbty - created an issue to improve docs around this: https://github.com/expo/expo/issues/10220

**Comment by ta1bbty** [comment]
@brentvatne thanks for the info, will do that and check.

**Comment by ta1bbty** [comment]
@brentvatne I checked the debug app that is built with `yarn android` it's 41MB.
is it actually supposed to be that big :thinking: ?
Also regarding permissions by default `AndroidManifest.xml` has a lot of permissions ( in the `main` release folder )

**Comment by brentvatne** [comment]
please never profile anything in a debug app. feel free to remove permissions that you don't need

**Comment by brentvatne** [comment]
https://support.google.com/googleplay/android-developer/answer/9302563?hl=en

**Comment by ta1bbty** [comment]
@brentvatne 
sorry for constant nagging, I tried removing the permission from manifest but it still ends up in the app bundle, I upload to playstore.
A little less than earlier ( it's 30 now, earlier it was 50 permissions ).
I've earlier removed from manifest file, which brought down permissions to 30.
Now, I've tried this : 
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"  xmlns:tools="http://schemas.android.com/tools" package="com.hackingsimplified.notifyme">
  <uses-permission tools:node="remove" android:name="android.permission.INTERNET"/>
  <uses-permission tools:node="remove" android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
```

`tools:node="remove"`

But I guess the permissions don't completely go down :sweat_smile: 

Like it comes down to this now : 
```Required permissions (22)
android.permission.FOREGROUND_SERVICE, android.permission.READ_APP_BADGE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.STORAGE, com.anddoes.launcher.permission.UPDATE_COUNT, com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE, com.google.android.gms.permission.ACTIVITY_RECOGNITION, com.google.android.providers.gsf.permission.READ_GSERVICES, com.htc.launcher.permission.READ_SETTINGS, com.htc.launcher.permission.UPDATE_SHORTCUT, com.huawei.android.launcher.permission.CHANGE_BADGE, com.huawei.android.launcher.permission.READ_SETTINGS, com.huawei.android.launcher.permission.WRITE_SETTINGS, com.majeur.launcher.permission.UPDATE_BADGE, com.oppo.launcher.permission.READ_SETTINGS, com.oppo.launcher.permission.WRITE_SETTINGS, com.sec.android.provider.badge.permission.READ, com.sec.android.provider.badge.permission.WRITE, com.sonyericsson.home.permission.BROADCAST_BADGE, com.sonymobile.home.permission.PROVIDER_INSERT_BADGE, me.everything.badger.permission.BADGE_COUNT_READ, me.everything.badger.permission.BADGE_COUNT_WRITE```

Which I think is good :)
you could be a better judge of it .

Thanks a lot for bearing with my tiring nuances :slightly_smiling_face:

**Comment by ta1bbty** [comment]
I don't see any special permissions here, which looks good :)

**Comment by ta1bbty** [comment]
@brentvatne 
This is the app size now :smile: 
![image](https://user-images.githubusercontent.com/45117337/93510670-38d59a00-f93f-11ea-89d0-fb2245e17d1f.png)

I think that's how low it can go.

**Comment by brentvatne** [comment]
at a quick glance those permissions look reasonable! you could make it a bit smaller by removing some of the libraries we include in default projects, but you will likely want those around at some point

**Comment by ta1bbty** [comment]
@brentvatne thanks a lot, you helped me a lot. I had been struggling with this for three days now :/
