### ISSUE TITLE
Wrong font appears after implementing jest-expo-puppeteer

### ISSUE THREAD

**Issue by bikashsahucbnits** [expo/expo#10216]
### Summary of Issue 

Expo CLI 3.27.4 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.11.25 => 0.11.25 
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^3.11.0 => 3.13.0 
    Expo Workflow: managed

 
module.exports = {
  preset: "jest-expo-puppeteer",
  globals: {
    URL: "http://localhost:19006/"
  },
  verbose: true,
  testTimeout: 30000,
  setupFilesAfterEnv: ["./jest.setup.js"],
  transform: {
    "\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
  },
  collectCoverage: true,
  collectCoverageFrom: [
    "**/*.{js,jsx}",
    "!**/coverage/**",
    "!**/web-build/**",
    "!**/node_modules/**",
    "!**/babel.config.js",
    "!**/webpack.config.js"
  ]
};

it doesnot show the respective fonts in my expo webpage instead it fallback to system's default font

**Comment by byCedric** [comment]
Hi @bikashsahucbnits! Thanks for the report. Unfortunately, without [a repro](https://stackoverflow.com/help/minimal-reproducible-example), we can't dig into this issue for you. Can you provide either a Snack or repo for us to debug?

**Comment by cruzach** [comment]
Closing this for lack of info and inactivity. If you're running into this issue, please provide a repro and we're happy to investigate!
