### ISSUE TITLE
FirebaseAnalytics logEvent() and setUserProperties doesn't log parameters properly

### ISSUE THREAD

**Issue by liukinsay97** [expo/expo#10225]
### Summary of Issue 
So, I tried using FirebaseAnalytics using `expo-firebase-analytics`,
everything works fine, but the parameters won't logged in analytics.
happens on `logEvent()` and `setUserProperties()`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.4 => 0.12.6 
      expo: ~37.0.3 => 37.0.10 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7

### Reproducible Demo

> - This should include as little code as possible, please don't simply link your entire project
> - Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
> - If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
> - If you need more guidance, please see https://stackoverflow.com/help/mcve

 
### Steps to Reproduce
> 1. create react-native project using expo init
> 2. install FirebaseAnalytics using expo install expo-firebase-analytics and expo install firebase (for web)
> 3. import and use FirebaseAnalytics, the function used is logEvent("some_event", {parameters: parameter_value})
> 4. wait for event logged in google analytics
> 5. check parameters in event then see no parameter available

### Expected Behavior vs Actual Behavior

Expected Behavior:
events and parameters are logged in google analytics

Actual Behavior: 
the events is logged but parameters doesn't logged
![Screen Shot 2020-09-18 at 4 00 03 PM](https://user-images.githubusercontent.com/54882003/93579218-6ca8d200-f9c8-11ea-9944-5aa22a1f2721.png)

**Comment by ronbel** [comment]
I am experiencing the same issue, is there any progress with this?

**Comment by liukinsay97** [comment]
> I am experiencing the same issue, is there any progress with this?

Sadly no response until now.
I don't know when will this be noticed

**Comment by brentvatne** [comment]
@ronbel @liukinsay97 - the beauty of open source :) if you really need a fix for this i would recommend digging in to the code and opening a pull request

**Comment by IjzerenHein** [comment]
If it's urgent you could greatly help us out by providing a PR :) 👍

**Comment by ronbel** [comment]
I was mistaken, it actually works fine, I was just looking for the parameters in the wrong place, Analytics is kinda hard to figure out in that way. For people in the future who might think they have encountered this issue, you have to look for the parameters in Google Analytics in the Analysis Hub, you'll probably have to define Metrics/Dimensions for your events. Bottom line, they're tricky to find if you have zero experience with Analytics.

**Comment by IjzerenHein** [comment]
Glad you were able to resolve this @ronbel. This may be of use to other people as well 👍
