### ISSUE TITLE
[Android] AppState wrong when using WebBrowser

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1022]
On iOS, AppState remains "active" as expected when a WebBrowser is opened (in this particular case, I'm using the facebook and google oAuth screens, which I assume are WebBrowser based?). On Android, however, the AppState changes to "background", which should only be the case when in another app or on the homescreen (per [docs](https://facebook.github.io/react-native/docs/appstate.html)).

**Comment by AdamJNavarro** [comment]
Hey @JulianKingman,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
