### ISSUE TITLE
[docs] Suggestion for improving MapView page

### ISSUE THREAD

**Issue by ShunyaWatanabe** [expo/expo#10222]
https://docs.expo.io/versions/v38.0.0/sdk/map-view/#deploying-to-a-standalone-app-on-android

^As this section starts with this sentence "Since your app is most likely using App Signing by Google Play ...", I feel like this should be the default step in your instruction instead of "Run `expo fetch:android:hashes`". 

I myself have just followed the instruction and run the command, and then realized getting the key from Google Play Console is the actual way to go.

**Comment by cruzach** [comment]
I think most people tend to test their APKs by installing them directly onto their devices first, rather than going through the Google Play store/beta testing route, and then later on after they've done some initial testing, they will go through the Google Play store

**Comment by ShunyaWatanabe** [comment]
Oh okay, yeah that makes sense. I was actually debugging my production app and got confused.
