### ISSUE TITLE
Conflict with ESLint rule react/style-prop-object in expo-status-bar style prop

### ISSUE THREAD

**Issue by yzobairi** [expo/expo#10237]
Hello,

There is a conflict with the rule react/style-prop-object and the StatusBar from expo.
When I use 

`<StatusBar style="auto" />`

I have the following error: 

`Style prop value must be an objecteslintreact/style-prop-object)`

I don't want to disable this rule but I don't want to have this error on each StatusBar I use in the project.
I think ESLint is confusing style prop from react components and style prop from StatusBar.

Do you have any suggestion for me?

Or maybe it would be better to rename style prop from StatusBar to "mode" or "barStyle" in a pull request?

Thanks in advance for your help.
(and sorry for my english)

**Comment by brentvatne** [comment]
this was an intentional choice - in my opinion it is the best name for the prop. i don't think this is a very reasonable eslint rule and would suggest disabling it.

**Comment by gasolin** [comment]
in 2021 expo also call it `colorscheme` instead of style ;)
https://docs.expo.io/versions/latest/react-native/usecolorscheme/

for devs that not use typescript, we still count on eslint to quick identify if we `typo the style to styles` etc.

@brentvatne would be nice to have an alias prop `colortheme` alone with the `style` (which conflict the eslint rule) prop

**Comment by brentvatne** [comment]
@gasolin - that is a different thing entirely :)

color scheme represents this API: https://developer.apple.com/documentation/swiftui/colorscheme
style on status bar represents UIStatusBarStyle: https://developer.apple.com/documentation/uikit/uistatusbarstyle - with some other options

i'm not convinced that we should rename this, again if you want to use this linter you can do this:

> one way to work around this if you would prefer to keep the rule is to create a component that wraps expo-status-bar and accepts another name for the prop, then just disable the eslint rule inline in that one place
