### ISSUE TITLE
Hot reload: how to manage module acception and reloading

### ISSUE THREAD

**Issue by whitecolor** [expo/expo#10246]
It is not much info about how expo hot reload working. What I observe is that if I change ANY ts module in my app it is accepted and re-executed. But some modules are just dependencies and execution of them will have no effect on the app and actually their dependants should be reloaded.

So the question is: how to manage the way modules are accepted and reloaded?

**Comment by brentvatne** [comment]
hi there! we use fast refresh as described in https://reactnative.dev/docs/fast-refresh - please refer to this docs page for more information
