### ISSUE TITLE
[expo-in-app-purchases] Module does not compile under xCode 12

### ISSUE THREAD

**Issue by Strate** [expo/expo#10245]
### Summary of Issue 
Looks like there are new enumeration values of `SKErrorCode`, so expo-in-app-purchase does not compile any more in xCode 12

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

I am using latest (`8.2.1`) version of `expo-in-app-purchase` module

### Compile error:

```
/Users/strate/gbn/mobile/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:418:10: warning: 4 enumeration values not handled in switch: 'SKErrorOverlayCancelled', 'SKErrorOverlayInvalidConfiguration', 'SKErrorOverlayTimeout'... [-Wswitch]
  switch(errorCode) {
         ^
/Users/strate/gbn/mobile/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:418:10: note: add missing switch cases
  switch(errorCode) {
         ^
/Users/strate/gbn/mobile/node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:443:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
```

**Comment by cruzach** [comment]
Can you try `expo-in-app-purchases@9.0.0`? I was able to build with that version, it looks like [this PR](https://github.com/expo/expo/commit/8d679462ea7e3c63bf8b31e9e4319e2536a16349#diff-55272ee26a86705f4148f9c1947530f6) fixed the issue

**Comment by cruzach** [comment]
just published a new version of `expo-in-app-purchases` as `latest`. To get the fix:

- run `yarn add expo-in-app-purchases`
- run `npx pod-install`

and rebuild 👍

**Comment by ArthurianX** [comment]
@cruzach - this is also a problem in `node_modules/expo-notifications/ios/EXNotifications/Permissions/EXUserFacingNotificationsPermissionsRequester.m:178`

Same issue, I added the default return there and it worked. 

Are there maybe other libraries affected by this?


Thanks!

**Comment by scortumee** [comment]
@ArthurianX hey, thanks for the fix. What value are you returning by default? 
like that `return @(0)` ?
