### ISSUE TITLE
Cannot use Expo Notifications using Expo URL

### ISSUE THREAD

**Issue by ronal2s** [expo/expo#10243]
Issue 1: 
I already configured all each time that I want to make a notification using (https://expo.io/notifications) I got the same error:
"InvalidCredentials: Unable to retrieve the FCM server key for the recipient's app. Make sure you have provided a server key as directed by the Expo FCM documentation."

I already follow those steps and nothing changed, the weird thing is that I can use the ExponentPushToken in Firebase Console Cloud Messaging without error, working well, but using the Expo endpoint doesnt work.

Issue 2: 
When I'm testing in a Sunmi Printer Device I got "fetching the token failed expo notification"

**Comment by brentvatne** [comment]
hi there!

1. it sounds like it's not configured properly - you need to upload the fcm server key. 

> the weird thing is that I can use the ExponentPushToken in Firebase Console Cloud Messaging without error, working well, but using the Expo endpoint doesnt work.

i don't think you would be able to use the ExponentPushToken in the firebase console - firebase does not understand expo tokens.

2. it seems like sunmi devices might not have google play services installed. FCM requires google play services
