### ISSUE TITLE
[expo-av] Video resizeMode doesn't work on first loop on iOS14

### ISSUE THREAD

**Issue by iamdavidmartin** [expo/expo#10249]
### Summary of Issue 
On iOS14 expo-av Video resizeMode does not correctly resize on first render, correctly renders on subsequent loops. iOS 13 and below is fine.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 5.3.19 => 5.3.19
      @types/react: 16.9.46 => 16.9.46
      @types/react-native: 0.63.8 => 0.63.8
      react: 16.13.1 => 16.13.1
      react-native: 0.63.2 => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.11.9

Using unimodules, bare workflow.

### Reproducible Demo

        <Video
          source={{
            uri: "https://furball-dev-filestorage-wcjv7qlhvwqk.s3.amazonaws.com/miles.m4v",
          }}
          rate={1.0}
          volume={1.0}
          isMuted={false}
          shouldPlay
          isLooping
          style={{ width: 300 height: 300 }}
          resizeMode="cover"
        />

### Steps to Reproduce

Drop that code snipped in a project with expo-av on an iOS14 simulator.

### Expected Behavior vs Actual Behavior

Left image is iOS12, right is iOS14 playing on first loop.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/373633/93688435-bfdb5d00-fa7a-11ea-85b2-2ceceb82e20d.png">

**Comment by iamdavidmartin** [comment]
Another quick note - even if the video already fits the dimensions, in my case a square video in a square container, each of the resizeMode options ("cover", "contain", "stretch") will still incorrectly resize the video in their own, unique, wrong way.

Hope this additional info is helpful.

**Comment by jackie577** [comment]
I am having the exact same issue as well.

**Comment by sammarks** [comment]
Here is the underlying issue inside react-native-video: https://github.com/react-native-community/react-native-video/issues/2159 - it has a potential workaround I'm currently trying to apply to ExpoAV manually.

**Comment by nyn531** [comment]
Same issue here.

**Comment by kevin-ashton** [comment]
Is there any update on this? Our users are getting these squished videos  and we are debating if we try to fix it ourselves. @sammarks were you able to fix it with manually applying the workaround from react-native-video?

**Comment by sammarks** [comment]
@kevin-ashton I just switched to the react-native-community version and applied the fix they had there. I was unsuccessful with my attempt to adopt it to the Expo version :/

**Comment by brentvatne** [comment]
hi there! as @sammarks mentioned above, this appears to be an issue with ios 14, and should be resolved in ios 14.2. the temporary patch mentioned in the react-native-video brings with it some regressions in other areas (eg: it appears to break `onReadyForDisplay`). we'll investigate if there is a way we can resolve it now without any similar issues.

**Comment by TimERTy** [comment]
It may not look exactly how you would like but as a temporary fix until this is resolved you can set it to `resizeMode="stretch"`  which doesn't seem to be experiencing this issue.

What I have done is:
```
<Video
...
    resizeMode={Platform.OS === 'ios' && Platform.Version === '14.0' ? 'stretch' : 'cover'}
...
/>
```

**Comment by dandre-hound** [comment]
@TimERTy this solution didn't quite work for me. The video is now full screen but the aspect ratio is still slightly off. Anyway if this solution worked for you, you may want to consider a more [comprehensive version compare](https://stackoverflow.com/a/6832721/8859305) since iOS 14.0.1 is out and your code snippet above wouldn't work for that.

For now, our team has just disabled video upload entirely until 14.2 is out:
```
  isVideoNotAllowed = () => {
    if (Platform.OS === 'ios') {
      const iosVersion = DeviceInfo.getSystemVersion()
      return (
        versionCompare(iosVersion, "14.0.0") === 0 ||
        (
          versionCompare(iosVersion, "14.0.0") > 0 &&
          versionCompare(iosVersion, "14.2.0") < 0
        )
      )
    } else {
      return false
    }
  }
```

**Comment by colinwilliams90** [comment]
I'm also having this issue. Is there an update or a good workaround?
The video will always appear stretched on the first loop, and then correct for all subsequent loops.
I'm using Video from 'expo-av' to playback the video files.

**Comment by antoarva** [comment]
Yesterday iOS 14.1 released, the video is fixed now. Just update.

**Comment by gurugutten** [comment]
@antoarva I still experience this issue on iOS 14.1

**Comment by antoarva** [comment]
> @antoarva I still experience this issue on iOS 14.1

Also I updated the react, react-native:
    "react": "16.13.1",
    "react-native": "0.63.3",
     "react-native-video": "5.1.0-alpha8",

maybe this would solve your issue
