### ISSUE TITLE
Web browser Header and footer on IOS displays slightly lighter colour than what is passed in

### ISSUE THREAD

**Issue by samc350** [expo/expo#10266]
Web browser Header and footer on IOS displays slightly lighter colour than what is passed in. 

Environment - we have been seeing this in IOS [13.6] and I have been able to reproduce this inside the snack.expo.io web browser demo simulator. 

### Reproducible Demo
https://snack.expo.io/2ZQGKvuW_

Change line 10 in web browser demo found on https://docs.expo.io/versions/latest/sdk/webbrowser/ to `let result = await WebBrowser.openBrowserAsync('https://expo.io', {toolbarColor: '#00000000'});` 
 

### Expected Behavior vs Actual Behavior
On IOS this should open a browser with a fully black header but instead the header and footer are slightly grey. I have tried a number of different color and they all seem to turn out slightly lighter than the colour i pass in, I have also tried colours in both #AARRGGBB or #RRGGBB formats. 
![Screen Shot 2020-09-22 at 9 57 24 AM](https://user-images.githubusercontent.com/68880995/93831001-d45f6580-fcc5-11ea-97e0-4ccc732d827b.png)

**Comment by ide** [comment]
There is a good chance that this is how iOS works and the colors are hints. Needs some UIKit investigation.

**Comment by JairajJangleSLIOT** [comment]
Facing the same issue, this might be the explanation of what is causing the issue: https://stackoverflow.com/questions/22844253/uinavigationbar-background-color-not-the-exact-uicolor-i-set-it-to

Would be great to have a parameter to disable the transparency of the web browser toolbar.
