### ISSUE TITLE
39.0.0 is not a valid sdk version

### ISSUE THREAD

**Issue by kevgrig** [expo/expo#10268]
### Summary of Issue 

Upgraded expo-cli (`sudo yarn global add expo-cli`), upgraded my project to Expo SDK 39 (`expo upgrade`), uninstalled the Expo app in my emulator, ran `expo start -c`, launched in Android which installed the latest client, and then received the following. Closing everything and restarting doesn't help.

![Screenshot_20200921_182648](https://user-images.githubusercontent.com/6432587/93836569-0a560880-fc38-11ea-9071-e3fbb94ef2ce.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
$ expo diagnostics

  Expo CLI 3.27.6 environment info:
    System:
      OS: Linux 5.8 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.14.6 - /usr/bin/npm
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: managed
```

### Steps to Reproduce

1. `yarn init play`
1. `cd play`
1. `yarn android`

**Comment by brentvatne** [comment]
your expo client version is out of date. you can run `expo client:install:android` to get the latest

```
╰─$ expo client:install:android                                                                                                                                                                                         130 ↵
? You are currently using SDK 39.0.0. Would you like to install client 2.17.2 released for this SDK? › (Y/n)
```

**Comment by kevgrig** [comment]
@brentvatne That didn't work:

```
$ expo client:install:android
✔ You are currently using SDK 39.0.0. Would you like to install client 2.17.2 released for this SDK? … yes
Uninstalling Expo from Android device.
Installing Expo on device
Done!
$ yarn android
... same issue
```

**Comment by kevgrig** [comment]
I got this to work by uninstalling the Expo app, then downloading the latest Expo app from the Play store and it worked (I don't normally do it this way as I don't bother signing into the Play store).

Could it be that the app in expo-cli hasn't been updated? Note that I did run `sudo yarn global add expo-cli` before all of this without error.

**Comment by brentvatne** [comment]
@kevgrig - do you have multiple android devices connected? eg: you have an emulator open and your phone connected? it could be that it's updating on a device that you're not expecting

**Comment by kevgrig** [comment]
@brentvatne No, just one and no phone connected. I stopped the emulator, ran `kill -9 -f adb`, re-started it, and same issue (before I got it working using the workaround mentioned).

**Comment by brentvatne** [comment]
thanks, looking into it

**Comment by brentvatne** [comment]
ok this should be fixed in expo-cli@3.27.7 - apologies!

**Comment by brentvatne** [comment]
i also rolled out an update to our versions api endpoint that will mitigate this issue on older versions of expo-cli. thanks again for the info!

**Comment by kevgrig** [comment]
Thanks!

**Comment by shubhampronteff** [comment]
To overcome this issue. Follow these steps.
Step 1) Run this command: "expo client:install: android" in your terminal.
Step 2) Update your Expo client in the play store for android apps.

Now it will most probably run fine...

**Comment by udokaokoye** [comment]
Updating the mobile app solved my issue

**Comment by RajaMuhammadJunaid** [comment]
Update your mobile app your issue will be solved

**Comment by mohaneduestc** [comment]
In my case uninstall expo CLI and install it again, this works!!
