### ISSUE TITLE
[ios][android] Warning about native splash screen in latest Expo development clients

### ISSUE THREAD

**Issue by esamelson** [expo/expo#10263]
## 🐛 Bug Report

In the iOS Expo development client 2.17.1, currently available for download from the App Store, and Android Expo development client 2.17.2, currently available from Google Play, occasionally the following warning is logged when running a project in development:

```
No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.
```

This is a known issue with these versions and will be fixed in a future update. This warning can be ignored and you do not need to do anything to resolve it.

**Comment by kevgrig** [comment]
To make this bug easier to find, here is an example stack on Android:

```
[Unhandled promise rejection: Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android).]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
- node_modules/expo/node_modules/expo-splash-screen/build/SplashScreen.js:23:7 in preventAutoHideAsync
[...]
```

**Comment by divonelnc** [comment]
This error is not so harmless, as I believe it causes this `try` to fail:

```
try {
    await SplashScreen.preventAutoHideAsync();
} catch (e) {
    console.warn(e);
    await SplashScreen.hideAsync();
}
```

**Comment by oguzhanali** [comment]
@bbarthec @divonelnc is right. SplashScreen.preventAutoHideAsync() is not working at all on Android and managed work flow. iOS is working fine. You could try use it without hideAsync(). Splash screen is just auto hiding any way. Expo snack is not updated yet to sdk 39, cant repoduce it there.

**Comment by divonelnc** [comment]
Is there an ETA for the update that will fix the issue?

**Comment by ptrobert** [comment]
This is the error 
[Unhandled promise rejection: Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android).]

we are not using any splashscreen based calls, i wonder how to avoid this

**Comment by pdandradeb** [comment]
@ptrobert You could avoid this by stop using `AppLoading` as a workaround until the problem is fixed.

**Comment by bbarthec** [comment]
The fix has already landed, but we need to wait for the next `Expo Client` submission to the `AppStore` with the all the bugfixes the Expo team has to deliver.

**Comment by HVHMobileDeveloper** [comment]
I'm facing the same issue,

**Comment by yuraxdrumz** [comment]
Im facing the same issue. After submitting to the Play Store, my app gets stuck on a white screen after showing the splash screen.

**Comment by Aryk** [comment]
> @ptrobert You could avoid this by stop using `AppLoading` until the problem is fixed.

I'm using AppLoading but now the background color in my app.json is not getting applied. This only started in SDK 39.

My app.json simply has:
```
"android":
      "splash": {
        "backgroundColor": "#3F51B5"
      },
```

Is that related to this?

**Comment by andihoerudin24** [comment]
i'm having the same problem is there a solution to this problem

**Comment by Aryk** [comment]
> > @ptrobert You could avoid this by stop using `AppLoading` until the problem is fixed.
> 
> I'm using AppLoading but now the background color in my app.json is not getting applied. This only started in SDK 39.
> 
> My app.json simply has:
> 
> ```
> "android":
>       "splash": {
>         "backgroundColor": "#3F51B5"
>       },
> ```
> 
> Is that related to this?

For those reading, there is a ticket for my issue as well:

https://github.com/expo/expo/issues/10434

**Comment by dante314** [comment]
Pude darle solución asi: https://github.com/expo/expo/issues/10464#issuecomment-707263630

**Comment by pntech20** [comment]
Same issue
`[Unhandled promise rejection: Error: No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.]`

**Comment by brentvatne** [comment]
@pntech20 - update to the latest version of expo client, it is explained in https://github.com/expo/expo/issues/10464#issuecomment-703178030

**Comment by pntech20** [comment]
That works. Thank you @brentvatne

**Comment by pntech20** [comment]
Actually it only works on the first time after re-install the latest version (2.17.4 at this time) of Expo Client @brentvatne .
If I close and re-open Expo, the error happens again sometimes and I have to re-install Expo again to make it work.
I'm using Managed Flow

**Comment by pntech20** [comment]
Update: I temporarily stop using AppLoading and problem solved

**Comment by brentvatne** [comment]
sorry i don't know why this would be happening and i can't help without any information that helps us to reproduce the issue. please create a new issue with a [mcve](https://stackoverflow.com/help/mcve) if you think this is a bug, thanks!
