### ISSUE TITLE
Can't find variable: performance - sentry-expo - v38 

### ISSUE THREAD

**Issue by yarapolana** [expo/expo#10260]
## 🐛 Bug Report
I recently installed expo 38 and when running I get an error
'ReferenceError: Can't find variable: performance'

![Screenshot 2020-09-21 at 15 40 44](https://user-images.githubusercontent.com/19730118/93789120-f94dcd00-fc20-11ea-9027-70425ed56175.png)
![Screenshot 2020-09-21 at 15 40 58](https://user-images.githubusercontent.com/19730118/93789123-fa7efa00-fc20-11ea-92d7-5674eb596dbb.png)

### Summary of Issue 
After commenting on a lot of imports found out that sentry-expo is causing this error. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
      Expo CLI 3.27.6 environment info:
      System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 25, 28, 29
        Build Tools: 28.0.3, 29.0.1, 29.0.2
        System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: 38.0.8 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: 0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.6
    Expo Workflow: managed

     sentry-expo: 2.1.2

### Steps to Reproduce
Install new project, import * as Sentry from 'sentry-expo'

initialize Sentry.init({ dsn: '...dsn...' })

when commenting out the import and Sentry.init app works
 
### Expected Behavior vs Actual Behavior

App should load
App gives red error

**Comment by cruzach** [comment]
hi! just tested this:
- `expo init`
- `yarn add sentry-expo`
- add 
```
import * as Sentry from "sentry-expo";

Sentry.init({
  dsn:
    "XXX",
  enableInExpoDevelopment: true,
  debug: true,
});
```
to App.js
- `expo start` 

and didn't have any issues, are you sure that's the exact steps you took?

**Comment by yarapolana** [comment]
@cruzach tried creating a new project and trying again but had the same issue.

Thinking I might have expo corrupt in my computer will try reinstall it and reply to this later.

**Comment by yarapolana** [comment]
Reinstalled expo cli
39 is working fine now.
If the issue persists I will continue the thread here
closing for now.
