### ISSUE TITLE
Facebook SDK Issue - AppEventsLogger.logEvent is undefined

### ISSUE THREAD

**Issue by atillasertkaya** [expo/expo#1027]
Hi,

When I used logEvent function of Facebook SDK with Expo, I get the following error. Any solutions?

![simulator screen shot - iphone 7 - 2017-11-30 at 00 42 13](https://user-images.githubusercontent.com/5853889/33400747-1ba32c02-d568-11e7-9d27-3b36e2fe413f.png)

**Comment by jesseruder** [comment]
Can you please share the code you are using?

**Comment by atillasertkaya** [comment]
Thanks @jesseruder 

`import {AppEventsLogger} from 'react-native-fbsdk';

export default class AnalyticsAPI {

    static trackScreen(screen) {
        AppEventsLogger.logEvent(screen);
    }

}`

**Comment by goleador0322** [comment]
@atillasertkaya could you fix that? this maybe caused by FBSDK bug. And also I cant solve this bug...

**Comment by mpm** [comment]
@atillasertkaya sorry for the noob question, but are you using an ejected version of your app? I'm trying to get the full FB SDK to work for ad attribution tracking, but finding no info on this (I guess its not possible with the limited wrapper of the SDK).

I can't import 'react-native-fbsdk' in my expo app ("unable to resolve").

**Comment by jamesloper** [comment]
I'm having the same issue. I tried `yarn add react-native-fbsdk` and it resolves when imported, but the SDK doesn't appear to initialize properly, leading to a `undefined is not an object`
