### ISSUE TITLE
ImagePicker.launchCameraAsync returns { cancelled: true } for a big panorama file on iOS

### ISSUE THREAD

**Issue by jparksecurity** [expo/expo#10272]
### Summary of Issue 
ImagePicker.launchCameraAsync returns `{ cancelled: true }` when I never cancel.\
I choose [a big panorama](https://upload.wikimedia.org/wikipedia/commons/e/e6/Clocktower_Panorama_20080622_20mb.jpg) and set option `{ allowsEditing: true }` on real iOS device(expo client & standalone app).

It works if I do one of the followings:
1. to use iOS simulator
2. to crop the image to a certain aspect ratio(not clear what it is. I cropped the image again and again until it works)
3. to use [lower resolution](https://commons.wikimedia.org/wiki/File:Clocktower_Panorama_20080622_20mb.jpg)
4. to set option `{ allowsEditing: false }`

I think it's related to #8397 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.27.4 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.20.1
    Expo Workflow: managed

### Reproducible Demo

 https://snack.expo.io/@horaeng/6a4978 on iOS devicie(The original code is from https://snack.expo.io/@ikroeber/imagepicker-returning-cancelled-when-shouldn't)

### Steps to Reproduce

1. download [a photo](https://upload.wikimedia.org/wikipedia/commons/e/e6/Clocktower_Panorama_20080622_20mb.jpg) on iOS device(no iOS simluator)
2. trigger `ImagePicker.launchCameraAsync` with `{ allowsEditing: true }` somehow
3. choose the photo you downloaded in step 1
4. you can log the result to confirm it's `{ cancelled: true }`

### Expected Behavior vs Actual Behavior
I should be able to edit the photo just like I do on iOS simulator

**Comment by jparksecurity** [comment]
no keep it open

**Comment by jparksecurity** [comment]
no

**Comment by keith-kurak** [comment]
Thanks for the repro! Reproduced on the latest SDK with an updated version of your snack (https://snack.expo.dev/@keith-kurak/imagepicker-returning-cancelled-when-shouldn't).
