### ISSUE TITLE
YellowBox has been replaced with LogBox. Please call LogBox.ignoreLogs() instead.

### ISSUE THREAD

**Issue by SimonHausdorf** [expo/expo#10276]
I upgraded to SDK 39 today. I am receiving the following warning:

```
YellowBox has been replaced with LogBox. Please call LogBox.ignoreLogs() instead.
- node_modules/react-native/Libraries/LogBox/LogBox.js:117:10 in registerWarning
- node_modules/react-native/Libraries/LogBox/LogBox.js:63:8 in warnImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:36:4 in console.warn
- node_modules/expo/build/environment/react-native-logs.fx.js:18:4 in warn
- node_modules/react-native/Libraries/YellowBox/YellowBoxDeprecated.js:25:6 in YellowBox.ignoreWarnings
- node_modules/@sentry/browser/node_modules/tslib/tslib.js:215:23 in __asyncDelegator
- node_modules/@sentry/utils/dist/object.js:124:28 in normalizeToSize
* [native code]:null in construct
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:261024:321 in _createSuperInternal
- node_modules/@sentry/browser/dist/eventbuilder.js:47:20 in eventFromUnknownInput
- node_modules/@sentry/utils/dist/instrument.js:62:5 in addInstrumentationHandler
- node_modules/@sentry/browser/dist/parsers.js:39:28 in eventFromPlainObject
- node_modules/expo-permissions/build/CoalescedPermissions.js:26:21 in expirations.sort$argument_0
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:128238:13 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:321:11 in loadModuleImplementation
- node_modules/expo/AppEntry.js:3:0 in <global>
- ... 4 more stack frames from framework internals
```

Seems like the warning is caused by `node_modules/expo/build/environment/react-native-logs.fx.js:18:4 in warn`

**Comment by alexandrius** [comment]
Happens to me as well

**Comment by Razorholt** [comment]
Try this:

1. Remove "YellowBox" from your import and replace it with "LogBox"
2. Make sure you are not calling YellowBox anywhere within your scripts.
3. If you want to ignore all warnings then include "LogBox.ignoreAllLogs();" in your App.js under useEffect  - if you are using Hooks - or inside ComponentDidMount
4. You may be more selective and ignore specific warnings, such as the annoying "Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.". In that case, add "LogBox.ignoreLogs(["Require cycle"]);"

After any changes like that I tend to restart the project using the following command: expo start -c

Hope  it helps!

**Comment by brentvatne** [comment]
this warning isn't actually coming from expo internals, it's from your own code. check for anywhere you're calling YellowBox and replace with LogBox as @Razorholt suggests! locking because it is an excellent description of the solution above ^

**Comment by cruzach** [comment]
this is the same as https://github.com/expo/expo/issues/10300, see my comment [here](https://github.com/expo/expo/issues/10300#issuecomment-700135603) for an explanation
