### ISSUE TITLE
QR code scanner in Android client is stretched

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#10270]
Notice the skew in the image

![Screenshot_20200921-201539](https://user-images.githubusercontent.com/90494/93841050-46449a00-fc47-11ea-8864-b95b29e571f6.jpg)

**Comment by thgh** [comment]
We have the same issue in Expo 38

**Comment by RodrigoDiazC** [comment]
Yep, this happened after the latest update for me along with other issues.

**Comment by brentvatne** [comment]
@thgh - the qr code screen in expo client or in your own app? you can fix it in your own app you just have to use the correct size of view for the aspect ratio you're using. this issue is about fixing it for the qr code screen in expo client.

**Comment by brentvatne** [comment]
fixed on latest android client. https://github.com/expo/expo/issues/10464#issuecomment-703178030
