### ISSUE TITLE
TaskManager doesn't work on iOS standalone app

### ISSUE THREAD

**Issue by EduardoRoc97** [expo/expo#10288]
### Summary of Issue 
I made an app which uses the background location for geotracking of the user. I use the TaskManager to implement that approach. On Android, it works fine; on iOS, only works when I test the app in Expo Client (Custom), but in the standalone it doesn't work very well. I even followed the steps that you give me in the following link to put the TaskManager running in iOS standalone apps: https://docs.expo.io/versions/latest/sdk/task-manager/.  

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Output of `expo diagnostics`

`
  Expo CLI 3.22.0 environment info:
    System:
      OS: Windows 10 10.0.19041    
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 4.6.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.3.1 => 4.4.0
`

Platforms that I'm targetting: Android and iOS

### Reproducible Demo
`bottom.jsx`

`
// Executa-se as notiicações de geolocalização que correm em background
TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
	if (error) {
		// Error occurred - check `error.message` for more details.
		Alert.alert('A geolocalização só funciona em smartphones.');
		return;
	}
	if (data) {
		const { locations } = data;
		// do something with the locations captured in the background
		add();
		console.log(counter);
		// if (counter % 2 != 0) {
			console.log('Aqui têm as vossas coordenadas!');
			console.log(data.locations[0].coords.latitude);
			console.log(data.locations[0].coords.longitude);
			// Aqui, ao recolher as coordenadas, invoca cada função para fazer qualquer operação com elas
			notificacoesPerdidas(data.locations[0].coords.latitude, data.locations[0].coords.longitude);
			// mask(data.locations[0].coords.latitude, data.locations[0].coords.longitude);
		// }
	}
});
`
`
		await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
			accuracy: Location.Accuracy.High,
			distanceInterval: 10
		});
`
`app.json`
`
{
   "expo":{
       ...,
        "ios": {
            "supportsTablet": true,
            "bundleIdentifier": "com.on.dica",
            "buildNumber": "4.1.2",
            "config": {
                "googleSignIn": {
                    "reservedClientId": "com.googleusercontent.apps.712914569696-qe8gq455d7gi5b3hj79eit5eu02tu1g2"
                }
            },
            "infoPlist": {
                "UIBackgroundModes": [
                    "location",
                    "fetch"
                ]
            }
        },
    ...
  }
}
`

 
### Steps to Reproduce
1. Include the following code in app.json:
`
{
  "expo": {
    ...
    "ios": {
      ...
      "infoPlist": {
        ...
        "UIBackgroundModes": [
          "location",
          "fetch"
        ]
      }
    }
  }
}
`

2. Test the app in custom Expo Client for ios (it worked fine)

3. Run `expo build:ios` to build the iOS standalone app

4. Test the standalone app in TestFlight

### Expected Behavior vs Actual Behavior

Expected Behavior
The app should give the local geolocation notifications, runned by TaskManager

Actual Behavior
The app is not giving the notifications.

**Comment by brentvatne** [comment]
how are you testing the behavior? are you closing the app from the multitasker or what?

**Comment by EduardoRoc97** [comment]
> how are you testing the behavior? are you closing the app from the multitasker or what?

Hi, brentvatne. The TaskManager should give me the coordinates when it's running on the standalone app, which is not doing what is supposed to do. On the Expo Client (Custom) app, on the iOS, it gives me the coordinates, but in the standalone app, is not giving me the coordinates. That's the problem. And it occurs only on iOS. And I run the app in foreground and background.

**Comment by EduardoRoc97** [comment]
And, I forgot to mention it, I'm using the background location.

**Comment by brentvatne** [comment]
understood, what i was asking here is what the exact steps are. eg:

1. open the app, keep it foregrounded
2. move around a bit to trigger the update
3. i get update on client but not standalone app

with as much detail as possible. eg: if you don't keep the app foregrounded, what exactly do you do?

**Comment by EduardoRoc97** [comment]
> understood, what i was asking here is what the exact steps are. eg:
> 
> 1. open the app, keep it foregrounded
> 2. move around a bit to trigger the update
> 3. i get update on client but not standalone app
> 
> with as much detail as possible. eg: if you don't keep the app foregrounded, what exactly do you do?

Hi, brentvatne. The problem is the following: when I open my app, in the foreground, it should give me, in the opening, an alert message with the coordinates info (which are given by the BackgroundLocation, ran bu the TaskManager). Unfortunately, in the standalone app, it doesn't happen as expected. That is, I get the update on client, but not in the standalone app when I move around a bit. And I'm referring to this, whether it's foregrounded or backgrounded.

**Comment by byCedric** [comment]
Hi @EduardoRoc97! We recently pushed out some bugfixes for the task manager in the latest Expo Client. Could you try updating to this version and check if you still experience the same issues?

**Comment by thimo1** [comment]
Running latest SDK 39.0.3 Standalone App,  permission set:

`{ "expo": { ... "ios": { ... "infoPlist": { ... "UIBackgroundModes": ["fetch" ] } } } }`

While trying to register task in iOS, still getting following error:
![1B6634A4-A84A-4F25-B5DE-3443E3765780_1_201_a](https://user-images.githubusercontent.com/20241082/97787061-14ace000-1bb0-11eb-8938-e53bdacd81fc.jpeg)

**Comment by brentvatne** [comment]
@thimo1 - make sure that you rebuild after setting that in app.json, it can't be updated OTA

**Comment by thimo1** [comment]
> @thimo1 - make sure that you rebuild after setting that in app.json, it can't be updated OTA

At least permissions work now, thanks. Testing iOS, and Android 9, 10 now.
