### ISSUE TITLE
Metro doesn't resolve nested entrypoint with expo yarn workspaces on SDK 39

### ISSUE THREAD

**Issue by byCedric** [expo/expo#10285]
### Summary of Issue 

For some reason, Metro doesn't resolve the "custom" entrypoint when using `expo-yarn-workspaces`. It keeps failing that it can't resolve `'./__generated__/AppEntry.js' from '';`. When moving the entrypoint to the root of the Expo app (`./AppEntry.js`), it _does_ gets resolved. I've tried these paths:

- `./__generated__/AppEntry.js` — as [mentioned in the docs](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces#define-the-entry-module-in-the-main-field-of-packagejson)
- `./.expo/AppEntry.js` — my own preference, to abstract generated/temp files in the `.expo` folder
- `./AppEntry.js` — Only this one works

This is an unrelated issue, but might also be affected by the same bug. [It's from where I tried to move the app entry to the root.](https://github.com/facebook/metro/issues/330#issuecomment-696033985)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Targeting Android and iOS on SDK 39

```
  Expo CLI 3.27.6 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.10.1 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 21, 26, 28, 29, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0
        System Images: android-22 | Intel x86 Atom_64, android-23 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
    Expo Workflow: managed
```

### Reproducible Demo

It's a bit hard, you need a monorepo for this. I tested this on [`use-expo` monorepo](https://github.com/byCedric/use-expo), you can see this in branches:
- [`metro-entry-issue/good`](https://github.com/byCedric/use-expo/tree/metro-entry-issue/good) — where it works without a nested app entry point
- [`metro-entry-issue/bad`](https://github.com/byCedric/use-expo/tree/metro-entry-issue/bad) — where it doesn't work with a nested app entry point
- [Also see this exact change what will break the metro bundler](https://github.com/byCedric/use-expo/compare/metro-entry-issue/good...metro-entry-issue/bad?expand=1)
 
### Steps to Reproduce

Once you cloned the repo, run the following steps:

- `$ yarn`
- `$ yarn build`
- `$ cd example`
- `$ yarn start`
- Press i to open the iOS simulator
  - See the Metro error on `metro-entry-issue/bad` branch
  - See no Metro error on `metro-entry-issue/good` branch

### Expected Behavior vs Actual Behavior

We either should change the path to non-nested entry points, or find the underlying cause.

**Comment by foolem** [comment]
+1 Having this issue too

**Comment by chadwatson** [comment]
Can confirm. Moving to ./AppEntry.js worked for me as well.
