### ISSUE TITLE
After update sdk 39, app crashed

### ISSUE THREAD

**Issue by choby** [expo/expo#10281]
### Summary of Issue 
I update Expo SDK to 39, but the app crashed.

TypeError: undefined is not an object (evaluating 'self.fetch.bind')

<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:333588:29
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:13
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:331662:13
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:13
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:331427:31
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:13
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:331343:51
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:13
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:286044:29
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:13
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271138:47
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:13
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:128282:54
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:13
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:1335:47
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:13
guardedLoadModule
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:163:46
global code
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:408363:3

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

expo: 39.0.0
react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz
 

if I just use sdk 39 and react-native sdk use 38.0.2 , app is ok. I guess it's the compatibility issues React Native has

**Comment by choby** [comment]
when I removed sdkVersion from app.config app crashed too

**Comment by Haechalas** [comment]
mine too , i cant run myapp on my physical devices it say 39.0.0 is not a valid SDK version. 

i checked my app.json and package its match but still error

**Comment by sjchmiela** [comment]
Hey!

When it comes to `TypeError: undefined is not an object (evaluating 'self.fetch.bind')` — do you have such code in your application? It doesn't look like one that comes from us. 🤔

When it comes to `39.0.0 is not a valid SDK version` — please ensure your Expo client is updated (latest version is `2.17.x`). If you open Expo client and look at the <kbd>Projects</kbd> tab in Expo client, at the bottom there is: <kbd>Client version</kbd> and <kbd>Supported SDKs</kbd>. Latest Expo client on my device shows:

![IMG_8CEA3425DA09-1](https://user-images.githubusercontent.com/1151041/93872688-d0851080-fcd0-11ea-918a-a4ae5d74bd7a.jpeg)

**Comment by choby** [comment]
my Expo client is updated ,and there is no 'self.fetch.bind' in my app, I think there's something wrong with a dependency.


"@react-native-community/async-storage": "~1.12.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "^5.9.6",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@use-expo/font": "^2.0.0",
    "add": "^2.0.6",
    "decimal.js": "^10.2.0",
    "expo": "^39.0.2",
    "expo-av": "~8.6.0",
    "expo-blur": "~8.2.0",
    "expo-camera": "~9.0.0",
    "expo-constants": "~9.2.0",
    "expo-device": "~2.3.0",
    "expo-file-system": "~9.2.0",
    "expo-linear-gradient": "~8.3.0",
    "expo-localization": "~9.0.0",
    "expo-location": "~9.0.0",
    "expo-media-library": "~9.2.1",
    "expo-network": "~2.3.0",
    "expo-notifications": "~0.7.2",
    "expo-permissions": "~9.3.0",
    "expo-random": "~8.3.0",
    "expo-splash-screen": "~0.6.1",
    "i18n-js": "^3.7.1",
    "lodash": "^4.17.19",
    "lottie-react-native": "~2.6.1",
    "mobx": "^5.15.4",
    "mobx-react": "^6.2.2",
    "moment": "^2.27.0",
    "moment-timezone": "^0.5.31",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-moment": "^0.9.7",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-linear-gradient": "~2.5.6",
    "react-native-maps": "0.27.1",
    "react-native-maps-directions": "^1.8.0",
    "react-native-masked-text": "^1.13.0",
    "react-native-masonry-scrollview": "^0.0.2",
    "react-native-navbar": "^2.1.0",
    "react-native-photo-view": "shoutem/react-native-photo-view#0ffa1481f6b6cb8663cb291b7db1d6644440584d",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-svg": "12.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^2.14.2",
    "react-native-vector-icons": "~6.6.0",
    "react-native-web": "^0.13.13",
    "react-native-webview": "10.7.0",
    "reactive": "^2.0.78",
    "sentry-expo": "^2.1.2",
    "umi-request": "^1.3.5",
    "uuid": "^8.1.0",
    "yarn": "^1.22.4"

**Comment by byCedric** [comment]
Hi guys! Without a repro, we can't really investigate this issue. It's most likely that some of your dependencies are referring to a React Native internal that was changed in between `0.62.2` and `0.63.3`. If someone can provide a repro, that would be helpful!

For now I can only suggest taking a look at either of these two issues, they seem to be similar
- https://github.com/facebook/react-native/issues/22956
- https://github.com/facebook/react-native/issues/9599

Hope this helps!

**Comment by Haechalas** [comment]
in my case, I just update the expo cli and when I create a new project app I wont run to my physical devices its said  39.0.0 is not a valid SDK version. my project before updating is fine gladly with sdk 38.0.2
