### ISSUE TITLE
Legacy notifications can handle event in background on android

### ISSUE THREAD

**Issue by sa1dai** [expo/expo#10291]
## 🐛 Bug Report

This is not an issue, but a behavior, that resolves on android (in some case) this feature request: https://expo.canny.io/feature-requests/p/silent-push-notifications

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

 Expo CLI 3.27.7 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.7
    Expo Workflow: managed

### Reproducible Demo

https://snack.expo.io/@maximboychenko1/602a3e
 
### Steps to Reproduce

1. Follow snack link
2. Download as zip
3. Run app on android
4. Copy expo token from console log
5. Background app (press home button)
6. Send push notification via https://expo.io/notifications
7. When push received, in console we could see information about the received notification

### Expected Behavior vs Actual Behavior

So we actually can handle background notification event on android

**Comment by cruzach** [comment]
Since we don't explicitly support this, I don't think we should close the feature request or add documentation around this. Until a feature is reliable, it's not "supported"

**Comment by sa1dai** [comment]
@cruzach 
Ok, it seems that I can't close the issue
