### ISSUE TITLE
Upgrade to SDK 39.0.0 is not working on physical device

### ISSUE THREAD

**Issue by vishalrajole** [expo/expo#10299]
### Summary of Issue 
expo app not working after upgrade 

```
expo --version
3.27.7
```

**expo mobile app is latest available version: 2.16.1**

I tried running multiple options including clearing cache (`~/.expo/cache`) and also by starting app with `SKIP_CACHE=true expo start`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```

expo diagnostics

Expo CLI 3.27.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.2 => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    npmGlobalPackages:
      expo-cli: 3.27.7
    Expo Workflow: bare

```

package.json 

 ```
    "expo": "^39.0.0",
    "expo-font": "~8.3.0",
    "expo-linear-gradient": "~8.3.0",
    "expo-splash-screen": "~0.6.1",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.3",
```

![WhatsApp Image 2020-09-22 at 6 32 38 PM](https://user-images.githubusercontent.com/4668780/93911226-6ab17c80-fd02-11ea-87a0-cc3fd18b7cf1.jpeg)
![WhatsApp Image 2020-09-22 at 6 32 22 PM (1)](https://user-images.githubusercontent.com/4668780/93911222-69804f80-fd02-11ea-9b27-ca9c2287d249.jpeg)
![WhatsApp Image 2020-09-22 at 6 32 22 PM](https://user-images.githubusercontent.com/4668780/93911223-6a18e600-fd02-11ea-921e-4f4b1b253ad4.jpeg)

**Comment by brentvatne** [comment]
plug in your device, run `expo client:install:android`

or, go to google play store and download the latest version of expo client

**Comment by vishalrajole** [comment]
@brentvatne  I do have latest expo client from play store.

![WhatsApp Image 2020-09-22 at 7 07 57 PM](https://user-images.githubusercontent.com/4668780/93914594-0c3acd00-fd07-11ea-8a3f-5b516eeb5f53.jpeg)

**Comment by brentvatne** [comment]
can you try uninstalling and reinstalling it? that's pretty odd

**Comment by vishalrajole** [comment]
Yes I did that already. I checked on two different devices as well. @brentvatne

**Comment by brentvatne** [comment]
can you uninstall, reinstall, open it, and screenshot the projects screen and upload that here?

**Comment by vishalrajole** [comment]
here, it shows SDK version 39
![WhatsApp Image 2020-09-22 at 7 35 32 PM](https://user-images.githubusercontent.com/4668780/93917125-db5c9700-fd0a-11ea-8802-7b9abed18a59.jpeg)

**Comment by brentvatne** [comment]
and now if you load your project from there it should work
