### ISSUE TITLE
Expo-Barcode-Scanner: Can't scan single character barcodes.

### ISSUE THREAD

**Issue by ntoates** [expo/expo#10297]
**Description:**
The expo-barcode-scanner is unable to scan barcodes that only contain a single character on Android. This behavior does not seem to be consistent across all formats though. For example, single character "qr" codes work just fine, however any type I tested in a barcode format did not work (ex. "code-128"). I tested a few different letters and numbers and the barcode was not able to scan any when they were not accompanied by other characters. This issue is not present on iOS with the same app.

This issue existed on SDK 37 as well, however we recently updated to SDK 39 and the issue is still persistent.

**Versions:**  SDK 39

> "expo": "^39.0.0",
> "expo-barcode-scanner": "~9.0.0",
> "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
> expo-cli Version: 3.27.7

**Steps To Reproduce:**
Set up a simple barcode scanner. Attempt to scan any single character barcode (or the one below).

![BarCodeExamples](https://user-images.githubusercontent.com/54894833/93898664-73359300-fcc1-11ea-856b-8f13ab85e62e.png)

_My code:_
```
const handleBarCodeScanned = async ({ type, data }) => {		
	setQuantity(data);
	setScanned(true);
};
...
<BarCodeScanner
    //@ts-ignore
    onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
    style={StyleSheet.absoluteFillObject}
/>
```
**Expected Behavior**
The barcode scanner should be able to scan single character barcodes on Android. This is especially significant if the user is attempting to scan quantity.

**Actual Behavior**
The barcode scanner does not register barcodes with single characters. However QR codes do work for this scenario.

_Update:_ I ran into this same issue using "expo-camera" too.

**Comment by ntoates** [comment]
For anyone running into this same issue, I was able to get my app working correctly by ejecting from expo and using react-native-camera instead.

**Comment by RT-mike** [comment]
Also having this same issue outlined here.

**Comment by fabriziobertoglio1987** [comment]
zxing suggest to crop the area around the barcode to improve the percentage of success 
smaller barcode means smaller cropping area

when I was working on `react-native-camera` I prepared a pr to improve the precision of the cropping in the BarCodeScanner https://github.com/react-native-camera/react-native-camera/pull/2766

but expo-camera and react-native-camera are not exactly the same, so I could be **totally wrong**

https://github.com/expo/expo/blob/78cc872e23796b0617ce828994a75830f701d79c/android/versioned-abis/expoview-abi40_0_0/src/main/java/abi40_0_0/expo/modules/barcodescanner/scanners/ZxingBarCodeScanner.java#L45

I also included step-by-step debugging of this functionality in https://youtu.be/9RQ2GiApkzU?t=824

I'll try to setup my debug environment and troubleshoot this issue in the future .. hopefully I can write a pr. Thanks :pray:

**Comment by fabriziobertoglio1987** [comment]
`result` is `{}`, probably caused by the image that we pass to [`detect`](https://developers.google.com/android/reference/com/google/android/gms/vision/barcode/BarcodeDetector#detect(com.google.android.gms.vision.Frame))

https://github.com/expo/expo/blob/e4945a62bd1c172f790251600b792d62f09e18a7/packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/GMVBarCodeScanner.java#L58

https://developers.google.com/android/reference/com/google/android/gms/vision/Frame
https://github.com/googlesamples/mlkit/issues?q=is%3Aissue+barcode+

**Comment by fabriziobertoglio1987** [comment]
as stated above we use android.gms and not zxing library, the reason it works on `react-native-camera` is that we use `zxing`. 

https://stackoverflow.com/questions/32105132/android-google-play-service-barcode-scanner-does-not-works-on-1d-ean13-barcode#32105820
https://github.com/googlesamples/mlkit/issues/225
https://github.com/firebase/firebase-android-sdk/issues/1698

expo-camera includes `zxing` so I'm planning to add an option to zxing to solve this issue.

**Comment by HeyItsJs** [comment]
Is this any fix / workaround for this? I am still facing the same issue :(
