### ISSUE TITLE
The expo tutorial image picker code doesn't work on sdk 39[docs] 

### ISSUE THREAD

**Issue by Raraku** [expo/expo#10293]
The tutorial on using expo-image-picker doesn't work in sdk 39.
```let pickerResult=await ImagePicker.launchImageLibraryAsync()```
should have some default options passed in as an array or even just an empty array:
```let pickerResult = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      quality: 1,
    })```
or 
```let pickerResult = await ImagePicker.launchImageLibraryAsync({});``` would both work.
I'm a newbie to native and it really gave me some issues.

**Comment by brentvatne** [comment]
sorry about this. there was a regression in `launchImageLibraryAsync` so it required options to be passed in. i've fixed that and the fix to snack should be deployed soon. the fix for local project development has been deployed in expo-image-picker@9.1.1
