### ISSUE TITLE
How to disable Expo namespace warning?

### ISSUE THREAD

**Issue by telmen** [expo/expo#103]
Since Expo.Components moved to root Expo, I've been seeing this warning every time I run an app. How do I disable this? like forever
![image](https://cloud.githubusercontent.com/assets/6022423/24836200/8676cf6e-1d50-11e7-9841-5260538cf2b2.png)

**Comment by sonaye** [comment]
Just change all the snippets in your code where you use the video component from `Expo.Components.Video` to `Expo.Video`.

**Comment by telmen** [comment]
I'm not using Expo.Component.Video anywhere. It just warns me everytime.

**Comment by sonaye** [comment]
Video is just an example, you are importing a component with Expo.Component somewhere.
