### ISSUE TITLE
[TypeScript] expo-linear-gradient not accepting children

### ISSUE THREAD

**Issue by rodneyrehm** [expo/expo#10302]
### Summary of Issue 

Type of `<LinearGradient>` does not accept children.

### Environment

* `expo-linear-gradient@8.3.0`
* `typescript@4.0.3`

### Reproducible Demo

https://docs.expo.io/versions/latest/sdk/linear-gradient/#usage - (if that snack was properly importing LinearGradient in SDK39)

### Expected Behavior vs Actual Behavior

```
Property 'children' does not exist on type 'IntrinsicAttributes & { colors: string[]; locations?: number[] | null | undefined; start?: { x: number; y: number; } | NativeLinearGradientPoint | null | undefined; end?: { ...; } | ... 2 more ... | undefined; } & ViewProps
```

I suppose [LinearGradientProps](https://github.com/expo/expo/blob/sdk-39/packages/expo-linear-gradient/src/LinearGradient.tsx#L9-L45) is missing a `children?: React.ReactNode;`
Additionally [NativeLinearGradientProps](https://github.com/expo/expo/blob/sdk-39/packages/expo-linear-gradient/src/NativeLinearGradient.types.ts#L5) is defining `children?: React.ReactChildren;` (but react itself types everything as `children?: ReactNode`)

**Comment by tylerc** [comment]
Looks like they already have the fix for this https://github.com/expo/expo/pull/10227 https://github.com/expo/expo/commit/7db65dee00cc9fb0395fd8a766deb3cb8a20131c it just needs to be released.
