### ISSUE TITLE
DocumentPicker on iOS 14

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#10303]
### Summary of Issue 

- Opening the DocumentPicker on iOS 14 on a physical device (not simulator) using the App Store client (not a local build from the sdk-39 branch) will crash Expo client
- If you build Expo client locally on sdk-39 branch it will open once, but it will not open a second time if you dismiss it

### Reproducible Demo

https://snack.expo.io/@lolpointerexception/laughing-pizza
 
### Steps to Reproduce

- Run the above Snack on an iOS 14 physical device, press "Pick a document"

**Comment by bbarthec** [comment]
I can confirm that this is happening on published iOS Expo Client from AppStore.

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/10464#issuecomment-703178030
