### ISSUE TITLE
(Expo Development Client, Android app) - Pinning an app from the Expo notification crashes Expo

### ISSUE THREAD

**Issue by luispinho** [expo/expo#10301]
### Summary of Issue

When running an app via the Expo Development Client, a persistent notification is shown. In there, there's an option to pin the app to the Home Screen of the Android device. Pressing this action crashes the Expo app.

### Environment

- Latest Expo Development Client (2.17.2). Although this already occurred with the previous version;
- Oneplus 6 device running Android 10 (OxygenOS);
- Using Nova launcher;
 
### Steps to Reproduce

- Start any app from Expo CLI;
- Scan QR code with Expo Development Client;
- After having the app running, go to the persistent notification and press the "pin" button;
- An "AlertDialog" will say that this will pin the app to the HomeScreen;
- After pressing OK, app crashes;

### Expected Behaviour vs Actual Behaviour
Expected: Expo Development Client should pin the app in the Home screen;
Actual behaviour: Expo Development Client crashes;

**Comment by sjchmiela** [comment]
Hey, thank you for reporting this issue!

Would it be a problem if we said we don't want to support this feature anymore and advise not to use it (in fact it will be removed in the next version of Expo client)?

FWIW I think it should be possible to add an icon to Android home screen that should have the same effect as the icon this "pin" feature would create. If the icon opens `exp://exp.host/@username/slug`, if I'm correct, it will be opened by Expo client.

**Comment by luispinho** [comment]
Hey! Thank you for addressing the issue so quickly. It's no problem at all (after all, I'm in no position of asking for or demanding anything 😅 ). Thanks for the warning.
Hmm ok, that can be a viable alternative. But how exactly can I do that? Would it be through my phone's launcher or through the Expo CLI or client app? Also, is this possible to do without an Expo account? (I think it is given only the URL changes, but it's just to confirm).

Also, unrelated question but one that I think you might be able to answer. For Android, is it possible to clear the app data of an Expo app without clearing the app data of the Expo client app itself?

**Comment by brentvatne** [comment]
if you want to have the app on your home screen the best way to do that is `expo build:android`.  if you want to create a shortcut to the url to open it in expo client, you can google "how to create a shortcut to a url on android" - i'm not actually too familiar with the process, but it's possible.

> Also, is this possible to do without an Expo account?

it could be if you used `expo export`. i'm not sure why you would jump through these hoops though. it's free to make an expo account and do these things.
