### ISSUE TITLE
[docs] Wrong argument listed for notification category

### ISSUE THREAD

**Issue by bill-pairaktaridis** [expo/expo#10314]
According to [this](https://docs.expo.io/versions/latest/sdk/notifications/#addnotificationresponsereceivedlistenerlistener-event-notificationresponse--void-void) we should use `categoryIdentifier` for the Notification category so that we have interactive notifications.

However, if you try using that, nothing happens. `_category` works but it seems to be the old way when this was still an experimental feature. So either the API needs to be updated to support `categoryIdentifier` properly or the documentation needs to be updated.

Note that [here](https://docs.expo.io/push-notifications/sending-notifications/#message-request-format), categories aren't even mentioned.

**Comment by twwspes** [comment]
In my case, categoryIdentifier works on both iOS and Android for local Notifications on expo app, but it crashes on Android standalone app.  _category works on push notification on Android phones when running on expo app, not yet try it on push notification and on iOS though.

**Comment by bill-pairaktaridis** [comment]
I've never tried with local notifications. I use the API directly for my testing. For our backend we do use `expo-server-sdk-ruby` which I assume will just work.

**Comment by bill-pairaktaridis** [comment]
Also worth noting that iOS interactive notifications don't seem to work at all, no matter which attribute I try.

**Comment by cruzach** [comment]
ref https://github.com/expo/expo/issues/10467

iOS interactive notifications seem to be working, if you're running into a problem please open an issue with a minimal reproducible demo

The documentation linked refers to the NotificationContent type, which is specific to the `expo-notifications` package, _not_ the Expo notifications service. The expo notification service does accept a `_category` key which is the category identifier, but it's still experimental (if you find issues with it, feel free to report them). As I mentioned in the other issue, if you're trying to send interactive notifications through Expo's push service **in the Expo client app**, then you need to prefix the `_category` you provide with `@yourExpoUsername/yourProjectSlug-`. Let me know if any of that is unclear and I'm happy to help 😄 

@twwspes could you give me the steps to reproduce the crash you're referring to on android standalone apps? that sounds like a bug I should fix
