### ISSUE TITLE
Warning: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by Razorholt** [expo/expo#10312]
Why is this no longer acceptable in SDK 39?

```
const [MyId, setMyId] = useState("");

function gettheid (responseJson) {
    setMyId(responseJson);
}
```

It generates the following error:

`Warning: Cannot update a component from inside the function body of a different component.`

Does it mean that I can no longer update a useState within a function? I’m confused.

**Comment by byCedric** [comment]
Hi @Razorholt, unfortunately I have no context or clue what's happening here. You should still be able to use all hooks and methods within a functional component as before. If you think this is an issue with Expo, please open a new bug issue and provide the information we ask in the template. Only with a reproducible example we are able to help.

Hope this helps!
