### ISSUE TITLE
[ios] expo SDK 39, Invalid Request token when upload image

### ISSUE THREAD

**Issue by HVHMobileDeveloper** [expo/expo#10313]
### Environment - output of `expo diagnostics` & the platform(s) you're targeting

![image](https://user-images.githubusercontent.com/48771179/93981037-9cc9e980-fda9-11ea-98eb-cdac3eb3c5f5.png)

**Comment by choby** [comment]
I found that the fetch function could not read the temporary files generated by the camera, Later, I solved the problem with the FileSystem.Upload() function

**Comment by gisliorn** [comment]
https://github.com/facebook/react-native/issues/29364

**Comment by butterfly-valley** [comment]
> I found that the fetch function could not read the temporary files generated by the camera, Later, I solved the problem with the FileSystem.Upload() function

Hi, can you share your code, please?

**Comment by choby** [comment]
> > I found that the fetch function could not read the temporary files generated by the camera, Later, I solved the problem with the FileSystem.Upload() function
> 
> Hi, can you share your code, please?

const response = await FileSystem.uploadAsync('apiurl', localUri, {
        uploadType: FileSystemUploadType.MULTIPART,
        httpMethod: "POST",
        headers: {
            Accept: 'application/json',
            'Content-Type': 'multipart/form-data',
            "X-Access-Token": (await sessionStorage.getSession())?.accessToken ?? "",
        },
        fieldName: "file",
        mimeType: "image/jpg",
        parameters: {
            uploadType
        }
    });

**Comment by diegorodriguesvieira** [comment]
> > > I found that the fetch function could not read the temporary files generated by the camera, Later, I solved the problem with the FileSystem.Upload() function
> > 
> > 
> > Hi, can you share your code, please?
> 
> ```js
> import * as FileSystem from 'expo-file-system';
> import { FileSystemUploadType } from "expo-file-system";
> 
> const response = await FileSystem.uploadAsync('apiurl', localUri, {
>         uploadType: FileSystemUploadType.MULTIPART,
>         httpMethod: "POST",
>         headers: {
>             Accept: 'application/json',
>             'Content-Type': 'multipart/form-data',
>         },
>         fieldName: "file",
>         mimeType: "image/jpg",
>         parameters: {
>             uploadType
>         }
>     });
> ```

It works!

**Comment by Hirbod** [comment]
While this might be a workaround, its not a fix. We actually will need to hope for a expo cherry pick or bugfix release

**Comment by butterfly-valley** [comment]
> > > > I found that the fetch function could not read the temporary files generated by the camera, Later, I solved the problem with the FileSystem.Upload() function
> > > 
> > > 
> > > Hi, can you share your code, please?
> > 
> > 
> > ```js
> > import * as FileSystem from 'expo-file-system';
> > import { FileSystemUploadType } from "expo-file-system";
> > 
> > const response = await FileSystem.uploadAsync('apiurl', localUri, {
> >         uploadType: FileSystemUploadType.MULTIPART,
> >         httpMethod: "POST",
> >         headers: {
> >             Accept: 'application/json',
> >             'Content-Type': 'multipart/form-data',
> >         },
> >         fieldName: "file",
> >         mimeType: "image/jpg",
> >         parameters: {
> >             uploadType
> >         }
> >     });
> > ```
> 
> It works!

Can confirm! Works on both Android and iOS, cheers!

**Comment by haciSeydaoglu** [comment]
The solution here worked for me: https://github.com/facebook/react-native/issues/29364#issuecomment-695352974

**Comment by Hirbod** [comment]
@HVHMobileDeveloper don't close this issue please. Reopen, its not resolved

**Comment by HVHMobileDeveloper** [comment]
use FileSystem.uploadAsync work for me,

**Comment by Hirbod** [comment]
Its still an issue, just reopen it please

**Comment by HVHMobileDeveloper** [comment]
> Its still an issue, just reopen it please
I just reopened again, please investigate as soon as possible

**Comment by YuntongLi6543** [comment]
Still have the problem using formdata, "expo": "^39.0.3"

**Comment by brentvatne** [comment]
can someone share a mcve? https://stackoverflow.com/help/mcve

**Comment by georgeMorales** [comment]
I also have a problem when trying to upload an image to the server with iOS, in sdk 38 and later it worked perfectly, but in sdk 39 the application does not break, nor do they appear warning, but the image is saved in Firebase Storage with a format application /octet-stream and 0 bytes, in the application you see a transparent image.
I don't know if it is related to this matter.
Thank you!

**Comment by karanmartian** [comment]
> I also have a problem when trying to upload an image to the server with iOS, in sdk 38 and later it worked perfectly, but in sdk 39 the application does not break, nor do they appear warning, but the image is saved in Firebase Storage with a format application /octet-stream and 0 bytes, in the application you see a transparent image.
> I don't know if it is related to this matter.
> Thank you!

No your issue is different. not related to this.

**Comment by karanmartian** [comment]
> can someone share a mcve? https://stackoverflow.com/help/mcve. it seems like this might be a bug in react-native mentioned earlier, which appears to have been solved ~9 days ago, and so it isn't part of a stable react-native release yet. [facebook/react-native#29364 (comment)](https://github.com/facebook/react-native/issues/29364#issuecomment-693550094)
> 
> also, like @HVHMobileDeveloper suggested you can use `FileSystem.uploadAsync` instead of formdata. this also has the benefit of letting you specify a `sessionType` so that the upload works when the app is backgrounded. https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemuploadasyncurl-fileuri-options

Ok going with the FS uploadAsync solution for now. And just to confirm this is an iOS issue only. Android works fine.

**Comment by karanmartian** [comment]
Hi all, I am using Hapi Server at backend to receive the image. The example of node server given here is in Express: https://docs.expo.io/versions/v39.0.0/sdk/filesystem/

Can someone please guide with a quick Hapi code snippet?

**Comment by cseelus** [comment]
Hi @brentvatne, thanks for the fast response, as always 👍 

Here is a minimal example: https://github.com/cseelus/expo-issue-10313

**Comment by svaldi** [comment]
A new version of React Native v0.63.3 has been released. Is there any plan to patch this bug on expo 39? 

https://github.com/facebook/react-native/releases/tag/v0.63.3

**Comment by brentvatne** [comment]
@svaldi - can you point to the commit or PR that fixes this?

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/10464#issuecomment-703178030

**Comment by jjmontalbo** [comment]
https://github.com/facebook/react-native/commit/2c5d4cba5c02f6cdf9fb02c78ffd155ad95298d0 does not seem to be included in https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz

I am still getting the issue on iOS after upgrading to the SDK 39++ bug fix.

**Comment by brentvatne** [comment]
@jjmontalbo - you need to update your expo client app or rebuild your standalone app. it's not necessary for us to include the commit in the fork because it's purely a native change and the only purpose of our fork is to serve the relevant js. here is the relevant commit for you: https://github.com/expo/expo/commit/19dddb31633d2224aad639767c089e72b2b09c86
