### ISSUE TITLE
[exp] Android: There was an error with this build.

### ISSUE THREAD

**Issue by saivyas** [expo/expo#1031]
Till yesterday it worked fine.But now when I am trying to build getting error like this.
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] Android: There was an error with this build.

my app.json

```
{
  "expo": {
    "name": "Appname",
    "description": " ",
    "slug": "app expo,
    "privacy": "public",
    "sdkVersion": "22.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "notification":{
      "icon":"./assets/app-icon_48_48.png",
    },
    "icon": "./assets/app-icon.png",
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "mp4"
      ]
    },
    "ios": {
      "supportsTablet": true,
    },
    "android": {
     "package": "com.appexpo",
     "versionCode":1,
     "permissions":[],
   }
  }
}
```

**Comment by jesseruder** [comment]
`slug` shouldn't have any spaces in it. Can you fix that first and then if you hit another error send us your build id?

**Comment by iSaadSalman** [comment]
@jesseruder Can You help me please. I tried to build multiple times but it keeps failing: build # 8e031186-3777-4f2f-b594-0c84b77bfe14

**Comment by iSaadSalman** [comment]
@jesseruder It for iOS btw

**Comment by jesseruder** [comment]
Sorry it looks like there was a temporary issue with our build server. Can you try again?

**Comment by iSaadSalman** [comment]
Ran again. Still got that issue. Build: 1ebdedc2-dfd1-4061-8286-5d28f662bf75

**Comment by jesseruder** [comment]
This time I see this error message:
> No signing certificate \"iOS Distribution\" found
> No \"iOS Distribution\" signing certificate matching team ID \"REDACTED\" with a private key was found

We just released an update to `exp` that does some of this locally on your computer. Can you download the latest version of `exp` and try `exp build:ios --local-auth -c` instead?

**Comment by iSaadSalman** [comment]
Tried. Got this error

`Reason:Unable to find a team with the given Team ID 'TEAM_ID' to which you belong.  Please contact Apple Developer Program Support. https://developer.apple.com/support Unable to find a team with the given Team ID 'TEAM_ID' to which you belong.  Please contact Apple Developer Program Support. https://developer.apple.com/support, raw:{"responseId":"9e467008-89a7-44d4-9418-1c138f80799e","resultCode":3100,"resultString":"Unable to find a team with the given Team ID 'TEAM_ID' to which you belong.  Please contact Apple Developer Program Support. https://developer.apple.com/support","userString":"Unable to find a team with the given Team ID 'TEAM_ID' to which you belong.  Please contact Apple Developer Program Support. https://developer.apple.com/support","creationTimestamp":"2017-12-01T02:23:02Z","protocolVersion":"QH65B2","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/listCertRequests.action","httpCode":200}`

**Comment by jesseruder** [comment]
Ok thanks for trying. @fxfactorial can you take a look at this?

**Comment by fxfactorial** [comment]
@iSaadSalman `TEAM_ID` is not a valid value, can you say the steps you did?

**Comment by terribleben** [comment]
Hi, we've pushed a bunch of improvements to this in the last month, and this thread contains a few different reports now. Please update `exp`, try again, and if you run into more trouble, please open a new issue with the error information. Thanks!
