### ISSUE TITLE
in-app-purchases - proper way of fetching purchases

### ISSUE THREAD

**Issue by vtsybulin** [expo/expo#10315]
Hi. Help wanted 🤔 
As per https://docs.expo.io/versions/latest/sdk/in-app-purchases latest updates, automatic purchases fetching was excluded from `connectAsync` method for the sake of resolving iOS issues, which is good as it doesn't interrupt user flow anymore, tho cant see a new proper way of initial purchases fetching. It was previously working fine for me since I was getting current purchases from `connectAsync` as follows:
`const {responseCode, results: purchases } = await InAppPurchases.connectAsync();`
and to get a full purchase history once could use `getPurchaseHistoryAsync ` method. Now, `getPurchaseHistoryAsync` seems like the only way to get purchases and now I can't see any mention of how to properly fetch and determine currently active purchases (if the app uses a subscription model) as it returns a full history along with already expired once.
I'm not sure if this is the intended behavior but I don't see any mention of it in the docs.

Correct me if I'm wrong and the only way to do so atm is to use receipts validation?

**Comment by darrylyoung** [comment]
Hi, @vtsybulin. I'm also just setting up in-app purchases and when trying to deal with restoring, I have the same question. I get an array of all the _purchases_ back but I'm not sure the best way to then verify if there's a currently active subscription. Did you get anywhere with this since posting? Thanks!

**Comment by vtsybulin** [comment]
@darrylyoung 👋 didn't make it up, was on a tight deadline for release thus switched to a vendor (revenuecat). The only I can think of is manual receipt validation https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store)

**Comment by darrylyoung** [comment]
@vtsybulin Thanks for the reply. Yeah, I came across that link last night and have it, for the most part, set up and working now. I pass the `transactionReceipt` to my server, build the request body, and hit the validation endpoint. I had to make sure I was using the sandbox URL but I'm getting a response as expected so I guess this is the way to go. Hopefully gonna finish this stuff today.

Have a good day. 👍

**Comment by cruzach** [comment]
Utilizing the `verifyReceipt` is the recommended route here. You can use the data you get back from your purchase (aka [the IAPurchase object](https://docs.expo.dev/versions/latest/sdk/in-app-purchases/#inapppurchase)) to determine when a subscription is active or not, based on the `purchaseTime` and the `IAPItemDetails`'s `subscriptionPeriod`

Let me know if there's still any remaining questions here, I'm happy to help (but will close this issue for now)
