### ISSUE TITLE
[sdk39][expo-notifications] Still in sdk39 the notification is not triggered in the background.

### ISSUE THREAD

**Issue by Woong25** [expo/expo#10318]
### Summary of Issue 
Still in sdk39 the notification is not triggered in the background.
But it runs fine in the foreground.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
`Expo CLI 3.27.7 environment info:

    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\ST\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^39.0.0 => 39.0.2
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.13
      react-navigation: ^4.4.0 => 4.4.0
    Expo Workflow: managed
`

### Reproducible Demo
https://github.com/sjchmiela/expo-notifications-initial-notification-test/blob/master/App.tsx
https://gist.github.com/cruzach/eadbf47990e57b9ff4c808dd377d44c7
Besides this, there are many ways...

The splash screen loads and nothing happens
Hasn't it been fixed yet?

**Comment by cruzach** [comment]
I believe this is the same as - https://github.com/expo/expo/issues/10357

can you confirm that using local notifications works as expected for you?

**Comment by cruzach** [comment]
going to tentatively close this, if you can provide a minimal reproducible demo I'm happy to investigate further
