### ISSUE TITLE
Reanimated v2 console.log() in doesn't display complex values

### ISSUE THREAD

**Issue by wcandillon** [expo/expo#10322]
## 🐛 Bug Report

Whereas the following works well:

```ts
const log = () => {
"worklet";
console.log("hello");
}

//...
runOnUI(log)();
```

This will throw an error:

```ts
const log = () => {
"worklet";
console.log({ c: 1 });
}

//...
runOnUI(log)();
```

![Simulator Screen Shot - iPhone 11 - 2020-09-23 at 14 57 01](https://user-images.githubusercontent.com/306134/94015419-20390a00-fdad-11ea-9227-a82802697d03.png)

**Comment by wcandillon** [comment]
oups my mistake ;-)

**Comment by byCedric** [comment]
Hi @wcandillon, thanks for the report! It could be related to how we mix up both Reanimated v1 and v2 in managed. Assuming you use the managed workflow on SDK 39, right?

**Comment by wcandillon** [comment]
that's correct indeed
