### ISSUE TITLE
[expo-av] Video controller doesn't appear

### ISSUE THREAD

**Issue by norasteria** [expo/expo#10320]
Hi all, I just working on making a video playlist player using expo-av. The issue is, the video controller does not appear in several devices. In my own device Android Oreo, it works properly, but it doesn't in my emulator (Android Lollipop API 22) and my partner phone with a similar Android version. Here is my code: 

```
export default (props) => {
  const videoRef = useRef();
  const [isVideoFinish, setVideoFinish] = useState(false);
  const { selectedLesson } = useSelector(({ courseProps }) => courseProps);
  let { content: noSplitVideo, title, timebar, lesson_split } = selectedLesson;
  const [lessonIndex, setLessonIndex] = useState(0);

  useEffect(() => {
    // init video source
    (async function () {
      if (!lessonIndex && !isVideoFinish) {
        const srcUrl = lesson_split.length
          ? lesson_split[0].video
          : noSplitVideo;
        const source = { uri: VIDEO_BASE_URL + srcUrl };
          await videoRef.current.loadAsync(source, {
            useNativeControls: true,
            shouldPlay: true,
            positionMillis: timebar * 1000,
          });
        }
    })();

    if (isVideoFinish) onVideoFinish();
  }, [isVideoFinish, videoRef.current]);

  const savePlaybackData = (videoData) => {
    const { durationMillis, positionMillis } = videoData;
    const newVideoState = durationMillis && durationMillis === positionMillis;

    if (isVideoFinish !== newVideoState && newVideoState !== undefined) {
      setVideoFinish(newVideoState);
    }
  };

  const onVideoReplay = async () => {
    await videoRef.current.setStatusAsync({ positionMillis: 0 });
  };

  const onVideoFinish = async () => {
    const nextIndex = lessonIndex + 1;

    if (!lesson_split[nextIndex]) return;

    const { video } = lesson_split[nextIndex];

    setLessonIndex(nextIndex);
    const source = { uri: VIDEO_BASE_URL + video };
    await videoRef.current.loadAsync(source, {
      useNativeControls: true,
      shouldPlay: true,
      positionMillis: 0,
    });
  };

  return (
      <View style={{ alignItems: "center", padding: 0 }}>
        <Video
          ref={videoRef}
          useNativeControls
          rate={1.0}
          volume={1.0}
          isMuted={false}
          resizeMode={Video.RESIZE_MODE_CONTAIN}
          onPlaybackStatusUpdate={savePlaybackData}
        />
      </View>
  );
};
```

The other way to execute  I've done is to initialize the `loadAsync` process inside the `ref` function just like this reference https://github.com/expo/playlist-example/blob/master/App.js, but it did not give me any different result. I really appreciate all of you who have a willingness to put your effort to discuss more this issue. Thanks a bunch!

I am using: 
- Expo SDK 38
- expo-av 8.2.1

The output of `expo diagnostics`:
  Expo CLI 3.27.4 environment info:
    System:
      OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.7 - ~/.npm-global/bin/npm
    SDKs:
      Android SDK:
        API Levels: 18, 21, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-18 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom
    npmPackages:
      expo: ^38.0.0 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: managed

**Comment by byCedric** [comment]
From issue #10346:

> Still continuing this [issue](https://github.com/expo/expo/issues/10320), I've got error message `[Error: d.g.b.d.j0.n$b: AudioTrack init failed: 0, Config(44100, 12, 44100)]` after adding catch function of `loadAsync`

**Comment by norasteria** [comment]
> From issue #10346:
> 
> > Still continuing this [issue](https://github.com/expo/expo/issues/10320), I've got error message `[Error: d.g.b.d.j0.n$b: AudioTrack init failed: 0, Config(44100, 12, 44100)]` after adding catch function of `loadAsync`

okay, thank you very much, but I'm still waiting for any response to this issue. I hope you guys noticed.

**Comment by DJAG95** [comment]
I have the same problem, mine is caused by playing a sound of about 0.3 seconds, several times, depending on the device, stops working at 6 to 14 times, in the case of a Samsung A51, never fails

I think it has to do with the memory management of the device
but they also have different versions of Android

I will inform about the news

**Comment by norasteria** [comment]
> and then I release

Thank you very much for your contribution. In my case, I can't even see the video controller in the first play. But lately, I just tricked it by creating my own video controller that builds from [Slider](https://docs.expo.io/versions/latest/sdk/slider/) and other display such as a timer which I calculated myself by dividing duration time and playing time.

**Comment by norasteria** [comment]
> I have the same problem, mine is caused by playing a sound of about 0.3 seconds, several times, depending on the device, stops working at 6 to 14 times, in the case of a Samsung A51, never fails
> 
> I think it has to do with the memory management of the device
> but they also have different versions of Android
> 
> I will inform about the news
> 
> Updated - 18:48
> 
> I solved my problem, mine, had to do with memory management, maybe android 10 has a better garbage collector than android 7 and that's why I couldn't reproduce this problem in Android 10.
> 
> my problem was that it either did not release the memory assigned to this clip, or did not allow time to play this clip and release it, I have solved it in a slightly manual way.
> 
> My sound takes less than 1000 ms to play, so I added a homemade Sleep to be able to wait for it to play, and then I released the memory
> 
> it looks like this
> 
> `
> 
> ```
> async reproduceSuccess(){
>    var soundObject = new Audio.Sound();
>       try {
>           await soundObject.loadAsync(require('url_to_sound'));
>           await soundObject.playAsync();
>           await this.sleep(1000);
>           await soundObject.unloadAsync();
> ```
> 
> ```
>   } catch (error) {
>     console.log(error);
>   }
>   
> },
> sleep(ms) {
>   return new Promise((resolve) => {
>     setTimeout(resolve, ms);
>   });
> },
> ```
> 
> `
> 
> I hope your problems can be related, and you can solve them too
> 
> Greetings!

Thank you very much for your contribution. In my case, I can't even see the video controller in the first play. But lately, I just tricked it by creating my own video controller that builds from Slider and other display such as a timer which I calculated myself by dividing duration time and playing time.
