### ISSUE TITLE
SDK 39 problem with Formik

### ISSUE THREAD

**Issue by ph-sw** [expo/expo#10326]
### Summary of Issue 
Just updated to SDK 39 - and updated Formik also to 2.1.5. This gives me a warning ("Reacy.createElement: type is invalid") and two Component Exceptions (both "Element type is invalid") from Formik's code. Same error was seen with SDK 39 and Formik 2.1.4. This worked on SDK 37 and Formik 2.1.4.

Does anybody else had problems with SDK 39 and Formik?

![93930267-164ed280-fceb-11ea-8e19-9954eff2fe69](https://user-images.githubusercontent.com/59928201/94019426-c706b180-fd7f-11ea-923d-185e45aff267.png)
![93930296-21a1fe00-fceb-11ea-9634-07ea6fd9e3da](https://user-images.githubusercontent.com/59928201/94019436-cb32cf00-fd7f-11ea-8c1d-095111cdb71b.png)
![93930317-2b2b6600-fceb-11ea-98c5-9e430c43a4ea](https://user-images.githubusercontent.com/59928201/94019448-cd952900-fd7f-11ea-944b-61da7c605209.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
MacOS 10.15.6 with EXPO SDK 39
{
"main": "node_modules/expo/AppEntry.js",
"scripts": {
"start": "expo start",
"android": "expo start --android",
"ios": "expo start --ios",
"web": "expo start --web",
"eject": "expo eject"
},
"dependencies": {
"expo": "^39.0.0",
"expo-status-bar": "~1.0.2",
"formik": "^2.1.5",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
"react-native-web": "~0.13.7"
},
"devDependencies": {
"@babel/core": "^7.8.6",
"babel-preset-expo": "^8.3.0"
},
"private": true
}

### Reproducible Demo
These are the crash reports on iOS simulator (SE2 w/ iOS14)
![93934975-e7882a80-fcf1-11ea-8932-51704abba3c6](https://user-images.githubusercontent.com/59928201/94019225-85760680-fd7f-11ea-959d-59c582c3ba8e.png)

**Comment by byCedric** [comment]
Hi @ph-sw! Unfortunately, I'm not able to reproduce this. You can [see this snack running on SDK 39](https://snack.expo.io/@bycedric/expo-sdk-39-formik), without issues. There are a lot of squiggly lines in your screenshot, I guess there is something going on in your project. But without a repro, I can't tell what that would be.

If you still think this is an issue with Expo, please provide either a Snack or repo for us to investigate.

Hope this helps!
