### ISSUE TITLE
getDevicePushTokenAsync - Standalone App

### ISSUE THREAD

**Issue by davidortizfrau** [expo/expo#1032]
Installed **APK** file in android. When invoking the getDevicePushTokenAsync method, im getting error.

`ExponentNotifications.getDevicePushTokenAsync got 2 arguments, expected 3`

**Comment by jesseruder** [comment]
Hi, we just updated the docs here: https://docs.expo.io/versions/latest/sdk/notifications.html#exponotificationsgetdevicepushtokenasyncconfig

Can you make sure you're passing in `config` and see if that works?
