### ISSUE TITLE
[iOS] An exception was thrown while calling `ExpoInAppPurchases.getPurchaseHistoryAsync` with arguments `(     "<null>" )`: -[NSNull boolValue]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/expo#10332]
### Summary of Issue 
```const history = await InAppPurchases.getPurchaseHistoryAsync()```
throws the error
```
An exception was thrown while calling `ExpoInAppPurchases.getPurchaseHistoryAsync` with arguments `(
    "<null>"
)`: -[NSNull boolValue]: unrecognized selector sent to instance
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

iOS
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: 37.0.12 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-native: 0.61.4 => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.17.15

Note: I am using "expo-in-app-purchases": "^9.1.0"

### Expected Behavior vs Actual Behavior

Is this because I'm using a new version of `"expo-in-app-purchases": "^9.1.0",` to fix another issue? Do I need to update expo now? I updated it to fix an issue for compiling in Xcode 12.

**Comment by valentinchelle** [comment]
I fixed the problem by calling `await InAppPurchases.getPurchaseHistoryAsync(true)`. The argument `refresh` doesn't seem to be optional.
