### ISSUE TITLE
A black screen shows before loading the splash screen in iOS & Android

### ISSUE THREAD

**Issue by debianw** [expo/expo#10330]
### Summary of Issue 
First a black screen would show.
And then the splash screen shows with bundle loading progress bar

Note: Is initial View Controller is checked

### Environment
Expo SDK 39 with bare minimum template
xcode 12
iOS 14
Android 10
 
### Steps to Reproduce
Create bare minimum template with expo.
Follow the readme for iOS and Android
https://github.com/expo/expo/tree/master/packages/expo-splash-screen
Run it in an iOS Emulator
Run it in a real android device 

### Expected Behavior vs Actual Behavior
Splashscreen should show right away after opening the app, instead a black screen shows for like 200ms and then the real splashscreen show up.

In the case of Android it shows a colored screen (depending which background color you set) for like 200ms and then the real splashscreen show up

**Comment by byCedric** [comment]
Hi @debianw, thanks for the issue report. Unfortunately, I can't seem to reproduce it when creating a new bare project. Could you share a repo with this behavior?
