### ISSUE TITLE
[EXPO-UPDATES] Crash on IOS build

### ISSUE THREAD

**Issue by LouisJS** [expo/expo#10331]
### Summary of Issue 

We have installed `expo-unimodules` and `expo-updates` in our app in bare workflow.
It works fine on **Android**, however, on **iOS**, the app crash when we make an archive. (It runs in dev mode in simulator).

We've tried to update some part of our file :
- Update some part in AppDelegate.m
- Change release channel

But without results

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.2 => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.25.1

### Reproducible Demo

ios/Supporting/Expo.plist: https://pastebin.pl/view/929e7ec3
ios/XXX/AppDelegate.m: https://pastebin.pl/view/bfe2cfb4
ios/XXX/AppDelegate.h: https://pastebin.pl/view/6ccc6725

### Expected Behavior vs Actual Behavior

Testing a build on an iPhone (physical device) -> It causes a crash almost instantly. Available here https://pastebin.pl/view/adcae3ca

Also:
- In appDelegate we've set the behavior of the build to the "DEBUG" condition to run it in simulator as it runs in the build.
```
#ifdef DEBUG
    EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
    controller.delegate = self;
    [controller startAndShowLaunchScreen:self.window];
  #else
    [self initializeReactNativeApp];
  #endif
```

And we end up with an error :
```
2020-09-23 17:50:07.181280+0200 Blank Staging[62141:3201597] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'expo-updates is enabled, but no valid URL is configured under EXUpdatesURL. If you are making a release build for the first time, make sure you have run `expo publish` at least once.'
```

Our publications are up and running, they appears in `expo publish:history` and works fine on Android build.

Would you have a github repo with a valid AppDelegate.m ?
We're also using `RNSplashScreen` / `BugBattle` / `RNNotifications`. And maybe the move from `didFinishLaunchingWithOptions` to `initializeReactNativeApp` is causing issue ? But how do we do then ?

Thank you for your time. Louis

**Comment by LouisJS** [comment]
We fix our issue : Here's how we did :

- On line
`74: RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"blank" initialProperties:nil];`

Check that your module name is the right one. 

- Expo.plist
You should **absolutely** drag and drop your `Expo.plist` file in your Project folder INSIDE XCode. This is a step that is quite poorly documented in expo-update. Best way to check that you did it right is that you should see in your file `pbxproj` lines like :

```
B3171EBF251BB3F3000A8985 /* Expo.plist in Resources */ = {isa = PBXBuildFile; fileRef = B3171EBE251BB3F2000A8985 /* Expo.plist */; };
B3171EC5251C8EC5000A8985 /* Supporting in Resources */ = {isa = PBXBuildFile; fileRef = B3171EC4251C8EC5000A8985 /* Supporting */; };
```

If it is at some point `null`, that is not right. The way we saw it was inside our Pull Request from our `Expo updates implementation`.

- AppDelegate.m

You should spend some time to try to read and understand it. You should have a `didFinishLaunchingWithOptions` and a clear `initializeReactNativeApp`.

Our AppDelegate.m looks like [this](https://pastebin.pl/view/79a19939). And we have additional dependencies such as React Native Splashscreen, React Native notifications or BugBattle.

I strongly believe that Expo should provide a link to this file example in their docs, instead of just showing diff.
It is very confusing IMO.


That's it. The Expo.plist tricks, the correct modulename, and quite a lot of time spent on AppDelegate.m structure did the trick ! We can enjoy expo-updates in bare workflow now ! :D

**Comment by LouisJS** [comment]
@EvanBacon @brentvatne
Do you think these advice could help in the Expo documentation ? Should i tried to make a PR to improve it or you could transfer these to someone in charge in Expo Team ?

Hope that could help !

**Comment by svm1** [comment]
Hey @LouisJS thanks for posting about your experience and solution. I am currently facing the exact same issue after ejecting my app from Expo. I strongly agree that the diff documentation on Expo's site is extremely confusing, having a sample file would make it much easier. Thanks for posting your solution and files.

If you don't mind, could you elaborate on what the modulename should be? I figured it should be the app 'name' in `app.json` but just want to be sure. I took a look at your `AppDelegate.m` and made sure my `Expo.plist` is in the project folder and being read from. Still seeing the same error though...

**Comment by Servo97** [comment]
> We fix our issue : Here's how we did :
> 
> * On line
>   `74: RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"blank" initialProperties:nil];`
> 
> Check that your module name is the right one. We've had confusing time to understand which one to chose. (we're probably a bit stupid idk)
> 
> * Expo.plist
>   You should **absolutely** drag and drop your `Expo.plist` file in your Project folder INSIDE XCode. This is a step that is quite poorly documented in expo-update. Best way to check that you did it right is that you should see in your file `pbxproj` lines like :
> 
> ```
> B3171EBF251BB3F3000A8985 /* Expo.plist in Resources */ = {isa = PBXBuildFile; fileRef = B3171EBE251BB3F2000A8985 /* Expo.plist */; };
> B3171EC5251C8EC5000A8985 /* Supporting in Resources */ = {isa = PBXBuildFile; fileRef = B3171EC4251C8EC5000A8985 /* Supporting */; };
> ```
> 
> If it is at some point `null`, that is not right. The way we saw it was inside our Pull Request from our `Expo updates implementation`.
> 
> * AppDelegate.m
> 
> You should spend some time to try to read and understand it. You should have a `didFinishLaunchingWithOptions` and a clear `initializeReactNativeApp` functions.
> 
> Our AppDelegate.m looks like [this](https://pastebin.pl/view/79a19939) now. And we have additional dependencies such as React Native Splashscreen, React Native notifications or BugBattle.
> 
> I strongly believe that Expo should provide a link to a file example in their docs, instead of just showing a part of it as a diff.
> It is very confusing IMO. As dev implementing it, i'd like to be able to check line by line what the example is, and what i'm doing on my side.
> 
> That's it. The Expo.plist tricks, the correct modulename, and quite a lot of time spent on AppDelegate.m structure did the trick ! We can enjoy expo-updates in bare workflow now ! :D

You Rock!
