### ISSUE TITLE
Unrecognized font family

### ISSUE THREAD

**Issue by jayeszee** [expo/expo#1033]
I seem to be having an issue after upgrading from 22 to 23 with the fonts icons used by native base or react native elements. In both cases, the loadAsync() function of expo doesn't seem to be loading the fonts where in the previous version it was doing that for the same code. 

![image](https://user-images.githubusercontent.com/10326244/33450645-588f12b2-d5c1-11e7-8f12-4ca23fbb551e.png)

what i had before:
![image](https://user-images.githubusercontent.com/10326244/33450707-894dd622-d5c1-11e7-93d2-673fd80e72e5.png)

what i refactored into:
![image](https://user-images.githubusercontent.com/10326244/33450762-b6abf43c-d5c1-11e7-808f-f2514beb4bb4.png)

"@expo/vector-icons": "^6.2.0"
"react-native": "^0.50.4"
"react": "16.0.0"
"native-base": "2.3.1"
"react-native-elements": "^0.18.4"
"expo": "^23.0.4"

**Comment by brentvatne** [comment]
need more context on the code but it looks like you're not waiting for that to actually finish, you're just firing it off. it's not a synchronous function -- when `Font.loadAsync(Ionicons.font)` is executed, it moves ahead to the next line and runs the next one. at some time in the future it finishes, but unless you use `await` or `.then`, it won't work

**Comment by brentvatne** [comment]
see this for an example of how to do it: https://github.com/expo/new-project-template/blob/master/App.js#L12-L47

**Comment by jayeszee** [comment]
@brentvatne i changed it and it still breaks. I wrote in issue https://github.com/expo/vector-icons/issues/31 But thanks for catching the part about the async functions not being awaited

**Comment by brentvatne** [comment]
https://github.com/expo/vector-icons/issues/31 contains info about the fix :)
