### ISSUE TITLE
Expo SDK 39 DocumentPicker.getDocumentAsync() crashes on iOS (Expo client on real device)

### ISSUE THREAD

**Issue by butterfly-valley** [expo/expo#10348]
### Summary of Issue
Working fine until upgrading to SDK 39. 

### Environment 
Expo CLI 3.27.7 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/bin/node
      npm: 6.14.6 - /usr/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    npmGlobalPackages:
      expo-cli: 3.27.7
    Expo Workflow: managed

### Reproducible Demo

https://snack.expo.io/@sobrius/doc-picker

It does open the picker using this Snack but crashes on my real device

 
### Steps to Reproduce

click on button

### Expected Behavior vs Actual Behavior

Open document picker (pdf)

**Comment by colinfwren** [comment]
Had a similar issue, here's my forum post https://forums.expo.io/t/getdocumentasync-crashing-expo-client-on-ios-device-after-v39-upgrade/43151/5 

Looks like it's only iOS 14 that causes it as 13.7 running on an iPhone X didn't have the issue

**Comment by butterfly-valley** [comment]
I do not believe iOS 14 is the culprit since everything was running fine on iOS 14 before upgrading the SDK

**Comment by colinfwren** [comment]
> I do not believe iOS 14 is the culprit since everything was running fine on iOS 14 before upgrading the SDK

Sorry to clarify I mean it's iOS 14 that's causing the combination of expo-document-picker 8.4.0 and Expo 39 to crash

**Comment by bogoslavskiy** [comment]
Same problem, only iOS 14 and Expo 39

**Comment by brentvatne** [comment]
known issue, fix is coming next week. https://github.com/expo/expo/issues/10303

**Comment by shye0000** [comment]
> known issue, fix is coming next week. #10303

so the fix will be released anytime this week, right?

**Comment by dommangetnicolas** [comment]
> known issue, fix is coming next week. #10303

Doesn't work for us on standalone app. Everything works fine on Expo client, but with TestFlight and/or Ad Hoc built with turtle CLI is crashes...

We are using:
`"expo": "~39.0.3",`
`"expo-document-picker": "~8.4.0"`
`"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",`

**Comment by sXakil** [comment]
> > known issue, fix is coming next week. #10303
> 
> Doesn't work for us on standalone app. Everything works fine on Expo client, but with TestFlight and/or Ad Hoc built with turtle CLI is crashes...
> 
> We are using: `"expo": "~39.0.3",` `"expo-document-picker": "~8.4.0"` `"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",`

Having the same issue, TestFlight on Mac freezes after picking a document. The simulator and real device work fine tho.
