### ISSUE TITLE
App is crashing in Starter Project with Bare Workflow

### ISSUE THREAD

**Issue by jawil003** [expo/expo#10343]
### Summary of Issue 

When I eject a `expo init` Typescript Project, and I eject to get into the Bare-Workflow, After building the Android App the App crashes, for an unknown Reason (no Stacktrace available). Just some warnings about used features are deprecated with Gradle 7. But Android Studio says I use Gradle 6 .3 so I guess that should be no Problem.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

OS: Windows 10
JDK: 8
Python: 3.8
Editor: VS-Code
Gradle: 6.3

### Reproducible Demo

https://github.com/jawil003/expo-eject-demo
 
### Steps to Reproduce

1. Install Expo CLI
2. Run Init Command to generate a Typescript Starter
3. Run `eject` to come into bare workflow
4. See that  Android Emulator is open
5. See opening App crashing

### Expected Behavior vs Actual Behavior

App should lauch and work as before ejecting.

**Comment by brentvatne** [comment]
please google your error message and try to debug the issue you're encountering. this is an issue with your environment setup. also run `npx react-native doctor`

**Comment by jawil003** [comment]
React Doctor only says I need to install Python 2 but Stackoverflow says it isn't necessary... Anything else is installed Android SDK latest, Java 8 etc. I tested a react-native-starter and it worked... So maybe this Gradle Issue is come from a expo Libary. 
I really don't know what to try, so do you have at least an Idea what could be wrong? Because I am not only difference between expo init and react-native-init are the expo modules and TS Support so may it is something of this. Idk.
