### ISSUE TITLE
[Expo-Notifications] custom sound doesn't work on Android, haven't confirm on IOS yet, but likely failed

### ISSUE THREAD

**Issue by guanhuay** [expo/expo#10349]
### Summary of Issue 
@sjchmiela 
The documentation states that NotificationContentInput can take a boolean or a string, where string could be the name of custom sound.

I followed the recommended steps here [expo bug 8032](https://github.com/expo/expo/issues/8032), but still failed to play custom sound.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.27.8 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.22.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.2 => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.13 
    npmGlobalPackages:
      expo-cli: 3.27.8
    Expo Workflow: bare

### Reproducible Demo

I have upload a minimal reproducible code to github ===> [testApp](https://github.com/guanhuay/testApp)

 
### Steps to Reproduce
1. Clone my repo
2. Run on you Android device
3. Click the button
4. Wait 2 seconds and you will hear the default Android notification sound.

### Expected Behavior vs Actual Behavior
Expected Behavior: custom sound should be played
Actual Behavior: Android default notification sound was played

**Comment by guanhuay** [comment]
any updates on this?

**Comment by sjchmiela** [comment]
Hey, @guanhuay! Sorry it took so long to look into it.

Have you by any chance been testing it on an Android device with system version of Oreo or higher?

It [looks like](https://stackoverflow.com/a/31398504/1123156) on these versions you'll need to not only set the `sound` property on a single notification, but also on the notification channel with which the notification will be presented.

Using your reproducing repository I've been able to make the notifications use custom sound by applying this patch:

```diff
diff --git a/App.js b/App.js
index 3f87cfd..3f2a978 100644
--- a/App.js
+++ b/App.js
@@ -51,6 +51,14 @@ export default function App() {
 }
 
 async function schedulePushNotification() {
+  // Not sure if this is the right place to set notification channel configuration,
+  // global scope or maybe some app setup would be better, but for test purposes
+  // it's ok.
+  await Notifications.setNotificationChannelAsync('test-channel', {
+    name: "Test channel with custom sound",
+    importance: Notifications.AndroidImportance.HIGH,
+    sound: "notification.wav"
+  });
   await Notifications.scheduleNotificationAsync({
     content: {
       title: "You've got mail! 📬",
@@ -58,7 +66,7 @@ async function schedulePushNotification() {
       data: { data: 'goes here' },
       sound: "notification.wav"
     },
-    trigger: { seconds: 2 },
+    trigger: { seconds: 2, channelId: 'test-channel' },
   });
 }
 

```

I'll add this information to `expo-notifications` documentation. 🙂

**Comment by guanhuay** [comment]
@sjchmiela Thanks for your reply, I didn't know that I need a channelId property as well. I would try you fixes later today.

Keep up the good works, expo is the best!

**Comment by LuuCongQuangVu** [comment]
i has a channel in app, but sound running is default

**Comment by GeneCodeFx** [comment]
> i have a channel in app, but sound running is the default

Same here
