### ISSUE TITLE
[expo-av] Load video using loadAsync gets error message "AudioTrack init failed: 0, Config(44100, 12, 44100)"

### ISSUE THREAD

**Issue by norasteria** [expo/expo#10346]
Still continuing this [issue](https://github.com/expo/expo/issues/10320), I've got error message `[Error: d.g.b.d.j0.n$b: AudioTrack init failed: 0, Config(44100, 12, 44100)]` after adding catch function of `loadAsync`

**Comment by byCedric** [comment]
Hi @norasteria, I'll merge your comment into your earlier issue #10320. It makes it a bit more workable for us to manage all issues.
