### ISSUE TITLE
Remove entrypoint from configuration docs for app.json

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#1034]
Hey guys, there's a configuration in the docs here: https://docs.expo.io/versions/latest/guides/configuration.html#entrypoint

but it doesn't seem to work. I don't want my App.js living in the root folder and would rather have it in a custom folder, but I can't seem to do that.

Anyone have updates about this?

**Comment by brentvatne** [comment]
entrypoint is controlled by main in package.json: https://github.com/expo/new-project-template/blob/master/package.json#L2

you'll want to look at the implementation of AppEntry.js, notice that it uses registerRootComponent, you will have to use that manually if you change the main entry point: https://github.com/expo/expo-sdk/blob/master/AppEntry.js

we should remove that entrypoint from docs.

**Comment by lightninglu10** [comment]
The regular main is `./node_modules/react-native-scripts/build/bin/crna-entry.js`

That file has a lot of stuff in it. Is it okay to change completely? I don't entirely know what it's doing.

Is there a better way to do this like set an entrypoint in app.json or package.json? I could write up a PR for that.

**Comment by brentvatne** [comment]
just read my last message and you'll be golden

**Comment by jjant** [comment]
This is still in the docs causing confusion.

**Comment by gregorskii** [comment]
Confusing indeed. The path is hard coded to `../../App.js`.

**Comment by tahv0** [comment]
hard coded?? Really

**Comment by brentvatne** [comment]
yes by convention App.js is the entry point. conventions are "hard coded" that is literally what conventions are. if you don't want to do that then just change the "main" in package.json to whatever you want but make sure to use https://docs.expo.io/versions/v31.0.0/sdk/register-root-component
