### ISSUE TITLE
Problem building same project in other expo account - Question

### ISSUE THREAD

**Issue by GiFarina** [expo/expo#10358]
When I build from expo cli with the command ‘expo build: android -t apk’ I get a perfect result.
 But when I buil from turtle CLI with another expo account the build has the next error. 

`FATAL EXCEPTION: main
Process: com.digicard.clook, PID: 15183
java.lang.RuntimeException: Expo encountered a fatal error: TypeError: undefined is not an object (evaluating 'f.NetInfo.getConnectionInfo'), stack:
<unknown>@928:2438
v@2:1474
<unknown>@914:144
v@2:1474
<unknown>@913:150
v@2:1474
<unknown>@906:188
v@2:1474
<unknown>@840:271
v@2:1474
<unknown>@839:133
v@2:1474
<unknown>@679:547
v@2:1474
<unknown>@6:61
v@2:14
	at host.exp.exponent.experience.f.o(BaseExperienceActivity.java:7)
	at host.exp.exponent.experience.a.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

If someone can tell me where the problem could be, it would be very helpful

successful enviroment:
```
 Expo CLI 3.27.8 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 25.0.0, 26.0.0, 27.0.3, 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Wear OS Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ~37.0.9 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed
```
unsuccessful enviroment:

```
  Expo CLI 3.27.6 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.4 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.8 - /builds/bin/npm
    npmPackages:
      expo: ~37.0.9 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
hi there! can you post this to https://github.com/expo/turtle? thanks
