### ISSUE TITLE
Expo client crashing on debug

### ISSUE THREAD

**Issue by MarsIntel** [expo/expo#10353]

**Comment by MarsIntel** [comment]
Everytime I try to debug on Android device through Expo Client, the app crashes.

**Comment by clynnocs** [comment]
I am having a similar problem after upgrading to Expo SDK 39 and trying to run the Expo Client with Remote Debugging On, on a Pixel 3 emulator.  I am running this on MacOS 10.15.6 and have no issues with debugging on the iPhone emulator. I have updated to the latest React Native Debugger.

**Comment by brentvatne** [comment]
tracking in https://github.com/expo/expo/issues/10284

we have fixes ready for this and will roll them out next week when we do a patch release for sdk 39
