### ISSUE TITLE
Facebook login window (iOS) exits immediately after opening

### ISSUE THREAD

**Issue by sachabest** [expo/expo#1035]
I recently updated to Expo v23 and Facebook login immediately stopped working. I followed the instructions on how to register the correct bundle id, etc. with Facebook from https://docs.expo.io/versions/latest/sdk/facebook.html#registering-your-app-with-facebook to the letter and still am seeing this error:

```
Error with Facebook login
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:80:57 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:347:19 in __invokeCallback
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:137:28 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:265:6 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:136:17 in invokeCallbackAndReturnFlushedQueue
```

I'm using the `web` auth mode.

Re-opened from #671

**Comment by sachabest** [comment]
EDIT: this is pretty sad. I turned on remote debugging and copied the entire exception (native code and all). Look what came up: 

```
NSErrorFailingURLStringKey: "https://googleads.g.doubleclick.net/pagead/viewthroughconversion/995153884/?value=1.00&currency_code=USD&label=ctneCPPWkWAQ3K_D2gM&guid=ON&script=0"
NSLocalizedDescription: "Could not connect to the server."
```

I run [Pi-Hole](https://pi-hole.net/) on our network to block ads at the DNS level, and it turns out that the popup itself will crash if any of the content on the HTML page that comes up cannot resolve (i.e this ad/tracking code that my network is blocking). It might be more user-friendly to throw warnings instead of errors (that crash the popup without any useful debugging info) in these cases, as they can come up from more than just ad-blocking (like network drops, packet loss, etc.)

My app was broken by ads. Thanks Facebook.

**Comment by jesseruder** [comment]
If I'm understanding correctly I don't think there's much Expo can do here to fix this issue. Are you fine closing this and opening an issue on the iOS Facebook SDK?

**Comment by sachabest** [comment]
Absolutely, this is a problem with the iOS WebView if anything. Thanks @jesseruder and everyone else on Expo Slack for your guidance along the way!

**Comment by terribleben** [comment]
This is really interesting. Thanks for digging in @sachabest

**Comment by manoj-nama** [comment]
@sachabest Wow, man that actually helped, I had the same problem with my network, and changing the network worked. At least I can develop forward. 

Thanks,

**Comment by sachabest** [comment]
@manoj-nama glad I could help and @terribleben same thing! You guys built a pretty awesome tool in expo so anything I can do to help I do with pleasure.
