### ISSUE TITLE
Expo v39: splash screen only on iOS

### ISSUE THREAD

**Issue by jaulz** [expo/expo#10352]
### Summary of Issue 
I upgraded recently and the only thing I see when I start the built app on iOS is the splash screen. Even if I use `SplashScreen.hideAsync()` the splash screen does not disappear. Is there any way how I can debug this?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
````
  Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.1.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.33 => 0.12.33 
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: 0.13.13 => 0.13.13 
    npmGlobalPackages:
      expo-cli: 3.27.8
    Expo Workflow: managed
````

### Reproducible Demo

n/a
 
### Steps to Reproduce
n/a

### Expected Behavior vs Actual Behavior
The splash screen should hide.

**Comment by jaulz** [comment]
Update: I just noticed the new status bar in Expo app and it keeps saying "Checking for new update..." but nothing happens. In the standalone app I obviously do not see this message.

**Comment by hardcodet** [comment]
Just seeing this on a version i pushed to Testflight (also 39). Seems to work just fine in Expo Client.

**Comment by brentvatne** [comment]
@jaulz - can you share a reproducible example please?

**Comment by jaulz** [comment]
@brentvatne yep, I will try to create an example. Maybe it's related to the fact that I host the app myself.

**Comment by jaulz** [comment]
@brentvatne it was related to my own hosting. Sorry for the confusion!
