### ISSUE TITLE
AuthSession.useAuthRequest in bare workflow

### ISSUE THREAD

**Issue by nathan-charles** [expo/expo#10362]
### Summary of Issue 
I upgraded my expo project to expo 39 then run expo eject and now AuthSession.useAuthRequest returns null for request. This worked when i ejected my app from expo 38.

![Screen Shot 2020-09-24 at 11 40 00 AM](https://user-images.githubusercontent.com/16949322/94174359-c8f17300-fe5a-11ea-8431-538388c308f3.png)

**Comment by nathan-charles** [comment]
I had to downgrade expo-auth-session from 2.0.0 -> 1.5.1 and now everything works.

**Comment by byCedric** [comment]
Hi @nathan-charles, thanks for writing in. Could you provide a repro, in code, instead of a screenshot? With that, we are able to run it locally and debug the issue. 😄

**Comment by Jonatthu** [comment]
@byCedric this is happening to me too when I use expo 39 and expo-auth-session 1.5.1 or 2.0.0 bare workflow.
