### ISSUE TITLE
39: Notifications.getExpoPushTokenAsync hanging indefinitely in TestFlight

### ISSUE THREAD

**Issue by hardcodet** [expo/expo#10369]
Expo 39, Managed App

This used to work on the previous build: Push notification token retrieval seems to be broken in iOS: My app simply is hanging without an error, and I traced it back to this call:

        try {
            ...
            rootStore.log += ".33";
            const tokenData = await Notifications.getExpoPushTokenAsync({experienceId});
            rootStore.log += ".34";
            ...
        } catch (e) {
            rootStore.log += ".36";
        } 

my log shows progress until the `.33`, and then nothing happens anymore. Any idea what's happening?

Btw, what i tried so far:

- Pushing a new build to TestFlight
- Uninstalling / reinstalling the app on the phone

**Comment by brentvatne** [comment]
what is `experienceId`? why are you passing it in? it defaults to the correct value if you leave it blank, if you are passing in an incorrect value this may have unexpected behavior

**Comment by hardcodet** [comment]
@brentvatne I took a snipped from the docs as below. However, that one also caught my eye and I tried to invoke the method without passing it, but the result was the same:

```
        let experienceId = undefined;
        if (!Constants.manifest) {
            // Absence of the manifest means we're in bare workflow - hardcode the expo experience ID
            experienceId = "@hardcodet/pssn";
        }
```

**Comment by hardcodet** [comment]
To make things worse: This is not hanging on all devices. So the device in question:

- works in the expo client of my phone
- did work in testflight but does no longer, without any other changes to that device rather then deploying the new build.
- as mentioned, uninstalling/reinstalling the app doesn't change anything
- works on another device (for now)

It's probably nothing but: I did an ios build with the `clear-provisioning-profile ` flag as I enabled universal links on a recent build.

**Comment by sjchmiela** [comment]
Hey @hardcodet!

1. I'm not sure if doing an iOS build with a new provisioning profile would affect this or not, sorry. 😕 If the new provisioning profile has push notifications enabled… it should work…

2. Regarding `Promise` taking a long time to fulfil — from my experience and from Internet's experience:
    - it may take a long time if there are problems with Internet connection as per [this SO answer](https://stackoverflow.com/a/34332047/1123156)

        > **iOS Note:** If a cellular or Wi-Fi connection is not available, neither the `application:didRegisterForRemoteNotificationsWithDeviceToken:` method nor the `application:didFailToRegisterForRemoteNotificationsWithError:` method is called. For Wi-Fi connections, this sometimes occurs when the device cannot connect with APNs over port 5223. If this happens, the user can move to another Wi-Fi network that isn’t blocking this port or, on an iPhone or iPad, wait until the cellular data service becomes available. In either case, the device should be able to make the connection, and then one of the delegation methods is called.

   - sometimes APNS is down and the callbacks (and thus `Promise`) are not called, as per [this Developer Forums thread](https://developer.apple.com/forums/thread/52224)
   - sometimes this may be a problem with Internet connection being shared with a computer, according to [this SO answer](https://stackoverflow.com/a/59156989/1123156)
    - [here's a detailed technical description](https://stackoverflow.com/a/8036052/1123156) on how to debug why aren't the callbacks called
    - according to [this SO answer](https://stackoverflow.com/a/10791240/1123156) it may fail if provisioning profile doesn't have push notifications capability enabled
    - [there's](https://stackoverflow.com/a/59864028/1123156) a tip to restart the device when moving between sandbox and production APNS
    - [here's](https://stackoverflow.com/a/19432504/1123156) a recommendation to setup the device with a SIM card if it hasn't been done.

I hope any of the tips may end up helpful to you. 🤗

**Comment by hardcodet** [comment]
Hi there Stanislaw

Thanks for taking the time to put all this together! The device in question at some point started working again after a few releases (no code changes around the push notification tokens though), and I haven't seen the issue again. It can't have been a temporary connectivity issue though, since it reliably failed over a long period of times (we're talking days here).

Since it's working now, I can't really help in diagnosing this, I'm afraid. The only thing that caught my eye was the (slightly mysterious ;) tip about the SIM card since the test device doesn't have one. But that still wouldn't explain why it resumed working at some point as if nothing ever happened.

Feel free to close this issue for now - I can post again if the issue creeps back in with a subsequent release.

Thanks again!

**Comment by sjchmiela** [comment]
Hey, thank you for responding! I'm glad it's sorted out now! I'll let myself close this issue with a pull request adding information on different situations which may impact push token retrieval to a new docs section ["Common gotchas / known issues"](https://docs.expo.io/versions/latest/sdk/notifications/#common-gotchas--known-issues) in a second! 🙂 

PS. Yeah, I agree the SIM card tip is a bit mysterious. 😃

**Comment by devcoderbuzz** [comment]
The below single line is creating a problem.

token = (await Notifications.getExpoPushTokenAsync()).data; with the below. 
I am using expo 44:
Exception is ::  [Error: No experienceId or projectId found. If one or the other can't be inferred from the manifest (eg. in bare workflow), you have to pass one in yourself.]

**Comment by TheRealMikeD** [comment]
@devcoderbuzz and @pors, I am getting the same error.  Searching for an explanation.  Expo 46.

**Comment by pors** [comment]
@TheRealMikeD I'm also on SDK 46. I only have the problem with a development build, not with TestFlight. So I choose to ignore it. Notifications work fine on TF.

**Comment by TheRealMikeD** [comment]
@pors, thanks - that's good to know.  I actually found a usable workaround for this issue in the dev environment, which I posted here: https://github.com/expo/expo/issues/18570#issuecomment-1235788144

**Comment by appsgenie** [comment]
same issue here with SDK 46 when trying out a development build..
