### ISSUE TITLE
Splash screen background color in standalone apps on Android ignored

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#10365]
### Summary of Issue 

<img width="763" alt="Screen Shot 2020-09-24 at 11 03 31 AM" src="https://user-images.githubusercontent.com/90494/94184041-30f28a00-fe58-11ea-8a0d-129e06ce99c3.png">

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

SDK 39, Android

### Steps to Reproduce

Set `backgroundColor`on `splash`, do a standalone app build, verify the expected color is used. *note*: I didn't try this myself, I am trusting the forums report. We need to verify fix

**Comment by viljark** [comment]
Hi, I'm the author of the forum comment, simple repo to reproduce the issue:
https://github.com/viljark/expo-android-bg-color-ignored-example

**Comment by jtklein** [comment]
I have the same problem. Neither the app.json expo.splash.backgroundColor nor the expo.android.splash.backgroundColor is applied when making a standalone build on the expo build servers.

**Comment by brentvatne** [comment]
this issue is better so moving it here https://github.com/expo/expo/issues/10434
