### ISSUE TITLE
Warn users if they call `AppRegistry.registerComponent` directly, rather than `Expo.registerRootComponent`

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#1036]
This would prevent confusing issues like this from occurring in the future: https://github.com/expo/vector-icons/issues/31

**Comment by ide** [comment]
Is this still an issue that is frequent enough to work on? Or does AppEntry take care of this in most cases?

**Comment by aleph-naught2tog** [comment]
I'm biased as I didn't fix a font issue until I found this [post](https://github.com/expo/vector-icons/issues/31), so yes, it's still an issue ;) I am not sure how frequently, though.

**Comment by tsapeta** [comment]
We're not receiving other reports about this and AppEntry takes care of this now, so I'm closing it. If anyone is still experiencing this please see the post linked in the previous comment and if this doesn't help then open a new issue 🙂
