### ISSUE TITLE
ReferenceError: Can't find variable: firebase

### ISSUE THREAD

**Issue by be90728** [expo/expo#10375]
## 🐛 Bug Report

When I upgraded from expo sdk 37 to 39, an error was displayed after downloading the code.
firebase 7.9.0
react native 0.63.2
expo ^39.0.0

Expo CLI 3.27.10 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.14
      react-navigation: ^4.1.1 => 4.4.1
    Expo Workflow: managed

The way I import firebase is as follows:  import * as firebase in "firebase";

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
