### ISSUE TITLE
Login modal with 'expo-google-app-auth'

### ISSUE THREAD

**Issue by MathisGuilhin** [expo/expo#10377]
Hello,

I've been trying to use expo-google-app-auth to login in my react-native app (wired-up to firebase for authentication).

This is actually what it looks like

![120171614_382192862792851_7456640040934049142_n](https://user-images.githubusercontent.com/45480583/94241302-c7848100-ff14-11ea-8d46-e7b9fd097da0.jpg)

using expo documentation : 
```javascript
try {
            const result = await Google.logInAsync({
                androidClientId: "<ID>",
                scopes: ['profile', 'email'],
            });

            if (result.type === 'success') {
                onSignIn(result);
            }
        } catch (e) {
            console.log("error", e);
        }
```

## Is it possible to have a modal instead of a redirection ?
I've seen a [screenshot on Expo forum](https://forums.expo.io/t/google-login-problem-with-standalone-app/2043) where the user has such a result.

![2a1f03ef4342ed34800ffd945609324dd2dab038](https://user-images.githubusercontent.com/45480583/94241943-a2444280-ff15-11ea-810d-e374d4a41cd3.jpeg)

Can anyone give me a clue ?

Thanks in advance, 
Mat

**Comment by brentvatne** [comment]
https://forums.expo.io for questions please
