### ISSUE TITLE
[reopened] Splash Screen ResizeMode Contain Doesn't Work on Android

### ISSUE THREAD

**Issue by superKalo** [expo/expo#1037]
If I understand correctly [the resizeMode docs](https://docs.expo.io/versions/latest/guides/splash-screens.html#splashresizemode), there must be a bug with the `contain` setting on Android.

I'm running on Expo 23.0.0 with React 16.0.0. Here is my "splash" config:

```json
{
  "expo": {
    "sdkVersion": "23.0.0",
    "splash": {
        "resizeMode": "contain",
        "backgroundColor": "#ffffff",
        "image": "./assets/icons/splash1.png",
    },
  }
}
```

I'm using this image for my test:
![splash1](https://user-images.githubusercontent.com/2548061/33475142-fb597de2-d685-11e7-8535-3cbac8e84b95.png)

On iOS (iPhone X, 7, 6S) it works as expected:
<img width="442" alt="screen shot 2017-12-01 at 10 49 51" src="https://user-images.githubusercontent.com/2548061/33475159-1367d2ee-d686-11e7-80a1-e162111360a9.png">

However, on Android - it doesn't "contain" the image. Here's a screenshot from Android device (running on Android 7.1.2):
![image uploaded from ios](https://user-images.githubusercontent.com/2548061/33475738-2ceb3d26-d688-11e7-84c7-6327e18aca54.jpg)

I tested on other Android devices and the result is the same.

The apps run on Expo Client, not as a standalone app yet, if that's something that matters.

**Comment by brentvatne** [comment]
hi! this is resolved now. please update your android client from the play store and in your simulator :) see https://blog.expo.io/expo-for-android-sdk23-minor-update-daf5847ae0a7

**Comment by superKalo** [comment]
Ah, all right! Yes, I just updated the client and it's all good. Thank you!

**Comment by AndyHubert** [comment]
Sadly, this fix does not seem to have properly affected the stand-alone android version. That is to say, the resizeMode flag works fine for me when using the expo client (per the fix), but reverts to the same issue discussed above when I create a stand-alone app for android.

**Comment by cgraio** [comment]
I'm having the same issue. Works well on expo client but in the standalone app it appears in the 'cover' mode.

**Comment by andreaPortfolio** [comment]
I'm having the same issue too!

**Comment by terribleben** [comment]
This does not appear to be fixed. cc @aalices or @esamelson to see if someone can verify.

**Comment by aalices** [comment]
Could anyone having the issue provide some screenshots? What is the size of the image you're using?

**Comment by aalices** [comment]
@aatreya what does your `app.json` look like? What is the size of your image ?

**Comment by ifalldev** [comment]
I'm facing that too. _Happens only on standalone version._

This is my `app.json`:
```
"expo": {
    "sdkVersion": "25.0.0",
    "name": "Awesome Project",
    "icon": "./assets/icon/icon.png",
    "splash": {
      "backgroundColor": "#ed2024",
      "image": "./assets/splash.png"
    },
    "version": "2.2.0",
    "slug": "Awesome-Project",
    "orientation": "portrait",
    "primaryColor": "#ed2024",
    "ios": {
      "bundleIdentifier": "com.awesomeproject",
      "buildNumber": "2.2.0"
    },
    "android": {
      "package": "com.awesomeproject",
      "versionCode": 202000
    },
    "androidStatusBar": {
      "backgroundColor": "#FFFFFF",
      "barStyle": "dark-content"
    }
  }
```

**Comment by aalices** [comment]
@ifalldev to achieve the best results on Android you need to also configure
```
android: {
  splash : {
    // various dpis here
  }
}
```
see here: https://docs.expo.io/versions/v27.0.0/guides/splash-screens#on-android-you-can-set-splash-images

**Comment by aatreya** [comment]
@aalices my app.json contains:
```
    "splash": {
      "image": "./assets/splash.png",
      "backgroundColor": "#01A9ED",
      "resizeMode": "contain"
    },
```
outside the "android" key. I'm not specifying any overrides inside the android key.

Current image size is 2000px wide by 393 tall. We selected this scaling (as opposed to a proportionally larger or smaller image) because it was the only way to get it to appear roughly the right size.

I'm aware that we can configure resolution-specific overrides inside the "android" key in app.json, but the issue here is that the "contain" mode doesn't actually contain the image on the screen. If the image is too low-resolution, it'll simply appear centered and too small, and if it's too high-resolution, it'll run off the edges of the screen. Making the splash screen fit properly is a process of trial and error until you have something that looks roughly right, unlike on iOS where the image is stretched properly to fit the display.

**Comment by aalices** [comment]
This is a kind of Android struggle with images - you have to prepare a couple of images to support all resolutions and there's an official guide for it: https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp 
I think we can't do much about it 😞

**Comment by aatreya** [comment]
In that case, you may want to update the docs to indicate that "contain" and "cover" don't actually do anything on Android.

**Comment by esamelson** [comment]
Hi @aatreya - we will try and update our docs as soon as we can, but you can too! It would be super helpful if you could send us a PR with any changes you think would clarify things. You can do so here: https://github.com/expo/expo-docs

**Comment by terribleben** [comment]
I'm going to close this since it seems the issue on Expo's end is actually fixed. It sounds like there is some confusion about default Android behavior which could be better documented.

For anybody finding this thread after the fact, please read [aatreya's comment](https://github.com/expo/expo/issues/1037#issuecomment-398868279) and make sure your image resolution is correctly configured. Lastly, please feel free to open a PR to our docs if you think there is specific information we could be adding there.

**Comment by ashish-dhiman** [comment]
My team also faced an issue, related to this. When building standalone build for android, the splash screen image became small. To fix it, team did as follows:

{
  "expo": {
    "name": "testing"
    "platforms": ["ios", "android"],
    "splash": {
      "resizeMode": "cover",
      "image": "./assets/splashmdpi.png",
      "backgroundColor": "#000000"
    },
    "ios": {
      "bundleIdentifier": "com.testing"
    },
    "android": {
      "package": "com.testing",
      "splash": {
        "backgroundColor": "#000000",
        "image": "./assets/splashmdpi.png",
        "mdpi": "./assets/splashmdpi.png",
        "hdpi": "./assets/splashhdpi.png",
        "xhdpi": "./assets/splashxhdpi.png",
        "xxhdpi": "./assets/splashxxhdpi.png"
      }
    },
    "description": ""
  }
}

I followed:
[dpi:(expected)] 

hdpi: (252x450), 
xhdpi:(336x600), 
xxhdpi: (504x900), 
xxxhdpi: (672x1200)

for cropping image width and height accordingly.
