### ISSUE TITLE
android.splash key not being used in standalone app builds on SDK 39

### ISSUE THREAD

**Issue by superKalo** [expo/expo#10382]
### Summary of Issue

Android splash screen images failing to load... on the splash screen.

### Environment

```
  Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v14.5.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 22, 28
        Build Tools: 21.1.2, 29.0.1
        System Images: android-22 | ARM EABI v7a, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: 39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.27.8
    Expo Workflow: managed
```

### Steps to Reproduce

This one, in `app.json` works just fine:

```
    "splash": {
      "resizeMode": "contain",
      "backgroundColor": "#FFFFFF",
      "image": "./assets/splash/splash.png"
    },
```

However, when configuring the `splash` attribute for Android specifically, it fails to load the appropriate images both - on Android simulator and on a real device.

It correctly renders only the `backgroundColor` configured.

```
  "android": {
    "splash": {
      "resizeMode": "contain",
      "backgroundColor": "#FFFFFF",
      "mdpi": "./assets/splash/test.png",
      "hdpi": "./assets/splash/test.png",
      "xhdpi": "./assets/splash/test.png",
      "xxhdpi": "./assets/splash/test.png",
      "xxxhdpi": "./assets/splash/test.png"
    },
 ```

### Expected Behavior vs Actual Behavior

Android splash screen images to actually load.

**Comment by brentvatne** [comment]
expo client or in standalone app?

**Comment by superKalo** [comment]
Both. I tried with a couple of images. Here's one.

![Bitcoin svg](https://user-images.githubusercontent.com/2548061/94313383-49ad8d80-ff87-11ea-9a27-f60dd543453a.png)

**Comment by kaushik-prasanna** [comment]
Having the same issue. Was perfectly fine with SDK 38.

**Comment by bbarthec** [comment]
At the moment, the working scenario should be achievable with https://docs.expo.io/versions/latest/config/app/#image-2

**Comment by brentvatne** [comment]
confirmed that using `android.splash.image` is not working as expected - `splash.image` will be used instead.

**Comment by conceptualspace** [comment]
also noticed an issue with `android.splash.backgroundColor` --

since sdk39 it is always white. strangely the expo app seems to use the correct backgroundColor (even when set to production) :thinking:

**Comment by brentvatne** [comment]
@conceptualspace https://github.com/expo/expo/issues/10434

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/10464#issuecomment-703178030

**Comment by superKalo** [comment]
@brentvatne , @esamelson sorry, but this issue still persists. I tested on Android emulator (in the Expo client) and the background color is there, but the image is missing.

However, it works just fine when I use the global `splash` prop. When I switch to defining `mdpi`, `hdpi`, `xhdpi`, `xxhdpi` and `xxxhdpi` under the splash prop of the android key - they don't work.

```
  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v14.5.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: 39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.20.3
```

Yesterday I also noticed it is broken with Expo SDK v38 too, when I create a new standalone Android build.

It works perfectly fine on our ~2 months old PROD build, with the same image.
