### ISSUE TITLE
Expo build failed

### ISSUE THREAD

**Issue by ksielyov** [expo/expo#10395]
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> Task :app:preBuild UP-TO-DATE
> Task :app:extractProguardFiles
> Task :app:preReleaseBuild
> Task :app:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:generateReleaseBuildConfig
> Task :app:javaPreCompileRelease
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
> Task :app:processReleaseGoogleServices
Parsing json file: /app/turtle/workingdir/android/sdk39/android-shell-app/app/google-services.json
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease
> Task :app:processReleaseManifest
/app/turtle/workingdir/android/sdk39/android-shell-app/app/src/main/AndroidManifest.xml:17:9-26:20 Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:17 to replace other declarations but no other declaration present
> Task :app:mergeReleaseResources FAILED
[stderr] FAILURE: 
[stderr] Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:mergeReleaseResources'.
[stderr] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]    > Android resource compilation failed
[stderr]      /app/turtle/workingdir/android/sdk39/android-shell-app/app/src/main/res/drawable-xxxhdpi/shell_launch_background_image.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
[stderr]          
[stderr]      /app/turtle/workingdir/android/sdk39/android-shell-app/app/src/main/res/drawable-xxxhdpi/shell_launch_background_image.png: AAPT: error: file failed to compile.
[stderr]          
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 1m 0s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
9 actionable tasks: 9 executed
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:940:11)
    at async Object.createAndroidShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:386:5)
    at async runShellAppBuilder (/app/turtle/build/builders/android.js:95:9)
    at async Object.buildAndroid [as android] (/app/turtle/build/builders/android.js:43:28)
    at async build (/app/turtle/build/jobManager.js:181:33)
    at async processJob (/app/turtle/build/jobManager.js:118:32)
    at async Object.doJob (/app/turtle/build/jobManager.js:49:5)
    at async main (/app/turtle/build/server.js:66:13)

My package.json 

`{
  "expo": {
    "name": "PriveDrive",
    "slug": "PriveDriveOnExpo",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "android": {
      "package": "com.privedrive",
      "versionCode": 1,
      "config": {
        "googleMaps": { "apiKey": "///" }
      }
    }
  }
}
`

**Comment by brentvatne** [comment]
> failed to read PNG signature: file does not start with PNG signature.

it looks like you're using an invalid png. you haven't provided enough information for us to help (eg: a copy of the png) so i will close this issue

**Comment by ziudeso** [comment]
Similar to

```
[stderr] > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable 1529 
[stderr] > Android resource compilation failed 1530 
[stderr] ERROR:/home/expo/workingdir/build/android/app/build/generated/res/react/release/drawable—mdpi/assets_images_splash2.png: AAP T: error: file failed to compile. 1531 
[stderr] 1532 
[stderr] * Try: 1533 
[stderr] > Run with --stacktrace option to get the stack trace. 1534 
[stderr] > Run with --info or --debug option to get more log output. 1535 
[stderr] > Run with --scan to get full insights. 1536 
[stderr]   1537 
[stderr] 2: Task failed with an exception. 1538 
[stderr]   1539 
[stderr] * What went wrong: 1540 
[stderr] java.lang.StackOverflowError (no error message) 1541 
[stderr] * Try: 1542 
[stderr] > Run with --stacktrace option to get the stack trace. 1543 
[stderr] > Run with --info or --debug option to get more log output. 1544 
[stderr] > Run with --scan to get full insights. 1545 
[stderr]   
```

Solved by re-saving the png file
