### ISSUE TITLE
Expo Application in Android Simulator Crashes in Debug 

### ISSUE THREAD

**Issue by stickybananas** [expo/expo#10399]
MacOs Catalina 10.15.5
Android Studio 4.0.1
Android Emulator 30.0.26
Android SDK 30.0.4
Simulator - Pixel 3a API 30 (Android 10.0+ X86)
Expo version 3.27.10

Created a hello world app with the basic template from tutorial
expo init HelloWorld

Scenario:
The simulator works fine and making change to the App.js is reflected correctly
In simulator after pressing cmd+m and selecting DebugModeJD
[https://imgur.com/Lk3hDYU](url)

Note: The only solution is to uninstall and reinstall expo to clear the settings however this still means I'm not able to debug in the android simulator

Is there a solution for this?

**Comment by AdamJNavarro** [comment]
Hey @stickybananas,

We're aware of this issue and have some PRs in progress to fix it. You can follow along here: https://github.com/expo/expo/issues/10284 I'm going to close this issue so we can focus our efforts and attention there.

Cheers,
Adam
