### ISSUE TITLE
FaceDetector 8.2.1 Not Working (Firebase Issue) in Standalone iOS Build in Managed SDK 38.0

### ISSUE THREAD

**Issue by Aryk** [expo/expo#10392]
Works on Android and Expo App. 

Steps I've taken:

1) Install FaceDetector 8.2.1 (I believe this is close to the newest version).
2) Upgrade expo-cli to 3.27.10
3) Downloaded "GoogleService-Info" and put it in my root directory of the app.
4) Add in app.json under expo.ios.googleServicesFile  ("./GoogleService-Info.plist") AND expo.ios.config.googleSignIn.reservedClientId from my firebase account.
5) expo publish

Then I get this error:

 
<img width="515" alt="Screen Shot 2020-09-26 at 3 19 13 AM" src="https://user-images.githubusercontent.com/525212/94325454-1d096e00-ffa7-11ea-9dc3-9ac47d70d732.png">

**Comment by Aryk** [comment]
Also, there is no documentation at all about the dependency on firebase in the docs:

https://docs.expo.io/versions/latest/sdk/facedetector/

Whatever the solution is to get it working on iOS, maybe we can add something there as well?

**Comment by brentvatne** [comment]
you need to do a new build with `expo build:ios` if you want to add `GoogleService-info` - that is bundled in the binary

**Comment by Aryk** [comment]
Thanks @brentvatne, that worked. Would be great to include something about that in the documentation.
