### ISSUE TITLE
Error using XMLHttpRequest with ImagePicker

### ISSUE THREAD

**Issue by NTakemori** [expo/expo#10394]
### Summary of Issue 
After picking and image and retrieving the URI then trying to retrieve the image blob to send to Firebase,  The onerror runs and I get: "Event { "isTrusted": false }".

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.9.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.3.6 => 4.3.6 
    npmGlobalPackages:
      expo-cli: 3.25.1
 
  Platform: iPhone 7+, iPhone 11 sim, and iPhone 5s
### Reproducible Demo
```
this.setState({
      statusLib: await ImagePicker.requestCameraRollPermissionsAsync(),
    });

    if ( this.state.statusLib !== "granted")
      alert(
        "We can't access your picture without your approval, please change your permissions in your privacy settings"
      );
    //Brings up the camera roll
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      aspect: [4, 3],
    });

    //Image is selected
    if (!result.cancelled) {
      this.setState({uri: result.uri});
   }


var getFileBlob = function (url, cb) {
      var xhr = new XMLHttpRequest();
      xhr.open("GET", url);
      xhr.responseType = "blob";
      xhr.addEventListener("load", function () {
        cb(xhr.response);
      });
      xhr.send();
};

getFileBlob(this.state.uri, (blob) => {
    //insert to DB,
})
```

### Expected Behavior vs Actual Behavior

Expected to return the blob, but it throws and error "Event { "isTrusted": false }".

**Comment by brentvatne** [comment]
see this example: https://github.com/expo/examples/blob/master/with-firebase-storage-upload/App.js

**Comment by emindeniz99** [comment]
> see this example: https://github.com/expo/examples/blob/master/with-firebase-storage-upload/App.js

This doesnt work on expo sdk 39.
I have tested on snack with sdk 38 and sdk 39

**Comment by halilsalihorhan** [comment]
Expo 39 does not support using XMLHttpRequest. Downgrading to expo 38 has temporary solved this problem.

**Comment by haydenbleasel** [comment]
Firebase also supports Base64 images, so if you want to get around this, you can get the image with `expo-file-system` instead of `fetch` / `XMLHTTPRequest`:

```js
import * as FileSystem from 'expo-file-system';
import * as firebase from 'firebase/app';
import * as ImagePicker from 'expo-image-picker';

// Pick the photo
const pickerResult = await ImagePicker.launchImageLibraryAsync({
    allowsEditing: true,
    aspect: [1, 1]
});

// Fetch the photo with it's local URI
const file = await FileSystem.readAsStringAsync(pickerResult.uri, {
    encoding: FileSystem.EncodingType.Base64,
});

// Create a ref in Firebase (I'm using my user's ID)
const ref = firebase.storage().ref().child(`avatars/${user.uid}`);

// Upload Base64 image to Firebase
const snapshot = await ref.putString(file, 'base64');

// Create a download URL
const remoteURL = await snapshot.ref.getDownloadURL();

// Return the URL
return remoteURL;
```
