### ISSUE TITLE
Expo SDK 39: build fails - unable to resolve module esm

### ISSUE THREAD

**Issue by Svarto** [expo/expo#10396]
### Summary of Issue 
Trying to build my project after a fresh update to SDK39, and it fails and throws a red screen:

Failed building JavaScript bundle.
Unable to resolve "module" from "node_modules/esm/esm.js"

I am building it for iOS simulator.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.27.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.14 => 0.13.14 
      react-navigation: ^4.4.1 => 4.4.1 
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: managed

### Reproducible Demo
npm start and start the iOS simulator, these are the packages I have installed / use in my project: 
 },
  "dependencies": {
    "@apollo/client": "^3.2.1",
    "@apollo/link-context": "^2.0.0-beta.3",
    "@hookform/resolvers": "0.1.1",
    "@react-native-community/async-storage": "~1.12.0",
    "@react-native-community/datetimepicker": "3.0.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "1.8.0",
    "@react-native-community/slider": "3.0.3",
    "@react-navigation/drawer": "^5.9.1",
    "@react-navigation/material-bottom-tabs": "^5.2.17",
    "@react-navigation/material-top-tabs": "^5.2.17",
    "@react-navigation/native": "^5.7.4",
    "@react-navigation/stack": "^5.9.1",
    "apollo-cache-persist": "^0.1.1",
    "axios": "^0.20.0",
    "expo": "^39.0.3",
    "expo-blur": "~8.2.0",
    "expo-image-picker": "~9.1.1",
    "expo-notifications": "~0.7.2",
    "expo-secure-store": "~9.2.0",
    "expo-splash-screen": "~0.6.1",
    "expo-updates": "~0.3.4",
    "fuse.js": "^6.4.1",
    "graphql": "^15.3.0",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.20",
    "nhost-js-sdk": "^2.2.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-hook-form": "^6.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
    "react-native-dropdown-picker": "^3.6.8",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-fast-toast": "^1.0.9",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.2",
    "react-native-paper": "^4.2.0",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "~1.13.1",
    "react-native-safe-area-context": "3.1.8",
    "react-native-screens": "~2.11.0",
    "react-native-shared-element": "0.7.0",
    "react-native-svg": "12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swiper": "next",
    "react-native-switch-selector": "^2.0.6",
    "react-native-tab-view": "^2.15.1",
    "react-native-vector-icons": "^7.1.0",
    "react-native-web": "~0.13.14",
    "react-navigation": "^4.4.1",
    "react-navigation-shared-element": "^3.0.0",
    "sentry-expo": "^2.1.2",
    "yup": "^0.29.3"
  },
  "devDependencies": {
    "babel-preset-expo": "^8.3.0",
    "@babel/core": "^7.11.6"
  },

### Expected Behavior vs Actual Behavior

I expected the npm start and build for the iOS to successfully build and start the development version of the app in my simulator. The esm package is nothing that I have chosen explicitly to install and it is only required by "Blob" package (https://www.npmjs.com/package/blob)

**Comment by brentvatne** [comment]
hi there, it seems like this package is not compatible with react-native. i'm not exactly sure why, or which of your packages pulls in blob, but you can use a yarn resolution to use an older version before it started using esm.

this is not an issue with expo but rather an issue in your app dependencies/code :) please post questions like this to https://forums.expo.io in the future, this issue tracker is for bugs in expo itself.
