### ISSUE TITLE
Expo project page does not reflect release-channel data

### ISSUE THREAD

**Issue by slorber** [expo/expo#1039]
[https://expo.io/@community/reactconf2017?release-channel=doesNotExistChannel](https://expo.io/@community/reactconf2017?release-channel=doesNotExistChannel)
 
I'm using a channel that was never used during any publication here.

yet the page renders correctly (with a modified QRCode corresponding to the release channel), and with the "x time ago" corresponding of the last publication of the default channel.

I think this is currently a bit confusing.

If nobody has ever published to this channel, it could be great to warn the user.

If someone has published to this channel, it would be great to display the channel somewhere, and display appropriate, channel specific data (like the "x time ago" being last publication to current release channel)

**Comment by FiberJW** [comment]
Hey @slorber, we are soon doing away with project pages and discoverability on web, as our focus has shifted away from distribution towards making the best app development experience we can. If you have any further related problems, please open another issue. Thanks :)
