### ISSUE TITLE
swiping away expo-document-picker modal on iOS doesn't trigger cancel

### ISSUE THREAD

**Issue by andordavoti** [expo/expo#10405]
### Summary of Issue
Dismissing the expo-document-picker modal on iOS doesn't trigger (await DocumentPicker.getDocumentAsync()).type === 'cancel'.

It also doesn't reopen the dialog after swiping away the modal once.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.10 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.27.8
    Expo Workflow: managed

### Reproducible Demo

[Link to snack](https://snack.expo.io/@andordavoti/documentpicker-ios-issue)
[Video showing the issue](https://drive.google.com/file/d/1raolcElL1eE_iK8sPL7J5bfkHUZYtdz3/view?usp=sharing)
 
### Steps to Reproduce

Run the snack and swipe the modal down. After that, I don't get that it's canceled in the console and I can't open it again.

### Expected Behavior vs Actual Behavior
Expected Behavior: I should get "File selected type: cancel" in the console and be able to open it again.
Actual Behavior: I only get "File selected type: cancel" in the console if I press the cancel button, not if I swipe it down.

**Comment by Badmuts** [comment]
#10325 fixed the issue for me, I believe this fix is available in SDK39. I'm running a bare workflow myself so can't give you any instructions on how to update.

**Comment by andordavoti** [comment]
@Badmuts you're right, the issue is fixed in SDK39
