### ISSUE TITLE
[expo-video-thumbnails] time option not working as expected

### ISSUE THREAD

**Issue by conceptualspace** [expo/expo#10400]
### Summary of Issue

according to the [documentation](https://docs.expo.io/versions/latest/sdk/video-thumbnails/), `VideoThumbnails.getThumbnailAsync` accepts a time parameter (in ms) that defines where the image will be retrieved from the video. but we get the same thumbnail several times when we request several thumbnails in the same second of a video.

perhaps the output is locked to keyframes? if so it would be ideal if we could disable this; see this previous forum post for more information:

https://forums.expo.io/t/videothumbnails-getthumbnailasync-return-only-key-frames-on-android/26292

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

- targeting android

Expo CLI 3.27.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.17.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: managed

### Reproducible Demo

```
const { thumb1 } = await VideoThumbnails.getThumbnailAsync('http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4', {time: 1000});

const { thumb2 } = await VideoThumbnails.getThumbnailAsync('http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4', {time: 1200});
```
 
### Steps to Reproduce

try getting different thumbnails that are a few hundred ms apart from the same source

### Expected Behavior vs Actual Behavior

- expected: the thumbnails returned to be different -- one from 1000ms into the video and the other from 1200ms into the video
- actual behaviour: returned same thumbnail

**Comment by tamagokun** [comment]
looks like it was included in 6.0.0 (https://github.com/expo/expo/blob/master/packages/expo-video-thumbnails/CHANGELOG.md#600--2021-09-28)

**Comment by ryanSoftwareEngineer** [comment]
anyone find a work around or another library to use?

**Comment by jmgarciasanti** [comment]
The problem is still there in Expo SDK 50. In https://github.com/expo/expo/blob/main/packages/expo-video-thumbnails/android/src/main/java/expo/modules/videothumbnails/VideoThumbnailsModule.kt the code is:

return retriever.getFrameAtTime(
  videoOptions.time.toLong() * 1000,
  **MediaMetadataRetriever.OPTION_CLOSEST_SYNC**
)

So it's only gettting key frames

**Comment by expolli** [comment]
Still an issue. Any plans on fixing this?

**Comment by expolli** [comment]
Could we please have this bug opened for the Android part.

**Comment by jmgarciasanti** [comment]
The problem continues in Expo SDK 52. @lukmccall ¿could you please change the OPTION_CLOSEST_SYNC to OPTION_CLOSEST?
