### ISSUE TITLE
Android uploadAsync not working

### ISSUE THREAD

**Issue by ejia-techsursolutions** [expo/expo#10401]
### Summary of Issue 
UploadAsync did not trigger backend Java API successfully in Android, we are getting 400 error, but after some debugging and logging in backend, the backend did not receive the call at all.  my guess is for some reason the File did not generated successfully, and couldn't match the File type in backend and return 400 error. but the same code is working properly in IOS. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Android

### Reproducible Demo
  FileSystem.uploadAsync(url, data.file, {
    headers,
    httpMethod: 'POST',
    uploadType: FileSystem.FileSystemUploadType.MULTIPART,
    fieldName: 'file',
    parameters: {
      data: data,
      id: data.id,
    },
  });

**Comment by barthap** [comment]
Hello,
I'll try to investigate it in my own app soon, but there are a few things you can also check on your own:
- Is your local file URI correct - can you open it in your app before uploading. Does this file have extension?
- You can try to sniff network traffic with tools like Wireshark. Both request and response HTTP headers and body dump would be super helpful here. I believe you can also gather some logs from backend.
- I don't quite understand _"couldn't match the File type in backend"_ - do you mean MIME type? Maybe the problem is that it cannot guess it automatically on Android? You can provide correct mimeType on your own as `options` parameter and also by setting `content-type` header.
- A minimal example on [Snack](https://snack.expo.io) with file that doesn't work would be even more helpful. I would try that on my own backend.

If it still doesn't work, you can do temporary workaround using JS `fetch()` or e.g. `axios` lib, for Android only (using `if Platform.OS === ...) {...}`).

**Comment by ejia-techsursolutions** [comment]
[Expo AsyncUpload Error.txt](https://github.com/expo/expo/files/5305765/Expo.AsyncUpload.Error.txt)

1. my local URI is correct, Image with URI can be displayed on the mobile. 
2. please see wireshark capture of the failing upload. 
3. I am not sure so I am guessing the file type uploaded by AysncUpload may not handled properly? I check MIME type, it is correct. 


 Object {
  "data": FormData {
    "_parts": Array [
      Array [
        "file",
        "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fxxxx-xxx-xxxx-74eded30-024c-4d53-a128-4473c8960bae/ImageManipulator/91b79014-7112-4eff-a0be-1caf700c249c.png",
      ],
      Array [
        "databaseId",
        31,
      ],
      Array [
        "somenumber",
        "sfdfdfdgfdgfdgfdgf",
      ],
    ],
  },
  "headers": Object {
    "Content-Type": "multipart/form-data",
    "tokenHeader": Object {
      "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdG......",
    },
  },
  "method": "POST",
  "params": Object {},
  "responseType": "json",
  "service": 4,
  "suffixURL": "/file/upload",
  "withCredentials": true,
}
INFO

uploadFileAndroid API return [Error: Request failed with status code 400]

**Comment by ejia-techsursolutions** [comment]
Hi barthap, 

Here is my answer:

- my local URI is correct, Image with URI can be displayed on the mobile.
- please see wireshark capture of the failing upload.
- I am not sure so I am guessing the file type uploaded by AysncUpload may not handled properly? I check MIME type, it is correct. Here is my post call 


Object {
"data": FormData {
"_parts": Array [
Array [
"file",
"file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fxxxx-xxx-xxxx-74eded30-024c-4d53-a128-4473c8960bae/ImageManipulator/91b79014-7112-4eff-a0be-1caf700c249c.png",
],
Array [
"databaseId",
31,
],
Array [
"somenumber",
"sfdfdfdgfdgfdgfdgf",
],
],
},
"headers": Object {
"Content-Type": "multipart/form-data",
"tokenHeader": Object {
"Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdG......",
},
},
"method": "POST",
"params": Object {},
"responseType": "json",
"service": 4,
"suffixURL": "/file/upload",
"withCredentials": true,
}
INFO

uploadFileAndroid API return [Error: Request failed with status code 400]
[AsyncUpload Error.pdf](https://github.com/expo/expo/files/5305893/AsyncUpload.Error.pdf)

**Comment by juanmait** [comment]
I'm experimenting something similar with expo **~38.0.8** on Androiid. But I get this error:

```
Error: Location 'http://192.168.0.101:8080/api/foo/bar' isn't readable.
```
The  request never hits the server.

The code is simple.

```typescript
export async function uploadVideo(fileUri: string) {
  const url = `${BASE_URL}/foo/bar`;
  const options: FileSystem.FileSystemUploadOptions = {
      httpMethod: 'POST',
      uploadType: FileSystem.FileSystemUploadType.MULTIPART,
      fieldName: 'file',
  };

  const result = await FileSystem.uploadAsync(url, fileUri, options);
  return result;
}
```

The request never hits the server so I don't get any status code. Here is a stack trace:

```
Stack trace:
  /***/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
  /***/node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
  /***/node_modules/expo-file-system/build/FileSystem.js:114:17 in uploadAsync
  /***/node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  /***/node_modules/regenerator-runtime/runtime.js:293:29 in invoke
  /***/node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  /***/node_modules/regenerator-runtime/runtime.js:154:27 in invoke
  /***/node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
  /***/node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
  /***/node_modules/promise/setimmediate/core.js:200:22 in doResolve
  /***/node_modules/promise/setimmediate/core.js:66:11 in Promise
  /***/node_modules/regenerator-runtime/runtime.js:188:15 in callInvokeWithMethodAndArg
  /***/node_modules/regenerator-runtime/runtime.js:211:38 in enqueue
  /***/node_modules/regenerator-runtime/runtime.js:238:8 in exports.async
  /***/node_modules/expo-file-system/build/FileSystem.js:110:7 in uploadAsync
  /***/node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  /***/node_modules/regenerator-runtime/runtime.js:293:29 in invoke
  /***/node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  /***/node_modules/regenerator-runtime/runtime.js:154:27 in invoke
  /***/node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
  /***/node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
  /***/node_modules/promise/setimmediate/core.js:200:22 in doResolve
  /***/node_modules/promise/setimmediate/core.js:66:11 in Promise
  /***/node_modules/regenerator-runtime/runtime.js:188:15 in callInvokeWithMethodAndArg
  /***/node_modules/regenerator-runtime/runtime.js:211:38 in enqueue
  /***/node_modules/regenerator-runtime/runtime.js:238:8 in exports.async
  http://192.168.0.101:19001/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:164852:51 in uploadVideo$
  /***/node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  /***/node_modules/regenerator-runtime/runtime.js:293:29 in invoke
  /***/node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  /***/node_modules/regenerator-runtime/runtime.js:154:27 in invoke
  /***/node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
  /***/node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
  /***/node_modules/promise/setimmediate/core.js:200:22 in doResolve
  /***/node_modules/promise/setimmediate/core.js:66:11 in Promise
  /***/node_modules/regenerator-runtime/runtime.js:188:15 in callInvokeWithMethodAndArg
  /***/node_modules/regenerator-runtime/runtime.js:211:38 in enqueue
  /***/node_modules/regenerator-runtime/runtime.js:238:8 in exports.async
  http://192.168.0.101:19001/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:164848:41 in uploadVideo
  http://192.168.0.101:19001/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:243060:32 in onUpload
  src/screens/OrderDetail/components/UploadVideo/UploadVideo.tsx:80:6 in UploadVideo
  /***/node_modules/react-native-gesture-handler/touchables/GenericTouchable.js:210:6 in onHandlerStateChange
  /***/node_modules/react-native-gesture-handler/GestureButtons.js:23:21 in BaseButton#constructor
  http://192.168.0.101:19001/__generated__/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:175785:80 in _onGestureHandlerStateChange
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:286:4 in invokeGuardedCallbackImpl
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:497:2 in invokeGuardedCallback
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:521:2 in invokeGuardedCallbackAndCatchFirstError
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:683:41 in executeDispatch
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:707:19 in executeDispatchesInOrder
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:872:28 in executeDispatchesAndRelease
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:853:4 in forEachAccumulated
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:897:20 in runEventsInBatch
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:1069:18 in runExtractedPluginEventsInBatch
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2835:35 in batchedUpdates$argument_0
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20569:13 in batchedUpdates$1
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2731:29 in batchedUpdates
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2834:16 in _receiveRootNodeIDEvent
  /***/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2854:25 in receiveEvent
  /***/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:425:19 in __callFunction
  /***/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:6 in __guard$argument_0
  /***/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:373:10 in __guard
  /***/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:4 in callFunctionReturnFlushedQueue
  [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by barthap** [comment]
Hello @juanmait,

Error `Location isn't readable` was known bug in SDK 38 (see #9075) and was fixed in SDK 39. The problem was that two first arguments were swapped (`url` and `fileUri`).

**Comment by juanmait** [comment]
@barthap I tried swapping the params before but didn't work either. I get this error:
```
java.lang.Double cannot be cast to java.lang.Integer
```
I can't move to version 39 until the regressions issues are fixed.

Thanks anyway. Will try with axios

**Comment by barthap** [comment]
The issue with Double to Int conversion was also fixed together with swapped arguments bug, so it doesn't happen in SDK 39. See #9076

**Comment by juanmait** [comment]
@barthap cool! Thanks so much for your info! It helps a lot.

**Comment by thebantz** [comment]
Hi, uploadAsync is nowhere to be found as a method. My stack trace informs me that it is not a function... 
![image](https://user-images.githubusercontent.com/35896079/96026388-47628480-0e0b-11eb-8570-835e8cbeacc0.png)
![image](https://user-images.githubusercontent.com/35896079/96026931-01f28700-0e0c-11eb-9e8a-1ceefc0c28ab.png)

**Comment by brentvatne** [comment]
@thebantz - you are probably using an older sdk version. uploadAsync was added in sdk 38

**Comment by eightyfive** [comment]
It's likely failing at the proxy level, before it can even reach your backend server.

Double-check your [`client_max_body_size`](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) nginx configuration for example.

It's `1M` by default, way too low nowadays.
