### ISSUE TITLE
I am not getting notifications after getting build.

### ISSUE THREAD

**Issue by mertct11** [expo/expo#10408]
my imports 
import * as Permissions from "expo-permissions"; // @^9.0.1
import {Notifications} from 'expo';   // @~38.0.8
import Constants from 'expo-constants'  // @^9.1.1

I use these packages with these versions.

 I run this function after the state of log in componentdidmount function in app.js is true. function this link is created as a reference expo official overview
```

registerForPushNotifications = async () =>
{
  const {status} = await Permissions.getAsync(Permissions.NOTIFICATIONS);
  let finalStatus = status;

  if(status !=='granted')
  {
    const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
    finalStatus= status ; 
  }

  if (finalStatus!=='granted') {return;}
 let token = await Notifications.getExpoPushTokenAsync();
    console.log("tokentokentokentokentokentoken");
    console.log(token);
    
    Fire.shared.firestore
                .collection("users")
                .doc(firebase.auth().currentUser.uid)
                .update({
                    tokenForPush: token
                }) 

    
  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }
 
}

```
 Then I open the expo application from my android phone that I use. I connect to the project and the value of tokenForPush variable in the user collection in the firestore is changed. no problem so far. Then I created the send notification function and this token is successfully sent to the notification expo application when it is open.

However, the part I do not understand is that when I run the expo build: android command, I can get builds smoothly and download from the relevant link.

I download and send the apk to the phone with the same android operating system via whatsapp and install it.

The application opens without any problems, but when I log in after it is opened, I cannot assign a value to tokenForPush on the firestore side. So the value does not change at the same time.

This expo push notification package is only valid for the expo application, right? I have API I can fetch it, but can I only get notifications from the expo mobile app? What is the point if I cannot get notifications after getting a build or after converting to a real app (after the apk file)? I am very confused. Can you help me?

OR how to set up push notification on my expo project without expo ejecting?

**Comment by anhquan291** [comment]
I'm facing the same problem... still waiting

**Comment by AdamJNavarro** [comment]
Hey @mertct11 and @anhquan291,

Can you guys let me know if you've done the necessary `app.json` configurations to have push notifications work on Android projects?

1. Setting the `useNextNotificationsApi` https://docs.expo.io/versions/v39.0.0/sdk/notifications/#android
2. Setting up FCM https://docs.expo.io/push-notifications/using-fcm/

Cheers,
Adam

**Comment by anhquan291** [comment]
@AdamJNavarro  Hi, thanks for answering, I also have an issue getting push token on IOS. 
Please check this post when you can, Thanks a lot 
https://github.com/expo/expo/issues/10374

**Comment by cruzach** [comment]
It's not clear from the issue report what the problem is here. It seems like you're having trouble getting a push token? 

> I cannot assign a value to tokenForPush on the firestore side

this doesn't really explain the issue to us or how it relates to `expo-notifications`, and we can't reproduce it on our end. @mertct11 if can you follow the issue template and provide a minimal reproducible demo, I'm happy to help investigate this further.

**Comment by ceafive** [comment]
@cruzach I am getting an error, when I use the Expo app and run my app locally I receive push notifications and everything works fine. But when I run an android build and install on my phone I don't receive notifications and I realise that the expo notification token i receive when I run a build is different from the one I receive when I run my app locally.
