### ISSUE TITLE
uri remote not working with query string parameter on iOS 

### ISSUE THREAD

**Issue by faustoct** [expo/expo#10404]
### Summary of Issue 
This code not working when having parameter but works without it ?token=SOME_TOKEN
````
<Video
  ref={videoRef}
  source={{uri: 'https://www.something.com/video.mp4?token=SOME_TOKEN'}}
  rate={1.0}
  volume={1.0}
  isMuted={false}
  resizeMode="cover"
  shouldPlay
  isLooping
  style={{ width: '100%', height: '100%' }}
/>
````
### Environment - output of `expo diagnostics` & the platform(s) you're targeting
````
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.9 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.4.1
````
 
### Steps to Reproduce
Any uri with with params

### Expected Behavior vs Actual Behavior
Play the video

**Comment by faustoct** [comment]
Anyone have any idea?

**Comment by bfitec** [comment]
Did you figure this out @faustoct ? We're having an issue with this on Android too.

**Comment by bfitec** [comment]
Figure this out on android had to add
`overrideFileExtensionAndroid: 'm3u8'`
expo video was failing to determine the correct video type due to the token in the query string. @faustoct
