### ISSUE TITLE
"No dimension set for key window" error in Expo App 2.1.2

### ISSUE THREAD

**Issue by Ivanrs297** [expo/expo#1041]
After the update of Expo App from 2.0.0 to 2.1.2 the following error appears on screen:

![error](https://user-images.githubusercontent.com/26337972/33503127-23192c66-d6a8-11e7-8f50-122a304cf179.png)

This appears when trying to run the app, but it doesn't starts.
When I was using Expo App 2.0.0, I was using the sdkVersion 15, but now with the Expo App 2.1.2 it says that this version of SDK is not supported anymore, so I updated the sdkVersion to 19, but the error appears.

**Extra information:**
- React Native: 0.42.0

- expo: 15.1.2

- Platform: Android

- OS: Ubuntu 16.04 LTS

**Comment by quinlanj** [comment]
hey @Ivanrs297 , try upgrading your dependencies in `package.json` and seeing if that works. The article here https://blog.expo.io/expo-sdk-v19-0-0-is-now-available-821a62b58d3d in the section `Upgrading your app` lists the dependencies to change. Closing this issue for now!
