### ISSUE TITLE
[ViewPager] Paging broken and some page no rendered with Drawer navigation

### ISSUE THREAD

**Issue by tree1891** [expo/expo#10412]
If go forward and back by drawer navigation, viewpager's paging is broken and some pages are not rendered.

react-native-viewpager: 3.3.0
react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2

**Comment by AdamJNavarro** [comment]
Hey @tree1891,

Given that `ViewPager` is maintained by `react-native-community` it would be best to open up an issue here https://github.com/react-native-community/react-native-viewpager. Since this is not Expo-specific I'm going to close this issue.

Cheers,
Adam
