### ISSUE TITLE
KeyboardAvoidingView issue on android expo sdk 39

### ISSUE THREAD

**Issue by The098** [expo/expo#10413]
## 🐛 Bug Report

Keyboard changes view on input touch. It shows white blank when it’s moving to top. If you set backgroundColor: “red” for the root view you will see this white blank on keyboard show right. Since sdk 37 i’m facing this issue. Please can somebody help me

### Environment 
Expo-cli 3.27.10
Expo sdk 39
Manage workflow
Platform Android

### Reproducible Demo

import React from 'react';
import { StatusBar } from "expo-status-bar";
import {
  View,
  KeyboardAvoidingView,
  TextInput,
  StyleSheet,
  Text,
  Platform,
  TouchableWithoutFeedback,
  Button,
  Keyboard,
} from 'react-native';

export default function KeyboardAvoidingComponent() {
  return (
      <KeyboardAvoidingView
          behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
          style={styles.container}>
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <View style={styles.inner}>
            <Text style={styles.header}>Header</Text>
            <TextInput placeholder="Username" style={styles.textInput} />
            <View style={styles.btnContainer}>
              <Button title="Submit" onPress={() => null} />
            </View>
            <View style={{flex:1}}>
              <Text>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium aliquid aperiam, architecto beatae
                blanditiis consectetur consequatur cupiditate
                dolores ex excepturi expedita necessitatibus nemo neque obcaecati omnis perspiciatis quibusdam suscipit 
              </Text>
            </View>
          </View>
        </TouchableWithoutFeedback>
        <StatusBar style={"auto"}/>
      </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "red"
  },
  inner: {
    padding: 24,
    flex: 1,
    justifyContent: 'space-around',
  },
  header: {
    fontSize: 36,
    marginBottom: 48,
  },
  textInput: {
    height: 40,
    borderColor: '#000000',
    borderBottomWidth: 1,
    marginBottom: 36,
  },
  btnContainer: {
    backgroundColor: 'white',
    marginTop: 12,
  },
});

### Expected Behavior vs Actual Behavior
Expected Behavior: Keyboard must not change view nor show white blank when moving to top like in expo sdk 36
Actual Behavior: Keyboard changes view and shows white blank when moving to top

**Comment by AdamJNavarro** [comment]
Hey @The098,

`KeyboardAvoidingView` is a React Native component so the best course of action would be to head over to the RN [repo](https://github.com/facebook/react-native) and check the issues to see if it's been reported or addressed. If I remember correctly this had been brought up and there was a PRsin the work to fix it in the future.

Cheers,
Adam

**Comment by The098** [comment]
Thanks for the reply i hope it will be fixed in the sdk 40. I will return
to the sdk 36 unfortunately

Le lun. 28 sept. 2020 à 14:15, Adam Navarro <notifications@github.com> a
écrit :
