### ISSUE TITLE
Expo SDK v39 - Updates.reloadAsync() makes the app crash if the phone is offline

### ISSUE THREAD

**Issue by superKalo** [expo/expo#10419]
### Summary of Issue

If wi-fi and mobile data are disabled (there is no internet connection), calling `Updates.reloadAsync()` makes the app crash. I observed this on an Android standalone app.

### Environment

```
  Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v14.5.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 22, 28
        Build Tools: 21.1.2, 29.0.1
        System Images: android-22 | ARM EABI v7a, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: 39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.27.8
    Expo Workflow: managed
```

`expo-updates v0.3.4`

### Steps to Reproduce

Simply switch-off wi-fi and mobile data on an Android phone (to simulate no internet connection) and call `Updates.reloadAsync()`.

### Expected Behavior vs Actual Behavior

App to reload.

**Comment by byCedric** [comment]
Hi @superKalo, thanks for the report. Unfortunately, I haven't been able to reproduce this error using a managed expo project and `expo-updates@0.3.4`. I tried turning off mobile data and wifi, and airplane mode. I've tested this on OnePlus 6 (Android 10).

Could you share a bit more on what Android phone this is happening for you? It would also be very useful if you can provide ADB logcat logs when this happens. You should be able to connect your phone to your computer, run something like `$ adb logcat &> expo-updates-crash.log`, and then trigger the error.

**Comment by brentvatne** [comment]
@superKalo - if you can help is repro this (a [mcve](https://stackoverflow.com/help/mcve) and a specific set of steps would be very helpful) we can try to get a fix in soon

**Comment by superKalo** [comment]
I updated to: `"expo-updates": "0.3.5" and:

```
  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v14.5.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: 39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.20.3
```

And now it works just fine 🤷 

Tested on: OnePlus 7 Pro, Oxygen OS 10.3.4 (Android 10).

So whatever was happening, I can't reproduce anymore.
