### ISSUE TITLE
Push Notifications not working with Notification Response Handler

### ISSUE THREAD

**Issue by dipamsen** [expo/expo#10416]
## 🐛 Bug Report
- Package: `expo-notifications`

### Summary of Issue 
Event Listener `addNotificationResponseReceivedListener` doesn't work with **Push Notifications**. It only works for Local Notifications.

### Reproducible Demo
Most of the code is from Native Component List App
[Snack Link](https://snack.expo.io/@dipamsen/notification-bug)
 
### Steps to Reproduce
https://snack.expo.io/@dipamsen/notification-bug

### Expected Behavior vs Actual Behavior
The alert message should come when we click on any notification. But it only comes for Local Notifications.

**Comment by AdamJNavarro** [comment]
Hey @dipamsen,

Based on your code comment above the handling of the response, are you only experiencing this on Android? Also, could you please put this into a reproducible and runnable example that we can test on our end?

Cheers,
Adam

**Comment by dipamsen** [comment]
Thanks for replying!

Yes, I have only tested on Android Phone.
I have put the code to Snack: https://snack.expo.io/@dipamsen/notification-bug

**Comment by cruzach** [comment]
looks like this is a duplicate of https://github.com/expo/expo/issues/10357, I'm looking into this now

**Comment by cruzach** [comment]
@dipamsen it's weird, I was able to reproduce this pretty consistently but am now having trouble, running the same code. Can you try clearing out your `node_modules` and trying again?

**Comment by dipamsen** [comment]
@cruzach yeah, I tried it out today, and it seemed to work in the client. I don't know why it wasn't working, but it is working fine today. I thought that it might have been patched or something, idk. I am closing the issue, please open it if required.

**Comment by maurohmartinez** [comment]
I am having an issue with SDK 39, on Android stand alone. When the app is open by a push notification, the addNotificationResponseReceivedListener is not triggered. The issue was present in SDK 38 but only fixed for iOS with SDK 39 (at least across my apps). I don't find an open issue for it, do you guys know anything about it?
Thanks!
