### ISSUE TITLE
[docs] Many packages reference "expo install" for bare workflow instead of "npm install"

### ISSUE THREAD

**Issue by tschanz-pcv** [expo/expo#10424]
Many packages (e.g. https://github.com/expo/expo/tree/master/packages/expo-face-detector or https://github.com/expo/expo/tree/master/packages/expo-random (and possibly many more)) reference the following install procedure for the bare workflow:

```
### Add the package to your npm dependencies

expo install expo-random
```

Which I believe is incorrect and should be `npm install ...` instead of `expo install ...` as the header clearly states to add it to the npm deps, the bare [workflow guide](https://docs.expo.io/bare/hello-world/#install-an-expo-sdk-package) says to `npm install` it, `expo install` doesn't work without having the `expo` package installed as well (which is not required for the unimodules I think) and some of the packages seem to have it correct, e.g. https://github.com/expo/expo/tree/master/packages/expo-image

**Comment by brentvatne** [comment]
@byCedric - we should update `expo install` to work fine in bare apps without the `expo` package installed, to just have it fall through and run `npm install` or `yarn add`
