### ISSUE TITLE
softwarekeyboardlayoutmode not work in Expo SDK 39

### ISSUE THREAD

**Issue by choby** [expo/expo#10420]
I set the softwarekeyboardlayoutmode property in the configuration file,and value was "pan", But react navigation/bottom-tabs will still be jacked up by the keyboard

os: samsung android 11
sdk:39.0.3

**Comment by brentvatne** [comment]
it works fine: https://github.com/brentvatne/expo-issue-10420 - tested this on sdk38 then updated to sdk39.

please follow the issue template correctly in the future.
