### ISSUE TITLE
[expo-av] Video opacity is always black

### ISSUE THREAD

**Issue by conceptualspace** [expo/expo#10427]
### Summary of Issue 

On Android, when setting the opacity of a Video component, the background is always black instead of seeing the component behind.

I haven't dug into Expo enough to say if this is the same thing as this upstream issue: https://github.com/react-native-community/react-native-video/issues/1983, which may be resolved by this PR: https://github.com/react-native-community/react-native-video/pull/2168

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.27.10 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.18.4 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.6 - /usr/bin/npm
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: managed

Targeting: Android

### Reproducible Demo

```
import { Video } from 'expo-av';
...
<View style={{backgroundColor:'red'}}>
<Video
        source={'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4'}
        style={{opacity:0.5}} 
/>
</View>
```

 
### Steps to Reproduce

1. Add Video component to a project
2. Set an opacity less than 1 on the Video component. Notice that Android will display a black background behind the transparent video, while iOS will display the proper background

### Expected Behavior vs Actual Behavior

In the reproducable code above, we would expect to see the red layer behind the video component when the video opacity is set to 0.5.

The actual behavior is we see a black layer behind the video component

**Comment by brentvatne** [comment]
> I haven't dug into Expo enough to say if this is the same thing as this upstream issue: react-native-video/react-native-video#1983, which may be resolved by this PR: react-native-video/react-native-video#2168

fwiw react-native-video isn't actually upstream from expo-av, expo-av is a completely independent implementation :)

> view.setOpaque(false);

i wonder if this will have any performance implications if it's applied generally and not only when the video has some opacity set. presumably there is a good reason why it's not always opaque (more research would be needed), so it seems a lot more safe to only set opaque when a non-1 opacity is set.

**Comment by conceptualspace** [comment]
valid points. and thanks for the background info, that is good to know :)
