### ISSUE TITLE
expo-random has no unimodules dependency but uses it

### ISSUE THREAD

**Issue by tschanz-pcv** [expo/expo#10423]
### Summary of Issue 

The `expo-random` package got the notice regarding unimodules for bare projects:
```
For bare React Native projects, you must ensure that you have [installed and configured the `react-native-unimodules` package](https://github.com/unimodules/react-native-unimodules) before continuing.
```
removed in the following Commit: https://github.com/expo/expo/commit/3571d4149c977e8d7997dbe00fe4ea58d731b3db#diff-edf854e2305e5d72534d219959df525a

This commit also removed most unimodule dependencies except for one location: https://github.com/expo/expo/blob/1168f4cb255c81f933008943040db4b42c3908fc/packages/expo-random/src/Random.ts#L1

The package now seems in the state that it doesn't really need the unimodules but still uses it without documenting it.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

/

### Reproducible Demo
 
/

### Steps to Reproduce

/

### Expected Behavior vs Actual Behavior

Preferably the last remaining unimodules dependency could be removed so this package is usable without it. Either by simply replacing it with a normal Error throw or bundling the unimodule parts during build.

**Comment by byCedric** [comment]
Hi @tschanz-pcv, thanks for mentioning this! @brentvatne can we implement something like "if unimodules/core is installed, use UnavailabilityError, else use normal Error" to make it work without unimodules?

**Comment by brentvatne** [comment]
i could add this as a peer dependency, would that be useful for you @tschanz-pcv?

**Comment by tschanz-pcv** [comment]
@brentvatne @byCedric Thanks for the super fast responses, due to timezone differences I only got the time to respond now.

I don't know expo's setup but wouldn't you also have to add the following back in the `package.json`: https://github.com/expo/expo/commit/3571d4149c977e8d7997dbe00fe4ea58d731b3db#diff-eb6ffeffd2a8a88fa7c7542e97056147L41 and there are also other changes relating to unimodules like: https://github.com/expo/expo/commit/3571d4149c977e8d7997dbe00fe4ea58d731b3db#diff-09d249fffc914916a5c45431cf14e122L1 will it work without these?

I can understand your reasoning of not going out of your ways to maintain strictly expo-agnostic libraries but I feel like requiring the entire unimodules setup just to get a "fancier" error throw is a bit much.

**Comment by brentvatne** [comment]
> I can understand your reasoning of not going out of your ways to maintain strictly expo-agnostic libraries but I feel like requiring the entire unimodules setup just to get a "fancier" error throw is a bit much.

yes that's fair, but we also don't want to break consistency across the expo sdk in terms of the errors provided and such things. to someone who is already using another expo-* package there are no additional dependencies added, and i would find it rather strange if someone only wanted to use expo-random and no other expo packages, so it's not a practical problem in my opinion.
