### ISSUE TITLE
Splash screen on Android visible when keyboard resizes app or orientation changes

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#10435]
### Summary of Issue 

Notice the green that appears under the tab bar when the keyboard is resizing the view:

![color](https://user-images.githubusercontent.com/90494/94499291-1fd7af00-01b1-11eb-9cf3-0f3646d79c3e.gif)

### Steps to Reproduce

- Set a non-white background color and apply splash screen configuration
- Ensure that the project has `android:windowSoftInputMode="adjustResize"` - this is the default for managed and bare projects
- Add a `TextInput` component somewhere in the app
- Build it and focus the `TextInput`, notice the behavior from the above video

I can currently only reproduce this in the bare workflow. We should verify that this does not occur in the managed workflow after https://github.com/expo/expo/issues/10434 is fixed.

### Expected Behavior vs Actual Behavior

Splash screen should be hidden and not visible behind the app root view

**Comment by beDenz** [comment]
Same thing. View no animate when keyboard opening.

**Comment by brentvatne** [comment]
@beDenz - i do not understand your statement

**Comment by bbarthec** [comment]
The root cause for this issue is exactly the same as for https://github.com/expo/expo/issues/10436
Moreover, this splash color will be visible during the app rotation as well (vertical ⏩ horizontal).

**Comment by andresquesadacascante** [comment]
The only thing I found that "works" is eject the project and then modify the root view background color of their respective platform with the Info that I got in the last month

**Comment by andresquesadacascante** [comment]
I'm having the same problem. As I read on some sites, it is best to run the project and modify it directly in its respective platform but for me it is not a solution

**Comment by 0b3r** [comment]
I figured this out.  You need to add a different style definition rather than putting the splash screen color in the root app theme. 

Below is an example `styles.xml`

Before: 

```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:textColor">#000000</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowLightStatusBar">true</item>
        <item name="android:windowBackground">@drawable/splashscreen</item> 
    </style>
</resources>
```

After
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:textColor">#000000</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowLightStatusBar">true</item>
    </style>
    <style name="Theme.App.SplashScreen" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@drawable/splashscreen</item> 
    </style>
</resources>
```

**Comment by vacom** [comment]
Hey guys any updates on this issue? Currently using Expo: 40.0.1 managed flow. It works fine on the expo client but when building a standalone app gives the same issue.

**Comment by aarku** [comment]
Still seeing it on expo 41.0.1 managed workflow.

**Comment by SBareno31** [comment]
Hello Any update for the problem?.

**Comment by ziniuguo** [comment]
jesus cant believe this bug is still not fixed till now

**Comment by bratelefant** [comment]
still there on sdk 42

**Comment by brentvatne** [comment]
if you're encountering this issue then please post a reproducible example.

here's a project you can clone and run: https://github.com/brentvatne/splashbg

notice that when the keyboard opens the red splash screen background color is not visible behind it. you can run this in either Expo Go with `expo start` or with `yarn android` to build the bare project.


https://user-images.githubusercontent.com/90494/126573799-4d13e4d3-a49d-41fe-b721-cb593ded6bb4.mov

the splash screen has no image and just a red background. when i open the keyboard or close it, i don't see the background anymore.

**Comment by gbarany** [comment]
Making the below change in `styles.xml` solved the issue for me:

Before:
`<style name="Theme.App.SplashScreen" parent="Theme.AppCompat.Light.NoActionBar">`

After:
`<style name="Theme.App.SplashScreen" parent="AppTheme">`

**Comment by brentvatne** [comment]
@gbarany - that's a good solution - we do the same thing by default now: https://github.com/expo/expo-cli/pull/3558/files

i believe this resolves the issue so i'm going to close this

**Comment by appasaheb4** [comment]
facing till same issue

**Comment by vlimag** [comment]
hey did you guys find a solution for this?
setting up on AndroidManifest `android:windowSoftInputMode="adjustPan"` fixes the splashScreen showing up issue, but then the screen doest fit properly sometimes on keyboard open.

So trying to keep `android:windowSoftInputMode="adjustResize"` there
