### ISSUE TITLE
Splash screen background color on native launch screen not applied in managed standalone apps

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#10434]
### Summary of Issue 

When a standalone app is built with `splash.backgroundColor` or `android.splash.backgroundColor` it should be applied to the native static splash screen that is visible from the moment the app is launched. Instead, it is only visible after switching to the custom splash screen view.

![splash](https://user-images.githubusercontent.com/90494/94498860-1568e580-01b0-11eb-9784-31d1a6df7c5c.gif)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

SDK 39

### Reproducible Demo

```
{
  "expo": {
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#7BDCB5"
    },
    "android": {
      "package": "com.example.app",
      "splash": {
        "image": "./assets/images/splash.png",
        "resizeMode": "contain",
        "backgroundColor": "#7BDCB5"
      }
    }
  }
}
```

**Comment by andihoerudin24** [comment]
this is my app.js file.  `import { StatusBar } from 'expo-status-bar';
import React,{useState} from 'react';
import { StyleSheet, Text, View } from 'react-native';
import * as Font from 'expo-font'
import {AppLoading} from 'expo'
import {enableScreens} from 'react-native-screens'
import login from './screens/login';


enableScreens();
const fetchFonts = () =>{
    return Font.loadAsync({
       "open-sans":require("./assets/fonts/OpenSans-Regular.ttf"),
       "open-sans-bold":require("./assets/fonts/OpenSans-Bold.ttf")
    })
}


export default function App() {
  const [fontLoaded, setFontLoaded] = useState(false);
  if (!fontLoaded) {
    return (
      <AppLoading
        startAsync={fetchFonts}
        onFinish={() => setFontLoaded(true)}
        onError={(err) => {
          console.log(err);
        }}
      />
    );
  }

  return (
    <View style={styles.container}>
      <Text style={styles.text}>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
   
  },
});
` and it is running on expo 38.0.8. after i used expo 39 i had this problem  `
[Unhandled promise rejection: Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android).]`

**Comment by Aryk** [comment]
@brentvatne  - I am also experiencing white splash screen on my iOS standalone as well when I do `Updates.reloadAsync();`

However, it shows the color, when opening the app or when I foreground it.

Are you sure it's only on Android?

**Comment by brentvatne** [comment]
@Aryk - if you are experiencing something similar to this on iOS when you use `Updates.reloadAsync()` please create a new issue and provide a reproducible example

**Comment by Aryk** [comment]
> @Aryk - if you are experiencing something similar to this on iOS when you use `Updates.reloadAsync()` please create a new issue and provide a reproducible example

Is there any expo bare-bone repo I can clone. Expo snack does not expose the App.json file, so will need to create a code base I think...

**Comment by brentvatne** [comment]
`expo init` will give you a variety of options

**Comment by conceptualspace** [comment]
maybe a couple of issues to tease apart here:

1. i recall seeing something documented that there is always a brief white flash on android if not using the native resizeMode?

2. that said, i have noticed that since sdk39 the background is always white even using native resizeMode (this is what brought me to this issue). since the native resize mode requires a bunch of images for different sizes, if a supplied image doesnt match exactly the screen the background color was visible, at least in sdk38
