### ISSUE TITLE
Cannot find symbol SplashScreen

### ISSUE THREAD

**Issue by luk3skyw4lker** [expo/expo#10431]
I've just updated from expo sdk 38 to 39 and I can't build my app because of a error on app:compileDebugJavaWithJavac:

`
> Task :app:compileDebugJavaWithJavac FAILED

/home/lucas_lemos/Bristom/bristom-pro/android/app/src/main/java/com/bristompro/MainActivity.java:10: error: cannot find symbol
import expo.modules.splashscreen.SplashScreen;
                                ^
  symbol:   class SplashScreen
  location: package expo.modules.splashscreen
/home/lucas_lemos/Bristom/bristom-pro/android/app/src/main/java/com/bristompro/MainActivity.java:19: error: cannot find symbol
    SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class, false);
    ^
  symbol:   variable SplashScreen
  location: class MainActivity
Note: /home/lucas_lemos/Bristom/bristom-pro/android/app/src/debug/java/com/bristompro/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use unchecked or unsafe operations.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

I've tried to reproduce the error with a new bare workflow Expo project but the build was successful and I have no clue on what to do with this. Already tried removing node_modules and reinstalling everything, pinning expo-splash-screen version to 0.6.1, 0.6.0 and 0.6.2.

Help!

**Comment by brentvatne** [comment]
hi there, check out this diff: https://github.com/expo/expo/pull/10432/files

**Comment by luk3skyw4lker** [comment]
Thanks, I was about to comment exactly this. I didn't noticed until I checked the files.

**Comment by jeloagnasin** [comment]
I recently ejected my app and the newly created android folder still imported from `import expo.modules.splashscreen.SplashScreen;`
