### ISSUE TITLE
[docs] [expo-splash-screen] Missing versions between npm and changelog file

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#10437]
If you see the [changelog](https://github.com/expo/expo/blob/master/packages/expo-splash-screen/CHANGELOG.md), the latest version is **0.7.1** 

But, when you install via npm the latest version is **0.6.2** (https://www.npmjs.com/package/expo-splash-screen)

And the versions **0.6.1** and **0.6.2** doesn't exist in the changelog file.

So, my question is, what is the current/latest version of `expo-splash-screen` and what are the changes of **0.6.1** and **0.6.2**?

Thanks a lot Expo team!

**Comment by RodolfoGS** [comment]
Also, if you install the version `0.6.2` you have changes that exists in the `0.7.1` like this https://github.com/expo/expo/pull/10192 PR

I think that something was wrong published

**Comment by RodolfoGS** [comment]
Thanks @bbarthec, and to clarify, the latest current version is 0.6.2 right?

**Comment by bbarthec** [comment]
@RodolfoGS, correct 👍
