### ISSUE TITLE
 error: incompatible types: Class<ReactRootView> cannot be converted to boolean     SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class)

### ISSUE THREAD

**Issue by akshaykatale99** [expo/expo#10447]
error: incompatible types: Class<ReactRootView> cannot be converted to boolean
    SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class, true)

![image](https://user-images.githubusercontent.com/12472207/94568019-a790ec80-0289-11eb-8da4-b71315a18f5a.png)

**Comment by byCedric** [comment]
Hi @akshaykatale99, thanks for the report. We are aware of some issues related to the splash screen auto-configuration and will deploy a fix asap. In the meantime, you can manually fix the configuration issue by following this https://github.com/expo/expo-cli/issues/2586

Hope it helps!

**Comment by akshaykatale99** [comment]
i am not able to get the manual config.
