### ISSUE TITLE
[expo-local-authentication] Failed to unlock using device pin code in MIUI 12

### ISSUE THREAD

**Issue by LuHugo** [expo/expo#10451]
### Summary of Issue 
Use the fingerprint to unlock, and the fingerprint unlock failed a few times to automatically jump to the pin code to unlock, enter the pin code when clicking the next button does not return any results.

`BiometricPrompt.ERROR_CANCELED` error from the log when automatically jumping to pin code unlock screen.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.26.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.9 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.26.2

expo-local-authentication: "^9.3.0"

Phone:  Redmi K30 Pro
Android version: 10
MIUI version: 12.0.8

### Reproducible Demo

[https://snack.expo.io/@luhugo/localauthentication](https://snack.expo.io/@luhugo/localauthentication)
 
### Steps to Reproduce

Click the login button and use the wrong fingerprint in the popup dialog box until you are automatically redirected to the pin code unlock screen.

### Expected Behavior vs Actual Behavior

Expected behaviour:
After the fingerprint recognition fails several times, it will automatically jump to the pin code interface, enter the pin code and return the correct result.

Actual Behavior: 
After the fingerprint recognition fails several times, it automatically jumps to the pin code interface, and does not return any result after entering the pin code.

My project is a bare React Native app.

**Comment by malyalavenu** [comment]
I am also facing this issue. Please advise on a resolution

**Comment by MarcCarranza** [comment]
Been running into this error with a Mi 9 SE (MIUI 12.0), but not when using a Mi A2 (Android One). Seems like an error with non-default ROMs?

**Comment by EddyDunda** [comment]
Hey guys, any update?

**Comment by MarcCarranza** [comment]
@EddyDunda In my case, we ended up ditching the biometrics auth as it was a nice-to-have. Hope they end up looking into this

**Comment by EddyDunda** [comment]
@MarcCarranza , thanks, but this feature is important for our app.
@AdamJNavarro any updates for this bug?

**Comment by davidtkramer** [comment]
Spent a few hours digging into this, and it looks like the bug is in one of the native dependencies of this package. `androidx.biometric.BiometricPrompt` has a bug where it erroneously invokes the failure callback whenever the user falls back to using a PIN or password. Then, it never invokes the success callback when a correct PIN or password is entered. More information here: https://issuetracker.google.com/issues/142740104

**Comment by pkp93** [comment]
Same problem on MI 12.0.5. On clicking USE PATTERN, it triggers a cancel. Is there any other library which can be used ?

**Comment by pjcaro** [comment]
@davidtkramer is there a solution or workaround?

**Comment by RicardoBrito1938** [comment]
has anyone manage a workaround for this issue?
