### ISSUE TITLE
Explanation of temporary workaround for "Umbrella issue for task manager and background location issues on Android #9288"

### ISSUE THREAD

**Issue by miroslavskela** [expo/expo#10452]
This issue is currently locked, and I'm not sure I understand temporary workaround, so if someone could explain it here it would be great for me. I don't understand first sentence "If you need a fix right now, you should be able to use the bare workflow for the ExpoHeadlessAppLoader.." does this mean i should eject from expo, and also, how do you mean "..and revert back to managed flow once we deployed the patches.". 
Thank you very much. 
#9288

**Comment by brentvatne** [comment]
```
expo eject
```

afterwards, if you want to undo this:

```
rm -rf ios android
yarn remove react-native-unimodules
```
