### ISSUE TITLE
[expo-notifications] Notifications stop being received after around 5 minutes of device inactivity

### ISSUE THREAD

**Issue by brunoaduarte** [expo/expo#10456]
## Update from @brentvatne 

🚨  Running into this issue? It's actually expected behavior! See https://github.com/expo/expo/issues/10456#issuecomment-724907761 - tl;dr: you should send your notifications with high priority if it is important that they are displayed as soon as possible, and setting the channel priority to high is not sufficient for this.

<hr />

### Summary of Issue 

When device is active all notifications show properly, but as soon as i turn off the screen, after around 5 minutes, the phone stops showing the notifications, till i unlock the phone screen and all of the undelivered notifications will come all at once like in a flood of messages. Why is this happening?

I've seen it on a couple of Android 29 devices...

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.27.12 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Users\Myself\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 22, 23, 24, 26, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-15 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom   
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.2 => 0.63.2
      react-native-web: ~0.13.7 => 0.13.14
    Expo Workflow: bare
```

### Steps to Reproduce

Android 29 devices
Turn device screen off... wait ~5-10 minutes. Send notifications... none will come.
And when screen is unlocked later all of these undelivered notifications will come all at once (flood of messages)

### Expected Behavior vs Actual Behavior

Notifications arrive instantly

**Comment by pweisensee** [comment]
this seems related to previously reported issues with Notifications with SDK 38 https://github.com/expo/expo/issues/9037

@brunoaduarte which Notifications module are you using? [LegacyNotifications](https://docs.expo.io/versions/latest/sdk/legacy-notifications/) or [expo-notifications](https://docs.expo.io/versions/latest/sdk/notifications/)?

**Comment by brunoaduarte** [comment]
> this seems related to previously reported issues with Notifications with SDK 38 #9037
> 
> @brunoaduarte which Notifications module are you using? [LegacyNotifications](https://docs.expo.io/versions/latest/sdk/legacy-notifications/) or [expo-notifications](https://docs.expo.io/versions/latest/sdk/notifications/)?

I'm using SDK 39 with expo-notifications

`"expo-notifications": "~0.7.2",`

**Comment by brunoaduarte** [comment]
> this seems related to previously reported issues with Notifications with SDK 38 #9037
> 
> @brunoaduarte which Notifications module are you using? [LegacyNotifications](https://docs.expo.io/versions/latest/sdk/legacy-notifications/) or [expo-notifications](https://docs.expo.io/versions/latest/sdk/notifications/)?

Do the LegacyNotifications module works well with SDK39? I'm going to switch back to it if so.

**Comment by lukmccall** [comment]
Yes, the `LegacyNotifications` module works with the `SKD39`. 

I have one question. Is this occur only on Android 29?

**Comment by RodolfoGS** [comment]
I tested and works perfect for me. My device: Nexus 6P with Android 8.1.0, the same device of the original issue that I created https://github.com/expo/expo/issues/9037, and now with sdk 39 works great.

**Comment by brunoaduarte** [comment]
> Yes, the `LegacyNotifications` module works with the `SKD39`.
> 
> I have one question. Is this occur only on Android 29?
> 
> If yes, could you provide more details about the devices that you're using? Cause, I wasn't able to reproduce it.

I'm not sure, i only have this device to test, and the users that complaint about it also are on API 29.

My testing device is a Samsung A01 (SM-A013M) running Android 10 (API 29). The error does not occur with the emulator running Android 7.1.

**Comment by brunoaduarte** [comment]
> I tested and works perfect for me. My device: Nexus 6P with Android 8.1.0, the same device of the original issue that I created #9037, and now with sdk 39 works great.

Which version of expo-notifications are you using @RodolfoGS ?

**Comment by RodolfoGS** [comment]
@brunoaduarte 
```
expo: 39.0.3
expo-notifications: 0.7.2
```

**Comment by brunoaduarte** [comment]
I'm on expo: 39.0.2... i'll try to upgrade to 39.0.3

**Comment by cruzach** [comment]
I tried to reproduce this as well, and wasn't able to on "expo@39.0.3" & "expo-notifications@0.7.2"

**Comment by cruzach** [comment]
going to tentatively close this, if you can provide a minimal reproducible demo I'm happy to investigate further

**Comment by brunoaduarte** [comment]
I'm able to reproduce this very easily, are you testing with an Android 29 device?

I've tested it with fresh installations of all packages and applications on a brand new Mac computer, so it's impossible to be some corrupted installation or cached data.

1) Installed Android Studio
2) Installed Node.Js
3) Installed Expo CLI
4) `expo init --template bare-minimum testapp`
5) `cd testapp` && `expo install expo-notifications`
6) Follow all the instructions from `https://docs.expo.io/versions/latest/sdk/notifications/` (I'm using the exact same code from the sample)
7) Followed all the bare workflow instructions from `https://github.com/expo/expo/tree/master/packages/expo-notifications` (all I did was to import firebase credentials google-services.json)

Updated expo diagnostics output
```
  Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      Android SDK:
        API Levels: 26, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.16 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: bare
```
App.js
```
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import * as Permissions from 'expo-permissions';
import React, { useState, useEffect, useRef } from 'react';
import { Text, View, Button, Platform } from 'react-native';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: false,
    shouldPlaySound: true,
    shouldSetBadge: false,
  }),
});

export default function App() {
  const [expoPushToken, setExpoPushToken] = useState('');
  const [notification, setNotification] = useState(false);
  const notificationListener = useRef();
  const responseListener = useRef();

  useEffect(() => {
    registerForPushNotificationsAsync().then(token => setExpoPushToken(token));

    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
    });

    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      console.log(response);
    });

    return () => {
      Notifications.removeNotificationSubscription(notificationListener);
      Notifications.removeNotificationSubscription(responseListener);
    };
  }, []);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-around',
      }}>
      <Text>Your expo push token: {expoPushToken}</Text>
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>Title: {notification && notification.request.content.title} </Text>
        <Text>Body: {notification && notification.request.content.body}</Text>
        <Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
      </View>
      <Button
        title="Press to schedule a notification"
        onPress={async () => {
          await schedulePushNotification();
        }}
      />
    </View>
  );
}

async function schedulePushNotification() {
  await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail! 📬",
      body: 'Here is the notification body',
      data: { data: 'goes here' },
    },
    trigger: { seconds: 2 },
  });
}

async function registerForPushNotificationsAsync() {
  let token;
  if (Constants.isDevice) {
    const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    let experienceId = '@my/experienceid';
    token = (await Notifications.getExpoPushTokenAsync({ experienceId: experienceId })).data;
    console.log(token);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  return token;
}

```

**Comment by brentvatne** [comment]
@brunoaduarte - do you have another non-samsung android device to test this with? it seems the problem you describe is [pretty common with samsung devices](https://www.google.com/search?q=samsung+delayed+push+notifications). expo-notifications can't do anything about operating system level settings ([as indicated by this note in the docs](https://docs.expo.io/push-notifications/receiving-notifications/#closed-notification-behaviour)).

**Comment by brunoaduarte** [comment]
> @brunoaduarte - do you have another non-samsung android device to test this with? it seems the problem you describe is [pretty common with samsung devices](https://www.google.com/search?q=samsung+delayed+push+notifications). expo-notifications can't do anything about operating system level settings ([as indicated by this note in the docs](https://docs.expo.io/push-notifications/receiving-notifications/#closed-notification-behaviour)).

I see... well, in the case it's not expo related, i'm going to try this "fixes" for delayed notifications and see if that solves the problem.

Unfortunately i don't have other devices to test.

But i have users with other device brands that also have this issue

[Xiaomi Redmi 6 (API 28)](https://www.gsmarena.com/xiaomi_redmi_6-9237.php)
[Honor 20 Pro (API 29)](https://www.gsmarena.com/honor_20_pro-9710.php)
[Huawei P30 Pro (API 29)](https://www.gsmarena.com/huawei_p30_pro-9635.php)


And Samsung
[Samsung Galaxy A70 (API 29)](https://www.gsmarena.com/samsung_galaxy_a70-9646.php)
[Samsung Galaxy A51 (API 29)](https://www.gsmarena.com/samsung_galaxy_a51-9963.php)
[Samsung Galaxy S10e (API 29)](https://www.gsmarena.com/samsung_galaxy_s10e-9537.php)

**Comment by brunoaduarte** [comment]
Also, users complain that there are no notifications delays with other apps like WhatsApp or others. Very confusing.

**Comment by brunoaduarte** [comment]
@brentvatne I'm doing some tests here and i can confirm, it's not a device issue.

The problem is related to expo push servers.

I've just sent a broadcast push notification using Firebase Cloud Messaging and the push notification arrived in less than 10 seconds everytime!

But if i send a notification to the specific ExpoPushToken, it won't arrive until i unlock the screen...

**Comment by brunoaduarte** [comment]
I've stopped using Expo servers and now i'm sending push notifications directly with FCM following this tutorial [https://docs.expo.io/push-notifications/sending-notifications-custom/](https://docs.expo.io/push-notifications/sending-notifications-custom/). Problem fixed... no more delayed notifications.

**Comment by lukmccall** [comment]
@brunoaduarte, I have one question. When you're sending a notification through FCM, do you change the priority?

**Comment by brunoaduarte** [comment]
> @brunoaduarte, I have one question. When you're sending a notification through FCM, do you change the priority?

No, i don't change it. Using the default priority.

**Comment by brentvatne** [comment]
thanks for the info @brunoaduarte! we need to investigate what might be happening on our push server that is causing this.

**Comment by ide** [comment]
For now, using high priority might be the workaround. There is a chance the expo-notifications library is using data notifications, which sometimes get deferred.

**Comment by brunoaduarte** [comment]
> For now, using high priority might be the workaround. There is a chance the expo-notifications library is using data notifications, which sometimes get deferred.

Yes. Sorry, my mistake, i'm changing the priority indeed. Setting it to high.

**Comment by jtherrien-accuraty** [comment]
We are seeing this same behavior in our managed standalone app on a Google Pixel 3 running Android 11 (API 30) and Samsung Note 10+ running Android 10 (API 29). The app was built using Expo SDK 39 and expo-notifications 0.7.2, and the notification channel importance is set to AndroidImportance.MAX and lockscreenVisability set to AndroidNotificationVisibility.PUBLIC.

**Comment by brentvatne** [comment]
@jtherrien-accuraty - are you setting the priority to high when sending the notification? https://docs.expo.io/push-notifications/sending-notifications/#message-request-format

**Comment by jtherrien-accuraty** [comment]
@brentvatne that solved it for me. We are still building the backend so was using the expo notification tool at https://expo.io/notifications for testing, and it doesn't have a place to set the priority. Wrote a script for the backend to fire off a test message with high priority, and it worked perfectly. Thank you again!

**Comment by ide** [comment]
It sounds like **specifying `"priority": "high"` when sending Android notifications** -- this is unrelated to notification channels -- has been working for at least one person and lines up with Google's documentation on the topic. 

Expo accepts four priorities:
* "default": manually mapped to the default priority documented by Apple and Google
* "high": mapped to the high priority level documented by Apple and Google
* "normal": mapped to the normal priority level documented by Apple and Google
* (priority omitted): treated exactly as if "default" were specified

<img width="872" alt="notif" src="https://user-images.githubusercontent.com/379606/98718624-83720200-2343-11eb-9ad5-b4d8034f72a8.png">

---

For Android, Firebase documents the behaviors of the priority levels:

> **priority:**
>
> Sets the priority of the message. Valid values are "normal" and "high." On iOS, these correspond to APNs priorities 5 and 10.
>
> By default, notification messages are sent with high priority, and data messages are sent with normal priority. Normal priority optimizes the client app's battery consumption and should be used unless immediate delivery is required. For messages with normal priority, the app may receive the message with unspecified delay.
>
> When a message is sent with high priority, it is sent immediately, and the app can display a notification.

Cf. https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json
