### ISSUE TITLE
Expo facebook error [Error: Argument of an incompatible class: java.util.HashMap 

### ISSUE THREAD

**Issue by kaitolovemiku** [expo/expo#10468]
I find this bug by using the Android device (Samsung  Galaxy A01) with expo-facebook
I got this 

Facebook error [Error: Argument of an incompatible class: class java.util.HashMap cannot be passed as an argument to parameter expecting class java.lang.String.]

How should I fix this problem? 🙂

**Comment by cruzach** [comment]
hi! please fill out the full bug report template with the version of `expo-facebook` you're using and a minimal reproducible demo, otherwise there's not much we can do to investigate 🙁

**Comment by SilentRaw95** [comment]
I have the same issue with sdk 37
![0001](https://user-images.githubusercontent.com/39563174/94866682-6a516980-0405-11eb-9852-3a5914bdf54d.jpg)

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
