### ISSUE TITLE
Hey @shbhmbnsl1,

### ISSUE THREAD

**Issue by prathyusha-2001** [expo/expo#10465]
Hey @shbhmbnsl1,

u mentioned a error in expo, did u get the solution for that, if u get plz help me in solving that issue

**Comment by byCedric** [comment]
Please don't use Github as a forum. Either use [Slack](https://slack.expo.io/), [forums](https://forums.expo.io/), or reach out directly. We use Github as an issue tracker, using it as a forum makes it harder for us to work with Github.
