### ISSUE TITLE
[expo-notifications] Handle invalid notification payloads gracefully rather than crashing

### ISSUE THREAD

**Issue by kevin-ashton** [expo/expo#10462]
### Reproducible Demo

Client
```ts
import React from "react";
import { View, Text } from "react-native";
import * as notifications from "expo-notifications";

notifications.setNotificationHandler({
  handleNotification: async s => {
    return {
      shouldPlaySound: true,
      shouldSetBadge: true,
      shouldShowAlert: true
    };
  },
  handleError: e => {
    console.log("error");
  },
  handleSuccess: e => {
    console.log("sucess");
  }
});

export default function App() {
  return (
    <View style={{ margin: 30 }}>
      <Text>Hello World</Text>
    </View>
  );
}

```

Server
```ts



async function main() {

  let msg = {
    notification: {
      body: "World",
      title: "Hello"
    },
    data: {
      foo: "Hello",
      body: "WILL CRASH IF PROPERTY IS PRESENT"
    },
    apns: {
      headers: {
        "apns-priority": "10"
      },
      payload: {
        aps: {
          sound: "default",
          badge: 7
        }
      }
    },
    android: {
      priority: "high",
      notification: {
        icon: "notification_icon",
        channelId: "exampleChannel"
      }
    },
    token:
      "TOKEN"
  };

  // Send with service of your choice, FCM, direct to Apple, etc

  process.exit(0);
}

main();

```

### Expected Behavior vs Actual Behavior

I would not expect the shape of the data object to be able to hard crash the app everytime.

**Comment by cruzach** [comment]
Hi! if you're sending notifications directly through APNs or FCM, then you should refer to this documentation for the payload formats that the `expo-notifications` package expects- https://docs.expo.io/push-notifications/sending-notifications-custom/#ios

**Comment by kevin-ashton** [comment]
From a technical perspective the definitions might be right.  That being said at Google allows you to send a `data` property at the root node even for iOS. 

See https://github.com/firebase/firebase-admin-node/blob/master/src/messaging.d.ts#L3

Mostly it just feels a little bad I swapped out one library and switched to expo-notifications and things began just hard crashing. Seems less ideal that a malformed notification (which isn't malformed if you follow Google's type definitions) can just hard crash the app. 

Thanks for the product though! What you are doing on Expo is great!

**Comment by brentvatne** [comment]
@kevin-ashton - that's reasonable, i'm not totally clear on what the best behavior would be in this case but certainly crashing isn't the best. we should handle invalid payloads more gracefully

**Comment by sjchmiela** [comment]
I totally agree. Fortunately we have a fix already in place for this. Basically `expo-notifications` assumed too much about the payload format ([assumed `data.body` is a map](https://github.com/expo/expo/pull/10453/files#diff-8623d3b9743dff7244f4ff48445195fbL75)). Now, (after [this change](https://github.com/expo/expo/pull/10453/files#diff-8623d3b9743dff7244f4ff48445195fbR75)) `expo-notifications` will just pass `data.body` as `data` of the notification.

Soon we'll release an updated version of `expo-notifications` that won't crash the app if `data.body` is not a dictionary. 🙂 

Now that I think about it… maybe we should validate whether `data.body` is a dictionary given we define `Notification` TS type as having a dictionary under `data`…?

**Comment by rodneyrehm** [comment]
> Soon we'll release an updated version of expo-notifications that won't crash the app **if data.body is not a dictionary**.

How can `data.body` be a dictionary in the first place?

* [FCM docs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message.FIELDS.data) say `map (key: string, value: string)`
* [firebase-admin types](https://github.com/firebase/firebase-admin-node/blob/9dd4040888d7d6ac7c2970bad26e7646d6a3f384/src/messaging/index.ts#L679-L681) say `[key: string]: string;`
* copying the [Firebase notification types](https://docs.expo.io/push-notifications/sending-notifications-custom/#firebase-notification-types) example leads to the typescript error `Type '{ photoId: number; }' is not assignable to type 'string'.` (ping @cruzach  who edited the docs last) - assuming we're talking about the same [firebase-admin](https://www.npmjs.com/package/firebase-admin) here.

While [APNS allows nested structures](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification?language=objc), I don't see how FCM does?

**Comment by sjchmiela** [comment]
`expo-notifications` on Android tries to parse Firebase's `data.body` as a JSON dictionary, see [code](https://github.com/expo/expo/blob/d40fb974f9c6310011e69e0bcf375725362c2458/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/JSONNotificationContentBuilder.java#L125-L132). Consider this `expo-notifications`' API.

To use send an `expo-notifications`-compatible message with `firebase-admin` I would suggest `JSON.stringify`ing the `body` (or you can use [`expo-server-sdk-node`](https://github.com/expo/expo-server-sdk-node) to send notifications with Expo servers).

**Comment by rodneyrehm** [comment]
> expo-notifications on Android tries to parse Firebase's data.body as a JSON dictionary,

Is the same true for iOS?
if not can this be made compatible?

> To use send an expo-notifications-compatible message with firebase-admin I would suggest JSON.stringifying the body 

sounds like you're suggesting to fix the docs to reflect the current situation:

```diff
@@ -11,9 +11,9 @@ admin.messaging().sendToDevice(
       // here is a "message". For more info see:
       // https://docs.expo.io/versions/latest/sdk/notifications/#android-push-notification-payload-specification

-      body: {        // ⚠️ As per Android payload format specified above, the
+      body: JSON.stringify({        // ⚠️ As per Android payload format specified above, the
         photoId: 42, // additional "data" should be placed under "body" key.
-      }
+      })
     },
   },
   options
```

**Comment by sjchmiela** [comment]
As you said, _APNS allows nested structures_ and what we expose under `content.data` is `userInfo[@"body"]` (or `userInfo` if it is a local notification, see [code](https://github.com/expo/expo/blob/69c8b63f5f64b87d990e1660beaf13a1603c0443/packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationSerializer.m#L72-L76)).

In general I think if you were to send notifications directly to APNS you'd send a payload of
```
{
   "aps" : {
      "alert" : {
         "title" : "Game Request",
         "subtitle" : "Five Card Draw"
         "body" : "Bob wants to play poker",
      },
      "category" : "GAME_INVITATION"
   },
   "data" : {
      "yourData": 2
   }
}
```

as per [documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification?language=objc#2943359):
> In addition to the Apple-defined keys, you may add custom keys to your payload to deliver small amounts of data to your app, notification service app extension, or notification content app extension. Your custom keys must have values with primitive types, such as **dictionary**, array, string, number, or Boolean. Custom keys are available in the `userInfo` dictionary of the `UNNotificationContent` object delivered to your app.
> 
> Typically, you use custom keys to help your code process the notification. For example, you might include an identifier string that your code can use to look up app-specific data. **Add app-specific keys as peers of the `aps` dictionary.**

**Comment by cruzach** [comment]
> sounds like you're suggesting to fix the docs to reflect the current situation

that's correct, I just updated the docs to reflect this! thanks for pointing that out
