### ISSUE TITLE
Fatal JS error hangs on splash screen rather than crashing

### ISSUE THREAD

**Issue by tevonsb** [expo/expo#10463]
### Summary of Issue 
After upgrading to SDK 39, the app will become completely unresponsive (stuck on the loading update) screen after the first OTA update.
### Environment - output of `expo diagnostics` & the platform(s) you're targeting

>   Expo CLI 3.27.8 environment info:
>     System:
>       OS: macOS 10.15.6
>       Shell: 5.7.1 - /bin/zsh
>     Binaries:
>       Node: 14.9.0 - /usr/local/bin/node
>       Yarn: 1.22.5 - ~/.yarn/bin/yarn
>       npm: 6.14.7 - /usr/local/bin/npm
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 14.0, DriverKit 20.0, macOS 10.16, tvOS 14.0, watchOS 7.0
>     IDEs:
>       Xcode: 12.0/12A6163b - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ^39.0.0 => 39.0.3 
>       react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
>     npmGlobalPackages:
>       expo-cli: 3.22.1
>     Expo Workflow: managed

### Reproducible Demo
This issue is NOT reproducible without publishing to a release channel.

### Steps to Reproduce
1. publish to a release channel (including default)
2. Publish again to that release-channel.
3. Observe that app is stuck on "downloading update splashscreen"

### Expected Behavior vs Actual Behavior
Update to be loaded : App is stuck downloading the update.

Possibly related to: 

https://github.com/expo/expo/issues/10304

**Comment by tevonsb** [comment]
Found the solution: for us we had an undefined value stemming from https://github.com/expo/expo/issues/10304. 

This was causing the app to hang infinitely at the "updating" staging on iOS, and to crash properly on android. 

A minimal example can be found here: https://github.com/JoinOXO/min-expo-repro/

**Comment by brentvatne** [comment]
thank you @tevonsb for investigating this!

**Comment by Norfeldt** [comment]
> Found the solution: for us we had an undefined value stemming from #10304.
> 
> This was causing the app to hang infinitely at the "updating" staging on iOS, and to crash properly on android.
> 
> A minimal example can be found here: https://github.com/JoinOXO/min-expo-repro/

@tevonsb  I don't know if this is related. I'm having this issue with my android production app (_managed workflow_)- it hangs at the splash screen waaaay longer than set by `fallbackToCacheTimeout: 10000` - with patience it comes by. Also did a `expo publish` on another production app and noticed that the iPhone version does not seem to catch this air update. Is there an issue with OTA updates at the moment?

**Comment by tevonsb** [comment]
Hey @Norfeldt yes there is, the issue you quoted #10304 mentions the issue with OTA currrently. On SDK 39 updates to custom release channels will not go through, instead only default release channel updates will actually update standalones using SDK 39.

**Comment by brentvatne** [comment]
we have fixed the bug leading to this issue and it'll go out in our patch release soon!

**Comment by Norfeldt** [comment]
> Hey @Norfeldt yes there is, the issue you quoted #10304 mentions the issue with OTA currrently. On SDK 39 updates to custom release channels will not go through, instead only default release channel updates will actually update standalones using SDK 39.

@tevonsb @brentvatne 

It just that the issues I have been referring to has been to default channels - hasn't used any channel but just `expo publish`.

------

BTW expo is great - I know that RN is evolving very quickly and expo is making the "rails" to let single indie developers deliver big comporate like ("train") solutions. You are a fantastic team!

**Comment by brentvatne** [comment]
@Norfeldt - default channels work as expected as far as we know. if this is not the case for you then please post a new issue with a reproducible example and steps to reproduce

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/10464#issuecomment-703178030
