### ISSUE TITLE
Issues with Swipeable Gesture Handler

### ISSUE THREAD

**Issue by ShMcK** [expo/expo#1046]
It should be easier to get Swipeable lists working with Expo.

1. Swipeable is not included with Expo
2. Swipeable cannot simply be imported from 'react-native-gesture-handler'

---

### Problem

`import { Swipeable } from 'react-native-gesture-handler'` also fails with the following error:

```
tried to register two views with the same RNGestureHandlerButton
```

This seems to be due to both Expo & RNGH registering their own gestures.

### Temp Solution

Gestures can be resolved if you import the code for Swipeable from the RNGH repo, then replace the RNGH imports with Expo imports.

```js
// import { PanGestureHandler, TapGestureHandler, State } from 'react-native-gesture-handler'
import { DangerZone } from 'expo'
const { GestureHandler } = DangerZone
const {
  PanGestureHandler,
  TapGestureHandler,
  State,
} = GestureHandler
```

As a downside, hardcoding an npm package will miss out on important updates. 

---

### Possible Fixes

1. Add Swipeable to Expo. 🍟 
2. Fix `RNGestureHandlerButton` to use Expo by default and ignore imports. 😕 
3. Avoid recommending using Swipeable with Expo 😞 
4. Create an '@expo/swipeable' package 😃

**Comment by brentvatne** [comment]
hello! we discussed this yesterday! looking into a good solution
