### ISSUE TITLE
Expo SDK 39 -  expo-av - video.dismissFullscreenPlayer method is not working on IOS (tested on simulator)

### ISSUE THREAD

**Issue by Adirsimona** [expo/expo#10473]
## 🐛 Bug Report

Seems like in the last release (Expo SDK 39) expo-av -> video -> dismissFullscreenPlayer function is not working anymore on IOS in Bare flow, still works the same on Android device.

 Environment :

  Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 10.15.6
    Binaries:
      Node: 14.5.0
      Yarn: 1.22.5 
      npm: 6.14.7
      Watchman: 4.9.0
    Managers:
      CocoaPods: 1.9.3 
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2
    IDEs:
      Android Studio: 4.0
      Xcode: 11.7/11E801a
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.2 => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.27.12
    Expo Workflow: bare

Steps to Reproduce: 
1. Use video with expo 39 and expo-av 8.6.0 : "expo": "^39.0.0", "expo-av": "~8.6.0".
2. Open a video in fullscreen mode.
3. Try to dismiss fullscreen mode on the IOS simulator by the dismissFullscreenPlayer method. (be aware to use await or then() to invoke the promise)
4. Nothing happens on IOS, Android works fine. 

Expected Behavior: 
The fullscreen mode should dismiss on IOS too.

**Comment by brentvatne** [comment]
@Adirsimona - can you confirm that this worked as expected for you on SDK 38? could you provide a reproducible example as well?

**Comment by Adirsimona** [comment]
@brentvatne I don't know if it works on SDK 38, I start to use this method for the first time at 39.
