### ISSUE TITLE
[expo-file-system][iOS] lack of utf-8 uri support on iOS

### ISSUE THREAD

**Issue by robertying** [expo/expo#10476]
### Summary of Issue 

on iOS, `expo-file-system` cannot properly handle uri that contains utf-8 strings.

It seems these lines of code that create URL from strings are responsible. They all return `nil` for any utf-8 file uri.

```objc
NSURL *uri = [NSURL URLWithString:uriString];
```

I believe we should use `NSURL fileURLWithPath` or `stringByAddingPercentEncodingWithAllowedCharacters` to properly handle this.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
    Expo Workflow: bare
```

### Steps to Reproduce

```js
import * as fs from 'expo-file-system';
await fs.makeDirectoryAsync(fs.documentDirectory + "中文");
```

throws an error: `[Error: Directory '(null)' could not be created because the location isn't writable.]`.

### Expected Behavior vs Actual Behavior

Uri should work with utf-8 strings.

**Comment by robertying** [comment]
Bump for visibility...

**Comment by albingroen** [comment]
I'm running into this problem as well. I'm trying to create local files that include Nordic letters like "Å, Ä, Ö" but keep getting an error for this. This will be a dealbreaker if it doesn't work... Any plans for a solution here?

**Comment by brentvatne** [comment]
we ended up having to revert this, @gabrieldonadel is investigating
