### ISSUE TITLE
ImagePicker.launchImageLibrary async still compresses video on iOS even if VideoExportPreset.Passthrough is chosen

### ISSUE THREAD

**Issue by gyoung-panopto** [expo/expo#10480]
### Summary of Issue 

I want to disable video compression entirely in the ImagePicker on iOS, so I set videoExportPreset to VideoExportPreset.Passthrough. However, I'm seeing that the "Compressing video..." progress bar on iOS still appears and takes several seconds to fill up on longer videos.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.27.8 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-navigation: ^3.11.0 => 3.13.0
    Expo Workflow: managed

Only reproduces on iOS

### Reproducible Demo

    const result = await ImagePicker.launchImageLibraryAsync({
          mediaTypes: ImagePicker.MediaTypeOptions.Videos,
          videoExportPreset: ImagePicker.VideoExportPreset.Passthrough
    });
 
### Steps to Reproduce

1. Use the code snippet above on iOS
2. Open a larger file with the image picker and tap "Use"

### Expected Behavior vs Actual Behavior

Expected:
Video compression is skipped entirely because Passthrough was selected

Actual:
"Compressing video" appears and the progress bar takes time to fill up proportional to the video's size

Is there some configuration I'm missing? Why does it still need to compress the video if Passthrough is chosen?

**Comment by gyoung-panopto** [comment]
Any updates on this? I'm wondering if there is some config I'm missing or if there is a bug somewhere in the native code. It seems like compression should be skipped if Passthrough is specified.

**Comment by Razorholt** [comment]
Same problem here

**Comment by lafiosca** [comment]
I just tested several different VideoExportPreset settings on an iPhone 8 running iOS 14.4, and none of them seemed to do anything, both when launching the library and launching the camera. Maybe it's more than just deprecated.

**Comment by rvieceli** [comment]
Same problem here.
