### ISSUE TITLE
Upgrade connect

### ISSUE THREAD

**Issue by lifeiscontent** [expo/expo#1048]
when creating an new expo project and npm installing I see this warning.

connect@2.30.2: connect 2.x series is deprecated

**Comment by brentvatne** [comment]
This comes from react-native itself

> warning react-native > connect@2.30.2: connect 2.x series is deprecated

See: https://github.com/facebook/react-native/blob/6e1db1f1ee263c3a8b68c3e1584e79ae86d5be86/package.json#L162

Please create an issue on https://github.com/facebook/react-native/issues or if you're feeling generous with your time, submit a pull request to fix it!
