### ISSUE TITLE
[expo-media-library] Crash getAssetsAsync in Android 10

### ISSUE THREAD

**Issue by eyu0415** [expo/expo#10488]
### Summary of Issue 

getAssetsAsync will crash in android 10 (real device)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

 Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.3/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.13.1 => 16.13.1
      react-native: ^0.63.3 => 0.63.3
    npmGlobalPackages:
      expo-cli: 3.24.2

expo-media-library: 9.2.1
react-native-unimodules: 0.11.0

### Reproducible Demo

https://snack.expo.io/@natysoz/sdk-39-exif-issue
 
### Steps to Reproduce

Requirement
- Real device with android 10 (in my case SM-N976N - samsung galaxy note 10)

Steps

1. Install Expo in device
2. Run demo
3. Allow permissions
4. Press 'LOAD ASSETS' button

### Expected Behavior vs Actual Behavior

Expected Behavior: load assets success
Actual Behavior: Error occured [FROM](https://github.com/expo/expo/blob/829acd688d99334d68090ecc83757c000a606e99/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAssets.java#L63)

### P.S.
#10398 was closed
Because expo sdk 39 will fix issues.
But bare workflow still catch error

**Comment by barthap** [comment]
If you use bare workflow, try debugging which line throws the `IOException` (last line before jumping into `catch` block), because I couldn't reproduce it on any device.

**Comment by eyu0415** [comment]
> If you use bare workflow, try debugging which line throws the `IOException` (last line before jumping into `catch` block), because I couldn't reproduce it on any device.

I tracked line by line for find which code throw error.

The error occured create [ExifInterface](https://developer.android.com/reference/android/media/ExifInterface#ExifInterface(java.lang.String)) in [MediaLibraryUtils.java](https://github.com/expo/expo/blob/829acd688d99334d68090ecc83757c000a606e99/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.java#L157)

the path is '/storage/emulated/0/DCIM/Album 3/IMG_7203.jpg'

**Comment by barthap** [comment]
Try updating `androidx.exifinterface:exifinterface:1.0.0` to `1.3.0` in `expo-media-library/android/build.gradle`, then rebuild project and let me know if it helped. It seems the issue may be related to some permission changes.

**Comment by eyu0415** [comment]
Not only exifinterface version upgrade but also add
> android:requestLegacyExternalStorage="true"
will fixed this issues

Thanks for quickly response.

**Comment by barthap** [comment]
Glad it helped, I'll keep it open until a fix is ready.

**Comment by matias91** [comment]
Hi!
I'm having the same issue in the managed workflow.
I followed all the suggestions I found on different issues, but it's still crashing on Android 10.

I'm using SDK 39, I added `"READ_EXTERNAL_STORAGE"` and `"WRITE_EXTERNAL_STORAGE"` in `android:permissions` on app.json, I'm requesting the permissions with `MediaLibrary.requestPermissionsAsync`. Nothing works.

My use case is identical as the one on the snack provided in this issue.

Any help will be really appreciated.
Thanks!

expo diagnostics:
```
Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.3.9 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed
```
