### ISSUE TITLE
[SDK 39] React Navigation navigation.setOptions in function component shows warning

### ISSUE THREAD

**Issue by apedroferreira** [expo/expo#10487]
## 🐛 Bug Report

If I use, for example,```navigation.setOptions({ title: 'Title' })``` to set a dynamic title in a React Navigation screen, in SDK 39 it now shows me the warning `Cannot update a component from inside the function body of a different component`. This did not show in SDK 38.

Is this a bug or is there some new recommended way of doing things?

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues/8796

this issue belongs on the react-navigation repo :) we work on that library too but we don't track issues here

**Comment by Razorholt** [comment]
Put navigation.setOptions inside a useEffect

**Comment by apedroferreira** [comment]
Yep, using an effect is the right way to do it and this was a mistake. Thanks all for the help!

**Comment by mostafero** [comment]
Do not change navigation properties in the constructor, and best way is to use componentdidmount:
```javascript
export default class CustomScreen extends Component {
  init() {
    const {route, navigation} = this.props;
    const custom_param = route.params.custom_param; // 
    navigation.setOptions({title: custom_param});
  }

  componentDidMount() {
    this.init(); // here is the right place to change header title for example (title is just an example here you can change other properties ofc)
  }

  render() {
    const {route, navigation} = this.props;
    const type = route.params.type;
    return <View>
    // .....
   </View>;
  }
}
```
