### ISSUE TITLE
[expo-av] Unmounting video : crash when compiled to APK

### ISSUE THREAD

**Issue by Narduzzi** [expo/expo#10491]
### Summary of Issue 

When unmounting a video, the application crashes when compiled to APK.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.27.3 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      expo: latest => 39.0.3 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ^0.63.3 => 0.63.3 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.3
    Expo Workflow: managed

Target platform : Android 10

### Reproducible Demo

Code is available here:
- https://github.com/Narduzzi/talk-bug

### Steps to Reproduce

- Clone repository and install packages
- `expo build:android`
- install android app and run it
- click on "Download" button to get the test video
- click on "Video" button to go to the screen showing the video
- click on "Back to audio" button to go back to the previous screen.
- click anywhere: crash.

### Expected Behavior vs Actual Behavior

Application works fine using `expo start`. Crash occurs only when compiled to APK.
Should be able to unmount video and continue to use the application.

**Comment by brentvatne** [comment]
hi there! please remove anything related to vue from that repo. we do not support that. [learn more about how to create a mcve](https://stackoverflow.com/help/mcve)
