### ISSUE TITLE
When I use Picker, I get this Warning only on iPhone : VirtualizedLists should never be nested inside plain ScrollViews with the same orientation 

### ISSUE THREAD

**Issue by khaja-nizamuddin1** [expo/expo#10493]
### Summary of Issue 
When I use React Native - native base **Picker** and display a list from an array, I get below warning
This happens only in iPhone, Android code works fine without any warnings
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

The warning persists even if I am displaying just 2-3 static Picker items

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.27.8 environment 
System: OS: Windows 10 Pro 64 bit
Device: iPhone 7 plus iOS: 14.0
Expo Workflow: managed

### Reproducible Demo

```
<Component>
                 <Header>
                    <Body>
                        <Title>Title</Title>
                    </Body>
                </Header>
    <Content>
        <Form>
            <Item rounded style={{marginBottom:20}}>
                  <Picker selectedValue={this.state.district} onValueChange={(val)=>this.setDistrict(val)}>
                       <Picker.Item label='Select District' value='0'/>  
                        {this.state.districtsList.map((item,index) => {
                             return (<Picker.Item label={item.name} value={item.id} key={index}/>) 
                        })}
                  </Picker>
        </Form>
    </Content>
</Container> 
 
```

districtsList is an array, displaying 2 values in the Picker item
Warning still pops up if I render only 2-3 static items in Picker
### Steps to Reproduce
Can be reproduced in any plain screen, with above given code 

### Expected Behavior vs Actual Behavior
Code should
![WhatsApp Image 2020-10-01 at 5 40 18 PM](https://user-images.githubusercontent.com/13907986/94807395-38dc9c00-040d-11eb-8ef4-82650855f125.jpeg)
 display the picker items without any warning

**Comment by AdamJNavarro** [comment]
Hey @khaja-nizamuddin1,

These components are not related to Expo so I'm going to close this issue. I would recommend opening an issue in native-base's repo.

Cheers,
Adam
