### ISSUE TITLE
[expo-av] - video: when the user skips the video forward on Android using the video slider controller the video gets stuck, IOS works fine.

### ISSUE THREAD

**Issue by Adirsimona** [expo/expo#10497]
Bug Report
Android:
When the user skips the video forward on Android using the video slider controller the video gets stuck, IOS works fine.

get this error on the console:
![image](https://user-images.githubusercontent.com/19407726/94824302-c368cf80-03fc-11eb-9562-2b2ccbe5ae84.png)

Environment 
  Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - 
      Yarn: 1.22.5 -
      npm: 6.14.7 -
      Watchman: 4.9.0 
    Managers:
      CocoaPods: 1.9.3 - 
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.7/11E801a - 
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.2 => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.27.12
    Expo Workflow: bare

 
### Steps to Reproduce
1. Open expo project using SDK 39 and expo-av 8.6.0.
2. Open Android Simulator.
3. Play any URL with a Video component.
4. Try to move backward or forward with the native controls.

Expected Behavior 
The video should be buffering the new position and continue playing

**Comment by AdamJNavarro** [comment]
Hey @Adirsimona,

Could you please provide a reproducible example of this that we can use to test on our end? Ideally in the form of a Snack or a public repository. Also, have you tested on a physical device and seen if the error occurs?

Cheers,
Adam

**Comment by Adirsimona** [comment]
@AdamJNavarro Hi Adam,
Yes I tested it on a physical device and it's still reproduce.
I can't provide here reproducible example, this issue coming from a big project and it's not just a small piece of code. Just use any video object with any url and try to move forward with video slider and it will happen again

**Comment by Adirsimona** [comment]
@AdamJNavarro any updates about this issue?
it's critical for my product and stuck our release to production.

please let me know if there is any workaround to solve it.

**Comment by Adirsimona** [comment]
Hey @AdamJNavarro,
Link to snack:
https://snack.expo.io/K8GzRkgMJ

Note that this issue is only happening **when I'm using CDN URL**, in this case - CloudFront.
Works fine on IOS and any web platform.

**Comment by Adirsimona** [comment]
@AdamJNavarro,
So I debug it by myself and I found a way to solve it,
all you need to do is to update the okhttp3 lib in expo-av build.gradle file to the latest version.

here is the path:
open android studio
go to expo-av -> android -> 
open build.gradle file ->

change 
 api "com.squareup.okhttp3:okhttp:3.10.0"
 api "com.squareup.okhttp3:okhttp-urlconnection:3.10.0"

to
  api "com.squareup.okhttp3:okhttp:4.9.0"
  api "com.squareup.okhttp3:okhttp-urlconnection:4.9.0"

Hope it will help you to fix this issue as soon as possible on your side

**Comment by mikhailperemitko** [comment]
I'm experiencing the same problem on Android. For me the issue happens when I'm using GraphCMS asset url https://media.graphcms.com/jyLnBuPTOaiOgZxP0fR3, but everything works as expected when using this one http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4. iOS works fine in both cases.

**Comment by Adirsimona** [comment]
@AdamJNavarro, any updates?

**Comment by valascus** [comment]
Having the same issue.

**Comment by glowingmanagement** [comment]
I'm having the same issue

**Comment by Rpaixao** [comment]
I am having a similar issue on Android. Basically, I am playing a playlist of videos and when I skip the video to the next one (2 or 3 times, it depends), the component controllers get stuck and videos stop being reproduced. I analyzed a bit the android native logs, and I got the idea (it's just a guess) that, although I skip the video to the next one, the previous video keeps being buffered and somehow the memory/buffer max capacity is reached. 

iOs works perfectly.

**Comment by samih7** [comment]
Having the exact same issue…

**Comment by sebastianrueckerai** [comment]
I have the same issue! Player will freeze on android when playing multiple videos in a row.

Also: On iOS when skipping from one video to the next the second video starts at the time the first video ended.
Lets say video A is 15 seconds long and video B is 50 seconds long -> When watching video A completely and then going to video B, video B will start at position 0:15!

**Comment by jeanlucnguyen** [comment]
Same issue here, tried with the links posted by @mikhailperemitko and I confirm it works with http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 but not with https://media.graphcms.com/jyLnBuPTOaiOgZxP0fR3

On our side, we are experiencing this problem with m3u8 videos from mux.com

**Comment by marco2216** [comment]
Same issue

**Comment by konyilwin** [comment]
Same issue

**Comment by victorlocomotiv** [comment]
Same issue

**Comment by valascus** [comment]
And it will keep happening in the next year aswell. Merry christmas!

**Comment by xididri** [comment]
Same issue here while playing a video hosted on Firebase Storage. After a while I get this error (when callback `onError` is defined):

```
Player error: Unable to connect to https://firebasestorage.googleapis.com/...
at components/Video.jsx:60:14 in Video
at node_modules/expo-av/build/Audio/Sound.js:149:4 in replayAsync
```

**Comment by counthackula** [comment]
I have the same issue. I tried a lot of things including switching to react-native-video-player, which solved it. Unfortunately, switching to RNVP opened up some other issues such as lackluster implementation of fullscreen video on Android.

I believe this issue is has its roots in the implementation of OkHttpClient. But I found a workaround
I looked at this issue, where it seems like the issue was solved by switching libraries
https://github.com/google/ExoPlayer/issues/4078

...and looked at this still open issue:
https://github.com/square/okhttp/issues/3146

...and took this idea to force HTTP/1.1 :
https://stackoverflow.com/questions/41925501/java-okhttp3-only-use-http-1-1-or-http-2

....and amended /node_modules/expo-av/android/src/main/java/expo/modules/av/player/datasource/SharedCookiesDataSourceFactory.java

I added `builder.protocols(Arrays.asList(Protocol.HTTP_1_1));`

....like so:
`package expo.modules.av.player.datasource;

import android.content.Context;

import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
import com.google.android.exoplayer2.upstream.TransferListener;

import java.net.CookieHandler;
import java.util.Arrays;
import java.util.Map;

import expo.modules.core.ModuleRegistry;
import okhttp3.JavaNetCookieJar;
import okhttp3.OkHttpClient;
import okhttp3.Protocol;

public class SharedCookiesDataSourceFactory implements DataSource.Factory {
  private final DataSource.Factory mDataSourceFactory;

  public SharedCookiesDataSourceFactory(Context reactApplicationContext, ModuleRegistry moduleRegistry, String userAgent, Map<String, Object> requestHeaders, TransferListener transferListener) {
    CookieHandler cookieHandler = moduleRegistry.getModule(CookieHandler.class);
    OkHttpClient.Builder builder = new OkHttpClient.Builder();
    if (cookieHandler != null) {
      builder.cookieJar(new JavaNetCookieJar(cookieHandler));
    }
    builder.protocols(Arrays.asList(Protocol.HTTP_1_1));
    OkHttpClient client = builder.build();
    mDataSourceFactory = new DefaultDataSourceFactory(reactApplicationContext, transferListener, new CustomHeadersOkHttpDataSourceFactory(client, userAgent, requestHeaders));
  }

  @Override
  public DataSource createDataSource() {
    return mDataSourceFactory.createDataSource();
  }
}
`

And it worked!

**Comment by rafaelgilead** [comment]
@counthackula didn't work for me. always hangs loading when I turn the video slider back. meanwhile, expo-video-player worked fine, but I prefer to use expo-av 
i run rm -fr $TMPDIR/metro-cache && rm $TMPDIR/haste-map-* && expo start --clear
i am using various Videos into Flatlist

**Comment by msphn** [comment]
Indeed we had this issue. We disabled now http2 support in our cdn used for streaming video resources which at least resolved this issue. The android player is still in bad shape and quite laggy, but it no longer freezes up.

**Comment by rafaelgilead** [comment]
I solved this using expo-video-player package

**Comment by msphn** [comment]
we tried expo-video-player, when tested we figured out that when entering fullscreen the issue remains.

**Comment by rafaelgilead** [comment]
are you using native fullscreen or have you created your own?

**Comment by lightrow** [comment]
> are you using native fullscreen or have you created your own?

the issue still was present when using native fullscreen. We can't use custom UI overlay because our video player is nested deeply within the app and we can't expand it to fullscreen without putting in into modal or portal, which remounts the player with loss of all internal cache and state

**Comment by rafaelgilead** [comment]
> > are you using native fullscreen or have you created your own?
> 
> the issue was still present when using native fullscreen (i.e. ExoPlayer). We can't use custom UI overlay because our video player is nested deeply within the app and we can't expand it to fullscreen without putting in into modal or portal, which remounts the player with loss of all internal cache and state

I'm also facing something similar. if you can't solve it, I'll adhere to your suggestion to disable http2 on cdn.

**Comment by sebastianrueckerai** [comment]
I still have this issue, it is a huge hurdle to do anything with video on Android.

**Comment by ThomasWillumsen** [comment]
Still an issue 🤐

**Comment by valascus** [comment]
> Still an issue 🤐




> And it will keep happening in the next year aswell. Merry christmas!


Who would have guessed

**Comment by msphn** [comment]
We have dropped expo meanwhile, problem solved.

**Comment by liquidvisual** [comment]
@msphn Did you use `react-native-video` instead? In my experience that's even worse in terms of bugs.

**Comment by msphn** [comment]
We forked that one and fixed all issues we had with it.

**Comment by msphn** [comment]
Could be, but didn't happen yet. But we also forked it and update some dependencies and so on. So hard to tell. The biggest deal is, that it's easier to extend for us

**Comment by sebastianrueckerai** [comment]
@barthap It may only happen on a real android device.

I subscribe to Rubens theory: 
https://github.com/expo/expo/issues/10497#issuecomment-796682896

This looks like a buffer issue. Which would explain why it takes an unpredictable amount of time to happen.

**Comment by sebastianrueckerai** [comment]
@barthap If you are interested I can demonstrate the error happening in my app

**Comment by marco2216** [comment]
Same issue here

**Comment by sebastianrueckerai** [comment]
The issue is as relevant as ever!

**Comment by xididri** [comment]
Hi, bot! I am currently active and like many, I want this issue to be resolved :-)

**Comment by sebastianrueckerai** [comment]
This is still an issue, still not solved.

**Comment by Rpaixao** [comment]
This is still an issue, still not solved. We are waiting for years 😇

**Comment by watadarkstar** [comment]
For those that have this issue I found that it is an issue with `.mp4` videos. However, if you use `.m3u8` it works fine!

**Comment by sebastianrueckerai** [comment]
Still a problem!

**Comment by lukmccall** [comment]
Could you try using our new package, `expo-video`, and see if the problem is still there?

**Comment by sebastianrueckerai** [comment]
Still an issue!

**Comment by nyplex** [comment]
still an issue!
