### ISSUE TITLE
Change the push notification server docs example to use the node sdk

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#1050]
Easier to follow when it's just the one language.

**Comment by ide** [comment]
Historically the Node SDK is best supported, nudging developers to use it will work out best for them I think.

**Comment by AdamJNavarro** [comment]
I'll try and get this done early next week.

**Comment by ide** [comment]
One related thing for the tutorial/guide - Firebase's free "Spark" plan blocks outbound network requests to non-Google APIs so we should steer people towards paid Firebase or AWS or GCP (non-Firebase) or Heroku or now.sh, etc... This isn't specific to the Node SDK but is a question we get sometimes.
