### ISSUE TITLE
How to disable unused android activities (Stripe for example)

### ISSUE THREAD

**Issue by cdstamper** [expo/expo#10507]
### Summary of Issue 

I got a complaint from my company's compliance department that an app build with expo was rejected due to an unnecessary 'activity' which is being exported. In this case, a url scheme for Stripe: `abi35_0_0.expo.modules.payments.stripe`

This app is built with expo and NOT ejected. I decompiled the binary with APKTool, and was able to find the reference in the AndroidManifest.xml:

```
<activity android:exported=“true” android:launchMode=“singleTask” android:name=“abi35_0_0.expo.modules.payments.stripe.RedirectUriReceiver” android:theme=“@android:style/Theme.Translucent.NoTitleBar.Fullscreen”>
    <intent-filter>
        <action android:name=“android.intent.action.VIEW”/>
        <category android:name=“android.intent.category.DEFAULT”/>
        <category android:name=“android.intent.category.BROWSABLE”/>
        <data android:scheme=“abi35_0_0.expo.modules.payments.stripe”/>
    </intent-filter>
</activity>
```

Why is expo exporting this android activity for Stripe? I don't use Stripe in the app and have not installed the payment module.

Is there a way to disable unused activity exports (`android:exported="false"`)?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Using SDK 38 for Android

```
  Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 11.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.12
    Expo Workflow: managed

```
### Expected Behavior vs Actual Behavior

I do not expect to see my app export a URL handler for stripe, when my app does not use payments at all.

See image for all exported schemes: 
<img width="624" alt="image" src="https://user-images.githubusercontent.com/7362344/94861320-56a60300-0405-11eb-90fd-f229eef53ab5.png">

**Comment by brentvatne** [comment]
this is the same reason as the app size is larger than it would be if only the modules you used were included. see https://expo.fyi/managed-app-size for more information on that topic
