### ISSUE TITLE
Splash screen image in Expo client on iOS flickers

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#10510]
### Summary of Issue 

**This does not happen in standalone apps**!

While loading a project with a splash screen image on Expo client for iOS, the image will flicker. This happens right when "Downloading JavaScript bundle" hits 100%.

![flicker](https://user-images.githubusercontent.com/90494/94879743-f4093300-0415-11eb-9091-e4165ab8f381.gif)

### Reproducible Demo

Run the tabs template project.

**Comment by brentvatne** [comment]
this happens because:

- we have code in EXAppViewController / EXManagedAppSplashScreenViewProvider that first displays the splash based off of the cached manifest (if available) and then updates it once the manifest finishes loading.
- in the code responsible for updating the splash screen in `configureSplashScreenView` we always remove the `splashImageView` even if the image being used is the same

**Comment by RodolfoGS** [comment]
Thanks @brentvatne for the fix, I experimented the same issue in Bare workflow, this also fix that flow?

**Comment by brentvatne** [comment]
@RodolfoGS - the fix merged above is only for managed apps. can you create a new issue for bare expo-splash-screen flicker? thanks!

**Comment by RodolfoGS** [comment]
@brentvatne Done https://github.com/expo/expo/issues/10537

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/10464#issuecomment-703178030
