### ISSUE TITLE
[expo-auth-session] redirect URI doesn't work on iOS (spotify api)

### ISSUE THREAD

**Issue by Pixelatex** [expo/expo#10514]
### Summary of Issue 
I'm using expo-auth-session to connect to spotify, this works in the expo app but when I release to testflight, the redirect uri is not valid (illegal uri).

### Reproducible Demo

I followed the spotify demo on the expo documentation site.
The app names 'com.company.app' etc are correctly added in the developer panel of spotify.

My auth code looks like this:
```
const [request, response, promptAsync] = useAuthRequest(
    {
      clientId: "{id}",
      scopes: [
        "user-read-email",
        "user-read-playback-state",
        "user-modify-playback-state",
        "playlist-modify-public",
      ],
      // In order to follow the "Authorization Code Flow" to fetch token after authorizationEndpoint
      // this must be set to false
      usePKCE: false,
      // For usage in managed apps using the proxy
      redirectUri: makeRedirectUri({
        // For usage in bare and standalone
        native: Platform.select({
          android: `be.{company}.{app}//redirect`,
          ios: `be.{company}.{app}//redirect`,
        }),
      }),
    },
    discovery
  );

```
 
### Steps to Reproduce
use the code above, connect to spotify.

### Expected Behavior vs Actual Behavior

In the expo app it will work, however, once you deploy to testflight or wherever. It will crash and return 'illegal url'

**Comment by SleeplessByte** [comment]
We have this working in production. Only real difference is that we use:

```js
const SCHEME = Constants.manifest.scheme;
const useProxy = Constants.appOwnership === 'expo' && Platform.OS !== 'web';

...

     redirectUri: makeRedirectUri({
        // For usage in bare and standalone
        native: `${SCHEME}://redirect`,
        useProxy,
      }),
```

**Comment by Pixelatex** [comment]
> We have this working in production. Only real difference is that we use:
> 
> ```js
> const SCHEME = Constants.manifest.scheme;
> const useProxy = Constants.appOwnership === 'expo' && Platform.OS !== 'web';
> 
> ...
> 
>      redirectUri: makeRedirectUri({
>         // For usage in bare and standalone
>         native: `${SCHEME}://redirect`,
>         useProxy,
>       }),
> ```

I tried this but I still get an invalid uri response when trying to login in :/ I have no idea how to debug this. It works in expo but not when deployed on testflight

**Comment by SleeplessByte** [comment]
What are your callback values on Spotify itself?

**Comment by Pixelatex** [comment]
@SleeplessByte 

redirect urls:

https://auth.expo.io/@username/app-name

ios bundle ids:

com.domain.appname

**Comment by SleeplessByte** [comment]
That's (one of) the issues! The redirect Uri will not use the proxy on testflight, because the Uri will be different on your standalone app 🔥

Add

```
<bundle-id>://redirect
```

**Comment by Pixelatex** [comment]
@SleeplessByte yeah tried that now, didn't fix it. Any ideas on what else could be causing the issue? Also, is there some way I can log the redirect uri being used on the standalone app?

**Comment by SleeplessByte** [comment]
Yah, you can do the makeRedirectUri call to a variable, and log that.

```javascript
const redirectUri = makeRedirectUri(...)
console.log(`[spotify] ${redirectUri}`)
```

I remember having issues with this when I was implementing. I did just check for you if it was still working, and it still is.

**Comment by Pixelatex** [comment]
> Yah, you can do the makeRedirectUri call to a variable, and log that.
> 
> ```js
> const redirectUri = makeRedirectUri(...)
> console.log(`[spotify] ${redirectUri}`)
> ```
> 
> I remember having issues with this when I was implementing. I did just check for you if it was still working, and it still is.

Hmm sure but I can’t see logs for a testflight build as far as I know :s

**Comment by SleeplessByte** [comment]
Gotta connect it up via XCode. But that's not ideal.

I would suggest printing it to a text node on the screen. Use a different release channel if you don't want your test flight build to affect others.

**Comment by Pixelatex** [comment]
> Gotta connect it up via XCode. But that's not ideal.
> 
> I would suggest printing it to a text node on the screen. Use a different release channel if you don't want your test flight build to affect others.

So yeah I did just that, got it released but trying to log it to a text node crashes it completely.

I logged this, your code :/

```
     redirectUri: makeRedirectUri({
        // For usage in bare and standalone
        native: `${SCHEME}://redirect`,
        useProxy,
      }),
```

**Comment by SleeplessByte** [comment]
If you're logging that as an object, you need to JSON.stringify it before rendering it as a text node, because text nodes don't understand objects unfortunately.

**Comment by Pixelatex** [comment]
> If you're logging that as an object, you need to JSON.stringify it before rendering it as a text node, because text nodes don't understand objects unfortunately.

Wasn't the issue really, something unrelated broke :) 

so what I get when I log it in production: myapp://redirect

that doesn't seem right .. hmm any ideas?

**Comment by brentvatne** [comment]
here is an example of an app that uses spotify for authentication with expo-auth-session and works as expected: https://github.com/brentvatne/hour-power/tree/master/app

**Comment by Pixelatex** [comment]
so probably my issue was that I used com.domain.name//redirect instead of name//redirect. Should work now

**Comment by SleeplessByte** [comment]
Happy you got it working!

**Comment by jedvalmar** [comment]
I know this is old news, but I'm wondering why does one needs to set the  `usePKCE` flag to false in order for the app to work with authorization code grant?

**Comment by SleeplessByte** [comment]
Because Spotify doesn't support PCKE.

**Comment by Abiramisaro** [comment]
> We have this working in production. Only real difference is that we use:
> 
> ```js
> const SCHEME = Constants.manifest.scheme;
> const useProxy = Constants.appOwnership === 'expo' && Platform.OS !== 'web';
> 
> ...
> 
>      redirectUri: makeRedirectUri({
>         // For usage in bare and standalone
>         native: `${SCHEME}://redirect`,
>         useProxy,
>       }),
> ```

here Constants means what it means ?
