### ISSUE TITLE
[expo-video] Silent video ducks Android

### ISSUE THREAD

**Issue by reinhardholl** [expo/expo#10518]
We have a requirement where we need to play silent videos that don't duck other apps on Android. We have an mp4 video that has no audio tracks but it looks like `expo-video` is still requesting Audio focus and ducking background music. 

Is there any way we can disable `expo-video` from behaving in this way?

Thanks!

**Comment by henrikland** [comment]
Setting the `isMuted` prop on the `Video` works for me.

**Comment by reinhardholl** [comment]
> Setting the `isMuted` prop on the `Video` works for me.

That's interesting @henrikland. We are still on `v7.0.0` as we are limited by our RN version. Maybe it's been fixed in a later version, will go through the changelogs again.

**Comment by reinhardholl** [comment]
> Setting the `isMuted` prop on the `Video` works for me.

Also, just to confirm @henrikland, `isMuted` does not cause your app to duck background music?

**Comment by henrikland** [comment]
> Also, just to confirm @henrikland, `isMuted` does not cause your app to duck background music?

Correct! Using expo-av version 8.6.0.

**Comment by reinhardholl** [comment]
Thanks @henrikland! I will spin up a test project to also confirm.

**Comment by reinhardholl** [comment]
I think I found the issue. The following example does not work like expected for me:

```
export default class App extends React.Component {
  private player: Video;
  public mountVideo = (component: Video) => {
    this.player = component;
  }

  async componentDidMount() {
    await this.player.loadAsync({
      uri: 'valid url',
    });
    await this.player.playAsync();
  }

  render() {
    return (
      <View style={styles.container}>
        <Video
          ref={this.mountVideo}
          volume={0.0}
          isMuted={true}
          shouldPlay={true}
          style={{
            height: 500,
            width: 500,
          }}
          isLooping={true}
          ></Video>
      </View>
    );
  }
}
```

As you can see, I set the `isMuted` flag on the component directly. When loading and playing a source using the video ref the background music always gets ducked, almost like its resetting the `isMuted` flag on either `loadAsync` or `playAsync`.
