### ISSUE TITLE
Can't open app on android

### ISSUE THREAD

**Issue by GregorBeatson** [expo/expo#1051]
I am trying to use Expo on Windows 10, and have not been able to consistently open my app on my phone or gentymotion. I had it working on gentymotion for about 20 minutes earlier, but now nothing is working again. The error at the moment is java.net.connectionexception. Attempting to open the app via browser gives me "connection refused". Can provide more information as necessary but at this point I don't know what is and isn't relevant.

Thanks in advance

**Comment by terribleben** [comment]
Hi, this sounds like a networking issue, either due to a poor connection or due to a firewall. Are you able to open your app's url on your computer (in a browser)? And have you tried switching from "tunnel" over to "lan" or "localhost" in XDE?

**Comment by terribleben** [comment]
Hey there, closing this for now. Let us know if you're still seeing this behavior, and try out the recommendations in my previous post if you haven't had a chance yet. Hope that helps!
