### ISSUE TITLE
In Expo Managed project the app Crashes while using MediaLibrary.getAssetsAsync(options)

### ISSUE THREAD

**Issue by kartikeyvaish** [expo/expo#10529]
Every time I call this function, the app crashes without logging any error
It Crashes on Android..Not Tested in iOS
Using a Expo Managed Project
Any Solution for this..

**Comment by byCedric** [comment]
Hi @kartikeyvaish, without the information filled in from the bug template we can't really help you. Right now, I have no idea how you use the Media Library API and why it could crash on Android. If you think this is an issue with Expo, please create a new issue with the information that we need.
