### ISSUE TITLE
[docs] Bare "up and running" guide is missing react native setup

### ISSUE THREAD

**Issue by byCedric** [expo/expo#10521]
We assume that React Native (CLI) is properly installed on the developer's machine in [this guide](https://docs.expo.io/bare/hello-world/). But, if that developer mainly used the managed workflow, that's not always true. Would be good to have a warning about that and a link to https://reactnative.dev/docs/environment-setup.

In one case I know the developer:
- installed the wrong Java version
- didn't have Android 9 SDK installed, causing [this "obscure error"](https://stackoverflow.com/questions/60844245/how-solve-could-not-initialize-class-org-codehaus-groovy-reflection-reflectionc)
- had [this issue with Gradle](https://stackoverflow.com/questions/60844245/how-solve-could-not-initialize-class-org-codehaus-groovy-reflection-reflectionc)

Most of these cryptic errors would have been avoided by that link or warning I think :)

**Comment by brentvatne** [comment]
@byCedric - good call!

**Comment by byCedric** [comment]
Credits should go to @gregfenton 😄
