### ISSUE TITLE
Cannot find module 'slash'

### ISSUE THREAD

**Issue by makhataibar** [expo/expo#1052]
![image](https://user-images.githubusercontent.com/27006656/33520895-a8c48f9a-d7ed-11e7-80b2-73904d5b2c71.png)

**Comment by brentvatne** [comment]
@fxfactorial ^

**Comment by brentvatne** [comment]
hi there! can you install `exp@46.0.6` and try this again? hopefully it should resolve the problem

**Comment by makhataibar** [comment]
@brentvatne thanks, this work for me!
