### ISSUE TITLE
Expo doesn't see node_modules outside the app directory. nodeModulesPath option in app.json doesn't work

### ISSUE THREAD

**Issue by vlad-dewitt** [expo/expo#10539]
### Summary of Issue

I have a simple structure: two expo apps and the shared folder, where there are reusable components and assets.
I'm trying to make the project have one top-level node_modules folder (this works in any web project and I've also tested it with regular React Native apps). But when I start the app using expo start I get the errors:
```
Error: Can't find react-native in package.json dependencies
Error: node_modules directory is missing. Please run `npm install` in your project directory.
Couldn't start project. Please fix the errors and restart the project.
```
I had a hard time finding the nodeModulesPath option for app.json but it didn't help. If I specify an external directory then I get error:
`Unable to resolve "@babel/runtime/helpers/interopRequireDefault" from "index.ts"`

### Steps to reproduce

1. Create the project root with common package.json where there are all expo deps.
2. Create shared folder where there are common components for TWO expo apps.
3. Init app1 using expo init in the project root.
4. Init app2 using expo init in the project root.
5. Move all dependencies from package.json files of both two apps (app1 and app2) to COMMON package.json which in the project root.
6. Run yarn install in the project root, NOT in the app1 and app2
7. Run app1 or app2 - you will get errors I described above.

### Expected Behavior vs Actual Behavior

I should only be able to use one top-level node_modules dir

**Comment by brentvatne** [comment]
replied here: https://github.com/expo/expo/issues/10538#issuecomment-703189809
