### ISSUE TITLE
[expo-splash-screen] Splash screen image in Bare workflow on iOS flickers

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#10537]
### Summary of Issue 

While loading a project with a splash screen image on Bare workflow for iOS, the image will flicker. This happens right when "Downloading JavaScript bundle" hits 100%.

Seems that is this same issue https://github.com/expo/expo/issues/10510 but in a Bare workflow.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.3
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: bare
```

### Steps to Reproduce

1. Create a Bare project
2. Build release and run on your device
3. Push an update via `expo-updates`
4. Restart the app, when the app change the bundle for the new download from `expo-updated` a flicker appears.

### Expected Behavior vs Actual Behavior

**Expected Behavior**: No flicker on splash screen
**Actual Behavior**: Flicker

**Comment by bbarthec** [comment]
Hello @RodolfoGS 👋 
I'm trying to reproduce the issue you're reporting, but with no luck so far 😓

#### I've followed your steps:
> 1. Create a Bare project - `expo init` (`expo-template-bare-minimal`) with the App.ts as follows:
```tsx
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Is it working as expected? 🤔</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
> 2. Build release and run on your device
>    - I've changed the `Build Configuration` to `Release` in Xcode and build the app (I've run the app both on Simulator & Device)
>     - App starts and everything is working at this point.
>     - Restarting the app shows no issues.
> 3. Push an update via `expo-updates`
>    - I've applied minor change in the `App.tsx` (I've added another `<Text />`) to see if the update is applied.
> 4. Start the app: app shows the the original content (no update is applied at this point). No issues visible.
>     - Restart the app: app shows the updated content (the update was fetched during the previous launch). No issues visible at this point.

- **Ad. 4.** I've started to wonder how to achieve what you're describing as `when the app change the bundle for the new download from expo-updated a flicker appears.` 🤔 I've applied the following change:
    - I had to configure `expo-updates` according to docs describing [`EXUpdatesLaunchWaitMs`](https://github.com/expo/expo/tree/master/packages/expo-updates#configuration) (updated this key in the `Expo.plist` file with the value of `10 000`)
    - Eventually I've achieved the following scenario:
        - the app launches, downloads the new bundle & immediately replaces the old one with the new one

#### Time for repeating the steps:
1. ✅ 
2. ✅
    - I've applied this change described above
3. ✅ 
4. ✅
    - App launched, fetched the update (and immediately applied it) and hid the SplashScreen with no flicker.
    - The app presented the new (published via `expo publish`) content.

@RodolfoGS, as you can see I cannot reproduce the issue you're reporting 🤔 Do you mind providing more detailed steps on how to reproduce the error or share some MVP repository presenting the erroneous scenario?

**Comment by RodolfoGS** [comment]
Sure, I'll create a demo

**Comment by RodolfoGS** [comment]
I've trying for hours but I can't reproduce the flicker in a new fresh project. I have the flicker in my production app for any reason that I don't know, I have the latest versions of `expo` and `expo-splash-screen`. Same storyboard, same image in the splash... I don't know what happen but seems that is a bug with my app.

In the meanwhile I'll close this issue, if I found a way to reproduce I'll create another issue with a demo
