### ISSUE TITLE
[Notifications] Interactive expo-notifications (local) seems crash standalone Android app

### ISSUE THREAD

**Issue by twwspes** [expo/expo#10532]
### output of `expo diagnostics` 
  Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29
        Build Tools: 25.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    npmGlobalPackages:
      expo-cli: 3.27.12
    Expo Workflow: managed

The platform(s) targeting:
Android and iOS, but only Android standalone app crashes. iOS seems working just fine on expo app and on standalone app.  The testing devices I use are two low-end Honor phones.

### Reproducible Demo

https://snack.expo.io/@takwwong5/notificationtesting

You may init a new expo, copy the code to it, npm install all packages and run it.  You will find that all interactive notifications should run fine on both android and ios, but if you build it and run it on standalone android app. it crashes when a local notification is about to be triggered.  I used android studio to look for a log.  It just said Notification something can not be cast to something (I cannot remember now sorry).

**Comment by twwspes** [comment]
Referring to  #10314 as per request by cruzach, https://github.com/expo/expo/issues/10314

**Comment by cruzach** [comment]
hey @twwspes , this is fixed on our builders now, just run `expo build:android` again and you should be all set 👍
