### ISSUE TITLE
Expo bare failed run on Xcode

### ISSUE THREAD

**Issue by king804** [expo/expo#10533]
after eject the expo, then run simulator via xcode show the error:

ld: warning: directory not found for option '-L-L/Users/king/Library/Developer/Xcode/DerivedData/friendie-fzifnhctcisdcpaowfnatupiyxon/Build/Products/Debug-iphonesimulator/AppAuth'
ld: library not found for -lAppAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by brentvatne** [comment]
please create a new issue that follows the issue template :)

also, you may want try to clean your build and build again.
