### ISSUE TITLE
Cannot be used in monorepo conditions. nodeModulesPath doesn't work.

### ISSUE THREAD

**Issue by vlad-dewitt** [expo/expo#10538]
### Summary of Issue

I have a simple structure: two expo apps and the `shared` folder, where there are reusable components and assets.
I'm trying to make the project have one top-level `node_modules` folder (this works in any web project and I've also tested it with regular React Native apps). But when I start the app using `expo start` I get the errors

**Comment by brentvatne** [comment]
https://github.com/expo/expo is a monorepo with a bunch of react-native apps in it.

we would need more specifics about exactly what is going wrong and how to reproduce. when you have time to fully fill out the issue template please create a new issue.

**Comment by vlad-dewitt** [comment]
@brentvatne, accidentally confirmed this without completing the issue description. I have updated this now, please take a look

**Comment by brentvatne** [comment]
still missing a reproducible example :)

**Comment by vlad-dewitt** [comment]
@brentvatne, I think this is the simplest description. Now I have added step-by-step instructions

**Comment by brentvatne** [comment]
it sounds like you're not using anything like yarn workspaces. you might find this to be helpful: https://github.com/expo/examples/pull/204

and potentially this: https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces

**Comment by vlad-dewitt** [comment]
@brentvatne, thanks, I will try this

**Comment by saurshaz** [comment]
I did not find setting up a monorepo with expo straightforward. However, with help from multiple generous contributors have been able to setup a template here `https://github.com/saurshaz/counter-monorepo` . Will try to contribute to simplify the process OOTB with some code.
