### ISSUE TITLE
[Unhandled promise rejection: Error: Location 'http://localhost:5000/api' isn't readable.]

### ISSUE THREAD

**Issue by TomLynx3** [expo/expo#10530]
### Summary of Issue 
FileSystem.uploadAsync can't read remote url

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Android EXPO

### Steps to Reproduce
FileSystem.uploadAsync can't read remote url

**Comment by brentvatne** [comment]
you probably can't reach localhost from your phone, unless you use `adb reverse` to do it, eg: `adb reverse tcp:5000 tcp:5000`. unless you use `adb reverse` for a given port, localhost on your phone maps to.. your phone.. not your computer. use a network ip instead.
