### ISSUE TITLE
InAppPurchases getProductsAsync always empty

### ISSUE THREAD

**Issue by king804** [expo/expo#10534]
1. already eject expo
2. already login sandbox account
3. already add capability - in app purchase
4. itunes connect - all item is ready to submit
5. itunes connect - all agreement is done

issue:   expo-in-app-purchases getProductsAsync when expo start always empty

**Comment by byCedric** [comment]
Hi @king804, please use the issue template and fill the requested information. Without this, it's really hard to pinpoint the issue for you. Right now, I have no idea what you want to achieve and how you use the API. I think there are two methods in our API which are often confused, so I'm going to mention them here (but again, I have no idea if this is relevant for you)

- [`InAppPurchases.getProductsAsync`](https://docs.expo.io/versions/v39.0.0/sdk/in-app-purchases/#inapppurchasesgetproductsasyncitemlist-string) is a method to fetch a list of _available in-app purchases **to buy**_.
- [`InAppPurchases.getPurchaseHistoryAsync`](https://docs.expo.io/versions/v39.0.0/sdk/in-app-purchases/#inapppurchasesgetpurchasehistoryasyncrefresh-boolean) is a method to fetch a list of _**already bought** in-app purchases of the user_.

Hope this helps! In case it doesn't, please create a new issue with all information required in our bug template.
