### ISSUE TITLE
expo upgrade stuck at v38

### ISSUE THREAD

**Issue by MichaelMcNeil** [expo/expo#10536]
I wanted to upgrade from 38 to 39.  Running npm i -g expo-cli takes me to 3.27.13.   Running expo upgrade tells me I'm at the latest version v38.    If I run npm i expo@39.0.0 it installs.  If I follow that up with expo upgrade, I'm told that I'm currently running v39, would I like to upgrade to the latest, v38. 

Any ideas?

**Comment by 9710willy** [comment]
Hi, make sure you have the latest version of expo-cli; then try running expo-upgrade after you downgrade to expo sdk 38. Hope that helps!

**Comment by MichaelMcNeil** [comment]
@9710willy Hi there. I just uninstalled expo-cli and reinstalled.  Running expo upgrade in my project is still showing sdk38 as the most recent.

Using node 14.6.0.

Expo is at v3.27.13.

**Comment by MichaelMcNeil** [comment]
After running expo diagnostics...

Expo CLI 3.27.13 environment info:
    System:
      OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
      npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
    npmPackages:
      expo: ^38.0.0 => 38.0.10
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed

**Comment by brentvatne** [comment]
it sounds like your machine has an outdated version of our versions config. are you able to access https://expo.io in your browser? what about https://expo.io/--/versions?

you can clear your cached values by deleting the `~/.expo/cache` on macos/linux

**Comment by MichaelMcNeil** [comment]
@brentvatne Interesting.  The contents of my .expo folder are 

PATH  ngrok.yml  state.json  template-cache  xde-recent-exps.json

Should I remove the template-cache folder?

**Comment by brentvatne** [comment]
are you able to access https://expo.io in your browser? what about https://expo.io/--/versions?

**Comment by MichaelMcNeil** [comment]
@brentvatne   hi there.  this is running in wsl2.  

wget https://expo.io/--/versions
--2020-10-01 08:43:19--  https://expo.io/--/versions
Resolving expo.io (expo.io)... 104.197.216.164
Connecting to expo.io (expo.io)|104.197.216.164|:443... connected.
ERROR: cannot verify expo.io's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate not yet valid.
To connect to expo.io insecurely, use `--no-check-certificate'.

------------------------------------------------

So running with the flag.

wget https://expo.io/--/versions --no-check-certificate
--2020-10-01 08:43:38--  https://expo.io/--/versions
Resolving expo.io (expo.io)... 104.197.216.164
Connecting to expo.io (expo.io)|104.197.216.164|:443... connected.
WARNING: cannot verify expo.io's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate not yet valid.
HTTP request sent, awaiting response... 302 Found
Location: /--/api/v2/versions [following]
--2020-10-01 08:43:38--  https://expo.io/--/api/v2/versions
Reusing existing connection to expo.io:443.
HTTP request sent, awaiting response... 200 OK
Length: 19594 (19K) [application/json]
Saving to: ‘versions’

versions                      100%[===============================================>]  19.13K  --.-KB/s    in 0.06s

2020-10-01 08:43:39 (298 KB/s) - ‘versions’ saved [19594/19594]


@brentvatne  Anything I should look for in the response?  I can share all or part of the versions object returned.

**Comment by brentvatne** [comment]
my bad, we store those in a different location on linux: https://github.com/expo/expo-cli/blob/cc4613dc4d9aeedcfb3ea69d9293fb66142c7148/packages/xdl/src/tools/FsCache.ts#L123-L135

for you it should be: `~/.cache/expo`

<hr />

that said, i don't know why you would be encountering this issue on your machine. the cert is indeed valid, see this screenshot from chrome:

![Screen Shot 2020-10-03 at 2 37 46 PM](https://user-images.githubusercontent.com/90494/95002193-2639a280-0586-11eb-986a-0fd8d53d78e6.png)

**Comment by MichaelMcNeil** [comment]
@brentvatne THANK YOU.  Removing the cache did the trick.

**Comment by brentvatne** [comment]
i think that's a decent temporary solution but ultimately it would be good to figure out why the ssl cert is deemed invalid on your machine

**Comment by MichaelMcNeil** [comment]
@brentvatne I couldn't find any reason why the cert was showing invalid.  BUT, punching my keyboard and then rebooting the vm seemed to fix it.  

Again, thank you so much.

**Comment by brentvatne** [comment]
great, np!
