### ISSUE TITLE
Expo Calendar reccurenceRule.occurence not working SDK 37

### ISSUE THREAD

**Issue by lacsinagramar** [expo/expo#10547]
I am using SDK37 Calendar.createEventAsync() and passing this as the event
```
 title: description,
 notes: 'Meditation App Reminder',
 startDate,
 endDate,
 allDay: true,
 alarms: [
     {
         relativeOffset: -30,
         method: Calendar.AlarmMethod.ALERT
     }
 ],
recurrenceRule: {
    frequency: Calendar.Frequency.WEEKLY,
    occurence: 4,
    interval: 1
}
```
It only creates one event. I am expecting it to occur weekly

**Comment by AdamJNavarro** [comment]
Hey @lacsinagramar,

Is this occurring on Android, iOS or both platforms? Also, could you please provide a working, reproducible example we can test on our end?

Cheers,
Adam

**Comment by lacsinagramar** [comment]
It's occurring on both Android and iOS.

I made an expo snack for it so you can test.

Here's the link: https://snack.expo.io/@devoffshorly/expo-calendar-bug

**Comment by lacsinagramar** [comment]
@AdamJNavarro any updates with this?

**Comment by lacsinagramar** [comment]
I updated to Expo SDK 39, but it doesn't fix it. Any updates with this? @AdamJNavarro
