### ISSUE TITLE
expo-contacts Sorting by FirstName or LastName not working for IOS

### ISSUE THREAD

**Issue by kaushikdas0** [expo/expo#10542]
### Summary of Issue 
Using Contacts.SortTypes.FirstName dont work on IOS simulator or Physical Device. 

### Environment 
**(Problem with Managed and Bare, both.)**

 ```
 Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.9 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.27.12
    Expo Workflow: bare
```

### Reproducible Demo
![image](https://user-images.githubusercontent.com/13030179/95015110-c9b9ae80-067d-11eb-8973-dcfcb6c3b36f.png)

 
### Steps to Reproduce
```
 useEffect(() => {
    const sortType = Contacts.SortTypes.FirstName;
    (async () => {
      const { status } = await Contacts.requestPermissionsAsync();
      if (status === 'granted') {
        const { data } = await Contacts.getContactsAsync({
          fields: [Contacts.Fields.PhoneNumbers, Contacts.Fields.Emails],
          sort: sortType
        });

        if (data.length > 0) {
          setContacts(data)
        }
      }
    })();
  }, []);
```

### Expected Behavior vs Actual Behavior
Ideally am expecting the Contact List to be Sorted based on First Name, but they are not sorted.

**Comment by kaushikdas0** [comment]
Anyone can help please?

**Comment by cruzach** [comment]
Testing this on SDK 40 on iOS 14, the contacts are sorted appropriately. If you're still seeing this issue, please share a Snack that reproduces it

**Comment by cruzach** [comment]
Closing for now, if you see this issue please share a repro

**Comment by moneszarrugh** [comment]
I have the same issue on SDK 49 and "expo-contacts": "~12.2.0"

**Comment by patrickcmrg** [comment]
Same problem using "expo": "^49.0.0",
  and "expo-contacts": "~12.2.0".

It works normally on Android, but not on iOS.
