### ISSUE TITLE
SDK 39.0.3: Invariant Violation: Native module cannot be null (iOS only)

### ISSUE THREAD

**Issue by khalidalmannai** [expo/expo#10541]
SDK 39.0.3: Invariant Violation: Native module cannot be null (iOS only)

The app is running fine on android device
Is it my code fault? or  a bug?

Expo CLI 3.27.13
Expo SDK 39.0.3
Expo client 2.17.4 on iPhone
Managed workflow

Upgrading steps:
upgrade to expo@39.0.3 in your package.json
https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz. 
remove your yarn.lock / package-lock.json
remove node_modules
run yarn or npm install
start the app again

Error and warning on mobile
![86801052-4edff800-c07c-11ea-8517-45b187ed5cd0](https://user-images.githubusercontent.com/32058764/95013060-4c267c00-0646-11eb-860a-fe5bc2f01bdc.png)
![86801117-5d2e1400-c07c-11ea-9d15-48ab6b058855](https://user-images.githubusercontent.com/32058764/95013182-5006ce00-0647-11eb-8edd-a6bfe4926811.png)

Error and warning on Metro

Invariant Violation: Native module cannot be null.

Stack trace:
  node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
  node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
  node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
  node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
  node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
  node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
  node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
  node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
  node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
  node_modules\regenerator-runtime\runtime.js:293:29 in invoke
  node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
  node_modules\regenerator-runtime\runtime.js:154:27 in invoke
  node_modules\regenerator-runtime\runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
  node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
  node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
  node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
  node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
  node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
  [native code]:null in flushedQueue
  [native code]:null in invokeCallbackAndReturnFlushedQueue
WARNING
13:15
Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.

Stack trace:
  node_modules\react-native\Libraries\LogBox\LogBox.js:117:10 in registerWarning
  node_modules\react-native\Libraries\LogBox\LogBox.js:63:8 in warnImpl
  node_modules\react-native\Libraries\LogBox\LogBox.js:36:4 in console.warn
  node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
  node_modules\react-native\Libraries\ReactNative\AppRegistry.js:200:6 in runApplication
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
  [native code]:null in callFunctionReturnFlushedQueue

**Comment by RodolfoGS** [comment]
If you are in Bare workflow maybe you forgot make `npx pod-install`

**Comment by khalidalmannai** [comment]
Thank you, but the app on Managed workflow.

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by hassanQureshi22** [comment]
I am also getting this error in expo  @khalidalmannai did you find any solution please share

**Comment by brentvatne** [comment]
@hassanQureshi22 - hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
