### ISSUE TITLE
Error on Web Build -- Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage' 

### ISSUE THREAD

**Issue by m4ttheweric** [expo/expo#10561]
### Summary of Issue

This issue is occurring anytime I attempt to run the web build since upgrading to v39. Never saw this prior to upgrading.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.7 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 3.27.12
    Expo Workflow: managed

### Reproducible Demo

The only requirement for repro is to import `import { AsyncStorage } from 'react-native'` and then run a build on web.

### Expected Behavior vs Actual Behavior

I imagine the expectation is that there's some asset available for import. But I am not totally sure.

**Comment by m4ttheweric** [comment]
Ok I actually discovered the paper trail here that `AsyncStorage` has been deprecated for some time. If anyone else encounters this, the solution is to migrate to the community packages at `react-native-community/async-storage`.

I will post any follow up here if necessary.

**Comment by brentvatne** [comment]
yeah - `AsyncStorage `was removed from the latest version of react-native-web. `expo install @react-native-community/async-storage` and import from there should work fine
