### ISSUE TITLE
Camera.recordAsync() crashes on Android in the Expo app

### ISSUE THREAD

**Issue by matejukmar** [expo/expo#1056]
When trying to start recording on Moto E2 with:

`this.camera.recordAsync().then(video => { ... }`

the app crashes (see attached screenshot).

I'm using expo sdkVersion 22.0.0

Camera is set up like this:
```
<Camera 
	style={{ 
		flex: 1,
		aspectRatio: 3/4,
	}} 
	type={this.state.cameraOrientation}
	ref={camera => this.camera = camera}
	onCameraReady={event => {
		this.setState({cameraReady: true})
	}}
	ratio='4:3'
>
...
```

And I do ask for permissions in componentWillMount, and both callbacks are granted:
```
Permissions.askAsync(Permissions.CAMERA).then( ({status}) => {
	console.log('got camera permission:', status)
	this.setState({ hasCameraPermission: status === 'granted' })
	Permissions.askAsync(Permissions.AUDIO_RECORDING).then( ({status}) => {
		console.log('got audio recording perm:', status)
		this.setState({ hasMicPermission: status === 'granted' })			
	})	
})
```
![screenshot_20171204-062647](https://user-images.githubusercontent.com/284002/33532731-e4c6fe74-d8e7-11e7-8483-7701db7acf73.png)

**Comment by fxfactorial** [comment]
Your current code works correctly on other devices? if so, Which ones?

**Comment by matejukmar** [comment]
I don't have other Android devices at hand right now.

**Comment by matejukmar** [comment]
I just found out that this crash happens only on front camera not on back.

**Comment by aalices** [comment]
Can you provide full code for the issue? This would be helpful to reproduce
