### ISSUE TITLE
expo-server-sdk-node is missing categoryId on ExpoPushMessage Type

### ISSUE THREAD

**Issue by Alain00** [expo/expo#10566]
I dont know if the property is used internally, but it is't exposed in the types
```js 
expo.sendPushNotificationsAsync([
        {
            to: token,
            title: title,
            body: body,
            sound: 'default',
            categoryId: 'category' //this property is missing
        }
    ])
}
```

**Comment by sjchmiela** [comment]
Yes it is! Unfortunately we still consider it an experimental feature. 😕 If you want to define a category to a notification try defining a `_category` property, like we do here:

https://github.com/expo/expo/blob/9155fd2f34daa213005f2c5001a5fea73216c1e7/apps/native-component-list/src/api/registerForPushNotificationsAsync.ts#L32

🙂
