### ISSUE TITLE
Admob : Confirm that rewarded video had been see by user

### ISSUE THREAD

**Issue by ssmeyaaa** [expo/expo#10567]
Hi,

I integrated Admob video rewarded on react-native project.
I don't find how can I check if the user saw the video or close before end.

Who could assist ?

Thanks

**Comment by byCedric** [comment]
HI @ssmeyaaa. Please use the [forums](https://forums.expo.io/) or [community slack](https://slack.expo.io/) for questions, we use Github for issues only. You can find more info on [video reward events over here](https://github.com/sbugert/react-native-admob/tree/1.x#events-1). You should be able to use those events to detect if a video is fully seen.

Hope it helps.
