### ISSUE TITLE
Bundle download progress banner blocking touch input in Expo iOS app

### ISSUE THREAD

**Issue by pugovkin** [expo/expo#10579]
### Summary of Issue  
Bundle download progress banner doesn't go away and blocks the touch input after the download is completed

### Environment - 
iOS Expo app via emulator and native on iPhone 11Pro

### Steps to Reproduce
When running a bundle via metro bundler in Expo CLI ("expo start -i") the expo iOS app launches the cached version of the bundle before the bundle has completed the download. If you tap "try again" in the Expo app, it'll start the download of the bundle, but the download progress banner stays on the screen after the download is successfully completed. The app then shows an alert prompting the user to either use the cached version or reload the bundle - the alert is not tappable because it's blocked by the bundle download progress banner in the foreground. It also blocks touch input even for the modal popping up on device shaking.

### Expected Behavior vs Actual Behavior

Bundle download progress banner going away after the bundle download is completed.

**Comment by brentvatne** [comment]
can you record a video of following the reproduction steps? i've tried following it but it does not reproduce.

also, are you using the latest version of expo client? you should see 2.17.4 here
<img width="487" alt="Screen Shot 2020-10-05 at 11 19 06 AM" src="https://user-images.githubusercontent.com/90494/95245688-4eb0df00-07c8-11eb-9e42-27a1421e0395.png">

**Comment by pugovkin** [comment]
Attachment available until Nov 5, 2020
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAQu5qa0yRwQU6k0nVNgfoSCcPuNkAdX8Cw_1X1cjxh4YWpvL00oXvtCI%2F%24%7Bf%7D%3Fo%3DAuaAn7MfMtWT2bWKpdCAUeyO9KAkXVxlN11TXx3M0ld6%26v%3D1%26x%3D3%26a%3DCAoguLijI9hOkYHGYYHm5AUe4fKesZ7J-fN73nWi0Od7uUwSdxCW1_L5zy4YluftzdkuIgEAKggByAD_QFv9GlIEnD7jZFoEF77QiGomEhHwF26w3hZ4o960KGExiHwez_XSx6mC6-dKvnpge-L25fLF3w1yJopoLi81XqVzw2agFHTHd6mvC0LIi_j6WHBxgA-7zrXbxvcxvder%26e%3D1604602000%26fl%3D%26r%3DAF0129FF-A055-46AB-B371-4AEBD333EF77-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D54E12AA9-387F-45C5-AD43-0B591A30921E%26p%3D21%26s%3DVbBOmPdcHc0Ryw12vswUuYS_1-A&uk=i4ADyMnKnPBusouQc-FZmg&f=bug.mov&sz=30809647>bug.mov
30.8 MB

**Comment by pugovkin** [comment]
These buttons don’t tap. Also, if you shake the device and prompt the Expo menu it wouldn’t tap either. My assumption is the bundle download banner is sitting in the foreground and blocking the touch input.

**Comment by pugovkin** [comment]
Were you able to reproduce it?

**Comment by brentvatne** [comment]
from my previous comment:

> also, are you using the latest version of expo client? you should see 2.17.4 here
<img width="487" alt="Screen Shot 2020-10-05 at 11 19 06 AM" src="https://user-images.githubusercontent.com/90494/95245688-4eb0df00-07c8-11eb-9e42-27a1421e0395.png">

**Comment by pugovkin** [comment]
Yes

**Comment by brentvatne** [comment]
please verify that with a screenshot. @esamelson attempted to fix the issue you're facing in our most recent release on saturday and i can't reproduce it

**Comment by pugovkin** [comment]
OK, this was the issue with the sdk version requested in app.json. My json requested sdk v34.0.

**Comment by pugovkin** [comment]
I updated json to the latest version, but the touch input still doesn’t work when the app is loaded or if I prompt the shake debug menu.

**Comment by djamesp1** [comment]
I am having this same issue.  It happens about 50% of the time, so I end up reloading until it goes away.  Client version 2.18.4.1010552

**Comment by brentvatne** [comment]
we've fixed this in the latest expo go for sdk 41. you can try the beta release as described in https://blog.expo.io/expo-sdk-41-beta-is-now-available-958edcd78991 :) it'll work for sdk 38, 39, 40, 41 projects.

testflight open beta link: https://testflight.apple.com/join/GZJxxfUU
or run this outside of an expo project to install to simulator: `EXPO_BETA=1 expo client:install:ios`

**Comment by pugovkin** [comment]
Thx!
