### ISSUE TITLE
[ios][camera] Camera.recordAsync flickers with black frames before recording starts on iOS.

### ISSUE THREAD

**Issue by matejukmar** [expo/expo#1057]
Camera's video preview flickers to black for a quarter of a second before recording starts. Tested on iPhone 6 and iOS 11, with expo app and sdkVersion 22.0.0.

**Comment by fxfactorial** [comment]
Howdy, can you produce a self contained code sample for this

**Comment by matejukmar** [comment]
I can prepare, although I'm not sure what do you mean by 'self contained code sample' - do you mean react component without other dependencies?

**Comment by matejukmar** [comment]
Flicker occurs only first time recording starts (if I stop and press record again flicker does not repeat). It seems as camera tries to adjust white balance and focus at that moment and it goes black for a moment. I tried back and front camera and I get flicker in both.

**Comment by aalices** [comment]
I'm afraid there's not much we can do about this as recording requires changing the mode camera is running in. So it needs some configuration before it starts recording - that's why you see some flickers. I'll try to enhance it as much as it's possible. Maybe we should consider having "modes" (recording/picture) just like native camera apps do.

**Comment by matejukmar** [comment]
I did several native iOS 'cameras', but I never got this problem. I think its definitely possible to fix this on iOS. Not sure about Android, there we did experience these kind of flickers.

**Comment by RealDeanZhao** [comment]
+1

**Comment by watadarkstar** [comment]
Hi @aalices did this ever get fixed? Any workarounds or progress on this issue?

**Comment by watadarkstar** [comment]
@aalices I'd like to contribute to fixing this issue. Can you guide me to the source code to the Expo camera and any specific spots in the code that you think might be helpful? Even if I can just fork this project and add properties that have "modes" (recording/picture) just like native camera apps do - this will help my team a lot. I'm thinking a prop is all we need to set the mode before the camera launches so people don't get this flicker when a recording happens.

**Comment by aalices** [comment]
@watadarkstar contacting you on Expo Slack :)

**Comment by ilyausorov** [comment]
@aalices Hope some progress is made soon :)

**Comment by flippinjoe** [comment]
So I had an issue with this, but it turns out it had to do with my rendering process.  Essentially I was forcing a re-render which caused the camera to unmount and remount whenever I started recording.  Once I updated to not re-render at the point of recording there was no more black

**Comment by watadarkstar** [comment]
What version of Expo SDK are you on @flippinjoe ?

**Comment by flippinjoe** [comment]
Latest

**Comment by kandarpdave** [comment]
Hello, I tested this on iPhone 6 Plus and iPhone 8, both running iOS 11, sdk version 28. The flickering issue still exists, and this flicker is captured in the resulting video as well in form of transparency. If you load a Video component with the uri of the recorded file, and have the video loop - you'll notice that the very first few frames of the video are be transparent, caused by the flicker itself.

Tested on iPhone 8, iOS 11 with sdk version 23 as well - it also has the black flickering issue, but the recorded part has around 30-40% transparency recorded.

Thanks for team's work on this!

**Comment by kandarpdave** [comment]
Hi Ben (@terribleben), I haven't updated to sdk v29, but I did check the blog post for v29 upgrade, and seems like Camera didn't make the cut. Please let me know if there's any update and/or workaround the black flickering issue at the start of recording. Thank you!

**Comment by ilyausorov** [comment]
Still flickering, still hoping for a solution. Any ideas?

**Comment by pqminh** [comment]
i'm so tired. :( Anyone help me?

**Comment by listicos** [comment]
The only solution I found was to pass the quality of the video as a component property.

**Comment by ilyausorov** [comment]
> The only solution I found was to pass the quality of the video as a component property.

Doesn't seem to solve it for me. Still seeing the black flicker.

@aalices Any updates?

**Comment by maxschmeling** [comment]
I believe I've figured out the cause of the issue and will be submitting a PR to `react-native-camera` soon.

See https://github.com/react-native-community/react-native-camera/issues/1934#issuecomment-440963828 and https://github.com/react-native-community/react-native-camera/issues/1934#issuecomment-440966283

**Comment by ilyausorov** [comment]
@maxschmeling Looks promising! Will keep track of what you're up to on the react-native-camera side. Hope the Expo team can follow through soon after the RNC team puts a fix in.

**Comment by lingxiao** [comment]
any updates on this?

**Comment by maxschmeling** [comment]
@lingxiao I've submitted a PR to the `react-native-camera` project. Hopefully it will get merged soon. I don't know how long it takes for stuff to make it into expo.

https://github.com/react-native-community/react-native-camera/pull/1942

**Comment by trops** [comment]
@listicos setting the defaultVideoQuality property on the RNCamera component worked for me too, thanks for that!

**Comment by lingxiao** [comment]
@listicos  @trops  how did you set the quality? I did:
'''
        <Camera 
            type  = {this.props.cameraDirection}
            quality = {Camera.Constants.VideoQuality['1080p']}
            ref   = {this.setCameraRef} 
        />
'''
And the camera still blinks when it begins recording.

**Comment by trops** [comment]
Here is my code for the component:

```
<RNCamera
          ref={(cam) => {
            this.camera = cam;
          }}
          defaultVideoQuality={RNCamera.Constants.VideoQuality['1080p']}
          style={styles.preview}
          aspect={this.state.camera.aspect}
          captureTarget={this.state.camera.captureTarget}
          captureAudio
          type={this.state.camera.type}
          flashMode={this.state.camera.flashMode}
          defaultTouchToFocus
          mirrorImage={false}
        />
```

I believe setting the defaultVideoQuality fixed the blinking issue for me.

I hope this helps!

**Comment by corbt** [comment]
@trops is that code using expo's camera (ie. `import { Camera } from "expo";`), or `react-native-camera`? Most of the props you're passing in don't appear to apply to the expo camera.

**Comment by tbiinfotech** [comment]
Please help, I am using camera api and open for video recording in landscape mode, When i get path of video it is working on ios but not android. In portrait mode both works

**Comment by cruzach** [comment]
[This snack](https://snack.expo.io/@charliecruzan/examplerecordasync) can be used to repro this

**Comment by FinnFrotscher** [comment]
+1

**Comment by AaronStackBarnes** [comment]
Has anyone found a work around for this?

**Comment by erikkjernlie** [comment]
Still no work around for this one?

**Comment by rafeautie** [comment]
any updates on this issue?

**Comment by brentvatne** [comment]
there are no updates. this is an open source project and if this is high priority for you then i encourage you to investigate! :)

**Comment by http-samc** [comment]
I've investigated, unfortunately, to no avail. Anyone make any progress?

**Comment by bbarthec** [comment]
@polnikale, the solution you're describing seems quite fine, but maybe you happen to know whether `react-native-vision-camera` is also suffering from such a flickering problem? 🤔 I wonder what's the approach in that library around reconfiguring the capture session.

**Comment by bbarthec** [comment]
@polnikale, given all your findings I'm on board with this idea of pre-configuring recording options via props 👍

**Comment by jigalin** [comment]
@polnikale @bbarthec Any update on this? I see some open PRs - are we just waiting for this to merge before we can have a fix? Or has someone found a reproduceable workaround. So far for me none of the `defaultVideoSettings` , `flash off` or anything works so far.

**Comment by polnikale** [comment]
@jigalin I think it waits for the merge to be done. The delay here is on my side, I'm quite busy atm, but will get it sorted out on the weekends 😫 

The defaultVideoSettings works for me just fine. Could you share an example of what exactly you do and how it behaves?

**Comment by jigalin** [comment]
I'm using this in my 'start video record' function to record: 

`camera.recordAsync({ VideoQuality: ["720p"] });`

and this is my camera component:

`<Camera type={"front"} ref={(ref) => setCamera(ref)} quality = {Camera.Constants.VideoQuality['720p']} />`

Someone said they had better luck with 720p which is why I'm using that! But still I have the black flash at the moment :( 

Thanks @polnikale for the reply! ❤️

**Comment by polnikale** [comment]
@jigalin as far as I remember, the issue comes out when you pass any options to recordAsync. What happens if you call 
`camera.recordAsync()`?

**Comment by TalTomax** [comment]
Hello, any solutions for this problem?
still happening using expo 45.

**Comment by milkmanjr** [comment]
Still seeing this issue on iOS. Has anyone got a work around?

**Comment by Verdier** [comment]
Any update on this? Still have the problem.

**Comment by eprice122** [comment]
Seeing an issue here as well

**Comment by ww8007** [comment]
I have the same issue 
When this issue sovle?

**Comment by sudokey** [comment]
Same issue

**Comment by mattlewer** [comment]
Almost 6 years since this was posted, still no solution? :/

**Comment by mattlewer** [comment]
https://github.com/expo/expo/assets/42501880/46bd87b5-3ab4-4b7b-b87e-7ef154fdb9d3

**Comment by HemangiVekaria** [comment]
I am also having this same issue with iOS only. When start recordAsync it shows black screen for 1-2 second and then start recording.

**Comment by GoodestUsername** [comment]
Still seeing this on IOS, setting quality doesn't seem to help.
expo: 49.0.21
expo-camera: 13.4.4

**Comment by OmarSaidIbrahim** [comment]
still having issues

**Comment by veljkoilic** [comment]
Here's a workaround that helped me, and hopefully someone else.

I had the same issue, so only the first time when the camera is initialised, and when i started recording, I would get a 1 second of black frames on the beginning of the video.
As I vaguely understood this is because when you call the recordAsync() function, the settings are committed to the camera.

So what you can do is do a "pre-recording".
When you open the camera screen make a recording that lasts very short in the background, and add a maxDuration to stop it after half a second for example.

If you are using react-navigation/native you can do it inside a useFocusEffect for example:

```
  useFocusEffect(
    useCallback(() => {
      const prepareCamera = async () => {
        if (camera.current && Platform.OS === "ios") {
          try {
            await camera.current.recordAsync({
              maxDuration: 0.5,
            });
          } catch (error) {
            console.log(error)
          }
        }
      };
      prepareCamera();
    }, [camera.current])
```
This way you will get a black screen briefly when you open the camera screen, but the recordings won't contain the black frames.
You can make a loading screen until the black recording finishes.

Good luck!

**Comment by ste00martin** [comment]
I've tried the above workarounds and it hasn't worked for me yet. Very frustrating
