### ISSUE TITLE
[Unhandled promise rejection: Error: No native splash screen registered for provided activity.

### ISSUE THREAD

**Issue by pfalcetti** [expo/expo#10573]
### Summary of Issue 
Running my Andorid App i'm getting this error: 

[Unhandled promise rejection: Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android).]

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
expo diagnostics

  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 27, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    Expo Workflow: managed

 
### Steps to Reproduce
Create a new Expo project with Expo init command.
Add to App.js file the component <AppLoading /> from 'expo'.
The error will appear.

I can figure out that the error is linked to the <AppLoading /> component.

How to solve it ?

Thanks in advance.

**Comment by pfalcetti** [comment]
SOLVED: 

The problem is the Expo client app version.

Be sure u have installed Version 2.17.4. 

If you launch expo start with no expo client app installed on your device, it will install V. 2.17.2 so the error remains.

You need to update the version.

**Comment by f4z3k4s** [comment]
Thanks dude, you saved me some time. Had the same issue.

> SOLVED:
> 
> The problem is the Expo client app version.
> 
> Be sure u have installed Version 2.17.4.
> 
> If you launch expo start with no expo client app installed on your device, it will install V. 2.17.2 so the error remains.
> 
> You need to update the version.
