### ISSUE TITLE
Problem with QR Code and exp://ip using VirtualBox

### ISSUE THREAD

**Issue by gustavopiucco** [expo/expo#1058]
I am using VirtualBox in my Windows 10, and VirtualBox creates a network interface. When I run react-native with expo (https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html), the QR Code doesn't work, and I find out that it is because the QR Code is generated with the IP of my virtualbox network interface instead of the real IP of my machine. So to get around the problem I type the real IP of my machine in the expo app (exp://correct-ip:port) and everything works perfectly. But for convenience and agility would be better to solve the problem so that anyone who has VirtualBox, display the correct QR Code.

Steps to Reproduce:

1. Install Oracle VirtualBox and VirtualBox network drivers (Windows 10)

2.  Use the create-react-native-app:
$ npm i -g create-react-native-app
$ create-react-native-app my-project
$ cd my-project
$ npm start

3. Press "q" to display QR Code

4. Try to scan QR Code in Expo app

**Comment by fxfactorial** [comment]
Howdy, 

wondering, why deal with virtual box at all. Expo works fine on windows

**Comment by ElinaSchaefer77** [comment]
I'm having the same issue. How did you solve it?

**Comment by gustavopiucco** [comment]
Sorry, but I never solved this problem

2018-03-22 9:28 GMT-03:00 Elina <notifications@github.com>:

**Comment by nicknovitski** [comment]
@gustavopiucco @ElinaSchaefer77 You can [configure virtualbox to forward any ports you from the host to the vm](https://www.virtualbox.org/manual/ch06.html#natforward).  You may need to also run the server with `REACT_NATIVE_PACKAGER_HOSTNAME` set to the ip of the VM.

Please do let me know if that works.

**Comment by yavrib** [comment]
I am also having this issue, anyone solved this yet? Strange thing is, when expo runs the first time, it runs on my account, however this changes when I try it for a second time.

**Comment by navidandalibi** [comment]
I was having the same issue using Ubuntu 16.04 and the following steps worked for me. Slight modification to procedure posted by @themmes .

1. Shutdown VM

2. Go to Settings/Network under the 'Attach to:' drop down menu I changed from NAT to Bridged Adapter 

3. Start VM

This issue is similar to other server applications, I believe I had the same issue when playing around with Apache. 

@yavrib let me know if works.

**Comment by RaphaelSaban** [comment]
@themmes you got the procedure right (port forwarding), except the IP of the host. You should run:

`REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.xx npm start`

Indeed, your smartphone will connect to your PC/laptop, not to itself (localhost=127.0.0.1).

**Comment by AdrienGiboire** [comment]
@navidandalibi Thanks! It did the job for me! Thanks 👍

**Comment by w-** [comment]
for those on windows and using powershell i used the following
```
$ENV:REACT_NATIVE_PACKAGER_HOSTNAME="192.168.xxx.xxx"
expo start
```

**Comment by sjchmiela** [comment]
Thanks guys for providing the solutions to this problem! I'll close this issue tentatively, feel free to reopen it if the solutions stop working (which, I hope, will be close to never 😃). 🙂

**Comment by tomchoo46** [comment]
I followed @themmes's instruction and  updated my expo client to version 2.10.4 solved my problem.

**Comment by nonoyek** [comment]
just disable the virtualbox will do 

![image](https://user-images.githubusercontent.com/31197125/57925234-16aab280-78da-11e9-8367-6216ed975f5b.png)
