### ISSUE TITLE
Sometimes downloading progress indicator does not hide after app loads in Expo client iOS

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#10585]
### Summary of Issue 

Reported in: https://forums.expo.io/t/stuck-at-downloading-javascript-bundle-100-0-android-sdk38/43050/5

I'm not sure how to get into this state, I can't reproduce it on my machine. The developer indicated that this happens on the latest version of the iOS client with fast refresh.

One idea from https://forums.expo.io/t/stuck-at-downloading-javascript-bundle-100-0-android-sdk38/43050/12 - maybe it's related to using SDK 38 in the latest client?

**Comment by sebastienlabine** [comment]
Same ereror on SDK 39. It occurs for me when as soon as I create a warning or an error. @brentvatne

**Comment by brentvatne** [comment]
@sebastienlabine - can you provide some exact steps we can follow to reproduce this?

**Comment by sebastienlabine** [comment]
I really have no idea how to reproduce it, i'll try to stay put, but usally it's when I make a change that requires to app to be completely reloaded. Usually I create an error, I correct it and the app is reloaded, but is fully rendered before the download is finished, creating this bug.
