### ISSUE TITLE
expo-barcode-scanner requires an internet connection

### ISSUE THREAD

**Issue by ekifakhrureza** [expo/expo#10590]
I have a problem with expo-barcode-scanner  because it requires an internet connection when scan qr code..
I need this feature to implement in my office local connection without internet connection.
Is it possible to implement expo-barcode-scanner without an internet connection when scan qr code?
Please give me any solution..Thanks..

**Comment by byCedric** [comment]
Hi @ekifakhrureza, thanks for writing in. On both [Android](https://github.com/expo/expo/blob/a34fe91fbb8edb3cd38caed3e7b20bd35f68de70/packages/expo-barcode-scanner/android/build.gradle#L69) and [iOS](https://github.com/expo/expo/blob/a34fe91fbb8edb3cd38caed3e7b20bd35f68de70/packages/expo-barcode-scanner/ios/EXBarCodeScanner.podspec#L22-L23), we use a library from [Zebra Crossing](https://www.zdnet.com/article/googles-zebra-crossing-project-celebrating-bar-codes/). This is a well-known library to detect and read barcodes. This does not perform any HTTP(S) request and uses its own code to perform the barcode related actions.

If you are having issues related to this, please open a bug issue. Hope this helps!
