### ISSUE TITLE
Animated in react-native with expo-linear-gradient cause "createAnimatedComponent does not support stateless functional components"

### ISSUE THREAD

**Issue by Mayvis** [expo/expo#10599]
### Summary of Issue

Invariant Violation: `createAnimatedComponent` does not support stateless functional components; use a class component instead.

### Reproducible Demo

```
import React, { Component } from 'react'
import { LinearGradient } from "expo-linear-gradient";
import { Animated } from "react-native";

class Project extends Component {
  render() {
    return (
       <AnimatedLinearGradient
          colors={["rgba(255,255,255, 0)", "rgba(255,255,255, 1)"]}
          style={{ ... }}
       />
    )
  }
}

export default Project

const AnimatedLinearGradient = Animated.createAnimatedComponent(LinearGradient); // This line will cause an error.
```

### Version

```
"expo-linear-gradient": "~8.3.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz",
``` 

### Expected Behavior vs Actual Behavior
I want to use Animated with LinearGradient, but it not work.

**Comment by brentvatne** [comment]
in https://github.com/expo/expo/commit/257e88788838257c4983e001fd3b31c8577f293b#diff-3e93ce91136d0e7afb9dc92f5d0c1fe6 we rewrote it to be a function component. it looks like we need to use `React.forwardRef` and pass the ref through to the native component

**Comment by cristian-milea** [comment]
is there any temporary fix until this bug is fixed?

**Comment by alanschwarz** [comment]
@cristian-milea this is a good idea! I will test this today, I've been waiting for this a while now.. thank you!

**Comment by alanschwarz** [comment]
@cristian-milea could you please explain a bit what exactly it is you did here? It is a bit confusing for me... Thank you!

**Comment by cristian-milea** [comment]
> @cristian-milea could you please explain a bit what exactly it is you did here? It is a bit confusing for me... Thank you!

The [HOC (Higher Order Component)](https://reactjs.org/docs/higher-order-components.html) is used to wrap the function component in a class component with props transfer. Nothing special there, think of it as a phone case for the phone => it is still a phone :))
