### ISSUE TITLE
QR Code doesn't display in VSCode embedded terminal

### ISSUE THREAD

**Issue by gustavopiucco** [expo/expo#1059]
Using VSCode embedded terminal (not ok):

![1](https://user-images.githubusercontent.com/13173325/33561018-93d09af0-d8f8-11e7-8e11-e2fe3ae626c3.png)

Using PowerShell (ok):

![2](https://user-images.githubusercontent.com/13173325/33561068-bb01c6a8-d8f8-11e7-8595-e13051348113.png)

**Comment by fxfactorial** [comment]
hi, I'm not a VSCode user but did you check maybe it the in IDE terminal has some kind of special pipe options?

**Comment by nikki93** [comment]
Just a guess -- maybe VSCode's terminal renderer doesn't support the unicode characters required?

**Comment by fxfactorial** [comment]
I don't think that JS package uses unicode

**Comment by GitTom** [comment]
There's also an issue open at vscode about this:
https://github.com/Microsoft/vscode/issues/32648

I would note that @dav_ell reports that he gets the issue with Powershell in vscode, but not when using PS outside vscode.
