### ISSUE TITLE
Font weight and style support

### ISSUE THREAD

**Issue by ChenLi0830** [expo/expo#106]
> Note: Fonts loaded through Expo don’t currently support the fontWeight or fontStyle properties — you will need to load those variations of the font and specify them by name, as we have done here with bold.

It would be nice to have the support for fontWeight and fontStyle.

**Comment by skevy** [comment]
Unfortunately, at the moment this is a limitation of the platform. We'll keep this in mind for the future, however!

**Comment by ashinzekene** [comment]
Anything on this?

**Comment by virus2016** [comment]
Does this still not work?

**Comment by vjsingh** [comment]
+1 this would be huge! Hard to manage your fonts and weights otherwise...
