### ISSUE TITLE
Notification response received listener code only working sometimes in production builds

### ISSUE THREAD

**Issue by coopbri** [expo/expo#10609]
### Summary of Issue
React Navigation code within notification listener (`addNotificationResponseReceivedListener`) only triggers sometimes in production builds (Android `.aab` and iOS `.ipa`), but consistently works in development. In production, the navigation code works approximately 20% of the time. In development, I have not seen the code fail and no errors are logged.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
- **Expo diagnostics output:**
  ```
  Expo CLI 3.27.14 environment info:
    System:
      OS: Linux 5.8 Arch Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.13.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.7 - /usr/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^38.0.0 => 38.0.10
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed
  ```
- **Target platforms:** Android, iOS

### Reproducible Demo
In a component called `OverviewScreen.tsx` at the top of a React Navigation stack navigator, I have the following side effect:
```js
  useEffect(() => {
    const listener = Notifications.addNotificationResponseReceivedListener(
      (res) => {
        const data = res.notification.request.content.data;

        // `groupOne` and `groupTwo` are JSON objects defined elsewhere
        if (data.type === "type_one") {
          props.navigation.navigate("OtherScreen", { group: groupOne });
        } else if (data.type === "type_two") {
          props.navigation.navigate("OtherScreen", { group: groupTwo });
        }
      }
    );

    return () => {
      listener.remove();
    };
  }, []);
```
I am not sure if this is an issue with the `useEffect` dependency array, but it consistently works in development both if the Expo app is closed or foregrounded. I also tried setting up the same listener in the entry component (`App.tsx`) without luck.

### Steps to Reproduce
- Create Expo project with React Navigation stack navigator (`"@react-navigation/native": "^5.5.1", "@react-navigation/stack": "^5.5.1"`)
- Add primary screen component to stack navigator with above notification listener code (such as `OverviewScreen.tsx`)
- Add another screen component for navigation from notification listener (such as `OtherScreen.tsx`)
- Generate platform binaries with  `expo build:android` and `expo build:ios`
- Using [Expo push notification tool](https://expo.io/notifications) or otherwise, send push notifications with `type: "type_one"` or `type: "type_two"` key-value pair in the extra JSON data field
- See if push notification properly navigates to `OtherScreen`

### Expected Behavior vs Actual Behavior
**Expected:** `addNotificationResponseReceivedListener` navigation code consistently navigating in production builds
**Actual:** `addNotificationResponseReceivedListener` navigation code only navigating sometimes in production (~20% of the time)
<br><hr><br>
Thank you for your help!

**Comment by brentvatne** [comment]
hi there.

we don't debug issues that aren't minimal. it sounds like there could be something you aren't expecting happening in react-navigation itself. if you can isolate this to something you can reproduce in an app with just expo-notifications, please create a new issue with a mcve (https://stackoverflow.com/help/mcve). otherwise you may want to create an issue on react-navigation for this.
