### ISSUE TITLE
send expo push notification from reactJS web app

### ISSUE THREAD

**Issue by darryl1975** [expo/expo#10600]
Hi, 

I tried to install expo-server-sdk on my react-web-app using 'yarn add expo-server-sdk'. I did successfully install it in the application. 

I m trying to send push notification on my web app to expo client mobile app.

I tried to copy the following code into the reactJS webapp:

        let expo = new Expo();
        let messages : any = [];

        const data = {
            'to': 'ExponentPushToken[xxx_y_xxxxxxxxxxxxxxxx]',
            'sound': 'default',
            'title': 'DOB',
            'body': 'Breaking news!'
        };
        messages.push(data);

        let chunks = expo.chunkPushNotifications(messages);
        let tickets = [];
        (async () => {
            for (let chunk of chunks) {
                try {
                    let ticketChunk = await expo.sendPushNotificationsAsync(chunk);
                    console.log('ModalScheduleBroadcast useEffect (ticketChunk): ', ticketChunk);
                    tickets.push(...ticketChunk);
                } catch (error) {
                    console.error(error);
                }
            }
        })();

However, when I run the code, I encountered the following error:

**Access to fetch at 'https://exp.host/--/api/v2/push/send' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**
ExpoClient.ts:214 POST https://exp.host/--/api/v2/push/send net::ERR_FAILED

![screenshot_1948](https://user-images.githubusercontent.com/8895749/95405020-387e5c80-0949-11eb-88cb-2c539c265553.png)

I am not sure how to go about resolving this. I have tried different methods. Can I have your solution on how to resolve this? 

Appreciate. Thank you.

Darryl

**Comment by brentvatne** [comment]
expo-server-sdk-node is meant to run in a node.js app, not in a web browser :)

you can read the source to see how to implement a similar thing in the browser. sending push notifications in a browser would be highly unusual, though.
