### ISSUE TITLE
Support, on Android, something analogous to the '+' for manual URL entry on iOS

### ISSUE THREAD

**Issue by nikki93** [expo/expo#1060]
<img width="828" alt="screenshot 2017-12-04 14 26 54" src="https://user-images.githubusercontent.com/49151/33571981-7ded5942-d8e6-11e7-86fe-41f2b6689fbd.png">

^ there's a '+' on the top right on the iOS version but not in the Android version, it's less clear how to manually enter URIs on Android (if possible).

**Comment by imakin** [comment]
why can't we input url manually today for android?

**Comment by FiberJW** [comment]
This seems to be resolved, so I'll close this for now. If you need further support, please make a topic on our [forums](https://forums.expo.io) :)
