### ISSUE TITLE
Width of TextInput is wrong with custom font

### ISSUE THREAD

**Issue by r0gi** [expo/expo#10614]
### Summary of Issue
The width of TextInput on Android is calculated wrong; it takes the width of the default font. I don't recall this happening in SDK 38.
Screenshots:
[default font]
![image](https://user-images.githubusercontent.com/47291559/95540545-854b5b80-0a4d-11eb-9d44-dd2dd6b21468.png)

[custom font]
![image](https://user-images.githubusercontent.com/47291559/95540614-b4fa6380-0a4d-11eb-9c45-09f852810ee0.png)

I'm unsure if I should be posting this issue here or the react-native repository. [This issue in the react-native repo](https://github.com/facebook/react-native/issues/23629) described the same problem, but is now closed.

### Environment
Expo CLI 3.27.14 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD   
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.17
    Expo Workflow: managed

Screenshots are from a OnePlus 6T.
 
### Steps to Reproduce
Make a new expo project, I called mine `issue`
1. In terminal: `expo init issue`
2. Select the blank managed workflow template
3. In terminal: `expo install expo-font @expo-google-fonts/fjalla-one`
4. Modify your App.js to be as follows:
```
import { StatusBar } from "expo-status-bar";
import React from "react";
import { StyleSheet, Text, TextInput, View } from "react-native";
import { AppLoading } from "expo";
import { useFonts, FjallaOne_400Regular } from "@expo-google-fonts/fjalla-one";

export default function App() {
  let [fontsLoaded] = useFonts({
    FjallaOne_400Regular,
  });

  if (!fontsLoaded) {
    return <AppLoading />;
  }
  return (
    <View style={styles.container}>
      <TextInput style={styles.textInput}></TextInput>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  textInput: {
    backgroundColor: "#fab",
    fontFamily: "FjallaOne_400Regular",
  },
});
```
5. In terminal: `expo start` and run on expo client on android
6. Start typing in the TextInput and watch the gap to the right increase as you type.
7. Remove the fontFamily style for the textInput (line 32) and reload the expo app
8. Start typing in the TextInput and watch there be no gap anywhere when using default font

### Expected Behavior vs Actual Behavior
Expected width of TextInput to match custom font instead of always matching default font.

**Comment by brentvatne** [comment]
this does seem to still be an issue in react-native itself. i copied your code to a blank new project, observed the behavior, then ejected and tried again and it had the same behavior, so it seems unrelated to the expo managed workflow. perhaps worth re-creating an issue on react-native, and also including a [mcve](https://stackoverflow.com/help/mcve) that is independent of any third party library

**Comment by r0gi** [comment]
I just checked on SDK 38 and it actually behaves the same way so I think you're right, this is a react-native issue that I never noticed before. Thank you for the prompt response, I'll create an issue on the react-native repo.
