### ISSUE TITLE
Expo-update issue with Android and SDcard

### ISSUE THREAD

**Issue by velcis** [expo/expo#10611]
I'm currently on SDK 38 of Expo Bare Workflow, just to youse expo-updates and I have problem with Android and SDCard.

I think the app is installed on SDCard so I'm getting this error:

`facebook::react::Recoverable: Could not open file/data/user/0/com.package-name/files/.expo-internal/6ACDE017E006293761347FE0BF34AE63A1BC85F5C76BCF3DD8A65244D38F9083.js: `

**It can be reproduced with** installing the app, with a Android with SDCard.4

Any clue to fix this?

**Comment by brentvatne** [comment]
i'm not sure i understand. you stored the app on your sd card and then you removed the sd card? or what?

**Comment by velcis** [comment]
> i'm not sure i understand. you stored the app on your sd card and then you removed the sd card? or what? can you give _detailed and exact steps_ that we can follow to reproduce this?

No, just installed in a device with SDCard set. Just installed as a normal app, and got crashed. The issue occurs when expo-updates, try to update it. I think the expo-update is downloading to SDCard, but the app is requesting from internal storage.

I show the steps above.

**Steps to reproduce**

- [ ] New Bare Workflow Project
- [ ] Create a simple logic to update the app with "expo-updates"
- [ ] Install the apk into a Android Device with SDCard on it.
- [ ] Open the app first time.
- [ ] Run **expo publish**
- [ ] Reopen the app and wait to fetch the update
- [x] The app crashed with no errors, but with Crashlytics I can get the error about _Could not open file..._
