### ISSUE TITLE
[AppleAuthentication][Managed app][iOS] In simulator, standalone build: AuthorizationError error 1000

### ISSUE THREAD

**Issue by platy** [expo/expo#10619]
### Summary of Issue 

When following the configuration instructions and tips on this page and then running standalone in simulator the button errors immediately on click with:
```
The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)
```
There is no more information in the system logs.

The apple login works on an iPhone and the error can't be reproduced there.

#5781 was closed a year ago and I don't believe is related to this simulator issue, but there are around 6 people since July 2020 reporting this issue specifically with the simulator.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.24.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
```

### Steps to Reproduce

- Implement login according to instructions
- build for simulator
- run in simulator
- click button

### Expected Behavior vs Actual Behavior

The error is particularly unhelpful and gives no information to help fix this. If it doesn't work in a simulator the documentation should state that.

Unfortunately I do not have a real device to test on.

Thanks

**Comment by dwyanelin** [comment]
I have the same problem.

And I tried: https://snack.expo.io/
It worked. But I don't know how safe it is.

You can test the method on snack before expo fix the issue.

**Comment by platy** [comment]
I was able to test using a colleague's iPhone and everything works

**Comment by dwyanelin** [comment]
I found error 1000 was appear when first time use simulator, and the simulator navigate to setting to sign in Apple ID.

Second press the button, there are no any response. no error, no return credential.

**Comment by DavidAPears** [comment]
I am having the same issue, unfortunately, I also don't have an iOS handset to test on right now.

**Comment by asabadyr** [comment]
Same behaviour guys. Testing on simulator.
After entering the password it hangs forever with no error or response

**Comment by brentvatne** [comment]
this appears to be a bug in the ios 14 simulators: https://developer.apple.com/forums/thread/651533

you can use ios 13 simulators until it's resolved

**Comment by Mogikan** [comment]
Maybe the following answer will help you https://stackoverflow.com/a/63378638/1099716
