### ISSUE TITLE
Universal link can not handle by Linking.getInitialURL correctly  when standalone app is not opened about 10(or more) hours.

### ISSUE THREAD

**Issue by imwilliamxy** [expo/expo#10612]
### Summary of Issue 
Universal link can not handle by Linking.getInitialURL correctly  when standalone app is not opened about 10(or more) hours.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.27.10 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /Users/xingyong/.rvm/gems/ruby-2.6.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29
        Build Tools: 28.0.2, 28.0.3, 29.0.3
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: ^16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.3.9 
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: managed

Standalone app env: iOS 14.0

### Reproducible Demo
I'll create a new demo repo asap.

 
### Steps to Reproduce
1. build standalone app.
2. install standalone app.
3. press a universal link ralated with app,  Linking.getInitialURL() return link correctly, the app runs ok now.
4. leave iOS device and go to sleep. (maybe need 10 hours or more)
5. press  a universal link ralated with app, Linking.getInitialURL() only return app schema, not the link this time.

### Expected Behavior vs Actual Behavior
Expected Behavior: Linking.getInitialURL() return universal link correctly,
Actual Behavior:  Linking.getInitialURL() return app schema,

**Comment by brentvatne** [comment]
i can't imagine how the amount of time that the device is inactive would be relevant here :) is there no way you can reproduce this *without leaving your device for 10 hours*?

**Comment by imwilliamxy** [comment]
Unfortunately, there is no way for me to reproduce this bug quickly on the emulator or on a physical device currently. The bug is hidden  deeply. A few weeks ago, we found this issue related with "long time background" standalone app. Few days ago, We found that the bug was related to the expo-linking module by add more and more debug logs.
