### ISSUE TITLE
My Expo App in release mode (minified) consumes 200-300MB of RAM.

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#10613]
Hi!

I am developing an app (I haven't generate an apk yet), and when profiling it with the Performance Monitor, I notice that it is consuming from 200 to 300MB of RAM. Is this normal? I mean, as I am running the app inside the Expo client, maybe this is the cause.

> Currently the app is small, no more than 25k lines, not complex and the most heavy components I am using are cached images, React Navigation 5, endless FlatLists of Images (windowSize = 5, maxToRenderPerBatch = 5, removeClippedSubviews = false and default options) and a DB listener. One of my components has a memory leak to solve, but the memory usage is high before mounting it, so not the problem.

Will the usage decrease when I generate the apk and don't run it with the Expo client? If so, approximately how much are we talking about?

Thank you.

**Comment by brentvatne** [comment]
hi there,

the memory usage will depend entirely on the contents of your app. if you have a lot of large images, those consume memory, and so on.

indeed memory usage is very different in the expo client app vs a built apk/aab. you can eject and profile it in android studio if you're curious, or build the apk and use `dumpsys` to analyze: https://developer.android.com/studio/command-line/dumpsys#ViewingAllocations
