### ISSUE TITLE
Constants.manifest is not available in the bare workflow. You should replace it with Updates.manifest. 

### ISSUE THREAD

**Issue by Junaid3232** [expo/expo#10622]
I just eject expo and now the warnings i get says
![Screenshot 2020-10-09 at 19 56 12](https://user-images.githubusercontent.com/55939459/95602556-8476f180-0a6e-11eb-9566-e2639cfd2b70.png)

Your app includes 3 packages that require additional setup in order to run:
- expo-constants: Constants.manifest is not available in the bare workflow. You should replace it with Updates.manifest. 

How can i solve this??

**Comment by AdamJNavarro** [comment]
Hey @Junaid3232,

As the terminal logs say, you'll need to swap any calls to `Constants.manifest` in your code with `Updates.manifest` (also be sure to import the updates package via `import * as Updates from 'expo-updates'`

I'm going to close this issue. If you run into any more issues or have further questions, please head over to [forums](https://forums.expo.io/)!

Cheers,
Adam

**Comment by woodcockjosh** [comment]
I switched my references from `Constants.manifest` to `Updates.manifest` and the references were undefined when running `expo web`
