### ISSUE TITLE
[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null

### ISSUE THREAD

**Issue by jonatasdaniel** [expo/expo#10627]
## 🐛 Bug Report

After ejecting from managed Expo, I run expo publish, all good, but when opening my project on Expo app, I got this error:
`Uncaught Error: Invariant Violation: "main" has not been registered.`
and on Android devices the error is more detailed:
`Uncaught Error: Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null`.

Even after linking `async-storage` lib (as suggested in the error log), the problem still happens.

### Environment
 ```
Expo CLI 3.22.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.22.0
```

### Reproducible Demo
No

 
### Steps to Reproduce
1. Eject from Expo
2. Add `@react-native-community/async-storage` lib
3. `import AsyncStorage from "@react-native-community/async-storage"` in some component
4. `expo publish`
5. Open project in Expo app

### Expected Behavior
Successful app build

### Actual Behavior
`[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null`

**Comment by brentvatne** [comment]
after you eject you cannot open your published project in the expo app. please notice that when you run `expo publish` you see a warning about this:

```
╭─~/code/testing-storage ‹master›
╰─$ expo publish

- Release channel: default
- Workflow: Bare

- Workflow target: This is a bare workflow project. The resulting publish will only run properly inside of a native build of your project. If you want to publish a version of your app that will run in Expo client, please use expo publish --target managed. You can skip this warning by explicitly running expo publish --target bare in the future.
```
