### ISSUE TITLE
addNotificationResponseReceivedListener not triggering when app is not running

### ISSUE THREAD

**Issue by coopbri** [expo/expo#10621]
### Summary of Issue
Notification listener for user interaction (`addNotificationResponseReceivedListener`) does not trigger when app is not running, only when app is foregrounded or backgrounded.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
- **Expo diagnostics output:**
  ```
  Expo CLI 3.27.14 environment info:
    System:
      OS: Linux 5.8 Arch Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.13.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.7 - /usr/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^38.0.0 => 38.0.10
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed
  ```
- **Target platforms:** Android, iOS

### Reproducible Demo
`App.tsx` side effect:
```js
  useEffect(() => {
    const listener = Notifications.addNotificationResponseReceivedListener(
      (res) => {
          console.log(res); // not logging when app is not running
      }
    );

    return () => {
      listener.remove();
    };
  }, []);
```

Also tried outside of (above) component (`App.tsx`):
```js
Notifications.addNotificationResponseReceivedListener((res) => {
  console.log(res);
});

const App = () => { ... };
```

### Steps to Reproduce
- Create Expo project and import Expo Notifications module into main entry component
- Obtain device push notification token following [Expo docs on push notifications](https://docs.expo.io/push-notifications/overview/)
- Add above listener code to main entry component
- Using [Expo push notification tool](https://expo.io/notifications) or otherwise, send push notification using acquired push token
- See if push notification data is logged when app is killed

### Expected Behavior vs Actual Behavior
**Expected:** `addNotificationResponseReceivedListener` logging response data when app is killed
**Actual:** `addNotificationResponseReceivedListener` only logging response data when app is foregrounded or backgrounded

<br><hr><br>
Thank you for your help!

**Comment by AdamJNavarro** [comment]
Hey @coopbri, two quick questions for you. Have you tested on SDK39 as well? Also, is this occurring when in the Expo client, standalone or both environments?

**Comment by coopbri** [comment]
Hey @AdamJNavarro, thanks for your response!

I have not tested on SDK39, and have only tested in the Expo client. I will test both and report back.

**Comment by coopbri** [comment]
@AdamJNavarro, first of all, thank you for your contributions to Expo. SDK 39 is awesome! Love having RN 0.63 support in the managed workflow.

Unfortunately, I had the same issue both with SDK 39 as well as in a standalone apk (physical Android device).

I think my issue might be similar to #7787. I have some production builds queued up right now, and am going to test on both iOS and Android after they hit the app stores.

**Comment by brentvatne** [comment]
this is expected behavior: https://docs.expo.io/versions/latest/sdk/notifications/#listening-to-notification-events

> Listeners registered by this method will be called whenever a notification is received while the app is running.

**Comment by coopbri** [comment]
The quote you mentioned is for the `addNotificationReceivedListener`, not the `addNotificationResponseReceivedListener` I am using.

`addNotificationResponseReceivedListener`:
> Listeners registered by this method will be called whenever a user interacts with a notification (eg. taps on it).

**Comment by coopbri** [comment]
I just tested on both the iOS app and Android app in production with the `addNotificationResponseReceivedListener` code outside of the `App.tsx` component render, and the issue persists (listener code not triggering).

In #7787, @ltsharma mentioned that it worked for him outside of the component (https://github.com/expo/expo/issues/7787#issuecomment-696347309), but I did not have any luck with this for some reason.

**Comment by coopbri** [comment]
Nevermind, I discovered that this is indeed an active bug as described in #9866. This should not have been closed due to "expected behavior" as it is indeed a bug, but rather as a duplicate issue, I suppose.
