### ISSUE TITLE
Allow custom *UsageDescription strings in iOS standalone builds

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1062]
Right now all of these keys are auto-populated with generic reasons like "Allow `<app-name>` to use the camera" or "Allow `<app-name>` to access the device location". Sometimes Apple requires more information here, so we should expose `app.json` keys that allow optional customization of these messages.

**Comment by terribleben** [comment]
We have a fix for this landed internally which should go out with SDK 24. You will be able to specify your own values for any of the `*UsageDescription` keys.

**Comment by shivamgupta94** [comment]
Hi, when is the expected time frame for this fix in the sdk24?

**Comment by terribleben** [comment]
The soonest would be some time next week, but we don't know the exact date yet.

**Comment by raihanrazi** [comment]
@terribleben thanks! Really keen on this one. Having some issues with Apple at the moment re this. Cheers.

**Comment by kelvinlawson** [comment]
Can you work around this by setting the usage description in info.plist via app.json?
 https://docs.expo.io/versions/latest/guides/configuration.html#infoplist

**Comment by terribleben** [comment]
Currently, no. Once SDK 24 comes out, that will be the recommended way of doing this.

**Comment by jhalborg** [comment]
Related Canny request. 

https://expo.canny.io/feature-requests/p/customisable-permission-descriptions 

Also, @terribleben  - why is not not possible via plist?

**Comment by kelvinlawson** [comment]
According to this on the forums it is possible: https://forums.expo.io/t/expo-location-permission-popup-text/5404/6

**Comment by jhalborg** [comment]
I've just tested it, and it works. I added the following to my app.json:
```
"ios": {
      ...
      "infoPlist": {
        "NSCameraUsageDescription":
          "The app needs permission to your camera in order to take photos for upload",
        "NSPhotoLibraryUsageDescription":
          "The app needs permission to your camera roll in order to add photos you've already taken for upload"
      }
    },
```

Whether or not those descriptions are enough for the app to be approved is yet to be seen, I'm praying to the review gods, but they are shown correctly in the permission dialog. 

The fact that they rejected the app for this reason during an obvious upload flow is beyond me, though 😢

**Comment by terribleben** [comment]
We started rolling out SDK 24 last night (blog post forthcoming). So the solution @jhalborg demonstrated in their last comment should work on our `exp build` servers as of now. There will also be documentation about this. Actually we wrote an entire new docs guide about considerations when submitting to the App Store. Thanks for the feedback everyone and sorry for the long wait.
