### ISSUE TITLE
Android app crashes enabling remote debugger - SDK 39

### ISSUE THREAD

**Issue by franjorub** [expo/expo#10634]
Hi recently I upgraded my current app on SDK 38.0.8 to the new SDK 39 using `expo upgrade` but when I want to use the remote debugger along with react native debugger the app crashes. I'm on Windows 10 and my device is the emulator in the latest version.

**Comment by brentvatne** [comment]
hi there. can you send a screenshot of your "projects" tab in the emulator verify that it is indeed the latest version? also, can you reproduce this issue in a new blank app or just in your specific app?
