### ISSUE TITLE
Invisible Captcha: expo-firebase-recaptcha

### ISSUE THREAD

**Issue by ankur99** [expo/expo#10631]
### Please note that feature requests opened in the core Expo repository will be closed.

  Thanks for helping us make Expo even better! 😀
  Unfortunately, this is not the right place for feature requests. Please find and upvote your feature (or create a new one) at https://expo.canny.io instead.

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by sra-013** [comment]
The 'attemptInvisibleVerification' flag is still giving ReCaptcha. Is that because it is in an experimental phase?

**Comment by brentvatne** [comment]
it hasn't been rolled out, we'll release it with sdk 40

**Comment by brentvatne** [comment]
it's released in expo-firebase-recaptcha@1.3.0

**Comment by sra-013** [comment]
Thank you @brentvatne! I tried and it bypassed the Recaptcha for the first time, but I started seeing it from the second time onwards. Could you give an idea of approximately what percentage of users will see the ReCaptcha if we go ahead with this implementation?

**Comment by brentvatne** [comment]
sorry i don't know, it's entirely dependent on google's recaptcha. it's not a perfect solution but it should save some users the hassle of using the recaptcha. see https://github.com/expo/expo/pull/9474#issuecomment-720568487

**Comment by aditya-vaish5** [comment]
Thank You for the feature, it surely helped, I think I made the right choice by choosing react native over flutter.
