### ISSUE TITLE
App crashes randomly when using FirebaseStorage

### ISSUE THREAD

**Issue by be90728** [expo/expo#10633]
## 🐛 Bug Report

When the App uses Firebase Storage, it will crash when using the function "put" or "putstring"

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.13 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.14
      react-navigation: ^4.1.1 => 4.4.1
    Expo Workflow: managed
```

### Reproducible Demo

```
      const AvatarBase64 = "...ImageBase64..."
      const blob = Buffer.from(AvatarBase64, 'base64');
      //App Will Crash Here  ↓↓↓
      firebase.storage().ref(`/avatar/users`).child(firebase.auth().currentUser.uid).put(blob).then(async (snapshot) => {
        const imageUrl = await dlUrl.ref.getDownloadURL();
      }).catch(err=>{ console.log(err) });
```
 
### Steps to Reproduce

```
Make sure "AvatarBase64" has a valid Base64 string
Then, upload the picture, the App may crash randomly (without any error message)
```

### Expected Behavior vs Actual Behavior

```
Expected Behavior
imageUrl returns a valid image URL
```

```
Actual Behavior
App crashes randomly, but sometimes it returns image URL
```

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
