### ISSUE TITLE
Does expo server will cache the published project ?

### ISSUE THREAD

**Issue by kevinleeTCA** [expo/expo#1063]
I met an issue with expo publish.
I recently upgrade expo SDK from 21 to 23, and publish to expo sever. Then I found that SDK 23 does not work well with "victory-native" (a graph library for react-native) (https://github.com/FormidableLabs/victory-native/issues/194). It will always show blank page whenever we use the lib to show graph

So I decided to downgrade expo SDK to 21. After publishing my changes to expo, the blank page problem is still there, I thought it might be cached, then I remove the project from expo client and re-publish it again, the problem is still there.

However, when I change the "name" and "slug" to anther name in "app.json", and publish, everything worked.
so, I am wondering is the published project being cached or archived when we remove the project ?
Any way we can fix this ? since in the future if same problem happens again, I have to rename the app name again and again.

**Comment by quinlanj** [comment]
hi @kevinleeTCA , for now, you can use release channels to publish a separate version https://docs.expo.io/versions/latest/guides/release-channels.html with the desired sdk version.

**Comment by kevinleeTCA** [comment]
Hi @quinlanj thank you for ur reply, but I only need one version to work, i do not need multiple versions by using release channels. I only use SDK 21 in my project now, so I just wanna publish these changes, it seems it does not work if I do not change the app and slug name, which is very confusing.   

Is this might be a potential bug of Expo that when downgrade SDK version, the published one still use the latest SDK version ?
