### ISSUE TITLE
expo-google-signin not working by following the docs => login: Error:GoogleSignIn.null:NETWORK_ERROR

### ISSUE THREAD

**Issue by ta1bbty** [expo/expo#10636]
Hi team,

First of all, thanks for the awesome work that your team is putting up in this project.
Let's talk about the problem now 🙁 

I was trying to integrate [expo-google-sign-in](https://docs.expo.io/versions/latest/sdk/google-sign-in/) but am unable to do that.

### My Approach
- Tried with expo managed but since expo client didn't support google auth by default and I didn't want to go through the hassle of this 😅 
> To use Google authentication in the Expo client, check out expo-google-app-auth or expo-app-auth.
- Did `expo eject` and compiled but getting `login: Error:GoogleSignIn.null:NETWORK_ERROR`

### Things I did
- Checked the fingerprints and added `debug` as well as `release` fingerprints in my firebase console.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/45117337/95701034-172db100-0c66-11eb-9f00-9d80e27b8fee.png">

- Enabled google signin on firebase
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/45117337/95700981-f6fdf200-0c65-11eb-837b-4072ac652517.png">

### What I found online
It is due to fingerprint mismatch but I am not sure how this can be 🤔

**Comment by ta1bbty** [comment]
I didn't add a ios `plist` file as I was only doing this for android.

would that be a problem 🤔 ?

**Comment by AdamJNavarro** [comment]
Hey @ta1bbty, 

The error indicates something might be wrong with the internet connection. Can you detail how you are testing this/running into this error? Also, it might be worth trying on a different network if possible.

As for the `ios plist` question, that won't matter if you're testing this on Android.

Cheers,
Adam

**Comment by ta1bbty** [comment]
Hi @AdamJNavarro 

I am testing it on a real device and yup internet is fine.

I see the native google account choosing screen and then after choosing an account this happens.

I've tried on wifi as well as mobile data, same issue.

However, I am curious as to how can this happen due to lack of internet 🤔 
I mean I can check with disabling the internet connection and then see what error happens

**Comment by ta1bbty** [comment]
Hi @AdamJNavarro 

I tried to verify the keys for release and debug builds as well. Even those checked out.

I first decompiled the apk and then checked the `META-INF/CERT.RSA` file as mentioned [here](https://stackoverflow.com/a/11331951/11857690)

## Release build key check
<img width="865" alt="image" src="https://user-images.githubusercontent.com/45117337/95853285-c788db80-0d72-11eb-9076-0e5175ddd17e.png">

## Debug build key check
<img width="830" alt="image" src="https://user-images.githubusercontent.com/45117337/95854100-1a16c780-0d74-11eb-89c9-4d4984ddfb5c.png">


## Debug keys were different, after adding those it's working in debug and also in release.

Thanks a lot for looking into this. Am closing this 🙂

**Comment by ilkerceng** [comment]
Hi, i disabled Google on firebase and it worked interestingly :(
<img width="1143" alt="Screen Shot 2021-09-09 at 23 26 36" src="https://user-images.githubusercontent.com/4923344/132757771-970f2a80-6e4e-4793-a61c-bb6604f02740.png">
