### ISSUE TITLE
[docs] unclear options for Android within App Signing

### ISSUE THREAD

**Issue by gregfenton** [expo/expo#10635]
(Originally reported as part of #10632)

As a reader of the options for [Android when App Signing](https://docs.expo.io/distribution/app-signing/#option-1--using-app-signing-by-google), it isn't obvious to me whether sub-sections of Option 1 are mutually exclusive. From my read there are 3 sub-sections:

- "If you're deploying a new app..."
- "If you're working on an existing app that uses an app signing key..."
- "If you want to create the upload certificate yourself, replace steps 2 and 3 from above with"

As a reader, I find myself having to read the entire section to figure out what part(s) I need. And even after reading them, with the lack of clear distinction (i.e. "pick one of subsection X, Y or Z"), I am not entirely sure if I can stop after doing all the steps in just the first (or second) section.

![image](https://user-images.githubusercontent.com/4407559/95694062-d8641080-0bfd-11eb-8268-9fc6928b4b1f.png)

**Comment by cruzach** [comment]
I think once we fix the ordered list bug, this will be a lot easier to understand, as it's pretty paired down already

Other than that, how do you think we might simplify this further @gregfenton ?

**Comment by cruzach** [comment]
Hopefully the fixed ordered list helps make this more readable. I'm not sure how we can make it clearer that the options for "If you're deploying a new app" & "If you're working on an existing app" are mutually exclusive (those options can't _both_ apply to an app), but I'm happy to review any docs PR to improve that

For now, I'm going to close this issue
