### ISSUE TITLE
[docs] App Signing doc not rendering numbered steps

### ISSUE THREAD

**Issue by gregfenton** [expo/expo#10632]
On the published page for [app signing](https://docs.expo.io/distribution/app-signing/) under the section for [Option 1](https://docs.expo.io/distribution/app-signing/#option-1--using-app-signing-by-google), there are a number of steps described and some steps reference previous steps by step numbers (e.g. "the .pem file you received in step 3") -- however, the steps are not rendered with numbered bullets (#1, #2, #3, ...) but instead regular bullets ( • ).

The markdown uses numbered bullets.  Something is amiss!

![image](https://user-images.githubusercontent.com/4407559/95689041-40096400-0bdc-11eb-97ca-188ddedde9c7.png)

**Comment by gregfenton** [comment]
In addition, while working on this page:

As a reader of the rendered page, it isn't obvious to me whether sub-sections of Option 1 are mutually exclusive.  From my read there are 3 sub-sections:
- "If you're deploying a new app..."
- "If you're working on an existing app that uses an app signing key..."
- "If you want to create the upload certificate yourself, replace steps 2 and 3 from above with"

As a reader, I find myself having to read the entire section to figure out what part(s) I need.  And even after reading them, with the lack of clear distinction (i.e. "pick one of subsection X, Y or Z"), I am not entirely sure if I can stop after doing all the steps in just the first (or second) section.

Hope the description within this writeup makes sense.  It is ... not easy to describe 😄

**Comment by AdamJNavarro** [comment]
Thanks for bringing this to our attention, @gregfenton! We'll try to get a fix for the markdown issue deployed as quickly as we can. As for the confusion, would you mind creating a separate issue so that we can keep things scoped properly and discussions focused.

Cheers,
Adam
