### ISSUE TITLE
 Argument of an incompatible class: class java.util.HashMap cannot be passed as an argument to parameter expecting class java.lang.String. SDK 38 - expo-facebook

### ISSUE THREAD

**Issue by radu200** [expo/expo#10641]

**Comment by byCedric** [comment]
Hi @radu200, please provide the information we need to investigate this issue. Without any context, we can't help.

**Comment by radu200** [comment]
Hi Cedric, I use expo-sdk 38, error occurs in development environment on Android 10 emulator, OS Ubuntu 19

Here is a code:
export async function signInWithFacebook() {
  try {
    await Facebook.initializeAsync({
      appId: FACEBOOK_LOGIN_APP_ID,
    });
    const { type, token } = await Facebook.logInWithReadPermissionsAsync({
      permissions: ["public_profile", "email"],
    });
    if (type === "success") {
      return token;
    } else {
      return { cancelled: true };
    }
  } catch (e) {
    return { error: true };
  }
}

Thanks,
Radu

**Comment by dramalcolm** [comment]
@radu200 
Just replace await **Facebook.initializeAsync({appId: FACEBOOK_LOGIN_APP_ID});** with Facebook.initializeAsync( FACEBOOK_LOGIN_APP_ID);

**Comment by Vaibhav-Kapupara** [comment]
ew

**Comment by Tausifsmt** [comment]
yes It's working.

**Comment by Tausifsmt** [comment]
> @radu200
> Just replace await **Facebook.initializeAsync({appId: FACEBOOK_LOGIN_APP_ID});** with Facebook.initializeAsync( FACEBOOK_LOGIN_APP_ID);

yes, It's working.
