### ISSUE TITLE
Adding gif for text input?

### ISSUE THREAD

**Issue by chow1340** [expo/expo#10646]
Is there anyway I can allow gif input for android in expo? I currently get this error when I try to click on the gif input:
![image](https://user-images.githubusercontent.com/56985007/95774073-b914c400-0c8d-11eb-9fb9-dddf8b0ed98b.png)

code:

    const _onImageChange = (event) => {
      const {uri, linkUri, mime, data} = event.nativeEvent;
      console.log(event);
      console.log(uri)
      // Nothing shows up on console here
    }
    return (
    
      <TextInput onImageChange={_onImageChange} />
      
    );

**Comment by AdamJNavarro** [comment]
Hey @chow1340,

As our issue template states, we reserve Github issues for reproducible and actionable bug reports. For questions such as this one, please feel free to create a post on our [forums](https://forums.expo.io/)!

Cheers,
Adam
