### ISSUE TITLE
[expo-in-app-purchases] [ios] Products are not properly cached for purchase flow

### ISSUE THREAD

**Issue by erandagan** [expo/expo#10654]
### Summary of Issue 
On iOS, `purchaseItemAsync` checks if a cached product has been already fetched [here](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L86). However, the method then continues to re-fetch the product [here](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L95) - rendering the caching process useless, submitting an extra network call (thus incurring additional delay until the purchase flow appears to the end-user) and creating an inconsistency with the android implementation which does [pull the product from the cache](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java#L140).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
react-native-unimodules@0.11.0
expo-in-app-purchases@9.1.0
```
 
### Steps to Reproduce
on iOS:
```js
await InAppPurchases.getProductsAsync("your.sku");
await InAppPurchases.purchaseItemAsync("your.sku"); // Causes a re-fetch, although the product should be in the cache.
```

#### Expected:
After fetching a product, it should be cached and reused during purchase.
#### Actual:
[The product is verified to be cached](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L86) but [is still re-fetched](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m#L92).

### Suggested Solution
1. Instead of caching the fetched product IDs (`_retrievedItems`), cache the actual product object like the current Android implementation.
1. Inside `purchaseItemAsync`, pull the product from the cache instead of refetching it and directly start the purchase flow.

**Comment by cruzach** [comment]
hey @erandagan , this is a good suggestion for the API, thanks! will open a PR in a bit
