### ISSUE TITLE
[expo-media-library] Write permission needlessly enforced on read-only operations

### ISSUE THREAD

**Issue by erandagan** [expo/expo#10653]
### Summary of Issue 
MediaLibrary enforces write permissions on read-only operations, like [getAssetsAsync](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryModule.java#L223).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
react-native-unimodules@0.11.0
expo-media-library@9.2.1
```

### Reproducible Demo

My apologies for not providing a demo; The issue is clearly visible in the codebase.

`getAssetsAsync` verifies the caller has permissions by calling `isMissingPermissions()` [here](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryModule.java#L224). [`isMissingPermissions`](https://github.com/expo/expo/blob/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryModule.java#L285) checks for both read and write permissions, although `getAssetsAsync` only requires a read permission.

### Steps to Reproduce
1. In an android app, request just the `READ_EXTERNAL_STORAGE` permission.
1. Call `getAssetsAsync`.
1. The call will fail although it has all the required permissions to complete.

#### Expected
`getAssetsAsync` shouldn't enforce the write permission. 

#### Actual
`getAssetsAsync` enforces a write permission.

I understand that the current code expects the usage of `MediaLibrary.requestPermissionsAsync` to get both permissions at once. However, using this method isn't feasible in apps that use a different permission mechanism to request precisely the permissions they need - like brownfield apps or apps that partially integrate some specific unimodules, but obtain permissions from elsewhere.

### Suggested Solution
1. Implement `isMissingReadPermission` for read-only operations.
1. Rename `isMissingPermission` to `isMissingReadOrWritePermissions`, which would use `isMissingReadPermission` and the existing [`isMissingWritePermission`](https://github.com/expo/expo/blame/19ffeb6aebf09f1b2007c3ed6c35be091424c31e/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryModule.java#L288)
1. Use `isMissingReadPermission` in read only operations, like `getAssetsAsync`.

**Comment by garviand** [comment]
I'm surprised this hasn't been discussed more. Is it not a common use case to just use the read permissions for the media library? It is surely more common than only using write permissions, for which there is a `writeOnly` argument.

**Comment by kkafar** [comment]
[iOS allows only write-only or read-write permissions](https://developer.apple.com/documentation/photokit/phaccesslevel) (correct me if I'm wrong) -- due to this fact, I believe, API for MediaLibrary module was implemented this way (compatibility between platforms). Therefore changes suggested in this issue, I believe, won't be implemented.
