### ISSUE TITLE
Adding "androidStatusBar" to app.json causing "built-in" KeyboardAvoidanceView-like behavior

### ISSUE THREAD

**Issue by rtlayzell** [expo/expo#1065]
Android (AFAIK)

I was struggling with this issue for some time until I realised that the `androidStatusBar` property from my app.json file was the cause; adding the property back I was successfully able to reproduce the issue.

You should be able to reproduce the issue with the following in app.json:
```
{
	"expo": {
		// ...
		"androidStatusBar": {
			"barStyle": "dark-content"
		},
		// ...
	}
}
```

Is it possible to get a solid status bar without introducing this implicit keyboard avoidance?

**Comment by ashconnell** [comment]
I can confirm that when you add the `androidStatusBar` option to the `app.json` it affects the way the window resizes when the keyboard is up.

I think expo might be accidentally changing the `android:windowSoftInputMode` which ends up breaking the KeyboardAvoidingView, because the windows is already resized so it doesn't need to adjust.

**Comment by ashconnell** [comment]
For now i'm going to leave that out of `app.json` and rely on the react-native `StatusBar` component

**Comment by bamne123** [comment]
After adding `androidStatusBar` option to the `app.json` it adds extra height to the header, not sure about the standalone app, but in expo it does show the extra height. Any solution to hide it?

**Comment by ltankey** [comment]
You can set a negative marginTop of the statusbar height, which I think is not really a proper fix, but offsets the additional padding it adds. Frustratingly you can't set a paddingTop of 0 (always seems to get set).

**Comment by otaviogaiao** [comment]
I'm facing the same issue. KeyboardAvoidingView doesn't work unless androidStatusBar is set. but that breaks my layout. Any workaround?

**Comment by platbr** [comment]
Same problem here.

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. Recent posts indicate this remains an issue, could one of you please open a new issue with a repro case? We'll get it appropriately assigned and we'll be happy to investigate.

Cheers,  
Adam

**Comment by jonasduever** [comment]
This is still broken, right? `androidStatusBar` changes the `android:windowSoftInputMode` behaviour.

**Comment by ltankey** [comment]
Yep.

**Comment by satya164** [comment]
I think it's not something that can be addressed. It's what Android does, not something done by expo.

**Comment by ltankey** [comment]
> I think it's not something that can be addressed. It's what Android does, not something done by expo.

Isn't the problem here that Expo is using a value set in `app.json` which is about the android status bar, which has a direct unintended affect on the keyboard behaviour? I'm not sure how this could not be an expo issue.
