### ISSUE TITLE
[IOS] can not add description when request permission

### ISSUE THREAD

**Issue by haciSeydaoglu** [expo/expo#1066]
I get an error about the permissions I send to the app store as an standalone application. Apple wants me to enter a description of the permissions. However, this parameter is not allowed in EXPO.

I got the error:
Additionally, we noticed that your app requests the user’s consent to access the camera and photos but does not clarify the use of this feature in the permission modal alert.

EXPO SDK Version: 23.0.0

edit: sorry for my english

**Comment by terribleben** [comment]
Hey there, thanks for the report! I think we're already tracking this [here](https://github.com/expo/expo/issues/1062), so I'll consolidate.
