### ISSUE TITLE
[expo-video] Video not yet loaded / documentation

### ISSUE THREAD

**Issue by Clonescody** [expo/expo#10661]
## 🐛 Bug Report

Hi everyone,

I am using a Video element on my app's homepage. The first display happens as expected, however, I am getting the following error sometimes ( mostly when returning to the homepage from inside the app ).

```
Unhandled promise rejection Error: Cannot complete operation because the Video component has not yet loaded
```

The _yet loaded_ makes me think that the view rendering is made before the asset has been loaded, but I don't know how I could handle that.

I am working on a **bare** app, and I'm loading a **local** video as followed : 

```
handleVideoRef = async component => {
    if (component && this.playbackObject === null) {
      this.playbackObject = component;
      const videoAsset = Asset.fromModule(require('./landing_page_video.mp4'));
      await this.playbackObject.loadAsync(videoAsset, {
        isLooping: true,
        isMuted: true,
        rate: 1.0,
        volume: 0,
        resizeMode: 'cover',
        shouldPlay: true,
      });
    }
  };
```
```
<Video
   ref={this.handleVideoRef}
   style={styles.backgroundVideo}
/>
```

I must specify that I am loading the video this way because I had no idea on how to do it from expo-av's documentation. 
The documentation itself does not include an example for the Video, and the source files of the playlist example are just showing URIs to load over the internet. 

I'm down to make a PR in order to update the doc if stuff is missing, but I would like to be sure I'm using the plugin the right way.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
      react-native-web: ~0.13.7 => 0.13.14
      react-navigation: ^4.0.10 => 4.4.2
    npmGlobalPackages:
      expo-cli: 3.27.12
```

Targeting platforms : 
10+ iOS 
29 android with 21 as minimum

Expo-av : "~8.6.0"

### Expected Behavior vs Actual Behavior

Actual : Video doesn't load anymore after the first load, which results in it not showing ( backgroundColor is displayed instead )

Expected : Make the video load throught `handleVideoRef` everytime.

Again, I couldn't find any real documentation on this so I might be doing something wrong. 

Thanks in advance for any help 🙏

**Comment by AdamJNavarro** [comment]
Hey @Clonescody,

You'll need to [load](https://docs.expo.io/versions/v39.0.0/sdk/asset/#assetloadasyncmodules) the asset via `Asset.loadAsync` Right now you're just getting the local uri of the video by calling `fromModule` but not loading the video file. Can you try implementing that and see if it works as expected?

Cheers,
Adam

**Comment by Clonescody** [comment]
Hi @AdamJNavarro, 

Your solution worked better in the end but my main issue was elsewhere. I was using a stored loading prop to determine if I should display the page or a loader, and apparently playing with `async` methods in that case was causing my video to never get loaded. 

New video loading function : 

```
handleVideoRef = async component => {
    if (component && this.playbackObject === null) {
      this.playbackObject = component;

      // here using Asset.loadAsync()

      const videoAsset = await Asset.loadAsync(require('./landing_page_video.mp4'));

      /// here using first entry of the array returned by Asset.loadAsync()

      await this.playbackObject.loadAsync(videoAsset[0], {
        isLooping: true,
        isMuted: true,
        rate: 1.0,
        volume: 0,
        resizeMode: 'cover',
        shouldPlay: true,
      });
    }
  };
```
Previous code in render : 

```
<View>
{loading 
    ? <ActivityIndicator ... /> 
    : <View> <Video ref={this.handleVideoRef} /> <Text>...</Text> </View>
}
</View>
```

New code in render : 

```
<View>
      <Video ref={this.handleVideoRef} />
      {loading ? <ActivityIndicator ... /> : <Text> ... </Text>}
</View>
```
