### ISSUE TITLE
[expo-keep-awake] Expo keep awake error in IOS 14.

### ISSUE THREAD

**Issue by gbferreira** [expo/expo#10664]
### Summary of Issue 
Expo keep awake error in IOS 14. Works fine in prior versions.

### Environment
``` 
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.4 => 37.0.12 
      react: 16.13.1 => 16.13.1 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: 0.63.2 => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.21.5

```
*Simulator*
- IOS 14
- Iphone 8

### Reproducible Demo
It's not my import:

<img width="584" alt="Screen Shot 2020-10-13 at 12 43 40" src="https://user-images.githubusercontent.com/29986121/95883826-bc718380-0d51-11eb-924a-0a55dda84ae7.png">

Error:
<img width="640" alt="Screen Shot 2020-10-13 at 12 39 02" src="https://user-images.githubusercontent.com/29986121/95883728-a4016900-0d51-11eb-83cd-e1a5486487a4.png">

### Steps to Reproduce

- use activateKeepAwake();

### Expected Behavior vs Actual Behavior

- Do not return any error;

**Comment by AdamJNavarro** [comment]
Hey @gbferreira, I tried to reproduce this with a project running SDK37 and a new one with SDK39 and I'm not getting an error while running on a 14.0 simulator. Can you share an actual reproducible example that we can test on our end?

Cheers,
Adam

**Comment by gbferreira** [comment]
Ook @AdamJNavarro, Thank for answer !! i'm search more informations.

**Comment by nescroft** [comment]
@AdamJNavarro @gbferreira I have the same error. I am running the code like the example. 

`import { activateKeepAwake, deactivateKeepAwake } from 'expo-keep-awake';
import React from 'react';
import { Button, View } from 'react-native';

export default class KeepAwakeExample extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Button onPress={this._activate}>Activate</Button>
        <Button onPress={this._deactivate}>Deactivate</Button>
      </View>
    );
  }

  _activate = () => {
    activateKeepAwake();
    };

  _deactivate = () => {
    deactivateKeepAwake();
    };
}`

**Comment by ovhwgr** [comment]
same issue as stated above. any updates?

**Comment by brentvatne** [comment]
@ovhwgr - no. nobody has provided a reproducible example. if you would like to, see https://stackoverflow.com/help/minimal-reproducible-example

most likely the issue you're encountering is that you are on an old sdk version where expo-keep-awake didn't expose the functions that you expect. you should pick the appropriate sdk version from the api reference section of the docs.

here's a simple working example: https://snack.expo.io/@notbrent/keep-awake-functions
