### ISSUE TITLE
[expo-local-authentication] Crash - BiometricPrompt.java - java.lang.IllegalArgumentException: FragmentActivity must not be null

### ISSUE THREAD

**Issue by vascofg** [expo/expo#10678]
### Summary of Issue 
We're getting this crash in production. It seems like FragmentActivity can be null for the given context, causing the creation of a new BiometricPrompt to crash the application.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
(running ejected), targeting iOS / Android

### Steps to Reproduce

Cannot reproduce locally, we just see this as part of our crash analytics

### Expected Behavior vs Actual Behavior

App shouldn't crash by guarding against null FragmentActivity.
I found this issue on another module, which was fixed this way: https://github.com/hieuvp/react-native-fingerprint-scanner/issues/137

**Comment by brentvatne** [comment]
it is included in sdk 40, which is in beta https://github.com/expo/expo/blame/9cf2f8a864e4d4562628e4a95439fbece0f2dd63/CHANGELOG.md#L145

https://dev.to/expo/expo-sdk-40-beta-is-now-available-59gb
