### ISSUE TITLE
Printing - API Addition

### ISSUE THREAD

**Issue by itslittlejohn** [expo/expo#1067]
Has there been any consideration of supporting iOS (AirPrint) and Android printing functionality in a unified Expo API? While potentially complex, an initial API could be fairly simple:

```js
getAvailablePrinters(printers => printers.map(({ address, name }) => {}))
print(document, onComplete)
```

This [project](https://github.com/christopherdro/react-native-print) already has basic support for this scenario as an example of what could be done. 

Is this something that others would find useful?

**Comment by nikki93** [comment]
Thanks for the suggestion! :) Made a Canny request here: https://expo.canny.io/feature-requests/p/printing-api -- feel free to upvote / comment here. We're trying to keep the GitHub issues for bugs or minor feature additions (as opposed to entire new APIs, for example) for now and are taking larger feature requests on Canny!

**Comment by itslittlejohn** [comment]
Sounds good! Thanks for pointing me over there.
