### ISSUE TITLE
[SDK 38] [expo-notification] scheduleNotificationAsync() does not trigger local notifications

### ISSUE THREAD

**Issue by abdymm** [expo/expo#10673]
### Summary of Issue 
Schedule some notifications with `scheduleNotificationAsync()` , got Return of the promise (identifier id), also when try to `getAllScheduledNotificationsAsync()` it return correct scheduled Array, But the notification doesnot show.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.18.2 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: 38.0.9 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.18.2
```

### Reproducible Demo

I also try scheduleNotificationAsync() with trigger: null, to show notification immediately and it works, but not if i set the time.
Here is my code, I just follow the documentation

```
import * as Notifications from "expo-notifications";

try {
      Notifications.setNotificationHandler({
        handleNotification: async () => ({
          shouldShowAlert: true,
          shouldPlaySound: true,
          shouldSetBadge: true,
        }),
      });
      let scheduledNotification = Notifications.scheduleNotificationAsync({
        content: {
          autoDismiss: false,
          title: "Remember to drink water!",
        },
        trigger: {
          seconds: 60,
          repeats: true,
        },
      });
      scheduledNotification.then((notification) => console.log(notification));
    } catch (error) {
      alert(error);
    }
```
 
### Steps to Reproduce
load the sample code above in expo client (managed workflow)

### Expected Behavior vs Actual Behavior
The notification doesn't show

**Comment by cruzach** [comment]
Hi! this looks just a little different than the example from the docs, so can you try running this snack- https://snack.expo.io/@charliecruzan/push-notifications? That's working for me on both iOS and Android

**Comment by abdymm** [comment]
Hi @cruzach thanks for the response, I've tried your snack expo it still doesn't work in my android device, iam using _Samsung A50_, is it because my devices?
oh ya sorry forgot to mention it doesn't work only in Android Expo Client, when i try to create a standalone app, it works. But it will be difficult if i need to generate the standalone app everytime to try out my code :( 

you have any idea whats going on?

Thank you

**Comment by abdymm** [comment]
What do you mean @cruzach ? Check `adb logcat` when running my app in expo client?

**Comment by cruzach** [comment]
yes

**Comment by abdymm** [comment]
Ok, will update here soon
Thanks!

**Comment by bakerkretzmar** [comment]
@cruzach that Snack isn't working on Android.

I have exactly the same thing locally and it's also not working on Android. `Notifications.scheduleNotificationAsync()` with a trigger of `{ seconds: 2 }` (or any trigger except `null` it would seem) doesn't do anything.

**Comment by cruzach** [comment]
@bakerkretzmar looks like there might be an issue that was introduced to snack recently, but running that same code from the snack locally in an SDK 39 project is working for me

**Comment by bakerkretzmar** [comment]
@cruzach thanks, yeah we updated to SDK 39 and this does work now.

**Comment by abdymm** [comment]
oh so it works on SDK 39? 
as @bakerkretzmar confirm it work in his end, will close this issue, and will try it later after upgrade to SDK 39
thanks @cruzach and @bakerkretzmar
