### ISSUE TITLE
[SDK 38][expo-notification] Way To Unregister/Invalidate/Unsubscibe/Revoke ExpoPushToken

### ISSUE THREAD

**Issue by abdymm** [expo/expo#10684]
### Summary of Issue 
I need to send Push notification only for logged in user  and when the user logout, i need to invalidate/unregister/unsubscribe the token, so when server doing push notification it will not send to that logged out user. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.18.2 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: 38.0.9 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.18.2
```

### Reproducible Demo

After login i just call the `registerForPushNotificationsAsync`

```
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';

export async function registerForPushNotificationsAsync(userId) {
  const expoPushToken = await Notifications.getExpoPushTokenAsync();
  await fetch('https://my-server.com/storeToken', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      userId,
      expoPushToken,
    }),
  });
}
```

### Steps to Reproduce

- User login to app (ex. userId: _1_)
- getExpoToken (ex. token: _ExponentPushToken[1234]_)
- send userId and expo token to our server,and store it to db (userId - expoTokens)
- server doing push notification to _ExponentPushToken[1234]_
- user doing logout -> _in thes step, user should be able unsubscribe the token_
- logged out
- server doing push notification to _ExponentPushToken[1234]_
- device still got the notification

### Expected Behavior vs Actual Behavior

- device should not receive the notification after the user logout VS the device still receive the notification 

we actually can create new endpoint to destroy token in our DB when user logout, but it can be bad at user experience when they trying to logout and the app cannot hit our server.

Thank you

**Comment by brentvatne** [comment]
you can just delete the token from your database. make a request to your backend when the user logs out to delete their session token (or whatever you're using for authentication) and then at the same time remove the token from your db. there isn't anything we do on the client side for this, it's up to the developer to handle it.

**Comment by abdymm** [comment]
hi @brentvatne thanks for the response, so there is no like `firebase.messaging().deleteToken()` in this expo-notification? or like fcm _topics_  so i can subscribe when login and unsubscribe when log in?

is your suggestion is a common way to handle token for the authenticated user?

**Comment by felipejh** [comment]
> you can just delete the token from your database. make a request to your backend when the user logs out to delete their session token (or whatever you're using for authentication) and then at the same time remove the token from your db. there isn't anything we do on the client side for this, it's up to the developer to handle it.

If that request fails? Do not allow user logout?

**Comment by classiebit** [comment]
We've found the solution. The reason why you wanna Unregister/Invalidate/Unsubscribe/Revoke the ExpoPushToken is that, if in case, user login with multiple accounts on the same device, then-

- When you send a notification from the server to the ExpoPushToken then the user may receive wrong notifications because multiple users now belong to the same ExpoPushToken.

And there's no way to generate user Specific ExpoPushToken like Pusher.

So the solution is:
**Keep one user belongs to only one ExpoPushToken**

And this is how we achieved that in our React Native Expo App with Laravel Backend API-

Every time user open the app or login or signup-
1. Fetch the ExpoPushToken from the device and send it to Backend API.
2. Then on the backend, check if the same ExpoPushToken belongs to any user 
3. If yes, then delete ExpoPushToken from that user
4. And add the ExpoPushToken to the current user


In this way, only the currently active user on the device will have the ExpoPushToken.

**Comment by Grohden** [comment]
> you can just delete the token from your database. make a request to your backend when the user logs out to delete their session token (or whatever you're using for authentication) and then at the same time remove the token from your db. there isn't anything we do on the client side for this, it's up to the developer to handle it.


So... a user gets offline, logout and then closes the app (which somehow schedules a request to remove that token), gets online again and only open the app like one week later...

It will keep receiving push's until it opens the app again (and that request to remove its token get released)... is there anyway to avoid that (other than using background services for only that request)?

I know this is kinda not expo problem, but I feel like this is a basic of push notifications, firebase for instance has the mentioned `.deleteToken()`, couldn't we have a similar method for expo?

**Comment by simontoulouze** [comment]
Up, we would need a way to delete/revoke the token in case he's offline when logging out please 👍

**Comment by kimkong88** [comment]
howcome unregistering notification/background task does not work? tried with urnegistering background notifiation task, and still notification comes through..

**Comment by Spharian** [comment]
> We've found the solution. The reason why you wanna Unregister/Invalidate/Unsubscribe/Revoke the ExpoPushToken is that, if in case, user login with multiple accounts on the same device, then-
> 
> * When you send a notification from the server to the ExpoPushToken then the user may receive wrong notifications because multiple users now belong to the same ExpoPushToken.
> 
> And there's no way to generate user Specific ExpoPushToken like Pusher.
> 
> So the solution is: **Keep one user belongs to only one ExpoPushToken**
> 
> And this is how we achieved that in our React Native Expo App with Laravel Backend API-
> 
> Every time user open the app or login or signup-
> 
> 1. Fetch the ExpoPushToken from the device and send it to Backend API.
> 2. Then on the backend, check if the same ExpoPushToken belongs to any user
> 3. If yes, then delete ExpoPushToken from that user
> 4. And add the ExpoPushToken to the current user
> 
> In this way, only the currently active user on the device will have the ExpoPushToken.

Thanks for the detailed answer. But what if the user logs in with different devices and same account? You managed to handle that case or you only authorize 1 expo push token per user?

**Comment by ayozebarrera** [comment]
Notifications.unregisterForNotificationsAsync() from expo do the job. In addition we remove the token from our db to keep it clean

**Comment by DhairyaMarwah** [comment]
> We've found the solution. The reason why you wanna Unregister/Invalidate/Unsubscribe/Revoke the ExpoPushToken is that, if in case, user login with multiple accounts on the same device, then-
> 
> * When you send a notification from the server to the ExpoPushToken then the user may receive wrong notifications because multiple users now belong to the same ExpoPushToken.
> 
> And there's no way to generate user Specific ExpoPushToken like Pusher.
> 
> So the solution is: **Keep one user belongs to only one ExpoPushToken**
> 
> And this is how we achieved that in our React Native Expo App with Laravel Backend API-
> 
> Every time user open the app or login or signup-
> 
> 1. Fetch the ExpoPushToken from the device and send it to Backend API.
> 2. Then on the backend, check if the same ExpoPushToken belongs to any user
> 3. If yes, then delete ExpoPushToken from that user
> 4. And add the ExpoPushToken to the current user
> 
> In this way, only the currently active user on the device will have the ExpoPushToken.

but what would happen to that user, how would that user(from which we deleted the push token) recieve notifications

**Comment by ronaldopires1982** [comment]
> Notifications.unregisterForNotificationsAsync() from expo do the job. In addition we remove the token from our db to keep it clean

How does it do it? I've tried using this method but nothing happens... And I didn't find a more robust documentation in Expo...

**Comment by ayozebarrera** [comment]
```js
// Remove the user push token saved on db
const unsubscribeToPushNotifications = async () => {
  const request = { url: '/users/device', method: 'DELETE' };
  const token = await getPushToken();
  const data = { token };
  return client({ request, data, logoutOnUnauthorized: false }).finally((response) => {
    // on the response, I call to my function to remove from the device and from Expo
    return unregisterForNotificationsAsync().then(() => response);
  });
};

//  Remove from the device and from Expo
const unregisterForNotificationsAsync = async () => {
  await removePushToken();
  return Notifications.unregisterForNotificationsAsync();
};

// Remove the token from storage
const removePushToken = () => AsyncStorage.removeItem(ASYNC_STORAGE_PUSH_TOKEN_KEY);
```

No more push notifications are received after call Notifications.unregisterForNotificationsAsync();
