### ISSUE TITLE
[WEB] ImageManipulator doesn't resize canvas when generating image

### ISSUE THREAD

**Issue by syousif94** [expo/expo#10683]
### Summary of Issue

When using ImageManipulator to edit images on web, the canvas is not resized.

### Environment

Only happens on web

### Reproducible Demo

```js
for (let i = 0; i < sliceCount; i++) {
      const originX = sliceWidth * i;

      const crop = await ImageManipulator.manipulateAsync(
        selectedImage.uri,
        [
          {
            crop: {
              originX,
              originY: 0,
              width: sliceWidth,
              height: selectedImage.height,
            },
          },
        ],
        { compress: 1, format: ImageManipulator.SaveFormat.JPEG, base64: isWeb }
      );
}
```

<img width="931" alt="broken screenshot" src="https://user-images.githubusercontent.com/8747517/96067639-d7321e00-0e5f-11eb-8ebb-dbac9493c40f.png">

**Comment by brentvatne** [comment]
pr to fix it would be welcome! please keep in mind that the code you provided is most certainly not a reproducible demo. please read more at https://stackoverflow.com/help/mcve

**Comment by syousif94** [comment]
I want to submit a pr but I just commented out these [lines](https://github.com/expo/expo/blob/8ac22c87ed85294a83780468508663775aaa4d94/packages/expo-image-manipulator/src/ExpoImageManipulator.web.ts#L243) to fix it, and I can't tell what they're intending to prevent based on the values they're receiving.

```js
    // lock sum of crop.
    // width = Math.min(width + originX, canvas.width);
    // height = Math.min(height + originY, canvas.height);

    // if (originX - width === 0 || originY - height === 0) {
    //   throw new CodedError(
    //   'ERR_IMAGE_MANIPULATOR_CROP',
    //   'Crop size must be greater than 0: ' + JSON.stringify(crop, null, 2)
    //  );
    // }
```

**Comment by markstreich** [comment]
Seems like the same issue as https://github.com/expo/expo/issues/9111 ?

I posted a minimal reproducible example:  it will attempt to crop the picked image to a centered-square:

https://snack.expo.io/@markstreich/imagemanipulator-web-crop

For example picking [this image](https://user-images.githubusercontent.com/1214573/95973361-379f6c00-0e1c-11eb-83b4-74337842fa89.png) (210x443 original) will result in:

![Screen Shot 2020-10-14 at 12 56 01](https://user-images.githubusercontent.com/1214573/95973683-a8468880-0e1c-11eb-8b28-ac02a6d15add.png)

**Comment by rSkogeby** [comment]
I have a proposed solution for this in https://github.com/expo/expo/pull/12021.

**Comment by brentvatne** [comment]
#12021 has landed and will be available in sdk 41. thanks @rSkogeby!
