### ISSUE TITLE
Custom font not working on TextInput with secureTextEntry

### ISSUE THREAD

**Issue by aikewoody** [expo/expo#10694]
### Summary of Issue
When using a custom font on a `TextInput` component that has the property `secureTextEntry` enabled the font of the placeholder doesn't change. This seems to only happen on the Android platform (tested with the device ONEPLUS A6013). Tried the following ways to load custom fonts in the project:
- expo-font with useFonts
- expo-font with loadAsync
- @expo-google-fonts/montserrat

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.14.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.38 
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ^0.14.1 => 0.14.1 
    npmGlobalPackages:
      expo-cli: 3.21.5
```

### Reproducible Demo
Link to a Snack demo: https://snack.expo.io/@marketing_nh1816/text-input-test

For the full code of the demo project see: https://github.com/aikewoody/expo-text-input-test

### Steps to Reproduce
Render a `TextInput` component with a custom font and set the property `secureTextEntry` to `true`.

### Expected Behavior vs Actual Behavior
The font of the placeholder should change but it doesn't.

Image of the rendered views:
![photo_2020-10-15 14 40 03](https://user-images.githubusercontent.com/17004429/96137542-af40ca00-0ef4-11eb-9ebb-b6ed43aafd06.jpeg)

**Comment by brooksbecton** [comment]
Seeing talk in React Native about this. 
Not sure if it is related. 

https://github.com/facebook/react-native/issues/30123

**Comment by aikewoody** [comment]
@brooksbecton Thanks for letting me know! The problem from that issue is exactly the same as mine and thus it seems like it's not related to Expo but rather React Native itself. Because of that I am closing this issue
