### ISSUE TITLE
Execution failed for task ':unimodules-react-native-adapter:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by nero2009** [expo/expo#10696]
I recently scaffolded a new expo barebone application and I get the following error when I try to build an android release bundle
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unimodules-react-native-adapter:compileReleaseKotlin'.
> Could not resolve all artifacts for configuration ':unimodules-react-native-adapter:releaseCompileClasspath'.
   > Could not find react-native-0.63.3.jar (com.facebook.react:react-native:0.63.3).
```
This is what `yarn why @unimodules/core` return:

```
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@unimodules/core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@unimodules/core@5.5.1"
info Reasons this module exists
   - "expo" depends on it
   - Hoisted from "expo#@unimodules#core"
   - Hoisted from "react-native-unimodules#@unimodules#core"
info Disk size without dependencies: "1.13MB"
info Disk size with unique dependencies: "1.15MB"
info Disk size with transitive dependencies: "1.15MB"
info Number of shared dependencies: 1
✨  Done in 1.18s.
```
react-native : 0.63.3
react-native-unimodules: ~0.11.0

**Comment by brentvatne** [comment]
this doesn't happen on new projects created with `expo init` without any changes, my guess is that you changed something in your project by accident, likely in your build.gradle: https://github.com/expo/expo/blob/master/templates/expo-template-bare-minimum/android/build.gradle. or you may not have react-native actually in your node_modules. either way, please follow the issue template to report issues in the future.
