### ISSUE TITLE
iOS can't play audio when there is no file extension in the url

### ISSUE THREAD

**Issue by localhosted** [expo/expo#10706]
## 🐛 Bug Report

I recently changed my file url to a id-based url. This caused iOS to fail playing audio with an error:

> Error: An unknown error occurred (1869640813) - The AVPlayerItem instance has failed with the error code -11800 and domain "AVFoundationErrorDomain".

Android works fine without the extension, ironically, I need a `overrideFileExtensionIOS` instead of `overrideFileExtensionAndroid`.

Both urls return a `Content-Type: audio/mpeg` header.

### Summary of Issue 
When playing an .m4a audio with no extension I get this error:

> Error: An unknown error occurred (1869640813) - The AVPlayerItem instance has failed with the error code -11800 and domain "AVFoundationErrorDomain".

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

This happens with Expo SDK 37 and so far with any iPhone model

### Steps to Reproduce

```
const sound = new Audio.Sound();
sound.loadAsync({
    uri: 'https//server.com/audiofile/download'
}) // throws error

sound.loadAsync({
    uri: 'https//server.com/audiofile/download.m4a'
}) // all good 
```

### Expected Behavior vs Actual Behavior

Audio should play

**Comment by raphaelmsr** [comment]
Agreed, same problem with SDK 40, iOS 14

**Comment by Aung-Myint-Thein** [comment]
Having the same issue on Expo-AV 8.4.0 on iOS 14.3. I am using expo unimodules in RN Cli project. Thanks for reporting.

**Comment by actuallymentor** [comment]
Also running into this. Playback fails in production with `The AVPlayerItem instance has failed with the error code 11800 and domain "AVFoundationErrorDomain"`.

**Comment by actuallymentor** [comment]
Update: I tried to first load the external uri as an `Asset` and passed that into `Audio.Sound.createAsync()` but no luck there either.

**Comment by sarevok89** [comment]
> Update: I tried to first load the external uri as an `Asset` and passed that into `Audio.Sound.createAsync()` but no luck there either.
> 
> I literally ended up "fixing" it with `if( isWeb || isIos ) return Linking.openURL( audioURI )`.

Hey, could you give some more details on how you solved this? I'm struggling with the issue with Cloudfront signed URLs without file extensions.

**Comment by actuallymentor** [comment]
> > Update: I tried to first load the external uri as an `Asset` and passed that into `Audio.Sound.createAsync()` but no luck there either.
> > I literally ended up "fixing" it with `if( isWeb || isIos ) return Linking.openURL( audioURI )`.
> 
> Hey, could you give some more details on how you solved this? I'm struggling with the issue with Cloudfront signed URLs without file extensions.

I didn't "solve" it, just triggered a file download when on web. Very bad UX but it's something. 

Sucks.

**Comment by Loquen** [comment]
Just checking in on this... Has anyone found a workable solution besides triggering a file download? 

We're getting the error `AVPlayerItem instance has failed with the error code -11850 and domain "AVFoundationErrorDomain".` which is occurring on both the iOS simulator as well as a physical iPhone. The file loads and plays fine on Android. Any help/insight would be appreciated!

**Comment by localhosted** [comment]
In my case we where expecting to always receive a .m4a , so I just hardcoded the extension to the end of the url and modifying the server route: `https://fileserver.com/files/:fileID` to `https://fileserver.com/files/:fileID*` 

You can also try to download the file and rename it, but I didn't try that

**Comment by dev-abuke** [comment]
Is there Anyone Who have found a solution for this issue, it's still occurring.

**Comment by samwilcoxon** [comment]
Yup this is still a bug

**Comment by alexlevy0** [comment]
+1
