### ISSUE TITLE
 Pod Install Error after detaching

### ISSUE THREAD

**Issue by donedgardo** [expo/expo#1070]
After detaching my app, running pod install inside the ios directory returns this:

```bash
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Pre-downloading: `ExpoKit` from `http://github.com/donedgardo/expo.git`, tag `ios/2.1.4`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `GLog` from `../node_modules/react-native/third-party-podspecs/GLog.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing Amplitude-iOS (3.14.1)
Installing Analytics (3.6.8)

[!] Error installing Analytics
[!] /usr/bin/git clone https://github.com/segmentio/analytics-ios.git /var/folders/48/ldn9nnlx7bnbg6m8ss2b84hr0000gn/T/d20171205-95902-1ficfq6 --template= --single-branch --depth 1 --branch 3.6.8

Cloning into '/var/folders/48/ldn9nnlx7bnbg6m8ss2b84hr0000gn/T/d20171205-95902-1ficfq6'...
warning: Could not find remote branch 3.6.8 to clone.
fatal: Remote branch 3.6.8 not found in upstream origin
```
https://github.com/segmentio/analytics-ios has no 3.6.8 branch.

Tried this https://github.com/donedgardo/expo/blob/master/ExpoKit.podspec#L23 with no success.

**Comment by terribleben** [comment]
Not sure why it's doing that - we [don't specify 3.6.8](https://github.com/expo/expo/blob/e227666a2e2349e85be72266b2d265e07d4d1ed6/ExpoKit.podspec#L23) anywhere. Maybe they pushed a bad release on their end. My best advice is to try nuking `Pods/**` and `Podfile.lock` (if they exist) and try pod installing again. It might also be a good idea to `pod repo update` to make sure you have the latest specs.

**Comment by donedgardo** [comment]
@terribleben 
`rm -rf Pods && rm Podfile.lock` did the trick thanks.
