### ISSUE TITLE
Fb login not working - Facebook.initializeAsync() issue from  expo-facebook

### ISSUE THREAD

**Issue by dancomanlive** [expo/expo#10709]
### Summary of Issue 
Facebook Login Error: Native method ExponentFacebook.initializeAsync expects2 arguments but received 1

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Platform: iOS

Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed

### Reproducible Demo

```
import React, { useState } from 'react';
import { StyleSheet, Text, View, Image, TouchableOpacity, ActivityIndicator } from 'react-native';
import * as Facebook from 'expo-facebook';

export default function App() {

  const [isLoggedin, setLoggedinStatus] = useState(false);
  const [userData, setUserData] = useState(null);
  const [isImageLoading, setImageLoadStatus] = useState(false);

  const facebookLogIn = async () => {
    try {
      await Facebook.initializeAsync("123456789", "myApp")
      const {
        type,
        token,
        expires,
        permissions,
        declinedPermissions,
      } = await Facebook.logInWithReadPermissionsAsync('123456789', {
        permissions: ['public_profile'],
      });
      if (type === 'success') {
        // Get the user's name using Facebook's Graph API
        fetch(`https://graph.facebook.com/me?access_token=${token}&fields=id,name,email,picture.height(500)`)
          .then(response => response.json())
          .then(data => {
            setLoggedinStatus(true);
            setUserData(data);
          })
          .catch(e => console.log(e))
      } else {
        // type === 'cancel'
      }
    } catch ({ message }) {
      alert(`Facebook Login Error: ${message}`);
    }
  }

  const logout = () => {
    setLoggedinStatus(false);
    setUserData(null);
    setImageLoadStatus(false);
  }

  return (
    isLoggedin ?
      userData ?
        <View style={styles.container}>
          <Image
            style={{ width: 200, height: 200, borderRadius: 50 }}
            source={{ uri: userData.picture.data.url }}
            onLoadEnd={() => setImageLoadStatus(true)} />
          <ActivityIndicator size="large" color="#0000ff" animating={!isImageLoading} style={{ position: "absolute" }} />
          <Text style={{ fontSize: 22, marginVertical: 10 }}>Hi {userData.name}!</Text>
          <TouchableOpacity style={styles.logoutBtn} onPress={() => logout()}>
            <Text style={{ color: "#fff" }}>Logout</Text>
          </TouchableOpacity>
        </View> :
        null
      :
      <View style={styles.container}>
        <Image
          style={{ width: 200, height: 200, borderRadius: 50, marginVertical: 20 }}
          source={{uri: "https://cdn.jpegmini.com/user/images/slider_puffin_before_mobile.jpg"}} />
        <TouchableOpacity style={styles.loginBtn} onPress={() => facebookLogIn()}>
          <Text style={{ color: "#fff" }}>Login with Facebook</Text>
        </TouchableOpacity>
      </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#e9ebee',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginBtn: {
    backgroundColor: '#4267b2',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20
  },
  logoutBtn: {
    backgroundColor: 'grey',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    position: "absolute",
    bottom: 0
  },
});
```

### Expected Behavior vs Actual Behavior

Expected behaviour is that Facebook.initializeAsync() is supposed to work because it is receiving 2 arguments. Actual behavior see Summary of Issue above.

**Comment by cruzach** [comment]
Hi! you're probably using an incompatible version of `expo-facebook` with your SDK (37 from the looks of your environment). If you install the package with `expo install expo-facebook`, the proper version will automatically be installed

**Comment by dancomanlive** [comment]
I used yarn add expo-facebook which is the same as expo install expo-facebook.

**Comment by cruzach** [comment]
in SDK 37, `expo-facebook` should be `~8.1.0`. If you run `yarn add expo-facebook`, you'll get `9.0.0`

 can provide a reproducible demo via [snack](https://snack.expo.io/)?

**Comment by Gabrielhvcardoso** [comment]
I'm using `expo@~38.0.8`, I've tried to use `expo-facebook@8.1.0`, `~8.2.1` and `9.0.0` and got the same error.

```
Facebook.initializeAsync({
  appId: "************",
  appName: "**********************",
  version: 'v2.7',
  autoLogAppEvents: false,
  domain: 'connect.facebook.net'
}).then(() => {
  // ...
})
```
Error:
```
[Unhandled promise rejection: Error: Native method ExponentFacebook.initializeAsync expects 2 arguments but received 1]
```

`node_modules\expo-facebook\build\Facebook.js`.

**Comment by cruzach** [comment]
@Gabrielhvcardoso like i said above- can you provide a reproducible demo via [snack](https://snack.expo.io/)?

**Comment by Gabrielhvcardoso** [comment]
@cruzach https://snack.expo.io/@dinamicami/amused-chip

**Comment by cruzach** [comment]
in SDK 38, that method expects two arguments: https://docs.expo.io/versions/v38.0.0/sdk/facebook/#facebookinitializeasyncappid-string--undefined-appname-string-, and you should use `expo-facebook@~8.3.0` in SDK 38

in SDK 39 that method expects one argument: https://docs.expo.io/versions/v39.0.0/sdk/facebook/#facebookinitializeasyncoptions-facebookinitializationoptions-promisevoid
you should use `expo-facebook@~9.0.0` in SDK 39

the correct version of `expo-facebook` is installed if you run `expo install expo-facebook`

**Comment by Gabrielhvcardoso** [comment]
When I run `expo install expo-facebook` in my `expo@~38.0.8`, the version installed is `~8.2.1`, even if I try to install the `~8.3.0` using `npm install expo-facebook@~8.3.0` i got the npm ERR `No matching version found for expo-facebook@~8.3.0.`

**Comment by SirPhemmiey** [comment]
Yes, same here. `8.2.1` keeps on getting installed when I use `expo install`

**Comment by jackdmarquez** [comment]
Any of you solved it?
