### ISSUE TITLE
Background Location Update not working after put app in background 

### ISSUE THREAD

**Issue by ronal2s** [expo/expo#10711]
## 🐛 Bug Report
I need to get location each X minutes, now I'm testing each 5 seconds, is working well when the app is up but when I put in background is not working anymore

### Reproducible Demo
https://pastebin.com/f4Ctcvbg
### Expected Behavior vs Actual Behavior

Expected: continue watching the log output in the console
Actual: Is not working after 1 minute in background

**Comment by brentvatne** [comment]
that's not a reproducible demo. see https://stackoverflow.com/help/mcve

**Comment by ronal2s** [comment]
> that's not a reproducible demo. see https://stackoverflow.com/help/mcve

Updated
