### ISSUE TITLE
expo-av setPositionAsync buffering to duration

### ISSUE THREAD

**Issue by Kornick** [expo/expo#10710]
When i use setPositionAsync or playFromPositionAsync sound is buffering to the end of file. But it doesn't  true, it play about 2 minutes and after is silent, but progress is continued. Same problem if i set in initialStatus positionMillis not equal 0.
In my source i use referer in headers. Maybe there is problem.
If i use source without referer for another source i have success. 
my log:
`_onPlaybackStatusUpdate -> status  {"androidImplementation": "SimpleExoPlayer", "didJustFinish": false, "durationMillis": **2324819**, "isBuffering": true, "isLoaded": true, "isLooping": false, "isMuted": false, "isPlaying": true, "playableDurationMillis": 1662010, "positionMillis": 1582451, "progressUpdateIntervalMillis": 500, "rate": 2, "shouldCorrectPitch": true, "shouldPlay": true, "uri": "/9/3/7/4/track-1.mp3", "volume": 1}`
`[Sat Oct 17 2020 24:38:31.451]  LOG      _onPlaybackStatusUpdate playableDurationMillis=1700907 positionMillis=1582830
[Sat Oct 17 2020 24:38:31.768]  LOG      _onPlaybackStatusUpdate playableDurationMillis=**2324819** positionMillis=1583464`

**Comment by byCedric** [comment]
Hi @Kornick, thanks for the issue report. But, to help you, we need a [small repro](https://stackoverflow.com/help/minimal-reproducible-example). With that, we can investigate and resolve your issue. Could you provide this?

**Comment by Kornick** [comment]
Hi @byCedric, i found out, that server use a HTTP pseudo streaming. How can i change Media types for exoplayer?

**Comment by Kornick** [comment]
hi, i suppose that problem in headers, how can i get headers

**Comment by Kornick** [comment]
i got headers, and its is ok. My code below.
in SimpleExoPlayerData.java add new inner class
`class EventLogger2 extends EventLogger implements AnalyticsListener {
    
    public EventLogger2() {
      super(null);
    }
  
    @Override
    public void onLoadStarted(EventTime eventTime, LoadEventInfo loadEventInfo, MediaLoadData mediaLoadData) {
      Map <String,List<String>> responseHeaders = loadEventInfo.responseHeaders;
      Log.d("EventLogger", "onLoadStarted" + responseHeaders.toString());
      // for(Map.Entry<String,List<String>> e: responseHeaders.entrySet())
      // for(String key: e.getValue()) Log.d("EventLogger", "onLoadStarted2" + key + ":" + e.getKey());
      if (mSimpleExoPlayer != null) Log.d("EventLogger", String.valueOf(mSimpleExoPlayer.getBufferedPosition()));
    }

    @Override
    public void onLoadCompleted(EventTime eventTime, LoadEventInfo loadEventInfo, MediaLoadData mediaLoadData) {
      Map <String,List<String>> responseHeaders = loadEventInfo.responseHeaders;
      Log.d("EventLogger", "onLoadCompleted" + responseHeaders.toString());
      // for(Map.Entry<String,List<String>> e: responseHeaders.entrySet())
      //   for(String key: e.getValue()) Log.d("EventLogger", "onLoadCompleted" + key + ":" + e.getKey());
      if (mSimpleExoPlayer != null) Log.d("EventLogger", String.valueOf(mSimpleExoPlayer.getBufferedPosition()));
    }

    @Override
    public void onLoadCanceled(EventTime eventTime, LoadEventInfo loadEventInfo, MediaLoadData mediaLoadData) {
      Map <String,List<String>> responseHeaders = loadEventInfo.responseHeaders;
      Log.d("EventLogger", "onLoadCanceled" + responseHeaders.toString());
      if (mSimpleExoPlayer != null) Log.d("EventLogger", String.valueOf(mSimpleExoPlayer.getBufferedPosition()));
    }

    @Override
    public void onBandwidthEstimate(EventTime eventTime, int totalLoadTimeMs, long totalBytesLoaded, long bitrateEstimate) {
      Log.d("EventLogger", "onBandwidthEstimate totalLoadTimeMs:" + String.valueOf(totalLoadTimeMs) + " totalBytesLoaded:" + String.valueOf(totalBytesLoaded) + " bitrateEstimate:" + String.valueOf(bitrateEstimate));
      if (mSimpleExoPlayer != null) Log.d("EventLogger", String.valueOf(mSimpleExoPlayer.getBufferedPosition()));
    }
  }`

`@Override
  public void load(final Bundle status, final LoadCompletionListener loadCompletionListener) {
mSimpleExoPlayer.addAnalyticsListener(new EventLogger2());
}`

After that i got headers and relize, that buffered position is correct. But when i started play, BufferedPosition stand like duration. Solution for a while a don't have.

**Comment by Kornick** [comment]
Hi @byCedric , i created an example for you. [https://snack.expo.io/@kornick/uplifting-tortilla](url)
playableDurationMillis is changed without buffering. It's play about 1,5 minutes and then is silent...

**Comment by Kornick** [comment]
i found my 206 Partial Content is closed immediately after receiving data, how to say that data is partial and do reconnect.
received headers:
`{accept-ranges=[bytes], cf-cache-status=[DYNAMIC], cf-ray=[5e5dc34c8b512deb-KBP], cf-request-id=[05ee7863d900002debff223000000001], content-length=[1048576], content-range=[bytes 5981845-7030420/18618657], content-type=[audio/mpeg], date=[Wed, 21 Oct 2020 20:35:03 GMT], expect-ct=[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"], nel=[{"report_to":"cf-nel","max_age":604800}], report-to=[{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=132&lkg-time=1603312504"}],"group":"cf-nel","max_age":604800}], server=[cloudflare]}`
