### ISSUE TITLE
Able to multi language on app.json?

### ISSUE THREAD

**Issue by watanabeyu** [expo/expo#1071]
Hi!  
I'm developing app multi language by use [ex-react-native-i18n](https://github.com/xcarpentier/ex-react-native-i18n).  
  
So Multi language on code is ok, but app name or any other settings not multi language...  
example, ios standalone app screen name, *UsageDescription on infoplist, etc...  
  
Do you have plans multi language on app.json?

**Comment by tcdavis** [comment]
Please request / look for new and upcoming features at https://expo.canny.io/feature-requests/
