### ISSUE TITLE
[Pressable] [SDK 39] Slow UI feedback when pressing Touchables and Pressable

### ISSUE THREAD

**Issue by Rafatcb** [expo/expo#10715]
## 🐛 Bug Report

I created a [post in Expo Forum](https://forums.expo.io/t/touchable-and-pressable-slow-ui-feedback-on-expo-sdk-39/44304/2) before creating this issue, so feel free to read it.

### Summary of Issue 

`Touchable` and `Pressable` components have a small delay before showing a "pressed state" UI feedback.

This is an issue from React Native, introduced in https://github.com/facebook/react-native/commit/49b2a6e9cd95b74375f51fda87b87430073ec20e (July 13) and fixed in 
https://github.com/facebook/react-native/commit/86ffb9c41e033f59599e01b7ad016706b5f62fc8 and https://github.com/facebook/react-native/commit/a6395d5406a297d06619e0f60afdfb3e6651a1af (Sep 10).

Please, see this issue https://github.com/facebook/react-native/issues/29376 for more details about it and the [v63.0.3 changelog](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0633). 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

I tested it only on Android 10.

```
Expo CLI 3.28.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6821437
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.16
    Expo Workflow: managed
```

### Reproducible Demo

I created reproducible demos ([SDK 38](https://snack.expo.io/@rafatcb/expo-sdk-38---touchable) and [SDK 39](https://snack.expo.io/@rafatcb/expo-sdk-39---touchable-has-a-delay)). The delay is easily noticeable if `onPress` is undefined, but you can notice that when you touch the Menu button in SDK 38, it starts showing the Ripple then opens the menu; in SDK 39, both occurs at the same time.

In my app, all Touchables/Pressables have `onPress` defined.
 
### Steps to Reproduce

1. Create a Touchable (or Pressable) with a *pressed state* (Ripple, shadow, anything)
2. Touch it

### Expected Behavior vs Actual Behavior

The ripple animation should start immediately on press as in Expo SDK 38.

| Expected: Expo SDK 38 | Actual: Expo SDK 39 |
| ------------------------- | ---------------------- |
| ![expo-sdk-38](https://user-images.githubusercontent.com/26308880/96043812-e73d0400-0e45-11eb-98cf-17b13c2e2585.gif) | ![expo-sdk-39](https://user-images.githubusercontent.com/26308880/96043823-ec9a4e80-0e45-11eb-95d3-6ed44c99a41b.gif) |

**Comment by brentvatne** [comment]
hi there! we pulled https://github.com/expo/react-native/commit/380487fbba461761d5c47ede791f08461f67b7fc into our most recent release and, which was *supposed* to fix this for touchable* components (and it does in the case i tested, with touchableopacity on ios) but it seems that is not the case in this particular situation you're encountering. i can cherry-pick this commit at some next week, but my recommendation for now is to use patch-package to pull it in to your project.

**Comment by brentvatne** [comment]
you can now update your react-native version to `https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz` to include facebook/react-native@86ffb9c and facebook/react-native@a6395d5 :)

**Comment by Rafatcb** [comment]
Thank you, @brentvatne ! Expo team is doing an awesome work 👊🏼🚀

**Comment by witherBattler** [comment]
Is this fixed in the current version of expo? I'm having the same/a similar issue in expo version 47.

**Comment by brentvatne** [comment]
@witherBattler - this was never really an "issue with expo" but rather a regression upstream, which was resolved a long time ago. if you are experiencing something similar to this, please create a new issue and provide a minimal reproducible example

**Comment by witherBattler** [comment]
Fair enough, I didn't mean to say anything negative about expo. I just wanted to know if expo already started using the version of react native that fixed the bug.
