### ISSUE TITLE
Expo Image Picker Build Error: PendingPromise.kt

### ISSUE THREAD

**Issue by Johnsonzhangc** [expo/expo#10713]
### Summary of Issue 
A react-native init project using expo-image-picker, when building android, this error occurs: 
```
......./expo-image-picker/android/src/main/java/expo/modules/imagepicker/PendingPromise.kt: (12, 5): This type has a constructor, and thus must be initialized here
```

iOS works fine

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @sentry/react-native: ^1.8.2 => 1.8.2 
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.0 => 0.63.0 
    npmGlobalPackages:
      expo-cli: 3.11.9

### Steps to Reproduce
"react-native-unimodules": "^0.10.1"
"expo-image-picker": "^9.1.1"

**Comment by cruzach** [comment]
what's the resolved version of `react-native-unimodules` in your project? you can run `yarn why react-native-unimodules` to find out, it should be v 0.11.0

when I had v 0.10.0 installed, I got the same error you did

**Comment by dorthwein** [comment]
I can confirm upgraded to `react-native-unimodules` `v0.11.0` fixed this issue for me.
@Johnsonzhangc

**Comment by Johnsonzhangc** [comment]
Thanks @dorthwein & @cruzach .

I downgrade the image picker version to 8.3.0, it works on both platforms.
