### ISSUE TITLE
[nextjs] SSR failing due to dependency on `badgin` in `expo-notifications`

### ISSUE THREAD

**Issue by davitykale** [expo/expo#10724]
### Summary of Issue 
SSR in Expo + Next.js application failing due to `ReferenceError: window is not defined` which seems to be tied to importing the `badgin` library in `ExponentNotifications.web.js`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Web (with Next.js)
```
  Expo CLI 3.28.0 environment info:
    System:
      OS: macOS 11.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 23
        Build Tools: 23.0.1
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.0
    Expo Workflow: managed
```

**Comment by byCedric** [comment]
Hi @davitykale! Thanks for the issue report. I opened a fix that should block usage of this module on SSR (NextJS). In the meantime, you can include this fix in your repo [by using `patch-package`](https://www.npmjs.com/package/patch-package). 

I've created an example repo with the [workaround here](https://github.com/byCedric/expo-issue-10724-workaround). You can try this out too, the most important part of this repo [is the patch file](https://github.com/byCedric/expo-issue-10724-workaround/commit/ff8ea03c2a8b8278304262042da4db82e97084bd#diff-bd61f2b257fe1a4ede097be4923a7577d22574e6afdf00d921fbe0a4208f737e). You can copy this locally to include the patch until we release a fix for this!

Hope this helps!
