### ISSUE TITLE
add animation for splash screen ?

### ISSUE THREAD

**Issue by bhram** [expo/expo#1072]
how can i add animation for my splash screen when showing up ?

can i put custom component instead ?

**Comment by tcdavis** [comment]
The splash screen is displayed while your code is being loaded. If you are using AppLoading, you could replace with some other component, but otherwise the only configuration we offer is in the app.json

**Comment by cristii** [comment]
@tcdavis hi, how can I replace the splash screen with other components? I've searched the docs and the [source code](https://github.com/expo/expo-sdk/blob/a4911c44b6b88a059f0a7e8bf09eeefee286a7b6/src/launch/AppLoading.js) and I can't seem to figure it out. My goal is to render a View and Text component on the splash screen
