### ISSUE TITLE
WebView err_cache_miss

### ISSUE THREAD

**Issue by baixiaoxiaobai** [expo/expo#10728]
### Summary of Issue 
WebView not work 
Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_CACHE_MISS",
  "loading": false,
  "target": 3,
  "title": "",
  "url": "https://m.xoyo.com/#/signin",
}

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.27.14 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Steps to Reproduce
expo start

### Expected Behavior vs Actual Behavior
There is a problem with Android 5, but not with react-native-webview alone

**Comment by AdamJNavarro** [comment]
Hey @baixiaoxiaobai, when creating an issue please follow the issue template that we provide. It's there to help you as much as it is to help us. Without more information and a reproducible example provided, we won't be able to help you.

If you can, please edit your issue and provide the necessary parts and then we will revisit this issue.

Cheers,
Adam

**Comment by baixiaoxiaobai** [comment]
I've updated the issue and I've seen a lot of people making this error, but there seems to be no solution @AdamJNavarro

**Comment by brentvatne** [comment]
I simplified the mcve here: https://snack.expo.io/@notbrent/brave-waffle

Direct link to try this on Android 5.1: https://appetize.io/embed/xc1w6f1krd589zhp22a0mgftyw?autoplay=false&debug=true&device=nexus5&deviceColor=black&embed=true&launchUrl=exp:%2F%2Fexpo.io%2F@notbrent%2Fbrave-waffle%2BdTyFbD3fc&orientation=portrait&screenOnly=false&xDocMsg=true&xdocMsg=true&params=%7B%22EXKernelLaunchUrlDefaultsKey%22:%22exp:%2F%2Fexpo.io%2F@notbrent%2Fbrave-waffle%2BdTyFbD3fc%22,%22EXKernelDisableNuxDefaultsKey%22:true%7D&scale=75&osVersion=5.1

That said, this is a duplicate of https://github.com/expo/expo/issues/6665 so let's just discuss it there
