### ISSUE TITLE
Can't Use React Hooks

### ISSUE THREAD

**Issue by ferryhinardi** [expo/expo#10721]
I can't use react hooks, showing this error.
<img width="363" alt="Screen Shot 2020-10-18 at 22 31 07" src="https://user-images.githubusercontent.com/5007428/96372570-a02a7800-1191-11eb-95d0-d0e400002a9b.png">

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
This is my package.json:
```
"dependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-transform-flow-strip-types": "^7.4.0",
    "@babel/plugin-transform-runtime": "7.0.0",
    "@babel/runtime": "^7.0.0-beta.55",
    "babel-preset-expo": "^8.3.0",
    "concurrently": "^3.6.1",
    "core-js": "^3.2.1",
    "expo": "^39.0.0",
    "expo-react-native-adapter": "^3.0.1",
    "react": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "react-native-gesture-handler": "~1.7.0",
    "whatwg-fetch": "2.0.4"
},
"devDependencies": {
    "@storybook/addon-actions": "5.2.1",
    "@storybook/addon-knobs": "5.2.1",
    "@storybook/addon-ondevice-knobs": "5.2.1",
    "@storybook/addon-storyshots": "5.2.1",
    "@storybook/addons": "5.2.1",
    "@storybook/react-native": "5.2.1",
    "appr": "^2.0.0",
    "exp": "^56.0.0",
    "jest-expo": "^39.0.0",
    "lolex": "^3.0.0",
    "prop-types": "^15.6.1",
    "react-dom": "16.13.1",
    "react-native-storybook-loader": "^2.0.2",
    "react-test-renderer": "16.13.1"
},
```

**Comment by byCedric** [comment]
Hi @ferryhinardi, you should be able to use hooks in Expo and React Native projects. In the error you post, you can see that it's actually using the `useLayoutComponents` hook. Could you share some of your code where you use the failing hook(s)?

Also, looking at your dependencies, it looks like your devDependency `exp` is a bit outdated. I wouldn't use this one, but the `expo-cli` instead. 😄
