### ISSUE TITLE
Failed to construct transformer:  Error: Failed to start watch mode. error

### ISSUE THREAD

**Issue by RaviBlock8** [expo/expo#10727]
### Summary of Issue 
Whenever I start my react-native application it gives following error

Failed to construct transformer:  Error: Failed to start watch mode.
    at Timeout._onTimeout (D:\Projects\rbb-demo\packages\client\node_modules\jest-haste-map\build\index.js:1059:24)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
ERROR
NaN:NaN
Error: Failed to start watch mode.
    at Timeout._onTimeout (D:\Projects\rbb-demo\packages\client\node_modules\jest-haste-map\build\index.js:1059:24)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.28.0 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Users\Acer\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    Expo Workflow: managed

### Steps to Reproduce
expo start

### Expected Behavior vs Actual Behavior
When I scan the QR code from android phone , it waits for few minutes and then shows this error

**Comment by AdamJNavarro** [comment]
Hey @RaviBlock8,

It looks like this error is being thrown due to watchman not being able to start watch mode. Can you make sure watchman is installed on your system? Also, have you tried creating a vanilla React Native project and seeing if that works?

Cheers,
Adam

**Comment by RaviBlock8** [comment]
hey @AdamJNavarro  , 
I did went to official guide for watchman installation ,and they do mention about beta version of watchman for windows, but can't find one in their download section.
It will be helpful if you can help with this.

**Comment by RaviBlock8** [comment]
@AdamJNavarro  , yup it solved the issue , many thanks

**Comment by gildniy** [comment]
> hey @AdamJNavarro , I did went to official guide for watchman installation ,and they do mention about beta version of watchman for windows, but can't find one in their download section. It will be helpful if you can help with this.

The latest version to be installed can be found here:
https://github.com/facebook/watchman/actions/workflows/getdeps_windows.yml
