### ISSUE TITLE
Branch.io ad attribution broken

### ISSUE THREAD

**Issue by hixus** [expo/expo#10720]
### Summary of Issue 

Our branch.io attribution broke after updating to sdk 39. Seems that the AAID was disabled in this pr https://github.com/expo/expo/pull/10204/commits/aa4a9e950eb9a5c9f9594e052e49a58ff309cda9#diff-281ded35b124f5160d0a57e47e521ee6f49f233933e091a0d33f3fd42a74abc8R63

However it doesn't say how to get it back? According to Branch helpdesk "Device identifiers i.e. AAID (for android) and IDFA (for iOS) are mandatory data field values which are requried for a deterministic attribution for your quick links and ad links."

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Managers:
      CocoaPods: 1.9.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.14
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed

**Comment by hixus** [comment]
@sjchmiela  Would have really liked mention about this on the breaking changes https://github.com/expo/expo/blob/master/CHANGELOG.md#-breaking-changes-1 like with expo-analytics-amplitude
 and expo-analytics-segment

Put's us developers in bit difficult position having to eject without planning.

**Comment by aarshaw** [comment]
@hixus Was there a resolution for this? Did you end up ejecting?
