### ISSUE TITLE
Expo SDK 23 doesn't support KeyboardAvoidingView/KeyboardAwareScrollView - TextInput hidden when keyboard visible

### ISSUE THREAD

**Issue by ceefour** [expo/expo#1073]
Original issue: https://github.com/GeekyAnts/NativeBase/issues/1418#issuecomment-349586972

## package.json

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^6.2.1",
    "expo": "^23.0.0",
    "firebase": "^4.6.2",
    "native-base": "^2.3.3",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
    "react-native-datepicker": "^1.6.0",
    "react-navigation": "^1.0.0-beta.19",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "jest-expo": "^23.0.0"
  }
}
```

## Expected behaviour

With `KeyboardAwareScrollView` / `Content` (from native-base, etc.). 

1. Auto-Scrolling should happen when I type an input on lower half of screen.
2. It is possible to scroll manually to make the input visible.

## Actual behaviour

1. No auto-scrolling happens. Both with Asus ZenUI keyboard and Google Gboard.
2. It's not possible to scroll manually to make the input visible. (see below for workaround)

Wrapping the Input/Item with `KeyboardAvoidingView` does not work either.

Input:

![image](https://user-images.githubusercontent.com/24123/33575817-6feef762-d970-11e7-876a-8a1928521042.png)

is obscured:

![image](https://user-images.githubusercontent.com/24123/33575776-525cc490-d970-11e7-8392-765184368f2e.png)

## Steps to reproduce (code snippet or screenshot)

Test case : https://github.com/ceefour/keyboardavoider

```xml
      <Container>
        <Content>
          <Form>
             ...other <Item>s...
            <Item stackedLabel>
              <Label>Pekerjaan (lainnya)</Label>
              <Input value={this.state.userProfile.employment_other}
                onChangeText={(text) => this.setState({userProfile: {...this.state.userProfile, employment_other: text}})}/>
            </Item>
          </Form>
        </Content>
      </Container>
```

Tried using: `<Content contentContainerStyle={{flex: 1}}>` but made the content squashed.

Using @Andr3wHur5t's `<KeyboardSpacer/>` (as @samarhaider suggests https://github.com/GeekyAnts/NativeBase/issues/534#issuecomment-344689283) only allows scrolling **manually** when keyboard is visible. However, auto-scroll still does not occur even with KeyboardSpacer :

![videotogif_2017 12 05_04 26 44](https://user-images.githubusercontent.com/24123/33577211-ea990f9e-d974-11e7-900d-a60077e2f6e8.gif)

## Is the bug present in both ios and android or in any one of them?

Only tested with Android 7.0 and Expo SDK 23. Issue did not occur with expo 19.0.1.

**Comment by tcdavis** [comment]
Thanks @ceefour, sounds like geekyAnts thinks this is a regression on our side some time since sdk 19?  It would help if you could isolate the particular SDK version when the issue starts occurring.

**Comment by ceefour** [comment]
@tcdavis I was unable to test with older versions due to various build/runtime errors I'm not familiar with.

But here's a very stripped down test case with only built-in KeyboardAvoidingView, no native-base or external stuff : https://github.com/ceefour/keyboardavoider2

**Comment by ide** [comment]
@ceefour Would you happen to know if this is a problem specifically with Expo or does it affect bare React Native too? KeyboardAvoidingView sometimes has problems with React Native, that could be related.

**Comment by ide** [comment]
@ceefour Do you know if this is a problem specific to Expo or does it affect bare React Native too? The KeyboardAvoidingView has some issues with React Native, which could be affecting Expo here.

**Comment by ceefour** [comment]
@ide Unfortunately I'm not sure. My first exposure to React Native is because of Expo (do you think that's a good or bad thing? :D ) I haven't even used CRNA, much less bare React Native.

**Comment by mario-subotic** [comment]
I'm having exactly the same issue. It only happens on Android. I'm also using Expo and I have tried experimenting with different versions of Expo and Native Base. The weirdest part is, when I download the Kitchen Sink App it works, I even tried changing the npm versions of `react-native`, `expo`, `native-base` and others to mirror my own project. I rebuilt and run and it always works in the Kitchen Sink app no matter which versions I try. But my own project doesn't want to work. 

I even copied my own code with all the styles (thinking it could be a styling issue) to the Kitchen Sick app and again it works fine, but it doesn't work in my project. I've reached a point where the two are almost identical in package.json and mine still doesn't work. I tried replacing `<Content />` with `<KeyboardAwareScrollView />` and still no luck. I really don't know what else to try. If anyone has any ideas I would be very happy to try. 

Here are my package.json dependencies as of now

``` {
  "dependencies": {
    "color": "^2.0.1",
    "expo": "^23.0.0",
    "firebase": "^4.4.0",
    "immutable": "^3.8.1",
    "native-base": "^2.3.5",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
    "react-native-markdown-view": "^1.1.4",
    "react-native-progress": "^3.4.0",
    "react-navigation": "^1.0.0-beta.19",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "eslint-config-rallycoding": "^3.2.0"
  }
}
  ```

**Comment by mario-subotic** [comment]
I was able to reproduce the issue on this Snack. 

https://snack.expo.io/r1A0kaj-M

**Comment by ceefour** [comment]
THANK YOU @mario-subotic ! Your hard work is really appreciated!

**Comment by mauroporrasp** [comment]
Thanks, I'm having the same issue.

**Comment by brentvatne** [comment]
add something like this to your app.json if you want this component to work with default props:

```
    "androidStatusBar": {
      "backgroundColor": "#C2185B",
    },
```

that makes it work as expected. the reason is that the status bar is translucent by default in expo but not in react-native. if someone wants to add more info to docs that would be appreciated!

![keyboard](https://user-images.githubusercontent.com/90494/34588600-b9fb9bb2-f162-11e7-9d61-a372d8af420a.gif)

**Comment by jreason** [comment]
@brentvatne 

I've never been able to get KeyboardAvoidingView to work with CRNA on iOS or Android for some reason? Even with a blank app and applying your suggested fix using the latest version of Expo 24
I have been using actual devices and not the emulator.
react-native-keyboard-aware-scroll-view seems to work fine though!
Can you share your code for the demo?

**Comment by mauroporrasp** [comment]
@brentvatne It works, thank you! I still don't get how they are related. I mean, why setting the color makes it work? Thank you again.

**Comment by ceefour** [comment]
@brentvatne @mauroporrasp Yeah, makes me wondering: what if the status bar is hidden entirely, i.e. a full screen app ?

**Comment by SimonVuong** [comment]
does the app need to be ejected for this to work?

**Comment by isaachinman** [comment]
@brentvatne That seems to work great on Android. However, absolutely nothing happens on iOS as far as I can tell, no position adjustment for keyboard events. Is there a similar trick to get this to work on iOS?

**Comment by SimonVuong** [comment]
for anyone who's looking for a sample code... the trick is to actually **not** use keyboardavoidingview

`
      <Container style={styles.background}>
        <Content>
          <Form>
            <Item floatingLabel>
              <Label>Email</Label>
            <Input value={this.state.email} onChangeText={email => this.setState({email})}/>
        </Item>
          </Form>
        </Content>
      </Container>
`

**Comment by vsakos** [comment]
I got it working with

    <KeyboardAvoidingView behavior="padding">
        ...
    </KeyboardAvoidingView>

**Comment by kapil708** [comment]
can you please give me a example of it i try to work with the following but it not working.
 here is the code

`<ScrollView>
                <Spinner visible={this.state.isLoading} textContent={"Loading..."} textStyle={{ color: '#FFF' }} />
                {/* <Loader loading={this.state.isLoading} /> */}
                
                    <Form style={styles.ContainerStyle}>
                    <KeyboardAvoidingView behavior="padding">
                        <Item inlineLabel style={!this.state.validateGiftCardNo ? styles.error : null}>
                            <Label style={styles.labelStyle}>Gift Card No *</Label>
                            <Input
                                style={styles.textStyle}
                                value={this.state.giftcardno}
                                onChangeText={(text) => {
                                    this.setState({ giftcardno: text })
                                    this.validateForm('giftcardno', text)
                                }}
                                keyboardType="phone-pad"
                                ref="one"
                                onSubmitEditing={() => this._focusNextField('two')}
                                returnKeyType={"next"}
                                blurOnSubmit={false}
                            />
                        </Item>
                        <Item inlineLabel style={!this.state.validateName ? styles.error : null}>
                            <Label style={styles.labelStyle}>FirstName *</Label>
                            <Input
                                style={styles.textStyle}
                                ref={(input) => { this.secondTextInput = input; }}
                                value={this.state.firstname}
                                onChangeText={(text) => {
                                    this.setState({ firstname: text })
                                    this.validateForm('firstname', text);
                                }}
                                ref="two"
                                onSubmitEditing={() => this._focusNextField('three')}
                                returnKeyType={"next"}
                                blurOnSubmit={false}
                            />
                        </Item>
                        <Item inlineLabel>
                            <Label style={styles.labelStyle}>Middle Name</Label>
                            <Input style={styles.textStyle}
                                value={this.state.middlename}
                                onChangeText={(text) => this.setState({ middlename: text })}
                                ref="three"
                                onSubmitEditing={() => this._focusNextField('four')}
                                returnKeyType={"next"}
                                blurOnSubmit={false} />
                        </Item>
                        <Item inlineLabel>
                            <Label style={styles.labelStyle}>Last Name</Label>
                            <Input style={styles.textStyle}
                                value={this.state.lastname}
                                onChangeText={(text) => this.setState({ lastname: text })}
                                ref="four"
                                onSubmitEditing={() => this._focusNextField('five')}
                                returnKeyType={"next"}
                                blurOnSubmit={false} />
                        </Item>
                        <Item inlineLabel style={!this.state.validateMobile ? styles.error : null}>
                            <Label style={styles.labelStyle}>Mobile No *</Label>
                            <Picker textStyle={styles.textStyle} style={{ width: (Platform.OS === 'ios') ? undefined : 130, color: '#fff' }}
                                mode="dropdown"
                                placeholder="Code"
                                selectedValue={this.state.phonecode}
                                onValueChange={(value) => this.setState({ phonecode: value })} >
                                {this.setPhoneCodeToList()}
                            </Picker>
                            <Input style={styles.textStyle}
                                value={this.state.mobileno}
                                onChangeText={(text) => {
                                    this.setState({ mobileno: text })
                                    this.validateForm('mobileno', text);
                                }}
                                keyboardType="phone-pad"
                                ref="five"
                                onSubmitEditing={() => this._focusNextField('six')}
                                returnKeyType={"next"}
                                blurOnSubmit={false}
                            />
                        </Item>
                        <Item inlineLabel style={!this.state.validateEmail ? styles.error : null}>
                            <Label style={styles.labelStyle}>Email</Label>
                            <Input style={styles.textStyle}
                                value={this.state.emailaddress}
                                onChangeText={(text) => {
                                    this.setState({ emailaddress: text })
                                    this.validateForm('email', text);
                                }}
                                ref="six"
                                onSubmitEditing={() => this._focusNextField('seven')}
                                returnKeyType={"next"}
                                blurOnSubmit={false} />
                        </Item>
                        <Item inlineLabel>
                            <Label style={styles.labelStyle}>Address</Label>
                            <Input style={styles.textStyle}
                                value={this.state.address}
                                onChangeText={(text) => this.setState({ address: text })}
                                ref="seven"
                                onSubmitEditing={() => this._focusNextField('eight')}
                                returnKeyType={"next"}
                                blurOnSubmit={false} />
                        </Item>
                        <Item inlineLabel style={!this.state.validatePincode ? styles.error : null}>
                            <Label style={styles.labelStyle}>Pincode</Label>
                            <Input style={styles.textStyle}
                                value={this.state.pincode}
                                onChangeText={(text) => {
                                    this.setState({ pincode: text })
                                    this.validateForm('pincode', text);
                                }}
                                ref="eight"
                                keyboardType="phone-pad"
                            />
                        </Item>
                        <View style={styles.imagePickerStyle}>
                            <TouchableOpacity onPress={this.show.bind(this)}>
                                <Text style={styles.imagePickerButton}>Pick Image</Text>
                            </TouchableOpacity>
                            {img}
                        </View>
                        <Button block
                            style={{ margin: 25, marginTop: 15 }}
                            onPress={() => this.handlePress()}>
                            <Text>Submit</Text>
                        </Button>
                        </KeyboardAvoidingView>
                    </Form>
                
            </ScrollView>`

**Comment by eslambasher** [comment]
@kapil708 you can do it like that, it's work for me
` <Container style={styles.background}>
        <Content>
          <Form>
           <KeyboardAvoidingView behavior="padding">
            <Item floatingLabel>
              <Label>Email</Label>
              <Input value={this.state.email} onChangeText={email => this.setState({email})}/>
            </Item>
          </Form>
        </KeyboardAvoidingView>
        </Content>
      </Container>`

**Comment by jhonathanaguiar** [comment]
@brentvatne  your solution doesn't work anymore :(. I thought that it was because I upgrade from expo sdk 28 to 29 but probably it's not this because I tried downgrade to sdk 28 and stills not working. What's changed in the build of Android apk? One important information, in expo app the solution still works, but it doesn't when I generate the apk

**Comment by gerardo15** [comment]
@jhonathanaguiar  did you ever solve this?, KeyboardAvoidingView works on expo but not in the generated APK

**Comment by samarhaider** [comment]
Yes, Put Content inside KeyboardAwareScrollView 
<Container>
       
        <KeyboardAwareScrollView
            extraScrollHeight={100}
            enableOnAndroid={true} 
            keyboardShouldPersistTaps='handled'
            >
            <Content padder >
              <Logo message={message} />
              <Form style={{ margin: 20 }}>
                <Item >
                  {/* <Icon active name='md-call' />                */}
                  <Input
                    style={{color: "#FFF", paddingLeft: 40}} 
                    placeholder="Enter your email address"
                    value={this.props.email}
                    onChangeText={this.onemailChanged}
                    keyboardType="email-address"
                    disabled={this.props.loading}
                    autoCorrect={false}
                    autoCapitalize={'none'}
                    returnKeyType={'done'}
                  />
                </Item>

              </Form>
            </Content>
          </KeyboardAwareScrollView>   
      </Container>

**Comment by gerardo15** [comment]
@samarhaider How does this work? if you look at <Content> from Native Base, it is a  KeyboardAwareScrollView

so basically you are placing a KeyboardAwareScrollView inside a KeyboardAwareScrollView?

**Comment by chriswait** [comment]
Still investigating, but just in case my experience helps someone in the future:

I found that if I was using NativeBase's `<Content>` then this behaviour did not work as I expected on Android (i.e the keyboard often covered the input I was interacting with). But, if I swapped it out for `<KeyboardAwareScrollView enableOnAndroid>`then everything worked as expected.

I'm not sure why nativebase ("cross-platform UI components") doesn't include the `enableOnAndroid` prop which makes this work on Android. I wondered if this was because the default expectation on Android is for the platform to pan the contents of the window (which in most cases probably results in the input being visible without any need to listen to keyboard events in the `<ScrollView>`).

However, as I understand it, `expo eject` produces an Android project with a manifest configured with ` android:windowSoftInputMode="adjustResize"`. This means the `<ScrollView>` will be resized, but I'm not experienced enough with react-native and/or Android to predict whether that will trigger any scrolling.

If it _doesn't_, this probably explains why using a `<Content>` on an Expo project will result in the keyboard covering inputs on Android - the `<ScrollView>` isn't panning, and `<KeyboardAwareScrollView>` isn't enabled.

@gerardo15 I suspect this is why nesting `<KeyboardAwareScrollView>`s "works" in the example provided by @samarhaider above - they're including `enableOnAndroid`, which `<Content>` does not.

P.P.S @SupriyaKalghatgi I'd love someone who probably actually understands the complexity here to check my understanding 😄

**Comment by pandapaul** [comment]
Rather than wrapping `<Content />` in a `<KeyboardAwareScrollView />`, I think you can simply add the `enableOnAndroid` prop to the `<Content />`.  NativeBase passes it along.  Side note:  `androidStatusBar` option in app.json didn't solve it for me.  I'm on expo 32 currently.

**Comment by allan-simon** [comment]
@pandapaul  awesome, your tricks works , had i been looking for this issue one hour earlier I wouldn't have seen your response :)
