### ISSUE TITLE
Permissions.getAsync() undetermined after enabling on iOS

### ISSUE THREAD

**Issue by nathanwaters** [expo/expo#10735]
### Summary of Issue

Permissions.getAsync(Permissions.NOTIFICATIONS) returns undetermined on iOS after denying initial prompt, then manually enabling in settings and returning to the app.

### Environment

sdk-39.0.3
"expo-notifications": "~0.7.2"
"expo-permissions": "~9.3.0"

### Reproducible Demo

Snack: https://snack.expo.io/@nathanwaters/expo-notifications-vs-expo-permissions-undetermined-bug
 
### Steps to Reproduce

1. Fresh Expo client install
2. Tap "ask permissions"
3. Don't allow
4. Tap "open settings"
5. Enable notifications
6. Return to app
7. Note that expo-notifications returns "granted" while expo-permissions returns "undetermined"

### Expected Behavior vs Actual Behavior

expo-permissions should return "granted" but returns "undetermined".

**Comment by gabrielgrover** [comment]
Any movement on this?
