### ISSUE TITLE
Regarding Intl support for Android in the production mode expo project

### ISSUE THREAD

**Issue by chuanxie** [expo/expo#10732]
`ReferenceError: Can't find variable: Intl` happens on `production mode` but not `development mode` in the latest expo for android  even i import the polyfill. 

looks like I need to eject and change?
`def useIntlJsc = true`

any other ways to sort out this issue?
thanks

**Comment by WilbertJanney** [comment]
I tried using the Intl package and it's working fine on iOS for Expo 38. For Android, it's not working. Have you figured out how to fix that issue?
