### ISSUE TITLE
React Navigation v.5 listeners don't work with remote debugging enabled.

### ISSUE THREAD

**Issue by 11grossmane** [expo/expo#10733]
### Summary of Issue 
React Navigation v.5 navigation listeners do not work properly if remote debugging is enabled. expo 39.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
all

### Reproducible Demo
N/A

### Steps to Reproduce
use navigation.addListener inside useEffect or component did mount function with remote debugging enabled.

### Expected Behavior vs Actual Behavior
events should properly fire and update state vs. events sometimes fire but don't update state

**Comment by AdamJNavarro** [comment]
Hey @11grossmane,

I'm not certain this is Expo specific. I would recommend creating a vanilla RN project and seeing if remote debugging works as expected. If it does and the problem only occurs with an Expo project, we can revisit this. Additionally, if it's specific to the React-Nav library, please create an issue on the react-navigation [repo](https://github.com/react-navigation/react-navigation/issues).

Cheers,
Adam

**Comment by 11grossmane** [comment]
Thanks Adam,
Unfortunately, React Nav said the same thing...Here's a snack.  It looks
like Appetize.io uses similar remote debugging that causes the same issue.

**Comment by 11grossmane** [comment]
Nevermind, it works correctly on the snack because there is no debugger.
