### ISSUE TITLE
Expo: Add autofillBackground to TextInput on android

### ISSUE THREAD

**Issue by tandu** [expo/expo#10734]
Expo can't control TextInput background color if it is autofilled on android. It takes yellow background. I would like to have an ability to control this behavior.

https://stackoverflow.com/questions/59531916/change-the-background-color-of-textinput-highlight-autocomplete-on-react-nativ
https://stackoverflow.com/questions/58879871/react-native-expo-textinput-style-changes-when-selecting-a-suggestion-provid

**Comment by AdamJNavarro** [comment]
Hey @tandu,

It's great to see you're interested in making Expo better! However, we use Github issues to track reproducible and actionable bugs. For feature requests or enhancements such as this one, please head over to our [Canny Board](https://expo.canny.io/admin/board/feature-requests)!

Cheers,
Adam
