### ISSUE TITLE
Image.resolveAssetSource not supported on web.

### ISSUE THREAD

**Issue by AlastairTaft** [expo/expo#10737]
### Summary of Issue 
When I run `Image.resolveAssetSource` on Expo web I get an error that the function doesn't exist.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Targeting Expo web, SDK 39.

### Reproducible Demo

Copy in the following code
```
import { Image } from 'react-native'
Image.resolveAssetSource({uri: 'foobar'})
```

### Steps to Reproduce
Run the above code.

### Expected Behavior vs Actual Behavior
Expect the code to run. Instead I receive the following error.

```
Unhandled Rejection (TypeError): react_native_web_dist_exports_Image__WEBPACK_IMPORTED_MODULE_6__.default.resolveAssetSource is not a function
```

**Comment by byCedric** [comment]
Hi @AlastairTaft! It looks like this is a pending issue on `react-native-web`, see https://github.com/necolas/react-native-web/issues/1666. We'd have to fix it in that repository to get a workaround for this. I see that the original author of that issue also provided a workaround/polyfill, could you try this on your end?

**Comment by AlastairTaft** [comment]
Thanks for the link, I ended up writing my own polyfill, but good to know cheers.

**Comment by greenimpala** [comment]
If your asset source is a string file path then you can polyfill with
```
if (Platform.OS === "web"
    Image.resolveAssetSource =  source => { uri: source }   
}
```
