### ISSUE TITLE
Video Does Not Display On Android

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo#10748]
### Summary of Issue 
Video does not display on Android devices. Usually happens when there are more than one Video components being used in the same screen.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.8 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.23.1

### Reproducible Demo

import { Video } from 'expo-av';

<Video
        source={{ uri: this.state.result1.uri }}
        style={{height: 200, width}}
        rate={1.0}
        volume={1.0}
        isMuted={true}
        resizeMode="cover"
        shouldPlay={false}
        isLooping
        />
<Video
        source={{ uri: this.state.result2.uri }}
        style={{height: 200, width}}
        rate={1.0}
        volume={1.0}
        isMuted={true}
        resizeMode="cover"
        shouldPlay={false}
        isLooping
        />
<Video
        source={{ uri: this.state.result3.uri }}
        style={{height: 200, width}}
        rate={1.0}
        volume={1.0}
        isMuted={true}
        resizeMode="cover"
        shouldPlay={false}
        isLooping
        />
<Video
        source={{ uri: this.state.result4.uri }}
        style={{height: 200, width}}
        rate={1.0}
        volume={1.0}
        isMuted={true}
        resizeMode="cover"
        shouldPlay={false}
        isLooping
        />
<Video
        source={{ uri: this.state.result5.uri }}
        style={{height: 200, width}}
        rate={1.0}
        volume={1.0}
        isMuted={true}
        resizeMode="cover"
        shouldPlay={false}
        isLooping
        />
</View>

### Steps to Reproduce

Video is not being displayed when on Android device. The space where the video should be is blank.

### Expected Behavior vs Actual Behavior
Video should show up as it does on an iPhone where ever it is to be displayed on the screen.
Video is blank in the place where it should be displayed.

P.S. I have seen this issue get raised with the expo team over the past couple of years and have seen all of the issues closed without any explanation or solution. This is a very typical use case: use videos in an app on Android. Thanks for the help in advance.

**Comment by byCedric** [comment]
Hi @mikeRChambers610, thanks for the issue report. I sense a small but sizable frustration in your PS, and I'm sorry for that. We are closing these issues because we can't reproduce this error on our end. Because of this, I threw together a [snack that renders a list of videos](https://snack.expo.io/@bycedric/expo-issue-10748-example). It has some nice features like:
- Render a set of example videos in a flat list _([from this gist](https://gist.github.com/jsturgis/3b19447b304616f18657))_
- Only 1 video can play at the time _(you can disable that by commenting out `onStartPlaying`)_
- When a video is playing, the description is expanded
- When a video is stopped, the description is collapsed _(using `numberOfLines` on the description)_

I can run this example without any issues on Android, iOS, and Web. So I'm not sure what's happening on your end. If you could [provide a repro](https://stackoverflow.com/help/minimal-reproducible-example) or a live example in Snack (just like I did), that would really help us investigate this further.

Hope this helps!

**Comment by bfitec** [comment]
We're having a similar issue that only seems to occur if we have query string parameters. ?token=secret 

We are using HLS videos and our videos play properly if there is no query string.

Is there a way we can send query string parameters in the requests? @byCedric

**Comment by bfitec** [comment]
@mikeRChambers610 

Have you tried setting `overrideFileExtensionAndroid: 'm3u8'` replace m3u8 with mp4 or whatever other extension you might have.

Expo may be failing to infer the proper media type...

**Comment by Spymannn** [comment]
Hello there, it's even worse on my phone, my app is locked after installing expo-av, I can't click on my button or anything on my android phone, it's working well on the iOS simulator but nothing on my One plus 6T phone.

I don't understand why it does that, any idea ?

"expo": "~38.0.8",
"expo-av": "~8.2.1",
 "react": "~16.11.0",
"react-native": "38.0.2",
"typescript": "~3.9.5"

**Comment by mikeRChambers610** [comment]
@byCedric  Thanks for your initial response. But I am still having the issue and it is occurring when the video is coming from the internet url since the video is not stored on the device or in the app files.

 Seems like the component is trying to download the content for all videos in the list at the same time rather than the first in the list then the second then third and so on.

**Comment by mikeRChambers610** [comment]
@byCedric Is there any update? This issue has been opened for 9 months now...

**Comment by byCedric** [comment]
Like I mentioned earlier, I'm not sure what's going on exactly. Without me being able to reproduce this, I can't do much to help.
> I can run this example without any issues on Android, iOS, and Web. So I'm not sure what's happening on your end. If you could [provide a repro](https://stackoverflow.com/help/minimal-reproducible-example) or a live example in Snack (just like I did), that would really help us investigate this further.

If it's related to all videos being downloaded at once, you could try adding code that prevents the video from downloading. [With the ref API](https://docs.expo.io/versions/latest/sdk/video/#the-following-methods-are-available-on-the) you should be able to tell each individual video component when and what to load. Also using video posters (still images) might help, as it avoids downloading the first frame of the video.

**Comment by Jestinxavier** [comment]
did any one solve this issue
