### ISSUE TITLE
The native view manager required by name (ExpoAppleAuthenticationButtonSignUpBlack) from NativeViewManagerAdapter isn't exported by @unimodules/react-native-adapter.

### ISSUE THREAD

**Issue by oporter1** [expo/expo#10747]
### Summary of Issue 
I am on SDK 37 with react native and expo v3.21.5
When implement the button it always throws a yellow error message
`The native view manager required by name (ExpoAppleAuthenticationButtonSignUpBlack) from NativeViewManagerAdapter isn't exported by @unimodules/react-native-adapter.`

I have tried uninstall and reinstalling the react-native-adapter and the expo-apple-authentication but no success.  

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.21.5

### Steps to Reproduce
sign in with appleid via button provided by expo-apple-authentication. Sign in works as expected but yellow error message is visible.

    <AppleAuthentication.AppleAuthenticationButton
      buttonType={AppleAuthentication.AppleAuthenticationButtonType.SIGN_IN}
      buttonStyle={AppleAuthentication.AppleAuthenticationButtonStyle.BLACK}
      cornerRadius={5}
      style={{
        width: Constant.width * 0.92,
        height: 44,
      }}
      onPress={async () => {
        try {
          setAppleLoggingIn(true);
          const credential = await AppleAuthentication.signInAsync({
            requestedScopes: [
              AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
              AppleAuthentication.AppleAuthenticationScope.EMAIL,
            ],
          });
          console.log("credential", credential);
          // signed in
          onSignIn(credential);
          setAppleLoggingIn(false);
        } catch (e) {
          console.log("e--->", e);
          if (e.code === "ERR_CANCELED") {
            // handle that the user canceled the sign-in flow
            setAppleLoggingIn(false);
            return {cancelled: true};
          } else {
            // handle other errors
            setAppleLoggingIn(false);
            return {error: true};
          }
        }
      }}
    />

### Expected Behavior vs Actual Behavior

actual button behavior is working. I can sign in with apple id. But the yellow error messages persist and I have to dismiss by adding `YellowBox.ignoreWarnings(["The native view manager"]);`

The native view manager required by name (ExpoAppleAuthenticationButtonSignUpBlack) from NativeViewManagerAdapter isn't exported by @unimodules/react-native-adapter.

![image](https://user-images.githubusercontent.com/12777243/96640993-0201f380-12f2-11eb-80cd-78e2f97c0117.png)

**Comment by brentvatne** [comment]
what version of `expo-apple-authentication` is installed in your project?

**Comment by oporter1** [comment]
@brentvatne     

"expo-apple-authentication": {
      "version": "2.2.1",
      "resolved": "https://registry.npmjs.org/expo-apple-authentication/-/expo-apple-authentication-2.2.1.tgz",
      "integrity": "sha512-BD4tKhoUWm99RTbFjf8IZo/CIOKFhjUej54mci1djOao770TVXl4Eq8IYDgwHEqK5v8UAySVwxAzgJBmQl9XIw=="
    },

**Comment by brentvatne** [comment]
that is the incorrect version for sdk-37. you should use `expo install expo-apple-authentication` to get the correct version, which will be "~2.1.0"

**Comment by oporter1** [comment]
I am on npm and when I `install expo-apple-authentication` it downloads the version 2.2.1. I manually updated the package and it's now working. thanks
