### ISSUE TITLE
[video] Video poster overlaps native controls

### ISSUE THREAD

**Issue by byCedric** [expo/expo#10752]
### Summary of Issue 

When using a video poster, the native controls are overlapped making it impossible to start the video.

This happens on web and an Android device, I'm not sure how this behaves on an iOS device.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.28.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 7.0.0 - ~/.nvm/versions/node/v14.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 21, 26, 28, 29, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0, 30.0.2
        System Images: android-21 | Google APIs ARM EABI v7a, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-23 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    Expo Workflow: managed
```

### Reproducible Demo

See [this snack](https://snack.expo.io/@bycedric/expo-video-poster-overlap-native-controls)
 
### Steps to Reproduce

In the `VideoCard` component, you can enable or disable the `usePoster` properties of the `Video`.

### Expected Behavior vs Actual Behavior

The poster should be rendered below the native controls, to allow that being used.

**Comment by IjzerenHein** [comment]
This behaviour is by design. The poster is rendered in JSX on top of the native Video player.

**Comment by jparksecurity** [comment]
@IjzerenHein If it's by design, do we play the video? It seems like we have to play a video to hide a poster, but we can't play.

Ref: https://github.com/expo/expo/blob/0f9dcb3b04818f3c2ed88eefcf37d33b026dce5a/packages/expo-av/src/Video.tsx#L116-L123

**Comment by saury** [comment]
Same question, the poster props become meaningless by this behavior.

**Comment by willerrodrigo** [comment]
Up

**Comment by jparksecurity** [comment]
Have we fixed it?

**Comment by mnightingale** [comment]
Anyone any ideas for fixing this?

I can think of a few options:

1. Accept that the poster covers the video and blocks the controls so add an onPress action to call `playAsync()`
  1.  Would require developers to show that users need to press to play
  2. Seems a bit awkward, may aswell create your own overlay with buttons and the poster
1. It might be possible to create a complex native solution, I'm thinking image props get sent to native, which creates a RCTRootView and passes the props back to javascript for rendering, add the native view behind the controls.

**Comment by MuhammedKpln** [comment]
We should be able to render custom overlay, as for now it's more like a image then a video because lack of native controls. Well when using poster, the only way to be able to play a video is creating a second button and handle it therefrom, which is i guess not the right way to do it.


![2022-03-30_11-57](https://user-images.githubusercontent.com/17166855/160805274-6bb2aae8-ef43-4e85-acde-01491f3e1358.png)
.

**Comment by jparksecurity** [comment]
no

**Comment by jparksecurity** [comment]
no stale

**Comment by usmansbk** [comment]
posterStyle={{
      zIndex: -1
    }}
