### ISSUE TITLE
iOS Standalone app with managed workflow: StatusBar during splash screen ignores userInterfaceStyle in app.json

### ISSUE THREAD

**Issue by elios264** [expo/expo#10758]
### Summary of Issue

During the splash screen the status bar color changes according to the ios dark/light mode no matter what's set on `userInterfaceStyle`, I already tried the all 3 possible options in a standalone app (submitting 3 builds to Testflight): `dark, light, automatic` as in:
```
{
  "expo": {
    "name": "Sample",
    "slug": "sample",
    "version": "1.0.0",
    "orientation": "portrait",
    "userInterfaceStyle": "dark",
    "backgroundColor": "#000000",
    "icon": "./assets/images/icon.png",
    "ios": {
      "requireFullScreen": true,
      "bundleIdentifier": "com.sample.app",
      "buildNumber": "17"
    },
    "androidStatusBar": {
      "hidden": true
    },
    "android": {
      "package": "com.sample.app",
      "versionCode": 17,
      "permissions": []
    },
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#000000"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
  }
}
```
But no matter the value of `userInterfaceStyle` the status bar color changes according to the iOS light/dark mode resulting on an ugly status bar for light theme:

![IMG_3533](https://user-images.githubusercontent.com/15863852/96756607-ebaf7280-1399-11eb-95b3-be8bc95f6af7.PNG)
![IMG_3532](https://user-images.githubusercontent.com/15863852/96756610-ed793600-1399-11eb-897c-1c117a272c8e.PNG)

### Environment

```
  Expo CLI 3.28.1 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.5.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2 
      react-native-web: ^0.13.18 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.1
    Expo Workflow: managed

```

### Expected Behavior vs Actual Behavior

Expected: status bar color to be locked.
Actual: Status bar color ignores everything.

**Comment by elios264** [comment]
anybody?

**Comment by brentvatne** [comment]
`"default"` in react-native's status bar doesn't do what you expect. i recommend using [expo-status-bar](https://docs.expo.io/versions/latest/sdk/status-bar/) and the "auto" value instead, which changes depending on the theme
