### ISSUE TITLE
Detached Android app cannot load redirect url in AuthSession Auth0 authentication flow

### ISSUE THREAD

**Issue by lihop** [expo/expo#1075]
**SDK Version:** 23

I am using AuthSession with Auth0 as documented [here](https://github.com/expo/auth0-example). It works on both iOS and Android with SDK 22 and 23 prior to detaching.

After detaching it continues to work on the standalone iOS app. On the standalone Android app I get this error on redirect after successfully authenticating:

<img width="344" alt="screen shot 2017-12-06 at 10 25 15 pm" src="https://user-images.githubusercontent.com/3696783/33675870-a34a0cf6-dae6-11e7-93d9-8dbd39ea2a06.png">

I am using `AuthSession.getRedirectUrl()` for the the redirect url parameter that is sent to Auth0. In all cases it returns `https://auth.expo.io/@lihop/sail`.

The value of `Constants.linkingUri` varies:
* Detached Android: `expc7ed2e7dc7ce4210b5b93237023accbb://nr-95m.lihop.sail.exp.direct:80/+`
* Detached iOS: `expc7ed2e7dc7ce4210b5b93237023accbb://+`

Possibly related to: #736 and #762

**Comment by tcdavis** [comment]
Did you add a scheme to your app.json before building?

**Comment by lihop** [comment]
I did not manually add a scheme, but I did notice the detachment process added a scheme under "expo.detach.scheme":
```
{
  "expo": {
    "isDetached": true,
    "detach": {
      "scheme": "expc7ed2e7dc7ce4210b5b93237023accbb",
      ...
    }
  ...
  }
}
```

This scheme is also present in `android/app/src/main/AndroidManifest.xml:
```
...
<manifest ...>
  <application ...>
    <activity ...>
      <intent-filter>
        <data android:scheme="expc7ed2e7dc7ce4210b5b93237023accbb"/>

        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
      </intent-filter>
    </activity>
  ...
  </application>

</manifest>
```

I have since tried adding the scheme up a level under the "expo" key and rebuilding but the issue remains.

**Comment by ide** [comment]
I suspect there's a bug with the Linking API on Android with detached apps and that's causing the issue here. Not sure of a workaround off the top of my head but maybe you can figure something out by reading the code for AuthSession.js: https://github.com/expo/expo-sdk/blob/master/src/AuthSession.js#L114

**Comment by jesseruder** [comment]
Hi. We made some changes in how detached apps work since SDK 23. Can you update to the latest SDK version and try again?
