### ISSUE TITLE
TouchableOpacity is not detecting instant touch

### ISSUE THREAD

**Issue by ShariqByteLegions** [expo/expo#10766]
I am using expo to build apps. I have previously built an app and designed a custom button in it using TouchableOpacity and the button components works fine. But after I have updated to the new CLI, my button component is not detecting instant touch and opacity is animated after some milliseconds delay. Here is the code for the button component I am using.

```
import React, { useState } from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";

const App = () => {
  const [count, setCount] = useState(0);
  const onPress = () => setCount(prevCount => prevCount + 1);

  return (
    <View style={styles.container}>
      <View style={styles.countContainer}>
        <Text>Count: {count}</Text>
      </View>
      <TouchableOpacity
        style={styles.button}
        onPress={onPress}
      >
        <Text>Press Here</Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 10
  },
  button: {
    alignItems: "center",
    backgroundColor: "#DDDDDD",
    padding: 10
  },
  countContainer: {
    alignItems: "center",
    padding: 10
  }
});

export default App;
```

Kindly help me if anyone is facing the same issue. I am using following versions;

Node v12.19.0
Expo v3.28.1

**Comment by cruzach** [comment]
hey @ShariqByteLegions , I believe we already have an issue for this topic open here- https://github.com/expo/expo/issues/10715 - so I'm going to close this as a duplicate

**Comment by brentvatne** [comment]
indeed, see this comment: https://github.com/expo/expo/issues/10715#issuecomment-714830002
