### ISSUE TITLE
expo-random claims equivalent output with NodeJS's crypto.randomBytes API but is not compatible with it

### ISSUE THREAD

**Issue by tschanz-pcv** [expo/expo#10767]
The [readme](https://github.com/expo/expo/blob/master/packages/expo-random/README.md) of the `expo-random` package says:
```
With Random you can create values equivalent to Node.js core crypto.randomBytes API.
```

But the method signatures specify:
```
byteCount (number) -- A number within the range: 0...1024. Anything else will throw a TypeError.
```

while the [NodeJS Docs](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) state: 
```
size <number> The number of bytes to generate. The size must not be larger than 2**31 - 1.
```

So by not allowing larger number of bytes than 1024 makes it only partially equivalent, right? Or did I understand something wrong? Additionally it returns a `Uint8Array` while NodeJS's crypto returns a `Buffer`. This would not satisfy the claim in the sense of "equivalent output values" in both size nor format.

The API currently is also not aligned with the NodeJS one, which allows a callback. Now that this library supports both sync and async it should be possible to add an optional CB argument which would then call the async function and return the value through the callback. This can of course be done in a project using this library if `expo-random` does not want to follow NodeJS's API but then it also won't satisfy the claim in the sense of "equivalent in the creation of the value".

**Comment by brentvatne** [comment]
it does not claim to be equivalent. it says that you can build something on top of it that is equivalent, for example https://www.npmjs.com/package/react-native-get-random-values or https://github.com/expo/expo/blob/master/packages/expo-standard-web-crypto/src/getRandomValues.ts

cc @ide

**Comment by ide** [comment]
The intent of expo-random is *not* to be a polyfill for Node's crypto API. It provides the same class of functionality but not the same API signature. We'll update the docs to reduce the implication that the Expo API mirrors Node's.
