### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '/Users/NAME/assets'

### ISSUE THREAD

**Issue by arys** [expo/expo#10760]
### Summary of Issue 
I started my project with `expo start` command and then alert popped up where watchman asking me access to my `Users/NAME/` folder. Then when I opened project in expo ios client, following message showed up in console `Error: ENOENT: no such file or directory, scandir '/Users/NAME/assets'`. Before it worked just fine, and I changed nothing in my code.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.28.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v10.20.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.5
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^3.0.9 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.28.1
    Expo Workflow: managed

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by colenndamn** [comment]
I had this exact same problem, it's because you are trying to install packages while expo is running, **solution:**

1. Go to the console, stop the execution (ctrl+c)
 
2. Then install the package using either yarn or npm

3. Then start the server again once the package has been installed using expo start. it worked for me, hope this helps
