### ISSUE TITLE
IPv6 Apple rejection...

### ISSUE THREAD

**Issue by orhaneee** [expo/expo#1076]
Hi, although my app is fully working on IPv4 network layer, and also I told Apple that I do not have an environment to test IPv6, Apple still rejects the app?

**Comment by orhaneee** [comment]
Turns out that the problem is actually coming from our backend.

**Comment by javadoffuad** [comment]
I have same problem.
What needs to be corrected at back-end?

**Comment by orhaneee** [comment]
@javadoffuad we have been using AWS EC2 which was not supporting IPv6, we changed configurations and Apple was able to communicate with them.
