### ISSUE TITLE
"React Native version mismatch" (continued)

### ISSUE THREAD

**Issue by Ifychim** [expo/expo#1077]
Hello, Hope you all are having a good day.

I am currently trying to create an app using the Expo XDE but when i try to start up the app via my phone, I get the error:

"React Native version mismatch"
JavaScript version: 0.51.0
Native version: 0.50.3

currently, my npm version is:
npm -v
5.6.0

and my react native version is : 
react-native -version
react-native-cli: 2.0.1
react-native: 0.49.5

im aware of the previous thread created (https://github.com/expo/expo/issues/923) but I have ran through all possible options proposed on this thread and I can't seem to find a solution, so would anyone mind helping out? Would be greatly appreciated.

**Comment by MikeFoog** [comment]
我也碰到同样的问题

**Comment by shicholas** [comment]
keeping your package.json at `0.50.3` for the `react-native` package should work for now.

**Comment by ide** [comment]
You need to use a version of the "react-native" package that matches the native code (RN 0.50). If you're unable to get this working, create a new project with XDE or `exp init` and ensure that it works for you. Then look at its package.json dependencies to see what a working configuration looks like.

**Comment by danikane** [comment]
@Ifychim I rm -rf-ed my entire node_modules after and yarn-ed.

I also did this:
https://stackoverflow.com/a/47764211

**Comment by luongs3** [comment]
@danikane not work for me.

**Comment by ide** [comment]
The error message "React Native version mismatch" means that your React Native JS and the native code (which is embedded with Expo) doesn't match. Creating a new project is one way to greatly reduce the chance that a stale cache or misconfigured project prevents you from loading the new project. If that works, then compare it with your project and try to get to a working state. The mismatch can happen for various reasons that are specific to your project or computer and there isn't a universal solution. Sometimes finding a contractor with RN and Expo experience can be helpful since this could take individual time and attention.

**Comment by blaneyneil** [comment]
i was having the exact same problem as the OP and was banging my head against the wall until i rebooted my phone.  i guess this is a problem for those developing on an actual phone and not a simulator.  

1) make your changes to package.json (including the react-native tarball from expo)
2) rm -rf node_modules/
3) rm yarn.lock (probably not necessary)
4) yarn cache clean (probably not necessary)
5) yarn install
6) restart the XDE
7) reboot your phone, or at least reload the expo app (not just your project in the app)

**Comment by chansuke** [comment]
@blaneyneil Thank you, this helps a lot.

**Comment by HugoMatilla** [comment]
I had the same issue starting a clean app following the instruction from [react-native official page](https://facebook.github.io/react-native/docs/getting-started.html) 
I was getting the error:
```
"React Native version mismatch"
JavaScript version: 0.50.4
Native version: 0.52.0
```
while the package created from `create-react-native-app AwesomeProject`   was
```
    "expo": "^23.0.4",
    "react": "16.0.0",
    "react-native": "0.50.3"
```
For me it was strange that a newly created project gave me an error. I could'n fix it with all the answers about this error, like [issue 1125],
(https://github.com/expo/expo/issues/1125),  [issue 923](https://github.com/expo/expo/issues/923) or this [SO question](https://stackoverflow.com/questions/47763824/react-native-version-mismatch/47764211#47764211)

Finally, I decided to try the [Expo XDE] (https://docs.expo.io/versions/latest/introduction/xde-tour.html) it created a project that worked right away. 
I checked the `package.json` and founf that the dependencies are differnt from the ones created using `create-react-native-app`
``` 
 "dependencies": {
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz"
  }```

I then add these dependencies to the project created by `create-react-native-app` and it worked.

I have now 2 questions.

Shouldn't  it be these dependencies the ones that `create-react-native-app` add to the newly created project? Or it is intended to use the ones it was created with?

Shouldn't it be more clear that these dependencies are the ones that are needed to be added to work on Expo React Native projects?  Mostly that Expo projects need to use the react-native fork from Expo. ` "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz"` I did not find it easily.

Thank you in advance and hope it helps others?

**Comment by CleonLopes** [comment]
I got this error today and I'm confused. I've been following a React Native course which includes a lot of creating new apps and loading them at Expo App. And so far I've been successful, but every new project I create with `create-react-native-app my-app` comes with this error and the new:
`"dependencies": {
    "expo": "^23.0.4",
    "react": "16.0.0",
    "react-native": "0.50.3"
  }` 
while my previous apps have something like :
`"dependencies": {
    "expo": "^25.0.0",
    "firebase": "^4.9.0",
    "react": "16.2.0",
    "react-native": "0.52.0"
  }` 
and still run within Expo App. I tried replacing it with @HugoMatilla solution or any of my last apps dependecies but it doesn't seem to do the trick.

**Comment by mykhailo-melnyk** [comment]
@HugoMatilla thanks a lot, it helped!

**Comment by McCloudA** [comment]
@HugoMatilla Your solution worked for me - thanks a ton!!!

**Comment by esamelson** [comment]
If anyone is still experiencing this issue, please try upgrading to the latest `create-react-native-app` and re-creating your project. It looks like an outdated build went out last night, but it should be fixed now 🎉   Thanks for reporting, everyone, and @HugoMatilla for the workaround.

**Comment by mandy6720** [comment]
Glad to hear it @esamelson ! Also big thank you to @HugoMatilla !!
I picked today for my first foray into RN and was totally about to ragequit lol

**Comment by lcnogueira** [comment]
I've got the same problem as @Ifychim. After reading this issue and some others, I couldn't understand what is the problem. So, before doing anything else, I tried to update the expo app of my smartphone, since there was no problem when I was I running my app on a simulator. This worked for me. No trouble anymore.

**Comment by zainulabidin302** [comment]
`react-native start --reset-cache`

**Comment by jpacol** [comment]
@zainulabidin302 your answer create an error. ERROR Metro Handler can't listen on port 8081.

**Comment by sandeep0607** [comment]
>open terminal inside your project folder
>step1-  sudo npm install -g react-native-git-upgrade
>step2- react-native-git-upgrade
after this delete the two highlighted lines in manifest.xml for the conflict named '>>>then and >>>>after'
>step3- watch-del-all && react-native start --reset-cache
now run your command react-native run-android

**Comment by yaseralimardany** [comment]
yes its work

**Comment by sorintamas** [comment]
much appreciated! this worked perfectly!

**Comment by sandeep0607** [comment]
@jpacol  you have kill the processes which runs on port no 8081. by running command >>sudo kill -9 PID
and then again run the command react-native start it works

**Comment by sandeep0607** [comment]
@Ashutosh21Nigam  try this:
open terminal inside your project folder
step1- sudo npm install -g react-native-git-upgrade
step2- react-native-git-upgrade
after this delete the two highlighted lines in manifest.xml for the conflict named '>>>then and >>>>after'
step3- watch-del-all && react-native start --reset-cache
now run your command react-native run-android

**Comment by TheSalarKhan** [comment]
The solution for me was to change the 'sdkVersion' key in `app.json`. II was on expo sdk 30.0.0 and then bumped it up to 31.0.0 which is the latest this is how my app.json looks right now:
```
{
  "expo": {
    ...
    "sdkVersion": "31.0.0",
   ...
   }
}

```

This is what fixed it for me. I've done this in the past and forgot this step.

**Comment by devmark88** [comment]
Still have problem with iOS
I've done these steps but no success
1. remove yarn cache completely
2. remove node_modules and run `yarn`
3. clean `watchman` cache
4. reset iPhone simulator content
5. start metro bundler by `react-native start --reset-cache `

It seems it read the previous version from somewhere! and I have to update it manually
NOTE: I don't use expo!

**Comment by 911flasher** [comment]
replace "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
