### ISSUE TITLE
[expo-updates] Bare workflow runs the metro bundler twice

### ISSUE THREAD

**Issue by majorhayes** [expo/expo#10787]
### Please note that discussions opened as issues in the core Expo repository will be closed.
Using expo-updates in a bare workflow results in the metro bundler running twice, once from the `react-native/react.gradle` and the second time from the `expo-updates/create-manifest-android.gradle`. Running the metro bundler twice is adding several minutes to the build time.

If the react native metro bundler has already created the bundles, why does expo-updates need to do it again? 

Since we're not uploading a bundle to expo on build, only for OTAs, what is the `createReleaseManifest` build step doing?

**Comment by brentvatne** [comment]
you can see exactly what it does in: https://github.com/expo/expo/blob/master/packages/expo-updates/scripts/createManifest.js

it creates an asset manifest to support updating assets over the air. starting up metro for doing this takes a trivial amount of time - we start the server programmatically and then fetch the assets map: https://github.com/expo/expo/blob/4f689b3ec5b17692e9a5fd1e9d9769ae9c419e6c/packages/expo-updates/scripts/createManifest.js#L109-L125

if you think this can be done more quickly or you would like to suggest an alternative way to do this, please open a discussion: https://github.com/expo/expo/discussions

**Comment by majorhayes** [comment]
I did read all the code, but for someone without any background or context, it's very opaque. (What does `getAssets` do, and what does it respond with?)

Why can't it use the bundle that was created earlier in the build rather than making a new one?
