### ISSUE TITLE
can't start app after installing any dependency

### ISSUE THREAD

**Issue by sasssssha** [expo/expo#1078]
When I initialize expo project, everything is working properly
After installing any dependency i get this error:

![image](https://user-images.githubusercontent.com/1540877/33693283-0e6dacb2-dac0-11e7-9a5e-8adc51534915.png)
react-native is installed(_react-native works in expo project template until i install any additional dependency, and i see link for expo's rn in package.json_)
npm install (as described above) doesn't cause any effect
Does anybody have any idea about what's going on?

OS: Mac OS Sierra 10.12.6
node -v: 8.9.1
npm -v: 5.0.3

**Comment by AdamJNavarro** [comment]
Hey, I would recommend switching to a npm 4.x.x version or Yarn. Using npm5 tends to lead to issues currently.

**Comment by sasssssha** [comment]
I downgraded npm to 4.6.1 from 5.0.3 and everything works fine
But when I tried to do _yarn add something_, i got "Unexpected end of file" and url from react-native from package.json
after some actions yarn also started working fine, it's kind of unknown magic...
