### ISSUE TITLE
API is incorrect for iOS scope on location permissions

### ISSUE THREAD

**Issue by special-character** [expo/expo#10781]
When using `Location.requestPermissionsAsync()` or `Location.getPermissionsAsync()` the response doesn't have the `ios` object with scope like it says in the [docs](https://docs.expo.io/versions/latest/sdk/location/#locationpermissionresponse). It has the scope at the top level object like:

```
{
    "scope":"always",
    "status":"granted",
    "canAskAgain":true,
    "expires":"never",
    "granted":true
}
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Targeting iPhone/iPad
```
  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native-web: 0.13.3 => 0.13.3 
```

### Reproducible Demo
https://snack.expo.io/@tiltshift/location (perms object listed above is console logged)
 
### Steps to Reproduce
Use location perms on iOS with the `Location` package.

### Expected Behavior vs Actual Behavior
The response would have an `ios` field with the scope nested on it.

**Comment by special-character** [comment]
After looking at the [permissions module docs](https://docs.expo.io/versions/latest/sdk/permissions/#permissionslocation), I think `scope` at the top level is probably latest/more accurate but not entirely sure. I think this might just be a docs issue and could submit a PR if so.

**Comment by lukmccall** [comment]
Hi @special-character, the response should be wrapped into a platform object. 
```
{
    "scope":"always",
    "status":"granted",
    "canAskAgain":true,
    "expires":"never",
    "granted":true
}
```
should look like this:
```
{
	// or "android":
	"ios": {
		"scope":"always",
    }
    "status":"granted",
    "canAskAgain":true,
    "expires":"never",
    "granted":true
}
```

That's how it works on Android right now. So to fix it we need to change how iOS works.

**Comment by lukmccall** [comment]
Moreover, we should also unify the android label `scope`. Why? In `expo-permissions` we don't use the "scope" key. We use "accuracy" instead. See https://github.com/expo/expo/blob/6c4358360ce2aa73bcc015ff7c7ceb66fa94c585/packages/expo-permissions/src/Permissions.types.ts#L36.

**Comment by truongtv22** [comment]
This issue is still not corrected yet :confused:

**Comment by mi-mazouz** [comment]
still have this issue, scope is not returned

**Comment by DanielFiller30** [comment]
Still have the same issue, no ios-object in LocationPermissionResponse: 
![Bildschirmfoto 2021-09-16 um 17 05 18](https://user-images.githubusercontent.com/62553667/133636861-e6523413-e1ce-47ea-bc3b-89458c5c1268.png)

**Comment by M1ST4KE** [comment]
Since SDK 41 methods [`requestPermissionsAsync`](https://docs.expo.dev/versions/latest/sdk/location/#locationrequestpermissionsasync) and [`getPermissionsAsync`](https://docs.expo.dev/versions/latest/sdk/location/#locationgetpermissionsasync) are deprecated, use their up-to-date alternatives mentioned in the docs.

**Comment by wafisher** [comment]
I'm using `getForegroundPermissionsAsync()` with SDK 43 on an iOS device and I don't see the `ios` key. It does come through in the `scope` key with the old `getPermissionsAsync()` but nothing in the new API call.

Haven't tested Android yet.

Using expo-location version 14.0.0.

**Comment by superyarik** [comment]
facing same, not ios-object in SDK48 on getForegroundPermissionsAsync and getBackgroundPermissionsAsync

**Comment by tb-nishant** [comment]
Still an issue on SDK 49!
