### ISSUE TITLE
Removing all Advertisment SDKs

### ISSUE THREAD

**Issue by supryan** [expo/expo#10791]
Hey there! We recently ejected our app to the bare workflow because we are having issues getting our app published to a target audience of 13 years and younger. Google has claimed that our app contains ads SDKs and that violates the Families Policy Requirements:

> **Issue: Violation of Families Policy Requirements**
>
> We have detected that your app includes non-certified ad SDKs or SDKs that are not approved for use in child-directed services. Any SDKs used in the app must be appropriate for use in child-directed services. Additionally, apps that solely target children must not contain any SDKs that are not approved for use in child-directed services, including ads SDKs. Apps in the Designed for Families program must only use ad SDKs that have certified their compliance with the [Families Ads Program](https://www.google.com/appserve/mkt/p/AD-FnEwXSrRqYBVqg3inI3-CByg1Iectp13piMBfaAbiA9Plt62iq3VHM8epfu_5RI1z_yeAedXYHxTok2ifvKflxulih62t4v1rTlpb4n-o3Ev26-jjs3YoguJ9rHiki6UE66n9EkyR-1Zg).

These ads SDK are automatically bundled inside Expo builds (why? I have no idea...). We did not include these ourselves. This single reason is preventing us from submitting our app to the Play Store until we can remove those completely due to the target audience.

So, now I have to figure out where these modules are contained in the ejected app and remove them. I am hoping someone can help point me in the direction of where these modules are and how to properly remove them from both iOS and Android builds. 

Any help would be greatly appreciated, thank you!

**Comment by brentvatne** [comment]
they are not bundled in bare workflow apps. in that context it depends entirely what you have installed in your project. if you have something installed, like expo-facebook, this includes the facebook sdk that perhaps google is considering to be ads.
