### ISSUE TITLE
[SDK23 issue] Android WebView cannot show unicode chars in html

### ISSUE THREAD

**Issue by turbozv** [expo/expo#1079]
exp: 47.1.0
sdk: 23.0.0

```
import React from 'react';
import { WebView } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <WebView
        html='<h1>Hello你好ハロー안녕하세요.</h1>' />
    );
  }
}

```
![image](https://user-images.githubusercontent.com/26913052/33919002-35a959b6-df6b-11e7-9282-7cb808d4c662.png)

**Comment by turbozv** [comment]
iOS works fine

**Comment by turbozv** [comment]
This issue only happens on some Android devices, my Nexus 5 cannot repro it, but emulator from Android studio can

**Comment by turbozv** [comment]
SDK21.0.0 is good on Android emulator

**Comment by turbozv** [comment]
Confirmed SDK22.0.0 works too, so it's only a problem on SDK23.0.0
![image](https://user-images.githubusercontent.com/26913052/33920541-674782e2-df73-11e7-92c7-5a28e788b9d4.png)

**Comment by turbozv** [comment]
@jesseruder, any update on the fix?

**Comment by jesseruder** [comment]
Hi @turbozv, this looks like an issue in upstream React Native. Can you open an issue on the Facebook repo?
