### ISSUE TITLE
expo-splash-screen preventing Android build

### ISSUE THREAD

**Issue by supryan** [expo/expo#10792]
### Summary of Issue 

Cannot compile Android build in Bare workflow due to expo-splash-screen and @expo/configure-splash-screen issue:

The build fails on task: :app:compileDebugJavaWithJavac with this error inside our MainActivity.java file:

```
error: no suitable method found for show(MainActivity,SplashScreenImageResizeMode,Class<ReactRootView>)
    SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);
However, dipping into the expo.modules.splashscreen.SplashScreen module that is also imported in this file, it looks like there is a show() method but it’s not getting referenced somehow for the SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);.
```

Removing this line completely in MainActivity.java allows for a successful build.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.21.5 environment info:
System:
OS: macOS 10.15.6
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
Yarn: 1.22.0 - /usr/local/bin/yarn
npm: 6.13.7 - ~/.nvm/versions/node/v13.9.0/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 4.1 AI-201.8743.12.41.6858069
Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
npmPackages:
expo: ^39.0.0 => 39.0.3
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: ~0.63.3 => 0.63.3
react-native-web: ~0.13.7 => 0.13.13
react-navigation: ^3.12.0 => 3.13.0
expo-splash-screen: ^0.2.3
@expo/configure-splash-screen: 0.1.19
npmGlobalPackages:
expo-cli: 3.21.5
```
 
### Steps to Reproduce
 
1. `expo eject` with `expo-splash-screen` installed.
2. Open SDK 39 project in Android Studio
3. Try to build, notice error at task: `:app:compileDebugJavaWithJavac FAILED`

### Expected Behavior vs Actual Behavior

1. Should build successfully with expo-splash-screen in Android Studio
2. Does not build successfully with expo-splash-screen in Android Studio

**Comment by brentvatne** [comment]
hello. i can't repro this. i just initialized a new project and ran `expo eject`, then built the project and it works as expected. i suspect you took some other steps after ejecting. please initialize a new blank project and eject and compare the result to what you have, or refer to https://github.com/expo/expo/blob/master/packages/expo-splash-screen/README.md#-update-mainactivityjavakt

**Comment by brentvatne** [comment]
it occurred to me after posting the above comment that the problem you are facing is that your expo-cli version is out of date. you should update to the latest version before running eject, at the time of writing that is 3.28.2 (3.21.5 is currently 5 months old).

**Comment by supryan** [comment]
@brentvatne thank you for getting back to me so quickly. I did update to the latest `3.28.2` before ejecting again (thank you for that) and am running into the same issue. It fails here, says "singletons" isn't available in `import expo.modules.splashscreen.singletons.SplashScreen` and this is why it is failing for me. Do you know why that would be?:

<img width="826" alt="Screen Shot 2020-10-25 at 2 02 17 PM" src="https://user-images.githubusercontent.com/6980704/97119046-e8362700-16ca-11eb-8841-6131a39ad0a0.png">

**Comment by supryan** [comment]
@brentvatne spoke too soon! An upgrade to expo-splash-screen to `0.6.1` fixed the issue.

**Comment by sometimescasey** [comment]
Thanks @supryan !

I also ran into this issue when I ran `expo install expo-splash-screen` in an Expo managed project (it seemed to have installed `0.3.1`) , ejected, and then tried to build my Android app.

`yarn remove expo-splash-screen` and then `yarn add expo-splash-screen` (which installed `0.5.0`) resolved the issue.
