### ISSUE TITLE
expo-service-worker.js:1 Uncaught (in promise) DOMException: Quota exceeded

### ISSUE THREAD

**Issue by barnu5** [expo/expo#10795]
SDK Version: 38.0
Platforms(Android/iOS/web/all): web
Repeated console error. 

In chrome, incognito mode

```
expo-service-worker.js:1
Uncaught (in promise) DOMException: Quota exceeded.
```

**Comment by AdamJNavarro** [comment]
Hey @barnu5, there isn't a lot of information to go off here. Can you let me know if this is project specific? If you haven't already could you see if this error happens with a newly created project?

Cheers,
Adam
