### ISSUE TITLE
[expo-auth-session] Google Provider does not allows to revoke the furnished token.

### ISSUE THREAD

**Issue by victorpicaud** [expo/expo#10809]
### Summary of Issue 
Hello, It seems that the Google provider discovery document does not passes well the revocation endpoint when invoking the revokeAsync() method of the AuthSession module. It may actually be a misuse of the AuthSession API form me but regarding the Google and Facebook provider, the use of these methods is not documented either here: https://docs.expo.io/guides/authentication/#google 
or here:
https://docs.expo.io/versions/latest/sdk/auth-session/

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed

### Reproducible Demo
//initialize the Google provider hook
const [request, response, promptAsync] = Google.useAuthRequest({
      expoClientId: 'Myclientid',
      iosClientId: 'Myclientid',
      androidClientId: 'Myclientid',
      webClientId: 'Myclientid',
      prompt: 'select_account',
      redirect_uri: 'https://auth.expo.io/@vipicaud/Frontend',
    });
//Trying to revoke the token here
const getRequestRevoke = async () => {
      //Getting the TokenResponse object works fine
      const res = AuthSession.TokenResponse.fromQueryParams(response.params);
      console.log(res);
      //Where the error is triggered
      const rev = AuthSession.revokeAsync({token: response.authentication.accessToken, clientId: 'Myclientid'})
      console.log(rev)
    }

//Classic Goggle provider auth flow
    React.useEffect(() => {
      if (response?.type === 'success') {
        const { authentication } = response;
        if (response.authentication) {
           getRequestRevoke();
        }
      }
    }, [response]);
 
### Steps to Reproduce
Create a classic Google auth flow with the provider as described here: https://docs.expo.io/guides/authentication/#google 
Then try to revoke the token obtained after a successful auth.

### Expected Behavior vs Actual Behavior
Expected Behavior:
The token should be revoked right after the login preventing any further requests in the app.

Actual Behavior:
The AuthSession.revokeAsync() fires an unhandled promise rejection error:
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'discovery.revocationEndpoint')]
and then the Token that was provided during the auth is still valid and usable.

**Comment by byhringo** [comment]
I'm having the exact same issue, and would love if someone could point to a solution :-)

**Comment by jsPl** [comment]
Instead of
<code>const rev = AuthSession.revokeAsync({token: response.authentication.accessToken, clientId: 'Myclientid'})</code>
try
<code>const isRevokeSuccessful = await AuthSession.revokeAsync({token: response.authentication.accessToken, clientId: 'Myclientid'}, Google.discovery)</code>

**Comment by justin-barca-at-camis** [comment]
I think the docs are responsible for this confusion. They do not declare discovery as a required second parameter and instead declare discovery as the return value. In fact, this function returns a promise along with all the other *Async functions but this is not declared either. Maintainers: should this or a new ticket be used to track this?
