### ISSUE TITLE
CSS.supports is not a function with server-side rendering

### ISSUE THREAD

**Issue by OKNoah** [expo/expo#10808]
https://github.com/expo/expo/blob/891f80d995d02eede2e4a2263e311dc638db4860/packages/expo-blur/src/BlurView.web.tsx#L15

**Comment by byCedric** [comment]
Hi @OKNoah, please provide the full bug report information in the future. That being said, we don't support `expo-blur` in SSR at the moment. One way to work around this issue, if you use NextJS, is to use Next's Dynamic import to only render this component in the client side (not on the server side).

Hope this helps!
