### ISSUE TITLE
Appearance configuration not respected after upgrading to Expo SDK 39

### ISSUE THREAD

**Issue by markholland** [expo/expo#10802]
### Summary of Issue 

After upgrade to Expo 39 `"userInterfaceStyle": "light",` in `app.json` is not respected.

https://docs.expo.io/versions/latest/sdk/appearance/#configuration

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 11.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.13.0 - /var/folders/dr/4wxt2q_x5_s8kc7gb0zk01lr0000gn/T/fnm-shell-2754045/bin/node
      npm: 6.14.8 - /var/folders/dr/4wxt2q_x5_s8kc7gb0zk01lr0000gn/T/fnm-shell-2754045/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B5025f - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed

### Reproducible Demo

https://github.com/markholland/expo-color-scheme
 
### Steps to Reproduce

- Set device theme to dark
- Set `"userInterfaceStyle": "light",` in `app.json`
- Consume `useColorScheme` hook from `react-native` and observe that returned value is 'dark'

### Expected Behavior vs Actual Behavior

 - Expect `useColorScheme` to always return 'light'

**Comment by byCedric** [comment]
Hi @markholland, thanks for the issue report! Have you tried importing the hook from `expo-appearance` instead? [From the docs](https://docs.expo.io/versions/latest/sdk/appearance/#api):
```
import { useColorScheme } from 'react-native-appearance';
```

**Comment by markholland** [comment]
Thanks for the reply, I've just tried that and updated the repro. It didn't make any difference. 

If I add an `<AppearanceProvider>` it now works.

What I don't understand is why I now need to use this component when in SDK 38 I didn't.

**Comment by elios264** [comment]
this is related to  #10758  

It also ignores `userInterfaceStyle` during the splash screen
