### ISSUE TITLE
No SplashScreen Implemented and getting error: "Native splash screen is already hidden. Call this method before rendering any view."

### ISSUE THREAD

**Issue by oporter1** [expo/expo#10816]
### Summary of Issue 
I have no reference of the expo splash screen in any part of my app. On every load of the app the yellow error message is displayed: 

`[Unhandled promise rejection: Error: Native splash screen is already hidden. Call this method before rendering any view.]`

I have reviewed the other threads and it seems like there was a fix for this issue a month back but it is still persisting for me and I am not sure why as I am not using the expo-splash-screen at anypoint.

I am on  ` "expo-splash-screen" "^0.6.1"`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.0.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed

### Reproducible Demo
I am not sure how to display the code as there is no code that references the expo-spalsh-screen other then the package-lock.json or yarn.lock file

`"expo-splash-screen@*", "expo-splash-screen@^0.6.1":
  "version" "0.6.2"
  dependencies:
    "@expo/configure-splash-screen" "0.2.0"`

 
### Steps to Reproduce
Run app off of expo metro bundler
On load of the app, yellow error message is displayed

### Expected Behavior vs Actual Behavior
Expected no yellow error message to appear on load of app 
Actual behavior: yellow error message appears

**Comment by kim791** [comment]
I get the same exact issue.

**Comment by valdrox** [comment]
Same, I got this on my iPod touch running iOS 14, but not on Android. Also don't know what is causing it.

**Comment by brentvatne** [comment]
download the latest version of expo client from the app store / play store. install the latest version with `expo client:install:ios` or `expo client:install:android`.

**Comment by Goszu** [comment]
Happening on the latest version of expo client with expo v39

![image](https://user-images.githubusercontent.com/1271130/97358866-c6d46700-1893-11eb-8fdb-6bd794d03e42.png)

**Comment by brentvatne** [comment]
![IMG_7627](https://user-images.githubusercontent.com/90494/97360852-f8314080-185b-11eb-8df6-af3fd2b2811c.jpg)

this is the latest version :)

**Comment by Goszu** [comment]
**Summary of issue:**

Same as above. 
I am not using expo-splash-screen anywhere in the code.
version in node-modules: 0.6.2

I am using AppLoading component. Removing it from the code makes this error disappear.
Please let me know if you need the actual implementation code.

**Environment**

System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed

**Comment by brentvatne** [comment]
that's not a reproducible example though :) from the issue template:

```
### Reproducible Demo

<!--
- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve
-->
<!--
As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!
-->

```

**Comment by brentvatne** [comment]
```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { AppLoading } from 'expo';

export default function App() {
  const [isLoading, setIsLoading] = React.useState(true);

  React.useEffect(() => {
    let timeout = setTimeout(() => {
      setIsLoading(false);
    }, 1000)

    return () => clearTimeout(timeout);
  }, [])

  if (isLoading) {
    return <AppLoading />
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

cannot repro it with this code

**Comment by Goszu** [comment]
Sorry, my bad for not providing the code. I created a snack with a simple example: https://snack.expo.io/erhB2KQlv.

Unfortunately I can't reproduce the issue with simple snack. I have similar code in my project, but there is more stuff which might conflict with the AppLoading component and cause this error (react-redux, react-navigation?).

I can only confirm that on expo SDK version 38 I had no errors, and it started happening after upgrading to 39. It happens only on iOS.

**Comment by truongtv22** [comment]
Let me know when this error is fixed

**Comment by neiker** [comment]
I'm getting the same warning on debug after a Fast Refresh on iOS simulator
Expo Client 2.17.4.101
Expo SDK 39.0.2
Expo CLI 3.28.2

**Comment by summerkiflain** [comment]
@brentvatne this is still an issue, I am also getting this warning constantly when using iOS simulator and using Fast Refresh, every time app fast refreshes it spits out this warning on console log, which is very troubling when debugging stuff.
Expo Client 2.17.4.101
Expo SDK 39.0.4
Expo CLI 3.28.5
Expo SDK 38 was not logging this warning. I am using AppLoading Component.

**Comment by Northshoot** [comment]
Getting the same error running on iOS device, no issues on Android. 

```
  Expo CLI 4.0.6 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.2.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.10 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.5 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
      react-native-web: ~0.13.7 => 0.13.18
      react-navigation: ^4.3.9 => 4.4.3
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
i'm going to lock this issue because nobody is following along with our request to provide a [mcve](https://stackoverflow.com/help/minimal-reproducible-example) that we need to investigate further. if you're still having a similar problem to this then please create a new issue and fill out the issue template completely
