### ISSUE TITLE
[blur] BlurView does not support SSR

### ISSUE THREAD

**Issue by byCedric** [expo/expo#10810]
## 🐛 Bug Report

Continuing #10808 

### Summary of Issue 

Right now, the blur view does not support SSR environments like NextJS. It has 2 problems

1. It looks like NextJS provide a `CSS` global on SSR, but that doesn't include the `supports` method. This results in a type error like `CSS.supports is not a function`. [We currently only check on CSS, but not on the supports method](https://github.com/expo/expo/blob/master/packages/expo-blur/src/BlurView.web.tsx#L19).

2. Even when guarding this property, there will be an unexpected difference (according to React/Next) if we SSR-render _without_ the style and in the client we render it _with_ the style. And, because of this, it keeps using the SSR style (without blur)

![Screenshot 2020-10-26 at 15 55 04](https://user-images.githubusercontent.com/1203991/97188293-a3ca8a00-17a3-11eb-8141-56c4564d39d1.png)

I could think of two alternatives:

1. Render an inline `<style>` element, [using `@supports (backdrop-filter: blur(1px)) { ... }`](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports). This works pretty nicely because, on both SSR and Client, we get the exact same styling. We leave it up to the browser through CSS to include saturation only when blur is supported. _**BUT**_ [React Native Web dropped support for `className`](https://github.com/necolas/react-native-web/issues/1146), meaning we can't just link the style :|

2. Another approach would be rendering `null` for the component, when rendered in SSR. _**BUT**_ also this causes a "yo server rendered this, and client rendered that, wtf"-error from React/Next

![Screenshot 2020-10-26 at 15 54 23](https://user-images.githubusercontent.com/1203991/97188947-5e5a8c80-17a4-11eb-8eaa-2cbf0b11b7d9.png)

> Both alternatives actually work 😄 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 7.0.0 - ~/.nvm/versions/node/v14.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 21, 26, 28, 29, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0, 30.0.2
        System Images: android-21 | Google APIs ARM EABI v7a, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-23 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    Expo Workflow: managed
```

### Steps to Reproduce

- `$ npx create-next-app --example with-expo-typescript`
- `$ yarn add expo-blur`
- Copy the [Snack example](https://docs.expo.io/versions/v39.0.0/sdk/blur-view/#usage) to `pages/index.tsx`
- `$ yarn dev`

### Expected Behavior vs Actual Behavior

It should work on SSR.

**Comment by nandorojo** [comment]
I was about to make this exact issue. I'm trying to use `expo-blur` with Next.js.

<img width="968" alt="Screen Shot 2020-11-11 at 10 50 46 AM" src="https://user-images.githubusercontent.com/13172299/98833236-c7303e80-240b-11eb-8b84-aae7c47fb7d5.png">

I'll probably `patch-package` with `CSS.supports?.(...)` to just get it to work for now.

For added context, this is what I get when I log `CSS` in Next:

![Screen Shot 2020-11-11 at 10 50 03 AM](https://user-images.githubusercontent.com/13172299/98833432-0068ae80-240c-11eb-8326-949ed367cc04.png)
![Screen Shot 2020-11-11 at 10 50 09 AM](https://user-images.githubusercontent.com/13172299/98833431-ffd01800-240b-11eb-8bc0-b6e117869c92.png)

**Comment by nandorojo** [comment]
For added context, I'll be testing this [CSS filters polyfill](https://github.com/Schepp/CSS-Filters-Polyfill) as well.

**Comment by nandorojo** [comment]
@byCedric if the solution I proposed makes sense to you, I could try to PR. In the meantime, I'll probably `patch-package` and test that out.

**Comment by byCedric** [comment]
Hi @nandorojo! Yeah, that makes a lot of sense! I kind-of forgot about the possibility of the data tag 😅  If you have time, go for it, I'd be happy to review the PR 😄

**Comment by nandorojo** [comment]
Sounds good!

For reference, I have this so far:

```tsx
import * as React from 'react'
import { View } from 'react-native'

import { BlurProps } from './BlurView.types'
import getBackgroundColor from './getBackgroundColor'

function BlurView({ tint = 'default', intensity = 50, style, ...props }: BlurProps) {
  // don't collide this style with other blurs
  // TODO how should I set this?
  const id = React.useRef(`${Math.random()}`).current
  const blurStyle = getBlurStyle(id, { tint, intensity })
  return (
    <>
      <View {...props} dataSet={{ blur: id }} style={[style, blurStyle]} />
      <style dangerouslySetInnerHTML={{ __html: blurStyle }} />
    </>
  )
}

function getBlurStyle(id: string, { intensity, tint }: Pick<BlurProps, 'intensity | 'tint'>) {
  // https://developer.mozilla.org/en-US/docs/Web/CSS/@supports
  const style = `[data-blur="${id}"] {
  background-color: ${getBackgroundColor(intensity, tint)}
}
@supports (backdrop-filter: blur(1px)) {
  [data-blur="${id}"] {
    backdrop-filter: saturate(180%) blur(${intensity * 0.2}px)
  }
}
@supports (-webkit-backdrop-filter: blur(1px)) {
  [data-blur="${id}"] {
    -webkit-backdrop-filter: saturate(180%) blur(${intensity * 0.2}px)
  }
}`
  return style
}

export default BlurView
```

To prevent `[data-blur]` from styling all elements, I figured each component should have a unique ID to identify the styles with. I put `Math.random()` as a placeholder, figured I would ask what you suggest to put there instead. @byCedric let me know if anything comes to mind as a replacement for that.

If I were only targeting Next.js, then I would use `<style jsx>` and the ID wouldn't be necessary, since it would be scoped to the component.

**Comment by nandorojo** [comment]
I added an example to Snack here: https://snack.expo.io/@nandorojo/jealous-crackers

If you open `./Blur` you'll see my code sample from above. I inlined `BlurViewProps` and `getBackgroundColor` (these are in `expo-blur/src`).

**Comment by nandorojo** [comment]
Just realized that the style is deterministic based on `tint` and `intensity`, so the `id` field should be calculated based on those. I'll update shortly.
