### ISSUE TITLE
Services and SeviceConnections

### ISSUE THREAD

**Issue by GiverDead** [expo/expo#10822]
Hello. I need tool for messaging with remote service in android. Can i do this with expo and react native or i need to eject my application from expo? 
[Google docs example](https://developer.android.com/reference/android/app/Service.html#remote-messenger-service-sample)

**Comment by byCedric** [comment]
Hi @GiverDead, please use our [Slack](https://slack.expo.io/) or [forums](https://forums.expo.io/) for these kinds of questions in the future. We use Github for issues only, to make our work possible 😄 

If you can use a JS-only version of the SDK/library you want to connect with, you can simply use that. If you need native code, you can still do that but have to go for the bare workflow.

Hope this helps.
