### ISSUE TITLE
Component Exception: Invalid Hook Call (plus other hook related error)

### ISSUE THREAD

**Issue by jack2684** [expo/expo#10825]
### Summary of Issue 
I cannot start the template project. Run into hook issue. I checked with https://reactjs.org/warnings/invalid-hook-call-warning.html. I don't think it is a problem with my react version.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Targeting IOS.

`expo diagnostics` output:
```
  Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 15.0.1 - /usr/local/bin/node
      npm: 7.0.3 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed
```

### Reproducible Demo
Below is what I get:
![image](https://user-images.githubusercontent.com/1225301/97324922-a4a8fd80-182f-11eb-8aef-88e6edfd66b4.png)

 
### Steps to Reproduce
1. I try to use `expo-template-tabs`, by running `expo init`.
2. Then choose the tabs template. 
3. I run `expo start`
4. Then I scan the QR code from my iphone
5. Then I run into the problem

### Expected Behavior vs Actual Behavior
Expecting a demo app to run successfully.

**Comment by AdamJNavarro** [comment]
Hey @jack2684, I just created a new project using the tabs template and can't seem to reproduce the error you are getting. Can you let me know what version of the Expo client you are running?

Cheers,
Adam

**Comment by jack2684** [comment]
@AdamJNavarro thx for your quick response. 

Weirdly, I tried both using my phone and ios emulator in my mac, they both failed. BTW this is the expo client version running on my iphone, `39.0.0`:
![image](https://user-images.githubusercontent.com/1225301/97358895-26f9e780-1859-11eb-9541-c5928e65d246.png)

If it is not the expo client problem, any chance it is caused by my react version? 🤔
```
[13:32:20]junjieguan:~/g/c/tabs-starter[main]$ npm ls react-dom
tabs-starter@ /Users/junjieguan/git/celltick/tabs-starter
├── react-dom@16.13.1
└─┬ react-native-web@0.13.18
  └── react-dom@16.13.1 deduped

[13:32:25]junjieguan:~/g/c/tabs-starter[main]$ npm ls react-native
tabs-starter@ /Users/junjieguan/git/celltick/tabs-starter
├─┬ @react-native-community/masked-view@0.1.10
│ └── react-native@0.63.2 deduped
...
├─┬ expo@39.0.3
```

**Comment by jack2684** [comment]
Hey @AdamJNavarro , I just tried on other macbook, and couldn't reproduce it neither. So likely something specific  to my macbook.

**Comment by jack2684** [comment]
I also double checked the version node, they are all the same. 

The only difference is, the other mac is using yarn. So I `brew install yarn` and run `yarn add expo`. Then everything works fine now.

It is not a problem for me anymore. If you don't find the necessary to dig, feel free to close it. Thanks again!

**Comment by byCedric** [comment]
Thanks for the follow up @jack2684! One thing you could try on your MacBook that has the issue, is force cleaning your cache: `npm cache clear --force`. This would wipe your local cache of the registry, maybe something is broken in there. I'll close this issue.

**Comment by dragonsnapx** [comment]
For people having similar problems (I did), try doing the yarn trick above and don't forget to add watchman.

**Comment by LarsGrevelink** [comment]
I too did encounter this issue and fixed it with NPM. These steps fixed it on my local environment;

1. Make sure you're running one of the support node versions
2. Remove the `node_modules` folder and `package.lock`
3. Run `npm install` again

 ✅

**Comment by adamelmohamad** [comment]
why was this issue closed?  I am getting the same error
