### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by juancancela** [expo/expo#1082]
Hi, 
Im getting an error without explicit logs when attempting to create a build for iOS.
This is the error im getting:

MacBook-Pro-2:mobile-app$ exp build:ios --clear-credentials
[exp] Making sure project is set up correctly...
|[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? xxx@xxx.com
? Password? **********
? What is your Apple Team ID (you can find that on this page: https://developer.apple.com/accou
nt/#/membership)? XXXXXXXXX
**[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID 84a4fa60-db84-11e7-8fcb-613d5826de9d, message: Internal error occurred. Please try again in a few minutes or contact support.**

**Ive already tried sending a message in the forums (https://forums.expo.io/t/there-was-an-error-with-this-build-ios/3443/10) but didnt get a response back, so Im posting it here.**

Thanks in advance.

**Comment by ide** [comment]
(Cross-posting from the forums) The error from the logs is:

```
No teams available on the Developer Portal You must accept an invitation to a team for it to be available To learn more about teams and how to use them visit https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.htm
```

This can happen if you're using the free Apple developer account. To build apps that run on other devices (excluding your own) you need to have a paid developer account.
