### ISSUE TITLE
[expo-image-picker][ios] Can't drag the picture around the crop area (bare react-native app)

### ISSUE THREAD

**Issue by aprilmintacpineda** [expo/expo#10820]
### Summary of Issue 

1. Call `launchCameraAsync` with `allowsEditing: true`.
2. Take a picture.
3. Try to drag the picture on the crop area.
4. It doesn't change

Works well on Android.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 79.11 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v14.8.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.14.0 => 16.14.0
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Reproducible Demo

https://github.com/aprilmintacpineda/repro-expo-image-picker-10820

This only happens for `launchCameraAsync` but not for `launchImageLibraryAsync`.

Sorry, can't upload GIF, file size way too big for github
https://streamable.com/4yfkf6

**Comment by AdamJNavarro** [comment]
Hey @aprilmintacpineda, could you please share a public repo with a minimal reproducible example so that we may test this on our end? Giving steps rather than explicit code provides an opportunity for user error.

Cheers,
Adam

**Comment by aprilmintacpineda** [comment]
@AdamJNavarro I have provided the repro above.

**Comment by aprilmintacpineda** [comment]
@AdamJNavarro Hi, I understand you may only be doing this on your free, but just to follow up if you have any news about this or if you've seen my reproducible repo. Thanks.

**Comment by uvrik** [comment]
Hi!
I have the same issue.

**Comment by WaiiM** [comment]
Hey ! 
The same issue on iOS with launchCameraAsync

**Comment by jfrolich** [comment]
Same here when invoked with `launchCameraAsync`

**Comment by aprilmintacpineda** [comment]
Still have a label "needs repro" but I've already added a repro. @lukmccall @AdamJNavarro

**Comment by mdivani** [comment]
same issue here

**Comment by dmitryusikriseapps** [comment]
Hi there. I can reproduce this on my side, I've attached the video. If I try to move the crop area then it'll be returned to the initial state.
https://streamable.com/2tlg14

**Comment by jfrolich** [comment]
I also saw it in a few production apps.

**Comment by aprilmintacpineda** [comment]
> I also saw it in a few production apps.

Well, it's happening right now on my app

**Comment by jonasbetareader** [comment]
Same here

**Comment by tylerduni** [comment]
Same here.  Happens with launchCameraAsync but not launchImageLibraryAsync.

**Comment by brentvatne** [comment]
this is a bug on ios, there isn't much we can do about that except use a non native image cropper

**Comment by aprilmintacpineda** [comment]
Wow, from that detail this bug has been around for 7 years and still hasn't been fixed...

**Comment by aprilmintacpineda** [comment]
To get this to work, I moved to https://github.com/ivpusic/react-native-image-crop-picker

**Comment by oguzturker8** [comment]
> https://streamable.com/2tlg14

Hi, i came here from that package. It works great but has some problems.
It has compressImageQuality prop like expo-image-picker's quality prop. It's initial value is 1 for Android and 0.8 for iOS but prop is not working on iOS.  So your media always being compressed 20% on iOS.
Seems we need to sacrifice one of these features, 😞.

**Comment by oguzturker8** [comment]
> To get this to work, I moved to https://github.com/ivpusic/react-native-image-crop-picker

I came here from this package. It works great but has some problems.
It's compressImageQuality prop is not working well on iOS. Initial value is 1 for Android and 0.8 for iOS. But prop is not overriding on iOS. So it keeps compressing image 20% when you set `compressImageQuality: 1`.
Seems like we need to sacrifice one of these features, 😞.

**Comment by aprilmintacpineda** [comment]
> > To get this to work, I moved to https://github.com/ivpusic/react-native-image-crop-picker
> 
> I came here from this package. It works great but has some problems. It's compressImageQuality prop is not working well on iOS. Initial value is 1 for Android and 0.8 for iOS. But prop is not overriding on iOS. So it keeps compressing image 20% when you set `compressImageQuality: 1`. Seems like we need to sacrifice one of these features, 😞.

Why don't you open an issue there maybe someone can help you out? I personally don't use those.

**Comment by Abhishek21k** [comment]
this issue still is not fixed, the image can be croped in the android but does not crops in ios

```
result = await ImagePicker.launchCameraAsync({
          mediaTypes: ImagePicker.MediaTypeOptions.Images,
          allowsEditing: true,
          // aspect: [4, 3],
          quality: 1,
          base64: true,
          exif: true,
          imageQuality: 0.8,
          presentationStyle: "fullScreen",
          cameraType: ImagePicker.CameraType.back,
        });
```
