### ISSUE TITLE
[expo-notifications] Push notification icon is a gray square/circle on One Plus

### ISSUE THREAD

**Issue by clems36** [expo/expo#10837]
### Summary of Issue

In a bare project, the push notification icon is a gray square instead of the app icon. This only has happened to me on One Plus devices (5T and 6T). Working fine on my Huawei and on iOS.

### Environment

Platform: android

expo diagnostics:

```
Expo CLI 3.28.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.7.2 - /Users/accountable/.rvm/gems/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.3
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.11.5
    Expo Workflow: bare
```

### Reproducible Demo

Created this MCVE, change the `experienceId` according to your expo username.

https://github.com/clems36/demo-push-notif
 
### Steps to Reproduce

- expo init
- select bare project
- expo install expo-notifications
- follow basic setup instructions from here: https://docs.expo.io/push-notifications/push-notifications-setup/
- yarn android (run on One Plus device)
- send push notif via curl command

I've tried setting `useNextNotificationsApi: true` and other notifications settings in app.json but this doesn't seem to affect the bare workflow.
In the past I wasn't using Expo for push notifications and this piece of code did the trick:

`android/app/src/main/java/com/evollu/react/fcm/SendNotificationTask.java`
```java
Resources res = mContext.getResources();
int smallIconResId = res.getIdentifier("ic_launcher", "mipmap", packageName);
            if(smallIconResId != 0){
                notification.setSmallIcon(smallIconResId);
            }
```
`AndroidManifest.xml`
```
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher" />
    <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorAccent" />
```

I found some related issues for the managed workflow but not for the bare workflow. I think the docs are not clear on how the icon is handled in the bare workflow.

### Expected Behavior vs Actual Behavior

Expected behaviour would be for One Plus devices to behave like other android devices. Here's the correct display on Huawei:

![Screenshot 2020-10-28 at 10 50 24](https://user-images.githubusercontent.com/6041593/97420275-654fdf00-190b-11eb-9769-c6f077205dff.png)

And here it is on One Plus:

![Screenshot 2020-10-28 at 10 51 11](https://user-images.githubusercontent.com/6041593/97420358-80225380-190b-11eb-867d-8677ce12cb79.png)

Notice that the app icon is correctly displayed in the status bar though (still on One Plus):
![Screenshot 2020-10-28 at 10 52 26](https://user-images.githubusercontent.com/6041593/97420500-ac3dd480-190b-11eb-838c-b349ffeebcf1.png)

**Comment by cruzach** [comment]
To customize your notification app icon and color on android, you should follow [this guide here](https://github.com/expo/expo/tree/master/packages/expo-notifications#configure-for-android).

Android recommends making that statusbar notification icon all white with a transparent background, otherwise that exact behavior ( blank gray square/circle) can happen- https://developer.android.com/design/style/iconography.html#notification

So make sure the image for `ic_stat_notifications` in
```
<meta-data
      android:name="expo.modules.notifications.default_notification_icon"
      android:resource="@drawable/ic_stat_notifications" />
```

follows those guidelines

**Comment by clems36** [comment]
Ok I was reading the docs from https://docs.expo.io/versions/latest/sdk/notifications/, and the `Installation in bare React Native projects` part is missing there.
It's working fine, thank you @cruzach

**Comment by komelabbbas** [comment]
![zzfast](https://user-images.githubusercontent.com/51354419/103684946-63ad3200-4fb2-11eb-97d8-bc403365565a.png)
![IMG_20210106_000033](https://user-images.githubusercontent.com/51354419/103684951-660f8c00-4fb2-11eb-92ea-6a32b592d006.jpg)

Any solution please help..

**Comment by komelabbbas** [comment]
> ![zzfast](https://user-images.githubusercontent.com/51354419/103684946-63ad3200-4fb2-11eb-97d8-bc403365565a.png)
> ![IMG_20210106_000033](https://user-images.githubusercontent.com/51354419/103684951-660f8c00-4fb2-11eb-92ea-6a32b592d006.jpg)
> 
> Any solution please help..

Thanks, now it working fine after using a different icon

**Comment by vitorverasm** [comment]
> android:name="expo.modules.notifications.default_notification_icon"

This should be added to the bare project setup docs!

**Comment by vitorverasm** [comment]
> To customize your notification app icon and color on android, you should follow [this guide here](https://github.com/expo/expo/tree/master/packages/expo-notifications#configure-for-android).
> 
> Android recommends making that statusbar notification icon all white with a transparent background, otherwise that exact behavior ( blank gray square/circle) can happen- https://developer.android.com/design/style/iconography.html#notification
> 
> So make sure the image for `ic_stat_notifications` in
> 
> ```
> <meta-data
>       android:name="expo.modules.notifications.default_notification_icon"
>       android:resource="@drawable/ic_stat_notifications" />
> ```
> 
> follows those guidelines

This should be added to the bare react native project setup docs! Is missing this step.

**Comment by TomasSestak** [comment]
> To customize your notification app icon and color on android, you should follow [this guide here](https://github.com/expo/expo/tree/master/packages/expo-notifications#configure-for-android).
> 
> Android recommends making that statusbar notification icon all white with a transparent background, otherwise that exact behavior ( blank gray square/circle) can happen- https://developer.android.com/design/style/iconography.html#notification
> 
> So make sure the image for `ic_stat_notifications` in
> 
> ```
> <meta-data
>       android:name="expo.modules.notifications.default_notification_icon"
>       android:resource="@drawable/ic_stat_notifications" />
> ```
> 
> follows those guidelines

The link is dead now :(

**Comment by Pascalkollie** [comment]
## Issue: Custom Notification Icon and Background Color for Firebase Messaging in Expo

### Solution

To add a custom notification icon and background color for Firebase Messaging in an Expo managed workflow, follow these steps:

### Step 1: Place the Notification Icon

Place your notification icon (`IconNotification.png`) in the `assets` directory of your project.

### Step 2: Update Your Expo Configuration Plugin

Add the following code to your Expo configuration plugin to copy the notification icon and set the notification background color:

```javascript
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Adds the notification icon for Firebase Messaging to the Android project.
 * @param {Object} config - The Expo config object.
 * @returns {Object} - The modified Expo config object.
 */
const withFirebaseMessagingNotificationIcon = (config) => {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const iconSrcPath = path.resolve(config.modRequest.projectRoot, 'assets', 'IconNotification.png');
      const iconDestPath = path.resolve(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'drawable', 'notification_icon.png');

      try {
        if (fs.existsSync(iconSrcPath)) {
          fs.mkdirSync(path.dirname(iconDestPath), { recursive: true });
          fs.copyFileSync(iconSrcPath, iconDestPath);
        } else {
          console.warn(`Icon source file does not exist: ${iconSrcPath}`);
        }
      } catch (error) {
        console.error(`Failed to copy notification icon: ${error}`);
      }

      return config;
    },
  ]);
};

/**
 * Adds Firebase Messaging configuration to the AndroidManifest.
 * @param {Object} config - The Expo config object.
 * @returns {Object} - The modified Expo config object.
 */
const withFirebaseMessagingConfig = (config) => {
  return withAndroidManifest(config, async (config) => {
    config.modResults = await setFirebaseMessagingConfig(config, config.modResults);
    return config;
  });
};

/**
 * Sets the Firebase Messaging configuration in the AndroidManifest.
 * @param {Object} config - The Expo config object.
 * @param {Object} androidManifest - The AndroidManifest object.
 * @returns {Object} - The modified AndroidManifest object.
 */
async function setFirebaseMessagingConfig(config, androidManifest) {
  const mainApplication = AndroidConfig.Manifest.getMainApplication(androidManifest);

  // Add the custom meta-data for notification icon
  AndroidConfig.Manifest.addMetaDataItemToMainApplication(
    mainApplication,
    'com.google.firebase.messaging.default_notification_icon',
    '@drawable/notification_icon',
    'resource'
  );

  // Add the custom meta-data for notification background color
  AndroidConfig.Manifest.addMetaDataItemToMainApplication(
    mainApplication,
    'com.google.firebase.messaging.default_notification_color',
    '0x3ab590' // Hex color value converted to integer
  );

  return androidManifest;
}

module.exports = (config) => {
  config = withFirebaseMessagingNotificationIcon(config);
  config = withFirebaseMessagingConfig(config);
  return config;
};
```

Rebuild Your Project
After making these changes, rebuild your project to ensure the new configurations are applied.

If you encounter any issues or have further questions, feel free to ask!
