### ISSUE TITLE
Unable to resolve module `@expo/vector-icons/Feather`

### ISSUE THREAD

**Issue by romk1n** [expo/expo#1083]
Using expo 2.22.1 and doing udemy course. after adding `react-native-elements` using `yarn add` getting the following error:

```
Unable to resolve module `@expo/vector-icons/Feather` from `/Users/rom/udemy/advanced-react/swipe/node_modules/react-native-elements/src/helpers/getIconType.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

ABI21_0_0RCTFatal
-[ABI21_0_0RCTBatchedBridge stopLoadingWithError:]
__34-[ABI21_0_0RCTBatchedBridge start]_block_invoke_2
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0
```

I tried deleting `node_modules` and running yarn and expo again, the same issue.

**Comment by ide** [comment]
It's hard to say what's going on here but I would make sure that `node_modules/@expo/vector-icons` has various contents and that you can run a project made with `exp init` as well, without any extra code. Take small steps so you can more precisely identify when things go wrong.

This post also explains how to clear various caches that could also be causing issues: https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352

**Comment by romk1n** [comment]
The way I fixed is by `yarn add @expo/vector-icons`

**Comment by tutak** [comment]
If using npm try uninstalling @expo/vector-icons and reinstalling.

`npm uninstall @expo/vector-icons --save`

and then

`npm install @expo/vector-icons --save`

**Comment by EliteCRM** [comment]
I tried many ways, but no one worked for me!!!

**Comment by kumbhar-ketan** [comment]
@EliteCRM  Same happened with me. Guys if someone have the solution then please let us know. Thanks.

**Comment by igorbrandao** [comment]
+1, also having this annoying issue which is a heavy blocker :(

**Comment by eandrad2** [comment]
@igorbrandao did you fix this problem?

**Comment by igorbrandao** [comment]
I went back to a version of package.json that worked for my project and figured that the culprit was `native-base` lib. In the latest version (2.9.0) it gives this error, but in 2.8.1 it does not. Hope it helps!

**Comment by ghasemikasra39** [comment]
I have the same issue: https://stackoverflow.com/questions/56268228/expo-dependencies-in-other-libraries-after-ejection
installing `yarn add @expo/vector-icons --save` causes another error: `cannot resolve module expo` 
running these also not helping:
```
rm -rf node_modules yarn.lock package-lock.json
yarn && yarn add react-native-elements
yarn add react-native-vector-icons
react-native link react-native-vector-icons
```
