### ISSUE TITLE
Error building with use_frameworks in Expo 39

### ISSUE THREAD

**Issue by carsondarling** [expo/expo#10841]
### Summary of Issue

Enabling `use_frameworks!` with Expo 39 causes the build fail in Xcode. This happens using the `bare-minimal` template, and appears to be an issue with the linking of `react-native-screens` and `react-native-gesture-handler`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.1, 29.0.2
        System Images: android-26 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.3
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: bare
```

### Reproducible Demo

Demo project created using the steps below:
https://github.com/carsondarling/expo39_use_frameworks_error_demo
 
### Steps to Reproduce

1. `expo init --npm --template bare-minimum`
2. Update Podfile to enable `use_frameworks!` and remove Flipper:
```ruby
# ios/Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'expo39useframeworkserrordemo' do
  use_frameworks!
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
end
```
2. `cd ios && pod install`
3. Attempting to build in Xcode now fails when linking `react-native-screens` and `react-native-gesture-handler` with the errors below:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTFont", referenced from:
      objc-class-ref in RNSScreenStackHeaderConfig.o
  "_RCTIsMainQueue", referenced from:
      -[RNSScreenContainerManager markUpdated:] in RNSScreenContainer.o
  "__RCTAssertFormat", referenced from:
      -[RNSScreenContainerManager markUpdated:] in RNSScreenContainer.o
      -[RNSScreenStackView setModalViewControllers:] in RNSScreenStack.o
  "_OBJC_CLASS_$_RCTRootContentView", referenced from:
      objc-class-ref in RNSScreenStack.o
  "_RCTRegisterModule", referenced from:
      +[RNSScreenManager load] in RNSScreen.o
      +[RNSScreenContainerManager load] in RNSScreenContainer.o
      +[RNSScreenStackManager load] in RNSScreenStack.o
      +[RNSScreenStackHeaderConfigManager load] in RNSScreenStackHeaderConfig.o
      +[RNSScreenStackHeaderSubviewManager load] in RNSScreenStackHeaderConfig.o
  "_OBJC_CLASS_$_RCTConvert", referenced from:
      __OBJC_$_CATEGORY_RCTConvert_$_RNSScreen in RNSScreen.o
      __OBJC_$_CATEGORY_RCTConvert_$_RNSScreenStackHeader in RNSScreenStackHeaderConfig.o
  "_OBJC_CLASS_$_RCTRootView", referenced from:
      objc-class-ref in RNSScreen.o
  "_OBJC_METACLASS_$_RCTViewManager", referenced from:
      _OBJC_METACLASS_$_RNSScreenManager in RNSScreen.o
      _OBJC_METACLASS_$_RNSScreenContainerManager in RNSScreenContainer.o
      _OBJC_METACLASS_$_RNSScreenStackManager in RNSScreenStack.o
      _OBJC_METACLASS_$_RNSScreenStackHeaderConfigManager in RNSScreenStackHeaderConfig.o
      _OBJC_METACLASS_$_RNSScreenStackHeaderSubviewManager in RNSScreenStackHeaderConfig.o
  "_OBJC_METACLASS_$_RCTView", referenced from:
      _OBJC_METACLASS_$_RNSScreenView in RNSScreen.o
  "_RCTExecuteOnMainQueue", referenced from:
      -[RNSScreenContainerManager markUpdated:] in RNSScreenContainer.o
  "_OBJC_CLASS_$_RCTTouchHandler", referenced from:
      objc-class-ref in RNSScreen.o
  "_OBJC_CLASS_$_RCTView", referenced from:
      _OBJC_CLASS_$_RNSScreenView in RNSScreen.o
  "_OBJC_CLASS_$_RCTViewManager", referenced from:
      _OBJC_CLASS_$_RNSScreenManager in RNSScreen.o
      _OBJC_CLASS_$_RNSScreenContainerManager in RNSScreenContainer.o
      _OBJC_CLASS_$_RNSScreenStackManager in RNSScreenStack.o
      _OBJC_CLASS_$_RNSScreenStackHeaderConfigManager in RNSScreenStackHeaderConfig.o
      _OBJC_CLASS_$_RNSScreenStackHeaderSubviewManager in RNSScreenStackHeaderConfig.o
  "_RCTConvertEnumValue", referenced from:
      +[RCTConvert(RNSScreen) RNSScreenStackPresentation:] in RNSScreen.o
      +[RCTConvert(RNSScreen) RNSScreenStackAnimation:] in RNSScreen.o
      +[RCTConvert(RNSScreen) RNSScreenReplaceAnimation:] in RNSScreen.o
      +[RCTConvert(RNSScreenStackHeader) RNSScreenStackHeaderSubviewType:] in RNSScreenStackHeaderConfig.o
      +[RCTConvert(RNSScreenStackHeader) UIBlurEffectStyle:] in RNSScreenStackHeaderConfig.o
  "__RCTLogNativeInternal", referenced from:
      -[RNSScreenView setStackPresentation:] in RNSScreen.o
      -[RNSScreenStackView insertReactSubview:atIndex:] in RNSScreenStack.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTScrollView", referenced from:
      objc-class-ref in RNNativeViewHandler.o
  "__RCTAssertFormat", referenced from:
      -[RNGestureHandlerRegistry attachHandlerWithTag:toView:] in RNGestureHandlerRegistry.o
  "_OBJC_METACLASS_$_RCTViewManager", referenced from:
      _OBJC_METACLASS_$_RNGestureHandlerButtonManager in RNGestureHandlerModule.o
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      _OBJC_CLASS_$_RNGestureHandlerModule in RNGestureHandlerModule.o
  "__RCTNotImplementedException", referenced from:
      -[RNGestureHandlerEvent init] in RNGestureHandlerEvents.o
      -[RNGestureHandlerStateChange init] in RNGestureHandlerEvents.o
  "_RCTGetUIManagerQueue", referenced from:
      -[RNGestureHandlerModule methodQueue] in RNGestureHandlerModule.o
  "_OBJC_CLASS_$_RCTConvert", referenced from:
      objc-class-ref in RNFlingHandler.o
      objc-class-ref in RNForceTouchHandler.o
      objc-class-ref in RNGestureHandler.o
      objc-class-ref in RNGestureHandlerModule.o
      objc-class-ref in RNLongPressHandler.o
      objc-class-ref in RNNativeViewHandler.o
      objc-class-ref in RNPanHandler.o
      ...
  "_RCTRegisterModule", referenced from:
      +[RNGestureHandlerButtonManager load] in RNGestureHandlerModule.o
      +[RNGestureHandlerModule load] in RNGestureHandlerModule.o
  "_OBJC_CLASS_$_RCTRootView", referenced from:
      objc-class-ref in RNGestureHandlerManager.o
  "_RCTDefaultLogFunction", referenced from:
      -[RNGestureHandlerManager registerRootViewIfNeeded:] in RNGestureHandlerManager.o
      -[RNGestureHandlerManager dealloc] in RNGestureHandlerManager.o
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_RNGestureHandlerModule in RNGestureHandlerModule.o
  "_OBJC_CLASS_$_RCTTouchHandler", referenced from:
      objc-class-ref in RNRootViewGestureRecognizer.o
  "_OBJC_CLASS_$_RCTViewManager", referenced from:
      _OBJC_CLASS_$_RNGestureHandlerButtonManager in RNGestureHandlerModule.o
  "__RCTLogNativeInternal", referenced from:
      -[RNGestureHandler configure:] in RNGestureHandler.o
      -[RNGestureHandlerManager createGestureHandler:tag:config:] in RNGestureHandlerManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Expected Behavior vs Actual Behavior

Expected: Able to use `use_frameworks!` with Expo 39
Actual: Build fails as soon as `use_frameworks!` is added

It's entirely possible that I'm missing some key step here, but I've been staring at this for a while now and haven't been able to come up with a solution.

**Comment by matteocargnelutti** [comment]
I am impacted by this issue as well.
Thanks in advance,

**Comment by carsondarling** [comment]
As a quick update, I now have what might be a successful workaround for this problem. It seems that this all stems back to [facebook/react-native#29633](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116).

My steps to fix this are:
1. Update packages:
```bash
npm i --save react-native-screens@2.12.0 react-native-gesture-handler@1.8.0 react-native-reanimated@1.13.1
```
*Note: The only one that seems to actually matter is react-native-screens@2.12.0, but I left the others there as I had already done the update and don't have time to test with the earlier versions. I've already lost too much time to this bug.*

2. Patch dependencies that still depend on `React` instead of `React-Core`. I believe this can be done fairly seamlessly through [`patch-package`](https://www.npmjs.com/package/patch-package), but I'm still working through it.
```diff
diff --git a/node_modules/expo-updates/ios/EXUpdates.podspec b/node_modules/expo-updates/ios/EXUpdates.podspec
index 7082722..c5faa6b 100644
--- a/node_modules/expo-updates/ios/EXUpdates.podspec
+++ b/node_modules/expo-updates/ios/EXUpdates.podspec
@@ -17,7 +17,7 @@ Pod::Spec.new do |s|
   s.requires_arc   = true
 
   s.dependency 'UMCore'
-  s.dependency 'React'
+  s.dependency 'React-Core'
 
   s.test_spec 'Tests' do |test_spec|
     test_spec.source_files = 'Tests/*.{h,m}'
```
```diff
diff --git a/node_modules/react-native-gesture-handler/RNGestureHandler.podspec b/node_modules/react-native-gesture-handler/RNGestureHandler.podspec
index d53738c..1922b04 100644
--- a/node_modules/react-native-gesture-handler/RNGestureHandler.podspec
+++ b/node_modules/react-native-gesture-handler/RNGestureHandler.podspec
@@ -14,6 +14,6 @@ Pod::Spec.new do |s|
   s.source       = { :git => "https://github.com/software-mansion/react-native-gesture-handler", :tag => "#{s.version}" }
   s.source_files = "ios/**/*.{h,m}"
 
-  s.dependency "React"
+  s.dependency "React-Core"
 
 end
```
```diff
diff --git a/node_modules/react-native-reanimated/RNReanimated.podspec b/node_modules/react-native-reanimated/RNReanimated.podspec
index 30be3ca..1939eb9 100644
--- a/node_modules/react-native-reanimated/RNReanimated.podspec
+++ b/node_modules/react-native-reanimated/RNReanimated.podspec
@@ -19,6 +19,6 @@ Pod::Spec.new do |s|
   s.source_files = "ios/**/*.{h,m}"
   s.requires_arc = true
 
-  s.dependency "React"
+  s.dependency "React-Core"
 end
 ```

At that point the project **should** build. I ended up having to remove the Flipper-related code from AppDelegate.m (see [this issue](https://github.com/facebook/flipper/issues/1326)).

This patch will be relevant until the changes get added to their respective projects, a new version is released, and the Expo team decide to update the dependency.

For anyone on the @expo team, what needs to be done to add testing to the build process to make sure that `use_frameworks` doesn't break future builds? This isn't the first time in recent history that `use_frameworks` was broken in new releases (see #7610).

**Comment by carsondarling** [comment]
It appears that some of the fixes are in the pipeline:
- `react-native-gesture-handler`: software-mansion/react-native-gesture-handler#1193
- `react-native-reanimated`: No updates, hotfix might be necessary unless Expo wants to upgrade to v2
- `expo-updates`:  No update in master yet.

**Comment by brentvatne** [comment]
@carsondarling - we can update the dependency to React-Core for each of our libraries and roll out the changes the next time they are ready to release. patch-package is a good workaround for now, as you suggested.

> For anyone on the @expo team, what needs to be done to add testing to the build process to make sure that use_frameworks doesn't break future builds? This isn't the first time in recent history that use_frameworks was broken in new releases (see #7610).

can you suggest a strategy for testing that we could use here? It may also be worth using the same strategy to catch regressions in react-native itself, given that the problems we are facing now are due to unannounced breaking changes in react-native (if I understand it correctly)

**Comment by carsondarling** [comment]
@brentvatne I really appreciate the quick follow up.

As for a strategy, I'm not familiar at all with the setup of Expo's codebase, nor it's release/testing process. One approach would be to automate using Expo as an end user would. In that scenario, you'd install `expo-cli`, initialize a fresh Expo project using a template for the proposed release, eject from Expo, make the necessary changes for `use_frameworks` and then build the resulting project. It's certainly not the cleanest solution, but it does at least verify that end users can rely on using `use_frameworks` in their project. If the [Expo 33 release notes](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c) hadn't explicitly mentioned support for `use_frameworks`, I would have assumed that Expo simply did not support that use case at all.

@brentvatne Any chance you could point me to where the `bare-minimum` workflow is tested? In my (admittedly extremely limited) poking around, I haven't quite figured out where that lives.

**Comment by brentvatne** [comment]
we document our release and testing workflow here:https://github.com/expo/expo/blob/master/guides/releasing/Release%20Workflow.md

we don't have integration tests for the template projects, rather we test all of the other pieces that go into it and then do a smoke test on each prior to releasing

**Comment by carsondarling** [comment]
@brentvatne I'll certainly look into it. Unfortunately I'm pretty much completely swamped right now so the raw hours I'll have available. to put into it are fairly minimal in the short term.

Thanks again your help!
