### ISSUE TITLE
issue with build in android ?

### ISSUE THREAD

**Issue by bhram** [expo/expo#1084]
hi , i build my app it's showing in device  in first time the last build but when be offline and reconnect or in some how i don't know exactly , it's show the previous build ??? 

i so tried from this problem :( , and sorry for my bad English i wish i had enplane the issues currently

**Comment by ide** [comment]
Hi, please see: https://docs.expo.io/versions/latest/guides/how-expo-works.html#publishingdeploying-an-expo-app-in-production

> As soon as the publish is complete, the new version of your code is available to all your existing users. They’ll download the updated version next time they open the app or refresh it, provided that they have a version of the Expo client that supports the sdkVersion specified in your app.json.
>
> Updates are handled differently on iOS and Android. On Android, updates are downloaded in the background. This means that the first time a user opens your app after an update they will get the old version while the new version is downloaded in the background. The second time they open the app they’ll get the new version. On iOS, updates are downloaded synchronously, so users will get the new version the first time they open your app after an update.
