### ISSUE TITLE
Android standalone app crashes when using image prop on MapView.Marker

### ISSUE THREAD

**Issue by uchamb** [expo/expo#10846]
## 🐛 Bug Report

This is exactly the same issue 2 years ago:
https://github.com/expo/expo/issues/1431

It happens again in SDK39. It was working fine in SDK38

I guess something has changed in asset bundling.

It's happening only for standalone Android apps.
Here is the log from adb logcat:

> unknown:ViewManager: Error while updating prop image
unknown:ViewManager: java.lang.reflect.InvocationTargetException
unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:4)
unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:2)
unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:9)
unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3)
unknown:ViewManager: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:8)
unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:2)
unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:15)
unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:10)
unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:1)
unknown:ViewManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:6)
unknown:ViewManager: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
unknown:ViewManager: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
unknown:ViewManager: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
unknown:ViewManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
unknown:ViewManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
unknown:ViewManager: 	at android.view.Choreographer.doFrame(Choreographer.java:727)
unknown:ViewManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:907)
unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:216)
unknown:ViewManager: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
unknown:ViewManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
unknown:ViewManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
unknown:ViewManager: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
unknown:ViewManager: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:248)
unknown:ViewManager: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:939)
unknown:ViewManager: 	at android.content.res.Resources.getDrawable(Resources.java:879)
unknown:ViewManager: 	at android.content.res.Resources.getDrawable(Resources.java:854)
unknown:ViewManager: 	at versioned.host.exp.exponent.modules.api.components.maps.AirMapMarker.setImage(AirMapMarker.java:17)
unknown:ViewManager: 	at versioned.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager.setImage(AirMapMarkerManager.java:1)
unknown:ViewManager: 	... 25 more
unknown:DisabledDevSupportManager: Caught exception
unknown:DisabledDevSupportManager: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'image' of a view managed by: AIRMapMarker
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:13)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:2)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:9)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:8)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:2)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:15)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:10)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:1)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:6)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:1)
unknown:DisabledDevSupportManager: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:7)
unknown:DisabledDevSupportManager: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:1)
unknown:DisabledDevSupportManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
unknown:DisabledDevSupportManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
unknown:DisabledDevSupportManager: 	at android.view.Choreographer.doFrame(Choreographer.java:727)
unknown:DisabledDevSupportManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
unknown:DisabledDevSupportManager: 	at android.os.Handler.handleCallback(Handler.java:907)
unknown:DisabledDevSupportManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
unknown:DisabledDevSupportManager: 	at android.os.Looper.loop(Looper.java:216)
unknown:DisabledDevSupportManager: 	at android.app.ActivityThread.main(ActivityThread.java:7464)
unknown:DisabledDevSupportManager: 	at java.lang.reflect.Method.invoke(Native Method)
unknown:DisabledDevSupportManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
unknown:DisabledDevSupportManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
unknown:DisabledDevSupportManager: Caused by: java.lang.reflect.InvocationTargetException
unknown:DisabledDevSupportManager: 	at java.lang.reflect.Method.invoke(Native Method)
unknown:DisabledDevSupportManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:4)
unknown:DisabledDevSupportManager: 	... 23 more
unknown:DisabledDevSupportManager: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
unknown:DisabledDevSupportManager: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:248)
unknown:DisabledDevSupportManager: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:939)
unknown:DisabledDevSupportManager: 	at android.content.res.Resources.getDrawable(Resources.java:879)
unknown:DisabledDevSupportManager: 	at android.content.res.Resources.getDrawable(Resources.java:854)
unknown:DisabledDevSupportManager: 	at versioned.host.exp.exponent.modules.api.components.maps.AirMapMarker.setImage(AirMapMarker.java:17)
unknown:DisabledDevSupportManager: 	at versioned.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager.setImage(AirMapMarkerManager.java:1)
unknown:DisabledDevSupportManager: 	... 25 more

### Reproducible Demo

This is the Demo app to reproduce the error:
https://github.com/uchamb/expo-map-marker-test
 
It's only Android issue, works great on iOS.

This is already built APK if you want to debug yourself (You need to click "show markers" button to see error):
https://drive.google.com/file/d/1fEy3c5YZVUkfUOpNJaxNXjTuy4g-4bSS/view?usp=sharing

**Comment by uchamb** [comment]
The solution is to exclude marker icon from "assetBundlePatterns"
So the actual problem is that react-native-maps doesn't support assets bundled by Expo SDK39

**Comment by imshreyansh** [comment]
@uchamb Is there any workaround for this ? Will you help me and tell me how to fix this ?

**Comment by imshreyansh** [comment]
@byCedric can you help ?

**Comment by imshreyansh** [comment]
This workaround will surely help

`<Marker 
  key={marker.id} 
  coordinate={{latitude: parseFloat(marker.lat), longitude: 
  parseFloat(marker.lng)}} 
  title={marker.name} 
  description={marker.description} 
  onCalloutPress={() => this.details(marker.id, marker.cover)} />

   <Image source={require('../../assets/logo-marker.png')} style={{height: 35, width:35 }} />

</Marker>`

**Comment by Tim-byte-afk** [comment]
> This workaround will surely help
> 
> ```
> <Marker 
>   key={marker.id} 
>   coordinate={{latitude: parseFloat(marker.lat), longitude: 
>   parseFloat(marker.lng)}} 
>   title={marker.name} 
>   description={marker.description} 
>   onCalloutPress={() => this.details(marker.id, marker.cover)} />
> 
>    <Image source={require('../../assets/logo-marker.png')} style={{height: 35, width:35 }} />
> 
> </Marker>
> ```

Hi, thanks for the solution. But because of this, when drawing a large number of objects, there are brakes.

**Comment by imshreyansh** [comment]
@Tim-byte-afk  Can you please explain your issue !

**Comment by Tim-byte-afk** [comment]
> @Tim-byte-afk Can you please explain your issue !

I don't know exactly what this is connected with. I am drawing 160 objects on the map. 
In SDK38 and use image={require('...')} - everything worked smoothly.
In SDK39 image={require('...')}  does not work, I used yours solution and map slows down very much.

**Comment by imshreyansh** [comment]
@Tim-byte-afk  I am not sure whether it is happening in development or in production for you, but i will suggest you to create a standalone app of your project and then check on the performance of the map loading like whether it is loading slow or not.

**Comment by uchamb** [comment]
> > @Tim-byte-afk Can you please explain your issue !
> 
> I don't know exactly what this is connected with. I am drawing 160 objects on the map.
> In SDK38 and use image={require('...')} - everything worked smoothly.
> In SDK39 image={require('...')} does not work, I used yours solution and map slows down very much.

Did you try to exclude marker icon from "assetBundlePatterns"?
This worked for me.
