### ISSUE TITLE
I'm also still seeing this issue. This code produces the above error, `Trigger of type: calendar is not supported on Android.`:

### ISSUE THREAD

**Issue by twwspes** [expo/expo#10853]
I'm also still seeing this issue. This code produces the above error, `Trigger of type: calendar is not supported on Android.`:

```js
await Notifications.scheduleNotificationAsync({
    content: { body: 'Hello' },
    trigger: { channelId: 'default', hour: 10, minute: 23, repeats: true },
});
```

This code does nothing (note the omitted `channelId`):

```js
await Notifications.scheduleNotificationAsync({
    content: { body: 'Hello' },
    trigger: { hour: 10, minute: 23, repeats: true },
});
```

_Originally posted by @bakerkretzmar in https://github.com/expo/expo/issues/8996#issuecomment-710079999_

**Comment by twwspes** [comment]
Having checked the expo-notifications/build/scheduleNotificationAsync.js, I find a function called "isDailyTriggerInput" which is to check whether the trigger inside the scheduleNotificationAsync is DailyNotificationTrigger or not.  The condition of being a DailyNotificationTrigger is that it must contain 3 keys, namely hour, minute, and repeats.  If we add the optional condition channelId by following the documentation https://docs.expo.io/versions/latest/sdk/notifications/#dailynotificationtrigger, the above condition will never be satisfied.  At the end the trigger { channelId: 'default', hour: 10, minute: 23, repeats: true } will fall into type calendarNotificationTrigger.  My suggestion is that should we add "const { channelId, ...triggerWithoutChannelId } = trigger;" in line 81 of expo-notifications/build/scheduleNotificationAsync.js to solve the problem?

**Comment by twwspes** [comment]
I have tried this on android expo app and it runs as I expected

**Comment by bakerkretzmar** [comment]
@twwspes are you on SDK version 38 or 39?

**Comment by bakerkretzmar** [comment]
SDK 39 fixed this for me, see #10673

**Comment by twwspes** [comment]
Mine is 39. Dunno if there is any minor update.  or if the version of expo- notifications matters.  Let me check it out tomorrow

**Comment by byCedric** [comment]
If you are unsure if you have the latest `expo-notifications`, don't forget about `expo install expo-notifications`. That command will install the most up-to-date version of any expo library compatible with your Expo SDK version 😄

**Comment by twwspes** [comment]
Thanks for the advice. My expo-notifications is ~0.7.2 which is the latest for now.  I have checked the changelog just now and saw @sjchmiela had already merge a fix to master branch of expo https://github.com/expo/expo/pull/10454.  The revised code is not yet available in sdk-39 branch though; so we may still come across this issue.  Looks like it will be publish in near future.  By considering that, I will close the issue and try wait for update.  Thanks mates!
