### ISSUE TITLE
The google login not completed the process in the .apk file but in the Android emulator work fine.

### ISSUE THREAD

**Issue by romelgomez** [expo/expo#10860]
### Summary of Issue 

The google login not completed the process, onAuthStateChanged never it get called **in the apk build installed** in the phone. 

In the Android emulator works O.K, but not in the .apk

#### Google Login Works in

- [x] Web - **Video**: [https://youtu.be/UyWPda3DQoc](https://youtu.be/UyWPda3DQoc)
- [x] Android emulator - **Video**: [https://youtu.be/HuZhiJRvUaA](https://youtu.be/HuZhiJRvUaA)
- [ ] Android Apk - **Video**: [https://youtu.be/ZgQkrFry_6o](https://youtu.be/ZgQkrFry_6o)
 

**Source Code:** [https://github.com/romelgomez/expo0auth](https://github.com/romelgomez/expo0auth)

**Web demo:** [https://expo0auth.web.app/](https://expo0auth.web.app/)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Platforms: 
- Android
- Web 

```
  Expo CLI 3.28.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 10.19.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.config/yarn/global/node_modules/.bin/npm
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed
```

### Reproducible Demo

[https://expo.io/@autana/projects/expo0auth](https://expo.io/@autana/projects/expo0auth)

### Steps to Reproduce

**Apk example:** [https://expo.io/artifacts/2d532756-f6d3-4313-98b2-2ea693a44f54](https://expo.io/artifacts/2d532756-f6d3-4313-98b2-2ea693a44f54)

- Try login with google
- Select any google acount 

### Expected Behavior vs Actual Behavior

- View the page with the message **The user exist** 

![Screenshot from 2020-10-29 11-05-05](https://user-images.githubusercontent.com/2358251/97600024-9ea15100-19d6-11eb-9794-5dd0efc85fdc.png)

**Comment by byCedric** [comment]
Hi @romelgomez, thanks for the issue report. Could you also provide the code of the reproducible example? Without that, we can't test any potential bug fix for this issue.

**Comment by romelgomez** [comment]
Hi @byCedric, sorry I thought i included it

https://github.com/romelgomez/expo0auth

**Comment by romelgomez** [comment]
Hi @byCedric  


https://github.com/romelgomez/expo0auth/blob/main/src/auths/google.auth.tsx#L14

With auth-session flow in android ... `import { useIdTokenAuthRequest } from 'expo-auth-session/providers/google';`

We get `{"type":"dismiss"}` in the `then` block:

```javascript
const login = (promptAsync: PromptAsync) => {
  promptAsync()
    .then((response: AuthSessionResult | null) => {
```

![Screenshot from 2020-11-03 08-41-27](https://user-images.githubusercontent.com/2358251/97992333-8b183080-1db0-11eb-8244-d1de643636e9.png)

As a workaround, we implement another flow for android calling the `logInAsync` method of package `expo-google-app-auth`. This other flow successfully return the `idToken`. We use **idToken** to to signIn again using signInWithCredential of firebase to keep the auth state in control of firebase, in this way we no need to use localstorage or expo-secure-store for the moment to know the auth state of the user. 

`import { logInAsync, LogInResult } from 'expo-google-app-auth';` 

If **promptAsync**  `const [request, _, promptAsync] = useIdTokenAuthRequest({` should return the auth token or the **id_token** in android, it's maybe possibly an AuthSession bug. 

Please let me know what do you thinks, and if there is a bug here please, tag-me to track the solution.

**Comment by fafo** [comment]
same issue confirmed here

**Comment by thebuddysystem** [comment]
I couldn't get AuthSession to work for me either, so my current workaround is to use the google-sign-in lib in standalone and AuthSession in expo client. I saw others opening bugs about this and doing the same thing.  

I think they need to fix the library for proper native implementation, or their documentation on how to use it.

**Comment by Jamedjo** [comment]
I think this happens because the redirect callback is picked up by the intent-filter in `<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">` instead of reaching `expo-web-browser`'s  `Linking.addEventListener('url', _redirectHandler)`.

When the app state changes from `background` to `active` this causes the `expo-web-browser` to act as if the browser had been dismissed because expo was re-activated without a redirect.

To have the redirect handled in react-native I needed to:
1. Avoid hitting the openid intent by updating AndroidManifest.xml with a path filter that actually works, `<data android:host="*" android:path="/oauthredirect" android:scheme="com.my.app"/>`.
2. Add a second intent filter for `expo-auth-session`, `<data android:host="*" android:path="/expo_oauthredirect" android:scheme="com.my.app"/>` under the main activity.
3. Use a native redirect callback that will hit our new intent-filter, `native: "" + Application.applicationId + ":///expo_oauthredirect"`

I've written in more detail at https://github.com/expo/expo/issues/9677#issuecomment-782558428, as I found that issue first and there is a lot of overlap.

**Comment by palaganaskurl** [comment]
Any updates on this issue? Encountering the same thing. (Expo Auth Google + Firebase) On Expo Go, it works fine, but on Android Standalone Build, after choosing a Google account, it just shows a loading spinner then exists webview but the response variable remains null

``
const [, response, promptAsync] = Google.useIdTokenAuthRequest({
  clientId: FirebaseClientID,
}); 
``

**Comment by thomas-coldwell** [comment]
For me the one thing that made this work was to set my intent filter simply as this in the `AndroidManifest.xml` file. Seems to fix the linking back into the app giving a modal to say which app do you want to open the redirect with and then selecting the app.
![image](https://user-images.githubusercontent.com/31568400/118254929-8345f100-b4a3-11eb-9559-6c62fcdb5cfb.png)
![Screenshot_1620986384](https://user-images.githubusercontent.com/31568400/118254946-89d46880-b4a3-11eb-9e79-5af57b48ae78.png)


Hope this helps!

**Comment by jenwit07** [comment]
Confirm this issue, it's working well on Expo go ,but on apk doesn't work

**Comment by ONaggar** [comment]
I faced the same problem using expo-auth-session. Referring to [AuthSession](https://docs.expo.io/versions/latest/sdk/auth-session/#usage-in-standalone-apps) documentation, the scheme should be the same as android.package in app.json, as mentioned [here](https://docs.expo.io/guides/authentication/#android-native): "Your app needs to conform to the URI scheme matching your android.package (ex. com.myname.mycoolapp:/)". Now everything's work fine after changing it. Hope this helps.

**Comment by lpambagoda** [comment]
@ONaggar can you please kindly let us know what exactly did you use under "scheme" property in app.json
is it 
1) "scheme":"com.myname.mycoolapp" 
or 
2) "scheme":"com.myname.mycoolapp:/"

**Comment by AnimatorJoe** [comment]
> @ONaggar can you please kindly let us know what exactly did you use under "scheme" property in app.json
> is it
> 
> 1. "scheme":"com.myname.mycoolapp"
>    or
> 2. "scheme":"com.myname.mycoolapp:/"

Same question

**Comment by ONaggar** [comment]
@lma

> @ONaggar can you please kindly let us know what exactly did you use under "scheme" property in app.json
> is it
> 
> 1. "scheme":"com.myname.mycoolapp"
>    or
> 2. "scheme":"com.myname.mycoolapp:/"

@lpambagoda I used "scheme": "com.myname.mycoolapp"

**Comment by pedralho** [comment]
> I faced the same problem using expo-auth-session. Referring to [AuthSession](https://docs.expo.io/versions/latest/sdk/auth-session/#usage-in-standalone-apps) documentation, the scheme should be the same as android.package in app.json, as mentioned [here](https://docs.expo.io/guides/authentication/#android-native): "Your app needs to conform to the URI scheme matching your android.package (ex. com.myname.mycoolapp:/)". Now everything's work fine after changing it. Hope this helps.

Using the scheme as proposed here, make it possible to complete the authentication process. However, now it becomes necessary to choose an application to be opened after the authentication completion. It's the same as the reported by @thomas-coldwell.

Did I miss something? Is there any way to make it user friendlier?

**Comment by pedralho** [comment]
> > I faced the same problem using expo-auth-session. Referring to [AuthSession](https://docs.expo.io/versions/latest/sdk/auth-session/#usage-in-standalone-apps) documentation, the scheme should be the same as android.package in app.json, as mentioned [here](https://docs.expo.io/guides/authentication/#android-native): "Your app needs to conform to the URI scheme matching your android.package (ex. com.myname.mycoolapp:/)". Now everything's work fine after changing it. Hope this helps.
> 
> Using the scheme as proposed here, make it possible to complete the authentication process. However, now it becomes necessary to choose an application to be opened after the authentication completion. It's the same as the reported by @thomas-coldwell.
> 
> Did I miss something? Is there any way to make it user friendlier?

I found another discussion related to this and, in my opinion, the best workaround to no have the choose app modal so far is that one:
https://github.com/expo/expo/issues/12044#issuecomment-877843137

**Comment by tlmader** [comment]
@pedralho On #12044, the following step is recommended:
> Use a expo.scheme different than expo.android.package (I am using a single word without symbols or special characters)
However, the discussion here is recommending to use the same scheme as `android.package`. What's currently working for you?

**Comment by tlmader** [comment]
> For me the one thing that made this work was to set my intent filter simply as this in the `AndroidManifest.xml` file. Seems to fix the linking back into the app giving a modal to say which app do you want to open the redirect with and then selecting the app.
> ![image](https://user-images.githubusercontent.com/31568400/118254929-8345f100-b4a3-11eb-9559-6c62fcdb5cfb.png)
> ![Screenshot_1620986384](https://user-images.githubusercontent.com/31568400/118254946-89d46880-b4a3-11eb-9e79-5af57b48ae78.png)
> 
> Hope this helps!

I was able to get sign in with Cognito User Pools + amplify-js + AuthSession in an Expo Android standalone build using the workaround shared by @thomas-coldwell with the following in `app.json`:

```
    "android": {
      "package": "com.patinaproject.app.development",
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "intentFilters": [
        {
          "action": "VIEW",
          "category": ["BROWSABLE", "DEFAULT"],
          "data": {
            "scheme": "com.patinaproject.app.development"
          }
        }
      ]
    },
```

**Comment by harismh** [comment]
FWIW, I experienced the same issue on our managed EAS app while attempting to authenticate with Azure: on APK builds only, AuthSession yields a "dismiss" message when it redirects back to the app (if at all). Followed most of the suggestions from here, #12044, #10860, and #9677 with no success. My guess is there is a bug with AuthSession itself, maybe a race condition with its listeners, or how intent filters are ultimately handled in the Manifest.xml file. 

I never was shown the prompt to open in app (the auth session simply redirected to the app instantly a la iOS). However, by running `expo prebuild` to sort of eject out and then manually adding the following to the manifest file, I was able to get the prompt to show up. However, after redirecting to the app, the same "dismiss" problem occurs, so all of these changes don't fix the underlying bug.

```xml
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="training.flip.dhg" android:path="/oauth-redirect" />
    </intent-filter>
</activity>
```

Expo diagnostics output for those curious (apparently SDK 43 doesn't fix the issue either):

```bash
npmPackages:
  expo: ^41.0.0 => 41.0.1 
  expo-crypto: 9.2.0
  expo-random: 11.2.0
  expo-auth-session: 3.3.1
  react: 16.13.1 => 16.13.1 
  react-dom: 16.13.1 => 16.13.1 
  react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.4 
  react-native-web: ~0.13.12 => 0.13.18 
Expo Workflow: managed
```

Android config in our app.json

```json
"android": {
  "package": "training.flip.dhg",
  "versionCode": 100,
  "adaptiveIcon": {
    "foregroundImage": "./assets/android-icon-fg.png",
    "backgroundImage": "./assets/android-icon-bg.png"
  },
  "intentFilters": [
    {
      "action": "VIEW",
      "data": [
        {
          "scheme": "training.flip.dhg"
        }
      ],
      "category": [
        "BROWSABLE",
        "DEFAULT"
      ]
    }
  ]
}
```

Gist of our Azure login code (largely follows the official docs, useAuthDiscovery, useAuthRequest, etc.): https://gist.github.com/harismh/e823422f0dbc310b2d77da35b089d3ea. A reproducible snack would be difficult to share given the need for Azure credentials and redirect URIs, but the above gist provides most of the code.

Any expedience from the Expo team in resolving this would be super appreciated as `expo-auth-session` is DOA for us currently.

**Comment by danielkv** [comment]
I'm dealing with the same problem here.

I've already tried all the suggestions in this issue. Nothing worked! I'm about to release the app, so I REALLY need something on this.

Ps: The problem also only occurs on Android Standalone app

**Comment by harismh** [comment]
Quick update: managed to get our Azure redirect working on a standalone Android production build! I looked through some of the source code/default configs of the Expo Go app in order to see why redirects were working on the emulator and managed to adapt that config to work on production.

On my Expo emulator, the redirect URL set when calling AuthSession.makeRedirectUri is (if you don't set the native prop override): `exp://localhost:19000/--/oauth-redirect`. This translates generically to `ANDROID_PACKAGE://WEBSITE_HOST/--/REDIRECT_PATH`. To make this work, I used the following intent filters:

```json
"scheme": "SOME_STRING",
android: {
  "package": "SAME_SCHEME_STRING",
  "intentFilters": [
        {
          "action": "VIEW",
          "data": [
            {
              "scheme": "https",
              "host": "WEBSITE_HOST",
              "pathPrefix": "/"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        },
        {
          "action": "VIEW",
          "data": [
            {
              "scheme": "SAME_SCHEME_STRING",
              "host": "SAME_WEBSITE_HOST",
              "path": "oauth-redirect"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
}
```

Then, for the redirect uri, I used the following:

```js
const isDev = Constants.manifest.packagerOpts?.dev ?? false;
const scheme = Constants.manifest.scheme;
const redirectUri = makeRedirectUri({
    scheme,
    path:
      Platform.OS === "android" && !isDev
        ? "SAME_WEBSITE_HOST/--/oauth-redirect"
         : isDev ? "/oauth-redirect" : "/--/oauth-redirect" // Expo Go already adds the -- for you
    preferLocalhost: isDev
  });
```

Then, to make Azure work, I added the following redirect Uris in the manifest file:
```json
 "replyUrlsWithType": [
      {
          "url": "SCHEME_STRING:///--/oauth-redirect",
          "type": "Spa"
      },
      {
          "url": "SCHEME_STRING://WEBSITE_HOST/--/oauth-redirect",
          "type": "Spa"
      },
      {
          "url": "https://WEBSITE_HOST/--/oauth-redirect",
          "type": "Spa"
      }
  ]
```

This makes Azure redirects work on iOS, Web, and Android 🙂
No idea why, but it appears that `/--/` is significant.

**Comment by danielkv** [comment]
I still didn't understand why use Azure in the middle of authentication proccess. with https://docs.expo.dev/versions/latest/sdk/google/ I haven't used at all a third party

**Comment by umarummas** [comment]
@acrdlph Please how do you make it work after removing your `"scheme": "com.myapp"` I try but didn't work. I'm using Expo Managed, and please do you have idea about Facebook? facing the same issue not responding.

**Comment by acrdlph** [comment]
@umarummas here is a working example/[mcve](https://stackoverflow.com/help/minimal-reproducible-example): https://github.com/acrdlph/expo-mcve/tree/expo-auth-sessions 
(this one even works with the `scheme` specified, so as I said in my previous post, that can't be the only reason for the issue)

You will have to work yourself up from there! Here are the steps for you:

0. Make sure that the mcve works for you, too (set up your own androidClientId in google console according to the [docs](https://docs.expo.dev/guides/authentication/#android-native) and insert it 
_Side note: If you're using Google Play App Signing you might need to take the Google SHA-1 certificate fingerprint from your [Play Console](https://play.google.com/intl/de/console/about/keymanagement/) rather than from `expo credentials:manager -p android`._
1. Start adding the other elements of your project layer by layer.
2. Continue until it breaks and when it breaks you know where the culprit lies.
3. If it never breaks, simply go on until your entire project has been reproduced on top of my working example ;)

**Comment by umarummas** [comment]
Thank you for explanation @acrdlph I checked your implementation is the same with mine, but the only difference is yours using `Google.useIdTokenAuthRequest` while my code is `Google.AuthRequest` so I don't know the differences because I'm beginner in this field.

So I decided to Published it to Store that way but my problem now is Facebook Login also do the same taking back to Login Screen after fb login. Any workaround?

**Comment by SrBrahma** [comment]
I am stuck on it for some good hours :/ No news?

**Comment by timknapp-qs** [comment]
I tried all of the work arounds above that apply to a managed expo app, but unfortunately nothing has worked for me yet in Android. I guess I'll have to stick with the deprecated `expo-google-sign-in` for now...

**Comment by ajsmth** [comment]
It would be extremely useful if someone were to share a minimal reproducible example of the issue that is going on here. There are a lot of good ideas in this thread, but we need to focus on a single example to test again and determine what the actual issue is. 

This section in the docs seems particularly relevant: https://docs.expo.dev/versions/latest/sdk/auth-session/#usage-in-standalone-apps  

Getting confirmation that those reporting issues have seen this portion of the docs will help rule it out as the culprit. This issue has had quite the lifespan, but whether its an issue of not documenting our features properly or an implementation problem, we need your help to figure this one out! Thanks!

**Comment by zhaxal** [comment]
Did you try using credentials from Expo dashboard ?

I had the same issue until I added SHA-1 key from project dashboard.

**Comment by Ahmed-Ibrahim-Anter** [comment]
same issue confirmed here

**Comment by hellotreedigital** [comment]
Same issue here, when trying app using expo run:android code is working perfectly. Yet when I build using expo build:android, promptAsync is falling

**Comment by XiangZhang0216** [comment]
> > For me the one thing that made this work was to set my intent filter simply as this in the `AndroidManifest.xml` file. Seems to fix the linking back into the app giving a modal to say which app do you want to open the redirect with and then selecting the app.
> > ![image](https://user-images.githubusercontent.com/31568400/118254929-8345f100-b4a3-11eb-9559-6c62fcdb5cfb.png)
> > ![Screenshot_1620986384](https://user-images.githubusercontent.com/31568400/118254946-89d46880-b4a3-11eb-9e79-5af57b48ae78.png)
> > Hope this helps!
> 
> I was able to get sign in with Cognito User Pools + amplify-js + AuthSession in an Expo Android standalone build using the workaround shared by @thomas-coldwell with the following in `app.json`:
> 
> ```
>     "android": {
>       "package": "com.patinaproject.app.development",
>       "adaptiveIcon": {
>         "foregroundImage": "./assets/images/adaptive-icon.png",
>         "backgroundColor": "#ffffff"
>       },
>       "intentFilters": [
>         {
>           "action": "VIEW",
>           "category": ["BROWSABLE", "DEFAULT"],
>           "data": {
>             "scheme": "com.patinaproject.app.development"
>           }
>         }
>       ]
>     },
> ```
> 
> Note that users are prompted for which app to return to, but this at least unblocks our Android release.
> 
> UPDATE: I'm now getting this problem where after sign in, users are receiving two of the same options to open the app—the left one works and authenticates, but the right one does goes back to the app and does nothing.
> 
> https://forums.expo.dev/t/app-appears-twice-on-open-with-list-after-google-auth/55659/6
> 
> UPDATE 2: I was able to workaround the "app appearing twice" issue with this approach, which bypasses the prompt completely and signs the user in: https://forums.expo.dev/t/app-appears-twice-on-open-with-list-after-google-auth/55659/8?u=tlmader

Hello @tlmader I'm also facing the double app issue, and gave your solution a try, but only seems to get an error 400: redirect_uri_mismatch on my Android physical device when app is installed from apk. I think my issue may be that on the Google cloud console the authorized redirect URIs (which can be found in a web client id credential) are only allowed in HTTPS scheme. I'm wondering how you got the redirectUri to work with the Android package name scheme (com.example.app format)?

**Comment by XiangZhang0216** [comment]
Hi, just an update on the double "open with" app issue. For me this stackoverflow page really helped. 
https://stackoverflow.com/questions/60984286/how-does-google-sign-in-for-android-work-without-a-redirect-uri
I was able to get my sign-in to bypass the double app by configuring my app.json to the following, note particularly the data section in the intent filter, the scheme is in the reverse DNS notation of the Android Client ID from Google Cloud Console:
`{
  "expo": {
    "name": "APP NAME",
    "slug": "appname",
    "scheme": "com.developername.appname",
    "android": {
      "useNextNotificationsApi": true,
      "package": "com.developername.appname",
      "intentFilters": [
        {
          "action": "VIEW",
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ],
          "data": {
            "scheme": "com.googleusercontent.apps.0123456789-whatever_your_android_client_id_is",
            "path": "/oauth2redirect"
          }
        }
      ]
    },
    "orientation": "portrait",
    "ios": {
      "bundleIdentifier": "iosbundle"
    }
  }
}`

and to use the auth request call, I used the following code, note that for the android native uri, it is simply the scheme string and path string in the intent filter data section connected with a ":" in between:
`  const [request, response, promptAsync] = Google.useIdTokenAuthRequest({
		androidClientId: '0123456789-whatever_your_android_client_id_is.apps.googleusercontent.com',
		iosClientId: '0123456789-whatever_your_ios_client_id_is.apps.googleusercontent.com',
    clientId: '0123456789-whatever_your_web_client_id_is.apps.googleusercontent.com',
		redirectUri: makeRedirectUri({
			//Enabling useProxy allows sign-in to remain functional on emulators.
			useProxy: true,
			//Reverse DNS notation of Android client ID (app.json > android > intentFilter > data > scheme)
			//+ ":" + arbitrary redirect path (app.json > android > intentFilter > data > path) in app.json.
			native: Platform.select({
				android: "com.googleusercontent.apps.0123456789-whatever_your_android_client_id_is:/oauth2redirect",
				default: undefined
			})
		})
  });`
Hopefully this can help out others who are also stuck on this.

**Comment by travishoki** [comment]
> Hi, just an update on the double "open with" app issue. For me this stackoverflow page really helped. https://stackoverflow.com/questions/60984286/how-does-google-sign-in-for-android-work-without-a-redirect-uri I was able to get my sign-in to bypass the double app by configuring my app.json to the following, note particularly the data section in the intent filter, the scheme is in the reverse DNS notation of the Android Client ID from Google Cloud Console: ![Screen Shot 2022-07-30 at 22 21 04](https://user-images.githubusercontent.com/22512161/182009933-048941a2-b7e8-499b-92c8-4f2fc1d82b71.png) and to use the auth request call, I used the following code, note that for the android native URI, it is simply the scheme string and path string in the intent filter data section connected with a ":" in between: ![Screen Shot 2022-07-30 at 22 38 09](https://user-images.githubusercontent.com/22512161/182010360-bbb113ca-2062-4b4d-b9af-623bafbfebc0.png) Hopefully this can help out others who are also stuck on this.

Omg! I just got the login working on the Android Standalone app!! 🔥💯 Over 2 months, countless hours, and 27 iterative app deploys! 😤 Thank you so much @XiangZhang0216

**Comment by komal1502** [comment]
I am still facing the same issue. Can anyone please help me ?. Following are the snippet of my code
![Login](https://user-images.githubusercontent.com/32698245/206147052-7ddb746f-b4ea-4d8d-9fbb-1b108b60fe56.png)
![AppJSON](https://user-images.githubusercontent.com/32698245/206147071-87d941b1-26a0-4217-8b8b-9da61f08ce86.png)

**Comment by danielkv** [comment]
> I am still facing the same issue. Can anyone please help me ?. Following are the snippet of my code
> ![Login](https://user-images.githubusercontent.com/32698245/206147052-7ddb746f-b4ea-4d8d-9fbb-1b108b60fe56.png)
> ![AppJSON](https://user-images.githubusercontent.com/32698245/206147071-87d941b1-26a0-4217-8b8b-9da61f08ce86.png)
> 

Hi, this is still going on hum? It's been a while since I don't play with Google authentication but it should be fixed by now. 

Next couple of weeks I'll have setup an authentication route in a new app here, if I have something new I'll post in this thread.

BTW don't share your auth tokens here, When you need to share your core just remove them. If I were you I'd revoke them and create new ones.

**Comment by komal1502** [comment]
> > Hi, just an update on the double "open with" app issue. For me this stackoverflow page really helped. https://stackoverflow.com/questions/60984286/how-does-google-sign-in-for-android-work-without-a-redirect-uri I was able to get my sign-in to bypass the double app by configuring my app.json to the following, note particularly the data section in the intent filter, the scheme is in the reverse DNS notation of the Android Client ID from Google Cloud Console: ![Screen Shot 2022-07-30 at 22 21 04](https://user-images.githubusercontent.com/22512161/182009933-048941a2-b7e8-499b-92c8-4f2fc1d82b71.png) and to use the auth request call, I used the following code, note that for the android native URI, it is simply the scheme string and path string in the intent filter data section connected with a ":" in between: ![Screen Shot 2022-07-30 at 22 38 09](https://user-images.githubusercontent.com/22512161/182010360-bbb113ca-2062-4b4d-b9af-623bafbfebc0.png) Hopefully this can help out others who are also stuck on this.
> 
> Omg! I just got the login working on the Android Standalone app!! 🔥💯 Over 2 months, countless hours, and 27 iterative app deploys! 😤 Thank you so much @XiangZhang0216

Can you share your code for social login? I am unable to proceed further. I am stuck here since ages.

**Comment by WellingtonSouzaAbreu** [comment]
Eu também estou preso nisso
, alguém pode me ajudar?
