### ISSUE TITLE
LocalAuthentication.supportedAuthenticationTypesAsync return only [1] in galaxy note10+(Android 10) which has Faceid and Fingerprint

### ISSUE THREAD

**Issue by treesen** [expo/expo#10861]
### Summary of Issue 

LocalAuthentication.supportedAuthenticationTypesAsync return only [1] in galaxy note10+(Android 10) which supports Faceid and Fingerprint

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 galaxy note10+(Android 10)
 "expo-local-authentication": "^9.2.0"

### Reproducible Demo
![image](https://user-images.githubusercontent.com/22449939/97601403-b7dce880-1a3c-11eb-8e28-608885901fd9.png)
const supportedBioTypes = await LocalAuthentication.supportedAuthenticationTypesAsync();

 
### Steps to Reproduce
call LocalAuthentication.supportedAuthenticationTypesAsync() on galaxy note10+(Android 10)

### Expected Behavior vs Actual Behavior

expected return [1,2], but return [1]

**Comment by treesen** [comment]
please help!!! Thank you

**Comment by treesen** [comment]
> Hi @treesen, could you verify the following for me?
> 
> * If you have set `android.permissions` in your `app.json`, does it include `USE_BIOMETRIC`?
> * Is your phone enrolled into facial recognition? _([see this](https://www.samsung.com/au/support/mobile-devices/setup-biometrics-and-security/))_?
> * Is your phone upgraded to the latest version? _([including this change](https://www.biometricupdate.com/202003/samsung-galaxy-note-10-10-upgrades-biometric-facial-recognition-navigation-gestures))_

hi @croaky 
1. I am using a expo project, but I use expo-local-authentication and add USE_BIOMETRIC in AndroidManifest.xml.
2.yes
3.yes
![image](https://user-images.githubusercontent.com/22449939/97605955-d5608100-1a41-11eb-8ee2-7d0c6b0a21c8.png)

**Comment by byCedric** [comment]
Awesome, thanks! I don't have access to a Galaxy Note 10+ device at the moment. If you are able to, [could you fetch a list of all available system features on this device](https://android.stackexchange.com/a/82181)? It looks like the [`hasSystemFeature(PackageManager.FEATURE_FACE)`](https://developer.android.com/reference/android/content/pm/PackageManager#FEATURE_FACE) is returning `false` somehow on this device. If we have a list of available features, we can double-check if it's available under a different name and fix this issue!

**Comment by treesen** [comment]
> Awesome, thanks! I don't have access to a Galaxy Note 10+ device at the moment. If you are able to, [could you fetch a list of all available system features on this device](https://android.stackexchange.com/a/82181)? It looks like the [`hasSystemFeature(PackageManager.FEATURE_FACE)`](https://developer.android.com/reference/android/content/pm/PackageManager#FEATURE_FACE) is returning `false` somehow on this device. If we have a list of available features, we can double-check if it's available under a different name and fix this issue!

wow, I found the feature name is "com.samsung.android.bio.face", list as below:

feature:reqGlEsVersion=0x30002
feature:android.hardware.audio.low_latency
feature:android.hardware.audio.output
feature:android.hardware.audio.pro
feature:android.hardware.bluetooth
feature:android.hardware.bluetooth_le
feature:android.hardware.camera
feature:android.hardware.camera.any
feature:android.hardware.camera.ar
feature:android.hardware.camera.autofocus
feature:android.hardware.camera.capability.manual_post_processing
feature:android.hardware.camera.capability.manual_sensor
feature:android.hardware.camera.capability.raw
feature:android.hardware.camera.flash
feature:android.hardware.camera.front
feature:android.hardware.camera.level.full
feature:android.hardware.faketouch
feature:android.hardware.fingerprint
feature:android.hardware.location
feature:android.hardware.location.gps
feature:android.hardware.location.network
feature:android.hardware.microphone
feature:android.hardware.nfc
feature:android.hardware.nfc.any
feature:android.hardware.nfc.ese
feature:android.hardware.nfc.hce
feature:android.hardware.nfc.hcef
feature:android.hardware.nfc.uicc
feature:android.hardware.opengles.aep
feature:android.hardware.ram.normal
feature:android.hardware.screen.landscape
feature:android.hardware.screen.portrait
feature:android.hardware.sensor.accelerometer
feature:android.hardware.sensor.barometer
feature:android.hardware.sensor.compass
feature:android.hardware.sensor.gyroscope
feature:android.hardware.sensor.hifi_sensors
feature:android.hardware.sensor.light
feature:android.hardware.sensor.proximity
feature:android.hardware.sensor.stepcounter
feature:android.hardware.sensor.stepdetector
feature:android.hardware.telephony
feature:android.hardware.telephony.gsm
feature:android.hardware.telephony.ims
feature:android.hardware.touchscreen
feature:android.hardware.touchscreen.multitouch
feature:android.hardware.touchscreen.multitouch.distinct
feature:android.hardware.touchscreen.multitouch.jazzhand
feature:android.hardware.usb.accessory
feature:android.hardware.usb.host
feature:android.hardware.vulkan.compute
feature:android.hardware.vulkan.level=1
feature:android.hardware.vulkan.version=4198400
feature:android.hardware.wifi
feature:android.hardware.wifi.aware
feature:android.hardware.wifi.direct
feature:android.hardware.wifi.rtt
feature:android.software.activities_on_secondary_displays
feature:android.software.app_widgets
feature:android.software.autofill
feature:android.software.backup
feature:android.software.cant_save_state
feature:android.software.companion_device_setup
feature:android.software.connectionservice
feature:android.software.cts
feature:android.software.device_admin
feature:android.software.file_based_encryption
feature:android.software.freeform_window_management
feature:android.software.home_screen
feature:android.software.input_methods
feature:android.software.ipsec_tunnels
feature:android.software.live_wallpaper
feature:android.software.managed_users
feature:android.software.midi
feature:android.software.picture_in_picture
feature:android.software.print
feature:android.software.secure_lock_screen
feature:android.software.securely_removes_users
feature:android.software.sip
feature:android.software.sip.voip
feature:android.software.verified_boot
feature:android.software.voice_recognizers
feature:android.software.webview
feature:android.sofware.nfc.beam
feature:com.google.android.feature.DPS
feature:com.google.android.feature.TURBO_PRELOAD
feature:com.nxp.mifare
feature:com.samsung.android.api.version.2402
feature:com.samsung.android.api.version.2403
feature:com.samsung.android.api.version.2501
feature:com.samsung.android.api.version.2502
feature:com.samsung.android.api.version.2601
feature:com.samsung.android.api.version.2701
feature:com.samsung.android.api.version.2801
feature:com.samsung.android.api.version.2802
feature:com.samsung.android.api.version.2803
feature:com.samsung.android.api.version.2901
feature:com.samsung.android.api.version.2902
feature:com.samsung.android.api.version.2903
feature:com.samsung.android.authfw
**feature:com.samsung.android.bio.face**
feature:com.samsung.android.camerasdkservice
feature:com.samsung.android.cameraxservice
feature:com.samsung.android.knox.knoxsdk
feature:com.samsung.android.sdk.camera.processor
feature:com.samsung.android.sdk.camera.processor.effect
feature:com.samsung.feature.SAMSUNG_EXPERIENCE
feature:com.samsung.feature.aodservice_v07
feature:com.samsung.feature.aremoji.v2
feature:com.samsung.feature.arruler
feature:com.samsung.feature.audio_listenback
feature:com.samsung.feature.device_category_phone
feature:com.samsung.feature.galaxyfinder_v7
feature:com.samsung.feature.ipsgeofence=1
feature:com.samsung.feature.samsung_experience_mobile
feature:com.samsung.feature.samsungpositioning
feature:com.samsung.feature.samsungpositioning.snlp
feature:com.sec.android.mdm
feature:com.sec.android.secimaging
feature:com.sec.android.smartface.smart_stay
feature:com.sec.feature.cocktailpanel
feature:com.sec.feature.cover
feature:com.sec.feature.cover.clearsideviewcover
feature:com.sec.feature.cover.flip
feature:com.sec.feature.cover.ledbackcover
feature:com.sec.feature.cover.nfcledcover
feature:com.sec.feature.cover.sview
feature:com.sec.feature.edge_v03
feature:com.sec.feature.fingerprint_manager_service
feature:com.sec.feature.motionrecognition_service
feature:com.sec.feature.nfc_authentication
feature:com.sec.feature.nfc_authentication_cover
feature:com.sec.feature.nsflp=521
feature:com.sec.feature.overlaymagnifier
feature:com.sec.feature.people_edge_notification
feature:com.sec.feature.saccessorymanager
feature:com.sec.feature.sensorhub=32
feature:com.sec.feature.slocation=3
feature:com.sec.feature.spen_usp=40
feature:com.sec.feature.support_mst
feature:com.sec.feature.usb_authentication
feature:com.sec.feature.wirelesscharger_authentication

**Comment by treesen** [comment]
there is another issue when call LocalAuthentication.authenticateAsync. it shows both finger and faceid to let user choose, but not show faceid only if finger and faceid both are avaliable

**Comment by StevenWonder** [comment]
I have the same problem on the Samsung A70. This device also has the feature `feature:com.samsung.android.bio.face`

Even though detection doesn't work, `authenticateAsync` prompts the face recognition sensor instead of the fingerprint sensor 🤔

**Comment by StevenWonder** [comment]
Please don't close this. My app really needs a fix for this

**Comment by VadimDyliko** [comment]
in my case `supportedAuthenticationTypesAsync` doesnt return IRIS for sumsung s9.

**Comment by StevenWonder** [comment]
Please don't close this. My app really needs a fix for this

**Comment by CorinneKelly** [comment]
Hello, I am also experiencing this on several android devices. One is a Galaxy Tab A7 running Android 11 where `hasHardwareAsync` returns false, even though the device has faceID enabled, `localAuthIsEnrolled` returns false and `localAuthTypes` returns an empty. My app is running expo SDK 42. Let me know what more information you need to help fix this bug.

**Comment by ngima** [comment]
Any updates on it?
