### ISSUE TITLE
ERROR ITMS-90717: "Invalid App Store Icon. The App Store Icon in the asset catalog in 'Exponent.app' can't be transparent nor contain an alpha channel."

### ISSUE THREAD

**Issue by vincentopensourcetaiwan** [expo/expo#1086]
![331f8258eda4166753f0e5e7650d7aa1c56d9e31](https://user-images.githubusercontent.com/1177247/33761327-9367ecd2-dc43-11e7-8037-f90d2dc29508.png)

I build an iOS APP and upload the .ipa file with Application Loader, and receive following error message.

description length:10052448

ERROR ITMS-90717: “Invalid App Store Icon. The App Store Icon in the asset catalog in ‘Exponent.app’ can’t be transparent nor contain an alpha channel.”

**Comment by terribleben** [comment]
Hi there, I recommend using an icon that isn't transparent and doesn't contain an alpha channel. You can find the full set of guidelines for iOS icons [here](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/).

**Comment by moussasarr** [comment]
Which file was the icon from ?

**Comment by mc9000** [comment]
Does this error refer to an icon in the ipa or in the iTunes app store listing page?

**Comment by terribleben** [comment]
This message refers to an icon in the ipa. When you run `exp build`, all the icons in the ipa are derived from your `app.json` configuration. The largest of the ipa icons is automatically used on the iTunes app store listing page. Check out our [guide](https://docs.expo.io/versions/latest/guides/app-icons.html) with some details about how to format your icons.

**Comment by moussasarr** [comment]
I have had that issue before. Use this website to remove the transparency
and alpha channel from your icon : http://alphachannelremover.
blogspot.com/?m=1
Good Luck !

**Comment by birja12** [comment]
If you are using Xcode 10 or earlier in MAC

Same icon use in appstoreconnect and another one xcode General->App icon and launch image->app icon source->
![screenshot 2019-02-15 at 12 58 01 pm](https://user-images.githubusercontent.com/40656734/52847845-51624a80-3133-11e9-88f8-d9a329271417.png)
