### ISSUE TITLE
Android Barcode Scanner Orientation

### ISSUE THREAD

**Issue by dondragon2** [expo/expo#10863]
I am using `expo-barcode-scanner` in a bare react native application. It works fine on iOS but on Android I noticed that it only scans if I turn the phone horizontally. How can I make it scan from any orientation or even just from portrait?

I am using:
`expo-barcode-scanner: ^9.0.0`

**Comment by byCedric** [comment]
Hi @dondragon2, thanks for the issue but without a repro I'm not sure what's going on. Could you provide one? If I use the example from [the docs](https://docs.expo.io/versions/v39.0.0/sdk/bar-code-scanner/), I can scan barcodes in both portrait and landscape.

**Comment by dondragon2** [comment]
@byCedric below is the code that I am using.

```
import { BarCodeScanner } from 'expo-barcode-scanner';
import React from 'react';
import { View } from 'react-native';
import BarcodeMask from 'react-native-barcode-mask';

interface IProps {
  onScanned?: (payload: any) => void;
  allowedTypes?: string[] | number[];
}

const Scanner: React.FC<IProps> = ({ onScanned, allowedTypes }) => {
  return (
    <View style={{flex: 1}}>
      <BarCodeScanner
        onBarCodeScanned={onScanned}
        style={StyleSheet.absoluteFill}
        barCodeTypes={allowedTypes as string[]}
      >
        <BarcodeMask/>
      </BarCodeScanner>
    </View>
  );
};```

**Comment by rubyte-s** [comment]
Im seeing the same issue on android, barcode will scan when holding the phone in portrait and the barcode is vertical. 

![image](https://user-images.githubusercontent.com/64439657/101329512-601a7400-3869-11eb-9947-efe0480a6fb3.png)

However will not scan when phone is portrait  and barcode horizontal

![image](https://user-images.githubusercontent.com/64439657/101329379-3c572e00-3869-11eb-9db9-0da1ff270238.png)

Repo: https://github.com/rubyte-s/RNBarcodeExample

**Comment by lis-hs** [comment]
I also have this problem. In addition to scanning the QR code, the bar code of the mobile phone needs to be scanned vertically

**Comment by mxcihak** [comment]
Same problem

**Comment by keithdmoore** [comment]
Same here

**Comment by mayying** [comment]
+1

**Comment by bohdan-vasylenko** [comment]
had to switch to expo-camera because of this issue. 
expo-camera also has built-in barcode scanner
