### ISSUE TITLE
Modal doesn't dismiss on swipe down

### ISSUE THREAD

**Issue by Benjamaker** [expo/expo#10866]
### Summary of Issue

We use a modal to create tray menus in our app e.g for a list of updates and page contents. Until latest updates, user could swipe down to dismiss the modal tray (I believe this has been standard since iOS 13), but this is no longer working.

### Environment 

iOS

### Reproducible Demo

[Snack](https://snack.expo.io/n6quJtLva)

### Steps to Reproduce

- Press the touchable (Press for Modal!)

### Expected Behavior vs Actual Behavior

-Modal pops up with a list of updates 
-User should be able to dismiss the modal by swiping down
-However, modal persists and can't be exited

**Comment by brentvatne** [comment]
see this related upstream react-native issue: https://github.com/facebook/react-native/issues/29319
