### ISSUE TITLE
expo build:iso does not work other I-Phone

### ISSUE THREAD

**Issue by alakdam07** [expo/expo#10879]
I build my app in `expo build:iso` and choose simulator.  My  app build successfully but It does not work other I-Phone than mine. i don't know what is the problem?

**Comment by byCedric** [comment]
Hi @alakdam07! [This doc](https://docs.expo.io/distribution/building-standalone-apps/#if-you-choose-to-build-for-ios) might help you further:
> You can build standalone apps for iOS with two different types, an archive (`expo build:ios -t archive`) or simulator (`expo build:ios -t simulator`) build. With the simulator build, you can test your standalone app on a simulator. If you want to publish your app to the store or distribute it with tools like TestFlight, you have to use the archive.
