### ISSUE TITLE
Feature request: Build status notifications

### ISSUE THREAD

**Issue by kadoshms** [expo/expo#1087]
Hey guys, thanks for your great work!

I just wondered - what if there was a notification system (email/push to expo app) that notifies when the standalone build is done?

Currently we need to actively run `exp build:status` which is great but it was really helpful to get notified when things are ready, without checking it repeatedly :)

Same for build errors, it could be really helpful to know if something went wrong, without checking myself.

I'd love to hear your opinion :)

**Comment by brentvatne** [comment]
hi there! would a webhook work for you? I agree this would be useful!

also -- can you repost this to https://expo.canny.io/feature-requests please? this helps us to organize and prioritize feature requests :)
