### ISSUE TITLE
Expo Sdk 39 Android Standalone App Crashes on MapView.Marker

### ISSUE THREAD

**Issue by imshreyansh** [expo/expo#10884]
Expo- SDK 39
Android- 11

Whenever i am creating an standalone app on Android
The app crashes due to Mapview.Marker Custom Image,
Although it doesn't happens on Development

The logcat displays
Error while updating property 'image' of a view managed by: AIRMapMarker

**Comment by imshreyansh** [comment]
#1431

**Comment by byCedric** [comment]
Hi @imshreyansh, thanks for the issue. But we don't have enough info from our template to help you further. The issue you linked is over 2.5 years old and already fixed. [I can only link to this issue](https://github.com/react-native-maps/react-native-maps/issues/3158), maybe that workaround works for you too.

If that doesn't work for you, and think this is a bug in either Expo or React Native Maps, please open a new issue with the full bug report information we ask for within the template. Only then we are able to investigate this further.

Hope this helps!

**Comment by SleeplessByte** [comment]
@byCedric just wanted to confirm the report. Works in Expo 38 (lower RN version), stops working in Expo 39.

- Doesn't matter if it's local or remote image
- Only crashes in production, not in development

It's a native bridge crash:

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'image' of a view managed by: AIRMapMarker
```

Naturally a proper issue should be created, but I did want to write this down for people stumbling upon this.

https://github.com/react-native-maps/react-native-maps/issues/3664 has a Minimal Reproducible Example. It does **not** use `expo`, so my intuition says it's actually an issue in `React Native`, or the metro builder (for example a Proguard related issue).
