### ISSUE TITLE
expo-font: [TypeError: undefined is not an object (evaluating '_ExpoFontLoader.default.loadAsync')]

### ISSUE THREAD

**Issue by OKNoah** [expo/expo#10882]
### Summary of Issue 

When running on iOS I get `[TypeError: undefined is not an object (evaluating '_ExpoFontLoader.default.loadAsync')]`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /Users/noahgray/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      react: 16 => 16.14.0 
      react-dom: 16 => 16.14.0 
      react-native: 0.61.5 => 0.61.5 
      react-native-web: 0.0.0-7cbe1609b => 0.0.0-7cbe1609b 
    npmGlobalPackages:
      expo-cli: 3.28.2
```

### Reproducible Demo

```
import React from 'react'
import * as Font from 'expo-font'
import 'react-native-gesture-handler'

const App = (...props) => {
  const [loaded, error] = Font.useFonts({
    jacky: require('./public/fonts/jackeyfont.ttf'),
  })

  if (error) {
    console.log(error)
  }

  if (!loaded) {
    return null
  }

  return (
    {/* ... */}
  )
}

export default App
``` 

### Steps to Reproduce

```
expo install expo-font
npx pod-install
react-native run-ios --device iPad
```

### Expected Behavior vs Actual Behavior

Blank screen, console log says as above.

**Comment by byCedric** [comment]
Hi @OKNoah, it looks like the native part of `expo-font` isn't properly loading for you. To fully investigate this issue we'd need a repository where this happens. It's most likely a configuration issue, and we can't find that info in the repro you provided. Could you provide one? If not, I would recommend [double-checking the unimodules guide](https://docs.expo.io/bare/installing-unimodules/) and see if everything is linked properly.
