### ISSUE TITLE
Pre-populated existing sqlite database

### ISSUE THREAD

**Issue by cristian-milea** [expo/expo#10881]
### Summary of Issue 
Hundreds of forum questions, lots of hackish solutions dating 3-4 years. Nothing official about how to use an existing sqlite database. Nothing works in SDK39 regarding existing sqlite db.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.28.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
    SDKs:
      Android SDK:
        Android NDK: 21.1.6352462
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed

targeting ios and android

### Reproducible Demo
I tried:
```
           await FileSystem.downloadAsync(
             Asset.fromModule(require('../assets/database.db')).uri,
            `${FileSystem.documentDirectory}SQLite/database.db`
           );
```
```
const sqliteDB = await AssetUtils.resolveAsync(require('../assets/database.db'))

          await FileSystem.copyAsync({
            from: sqliteDB.localUri,
            to: `${FileSystem.documentDirectory}SQLite/database.db`
          })
```
Tried running this other hack some users said it's the Holy Graal before copying and connecting the actual database file.. 
```
  const makeSQLiteDirAsync = React.useCallback(async () => {
    const dbTest = SQLite.openDatabase('dummy.db');
    try {
      await dbTest.transaction(tx => tx.executeSql(''));
  
    } catch(e) {
      console.log('error while executing SQL in dummy DB');
    }
  }, []);
```
Tried with expo-sqlite and typeorm/browser
```
const gotConnection = await createConnection({
          database: 'database.db',
          driver: require('expo-sqlite'),
          entities: [
              User,
              SomeTable,
              SomeOtherTable
          ],
          logging: true,
          synchronize: false, // Indicates if database schema should be auto created on every application launch. Be careful with this option and don't use this in production - otherwise you can lose production data. This option is useful during debug and development
          type: "expo",
        });

gotConnection.isConnected // this is true, but any query fails because it seems like some other empty new database
```
Tried with timeouts
Tried even the mp4 hack..
Read all expo forum posts about this
Lost a lot of time, I'm afraid to count.
 
### Steps to Reproduce
add file.db to assets, try to copy to phone documentDirectory using expo docs.. then open / create a connection to the database using methods above and endless hacks.

### Expected Behavior vs Actual Behavior
Ability to use prepopulated sqlite database.
Now the file gets copied, but when I try to query it, no tables exist.

running `SELECT 
            *
        FROM 
            sqlite_master` gives 

```
Array [
  Object {
    "name": "android_metadata",
    "rootpage": 3,
    "sql": "CREATE TABLE android_metadata (locale TEXT)",
    "tbl_name": "android_metadata",
    "type": "table",
  },
]
```
and I have 4 tables in that file.

Opening the assets/file.db copied file.db with any sqlite browser / studio / editor shows all the tables with all the data.

I honestly don't know what more to do and do not understand why there is no official 
`SQLite.initializeDbFromAssets(require(../assets/file.db))` something.

**Comment by kaderisoft** [comment]
`async function loadAsyncResources() {

const dbinfo = await FileSystem.getInfoAsync(`${FileSystem.documentDirectory}SQLite/tutsdic1118.db`);

console.log(dbinfo);

if (!dbinfo.exists && !dbinfo.isDirectory) {

await FileSystem.makeDirectoryAsync(`${FileSystem.documentDirectory}SQLite`, {

intermediates: true

}).then(async () => await FileSystem.downloadAsync(

Asset.fromModule(require("./src/assets/data/tutsdic1118.db")).uri,

`${FileSystem.documentDirectory}SQLite/tutsdic1118.db`)

)

} else {

}


`
I used the previous code in order to use an existing database.  But the problems that occur are:

- Transferring files lags when using the app, but it works faster than using the expo client.

The size of the database is 10 MB, and it takes more than 2 minutes for the copying process to complete.

- The file is only copied when the network is available, but the file is in the assets folder and the network is not needed


I searched several sites and read several instructions, but did not reach any results

**Comment by cruzach** [comment]
@kaderisoft is correct, the best way to do this is:

```
async function openDatabase(pathToDatabaseFile: string): SQLite.WebSQLDatabase {
  if (!(await FileSystem.getInfoAsync(FileSystem.documentDirectory + 'SQLite')).exists) {
    await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + 'SQLite');
  }
  await FileSystem.downloadAsync(Asset.fromModule(require(pathToDatabaseFile)).uri, FileSystem.documentDirectory + 'SQLite/myDatabaseName.db')
  return SQLite.openDatabase('myDatabaseName.db');
}
```

I'll make a PR to our docs to include a guide on doing this, thanks @cristian-milea 


@kaderisoft - I was able to open the existing database without a network connection, it seems like maybe you're trying to access a remote .db asset rather than a local one?

**Comment by cruzach** [comment]
@cristian-milea let me know if this guide helps- https://github.com/expo/expo/pull/10903/files#diff-07ef15043ef5d408fb79f45a3795f2901a2b706cac9034afc9fe39a98f9aa3c0R96-R129 - and I'll merge

**Comment by cristian-milea** [comment]
Thank you very much! Will try these days if I can get a decent internet connection!

**Comment by lemmingworks** [comment]
`async function openDatabase(pathToDatabaseFile: string): SQLite.WebSQLDatabase {
  if (!(await FileSystem.getInfoAsync(FileSystem.documentDirectory + 'SQLite')).exists) {
    await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + 'SQLite');
  }

  // Always copies the DB stored in the assets folder to the expo FileSystem.documentDirectory.
  // The first time the app is opened this is great, but any changes stored to the FileSystem DB in the
  // first session would be overwritten by the DB being recopied in the second session.
  await FileSystem.downloadAsync(Asset.fromModule(require(pathToDatabaseFile)).uri, FileSystem.documentDirectory + 'SQLite/myDatabaseName.db')
  return SQLite.openDatabase('myDatabaseName.db');
}`

@cruzach I'm was wonder if in your example this would always copy an existing database to the expo file system, and would therefore overwrite any changes from one session using the app to the next.

**Comment by iamursky** [comment]
Here's what I came up with.

```typescript
import { Slot } from "expo-router";
import { SQLiteProvider, SQLiteProviderAssetSource } from "expo-sqlite";
import { Suspense } from "react";
import { ActivityIndicator } from "react-native";

const dbAssetSource: SQLiteProviderAssetSource = {
  assetId: require("@/assets/data.db"),
};

export default function RootLayout() {
  return (
    <Suspense fallback={<ActivityIndicator size="large" />}>
      <SQLiteProvider assetSource={dbAssetSource} databaseName="data.db" useSuspense>
        <Slot />
      </SQLiteProvider>
    </Suspense>
  );
}
```
