### ISSUE TITLE
Expo AV Video large file crash

### ISSUE THREAD

**Issue by galizhan** [expo/expo#10888]
On loading large files with Video it crashes on both android and ios. Even spliting video with hls doesn't fix this problem.

**Comment by byCedric** [comment]
Hi @galizhan, I'm sorry to hear you are having issues with `expo-av`. In order to help you investigate it, we need more info. If you think you encountered a bug with our tools, please open a new bug report with all the information we ask for within the template. Only then we are able to help you.
