### ISSUE TITLE
Any workaround for Firebase Firestore persistence in Expo?

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#10886]
Hi!!

I am facing a problem in expo and react native using Firesbase Firestore. I am trying to persist it but I get the error

> Error enabling offline storage. Falling back to storage disabled: FirebaseError: [code=unimplemented]: This platform is either missing IndexedDB or is known to have an incomplete implementation. Offline persistence has been disabled.

Is there any way to persist it? Or not possible?

```
 (async () => {
      try {
        // Try to enable the firebase auth persistence
        await firebase.enableAuthPersistence(); <------------------ Works good!
      } catch (err) {
        console.log(err);
      }

      // Try to enable the firestore persistence
      try {
        await firebase.enableFirestorePersistence(); <------------- Not working
      } catch (err) {
        console.log(err);
      }
    })().then(() => {
      // Listen the user's auth state
      unsubscribe = firebase.auth.onAuthStateChanged((authUser) => {
```

Note: This code is implemented in a Splash Screen. I only show the login form after running it.

Also, here is the code for my firebase class (context provider)

```
export default class Firebase {
  constructor() {
    if (!firebase.apps.length) {
      // Initialize App
      firebase.initializeApp(Constants.manifest.web.config.firebase);

      // Initialize firebase services
      this.auth = firebase.auth();
      this.db = firebase.firestore();
      this.storage = firebase.storage();
      this.functions = firebase.functions();
    }
  }

  enableAuthPersistence = () =>
    this.auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);

  enableFirestorePersistence = () => this.db.enablePersistence();

   ...

}
```

Tested in Samsung galaxy s8+ and iPhone 11. 

    "react-native": "^0.63.3",
    "expo": "39.0.0",
    "firebase": "7.9.0",
    "firebase-tools": "^8.4.3",

**Comment by byCedric** [comment]
Hi @VictorioMolina, it's a "known issue" that the standard Firebase JS SDK isn't fully working in a React Native or Expo environment. It needs more context that's only possible through native code, that's why we have multiple Expo Firebare packages to help in that. I would suggest taking a look at the ["using firebase" docs](https://docs.expo.io/guides/using-firebase/) and try using the `expo-firebase*` packages instead. If that doesn't work for you, please let us know! You can create a new issue for the stuff you encounter.

Hope this helps!

**Comment by frunkad** [comment]
There's a package exactly for this! https://www.npmjs.com/package/expo-firestore-offline-persistence

**Comment by suzigit** [comment]
I was using Firebase/firestore and https://www.npmjs.com/package/expo-firestore-offline-persistence to save and read saved objects. I upgraded to Expo SDK42 and now I have this exception. 
FirebaseError: You are using the memory-only build of Firestore. Persistence support is only available via the @firebase/firestore bundle or the firebase-firestore.js build.

I noticed that expo-firestore-offline-persistence is not maintained anymore. Is it possible to deal with that without going to native code?

**Comment by Eosis** [comment]
I'm also facing this issue when trying to use Firestore's offline persistence with expo-firestore-offline-persistence.

@suzigit , Did you try the workaround described [here](https://github.com/expo/expo/issues/13670#issue-946968367) ?

This has stopped the error you mentioned occuring on my android device.

In addition to that, I needed to build all using a Linux/amd64 platform in my docker devcontainer as the `expo-firestore-offline-persistence` library didn't install correctly on apple silicon ( I think this is related to some dependencies not providing linux/arm64 pre-compiled binaries. )

In the docker-compose.yaml file for the devcontainer...
```diff
version: "3.7"

services:
  devcontainer:
+   platform: linux/amd64
    build:
      ...
```

Then rebuild the image.

**Comment by suzigit** [comment]
Hi @Eosis. It worked out when I upgraded the versions of SDK42.
    "expo": "^42.0.0",
    "expo-firestore-offline-persistence": "^0.1.0",
    "firebase": "8.8.1",

**Comment by Kubaguette** [comment]
> I was using Firebase/firestore and "expo-firestore-offline-persistence" to save and read saved objects. I upgraded to Expo SDK42 and now I have this exception.
> FirebaseError: You are using the memory-only build of Firestore. Persistence support is only available via the @firebase/firestore bundle or the firebase-firestore.js build.
> 
> I noticed that expo-firestore-offline-persistence is not maintained anymore. Is it possible to deal with that without going to native code?

I still have the same error even after installing the "expo-firestore-offline-persistence" module and cant work around anything. Its insanely frustrating and I still have the same error.

**Comment by VictorioMolina** [comment]
After some days researching and without finding any solution, I decided to implement my own LRU in-memory cache.

Using a memorization pattern is not the best idea, I know, it has some limitations… but, there is a pro, as you may know, it is not possible to avoid the doc read payment for offline fetches with the native Firestore solution… 

There are some techniques that we can combine to get a good result:

1- Denormalizations
2- Contexts/Redux (can work as an in-memory cache)
3- Lodash Memoizations
4- Memoization pattern (using a LRU to avoid RAM problems)
