### ISSUE TITLE
MediaLibrary.createAssetAsync on Android Expo app

### ISSUE THREAD

**Issue by LivioMurianni** [expo/expo#10887]
## 🐛 Bug Report

Hi, this is my first post.
I hope this is the right place and that someone could help me.

I’m trying to use the MediaLibrary.createAssetAsync(uri); function to create an assets.

I’m use the App Expo Client 2.17.4.

On iOS device everything is working as expected.
Saddly on my Android Device (Samsung Galaxy s9) no, it seems that the MediaLibrary.createAssetAsync(uri) method either return an asset or throw an exception.

Thanks for the help

Expo CLI 3.27.7 environment info:
System:
OS: macOS 10.15.5
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 14.11.0 - /usr/local/bin/node
npm: 6.14.8 - /usr/local/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6514223
Xcode: 11.5/11E608c - /usr/bin/xcodebuild
npmPackages:
expo: ~37.0.3 => 37.0.7
react: ~16.9.0 => 16.9.0
react-dom: ~16.9.0 => 16.9.0
react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
react-native-web: ~0.11.7 => 0.11.7
npmGlobalPackages:
expo-cli: 3.27.7
Expo Workflow: managed
 

### Reproducible Demo

import React from ‘react’;
import { Text, View, TouchableOpacity, Alert,SafeAreaView,Dimensions, Platform,StyleSheet } from ‘react-native’;

import { Camera } from ‘expo-camera’;
import * as Permissions from ‘expo-permissions’;
import * as ImagePicker from ‘expo-image-picker’;
import * as MediaLibrary from ‘expo-media-library’;

import { FontAwesome, Ionicons,MaterialCommunityIcons} from ‘@expo/vector-icons’;

import styles from ‘…/…/Stili/styles’;
import Graphic from ‘…/…/Helper/Graphic’;
import Costanti from ‘…/…/Helper/Costanti’;
import NomiView from ‘…/NomiView’;

import SharedData from ‘…/…/Data/SharedData’;

const windowWidth = Dimensions.get(‘window’).width;
const windowHeight = Dimensions.get(‘window’).height;

import * as ScreenOrientation from ‘expo-screen-orientation’;

export default class AttivitaDettaglioFotoIns2View extends React.Component{

constructor(props){
    super(props);
    this.state = { 
        hasPermission:false,
        type:Camera.Constants.Type.back,
        refresh:false,
        bestRatio:'4:3',
        zoom:0,
        isLandScape:false,
    };
};

async componentDidMount(){
    this.getPermissionAsync();
    
    ScreenOrientation.unlockAsync();

    /* */
    Dimensions.addEventListener('change',()=>{
        ScreenOrientation.getOrientationAsync().then((data)=>{
            let isLandScape=false;
            if (data==ScreenOrientation.Orientation.LANDSCAPE_LEFT || 
                data==ScreenOrientation.Orientation.LANDSCAPE_RIGHT ){
                isLandScape=true;
              }
            
              this.setState({isLandScape:isLandScape});
      
          }).catch((error)=>{
            alert('non è stato possibile determinare la posizione dello schermo');
          });
    });
    
}

componentWillUnmount(){
    ScreenOrientation.lockAsync(Graphic.myPortrait());
}

prepareRatio = async () =>{
    //
    if (Platform.OS === 'android' && this.camera) {
        const ratios = await this.camera.getSupportedRatiosAsync();
        var bestRatio = '';
        
        
        var bestRatioError = 100000;
        var wantedRatio=windowHeight/windowWidth;
        
        for (i in ratios) {
            const r = ratios[i].split(":");
            if (Math.abs(wantedRatio - r[0]/r[1]) < bestRatioError) {
                bestRatioError = Math.abs(wantedRatio - r[0]/r[1]);
                bestRatio = ratios[i];
            }
        }
        
        this.setState({bestRatio:bestRatio});   
        this.setState({refresh:!this.state.refresh});
    }
}

/*funzioni grafiche*/
render(){

    if(this.state.hasPermission===false){
        return(
            <View>
                 <Text>No access to camera</Text>
            </View>
        );
    }

    return(
        <SafeAreaView style={{ flex: 1 }}>
            
            <Camera style={this.state.isLandScape?styleView.cameraL:styleView.carmeraP} 
                    type={this.state.type}
                    ref={ref => {
                        this.camera = ref;
                      }}
                      onCameraReady={
                        this.prepareRatio
                      }
                      ratio={this.state.bestRatio}
                      zoom={this.state.zoom}
                    >
                    {this._currentAspectRatio()}    
                
                <View style={{flex:1}}></View>
                {this._slider()}    
                <View style={this.state.isLandScape?styleView.pulsantieraInnerL:styleView.pulsantieraInnerP}>
                    <TouchableOpacity
                        style={this.state.isLandScape?styleView.pulsanteCameraL:styleView.pulsanteCameraP}
                        onPress={this.takePictureFromCameraRoll}
                        >
                        <Ionicons
                            name="ios-photos"
                            style={{ color: "#fff", fontSize: 30}}
                        />
                    </TouchableOpacity>
                    <TouchableOpacity
                        style={this.state.isLandScape?styleView.pulsanteCameraL:styleView.pulsanteCameraP}
                        onPress={this.takePicture}>
                        <FontAwesome
                            name="camera"
                            style={{ color: "#fff", fontSize: 30}}
                        />
                    </TouchableOpacity>
                    <TouchableOpacity
                        style={this.state.isLandScape?styleView.pulsanteCameraL:styleView.pulsanteCameraP}
                        onPress={()=>{
                            this.ritornaRiepilogoFoto();
                        }}>
                        <MaterialCommunityIcons
                            name="exit-to-app"
                            style={{ color: "#fff", fontSize: 30}}
                        />
                    </TouchableOpacity>
                </View>
                
            </Camera>
        </SafeAreaView>
    );
}; 

_slider=()=>{
    
    return(
        <View style={this.state.isLandScape?styleView.pulsantieraInnerL:styleView.pulsantieraInnerP}>
                    <TouchableOpacity
                        style={this.state.isLandScape?styleView.pulsanteCameraL:styleView.pulsanteCameraP}
                        onPress={()=>{
                            if(this.state.zoom>0) {
                                let newZoom=this.state.zoom;
                                newZoom-=0.1;
                                if (newZoom<0) newZoom=0;
                                this.setState({zoom:newZoom});
                            }
                        }}>
                        <FontAwesome
                            name="minus"
                            style={{ color: "#fff", fontSize: 30}}
                        />
                    </TouchableOpacity>

                    <View style={this.state.isLandScape?styleView.testoL:styleView.testoP}>
                        <Text style={styles.testoDefault} >Zoom :{this.state.zoom.toFixed(2)}</Text>
                    </View>
                    <TouchableOpacity
                        style={this.state.isLandScape?styleView.pulsanteCameraL:styleView.pulsanteCameraP}
                        onPress={()=>{
                            if(this.state.zoom<1) {
                                let newZoom=this.state.zoom;
                                newZoom+=0.1;
                                if (newZoom>1) newZoom=1;
                                this.setState({zoom:newZoom});
                            }
                        }}
                        >
                        <FontAwesome
                            name="plus"
                            style={{ color: "#fff", fontSize: 30}}
                        />
                    </TouchableOpacity>
                </View>
        
        );
       
}

_currentAspectRatio=()=>{
    if(Platform.OS=='android'){
        return(
            <View style={{position:'absolute',top:20,left:10, backgroundColor:'black'}} >
                <Text style={styles.testoDefault}>ratio: {this.camera?this.camera.props.ratio:''} {this.state.isLandScape?'L':'P'}</Text>
            </View>

        );
    }else{return (null);}
}

/*funzioni logiche */
addPicture(photo,idFoto,isFromCamera){
    var obj= new Object;
    obj.photo=photo;
    obj.id=idFoto;
    obj.isFromCamera=isFromCamera;
    return obj;
}

takePictureNoAlbum=async()=>{
    const { uri }  = await this.camera.takePictureAsync();
    MediaLibrary.createAssetAsync(uri)
    .then((asset)=>{
        var idFoto=SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.length+1;
        SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.push(this.addPicture(asset,
                                                                                     idFoto,
                                                                                     true));                                                                              
        this.ritornaRiepilogoFoto();
    })
    .catch((error)=>{
        alert('errore durante il salvataggio della foto ' + error);
    })

}

/* */
takePicture = async () => {
   
    const { uri }  = await this.camera.takePictureAsync();

    /**/
    const asset = await MediaLibrary.createAssetAsync(uri);

    /*this piece of code is not executed at all */
    var idFoto=0;
    SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.forEach((item)=>{
        if (item.id>idFoto) idFoto=item.id;
    });
    idFoto+=1;
    
    SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.push(this.addPicture(asset,
                                                                                    idFoto,
                                                                                    true));                                                                              
    this.ritornaRiepilogoFoto();
        
}

/*original method currently not used */
takePicture_backup= async () => {
    const { uri }  = await this.camera.takePictureAsync();
    
    const asset = await MediaLibrary.createAssetAsync(uri);

    MediaLibrary.createAlbumAsync(Costanti.NOME_ALBUM, asset)
      .then(() => {
          
        var idFoto=0;
        SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.forEach((item)=>{
            if (item.id>idFoto) idFoto=item.id;
        });
        idFoto+=1;
        
        SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.push(this.addPicture(asset,
                                                                                     idFoto,
                                                                                     true));                                                                              
        this.ritornaRiepilogoFoto();
      })
      .catch((error) => {
        Alert('errore durante lo scatto della foto: ' + error);
      });
  }

/* */
takePictureFromCameraRoll=async()=>{
    //
    if(!this.state.hasPermission){
      Alert('l\'App non ha il permesso di accedere al rullino!');
    }else{
        let photo =await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,})
        let  asset = await MediaLibrary.createAssetAsync(photo.uri);
        var idFoto=0;
        SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.forEach((item)=>{
            if (item.id>idFoto) idFoto=item.id;
        });
        idFoto+=1;
        SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.push(this.addPicture(asset,
                                                                                        idFoto,
                                                                                        false));                                                                              
        this.ritornaRiepilogoFoto();
      
    }
}

takePictureFromCameraRoll_backup=async()=>{
    //
    if(!this.state.hasPermission){
      Alert('l\'App non ha il permesso di accedere al rullino!');
    }else{
      let photo =await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,})
      let  asset = await MediaLibrary.createAssetAsync(photo.uri);
      MediaLibrary.createAlbumAsync(Costanti.NOME_ALBUM, asset)
      .then(() => {
        var idFoto=0;
        SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.forEach((item)=>{
            if (item.id>idFoto) idFoto=item.id;
        });
        idFoto+=1;
        SharedData.getInstance().getAttivitaCorrente().fotoNuoveLista.push(this.addPicture(asset,
                                                                                     idFoto,
                                                                                     false));                                                                              
        this.ritornaRiepilogoFoto();
      })
      .catch(error => {
        Alert('errore durante la lettura del rullino: ' + error);
      });
    }
}

/* */
getPermissionAsync = async () => {
    // Camera roll Permission 
    const stat_cr = await Permissions.getAsync(Permissions.CAMERA_ROLL);
    
    if(stat_cr.status!== 'granted'){
        const new_stat_cr = await Permissions.askAsync(Permissions.CAMERA_ROLL);
        if (new_stat_cr.status !== 'granted') {
            alert('autorizzazione al salvataggio delle foto non data!');
        }
    }
    // Camera Permission
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({ hasPermission: status === 'granted' });
  } 

  /* */
  ritornaRiepilogoFoto(){
    this.props.navigation.replace(NomiView.NomeAttivitaDettaglioFotoNew2View());
  }
};

**Comment by byCedric** [comment]
Hi @LivioMurianni, congrats on your first issue 😉   Unfortunately, I'm not sure what's going on here. I'm not sure if it's an issue with Expo, or your code. The repro you provided contains _a lot of code_, which makes it hard for us to start this up. Could you provide a smaller example, preferably through [Snack](https://snack.expo.io/) so we can start it and see what happens. It also would be helpful to add the error you mentioned, that also could give us valuable information to get this resolved. You should be able to catch the error by wrapping the method in something like this `try { ... } catch (error) { console.log(error); throw error; }`.

**Comment by janshajansha** [comment]
Hello @byCedric 
 
Let me explain it since im alos experiencing the same issue.

Here is my code 

```
pickerResult = await ImagePicker.launchImageLibraryAsync({
                mediaTypes : ImagePicker.MediaTypeOptions.Images,
                allowsEditing :false,
                base64:false,
                exif:false,
                quality:0.5
            });  

localUri = pickerResult.uri;                

  
const asset = await MediaLibrary.createAssetAsync(localUri);  
/* asset is created and after the below code is not working  */         
console.log(asset);

```

`asset` is created but the after that console code is not executing .

I have tried with try catch as well but no use.

Thanks

**Comment by janshajansha** [comment]
Hello @byCedric @LivioMurianni 

I tried to update the expo to 39 . Its Working fine now 

:)

**Comment by nihal-37-37** [comment]
Hi @janshajansha @byCedric @LivioMurianni   MediaLibrary.createAssetAsync() does work on android 11.. gives a error :-  Unable to copy file into external storage

**Comment by Marko-D** [comment]
I'm also having problems with MediaLibrary.createAssetAsync() not work on android 11. I cannot find any solution to this problem. There is another thread that you can follow where this issue is discussed but with no working solution: https://github.com/expo/expo/issues/12060

This needs to be addressed immediately. The deadline is November 1-st to update to android 30 and with this issue still not resolved our application will became useless .

**Comment by VSV6** [comment]
Hi, I'm also facing this error. I also posted in stackoverflow
[https://stackoverflow.com/q/69221755/8130756](StackOverFlow)

I'm able to save .xlsx file in my phone storage but I've 2 issues:-
       * App exits automatically once it saves a .xlsx file into the phone storage.
       * .xlsx file is saving in 'DCIM' folder, but I need to save in 'Download' folder.

My code below and especially check this function(saveXLSXFile).

`handleDownload = async () => {
const data = this.handleDownloadAbleLogs();

if (!data.length)
  return ToastAndroid.showWithGravity(
    "Sorry, no logs available to download.",
    ToastAndroid.LONG,
    ToastAndroid.CENTER
  );

const ws = XLSX.utils.json_to_sheet(data);
const wb = XLSX.utils.book_new();

XLSX.utils.book_append_sheet(wb, ws, "Logs");

const wbout = XLSX.write(wb, {
  type: "base64",
  bookType: "xlsx",
});
const uri = `${FileSystem.cacheDirectory}logs.xlsx`;

try {
  await FileSystem.writeAsStringAsync(uri, wbout, {
    encoding: FileSystem.EncodingType.Base64,
  });
  console.log(uri);
  this.saveXLSXFile(uri);
  alert("Logs file has been saved in DCIM folder, do check there.");
} catch (e) {
  console.error(e);
}};


 saveXLSXFile = async (fileUri) => {
    const { status } = await MediaLibrary.requestPermissionsAsync();
    if (status === "granted") {
      const asset = await MediaLibrary.createAssetAsync(fileUri);
      await MediaLibrary.createAlbumAsync("Download", asset, false);
    } else alert("We need you permission to download this file.");   
};`

**Comment by devanada** [comment]
really no update on this issue?

**Comment by devanada** [comment]
still no update on this issue?

**Comment by HighDeck** [comment]
Same here. I'm trying to save a json file into whatever user accessible folder outside the app but the issue is still there : 
```
// const fileUri = file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540User%252FProject/logs/test.json
const perm = await MediaLibrary.requestPermissionsAsync();
if (perm.granted) {
    const info = await FileSystem.getInfoAsync(fileUri);
    /*
    Info :  Object {
        "exists": true,
        "isDirectory": false,
        "modificationTime": 1640281208,
        "size": 59503,
        "uri": "file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540User%252FProject/logs/test.json",
        }
    */
    const asset = await MediaLibrary.createAssetAsync(info.uri);
    // Error : Could not create Asset
}
```
I have something different when i try the following : 
```
// const fileUri = file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540User%252FProject/logs/test.json

const contentUri = await FileSystem.getContentUriAsync(fileUri);

const perm = await MediaLibrary.requestPermissionsAsync();
if (perm.granted) {
    const info = await FileSystem.getInfoAsync(contentUri);
    /*
    Info :  Object {
        "exists": true,
        "isDirectory": false,
        "size": 59503,
        "uri": "content://host.exp.exponent.FileSystemFileProvider/expo_files/ExperienceData/%2540llienard%252Fsmart-drive/logs/test.json",
      }
    */
    const asset = await MediaLibrary.createAssetAsync(**contentUri**);
    // Error : Unable to copy file into external storage
}
```

I read something about ScopedStorage for android application but i can't find a way to save this file into a public folder

**Comment by UVStudio** [comment]
@mln4you @devanada @HighDeck Have you guys found anything?
[](https://github.com/expo/expo/pull/14518) supposedly fixed it but it still doesn't seem to be working. I'm on Expo 42.
MediaLibrary.saveToLibraryAsync is returning the same error.

Thanks.

**Comment by devanada** [comment]
> @mln4you @devanada @HighDeck Have you guys found anything? #14518 supposedly fixed it but it still doesn't seem to be working. I'm on Expo 42. MediaLibrary.saveToLibraryAsync is returning the same error.
> 
> Thanks.

In my case, I'm not using MediaLibrary to download some document files like pdf, but instead I'm using Linking.openURL() and using browser or some pdf viewer app to view and download

**Comment by HighDeck** [comment]
For our app purpose, we actually needed to export a JSON file. We wanted to save the file but ended up using the sharing module instead. Sorry, I won't be able to help on this :/

**Comment by UVStudio** [comment]
@devanada @HighDeck - Guess it's eject time for me!

**Comment by sheosumit** [comment]
Facing the same issue on Expo 42.0.0. Please help someone

**Comment by Marko-D** [comment]
Check out aeroholic comment here: https://github.com/expo/expo/issues/12060#issuecomment-868928047. I managed to make it work using his suggestion.

**Comment by SHANbic** [comment]
Hi! I am working on a React Native app (with expo 44.0.0 managed workflow) and I wanted to add a feature that allows users to save an image to their camera roll. I tried to find some tutorials to help me achieve this but most of them were outdated.

Based on what I had read, I chose to make use of expo-media-library and expo-file-system and I faced the terrible issue `Error: Unable to copy file into external storage` on Android (ios worked on the first attempt).

I also made sure to add the permissions suggested by [expo](https://docs.expo.dev/versions/latest/sdk/media-library/#permissions)

In the end, here is the code that worked for both ios and android:
```js
if (Platform.OS === "ios") {
    await MediaLibrary.saveToLibraryAsync(filepath);
  } else {
    const file = await FileSystem.downloadAsync(
      filepath,
      FileSystem.documentDirectory + ".png"
    );
    await MediaLibrary.saveToLibraryAsync(file.uri);
  }
Alert.alert("can't believe it finally works!")
```

where _filepath_ is just a regular https url that points to an image (eg: https://somewebsite/icons/arrow.png).

On android, the downloaded image gets saved into DCIM folder.

Please let me know if that works for you and also if this can be considered as not being a bad practice.

**Comment by durgesh2007** [comment]
Facing the same issue on Expo 45.0.0.

A reproducible issue on snack expo: [](https://snack.expo.dev/@dev-app-store/filedownload)
