### ISSUE TITLE
SQLite high RAM usage, how to close database connection?

### ISSUE THREAD

**Issue by mchen37** [expo/expo#1089]
Is there a way to close the database connection to SQLite? I am seeing high RAM usage after inserting many records. Even after moving all of the SQLite calls to its own component and unmounting that component after work is completed, RAM usage does not go down. If there are too many records, the RAM usage maxes out the device and crashes. Is there something I am missing here?

**Comment by terribleben** [comment]
Hey there, thanks for the report. It would be really helpful if you could provide some simple reproduction code demonstrating this. Also, what device and OS are you testing on?

**Comment by mchen37** [comment]
Closed as likely due to my own looping code. Will probably just download and replace db file when needed. Look forward to SQLite enhancements in future SDK versions :)
