### ISSUE TITLE
NativeModules from react-native is empty

### ISSUE THREAD

**Issue by NeutrinoXY** [expo/expo#10892]
### Summary of Issue 

After creating a native module and registering it, imported NativeModules from react-native is empty.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.28.2 environment info:
    System:
      OS: Windows 10 10.0.20241
    Binaries:
      Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 28, 30
        Build Tools: 28.0.3, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^38.0.10 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ^16.13.1 => 16.14.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ^0.11.7 => 0.11.7
    Expo Workflow: bare

### Reproducible Demo

Follow the steps from the following tutorials:

https://docs.expo.io/expokit/eject/?redirected
https://docs.expo.io/expokit/expokit/
https://reactnative.dev/docs/native-modules-android
 
### Steps to Reproduce

`import { NativeModules } from 'react-native';`
`console.log(NativeModules);`

### Expected Behavior vs Actual Behavior

NativeModules should contain the ToastModule.

**Comment by brentvatne** [comment]
this doesn't work how you think it does. NativeModules isn't just an object with a bunch of keys eagerly initialized on it, see the c++ implementation of nativeModulesProxy here: https://github.com/facebook/react-native/blob/7b7c9f2309ff579af0cde892dd6f54f11875c367/ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp

as for the ToastModule, you can clearly see that it does exist on the docs: https://reactnative.dev/docs/toastandroid - the snack runs in an expo environment. perhaps you are looking it up under the wrong name.

**Comment by NeutrinoXY** [comment]
@brentvatne 

Well, even if NativeModules is supposed to be empty, the ToastExample I import should not be null:

`//ToastExample.js:
import { NativeModules } from 'react-native';
module.exports = NativeModules.ToastExample;`

`App.js
import ToastExample from './ToastExample';
ToastExample.show('Awesome', ToastExample.SHORT);`

I don't want to use ToastModule, I just want to run this example so I can create another native modules.

I suggest you re-open this issue.

**Comment by brentvatne** [comment]
what is ToastExample? there is no NativeModule called ToastExample.

i think you are confused about this functionality
