### ISSUE TITLE
[docs] VideoThumbnail.getThumbnailAsync prop type not consistent with documentation

### ISSUE THREAD

**Issue by 9710willy** [expo/expo#10893]
Hi all,

According to the documentation below, it says one of the option parameter for VideoThumbnail.getThumbnailAsync is **compress**. However, it seems that the type checking of props tells me that it is **quality**. 

![image](https://user-images.githubusercontent.com/42782480/97809408-b2e58800-1c3a-11eb-8002-75501b9dd4a2.png)

Not sure if it was a documentation issue or a typo in the type definition, but wanted to let you guys know!

Thank you for all your hard work :D

Link to doc: https://docs.expo.io/versions/latest/sdk/video-thumbnails/#arguments

**Comment by byCedric** [comment]
Hi @9710willy, thanks for the heads up! I created a PR that should fix this in the docs 😄
