### ISSUE TITLE
ios: universal clipboard

### ISSUE THREAD

**Issue by inyono** [expo/expo#109]
Firstly: thanks for Expo and CRNA, it helped us to lower our initial hurdle for new developers 👍.

Secondly: When I'm developing a CRNA, I get periodically (like multiple times per minute) the following alert in iOS:

![img_0414](https://cloud.githubusercontent.com/assets/1508477/25060700/0b88f478-21a4-11e7-9116-7cf749af014a.PNG)

I suppose this is because of [Universal Clipboard](https://support.apple.com/kb/PH25168?viewlocale=en_AP&locale=en_AP) and because Expo is listening on the clipboard (?). If so, can we deactivate that behaviour when one has opened an Expo app? Apart from it being super annoying when developing, it also might be problematic if the app itself tries to listen on the clipboard (if that's even possible with an Expo app).

**Comment by terribleben** [comment]
cc @brentvatne -- does the Expo Home experience use clipboard? We don't have any native hooks into the clipboard other than the standard React Native module.

**Comment by dikaiosune** [comment]
@inyono hi! I believe this was fixed in our latest release. Can you check to see if you're still able to reproduce it on an up-to-date client?

**Comment by inyono** [comment]
Hey @dikaiosune. I don't have the issue anymore, thanks 👍
