### ISSUE TITLE
launchImageLibraryAsync returns portrait video on iOS and Android with switched dimensions

### ISSUE THREAD

**Issue by Aryk** [expo/expo#10909]
Steps to reproduce:

1. Run ImagePicker.launchImageLibraryAsync with mediaTypes  = ImagePicker.MediaTypeOptions.All
2. Select a portrait-oriented video (like for an instagram story) on the phone.
3. Notice that the width and height need to be flipped but there is no way to know that. The height should be the larger value (since it is a portrait video).

Managed SDK 39.0

Only hacky workaround for now that I see is:

```ts
const asset = await MediaLibrary.createAssetAsync(uri);
        console.log(await MediaLibrary.getAssetInfoAsync(asset))
 await MediaLibrary.deleteAssetsAsync([asset]);
```
 
which I have verified does return the width and height correctly. Unfortunately if you do ` await MediaLibrary.deleteAssetsAsync([asset]);` on iOS it will prompt the user if they want to delete this duplicate. The user does not know it is a duplicate so I will have to leave the extra duplicate on their system.. . 🙉

**Comment by AdamJNavarro** [comment]
Hey @Aryk, I was able to reproduce this on Android (Galaxy S8) with this [Snack](https://snack.expo.io/@adamjnav/364575). However, it seems to be working as expected on iOS (iPhone 11). Can you let me what you reproduced the error on iOS with?

**Comment by Aryk** [comment]
I just shot a 2 second portrait clip and reproduced it with your snack on iPhone X (I'm on the newest osx as well).

**Comment by Aryk** [comment]
Just make sure you shoot a video that is portrait.

Here is one of the videos shot on my phone:

https://www.dropbox.com/s/tgbc04htukvi6bu/test%20for%20expo%20portrait%20issue.MOV?dl=2

**Comment by Aryk** [comment]
Since it is happening on both devices, my guess is you guys are doing zero metadata checking...because if you run [this function](https://docs.expo.io/versions/latest/sdk/media-library/#medialibrarygetassetinfoasyncasset-options) on it, it actually returns the width/height correctly...

**Comment by AdamJNavarro** [comment]
Ok, I was able to reproduce it with your video and a video I recorded via the iPhone Camera app. The initial video I tried from my camera roll was an Instagram Story I saved to camera roll which does seemingly return the proper dimensions.

**Comment by Aryk** [comment]
Great! I'm glad we got this bug verified...am I correct in assuming that it will not be released until SDK 40 (for those on managed workflow) even if it got fixed today?

**Comment by AdamJNavarro** [comment]
That's correct. For Managed projects, fixes of this nature will be rolled out is with SDK releases. (Unless the bug is a major and widespread issue that calls for a minor/patch release like we saw with SDK39).

**Comment by grantmsweeney** [comment]
I'm running into this issue with both `ImagePicker.launchImageLibraryAsync` and `ImagePicker.launchCameraAsync`. I was able to work around the `launchCameraAsync` case by using the width and height off of the `asset` when saving the photo using `MediaLibrary.createAssetAsync`, as mentioned by @Aryk. Thankfully that is part of my intended flow for the camera case, but is undesirable when picking existing media using `launchImageLibraryAsync`.

**Comment by Aryk** [comment]
> That's correct. For Managed projects, fixes of this nature will be rolled out is with SDK releases. (Unless the bug is a major and widespread issue that calls for a minor/patch release like we saw with SDK39).

@AdamJNavarro ...doesn't seem like this made it out with the SDK 40 release 😞 

Could you let me know when you guys plan to fix it or any updates?

**Comment by Aryk** [comment]
> I'm running into this issue with both `ImagePicker.launchImageLibraryAsync` and `ImagePicker.launchCameraAsync`. I was able to work around the `launchCameraAsync` case by using the width and height off of the `asset` when saving the photo using `MediaLibrary.createAssetAsync`, as mentioned by @Aryk. Thankfully that is part of my intended flow for the camera case, but is undesirable when picking existing media using `launchImageLibraryAsync`.

@grantmsweeney  Were you able to find a way to delete the duplicates after using `MediaLibrary.createAssetAsync`...I still haven't found a way.

**Comment by atul-jalan** [comment]
@Aryk I got around this by using a Video component from expo-av with width and height of 0. The component has a prop called onReadyForDisplay that returns the correct width, height, and orientation of the video.

**Comment by Aryk** [comment]
@AdamJNavarro any updates? It's been a few months...

@atul-jalan cool! could you share your code? Do you do it without having to actually render the component into your view?

**Comment by atul-jalan** [comment]
@Aryk sure. The video technically renders in my View, but given the fact that it has a height of 0 and width of 0, it's not actually visible. You can also only render the video while you're retrieving the dimensions, and then stop rendering it.

`{renderVideo && (
    <Video
      style={{ height: 0, width: 0 }}
      source={{ uri: videoUrl }}
      isMuted={true}
      shouldPlay={false}
      onReadyForDisplay={(e) => setDimensions(e.naturalSize)}
    />
  )}`

Relevant documentation: [expo documentation](https://docs.expo.io/versions/latest/sdk/video/#props)

**Comment by Aryk** [comment]
Got it.

@cruzach - Could you check on this multi-month bug? It seems like a pretty core piece of functionality that is broken - getting video dimensions off a video taken with the phone camera. Any update on when a fix might be out would be greatly appreciated.

**Comment by cruzach** [comment]
hey @Aryk! I don't have much to add here- we try to cover as many issues as quickly & efficiently as we can. Investigating and fixing bugs like this takes some time, as I'm sure you know.

One way to help would be to identify the root cause of the issue, that way whoever makes the fix (whether it be an internal or external contributor) knows exactly where to begin

**Comment by mstach60161** [comment]
It seems that this issue doesn't occur on expo SDK 42. I tried to reproduce it on different configurations. Could you try it on newer SDK and if still occurs, reopen issue with updated SDK version?

**Comment by Aryk** [comment]
@mstach60161 - This issue is still happening on SDK 43 Managed. Just run await ImagePicker.launchImageLibraryAsync and use this file.

https://user-images.githubusercontent.com/525212/142275237-45c87dd0-dfbe-409d-9f2d-5013cfc4c7bd.MOV
