### ISSUE TITLE
Issue building for iOS

### ISSUE THREAD

**Issue by gabescarbrough** [expo/expo#1090]
I rebuilt an app that was previously created using PhoneGap with Expo and I'm trying to build for iOS and I keep getting an error when I try to validate the P12 file. I used the same certificate for the Android build which I was able to do successfully and submit to the Play Store.

`
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
`
`
[exp] Unable to validate credentials. Request ID 20a18e10-dc5c-11e7-a860-29b7b52a7738, message: Internal error occurred. Please try again in a few minutes or contact support.
` 

I've tried many times, hours apart, with `exp build:ios -c`. I was able to build the app for iOS letting Expo manage the certificate, but that won't work as I need to get the app on the app store as an update to the old app, not as a new one. Could someone walk me through potential issues to work through to resolve this?

**Comment by btk** [comment]
Your credential files might be lost (?) maybe someone from expo can help you retrive it directly. You should try the slack channel, as you would have a higher chance to get in contact with an expo guy.

https://expo.slack.com/

**Comment by gabescarbrough** [comment]
Figured it out. It turned out the developer who built the previous version of the app had used a different bundle identifier for the iOS and Android versions of the app which I was unaware of. Once I used the correct bundle identifier I was able to get everything working.
