### ISSUE TITLE
eslint-config-universe is ignoring prettier config

### ISSUE THREAD

**Issue by mattiascaricato** [expo/expo#10912]
`.prettierrc` is being ignored. In VS Code I'm getting the following error:

```"Replace `'expo-status-bar'` with `\"expo-status-bar\"`"```

When it shouldn't exist because the `.prettierrc` config defined in `eslint-config-universe` ([here](https://github.com/expo/expo/blob/master/packages/eslint-config-universe/.prettierrc)) is explicitly saying `singleQuote: true`. That being said, I assume that the file is being ignored so the only work around I've found is to manually copy this file and these rules inside your project.

Documentation: https://github.com/expo/expo/tree/master/packages/eslint-config-universe

**Comment by brentvatne** [comment]
does it work as expected when running lint from command line? if so, you likely need to configure something differently in vscode. maybe it's using your system prettier instead of eslint

**Comment by brentvatne** [comment]
oh i think i see the issue. https://github.com/expo/expo/blob/master/packages/eslint-config-universe/.prettierrc is only intended to configure prettier *for the eslint-config-universe source files* not for your project. it only configures eslint to use prettier in your project, you have to provide a .prettierrc to actually provide the rules.

**Comment by mattiascaricato** [comment]
got it, it would be nice to point it out in the documentation. Btw what is the point of adding prettier as a peerDependency if there are no rules configured? just to use it with the default options?

**Comment by brentvatne** [comment]
we configure its integration with eslint here: https://github.com/expo/expo/blob/master/packages/eslint-config-universe/shared/prettier.js

but maybe @ide can speak more to the choice of why it's a peer dep

**Comment by ide** [comment]
It's a peer dep since both Prettier v1 and v2 work with it, and this has worked for the Expo repos. The point is to use your own prettierrc. Maybe we should add .prettierrc to .npmignore (or exclude it from package.json "files").
