### ISSUE TITLE
MediaLibrary : unable to retrieve assets / albums previously created

### ISSUE THREAD

**Issue by ErnestBrandi** [expo/expo#10922]
### Summary of Issue 

If I create an asset in an album with ` MediaLibrary.createAssetAsync` and `MediaLibrary.createAlbumAsync`, I cannot retrieve them afterwards (in order to delete them). 

It seems that `getAlbumAsync` and `getAssetsAsync` targets my sdcard files (when I check assets' uri) which might be why there cannot be found when they are created on phone's disk (which is surprising though when I see that interacting with sdcard is a feature request...).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.28.2 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: bare
```

**Comment by AdamJNavarro** [comment]
Hey @ErnestBrandi, can you let me know if it works as expected when the SD card is removed from the phone? Also, could you please provide the specifics of the project you are testing with such as package versions, the device you are testing with, etc.

**Comment by ErnestBrandi** [comment]
Hi, with the SD card removed, I am indeed able to get the files/assets on the phone using `getAssetsAsync`. But I still cannot get the album with `getAlbumAsync` (returns `null`) even right after it should have been created using `createAlbumAsync`.
It is a problem in my case as I cannot delete previously created Album, neither can I filter targeted assets in `getAssetsAsync` using the `album` option.

I am using a Huawei LUA-L22 phone with Android 5.1; packages infos have been exposed in my initial message.

**Comment by ErnestBrandi** [comment]
@AdamJNavarro did you have time to look into this ? thanks :)
