### ISSUE TITLE
Background Location does not work.

### ISSUE THREAD

**Issue by miroslavskela** [expo/expo#10920]
Hello everyone,
I'm trying to implement background location, android 10, expo sdk 39.0.3. I'm not using foregroundService object. So actually I want to ask if foreground service is mandatory, and if it is not, why background does not updates. I'm testing on Nexus 5, and when I put app in background and change location nothing happens, but when I open app after that, location is updated. So definitely is some problem with background. 
Allow all the time is choosen for location.
Thank you very much!

**Comment by AdamJNavarro** [comment]
Hey @miroslavskela, without seeing code we can't really begin to help you debug this issue. Please provide us with a public repo that we can clone and test on our end.

**Comment by miroslavskela** [comment]
Hi expo team, here is the git repo with minimalistic example, and I can say that background update does not work, only foregraound, i tried this example on android 10, android 8 and android 7.1, on 10 and 8, does not work, and on 7.1 it works pretty good, as I could see location updates every 2 sec, no matter if it is in background or foreground. 
https://github.com/miroslavskela/expo_test 
master branch

Thank you, Miroslav.

**Comment by cruzach** [comment]
@miroslavskela have you looked through the [existing open issues for `expo-location`](https://github.com/expo/expo/labels/Location) to make sure an issue on the same topic hasn't already been opened? For instance, this one looks quite similar to yours- https://github.com/expo/expo/issues/10712

**Comment by miroslavskela** [comment]
@cruzach Yes, i looked, and this one is more specific informations. But however neithier this one after 14 days, or that one that you linked after month does not have any update. I can find more probably but ther are not helpful.

**Comment by cruzach** [comment]
You're more than welcome to dig into the `expo-location` and `expo-task-manager` Android source code if you'd like this to be fixed right now, Expo's SDK is 100% open source and we'd love to see a PR. But opening new issues is not a good way to garner more attention to existing bugs- it actually takes up _more_ of the repo maintainers' time, so they have _less_ time to investigate & fix existing bugs

**Comment by miroslavskela** [comment]
Yes, I understand everything, i just think that im someone waits for 15 or 30 or 90 days, at least someone can write we are still investigating, or we don't have time now, or this will not be fixed. After 30 days I don't know what I'm waiting for. I would definitely help, but I don't know.

**Comment by cruzach** [comment]
Sorry that we didn't update that issue, I agree we could communicate more there

I still think it's best for you to close this issue and keep conversation focused on the other one. That makes it much easier for contributors and maintainers to discuss and find a solution. If you'd _like_ to try investigating on your own, you can eject your project with `expo eject` and then begin to fiddle with the native android code in `path/to/node_modules/expo-location` and `path/to/node_modules/expo-task-manager`. If not, no worries, just thought I'd let you know in case you wanted to dive in 😄

**Comment by miroslavskela** [comment]
Hi, if this could help you, this is the error I get on start watching location. 
![Screenshot from 2020-11-27 04-20-19](https://user-images.githubusercontent.com/36046629/100438928-7144d300-3068-11eb-9706-55f5eac25f95.png)

**Comment by byCedric** [comment]
Yes, fully agree we have to be more strict in combining the issues into one managable issue. Having this spread out over multiple issues is really hard for us to keep up. We will take note of that for the future.

For this issue, please [checkout this comment](https://github.com/expo/expo/issues/11330#issuecomment-750894337). It includes an example app for background location and some recent changes we made.

Happy holidays!
