### ISSUE TITLE
Quickly click images shown by launchImageLibraryAsync will cause error Invariant Violation: No callback found with cbID

### ISSUE THREAD

**Issue by imhazige** [expo/expo#10926]
### Summary of Issue 
when using this api
https://docs.expo.io/versions/latest/sdk/imagepicker/#imagepickerlaunchimagelibraryasyncoptions
if user click one image very quickly many times. it will show this error `Invariant Violation: No callback found with cbID`
 
### Environment - output of `expo diagnostics` & the platform(s) you're targeting
ios

### Reproducible Demo
![image](https://user-images.githubusercontent.com/4122902/98183118-710e5780-1f42-11eb-8f84-3025cbb28a97.png)

**Comment by byCedric** [comment]
Hi @imhazige, thanks for the issue report. But I'm unable to reproduce this on my end, could you provide a [small repro](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by imhazige** [comment]
I have tried on android device, it seems not happen, will try on ios device. currently can not access testflight.

**Comment by imhazige** [comment]
Sorry to delay to response.

Have test on android and ios12 device. it did not happen.

But I  found it only happen on ios14 simulator. as I have not a ios14 device, so I am not sure.

**Comment by Shing-Ho** [comment]
It's happening to me in iPhone 11 - 14.0

**Comment by matejkubinec** [comment]
I also run into the same issue (iPad, iOS 14.4), I've created a sample repo with steps for reproduction:

https://github.com/matejkubinec/expo-image-picker-ios-bug-repro

**Comment by denek01** [comment]
same issue "expo-image-picker": "~9.2.0",  "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",  "expo": "^40.0.0",

**Comment by obiwankenoobi** [comment]
Is this going to be fixed soon?
