### ISSUE TITLE
WEB - Fonts (And Icons) Not Loading When Offline

### ISSUE THREAD

**Issue by Siyavoshi** [expo/expo#10928]
I apologize if this is the wrong place to express this.

### Summary of Issue 
What I do:
1) Upload contents of web-build folder to my server
2) Access the PWA with Safari on an iPhone
3) Add the PWA to HomeScreen

Everything is fine as long as I'm connected to the internet. But when I get disconnected, fonts and icons in the pages I haven't visited in my app won't load (icons will get replaced with rectangles with x ).
I have minimal knowledge about service workers but I think it has something to do with it.
Is there a way to load all JS files at once so this doesn't happen to me anymore?

`{
"dependencies": {
    "@react-native-community/async-storage": "~1.11.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "5.9.2",
    "@react-native-community/toolbar-android": "~0.1.0-rc.2",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "crypto-js": "3.1.9-1",
    "expo": "^38.0.0",
    "expo-cli": "^3.21.13",
    "expo-constants": "~9.1.1",
    "expo-file-system": "^9.2.0",
    "expo-image-picker": "~8.3.0",
    "expo-intent-launcher": "^8.3.0",
    "expo-linear-gradient": "~8.2.1",
    "expo-permissions": "9.1.0",
    "expo-splash-screen": "~0.3.1",
    "expo-sqlite": "~8.2.1",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "jalaali-js": "^1.1.0",
    "jetifier": "^1.6.6",
    "modal-enhanced-react-native-web": "^0.2.0",
    "moment-jalaali": "^0.9.2",
    "native-base": "2.13.8",
    "react": "~16.11.0",
    "react-dom": "16.11.0",
    "react-native": "~0.62.2",
    "react-native-background-downloader": "^2.3.4",
    "react-native-config": "^1.2.1",
    "react-native-document-picker": "^3.5.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-modal": "^11.5.6",
    "react-native-popover-view": "^3.0.2",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "3.0.2",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.4.0",
    "react-navigation-drawer": "^2.5.0",
    "react-navigation-stack": "^2.8.2",
    "react-redux": "7.1.3",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "validate.js": "^0.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@babel/runtime": "^7.8.0",
    "@react-native-community/eslint-config": "^0.0.6",
    "babel-jest": "^24.9.0",
    "babel-preset-expo": "^8.2.3",
    "eslint": "^6.8.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.4",
    "react-test-renderer": "16.9.0"
  }
}`

P.S1: `{offline: true}` is present in my webpack config
P.S2: I load fonts via LoadAsync
P.S3: I'm working on an ejected project (Bare workflow)
P.S4: App works fine in offline mode on Android

**Comment by Siyavoshi** [comment]
Anybody?

**Comment by brentvatne** [comment]
@Siyavoshi - sorry we don't have time to investigate your issue right now, and in general we don't prioritize issues that do not correctly fill out our issue template because they don't include the information that we need in order to help: https://github.com/expo/expo/issues/new?labels=Issue+needs+review&template=bug_report.md
