### ISSUE TITLE
[docs] Push Notifications need two clarifications

### ISSUE THREAD

**Issue by Aryk** [expo/expo#10923]
I read through: 

https://docs.expo.io/push-notifications/overview/#faq
https://docs.expo.io/versions/latest/sdk/notifications/

Two questions that I think is reasonable to answer in the docs:

1) After calling [getExpoPushTokenAsync](https://docs.expo.io/versions/latest/sdk/notifications/#getexpopushtokenasyncoptions-expotokenoptions-expopushtoken), does the returned token change on every call to this method? I noticed that it is the same on subsequent calls...but lets say I try again in one month...could it be a different value?

Which brings me to the next question:

2) Do expo tokens ever "expire" assuming the user does not delete the app on their phone and does not change phones?

====

If #1 is true and the token doesn't change, then one can feel safe "find or creating" a new token for a user knowing that each token is tied to a unique device **even if** the user logs into the same account with multiple phones...

**Comment by cruzach** [comment]
1- the token should remain the same, unless the user uninstalls and reinstalls their device (it's probably good practice to check this in that case)

2- no, they don't ever "expire" unless the user uninstalls the app


not sure I understand this question @Aryk :
> one can feel safe "find or creating" a new token for a user knowing that each token is tied to a unique device even if the user logs into the same account with multiple phones

**Comment by Aryk** [comment]
Thanks for the clarification.

What I meant by the last point was that if the user logs into the same account on multiple phones, you will only really be  creating expo tokens for each individual phone, and not one unique one everytime you call the getExpoPushTokenAsync in the app.

That said, if they uninstall and reinstall the app, how do you know that the old Expo tokens are "invalid". You will try to send to them and then just nothing will happen?

Is there anyway to prune these tokens which essentially have no effect?

**Comment by cruzach** [comment]
On Android, you will receive [`DeviceNotRegistered` in the push receipt](https://docs.expo.io/push-notifications/sending-notifications/#push-receipt-errors) for old tokens that no longer apply, and you can handle this server-side. On iOS, it's a bit of a different story, [hence this issue](https://github.com/expo/expo/issues/9322). 

I've been reading around Apple's docs and forums and, although they do document that they will send a 410 `unregistered` response in these situations, it looks like actually _getting_ that response is rare- https://developer.apple.com/forums/thread/88332
