### ISSUE TITLE
Blank screen display when the app crash (fatal JS) instead of splash screen

### ISSUE THREAD

**Issue by hunterbmt** [expo/expo#10927]
### Summary of Issue
Previous behavior when config "checkAutomatically": "ON_ERROR_RECOVERY", if the fatal JS error happened, the app will be restart and try to load the newest OTA update. The splash screen will appear during the process as usual.
In SDK 39, if the fatal JS error happened, the app still reset and load new OTA but the splash screen no longer appear.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.27.10 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.0 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/opt/node@12/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6200805
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-navigation: ^4.4.0 => 4.4.0
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: managed
 
### Steps to Reproduce

Load the standalone app, call SplashScreen.hideAsync(), trigger fatal JS error => the app will be reset but splash screen isn't re-appear. 

### Expected Behavior vs Actual Behavior

Expected Behavior: Splash screen appears so user knows the app are resetting.
Actual Behavior: Splash screen doesn't appear.

**Comment by AdamJNavarro** [comment]
Hey @hunterbmt, is this occurring on Android, iOS or both platforms?

**Comment by hunterbmt** [comment]
@AdamJNavarro It seems to only happen on iOS. On Android the splash screen appears but the app is frozen, user has to manual kill and restart the app but that behavior may be the result of network error, we are doing some more testing on Android to verify that behavior.

**Comment by hunterbmt** [comment]
It seem like Updates.reloadAsync() wouldn't init SplashScreen again, that why the app will display blank scene instead of SplashScreen.
@AdamJNavarro , any chance you know a workaround for this ?

Regards,

**Comment by hunterbmt** [comment]
It also only happens on ios, not android

**Comment by feliperaul** [comment]
Same here
