### ISSUE TITLE
Local authentication returns {“1”: “FINGERPRINT”, “2”: “FACIAL_RECOGNITION”, “FACIAL_RECOGNITION”: 2, “FINGERPRINT”: 1, IRIS:3}

### ISSUE THREAD

**Issue by iamrekhaverma** [expo/expo#10930]
### Summary of Issue 
I used LocalAuthentication in a bared React-Native project:

"expo-local-authentication": "^9.3.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-unimodules": "^0.11.0"

undefined is not an object (evaluating ‘_ExpoLocalAuthentication.default.authenticateAsync’)

Any help pls?

**Comment by byCedric** [comment]
Hi @iamrekhaverma, thanks for the issue. It looks like the native part of the library isn't properly linked. You mentioned you are working from a bare RN project. 

- If you meant a "pure" React Native project, please [double-check if you added unimodules properly with this guide](https://docs.expo.io/bare/installing-unimodules/). 
- If you meant an ejected Expo project, this should happen automatically. If not, try to rebuild the project.

Without all the information from the bug report, we can't help you any further. And without context about the environment, platforms you use, and/or a reproducible example, we simply don't know what's happening. If you think this is an issue with our code, please open a new issue with the full bug report template filled in.

Hope this helps!

**Comment by iamrekhaverma** [comment]
Created a new issue with the reproducible repo link. https://github.com/expo/expo/issues/10938 I am not sure what's going wrong here https://github.com/iamrekhaverma/LocalAuthExample
