### ISSUE TITLE
components not in use on a app are included...?

### ISSUE THREAD

**Issue by nyakamura** [expo/expo#10939]
hi
My app was indicated by the security assessment service that components not in use on your app should not be included.

- host.exp.Exponent.experience.TvActivity
- com.facebook.CustomTabActivity

This `TvActivity` seems to be part of  Expo.
https://github.com/expo/expo/pull/1957/files

Is it possible to isolate it?

thanks

**Comment by byCedric** [comment]
Hi @nyakamura, yes this is [included in a managed app by default](https://github.com/expo/expo/blob/master/template-files/android/AndroidManifest.xml#L140-L149). If you need to modify these native settings, you have to eject and manage that yourself. You can [see a walkthrough of that, here](https://docs.expo.io/bare/exploring-bare-workflow/).

Hope this helps!
