### ISSUE TITLE
Setup expo mocha test

### ISSUE THREAD

**Issue by alakdam07** [expo/expo#10936]
I am using expo-typescript app. I want to test my app. For testing the app I am planning to use mocha test. In expo documentation I found only [Jest](https://docs.expo.io/guides/testing-with-jest/) setup. I did not find anywhere, how to setup Mocha testing. When I run the test by doing `npm run test` and I got error.

I setup my app like this. 
<img width="266" alt="testing" src="https://user-images.githubusercontent.com/47625626/98339015-bc446b00-2013-11eb-9477-dd8801b67be4.png">

**This is my package.json**
 ```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "clearcache": "expo r -c",
    "typecheck": "tsc",
    "test": "mocha"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.10.0",
    "@react-navigation/native": "^5.8.0",
    "@react-navigation/stack": "^5.10.0",
    "@reduxjs/toolkit": "^1.4.0",
    "chai": "^4.2.0",
    "chai-http": "^4.3.0",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "expo": "~39.0.2",
    "expo-secure-store": "~9.2.0",
    "expo-status-bar": "~1.0.2",
    "mocha": "^8.2.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-appearance": "^0.3.4",
    "react-native-flash-message": "^0.1.16",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-modalize": "^2.0.6",
    "react-native-portalize": "^1.0.7",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.2",
    "styled-components": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-dom": "~16.9.8",
    "@types/react-native": "~0.63.2",
    "@typescript-eslint/eslint-plugin": "^4.6.0",
    "@typescript-eslint/parser": "^4.6.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-preset-expo": "^8.3.0",
    "eslint": "^7.12.1",
    "eslint-import-resolver-babel-module": "^5.2.0",
    "typescript": "^3.9.7"
  },
  "private": true
}
```

**Comment by byCedric** [comment]
Hi @alakdam07, unfortunately, we don't support Mocha. If you want to use it, you have to implement basically everything we implement for you in `jest-expo`. For example, you'd have to
- Mock [some native modules](https://github.com/expo/expo/blob/master/packages/jest-expo/src/preset/setup.js)
- Fake some [phone information](https://github.com/expo/expo/blob/master/packages/jest-expo/src/preset/createMockConstants.js)
- Setup [transpiling with Metro](https://www.bengladwell.com/testing-react-native-components-with-mocha/)
- Add drivers for [snapshot testing](https://github.com/expo/expo/tree/master/packages/jest-expo/src/snapshot)

You are free to use mocha, if you want to set it up I'd recommend checking out our `jest-expo` package. But this is not something we actively support.

Hope this helps!
