### ISSUE TITLE
Local authentication returns {“1”: “FINGERPRINT”, “2”: “FACIAL_RECOGNITION”, “FACIAL_RECOGNITION”: 2, “FINGERPRINT”: 1, IRIS:3} in bare workflow(IOS)

### ISSUE THREAD

**Issue by iamrekhaverma** [expo/expo#10938]
### Summary of Issue 

 used LocalAuthentication in a bared React-Native project:

"expo-local-authentication": "^9.3.0",
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-unimodules": "^0.11.0"

undefined is not an object (evaluating ‘_ExpoLocalAuthentication.default.authenticateAsync’)

Any help pls?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Bare react native app(IOS)

### Reproducible Demo
Repo link for just checking if LocalAuthentication's methods are available or not
https://github.com/iamrekhaverma/LocalAuthExample
 
### Steps to Reproduce
Need to clone the repo and npm install and pod install also

### Expected Behavior vs Actual Behavior
The result should be true or false but it shows unhandled promise rejection (Undefined is not an object)

**Comment by byCedric** [comment]
Hi @iamrekhaverma, thanks for the repro. It looks like your iOS project is set up properly, although I encountered an issue with the `Podfile.lock`. Can you try to remove it, and use `npx pod-install` in the root of your project? That should fix possible native dependency issues. I also want to mention that unimodules isn't linked in Android, just as an FYI. If you want to run it on Android, you still have to do these steps.

The message you mention in the title is also what we would expect. `JSON.stringify` would never compile methods of an object to string. If you want to see all methods available for this module, try `JSON.stringify(Object.keys(LocalAuthentication))`, which would also include the names of methods.

Hope this helps!

**With `JSON.stringify(LocalAuthentication)`**
![Screenshot 2020-11-06 at 13 43 47](https://user-images.githubusercontent.com/1203991/98367736-6df49380-2036-11eb-93ad-36254e35bd54.png)

**With `JSON.stringify(Object.keys(LocalAuthentication))`**
![Screenshot 2020-11-06 at 13 53 53](https://user-images.githubusercontent.com/1203991/98368364-844f1f00-2037-11eb-9292-e763fce647d7.png)

**Comment by iamrekhaverma** [comment]
@byCedric When we run this `npx pod-install`, does it update podfile.lock?

**Comment by alexgas** [comment]
Hi! same issue here. I removed the `Podfile.lock` and used and use `npx pod-install` again. 

It's very strange behavior, the MetroBundler says: 
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating '_ExpoLocalAuthentication.default.authenticateAsync')
```
but only in the very first running, if I refresh the app works properly. 


p.d: I am using the iPhone 8 v14.0 simulator and works perfectly on android.

**Comment by byCedric** [comment]
@iamrekhaverma, not necessarily. You can see what it [tries to do exactly over here](https://github.com/expo/expo-cli/blob/master/packages/package-manager/src/CocoaPodsPackageManager.ts#L164-L184). And no, you don't need that to call the methods, you only need it to check the available methods with `JSON.stringify` (only for debugging this).

@alexgas it could be related to some weird metro caching, have you tried force-clearing that cache? (see [this snippet](https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d))

**Comment by alexgas** [comment]
@byCedric I just cleaned cache (yarn in my case) and the behavior is the same.
My code is something like that: 

```
import * as LocalAuthentication from "expo-local-authentication";
...
console.log(JSON.stringify(Object.keys(LocalAuthentication)));
let verificationResultAviable = await LocalAuthentication.hasHardwareAsync();
...
```

And the log in the Metro Bundler is: 
```
  LOG  ["hasHardwareAsync","supportedAuthenticationTypesAsync","isEnrolledAsync","authenticateAsync","cancelAuthenticate","AuthenticationType"]
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating '_ExpoLocalAuthentication.default.hasHardwareAsync')
...
```

how I said before, this happens in the first execution on simulator (works ok after refresh) and on production environment (installing via IPA file) 😞

**Comment by alexgas** [comment]
Update: I upgraded the rn version to 0.63.3, expo to sdk 39 and expo-local-authentication to 9.3.0.

Now, it works 👍

**Comment by alexgas** [comment]
I was wrong, is not working after the upgrade.

I am using: 

"expo": "39.0.4",
"react": "~16.13.1",
"react-native": "~0.63.3"
"expo-local-authentication": "^9.3.0",

Any idea @iamrekhaverma  @byCedric ??

**Comment by iamrekhaverma** [comment]
@alexgas It has been fixed. The issue was in the pod file. Just moving some statements above fixed it.

**Comment by byCedric** [comment]
Awesome, happy holidays!

**Comment by Basir-PD** [comment]
I faced similar issue when installing expo-local-authentication in React Native CLI on Android. I solved it by installing [Expo Modules](https://docs.expo.dev/bare/installing-expo-modules/) through `npx install-expo-modules`. Remember that react-native-unimodule is deprecated in favor of above mentioned expo-module package.
