### ISSUE TITLE
[ImagePicker] compileDebugKotlin fails if kotlinVersion in build.gradle is set to 1.3.50

### ISSUE THREAD

**Issue by nicolasbraun** [expo/expo#10931]
With error `Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?`
Which is odd since this is the default version to fallback too in the expo code

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1089363/98260098-324cc180-1f83-11eb-8c3b-101f96b066dd.png">

**Comment by sertiano93** [comment]
@nicolasbraun did you solve it ? 
I have the same problem

**Comment by nicolasbraun** [comment]
@sertiano93 I did not, i am currently using the version 1.3.21 (default value for RN 0.63 if I remember correctly)

**Comment by lukmccall** [comment]
Fixed by https://github.com/expo/expo/pull/11552. Please check the newest versions -> 10.0.0.

**Comment by Sheharyar566** [comment]
I'm at image-picker 10.0.0, and the error still occurs

**Comment by renanbronchart** [comment]
I had the same error with image-picker 10.0
I update my build.gradle with this classpath : 

classpath("com.android.tools.build:gradle:3.6.3")

From 3.5.3 to 3.6.3
