### ISSUE TITLE
some strings are saved in a local file by sending a malicious intent.

### ISSUE THREAD

**Issue by nyakamura** [expo/expo#10937]
Hi,
It has been confirmed that when some apps send a malicious intent to my app, some strings are saved in a local file.
My  app is  a  standalone-app.

example: sending an intent
```
private void sendBroadcast(){
    Intent intent = new Intent();
    intent.setAction("com.android.vending.INSTALL_REFERRER");
    intent.setClassName("net.myapp.test","host.exp.exponent.referrer.InstallReferrerReceiver");
    intent.putExtra("referrer","TEST"); sendBroadcast(intent);
}
```

saved local file
/shared_prefs/host.exp.exponent.SharedPreferences.xml
`<string name="referrer">TEST</string>`

SDK Version: 38 or 39
Platform: Android

thanks

**Comment by cruzach** [comment]
hi @nyakamura ! If you can provide a clear explanation of what exactly the threat is and how to defend against it, please do, but otherwise this issue probably won't get much attention, so I'm going to close it for now.

**Comment by nyakamura** [comment]
hi @cruzach 
I appreciate your point of view.

I don't know the magnitude of the security threat, but it was indicated by the security assessment service.
I think the following methods are possible.
- If the app don't need calls from other app, set the attribute android:exported="false" (for components defined in AndroidManifest)
- Calling from outside is necessary, but if the caller can be limited, restrict the source of access by permission or signature.
- If it is difficult to restrict access, verify the security of the Intent to be received.

thanks
