### ISSUE TITLE
Inaccurate reporting of orientation from OrientationChangeListener in SDK39

### ISSUE THREAD

**Issue by badbod99** [expo/expo#10944]
### Summary of Issue 

ScreenOrientation OrientationChangeListener incorrectly returns orientation when changing.  Change event is fired, by orientation value is same as previous value.  Issue was not found in SDK 38, but present in SDK 39.

[Example of **working** SDK 38 version in Snack](https://snack.expo.io/@badbod99/thankful-mixed-nuts).  This version consistently reports correct orientation unlike SDK 39.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

 Expo CLI 3.28.2 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~39.0.2 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible Demo

Snack currently running SDK38, issue is only present in SDK39.  Reproducible with simple project created with expo init and expo-screen-orientation added via expo install.

```javascript
import { StatusBar } from 'expo-status-bar';
import React, { useEffect, useState } from 'react';
import * as ScreenOrientation from 'expo-screen-orientation';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  const [screenOrientation, setScreenOrientation] = useState();

  useEffect(() => {
    const onOrientationChange = (currentOrientation) => {
      const orientationValue = currentOrientation.orientationInfo.orientation;
      setScreenOrientation(orientationValue)
    }

    const initScreenOrientation = async () => {
      const currentOrientation = await ScreenOrientation.getOrientationAsync();
      setScreenOrientation(currentOrientation);
    };

    const screenOrientationListener = ScreenOrientation.addOrientationChangeListener(
      onOrientationChange,
    );

    initScreenOrientation();
    return () => {
      ScreenOrientation.removeOrientationChangeListener(screenOrientationListener);
    };
  }, []);

  
    return (
    <View style={styles.container}>
      <Text>This test app shows current screen orientation as a number</Text>
      <Text>{screenOrientation}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
 
### Steps to Reproduce

1. Create new project with `expo init --template blank`
2. Install expo-screen-orientation with `expo install expo-screen-orientation`
3. Add above code to App.js
4. Set orientation to default in app.json `"orientation": "default",`
5. Run using `expo start` on Android device
6. Rotate screen from portrait to landscape 10-15 times and note value of orientation shown on screen

### Expected Behavior vs Actual Behavior

Expected: When rotating from Portrait to Landscape, expect change listener to get value of 3 or 4.  When rotating from Landscape to Portrait, expect to get value of 1 or 2.

Actual: Sometimes getting Landscape orientation when rotating from Landscape to Portrait.  Sometimes getting Portrait orientation when rotating from Portrait to landscape.  Fault seems to be always due to reporting previous value rather than new orientation.  Also checked with console.log directly on the event, rather than useState, same issue.

Reference enum:

```javascript
export declare enum Orientation {
    UNKNOWN = 0,
    PORTRAIT_UP = 1,
    PORTRAIT_DOWN = 2,
    LANDSCAPE_LEFT = 3,
    LANDSCAPE_RIGHT = 4
}
```

**Comment by badbod99** [comment]
Possibly related to Dimensions API in React Native, update released in 63.4 here https://github.com/facebook/react-native/commit/0e9296b95da06789121f052e6cd6d7cac808464c

**Comment by Baloche** [comment]
I think I discovered the same issue.

Here are my observations : 
- When orientation changes from `PORTRAIT_*` to `LANDSCAPE_*`, everything is fine, the listener is triggered
- But when I rotate my device quickly so that the orientation switches directly between the two landscape modes without passing by `PORTRAIT_*`, the listener is not triggered.

If it is indeed related to the Dimensions API, I believe this might be due to `width` and `height` not changing when switching to one of the `LANDSCAPE_*` comming from the other `LANDSCAPE_*`

**Comment by CostachescuCristinel** [comment]
Having same issue on Expo SDK 40. Even worse, both on Android and iOS:
- Orientation mode `PORTRAIT_DOWN` (upside-down screen) never triggers. However, I suspect this might be an OS thing where upside-down is kept unchanged from the previous orientation, intentionally.
- Orientation modes `LANDSCAPE_LEFT` and `LANDSCAPE_RIGHT` are inverted!
  Issue happens both on real device and simulator. Easier to test on simulator (iOS), set `Device > Orientation > Landscape left`. In an orientation change listener you will find that it reports `LANDSCAPE_RIGHT`. The inverse happens with `Landscape right` reporting `LANDSCAPE_LEFT`.

**Comment by CostachescuCristinel** [comment]
Hi, any updates please? I am working on an app that really needs orientation to work properly, the development of multiple parts of it is stale due to this issue...

**Comment by AlexJWayne** [comment]
It seems the `PORTRAIT_DOWN` cannot be detected on iPad? See simple snack:
https://snack.expo.dev/@alexwayne/rebellious-pastry

Open on an iPad, rotate to portrait down, and see that the orientation name stays the same even though the view does adjust to that orientation just fine.

I have a crazy work around where I check the window dimensions to see if they are taller than they are wide, and if the reported orientation is landscape, then I assume it's `PORTRAIT_DOWN`. However, this misses the quick flip from `PORTRAIT_UP` directly to `PORTRAIT_DOWN`.

**Comment by Baloche** [comment]
The issue still exists

**Comment by liquidvisual** [comment]
For me, this straight up doesn't log anything. Have I done something wrong?

```
ScreenOrientation.addOrientationChangeListener((e) => {
 console.log(e);
});
```

**Comment by albert-03** [comment]
The issue still exists,  addOrientationChangeListener does not detect  PORTRAIT_DOWN and LANDSCAPE_RIGHT
