### ISSUE TITLE
Making web requests and using NPM packages not optimized for React Native

### ISSUE THREAD

**Issue by FerretCode** [expo/expo#10945]
Hi! I just discovered Expo and I think it's super nifty however, I have two questions:

One: Is there a way to make web requests from my app without using any libraries like request or axios?

Two: Is there a way to use normal NPM packages inside of my Expo app?

Thanks in advance :)

**Comment by brentvatne** [comment]
1. use `fetch`. https://reactnative.dev/docs/network#using-fetch
2. https://docs.expo.io/bare/using-libraries/
