### ISSUE TITLE
Corrupt APK after build

### ISSUE THREAD

**Issue by asela-wijesinghe** [expo/expo#1094]
I tried building android apk from `exp build:android` all expo projects are built fine and running on the android device except for a one type of app (after checking for 5-6 hours) doesn't seem to work as expected. when i use `exp init ` and create a **project with tabs** and after i build it APK seems to throw error 

> there was a problem while parsing the package

but in all other occasions i created testing apps and they working fine in the device.only this type.
can someone please check whether i am right and find a fix? 

This is my full story from morning in the forum.
Link:  [https://forums.expo.io/t/corrupt-apk-after-build/5487](url)

**Comment by terribleben** [comment]
Hey there, I'm having a hard time understanding how to reproduce the issue. 

- `exp init`
- Tabs project
- `exp build:android`
- ????
- "there was a problem while parsing the package"

Can you help fill in the "???" Can you also mention what type of Android device you are testing on, and what version of Android it is running? Thanks!

**Comment by asela-wijesinghe** [comment]
hi ??? would be installing the APK to the device after the build. the error
was the "parse error" since the build was corrupted and i tried it on
several devices As i mentioned the APK worked for me when i create it
"without tabs" option.
Also miraculously my app compiled correctly and started working nicely
after doing more than 10 builds.
i hope its somethng in the exp build engine and maybe it would have fixed
at some point and right now i cant reproduce the error and it builds
perfectly now.
but you can find the issue if needed i can send you the corrupt APK.right
now this issue is no more

**Comment by terribleben** [comment]
Ok, there's probably not a lot we can do for now. I recommend making sure the `package` field under `android` in `app.json` is a valid Android package value. Please let us know if you start seeing this issue again.
