### ISSUE TITLE
Expo-Print html doesn't respect @page css 

### ISSUE THREAD

**Issue by himrocks33** [expo/expo#10943]
### Summary of Issue 
When using expo-print printAsync the html property does not respect the @page css property.  My guess this is due to safari not supporting this property.  This is a major issue though as you cannot set margins on print out.  Thus, pages are being cut off when printing.  Using the same html with the property "markupFormatterIOS"  works as expected.  Please do not remove this property without figuring out a solution to page margins. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
iOS 

### Reproducible Demo
css:
@page {
    margin: 1cm;
}

Doesn't work on iOS:
await Print.printAsync({ html })

Does work on iOS
await Print.printAsync({ markupFormatterIOS: html })

**Comment by vanpacheco** [comment]
Same thing is happening with printToFileAsync on iOS.

**Comment by moedeveloper** [comment]
any solution?

**Comment by kdechant** [comment]
Old issue, but commenting for future reference:

If anyone is trying to set margins on the printed page on iOS, there's a 'margins' option to do this. (iOS only.) [See the Expo documentation](https://docs.expo.dev/versions/latest/sdk/print/#page-margins).

Example from the docs: 
```
const { uri } = await Print.printToFileAsync({
  html: 'This page is printed with margins',
  margins: {
    left: 20,
    top: 50,
    right: 20,
    bottom: 100,
  },
});
```
