### ISSUE TITLE
AsyncStorage Android Limitation cannot be configured

### ISSUE THREAD

**Issue by xsmcemmons** [expo/expo#10953]
### Please note that discussions opened as issues in the core Expo repository will be closed.

I'm doing an Expo Bare App using React Native and AWS Datastore features. Everything was working so far but my DB size started to grow. I have a Product table with over 4000k records. AWS Datastore says that it uses SQLite as it database, but the engine that works with the sync part of the process seems to be working with AsyncStorage. In android we have a [6MB limitation](https://github.com/facebook/react-native/issues/7869) and when we try to sync up our products data, it gives us the Database full error. 

```
Possible Unhandled Promise Rejection (id: 7):
Array [
  [Error: database or disk is full (code 13)],
]
```

I have read [this issue](https://github.com/expo/expo/issues/878) that says we cannot modify the MainActivity.java, from 2017.. I'd like to know if this is something that has already changed so I can put a larger size for my datastore sync process could work.

### Environment 

    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Users\cemmons\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: 38.0.9 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: bare

**Comment by byCedric** [comment]
Hi @xsmcemmons, please see the [documentation of `@react-native-community/async-storage`](https://react-native-async-storage.github.io/async-storage/docs/advanced/db_size). This should be possible for you to configure because you mentioned you used Expo bare 😄
