### ISSUE TITLE
Accuracy.BestForNavigation and Galileo (not GPS) compatible devices

### ISSUE THREAD

**Issue by iliastsergoulas** [expo/expo#10950]
Does Accuracy.BestForNavigation (in LocationAccuracy) support non-GPS sensors (especially [Galileo](https://www.gsa.europa.eu/galileo/services/initial-services/galileo-enabled-devices) of the GNSS options) that come with new devices?

**Comment by byCedric** [comment]
Hi @iliastsergoulas, the short answer is yes that should be supported. The slightly longer answer is, we use [Android's Fused Location API](https://developers.google.com/location-context/fused-location-provider). It combines data from multiple sensors, including Galileo, GPS and others, into a single client. Galileo is already compatible with over 1 billion devices, so some of them probably use Galileo already.

Hope it helps!

**Comment by iliastsergoulas** [comment]
Thank you so much @byCedric for your answer. Whether it is supported was my worry so, once verified, I have no problem with API's auto-determining best data.
