### ISSUE TITLE
IPOS print Not Printing with expo-print

### ISSUE THREAD

**Issue by wissedenis** [expo/expo#10952]
Hello thanks for this great SDK.

 I tried run this tutorial "https://snack.expo.io/2qHwNJRsg" on this wireless Data POS System but it only stops on searching printer.  The model of printer is IPOS Printer
Kindly is there anything I need to do in order find the printer

**Comment by byCedric** [comment]
Hi @wissedenis, I'm not sure how we can help here. On both iOS and Android, we use the underlying OS Print APIs. This means, if you can add the printer to the OS successfully, it should work. But I'm not sure on what OS you are running, and I don't have that printer unfortunately. The manufacturer might have additional libraries that you might need to add to make it work, if they have you have to use the Expo bare workflow.

Hope this helps!

**Comment by wissedenis** [comment]
> Hi @wissedenis, I'm not sure how we can help here. On both iOS and Android, we use the underlying OS Print APIs. This means, if you can add the printer to the OS successfully, it should work. But I'm not sure on what OS you are running, and I don't have that printer unfortunately. The manufacturer might have additional libraries that you might need to add to make it work, if they have you have to use the Expo bare workflow.
> 
> Hope this helps!

the OS is Android. it runs on Android
