### ISSUE TITLE
AV: setPositionAsync Not working correctly for iOS

### ISSUE THREAD

**Issue by btk** [expo/expo#1095]
Hey;

```JS
 let soundObj = new Audio.Sound();

soundObj.loadAsync(require("./blah"));

let play = () => {
  soundObj.setPositionAsync(0).then(() => {
    soundObj.playAsync();
  });
}
```

In my use case, I create one sound object and load it for only one time, that I know I will be playing it through out the app. And I use `setPositionAsync` to set the native player (?) timer to zero.

This works as I want it to be in Android. It also works in the iOS, but the problem is, sound starts from the 100ms. I looked at the code if is there anything I can do, but it seems about native ios?

**Comment by EvanBacon** [comment]
Could you please provide a snack that reproduces this error?

**Comment by sjchmiela** [comment]
Hi @btk, there are two issues that you may encounter here:

1. **Tolerance of `setPositionAsync`.** `AVPlayer`, which we use under the hood, by default has an infinite seek tolerance, meaning it may not seek to the exact time requested if it decides that it will save some decoding time by seeking to a position near the one requested (see [Apple documentation](https://developer.apple.com/documentation/avfoundation/avplayer/1387741-seek#discussion)). To customize seek tolerance you can use [`setPositionAsync(millis, { toleranceMillisBefore, toleranceMillisAfter })`](https://docs.expo.io/versions/latest/sdk/av.html#playbackobjectsetpositionasyncmillis--tolerancemillisbefore-tolerancemillisafter-) introduced in SDK 24.
2. **Better way to replay sounds.** To help developers mitigate effects of long decoding and seeking time of iOS, in SDK 24 we've introduced a new method [`replayAsync`](https://docs.expo.io/versions/latest/sdk/av.html#playbackobjectreplayasyncstatustoset). `Audio` API [now](https://github.com/expo/expo/commit/0caf4d47bae0bc32b9facfe415be0dd8fb9288d7) uses `AVQueuePlayer` behind the scenes, which is capable of storing a queue of items to play and decodes next item ahead of time.

Let us know if any of these methods resolves your problems!

**Comment by btk** [comment]
@sjchmiela thank you so much!
