### ISSUE TITLE
Expo files error on production with Xiaomi Redmi phones: /data/user/0/com.company.project/files/.expo-internal/filename

### ISSUE THREAD

**Issue by esteban199** [expo/expo#10951]
![WhatsApp Image 2020-11-07 at 9 32 26 AM](https://user-images.githubusercontent.com/32593721/98442881-127de080-20de-11eb-83ca-392b24f5bf98.jpeg)

![WhatsApp Image 2020-11-07 at 9 42 25 AM](https://user-images.githubusercontent.com/32593721/98442882-13af0d80-20de-11eb-81e9-df73556a7778.jpeg)

On development everything is fine, but on production when i try to call login and fetch a request with fetch or axios i get following error... the error is only present with Xiaomi Redmi phones...

i test these versions and get the same bug: 
"expo": "~37.0.3",
"react-native": "~0.61.5",

"expo": "~39.0.2",
"react-native": "0.63.3",

**Comment by byCedric** [comment]
Hi @esteban199, it looks like something is up with the permissions of your app. On the background error, I can see that it can't connect to the internet. I'm not sure what's going on with the one on the foreground, but it could be related. Maybe this can help, it looks [like MIUI/MI phones have special functionality to block internet access to apps](https://c.mi.com/thread-2263899-1-0.html). I'm not sure how we can help you further here, this isn't possible on other phone manufacturers.

Hope this helps!

**Comment by esteban199** [comment]
thank you @byCedric, the problem was with my api, cause was not serve over https, some devices block those apis that are serve over http for security reasons...
