### ISSUE TITLE
Call History

### ISSUE THREAD

**Issue by cyaxares** [expo/expo#1096]
Hello
I use Checkmobi for verification and need access to Call history,  React Native have some Packages when I added on Expo I receive this Error “ Native module can not be null “ do u have way for solve this Error?

Or other same way in Expo? Or don’t way in Expo?

Thanks and Regards

**Comment by EvanBacon** [comment]
Unfortunately we do not support this feature at the moment. 
I added it as a feature request to our canny, [you can up vote it here!](https://expo.canny.io/feature-requests/p/get-the-devices-phone-call-history) 

Currently if you want to add external native modules you need to ["detach"](https://docs.expo.io/versions/latest/guides/detach.html#content) your app. After detaching you will get a native ios and android folder, from there you can add and link custom native modules.

**Comment by ide** [comment]
This API access very sensitive information and is likely subject to stricter app review. We can't add risk for the vast majority of apps that don't need this feature. This is best left to the bare workflow where you can write whatever native code you need instead.
