### ISSUE TITLE
Expo Bare Workflow Segment

### ISSUE THREAD

**Issue by Sigve84** [expo/expo#10963]
### Summary of Issue 
If Segment is added to package.json its not possible to build an Android Bare workflow app. Ios works fine. Get an error message indicating duplicate classes. Error messages are in the bottom of this report. I tested with a clean javascript Expo project, and ejected. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.1, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.3
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare

### Steps to Reproduce
Clean Expo project. Eject it to bare workflow. Add

"expo-ads-admob": "~8.3.0",
 **"expo-analytics-segment": "9.0.0",**

Package.json:
"dependencies": {
    "expo": "~39.0.2",
    "expo-ads-admob": "~8.3.0",
    "expo-analytics-segment": "9.0.0",
    "expo-splash-screen": "~0.6.2",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.3",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-screens": "~2.10.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.12"
  },

run: 
yarn android

### Expected Behavior vs Actual Behavior

**Actual:**

Installing unimodules:
 unimodules-core@5.5.1 from xx/testandroidbareworkflow/node_modules/@unimodules/core
 unimodules-react-native-adapter@5.6.0 from xx/testandroidbareworkflow/node_modules/@unimodules/react-native-adapter
 expo-ads-admob@8.3.0 from xx/testandroidbareworkflow/node_modules/expo-ads-admob
 expo-analytics-segment@8.2.1 from xx/testandroidbareworkflow/node_modules/expo-analytics-segment
 expo-constants@9.2.0 from xx/testandroidbareworkflow/node_modules/expo-constants
 expo-error-recovery@1.3.0 from xx/testandroidbareworkflow/node_modules/expo-error-recovery
 expo-file-system@9.2.0 from xx/testandroidbareworkflow/node_modules/expo-file-system
 expo-font@8.3.0 from xx/testandroidbareworkflow/node_modules/expo-font
 expo-image-loader@1.2.0 from xx/testandroidbareworkflow/node_modules/expo-image-loader
 expo-keep-awake@8.3.0 from xx/testandroidbareworkflow/node_modules/expo-keep-awake
 expo-linear-gradient@8.3.1 from xx/testandroidbareworkflow/node_modules/expo-linear-gradient
 expo-location@9.0.1 from xx/testandroidbareworkflow/node_modules/expo-location
 expo-permissions@9.3.0 from xx/testandroidbareworkflow/node_modules/expo-permissions
 expo-splash-screen@0.6.2 from xx/testandroidbareworkflow/node_modules/expo-splash-screen
 expo-sqlite@8.4.0 from xx/testandroidbareworkflow/node_modules/expo-sqlite
 expo-updates@0.3.5 from xx/testandroidbareworkflow/node_modules/expo-updates
 unimodules-app-loader@1.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-app-loader
 unimodules-barcode-scanner-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-barcode-scanner-interface
 unimodules-camera-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-camera-interface
 unimodules-constants-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-constants-interface
 unimodules-face-detector-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-face-detector-interface
 unimodules-file-system-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-file-system-interface
 unimodules-font-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-font-interface
 unimodules-image-loader-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-image-loader-interface
 unimodules-permissions-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-permissions-interface
 unimodules-sensors-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-sensors-interface
 unimodules-task-manager-interface@5.3.0 from xx/testandroidbareworkflow/node_modules/unimodules-task-manager-interface

> Task :app:checkDebugDuplicateClasses FAILED

> Transform artifact firebase-analytics-16.0.3.aar (com.google.firebase:firebase-analytics:16.0.3) with DexingWithClasspathTransform

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
442 actionable tasks: 2 executed, 440 up-to-date
AGPBI: {"kind":"error","text":"Type com.google.android.gms.internal.measurement.zzwv is referenced as an interface from `com.google.android.gms.internal.measurement.zzfq$zzb$zza`.","sources":[{}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.android.gms.internal.measurement.zzsr found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.internal.measurement.zzss found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.internal.measurement.zzst found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.internal.measurement.zzsu found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.internal.measurement.zzsv found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.measurement.internal.zzcu found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.measurement.internal.zzcv found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.measurement.internal.zzcw found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.measurement.internal.zzcx found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.measurement.internal.zzcy found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)
  Duplicate class com.google.android.gms.measurement.internal.zzdw found in modules jetified-firebase-analytics-impl-16.2.1-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.1) and jetified-play-services-measurement-base-16.3.0-runtime.jar (com.google.android.gms:play-services-measurement-base:16.3.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
AGPBI: {"kind":"error","text":"Type com.google.android.gms.internal.measurement.zzwv is referenced as an interface from `com.google.android.gms.internal.measurement.zzfq$zzb$zza`.","sources":[{}],"tool":"D8"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by cruzach** [comment]
hi @Sigve84 , thanks for reporting this! could you try making the changes in https://github.com/expo/expo/pull/10972 manually to `yourProjectDirectory/node_modules/expo-analytics-segment/android/build.gradle`  and let me know if that fixes it?
