### ISSUE TITLE
How do I fix this issue node_modules/expo/AppEntry.js: [BABEL] ?

### ISSUE THREAD

**Issue by hvaandres** [expo/expo#10964]
#node_modules/expo/AppEntry.js: [BABEL]

I already installed all the dependencies for my project, and I'm getting this issue, and I'm not sure how to solve it. 

#package.json - Main 

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "babel": "^6.23.0",
    "expo": "~39.0.2",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-dotenv": "^2.4.2",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-plugin-module-resolver": "^4.0.0"
  },
  "private": true,
  "name": "my-project"
}

```

# babel.config.js

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo", "module:react-native-dotenv"],
  };
};

```

My github repository is the following: 

`https://github.com/hvaandres/WeatherApp_React`

**Comment by hvaandres** [comment]
I ran this command to see if I can fix it or not `npm i --save-dev babel-plugin-module-resolver@latest` and it seems that is still the same.

**Comment by byCedric** [comment]
Hi @hvaandres, it seems that you added 2 incompatible libraries. The first would be `"babel": "^6.23.0"`, it's incompatible because we use babel 7 internally. Adding this version of babel, which I personally don't think you should need to add, may causes issues between these two.

The other one is the deprecated [`"react-native-dotenv": "^2.4.2"`](https://github.com/zetachang/react-native-dotenv/blob/master/package.json#L16). This library was last worked on 2 years ago, and might be severely outdated. You probably have more luck using [`babel-plugin-inline-dotenv`](https://github.com/brysgo/babel-plugin-inline-dotenv) which is actively maintained and shouldn't cause issues like these.

Hope this helps!

**Comment by hvaandres** [comment]
Well babel was added by itself when I used the command to create the react-native project through expo. Your answer has not logic @byCedric. I will look it up for the updated version of dotenv. However, why do we have documentation published by NPM that doesn't work anymore?

**Comment by hvaandres** [comment]
I uninstall the previous version, and it doesn't do anything. I still get the same issue. Meaning that your answer didn't work at all. Looking at the latest JSON file:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "babel-plugin-inline-dotenv": "^1.6.0",
    "babel-preset-expo": "^8.3.0",
    "expo": "~39.0.2",
    "expo-location": "~9.0.0",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/cli": "^7.12.1",
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.12.1",
    "babel-plugin-module-resolver": "^4.0.0"
  },
  "private": true,
  "name": "my-project"
}
```

**Comment by byCedric** [comment]
If you can point me to the parts where we recommend [`react-native-dotenv`](https://github.com/expo/expo/search?q=react-native-dotenv) and/or the part where we add [`"babel": "^6.23.0"`](https://github.com/expo/expo/search?q=%22babel%22%3A+%22%5E6.23.0%22), I'm happy to update that. I've tested the solution I provided with your example app, and I'm 100% sure that should work. If it doesn't it could be related to other issues with environments or local setup. 

It's not really motivating or helpful to say that "Your answer has not logic" or "Meaning that your answer didn't work at all". If you don't understand the problem or solution, ask more questions about the stuff you don't understand or would like an explanation for.

You might be able to [debug it further with this guide](https://docs.expo.io/workflow/debugging/).

**Comment by hvaandres** [comment]
I just used this documentation `https://docs.expo.io/`. I ran the following commands: "npm install --global expo-cli  expo init my-project" This includes the version of my previous version of Babel. I didn't do anything different. [NPM published a new version 18 days ago](https://www.npmjs.com/package/react-native-dotenv)

**Comment by marksikaundi** [comment]
node_modules\expo\AppEntry.js: Unknown option: .Plugins. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    Plugins: ["tailwindcss-react-native/babel"],
  };
};
`

**Comment by marksikaundi** [comment]
any help will be highly appreciated

**Comment by brentvatne** [comment]
@marksikaundi - use lower case p on Plugins, it is `plugins` not `Plugins`

**Comment by marksikaundi** [comment]
thanks i didnt notice that, now all good

**Comment by pierregambaud** [comment]
Adding the following to my `package.json` solved my "api.addExternalDependency is not a function" error:
```
"resolutions": {
  "@babel/core": "^7.20.2",
  "babel-loader": "8.3.0"
}
```

_Source: https://dev.to/goatandsheep/how-to-use-babels-new-addexternaldependency-api-338h_

**Comment by yalinn** [comment]
in you are using **expo-router** you should enter this in package.json:
```json
"main": "expo-router/entry",
```

**Comment by hariDasu** [comment]
still unclear how to solve this varying combinations of these did not work for me starting from create-t3-turborepo with expo sdk 51

**Comment by learnersaurabh** [comment]
thanks @yalinn ,this worked for me to fix  node_modules/expo/AppEntry.js error.

**Comment by BlueBigThink** [comment]
My project was working well with expo 48. But google store asked me to upgrade to API 34. So I upgrade the expo to SDK50.
Now I got these errors on the Android Emulator

Android Bundled 2469ms (D:\Antonio\blogchain\node_modules\expo\AppEntry.js)
 ERROR  TypeError: undefined is not a constructor (evaluating 'new _reactNativeReanimated.default.Value(0)')
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

How can I fix this issue? I will share my package.json


{
  "main": "node_modules/expo/AppEntry.js",
  "name": "blogchain",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest",
    "lint": "eslint . --ext .ts,.tsx --quiet"
  },
  "dependencies": {
    "@babel/core": "^7.20.0",
    "@coder-shubh/react-native-image-slider": "^1.0.6",
    "@dev-plugins/react-query": "^0.0.7",
    "@expo/config-plugins": "^7.8.0",
    "@expo/metro-config": "^0.17.8",
    "@expo/prebuild-config": "^6.7.0",
    "@flyerhq/react-native-link-preview": "^1.6.0",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-masked-view/masked-view": "0.3.0",
    "@react-navigation/drawer": "5.12.5",
    "@react-navigation/native": "5.9.4",
    "@react-navigation/stack": "5.14.5",
    "@reduxjs/toolkit": "^2.2.7",
    "@tanstack/react-query": "^5.56.2",
    "@types/react": "~18.0.27",
    "@types/react-native-indicators": "^0.16.6",
    "axios": "^1.7.7",
    "babel-plugin-module-resolver": "^5.0.2",
    "dayjs": "1.10.5",
    "expo": "~50.0.20",
    "expo-av": "~13.10.6",
    "expo-blur": "~12.9.2",
    "expo-constants": "~15.4.6",
    "expo-file-system": "~16.0.9",
    "expo-haptics": "~12.8.1",
    "expo-image-picker": "~14.7.1",
    "expo-linear-gradient": "~12.7.2",
    "expo-localization": "~14.8.4",
    "expo-modules-autolinking": "~1.10.0",
    "expo-modules-core": "~1.11.14",
    "expo-splash-screen": "~0.26.5",
    "expo-status-bar": "~1.11.1",
    "i18n-js": "3.8.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-infinite-scroll-component": "^6.1.0",
    "react-native": "0.73.6",
    "react-native-calendars": "1.1263.0",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-gifted-chat": "0.16.3",
    "react-native-image-slider-banner": "^1.0.3",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "0.9.4",
    "react-native-pager-view": "6.2.3",
    "react-native-progress": "^5.0.1",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-speedometer": "^1.0.5",
    "react-native-speedometer-chart": "^0.7.5",
    "react-native-svg": "14.1.0",
    "react-native-vector-icons": "^10.1.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.6.4",
    "react-redux": "^9.1.2",
    "typescript": "^4.9.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.18.6",
    "@babel/plugin-proposal-optional-chaining": "^7.21.0",
    "@react-native-community/eslint-config": "2.0.0",
    "@types/i18n-js": "3.8.1",
    "@types/react": "~18.2.45",
    "@types/react-native": "0.67.6",
    "@types/react-native-calendars": "1.505.3",
    "eslint": "7.28.0",
    "expo-cli": "5.4.3",
    "jest-expo": "~50.0.4",
    "typescript": "^5.3.0"
  },
  "private": true,
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
    ]
  }
}

**Comment by michaelsturd** [comment]
error: node_modules/expo/AppEntry.js: [BABEL] /Users/user/Apps/my-app/node_modules/expo/AppEntry.js: .plugins is not a valid Plugin property

Any help ?

**Comment by BlueBigThink** [comment]
Can you share the codebase?
Currently I can say try to check babel config or babelrc only.
Or you can try to clear the cache or upgrade expo.
If you need my help, contact me telegram.
Shared on my github.
Thank you.
Brent

**Comment by joksa** [comment]
> error: node_modules/expo/AppEntry.js: [BABEL] /Users/user/Apps/my-app/node_modules/expo/AppEntry.js: .plugins is not a valid Plugin property
> 
> Any help ?

same here, what the f*** is happening?

**Comment by michaelsturd** [comment]
It's so pricky, JavaScript is not being well coordinated, is this how we
are going to be facing overnight raised errors when working with companies?

**Comment by Ajiboye7** [comment]
iOS Bundling failed 1053ms node_modules\expo-router\entry.js (1 module)
 ERROR  node_modules\expo-router\entry.js: [BABEL] C:\Users\hp\Desktop\deraasah\Courses\Web devlopment\new web\New React\NetNinja\React Native\React Native JS_Mastery\testingmobile\node_modules\expo-router\entry.js: .plugins is not a valid Plugin property   

Any help please. I have beenn facing this issue for days now

**Comment by ankitkhaire-20** [comment]
I am facing the same issue any help on these Please.. I am stuck...

**Comment by michaelsturd** [comment]
Sorry I have been busy, have you resolved it.,?
If you haven’t, let me know so we can do that.

**Comment by michaelsturd** [comment]
Chat me on WhatsApp 09150283137
