### ISSUE TITLE
Issue with Facebook Ads

### ISSUE THREAD

**Issue by donutsahoy** [expo/expo#10976]
Trying to implement Facebook Ads into my app. They are currently not displaying. 

As anyone encountered this issue before?

This is the error I am receiving: 

> error SyntheticEvent {
  "_dispatchInstances": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "_dispatchListeners": [Function onError],
  "_targetInst": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "bubbles": undefined,
  "cancelable": undefined,
  "currentTarget": ReactNativeFiberHostComponent {
    "_children": Array [],
    "_internalFiberInstanceHandleDEV": FiberNode {
      "tag": 5,
      "key": null,
      "type": "ViewManagerAdapter_CTKBannerView",
    },
    "_nativeTag": 1045,
    "viewConfig": Object {
      "Commands": Object {},
      "Constants": Object {},
      "Manager": "ViewManagerAdapter_CTKBannerView",
      "NativeProps": Object {
        "onAdError": "BOOL",
        "onAdPress": "BOOL",
      },
      "baseModuleName": "UMViewManagerAdapter",
      "bubblingEventTypes": Object {
        "topBlur": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onBlur",
            "captured": "onBlurCapture",
          },
        },
        "topChange": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onChange",
            "captured": "onChangeCapture",
          },
        },
        "topEndEditing": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onEndEditing",
            "captured": "onEndEditingCapture",
          },
        },
        "topFocus": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onFocus",
            "captured": "onFocusCapture",
          },
        },
        "topKeyPress": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onKeyPress",
            "captured": "onKeyPressCapture",
          },
        },
        "topPress": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onPress",
            "captured": "onPressCapture",
          },
        },
        "topSubmitEditing": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onSubmitEditing",
            "captured": "onSubmitEditingCapture",
          },
        },
        "topTouchCancel": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onTouchCancel",
            "captured": "onTouchCancelCapture",
          },
        },
        "topTouchEnd": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onTouchEnd",
            "captured": "onTouchEndCapture",
          },
        },
        "topTouchMove": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onTouchMove",
            "captured": "onTouchMoveCapture",
          },
        },
        "topTouchStart": Object {
          "phasedRegistrationNames": Object {
            "bubbled": "onTouchStart",
            "captured": "onTouchStartCapture",
          },
        },
      },
      "directEventTypes": Object {
        "onGestureHandlerEvent": Object {
          "registrationName": "onGestureHandlerEvent",
        },
        "onGestureHandlerStateChange": Object {
          "registrationName": "onGestureHandlerStateChange",
        },
        "topAccessibilityAction": Object {
          "registrationName": "onAccessibilityAction",
        },
        "topAccessibilityEscape": Object {
          "registrationName": "onAccessibilityEscape",
        },
        "topAccessibilityTap": Object {
          "registrationName": "onAccessibilityTap",
        },
        "topAdError": Object {
          "registrationName": "onAdError",
        },
        "topAdPress": Object {
          "registrationName": "onAdPress",
        },
        "topLayout": Object {
          "registrationName": "onLayout",
        },
        "topMagicTap": Object {
          "registrationName": "onMagicTap",
        },
      },
      "uiViewClassName": "ViewManagerAdapter_CTKBannerView",
      "validAttributes": Object {
        "accessibilityActions": true,
        "accessibilityElementsHidden": true,
        "accessibilityHint": true,
        "accessibilityIgnoresInvertColors": true,
        "accessibilityLabel": true,
        "accessibilityRole": true,
        "accessibilityState": true,
        "accessibilityValue": true,
        "accessibilityViewIsModal": true,
        "accessible": true,
        "alignContent": true,
        "alignItems": true,
        "alignSelf": true,
        "aspectRatio": true,
        "backfaceVisibility": true,
        "backgroundColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderBottomColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderBottomEndRadius": true,
        "borderBottomLeftRadius": true,
        "borderBottomRightRadius": true,
        "borderBottomStartRadius": true,
        "borderBottomWidth": true,
        "borderColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderEndColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderEndWidth": true,
        "borderLeftColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderLeftWidth": true,
        "borderRadius": true,
        "borderRightColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderRightWidth": true,
        "borderStartColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderStartWidth": true,
        "borderStyle": true,
        "borderTopColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderTopEndRadius": true,
        "borderTopLeftRadius": true,
        "borderTopRightRadius": true,
        "borderTopStartRadius": true,
        "borderTopWidth": true,
        "borderWidth": true,
        "bottom": true,
        "direction": true,
        "display": true,
        "end": true,
        "flex": true,
        "flexBasis": true,
        "flexDirection": true,
        "flexGrow": true,
        "flexShrink": true,
        "flexWrap": true,
        "height": true,
        "hitSlop": Object {
          "diff": [Function insetsDiffer],
          "process": null,
        },
        "justifyContent": true,
        "left": true,
        "margin": true,
        "marginBottom": true,
        "marginEnd": true,
        "marginHorizontal": true,
        "marginLeft": true,
        "marginRight": true,
        "marginStart": true,
        "marginTop": true,
        "marginVertical": true,
        "maxHeight": true,
        "maxWidth": true,
        "minHeight": true,
        "minWidth": true,
        "nativeID": true,
        "needsOffscreenAlphaCompositing": true,
        "onAccessibilityAction": true,
        "onAccessibilityEscape": true,
        "onAccessibilityTap": true,
        "onAdError": true,
        "onAdPress": true,
        "onLayout": true,
        "onMagicTap": true,
        "opacity": true,
        "overflow": true,
        "padding": true,
        "paddingBottom": true,
        "paddingEnd": true,
        "paddingHorizontal": true,
        "paddingLeft": true,
        "paddingRight": true,
        "paddingStart": true,
        "paddingTop": true,
        "paddingVertical": true,
        "pointerEvents": true,
        "position": true,
        "proxiedProperties": true,
        "removeClippedSubviews": true,
        "right": true,
        "shadowColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "shadowOffset": Object {
          "diff": [Function sizesDiffer],
          "process": null,
        },
        "shadowOpacity": true,
        "shadowRadius": true,
        "shouldRasterizeIOS": true,
        "start": true,
        "style": Object {
          "alignContent": true,
          "alignItems": true,
          "alignSelf": true,
          "aspectRatio": true,
          "backfaceVisibility": true,
          "backgroundColor": Object {
            "process": [Function processColor],
          },
          "borderBottomColor": Object {
            "process": [Function processColor],
          },
          "borderBottomEndRadius": true,
          "borderBottomLeftRadius": true,
          "borderBottomRightRadius": true,
          "borderBottomStartRadius": true,
          "borderBottomWidth": true,
          "borderColor": Object {
            "process": [Function processColor],
          },
          "borderEndColor": Object {
            "process": [Function processColor],
          },
          "borderEndWidth": true,
          "borderLeftColor": Object {
            "process": [Function processColor],
          },
          "borderLeftWidth": true,
          "borderRadius": true,
          "borderRightColor": Object {
            "process": [Function processColor],
          },
          "borderRightWidth": true,
          "borderStartColor": Object {
            "process": [Function processColor],
          },
          "borderStartWidth": true,
          "borderStyle": true,
          "borderTopColor": Object {
            "process": [Function processColor],
          },
          "borderTopEndRadius": true,
          "borderTopLeftRadius": true,
          "borderTopRightRadius": true,
          "borderTopStartRadius": true,
          "borderTopWidth": true,
          "borderWidth": true,
          "bottom": true,
          "color": Object {
            "process": [Function processColor],
          },
          "decomposedMatrix": true,
          "direction": true,
          "display": true,
          "elevation": true,
          "end": true,
          "flex": true,
          "flexBasis": true,
          "flexDirection": true,
          "flexGrow": true,
          "flexShrink": true,
          "flexWrap": tru...(truncated to the first 10000 characters)

**Comment by AdamJNavarro** [comment]
Hey @donutsahoy, there's a lot of information missing from your issue such as environment info, platform info, versions, etc. Please follow our issue template and provide the information we ask for as well as a reproducible example we can run on our end to test.

Cheers,
Adam

**Comment by donutsahoy** [comment]
@AdamJNavarro Sorry I missed that, where is the info posted for the template? Looked for it and couldn't find it.

**Comment by cruzach** [comment]
@donutsahoy - https://github.com/expo/expo/issues/new?labels=Issue+needs+review&template=bug_report.md
