### ISSUE TITLE
expo-updates reloadAsync method is not applying updates from latest download (iOS)

### ISSUE THREAD

**Issue by fuller** [expo/expo#10975]
### Summary of Issue 
Expo Updates [`reloadAsync`](https://docs.expo.io/versions/latest/sdk/updates/#updatesreloadasync
) method does not reload the application on iOS even if file is successfully downloaded

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.0 - /Users/afuller/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 27.0.2, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.2
        System Images: android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-Q | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare
```
### Reproducible Demo
Initialized the following with `expo init --template=expo-template-bare-minimum`

https://github.com/fuller/ota-repro

Bulk of changes from base project is https://github.com/fuller/ota-repro/commit/bb40417c62d42035ec76e57759fef41575a885c4

 
### Steps to Reproduce

Application is setup to look at http://localhost:8000/dist/ios-index.json for the update manifest

Can be validated by:
1. Running on iOS (defaulted to release scheme)
2. Making small change to App.js and exporting with `npm run export`
3. Starting a local server with `npm run serve`

### Expected Behavior vs Actual Behavior
The file does get downloaded and will eventually update after force closing and opening the app a few times, but it does not update when merely fetching and reloading in the manual steps.

Expectation is that manually reloading with `reloadAsync` would re-initialize with latest downloaded file.

**Comment by manjuy124** [comment]
Same problem with us. It's taking couple force restarts to reflect latest JS bundle.
Any news?

**Comment by esamelson** [comment]
Hey @fuller -- apologies for the delayed response here, and thanks for providing the repro. However, I've tried cloning the repo and following your instructions, and the update works just fine for me every time.

Is it possible that in the instances the update wasn't working for you, you had actually built the binary *after* running `npm run export`? In this case, the creation date of the exported update would actually be earlier than the one embedded in the app binary (since that's generated on demand when you run a build) and so expo-updates would choose to ignore the served update since it already has a newer one.

**Comment by awinograd** [comment]
I'm seeing the same behavior on expo-updates 0.4.2 on Android. 

I didn't run the provided repro, but our code base essentially does the same thing. Performing a reloadAsync after awaiting fetchUpdateAsync reloads the app, but doesn't reload with the newest JS bundle until a subsequent force quit.

I also observe that after reloadAsync, the manifest appears to be updated, but the actual JS bundle logic / code is not

**Comment by esamelson** [comment]
Hey @awinograd - do you have a way to reliably repro this, or does it just happen intermittently?

**Comment by awinograd** [comment]
@esamelson I can consistently reproduce it in our app. I haven't yet attempted to create a minimal reproduction, however.

**Comment by esamelson** [comment]
Please definitely let me know if you are able to!

**Comment by awinograd** [comment]
@esamelson digging into this a little more, I think the issue here is I run hermes on Android. I know that technically expo-updates is not compatible with hermes yet, so perhaps a `wontfix`

**Comment by esamelson** [comment]
Ah, gotcha. Yes, at the time of writing this hermes is not supported by expo-updates. That may change in the future (we hope and intend so!) but for now you'll need to find a different solution or debug this on your own if you're using hermes.
