### ISSUE TITLE
SQLite - thrown exception in success callback makes the database unusable

### ISSUE THREAD

**Issue by rystraum** [expo/expo#1098]
Any thrown exception in callbacks will 'lock' up the database and make it unusable.

Simplest case to replicate:
```
import { SQLite } from 'expo';
const db = SQLite.openDatabase('database.db', 1);
db.transaction( tx => {
    tx.executeSql(`some valid sql here`, [], (tx, results) => { throw 'error'; });
});
```

then remove the throw error and try to load the db again and it will refuse to load.

Background:

I have the following class:

```
export const db = SQLite.openDatabase('database.db', 1);

class WorkoutSessionModel {
    create(attributes, callback = () => {}) {
        const {
            startTimestamp,
            endTimestamp,
            routine,
            routineSet,
            exercises,
        } = attributes;

        db.transaction(tx => {
            tx.executeSql(
                `insert into workoutSessions (
                    startTimestamp,
                    endTimestamp,
                    routine,
                    routineSet,
                    exercises
                ) values (?, ?, ?, ?, ?);`,
                [ startTimestamp, endTimestamp, routine, routineSet, exercises ],
                (tx, results) => {
                    callback(results.insertId);
                },
                (tx, error) => {
                    console.log("error", tx, error);
                }
            );
        });
    }
}
```

which allows me to do this in redux actions:
```
export function newWorkoutSession(payload) {
    return (dispatch) => {
        WorkoutSessionModel.create(payload, (createdID) => {
            console.log('payload', payload);
            console.log('created', createdID);
            dispatch({
                type: NEW_WORKOUT_SESSION, 
                payload: Object.assign({}, payload, { id: createdID })
            });
        });
    }
}
```

where I can dispatch redux actions from. I refactored my reducers and accidentally introduced a bug during refactoring which raised a TypeError exception which locked up my database. I was still in dev so the workaround for me was just change the DB name while I was fixing the error. I suspect restarting my phone would allow me to open up the DB again, but that would be a bad workaround in a prod app.

**Comment by AdamJNavarro** [comment]
Hey @rystraum,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam

**Comment by rystraum** [comment]
Hi @AdamJNavarro,

No worries. Thanks for taking the time in cleaning up the issues in this project.
