### ISSUE TITLE
expo-sqlite SQLResultSet type update required

### ISSUE THREAD

**Issue by cheng500** [expo/expo#10998]
### Summary of Issue 
TypeScript error for SQLResultSetRowList. `_array` does not exist on type even though it exists and is documented [here](https://docs.expo.io/versions/latest/sdk/sqlite/).
![image](https://user-images.githubusercontent.com/29183323/98939376-a3dbc100-24e9-11eb-9cec-5a4f1c7f2711.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.28.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.9.0 - ~/.nvm/versions/node/v14.9.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /Users/chengkuan/.rvm/rubies/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 28, 29
        Build Tools: 26.0.2, 28.0.3
        System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.3
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.0
    Expo Workflow: bare
```

### Expected Behavior vs Actual Behavior
`SQLResultSetRowList` should include `_array: Array<any>`

**Comment by slpixe** [comment]
Strangely when going through React-Native on a device, the `SQLResultSetRowList` does return:
- _array
- length

However going via react-native-web (browser), then the typing matches whereby there is only the `length` & `item(index)`

But as far as react-native is concerned, it looks like that property is available, however underscore is typically a private/local value not intended for end use ?
