### ISSUE TITLE
[ImagePicker] TypeError: Cannot read property 'launchImageLibraryAsync' of undefined

### ISSUE THREAD

**Issue by NickDelBen** [expo/expo#11007]
### Summary of Issue 

In the browser when calling any method from ImagePicker (example `ImagePicker.launchImageLibraryAsync`) an error is thrown

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Targeting web
react-native: 0.63.3
expo-image-picker: 9.1.0

### Reproducible Demo

```jsx
import React from 'react';
import { TouchableOpacity, View, Text } from 'react-native';
import * as ImagePicker from 'expo-image-picker';

const PhotoPickerSettings = {
  mediaTypes: ImagePicker.MediaTypeOptions.All,
  allowsEditing: true,
  quality: 1,
  base64: true
};

export const WizardPhotoStep = () => {

  const handleUseSavedPhotoPressed = async () => {
    let result = await ImagePicker.launchImageLibraryAsync(PhotoPickerSettings);
    if (!result.cancelled) changePhoto(result);
  }

  return (
    <View style={{ alignItems: 'center', justifyContent: 'center' }}>
      <TouchableOpacity onPress={handleUseSavedPhotoPressed}>
        <Text>From Saved Photos</Text>
      </TouchableOpacity>
    </View>
  );  
};
```
 
### Steps to Reproduce

Simply load this componant and try to press the button

### Expected Behavior vs Actual Behavior

Should open select image dialog on browser instead throws error:
`TypeError: Cannot read property 'launchImageLibraryAsync' of undefined`

**Comment by waleedbhatti** [comment]
Any update regarding this issue? Facing same :(

**Comment by Sai-Smaran** [comment]
Try reinstalling the package, see if it helped?

**Comment by evanstern** [comment]
I'm using a bare install of expo and had this issue as well. I was able to fix it by running `cd ios && pod install` and then rebuilding the app in xcode. The `pod install` command resulted in installing `EXImagePicker`, so that is probably what is the culprit.

The documentation doesn't specify that you need to `pod install` but it does make sense.

**Comment by SeryojaTolsty** [comment]
> Эта проблема была закрыта, поскольку она неактивна в течение 7 дней с момента ее пометки как устаревшая. Пожалуйста, откройте новую проблему, если вы считаете, что столкнулись с похожей проблемой.

пидорас блять! нахуй комменты почистил?!
