### ISSUE TITLE
[expo-notifications] Device identifier used by expo-notifications is scoped per experience

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo#11008]
## 🐛 Bug Report

While testing https://github.com/expo/expo/pull/11005 I have found a bug — `InstallationIdProvider` exposed to JS, used to get/create `deviceId`, was not being subclassed in `expoview` and while at first it looked like it would grab the same UUID that:
- `Constants.installationId` exposed to JS, used in `expo-firebase-analytics`, `home`
- `ExponentFcmIntentService` used when automatically updating device push token on Expo servers in standalone apps
- old `Notifications` API uses when fetching an Expo push token

used thanks to the same `SharedPreferences` name and key, it actually created a UUID of its own (the module received a `ScopedContext` which automatically scopes `SharedPreferences` and while it looked like it would operate on `host.exp.exponent.SharedPreferences`, it actually used `@username/id-host.exp.exponent.SharedPreferences`.

On one hand this creates a dichotomy in installation identifiers used throughout the codebase, on the other hand it actually may make it easier for us to deprecate and eventually remove the "common" installation ID.

The one problem it raises is the fact that apps for projects that were initially built as standalone apps and then were ejected will rotate their `installationId` on this change (since in bare the `InstallationIdProvider` will no longer receive a `ScopedContext`, it will start to use the "common" installation ID) and as a result of this — Expo push token.

Essentially this boils down to whether we'd accept Expo push token change:
- as a result of upgrading (`InstallationIdProvider` could start using "common" installation ID in SDK 40)
- as a result of ejecting to bare workflow (once ejected, `InstallationIdProvider` receives unscoped `Context` and uses a different UUID than the one that it used previously).

I'm curious to hear your opinion, @ide, I thought postponing the issue to "ejecting" may look like less inconvenience for all parties (why anyone would expect tokens to change after upgrading) and "ejecting" is also a more "serious" process (during which token rotation may even look like something expected). On the other hand subclassing `InstallationIdProvider` and rotating the tokens on this upgrade fixes the issue completely and immediately (also fixing device push token being outdated in standalone apps without need to implement autoreregistration).

### Environment

This happens on Android.
 
### Steps to Reproduce

I've inspected `shared_prefs` stored in the data directory of a sample standalone app on an Android emulator and noticed two `uuid` values:
1. `/data/user/0/com.sjchmiela.myapp/shared_prefs/%40sjchmiela%2Fmy-app-host.exp.exponent.SharedPreferences.xml`
2. `/data/user/0/com.sjchmiela.myapp/shared_prefs/host.exp.exponent.SharedPreferences.xml`

Another way to see this is to run the app

<details><summary>Code</summary>

```tsx
import { StatusBar } from "expo-status-bar";
import Constants from "expo-constants";
import InstallationIdProvider from "expo-notifications/build/InstallationIdProvider";
import React from "react";
import { StyleSheet, Text, View } from "react-native";

export default function App() {
  const [notificationsId, setNotificationsId] = React.useState<
    string | undefined
  >(undefined);
  React.useEffect(() => {
    try {
      InstallationIdProvider.getInstallationIdAsync!().then(setNotificationsId);
    } catch (e) {
      alert(e);
    }
  }, []);

  return (
    <View style={styles.container}>
      <Text>Constants.installationId</Text>
      <Text>{Constants.installationId}</Text>
      <Text>expo-notifications.installationId</Text>
      <Text>{notificationsId}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

</details>

for apps of two different `experienceId`s:

<img width="796" alt="Zrzut ekranu 2020-11-12 o 22 16 23" src="https://user-images.githubusercontent.com/1151041/98997370-b4655900-2534-11eb-9cdb-b808c6cdb1c1.png">

### Expected Behavior vs Actual Behavior (or is it?)

I imagine one could expect `InstallationIdProvider` to always return the same identifier as `Constants.installationId`.

Currently it returns the same identifier only on apps in bare workflow.

**Comment by sjchmiela** [comment]
**Update:** on iOS a similar thing happens, but there:
- for unversioned code the `InstallationIdProvider`'s `installationId` is the same as `Constants.installationId`
- for every versioned SDK the `InstallationIdProvider`'s `installationId`  is different, but the same across different experiences.

**Comment by ide** [comment]
* The device ID for push notifications does not have to be equal to `Constants.installationId`. They can be two separate values.
* Until we remove `Constants.installationId` in SDK 43, let's keep the value of `Constants.installationId` stable across SDK versions and ejecting.
* For push notifications, changing the device ID will change the Expo push token as well. This breaks our API contract, so if we do this, we need to document it.
* Ideally, we would not change the device ID at all. But if I understand this issue correctly, the device ID currently changes when a developer ejects from Expo to bare React Native, and there isn't a good way to address this except to make Expo use an unscoped Context in the first place and match bare RN.
* Doing a one-time reset of the push token when ejecting seems much better to me than resetting the push token when upgrading an SDK version.
* Could we have code like: `if (!hasExistingDeviceID) { useUnscopedContext() } else { return existingDeviceID }`? This way, newly installed managed apps will use the unscoped context and match bare RN, and existing apps won't change their device ID at all.
* In December 2021 we could change this code to use only the unscoped context. This would affect managed apps that upgrade their SDK version, but only installations over one year old.
