### ISSUE TITLE
expo-notifications: unable to resolve getExpoPushTokenAsync 

### ISSUE THREAD

**Issue by yarapolana** [expo/expo#11000]
## 🐛 Bug Report
When calling getExpoPushTokenAsync() it never gets resolved, I don't receive an error and the code just stalls.
After trying again to reset credentials again I get this error, it didn't happen the first time and it only happens with this command `expo credentials:manager -p ios` setting credentials with android works.
The issue is similar to another already reported but the difference is the solution stated there is applicable when handling push notifications service yourself as opposed to having expo push notifications service already working on other expo managed and bare projects.

```
  code: 'INTERNAL_SERVER_ERROR',
  details: undefined,
  serverStack: undefined,
  metadata: undefined,
  _isApiError: true
```

### Summary of Issue 
Trying to use expo-notifications in a react-native project, after setting up everything I need and all credentials when calling getExpoPushTokenAsync it never resolves. I tried in an expo managed and an expo bare project both work, but not the react-native one.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.28.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.12.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 25, 28, 29
        Build Tools: 28.0.3, 29.0.1, 29.0.2
        System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/yarapolana/react-native-patched => 0.63.2 
    Expo Workflow: bare

Targeting and testing on iOS & Android devices

### Reproducible Demo
since snacks come with expo the issue would not be present

### Steps to Reproduce

create a project with `npx react-native init AwesomeTSProject --template react-native-template-typescript`
install and configure react-native-unimodules & expo-notifications
configure FCM and APNS to use expo push notification service

and use this snippet
```js
import DeviceInfo from 'react-native-device-info'
import * as Notifications from 'expo-notifications'
import * as Permissions from 'expo-permissions'

import Client from '@yay/services/client'
import { Alert } from 'react-native'

let finalStatus

export const registerForPushNotificationsAsync = async (): Promise<any> => {
  const isEmulator = await DeviceInfo.isEmulator()
  const experienceId = '@username/projectname'

  if (isEmulator) {
    console.log('[📢 LOG] No notifications in simulators')
    return
  }
  const { status: existingSatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS)

  finalStatus = existingSatus

  if (existingSatus !== 'granted') {
    const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS)
    console.info('Permission not granted')
    finalStatus = status
  }

  if (finalStatus !== 'granted') {
    Alert.alert('Failed to get push token for push notification')
    return false
  }
// 
  const token = await Notifications.getExpoPushTokenAsync({ experienceId })
  console.log('token', token) // this never gets called

  const { data: devicePushToken } = await Notifications.getExpoPushTokenAsync()

  try {
    if (devicePushToken) {
      console.log('Device Token Exists', devicePushToken)
      await Client.post('/PushToken', { PushToken: devicePushToken })
    }
  } catch (e) {
    if (e.status === 409) {
      // Token already exists. Fine.
    } else {
      console.error(e)
    }
  }
}
```

### Expected Behavior vs Actual Behavior

Retrieve token from getExpoPushTokenAsync in iOS and Android.

Token never comes from the call for either one.

**Comment by quinlanj** [comment]
hey @yarapolana , thanks for reporting the issue. To clarify, if `getExpoPushTokenAsync()` never resolves, which command is returning the `code: 'INTERNAL_SERVER_ERROR'`?

**Comment by yarapolana** [comment]
@quinlanj expo credentials:manager -p ios

**Comment by cruzach** [comment]
@yarapolana have you provided the push notification entitlement in Xcode? To do that, open your ios project in Xcode, go to the Signing and Capabilities tab, click `+ capability`, and select push notifications

**Comment by yarapolana** [comment]
@cruzach Yes I have :)

**Comment by yarapolana** [comment]
Should I share a rn project to replace the reproduceable demo?

**Comment by quinlanj** [comment]
`getExpoPushTokenAsync({ experienceId })` should be independent of any credentials you configure. It's only when you request a push token be sent (`await Client.post('/PushToken', { PushToken: devicePushToken })`), that we try to use your push key.

**Comment by yarapolana** [comment]
@quinlanj 😅 Regardless it never resolves so Client.post or any code after getExpoPushTokenAsync never gets called. This works on managed and bare, the issue is with react native.

**Comment by sjchmiela** [comment]
Are you sure you've configured `react-native-unimodules` correctly? What I imagine could make things worse is *not* integrating `UMAppDelegateWrapper` into the setup.

Apart from that make sure you read [a documentation section on long push token resolves](https://docs.expo.io/versions/latest/sdk/notifications/#fetching-a-push-token-takes-a-long)! 🙂

**Comment by quinlanj** [comment]
hey @yarapolana - i looked up your credentials, and it looks correctly configured for your main bundle identifier. in addition to what has been suggested by sjchmiela, could you ensure the following is configured:
- In Apple Developer portal -> Identifiers, navigate to your app id and make sure that the 'push notifications' option is selected
![Screen Shot 2020-11-16 at 1 18 09 PM](https://user-images.githubusercontent.com/6380927/99309762-ca159f80-280e-11eb-8eaf-a8dc9c3f85e4.png)

![Screen Shot 2020-11-16 at 1 18 26 PM](https://user-images.githubusercontent.com/6380927/99309721-bb2eed00-280e-11eb-8003-89816ca8088d.png)

- `app.json` contains the correct bundleIdentifier and slug

**Comment by yarapolana** [comment]
@sjchmiela yes :) I am using other expo  libraries in this project. Indeed in my very first project this was the case, but not on this one :) thank you though.

**Comment by yarapolana** [comment]
@quinlanj Yes to both =) otherwise the bare version wouldn't work.

**Comment by timdelange** [comment]
I have the same problem on android. getExpoPushTokenAsync is not resolving.

**Comment by yarapolana** [comment]
I ended up migrating my code to an expo bare workflow project since I couldn't get it to work in a regular rn project.

**Comment by hardcodet** [comment]
Bit late to the discussion but: First thing to do is trying it out on a different device. My old testing iPhone yielded very mixed results when it came to getting token, while other iPhones didn't have an issue with the same build. Publishing new builds to Testflight did help in some cases, currently it's working just fine.

**Comment by cruzach** [comment]
> I ended up migrating my code to an expo bare workflow project since I couldn't get it to work in a regular rn project.

looks like this might be something with misconfigured unimodules? If you're having this problem in a vanilla RN app, make sure to follow [this guide](https://docs.expo.io/bare/installing-unimodules/)

**Comment by yarapolana** [comment]
> > I ended up migrating my code to an expo bare workflow project since I couldn't get it to work in a regular rn project.
> 
> 
> 
> looks like this might be something with misconfigured unimodules? If you're having this problem in a vanilla RN app, make sure to follow [this guide](https://docs.expo.io/bare/installing-unimodules/)

If I am not mistaken you still have access to the our repo, but with billion things on your list you probably couldn't find time to check. I am afraid this is not the case though, while testing on bare I went to check what I could be missing but couldn't find nothing so far.

The bare has come a very long way so it was easy migration.

Thank you for the time and the team for the care! ✌🏽
