### ISSUE TITLE
Android facebook: logInWithReadPermissionsAsync keeps loading

### ISSUE THREAD

**Issue by wyvasi** [expo/expo#1101]
Hello,
https://imgur.com/1fouDEB
I tested on my Android 7.0
First login works, after that I can't login again as it keeps loading. After some time and if I remove all apps from expo app and restart project it may work again for one time.
There is no error .
Also I tried 'native','web','browser' as behaviour.
I can only test on android.
Is there anything I can do?
Thanks!

logInWithReadPermissionsAsync keeps loading

"dependencies": {
    "expo": "^23.0.0",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz"
  },
node v7.10.0
npm 4.6.1

**Comment by jimmylee** [comment]
To clarify, is this just specific to Android? Are you having this issue on iOS? Is there anyway you could share some of your code in a format so I can try to test it myself?

Look forward to helping. 😎

**Comment by jimmylee** [comment]
I had an expert on the team direct me to this: https://snack.expo.io/@bacon/facebook-login-+-graph-api

I imagine this might help out in some way! Regardless, look forward to hearing back from you.

**Comment by wyvasi** [comment]
![screenshot_20171213-072110](https://user-images.githubusercontent.com/4634020/33922858-50d74ae8-dfd6-11e7-81dd-bb383cf78707.png)
The project didn't work so I just copy the code and run it(Tried to scan but got an error).
I can't test on IOS, I test on my Android 7.0

I logged in but when I try second time to log in it just spins forever, I couldn't find anything in the Expo.facebook documentation, maybe is there a limit that I don't know about on facebook login apis?

**Comment by wyvasi** [comment]
I opened an issue on react-native after I traced the source code. Is very strange as I can't find anyone else experiencing this issue

**Comment by ArsenyYankovsky** [comment]
This affects both iOS and Android for me. Only reproducible on standalone build with expo, not in development mode.

**Comment by anp** [comment]
@wyvasi it's pretty hard for us to debug this without having a reproducible example we can try. Unfortunately I don't see any action for us to take on this right now, so I'll give it a close. If you post back with a snack or other example we can try I'll reopen. Thanks!
