### ISSUE TITLE
Expo-notifications incorrect typescript definition for showAnnouncement (is showAnnouncment)

### ISSUE THREAD

**Issue by swittk** [expo/expo#11013]
### Summary of Issue 
In setNotificationCategoryAsync() function options, there is a field specifying if the notification should be announced over headphones. It is specified incorrectly as "allowAnnouncment", and this misspelling is also replicated in the expo-notifications documentation.

The code on the iOS bridge side seems to be spelled correctly as "allowAnnouncement".

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Typescript React Native Expo.

### Reproducible Demo

    Notifications.setNotificationCategoryAsync(
      NOTIFICATION_CATEGORY_EXAMPLE,
      [{
        identifier: "myIdentifier",
        buttonTitle: 'Hello',
        textInput: {
          submitButtonTitle: 'Done',
          placeholder: 'Enter the time in format XX:XX'
        }
      },
      {
        identifier: "myIdentifier2",
        buttonTitle: 'Goodbye'
      }], {
      showTitle: true,
      // allowAnnouncment: true // <<< This here is the typo. Typescript would complain if it was changed to the correct "allowAnnouncement"
    }); 
### Steps to Reproduce
As above

### Expected Behavior vs Actual Behavior
Typescript complains with the correct value of "allowAnnouncement", tries to correct to "allowAnnouncment".

**Comment by cruzach** [comment]
thanks for pointing this out, I'll fix this 👍
