### ISSUE TITLE
printAsync doesn't work on iPhone 5

### ISSUE THREAD

**Issue by FabianOMB** [expo/expo#11016]
### Summary of Issue 
When using Print.printAsync from expo-print package it will only render a blank page on iPhone 6. It works on all other platforms I have tested.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
iPhone 5
iOS: 10.3.4
Client version (Expo): 2.17.4.109949
SDK: 39

### Reproducible Demo
https://snack.expo.io/@evidensa/printasync-not-working-on-iphone-6

### Steps to Reproduce
Run this snack on an iPhone 5. Klick on the "Print this" link. A blank page is printed.  

### Expected Behavior vs Actual Behavior
A page with the word "Hello" should be printed. This works on all newer iPhones and Android phones that I have tested.

**Comment by AdamJNavarro** [comment]
Hey @FabianOMB, when you say iPhone 6 do you mean explicitly an iPhone 6? I just tested on my iPhone 6+ that's running iOS version 12.4.8 and I'm getting the "Hello" on the page.

Cheers,
Adam

**Comment by FabianOMB** [comment]
Sorry. The phone is an iPhone with Model number A1429. I realize now that this is an iPhone 5! Updated title to reflect this. As I said it works correctly with my other phones.

**Comment by cruzach** [comment]
I tested this on the iPhone 5s simulator on iOS 12.4 an it's printing the `Hello` (using SDK 40 and `expo-print@~9.2.0`
