### ISSUE TITLE
expo-contacts: Error when fetching notes

### ISSUE THREAD

**Issue by itadventurer** [expo/expo#11017]
## 🐛 Bug Report

I am currently unable to get the note of a contact.
If I just do `Contacts.getContactByIdAsync(id)` – I get no note field back.
If I try to explicitly fetch the note field I get the following exception:

```
[Unhandled promise rejection: Error: Error while fetching contacts | Description: Unauthorized Keys, Reason: This application has not been granted permission to access some of the requested keys., Options: (null), Suggestion: (null)]
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B5044c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
      react-native-web: ~0.13.7 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare
```

Trying it out in the expo app. 

### Reproducible Demo

https://snack.expo.io/@azapps/expo-contacts-notes-exception

Works on Android. Does not work on iOS

### Steps to Reproduce

Just open the app, allow it accessing your contacts and have a look at the log output.

### Expected Behavior vs Actual Behavior

This should not throw exceptions on iOS and just show the note.

**Comment by cruzach** [comment]
hey @itadventurer , this is a limitation on iOS- you need to request the proper entitlements from apple in order to access notes- https://docs.expo.io/versions/latest/config/app/#accessescontactnotes

We added this to our Contacts docs, but it seems to have been removed at some point so we'll add that back in

**Comment by itadventurer** [comment]
Thank you!
