### ISSUE TITLE
AuthSession not retrieving AccessToken

### ISSUE THREAD

**Issue by darryl1975** [expo/expo#11015]
Hi,

I m having the issue where AuthSession could use to retrieve an accessToken.

I tried the following code to login to Azure AD and am successfuly to login to Azure.

let client_Id = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx';
let client_Secret = 'yyyyyyyyyyyy_yyyyyyy-yyy-yyyyyyyyy';
let scopesList: string[] = ['openid', 'profile', 'email', 'offline_access'];

let authorization_Endpoint = 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/oauth2/authorize';
let token_Endpoint = 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/oauth2/token';

// AuthRequestConfig
let reqConfig: AuthSession.AuthRequestConfig = {
//responseType: ResponseType.Token,
clientId: client_Id,
clientSecret: client_Secret,
redirectUri: redirect_uri,
scopes: scopesList,
usePKCE: true
}

let discoveryConfig: AuthSession.DiscoveryDocument = {
authorizationEndpoint: authorization_Endpoint,
tokenEndpoint: token_Endpoint
}

let authRequestConfig: AuthSession.AuthRequestConfig = {
clientId: client_Id,
clientSecret: client_Secret,
redirectUri: redirect_uri,
scopes: scopesList,
prompt: AuthSession.Prompt.Login
};

// Create and load an auth request
const [request, result, promptAsync] = AuthSession.useAuthRequest(
reqConfig,
discoveryConfig
);

However, the response doesn't provide me the email or id_token or access_token.

I tried to use the return code provided in response.params.code to retrieve a token. However, I am unsuccessful.

The following is the code I have to retrieve a token (on button clicked):

const getToken = async () => {
try {
var rslt: any = result;
console.log('App getToken (rslt): ', rslt.params.code);

  const accessToken = new AuthSession.AccessTokenRequest({
    clientId: client_Id,
    clientSecret: client_Secret,
    code: rslt.params.code,
    redirectUri: redirect_uri,
    scopes: scopesList,
  });

  console.log(accessToken);

  const responseToken = await AuthSession.exchangeCodeAsync(accessToken, { tokenEndpoint: discovery.tokenEndpoint });
  console.log(JSON.stringify(responseToken, null, 4))
} catch (err) {
  console.log(err);
  console.log(JSON.stringify(err, null, 4))
};
};

The error I encountered:

App retrieveToken (error): [Error: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
More info: AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE.
Trace ID: 256b595a-2503-4d44-83e4-1ac91add3400
Correlation ID: e74b0bd0-52ef-4f65-923b-2c0afee976e1
Timestamp: 2020-10-29 03:38:28Z]
Unrecognized event: {"type":"client_log","level":"log","data":["App retrieveToken (error): ","[Error: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\nMore info: AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE.\r\nTrace ID: 256b595a-2503-4d44-83e4-1ac91add3400\r\nCorrelation ID: e74b0bd0-52ef-4f65-923b-2c0afee976e1\r\nTimestamp: 2020-10-29 03:38:28Z]"]}

Please advice what I can do.

Thank you.

**Comment by AdamJNavarro** [comment]
Hey @darryl1975, we try to reserve github issues for actionable and reproducable bug reports. For implementation questions like this one, please feel welcome to create a [forum post](forums.expo.io) and we can explore this further.

Cheers,
Adam
