### ISSUE TITLE
expo-image-picker camera can take photo at first time but for second time it crashed immediately in iOS. Android works.

### ISSUE THREAD

**Issue by Kennethhung** [expo/expo#11014]
"expo-image-picker": "~9.1.0"
"expo": "^39.0.0"
"expo-permissions": "~9.3.0"

When I am testing my app in iphone 11 (ios 14.2), 
I found that I can take photo at the first time and display the image after ask permissions for the camera.
However , when I click to open camera at the second time, the camera only appears around one second and then close.
In Android, the app works fine without any problems.

My code for take picture is as below.
![image](https://user-images.githubusercontent.com/36217281/99046687-13c37780-25ce-11eb-8a22-98aebda1cf9b.png)

**Comment by AdamJNavarro** [comment]
Hey @Kennethhung, I just created this [Snack](https://snack.expo.io/@adamjnav/ecb4da) and it seems to work as expected for me. (I'm able to take multiple consecutive pictures with the camera without a crash). I'm also running iOS 14.2 on an iPhone 11.

Could you please share a reproducible example of this crash so we can test it on our end? Pictures of code are better than no code but the best code is runnable code 😄 

Cheers,
Adam

**Comment by Kennethhung** [comment]
@AdamJNavarro Hi, thank you for your kind attention.
My code is as below.  The below url is the video that the bug is.
https://drive.google.com/file/d/15mAUtucft67PiKYHnGALpkxPIdU8jslV/view?usp=sharing



    useEffect(()=> {
        
        setFileList(navigation.state.params.photo)
    },[navigation.state.params.photo])

    useEffect(()=> {
        console.log(fileList)
        if (fileList.length == maxImage){
            setDisable(true)
        } else {
            setDisable(false)
        }
    },[fileList])

    
    function PresentSelector({input, layerLevel=0,placeHolder='Location'}){
        const nestedPicker = input.map(nest => {
            return <SelectItem key={nest.id} title={nest.name} />
        })
        const subNestedPicker = input.map(nest => {
            if ( nest.children.length > 0 && hasSelected[layerLevel] && nest.name == targetSite[layerLevel]){
                const newLayerLevel = layerLevel+1
                const placeHolder = 'Section'
                return <PresentSelector key={nest.id} input={nest.children} layerLevel={newLayerLevel} placeHolder={placeHolder}/>
            } 
        })
        return (
            <View>
                <Text style={[{opacity:opacityPlaceholder[layerLevel]},styles.placeholder]}>{placeHolder}</Text>
                <Layout level={layerLevel} style={styles.layout}>
                    <Select
                        onSelect={index => onPressHandler(index,layerLevel, input)}
                        value={targetSite[layerLevel]} 
                        placeholder={placeHolder}
                        styles={{fontFamily:'robot-medium'}}
                    >   
                        {nestedPicker} 
                    </Select>
                </Layout>
                {subNestedPicker}
            </View>
        )
    }

    const onPressHandler = (index,layerLevel, input) => {
        const newHasSelected = [...hasSelected]
        const newTargetSite = [...targetSite]
        const newPlaceHolder = [...opacityPlaceholder]
        setTargetPrefix(input[index.row].id)
        if (newHasSelected.slice(layerLevel+1,maxImage).includes(true)){
            const reNewHasSelected = new Array(layer+1).fill(false)
            const reNewTargetSite = new Array(layer+1).fill('')
            const reNewPlaceHolder = new Array(layer+1).fill(0)
            for(let i = 0; i < layerLevel+1; i++){
                reNewHasSelected[i] = true
                reNewTargetSite[i] = input[index.row].name
                reNewPlaceHolder[i] = 1
            }
            setHasSelected(reNewHasSelected)
            setTargetSite(reNewTargetSite)
            setOpacityPlaceholder(reNewPlaceHolder)
        }   else{
            newHasSelected[layerLevel] = true
            setHasSelected(newHasSelected)
            newTargetSite[layerLevel] = input[index.row].name
            setTargetSite(newTargetSite)
            newPlaceHolder[layerLevel] = 1
            setOpacityPlaceholder(newPlaceHolder)
        }
    }

    const renderItem = ({ item, index}) => {
        const pressHandler = (index) => { 
            var array = [...fileList]
            setSelectedImage(index)
            setIsVisible(true)
        }    
        
        return(
            <View >
                <TouchableOpacity style={[styles.deleteBtn,{right:'10%'}]} onPress={() => deleteImage(index)} >
                    <MaterialIcons style={{padding:5}} name="close" size={24} color="white" />
                </TouchableOpacity>
                <TouchableOpacity style={{flex:1/2,aspectRatio:1}} onPress={() => pressHandler(index)} >
                    <Image style={styles.image} resizeMode='cover' source={{isStatic:true,uri:item.uri}} key={index} />
                </TouchableOpacity>
                
            </View>
        )
    }
  

    const takePicture = async () => {
        setModalOpen(false)
        setSubModalOpen(false)
        setIsVisible(false)
        const {status: camera} = await Permissions.askAsync(Permissions.CAMERA);
        if (camera === 'granted'){
            let result = await ImagePicker.launchCameraAsync({
                mediaTypes: ImagePicker.MediaTypeOptions.All,
                allowsEditing: false,
                aspect: [4, 3],
                quality: 1,
            })
            if (!result.cancelled) {
                
                if (Platform.OS === 'android'){
                    const uri =  "file:///" + result.uri.split("file:/").join("");
                    setFileList([...fileList, { 
                        uri,
                        remark:'',
                        image:{name:uri.split("/").pop(),type:mime.getType(uri),uri:uri}
                    }])
                }else if (Platform.OS === 'ios'){
                    setFileList([...fileList, { 
                        uri:result.uri,
                        remark:'',
                        image:{name:result.uri.split("/").pop(),type:'image/jpeg',uri:result.uri}
                    
                    }])

                }
                
    
            }

        }
    }

    const convertUriToBlob = async (fileList,data) => {
        const filePress = await Promise.all(
            fileList.map(async image => {
                console.log(image.remark)
                
                data.append('remark',image.remark)
                data.append('attachment',image.image)
                console.log(data)
                })
           
        ) 
        return  data
    }

    const handleSubmit = async () => {
        setUploading(true)
        if (targetPrefix === ''){
            console.log('missing location')
            Alert.alert('Error','Please select the corresponding location')
            setUploading(false)
        } else if (fileList.length === 0){
            console.log('missing image')
            Alert.alert('Error','Please upload at least one image(maximun 4 images)')
            setUploading(false)
        } else{
            const data = new FormData()
            
            data.append('location',targetPrefix)
            const sendData = await convertUriToBlob(fileList,data)

            const authToken = "Token "+userData.token
            console.log(authToken)
            const result = await axios.post(constants.apiHost, sendData, {
                headers: {
                    Accept: 'application/json',
                    'content-type': 'multipart/form-data',
                    Authorization: authToken
                }
                }).then(res => {
                        setUploading(false)
                        console.log("image uploaded")
                        navigation.goBack()
                        setUploadStatus(true)
                    })
                    .catch(err => {
                        setUploading(false)
                        // setUploadStatus()
                        alert(err)
                        alert(fileList[0].uri)})
        }
        

    }


    const deleteImage = (index) => {
        var array = [...fileList] 
        const fileLength = array.length
        array.splice(index, 1)
        setFileList(array)
    }

    const addImageFromLibrary = () => {
        setModalOpen(false)
        setSubModalOpen(false)
        setIsVisible(false)
        const imageCount = fileList.length
        // console.log(imageCount)
        navigation.navigate('ImageScreen',{photo:fileList,max:maxImage-imageCount})
    }
    
    const footerComponent = () => {
        return(
            <View  style={styles.modal} >
                <View style={globalStyles.container}>
                    <TouchableOpacity style={{flex:0.75}} activeOpacity={1} onPress={()=>setSubModalOpen(false)} >
                    </TouchableOpacity>
                    <View style={{flex:0.25,
                                width:'100%',
                                backgroundColor:'#262626',
                                paddingHorizontal:20*constants.widthRatio}}>
                        <TouchableOpacity style={styles.imageLibBtn} onPress={()=>addImageFromLibrary()}>
                            <MaterialIcons name="insert-photo" size={30} color="white" />
                            <Text style={styles.imageBtnDes}>Upload from Album</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={{flexDirection:'row'}} onPress={()=>Platform.OS ==='android'?takePicture():goToCameraScreen()}>
                            <MaterialIcons name="camera-alt" size={30} color="white" />
                            <Text style={styles.imageBtnDes}>Camera</Text>
                        </TouchableOpacity>
                    </View>
                
                </View>
            </View>
        )
    }

    const goToCameraScreen = () => {
        setModalOpen(false)
        setSubModalOpen(false)
        setIsVisible(false)
        navigation.navigate('CameraScreen',{photo:fileList})
    
    }
                                                                                              
    const headerComponent = () => {
        // console.log(typeof(footerRef))
        const HIT_SLOP = { top: 16, left: 16, bottom: 16, right: 16 };
        const closeModal = () => {
            setIsVisible(false)
        }
        return(
            <SafeAreaView style={{flexDirection:'row'}}>
                <TouchableOpacity style={styles.closeButton} onPress={closeModal} hitSlop={HIT_SLOP}>
                    <MaterialIcons name="arrow-back" size={24} color="white" />
                </TouchableOpacity>
                
            </SafeAreaView>
        )
    }
    

    return (
        
        <View style={[globalStyles.container,styles.container]}>
            <View style={styles.formContainer}>
                <PresentSelector input={site}/>
                <Text style={styles.uploadDes}>Upload Images(max. {maxImage} images)</Text>
                <FlatList
                    style={styles.flatList}
                    numColumns={2} 
                    data={fileList}
                    renderItem={renderItem}
                    extraData={navigation.state.params.photo}
                    keyExtractor={(item, index) => index.toString()}
                />
                <TouchableOpacity  onPress={()=>{!disable && setModalOpen(true)}} style={[styles.submitButton,{width:'40%',marginBottom:20}]}>
                    <Text style={styles.btnDes} >CHOOSE</Text>
                </TouchableOpacity>
            </View>
            <View style={styles.subContainer}>
                <Text style={styles.reminder}>
                    Please be noted that the images cannot be deleted after uploaded to the system
                </Text>
                <TouchableOpacity onPress={()=>handleSubmit()} style={styles.submitButton}>
                    <Text style={styles.btnDes}>
                        UPLOAD
                    </Text>
                </TouchableOpacity>
            </View>
            <Modal transparent={true} visible={modalOpen} style={{zIndex:999}}>
                <View  style={styles.modal} >
                    <View style={globalStyles.container}>
                        <TouchableOpacity style={{flex:0.75}} activeOpacity={1} onPress={()=>setModalOpen(false)} >
                        </TouchableOpacity>
                        <View style={{flex:0.25,
                                    width:'100%',
                                    backgroundColor:'#262626',
                                    paddingHorizontal:20*constants.widthRatio}}>
                            <TouchableOpacity style={styles.imageLibBtn} onPress={()=>addImageFromLibrary()}>
                                <MaterialIcons name="insert-photo" size={30} color="white" />
                                <Text style={styles.imageBtnDes}>Upload from Album</Text>
                            </TouchableOpacity>
                            <TouchableOpacity style={{flexDirection:'row'}} onPress={()=>Platform.OS ==='android'?takePicture():goToCameraScreen()}>
                                <MaterialIcons name="camera-alt" size={30} color="white" />
                                <Text style={styles.imageBtnDes}>Camera</Text>
                            </TouchableOpacity>
                        </View>
                       
                    </View>
                </View>
                
            </Modal>
            
            <ImageView
                images={fileList}
                imageIndex={selectedImage}
                visible={isVisible}
                subModalOpen={subModalOpen}
                setSubModalOpen={setSubModalOpen}
                onRequestClose={() => setIsVisible(false)}
                HeaderComponent={headerComponent}
                responseData={setFileList}
                FooterComponent={footerComponent}
                />
           
            <Modal transparent={true} visible={uploading}>
                <View style={{flex:1,justifyContent:'center'}}  >
                    <View style={{backgroundColor:'#FFFFFF',flex:0.1,flexDirection:'row',justifyContent:'center',marginHorizontal:'10%',borderRadius:20}}>
                        <Text style={{fontFamily:'roboto-medium',alignSelf:'center',fontSize:20,color:'#679BCD'}}>Uploading</Text>
                        <ActivityIndicator size="large" color="#679BCD"/>
                    </View>
                    
                </View>
            </Modal>
        </View>
    )
}

const styles = StyleSheet.create({
    image:{
        width: 200*constants.widthRatio,
        height: 150*constants.HeightRatio,
        marginBottom: 20*constants.HeightRatio,
        borderRadius:5,
        flex:0.5,
        aspectRatio:1
    },
    modalImage:{
        width: 100*constants.widthRatio,
        height: 50*constants.HeightRatio,
        marginBottom: 20*constants.HeightRatio,
        borderRadius:5,
        flex:0.5,
        aspectRatio:1,
        marginHorizontal:5*constants.widthRatio,
        borderColor:'#679BCD',
        
    },
    modalFlatList:{
        alignSelf: 'center',
        borderRadius: 10,
    },
    formContainer:{
        flex:0.8,
        backgroundColor:'#FFFFFF',
        paddingHorizontal:20*constants.widthRatio, 
        marginHorizontal:20*constants.widthRatio,
        marginVertical:10*constants.HeightRatio,
        borderRadius:5,
        shadowColor:'#7C7C7C', 
        shadowOffset:{width:1,height:1},
        shadowOpacity:1,
        elevation:2,
        shadowRadius:2
    },
    submitButton:{
        backgroundColor:'#679BCD',
        paddingVertical:10*constants.HeightRatio,
        borderRadius:5,
        shadowColor:'#7C7C7C', 
        shadowOffset:{width:1,height:1},
        shadowOpacity:1,
        elevation:3,
        shadowRadius:5,
        marginTop:20*constants.HeightRatio,
    },
    subContainer:{
        flex:0.2,
        marginHorizontal:20*constants.widthRatio,
        marginVertical:20  *constants.HeightRatio 
    },
    bgImage:{
        width:'100%',
        height:'100%'
    },
    placeholder:{
        color:'#7C7C7C',
        zIndex:10,
        position:'relative',
        top:17*constants.HeightRatio,
        left:10*constants.widthRatio,
        fontSize:12,
        backgroundColor:'#FFFFFF',
        width:'18%',
    },
    layout:{
        borderRadius:5,
        marginTop:10*constants.HeightRatio
    },
    uploadDes:{
        color:'#7C7C7C',
        fontSize:12,
        fontFamily:'roboto',
        marginVertical:5*constants.HeightRatio
    },
    btnDes:{
        color:'#FFFFFF',
        textAlign:'center',
        fontFamily:'roboto-medium'
    },
    reminder:{
        fontSize:12,
        fontFamily:'roboto',
        color:'#666666'
    },
    modal:{
        flex:1, 
        justifyContent:'flex-end',
        backgroundColor:'rgba(0,0,0,0.3)'
    },
    deleteBtn:{
        shadowRadius:1,
        shadowOffset:{width:0,height:3},
        shadowOpacity:0.5,
        shadowRadius:3,
        zIndex:5,
        position:'absolute',
        elevation:20
    },
    modalView:{
        width:'100%',
        height:'25%',
        backgroundColor:'#262626',
        paddingHorizontal:20*constants.widthRatio
    },
    imageLibBtn:{
        flexDirection:'row',
        marginVertical:20*constants.HeightRatio
    },
    imageBtnDes:{
        color:'#FFFFFF',
        fontFamily:'roboto-medium',
        fontSize:14,
        marginLeft:30*constants.widthRatio,
        paddingVertical:6*constants.HeightRatio
    },
    imagePreView:{
        width:'100%',
        position:'relative',
        paddingVertical:5,
        shadowColor:'#7C7C7C',
        shadowRadius:5,
        shadowOffset:{width:1,height:1},
        shadowOpacity:0.5,
        backgroundColor: 'rgba(52, 52, 52, 0.5)',
        paddingHorizontal:20,
        

    },
    closeIcon:{
        marginTop:50*constants.HeightRatio,
        marginLeft:25*constants.widthRatio
    },
    remark:{ 
        height: 50*constants.HeightRatio,
        borderRadius:5,
        padding:10,
        fontFamily:'roboto' 
    },
    imageFlatView:{
        flexDirection:'row', 
        marginTop:20*constants.HeightRatio
    },
    addIcon:{
        paddingVertical:10*constants.HeightRatio,
        marginRight:20*constants.widthRatio,
       
    },
    doneBtn:{
        color:'#FFFFFF',
        textAlign:'center',
        fontFamily:'roboto-medium'
    },
    closeButton: {
        marginLeft:'5%',
        marginRight: '60%',
        marginTop: 8,
        width: 45,
        height: 45,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 22.5,
        backgroundColor: "#00000077",
    },
    closeText: {
        lineHeight: 25,
        fontSize: 25,
        paddingTop: 2,
        textAlign: "center",
        color: "#FFF",
        includeFontPadding: false,
    },
})

**Comment by supriyomondal1** [comment]
having the same issue here . 
did you manage to fix it @Kennethhung  ?

**Comment by yang-li-tes** [comment]
I fixed this issue by close modal after image picking.

**Comment by ibrust** [comment]
I have the same bug. 
Not surprisingly there was no investigation done and the ticket was just closed prematurely.
