### ISSUE TITLE
After Building the Apk from Expo,the apk didn't worked properly

### ISSUE THREAD

**Issue by NagabhushanAdiga** [expo/expo#11022]
i already generated APK from expo using ****expo build:android**** ,after generating the apk from expo and i installed it on my device ,then the Apk installed and when i opened it then it didn't worked properly...

**Comment by cruzach** [comment]
Here's a guide on debugging production errors- https://docs.expo.io/workflow/debugging/#production-errors, that will hopefully help you investigate what the root issue is. If you find a bug with the Expo SDK, then please open a bug report with all the information we ask for
