### ISSUE TITLE
Expo SDK 38: .png image not showing on testflight app (working fine in dev)

### ISSUE THREAD

**Issue by sahiljaidka224** [expo/expo#11037]
## 🐛 Bug Report
.png images are not showing inside test-flight app(Works fine in dev mode)

Platform: ios

### Reproducible Demo

Expo SDK version: 38

app.json includes `"assetBundlePatterns": ["**/*"]`

Styled components are used to display the image

```
const NameWrapper = styled.Image`
  height: 52px;
  width: 68px;
  margin-top: 5px;
`;

<NameWrapper source={require("../../../assets/WelcomeScreenLogo.png")} />

<WelcomeImage source={require("../../../assets/WelcomeScreen.png")}
  resizeMode="contain"
/>
```
None of these images is showing in test flight however working fine in dev mode.
 
### Steps to Reproduce

Create expo-app using SDK 38
Add images using styled components
Build and check your app on test-flight

### Expected Behavior vs Actual Behavior
Expected:  Images should show
Actual: Images not showing

**Comment by pouriaa** [comment]
Upgrading to SDK 39 worked for me

```
expo upgrade
```

**Comment by kevindavis** [comment]
I'm also experiencing this. In my app I load images two different ways, both aren't working. 

1. local assets
`import closeIcon from '../assets/close.png';`
`<Image source={closeIcon} style={localStyles.closeIcon} />`

2. remote assets (served from imfast.io)
`<Image source={{uri: call.call_type.icon}} />`

My environment:
- Expo 38
- CLI 3.28.2
- using release channels 

Happy to answer any other questions

**Comment by ajonikas** [comment]
Bumping this. None of our static or remote images are rendering in prod...

**Comment by brentvatne** [comment]
hi there. we rolled out xcode 12 on our build servers recently and this has caused the issue that you're observing on ios. we are in the process of rolling back to xcode 11, and then we will investigate the root cause and upgrade to xcode 12 again.

**Comment by brentvatne** [comment]
@ajonikas - it will require running a new build once we have rolled back to xcode 11 (or if you upgrade to sdk 39). sorry for the hassle.

**Comment by ajonikas** [comment]
kk I think we will do the upgrade to 39, build it, ship it in the meantime

**Comment by cruzach** [comment]
@ajonikas we just pushed out a fix to our builders, so if you’re still on SDK 38, you can rebuild with `expo build:ios`

**Comment by brentvatne** [comment]
sorry for the hassle, this should be resolved now! we'll look into why images aren't loading on sdk <= 38 when built with xcode 12.1 and roll out xcode 12.1 again when we have fixed that.

**Comment by zzswang** [comment]
Is it working now?

Still has same problem with latest expo.

**Comment by mitkodkn** [comment]
Still having the issue on SDK 45.

**Comment by lawnguyendev** [comment]
Same here. SDK 45.
