### ISSUE TITLE
Upgrade AsyncStorage

### ISSUE THREAD

**Issue by Immortalin** [expo/expo#11035]
ref #4117

The old package has been deprecated, including on npm.

https://react-native-async-storage.github.io/async-storage/docs/install/

https://www.npmjs.com/package/@react-native-community/async-storage

**Comment by brentvatne** [comment]
go ahead and run `expo install @react-native-community/async-storage` - it will work

**Comment by brentvatne** [comment]
updated the docs instructions here: https://github.com/expo/expo/commit/0d3af70e66ef5e4a63defd13d288fd1d7071fa79
