### ISSUE TITLE
Expo Camera zoom animated value

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#11032]
I have implemented a pinch-to-zoom camera using your package. Currently I am doing something like this:

```
const [zoom, setZoom] = useState(0);

...

const handlePinch = (nativeEvent) => {
    const { scale, velocity } = nativeEvent;

    let newZoom =
      velocity > 0
        ? zoom + scale * velocity * (Platform.OS === "ios" ? 0.01 : 25)
        : zoom -
          scale * Math.abs(velocity) * (Platform.OS === "ios" ? 0.02 : 50);

    if (newZoom < 0) newZoom = 0;
    else if (newZoom > 0.5) newZoom = 0.5;

    setZoom(newZoom);
  };

const onGestureEvent = ({ nativeEvent }) => {
    if (nativeEvent.state === State.ACTIVE) {
      handlePinch(nativeEvent);
    }
};

...

<ExpoCamera
    ref={cam}
    type={cameraType}
    ratio={cameraRatio}
    zoom={zoom}
    flashMode={flashMode}
    onCameraReady={handleCameraReady}
    style={styles.container}
>
    <PinchGestureHandler onGestureEvent={onGestureEvent}>
        <View style={styles.GUIContainer}>

            ...

        </View>
    </PinchGestureHandler>
</ExpoCamera>
```

but this will cause multiple re-renders... as zoom is stateful and not an animated value. Any ideas how to solve this performance issue? I have tried with

`const [zoom, setZoom] = useState(new Animated.Value(0));`

but expo camera seems to not accept animated values.

Also, I have tried to memoize the camera child but, for some reasons, as this will suppose to move the pinch handler to the top level, above the camera, on android it will show a black screen when performing other animations like navigating or displaying a modal.

**Comment by AdamJNavarro** [comment]
Hey @VictorioMolina, we try our best to reserve github issues for actionable and reproducible bug reports. For inquiries like this one, please feel welcome to create a [forum post](https://forums.expo.io/) to explore implementation experiments with others.

But as you have stated, the `zoom` property only accepts a `float` value so your implementation won't work with a Managed project. If you need to ship with pinch to zoom and passing animated values, you'd want to switch to a Bare project where you can manipulate the native code for the module.

Cheers,
Adam

**Comment by siddharth-kt** [comment]
@VictorioMolina did you got any solution ?
