### ISSUE TITLE
[web] background tasks - how do i use web worker? 

### ISSUE THREAD

**Issue by hunght** [expo/expo#11036]
I have tried to search all over the place but don't get the answer yet. so the issue is I want to run tasks in the background. but I can't find how to do it in expo web config.

**Comment by hunght** [comment]
here the same questions:
https://stackoverflow.com/questions/64437169/put-js-files-in-react-native-web-assets
https://forums.expo.io/t/multithreading/10829

**Comment by AdamJNavarro** [comment]
Hey @hunght, we try to reserve github issues for actionable and reproducible bug reports. For implementation questions like this one, please feel welcome to create a [forum post](forums.expo.io) and we can explore this further.

Cheers,
Adam
