### ISSUE TITLE
How can I get expo to connect to Android emulator with a non-localhost ip address?

### ISSUE THREAD

**Issue by richardwu** [expo/expo#11030]
I have an Android Emulator running on Windows on port 5554.

I am running expo inside WSL2. I have verified that I can access my Android Emulator on WIndows since if I type in:
```
# 172.22.80.1 is the IP to Windows from WSL2
telnet 127.22.80.1 5554    
```
it shows me the same "Android Console: Authentication required" prompt as if I did it in my Windows PowerShell.

However, when I click on "Run on Android device/emulator" from the Metro Bundler web page, it throws me:
```
Couldn't start project on Android: could not connect to TCP port 5554: Connection refused
```
It seems like it's trying to access the emulator via `localhost:5554`, but I would like it to connect to `$SPECIFIED_IP:5554`.

Is there an env var where I can change this? FWIW I am using a Managed Expo project.

**Comment by byCedric** [comment]
Hi @richardwu, in Expo we only use the CLI tooling to start emulators or tell them to open the Expo app. This means that WSL2 should have `adb` and `emulator` CLI tools installed and you should connect the emulator/adb to that remote device. I've used WSL2 with an actual device by connecting it to ADB over wifi. I guess you should be able to use something similar to connect it to an emulator. [This guide](https://medium.com/@radpangolin/android-development-adb-debugging-on-a-remote-emulator-92c5980f65fd) might help you in doing just that.

Hope this helps!

**Comment by reteps** [comment]
@richardwu Was this ever solved? I am having the same exact issue. Only thing I am not doing is port forwarding.

**Comment by richardwu** [comment]
I did not end up spending time figuring it out: instead I just went directly to real devices using the Expo app and LAN mode.

FYI to get your Expo app to connect properly to the Expo backend in WSL, I had to set the `REACT_NATIVE_PACKAGER_HOSTNAME` to my private IP of my Windows machine, e.g.:
```
REACT_NATIVE_PACKAGER_HOSTNAME='10.0.0.41' yarn start -- --web
```
(and of course forwarding ports 19000-19002 on my router).
