### ISSUE TITLE
sessionPreset value for Camera component on iOS

### ISSUE THREAD

**Issue by irtemed88** [expo/expo#1103]
I’m working with the Camera component right now and am having an issue where the resolution of the image captured by the front-facing camera on an iPhone 6S when calling `takePictureAsync` is smaller than if I were to take the same photo using the native camera app (roughly 700x800 versus 1900x2500). Here is the call I’m making:
```
this.camera.takePictureAsync({ base64: true }).then(({ uri, width, height, exif, base64 })...
```

Based on what I've found in EXCameraManager.m (https://github.com/expo/expo/blob/07a62367b7f68e8b1dd5a62bf64546fd393b8967/ios/Exponent/Versioned/Modules/Api/Components/Camera/EXCameraManager.m), it looks like AVCaptureSession.sessionPreset is being left to its default value on iOS which is 'high.' There is another preset value of 'photo' which I think provides a higher resolution than the default (https://developer.apple.com/documentation/avfoundation/avcapturesession.preset/1390112-photo).

Is there currently a way to get the higher camera resolution using the Camera component? If not, would it be possible to add support for configuring this preset value or changing the default to the photo quality preset? If the latter, I imagine the change would be relatively straightforward and I'd be happy to issue a PR (though not sure how to go about testing it).

**Comment by aalices** [comment]
Thanks for reporting! Shame that I missed it ;) It's not actually about the preset `High` is the default one but thanks for diving into this. Fix on its way
