### ISSUE TITLE
takePictureAsync call never resolves

### ISSUE THREAD

**Issue by capelski** [expo/expo#11039]
### Summary of Issue
Calling the takePictureAsync method inside an event handler never resolves when setting the state of the React function component (through the useState hook) in the same event handler.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.27.10 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~39.0.2 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

The issue happens on **Android** devices. The same code sample works well on the web. I haven't tested it on iOS

### Reproducible Demo

Snack: https://snack.expo.io/@capelski/8d8ea6
Git repository: https://github.com/capelski/expo-camera-stucked
 
### Steps to Reproduce

Run the app on an Android device, grant permissions to use the camera and click on **Take picture**.

### Expected Behavior vs Actual Behavior

Expected behaviour: The takePictureAsync method resolves and returns the captured image
Actual behaviour: The takePictureAsync method resolves never resolves

### Notes

I believe this issue is related to the these other two: https://github.com/expo/expo/issues/2288, https://github.com/expo/expo/issues/10403

There is an strange workaround to this issue. takePictureAsync resolves correctly when removing the ternary operator inside the `<Camera>` element. That is replacing

```jsx
<Camera
    // ...
>
    <View style={styles.container}>
        {isLoading ? (
            <Text style={styles.text}>Working on it...</Text>
        ) : (
            <TouchableOpacity onPress={takePicture}>
                <Text style={styles.text}>Take picture</Text>
            </TouchableOpacity>
        )}
    </View>
</Camera>
```

with 

```jsx
<Camera
    // ...
>
    <View style={styles.container}>
        {isLoading && (
            <Text style={styles.text}>Working on it...</Text>
        )}
    </View>
    <TouchableOpacity onPress={takePicture}>
        <Text style={styles.text}>Take picture</Text>
    </TouchableOpacity>
</Camera>
```

**Comment by mccraveiro** [comment]
@capelski I'm facing the same issue. However, I don't have any children components to the camera.

**Comment by capelski** [comment]
@mccraveiro Unfortunately, I have no clue about what might be going on in your case. I recommend you creating a Snack or a new project and play with the Camera component. That's how I realized about the mysterious children ternary operator issue. Hopefully, you will gain some understanding on what the issue is and how you can work around it until a fix is released by the expo team.

**Comment by mccraveiro** [comment]
@capelski We played around and it seems that the camera is never focusing and the picture is never taken. Disabling autoFocus works but then the picture is awful :/
