### ISSUE TITLE
TouchableOpacity activeOpacity has no effect on Android

### ISSUE THREAD

**Issue by lxinghe** [expo/expo#11047]
## 🐛 Bug Report

Seems like the response to touches of TouchableOpacity component has disappeared after I upgraded the SDK to 39.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.28.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - E:\react-native\moego\node_modules\.bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^39.0.4 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
      react-navigation: ^2.4.1 => 2.18.3
    Expo Workflow: managed

Android emulator: Pixel 3a, API 29

### Reproducible Demo
import React, { useState } from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";

const App = () => {
  const [count, setCount] = useState(0);
  const onPress = () => setCount(prevCount => prevCount + 1);

  return (
    <View style={styles.container}>
      <View style={styles.countContainer}>
        <Text>Count: {count}</Text>
      </View>
      <TouchableOpacity
        style={styles.button}
        onPress={onPress}
      >
        <Text>Press Here</Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 10
  },
  button: {
    alignItems: "center",
    backgroundColor: "#DDDDDD",
    padding: 10
  },
  countContainer: {
    alignItems: "center",
    padding: 10
  }
});

export default App;

### Expected Behavior vs Actual Behavior
TouchableOpacity responds properly to touches. On press down, the opacity of the wrapped view is decreased, dimming it.

**Comment by brentvatne** [comment]
hi there, if you believe this is a bug then it belongs in the react-native repository: https://github.com/facebook/react-native/issues
