### ISSUE TITLE
After watching a rewarded video, I close the video, the app does not return to the corresponding screen and goes to the expo menu.

### ISSUE THREAD

**Issue by georgeMorales** [expo/expo#11041]
I am using Admob rewarded video, everything is fine but when the video ends or does not end and I close it, the application does not return to the same screen where the video was opened but it goes to the expo menu, if I click the app does not load, it returns to the screen that should have returned with the state of app.
How can i fix this?
Expo sdk 39
"expo-ads-admob": "~8.3.0",

**Comment by martynasNarijauskas** [comment]
Same issue

**Comment by KristianMijares** [comment]
Same issue too when the rewardedVideoDidClose event fire the app just close and return to expo menu.

**Comment by martynasNarijauskas** [comment]
@KristianMijares for me, completely killing application and cold booting emulator temporary solves the problem
