### ISSUE TITLE
[expo-ads-admob][android][bug][Admob] AdMob sends multiple fill request for banner ads - leads to violation

### ISSUE THREAD

**Issue by akashbudhia** [expo/expo#11046]
### Summary of Issue 
On Android(only) expo admob package sends multiple fill request every time the component is rendered. This reduces the impression/show rate and wastes the available fill inventory. Most often **google also flags this as an invalid traffic violation** and applies limit on the account.

### Reproducible Demo
I have created a snack to reproduce the issue: [click to view the snack](https://snack.expo.io/@akashbudhia/admob-android-multiple-fill-request-bug)
Run the snack on an Android device to reproduce the issue. Even when the component is rendered only once, it would send at-least 2 fill request and sometime even more. 

![Logs Screenshot](https://i.ibb.co/FY3QwXr/admob-expo-android-logs.png)

**Check the console logs for detailed log** of the render vs ad fill.

 
### Steps to Reproduce
Happens for bare-min banner ad on Android device. See the snack link above.

### Expected Behavior vs Actual Behavior
Expected- for a single render, only one fill request should be sent.
Actual- multiple fill requests are sent and received successfully. This has also been verified by looking at the show rate on AdMob dashboard (~50% for Android, ~95% for iOS running same source code).

**Comment by pskryuchkov** [comment]
I confirm that problem. Any update? It seems my account was suspended because of that.

**Comment by mikejsdev** [comment]
I am having this same problem. My account has now been suspended.

For each render three Admob requests are made

Until this is fixed is there an alternative I can use? Or does anyone have any workarounds?

**Comment by ahmadeyamin** [comment]
I have the same problem please help :(

**Comment by akashbudhia** [comment]
Bump @cruzach
