### ISSUE TITLE
Expo-notifications cannot be collapsed and null channelId on Android?

### ISSUE THREAD

**Issue by adhicl** [expo/expo#11042]
### Summary of Issue 
Android notifications from expo never collapsed. I also checked the notifications returned from addNotificationReceivedListener and the channelId is always null
```
Object {
  "content": Object {
    "autoDismiss": true,
    "badge": null,
    "body": "Another device has logged in to your account.",
    "data": Object {
      "action": "signout",
    },
    "sound": "default",
    "sticky": false,
    "subtitle": null,
    "title": "User logged in",
  },
  "identifier": "0:1605529554731302%0ac519e6f9fd7ecd",
  "trigger": Object {
    "channelId": null,
    "remoteMessage": Object {
      "collapseKey": null,
      "data": Object {
        "body": "{\"action\":\"signout\"}",
        "experienceId": "@adhicl/garuda-chat",
        "message": "Another device has logged in to your account.",
        "title": "User logged in",
      },
      "from": "367315174693",
      "messageId": "0:1605529554731302%0ac519e6f9fd7ecd",
      "messageType": null,
      "notification": null,
      "originalPriority": 2,
      "priority": 2,
      "sentTime": 1605529554727,
      "to": null,
      "ttl": 2419200,
    },
    "type": "push",
  },
}
```
### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.28.5 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.22.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    npmPackages:
      expo: ^39.0.0 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
      react-navigation: ^4.4.3 => 4.4.3
    Expo Workflow: managed
```
Target: android 

### Steps to Reproduce
Hi need help, I have already added "collapse" to app.json notification
```
"notification": {
      "icon": "./assets/icons/Icon-Garuda-Chat-Notification.png",
      "androidMode": "collapse",
      "androidCollapsedTitle": "#{unread_notifications} new messages"
    }
```
I updated my project from previous expo notifications to expo-notifications, then I test using expo push notification tools and put "messages" to channelId.
![Screenshot_20201116-194255](https://user-images.githubusercontent.com/2452628/99253886-14654380-2844-11eb-987d-624a8ac869fe.png)
But notifications is not collapsed and the channel id is always null

### Expected Behavior vs Actual Behavior
notifications is collapsed into one

**Comment by sjchmiela** [comment]
Hm:
1. Are you sure the device you're testing this on supports notification channels?
2. …and notification collapsing?
3. For some reason it looks like `channelId` information isn't sent in the notification payload, notice there's nothing about `channelId` in the `trigger.data`. If the notification was to be sent to `messages` channel it would need to have this property. (See [code](https://github.com/expo/expo/blob/379bd05b9310f63bbc273180ac0b2240cf341a7c/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/model/triggers/FirebaseNotificationTrigger.java#L55-L58) to see how it's extracted from the trigger.) Have you tried sending the notification not with the [Push Notification tool](https://expo.io/notifications) but using code?

**Comment by adhicl** [comment]
Hi, @sjchmiela . For number 1 and 2 yes it supports them. Before I upgraded the project, using old version the notification is collapsing. And I have tried using code, using exponent-server-sdk-php  from my server, both has channelId but when I logged it, it always return trigger null.

**Comment by adhicl** [comment]
I also just tried create a fresh new project to test it with same result. no channelId and cannot collapse. Here are the snap of the codes: app.js (I change to js to make it the same as mine)
`import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import * as Permissions from 'expo-permissions';
import React, { useState, useEffect, useRef } from 'react';
import { Text, View, Button, Platform } from 'react-native';

Notifications.setNotificationHandler({
	handleNotification: async () => ({
		shouldShowAlert: true,
		shouldPlaySound: false,
		shouldSetBadge: false,
	}),
});

export default function App() {
	const [expoPushToken, setExpoPushToken] = useState('');
	const [notification, setNotification] = useState(false);
	const notificationListener = useRef();
	const responseListener = useRef();

	useEffect(() => {
		registerForPushNotificationsAsync().then(token => setExpoPushToken(token));

		// This listener is fired whenever a notification is received while the app is foregrounded
		notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
			console.log("notification listener");
			console.log(notification);
			setNotification(notification);
		});

		// This listener is fired whenever a user taps on or interacts with a notification (works when app is foregrounded, backgrounded, or killed)
		responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
			console.log("reponse listener");
			console.log(response);
		});

		return () => {
			Notifications.removeNotificationSubscription(notificationListener);
			Notifications.removeNotificationSubscription(responseListener);
		};
	}, []);

	return (
		<View
			style={{
				flex: 1,
				alignItems: 'center',
				justifyContent: 'space-around',
			}}>
			<Text>Your expo push token: {expoPushToken}</Text>
			<View style={{ alignItems: 'center', justifyContent: 'center' }}>
				<Text>Title: {notification && notification.request.content.title} </Text>
				<Text>Body: {notification && notification.request.content.body}</Text>
				<Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
			</View>
			<Button
				title="Press to Send Notification"
				onPress={async () => {
					await sendPushNotification(expoPushToken);
				}}
			/>
			<Button
				title="Press to Clear Notification"
				onPress={async () => {
					Notifications.dismissAllNotificationsAsync();
				}}
			/>
		</View>
	);
}

// Can use this function below, OR use Expo's Push Notification Tool-> https://expo.io/notifications
async function sendPushNotification(expoPushToken) {
	const message = {
		to: expoPushToken,
		sound: 'default',
		title: 'Original Title',
		body: 'And here is the body!',
		channelId: "message_test",
		data: { data: 'goes here' },
	};

	await fetch('https://exp.host/--/api/v2/push/send', {
		method: 'POST',
		headers: {
			Accept: 'application/json',
			'Accept-encoding': 'gzip, deflate',
			'Content-Type': 'application/json',
		},
		body: JSON.stringify(message),
	});
}

async function registerForPushNotificationsAsync() {
	console.log("registerForPushNotificationsAsync");
	let token;
	//if (Constants.isDevice) {
		const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
	let finalStatus = existingStatus;
	console.log("registerForPushNotificationsAsync:"+finalStatus);
		if (existingStatus !== 'granted') {
			const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
			finalStatus = status;
		}
		if (finalStatus !== 'granted') {
			alert('Failed to get push token for push notification!');
			return;
		}
		token = (await Notifications.getExpoPushTokenAsync()).data;
		console.log(token);
	//} else {
	//	alert('Must use physical device for Push Notifications');
	//}

	if (Platform.OS === 'android') {
		Notifications.setNotificationChannelAsync('message_test', {
			name: 'message_test',
			importance: Notifications.AndroidImportance.MAX,
			vibrationPattern: [0, 250, 250, 250],
			lightColor: '#FF231F7C',
		});
	}

	return token;
}`


app.json
`{
	"expo": {
		"name": "test_push",
		"slug": "test_push",
		"version": "1.0.0",
		"orientation": "portrait",
		"icon": "./assets/icon.png",
		"splash": {
			"image": "./assets/splash.png",
			"resizeMode": "contain",
			"backgroundColor": "#ffffff"
		},
		"updates": {
			"fallbackToCacheTimeout": 0
		},
		"assetBundlePatterns": [
			"**/*"
		],
		"ios": {
			"supportsTablet": true
		},
		"android": {
			"adaptiveIcon": {
				"foregroundImage": "./assets/adaptive-icon.png",
				"backgroundColor": "#FFFFFF"
			},
			"googleServicesFile": "./google-services.json",
			"package": "com.adhi.test_push",
			"versionCode": 1,
			"useNextNotificationsApi": true
		},
		"web": {
			"favicon": "./assets/favicon.png"
		},
		"notification": {
			"androidMode": "collapse",
			"androidCollapsedTitle": "#{unread_notifications} new messages"
		}
	}
}
`

**Comment by adhicl** [comment]
I also tried with new project and same result, no channelId and no collapse.
I use the example in https://docs.expo.io/push-notifications/overview/ and change the channelId from "default" to "message_test".
And this is my app.json
`{
	"expo": {
		"name": "test_push",
		"slug": "test_push",
		"version": "1.0.0",
		"orientation": "portrait",
		"icon": "./assets/icon.png",
		"splash": {
			"image": "./assets/splash.png",
			"resizeMode": "contain",
			"backgroundColor": "#ffffff"
		},
		"updates": {
			"fallbackToCacheTimeout": 0
		},
		"assetBundlePatterns": [
			"**/*"
		],
		"ios": {
			"supportsTablet": true
		},
		"android": {
			"adaptiveIcon": {
				"foregroundImage": "./assets/adaptive-icon.png",
				"backgroundColor": "#FFFFFF"
			},
			"googleServicesFile": "./google-services.json",
			"package": "com.adhi.test_push",
			"versionCode": 1,
			"useNextNotificationsApi": true
		},
		"web": {
			"favicon": "./assets/favicon.png"
		},
		"notification": {
			"androidMode": "collapse",
			"androidCollapsedTitle": "#{unread_notifications} new messages"
		}
	}
}
`

**Comment by adhicl** [comment]
Hi, can anyone help? For now I want to be sure if this is a bug or am I missing some steps?

**Comment by adhicl** [comment]
Hello?

**Comment by sjchmiela** [comment]
Hey, so sorry for taking such a long time to respond.

Off the top of my head I think `expo-notifications` doesn't use the `app.json` `"notification"` field so I'm not sure if this setting will be used.

I think `expo-notifications` doesn't support collapsing notifications the way legacy notifications did, so if you really really care about it I think you may need to stick to LegacyNotifications for the time being. 😕

**Comment by adhicl** [comment]
Ok @sjchmiela thank you for your info. I just reverted it back to legacy notifications for now and it works. Thank you very much

**Comment by hyochan** [comment]
Thanks for opening up this thread. However, the `collapse` feature is really really important in the notification, especially in the chat app. Otherwise, clients will be annoyed by lots of banner threads and the app may be deleted. Hope the expo team recognizes this!

**Comment by rmacuna** [comment]
Hello everyone.
I have the same issue. We use expo-push-notifications in the chat feature, which means that users get spammed with a lot of messages. Anyone have found a workaround to solve this?
Thank you

**Comment by MaxiAringoli** [comment]
I'm waiting the same thing here...

**Comment by jrausell** [comment]
Does anyone have this working? 
I'm trying to accomplish the same but no luck with the collapse. Tested on Expo Go and Dev build.
Any help? thanks

**Comment by LVExMachina** [comment]
Me too

**Comment by phicoder** [comment]
Bump

**Comment by zguo123** [comment]
Collapsing notifications are an **essential** item that this package must have!

**Comment by phicoder** [comment]
Which one will be first: collapsible expo-notifications or GTA VI?

**Comment by AspireOne** [comment]
How the hell can the package lack this functionality and give no official statement about it 4 YEARS LATER?

**Comment by bcoghe** [comment]
Wow, came here for this.. So disappointed tbh. How difficult can this be?

**Comment by Giulio987** [comment]
Still no news? For chat applications, this feature is essential. 
I can’t understand why the Expo team isn't looking into this.

**Comment by Arjit0762** [comment]
Why is this closed?

**Comment by phicoder** [comment]
Check this out: https://rnfirebase.io/messaging/usage Cloud Messaging by Google is far more advanced and reliable than Expo Notifications. It can collapse notifications and much more.
