### ISSUE TITLE
Standardize .gitignore

### ISSUE THREAD

**Issue by lorensr** [expo/expo#11045]
When I `init` a new project, I get this file:

`.gitignore`:

```
node_modules/**/*
.expo/*
npm-debug.*
*.jks
*.p8
*.p12
*.key
*.mobileprovision
*.orig.*
web-build/

# macOS
.DS_Store
```

It contains 3 ways of ignoring directories:

```
node_modules/**/*
.expo/*
web-build/
```

I believe this would be sufficient:

```
node_modules/
.expo/
web-build/
```

**Comment by EvanBacon** [comment]
this can be updated in the templates

**Comment by cruzach** [comment]
@lorensr the files you're looking for can be found [here](https://github.com/expo/expo/tree/master/templates) (if you're feeling up to a PR 😄 )
