### ISSUE TITLE
React-native-webview SSL Issue Causes Webview Crash

### ISSUE THREAD

**Issue by valdrox** [expo/expo#11058]
React-native-webview is showing the error page when a user encounters an "non critical" ssl error. It sporadically makes the webview crash on Android, on links that work flawlessly in browsers. Unfortunately, I noticed it a while after having upgraded to SDK 39 and would rather not downgrade.
 
This issue is described here, and fixed in react-native-webiew@10.9.3. https://github.com/react-native-webview/react-native-webview/pull/1466 

I guess you will bump the version for the next SDK version, but I thought I should point it out, just in case you weren't planning on doing that, and because I don't have a workaround, other than to let the pages crash. npm i react-native-webiew@10.9.3 didn't work.

**Comment by brentvatne** [comment]
hi there! i just pulled in the latest version, it will be included in the next sdk release in december: https://github.com/expo/expo/commit/46e6b8ac0b8ba1753fbb385b455c78519275456c
