### ISSUE TITLE
Devmenu only usable 1 time per run when simulating ios

### ISSUE THREAD

**Issue by MichaelHindley** [expo/expo#11054]
### Summary of Issue 
Pressing cmd + d only works 1 time per fresh start of a simulated ios device.
Same goes for cmd + r (reload).

After that, cmd + d adopts this behaviour:
* Opens and close repeated amount of times and then stays closed
* Does not open at all

Fix is to turn off the packager and quit any simulated devices.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/Cellar/node@12/12.18.3/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/Cellar/node@12/12.18.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

-->
 
### Steps to Reproduce
install xcode (latest)
npm install -g expo
expo init debug-test-bare --npm , select blank typescript
cd debug-test-bare
npm start, press "i" (defaults to iphone 12 pro max, I have tried this on the first 6 entries in the list)
wait for app to start
press cmd + d, close menu
try to open menu again, it will either jump up and down 3 times or not open at all
press cmd + r, it will reload the app
try to press cmd + r again, it will not work

this issue does not show up when running an android emulator, where the devmenu works as expected

### Expected Behavior vs Actual Behavior
devmenu working more than 1 time when simulating an ios device

I don't know if it's related, but if I want to restart the packager, it will not find the previously simulated ios device, I have to explicitly quit the Simulator or the device turns into a literal black box.

**Comment by brentvatne** [comment]
`expo init debug-test-bare --npm , select blank typescript`

can you clarify if this is a managed or bare app?

**Comment by MichaelHindley** [comment]
Same behaviour is observed on managed and bare apps.
Resetting and erasing all contents had no effect.
Some more manual testing revealed about a ~5% success rate of getting the dev menu to show up by spamming cmd + d over and over.

**Comment by MichaelHindley** [comment]
100% success rate workaround: Drag the menu down just a few pixels from the top notch and then click focus on the application, you can then use cmd + d 1 time. Repeat for every time you want to access the devmenu.

**Comment by brentvatne** [comment]
interesting, these are totally different implementations in managed and bare apps. it does make me suspect that there is something wrong on your end, not really sure what that would be though.

**Comment by MichaelHindley** [comment]
For what it's worth, I had never run Xcode, Simulator or Expo before.  I.e this is the only state I have achieved from a clean start.

**Comment by brentvatne** [comment]
could you possibly record your screen when you're reproducing this and share the video? maybe there's some small thing that you're doing differently that exposes this issue

**Comment by MichaelHindley** [comment]
Video is in root at https://github.com/MichaelHindley/expo-debug in webm format.
The repo is what I get when choosing to init a managed bare typescript expo variant.

At some point in the video, I bring up karabiner event viewer to show the cmd + d interactions while focus is on the simulator.

**Comment by brentvatne** [comment]
when trying to reproduce this, i can get into a situation where sometimes i need to press cmd + d twice in order for the menu to appear - i believe this happens when the menu is still finishing animating. but i can always open it again. see the gif below.

![Screen Recording 2020-11-17 at 3 57 47 PM](https://user-images.githubusercontent.com/90494/99464948-256a8f00-28ee-11eb-93f1-c1dfdec6b5f7.gif)

we can investigate why it's necessary to press cmd+d twice occasionally, certainly! but i'm still puzzled as to why you're observing anything different than that

**Comment by brentvatne** [comment]
ok i think i might know what is happening here. are you holding down cmd? if you do this in the ios simulator it'll just keep repeating your previous keyboard shortcut. for example, to get in a reload loop: press cmd+r, release the r key but keep holding cmd. we can't really do anything about that, it's an ios simulator quirk

**Comment by MichaelHindley** [comment]
During the part with the keyboard event viewer, I do hold down cmd which results in the menu dancing up and down, but all the other times it's just a short press.

**Comment by brentvatne** [comment]
here's something you can do to make it more reliable - enable "Send keyboard input to device" for the simulator. this sometimes gets toggled off and you need to re-enable it. this makes sending keyboard shortcuts to the simulator work a lot better.

![Screen Shot 2020-11-18 at 10 25 32 AM](https://user-images.githubusercontent.com/90494/99571628-6616e680-2988-11eb-887a-45d5a5c7c484.png)

another thing you can do is use the shake shortcut instead, this doesn't rely on the simulator receiving the shortcut, instead it just responds to the simulated device shake event.

![Screen Shot 2020-11-18 at 10 30 12 AM](https://user-images.githubusercontent.com/90494/99572118-0c62ec00-2989-11eb-8173-9dd87de609f5.png)

**Comment by MichaelHindley** [comment]
Can confirm that enabling "Send Keyboard Input to Device" resolves the issue completely, thank you very much for the help @brentvatne !

To close out, using the Shake keybind has not successfully triggered the debug menu a single time. However, clicking the Shake button in the Device dropdown does trigger it.
