### ISSUE TITLE
EXGL: gl.pixelStorei() doesn't support this parameter yet!

### ISSUE THREAD

**Issue by Joshandrews43** [expo/expo#11063]
### Summary of Issue 

Randomly using SDK 39 (`"expo-gl: ~9.1.1", "expo-gl-cpp": "~9.1.2"`) I get the above error in my production app (non-simulator. I do not use any special configuration. I wish I had more information.

Sentry error produced: `TypeError: undefined is not an object (evaluating 't.__exglCtxId=n')`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

I have a production app on IOS & Android, however this only breaks on IOS with SDK 39. This error has never occured before SDK 39, and has occurred only on IOS for all IOS versions. Out of hundreds of people who use the app each day (and this feature), only ~1% crash. I cannot reproduce in a simulator.

```
Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    Expo Workflow: managed
```

### Reproducible Demo

I cannot reliably reproduce it, although the only code for expo pixi in my app is: 

```
<ExpoPixi.Sketch
     style={expoStyle}
     strokeColor="black"
     strokeWidth={9}
     strokeAlpha={1}
     ref={sketchRef}
     initialLines={initialLines(width, height, ratio)}
/>
```
 

### Expected Behavior vs Actual Behavior

Not crash

**Comment by badbod99** [comment]
Having this issue also on Expo client on Android device, but it's not crashing the app.

Comes from this code in Expo:

```javascript
NATIVE_METHOD(pixelStorei) {
  auto pname = ARG(0, GLenum);
  switch (pname) {
    case GL_UNPACK_FLIP_Y_WEBGL: {
      unpackFLipY = ARG(1, GLboolean);
      break;
    }
    default:
      jsConsoleLog(runtime, "EXGL: gl.pixelStorei() doesn't support this parameter yet!");
  }
  return nullptr;
}
```

I've tried to track this through to the expo-pixi project, but I can't find any code in expo-pixi that calls either this or any method linked to this, so this must be something Expo is calling internally with an invalid param.

**Comment by Joshandrews43** [comment]
> Having this issue also on Expo client on Android device, but it's not crashing the app.
> 
> Comes from this code in Expo:
> 
> ```js
> NATIVE_METHOD(pixelStorei) {
>   auto pname = ARG(0, GLenum);
>   switch (pname) {
>     case GL_UNPACK_FLIP_Y_WEBGL: {
>       unpackFLipY = ARG(1, GLboolean);
>       break;
>     }
>     default:
>       jsConsoleLog(runtime, "EXGL: gl.pixelStorei() doesn't support this parameter yet!");
>   }
>   return nullptr;
> }
> ```
> 
> I've tried to track this through to the expo-pixi project, but I can't find any code in expo-pixi that calls either this or any method linked to this, so this must be something Expo is calling internally with an invalid param.

To clarify, I can get the issue in development to console log, but it does not crash it in the simulator. Only on prod.

**Comment by badbod99** [comment]
> To clarify, I can get the issue in development to console log, but it does not crash it in the simulator. Only on prod.

Not crashing on production this end either.  Also looking at that code, shouldn't result in a crash, it just don't do the flip and logs.  There may be another reason for your crash.

**Comment by Joshandrews43** [comment]
Any update here? This is still crashing for me and I cannot reproduce it

**Comment by badbod99** [comment]
@Joshandrews43 - I suspect your crash is coming from elsewhere.  Make sure you are not ignoring any warning messages.  Yellowbox warning for example does cause a crash on iOS.

**Comment by 3GOMESz** [comment]
On expo-three as well https://github.com/expo/expo-three/issues/196

**Comment by YarooqH** [comment]
Just add these lines to your <Canvas>

`onCreated={(state) => {
      const _gl = state.gl.getContext()
      const pixelStorei = _gl.pixelStorei.bind(_gl)
      _gl.pixelStorei = function(...args) {
        const [parameter] = args
        switch(parameter) {
          case _gl.UNPACK_FLIP_Y_WEBGL:
            return pixelStorei(...args)
        }
      }
 }}`
    
After Adding your Canvas should look something like this.

`<Canvas gl={{ physicallyCorrectLights: true }} camera={{ position: [-6, 0, 16], fov: 36 }}  onCreated={(state) => {
      const _gl = state.gl.getContext()
      const pixelStorei = _gl.pixelStorei.bind(_gl)
      _gl.pixelStorei = function(...args) {
        const [parameter] = args
        switch(parameter) {
          case _gl.UNPACK_FLIP_Y_WEBGL:
            return pixelStorei(...args)
        }
      }
    }}></Canvas>`
