### ISSUE TITLE
Google Provider in `expo-auth-session` does not return authorization code

### ISSUE THREAD

**Issue by andywong418** [expo/expo#11061]
## 🐛 Bug Report
In `expo-auth-session` version `~2.0.0`, when I follow the guide in [docs about logging in with Google](https://docs.expo.io/guides/authentication/#google), I do not get the authorization code in my `authentication` object or in the params of the result (`result.params`). Looking into the source code I tried to set `responseType` to `code`, but I cannot retrieve the code without setting the clientSecret. Then when I set `shouldAuthExchangeCode` as false, nothing is returned from the library.
### Summary of Issue 
Following the docs does not give me an authorization code to login a user on the server side

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.43 => 0.12.43 
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

### Reproducible Demo
https://snack.expo.io/@andywong418/google-auth-code (Please use appropriate clientIds).

 
### Steps to Reproduce
1. Install expo-auth-session
2. Follow [guide about logging in with Google](https://docs.expo.io/guides/authentication/#google)
3. Log authorization object - you can see that no code is provided in the result or authorization object.
4. Add responseType 'code' to the object called in function `useAuthRequest`. You will then get an error on log in which states that the clientSecret is needed.
5. Add `shouldAutoExchangeCode` to object called in `useAuthRequest`. Nothing is returned when you log in via Google

### Expected Behavior vs Actual Behavior
I should receive an authorization code to be used in OpenId, but instead I do not get that from the library currently.

Thanks for the help!

**Comment by andywong418** [comment]
@AdamJNavarro Has there been any updates regarding this issue? Is the error not reproducing?

**Comment by Praharsh99** [comment]
Is this issue fixed?
Even I tried fetching just the authorization code, by setting `shouldAutoExchangeCode` to `false`. But, I still get the access token in the final result.
