### ISSUE TITLE
[expo-device] iPhone 12 is not recognized as modelName

### ISSUE THREAD

**Issue by milennaj** [expo/expo#11065]
### Summary of Issue 

iPhone 12 is not recognized as model Name, device model for iPhone 12 is just iPhone

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
    "expo": "^39.0.4",
    "expo-cli": "^3.18.0",
    "expo-device": "^2.3.0",

### Reproducible Demo
import * as Device from "expo-device";
import * as Notifications from "expo-notifications";
import axios from "axios";
import { DeviceTokenExist } from "../constants/apiConstants";
import { saveDevice } from "../api/notificationsApi";
import Constants from "expo-constants";
import { Alert } from "react-native";
import { UserDeviceStatus } from "../utils/enums/UserDeviceStatus";

export const useRegisterDevice = async (dispatch) => {
  let token = (await Notifications.getExpoPushTokenAsync()).data;
  var result = null;
  try {
    result = await axios.get(
      `${Constants.manifest.extra.apiurl}/${DeviceTokenExist}?deviceid=${token}&brand=${Device.brand}&model=${Device.modelName}`
    );
  } catch (error) {
    console.log("device id: error", error);
  }

  if (result) {
    if (result.data === UserDeviceStatus.NoToken) {
      Alert.alert(
        "Notificaties toestaan",
        "Mogen wij jou op deze telefoon notificaties toesturen?",
        [
          {
            text: "Ja",
            onPress: () => {
              saveDevice(dispatch, {
                deviceID: token,
                deviceBrand: Device.brand,
                deviceModel: Device.modelName,
              });
            },
          },
          { text: "Liever niet", onPress: () => {} },
        ],
        { cancelable: false }
      );
    }
    if (result.data === UserDeviceStatus.InvalidToken) {
      renewRegisterDevice(dispatch);
    }
  }
};

 
### Steps to Reproduce
import * as Device from "expo-device";

Just use Device.modelName for iPhone 12 and you will get iPhone for modelName instead of iPhone 12 or similar
### Expected Behavior vs Actual Behavior

Expected behavior is to get iPhone 12 recognized as a model, not generic 'iPhone"

**Comment by AdamJNavarro** [comment]
Hey @milennaj, thanks for bringing this to our attention. It looks like we haven't updated the [model names list](https://github.com/expo/expo/blob/sdk-39/packages/expo-device/src/ModelNames.ts) to accommodate the iPhone 12 models yet. We'll try and update this as soon as possible.

Cheers,
Adam

**Comment by MattGoldwater** [comment]
@AdamJNavarro The 2nd generation iPhone SE is also not recognized.

**Comment by karlazzam** [comment]
@AdamJNavarro device list still hasn't been updated with the iphone 12 line

**Comment by zeckdude** [comment]
This ticket is from November. Can you please add iPhone 12 soon?

**Comment by omid29sarei** [comment]
Do we have any updates here ?

**Comment by filipepratalima** [comment]
any updates?
