### ISSUE TITLE
Missing a step in upgrading instructions

### ISSUE THREAD

**Issue by arrygoo** [expo/expo#1107]
The first step under android needs to be copied over for ios as well: 

Right now there's only:
* Go to https://expo.io/—/api/v2/versions and find the androidExpoViewUrl key under sdkVersions.[NEW SDK VERSION].

Whereas it should say:
* Go to https://expo.io/—/api/v2/versions and find the androidExpoViewUrl and iosExpoViewUrl key under sdkVersions.[NEW SDK VERSION].

And it should be listed under both not just android.

**Comment by AdamJNavarro** [comment]
Upgrading a detached project's for iOS only requires you to change the ExpoKit tag in your podfile to the corresponding release and then running pod install.

**Comment by arrygoo** [comment]
So is there no need to include this line in app.json? 
```
      "iosExpoViewUrl":
        "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.1.4-sdk23.0.0-f67c5bc3-4a27-40f6-8686-91e8f868a145.tar.gz"
```

**Comment by AdamJNavarro** [comment]
No, that key was added to the app.json a while back when we thought we may need it stored but it isn't required. Sorry for the confusion!

**Comment by ericjames** [comment]
I don't think this is still true @AdamJNavarro my app is reporting it still uses SDK v30 even though I did all the steps in upgrading to SDK 31.
