### ISSUE TITLE
Error: Unable to resolve module `./node_modules\expo\AppEntry` from ``

### ISSUE THREAD

**Issue by Alain00** [expo/expo#11074]
I'm getting this when i try to open the project in the expo client app. I've the `expo-cli` and the expo client app updated to the lastest version

```
Error: Unable to resolve module `./node_modules\expo\AppEntry` from ``: 

None of these files exist:
  * node_modules\expo\AppEntry(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.wasm|.native.wasm|.wasm)
  * node_modules\expo\AppEntry\index(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.wasm|.native.wasm|.wasm)
```
### Environment
Expo CLI 3.28.5 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20200424.164118.0 - D:\Instaladores\watchman\windows\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 7, 8, 9
        Build Tools: 24.0.3, 25.0.3, 26.0.0, 26.0.2, 27.0.1, 27.0.2, 27.0.3, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom
        Android NDK: 16.1.4479499
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: ^16.12.0 => 16.12.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
      react-navigation: 4.1.1 => 4.1.1
    Expo Workflow: managed

**Comment by brentvatne** [comment]
please follow the full issue template. you left out a reproducible example and steps to reproduce.

**Comment by Alain00** [comment]
@brentvatne I don't know exactly how to reproduce this, I have other Expo projects that work fine with SDK 39. Tried updating this to SDK 39 but no luck, and then I tried it on ubuntu 18.04 and it worked perfectly

**Comment by brentvatne** [comment]
hard to help on this without seeing the project or a reproducible example :(

i would suggest following typical debugging practices here. maybe try initializing a new project and copying your project over piece by piece until you can reproduce it. if you are able to copy the entire project over, then diff them and see what is unique about the new vs the old project.

**Comment by brentvatne** [comment]
also see related issues:

- https://github.com/expo/expo/issues/9591
- https://github.com/expo/expo/search?q=Error%3A+Unable+to+resolve+module+%60.%2Fnode_modules%5Cexpo%5CAppEntry&type=issues
- https://github.com/expo/expo/search?q=Unable+to+resolve+module+%60.%2Fnode_modules%5Cexpo&type=issues

**Comment by minaelee** [comment]
I work with students and two of them this week reported this same issue. Fresh installs, expo-cli installed using yarn, nothing added to the starter code from expo init, both using Android emulators. Expo SDK 39. Immediately resolved by downgrading SDK to 38.

**Comment by Alain00** [comment]
> i would suggest following typical debugging practices here. maybe try initializing a new project and copying your project over piece by piece until you can reproduce it. if you are able to copy the entire project over, then diff them and see what is unique about the new vs the old project.

I've initialized a new project, then downgrading the SDK to 36, and copying the entire project over and the error went away. There are few differences between the two projects, same `app.json`, same `package.json`, using yarn in both. Maybe it was a cache problem, I don't know

@minaelee before downgrading to SDK 36 i tested the project recently installed with the SDK 39 and it worked fine

**Comment by Alain00** [comment]
Now i moved my project folder to a different directory and the exact same error happened again, then move the project folder back to the initial dir and the error went away. Any idea of what is causing this?

**Comment by brentvatne** [comment]
@Alain00 - what is the full path to your project when it does not work?

**Comment by Alain00** [comment]
@brentvatne the project works in `/user/projectFolder` but does not work in `/user/test/projectFolder`, the path where the error happends is a subpath

**Comment by brentvatne** [comment]
please give the actual full path, i want to see what characters are used in it

**Comment by brentvatne** [comment]
also what is in the `test` directory in the above scenario? aside from `projectFolder`

**Comment by Alain00** [comment]
work - C:\Users\Alain\projects\foo-clients
don't work - C:\Users\Alain\projects\foo\foo-clients

This is the real scenario, in ` C:\Users\Alain\projects\foo` are other projects in their respective folders but outside (`C:\Users\Alain\projects`) are also others projects

**Comment by brentvatne** [comment]
can you try to reproduce this in a separate directory where you can share the full contents of the directories?

so you would share `C:\Users\Alain\projects\foo2` and have your project at ``C:\Users\Alain\projects\foo2\foo-clients`

i'm not sure what is going on in the parent directory but it seems like it must be related

**Comment by Alain00** [comment]
> also - are you using yarn workspaces? or the new npm version of that? are there other projects inside of foo-clients aside from the expo one?

`foo-clients` does't have any workspaces inside

Now i renamed `C:\Users\Alain\projects\foo-clients` to `C:\Users\Alain\projects\foo2-clients` and the project don't work. The project was genereted by `expo init` in `C:\Users\Alain\projects\foo-clients`, so I think that this happends with any project initilialized in any directory when its moved or renamed. Sorry i can't comfirm that, i can't initialize another expo project right now

**Comment by brentvatne** [comment]
>  so I think that this happends with any project initilialized in any directory when its moved or renamed

it doesn't on macos or linux, so i doubt this is the case on windows. i'm fairly confident that there is some detail with your setup that is being overlooked that is leading to the problems that you're observing but i'm not sure what that would be.

**Comment by Alain00** [comment]
Yes, there is something in my setup, I reboot the PC and now the project that worked does not work 🤷‍♂️

**Comment by Alain00** [comment]
@brentvatne I cloned my project and let him with the minimal code, just an `App.tsx` and the error still shows up, here is the project https://github.com/Alain00/expo-test, could you check it please? I've others expo projects working fine

**Comment by jeremeheh** [comment]
Is there any fix on this issue? Im currently having the same problem

**Comment by brentvatne** [comment]
@Alain00 - sorry i missed your message.

then problem is that you included node_modules in your watchman ignore_dirs... watchman is used for crawling and watching the fs. you won't be able to resolve any node_modules if you do this. https://github.com/Alain00/expo-test/blob/master/.watchmanconfig#L3

delete that line and run `expo start -c`

@jeremeheh - provide a repo like @Alain00 did above and i'll let you know where your project configuration is messed up ;)

**Comment by expelledboy** [comment]
For anyone that is having issues, and need the bug resolved asap, I just kept changing the path of AppEntry and eventually it worked. Honestly thats all I did, and started using `expo start --clear`.

**Comment by Alain00** [comment]
> then problem is that you included node_modules in your watchman ignore_dirs... watchman is used for crawling and watching the fs. you won't be able to resolve any node_modules if you do this. https://github.com/Alain00/expo-test/blob/master/.watchmanconfig#L3
> 
> delete that line and run `expo start -c`

Thanks @brentvatne, it worked

**Comment by tilman** [comment]
> @Alain00 - sorry i missed your message.
> 
> then problem is that you included node_modules in your watchman ignore_dirs... watchman is used for crawling and watching the fs. you won't be able to resolve any node_modules if you do this. https://github.com/Alain00/expo-test/blob/master/.watchmanconfig#L3
> 
> delete that line and run `expo start -c`
> 
> @jeremeheh - provide a repo like @Alain00 did above and i'll let you know where your project configuration is messed up ;)

Hasn't worked for me. 

In my case the fault was `PNPM`. Changed to `NPM` and everything worked.

**Comment by EcoticketApp** [comment]
add in root of the project, a file called Index.js

`/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
`

**Comment by EcoticketApp** [comment]
add in root of the project, a file called Index.js



/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);

**Comment by TmLev** [comment]
> In my case the fault was PNPM. Changed to NPM and everything worked.

I also had problems with `pnpm`. Switch to `yarn` and it started working.

**Comment by ritmillio** [comment]
Same issue here with `pnpm` so I switched back to yarn...

**Comment by awohletz** [comment]
If you're using `pnpm`, create an `index.ts` (or JS) file in your project root with this:
```
import { registerRootComponent } from "expo";
import App from "./src/App";

registerRootComponent(App);
```
In package.json, set `"main"` to `"index.ts"`

Create a `.npmrc` file in your project root with this:
```
# Expo doesn't play nice with pnpm by default.
# The symbolic links of pnpm break the rules of Expo monorepos.
# @link https://docs.expo.dev/guides/monorepos/#common-issues
node-linker=hoisted
```
