### ISSUE TITLE
Localization with Context API in react navigation 5

### ISSUE THREAD

**Issue by butri71** [expo/expo#11073]
Hey guys,

React-native "version": "0.63.2"
SDK 39
react-navigation 5

I'm trying to implement the Context API to react navigation 5 in order to pass the locale globally across the entire App following the example shown in Expo documentation about localization: https://reactnavigation.org/docs/localization/

I get no errors in the setup and the App runs as expected until I get to a screen where I'm fetching the data. It looks like the Context wrapper is not propagating the data.

Here is my my App.js
`
import React from 'react';
import { NavigationContainer } from "@react-navigation/native";
import * as Localization from 'expo-localization';
import i18n from 'i18n-js';

import AppNavigator from './AppNavigator';
import StartupScreen from "../screens/StartupScreen";

const en = {
    hello: 'Hello',
    welcome: 'Welcome',
  };  
const es = {
    hello: 'Hola',
    welcome: 'Bienvenido',
};
i18n.fallbacks = true;
i18n.translations = { en, es };

export const LocalizationContext = React.createContext();

export default function App() {       
    const [locale, setLocale] = React.useState(Localization.locale);
    const localizationContext = React.useMemo(
        () => ({
        t: (scope, options) => i18n.t(scope, { locale, ...options }),
        locale,
        setLocale,
    }), [locale]);
  console.log(locale);
  return (
    <LocalizationContext.Provider value={localizationContext}>
        <NavigationContainer>  
            <AppNavigator />            
        </NavigationContainer>  
    </LocalizationContext.Provider>
  );
}
`
and this is the screen where i get the error **"Can't find variable: LocalizationContext"**

`import React, { useState, useContext } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import i18n from 'i18n-js';

const en = {
  hello: 'Hello',
  welcome: 'Welcome',
};  
const es = {
  hello: 'Hola',
  welcome: 'Bienvenido',
};
i18n.fallbacks = true;
i18n.translations = { en, es };

const LanguageScreen = (props) => {  
  const { t, locale, setLocale } = useContext(LocalizationContext);

  return (
    <View style={styles.screen}>
      <Text>Language Screen</Text>
      <StatusBar hidden />
      <Text style={styles.text}>
        Current locale: {locale}.{' '}
        {locale !== 'en' && locale !== 'es' 
          ? 'Translations will fall back to "en" because none available'
          : null}
      </Text>
      <Text>{t('hello')}</Text>
      <Text>{t('welcome')}</Text>
      {locale === 'en' ? (
        <View>
          <Button title="Switch to Spanish" onPress={() => setLocale('es')} />          
        </View>
      ) : (
        <View>
          <Button title="Switch to English" onPress={() => setLocale('en')} />         
        </View>
      )}
    </View>
  );
};

export default LanguageScreen;`

It does not seem to recognise LocalizationContext in any component wrapped from the main navigation.

I've opened a ticket in Stackoverflow, no answer so far however the example shown in your documentation does not seems to be working.

Thanks

**Comment by brentvatne** [comment]
hi there! this is a good question to ask on https://forums.expo.io/

but the problem is fairly clear from reading your code - you are attempting to use LocalizationContext without importing it on "the screen where i get the error"

you should put LocalizationContext in another file and import it in that screen and in your root

**Comment by butri71** [comment]
Thanks @brentvatne 

That was me being silly, long day...  your comment helped me spotting the error.

Cheers
