### ISSUE TITLE
[docs] Scheduling Repeating Notifications Using Latest SDK

### ISSUE THREAD

**Issue by swushi** [expo/expo#11080]
[Link To Documentation Page](https://docs.expo.io/versions/latest/sdk/notifications/)

Since Expo's latest SDK Update that has updated their Notification API, I have found it much more difficult to produce repetitive notifications.

#### What I am trying to do:
Schedule a repeating weekly notification on specific days. For example, someone could select MWF at 7:00 PM.
In Expo's old Notification API (which will lose support in future SDK updates) I would simply schedule 3 different repeating notifications with the initial time and date of the first notification and then set its repeat attribute to 'weekly'.

##### Old API scheduling:
```
// OLD API 
const localNotification: ExpoLocalNotification = {     
  notification: {       
    title: notificationTitle,       
    body: notificationBody,     
  },     
  repeat: {                            // notice this is an object with configuration       
  time: remindTime,       
  repeat: "week",     
  }, 
}; 
```
However, with their new API, they have adjusted how you schedule local notifications.

##### New API scheduling:
```
Notifications.scheduleNotificationAsync({   
  content: {     
    title: notificationTitle,   
  },   
  trigger: {     
    seconds: 60 * 20,     
    repeats: true                       // now boolean, no longer an obj w/ repeat config   
  }, 
}); 
```
With their new API, they provide various triggers for scheduling, but none of them have any configuration for repeat frequency.
```
export type NotificationTriggerInput =   
| null   
| ChannelAwareTriggerInput   
| DateTriggerInput   
| TimeIntervalTriggerInput   
| DailyTriggerInput   
| CalendarTriggerInput; 
```
The only solution I see to this is by just physically scheduling each notification for the next year or so. Then just repeat.
Any advice? How do you guys usually handle repeating notifications in production apps? Will FCM support this?
Thanks in advance!

**Comment by swushi** [comment]
Any update on this?

**Comment by cruzach** [comment]
added to our docs in https://github.com/expo/expo/commit/aa01cf1a901724ff2dd73ff3ee256b35c40f3488

You'll have to wait until SDK 40 (releasing very soon) to use this in the managed workflow

**Comment by kasran15** [comment]
What about a HourlyTriggerInput?
I don't see a way to schedule a hourly notification
