### ISSUE TITLE
[expo-permissions][iOS] accessPrivileges is never limited for Permissions.CAMERA_ROLL

### ISSUE THREAD

**Issue by jparksecurity** [expo/expo#11081]
### Summary of Issue 
Accroding to [doc](https://docs.expo.io/versions/v39.0.0/sdk/permissions/#permissionscamera_roll), `accessPrivileges` should be `limited`.

However, it's `all` even if I click `selected photos` for `Permissions.CAMERA_ROLL`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    Expo Workflow: managed

Platform: iOS

### Reproducible Demo

 https://snack.expo.io/@horaeng/blessed-truffle
### Steps to Reproduce

1. Run `Permissions.askAsync(Permissions.CAMERA_ROLL);`
2. choose `Selected Photos`
3. check `accessPrivileges` value

### Expected Behavior vs Actual Behavior

`accessPrivileges` should be `limited` when a user choose `Selected Photos`.

**Comment by SimenB** [comment]
I was just about to open an issue for this 😅 I mentioned it in #11070, but it seems orthogonal to the main problem of that issue

**Comment by cvburgess** [comment]
My team is seeing this to, our QA team reported this in SDK 42, and still an issue in SDK 43.

When we were "vanilla" react native (before migrating to expo two months ago) we did not have this issue.

**Comment by brentvatne** [comment]
@cvburgess - expo-permissions was deprecated a while ago and is not supported at all on sdk 43

**Comment by cvburgess** [comment]
Sorry, we are using `getMediaLibraryPermissionsAsync` - I didn't realize this was something else.

Heres the functions called in isolation:

```js
import {
  getMediaLibraryPermissionsAsync,
  launchImageLibraryAsync,
  requestMediaLibraryPermissionsAsync,
  MediaTypeOptions,
} from "expo-image-picker";

getMediaLibraryPermissionsAsync();
requestMediaLibraryPermissionsAsync();
launchImageLibraryAsync({
  allowsEditing: true,
  allowsMultipleSelection: false,
  mediaTypes: MediaTypeOptions.Videos,
});
```

Should I open a new issue? Its identical but I guess for a different method.

**Comment by cvburgess** [comment]
Steps to reproduce:

1. Select limited photos when granting permissions
2. Access the camera roll with expo-image-picker
3. [ BUG ] All items, not just the ones selected appear as an option
4. If the user goes to iOS settings, the limited option is selected and the selected options are accurate

It appears as if the image picker doesn't respect the limited selection. Is that a regression or a misunderstanding of the feature? Other react-native pickers we used pre-expo respected the option so it feels library-specific.
