### ISSUE TITLE
EXPO SDK39 crash on Huawei devices

### ISSUE THREAD

**Issue by DimaNovik** [expo/expo#11082]
When trying to run a clean build of expo-cli SDK39, Huawei devices crash.

Information about test device:
**name**: Huawei P40 lite E
**model**: ART-L29
**Android version**: 10

package.json file information:
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~39.0.2",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}`

**Comment by AdamJNavarro** [comment]
Hey, @DimaNovik can you elaborate on when and how the app is crashing? Also, are you able to access the device logs? https://docs.expo.io/workflow/debugging/#my-production-app-is-crashing 

Also, you use the word "devices" in the title. Have you reproduced the crash on other Huawei devices in addition to the model you listed above?

Cheers,
Adam

**Comment by DimaNovik** [comment]
Made bug reports using ADB Logcat.
[logcat.txt](https://github.com/expo/expo/files/5569051/logcat.txt)

**Comment by eKuzhel** [comment]
Same problem on Huawei P40, no one expo app starts. The usual RN is ok, it starts up. And expo doesn't even pass the splash screen

**Comment by DimaNovik** [comment]
Hy. tried to do "Existing Expo managed workflow apps" expo eject and then build project. Problem still exists.
[logcat (1).txt](https://github.com/expo/expo/files/5574311/logcat.1.txt)

Attach video screencast. Let me remind you that the assembly is clean

![telegram-cloud-document-2-5314256961980598412](https://user-images.githubusercontent.com/6716713/99815610-310abf80-2b53-11eb-96d2-60267633386a.gif)


Cheers,
Dima

**Comment by eKuzhel** [comment]
@AdamJNavarro @cruzach 

Can you help figure it out?

**Comment by brentvatne** [comment]
we believe this is happening on huawei devices without google play services, because we depend on google play services extensively, eg: for FCM. we will investigate how to resolve this, any PRs would be welcome.

to resolve this on a particular device for now, you can search for how to install google play services on it. sadly, huawei is diverging significantly from google now which is causing problems for the android ecosystem.
