### ISSUE TITLE
Pedometer's step count is inconsistent with Apple Health App

### ISSUE THREAD

**Issue by lukezirngibl** [expo/expo#11088]
Expo SDK 39
expo-sensors v9.1.0

Pedometer.getStepCountAsync only returns steps recorded by the iPhone and NOT steps that were synced to the phone by 3 parties (e.g Garmin watch or Apple Watch). 

Therefore, if I walk around my house (200 steps) and then go running with my watch (10,000 steps), my expo app thinks I only took 200 steps for the day.

**Comment by cruzach** [comment]
the pedometer from `expo-sensors` relies on [CMPedometer](https://developer.apple.com/documentation/coremotion/cmpedometer) on the iOS side, which is just a measure of how many steps were taken with the device. I believe what you're looking for is the data from [HealthKit](https://developer.apple.com/documentation/healthkit/reading_data_from_healthkit) (not core motion)

**Comment by JonasHenrq** [comment]
Has this problem been resolved yet? Today, with `"expo-sensors": "~11.3.0"`, I have the same problem.

**Comment by HuzefaUsama25** [comment]
same problem in 2025
