### ISSUE TITLE
ScreenOrientation.lockPlatformAsync has no effect on iPad

### ISSUE THREAD

**Issue by robertracz** [expo/expo#11084]
### Summary of Issue 

Setting ScreenOrientation.lockPlatformAsync has no effect on iPad. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.14.0/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

### Reproducible Demo

```javascript
{
    "ios": {
      "supportsTablet": true,
      "requireFullScreen": true
    },
}
```

```javascript
  import * as ScreenOrientation from 'expo-screen-orientation';

  React.useEffect(() => {
    (async function changeScreenOrientation() {      
        await ScreenOrientation.lockPlatformAsync({
          screenOrientationArrayIOS: [
            ScreenOrientation.Orientation.PORTRAIT_UP,
          ],
        })      
    })();
  }, []);
 ```

### Steps to Reproduce

Start the app in an Ipad in portrait. Rotate to landscape.

### Expected Behavior vs Actual Behavior

It should not rotate.

**Comment by AdamJNavarro** [comment]
Hey @robertracz, this is expected behavior if the ipad is running iOS 9+ due to split view mode. You can read about this more in depth here: https://docs.expo.io/versions/v39.0.0/sdk/screen-orientation/#warning

Cheers,
Adam

**Comment by robertracz** [comment]
Hey @AdamJNavarro, eh sorry I rushed through that part and for some reason I thought `"requireFullScreen": true` opts out of that automatically. That makes sense though, thanks for the quick response.

**Comment by krschacht** [comment]
@AdamJNavarro  I read the docs the same way as Robert: I thought you can't do lockPlatformAsync unless you do `requireFullScreen: true`, but if you do that then you get this ability. Is that an incorrect reading of this? Does lockPlatformAsync() not do anything on iOS regardless of the settings? The docs say, "In order to be able to lock screen orientation using this module you will need to disable support for this feature." so that implies you can disable support for split screen and then use this feature.

**Comment by brunops** [comment]
How does one disable split view mode? `requireFullScreen: true` doesn't seem to work on iPad

**Comment by arbass22** [comment]
I am having issues locking iPad orientation as well and the docs are very unclear about what is supported or how to disable the split mode view (if that is actually even the problem here).

I am aiming to support only Landscape

**Comment by K-E-L** [comment]
setting "requireFullScreen" in app.json to true disables the split view mode for me
