### ISSUE TITLE
FileSystem downloadAsync poor performance on Android

### ISSUE THREAD

**Issue by gkuettel** [expo/expo#11090]
We're using FileSystem API to download videos and `downloadAsync()`is absolutely crushing the JavaScript thread on Android. Performance is good on iOS. 

Are there any known issues with `downloadAsync` performance on Android? Any possible workarounds?

Thanks.

**Comment by brentvatne** [comment]
please follow the issue template :) 

https://github.com/expo/expo/issues/new?labels=Issue+needs+review&template=bug_report.md
