### ISSUE TITLE
SplitScreen mode on Android, Works in ExpoClient but crashes on standalone build (.apk and .aab) - Expo Cloud Build Agend

### ISSUE THREAD

**Issue by evangeloszotos** [expo/expo#11091]
### Summary of Issue 
On android, a Standalone build, .apk or .aab crashes, once the Split Screen mode is entered.
The same code though works when running on the expo client. Only the Standalone app crashes.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.28.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~39.0.2 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

- Android - Standalone build.
- Created using expo build:android
- Selected "apk" 
- The build was created in the ExpoCloud (Build Agents)
- It was Tested on a Samsung Galaxy S7 Edge and on Huawei P20 lite, physical hands on devices. See Screenshots for more details about the devices.

![Screenshot_20201120-110025_Settings](https://user-images.githubusercontent.com/33234890/99790080-e32a9300-2b23-11eb-882f-63f0fa9b1b9e.jpg)
![PHOTO-2020-11-20-10-48-56](https://user-images.githubusercontent.com/33234890/99790084-e3c32980-2b23-11eb-9389-542de0fa7cfb.jpg)

Initially I did this, because my actual app is crashing when starting split screen, so I wanted to know if it is my fault, or if the expo just crashes. Here is the stacktrace that I get when I start the Split Screen mode on my original app, installed from the PlayStore: 
(I omitted Package Name)
![20201120-111437_Market Feedback Agent_LI stacktrace](https://user-images.githubusercontent.com/33234890/99790066-ddcd4880-2b23-11eb-9803-e2ddc8de8452.jpg)

### Reproducible Demo
I have recoreded a video:  [https://youtu.be/PIEE6qRUoUI](https://youtu.be/PIEE6qRUoUI)
### Steps to Reproduce
- Create a demo project with `expo init my-demo-proejct` 
- Select TabsTemplate (TypeScript)
- run `expo build:android` (choose APK or AAB)
- Install the created apk or aab on your phone
- Start the App
- Press the task manager button on your device
once the app is shown in the windowed mode, press the SplitScreen button at the Header Bar
- App Crashes

Tested on Android 8.0.0 (physical devices)

### Expected Behavior vs Actual Behavior
Expected: The installed standalone app does not crash.
Actual: The installed stanalone app crashes

**Comment by dapperappdeveloper** [comment]
Encountered same issue, a feature that allows split screen to be disabled within the app.json would be helpful

**Comment by wennaspeedy** [comment]
I have also this issue, but I think I didnt open splitscreen.

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/11091 should fix an issue where the app crashes when you re-open the app after a crash
