### ISSUE TITLE
App was required to update for Background Location by Google

### ISSUE THREAD

**Issue by doubleh311** [expo/expo#11102]
### Summary of Issue
My app on the Play Store was required to update a new version without background location permission or to submit an approval for the usage of background location

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo SDK 38
Expo CLI 3.27.12
Permission on app.json was set to: "permissions": []
I did not install expo-location to my project
On Android 10: there is a permission: Location

### Found
In the yarn.lock there is expo-location in the dependencies for Expo SDK 38
In the Expo.fx.expo.js there is a usage of expo-location
`import { installWebGeolocationPolyfill } from 'expo-location';
...
installWebGeolocationPolyfill();
`
I think this one cause the app to need location in the permission in case I set permission to []

###
I would like to know if this is the rootcause of the problem and is there any way to get rid of it?

Thanks

**Comment by valdrox** [comment]
Got an email about this as well. I'm on SDK 39. This was the relevant part of the message : 

Issue with your app
--
We found that your app [APP NAME] uses background location data. You must remove access to location in the background or get approval for the requests by January 18, 2021 so your app can stay on Google Play. You still need to get approved by the deadline even if you previously informed us during an app submission that your app is not yet compliant.

**Comment by brentvatne** [comment]
@valdrox - please refer to https://docs.expo.io/distribution/app-stores/#android-permissions

@doubleh311 - android permissions we revamped in sdk 39, please update your project to have more control over them

**Comment by dominik992** [comment]
@doubleh311 @valdrox have you managed to fix the issue?

**Comment by app-arianamini** [comment]
Still the same issue, now it is official, I hate React Native. Always the same, as a developer you need third-party libraries based on some other third-party stuff.....

**Comment by valdrox** [comment]
@dominik992 I upgraded to sdk 40 and ejected to the bare workflow (for implementing InAppPayments), and removed the permissions from the config file, and thankfully nothing appeared to break. Everything seems okay on my end, but I don't know if it would be if I was still on the managed workflow, which i'm guessing you are using. Good luck!

**Comment by brentvatne** [comment]
if you have this problem, please reply with answers to these questions:

1. Are you using managed or bare app?

2. What SDK version do you use?

3. What packages do you use? (e.g. list your package.json)

4. What is the output of `aapt2 d permissions path/to/app.apk` (See this [installation/usage guide](https://developer.android.com/studio/command-line/aapt2) of aapt2)

5. What is the name of your app (e.g. @acme/app)

**Comment by r-mhjn** [comment]
Hi @brentvatne, i was able to send my app for review in play console after removing the location permission's, but the app update got rejected on the grounds of location permission's can you please help with this. Thanks alot.
1. I'm using managed workflow.
2. 40
3. 
- `"@react-native-community/async-storage": "~1.12.0",
-     "@react-native-community/checkbox": "^0.5.6",
-     "@react-native-community/masked-view": "0.1.10",
-     "@react-native-community/picker": "^1.8.1",
-     "@react-native-community/slider": "^3.0.3",
-     "@react-navigation/native": "^5.0.8",
-     "@react-navigation/stack": "^5.1.0",
-     "axios": "^0.19.2",
-     "clamp": "^1.0.1",
-     "expo": "^40.0.0",
-     "expo-av": "~8.7.0",
-     "expo-firebase-analytics": "~2.6.0",
-     "expo-firebase-core": "~1.3.0",
-     "expo-google-sign-in": "~8.4.0",
-     "expo-linear-gradient": "~8.4.0",
-     "expo-localization": "~9.1.0",
-     "expo-location": "~10.0.0",
-     "i18n-js": "^3.5.1",
-     "jwt-decode": "^2.2.0",
-     "native-base": "^2.13.8",
-     "react": "16.13.1",
-     "react-dom": "16.13.1",
-     "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz",
-     "react-native-deck-swiper": "^1.6.7",
-     "react-native-dropdown-menu": "^2.0.0",
-     "react-native-gesture-handler": "~1.8.0",
-     "react-native-keyboard-aware-scroll-view": "^0.9.1",
-     "react-native-material-dropdown": "^0.11.1",
-     "react-native-paper": "^3.10.1",
-     "react-native-picker-checkbox": "^2.0.2",
-     "react-native-reanimated": "~1.13.0",
-     "react-native-responsive-dimensions": "^3.0.0",
-     "react-native-safe-area-context": "3.1.9",
-     "react-native-screens": "~2.15.0",
-     "react-native-slider": "^0.11.0",
-     "react-native-web": "~0.13.12",
-     "react-native-webview": "11.0.0",
-     "react-navigation": "^4.2.2",
-     "socket.io-client": "2.1.0",
-     "transliteration": "^2.1.11",
-     "validator": "^12.2.0"`

```
4. `package: com.bobble.mutli_project_manager
permission: com.bobble.mutli_project_manager.permission.C2D_MESSAGE
uses-permission: name='com.bobble.mutli_project_manager.permission.C2D_MESSAGE'
uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.SYSTEM_ALERT_WINDOW'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.camera'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='host.exp.exponent.permission.C2D_MESSAGE'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='com.sonymobile.home.permission.PROVIDER_INSERT_BADGE'
uses-permission: name='com.huawei.android.launcher.permission.CHANGE_BADGE'
uses-permission: name='com.huawei.android.launcher.permission.READ_SETTINGS'
uses-permission: name='com.huawei.android.launcher.permission.WRITE_SETTINGS'
uses-permission: name='android.permission.READ_APP_BADGE'
uses-permission: name='com.oppo.launcher.permission.READ_SETTINGS'
uses-permission: name='com.oppo.launcher.permission.WRITE_SETTINGS'
uses-permission: name='me.everything.badger.permission.BADGE_COUNT_READ'
uses-permission: name='me.everything.badger.permission.BADGE_COUNT_WRITE'
uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'`
5. Data Annotator.

**Comment by ghacosta** [comment]
Any news on this topic? I don't wanna to eject my app in order to solve it!

**Comment by AMoktar** [comment]
I'm here with the same issue :(

**Comment by r-mhjn** [comment]
I haven't been able to resolve the issue yet.

**Comment by doubleh311** [comment]
Hi @brentvatne, @valdrox , @r-mhjn, @ghacosta @AMoktar 
FYI
I have been away a while for this topic, I found that in Expo.fx.expo.js file of expo folder in the node_modules, currently import this line 
import { installWebGeolocationPolyfill } from 'expo-location';
and this is the root cause
You can never find location request on android 8 or lower, but in andoird 10, you can see location permission in settings even you set permission is [] in the app.json

After remove those line of code, the location permission disappear on the settings.
But this fix is not official, especially work in a team.
My project still at expo 38

**Comment by brentvatne** [comment]
@doubleh311 - js imports are unrelated to what packages are used in your android app, but i'm glad you were able to resolve your issue!

**Comment by brentvatne** [comment]
please refer to https://github.com/expo/expo/issues/11918 if you land on this issue
