### ISSUE TITLE
'Network Request Failed' for prolonged requests in iOS

### ISSUE THREAD

**Issue by gilbert** [expo/expo#11104]
### Summary of Issue 
For `fetch` requests that takes over 3-4 seconds, if the user backgrounds the app, the request just fails.

### Reproducible Demo

Here's [the snack demo](https://snack.expo.io/@gumdrop/github.com-expo-examples:with-formdata-image-upload-app). It's copied from [the official example](https://github.com/expo/examples/tree/master/with-formdata-image-upload) with two changes:

1. The endpoint points to our own sample endpoint, which just spits out some json after a 5 second delay
2. The request uploads an empty body instead of a file, and without the multipart header (eliminating the possibility that this is file-upload specific)

### Steps to Reproduce

1. Take a photo or select a photo
2. Background the app once the request starts
3. Wait about 2 seconds
4. Come back to the app
5. Request failed

### Expected Behavior vs Actual Behavior

There should be a way to robustly handle this common situation ([beginBackgroundTask](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtask) comes to mind). Whether it's due to a file upload, a slow 3rd party api, or a slow internet connection, we prefer not to eject expo to handle internet requests that take longer than a few seconds (using expo has been great!).

**Comment by AdamJNavarro** [comment]
Hey @gilbert, this is expected behavior for the request to terminate when the app is backgrounded. To handle background uploads, you can use the `FileSystem` module: https://docs.expo.io/versions/v39.0.0/sdk/filesystem/#filesystemuploadasyncurl-fileuri-options

Cheers,
Adam

**Comment by cruzach** [comment]
Just to add on to what Adam said above, you can also make use of `expo-background-fetch` if you're looking to do some more general fetch requests that aren't file uploads in the background- https://docs.expo.io/versions/latest/sdk/background-fetch/
