### ISSUE TITLE
takeSnapshotAsync: The resulting image has incorrect dimensions

### ISSUE THREAD

**Issue by jhalborg** [expo/expo#1110]
Hey there,

I’m trying to make a view that shows an image with another image on top of it. The purpose is that a user can pick an image, add a ‘sticker’ that can be panned, scaled and rotated a la Snapchat and save it.

To save the result, I’m using takeSnapshotAsync, but I’m having difficulty understanding how to set the quality, height and width variables.

The results I’m getting from different configs of takeSnapshotAsync are not logical to me:
```
quality: 1, 
height: 1200, 
width: 1200, 
real size in camera roll: 3500 x 3500
____
quality: 1, 
height: 1200, 
width: 1200, 
real size in camera roll: 4200 x 4200
____
quality: 1, 
height: 800, 
width: 800, 
real size in camera roll: 2800 x 2800

```
My goal is, of course, to save an image with same dimensions as the original but with the sticker ‘burnt in’, but I can’t see how and if this is possible from the above tests? It seems that takeSnapshotAsync can produce a large enough image (at least for my needs, 4200x4200 = 17.6 megapixels), but I still cannot see the relation between the results, and what height/width I’m supposed to pass in the config to end up with an image the same size as the original.

I'm not sure if this is a bug report, or a request for better docs on what to pass in the config. 

I’ve made a sketch to play around with here: https://snack.expo.io/ryO6GTAbf

**Comment by terribleben** [comment]
Hey there, do you happen to remember whether this was on iOS or Android? And also which specific device/simulator/emulator model you were using?

**Comment by jhalborg** [comment]
Hey :)

I was testing it on a Nexus 6P with 8.0, and an iPhone 7 emulator with iOS 11.2

**Comment by ide** [comment]
The last two samples you posted (1200x1200 becoming 4200x4200 and 800x800 becoming 2800x2800) would make sense on a Nexus 6P which has a 3.5x pixel ratio. When you work with pixel values in a UI, most of the time those units are "logical pixels" or "device-independent pixels". With images like PNG files, you often work with "physical pixels".

You can get the pixel ratio of the device with this React Native API called `PixelRatio.get()`: https://facebook.github.io/react-native/docs/pixelratio.html

**Comment by jhalborg** [comment]
@ide - So sorry for taking so long to respond. I just tested it, and it seems that you're indeed right. 

For anyone finding this in the future, the way to get a picture of the dimensions you want is something like this:

```
const targetPixelCount = 1080; // If you want full HD pictures
const pixelRatio = PixelRatio.get(); // The pixel ratio of the device
// pixels * pixelratio = targetPixelCount, so pixels = targetPixelCount / pixelRatio
const pixels = targetPixelCount / pixelRatio;

const result = await takeSnapshotAsync(this.imageContainer, {
      result: 'file',
      height: pixels,
      width: pixels,
      quality: 1,
      format: 'png',
});
```
