### ISSUE TITLE
You don't have Device ID for your Constants API documentation [docs] 

### ISSUE THREAD

**Issue by thebantz** [expo/expo#11113]

**Comment by thebantz** [comment]
Unique Device ID not available in Constants Documentation

**Comment by brentvatne** [comment]
https://expo.canny.io/feature-requests/p/provide-access-to-device-id-that-is-consistent-across-installations

**Comment by brentvatne** [comment]
> Apple restricted access to device id for privacy purposes since ios 7.0 release.
