### ISSUE TITLE
On expo, there are multiple charts on the current page, jump to another page, the system crashes directly, I don't know what to do

### ISSUE THREAD

**Issue by Tom0115** [expo/expo#11114]
package.json：
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@eva-design/eva": "^2.0.0",
    "@highcharts/highcharts-react-native": "^3.1.2",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/material-top-tabs": "^5.3.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "@ui-kitten/components": "^5.0.0",
    "@ui-kitten/eva-icons": "^5.0.0",
    "axios": "^0.21.0",
    "expo": "~39.0.2",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-echarts-wrapper": "^2.0.0",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-svg": "9.13.6",
    "react-native-tab-view": "^2.15.2",
    "react-native-table-component": "^1.2.1",
    "react-native-web": "~0.13.12",
    "react-native-webview": "^10.10.2"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}

Mobile devices: android 10
charts library: react-native-echarts-wrapper

**Comment by Tom0115** [comment]
Replicable demos:

`const options = {
    legend: {
      // top: 15,
      bottom: 1
      // right: 15,
      // orient: "vertical",
      // itemGap: 1,
      // align: "left"
    },
    grid:{
      top: 10
    },
    tooltip: {},
    backgroundColor: "#fff",
    dataset: {
      source: [
        ['product', '同期', '本期'],
        ['1月', 43.3, 85.8],
        ['2月', 83.1, 73.4],
        ['3月', 86.4, 65.2],
        ['4月', 72.4, 53.9]
      ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    series: [
      {
        type: 'bar',
        itemStyle: {
          normal: {
            color: '#99C5F0'
          }
        }
      },
      {
        type: 'bar',
        itemStyle: {
          normal: {
            color: '#D4F8CD'
          }
        }
      },
    ]
  }
<View style={{width: windowWidth, height: 200}}>
          <ECharts
            option={options}
            backgroundColor="rgba(93, 169, 81, 0.3)"
          />
 </View>
`

**Comment by AdamJNavarro** [comment]
Hey @Tom0115, seeing as this seems specific to a third party library could you please determine if this is Expo-specific by creating a vanilla RN project and seeing if the crash occurs? If the crash only occurs in an Expo environment, we can take a deeper look into this.

Cheers,
Adam

**Comment by Tom0115** [comment]
With Android 10 below Expo, there seems to be no problem

**Comment by Tom0115** [comment]
It is the third party library. Thank you for your reply

**Comment by brentvatne** [comment]
issues on this repository are for bugs that you can demonstrate in expo tools and libraries, not in other third party libraries. if you can reproduce the problem you're encountering using only expo tools and libraries then feel free to create another issue here for it, otherwise i recommend trying to isolate your issue and post it to the library that is the source of the bug. good luck!
