### ISSUE TITLE
metro.config.js is ignored because of default expo-cli parameters

### ISSUE THREAD

**Issue by MasGaNo** [expo/expo#11116]
### Summary of Issue 
Hi everyone,

By following the documentation regarding [Customizing Metro](https://docs.expo.io/guides/customizing-metro/), I add the `metro.config.js` file into my project root, it was perfectly taken in consideration (I put a basic `console.log`, which is displayed in my terminal after executing `expo start`).

But some parameters of `metro.config.js` (like `sourceExts`) are ignored as `metro` prioritize `argv`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```

  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.44 => 0.12.44 
      expo: ~39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed
```

Platform: Mobile (which require `Metro bundler`)

### Reproducible Demo

As describe above, what I want to achieve is to add a new `sourceExts`:
```js
const { getDefaultConfig } = require('@expo/metro-config');
const defaultConfig = getDefaultConfig(__dirname);

const newConfig = {};
if (process.env.EXPO_TENANT) {
  newConfig.resolver = {
    sourceExts: [`${process.env.EXPO_TENANT}.js`, ...defaultConfig.resolver.sourceExts],
  };
}

module.exports = newConfig;
```
If I print `newConfig`, everything is fine, except the fact that this list of `sourceExts` is not property updated once it reach `Metro` bundler.
```js
// newConfig
{
  // ...
  sourceExts:
      [ 'lt.ts', // <- the new ext I want to add
        'expo.ts',
        'expo.tsx',
        'expo.js',
        'expo.jsx',
        'ts',
        'tsx',
        'js',
        'jsx',
        'json',
        'wasm' ],
  // ...
}
```
```js
// Final metro config
{
  // ...
  sourceExts:
   [ 'expo.ts', // <- Missing my lt.ts 😰
     'expo.tsx',
     'expo.js',
     'expo.jsx',
     'ts',
     'tsx',
     'js',
     'jsx',
     'json',
     'wasm' ],
  // ...
}
```

So, after digging deeper in the difference source code, I managed to understand that when `Expo` tries to start React Native Server in the [xdl/src/Project.ts](https://github.com/expo/expo-cli/blob/dc82a5de9e6cbc155ec410f28af7f14eb4e1d7d2/packages/xdl/src/Project.ts#L1781), and it tries to fetch the [`userPackagerOpts`](https://github.com/expo/expo-cli/blob/dc82a5de9e6cbc155ec410f28af7f14eb4e1d7d2/packages/xdl/src/Project.ts#L1486) which is `undefined` (I need to dig deeper to understand why).

And finally, it [spawns react-native-cli](https://github.com/expo/expo-cli/blob/dc82a5de9e6cbc155ec410f28af7f14eb4e1d7d2/packages/xdl/src/Project.ts#L1548) with these parameters:
```js
[ '/.nvm/versions/node/v10.14.1/bin/node',
  '/expoproject/node_modules/react-native/local-cli/cli.js',
  'start',
  '--port',
  '19001',
  '--customLogReporterPath',
  '/.nvm/versions/node/v10.14.1/lib/node_modules/expo-cli/node_modules/@expo/xdl/build/reporter/index.js',
  '--sourceExts',
  'expo.ts,expo.tsx,expo.js,expo.jsx,ts,tsx,js,jsx,json,wasm', // <- Default sourceExts list from expo, without user config
  '--assetPlugins',
  '/expoproject/node_modules/expo-asset/tools/hashAssetFiles.js' ]
```
Then, `react-native-cli` does many things, and finally execute `metro-config` code, especially the [`loadConfig`](https://github.com/facebook/metro/blob/df8fd4cc18ead6ef092d22f0c65c264629e53a33/packages/metro-config/src/loadConfig.js#L50) file which load a `cosmiconfig`:
```js
const explorer = cosmiconfig('metro', {
  searchPlaces: ['metro.config.js', 'metro.config.json', 'package.json'], // <- YOUHOU metro.config.js is included!
  // ...
});
```

And after loading the [whole configuration via `loadMetroConfigFromDisk`](https://github.com/facebook/metro/blob/df8fd4cc18ead6ef092d22f0c65c264629e53a33/packages/metro-config/src/loadConfig.js#L276), if I print the `configuration` value:
```js
{ resolver:
   { assetExts: [ Array ],
     platforms: [ 'ios', 'android', 'native' ],
     sourceExts:
      [ 'lt.ts', // <- Welcome back!
        'expo.ts',
        'expo.tsx',
        'expo.js',
        'expo.jsx',
        'ts',
        'tsx',
        'js',
        'jsx',
        'json',
        'wasm' ],
     resolverMainFields: [ 'react-native', 'browser', 'main' ],
     // ...
  },
  serializer: {Object},
  server: {Object},
  symbolicator: {Object},
  transformer: {Object},
  // ...
}
```

But... The drama happens [few lines after](https://github.com/facebook/metro/blob/df8fd4cc18ead6ef092d22f0c65c264629e53a33/packages/metro-config/src/loadConfig.js#L293) 😱 :
```js
  // Override the configuration with cli parameters
  const configWithArgs = overrideConfigWithArguments(configuration, argv);
```
As a reminder, we are talking about what `expo xdl` sends to `metro`:
```js
{ cwd:
   '/Users/norbert/Workspace/github.com/propertyfinder/pfbrokertoolsexpo',
  config: undefined,
  maxWorkers: undefined,
  port: 19001,
  resetCache: undefined,
  watchFolders: undefined,
  projectRoot: undefined,
  sourceExts:
   [ 'expo.ts', // <- Bye again 😢
     'expo.tsx',
     'expo.js',
     'expo.jsx',
     'ts',
     'tsx',
     'js',
     'jsx',
     'json',
     'wasm' ],
  reporter: { update: [Function: update] } }
```
And of course, the final object [`configWithArgs`](https://github.com/facebook/metro/blob/df8fd4cc18ead6ef092d22f0c65c264629e53a33/packages/metro-config/src/loadConfig.js#L312) which is return in the very last line:
```js
  return mergeConfig(configWithArgs, overriddenConfig);
```
contains only the parameters sent by `expo xdl`:
```js
{ resolver:
   { assetExts: [Array],
     platforms: [ 'ios', 'android', 'native' ],
     sourceExts:
      [ 'expo.ts', // <- No lt.ts 🏳️
        'expo.tsx',
        'expo.js',
        'expo.jsx',
        'ts',
        'tsx',
        'js',
        'jsx',
        'json',
        'wasm' ],
     resolverMainFields: [ 'react-native', 'browser', 'main' ],
     extraNodeModules: {},
    // ...
  }
  // ...
}
```
 
### Steps to Reproduce

Create new `expo` project, create `metro.config.js` file with `sourceExts` and execute `expo start`.

### Expected Behavior vs Actual Behavior

Expected Behavior:
I want to have my custom list of `sourceExts`.

Actual Behavior:
`expo xdl` ignores it and use its own default list.

I don't know what should be the approach:
- reporting the bug to `metro` team and ask them why `argv` have higher priority than `metro.config.js` file (well, I know the answer)
- `expo xdl` should not send its own list of `sourceExts` through CLI args, especially if the user already provides one
- dig deeper and understand why [`userPackagerOpts`](https://github.com/expo/expo-cli/blob/dc82a5de9e6cbc155ec410f28af7f14eb4e1d7d2/packages/xdl/src/Project.ts#L1486) is undefined (otherwise, it would solve this issue)

What do you think?

**Comment by brentvatne** [comment]
hi there! try starting expo with the following flag:

```
EXPO_USE_DEV_SERVER=1 expo start
```

this should resolve your issue. we had to do a bunch of work to make it possible to start metro with the required react-native configuration without just starting react-native cli in a separate process.

**Comment by MasGaNo** [comment]
Indeed, with this option, it works like a charm 😄 

Thanks for the hint 👍

**Comment by ide** [comment]
@fson Has this issue been addressed now with all of the expo-cli changes?
