### ISSUE TITLE
@react-native-community/picker has been deprecated

### ISSUE THREAD

**Issue by diegomais** [expo/expo#11118]
### Summary of Issue 

The library *@react-native-community/picker* has been renamed to **@react-native-picker/picker**.

See the GitHub new repository: [https://github.com/react-native-picker/picker](https://github.com/react-native-picker/picker).

This information is available at [https://www.npmjs.com/package/@react-native-community/picker](https://www.npmjs.com/package/@react-native-community/picker).

**Comment by brentvatne** [comment]
we've already changed this on master and it'll be released in sdk 40
