### ISSUE TITLE
Feature Request: CLI to upgrade to new Expo SDK

### ISSUE THREAD

**Issue by deadcoder0904** [expo/expo#1111]
You guys are so fast that everytime I start & finish an app, its a version behind of new SDK so I have to change it manually by going to the blog. 

Rather than that I wish a tool exists which would do the work of updating the `package.json` file & then [surrender](https://github.com/tiaanduplessis/react-native-surrender).

I can work on it, it won't take a lot of time, but I need to know (1) how to get the exact versions from & (2) which packages to change ❓ 

For (2), I think only 6 packages change `react-native`, `expo`, `react`, `react-navigation`, `jest-expo` & `sentry-expo`. So only (1) remains.

I got a name too `expo-updater` 😉

**Comment by deadcoder0904** [comment]
So I made a CLI tool named [expo-updater](https://github.com/deadcoder0904/expo-updater) which changes your `package.json` file to update to `SDK 24` for all packages except for `react` & `react-navigation`. 

I didn't find a way to automatically update to `react` & `react-navigation` versions so if any of you guys know it would be a great help.

**Comment by quinlanj** [comment]
hey @deadcoder0904 , its awesome that you open sourced your solution!  When you refer to updating the react & react-navigation versions, are you talking about bumping the versions of the packages in `package.json` ? For example, see `Upgrading your App` section in https://blog.expo.io/expo-sdk-v23-0-0-is-now-available-be0a8c655414

**Comment by deadcoder0904** [comment]
Yep exactly that, currently I fetch 4 out of 6 like [this](https://github.com/deadcoder0904/expo-updater/blob/master/index.js#L45) but I need those two. Can't scrape blog bcz it wouldn't be easy to maintain

**Comment by deadcoder0904** [comment]
There was a bug when a version of `expo` was bumped to `24.0.1` so I managed to release new version 2.0.0 which will be updated by me manually, its just a [JSON file](https://github.com/deadcoder0904/expo-updater/blob/master/expo.json) which will be kept in sync with newer releases of Expo SDK. So closing this one. Thanks @quinlanj & Merry Christmas 🎄 🎅
