### ISSUE TITLE
Expo Build Android Icon not changing

### ISSUE THREAD

**Issue by mrkhanakia** [expo/expo#1112]
I have mentioned the APP icon in app.json but expo is not changing the icon when I install the apk file it still shows the EXPO Icon

You can see in screenshot I have correctly mentioned the icon path

![screen shot 2017-12-14 at 8 07 50 pm](https://user-images.githubusercontent.com/2174170/33997475-8681109a-e10a-11e7-99b7-cf4f801e485b.png)

**Comment by karanmartian** [comment]
yes this is a breaking change. I cant release a new Android app with Expo icon like this. This needs to be fixed asap.

**Comment by sonaye** [comment]
Same here, we have a build ready but it has Expo icon instead, sdk 24.

**Comment by Zuken** [comment]
+1 Same here on android, sdk 23

**Comment by rebitte** [comment]
+1 same here on Android :(

![whatsapp image 2017-12-14 at 13 24 26](https://user-images.githubusercontent.com/30100865/34000030-4530b6ea-e0d3-11e7-9474-0dbf5036d014.jpeg)

**Comment by karanmartian** [comment]
Yea this is an expo server side issue agnostic to any particular version of exp or sdk. This is a major issue and they need to fix the server. Hope they fix it soon because we are stuck on releasing a major fix to our users that is crashing the app on scroll and that fix is only available in sdk24. Boy o boy.

**Comment by rebitte** [comment]
https://forums.expo.io/t/critical-issue-expo-is-building-android-without-icon/5577

**Comment by karanmartian** [comment]
Yea another on here: https://forums.expo.io/t/getting-expo-app-icon-for-standalone-builds-instead-of-my-app-icon/5567/12.
Expo team request you to please escalate this issue for fix.

**Comment by karanmartian** [comment]
so guys in the interest of urgency the workaround I am going with right now is this until the Expo guys fix the server:

1. Grab the keystore from Expo:
exp fetch:android:keystore

2. Then use the APK Icon Editor to easily replace the expo icon for all sizes. Ironically i see that the apk that the new expo server is generating sees your icon only in the HDPI (72x72) and other sizes have the default expo icon. So I changed it accordingly.

3. Finally within APK Icon Editor and using the keystore obtained above I repack the APK.

What say?

**Comment by thiagolinsx** [comment]
+1 same here on Android with Expo SDK 24.0.0

**Comment by jesseruder** [comment]
Pushing out a fix now. Will let you know when it's available.

**Comment by jesseruder** [comment]
Ok the new builders are deployed. Testing them myself right now but the fix should be available.

**Comment by pabeda-bt** [comment]
I have a got a build 5 minutes ago, it has the same error.

**Comment by jesseruder** [comment]
@pabeda-bt I think the builders might have not been fully deployed as of my last message. Just ran a build and it worked for me. Sorry about that.

**Comment by integratio** [comment]
It's working again for me. Thanks for the quick resolution!

**Comment by jesseruder** [comment]
Sorry about that everyone. Going to close this issue for now but ping me if it shows up again!

**Comment by pabeda-bt** [comment]
jesseruder - Thank you! I works

**Comment by newfylox** [comment]
Unfortunately it doesn't work for me.

**Comment by jesseruder** [comment]
@newfylox what do you mean exactly? You ran `exp build` recently and got an .apk with an icon that didn't work? Can you provide more information about your project if so?

**Comment by newfylox** [comment]
Sorry, you were right. It only happens on EXPO but not when building and installing an APK. My bad.

**Comment by donedgardo** [comment]
I'm having the same issue but by building the APK. do i need to upgrade expo for this?

**Comment by pcowgill** [comment]
I'm having the same issue when building an APK for a standalone app

**Comment by gitadonis** [comment]
Same issue with SDK 31.0.0.
My app (installed on Android using the apk generated by expo server) has the expo icon on home screen.
I tried several things modifying app.json without success (expo.icon / expo.android.icon ...).
I also tried to open the apk in APK Icon Editor and icons seems to be good (several icons corresponding to my image at different resolutions).

Any ideas ?
thank you.
