### ISSUE TITLE
Bug with datetimepicker in ios 14 (local env)

### ISSUE THREAD

**Issue by NozhenkoD** [expo/expo#11126]
### Summary of Issue 

When I run in a local datetimepicker looks as wheels - 
![Screenshot 2020-11-25 at 15 20 58](https://user-images.githubusercontent.com/7542315/100233343-48babd00-2f32-11eb-9636-45bbc0b8169a.png)

But when I compile (`expo build:ios`) it looks with new ios 14 styles -
![Screenshot 2020-11-25 at 15 21 15](https://user-images.githubusercontent.com/7542315/100233495-7dc70f80-2f32-11eb-9d3f-e6ecbac1a256.png)

### Environment 

Expo Workflow: managed
Platform: iPhone 12 Pro Max simulator iOS 14.2

"expo": "^39.0.0",
"@react-native-community/datetimepicker": "3.0.0",

### Example code:

```
 <DateTimePicker
    testID="dateTimePicker"
    value={date}
    is24Hour
    mode="time"
    locale="en_GB"
    display="default"
    onChange={console.log}
/>
```

I have 2 questions. 
1. How set up a local environment with ios 14 views for datetimepicker?
2. How to turn on wheels view for datetimepicker in ios 14?

**Comment by brentvatne** [comment]
the expo client on the app store wasn't build with xcode12 and so it doesn't support new styles, but we did roll out xcode12 support in app store builds just last week.

1. you could build expo client locally, but this is fairly complicated. see the contributing guide on this repo
2. see the readme for that package

**Comment by hehex9** [comment]
@NozhenkoD set display to `spinner` instead of `default` should resolve this

**Comment by NozhenkoD** [comment]
> @NozhenkoD set display to `spinner` instead of `default` should resolve this

This does not solve the problem

**Comment by NozhenkoD** [comment]
> the expo client on the app store wasn't build with xcode12 and so it doesn't support new styles, but we did roll out xcode12 support in app store builds just last week.
> 
> 1. you could build expo client locally, but this is fairly complicated. see the contributing guide on this repo
> 2. see the readme for that package

1. It would be great to be able to build on the old version Xcode.
2. I saw issue in datepicker packages, but I don't know how fix it in expo. Need update `ios/APP_NAME/AppDelegate` file
https://github.com/react-native-datetimepicker/datetimepicker/issues/285#issuecomment-733836694

**Comment by hehex9** [comment]
> This does not solve the problem

2. `spinner` should be ok if your need is the wheels behavior 🤔️

**Comment by NozhenkoD** [comment]
@hehex9 Value default and spinner are equal. The problem is different. Wheels behavior is updated in ios14. 
The problem is the different views locally and when you build an app. 
When you develop locally with a simulator you don't see a new view datepicker. But when you build an app you have a new view. Check my screens in the first question.

**Comment by hehex9** [comment]
@NozhenkoD Sorry about the language.
I think the default picker style on iOS is [UIDatePickerStyleAutomatic](https://developer.apple.com/documentation/uikit/uidatepickerstyle/uidatepickerstyleautomatic?language=objc)?
> A style indicating that the system picks the concrete style based on the current platform and date picker mode.

Maybe that's why your app behaves differently under different iOS version?
If we don't need that **automatic**, we could set a specific value to `display`, like spinner. You can try that with `expo build:ios`. It totally works fine on my simulator (iPhone 12 - iOS 14.2)

(btw, spinner will [convert](https://github.com/react-native-datetimepicker/datetimepicker/blob/master/ios/RNDateTimePickerManager.m#L26) to UIDatePickerStyleWheels)

**Comment by NozhenkoD** [comment]
@hehex9 I tried value "spinner", the same result. Use a managed workflow.

**Comment by hehex9** [comment]
have you compiled your project via `expo build:ios`?  like brentvatne said, expo client is not build with Xcode 12 (that's the key) but the turtle services is.

**spinner** and **default** looks identical on the expo client currently.

**Comment by NozhenkoD** [comment]
@hehex9 What your solutions?

**Comment by rasmusviben** [comment]
Is there a solution for this? Encountering the same issue, and changing to "spinner" didn't resolve the issue.

**Comment by brentvatne** [comment]
run `EXPO_BETA=1 expo client:install:ios` to install the beta version of expo client that is built using xcode 12, so you can test this locally without doing a standalone app build.

![Screen Recording 2020-12-02 at 10 44 12 AM](https://user-images.githubusercontent.com/90494/100917623-40133b00-348c-11eb-8c5d-0e9c9d9c3339.gif)

also note that you need to specify a width - '100%' should work for most cases.

**Comment by brentvatne** [comment]
this is live in the latest client now, no need to use a beta version

**Comment by ndang6** [comment]
Any updates on this open bug ticket? 
I tried expo client:install:ios as @brentvatne mentioned above but it didn't work.

**Comment by brentvatne** [comment]
@ndang6 - use the latest version from the store
