### ISSUE TITLE
FileSystem doesn't correctly read files into base64

### ISSUE THREAD

**Issue by NTakemori** [expo/expo#11122]
#10971  🐛 Bug Report
### Summary of Issue 

Doesn't work with WEBP of HEIC images, when uploading the base64 string to firebase. It does however work for jpg/jpeg/pngs. When copying and pasting the base 64 string to certain websites, it does however decode to images for WEBP and HEIC images. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.3.6 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

Platform: iPhone 12 Pro Max simulator iOS 14

### Reproducible Demo

```
let uri = FileSystem.cacheDirectory + Date.now();
await FileSystem.makeDirectoryAsync(uri, {intermediates: true});
await FileSystem.copyAsync({to: uri, from: image});
let base64URL = await FileSystem.readAsStringAsync( uri, { encoding: FileSystem.EncodingType.Base64 });
//outputs a valid Base64, but doesn't work with WebP image, only jpg/jpeg/png

let storageRef = firebase.storage().ref();
let imageName = `${this.props.user.id}_ProfilePhoto_${Date.now()}_${i}`;
let imageRef = storageRef.child("Profile Photos/" + imageName);
let formattedImg = "data:image/png;base64," + base64URL ;
const snapshot = await imageRef.putString(formattedImg, "data_url");
const remoteURL = await snapshot.ref.getDownloadURL();

```
 
### Steps to Reproduce
Upload images using the MediaLibrary, transform them to base64 using FileSystem and send them to firebase

### Expected Behavior vs Actual Behavior

Expected: Image to be uploaded
Actual: small white square is uploaded for WEBP and HEIC images

**Comment by midoushitongtong** [comment]
If you want to convert the image to base64, you can use **expo-image-manipulator**

```typescript
import { manipulateAsync, SaveFormat } from 'expo-image-manipulator';

const imageUri = 'file:///xxx.xxx.HEIC';
const manipulatedImage = await manipulateAsync(imageUri, [], {
  compress: 1,
  format: SaveFormat.PNG, // convert to png
  base64: true, // return base64
});
base64 = `data:image/png;base64,${manipulatedImage.base64}`;
```
