### ISSUE TITLE
android 10 standalone Bug Report in MapView and expo-facebook

### ISSUE THREAD

**Issue by Kegovc** [expo/expo#11135]
###  The map is not displayed and the login with facebook does not work in the .aab compilation in Android 10 when downloading from the stores

in tests and in standalone compilations everything works but when downloading from the store they stop working only on android 10 devices
https://play.google.com/store/apps/details?id=mx.com.stx.ecofeed

**Comment by byCedric** [comment]
Hi @Kegovc, thanks for the issue. Unfortunately, you didn't provide enough information for us to investigate. Please follow the bug report template and provide a repro where your issue occurs. With that, we are able to help you further.

I can only point you to our docs, to double-check if you configured everything correctly:
- Make sure you [configured the `MapView` for standalone apps](https://docs.expo.io/versions/latest/sdk/map-view/#configuration).
- Make sure you configured [Facebook for standalone apps](https://docs.expo.io/versions/latest/sdk/facebook/#configuration).

Hope this helps!

**Comment by Kegovc** [comment]
### I already solved it.
**I document it for whoever works for the future.**
1) For google in the new google interface:
Go to Play Console → (your app) → Setting → Application signing **
Copy the value of SHA-1 Certificate Fingerprint
Go to Google API Dashboard → (your project) → Credentials
Select the appropriate "API keys" entry
Under Key restrictions → Application restrictions, ensure that the Android apps radio button is chosen.
Add or replace the SHA-1 Certificate Fingerprint with the value copied in step # 2
Click Done and then click Save

2) For expo-facebook:
[based on](https://stackoverflow.com/questions/44798378/google-play-app-signing-keyhash-mismatch)
run in your terminal **echo {SHA-1 Certificate Fingerprint} | xxd -r -p | openssl base64** and paste it as a key hash in your Facebook developer.
