### ISSUE TITLE
AuthSession response is always null in standalone apps

### ISSUE THREAD

**Issue by fafo** [expo/expo#11131]
### Summary of Issue 
Using expo-auth-session with Google provider works in expo client, but it always returns a null response either in standalone Android and bare react native apps.
The bug maybe is already open since I see many issues with AuthSession, but it's is not clear if it's the same issue.
The example is with the google provider for simplicity, but also the basic useAuthRequest displays the same behaviour.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.28.5 environment info:
    System:
      OS: Linux 5.0 Linux Mint 19.3 (Tricia)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.19.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

targeting Android

### Reproducible Demo

Directly from the documention:"
```
  const [request, response, promptAsync] = Google.useAuthRequest({
    expoClientId: "xxxx.apps.googleusercontent.com",
    androidClientId: "xxx.apps.googleusercontent.com"
  })
console.log("RESP", response)
```
and
```
 <Button
        title="Sign In with Google "
        onPress={() => promptAsync()}
      />
```
 
### Steps to Reproduce
- build the android standlone app
- launch on the device and finish the authentication
- read the logs with adb

### Expected Behavior vs Actual Behavior

response should contain the access token, but it remains null
If we read the result from promtAsync it's always of type "dismiss" in standalone apps

**Comment by takacskalman** [comment]
Any updates? I'm facing the same issue.

**Comment by fafo** [comment]
Apparently no. I switched to app auth in order to make it work.

**Comment by GiovanniColonni** [comment]
i'm facing the same problem today, any updates ? what should i do ?

**Comment by jgaNet** [comment]
Any Update ? I have the same problem

**Comment by tahola** [comment]
> Any updates? I'm facing the same issue.

I was finally able to make it work on Android by changing the scheme in app.json, instead of scheme: `"myapp"` I wrote the same name as the package `scheme: "app.myapp.com"`.

Weird thing now is that before the redirect chrome is asking me if I want to open it inside the app, my app name come twice and sometime it still return null.

**Comment by mickamy** [comment]
I fixed this issue with the following code.

https://github.com/expo/expo/issues/19445#issuecomment-2888421399

**Comment by useEffects** [comment]
No need `useEffect` at all, refer the code below

https://github.com/expo/expo/issues/19445#issuecomment-2888417575
