### ISSUE TITLE
ErrorBoundary does not work in production

### ISSUE THREAD

**Issue by nimabrownlee** [expo/expo#11137]
### Summary of Issue 
ErrorBoundary works fine in local development and even when using `expo start --no-dev --minify`. Unfortunately that's not the case in production (Expo client).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare
```

### Reproducible Demo

```
class ErrorBoundary extends Component<Props, State> {
  public state: State = {
    hasError: false,
  }

  public static getDerivedStateFromError(_: Error): State {
    return { hasError: true }
  }

  public componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    Sentry.Native.captureException(error, { extra: errorInfo })
  }

  public render() {
    if (this.state.hasError) {
      return (
        <SafeAreaView
          style={{ flex: 1, justifyContent: 'center', marginHorizontal: 24 }}
        >
          <Text
            style={{
              fontSize: 20,
            }}
          >
            There's an error.
          </Text>
        </SafeAreaView>
      )
    }

    return this.props.children
  }
}

export default ErrorBoundary
```
 
### Steps to Reproduce
Nothing fancy. Create an `ErrorBoundary` component and add it as top-level component in `App.tsx/App.js`. Then throw an error in any child component.

### Expected Behavior vs Actual Behavior
It should work in production but it doesn't.

**Comment by AdamJNavarro** [comment]
Hey @nimabrownlee, can you let me know if this works as expected in a vanilla React Native project? Before moving forward, I'd like to determine if this is an Expo-specific issue or not.

Cheers,
Adam

**Comment by nimabrownlee** [comment]
@AdamJNavarro Hey Adam, I can't tell you right now but I'll try to reproduce it under the week. I even tried Sentrys default ErrorBoundary and it crashes the app in production. Clearly it either can't used as a top-level container. Whats weird is that it works completely fine in development.
