### ISSUE TITLE
OTA with new native package causing old native version user crashes

### ISSUE THREAD

**Issue by TrustyTechSG** [expo/expo#11138]
### Summary of Issue
Bare workflow, add new package react-native-share, uploaded new native build to App Store, and then publish a OTA with expo-update, expect only user made the native update be able to see the OTA, however,  user without native upgrade also received the OTA updates, causing direct open crashes.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 27, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare

**Comment by conghai** [comment]
This is the same for me

```
Expo CLI 4.0.1 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/opt/node@12/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.5 **(and tested same in 4.0.1)**
    Expo Workflow: managed
```

My OTA Link (Working version): [https://ota.appfast.io/nevable/39/ios-index.json](https://ota.appfast.io/nevable/39/android-index.json)

1 - But not yet working from yesterday with `expo export` Always shows dialog [ Updating... ] but can't finish
2 - But it working well with `expo publish` - OTA Expo Test: [https://exp.host/@conghai/nevable/index.exp?sdkVersion=39.0.0](https://exp.host/@conghai/nevable/index.exp?sdkVersion=39.0.0)

I not any change in my OTA Server except bundle file & upgrade version number

**Comment by AdamJNavarro** [comment]
Hey @TrustyTechSG, if you didn't upgrade the SDK version of your app and didn't specify a release channel specific to the new native build containing the rn-share module then this is expected. Can you let me know if that's the case here?

Cheers,
Adam

**Comment by brentvatne** [comment]
please read https://docs.expo.io/bare/updating-your-app/#update-compatibility for more info :)

it is indeed expected that if you ship a js update to an incompatible native binary then you will end up with a crash. the docs page above should help clarify
