### ISSUE TITLE
Dimension does not resume to the one of portrait position after using expo-screen-orientation to rotate the screen

### ISSUE THREAD

**Issue by lxinghe** [expo/expo#11134]
### Summary of Issue 
I used await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE_RIGHT) for a certain page and then used await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP) before leaving the page. The rotation works fine but Dimensions.get('window').width does not go back to the one when it was in portrait, which might be a very serious bug. Not sure if it is expo-screen-orientation's bug or react native's bug. This appears to always happen on android, and most of the time on ios.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.28.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - E:\react-native\moego\node_modules\.bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^39.0.4 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
      react-navigation: ^2.4.1 => 2.18.3
    Expo Workflow: managed

### Reproducible Demo
here is the demo app github repo: https://github.com/lxinghe/TestExpoScreenOrientation/tree/master
 
### Steps to Reproduce
1. clone it
2. expo install
3. expo start
4. check it on the phone
5. go to detail page then go back to home page

### Expected Behavior vs Actual Behavior
Dimenssion.get('window').width shall go back to the one in portrait position, but it is still of the one in landscape orientation.
please help.

**Comment by AdamJNavarro** [comment]
Hey @lxinghe, based on your description it sounds like this falls under the React Native umbrella rather than Expo. With that said, I'm not sure this is a bug. As the `Dimension` [RN docs state](https://reactnative.dev/docs/dimensions) at the top, you should be using [`useWindowDimensions`](https://reactnative.dev/docs/usewindowdimensions) to ensure the values update as the window's dimensions change.

Cheers,
Adam
