### ISSUE TITLE
New update available downloading......... 

### ISSUE THREAD

**Issue by ponikar** [expo/expo#11146]
It's been more than hour since the Expo Client App is showing me this message. It is happening only first time! Whenever I try to run application on expo client it takes more than half an hour to start and this is happening with EXPO SDK 39. It was working fine before. 

I don't know what kind of update it is trying to download.

**Comment by brentvatne** [comment]
hi there, please follow the issue template when creating a new issue:

```
<!-- ATTENTION:
The US Thanksgiving holiday is this week, so responses from the Expo team will slow down from Nov. 25th to Dec. 1st. We’ll still be monitoring all of our services (i.e. builds, hosting, notifications) as usual.
If you’re celebrating Thanksgiving this week, enjoy your holiday! Stay safe and we’ll see you after the holidays
Thanks!
The Expo team
-->

## 🐛 Bug Report

### Summary of Issue <!-- (just a few sentences) -->


### Environment - output of `expo diagnostics` & the platform(s) you're targeting


### Reproducible Demo

<!--
- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve
-->
<!--
As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!
-->
 
### Steps to Reproduce


### Expected Behavior vs Actual Behavior

```

**Comment by conghai** [comment]
I also have the same situation. Always shows Update and never ends.

The build (`expo export --public-url`) **2** days ago has no problems. Only affected with builds **24 hours** ago

**Comment by brentvatne** [comment]
hey @conghai - we need more information. see my previous comment

**Comment by conghai** [comment]
```
Expo CLI 4.0.1 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/opt/node@12/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.5 **(and tested same in 4.0.1)**
    Expo Workflow: managed
```

My OTA Link (Working version): [https://ota.appfast.io/nevable/39/ios-index.json](https://ota.appfast.io/nevable/39/android-index.json)

1 - But not yet working from yesterday with `expo export` Always shows dialog [ Updating... ] but can't finish
2 - But it working well with `expo publish` - OTA Expo Test: [https://exp.host/@conghai/nevable/index.exp?sdkVersion=39.0.0](https://exp.host/@conghai/nevable/index.exp?sdkVersion=39.0.0)

I not any change in my OTA Server except bundle file & upgrade version number

**Comment by ponikar** [comment]
### Environment - output of `expo diagnostics` & the platform(s) you're targeting

expo diagnostics

  Expo CLI 3.28.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.0 - E:\installedSetup\nodejs\node.EXE
      npm: 6.14.8 - E:\installedSetup\nodejs\npm.CMD
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    Expo Workflow: managed


### Reproducible Demo
try to run any expo project which as expo version 29 or 30.
command -> expo start
till now everything will be fine.
BUT when I try to run app on my android device or emulator it gets stuck and I have to wait for like a hour to buid the bundle.

I think JS bundle won't start to build

### Expected Behavior vs Actual Behavior

Application should be run on EXPO client.

But 

got stuck on  New update available downloading.

Thanks

**Comment by ponikar** [comment]
also I have added this line in my app.json
  "updates": {
      "fallbackToCacheTimeout": 0
    },
after reading the documentation, But it won't worked

**Comment by badbod99** [comment]
Having this issue also, seems to occur on iOS only, the message remains on the device screen sometimes even when JS already downloaded and running.  Intermittent.

**Comment by ezrul19** [comment]
I'm having the same issue here. Only happens when trying to run the expo on an iOS device. It does work fine when the app is fully built into TestFlight.

**Comment by ponikar** [comment]
I am having this issue on android and iOS both when I run expo start......

**Comment by ponikar** [comment]
@brentvatne any luck to resolve this problem! I mean what if I update my expo SDK to 40 (the latest one). Will it solve the problem?

**Comment by janisdimants** [comment]
Having the same issue! It's been extremely inconsistent for me today, with most of the time getting stuck on blank screen with the "New update available, downloading..." screen. If it's of any help, running on macOS, connected device is S20FE

**Comment by ponikar** [comment]
Hi @janisdimants, Well I forgot the mention my issue got solved by update Expo SDK from 39 to 40! I would suggest you upgrade your SDK.

**Comment by DatConley** [comment]
Same problem, trying to run sdk 40 on android emulator

**Comment by brentvatne** [comment]
this is just a generic thing that can happen when your app isn't starting. it is freezing on the loading screen. try usual debugging techniques to get your app running, then add code back until you find what's causing it.
