### ISSUE TITLE
[exp] Android: There was an error with this build

### ISSUE THREAD

**Issue by affanshahab** [expo/expo#1115]
I have been trying to build for android lately but no luck.

$ exp build:android
[exp] Making sure project is set up correctly...
/[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Starting build process...
[exp] Unable to find an existing exp instance for this directory, starting a new one...
[exp] Warning: Problems validating asset fields in app.json. See https://docs.expo.io/
[exp]  • Field: icon - cannot access file at './assets/icons/appicon.png'.
[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Starting React Native packager...
[exp] Scanning folders for symlinks in D:\xxxxx\xxxxx\AllMedical\App\node_modules (23ms)
[exp] Loading dependency graph.
[exp] Successfully ran `adb reverse`. Localhost urls should work on the connected Android device.
[exp] Error starting tunnel: Error: Starting tunnels timed out
[exp] Publishing...
[exp] Building iOS bundle
[exp] Tunnel connected.
[exp] Dependency graph loaded.
[exp] Finished building JavaScript bundle in 44526ms.
[exp] Building Android bundle
[exp] Finished building JavaScript bundle in 55816ms.
[exp] Analyzing assets
[exp] Finished building JavaScript bundle in 36193ms.
[exp] Finished building JavaScript bundle in 33725ms.
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://exp.host/@xxxxxx/xxxxxx

[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: 93916730-bd9d-4b6e-b15e-ffb85285cf8d
[exp] Run `exp build:status` to monitor it.

It just stays there forever.

Running exp build:status result below.

$ exp build:status
[exp] Making sure project is set up correctly...
-[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] Android: There was an error with this build.

**Comment by ajinkyaDivekar** [comment]
Hi
1.exp build: android => take much time to build .apk
2.exp build: status =>  after  few minute get result and Signed apk

[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] Android:
[exp] APK: https://***************.com/android%2F%40*******%2F************-8f905407-***********-signed.apk

**Comment by quinlanj** [comment]
hey @ajinkyaDivekar , from your last post, it looks like you managed to get the apk s3 link. I'm going to go ahead and close this issue, but if you have any more problems, please do post on forums.expo.io!

**Comment by quinlanj** [comment]
@affanshahab i looked up your build id in our system, and it appears that your build failed because one of your images is not of `png` format. In particular, the error message we are getting is: `APT err(Facade for 1364583577) : No Delegate set : lost message:libpng error: Not a PNG file`. If you use the `file` command, you can verify that an image is indeed `png` formatted (ie) https://linux.die.net/man/1/file

**Comment by thechori** [comment]
Just wanted to chime in here as well, I had the same issue as the OP. I think it'd be extremely helpful if the error message let us know that the file needs to be a .png. When I had originally uploaded a .png with transparency to TestFlight via Application Loader, I was informed that the image could not contain transparency. 

I interpreted this message as it wanted a .jpg instead (maybe this is an error on my part?). But then upon changing the .png to a .jpg, Expo was giving me the following error:

> [12:47:51] Error: Problems validating asset fields in app.json. See https://docs.expo.io/
> [12:47:51]  • Field: icon - cannot access file at './assets/icon.jpg'.

Just a suggestion. Keep up the great work Expo team!
