### ISSUE TITLE
node_modules/react-native-unimodules/gradle.groovy (No such file or directory)

### ISSUE THREAD

**Issue by stephengladney** [expo/expo#11157]
We recently upgraded from SDK 35 to 36 in our ejected app. 

We were getting this error when trying to generate a new APK from Android Studio:
`android.support.annotation does not exist` 

So we followed the instructions quoted below. However, now we're getting the following error:
`node_modules/react-native-unimodules/gradle.groovy (No such file or directory)`

BEGIN QUOTED INSTRUCTIONS:

@i7soft Yeah. It's a bit of a mess. react-native 0.60+ uses AndroidX. And expo hasn't been migrated to use AndroidX.

I found the proper solution here: https://github.com/react-native-community/discussions-and-proposals/issues/129#issuecomment-507010053

It's really simple.

Add `jetifier` to your `package.json` dev-dependencies:

```npm install jetifier --save-dev```

Then add this to your scripts section in your `package.json` file:

```"postinstall": "jetify"```

So your `package.json` should look something like this:

```json
{
	"name": "app",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"postinstall": "jetify"
	},
	"dependencies": {
		"react-native": "0.60.5",
		"react-native-unimodules": "^0.7.0-rc.1"
	},
	"devDependencies": {
		"jetifier": "^1.6.4",
	}
}
```

Then run `npx jetify` in the same folder as your `package.json`.

Now you can properly compile your android app. The next time you run `npm install` the `jetify` command will be run automatically.

_Originally posted by @kkirby in https://github.com/expo/expo/issues/5821#issuecomment-538026959_

**Comment by stephengladney** [comment]
Deleting `node_modules` and running `npm install` seems to have resolved. Closing issue.

**Comment by dorianmariefr** [comment]
That didn't fix it for me
