### ISSUE TITLE
Issue with Clipboard after migrating to react-native-community/clipboard

### ISSUE THREAD

**Issue by raRaRa** [expo/expo#11156]
Hey all.

So I noticed this warning when I was importing `Clipboard` from `react-native`:

> Clipboard has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from @react-native-community/clipboard instead of 'react-native'

I thought I could just migrate, but when I use Clipboard from that package I get the following error:
`null is not an object (evaluating 'NativeClipboard_1.default.getString')`

when performing the following call:
`const text = await Clipboard.getString()`

I've tried removing the `node_modules` folder and doing a clean install. I'm using Expo 39.0.5.

**Comment by AdamJNavarro** [comment]
Hey @raRaRa, if your project is using the Managed workflow this won't be possible as the rn-community clipboard module is not part of the Expo SDK. If you are using the Bare workflow, you'll be able to use the module however.

Cheers,
Adam

**Comment by raRaRa** [comment]
Since it's being removed from 'react-native', wouldn't it make sense to add support for it to avoid Clipboard being broken in future versions?
