### ISSUE TITLE
Any plans for lock screen widget for audio/video player?

### ISSUE THREAD

**Issue by damilolah** [expo/expo#11151]
Hi Expo, 

Happy Thanksgiving 🦃 
Thanks for all you do!
Are there any plans to implement this feature?
👇🏽
https://expo.canny.io/feature-requests/p/add-react-native-music-control

Thanks again 😀

**Comment by AdamJNavarro** [comment]
Hey @damilolah, Happy Thanksgiving to you as well. We appreciate the kind words! We do not have any active plans to implement said feature at this time. Hope you have a great weekend!

Cheers,
Adam
