### ISSUE TITLE
error implementing relay modern: graphql: Unexpected invocation at runtime.

### ISSUE THREAD

**Issue by daniloab** [expo/expo#11154]
###  🐛 Bug Report
I'm trying to implement relay modern in my project. I'm following the instructions from relay.dev. I have a repo that uses rn-cli and works well.

But, at expo I'm getting the following error:
<img width="340" alt="Screen Shot 2020-11-26 at 21 56 49" src="https://user-images.githubusercontent.com/19939822/100489673-79e2eb00-30f4-11eb-8ce9-9a2cc19ad41d.png">

### Reproducible Demo
repo to reproduce the error https://github.com/daniloab/b4a-expo-app

only needs:

yarn

yarn start & yarn ios/android

when trying to build get the error above mentioned

**Comment by brentvatne** [comment]
this is better suited for forums: https://forums.expo.io

the issues are intended for bug reports where you can provide a minimal reproducible example without introducing a third party library

**Comment by brentvatne** [comment]
i tried to run the app that you provided, out of curiosity, and saw this error:

```
Opening on iOS...
Opening exp://127.0.0.1:19001 on iPhone 11 Pro

Press ? to show a list of all available commands.
Failed building JavaScript bundle.
The package at "node_modules/babel-plugin-relay/lib/compileGraphQLTag.js" attempted to import the Node standard library module "crypto". It failed because the native React runtime does not include the Node standard library. Read more at https://docs.expo.io/workflow/using-libraries/#using-third-party-libraries
```

so i can't get to the same error that you've mentioned above. i also looked in the relay docs and they only mention react-native in one place, and it's not related to installation and configuration. i also can't find any up-to-date guides on how to set it up in react-native elsewhere.

**Comment by brentvatne** [comment]
i removed this line from your app: `import graphql from 'babel-plugin-relay/macro';`

this fixed it for me. you can't use this macro in react-native env because it requires that you import crypto, so you'd have to polyfill that if you wanted to. but there's no need because it seems to just be an alternative to using the relay babel plugin, which you already installed and configured.

![Screen Shot 2020-11-27 at 4 32 58 PM](https://user-images.githubusercontent.com/90494/100490165-38d7e000-30ce-11eb-95a1-d089b984e5f4.png)

**Comment by daniloab** [comment]
do you remove this line and works without any import? This was a tried to fix based on this issue https://github.com/facebook/relay/issues/2206. But, the common use is import from `react-relay` lib.

**Comment by daniloab** [comment]
yeah, I removed the same line without imports, and works well. Does Expo handle graphql tag? Anyway, thanks!

**Comment by brentvatne** [comment]
@daniloab - no, my understanding is that is what babel-plugin-relay is for
