### ISSUE TITLE
[expo-media-library][bare workflow] createAssetAsync doesn't work on Android 10.

### ISSUE THREAD

**Issue by yaroslavnikiforov** [expo/expo#11165]
### Summary of Issue 
I have an issue using `MediaLibrary.createAssetAsync(uri)` on Android - it always returns an error `[Error: Unable to copy file into external storage.]`. This happens on Xiaomi Redmi Note 7 (tested on two similar devices with Android 10) but works on Xiaomi Redmi Note 8 (Android 9) and on other our team members' devices with Android 9.

### Environment 
| software         | version
| ---------------- | -------
| react-native | ~0.63.3
| react-native-unimodules | ~0.11.0
| expo-media-library | ^9.2.1
| expo-camera | ^9.0.0
| platform OS | Android
| device | Xiaomi Redmi Note 7
| Android version | 10

### Reproducible Demo

[https://github.com/yaroslavnikiforov/ExpoMediaLibraryDemo](https://github.com/yaroslavnikiforov/ExpoMediaLibraryDemo)

**Comment by yaroslavnikiforov** [comment]
Here is a temporary solution:
[https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage)

**Comment by thomas-blitzm** [comment]
@AdamJNavarro any particular timeline for this fix?

**Comment by brentvatne** [comment]
@thomas-blitzm @yaroslavnikiforov - pull request welcome!

**Comment by enesakin1** [comment]
Fixing this would be appreciated. The issue still exists.
