### ISSUE TITLE
AppAuth Semantic and Parse Issue are breaking my IOS build

### ISSUE THREAD

**Issue by omorhefere** [expo/expo#1116]
I have detached to expokit in order to use the payment API but I have not been able to build the project. I always get 13 errors. 

I posted the issue on the forum: https://forums.expo.io/t/i-cant-build-my-ios-app-after-i-detach-to-expokit/5537

I checked this post: https://github.com/expo/expo/issues/712 but the fix suggested here has already been added to expo

Here's my StackOverflow question: https://stackoverflow.com/questions/47824744/appauth-semantic-and-parse-issues-are-breaking-build-of-react-native-project-in

Xcode version - 8.3.3
My project targets IOS version 10

**Comment by terribleben** [comment]
What version of Xcode are you using and what version of iOS does your project target?

**Comment by omorhefere** [comment]
@terribleben hi,
Xcode version - 8.3.3
My project targets IOS version 10

**Comment by terribleben** [comment]
Cool. Can you update to Xcode 9.x? That API was introduced in iOS 11, so you need the latest SDK to at least exist before Xcode understands how to handle those method calls.

Closing, but let me know if you still have an issue after updating Xcode.

**Comment by omorhefere** [comment]
@terribleben Thankyou, I updated it an no longer get that error. I get a new one with expokit.
" No visible @interface for 'RCTAsyncLocalStorage' declares the selector 'initWithStorageDirectory:'"
In package.json i am not using the expo fork of react native as i get an error anytime i try to install it. I use "0.51.0" could this be causing a problem?
I am using sdk 24

**Comment by omorhefere** [comment]
That was the problem when I used yarn to install expo's fork of react native everything was solved
