### ISSUE TITLE
Expo root view visible when rotating device or switching screens

### ISSUE THREAD

**Issue by badbod99** [expo/expo#11162]
#10971  🐛 Bug Report

### Summary of Issue 

Expo specifies the color of the root view in the app.json, e.g. `"backgroundColor": "#FFFFFF",`.  The default is white.  When your app supports dark and light themes, this root view shows through on iOS when rotating the device or switching screens (e.g. with React Navigation).  This does not seem to occur on Android.  Setting an black background View at the top level of your application does not resolve this issue.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
$ expo diagnostics
[09:48:43]
  Expo CLI 4.0.1 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

### Reproducible Demo

[Minimal demo project on github](https://github.com/badbod99/ExpoRootViewColor10971).

### Steps to Reproduce

Occurs in any new project where dark and light themes are available.  Basic steps:

1. expo init
2. expo install react-native-appearance
3. implement useColorScheme or your own logic for selecting theme
4. set the main view background to the theme's color
5. test your app on iOS

### Expected Behavior vs Actual Behavior

Expected: Backgound color of theme should show when changing screens or rotating device
Actual: Root view color (default white) shows when rotating or changing screens

It is not a solution to set the backroundColor in app.json to a different color, as the theme is user selectable.  Whatever color you hardcode in app.json will be different than the user's chosen theme unless they happen to pick the same.

**Comment by brentvatne** [comment]
hi there! thanks for following the issue template. let's continue this discussion in https://github.com/expo/expo/issues/10435

**Comment by brentvatne** [comment]
actually, given that this is specifically about ios and managed workflow let's keep this one open

**Comment by badbod99** [comment]
Thanks for your response @brentvatne.  Yes, that's the behaviour I am seeing.  Might apply on Android also, but apparently not with my device.  I'm running with black as the background colour now, but on the _light_ theme, when navigating the screen momentarily flashes black.  The rotation issue isn't as noticeable with black background, but the flicker is very jarring.

**Comment by badbod99** [comment]
This is still an issue.

**Comment by brentvatne** [comment]
you can use the `backgroundColor` field in app.json to set the root view background color statically: https://docs.expo.dev/versions/latest/config/app/#backgroundcolor
you can use expo-system-ui to set the root view background color at runtime: https://docs.expo.dev/versions/latest/sdk/system-ui/

so i consider this issue resolved on our end

**Comment by badbod99** [comment]
@brentvatne - Thanks Brent, I wasn't aware of the new(ish) SystemUI API.  Looks like it will resolve the issue. 👍
