### ISSUE TITLE
deleteItemAsync not delete userInfo

### ISSUE THREAD

**Issue by yousss** [expo/expo#11164]
## 🐛 Bug Report
"expo": "~39.0.2",
"expo-secure-store": "~9.2.0",

import * as SecureStore from 'expo-secure-store';

const removeToken = async () => {
  console.log('rest1')
  try {
    await SecureStore.deleteItemAsync('userInfo')
  } catch (error) {
    console.log('rest2', error)
  }

}
### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.28.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

**Comment by byCedric** [comment]
Hi @yousss, thanks for the issue report. Unfortunately, I can't repro this on my end. Could you provide either a snack or repository where this happens for you?
