### ISSUE TITLE
[docs] Set up meta tags for Facebook / Twitter sharing

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#11178]
😱 

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdocs.expo.io%2F
https://cards-dev.twitter.com/validator

**Comment by Simek** [comment]
Is this issue still valid? The docs pages in testers doesn't look that bad. 🙂 

Maybe there is something which you want to improve with those share cards?

**Comment by brentvatne** [comment]
yeah this is done now :)
