### ISSUE TITLE
After expo eject, expo publish, app stuck at splash screen.

### ISSUE THREAD

**Issue by YuntongLi6543** [expo/expo#11174]
After expo eject, expo publish, app stuck at splash screen (IOS). 

1. No error in dev mode. 
2. Using Expo SDK 39.0.4
3. Searched reletive problem, like expo-splash-screen, did not solve this problem.

Any tips or debug method I can try?

**Comment by brentvatne** [comment]
please follow issue template and create a new issue, thanks!
