### ISSUE TITLE
[docs] Haptics docs say that Android VIBRATE permission will be added automatically, but it's not if you manually list permissions in app.json

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#11172]
It sounds implied from the [Haptics doc](https://docs.expo.io/versions/latest/sdk/haptics/) as well as the general [Permissions Doc](https://docs.expo.io/versions/latest/sdk/permissions/) that the `VIBRATE` permission request would be automatically added to an app using the managed workflow if it imports `Haptics`, even if it's not included under `app.json`'s `android.permissions` key.

**Comment by AdamJNavarro** [comment]
Hey @Slapbox, if you manually configure your array of android permissions in `app.json` then it is expected that permissions will no longer be added automatically (aside from the `Minimum Necessary` list of permissions) so the behavior here is correct.

We can definitely do a better job clarifying that on the `Haptics` module page and I'm guessing we might have other module pages that say something similar that we should clarify as well. Thanks for bringing this to our attention!

Cheers,
Adam

**Comment by Slapbox** [comment]
Makes sense, thanks for the clarification!

**It looks like the other affected pages are:**

- [MediaLibrary](https://docs.expo.io/versions/latest/sdk/media-library/)
- [Notifications](https://docs.expo.io/versions/latest/sdk/notifications/)
- [Network](https://docs.expo.io/versions/latest/sdk/network/)
- [ImagePicker](https://docs.expo.io/versions/latest/sdk/imagepicker/)
- [BackgroundFetch](https://docs.expo.io/versions/latest/sdk/background-fetch/)

[as determined with a Google search](https://www.google.com/search?q='site:https://docs.expo.io/versions/latest/sdk/ "added automatically"')

**Comment by brentvatne** [comment]
@Slapbox - can you point to the exact wording that you found confusing? i think the behavior is fairly straightforward and so we must not be explaining it well enough - if you don't specify `android.permissions` in app.json, then the permission will be included automatically. if you do specify `android.permissions`, then it is up to you to pick which permissions to include.

**Comment by Slapbox** [comment]
Hey @brentvatne

**Comment by Slapbox** [comment]
Hey @brentvatne, it makes total sense in retrospect, taking the Permissions doc as the superseding doc, and if you interpret minimum as absolute minimum to run Expo, and not minimum to run your app. If you take the sentences at face value on Haptics and the other pages then it's a bit misleading. It could benefit from a few extra words to clarify.

**Currently:**

> On Android, this module requires permission to control vibration on the device. The VIBRATE permission is added automatically.

This seems to state that if you import the module, it *will* be added, period. I interpreted this to be included in what constituted the "minimum" permissions.

I'd suggest updating the language to something like:

> On Android, this module requires permission to control vibration on the device. The VIBRATE permission is added automatically unless you're managing permissions yourself in your app.json under `android.permissions`.

That might not be the *best* wording, and I'm not sure it's correct for the Bare Workflow, but I think that it would be more clear.

The only thing that really makes it a pain to misinterpret is that you won't notice your mistake until you've gone through the entire build/deploy/review process.

**Comment by EvanBacon** [comment]
Technically the VIBRATE permission is always added via the [`AndroidManifest.xml`](https://github.com/expo/expo/blob/27822831ad462b5d8cf1398ee74c60f7248bfe42/packages/expo-haptics/android/src/main/AndroidManifest.xml#L4). The only way to remove it would be to use `tools:node="remove"` https://developer.android.com/studio/build/manage-manifests or to simply not include the module.
