### ISSUE TITLE
 After expo eject, expo publish, app stuck at splash screen (IOS)

### ISSUE THREAD

**Issue by YuntongLi6543** [expo/expo#11175]
### Summary of Issue

After expo eject, expo publish, app stuck at splash screen (IOS).

1.  No error in dev mode.
2. Using Expo SDK 39.0.3
3. Searched reletive problem, like expo-splash-screen, did not solve this problem.

Any tips or debug method I can try?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 4.0.4 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD   
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.4 
      react-native-web: ~0.13.14 => 0.13.14 
    Expo Workflow: bare

### Reproducible Demo

  "dependencies": {
    "expo": "^39.0.3",
    "expo-splash-screen": "~0.6.2",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.3",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-reanimated": "~1.13.1",
    "react-native-screens": "~2.10.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.14",
    "@expo/vector-icons": "^10.2.1",
    "@react-native-community/async-storage": "~1.12.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.9.0",
    "@react-navigation/native": "^5.7.4",
    "@react-navigation/stack": "^5.9.1",
    "axios": "^0.20.0",
    "expo-cli": "^3.27.14",
    "expo-localization": "~9.0.0",
    "graphql": "^15.3.0",
    "i18n-js": "^3.7.1",
    "lottie-react-native": "~2.6.1",
    "node": "^14.12.0",
    "react-native-auto-height-image": "^3.2.2",
    "react-native-paper": "^4.2.0",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^2.15.1",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  },

**Comment by brentvatne** [comment]
that's not a reproducible demo.. please see https://stackoverflow.com/help/minimal-reproducible-example

**Comment by brentvatne** [comment]
from the issue template:

> - This should include as little code as possible, please don't simply link your entire project
> - Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
> - If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
> - If you need more guidance, please see https://stackoverflow.com/help/mcve
> As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

sorry for closing the issue again but you really do need to follow the issue template to get help

**Comment by YuntongLi6543** [comment]
I think in this situation I need to put my entire code on, but that's too much for this. I don't know which part of the code is wrong, the only clue I have is that I may use undefined object before expo eject, but everything works fine. Also, it works fine in simulator after eject. The problem is after build to standalone app or expo publish, app cannot be opened. But undefined object is only my guess, I have to fine a way to fine out what's going on in the publish process.

**Comment by YuntongLi6543** [comment]
> 
> 
> from the issue template:
> 
> > * This should include as little code as possible, please don't simply link your entire project
> > * Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :)
> > * If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
> > * If you need more guidance, please see https://stackoverflow.com/help/mcve
> >   As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!
> 
> sorry for closing the issue again but you really do need to follow the issue template to get help

Thanks for the replay, if you can see my comment we can go from there. You can close this issue, but that's not my way out of here.

**Comment by brentvatne** [comment]
we don't provide one on one support for problems that are not clearly demonstrable issues, otherwise we would have no time for development of expo. i'd suggest posting to https://forums.expo.io/ to get help from the community if are unable to create a minimal reproducible example

**Comment by YuntongLi6543** [comment]
> 
> 
> we don't provide one on one support for problems that are not clearly demonstrable issues, otherwise we would have no time for development of expo. i'd suggest posting to https://forums.expo.io/ to get help from the community if are unable to create a minimal reproducible example

Thanks for the reply, I will give a try on that.
