### ISSUE TITLE
expo-local-authentication: Is Local Authentication secure?

### ISSUE THREAD

**Issue by JeffreyLeeDave** [expo/expo#11186]
So I was reading an article [here](https://www.freecodecamp.org/news/how-to-implement-secure-biometric-authentication-on-mobile-devices-4dc518558c5c/) and it mentioned code a line of code that belongs in the react-native-touchid:

`evaluatePolicy:localizedReason:reply:^(BOOL success, NSError *error)`

My understanding is that this relies on Local Authentication and that it is an issue because "There have been reports of the possibility to bypass Local Authentication by sending a success signal to Apple’s APIs on jailbroken or non-jailbroken iOS devices"

So how does this relate to this package? Well when I looked at the react-native-touchid source code, I didn't see this line verbatim, but I saw code that looked like it. Similarly I see code that looks like it in this package as well

```
[context evaluatePolicy:LAPolicyDeviceOwnerAuthenticationWithBiometrics
          localizedReason:reason
                    reply:^(BOOL success, NSError *error) {
                      resolve(@{
                                @"success": @(success),
                                @"error": error == nil ? [NSNull null] : [self convertErrorCode:error],
                                @"warning": UMNullIfNil(warningMessage),
                                });
                    }];
```

While technically this is only an issue with jailbroken phones, how much do we think this is a security risk for this package?

**Comment by byCedric** [comment]
Hi @JeffreyLeeDave! If the device is jailbroken, there are a lot of security implications going on. Yes, if they can spoof security checks it's not as secure as you might want it to be. But if I look at what API we expose and how you can use it, I don't see a relevant attack vector that might cause this library to be insecure for developers.

If you take the use case of a banking app for example. You might be able to install the app on a jailbroken device. But local authentication alone doesn't give you access to any accounts. It only serves as a check to see if the owner or registered user of the device is accessing the account. It still needs to have secure API access to the server and most probably requires activation by the owner of the banking account before you can access it.

If you do know an attack vector that might be troublesome, lmk!

**Comment by JeffreyLeeDave** [comment]
Well, take this article [here](https://medium.com/swlh/integrate-biometric-authentication-to-your-expo-app-77252d041f5). People use this library to see if someone successfully authenticated with biometrics. And upon success, they will log the person in to the app. In a jail broken phone, if an attacker can fake a success, they can login to the app. I am by no means an expert on security, but this to me seems like a possible attack vector

**Comment by jakubboguski** [comment]
Related https://github.com/expo/expo/issues/14456
