### ISSUE TITLE
expo-av: Video is not looping forever

### ISSUE THREAD

**Issue by Shing-Ho** [expo/expo#11187]
### Summary of Issue 
The video is showing only once or twice and it's not showing at all.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.3/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.44 
      expo: ^39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.3.9 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

### Reproducible Demo
https://snack.expo.io/@talentexpo/video-test
 
### Steps to Reproduce
Just open this snack

### Expected Behavior vs Actual Behavior
Video should loop forever

**Comment by byCedric** [comment]
Hi @Shing-Ho, thanks for the issue report. Unfortunately, the snack you provided is working fine on my OnePlus 6 (Android 10). I let it loop for 2 minutes so I'm not sure what's going on here. 

One factor that might be causing the video "not to show" could be related to the `.m3u8` file extension you used. I don't think there is a lot of support for this type of video, e.g. look at [chromecast supported file types](https://developers.google.com/cast/docs/media#media_container_formats). On web, this could result in the video not displaying.

Hope this helps!

**Comment by Shing-Ho** [comment]
@byCedric Thank you for your comments. It's not working well in iOS

**Comment by Shing-Ho** [comment]
@byCedric Please check my snack again in the ios. It's playing two or three times only even it's autoplay set. But it should be play forever. This is the bug that I am trying to report you guys. Please check and let me know anytime!

**Comment by BraveLilToaster** [comment]
I am also on iOS and experiencing the same issue that @Shing-Ho raised above. My video is a `.m3u8` file and play three times and then goes blank.
