### ISSUE TITLE
expo-auth-session: can't switch Google accounts

### ISSUE THREAD

**Issue by amhouel** [expo/expo#11182]
### Summary of Issue
Using useAuthRequest with Google provider and with selectAccount param set to true I am able to select an account and get the account info the first time I do it but when I try to switch accounts I keep getting the first selected account information instead of the newly selected account's info.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed

Targeting Web

### Reproducible Demo

https://github.com/amhouel/expo-auth-session-google
![Screen Recording 2020-12-02 at 9 51 58 AM](https://user-images.githubusercontent.com/32083935/100889821-95981980-3485-11eb-8d2e-1ed1118fcfa7.gif)

 
### Steps to Reproduce

1/ click on the "Select Account" button and select a google account when prompted
2/ see the account email address display
3/ click on the "Select Account" button and select a different account when prompted
4/ see the account email address display - which will the same as the 1st one

### Expected Behavior vs Actual Behavior

Expected behavior: see the account info change as you change accounts.
Actual behavior: we keep getting the info of the account we first selected.

**Comment by brentvatne** [comment]
can you record a video of this and share it here? it'll be a bit easier to understand than setting up an app for it, would be much appreciated :)

**Comment by amhouel** [comment]
@brentvatne no worries, I've just added a video. thanks!

**Comment by imnotjames** [comment]
I think I've run into this issue as well.

Seems that per the Google provider there's no case in which a new AuthResponse can ever propagate down

https://github.com/expo/expo/blob/6621638281ef914d13567304c914e4d360fb581d/packages/expo-auth-session/src/providers/Google.ts#L359

You can check to see if the PR that I opened helps with this problem https://github.com/expo/expo/pull/11503

**Comment by fawzibazari** [comment]
Hello,
i find a solution for expo go app running on IOS simulator
you should add to your useAuthRequest config 
`selectAccount: true,
      shouldAutoExchangeCode: false`
for me it works
