### ISSUE TITLE
Enabling turbo modules breaks Blobs

### ISSUE THREAD

**Issue by sospedra** [expo/expo#11194]
### Summary of Issue 

If `turboModules` is enabled Blobs don't work

### Environment

<details>
<summary>env</summary>

```
  Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.asdf/installs/nodejs/12.13.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.asdf/installs/nodejs/12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /Users/sagan/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed
```

</details>

### Reproducible Demo

Here's a demo: https://github.com/sospedra/expo-blob-error-demo
The demo is branched off your example: https://github.com/expo/examples/tree/master/with-firebase-storage-upload
 
### Steps to Reproduce

1. At `app.json` set `experiments.turboModules: true`
2. Try to use any Blob
3. This error will throw: `Native module BlobModule is required for blob support`

To double-check, set the `turboModules: false` and try again. It'll work.

### Expected Behavior vs Actual Behavior

Blobs should behave equally regarding if turbo modules are enabled or not.

**Comment by byCedric** [comment]
Hi @sospedra! Thanks for the issue report with example! Unfortunately, I can't reproduce the error you mentioned related to turbo modules. I did find some issues related to UUID and had to add the [`react-native-get-random-values` workaround described here](https://github.com/expo/expo/issues/7209#issuecomment-712229139).

On what device(s) and/or OS versions are you running into this issue?

**Comment by sospedra** [comment]
Using the expo app in a simulator

Host: `macOS 10.15.7`
Sim: `Version 11.7 (921.9.1)`
Node: `12.13.0`
Yarn: `1.22.4`

I'm shipping a new app -- currently in closed Beta -- where we're experiencing this issue in standalone apps; as well.

**Comment by sospedra** [comment]
Here's a video demo: https://i.imgur.com/keCml4e.mp4

**Comment by brentvatne** [comment]
in sdk 40 you won't need to enable turboModules in order to use reanimated 2, so this won't be an issue.

further, this is an issue on the react-native side so it would be good to post an issue there: https://github.com/facebook/react-native/issues

**Comment by brentvatne** [comment]
by the way, thank you for the excellent issue report, we do really appreciate the effort that you put into it.

**Comment by stanleyugwu** [comment]
On `SDK 49`, setting this flag to true `turboModules: true` caused my app to show blank/white screen on iOS on Expo Go
