### ISSUE TITLE
SDK40 can't handle yarn workspaces

### ISSUE THREAD

**Issue by thgh** [expo/expo#11195]
### Summary of Issue 
When upgrading to SDK40 (or setting `EXPO_USE_DEV_SERVER=true`) workspaces cannot access react native dependencies. In my case AsyncStorage. It seems to build the dev version fine, but when running on simulator and device I get:

    Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Target: Android + iOS
```
  Expo CLI 4.0.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0-beta.2 => 40.0.0-beta.2
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.6
    Expo Workflow: bare => it's managed actually
````

### Reproducible Demo
TODO, can I do this later?

 
### Steps to Reproduce
Create an Expo 39 project
Add expo-yarn-workspaces
Add this script in package.json: `    "postinstall": "expo-yarn-workspaces postinstall"`
Add `  "workspaces": ["packages/*" ],`
Add package in `packages/example` that uses AsyncStorage 1.12
Import `packages/example` in App.tsx
`expo start` => works as expected
Upgrade to Expo 40 (or run `export EXPO_USE_DEV_SERVER=true`)
`expo start`
Open on device => error

### Expected Behavior vs Actual Behavior
Expected: App runs like before
Actual: Error when running on device/simulator: `Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null`

Note: it might be expo-cli related

Related: https://github.com/expo/expo-cli/pull/2921#issuecomment-735694016

**Comment by brentvatne** [comment]
it can definitely still handle yarn workspaces because we use it in this very repository with dev server enabled and have done so for a while! so, a reprodicible example will be very important here

**Comment by brentvatne** [comment]
my suspicion: something is causing this project not to be detected as a managed project. if you are getting `Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null` it means that [RCTAsyncStorage.expo.js](https://github.com/react-native-async-storage/async-storage/blob/master/src/RCTAsyncStorage.expo.js) is not being loaded, which means that the `.expo` extension isn't being included in your project, or you are overriding the `sourceExts` and not including `expo`

**Comment by thgh** [comment]
I tested out ejecting some time ago and somehow still had an `ios` folder which was gitignored. After removing the folder, everything works fine!

**Comment by brentvatne** [comment]
@thgh - thanks for following up!

**Comment by ahmed2m** [comment]
@brentvatne
Can the npm v7 's  workspaces be handled with the same `expo-yarn-workspaces` ?

**Comment by brentvatne** [comment]
probably not, expo-yarn-workspaces is meant for usage with yarn. the principles should be the same, so you could look at the source and figure out how to build similar tools for npm workspaces. i'd recommend using yarn workspaces instead because they are much more established at this point

**Comment by nandorojo** [comment]
FWIW, after upgrading I seem to also be facing some issues with `expo-yarn-workspaces`. It seems like my packages are installing to the incorrect place. I'll try to get a repro made if I can figure out what's causing it. 

The problem:

After running `expo upgrade`, and then `yarn install` inside of the app's package folder, certain packages are installing in the local package folder's `node_modules`, instead of in the global workspace's `node_modules`. This is a new phenomenon, and I'm not sure why it's happening. 

It seems like the `node_modules` folder in my app's package is actually installing everything into that folder, instead of symlinking to the workspace's `node_modules`. I'll create a more fleshed out issue once I reproduce this, but I figured I'd write in case someone has seen something similar.

**Comment by brentvatne** [comment]
hey @nandorojo - we didn't make any changes that would impact this in sdk 40. let me know if you find more information about what caused it, if it's on our end

**Comment by nandorojo** [comment]
Will do. My best guess is it's something happening to `yarn.lock` when Expo upgrades all the packages. Is there a way to manually do what `expo upgrade` does so I can debug more easily?

Thanks @brentvatne!

**Comment by nandorojo** [comment]
@brentvatne just wanted to check above. I think the `expo upgrade` command is doing something odd to my packages. After running that command, everything installs in my package's `node_modules`, instead of to my workspace's `node_modules`.

Instead of `expo upgrade`, can I just upgrade the react-native and expo packages in package.json, or is there some other magic going on?

**Comment by nandorojo** [comment]
For context, I've located what causes the issue: 

`expo upgrade` upgrades `expo` from `^39.0.3` to `^40.0.0`. This change is, for some reason, responsible for packages installing in the wrong `node_modules` folder. If I change nothing other than reverting back to `^39.0.3`, everything works fine. Was there a significant change in `expo`'s dependencies or something like that, by chance?

**Comment by nandorojo** [comment]
I found the problem – I have 2 expo apps in my monorepo, and I only upgraded one of them from 39 to 40. When I upgraded both, it worked. 🤦‍♂️
