### ISSUE TITLE
BarCodeScanner [Unknown encoding]

### ISSUE THREAD

**Issue by youssame** [expo/expo#11193]
Hello guys,

BarCodeScanner add an `Unknown encoding` in the result when there is a string that contains accents.
Any help please ?

Thank you

**Comment by byCedric** [comment]
Hi @youssame, thanks for the issue report. Unfortunately, you didn't provide enough information for us to investigate this issue and help you further. If you think this is an issue with Expo, please create a new issue using the bug report template. It should contain a minimal reproducible example of the issue. With that, I'm happy to dig into it!

The QR code below contains the french phrase, with accents. This is getting picked up [by the example snack in the barcode scanner's docs](https://docs.expo.io/versions/v40.0.0/sdk/bar-code-scanner/#usage).
> La vie en France est très différente de celle au Canada. 
![Screenshot 2020-12-02 at 14 41 27](https://user-images.githubusercontent.com/1203991/100880101-a1e39d00-34ac-11eb-9e0d-7f90f80622cf.png)

Hope this helps!

**Comment by youssame** [comment]
Thank you for your response, I had the problem with QRCODE that contains zxing/zxing data.
