### ISSUE TITLE
Problems with exp build:ios

### ISSUE THREAD

**Issue by lbayarkhuu** [expo/expo#1120]
Hello expo team,
I'm having a trouble with building ios stand-alone app. I used exp build:ios -c and following error occurred:
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch push certificate. Request ID 041ff1e0-e15d-11e7-92cb-19727301b1b4, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by terribleben** [comment]
Hi there, sorry for the delay here. It looks like you managed to successfully build sometime yesterday, so I'll close this unless you are still blocked.

It seems like our build service was having trouble fetching your certs based on the Apple id and bundle id you provided, for whatever reason. Just curious, what did you do differently that fixed it? That would be helpful for us to know in case somebody else hits the same issue.

**Comment by lbayarkhuu** [comment]
I just created a new project and changed the bundle id :D
