### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by YuntongLi6543** [expo/expo#11201]
Hi, 

********************************* 
THIS IS NOT A ENTIRE PROJECT, IT IS JUST A NEW EXPO PROJECT WITH ONLY react-native-async-storage/async-storage INSTALLED, for anyone want to reproduce this, try master branch.

github source code here: https://github.com/Damon-Zhong/expo39-asyncstorage-bug/tree/master
**********************************

My problem is as follows:
1. Expo SDK 39.0.3
2. Project is in bare workflow with expo eject.
3. Async Storage is the only SDK used in the project, works fine in develop mode and simulator.
4. After expo publish, app stuck at splash screen, error is:
    [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null
5. manual link tried, not working.
6. react-native link tried, not working

If need any information, please let me know.

Thanks. Do need help.

**Comment by brentvatne** [comment]
just run `pod install` in the ios directory and that will fix it. if it doesn't, then post an issue to https://github.com/react-native-async-storage/async-storage

an ejected expo app is just like any react-native app but with some expo modules installed
