### ISSUE TITLE
InAppPurchases.getPurchaseHistoryAsync() promise never resolves on iOS

### ISSUE THREAD

**Issue by special-character** [expo/expo#11203]
### Summary of Issue 

When I call `InAppPurchases.getPurchaseHistoryAsync(true)` on iOS, the promise never resolves. It appears to be the only `InAppPurchases` function with this issue. I can fetch my subscription, purchase it, and have it successfully be called in the `setPurchaseListener` callback. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.23.0 - ~/.nvm/versions/node/v10.23.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v10.23.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native-web: 0.13.3 => 0.13.3 
```

### Reproducible Demo
I haven't been able to do this yet. It would/will require creating a new iOS app on apple and setting up a subscription to purchase which I haven't gotten to yet.
 
### Steps to Reproduce
Have a subscription and call `InAppPurchases.getPurchaseHistoryAsync(true)` on iOS.

### Expected Behavior vs Actual Behavior
The promise would resolve with some form of success or even an error.

I am following the JS code down to the native code to try and figure out where this is happening. For posterity, this is from a sandbox account and I haven't been able to test this in a "real" account yet since I haven't finished the purchase capability.

My function to test this out looks like:
```
const getPurchaseHistory = async () => {
      try {
        await InAppPurchases.connectAsync()

        console.log('A')
        // Calling with ignored param true because of this GH issue: https://github.com/expo/expo/issues/10332
        const { responseCode } = await InAppPurchases.getPurchaseHistoryAsync(
          false,
        )
        console.log('B')

        if (responseCode === InAppPurchases.IAPResponseCode.ERROR) {
          console.log('C')
        }
        await InAppPurchases.disconnectAsync()
      } catch (err) {
        console.log('D')
      }
    }
```
I can see the function hit `A` and nothing else. Setting breakpoints like I normally do confirmed that the promise never seems to resolve.

I also tested this directly in the `expo-in-app-purchases` module with the same result (nothing after `AA` being hit):

```
export async function getPurchaseHistoryAsync(refresh) {
    if (!connected) {
        throw new ConnectionError(errors.NOT_CONNECTED);
    }
    console.log('AA')
    const nativePromise = ExpoInAppPurchases.getPurchaseHistoryAsync(refresh);

    nativePromise.then((res) => {
        console.log('BB')
        return res
    }).catch(err => {
        console.log('CC', err)
    })

    return await nativePromise
}
```

**Comment by special-character** [comment]
Looking at the native code, there is a variable `promiseSet` which might not be getting set in my case somehow.

https://github.com/expo/expo/blob/d5aac8414a1e3e52c028d689b1d93a06cc256dd3/ios/versioned-react-native/ABI39_0_0/Expo/EXInAppPurchases/ABI39_0_0EXInAppPurchases/ABI39_0_0EXInAppPurchasesModule.m#L120

**Comment by special-character** [comment]
Trying again this morning and this call started returning. Not sure what changed but this is no longer an issue for me.

**Comment by jinghongchan** [comment]
I'm facing this issue

**Comment by AlenToma** [comment]
I am having the same issue in android. How should this be fixed?

**Comment by Santo-dev** [comment]
Facing the same issue on Android, it seems to occur randomly. Has anyone found a solution?

**Comment by halbano** [comment]
I am always receiving an empty array on Android, Is someone experiencing a similar situation?
