### ISSUE TITLE
Possibly add <CheckBox /> replacement library

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#11205]
### Summary of Issue 

React Native 0.64 removes the CheckBox component on Android, so we should build or include a replacement before we update to 0.64 *or* we should have some pure JS alternative.

Note that you can continue to use the `CheckBox` component from react-native on Android and web at least until and including SDK 40. `CheckBox` still exists in react-native-web at the time of writing.

**Comment by byCedric** [comment]
Done, see https://github.com/expo/expo/pull/11274
