### ISSUE TITLE
MediaLibrary getAssetsAsync Could not read file or parse EXIF tags

### ISSUE THREAD

**Issue by EngMustafaTaha** [expo/expo#11211]
I upgraded to SDK 39 and when I try to use MediaLibrary.getAssetsAsync() I get an error of Could not read the file or parse EXIF tags
this happened only in albums that have some images with a not valid EXIF.
All I need to select multiple images so I don't care about EXIF but I tried to add exif:false as an option but no luck.
 
"expo": "^39.0.0",
"expo-media-library": "^10.0.0",

**Comment by cruzach** [comment]
hi @EngMustafaTaha , please fill out the bug report template and include a reproducible demo and we're happy to reopen the issues and look into this

**Comment by usama-asfar** [comment]
Fix this issue by adding `android:requestLegacyExternalStorage="true" ` in manifest file

**Comment by EngMustafaTaha** [comment]
> I use expo-media-library with bare workflow I get the same error message and fix this issue by adding `android:requestLegacyExternalStorage="true" ` in the manifest file

Where I can add this line, I am using expo project without eject.

**Comment by usama-asfar** [comment]
> > I use expo-media-library with bare workflow I get the same error message and fix this issue by adding `android:requestLegacyExternalStorage="true" ` in the manifest file
> 
> Where I can add this line, I am using expo project without eject.

You can't edit the manifest file without ejecting

**Comment by cruzach** [comment]
Managed Expo projects add this line to androidmanifest by default https://github.com/expo/expo/blob/master/template-files/android/AndroidManifest.xml#L54

**Comment by mackan92** [comment]
Same issue here. Running Expo 41.0.0 and expo-media-library 12.0.2 in managed workflow. It's not possible to change AndroidManifest.xml if running project in managed workflow?

**Comment by maelthi** [comment]
Same issue with expo 42.0.1. Aren't there any solutions if we use the manage workflow ?

**Comment by ScareCrow95** [comment]
Were you guys able to figure out any solutions? I am on expo 42.0.0, and it's not working on android for managed workflow
