### ISSUE TITLE
Background image loads too slowly and appears only then when screen is already rendered. 

### ISSUE THREAD

**Issue by ArtyomBaykov** [expo/expo#1121]
When I include all the content inside <Image> (means image works as a View) that image loads to slow. When you navigate to that screen everything is there but image loads quite late and  that screen looks like very unprofessional because of that. I have many screens where   image used as a full screen background and all those screens have the same behavior. Is there any solution for this issue?

**Comment by terribleben** [comment]
Hi, I recommend downloading and caching your crucial assets when the app starts, and showing `<Expo.AppLoading />` until the app is completely ready to render. There is an example of this in the Expo [new project template](https://github.com/expo/new-project-template/blob/master/App.js#L13-L29). There is also a guide with more ideas about this [here](https://docs.expo.io/versions/latest/guides/offline-support.html). Hope that helps!

**Comment by ArtyomBaykov** [comment]
Thanks for replying @terribleben 
I am new in react native. I am a bit confused. Here is the code that I am using at the moment:

```
export default class App extends React.Component {
  constructor() {
    super();
    this.state = {
      appIsReady: false,
      mainApplication: false,
    };
  }
  async componentWillMount() {
    this._loadFontsAsync();
    this._cacheResourcesAsync();
  }
  async _cacheResourcesAsync() {
    const images = [
      require("./assets/icons/app.png"),
      require("./assets/icons/loading.png"),
      require("./img/img1.jpg"),
      require("./img/img2.jpg"),
      require("./img/img3.jpg"),      
    ];
    for (let image of images) {
      await Asset.fromModule(image).downloadAsync();
    }
  }
async _loadFontsAsync() {
    await Expo.Font.loadAsync({
     Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf"),
      Arial: require("native-base/Fonts/Roboto.ttf"),
      Roboto: require("native-base/Fonts/Roboto.ttf"),
      Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
   
    });
    this.setState({appIsReady: true});
  }
  render() {
    if (this.state.appIsReady) {
      return (

            <Nav/>
        
      );
    } else {
      return <AppLoading />;
    }
  }
}
```

Which parts must I remove and use the part mentioned in your example?

**Comment by ide** [comment]
@ArtyomBaykov I see couple of ways to improve the way your app loads. One is that your app is not waiting for the images to download before you set `appIsReady` to true -- it's waiting for only the fonts -- so if we wait for the images too, that may fix your issue.

Also, the `await` in a for-loop will be slow because the images will download in serial instead of in parallel. If you await all of the images together, that will probably be faster.

```js
  // Improved, but still has bugs

 async componentWillMount() {
    // Wait for both fonts and images
    await Promise.all([
      this._loadFontsAsync(),
      this._cacheResourcesAsync(),
    ]);
    this.setState({ appIsReady: true });
  }

  async _cacheResourcesAsync() {
    const images = [
      require("./assets/icons/app.png"),
      require("./assets/icons/loading.png"),
      require("./img/img1.jpg"),
      require("./img/img2.jpg"),
      require("./img/img3.jpg"),      
    ];
    // Asset.loadAsync takes an array and this way we can load the images in parallel
    await Asset.loadAsync(images);
  }

  async _loadFontsAsync() {
    await Expo.Font.loadAsync({
     Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf"),
      Arial: require("native-base/Fonts/Roboto.ttf"),
      Roboto: require("native-base/Fonts/Roboto.ttf"),
      Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
    });
    // We want to wait for images and fonts before setting the state
    // this.setState({appIsReady: true});
  }
```

However, there are still bugs in this code. If an image or font file fails to load, you will get an exception and never set `appIsReady`. The AppLoading component helps you handle failures better. The link Ben posted shows this:

```js

  // in render()
       <AppLoading
          startAsync={this._loadResourcesAsync}
          onError={this._handleLoadingError}
          onFinish={this._handleFinishLoading}
        />

...

  // other methods
  _loadResourcesAsync = async () => {
    return Promise.all([
      Asset.loadAsync([
        require("./assets/icons/app.png"),
        require("./assets/icons/loading.png"),
        require("./img/img1.jpg"),
        require("./img/img2.jpg"),
        require("./img/img3.jpg"),    
      ]),
      Font.loadAsync({
        Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf"),
        Arial: require("native-base/Fonts/Roboto.ttf"),
        Roboto: require("native-base/Fonts/Roboto.ttf"),
        Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
      }),
    ]);
  };

  _handleLoadingError = error => {
    // In this case, you might want to report the error to your error
    // reporting service, for example Sentry
    console.warn(error);
  };

  _handleFinishLoading = () => {
    this.setState({ appIsReady: true });
  };
```

**Comment by ArtyomBaykov** [comment]
Thanks a lot @ide  for your detailed message. I did as you said however the same trouble remains. When you navigate through the screens background image flashes like several mlili seconds background is white then background image appears.

**Comment by ide** [comment]
It might take time to render the image. You could try techniques like rendering the image before hiding AppLoading or fading in the image. This issue sounds more advanced and requires more investigation -- these are some consultants who could help you out: https://expo.io/consultants

**Comment by ArtyomBaykov** [comment]
@ide  last question: What do you think about this solution? I am asking it because documentation is not enough clear :(  I've got a recommendation to use this but there is an syntax error on the font's line and don't know why :( 

```
function cacheImages(images) {
  return images.map(image => {
    if (typeof image === 'string') {
      return Image.prefetch(image);
    } else {
      return Asset.fromModule(image).downloadAsync();
    }
  });
}

function cacheFonts(fonts) {
  return fonts.map(font => Font.loadAsync(font));
}

export default class App extends React.Component {
   constructor() {
    super();
    this.state = {
     isReady: false,
      store: configureStore(() => this.setState({ isLoading: false })),
      mainApplication: false,
    };
  }
  

  async _loadAssetsAsync() {
    const imageAssets = cacheImages([
     require("./assets/icons/app.png"),
      require("./assets/icons/loading.png"),
      require("./img/img1.jpg"),
      require("./img/img2.jpg"),
      require("./img/img3.jpg"),
      
    ]);

    const fontAssets = cacheFonts([
     Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf"),
        Arial: require("native-base/Fonts/Roboto.ttf"),
        Roboto: require("native-base/Fonts/Roboto.ttf"),
        Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),]);

    await Promise.all([...imageAssets, ...fontAssets]);
  }

 render() {
    if (!this.state.isReady) {
      return (
        <AppLoading
          startAsync={this._loadAssetsAsync}
          onFinish={() => this.setState({ isReady: true })}
          onError={console.warn}
        />
      );
    }
else {
    return (
      return  <Provider store={this.state.store}>
      <Root>
            <Main/>
            </Root>
</Provider>;
    );
  }
}
```

**Comment by andreh111** [comment]
hey guys try using this https://www.npmjs.com/package/react-native-fast-image 
it can solve the problem of image loading time

**Comment by kebernet** [comment]
@andreh111 Yeah, fast-image doesn't actually fix this particular class of problem as it seems to have the same state lifecycle as Image.

ProTip, though, if you skip doing appImg = require("./assets/icons/app.png"), and do 
import appImg from './assets/icons/app.png' 

You will get the image loaded as part of the script lifecycle itself, since require is a promise and all the import promises have to resolve before the file is considered loaded.

**Comment by GaryPlayer** [comment]
next time use
`this.setState({ appIsReady: true });`

**Comment by spedy** [comment]
I solved it by preloading the images with:

```
Expo.Asset.fromModule(require("../assets/castle_icon.png")).downloadAsync()
Expo.Asset.fromModule(require("../assets/tree_icon.png")).downloadAsync()
```

**Comment by simb4** [comment]
@spedy where did you put it exactly? In AppLoading ?
