### ISSUE TITLE
Network request failed on fetch DELETE (android only)

### ISSUE THREAD

**Issue by julste** [expo/expo#11215]
### Summary of Issue 

Fetching a request using DELETE method on Android raises TypeError: Network request failed. (IP used, not localhost)  
POST and GET request working on Android.
DELETE, POST, GET working on IOS. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 4.0.7 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.17.0 - /usr/local/bin/node
      npm: 6.14.9 - /usr/local/bin/npm
    npmPackages:
      expo: ^39.0.4 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ^0.13.18 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.7
    Expo Workflow: managed
```

### Reproducible Demo
      fetch(
        `http://serverIP/delete-user`,
        {
          method: "DELETE",
          body: JSON.stringify({
            user_id: user_id
          })
        })
        .then(() => {
          loadUser();
      });

**Comment by brentvatne** [comment]
hi there! this isn't a reproducible example. most likely this is a server issue. you can create a [minimal runnable reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and share it and i'll reopen the issue!

**Comment by julste** [comment]
I found the solution for my issue, just in case somebody ends here:

It wasn't about GET, POST or DELETE, but about the content-type. Only for Android I had to add `'Content-Type': 'application/json'` to my header, IOS works without defining the content-type.

**Comment by andrejpavlovic** [comment]
For me, the backend response to DELETE request was returning `204`. The issue was that there was content included in the response instead of being empty. The fix was to have the backend return `200`, but I think ensuring that the backend returns empty content in the response while keeping `204` status would have worked just as well.
