### ISSUE TITLE
Expo-contacts getContactsAsync not returning phone numbers on Android

### ISSUE THREAD

**Issue by JeremiahUL** [expo/expo#11216]
### Summary of Issue 
getContactsAsync even with fields like ```Contacts.Fields.phoneNumbers``` does not return any phone numbers on android

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 4.0.7 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.9.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0. - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 23, 28, 29
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.7
    Expo Workflow: managed

### Reproducible Demo
```
       import * as Contacts from 'expo-contacts';

        const { data } = await Contacts.getContactsAsync({
            fields: [
                Contacts.Fields.PhoneNumbers
            ],
            sort: Contacts.SortTypes.FirstName 
        });
```

### Expected Behavior
```
{
  "contactType": "person",
  "firstName": "Csg",
  "id": "33060",
  "imageAvailable": false,
  "lookupKey": "1450iSkype_32632",
  "name": "Csg",
  "phoneNumbers": [{
      number,
      ...
  }]
}
```
### Actual Behavior
```
{
  "contactType": "person",
  "firstName": "Csg",
  "id": "33060",
  "imageAvailable": false,
  "lookupKey": "1450iSkype_32632",
  "name": "Csg",
}
```

**Comment by brentvatne** [comment]
for future reference, here is how you create a reproducible example: https://snack.expo.io/@notbrent/issue-11216

> This happens on Android. No errors or warnings on the logs.

this is not sufficient. please run `expo diagnostics` in your project as requested

**Comment by JeremiahUL** [comment]
This snack repo does not return any phone numbers on my device after I accepted permissions.
[https://snack.expo.io/@notbrent/issue-11216](https://snack.expo.io/@notbrent/issue-11216)
```
{
  "lookupKey": "1450iSkype_29149",
  "contactType": "person",
  "firstName": "Ikenna",
  "name": "Ikenna",
  "id": "29580",
  "imageAvailable": false,
}
```

**Comment by JeremiahUL** [comment]
It seems like it is working on Simulators but not on a real device

**Comment by brentvatne** [comment]
it's important to know what device you are using, what operating system version, and anything else that may be relevant.

**Comment by JeremiahUL** [comment]
Infinix X626B Android 9

**Comment by JeremiahUL** [comment]
CPU Frequency 2.0GHz
Internal storage 64 GB
RAM 6 GB
Screen resolution 720 X 1520

**Comment by hakoemmy** [comment]
The same behaviour just happening to me on this device:

CPU: 2.0GHZ*4
RAM: 2.00 GB
Internal storage: 32 GB
Device Name: TECNO SPARK 4
Android version: 9

**Comment by karimdakroury** [comment]
hi, after i give permission to access contacts my contact list are not showing on ios device but are shown on simulator. Is this an issue with ios device or is something wrong in my code???

**Comment by taheri79** [comment]
it doesn't work for me on basic example _https://docs.expo.dev/versions/v45.0.0/sdk/contacts/_

**Comment by Etienne971** [comment]
> hi, after i give permission to access contacts my contact list are not showing on ios device but are shown on simulator. Is this an issue with ios device or is something wrong in my code???

hi, did you find something about this ?

**Comment by SamMakesThings** [comment]
Experiencing the same, on physical iPhone XR

Expo development build
expo ~47.0.12
expo-contacts ~11.0.1
react-native 0.70.5
iPhone XR running 16.0
