### ISSUE TITLE
[expo-image-picker] [Android] Incorrect file:/ url

### ISSUE THREAD

**Issue by petrbela** [expo/expo#11214]
### Summary of Issue

`ImagePicker.launchImageLibraryAsync` returns a file url that starts with `file:/`, not `file:///`. That's not only in contrast with what the documentation says but it also causes problems when trying to use the file url further, e.g. in VideoThumbnail. (Though, when used directly, the picked image/video seems to display correctly.)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

This seems to affect Android, both in Expo and standalone (bare).

<details>
  <summary>Environment info</summary>

```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.6.0/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/petrbela/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.40 => 0.12.40 
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare
```

</details>

### Reproducible Demo

I'm able to reproduce it with the example Snack at https://docs.expo.io/versions/latest/sdk/imagepicker/
 
### Steps to Reproduce

Choose any image or video (on Android). The resulting `uri` looks like this:

```js
{
  cancelled:false,
  width:1440,
  type:"image",
  uri:"file:/data/user/0/host.exp.exponent/cache/ExperienceData/%2540snack%252Fsdk.39.0.0-cmP99I8ELy/ImagePicker/3060429b-a71c-42cf-9595-d3f39d044422.png",
  height:1080
}
```

### Expected Behavior vs Actual Behavior

The file url should start with `file:///` instead of `file:/`.

**Comment by harshaliitr** [comment]
I don't know if this is related, but in my react native app on production(only Android), 
the expo-image-picker doesn't work for the first time after an **update is pushed**. Be it a codepush update or an android update.
RN version - 0.61.2

https://user-images.githubusercontent.com/17101511/103895232-13e77b80-5116-11eb-87b4-4e8b3ffbef70.mp4

**Comment by harshaliitr** [comment]
It works after a user closes and reopens the app, but the experience is very annoying

**Comment by haseebrehmanpc** [comment]
Can you please merge open PR for it.
