### ISSUE TITLE
Expo "home" UI within Expo client only supports portrait orientation

### ISSUE THREAD

**Issue by codthing** [expo/expo#11229]
Based on development needs, the equipment I set in the simulator is horizontal`1920*720`. But the interface automatically installed by Expo does not meet my needs. How to solve?

![image](https://user-images.githubusercontent.com/16655229/101227338-74783880-36d2-11eb-8867-d4badc17f171.png)
![image](https://user-images.githubusercontent.com/16655229/101227385-9b366f00-36d2-11eb-9026-a4023bfecc38.png)

**Comment by brentvatne** [comment]
the expo "home" app does not run in landscape mode but once you enter into an app within expo client you can use any orientation you like. we don't plan on supporting this in "home" in the near future.

**Comment by mofengfs** [comment]
Ok, I see, Thx @brentvatne

**Comment by brentvatne** [comment]
see the orientation key in app.json for how to control orientation of your app: https://docs.expo.io/versions/v39.0.0/config/app/#orientation

**Comment by mofengfs** [comment]
> see the orientation key in app.json for how to control orientation of your app: https://docs.expo.io/versions/v39.0.0/config/app/#orientation

many thx
