### ISSUE TITLE
App crash on load when running reanimated2 >alpha.7 and rc.0

### ISSUE THREAD

**Issue by Evanion** [expo/expo#11232]
### Summary of Issue 
I'm trying to run the generated `with-reanimated2` with the latest version of reanimated2.. and as soon as I go over alpha 7, it repeatedly crash with an error about not being able to find the `_frameTimestamp` variable.
I have tried running it both with and without turbomodules (as per https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-alpha.8).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.npm-pkg/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.0 => 39.0.5 
      react: ~16.13.0 => 16.13.1 
      react-dom: ~16.13.0 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2 
      react-native-web: 0.13.13 => 0.13.13 
    Expo Workflow: managed

### Reproducible Demo
(this is just the basic template generated by `with-reanimated2`)
https://snack.expo.io/@evanion/reanimated2-rc

 
### Steps to Reproduce
- Run `npx crna --template with-reanimated2 <appname>` in your favorite terminal
- Update `react-native-reanimated` to `2.0.0-rc.0`
- disable turboModules in `app.json`
- Fire up in iOS simulator

### Expected Behavior vs Actual Behavior
I expect the app to render correctly and work as it does with version `alpha-6.1`

**Comment by brentvatne** [comment]
this is expected. https://docs.expo.io/versions/v39.0.0/sdk/reanimated/#experimental-support-for-v2-alpha

> # This exact version is supported:
> npm install react-native-reanimated@2.0.0-alpha.6.1

**Comment by brentvatne** [comment]
(sdk 40 will add support for rc.0 and it will not require enabling turbomodules in app.json anymore - it should be released next week)
