### ISSUE TITLE
[docs] Search returns results for beta version before stable

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#11231]
<img width="922" alt="Screen Shot 2020-12-04 at 4 41 23 PM" src="https://user-images.githubusercontent.com/90494/101228226-9c728800-364f-11eb-86da-4656f292bacc.png">

**Comment by byCedric** [comment]
Hmm, I guess we can do two things here:

1. Add an extra attribute that defines if the indexed page is beta, this must be added in the [Algolia config](https://github.com/algolia/docsearch-configs/blob/master/configs/expo.json#L31) and included in [our pages here](https://github.com/expo/expo/blob/master/docs/components/DocumentationPage.tsx#L267).
**Pros**: We have more control over the search result and can ask algolia "everything except beta results".
**Cons**: Algolia has to reindex the website to process beta version changes (e.g. when we release)

2. Make sure the [`currentVersion` in AlgoliaSearch](https://github.com/expo/expo/blob/master/docs/components/plugins/AlgoliaSearch.tsx#L150) is never a beta version
**Pros**: When we change beta versions, this is propagated whenever we deploy
**Cons**: We have fewer options to filter search result based on beta info

I think option 2 is the most sensible one here, or do you see an alternative solution? 😄

**Comment by byCedric** [comment]
All right, option 2 is ready to deploy 😄  @brentvatne
