### ISSUE TITLE
Clipboard getString & pasting not working in iOS 14 Simulator / Big Sur

### ISSUE THREAD

**Issue by nikgraf** [expo/expo#11234]
### Summary of Issue 

I setup my project on a new Macbook Pro with Big Sur and iOS 14 Simulator.
On this device in an Expo app, but also directly in Expo when for example trying to add a new project pasting doesn't work.

It's working fine on an older machine with Mojave.

Interestingly `setString` and copying works and I can paste the content into my text editor.

Once I try to paste into a TextInput nothing happens. Also no log on the device console output.
In addition I also see `Expo pasted from CoreSimulatorBridge` once.
I also tried the Clipboard's `getString`, but no content in there.

When I tried pasting in the Reminders app in the same simulator it works fine.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

I'm using Expo 39, but also tried out the 40 Beta.

```
  Expo CLI 4.0.7 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 40.0.0-beta.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
discussed in twitter dms, seems to work as expected, maybe a simulator/os issue. tried to repro with https://snack.expo.io/@notbrent/ludicrous-ice-cream and worked as expected
