### ISSUE TITLE
How to import .scss file in project and how to init new project with .js file (not .tsx)?

### ISSUE THREAD

**Issue by yoyhosoft** [expo/expo#11242]
Hi,

**First question:**
Before now, I was use "react-create-app" and install "node-sass" then import my ".scss" file to my project, it work fine.

After that, I move to use "expo init" I do the same thing, but it's not work.

Anyone know the solution to make ".scss" file work with Expo?

**One more question:**
How to "expo init" create ".js" file (not .tsx)

Any help will much appreciate.

### Sorry for my English skill.

**Comment by AdamJNavarro** [comment]
Hey @yoyhosoft, running `expo init` should provide you with a list of options. To get a project that uses `.js` files, select either `Blank` for the Managed workflow or `Minimal` for the Bare workflow. The ones that have `(TypeScript)` are the templates that will use the `.tsx` extension.

Also, `expo init` is not an alternative to `create-react-app` as it creates a mobile project with web-support provided via expo-web (built on top of react-native-web).

Cheers,
Adam
