### ISSUE TITLE
The simulator runs normally, but the WEB reports an error:

### ISSUE THREAD

**Issue by mofengfs** [expo/expo#11247]
## 🐛 The simulator runs normally, but the WEB reports an error:
![image](https://user-images.githubusercontent.com/16655229/101305738-4c2d3d00-387e-11eb-8a77-899fca6b04df.png)
![image](https://user-images.githubusercontent.com/16655229/101306254-5996f700-387f-11eb-99c7-f5b89055b078.png)

### App.js
```
import React from 'react';
import * as eva from '@eva-design/eva';
import { ApplicationProvider, IconRegistry } from '@ui-kitten/components';
import { AppNavigator } from './src/navigation/navigation.component.js';
import { EvaIconsPack } from '@ui-kitten/eva-icons'; 
import { default as theme } from './src/theme/custom-theme.json';

export default function App() {

  return (
    <>
      <IconRegistry icons={EvaIconsPack} />
      <ApplicationProvider
        {...eva}
        theme={{ ...eva.dark, ...theme }}
      >
        <AppNavigator />
      </ApplicationProvider>
    </>
  )
};
```

### \node_modules\expo\AppEntry.js

```
import registerRootComponent from 'expo/build/launch/registerRootComponent';

import App from '../../App';

registerRootComponent(App);

```

**Comment by brentvatne** [comment]
this is a normal error that you get when you attempt to render a component that is undefined. you will have to debug this on your own, it's not a bug in expo.

if you believe you've found a bug, then as requested by the issue template please provide a https://stackoverflow.com/help/minimal-reproducible-example without external dependencies
