### ISSUE TITLE
Any idea about how to fix Rect Native version Mismatch?

### ISSUE THREAD

**Issue by Asinox** [expo/expo#1125]
Hello guys, I'm getting into React Native, and right now I got an error that I can't fix, after update RN, this is what I got while I'm using Expo:

```
Rect Native version Mismatch
JavaScript version: 0.51.0
Native version: 0.50.3
```

> Expo: 2.1.2.1010988
> react-native-cli: 2.0.1
> react-native: 0.51.0

Any idea how to fix this?

Thanks!

**Comment by terribleben** [comment]
Hi, if you are using Expo, then you should be using Expo's fork of React Native and using the SDK version corresponding to that version of React Native. The `sdkVersion` field of `app.json` will tell Expo what version of the RN native code to target. See [this table](https://docs.expo.io/versions/latest/sdk/index.html). (looks like we still need to add SDK 24 there - check the [release notes](https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51) if you're using SDK 24).

Let me know if you're still having trouble after you ensure that `sdkVersion` and `react-native` are pointing to the right versions. Hope this helps!
