### ISSUE TITLE
expo-crypto & expo-standard-web-crypto don't appear to be global on the first load. 

### ISSUE THREAD

**Issue by davidrhyswhite** [expo/expo#11251]
### Summary of Issue

I'm unsure if this is an issue with an external module or how expo / metro boots dependencies, when invoking a function that uses the `randomBytes` method, having loaded in a global node environment, it fails the first time it's loaded as the crypto dependencies appear to be null, however commenting out the crypto dependency in my app, waiting for the app to re-fresh the uncommenting them, the app suddenly loads.

Any help or pointers would be great.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 4.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
      npm: 6.14.9 - ~/.nvm/versions/node/v14.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.3
    Expo Workflow: managed
```

### Reproducible Demo

https://github.com/davidrhyswhite/crypto-expo-project
 
### Steps to Reproduce

1. Start the application with: `expo start`
2. Wait for the error message:
      Error: Secure random number generation is not supported by this browser.
      Use Chrome, Firefox or Internet Explorer 11
3. Comment out lines: 22 and 25 in App.tsx
4. Save the file and wait for a relead
5. Uncomment lines: 22 and 25 in App.tsx
6. Save the file and wait for a relead
7. The app will run again this time with the crypto library polyfilled for mobile and the bytes logged to the console.

### Expected Behavior vs Actual Behavior

It that for some reason the `crypto` library is not loaded and global the first time the project is run but subsequent runs it seems that it's available and able to run.

**Comment by brentvatne** [comment]
@davidrhyswhite - can you try to make your example more minimal? it should be able to demonstrate this in a single App.tsx file without any external dependencies beyond the libraries included in a blank app and expo-crypto and expo-standard-web-crypto, we are not familiar with the internals of third party libraries like bitcoinjs-lib and node-libs-expo

**Comment by ide** [comment]
There's nothing special about the first load and this library, it's stateless. The library is pretty small so I think the shortest path to answering your question is to read the code.

**Comment by davidrhyswhite** [comment]
Thanks @brentvatne @ide.

I've updated with a more mimimal example, and pulled in just the single dependency that causes an issue which is the `randombytes` module. I've kind of half figured out the issue and it seems to be related to using `import` and then polyfilling, then importing after that, and the way the random bytes library exports its' module:

```javascript
var crypto = global.crypto || global.msCrypto

if (crypto && crypto.getRandomValues) {
  module.exports = randomBytes
} else {
  module.exports = oldBrowser
}
```

You can still do the `expo start`, fail, comment out code, save, uncomment, save, works, trick so I've left the code up with a description in the file if you're interested in it .

To actually "fix" it however I found two solutions that work, one is to change the import of the offending library to a dynamic import, so we can be sure that the crypto functionality has been pollyfilled when when the module is loaded. The other is to switch to a `require` statement, rather than an `import` statement.

**Comment by davidrhyswhite** [comment]
Here's the main `App.js` file from my example:

```javascript
// The randombytes library requires Node's Buffer to be available.
global.Buffer = require('buffer').Buffer;
import { polyfillWebCrypto } from 'expo-standard-web-crypto';
polyfillWebCrypto();

import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

/*
1. Start the application with: expo start
2. Wait for the error message:
      Error: Secure random number generation is not supported by this browser.
      Use Chrome, Firefox or Internet Explorer 11
3. Comment out lines: 22 and 25
4. Save the file and wait for a relead
5. Uncomment lines: 22 and 25
6. Save the file and wait for a relead
7. The app will run again this time with the crypto library polyfilled for mobile and the bytes logged to the console.
*/

import random from 'randombytes';

export default function App() {
  console.log('random(32) :>> ', random(32));
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}
```

**Comment by ide** [comment]
Makes sense, this is just how JS works. Make a new module that initializes the polyfill and import it first:

**App.js:**
```jsx
import './initialization';

import { StatusBar } from 'expo-status-bar';
import random from 'randombytes';
import React from 'react';
import { Text, View } from 'react-native';

export default function App() {
  console.log('random(32) :>> ', random(32));
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}
```

**initialization.js:**
```jsx
global.Buffer = require('buffer').Buffer;
import { polyfillWebCrypto } from 'expo-standard-web-crypto';
polyfillWebCrypto();
```
