### ISSUE TITLE
FileSystem.readAsStringAsync has integer overflow for position option on Android

### ISSUE THREAD

**Issue by gyoung-panopto** [expo/expo#11264]
### Summary of Issue 

I am trying to use FileSystem.readAsStringAsync to read parts of an arbitrarily large file. However, I am noticing it is reading incorrect data if the position option is larger than the max integer in Java.

A potential fix would be to use long instead of int32 for the position option when it converts the options on this line: https://github.com/expo/expo/blob/bc70482d8f92aae82a4011d81ee093e561a45e33/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java#L295

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 4.0.8 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-navigation: ^4.0.0 => 4.4.2
    Expo Workflow: managed

### Reproducible Demo

Where fileUri points to a file larger than ~2GB:

FileSystem.readAsStringAsync(fileUri, {
      encoding: FileSystem.EncodingType.Base64,
      position: 2147483648, (or any value larger than Java's max int32)
      length: 1024
});
 
### Steps to Reproduce

Run the code above on a file larger than 2GB, compare the result to the actual file

### Expected Behavior vs Actual Behavior

Expected: the code returns the correct part of the file as a Base64 string
Actual: Integer overflow prevents reading the correct part of the file since position is higher than Java's max integer

Is there any way to work around this?

**Comment by gyoung-panopto** [comment]
It turns out this also reproduces on iOS, though iOS instead just throws an error:

Error: An exception was thrown while calling `ExponentFileSystem.readAsStringAsync` with arguments `(
    "file:///...",
        {
        encoding = base64;
        length = 5242880;
        position = 2149580800;
    }
)`: *** -[NSConcreteFileHandle seekToFileOffset:]: Invalid argument

Is there a way to work around this overflow error? It's very limiting to only allow this operation on a file smaller than 2GB.

**Comment by schneikai** [comment]
Same issue here. 

```
Error! An exception was thrown while calling `ExponentFileSystem.readAsStringAsync` with arguments `(
    "file:///var/mobile/Media/DCIM/139APPLE/IMG_9307.MP4",
        {
        encoding = base64;
        length = 10485760;
        position = 2149580800;
    }
)`: *** -[NSConcreteFileHandle seekToFileOffset:]: Invalid argument
```

**Comment by schneikai** [comment]
@AdamJNavarro @byCedric I was wondering if you guys would consider reopening this. The bug prevents to use FileSystem.readAsStringAsync on files larger than 2GB. I believe @gyoung-panopto has already supplied a bugfix. Thanks so much guys for your work! ❤️
