### ISSUE TITLE
ios - Get IDFA for Google Ads Conversion Tracking

### ISSUE THREAD

**Issue by carsonwah** [expo/expo#1126]
Is there a way to get IDFA in ios in order to track conversion for Google Ads Universal App Campaign performance? I think this is an neccessary step in doing app promotion in Google Ads.

[Create Universal App Campaign (step 13)](https://support.google.com/adwords/answer/6291545?co=ADWORDS.IsAWNCustomer%3Dfalse&hl=en)

> AdWords can count installs as conversions for Android apps in the Google Play store automatically. To track all other installs and key events, make sure to set up mobile app conversion tracking.

[iOS Conversion Tracking doc](https://developers.google.com/app-conversion-tracking/api/legacy/ios-conversion-tracking-server)

**Comment by terribleben** [comment]
Hi there, we currently don't expose the IDFA in our API. There are a couple things you can do:

- Open a [feature request](https://expo.canny.io/feature-requests) to add this.
- Detach to [ExpoKit](https://docs.expo.io/versions/latest/expokit/index.html) and expose the IDFA through your own native hook.

Sorry there's no easy solution right now. Hope those suggestions help!
