### ISSUE TITLE
[expo-av] Recording from the Bluetooth A2DP sink?

### ISSUE THREAD

**Issue by kidfrom** [expo/expo#11276]
### Please note that discussions opened as issues in the core Expo repository will be closed.

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂 

My goal is to record audio using Bluetooth Microphone with the [`react-native-a2dp`](https://github.com/microCloudCode/react-native-a2dp/).

I could not find any options for recording from the Bluetooth A2DP sink on https://docs.expo.io/versions/latest/sdk/audio/#audiorecording.

**Comment by AdamJNavarro** [comment]
Hey @kidfrom, this is not possible within the Managed workflow using the `expo-av` modules.

Cheers,
Adam
