### ISSUE TITLE
SecureStore variables not accessible after ejecting

### ISSUE THREAD

**Issue by jacobarvidsson** [expo/expo#11272]
### Summary of Issue 
When ejecting an app, retrieving saved variables from the SecureStore are all undefined. The app is using the same developer credentials, certificates, app ids etc. 

```
const item = await SecureStore.getItemAsync("stored_value_from_before_eject");
// item === undefined
```

**Use case**: Store refresh token and authentication token in secure store. User authenticates with app. Ejected version of the app is uploaded. User is logged out.

### Environment

Expo CLI 4.0.8 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18
      expo-secure-store: ~9.2.0
    npmGlobalPackages:
      expo-cli: 4.0.8
    Expo Workflow: bare

### Reproducible Demo

```javascript
import React, { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as SecureStore from "expo-secure-store";

const App = () => {
  const [value, setValue] = useState<string | null>();

  useEffect(() => {
    const init = async () => {
      const item = await SecureStore.getItemAsync("stored_value");
      setValue(item);
    };
    init();
  }, []);

  const storeItem = async () => {
    setValue("Stored value");
    await SecureStore.setItemAsync("stored_value", "Stored value");
  };

  return (
    <View style={{ margin: 80 }}>
      <Pressable onPress={storeItem}>
        <Text>Store item</Text>
      </Pressable>
      <Text>{value ? `Received value: ${value}` : "No value found"}</Text>
    </View>
  );
};
 
export default App;
```
### Steps to Reproduce
I am not sure if there is a way of replicating this on your local machine. 
1. Upload an app using expo manned workflow (using the above code for main app file).
2. Using the app store a value in the secure store.
3. Eject the app and upload a new version of the app.
4. Observe the value is now undefined when starting the updated app.

### Expected Behavior vs Actual Behavior
Value is undefined, it should be "Stored value". 

### Comment
I am wondering if there is some configuration needed by secure store that becomes undefined by the eject process. For example in expo-notification I need to provide the experienceId when getting token, while in managed workflow it gets the experienceId from the manifest file. Is there maybe something similar happening here, where it sets something similar to the  experienceId in SecureStore, which is undefined in the bare workflow, so I don't get access to my secure store (or not the same container at least). For example if changing the "owner" field in the app.json in the managed workflow, you get the same problem. Is there anything you could pass as part of the options of SecureStore.getItemAsync to fix this?

**Comment by cruzach** [comment]
hey @jacobarvidsson , is this on iOS, Android, or both? It is possible the SecureStore is currently scoped by experience ID

**Comment by jacobarvidsson** [comment]
@cruzach Hi, I experienced it on both iOS and android when I ejected our app, however when I redid the test from a new project to test it, I only did it on iOS so the above "environment" is from that project.

**Comment by jacobarvidsson** [comment]
Wondering if there is anything you can input to the current options to make it work. I tried setting the keychainService to experience id, but that didn't work, and to be honest I am not sure what keychainService is.

**Comment by jacobarvidsson** [comment]
Also I tried upgrading to SDK 40, which didn't work. Thought maybe the changes to the Constants.manifest in bare would have helped.

**Comment by Zakrevskijj** [comment]
@cruzach Hello, I've checked out a fix applied in a referenced MR and tried to fix this issue in my project by upgrading to Expo SDK 40 and upgrading expo-secure-store to the latest 10.0.0 prior to ejecting. And after that ejected version is still showing the same behavior. 

**Could you, please, help with an explanation of how this issue can be fixed?**

_Context:_ I have a prod issue because of this for Android and as a temp solution asked users to hold on updating to next version. And, also, this blocks updates publishing for iOS. 

Thanks in advance!

My other question in a MR itself: https://github.com/expo/expo/pull/11309#issuecomment-794427617

**Comment by cruzach** [comment]
@Zakrevskijj this fix will be applied to SDK 41, not SDK 40. You will need to upgrade to SDK 41, _then_ eject (this is explained in the PR you linked)
