### ISSUE TITLE
Localization files in app.json not working

### ISSUE THREAD

**Issue by Badyl1g** [expo/expo#11281]
### Summary of Issue 
Localization files for iOS permission descriptions are not being used in built app
The phone's locale is french but the permission modal displays message in english

Our current setup looks like this: 

#### app.json
```
{
   "expo":{
      "locales":{
         "en":"./locales/ios/en.json",
         "nl":"./locales/ios/nl.json",
         "fr":"./locales/ios/fr.json"
      },
      "ios":{
         "infoPlist":{
            "NSCameraUsageDescription":"Camera will be used to scan product package and display information about specific product"
         }
      },
      (...the rest of the settings)
   }
```

#### `locales/ios/fr.json`
```
{
  "NSCameraUsageDescription": "Pour prendre des photos et détecter votre produit"
}
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed
```

### Steps to Reproduce
(We use an iPhone with french localization in testing process)
1. Add translation files
2. Include them in app.json under `locales` key
3. `expo publish` - App shows english message
4. Remove `infoPlist` from app.json entirely
5. `expo publish`
6. The app still displays english message

#### Expected Behavior
The app should display messages regarding permission requests in phone's language

#### Actual Behavior
It always uses english instead

**Comment by AdamJNavarro** [comment]
Hey @Badyl1g, this is the expected behavior as you need to build a new binary for those changes to take effect. You can read more about publishing limitations here: https://docs.expo.io/workflow/publishing/#limitations

Cheers,
Adam
