### ISSUE TITLE
Not getting any observable changes while using `androidStatusBar` in dark mode

### ISSUE THREAD

**Issue by ahtrahdis7** [expo/expo#11286]
## 🐛 Bug Report
`app.json` file is as follows
<pre>
{
  "expo": {
    "name": "Cykal",
    "slug": "cykal",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/cykal_logo.png",
    "splash": {
      "image": "./assets/logo.png",
      "resizeMode": "contain",
      "backgroundColor": "#000000"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "versionCode": 2,
      "package": "in.cykal.cykal",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#000000"
      },
      "permissions": [
        "READ_EXTERNAL_STORAGE"
      ],
      "userInterfaceStyle": "dark"
    },
    "androidStatusBar" : {
      "hidden": true,
      "barStyle": "light-content",
      "backgroundColor": "#000000",
      "translucent" : false
    },
    "androidNavigationBar": {
      "visible": "sticky-immersive",
      "barStyle": "dark-content",
      "backgroundColor": "#ffffff"
    },
    
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "description": ""
  }
}

</pre>

### Summary of Issue 
I am not getting any observable changes in my status bar. The`background-color` is remaining white and `text-color`  is also white. Even if,`"hidden": true`, The status bar is visible.

### Reproducible Demo
![WhatsApp Image 2020-12-09 at 7 01 32 PM](https://user-images.githubusercontent.com/44672399/101636353-358b0f80-3a51-11eb-8168-88d0208a6453.jpeg)

 
### Steps to Reproduce
Use my `app.json` configuration, i suppose , that would be enough.

### Expected Behavior vs Actual Behavior

`backgroundColor: "#000000#` for the `status bar`

**Comment by byCedric** [comment]
Hi @ahtrahdis7! Please see these two guides on how to change the status bar when the app is running:
- https://docs.expo.io/guides/configuring-statusbar/#updating-the-status-bar-while-your-app
- https://docs.expo.io/versions/latest/react-native/statusbar/#usage-with-navigator

**Comment by ahtrahdis7** [comment]
There was a blank link associated with the `statusbar` in the documentation `app.json/app.config.js` .

**Comment by byCedric** [comment]
Yes, I've seen that one too. A PR is up to update the configurations we generate the docs from 😄  Thanks for mentioning it.
