### ISSUE TITLE
expo-image-picker freezes when clicking the "choose" button with IOS Simulator on Big Sur

### ISSUE THREAD

**Issue by ikey2244** [expo/expo#11290]
### Summary of Issue 
expo-image-picker freezes after selecting an image and hitting the "choose" button. It works as expected on a physical device and on a 2018 macbook pro. However it does not work in the IOS simulator on an M1 Chip Macbook Air(Big Sur).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 4.0.11 environment info:
    System:
      OS: macOS 11.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 4.0.11
    Expo Workflow: managed

**Comment by avenyproduction** [comment]
have you been able to make this work on your Macbook with M1 processor?
