### ISSUE TITLE
Issue with expo-localization and Jest in a bare workflow app

### ISSUE THREAD

**Issue by jamonholmgren** [expo/expo#11298]
### Summary of Issue

(Note that this only happens when using expo-localization in a bare workflow app.)

When including `expo-localization` in a file that is run via a Jest test, I get:

```
  ● Test suite failed to run

    TypeError: Cannot read property 'locale' of undefined

    > 1 | import * as Localization from "expo-localization";
        | ^
      2 | 

      at Object.<anonymous> (node_modules/expo-localization/src/Localization.ts:15:52)
      at Object.<anonymous> (index.ts:1:1)
```

![image](https://user-images.githubusercontent.com/1479215/101717325-ef837b00-3a53-11eb-86ee-68b4df4862bd.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

<details>
 <summary>expo diagnostics info</summary>
  <pre><code>
  Expo CLI 4.0.12 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.0.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      react: ^17.0.1 => 17.0.1 
      react-native: ^0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.0.12
    Expo Workflow: managed
  </code></pre>
</details>

### Reproducible Demo

I've reproduced this in a very minimal app:

https://github.com/jamonholmgren/repro-expo-localization
 
### Steps to Reproduce

```
git clone https://github.com/jamonholmgren/repro-expo-localization
cd repro-expo-localization
yarn
yarn test
```

### Expected Behavior vs Actual Behavior

Expected the tests to pass. Instead, they fail with an error because `Localization.js` can't seem to find `ExpoLocalization.js` in the build folder.

If I edit `Localization.js` line 1 like this, it works fine:

```
import ExpoLocalization from './ExpoLocalization';
// becomes
import ExpoLocalization from './ExpoLocalization.js';
```

See Twitter thread for more: https://twitter.com/jamonholmgren/status/1336865643895824384

**Comment by brentvatne** [comment]
I believe the error that you are getting is because there is no mock for the native module available. We use the `jest-expo` package for this: https://github.com/expo/expo/blob/ded562c9b74a2c51bc690d888d5ff89784b87726/packages/jest-expo/src/preset/expoModules.js#L703-L713

If I add that to the project then it works as expected. I recommend using jest-expo if you use expo-modules, all it does is extend the react-native preset to add mocks for all Expo modules 👍 

![Screen Shot 2020-12-09 at 7 28 54 PM](https://user-images.githubusercontent.com/90494/101717788-d0391d80-3a54-11eb-9ffd-ecd51c858906.png)

https://github.com/brentvatne/repro-expo-localization

Docs are here: https://docs.expo.io/guides/testing-with-jest/ - maybe we need to surface this another way somehow

**Comment by jamonholmgren** [comment]
Thanks, that did the trick! You're the best, Brent.

![image](https://user-images.githubusercontent.com/1479215/101719106-81d94e00-3a57-11eb-94d5-78516c9eb74c.png)

**Comment by amalikmuhd** [comment]
Hi @jamonholmgren ,

I followed exactly what you said but it is not working for me. I am getting error in expo-local-authentication

<img width="997" alt="Screenshot 2023-08-13 at 11 50 04" src="https://github.com/expo/expo/assets/4702828/94601d05-bb36-487d-84eb-7ceeae1ccd33">



I added the code you provided
<img width="1792" alt="Screenshot 2023-08-13 at 11 52 02" src="https://github.com/expo/expo/assets/4702828/93ac18aa-47a8-4afd-bd68-b784dbb85470">

Thanks
