### ISSUE TITLE
InAppPurchases.purchaseItemAsync() promise never resolves on iOS

### ISSUE THREAD

**Issue by special-character** [expo/expo#11294]
### Summary of Issue

When I call `InAppPurchases.purchaseItemAsync()` on iOS, the promise *sometimes* doesn't resolve. When this happens, I don't see the Apple purchase confirmation that slides up. When I try to call it a 2nd time, I get the error:

```
Error: Must wait for promise to resolve before recalling function.
    at Object.promiseMethodWrapper [as callMethod] (NativeModules.js:103)
    at Object.NativeModulesProxy.<computed>.<computed> [as purchaseItemAsync] (NativeModulesProxy.native.js:15)
    at purchaseItemAsync$ (InAppPurchases.js:38)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:189
    at tryCallTwo (core.js:45)
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Targeting iOS
```
  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.23.0 - ~/.nvm/versions/node/v10.23.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v10.23.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native-web: 0.13.3 => 0.13.3 
```

### Reproducible Demo
I haven't been able to do this yet. It would/will require creating a new iOS app on apple and setting up a subscription to purchase which I haven't gotten to yet.

 
### Steps to Reproduce
Have a renewable subscription and call `InAppPurchases.purchaseItemAsync()` on iOS (may happen for other types of IAP but mine is renewable).

### Expected Behavior vs Actual Behavior

The promise would resolve with some form of success or an error.
----------------------------------------------------------------------------------------------------------------------------

Overall, I am not sure what could cause this. I make sure that I am connected to apple before calling `purchaseItemAsync`.

```
    const connectToApple = async () => {
      try {
        const responseCode = await InAppPurchases.getBillingResponseCodeAsync()
    
        if (responseCode === InAppPurchases.IAPResponseCode.ERROR)
          await InAppPurchases.connectAsync()
      } catch (err) {
        Sentry.captureException(err)
      }
    }
    
    const purchaseSubscription = async () => {
      console.log('PURCHASE_SUB_STARTED')
      try {
        await connectToApple()
        console.log('PURCHASE_SUB_CONNECTED_TO_APPLE')

        await getSubscriptionDetails()
        console.log('PURCHASE_SUB_DETAILS_FETCHED')

        await InAppPurchases.purchaseItemAsync(
          envVars.APPLE_SUBSCRIPTION_PRODUCT_ID,
        )
        console.log('PURCHASE_SUB_COMPLETE')
      } catch (err) {
        console.log('PURCHASE_SUB_FAILED', err)
        Sentry.captureException(
          `Failed to call purchaseItemAsync with product id ${
            self.appleSubscriptionDetails!.productId
          }`,
        )
      }
    }
```

I get to `PURCHASE_SUB_DETAILS_FETCHED` and it just hangs.

It is worth noting I ran into a similar issue with the expo IAP api before but it seemed to resolve itself https://github.com/expo/expo/issues/11203. I have been through the docs a few times and don't think I am doing something wrong but not sure exactly why it is never resolving.

Any help/ideas would be appreciated, thanks!

**Comment by special-character** [comment]
After more testing, I don't think that the network request is actually rejected if it fails. I am using Charles proxy to inspect network traffic and can make it fail and just hang.

I also don't think the prompt is always showing properly. I have an expired subscription but when I called `purchaseItemAsync`, no prompt was displayed. It called the purchase listener callback with a bunch of purchases but they were all marked as having `InAppPurchaseState.PURCHASED`.

**Comment by ayberkanilatsiz** [comment]
I've got the same issue with @special-character. +1

**Comment by special-character** [comment]
@ayberkanilatsiz ooooh I didn't realize that. I grab the purchase history on startup. I wonder what is blocking the prompt from opening. I will try digging into it a bit more today.

**Comment by special-character** [comment]
After taking a look at the apple docs, I don't think I should be calling `getPurchaseHistoryAsync` on startup since it actually does a restore. Apple specifically says not to do a restore on startup.

https://developer.apple.com/documentation/storekit/in-app_purchase/restoring_purchased_products

I think the flow that I am using needs to change a bit and calling `getPurchaseHistoryAsync` should really only be called for the typical `restore` needs.

**Comment by ARMATAV** [comment]
This fixed it for me - don't call `getPurchaseHistoryAsync()` on startup, it hangs the promise and `purchaseItemAsync()` stops going through.

**Comment by ferrannp** [comment]
If you do not have to call `getPurchaseHistoryAsync` (only for restore), how do you check if the item was previously purchased when you start the app?

**Comment by arun0715** [comment]
Some time not loading purchase screen to IOS 14.5 when we calling this  InAppPurchases.purchaseItemAsync(product_id)

**Comment by cruzach** [comment]
So it looks like the fix here is to not call `getPurchaseHistoryAsync` on start up. We can update the docs for that 👍

**Comment by cruzach** [comment]
fixed in https://github.com/expo/expo/commit/b917897d68963c8582ef70907d3f73fa15d94707

**Comment by CruelMoney** [comment]
@cruzach Is it possible to fix this so `getPurchaseHistoryAsync` doesn't halt `purchaseItemAsync`? 

I think it's quite common that users would attempt to restore purchase, then realize they never purchased the product, and then press purchase.

**Comment by tbergeron** [comment]
But how should we check if a subscription is still active on startup if we cannot use this function on startup? Is there something I don't understand? Can someone enlighten me please? Thanks!
