### ISSUE TITLE
expo upgrade doesn't offer SDK 40

### ISSUE THREAD

**Issue by jpenjgusic** [expo/expo#11296]
I have installed latest expo-cli globally and run command expo upgrade but it is saying that I am already on latest version which is sdk 39.

I have installed sdk-39.04

**Comment by brentvatne** [comment]
try deleting the the `~/.expo/cache directory` - it's possible that you're having some trouble connecting to our versions endpoint and getting the updated versions data

**Comment by brentvatne** [comment]
this was an issue on my end, it has been resolved, thanks for the issue
