### ISSUE TITLE
expo-notifications error in new version 0.8.2

### ISSUE THREAD

**Issue by bhandanyan-nomad** [expo/expo#11295]
### Summary of Issue 
After running `yarn add expo-notifications` & `npx pod-install` to get version 0.8.2 all existing unit tests are failing with this error:
```
TypeError: Cannot read property 'getRegistrationInfoAsync' of undefined

> 1 | import * as Notifications from 'expo-notifications';
    | ^
  2 | import * as Permissions from 'expo-permissions';
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 4.0.12 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
      react-native-web: ~0.13.7 => 0.13.18
      react-navigation: ^4.4.1 => 4.4.3
    npmGlobalPackages:
      expo-cli: 4.0.12
    Expo Workflow: bare
```

### Reproducible Demo
https://snack.expo.io/ObiIHkYQ_

 
### Steps to Reproduce
Run the snack above, see an error about getRegistrationInfoAsync. There is an error that says 0.8.2 is not the expected version for expo sdk 39.0.0, but with the bare workflow I expect to be able to update packages independently and have them work.

### Expected Behavior vs Actual Behavior
I expect the new version of expo-notifications to work in an app that has ejected.

**Comment by brentvatne** [comment]
update jest-expo to the latest version to get new mocks
