### ISSUE TITLE
iOS custom system permission dialog for notifications

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#1129]
Hi, the docs specify how to add custom system permissions dialogs in iOS through `app.json`:

https://docs.expo.io/versions/latest/guides/app-stores.html#system-permissions-dialogs-on-ios

The list of keys provided by Expo by default though doesn't include notifications:

https://github.com/expo/expo/blob/master/exponent-view-template/ios/exponent-view-template/Supporting/Info.plist#L28-L41

Does a key for system notifications exist?

Thanks!

**Comment by terribleben** [comment]
Hi, great question. At the moment Apple [does not seem to support such a key](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html). I believe it will always say "<app name> would like to send you notifications." (if I'm wrong, let me know, but I can't find a better resource besides that link.)

In the future if this turns into a native API, we'd be happy to add it in Expo. Hope that helps!

**Comment by pensierinmusica** [comment]
@terribleben awesome, thx!
