### ISSUE TITLE
[push-notifications] Cannot send notifications using ExpoPushToken (Expo 40)

### ISSUE THREAD

**Issue by fedyk** [expo/expo#11304]
### Summary of Issue 

After upgrade to Expo 40 and iOS, I have a problem with sending Push Notifications using `ExpoPushToken`. The issue happens only on a standalone app, in Expo client everything works fine.

During the debug process, I had tried to use `DevicePushToken` and I managed to send and receive notifications (using `node-apn` with keys from `expo fetch:ios:certs`). The device token is `645f97af437250b8207c3e4ddaff9d9850350bc4391cf895cdb526f502a9716d`.

When I call [exp.host/getExpoPushToken](https://exp.host/--/api/v2/push/getExpoPushToken) with `deviceToken` above I receive token `ExponentPushToken[pXoWnIHNZytciNSC7M0LtC]`. The notifications sent by this `ExpoPushToken` do not appear on iOS device.

IMO, the standalone build and certificates are just fine, as I manage to receive notifications using `node-apn`. Most probably the issue is somewhere in `exp.host/--/api/v2/push/send` or in the method that "links" ExpoPushToken and DeviceToken.

Can you check if there were any changes on expo.api that can cause the following regression?

I'd appreciate any help here.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.19.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2
        System Images: android-24 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: 40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

**Comment by cruzach** [comment]
It's possible this is related to recent installation ID changes. Why are you providing a device push token to `getExpoPushTokenAsync`? It should default to the proper value

You should also look at the push receipt for errors, because without an error message or a reproducible demo, there's very little we can do to help

**Comment by fedyk** [comment]
Thanks for your answer. Let me clarify some things.

> Why are you providing a device push token to `getExpoPushTokenAsync`?

I wasn't. During the debug process, I was comparing the result from `Notifications.getExpoPushTokenAsync`(no arguments) and response from direct calling `POST https://exp.host/.../getExpoPushToken`. I wanted to be sure that I have the correct `ExpoPushToken` for the device.

> You should also look at the push receipt for errors, because without an error message or a reproducible demo, there's very little we can do to help

Yeah, I was checking the receipts - they look okay ☹️. I will try to figure out some way to share the reproductive demo tomorrow.

<details>
  <summary>CURLs for two recent receipts</summary>
  
 
```
curl --location --request POST 'https://exp.host/--/api/v2/push/getReceipts' \
--header 'Content-Type: application/json' \
--data-raw '{
	"ids": ["cfb6cdaa-7d67-42a7-8973-b07c914425cb", "745fb999-9fb0-4020-868d-c75e2c2bc437"]
}'
```

</details>

**Comment by dellwatson** [comment]
I've got this issue too since sdk40, 

I have switched back to back between branch sdk39 & sdk40, reinstall module, re-install expo app + standlone build etc, 
sure they results in 2 different push token but if its from sdk40, there will be no notification, 
the expo server api `https://exp.host/--/api/v2/push/send` still 200 
and again if i switch to sdk39, and reinstall expo app & everything, i will get the notification

weirdly, i have tried since the beta, and it was okay before on iphone but on ipad was already not working, now it's both. and not even working in expo app.
also everytime i click ok for the access from the permission, it always undertemined, but after i reload the app, it becomes granted.

i'm still trying to debug, will inform back later

**Comment by dellwatson** [comment]
@cruzach hello i have create the repo, please try to check

i use the plain code for notif-handler, and already put my google plist on the repo, on sdk39 works perfectly on expo apps,
just take the  `ExponentPushToken[...]` and send it via `https://exp.host/--/api/v2/push/send`

[https://github.com/dellwatson/sdk40-notif-issue](https://github.com/dellwatson/sdk40-notif-issue)
[https://github.com/dellwatson/sdk39-notif-issue](https://github.com/dellwatson/sdk39-notif-issue)

Expo CLI 4.0.6 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK: 14
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.6
    Expo Workflow: managed  
Device: iphone 7

i have tried all versions expo-apps too from testflight and appstore, but no different

**Comment by andreas-arkulpa** [comment]
I am having the same issue. With expo-sdk 39, the push was working on the ios standalone build. Since expo-sdk 40 I do not recieve any push notifications in a prod build. The permissions are set correctly and also the expo push-token seems ok.

**Comment by cruzach** [comment]
@dellwatson I tested your repro and it's working for me in Testflight. Steps I took were:

- `git clone https://github.com/dellwatson/sdk40-notif-issue`
- `yarn`
- changed bundle identifier
- `expo build:ios -t archive`
- deliver through transporter, etc.
- install via testflight
- 
```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[<my-push-token-uuid>]",
  "title":"hello",
  "body": "world"
}'
```
- received push notification

If you are not receiving push notifications, you should debug a little bit more. Are you able to receive local notifications? What does the push ticket **and** push receipt say? What if you try to send directly through APNS using the _device_ push token?

**Comment by andreas-arkulpa** [comment]
I checked the push-token from the iOS-App. Then run the command from above to test the push-token.

```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[F5Hzoalt-ZM7P9BuSwuv0bG]",
  "title":"hello" 
}'
```

on Android the push-token I got was working, on iOS the result was the following:

`{"data":{"status":"error","message":"\"ExponentPushToken[F5Hzoalt-ZM7P9BuSwuv0bG]\" is not a registered push notification recipient","details":{"error":"DeviceNotRegistered"}}}`

I have only used the Expo-Push-Setup (before on SDK39 I was using the legacy-push-notification package, there it was working).

**Comment by dellwatson** [comment]
@cruzach thankyou for trying, i do get the local notif, and the push ticket return normal with their id with status ok, 
i will try send directly through APNS then

@andreas-arkulpa hey what device are you using ?

**Comment by andreas-arkulpa** [comment]
I am using iPad (6th generation). The strange thing it, it is working on Android without any problems.

**Comment by cruzach** [comment]
@andreas-arkulpa did your push token change with the SDK upgrade? Does this happen on a fresh install of the app? Are you absolutely certain you are using the most up-to-date push token?

**Comment by fedyk** [comment]
Hello, I have suspicion that issue is happens when user had an app installed with SDK 38 + old notifications module, then installed an update with SDK 39/40 + new notifications module.

Here reproduction steps:
1. Install app with SDK 38 from [here](https://testflight.apple.com/join/HKP1T67T).
2. Sign up with any dummy email (just to register device for push notifications, [short demo](https://take.ms/gTZdw))
3. Install app with Expo 40 and new notifications module from [here](https://testflight.apple.com/join/cfjoDIVS).
  Here we removed all not needed code and just created a simple App with device tokens (long press for copy) + "Test notification" button (_please close/open app two times to install recent OTA update_).
  The demo with testing v1.14-notifications-test - https://take.ms/1iv6M.

<details>
  <summary>Code of app with Expo 40</summary>

```ts
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import * as Permissions from 'expo-permissions';
import React, { useState, useEffect, useRef } from 'react';
import { Text, View, Button, Platform, Alert, ScrollView } from 'react-native';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function App() {
  const [expoPushToken, setExpoPushToken] = useState('');
  const [devicePushToken, setDevicePushToken] = useState('');
  const [notification, setNotification] = useState<Notifications.Notification | null>(null);
  const notificationListener = useRef<ReturnType<typeof Notifications.addNotificationReceivedListener>>();
  const responseListener = useRef<ReturnType<typeof Notifications.addNotificationResponseReceivedListener>>();

  useEffect(() => {
    registerForPushNotificationsAsync().then((data) => {
      if (data) {
        setDevicePushToken(data.devicePushToken)
        setExpoPushToken(data.token)
      }
    });

    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
    });

    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      console.log(response);
    });

    return () => {
      // @ts-ignore
      Notifications.removeNotificationSubscription(notificationListener)
      // @ts-ignore
      Notifications.removeNotificationSubscription(responseListener);
    };
  }, []);

  return (
    <ScrollView
      contentContainerStyle={{
        flex: 1,
        padding: 10,
        alignItems: 'center',
        justifyContent: 'space-around',
      }}>
      <View>
        <Text>Your expo push token: </Text>
        <Text selectable>{expoPushToken}</Text>
      </View>
      <View>
        <Text>Your device push token: </Text>
        <Text selectable>{devicePushToken}</Text>
      </View>
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>Title: {notification && notification.request.content.title} </Text>
        <Text>Body: {notification && notification.request.content.body}</Text>
        <Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
      </View>
      <Button
        title="Send with api/v2/push/send"
        onPress={async () => {
          await sendPushNotification(expoPushToken);
        }}
      />
    </ScrollView>
  );
}

async function sendPushNotification(expoPushToken: string) {
  const message = {
    to: expoPushToken,
    expiration: Math.ceil(Date.now() / 1000) + (30 * 60),
    title: "Test notification",
    body: "test notification send by API",
    sound: "default",
    channelId: "v1.14-notifications-test",
    data: {
      action: "test_notification"
    },
    _displayInForeground: true // if falsy iOS won't show notification on when the app is on foreground
  };

  return  fetch('https://exp.host/--/api/v2/push/send', {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Accept-encoding': 'gzip, deflate',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(message),
  }).then(response => {
    if (response.status !== 200) {
      return response.text()
        .then(text => {
          try {
            return JSON.parse(text)
          }
          catch (err) {
            throw new Error(`${err.message}: ${text}`)
          }
        })
        .then(json => {
          const error = json.result || json.error_description || JSON.stringify(json)

          throw new Error(error)
        })
      }

      return response.text();
    })
    .then(response => {
      Alert.alert('Notification sent', response)
    })
    .catch(err => {
      Alert.alert("Notification (api) error", err.message + "")
    })
}

async function registerForPushNotificationsAsync() {
  let token;
  let devicePushToken;
  if (Constants.isDevice) {
    const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    devicePushToken = (await Notifications.getDevicePushTokenAsync()).data
    console.log(token);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('v1.14-notifications-test', {
      name: 'v1.14-notifications-test',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  return {
    token,
    devicePushToken
  };
}
```
</details>

I hope the steps above will help to investigate problem

**Comment by dhorelik** [comment]
Hi. I’ve encountered the same issue, can't send notifications. I've tried to get `ExpoPushToken` token via `DevicePushToken` as well. 

Maybe the following detail will help: when I try to call `getExpoPushTokenAsync` and pass different `DevicePushToken`s, the Expo token I get is exactly the same every time (`experienceId` and other params don't change). And it doesn't work, notifications aren't sent. Correct me if I'm wrong, but my understanding is that different Expo tokens are supposed to be generated for different Device tokens.

**Comment by cruzach** [comment]
@fedyk I tried reproducing this by installing an SDK 38 app, then updating to SDK 40 and updating the app via testflight, notifications still come through and the ExpoPushToken remained the same (even switching from LegacyNotifications to `expo-notifications`). 

Here is the repo to test this: https://github.com/cruzach/11304-repro/commits/master. You can use the `sdk 38` and `sdk 40` commits to try for yourself.

**Comment by andreas-arkulpa** [comment]
> @andreas-arkulpa did your push token change with the SDK upgrade? Does this happen on a fresh install of the app? Are you absolutely certain you are using the most up-to-date push token?

@cruzach the push token haven't changed during the sdk upgrade (from 39 to 40 - was using the old notification-package until sdk 39) when testing on an other device.
On the mentioned iPad I have made a fresh installation of the app (with sdk 40). The push-token I got then was the one mentioned here: https://github.com/expo/expo/issues/11304#issuecomment-744019947

**Comment by andreas-arkulpa** [comment]
what maybe helps here: was using sdk 38 + 39 with the old notifications module (also due to #9866), then upgraded to sdk 40 and the new notifications module.

**Comment by cruzach** [comment]
@andreas-arkulpa thanks but that's exactly what I said I tested in [this comment](https://github.com/expo/expo/issues/11304#issuecomment-744057410), so unfortunately that doesn't help. What would help is to provide a consistent reproducible demo (going to mark these comments as duplicates so that my original comment stays visible)

**Comment by jnoleau** [comment]
Hello, same behavior for my app. Everything is working correctly on SDK39 but impossible to receive push from SDK40 (ios).
I uninstall / reinstall a fresh build from testflight with no code change (only the upgrade to SDK40) and use the notification tool  `https://expo.io/notifications` and don't receive push

A strange thing: Even if I uninstall / reinstall the app, my ExpoToken received from the server does not change. I suppose there is a problem with the `installationID`  cached somewhere

**Comment by dhorelik** [comment]
I believe the issue is somehow related to ExpoToken caching happening per device on expo servers. The pushes are working now, but I only managed to do that with a different expo experienceId. My fix attempts can be narrowed down to the following flow:

Originally the project was setup to receive pushes via expo, and the setup worked, the app received pushes sent with `ExpoPushToken`. Then I reinstalled the app on my phone and pushes stopped working. `ExpoPushToken` remained the same. I fetched `DevicePushToken` explicitly, tried to send a notification directly via apns, and it worked, the device received it. Expo pushes were sent without errors, the receipts stated `ok`, but the device never got the pushes. Credentials uploaded to expo were fine. Trying to fix this I changed experienceId, pushed it to expo and on reinstall I received a new `ExpoPushToken` that works.

Since `ExpoPushToken` never changes on app reinstall (while DevicePushToken does), I guess Expo stores ios tokens linked to expo tokens in its database. Maybe when a new device token comes with a new installation, expo doesn't update it? Not sure Apple unregisters old tokens straight away, so perhaps there's a chance that expo can still get ok from Apple for some time with an old deviceToken.

I can share the failing ExpoToken, if it helps with the investigation.
Thanks.

**Comment by cruzach** [comment]
Okay, I think I was able to reproduce the behavior -> you need to install a fresh SDK 40 iOS app, then uninstall it, then reinstall it again. The ExpoPushToken doesn't change, and the push notifications aren't sent.

**Comment by fedyk** [comment]
@cruzach exactly! I was about to send you repro steps from here https://github.com/fedyk/11304-repro2/blob/main/README.md

**Comment by maurohmartinez** [comment]
@cruzach I am having the same issue. What is the solution? Thanks!

**Comment by cruzach** [comment]
We will need to deploy the fix, I'll update here once we do. It won't require any changes or updates on your end

**Comment by cruzach** [comment]
This should be fixed now 👍 let me know if you still run into the same issue

**Comment by maurohmartinez** [comment]
> This should be fixed now 👍 let me know if you still run into the same issue

Fixed. Awesome. Expo rocks :)
