### ISSUE TITLE
SDK 40 react-native-screens warning if using react-navigation v4

### ISSUE THREAD

**Issue by rafmst** [expo/expo#11301]
### Summary of Issue
After updating SDK the following warning was shown for apps that are still using react-navigation version 4.

<img src="https://user-images.githubusercontent.com/924985/101758618-d5d84700-3ad8-11eb-90c7-c29a01822ea5.png" width="400px"/>

I suspect if I downgrade react-native-screens it will work but that shouldn't be the best thing, in my opinion. To upgrade to version 5 would be insane in a project this size. What should be done in this case?

**EDIT**
Tried to revert to my previous version 2.10.1, and it shows a blank white screen.

**Comment by rafmst** [comment]
Something that worked was the removal of the following code from `App.js`:

```jsx
import { enableScreens } from 'react-native-screens';
enableScreens();
```

**Comment by brentvatne** [comment]
@rafmst - you should be able to get rid of this warning by updating to the latest versions of react-navigation packages that are compatible with v4:

- latest version fo `react-navigation`, `react-navigation-stack`, `react-navigation-drawer`, `react-navigation-tabs`
- `@react-navigation/native@^3.7`

at some point it is probably a good idea to update to react-navigation v5, because v4 is currently in maintenance mode. there is a very good upgrade guide: https://reactnavigation.org/docs/upgrading-from-4.x/

**Comment by rafmst** [comment]
I have the latest on all libraries, will ignore the warning for now. I really want to update to v5 but it will take same time.
Thanks for your insights :)

**Comment by bernalmurcia** [comment]
> Something that worked was the removal of the following code from `App.js`:
> 
> ```js-jsx
> import { enableScreens } from 'react-native-screens';
> enableScreens();
> ```

Thanks! That worked for me as well. To make sure you continue executing it in production while preventing the dev warning you can do:
```
import { enableScreens } from 'react-native-screens';

if (!__DEV__) {
  enableScreens();
}
```

**Comment by shahidcodes** [comment]
I am already using react-navigation v5 but sill I am seeing those errors why?
```
"@react-navigation/bottom-tabs": "^5.3.1",
"@react-navigation/native": "^5.2.1",
"@react-navigation/stack": "^5.2.16",
````

**Comment by butri71** [comment]
I've been facing the same issue for long time. I opened a ticket and was told that it had something to do with the react-navigation library.

I then flagged a new issue here https://github.com/react-navigation/react-navigation/issues/9252 which is still open and unassigned

**Comment by brentvatne** [comment]
you might have an old version of react-navigation installed in your app and still being used somewhere. here is where the warning is coming from: https://github.com/software-mansion/react-native-screens/blob/f3bbd486eeea4d0e66822c48d13760f1b69d4f00/src/index.native.js#L100-L105

try to create a minimal reproducible example (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by butri71** [comment]
I have updated all react-navigation packages to the latest and does not make any difference, still getting the warning. I did follow @bernalmurcia advice and suddenly the warning has disappeared. Hopefully newer versions will solve this issue
