### ISSUE TITLE
SDK 40 doesn't work with TypeScript 4.1 features

### ISSUE THREAD

**Issue by MohammedFaragallah** [expo/expo#11307]
### Summary of Issue 
it seems to be related to react native [see](https://github.com/facebook/react-native/issues/29943)

### Steps to Reproduce
clean SDK 40 installation and use any of TypeScript 4.1 features [see](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/)

**Comment by brentvatne** [comment]
we explicitly support typescript 4.0 in our templates: https://github.com/expo/expo/blob/sdk-40/templates/expo-template-blank-typescript/package.json#L26

if you'd like to try 4.1 and let us know what is needed to support it, that'd be great. we'll probably update this in sdk 41.

**Comment by MohammedFaragallah** [comment]
@brentvatne I don't understand why expo needs explicit support for a specific typescript version if you can give me a hint where to look also those features worked fine with SDK 39

I did test [Template Literal Types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types) and [Key Remapping in Mapped Types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#key-remapping-in-mapped-types) with SDK 40 both don't work

**Comment by nandorojo** [comment]
I upgraded to TypeScript 4.1 in my project, but when I use template literal types, `expo build` seems to break at the lines with the template literals.

**Comment by MohammedFaragallah** [comment]
Try this https://github.com/facebook/react-native/issues/29943#issuecomment-759661657

**Comment by wcandillon** [comment]
Upgrading the @babel/core dependency in the project doesn't seem to help since it doesn't seem to be the version that expo is using. It seems that this dev dependency in the TS blank project template is not necessary.

**Comment by nandorojo** [comment]
I'm working with a large Expo + Next project. I've been getting random build errors and hold ups for weeks and have tried to debug it with little stack trace.

#For what it's worth, taking out all uses of TS template strings seems to have helped. I've had many issues with this feature, so I would use it with caution. Make sure you test your build/dev time changes, and be extra careful getting stuck in a near-infinite loop. Even if it isn't infinite, it could hold things up.

I'll be holding off on this feature until it's matured.

**Comment by wcandillon** [comment]
For an expo project, I was able to use the 4.1 syntax using:

```
  "resolutions": {
    "@babel/core": "7.1.2"
  },
```

in package.json

**Comment by nandorojo** [comment]
For anyone coming in late, use @wcandillon's [answer](https://github.com/expo/expo/issues/11307#issuecomment-765890458), but with v `7.12.10`

**Comment by ajsmth** [comment]
@nandorojo hey Fernando - have you run into this issue recently? A fresh init of expo (sdk 40, 41, 42) all seem to be able to run TS 4.1 template strings on my end (You might have to blow up your `yarn.lock` if updating the resolutions field). I'm looking into bumping these versions regardless, but I want to make sure I'm not missing anything from this issue!

**Comment by nandorojo** [comment]
Tbh I've just avoided the feature lol it caused me many headaches. But I'll try it again with SDK 42 since I'm on that now. I have issues with Expo whenever I use these new TS features. 

Another example was TS 4.0 [Assignment Operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#short-circuiting-assignment-operators)s:

```js
const artists ||= []
```

This broke my app, so I changed it to:

```ts
const artists = artists || []
```

🤷‍♂️

**Comment by ajsmth** [comment]
> Tbh I've just avoided the feature lol it caused me many headaches. But I'll try it again with SDK 42 since I'm on that now. I have issues with Expo whenever I use these new TS features.
> 
> Another example was TS 4.0 [Assignment Operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#short-circuiting-assignment-operators)s:
> 
> ```js
> const artists ||= []
> ```
> 
> This broke my app when I built it, so I changed it to:
> 
> ```ts
> const artists = artists || []
> ```
> 
> 🤷‍♂️

was this for react-native-web? the babel preset seems to work for this w/ metro, I bet we'll need to update the webpack config for those operators

**Comment by nandorojo** [comment]
I use Next.js on web. Works fine there. But it broke when I tried to build expo’s Native app.
