### ISSUE TITLE
SDK 40 the new AppLoading crashes the app

### ISSUE THREAD

**Issue by TNBoiBoi** [expo/expo#11302]
### Summary of Issue 
I switched to the new AppLoading, installed expo install expo-app-loading - 
then imported import AppLoading from 'expo-app-loading';
and now whenver I run my up it crashes badly,

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
AppLoading threw an unexpected error when loading:
startLoadingAppResourcesAsync$@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:182771:32
tryCatch@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:29510:23
invoke@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:29683:32
tryCatch@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:29510:23
invoke@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:29583:30
http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:29613:19
tryCallTwo@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:4411:9
doResolve@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:4575:25
Promise@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:4434:14
callInvokeWithMethodAndArg@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:29612:33
enqueue@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:29617:157
http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:29634:69
startLoadingAppResourcesAsync@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:182746:42
componentDidMount@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:182734:43
commitLifeCycles@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:24239:47
commitLayoutEffects@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:26499:29
invokeGuardedCallbackImpl@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:13720:21
invokeGuardedCallback@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:13814:42
commitRootImpl@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:26288:36
commitRootImpl@[native code]
unstable_runWithPriority@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:48066:30
commitRoot@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:26175:24
performSyncWorkOnRoot@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:25699:19
performSyncWorkOnRoot@[native code]
http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:16971:38
unstable_runWithPriority@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:48066:30
flushSyncCallbackQueueImpl@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:16966:28
flushSyncCallbackQueue@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:16955:35
scheduleUpdateOnFiber@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:25308:37
updateContainer@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:27787:21
render@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:28221:24
renderApplication@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:75537:77
run@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:75107:28
runApplication@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:75164:28
__callFunction@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:3725:36
http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:3457:31
__guard@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:3679:15
callFunctionReturnFlushedQueue@http://192.168.1.109:19000/src%5Cindex.ts.bundle?platform=ios&dev=true&hot=false&minify=false:3456:21
callFunctionReturnFlushedQueue@[native code]
- node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
- node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
- node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
- node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
- node_modules\expo-app-loading\build\AppLoading.js:10:13 in componentDidMount
- node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
- node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

### Reproducible Demo
All I did was importing the new AppLoading 
It used to work with the old one
<AppLoading
        onFinish={() => setReady(true)}
        startAsync={loadAssetsAsync}
      />

the output from my visual studio code is that - 
No overload matches this call.
  Overload 1 of 2, '(props: { startAsync: () => Promise<void>; onError: (error: Error) => void; onFinish: () => void; autoHideSplash?: boolean | undefined; } | { autoHideSplash?: boolean | undefined; } | Readonly<...> | Readonly<...>): AppLoading', gave the following error.
    Type '{ onFinish: () => void; startAsync: () => Promise<void>; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<AppLoading> & Readonly<{ startAsync: () => Promise<void>; onError: (error: Error) => void; onFinish: () => void; autoHideSplash?: boolean | undefined; }> & Readonly<...>) | (IntrinsicAttributes & ... 2 more ... & Readonly<...>)'.
      Property 'onError' is missing in type '{ onFinish: () => void; startAsync: () => Promise<void>; }' but required in type 'Readonly<{ startAsync: () => Promise<void>; onError: (error: Error) => void; onFinish: () => void; autoHideSplash?: boolean | undefined; }>'.
  Overload 2 of 2, '(props: Props, context: any): AppLoading', gave the following error.
    Type '{ onFinish: () => void; startAsync: () => Promise<void>; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<AppLoading> & Readonly<{ startAsync: () => Promise<void>; onError: (error: Error) => void; onFinish: () => void; 
And that's the loadAssetsAsync function - 

const loadAssetsAsync = async () => {
    
    const fontAssets = cacheFonts([
      { HelveticaNeue: HelveticaNeueFont },
      { HelveticaNeueB: HelveticaNeuBoldFont },
      { HelveticaNeueL: HelveticaNeueLightFont },
      { HelveticaNeueM: HelveticaNeueMediumFont },
      { HelveticaNeueT: HelveticaNeueThinFont },
    ]);

    await Promise.all([...imageAssets, ...fontAssets]);
  };

Pretty basic and like I said it used to work untill this update occured. 
### Steps to Reproduce

Just change to the new AppLoading didn't change anything else

### Expected Behavior vs Actual Behavior
Not crashing

**Comment by TNBoiBoi** [comment]
A possible solution that might solved it but still not sure,
Now you are required to provide onError in your AppLoading props and not only onFinish, 
Still not sure if it's the correct fix though.

**Comment by cruzach** [comment]
@TNBoiBoi this is indeed because you are not passing the  `onError` prop- https://github.com/expo/expo/blob/master/packages/expo-app-loading/src/AppLoading.tsx#L67-L69

The way we're catching the error is obscuring the root error message though, so we can improve that
