### ISSUE TITLE
expo constants build script works on iOS but not on android in bare workflow

### ISSUE THREAD

**Issue by SergueyML** [expo/expo#11305]
## 🐛 Bug Report

Hi! I am trying to implement the expo-constants build scripts as described here https://github.com/expo/expo/tree/master/packages/expo-constants
And I think that there's something wrong with the gradle file as I'm getting the following warning when logging Constants.manifest on android

```
Constants.manifest is null because the embedded
app.config could not be read. Ensure that you have installed the expo-constants build scripts if you need to read from Constants.manifest.
```

The iOS script works fine.

I am running this in a Bare app using SDK40 (Android 10 and iOS 14)

**Comment by hardcodet** [comment]
(assuming you did set the build scripts for Android and iOS as described under the link you posted)

I just went through the same exercise. Somehow, my expo CLI still thought (thinks) I'm on SDK 39 and installed an older version of the `expo-constants` package for me, which doesn't contain the `scripts` folder.. Once I manually set package.json to use the latest, it worked.

**Comment by brentvatne** [comment]
make sure you're using expo-constants@9.3.4: https://github.com/expo/expo/blob/master/packages/expo-constants/package.json#L3

@hardcodet - make sure the expo pkg and sdkVersion in app.json (if you have the latter, it's optional) is sdk 40

**Comment by brentvatne** [comment]
post a reproducible example if the issue persists after the above and i'll reopen

**Comment by SergueyML** [comment]
Thanks! It was indeed a version mismatch 🙂
