### ISSUE TITLE
Video: Reports of `onReadyForDisplay` never getting called on iOS

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1131]
https://forums.expo.io/t/onreadyfordisplay-not-triggering-for-video/5655

**Comment by Noitidart** [comment]
Thank you @terribleben for helping me with this. I was on iOS. I'm not sure if it's the same situation on Android.

**Comment by sjchmiela** [comment]
It looks like `onReadyForDisplay` isn't called when `useNativeControls` is `true`. Looking into it!

**Comment by Noitidart** [comment]
Thank you @terribleben!

**Comment by teod** [comment]
This still does not work for me with expo v32.

**Comment by sjchmiela** [comment]
If so, could you please create a new bug report on this repo with all the required details? 🙂

**Comment by shirohana** [comment]
Seems related to https://github.com/expo/expo/issues/3649/.
