### ISSUE TITLE
Migration from SDK 37 to 40

### ISSUE THREAD

**Issue by LorhanSohaky** [expo/expo#11314]
### Summary of Issue 
After upgrade to Expo 40, I ran `expo start` and this error happened.

![async_storage](https://user-images.githubusercontent.com/16273730/101839565-5d49a880-3b21-11eb-838e-466e8770ff44.jpeg)

![metro_bundler](https://user-images.githubusercontent.com/16273730/101839567-5de23f00-3b21-11eb-924b-f7139daba189.jpeg)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 4.0.13 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: bare

**Comment by brentvatne** [comment]
you have a bare workflow project, you should add `@react-native-community/async-storage` and run pod install. as suggested in the instructions in the release notes, you should follow the upgrade steps from the react-native upgrade helper when upgrading bare projects

**Comment by LorhanSohaky** [comment]
@brentvatne I already using `@react-native-community/async-storage`

![image](https://user-images.githubusercontent.com/16273730/101842217-5709fb00-3b26-11eb-860f-c7efe302bbfb.png)

![image](https://user-images.githubusercontent.com/16273730/101842234-5ffacc80-3b26-11eb-8d0a-b95867ce9206.png)

**Comment by LorhanSohaky** [comment]
@brentvatne , please reopen

**Comment by hyochan** [comment]
![Screenshot from 2020-12-12 16-44-47](https://user-images.githubusercontent.com/27461460/101978649-d53ade80-3c99-11eb-9e3c-53937d4d8630.png)

I am also facing above issue in new expo sdk 40 (from sdk 39).
The reproducible project is in https://github.com/dooboolab/hackatalk/pull/325 currently in pending status.

**Comment by hyochan** [comment]
@brentvatne Hope you can have a look :pray:

**Comment by brentvatne** [comment]
@hyochan: https://github.com/dooboolab/hackatalk/blob/upgrade/expo-40/client/metro.config.js#L2-L16

you should use `@expo/metro-config` instead so that it uses the appropriate base sourceExts (the default metro config does not include `.expo.js` files, which is needed in managed workflow for a variety of things to work)

**Comment by brentvatne** [comment]
@LorhanSohaky - maybe you have the same issue as above. if not, please create a new issue and fill out the issue template properly. notice how i was able to help @hyochan quickly here because i could actually look at the source code :P 

i cannot help you without a reproducible example, ideally something minimal

**Comment by hyochan** [comment]
@brentvatne Thank you! That did the trick :100:

**Comment by seyaobey** [comment]
@brentvatne I'm having the same issue, just upgraded from 39 to 40. I tried to use your solution by using `@expo/metro-config` in my `metro.config.js` by changing this line (previously):

`const { getDefaultConfig } = require("metro-config");`

to this line:

`const { getDefaultConfig } = require("@expo/metro-config");`

But now I'm getting this new error:

`The "path" argument must be of type string. Received undefined`

`TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

**Comment by brentvatne** [comment]
@seyaobey - as in the docs: https://docs.expo.io/guides/customizing-metro/

```
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);
```

it requires the path param

**Comment by seyaobey** [comment]
@brentvatne Thanks you so much, it has worked! (I was so stressed, I could not see it from the guides...)
