### ISSUE TITLE
Ionicons SDK 40

### ISSUE THREAD

**Issue by valdrox** [expo/expo#11324]
### Summary of Issue 
Ionicons missing in SDK 40. I'm not sure if this is intentional, but it wasn't listed in the [release blog post](https://blog.expo.io/expo-sdk-40-is-now-available-d4d73e67da33).

### Reproducible Demo
(App.js)
```
import { Ionicons } from "@expo/vector-icons";

export class App extends Component {
  render() {
    return (
      <View>
        <Ionicons name="md-filing" size={30} /> // doesn't work 
        <Ionicons name="md-paper" size={30} /> // doesn't work
        <Ionicons name="md-paper-plane" size={30} /> // works
      </View>
    );
}}
```

 
### Steps to Reproduce
run the code above. 

### Expected Behavior vs Actual Behavior
All Icons should appear, or the blog post should show that there has been updates in Ionicons too. I didn't try other sets so I don't know if this is an isolated issue or not. If anyone else sees this I believe this https://oblador.github.io/react-native-vector-icons/ is the up to date icon directory.

**Comment by brentvatne** [comment]
these icons don't exist in the latest version of @expo/vector-icons

https://icons.expo.fyi/ is the source you should refer to. if you don't see "@expo/vector-icons@12.0.2" in the header of this page, press cmd+shift+refresh (or whatever the equivalent is on your operating system to reload without cache)

also notice that if you use typescript you can get validation for this:

<img width="566" alt="Screen Shot 2020-12-11 at 10 48 57 AM" src="https://user-images.githubusercontent.com/90494/101942511-7b092300-3b9e-11eb-9496-f82fc55de63c.png">
