### ISSUE TITLE
[expo-av] RecordingInstance.startAsync() did not handle error when another app is recording. This causes empty audio.

### ISSUE THREAD

**Issue by kidfrom** [expo/expo#11325]
### Summary of Issue 
The expo-av did not handle error when another app is recording. This causes `RecordingInstance.getStatusAsync()` to not return Promise. The only known fix is to went back to `Foreground Mode`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.27.6 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible Demo
[App.js](https://github.com/kidfrom/learn-react-native-2/blob/master/record_audio_expo/App.js)
 
### Steps to Reproduce
1. Record audio on other app e.g Instagram
2. Invoke `RecordingInstance.startAsync()` e.g through Hardware Key Event.
3. The recording will be started without throwing an error.
4. Stop the recorder.
5. Play the recorded audio. The audio is empty.

### Expected Behavior vs Actual Behavior

Expected behavior: The `RecordingInstance.startAsync()` will throw error if invoked while other app is recording.
Actual behavior: The `RecordingInstance.startAsync()` start the recorder but it will not record anything.

**Comment by AdamJNavarro** [comment]
Hey @kidfrom, have you been able to test this on iOS to see if the same behavior occurs?
