### ISSUE TITLE
Expo 40 does not display the splash image.

### ISSUE THREAD

**Issue by kevinvuillemin** [expo/expo#11339]
### Summary of Issue
Expo 40 does not display the splash image.

### Environment 
Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.21.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.25.1

### Steps to Reproduce
```
expo init
yarn start
```

### Expected Behavior vs Actual Behavior
Expo 40 does not display the splash image even after the ios or android builded.

**Comment by byCedric** [comment]
Hi @kevinvuillemin, thanks for the issue report. Unfortunately, I can't reproduce this on my end. Do you have an example project where this happens, and/or more context on how to trigger this issue?

![issue-11339](https://user-images.githubusercontent.com/1203991/102090001-3808b300-3e1d-11eb-962d-737990d098e0.gif)

**Comment by maxkudla** [comment]
@kevinvuillemin Have u find a problem?

**Comment by kevinvuillemin** [comment]
@maxkudla  No I'm sorry, I downgraded to 39 because I was hurry.

**Comment by brentvatne** [comment]
if someone encounters any problems with splash screens in sdk 40 please create a new issue and fill out the issue template so that we have the information that we need to help! thanks!
