### ISSUE TITLE
Expo 40 splash image not working

### ISSUE THREAD

**Issue by kevinvuillemin** [expo/expo#11338]
On version 40 of expo, the splashscreen does not display the image.

**Comment by brentvatne** [comment]
please fill out the issue template:

```
## 🐛 Bug Report

### Summary of Issue <!-- (just a few sentences) -->


### Environment - output of `expo diagnostics` & the platform(s) you're targeting


### Reproducible Demo

<!--
- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve
-->
<!--
As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!
-->
 
### Steps to Reproduce


### Expected Behavior vs Actual Behavior


```

**Comment by yonahforst** [comment]
@kevinvuillemin - did you figure this out?

**Comment by kevinvuillemin** [comment]
not yet

**Comment by mbui0529** [comment]
Summary:
I have just updated expo from 37.0.0 to 40.0.0. Splash Screen works OK but does not show the image. This happens for both iOS & Android.

Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23
        Build Tools: 23.0.1
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed

Reproducible:

import React, { useState } from "react";
import { NavigationContainer } from "@react-navigation/native";
import AppLoading from "expo-app-loading";

export default function App() {
  const [user, setUser] = useState();
  const [isReady, setIsReady] = useState(false);

  const restoreUser = async () => {
    const user = await authStorage.getUser();
    if (user) setUser(user);
  };

  if (!isReady)
    return (
      <AppLoading
        startAsync={restoreUser}
        onFinish={() => setIsReady(true)}
        onError={console.warn}
      />
    );

  return (
      <NavigationContainer ref={navigationRef} theme={navigationTheme}>
        {user ? <AppNavigator /> : <AuthNavigator />}
      </NavigationContainer>
  );
}

Expected:
Showing the image in splash screen.
Actual:
Only splash screen with background color

**Comment by hunterbmt** [comment]
https://github.com/expo/expo/issues/11460

Upgrading expo-cli to 4.0.16 will help to solve this problem.

**Comment by zyadkhalil** [comment]
Upgrading expo-cli did the job for me too!
