### ISSUE TITLE
Empty Recaptcha window using expo-firebase-recaptcha

### ISSUE THREAD

**Issue by manupeco** [expo/expo#11341]
## 🐛 Bug Report
White reCaptcha window using the expo-firebase-recaptcha

### Summary of Issue 
I have followed the code example at https://docs.expo.io/versions/latest/sdk/firebase-recaptcha/ but when my code call 

`await phoneProvider.verifyPhoneNumber(phone, recaptchaVerifier.current)`

the webview opens but it's empty

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

`Expo CLI 3.28.2 environment info:
    System:
      OS: macOS Mojave 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 16, 19, 22, 23, 26, 27, 28
        Build Tools: 19.1.0, 21.0.0, 21.0.1, 21.1.2, 22.0.0, 22.0.1, 23.0.0, 23.0.1, 26.0.2, 27.0.0, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0
        System Images: android-22 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed
`

### Reproducible Demo

Take the example https://snack.expo.io/@manupeco/mtm

### Steps to Reproduce
Replace with your firebase config, put your phone in the code (line 34) and click Next.

### Expected Behavior vs Actual Behavior
The webview opens without any image or button to interact except 'Cancel'. I should have a way to prove I'm human and continue the flow

**Comment by byCedric** [comment]
Hi @manupeco, thanks for the issue report. Unfortunately, I can't reproduce this issue on my end. Do you have more context on the environment the app is running in or specific steps to trigger the issue?

![captcha](https://user-images.githubusercontent.com/1203991/102087993-93857180-3e1a-11eb-9b1c-469d6da4cdda.gif)

**Comment by manupeco** [comment]
Hi, 
I have the issue testing directly on https://snack.expo.io/@manupeco/mtm I have the issue as you can see in the video.

![video_recaptcha](https://user-images.githubusercontent.com/1726528/102090858-460b0380-3e1e-11eb-9281-777c856927c7.gif)

**Comment by manupeco** [comment]
Hi @byCedric ,
any chance to share a firebase project config on which the code works for you?

Best

**Comment by Vindi-Van** [comment]
I have that enabled and still see a blank screen, any solution to this?

**Comment by Imtiajrex** [comment]
@Vindi-Van did you solve it?
