### ISSUE TITLE
iOS: There was an error with this build

### ISSUE THREAD

**Issue by magician11** [expo/expo#1134]
I ran the Android build it worked fine.

FYI for Android: `[exp] Build ID: 99f0197f-b2a6-47d1-a8b3-289d5efb8bf1`

There is an issue with building for iOS though.  The only output I see when typing `exp build:status` is

```
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build.
```
The build ID for this iOS build is

`[exp] Build ID: 20ae24ef-139a-40b8-a602-ea3a21079c4b`

--- 
Side note: the log messages for building either iOS or Android, both say they're building both bundles... and I don't think that's right?

```
[exp] Loading dependency graph.
[exp] Dependency graph loaded.
[exp] Tunnel connected.
[exp] Publishing...
[exp] Building iOS bundle
[exp] Finished building JavaScript bundle in 34103ms.
[exp] Building Android bundle
[exp] Finished building JavaScript bundle in 22294ms.
[exp] Analyzing assets
```

**Comment by lbayarkhuu** [comment]
Same error here. Android build works fine. But ios build got this error. My ios build ID: 41c94708-6bd6-4090-b1b0-adbb6eee0f99. Please help, why I get this error?

**Comment by ide** [comment]
@magician11 

There was a macOS keychain error on our end. Can you try your build again?

---

@lbayarkhuu The log for your build included:
```
Starting login with user '<apple id>' Couldn't find team with ID '<team id>'.
```

Is your Apple ID associated with the team? You may want to try giving it admin privileges too so it can create certificates and provisioning profiles when needed.

**Comment by magician11** [comment]
@ide worked now for me thanks.
