### ISSUE TITLE
Failed to render local img list

### ISSUE THREAD

**Issue by mofengfs** [expo/expo#11347]
### I try to use local images, require quotes. But error: Module ../assets/img/1.jpg not declared as a System.registerDynamic dependency of module://App.js.js

```
expo": "^40.0.0",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz",
```

[my snack](https://snack.expo.io/@fengmo/imagelist)

**Comment by AdamJNavarro** [comment]
Hey @mofengfs, you can't pass dynamic strings to a `require` call. This is an expected error. You can pass an entire require call as a value to your `posterUrl` prop however.

Cheers,
Adam
