### ISSUE TITLE
More details on Expo push token

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#1135]
Hi,

I'd like to have more details in the docs about the Expo push token if possible:

https://docs.expo.io/versions/latest/guides/push-notifications.html

- Is this token unique per device?
- If the user uninstall and re-installs the app does the token change?
- What if the user resets the device?

Thanks!

**Comment by ide** [comment]
@pensierinmusica Thanks for the questions! We should add them to the docs but to answer them here:

- Is this token unique per device?
  - **Yes. No two devices should have the same Expo push token.**
- If the user uninstall and re-installs the app does the token change?
  - **Yes, the Expo push token will change if the app is re-installed.** The native device token may or may not change (totally up to the OS).
- What if the user resets the device?
  - **Yes, the Expo push token will change if the device is reset. But if it's restored from a backup, the Expo push token should be restored.**

**Comment by pensierinmusica** [comment]
@ide thanks for the clarifications! Do you want me to send a pr for the docs? Cheers

**Comment by ide** [comment]
Sure, feel free to send a PR!

**Comment by pensierinmusica** [comment]
@ide done!  :)

**Comment by dailycommit** [comment]
What if **multiple** users are using the same device?

Will ``Notifications.getExpoPushTokenAsync()`` return a different value each time, or is it the only value created for a particular range of time to each devices?

Is there a way to delete the push token from the expo server ? something like ``Notifications.removeExpoPushToken("ExponentPushToken[blablablabla]")`` ?

**Comment by ide** [comment]
Multi-user: If the OS keeps each user's installed apps separate (ex: separate accounts at the OS level) then they will get separate Expo push tokens. On an OS like iOS, there will be just one Expo push token. This isn't anything specific to Expo and is how mobile works.

Expo push token stability: the Expo push token is stable for the installation of the app. The docs cover this in more detail.

Revocation: there isn't a token deletion API. When Apple or Google deems that you should not send notifications to a token anymore for whatever reason they choose (ex: app was uninstalled, user disabled notifications, or any other reason that Apple or Google has), Expo will send you back a DeviceNotRegistered error.

**Comment by jeandelavarene** [comment]
I couldn't find in the doc the size of the token which is needed for the design of the table column that will store it. What's the max size of the token? Thanks.

**Comment by ide** [comment]
The token size and format may vary. It is guaranteed to be a string. We recommend using a variable-sized string field.

**Comment by machester4** [comment]
There is a problem every time you reinstall the app you will get a new token that will be useless since only the token of the first installation will be operative and you will get the **DeviceNotRegistred** error. Is there any way to get the token that is really operational?

**Comment by ide** [comment]
@machester4 On Android you should set up FCM. Search the docs for the guide on FCM keys. On iOS you should encounter DeviceNotRegistered infrequently assuming the device has give permission to send notifications.

**Comment by morenoh149** [comment]
@ide I need a max length for the expo token, what's a good number? 200?

**Comment by ide** [comment]
We use 4096 in our database but would increase it if needed. Most SQL databases, if that's what you're using, don't need a limit though (plain VARCHAR is fine).

**Comment by morenoh149** [comment]
ah, using django's model api I was trying with `CharField` but it sounds like `TextField` is more appropriate.

**Comment by dellwatson** [comment]
> Multi-user: If the OS keeps each user's installed apps separate (ex: separate accounts at the OS level) then they will get separate Expo push tokens. 
@ide 

can you elaborate what u meant ? i don't quite get it,
can I give u my scenario? im building e-commerce apps, every time the user login-account, the apps will send the expo-device-id along with access token to the database, and everytime the user logout, the database would clear the expo-device-id, 

so let's say the user change account and re-login with new account in the apps that haven't been re-install, will the apps generate another unique expo-device-id again ? because it doesnt seem so,
resulting my database will send notification to the previous account while currently login with different account because the user have the same device. and the endpoint of push API is require expo-device-id only.

It seems Im surely wrong and can you please correct my mistake ?

**Comment by ide** [comment]
@dellwatson My comment was referring to OSes that support multiple logins. It sounds like you are building your own login system but the OS is still single-user.

**Comment by yoojeen126** [comment]
@ide I have same issue. 
i had save my push token in my db when running app. but reinstall app push token added different token. the before token pushing its not worked, new token is work fine. how i know is not available token ? no problem with app running, but this make more available  data
