### ISSUE TITLE
Can't get `expo-camera` to build using `react-scripts`

### ISSUE THREAD

**Issue by jmccarrell-lmi** [expo/expo#11358]
### Summary of Issue 
I started a fresh project using `npx react-native`, and then following the best instructions ive found thus far for `react-native-web`: https://medium.com/@aureliomerenda/create-a-native-web-app-with-react-native-web-419acac86b82

This worked nearly perfectly [I only needed to remove eslint from package.json]

I added `expo-permissions` without a problem
but when i added `expo-camera`, I ran into a missing dependencies
```
Module not found: Can't resolve '@unimodules/core' in './ReactNativeWebApp/node_modules/expo-camera/build'
```

So i ran `yarn add react-native-unimodules` as suggested by the `@unimodules/core` README
But then I recieve a loader error:
```
./node_modules/expo-camera/build/WebUserMediaManager.js 142:19
Module parse failed: Unexpected token (142:19)
>   return isCapable?.deviceId || hasCamera?.deviceId || null;
```

I could keep going, adding a webpack config file to use babel on this specific node module, but I feel I shouldn't have ran into all of these issues from a fresh project.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
targetting web using `react-scripts` on Mac OS X 10.15.7 Catalina

`expo diagnostics`
```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.0 - ~/.volta/tools/image/node/14.15.0/bin/node
      Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
      npm: 6.14.8 - ~/.volta/tools/image/node/14.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: 0.14.9 => 0.14.9 
    Expo Workflow: bare
```

### Reproducible Demo
Follow the tutorial linked above, then `yarn add expo-camera`, then import it `import {Camera} from 'expo-camera';`

 
### Expected Behavior vs Actual Behavior

The project to compile and preferably the camera preview shows up.

**Comment by jmccarrell-lmi** [comment]
I just noticed `expo-camera` has a LOT of peer dependencies. So I suppose I'll have to install all of them.

This is not a good user experience.

**Comment by jmccarrell-lmi** [comment]
Now I'm getting the following with `expo-permissions` with a clean installation. What is going on with the expo library???
```
./node_modules/expo-permissions/build/Permissions.types.js
Module not found: Can't resolve 'unimodules-permissions-interface'
```

**Comment by jmccarrell-lmi** [comment]
A simple problem, built from a tutorial and no response for 7 days.

**Comment by byCedric** [comment]
Hi @jmccarrell-lmi, thanks for writing in. This is a good example of why we provide templates to get started. Projects are relatively complex and require a certain bundler configuration to make them work. It looks like there are multiple things going on here.

1. No support for [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), should be possible through a babel plugin
```
./node_modules/expo-camera/build/WebUserMediaManager.js 142:19
Module parse failed: Unexpected token (142:19)
>   return isCapable?.deviceId || hasCamera?.deviceId || null;
```

2. Looks like either not-configured unimodules or missing support for your project. I would recommend taking a [look at the docs](https://docs.expo.io/bare/installing-unimodules/#usage).
```
./node_modules/expo-permissions/build/Permissions.types.js
Module not found: Can't resolve 'unimodules-permissions-interface'
```

I'm sorry it took so long for a response. But we can't provide support for custom project setups. I hope everything will be a bit more portable in the future.

Hope this helps!
