### ISSUE TITLE
Updating to sdk 24

### ISSUE THREAD

**Issue by omorhefere** [expo/expo#1136]
When I try updating I follow the instruction here: https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51

The problem is that I cannot run "npm install" when i use expo's fork of react-native. can only upgrade when I use this:
"react-native": "^0.51.0"

Could this cause a problem

**Comment by ide** [comment]
You can try using `"react-native": "^0.51.0"` with Expo SDK 24 but we support just the fork because it has some bug fixes. If npm isn't working for you we recommend using Yarn, since most of the people who work on Expo and React Native use it.

**Comment by omorhefere** [comment]
@ide Thank you, I used yarn and it worked. also it solved my issue
