### ISSUE TITLE
useFocusEffect not working after update to Expo SDK 40

### ISSUE THREAD

**Issue by pcm-binhpd** [expo/expo#11364]
After I update to Expo SDK 40, useFocusEffect function of react navigation v5 is not working. It only works on the first time the screen loaded. On Expo SDK 39, it works normally. Please help me. Customers is claiming me.

**Comment by AdamJNavarro** [comment]
Hey @pcm-binhpd, without a runnable repro example of this I'm afraid we won't be able to help you. If you can create a Snack or a provide a public repository we can clone and run locally, we can circle back and investigate. One other thing I'd recommend is to try creating a vanilla RN project and seeing if the issue occurs. That will help us determine if it could be expo-specific or not.

Cheers,
Adam
