### ISSUE TITLE
EAS build iOS permissions on submit (managed workflow)

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo#11376]
When build is made with new EAS build services for ios, when I upload to app store it says that build has invalid binary.

I was uploading with transporter and I don't have anymore information why build was rejected because Apple just sent me notification that build was rejected....

**Comment by cruzach** [comment]
Unfortunately without a lot more information, we can't really help here. You should open a new issue and follow the bug report template, including SDK version and a reproducible demo. I tried EAS Build on a managed project myself and it was working, so this is likely something specific to your project

**Comment by cruzach** [comment]
thanks @jurica-penjgusic ! 

Okay, that's much more helpful to include the error messages 😄 it looks like you should add those relevant `NS*` usage description keys to `ios.infoPlist` in your app.json file. You can read here for more info [here](https://docs.expo.io/distribution/app-stores/#system-permissions-dialogs-on-ios) and [here](https://docs.expo.io/versions/latest/sdk/permissions/#permissions-on-ios)

**Comment by brentvatne** [comment]
reopened because there should be consistency between build output of a managed project between eas build and expo build

**Comment by jurica-penjgusic** [comment]
Hi to all,
This is info.plist I am using in project (it's localized info.plist)

{
  "CFBundleDisplayName": "Tekica Biznis",
  "NSCameraUsageDescription": "In order to share your workspace photos we need access your camera.",
  "NSCalendarsUsageDescription": "In order to keep your schedule in sync we need access to your calendar.",
  "NSMotionUsageDescription": "In order to keep your location in sync we need access motion.",
  "NSMicrophoneUsageDescription": "Tekica uses microphone so you can voice interact with app",
  "NSContactsUsageDescription": "In order to establish your customer base we need to access your contacts.",
  "NSLocationWhenInUseUsageDescription": "In order to share location of your office we need access your location.",
  "NSPhotoLibraryAddUsageDescription": "In order to share your workspace photos we need access your camera.",
  "NSRemindersUsageDescription": "Allow Tekica to remind you about upcoming appointments."
}

**Comment by keomabrun** [comment]
Hi all,

Any update on this ? I face the same issue. I build my info.plist dynamically (with locales) using 
```
    infoPlist: {
        "CFBundleAllowMixedLocalizations": true,
        "NSCameraUsageDescription": true,
        "NSPhotoLibraryUsageDescription": true,
        "NSLocationWhenInUseUsageDescription": true,
        "NSLocationAlwaysUsageDescription": true
    },
```
I use sdkVersion: `42.0.0`

**Comment by brentvatne** [comment]
@keomabrun - you need to use strings for those values, eg:

` "NSPhotoLibraryUsageDescription": "This app wants to read your photo library in order to share photos with friends"`

**Comment by dqii** [comment]
I got the error
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

With eas build but not with expo build. Is there any reason why there would be an inconsistency?

**Comment by dqii** [comment]
Ah, that was what was going on, thank you. I was using @stripe/stripe-react-native (which didn't work properly with expo build) and didn't realize it had NSCameraUsageDescription

**Comment by brentvatne** [comment]
oh interesting! i did not know that. thanks for sharing
