### ISSUE TITLE
EAS android build (managed workflow)

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo#11386]
When app is built with new EAS and release channel isn't published, only set to a new channel eg. staging, app crashes on start.

In attachment is screen shot.
Is it correct behaviour or bug?

![Screenshot_2020-12-16-21-43-28-906_com miui bugreport](https://user-images.githubusercontent.com/26301007/102404469-127bd500-3fe8-11eb-9988-b6e1f8b8a0ac.jpg)

**Comment by brentvatne** [comment]
@jurica-penjgusic - this looks like there is some code in your app that is looking for releaseChannel, we'd have to see your app code to have a better idea. happy to investigate but need more info to understand if this is a bug or not.

**Comment by jurica-penjgusic** [comment]
@brentvatne  I can add you to my repo if you like and you will always get an app :)
