### ISSUE TITLE
Can't create bare workflow for iOS with latest version of the Xcode and Expo

### ISSUE THREAD

**Issue by DjordjePetrovic** [expo/expo#11385]
## 🐛 Bug Report

Creating fresh project, running `expo init newProject` everything passes properly, but after running `yarn ios` error is thrown -> 

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/djordjepetrovic/Library/Developer/Xcode/DerivedData/novo-gqarluookuikzgfofeadeaxktbfs/Build/Intermediates.noindex/novo.build/Debug-iphonesimulator/novo.build/Objects-normal/x86_64/AppDelegate.o /Users/djordjepetrovic/Documents/novo/ios/novo/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

### Environment

```
Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: bare
```

### Expected Behavior vs Actual Behavior

Bare workflow working for the iOS

**Comment by brentvatne** [comment]
hi there! please open the project in xcode, clean the build, and try again. looks like an intermittent issue on the xcode side

**Comment by DjordjePetrovic** [comment]
@brentvatne thanks for the quick answer! After doing that I got this error actually 

<img width="741" alt="Screenshot 2020-12-16 at 21 01 42" src="https://user-images.githubusercontent.com/6237097/102400278-fa08bc00-3fe1-11eb-9222-2be730b01b47.png">

Doing `pod install `l did not help

**Comment by brentvatne** [comment]
ah ok, this is related to a recent change I made to leave out flipper. it worked on a release build but was problematic here. you can uncomment lines in podfile related to flipper, and i published updated templates that rolls that back.

flipper approximately doubles build times, so i'm looking at making it easier to leave it out

**Comment by DjordjePetrovic** [comment]
@brentvatne Interesting, Thanks! So fix for it will be published soon?

**Comment by brentvatne** [comment]
yeah it already is. but you can fix your initialized project by uncommenting lines related to flipper in your ios/Podfile and then running pod install

**Comment by brentvatne** [comment]
-- but in terms of build times, there's more work to be done around this

**Comment by DjordjePetrovic** [comment]
@brentvatne Thanks for the quick answer!

**Comment by brentvatne** [comment]
no problem, sorry for the hassle

**Comment by brentvatne** [comment]
disabled flipper by default again: https://github.com/expo/expo/commit/ca63d56b522a94d2a6947d7a5905542c7b8370cd

just needed to update the ifdef directive to also check whether the flipper header exists
