### ISSUE TITLE
Expo-AV Audio limitation causing bug?!

### ISSUE THREAD

**Issue by aliakhgar** [expo/expo#11387]
Hi, Im trying to build an MusicPlayer Application which plays musics & playlists. Every time user plays an audio I’ll first unload and load new uri to expo-av. And Every time user hits next button, I’ll unload and loadAsync the next uri in my expo-av.
The problem is,the expo-av only allows unloadAsync when loadAsync has finished loading the current uri. So if user hits next button 4-5 or more times rapidly, the playNext function will be called and run many unload and loads which causes a mes. for example, application may freeze for many loads or plays multiple songs(only when I recreate new player) or even a big delay to load and unload all uri’s!
This is because in my playNext button I cant stop or unload the current loading uri ASAP! and causing me nasty bug.
I have also done the below methods:
1.Recreate new player and destroy the last player every time user hits next!
2.Use an next-uri’s-holder array and add next uri to the array and play the last uri after an amount of time with Timers.(and such workarounds)
3.Using lodash debounce with function.
4.Using other ways like using with redux or so…
But nothing works and I have stuck here.
Any help is appreciated, any links to helpful source codes is also nice.
Thanks.

**Comment by AdamJNavarro** [comment]
Hey @aliakhgar, as this seems to be an issue with implementation rather than a bug pertaining to the module, I'm going to close this issue. As for some source code examples, take a look at the playlist example here: https://github.com/expo/playlist-example

It's a little out of date but the `AV` modules have largely remained the same so it should mostly still apply to the currently supported SDK versions.

Cheers,
Adam

**Comment by aliakhgar** [comment]
Hi, Im reopening this issue because expo-av example itself is working explained bug above. Expo-av example just disables the controls on file load which is a workaround itself! If you prevent controls disable in example the same bug happens.
Please tag this issue has an "Improvement" because there is literally NO AUDIO PLAYER package out for react native!
expo sdk should really improve this part because large community using expo-av and so large community is having "Not Stable" music player!!!
sorry for bad english.
Thanks.
