### ISSUE TITLE
AsyncStorage and developing with Expo client in Bare Workflow

### ISSUE THREAD

**Issue by jparkrr** [expo/expo#11388]
### Summary of Issue 

My question is similar to https://github.com/expo/expo/issues/10627, but it's about developing a bare app that uses async storage with the expo client.

Running `expo start` causes an error: `[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null`

According to the [docs](https://docs.expo.io/bare/using-expo-client/) it should be possible to use the expo client with the bare workflow, or does AsyncStorage preclude me?

I'm guessing it's for the reason @brentvatne stated here: https://github.com/expo/expo/issues/11195#issuecomment-737488025, except I am in the bare workflow so the `ios` directory must be present.

Thanks for taking a look!

### Environment

<details>
 <summary>Environment</summary>

```
  Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/opt/node@14/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: bare
```

</details>

### Reproducible Demo

A newly init-ed bare app with just `@react-native-community/async-storage` imported.
https://github.com/jparkrr/bare-in-client-asyncstorage/blob/main/App.js

 
### Steps to Reproduce
`expo start` and open in iOS simulator

### Expected Behavior vs Actual Behavior
Expected: AsyncStorage works

Actual: `Uncaught Error: Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null`

**Comment by jparkrr** [comment]
If this is difficult to accomplish, I'd also be open to suggestions of some way of stubbing out async storage to do nothing when running in the client.

**Comment by jparkrr** [comment]
I'm also seeing the same problem with sentry-expo.

**Comment by brentvatne** [comment]
hi there! 

you will need to do this:

```
EXPO_TARGET=managed expo start
```

i tried it on your example project and it worked. related to this issue: https://github.com/expo/expo-cli/issues/3005

going to track it there. sorry for the hassle!
