### ISSUE TITLE
Intent.ACTION_SET_WALLPAPER In React Native

### ISSUE THREAD

**Issue by Belgin-Android** [expo/expo#11389]
Hope We Can Have ` Intent.ACTION_SET_WALLPAPER` In React Native.
There are no modules out there with this functionality. 

I searched a lot on google but couldn't find any solution to set wallpaper in react native 
but came across intent and found solutions like the one's below

```java
    Intent intent = new Intent(Intent.ACTION_ATTACH_DATA);
    intent.addCategory(Intent.CATEGORY_DEFAULT);
    intent.setDataAndType(uri, "image/jpeg");
    intent.putExtra("mimeType", "image/jpeg");
    this.startActivity(Intent.createChooser(intent, "Set as:"));
```

```java
Intent intent = new Intent(Intent.ACTION_SET_WALLPAPER);
startActivity(Intent.createChooser(intent, "Select Wallpaper"));
```

There are Mostly Unanswered Questions In Stackoverflow

https://stackoverflow.com/questions/18700161/android-set-wallpaper-using-intent

**Comment by AdamJNavarro** [comment]
Hey @Belgin-Android, we try our best to keep github issues reserved for reproducible and actionable bug reports. For feature requests such as this one, please direct them to our [Canny Board](https://expo.canny.io/)!

Cheers,
Adam
