### ISSUE TITLE
expo-updates ios build fails

### ISSUE THREAD

**Issue by freemanUA** [expo/expo#11397]
Hello, trying to add expo-updates in existing app,
I installed unimodules succesfully and performed all steps for expo-updates.
when I trying to build ios in release mode I getting this error:
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere

info Writing bundle output to:, /Users/xxxx/Library/Developer/Xcode/DerivedData/xxxx-axgsklnfgnpueteilfvzgeietcbj/Build/Products/ReleaseDev-iphonesimulator/xxxx.app/main.jsbundle
info Done writing bundle output
info Copying 261 asset files
info Done copying assets
+ [[ false != true ]]
+ [[ ! -f /Users/andrey/Library/Developer/Xcode/DerivedData/xxxxx-axgsklnfgnpueteilfvzgeietcbj/Build/Products/ReleaseDev-iphonesimulator/xxxxx.app/main.jsbundle ]]
                    Welcome to Metro!
              Fast - Scalable - Integrated

Failed to construct transformer:  TypeError: Transformer is not a constructor
    at getTransformCacheKey (/Users/xxxxx/Documents/workspace/xxxxx/xxxxxx/node_modules/metro/src/DeltaBundler/Transformer/getTransformCacheKey.js:33:31)
    at new Transformer (/Users/xxxxx/Documents/workspace/xxxxxx/xxxxx/node_modules/metro/src/DeltaBundler/Transformer.js:147:28)
    at Bundler._depGraphPromise.then.dependencyGraph (/Users/xxxxx/Documents/xxxxx/xxxxx/xxxxxx/node_modules/metro/src/Bundler.js:54:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. Cannot read property 'transformFile' of undefined
    at /Users/xxxxxx/Documents/xxxxxx/xxxxxxxx/xxxxxxx/node_modules/expo-updates/scripts/createManifest.js:27:11
    at process._tickCallback (internal/process/next_tick.js:68:7)
Command PhaseScriptExecution failed with a nonzero exit code

project is freshly updated:

"react": "16.13.1",
 "react-native": "0.63.4",
"metro-react-native-babel-preset": "0.59.0",
"react-native-unimodules": "^0.12.0",
"expo-updates": "^0.4.1",

**Comment by freemanUA** [comment]
Apparently I had "metro-config" 0.64 version. Should be 0.58

**Comment by appinteractive** [comment]
@freemanUA When upgrading to SDK 40 you sould swith to `@expo/metro-config` as described here: https://docs.expo.io/guides/customizing-metro/

**Comment by freemanUA** [comment]
@appinteractive I am using expo-updates in bare app workflow. Don't see any remarks about that in docs.

**Comment by appinteractive** [comment]
I see, still it could be useful for others 😬
