### ISSUE TITLE
_expo.Font.style is not a funtion

### ISSUE THREAD

**Issue by muratozgul** [expo/expo#1139]
Upgraded expo from 23.0.0 to 24.0.0
Started to get this error (originating from `node_modules/@expo/vector-icons/createIconSetFromFontello.js`):

<img width="411" alt="screen shot 2017-12-20 at 11 48 28 am" src="https://user-images.githubusercontent.com/4857407/34226522-c62c1d0c-e57e-11e7-8b00-75900b1268ae.png">

**Comment by ide** [comment]
Font.style was deprecated and then removed. You may have some old code still depending on it.

**Comment by muratozgul** [comment]
My problem will probably be solved with this [commit](https://github.com/expo/vector-icons/commit/5ecca09e6f1f00d4693fcc832ba9893edcb39fd0) to @expo/vector-icons.

**Comment by ide** [comment]
24.0.2 was published with this fix recently.

**Comment by muratozgul** [comment]
Thanks!
