### ISSUE TITLE
Could  not load app. Are you sure XDE or exp is running? Netwok Response time out

### ISSUE THREAD

**Issue by Bharanitharan06** [expo/expo#11392]
HI, am new to expo ,  Am trying to run app in my windows 10 but its not able to run. My laptop and device is connected with same network. REACT_NATIVE_PACKAGER_HOSTNAME IP is also same of  IPv4 Address. I tried LAN and WIFI both and I offed firewall, make connection in private. allowed ports in inbound. after done these all the thinks still am getting error and in my devices should Constant IP for PORT which is not related to any of my LAN, WIFI, laptop, devices and port, i don't know how to fix it.
OS: windows 10

Node :v12.14.0
npm : 6.13.4
"expo": "^33.0.0",
![Screenshot_2020-12-07-09-47-42-479_com eventzilla attendee app 1](https://user-images.githubusercontent.com/62028631/102478983-4a385a80-4084-11eb-83ec-85d9e39ff546.jpg)
![Screenshot_2020-12-07-09-47-36-388_com eventzilla attendee app 1](https://user-images.githubusercontent.com/62028631/102479120-7f44ad00-4084-11eb-9ccc-ad321cb5633f.jpg)

@expo-ci  @expo-ci

**Comment by AdamJNavarro** [comment]
Hey @Bharanitharan06, you are running some rather outdated versions of our tools. Both XDE and exp have been replaced for quite some time. I would recommend uninstalling what you currently have in your environment and then running either `npm i -g expo-cli` or `yarn global add expo-cli`. Also, make sure you have downloaded the latest version of the Expo client either from the Play Store or if you are using an emulator via the command `expo client:install:android`.

If you still have issues once you're using the updated tools, please feel free to post on our [Forums](forums.expo.io)!

Cheers,
Adam
