### ISSUE TITLE
Specifying a sound during a push notification fails silently if pushing to android device

### ISSUE THREAD

**Issue by Kilowhisky** [expo/expo#11390]
### Summary of Issue 
If you specify a value for `sound` on a push payload other than `null` or `default` the push response will still be a successful response but with no content. The message will never make it to the app.  The documentation indicates that this is an 'iOS Only' property but makes no mention that it will cause android notifications to fail.

Here is documentation stating it can be done. https://docs.expo.io/push-notifications/sending-notifications/#message-request-format

The expo push tool doesn't let you specify a sound at all. 
https://expo.io/notifications  

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
_Expo CLI 4.0.13 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^39.0.4 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed_

### Steps to Reproduce
1) Register for push notifications
2) Generate a push notification with the `sound` field set to anything other than `null` or `default`. 

### Expected Behavior vs Actual Behavior

The notification should still submit.  Instead it fails silently.

**Comment by cruzach** [comment]
Since the documentation says that `sound` only accepts `'default' | null`, why are you passing something other than one of those values?

**Comment by Kilowhisky** [comment]
Welp that's a late night misread....
