### ISSUE TITLE
Expo-av player scrollbar issue 

### ISSUE THREAD

**Issue by brahul0410** [expo/expo#11407]
We have developed an application using expo and we are using video player as expo-av, we are trying to play a video of 200MB using this player and below are our observations
- It start video very quick and working fine
- if we directly put out finger in any place scroll bar it start video from that position immediately without any delay  
 Issue:
When we drag pointer in scroll bar to a future point it hang and video never start. 

How to impose same behavior like selecting a future point while dragging pointer to middle of  video (Like if video is for an hour then directly selecting any point touching that place works fine but if I drag pointer till 40 Min it will hang and not start video)

**Comment by AdamJNavarro** [comment]
Hey @brahul0410, without seeing any code, relevant version numbers or platforms it will be hard to provide any insight here. Please share a publicly accessible repo and provide as much relevant information as you can.

Cheers,
Adam
