### ISSUE TITLE
Whenever I install  @react-navigation/bottom-tabs after installing all it's dependencies. I end up getting indefinite crashing when my device(socket) is connected

### ISSUE THREAD

**Issue by shelcia** [expo/expo#11404]
Github Link : https://github.com/shelcia/farmer-app

Terminal Output:

ℹ ｢wds｣: Project is running at http://0.0.0.0:19006/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /usr/local/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/web-default
ℹ ｢wds｣: 404s will fallback to /
Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shelciaabi/.npm/_logs/2020-12-18T07_46_53_042Z-debug.log

**Comment by AdamJNavarro** [comment]
Hey @shelcia, I'm getting a `404` when trying to access your repo. Can you please update the issue with a working link?

Cheers,
Adam

**Comment by shelcia** [comment]
I am so sorry ... here's the update link -> https://github.com/shelcia/farmerapp

**Comment by hamedmam** [comment]
hey @shelcia I also ran into similar issue, it is because you don't have `watchman` , if you are using mac simply run
```
$ brew update
$ brew install watchman
```
if you don't have brew you can do
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
