### ISSUE TITLE
Location.getCurrentPositionAsync({}) does not return value

### ISSUE THREAD

**Issue by maralihart** [expo/expo#11400]
### Summary of Issue 
When following the expo-location tutorial, getCurrentPositionAsync({}) never returns a value

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/mara/.rvm/rubies/ruby-2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

iPhone 12 mini iOS 14.2

### Reproducible Demo

```
import * as Location from 'expo-location';
const [location, setLocation] = useState(null);
    const [errorMsg, setErrorMsg] = useState(null);

    useEffect(() => {
        (async () => {
            const { status } = await Location.requestPermissionsAsync()
            if (status !== 'granted') {
                setErrorMsg('Permission to access location was denied');
                return;
            }
            const locationCall = await Location.getCurrentPositionAsync({});
            setLocation(locationCall);
        })();
    }, []);

    let text = "Waiting...";
    if (errorMsg) text = errorMsg;
    else if (location) text = JSON.stringify(location);
```
 
### Steps to Reproduce
1. Use code above
2. Open iOS 14.2 iPhone 12 mini simulator
3. Accept permissions
4. Wait for "Waiting" text to change to location

### Expected Behavior vs Actual Behavior
Expected: Location is returned
Actual: Infinite wait for location with possible unhandled Promise Rejection warning

![Simulator Screen Shot - iPhone 12 mini - 2020-12-17 at 13 44 08](https://user-images.githubusercontent.com/42477471/102529478-f15dc780-406d-11eb-954b-fefdd80033e9.png)

**Comment by AdamJNavarro** [comment]
Hey @maralihart, this error is thrown when the simulator does not have Location enabled. As the [docs](https://docs.expo.io/versions/v40.0.0/sdk/location/#usage) state, you'll need to enable this before testing it. One important note though, `Location` has now been moved to the "Features" tab instead of "Debug" in the top toolbar.

Cheers,
Adam

**Comment by shizongli94** [comment]
Got the same problem.
Mine solved by installing Google Play Services since I don't already have one on my Android phone. 

It would be nice if the Expo team can do away with Google stuff.
