### ISSUE TITLE
Expo-Device : getDeviceTypeAsync returns TABLET for Motorola G7

### ISSUE THREAD

**Issue by StevenWonder** [expo/expo#11409]
### Expected behaviour
On Motorola G7 phone, `getDeviceTypeAsync` returns PHONE

### Actual behaviour
On Motorola G7 phone, `getDeviceTypeAsync` returns TABLET
Motorola G6 works fine

```
import { DeviceType, getDeviceTypeAsync } from 'expo-device'

getDeviceTypeAsync().then((deviceType) => {
  // deviceType --> DeviceType.TABLET on Motorola G7
})
```

**Comment by AdamJNavarro** [comment]
Hey @StevenWonder, on Android screen dimensions are used to determine device type as detailed here in the [Android documentation](https://developer.android.com/training/multiscreen/screensizes#TaskUseSWQuali). Can you let me know what your leveraging device type for?

Cheers,
Adam

**Comment by StevenWonder** [comment]
We use device type for two reasons
- We have different UI requirements depending if the device is a phone or a tablet
- We have some webviews in our react native app. The web pages are not optimized for tablets so business wants these features only on phones

Motorola G7 phone uses our tablet layout which doesn't render properly. And the webview features are missing

**Comment by outaTiME** [comment]
The same thing happens to me with a T-Mobile REVVLRY+ and a Moto G7 Plus using Expo 45 with EAS, is it something that is planned to be solved in `expo-device`?
Could it be that using `react-native-device-info` I will have the same behavior?

**Comment by outaTiME** [comment]
btw, if i compare both android implementations of `expo-device` and `react-native-device-info`, they are quite similar, except that `react-native-device-info` defines a condition on the treatment of `DisplayMetrics `. Could this be what causes different behaviors on `expo-device`?

Here are both codes:

https://github.com/react-native-device-info/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceTypeResolver.java#L71

https://github.com/expo/expo/blob/sdk-45/packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt#L174
