### ISSUE TITLE
[docs] Broken link in app config } iOS } associatedDomains

### ISSUE THREAD

**Issue by kevgrig** [expo/expo#11413]
Where the broken link is: https://docs.expo.io/versions/latest/config/app/#associateddomains

The broken link:

> See [Apple's docs for config](https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/enabling_universal_links).

**Comment by brentvatne** [comment]
thanks for pointing this out! it looks like apple removed the old link without setting up any redirect or anything 😅 i updated it to https://developer.apple.com/documentation/safariservices/supporting_associated_domains - it'll be fixed next time the schema is deployed and we sync it to the docs

**Comment by kevgrig** [comment]
Thanks!
