### ISSUE TITLE
The expo-font package is not deduped on Expo SDK 40 upgrade

### ISSUE THREAD

**Issue by soullivaneuh** [expo/expo#11417]
### Summary of Issue

Since and upgrade to Expo v40, I noticed the `expo-font` package is not deduped:

```
❯ npm list | grep expo-font@
│ └─┬ expo-font@8.4.0
│ ├─┬ expo-font@8.4.0
```

It was under v39:

```
❯ npm list | grep expo-font@
│ └─┬ expo-font@8.3.0
│ ├── expo-font@8.3.0 deduped
```

It seems to cause may font loading issue like this one: https://github.com/expo/google-fonts/issues/9

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 4.0.7 environment info:
    System:
      OS: Linux 5.8 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.0.1 - /usr/bin/node
      npm: 6.14.9 - /usr/bin/npm
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.7
    Expo Workflow: managed
```

### Reproducible Demo

I was unfortunately not able to create a reproducible case.

However, if an expo team member want to take a look, I may share my private project access with him to investigate. :+1: 

BTW, why the [`expo-font` documentation](https://docs.expo.io/versions/latest/sdk/font/) tells to install the package as it's already an `expo` dependency? Do we really have to do this? :thinking:

**Comment by soullivaneuh** [comment]
I setup a test scripts that give me interessting clues:

```
#!/usr/bin/env bash
set -e

mkdir -p expo-tests
cd expo-tests

# Classic
rm -rf classic
expo init --template expo-template-blank-typescript@sdk-39 classic
cd classic
expo install @project/apps-components@4.x
npm list | grep expo-font@ # deduped
expo upgrade --non-interactive
npm install @project/apps-components@5.x
npm list | grep expo-font@ # not deduped
cd ..

# Direct
rm -rf direct
expo init --template expo-template-blank-typescript direct
cd direct
npm install @project/apps-components@5.x
npm list | grep expo-font@ # deduped
cd ..
```

As I said on the script comments, the upgrade workflow produce the not deduped package issue, but not if I directly use a new project with v40.

So I made a diff of the `package-lock.json`:

```diff
3235,3245d3234
<       },
<       "dependencies": {
<         "expo-font": {
<           "version": "8.4.0",
<           "resolved": "https://registry.npmjs.org/expo-font/-/expo-font-8.4.0.tgz",
<           "integrity": "sha512-CPGcHLUkPP+yf618fiw2bWTFLojIYCCqWonco/JONcM3tsv6wjkafx4Qw1mMCRoFL7XoiBfHylkKnD0avpzQIQ==",
<           "requires": {
<             "fbjs": "1.0.0",
<             "fontfaceobserver": "^2.1.0"
<           }
<         }
6229,6230c6218,6219
<       "version": "https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz",
<       "integrity": "sha512-/OVa92kVCuG9z5X1q8ivQcIL0ljpgxEcMwP7bNfI86dRGRRPtxFFV3zI1DAoBuT06NIvgJ5GPp953r/0p0oOEQ==",
---
>       "version": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
>       "integrity": "sha512-wYOQJnPj9CHg1db2/xXebxfzJpdwxeQpsqi9HLz5Y6Zv8xY/J7p6O4eeDyenw1FARWbeAPWwzl2y+OYE4CUrPA==",
```

Two things we can observe:

1. On the upgrade script, we have an extra `expo-font` dependency.
2. The SDK `tar.gz` file version is not the same between each instance.

The `@project/apps-components` package is an internal package that requires `expo-font`. v4 is compatible with SDK v39, v5 with v40. Here is its package.json:

```json
{
  "name": "@company/apps-components",
  "version": "0.0.0-dev",
  "description": "apps' common components.",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "react-native": "src/index.ts",
  "files": [
    "dist",
    "src/components",
    "src/utils",
    "src/index.ts"
  ],
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "storybook": "start-storybook -h 0.0.0.0 -p 7007",
    "build": "rm -rf dist && tsc",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "@expo-google-fonts/lato": "^0.1.0",
    "@expo-google-fonts/poppins": "^0.1.0",
    "expo-app-loading": "^1.0.1",
    "expo-font": "~8.4.0"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@kidways/apps-config": "^1.1.1",
    "@kidways/design": "^2.2.0",
    "@storybook/addon-knobs": "^5.3.21",
    "@storybook/addon-links": "^5.3.21",
    "@storybook/addon-ondevice-knobs": "^5.3.23",
    "@storybook/react-native": "^5.3.23",
    "@storybook/react-native-server": "^5.3.23",
    "@types/react": "~16.9.35",
    "@types/react-dom": "~16.9.8",
    "@types/react-native": "~0.63.2",
    "babel-loader": "^8.2.2",
    "expo": "^40.0.0",
    "expo-constants": "~9.3.3",
    "expo-status-bar": "~1.0.3",
    "internal-ip": "^6.2.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.63.4",
    "react-native-web": "~0.13.12",
    "typescript": "~4.0.0"
  },
  "peerDependencies": {
    "react": "*",
    "react-native": "*"
  },
  "publishConfig": {
    "@kidways:registry": "https://gitlab.com/api/v4/projects/xxx/packages/npm/"
  }
}
```

Note: I have the same result without using the typescript variant of the templates.

Hope it helps.

**Comment by soullivaneuh** [comment]
I tried to remove the `expo-font` dependency from my internal library to test.

The expo is yelling because I don't have `expo-font` on my end project which is, I guess, expected.

So I ran `expo install expo-font` but then I have a screen loading freeze issue and my packages are not deduped.

The only way to make it working is to remove the `node_modules/expo/node_modules/expo-font` directory as explained in https://github.com/expo/google-fonts/issues/9#issuecomment-678354163.

I think I'll stick to this hack waiting more official clues.

**Comment by byCedric** [comment]
Hi @soullivaneuh! Thanks for the in-depth research, it helps a lot in the search for the issue. But, unfortunately, I can't seem to repro this issue. I've tried your repro steps a couple of times, each with a different approach.
1. SDK 39 project, install `expo-font`, upgrade to 40
2. SDK 39 project, install `expo-font` and some `@expo-google-fonts/*`, upgrade to 40
3. SDK 40 project, install `expo-font`, downgrade to 39

Each of these all deduped `expo-font`, maybe it's related to an issue in NPM. I'm using NPM 7 to test this, using node 14.

Another possibility is that when you include 2 different dependencies (e.g. `expo` and your `@project/apps-components`), both with a "child"-dependency on `expo-font`, it doesn't dedupe that dependency. I'm not sure if that private package includes `expo-font`, but that could also be the issue.

Any thoughts on that?

**Comment by worstpractice** [comment]
@byCedric I have the same problem in my managed project. All dependencies and expo itself are on the latest (stable) version, as is the Expo Go app on my two respective Android phones.

Manually deduping expo-font by (recursively) deleting `node_modules/expo/node_modules/expo-font` solves the runtime crash for me.

**Comment by byCedric** [comment]
@worstpractice If you are using Yarn, you might be able to "automate" the deduping with [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/). For the long term, we are working on removing the packages nested in `expo`. We had to wait until Metro supported optional dependency imports, and that was merged not so long ago. Once that has landed, you should be able to have more control over what specific version is installed and without having to dedupe them.

**Comment by worstpractice** [comment]
> @worstpractice If you are using Yarn, you might be able to "automate" the deduping with [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/). For the long term, we are working on removing the packages nested in `expo`. We had to wait until Metro supported optional dependency imports, and that was merged not so long ago. Once that has landed, you should be able to have more control over what specific version is installed and without having to dedupe them.

Thank you for the helpful suggestions and general update on the issue!

I haven't seen anything on the Metro docs about optional dependency imports, but that sounds most useful indeed.
