### ISSUE TITLE
Fast Refresh: Which folders are "monitored"?

### ISSUE THREAD

**Issue by aghasemi** [expo/expo#11415]
Hi,
I just noticed that if I move my `App.tsx` file from the root of the expo project to some `src` folder, the fast refresh does not update the project anymore as I change the file. I assume it's not a bug, but the actual way things are programmed.

So, may I ask please, what folders are monitored by fast refresh for changes, and whether that list can be customised?

Many thanks

**Comment by AdamJNavarro** [comment]
Hey @aghasemi, I would recommend reading the Fast Refresh documentation! https://reactnative.dev/docs/fast-refresh

Cheers,
Adam
