### ISSUE TITLE
[docs] app.json / app.config.js typo

### ISSUE THREAD

**Issue by Dayton-IX** [expo/expo#11412]
Hello, I was looking through the documentation on androidStatusBar in [https://docs.expo.io/versions/latest/config/app/#androidstatusbar](url) and found that under the backgroundColor prop there is a small typo in the second paragraph. 

`6 character long hex color string '#RRGGBBAA', for example, '#000000' for black. Or 8 character long hex color string '#RRGGBBAA', for example, '#00000088' for semi-transparent black.`

The first hex string example is supposed to be a 6 character long hex color string `#RRGGBB` but it is currently an 8 character long hex color string `#RRGGBBAA`

Just a small issue that I couldn't figure out how to find in the docs source code!

**Comment by brentvatne** [comment]
thanks for pointing this out! the schema files live in a private repo where we keep our server side / infra code, i've fixed it there, we'll deploy an update next time we sync the schemas

**Comment by Dayton-IX** [comment]
Ok that's what I was starting to think. Thanks for responding so quickly!
