### ISSUE TITLE
after exp detach，react-navigation  initial route  has been constructed twice

### ISSUE THREAD

**Issue by xiaocjin** [expo/expo#1142]
I am running app on ios virtual machine

before detach，it is fine on ios virtual machine

**Comment by quinlanj** [comment]
hi @xiaocjin , could you give us more info to help us root cause your problem? For example, the commands you ran, error messages you see, a basic toy app with which we can reproduce your steps with, versions of expo you are running with, etc,  would really help when we try to reproduce your bug.

**Comment by xiaocjin** [comment]
@quinlanj  same problem https://github.com/react-community/react-navigation/issues/2599
