### ISSUE TITLE
Image picker stuck on iOS 14.2 when editing

### ISSUE THREAD

**Issue by eyalyoli** [expo/expo#11435]
### Summary of Issue 
On iOS 14.2, when opening the image picker to choose a photo from the library, it gets stuck on cropping (after selecting a photo). usually, it occurs if you allow more than one photo to be selected in a sequence.

A workaround is to press the home button and return to the app then the picker works fine.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 4.0.15 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        Android NDK: 21.3.6528147
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.39 
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.15
    Expo Workflow: bare

### Reproducible Demo
```javascript
const pickImage = async () => {
    const { status } = await ImagePicker.requestCameraRollPermissionsAsync();
    if (status !== "granted") {
      alert("Sorry, we need camera roll permissions to make this work!");
    }

    try {
      let result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true, // <-- this is the problem
        aspect: ImageConstants.PROPERTY_IMG_ASPECT,
        //quality: constants.PROPERTY_IMG_QUALITY,
      });
      if (!result.cancelled) {
        addPicture(result.uri);
      }

      console.log(result);
    } catch (E) {
      console.log(E);
    }
  };
```

 
### Steps to Reproduce
Just try to pick a photo a couple of time in a row. One of them will get stuck.

### Expected Behavior vs Actual Behavior
Needs to work sommethly as on lower iOS version (tested on 12.4 vs 14.2 - it doesn't happen on 12.4).

**Comment by eyalyoli** [comment]
I checked the same code with ```allowsEditing: false``` on both version of iOS v12.4/14.2 and on 12.4 you can select the photo without cropping as expected, but on 14.2, ```allowsEditing```doesn't really matter, it allows the user to crop the photo after selection even when ```allowsEditing: false``` ! 

I guess the problem is the conflict on the new iOS version...

**Comment by lukmccall** [comment]
Hi @eyalyoli, could you test your demo using iOS 14.4? 

I've tried to reproduce your issue. Unfortunately, without any result. I used iPhone 8 (with iOS 14.4). 

In iOS 14 Apple introduced a lot of issues connected with the image picker. So that also might be a bug in the iOS SDK.

**Comment by eyalyoli** [comment]
I tested on iOS 14.3 and it seems that it doesn't allow cropping of the photo no matter what you set on `allowsEditing`.
And yes it seems to be bugs related to iOS itself.

I've come to the conclusion that it is better to implement a built-in (non-native) image cropping to get a unified, bug-free experience!

**Comment by junqdu** [comment]
@lukmccall using iOS 14.4, it stuck for me

**Comment by quangnguyen17** [comment]
It's now May 2021, and the issue still persists. The entire app freezes when user taps on the Choose button.

**Comment by Ducksome** [comment]
Same problem for me, the entire image picker freezes when I tap on the choose button on the image picker, Looks like an ios sdk problem. Anyone have any fixes yet?

**Comment by malcolmdsmith** [comment]
I have same problem. I can pick an image then it goes to crop screen but then its stuck. IPad IOS 12.5???
