### ISSUE TITLE
[Expo-In-App-Purchase] IOS Multiple calls of setPurchaseListener's callback

### ISSUE THREAD

**Issue by roboman-sil** [expo/expo#11432]
### Summary of Issue 
On occasion, the callback in setPurchaseListener would do multiple calls. (The calls seem to be previous attempts of purchase).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 4.0.16 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.16
    Expo Workflow: bare

### Reproducible Demo

This is an IAP module that is loaded in on App.js

========================================================================================
import React from 'react';
import PropTypes from 'prop-types';
import { Platform } from 'react-native';
// import RNIap, {
// 	purchaseErrorListener,
// 	purchaseUpdatedListener,
// } from 'react-native-iap';
import * as InAppPurchases from 'expo-in-app-purchases';

import Toastr from '@/components/Toastr';
import LoaderGlobal from '@/components/LoaderGlobal';

const propTypes = {
	sendIOSReceiptToServer: PropTypes.func.isRequired,
	sendReceiptToServer: PropTypes.func.isRequired,
	refreshPageContent: PropTypes.func.isRequired,
	closeModal: PropTypes.func.isRequired,
	children: PropTypes.node,
	appendLog: PropTypes.func.isRequired,
};

const defaultProps = {
	children: null,
};

class IAP extends React.PureComponent {
	purchaseUpdateSubscription = null
        purchaseErrorSubscription = null

	componentDidMount() {
		console.log('MOUNTED LISTENERS');
		// TODO: temporary comment out IAP, need to find a better way to detect native module exist
		console.log(this.purchaseUpdateSubscription);
		this.initPurchaseListener();
		console.log(this.purchaseUpdateSubscription);
		// this.initPurchaseErrorListener();
	}

	componentWillUnmount() {
		this.purchaseUpdateSubscription = null;
	}

	initPurchaseListener = () => {
		if (InAppPurchases.setPurchaseListener) {
			console.log('initPurchaseListener');
			this.purchaseUpdateSubscription = InAppPurchases.setPurchaseListener((
				{ responseCode, results, errorCode },
			) => {
				const { appendLog } = this.props;
				console.log('setPurchaseListener');
				console.log({ responseCode, results, errorCode });
				appendLog('setPurchaseListener');
				// appendLog({ responseCode, results, errorCode });
				// Purchase was successful
				if (responseCode === InAppPurchases.IAPResponseCode.OK) {
					let selectedPurchase = null;
					results.forEach((purchase) => {
						if (!purchase.acknowledged) {
							selectedPurchase = purchase;
						}
					});

					if (selectedPurchase) {
						console.log(`Successfully purchased ${selectedPurchase.productId}`);
						console.log(selectedPurchase);
						this.sendReceiptToServerFunc(selectedPurchase).then(() => {
							console.log('CLOSE EVERYTHING');
							this.closePaymentProcessing({ closeModal: true });
						});
					} else {
						Toastr.warning({ text: 'There is an error registering this subscription' });
					}
				} else {
				// Else find out what went wrong
					if (responseCode === InAppPurchases.IAPResponseCode.USER_CANCELED) {
						console.log('User canceled the transaction');
						Toastr.warning({ text: 'User canceled the transaction' });
					} else if (responseCode === InAppPurchases.IAPResponseCode.DEFERRED) {
						console.log('User does not have permissions to buy but requested parental approval (iOS only)');
						Toastr.warning({ text: 'User does not have permissions to buy but requested parental approval (iOS only)' });
					} else if (errorCode) {
						console.warn(`Something went wrong with the purchase. Received errorCode: ${InAppPurchases.IAPErrorCode[errorCode]}`);
						Toastr.warning({ text: `Something went wrong with the purchase. Received errorCode: ${InAppPurchases.IAPErrorCode[errorCode]}` });
					}

					this.closePaymentProcessing();
				}
			});
		}
	}

	closePaymentProcessing = ({ closeModal = false }) => {
		console.log('Close Payment Processing');
		console.log(closeModal);
		const { refreshPageContent, closeModal: shutModalDown } = this.props;
		console.log(shutModalDown);
		if (closeModal) {
			shutModalDown();
		}

		LoaderGlobal.hide();
		refreshPageContent();
	}

	receiptToServer = (purchase) => {
		const { productId } = purchase;
		const { sendReceiptToServer, sendIOSReceiptToServer } = this.props;

		if (Platform.OS === 'ios') {
			return sendIOSReceiptToServer(purchase);
		}

		return sendReceiptToServer(JSON.stringify(purchase), productId, '10');
	}

	handleConnectionError = async () => {
		const { appendLog } = this.props;
		console.log('In Handle Connection Error');
		appendLog('In Handle Connection Error');
		const responseCode = await InAppPurchases.getBillingResponseCodeAsync();
		if (responseCode !== InAppPurchases.IAPResponseCode.OK) {
			console.log('Failed with response code:');
			console.log(responseCode);
			appendLog('Failed with response code:');
			appendLog(responseCode);
			await InAppPurchases.disconnectAsync();
			await InAppPurchases.connectAsync();
		}
	}

	repurchase = async (purchase) => {
		const { appendLog } = this.props;
		console.log('GET PURCHASE HISTORY ASYNC');
		appendLog('GET PURCHASE HISTORY ASYNC');
		const { responseCode, results } = await InAppPurchases.getPurchaseHistoryAsync(true);
		console.log(responseCode);
		console.log(results);
		appendLog(responseCode);
		// appendLog(results);

		const listOfSameItems = [];
		results.forEach((purchasedData) => {
			if (purchasedData.productId === purchase.productId) {
				listOfSameItems.push(purchasedData);
			}
		});

		const latestPurchase = listOfSameItems.reduce((accumulator, currentValue) => {
			if (
				Math.max(accumulator.purchaseTime, currentValue.purchaseTime) === accumulator.purchaseTime
			) {
				return accumulator;
			}
			return currentValue;
		}, { purchaseTime: 0 });

		console.log('LARGEST');
		console.log(latestPurchase);
		appendLog('LARGEST');
		// appendLog(latestPurchase);

		if (responseCode === InAppPurchases.IAPResponseCode.OK) {
			const { type } = await this.receiptToServer(latestPurchase);
			console.log('TYPE');
			console.log(type);
			appendLog('TYPE');
			appendLog(type);

			if (type === 'SEND_RECEIPT_SUCCESS') {
				await InAppPurchases.finishTransactionAsync(purchase, false);
			}
		}

		this.closePaymentProcessing();
	}

	sendReceiptToServerFunc = async (purchase) => {
		const { appendLog } = this.props;
		appendLog('=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+');
		appendLog('sendReceiptToServer');
		// appendLog(purchase);

		try {
			const { type } = await this.receiptToServer(purchase);
			console.log('TYPE');
			console.log(type);
			appendLog('TYPE');
			appendLog(type);

			if (type === 'SEND_RECEIPT_SUCCESS') {
				const result = await InAppPurchases.finishTransactionAsync(purchase, false);
				console.log('DONE TRANSACTION');
				console.log(result);
				appendLog('result');
				appendLog(result);
			} else {
				await this.repurchase(purchase);
			}

			console.log('sendReceiptToServerFunc');
		} catch (err) {
			appendLog('Error');
			appendLog(err);
			console.log('ERROR IN sendReceiptToServerFunc');
			console.log(err);
			Toastr.show({ text: err.message || 'Subscription error' });
			await this.handleConnectionError();
		}
	};

	render() {
		const { children } = this.props;
		return children;
	}
}

IAP.propTypes = propTypes;
IAP.defaultProps = defaultProps;

export default IAP;

====================================================================== 
Below is the view for the Subscription Modal, which contains connectAsync, purchaseItemAsync and disconnectAsync
import React from 'react';
import PropTypes from 'prop-types';
import { Platform } from 'react-native';
import i18n from 'i18next';
import * as InAppPurchases from 'expo-in-app-purchases';
import numeral from 'numeral';
import _ from 'lodash';

import RedeemCode from '@/screens/RedeemCode';

import Toastr from '@/components/Toastr';
import LoaderGlobal from '@/components/LoaderGlobal';
import SubscriptionDetails from './SubscriptionDetails';
import SubscriptionList from './SubscriptionList';

const propTypes = {
	loading: PropTypes.bool,
	error: PropTypes.string,
	subscriptionPackages: PropTypes.arrayOf(PropTypes.shape()),
	closeModal: PropTypes.func.isRequired,
	openModal: PropTypes.func.isRequired,
	getSubscriptionPackages: PropTypes.func.isRequired,
	subscribeToPackage: PropTypes.func.isRequired,
	subscriptionSkus: PropTypes.arrayOf(PropTypes.string).isRequired,
	getSubscriptionSKUs: PropTypes.func.isRequired,
	refreshPageContent: PropTypes.func.isRequired,
	appendLog: PropTypes.func.isRequired,
};

const defaultProps = {
	loading: true,
	error: null,
	subscriptionPackages: [{}],
};

class SubscriptionModal extends React.PureComponent {
	state = {
		products: [],
		selectedSubscription: null,
	};

	componentDidMount = async () => {
		const { getSubscriptionPackages, getSubscriptionSKUs, appendLog } = this.props;
		console.log('CONNECT');
		await InAppPurchases.connectAsync();
		await getSubscriptionPackages();
		let products = null;

		await getSubscriptionSKUs();
		products = await this.retrieveSubscriptionDetailsFromStore();
		appendLog('Products in store');
		appendLog(products);

		this.setState({ products });
	};

	componentWillUnmount = () => {
		console.log('DISCONNECT');
		InAppPurchases.disconnectAsync();
	}

	retrieveSubscriptionDetailsFromStore = async () => {
		const { subscriptionSkus, appendLog } = this.props;

		const itemSkus = Platform.select({
			ios: subscriptionSkus,
			android: subscriptionSkus,
		});
		appendLog('===================================');
		appendLog('itemSkus');
		appendLog(itemSkus);
		console.log('itemSkus');
		console.log(itemSkus);
		try {
			console.log('SKU');
			console.log(itemSkus);
			appendLog('storeProducts');
			const { results: storeProducts } = await InAppPurchases.getProductsAsync(itemSkus);
			console.log(storeProducts);
			appendLog(storeProducts);
			return this.mergeSubscriptionPackagesWithStore(storeProducts);
		} catch (err) {
			appendLog('retrieveSubscriptionDetailsFromStore Error');
			appendLog(err);
			console.log('Subscription From Store');
			console.log(err);
			Toastr.show({ text: err.message || i18n.t('subscription:storeRetrieveError') });
			appendLog('===================================');
			appendLog('===================================');
			appendLog('===================================');
			return this.convertFeeToNumeral();
		}
	};

	mergeSubscriptionPackagesWithStore = (storeProducts) => {
		const { subscriptionPackages, appendLog } = this.props;
		appendLog('===================================');
		appendLog('===================================');
		appendLog('===================================');
		appendLog('mergeSubscriptionPackagesWithStore');
		appendLog('subscriptionPackages');
		appendLog(subscriptionPackages);

		const keyedStoreProducts = _.keyBy(storeProducts, 'productId');
		subscriptionPackages.forEach((sub, id) => {
			subscriptionPackages[id].subscriptionFee = sub.subscriptionFee.filter(
				(feeType) => {
					const newFeeType = feeType;
					if (!_.isEmpty(keyedStoreProducts[newFeeType.storeProductId])) {
						newFeeType.fee = keyedStoreProducts[newFeeType.storeProductId].price;
						return true;
					}
					return false;
				},
			);
		});
		return subscriptionPackages.filter((it) => it.subscriptionFee.length > 0);
	};

	convertFeeToNumeral = () => {
		const { subscriptionPackages, appendLog } = this.props;
		appendLog('===================================');
		appendLog('===================================');
		appendLog('===================================');
		appendLog('convertFeeToNumeral');
		appendLog('subscriptionPackages');
		appendLog(subscriptionPackages);
		subscriptionPackages.forEach((sub) => {
			sub.subscriptionFee.forEach((feeType) => {
				const newFeeType = feeType;
				newFeeType.fee = newFeeType.fee
					&& `$${numeral(newFeeType.fee.toString()).format('0.00')}`;
			});
		});
		return subscriptionPackages;
	};

	gotoCode = () => {
		const { openModal } = this.props;
		openModal(<RedeemCode />);
	};

	goToSubscriptionDetails = (item) => {
		this.setState({ selectedSubscription: item });
	};

	goBack = () => {
		this.setState({ selectedSubscription: null });
	};

	subscribe = async (storeProductId) => {
		LoaderGlobal.show({ message: i18n.t('subscription:processingPayment') });
		// if (this.hasIAP) {
		await this.buySubscriptionFromStore(storeProductId);
		// } else {
		// 	await this.devModeSubscribeToPackage(storeProductId);
		// }
	};

	buySubscriptionFromStore = async (storeProductId) => {
		if (!InAppPurchases.purchaseItemAsync) {
			Toastr.show({ text: i18n.t('subscription:iapError') });
			return;
		}
		try {
			// eslint-disable-next-line max-len
			// To replace an existing subscription on Android await purchaseItemAsync('gold_yearly', 'gold_monthly');
			InAppPurchases.purchaseItemAsync(storeProductId);
		} catch (err) {
			Toastr.show({ text: err.message });
		}
	};

	devModeSubscribeToPackage = async (storeProductId) => {
		Toastr.warning({ text: i18n.t('subscription:devMode') });
		const { subscribeToPackage, refreshPageContent, closeModal } = this.props;

		try {
			const res = await subscribeToPackage({ storeProductId });
			closeModal();
			if (res.type === 'SUBSCRIBE_TO_PACKAGE_SUCCESS') {
				await refreshPageContent();
			}
		} catch (err) {
			Toastr.show({ text: err.message || 'Subscription error' });
		} finally {
			LoaderGlobal.hide();
		}
	}

	render() {
		const { closeModal, error } = this.props;
		const { products, selectedSubscription } = this.state;

		if (!selectedSubscription) {
			return (
				<SubscriptionList
					closeModal={closeModal}
					loading={false}
					error={error}
					products={products}
					gotoCode={this.gotoCode}
					goToSubscriptionDetails={this.goToSubscriptionDetails}
				/>
			);
		}
		return (
			<SubscriptionDetails
				name={selectedSubscription.name}
				description={selectedSubscription.description}
				subscriptionFee={selectedSubscription.subscriptionFee}
				goBack={this.goBack}
				closeModal={closeModal}
				subscribe={this.subscribe}
			/>
		);
	}
}

SubscriptionModal.propTypes = propTypes;
SubscriptionModal.defaultProps = defaultProps;

export default SubscriptionModal;

### Steps to Reproduce
The multiple api calls would occur when connectAsync runs. It occurs at random most of the time. I mostly experience that after a failed purchase, it would run the multiple calls. There are occasions when, without a failed purchase, it runs upon the first initialisation of the connectAsync in a whole new app.

**Comment by cipriancaba** [comment]
This problem still randomly pops for me as well. Happened much more often a while back, thought it was solved, but started happening again in the latest version. I am dealing with subscriptions so not sure if this has anything to do with that

**Comment by Clonescody** [comment]
Hi there, bumping this issue as I keep facing the problem as well. 

Infos : 
- Issue happens locally and in TestFlight
- Expo v41.0.0
- React Native v0.63.4
- Expo IAP v10.1.1
- 4 subscriptions available in AppStoreConnect

`connectAsync()` works as expected and fetches my subscriptions. 

When I'm clicking my payment button, the payment popin arrives, and sometimes displays 4 times in a row with each of my subscriptions ( 4 subscriptions registered in AppStoreConnect ) in a random order.

If I pay the displayed subscription ( even if it's not the one provided to `purchaseItemAsync(id)` ), it's validating a payment, however if I cancel it, I can cancel all 4 in a row without any event triggered ( user_cancel ).

This behavior happens both locally and with the TestFlight version, but isn't consistent at all. Sometimes It'll work as expected first try, sometimes I have to logout and log back in with my Sandbox account or uninstall/reinstall the app for it to work as intended. 

The IAP module isn't triggering any exception as far as I can tell.

Can this just be related to the sandbox env ? Or an Apple connection ? 

I am actually worried as I can't test those payments with consistency and I have no idea if it would work 100% of the time in prod. 

Thanks so much for any reply 🙏 available for more informations if needed

**Comment by dernster** [comment]
@Clonescody I'm experiencing the same behavior, were you able to solve it somehow?

**Comment by dorapax-lab** [comment]
Issue happens locally android
Expo: ~42.0.1
React Native: ~0.63.4
Expo IAP: ^11.0.1

When I do a test subscription first time processNewPurchase(purchase) only calls once (correct behaviour). But after 5 minutes (since it is a test subscription) subscription got cancelled and again try to do the subscription processNewPurchase(purchase) calls twice and so on, (next time it is thrice).

```
InAppPurchases.setPurchaseListener(
      ({ responseCode, results, errorCode }) => {
        // Purchase was successful
        if (responseCode === InAppPurchases.IAPResponseCode.OK) {
          results.forEach(async (purchase) => {
            if (!purchase.acknowledged) {
              await processNewPurchase(purchase)

              // finish the transaction on platform's end
              InAppPurchases.finishTransactionAsync(purchase, true)
            }
          })

          // handle particular error codes
        } else if (
          responseCode === InAppPurchases.IAPResponseCode.USER_CANCELED
        ) {
          console.log('User canceled the transaction')
        } else if (responseCode === InAppPurchases.IAPResponseCode.DEFERRED) {
          console.log(
            'User does not have permissions to buy but requested parental approval (iOS only)'
          )
        } else {
          console.warn(
            `Something went wrong with the purchase. Received errorCode ${errorCode}`
          )
        }

        setProcessing(false)
      }
    )
```

since setPurchaseListener should be in global state , I use that in App.js as <IAPManagerWrapped>

```
export default function App() {
  return (
    <ErrorBoundary onError={errorHandler}>
      <Auth>
        <IAPManagerWrapped>
          <Provider store={store}>
            <NavigationContainer ref={navigationRef}>
              <StatusBar barStyle='dark-content' />
              <Main navigationRef={navigationRef} />
            </NavigationContainer>
          </Provider>
        </IAPManagerWrapped>
      </Auth>
    </ErrorBoundary>
  )
}
```

In my purchase screen (PurchaseScreen.js), I am using useIAP() hook to get the product details.
```
  const { getProducts } = useIap()

  const [subscription, setSubscription] = useState([])

  useEffect(() => {
    getProducts().then((results) => {
      console.log(results)
      if (results && results.length > 0) {
        const sub = results.find((o) => o.productId === subscribeId)
        if (sub) {
          setSubscription(sub)
        }
      }
    })
    return () => {}
  }, [])
```
