### ISSUE TITLE
Upgrade react-native-maps to 0.19.x

### ISSUE THREAD

**Issue by khomyakov42** [expo/expo#1143]
When you plan to upgrade the react-native-maps to version 0.19.0?
https://github.com/react-community/react-native-maps

**Comment by ide** [comment]
We don't have a planned schedule for upgrades -- in the past, we've upgraded react-native-maps and other similar dependencies when there's been a breaking change to React Native and upgrading the dependency is the smoothest path forward.

**Comment by terribleben** [comment]
@khomyakov42 is there a particular feature you need, or issue which is blocking you, which would be fixed if we updated?

**Comment by nurdeen** [comment]
@terribleben there is a bug that was fixed for maps in android 15 days ago. I need this fix.

https://github.com/react-community/react-native-maps/issues/1153
https://github.com/react-community/react-native-maps/commit/6220583a19cf62f942b4166927aafeeeb1003a81

**Comment by khomyakov42** [comment]
Yes, https://github.com/react-community/react-native-maps/issues/1819 fixed in 0.18

**Comment by truca** [comment]
I need this method: animateToRegion

**Comment by truca** [comment]
is there a way to fork this repo and get expo working with react-native-maps v0.19.x?

**Comment by truca** [comment]
link to react-native-maps that expo is currently using: 
https://github.com/react-community/react-native-maps/tree/v0.17.1
