### ISSUE TITLE
Error: The keyPrefix reduxPersist: is already in use. Multiple clients cannot share the same keyPrefix. Provide a different keyPrefix in the offlineConfig object.

### ISSUE THREAD

**Issue by savita-malaghan** [expo/expo#11431]
When I am upgrading expo from sdk-33 to sdk-40 version of expo. I am getting this issue, I have aws_appsync dependency in my react-native version 59.10.0.
The problem is occurring when I create new AWSAppSyncClient, I have set "disableOffline" property to true. Still I am getting this issue.

Is this any issue with upgrade expo or react-native dependencies?

**_Please provide guidelines Upgrade expo sdk-33 to SDK-40 in expo with their dependency also._**

**Comment by byCedric** [comment]
Hi @savita-malaghan. It looks like your [code might be initializing multiple instances of `AWSAppSyncClient`](https://github.com/aws-amplify/amplify-js/issues/3372#issuecomment-497792456). Without any context or repro, I can't be certain about that or help you further.

Upgrading from sdk-33 all the way to sdk-40 means you are:
- upgrading 7 major SDK versions
- upgrading (at least) 4 versions of React Native

Doing this all at once will definitely cause some breaking change. I would recommend doing them 1 by 1 and reading the [SDK changelog](https://docs.expo.io/workflow/upgrading-expo-sdk-walkthrough/#sdk-33) and validating if the update was successful.

Hope this helps!

**Comment by majirosstefan** [comment]
Only upgrading React Native / Expo SDKs does not work.
