### ISSUE TITLE
Font doesn't work after expo eject

### ISSUE THREAD

**Issue by nartydev** [expo/expo#11443]
### Summary of Issue 
Font doesn't work after expo eject

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I target iOS 

  Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 19, 23, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: bare
 
### Steps to Reproduce
expo init
expo eject
npm install react-native-unimodules
npx pod-install

### Expected Behavior vs Actual Behavior

Font doesn't work

My file for load font : 
```
import * as Font from "expo-font";
import * as React from "react";

export default function useCachedResources() {
  const [isLoadingComplete, setLoadingComplete] = React.useState(false);

  // Load any resources or data that we need prior to rendering the app
  React.useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {
        //SplashScreen.preventAutoHideAsync();
        // Load fonts
        await Font.loadAsync({
          "Poppins Light": require("../assets/fonts/Poppins-Light.ttf"),
          "Poppins Regular": require("../assets/fonts/Poppins-Regular.ttf"),
          "Poppins Bold": require("../assets/fonts/Poppins-Bold.ttf"),
          "Poppins ExtraBold": require("../assets/fonts/Poppins-ExtraBold.ttf"),
        });
      } catch (e) {
        // We might want to provide this error information to an error reporting service
        console.warn(e);
      } finally {
        setLoadingComplete(true);
        //SplashScreen.hideAsync();
      }
    }
    loadResourcesAndDataAsync();
  }, []);

  return isLoadingComplete;
}
```

**Comment by brentvatne** [comment]
it does work. you can create a new tabs project and eject to verify.

if you are having an issue with this it is related to some other config in your project. please provide more information to help us reproduce, the code you provided is insufficient

**Comment by brentvatne** [comment]
<img width="506" alt="Screen Shot 2020-12-30 at 4 33 07 PM" src="https://user-images.githubusercontent.com/90494/103388230-b40d2700-4abc-11eb-85d5-e7184e882f1c.png">
<img width="404" alt="Screen Shot 2020-12-30 at 4 41 53 PM" src="https://user-images.githubusercontent.com/90494/103388455-f84cf700-4abd-11eb-95a0-bde11463db5d.png">

steps to repro this working:

```
expo init tabsy --template tabs
cd tabsy
expo eject
yarn ios
yarn android
```

closing this until a reproducible example is provided
