### ISSUE TITLE
UnhandledPromiseRejectionWarning when i try run "expo start" 

### ISSUE THREAD

**Issue by limk10** [expo/expo#11444]
I'm trying to run expo on the iOS simulator, but the following message comes back to me

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections = strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

![image](https://user-images.githubusercontent.com/20530933/102930365-a62f2480-4472-11eb-904f-f175dcee84ff.png)

**Comment by brentvatne** [comment]
hi there!

maybe there is a problem with your xcode installation.

try running `xcrun simctl list` in your terminal, does that work?

if so, pick one of those device ids and try `xcrun simctl boot <deviceid>` eg: `xcrun simctl boot 9F6E2A1A-F2EB-45E2-840C-F9E5BC2EAEB3`

does that start a simulator for you?

**Comment by limk10** [comment]
Hi @brentvatne, yep he starts the service, and again "expo start -i" but the error persists.

"UnhandledPromiseRejectionWarning: Error: xcrun exited with non-zero code: 4"

![image](https://user-images.githubusercontent.com/20530933/102933207-3754ca00-4478-11eb-9920-d2812845a37d.png)

**Comment by brentvatne** [comment]
does that also happen from the same terminal? i noticed in your screenshot that you are running expo-cli from vscode terminal, and i don't know if there might be some issue related to that environment
