### ISSUE TITLE
Using expo local authentication not receive enrolled biometrics and callbacks while selecting authentiation type at runtime to update strings dynamically. 

### ISSUE THREAD

**Issue by pankaj-bhardwaj** [expo/expo#11451]
## 🐛 Bug Report

In Expo local authentication for Android, we do not receive enrolled biometrics(fingerprint, face detection, or iris). The method supportedAuthenticationTypesAsync() returns only hardware supported on device(not enrolled) and the isEnrolledAsync() method returns a Boolean value where true will be returned in case of any biometric enrolled.

   isEnrolledAsync () will return true if the user has enrolled with either fingerprint or face Id and there is a need to receive the exact biometric type is active/enrolled on the device.
  
As of now in Samsung devices, the biometric prompt will be displayed with face and fingerprint both(in case the user enrolled both). We need a call-back method where we will get which biometric is selected by user runtime on popup to update the description accordingly. (Refer to attached screenshot – right now we do not know which authentication method is selected so even user selects face, the message is not updated).

![Screenshot 2020-12-23 at 3 01 12 PM](https://user-images.githubusercontent.com/52382146/102984234-52384480-4533-11eb-8a02-52d93caac7fb.jpeg)
<img width="288" alt="Screenshot 2020-12-23 at 2 03 15 PM" src="https://user-images.githubusercontent.com/52382146/102984279-5fedca00-4533-11eb-84d5-c9c9571afa3b.png">

**Comment by byCedric** [comment]
Please [see this discussion/PR](https://github.com/expo/expo/pull/11173), closing in favor of #10861
