### ISSUE TITLE
'expo-auth-session/providers/facebook' is not defined in dependencies

### ISSUE THREAD

**Issue by victorbruce** [expo/expo#11454]
## 🐛 Bug Report
'expo-auth-session/providers/facebook' is not defined in dependencies

### Summary of Issue 
I tried the Facebook OAuth sign-in example in expo snak. I had an error that expo-auth-session requires a peer-dependencies 'expo-application',  'expo-linking'. and 'expo-contants'

### Reproducible Demo
Here is a link to the snack example: https://snack.expo.io/@victorbruce/0b2521

 
### Steps to Reproduce
Run this link in the browser to open my snack on expo: https://snack.expo.io/@victorbruce/0b2521

### Expected Behavior vs Actual Behavior
The actual behavior is that expo is complaining about some peer dependencies. What I expect is that I'm able to scan the QR code and test the example out

**Comment by brentvatne** [comment]
Snack doesn't work well with internal imports like `package-name/internal/import`.

if you use this in a local project it will work as expected

**Comment by brentvatne** [comment]
cc @EvanBacon maybe we should remove snack links for authsession examples that aren't working

**Comment by howardwu1** [comment]
Wanted to confirm that my previous examples don't work on snack after expo-linking and others were deprecated because of these unmet peer dependencies. And with the snack examples, if you re-add the dependencies things end up working but for sdk 42 or lower
