### ISSUE TITLE
Imagepicker.launchCameraAsync() crashing for some android users. 

### ISSUE THREAD

**Issue by Lastofthefirst** [expo/expo#11465]
## 🐛 Bug Report
Imagepicker.launchCameraAsync crashes the application without any error logs.

### Summary of Issue 
Some users are reporting "the camera not working", which when I reproduced on Android 10 with a Nexus S emulator was the whole app crashing whenever Imagepicker.launchCameraAsync was called. The camera is never visible, and I have not been able to get any javascript logs from the crash.

**Devices reporting the issue:**
Device: Google Pixel 3a, Android version (SDK): Android 11 (SDK 30)
Device: Google Pixel 5, Android version (SDK): Android 11 (SDK 30)
Device: Samsung Galaxy S10+, Android version (SDK): Android 10 (SDK 29)
Device: Samsung Galaxy Note10+, Android version (SDK): Android 10 (SDK 29)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed

### Reproducible Demo
```js
   let result = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
        aspect: [4, 3],
      quality: 1,
      base64: true,
    });
```

 
### Steps to Reproduce
Call the above function from an Android 10 Nexus S emulator.

### Expected Behavior vs Actual Behavior

The camera should open to take a picture. Instead the application crashes.

**Comment by AlvaroKore** [comment]
is there any solution yet?

**Comment by conquext** [comment]
@lukmccall Thanks for all you do. 
I tried your fix to this issue but it did not work for me. The app still crashes, regardless of whether `allowEditing` is true or false.

**Comment by lukmccall** [comment]
@conquext are you using the bare flow? This changes haven't been published for managed yet.

If you are using the bare workflow, can you provide logs from your device? It's very hard to fix such issues without logs.

**Comment by conquext** [comment]
@lukmccall Thanks for the quick response. Sadly there are no logs on the console when the crash happens. I ejected from a managed workflow.

What I can say for certain is that the crash happens immediately launchCameraAsync is called, right after taking the image.

**Comment by lukmccall** [comment]
By the console, you mean the bundler one? If yes, could you check the native logs? You can access them using Android studio or by the command line using adb. For more information about the command line comand, check out https://developer.android.com/studio/command-line/logcat

**Comment by conquext** [comment]
@lukmccall Thanks for the headsup. I pasted the logs in here https://gist.github.com/conquext/45c590c7d658f3f59ec3fd6a857abed3. 
I hope you find something useful.

**Comment by lukmccall** [comment]
Thanks, it looks strange, but I didn't find anythig that points to the solution yet. I have one more question. Do you use `expo-camera`?

**Comment by conquext** [comment]
I am using this [expo-image-picker](https://www.npmjs.com/package/expo-image-picker) library

**Comment by lukmccall** [comment]
Ye, I know, but I just wonder if a similar behavior will be visible in `expo-camera`. This bug seems to be connected with the system camera code.

**Comment by conquext** [comment]
@lukmccall got `autoFocus failed` when I plug in the expo-camera

![image](https://user-images.githubusercontent.com/28393660/112748504-e511d080-8fb3-11eb-9001-b377728643f6.png)

**Comment by lukmccall** [comment]
Can you diable it? I think there is a property that control the auto focus. Moreover please set the useCamera2Api prop to true.

**Comment by conquext** [comment]
@lukmccall Please see the error with useCamera2api and autoFocus disabled,
![image](https://user-images.githubusercontent.com/28393660/112751652-f87a6700-8fc6-11eb-96d8-23d3618e579f.png)

the code snippet below
![image](https://user-images.githubusercontent.com/28393660/112751781-9f5f0300-8fc7-11eb-8537-1cff77910182.png)

**Comment by lukmccall** [comment]
Ohh, that is weird. I'll dig into this issue later.
