### ISSUE TITLE
Release SDK Expo 40 Splash Screen Image Not Displaying

### ISSUE THREAD

**Issue by ajohnson1031** [expo/expo#11460]
### Summary of Issue 
After upgrading to Expo 40, the splash screen image seems to have disappeared. Apparently, the splash screen is being displayed, because the background color is shown, however the image is not. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.4.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.0.15 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.21.13

### Reproducible Demo
Snack Link: https://snack.expo.io/@a.j1031/trembling-macaroni-and-cheese

Previously, I tried setting the splash image to the snack-icon file, but to clear confusion, I set it to an image I found on the web. In the snack, neither the background color nor the image are shown. Neither does it appear that the `preventAutoHideAsync` method is firing. To be clear, this is not the issue I'm seeing during development, only that the splash image is not displayed. These other side effects seem peculiar to the snack.expo.io platform.

 
### Steps to Reproduce
Nothing seems to prompt this behaviour. It simply began once I upgraded from SDK 39 to SDK 40. For further reference, I'm listing my dependencies and dev dependencies in order to provide a referent for future users.

"dependencies": {
    "@expo-google-fonts/dosis": "^0.1.0",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native": "^5.7.2",
    "@react-navigation/stack": "^5.8.0",
    "apsl-react-native-button": "^3.1.1",
    "axios": "^0.21.0",
    "expo": "^40.0.0",
    "expo-app-loading": "^1.0.1",
    "expo-barcode-scanner": "~9.1.0",
    "expo-font": "~8.4.0",
    "expo-splash-screen": "~0.8.1",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz",
    "react-native-confirmation-code-field": "^6.5.1",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-intl-phone-input": "^1.2.26",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-tiny-toast": "^1.0.7",
    "react-native-web": "~0.13.12",
    "validate.js": "^0.13.1"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-preset-expo": "8.3.0",
    "react-devtools": "^4.10.1"
  },

### Expected Behavior vs Actual Behavior

It is expected that the splash screen image would be displayed during the app loading sequence. What is actually happening, however, is that the image is not shown, though the background color is.

**Comment by ajohnson1031** [comment]
Closing this issue as it appears to have been resolved by upgrading to the latest `expo-cli` version. Previously, I had version **3.21.13**. Updating to version **4.0.16** appears to have done the trick and my splash screen and image are displaying nicely now.

**Comment by altssolution** [comment]
same issue !!

**Comment by neiker** [comment]
Same issue. I see the backgroundColor but not the image.
I'm using `expo-cli@4.0.17`  with `expo@40`

**Comment by minaibrahimsaid** [comment]
same issue here

**Comment by yip-theodore** [comment]
Using `adb logcat` with my device on (expo bare workflow) I had:
```
W OpenGLRenderer: Bitmap too large to be uploaded into a texture (2484x4672, max=4096x4096)
```
So I tried resizing down my `splashscreen_image.png`... and it worked.
