### ISSUE TITLE
[expo-gl] java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libexpo-gl.so caused by: dlopen failed: library "libndk_translation_proxy_libGLESv3.so" not found result: 0

### ISSUE THREAD

**Issue by zholmes1** [expo/expo#11469]
### Summary of Issue
After testing my release APK on my local device and emulator, I uploaded my AAB to the Play Store for internal testing. I'm receiving crash reports through Crashlytics. It appears they are trying over and over again to open the app and are receiving this error.

### Environment
  Expo CLI 3.28.5 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.19.0 - /usr/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
    Expo Workflow: bare

### Reproducible Demo
Unfortunately I am unable to reproduce this even on my own devices.

Here is the full error they are receiving.

```
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libexpo-gl.so caused by: dlopen failed: library "libndk_translation_proxy_libGLESv3.so" not found result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
       at expo.modules.gl.cpp.EXGL.<clinit>(EXGL.java:8)
       at expo.modules.gl.GLContext$1.run(GLContext.java:93)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:818)
```

One thing to note is that they are testing on a 5 year old device (Nexus 5X), whereas my primary development device is a brand new Samsung S20+. Could that be causing issues?

**Comment by zholmes1** [comment]
Further research:

```
Caution: Support of the OpenGL ES 3.0 API on a device 
requires an implementation of this graphics pipeline provided 
by the device manufacturer. A device running Android 4.3 or 
lower may not support the OpenGL ES 3.0 API. For information 
on checking what version of OpenGL ES is supported at run time, 
see Checking OpenGL ES version.
```

Found at: https://developer.android.com/guide/topics/graphics/opengl

--------------------

**android:glEsVersion**
```
The OpenGL ES version required by the application. The higher 16 bits represent the major number and the lower 16 bits represent the minor number. For example, to specify OpenGL ES version 2.0, you would set the value as "0x00020000", or to specify OpenGL ES 3.2, you would set the value as "0x00030002".
```

Found at: https://developer.android.com/guide/topics/manifest/uses-feature-element

I will be adding `<uses-feature android:glEsVersion="0x00030000" android:required="true"/>` to my `<manifest>` tag to see if it stops Google from attempting to install the app on devices that don't have OpenGL ES 3.

**Comment by zholmes1** [comment]
Adding `<uses-feature android:glEsVersion="0x00030000" android:required="true"/>` to `<manifest>` stopped Google Play from attempting to install the app on devices that don't support OpenGL ES 3.

Two outstanding issues/questions:

1. Is `expo-gl` supposed to crash out on devices that do not support v3?
2. Anyone who attempts to install the APK on a device that does not have v3 will have an unusable app. Obviously exceedingly rare.

**Comment by Vluf** [comment]
Getting the same error. I'm not fond of adding it to the manifest, as over 10% of all devices still run OpenGL ES < 3

Additionally, it seems like `expo-gl` is providing a fallback if 3 is not available: https://github.com/expo/expo/blob/master/packages/expo-gl/android/src/main/java/expo/modules/gl/GLContext.java#L395
That doesn't seem to work though.

**Comment by paulorrfilho** [comment]
I don't use expo with my apps but I am facing the same issue, also Nexus 5X. The same device is reporting the crash multiple times right after I release a new version, like 30 crashes within a few minutes after the release. I also noted that the device is rooted, so my best guess is that this is a bot device trying to download the apk, hack it, and make it available for download on the hundreds of apk websites.

**Comment by Vluf** [comment]
Any update on this? Still an issue ..
