### ISSUE TITLE
Renaming an App in App Store does not propagate to URL links

### ISSUE THREAD

**Issue by marchingband** [expo/expo#11468]
I have an App that's been in the App Stores for about a year.
I recently decided to change the name of the App, and that worked.
Unfortunately when I share a link to the app, the URL, and the display name in the preview of that URL retains the old name.
I don't see anything in the docs to address this.

The new name of the App is "Support a Troop", but as you can see in this screen shot, the URLs have the old name, and the preview shows the old name (this is the URL pasted into FB Messenger, just for example)

It looks like there are 2 things at play.
1) I need to change the bundleIdentifier field in app.json, but I assume this will mean App Store Connect will get very confused. I couldn't find anything in the docs (or anywhere online) which addresses this ...
2) Perhaps there is some kind of a cache at work with the preview name? The icon updated, but the name remains the same.

![Screen Shot 2020-12-26 at 1 35 51 PM](https://user-images.githubusercontent.com/34205564/103159521-59ec2900-477f-11eb-9bdb-be57cdfdcfb3.png)

**Comment by brentvatne** [comment]
this is a question to raise with apple support. or try rescraping with fb sharing debugger https://developers.facebook.com/tools/debug/

unrelated to expo itself
