### ISSUE TITLE
Expo 24.0.2 - sdk directory hardcoded

### ISSUE THREAD

**Issue by ptariche** [expo/expo#1146]
Steps to reproduce

Detach APP

Build Assemble:

* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory '/Users/jesseruder/Library/Android/sdk' does not exist.

**Comment by anp** [comment]
Sorry about that! What are the contents of the `local.properties` file? If you delete it, does the build work again?

**Comment by ptariche** [comment]
There doesn't seem to be one.

**Comment by ptariche** [comment]
Android Studio inserts one once being fired up.

**Comment by jesseruder** [comment]
Can you grep for that string in your project directory? I bet there's a local.properties file somewhere with that string.

**Comment by ptariche** [comment]
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Thu Dec 21 13:43:02 PST 2017
sdk.dir=/Users/zzPeter/Library/Android/sdk

**Comment by jesseruder** [comment]
Ok, did you search for `/Users/jesseruder/Library/Android/sdk` in your project directory?

**Comment by ptariche** [comment]
Haha =D

**Comment by brentvatne** [comment]
@ptariche - @jesseruder is asking where that string appears in your project

**Comment by ptariche** [comment]
`FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory '/Users/jesseruder/Library/Android/sdk' does not exist.
* Try:
Run with --info or --debug option to get more log output.
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)`

when running

`Running gradle task...
./android/gradlew "--build-file" "./android/app/build.gradle" "assemble" "--stacktrace" "--no-daemon"
Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip`

**Comment by ptariche** [comment]
This is with:

exp 47.1.2
expo 24

**Comment by anp** [comment]
Can you paste the output of `git grep '/Users/jesseruder/Library/Android/sdk'` when run from the directory of your project that holds app.json?

**Comment by ptariche** [comment]
This was an automated build I had working with bitrise. Let me see if I can see if I can pull from their logs. This was working with 23^.

Prior to the error, I

"f you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/jesseruder/android-ndk-r10e."

**Comment by brentvatne** [comment]
@ptariche - regardless of that, can you not do what @anp asked above? it should just be building the code that you already have in your repo

**Comment by ptariche** [comment]
(END)

**Comment by ptariche** [comment]
➜  app git:(expo-24) ✗ git grep '/Users/jesseruder/Library/Android/sdk'

(END)

**Comment by ptariche** [comment]
"detach": {
      "scheme": "expa9e968dde4b4435cb81d0c096d00afda",
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.2.1-sdk24.0.0-36ff2264-629d-44df-a819-8c982454e5e8.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.2.0-sdk24.0.0-f3c74eb9-2084-4c71-8358-ab9eb312bc4b.tar.gz"
    }

https://s3.amazonaws.com/exp-exponent-view-code/android-v2.2.0-sdk24.0.0-f3c74eb9-2084-4c71-8358-ab9eb312bc4b.tar.gz"


## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Tue Aug 22 12:16:28 PDT 2017
sdk.dir=/Users/jesseruder/Library/Android/sdk
ndk.dir=/Users/jesseruder/android-ndk-r10e


![screen shot 2017-12-21 at 3 40 48 pm](https://user-images.githubusercontent.com/3300641/34279373-5dc29ed4-e665-11e7-8a88-fc2031c6bf95.png)

**Comment by jesseruder** [comment]
Should be fixed in the new version of exp! 47.1.4

**Comment by nikki93** [comment]
Nice so this file has the `/Users/jesseruder/Library/Android/sdk` path ^ -- if you replace that with your path under `/Users/` followed by your username, that should move you ahead.
