### ISSUE TITLE
Slash doesn't hide on Android APK

### ISSUE THREAD

**Issue by pabeda-bt** [expo/expo#1147]
It works good on development mode, but error occurs with APK.
It is showing a splash screen, but splash screen stays as background for all screen.

Here is my Build ID: 0ab8af8d-091d-43b5-9606-2724494c620d

Here is my app.json

[{
   "expo": {
    "name": "Myapp",
    "icon": "./src/assets/images/appIcon.png",
    "version": "1.0.1",
    "slug": "com-myapp-myslug",
    "sdkVersion": "21.0.0",
    "ios": {
      "bundleIdentifier": "com.myapp.myslug"
    },
    "android": {
      "package": "com.myapp.myslug"
    },
    "loading": {
      "backgroundColor": "#FF0000",
      "hideExponentText": false,
      "icon": "./src/assets/images/appIcon.png"
    },
    "splash": {
      "image":"./src/assets/images/splashScreen.png",
      "resizeMode":"contain",
      "backgroundColor": "#f5a623"
    }
  }
 }](url)

**Comment by brentvatne** [comment]
post more information to forums.expo.io, ideally also a link to your source
