### ISSUE TITLE
react-navigation drawer gesture

### ISSUE THREAD

**Issue by AnasAlamin** [expo/expo#11475]
### Summary of Issue 
after updating to expo 40, on sliding gesture for drawer there is lagging and screen turns white for few milliseconds 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
@react-navigation/drawer": "^5.9.0
expo": "^40.0.0

**Comment by byCedric** [comment]
Hi @AnasAlamin, thanks for the issue report. Unfortunately, without more context and reproducible example I'm not sure how to help you further. [The minimal example from React Navigation](https://reactnavigation.org/docs/drawer-based-navigation/#minimal-example-of-drawer-based-navigation), using the drawer and slide gesture is working fine on our end.

If you still think this is an issue with Expo or React Navigation, please open a new issue with all the information we ask from the bug template.

Hope this helps!

**Comment by AnasAlamin** [comment]
> Hi @AnasAlamin, thanks for the issue report. Unfortunately, without more context and reproducible example I'm not sure how to help you further. [The minimal example from React Navigation](https://reactnavigation.org/docs/drawer-based-navigation/#minimal-example-of-drawer-based-navigation), using the drawer and slide gesture is working fine on our end.
> 
> If you still think this is an issue with Expo or React Navigation, please open a new issue with all the information we ask from the bug template.
> 
> Hope this helps!

thank you for your reply, anyway i was able to solve it by upgrading react-native-gesture-handler

**Comment by vujevits** [comment]
I'm having the same issue, but upgrading `react-native-gesture-handler` did not help. The issue only happens on iOS, with the released app. It's working both with the iOS Simulator, and the expo client running the app on the physical device.

There's an issue on the forum as well: https://forums.expo.io/t/react-navigation-drawer-wont-open-close-when-swiping-from-the-side-of-the-screen-ios/47338
