### ISSUE TITLE
Speech.isSpeakingAsync returning [object Object]

### ISSUE THREAD

**Issue by Razorholt** [expo/expo#11473]
Speech.isSpeakingAsync() doesn't return 'true' while speaking or pausing. it returns [object Object]. Am I missing something?

**Comment by brentvatne** [comment]
it returns a promise that resolves to true or false

**Comment by xam7247** [comment]
I don't know why isSpeaking needs to be an Async function, requiring everyone to create a wrapper in their implementation to handle the promise. I feel it would be better if the function could just return the boolean value.
