### ISSUE TITLE
Link to docs when showing "Couldn't find a build phase "Bundle React Native code and images" in build:configure

### ISSUE THREAD

**Issue by TrustyTechSG** [expo/expo#11478]
eas build:configure
💡 The following process will configure your iOS and/or Android project to be compatible with EAS Build. These changes only apply to your local project files and you can safely revert them at any time.

✔ Which platforms would you like to configure for EAS Build? › All

✔ Generated eas.json
✔ Android project configured
    Error: Couldn't find a build phase "Bundle React Native code and images"

**Comment by brentvatne** [comment]
hi there! every react-native project has a build phase named "Bundle React Native code and images" -- unless it has been removed from the project.

for example, initialize a new project with `expo init` and choose bare workflow, then go to the build phases section in xcode and you will see it there. you can copy that to your project.
