### ISSUE TITLE
[docs] `expo-auth-session/providers/facebook` documentation is wrong/outdated

### ISSUE THREAD

**Issue by fr3fou** [expo/expo#11471]
The provided code example doesn't work.

![image](https://user-images.githubusercontent.com/1344906/103181064-797d7180-48a5-11eb-9927-8b739edef58b.png)

This is the error I get with this code:

![image](https://user-images.githubusercontent.com/1344906/103181074-8dc16e80-48a5-11eb-9284-5dfa510641dc.png)

After adding the `fb` prefix in front, I get this error:

![image](https://user-images.githubusercontent.com/1344906/103181092-b5b0d200-48a5-11eb-878a-74cac914dd6d.png)

After adding `://authorize` at the end, like so:

![image](https://user-images.githubusercontent.com/1344906/103181112-01fc1200-48a6-11eb-89c7-f7f767baeb0a.png)

I still get the same error as before:

![image](https://user-images.githubusercontent.com/1344906/103181118-16400f00-48a6-11eb-9b10-c302843790ee.png)

**Comment by MMDF** [comment]
It seems that the expo facebook auth uses API v6. I can't find anything about the fb<Client-ID> uri scheme for redirects on the docs right now. And I can't add it as a valid redirect because facebook enforces HTTPS?

**Comment by MMDF** [comment]
Ok I have figured out everything. It's just that the documentation structure should've made it easier for beginners in my opinion. The reason the first example doesn't work is that you haven't added the expo auth url to Valid Oauth Redirects in the Facebook console. In development mode, AuthSession by default has a redirect url of https://auth.expo.io/@user/appname . You have to replace user with your expo username and appname with your app's published name and then add this to every oauth provider you use. In production however, for Facebook it will use fb<client-id>://authorize and for other providers it will use whatever redirect uri you provide, might be yourscheme://authorize or whatever you want.

Now, the documentation doesn't explain it in the right places for people like me that want to implement Facebook login. I look at the Facebook login guide and I see no indication that I should've also added auth.expo.io to my allowed redirects. I believe a link should be put in every Auth guide in the documentation to ["It makes redirect URL allowlists easier to manage for development and working in teams"](https://docs.expo.io/versions/latest/sdk/auth-session/#it-makes-redirect-url-allowlists-easier-to) which explains the mechanism I explained above much better than I did. It took me some time to figure out this was what I needed to do to get it working.

**Comment by MMDF** [comment]
Oh also, the provided code example for Facebook has a couple compilation problems.

**Comment by CaioMars** [comment]
Thanks for the explanation @MMDF! I'm getting there though I get a blank page with no response from Facebook Auth. Basically I click on authorize (to access facebook's user data) and then a blank page lingers on, without any response. I think my problem is on the redirect URI but I am not completely sure.

As you have mentioned, I added `https://auth.expo.io/@user/appname` in the `Valid OAuth Redirect URIs` in Facebook Console. I also added `<data android:scheme="fb{FACEBOOK_APP_ID}"/>` to my Android manifest. Do you know if I have to add a redirect URI to the manifest as well? If so, how do I do that?

This is my work flow for my sign-in:

    // FACEBOOK SIGN-IN
    const [
        requestFacebookAuth,
        responseFacebookAuth,
        promptFacebookAuthAsync,
    ] = Facebook.useAuthRequest({
        clientId: FACEBOOK_APP_ID,
        redirectUri: `fb${FACEBOOK_APP_ID}://authorize`,
        responseType: ResponseType.Token,
    });

    React.useEffect(() => {
        console.log(responseFacebookAuth);
        if (responseFacebookAuth?.type === "success") {
        const { access_token } = responseFacebookAuth.params;

        const credential = firebase.auth.FacebookAuthProvider.credential(
            access_token
        );
        // Sign in with the credential from the Facebook user.
        // clientFirebase.auth.signInWithCredential(credential);
        } else {
        if (loading) setLoading(false);
        }
    }, [responseFacebookAuth]);

In the expo-auth-session documentation, I am confused about the line:

    The `native` redirect URI must be formatted like fbYOUR_NUMERIC_ID://authorize

It's not clear to me what they mean by "native". I explicitly added the redirect URI in my code in the config parameters as shown above. I also tried using the function `AuthSession.makeRedirectUri()` to created it but no luck so far.

Got any suggetions on what I should try next? It's a bit frustrating the lack of instructions on how to get this to work ;/

**Comment by MMDF** [comment]
Actually my suggestion would be to not use the provided Facebook AuthRequest API because it is broken on Android standalone for expo! I eventually switched to Instagram Basic Display API but before that this was what I used on Android:
```tsx
const isNative = Constants.appOwnership !== "expo" && Platform.OS !== "web";
const useProxy =
  (Constants.appOwnership === "expo" && Platform.OS !== "web") ||
  Platform.OS === "android";

const discovery = {
  authorizationEndpoint: "https://www.facebook.com/v9.0/dialog/oauth",
  tokenEndpoint: "https://graph.facebook.com/v9.0/oauth/access_token",
};

const config = {
  clientId: FACEBOOK_ID,
  scopes: [
    "public_profile",
    "email",
    "instagram_basic",
    "instagram_manage_insights",
    "pages_show_list",
  ],
  responseType: ResponseType.Token,

  // For usage in managed apps using the proxy
  redirectUri: isNative
    ? Platform.OS === "android"
      ? `https://auth.expo.io/@user/slug`
      : `fb${FACEBOOK_ID}://authorize`
    : makeRedirectUri({
        useProxy,
        // For usage in bare and standalone
        // Use your FBID here. The path MUST be `authorize`.
        native: `fb${FACEBOOK_ID}://authorize`,
      }),

  useProxy,
  extraParams: {
    // Use `popup` on web for a better experience
    // display: Platform.select({ web: 'popup' }) as string,
    // Optionally you can use this to rerequest declined permissions
    auth_type: "rerequest",
  },
};
export const InstagramCard: React.FC = () => {
  const [request, response, promptAsync] = useAuthRequest(config, discovery);
  // ...
}
```
I copied most of this code from the issue I found but it worked for me. I overall had a very bad experience with AuthSession because its options and the behavior of the utility functions were not documented well and they behaved differently (I had to read the source code to figure out what they'd do and how I could manipulate them to do what I want, even then I was wrong multiple times)
