### ISSUE TITLE
onFullscreenUpdate is executed twice in IOS and Andriod

### ISSUE THREAD

**Issue by Vivekmanu4343** [expo/expo#11479]
## 🐛 Bug Report

onFullscreenUpdate is executed twice in IOS and Andriod whenever I click on default fullscreen or minimize screen.

### Summary of Issue 
I have been trying to find a way to display fullscreen landscape video play in android and I found a useful prop in the video component which will help us execute some code to change the screen orientation but when I just put a console statement, I could notice that console statement is executing twice whenever I click on fullscreen or minimize.

### Environment 
IOS and Andriod

### Reproducible Demo
The issue can be reproduced here.
[https://snack.expo.io/@vivek4334/onfullscreenupdate-is-executed-twice-in-ios-and-andriod](https://snack.expo.io/@vivek4334/onfullscreenupdate-is-executed-twice-in-ios-and-andriod
)
### Steps to Reproduce
just open the logs and click on maximize and minimize the screen using native controls

### Expected Behavior vs Actual Behavior
onFullscreenUpdate should be executed only once but it's executing twice

**Comment by Vivekmanu4343** [comment]
Hi Team,

Is anybody looking into this or could you please provide some solution?

**Comment by TowhidKashem** [comment]
+1 experiencing this on IOS (I don't support Android). Currently working around it like this:

```
  const eventFired = useRef(false);

  <Video
      onFullscreenUpdate={(): void => {
        if (!eventFired.current) {
          analytics.logEvent('full_screened');
          eventFired.current = true;
        }
      }}
      // etc...
/>
```

but would be good to get a proper fix.
