### ISSUE TITLE
Calling ResumableDownload.pauseAsync() destroys download/throws exception

### ISSUE THREAD

**Issue by coreyRalli** [expo/expo#11482]
### Summary of Issue
When ``pauseAsync`` is called on a ``DownloadResumable`` an exception is thrown: ``('Error: stream was reset: CANCEL')``. Trying to resume the download throws another error '‘No download object available’. Resume data is still returned so you can technically resume by creating another ``DownloadResumable``, though the documentation implies you should just be able to call ``pause/resumeAsync``.

### Environment
react-native-unimodules: 0.12.0/expo-file-system: 9.3.0
react-native: 0.63.4
Android 11/Pixel 4a

### Reproducible Demo
[Snack repro](https://snack.expo.io/b9eAt3ApL)
 
### Steps to Reproduce
1. Create a ``DownloadResumable`` object
2. Call ``downloadAsync`` on it
3. Once the download is started, call ``pauseAsync``. Exception will be thrown.
4. Call ``resumeAsync`` on same download, another exception will be thrown.

### Expected Behavior vs Actual Behavior
Expected: Calling ``pauseAsync`` should pause the download and block the original ``downloadAsync()`` promise from resolving until ``resumeAsync()`` is called.

Actual: Calling ``pauseAsync`` closes the connection and destroys the download object, requiring passing the resume data into a new ResumableDownload, contrary to the code sample in the [documentation](https://docs.expo.io/versions/latest/sdk/filesystem/)

**Comment by elliotdickison** [comment]
Verified this on a Pixel 3a running Android 11. I'm using an older version of expo-file-system though: 11.1.3
