### ISSUE TITLE
Expo-av doesn't work on ios 13.5

### ISSUE THREAD

**Issue by VitaliiTsurkan** [expo/expo#11480]
### Summary of Issue 
Expo-av doesn't work on ios 13.5 but works correctly on ios 14(14.0-14.3)
Video just not playing on ios 13.5. but on 14 versions works ok both managed and bare flows.
Fullscreen button is working but playing -no.
Both automatic autoplay and state triggering have the same behavior.
Not a problem with video URL.
player works correctly on android.
### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  "expo": "~40.0.0",
   "expo-av": "~8.7.0",
can confirm that repro in managed and bare flow with different versions of sdk and expo-av

expo diagnostics                                                                          ─╯

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.3.0 - /usr/local/opt/node/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 7.0.14 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 25, 26, 28, 29
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 28.0.3, 29.0.2
        System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

### Steps to Reproduce
All cases (also try basic code example in documentation). 

### Expected Behavior vs Actual Behavior
Expected Behavior: video player works correctly;
Actual Behavior:  video player doesn't work at all;

**Comment by AdamJNavarro** [comment]
Hey @VitaliiTsurkan, please provide a working, publicly-accessible reproduction of the issue when creating issues on the Expo repo. I'm going to close this for now but will gladly reopen when you can provide a repro.

Cheers,
Adam

**Comment by VitaliiTsurkan** [comment]
Hey, @AdamJNavarro here is a screen recording of running one code on ios 13.5 and 14.3 and simulators are the same too.
https://user-images.githubusercontent.com/49519698/103344086-40f0ba00-4a96-11eb-8008-5b0afe28775d.mov

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Video } from 'expo-av';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Video
        source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
        rate={1.0}
        volume={1.0}
        isMuted={false}
        resizeMode="cover"
        useNativeControls
        shouldPlay
        isLooping
        style={{ width: 300, height: 300 }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~40.0.0",
    "expo-av": "~8.7.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}
