### ISSUE TITLE
Expo Ads Facebook

### ISSUE THREAD

**Issue by Daniyalzakir321** [expo/expo#11483]
**Facebook ads not showing in expo**

import React from 'react'
import * as FacebookAds from 'expo-ads-facebook';
import { View} from 'react-native'

export default function ADS(props) {
    return (
        <View>
                   <FacebookAds.BannerAd
                  placementId="549167759165615_549192715829786"
                  type="standard"
                  onPress={() => console.log('click')}
                  onError={error => console.log('error', error)}
                />
        </View>
    )
}

![134088611_694361374615916_4051578663485612289_n](https://user-images.githubusercontent.com/41327126/103313378-c3b14080-49d4-11eb-964d-d101da23a695.jpg)

**At the top, their is a banner ads but its not showing...**

**Comment by AdamJNavarro** [comment]
Hey @Daniyalzakir321, can you please provide your environment information/version numbers relevant to the issue?

**Comment by Daniyalzakir321** [comment]
Hi @AdamJNavarro,  here it is:

![image](https://user-images.githubusercontent.com/41327126/103423966-adcf8700-4b5e-11eb-93ff-1a92ad65343b.png)

**Comment by AdamJNavarro** [comment]
Hey @Daniyalzakir321, I would suggest taking a look at this section of our docs: https://docs.expo.io/versions/v40.0.0/sdk/facebook-ads/#troubleshooting and see if that helps you get to the bottom of what's happening in your project. If you find a reproducible bug, please let me know and we can re-open this issue.

Thanks,
Adam

**Comment by Daniyalzakir321** [comment]
@AdamJNavarro 
No its not solved....
