### ISSUE TITLE
Why the entry point for Snack is `app.js`? Shouldn't it be `App.js`?

### ISSUE THREAD

**Issue by leosurwiki** [expo/expo#1149]
I am trying to use `Snack` in my project. But I have found that the entry point for `Snack` is `app.js` while react-native-script require `App.js` to be the entry point.

**Comment by quinlanj** [comment]
@leosurwiki afaik its `App.js`. Could you explain more on where you found the entry point to be `app.js`?
![screen shot 2017-12-22 at 12 29 59 pm](https://user-images.githubusercontent.com/6380927/34311717-0ab7aac2-e714-11e7-9db1-adec12bb9764.png)

**Comment by leosurwiki** [comment]
@quinlanj sorry, I mean in snack sdk:
https://github.com/expo/snack-sdk/blob/7300757fe65251ce31c5308e64eba2df4db69fe0/src/SnackSession.js

**Comment by jesseruder** [comment]
What exactly are you trying to do? Very few people need to use snack-sdk.

From the README:
> Use this to create a custom web interface for https://snack.expo.io/

**Comment by leosurwiki** [comment]
@jesseruder 
I tried to upload my project on snack.expo.io, but I got
![image](https://user-images.githubusercontent.com/5493592/34313284-db9f879a-e71e-11e7-95a3-55db07db38ab.png)

What I am trying to do instead is uploading my project through `snack-sdk`. But it requires `app.js` to be present.

**Comment by jesseruder** [comment]
Can you send a screenshot of what you did to try to upload your project to snack.expo.io?

Ok, snack-sdk isn't really intended for this purpose, so we can't spend much time debugging this with you. It sounds like based on the error message you might want to rename App.js to app.js, but you'll have to dig in yourself if you hit more errors.

**Comment by leosurwiki** [comment]
Thanks! I will try to find other solutions!

**Comment by jesseruder** [comment]
If you show us what went wrong on the snack website we can help you with that!
