### ISSUE TITLE
[docs] SplashScreen delay guidance is invalid

### ISSUE THREAD

**Issue by mklaber** [expo/expo#11498]
The [Configuration](https://github.com/expo/expo/blob/master/docs/pages/tutorial/configuration.md) page includes this hint:

> Is the app loading too quickly for you to get a good look at the splash screen?

But, this API has been removed from the`expo` package, or so says the exception thrown in the iOS app.

If an industrious reader follows the exception's instructions and installs `expo-splash-screen`, then uses the knowledge they've gained from the previous steps and adds: `import * as SplashScreen from 'expo-splash-screen';`, they do get the desired results. But they'll be greeted with a deprecation notice for `preventAutoHide()`, and then again for `SplashScreen.hide` after the 5s timeout.

I'd submit a PR with a suggested change but given this is my first and only interaction with expo, I'm probably not well suited to guide other new users :-)

**Comment by brentvatne** [comment]
thank you kindly for pointing this out! looks like we missed a spot to update after removing the SplashScreen import recently. fixed in https://github.com/expo/expo/commit/ecdd37fd11af908823c3a112ff639c93a69552bc and currently being deployed :)
