### ISSUE TITLE
[Expo-in-app-purchase][Android] Exception was thrown when calling `InAppPurchases.purchaseItemAsync(productID)`: - [Error: Encountered an exception while calling native method: Exception occurred while executing exported method purchaseItemAsync on module ExpoInAppPurchases: null]

### ISSUE THREAD

**Issue by Jkkarr2015** [expo/expo#11496]
### Summary of Issue 
The line `await InAppPurchases.purchaseItemAsync(productID)` throws the following error: ` [Error: Encountered an exception while calling native method: Exception occurred while executing exported method purchaseItemAsync on module ExpoInAppPurchases: null]`. This issue only occurs on Android devices and occurs with and without the second parameter `oldItem`. The purchase is a none consumable one-time purchase.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.4 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.2.2 => 4.4.3
      expo-in-app-purchases: ^8.2.1

Target Platforms:
iOS
Android

### Expected Behavior vs Actual Behavior
I would expect the method to open a prompt for users to be able to purchase the in-app product like I am seeing on iOS, but in actuality, it just throws the error and never opens a prompt.

**Comment by Jkkarr2015** [comment]
I believe I found the issue for anyone else that comes across this issue. It looks like the parameter `oldItem` is mandatory even though the documentation says it can be null.  I do not use the parameter so I just went into `BillingManager.java` and changed line 146/147 from:

` BillingFlowParams purchaseParams = BillingFlowParams.newBuilder()
          .setSkuDetails(skuDetails).setOldSku(oldSku).build();`

to:

` BillingFlowParams purchaseParams = BillingFlowParams.newBuilder()
          .setSkuDetails(skuDetails).build();`

and that fixed my issue. Maybe it should be amended to not try to call `setOldSku()` if the `oldSku` is null.

**Comment by cruzach** [comment]
hi @Jkkarr2015 sorry for the slow followup, but this will be fixed in this PR: https://github.com/expo/expo/pull/13884

Thanks for the report!

**Comment by RonaldoBueno16** [comment]
What is the solution?

**Comment by Jkkarr2015** [comment]
@RonaldoBueno16  I'm not sure what version you are running, but I thought they had fixed this issue. If this is still a problem you may want to open a new ticket about this. I was able to fix it using the steps I documented in my January 5th comment.

**Comment by haron68** [comment]
Still seeing this problem too

**Comment by miamiappmachine** [comment]
Experiencing the same thing here.

Expo SDK 45.0.4
expo-in-app-purchases 13.0.0

**Comment by duggster** [comment]
> This same error gets thrown when you don't include a details object on Android - see:
> 
> https://docs.expo.dev/versions/latest/sdk/in-app-purchases/#inapppurchasespurchaseitemasyncitemid-details

Thanks @miamiappmachine, this helped me get past this error after upgrading to SDK45. Also I referenced the Google API for more info about the accountIdentifiers in the details object: https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setObfuscatedAccountId(java.lang.String)
