### ISSUE TITLE
BackgroundFetch is Available when Low Power Mode is on

### ISSUE THREAD

**Issue by cesconix** [expo/expo#11505]
### Summary of Issue 
The response of `await BackgroundFetch.getStatusAsync()` returns `Available` when Low Power Mode is enabled. 

Considering the Background App Refresh feature is automatically disabled by iOS when Low Power Mode is enabled, I expected the status should returns `Denied`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I cannot simulate Low Power Mode in iPhone simulator, so I tried to my real device: **iPhone 7 (iOS 14.1)**.

```
  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.2.0 - ~/.nvm/versions/node/v15.2.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.2.0/bin/yarn
      npm: 7.0.11 - ~/.nvm/versions/node/v15.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed
```

### Reproducible Demo

https://snack.expo.io/@quicki.app/issue-backgroundfetch-status
 
### Steps to Reproduce

1. In your iPhone set Low Power Mode
2. Open Expo Snack from Expo Client app
3. See the centered label

### Expected Behavior vs Actual Behavior

Expected: 1 or 2
Actual: 3

The status code (BackgroundFetch.Status) should not be 3 (Available), but 1 or 2.

**Comment by brentvatne** [comment]
can you point out the mistake in the logic here? it seems correct to me:

https://github.com/expo/expo/blob/c8501408a105c2feb23320fdb81310e2d77767a2/packages/expo-background-fetch/ios/EXBackgroundFetch/EXBackgroundFetch.m#L84-L96

**Comment by cesconix** [comment]
@brentvatne, unfortunately, I don't understand very well the syntax in the example, but it seems clear and correct also for me. Probably the backgroundRefreshStatus is not closely related to low-power mode.

So I read the Apple Documentation about  **backgroundRefreshStatus**  and it says:

> You can use this property to determine whether Background App Refresh—an app's ability to open in the background to perform refresh tasks—is enabled, and warn the user if it is not. Don't warn the user if the value of this property is set to UIBackgroundRefreshStatusRestricted. A restricted user, such as one who is managed under parental controls, can't enable Background App Refresh.
> 
> Background App Refresh is disabled automatically when a device is operating in low-power mode. When this happens, the time available for performing background tasks is reduced to save power.

Apple Documentation: https://developer.apple.com/documentation/uikit/uiapplication/1622994-backgroundrefreshstatus?language=objc

The sentence is ambiguous: is not clear to me if it's completely disabled or available with a reduced time available to perform the background task.

**Comment by brentvatne** [comment]
@cesconix - sorry i'm not really sure here, this might be a question better suited for apple. we use their api and give back the result that it returns, so if that doesn't return the result you expect it seems like a documentation issue with ios or a bug with ios
