### ISSUE TITLE
@babel/plugin-proposal-nullish-coalescing-operator doesn't work with “babel-preset-expo”

### ISSUE THREAD

**Issue by liushigit** [expo/expo#1150]
# Bug report

When working with [@babel/plugin-proposal-nullish-coalescing-operator ](https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-nullish-coalescing-operator), there will be:

> TransformError: ...Cannot read property 'loose' of undefined

[Demo](https://github.com/liushigit/babel-nco-plugin-issue)

[Mirror Issue]: https://github.com/babel/babel/issues/7089

To run (on macOS): 
```bash
yarn install
react-native run-ios
```
 
### Input Code

`const a = 2 ?? 3`

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
```js
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  },
  "plugins": ["@babel/plugin-proposal-nullish-coalescing-operator"]
}
```

### Expected Behavior

The app should run. 

### Current Behavior

> TransformError: 
> ...Cannot read property 'loose' of undefined

### Context

The demo was created with [`create-react-native-app`](https://github.com/react-community/create-react-native-app). I tried using a statement like `const a = 2 ?? 3` in the `App.js` but found it doesn't work. Is there any conflict between `babel-preset-expo` and `@babel/plugin-proposal-nullish-coalescing-operator`?

### Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  "babel-cli": "^6.26.0"
| Babylon          | 
| node             | v8.9.1
| npm              | 
| Operating System | macOS 10.13.2
|  @babel/plugin-proposal-nullish-coalescing-operator | 7.0.0-beta.35
|  @babel/core | 7.0.0-beta.35

**Comment by ide** [comment]
Hi @liushigit, I don't think we've tried this plugin before. Can you debug Babel and the plugin more to help identify the issue more precisely?

**Comment by liushigit** [comment]
I'd love to. But first I need to understand the toolchain used here, since the `create-react-native-app` toolchain is not explicit. One comment from the referenced mirror Issue says @babel/cli (7.0) should be used. I suspect that the project is using another version of Babel implicitly, right?

Could you give me a hint how to debug this issue? Shall I `eject` the project first? Many thanks!

**Comment by ide** [comment]
React Native uses Babel 6 -- one way to figure this out is to look under node_modules to see what's actually installed (you also can run `yarn why babel-core` for example). If the plugin requires Babel 7, that's probably the problem. But to debug further I'd generally try reducing your source code to the bare minimum and then add bits of code under Babel and the plugin under node_modules to figure out what's going on.

**Comment by liushigit** [comment]
Thanks! The [demo](https://github.com/liushigit/babel-nco-plugin-issue) is a vanilla project created with create-react-native-app, with only a line of code added.

**Comment by ide** [comment]
You could try this again since Metro (the React Native packager) now may support Babel 7. But this isn't something that we're focusing on with Expo until React Native ships Babel 7 upstream.
