### ISSUE TITLE
Error encountered while fetching Expo token

### ISSUE THREAD

**Issue by navicstein** [expo/expo#11508]
Am  logged in to expo but I  receive this error when trying to get expo push token 

```sh
$ expo login 
✔ You are already logged in as xxxxxx. Log in as new user? … no
```
then later...

`[Unhandled promise rejection: Error: Error encountered while fetching Expo token, expected an OK response, received: 400 (body: "{"errors":[{"code":"VALIDATION_ERROR","message":"The Expo push notification service is supported only for Expo projects. Ensure you are logged in to your Expo developer account on the computer from which you are loading your project."}]}").]`

```sh
$  expo diagnostics
  Expo CLI 3.28.6 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.8.0 - /opt/node/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.7 - /opt/node/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.6
    Expo Workflow: managed


```

am using `    "expo-notifications": "~0.8.2"`

**Comment by brentvatne** [comment]
are you sure that you're still authenticated? are you running the expo server on your local machine or in cloud? what is your username?

**Comment by navicstein** [comment]
username's `navicstein`, am still authenticated because I can publish to my release channel

**Comment by navicstein** [comment]
@brentvatne I've found the problem

I was running `expo --offline --lan`
It's working now, thanks

**Comment by samiklah** [comment]
@navicstein  
Hi, 

will I be able to get the token in production app ios and android, not all the app users need to log in to expo right? 

I need to save each user token in database and send a notification with a post requests in backend, is it good solution for now?

**Comment by madniqureshi** [comment]
Actually, you have to complete the authentication either using a username or email address right after pressing the command "expo login" in cli.

**Comment by PrettyLegit0101** [comment]
logged in on the expo app and in the cli and it worked. Thanks.
