### ISSUE TITLE
Unrecognized permission: mediaLibrary

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#11504]
### Summary of Issue 
I have upgraded my expo sdk to the last one, and I am refactoring the permissions manager of my app.
When asking for the permissions of the camera roll, I get the error "Unrecognized permission: mediaLibrary"

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.27.13 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: ^16.13.1 => 16.14.0
      react-dom: 16.11.0 => 16.11.0
      react-native: ^0.63.4 => 0.63.4
      react-native-web: ~0.13.7 => 0.13.18
    Expo Workflow: managed

### Steps to Reproduce
Test the following code on iOS 14:

 ```
import { Camera as ExpoCamera } from "expo-camera";
import * as MediaLibrary from "expo-media-library";
import * as Permissions from "expo-permissions"; <--------

...
 const [hasPermission, setHasPermission] = useState(null);

 useEffect(() => { <------
    // TODO - Request CAMERA and CAMERA_ROLL permissions https://docs.expo.io/versions/latest/sdk/media-library/
    (async () => {
      const { status } = await Permissions.askAsync(
        Permissions.CAMERA,
        Permissions.MEDIA_LIBRARY
      );

      setHasPermission(status === "granted");
    })();
  }, []);
```

### Expected Behavior vs Actual Behavior
How can I be able to ask media library permissions in the new sdk?

"expo-camera": "~9.1.0",
"expo-media-library": "~10.0.0",
"expo-permissions": "~10.0.0",

**Comment by VictorioMolina** [comment]
Update: If I explictly write "cameraRoll", it works good.

` const { status } = await Permissions.askAsync("camera", "cameraRoll");`

But... Permissions.CAMERA_ROLL is deprecated:

```

import { PermissionResponse, PermissionType, PermissionMap, PermissionStatus, PermissionExpiration, PermissionInfo } from './Permissions.types';
export { PermissionStatus, PermissionResponse, PermissionExpiration, PermissionMap, PermissionInfo, PermissionType, };
export declare const CAMERA = "camera";
export declare const MEDIA_LIBRARY = "mediaLibrary";
export declare const MEDIA_LIBRARY_WRITE_ONLY = "mediaLibraryWriteOnly";
/**
 * @deprecated Use `MEDIA_LIBRARY` or `MEDIA_LIBRARY_WRITE_ONLY`
 */
export declare const CAMERA_ROLL = "mediaLibrary";
export declare const AUDIO_RECORDING = "audioRecording";
export declare const LOCATION = "location";
export declare const USER_FACING_NOTIFICATIONS = "userFacingNotifications";
export declare const NOTIFICATIONS = "notifications";
export declare const CONTACTS = "contacts";
export declare const CALENDAR = "calendar";
export declare const REMINDERS = "reminders";
export declare const SYSTEM_BRIGHTNESS = "systemBrightness";
export declare const MOTION = "motion";
export declare function getAsync(...types: PermissionType[]): Promise<PermissionResponse>;
export declare function askAsync(...types: PermissionType[]): Promise<PermissionResponse>;
```

**Comment by brentvatne** [comment]
sorry is this on ios, android, or web?

**Comment by VictorioMolina** [comment]
@brentvatne ios

**Comment by brentvatne** [comment]
we've moved away from using the `Permissions` module as the central way to request permissions and prefer calling the permissions requesters directly on the modules now.

so, [MediaLibrary.requestPermissionsAsync()](https://docs.expo.io/versions/latest/sdk/media-library/#medialibraryrequestpermissionsasync) would be the solution here.

example: https://snack.expo.io/@brents/shallow-blueberries

that said, we should keep these old methods working or deprecate them

**Comment by diegomais** [comment]
When using [MediaLibrary.saveToLibraryAsync()](MediaLibrary.saveToLibraryAsync(localUri)), I received the error: `Missing MEDIA_LIBRARY write permission`.
Then I added [MediaLibrary.requestPermissionsAsync()](https://docs.expo.io/versions/latest/sdk/media-library/#medialibraryrequestpermissionsasync) before saving the media, but I still got the error: `Missing MEDIA_LIBRARY write permission`.

The workaround was using [ImagePicker.requestMediaLibraryPermissionsAsync()](https://docs.expo.io/versions/latest/sdk/imagepicker/#imagepickerrequestmedialibrarypermissionsasyncwriteonly).

It would be nice to also have MediaLibrary.requestMediaLibraryPermissionsAsync().

**Comment by brentvatne** [comment]
@diegolmello - is this on ios or android?

**Comment by diegomais** [comment]
It is on Android 10.

**Comment by brentvatne** [comment]
@diegomais - can you please share a reproducible example? this appears to work as expected here: https://snack.expo.io/@brents/image-picker

**Comment by diegomais** [comment]
@brentvatne - follow a reproducible example: https://snack.expo.io/@diegomais/save-to-library

**Comment by heyheyjude** [comment]
The same problem on Android 11 (Huawei P30), but its work properly on emulator with android 10 or other real devices, 
I noticed, that MediaLibrary.getPermissionsAsync / MediaLibrary.requestPermissionsAsync always return 
{"status": "undetermined", "canAskAgain": false, "expires": "never", "granted": false} even if manually set up this permission
READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE also added to Manifest

**Comment by professorkolik** [comment]
Same here, any updates on this? @brentvatne

**Comment by heyheyjude** [comment]
> Same here (Android 11 API 30), any updates on this? @brentvatne
> **UPDATE** Resolved on my side
> The issue was that I had another package which has
> `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" />`
> When I built app, AndroinManifest.xml was merged together and at the end I haven't got permissions for using expo-media-library

thank you for explanation, because i have the same. But that's a problem that from SDK 29 we can't use WRITE_EXTERNAL_STORAGE, and should use scoped storage, but i can't find any info about supporting that in expo-media-library

**Comment by professorkolik** [comment]
@heyheyjude  I think for now, it's ok, so we have working media-library, and lets hope expo-media-library will be upgraded to support scoped storage, or at least get rid of WRITE_EXTERNAL_STORAGE permission

**Comment by Joshandrews43** [comment]
What is the solution here? I have hundreds of users getting `Missing MEDIA_LIBRARY write permission.`. 


Do I just request media permissions with `ImagePicker.requestMediaLibraryPermissionsAsync()`?

**Comment by shubhamdeol** [comment]
any update on this?

**Comment by Sany655** [comment]
Expo eject to react native cli, all problem will be solved 😴, you can use all expo library there, just copy paste permission syntax...

**Comment by micha5104** [comment]
I also got the "{"status": "undetermined", "canAskAgain": false, "expires": "never", "granted": false}" reply.
For me it helped to simply delete the MediaLibrary.requestPermissionsAsync() call - make sure you actually need it. I can still write to external storage (SDK43)

**Comment by Aryk** [comment]
> What is the solution here? I have hundreds of users getting `Missing MEDIA_LIBRARY write permission.`.
> 
> Do I just request media permissions with `ImagePicker.requestMediaLibraryPermissionsAsync()`?

Using requestMediaLibraryPermissionsAsync seems to have fixed the issue for me on Android

**Comment by StampixSMO** [comment]
How is this not solved? This literally prevents anyone from using Media Library on Android?

**Comment by endruuu** [comment]
> Same here (Android 11 API 30), any updates on this? @brentvatne **UPDATE** Resolved on my side The issue was that I had another package which has `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" />` When I built app, AndroinManifest.xml was merged together and at the end I haven't got permissions for using expo-media-library

Same issue on my side. In my case, I need to use this in my project's AndroidManifest.xml file to get rid of that and it works properly now.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    ...
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion"/>
```

**Comment by CCB-cerivera** [comment]
Could someone help me, I'm on IOS 15.2 (simulator) and when requesting the MEDIA_LIBRARY permission it returns [granted] however when I use expo-media-library it returns the following error:

Error: MEDIA_LIBRARY permission is required to do this operation.

     "expo-media-library": "^12.1.2",
     "expo-permissions": "~10.0.0",

Permission routine:

const { status } = await Permissions.askAsync(Permissions.MEDIA_LIBRARY);

**Comment by jparksecurity** [comment]
@CCB-cerivera FYI I heard `Permissions` module is deprecated. Try [MediaLibrary.requestPermissionsAsync](https://docs.expo.dev/versions/v44.0.0/sdk/media-library/#medialibraryrequestpermissionsasyncwriteonly) to get the permission.

**Comment by jparksecurity** [comment]
no!

**Comment by abomblabrom** [comment]
> no!

from [docs]( https://docs.expo.dev/versions/latest/sdk/media-library/#configuration-in-appjsonappconfigjs)
setting the flag isAccessMediaLocationEnabled in the plugin resolved this for me
```
{
  "expo": {
    "plugins": [
      [
        "expo-media-library",
        {
          "photosPermission": "Allow $(PRODUCT_NAME) to access your photos.",
          "savePhotosPermission": "Allow $(PRODUCT_NAME) to save photos.",
          "isAccessMediaLocationEnabled":true
        }
      ]
    ]
  }
}
```

> Seems like we need an extra permission to be able to do this and it's missing from the docs:
> 
> ```
> <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
> ```
> 
> This solves it for me

from [docs]( https://docs.expo.dev/versions/latest/sdk/media-library/#configuration-in-appjsonappconfigjs)
setting the flag isAccessMediaLocationEnabled does it
```
{
  "expo": {
    "plugins": [
      [
        "expo-media-library",
        {
          "photosPermission": "Allow $(PRODUCT_NAME) to access your photos.",
          "savePhotosPermission": "Allow $(PRODUCT_NAME) to save photos.",
          "isAccessMediaLocationEnabled":true
        }
      ]
    ]
  }
}
```

**Comment by abomblabrom** [comment]
idk if anyone is facing this issue still - but in android 13+ i needed to explicitly request permission for READ_MEDIA_IMAGES in order to write to the media library. this solved if for me:

`  public static hasAndroidPermission = async (): Promise<boolean> => {
    const OsVer = (Platform as any).constants['Release'];

    // GET SPECIFIC MEDIA PERMISSION ANDROID 13+
    const permission = parseInt(OsVer, 10) >= 13 ? PermissionsAndroid.PERMISSIONS.READ_MEDIA_IMAGES : PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE;

    const hasPermission = await PermissionsAndroid.check(permission);

    if (hasPermission) {
      return true;
    }

    const status = await PermissionsAndroid.request(permission);

    return status === 'granted';
  }`

**Comment by balloman** [comment]
> const OsVer = (Platform as any).constants['Release'];
> 
>     // GET SPECIFIC MEDIA PERMISSION ANDROID 13+
>     const permission = parseInt(OsVer, 10) >= 13 ? PermissionsAndroid.PERMISSIONS.READ_MEDIA_IMAGES : PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE;
> 
>     const hasPermission = await PermissionsAndroid.check(permission);
> 
>     if (hasPermission) {
>       return true;
>     }
> 
>     const status = await PermissionsAndroid.request(permission);
> 
>     return status === 'granted';

I get true with has permission but am still getting the missing media permissions error when saving to camera roll

**Comment by marcelino-borges** [comment]
I have tried both
```javascript
const [mediaPermission, requestMediaPermission] = MediaLibrary.usePermissions();
```
and 
```javascript
const result: MediaLibrary.PermissionResponse = await MediaLibrary.getPermissionsAsync();
const res = await MediaLibrary.requestPermissionsAsync();
```
But I always have `{"status":"undetermined","canAskAgain":false,"granted":false,"expires":"never"}` when I get the current permissions. And the `requestPermissionsAsync` doesn't show up. I tried cleaning up expo cache and everything, but nothing changes.
The requests to ask permission for mic, photos and videos and camera are showing up though.
Struggling with this for days... =/

Please help? lol

**Comment by CCB-cerivera** [comment]
> I have tried both
> 
> ```js
> const [mediaPermission, requestMediaPermission] = MediaLibrary.usePermissions();
> ```
> 
> and
> 
> ```js
> const result: MediaLibrary.PermissionResponse = await MediaLibrary.getPermissionsAsync();
> const res = await MediaLibrary.requestPermissionsAsync();
> ```
> 
> But I always have `{"status":"undetermined","canAskAgain":false,"granted":false,"expires":"never"}` when I get the current permissions. And the `requestPermissionsAsync` doesn't show up. I tried cleaning up expo cache and everything, but nothing changes. The requests to ask permission for mic, photos and videos and camera are showing up though. Struggling with this for days... =/
> 
> Please help? lol

It shows what version of expo-media-library you are using, version of react, react native, expo and if you are using unimodules or expo modules.

In summary if you use:

```
"react-native": "0.70.5",
"react": "^18.1.0",
"expo": "^47.0.9",
"expo-media-library": "~15.0.0",
"expo-permissions": "~14.0.0",
```

The following routine should work for you:

```
import * as MediaLibrary from 'expo-media-library';
const {status} = await MediaLibrary.requestPermissionsAsync();
console.log('status--->', status === 'granted' ? true : false); 
```
I recommend you run expo doctor --fix-dependencies in case you have an outdated project based on your version of expo, react and react-native

[https://docs.expo.dev/archive/expo-cli/#expo-doctor](url)

**Comment by wahidshadab** [comment]
+1

**Comment by jpagand** [comment]
Had the same issue for android version < 13
[endruuu's solution](https://github.com/expo/expo/issues/11504#issuecomment-1034208108) was the only one to work 
Note: you have to run `npx expo prebuild -p android` to be able to edit AndroidManifest
