### ISSUE TITLE
Unable to resolve './getNotificationCategoriesAsync' in expo-notifications

### ISSUE THREAD

**Issue by ikismail** [expo/expo#11509]
I'm using expo SDK-38. trying to implement expo-notifications. followed the documentation [Notification](https://docs.expo.io/versions/v38.0.0/sdk/notifications/) for implementation. 

after installing `expo-notifications` and restarting the app. The app gets crashed, and get `unable to resolve module ./getNotificationCategoriesAsync from node_modules/expo-notification/build/index.js`

![image](https://user-images.githubusercontent.com/17190913/103488250-05a51100-4e31-11eb-9ae7-80fbec2b0dca.png)

**Expo Diagnostics:**:
Expo CLI 3.22.3 environment info:
   - System:
        - OS: macOS 11.1
        - Shell: 5.8 - /bin/zsh
   - Binaries:
        - Node: 12.16.1 - /usr/local/bin/node
        - Yarn: 1.22.4 - /usr/local/bin/yarn
        - npm: 6.14.8 - /usr/local/bin/npm
        - Watchman: 4.9.0 - /usr/local/bin/watchman
   - IDEs:
       - Xcode: 12.2/12B45b - /usr/bin/xcodebuild
   - npmPackages:
       - expo: ^38.0.0 => 38.0.10 
       - react: 16.11.0 => 16.11.0 
       - react-dom: 16.11.0 => 16.11.0 
       - react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
       - react-native-web: ~0.11.7 => 0.11.7 
       - react-navigation: ^4.0.10 => 4.4.0 
   - npmGlobalPackages:
        - expo-cli: 3.22.3

**Comment by cruzach** [comment]
Notification categories landed in SDK 39 - https://blog.expo.io/expo-sdk-39-is-now-available-4c10aa825e3f - so you should upgrade to at least SDK 39 (and `expo-notifications` version ~0.7.2) to use categories
