### ISSUE TITLE
expo publish taking long time in azure pipelines to finish

### ISSUE THREAD

**Issue by Jonatthu** [expo/expo#11516]
Command I am running is 
```
expo publish --target bare --release-channel default --non-interactive
```

As you see in the image is lasting a long time.
But locally in my computer it is really fast...

<img width="1110" alt="Screen Shot 2021-01-04 at 10 12 54 AM" src="https://user-images.githubusercontent.com/3742176/103565839-e381b200-4e75-11eb-895a-cba397529cf4.png">

My environment is:

NodeJs: 12.x
Expo: 4.0.17
OS: ubuntu-latest

Is this normal?
if not how can I solve it?

Is there any command in expo cli that can generate cache and then I can re-use it the next run?
Locally looks like it is using the cache system, I would like to use something similar in the CI,
I just need to know how to access to the cache and save it.

**Comment by brentvatne** [comment]
run `expo publish -c` locally to see how long it takes from a clear cache on your machine. metro can take a while on the first build with a cold cache, and this is especially true on constrained hardware. i'm not familiar with azure pipelines but i imagine they offer an option to use a faster ci machine, you could opt in to that.
