### ISSUE TITLE
Application size rises when show photos from internet source

### ISSUE THREAD

**Issue by pabeda-bt** [expo/expo#1151]
Hello,

I have an ap that loads image contents from internet source, I don't know why but displaying each image raises the application size (that I see in Settings->Applications->My apps detail)
This occurs with Android.

I think it is about expos or react natives nature, caching images. But is there a way to don't cache or clear cache on exit?

Thanks

**Comment by quinlanj** [comment]
@pabeda-bt could you provide a simple toy app example of this code?  This may be due to something that is preventing the images from being garbage collected

**Comment by terribleben** [comment]
On iOS, resources will be cached using NSURLSession's default cache mechanism, or in some cases we'll manually write them to the system Caches directory. That means you may see the storage used by the app increase over time, but the system can clear this whenever you need space. This is the same behavior used by other apps that need to cache downloaded images (e.g. Facebook, etc.)

@jesseruder can you explain how we cache images on Android?
