### ISSUE TITLE
Firestore SDK React-Native/Expo support for Android devices

### ISSUE THREAD

**Issue by Quantmatic** [expo/expo#11514]
### Summary of Issue 
Warning: "Setting a timer for a long period of time"

https://github.com/firebase/firebase-js-sdk/issues/283

Seems that this issue has reemerged. I'm running with no problems on ios, but the Android emulator takes forever to fetch firestore data. Makes the Android app unusable.

Has anyone ran into this recently?

I tried the workarounds posted in the thread above, but they did not help much. The package changed quite a bit since then.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo 40
Firebase 7.9.0
Android 10

### Reproducible Demo

Not available atm.

**Comment by AdamJNavarro** [comment]
Hey @Quantmatic, if the issue re-emerged it will need to be fixed by the maintainers of said library. We unfortunately can't provide workarounds or fixes for 3rd party libraries.

Cheers,
Adam
