### ISSUE TITLE
After detached, how to build a release android app

### ISSUE THREAD

**Issue by xiaocjin** [expo/expo#1152]
i have tried a lot, use android studio build -> Generate Signed APK, but i find the app don't contain the real code(during building, it seems that it never load the bundle) 

I‘ve tried every Host & Protocol on the Expo XDE.

Anybody can help?

**Comment by jesseruder** [comment]
Hello! Did you read this section of the guide? https://docs.expo.io/versions/latest/guides/detach.html#6-distribute-your-app

Specifically:
> If you decide to distribute your app as an ipa or apk, it will automatically hit your app’s published URL instead of your development XDE url.

**Comment by xiaocjin** [comment]
@jesseruder  you mean i should run exp publish first?

**Comment by jesseruder** [comment]
@xiaocjin yes, that's how the release version will get the code. Does it work if you do that?

**Comment by xiaocjin** [comment]
@jesseruder It woks, thanks a lot. After detach, the release Android app's icon is always the expo icon, do I have to replace it by myself?

**Comment by jesseruder** [comment]
@xiaocjin I think there's a bug with the detach icon right now. You can add a ic_launcher.png images to the `res/mipmap-*` directories to specify your own icon until we fix that script.

**Comment by bintoll** [comment]
+1 how can i get apk, it us written in doc: "If you decide to distribute your app as an ipa or apk, it will automatically hit your app’s published URL instead of your development XDE url" but i still can not understand how to get file. Could someone help me? Thanks!

**Comment by Jamongkad** [comment]
Seconded, I created a small detached app for testing purposes and I published it with this url https://expo.io/@jamongkad/Tuplefish, so how do I access my detached app from there?

**Comment by stevanus1997** [comment]
exp publish -> generate signed apk
and after that the apps always show could not load app

**Comment by KamranKhankhail** [comment]
Same is the case for me I have generated prod flavour released .apk of my expo detached project. Now app always shows could not load app.  Any solved this issue?

**Comment by s2zaman** [comment]
**Issue:**
After detaching expo; when published as a standalone app, my android release is **not reflecting new changes** but the ios standalone release is okay.
The android app is reflecting changes **only** in debug mode, in emulator or an attached device.

**Steps i follow to publish the standalone APK**

 - npm install
 - exp publish
 - react-native link
 - clean
 - build
 - sign the generated APK


**Still facing the issue !**

**Comment by s2zaman** [comment]
I was using a different expo account while publishing my app, via `exp publish`
Now my issue has been resolved :) as;
[this expo docs article](https://docs.expo.io/versions/latest/guides/advanced-expokit-topics.html#configuring-the-js-url) has helped me.

I updated the publishedUrl value in below files for android, to new ones like `exp://exp.host/@myProfileName/my-good-slug`
 - MainActivity.java
 - AppConstants.java

**Remember:** the publishedUrl value should be the one, where we are publishing the expo code via cmd-let `exp publish`
i-e i first logged in to myProfileName account
