### ISSUE TITLE
TextInput laggy / slow clear with much content on screen

### ISSUE THREAD

**Issue by andrepinkman** [expo/expo#11537]
### Summary of Issue 

I have an issue that when I spam typing in a TextInput and click a button on to submit and clear the text it becomes laggy and it doesn't clear the text in the TextInput right away. This happens when **I have a lot of content** within the Screen (like Lorem Ipsum text).

This is a problem for me, because I am developing a chat app and whenever the chat log is large and the users types and submits the message fast it won't get cleared immediately and will still remain in the TextInput, which is bad usability. I tried it with ref and controlled TextInput (no difference).

You can see the issue in my gif:
![stackk](https://user-images.githubusercontent.com/58225896/103715601-58153780-4fc1-11eb-9272-48b8fdaeb4e1.gif)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

 Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.1 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

### Reproducible Demo

https://snack.expo.io/s22hVf140

**Comment by brentvatne** [comment]
hi there,

this is a place to report bugs in expo, but this particular issue is related to [react-native](https://github.com/facebook/react-native/issues) (which is indeed an important part of expo, but a different project). 

it looks like you've gone ahead and created an issue there already for this (https://github.com/facebook/react-native/issues/30692) so i'll close this one.
