### ISSUE TITLE
Invariant violation : tried to register two views with the same name 

### ISSUE THREAD

**Issue by hizem** [expo/expo#11535]
### Summary of Issue 
I have installed the **Picker** component using `npm install @react-native-picker/picker --save`but then I discovered that the expo cli provide a cmd for installing the component using the `expo install @react-native-picker/picker`
after perform an `npm uninstall @react-native-picker/picker` and using the expo cmd an error appeared when i use the Picker component within my app **Invariant violation : tried to register two views with the same name RNCPicker ** 
The same error occurred previously with the `@react-native-community/datetimepicker` library but It was resolved when I have upgraded to the latest expo version for both the cli and the client, but now I'm using the latest one.
### Environment - output of `expo diagnostics` & the platform(s) you're targeting
![image](https://user-images.githubusercontent.com/32454249/103700382-a9fb9480-4fa4-11eb-89a5-21e8257f20c9.png)

### Reproducible Demo
![image](https://user-images.githubusercontent.com/32454249/103700228-7a4c8c80-4fa4-11eb-94df-ea8a525aa322.png)
 
### Steps to Reproduce
1. npm install @react-native-picker/picker --save
2. npm uninstall @react-native-picker/picker
3. expo install @react-native-picker/picker
4. now use the Picker component 

### Expected Behavior vs Actual Behavior
** Expected Behavior :  ** The Picker component appears within the app.
** Actual Behavior : ** Exception Invariant violation : tried to register two views with the same name RNCPicker

**Comment by brentvatne** [comment]
you have two versions of the package installed. look in your package-lock.json to see where the other is coming from

**Comment by hizem** [comment]
After checking my package-lock.json file I've noticed that the **nativebase** library uses the same package with an older version as a **transitive dependency**, so I decided to remove the actual package using `npm uninstall @react-native-picker/picker
` and move with the **nativebase** version and the problem has been solved thanks a lot :)
