### ISSUE TITLE
Our code broke: IOS

### ISSUE THREAD

**Issue by MrShakes** [expo/expo#1154]
I am successfully building for ios using `expo build:ios` however after it's uploaded I get:
"Our code broke, looks like there's an error we need to look at" here:
- https://expo.io/builds/6a724520-f691-425a-84c4-0e300a1b2113
- https://expo.io/builds/15502599-fd1a-4fba-8b15-49ddc9467b91

**Comment by brentvatne** [comment]
@MrShakes - make sure you're signed in when going to those pages. you can sign in at https://expo.io/login
