### ISSUE TITLE
Will I be able to Realm database on expo-electron?

### ISSUE THREAD

**Issue by Ngomana** [expo/expo#11545]
I've been reading around about expo and realm. I know know that expo doesn't support react native at the moment. But I want to know is will it work on expo-electron project?

**Comment by byCedric** [comment]
Hi @Ngomana, I'm not sure what you mean by "... I know that Expo doesn't support React Native at the moment ...". Expo is a framework built on top of React Native and uses React Native to run everything. Yes, not all external libraries that requires native code are supported in the managed workflow, but it does in the bare workflow.

As for Realm, as I mentioned, in a bare project you are able to use the React Native module without issues. It looks like Realm also supports NodeJS through native code. You might get that working with Electron and Expo [using this guide](https://www.electronjs.org/docs/tutorial/using-native-node-modules).

Hope this helps!
