### ISSUE TITLE
Concerns about React Native Licensing

### ISSUE THREAD

**Issue by an-kumar** [expo/expo#1155]
Thanks a lot for your work on expo. It's really a fantastic tool.

While Expo is under a normal BSD license, React Native is under Facebook's BSD+Patents license, for which there are some concerns. I was just wondering if you guys had any opinion on this situation, and if you guys think it is safe to develop commercial products on Facebook's license.

**Comment by ccheever** [comment]
Hi-

You are correct that React Native is under the BSD + Patents license.

@ide wrote up some thoughts on that license here which represent our views:
https://medium.com/@ji/the-react-license-for-founders-and-ctos-b38d2538f3e5

In general, we don't think its something to be concerned about, but there are some things you might want to think through carefully.
