### ISSUE TITLE
Native module works on Android but not on ios with EAS build

### ISSUE THREAD

**Issue by jacobworman** [expo/expo#11555]
Hi,

I work on a managed workflow and have included and imported @react-native-firebase/dynamic-links inside of my project.

It works perfectly when I build a android apk with EAS build, but when I build the same project on ios I'm stuck with splash-screen (it seems to have been a error). Later on, when I commented off the library from the project's file I then tested it again on ios the result were good and it worked, so the problem lies with the library. 

In my app.json file I have included googleServicesFile for both Android and ios.

"ios": {
      ....,
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "android": {
      .....,
      "googleServicesFile": "./google-services.json"
    }

I can't understand the problem and think this issue could be dicussed here.

**Comment by AdamJNavarro** [comment]
Hey @jacobworman, as Brent mentioned on your [Forum Post](https://forums.expo.io/t/native-module-works-on-android-but-not-on-ios-with-eas-build/47285) we don't support custom native modules in a managed project.

Cheers,
Adam
