### ISSUE TITLE
Response body is empty on Expo but available when reproduced on Node.js 

### ISSUE THREAD

**Issue by thebantz** [expo/expo#11557]
Context: I'm working on a voice recording app that uses S3 for storage and download.

Hello, I'm currently working on a download function where I fire a GET request on a button event trigger and I expect an audio stream as a response straight from S3! 

We have tested the backend. On Postman, it returns a playable audio file. Also, on Node.js, it returns the audio stream in the form of a gibberish response. 

When it comes to Expo, the same GET request we've replicated on Node, the response returns an empty body but with a status code of 200. We've tried JSON conversion methods such as stringify and parse but there really isn't anything there. 

I would like to know if Expo behaves weirdly for others when performing HTTP requests and if you have any workarounds on it? We've tried `axios` as well as `fetch` for sending the requests. 

Thank you! ☺️

**Comment by brentvatne** [comment]
please post this type of question to https://forums.expo.io unless you can fill out the issue template and believe this is a bug in expo :)
