### ISSUE TITLE
expo-facebook crash in IOS 13 - SDK 38

### ISSUE THREAD

**Issue by zapcriativo** [expo/expo#11550]
Hello, when putting the credentials of my facebook app.json in my expo project, crash when opening the app in IOS 13 standalone version, but in the same project I put credentials from another facebook app that I have, the app does not crash. What can it be?

### Expo Diagnostics 
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.10
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^3.11.1 => 3.13.0
    npmGlobalPackages:
      expo-cli: 4.0.17

**Comment by zapcriativo** [comment]
I found out that by activating the marketing APi on facebook developers, do you know what I can do to get around?

![image](https://user-images.githubusercontent.com/7153803/103808429-ba5c4f80-5036-11eb-8d47-8bf2f9a7b546.png)

**Comment by cruzach** [comment]
hi! I recommend looking through the device logs (for iOS, just hook up your device to your mac and open the Console app) for more information. A project crashing doesn't necessarily mean it's a bug with Expo, so I'm going to close this issue for now- but if you can provide a reproducible demo that shows this is an issue with `expo-facebook` that we can fix, I can reopen the issue 😄  thanks!

Here's a more detailed guide to debugging with Expo- https://docs.expo.io/workflow/debugging/

**Comment by zapcriativo** [comment]
I created new app on facebook developers and it's worked, but not registered log events from android

**Comment by zapcriativo** [comment]
Hi, I disable this option and the standalone IOS App is stoping crash for me 

![Captura de Tela 2021-04-13 às 11 56 08](https://user-images.githubusercontent.com/7153803/114574096-535ec000-9c4f-11eb-9302-f0fda8d3dbdd.png)
