### ISSUE TITLE
Exception thrown expo-contacts

### ISSUE THREAD

**Issue by slauzinho** [expo/expo#11556]
### Summary of Issue 
While trying to add a contact, iOS throws an exception:
```
error: An exception was thrown while calling `ExpoContacts.addContactAsync` with arguments `(
        {
        firstName = John;
        lastName = Doe;
        phoneNumbers = "+44123456789";
    },
    "<null>"
)`: -[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x2825fe460
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
iOS real device

### Steps to Reproduce
Using the [docs](https://docs.expo.io/versions/latest/sdk/contacts/#contactsaddcontactasynccontact-containerid) example of code:
```javascript
const contact = {
      [Contacts.Fields.FirstName]: 'John',
      [Contacts.Fields.LastName]: 'Doe',
      [Contacts.Fields.PhoneNumbers]: '+44 123456789',
    };
await Contacts.addContactAsync(contact);
```

### Expected Behavior vs Actual Behavior
It should prompt the native contact form for iOS but it crashes

**Comment by cruzach** [comment]
Please include all the information we ask for, especially your SDK version and `expo-contacts` version. Here's a snack that uses that code, I tested it on an iOS device and it worked properly- https://snack.expo.io/@chuckaroo/basic-contacts-usage

**Comment by slauzinho** [comment]
I'm using it in a bare workflow.

```
"expo-constants": "^9.2.0",
"expo-contacts": "^8.6.0",
```

**Comment by brentvatne** [comment]
works as expected, you just didn't provide the data in the correct format as per the docs - the phone numbers field is a `PhoneNumber[]` and not a `string`, so `[{number: '+44123456789}]` - https://github.com/brentvatne/contactsy

also added an example that opens the form for the contact that you create. please refer to docs in the future - https://docs.expo.io/versions/latest/sdk/contacts/#contactspresentformasynccontactid-contact-formoptions
