### ISSUE TITLE
image picker permissions on Android

### ISSUE THREAD

**Issue by miroslavskela** [expo/expo#11564]
Expo sdk 40, Android 11, App in production.
Hello, recently I added expo-image-picker package to my app, where I want to select photo from phone or to take photo directly from app. It works fine in expo cli, but when i published changes to production app it does not work, it just says that permissions are denied, even if I check allow when asks me. In app.json, permissions I have CAMERA, permission, do I need some more permissions like READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE for example to make it work? 
On ios I did same, and published it, and it works fine.
Thanks.

**Comment by ipakhomov** [comment]
@miroslavskela I've faced the same problem. Setting the following permissions in the `android.permissions` in `app.json` helped:
```json
permissions: ["CAMERA", "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE"],
```
Though, the [docs say](https://github.com/expo/expo/tree/sdk-40/packages/expo-image-picker#configure-for-android) that these permissions are configured by default.

**Comment by miroslavskela** [comment]
Thanks, i assumed this could be a problem, so i build new version with those permissions, and now I'm waiting for review. If this helps me too, than it would be good to add this to documentation.

**Comment by miroslavskela** [comment]
Hi, just to let you know, setting "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE" in permissions, and with new upload to play store, this works now. 
Thanks @ipakhomov .

**Comment by stdavis** [comment]
This is a bug or the docs need to be updated, right?

**Comment by NikkiDelRosso** [comment]
This seems to still be an issue. There is not specific documentation indicating I need this (just "camera roll permissions").

**Comment by wiltonzanin** [comment]
This is still be an issue, but the @ipakhomov solution works fine.

**Comment by TomasSestak** [comment]
Still issue @byCedric - could the docs be updated please? https://docs.expo.dev/versions/latest/sdk/imagepicker/#android
