### ISSUE TITLE
[expo-local-authentication]How to set fallback for android if a user doesn't have any fingerprints registered / or failed attempts?

### ISSUE THREAD

**Issue by Yandamuri** [expo/expo#11569]
How to set fallback for android if a user doesn't have any fingerprints registered / or failed attempts?

**Comment by AdamJNavarro** [comment]
Hey @Yandamuri, for questions such as this one, please direct them to our [Forums](forums.expo.io)! We try our best to reserve Github issues for reproducible and actionable bug reports.

Cheers,
Adam
