### ISSUE TITLE
Expo Video completely unresponsive in fullscreen mode

### ISSUE THREAD

**Issue by YeetOrBeYate** [expo/expo#11572]
## 🐛 Bug Report
"expo": "^40.0.0",
"expo-av": "~8.7.0",
### Summary of Issue 
I have a custom button that puts the video in full screen mode, but as soon as it displays the video freezes while the audio plays in the background. I've commented all other functions interacting with the video ref, and it still glitches out.

### Reproducible Demo
        `<Video

          ref={playbackInstance}

          source={{ uri: media.url }}

          rate={1.0}

          volume={1.0}

          isMuted={false}

          resizeMode="cover"

          shouldPlay

          isLooping

          style={styles.video}

          onPlaybackStatusUpdate={videoPlayBackStatus}

          onFullscreenUpdate={fullScreenPlayBackStatus}

        />`

`  const presentFullScreen = () => {
    try {
      playbackInstance.current.presentFullscreenPlayer();
    } catch (error) {
      console.log('error', error);
    }
  };`

**Comment by AdamJNavarro** [comment]
Hey @YeetOrBeYate, please provide an accessible and actual reproducible example of the behavior. Incomplete code snippets won't help us debug the issue. Additionally, please provide the platform(s), version(s) the issue occurs on. Once you provide the things mentioned above, we'll gladly re-open and discuss.

Cheers,
Adam
