### ISSUE TITLE
Last version iOS Expo Client bugs (This experience uses an unsupported version of Expo (SDK 17.0.0))

### ISSUE THREAD

**Issue by Shaita-KrZ** [expo/expo#1157]
Hi here !

Since I have installed the last version of Expo Client (iOS) on my iphone (same on simulator). I can't launch my expo app anymore. I'm getting this error :

`Error: This experience uses an unsupported version of Expo (SDK 17.0.0). You may need to update Expo Client on your device`

With the older versions, it was working fine. 

I was using the expo SDK version 17.0.0, but even after upgrading to the latest version (23.0.0 I think), I got the same issue.
I also tried to upgrade react native.

**Comment by brentvatne** [comment]
hello! you need to change the sdkVersion in your app.json and re-open the app

**Comment by bnjm** [comment]
Also running into this. What should the sdkVersion be changed to if it was already 23.0.0? 22.0.0 seems to cause a react-native mismatch error as it doesn't support react-native 0.50.0

**Comment by jesseruder** [comment]
@bnjm you have to do a few other steps in addition to changing the sdkVersion. Follow the upgrade guide at the end of any of the release notes: https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51

**Comment by terribleben** [comment]
Let us know if you're still having trouble after following all of the upgrade steps in the blog post that Jesse pasted. Sorry this was confusing, we'll work on making it easier to upgrade in the future.
