### ISSUE TITLE
[docs] Documentation expo-av links to an example which uses Expo SDK v15.0.0. 

### ISSUE THREAD

**Issue by ApayRus** [expo/expo#11576]
Hi! I'm triying to use ['expo-av' ](https://docs.expo.io/versions/latest/sdk/audio/) and at the beginning of docs there is [a paragraph with example](https://expo.io/@documentation/projects/playlist-example). But when I open it to see how it works, there is a message: `This project needs an update
This project uses Expo SDK v15.0.0. If you want to open this project, the author will need to update the project's SDK version.`

Is it normal? Should I seek for an ancient expo and install it? Or should I report about bug in docs?

**Comment by AdamJNavarro** [comment]
Hey @Aparus, don't go about trying to find a way to run an expo project running SDK15. The publish project has not been updated but the link to the source code is running SDK34. While that is still not as updated as we would like it to be and it is out of the support cycle, the AV modules have largely remained the same except for bug fixes so the code should still be applicable. We'll get the docs updated as soon as we can.

Cheers,
Adam
