### ISSUE TITLE
Expo 40 - 'Check the render method of ExpoRoot' Error

### ISSUE THREAD

**Issue by tcagkansokmen** [expo/expo#11575]
Hi there

I upgraded to expo sdk 40. And got error below:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ExpoRoot`.
```

My /App.js file:
```
import { registerRootComponent } from 'expo'
import App from './src/App'

registerRootComponent(App)

```

My ./src/App.js
```
import 'react-native-gesture-handler'
import React from 'react'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/lib/integration/react'
import { store, persistor } from '@/Store'
import { SafeAreaView, StatusBar, Text } from 'react-native'
import { NavigationContainer } from '@react-navigation/native'
import { ApplicationNavigator } from '@/Navigators'
import { navigationRef } from '@/Navigators/Root'
import { Layout } from '@/Theme'
import './Translations'

import { useDispatch } from 'react-redux'
import * as Sentry from 'sentry-expo'

const App = (props) => (
  <Provider store={store}>
    {/**
     * PersistGate delays the rendering of the app's UI until the persisted state has been retrieved
     * and saved to redux.
     * The `loading` prop can be `null` or any react instance to show during loading (e.g. a splash screen),
     * for example `loading={<SplashScreen />}`.
     * @see https://github.com/rt2zz/redux-persist/blob/master/docs/PersistGate.md
     */}
    <PersistGate loading={null} persistor={persistor}>
      <NavigationContainer ref={navigationRef}>
        <StatusBar barStyle="light-content" backgroundColor="#3b7a99" />
        <ApplicationNavigator />
      </NavigationContainer>
    </PersistGate>
  </Provider>
)

export default App
```

**Comment by brentvatne** [comment]
as the error message suggests, you are rendering something that you think is a component but is actually an object.

```
const MyComponent = {};

const App = () => {
  return <MyComponent />
}
```

so, check to make sure that everything you are rendering is imported/exported correctly

**Comment by SavedThunder** [comment]
This issue was closed but was there any reasoning as to why the error was around the render method of ExpoRoot? Running into the same problem

**Comment by brentvatne** [comment]
ExpoRoot is the root component. your app is rendered as a child of it

**Comment by mehrdadabdi** [comment]
I had this issue and I fixed it by modifying the file /Users/myname/dir.../dirprojectname/node_modules/expo/AppEntry.js

line import App from '../../src/index'; used to be import App from '../../App'; 
this error came up when I aded src dir and added the file index.js

**Comment by zanele24** [comment]
i am encountering the same error. Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ExpoRoot`.

This error is located at:
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

my code 
import { NavigationContainer } from "@react-navigation/native";
import {Tabs} from "./src/navigation/tabs";
import {React} from 'react';

const App = () =>{
  return(
    <NavigationContainer>
      <Tabs/>
    </NavigationContainer>
  );
}
export default App();

How i do solve it?

**Comment by fabqc10** [comment]
try to declare your App component like i did below , i had the same problem and it worked for me @zanele24 

export default function App() {
  // your code
}

**Comment by MEDSAM2412** [comment]
> export default function

thanku this help me alot
