### ISSUE TITLE
[docs] Admob page testing section spelling error in example

### ISSUE THREAD

**Issue by julste** [expo/expo#11578]
I just copied the testing section from admob [page](https://docs.expo.io/versions/latest/sdk/admob/) to my code:

```
import Constants from 'expo-constants';

const testID = 'google-test-id';
const productionID = 'my-id';
// Is a real device and running in production.
const adUnitID = Constants.isDevice && !__DEV__ ? productionId : testID;
```

The const productionID is misspelled in the const adUnitID. Needs to be a capital D.

**Comment by AdamJNavarro** [comment]
Hey @julste, I'm going to close this issue in favor of your other one.

Cheers,
Adam
