### ISSUE TITLE
AuthSession with Google does not work in standalone if responseType: "id_token",

### ISSUE THREAD

**Issue by PPjev** [expo/expo#11581]
## 🐛 Bug Report

Trying to authorize with Google SignIn by using Google from "expo-auth-session/providers/google";
I need to get specific response type which is id_token. In expo it works, Google returns all I need, but in Standalone, Google thorough an error that such response type is unsupported. If I omit this property, all works fine, but I don't get id_token, so does not help me.

Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

 
### Steps to Reproduce

Every time you add responseType parameter to Google auth, it will through an error for unsupported response typer during the WebBrowser authorization, before even asking for an email. Will work in Expo though ...

### Expected Behavior vs Actual Behavior

I expect it to return id_token instead of authoriztion_token. Which it does in Expo, Google accepts this parameter, and returns what I want. But in standalone on both Android and iOS, it does not work.

**Comment by dorapax-lab** [comment]
Do we have any workaround for this ?

**Comment by arthurherbert** [comment]
I have the same problem @dorapax-lab, have you found a workaround for this?

**Comment by NickCastillo** [comment]
Hi! Something that seems to have worked for me (so far) was switching the method `useAuthRequest` for `useIdTokenAuthRequest`

**Comment by Traviskn** [comment]
@NickCastillo's solution worked for me. In the docs they only show `useIdTokenAuthRequest` for use with firebase, but it works with all the same arguments as the normal `useAuthRequest` method

**Comment by tonicprism** [comment]
Also 

> Hi! Something that seems to have worked for me (so far) was switching the method `useAuthRequest` for `useIdTokenAuthRequest`

Also worked to me!
