### ISSUE TITLE
[docs] Install Section for AppLoading is empty

### ISSUE THREAD

**Issue by hardfire** [expo/expo#11582]
Installation section for AppLoading (https://docs.expo.io/versions/v40.0.0/sdk/app-loading/#installation) is empty.
![image](https://user-images.githubusercontent.com/513457/104104410-1988c100-52d0-11eb-855b-c06981f05c23.png)

**Comment by byCedric** [comment]
Thanks for mentioning this! I opened a PR to include it, once that passes I'll merge and deploy it.

**Comment by hardfire** [comment]
Perfect! didn't realize that it was failing because of the missing import.
