### ISSUE TITLE
Android: There was an error with this build.

### ISSUE THREAD

**Issue by radi-cho** [expo/expo#1158]
When I try to build my project:
```
[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: 4283c5c1-7743-44fc-94bb-9e1113b166f5
[exp] Run `exp build:status` to monitor it.
```
```
[exp] Android: There was an error with this build.
```

**UPDATE:**
_This isn't bug with Expo, Expo CLI or Expo XDE, but I need the logs (of my build) from your build server. That's why I opened this feature request #1159_ 

### Please help me! Build ID: `4283c5c1-7743-44fc-94bb-9e1113b166f5`

**Comment by brentvatne** [comment]
hi there, go to https://expo.io/builds/4283c5c1-7743-44fc-94bb-9e1113b166f5 for more information about the build. latest version of `exp` will link you there

**Comment by radi-cho** [comment]
Thanks! Sorry, but I worked with exp 44, I'm going to update it...
