### ISSUE TITLE
Native Ad support for Admob library

### ISSUE THREAD

**Issue by AbdnhVmpr** [expo/expo#11589]
Please add native ads support for Admob.  I am aware that the Facebook network library has support for native ads, but I have not seen anything for the Admob library.
PLEASE ADD IT IT'S REALLY USEFUL!

**Comment by byCedric** [comment]
Hi @ AbdnhVmpr! Thanks for writing in, but unfortunately we don't handle feature requests through Github. The best thing you can do is create a small post on [our feature request tracker](https://expo.canny.io) and provide a short use case of why or how you want to use the native admob library (and the benefits over the current one).

Hope this helps!
