### ISSUE TITLE
"Clicky" haptics

### ISSUE THREAD

**Issue by samuelcelko** [expo/expo#11584]
Hi there, I've been trying to use `expo-haptics` to invoke a **CLICKY** (for lack of a better term) type of haptics that are present for instance in Google Pixel phones but have only been able to invoke a **VIBRATION** type of haptics which seems quite outdated by today's standards. 

expo haptics - https://docs.expo.io/versions/latest/sdk/haptics/

Does anyone know of a way of doing this?
Cheers!

**Comment by brentvatne** [comment]
hi there. we use this api on android: https://developer.android.com/reference/android/os/Vibrator
