### ISSUE TITLE
Error: Cross-Site request verification failed. Cached state and returned state do not match":  Expo/Spotify Authorization using Expo's "useAuthRequest"

### ISSUE THREAD

**Issue by Nfinley** [expo/expo#11592]
### Summary of Issue 
I am trying to authenticate a user via Spotify using the `useAuthRequest` flow as outline in the [docs](https://docs.expo.io/guides/authentication/#spotify) and via @brentvatne repo mentioned [here](https://github.com/expo/expo/issues/10514#issuecomment-719821735) but I am only receiving the authorization code from Spotify when on localhost. When on higher environments I receive a `Cross-Site request verification failed` error.

Given that it is a cross site error, could there be an issue with my aws hosting configuration? 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  ```Expo CLI 4.0.17 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 23, 28
        Build Tools: 25.0.0, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.45 => 0.12.52 
      expo: ^39.0.2 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed
```

I am also using AWS Amplify to host my dev environment

### Reproducible Demo
Below is the main function I am using to trigger the pop window to authorize the user via Spotify and obtain the authorization code. I am hard coding the redirect url right now.

```
import { useEffect, useState } from 'react';
import { Platform } from 'react-native';
import { useAuthRequest } from 'expo-auth-session';
import * as WebBrowser from 'expo-web-browser';
import { fetchTokenAsync } from '../api/spotify';
import * as LocalStorage from '../lib/LocalStorage';

const discovery = {
  authorizationEndpoint: 'https://accounts.spotify.com/authorize',
  tokenEndpoint: 'https://accounts.spotify.com/api/token',
};
const scopes = [
  'user-modify-playback-state',
  'user-library-modify',
  'user-library-read',
  'user-read-recently-played',
  'user-top-read',
  'user-follow-modify',
  'streaming',
  'user-read-email',
  'user-read-private',
  'user-follow-read',
];
const REDIRECT_URI = 'http://localhost:19006/Fan/Listen/Discover';
// REDIRECT_URI FOR UPPER ENV's
// const REDIRECT_URI =
//   'https://<amplifycode>.amplifyapp.com/Fan/Listen/Discover';
const CLIENT_ID = '<MyClientID>';
const stateKey = 'some_state_key';
WebBrowser.maybeCompleteAuthSession();

export default function useSpotifyAuth() {
  const [error, setError] = useState<any | null>(null);
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(false);

  const [authRequest, authResponse, promptAsync] = useAuthRequest(
    {
      clientId: CLIENT_ID,
      usePKCE: false,
      scopes,
      state: stateKey,
      redirectUri: REDIRECT_URI,
      extraParams: {
        // On Android it will just skip right past sign in otherwise
        show_dialog: 'true',
      },
    },
    discovery,
  );

  useEffect(() => {
    async function updateFromAuthResponseAsync() {
      if (authResponse === null) {
        return;
      } else if (authResponse.type === 'error') {
        console.error('ERROR in spotify hook: ', authResponse); 
        setError(authResponse.error);
        return;
      } else if (authResponse.type === 'success') {
        const result = await fetchTokenAsync(
          authResponse.params.code,
          REDIRECT_URI,
        );
        if (result.error || !result.token) {
          setError(result.error ?? 'Unknown error');
        } else {
          console.log('RESULT: ', result);
          await LocalStorage.setAuthCredentialsAsync({
            ...result,
            lastRefreshed: new Date(),
          });
          setIsAuthenticated(true);
        }
      }
    }

    if (!isAuthenticated) {
      updateFromAuthResponseAsync();
    }
  }, [authResponse]);

  return {
    error,
    isAuthenticated,
    authenticateAsync: () => promptAsync({ useProxy: false }),
  };
}
```
When stepping through the  Expo`AuthRequest.ts` file the `state` and `code` params are not coming through on the url in the `parseReturnUrl` function (see image below) which is why I get the Cross-Site Error. But why is the `code` and `state` not being returned as params on a higher env? 

![parseReturnUrlFunction](https://res.cloudinary.com/thefinleycode/image/upload/v1610339369/Screen_Shot_2021-01-10_at_8.26.57_PM_awu2pl.png)

### Steps to Reproduce

1. Implement the useAuthRequest flow on web for Spotify
2. Deploy to a dev environment
3. Authentication to Spotify works on localhost but doesn't work on a dev/hosted environment

### Expected Behavior vs Actual Behavior
Expected: The useAuthRequest function to authorize a user via Spotify retrieves a code for token exchange in both localhost and dev environments
Actual:  The useAuthRequest function only works on localhost and on dev it throws the error: `Error: Cross-Site request verification failed. Cached state and returned state do not match`

**Comment by brentvatne** [comment]
this isn't a bug in expo-auth-session, as demonstrated in the repo you referred to it works as expected. 

it sounds like you are using expo web?

why are you passing in your own state key?

**Comment by Nfinley** [comment]
> it sounds like you are using expo web? why are you passing in your own state key? have you verified that it is being send along as expected in the auth url?
> 


Thanks @brentvatne for your response. I am using expo web and I don't have a strong reason for passing a state key given its optional. Regarding the auth url everything is being sent along locally and in a dev env its just in the response where the redirect uri loses its `params`. 

Apologies for posting this in the bug section, I will post any additional inquires to the forums section

**Comment by sealabcore** [comment]
This is specifically an AWS Amplify issue. You need to add a rewrite / redirect in AWS Amplify app settings. `/auth` is the path our app uses. Your path may be different based on your auth flow.

The issue is that AWS Amplify strips all the params with that 404 rewrite so you need to allow the redirect to not have the params stripped.

<img width="805" alt="Screen Shot 2021-11-17 at 11 48 09 AM" src="https://user-images.githubusercontent.com/79464/142272670-9170d4db-62ec-4438-b2c3-8a6a48241d74.png">
