### ISSUE TITLE
[expo-notification] Push data wont open in app (Android/Firebase FCM)

### ISSUE THREAD

**Issue by ijro** [expo/expo#11596]
### Summary of Issue 
Sending Push with Firebase only with DATA d'ont deliver. Sending Puth with Data and Notification wont open details in app.
I'm trying to follow "Firebase Notification Types" present in [https://docs.expo.io/push-notifications/sending-notifications-custom/ ](https://docs.expo.io/push-notifications/sending-notifications-custom/ )with no success.

### Environment 
Tried:
"expo-notifications": "0.7.2"
"expo-notifications": "0.8.2",
"expo-notifications": "0.5.0",

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

Platform target: Android
### Reproducible Demo

Server side:

```
var admin = require("firebase-admin");

var serviceAccount = require("./firebaseFile.json");

admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
});

const devicePushToken = "fr_SKPL9Qdu_sYJ1JHRz8e:APA91...";

var payload =
    {
        data: {
            title: 'TEST up 1.43% on the day',
            body: '{stock: \'GOOG\', open: \'829.62\', close: \'635.67\''
        }
    };

var options = {
    priority: 'high',
    timeToLive: 60 * 60 * 24
};


admin.messaging().sendToDevice(devicePushToken, payload,options)
    .then(function(response) {
        console.log('Successfully sent message:', response);
    })
    .catch(function(error) {
        console.log('Error sending message:', error);
    });
```

At client side I use addNotificationResponseReceivedListener
https://docs.expo.io/versions/latest/sdk/notifications/
 
### Steps to Reproduce
Try to send a data push notification through FCM and open (and read data) it in client side with the app closed.

### Expected Behavior vs Actual Behavior
My expectation was to read the data (key / value) on android as I already read correctly on IOS

**Comment by cruzach** [comment]
You are not including your `experienceId` in the payload, and as the [docs](https://docs.expo.io/push-notifications/sending-notifications-custom/#android) state:
> The experienceId field is required, otherwise your notifications will not go through to your app.

**Comment by ijro** [comment]
cruzach, you were amazing! Thank you! That was it. The documentation did not include this in the FCM part and had not tried. Thanks!

**Comment by cruzach** [comment]
Not sure what you mean @ijro , it _is_ included in the documentation (see my link above)

**Comment by ijro** [comment]
I was consulting https://docs.expo.io/push-notifications/sending-notifications-custom/#firebase-notification-types 
I was consulting Firebase  Notification Types that has no experienceId and it took me a while to see that experienceId was mandatory (I only saw it after your help).
