### ISSUE TITLE
Unable to open Expo menu after failing to connect to debugger

### ISSUE THREAD

**Issue by jojenki** [expo/expo#11598]
I've never setup a debugger for my app when running on my Android device (tried and can't figure it out). That's acceptable for now, since I've just been using Android for look-and-feel. Today, I opened the Expo menu within my app and accidentally clicked "Debug Remote JS". Of course, this always fails because I don't have a debugger setup.

Now, whenever I open my app on my Android device it gives me the failure screen with the big red bar at the top saying "Failed to connect to debugger!". The only options I have are "DISMISS" and "RELOAD". If I RELOAD, it kills the app and restarts it, and takes me back to the "Failed to connect to debugger!" page. If I DISMISS, it closes the warning page and then just hangs on the app loading screen. It never actually loads the app.

The most frustrating part (and the real bug here) is that I can't bring up the context menu to tell it to stop trying to connect a debugger or tell Expo to forget my settings for this app. Expo effectively locks me out of the app because of the failure to connect to the debugger. The only "fix" I've found for this is to go into Android's Settings and Clear Cache and Clear Storage for the Expo app, which also logs me out. Instead, the Expo app should let me change the settings like connecting to the debugger before I actually launch the app.

**Comment by brentvatne** [comment]
> Of course, this always fails because I don't have a debugger setup.

this shouldn't be the case - it should open up chrome to start the debugger.

> The most frustrating part (and the real bug here) is that I can't bring up the context menu to tell it to stop trying to connect a debugger or tell Expo to forget my settings for this app.

yeah that's very annoying, sorry about that

**Comment by jojenki** [comment]
Thanks for the quick response. Where should it open the Chrome window, on the Android device where the app is being launched or on my desktop where I'm doing development? Maybe I need to already have a Chrome window open on my desktop? (My default browser is actually Firefox.) I'll take another pass through the setup. Thanks!

**Comment by chuanxie** [comment]
i would say sdk 40 is the worst upgrade of expo. 
so many things stop working

**Comment by jojenki** [comment]
Well, if this is the worst upgrade, then the product is in a pretty great state. This is my first experience with it, and I am extremely pleased.

**Comment by brentvatne** [comment]
@chuanxie - that is strange, because we didn't update the react-native version and most of the changes were bug fixes and feature improvements. perhaps there are some other underlying issues in your app? if you want to share your app with me on github i can investigate. i strongly suspect it's not actually related to anything we did

**Comment by brentvatne** [comment]
> Thanks for the quick response. Where should it open the Chrome window, on the Android device where the app is being launched or on my desktop where I'm doing development? Maybe I need to already have a Chrome window open on my desktop? (My default browser is actually Firefox.) I'll take another pass through the setup. Thanks!

it would open chrome on your computer (or i believe it will fall back to firefox if you use that by default, but i am not entirely sure).

**Comment by chuanxie** [comment]
@brentvatne. i created a branch for `sdk40` upgrade and react native debugger stopped working (waiting for react to connect), deleted `yarn lock` and `node_modules`, checkout the `sdk39`  and ran `yarn install`. react native debugger starts working again.
i even tested with react native debugger with brand new expo init  and same issue with react native debugger. https://github.com/chuanxie/sdk40

**Comment by brentvatne** [comment]
we lean on react-native's built in debugging, and so any problems that occur there also occur in expo projects. sadly this is an upstream react-native issue: https://github.com/facebook/react-native/issues/28844

we have already worked on a fix for one of the possible causes (related to caching), @satya164 released a fix for it here: https://github.com/react-native-community/cli/pull/1307

he has also encountered a similar issue to what you mentioned above, and he said that it's just a warning and debugging continues to work. he is investigating it though.

**Comment by jojenki** [comment]
Ah, the upstream issue seems to be the same issue that I've always experienced (as a new user). I've never been able to get debugging working on a device, emulator, or web, and I suspect that's the root cause. I've subscribed to it, so this issue can either track that one or be closed in lieu of it, as far as I'm concerned. Thanks!

**Comment by chuanxie** [comment]
@brentvatne 
RN debugger problem solved after running brew upgrade like python and also watchman
maybe need to notice those dependencies for the future expo updates

**Comment by AlanSl** [comment]
>> The most frustrating part (and the real bug here) is that I can't bring up the context menu to tell it to stop trying to connect a debugger or tell Expo to forget my settings for this app.
>
> yeah that's very annoying, sorry about that

@brentvatne This seems to still happen, so I don't think this issue should be closed.

I just did exactly the same thing as the original question: I accidentally turned on remote debugging on an app where I don't expect it to work (in my case it uses turbomodules / reanimated); and now I'm stuck because Expo has remembered my "preference", there's no way to change it outside of the developer shake-menu of the app (that I can see), but the app instantly crashes with this error before I can access the developer menu to try to turn it off again.

Is there any workaround for this?

(Longer-term, it'd be nice if there was an option in Expo app settings, or if you could access the developer menu of an app before opening it by long-pressing it in the Expo list)

**Comment by anti-duhring** [comment]
> I just did exactly the same thing as the original question: I accidentally turned on remote debugging on an app where I don't expect remote debugging to work (in my case it uses turbomodules / reanimated); and now I'm stuck because Expo has remembered my "preference", there's no way to change it outside of the developer shake-menu of the app (that I can see), but the app instantly crashes with this error before I can access the developer menu to try to turn it off again.

Got the same error here... There's any solution?

**Comment by jpschw** [comment]
We can't access our application anymore in the Android simulator because of this bug. There is no way to bring up the menu after an error has occurred.

**Comment by DmitriyOpletaev** [comment]
I also faced this, it's terrible. Can you fix it?

**Comment by audoh** [comment]
Issue still seems to be present, tried getting the debugger to work as an alternative to reinstalling the app but no luck.

**Comment by admehta01** [comment]
Happening for me too, only workaround is to uninstall and re-install my development build.

**Comment by soulfresh** [comment]
Same issue here
