### ISSUE TITLE
[Feature request] Show the build logs to the users.

### ISSUE THREAD

**Issue by radi-cho** [expo/expo#1159]
## Is this _feature request_ or _bug report_?
Feature request

## Description
When someone try to build an `apk` or `ipa` file there are few steps... After successfully built and uploaded bundles, the user need to run `exp build:status` to find `apk` (`ipa`) file or view the current build status.
If everything is completed successful he/she can find installation files (_apk_ or _ipa_).
But in the most cases if there was a problem/s the user can only see:
```
[exp] Android: There was an error with this build.
```
```
[exp] iOS: There was an error with this build.
```

## Expected behavior
I suggest when there are problems to show more detailed information. This'll help the users to remove the problems and build their apps as well.

## Examples for different errors, that can help users without need to open issues on Github and contact the Expo team
```
No signing certificate for iOS found
```
```
APT err(Facade for 1364583577) : No Delegate set : lost message:libpng error: Not a PNG file
```
```
No valid iOS Distribution signing identities belonging to team YOUR_TEAM_ID were found.
```
ect.

**Comment by brentvatne** [comment]
hello. update to the latest version of exp and you can see the logs. see this blog post about it: https://blog.expo.io/introducing-support-for-build-dashboards-apple-two-factor-authentication-81d288a3d03

**Comment by radi-cho** [comment]
Great.
