### ISSUE TITLE
Apple Pay - is it on the roadmap?

### ISSUE THREAD

**Issue by KidkArolis** [expo/expo#116]
It seems like I could use Stripe's REST API to handle payments in an Expo app. But for something like Apple Pay - an SDK support would be required. Is that on the roadmap in any shape or form?

**Comment by ccheever** [comment]
Yes. It's on our roadmap. It might be a bit tricky to make it work across multiple apps but we think we can figure something out. We don't have a timeline yet but it's a very common request and near the top of our list.

**Comment by dikaiosune** [comment]
Hi! We're moving feature requests to Canny, so I [created one there](https://expo.canny.io/feature-requests/p/apple-pay) for this. We have other Payment API work in progress through Stripe, but we also are hoping to provide Apple and Android pay at some point in the future.

**Comment by bielcapanema** [comment]
any updates on this?

**Comment by Dygerati** [comment]
Also wondering, is there anywhere we can look to see that status here? 
Via the docs: 

> We’re still excited to give developers a way to let users pay for goods when they need to and we’ll announce ways to do so shortly.

Thanks! :)

**Comment by arrygoo** [comment]
Any updates on the status of this feature? Any hope it will be in Expo 24?

**Comment by jsappme** [comment]
any updates on this very useful feature?

**Comment by ide** [comment]
There are no status updates on Apple Pay in Expo at this time (early 2018).

**Comment by alanlanglois** [comment]
@ide I need to include inapps / subscriptions on Android & iOS in my app very soon. I'm thinking about detaching to ExpoKit, but if you tell me it's something you are working on it and that it will be released in the next days/weeks I'll reconcider doing it now and wait for this feature to be released :)

**Comment by ide** [comment]
You should detach if timeliness is important to you. We aren't working on Apple Pay right now.

**Comment by isaachinman** [comment]
@KidkArolis Did you find a way to accept Stripe payments cross-platform without detaching?

**Comment by nicolasconnault** [comment]
@ide  Any update on this? I need to know if there's any hope of this being implemented within the next 3-4 months.

Thanks!

**Comment by ide** [comment]
Some payments work landed in this commit here: https://github.com/expo/expo/commit/db974ba46cd428182bd51474fefcdda9dbe366d2. Please refer to the code to see if it meets your needs and if so, you will be able to use the module with ExpoKit.

**Comment by nicolasconnault** [comment]
Thanks @ide, that's awesome! What's the best way to update my expo to this version, I assume it's not the latest stable build?

**Comment by ide** [comment]
The code is in a module for an unreleased version of Expo. Due to the nature of the module (Apple asks that apps actually use payments if they include payments code) it may not be included in the Expo Client from the App Store but you can use the module with ExpoKit. There are some notes on upgrading here: https://docs.expo.io/versions/latest/workflow/upgrading-expo
