### ISSUE TITLE
babel.config.js configure plugin: babel-plugin-module-resolver does not work

### ISSUE THREAD

**Issue by seenyea** [expo/expo#11602]
Dev Environment:
macOS Big Sur version 11.1 (20C69)
expo-cil: 4.0.17
node: 15.5.1
npm: 7.3.0
react-native-cli: 2.0.1

Problem:
My babel.config.js:

```
const path = require('path');

module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      ['module-resolver', {
        root: ["./"],
        alias: {
          '@h5': path.resolve(__dirname, './components/src/h5/'),
          '@static': path.resolve(__dirname, './components/static/css/'),
          '@project': path.resolve(__dirname, './components/project'),
          '@libs': path.resolve(__dirname, './components/libs'),
          '@store': path.resolve(__dirname, './components/store')
        }
      }],
    ],
  };
};
```
My RN Structure:

![image](https://user-images.githubusercontent.com/46433320/104270977-b156fc80-54d4-11eb-82c8-f52eeee1e965.png)

My Problem:
![image](https://user-images.githubusercontent.com/46433320/104271171-2b878100-54d5-11eb-8870-919839014036.png)
ERROR
Building JavaScript bundle: error
ERROR
Unable to resolve "@store" from "components/src/h5/project/todo/app.js"

**Comment by brentvatne** [comment]
this isn't a bug with expo, if you have some problem with configuring a babel plugin then please either post to https://forums.expo.io or on a babel help forum. 

also, make sure you clear the metro / babel cache after changing babel config. a shortcut to do that is `expo start -c`
