### ISSUE TITLE
Video recording doesn’t work on Xiaomi 8 Lite

### ISSUE THREAD

**Issue by asmailov** [expo/expo#11603]
### Summary of Issue 
I have an issue when recording video using ImagePicker API: [ImagePicker - Expo Documentation](https://docs.expo.io/versions/latest/sdk/imagepicker/#imagepickerlaunchcameraasyncoptions)
When launching a camera with media type selected as Videos the Camera app is opened and I can click to record. However, when I do click record a beep is heard (as if the video recording had started) but the UI doesn’t transition into the “recording” state - essentially nothing happens.

### Environment
SDK Version: 40
Platforms: Android
Device: Xiaomi 8 Lite

### More info
I think another person had the same issue already with Xiaomi 8 Pro and it was not resolved ([expo-camera recordAsync recordasync does not work on Xiaomi Mi 8 Pro](https://forums.expo.io/t/expo-camera-recordasync-recordasync-does-not-work-on-xiaomi-mi-8-pro/41827))

**Comment by lukmccall** [comment]
Could you provide logs from your device?
