### ISSUE TITLE
[Unhandled promise rejection: Error: TypeError: Network request failed]

### ISSUE THREAD

**Issue by keomalima** [expo/expo#11608]
### Summary of Issue 

I'm trying to upload a picture with me app but every time I get this error. It works when I try on the web, but not on my physical device. I checked [https://github.com/expo/expo/issues/9098] but I was wondering, why it would work in the web and not on my physical device. 

### Reproducible Demo

```
const takeImage = async () => {
    const hasPermission = await verifyPermissions();
    if (!hasPermission) {
      return;
    }
    let result = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
    });

    if (!result.cancelled) {
      setImage(result.uri);
      uploadImage(result);
    }
  };

  const uploadImage = async (result) => {
    try {
      const response = await fetch(result.uri);
      const blob = await response.blob();

      let formData = new FormData();

      formData.append('file', blob, 'keo.jpg');
      formData.append('idAtendimento', 88);

      const fetchResponse = await fetch(
        'https://api.flow2.com.br/arquivos/upload/',
        {
          method: 'POST',
          headers: {
            Authorization: 'Bearer ' + authToken,
            'Content-Type': 'multipart/form-data',
          },
          body: formData,
        }
      );
    } catch (error) {
      throw Error(error);
    }
  };
```

### Error 
[Unhandled promise rejection: Error: TypeError: Network request failed]

Stack trace:
  node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  node_modules/regenerator-runtime/runtime.js:293:29 in invoke
  node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  node_modules/regenerator-runtime/runtime.js:154:27 in invoke
  node_modules/regenerator-runtime/runtime.js:166:18 in PromiseImpl.resolve.then$argument_1
  node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
  node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
  [native code]:null in flushedQueue
  [native code]:null in callFunctionReturnFlushedQueue
  ...

**Comment by byCedric** [comment]
Hi @keomalima, thanks for writing in! I think your issue might be related to an ongoing `file:/...` mixup on Android (if you are using Android). You should be able to run [the snack I provided in issue #11422](https://github.com/expo/expo/issues/11422#issuecomment-748996855). This snack has a working example how to pick and upload an image (on both web and native).

- Make sure to checkout line 36, which includes a workaround for incorrect file paths
- See lines 40 to 50 to see web vs native differences

One thing to be careful about is using `fetch` to retrieve a local file. I don't think that's supported, if you use fetch it should be fetching an URL (not a URI).

Hope this helps!

**Comment by keomalima** [comment]
Hello @byCedric thanks for taking the time. I've tried this example previously but I'm still getting the error. 

I'm only fetching the URI because I need the image in binary format, I'm still struggling to see if this would be the correct approach tho since expo doesn't support rn-fetch-blob.

**Comment by byCedric** [comment]
@keomalima, do you need the binary within React Native or just the server? Because in the example, the image is still sent as a file/binary. This means you can store on your CDN for example, and serve it as an image later.

**Comment by DylanRiden** [comment]
@byCedric Hi, I am getting this same exact issue when using fetch on android... not uploading image, just fetching from my external API.
A placeholder API such as https://reqres.in/api/users?page=2 works fine, are there any necessary headers for Android?

**Comment by DylanRiden** [comment]
@byCedric Tested this on multiple networks, on multiple different android phones... all not working

**Comment by byCedric** [comment]
@DylanRiden Please open a new issue with a reproducible example for us. I can't repro this with the snippet from this issue, so I can't help much further. If you have a snack or git repo with the issue, that would be very helpful.
