### ISSUE TITLE
[issue/question/discussion] Too many access required

### ISSUE THREAD

**Issue by radi-cho** [expo/expo#1160]
I created a demo app with Expo XDE (Basic app with bottom navigation bar). After that built it (for android - `apk` file) and installed it on my device. I was surprised, because it requires too many access (internet, phone, microphone, camera, GPS, Google service info, ect.). I understand that Expo provides a lot of APIs - camera, microphone, GPS, ect. but **I'm not using them. Can I build app, that won't require so many access (if not using Expo APIs)**
My app is hosted here: https://expo.io/@radi-cho/test1

<image alt="screenshot" src="https://user-images.githubusercontent.com/12954909/34326403-a99cc500-e8b3-11e7-899d-e95c0cb1ff93.png" width="250" /> <image alt="screenshot" src="https://user-images.githubusercontent.com/12954909/34326402-a97fbbc2-e8b3-11e7-8fb0-50fc2df2da1f.png" width="250" />

**Comment by brentvatne** [comment]
hi! please consider only posting your question/concern to one channel rather than spamming us on multiple channels (twitter, github). see: https://twitter.com/notbrent/status/945022287954173952

**Comment by radi-cho** [comment]
Okay. Thanks for the response and sorry about the spamming.
