### ISSUE TITLE
Expo not 'reading' app.json

### ISSUE THREAD

**Issue by bbrez1** [expo/expo#11617]
### Summary of Issue 

I have this issue on multiple projects and 2 devices. No matter what I change (I created 5 new projects and they all have this issue) the **expo publish** command publishes the app's slug as the project folder's name instead of the slug specified in app.json. The app name is default (Folder name again but capitalized) and there is no icon. I have tried on 5 new projects and it works fine 2-3 times until it doesn't anymore and nothing I have tried for the past 3 days has worked. This includes creating new projects and moving my code into that project, going through all dependencies and checking each one of them, removing node_modules folders, upgrading and downgrading from 39 to 40 Expo SDK, etc. When I build the apk the app's name is Expo2 (my folder name) and it uses the default logo. It used to work fine a few months ago.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Users\Blaz\AppData\Local\Yarn\bin\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible Demo

I don't know how to give an example to reproduce this as I have no idea what the issue is. It's simply a new project that publishes fine for 2-3 times until I make a few changes to the code.

**Comment by bbrez1** [comment]
One of our developers added an app.config.js file, just realized that if you do not pass the config file from app.json into this then it won't be read.

```
export default ({ config }) => {
  return {
    ...config,
    extra: {
      ...
    }
  };
};

```

^ in app.config.js has solved this issue.

**Comment by AdamJNavarro** [comment]
Glad you got this sorted out @bbrez1! Thanks for following up. 👏
