### ISSUE TITLE
React native debugger cannot be connected after sdk 40 upgrade

### ISSUE THREAD

**Issue by chuanxie** [expo/expo#11615]
is anyone else has similar issue? working fine on sdk 39

even upgrade the react native debugger to v0.11.7

    "react": "^17.0.1",
    "react-devtools": "4.10.1",
    "react-dom": "^17.0.1",
    "react-native": "^0.63.4",
    "expo": "^40.0.0",

**Comment by byCedric** [comment]
Hi @chuanxie, could you provide more context and a repro for this issue? Without that, I'm not sure where to start debugging. It works fine in a new project.

**Comment by chuanxie** [comment]
@byCedric  you can check this repo https://github.com/chuanxie/sdk40.
its basically new expo project and run the following 
`REACT_DEBUGGER="unset ELECTRON_RUN_AS_NODE && open -g 'rndebugger://set-debugger-loc?port=19001' || yarn start` 
i can see react native debugger opened but `waiting for react to connect`

**Comment by chuanxie** [comment]
@byCedric 
problem solved after running `brew upgrade` like python and installed watchman globally
maybe need to notice those dependencies for expo upgrade
