### ISSUE TITLE
ImagePicker returns null for bae64 on Android

### ISSUE THREAD

**Issue by igorroman777** [expo/expo#11610]
### result.base64 is undefined
Only uri works for me: file:/data/user/0/…
With base64: I get no alert to see.

### I have on my smartphone Samsung Galaxy A6+ with Android 10 (Kernel 3.18.124-19348620)
tested.
"expo": "~40.0.0",
    "expo-app-loading": "^1.0.1",
    "expo-asset": "~8.2.1",
    "expo-constants": "~9.3.0",
    "expo-font": "~8.4.0",
    "expo-gl": "~9.2.0",
    "expo-image-picker": "^9.2.1",
    "expo-linking": "~2.0.0",
    "expo-screen-orientation": "^2.1.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "expo-three": "^5.4.0",
    "expo-three-orbit-controls": "^2.0.0",
    "expo-web-browser": "~8.6.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-web": "~0.13.12",

### Reproducible Demo
!--
      let result = await ImagePicker.launchImageLibraryAsync({
                mediaTypes: ImagePicker.MediaTypeOptions.Images,
                base64: true,
                allowsEditing: true,
                // aspect: [4, 3],
                quality: 1,
    });
   if (!result.cancelled) {
             alert(result.base64);
    }
``

**Comment by lukmccall** [comment]
I couldn't reproduce this bug.  Can you provide an asset that causing that problem?

**Comment by igorroman777** [comment]
@lukmccall 
> Can you provide an asset that causing that problem?

It does not work on kubuntu laptop in browser and also on Samsung A6+ phone with Android 10.
I need result.base64 -> and that does not work.
result.uri works.
