### ISSUE TITLE
[Android] ImagePicker selected image not showing

### ISSUE THREAD

**Issue by riwu** [expo/expo#1161]
https://snack.expo.io/@riwu/image-picker-bug

Works fine on iOS: https://i.imgur.com/n861Leq.png

On Android:
Embedded device on snack: shows up briefly then disappears https://i.imgur.com/QKIMAqi.gif
Actual device (Samsung S8+, Android 7.0): doesn't show at all after picking an image 

```
    "expo": "^24.0.2",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
```

**Comment by jesseruder** [comment]
Thanks for the information. As far as I can tell the ImagePicker API is working but the snack gets reloaded after the image shows up.

**Comment by riwu** [comment]
Oh right, I mistyped `url` instead of `uri` for `Image` `src` in my original project which strangely still works on iOS but not Android...

**Comment by riwu** [comment]
Out of curiosity, what's the technology behind snack? 
Does it simply run the code in a Docker container or an actual OS (that assigns a random port to an instance)?
If so, why does it frequently exhibit different behaviours than local environment?
