### ISSUE TITLE
exp Command-Line tool can't install on ubuntu 17.10

### ISSUE THREAD

**Issue by YouSour** [expo/expo#1162]
hi , guy , i'm new with expo , i try  to install  expo Command-Line tool on ubuntu 17.10 but it 's not work , any idea about this , thank for advance :)
![screenshot from 2017-12-25 20-29-08](https://user-images.githubusercontent.com/9318106/34340235-ef3b4686-e9b2-11e7-99f6-0c5d1e89f0c6.png)

**Comment by fxfactorial** [comment]
Your npm installation is installing to an odd location, non usual for global location. 

You could either fix that or as a short cut try: `yarn global add exp` and use that installation

**Comment by YouSour** [comment]
i want to fix it , how ? @fxfactorial

**Comment by fxfactorial** [comment]
i don't know why your npm install is installing to a non-standard location. Probably easiest to get rid of it and install the recommended way: 

https://nodejs.org/en/download/package-manager/
