### ISSUE TITLE
Xcode iOS Build & process.env

### ISSUE THREAD

**Issue by mdbiscan** [expo/expo#11621]
I've just ejected an expo project and I've got everything working properly in Android, Android Simulator, iOS Simulator, but not iOS build through Xcode. It's imperative that we use `process.env`, which I have discovered is not available in an Xcode build. 

Can I access Xcode environment variables as a fallback? I'm finding lack if information about this on `expo-constants` and other areas of the web hard to swallow. Am I missing something obvious here?

- Expo SDK40
- Xcode 12.3
- Node 14 LTS

**Comment by mdbiscan** [comment]
Discovered after I switched to https://github.com/babel/website/blob/master/docs/plugin-transform-inline-environment-variables.md and set exports in Xcode, everything worked again. Posting here for posterity.

**Comment by danbeo95** [comment]
I am facing the same problem
Anyone have solution?
