### ISSUE TITLE
[imagepicker]: iOS14.0+ photoLibrary shows all photos even if user choose the selected photos permission

### ISSUE THREAD

**Issue by devcocup** [expo/expo#11625]
## 🐛 Bug Report

I am using the expo-image-picker in my project. When I use the photo from the photo library, app shows the all photos even if I choose the "selected photos" permission. This is happening on the iOS 14.0+ only.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
expo-image-picker: 0.8.0
 
### Steps to Reproduce
1. Choose the "selected photos" permission in the photolibrary permission popup.
2. Open photoLibrary
3. It shows all photos

### Expected Behavior vs Actual Behavior
This should display the selected photos only since I chose the "selected photos" permission.

**Comment by gyoung-panopto** [comment]
I have the same issue.

**Comment by Razorholt** [comment]
My expo-image-picker version is 9.2.0. Can you try and update it?

Also, I found that package quite buggy. i.e. Video Passthrough is not respected and when a video is selected (on iOS) the compressing process gets stuck and freezes the app.

Finally, there is a typo in C:\Users\vhirt\OneDrive\business\mobshed\expo\mobshed9\node_modules\expo-image-picker\src\ImagePicker.ts - Search for "libary"

**Comment by thisisgit** [comment]
I had the same concern but after looking into a number of post, I have a feeling that it's an intended behavior. (FYI, I'm new to mobile dev)

As I tested few apps like Instagram, Facebook, Pinterest, and etc., they all have their own custom camera roll and that's the place where the app is showing accessible photos. The picker itself always shows all the photos and is only used to add selected photos to the camera roll.

Based on [this thread](https://developer.apple.com/forums/thread/653414), [another thread](https://developer.apple.com/forums/thread/663098), and [this answer](https://stackoverflow.com/a/65025110), I assume the picker always shows all the photos and to show only selected photos, custom camera roll is necessary.

So the UX goes like this:
1. Full access to photos - shows all photos to your camera roll
2. Access to only selected photos - select photos from the **picker** to display in your camera roll. Optionally have a button which lead user to select more photos.
3. No access - show nothing in the camera roll. Optionally have a button that lead user to change app permission.

And to achieve above flow, we are missing following features:
1. Being able to select more photos ([example of screenshot](https://github.com/expo/expo/pull/9423#issuecomment-707237822))
2. Being able to fetch photos with permission to show in custom camera roll ([open issue in another library](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/279))

Anyone please correct me if I'm wrong.
cc @byCedric

**Comment by lukmccall** [comment]
The image picker is a part of the iOS SDK. Expo package only displays the system modal with some additional configuration. Your app doesn't have access to photos before the user selects one. That's why Apple shows you all photos even if you have partial permission.

**Comment by devcocup** [comment]
@lukmccall I think "selected photos" permission was introduced on iOS14.+(maybe September 2020?)

**Comment by lukmccall** [comment]
Yes, the "selected photos" permission was introduced on iOS 14.0.

**Comment by thisisgit** [comment]
Hi @lukmccall, is there any issue that I can follow to see the progress of [this feature](https://github.com/expo/expo/pull/9423#issuecomment-707237822)? If it won't be available any time soon, I would have to use other library like [this one](https://github.com/zoontek/react-native-permissions#openlimitedphotolibrarypicker-ios-14).

Plus, I was looking for an API from Expo to fetch photos with permission but I don't think [this](https://docs.expo.io/versions/v40.0.0/sdk/media-library/#medialibrarygetassetsasyncoptions) supports the feature yet. May I know if there's an ongoing progress on that feature?

**Comment by lukmccall** [comment]
Hi @thisisgit, this feature was added to `expo-media-library` in the SDK 40. See https://docs.expo.io/versions/latest/sdk/media-library/#medialibrarypresentpermissionspickerasync ;)

**Comment by rizwan-incapsulate** [comment]
i am also facing the same issue in expo 47

**Comment by nicolazj** [comment]
yes having same issue.. 
is there a plan to fix this ?

**Comment by hungnm-kaopiz** [comment]
Any update?
