### ISSUE TITLE
BarCodeScanner ignores barCodeTypes property in Android

### ISSUE THREAD

**Issue by mvestola** [expo/expo#11632]
### Summary of Issue 

In BarCodeScanner, `barCodeTypes` prop is ignored in Android at least. This started to happen when I upgraded expo from v38 to v40. In version 38 it worked as expected. Docs here: https://docs.expo.io/versions/latest/sdk/bar-code-scanner/#supported-formats

This seems to have been issue also earlier, e.g. https://github.com/expo/expo/issues/7352

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 4.0.17 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      npm: 6.14.5 - ~/.nvm/versions/node/v12.14.1/bin/npm
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed
```

Tried in Android only. Android version 10. Phone model: Onplus Nord AC2003
 
### Steps to Reproduce

This might be hard to reproduce in other than real phone since needs camera and barcodes to scan.

I have some different types of barcodes here: https://github.com/mvestola/panttipullo-react-native/tree/master/test/barcodes

Scan those barcodes with phone using below barcode scanner code which restricts barcode types to EAN-13 / EAN-8 / UPC-A / UPC-E. All other test images should be scanned but not the ones starting with name "not_supported_*".

Barcode scanner code used in this project is here: https://github.com/mvestola/panttipullo-react-native/blob/master/src/feature/scanner/view/BarcodeScanner.jsx

```
import React from "react"
import { BarCodeScanner } from "expo-barcode-scanner"

const handleBarCodeScanned = ({ data }) => {
  console.log(data)
}

export const BarcodeScanner = () => (
  <BarCodeScanner
    onBarCodeScanned={handleBarCodeScanned}
    barCodeTypes={[
      BarCodeScanner.Constants.BarCodeType.ean13,
      BarCodeScanner.Constants.BarCodeType.ean8,
      BarCodeScanner.Constants.BarCodeType.upc_a,
      BarCodeScanner.Constants.BarCodeType.upc_e,
    ]}
  />
)
```

### Expected Behavior vs Actual Behavior

Expected: Barcode scanner should not scan any other types of barcodes than defined in barCodeTypes prop.

Actual: Now it scans also e.g. QR code and Code 39 even if limited to EAN-13 / EAN-8 / UPC-A / UPC-E in barCodeTypes prop.

**Comment by byCedric** [comment]
Hi @mvestola, thanks for the issue report and the example. This looks like a race condition, as I can only reproduce this on the first render. After that, when a state value updates and the barcode scanner is rerendered, it does _not_ ignore the types. We have to look into this to fully resolve it.

In the meantime, you could "work around" the issue by adding a check to your barcode scanner handle. E.g.
```jsx
const allowedBarCodes = [
  BarCodeScanner.Constants.BarCodeType.ean13,
  BarCodeScanner.Constants.BarCodeType.ean8,
  BarCodeScanner.Constants.BarCodeType.upc_a,
  BarCodeScanner.Constants.BarCodeType.upc_e,
]

const handleBarCodeScanned = (event) => {
  if (!allowedBarCodes.includes(event.type)) {
    // barcode not allowed, ignore this event
    return
  }

  console.log(event.data)
}

export const BarcodeScanner = () => (
  <BarCodeScanner
    onBarCodeScanned={handleBarCodeScanned}
    barCodeTypes={allowedBarCodes}
  />
)
```

**Comment by mvestola** [comment]
Thanks for the workaround, I can confirm that it works well. Without the workaround, at least for me, the issue happens not only on the first render but on every render, so if I go to some other view and then come back again to the barcode scanner view, issue happens every time.

**Comment by markerio** [comment]
We can still reproduce the issue.

We updated the app and expo sdk/cli to the most recent versions.

We are using:
    "expo": "^49.0.0",
    "expo-barcode-scanner": "~12.5.3",
    "expo-camera": "~13.4.4",

Any updates on this issue?

**Comment by marcosdiasdev** [comment]
I can confirm the issue is still happening on Expo 49. I'm using `expo-camera` and my scanner still scans any barcode type no matter which `barCodeTypes` I set.

**Comment by n-ii-ma** [comment]
This issue is still happening!
