### ISSUE TITLE
Entitlements can no longer have empty arrays

### ISSUE THREAD

**Issue by IronforgeAsh** [expo/expo#11631]
### Summary of Issue 
Apple now requires entitlement keys to be completed or not included at all.

So sending keys like this:

```
 <key>com.apple.developer.in-app-payments</key>
 <array/>
 
 <key>com.apple.security.application-groups</key>
 <array/>
```

Will now cause Apple to reject the app when you attempt to upload it with the following error:

`ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: '[]' for the key 'com.apple.security.application-groups' in 'Payload/ExpoKitApp.app/com.company.appname'.`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

**Target Platform:** iOS
**IDE:** Visual Studio Code
**Local Platform:** Windows 10

**Diagnostics:**
  Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\ashle\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed

**App.json:**
```
{
  "expo": {
    "name": "App Name",
    "slug": "app-name-slug",
    "version": "1.1.3",
    "orientation": "portrait",
    "icon": "./src/assets/icon.png",
    "splash": {
      "image": "./src/assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#000000"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "com.company.appname",
      "buildNumber": "1.1.3",
      "infoPlist": {
        "NSCameraUsageDescription": "appname uses your camera to allow you to upload a profile picture.",
        "NSPhotoLibraryUsageDescription": "appname uses your photos to allow you to upload a profile picture."
      },
      "entitlements": {        
      }
    },
    "android": {
      "package": "com.company.appname",
      "versionCode": 15,
      "permissions": []
    },
    "web": {
      "favicon": "./src/assets/favicon.png"
    },
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#042f3d"
    },
    "androidNavigationBar": {
      "barStyle": "dark-content",
      "backgroundColor": "#042f3d"
    },
    "description": ""
  }
}
```

How do we ensure these keys are no longer included in the build archive?

**Comment by TheJoshE** [comment]
This is a pretty urgent one as no apps can now be submitted to the app store.

Is there any way around this in the meantime?

**Comment by IronforgeAsh** [comment]
> This is a pretty urgent one as no apps can now be submitted to the app store.
> 
> Is there any way around this in the meantime?

The only suggestion I have found is running in bare mode, which is far from ideal.

**Comment by TheJoshE** [comment]
Yeah that's not really a solution for me.

Just to add my errors to list:

`ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: '[ ]' for the key 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/CymruAmamAm'."

ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: '[ ]' for the key 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/CymruAmamAm'."

ERROR ITMS-90211: "Invalid Code Signing Entitlements. The signature for your app bundle contains entitlement values that are not supported. Specifically, value '( ) [not an Array]' for the key 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/CymruAmamAm' is not supported."

ERROR ITMS-90211: "Invalid Code Signing Entitlements. The signature for your app bundle contains entitlement values that are not supported. Specifically, value '( ) [not an Array]' for the key 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/ExpoKitApp.app/CymruAmamAm' is not supported."`

Here's a topic on the Apple forums detailing the issue too: https://developer.apple.com/forums/thread/671352

Fingers crossed a hotfix can be pushed through quickly!

**Comment by IronforgeAsh** [comment]
Yeah, it's not a solution for me either.
I am currently attempting to eject in a new branch, but it's not ideal. The entire reason we used expo was for managed mode :(

**Comment by cruzach** [comment]
Hi guys, thanks for bringing this up! We'll look into it ASAP

**Comment by TheJoshE** [comment]
Great, thanks @cruzach!

**Comment by cruzach** [comment]
@IronforgeAsh does your app.json file include an empty `entitlements` object, or are you excluding those from the issue report?

**Comment by pedro-lopes97** [comment]
I made a build an hour ago and got the same error. I do not include an empty entitlements object in my app.json. 
I'm in managed workflow sdk 39

**Comment by TheJoshE** [comment]
> @IronforgeAsh does your app.json file include an empty `entitlements` object, or are you excluding those from the issue report?
> 
> @TheJoshE do you include `usesIcloudStorage` in your app.json file?

Yes here's the ios section of my app.json

`"ios": {
      "supportsTablet": true,
      "bundleIdentifier": "cymru.amam.am",
      "buildNumber": "21",
      "userInterfaceStyle": "light",

      "usesIcloudStorage": true,
      "infoPlist": {
        "NSPhotoLibraryUsageDescription": "AM requires access to your photo library to allow you to upload photos from your library.",
        "NSCameraUsageDescription": "AM requires access to your camera to allow you to take and upload photos."
      }
    },`

**Comment by IronforgeAsh** [comment]
> @IronforgeAsh does your app.json file include an empty `entitlements` object, or are you excluding those from the issue report?
> 
> @TheJoshE do you include `usesIcloudStorage` in your app.json file?

I have tried with and without.

**Comment by cruzach** [comment]
Does your provisioning profile (available at https://developer.apple.com/account/resources/profiles/list) or app id (available at https://developer.apple.com/account/resources/identifiers/list)  include the entitlements that are causing the error? If you don't use them, you should remove them. If you do, then you should include them in the `entitlements` object

With a new app id/provisioning profile, I'm not able to reproduce this so far

**Comment by IronforgeAsh** [comment]
> Does your provisioning profile (available at https://developer.apple.com/account/resources/profiles/list) or app id (available at https://developer.apple.com/account/resources/identifiers/list) include the entitlements that are causing the error? If you don't use them, you should remove them (you'll then have to regenerate the provisioning profile and re build). If you do, then you should include them in the `entitlements` object
> 
> With a new app id/provisioning profile, I'm not able to reproduce this so far

FWIW, the entitlements object doesn't appear to be well documented. I found one use for it in the expo docs.

I don't believe the provisioning profile has my entitlements enabled.

**Comment by pedro-lopes97** [comment]
This is my error:

`[16:18:18]: [Transporter Error Output]: ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: '[ ]' for the key 'com.apple.developer.icloud-container-identifiers' in 'Payload/ExpoKitApp.app/Com.app.blabla'"

**Comment by cruzach** [comment]
@IronforgeAsh please check your App ID in the developer portal, my guess is you have the App Groups item checked but don't have any app groups configured

**Comment by cruzach** [comment]
@pedro-lopes97 check your App ID in the developer portal, you probably have the icloud item checked but don't have any containers configured: 
![image](https://user-images.githubusercontent.com/35579283/104752236-6c290980-5724-11eb-854d-cba5431d0908.png)

**Comment by TheJoshE** [comment]
> @pedro-lopes97 check your App ID in the developer portal, you probably have the icloud item checked but don't have any containers configured:
> ![image](https://user-images.githubusercontent.com/35579283/104752236-6c290980-5724-11eb-854d-cba5431d0908.png)

This is the case for me, I didn't have a cloud container attached so I've just created one. 

Just rebuilding so will confirm if it works as soon as it's done.

Strange Apple have changed this requirement as it's been this way for months!

**Comment by cruzach** [comment]
I totally agree, it is strange. I think we could protect you better from this by not adding the entitlement to your IPA if there are none configured (I believe we already do that in EAS build, which is why that was working)

**Comment by pedro-lopes97** [comment]
> > @pedro-lopes97 check your App ID in the developer portal, you probably have the icloud item checked but don't have any containers configured:
> > ![image](https://user-images.githubusercontent.com/35579283/104752236-6c290980-5724-11eb-854d-cba5431d0908.png)
> 
> This is the case for me, I didn't have a cloud container attached so I've just created one.
> 
> Just rebuilding so will confirm if it works as soon as it's done.
> 
> Strange Apple have changed this requirement as it's been this way for months!

This is my case too. I will rebuild and let you know

**Comment by IronforgeAsh** [comment]
Waiting for a team member to check this out (I don't have the credentials to the client's apple account, only via have access via App Store Connect). Will update here as soon as I can.

**Comment by TheJoshE** [comment]
Just uploaded the app with no issues.

Thanks @cruzach for your help, much appreciated!

**Comment by IronforgeAsh** [comment]
@cruzach Looks good so far. Thanks!
