### ISSUE TITLE
Expo MediaLibrary requestPermissionsAsync expects 0 arguments but received 1

### ISSUE THREAD

**Issue by king804** [expo/expo#11649]
### Summary of Issue 
Native method ExponentMediaLibrary.requestPermissionsAsync expects 0 arguments but received 1

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: 3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

### Reproducible Demo
i saw the node_module code as below, i think there are no need to pass writeOnly?

```
export async function requestPermissionsAsync(
  writeOnly: boolean = false
): Promise<PermissionResponse> {
  if (!MediaLibrary.requestPermissionsAsync) {
    throw new UnavailabilityError('MediaLibrary', 'requestPermissionsAsync');
  }
  return await MediaLibrary.requestPermissionsAsync(writeOnly);
}
```

 
### Steps to Reproduce
await MediaLibrary.requestPermissionsAsync();

### Expected Behavior vs Actual Behavior
no need pass writeOnly?

**Comment by king804** [comment]
ios: 14
"expo-media-library": "^10.0.0"

**Comment by VictorioMolina** [comment]
I have exactly same issue. Did you solve it?
