### ISSUE TITLE
Expo init web UI hidden apart from tab navigation

### ISSUE THREAD

**Issue by tedcurrent** [expo/expo#11644]
### Summary of Issue 
Expo web UI flickers and stays hidden when using the TypeScript tabs template from `expo init`. In other words, it's unusable for me at least.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed
```

### Reproducible Demo
This is 100% the first thing you get from running `expo init` and `yarn start` on web, no code of my own.

 
### Steps to Reproduce
1. `expo init test-project`
2. `cd test-project`
3. `yarn start`
4. w to run on web
5. Go to browser

### Expected Behavior vs Actual Behavior
Expected: The content of a tab view should be visible.
Actual: The content of a tab view is hidden. It is rendered, but not visible.

See video here:
https://user-images.githubusercontent.com/7895034/104740405-97295280-5750-11eb-95ba-28163e0c479b.mov
And screenshot here:
<img width="1679" alt="Screenshot 2021-01-15 at 16 42 37" src="https://user-images.githubusercontent.com/7895034/104740518-b627e480-5750-11eb-986d-b8f5cd4efaff.png">

**Comment by nedredmond** [comment]
I am having this issue as well on a fresh install. View renders in Android.

**Comment by byCedric** [comment]
Hi @tedcurrent and @nedredmond, it seems like this could be related to this bug in `react-navigation` https://github.com/react-navigation/react-navigation/issues/9225. Could you try downgrading to the specific versions mentioned there.

**Comment by brentvatne** [comment]
i released a new version of the tabs template that fixes this by ensuring we're using versions of react-navigation w/o this regression on web: https://github.com/expo/expo/commit/4d2b2fc281cdda7f875318925710f698824a604a

this issue will be resolved in react-navigation itself shortly, and then we can go back to using the latest versions.
