### ISSUE TITLE
Expo SDK 40: Native module cannot be null

### ISSUE THREAD

**Issue by nickprozee** [expo/expo#11641]
## 🐛 Bug Report
Expo SDK 40 crashesh on iOs (Managed Workflow)

### Summary of Issue
StackOverflow: [Stackoverflow Question](https://stackoverflow.com/questions/65721834/native-module-cannot-be-null-ios-expo)
When debugging the project on iOs device using the expo client, it crashes immediatly, **on android everything works without any issues**. **The problem here is that I want to be able to find the package causing this,  being able to fix futher instances.**

As far as I understand, some of my packages use native modules, which ofcourse are not used by the managed workflow, I need to eject in order to do this, however, I want to stay in the managed workflow so far.

Also, what I do not understand is, how does this run on android if this requires native modules?

## Output
![image](https://user-images.githubusercontent.com/7586797/104714996-384ee380-5726-11eb-9787-2fec6d1ea9de.png)

## Packages
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "@microsoft/signalr": "^3.1.9",
    "@react-native-community/async-storage": "~1.12.0",
    "@react-native-community/datetimepicker": "3.0.4",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.9.2",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",
    "expo": "^40.0.0",
    "expo-asset": "~8.2.1",
    "expo-av": "~8.7.0",
    "expo-camera": "~9.1.0",
    "expo-constants": "~9.3.3",
    "expo-document-picker": "~8.4.1",
    "expo-file-system": "~9.3.0",
    "expo-font": "~8.4.0",
    "expo-image-manipulator": "~8.4.0",
    "expo-image-picker": "~9.2.0",
    "expo-linking": "~2.0.0",
    "expo-media-library": "~10.0.0",
    "expo-notifications": "~0.8.2",
    "expo-splash-screen": "~0.8.1",
    "expo-status-bar": "~1.0.3",
    "expo-web-browser": "~8.6.0",
    "i": "^0.3.6",
    "install": "^0.13.0",
    "jwt-decode": "^3.0.0",
    "moment": "^2.29.1",
    "npm": "^6.14.9",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-audio-record": "^0.2.2",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-image-view": "^2.1.9",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-modal-datetime-picker": "^9.0.0",
    "react-native-paper": "^4.2.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-spinkit": "^1.5.1",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-toast-message": "^1.3.4",
    "react-native-web": "~0.13.12",
    "react-navigation": "^4.4.3",
    "react-navigation-material-bottom-tabs": "^2.3.3"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "babel-preset-expo": "8.3.0",
    "jest-expo": "^40.0.0",
    "typescript": "~4.0.0"
  },
  "private": true
}

```

### Steps to Reproduce
Run the expo client and open project on iOs device

### Expected Behavior vs Actual Behavior
Result: Crash
Expected: Run without issues

**Comment by brentvatne** [comment]
hi there! please follow the issue template fully and provide a [mcve](https://stackoverflow.com/help/minimal-reproducible-example) - a runnable reproducible demo. this is an important step to debugging the project on your own, and we need it in order to help, unless you have otherwise clearly identified and explained the root cause.
