### ISSUE TITLE
[XDE] It hangs without stopping

### ISSUE THREAD

**Issue by yordis** [expo/expo#1165]
This is a snapshot of the output but this is in an infinite loop and I have to close the app.
```
1514295290720 - Worker 0 exited - Exit code: 1
5:34:50 AM
1514295290938 - Origin: Worker (PID 99823)
   [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (/Users/yordisprietolazo/Sites/APPNAME/node_modules/uws/uws.js:38:19)
    at Object.<anonymous> (/Users/yordisprietolazo/Sites/APPNAME/node_modules/uws/uws.js:42:3)
    at Object.<anonymous> (/Users/yordisprietolazo/Sites/APPNAME/node_modules/uws/uws.js:565:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by yordis** [comment]
I had to add this change

```
-    "remotedev": "remotedev-debugger --injectserver",
-    "postinstall": "yarn remotedev && rndebugger-open --expo"
+    "postinstall": "rndebugger-open --expo"
```

I am not sure why `remotedev-debugger` is causing XDE to fail ...

**Comment by jesseruder** [comment]
This happened when you opened the your app in XDE? I'm confused why the postinstall script would matter at all.

**Comment by yordis** [comment]
@jesseruder when I click on specific app on my XDE yes.

**Comment by jesseruder** [comment]
I'm not sure what rndebugger is doing, it might just not interact well with XDE. Since that's not an Expo project we can't dig in too deeply.

Did you try following these instructions?
> Please install a supported C++11 compiler and reinstall the module 'uws'

**Comment by yordis** [comment]
> This happened when you opened the your app in XDE? I'm confused why the postinstall script would matter at all.

This is the first I would like to answer 😄  Why is XDE getting stock with something that suppose to run only when I run the script.

When XDE lunches `remote debugger`?

> Did you try following these instructions?

I didn't run it.

**Comment by yordis** [comment]
@terribleben I didn't fix this but I do not have that issue anymore because the project doesn't exists anymore.

Hopefully I will no have it anymore
