### ISSUE TITLE
[docs] iOS Push Notifications Setup Unclear for Bare Workflow

### ISSUE THREAD

**Issue by kevgrig** [expo/expo#11656]
The Push Notifications Setup instructions have [a section](https://docs.expo.io/push-notifications/push-notifications-setup/#credentials) on using `expo credentials:manager` to specify the Push Notifications Key for iOS. I used the `I want to upload my own file` option. However, after uploading the p8 key with `Add new Push Notifications Key`, push notifications didn't work seemingly until I also chose the option `Use existing Push Notifications Key in current project`. This confused me for a while so it would be nice if the docs mentioned this step. Here are the steps I took in my console:

```
✔ What do you want to do? › Add new Push Notifications Key
✔ Will you provide your own Apple Push Notifications service key? › I want to upload my own file
✔ Path to P8 file: … ${ABS_PATH_TO_P8_FILE}
✔ Key ID: … ${P8_KEY_ID}
✔ Apple Team ID: … ${TEAM_ID}
Unable to validate Push Keys due to insufficient Apple Credentials
Successfully created Push Notification Key

  Push Notifications Key - Key ID: undefined
    Apple Team ID: ${TEAM_ID},  Apple Team Name: ---------


Available credentials for iOS apps

Application credentials


User credentials

  Push Notifications Key - Key ID: undefined
    Apple Team ID: ${TEAM_ID},  Apple Team Name: ---------
    not used by any apps



✔ What do you want to do? › Use existing Push Notifications Key in current project
✔ Select credentials from list › Push Notifications Key (Key ID: undefined, Team ID: ${TEAM_ID})
    not used by any apps
    ❓ Validity of this certificate on Apple's servers is unknown.
Successfully assigned Push Notifactions Key to ${MY_APP_INFO}
```

**Comment by cruzach** [comment]
thanks @kevgrig ! I think we can do even better than documentation here- the option to `Add new Push Notifications Key` should also prompt you if you'd like to configure that push key with your current project (if there is one). One-stop-shop commands are nice imo, I'll open a PR for that. hopefully that addresses your use case?

**Comment by kevgrig** [comment]
@cruzach Yes, that'd be great, thanks!

**Comment by cruzach** [comment]
cool 👍  this issue will be fixed by https://github.com/expo/expo-cli/pull/3098 in that case
