### ISSUE TITLE
[expo-store-review] only opens play store but no modal

### ISSUE THREAD

**Issue by alexis19872** [expo/expo#11654]
Please provide the following:
1. SDK Version:38
2. Platforms(Android/iOS/web/all): Android

I past the last 5 hours trying to use expo request Review but i cant.

I folowed the instructions (or what i understood) so i put
i instaled expo-store-review
import * as StoreReview from 'expo-store-review';
it didnt work, so i instaled also expo-linking, and expo-constants

I call       StoreReview.requestReview()
Im on emulator with android 7 and my smarthphone with android 10 and in both cases it opens the PlayStore url.

But never opens the modal to rate from there. On the other hand is it posible to call StoreReview.requestReview() after determinated time with the app opened? 
So for example to call StoreReview.requestReview() after one hour of using the app?

(Not one hour of continuinly using the app, instead one hour total)

**Comment by brentvatne** [comment]
https://developer.android.com/reference/com/google/android/play/core/review/ReviewManager

> Note: In some circumstances the review flow will not be shown to the user, e.g. they have already seen it recently, so do not assume that calling this method will always display the review dialog.

**Comment by dhguissepe** [comment]
@alexis19872 I'm having another kind of issue that could be solved by the answer given here. But as far as I understand, the flow only works for android on expo sdk v40. If you go to the correct page of the [documentation](https://docs.expo.io/versions/v38.0.0/sdk/storereview/) you will see this:

> If this is used in Android the device will attempt to link to the Play Store using ReactNative.Linking and the android.playStoreUrl from the app.json instead.
