### ISSUE TITLE
Getting Failure delivering result ResultInfo after picking image.

### ISSUE THREAD

**Issue by akshaykatale99** [expo/expo#11659]
### Summary of Issue 
Getting Failure delivering result ResultInfo after picking image. I have followed all installation steps but still getting this error.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

    Expo CLI 3.21.5 environment info:
        System:
          OS: Windows 10 10.0.19041
        Binaries:
          Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
          npm: 5.3.0 - C:\Program Files\nodejs\npm.CMD
          Watchman: 20200816.222424.0 - C:\Users\User\AppData\Local\watchman\bin\watchman.EXE
        IDEs:
          Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
        npmPackages:
          expo: ~39.0.2 => 39.0.3
          react: 16.13.1 => 16.13.1
          react-dom: 16.13.1 => 16.13.1
          react-native: ~0.63.3 => 0.63.3
          react-native-web: ~0.13.12 => 0.13.18

### Reproducible Demo

Using this code from documentation.

    const pickImage = async () => {
            let result = await ImagePicker.launchImageLibraryAsync({
              mediaTypes: ImagePicker.MediaTypeOptions.Images,
              allowsEditing: true,
            //   aspect: [4, 3],
              quality: 1,
            });
    
           console.log(result);
    
            // if (!result.cancelled) {
            //   setImage(result.uri);
            // }
        };

Also, I have added activity to AndroidManifest.xml

    <activity
          android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
          android:theme="@style/Base.Theme.AppCompat">
    </activity>
 
### Expected Behavior vs Actual Behavior

In my case app crashing for both launchImageLibraryAsync & launchCameraAsync.

**Comment by brentvatne** [comment]
hi! please provide a [mcve](https://stackoverflow.com/help/minimal-reproducible-example). we're happy to help but need a runnable example. 

you can verify using this simple demo that when used properly it works as expected: https://docs.expo.io/tutorial/image-picker/
