### ISSUE TITLE
Expo debug port seems to have changed from 19001 to 19000

### ISSUE THREAD

**Issue by KurtMar** [expo/expo#11664]
### Summary of Issue
After the Expo 40 upgrade I couldn't connect neither JetBrains nor React Native Debugger to Expo. I finally tried port 19000 instead of 19001 (the one stated in the documentation) and it worked. Has there been a change in the port number or what could be the cause of this?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

### Reproducible Demo
N/A

### Steps to Reproduce
N/A

### Expected Behavior vs Actual Behavior
Either port 19001 should work or the documentation should be changed to port 19000.

**Comment by brentvatne** [comment]
thanks for catching this! we missed updating the docs. metro runs on port 19000 in sdk 40+ because it now shares a server with our manifest endpoint. before we needed 19000 to serve the manifest and 19001 to run metro, but we've improved this situation so that they both are handled by the same server.
