### ISSUE TITLE
ExpoKit Android: "Too many classes in --main-dex-list, main dex capacity exceeded"

### ISSUE THREAD

**Issue by linzebin** [expo/expo#1166]
I want to integrate my own push notification, so I detach my exp project.
After detached, Android project build failed.

`
Error:Execution failed for task ':app:transformClassesWithDexForDev19Debug'.
  com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded
`

- Simulator (Android5.1 API 22) build failed
- Simulator (Android6.0 API 23) build success
- My sdkVersion is 24.0.0

**Comment by terribleben** [comment]
Hey there, sorry about the annoyance. For now I think the best thing to do is to use a prod target, or keep targeting a newer version of Android.

Leaving this issue open so we can come up with a better answer.

**Comment by andrewnaeve** [comment]
Just encountered this, and it magically resolved. my settings in build.gradle (module app) were:
```
android {
  compileSdkVersion 26
  buildToolsVersion '26.0.1'

  defaultConfig {
    applicationId 'CryptoCushion'
    targetSdkVersion 25
```
I changed targetSdkVersion to 23, built, got success, changed back to 25 and poof-- build worked fine. I don't know if that helps at all, but thought I'd let you know what worked for me.

**Comment by nicoara** [comment]
I have the same error. I have detached a project, I want to run the app from Android Studio on the two different real devices I have, none work:
Samsung Galaxy S4 with OS 5.0.1 API 21
Vodafone with OS 4.4.2 API 19
It is unclear, how do I run a detached app on a real device, outside the Expo mobile app - by itself?

**Comment by fxfactorial** [comment]
Hi, you'll want to use the gradle target `-installDevDebug`

**Comment by johhansantana** [comment]
@fxfactorial how can I use this?

**Comment by dooboolab** [comment]
@johhansantana @linzebin @nicoara 
Hi~ I've had few days to solve this problem in expo detached app for android.
Please refer to expo forum in [link here](https://forums.expo.io/t/stuck-on-upgrading-sdk-24-for-android/5902/10).

I've had someone fixed same problem following what I've written here.
Hope it helps you people~

**Comment by dooboolab** [comment]
@johhansantana 
Fastest answer would be just avoid dev19 from flavor

![image](https://user-images.githubusercontent.com/27461460/34927356-e82589be-f9f8-11e7-903c-e0a9eae7546b.png)

**Comment by XardoniK** [comment]
Any updates with this problem? I try 2 diffrent way(XDE or exp) to do project and build in android studio and still have 

Execution failed for task ':app:transformClassesWithDexForDev19Debug'.

I changed sdk tools from 26.0.1 to 27.0.3. I cleaned project and cache and nothing changed, :/

**Comment by ethanyuwang** [comment]
Any update on this?

**Comment by faisal-alamri** [comment]
+1

**Comment by fxfactorial** [comment]
Have folks tried: `./gradlew assembleRelease`

**Comment by ahmetabdi** [comment]
Same issue here

**Comment by alanlanglois** [comment]
same issue

**Comment by icaroharry** [comment]
I'm not sure about that because I don't know very well how Android works, but it seems that this error goes away when I run expo before building the android source on Android Studio.

**Comment by LeiZeng** [comment]
Try add this, works for me for `./gradew assembleProdRelease`

```
android {

    dexOptions {
        keepRuntimeAnnotatedClasses false
    }

}
```
Refference:
https://stackoverflow.com/questions/32721083/too-many-classes-in-main-dex-list-main-dex-capacity-exceeded

**Comment by logan1220** [comment]
@LeiZeng This worked for me! Thanks!

**Comment by a1018875550** [comment]
change the buildToolsVersion to "27.0.2"  it's sloved

**Comment by Rumidom** [comment]
I'm sorry, i'm a complete newbie to android studio. I've been only using expo so far, after detaching i got stuck with this error. I'm trying to use @LeiZeng's solution, but i don't know  where to put that snippet of code. Where is my main DEX file?

**Comment by spedy** [comment]
@Rumidom it's the `android/app/build.gradle` file

**Comment by xiamike** [comment]
wanted to chime in.  @LeiZeng method worked for me too with `installProdDebug` 

still no luck with `installDevDebug` though.  I'm getting a fatal error on launch.  

```
E/AndroidRuntime( 5395): FATAL EXCEPTION: main
E/AndroidRuntime( 5395): Process: com.monad.hexis, PID: 5395
E/AndroidRuntime( 5395): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.monad.hexis-1/base.apk"],nativeLibraryDirectories=[/data/app/com.monad.hexis-1/lib/x86, /vendor/lib, /system/lib]]
E/AndroidRuntime( 5395): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4967)
E/AndroidRuntime( 5395): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4559)
E/AndroidRuntime( 5395): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4499)
E/AndroidRuntime( 5395): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
E/AndroidRuntime( 5395): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
E/AndroidRuntime( 5395): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5395): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5395): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 5395): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5395): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5395): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 5395): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime( 5395): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.monad.hexis-1/base.apk"],nativeLibraryDirectories=[/data/app/com.monad.hexis-1/lib/x86, /vendor/lib, /system/lib]]
E/AndroidRuntime( 5395): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 5395): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 5395): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 5395): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4952)
E/AndroidRuntime( 5395): 	... 11 more
E/AndroidRuntime( 5395): 	Suppressed: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime( 5395): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 5395): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 5395): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 5395): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 5395): 		... 13 more
E/AndroidRuntime( 5395): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager( 1496):   Force finishing activity com.monad.hexis/host.exp.exponent.MainActivity
D/gralloc_ranchu( 1136): gralloc_alloc: Creating ashmem region of size 1019904
D/        ( 1496): HostConnection::get() New Host Connection established 0x9b0ff3d0, tid 1699
E/EGL_emulation( 1136): tid 1136: eglCreateSyncKHR(1865): error 0x3004 (EGL_BAD_ATTRIBUTE)

...

...
```

**Comment by sjchmiela** [comment]
This issue has been solved with ExpoKit SDK31. 🙂

**Comment by WinterHuang003** [comment]
https://blog.csdn.net/micotale/article/details/90202814 可以看看这个博客，解决主dex撑爆问题
