### ISSUE TITLE
"main" has not been registered

### ISSUE THREAD

**Issue by barnu5** [expo/expo#11668]
## 🐛 Bug Report

Note, this is happening after I change the app details in app.json to a new app (same code, different branch). 

I have already tried:
- Deleting node_modules
- Removing yarn.lock
- Running yarn
- Updating react native, expo, react-native-safe-area-context

None of the above solved the problem. 

```
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```
### Summary of Issue 
App crashes at splash

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

iOS
```

  Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.22.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: ~16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ^0.63.4 => 0.63.4
      react-native-web: ^0.13.12 => 0.13.18
    Expo Workflow: managed
```

### Expected Behavior vs Actual Behavior
App crashes. Expect not to crash.

**Comment by brentvatne** [comment]
you did not include a reproducible example, we cannot help you without you fully completing the issue template.

possibly refer to this also https://docs.expo.io/workflow/common-development-errors/#module-appregistry-is-not-a-registered-callable

**Comment by barnu5** [comment]
Thanks @brentvatne, seems it was due to an app error. `expo start --no-dev --minify` was helpful!

**Comment by Aparus** [comment]
try to run 
`EXPO_USE_DEV_SERVER=1 EXPO_TARGET=managed expo start`
instead of `expo start`
