### ISSUE TITLE
ERROR ITMS-90179: “Invalid Code Signing. The executable ‘Payload/Exponent.app/Exponent’ must be signed with the certificate that is contained in the provisioning profile

### ISSUE THREAD

**Issue by ArsenyYankovsky** [expo/expo#1167]
Hey guys,

I’m trying to use Application Loader to publish my built .ipa to TestFlight.

However I’m getting this error:

`ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/Exponent.app/Exponent' must be signed with the certificate that is contained in the provisioning profile.`

I tried both approaches to the certificate there is: letting expo managing everything for me and manually generating certificates, creating a provisioning profile and using certificates with exp build:ios.

Latest build id is cc09aa55-d5ad-4582-b475-8dfe31681fb6, my exp version is 47.1.4

What am I doing wrong? Thanks in advance.

**Comment by terribleben** [comment]
Hey there, sorry you ran into this. Can you provide me with the following info?

- What `exp` command did you run to generate your first build, including all the flags you passed to that command?
- If you ran multiple commands to make multiple builds, and they all had the same issue, can you let me know all of the commands you tried?

I'm hoping to reproduce the exact message on my end, so the more info you can provide about repro steps, the better. Thanks!

**Comment by ArsenyYankovsky** [comment]
All right, I tried running exp build:ios -c on my OS X and it worked. Previously I tried running it on Windows which apparently didn't work. I guess there needs to be a warning of some sorts.

**Comment by terribleben** [comment]
Glad you got it working. Without answers to my previous questions, I won't be able to help determine what caused the issue. We haven't had other reports of this, so the most likely explanation for now is that you provided a profile that didn't match your cert when you tried to do it manually. Let me know if you think there's an issue on our end we should be tracking.

**Comment by ArsenyYankovsky** [comment]
@terribleben 

Well I was running  `exp build:ios -c` in my every new attempt when I tried changing something to use new certificates.

I tried running it letting expo generate certificates which resulted in the same error (on Windows, not OS X). I think it didn't create provisioning profile for me which I did by myself using certificates generated by Expo and imported them into my Xcode.

I also tried re-running build using `exp build:ios` with the same settings after I've seen an error with `exp build:ios -c` which resulted in the same error.

I tried generating certificate and exporting p12 following [this guide](https://calvium.com/how-to-make-a-p12-file/) and running `exp build:ios -c` pointing it at my certificate. I created a provisioning profile from it and imported it into my Xcode and that resulted in the error too. I'm pretty sure that I didn't use the wrong certificate since there was the only one active at the moment though the error might have been caused by the exporting the p12 done wrong (though I did follow the guide and when that didn't work multiple times I tried exporting it without a private key which didn't work too).

Note that I always ran my `exp build:ios -c` on my Windows machine and downloaded .ipa on my OS X one (which I used to generate certificates and imported provisioning profile on). It worked fine when I ran `exp build:ios -c` on my OS X.

Hope that helps.

**Comment by terribleben** [comment]
Ok good to know. If you were running `exp build:ios -c` with no additional flags (e.g. no --local-auth`), then the cert generation and profile generation was happening on our build servers, and the OS of your local machine should not make a difference.

We're landing a change in the nearish future which will do this locally by default, so you should get more explicit information if the issue recurs after that.

**Comment by dima** [comment]
I am running into the same issue except now with `Payload/ExpoKitApp.app/ExpoKitApp`, claims to not be signed with the certificate contained in the provisioning profile. I've tried `exp build:ios` and `exp build:ios -c`. Upgraded to the latest expo prior to building, currently running 49.0.1. I've published other apps using expo and this used to work just fine prior to upgrading.

Any ideas?

**Comment by dima** [comment]
My last build id is: 2660f58a-0b86-4d49-9bdb-6ba986770522 in case you want to check the build file.
