### ISSUE TITLE
FaceDetector detects faces but is missing most face props

### ISSUE THREAD

**Issue by johannesfritsch** [expo/expo#11671]
### Summary of Issue 

Camera image is present. I receive events as soon as my face enters the camera view. It contains a faces array. My face usually has a faceID of 2. But most props are zero (like bounds.size.width and bounds.origin.x). The probabilities for the different locations change between 0 and 1. So it seems that face detection is working correctly.

### Environment

I installed unimodules (0.12.0), expo-camera (9.1.1) and expo-face-detector (8.4.0) into a blank react-native project. There were no issues during installation. I added all the native code into the project according to the guide on unimodules. Tested on latest stable iOS with React Native 0.63.3.

### Reproducible Demo

```javascript
export default function CompetitionScreen() {
  const handleFaceDetected = async (fdr: FaceDetectionResult) => {
    console.log(JSON.stringify(fdr, undefined, 2));
  };

  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Competition Screen</Text>
      <Camera
        style={styles.camera}
        type={Camera.Constants.Type.front}
        faceDetectorSettings={{
          mode: FaceDetector.Constants.Mode.accurate,
          runClassifications: FaceDetector.Constants.Classifications.all,
          tracking: true,
          detectLandmarks: FaceDetector.Constants.Landmarks.all,
        }}
        onFacesDetected={handleFaceDetected}></Camera>
    </View>
  );
}
```
 
### Steps to Reproduce

Just add that screen and the problem starts occuring.

### Expected Behavior vs Actual Behavior

The faces array should contain bounds and all other locations of landmarks for each detected face.

**Comment by brentvatne** [comment]
@johannesfritsch - can you please test this in expo client as well, to help us understand if this is specific to bare react native apps? thanks!

**Comment by ssilverst** [comment]
This does not work in the expo client.

**Comment by brentvatne** [comment]
@ssilverst - please file an issue if you believe you have found a bug. fill in the template.

**Comment by brentvatne** [comment]
closing because no response
