### ISSUE TITLE
React native app suddenly closes - no reason?

### ISSUE THREAD

**Issue by NaamaShiponi** [expo/expo#11677]
I have an app in react native and I'm using expo. After a while the app suddenly crashes and exits. The user is still logged in (so it's not the code that kicks the user out) and no error is displayed.

Have anyone seen something like this before?

I looked for a solution online, and the only clue that I found is that maybe I have a broken package in my project that causes memory leak.

This is my package.json:

 "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-native-fontawesome": "^0.2.5",
    "@hilma/auth": "^0.2.37",
    "@hilma/auth-native": "^0.6.26",
    "@hilma/tools": "^0.1.18",
    "@material-ui/core": "^4.10.1",
    "@material-ui/icons": "^4.9.1",
    "@react-native-community/async-storage": "~1.11.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/core": "^5.12.3",
    "@react-navigation/drawer": "^5.8.0",
    "@react-navigation/material-top-tabs": "^5.2.9",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.3",
    "axios": "^0.21.0",
    "css-tree": "1.0.0-alpha.39",
    "emoji-mart": "^3.0.0",
    "expo": "^38.0.0",
    "expo-av": "~8.2.1",
    "expo-camera": "~8.3.1",
    "expo-file-system": "~9.0.1",
    "expo-font": "~8.2.1",
    "expo-google-app-auth": "^8.1.0",
    "expo-image-picker": "~8.3.0",
    "expo-permissions": "~9.0.1",
    "expo-screen-orientation": "~1.1.1",
    "expo-updates": "^0.3.5",
    "gapi-client": "0.0.3",
    "googleapis": "^39.2.0",
    "lottie-react-native": "~2.6.1",
    "milsymbol": "^2.0.0",
    "mobx": "^6.0.1",
    "mobx-react": "^7.0.0",
    "modal-react-native-web": "^0.2.0",
    "navigation": "^5.3.1",
    "react": "16.11.0",
    "react-beautiful-dnd-grid": "^0.1.3-alpha",
    "react-dom": "16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-animated-loader": "0.0.8",
    "react-native-clear-app-cache": "^1.0.4",
    "react-native-draggable": "^3.3.0",
    "react-native-elements": "^2.3.2",
    "react-native-expo-viewport-units": "0.0.8",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-image-picker": "^0.28.0",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "^2.13.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-tab-view": "^2.14.4",
    "react-native-vector-icons": "^6.6.0",
    "react-native-viewport-units": "0.0.5",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^9.4.0",
    "react-navigation": "^4.3.9",
    "react-navigation-tabs": "^2.8.13"
  },

Is any of this packages is broken? I really need help. Thanks!

**Comment by cruzach** [comment]
Hi @NaamaShiponi , github issues are reserved for bugs in the Expo SDK, so I'm going to close this. Since you're looking for general programing help, I recommend using our [forums](https://forums.expo.io/) or [stackoverflow](https://stackoverflow.com/). That being said, I think the best thing for you to do is investigate this a little bit more yourself, [here's a couple starting points](https://docs.expo.io/workflow/debugging/) to help you out. Good luck debugging!
