### ISSUE TITLE
Calendar and Reminder Permission

### ISSUE THREAD

**Issue by shima93** [expo/expo#11684]
I am trying to use Expo-calendar in my project. I want to use the "Calendar.createEventAsync(calendarId, details)" which is working fine. However, my concern is about the Reminder-permission.
I use "Calendar.getDefaultCalendarAsync()" for getting the default calendar id and the I use "Calendar.createEventAsync()" method to just create an event in Calendar. I don't want to use Reminder, why do I need reminder permission(for ios)? 
is there any way that I can just ask for calendar permission for creating an event?

**Comment by brentvatne** [comment]
@lukmccall / @tsapeta - this appears to be related to https://github.com/expo/expo/pull/7928

if you run https://snack.expo.io/@notbrent/basic-calendar-usage on ios you will see "REMINDERS permission is required to do this operation." in logs

**Comment by lukmccall** [comment]
I'm a little bit confused about this issue. 

I've created a demo that should explain everything ;) 
https://snack.expo.io/@lukaszkosmaty/https:-github.com-expo-expo-issues-11684---demo

The one certain thing is that we have a bug in our documentation - to get all calendars you need to have all permissions or pass entity type to `Calendar.getDefaultCalendarAsync`.

On the screenshots, you can see, that I've managed to create a new calendar and event without reminders permission.
![image](https://user-images.githubusercontent.com/9578601/105170898-e808c480-5b1d-11eb-8b01-f2224e40dc54.png)
![image](https://user-images.githubusercontent.com/9578601/105170927-f3f48680-5b1d-11eb-8e81-317d12faed16.png)
![image](https://user-images.githubusercontent.com/9578601/105171003-05d62980-5b1e-11eb-920f-1cab2aaf5cf5.png)

**Comment by shima93** [comment]
It helped. Thank you
