### ISSUE TITLE
Error building for android

### ISSUE THREAD

**Issue by tusharkhatiwada** [expo/expo#1168]
I'm getting the following error (Screenshot Attached) after running **`exp build:android`**. It was running fine yesterday. I had successfully build multiple times for the same project. But now I'm getting the error:

<img width="1045" alt="screen shot 2017-12-27 at 4 21 30 pm" src="https://user-images.githubusercontent.com/5126590/34379238-66ae82d0-eb22-11e7-97c8-48193f39a022.png">

**Comment by terribleben** [comment]
Sorry about the trouble. It looks like `exp` from your machine was having a problem communicating with our build server. Can you check your internet connection or try switching to a different network? Let me know if it's still happening after that.

**Comment by tusharkhatiwada** [comment]
That could be the issue. It's working fine now. Thanks.
