### ISSUE TITLE
FileSystem.downloadAsync Crash / RedScreen

### ISSUE THREAD

**Issue by MikePodgorniy** [expo/expo#1169]
expo 23

I'm creating a caching layer for images. Application downloads a lot of files. Server doesn't response sometimes or responses with 404 status. I correctly process promise rejection of FileSystem.downloadAsync function, but sometimes app is crashed with red screen and error in native code.

![2017-12-27 12 53 05](https://user-images.githubusercontent.com/5052136/34379644-01b01898-eb05-11e7-9caf-faa18297ae90.png)

<img width="280" alt="2017-12-27 12 27 05" src="https://user-images.githubusercontent.com/5052136/34379426-ed7bf71c-eb03-11e7-9933-a2d5d94c6982.png">

> null: Error: Could not download from 'https://www.develop-labs.cf/staticus/glossary/v2/top100-glagolov_1510921572713.jpg?var=word_set'
code: "E_DOWNLOAD_FAILED"
domain: "NSURLErrorDomain"
framesToPop: 1
message: "Could not download from 'https://www.develop-labs.cf/staticus/glossary/v2/top100-glagolov_1510921572713.jpg?var=word_set'"
nativeStackIOS: Array(21) ["0   Exponent                            0x00000001…", "1   Exponent                            0x00000001…", "2   Exponent                            0x00000001…", …]
length: 21
__proto__: Array(0) [, …]
0: "0   Exponent                            0x0000000104fd17ed ABI23_0_0RCTJSErrorFromCodeMessageAndNSError + 80"
1: "1   Exponent                            0x0000000104f76310 __50-[ABI23_0_0RCTModuleMethod processMethodSignature]_block_invoke_2.194 + 98"
2: "2   Exponent                            0x0000000104ee0732 __89-[ABI23_0_0EXFileSystem downloadAsyncWithUrl:withLocalURI:withOptions:resolver:rejecter:]_block_invoke + 137"
3: "3   CFNetwork                           0x0000000110936454 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19"
4: "4   CFNetwork                           0x0000000110935cad __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147"
5: "5   Foundation                          0x000000010a52f22f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7"
6: "6   Foundation                          0x000000010a52f091 -[NSBlockOperation main] + 68"
7: "7   Foundation                          0x000000010a52d54e -[__NSOperationInternal _start:] + 778"
8: "8   libdispatch.dylib                   0x000000011210e1ba _dispatch_client_callout + 8"
9: "9   libdispatch.dylib                   0x0000000112113468 _dispatch_block_invoke_direct + 324"
10: "10  libdispatch.dylib                   0x000000011210e1ba _dispatch_client_callout + 8"
11: "11  libdispatch.dylib                   0x0000000112113468 _dispatch_block_invoke_direct + 324"
12: "12  libdispatch.dylib                   0x0000000112113304 dispatch_block_perform + 109"
13: "13  Foundation                          0x000000010a52955c __NSOQSchedule_f + 342"
14: "14  libdispatch.dylib                   0x000000011210e1ba _dispatch_client_callout + 8"
15: "15  libdispatch.dylib                   0x0000000112114134 _dispatch_continuation_pop + 500"
16: "16  libdispatch.dylib                   0x0000000112112996 _dispatch_async_redirect_invoke + 760"
17: "17  libdispatch.dylib                   0x0000000112118980 _dispatch_root_queue_drain + 568"
18: "18  libdispatch.dylib                   0x00000001121186ea _dispatch_worker_thread3 + 119"
19: "19  libsystem_pthread.dylib             0x00000001125cc1ca _pthread_wqthread + 1387"
20: "20  libsystem_pthread.dylib             0x00000001125cbc4d start_wqthread + 13"
stack: "Error: Could not download from 'https://www.develop-labs.cf/staticus/glossary/v2/top100-glagolov_1510921572713.jpg?var=word_set'
    at createErrorFromErrorData (/Users/mike/Documents/Work/App/.vscode/.react/main.bundle:2037:15)
    at /Users/mike/Documents/Work/App/.vscode/.react/main.bundle:1990:25
    at MessageQueue.__invokeCallback (/Users/mike/Documents/Work/App/.vscode/.react/main.bundle:2348:16)
    at /Users/mike/Documents/Work/App/.vscode/.react/main.bundle:2165:16
    at MessageQueue.__guard (/Users/mike/Documents/Work/App/.vscode/.react/main.bundle:2283:9)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (/Users/mike/Documents/Work/App/.vscode/.react/main.bundle:2164:12)
    at /Users/mike/Documents/Work/App/.vscode/.react/debuggerWorker.js:126:58
    at process.<anonymous> (/Users/mike/Documents/Work/App/.vscode/.react/debuggerWorker.js:35:9)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)"
userInfo: Object {NSLocalizedDescription: "The request timed out.", NSErrorFailingURLStringKey: "https://www.develop-labs.cf/staticus/glossary/v2/t…", NSErrorFailingURLKey: null, …}
_kCFStreamErrorCodeKey: -2102
_kCFStreamErrorDomainKey: 4
NSErrorFailingURLKey: null
NSErrorFailingURLStringKey: "https://www.develop-labs.cf/staticus/glossary/v2/top100-glagolov_1510921572713.jpg?var=word_set"
NSLocalizedDescription: "The request timed out."
NSUnderlyingError: Object {code: "-1001", message: "underlying error", nativeStackIOS: Array(22), …}
code: "-1001"
domain: "kCFErrorDomainCFNetwork"
message: "underlying error"
nativeStackIOS: Array(22) ["0   Exponent                            0x00000001…", "1   Exponent                            0x00000001…", "2   Exponent                            0x00000001…", …]
length: 22
__proto__: Array(0) [, …]
0: "0   Exponent                            0x0000000104fd17ed ABI23_0_0RCTJSErrorFromCodeMessageAndNSError + 80"
1: "1   Exponent                            0x0000000104fd19db ABI23_0_0RCTJSErrorFromCodeMessageAndNSError + 574"
2: "2   Exponent                            0x0000000104f76310 __50-[ABI23_0_0RCTModuleMethod processMethodSignature]_block_invoke_2.194 + 98"
3: "3   Exponent                            0x0000000104ee0732 __89-[ABI23_0_0EXFileSystem downloadAsyncWithUrl:withLocalURI:withOptions:resolver:rejecter:]_block_invoke + 137"
4: "4   CFNetwork                           0x0000000110936454 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19"
5: "5   CFNetwork                           0x0000000110935cad __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147"
6: "6   Foundation                          0x000000010a52f22f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7"
7: "7   Foundation                          0x000000010a52f091 -[NSBlockOperation main] + 68"
8: "8   Foundation                          0x000000010a52d54e -[__NSOperationInternal _start:] + 778"
9: "9   libdispatch.dylib                   0x000000011210e1ba _dispatch_client_callout + 8"
10: "10  libdispatch.dylib                   0x0000000112113468 _dispatch_block_invoke_direct + 324"
11: "11  libdispatch.dylib                   0x000000011210e1ba _dispatch_client_callout + 8"
12: "12  libdispatch.dylib                   0x0000000112113468 _dispatch_block_invoke_direct + 324"
13: "13  libdispatch.dylib                   0x0000000112113304 dispatch_block_perform + 109"
14: "14  Foundation                          0x000000010a52955c __NSOQSchedule_f + 342"
15: "15  libdispatch.dylib                   0x000000011210e1ba _dispatch_client_callout + 8"
16: "16  libdispatch.dylib                   0x0000000112114134 _dispatch_continuation_pop + 500"
17: "17  libdispatch.dylib                   0x0000000112112996 _dispatch_async_redirect_invoke + 760"
18: "18  libdispatch.dylib                   0x0000000112118980 _dispatch_root_queue_drain + 568"
19: "19  libdispatch.dylib                   0x00000001121186ea _dispatch_worker_thread3 + 119"
20: "20  libsystem_pthread.dylib             0x00000001125cc1ca _pthread_wqthread + 1387"
21: "21  libsystem_pthread.dylib             0x00000001125cbc4d start_wqthread + 13"
userInfo: Object {_kCFStreamErrorCodeKey: -2102, _kCFStreamErrorDomainKey: 4}
_kCFStreamErrorCodeKey: -2102
_kCFStreamErrorDomainKey: 4
__proto__: Object {__defineGetter__: , __defineSetter__: , hasOwnProperty: , …}
__proto__: Object {__defineGetter__: , __defineSetter__: , hasOwnProperty: , …}
__proto__: Object {__defineGetter__: , __defineSetter__: , hasOwnProperty: , …}
__proto__: Object {name: "Error", message: "", constructor: , …}
constructor: function Error() { … }
message: ""
name: "Error"
toString: function toString() { … }
__proto__: Object {__defineGetter__: , __defineSetter__: , hasOwnProperty: , …}

**Comment by terribleben** [comment]
Hi, the message you pasted is a rejection from `downloadAsync`, which suggests that maybe you aren't actually handling this case. Can you paste your code here (or produce a [snack](https://snack.expo.io/) which demonstrates the behavior)?

**Comment by MikePodgorniy** [comment]
Hi Ben, it looks like this:
```javascript
     FileSystem.downloadAsync(serverUri, correctUri)
      .then(fileInfo => {
        const { status, uri: localUri } = fileInfo;
        // console.log('Finished downloading to:', fileName); //, fileInfo);

        this.currentQueue = _.without(this.currentQueue, serverUri);
        if (status === 200) {
          this.actions.addImage(fileName, localUri);
          this.emitter.emit(`${ON_LOAD}_${fileName}`, { fileInfo, uri: serverUri, load: true });
        } else {
          this.emitter.emit(`${ON_LOAD}_${fileName}`, {
            uri: localUri,
            load: false,
            error: new Error(
              `Ошибка загрузки файла ${fileName}. Статус ответа: ${status}, LocalUri: ${localUri}, ServerUri: ${serverUri}`
            ),
          });
          FileSystem.deleteAsync(localUri, { idempotent: true });
        }
        this.loadNext();
      })
      .catch(error => {
        console.error(error);

        this.currentQueue = _.without(this.currentQueue, serverUri);
        this.emitter.emit(ON_LOAD, { uri: serverUri, load: false, error });
        this.loadNext();
      });
```

**Comment by terribleben** [comment]
What happens if you change your `console.error()` to a `console.log()` ?
