### ISSUE TITLE
Downloaded and Saved image md5's are not identical(iOS)

### ISSUE THREAD

**Issue by kemalsanli** [expo/expo#11703]
Hello,  i am trying to save image from url. I am using 'expo-file-system' for download and calculate md5 on iOS and for saving gallery i am using 'expo-media-library'.

Code for downloading and saving images:

```
      FileSystem.downloadAsync(
                  'https://homepages.cae.wisc.edu/~ece533/images/airplane.png',
                  FileSystem.documentDirectory + 'airplane.png',{md5:true}
                )
                  .then(({ uri , md5}) => {
                    console.log('Finished downloading to ', uri);
                    setImage(uri);
                    console.log("---downloaded file's md5------");
                    console.log(md5);
                    console.log("------------------------------");
                    MediaLibrary.saveToLibraryAsync(uri);
                  })
                  .catch(error => {
                    console.error(error);
                  });
```

Code for picking image from gallery:

```
const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync();
    console.log(result);

    if (!result.cancelled) {
      setImage(result.uri);
      console.log("------------gallery md5--------");
      console.log((await FileSystem.getInfoAsync(result.uri,{ md5: true })).md5);
      console.log("-------------------------------");
    }
  };
```

Image's md5 is 4ea4533aca1b28437caa793ff4dcf5ba but when i save image to my gallery md5 is changing to 4e03887a43c538205569878db90297cc

Log for better understanding

```
Finished downloading to  file:///Users/kemal/Library/Developer/CoreSimulator/Devices/438BC6C2-03E8-4A6B-96EC-3E25FEF09585/data/Containers/Data/Application/A1459006-1F2C-40E7-8AC6-076D4D0D8166/Documents/ExponentExperienceData/%2540anonymous%252FBilmiyorum-0af02265-da50-44c7-bfa2-ccec82cc1ed6/airplane.png
---downloaded file's md5------
4ea4533aca1b28437caa793ff4dcf5ba
------------------------------
Object {
  "cancelled": false,
  "height": 512,
  "type": "image",
  "uri": "file:///Users/kemal/Library/Developer/CoreSimulator/Devices/438BC6C2-03E8-4A6B-96EC-3E25FEF09585/data/Containers/Data/Application/A1459006-1F2C-40E7-8AC6-076D4D0D8166/Library/Caches/ExponentExperienceData/%2540anonymous%252FBilmiyorum-0af02265-da50-44c7-bfa2-ccec82cc1ed6/ImagePicker/BD676FC1-4ED6-4DC2-9F03-9666C835059D.png",
  "width": 512,
}
------------gallery md5--------
4e03887a43c538205569878db90297cc
-------------------------------

```

I downloaded image and saved to camera roll and i selected image with image picker to see md5 value.

For my app hashes must be identical and i couldn't find a workaround, I am not sure is this a bug or something different. 

Thanks in advance for any kind of answer or workaround...

**Comment by brentvatne** [comment]
it's not safe to assume that the returned image from expo-image-picker will be exactly identical to what you have saved in the media library, as you have identified here. notice the set of options available:

<img width="1165" alt="Screen Shot 2021-01-21 at 4 15 55 PM" src="https://user-images.githubusercontent.com/90494/105428294-f204f300-5c03-11eb-82ee-59ee9c348311.png">

see the implementation of handling a picked image: https://github.com/expo/expo/blob/master/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m#L249-L371

if you would like to get the identical image, you would need to create your own ui around expo-media-library, or you could open a feature request to have some alternative way to return the original image from this method on https://expo.canny.io/feature-requests
