### ISSUE TITLE
Barcode scanner doesn't trigger onBarCodeScanned on IOS

### ISSUE THREAD

**Issue by simo385** [expo/expo#11706]
### Summary of Issue 
In my app, I'd like to scan the barcodes. When i open up the camera, I see the barcode(simple EAN13) fine, but I unable to scan that.It seems the IPhone is blocked.

If I use Android, Barcode scanner works fine.

How can I solve the issue?

Thanks in advance,
Simone

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 4.0.1 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 10.3, macOS 10.12, tvOS 10.2, watchOS 3.2
      Android SDK:
        API Levels: 24, 25, 26
        Build Tools: 26.0.0
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 8.3.3/8E3004b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.5 => 39.0.5 
      react: ~16.13.0 => 16.13.1 
      react-dom: ~16.13.0 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2 
      react-native-web: ~0.13.13 => 0.13.18 
      react-navigation: ^4.3.1 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.0.1
    Expo Workflow: managed

I'm running the app on IPhone 6.

### Reproducible Demo

Install expo-barcode-scanner using the following guide https://docs.expo.io/versions/v39.0.0/sdk/bar-code-scanner/ 
and try to scan a barcode EAN13 with IPhone 6.

### Expected Behavior vs Actual Behavior
I expected the function in onBarCodeScanned is triggered, but it doesn't happend.

**Comment by byCedric** [comment]
Hi @simo385, thanks for writing in. Could you provide a reproducible example through [Snack](https://snack.expo.io/) or Github repo? With that we can investigate this behavior further.

**Comment by simo385** [comment]
Hi @byCedric ,

Snack: https://snack.expo.io/@simo3853/barcodescanner-issue-ios

Thanks in advance,
Simone

**Comment by alicansoysal** [comment]
Same here...

**Comment by simo385** [comment]
Hi everybody,

any updates?

thanks,
Simone

**Comment by kathawala** [comment]
I had the same issue just now and found this old forums post with the answer: https://forums.expo.io/t/ios-camera-barcode-scanner/17597

In my case, I had the following:

```tsx
      <BarCodeScanner
        barCodeTypes={['qr']}
        onBarCodeScanned={handleBarCodeScanned}
        style={styles.barcodeScanner}
      />
```

and I wasn't getting the bar code to scan. I set the barCodeTypes prop to undefined on ios and it worked:

```tsx
      <BarCodeScanner
        barCodeTypes={Platform.OS === 'ios' ? undefined : ['qr']}
        onBarCodeScanned={handleBarCodeScanned}
        style={styles.barcodeScanner}
      />
```

**Comment by simo385** [comment]
Dear @kathawala,

I had the following: `barCodeTypes={['ean13', 'ean8', 'code128']}`

and I changed as follows: `barCodeTypes={Platform.OS === 'ios' ? undefined : ['ean13', 'ean8', 'code128']}`

now it works!

Many thanks for your support,
Simone
