### ISSUE TITLE
[iOS] Audio recorder doesn't work for other file extensions

### ISSUE THREAD

**Issue by riwu** [expo/expo#1170]
https://snack.expo.io/@riwu/audio-recorder
I modified https://github.com/expo/audio-recording-example to change the `extension` and `outputFormat` to
```
        extension: '.amr_wb',
        outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_AMR_WB,
```
then `prepareToRecordAsync` failed with `Error: Prepare encountered an error: recorder not created.`.

**Comment by sjchmiela** [comment]
It seems that although there are many output formats defined both in [Expo Audio docs](https://docs.expo.io/versions/latest/sdk/audio.html#outputformat--1) and in [Apple docs and source code](https://developer.apple.com/documentation/coreaudio/core_audio_data_types/1572096-audio_data_format_identifiers), iOS is not capable of encoding recordings in all of these formats.

The (most probably) proper lists of supported entities are here: [codecs](https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/CoreAudioOverview/CoreAudioEssentials/CoreAudioEssentials.html#//apple_ref/doc/uid/TP40003577-CH10-SW26), [audio file formats](https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/CoreAudioOverview/CoreAudioEssentials/CoreAudioEssentials.html#//apple_ref/doc/uid/TP40003577-CH10-SW57).

Unfortunately, @riwu, AMR-WB isn't among them, so iOS won't be able to record and save sound into this format.

@terribleben, should we update the source code and remove unsupported values or update documentation to point developers to these documents?

**Comment by nappels** [comment]
@sjchmiela It doesn't seem to work even with supported codecs and file formats, other than `.caf`.

I'm trying to save an audio file as `.mp3`, and have these recording settings for ios:

```
ios: {
      extension: '.mp3',
      outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEGLAYER1,
      audioQuality: Audio.RECORDING_OPTION_IOS_AUDIO_QUALITY_MIN,
      sampleRate: 44100,
      numberOfChannels: 2,
      bitRate: 128000,
      linearPCMBitDepth: 16,
      linearPCMIsBigEndian: false,
      linearPCMIsFloat: false,
    }
```

On call to `prepareToRecordAsync()`, I get this error: `Error: Prepare encountered an error: recorder not created`.

In fact, in every codec/file extension combo I've tried other than `extenstion: '.caf'`, I get the same error.

Is there a specific combo that I'm missing, or is it just not possible to save an audio file on ios that doesn't have the `.caf` extension?

**Comment by sjchmiela** [comment]
> iOS contains the recording codecs listed in Table 2-5. As you can see, neither MP3 nor AAC recording is available. This is due to the high CPU overhead, and consequent battery drain, of these formats. ([source](https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/CoreAudioOverview/CoreAudioEssentials/CoreAudioEssentials.html#//apple_ref/doc/uid/TP40003577-CH10-SW26))

So yeah, only `.caf` and maybe some `.lbc` and other even less used formats may be supported by iOS. 😕

**Comment by riwu** [comment]
@nappels did you call `Expo.Audio.setAudioModeAsync` to enable `allowsRecordingIOS`?

I have gotten it working for a few file extensions. 
The working config I'm currently using:
```
          ios: {
            ...Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY.ios,
            extension: '.wav',
            outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_LINEARPCM,
            sampleRate: 16000,
            bitRateStrategy:
              Audio.RECORDING_OPTION_IOS_BIT_RATE_STRATEGY_CONSTANT,
          },
```

**Comment by nappels** [comment]
Ok great I got it. I'm using this now:

```
ios: {
      extension: '.m4a',
      outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_APPLELOSSLESS,
      audioQuality: Audio.RECORDING_OPTION_IOS_AUDIO_QUALITY_MIN,
      sampleRate: 44100,
      numberOfChannels: 2,
      bitRate: 128000,
      linearPCMBitDepth: 16,
      linearPCMIsBigEndian: false,
      linearPCMIsFloat: false,
    }
```

Would be nice to know which extension/outputFormat combinations are valid for each device, instead of just listing every possible value in the docs.

**Comment by terribleben** [comment]
I've pushed a change to our docs which clarifies the supported iOS formats and provides those links to the Apple docs. The change will go live next time we deploy our docs.
