### ISSUE TITLE
[video][ios] Using src attribute on Video player causes unmounting crashes

### ISSUE THREAD

**Issue by superplussed** [expo/expo#11719]
I have an app in beta and I was tracking crash reports, I was getting some crashes on iOS (none on Android) with each release related to the video player. My app has lots of small videos that get loaded and unloaded in various contexts, sometimes with overlapping sound effects and/or audio recording. 

The error was:

```Cannot form weak reference to instance (0x282109380) of class EXAVPlayerData. It is possible that this object was over-released, or is in the process of deallocation.```

I found a solution to the problem, and wanted to write it here in case anyone else has the same problem. When I was getting the crash, I was using the "source" attribute on the Video component. But when I moved the loading to a store using loadAsync, and also called an explicit unload on componentWillUnmount using unloadAsync (of course wrapped in a try...catch), the crashes stopped.

It might be that this is just working as intended, and advanced usage should never be using the "source" attribute in the first place but thought I would share in case it trips anyone else up.

**Comment by MrXyfir** [comment]
@superplussed You sound knowledgeable on this issue so forgive me for hijacking this thread to ask you a question. Have you ran into the issue where a video's sounds continue to play _after_ the component has unmounted? So there's no video (or you're watching a different video) but you still hear the sound of the previous video(s) playing? It only happens occasionally in production builds for me and I can't figure it out.

**Comment by mtroskot** [comment]
@superplussed I'm also having this issue, can you maybe put some code example how did you fix this ?

**Comment by MrXyfir** [comment]
@mtroskot Could you please update here if you find a solution? It's not exactly my same issue but it might still help.

**Comment by mtroskot** [comment]
@MrXyfir  Here's the solution

`  const videoRef = useRef<Video>(null);
  const playbackInstance = useRef<Video>(null);

  const videoRef = useRef<Video>(null);

  useEffect(() => {
    loadVideo();
  }, [source]);

  const loadVideo = async () => {
    if (source && videoRef.current) {
      await unloadVideo();
      await videoRef.current.loadAsync(source);
      await videoRef.current.setStatusAsync({ shouldPlay: true, isLooping: true, isMuted: true, volume: 0 });
    }
  };

  async function unloadVideo() {
    if (videoRef.current !== null) {
      await videoRef.current.unloadAsync();
    }
  }

  return (
      <Video ref={videoRef} style={styles.video} useNativeControls={false} volume={0} resizeMode={'cover'} />
  );`

**Comment by MrXyfir** [comment]
@mtroskot Unfortunately that doesn't solve my issue but I do appreciate you sharing your solution. Thanks!

**Comment by mtroskot** [comment]
@MrXyfir what issue do you have ?

**Comment by jackblackCH** [comment]
As mentioned, don't change the src itself, rather use `player.loadAsync({uri: 'your_source'})`. Works like a charm.
