### ISSUE TITLE
Expo.Notifications.cancelAllScheduledNotificationsAsync() isn't reliably asynchronous

### ISSUE THREAD

**Issue by fiber-god** [expo/expo#1171]
On iOS, calling that function returns `undefined`, and seems to run in a synchronous fashion, but on Android, it returns a promise and works asynchronously as planned.

To work around this, in my Reason app (sdk24) I'm binding the function as so:
```ocaml
 [@bs.scope "Notifications"] [@bs.module "expo"]
    external cancelAllScheduledNotifications : unit => unit =
      "cancelAllScheduledNotificationsAsync";
    [@bs.scope "Notifications"] [@bs.module "expo"]
    external cancelAllScheduledNotificationsAsync : unit => Js.Promise.t(unit) =
      "cancelAllScheduledNotificationsAsync";
```

and calling them later in this function like this:
```ocaml
let cancelNotifications = (self, callback) =>
  switch Platform.os {
  | Platform.IOS =>
    Expo.Notifications.cancelAllScheduledNotifications() |> ignore;
    self.ReasonReact.reduce(() => UnsetNotification, ());
    callback()
  | Platform.Android =>
    Js.Promise.(
      Expo.Notifications.cancelAllScheduledNotificationsAsync()
      |> then_(
           () =>
             {
               self.ReasonReact.reduce(() => UnsetNotification, ());
               callback()
             }
             |> resolve
         )
      |> ignore
    )
  };
```

My use case is that before setting a new local notification, I clear out any old/stale ones. On iOS, running it in a synchronous fashion gets the job done and on android I have to handle it as a promise. Handling it on iOS as a promise explodes the app.

I hope this can be a quick fix for you folks so that you can work on the bigger things you have planned :)

-- Juwan

**Comment by terribleben** [comment]
It looks like this was implemented synchronously at the native level, and then sometime later, somebody came in and wrapped it in a JS api and wrote `async` without actually checking that the method was async.

**Comment by terribleben** [comment]
Fix will ship with SDK 25
