### ISSUE TITLE
Custom sound doesn't work when is set in a channel

### ISSUE THREAD

**Issue by CarlosDanielPG** [expo/expo#11713]
### Summary of Issue 
I have tried adding a custom sound to my notifications using a .wav file by following this reference:
https://docs.expo.io/versions/latest/sdk/notifications/#setting-custom-notification-sounds-on-android
However, when you build the application to android and test using expo.io/notifications, the notification sound arrives as the default sound of the physical device.

I have a folder in the root called assets and inside another called sounds, inside I have the file, and the code with which I configure the channel is the following:

src/screens/Login.js
`
if(Platform.OS === 'android') {
          Notifications.setNotificationChannelAsync('new-orders', {
            name: 'Orders notifications',
            importance: Notifications.AndroidImportance.HIGH,
            sound: '../../assets/sounds/cash-register-purchase.wav'
          })
        }
`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
    npmPackages:
      expo: ^38.0.0 => 38.0.10
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.3.9 => 4.4.3
    Expo Workflow: managed

### Reproducible Demo
`
const registerForPushNotifications = async () => {
      ...
        if(Platform.OS === 'android') {
          Notifications.setNotificationChannelAsync('new-orders', {
            name: 'Orders notifications',
            importance: Notifications.AndroidImportance.HIGH,
            sound: '../../assets/sounds/cash-register-purchase.wav', // <- for Android 8.0+, see channelId property below
          })
        }
      }
    }
`

### Expected Behavior vs Actual Behavior
Play custom sound when recieve a notification to the channel vs Default sound when recieve a notification to the channel

**Comment by CarlosDanielPG** [comment]
@byCedric any idea of this bug? Or is my error?

**Comment by cruzach** [comment]
@CarlosDanielPG the Expo push notification service does not support custom sounds yet. As the docs state, the only available values for the `sound` field are `'default' | null` and it is iOS only- https://docs.expo.io/push-notifications/sending-notifications/#message-request-format


If you'd like to use custom sounds in your notifications, you'll either need to use local notifications, or send notifications directly with APNs or FCM, [which we have a guide for here](https://docs.expo.io/push-notifications/sending-notifications-custom/)
