### ISSUE TITLE
Error when using `expo-location` in Android: Invalid regular expression: unmatched parentheses

### ISSUE THREAD

**Issue by cjhines** [expo/expo#11716]
### Summary of Issue 
As soon as a I use an instance of `expo-location`, starting via `npm run android` causes metro to crashing during AppRegistry.

```
SyntaxError: Invalid regular expression: unmatched parentheses

Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

I've tried checking `metro-config` [as suggested here](https://stackoverflow.com/questions/58120990/how-to-resolve-the-error-on-react-native-start) but to no avail.

### Environment
```
  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: bare
```

### Reproducible Demo

This code never gets called, it just crashes once metro begins handling the bundle.

```
import * as Location from 'expo-location';

export const getLocation = () =>
  new Promise((resolve) => {
    Location.requestPermissionsAsync().then(({ status }) => {
      if (status === 'granted') {
        Location.getCurrentPositionAsync({})
          .then((location) => resolve(location));
      }
    });
  });
```
 
### Steps to Reproduce

- Install expo bare on existing RN project
- Use the `expo-location` import.
- `npm run android`

**Comment by byCedric** [comment]
Hi @cjhines, thanks for writing in. Did you follow the installation steps required to install this module in plain React Native projects? These are listed in [`expo-location`](https://github.com/expo/expo/tree/master/packages/expo-location#installation-in-bare-react-native-projects) and of course [our guide to install unimodules](https://docs.expo.io/bare/installing-unimodules/). The missing `AppRegistry` points to an error within your unimodules setup.
```
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
``` 

If you think this is done properly, could you provide a small repository where this issue happens? With that, we would be able to investigate this issue.

Hope this helps!

**Comment by cjhines** [comment]
@byCedric 

This was the issue. Some weird interaction between Intl and expo.

https://github.com/expo/expo/issues/6536
