### ISSUE TITLE
Super simple app will not launch on Android tablet or emulator, works fine on iOS

### ISSUE THREAD

**Issue by ksnyder** [expo/expo#11723]
### Steps to Reproduce
Create a new app from expo-cli 4.0.17 running on macOS Catalina and add a TouchableOpacity component, then try to run it on a Lenovo Tab 4 Plus, 8" with Android 7.1.1 and a fresh install of the Expo client from the Play store.  Or, try to run it on the Pixel_3a_API_30_x86 emulator.

### Expected Behavior vs Actual Behavior
Expect the app to launch and work, as it does on iPhone 12.  Instead there is a crash that says “java.lang.String cannot be cast to java.lang.Boolean”.  A few times on the tablet, in addition to the error screen, there was a window that showed the app, but nothing was clickable and the app was non-responsive.  Most of the time this does not appear and only the error screen shows up.  I have attached a screenshot of the error screen from the emulator.
<img width="1196" alt="Screen Shot 2021-01-22 at 2 44 53 PM" src="https://user-images.githubusercontent.com/182565/105559786-f0e8ca00-5cc6-11eb-8ee0-bc4a216d9326.png">

**Comment by brentvatne** [comment]
please share this app. we cannot guess what may be causing this error without some code to reproduce it, please fill out the "Reproducible Demo" part of this report

react-native android is more strict about validating types, so it seems you are probably using a boolean somewhere where a string is expected.

closing the issue until the template is completed
