### ISSUE TITLE
Expo- Lottie-React-native error/bug

### ISSUE THREAD

**Issue by AJITESH3210** [expo/expo#11729]
TypeError: _reactNative.Platform.select(...) is not a function[
![Capture](https://user-images.githubusercontent.com/64904115/105621739-db8faf00-5e30-11eb-94cd-3f3ce5505767.PNG)
](url)

Same issue is in WEB and ANDROID

**Comment by AdamJNavarro** [comment]
Hey @AJITESH3210, please follow our issue template and fill out all the required information. Once you've done so, we can re-open this issue and investigate it properly.
