### ISSUE TITLE
Auth session uri format incompatible 

### ISSUE THREAD

**Issue by andrewnaeve** [expo/expo#1172]
Example format: https://auth.expo.io/@username/your-app-slug

On Coinbase, adding the result of AuthSession.getRedirectUrl() to "permitted callback uris" results in:
"Redirect uri Invalid redirect uri". 

Stripping the @ symbol bypasses the error on coinbase, but breaks the flow everywhere else. 

Probably a coinbase issue, but seems like compatibility would be generally improved by using a link without special symbols?

any ideas for getting around this?

**Comment by terribleben** [comment]
It sounds like you're right, but pinging @brentvatne to sanity check since he knows the most about this API's expected behavior.

**Comment by andrewnaeve** [comment]
@brentvatne suggested in Slack using WebBrowser to get around this. Unfortunately, the '+' symbol is no good either, making testing in development impossible until I can actually use a named scheme in production to get the Linking.addEventListener callback to fire. Unless I've missed something glaring. 

This is definitely on Coinbase, but just thought I'd make you aware of it. 

Thanks for the support! Its always a major selling point of Expo.

**Comment by brentvatne** [comment]
so Coinbase doesn't let you use + or @ in your redirect urls? In this case I would set up some proxy url (basically what Expo AuthSession web urls do for you) that works with whatever format that Coinbase lets you use and redirects you into a format that works for the Expo app

**Comment by brentvatne** [comment]
here's a very simple example of an express backend that just redirects to an `exp` endpoint. you could have different endpoints depending on the environment that you're using your coinbase app in https://github.com/expo/examples/blob/648fc8fb2d625d0c60beb9455952189a270db69b/with-facebook-auth/backend/index.js
