### ISSUE TITLE
Apple pay doesn't support in real device.

### ISSUE THREAD

**Issue by prasidhda** [expo/expo#11730]
### Please note that discussions opened as issues in the core Expo repository will be closed.

With the simulator, the "Apple pay" was working fine, but with the real devices it throws an error saying not supported. 

Would you please direct me to the right path. This is the first time I am trying to publish the app to the App store and here I am stuck with no clue whatsoever 

Thanks.

**Comment by AdamJNavarro** [comment]
Hey @prasidhda, please make sure you've followed the steps described here: https://docs.expo.io/versions/v40.0.0/sdk/payments/#enabling-apple-pay-in-bare

If you encounter more issues, please feel free to head to our [Forums](forums.expo.io) and we can discuss further there! (We try to reserve Github issues for reproducible and actionable bug reports)

Cheers,
Adam
