### ISSUE TITLE
EXCamera requires minimum iOS version of 11.0

### ISSUE THREAD

**Issue by thisisgit** [expo/expo#11733]
Hi, I'm trying to install Expo Camera on my bare React Native project and I'm getting this error on `npx pod-install`:
```
[!] CocoaPods could not find compatible versions for pod "EXCamera":
  In Podfile:
    EXCamera (from `../node_modules/expo-camera/ios`)

Specs satisfying the `EXCamera (from `../node_modules/expo-camera/ios`)` dependency were found, but they required a higher minimum deployment target.
```

And after I updated CocoaPods to 1.10.1, I'm getting following warning:
```
[!] The platform of the target `project` (iOS 10.0) may not be compatible with `EXCamera (10.0.0)` which has a minimum requirement of iOS 11.0.

[!] The platform of the target `projectTests` (iOS 10.0) may not be compatible with `EXCamera (10.0.0)` which has a minimum requirement of iOS 11.0.
```

So updating platform :ios, '10.0' -> platform :ios, '11.0' in Podfile solves the issue, but this [page](https://docs.expo.io/bare/installing-unimodules/) shows that the minimum version is set to 10.0 and started to wonder if minimum required version to use EXCamera is intentionally set to 11.0. I couldn't find any document or issue referring about this.

Should I set it to 11.0 to use Expo Camera or is it some kind of bug?

**Comment by AdamJNavarro** [comment]
Hey @thisisgit, this is dependent on what version of expo-camera you use. With the latest version, support for iOS 10 has been dropped. See the changelog: https://github.com/expo/expo/blob/master/packages/expo-camera/CHANGELOG.md#-breaking-changes-1

Cheers,
Adam
