### ISSUE TITLE
Background fetch never works on iOS

### ISSUE THREAD

**Issue by srikanthkh** [expo/expo#11731]
### Summary of Issue 
I tried multiple examples of Background fetch but nothing seem to work on iOS. Is it supposed to work on iOS without Location?
Checked literally every conversation that happened about this on every medium possible but did not see a single resolution/ example that work. Please can someone share a simple example that works?

I tried this one as well but does not work either.
https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/BackgroundFetchScreen.tsx

![image](https://user-images.githubusercontent.com/7452893/105624925-5083ca00-5dda-11eb-9473-a060a2c2de71.png)

**Comment by AdamJNavarro** [comment]
Hey @srikanthkh, could you please elaborate on what you mean by "never works"? What, explicitly, is happening or not happening? Also, let's direct this conversation to a [Forum](forums.expo.io) post. (We try to reserver Github issues for reproducible and actionable bug reports.

Cheers,
Adam
