### ISSUE TITLE
expo certificate

### ISSUE THREAD

**Issue by elhsoufiane** [expo/expo#11732]
hi,
how i can force expo to run with the certificate i create 
with to command expo:start web --https expo not seem use my certificate i create in the webpack.config.js
what is going wrong?

**Comment by AdamJNavarro** [comment]
Hey @elhsoufiane, please make a [forum post](https://forums.expo.io/c/expo-web/21) so we can discuss further. We try to reserve github issues for reproducible and actionable bug reports.

Cheers,
Adam
