### ISSUE TITLE
uglify-es 3.3 causes `Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')`

### ISSUE THREAD

**Issue by w-** [expo/expo#1173]
Issue is actually this one
https://github.com/facebook/react-native/issues/17348

Created this expo issue because Expo maintains and suggests it's own version of React Native.

**Symptoms:**
Executing workflows on simulator work fine but if you publish and run your app inside the expo app it will crash with no error message on the same workflow.

If you are lucky expo might report the following error
> Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')

**Workaround:**
Two workarounds described in issue above.

i applied the solution of adding `"resolutions": { "uglify-es": "3.2.2" }` to my package.json but that didn't work.

I had to manually edit subscribables.js line 33 and make this change.
`this._subscribableSubscriptions && this._subscribableSubscriptions.forEach`

I wasted 4 hours or so trying to figure this out ='(

**Comment by kadoshms** [comment]
Same for me! exact same error

**Comment by anp** [comment]
Hi! So sorry it took you so much time to sort this out. We do maintain a fork of React Native, but it looks like the uglify-es dependency is actually specified in [Metro](https://github.com/facebook/metro), which we don't fork. From reading the various threads, it seems like Metro 0.24 (which is going to be the version specified for RN 0.52) has a more relaxed uglify dependency and should resolve this temporarily.

In the meantime, it seems like specifying an exact version under `resolutions` is the best workaround.

**Comment by cowai** [comment]
Adding the resolutions to package.json does not work. The wrong version is still installed.

**Comment by kadoshms** [comment]
@cowai try to follow this guide https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352 and then publish, helped me.
