### ISSUE TITLE
"Certificate doesn't have password." with `exp build:ios --local-auth -c`

### ISSUE THREAD

**Issue by felipemillhouse** [expo/expo#1174]
I have been trying to build for iOS lately but no luck, It's work just android. Help me please

MacFelipe:findmyshade FelipeSantos$ exp build:ios --local-auth -c
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? *************
? Password? **********
? What is your Apple Team ID (you can find that on this page: https://developer.
apple.com/account/#/membership)? *****************
[exp] Creating Certificates...
[exp] Starting build process...
[exp] Unable to find an existing exp instance for this directory, starting a new one...
[exp] Starting React Native packager...
[exp] Scanning folders for symlinks in /Users/FelipeSantos/Desenvolvimento/findmyshade/node_modules (20ms)
[exp] Loading dependency graph.
[exp] Dependency graph loaded.
[exp] Tunnel connected.
[exp] Publishing...
[exp] Building iOS bundle
[exp] Finished building JavaScript bundle in 35057ms.
[exp] Building Android bundle
[exp] Finished building JavaScript bundle in 32876ms.
[exp] Analyzing assets
[exp] Finished building JavaScript bundle in 30615ms.
[exp] Finished building JavaScript bundle in 30818ms.
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://exp.host/@felipemillhouse/findmyshade

[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] You can monitor the build at

 https://expo.io/builds/d54a8f04-9520-4e73-8f8d-74b6f434adce

[exp] Alternatively, run `exp build:status` to monitor it from the command line.
MacFelipe:findmyshade FelipeSantos$ exp build:status
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build.
MacFelipe:findmyshade FelipeSantos$ 

### I still have another app in revew at iTunes Connect, can this be?

**Comment by felipemillhouse** [comment]
app.json

{
  "expo": {
    "name": "FindMyShade",
    "description": "Encontrando as cores que combinam com você.",
    "slug": "findmyshade",
    "sdkVersion": "24.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "icon": "./assets/icon1024.png",
    "splash": {
      "image": "./assets/splash.png",
      "backgroundColor": "#1c232d"
    },
    "ios": {
      "bundleIdentifier": "br.com.felipesantos.findmyshade"
    },
    "android": {
      "package": "br.com.felipesantos.findmyshade",
      "versionCode": 1.0
    }
  }
}

**Comment by aaronduino** [comment]
I'm having the same problem.

For me, watchman crashes every time, causing macos to show the "watchman quit unexpectedly" dialog.

**Comment by felipemillhouse** [comment]
Well... I think the solution is eject. I've tried everything, my App is pretty simple, it was not supposed to be happening

**Comment by fxfactorial** [comment]
@felipemillhouse Hi, can you upgrade your install of exp to the latest? 

And then `$ exp build:ios -c` to clear your creds. There is no more `--local-auth`.

**Comment by aaronduino** [comment]
@fxfactorial I just upgraded to the version released a few minutes ago, and it works!

I have been trying to get this to build for 6 hours now, and I'm extremely excited that it finally built successfully.

**Comment by aaronduino** [comment]
@fxfactorial May I ask what fixed it or which commit?

**Comment by fxfactorial** [comment]
Lots of different little things, moving parts. The new default moved all authing to client away from our servers, so we don't have your apple ID or password anymore.

**Comment by felipemillhouse** [comment]
Great!!!! but... Do you know what this?

MacFelipe:findmyshade FelipeSantos$ exp build:ios -c
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Removed existing credentials
? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? **********
? Password? **********
[exp] Validating Credentials...
[exp] You have 1 teams
Only 1 team associated with your account, using Team ID: **********
? Will you provide your own Distribution Certificate? Let Expo handle the proces
s
? Will you provide your own Push Certificate? Let Expo handle the process
[exp] Error while gathering & validating credentials
[exp] Reason:Unknown reason, raw:"Could not find app with bundle id 'br.com.felipesantos.findmyshade'"
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by fxfactorial** [comment]
@felipemillhouse are you on `47.3.5`? exp should be making this app ID for you.

**Comment by felipemillhouse** [comment]
Yeah @fxfactorial 
MacFelipe:findmyshade FelipeSantos$ exp --version
47.3.5
MacFelipe:findmyshade FelipeSantos$

**Comment by fxfactorial** [comment]
Okay, I have reproducible case, will fix. Thank you for your patience.

**Comment by felipemillhouse** [comment]
@fxfactorial.... Just for you to know, exp build:android works, the problem is just not ios.

**Comment by fxfactorial** [comment]
@felipemillhouse appreciate your patience here, can you try on `47.3.6`

**Comment by felipemillhouse** [comment]
MacFelipe:findmyshade FelipeSantos$ exp build:status
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: Build in progress...

@fxfactorial You the man! You the fu** man guy!!! Thanks a lot and happy new year.
