### ISSUE TITLE
[expo-yarn-workspaces] AppDelegate.h:2:9: 'EXUpdates/EXUpdatesAppController.h' file not found

### ISSUE THREAD

**Issue by benallfree** [expo/expo#11741]
## 🐛 Bug Report

Hi, I hope someone can help me troubleshoot this. `expo-updates` has been hoisted to the root `node_modules`, and even though there is a symlink in my project folder's node_modules, it still is not finding this file.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo bare workflow

**Comment by brentvatne** [comment]
please share a https://stackoverflow.com/help/minimal-reproducible-example

**Comment by TMiller00** [comment]
@benallfree did you find a resolution to this issue?
