### ISSUE TITLE
[expo-updates] "directory" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by akivanov** [expo/expo#11744]
### Summary of Issue 
when I'm trying to launch `react-native run-ios` in a bare workflow with `expo-updates` dependency, I run into the error:
```
Error: Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. The "directory" argument must be of type string. Received undefined
    at /Users/.../project/node_modules/expo-updates/scripts/createManifest.js:27:11
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: bare
```

**Comment by akivanov** [comment]
Solved. Just needed to add `export ENTRY_FILE=index.ts` in 'Build Phases' / 'Bundle React Native code and images' script, since my project doesn't have `index.js` file.

**Comment by LeonardoDrici** [comment]
To me the suggested fix above didn't work, but renaming `index.ts` to `index.js` seems to have fixed the issue

**Comment by giautm** [comment]
For anyone, who used `expo-yarn-workspaces`; It must be:
```
export ENTRY_FILE=./__generated__/AppEntry.js
```

**Comment by tevonsb** [comment]
This may be obvious, but do we want to export this from the PATH or does this go somewhere in Xcode?

**Comment by darcien** [comment]
> This may be obvious, but do we want to export this from the PATH or does this go somewhere in Xcode?

@tevonsb not sure if you already got your answer, but it's in Xcode.

Open your project with Xcode > Left navigator, double click on your app > Targets, select your app > "Build Phases" tab > In "Bundle React Native code and images" step > Add `ENTRY_FILE` export before the scripts.

<details><summary>Screenshot</summary>
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/19742419/113866844-fdfe5b00-97d7-11eb-8de5-acaee3162b92.png"></details>

Anyway, regarding this issue, I encountered this issue from a fresh bare Expo project inside a yarn workspaces.

```
$ expo diagnostics

  Expo CLI 4.3.4 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.5.3 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /Users/darcien/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react-native: ~0.63.4 => 0.63.4
    Expo Workflow: bare
```
