### ISSUE TITLE
Wrong check for project structuring in react-native-modules

### ISSUE THREAD

**Issue by mishsom** [expo/expo#11756]
### Wrong check for project structuring in react-native-modules 

Nearly all the modules in expo have checks similar to below,

```
if (new File(rootProject.projectDir.parentFile, ‘package.json’).exists()) {
apply from: project(":unimodules-core").file("…/unimodules-core.gradle")
} else {
throw new GradleException(
"‘unimodules-core.gradle’ was not found in the usual React Native dependency location. " +
“This package can only be used in such projects. Are you sure you’ve installed the dependencies properly?”)
}
```
in expo-file-system build.gradle file,
this check is wrong as hybrid apps can have react project anywhere.

### Reproducible Demo

Keep project structure as following and build breaks:

Android Project
    -- React-native-modules
    --android-module-1
    --other-modules

In such kind of structure(which can arise in hybrid apps that adopted react-native later)
 

### Expected Behavior vs Actual Behavior
actual:- project fails to build due to above check
expected:- build should pass and take the path of node_modules maybe as config

**Comment by brentvatne** [comment]
please share a project that we can run to reproduce this issue

**Comment by mishsom** [comment]
Please find sample implementation here: 
https://github.com/mishsom/ReactNativeDemoWithCustomFolder

**Comment by mishsom** [comment]
Also had a relevant discussion on expo forums:
https://forums.expo.io/t/unimodules-install-on-react-native-hybrid-app/47147

**Comment by brentvatne** [comment]
@tsapeta - curious what you think about this

**Comment by brentvatne** [comment]
one possible workaround could be to symlink files to the location that they are expected to be in. i think this may be reasonable, and it should unblock you to structure your project however you like.

**Comment by mishsom** [comment]
@brentvatne I might be wrong, but that involves creating a symlink outside the project directory in my case, that seems a bit unreliable for a build system that would be /opt and it would require root access to create symlinks. I did make it work by placing a dummy file outside on my local but was not able to sell the idea to other developers of the android and ios team.

**Comment by mishsom** [comment]
Will this be taken up by the team, there are libraries that depend on expo-based libs, I think it becomes critical for maintainers to look into this issue.

For example, I am trying to use https://github.com/gre/gl-react/tree/master/packages/gl-react-native, and it depends on `react-native-unimodules`.

**Comment by brentvatne** [comment]
this isn't a priority for us right now, we are very busy working on our sdk 41 release and various services. we're open to suggestions on how to improve it. you should be able to use `patch-package` to make any changes that you need to work around this for now.

**Comment by mishsom** [comment]
@brentvatne is there someone who can just help me with a basic understanding as to why these checks were placed? My issue is there are just too many packages in expo that have the same or similar checks and it would be difficult to work with so many patched packages. Ideally, this check should not be there only.

Thanks for addressing and replying :-)

**Comment by brentvatne** [comment]
because the unimodules-core gradle file adds some configuration to each of these modules: https://github.com/expo/expo/blob/master/packages/@unimodules/core/unimodules-core.gradle

**Comment by mishsom** [comment]
As far as I understood from the above code, the check is not required :-(

**Comment by tsapeta** [comment]
Hey @mishsom! Yeah, I agree that this check should be fixed for custom project structures, or maybe even removed. However, we can't just do that because this file needs to be included in those `build.gradle` files.
Right now we're really busy with SDK41 release, but after that I'd like to come back to #11593 where, for sure, I'll cover your use case.
