### ISSUE TITLE
[ios] Unhandled JS Exception: Can't find variable: require

### ISSUE THREAD

**Issue by viraatdas** [expo/expo#11758]
This is regarding a react native/react native web project. 

Whenever I run `expo start --ios`, the iOS simulator throws me 

```
Unhandled JS Exception: Can't find variable: require

http://127.0.0.01:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:5:24
global code@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:701:3
```

This is my `.babelrc`

```
{ 
  "presets": [
      "@babel/preset-env", 
      "@babel/preset-react", 
      "module:metro-react-native-babel-preset",
      ["es2015", { "modules": false }]
    ],

    "plugins": [
      "@babel/plugin-proposal-class-properties", 
      "@babel/plugin-proposal-object-rest-spread",
      "@babel/transform-flow-strip-types",
      "@babel/transform-runtime"
    ],

    "sourceMaps": true
}

```

Any help on this issue will be greatly appreciated. Thanks!

**Comment by byCedric** [comment]
Hi @viraatdas, thanks for writing in. Unfortunately, I'm not sure where this error is coming from. I tried using your exact babel configuration, and that seems to work just fine on my end (with an exception of the `es2015`, [which is deprecated and replaced by `@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-es2015/)). 

I would recommend taking a look [at this github thread](https://github.com/facebook/react-native/issues/21048#issuecomment-425642199), they seem to provide some ways to recover from this exact error. If that doesn't help, please open a new issue report with a reproducible example so we can investigate this further.

Hope this helps!
