### ISSUE TITLE
[docs] [expo-notifications] Custom iOS sound in expo-notifications?

### ISSUE THREAD

**Issue by abelfiore** [expo/expo#11761]
In the [expo-notifications documentation](https://docs.expo.io/versions/latest/sdk/notifications/), it describes how to add custom sounds for Android, but not iOS. I have tried setting the sound property of scheduleNotificationAsync, but have had no luck. Can the documentation confirm that this is possible? And if it is, any tips on how to get this to work (e.g. sound file types supported).

**Comment by cruzach** [comment]
This is only supported in the bare workflow, and the question was answered [here](https://forums.expo.io/t/playing-a-custom-sound-for-local-notificaitons/45606/7)

**Comment by abelfiore** [comment]
Is there an expected timeframe for this to be supported in the managed workflow?

**Comment by cruzach** [comment]
No timeframe yet, probably something we'll look into once EAS Build fully supports managed projects
