### ISSUE TITLE
exp build:ios references Android

### ISSUE THREAD

**Issue by ShMcK** [expo/expo#1176]
Not a serious issue, but the ios build process logs "Building Android bundle", though it seems no build actually occurs.

```
exp build:ios

---

[exp] Loading dependency graph.
[exp] Dependency graph loaded.
[exp] Tunnel connected.
[exp] Publishing...
[exp] Building iOS bundle
[exp] Finished building JavaScript bundle in 31947ms.
[exp] Building Android bundle
```

**Comment by ccheever** [comment]
When you build for either platform, we'll republish your JavaScript and bundle it with that built app. Whenever we publish, we generate the JS for both iOS and Android because we always want those to be in sync.

That's why you are seeing something about Android here.
