### ISSUE TITLE
Convert ExpoWebBrowser to use ASWebAuthenticationSession instead of the deprecated SFAuthenticationSession

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#11769]
### Summary of Issue 

> we may want to convert ExpoWebBrowser to use ASWebAuthenticationSession instead of the deprecated SFAuthenticationSession since it has a prefersEphemeralWebBrowserSession setting ...

https://github.com/expo/expo/pull/11753

We also should just do it because it's the new preferred API for the use case

**Comment by jarvisluong** [comment]
This looks like an interesting task. I have some project using expo-auth-session and it would be nice to always use up-to-date API 😁

**Comment by tajetaje** [comment]
Yeah, being able to set `prefersEphemeralWebBrowserSession` would be great for unsupported flows like SAML (I have to pass an auth token through query parameters).

**Comment by brentvatne** [comment]
this was done in https://github.com/expo/expo/commit/59836aab8caace709414516068cca24ccbbed41e

to be rolled out in sdk 45

**Comment by tajetaje** [comment]
> this was done in [59836aa](https://github.com/expo/expo/commit/59836aab8caace709414516068cca24ccbbed41e)
> 
> to be rolled out in sdk 45

If that is the case, then the SDK 45 docs need an update
See "On iOS" under https://docs.expo.dev/versions/v45.0.0/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl-options
