### ISSUE TITLE
" Go" suffix was added to appName

### ISSUE THREAD

**Issue by phaffonso** [expo/expo#11778]
After upgrading Expo SDK version from 39 to 40, my application name got a "Go" suffix when building through managed workflow (android, appBundle/.aab).

app.json: 
  "expo": {
    "name": "MedKit",
    "slug": "MedKit",
...

On Android home screen (after installed), my app now shows as "MedKit Go". Previously, it was just "MedKit" as intended.

**Comment by cruzach** [comment]
When did you build your app? This was a bug, but we've since deployed a fix for it, so if you rebuild your app you should be good to go

**Comment by phaffonso** [comment]
That build was about 3 days ago. If the bug is fixed, great! When was this fix deployed? Tomorrow our next build will be available for testing so I can check if this problem persists. Thank you very much for your attention!

**Comment by cruzach** [comment]
It was fixed 2 days ago- https://forums.expo.io/t/go-is-added-to-the-end-of-the-application-name/47968/4

**Comment by brentvatne** [comment]
precisely: tuesday, january 26th at 6:15am

**Comment by phaffonso** [comment]
Great! Thanks for the information
