### ISSUE TITLE
Camera.recordAsync hangs and crashes the app when app is backgrounded on Android

### ISSUE THREAD

**Issue by gyoung-panopto** [expo/expo#11777]
**Summary**

When recording a video with Camera.recordAsync in the expo-camera package, the app hangs and crashes when the app goes into the background on Android devices. According to the documentation the recording is supposed to stop gracefully, and it does on iOS. But on Android the app crashes.

Additionally, an "ApplicationNotResponding" in android.media.MediaRecorder stop function error is sent to Sentry logs.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

39

**Environment**

  Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.0.0 => 4.4.2 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

Here's a minimal snack that reproduces the issue:

https://snack.expo.io/bCN908FMZ

Just run the app, hit "Record", then put the app in the background.

Note that this reproduces in the same way both when managed in the Expo app and when in bare workflow.

**Comment by marco2216** [comment]
Same issue here

**Comment by RookieIndieDev** [comment]
Not sure if this has been fixed in a newer version but even in expo 48, this bug still persists.
