### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by expjess** [expo/expo#11774]
**Summary**

This is so awesome

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

Too bad this can't be required depending on the workflow answer

**Environment**

Hello, world.

**Reproducible demo or steps to reproduce from a blank project**

This is AMAZING!

**Comment by brentvatne** [comment]
👏
