### ISSUE TITLE
Cellular from expo-cellular not working on iOS / TestFLight

### ISSUE THREAD

**Issue by pors** [expo/expo#11788]
**Summary**

In an app deployed on TestFlight (and also in Expo Go) the Cellular object returns only null data.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.2
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.56 => 0.12.56
      expo: ^40.0.1 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2
      react-native-web: ~0.14.10 => 0.14.10
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

import * as Cellular from 'expo-cellular';
console.log(Cellular);

Returns:

Object {
  "CellularGeneration": Object {
    "0": "UNKNOWN",
    "1": "CELLULAR_2G",
    "2": "CELLULAR_3G",
    "3": "CELLULAR_4G",
    "CELLULAR_2G": 1,
    "CELLULAR_3G": 2,
    "CELLULAR_4G": 3,
    "UNKNOWN": 0,
  },
  "allowsVoip": true,
  "carrier": null,
  "getCellularGenerationAsync": [Function getCellularGenerationAsync],
  "isoCountryCode": null,
  "mobileCountryCode": null,
  "mobileNetworkCode": null,
}

**Comment by ide** [comment]
Is the device using a cellular data connection?

**Comment by pors** [comment]
Yes

**Comment by IdoLevi235** [comment]
That issue happens at my app also.
In android - Cellular returns the correct data

**Comment by pors** [comment]
Can confirm this is still an issue with SDK 41 on iOS. Works fine on Android!

**Comment by dlenskyi** [comment]
Same for me on iOS

**Comment by EvanBacon** [comment]
Looks like the fix for this has landed in #12710
