### ISSUE TITLE
Typescript:  Subscription type is not accessible

### ISSUE THREAD

**Issue by allan-simon** [expo/expo#11783]
**Summary**

I'm using  expo-notifications with typescript 

In order to please the typechecker ,  I'm trying to adapt the example code here 

https://docs.expo.io/versions/latest/sdk/notifications

```
import * as Notifications from 'expo-notifications';

      const notificationListener = useRef();                  
      const responseListener = useRef();
```

As they're supposed to be ref holding a  Subscription, I'm trying to do
```
      const notificationListener = useRef<Notifications.Subscriptions>();                  
      const responseListener =useRef<Notifications.Subscriptions>();
```

but with no luck, which is weird because at the opposite 

```
const [notification, setNotification] = useState<Notifications.Notification>();
```

works, and the documentation https://docs.expo.io/versions/latest/sdk/notifications/#subscription clearly state the type is exported 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.3 environment info:
    System:
      OS: Linux 5.10 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.20.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.10 - /usr/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

```
import Constants from 'expo-constants';
import React, { useState, useEffect, useRef } from 'react';
import { WebView } from 'react-native-webview';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import {StatusBar, Platform} from 'react-native';
import * as Notifications from 'expo-notifications';


Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function App() {

    const [notification, setNotification] = useState<Notifications.Notification>();
    const notificationListener = useRef<Notifications.Subscription>();
    const responseListener = useRef();


    useEffect(() => {
        registerForPushNotificationsAsync().then((token: string) => console.log(token));

        // This listener is fired whenever a notification is received while the app is foregrounded
        notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
            setNotification(notification);
        });

        // This listener is fired whenever a user taps on or interacts with a notification (works when app is foregrounded, backgrounded, or killed)
        responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
            console.log(response);
        });

        return () => {
            Notifications.removeNotificationSubscription(notificationListener);
            Notifications.removeNotificationSubscription(responseListener);
        };
    }, []);


    console.log(notification);

    return (
        <SafeAreaProvider>
            <StatusBar backgroundColor="#0000D1"/>
            <SafeAreaView style={{height: '100%'}}>
                <WebView source={{ uri: 'https://app-production.rosaly.info' }}/>
            </SafeAreaView>
        </SafeAreaProvider>
    );
}

async function registerForPushNotificationsAsync() {
    if (!Constants.isDevice) {
        throw new Error('Must use physical device for Push Notifications');
    }
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
        const { status } = await Notifications.requestPermissionsAsync();
        finalStatus = status;
    }
    if (finalStatus !== 'granted') {
        throw new Error('Failed to get push token for push notification!');
    }

    const token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log(token);

    if (Platform.OS === 'android') {
        Notifications.setNotificationChannelAsync('default', {
            name: 'default',
            importance: Notifications.AndroidImportance.MAX,
            vibrationPattern: [0, 250, 250, 250],
            lightColor: '#FF231F7C',
        });
    }

    return token;
}

```

**Comment by jarvisluong** [comment]
Hi! I think you can get the `Subscription` type from `@unimodules/core`. I did a dive from the `expo-notification` implementation and it was from the above mentioned package. An interesting though here is if the `Subscription` type is also exported from `expo-notification`? 🤔

**Comment by cruzach** [comment]
That type is indeed from `@unimodules/core`, as you can see [here](https://github.com/expo/expo/blob/master/packages/expo-notifications/src/NotificationsEmitter.ts). The type is not exported from `expo-notifications` right now

**Comment by cruzach** [comment]
For an example of using the Subscription type from @unimodules/core, please refer to this file- https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/NotificationScreen.tsx

**Comment by mercpls** [comment]
Any update on this?

I'm getting a typescript error
`Type 'Subscription' is not assignable to type 'undefined'.`
`Argument of type 'undefined' is not assignable to parameter of type 'Subscription'.` 

What types do I import and from where? Because the github example linked has changed in the short time since this was /answered/. How can I go about importing this?

**Comment by mtakac** [comment]
@fabarea you can now import it as `import { Subscription } from 'expo-modules-core';`.

**Comment by mrcMesen** [comment]
> For an example of using the Subscription type from @unimodules/core, please refer to this file- https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/NotificationScreen.tsx

Thanks this works to me!

**Comment by iM-GeeKy** [comment]
As of `"expo": "^52.0.0-preview.0"` I'm seeing `Module '"expo-modules-core"' has no exported member 'Subscription'` and per the [usage](https://docs.expo.dev/versions/latest/sdk/notifications/#usage) and initial issue `Notifications.Subscription` is not accessible. Is there any workaround?

**Comment by du5rte** [comment]
> has no exported member 'Subscription'

Hi @iM-GeeKy I just came across the same, if you inspect `Notifications.addNotificationReceivedListener` you can see it's now returning `Notifications.EventSubscription`, renamed it and worked.
```
const notificationListener = useRef<Notifications.EventSubscription>();
```

Also if you're using `Notifications.removeNotificationSubscription` you might need to check for undefined.
```
if (notificationListener.current) Notifications.removeNotificationSubscription(notificationListener.current);
```

Hope it helped

**Comment by iM-GeeKy** [comment]
@du5rte Yeah, I had figured it out and forgot to share the fix. Thanks for posting that!
