### ISSUE TITLE
[expo-local-authentication] cancelLabel option in android

### ISSUE THREAD

**Issue by schmru** [expo/expo#11781]
**Summary**

Android not showing cancel label

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

38.0.8

**Environment**

 System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: 38.0.8 => 38.0.8 
      react: ~16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: 0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.3
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

LocalAuthentication.authenticateAsync({
promptMessage: ${getTranslation('BiometricLoginAs')} ${credentials},
cancelLabel: getTranslation(‘LoginAsDifferentUser’)
}
).then…

Hello, I have posted this question on forum ([link](https://forums.expo.io/t/localauthentication-android-cancellabel/47987)) already but didn't get any answers, so I've post it here also. I have implemented LocalAuthentication for my app and it works as expected on iOS, but on A Android I don’t see cancelLabel (the button to cancel). Is this because Android has back button or am I missing something?
I’ve tested on multiple devices so it is not device problem.

LocalAuthentication.authenticateAsync({
promptMessage: ${getTranslation('BiometricLoginAs')} ${credentials},
cancelLabel: getTranslation(‘LoginAsDifferentUser’)
}
).then…

Thanks for any help.

**Comment by alexstanbury** [comment]
I had to set `disableDeviceFallback` to `true` in order for this to show. I'm having a lot of issues with this package so far!
