### ISSUE TITLE
Highest supported device resolution cannot current be achieved using Camera module

### ISSUE THREAD

**Issue by irtemed88** [expo/expo#1178]
I originally filed this ticket on the react-native-camera project, but I believe that library as well as the Camera component in Expo share much of the same logic. Copying over here in case the integration needs to occur within Expo:

https://github.com/react-native-community/react-native-camera/issues/1066

If filing a ticket this way is not appropriate, feel free to close this ticket and I can open another with the issue spelled out here rather than linking to another project. Thanks!

**Comment by aalices** [comment]
@irtemed88 the flag you mention was the solution for another issue you opened: #1103 . What do you mean by opening this one? Is it a request for the resolution toggle?

**Comment by irtemed88** [comment]
Sorry for the confusion! It was pretty late when I filed this and I left off a few details 😅... Allow me to elaborate.

1) Yes I was thinking it might be worthwhile to have a toggle for the flag in case consumers of the Expo Camera API don't want the highest resolution. I can't think of a concrete example where you wouldn't want the highest resolution, but maybe there is one?

2) I do think it would be nice to be able to set the quality of AVCaptureSession.sessionPreset like react-native-camera currently supports. Using `AVCaptureSession.sessionPreset = .high` with the resolution toggle set to 'true' will yield a lower resolution image than what would be provided if `AVCaptureSession.sessionPreset = .photo`. 

I tested this by downloading the AVCam-iOS sample code from Apple and taking two separate photos with the front facing camera. One with sessionPreset set to .photo and the other .high (`isHighResolutionPhotoEnabled` is set to true when capturing a photo).

The resulting images were 1932×2576 and 720×1280 on my iPhone 6s respectively. I think this means to get the highest resolution possible we need to have a way to modify sessionPreset?

Sample code here: https://developer.apple.com/library/content/samplecode/AVCam/Introduction/Intro.html

**Comment by aalices** [comment]
I tried to play around with `Photo` session preset but it leads to crash, I am not yet sure why. So at this moment only low/medium/high is possible. We could think of adding this quality prop but we also need to "convert" this to Android as there are no such presets - all we can do is setting a lower resolution to decrease the quality. 

A current workaround is to use `ImageManipulator` to resize the taken photo (to a smaller one) but I assume we can't get the highest res photo without the `Photo` preset. Quite a mystery why it crashes 🤔

**Comment by irtemed88** [comment]
Do you mean the AVCam sample code is crashing for you? I was able to download it and run without an issue. If you send me the crash log I'd be happy to take a look and see if I can send you a sample project that works.

For Android, react-native-camera uses the `getSupportedPictureSizes` API on android.hardware.Camera to determine which resolution to set for a given captureQuality. See [RCTCameraView.java](https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraView.java).

They switch on the `captureQuality` prop and for low, medium, and high they iterate over the supported sizes on Android to find the best value (see methods `setCaptureQuality` and `getBestSize`). I think that's a decent approach and might be more efficient from a perf/memory consuption perspective than capturing a high quality photo and downsizing. That said, it definitely seems more involved than a 1:1 mapping of prop to native API 😕.

**Comment by aalices** [comment]
we chatted a bit and created a request if there's any one else interested: https://expo.canny.io/feature-requests/p/capturequality-prop-for-camera-component
