### ISSUE TITLE
Google app store constantly rejecting the app for location permissions

### ISSUE THREAD

**Issue by dennisbouwpas** [expo/expo#11797]
Expo SDK: 40
Expo CLI: 4.1.3
Workflow: Managed.

Rejection message from Google
----
Remove the ACCESS_BACKGROUND_LOCATION permission from your app APK or app bundle.
If you’re using ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION, examine your code paths and restrict usage to foreground purposes only. (learn more)
You should no longer see the Location declaration listed in console under App Content.
----

But I don't use location permission across the project.
The previous 6 versions of the app were accepted.
And now I'm completely frustrated....

Permissions I use In the project
`"permissions": [
        "CAMERA",
        "USE_FINGERPRINT",
        "USE_BIOMETRIC",
        "VIBRATE",
        "READ_PHONE_STATE",
        "com.google.android.c2dm.permission.RECEIVE",
        "com.anddoes.launcher.permission.UPDATE_COUNT",
        "com.majeur.launcher.permission.UPDATE_BADGE",
        "com.google.android.providers.gsf.permission.READ_GSERVICES",
        "com.sonyericsson.home.permission.BROADCAST_BADGE",
        "com.htc.launcher.permission.READ_SETTINGS",
        "com.htc.launcher.permission.UPDATE_SHORTCUT",
        "com.sec.android.provider.badge.permission.READ",
        "com.sec.android.provider.badge.permission.WRITE"
      ],`

**Comment by komelabbbas** [comment]
Same issue...
Any solution..?
Please help.
I have tried many times but fail unfortunately,😓

**Comment by dennisbouwpas** [comment]
You should delete all your .apk and .aab from google.console and then upload a new version without permissions, expo SDK 40 should help with that.
