### ISSUE TITLE
@unimodules/core dependency conflict between `expo-gl` and `expo-localiztion`

### ISSUE THREAD

**Issue by jedahan** [expo/expo#11790]
**Summary**

I cannot have expo-gl and expo-localization in a project without npm install failing, supposedly due to conflicting peer dependencies.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS, Web

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.6.0 - /opt/homebrew/bin/node
      npm: 7.4.0 - /opt/homebrew/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

```shell
expo init --npm --yes
npm install expo-gl expo-localization
```

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @unimodules/core@6.0.0
npm ERR! node_modules/@unimodules/core
npm ERR!   @unimodules/core@"~6.0.0" from expo@40.0.1
npm ERR!   node_modules/expo
npm ERR!     expo@"~40.0.0" from the root project
npm ERR!   peer @unimodules/core@"*" from expo-application@2.4.1
npm ERR!   node_modules/expo-application
npm ERR!     expo-application@"~2.4.1" from expo@40.0.1
npm ERR!     node_modules/expo
npm ERR!       expo@"~40.0.0" from the root project
npm ERR!   2 more (expo-location, expo-gl)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! expo-localization@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @unimodules/core@5.1.2
npm ERR! node_modules/@unimodules/core
npm ERR!   peer @unimodules/core@"~5.1.2" from expo-localization@10.0.0
npm ERR!   node_modules/expo-localization
npm ERR!     expo-localization@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by brentvatne** [comment]
```
expo install expo-localization expo-gl
```

**Comment by jedahan** [comment]
Same issue with `expo install`
```
 ▲ expo install expo-localization expo-gl
Installing 2 SDK 40.0.0 compatible native modules using npm.
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @unimodules/core@6.0.0
npm ERR! node_modules/@unimodules/core
npm ERR!   @unimodules/core@"~6.0.0" from expo@40.0.1
npm ERR!   node_modules/expo
npm ERR!     expo@"~40.0.0" from the root project
npm ERR!   peer @unimodules/core@"*" from expo-application@2.4.1
npm ERR!   node_modules/expo-application
npm ERR!     expo-application@"~2.4.1" from expo@40.0.1
npm ERR!     node_modules/expo
npm ERR!       expo@"~40.0.0" from the root project
npm ERR!   2 more (expo-location, expo-gl)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! expo-localization@"~9.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @unimodules/core@5.1.2
npm ERR! node_modules/@unimodules/core
npm ERR!   peer @unimodules/core@"~5.1.2" from expo-localization@9.1.0
npm ERR!   node_modules/expo-localization
npm ERR!     expo-localization@"~9.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/micro/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/micro/.npm/_logs/2021-01-29T21_32_11_399Z-debug.log
```

**Comment by brentvatne** [comment]
please use npm <= 6 or yarn for now. npm 7 has behavior around peer dependencies that is likely to cause lots of problems for react-native projects, we need to do some work to accommodate it better

**Comment by jedahan** [comment]
Cool, thanks for the info.

Not sure where it would fit in the documentation, but maybe a line like

> We support Node LTS, as per the [Node Release Guideline](https://nodejs.org/en/about/releases/)

somewhere would help.

---

I could also see settings the engines variables in package.json, and throwing a warning while running expo commands on unsupported versions of node/npm.

If you think these are useful, I can submit them as separate feature requests. LMK and I think this issue can be closed after.

**Comment by brentvatne** [comment]
@jedahan - we try to support the latest version where possible but sometimes a new version is released and it takes some time to catch up. in our [installation docs](https://docs.expo.io/get-started/installation/#1-expo-cli) we ask for "Node.js LTS release or greater" and we manually validate in https://github.com/expo/expo-cli/blob/7c098b88ca32a71dfa9da5d9450901d86652ce38/packages/expo-cli/bin/expo.js#L14-L19 - but we missed some npm 7 issues it seems.

if you're curious, there's a long thread with info about npm 7 peer dependency changes here, which i engaged in earlier today after reading this issue: https://twitter.com/ruyadorno/status/1357383518901460993

**Comment by ipakhomov** [comment]
For those who experience problems with dependencies after upgrading to NPM 7 try to install dependencies with [--legacy-peer-deps](https://docs.npmjs.com/cli/v7/commands/npm-install#configuration-options-affecting-dependency-resolution-and-tree-design) flag: `npm  i --legacy-peer-deps`. This may help until npm 7 issues fixed.

**Comment by rodneyrehm** [comment]
So that `expo upgrade --npm` wouldn't fail  I've added a local `.npmrc` with the following content to my project:

```
# expo and react-native don't cope well with npm v7 yet
legacy-peer-deps=true
```
