### ISSUE TITLE
Android: There was an error with this build

### ISSUE THREAD

**Issue by vageeshs** [expo/expo#1179]
Build ID: 8d5606e9-71b3-4d79-aa69-3ad03282e28d 
How can I get more details as to what the issue?. I don't see any other details other than the message there was an error with this build. 
Thanks

**Comment by ccheever** [comment]
Hi-

Did you get a URL where you can see the logs?
Something that would look like:
https://expo.io/builds/d54a8f04-9520-4e73-8f8d-74b6ffffff

or something like that?

**Comment by vageeshs** [comment]
Thanks for looking into this. 
No, I didn't get any callback URL like that .. this is what I see

....$ exp build:android
[exp] There is a new version of exp available (47.2.2).
You are currently using exp 46.0.6
Run `npm install -g exp` to get the latest version
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Starting build process...
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://exp.host/@nanapro/nana-pro

[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: 99b78c02-d942-4c1e-9833-7904cf495243
[exp] Run `exp build:status` to monitor it.

...$ exp build:status
[exp] There is a new version of exp available (47.2.2).
You are currently using exp 46.0.6
Run `npm install -g exp` to get the latest version
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] Android: There was an error with this build.

**Comment by ide** [comment]
Hi, you can find the logs by putting the build ID into a URL like this: https://expo.io/builds/99b78c02-d942-4c1e-9833-7904cf495243.

This is the error in the logs:
```
AAPT: libpng error: Not a PNG file
Error: Some file crunching failed, see logs for details
```

It looks like one of your image assets (perhaps your app icon) is expected to be a PNG file but isn't. You may want to try re-encoding the image as a valid PNG file.

**Comment by vageeshs** [comment]
Thanks ide. Weird! had tried https://expo.io/builds/8d5606e9-71b3-4d79-aa69-3ad03282e28d which failed. May be it takes some time to serve the log over the web?
