### ISSUE TITLE
error: unknown option `--variant'

### ISSUE THREAD

**Issue by patricklongo1** [expo/expo#11798]
Hello!

Im trying use EXPO Updates, but i cant run my project as Release mode.

im trying the follow comand:
npm run android --variant Release

from documentation:
https://docs.expo.io/versions/latest/sdk/updates/

but im getting follow error:
error: unknown option `--variant'

same error with yarn.
same error with "configuration" instead "variant"

"expo": "~38.0.8",
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",

![image](https://user-images.githubusercontent.com/51893683/106394851-942f9280-63dd-11eb-9d24-d175b5b3837c.png)

![image](https://user-images.githubusercontent.com/51893683/106394868-add0da00-63dd-11eb-80ff-d5852dc28874.png)

tks for any help!

**Comment by byCedric** [comment]
Hi @patricklongo1! There is a small difference between the managed and bare workflow.

- **Bare workflow** only uses the `@react-native-community/cli` library to manage building native/js. This contains the `--variant` property to switch the standalone build (apk/ipa) to a certain mode. You can use it like `yarn react-native run-android --variant Release`.
- **Managed workflow** doesn't have the concept of a debug apk, that's just the Expo Go app. Although you can build a standalone version for the simulator with Expo. To switch between production and development mode in the managed workflow, [check this doc](https://docs.expo.io/workflow/development-mode/#production-mode) out.

Hope this helps!
