### ISSUE TITLE
[expo-av][iOS] didJustFinish called twice

### ISSUE THREAD

**Issue by mtroskot** [expo/expo#11792]
**Summary**
Sometimes code in didJustFinish block get's called twice. This happens when progressUpdateInterval is less than 200ms and changes after each audio.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 21, 26, 28, 30
        Build Tools: 28.0.3, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 16.9.0 => 16.9.0 
      react-native: 0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

```
const progressUpdateInterval = useMemo(() => {
    const updateInterval = 100 + 30 * Math.ceil(Math.max(0, liveWorkoutStore.audioPlayableDuration - 6) / 5);
    return updateInterval
  }, [liveWorkoutStore.audioPlayableDuration, liveWorkoutStore.chapterIndex]);

onSoundPlaybackStatusUpdate = (status: IAVPlaybackStatus) => {
    try {
      if (status.isPlaying) {
        this.props.onProgress({
          currentTime: millisecondsToSeconds(status.positionMillis),
          playableDuration: millisecondsToSeconds(status.playableDurationMillis),
          seekableDuration: millisecondsToSeconds(status.playableDurationMillis),
        });
      }
      if (status.didJustFinish) {
        this.props.onAudioEnd();
      }
    } catch (error) {
      console.log('onSoundPlaybackStatusUpdate', error);
    }
  };

```

**Comment by Razorholt** [comment]
The fullscreen callback is also called twice...

**Comment by rZinnatov** [comment]
Hey! Just faced this issue. Did by any chance anyone found the fix or workaround?
