### ISSUE TITLE
`addNotificationResponseReceivedListener` on SDK40 with app in background

### ISSUE THREAD

**Issue by mairasala** [expo/expo#11791]
**Summary**

addNotificationResponseReceivedListener doesn't fire when app is in background.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40

**Environment**

Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 23.0.1, 23.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3, 30.0.1
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

Fetch the Expo token from the app
https://snack.expo.io/@maysala/fa51ad
Send a push notification with expo notification tool using the token to channelId "myChannel"
click on the notification

If the app is killed, an Alert will display the data information from the notification
If the app is in the background, no Alert is displayed.

I've been struggling for a while now with receiving `addNotificationResponseReceivedListener` events when the app is in background. 

It is fired when I interact with the notification, launching the app, if it was fully killed. However, if the app is in background, sometimes the event is fired and sometimes it isn't, when bringing the app to foreground. I am declaring the listener outside of the component and still no luck.

In the same way, the `useLastNotificationResponse` is fired on the same scenarios, not always.

Is there some minimal interval between the notifications for it to work? With expo publish it never functions, only eventually with built apps.

**Comment by jurica-penjgusic** [comment]
I had problems with that also.
Setting   _displayInForeground to true seems to solve my problems.

**Comment by cruzach** [comment]
<img width="1138" alt="Screen Shot 2021-02-01 at 9 54 33 AM" src="https://user-images.githubusercontent.com/35579283/106475017-7e6cac80-6473-11eb-9a18-96b8bea8f82f.png">

have you configured your app.json as above @mairasala ?

**Comment by mairasala** [comment]
Yes.

**Comment by cruzach** [comment]
I think the issue is with `Alert` here, if you change it to console log, you can see it is triggered (whether you are tapping on the notification while the app is foregrounded or background)- https://snack.expo.io/@charliecruzan/11791

**Comment by mairasala** [comment]
yes you are quite right, the issue seems to be from the Alert instead.
Thanks!
