### ISSUE TITLE
create project fail

### ISSUE THREAD

**Issue by zeffon** [expo/expo#118]
<img width="499" alt="2017-04-18 08 09 52" src="https://cloud.githubusercontent.com/assets/4590967/25110539/79721562-2417-11e7-9abc-e24e786cf73d.png">
This is my first expo project.But i can't create successfully.I have try lots of times.

**Comment by ide** [comment]
Do you know if your computer is able to connect to Amazon S3? That is where the project templates are hosted.

**Comment by zeffon** [comment]
Thanks.
I try to visit the site https://aws.amazon.com/s3/, but response status code is 503.I am in a bad network.
