### ISSUE TITLE
[docs] Some Constants.manifest fields are not available until update is downloaded when building managed app on EAS Build

### ISSUE THREAD

**Issue by ajgrover** [expo/expo#11808]
**Summary**

Based on the discussion in https://github.com/expo/sentry-expo/issues/168, it seems that EAS build is using a version of the bare workflow rather than the managed workflow. This isn't clear from the docs and following the instructions on the normal [Constants doc page](https://docs.expo.io/versions/latest/sdk/constants/) results in a standalone build that crashes on startup because `Constants.manifest.extra` is null.

I was able to fix the crash by switching to using the implementation described [here](https://docs.expo.io/build-reference/variables/) but this page isn't obvious to find and the crash is difficult to debug since it only happens on standalone builds. I didn't test if following the bare workflow instructions on the first page would resolve the issue as well.

I think that at the very least the docs on the Constants page should be updated to reflect the fact that the steps detailed there won't work on EAS as written. Happy to make a PR for that change if desired.

**Link to the related docs page**

https://docs.expo.io/versions/latest/sdk/constants/

**Comment by ajgrover** [comment]
cc @allan-simon

**Comment by brentvatne** [comment]
hi there,

indeed when you do a managed app build on EAS Build it is converted to a bare app and then built.

with EAS Build for managed and bare apps, `Constants.manifest` **will not be available when you first build**.  we moved away from requiring developers to run `expo publish` before building, so there isn't actually an "update manifest" available at that time. once you download an update on your build, a manifest will be available. ([more info in this post](https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf))

longer term, we would like to remove `Constants.manifest` and make this more clear by having folks depend on `Updates.manifest` instead.

for sdk 41, i think we should do a couple things:

1. update the type of `Constants.manifest`

https://github.com/expo/expo/blob/master/packages/expo-constants/src/Constants.types.ts#L120

this should be `manifest?: AppManifest;` and we should mark it as deprecated, and suggest developers use [`Updates.manifest`](https://docs.expo.io/versions/latest/sdk/updates/#updatesmanifest) instead.

2. update the api reference to clarify the behavior of the `Constants.manifest` and `Updates.manifest`

**Comment by ajgrover** [comment]
Got it, I think this can be resolved in the short term by updating [this line](https://docs.expo.io/versions/latest/sdk/constants/#installation) to say `bare React Native app or using EAS Build`. I tried to make a PR but it seems like those install instructions are autogenerated or something so I can't just update the markdown.
<img width="466" alt="Screen Shot 2021-02-01 at 14 12 05" src="https://user-images.githubusercontent.com/3088615/106524545-90604680-6497-11eb-8056-a5e7129acf03.png">

It might also be helpful to state some version of your comment on the [EAS Limitations page](https://docs.expo.io/build-reference/limitations/) so that it's clear that you might need to follow bare workflow instructions.

**Comment by brentvatne** [comment]
@ajgrover - i'm hesitant to add any more about this currently because we already say "Managed workflow support is early, not recommended for production." in the limitations page

**Comment by ajgrover** [comment]
up to you of course! my experience as a user: I followed what I believed to be the canonical way to add environment variables and ended up with a crash that took me the better part of a week to debug. I had read the limitations page but it wasn't clear what exactly was happening under the hood.

I think this could have been avoided by exposing some of this context on either page. Might be best to do that on the Limitations page so that it's centralized. But my issue is solved now so whatever you think is best 👍🏽

**Comment by brentvatne** [comment]
my concern is that this would just be a game of whack a mole - this is the issue that you encountered, but there are maybe a hundred more that could have caused you similar problems depending on what you are using in your app. maybe the best approach here is for us to more strongly discourage use of eas build with managed apps right now. it is not our intention for people to be using eas build with managed apps at the moment

**Comment by allan-simon** [comment]
ok so if we want to build a managed app we have to resort to normal expo:build ?

**Comment by brentvatne** [comment]
@allan-simon - yes

**Comment by brentvatne** [comment]
@ajgrover - what sdk version were you using here?

**Comment by ajgrover** [comment]
@brentvatne 39

**Comment by brentvatne** [comment]
@ajgrover - oh ok, you can actually update to sdk 40 and this will work. we updated expo-constants to be available in bare apps in sdk 40

**Comment by ajgrover** [comment]
got it, i switched to using [this approach](https://docs.expo.io/build-reference/variables/) and the build is working fine on EAS for me now as well.

**Comment by allan-simon** [comment]
> @allan-simon - yes, until we roll out preview of managed builds on eas build, which we're aiming for in the next few months

thanks for the info, yes indeed it will be a deal breaker for me, as a solo developer, not from the  mobile world, in a small company sticking to managed workflow is a safe harbor , especially as I don't have a mac. Waiting for that I will use bitrise who seems to compile fine (but does not have the niceties of creating for me all the needed stuff on the apple developer website )

**Comment by brentvatne** [comment]
@allan-simon - you can just use `expo build:ios` for managed apps - you don't need to use `eas build` right now. https://docs.expo.io/distribution/building-standalone-apps/

**Comment by allan-simon** [comment]
but it seems the expo build:ios is much much bigger no ? (when i tried i got a 120mb ipa instead of 20mb something when doing eas build ? )

**Comment by allan-simon** [comment]
(and it was nothing more than a hello world with webview and sentry-expo )

**Comment by brentvatne** [comment]
120mb is not the actual size on the app store. https://expo.fyi/managed-app-size

**Comment by allan-simon** [comment]
ah nice :)  
one last thing (sorry to hijack this thread :/ ) was that on with expo build:ios  i was only having a development .ipa , and on eas:build i had a ad-hoc ipa (the big difference for me was that, not having a mac,  I was apple to give the ad-hock eas build link to the iphone of my coworker and he was able to install it, while the development ipa need to be installed through xcode )

**Comment by cruzach** [comment]
You can do ad hoc builds with `expo build:ios` as well- https://docs.expo.io/distribution/building-standalone-apps/#adhoc-distribution (it's not as smooth, but it's possible)

**Comment by allan-simon** [comment]
ah nice thanks !

**Comment by prometheas** [comment]
> @ajgrover - oh ok, you can actually update to sdk 40 and this will work. we updated expo-constants to be available in bare apps in sdk 40 (and therefore it will work when built on eas build) - although it's hard to say if you will run into some other things we're currently working on with eas build managed support.

For what it's worth, @brentvatne, I just upgraded my bare workflow app project from SDK 39 => SDK 40, and was seeing the that "Constants.manifest is null" warning in my simulator until I applied a small variation of @ajgrover's [recommendation](https://github.com/expo/expo/issues/11808#issuecomment-771197912), adding `import 'expo-constants'` to the top of my `App.js` file—that solved the problem.

I'm pretty sure that one of my dependencies was causing the issue, so I've yet to identify the root cause, but at least I now can defer that work, in case I run out of time on my sprint 😅

**Comment by brentvatne** [comment]
@prometheas - it shouldn't be necessary to do that if you configure your app to embed the manifest as described [here](https://github.com/expo/expo/blob/master/packages/expo-constants/README.md#optional-set-up-script-to-get-app-config). 

this is automatically set when you initialize a new sdk 40 project or eject on sdk 40 but needs to be done manually when upgrading an existing bare project.

**Comment by prometheas** [comment]
@brentvatne - I can swear I had done that yesterday and run into build errors, so I backed that out… but I just did it again and you are indeed correct. Perhaps it was some bad build cache, or something, but today it build and ran nary a hitch.

Anyway, you are quite right. I'll update my previous comment to flag my mistake to future readers.

Thank you sir!
