### ISSUE TITLE
Failed building JavaScript bundle - expo-app-loading

### ISSUE THREAD

**Issue by gatoledo1** [expo/expo#11805]
**Summary**

SDK 40: Failed building JavaScript bundle. While trying to resolve module `expo-app-loading`

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

Expo CLI 4.1.4 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

import AppLoading from 'expo-app-loading';

export default function App() {

const [isReady, setIsReady] = useState(false);
  
async function ResourcesAsync() {
    let [fontsLoaded] = useFonts({
      Poppins_400Regular,
      Poppins_600SemiBold,
      Poppins_400Regular_Italic
    });
  }

  if (isReady == false) {
    return (
      <AppLoading
        startAsync={ResourcesAsync}
        onFinish={() => setIsReady(true)}
        onError={console.warn}
      />
    );
  } else {

    return (
      <NavigationContainer>
        <StatusBar style="light" />
          <AuthProvider> 
            <Routes />
          </AuthProvider>
      </NavigationContainer>
    );

  }
}

Hi,
I updated the SDK to version 40 and read the documentation warning about the migration of AppLoading. I performed the installation according to the documentation (https://docs.expo.io/versions/latest/sdk/app-loading/).
When I start the app, with yarn start, in 95% of the JavaScript bundle the error occurs:

Failed building JavaScript bundle.
While trying to resolve module `expo-app-loading` from file `C:\.......\project\App.tsx`, the package `C:\.......\project\node_modules\expo-app-loading\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\.......\project\node_modules\expo-app-loading\build\index.js`. Indeed, none of these files exist:

![print-bug](https://user-images.githubusercontent.com/19327889/106499448-601ca600-649f-11eb-89dc-5f7febb49cb2.png)

**Comment by AdamJNavarro** [comment]
Hey @AdamJNavarro, the code you shared references some external assets and imports. Can you please share a runnable example that we can test on our end? With that said, I just created a fresh managed TS project, installed expo-app-loading and implemented it without issue on android or ios.

Cheers,
Adam

**Comment by gatoledo1** [comment]
Hi @AdamJNavarro, i ran the command to install expo-app-loading, but it seems that some files are missing. Any correction I make to the code does not change the problem

**Comment by brentvatne** [comment]
<img width="1032" alt="Screen Shot 2021-02-01 at 9 44 49 PM" src="https://user-images.githubusercontent.com/90494/106557450-b822cf00-64d6-11eb-99a9-d1246df71648.png">

the files you're looking for are indeed there when you install the package. what you are encountering is possibly a bug with npm, or something else on your machine. delete node_modules and reinstall. if necessary, run `npm cache clean -f`.

**Comment by gatoledo1** [comment]
@brentvatne thank you very much! clearing the cache solved the problem
