### ISSUE TITLE
SQLite data not loading on Android applications

### ISSUE THREAD

**Issue by ianlavapiez** [expo/expo#11802]
**Summary**

The expo-lite is not working on android devices.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40.0

**Environment**

Expo CLI 4.0.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 24, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.3 => 4.4.3 
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

import React, { useEffect, useState } from "react";
import * as FileSystem from "expo-file-system";
import { ScrollView, View, Image, Text, TouchableOpacity, StyleSheet, Alert } from "react-native";
import * as SQLite from "expo-sqlite";
import { Asset } from "expo-asset";
import { category } from "../data/category";

const MenuScreen = ({ navigation }) => {
  let db;

  const [agriculturalEconomicsArray, setAgriculturalEconomicsArray] = useState([]);
  const [agriculturalExtensionArray, setAgriculturalExtensionArray] = useState([]);
  const [animalScienceArray, setAnimalScienceArray] = useState([]);
  const [cropProtectionArray, setCropProtectionArray] = useState([]);
  const [cropScienceArray, setCropScienceArray] = useState([]);
  const [soilScienceArray, setSoilScienceArray] = useState([]);

  const shuffleArray = (array) => {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }

    return array;
  };

  const gameMode = (name, quiz) => {
    Alert.alert(
      "Game Mode",
      "Do you want to use time trial?",
      [
        {
          text: "Yes",
          onPress: () => navigation.navigate("Quiz", { name, quiz, timeTrial: true }),
          style: "cancel",
        },
        { text: "No", onPress: () => navigation.navigate("Quiz", { name, quiz, timeTrial: false }), style: "cancel" },
      ],
      { cancelable: false }
    );
  };

  useEffect(() => {
    async function openDatabase() {
      if (!(await FileSystem.getInfoAsync(FileSystem.documentDirectory + "SQLite")).exists) {
        await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + "SQLite");
      }
      await FileSystem.downloadAsync(
        Asset.fromModule(require("../assets/database/iagri.db")).uri,
        FileSystem.documentDirectory + "SQLite/iagri.db"
      );

      db = SQLite.openDatabase("iagri.db");

      db.transaction((tx) => {
        tx.executeSql(`select * from agriculturaleconomics;`, [0], (_, { rows: { _array } }) => console.log(_array));
      });

      db.transaction((tx) => {
        tx.executeSql(`select * from agriculturalextension;`, [0], (_, { rows: { _array } }) =>
          setAgriculturalExtensionArray(_array)
        );
      });

      db.transaction((tx) => {
        tx.executeSql(`select * from animalscience;`, [0], (_, { rows: { _array } }) => setAnimalScienceArray(_array));
      });

      db.transaction((tx) => {
        tx.executeSql(`select * from cropprotection;`, [0], (_, { rows: { _array } }) =>
          setCropProtectionArray(_array)
        );
      });

      db.transaction((tx) => {
        tx.executeSql(`select * from cropscience;`, [0], (_, { rows: { _array } }) => setCropScienceArray(_array));
      });

      db.transaction((tx) => {
        tx.executeSql(`select * from soilscience;`, [0], (_, { rows: { _array } }) => setSoilScienceArray(_array));
      });

      return db;
    }

    openDatabase();
  }, []);

  return (
    <ScrollView>
      <View style={styles.container}>
        <TouchableOpacity
          style={styles.button}
          onPress={() => gameMode(category.cropScience, shuffleArray(cropScienceArray))}
        >
          <Image style={styles.logo} source={require("../assets/crops.png")} />
          <Text>{category.cropScience}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.button}
          onPress={() => gameMode(category.animalScience, shuffleArray(animalScienceArray))}
        >
          <Image style={styles.logo} source={require("../assets/pawprint.png")} />
          <Text>{category.animalScience}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.button}
          onPress={() => gameMode(category.soilScience, shuffleArray(soilScienceArray))}
        >
          <Image style={styles.logo} source={require("../assets/plant.png")} />
          <Text>{category.soilScience}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.button}
          onPress={() => gameMode(category.cropProtection, shuffleArray(cropProtectionArray))}
        >
          <Image style={styles.logo} source={require("../assets/protect.png")} />
          <Text>{category.cropProtection}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.button}
          onPress={() => gameMode(category.economics, shuffleArray(agriculturalEconomicsArray))}
        >
          <Image style={styles.logo} source={require("../assets/megaphone.png")} />
          <Text>{category.economics}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.button}
          onPress={() => gameMode(category.communication, shuffleArray(agriculturalExtensionArray))}
        >
          <Image style={styles.logo} source={require("../assets/chat.png")} />
          <Text>{category.communication}</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    height: "100%",
    width: "100%",
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  button: {
    position: "relative",
    color: "#199A8E",
    width: 300,
    height: 200,
    backgroundColor: "white",
    borderColor: "#C0C0C0",
    borderWidth: 1,
    borderRadius: 10,
    shadowColor: "#C0C0C0",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    margin: 20,
    display: "flex",
    justifyContent: "center",
    elevation: 1,
    alignItems: "center",
  },
  logo: {
    margin: 20,
  },
});

export default MenuScreen;

The `expo-sqlite` is working fine on iOS apps, but when I tried it to run on an Android device, the SQLite is not loading properly. The function is being called inside the `useEffect()`. Can anyone help me out with this? Thank you very much!

**Comment by byCedric** [comment]
Hi @ianlavapiez, thanks for writing in! I see that your snippet is referring to a lot of external data and assets, could you create a small repo/version of this on Snack? With that, we can help you dig deeper into this issue.

**Comment by ianlavapiez** [comment]
It seems I have resolved it sir through the error parameter. Thanks, sir!
