### ISSUE TITLE
attemptInvisibleVerification crashes 'Expo Go' latest update

### ISSUE THREAD

**Issue by OsamaMohammed** [expo/expo#11803]
**Summary**

I am using FirebaseRecaptchaVerifierModal for phone verification purposes, when I updated Expo client to the latest Expo Go, the app craches whenever FirebaseRecaptchaVerifierModal renders.

Note: this issue only appears on Android, I've tested it on iOS 13 and it works as expected.

```javascript
<FirebaseRecaptchaVerifierModal ref={recaptchaVerifier} firebaseConfig={FIREBASE_CONFIG} attemptInvisibleVerification={true} />
```

Temporary solution:

```javascript
<FirebaseRecaptchaVerifierModal ref={recaptchaVerifier} firebaseConfig={FIREBASE_CONFIG} attemptInvisibleVerification={false} />
```

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

4.1.4

**Environment**

  Expo CLI 4.1.4 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

setting attemptInvisibleVerification to true.

```javascript
<FirebaseRecaptchaVerifierModal ref={recaptchaVerifier} firebaseConfig={FIREBASE_CONFIG} attemptInvisibleVerification={true} />
```

**Comment by brentvatne** [comment]
please provide a runnable example that we can use to verify this. it should be possible to share it on https://snack.expo.io

**Comment by OsamaMohammed** [comment]
sorry for the typo, I meant to type 
<FirebaseRecaptchaVerifierModal ref={recaptchaVerifier} firebaseConfig={FIREBASE_CONFIG} `attemptInvisibleVerification={true}` />

attemptInvisibleVerification should be set to `true` to reproduce this issue.

I will make a slack reproduction example as soon as possible

**Comment by OsamaMohammed** [comment]
Unfortunately I wasn't able to re-create this issue with snack or new project, I think its something tight to my project (App container itself)

I tried to get the screen I was having the issue with to another vanilla project but no issue occurred.

I was able to export the crash log out of my Samsung A01 device using logcat (Attached)
[crash_log_logcat.txt](https://github.com/expo/expo/files/5911327/crash_log_logcat.txt)
.

**Comment by OTHMANE-AKHSAS** [comment]
I have the exact same issue... did you find a solution other than setting `attemptInvisibleVerification={false}` ?

**Comment by islamouzou** [comment]
Same here guys setting attemptInvisibleVerification={true} crashes my app when i press   the back button or try to navigate between screens .

**Comment by 2van** [comment]
I have same issue on Pixel 3.

**Comment by brentvatne** [comment]
from @OsamaMohammed above:

> Unfortunately I wasn't able to re-create this issue with snack or new project, I think its something tight to my project (App container itself)

y'all need to try to re-create a minimal reproducible example (https://stackoverflow.com/help/minimal-reproducible-example) for us to help.

**Comment by centemians** [comment]
This is breaking for me also. The whole application just crashes out :(

**Comment by hhananda** [comment]
Yes, I have the same issue, attemptInvisibleVerification={true} my app crash.

**Comment by brentvatne** [comment]
it seems like this is a bug with webview on android. i'm going to lock the thread because nobody is trying to create a reproducible example, which we need to dig deeper

**Comment by brentvatne** [comment]
this library was deprecated in sdk 47 and is no longer supported. [more information here](https://blog.expo.dev/expo-sdk-47-a0f6f5c038af)
