### ISSUE TITLE
Expo push notifications not working at all

### ISSUE THREAD

**Issue by aexol** [expo/expo#1180]
```
curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '{ "to": "ExponentPushToken[xxx]", "title":"hello", "body": "world" }'
```
This command with correct push token of course, works only one in 4 or one in 5 times.

**Comment by ide** [comment]
We are deploying a change to our push notification processing (just for iOS) that should fix 120-second long requests that result in 502 errors.

**Comment by ide** [comment]
We have push notification monitoring set up which shows notifications are currently working as expected.

**Comment by aexol** [comment]
Thank you very much :)
