### ISSUE TITLE
Native Module Cannot be Null when importing anything from expo-in-app-purchases

### ISSUE THREAD

**Issue by TKB21** [expo/expo#11809]
**Summary**

Looking to import and utilize components from the `expo-in-app-purchases` library but get thrown an Exception. Note that the react-native-unimodules package and expo-in-app-purchases have been installed in my app via yarn. I have also tried this in both the iOS simulator and physical device iPhone 11 but get the same error.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

~40.0.0

**Environment**

  Expo CLI 4.1.4 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.3 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.1.4
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

In the entry point of my app (App.js), simply import as follows:

    import * as InAppPurchases from 'expo-in-app-purchases';

Once your app has finished loading you should see the following error message: `Native Module cannot be null`.

![image](https://user-images.githubusercontent.com/4657771/106524429-90207500-64b0-11eb-8c80-9c85b99be7c0.png)

**Comment by brentvatne** [comment]
doesn't work in managed workflow

**Comment by brentvatne** [comment]
<img width="956" alt="Screen Shot 2021-02-01 at 3 12 35 PM" src="https://user-images.githubusercontent.com/90494/106529850-0ec0e680-64a0-11eb-9283-8e5b69461f10.png">

https://docs.expo.io/versions/latest/sdk/in-app-purchases/

**Comment by cbanksbi** [comment]
@brentvatne My apologies for the oversight. Given I have a fully functional app in the App Store atm, is there a way to convert my codebase to bare or what I have to start all over from scratch? Would you recommend doing so? Thanks for the prompt responses.

**Comment by TKB21** [comment]
@brentvatne My apologies for the oversight. Given I have a fully functional app in the App Store atm, is there a way to convert my codebase to bare or what I have to start all over from scratch? Would you recommend doing so? Thanks for the prompt responses.

**Comment by brentvatne** [comment]
@TKB21 - indeed, you can convert by running `expo eject`: https://docs.expo.io/workflow/customizing/

you can use eas build to build your app after ejecting: https://docs.expo.io/eas/

**Comment by TKB21** [comment]
> @TKB21 - indeed, you can convert by running `expo eject`: https://docs.expo.io/workflow/customizing/
> 
> you can use eas build to build your app after ejecting: https://docs.expo.io/eas/

Perfect. Thank you!
