### ISSUE TITLE
expo-av plays sounds on simulator but not on iPhone

### ISSUE THREAD

**Issue by ksnyder** [expo/expo#11806]
I copied the brief snipped of code for playing sounds from Playing Sounds section of this page of your docs:  https://docs.expo.io/versions/latest/sdk/audio/

It works in the simulator about half the time (iPhone 11 iOS 13.2.2), but never works on a device (iPhone 12 Pro Max iOS 14.4).

Other users are having the exact same problem -- I am using a brand-new expo app generated last week with the specs mentioned in this posting (the same as the other developer):
[(https://stackoverflow.com/questions/65978664/sound-doesnt-play-on-built-standalone-version-of-expo-app-ios-and-android-usi)]

**Comment by AdamJNavarro** [comment]
Hey @ksnyder, could you please share a repro case that we can access and run without any additional steps needed? Playing the game of "copy and paste" code is always a dangerous game because it allows for more opportunities of user error. Also, have you tested multiple different models/ios versions of this or is it limited to the versions/models you've mentioned above?

Cheers,
Adam

**Comment by frankieisgood** [comment]
https://snack.expo.io/@frankieisgood/7e8323 I am having the same problem with that documentation code on iPhone 11 iOS 14.3. It plays on web browser but never the device.

**Comment by ksnyder** [comment]
I haven't been able to repro this problem -- after several days trying to get sound out of my iPhone 12, I gave up and moved on to working on other features.  However, at some point, I tested the sound again and found that it was now working, and it has remained working since then.  During this time I did not change the code handling sound (which had been mostly working on the simulator in any case).  I have tried to figure out what might have made it suddenly work, and I don't know for sure, but I think one possibility was that the automatic rebuild and reload process was part of the problem.  I believe that some combination of stopping all Expo processes: the phone app, the simulator, servers / build processes and debuggers and beginning again with a clean slate *may* have made the difference, so I would suggest trying that if you haven't already.

**Comment by abstauff** [comment]
I'm having the same problem, event when directly using Expo-AV documentation: https://docs.expo.io/versions/latest/sdk/audio/

Your android emulator, ios simulator, and my device (iphone6) don't play any sound. Web version does.

**Comment by QendresaB** [comment]
I'm also having problems with playing sounds in **IOS**, ... I'm getting the error:
**The server is not correctly configured. - The AVPlayerItem instance has failed with the error code -11850 and domain "AVFoundationErrorDomain".**
The error occurs in both cases even if I use createAsync method or load then play the files. Also I'm loading audio from a network URL as in: 
   await Audio.Sound.createAsync(
      {
        uri: 'http://xx.x.x.xxx:5000/api/file/recording-1234.m4a'
      },
      {
        shouldPlay: true,
      }
    )

**Comment by yongzhi-chen** [comment]
> https://snack.expo.io/@frankieisgood/7e8323 I am having the same problem with the documentation code on iPhone 11 iOS 14.3 and iPhone 6 12.5.1. It plays on web browser but never the device.

Im also having problems with iphone 11... What i am observing is that

Audio recorded on iphone 11 is not playable on iphone 7 (However it is playable on web)
Audio recorded on iphone 7 is playable everywhere

My recordOptions is something like this 

```
const recordOptions = Audio.RECORDING_OPTIONS_PRESET_LOW_QUALITY;

recordOptions.ios.outputFormat = Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC
recordOptions.ios.extension = '.m4a'
```

**Comment by kmichnicki** [comment]
I'm having the same issue. Mp3 audio works on android, but not on ios, specifically iphone 11. 

here are the versions that I have installed.
"expo": "^44.0.6",
"expo-av": "^10.2.1",
"expo-cli": "^5.3.0",

My code is something like
```
Audio.Sound.createAsync(require("something.mp3"), {volume: 1})
    .then(({ sound }) => {
        sound.playAsync();
     });
```

I run `expo publish` and then try the app out on my iphone using expo go.
