### ISSUE TITLE
[Expo-av] pause.Asyn() will not pause song playing

### ISSUE THREAD

**Issue by sawane8** [expo/expo#11815]
hello, i'm new with Expo sdk so since i'm playing around with it, i'm having some problems with audio
here's what i'm doing 

`async playSound() {

    const { sound } = await Audio.Sound.createAsync(
       require('../assets/ama.mp3'),
    );

    this.setState({ sons: sound });

    if(this.state.isPlaying){
      
       await this.state.sons.pauseAsync()
       console.log('Pause Playing');
        this.setState({isPlaying: false})

    }else{

      await this.state.sons.playAsync(); 
      this.setState({isPlaying: true})

      console.log('Playing Sound');
    }

  }`

The sound is Playing well, I couldnt stop or pause the sound, what i'm doing wrong ?

thanks in advance

**Comment by AdamJNavarro** [comment]
Hey @sawane8, happy to hear you've decided to try out the Expo SDK. Welcome to the community! With that said, we try our best to reserver github issues for reproducible and actionable bug reports. Would you please create a forum post on our [Forums](forums.expo.io) so we can help out with questions about implementation such as this one?

Cheers,
Adam
