### ISSUE TITLE
Not able to deploy to appstore after Expo eject

### ISSUE THREAD

**Issue by RocKer004** [expo/expo#11811]
**Summary**

Hi there, I ejected my expo app, which was already successfully deployed to the appstoreconnect using expo build:ios and transporter app. After ejecting expo you're no longer able to do it so, so you have to use Xcode to create an archive.
I've created the archive (.ipa file) with my Xcode and have successfully signed it. After uploading Xcode says, that it was successfully uploaded, but it doesn't appear in the appstoreconnect under my builds (as it would do with expo build).
Also, when I export .ipa file from Xcode (that I was trying to upload) it's only 58 mbs, when the .ipa file generated with expo build:ios was around 210mbs. 
Am I doing something wrong ?
Thanks in advance.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

 Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 17, 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: ^17.0.1 => 17.0.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

there's no way to do that, if u'we read description u'll understand :)

**Comment by brentvatne** [comment]
this is unrelated to expo tooling. once you eject, [unless you use eas build](https://blog.expo.io/expo-application-services-eas-build-and-submit-fc1d1476aa2e), expo has nothing to do with your app store builds and it's no different from building any other ios app, so you should refer to the appropriate ios documentation.
