### ISSUE TITLE
- URL mismatch: No standalone app has been built with SDK 40.0.0 and release channel "default" for this project before.

### ISSUE THREAD

**Issue by khelifioussama** [expo/expo#11812]
**Summary**

Hello ,
I upgrated expo CLI to latest (4.1.4) and upgrade expo in my app to expo 40.0.0 
now I can't do expo publish first I have "- URL mismatch: No standalone app has been built with SDK 40.0.0 and release channel "default" for this project before.
OTA updates only work for native projects that have the same SDK version and release channel. Learn more: https://docs.expo.io/workflow/publishing/#limitations" then that stop the Publish and I have Request body larger than maxBodyLength limit
any Solution Please

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40.0.0

**Environment**

Expo CLI 4.1.4 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Kingdel\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.1, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

- Expo SDK: 40.0.0
- Release channel: default
- Workflow: Managed

- URL mismatch: No standalone app has been built with SDK 40.0.0 and release channel "default" for this project before.
  OTA updates only work for native projects that have the same SDK version and release channel. Learn more: https://docs.expo.io/workflow/publishing/#limitations

Building optimized bundles and generating sourcemaps...
Starting Metro Bundler
Finished building JavaScript bundle in 34811ms.

Bundle                     Size
┌ index.ios.js          5.98 MB
├ index.android.js      5.97 MB
├ index.ios.js.map      14.8 MB
└ index.android.js.map  14.8 MB

� JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes

Analyzing assets
Saving assets
No assets changed, skipped.

- C:\Users\Kingdel\Desktop\imaxeam\***\**\*

Uploading JavaScript bundles
Request body larger than maxBodyLength limit

**Comment by byCedric** [comment]
Hi @khelifioussama, please upgrade to Expo CLI `4.1.5`. See [this issue](https://github.com/expo/expo-cli/issues/3158)

**Comment by bkoether** [comment]
@byCedric I get the same issue after upgrading from SKD40.0.0 to 41.0.0
I'm running explo-cli `4.4.2` on macOS

Was there something missed when I did the upgrade?

**Comment by bkoether** [comment]
> @byCedric I get the same issue after upgrading from SKD40.0.0 to 41.0.0
> I'm running explo-cli `4.4.2` on macOS
> 
> Was there something missed when I did the upgrade?

I actually should clarify, I do not get "Request body larger than maxBodyLength limit"... I'm seeing 
"URL mismatch: No standalone app has been built with SDK 41.0.0 and release channel "production" for this project before." and don't know why. Didn't see this happening with previous SDK updates.

**Comment by MaRaSu** [comment]
I have SDK40 app upgraded to SDK41 and then ejected. Configured a "beta" release channel in expo.plist, built app archive with XCode UI and distributed via TestFlight to devices - all good. 

When I try to do expo publish (expo-cli 4.4.1 on Mac) I get the same warning "URL mismatch..." AND when I launch app in the device so that it fetches (or tries at least) new expo package it crashes.

**Comment by torreyleonard** [comment]
Same issue as @MaRaSu here. Upgraded to SDK 41 and ejected. Builds work and the app is running on phones, but I get the following when running expo-publish:

`> expo publish --release-channel $npm_package_version-beta

› Expo SDK: 41.0.0
› Release channel: 1.1.0-beta
› Workflow: Bare

- URL mismatch: No standalone app has been built with SDK 41.0.0 and release channel "1.1.0-beta" for this project before.
  OTA updates only work for native projects that have the same SDK version and release channel. Learn more: https://docs.expo.io/workflow/publishing/#limitations

Building optimized bundles and generating sourcemaps...
Starting Metro Bundler
Building JavaScript bundle [============                                                    ] 18%`

After launching, the bare workflow app can't find any new updates within that release channel (configured in Expo.plist).

**Comment by brentvatne** [comment]
the url mismatch doesn't apply to you if you are using this in bare workflow, you can ignore it.

please share a reproducible example if updates aren't loading for you and i'll be happy to re-open and investigate

**Comment by torreyleonard** [comment]
My issue is resolved, it looks like I was checking for an update only when `Constants.appOwnership === "standalone"`, but after ejecting `appOwnership` always returns null. I changed the check to `__DEV__` and it appears to be working now.

Thanks for the quick response!
