### ISSUE TITLE
`exp build-ios` You already have a current iOS Distribution certificate

### ISSUE THREAD

**Issue by ShMcK** [expo/expo#1181]
I'm currently having issues building the ios version of an app with credentials. See [1177](https://github.com/expo/expo/issues/1177).

A week ago, I had success building the .ipa with Expo managing credentials. It worked once, but since then has been failing.

When I select `Let Expo handle the process`, I get the following error/warning:

```
[exp] Error while gathering & validating credentials
[exp] Reason:You already have a current iOS Distribution certificate or a pending certificate request. Maximum number of certificates generated, raw:{"responseId":"ca585f95-6cb3-457f-a695-12c55cc4f018","resultCode":7460,"resultString":"Maximum number of certificates generated","userString":"You already have a current iOS Distribution certificate or a pending certificate request.","creationTimestamp":"2017-12-29T18:22:41Z","protocolVersion":"QH65B2","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action","httpCode":200}
```

As expected, these certificates are not available from my own apple developer console. Leaving me no way to remove them.

Running `exp build-ios -c` does not clear these existing or pending certificates.

---

- Is there a way to specify to use an existing certificate with exp?
- Is there a way to clear pending or existing certificates?

**Comment by fxfactorial** [comment]
Hi, `-c` does not delete certificates from your apple account. Only you can do that right now. 

Using your apple credentials, log into https://developer.apple.com/account and delete certs to free up space for exp to make new certs for you. 

I will look about adding 'Is there a way to specify to use an existing certificate with exp?'

**Comment by ShMcK** [comment]
In the case where I select `Let Expo handle the process` rather than handling my own certs, are you saying that Expo adds these certificates to my developer.apple account? Or does Expo manage these certifications from their own account?

**Comment by fxfactorial** [comment]
Yes, it creates it. It is a regression of mine to always attempt to make new creds rather than use existing from previous creation. I will fix this now, it is a quick fix.

**Comment by fxfactorial** [comment]
@ShMcK Released, please try when you can.

**Comment by ShMcK** [comment]
Running exp 47.3.2 with and selecting "Expo handles all credentials" results in the same error for me.

**Comment by fxfactorial** [comment]
@ShMcK What is the exact error message? Are you okay with doing `-c`?

**Comment by ShMcK** [comment]
Error message with 47.3.2. Essentially the same as before.

```
[exp] Error while gathering & validating credentials
[exp] Reason:You already have a current iOS Distribution certificate or a pending certificate request. Maximum number of certificates generated, raw:{"responseId":"9cc73cc7-0be8-4fff-b678-0da3b5dd3703","resultCode":7460,"resultString":"Maximum number of certificates generated","userString":"You already have a current iOS Distribution certificate or a pending certificate request.","creationTimestamp":"2017-12-29T22:11:54Z","protocolVersion":"QH65B2","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action","httpCode":200}
```

I also removed the certificates from developer.apple, and ran again with `-c`. Same error.

**Comment by ShMcK** [comment]
I think I've found the root cause.

<img width="732" alt="screen shot 2017-12-29 at 2 22 08 pm" src="https://user-images.githubusercontent.com/4660659/34448594-be44278e-eca3-11e7-954d-809008899dae.png">

**Comment by fxfactorial** [comment]
Yes, you are limited to 2 in individual account. Error messages you get should have mentioned that

**Comment by ShMcK** [comment]
Got it submitted.

One note:

Duplicate warnings appeared if I had any duplicates out of "IOS Distribution", "Push Notification", or "Provisioning Profile". Removing any one of these duplicates would still fail. Removing them all, then running exp build again was successful.

**Comment by gfviegas** [comment]
I'm having the same issue @ShMcK , I noticed it happened just after I updated my MacOS version, if this means something.

I've deleted the certificate and Provisioning Profile from Apple Developer but I can't delete anything else (like the App ID because it's being used in App Store).

Still, using `exp:build ios -c` returns me

> [exp] Error while gathering & validating credentials
> [exp] Reason:You already have a current iOS Distribution certificate or a pending certificate request. Maximum number of certificates generated, raw:{"responseId":"HIDDEN","resultCode":7460,"resultString":"Maximum number of certificates generated","userString":"You already have a current iOS Distribution certificate or a pending certificate request.","creationTimestamp":"2018-01-22T23:16:36Z","protocolVersion":"HIDDEN","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/HIDDENaccount/ios/certificate/submitCertificateRequest.action","httpCode":200}

when I try to let expo handle stuff.

**Comment by crazyx13th** [comment]
same here :-(

```
[exp] Error while gathering & validating credentials
[exp] {}
[exp] Reason:You already have a current iOS Distribution certificate or a pending certificate request. Maximum number of certificates generated, raw:{"responseId":"HIDDEN","resultCode":7460,"resultString":"Maximum number of certificates generated","userString":"You already have a current iOS Distribution certificate or a pending certificate request.","creationTimestamp":"2018-01-23T11:57:18Z","protocolVersion":"HIDDEN","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/HIDDEN/account/ios/certificate/submitCertificateRequest.action","httpCode":200}
```

thx

**Comment by fxfactorial** [comment]
Hi @crazyx13th 
2 is the limit set by Apple. Once your credentials are saved by `exp`, you won't need to do this again.

(Also please make your own issue or use the expo forums)

**Comment by crazyx13th** [comment]
thx, first I was thinking this would be the same issue (before edit1+2), sorry

**Comment by markmiller21** [comment]
So I am also having this issue and can't figure out how to get back in the iOS store.  We have used exp for the entire submission process thus far but yet this time when I submit I am getting the same error as @crazyx13th  & @ShMcK.  I am not a mobile dev so this is foreign to me.  What will deleting these certificates do?  I am getting pressure on my team because we need to submit to the app store again but don't want our production app to not work because of something I did with the certificates.

What was the final solution?  Remove the existing certificates and pray it works?  We currently have 5 somehow

**Comment by fxfactorial** [comment]
@markmiller21 You revoke the certificates on developer.apple.com that have been created via exp. Be sure to also remove the provisioning profile associated with your bundleIdentifier. While they are revoked, things like push notifications won't work. So after you remove them, you do `exp build:ios -c` and exp will create new certs, save them and everything will work again. exp won't bother you for certs next time you do `exp build:ios`.

**Comment by EliteCRM** [comment]
@gfviegas do you figure out this problem? i have stuck in which a week! can you help me?

**Comment by AnthonyLamot** [comment]
Question: Does it make sense to keep revoking certificates / profiles whenever doing another `exp build:ios`?

It is nice that Expo takes care of the certificates / profiles, but it seems weird that you would remove / recreate these if you want to submit another build to the App Store again. So if you have an app in production, would it make more sense to manage the certificates yourself, or does it really not matter that much?

**Comment by fxfactorial** [comment]
exp only makes new things if all required certs are missing. Again, if exp build:ios succeeded once, then the next usage will use existing files and won’t try making new ones. If it is making new ones, it means you did exp build:ios -c at some point.

**Comment by drewbietron** [comment]
I am stuck with  `Reason:Multiple profiles found with the name` error as well.  I have removed certificates multiple times and and it creating new certificates although it is not using them.

**Comment by fxfactorial** [comment]
Its not about certificates. Multiple profiles is about provisioning profile. Look at your provisioning profile on developer.apple.com. Once it is made by `exp` and saved, `exp` will not make a new one unless you have done a `exp build:ios -c`

**Comment by drewbietron** [comment]
@fxfactorial - I’ve tried deleting all of the certificates and running build with -c multiple times and I always get the multiple profile error. The certs do show up on developer.apple.com after every failed build

**Comment by fxfactorial** [comment]
@drewbietron As I said, it is not an issue of certificates. It is about provisioning profile. A provisioning profile IS NOT a certificate. 

Remove your existing provisioning profile for the app.

**Comment by drewbietron** [comment]
@fxfactorial - Gotcha, my bad for not understanding.  I saw two certificates on developer.apple.com and did not see the provisioning tab with all of my various bundle identifiers.

I have since delete these and what do you know, it works! 😄 

Thanks

**Comment by fxfactorial** [comment]
Happy you got it working! ships some apps :)

**Comment by derekyle** [comment]
I'm having the same trouble with a ducplicate provisioning profile. I didn't run the -c command, but I have upgraded exp since my last attempt to build:ios.

Will deleting the current Provisioning Profile cause problems for my app that is currently launched?

**Comment by stefdelec** [comment]
I have the error too. And the error is not self understandable.

**Comment by JorgeMoralesLopez** [comment]
I have the same error, I could upload a test to testflyght but wanting to update it tells me that I have duplicates

**Comment by jefelewis** [comment]
Was there any resolution to this? I'm getting the same error and this issue popped up randomly. I've already pushed my App to TestFlight twice, but now this error comes up for the 3rd time

`Reason: Unexpected response, raw: {"responseId":"9711aca9-68e0-4a62-ab88-asdsa924e1414","resultCode":35,"resultString":"There were errors in the data supplied. Please correct and re-submit.","userString":"Multiple profiles found with the name 'com.inspectr.inspectr AppStore'.  Please remove the duplicate profiles and try again.","creationTimestamp":"2019-05-22T01:26:08Z","protocolVersion":"QH65B2","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action","httpCode":200,"validationMessages":[{"validationKey":"provisioningProfileName","validationUserMessage":"Multiple profiles found with the name 'com.appName.appName AppStore'.  Please remove the duplicate profiles and try again."}]}`
