### ISSUE TITLE
[web][expo-image-picker] Image picker does not resolve after pressing cancel button on web

### ISSUE THREAD

**Issue by jayprado** [expo/expo#11817]
**Summary**

When using `ImagePicker.launchImageLibraryAsync` or `ImagePicker.launchCameraAsync` on web, pressing the "Cancel" button on the picker dialog does NOT return `{ cancelled: true }` as the result, as expected from the [docs](https://docs.expo.io/versions/v40.0.0/sdk/imagepicker/#returns-4). It seems to be stuck on the `Promise`, as the succeeding code does not run (see [Snack](https://snack.expo.io/@purrado/expo-image-picker-cancelled-on-web)).

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Web

**SDK Version (managed workflow only)**

40.0.1

**Environment**

```
  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/jayprado/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed
```

**Reproducible demo or steps to reproduce from a blank project**

https://snack.expo.io/@purrado/expo-image-picker-cancelled-on-web

Use on `Web` and observe `Logs`

**Comment by brentvatne** [comment]
pr welcome for this! the source is in https://github.com/expo/expo/blob/master/packages/expo-image-picker/src/ExponentImagePicker.web.ts

**Comment by Vimiso** [comment]
Any updates on this? Pending merge conflicts?

**Comment by coren-frankel** [comment]
> Any updates on this? Pending merge conflicts?

@Vimiso, looks like #27454 aims to address the resurgence of this issue
