### ISSUE TITLE
undefined is not a function (near '..._core.Platform.select...') after upgrading from SDK37 to SDK38

### ISSUE THREAD

**Issue by obiwankenoobi** [expo/expo#11819]
**Summary**

trying yo upgrade SDK from 37 to 38 and the upgrade went well and now when I start the app it's crushing with this error `undefined is not a function (near '..._core.Platform.select...') after`

It happens when changing `import { Linking } from 'expo'` to `import * as Linking from 'expo-linking'` as the change-log suggests

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

38.0.0

**Environment**

  Expo CLI 3.27.14 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.13.1 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

upgrading from SDK37 to SDK38

**Comment by brentvatne** [comment]
here's what you can do to try to manually debug this:  https://expo.fyi/manual-debugging

if you find what the source of the error is and it is a bug on our end and not in your code, let us know!

**Comment by georgesatar96** [comment]
Hi guys, i have the same problem i have spent 2 days on this, in the moment i put the import * as Linking from 'expo-linking' the entire app crashes with that same error.

Have you find any solution for this yet ?

Thanks!

**Comment by brentvatne** [comment]
@georgesatar96 - https://stackoverflow.com/help/minimal-reproducible-example please!
