### ISSUE TITLE
Pedometer.watchStepCount works only when app in foreground

### ISSUE THREAD

**Issue by zvs001** [expo/expo#11822]
**Summary**

`Pedometer.watchStepCount` is not being called when app on background.

I'm trying to use package within headless task. Callback works only when app in foreground. 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

    "expo-sensors": "^10.0.0",
    "react-native": "^0.63.4",
    "react-native-unimodules": "^0.12.0",

**Reproducible demo or steps to reproduce from a blank project**

cases:
- foreground:
works good

- background / locked:
steps still counting, but callback is not fired. After app launch callback will be called with total steps number (bg).

- terminated app state:
callback is never fired. Steps are reset. Next one app launch will crash.

**Comment by brentvatne** [comment]
hi! we don't explicitly support this, here is the source if you would like to contribute and help fix: https://github.com/expo/expo/blob/9c26fbc09d2ec8c7b48d5e7d79bf99631b7b84cc/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/PedometerModule.java

we likely will not investigate this any time soon
