### ISSUE TITLE
iOS MapView.Marker size doubles in size after build (v24.0.0 only)

### ISSUE THREAD

**Issue by robert-newapptech** [expo/expo#1182]
I was running into this exact issue seen on react-native-maps but only for iOS devices:
https://github.com/react-community/react-native-maps/issues/1422

I am posting this on Expo because the react-native-maps dependency was unchanged between v23.0.0 and v24.0.0. However, I was running into this exact issue after upgrading to v24.0.0. The solution posted in the react-native-maps issue did not resolve the issue. After downgrading to v23.0.0, the issue was immediately resolved.

I did not run into this issue while testing on the iPhone 6 simulator. This issue was reproducible on iPhone 7 and iPhone X builds. (I did not test iPhone 6s devices).

Note that the Markers look fine while running the application on Expo, but the markers are too big after building.

**Comment by ide** [comment]
It's possible that the React Native packager, which is responsible for handling image assets, changed how it handles hi-res images between the versions of RN used for SDK 23 and 24. 

Have you tried the workaround with `@2x` and `@3x` marker icons? (Presumably you'd get 2x and 3x-scaled versions of your icons and save them as `icon-name@2x.png` for example.)

**Comment by robert-newapptech** [comment]
@ide my assets already had the `@2x` and `@3x` on the marker icons. That was unchanged between upgrades. I also tried with workaround using a nested `<Image />` in the `MapView.Marker` as suggested [here](https://github.com/react-community/react-native-maps/issues/882) with no luck.

**Comment by ide** [comment]
Hm, I'm not sure what this could be then. We periodically (but not always regularly) update react-native-maps, so if the issue is fixed upstream it likely will eventually make its way back to Expo.

**Comment by pcooney10** [comment]
@robert-newapptech do you use the image prop on `MapView.Marker` or do you wrap an `Image` component in `MapView.Marker` like people were suggesting (in the thread you linked [https://github.com/react-community/react-native-maps/issues/1422](https://github.com/react-community/react-native-maps/issues/1422))? 

I also noticed this in my standalone iOS build with v24.0.0.

**Comment by robert-newapptech** [comment]
@pcooney10 I tried both methods but neither worked for me.

**Comment by andrioid** [comment]
I can reproduce this on SDK 25. Didn't have this issue on SDK 24. I'm using the `image` prop on `<Marker />`.

- I can't use ` <Image />` as child, because it won't render properly on Android 7.1 (see https://github.com/react-community/react-native-maps/issues/1870)
- I can't use `<Svg />` as child, because it performs badly with 30+ markers

I have a forum post here: https://forums.expo.io/t/sdk-25-custom-map-markers-are-now-huge-on-ios/6681/2

I'll update with a Snack ASAP

**Comment by ccheever** [comment]
this seems to maybe be a problem with `Image.prefetch` and its interaction with maps.
https://forums.expo.io/t/sdk-25-custom-map-markers-are-now-huge-on-ios/6681

A workaround may be to turn off prefetching for the images you're using for markers if you are doing that.

**Comment by andrioid** [comment]
Sorry I deleted my post, but yes I could be the prefetching. But as I said, it was working perfectly for me in SDK 24. So, I didn't want to presume it was the same issue.

**Comment by robert-newapptech** [comment]
@ccheever This may be a different issue. I was seeing this behavior without calling `Image.prefetch` on SDK 24

**Comment by outaTiME** [comment]
Im getting the same issue with SDK 26 here my forum question with test cases:

https://forums.expo.io/t/asset-loadasync-image-density-issue/8847

any updates?

**Comment by guillermodoghel** [comment]
same issue over here.

**Comment by andrioid** [comment]
I was not thrilled when my standalone build finished today and I saw this bug was back. No pre-fetching either.

Does anyone have a work-around yet?

**Comment by outaTiME** [comment]
Hi @andrioid, im post my workaround with prefetch support in expo forums:

https://forums.expo.io/t/asset-loadasync-image-density-issue/8847/8?u=outatime

I hope you find it useful

**Comment by miraan** [comment]
I'm also getting this issue. Just built an ejected ExpoKit iOS on SDK 28, and my map marker images are now very big (3x the size). I have 2x and 3x icons. No issues on Android.

**Comment by EvanBacon** [comment]
@miraan is there possibly a more elegant solution, or should we consider this issue closed? 
I can throw some syntax sugar on it for you. 
`image` & `imageStyle: {width: number, height: number}` props.
```js
class Marker extends React.Component {
  render() {
    const { image, imageStyle, children, ...props } = this.props;
    const { OS } = Platform;
    return (
      <MapView.Marker image={OS === 'android' ? image : undefined}>
        {OS === 'ios' && <Image source={image} style={imageStyle} />}
        {children}
      </MapView.Marker>
    );
  }
}
```

**Comment by AdamJNavarro** [comment]
Hey @robert-newapptech,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam

**Comment by moxorama** [comment]
Problem still exists

**Comment by Zhdanown** [comment]
for me using Image wrapped in Marker helped
