### ISSUE TITLE
expo-analytics-segment not displaying version number of OTA

### ISSUE THREAD

**Issue by michaelmarriott** [expo/expo#11835]
**Summary**

Version number from OTA not appearing in RAW segment been sent from app.
A build from 624 was pushed to store, then an OTA 625 was published successfully.
Segment only shows the build number of artifact(624) loaded to store and doesn't display the OTA number(625).

App.json
=====
"expo": {
...
    "version": "2.40.625",
...
    "android": {
...
      "versionCode": 625
    }
..

Raw Segment after OTA:
=========
{
  "anonymousId": "xxxxxxxxxxxxxxxxxx,
  "context": {
    "app": {
      "build": "624",
      "name": "xxxxxxxxxxxxxxx",
      "namespace": "xxxxxxxxxxxxxxxx",
      "version": "2.40.624"
    },

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40

**Environment**

Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.3 => 4.4.3 
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

* react init a new project
yarn install expo-analytics-segment

#Add import
import * as Segment from 'expo-analytics-segment';

#Setup Segment
const androidWriteKey = "xxxxxxxxxxxxxxx";
const iosWriteKey = "xxxxxxxxxxxxx";

Segment.initialize({ androidWriteKey, iosWriteKey })

Do A build, upload to store, check build coming

**Comment by cruzach** [comment]
the `versionCode` shouldn't be incremented with OTA updates, it should be incremented with new builds. To differentiate between OTA updates, you can should use `version`

See the difference between `Constants.nativeAppVersion` and `Constants.nativeBuildVersion` here- https://docs.expo.io/versions/latest/sdk/constants/#constantsnativeappversion
