### ISSUE TITLE
[eas-build] Unable to build for ios and android

### ISSUE THREAD

**Issue by yarapolana** [expo/expo#11839]
**Summary**

ios: Everything works well with command eas build, but after `uploading to EAS` the build fails with Launcher few seconds later.
android: Build fails at ```Execution failed for task ':unimodules-image-loader-interface:compileReleaseJavaWithJavac'.```

Both build successfully locally.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.12.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 25, 28, 29
        Build Tools: 28.0.3, 29.0.1, 29.0.2, 30.0.2
        System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: 40.0.1 => 40.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: 0.13.12 => 0.13.12 
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

Not Applicable?!

---ios---
Not much feedback here to continue.

![Screenshot 2021-02-04 at 12 57 48](https://user-images.githubusercontent.com/19730118/106895885-b7618700-66e8-11eb-9985-84059242a02f.png)

---android---
Unable to extend the "Compilation" error for more details to debug and continue.

![Screenshot 2021-02-04 at 12 59 33](https://user-images.githubusercontent.com/19730118/106895996-db24cd00-66e8-11eb-9aa7-fd1ce7b04232.png)

**Comment by brentvatne** [comment]
can you please share links to your build pages to secure@expo.io?

also, can you try a release build locally for android? you can do this by syncing your credentials to your local machine (described here: https://docs.expo.io/app-signing/syncing-credentials/) and then running `./android/gradlew :app:bundleRelease`

**Comment by yarapolana** [comment]
@brentvatne sent the links. 
and with building android release version locally I get the same error
```org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':unimodules-image-loader-interface:compileReleaseJavaWithJavac'```

**Comment by yarapolana** [comment]
@brentvatne secure@expo.io replied and I managed to build for iOS after that.
Though on Android if I comment out eas-build.gradle and build locally for release everything works =/
