### ISSUE TITLE
[Expo-AV] setPositionAsync results in buffering when new position is within playableDuration

### ISSUE THREAD

**Issue by balsamfir7** [expo/expo#11837]
**Summary**

When I call the setPositionAsync function it will always buffer the video even if the new position is less than playableDurationMillis away from the current position. For making a frame by frame player this results in a very poor user experience as there is a delay every time the user wants to advance a frame. Is there a way around this?

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

Check playableDuration
Call setPositionAsync within playableDurable range
Results in buffering

**Comment by top-kat** [comment]
@balsamfir7 have you find a solution to this ? Making a image by image video player in react native is a real PITA

**Comment by balsamfir7** [comment]
@top-kat - I didn't but it's also been 1 yr since I worked on this project. Might be some new solutions out there.
