### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException

### ISSUE THREAD

**Issue by thmsngyn** [expo/expo#11830]
**Summary**

This is a trending issue for our iOS users. Unfortunately, I haven't been able to reproduce the issue.

Expected:
App loads.

Actual:
App crashes on load.
```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18cd4986c __exceptionPreprocess
1  libobjc.A.dylib                0x1a1cb8c50 objc_exception_throw
2  CoreFoundation                 0x18cdb9e1c -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x18cdc6270 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5
4  CoreFoundation                 0x18cc3a550 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5  CoreFoundation                 0x18cc2cdd0 +[NSDictionary dictionaryWithObjects:forKeys:count:]
6  EXFileSystem                   0x102999fe4 (Missing)
7  EXFileSystem                   0x1029995cc (Missing)
8  EXFileSystem                   0x10299952c (Missing)
9  EXFileSystem                   0x10299a224 (Missing)
10 CFNetwork                      0x18d523254 _CFNetworkHTTPConnectionCacheSetLimit
11 libdispatch.dylib              0x18c93c24c _dispatch_call_block_and_release
12 libdispatch.dylib              0x18c93ddb0 _dispatch_client_callout
13 libdispatch.dylib              0x18c94510c _dispatch_lane_serial_drain
14 libdispatch.dylib              0x18c945c90 _dispatch_lane_invoke
15 libdispatch.dylib              0x18c94fd78 _dispatch_workloop_worker_thread
16 libsystem_pthread.dylib        0x1d851b804 _pthread_wqthread
17 libsystem_pthread.dylib        0x1d852275c start_wqthread
```
The stack trace points me to a file called `EXSessionTaskDispatcher` in the `EXFileSystem` dependency. The call is likely originating from either react native's initialization or a call made by a dependency.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @sentry/react-native: 2.0.2 => 2.0.2 
      @testing-library/react: ^10.4.7 => 10.4.9 
      @types/react: ~16.9.35 => 16.9.53 
      @types/react-native: ~0.63.2 => 0.63.29 
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.3 => 0.63.3 
      react-navigation: 4.4.2 => 4.4.2 

**Reproducible demo or steps to reproduce from a blank project**

N/A

**Comment by larry-cherry** [comment]
I am having the same issue when I am trying to load a component that uses expo-gl. I am using expo-gl with react-three-fiber.

**Comment by brentvatne** [comment]
> The stack trace points me to a file called EXSessionTaskDispatcher in the EXFileSystem dependency. The call is likely originating from either react native's initialization or a call made by a dependency.

it sounds like you may be making a call to expo-file-system with an invalid param, possibly.

happy to investigate if you can demonstrate that this is a bug in expo code rather than your own app code.

if you're having trouble finding the source of the problem, try adding additional telemetry to help you understand how this ends up happening. there isn't much we can do with a generic error message like this without more information about what code is causing it or how to reproduce it.
