### ISSUE TITLE
[expo-notification] useLastNotificationResponse & addPushTokenListener called twice

### ISSUE THREAD

**Issue by sebastienlabine** [expo/expo#11843]
**Summary**

When pressing on a notification to open it, the useLastNotificationResponse hook and the addPushTokenListener are called twice.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40

**Environment**

 Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.19041    
    Binaries:
      Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\sebas\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

```
import React, { useEffect } from "react";
import * as Notifications from 'expo-notifications';
import { useDispatch, useSelector } from "react-redux";

export function usePushNotifications() {
    const dispatch = useDispatch();
    const lastNotificationResponse = Notifications.useLastNotificationResponse();
    React.useEffect(() => {
        console.log("update happened")
    }, [lastNotificationResponse]);

    Notifications.setNotificationHandler({
        handleNotification: async () => ({
            shouldShowAlert: true,
            shouldPlaySound: true,
            shouldSetBadge: true,
        }),
    });

    useEffect(() => {
        console.log("called once")
        const subscription = Notifications.addPushTokenListener((token) => { });

        const notficationSubscription = Notifications.addNotificationReceivedListener(notification => {
        });

        const responseSubscription = Notifications.addNotificationResponseReceivedListener(event => {
        console.log("new notification")
        });

        return () => {
            responseSubscription.remove();
            notficationSubscription.remove();
            subscription.remove();
        }
    }, []);
}
```

**Comment by brentvatne** [comment]
@sebastienlabine - please provide a full runnable example. there could be valuable context in other files to help determine what is happening here. see https://stackoverflow.com/help/minimal-reproducible-example for more info

**Comment by sebastienlabine** [comment]
Actually debugged it. Using a hook to register the listeners was actually creating multiple listener, hence handling multiple times the notification

**Comment by cruzach** [comment]
thanks for following up and debugging @sebastienlabine !

**Comment by hanijazzar** [comment]
@sebastienlabine please how exactly should this be done? The docs specify to put the listeners inside useEffect but Im having the same issue of listener being called twice! Thanks

**Comment by sebastienlabine** [comment]
@hanijazzar I don't remember exactly what was the exact cause of the problem but I remember it's either one of them: 

1. I was calling enableScreen() from the directly from the app.tsx (without a useEffect hook) that was rendering two mounts, creating two instance of notificationsSubscribtion. The fix was to call enableScreen on mount with a useEffect hook.

```js
export default function App() {
  useEffect(() => {
    enableScreens();
  }, [])
```
2. The other situation might be that I was using Redux and react-navigation and was calling my hook from component that was wrapped inside the _Provider_ and _NavigationContainer_  component. The Provider or the navigation container component was forcing two mount (I don't know specifically why), calling my useEffect hook twice. 
```js
<Provider store={store}>
      <SafeAreaProvider>
        <NavigationContainer
          ref={navigationRef}
          linking={LinkingConfiguration}
          theme={smartbillsTheme}>
          <RootNavigator></RootNavigator> {/* I was registering the notifications in this component with the useEffectHook */}
          <StatusBar style="dark" />
        </NavigationContainer>
      </SafeAreaProvider>
    </Provider >
```

I simply put my hook at the root of my App.tsx 
```js
export const usePushNotifications = () => useEffect(() => {
        Notifications.setNotificationHandler({
            handleNotification: async () => ({
                shouldShowAlert: true,
                shouldPlaySound: true,
                shouldSetBadge: true,
            }),
        });
        const subscription = Notifications.addPushTokenListener((token) => { });
        const responseSubscription = Notifications.addNotificationResponseReceivedListener(notification => {
            handleNotificationPressed(notification);
        });
        const notficationSubscription = Notifications.addNotificationReceivedListener(notification => {
            handleNotificationReceived(notification);
        });
        return () => {
            notficationSubscription.remove();
            subscription.remove();
            responseSubscription.remove();
        }
    }
}, [])`
```
```js
export default function App() {
  useEffect(() => {
    enableScreens();
  }, []);
  usePushNotifications();
```

**Comment by hanijazzar** [comment]
@sebastienlabine thank you very much for your quick and detailed reply. My case is the second case, but even if I put the listener in App.js inside a useEffect it gets called multiple times! Any idea what might be the cause? Much appreciated

**Comment by sebastienlabine** [comment]
I looked back to my code and I created a ref for the navigationcontainer and passed it to my usePushNotification hook. Inside my hook, i registered the ref as dependency, and validated that the navigation existed before subscribing.

const usePushNotification = useEffect(()=> {
if(navigationRef) {
 // subscribe
}
},[navigationRef])

**Comment by hanijazzar** [comment]
@sebastienlabine thanks again for your help. I have tried the following but 'finalDeepLinkUrl' always gets logged twice whenever I click on a notification. Am I missing something?
            `const usePushNotification = (navigationRef) =>
                useEffect(() => {
                  if (navigationRef) {
                    // subscribe
                    const responseSubscription = Notifications.addNotificationResponseReceivedListener((response) => {
                      if (response.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER) {
                        const parsedNotification = Helpers.parseNotification(response.notification.request.content.data);
                        const finalDeepLinkUrl = Linking.makeUrl(parsedNotification.deeplink);
                        console.log('finalDeepLinkUrl');
                        console.log(finalDeepLinkUrl);
                        Linking.openURL(finalDeepLinkUrl);
                      }
                    });
                    return () => {
                      responseSubscription.remove();
                    };
                  }
                }, [navigationRef]);
            
              usePushNotification(navigationRef);
            `

**Comment by TomFrames** [comment]
Hi @hanijazzar - did you have any success with this? I have run into the same issue using SDK40

**Comment by hanijazzar** [comment]
Hi @TomFrames , Unfortunately i couldn't find any clean solution so I had to make a hack/workaround. Basically i added a separate screen that handles deeplinks, and in that screen i have a setTimeout which makes the navigation after some short delay, and i also have some checks in useEffect to check whether the component is mounted or not in order to only make the navigation to the correct screen once. So the deeplink screen gets opened twice and only the second time this screen makes the navigation to the correct screen (through checking isMounted and setTimeout). You need to show a loader or Splash Screen while on the Deeplink screen for a better UX, hope this helps

**Comment by ctwillie** [comment]
@sebastienlabine Were you able to definitively find the reason for this. I am experiencing the same thing and cannot determine why. Any help is appreciated!
