### ISSUE TITLE
Expo Audio prepareToRecordAsync broken on web: `TypeError: Cannot read property 'uri' of undefined`

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo#11840]
**Summary**

Calling prepareToRecordAsync results in `TypeError: Cannot read property 'uri' of undefined`.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Web

**SDK Version (managed workflow only)**

40

**Environment**

Snack.

**Reproducible demo or steps to reproduce from a blank project**

[Repro snack here](https://snack.expo.io/@mentor/intelligent-juice-box)

**Comment by cruzach** [comment]
looks like it's throwing [here](https://github.com/expo/expo/blob/master/packages/expo-av/src/Audio/Recording.ts#L319-L326), I think bc `prepareAudioRecorder` on web doesn't do anything: https://github.com/expo/expo/blob/fbbf9917976ff15252b9085341221ef3085bcd4f/packages/expo-av/build/ExponentAV.web.js#L131

**Comment by actuallymentor** [comment]
As a side note, that function also fails (all platforms) without a parameter with a nondescriptive error about not being able to have multiple recorders instantiated. Not sure if it is worth another issue but setting `Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY` as a default parameter might be nice.

**Comment by mnightingale** [comment]
See #11833 and PR #8791 which adds web support (was created for 39 so may need some changes to use with 40, looking a for some feedback on some changes).

Even with the web support added be aware uri isn't available from prepareAudioRecorder (PR returns null) since it isn't available until after the recording is created.
