### ISSUE TITLE
[Android] ReactProgressBarViewManager cannot be cast

### ISSUE THREAD

**Issue by danstepanov** [expo/expo#1184]
I'm running the most recent release of the expo sdk and upon running the android simulator, I get this error. I've been getting for a while and throughout previous releases of the sdk. Everything works on the iOS simulator. I've seen this error resolved by upgrading to react 0.25 but I'm not sure what that means as I'm running `react: 16.0.0`. Any help would be greatly appreciated.
<img width="601" alt="screen shot 2017-12-30 at 3 41 50 pm" src="https://user-images.githubusercontent.com/5482800/34457370-b6b3547a-ed7c-11e7-813a-d2968c252c71.png">

**Comment by brentvatne** [comment]
hey @danstepanov - please open a thread on forums with code to reproduce this!

**Comment by danstepanov** [comment]
@brentvatne No longer an issue but noted for the future :)

**Comment by kstolte** [comment]
@danstepanov Im running into this in 25. any tips on how you worked it out?
