### ISSUE TITLE
After exiting the managed workflow, use `gradlew assembleRelease` to build apk and report an error

### ISSUE THREAD

**Issue by mofengfs** [expo/expo#11851]
**Summary**

After everything was ready, I used `gradlew assembleRelease` to build apk, and an error was reported.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.3, 24.0.3, 25.0.3, 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.3
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

/android

`gradlew assembleRelease`

![image](https://user-images.githubusercontent.com/16655229/107001168-28c23800-67c4-11eb-9fe2-ff54b779558f.png)

**Comment by byCedric** [comment]
Hi @mofengfs! Sorry to hear you are having issues with this. It looks like it could be related to intermittent server issues on Bintray's end. When you run Gradle, it installs the Android libraries that your project needs. It's similar to `npm install` or `yarn install`.

If I test the failing URL from the screenshot, I get the `.pom` file without issues. Have you tried to run it again, or check if you have access to this URL manually?
- https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin-model/1.3.50/kotlin-gradle-plugin-model-1.3.50.pom

Hope this helps!

**Comment by mofengfs** [comment]
@byCedric 
I re-executed and still reported an error

![image](https://user-images.githubusercontent.com/16655229/107104518-fc0e2f00-685c-11eb-913b-506de65a7d77.png)

**Comment by mofengfs** [comment]
@byCedric 
Solution to the problem:
Upgrade java8u271 to the latest java8u281.
The naked leak workflow can be packaged normally and the apk startup image is displayed normally.https://github.com/expo/expo/issues/11849#issue-801843711
The apk packaged by the hosting workflow cannot display images normally, and your team needs to upgrade the java8 of the server.

**Comment by mofengfs** [comment]
@byCedric 

After expo exits to the bare workflow, .gitignore does not automatically generate the include
.hprof new file. As a result, the file of git push to github is too large, and I hope to improve it in time.
