### ISSUE TITLE
Expo getting crashed when I install npm packages after cloning from github [Working on different systems. The versions installed are same on both the system but one system is crashed]

### ISSUE THREAD

**Issue by dbhardwaj1904** [expo/expo#11853]

**Comment by byCedric** [comment]
Hi @dbhardwaj1904, thanks for writing in. But, in order for us to help to investigate this issue, we need more information other than "it crashes when I install npm packages". If you think this is an issue with Expo, and not with the environment it's crashing in, please open a new bug report. With the information we ask you to provide, we can help to check this out.

Hope this helps!
