### ISSUE TITLE
Hi my name is Bilal Sabugar and I am one of your user and i am facing problem in expo build:android pls help me out

### ISSUE THREAD

**Issue by BilalSabugar** [expo/expo#11859]
**Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?**

true

**Comment by BilalSabugar** [comment]
Hi my name is Bilal Sabugar and I am one of your user and i am facing problem in expo build:android pls help me out

**Comment by AdamJNavarro** [comment]
Hey Bilal, please feel welcome to go to our [Forums](https://forums.expo.io/) and post about your build issue. However, please provide as much information as you can. Introducing yourself and saying you have a problem does not equip us to help you out.

Cheers,
Adam
