### ISSUE TITLE
[bare][expo-contacts] freshly made project minimum deployment target pod install error

### ISSUE THREAD

**Issue by yarapolana** [expo/expo#11855]
**Summary**

Installing expo contacts with pod install in a freshly made project gives this error 
```[!] CocoaPods could not find compatible versions for pod "EXContacts":
  In Podfile:
    EXContacts (from `../node_modules/expo-contacts/ios`)

Specs satisfying the `EXContacts (from `../node_modules/expo-contacts/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.12.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 25, 28, 29
        Build Tools: 28.0.3, 29.0.1, 29.0.2, 30.0.2
        System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: 40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: 0.13.12 => 0.13.18 
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

Create a new project with bare configurations (and typescript)
yarn add expo-contacts
cd ios
pod install

NOTE: This is occurring with the following libs

```
expo-av
expo-camera
expo-contacts
expo-notifications triggers expo-constants error

```

**Comment by oliversieto** [comment]
Same for me, but  I'm trying these packages for now: expo-secure-store and expo-local-authentication. I'm updating my project, but I'm not able to run pod install because always return the same error.

**Comment by oliversieto** [comment]
@yarapolana I think the problem is target option. I change for 11.0 and pod install works. Because error describe that found a dependency, but they required a higher minimum deployment target.

**Comment by brentvatne** [comment]
thanks for writing this in, i'm going to update our docs and bare projects to target ios 11 - we are changing managed projects over to this in sdk 40 but we have already gone ahead and changed this on the latest version of expo-* libraries

**Comment by brentvatne** [comment]
https://github.com/expo/expo/commit/fb3a97779b97baeba0ca2da46cb52b8eeed21436

docs changes should be live soon, and i just rolled out updates to the bare js and typescript templates from expo-cli, which you should get soon once npm starts shipping it as latest

**Comment by yarapolana** [comment]
@oliversieto @brentvatne Thank you both for the fast reply.
Out of curiosity is it possible that changing the target could cause other perhaps older libs to fail or become incompatible?

**Comment by brentvatne** [comment]
@yarapolana - it shouldn't cause any issues with other libraries, but it does impact which ios versions can use the app. if you don't want to use a deployment target of 11 then you could also update it in on each pod by using a `post_install` hook, something like:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
```

ymmv if a lib isn't actually compatible with an older deployment target

**Comment by ProteanDev** [comment]
@brentvatne for some reason that post install hook isn't working with new expo releases.
