### ISSUE TITLE
Unable to link react-native-navigation after detach

### ISSUE THREAD

**Issue by James2516** [expo/expo#1185]
### Issue Description

I created a new project with [expo](https://github.com/expo/expo) and detached it.

When I try to run the iOS project in XCode, it gives an error
>'React/RCTRootView.h' file not found

If I create a new project with `react-native init` instead, I'm able to build with [react-native-navigation](https://github.com/wix/react-native-navigation) successfully. Why does it fail with expo?

### Steps to Reproduce / Code Snippets / Screenshots

https://github.com/James2516/expo-native-nav
Run `npm install` and try building the iOS project in Xcode.

Or start a new project:
1. `exp init`
2. `exp detach`
3. `yarn add react-native-navigation`
4. `react-native-link`
5. `cd ios && pod install`

I have tried adding React to build target ![](https://i.imgur.com/OCQ30Tj.png)

---
### Environment
* React Native Navigation version: ^1.1.323
* React Native version: expo sdk 24 / 0.51
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Failed at XCode build

**Comment by terribleben** [comment]
Hi there! This library doesn't appear to have a `podspec`, so `react-native link` is unable to install the library in a CocoaPods-compatible way. Like many apps in the iOS ecosystem, ExpoKit projects link their libraries with CocoaPods. The solution would either be to ask the library authors to make their library CocoaPods-compatible by adding a `podspec`, or until they do that, [use this temporary hack described in the Expo docs](https://docs.expo.io/versions/latest/guides/expokit.html#if-the-library-doesnt-support-cocoapods-react-native-link-may-fail-to-include-the-librarys-header-files-if-you-encounter-build-issues-locating-the-react-headers-you-may-need-to-manually-add-podsheaderspublic-to-the-header-search-paths-configuration-for-your-native-dependency-in-xcode-if-youre-not-familiar-with-xcode-search-xcode-help-for-configure-build-settings-to-get-an-idea-of-how-those-work-header-search-paths-is-one-such-build-setting-the-target-you-care-to-configure-is-the-one-created-by-react-native-link-inside-your-xcode-project-youll-want-to-determine-the-relative-path-from-your-library-to-podsheaderspublic).

**Comment by terribleben** [comment]
I'd also like to add that react-native-navigation historically makes some assumptions about the structure of React Native apps which may not be true with Expo. [This thread is very old](https://github.com/expo/expo/issues/13) and probably no longer applies, but I haven't personally verified that modern-day react-native-navigation will work out of the box with Expo, even if you fix the Header problem described above.

If you resolve the header issue and find that they still don't play nicely together, here's what you can do:

- Track a [feature request](https://expo.canny.io/feature-requests) that we work on making react-native-navigation compatible with Expo. (it's currently not a high priority for us.)
- Implement the required work yourself and submit a PR to react-native-navigation.
- Use [react-navigation](https://github.com/react-navigation/react-navigation) instead, which we know works with Expo and currently recommend.
