### ISSUE TITLE
Execution failed for task ':unimodules-react-native-adapter:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by sw-dev-code** [expo/expo#11867]
**Summary**

When I try to run the project which is ejected from Expo I'm receiving the following error. All the instructions for installation the unimodules-react-native are followed and double-checked.

node_modules\@unimodules\react-native-adapter\android\src\main\java\org\unimodules\adapters\react\PromiseWrapper.java:17: error: no interface expected here
/* package */ class PromiseWrapper extends Promise { 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

  Expo CLI 3.25.0 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.2 - C:\Programs\nodejs\node.EXE      
      npm: 6.14.5 - C:\Programs\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.0 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7

**Reproducible demo or steps to reproduce from a blank project**

Not sure where is the problem in the project. The project is too complicated to be copied.

**Comment by AdamJNavarro** [comment]
Hey @sw-dev-code, it looks like expo-cli version is quite out of date. I would first update that to the latest version (`4.1.6`). Unfortunately, if you're not able to provide a minimal, reproducible example for us to test on our end there isn't much we can do here. I can suggest trying to upgrade to a newer sdk version such as 40 and re-running expo eject. If you can provide the aforementioned minimal repro, we can revisit this!

Cheers,
Adam

**Comment by sw-dev-code** [comment]
@AdamJNavarro Thank you for the help. I will try your advice.

**Comment by super-potion** [comment]
@sw-dev-code have you been able to find a solution? Been stuck on this error for 3 days now :(

**Comment by brentvatne** [comment]
@super-potion - create a new issue and sharpe a [mcve](https://stackoverflow.com/help/minimal-reproducible-example)
