### ISSUE TITLE
MediaLibrary.getAssetInfoAsync(asset.id) return null on android

### ISSUE THREAD

**Issue by parice02** [expo/expo#11864]
**Summary**

When I do *MediaLibrary.getAssetInfoAsync(asset.id)*
I get *null* on android but it works on iOS.
I tested with Android 10 and iOS 14.2.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40 ejected

**Environment**

Expo CLI 4.0.17 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.4 - /usr/bin/node
      npm: 6.14.10 - /usr/bin/npm
    SDKs:
      Android SDK:
        Android NDK: 22.0.7026061
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

let asset = null;
let album = null;
/*
*photo* is ImagePicker.launchCameraAsync(...) result of expo-image-picker

asset = await MediaLibrary.createAssetAsync(photo.uri); // not null
album = await MediaLibrary.createAlbumAsync(
        "Album name",
        asset,
        false
      ); // not null
asset = await MediaLibrary.getAssetInfoAsync(asset.id) // return null on Android

**Comment by AdamJNavarro** [comment]
Hey @parice02, please provide a runnable repro case that we can spin up and run without additional steps. Copy and pasting code snippets will not suffice. Thanks!

Cheers,
Adam

**Comment by parice02** [comment]
> Hey @parice02, please provide a runnable repro case that we can spin up and run without additional steps. Copy and pasting code snippets will not suffice. Thanks!
> 
> Cheers,
> Adam

Okay! Thanks

**Comment by parice02** [comment]
The link for a repo [https://github.com/parice02/expo_media_lib_test.git](url)

**Comment by parice02** [comment]
> The link for a repo [https://github.com/parice02/expo_media_lib_test.git](url)

It's an expo

**Comment by parice02** [comment]
Sorry. I accidentally closed the issue. It's not closed

**Comment by parice02** [comment]
> The link for a repo [https://github.com/parice02/expo_media_lib_test.git](url)

or this [https://snack.expo.io/@parice02/72bcfc](snap)

**Comment by sereda93** [comment]
I have the same problem.
