### ISSUE TITLE
Unable to register a background fetch task because it is not defined, but it is already defined according to TaskManager

### ISSUE THREAD

**Issue by trajano** [expo/expo#11866]
**Summary**

TaskManager.isTaskDefined(NOTIFICATION_TASK_NAME) == true, but 

await BackgroundFetch.registerTaskAsync(NOTIFICATION_TASK_NAME, {
        minimumInterval: 60,
        startOnBoot: true,
        stopOnTerminate: false
      })

gives

```
[Unhandled promise rejection: Error: Task 'background-notifications-task' is not defined. You must define a task using TaskManager.defineTask before registering.]
```

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS
Android

**SDK Version (managed workflow only)**

40

**Environment**

```
  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      npm: 6.14.11 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0. - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed
```

**Reproducible demo or steps to reproduce from a blank project**

I can't recreate it on my MCVE, not sure what would cause the issue though.

Here are the relevant lines of the code though

```
      console.log("TaskManager.toggle before await", NOTIFICATION_TASK_NAME, TaskManager.isTaskDefined(NOTIFICATION_TASK_NAME));
      await BackgroundFetch.registerTaskAsync(NOTIFICATION_TASK_NAME, {
        minimumInterval: 60,
        startOnBoot: true,
        stopOnTerminate: false
      })

```

The output I get is

```

TaskManager.toggle before await background-notifications-task true

[Unhandled promise rejection: Error: Task 'background-notifications-task' is not defined. You must define a task using TaskManager.defineTask before registering.]
```

So it shows that the task was defined.

I even have the task manager defined in the logs using this code

```
    console.log("TaskManager.defineTask", NOTIFICATION_TASK_NAME, executor, TaskManager.isTaskDefined(NOTIFICATION_TASK_NAME));
    TaskManager.defineTask(NOTIFICATION_TASK_NAME, executor);
    console.log("TaskManager.defineTaskAfter", NOTIFICATION_TASK_NAME, executor, TaskManager.isTaskDefined(NOTIFICATION_TASK_NAME));
```

And the results are 

```
TaskManager.defineTask background-notifications-task [Function backgroundFetch] false
TaskManager.defineTaskAfter background-notifications-task [Function backgroundFetch] true
```

**Comment by trajano** [comment]
I just tried to do
```
      TaskManager.defineTask(NOTIFICATION_TASK_NAME, ()=>{console.log("HERE")});
      await BackgroundFetch.registerTaskAsync(NOTIFICATION_TASK_NAME, {
        minimumInterval: 60,
        startOnBoot: true,
        stopOnTerminate: false
      })

```
And it still fiails

**Comment by trajano** [comment]
Not sure what step I did exactly, but I just did an `expo update` which clears off the node_modules among other things, uninstalled the Expo Go app and now things are working again.

**Comment by abdulbasitideofuzion** [comment]
any progress here?

**Comment by trajano** [comment]
I closed this already since all I did was clear off node modules.

**Comment by Trader5050** [comment]
Can you explain what you mean by "uninstalled expo go app?"

You're not talking about ejecting from expo, correct, since then you're not actually building an expo app... Or do you mean you literally uninstalled the Expo Go App from the emulator/device only and just build as normal?

**Comment by BrodaNoel** [comment]
Guys, who has this problem, I recommend to remove `node_modules`, then remove `yarn.lock`, and then `yarn install` again.

Sometimes, you get 2 different versions of `expo-task-manager` installed, and that creates the problem
