### ISSUE TITLE
expo-media-library [expo-android] promise rejection: Error: Could not read file or parse EXIF tags

### ISSUE THREAD

**Issue by HVHMobileDeveloper** [expo/expo#11878]
**Summary**

- here is my code below
 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

    "expo": "~40.0.0",    "expo-media-library": "~10.0.0",

**Environment**

expo 

**Reproducible demo or steps to reproduce from a blank project**

async function mediaLibraryAsync() {
        const {status} = await MediaLibrary.requestPermissionsAsync();
        const media = await MediaLibrary.getAssetsAsync({
            mediaType: [
                MediaLibrary.MediaType.photo,
                MediaLibrary.MediaType.video,
            ],
            first: 10,
            sortBy: MediaLibrary.SortBy.modificationTime,
        });
        const video = await MediaLibrary.getAssetInfoAsync(media.assets[0]);

        console.log(video);
    }

@please review

**Comment by AdamJNavarro** [comment]
Hey @HVHMobileDeveloper, in order to help we need a minimal repro case that is publicly accessible and doesn't reference any external assets/configuration we don't have. Please provide a public repo link that we can clone and run to test the error you're referring to.

Cheers,
Adam
