### ISSUE TITLE
expo eject does not respect the android.permissions that were set in the app.json

### ISSUE THREAD

**Issue by allan-simon** [expo/expo#11880]
**Summary**

Most CI/CD build system that permits you to ship an android app made with expo  will do a `expo eject` on their side during the build process

As such it's important that expo eject respect as much as possible the configuration that was set in app.json

today that's not the case with android.permissions 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40.0.1

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: Linux 5.10 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.20.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.10 - /usr/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.* => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

Create a managed app

edit the app.json

put in the android section:

```
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#0000D1"
      },
      "package": "com.rosaly.app",
      "versionCode": 2,
      "permissions": []
    },
```

run expo eject  and compile the app

=> the resulting apk, has the correct package name, adaptive icons , but the permissions are still 

```
android.permission.INTERNET
android.permission.SYSTEM_ALERT_WINDOW
android.permission.READ_PHONE_STATE
android.permission.USE_FINGERPRINT
android.permission.USE_BIOMETRIC
android.permission.VIBRATE
android.permission.MODIFY_AUDIO_SETTINGS
android.permission.ACCESS_COARSE_LOCATION
android.permission.ACCESS_FINE_LOCATION
android.permission.ACCESS_BACKGROUND_LOCATION
android.permission.CAMERA
android.permission.RECORD_AUDIO
android.permission.READ_CONTACTS
android.permission.WRITE_CONTACTS
android.permission.READ_CALENDAR
android.permission.WRITE_CALENDAR
android.permission.READ_EXTERNAL_STORAGE
android.permission.WRITE_EXTERNAL_STORAGE
android.permission.WRITE_SETTINGS
android.permission.ACCESS_NETWORK_STATE
android.permission.WAKE_LOCK
com.google.android.c2dm.permission.RECEIVE
android.permission.FOREGROUND_SERVICE
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE
com.google.android.providers.gsf.permission.READ_GSERVICES
com.google.android.gms.permission.ACTIVITY_RECOGNITION
```

**Comment by mikeeus** [comment]
I was experiencing this issue too. The only way I was able to fix it was to remove 'expo-location' from my package-lock.json file and to comment out the `import { installWebGeolocationPolyfill } from 'expo-location';` line from `node_modules/expo/build/Expo.fx.expo.js`.

After commenting it out it looks 

```
import './environment/validate.fx';
import './environment/logging.fx';
import './environment/LogBox.fx'; // This must be imported exactly here
import './environment/react-native-logs.fx';
// load expo-asset immediately to set a custom `source` transformer in React Native
import 'expo-asset';
import Constants from 'expo-constants';
import * as Font from 'expo-font';
// import { installWebGeolocationPolyfill } from 'expo-location';
import * as React from 'react';
import { AppRegistry, Platform, StyleSheet } from 'react-native';
import DevAppContainer from './environment/DevAppContainer';
if (Constants.manifest && typeof Constants.manifest.env === 'object') {
    Object.assign(process.env, Constants.manifest.env);
}
// add the dev app container wrapper component on ios
if (__DEV__) {
    if (Platform.OS === 'ios') {
        // @ts-ignore
        AppRegistry.setWrapperComponentProvider(() => DevAppContainer);
        // @ts-ignore
        const originalSetWrapperComponentProvider = AppRegistry.setWrapperComponentProvider;
        // @ts-ignore
        AppRegistry.setWrapperComponentProvider = provider => {
            function PatchedProviderComponent(props) {
                const ProviderComponent = provider();
                return (React.createElement(DevAppContainer, null,
                    React.createElement(ProviderComponent, Object.assign({}, props))));
            }
            originalSetWrapperComponentProvider(() => PatchedProviderComponent);
        };
    }
}
if (StyleSheet.setStyleAttributePreprocessor) {
    StyleSheet.setStyleAttributePreprocessor('fontFamily', Font.processFontFamily);
}
// polyfill navigator.geolocation
// installWebGeolocationPolyfill();
// if (module && module.exports) {
//     if (global) {
//         const globals = require('./globals');
//         // @ts-ignore
//         global.__exponent = globals;
//         // @ts-ignore
//         global.__expo = globals;
//         // @ts-ignore
//         global.Expo = globals;
//     }
// }
//# sourceMappingURL=Expo.fx.expo.js.map
```

**Comment by allan-simon** [comment]
interesting , this specific package holds the whole android permission stuff ? (or at least put it back ?)
on my side currently the workaround I've used is to have in a folder `foobar` an edited copy of the androidmanifest , and I run a `cp` to override this file between the `expo eject` and android compilation phase of my CI/CD
