### ISSUE TITLE
[expo-yarn-workspaces] createMetroConfiguration should extend @expo/metro-config

### ISSUE THREAD

**Issue by giautm** [expo/expo#11896]
**Summary**

React-Native throw an error about custom font: Roboto-Black. It still load success without `react-native-svg-transformer` setup steps. After I change [`metro.config.js`](https://github.com/giautm/expo-workspace-font-bug/commit/04e304131106a39d673f856c4eacb8f693ee5f12#diff-0fd4d432bff6fc08b1c6378c0fb48a2e6ae5e67a32a2811dfa757682c4714b52), RN cause this error

```
Unrecognized font family 'Roboto-Black'

+[ABI40_0_0RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:]
    ABI40_0_0RCTFont.mm:329
+[ABI40_0_0RCTFont(ABI40_0_0UMReactFontManager) ABI40_0_0UMUpdateFont:withFamily:size:weight:style:variant:scaleMultiplier:]
```

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

```
  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.2/12B5025f - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed
```

**Reproducible demo or steps to reproduce from a blank project**

https://github.com/giautm/expo-workspace-font-bug

1) Ran `npx create-react-native-app --template with-yarn-workspaces` to create new project with this template
2) Apply patch from (this commit](https://github.com/giautm/expo-workspace-font-bug/commit/04e304131106a39d673f856c4eacb8f693ee5f12). This commit set up react-native-svg-transformer.

**Comment by brentvatne** [comment]
looks like we need to update `createMetroConfiguration` to extend `@expo/metro-config`

**Comment by giautm** [comment]
Hi @brentvatne , Thanks for fast reply. I just try to merge config from `@expo/metro-config` with `expo-yarn-workspaces`, and it resolve the problem. I hope expo-yarn-workspace with updated soon, ;)

https://github.com/giautm/expo-workspace-font-bug/commit/f7b12c8a08fdc946a1b8a166204c5ec30f451e6c

**Comment by brentvatne** [comment]
related: ENG-87

**Comment by giautm** [comment]
Closed in https://github.com/expo/expo/pull/11912
