### ISSUE TITLE
Need help about Camera (got error: Unknown pattern character 'Y')

### ISSUE THREAD

**Issue by keeratita** [expo/expo#1189]
Hi there!,

I've been trying to implement Camera on Expo to develop an android application. But I got this following error.
`Unknown pattern character 'Y'`

![screenshot_1514807823](https://user-images.githubusercontent.com/5326774/34467471-998b902e-ef25-11e7-945f-6d2757f97d10.png)

Found this error on both versions of `expo`: `23.0.0` and `24.0.2`.

Anyone has any idea, please?

**Comment by aalices** [comment]
@keeratita can you provide your app's code?

**Comment by saalihou** [comment]
Facing the same issue but only in the genymotion emulator. Happens when you try to take a picture.
Let me also mention that the camera does not display anything despite me activating the camera for the emulator. The built in camera app works fine.
Here is my code:
```
const photo = await this.camera.takePictureAsync({
      quality: 0.5,
      base64: false,
    });
```
Thank you for your time.

**Comment by nicknovitski** [comment]
The error message looks like it's from [SimpleDateFormat](https://developer.android.com/reference/java/text/SimpleDateFormat.html), which should recognize the pattern `Y`, but maybe that varies  across platforms.  And from the docs, we probably want to use `y` instead.

@saalihou Which version of expo are you using, and on which devices?

@keeratita Are you emulating a particular android version or device?

**Comment by sjchmiela** [comment]
This issue should have been fixed in https://github.com/expo/expo/commit/3c8b9111a9686456e62069b1bcfa4a1bdae6cb6f. Thanks for taking the time to notify us! 🙂
