### ISSUE TITLE
Allow loading icon to be a svg animation

### ISSUE THREAD

**Issue by martincarrera** [expo/expo#119]
It would be a nice feature to configure your own loading animation with a SVG file, instead of just making a static png file appear and disappear.

**Comment by jesseruder** [comment]
Makes sense! We definitely want to improve our loading screen API so will think about this.

**Comment by dk0r** [comment]
I'm holding off on Expo until there is proper SVG support..

**Comment by dikaiosune** [comment]
@dk0r can you provide more detail? We have SVG support in general, just not in a few places like loading icons.

**Comment by dikaiosune** [comment]
I added a comment on [a splash screen feature request](https://expo.canny.io/feature-requests/p/improved-splash-screen-api) to improve this. We'll track it there from now on. Thanks!
