### ISSUE TITLE
XDE complaining that react-native is not installed

### ISSUE THREAD

**Issue by FrancisRenaud** [expo/expo#1191]
Hi I'm having an issue identical to one that has been closed
.
On fresh install, the starter app seems fine.

However, as soon as I add an import statement such as import { TabNavigator } from 'react-navigation' XDE resuses to run my app and complains that react-native is not installed.

Should I downgrade npm to a 4.x version?

Or has anyone identified the source of the problem?

Thanks!

@rafWork Still having the issue?
@sodbileg Have you done something in particular that might have fixed it?

**Comment by FrancisRenaud** [comment]
By downgrading to npm 4.x.x the problem seems fixed.

**Comment by rafWork** [comment]
forgot to mention that I've downgraded it after read the issue fix. It worked fine.

**Comment by anp** [comment]
Hi! Glad you were able to get this working by using npm 4.
