### ISSUE TITLE
[expo-in-app-purchases] iOS promoted purchases not supported

### ISSUE THREAD

**Issue by juliar** [expo/expo#11924]
**Summary**

expo-in-app-purchases does not seem to support iOS promoted purchases (https://developer.apple.com/app-store/promoting-in-app-purchases/). I get an error "These in-app purchases can’t be promoted on the App Store because your latest approved binary doesn’t include the [SKPaymentTransactionObserver method](https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue).”, and indeed it looks like `paymentQueue(_:shouldAddStorePayment:for:)` is not implemented in https://github.com/expo/expo/blob/master/packages/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m.

For what it's worth, it looks like react-native-iap does support this (https://github.com/dooboolab/react-native-iap#how-do-i-handle-promoted-products-in-ios), but I'd like to avoid switching libraries if possible.

Thanks!

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

Expo CLI 3.23.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.23.2

**Reproducible demo or steps to reproduce from a blank project**

1. Configure in-app purchases for iOS, including the App Store Promotion section of each In-App Purchase configuration(s) in App Store Connect.
2. Implement in-app purchases in your app with expo-in-app-purchases.
2. Upload a build to App Store Connect.
3. See the "App Store Promotions" page in you App Store Connect account. You'll see the message "These in-app purchases can’t be promoted on the App Store because your latest approved binary doesn’t include the SKPaymentTransactionObserver method."

**Comment by anhkieet** [comment]
I am having the same issue :(

**Comment by Mistes974** [comment]
Same, anyone find a way to solve it ?

**Comment by Car-ElWilliams** [comment]
Same here, will try to add it natively instead

**Comment by janhorubala** [comment]
Any updates? I'm gonna switch to https://github.com/dooboolab/react-native-iap

**Comment by kesha-antonov** [comment]
Hi
Did you solve it?
