### ISSUE TITLE
Linking.getInitialURL() returns "https://expo.io:443/" instead of null when no scheme is specified

### ISSUE THREAD

**Issue by adamjuhasz** [expo/expo#11920]
**Summary**

When the standalone application is cold started `Linking.getInitialURL()` returns `https://expo.io:443/<team>/<slug>` instead of `null`.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.3.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.14 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.58 => 0.12.58 
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

```typescript
import { Linking } from "react-native";

let singletonLock = false;

export const DeepLinking = (): JSX.Element => {
  const history = useHistory();

  useEffect(() => {
    if (singletonLock === false) {
      singletonLock = true;

      void Linking.getInitialURL().then((incomingLink) => {
        if (incomingLink !== null) {
          if (incomingLink === "https://expo.io:443/@team/slug") {
            console.log(`DeepLinking incomingLink was ${incomingLink}`);
            return; /* bug with Expo? */
          }

          history.replace(normalizeLink(incomingLink));
        }
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return <></>;
};
```

```json
"android": {
      "intentFilters": [
        {
          "action": "VIEW",
          "autoVerify": true,
          "data": [
            {
              "scheme": "https",
              "host": "<website>",
              "pathPrefix": "/"
            }
          ],
          "category": ["BROWSABLE", "DEFAULT"]
        }
      ]
    },
```

**Comment by brentvatne** [comment]
do you have a scheme set for your app?

**Comment by adamjuhasz** [comment]
We have the `https` scheme with our host set up but not a custom scheme like `superapp://`

app.json relevant section
```json
"android": {
      "intentFilters": [
        {
          "action": "VIEW",
          "autoVerify": true,
          "data": [
            {
              "scheme": "https",
              "host": "<website>",
              "pathPrefix": "/"
            }
          ],
          "category": ["BROWSABLE", "DEFAULT"]
        }
      ]
    },
```

**Comment by adamjuhasz** [comment]
Linking does work when an actual link is clicked, we just get the extra `getInitialURL` with `https://expo.io:443/..` when the app is opened directly. 

We attempted to follow https://docs.expo.io/guides/linking/?redirected#universaldeep-links-without-a-custom-scheme as best as we could, did we miss something?

**Comment by adamjuhasz** [comment]
@brentvatne Just wanted to bump this and see if we should close the issue, hate to have dangling open issues...

**Comment by npedrini** [comment]
@adamjuhasz were you able to resolve why `getInitialURL` returns the Expo project url when the app is opened directly? We're seeing the same and it's causing some issues with url parsing.

**Comment by adamjuhasz** [comment]
We were not and had to add code to filter expo urls and short-circuit the url processing code if detected.

**Comment by brentvatne** [comment]
this fix will be deployed in sdk 42

**Comment by fikip** [comment]
Hi there, I'm still facing this issue when building a standalone app for android.No issues for iOS build, or when in dev / expo go mode. 
Is it definitely fixed for both platforms? Cheers!

**Comment by brentvatne** [comment]
@fikip - it should be fixed, if you are encountering a similar problem please create a new issue with a reproducible example :)
