### ISSUE TITLE
App icon incorrect in testflight

### ISSUE THREAD

**Issue by rueiwoqp** [expo/expo#11925]
**Summary**

I renamed my app name, slug and bundleIdentifier in app.json and updated my icon using the top level "icon" property as well as duplicating it in the ios and android properties in app.json.  The icon shows correctly on the Expo Build Details page but in App Store Connect / My Apps, it shows the default Expo icon. In test flight and on my device it shows the old icon. 

I have verified that the old icon image doesn't even exist in my project any longer, so it must be cached somewhere.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40.0.1

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.8.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /Users/moby/.rvm/gems/ruby-2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

I don't think there is a way to repro this from a blank project.

**Comment by brentvatne** [comment]
https://stackoverflow.com/a/40419540/659988

**Comment by brentvatne** [comment]
oh i missed this one:

> The icon shows correctly on the Expo Build Details page but in App Store Connect / My Apps, it shows the default Expo icon

can you share your icon file? maybe something is wrong with it that missed our validations.

**Comment by rueiwoqp** [comment]
![Uploading icon.png…]()

**Comment by rueiwoqp** [comment]
![image](https://user-images.githubusercontent.com/42003718/107713275-bba91980-6c7f-11eb-9c73-e93102df77da.png)

**Comment by brentvatne** [comment]
looks like that png has transparency. you can re-export and uncheck this transparency box. i'm surprised it actually built the app given this, we check for transparency in the build process - https://github.com/expo/expo-cli/blob/834bc98db754d332d37c51ef9fcde386cf36d2a7/packages/expo-cli/src/commands/build/ios/utils/image.ts

more info https://github.com/expo/fyi/blob/master/remove-alpha-channel.md

<img width="1030" alt="Screen Shot 2021-02-11 at 3 44 39 PM" src="https://user-images.githubusercontent.com/90494/107713426-0fb3fe00-6c80-11eb-9bcd-fe3586547ee4.png">

**Comment by rueiwoqp** [comment]
Got it, thanks.  The transparency made it look correct in both dark and light modes...

**Comment by brentvatne** [comment]
@rueiwoqp - did you build with `expo build:ios` or `eas build`?

**Comment by rueiwoqp** [comment]
`expo build:ios`

**Comment by rueiwoqp** [comment]
It's still bizarre to me that it somehow used the old icon when it no longer exists. :)

**Comment by brentvatne** [comment]
that's the ios caching behavior mentioned in the original reply

**Comment by rueiwoqp** [comment]
BTW, can you delete the icon above? I haven't launched yet ;) Thanks

**Comment by brentvatne** [comment]
it seems like in your case the image you shared had *no transparent pixels* but did have an alpha channel. it seems like https://github.com/expo/expo-cli/pull/456 was intended to consider these types of icons as valid, but from your experience here that may not actually work.. but it would surprise me if this is the first time someone has tried to use a png with an alpha channel without transparent pixels, so i wonder if something else might have gone wrong. let me know how removing the alpha channel works out for you
