### ISSUE TITLE
 [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null. work find in expo client but failing on expo android:build

### ISSUE THREAD

**Issue by athishsreeram** [expo/expo#11923]
**Summary**

02-11 16:52:10.003 13172 13248 E ReactNativeJS: Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
02-11 16:52:10.003 13172 13248 E ReactNativeJS:
02-11 16:52:10.003 13172 13248 E ReactNativeJS: To fix this issue try these steps:
02-11 16:52:10.003 13172 13248 E ReactNativeJS:
02-11 16:52:10.003 13172 13248 E ReactNativeJS:   • Run `react-native link @react-native-async-storage/async-storage` in the project root.
02-11 16:52:10.003 13172 13248 E ReactNativeJS:
02-11 16:52:10.003 13172 13248 E ReactNativeJS:   • Rebuild and restart the app.
02-11 16:52:10.003 13172 13248 E ReactNativeJS:
02-11 16:52:10.003 13172 13248 E ReactNativeJS:   • Run the packager with `--reset-cache` flag.
02-11 16:52:10.003 13172 13248 E ReactNativeJS:
02-11 16:52:10.003 13172 13248 E ReactNativeJS:   • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.
02-11 16:52:10.003 13172 13248 E ReactNativeJS:
02-11 16:52:10.003 13172 13248 E ReactNativeJS:   • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest
02-11 16:52:10.003 13172 13248 E ReactNativeJS:
02-11 16:52:10.003 13172 13248 E ReactNativeJS: If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/react-native-async-storage/issues
02-11 16:52:10.018   297  5320 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
02-11 16:52:10.032 13172 13249 E unknown:ReactNative: CatalystInstanceImpl caught native exception
02-11 16:52:10.032 13172 13249 E unknown:ReactNative: com.facebook.react.common.Javascr

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40

**Environment**

expo android:build

when trying to run the apk

**Reproducible demo or steps to reproduce from a blank project**

NA

**Comment by brentvatne** [comment]
i believe that i responded to you here: https://forums.expo.io/t/androidruntime-java-lang-runtimeexception-expo-encountered-a-fatal-error-error-rnc-asyncstorage-nativemodule-asyncstorage-is-null/48743/2
