### ISSUE TITLE
Update Lottie to 2.3.1

### ISSUE THREAD

**Issue by spoord** [expo/expo#1193]
Would it be possible to update to the latest version of Lottie in an upcoming release? v2.3.1 includes some changes that make it easier to define the start and end frame as discussed here https://github.com/airbnb/lottie-react-native/issues/178  
Thanks! 😄

**Comment by brentvatne** [comment]
tracking this internally. we will update unless it causes some difficult to solve issues in the process, in that case we will need to do it in following sdk
