### ISSUE TITLE
[docs] Background Fetch Known Issues is Misleading

### ISSUE THREAD

**Issue by Stefata** [expo/expo#11936]
**Summary**

Background Fetch Known Issues (on top of the docs almost) mentions it doesn't work when app is terminated or closed on top of the page. However, further down below on the docs, you can see stop terminate and startOnBoot parameters stating it works for Android.

**Link to the related docs page**

https://docs.expo.io/versions/latest/sdk/background-fetch/

I am developing an Android app and was close to ejecting and going with the  bare workflow, since I needed to use a background fetch library. I noticed that in the docs: https://docs.expo.io/versions/latest/sdk/background-fetch/ Under know issues it states: 
`BackgroundFetch only works when the app is backgrounded, not if the app was terminated or upon device reboot.` 

However down below, you can see:

> `stopOnTerminate (boolean) -- Whether to stop receiving background fetch events after user terminates the app. Defaults to true. (Android only)`

> `startOnBoot (boolean) -- Whether to restart background fetch events when the device has finished booting. Defaults to false. (Android only)`

I find this rather confusing. I saw some posts where people got the background fetch working on Android with app terminating and closing using the managed workflow. Can you please clarify if that is the case? I suppose `Known issues` included iOS, but if it works on Android, that should be mentioned!

**Comment by jasan-s** [comment]
@StefanBratanov  I'm running into the same issue, the background fetch task runs while app is in background but not after its terminated on Android. Did you find a solution? Did you end up using expo?
