### ISSUE TITLE
Google Mobile Ads SDK 7.64+

### ISSUE THREAD

**Issue by uakhundz** [expo/expo#11934]
**Summary**

Admob is showing the following warning:

Some of your iOS apps require a GMA SDK update To keep ads serving normally and minimize a loss in ad revenue, implement the GMA SDK 7.64.0 (or later) for your iOS apps. And configure the SKAdNetwork in your apps with Google's network ID.

Do we know when the expo-ads-admob module will be upgraded to Google Mobile Ads SDK 7.64+?

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

39.0

**Environment**

n/a

**Reproducible demo or steps to reproduce from a blank project**

Just using the standard module steps for admob in Expo

**Comment by valdrox** [comment]
I'm on SDK 40 (bare) with { "expo-ads-admob": "~8.4.0"} and getting this notification too.

**Comment by SethuSenthil** [comment]
> I'm on SDK 40 (bare) with { "expo-ads-admob": "~8.4.0"} and getting this notification too.

There is a separate issue for bare workflows
#11941

**Comment by montanojd** [comment]
i got the same error in Admob

**Comment by alexscarlett** [comment]
+1 on this, any update guys?

**Comment by yuta-hidaka** [comment]
Expo team said Admob's priority is not hight. So someone not Expo team have to handle this issue with PR😢

https://forums.expo.io/t/admob-native-ads-support/47192/8

**Comment by SethuSenthil** [comment]
> Expo team said Admob's priority is not hight. So someone not Expo team have to handle this issue with PR😢
> 
> https://forums.expo.io/t/admob-native-ads-support/47192/8

Oh no! Does ejecting allow us to use a different AdMob library with no hassles? We need to update the SDK ASAP since iOS 14.5 is coming out anytime in the upcoming weeks and will have a detrimental effect on ad revenue.

**Comment by brentvatne** [comment]
> Expo team said Admob's priority is not hight. So someone not Expo team have to handle this issue with PR😢
> 
> https://forums.expo.io/t/admob-native-ads-support/47192/8

this person is not an expo employee.

we may consider this for sdk 41, but it has come pretty close to our code cutoff. if someone wants to open a pull request to bump the version and is able to test it adequately, that would help.

**Comment by montanojd** [comment]
> > Expo team said Admob's priority is not hight. So someone not Expo team have to handle this issue with PR😢
> > https://forums.expo.io/t/admob-native-ads-support/47192/8
> 
> Oh no! Does ejecting allow us to use a different AdMob library with no hassles? We need to update the SDK ASAP since iOS 14.5 is coming out anytime in the upcoming weeks and will have a detrimental effect on ad revenue.

My revenue is already low, iOS apps from this month doesn't show ads.

**Comment by SethuSenthil** [comment]
> > Expo team said Admob's priority is not hight. So someone not Expo team have to handle this issue with PR😢
> > https://forums.expo.io/t/admob-native-ads-support/47192/8
> 
> this person is not an expo employee.
> 
> we may consider this for sdk 41, but it has come pretty close to our code cutoff. if someone wants to open a pull request to bump the version and is able to test it adequately, that would help.
> 
> edit: oh maybe you're referring to me in that thread. the thread is very different from what is discussed here - bumping the version of google ads vs adding a new feature.

Yeah exactly, I was confused as well. They talking about Native Ads (which would be a cool addition) but most of us are currently concerned about the SDK version

**Comment by yuta-hidaka** [comment]
> > Expo team said Admob's priority is not hight. So someone not Expo team have to handle this issue with PR😢
> > https://forums.expo.io/t/admob-native-ads-support/47192/8
> 
> this person is not an expo employee.
> 
> we may consider this for sdk 41, but it has come pretty close to our code cutoff. if someone wants to open a pull request to bump the version and is able to test it adequately, that would help.
> 
> edit: oh maybe you're referring to me in that thread. the thread is very different from what is discussed here - bumping the version of google ads vs adding a new feature.

@brentvatne 

Sorry for mislead.

I was thinking same priority as bumping the version of google ads vs adding a new feature.

**Comment by brentvatne** [comment]
just a reminder to everyone here - this is all open source! if this is important for you, you can absolutely contribute! here is where the code for expo-ads-admob lives: https://github.com/expo/expo/tree/master/packages/expo-ads-admob

**Comment by justindannguyen** [comment]
Awesome if we have this merged for Expo 41 release.
