### ISSUE TITLE
Image resizeMode 'center' doesn't work in published Expo app

### ISSUE THREAD

**Issue by lachlanglen** [expo/expo#11939]
**Summary**

In **published** Expo app, `Image` overflows its container `View` when `resizeMode=center` is specified. `Image` should be centered and contained within its container `View`.

This does not occur when running the unpublished app on a device (iPhone SE 2nd Generation) or a simulator.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.5.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0. - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

https://snack.expo.io/@lachlanglen/supportive-juice-box

I'm running a super simple app where I want an `Image` to be centered within its container `View`, using `resizeMode='center'`.

```
import * as React from 'react';
import { View, Image } from 'react-native';

export default function App() {
  return (
    <View style={{
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    }}>
      <View style={{
        height: 30,
        width: 30,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'lightgrey',
      }}>
        <Image
          resizeMode='center'
          styles={{
            width: '100%',
            height: '100%',
          }}
          source={require('./assets/hexagon2x.png')} />
      </View>
    </View>
  );
}
```

Also at [this snack.](https://snack.expo.io/@lachlanglen/supportive-juice-box)

When I run the unpublished project on my device (iPhone SE 2nd Gen) or on a simulator, I get the desired behavior, with the `Image` centered in the middle of the containing `View`:

![image](https://user-images.githubusercontent.com/54282009/107859894-854bd580-6e0a-11eb-8bb1-bb5f8d22aeb7.png)

However, when I run `expo publish` on this exact project and open the published app, the `Image` is no longer contained within the `View`:

![image](https://user-images.githubusercontent.com/54282009/107859889-7e24c780-6e0a-11eb-936a-5b65b4ae21f8.png)

**Comment by brentvatne** [comment]
it looks like an upstream react-native bug, if you run `expo eject` and then do a build with build configuration set to "Release" you can observe the same behavior

**Comment by lachlanglen** [comment]
@brentvatne Thanks for the fast reply! Guess I'll stay up to date with that RN issue and store/access the images remotely in the meantime.
