### ISSUE TITLE
Expo notification icon changed to expo icon after build

### ISSUE THREAD

**Issue by lHersey** [expo/expo#11940]
**Summary**

Hello! :)

I rebuild my app (managed workflow) and I noticed that  the notification icon was changed to the expo icon (was working before, I didn't touch that part of the code. so I think it's something with the build) 

My notification icon is transparent, white color, 96x96 .

One change that I did was add the adaptative icon for android (That is why I rebuild) But Idk how it would affect.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /var/folders/8x/7l7_wyss71nd6k7c457vy4fw0000gn/T/yarn--1613245695845-0.0698875867472597/node
      Yarn: 1.22.10 - /var/folders/8x/7l7_wyss71nd6k7c457vy4fw0000gn/T/yarn--1613245695845-0.0698875867472597/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

I can't share a snack since the issue is the notification icon.

Notification app.json:

```
"notification": {
      "color": "#F3933F",
      "icon": "./assets/images/notification-icon.png"
    },
```

I ran `expo doctor` to ensure that the notification image is found,  even in the build logs it finds the icon and upload it to cloudfront correctly.

UPDATED: the info of the icon file
`assets/images/notification-icon.png: PNG image data, 96 x 96, 8-bit gray+alpha, non-interlaced`

**Comment by cruzach** [comment]
Sorry- if I understand correctly you're saying that previously this was working, and now it's not (the only change being adding android adaptive icon)? Are you build with `expo build:android`?

**Comment by lHersey** [comment]
Yes, I am using `expo build:android`, I use OTA updates to test, but I think other expo dependency is affecting this (not affecting via OTA but via build).

I just created a new managed project, added the minimum notification code and is working (even copied the same code `app.json` config, same code to schedule and same icon image) Idk what is happening but we can say that is not a direct bug.

**Comment by cruzach** [comment]
Okay, unfortunately without a reproducible demo I don't know how much help I can be 😅

You could inspect the resulting APK for your image asset maybe? Just to tell if it's actually there or not

**Comment by lHersey** [comment]
In fact, I renamed the apk to zip, and the icon file is not there :/

In the project were I tried to replicate the issue it does exist with the name `shell_notification_icon.png`

checked path : ./res/drawable-hdpi-v4/

**Comment by lHersey** [comment]
After more deep checking, `shell_notification_icon.png` exist but is the expo icon

**Comment by cruzach** [comment]
are you using the exact same image and app.json config in both?

This is the code responsible for changing the expo icon to the provided one- https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/AndroidIcons.ts#L235-L253 - it should delete the expo icon no matter what

**Comment by lHersey** [comment]
Yes I'm using the exact same image in both projects, same config, same path, same expo-cli versoin.

![shell_notification_icon](https://user-images.githubusercontent.com/18200355/107865799-f8b40e00-6e2f-11eb-869a-02b1368b627d.png)

It is not generating the rest of assets, in the logs of the project were I tried to replicated the issue there is 

1. res/drawable-hdpi-v4/shell_notification_icon.png
2. res/drawable-mdpi-v4/shell_notification_icon.png
3. res/drawable-xhdpi-v4/shell_notification_icon.png
4. res/drawable-xxhdpi-v4/shell_notification_icon.png
5. etc.. all the other sizes

These have my custom icon.


In the project with the problem according with the logs only exist `res/drawable-xxxhdpi-v4/shell_notification_icon.png` and is the expo icon but at the beginning  of the logs (where is reading the manifest) I found this

```
"notification":{"icon":"./assets/notification-icon.png","color":"#F3933F","iconUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/fb61c8630678ab05adbdc89b0b2fda67"}
```

So I can be sure the the build found the asset, but for some reason is not getting to the code that you

**Comment by lHersey** [comment]
On the project with the problem I'm using `expo-asset`  but since this is a problem in the build and no startup I can say that is not related

**Comment by lHersey** [comment]
I fixed my problem but I think there is an issue, the problem was that on adaptive icon I was using 

```
"adaptiveIcon": {
        "backgroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#fff"
 },
```

and I changed it to:
```
"adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#fff"
  },
```

And is working! <3

Was my mistake but my question is: should this affect the notification icon?

**Comment by lHersey** [comment]
@cruzach I got a repo to reproduce the issue

https://github.com/lHersey/notification-icon-issue/blob/master/app.json

If `adaptiveIcon.backgroundImage` is set instead of `foregroundImage` the notification icon is not working

**Comment by cruzach** [comment]
thanks! was able to reproduce it. My guess is this issue lies somewhere [here](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/AndroidIcons.ts#L179-L205)
