### ISSUE TITLE
getLocalizationAsync should return whether the phone uses 24 or 12 hour format [missing feature]

### ISSUE THREAD

**Issue by chybisov** [expo/expo#11948]
**Summary**

getLocalizationAsync from expo-localization package doesn't return hour format. This is not actually a bug, BUT it's critical for localization, because sometimes user can use 24 hour format for `en_*` locale and currently there is no way to determine this settings in managed workflow. 
Сonsidering all of the above even simple localization (e.g. time of sent messages in chat) can't be developed in managed workflow.

Maybe we could consider to add this function as part of the expo-localization package https://github.com/zoontek/react-native-localize#uses24hourclock ?

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 15.8.0 - C:\Program Files\nodejs\node.EXE        
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.5.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: ^17.0.1 => 17.0.1 
      react-dom: ^17.0.1 => 17.0.1 
      react-native: ^0.63.4 => 0.63.4 
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

// localization object don't have hour format
const localization = await Localization.getLocalizationAsync();

**Comment by EvanBacon** [comment]
Probably want something like this:
```swift
  static func isLocaleUsing24HourTime(locale: Locale) -> Bool {
    let timeFormatter = DateFormatter()
    timeFormatter.locale = locale
    timeFormatter.dateStyle = DateFormatter.Style.none
    timeFormatter.timeStyle = DateFormatter.Style.short
    
    let text = timeFormatter.string(from: Date())
    return !text.contains(timeFormatter.amSymbol) && !text.contains(timeFormatter.pmSymbol)
  }
```

Problem with this approach is that it doesn't return `true` on American devices even if the device manually changed from 12 to 24 hour format.
