### ISSUE TITLE
expo-ads-admob is using an old version of Google-Mobile-Ads-SDK and its prompting an admob error

### ISSUE THREAD

**Issue by arichayo** [expo/expo#11941]
**Summary**

Google admob gives this error:

"Some of your iOS apps require a GMA SDK update To keep ads serving normally and minimize a loss in ad revenue, implement the GMA SDK 7.64.0 (or later) for your iOS apps. And configure the SKAdNetwork in your apps with Google's network ID."

Even when i started a fresh React Native project and installed expo-ads-admob it still installs Google-Mobile-Ads-SDK (7.55.1)

If Admob is insisting to have 7.64.0 or later i think we should get this fixed!

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40.0.1

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      npm: 7.5.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.1 => 40.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.15.0 => 0.15.0 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

run `npm install expo-ads-admob` then `cd ios` and `pod install`

**Comment by montanojd** [comment]
Expo Admob Sdk Upgrade is urgent

**Comment by brentvatne** [comment]
please open a pull request
