### ISSUE TITLE
Expo [web] document-picker missing uri data for multiple files

### ISSUE THREAD

**Issue by buffaloDeveloper** [expo/expo#11946]
**Summary**

https://docs.expo.io/versions/latest/sdk/document-picker/

When you enable "multiple" and select multiple documents, the picker result only includes the URI (base64 data) for the first file.  Ideally you want the uri data for each file in the "output" array.

Tested on Chrome.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Web

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: 0.14.11 => 0.14.11 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

const _pickDocument = async () => {
		
		let pickerResult = await DocumentPicker.getDocumentAsync({
			type: props.mediaType,
			copyToCacheDirectory: true,
			multiple: props.allowsMultipleSelection
		});

		console.log('pickerResult:', pickerResult);

		if (!pickerResult.cancelled) {
		  
		  // check if mobile upload
		  if (pickerResult.uri.startsWith('file:')){
		  	// convert local file to base64
		  	const base64 = await FileSystem.readAsStringAsync(pickerResult.uri, { encoding: FileSystem.EncodingType.Base64 })
		  	pickerResult.uri = base64;
		  }

		  //props.callback(pickerResult);
		}
	}

**Comment by bwilson-ux** [comment]
Has anyone found a solution around this issue as of yet? Thanks in advance!

**Comment by oparisblue** [comment]
You can (web only) use the JS `FileReader` API to read the file URIs from `output` yourself. Something like:

```ts
//...

const files: FileList = files.output;

return Promise.all(
    Object.keys(files).map(
      (_key, i) =>
        new Promise((resolve) => {
          const reader = new FileReader();
          const file = files[i];

          reader.onload = () => {
            resolve({
              dataUri: reader.result as string,
              name: file.name,
              size: file.size
            });
          };
          reader.readAsDataURL(file);
        })
    )
  );
```
 ought to do it
