### ISSUE TITLE
Exp buid:ios not work

### ISSUE THREAD

**Issue by anhnam00** [expo/expo#1194]
Hello everybody,
I’m having a problem with a building for IOS. i ran my command: exp build:ios -c and this is my screen:

https://expo-discourse-uploads.s3-us-west-1.amazonaws.com/optimized/2X/7/73a217fb349c353be4cde50961068cfe1fd4b3d8_1_594x500.png

Expo stopped at this message : “Validating Credentials…” and not continue to ran. I tried again many times but nochange!

My expo version: 47.3.7 and my app config:

{
“expo”: {
“name”: “Smart”,
“description”: “App”,
“slug”: “sboz”,
“privacy”: “public”,
“sdkVersion”: “23.0.0”,
“version”: “1.0.0”,
“orientation”: “portrait”,
“primaryColor”: “#cccccc”,
“icon”: “./assets/icon.png”,
“splash”: {
“image”: “./assets/splash.png”,
“resizeMode”: “contain”,
“backgroundColor”: “#ffffff”
},
“ios”: {
“bundleIdentifier”: “com.home.smart”,
“buildNumber”: “3.0”,
“supportsTablet”: true
},
“android”: {
“package”: “com.home.smart”,
“versionCode”: 1

}
},
“name”: “Smart”,
“displayName”: “Smart”
}

Please help me!
Thank you,

**Comment by fxfactorial** [comment]
Hi @anhnam00 , 

Do you have WSL enabled? 

Please run `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`, restart your machine and try again.

**Comment by fxfactorial** [comment]
User got it building as reported on forums
