### ISSUE TITLE
expo-font Makes app throw "unrecognized font family" error in bare workflow, expo 40

### ISSUE THREAD

**Issue by kevinrodriguez-io** [expo/expo#11953]
**Summary**

So, basically, after creating a "bare" workflow typescript app, I proceeded to install the following two dependencies:

```
"expo-font": "~8.4.0",
"@expo-google-fonts/open-sans": "^0.1.0",
```

(Those were resolved by `expo install expo-font @expo-google-fonts/open-sans`).

So, first things first, I created this on my root application

```tsx
const App: FC = () => {
  return (<Text style={{fontFamily: 'OpenSans_700Bold'}}>I'm working</Text>);
}

const AppWrapper: FC = () => {
  const [loading, error] = useFonts({
    OpenSans_300Light,
    OpenSans_400Regular,
    OpenSans_600SemiBold,
    OpenSans_700Bold,
  })

  if (error) {
    return (
      <View style={styles.container}>{JSON.stringify(error, null, 2)}</View>
    )
  }

  if (loading) {
    return (
      <View style={styles.container}>
        <ActivityIndicator />
      </View>
    )
  }
  return <App />
}
```

So, I basically don't know what to do, the font itself may be broken but I do require this specific font, or maybe expo-font is broken, because I tried adding the font to 'assets/fonts/*.ttf' and didn't work either. I must be missing something on my metro config but It is definitely not documented anywhere.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

1- Init app with bare TS workflow.
2- Install expo font and your favorite google font by running: `expo install expo-font @expo-google-fonts/open-sans` (try with open-sans, just to discard).
3- Create a wrapper component that loads the fonts.
4- Create a simple text component that uses those fonts down the tree.

![SS](https://user-images.githubusercontent.com/6248571/108072437-83615c80-702c-11eb-8eee-15678fb6cd0d.png)

**Comment by kevinrodriguez-io** [comment]
By the way: I already looked at similar issues trying to fix this and I found stuff more related to the SVG transformer, things that didn't make sense for a new project. The weird thing is I think at some point worked, so this may also be a cache thing, which I already tried to fix by clearing watchman, but I don't know, may also be related to the sdk.

**Comment by brentvatne** [comment]
this appears to be due to a misunderstanding of the hook return value.

```js
  const [loading, error] = useFonts({
    OpenSans_300Light,
    OpenSans_400Regular,
    OpenSans_600SemiBold,
    OpenSans_700Bold,
  })
```

if you change `loading` to `loaded` and update your other logic accordingly, this works as expected. see the documentation: https://docs.expo.io/versions/latest/sdk/font/#usefonts

full working example from your code:

```js
import React from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { useFonts } from "expo-font";
import {
  OpenSans_300Light,
  OpenSans_400Regular,
  OpenSans_600SemiBold,
  OpenSans_700Bold,
} from "@expo-google-fonts/open-sans";

const App = () => {
  return (<Text style={{fontFamily: 'OpenSans_700Bold'}}>I'm working</Text>);
}

const AppWrapper = () => {
  const [loaded, error] = useFonts({
    OpenSans_300Light,
    OpenSans_400Regular,
    OpenSans_600SemiBold,
    OpenSans_700Bold,
  })

  if (error) {
    return (
      <View style={styles.container}>{JSON.stringify(error, null, 2)}</View>
    )
  }

  if (!loaded) {
    return (
      <View style={styles.container}>
        <ActivityIndicator />
      </View>
    )
  }
  return <App />
}

export default AppWrapper;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
});
```

**Comment by kevinrodriguez-io** [comment]
@brentvatne Such a silly mistake, I must've been really tired. Thanks for clarifying!

**Comment by brentvatne** [comment]
@kevinrodriguez-io - honestly it took me maybe 5 minutes of looking at the code to realize it. it's a little tricky

**Comment by bj97301** [comment]
> this appears to be due to a misunderstanding of the hook return value.
> 
> ```js
>   const [loading, error] = useFonts({
>     OpenSans_300Light,
>     OpenSans_400Regular,
>     OpenSans_600SemiBold,
>     OpenSans_700Bold,
>   })
> ```
> 
> if you change `loading` to `loaded` and update your other logic accordingly, this works as expected. see the documentation: https://docs.expo.io/versions/latest/sdk/font/#usefonts
> 
> full working example from your code:
> 
> ```js
> import React from "react";
> import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
> import { useFonts } from "expo-font";
> import {
>   OpenSans_300Light,
>   OpenSans_400Regular,
>   OpenSans_600SemiBold,
>   OpenSans_700Bold,
> } from "@expo-google-fonts/open-sans";
> 
> const App = () => {
>   return (<Text style={{fontFamily: 'OpenSans_700Bold'}}>I'm working</Text>);
> }
> 
> const AppWrapper = () => {
>   const [loaded, error] = useFonts({
>     OpenSans_300Light,
>     OpenSans_400Regular,
>     OpenSans_600SemiBold,
>     OpenSans_700Bold,
>   })
> 
>   if (error) {
>     return (
>       <View style={styles.container}>{JSON.stringify(error, null, 2)}</View>
>     )
>   }
> 
>   if (!loaded) {
>     return (
>       <View style={styles.container}>
>         <ActivityIndicator />
>       </View>
>     )
>   }
>   return <App />
> }
> 
> export default AppWrapper;
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     alignItems: "center",
>     justifyContent: "center",
>   },
> });
> ```

You are a life saver!  Thank you.
