### ISSUE TITLE
Expo-AV: Recorded sounds on Android cannot be played on iOS

### ISSUE THREAD

**Issue by emmanuel-D** [expo/expo#11952]
**Summary**

I am using the `Audio.Recording` class of `Expo-AV` to record sounds on my Chat App.
On **Android** when using the default audio preset config for `LOW_QUALITY`, it returns an audio file with the extension `.3gp`
And on **iOS** it returns an audio file with the extension.caf

The problem is that the Sound Player cannot play `.caf` files on **Android** and the same way, `.3gp` files cannot been played on **iOS**.

I also try to use the same `extension` using `.mp3, .mp4, .wav, ...` for both OS but, the result is the same: Audio files recorded on Android cannot be played on iOS, but the opposite is possible.

Is there any way to record audio files so that there can been played on both OS Platforms automatically ?

I have also try order customs recordingOptions, but nothing works for both OS

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
        System Images: android-16 | ARM EABI v7a, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-navigation: ~4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

Here is how I record the audio.
````
await Audio.requestPermissionsAsync();
            await Audio.setAudioModeAsync({
                allowsRecordingIOS: true,
                playsInSilentModeIOS: true,
            });
            console.log('Starting recording..');
            const recording = new Audio.Recording();

            const RECORDING_OPTIONS_PRESET_LOW_QUALITY: RecordingOptions = {
                android: {
                    extension: '.wav',
                    outputFormat: RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_MPEG_4,
                    audioEncoder: RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AMR_NB,
                    sampleRate: 44100,
                    numberOfChannels: 2,
                    bitRate: 128000,
                },
                ios: {
                    extension: '.wav',
                    audioQuality: RECORDING_OPTION_IOS_AUDIO_QUALITY_MIN,
                    sampleRate: 44100,
                    numberOfChannels: 2,
                    bitRate: 128000,
                    linearPCMBitDepth: 16,
                    linearPCMIsBigEndian: false,
                    linearPCMIsFloat: false,
                },
            };

            await recording.prepareToRecordAsync(RECORDING_OPTIONS_PRESET_LOW_QUALITY);
            await recording.startAsync();
            console.log({recording})
            this.setState({recording});
            recording.setProgressUpdateInterval(1000);
````

After that, the audio is saved in an Amazon S3 and can be reached via an url like https://example.file.wav

The play the sound in the App, I use the following code:

````
const {sound} = await Audio.Sound.createAsync(
                   {uri: 'https://example.file.wav', headers: {}},
                   undefined,
                   onRecordingStatusUpdate,
                   false
               );
               setSound(sound);
               const playbackStatus: AVPlaybackStatus = await sound.playAsync();
               setIsPlaying(true);
````

**Comment by actuallymentor** [comment]
I'm encountering the same issue. Did you find a codec/extension config that works cross platform?

It's a bit embarrassing that a cross platform framework uses non-cross platform defaults...

**Comment by actuallymentor** [comment]
Allright I found the overlap:

```js
// Below code runs in a function

const { ios, android } = Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY
await recorder.prepareToRecordAsync( {
	android: android,
	ios: {
		...ios,
		extension: '.mp4',
		outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC
	}

} )
```

Might I also add that according to #1545 the expo module uses ExoPlayer and not the Andriod media player which according to that ticket makes the documentation link to the android codecs faulty.

**Comment by emmanuel-D** [comment]
I will try your code snippet and tell you back if it works on both OS

**Comment by dcuti8** [comment]
> Allright I found the overlap:
> 
> ```js
> // Below code runs in a function
> 
> const { ios, android } = Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY
> await recorder.prepareToRecordAsync( {
> 	android: android,
> 	ios: {
> 		...ios,
> 		extension: '.mp4',
> 		outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC
> 	}
> 
> } )
> ```
> 
> Might I also add that according to #1545 the expo module uses ExoPlayer and not the Andriod media player which according to that ticket makes the documentation link to the android codecs faulty.
save my life！！ thanks very much！

**Comment by emmanuel-D** [comment]
@actuallymentor I also tested your presets and it works for both Platforms

**Comment by emmanuel-D** [comment]
@actuallymentor Are there any ways to compress that generated audio files directly using Expo ?

**Comment by actuallymentor** [comment]
@jonsamp sorry for the direct tag. Does it make sense for me to create a PR that makes these the defaults?

I'm guessing cross-platform incompatibility wasn't a design decision.

**Comment by jonsamp** [comment]
This seems like a very reasonable PR, since it makes this API more universal! Thanks for finding a solution and contributing. If you need help with the PR, or review, let me know and I can connect you with people at Expo more familiar with our SDK.

**Comment by Enneson** [comment]
> Allright I found the overlap:
> 
> ```js
> // Below code runs in a function
> 
> const { ios, android } = Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY
> await recorder.prepareToRecordAsync( {
> 	android: android,
> 	ios: {
> 		...ios,
> 		extension: '.mp4',
> 		outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC
> 	}
> 
> } )
> ```
> 
> Might I also add that according to #1545 the expo module uses ExoPlayer and not the Andriod media player which according to that ticket makes the documentation link to the android codecs faulty.

Works as should, thanks a lot, mate!

**Comment by AbdelhamidLarachi** [comment]
Thanks that works very well, This is an updated solution with newer update : 
 
`const { ios, android } = Audio.RecordingOptionsPresets.HIGH_QUALITY;`
 `const { recording } = await Audio.Recording.createAsync(
                {
                    android: android,
                    ios: {
                        ...ios,
                        extension: '.mp4',
                        outputFormat: IOSOutputFormat.MPEG4AAC
                    }
                } as Audio.RecordingOptions
            );
`

**Comment by JCcastagne** [comment]
Seems that if you use the LOW_QUALITY preset, Android and iOS use different file extensions. But since the last comment above (2 years ago), high quality seems to be working, since using the HIGH_QUALITY preset does uses the same file extension for audio files.

Thank you for the answer above.


A copy of the presets enum:
```
RecordingOptionsPresets.HIGH_QUALITY = {
  isMeteringEnabled: true,
  android: {
    extension: '.m4a',
    (...)
  },
  ios: {
    extension: '.m4a',
    (...)
  },
  web: {
    (...)
  },
};
LOW_QUALITY
RecordingOptionsPresets.LOW_QUALITY = {
  isMeteringEnabled: true,
  android: {
    extension: '.3gp',
    (...)
  },
  ios: {
    extension: '.caf',
    (...)
  },
  web: {
    (...)
  },
};
```

**Comment by jaiw23** [comment]
This isnt working still. I am getting the below error when trying to play audio on IOS (Iphone 15) recorded on Android (Android14) with setting Audio.RecordingOptionsPresets.HIGH_QUALITY. Audio recorded on IOS plays fine on Android

Error:
 ERROR  [Error: An unknown error occurred (1685348671) - The AVPlayerItem instance has failed with the error code -11800 and domain "AVFoundationErrorDomain".]

Saving file as : 
formData.append('file', {
        uri: recordingPath,
        name: `audio_${requestId}.m4a`,
        type: 'audio/mp4',
      });
