### ISSUE TITLE
RFC: Audio playback in background

### ISSUE THREAD

**Issue by alejomendoza** [expo/expo#1195]
# Title

- **Start date**: 2018-01-02
- **Main Author:** @alejomendoza

## 1 Summary

This RFC aims to propose a user-facing API to support audio playback in background.

## 2 Motivation

Audio playback in background is one of the most common and necessary features for a lot of apps in fields like music, broadcasting, radio and entertainment. 

### 3.1 Support two new key-value pairs in the mode object when calling the method `Expo.Audio.setAudioModeAsync(mode)`

- `playsInBackgroundModeIOS`: a boolean selecting if your experience’s audio should play in background mode on iOS. This value defaults to `false`.
- `playsInBackgroundModeAndroid`: a boolean selecting if your experience’s audio should play in background mode on Android. This value defaults to `false`.

### 3.2 Implementation example

```
import React from 'react';
import { Audio } from 'expo';

export default class AudioPlayer extends React.Component {
  constructor(props) {
    super(props);
  }

  async componentDidMount() {
    try {
      Audio.setAudioModeAsync({
        playsInBackgroundModeIOS: true,
        playsInBackgroundModeAndroid: true,
      });
    } catch (e) {
      this.props.errorCallback({
        type: 'NON_FATAL',
        message: 'setAudioModeAsync error',
        obj: e,
      });
    }
  }

  render() {
    return (<View/>)
  }
}
```

**Comment by anp** [comment]
Hi! Thanks for the detailed request. We currently have an [open feature request](https://expo.canny.io/feature-requests/p/audio-playback-in-background) for this, please check it out!

**Comment by alejomendoza** [comment]
oh ok, check out @brentvatne last comment, @anp in that thread.

**Comment by elgiovanno** [comment]
Hi. Any updates on this?

**Comment by pixelvitamina** [comment]
btw. we managed to enable background audio by detaching to ExpoKit and practically disabling the following two methods: 

https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi24_0_0/host/exp/exponent/modules/api/av/AVModule.java#L148

https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Core/Api/AV/EXAV.m#L120

We used https://github.com/tanguyantoine/react-native-music-control for Lockscreen controls.

@anp @brentvatne wouldn't it be possible to allow this to be configurable in Expo?

**Comment by machester4** [comment]
Hi @pixelvitamina, when i try to modify the AVModule file from android studio it tells me that the file is just read. I would appreciate if you could help me. Thank you

**Comment by alejomendoza** [comment]
Thanks for the insight @pixelvitamina I had to fork the expo client, still not sure of how to create a release version with the changes, package it and use it on the detached app. https://github.com/skyhitz/expo/pull/1/commits/9319e504e19ea8b365e152df6da85e507b4c339a

**Comment by pixelvitamina** [comment]
@machester4 @alejomendoza 
basically we forked and recompiled expoview and add it back to our repo at this path
app/android/maven/host/exp/exponent/expoview/25.0.0/expoview-25.0.0.aar

**Comment by machester4** [comment]
thx @pixelvitamina

**Comment by alejomendoza** [comment]
How do you recompile expoview @pixelvitamina ?

**Comment by alejomendoza** [comment]
Hmm that didn't work for us, we were able to recompile expoview though :/

**Comment by ntk860** [comment]
It is taking vey long

**Comment by ryekerjh** [comment]
Any production-ready implementation possibilities anytime soon?

**Comment by brentvatne** [comment]
no timeline available at the moment, I'm only starting to investigate this now

**Comment by williamswebworks** [comment]
What is the update for this? We are now 9 months since the initial request. Audio backgrounding is such a basic need that I am surprised this hasn't been implemented yet.

**Comment by ryekerjh** [comment]
@williamswebworks as per Expo official documentation: `Expo apps don't support background code execution (running code when the app is not foregrounded or the device is sleeping). This means you cannot use background geolocation, play audio in the background, handle push notifications in the background, and more. This is a work in progress.`
So it doesn't look like they have any plans at all.
https://docs.expo.io/versions/v26.0.0/introduction/why-not-expo#expo-apps-dont-support-background-code-execution

**Comment by williamswebworks** [comment]
So what options do I have then?

**Comment by ryekerjh** [comment]
I had to refactor my application (eject or detach from Expo, depending on how you built your CRNA proejct) into a pure react native project and use a third-party piece of software. I went with [react native video](https://github.com/react-native-community/react-native-video) but there are several others. We Ejected, so I used [this guide](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md). Good luck!

**Comment by samescolas** [comment]
Guess I'll just not use expo for my music player, then. Time for a rewrite..

**Comment by AdamJNavarro** [comment]
Closing this in favor of the Feature Request here: https://expo.canny.io/feature-requests/p/audio-playback-in-background

**Comment by thomashagstrom** [comment]
Still no update on the FR though

**Comment by vkiranmaniya** [comment]
> btw. we managed to enable background audio by detaching to ExpoKit and practically disabling the following two methods:
> 
> https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi24_0_0/host/exp/exponent/modules/api/av/AVModule.java#L148
> 
> https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Core/Api/AV/EXAV.m#L120
> 
> We used https://github.com/tanguyantoine/react-native-music-control for Lockscreen controls.
> 
> @anp @brentvatne wouldn't it be possible to allow this to be configurable in Expo?

The Links you provided is not working. can you please post the details here?
