### ISSUE TITLE
[docs] Seems eslint-config-universe has a dependency on typescript not mentioned in the README

### ISSUE THREAD

**Issue by triptec** [expo/expo#11969]
**Summary**

Oops! Something went wrong! :(

ESLint: 7.20.0

Error: Failed to load plugin '@typescript-eslint' declared in 'package.json » eslint-config-universe/native » ./shared/typescript.js': Cannot find module 'typescript'

**Link to the related docs page**

https://github.com/expo/expo/blob/master/packages/eslint-config-universe/README.md

**Comment by jaquinocode** [comment]
So wondering why the pull request mentioned here hasn't been accepted. It's just a change to a README. The README makes it seem like you can still use it with just javascript, thus wasting a lot of devs' time & causing frustration.

**Comment by jaquinocode** [comment]
@byCedric
