### ISSUE TITLE
Local Assets missing in standalone ios build

### ISSUE THREAD

**Issue by GFean** [expo/expo#11987]
**Summary**

Expected behaviour : Local images and assets should be displayed normally.
Current behaviour : Local images are shown in simulator and on the real device if using development build through Xcode, but they're gone in production mode (which I download from testflight), However, If I close and reopen the app several times they are displayed normally. 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 17, 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: ^17.0.1 => 17.0.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

init expo project,
make some changes and add local assets.
eject.
run expo publish
build with Xcode
upload to testflight.
download on real device.

Hi there, I have ejected expo project and everytime I build the project with Xcode I run expo publish, so the javascript bundle will get updated. After uploading the build to Testflight and downloading it to the real device there're no local assets being displayed. So the icons and images I have in my local directory are just not there. 
After closing and opening the app again (sometimes it needs to be done several times) the assets are being shown again. I think this happens because of expo publish, because this was the way expo publish was working before - you had to open the app, close it and reopen it to get the over-the-air-update.. 
The assets in simulator are displayed, even if I connect my Iphone and build and run it on real device, the icons are always there. This happens only in production builds and I don't know why. I tried almost everything - like copying assets folder to ios directory and so on, but the problem persists. 
I think this is something more related with expo and javascript bundle. (before, when I was using expo build:ios assets were always being displayed and I've never had this kind of problem )

**Comment by RocKer004** [comment]
Hi, any updates about this ? I guess it's something wrong with expo-splash screen and preloading resources.. after ejecting something doesn't work like expected

**Comment by brentvatne** [comment]
please provide a reproducible example. this works as expected, so something is happening beyond the steps that you're explaining

**Comment by brentvatne** [comment]
this was likely due to invalid metro config. we warn about this with eas build. make sure to follow https://docs.expo.dev/guides/customizing-metro/ when customizing metro.config.js.
