### ISSUE TITLE
Cannot import expo-notifications - TypeError: Cannot read property 'getRegistrationInfoAsync' of undefined

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#11982]
**Summary**

The following line of code

`import * as Notifications from "expo-notifications";`

gives me the error TypeError: undefined is not an object (evaluating '_ServerRegistrationModule.default.getRegistrationInfoAsync')

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS device (web app)

**SDK Version (managed workflow only)**

^40.0.0

**Environment**

```
 Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: ^17.0.1 => 17.0.1
      react-dom: 16.11.0 => 16.11.0
      react-native: ^0.63.4 => 0.63.4
      react-native-web: ^0.15.0 => 0.15.0
    Expo Workflow: managed
```

`"@unimodules/core": "~6.0.0"`

**Reproducible demo or steps to reproduce from a blank project**

1. Install "expo-notifications": "~0.8.2",

      "expo install expo-notifications"

2. Add this to app.json

     "android": {
         "useNextNotificationsApi": true,
         ...

3. Import expo-notifications

     `import * as Notifications from "expo-notifications";`

WHAT I HAVE TRIED
---------------------------------
**After getting the error:**
I have reinstalled node_modules completly
I have upgraded from expo 40.0.0 to 40.0.1 and react native to the last version
Also, I got a warning:

      File 'expo-module-scripts/tsconfig.base' not found. In the file "tsconfig.json" of expo-notifications.

So, I decided to install expo-module-scripts
I have also tried to install @unimodules/react-native-adapter in my project (just in case I needed to have it installed for the operation of the library)

**The problem still persists.**

Module which causes the error
--------------------------------------

**expo-notifications > build > DevicePushTokenAutoRegistration.fx.js**  

`if (ServerRegistrationModule.getRegistrationInfoAsync) {`

ServerRegistrationModule is undefined. What have I done wrong?

Note: testing on iOS (iPhone 11) and Expo GO (also tested in Samsung Galaxy S8)

**Comment by VictorioMolina** [comment]
Also, I have tested the legacy implementation, and it works fine.

Why am I getting this error when importing the new  module??

**Comment by VictorioMolina** [comment]
Here all my dependencies:

This might be a conflict, but not sure.

```
"dependencies": {
    "@grpc/grpc-js": "^1.2.8",
    "@react-native-async-storage/async-storage": "^1.13.4",
    "@react-native-community/datetimepicker": "3.0.4",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/compat": "^5.3.13",
    "@react-navigation/material-bottom-tabs": "^5.3.13",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "@unimodules/core": "~6.0.0",
    "expo": "^40.0.1",
    "expo-asset": "~8.2.1",
    "expo-av": "~8.7.0",
    "expo-camera": "~9.1.0",
    "expo-constants": "~9.3.3",
    "expo-file-system": "~9.3.0",
    "expo-font": "~8.4.0",
    "expo-image-manipulator": "~8.4.0",
    "expo-linear-gradient": "^8.3.1",
    "expo-location": "~10.0.0",
    "expo-media-library": "~10.0.0",
    "expo-notifications": "~0.8.2",
    "expo-permissions": "~10.0.0",
    "firebase": "7.9.0",
    "firebase-tools": "^9.3.0",
    "lottie-react-native": "~2.6.1",
    "moment": "^2.29.1",
    "prop-types": "15.5.7",
    "react": "^17.0.1",
    "react-dom": "16.11.0",
    "react-native": "^0.63.4",
    "react-native-console-time-polyfill": "^1.2.1",
    "react-native-easy-toast": "^1.2.0",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-get-random-values": "1.5.0",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-maps": "0.27.1",
    "react-native-modal-datetime-picker": "^8.9.3",
    "react-native-paper": "^4.7.1",
    "react-native-reanimated": "~1.13.0",
    "react-native-redash": "14.1.1",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "~2.15.2",
    "react-native-snap-carousel": "^4.0.0-beta.5",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-vector-icons": "^7.1.0",
    "react-native-web": "^0.15.0",
    "react-native-windows": "^0.63.16",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "shorthash": "^0.0.2",
    "uuid": "^8.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.2.3",
    "jest-expo": "^40.0.2",
    "react-test-renderer": "^16.13.1"
  },
```

**Comment by VictorioMolina** [comment]
Solved. It was a conflict between 2 deps. I have created another project and reinstall the deps of the original project (unless jest). As it was working on the new project, I decided to delete jest from the original and, then, I was able to import it.

**Comment by VictorioMolina** [comment]
Okey I am stupid, I didn't update the sdkVersion of my app.json when moving from sdk 36 to 40. Sorry.

**Comment by kazeemOnis** [comment]
hi @VictorioMolina  how did you solve this issue, did you simply just add sdkVersion to your app.json?

**Comment by TheEarlyNerd** [comment]
^ I'm wondering the same thing. Actually, in my case, I'm trying to downgrade the SDK and I'm wondering how to make everything match.

**Comment by VictorioMolina** [comment]
@TheEarlyNerd @kazeemOnis Hey! I am using Expo SDK 40, last version, and everything works fine. Just make sure that, after uograding via yarn or npm, you have the same versión in ur app.json. If not, just change it un your editor and sabe the file!

**Comment by titanve** [comment]
Hello @VictorioMolina

I did what you suggested and I'm still getting the error, do you know about another fix?

Thank you.

**Comment by davidjbng** [comment]
To anyone still experiencing this issue I solved it by using a named import.

```diff
- import * as Notifications from 'expo-notifications'`
+ import { usePermissions, /* ... */ } from 'expo-notifications'`
```
