### ISSUE TITLE
AppleAuthentication.signInAsync never resolve

### ISSUE THREAD

**Issue by junqdu** [expo/expo#11995]
**Summary**

Trying to integrate AppleAuthentication.signInAsync, but after entering password in the simulator, and clicking on continue, nothing happens, just infinite spinner.
If I enter the wrong password, the password do get reset.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

Can't reproduce on Snack

![Screen Shot 2021-02-20 at 2 35 57 AM](https://user-images.githubusercontent.com/4250728/108593415-6b3d5600-7328-11eb-88dd-564e32235058.png)

Trying to integrate AppleAuthentication.signInAsync, but after entering password in the simulator, and clicking on continue, nothing happens, just infinite spinner.
If I enter the wrong password, the password do get reset.

**Comment by RocKer004** [comment]
Hi, from my personal experience this doesn't work in simulator as it needs the fingerprint to proceed. You need a real device and it'll work

**Comment by junqdu** [comment]
@RocKer004 That's weird, you need the password ADN fingerprint?

**Comment by RocKer004** [comment]
Yes, somehow you can't use apple sign in without the fingerprint, I'm not sure if it's possible to set up biometrics in simulator (but theoretically this could help), otherwise you'll need a real device and you have to use the standalone build for this (scanning expo barcode won't work), because the authorization_code that expo emulated build returns is somehow invalid (apple will always return invalid_grant). Not sure why does this happen, but I've been struggling with this during weeks until I found out that authorization_code generated by standalone ios build (although it looks like the same) is different. 
Get an ios device and deploy the app to testflight, or build on real device using Xcode (if you have bare workflow).

**Comment by junqdu** [comment]
@RocKer004 Wow, this helps a lot, thanks! I been scratching my head for a week now, since I wasn't able to debug it at all, no console nor promise rejection.

Wonder if they should update the [doc](https://docs.expo.io/versions/latest/sdk/apple-authentication/), to mark the iOS simulator as not working...

**Comment by RocKer004** [comment]
Lol yeah, running the app through expo start and viewing that with expo go app on ios is even weirder :D it seems to be working, it even gives you the authorization_code, but in the end that code won't work, if you try to pass it to apple (from back-end) it'll return error with message invalid_grant. We've spent weeks to debug this, searching the problem in our back-end, then I just tried to try on standalone production build and it has just worked.
Alright, I'm glad if I helped somehow, 
good luck ;)

**Comment by TheAnkurPanchani** [comment]
Although it works on simulator with iOS version 13.x when running standalone app. Seems like issue with iOS 14.x.
I tried following steps to run it on iPhone 11 with iOS 13.7 and it worked.
- `expo eject` (to run standalone app)
- `npx react-native run-ios --simulator="iPhone 11 (13.7)"` (replace `iPhone 11` with your simulator name, replace `13.7` with any 13.x available on your device)

This will launch standalone app on simulator and when you try apple authentication flow, it will work. So if you just want to check apple authentication related configuration and changes, this should help. Although I recommend to check it on actual iPhone with iOS 14.x once to be sure.

Note: you can delete `ios` and `android` directories created by `expo eject` command and continue with managed workflow if you want after testing.
Second Para from [here](https://docs.expo.io/workflow/customizing/):
`The process of ejecting is easily reversible so don't worry about experimenting with it. Just commit any changes you want to keep and then follow along with this guide. If you decide you want to abort it, just check out your most recent commit. You can also reverse it in the future by deleting the ios and android directories.`

**Comment by RocKer004** [comment]
Yup, with ejected projects you can try just `npx react-native run-ios --configuration Release`

**Comment by dylanrandle** [comment]
I am also finding that `AppleAuthentication.signInAsync` hangs when running in Expo Go app on the iOS simulator (iOS 15.0). Does anyone have any suggestions for how to resolve this?

**Comment by vaibhavzignuts** [comment]
error while npx expo run:ios  --device
