### ISSUE TITLE
Calendar.updateEventAsync Not Updating Single Instance of a Recurring Event

### ISSUE THREAD

**Issue by duggster** [expo/expo#11998]
**Summary**

I am trying to update a particular instance of a recurring event but having trouble selecting the instance by start date, and also updating the single instance. First thing is I create a recurring event:

```
let startDate = new Date(START_DATE_ISO); //"2021-02-19T14:00:00.000Z"
let endDate = new Date(END_DATE_ISO); //"2021-02-19T15:00:00.000Z"
let details = {
  title: "Create Test 123",
  startDate: startDate,
  endDate: endDate,
  timeZone: "America/New_York",
  recurrenceRule: {
	frequency: Calendar.Frequency.DAILY,
	interval: 1
  }
}
let id = await Calendar.createEventAsync(calendarId, details);
```
Then I retrieve the first few days of events and filter to just the newly created event id:

```
let events = await Calendar.getEventsAsync([calendarId], start, end);
events = events?.filter((event) => event.id == eventId) || [];
```
Now I select the SECOND instance in the list, and attempt to update the event. In order to specify the instance of the recurring event, I am using the startDate directly from the loaded event instance and passing a Date object to the recurringEventOptions.instanceStartDate parameter of Calendar.updateEventAsync as per the documentation.

**Test (1): Date Object**

```
let instanceStartDate = new Date(instance.startDate); // console.log output shows "2021-02-20T14:00:00.000Z"
let recurringEventOptions = {
	instanceStartDate, 
	futureEvents: false
};
await Calendar.updateEventAsync(id, details, recurringEventOptions)
```
This results in an error on iOS (iOS 14):

> “An exception was thrown while calling ExpoCalendar.getEventByIdAsync with arguments ( "11135253-44E6-470E-9386-54B321A28C2E", { } ): -[__NSDictionaryM __baseAttributedString]: unrecognized selector sent to instance 0x28394b060” in [snack internals] << [snack internals] << << u …"

This same code appears to complete successfully on Android, but looking at the event in the calendar shows that it has actually incorrectly updated all events and not just the specific instance.

**Test (2): Date String From Loaded Event**
Ok, so the next thing I try is just leaving the startDate as a string the same way it was loaded.

`instanceStartDate = instance.startDate; // console.log output shows "2021-02-20T14:00:00.000Z"`

When updating, this results in a different error on iOS:

> Event with id 2A38B025-ADDF-4141-ACEA-A903DBC2077C could not be found" in [snack internals] << [snack internals] << << u …

This does the same thing on Android as with the Date object - it appears to complete successfully on Android, but looking at the event in the calendar shows that it has actually incorrectly updated all events and not just the specific instance.

**Test (3): Date String with Timezone Offset**
The last thing I tried was hardcoding the instance start date with the timezone offset:

`instanceStartDate = "2021-02-20T09:00.00-05:00";`

When updating now, on iOS it appears to complete successfully however only the FIRST instance of the recurring is updated, instead of the second one corresponding to the instance start date as expected.

On Android, it does the same thing as the first two tests, updating all instances.

**Expected Behavior:**
Calendar.updateEventAsync() should be able to update a single specific instance of an event using an instance start date easily derived directly from a loaded event coming from Calendar.getEventsAsync() or Calendar.getEventAsync(). I would prefer not to have to deal with any timezone offsets if at all possible.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

 Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^3.12.0 => 3.13.0
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

https://snack.expo.io/@duggster/update-event-test

**Comment by JSimai** [comment]
Has this been addressed at all?

**Comment by jahnagoldman** [comment]
> **Summary**
> 
> I am trying to update a particular instance of a recurring event but having trouble selecting the instance by start date, and also updating the single instance. First thing is I create a recurring event:
> 
> ```
> let startDate = new Date(START_DATE_ISO); //"2021-02-19T14:00:00.000Z"
> let endDate = new Date(END_DATE_ISO); //"2021-02-19T15:00:00.000Z"
> let details = {
>   title: "Create Test 123",
>   startDate: startDate,
>   endDate: endDate,
>   timeZone: "America/New_York",
>   recurrenceRule: {
> 	frequency: Calendar.Frequency.DAILY,
> 	interval: 1
>   }
> }
> let id = await Calendar.createEventAsync(calendarId, details);
> ```
> 
> Then I retrieve the first few days of events and filter to just the newly created event id:
> 
> ```
> let events = await Calendar.getEventsAsync([calendarId], start, end);
> events = events?.filter((event) => event.id == eventId) || [];
> ```
> 
> Now I select the SECOND instance in the list, and attempt to update the event. In order to specify the instance of the recurring event, I am using the startDate directly from the loaded event instance and passing a Date object to the recurringEventOptions.instanceStartDate parameter of Calendar.updateEventAsync as per the documentation.
> 
> **Test (1): Date Object**
> 
> ```
> let instanceStartDate = new Date(instance.startDate); // console.log output shows "2021-02-20T14:00:00.000Z"
> let recurringEventOptions = {
> 	instanceStartDate, 
> 	futureEvents: false
> };
> await Calendar.updateEventAsync(id, details, recurringEventOptions)
> ```
> 
> This results in an error on iOS (iOS 14):
> 
> > “An exception was thrown while calling ExpoCalendar.getEventByIdAsync with arguments ( "11135253-44E6-470E-9386-54B321A28C2E", { } ): -[__NSDictionaryM __baseAttributedString]: unrecognized selector sent to instance 0x28394b060” in [snack internals] << [snack internals] << << u …"
> 
> This same code appears to complete successfully on Android, but looking at the event in the calendar shows that it has actually incorrectly updated all events and not just the specific instance.
> 
> **Test (2): Date String From Loaded Event** Ok, so the next thing I try is just leaving the startDate as a string the same way it was loaded.
> 
> `instanceStartDate = instance.startDate; // console.log output shows "2021-02-20T14:00:00.000Z"`
> 
> When updating, this results in a different error on iOS:
> 
> > Event with id 2A38B025-ADDF-4141-ACEA-A903DBC2077C could not be found" in [snack internals] << [snack internals] << << u …
> 
> This does the same thing on Android as with the Date object - it appears to complete successfully on Android, but looking at the event in the calendar shows that it has actually incorrectly updated all events and not just the specific instance.
> 
> **Test (3): Date String with Timezone Offset** The last thing I tried was hardcoding the instance start date with the timezone offset:
> 
> `instanceStartDate = "2021-02-20T09:00.00-05:00";`
> 
> When updating now, on iOS it appears to complete successfully however only the FIRST instance of the recurring is updated, instead of the second one corresponding to the instance start date as expected.
> 
> On Android, it does the same thing as the first two tests, updating all instances.
> 
> **Expected Behavior:** Calendar.updateEventAsync() should be able to update a single specific instance of an event using an instance start date easily derived directly from a loaded event coming from Calendar.getEventsAsync() or Calendar.getEventAsync(). I would prefer not to have to deal with any timezone offsets if at all possible.
> 
> **Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**
> 
> managed
> 
> **What platform(s) does this occur on?**
> 
> Android, iOS
> 
> **SDK Version (managed workflow only)**
> 
> 40
> 
> **Environment**
> 
> Expo CLI 4.1.6 environment info: System: OS: Windows 10 10.0.19041 Binaries: Node: 12.13.1 - C:\Program Files\nodejs\node.EXE npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD IDEs: Android Studio: Version 4.0.0.0 AI-193.6911.18.40.6626763 npmPackages: expo: ^40.0.0 => 40.0.0 react: 16.13.1 => 16.13.1 react-dom: 16.13.1 => 16.13.1 react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 react-native-web: ~0.13.12 => 0.13.18 react-navigation: ^3.12.0 => 3.13.0 Expo Workflow: managed
> 
> **Reproducible demo or steps to reproduce from a blank project**
> 
> https://snack.expo.io/@duggster/update-event-test

did you ever figure this out? i'm running into a similar issue, its always editing the first instance rather than the one you want
