### ISSUE TITLE
Facebook Login 'native' behaviour not working.

### ISSUE THREAD

**Issue by thibault12** [expo/expo#1199]
Hi,
I am currently experiencing some issues with the FB login of my app. Before the most recent update, the login was working fine but now the only behaviour that works is 'web' which is not ideal because people have to enter their full email address and password to log into the app. Is anyone else experiencing this? And does anyone know a fix or has more info about this or the new update? 
It was working fine before and I double check the steps again but can't find anything wrong with my implementation. 

Any help welcome thanks!!

**Comment by brentvatne** [comment]
hi, I believe I answered this on forums and/or in Slack. follow up with a forum link here with more info if you made one, if not, then make one please :)

**Comment by thibault12** [comment]
I was not able to find anything on forums as I believe this bug is due to the most recent Expo update.

**Comment by thibault12** [comment]
Here is our FB login code. When it is set to 'web' for behavior it works fine but when we switch it to 'native' nothing happens when the FB login button is pressed in our standalone app.

`login = async () => {
    const APP_ID = '<our_app_id'
    const options = {
    permissions: ['public_profile', 'email'],
    behavior: 'web'
    }
    const {type, token} = await Expo.Facebook.logInWithReadPermissionsAsync(APP_ID, options)
    if (type === 'success') {
      this.setState({showSpinner: true})
      const response = await fetch(`https://graph.facebook.com/me?access_token=${token}`)
      const userData = await response.json()
      const {uid} = await this.authenticate(token)
      this.registerForPushNotificationsAsync(uid)
      this.createUser(uid, userData)
    }
  }`

**Comment by thibault12** [comment]
@janicduplessis Would it be possible to have someone look at the issue please.

**Comment by aalices** [comment]
Investigating!
