### ISSUE TITLE
Definitive video/image picker/recorder solution

### ISSUE THREAD

**Issue by emilebosch** [expo/expo#120]
Hi, 
I was wondering if there is a possibility to bundle an record or select video. Or a take photo/pick foto solution in expo?

For now i can't seem to find any way of recording a video or taking a photo in expo. Is it available?

Thanks

**Comment by terribleben** [comment]
For taking a photo, you can use [launchCameraAsync](https://docs.expo.io/versions/v15.0.0/sdk/imagepicker.html#expoimagepickerlaunchcameraasyncoptions). I believe there is an undocumented way of making this component record video as well, but the reason we don't document it is because we're planning on making major improvements to this API in a near-term cycle.

**Comment by emilebosch** [comment]
Hi Ben, thanks for replying so quickly, is there maybe a roadmap available? This really helps us in planning whether to go for a custom build with extra native modules, or just sit and wait for a release. Is there some other way we can help maybe?

**Comment by emilebosch** [comment]
Also for the people wondering what the undocumented option is:

```
let result = await ImagePicker.launchCameraAsync({
      mediaType: 'video' 
    });
```

**Comment by terribleben** [comment]
I'm not sure I understand your question: I've noted that we _do_ support everything you asked for right now. Is there a specific feature you need that you have not mentioned?

As for the ImagePicker refactor, I believe @nikki93 is likely to work on this for SDK 17, but it's too early for me to make a strong guarantee right now.

**Comment by emilebosch** [comment]
Hi Ben, it was more of a general roadmap question in that sense. Ofcourse like to see things such as trimming, or setting the resolution, compressing. However i'm not sure, but it seems that the video captured is 360 × 480 and not the native 720 × 1280. I could be mistaken though but it seems that way if i do a quick upload test at transfer.sh.

**Comment by emilebosch** [comment]
Ok nevermind i can see that there are some settings aswell like this:

```
  self.picker.mediaTypes = @[(NSString *)kUTTypeMovie];

    if ([[self.options objectForKey:@"videoQuality"] isEqualToString:@"high"]) {
      self.picker.videoQuality = UIImagePickerControllerQualityTypeHigh;
    } else if ([[self.options objectForKey:@"videoQuality"] isEqualToString:@"low"]) {
      self.picker.videoQuality = UIImagePickerControllerQualityTypeLow;
    } else {
      self.picker.videoQuality = UIImagePickerControllerQualityTypeMedium;
    }

    id durationLimit = [self.options objectForKey:@"durationLimit"];
    if (durationLimit) {
      self.picker.videoMaximumDuration = [durationLimit doubleValue];
``` 

let me try them out first.

**Comment by emilebosch** [comment]
Closing this since i've worked it out using the undocumented features as said above.

**Comment by terribleben** [comment]
Just following up on this really old issue, I think we've since [added everything here](https://docs.expo.io/versions/latest/sdk/camera.html).
