### ISSUE TITLE
StyleSheet.create vs StyleSheet.compose

### ISSUE THREAD

**Issue by sanengineer** [expo/expo#12008]
**Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?**

Yes

**Comment by sanengineer** [comment]
stylesheet.create on react native is works fine but at expo I'm get errors :(

https://snack.expo.io/@sanengineer/stylesheet-create-vs-stylesheet-compose

<div data-snack-id="@sanengineer/stylesheet-create-vs-stylesheet-compose" data-snack-platform="web" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#F9F9F9;border:1px solid var(--color-border);border-radius:4px;height:505px;width:100%"></div><script async src="https://snack.expo.io/embed.js"></script>

**Comment by AdamJNavarro** [comment]
Hey @sanengineer, I'm not getting any errors when running your Snack. Is this still an issue you're encountering?

**Comment by sanengineer** [comment]
@AdamJNavarro , at my Snack, I create 2 difference from line 6 until 29 I use Stylsheet.Create and Line 33 until 55 I use StyleSheet.Compose.

If I Use StyleShee.Create On ReactNative Without Expo, Its going well without problem.. But If I Use Expo I must change .Create to .Compose...

Are it is normally? Or A Bug??

<img width="1435" alt="Screen Shot 2021-02-25 at 16 04 18" src="https://user-images.githubusercontent.com/48153104/109129344-216aca80-7783-11eb-89cc-eb258c9cbf59.png">
