### ISSUE TITLE
TypeError: shouldFallbackToLegacyNativeModule is not a function. after setting up redux-persist

### ISSUE THREAD

**Issue by AnasAlamin** [expo/expo#12006]
**Summary**

i'm getting  this error when i set up redux-persist.
TypeError: shouldFallbackToLegacyNativeModule is not a function. (In 'shouldFallbackToLegacyNativeModule()', 'shouldFallbackToLegacyNativeModule' is an instance of Object)

as far as i understood it has something to do with app registery, i tried to use both AppRegistery of react-native and expo's version registerRootComponent, but none of them worked.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\User\AppData\Roaming\npm\yarn.CMD
      npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ^0.15.0 => 0.15.0
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

unavailable

**Comment by keltran35** [comment]
Same issue

**Comment by jaydeep911** [comment]
Same Issue

**Comment by darbaidze2020** [comment]
same issue, after @react-native-async-storage/async-storage installation

**Comment by aliciant** [comment]
Same issue

**Comment by taher07** [comment]
same issue

**Comment by torqen** [comment]
same issue, only after adding @react-native-async-storage/async-storage

**Comment by hunter-and1** [comment]
Please use version `1.13.4` as I'll get this resolved

**Comment by brentvatne** [comment]
install @react-native-async-storage/async-storage@1.13.4

**Comment by Alejandrehl** [comment]
Same Issue. I Have installed @react-native-async-storage/async-storage@1.13.4 but problem persist.

**Comment by brentvatne** [comment]
@Alejandrehl - this means that you have not installed @react-native-async-storage/async-storage@1.13.4

**Comment by darbaidze2020** [comment]
> Same Issue. I Have installed @react-native-async-storage/async-storage@1.13.4 but problem persist.

@brentvatne is right. make sure, that u removed package via package manager, not manually.

**Comment by brentvatne** [comment]
i've updated the expo docs accordingly:

<img width="1193" alt="Screen Shot 2021-02-22 at 11 21 38 AM" src="https://user-images.githubusercontent.com/90494/108758585-223ffa00-7500-11eb-80ec-af6b3754f6f9.png">

the issue with 1.14.0 is *my fault* - sorry about that, we will have it resolved soon

**Comment by kebeney** [comment]
what a super helpful thread at the right time. I hit this issue an hour ago and now this has fixed it. yarn add @react-native-async-storage/async-storage@1.13.4

**Comment by AnasAlamin** [comment]
apparently the problem is with AsyncStorage, just downgrade the version to 1.13.4 until it gets resolved.
i'm closing this issue.

**Comment by brentvatne** [comment]
the problem is with my patch to async storage that was released in 1.14.0. the maintainers have since fixed that and re-released as 1.14.1
