### ISSUE TITLE
[docs] Clarify enableScreens documentation

### ISSUE THREAD

**Issue by kevgrig** [expo/expo#12002]
**Summary**

The [Expo Screens](https://docs.expo.io/versions/latest/sdk/screens/) documentation for using `enableScreens` from [react-native-screens](https://github.com/software-mansion/react-native-screens) doesn't highlight the downsides & risks; it only writes:

> react-native-screens provides native primitives to represent screens instead of plain <View> components in order to better take advantage of operating system behavior and optimizations around screens

However, there is a significant issue on Android that requires [disabling state serialization](https://github.com/software-mansion/react-native-screens/issues/17). This may cause [lost state](https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-763972444), for example. The consensus is that this is a [design limitation](https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-763996402) of `react-native-screens`.

I suggest that a doc update would be good to both: 1) add more detail to the current documentation of the value of using react-native-screens (because "in order to better take advantage of operating system behavior and optimizations around screens" is vague), and 2) add a warning about the above known risk and tradeoff on Android (and is this Android-only?).

**Link to the related docs page**

https://docs.expo.io/versions/latest/sdk/screens/

**Comment by Razorholt** [comment]
Not to mention that Expo only allows version up to 2.15.1 - The current one is 2.17.1. The other thing is that it's quite buggy, especially if you intend to use the Presentation modal on iOS. 

That being said, I'm confident that the team will get those bugs fixed anytime soon :) And I hope SDK 41 will allow the most recent version too.

**Comment by brentvatne** [comment]
@Razorholt - we update the version on each sdk release, once per quarter. you can eject if you need to update sooner.

@kevgrig - we don't try to extensively document libraries like react-native-screens that are included in the sdk. the developer should visit the official documentation for these libraries to become more informed. i think the best way to handle this would be to send a PR to react-native-screens to add a "limitations" section, and then we can link to that from the expo docs. cc @WoLewicki

also, as far as i know the limitation is inherited from react-native itself. the author of screens, former react-native android core maintainer at facebook, explains it here: https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-425027574.

**Comment by kevgrig** [comment]
@brentvatne Thanks, I can do that. I'm a bit confused: does this lack of view state reconstruction affect all RN projects or only those that use react-native-screens?

**Comment by brentvatne** [comment]
it impacts all react-native apps, unless you do some manual work to ensure that you're saving the react-native js state in a way that it can also be restored - and you're on your own with that because react-native does not provide any official suggestions for how to do it.

the comments in that thread go a bit more in depth on this if you're curious

**Comment by kevgrig** [comment]
That was the impression I was starting to get. So then might a better solution here be to modify `expo eject` to always generate the following code?

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);
}
```

**Comment by brentvatne** [comment]
that's a pretty reasonable suggestion

**Comment by kevgrig** [comment]
Ok, thanks, I'll take a look at creating a PR

**Comment by brentvatne** [comment]
thanks @kevgrig! we appreciate all of the useful issues that you have been involved in

**Comment by kevgrig** [comment]
Created PR https://github.com/expo/expo/pull/12043

By upstreaming to react-native core, do you mean changing https://github.com/facebook/react-native/blob/master/template/android/app/src/main/java/com/helloworld/MainActivity.java ?

**Comment by brentvatne** [comment]
yup

**Comment by kevgrig** [comment]
FYI, I found some time to do the FB PR and someone from the `react-native-screens` team has already done it: https://github.com/facebook/react-native/pull/31212
