### ISSUE TITLE
expo-device returns null on standalone app

### ISSUE THREAD

**Issue by osamaarefm** [expo/expo#12007]
**Summary**

I'm using sentry-expo and I want to log the device info (model, OS version, brand, etc) for the crashes. I noticed that Sentry dashboard logs everything correctly except for the device info (it says Unknown Device - Unknown OS) on standalone app, but on Expo Go it logs everything fine.
As an alternative i tried to use expo-device module, and use some data like Device.brand, Device.modelName, Device.osName, Device.osVersion. All of these work fine IF i'm using Expo Go. But when I build a standalone app, ALL of these return null.
So I'm wondering, why device info can be accessed if project is running on Expo Go, but nothing is accessed on standalone apps?

Thanks in advance.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

38

**Environment**

Expo CLI 3.26.2 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      expo: ^38.0.0 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.26.2

**Reproducible demo or steps to reproduce from a blank project**

import * as Device from 'expo-device';

alert(Device.brand + ' ' + Device.modelName + ' ' + Device.osName + ' ' + Device.osVersion);

**Comment by cruzach** [comment]
Hi @osamaarefm , thanks or the report. I'm not able to reproduce this on SDK 40, could you give that a try and lmk if it works for you?
