### ISSUE TITLE
ImagePicker opens under RNS screen modal

### ISSUE THREAD

**Issue by JB1905** [expo/expo#12009]
**Summary**

ImagePicker opens under RNS screen modal

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.0.8 environment info:
    System:
      OS: macOS 11.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.9 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.8
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

https://snack.expo.io/@jbiesiada/image-picker-rns

https://user-images.githubusercontent.com/28870390/108758201-1c233b00-754b-11eb-8b17-bc68a499faf8.MP4

https://user-images.githubusercontent.com/28870390/108758247-2b09ed80-754b-11eb-9147-d901528a2117.MP4

**Comment by AdamJNavarro** [comment]
Hey, @JB1905 I'm not able to reproduce this behavior. What iOS version are you on? 

https://user-images.githubusercontent.com/8992878/109029518-8ab9e300-7688-11eb-9bc5-a429683ae1f2.MP4

**Comment by JB1905** [comment]
Hi @AdamJNavarro, I use iOS 14.5 beta 2. I tested it on stable version and it works fine. Please be aware that the bug may remain after a stable release.

**Comment by JB1905** [comment]
Also visible on iOS 14.5 beta 3

**Comment by JB1905** [comment]
Also visible on iOS 14.5 beta 4

**Comment by JB1905** [comment]
Also visible on iOS 14.5 beta 5

**Comment by ayoubkalil** [comment]
Also visible on IOS 14.5 beta 7

**Comment by JB1905** [comment]
And on iOS 14.5 b8

**Comment by JB1905** [comment]
@AdamJNavarro issue is also visible on 14.5 RC and 14.6 beta 1

**Comment by Aryk** [comment]
For those that are having this issue (like I was)...if you are using react-native-screens *and* if you are using a full screen modal (coming in from the bottom)....you can use `stackPresentation: containedTransparentModal` like this

```js
<Stack.Screen
    name="CameraScreen"
    component={CameraScreen}
    options={{stackPresentation: "containedTransparentModal"}}
  />
```

for the modal...and then the ImagePicker will open *above* the modal. 

I was using a full screen modal before with Modal from react-native and Modal from react-native-modal and neither worked.

This did.

**Comment by Petercopter** [comment]
Still a thing in 14.5.1

**Comment by thebuddysystem** [comment]
@Aryk Thanks for posting your workaround, but what version of react-native-screens or react-navigation are you using?  I'm using Expo with the recommended React Navigation (5.x), which uses react-native-screens (~3.0.0), and that option is not available.  Referring to https://reactnavigation.org/docs/stack-navigator#options for the options.

And I'm not sure i understand the whole context of your workaround; is the workaround just to create another screen instead of using the modal, or are you using a modal in your `CameraScreen` screen component (with this additional option i can't find)?
Many thanks.

**Comment by Aryk** [comment]
@thebuddysystem  - To answer your questions

1. react-navigation - 5.14, react-native-screens 2.15. In 2.15 it's available. Read here: https://www.npmjs.com/package/react-native-screens. My guess is it should be in 3.0, just it's not documented.  If you go to main README, on github, I cannot find it there. 
2. It's the first one...I wanted to "Modal" to come up over the screen and it worked fine before...then on 14.5 broke like it did for everyone here. So I tried containedTransparentModal and frankly the behavior feels exactly the same. There is no "Modal" component inside my containedTransparentModal (I don't need it for anything). If you're trying to do a partial-screen modal though or you don't want it to slide in from the bottom, then my solution won't work. 
 
Hope that helps!
