### ISSUE TITLE
I cant post/get request to api from android but it works perfectly in ios.  Api working perfectly on android browser. Note: API'S Certificate provided by Let's Encrypt

### ISSUE THREAD

**Issue by aliburhankeskin** [expo/expo#12016]
**Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?**

Yes

**Comment by byCedric** [comment]
Hi @aliburhankeskin, thanks for writing in. Generally speaking, any valid SSL certificate should work just fine. That also includes all lets encrypt certificates, with the only requirement that it's a valid certificate. You can use tools [like SSL Labs](https://www.ssllabs.com/ssltest/) to test the validity of your SSL certificate.

But without a proper repro, we can't help you much further. If you think there is an issue with Expo, please open a new bug report with all the info we ask for. With that, we are able to investigate and help you further.

Hope this helps!

**Comment by aliburhankeskin** [comment]
Thank you for your help.

**Comment by tamzidkarim** [comment]
@aliburhankeskin how did you solve it in the end? Like you mine is also not working only on android devices.

**Comment by aliburhankeskin** [comment]
@tamzidkarim My problem was with the certificate, I suggest you check your SSL certificates.

**Comment by manjotsk** [comment]
![image](https://user-images.githubusercontent.com/26750100/143789175-901119e3-0407-400e-8066-da028f87d71f.png)
This is how my certificate looks like! 

Requests work fine on my iOS build! :')

**Comment by manjotsk** [comment]
In case wondering, i've just figured this out!

```
    Axios({
                                                                        // 'get'                                       :        "GET"
      method: Platform.OS=== 'ios' ? uriEndPoint.method.toLowerCase() : uriEndPoint.method,
      url: makeUrl({ ...uriEndPoint, pathParams, query }, hostUrl),
      headers: {
        ...hed,
        ...uriEndPoint.headerProps,
      },
      data: body || new FormData(),
    })
```

iOS prefers lowercase, android prefers uppercase!

**Comment by aliburhankeskin** [comment]
First time I've heard of this, thanks for letting me know. @manjotsk

**Comment by manjotsk** [comment]
@aliburhankeskin  Taking my works back, it seems android is very strict about the xhr parameters! I was sending body in a get request, which was the main reason for the Network Error!

**Comment by aliburhankeskin** [comment]
You cannot send body in GET request. If you want to send data(body) , you can try 'post' , 'patch',  'delete ', methods @manjotsk

**Comment by manjotsk** [comment]
Yeah I know that! I've migrated a lot of code from my web app, which doesn't throw any error on the bug which i had in my API processing function, even on multiple browsers! 

The same API engine that I used on my nextjs app had to be tweaked in order to remove the `null` body, which was being passed to the data param of the Axios, instead of `undefined`!
