### ISSUE TITLE
[expo-image-picker] ImagePicker.launchImageLibraryAsync fails for large images on new version

### ISSUE THREAD

**Issue by calebmadrigal** [expo/expo#12011]
**Summary**

ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.All,
        allowsEditing: true,
        quality: 1
    }) 

Fails to on large images, but only on the newer version. Specifically:
* large image selection fails with:"expo-image-picker": "~9.2.0"
* large image selection works great with "expo-image-picker": "~8.3.0"

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

Running on TestFlight

**Reproducible demo or steps to reproduce from a blank project**

ImagePicker.launchImageLibraryAsync() and select a large-resolution image.

**Comment by brentvatne** [comment]
please provide an example of an image that is failing for you

**Comment by calebmadrigal** [comment]
@brentvatne I just tried to get more details, but it doesn't happen when running on expo - only on TestFlight and in production. I'm not seeing any error, but the returned object seems to be null.

I don't have a good example of an image, but when I crop an image small enough it works, and if I select a smaller image, it works, but larger images return null.

**Comment by brentvatne** [comment]
can you send me one of those larger images?

**Comment by calebmadrigal** [comment]
@brentvatne Here are two that were consistently failing.

![IMG_6225](https://user-images.githubusercontent.com/1395167/108769875-99d54f80-7527-11eb-9938-608c956c4d73.jpeg)
![IMG_6229](https://user-images.githubusercontent.com/1395167/108769886-9d68d680-7527-11eb-9461-481ded8338a4.jpeg)

**Comment by brentvatne** [comment]
is there any difference in the device that you are using in Expo Go vs the standalone app?

in your original post you mention that "expo-image-picker": "~8.3.0" works for you, is this also in sdk 40?

**Comment by calebmadrigal** [comment]
@brentvatne Using sdk 40. And I'm using the same device (and iPhone X) for both Expo Go and TestFlight testing.

**Comment by brentvatne** [comment]
what permissions are you requesting?

**Comment by calebmadrigal** [comment]
@brentvatne `const status = await Permissions.askAsync(Permissions.CAMERA_ROLL);`

**Comment by brentvatne** [comment]
you should request the same permission as in this example: https://docs.expo.io/versions/latest/sdk/imagepicker/#usage

`onst { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();`

**Comment by brentvatne** [comment]
will reopen this if changing to the new permissions requesting method doesn't work for you

**Comment by calebmadrigal** [comment]
@brentvatne I'm doubtful it's a permission issue (since permissions work), but reverting to `8.3.0` fixed the problem.

**Comment by brentvatne** [comment]
that's odd, because the diff in the js code between 8.3.0 and 9.2.0 is only related to permissions
