### ISSUE TITLE
I have problem with expo eject ⚠️  Config synced with warnings that should be fixed: - splash: Unable to automatically configure splash screen. Please refer to the expo-splash-screen README for more information: https://github.com/expo/expo/tree/master/packages/expo-splash-screen

### ISSUE THREAD

**Issue by babay123** [expo/expo#12019]
**Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?**

Yes

**Comment by babay123** [comment]
⚠️  Config synced with warnings that should be fixed:
- splash: Unable to automatically configure splash screen. Please refer to the expo-splash-screen README for more information: https://github.com/expo/expo/tree/master/packages/expo-splash-screen

**Comment by byCedric** [comment]
Hi @babay123, thanks for writing in. But without the information from the bug template, there isn't a lot we can do. If you think this is an issue with Expo, please open a new bug report with the information we ask for. With that, we are able to investigate and help you further.

Hope this helps!
