### ISSUE TITLE
Generating .ipa file throws "You already have a current iOS Distribution certificate or a pending certificate request"

### ISSUE THREAD

**Issue by renancaldas** [expo/expo#1202]
Hey there,

I'm trying to run exp ios:build, having exp handle my cert for me, but it throws me this error: "You already have a current iOS Distribution certificate or a pending certificate request" (forcing me to remove the previous certificates):

![screen shot 2018-01-03 at 4 25 44 pm](https://user-images.githubusercontent.com/18703055/34533806-f138a2fc-f0a2-11e7-9945-bbe0c1a5ba44.png)

Is it posible to download the certficates from Apple Developer dashboard, generate a .p12 file and reuse the same certificate for the future builds?

Thanks!

**Comment by fxfactorial** [comment]
@renancaldas Hi, yes you can. When exp asks you whether it handles the process, you can say no and provide your own files instead.

**Comment by renancaldas** [comment]
@fxfactorial, thanks! In addition, do you know how can I generate a .p12 file from a certificate generated in this process? 

I tried to do this via Keychain Access (downloading the cert from Apple Developer) but since I don't have the private key, it doesn't allow this option:

![screen shot 2018-01-03 at 10 04 07 pm](https://user-images.githubusercontent.com/18703055/34545162-0ff9a392-f0d2-11e7-9fc8-d94e75b2247a.png)

**Comment by fxfactorial** [comment]
Ah, sorry. I wasn't entirely accurate, you can make your own p12 by going through the signing process yourself. That is, you make the CSR, have the private key, make the cert with apple, then change to p12 yourself. Its a bit of a CLI process (hence nicer when exp client handles this for you)
