### ISSUE TITLE
ERR_APP_AUTH: ID Token expired

### ISSUE THREAD

**Issue by RobertoSilvaZ** [expo/expo#12022]
**Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?**

Yes

**Comment by RobertoSilvaZ** [comment]
Hi, I've implemented a Login page using the **expo-google-app-auth** and I have a problem with some iPhone's devices, after the call the function **Google.logInAsync** I received the catch error **ERR_APP_AUTH: ID Token expired** , please if anyone has the same issue, please feel free to leave your comment or any idea, thank you!

**Comment by AdamJNavarro** [comment]
Hey @RobertoSilvaZ, as the issue template mentioned, we're going to close this issue. If you haven't already, please head to our [Forums](forums.expo.io) for this kind of matter.

Cheers,
Adam
