### ISSUE TITLE
Expo, "Simulator Not Installed!" Me, "Oh, but it is!"

### ISSUE THREAD

**Issue by geirman** [expo/expo#1203]
I was plugging away on my app, using the iOS simulator, when I got a random error. I don't even remember what it was, but red screen, wouldn't go away to spite knowing my app was in a known good state, etc. So did what any self respecting, technically savvy developer would...I quit the simulator and restarted expo. When I relaunched my project in expo and attempted to relaunch the simulator, I got this error. Hmmm, I thought to myself. Maybe I'll restart again. I did, but with the same result. I haven't yet rebooted my machine (my next step), but that shouldn't be necessary, right? Surely that will fix the problem, but can't be acceptable, right? After a quick search through the issues, it doesn't look as though this has been seen before, so I thought I'd fire off one. 

![2018-01-03_1147](https://user-images.githubusercontent.com/1640318/34537282-d3c3849c-f07c-11e7-8bce-ea5ef91efd56.png)

**Comment by brentvatne** [comment]
run the command that it suggests at the end of the error message and let me know if that fixes it!

**Comment by geirman** [comment]
Nope!

Here's a couple thoughts about that...

1. I didn't notice it until you pointed it out. My bad. I saw visit https//... and stopped reading. I knew I had it installed. 
2. I'm leery of running commands to "fix" something that worked seconds ago without the command. Especially sudo commands. Doubly especially sudo commands when I don't understand what they're doing or how to reverse it if it makes matters worse. 

Just to make sure I ran the command correctly, this is what I did in detail.

1. With expo still running, I executed the command in zsh iTerm
2. Switched back to expo, and chose "open in iOS simulator"
3. When that didn't work, I closed expo, reopened, and chose "open in iOS simulator" again
4. cried a little, but quickly got ahold of myself

sorry for any typos. It's tough to proofread through the tears 😜

**Comment by jesseruder** [comment]
If you don't want to run that command you can look here https://github.com/expo/xdl/blob/master/src/Simulator.js to see what commands we're running behind the scenes.

It runs:
`open -a Simulator`
`xcrun simctl install booted ~/.expo/ios-simulator-app-cache/Exponent-2.2.0.app`
`xcrun simctl openurl booted [YOUR URL HERE]`

One of those commands will probably error, and then you'll be able to debug it yourself.

**Comment by geirman** [comment]
Thanks @jesseruder! It's not that I didn't want to run the command. I was just providing feedback. I'm leery of running it because I wasn't sure what it did. It may have been more comforting had the instructions reassured me that "this is perfectly safe to run". Hope that makes sense.

When I run `open -a Simulator` it fails with "Unable to find application named 'Simulator'", so I guess that's my problem. I'll try restarting once another process finishes, and hopefully that will solve the problem (fingers crossed).

**Comment by jesseruder** [comment]
I think it's unlikely that restarting will work. You'll probably end up needing to run that sudo command. See: https://stackoverflow.com/a/41022224

**Comment by geirman** [comment]
Not sure why you thought it would be unlikely since it was working, then randomly stopped working. As it turned out, rebooting did resolve the issue in my case, but as always...I learned something. Thanks for the education on the scripts and for the quick responses. You guys rock!

**Comment by methodbox** [comment]
For anyone having this same issue w/the latest Xcode update, this fix works. And it does require a reboot to take effect.

**Comment by brentvatne** [comment]
@fson - I wonder if we can catch this somehow, seen a lot of this kind of thing recently with the latest xcode update

**Comment by jfedgar** [comment]
I am now getting this at least once a day.

**Comment by fson** [comment]
Could be related to changes in Xcode 10.2: https://github.com/react-native-community/react-native-cli/pull/138

**Comment by fson** [comment]
Let's track this in this expo-cli issue https://github.com/expo/expo-cli/issues/469 instead of reviving this age-old issue.

**Comment by SCasarotto** [comment]
Just wanted to point you toward the same conversation going on in the forums: https://forums.expo.io/t/unable-to-run-ios-simulator/20917/7 .

**Comment by sakhiyakauser** [comment]
type this command : sudo xcode-select -s /Applications/Xcode.app in your project directory it works for me...

**Comment by methodbox** [comment]
> type this command : sudo xcode-select -s /Applications/Xcode.app in your project directory it works for me...

It literally says that in the error...

**Comment by sakhiyakauser** [comment]
> > type this command : sudo xcode-select -s /Applications/Xcode.app in your project directory it works for me...
> 
> It literally says that in the error...
> 
> But it doesn't need to be in the project directory. You're running the command against the Xcode.app application.

ok

**Comment by ARMATAV** [comment]
This happens right after an Xcode update.
