### ISSUE TITLE
Linphone-sdk 4.2+ not starting up for ejected Expo 38.0.0

### ISSUE THREAD

**Issue by Sivasanjeevi18** [expo/expo#12035]
**Summary**

Hi I'm trying to integrate Linphone-SDK with ejected workflow of expo.
The SDK worked fine with EXPO SDK 36.0
But fails with ejected Expo 38.0
I'm unable to start the Linphone service on Expo 38.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.23.1 - ~/.nvm/versions/node/v10.23.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v10.23.1/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v10.23.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.11 
      react: ~16.11.0 => 16.9.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

1. Eject from blank Expo app
2. Integrate Linphone Native Module.
3. Start Linphone service on app launch

Expo SDK version: 38.0
The linphone service was not able to start from the app.
This is the build.gradle

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
ext {
buildToolsVersion = "28.0.3"
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 29

}
repositories {
    google()
    jcenter()
    mavenCentral()
    maven {
        url "https://plugins.gradle.org/m2/"
    }
}
dependencies {
    classpath 'com.android.tools.build:gradle:3.3.0'

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}
}

allprojects {
repositories {
mavenLocal()
maven {
// All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
url("$rootDir/../node_modules/react-native/android")
}
maven {
// Android JSC is installed from npm
url("$rootDir/../node_modules/jsc-android/dist")
}

    google()
    jcenter()
    maven { url 'https://www.jitpack.io' }
}
}
This is my app:build.gradle:apply plugin: "com.android.application"

import com.android.build.OutputFile

/**

The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
and bundleReleaseJsAndAssets).
These basically call react-native bundle with the correct arguments during the Android build
cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
bundle directly from the development server. Below you can see all the possible configurations
and their defaults. If you decide to add a configuration block, make sure to add it before the
apply from: "../../node_modules/react-native/react.gradle" line.
project.ext.react = [
// the name of the generated asset file containing your JS bundle
bundleAssetName: "index.android.bundle",
// the entry file for bundle generation. If none specified and
// "index.android.js" exists, it will be used. Otherwise "index.js" is
// default. Can be overridden with ENTRY_FILE environment variable.
entryFile: "index.android.js",
// https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
bundleCommand: "ram-bundle",
// whether to bundle JS and assets in debug mode
bundleInDebug: false,
// whether to bundle JS and assets in release mode
bundleInRelease: true,
// whether to bundle JS and assets in another build variant (if configured).
// See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
// The configuration property can be in the following formats
// 'bundleIn${productFlavor}${buildType}'
// 'bundleIn${buildType}'
// bundleInFreeDebug: true,
// bundleInPaidRelease: true,
// bundleInBeta: true,
// whether to disable dev mode in custom build variants (by default only disabled in release)
// for example: to disable dev mode in the staging build type (if configured)
devDisabledInStaging: true,
// The configuration property can be in the following formats
// 'devDisabledIn${productFlavor}${buildType}'
// 'devDisabledIn${buildType}'
// the root of your project, i.e. where "package.json" lives
root: "../../",
// where to put the JS bundle asset in debug mode
jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
// where to put the JS bundle asset in release mode
jsBundleDirRelease: "$buildDir/intermediates/assets/release",
// where to put drawable resources / React Native assets, e.g. the ones you use via
// require('./image.png')), in debug mode
resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
// where to put drawable resources / React Native assets, e.g. the ones you use via
// require('./image.png')), in release mode
resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
// by default the gradle tasks are skipped if none of the JS files or assets change; this means
// that we don't look at files in android/ or ios/ to determine whether the tasks are up to
// date; if you have any other folders that you want to ignore for performance reasons (gradle
// indexes the entire tree), add them here. Alternatively, if you have JS files in android/
// for example, you might want to remove it from here.
inputExcludes: ["android/", "ios/"],
// override which node gets called and with what additional arguments
nodeExecutableAndArgs: ["node"],
// supply additional arguments to the packager
extraPackagerArgs: []
]
*/
project.ext.react = [
enableHermes: false
]

apply from: '../../node_modules/react-native-unimodules/gradle.groovy'
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/expo-updates/scripts/create-manifest-android.gradle"

/**

Set this to true to create two separate APKs instead of one:
An APK that only works on ARM devices
An APK that only works on x86 devices
The advantage is the size of the APK is reduced by about 4MB.
Upload all the APKs to the Play Store and people will download
the correct one based on the CPU architecture of their device.
*/
def enableSeparateBuildPerCPUArchitecture = false
/**

Run Proguard to shrink the Java bytecode in release builds.
*/
def enableProguardInReleaseBuilds = false
/**

The preferred build flavor of JavaScriptCore.
For example, to use the international variant, you can use:
def jscFlavor = 'org.webkit:android-jsc-intl:+'
The international variant includes ICU i18n library and necessary data
allowing to use e.g. Date.toLocaleString and String.localeCompare that
give correct results when using with locales other than en-US. Note that
this variant is about 6MiB larger per architecture than default.
*/
def jscFlavor = 'org.webkit:android-jsc:+'
/**

Whether to enable the Hermes VM.
This should be set on project.ext.react and mirrored here. If it is not set
on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
and the benefits of using Hermes will therefore be sharply reduced.
*/
def enableHermes = project.ext.react.get("enableHermes", false);
android {
compileSdkVersion rootProject.ext.compileSdkVersion

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

defaultConfig {
    applicationId 'com.version38'
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
    versionCode 1
    versionName "1.0.0"
}
splits {
    abi {
        reset()
        enable enableSeparateBuildPerCPUArchitecture
        universalApk false  // If true, also generate a universal APK
        include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
    }
}
signingConfigs {
    debug {
        storeFile file('debug.keystore')
        storePassword 'android'
        keyAlias 'androiddebugkey'
        keyPassword 'android'
    }
}
buildTypes {
    debug {
        signingConfig signingConfigs.debug
    }
    release {
        // Caution! In production, you need to generate your own keystore file.
        // see https://facebook.github.io/react-native/docs/signed-apk-android.
        signingConfig signingConfigs.debug
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
    }
}

packagingOptions {
    pickFirst '**/armeabi-v7a/libc++_shared.so'
    pickFirst '**/x86/libc++_shared.so'
    pickFirst '**/arm64-v8a/libc++_shared.so'
    pickFirst '**/x86_64/libc++_shared.so'
    pickFirst '**/armeabi-v7a/libjsc.so'
    pickFirst '**/x86/libc++_shared.so'

    pickFirst '**/x86_64/libjsc.so'

    pickFirst '**/arm64-v8a/libc++_shared.so'
    pickFirst '**/x86_64/libc++_shared.so'
    pickFirst '**/armeabi-v7a/libc++_shared.so'
    pickFirst '**/armeabi-v7a/libjsc.so'
    pickFirst '**/arm64-v8a/libjsc.so'
    pickFirst '**/x86/libjsc.so'
    pickFirst '**/x86_64/libjsc.so'

    pickFirst '**/arm64-v8a/libjscexecutor.so'
    pickFirst '**/x86_64/libjscexecutor.so'
    pickFirst '**/armeabi-v7a/libjscexecutor.so'
    pickFirst '**/x86/libjscexecutor.so'

    pickFirst '**/armeabi-v7a/libffmpeg-linphone.so'
    pickFirst '**/arm64-v8a/libffmpeg-linphone.so'
    pickFirst '**/x86/libffmpeg-linphone.so'
    pickFirst '**/x86_64/libffmpeg-linphone.so'
}

// applicationVariants are e.g. debug, release
applicationVariants.all { variant ->
    variant.outputs.each { output ->
        // For each separate APK per architecture, set a unique version code as described here:
        // https://developer.android.com/studio/build/configure-apk-splits.html
        def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
        def abi = output.getFilter(OutputFile.ABI)
        if (abi != null) {  // null for the universal-debug, universal-release variants
            output.versionCodeOverride =
                    versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
        }

    }
}
}

repositories {
maven {
url "https://linphone.org/maven_repository/"
}
}

dependencies {
implementation fileTree(dir: "libs", include: ["*.jar"])
//noinspection GradleDynamicVersion
implementation "org.linphone:linphone-sdk-android:4.2+"
implementation "com.facebook.react:react-native:+" // From node_modules
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

addUnimodulesDependencies()

if (enableHermes) {
    def hermesPath = "../../node_modules/hermes-engine/android/";
    debugImplementation files(hermesPath + "hermes-debug.aar")
    releaseImplementation files(hermesPath + "hermes-release.aar")
} else {
    implementation jscFlavor
}
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
from configurations.compile
into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
`

This is the crash log obtained from my phone
[Logs.txt.txt](https://github.com/expo/expo/files/6042824/Logs.txt.txt)

**Comment by AdamJNavarro** [comment]
Hey @Sivasanjeevi18, could you please try implementing the linphone sdk in a vanilla react-native project running the corresponding rn version (0.62 in this case). It'll be helpful to know if this is an issue specific to Expo or rather one to do with react native.

Cheers,
Adam

**Comment by Sivasanjeevi18** [comment]
Hi @AdamJNavarro I tried with vanilla react-native I had no issues there. Also I was able to eject the Expo SDK 36.0 and integrate Linphone with it. Here ReactNative's version is alright.
This problem persists from expo SDK version 37 and above.
