### ISSUE TITLE
Expo.Audio not working with mp3 stream on Android

### ISSUE THREAD

**Issue by grav** [expo/expo#1204]
I've created an app that plays back radio streams. It works on both Android and iPhone with Expo 21, but updating to Expo 24, the streams start behaving weirdly on Android.

The following (ClojureScript) will reproduce the problem:
```
(-> (Expo.Audio.Sound.create #js{:uri "http://onair.100fmlive.dk/100fm_live.mp3?ua=WEB"}
                               #js {:shouldPlay         true
                                    :rate               1.0,
                                    :shouldCorrectPitch false
                                    :volume             0.5
                                    :isMuted            false
                                    :isLooping          false}
                               prn true)
      (.then prn)
      (.catch prn))
```

What will mostly happen is that the status update function (third argument to `Expo.Audio.Sound.create`) is never called, even though the stream does start playing, meaning that it is not possible to get hold of the sound object.

Creating an instance of Expo.Audio.Sound does return a sound object, but calling eg. `.stopAsync` on it results in an error about the stream not playing, even though it is.

Other streams such as https://s3.amazonaws.com/exp-us-standard/audio/playlist-example/Comfort_Fit_-_03_-_Sorry.mp3 work fine - maybe because it's a finite audio file and not an infinite stream?

**Comment by arrygoo** [comment]
I have similar issues only on Android since upgrading but I'm using acc rather than mp3.

**Comment by brentvatne** [comment]
@sjchmiela - halp! ;)

**Comment by sjchmiela** [comment]
Hi, all!

Pre-SDK24 a sound was being considered loaded before it really loaded. This bug has been improperly fixed in https://github.com/expo/expo/commit/a957b74ab7829cf18e425de555f6f17ef1e135a7.

A proper fix is awaiting and should be reviewed soon. :) https://github.com/expo/universe/pull/1686
