### ISSUE TITLE
[FileSystem] Prebuilt modules cause build to fail for Mac Catalyst

### ISSUE THREAD

**Issue by robertying** [expo/expo#12040]
**Summary**

When building expo-file-system v10.0.0 for Mac Catalyst, there is an error like `Cannot find framework ExpoFileSystem`.

Xcode shows a warning that `unable to find matching .xcframework slice in ...(path of expo-file-system)`.

I couldn't figure that out until I saw the latest changelog from unimodules about [using prebuilt modules](https://github.com/expo/expo/commit/2c6fe5267d00ead4db8851edcd6195a144b445ec#diff-e7f5cb40c3e580a445b65533e482658de89ffd5153e8e5f34548e900fced7433).

Following https://github.com/expo/fyi/blob/master/prebuilt-modules.md, using `EXPO_USE_SOURCE=1 pod install` to disable use of prebuilt binary fixes the problem.

I think this is because expo-file-system hasn't shipped proper binary for x86-64 (mac catalyst).

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
        Android NDK: 22.0.7026061
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.0-rc.3 => 0.64.0-rc.3 
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

1. Init with bare workflow
2. Add `expo-file-system`
3. cd ios && pod install && cd ..
4. Build for Catalyst

**Comment by cruzach** [comment]
We don't explicitly support building for Mac catalyst (it's not something we test against, so we can't gaurantee it will always work). That being said, we're happy to review any PRs that address issues like this. Here's an example issue of something similar - https://github.com/expo/expo/issues/7166
