### ISSUE TITLE
Numbers with underscore separators cause error on Android

### ISSUE THREAD

**Issue by xavierstampslafont** [expo/expo#12042]
**Summary**

If a number has underscore separators in it, e.g. `1_000`, it will cause this error on Android (both on emulator and on device): `No identifiers allowed directly after numeric literal`

It works fine on iOS. Ideally it should work for Android too!

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.3
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

https://snack.expo.io/ns4xL2JLk

**Comment by AdamJNavarro** [comment]
Hey @xavierstampslafont, this falls out of the scope of Expo but rather deals with JavaScript's implementation itself.

**Comment by xavierstampslafont** [comment]
Is it because of different JS engines being used for Android vs iOS? 

If you're aware of where else I can raise this issue, I'd appreciate any help!
