### ISSUE TITLE
Audio.Sound.loadAsync never resolves or rejects if non-encoded space character in source URI

### ISSUE THREAD

**Issue by jonmumm** [expo/expo#12048]
**Summary**

If there is a non-encoded space character in the source URI passed in to `Audio.Sound.loadAsync`, the call never resolves or rejects. Even if this is an error (I expected the source URI to properly encode the URI for me if it wasn't already), I would expect that loadAsync should still reject and not hang.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

 Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.53 => 0.12.53 
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

```ts
    const sound = new Audio.Sound();
    try {
      await sound.loadAsync({ uri: "https://www.example.com/my URL with a space in it" })
      console.log("This never happens");
    } catch (ex) {
      console.error("This also never happens, loadAsync is never resolving or rejecting if there is a non-encoded space in the source uri");
    }
```

**Comment by AdamJNavarro** [comment]
Hey @jonmumm, thanks for bringing this to our attention. Adding that this also occurs on Android and here's a [Snack](https://snack.expo.io/@adamjnav/b9e3e7) for further testing/investigation.

**Comment by reinhardholl** [comment]
We are seeing similar failures on videos. We don't have spaced in the URL's though. The failures are also erratic. Sometimes they reject properly but sometimes they just hang.
