### ISSUE TITLE
App rejected, reason: 'We have determined your app contains code to facilitate Ad Fraud.'

### ISSUE THREAD

**Issue by pierrefrota** [expo/expo#12053]
**Summary**

Application rejected in the PlayStore. I already have a production version, I'm trying to launch a new update but it is being rejected

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

39.0.0

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.20.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.10 - /usr/bin/npm
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

expo build:android

I already have a production version, I'm trying to launch a new update but it is being rejected.

`
**Issue with your app**
--
We have determined your app contains code to facilitate Ad Fraud.
Affected Versions: App Bundle:3.

**App status: Rejected**
--
Your app has been rejected and wasn't published due to this policy issue. If you submitted an update, the previous version of your app is still available on Google Play.
`

**Comment by AdamJNavarro** [comment]
Hey @pierrefrota, did Google share more about the specific policy issue you are referring to? As well, did they identify any culprit code or module specifically?

**Comment by pierrefrota** [comment]
Hello, @AdamJNavarro. 

They have not specified which code is causing this.
What is strange is that I only updated the Styles of the App. All the logic, all screens and functions are the same.

The Admob IDs are the same as in the previous version as well. In the previous version I was using Expo Version 36.0.0. Now with the version of Expo 39.0.2

**Comment by AdamJNavarro** [comment]
Thanks for the info, @pierrefrota. We didn't change Admob versions between SDK36 and 39 so it's unlikely this is something to do with that. I would seek further clarification from Google to try and get to the bottom of this. We haven't seen others report getting this rejection either. It may simply be a mistake on their end. Some good news, we will be updating Admob versions in SDK41!

**Comment by pierrefrota** [comment]
I solved it by adding `setTimeout()`. Adding a 3 second interval to display the banner
