### ISSUE TITLE
expo-checkbox doesn't seem to be working on Expo Snack

### ISSUE THREAD

**Issue by howardwu1** [expo/expo#12054]
**Summary**

Expo-checkbox gives an error "The method or property expo-checkbox.Checkbox is not available on android, are you sure you've linked all the native dependencies properly?" for android but works on web. 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

expo v40.0 on snack

**Reproducible demo or steps to reproduce from a blank project**

https://docs.expo.io/versions/latest/sdk/checkbox/#usage -- click on try on snack

**Comment by waymond91** [comment]
## Bare workflow
After `expo install expo-checkbox` I'm having a similar issue on iOS:
![image](https://user-images.githubusercontent.com/3513523/139847850-839181aa-6a66-4ce3-9610-68575dfae4f3.png)
