### ISSUE TITLE
Expo Location (Android Platform) -  Cannot read property 'coords' of null

### ISSUE THREAD

**Issue by HVHMobileDeveloper** [expo/expo#12056]
**Summary**

Cannot read property 'coords' of null': getLastKnownPositionAsync()

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

expo

**Reproducible demo or steps to reproduce from a blank project**

I'm getting the error when calling the method:  
- const {coords} = await Location.getLastKnownPositionAsync({});
=> with the exception: 'Cannot read property 'coords' of null'

**Comment by HVHMobileDeveloper** [comment]
the full of code: 
async function handleGetLocation() {
       const {status} = await Location.requestPermissionsAsync();
            if (status !== 'granted') {
            }
            try {
                const {coords} = await Location.getLastKnownPositionAsync({});
                dispatch(setUserRegion(coords.latitude, coords.longitude));
            } catch (e) {
                console.log(e);
            }
    }

**Comment by byCedric** [comment]
Hi @HVHMobileDeveloper, thanks for writing in. But `null` is a valid output of this method. The way it works is that it's temporary saving the last fetched position, if that wasn't fetched before it doesn't know the last position. Form [the docs](https://docs.expo.io/versions/latest/sdk/location/#returns-3):
> Returns a promise resolving to an object of type `LocationObject` or `null` if it's not available or doesn't match given requirements such as maximum age or required accuracy.

Hope this helps!
