### ISSUE TITLE
[ios][notifications] use 0-11 based months everywhere, translating to/from 1-12 in iOS native code

### ISSUE THREAD

**Issue by raulmt** [expo/expo#12061]
**Summary**

There should be a standard way to refer to months, ideally 0-11 based months which is the way JS uses.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

Not needed

**Reproducible demo or steps to reproduce from a blank project**

Not needed

From discussion on #11898, months in JS are 0-11 based, but iOS uses 1-12 based months. This implies that in iOS, when a calendar trigger notification is created (directly or indirectly through yearly trigger, for example), the created notification will end up with 1-12 months (even though was created with 0-11 months from yearly trigger). The ideal solution is to translate to 0-11 months from native iOS code, so then everything from JS (both, write and read) looks like 0-11 based months. Android already uses 0-11 months, so nothing is needed for Android.

Note this would be a breaking change in two ways:
- when creating a calendar trigger, currently it implicitly asks for 1-12 months (since it passes the data directly to iOS native code), and we would change that to accept 0-11 months and translate it to 1-12 months in native code only
- when receiving a created calendar trigger notification (both directly or through yearly trigger, for example), it will contain months in 0-11 instead of the current 1-12 months used

**Comment by raulmt** [comment]
@cruzach here is the issue discussed in #11898 . I cannot assign it to you, so letting you know with this comment :)

**Comment by cruzach** [comment]
perfect, thanks!
