### ISSUE TITLE
Linear Gradient flickers on mount

### ISSUE THREAD

**Issue by nandorojo** [expo/expo#12066]
### Summary

Expo's LinearGradient component flickers initially on web. It's often hard to tell, but it is noticeable, namely if a screen triggers a re-render for some reason. The reason appears to be that the gradient sets its colors in `useEffect`. This might be one of the rare use-cases for [`useLayoutEffect`](https://github.com/expo/expo/blob/45dd06df4c3d844e8adf774207d64015e76ec902/packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx#L19).

I also noticed that the gradient colors are set by triggering a re-render in an effect. It might make more sense for this to be a memoized variable, but maybe this [re-render](https://github.com/expo/expo/blob/45dd06df4c3d844e8adf774207d64015e76ec902/packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx#L49) is on purpose.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40

### Environment

 Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@nandorojo/linear-gradient

This is ironically hard to reproduce, because in an app that only renders one view, it's basically invisible to the naked eye. But when there's more JS involved, it is indeed noticeable.

Here's a rough example of a mock-page: https://www.loom.com/share/7d6b33b7582540fcbc3192fcb91f1d09

Notice the yellow flicker. This happens before the gradient's first paint, since the background is yellow behind it.

This may also happen on other platforms, but I've only debugged web so far.

**Comment by EvanBacon** [comment]
`useEffect` does not appear to be in use anymore.
