### ISSUE TITLE
Build error - Cannot find module '/scripts/getAppConfig.js'

### ISSUE THREAD

**Issue by ewilliam** [expo/expo#12069]
### Summary

Attempting to build an app bundle for Android ends in error, even in fresh bare projects.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 3.1.2 - /usr/local/bin/fish
    Binaries:
      Node: 15.8.0 - ~/.asdf/installs/nodejs/15.8.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.1 - ~/.asdf/installs/nodejs/15.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/ewilliam/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-29 | Intel x86 Atom_64
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

expo init --template bare-minimum
cd android
./gradlew bundleRelease

### The Error

> Task :app:bundleReleaseExpoConfig FAILED
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module '/scripts/getAppConfig.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseExpoConfig'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 13s
443 actionable tasks: 443 executed

**Comment by brentvatne** [comment]
it looks like something is missing in your node_modules directory. run `ls node_modules/expo-constants/scripts` from the root of your project directory and let me know what you find.

is there any chance you're trying to use this in a yarnworkspace? if so you need to symlink expo-updates to your project directory

**Comment by ewilliam** [comment]
@brentvatne no workspaces and node_modules directory contains 3 files as expected:

get-app-config-android.gradle  
get-app-config-ios.sh*         
getAppConfig.js

**Comment by brentvatne** [comment]
hm not sure what is different about your machine that is making this particular script fail.

here is how we determine the expo-constants directory: https://github.com/expo/expo/blob/7e8c833aaae7b304434f52a0ce4f5f581e8dad6e/packages/expo-constants/scripts/get-app-config-android.gradle#L13

we then run the script like this: https://github.com/expo/expo/blob/7e8c833aaae7b304434f52a0ce4f5f581e8dad6e/packages/expo-constants/scripts/get-app-config-android.gradle#L48

what does `node -e "console.log(require('path').dirname(require.resolve('expo-constants/package.json')));"` run inside of your `android` directory return?

**Comment by ewilliam** [comment]
returns pathtouser/Projects/sandbox/expo-bare-test/node_modules/expo-constants

**Comment by brentvatne** [comment]
that seems correct. now try this from the root of your project: 

```
mkdir tmp
node <insert-that-path-here>/scripts/getAppConfig.js . tmp
```

i expect that should work. if that's the case, then we can see that somehow in `get-app-config-android.gradle` we are unable to resolve `expo-constants/package.json`, which makes me suspicious of the node installation.

**Comment by ewilliam** [comment]
that worked as you said it would, new app.config file in tmp dir. what about the node installation?

**Comment by ewilliam** [comment]
try homebrew node?

**Comment by brentvatne** [comment]
also you can try adding these lines to `get-app-config-android.gradle` in your node_modules, right under the `expoConstantsDir` def

```
def nodeVersion = ["node", "-v"].execute([], projectDir).text.trim()

project.logger.lifecycle("projectDir: ${projectDir}")
project.logger.lifecycle("expoConstantsDir: ${expoConstantsDir}")
project.logger.lifecycle("nodeVersion: ${nodeVersion}")
```

next time you run the build you should see some logs with this information, eg:

```
projectDir: /Users/brentvatne/code/myapp/android/app
expoConstantsDir: /Users/brentvatne/code/myapp/node_modules/expo-constants
nodeVersion: v14.15.2
```

**Comment by ewilliam** [comment]
ah switching to homebrew node fixed it. thanks a lot!

that's a good tip, will keep in mind when i give the old setup another try

**Comment by brentvatne** [comment]
thanks for talking through it! i'm glad we were able to find the source of the problem

**Comment by YoranBrondsema** [comment]
Just an FYI that I was facing the same error as described in this thread with node from `asdf`. Switching to node from Homebrew's fixed the issue.

**Comment by jarnove** [comment]
We're also using `asdf` and have the same issue, why would it be an issue with asdf node and not with homebrew? Just to know :)
We didn't have that issue with RN version 0.63.4, we're updating to 0.64 and now we have the issue as well. But I guess 0.64 isn't supported by expo for the moment?

**Comment by sospedra** [comment]
Same problem with `asdf`. Switching to brew node does **not** fix the issue
