### ISSUE TITLE
expo-splash-screen command creates incorrect configuration for older apps

### ISSUE THREAD

**Issue by lindboe** [expo/expo#12068]
### Summary

The issue appears to be that the tool adds the import `import expo.modules.splashscreen.singletons.SplashScreen;`, but that doesn't exist in this older version of expo-splash-screen. Instead it needs to be `import expo.modules.splashscreen.SplashScreen;`, as noted in https://github.com/expo/expo/blob/sdk-38/packages/expo-splash-screen/README.md#-configure-android (this file does not exist for sdk 37, but sdk 38 seems to match).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/lib/ruby/gems/2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 25, 27, 28, 29
        Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.11.25 => 0.11.25
      expo: 37.0.12 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- Create a bare workflow app with expo version 37.x (possibly also 38.x)
- Add expo-splash-screen with `expo install expo-splash-screen` (I got version expo-splash-screen@0.2.3)
- Run `yarn run expo-splash-screen` with arbitrary options
- Android app fails to compile with error `package expo.modules.splashscreen.singletons does not exist`

**Comment by AdamJNavarro** [comment]
Hey @lindboe, could you please create a public github repo running SDK 37 that we can simply clone and test on our end?

**Comment by brentvatne** [comment]
hi there! it's possible that there was some dependency bump that results in an incompatible version of configure-splash-screen being used. this was one of the first sdks where expo-splash-screen existed and we were still working through it, it's in a much better spot on the latest releases. i recommend upgrading to the latest version of expo-splash-screen and react-native-unimodules. in the bare workflow you aren't tied to packages from a specific sdk version

**Comment by lindboe** [comment]
We were on expokit before, and the eject to bare process is already fairly big for us -- we're trying to minimize upgrades to keep scope and risk smaller.

The import statement change manually is sufficient for us, I just wanted to file an issue in case anyone else runs across this problem.

I can try setting up a repro case later on in my own time if that's helpful.

**Comment by brentvatne** [comment]
thanks for the follow up @lindboe!
