### ISSUE TITLE
For everyone ease of use, would need your help to get gps info(Latitude, longitude, Heading, altitude, Speed) into Expo Camera, takepictureasync 

### ISSUE THREAD

**Issue by ashishGo360** [expo/expo#12077]
### Summary

For everyone ease of use, would need your help to get gps info(Latitude, longitude, Heading, altitude, Speed) into Expo Camera, takepictureasync . I tried on Redmi and oppo android phones. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.0

### Environment

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

take picture with Expo camera takepictureasync function with exif true option
after taking picture use an online exif viewer to see if gps info is saved or not in the exif data. 
if you don't see these tags in Latitude, longitude, Heading, altitude, Speed then gps info is not saved

On the other hand expo-image-picker, did capture some GPS info in exif automatically. However image picker doesnt let images to be taken continuously and automatically.

**Comment by ashishGo360** [comment]
@brentvatne thank you so much for helping me with the info on the other issue. I have raised an issue here. 
meanwhile i couldnt figure how to use the code that you sent me. 


 public static Bundle getExifData(ExifInterface exifInterface) { 
   Bundle exifMap = new Bundle(); 
   for (String[] tagInfo : CameraViewHelper.exifTags) { 
     String name = tagInfo[1]; 
     if (exifInterface.getAttribute(name) != null) { 
       String type = tagInfo[0]; 
       switch (type) { 
         case "string": 
           exifMap.putString(name, exifInterface.getAttribute(name)); 
           break; 
         case "int": 
           exifMap.putInt(name, exifInterface.getAttributeInt(name, 0)); 
           break; 
         case "double": 
           exifMap.putDouble(name, exifInterface.getAttributeDouble(name, 0)); 
           break; 
       } 
     } 
   } 
  
   double[] latLong = exifInterface.getLatLong(); 
   if (latLong != null) { 
     exifMap.putDouble(ExifInterface.TAG_GPS_LATITUDE, latLong[0]); 
     exifMap.putDouble(ExifInterface.TAG_GPS_LONGITUDE, latLong[1]); 
     exifMap.putDouble(ExifInterface.TAG_GPS_ALTITUDE, exifInterface.getAltitude(0)); 
   } 
  
   return exifMap; 
 }

**Comment by ptpmashish** [comment]
@brentvatne any updates, this is a common feature in RN camera and a basic one for images .

**Comment by brentvatne** [comment]
we don't have an update but if you'd like to send a pull request to add the info that you'd like, you're welcome to. i'm closing this issue because issues are intended for bugs and this is a feature request :)
