### ISSUE TITLE
expo-av plays sound twice

### ISSUE THREAD

**Issue by OoDeLally** [expo/expo#12085]
### Summary

I'm using expo-av to play a mp3 sound.
The first time the sound is played, it is played twice at a few milliseconds interval.
Next times it work fine.

We wait for a few seconds and try again, it will play twice again.
It also plays twice everytime we quit and reload the app.

The problem arises in both managed and bare.
It does not occur on web.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: Linux 5.4 Linux Mint 20 (Ulyana)
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
      npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Repo: https://github.com/OoDeLally/expo-multiple-sound-bug
Snack: https://snack.expo.io/@oodelally/github.com-oodelally-expo-multiple-sound-bug

**Comment by byCedric** [comment]
Hi @OoDeLally, thanks for writing in! Unfortunately, I can't seem to reproduce this issue on my OnePlus 6. Does this happen on multiple devices, or just a specific one? If so, what device is that (e.g. Android version, manufacturer etc)

**Comment by OoDeLally** [comment]
I'm using a OnePlus 8 with OxygenOS 11. This is my only device unfortunately so I cannot test on others.
I've made a recording of the bug. You can see the sound plays twice at the first play, then plays normally the subsequent times. Then after having waited for a few seconds, it plays twice again.

https://user-images.githubusercontent.com/1717629/110333340-c7d78b00-8021-11eb-998f-ff540268b634.mp4

**Comment by OoDeLally** [comment]
The bug is still there, even with the latest version of expo / RN / android.
