### ISSUE TITLE
When testing Expo Audio (expo-av) in our app, it appears to be using streaming, but this is not the documented behaviour

### ISSUE THREAD

**Issue by williamdespard** [expo/expo#12081]
### Summary

In the Expo Audio docs (https://docs.expo.io/versions/latest/sdk/audio/) there is no mention that there is any streaming functionality. So, one would assume that the user's device must download the entire audio file from S3 (well, in our case, Cloudfront) before being able to play it to the user. However, in our app, if we start playing an audio file (using expo-av), and then immediately disconnect the device (iPhone) from the internet/wifi, the track continues for a period but stops before it is fully finished playing. This implies that there is still a portion of the audio file left to download from S3, which in turn implies, that Expo Audio is utilizing streaming.

Is streaming a feature that comes out of the box with Expo Audio? And if so, is there a way we can turn the streaming functionality off? Or indeed, turn it on, if it is a functionality that is provided, but not out of the box.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40.0.1

### Environment

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.8.0 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 7.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.2, 30.0.3
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Simple Expo audio implementation, taking audio urls from Cloudfront.

**Comment by artsnr1** [comment]
But why doesn't the audio resumes playing when we turn on the internet? It keeps buffering and when I try to pause it, it throws erro 'e_audio_noplayer '
