### ISSUE TITLE
How to add password for a db in expo-sqlite? Is that possible?

### ISSUE THREAD

**Issue by hchen98** [expo/expo#12083]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by brentvatne** [comment]
https://forums.expo.io/ is a good place to ask this

sqlite does not ship with a mechanism to password protect databases. if you need to securely store some data, consider [expo-secure-store](https://docs.expo.io/versions/latest/sdk/securestore/)
