### ISSUE TITLE
Expo [Andriod] - (0,s.default) is not a function. Error after production

### ISSUE THREAD

**Issue by Jidnyesh** [expo/expo#12099]
### Summary

Expo app giving unwanted errors in production which didn't exist in the development. Also the error does not describe itself well enough and do not relate to any variable or function I am using.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

Only CLI

### Environment

Expo CLI 4.2.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. Built a normal expo app using expo init
2. Added aws-amplify JS library
3. Imported Auth into my project and ran Auth.signIN
4. Everything works really well in development mode but the app throws an error only in production.
Error : (0,s.default) is not a function , '(0,s.default)(t.typeLength)' is not a function

If it works in normal development mode, it shouldn't give an error in the production. I think the expo build has some bug while exporting the app.

I am adding an AWS Cognito Auth function in my Expo React-native app. Everything works absolutely fine in development mode. No errors nothing at all unless I export my Expo app. After exporting my Expo app, I get an error stating `(0,s.default) is not a function, '(0,s.default)(t.typeLength)' is not a function`. I assume that it is related to my `AWS-amplify` or `amazon-Cognito-identity-js` library because it pops as soon as I click the Login button which runs `Auth.signin` function. Also I tried printing the full error and it states `line:1034,column:9307,sourceUrl:/data/user/0/com.MyProject.main/files/.expo-internal/buldle-99A..randomNumber..`
I have gone through similar questions but none stated the error I am getting i.e. `(0,s.default) is not a function`. I cannot go through all the libraries in the node modules cause then it would take a decade. Also for trial and error, I am having to export my app 100s of times which isn't feasible. Can anyone let me know how can I find out what's wrong or any help? I have already tried modular exports and totally changed all the import lines.

```
import React, { useEffect,useMemo, useState,useContext } from 'react'
import {
  Text
} from 'react-native'
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

import {AuthContext} from './component/context'

import {Amplify,Auth} from 'aws-amplify';

import {getItemAsync,setItemAsync,deleteItemAsync} from 'expo-secure-store';
import { LinearGradient } from 'expo-linear-gradient';
```

I have already gone through all the other issues on GitHub as well as StackOverflow but I am finding no help. If one of you could help, it would be life-saving.

**Comment by brentvatne** [comment]
you might want to use something like sentry to see a more detailed error stack: https://docs.expo.io/guides/using-sentry/

you can also try running your app in production mode locally to reproduce. if you can come up with a minimal reproducible example that involves the code in this repository, please share and we can help.

**Comment by Jidnyesh** [comment]
Will sentry show errors in the code from which the app was exported ?
Currently its showing errors related to bundles and some error which don't provide any information

How is that it is running perfect in development and gets an error in production?

**Comment by brentvatne** [comment]
i'm not sure i totally understand the question, but sentry will use source maps to map errors back to the original file and line in your code (before being transpiled, minified, and concatenated for production).

try this: https://docs.expo.io/workflow/development-mode/#production-mode

different babel transforms apply in production. different code executes in your app depending on your own logic, or in libraries depending on their logic. it's not possible for expo to control these cases, at some point it's up to app developers and library authors

**Comment by Jidnyesh** [comment]
Trying that link didn't worked, its running the same without errors in --no-dev. But in production, its running into errors.
I would have blamed the library but its aws-amplify. A lot of developers are already using it with react-native and I don't think its the error.
I will still try using sentry, and let you know if anything gets solved.

**Comment by Jidnyesh** [comment]
Writing again because sentry isn't helping a lot to identify the error. Its showing errors in app bundle lines but not in which part of the code. Its showing error in somethings like ```app:///bundle-FCFD744EAF9A7B18E51493891EC56DD19FDB6AA8DA850F50228C88BCD5D791AF in default at line 1051:455```
Could you tell me how can I solve this error by the information given?

**Comment by brentvatne** [comment]
make sure your source maps are being uploaded to sentry. if all else fails, try https://expo.fyi/manual-debugging
