### ISSUE TITLE
google auth :   Exception:  you must specify | client Id |  for |GID Signin| was thrown while 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#1209]
I dont understand why it works fine on simulator both on mac and also inside the expo app on my phone… but after deploying it to production it throws this error.

expo version: 21

Currently, this one specific to ios.

![](https://expo-discourse-uploads.s3-us-west-1.amazonaws.com/original/2X/b/bb991e78b3460e4a01eb9395d82cf9b6b391318e.jpg)

**Comment by brentvatne** [comment]
hi there

1) you should update to the latest version of expo
2) you should be sure you followed these steps properly: https://docs.expo.io/versions/latest/sdk/google.html#deploying-to-a-standalone-app-on-ios

let me know if this resolves your problem

**Comment by jpca999** [comment]
"you should update to the latest version of expo"
okay, this could be the issue...   I just updated the expo by npm update expo. 
I'll keep you updated,   Appreciate your reply @brentvatne

**Comment by jpca999** [comment]
@brentvatne  okay so after updating the npm update expo on my mac.  I hit publish on expo xde, it didnt work 

for the second option. 
"
you should be sure you followed these steps properly: https://docs.expo.io/versions/latest/sdk/google.html#deploying-to-a-standalone-app-on-ios"

you think id be able to resolve g auth without updatng the sdk to 24 ?

**Comment by bogdan-calapod** [comment]
Also experiencing this with the latest version of Expo. Works just fine in dev and in Expo client app, but as soon as I make the production build it throws with this error.

**Comment by lfventura** [comment]
I am getting the same error and already applied everything that the docs says.
Did someone sorted it out? It is working good on expo but it fails when I build the IPA and install at my cellphone.

**Comment by AdamJNavarro** [comment]
Hey @jpca999,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. It looks like @takuya0206 has solved this, but if you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
