### ISSUE TITLE
BarcodeScanner change direction of camera

### ISSUE THREAD

**Issue by lucfranken** [expo/expo#121]
I am testing out the barcode scanner.

Example reproduction which crashes on iPhone and iPad with iOS 10 here:

https://snack.expo.io/H1BFJVPRe

I try to change the direction of the camera. I do that by setting a state variable on a button press.

Expected: Camera changes direction
Actual result: Full crash without any logs available

Reason why researching this: 
Even when the camera direction is set hardcoded to 'front' it sometimes uses the back camera. Cannot reproduce that issue consistently. It looks like a loading order problem. I tried to fix it with a simple button as a workaround but that also does not work as seen in the example.

The code (also available in the snack):

```
import React from 'react';
import { Text, Button, View, StyleSheet } from 'react-native';
import Expo, { BarCodeScanner, Permissions } from 'expo';

export default class BarcodeScannerExample extends React.Component {
  state = {
    hasCameraPermission: null,
    cameraDirection: 'back',
  }

  async componentWillMount() {
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({hasCameraPermission: status === 'granted'});
  }
  
  _changeDirection() {
    this.setState({cameraDirection: 'front'});
  }
  
  render() {
    const { hasCameraPermission } = this.state;
    if (hasCameraPermission === null) {
      return <View />;
    } else if (hasCameraPermission === false) {
      return <Text>No access to camera</Text>;
    } else {
      return (
        <View style={{flex: 1}}>
          <BarCodeScanner
            onBarCodeRead={this._handleBarCodeRead}
            style={StyleSheet.absoluteFill}
            type={this.state.cameraDirection}
          />
          <Button title={this.state.cameraDirection} onPress={() => {this._changeDirection()}}/>
        </View>
      );
    }
  }

  _handleBarCodeRead = (data) => {
    alert(JSON.stringify(data));
  }
}

Expo.registerRootComponent(BarcodeScannerExample);
```

Minor documentation issue:
https://docs.expo.io/versions/v15.0.0/sdk/bar-code-scanner.html

It is missing the StyleSheet import, that raises an error when copying the example into a snack.

**Comment by dikaiosune** [comment]
cc @nikki93

**Comment by brentvatne** [comment]
all fixed ins sdk18, to be released later today
