### ISSUE TITLE
[LocalAuthentication] Huawei 3D Facial Recognition not recognized

### ISSUE THREAD

**Issue by mstankov** [expo/expo#12107]
### Summary

supportedAuthenticationTypesAsync does not detect a Huawei physical device (P40 Lite)'s facial recognition feature

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

Bare

### Environment

react-native: 0.63.4
expo-local-authentication: 9.5.0

### Reproducible demo or steps to reproduce from a blank project

None available

Testing on a physical Huawei device: P40 Lite. `supportedAuthenticationTypesAsync` does not return the device's 3D facial recognition as available even though I have it registered and usable. I noticed in another thread that samsung have changed their facial recognition feature's ID to samsung-branded, like samsung.hardware.bio.face or so. I was wondering whether Huawei have done the same but unfortunately `mPackageManager.getSystemAvailableFeatures()` does not returning anything even remotely hinting to facial recognition. Did a bit of digging and this came up:
[Huawei FIDO](https://www.reddit.com/r/HMSCore/comments/lsskmv/step_by_step_integration_for_huawei_fido/)

Does this mean that in order to support facial recognition, I'd have to create a custom native module using Huawei's FIDO SDK?

Thanks

**Comment by byCedric** [comment]
Hi @mstankov, the short answer is "yes, I'm afraid so". The long answer is because `expo-local-authentication` was built with the native Android API called "[Biometric Prompt](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt)".  This gave us the basic functionality for all Android devices. Now that Huawei is diverging from normal Android, including this biometric library, those APIs won't work on Huawei devices.

That being said, if there is an easy way to add support for Huawei devices, we'd love a PR. Maybe there is a shim or library to "translate" the Biometric Prompt API to Huawei's API.

Hope this helps!

**Comment by mstankov** [comment]
> Hi @mstankov, the short answer is "yes, I'm afraid so". The long answer is because `expo-local-authentication` was built with the native Android API called "[Biometric Prompt](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt)". This gave us the basic functionality for all Android devices. Now that Huawei is diverging from normal Android, including this biometric library, those APIs won't work on Huawei devices.
> 
> That being said, if there is an easy way to add support for Huawei devices, we'd love a PR. Maybe there is a shim or library to "translate" the Biometric Prompt API to Huawei's API.
> 
> Hope this helps!

@byCedric thanks for answering! I built me a small custom module following expo's module structure but unfortunately their own library returns **false** when asked whether the given device supports facial recognition haha... Basically their latest SDK is built to partially be used with local authentication using biometry - the other part being to authenticate online payments and other operations that are tightly connected to the new Huawei environment (HMS). Considering that, i don't think it's wise to add it to expo-local-authentication.
