### ISSUE TITLE
Remote debugger, live reload & hot reloading, all unavailable

### ISSUE THREAD

**Issue by laurion** [expo/expo#1210]
Remote debugger, live reload & hot reloading, are all greyed out & it says "unavailable"
To the right of "Hot Reloading Unavailable" there's also an info button and it says to disable live reload, but live reload can't be clicked on because it's also unavailable. It does however reload every time I save. Expo XDE says "Restarted watchman".

The remote debugger I can't understand why it's unavailable and there seems to be no other issue with this problem.

**Comment by terribleben** [comment]
It sounds like development mode accidentally got disabled in XDE:
![image](https://user-images.githubusercontent.com/1316332/34576889-422c86d8-f134-11e7-8abe-4e85e52bffde.png)
Development mode slows down your project slightly, but allows you to use tools like Debugging. It is enabled by default in XDE but somehow it seems to be turned off for you. Try enabling this, then pressing "Refresh" on the device. Hope that helps!

**Comment by davidalekna** [comment]
Was battling with this issue all day... It was in development mode already but I have toggled it couple of times and then restarted the project, all back to normal now...

**Comment by terribleben** [comment]
One very confusing issue is that "Reload JS Bundle" is insufficient to pick up a change to development mode. You need to use "Refresh" to fetch the new project manifest.

We think that behavior is annoying and are tracking that issue here: https://github.com/expo/expo/issues/413

I'll close this for now, let us know if you're still having trouble.

**Comment by laurion** [comment]
Thanks!

Should I file another bug report about the fact that the info message next to hot reloading is misleading? It shouldn't say to disable live reload, but instead to enable development mode at least as another possible action. Or warn somewhere that you're not in development mode..

**Comment by beaurushton** [comment]
Just got caught on this myself, a hint to enable development mode would be helpful.

**Comment by sherxia92** [comment]
I fixed which by update the paramter.
![qq 20180704104629](https://user-images.githubusercontent.com/20177543/42254082-8730da46-7f77-11e8-885c-602cb7a3618b.png)
