### ISSUE TITLE
GoogleSignIn.signInAsync stopped working suddenly in PROD

### ISSUE THREAD

**Issue by okeybond** [expo/expo#12105]
### Summary

GoogleSignIn.signInAsync stopped working suddenly in PROD for android. It works fine in iOS. My users get Error
GoogleSignIn.null: DEVELOPER_ERROR when they try to sign it with Google. Please help, so many issues starting from 2021-02-28.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 30.0.2
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.45 => 0.12.57 
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Try implementing GoogleSignIn, and then upload an testing the standalone app in PROD. Please note it works if I build apk and test on my devices. It just doesn't work when I upload the apk or aab. All the relevant fingerprint is in firebase and fetch:android:hashes returns values that tally with firebase.

await GoogleSignIn.initAsync();
await GoogleSignIn.askForPlayServicesAsync();

work, but it fails on GoogleSignIn.signInAsync

```
export const socialLogin = (selectedProvider) =>
    async (dispatch, getState) => {
            await GoogleSignIn.initAsync();
            console.log('initAsync completed');
            await GoogleSignIn.askForPlayServicesAsync();
            console.log('askForPlayServicesAsync completed');
            const {type, user: {auth: {idToken, accessToken}}} = await GoogleSignIn.signInAsync();
            console.log({type})
            if (type === 'success') {
                const credential = firebase.auth.GoogleAuthProvider.credential(
                    idToken,
                    accessToken,
                );
}
```

**Comment by grifotv** [comment]
@okeybond wondering if you found a solution for this?

I'm having a similar problem: I have a bare workflow app that has Google Sign In working fine in debug mode and release mode when installing from my computer. I made sure there are SHA certificate fingerprints for the debug and release keystores. Both SHA certificate fingerprints were also added to the Firebase project.

My beta testers get this error `GoogleSignIn.null: DEVELOPER_ERROR` with the app installed from Google Play Store only.

**Comment by grifotv** [comment]
@okeybond I think that's the solution https://github.com/react-native-google-signin/google-signin/blob/master/docs/android-guide.md#google-login-does-not-work-when-downloading-my-app-from-the-play-store

We need to add the SHA certificate fingerprint from Google Play Console. So in total, I added 3 fingerprints. I'll test it as soon as it's deployed and will let you know.

**Comment by okeybond** [comment]
> @okeybond I think that's the solution https://github.com/react-native-google-signin/google-signin/blob/master/docs/android-guide.md#google-login-does-not-work-when-downloading-my-app-from-the-play-store
> 
> We need to add the SHA certificate fingerprint from Google Play Console. So in total, I added 3 fingerprints. I'll test it as soon as it's deployed and will let you know.

I am really grateful, it worked. I hope it worked for you

**Comment by BrodaNoel** [comment]
After 1 year I could this this problem. It was just a missing fingerprint. Thanks guys!
I'm going to add some info about it to the documentation.
