### ISSUE TITLE
[Expo Go][iOS] First load of a landscape app often breaks the loader, splash screen, red box, and dev menu behavior

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#12109]
# What

- In a landscape app, the first load of an app (completely restart the client to test (no need to restart the bundler)), causes the loader to show up on the top of the device, the splash screen to be pushed over, and if your app loads with an error, the red box will be broken. Sometimes the components go back to normal, but in larger apps they just stay broken.

# Repro

- Create a new blank project.
- In `app.json`, set `expo.orientation: "landscape"`.
- Open the project on an iOS device.
  - Close the client app completely, reopen the app.

https://user-images.githubusercontent.com/9664363/110044703-70be7700-7cfe-11eb-8314-7d13ce285ec0.mov

**Comment by sagearora** [comment]
Yes having this exact same issue and I have no idea how to fix this...it looks so ugly :(
