### ISSUE TITLE
[Android][file system] Investigate `file:/` and `file:///` schemas

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#12101]
### Summary

This is an investigation issue that should answer the questions raised in https://github.com/expo/expo/pull/11823.

Android is either using `file:/` or `file:///` url/uri schemas to handle local files and we need to be sure we have a consistent behaviour across all modules.

### What platform(s) does this occur on?

Android

### Environment

Expo SDK 40/41

### Reproducible demo or steps to reproduce from a blank project

See https://github.com/expo/expo/pull/11823

**Comment by cruzach** [comment]
maybe also related - https://github.com/expo/expo/issues/10906

**Comment by hbiede** [comment]
While #12439 may have fixed this issue for `expo-image-picker`, it appears to still be an issue for `expo-file-system`
