### ISSUE TITLE
Android - windowSoftInputMode="adjustResize" doesn't work

### ISSUE THREAD

**Issue by ArsenyYankovsky** [expo/expo#1211]
Hello,

It seems like this option doesn't work for me. I've read the [earlier issue](https://github.com/expo/expo/issues/351) on that matter and it seems like I need to use an opaque status bar for it to work.

So I changed my status bar to the following:

`<StatusBar transcluent={false} backgroundColor="#000000" />`

But it still doesn't work for me. 

I also tried setting it via app.json like that:
```
    "androidStatusBar": {
      "backgroundColor": "#000000"
    },
```
 but it didn't work for me either.

My sdk version is 23.0.0

Thanks.

**Comment by ArsenyYankovsky** [comment]
Ok, got it working with a native build, but the adjustResize value breaks my layout. I understand that right now there is no way of configuring other behavior without detaching but I think this is a MUST. Should I create another issue to reflect that?

![device-2018-01-04-162243](https://user-images.githubusercontent.com/1508345/34565355-9a57b33c-f16b-11e7-9818-2681b75a5a97.png)

**Comment by brentvatne** [comment]
hello! this is another option for how to change the color: https://docs.expo.io/versions/latest/guides/configuring-statusbar.html#place-an-empty

**Comment by ArsenyYankovsky** [comment]
@brentvatne Thanks for reading my message thoroughly.
