### ISSUE TITLE
[iOS] Standalone offline app could not connect to development server

### ISSUE THREAD

**Issue by jnoyola** [expo/expo#12117]
### Summary

Basically `updates.enabled: false` does not seem to work on iOS. When running the app, it fails on startup saying "Could not connect to development server. [...] URL: http://127.0.0.1:8000/bundles/ios-xxxx.js".

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

39.0.2 and 40.0.1

### Environment

```
  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. Create blank app: `expo init test-app -t blank`
2. Edit app.json and set `updates.enabled: false` and `ios.bundleIdentifier: xxxx`
3. Export locally: `expo export --dev --public-url http://127.0.0.1:8000`
4. Host locally: `npx http-server -p 8000 dist`
5. Build locally (turtle-cli v0.20.7) in a separate terminal:
    ```
    EXPO_IOS_DIST_P12_PASSWORD="aaaa" \
    turtle build:ios \
    --team-id "bbbb" \
    --dist-p12-path "cccc" \
    --provisioning-profile-path "dddd" \
    --public-url "http://127.0.0.1:8000/ios-index.json" \
    --allow-non-https-public-url \
    --output "eeee" \
    --type simulator
    ```
6. Stop hosting. Install and run app in the iPhone simulator. (Same behavior if an ipa on a device.)

This seems to be a recurring problem based on closed issues. I tried changing `fallbackToCacheTimeout` to non-zero, changing `checkAutomatically`, and various other tips I've found on github, but nothing solves this problem. I see another user [here](https://forums.expo.io/t/standalone-ios-app-builded-with-turtle-cli-fails/46673) with the same issue. I have not tested it on Android myself, but that forum post says this is only a problem on iOS. For this to be working correctly, I would like to be able to locally build a standalone offline app with the managed workflow.

**Comment by jnoyola** [comment]
[Here](https://forums.expo.io/t/building-offline-ipa-app-locally-without-publish-or-eject/49631) is my own forum post by the way, but I opted to open a GitHub issue based on the suggestion in the linked forum post, since I could not find a similar issue from that user.

**Comment by jnoyola** [comment]
Here is an identical issue with comments from jpcodr, the author of the other forum post. Unfortunately their workaround was simply to host the files, which doesn't address the problem if we want the app to be offline. I would really like to have the option to turn off updates and generate entirely self-contained apps.
https://github.com/expo/turtle/issues/282

**Comment by charles-m-knox** [comment]
This appears to be happening to me too. Still looking into it, but wanted to put a second voice on the matter. Agreed with @jnoyola that the ability to generate self-contained apps should be supported.

**Comment by charles-m-knox** [comment]
Somewhat related to https://github.com/expo/turtle/issues/302, which brought me to this point.

**Comment by charles-m-knox** [comment]
@jnoyola , are you still experiencing this issue? For what it's worth, I was able to solve it using:

* some networking tricks
* a domain name (or subdomain) I have control over
* caddy (I have a sample caddy config file that you can use [here](https://github.com/charles-m-knox/space-codes/blob/main/caddy/Caddyfile))
* removing the `--dev` flag from the `expo export` command
  * VERY important - I see that this flag is present in your comments, you may want to try removing it if you haven't?

See my comment for some more details in my other issue here: https://github.com/expo/turtle/issues/302#issuecomment-809848518

For a complete Mac-based guide, I included all the steps I ran in my app: https://github.com/charles-m-knox/space-codes#building-locally
