### ISSUE TITLE
[expo-task-manager] TaskManager skipping tfjs-react-native task

### ISSUE THREAD

**Issue by ragalz** [expo/expo#12119]
### Summary

I'm trying to train some model on the background ( a very very light model), but the TaskManager seems to be skipping the task, it skips to the next iteration of the task without finishing the current task 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

4.14

### Reproducible demo or steps to reproduce from a blank project

Use "@tensorflow/tfjs" & "@tensorflow/tfjs-react-native" in order to create mode, fit it with some random params (doesn't even matter that it works in this case). Do all of this inside the function scheduled.

**Comment by byCedric** [comment]
Hi @ragalz, thanks for writing in. Could you provide a repository or Snack with the code causing this issue? With that, we would be able to investigate this further.

**Comment by ragalz** [comment]
Looking for alternative ways of doing this I discovered that carrying on heavy tasks (is a very tiny model yes, but even so) on a background task is not a good idea. This is why I incline more on doing this in a foreground task (I know it's only available in Android). If you think I could be doing this in the background task (It'd be preferable) I'll send you the code, but otherwise, I'd rather not waste anyone's time.
