### ISSUE TITLE
Could not install the app on the device after Expo detach 

### ISSUE THREAD

**Issue by nicoara** [expo/expo#1212]
After Expo Detach, I cannot run a project in Android Studio 2.3 in Windows 10:
If I try to run it in Android Studio, the app does not work, I am asked if I have an Expo app.
If I try to run it from command line  
C:\Users\nicoara\Desktop\demoapp>react-native run-android
Scanning folders for symlinks in C:\Users\nicoara\Desktop\demoapp\node
_modules (47ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat install
Debug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

After two hours of debugging, all the answers here are still confusing as an answer.
Please explain clearly the steps, as in (although the order below does not work):

1) detach
2) open in Android Studio the detached project
3) open in Expo XDE on desktop the detached project
4) run react-native run-android in command line

Thanks

**Comment by jesseruder** [comment]
Hi @nicoara! Did you follow the instructions here? https://docs.expo.io/versions/latest/guides/expokit.html#setting-up-your-project

**Comment by keeratita** [comment]
Hi @jesseruder ,

Please correct me if i'm wrong. My understanding is - I have to publish my expo app (detached) before building an APK file. Once my client downloads and installs my app, the app has to load data (js, assets, etc.) from CDN (where given from published).

If yes, is there a way to build app with bundled assets and js at the start?

Thank you in advance and sorry for my bad english.
Cheers!

**Comment by AdamJNavarro** [comment]
@keeratita Your understanding is correct. There are two configurations you can do in your app.json to bundle assets in your binary (https://docs.expo.io/versions/latest/guides/configuration.html#assetbundlepatterns) and to load your JS quicker (on iOS) (https://docs.expo.io/versions/latest/guides/configuration.html#loadjsinbackgroundexperimental)

**Comment by keeratita** [comment]
Hi @AdamJNavarro thanks so much for your information. I will try to build it again today.

**Comment by githubmss** [comment]
I have detached the application code from Expo and then import the android folder in my android studio then in terminal I run command exp start after running command when I run the code from android studio my application works fine , but when I try to run the same code using react-native run-android it displays me error and did not run application, Anybody out there did this before, I am scratching my head on this from past 8 hours, Any suggestion will be Appreciated !!!

**Comment by ide** [comment]
If you have a detached project, you should continue using `exp start` while building your project in Android Studio or a similar tool. If you want to use `react-native run-android` and other tools, that's a different path with bare React Native that doesn't currently support Expo APIs.

**Comment by wjielim** [comment]
I'm facing issue setting up ExpoKit project on Windows 10 as well. 
Not sure whether if it's a SDK issue or not, I'm on SDK 29. 
On a side note, I think the setup guide [here](https://docs.expo.io/versions/latest/guides/expokit.html#setting-up-your-project) is more biased towards MacOS or Linux, there's no clear direction on how to setup on Windows 10. (especially on the adb part)

**Comment by paul019** [comment]
I've also problems installing my app on the simulator after `exp detach`. I'm using iOS and Xcode and can in fact build and install the app via Xcode. But then I get the following error:

<img width="526" alt="bildschirmfoto 2018-11-07 um 16 02 00" src="https://user-images.githubusercontent.com/39464035/48147698-34a6b300-e2b8-11e8-9d67-2e8d3b8e825f.png">

I'm serving the JS server correctly via `expo start`, but get the error anyway. @jesseruder @ide Do you've any idea, what's wrong here?

**Comment by chintansavjiyani1996** [comment]
If you have a detached project you have to follow these steps:
1)open android folder in android studio, Sync gradle file and install all dependencies 
2)go to the project directory run command ```expo start```
3)start App via play button in android studio
