### ISSUE TITLE
[Expo Go][iOS] Drop SDK 22 checks

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#12127]
- https://github.com/expo/expo/blob/c247e20f11b037126073991620b3ed8bdaa8b338/ios/Exponent/Kernel/ReactAppManager/EXReactAppManager.mm#L335-L338
- https://github.com/expo/expo/blob/c247e20f11b037126073991620b3ed8bdaa8b338/ios/Exponent/Kernel/ReactAppManager/EXReactAppManager.mm#L357-L360

**Comment by Simek** [comment]
It looks like the mentioned checks are no longer present on `master` and have been removed in:
* #14690
