### ISSUE TITLE
Unable to resolve module in iOS and Android, but not in Web

### ISSUE THREAD

**Issue by akolybelnikov** [expo/expo#12136]
### Summary

I have installed (near-api-js)[https://www.npmjs.com/package/near-api-js] in the newly created project and whereas it builds well with Web, iOS and Android builds started throwing the error:
```
Unable to resolve module http from /.../near/near-app/node_modules/near-api-js/lib/utils/web.js: http could not be found within the project.
   5 | Object.defineProperty(exports, "__esModule", { value: true });
   6 | exports.fetchJson = void 0;
>  7 | const http_errors_1 = __importDefault(require("http-errors"));
     |                                                ^
   8 | const exponential_backoff_1 = __importDefault(require("./exponential-backoff"));
   9 | const providers_1 = require("../providers");
  10 | const START_WAIT_TIME_MS = 1000;
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40.0.0

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v12.15.0/bin/npm
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@reddree/spunky-waffle

**Comment by brentvatne** [comment]
you should post on the repository for near-api-js if it's meant to support react-native and it doesn't. we don't maintain that library
