### ISSUE TITLE
I can not sign up expo.io

### ISSUE THREAD

**Issue by ARAldhafeeri** [expo/expo#12145]
###  I can not sign  up  at expo.io 

Error: 
Something went wrong when connecting to Expo: Failed to fetch.

**Comment by brentvatne** [comment]
are you able to access https://expo.dev in your browser?

**Comment by ARAldhafeeri** [comment]
Yes same when I try to make an account because, I am trying to deploy my app. When I register , I get the following: 

Something went wrong when connecting to Expo: Failed to fetch.

**Comment by byCedric** [comment]
Are you able to access https://exp.host/ (our API)?

**Comment by ARAldhafeeri** [comment]
@byCedric , I have tried naively to send a post request to the URL. 
```
const url= const url= "https://exp.host/--/api/v2/project/configuration/schema/40.0.0";

await fetch(url,
 {method: "POST",
email:"iahmedkuw@gmail.com", 
username:"iahmedkuw",
 password:"12341234Q@",
 confirmpassword:"12341234Q"}
).then(response => console.log(response))

```

I got this response back:
```
VM1361:1 Refused to connect to 'https://exp.host/--/api/v2/project/configuration/schema/40.0.0' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://alive.github.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com online.visualstudio.com/api/v1/locations".

(anonymous) @ VM1361:1
VM1361:1 Refused to connect to 'https://exp.host/--/api/v2/project/configuration/schema/40.0.0' because it violates the document's Content Security Policy.
(anonymous) @ VM1361:1
VM1361:2 Uncaught TypeError: Failed to fetch
    at <anonymous>:1:7
```

Documents for this response:
https://developers.google.com/web/fundamentals/security/csp

The jest of the following response is:
An endpoint violates the Content Security Policy directive when : 
Code from specific URL should only have access to that specific URL. When another URL that is not " whitelisted " then the violation happens.

**Comment by brentvatne** [comment]
@ARAldhafeeri - are you able to navigate directly to https://exp.host/--/api/v2/project/configuration/schema/40.0.0 in your browser? it should show you a json doc

**Comment by ARAldhafeeri** [comment]
@brentvatne 

 https://exp.host/--/api/v2/project/configuration/schema/40.0.0

Does not show a JSON doc. It keep attempting to fetch it though. And instead, of getting status 200 on the fetch. 

it keep loading an unsecure domain that response to the get response by this image: 
![request](https://user-images.githubusercontent.com/48261339/110766552-54728b00-8266-11eb-9106-bfd252f4f1d9.png)


in the network tap, the process keeps repeating , request to 
 https://exp.host/--/api/v2/project/configuration/schema/40.0.0 
are redirected to the image url shown above. 

over and over again

![expo](https://user-images.githubusercontent.com/48261339/110766731-8a177400-8266-11eb-9713-d53666162fdf.JPG)

Anything I can do to help ?

**Comment by ide** [comment]
Are you able to connect using curl? That way you can eliminate the same-origin policy from the situation.

It may be that your ISP or something else about your internet connection is preventing you from connecting, which we have no control over.

**Comment by ARAldhafeeri** [comment]
@ide  you were right thank you so much. I guess there was a problem with my ISP as you said or somthing.

I connected to VPN  over my phone and was able to register. I am located in kuwait. 

I was also able to login without VPN 

Thanks.
