### ISSUE TITLE
Local Notifications Permissions do not work in fresh SDK 39 app when deployed to Testflight

### ISSUE THREAD

**Issue by yolpsoftware** [expo/expo#12141]
### Summary

The reproducible demo (see below) is an app that shows a "local notification" to the user when run on the Expo Go app.

However, if deployed via Testflight, the app won't show the notification, and it won't ask the user for the notifications permissions. `Permissions.getAsync` will return `status=undetermined`, and the app won't appear in the notifications section in the Settings app.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

39

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/opt/nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.3 - /usr/local/opt/nvm/versions/node/v14.15.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.4 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

* Clone this repo: https://github.com/yolpsoftware/expo-notifications
* Run yarn
* Create a new App ID (with Push Notifications checked) in your Apple Developer Account
* Create a new App in App Store Connect, using the App ID.
* Set the App ID in `app.json` under `ios.bundleIdentifier`. Make sure the app version matches the one in App Store Connect.
* `expo build:ios --release-channel production`, choose all default settings (let Expo handle everything)
* `curl -o app.ipa "$(expo url:ipa --non-interactive)"`
* Deliver the app via Transporter or via `fastlane deliver --ipa "app.ipa" --skip_screenshots --skip_metadata`

When the app appears in Testflight, we expect it to ask the user for the Notifications Permission. However, this prompt does not appear. Instead, we get `status=undetermined` on the permission.

**Comment by brentvatne** [comment]
you never request permissions, you only check the status. note the difference between `getPermissionsAsync` and `requestPermissionsAsync`.

https://docs.expo.io/versions/v39.0.0/sdk/notifications/#requestpermissionsasyncrequest-notificationpermissionsrequest-promisenotificationpermissionsstatus

i was able to reproduce your described issue in expo go because it's not actually a bug but improper usage of the api. see below for a fixed version of your example - it works as expected in expo go and will continue to work in a simulator build (`expo build:ios -t simulator`) or a build on test flight.

i suspect you might have seen this working in expo go because you probably had some code for requesting the permission before and then removed it, so the app in expo go already had permissions.

```js
import React from 'react';
import * as Notifications from 'expo-notifications';
import { Alert, Text } from 'react-native';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: true,
  }),
});

Notifications.requestPermissionsAsync()
  .then(permission => {
    Alert.alert(JSON.stringify(permission));
    Notifications.scheduleNotificationAsync({
      content: {
          title: 'Hello',
          subtitle: 'world',
      },
      trigger: {
          seconds: 10,
      }
    });
  })

export const App = () => {
  return <Text style={{justifyContent: 'center', alignItems: 'center'}}>Hello World</Text>
}

export default App;
```

**Comment by yolpsoftware** [comment]
@brentvatne wow, sorry for this! I really was sure that I tried the same thing with `Permissions.askAsync` and that it didn't work either, but apparently it does work! Thanks a lot and sorry for the false alarm.

**Comment by brentvatne** [comment]
i'd suggest moving away from using expo-permissions and instead use the permissions methods on specific modules. we're deprecating expo-permissions in sdk 41 as it's not longer needed

**Comment by yolpsoftware** [comment]
That's great, I was asking myself why there are two options for the same thing.
