### ISSUE TITLE
Expo CLI says Push Notification Key Setup, but get error when trying to use for push notifications

### ISSUE THREAD

**Issue by broksonic21** [expo/expo#12142]
## Description

Expo-cli says that we are using a good push notification key (for iOS) but it apparently isn't checking enough, as trying to use the key causes Expo to say it's missing. 

(Note: using ExponentToken and sendPushNotificationsAsync on Android push notifications work fine). but iOS we are having issues with - expo knows about our APN, but complains when actually sending.

I can confirm expo credentials:manager shows our only Push Key is assigned to the right owner/slug. I can confirm expo fetch:ios:certs also pulls the right key and team, include the right p8 file.

## Expected Behavior

If credentials:manager and fetch;ios:certs says a p8 is good to go, expo knows about it when trying to curl into a push token.

## Observed Behavior

`expo credentials:manager -p iOS`:

```
Accessing credentials for REDACTED in project REDACTED
Available credentials for iOS apps

Application credentials

  Experience: @ REDACTED/REDACTED, bundle identifier: REDACTED
    Provisioning profile (ID: REDACTED)
    Apple Team ID: REDACTED,  Apple Team Name: REDACTED (Company/Organization)


User credentials

  Distribution Certificate - Certificate ID: REDACTED
    Apple Team ID: REDACTED,  Apple Team Name: REDACTED (Company/Organization)
    used by
      @REDACTED/REDACTED (REDACTED)

  Push Notifications Key - Key ID: REDACTED
    Apple Team ID: REDACTED,  Apple Team Name: REDACTED (Company/Organization)
    used by
      @REDACTED/REDACTED (REDACTED)

```

`expo fetch:ios:certs`:

```
These credentials are associated with Apple Team ID: REDACTED
Wrote distribution cert credentials to disk.
Wrote push key credentials to disk.
Wrote provisioning profile to disk
Save these important values as well:
 
Distribution P12 password: REDACTED
Push Key ID:               REDACTED
Push P12 password:         (not available)
From the app, we can get an ExponentPushToken fine.
```

I can also confirm that expo did in fact create a P8 Key in the Apple Credentials dashboard.

but trying to curl shows this error: (same error in calling sendPushNotificationsAsync - note: Android works, just not iOS)

```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[REDACTED]",
  "title":"hello",
  "body": "world"
}'
```

```
{"data":{"status":"error","message":"Could not find APNs credentials for REDACTED (@REDACTED/REDACTED). You may need to generate or upload new push credentials.","details":{"error":"InvalidCredentials"}}}%
```

I’ve confirmed that this also fails with the same error on the Expo Push Test Tool - it also says “Could not find APNs credentials for REDACTED (@REDACTED/REDACTED). You may need to generate or upload new push credentials” for any of these tokens.

## Environment

```
Expo CLI 4.0.7 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.2.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/Cellar/node/15.2.1/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.40 => 0.12.40
      expo: ^37.0.0 => 37.0.12
      react: ^17.0.1 => 17.0.1
      react-dom: ^17.0.1 => 17.0.1
      react-native: ^0.63.3 => 0.63.3
      react-native-web: ^0.14.5 => 0.14.5
      react-navigation: ^4.4.3 => 4.4.3
    npmGlobalPackages:
      expo-cli: 4.0.7
    Expo Workflow: bare
```

Phone: iOS 11

## Reproducible Demo

Happens on our account - not sure if it happens on other accounts though.

**Comment by markymc** [comment]
@quinlanj @brentvatne Any news on this? Or @broksonic21 @wallacer did you guys find a solution?

We're attempting to use Expo notifications in our bare app and have the same setup/problem as @broksonic21, except that we have `Distribution P12 password: (not available)` as we're not using Expo's build services.

**Comment by abhandaru** [comment]
Having this issue as well, if it's any signal.

**Comment by virginia-duca** [comment]
I'm having the same issue, i uploaded the APNS key credentials through the expo:manager, but the expo is still unable to use the credentials or connect to the the APN server. Did anyone found a solution ?

**Comment by wallacer** [comment]
I ultimately decided to eject and switch to firebase for notifications.  Had a much smoother experience than expo

**Comment by finnigantime** [comment]
@quinlanj thank you, I hit this issue as well and your post helped me solve it

Getting `experienceId` right was the key for me. For `@expo_account/expo_projectname`, `expo_account` is the value of `expo.owner` in app config (app.config.ts for my app) and `expo_projectname` is the value of `expo.slug`.
