### ISSUE TITLE
Unable to validate credentials. Request ID 4ef243d0-f17f-11e7-8ca2-a34346d76906, message: Internal error occurred.

### ISSUE THREAD

**Issue by jpca999** [expo/expo#1214]
Unable to validate credentials. Request ID 4ef243d0-f17f-11e7-8ca2-a34346d76906, message: Internal error occurred. Please try again in a few minutes or contact support.
  

@anp @brentvatne  can you pls do your magic on this ?

**Comment by fxfactorial** [comment]
Hi, please upgrade to latest exp. I think you might be on something older.

**Comment by jpca999** [comment]
@fxfactorial   Do you mean   "sdkVersion": "21.0.0",  in app.json  or       "expo": "^21.0.0",  in package ?

**Comment by fxfactorial** [comment]
No, the `exp` CLI client itself. `npm i -g exp` or use it locally in your project

**Comment by jpca999** [comment]
@fxfactorial   I tried what you said,  so i dont get the same error message but now it complains for 
I also tried removing the old apple certificates.   any idea how to resolve this ?

![image](https://user-images.githubusercontent.com/1026325/34586042-26edb7fc-f157-11e7-876a-de150a190c71.png)

**Comment by fxfactorial** [comment]
exp was trying to help you, it says to remove the existing provisioning profile on your developer account on Apple.

**Comment by jpca999** [comment]
your right, i did it by removing the certificates on here :  

![image](https://user-images.githubusercontent.com/1026325/34587278-8a010218-f15c-11e7-846a-98b82e3f5a4f.png)
