### ISSUE TITLE
`getAvailablePictureSizesAsync` throws an error when invoked with valid ratio

### ISSUE THREAD

**Issue by muZk** [expo/expo#12168]
### Summary

I'm using `getAvailablePictureSizesAsync(ratio)` with an available `ratio` (from `getSupportedRatiosAsync`) but it throws an `unexpected error`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare AND managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/muzk/.rvm/rubies/ruby-2.4.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 25, 27, 28, 29, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0
        System Images: android-28 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Snack demo: https://snack.expo.io/@muzk/sadistic-mixed-nuts

Steps:

- Use a real android device. _I'm having this issue with a Samsung Galaxy J3 (2016) that has android 5.1.1_
- Allow camera permissions.
- Tap on `3:2` or `11:9` buttons. 
- You will see an alert with the error message.

```
[Error: getAvailablePictureSizes -- unexpected error -- Attempt to invoke interface method 'int java.util.SortedSet.size()' on a null object reference]
```

![imagen](https://user-images.githubusercontent.com/1679496/110533503-d181f100-80fc-11eb-979b-8f5385c7d329.png)

**Comment by DCKT** [comment]
Hello there,

I have this issue on the latest SDK, any idea to handle that ? 

Thanks :)

**Comment by muZk** [comment]
@DCKT I filtered out the invalid ratios, something like this:

```js
const supportedRatios = await camera.current.getSupportedRatiosAsync();

const pictureSizes = await Promise.all(
  supportedRatios.map(ratio => camera.current.getAvailablePictureSizesAsync(ratio).catch(() => []))
);

const validRatios = supportedRatios.filter((ratio, index) => pictureSizes[index].length > 0)
```

**Comment by DCKT** [comment]
@muZk Thanks I will try this :)
