### ISSUE TITLE
(SDK40)(Android & iOs) expo-notifications: all methods never resolve

### ISSUE THREAD

**Issue by Prozoft** [expo/expo#12164]
### Summary

functions like getPermissionsAsync and requestPermissionsAsync never resolve (android & ios)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\NickP\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ^0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Create new expo project, add the expo-notifications package. Follow the FCM Setup guide, try to ask for permissions and token. They never resolve

**Methods from 'expo-notifications' never resolve**

I am running into the issue that I am not able to get expo push tokens using the **expo-notifications** package.
It is not the first time I have implemented push notifications but it has been a few SDK's back. I followed the FCM setup guide and implemented everything as documented, twice to be sure.

When I run methods like:
```
await Notifications.getPermissionsAsync();
await Notifications.requestPermissionsAsync();
await Notifications.getExpoPushTokenAsync();
```
They never resolve,

However, this method does and returns 'granted' which is from the 'expo-permissions' package:
`await Permissions.askAsync(Permissions.NOTIFICATIONS)`

I have removed my package-lock json file, cleared expo cache and reinstalled the SDK on my phone. Issue still persists.

**Comment by AdamJNavarro** [comment]
Hey @Prozoft, can you provide a public repo that we can clone and run on our end? It's hard to help without having code we can test on our end.

Cheers,
Adam

**Comment by Prozoft** [comment]
Hi @AdamJNavarro ,

The error that I am receiving is: TypeError: undefined is not an object (evaluating '_expoNotifications.default.getPermissionsAsync')]

When I tried to run the demo from the expo docs, I got a push token, I guess its something with my code or packages.. I cannot tell yet why it is giving me this exception.

**Comment by Prozoft** [comment]
The problem was caused by `import { Constants } from 'expo'`, package has been moved to `expo-constants`
