### ISSUE TITLE
On android device I am getting the following error "Uncaught error: 24.0.0 is not a valid SDK version. Options are 23.0.0, 22.0.0, 21.0.0 20.0.0, 19.0.0, 18.0.0, 17.0.0, UNVERSIONED"

### ISSUE THREAD

**Issue by albaqawi** [expo/expo#1216]
Hi community. 

I am using Expo with my RN project. I am able to link ok via a tunnel without issues. On my **android device** Every time I use the QR code on my **Expo android client**, when I access the application I get this error **"Uncaught error: 24.0.0 is not a valid SDK version. Options are 23.0.0, 22.0.0, 21.0.0 20.0.0, 19.0.0, 18.0.0, 17.0.0, UNVERSIONED".**

On iOS Expo client the app is working perfectly well. 

my system has the following versions:
$ react-native info
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.2.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0
$ react-native -version
react-native-cli: 2.0.1
react-native: 0.51.0

I need to test on Android badly but I am completely stuck. Please help 🙏🏻.

**Comment by brentvatne** [comment]
please install the latest version of the expo client on your device. if this is the simulator, uninstall it from the simulator and start it again to automatically install the latest :)

**Comment by albaqawi** [comment]
Amazing help brentvatne! thank you so so much :D

**Comment by amypellegrini** [comment]
Sorry, I'm currently having this same issue, I re-installed the expo client in my Android device, and I still get the same error `Uncaught Error: 19.0.0 is not a valid SDK version...`

Any ideas?

**Comment by amypellegrini** [comment]
@EvanBacon I have already upgraded to version 26, still having the same error (it keeps insisting with version 19). I have cleared the cache, I deleted my node_modules folder and installed everything again, and also re-installed the expo client in my device... no joy, there must be something very fundamental that I'm missing.

**Comment by amypellegrini** [comment]
@EvanBacon Ok, finally I had a breakthrough, I had to update the `sdkVersion` in the `app.json` file. Now I'm running into other issues but at least I've sorted this one out, I leave my comment here in case some else runs into the same problem. Thanks!
