### ISSUE TITLE
expo-image-manipulator fails to decode bitmap on Android

### ISSUE THREAD

**Issue by ShaneMcNamara** [expo/expo#12167]
### Summary

Calling ImageManipulator.manipulateAsync on Android fails with `java.lang.Exception: Loading bitmap failed`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.1

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.3 - /Users/ShaneMcNamara/.rvm/gems/ruby-2.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

tbd

I'm trying to create image previews using `ImageManipulator.manipulateAsync` as follows:

```
const { uri } = await ImageManipulator.manipulateAsync(
   path, // `${FileSystem.cacheDirectory}photos/${filename}`;
   [{ 
      resize: {
         height:Layout.IMAGE_PREVIEW_SIZE, // 60
      } 
   }],
   {
      compress:0,
      format:ImageManipulator.SaveFormat.PNG
    }
);
```

I receive the following error in my console:
```
Error Could not get decoded bitmap of file:///data/user/0/host.exp.exponent/cache/ExperienceData/myapp/photos/myfile: java.lang.Exception: Loading bitmap failed
```

This seems to only happen for a specific photo, which happens to be the largest of the bunch (16.5 MB). `manipulateAsync` is successful with the same file on iOS and with all the smaller files on Android (up to ~7MB). Is there a size limit for this method?

**Comment by AdamJNavarro** [comment]
Hey @ShaneMcNamara, could you please provide a public repro case that we can clone and run on our end? Your code makes reference to external variables and assets we can't make sense of.

Cheers,
Adam

**Comment by ShaneMcNamara** [comment]
Hi @AdamJNavarro, I can do that, however I'm not sure what you mean by this: "Your code makes reference to external variables and assets we can't make sense of".

```
const { uri } = await ImageManipulator.manipulateAsync(
   path, // `${FileSystem.cacheDirectory}photos/${filename}`;
   [{ 
      resize: {
         height:Layout.IMAGE_PREVIEW_SIZE, // 60
      } 
   }],
   {
      compress:0,
      format:ImageManipulator.SaveFormat.PNG
    }
);
```
In the above:
-  `path` is just the path to the file. It is equal to the path in the comment there, `${FileSystem.cacheDirectory}photos/${filename}`. I'm using  [FileSystem.getInfoAsync](https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemgetinfoasyncfileuri-options) above this block to confirm that the file exists at that path. (Also this whole thing works perfectly fine on iOS). I'm not sure the path is the culprit here, either way it seems easy to create and add the file to that path for purposes of debugging.
- `Layout.IMAGE_PREVIEW_SIZE` just equals 60, as outlined in the comment.

The image, aside from being larger, is just a standard .jpeg file. Is there anything else that I can clarify?

**Comment by ShaneMcNamara** [comment]
@AdamJNavarro - [See here](https://github.com/ShaneMcNamara/image-manipulator-12167).

Interesting to note that the error seems to be related to calling the method multiple times. With just one image, both iOS and Android had no issues. Increasing the array to 10 caused Android to throw the `Loading bitmap failed` error and caused iOS to hard crash my Expo Go app (app disappears, assuming it's being terminated by the OS for consuming too much memory?). Even more curious, I attempted to serialize the `manipulateAsync` calls in the `serialize` branch, which then performs as expected on iOS but still returns the `Loading bitmap failed` error on Android (even after spacing the `manipulateAsync` calls by 60 seconds).

**Comment by ShaneMcNamara** [comment]
Hi @AdamJNavarro , just want to check in and see if you have sufficient information.

**Comment by dsokal** [comment]
Hi @ShaneMcNamara,
I tried to repro this issue with the example app you provided but it's working fine for me (Xiaomi Redmi 4A). What device do you have?

**Comment by ShaneMcNamara** [comment]
> Hi @ShaneMcNamara,
> I tried to repro this issue with the example app you provided but it's working fine for me (Xiaomi Redmi 4A). What device do you have?

@dsokal Here is the device info:

- Samsung Tab A (SM-T510)
- One UI Version 2.1
- Android Version 10
- 2GB RAM
- 32GB Storage

The device is quite underpowered, and has a tough time running its own OS to be fair. However, I would have hoped that the error behaviour was: A. a little more obvious to what the issue is, and B: more graceful than potentially hard killing the app.

Let me know if you need more info, or want me to try anything on this device.

**Comment by shrynshjn** [comment]
Hi, Is there a solution for this problem? Its still occcuring. I am not able to resize png files selected from expo-image-picker.

**Comment by shrynshjn** [comment]
@ShaneMcNamara were you able to find a solution for this?

**Comment by ShaneMcNamara** [comment]
@shrynshjn - I could not fix the issue. The problem was only occurring for large files on Android devices. I am using this functionality to generated small, compressed previews of images. For large images (> 10MB) on Android, I don't generate the previews, instead I display a little icon.

**Comment by BrodaNoel** [comment]
Seems like this error still there on SDK 44.
Does anybody checked if it's fixed on SDK 45?

**Comment by BrodaNoel** [comment]
@IjzerenHein seems like this is still a thing.
Any possibility to reopen it? Thanks!

**Comment by MarioUnlam** [comment]
@BrodaNoel I was having the same error on an old phone. I also noticed something similar with another library (react-native-image-resizer), it was throwing the following error: "Unable to resize image. Most likely due to not enough memory". So I did what they suggested in this github issue:
https://github.com/bamlab/react-native-image-resizer/issues/235

After adding android:largeHeap="true" to my AndroidManifest.xml, both react-native-image-resizer and expo-image-manipulator started working again. It's worth noting that my project is bare expo, not managed. I don't know if expo users have access to the AndroidManifest, you may need to do something else in your case.

**Comment by Abdulmateenchitrali** [comment]
This error occur for me "An error occurred while printing Error: Could not get encoded bitmap of assets_images_certifcatebanner"

**Comment by galih9** [comment]
please mark this as open, because the issue still exist
