### ISSUE TITLE
Crash when running expo on an ios <14.0 simulator with apple M1 chip.

### ISSUE THREAD

**Issue by gyl89** [expo/expo#12188]
### Summary

When opening my project (which works correctly on real device) on an ios simulator (< 14.0), it crashes. More precisely, I see expo splash screen for one second before it kills the process. If I then try to open the expo go app, I end up with the same process : splash screen for one second and crash.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

 Expo CLI 4.0.15 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - /opt/local/bin/node
      Yarn: 1.22.10 - /opt/local/bin/yarn
      npm: 7.0.15 - /usr/local/bin/npm
      Watchman: 4.9.0 - /opt/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.18 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Open an ios simulator with the proper version with the M1 chip computer.  Then either
2.1. Open any expo project on this simulator.
2.2. Try to open the expo app

Device logs are:

> Jan 14 11:43:19 MacBook-Pro-de-Gilles com.apple.CoreSimulator.SimDevice.6D290037-CCB6-46A9-9590-C47D7B34D98E[2020] (UIKitApplication:host.exp.Exponent[e203][rb-legacy][2287]): Service exited due to SIGILL | sent by exc handler[2287]

I contacted Apple support. They told me it's an expo issue. I'm not sure about it though since other apps (Safari for instance) seem to also crash in the simulator.

**Comment by brentvatne** [comment]
given that safari crashes i would suspect that apple support is mistaken. given limited time on our side and limited impact/control over the outcome here, we're not going to investigate this, you should use ios 14+ on m1 if older simulators cause problems for other apps :)
