### ISSUE TITLE
expo-ads-admob doesn't show advertisements in iOS devices only 

### ISSUE THREAD

**Issue by ornakash** [expo/expo#12186]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by ornakash** [comment]
I must add that this happens only with a physical device and after I uploaded my application to the AppStore. In Android, everything works perfectly. Also in Expo simulator it shows the ads. The problem is only with physical devices and only when the application is installed on the device.

**Comment by brentvatne** [comment]
please discuss on https://forums.expo.io if you can't fill out a bug report template here
