### ISSUE TITLE
A returned address by Location.reverseGeocodeAsync lacks some fields

### ISSUE THREAD

**Issue by aruneko** [expo/expo#12187]
### Summary

A returned address by `Location.reverseGeocodeAsync` lacks some required fields for an address in Japan.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 15.11.0 - /var/folders/1y/l347vl3x7szbd93vm9fb6q6w0000gn/T/yarn--1615450234418-0.4526026348325587/node
      Yarn: 1.22.10 - /var/folders/1y/l347vl3x7szbd93vm9fb6q6w0000gn/T/yarn--1615450234418-0.4526026348325587/yarn
      npm: 7.6.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

When you call `Location.reverseGeocodeAsync()` method like below, you can get the result.

```typescript
const coordinate = { latitude: 34.7275805, longitude: 135.2723769 }
const results = await Location.reverseGeocodeAsync(coordinate)
```

on iOS

```
Array [
  Object {
    "city": "神戸市東灘区",
    "country": "日本",
    "district": "田中町",
    "isoCountryCode": "JP",
    "name": "田中町1丁目7-22",
    "postalCode": "658-0081",
    "region": "兵庫県",
    "street": "田中町1丁目",
    "subregion": null,
    "timezone": "Asia/Tokyo",
  },
]
```

on Android
```
Array [
  Object {
    "city": "神戸市",
    "country": "日本",
    "district": "東灘区",
    "isoCountryCode": "JP",
    "name": "２２",
    "postalCode": "658-0081",
    "region": "兵庫県",
    "street": "１丁目",
    "subregion": null,
    "timezone": null,
  },
]
```

The actual address of the point is `兵庫県 / 神戸市 / 東灘区 / 田中町 / 1丁目 / 7-22`, but the result on Android lacks `田中町` and `7`.

I think `getPremises()` and `getSubThoroughfare()` method in [Address](https://developer.android.com/reference/android/location/Address) object in Android API return those lacking attributes. So I propose add those fields as `premises` and `subStreet` in address object in the return value of `Location.reverseGeocodeAsync` method.

Fortunately, `CLPlacemark` object on iOS has `subThoroughfare` attribute. Therefore I think we can map those attributes between iOS and Android.

**Comment by chrisdrackett** [comment]
I'm running into this as well. Without `subThoroughfare` on iOS the street number is often impossible to get, making the address much less useful.

**Comment by aruneko** [comment]
@chrisdrackett  Oh, it sounds great! 

But I have a concern. Basically, Japanese addresses are defined by not streets but blocks. For example, `田中町1丁目` means [this block (Link to Google Map)](https://www.google.com/maps/place/%E3%80%92658-0081+%E5%85%B5%E5%BA%AB%E7%9C%8C%E7%A5%9E%E6%88%B8%E5%B8%82%E6%9D%B1%E7%81%98%E5%8C%BA%E7%94%B0%E4%B8%AD%E7%94%BA%EF%BC%91%E4%B8%81%E7%9B%AE/@34.7249076,135.2747797,17z/data=!3m1!4b1!4m5!3m4!1s0x60008ce19fd1995b:0x6d935c008a5c6d84!8m2!3d34.725165!4d135.2768063).

For many countries that addresses are defined by streets, `subThoroughfare` is not so important. But in Japan, `subThoroughfare` is quite important since it means house level block number in an address.

Therefore, I and many of Japanese developer will be happy if you add the `subThoroughfare` field in modified API.
