### ISSUE TITLE
android opened notification icon

### ISSUE THREAD

**Issue by mairasala** [expo/expo#12196]
### Summary

In android, in the opened native notification, I don't see my icon but a grey square instead.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 23.0.1, 23.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3, 30.0.1
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

{
  "expo": {
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.5",
    "orientation": "default",
    "primaryColor": "#cccccc",
    "icon": "./assets/images/app_icon.png",
    "notification": {
      "color": "#cccccc",
      "icon": "./assets/images/notification_icon.png",
      "iosDisplayInForeground": true
    },
    "packagerOpts": {
    },
    "ios": {
      "supportsTablet": true,
      "requireFullScreen": true
    },
    "android": {
      "permissions": [
        "VIBRATE"
      ],
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/app_icon.png",
        "backgroundColor": "#d96235"
      },
      "useNextNotificationsApi": true
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "splash": {
      "image": "./assets/images/dispersao_splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#000000"
    },
    "assetBundlePatterns": [
      "./assets/*"
    ]
  }
}

Hello,
I have created an apk and installed it in my phone with the following app.json:

```
"notification": {
      "color": "#cccccc",
      "icon": "./assets/images/notification_icon.png",
      "iosDisplayInForeground": true
    },
    ...
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/app_icon.png",
        "backgroundColor": "#d96235"
      },
  }
```

Following [this issue comments](https://github.com/expo/expo/issues/11940).
When I receive a notification I see the assigned icon in the top of the phone. However in the opened notification drawer, the notification displays a grey square. Shouldn't it be the same icon?

**Comment by cruzach** [comment]
This common issue is addressed in the push notifications FAQ- https://docs.expo.io/push-notifications/faq/#my-notification-icon-on-android-is-a
