### ISSUE TITLE
Scheduled notification to update badge appears with the text of the last notification

### ISSUE THREAD

**Issue by yolpsoftware** [expo/expo#12211]
### Summary

We use `Notifications.scheduleNotificationAsync` both to display notifications, as well as to periodically update the badge count. In the second case, we don't provide any notification text, we just update the badge count:

```
Notifications.scheduleNotificationAsync({
  content: {
    badge: 23,
  },
  trigger: date.getTime(),
});
```

This indeed updates the app badge count, but it also displays a notification. The text used is the one of the last notification.

Note that this is not about push notifications, but about local, scheduled notifications.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.0 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/opt/nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.6.2 - /usr/local/opt/nvm/versions/node/v14.15.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.1.0 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.3.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Schedule one notification, and then schedule a second one:

```
Notifications.scheduleNotificationAsync({
  content: {
    title: 'Foo bar',
    body: 'body',
  },
  trigger: date1.getTime(),
});
Notifications.scheduleNotificationAsync({
  content: {
    badge: 23,
  },
  trigger: date2.getTime(),
});
```

Actual behavior: The second notification appears with the text of the first one.
Expected behavior: The second one should not appear as a notification, it should only update the badge count.

**Comment by cruzach** [comment]
If you want to update the badge number, why not use [`setBadgeCountAsync`](https://docs.expo.io/versions/latest/sdk/notifications/#setbadgecountasyncbadgecount-number-options-setbadgecountoptions-promiseboolean)?

Tested on iOS in this snack and couldn't reproduce- https://snack.expo.io/@charliecruzan/12211. If you provide a snack that reproduces the issue, I'm happy to reopen and investigate
