### ISSUE TITLE
Custom mode_modules path not working

### ISSUE THREAD

**Issue by harshal2030** [expo/expo#12215]
### Summary

I'm currently converting my project to monorepo, I've updated my node_modules path too. But gradle.groovy in react-native-unimodules always throws an error.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.1.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Harshal\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

In my settings.gradle
apply from: '../../../node_modules/react-native-unimodules/gradle.groovy'; includeUnimodulesProjects([modulesPaths: ['../../../node_modules']])

In my app/build.gradle
addUnimodulesDependencies([exclude: ['expo-image-loader', 'expo-permissions', 'expo-constants', 'expo-file-system'], modulesPaths: ['../../../../node_modules']])

I'm currently converting my project to monorepo, I've updated my node_modules path too. But gradle.groovy in react-native-unimodules always throws an error.
```
* Where:
Script 'C:\Users\Harshal\Desktop\EasyTeach\node_modules\react-native-unimodules\gradle.groovy' line: 129

* What went wrong:
A problem occurred evaluating settings 'EasyTeach'.
> C:\Users\Harshal\Desktop\EasyTeach\packages\node_modules does not exist.
```

My current directory looks like this:
![issue](https://user-images.githubusercontent.com/43959510/111183511-f92df900-85d5-11eb-9718-74423ed79317.JPG)

**Comment by brentvatne** [comment]
> * What went wrong:
>A problem occurred evaluating settings 'EasyTeach'.
> > C:\Users\Harshal\Desktop\EasyTeach\packages\node_modules does not exist.

you probably meant to point it to `C:\Users\Harshal\Desktop\EasyTeach\node_modules`? so add another .. to the path

**Comment by harshal2030** [comment]
I think it is pointing correctly to the node_modules, one more .. will take me out of my root directory
