### ISSUE TITLE
exp publish with teams

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#1221]
Hey guys, my brother & I are both working on an expo project and we both want to publish. It seems as though when we run `exp publish` it publishes to two separate apps. 

Can `exp publish` for the same app be run by multiple people?

**Comment by jesseruder** [comment]
Hi @lightninglu10 if you `exp login` with the same credentials it will publish to the same app. Does that work for you?

**Comment by lightninglu10** [comment]
Yikes, that's the only way to do it? For the short term it does, but I foresee other people working on this app and only one account having the ability to publish is really annoying.

**Comment by jimmylee** [comment]
Hi @lightninglu10, I totally agree! I'm really sorry about this.

Unfortunately it is the best solution we have today. Our small team is working hard to make sure that we have a better solution in the future, but thats all I can promise. 😞 

If you would like, you could check out our [Canny](https://expo.canny.io/) where people make feature requests. As a team, we frequently look at this and try our best to prioritize. 

I'm going to close this issue for now, let us know if you have any other questions!

**Comment by joelbowen** [comment]
I thumbed down but I totally understand you're a small team with lots of competing priorities, however I'd like to put my vote on this feature to be prioritized in your roadmap.

**Comment by brooksbecton** [comment]
On point A4 of the terms of service, it says 

> Your login may only be used by one person - a single login shared by multiple people is not permitted.

https://expo.io/terms

I wouldn't want to break the terms if possible. 
Do ya'll still think this is ok?

**Comment by brooksbecton** [comment]
I've just received an email about a "Going Pro" paid service that Expo is doing. 
It specifically talks about allowing collaboration on Expo projects. 

You can see it under your Account -> Services
