### ISSUE TITLE
react-native-unimodules with rare react native project. Build success, archive failed. 

### ISSUE THREAD

**Issue by caifu92** [expo/expo#12225]
### Summary

I need to use expo in rare react native project so installed react-native-unimodules.
When I build the project and run on simulator, all things working fine. But when I try to archive the project for uploading to testflight, getting the error.
'Library not found -IDoubleConversion'

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

I haven`t used expo cli.
Just trying to install react-native-unimodules and getting error.

### Reproducible demo or steps to reproduce from a blank project

1. create a new react native project
react-native init
2. install react-native-unimodules
follow this guide. https://docs.expo.io/bare/installing-unimodules/
3. run `react-natvie run-ios` on simulator which will success
4. achieve the project to upload testflight. This failed with `Library not found: -IDoubleConversion`

I followed react-native-unimodules installation guide exactly. Have no idea how to solve this.

    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-unimodules": "^0.12.0",

- AppDelegate.h
![image](https://user-images.githubusercontent.com/66729340/111183309-b9bdd780-85ea-11eb-87d4-9f3e7e6e569d.png)

- AppDelegate.m
![image](https://user-images.githubusercontent.com/66729340/111183520-f12c8400-85ea-11eb-9dac-cec9b0d0e5c0.png)
![image](https://user-images.githubusercontent.com/66729340/111183561-fe497300-85ea-11eb-84cf-59656c79a8e3.png)

- Podfile
![image](https://user-images.githubusercontent.com/66729340/111183633-14573380-85eb-11eb-9ec5-3bf56f8cb594.png)
![image](https://user-images.githubusercontent.com/66729340/111183685-233de600-85eb-11eb-8cff-f5a112c56fc5.png)

Please help me.

**Comment by brentvatne** [comment]
make sure you run your project from the xcworkspace. if that doesn't help, share a reproducible example that demonstrates this is related to expo code, thanks!

**Comment by g4laura** [comment]
I'm having a similar problem except I'm getting 'React/RCTBridgeDelegate.h' file not found when I try to archive

**Comment by BooYeu** [comment]
@brentvatne I have same problem

**Comment by vrgimael** [comment]
This is an actual issue while following the tutorial here https://docs.expo.io/bare/installing-unimodules with RN 0.64.2.

Solved it by messing around with imports - mine was just missing `#import <React/RCTBridgeDelegate.h>` but it seems others had different results here
