### ISSUE TITLE
ImagePicker produces invalid URI that causes Error in VideoThumbnails

### ISSUE THREAD

**Issue by ianmelendez95** [expo/expo#12220]
### Summary

The URI produced by ImagePicker on Android SM-G975U seems to be missing forward slashes '/' after file: prefix. (e.g. "file:/path/to/file" instead of "file:///path/to/file") This causes an error when passed to VideoThumbnails.

WORKAROUND: Could programatically introduce the missing forward slashes, or otherwise use FileSystem.getInfoAsync, which seems to handle the uri correctly and returns a well-formatted uri that can then be passed to VideoThumbnails.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

v40.0.0

### Environment

Expo CLI 4.3.0 environment info:
    System:
      OS: Linux 5.10 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
      npm: 7.6.1 - ~/.nvm/versions/node/v14.6.0/bin/npm
      Watchman: 20200726.234435.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Intel x86 Atom_64
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Snack link, where it logs an error when VideoThumbnails fails due to uri, then when the uri as checked by FileSystem is different, and finally when it succeeds when using the uri produced by FileSystem.
https://snack.expo.io/@imelendez/75a10a

**Comment by AdamJNavarro** [comment]
Hey @ianmelendez95, thanks for taking the time to create a detailed bug report! Fortunately this bug was already reported and a [PR](https://github.com/expo/expo/commit/ea252b1aa8d50e1b994447b5616a5d4c3abd25e6) has been merged with the fix. The fix will be rolled out with SDK41. As you mention, in the interim you can do some string transformation logic if this is a blocker for you.

Cheers,
Adam
