### ISSUE TITLE
Code works fine on Expo App but Standalone app Android build gives Error 

### ISSUE THREAD

**Issue by Rumidom** [expo/expo#1222]
hi, i'm new to expo and this is my first app, i have searched around but could't find anything on this. My code work fine on the expo app (even when using exp start --no-dev) but when i build it for android it first shows the splash screen with the wrong size (i'm using resize mode 'contain')  and then it gives me a error: 
**Uncaught Error: TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')**
![screenshot_2018-01-06-10-34-55](https://user-images.githubusercontent.com/1103035/34640631-84f71ec4-f2dd-11e7-862a-7332d03d8038.png)
![screenshot_2018-01-06-10-35-02](https://user-images.githubusercontent.com/1103035/34640632-85142fbe-f2dd-11e7-8d19-73e39609385c.png)

**Comment by Rumidom** [comment]
i found another issue with the same problem here : https://github.com/facebook/react-native/issues/17348

**Comment by khomyakov42** [comment]
https://github.com/facebook/react-native/issues/17348
