### ISSUE TITLE
[Expo-Web] Camera not mounting properly on Samsung devices

### ISSUE THREAD

**Issue by AWinterFox** [expo/expo#12227]
### Summary

On newer Samsung models, the expo-camera component for expo-web is not working. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

4.3.0

### Environment

  Expo CLI 4.3.0 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Users\Fox\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3, 29.0.2
        System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1). Create a project with expo-camera and run it on a newer Android devices browser
2.) Go to https://quirky-wing-505041.netlify.app/ on a newer Android devices browser

This is Evan Bacon's own website utilizing expo-camera in Expo-Web:
https://github.com/expo/expo/pull/4166#issue-277215962

This has occurred on Google Chrome and the default Samsung browser on the following devices:
Samsung Galaxy S20
Samsung Galaxy S21
Samsung Galaxy A71

I'm sure this will occur on any of the newer Samsung devices, but I am inhibited from checking due to me not owning the devices. On a side note, this does work on the Samsung Galaxy A20

**Comment by Durotemy** [comment]
The expo camera work on android and ios but fails on samsumg
