### ISSUE TITLE
[expo-notifications] The `addNotificationResponseReceivedListener` is not triggered when the app is killed.

### ISSUE THREAD

**Issue by samuelpismel** [expo/expo#12228]
### Summary

**!!! This only happens in the builds installations, it not happen in the Expo Go. This is an after build bug. !!!**

Expected behavior:
When we click on an notification the addNotificationResponseReceivedListener should be triggered.

Current behavior: 
The addNotificationResponseReceivedListener is not triggered and it is triggered if we reload the app.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.0 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I've made an repository with an reproducible demo:
https://github.com/samuelpismel/expo-notifications-interaction-bug

**It will be necessary build the android project to reproduce, it does not occur in the Expo Go, it only happen in the built version.**

The steps are in the README, but I'll put here too:

1. Create a build and install it in your phone via `adb install`
2. Click on Send Notification button
3. Close the app and remove it from memory
4. Click on the notification to open the app
5. The response data should have appeared but it will not
6. If you click in the reload button the response data will appear

Screenshot of the App:

![Debug App Image](https://github.com/samuelpismel/expo-notifications-interaction-bug/blob/master/assets/expo-notification-app-debug.png?raw=true)

**Comment by cruzach** [comment]
This issue was fixed for SDK 41, and is available now to bare workflow users in `expo-notifications@0.11.0`

SDK 41 beta will be coming out soon for you to try out 😄

**Comment by superyarik** [comment]
is SDK39 affected by this issue? looks like in SDK39 addNotificationResponseReceivedListener not working on android, but workin in ios

**Comment by superyarik** [comment]
@cruzach  if SDK39 is supported for now, is rebuild apps(SDK39) will fix this notification problems?

**Comment by cruzach** [comment]
No- you should upgrade to SDK 41 for the fix

**Comment by abourtnik** [comment]
Hello, I migrate to Expo SDK 41, build an APK and test it on my device but the addNotificationResponseReceivedListener() method is only called when my app is on foreground. When I killed my app and click on the notification the method is not  triggered.
