### ISSUE TITLE
Using Three Fingers on Expo App causes to throw console.error

### ISSUE THREAD

**Issue by kaungmyatlwin** [expo/expo#1223]
Hello, I'm using Expo with `create-react-native-app` cli. I touched the device (One Plus 5, Android 7.1.1 ) with three fingers (swipe down) to screenshot and this error came up.

![image](https://user-images.githubusercontent.com/11173080/34652566-9950c06e-f40e-11e7-9bcf-2dcba8a067ae.png)

Is this a necessary error to show? It just doesn't happen when I try to screenshot by swipe down but also whenever I touch it with three fingers.

P.S: Expo is an awesome product.

**Comment by jimmylee** [comment]
Hey @kaungmyatlwin ! Nice to meet you and I'm really glad you're enjoying using Expo. 🎊 

To help you out further, I would love to see a code example so I can have a better understanding of whats going on? Have you attempted to address the error message `Cannot record touch end without a touch start"?

**Comment by kaungmyatlwin** [comment]
Hello. Sorry for late reply. Here is how you could reproduce this bug without any code, because it also happens on bare template.

Steps to Repro:

1. Create a React Native App using `create-react-native-app` CLI.
2. Start the project and use Expo to import.
3. Touch with 3 fingers (or) perform a gesture with more than 3 fingers.

The error will persist there.

**Comment by brentvatne** [comment]
this is a known issue with react-native upstream :( https://github.com/facebook/react-native/issues/15059

**Comment by brentvatne** [comment]
(it only happens on certain devices as listed in that issue)
