### ISSUE TITLE
`ExpoWebGLRenderingContext` fails to return accurate GL Extensions information

### ISSUE THREAD

**Issue by wilson0x4d** [expo/expo#12231]
### Summary

We expect a call to `ExpoWebGLRenderingContext::getSupportedExtensions` to return a valid array containing all extensions supported by the underlying system. This is critical for the proper implementation of GL-based applications which need to perform efficient postprocessing, use advanced methods for resource management, and use of certain shading language features.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
  Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      react: ^16.14.0 => 16.14.0
      react-native: ^0.63.4 => 0.63.4
      react-native-web: ^0.13.18 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

using `GLView` to acquire an `ExpoWebGLRenderingContext`, then call:

```typescript
    console.warn(glcontext.getSupportedExtensions());
```

See also:
    https://github.com/expo/expo-three/issues/194

I could be mistaken, but the root cause for this behavior seems to be the expo-gl-cpp implementation being written to return an empty array and a nullptr for these two calls:

```cpp
NATIVE_METHOD(getSupportedExtensions) {
  return jsi::Array(runtime, 0);
}

NATIVE_METHOD(getExtension) {
  return nullptr;
}
```
Excerpt is from expo-gl-cpp:
https://github.com/expo/expo/blob/fa078bd395861307e70ec0622e4e7e37e038b8e9/packages/expo-gl-cpp/cpp/EXGLNativeMethods.cpp#L1565-L1574

I'm not familiar enough with the expo-gl-cpp codebase to debug nor modify without guidance from a contributor. Any help in resolving this issue is greatly appreciated, it is affecting the behavior of upstream projects (THREE) as well as our own code.

Thanks.

**Comment by wilson0x4d** [comment]
After digging around the repo a bit, trying to get packages to build, it seem as though Xcode is required to build packages like `expo-gl-cpp`. I could be wrong, if so hopefully someone can explain how to build on windows, under mingw, or under debian/ubuntu.

If someone is able to build and test, I believe the following code is (approximately) what is needed for `getSupportedExtensions` to return a valuable result. Again, I can't build and test, and not familiar with any of the codebase, so I'm not 100% sure:

```cpp
// Extensions
// ----------
!@#
NATIVE_METHOD(getSupportedExtensions) {
  std::vector<const GLubyte *> extensionNames;
  GLint numExtensions = 0;
  addBlockingToNextBatch([&] {
    glGetIntegerv(GL_NUM_EXTENSIONS, &numExtensions);
    extensionNames.reserve(numExtensions);
    for (auto i = 0; i < numExtensions; i++) {
      auto glStr = glGetStringi(GL_EXTENSIONS, i);
      extensionNames.push(glStr);
    }
  });
  jsi::Array array(runtime, numExtensions);
  for (auto i = 0; i < numExtensions; i++) {
    auto extensionName = jsi::String::createFromUtf8(
      runtime, std::string(reinterpret_cast<const char *>(extensionNames[i])));
    array.setValueAtIndex(runtime, i++, extensionName);
  }
  return array;
}
```

I am not sure if the following two entries should be added to EXGLConstants.def, but noticed the constants were missing:

```cpp
GL_CONSTANT(EXTENSIONS) /* 17403 */
GL_CONSTANT(NUM_EXTENSIONS) /* 33309 */
```

I'd love to compile, test, and submit a PR myself but I don't see any way to validate the work without access to an osx machine. Hopefully someone with a working environment can pick this up and run with it.  If it helps I can also take a stab at implementing `getExtension` ... but still have no way of testing the code.

Thanks.

**Comment by tsapeta** [comment]
Hi @wilson0x4d! Thanks for the detailed description and the code you provided 🙏 I'll try using your implementation in a few days, but I think it won't work.

As you noticed, we don't support OpenGL ES extensions right now — they are kinda different than these that are available in WebGL and since we want expo-gl to be compliant with WebGL spec, it may require more work to map their functionality properly. Anyway I agree that it would be a nice feature to have.

I think you don't need to have macOS to test and build it as the C++ code is shared between iOS and Android, so it should be fine if you manage to try it only on Android.

In terms of the constants — they are a good example of OpenGL ES and WebGL differences — they don't exist in WebGL so there is no need to add them to `EXGLConstants.def`.

Let me know if you encounter any issues with testing it on Android!

**Comment by wilson0x4d** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getSupportedExtensions 

In Chrome or equivalent if we open a dev console, we can pull the extension list easily:

```javascript
document.body.appendChild(document.createElement('canvas')).getContext('webgl').getSupportedExtensions();
```

Gives me:

```json
[   "ANGLE_instanced_arrays",
    "EXT_blend_minmax",
    "EXT_color_buffer_half_float",
    "EXT_disjoint_timer_query",
    "EXT_float_blend",
    "EXT_frag_depth",
    "EXT_shader_texture_lod",
    "EXT_texture_compression_rgtc",
    "EXT_texture_filter_anisotropic",
    "WEBKIT_EXT_texture_filter_anisotropic",
    "EXT_sRGB",
    "OES_element_index_uint",
    "OES_fbo_render_mipmap",
    "OES_standard_derivatives",
    "OES_texture_float",
    "OES_texture_float_linear",
    "OES_texture_half_float",
    "OES_texture_half_float_linear",
    "OES_vertex_array_object",
    "WEBGL_color_buffer_float",
    "WEBGL_compressed_texture_s3tc",
    "WEBKIT_WEBGL_compressed_texture_s3tc",
    "WEBGL_compressed_texture_s3tc_srgb",
    "WEBGL_debug_renderer_info",
    "WEBGL_debug_shaders",
    "WEBGL_depth_texture",
    "WEBKIT_WEBGL_depth_texture",
    "WEBGL_draw_buffers",
    "WEBGL_lose_context",
    "WEBKIT_WEBGL_lose_context",
    "WEBGL_multi_draw"]
```

Obviously I'm not expecting all extensions to be valid over all devices, but for the case of knowing which texture compression methods are supported by the GPU on this particular device I can see that `WEBGL_compressioned_texture_s3tc_srgb` and `EXT_texture_compression_rgtc` are available. with this information and by leveraging basisu on the server-side I can deliver transcoded textures that the device can decode. this is my primary goal. I am not expecting to acquire a JS thunk/wrapper into GL extensions (although that would be a "nice to have!")

Perhaps I'm misunderstanding something about how Expo wraps/delegates to GL and the underlying hardware, I assume it would be like any other GL implementation and the hardware is the arbiter of what can/cannot be done (not the wrapper/Expo.)

I'll setup a macOS build env this weekend.

**Comment by tsapeta** [comment]
The biggest "problem" is that WebGL extensions are not equal to OpenGL ES extensions. For example, with your code, on iOS simulator I'm getting such array of supported extensions:
```
[
  "GL_OES_standard_derivatives",
  "GL_EXT_color_buffer_half_float",
  "GL_EXT_debug_label",
  "GL_EXT_debug_marker",
  "GL_EXT_pvrtc_sRGB",
  "GL_EXT_read_format_bgra",
  "GL_EXT_separate_shader_objects",
  "GL_EXT_shader_framebuffer_fetch",
  "GL_EXT_shader_texture_lod",
  "GL_EXT_shadow_samplers",
  "GL_EXT_texture_filter_anisotropic",
  "GL_APPLE_clip_distance",
  "GL_APPLE_color_buffer_packed_float",
  "GL_APPLE_copy_texture_levels",
  "GL_APPLE_rgb_422",
  "GL_APPLE_texture_format_BGRA8888",
  "GL_IMG_read_format",
  "GL_IMG_texture_compression_pvrtc",
]
```
As you can see some of them are also available in WebGL specification, but some of them are not. Also, some of WebGL extensions can be already available by default (need to figure out which ones). This generally requires more research but I think there is no simple implementation for this and we will end up implementing each one separately. I quickly made a PR to show you how the implementation could look like: #12309
