### ISSUE TITLE
Upgrade Google Play Billing dependency to V3

### ISSUE THREAD

**Issue by cruzach** [expo/expo#12238]
### Summary

"We've detected that this app is using an old version of Google Play Billing. **By November 1, 2021, all app updates must use Billing Library version 3 or newer**. Update to Billing Library 3 before this date. Learn More about Billing Library 3."

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

This applies to the `expo-in-app-purchases` library

### Reproducible demo or steps to reproduce from a blank project

n/a

**Comment by krvajal** [comment]
Is it fixed for you?
