### ISSUE TITLE
Does Expo document picker affects behavior of KeyboardAvoidingView?

### ISSUE THREAD

**Issue by Infrus** [expo/expo#12232]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by Infrus** [comment]
I am having problems with expo document picker and input wrapped in the RN KeyboardAvoidingView.
If I don't use document picker, everything works as intended, the screen with input moves from the view as keyboard is open.
But if I use document picker and open input again the layout gets resized to fit space between keyboard and top of the screen.
The view is not pushed but resized, which breaks the layout.
It happens only after use of document picker.

**Comment by brentvatne** [comment]
https://forums.expo.io is better suited for such questions
