### ISSUE TITLE
Android app crashes when user denies permissions

### ISSUE THREAD

**Issue by ShaneMcNamara** [expo/expo#12248]
### Summary

My application requires 'ACCESS_FINE_LOCATION' and 'CAMERA', permissions. When the user denies the location permissions the Android app crashes.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.1

### Environment

Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.3 - /Users/ShaneMcNamara/.rvm/gems/ruby-2.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/ShaneMcNamara/android-permissions-crash

When a user denies both location and camera perms, the app crashes. iOS handles this case correctly. Both permissions are in my `app.config.js` 

Through testing, it appears that when the user denies location permissions, the app is not able to present camera permissions and crashes. Here's some test cases I've run and the results:

1. Open app and accept both permissions. App works fine.
2. Open app and accept location permissions. App will show camera permissions request. Deny camera permissions. App works fine.
3. Open app and deny location permissions. App crashes. 
4. Go into the Android app settings and manually enable Camera permissions. Open app and deny location permissions. App works fine.

This also happens in the Expo Go app.

After further testing, I believe this is caused by [requesting permissions at the same time](https://github.com/expo/expo/issues/1848).

**Comment by ShaneMcNamara** [comment]
@esamelson - I noticed you mentioned [here](https://github.com/expo/expo/issues/1848) that the issue was fixed internally. I'm still seeing this crash on my app, is this expected or a regression?

I would also suggest updating the documentation for [expo-permissions](https://docs.expo.io/versions/latest/sdk/permissions) and any other libraries that can ask for permissions (e.g. [expo-camera](https://docs.expo.io/versions/latest/sdk/camera/#requestpermissionsasync))

**Comment by brentvatne** [comment]
the example app you provided is strangely complicated, you can test your theory much more simply (it doesn't crash here): https://snack.expo.io/@brents/carefree-candy

i suspect the crash you are seeing is related to your own app code, but if you can make a more simple app like the above that reproduces then we can investigate further

**Comment by ShaneMcNamara** [comment]
@brentvatne  - I've updated the repro code to be even simpler. Your code does not crash, but moving the second permission request to another component does crash.

**Comment by brentvatne** [comment]
thanks! i updated my example to do something similar: https://snack.expo.io/@brents/carefree-candy

**Comment by lukmccall** [comment]
@brentvatne, I've managed to fix that, but I'm not happy with the result. The main reason why this is not working properly is the inner implementation of RN. It overrides the permission listener on every request. So if you ask, for example, for camera permission and before getting a response, you requested other permission, the react native will forget about your first request.  

Maybe we should disallow asking for another permission without awaiting the previous call?
