### ISSUE TITLE
Do we need access_background_location permission if using foreground service?

### ISSUE THREAD

**Issue by devashishsethia** [expo/expo#12242]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by devashishsethia** [comment]
Quoting from android docs:

> The system considers your app to be using foreground location if a feature of your app accesses the device's current location in one of the following situations:
> 
> An activity that belongs to your app is visible.
> Your app is running a foreground service. When a foreground service is running, the system raises user awareness by showing a persistent notification. Your app retains access when it's placed in the background, such as when the user presses the Home button on their device or turns their device's display off.
> 
> Additionally, it's recommended that you declare a foreground service type of location, as shown in the following code snippet. On Android 10 (API level 29) and higher, you must declare this foreground service type.
> 
>

**Comment by MaRaSu** [comment]
For anyone finding this closed issue, there is an answer to the question in issue #11854.
