### ISSUE TITLE
Status Bar Missing

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#1224]
Hey guys, weird because in the simulator the status bar is there in my app:

<img width="310" alt="screen shot 2018-01-07 at 4 36 00 pm" src="https://user-images.githubusercontent.com/2453737/34656073-33155b42-f3c9-11e7-8880-dd748fa69a6a.png">

But on the app in the app store, the status bar is not there:

![img_4290](https://user-images.githubusercontent.com/2453737/34656066-5a2ba3f0-f3d1-11e7-9443-19a426d5f3a1.PNG)

Any clues to what's up?

**Comment by jimmylee** [comment]
@lightninglu10 that seems really strange! Sorry you're encountering this issue.

I'm guessing your current issue is on Android? Can you verify? Also can you share some example code for how you have this configured? Thanks.

**Comment by lightninglu10** [comment]
So this is on iOS app store. 

In my code I didn't configure any status bar, but I have a header with a higher zIndex that contains the white bar with Codepress in it:

```
<View style={styles.topBar}>
        <View style={styles.questionProgress}>
          {this.props.router.location.pathname.includes(routes.questions.prefix) || this.props.router.location.pathname === '/'
            ? <QuestionProgress questions={questions.activeSet.questions} activeIndex={questions.activeIndex} />
            : <Text style={styles.header}>CodePress</Text>
          }
        </View>
      </View>
```

```
const styles = StyleSheet.create({
  topBar: {
    display: 'flex',
    width: '100%',
    backgroundColor: '#fff',
    top: 0,
    height: 66,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
```

**Comment by esamelson** [comment]
Hey @lightninglu10 - have you tried setting `top: Expo.Constants.statusBarHeight` inside of `styles.topBar`?

See here for more detailed instructions about configuring the Status Bar: https://docs.expo.io/versions/latest/guides/configuring-statusbar.html#place-an-empty . You may also want to try using RN's `StatusBar` component.

Let us know if none of this works.

**Comment by lightninglu10** [comment]
@esamelson, no I haven't but it's weird that the status bar shows up in the simulator but not the app. 

I'll give what you suggest a go and see what happens.
