### ISSUE TITLE
[docs] App.json version doesn’t seem to update

### ISSUE THREAD

**Issue by jeromevs** [expo/expo#12247]
### Summary

I am trying to increment my app version, I have modified the number in app.json, but when I log the Constants.nativeAppVersion, I still get the previous number of version

### Link to the related docs page

https://docs.expo.io/versions/latest/sdk/constants/

**Comment by brentvatne** [comment]
not enough information here. my guess is that there is some kind of misunderstanding.

as per the description:

> The Info.plist value for CFBundleShortVersionString on iOS and the version name set by version in app.json on Android at the time the native app was built.

you need to rebuild the standalone app for this version to update. you cannot update it with an ota update.
