### ISSUE TITLE
Expose NotificationsEmitterModule.getLastNotificationResponseAsync so integration with react-navigation is possible once again.

### ISSUE THREAD

**Issue by vladev** [expo/expo#12254]
### Summary

Integration between `expo-notifications` and `react-navigation` has gotten clumsy due to unexposed API.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.0 environment info:
    System:
      OS: Linux 5.10 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.10.0 - /tmp/yarn--1616103213558-0.23622838655735223/node
      Yarn: 1.22.10 - /tmp/yarn--1616103213558-0.23622838655735223/yarn
      npm: 6.14.11 - /usr/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

See below ↓

The canonical way to integrate `react-navigation` and `expo-notifications` has been to use react-navigation's [subscribe method](https://reactnavigation.org/docs/deep-linking/#third-party-integrations) and expo-notifications' `Notifications.addNotificationResponseReceivedListener`. See link for a code example.

However, due to #9866, the recommended way to handle notifications now is the `Notifications.useLastNotificationResponse` hook. This makes integration hacky as one needs to reroute everything once more through the linking module (then react-navigation picks up the new `getInitialURL`). If we expose the underlying `NotificationsEmitterModule.getLastNotificationResponseAsync` that can be used in place of react-navigation's `getInitialURL` and a seamless integration with react-navigation can be achieved.

@satya164 might provide more details.

----
*Hack to get it working if someone stumbles on this issue:*
```
const lastNotificationResponse = Notifications.useLastNotificationResponse()
  useEffect(() => {
    console.log({ lastNotificationResponse })
    if (
      lastNotificationResponse &&
      lastNotificationResponse.notification.request.content.data.url &&
      lastNotificationResponse.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER
    ) {
      Linking.openURL(lastNotificationResponse.notification.request.content.data.url as string)
    }
  }, [lastNotificationResponse])
```

**Comment by cruzach** [comment]
`useLastNotificationResponse` uses `addNotificationResponseReceivedListener` behind the scenes, so I think for this use case you should just continue to use the latter. https://github.com/expo/expo/issues/9866 is fixed now in the bare workflow, and will be fixed in SDK 41 for managed workflow users

**Comment by cruzach** [comment]
fixed in https://github.com/expo/expo/commit/ed84cd87215e1ab7fa04fee0ba9759dab2eba291
