### ISSUE TITLE
ImagePicker.launchCameraAsync doesn't open the camera with the current os language

### ISSUE THREAD

**Issue by RealDeanZhao** [expo/expo#1225]
# Hi All,
**ImagePicker.launchCameraAsync** shows the camera in English, but my os language is Chinese.  So how can i make the default language to chinese?   **ImagePicker.launchImageLibraryAsync** works correctly.

# Env:
iOS 11,
EXPO SDK 24,

Thanks a lot.

**Comment by terribleben** [comment]
I think `launchImageLibraryAsync` just uses the built-in iOS system image picker dialog, in which case your use case may be blocked by this other issue we're tracking: https://github.com/expo/expo/issues/576

Probably your best bet in the short term would be to create your own custom image picker UI by using the [Camera](https://docs.expo.io/versions/latest/sdk/camera.html) and [ImageManipulator](https://docs.expo.io/versions/latest/sdk/imagemanipulator.html) APIs. This will be more work to create, but you would have complete control over how the interface looks.

**Comment by jimmylee** [comment]
If you're looking for some example code to get started with you could try taking a look at: https://github.com/react-community/react-native-image-picker Sourced from [Native Directory](https://native.directory/?search=image)

**Comment by RealDeanZhao** [comment]
@jimmylee I have read the doc of react-native-image-picker before and i found the options of EXPO ImagePicker is different from react-native-image-picker. 
I tried to set the title options but it didn't work. 
`{''cancelButtonTitle' : '取消'}`

So as @terribleben said, one option is to use **EXPO Camera** and the other is to use **standalone react-native-image-picker**.

I will try **EXPO Camera** first without the 'CRNA eject' things..

Thanks a lot.
