### ISSUE TITLE
Expo is asking a lot of authorisations by default

### ISSUE THREAD

**Issue by MedjahdiKaram** [expo/expo#12269]
### Summary

After building an app that needs onlly mobile data and GPS the app is asking for the authorisations bellow:
for agenda , camera and a lot of authorisations that i neved used in the code.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

production

### Reproducible demo or steps to reproduce from a blank project

build an app that require only mobile data and gps

After building an app that needs onlly mobile data and GPS the app is asking for the authorisations bellow:
for agenda , camera and a lot of authorisations that i neved used in the code.

**Comment by brentvatne** [comment]
https://docs.expo.io/distribution/app-stores/#android-permissions
