### ISSUE TITLE
audio.playAsync() doesn't work when the app is in the background, but if audio.playAsync() is called and THEN the app is moved to background, the audio DOES play correctly (On iPhone Xs | 14.3)

### ISSUE THREAD

**Issue by williamdespard** [expo/expo#12261]
### Summary

PLEASE NOTE: This bug ONLY reveals itself on a real iPhone with a standalone app, it will not be evident on an iOS simulator (for reasons unknown) or in the expoGo app (because expoGo doesn't support background audio)

We have an app that plays one audio track after another automatically. This is designed to also work when our app is in the background/phone is locked etc.

- Everything works as planned when the app is in the foreground. When a track is clicked, it plays, and when the track reaches the end, the next track is automatically played using audio.playAsync()
- If an audio track is played, and then the app is moved to the background, the audio track plays as expected. However, once the track in question reaches its end, the next track DOES NOT play until the app is opened again.

Our hypothesis as to why this was not working was that audio.playAsync() wasn't being executed in background mode for some reason, however, after testing, we've realized that audio.playAsync() IS being triggered, but it's just not working until the app is opened again, meaning this is a bug.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40.0.1

### Environment

Expo CLI 4.1.6 environment info:
  System:
   OS: macOS 11.2
   Shell: 3.2.57 - /bin/bash
  Binaries:
   Node: 15.8.0 - /usr/local/bin/node
   Yarn: 1.21.1 - ~/.yarn/bin/yarn
   npm: 7.5.0 - /usr/local/bin/npm
   Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
   CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
   iOS SDK:
    Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
   Android SDK:
    API Levels: 29
    Build Tools: 29.0.2, 30.0.3
    System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
  IDEs:
   Android Studio: 4.1 AI-201.8743.12.41.7042882
   Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
   expo: ^40.0.1 => 40.0.1 
   react: 16.13.1 => 16.13.1 
   react-dom: 16.13.1 => 16.13.1 
   react-native: ~0.63.4 => 0.63.4 
   react-native-web: ~0.13.12 => 0.13.18 
  npmGlobalPackages:
   expo-cli: 4.1.6
  Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

To reveal this bug, you must:

1. Follow the steps below to make the simple app
2. Run expo build:ios
3. Create an app in App Store Connect
4. Deliver the app using Transporter
5. Test the app using Test Flight on an iPhone (we were using an iPhone Xs running 14.3)

Steps to build the app:

Either clone the following repo we've made especially to demo this issue: https://github.com/Twnsquare/expo-av

OR

Follow these steps to create your own project to replicate the issue

1. Create a new project using 'expo init my-app'
2. Run the following in the terminal: 'expo install expo-av'
3. Add the following to the 'ios' object in app.json:

"bundleIdentifier": [whateverYourBundleIdIs],
"buildNumber": "1.1.1",
"infoPlist": {
    "UIBackgroundModes": ["audio"]
}

4. Replace App.js with the following:

```
import React, { useState, useEffect } from "react";
import { Text, View, StyleSheet, TouchableOpacity } from "react-native";
import Constants from "expo-constants";
import { Audio } from "expo-av";

export default function App() {
  // Tracks we have
  const audioUrls = [
    {
      name: "Track 1",
      uri:
        "https://townsquare-audio-app-staging.s3.eu-west-2.amazonaws.com/audio_files/posts/50/1616067568097audio_1616067567161.caf",
    },
    {
      name: "Track 2",
      uri:
        "https://townsquare-audio-app-staging.s3.eu-west-2.amazonaws.com/audio_files/posts/49/1615923245158audio_1615923239730.caf",
    },
    {
      name: "Track 3",
      uri:
        "https://townsquare-audio-app-staging.s3.eu-west-2.amazonaws.com/audio_files/posts/48/1615920401504audio_1615920393508.caf",
    },
    {
      name: "Track 4",
      uri:
        "https://townsquare-audio-app-staging.s3.eu-west-2.amazonaws.com/audio_files/posts/47/1615804844998audio_1615804833700.caf",
    },
  ];
  const [currentTrackIndex, setCurrentTrackIndex] = useState(0);
  const [currentSound, setCurrentSound] = useState(null);

  // Creates an "sound" instance for the current track and immediately plays iy
  const playTrack = async (trackIndex) => {
    const currentTrack = audioUrls[trackIndex];
    const { sound } = await Audio.Sound.createAsync(
      { uri: currentTrack.uri },
      undefined,
      null,
      false
    );

    setCurrentSound(sound);
    await sound.playAsync();
  };

  // When a track is finished this function runs
  const handlePlaybackStatusUpdate = (playbackObject) => {
    const { didJustFinish } = playbackObject;
    if (didJustFinish) handleOnTrackEnd();
  };

  // Determines the next function, if we are end of the audioUrls starts from 0, or just moves to the next track
  const handleOnTrackEnd = () => {
    const nextTrackIndex =
      currentTrackIndex === audioUrls.length - 1 ? 0 : currentTrackIndex + 1;
    setCurrentTrackIndex(nextTrackIndex);
    playTrack(nextTrackIndex);
  };

  useEffect(() => {
    if (currentSound) {
      currentSound.setOnPlaybackStatusUpdate(handlePlaybackStatusUpdate);
    }
  }, [currentTrackIndex, currentSound]);

  useEffect(() => {
    Audio.setAudioModeAsync({
      interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
      interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
      staysActiveInBackground: true,
      playsInSilentModeIOS: true,
    });
  }, []);

  return (
    <View style={styles.container}>
      <TouchableOpacity onPress={() => playTrack(0)}>
        <Text style={styles.paragraph}>Press to Play</Text>
      </TouchableOpacity>
      <Text style={styles.paragraph}>
        Current Track: {audioUrls[currentTrackIndex].name}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    paddingTop: Constants.statusBarHeight,
    backgroundColor: "#ecf0f1",
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
});
```

**Comment by williamdespard** [comment]
Hi @byCedric , any chance a member of the team could look into this anytime soon?

**Comment by williamdespard** [comment]
Hi @brentvatne I've been waiting on an answer for this for a little while now. Annoyingly, this is pretty mission-critical for us to solve this bug. Any chance you guys could have a look at it sometime soon?

**Comment by brentvatne** [comment]
we're not looking into this right now, if you'd like to do so it would be appreciated!

**Comment by eugenehp** [comment]
@williamdespard can you reproduce this bug when you eject the expo?

**Comment by williamdespard** [comment]
> @williamdespard can you reproduce this bug when you eject the expo?

@eugenehp It's a good question. I haven't tried, but one would assume the issue will remain as it will still us the underlying expo-av implementation...

**Comment by eugenehp** [comment]
@williamdespard most likely. My assumption is that ejection will let you intercept the calls during your debugging section in an easier way.

Also using flipper might be beneficial too.

You will most likely end up in building a temporary clone of `expo-av` module and debugging it step-by-step.

**Comment by williamdespard** [comment]
> @williamdespard most likely. My assumption is that ejection will let you intercept the calls during your debugging section in an easier way.
> 
> Also using flipper might be beneficial too.
> 
> You will most likely end up in building a temporary clone of `expo-av` module and debugging it step-by-step.

Very helpful @eugenehp, I have sent you an email to discuss further.

**Comment by ArGeoph** [comment]
Was wondering if there's any progress on fixing this bug? Our app's users are suffering from this bug on both Android.

@williamdespard Did your team find a workaround for this bug?

**Comment by williamdespard** [comment]
@ArGeoph Apologies for the slow reply. We actually moved away from React Native because we faced so many bugs relating to audio features.

**Comment by josema03** [comment]
> Was wondering if there's any progress on fixing this bug? Our app's users are suffering from this bug on both Android.
> 
> @williamdespard Did your team find a workaround for this bug?

Did you manage to find a solution? I'm currently facing the same problem. I'm unable to call `sound.playAsync()` successfully while the app is in background

**Comment by humbroll** [comment]
I'm still seeing the issue. Could someone share some hints if they had some chance to drill down?
