### ISSUE TITLE
Barcode scanner is missing permission requesters on web

### ISSUE THREAD

**Issue by byCedric** [expo/expo#12279]
### Summary

When using `BarCodeScanner.requestPermissionsAsync`, it fails on web due to [missing implementation on web](https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/src/ExpoBarCodeScannerModule.web.ts).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40

### Environment

<any>

### Reproducible demo or steps to reproduce from a blank project

- Use the [Snack example from the docs](https://docs.expo.io/versions/latest/sdk/bar-code-scanner/#usage)
- Open the web tab
- Open console of that web tab

You should see this error:
```
Uncaught (in promise) TypeError: b.default.requestPermissionsAsync is not a function
    at eval ((index):3)
```

Edit: Seems like this also applies to other packages, like Camera.

**Comment by SleeplessByte** [comment]
This seems to be true for all packages and also reproducible in SDK 41.

**Comment by ShuHighBridge** [comment]
The same error also seems to occur on SDK 39.0.2 : (

**Comment by SleeplessByte** [comment]
Might be resolved since https://github.com/expo/expo/pull/13109/files, but @byCedric probably wants to confirm

**Comment by SleeplessByte** [comment]
Previous comment is unresolved.

**Comment by SleeplessByte** [comment]
This is not stale.

**Comment by byCedric** [comment]
It's resolved: https://snack.expo.dev/@bycedric/61e773?platform=web
