### ISSUE TITLE
HTTP 300s Redirect support for Audio/Video URLs

### ISSUE THREAD

**Issue by SatoshiInoue** [expo/expo#1227]
I'd like to know if Expo AV player can support file/stream URLs that initially returns HTTP 300s as a redirect and then returns 200 for authentication/server-side caching purposes. I've tested an mp3 URL that returns 302 upon request and I was able to play it using playlist-example project of Expo, both on Android and iOS. But I just wanted to check here to know if there's an official support for this or not.

**Comment by sjchmiela** [comment]
Hello there!

Yes, we'd like to support not only direct URLs to files, but also URLs that redirect. 

This is quite easy on both platforms, however once [Android HLS support](https://github.com/expo/expo/issues/1187) lands there may be some extra configuration that one will have to provide to ensure Android decodes the file properly.

Just to be on the safe side, I'll add tests ensuring that A/V supports redirects. 🙂

**Comment by sjchmiela** [comment]
Hi @mikenz1000, that is a nasty bug! 😃

It looks like the player indeed does not follow redirections when the first response code is 302 (when the protocol is HTTPS, haven't checked HTTP).

For example setting `uri` to https://bit.ly/2yUKnVl makes the video play (and this shortened URL redirects with 301 to the URL you're using which then uses 302 to redirect to the file). Strange! 😲 

Could you please open a new issue about it? Feel free to assign it to me! 🙂

**Comment by mikenz1000** [comment]
Cool thanks, have done (https://github.com/expo/expo/issues/1935)
