### ISSUE TITLE
Logo not displayed on Push Notification Android

### ISSUE THREAD

**Issue by maurohmartinez** [expo/expo#12273]
### Summary

When receiving a push on Android devices, the logo of my application doesn't show up, instead, a black solid.
This issue seems to affect only devices running Android +10.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

{
    "expo": {
        [...]
        "icon": "./assets/icon.png",
        "notification": {
            "icon": "./assets/logo-for-push-new.png",
            "color": "#EF7D00",
            "iosDisplayInForeground": true,
            "androidMode": "default"
        },
        "android": {
            [...]
            "icon": "./assets/icon_andriod.png",
            "adaptiveIcon": {
                "backgroundColor": "#fff",
                "foregroundImage": "./assets/icon_andriod_adaptive.png"
            },
            "useNextNotificationsApi": true,
        }
    }
}

The code above contains the parts of my app.json file where there is info about the icon.

**Comment by cruzach** [comment]
What does your notification icon look like? Asking bc checking for this issue- https://docs.expo.io/push-notifications/faq/#my-notification-icon-on-android-is-a

**Comment by cruzach** [comment]
no problem 👍
