### ISSUE TITLE
Facebook SDK Version Not Up-to-Date

### ISSUE THREAD

**Issue by pROFESOR11** [expo/expo#12272]
### Summary

Although we're in the latest Expo SDK in the managed workflow, FB support stated that our Facebook SDK is too old to set up ads. We want to meet the minimum requirements to be able to make fb ads integration work.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.18.2 - ~/.config/nvm/12.18.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.config/nvm/12.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4.0.10 => 4.4.0
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@profesor/brave-truffles

Hi,
We want to track app events with facebook and set up facebook ads. We’re in the managed workflow, and use expo-facebook package.

```
// App.js
import * as Facebook from 'expo-facebook';
...
try {
      await Facebook.initializeAsync({
        appId: "<appId>",
        appName: "<appName>",
        autoLogAppEvents: true,
      })
      await Facebook.setAutoLogAppEventsEnabledAsync(true);
      await Facebook.setAdvertiserIDCollectionEnabledAsync(true);
      console.log("Facebook initialized successfully")
    } catch ({ message }) {
      console.log("facebook initialize error: ", message)
    }
```
```
// app.json
{
  "expo": {
  ...
  "facebookAppId": "<appId>",
   "facebookAutoLogAppEventsEnabled": true,
   "facebookScheme": "<fbScheme>",
  ...
  ```
  
We could be able to log the events in the FB Analytics. But when we try to set up facebook ads, we get an error “We haven’t received any standard app events from your app”, although we see many events in the dashboard. We’ve contacted with Facebook, and the problem is that the FB SDK that is used in our expo-facebook version is too old. We have also generated builds with expo-facebook@9.1.0 and expo-facebook@10.0.0 and expo-facebook@11.0.1.

![Screen Shot 2021-03-21 at 14 10 25](https://user-images.githubusercontent.com/26159043/111902994-138e2980-8a51-11eb-88d6-19c02ce37f10.png)

For every expo-facebook version we used, we still see the SDK version as 5.8.0 in the FB dashboard. Apparently, 5.8.0 is too old to set up facebook ads. We would like to get your help on how to set up facebook ads, or how to update Facebook SDK version within the managed workflow. We’ll be very pleased to hear if it’s not possible right now, but have any plans for the next Expo SDKs.

**Comment by brentvatne** [comment]
https://github.com/expo/expo/pull/11921

it will land in sdk 41

**Comment by pROFESOR11** [comment]
@brentvatne Thanks!

**Comment by pROFESOR11** [comment]
@brentvatne Hi Brent,
I've upgraded to SDK 41 beta, but can't see the events in the FB dashboard.
```
"expo": "^41.0.0-beta.2",
"expo-facebook": "~11.0.4",
```

I've gone through the documentation, but everything seems fine.
Are there any specific actions I need to do with the upgrade?

**Comment by brentvatne** [comment]
just follow https://docs.expo.io/versions/v41.0.0/sdk/facebook-ads/ and if everything seems fine then you might need to wait a bit for fb dashboard to update
