### ISSUE TITLE
[Ubuntu] Expo always do full reload

### ISSUE THREAD

**Issue by gunzino** [expo/expo#1228]
Hello,

I am new to Expo and React native. It was recommended to me by friend of mine some months ago. As I during his dev process, if he edited some file it immediately changed on the device as well.

However, if I do some edit on my app(just editing default string) it takes about 1-2 minutes to reload on the device which is very slow. Should it not be a little bit faster ?

Thank you for explanation and I am sorry if I misunderstood something.

**Comment by jimmylee** [comment]
@gunzino welcome and thanks for using Expo!  I don't have much experience using Expo on Ubuntu but I've cc'd @fson who might be able to help provide some insight.

**Comment by gunzino** [comment]
thanks!

the only thing I do is editing the default string in App.js. I think it should only send this small change but it does full build instead.

**Comment by gunzino** [comment]
Using CRNA, the live reload works fine.

**Comment by becreat** [comment]
@gunzino  Just disable Live Reload and Keep Enable Hit Reloading :) Simple
