### ISSUE TITLE
[Android] Android hangs at when asking permissions for push-notifications

### ISSUE THREAD

**Issue by emilpriverrc** [expo/expo#12282]
### Summary

We have a problem were a user are able to open the app for the first time and sign in, But when the user restart the app wont the user load the application as the app cant connect to firebase for notifications. We still use expo and expos own service for notifications.

`Caused by: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 3.23.0 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: 39.0.0 => 39.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18

### Reproducible demo or steps to reproduce from a blank project

Start the app in a real android device and ask for notifications permissions.

**Comment by cruzach** [comment]
@emilpriverrc I tried this with a blank app and wasn't able to reproduce- if you can provide a reproducible demo like we ask for in the template, I can re-open and investigate this.

You may want to make sure you've setup FCM properly- https://docs.expo.io/push-notifications/using-fcm/, and added `google-services.json` to your project and then rebuilt with `expo build:android`
