### ISSUE TITLE
Facing issue after ejecting to bare flow at runtime

### ISSUE THREAD

**Issue by jitendrahpatwa** [expo/expo#12280]
### Summary

Hi Team,

Facing an issue after ejecting from expo to bare using react native metro.
All the compilation process completed fine for the project. But stuck at run time for manifest issues.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

38.0.8

### Environment

Expo CLI 4.2.1 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Step that used to execute app,
Used following steps from eject to native run,
1 expo eject
2 created index.js from, 
> react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
3 added some plugin dependencies in build.gradle
4 run app using, 
> cd android && gradlew clean && cd .. && yarn android

After compiled code successfully and running with 
`>yarn react-native run-android`
gives following error as shown in below,
![Screenshot_20210322-174534](https://user-images.githubusercontent.com/17291685/112004072-79f57380-8b47-11eb-91fc-110198ed7c82.jpg)

I tried finding the resolution for it but failed.
Following are the scenarios have tried.
using importing like,

```
import { name as appName } from './app.json';
import Constants from 'expo-constants';
import * as manifest from "./app.json"
if (!Constants.manifest){
    Constants.manifest = manifest.default.expo
}
```

here also used like 
```
Constants.manifest = manifest.expo;
Constants.manifest = { ...manifest.expo, id: '...' };
```
But still shows manifest.scheme error :
![Screenshot_20210322-174607](https://user-images.githubusercontent.com/17291685/112004138-8974bc80-8b47-11eb-8d5c-42eb39470fd7.jpg)

Please suggest what can be done here to resolve the same it will be helpful.

**Comment by brentvatne** [comment]
hello! you should update to sdk 40 and then eject. this is resolved in sdk 40
