### ISSUE TITLE
[Android] Can't find recorded audio file

### ISSUE THREAD

**Issue by James2516** [expo/expo#1229]
I detached to ExpoKit, recorded an audio, and `recording.getURI()` returns
`file:///data/user/0/app/cache/ExperienceData/%2540anonymous%252Fapp-7f1f4908-e9cb-4519-a432-18a05942cce4/Audio/recording-1de5fe1c-b622-47f2-bd24-1314ef0d259b.3gp`.

I try to read the file with `RNFetchBlob.fs.readFile(file, 'base64')` using https://github.com/wkh237/react-native-fetch-blob but it throws `No such file or directory`. Removing the `file://` didn't work either.

**Comment by brentvatne** [comment]
we don't support react-native-fetch-blob, you're best off asking on their repo about why it can't read that uri

**Comment by brentvatne** [comment]
also -- reading the base64 string of an audio file over the bridge is not a good idea. if the audio file is very large you will maybe stall your app for several seconds or more
