### ISSUE TITLE
[expo-in-app-purchase] getPurchaseHistoryAsync() transaction is not resolved.

### ISSUE THREAD

**Issue by watanabeyu** [expo/expo#12291]
### Summary

When I try to do a purchaseItemAsync() after a getPurchaseHistoryAsync() in expo-in-app-purchases, the purchase modal does not appear.
The transaction has not been resolved, so the history transaction is still intact and the purchase modal does not appear.

please fix, thank you.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.11.0 - ~/.nodebrew/current/bin/node
      npm: 7.6.0 - ~/.nodebrew/current/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.1 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/l7dK8zsDH

Run device on bare workflow.
1. Press Query History button.
2. Press Buy button.

**Comment by jonny-kc** [comment]
did you manage to resolve this issue?

**Comment by AlenToma** [comment]
Getting the same issue. it happen sometimes only.

Is there any solution to this?

**Comment by AlenToma** [comment]
Managed to fix by settings `useGooglePlayCache: false`

You will have to handle the `Cache` manually instead.

Hop this could help.

`await InAppPurchases.getPurchaseHistoryAsync({ useGooglePlayCache: false });`

**Comment by caycecollins** [comment]
> Managed to fix by settings `useGooglePlayCache: false`
> 
> You will have to handle the `Cache` manually instead.
> 
> Hop this could help.
> 
> `await InAppPurchases.getPurchaseHistoryAsync({ useGooglePlayCache: false });`

Unfortunately your fix only affects Android. This issue is regarding iOS and I'm seeing the same behavior as described by the OP, reproducible every time when attempting `purchaseItemAsync()` after a `getPurchaseHistoryAsync()`

Has anybody managed to find a solution or workaround?

**Comment by AlenToma** [comment]
Yes after much work, I found a solution to this problem.
when you fire `getPurchaseHistoryAsync` dont wait for it to finish and instead gets your history in `PurchaseListener`
 example 
```js
     InAppPurchases.setPurchaseListener(async ({ responseCode, results, errorCode }) => {
            // Purchase was successful
            if (responseCode === InAppPurchases.IAPResponseCode.OK && results) {
                results.forEach(purchase => {
                    if (!purchase.acknowledged) {
                        console.log(`Successfully purchased ${purchase.productId}`);
                        // Process transaction here and unlock content...
                        // Then when you're done
                        this.finishTransactionAsync(undefined, purchase);
                    } else if (!this.unlockedItems.find(x => x.productId == purchase.productId)) // your history items
                        this.unlockedItems.push(purchase);
                });
});


```
