### ISSUE TITLE
Notification handler doesn't run when app is not backgrounded

### ISSUE THREAD

**Issue by FrickenHamster** [expo/expo#12290]
### Summary

Hey,
So I'm trying to get my expo app to run the notification handler when it is opened from a notification. When I open the app, background it, and then open the app from a notification, it works as intended.

However, if I close the app, then open it from a notification, the notification handler never runs.

This happens with both a built app and on expo go.

I've also been able to reproduce it with the snack app on the expo notification page.

expo-notifications version is 0.8.2

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40.0.0

### Environment

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 27, 28, 29
        Build Tools: 19.1.0, 28.0.3, 29.0.1, 29.0.2
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://docs.expo.io/versions/latest/sdk/notifications/
I can reproduce it if I open this snack in expo go. Close the app, then send a notification from the expo notification dashboard. Then open the app from the notification. The handle will not run, so the text will not change.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/expo/expo/blob/5d59e2b8d50bcdac71c669cfeef0e9765e0f9890/packages/expo-notifications/src/scheduleNotificationAsync.ts#L19-L31

https://github.com/expo/expo/blob/5d59e2b8d50bcdac71c669cfeef0e9765e0f9890/packages/expo-notifications/src/scheduleNotificationAsync.ts#L19-L31

https://github.com/expo/expo/blob/5d59e2b8d50bcdac71c669cfeef0e9765e0f9890/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/scheduling/NotificationScheduler.java#L74-L99

**Comment by cruzach** [comment]
This was fixed in SDK 41, see:
- https://github.com/expo/expo/issues/11933
- https://github.com/expo/expo/issues/12228

The beta will be available soon, stay tuned! (if you need the fix now, you can install `expo-notifications@next` if you're in the bare workflow
