### ISSUE TITLE
[expo-av][iOS] App crashes when quickly changing lot of videos

### ISSUE THREAD

**Issue by mtroskot** [expo/expo#12302]
### Summary

App crashes when quickly changing lot of videos.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 21, 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.0-rc.4 => 0.64.0-rc.4 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project
Reproducible demo: https://snack.expo.io/@trokiize/video-crash
Change playing video by pressing next. Press next in different intervals, from multiple times in 1 second, to once every second. The app will crash eventually.

I've attatched bellow the logs from Xcode and Firebase.
[Xcode log.txt](https://github.com/expo/expo/files/6196925/Xcode.log.txt)
[firebase log.txt](https://github.com/expo/expo/files/6196926/firebase.log.txt)

**Comment by mtroskot** [comment]
Possible duplicate of  [issue 117719](https://github.com/expo/expo/issues/11719)

**Comment by jackblackCH** [comment]
I had the same issue. Do not change the source it self, rather use the loadAsync({uri: 'your_source'}), it works like a charm.
