### ISSUE TITLE
[github] I can't merge my PR that was approved and tested

### ISSUE THREAD

**Issue by vvladd** [expo/expo#12303]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

https://github.com/expo/expo/pull/12285 
I have an error: `Merging is blocked The base branch restricts merging to authorized users.`
<img width="950" alt="screen" src="https://user-images.githubusercontent.com/13506999/112327740-c0251100-8cc6-11eb-85e8-b505aa488cf0.png">

**Comment by brentvatne** [comment]
only expo employees can merge pull requests
