### ISSUE TITLE
Production EXVideoView issue.

### ISSUE THREAD

**Issue by ngima** [expo/expo#12314]
### Summary

Getting this crash report on AppStoreConnect. Not able to recreate it on my end. Not sure what should I do to avoid it in future.

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000da9be5000
VM Region Info: 0xda9be5000 is not in any region.  Bytes after previous region: 47408107521  Bytes before following region: 8963338240
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO              280000000-2a0000000 [512.0M] rw-/rwx SM=PRV  
--->  GAP OF 0xd20000000 BYTES
      commpage (reserved)      fc0000000-1000000000 [  1.0G] ---/--- SM=NUL  ...(unallocated)

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [8989]
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libobjc.A.dylib               	0x00000001ad9d7474 objc_msgSend + 20
1   CoreFoundation                	0x00000001996b4088 mdict_rehashd + 184 (NSDictionaryM_Common.h:59)
2   CoreFoundation                	0x00000001995411ac -[__NSDictionaryM setObject:forKey:] + 548 (NSDictionaryM_Common.h:194)
3   CoreFoundation                	0x00000001995480a8 -[NSMutableDictionary addEntriesFromDictionary:] + 260 (NSMutableDictionary.m:31)
4   AppProd           	0x000000010475e2e8 -[EXVideoView setStatus:resolver:rejecter:] + 96 (EXVideoView.m:363)
5   AppProd           	0x0000000104753e4c __53-[EXAV _runBlock:withEXVideoViewForTag:withRejecter:]_block_invoke + 104 (EXAV.m:414)
6   AppProd           	0x0000000104c2571c __55-[UMReactNativeAdapter executeUIBlock:forView:ofClass:]_block_invoke + 68 (UMReactNativeAdapter.m:0)
7   AppProd           	0x0000000104c26560 __47-[UMReactNativeAdapter executeUIBlock:forView:]_block_invoke_2 + 68 (UMReactNativeAdapter.m:295)
8   AppProd           	0x0000000104b70198 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke + 180 (RCTUIManager.m:1189)
9   AppProd           	0x0000000104b703c8 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.422 + 336 (RCTUIManager.m:1209)
10  libdispatch.dylib             	0x000000019928d298 _dispatch_call_block_and_release + 24 (init.c:1454)
11  libdispatch.dylib             	0x000000019928e280 _dispatch_client_callout + 16 (object.m:559)
12  libdispatch.dylib             	0x000000019923d05c _dispatch_main_queue_callback_4CF$VARIANT$mp + 896 (inline_internal.h:2548)
13  CoreFoundation                	0x00000001995d55e0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12 (CFRunLoop.c:1790)
14  CoreFoundation                	0x00000001995cfa88 __CFRunLoopRun + 2480 (CFRunLoop.c:3118)
15  CoreFoundation                	0x00000001995ceba0 CFRunLoopRunSpecific + 572 (CFRunLoop.c:3242)
16  GraphicsServices              	0x00000001b0337598 GSEventRunModal + 160 (GSEvent.c:2259)
17  UIKitCore                     	0x000000019bec02f4 -[UIApplication _run] + 1052 (UIApplication.m:3253)
18  UIKitCore                     	0x000000019bec5874 UIApplicationMain + 164 (UIApplication.m:4707)
19  AppProd           	0x00000001046bd0d8 main + 88 (main.m:8)
20  libdyld.dylib                 	0x00000001992ad568 start + 4

#Could some one please tell what's wrong here?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.5.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 22, 25, 26, 27, 28, 29, 30
        Build Tools: 21.1.2, 27.0.3, 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.1, 30.0.2
        System Images: android-21 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.0 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Unable to reproduce.

**Comment by cruzach** [comment]
> Unable to reproduce.

We state in the issue template that we need repros in order to begin investigating, otherwise the issue will be closed, so I'm going to close this. Here's a guide to debugging production crashes- https://docs.expo.io/workflow/debugging/#production-errors
