### ISSUE TITLE
Expo.ImagePicker.launchCameraAsync() make app restart on some device

### ISSUE THREAD

**Issue by masmun12** [expo/expo#1232]
device detail = Xiaomi MI4C MIUI9 China Stable
android version = 7.0

**Comment by quinlanj** [comment]
hi @masmun12 , could you give us more details to reproduce this? What would be really helpful if you gave us a step by step list to follow so we can get the same error, using your device. Also if you can send some `adb logs` our way, that would also be great. Thanks again for reporting this!

**Comment by jesseruder** [comment]
Going to close this until we hear more details.
