### ISSUE TITLE
Expo app problem loading especific custon font weights

### ISSUE THREAD

**Issue by crisfcodes** [expo/expo#12323]
### Summary

I have created an `react-native/typescript` app with `expo CLI`, this generate some base code, inlcuding `hooks/useCachedResources` to load any resources or data that we need prior to rendering the app, in my case in this hook I load custom fonts(in particular [Inter Display Font](https://github.com/rsms/inter/releases/tag/display-beta-1)). I'm experimenting some problems because the app loads only two weights: `regular and medium`, If I try to use `semi-bold` or `bold` this doesnt work and use the san serif font that comes by default.

### Additional data:

1. The fonts path its ok
2. Expo app doesn't show any error. I have seen in other [questions](https://stackoverflow.com/questions/62761262/custom-font-load-not-working-in-expo-react-native-app) errors such as `fontFamily "MyFontFamily" is not a system font and has not been loaded through Font.loadAsync.` This is not the case.
3. Font family name is in the correct format.
4. I'm using [React Native UI Kitten](https://akveo.github.io/react-native-ui-kitten/docs/guides/branding#typography) and I load the fonts as they suggest in `Advanced Configuration` and change some especific styles. 
5. According to some [answers](https://stackoverflow.com/a/38820631/8582246) The out of the box support for custom fonts on Android is a little limited in React Native. It does not support font weights other than normal and bold. So I tried setting `fontWeight: normal` or any of the weights but nothing works.

### useCachedResources hook

This come by default with `expo init my-app`.

```typescript
import * as Font from 'expo-font';
import * as SplashScreen from 'expo-splash-screen';
import { useEffect, useState } from 'react';

// Error reporting service
import { logger } from '@utils';

export function useCachedResources(): boolean {
  const [isLoadingComplete, setLoadingComplete] = useState(false);

  // Load any resources or data that we need prior to rendering the app
  useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {
        await SplashScreen.preventAutoHideAsync();

        // Load fonts
        await Font.loadAsync({
          'inter-display-regular': require('../assets/fonts/InterDisplay-Regular.ttf'),
          'inter-display-medium': require('../assets/fonts/InterDisplay-Medium.ttf'),
          'inter-display-semibold': require('../assets/fonts/InterDisplay-SemiBold.ttf'),
          'inter-display-bold': require('../assets/fonts/InterDisplay-Bold.ttf'),
        });
      } catch (loadCachedResourcesError) {
        logger.log(loadCachedResourcesError);
      } finally {
        setLoadingComplete(true);
        await SplashScreen.hideAsync();
      }
    }

    loadResourcesAndDataAsync();
  }, []);

  return isLoadingComplete;
}
``` 

### Consuming the hook in App.tsx

```typescript
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import useCachedResources from './hooks/useCachedResources';
import Navigation from './navigation';

// again this comes by defautl expo init command
export default function App(): React.ReactElement | null  {
  const isLoadingComplete = useCachedResources();

  if (!isLoadingComplete) {
    return null;
  } 

  return (
    <SafeAreaProvider>
      <Navigation />
      <StatusBar />
    </SafeAreaProvider>
  );
}
```

### mapping.json: specific UI-Kitten configuration to change font style 

I can think that the problem comes from here but the thing is, if there was a problem loading the fonts, either expo would have already thrown an error or the other fonts weights(regular/medium) would not load.

```JSON
{
  "strict": {
    "text-font-family": "inter-display-regular",

    "text-heading-1-font-size": 32,
    "text-heading-1-font-weight": "normal",
    "text-heading-1-font-family": "inter-display-medium",

    "text-paragraph-1-font-size": 16,
    "text-paragraph-1-font-weight": "normal",
    "text-paragraph-1-font-family": "$text-font-family",
  }
}
```

### metro.config.js

I'm using [UI Kitten metro config](https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance) to load custom `mappding` and improve perfomance:

```typescript
// Improving Performance of UI Kitten:
// https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance

const MetroConfig = require('@ui-kitten/metro-config');

const evaConfig = {
  // represent the name of Eva Design System package installed - In this case @eva-design/eva
  evaPackage: '@eva-design/eva',
  // Mapping customization feature.
  customMappingPath: './src/globalStyles/mapping.json',
};

module.exports = MetroConfig.create(evaConfig, {
  // Whatever was previously specified
});

```

## The problem

I have no idea if the problem comes from `expo`, `ui kitten` or if `inter` font can't be loaded by react native by some other reason.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

~40.0.0

### Environment

Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\Desktop\saleor-storefront-react-native\nod
e_modules\.bin\yarn.CMD
      npm: 7.7.3 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - D:\tools\watchman-v2021.01.11.
00-windows\bin\watchman.EXE
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/s
dk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Create a Expo app with `expo init my-app` and add UI kitten as dependency.
2.  in `App` component wrap the navigation with `ApplicationProvider` like so:
```typescript
<ApplicationProvider {...eva} theme={{ ...eva.light, ...UIKTheme }}>
    <RootNavigator />
</ApplicationProvider>
```
3. Create and configuring Metro Bundler as UI Kitten [documentation](https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#definition) reccomends.
4. use `useCachedResources` default hook to load [inter font](https://github.com/rsms/inter).
5. Try to use `semibold` or `bold` weights in any component.

**Comment by byCedric** [comment]
Hi @cristian05! I can confirm this should work normally, you can [check out this snack](https://snack.expo.io/@bycedric/expo-issue-12323) on an Android or iOS device/emulator. (see `resources.js` to switch fonts, I used a more distinctive font to determine if it works)

That being said, this error might occur when you have multiple `expo-font` packages installed. I would validate that and try to deduplicate them.
- `$ yarn why expo-font`
- `$ npm list expo-font`

Hope this helps!

**Comment by cristian05** [comment]
Hello @byCedric, sorry in the open issue I missed that I am loading the `mapping.js` or the `customTheme` in your example with suggested [metro config](https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance) by UI Kitten. This can be important to check the error. Other thing is Im not loading fonts with `expo-google-fonts`, I Imagine to this is not relevant but its other difference with your example.  Finally, rememver that in my case I can load `regular` and `medium` but if I try to use `semi-bold or bold` this doesnt work.

This is the console output run the command `yarn why expo-font`:

```shell
λ yarn why expo-font
yarn why v1.22.10
[1/4] Why do we have the module "expo-font"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "expo-font@8.4.0"
info Has been hoisted to "expo-font"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "expo#expo-font"
info Disk size without dependencies: "260KB"
info Disk size with unique dependencies: "8.84MB"
info Disk size with transitive dependencies: "16.94MB"
info Number of shared dependencies: 13
```
