### ISSUE TITLE
Unable to use Camera.Constants in a strictly typed TS enviornment

### ISSUE THREAD

**Issue by hbiede** [expo/expo#12332]
### Summary

Whenever using Camera.Constants in a strictly typed TS file, all the properties are typed as any, yielding @typescript-eslint/no-unsafe-member-access errors due to my linter.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40.0.1

### Environment

Expo CLI 4.2.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Attempt to use `Camera.Constants.FlashMode` anywhere in TS

**Comment by brentvatne** [comment]
good call, you can you open a pull request?

**Comment by hbiede** [comment]
It’ll be Monday afternoon at the earliest

**Comment by hbiede** [comment]
PR Created: #12343

**Comment by hbiede** [comment]
Resolved by #12343
