### ISSUE TITLE
[docs] expo-yarn-workspaces, name exactly what package is being referred to 

### ISSUE THREAD

**Issue by conor909** [expo/expo#12338]
### Summary

Throughout the docs, is it always referring to the root of the repo?

**Comment by brentvatne** [comment]
that makes sense. "Add a postinstall script to package.json" and "Define the entry module in the "main" field of package.json" should be more clear. in the former case, it refers to the root, and in the latter case, it refers to the package.json for any app inside of the monorepo.

**Comment by conor909** [comment]
Ok, so I presume the initial `yarn add expo-yarn-workspaces --dev` should be ran at the root of your repo too

**Comment by conor909** [comment]
Are you sure the `postinstall` script goes in the root?

**Comment by brentvatne** [comment]
https://github.com/expo/expo/blob/master/package.json#L10

**Comment by brentvatne** [comment]
here's an example project with it set up: https://github.com/expo/examples/tree/master/with-yarn-workspaces

`npx create-react-native-app -t with-yarn-workspaces`

**Comment by ide** [comment]
expo-yarn-workspace's documentation applies to each app workspace package, not the workspace root. Adding a commit to make this clearer, though please be aware that expo-yarn-workspace's purpose is to work with this repository.
