### ISSUE TITLE
In bare projects several new versions of plugins are throwing iOS linker errors

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#12347]
### Summary

After bumping to `"expo-facebook": "11.0.2"` 
receive: 
ld: library not found for -lEXFacebook
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Also "expo-google-sign-in" threw the same error with 9.0.0 but not 9.1.0. Can you please advise what the necessary fix is to make the prebuilt binaries work with bare projects? I don't see any steps outlined in the FYI documents.

For Google:
ld: library not found for -lEXGoogleSignIn
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

    System:
      OS: macOS 11.2.3
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/admin/.rvm/gems/ruby-2.5.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.63 => 0.12.63
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ^0.15.0 => 0.15.0
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Install expo-facebook latest version, receive linker error. Install expo-google-sign-in 9.0.0, receive same linker error.

ld: library not found for -lEXGoogleSignIn
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by brentvatne** [comment]
this shouldn't require any additional steps. if you initialize a new project with `expo init shamilovtim --template expo-template-bare-minimum@sdk-41` then add the latest `expo-facebook`, run `npx pod-install`, then add a swift bridging header, your project will build as expected.

**Comment by shamilovtim** [comment]
Thanks Brent. I think it's .xcframeworks related which is why the latest majors are all throwing the error. Seeing lots of these warnings. Not sure if related.

```
target overrides the `EXCLUDED_ARCHS[sdk=iphonesimulator*]` build setting defined in `Pods/Target Support Files/Pods
```

**Comment by shamilovtim** [comment]
Tried to build for device and then got this: ld: library not found for -lEXGoogleSignIn. What's odd is that all of these errors are related to bumping from expo 9 plugins to expo 10/11 plugins which leads me to believe that this is all incompatibility with xcframeworks. However I'm not aware of any settings that I was supposed to migrate, and my experience has been that xcframework pods just work out of the box.

**Comment by shamilovtim** [comment]
Resolved. Those interested in the solution: this was caused by tons of legacy linker flags left over in the pbxproj inside of  `OTHER_LDFLAGS`. I replaced them with the standard ones: `"$(inherited)"` `"-lc++"`  and `"-ObjC"`.
