### ISSUE TITLE
Can you update video player? it's not working on android.

### ISSUE THREAD

**Issue by ArtyomBaykov** [expo/expo#1235]
In Android it shows spinner all the time. Expo is 22.0.0. I saw that it's your project too but it seems that you forgot that project. I found similar issue opened there but there was not any support so decided to open it here too. I've checked also code example as well as published version and none of them worked on android. Please update it. Here is the link:
[https://github.com/expo/videoplayer](https://github.com/expo/videoplayer)

**Comment by terribleben** [comment]
Hey there, sorry I think we did actually forget about that example. For now can you try [playlist-example](https://github.com/expo/playlist-example) (includes both Video and Audio) and see if that is helpful for you? I think it's more up to date.

**Comment by quinlanj** [comment]
looks like this was updated a couple days ago (https://github.com/expo/videoplayer/commit/2afb33bdd4da97b66e6d72fc54236c392dd1bf04)
Closing this issue.
