### ISSUE TITLE
Camera is not shown if open web version in mobile browser

### ISSUE THREAD

**Issue by tandu** [expo/expo#12369]
### Summary

When I open app with `Camera` component in mobile browser the camera is not initialized and I get this error: `MediaStreamTrack.getSources is not a function`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40.0.0

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.11.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

`expo init testCamera`, selected tabs with typescript option, installed camera component `expo install expo-camera` and put camera in first tab then opened in mobile web browser.
```typescript
export default function TabOneScreen() {
  const [camError, setCamError] = React.useState<string>();
  return (
    <View style={styles.container}>
      <Camera ratio='16:9' style={{flex: 1, width: '100%'}} onMountError={e => setCamError(e.message)}/>
    </View>
  );
}
```
Tried in default xiaomi browser and chrome browser in mi8 phone. In desktop browser camera is working correctly.

**Comment by brentvatne** [comment]
you should use `Camera.isAvailableAsync()` to see if it's available on your device: https://docs.expo.io/versions/latest/sdk/camera/#cameraisavailableasync-boolean

**Comment by tandu** [comment]
Camera is available on mobile phone physically. Does it mean that expo not allowing to use it from mobile web?

**Comment by brentvatne** [comment]
it means it's not available according to your browser: https://github.com/expo/expo/blob/dc2c39e31508a82a4a9bbdf62c53cb7bccb45779/packages/expo-camera/src/ExponentCameraManager.web.ts#L97-L107

eg: see https://github.com/jeromeetienne/AR.js/issues/558

also be sure the site is being served over https

**Comment by tandu** [comment]
Thank you for the advice, I really had to use https to see camera on mobile though in desktop it is not required. So `expo web --https` solves the issue.

**Comment by lavahasif** [comment]
@tandu worked

**Comment by Hittitech** [comment]
> Thank you for the advice, I really had to use https to see camera on mobile though in desktop it is not required. So `expo web --https` solves the issue.

but how can we test it out during development ? would be very  helpful.
I ran with same command but still its not opening the camera
