### ISSUE TITLE
EXPO-FACEBOOK Unable to resolve module unimodules-permissions-interface

### ISSUE THREAD

**Issue by JPSantistebanQ** [expo/expo#12361]
### Summary

After update from sdk 40 to beta 41. Not start the app.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.21343
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.7.0 - C:\Users\...\AppData\Roaming\npm\npm.CMD
    npmPackages:
      expo: ^41.0.0-beta.1 => 41.0.0-beta.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Failed building JavaScript bundle.
Unable to resolve module unimodules-permissions-interface from C:\Users\...\node_modules\expo-facebook\build\Facebook.js: unimodules-permission\build\Facebook.js: unimodules-permissions-interface could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | import { UnavailabilityError } from '@unimodules/core';
  2 | import { Platform } from 'react-native';
> 3 | import { PermissionStatus, } from 'unimodules-permissions-interface';
    |                                    ^
  4 | import ExponentFacebook from './ExponentFacebook';
  5 | export { PermissionStatus, };
  6 | const androidPermissionsResponse = {

After update from sdk 40 to beta 41. Not start the app.

**Comment by evanheckert** [comment]
I'm getting the same error but for expo-contacts. 

```
  1 | import { UnavailabilityError } from '@unimodules/core';
  2 | import { Platform, Share } from 'react-native';
> 3 | import { PermissionStatus } from 'unimodules-permissions-interface';
    |                                   ^
  4 | import uuidv4 from 'uuid/v4';
  5 | import ExpoContacts from './ExpoContacts';
  6 | export { PermissionStatus };
```

Inspecting yarn.lock, it seems `unimodules-permissions-interface` is missing as a dependency.

**Comment by brentvatne** [comment]
thanks. looks like we need to add this to a few packages

**Comment by Muirik** [comment]
I am still running into this error after upgrading from react-navigation 3 to 4 in June 2021. What is the workaround or way to resolve this?
