### ISSUE TITLE
getPurchaseHistory returns empty array

### ISSUE THREAD

**Issue by AlinaDogariu** [expo/expo#12365]
### Summary

I am using `expo-in-app-purchases` and `getPurchaseHistory` returns an empty array while testing it on iOS, even though the subscription exists in my AppStore account.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.0, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: bare

Library version: expo-in-app-purchases@10.0.0

### Reproducible demo or steps to reproduce from a blank project

```
const getReceipts = async () => {
  try {
    await connectAsync()

    const { responseCode, results } = await getPurchaseHistoryAsync(false)

    console.log(results) // []
    console.log(responseCode) // 0

    return results
  } catch (error) {
    console.error(error)
  }
}
```

**Comment by wen-kai** [comment]
We're noticing something similar -- we use the history to find if the user has redeemed an offer code outside of the app and apply their relevant subscription. Unfortunately the subscription doesn't seem to exist in purchase history when we call this function.
