### ISSUE TITLE
Crash on enableScreens(false)

### ISSUE THREAD

**Issue by alexandrius** [expo/expo#12374]
### Summary

enableScreens(false) crashes the app when used with react-navigation 4.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.21.0 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/opt/node@12/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 25, 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0-beta.1 => 41.0.0-beta.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Wasn't able to reproduce 

![Simulator Screen Shot - iPhone 11 - 2021-03-31 at 22 48 34](https://user-images.githubusercontent.com/5978212/113195357-3bf8fd80-9273-11eb-82f1-34d105108a3a.png)

**Comment by brentvatne** [comment]
is this the first thing called in your app? it should be at the top of App.js

**Comment by brentvatne** [comment]
can you share the relevant code?

**Comment by alexandrius** [comment]
```jsx
import { Provider } from 'aniuta';
import { AppLoading } from 'components';
import ExpoAppLoading from 'expo-app-loading';
import * as Font from 'expo-font';
import * as Notifications from 'expo-notifications';
import React, { useState, useEffect } from 'react';
import { View, LogBox, Platform, Keyboard } from 'react-native';
// import { UpdateRequired } from 'screens';
import { enableScreens } from 'react-native-screens';
import * as Sentry from 'sentry-expo';
import { Ajax, Analytics } from 'services';
import { Common } from 'styles';
import { Defaults, initilizeFeedbackLogic, isAndroid } from 'utils';
import { RECENTLY_UPDATED, AsyncStorage, loadProfile, deleteProfile } from 'utils/settings';
import { enableAndroidLayoutChanges } from 'utils/uiUtils';

import { ENV } from './env';
import Root from './src/root';

enableScreens(false);

//Disable LogBox
LogBox.ignoreAllLogs(true);

//Disable logs if production
if (!__DEV__) {
   console.log = () => {};
}

let notificationListener;

//Workaround notification not received when app is killed | Android
if (isAndroid())
   notificationListener = Notifications.addNotificationResponseReceivedListener(
      ({ notification }) => {
         Defaults.initialNotification = notification;
      }
   );

Sentry.init({
   dsn: 'https://246a878df2124f04b19a67ed86109a6c@sentry.io/1845448',
   environment: ENV,
});

let isLoggedIn = false;

export default function App({ exp }) {
   const [coreLoaded, setCoreLoaded] = useState(false);
   const [animationFinished, setAnimationFinished] = useState(false);
   const [recentlyUpdated, setRecentlyUpdated] = useState(true);

   useEffect(() => {
      enableAndroidLayoutChanges();
      if (exp.notification)
         Defaults.initialNotification = { request: { content: exp.notification } };
   }, []);

   useEffect(() => {
      const keyboardWillShowListener = Keyboard.addListener(
         Platform.select({
            ios: 'keyboardWillShow',
            android: 'keyboardDidShow',
         }),
         ({ endCoordinates }) => {
            Defaults.keyboardCurrentHeight = endCoordinates.height;
         }
      );
      const keyboardWillHideListener = Keyboard.addListener(
         Platform.select({
            ios: 'keyboardWillHide',
            android: 'keyboardDidHide',
         }),
         () => (Defaults.keyboardCurrentHeight = 0)
      );
      return () => {
         keyboardWillShowListener.remove();
         keyboardWillHideListener.remove();
      };
   }, []);

   const loadCore = async () => {
      console.log('Loading Core');

      Analytics.setVersion();

      await Font.loadAsync({
         regular: require('./assets/fonts/lineto-brown-pro-regular.ttf'),
         light: require('./assets/fonts/lineto-brown-pro-light.ttf'),
         bold: require('./assets/fonts/lineto-brown-pro-bold.ttf'),
         FontAwesome: require('./assets/fonts/fa-light-300.ttf'),
         FontAwesomeSolid: require('./assets/fonts/fa-solid-900.ttf'),
         FontAwesomeRegular: require('./assets/fonts/fa-regular-400.ttf'),
      });

      const profile = await loadProfile();
      await initilizeFeedbackLogic(profile);
      setRecentlyUpdated(!!(await AsyncStorage.getItem(RECENTLY_UPDATED)));
      AsyncStorage.removeItem(RECENTLY_UPDATED);

      if (profile) {
         Defaults.profile = JSON.parse(profile);
         Analytics.setUser(Defaults.profile.id);
         try {
            isLoggedIn = true;
            const { watchlist } = await Ajax.get('account');
            if (watchlist) {
               Defaults.saved = watchlist;
            }
         } catch (error) {
            if (error.response.status === 401) {
               Defaults.profile = null;
               isLoggedIn = false;
               deleteProfile();
            }
         }
      }
      if (isAndroid()) notificationListener.remove();

      console.log('Core Loaded');
   };

   if (!coreLoaded)
      return (
         <ExpoAppLoading
            startAsync={loadCore}
            onFinish={() => setCoreLoaded(true)}
            onError={() => {}}
         />
      );

   // return <UpdateRequired />;

   return (
      <View style={Common.fill}>
         <Provider>
            {animationFinished ? (
               <Root />
            ) : (
               <AppLoading
                  onFinish={() => setAnimationFinished(true)}
                  {...{ recentlyUpdated, isLoggedIn }}
               />
            )}
         </Provider>
      </View>
   );
}
```

**Comment by alexandrius** [comment]
I definitely will on the weekend, sorry really swamped atm

**Comment by brentvatne** [comment]
thanks! good luck with your work

**Comment by WoLewicki** [comment]
@alexandrius can you check if applying https://github.com/react-navigation/react-navigation/pull/9477 to your code fixes the issue?

**Comment by alexandrius** [comment]
@brentvatne Works fine on 2.18.1

@WoLewicki the path does fix the problem too

**Comment by Infinitism** [comment]
I tried all the steps mentioned and the app still crashes on ios only. Works fine on Android! 

This is the diagnostics I have:

  Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/refs/tags/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed
