### ISSUE TITLE
Unable to resolve "expo-location" from "node_modules/expo/build/Expo.fx.js

### ISSUE THREAD

**Issue by alexandrius** [expo/expo#12372]
### Summary

Upgrade with `EXPO_BETA=1 expo upgrade.
get the error `Unable to resolve "expo-location" from "node_modules/expo/build/Expo.fx.js`
Once I install expo-location Expo Go crashes without logs. iOS system logs:
```
Mar 31 22:16:51 Alexanders-MacBook-Pro com.apple.CoreSimulator.SimDevice.BDE3DCFA-28D1-45DA-8DD9-9218CAE4F6C9[25076] (UIKitApplication:host.exp.Exponent[aaf1][rb-legacy][36677]): Service exited due to SIGABRT
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.21.0 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/opt/node@12/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 25, 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0-beta.1 => 41.0.0-beta.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Wasn't able to reproduce in blank project

![Simulator Screen Shot - iPhone 11 - 2021-03-31 at 21 50 58](https://user-images.githubusercontent.com/5978212/113189755-993d8080-926c-11eb-83ec-967424e00fce.png)

**Comment by brentvatne** [comment]
what version does `yarn why metro` give you?

**Comment by brentvatne** [comment]
it should be 0.59.0 - you will need to clear your lockfile and node_modules and run `yarn` again, or you can uninstall the react-native package and reinstall it

the reason this happened is that metro@0.59.0 was released a couple months ago but wouldn't be used if you already had locked down that dependency. so we may need to clear lockfiles or remove/re-add react-native when updating to sdk 41

**Comment by alexandrius** [comment]
All good thanks!
