### ISSUE TITLE
[Beta] Lottie animation make app instant crash on iOS

### ISSUE THREAD

**Issue by wawrzy** [expo/expo#12378]
### Summary

Lottie animation is crashing the app on the new SDK 41 release on iOS simulator.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0-beta.1 => 41.0.0-beta.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@julienw/lottie-ios

Hello, I try the new SDK 41 in my project and I notice an instant crash in my app when I'm trying to load an animation.

(The animation is in my snack https://snack.expo.io/@julienw/lottie-ios)

**Comment by brentvatne** [comment]
fixed in https://github.com/expo/expo/pull/12377

**Comment by brentvatne** [comment]
- updated simulator build released: `EXPO_BETA=1 expo client:install:ios`
- testflight build in review
- standalone app builder updated
