### ISSUE TITLE
[Android] Cannot read property 'length' of null

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#1237]
Hey guys, when I try to start the android sim, I get this error message: 

```
(node:22219) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'length' of null
```

Before the android app even starts. I'm using genymotion with a custom android SDK. Anyone know what's up with that? 

When I run `adb logcat` I get a ton of messages streaming, and also stuff like this:

```
I/installd(   90): new connection
I/SystemServiceManager( 5703): Starting com.android.server.am.ActivityManagerService$Lifecycle
I/ActivityManager( 5703): Memory class: 96
I/ServiceThread( 5703): Enabled StrictMode logging for ActivityManager looper.
I/DEBUG   (   86): 
I/DEBUG   (   86): Tombstone written to: /data/tombstones/tombstone_09
E/eglCodecCommon( 5699): writeFully: failed: Broken pipe
W/libEGL  ( 5699): eglInitialize(0xb71e7040) failed (EGL_SUCCESS)
I/ServiceManager(  381): service 'media.audio_flinger' died
I/ServiceManager(  381): service 'sensorservice' died
E/installd(   90): eof
E/installd(   90): failed to read size
I/installd(   90): closing connection
```

**Comment by quinlanj** [comment]
hi @lightninglu10  , thanks for reporting this! Could you also send your `adb logs` our way to help us root cause this problem?

**Comment by lightninglu10** [comment]
I don't really know what the issue was, but I changed the simulator for to a different device and now it works.

**Comment by pashute** [comment]
My genimotion virtual device wasn't responding. Closed it. and re-opened. showed errors of missing npm installs. installed and alls ok.

**Comment by remeshothera** [comment]
any fix for this issue ? i am also facing the same issue.
I am using GenyMotion virtual devices.

**Comment by habeelmazhar** [comment]
For me this issue was caused when the warning on expo-cli  said to uninstall  and reinstall expo on emulator (in my case, genymotion).
