### ISSUE TITLE
"Open up Snack" dialog appears on device, even though the QR was already scanned

### ISSUE THREAD

**Issue by jaggzh** [expo/expo#1238]
Platform: iOS and Android
After scanning in a QR code of a snack in my registered account, the app shows for a split second before an impenetrable dialog pops up.
For example: https://snack.expo.io/@jaggzh/slider-example
(QR Code contains: exp://expo.io/@\jaggzh/slider-example+SJ_ChzrNM )
*I can't get github's markdown @ symbol to be ignored in the URL above, so ignore the \ *

Reproduce:
1. Run Expo
2. Scan QR code
3. Receive "Welcome to Expo!" screen
4. If you get Expo's intro message, click X or Got It.
5. Message pops up saying:
  *"Open up https://snack.expo.io and scan the QR code to get started!
   Make sure to leave the web page open while you are running the project."*

The app shows briefly before this window pops up.
I'm not sure why it goes to this screen.  Nothing can be done from here that I can find, and Expo app needs to be killed at this point in iOS. Android's back button will return to Expo's main screen.
*

In iOS, *the window has the Camera's view visible* below the message (#5 above).
It won't scan and doesn't seem like the QR code scanning interface.  Android is in an emulator with no cam at the moment, and shows a full white screen (see screenshot posted below).

*Note: Edited to include Android after @sjchmiela's labeling.

**Comment by jaggzh** [comment]
![foo](https://user-images.githubusercontent.com/20318973/34849559-9b2a96fa-f6d7-11e7-8317-52514a8ebff6.jpg)

**Comment by aalices** [comment]
@jaggzh would it be possible for you to record what is happening and put here as a gif? I don't really get the issue 🤔

**Comment by jaggzh** [comment]
Okay.
1. Please bear in mind, I'm using the android emulator here, not my iPad.  If I use the iPad it happens when I scan the QR code with the camera.  With the android emulator, I'm using a URL I obtain from the QR code. The same message appears in either case.
2. Please also note that the Expo snack is definitely loading, because I'm sometimes able to see a brief error message of, say, a syntax error in my snack, right before the white final screen shows.
3. Please thirdly remember that the iPad shows the same white screen, but with the live camera view taking the bottom 2/3, or so, of the display.
4. And fourthly, the `expoqr` script is available at: https://github.com/jaggzh/react-native--expo-shell-utils

![ss](https://user-images.githubusercontent.com/20318973/35007525-cdffda4c-faae-11e7-8e69-d7e3c03ba52e.gif)

**Comment by aalices** [comment]
Your snack contains an Error in line 21 (`Test` not defined). Is this on purpose just to show that the behavior is wrong when the code contains some errors? If no, is this working when you change this to be just a text (without braces) ?

**Comment by jaggzh** [comment]
Yes, deliberate.  In both cases it goes to the off-white message.  With the code error I was once able to briefly see the red screen with the syntax error before it moved to the off-white message.

**Comment by jaggzh** [comment]
Yeah, with and without the error, my app very briefly shows before this message appears (or the error briefly shows).  If there's a way I can help, please let me know.  I can skype or teamviewer screenshare, or if there are some logs that'd help you...?  This only happens on the user-based Snacks (vs. the anonymous random-ID URL's).

**Comment by jaggzh** [comment]
Here's someone else's snack with the same behavior:
https://snack.expo.io/@notbrent/circular-video

**Comment by jaggzh** [comment]
Here's a snapshot of the iPad screen, immediately subsequent to successful QR scan:  Note the continued live camera view:
![expo-qr-error](https://user-images.githubusercontent.com/20318973/35360152-96579e18-0111-11e8-875f-2a62769b0a3e.jpg)
