### ISSUE TITLE
Expo-facebook 11.0.x contains bug from FBSDK during archive. Needs to be bumped to FbSDK 9.1.0.

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#12389]
### Summary

Archiving a project with Expo-Facebook 11.0.x in it throws an error:  
`FBSDKLoginKit(LoginManager.o)' was built without full bitcode.` 

This is due to a bug in the underlying FBSdk: https://github.com/facebook/facebook-ios-sdk/issues/1660.
Please bump to FBSDK 9.1.0 when possible!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/admin/.rvm/gems/ruby-2.5.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.63 => 0.12.63
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ^0.15.0 => 0.15.0
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Try to archive a project which includes Expo-Facebook 11.0.x and fail, receive the error from the FBSDK above.

**Comment by brentvatne** [comment]
this is a known issue that is still present in the underlying fbsdk. we investigated and opened a pr to fix it, but it hasn't been merged or released yet: https://github.com/facebook/facebook-ios-sdk/pull/1698

also see: https://github.com/facebook/facebook-ios-sdk/issues/1679

because of this, we had to disable bitcode for Expo Go and iOS standalone apps during the SDK 41 beta release, but we are hoping to have this resolved soon.

**Comment by brentvatne** [comment]
this is fixed in todays facebook-ios-sdk release. we'll publish a new version of expo-facebook tmrw

**Comment by shamilovtim** [comment]
Nice!
