### ISSUE TITLE
[expo-gl] Performance issue

### ISSUE THREAD

**Issue by Losses** [expo/expo#12399]
### Summary

The performance of expo-gl is worse than WebGL(inside a webview) on most situation.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40.0.1 

### Environment
```
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (4.1.6).                 │
│   You are currently using expo-cli 4.1.4                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘

  Expo CLI 4.1.4 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.14.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@zhaodonghao586/0e4aaa
https://github.com/zwh1666258377/expo-gl-demo

* * *

Hello everyone, we’ve met some serve performance issue and wonder if we can get some help or insight from the development team.
Things we’ve did is quite simple, run the same benchmark code on both WebView and ExpoGL, based on previous discussion happens on Expo-THREE, we expect that the performance of Expo GL should be better than WebGL running on a browser, but the performance of ExpoGL is much worse than WebGL, we’ve created a very simple program to reproduce the problem.
This example uses Instancing, where you can keep increasing the number of elements to see the difference in performance between WebGL and ExpoGL.
Do we have a chance to deal with this issue? Do we have a chance to deal with this issue?
Our team wanted to use ExpoGL as a fallback solution when WebGL performance was lacking.
The current solution from ExpoGL looks pretty sound, so maybe there is something wrong somewhere that has led to the current situation.

Related discussion:
https://github.com/expo/expo-three/issues/26
https://github.com/expo/expo/issues/12030
https://forums.expo.io/t/expo-gl-really-poor-performance-how-to-improve/46540

**Comment by brentvatne** [comment]
the purpose of expo-gl isn't to beat out a webview but to integrate with native views and fit seamlessly into your app. as @nikki93 mentioned on the expo-three thread:

> The perf is (from my profiling a bit ago) mostly due to differences in like pure math in JS. We could theoretically enable JIT on Android JSC but I don't think we do right now

jsc on ios does not have jit enabled and there is no way to change that, and it's up to you if you want to do this on android (https://github.com/react-native-community/jsc-android-buildscripts/issues/130#issuecomment-573957942).

if you believe you have some information to share around how to improve performance given these constraints, we'd be open to a pull request. but otherwise, matching/beating performance of webview in many cases isn't something we can do with expo-gl because the js engine is the bottleneck.

**Comment by Losses** [comment]
> the purpose of expo-gl isn't to beat out a webview but to integrate with native views and fit seamlessly into your app. as @nikki93 mentioned on the expo-three thread:
> 
> > The perf is (from my profiling a bit ago) mostly due to differences in like pure math in JS. We could theoretically enable JIT on Android JSC but I don't think we do right now
> 
> jsc on ios does not have jit enabled and there is no way to change that, and it's up to you if you want to do this on android ([react-native-community/jsc-android-buildscripts#130 (comment)](https://github.com/react-native-community/jsc-android-buildscripts/issues/130#issuecomment-573957942)).
> 
> if you believe you have some information to share around how to improve performance given these constraints, we'd be open to a pull request. but otherwise, matching/beating performance of webview in many cases isn't something we can do with expo-gl because the js engine is the bottleneck.

So the current problem is not related to this one? https://github.com/expo/expo/issues/12030

**Comment by brentvatne** [comment]
i'm not familiar enough with this particular module to say, but if you want to investigate and try to solve this or share information about the root cause it would be helpful!
