### ISSUE TITLE
Connection to Chrome debugger timed out

### ISSUE THREAD

**Issue by lucfranken** [expo/expo#124]
When testing on a physical device sometimes the debugger stops running.

I can confirm this by trying to refresh the debugger page in Chrome. It's just unavailable. This happens for example when you app crashes because of wrong imports while developing. 

Screen you get is like this one: http://stackoverflow.com/questions/37370916/react-native-error-connection-to-http-localhost8081-debugger-proxyrole-clie

No problem, can happen.

The problem is though: The Expo app on iOS seems to remember the state that it was debugging remotely. So I cannot get it back to working anymore. Also the "shake" gesture to disable it won't work again.

So then you re stuck. Even closing the app on the iOS device will  not work. It will remember the active status of the remote debugger.

Possible fixes I imagine:
- Ensure that the developer menu is always available even when your in state: "There was a problem running Expo"
- Allow somewhere to restart the debugger
- Restart the debugger automatically

On the simulator you can get out of this locked position by: Removing the Expo app from the iOS device. Then it will re-install it which fixes it. See: http://stackoverflow.com/a/41781232/1177905

**Comment by jesseruder** [comment]
Thanks for the report @lucfranken. Unfortunately this is just how React Native works - it persists the settings in NSUserDefaults. We want to work on this in the future but it's a pretty large project to fix.

**Comment by lucfranken** [comment]
Thanks for the quick reply! Yeah it's quite common I guess, there should be a simple reset() in the beginning of running the app. So you can always start with a clean state.

Did not know it was stored in NSUserDefaults. Any idea whether I would be able to override that?

Then I can fix it in my local app. I found things like: https://github.com/wwayne/react-native-user-defaults.

**Comment by terribleben** [comment]
The reason it uses NSUserDefaults is because changes to some dev tools (e.g. remote debugging) require restarting your app. That's why they are not designed to reset when you restart.

Longer term we can change the implementation such that the Expo kernel persists these settings, rather than your app itself.

**Comment by lucfranken** [comment]
Clear!

I though (before the new menu was launched in version 16) I was able to shake (while seeing the error) to disable remote debugging. That allowed me to fix the behavior. 

With the new menu it seems impossible. Might that be the difference in my experience or is that nonsense?

**Comment by terribleben** [comment]
You can still shake to show the menu, but the menu will appear underneath the `RCTRedBox` window, so you should dismiss the RedBox. Let me know if you have issues with this. I will backlog a task to make this interface a bit more clear.

**Comment by lucfranken** [comment]
Thanks! I think this does not work when you get: expo encountered an error. Then shake doesn't work. 

Actually while developing that whole expo encountered an error message is not needed. It should just restart.

This happens for example when you have syntax or import errors while developing.

**Comment by cideM** [comment]
Same problem but if I hit "Dismiss" and then shake the device, I eventually get the popup that allows me to turn off remote debugging. But the shaking is a bit unreliable sometimes. Maybe I'm just shaking it wrong though.

**Comment by williamwlchan** [comment]
I get a similar problem but the error message shown on the ios simulator is different. Everytime I enable Debug JS Remotely, then I get this error. In order to fix it, I have to reset content of the simulator or reinstall the expo app on the simulator but cannot enable debug anymore.
![screen shot 2017-07-22 at 11 46 19 am](https://user-images.githubusercontent.com/27396994/28488023-806a01c0-6ed3-11e7-8c56-2a8071ea12ed.png)

Any ideas?

**Comment by LaszloDev** [comment]
@williamwlchan Try updating to the latest version of expo and xde. This did resolve the BatchedBridge issue see #321

**Comment by williamwlchan** [comment]
@LaszloDev I updated to the latest version of expo client and did not get this error. However, when I put my debug mode on, the app is popped out to the iphone main screen.

**Comment by LaszloDev** [comment]
I did had a similar issue too. Try to find out at what function call the app crashes with some console loggs in the debugger.

**Comment by Dayjo** [comment]
Thought I'd screwed myself over here setting the remote debugger then it just permanently erroring. Shaking to bring up the menu and disable the remote js debugger solved it for me.
