### ISSUE TITLE
[Beta][Android][Lottie] Can't build APK with lottie-react-native

### ISSUE THREAD

**Issue by wawrzy** [expo/expo#12409]
### Summary

Can't build APK with lottie-react-native

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0-beta.1 => 41.0.0-beta.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Build an APK for and that using lottie-react-native on the SKD 41

Hello,

I'm unable to build an APK on the new SDK 41 (iOS build is OK) because of `lottie-react-native` (everything is OK without it), I try several times and the error isn't consistent (see my screens).

Edit 1:
I finally managed to build my APK after upgrading my expo-cli to 4.3.4 but sometimes it still fail with the same error

<img width="1236" alt="Screenshot 2021-04-03 at 01 27 12" src="https://user-images.githubusercontent.com/13482923/113461168-cc724200-941b-11eb-8fd7-3f43745f50d3.png">
<img width="1247" alt="Screenshot 2021-04-03 at 01 27 23" src="https://user-images.githubusercontent.com/13482923/113461169-ce3c0580-941b-11eb-820e-2ed301496813.png">
<img width="1230" alt="Screenshot 2021-04-03 at 01 27 34" src="https://user-images.githubusercontent.com/13482923/113461172-cf6d3280-941b-11eb-9033-66baabee9067.png">

**Comment by cruzach** [comment]
Hi! Can you share the link to your build page? That way we can take a look at the full logs

**Comment by cruzach** [comment]
@wawrzy I just built an APK on SDK 41 with `lottie-react-native` installed and it succeeded
