### ISSUE TITLE
Cannot load project on expo client on iPhone 5s

### ISSUE THREAD

**Issue by ethanyuwang** [expo/expo#1240]
I recently updated my project's expo version to SDK v24.0.0 and it works fine on my expo client on iPhone X and Pixel. However, it says ""This experience uses an unsupported version of Expo (SDK 24.0.0). You may need to update Expo." (code undefined)" when I tried to load it on iPhone 5s

The expo client on iPhone 5s has already been upgraded to the latest version. What could be causing this problem?

**Comment by ide** [comment]
What version of the Expo Client do you have in your 5S? You can find out by opening the Expo Client app and then looking for “Client version” on the home screen and tap it to copy to clipboard.

**Comment by ethanyuwang** [comment]
I just found out the expo client actually wasn't the latest version. Because iOS version was out of date, expo client was the last compatible version for iOS 8
