### ISSUE TITLE
I've faced a problem in download #apk file of #expo

### ISSUE THREAD

**Issue by Ali8484** [expo/expo#1241]
https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40 ali84%2Fgif-5dfa5989-f530-11e7-a256-0a580a782c2f-signed.apk

The browser show me this error : - 
---------------------------------------------------
This XML file does not appear to have any style information associated with it. The document tree is shown below.
-------------------------------------------------------------
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C6FE445F5D30F2B5</RequestId>
<HostId>
SnFe7dQooXpD+D+UxF9GWiQZAaInLrHRL7ep0nykjfiS/b/fuO080BmoBilFajL/HDWKL3WSf+Q=
</HostId>
</Error>

**Comment by Ghostaunt** [comment]
there is a incorrect whitespace in your link : https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android/@ali84/gif-5dfa5989-f530-11e7-a256-0a580a782c2f-signed.apk
