### ISSUE TITLE
Expo Vector Icons with Typescript gives error when passing string value

### ISSUE THREAD

**Issue by ranka23** [expo/expo#12416]
### Summary

After upgrading to the latest Expo version, 40.0.0, I receive type errors on the name property for the vector icons. MaterialCommunityIcons especially. Those are the icons I've used throughout the app.
Error Message:
Type 'string' is not assignable to type '"function" | "contain" | "repeat" | "details" | "head" | "iframe"...

While its a good step ahead to add types for the allowed values. It throws the above typescript error if you provide values conditionally or if you pass object keys with valid name types, because the object key is of type string.
```
<MaterialCommunityIcons
    name={activeTab === item.name ? item.activeIcon : item.icon}
    size={Size.medium}
    color={Color.black}
 />
```
Here the name throws a type error in VSCode. Also, if you create custom components with icons in them and try to pass name to the icons from the parent component, this problem surfaces. I cannot extend the name types to my custom component because its huge.

It's really annoying to add @ts-ignore everywhere. In case, I'm doing something wrong and this shouldn't occur any guidance would be much appreciated.

Thanks.

Sharing a screenshot below:

![Screenshot from 2021-04-05 17-48-32](https://user-images.githubusercontent.com/35439798/113578706-daed7300-9640-11eb-9465-07488141ee61.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

**Comment by awinograd** [comment]
@ranka23, here are a couple of typescript tips which may be helpful. 

For `    name={activeTab === item.name ? item.activeIcon : item.icon}`, you can go to the definitions of activeIcon and icon and do something like:

```ts
const item = { activeIcon: 'check' as const, icon: 'menu' as const };
```

If you have a custom component that forwards an icon prop along to the vector icon component you could use the following when declaring your type:

```ts
type CustomComponentProps = {
  icon: React.ComponentProps<typeof MaterialCommunityIcons>['icon']
}
```

**Comment by ranka23** [comment]
@awinograd   Thank you so much for your suggestions. The second suggestion was particularly helpful. I'll close the issue.
