### ISSUE TITLE
[expo-location][Android] Leaving startLocationUpdates to run in the background and terminating the app causes a double bundle load and execution when relaunching

### ISSUE THREAD

**Issue by mogery** [expo/expo#12415]
### Summary

If I do a `startLocationUpdatesAsync`, kill the app, and then relaunch it, the app's bundle will be loaded twice and executed at the same time, causing race conditions, crashes, etc.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.1

### Environment

  Expo CLI 4.3.4 environment info:
    System:
      OS: Linux 5.11 Pop!_OS 20.10
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.22.0 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 7.8.0 - /usr/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Demo repo: [link](https://github.com/mogery/el-dl-repro)

Steps to reproduce:
 * Create expo app
 * Eject
 * Set up expo-locations (with permissions for background location updates)
 * Define dummy task (it doesn't matter what it does, can just log params)
 * Start location updates, and don't stop it
 * Build and run for Android
 * Kill app, then restart it
 * Repeat previous step until you can see the bundle being loaded twice from the bundler (note: this behavior also happens on release builds, but it's not as visible since there is no bundler)

This occurs on both Android Q and R. Did not test on previous versions.

**Comment by mogery** [comment]
Sorry, I forgot to upload the demo repo at first. Should be up now.

**Comment by mogery** [comment]
Note for others: [this package](https://github.com/darron1217/react-native-background-geolocation) does not collide with expo-location and does not exhibit this bug. We switched to it temporarily.

**Comment by hungtrn75** [comment]
Same problem. Someone can help that issue?

**Comment by juanoude** [comment]
I had a similar issue, it was the lack of background location permission in the app.json. Beggining with SDK 40, expo doesn't declare this permission by default anymore. Then, everytime the app was closed, when it opens again it crashes, and do not work anymore until reinstallation.
