### ISSUE TITLE
[expo-av][Android] onPlaybackStatusUpdate called twice, first with correct data after with incorrect data

### ISSUE THREAD

**Issue by mtroskot** [expo/expo#12427]
### Summary

When using the same component for playing multiple videos, onPlaybackStatusUpdate gets called multiple times.
When playing the first video everything works fine, after switching to next onPlaybackStatusUpdate is called twice.
First callback contains correct data, second one always returns
`
 {
  "androidImplementation": "SimpleExoPlayer",
  "isLoaded": false,
}
`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 3.27.4 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    SDKs:
      Android SDK:
        Android NDK: 23.0.7123448-beta1
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Reproducible demo:
https://snack.expo.io/@trokiize/video-loading

**Comment by AdamJNavarro** [comment]
Hey @mtroskot, I ran your Snack on my Galaxy 8 device and am unable to reproduce your issue. Can you let me know what device(s) you've been able to reproduce the issue on?

<img width="1111" alt="Screen Shot 2021-04-06 at 11 12 19 AM" src="https://user-images.githubusercontent.com/8992878/113743292-20ee1980-96c9-11eb-8d63-28804d58560b.png">

**Comment by mtroskot** [comment]
@AdamJNavarro 
I did test it on Android Emulator API_23 & API_30 and on my Xiaomi A7. On all three devices and I can reproduce it.
Here the video of the bug with logs visible.
https://user-images.githubusercontent.com/26821326/113773449-5412c600-9726-11eb-868f-5b5c7b5a947d.mp4

**Comment by Gotemperor** [comment]
It is really unpleasant how you close issues like this one without any answer.
I am having same issue, I've been struggling  with it for two days.
Any help?

**Comment by ramzitannous** [comment]
any solution here ?

**Comment by jigneshCoderOceans** [comment]
I got the same issue

**Comment by Rickson298** [comment]
same issue here
