### ISSUE TITLE
Expo crashing issue with wrong uri in ImageManipulator

### ISSUE THREAD

**Issue by JegoYann** [expo/expo#1242]
Hello folks,
Thanks for a great work on expo !

By error, i used a wrong `uri` in `ImageManipulator.manipulate` and it makes expo crashes.

```
let image = await ImagePicker.launchImageLibraryAsync();
let resizedImage = await ImageManipulator.manipulate( image, // BAAAAAAD
[{ resize: { width: 200, height: 200 } }],
{ compress: 1, format: 'png', base64: true });
```

This code is crashing expo app.
Of course, using `image.uri` is working nicely.

**Comment by terribleben** [comment]
@aalices maybe we can just add a check here to avoid hard crashing when the wrong type is passed?
