### ISSUE TITLE
Text Appears Light Grey in Android 

### ISSUE THREAD

**Issue by ramdhanymf** [expo/expo#12424]
### Summary

When running yarn android, default text color appears grey instead of black. modifying styles.xml in Android results nothing, no changes happens. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.3.4 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Steps:
1. Create freshly new expo bare workflow project by running expo init, select bare minimal project
2. run yarn start
3. run yarn ios && yarn android

and walla, text appear grey on Android and black on iOS. Try change the default color on Android by modifying android:textColor in styles.xml file but no result, no changes happens.

**Comment by AdamJNavarro** [comment]
Hey @ramdhanymf, are you able to correctly change the styles with a vanilla react native project?

**Comment by ramdhanymf** [comment]
> Hey @ramdhanymf, are you able to correctly change the styles with a vanilla react native project?

Hi, thank u for resoonding! Yes I can, but I would like to set global default font color. Besides that, the app that i currently working has been big enough, so it may not efficient to change the font color one by one.

**Comment by byCedric** [comment]
@ramdhanymf yes, that's correct! If you are using the bare workflow, you get access to Android native configuration including things like `AndroidManifest.xml` and you can change the global configuration for text color too (as you mentioned).

**Comment by ramdhanymf** [comment]
> @ramdhanymf yes, that's correct! If you are using the bare workflow, you get access to Android native configuration including things like `AndroidManifest.xml` and you can change the global configuration for text color too (as you mentioned).
> 
> One thing that I can think off might be the "aggressive" dark mode on some MIUI devices. What device are you using?

Yes, absolutely! However, that was not what actually happens. I have used three different devices such as Samsung A8, and two other Pixel and Pixel 2 emulators, but still results the same across all devices. Those three devices also do not use any dark mode theme or whatsoever. But it works perfectly on iOS. 

Have you ever tried creating a fresh Expo bare project with the current latest version of expo-cli and results the same as I have? I wonder if other people have the same result as me.

**Comment by peroh** [comment]
Not sure if this is related or not, but I'm using managed builds and am having this issue after updating to SDK41 and using EAS builds.

**Comment by peroh** [comment]
@ramdhanymf Are you using styled components by any chance? The issue only appears to be happening for me when I use the `styled-components/native` package e.g.

```js
const Title = styled.Text``
```

But changing to this fixes it for me

```
import { Text } from 'react-native'

const Title = styled(Text)``
```

**Comment by ramdhanymf** [comment]
> @ramdhanymf Are you using styled components by any chance? The issue only appears to be happening for me when I use the `styled-components/native` package e.g.
> 
> ```js
> const Title = styled.Text``
> ```
> 
> But changing to this fixes it for me
> 
> ```js
> import { Text } from 'react-native'
> 
> const Title = styled(Text)``
> ```

Hi, thank you for responding. Nope, I did not use any of that, neither styled-component nor build using EAS Build Service. Have you ever tried to create a freshly new project using Expo Bare project and run it using **yarn start** and then **yarn android**?

**Comment by peroh** [comment]
> Hi, thank you for responding. Nope, I did not use any of that, neither styled-component nor build using EAS Build Service. Have you ever tried to create a freshly new project using Expo Bare project and run it using **yarn start** and then **yarn android**?

Thought it might be a long-shot. Nope I've steered clear from ejecting as I love the managed process so much!
