### ISSUE TITLE
Problems with Expo-Contacts API

### ISSUE THREAD

**Issue by PietroFalcetti** [expo/expo#12426]
### Summary

Hello everyone, I'm experiencing issues with the method 'Contacts.addContactAsync(Contact)' and 'Contacts.presentFormAsync(contactID, Contact, FormOpts).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 27, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Simply try to add a contact and update it via Expo-Contacts API.

I'm trying to add a new contact :

```
const contact = {
            [Contacts.Fields.FirstName]: 'Pietro6',
            [Contacts.Fields.LastName]: 'Falcetti5',
            [Contacts.Fields.PhoneNumbers]: [
              {
                number: '3456789015',
                isPrimary: true,
                digits: '3456789015',
                countryCode: '+39',
                id: 12334,
                label: 'Cell'
              }
            ],
            [Contacts.Fields.Emails]: [
              {
                email: 'first.second@gmail.com',
                isPrimary: true,
                id: 1234,
                label: 'Gmail mail'

              }
            ]
}
```

with 
`const contactID = await Contacts.addContactAsync(contact)`

The contact is correctly added (Firstname and lastname), but phone number and email are missing when I check in the Contacts App on my Android Tablet. 

Trying to update a contact by ID, it always open a modal with a form for editing the contact. Is there a way to update a contact automatically from code, without open the modal on the screen ? 
`await Contacts.presentFormAsync(contactID, { [Contacts.Fields.FirstName]: 'PietroUp' })`

if would like to replace the Firstname without asking the user to compile the form via modal.

Hope someone could help me! 

Thank you!

**Comment by AdamJNavarro** [comment]
Hey @PietroFalcetti, on Android you're unfortunately only able to use presentFormAsync to perform updates to Contacts. As for the `addContactAsync` issue, could you please provide a repro case of this? Ideally in the form of a public github repo that we can clone and build to test, seeing as we can't quickly test in Expo Go since the `WRITE_CONTACTS` permission is not in the manifest.

Cheers,
Adam

**Comment by PietroFalcetti** [comment]
Hello @AdamJNavarro ! 
I was wrong with the Contact object ... the id field in the PhoneNumber object must be a string ... I used an int! 

It correctly works!

Thank you anyway for the response!
