### ISSUE TITLE
Constants.manifest.extra is undefined in web

### ISSUE THREAD

**Issue by ericwooley** [expo/expo#12430]
### Summary

Constants.manifest.extra is undefined in web only. Possibly a regression of https://github.com/expo/expo/issues/4784

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40.0.0

### Environment

  Expo CLI 4.3.4 environment info:
    System:
      OS: Linux 5.11 Arch Linux
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    npmPackages:
      @expo/webpack-config: ~0.12.45 => 0.12.64 
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/ericwooley/rolledex/tree/d2f911885b5afef68e76e89a2ff85abc4f54dfc4

This is a bit of an advanced setup, with Nx.dev. Nothing too crazy though. webpack.config.js is modified as well.

### web
![image](https://user-images.githubusercontent.com/1930227/113755758-8b9d5600-96c5-11eb-9c01-2092e281e1fe.png)

### android
![image](https://user-images.githubusercontent.com/1930227/113756056-d61ed280-96c5-11eb-9fa8-f6dbc467b1fc.png)

**Comment by ericwooley** [comment]
I am able to get this working in a fresh `expo init`, so i am thinking I messed up the config somewhere. Still investigating, will re-open if it is an expo problem after all.

**Comment by ericwooley** [comment]
@byCedric I figured out what causes the issue.

If you customize web, and move your app.json, web doesn't show up.

Created a new repo for reproduction here:

https://github.com/ericwooley/no-web-extra-expo

**Comment by toshihr** [comment]
Related
https://github.com/expo/expo-cli/issues/88
https://github.com/expo/expo/issues/11888

https://github.com/expo/expo/blob/master/packages/expo-constants/CHANGELOG.md
Expo-constants will update mamifest handling at SDK 43

**Comment by ericwooley** [comment]
As far as I know, this is still an issue...

**Comment by arsalan-arshad** [comment]
I also insert this "transform-inline-environment-variables"   plugins in babel.config.js

But still not working in expo web. Ios android is fine with constants

**Comment by benlutz** [comment]
Just ran into the same issue. Anybody found a fix or workaround for this yet?
iOS and Android works as intended, on web `Constants.manifest` is empty.

**Comment by thefinnomenon** [comment]
Still an issue. The only solution I have found is to customize the webpack configuration, using dotenv to set your variables there.

**Comment by benlutz** [comment]
> Still an issue. The only solution I have found is to customize the webpack configuration, using dotenv to set your variables there.

Would you be able to share your webpack config with us? We haven't managed to come up with a satisfying workaround yet.

**Comment by thefinnomenon** [comment]
@benlutz I wrote up what I did last year here. Basically I avoided using Constants & just used env
https://finnternet.com/dev/blog/expo-starter-initial-setup
I was wrong about the webpack config. The babel inline dotenv setup will work with web as long as you don't customize your webpack config.

**Comment by LordParsley** [comment]
Thanks, @robertoyoc 👍

I used your approach combined with [dotenv](https://www.npmjs.com/package/dotenv) to load env vars from `.env` the way they do in the `tsconfig` version of this [Expo guide](https://docs.expo.dev/guides/environment-variables/#from--appconfigjs).

**Comment by dmarcucci** [comment]
> If you customize web, and move your app.json, web extra doesn't show up.

@ericwooley By "customize web", I assume you mean with `webpack.config.js`?

I do not have a `webpack.config.js` file in my project and did not move my `app.json`, but I was using `transform-inline-environment-variables` as a plugin in my `babel.config.js` (as I was taking the [Using Babel to "replace" variables](https://docs.expo.dev/guides/environment-variables/#using-babel-to-replace-variables) approach before switching to using the app manifest). With this setup, however, I was having the same issue.

Once I removed the plugins from `babel.config.js`, I was able to use the app manifest in web. `transform-inline-environment-variables` was the only plugin I'm using, so this works fine for me as I'll be uninstalling `babel-plugin-transform-inline-environment-variables` from my dev dependencies entirely.

Perhaps the plugin itself was customizing web under the hood, but it's not clear. Also not sure if this fix is feasible for others with additional plugins, but just putting it out there in case somebody runs into a similar issue.

**Comment by dmitryame** [comment]
same here, the expo documentation is either confusing or wrong.
In my app.config.js i have:
```
export default {
  expo: {
...
    extra: {
      API_URI: process.env.API_URI,
      API_KEY: process.env.API_KEY,
    },
...
```

In consts.js :
```
import Constants from 'expo-constants'
...
export const { API_URI, API_KEY } = Constants.manifest.extra
```
When I export API_URI and API_KEY env vars on my local box, `expo start` works just fine (does not work without the exports which is expected).

When I create build with `eas build` and submit it to the app store -- the app in the test flight can never connect to the API as it can't find the config values. I have created the secrets via expo UI -- nada.

It does not have to be this complicated. What am I missing?
Please help!

**Comment by dmitryame** [comment]
Got my answer here https://github.com/expo/eas-cli/issues/1265#issuecomment-1301525320
I do wish expo simplified/cleaned their documentation a bit and made like one simple example which just works out of the box instead of providing tons of information where it's so easy to miss Constants.expoConfig vs Constants.manifest

**Comment by bombillazo** [comment]
Im thinking the issue has something to do with webpack. how does one customize the webpack config so the app.config.js is loaded?

**Comment by AizenSousuke** [comment]
Any working examples?

**Comment by EvanBacon** [comment]
Constants manifest does not work in the following web-cases:
- Custom Webpack configurations, e.g. configurations that do not use `@expo/webpack-config`.
- The Next.js Adapter.
- Metro web projects that aren't using Expo Router (specifically the Babel plugin).

**Comment by kmalyshev** [comment]
Expo v48, having the same issue on web. However i'm using metro instead of webpack

**Comment by dylanrandle** [comment]
@EvanBacon I'm finding that `Constants.manifest`, `Constants.manifest2` and `Constants.expoConfig` are all empty (`{}`) using the default Webpack configuration (`@expo/webpack-config`) in Expo `47`.

I am using the `transform-inline-environment-variables` approach to using environment variables in Expo.

**Comment by kmalyshev** [comment]
Managed to resolve the issue on web using the following babel plugin:

`module.exports = function (api) {
  api.assertVersion(7);

  return {
    visitor: {
      Identifier(path, { file }) {
        const filePath = file.opts.filename;

        if (filePath.endsWith('ExponentConstants.web.js')) {
          if (path.node.name === 'APP_MANIFEST') {
            const isEnvVar =
              path.parentPath.isMemberExpression() &&
              path.parentPath.node.object.object.name === 'process' &&
              path.parentPath.node.object.property.name === 'env';
            if (isEnvVar) {
              console.log(
                'Found process.env.APP_MANIFEST:',
                path.parentPath.parentPath.node,
              );
              const manifestString = JSON.stringify(getAppManifest());
              path.parentPath.replaceWith(
                api.types.callExpression(api.types.identifier('JSON.parse'), [
                  api.types.stringLiteral(manifestString),
                ]),
              );
            }
          }
        }
      },
    },
  };
};
`

getAppManifest() is a function that reads my app.json, third party files and assembles the final merged manifest (like in app.config.ts). I won't paste it here

**Comment by ericwooley** [comment]
I don't use it anymore, but it seems like this is still open

**Comment by oftoapp** [comment]
I'm on 49 and I still getting the same error

**Comment by robbporto** [comment]
This is still happening on both 48 and 49.

**Comment by tehmann83** [comment]
Same as above

**Comment by MateuszBukowski93** [comment]
same here
