### ISSUE TITLE
When I detach and build in Android Studio, I get a RuntimeException: Didn't find class

### ISSUE THREAD

**Issue by kkotkkio** [expo/expo#1243]
iOS(Xcode) Building is well. 
But in Android(Android Studio), be terminated on runtime. (when be install and just started)

Error Message below.
`java.lang.RuntimeException: Unable to instantiate application host.exp.exponent.MainApplication: java.lang.ClassNotFoundException: Didn't find class "host.exp.exponent.MainApplication" on path: DexPathList[[zip file "/data/app/com.zzieut.zzim-2/base.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.zzieut.zzim-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.zzieut.zzim-2/lib/arm, /vendor/lib, /system/lib]]`

**Comment by RevanScript** [comment]
The same problem

**Comment by priezz** [comment]
Confirm for Android 5.0 and 5.1. For 6.0 and newer problem does not exist for me.

**Comment by WilliamAnputra** [comment]
I got the same problem if i run on android 5.0, but it worked on android > 6.0

**Comment by fxfactorial** [comment]
Hi. This is a known and occasional issue on Android API <= 21.

**Comment by YKSing** [comment]
I am having the same problem with Android 5.1.1

**Comment by WilliamAnputra** [comment]
@fxfactorial  any updates on this bug?

**Comment by fxfactorial** [comment]
Not right now.

**Comment by jesseruder** [comment]
This shouldn't happen when you make a prod build, it's only an issue in development on Android <= 21

**Comment by WilliamAnputra** [comment]
@jesseruder any updates on when it'll be fixed?

**Comment by ljuborados** [comment]
Having the same problem while targeting API 23, or API 26.
App closes as soon as it's launched, with the same error message.
It literally worked 3 days ago, no changes to the android files.

**Comment by safilsunny** [comment]
any updates?

**Comment by jesseruder** [comment]
> Having the same problem while targeting API 23, or API 26.

This is not related to targetSdkVersion. This should only happen in debug builds with minSdkVersion < 21. We don't have a great way of fixing this for now, but it does not affect prod builds. As long as you develop with minSdkVersion set to 21 it should be fine.

**Comment by dorelm** [comment]
I get this error even with prod release (I use build variant prodRelease).
I use expo sdk 25.0.0, minSdkVersion set to 21 in app gradle file, and running android 5.0.0.

What an I missing? 

Thanks!

**Comment by jesseruder** [comment]
@dorelm did you change the proguard config or any of the build.gradle files? Does this happen for you on a project immediately after `exp detach`?

**Comment by pavkoo** [comment]
I did not found any  host.exp.exponent.MainApplication or host.exp.exponent.MainActivity at my apk{ classes*.dex} file

**Comment by vjsingh** [comment]
I am getting this error in development mode on API level 28. App randomly shuts down upon startup with the same error

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. Recent posts indicate this remains an issue, could one of you please open a new issue with a repro case? We'll get it appropriately assigned and we'll be happy to investigate.

Cheers,  
Adam

**Comment by borie88** [comment]
So closed with no feedback?

**Comment by AdamJNavarro** [comment]
Hey @borie88,

As my message above indicates, this post was closed in an effort to clean up our issues. Furthermore, we only actively support the 6 most recent SDK versions and this post is from a time pre-dating the last supported version. If you're encountering this issue on one of the supported SDK versions (26-32) I suggest creating a new issue with as much relevant information as you can rather than grave-digging old posts with comments that provide nothing of substance or use.

Cheers,
Adam
