### ISSUE TITLE
How to judge the installation and uninstallation status of the app?

### ISSUE THREAD

**Issue by fungmo** [expo/expo#12433]
## Description
I have a new version of apk to install, and the new file and database overwrite the old apk file and database. I know this may require me to edit the code to achieve. My idea is to find the status of apk uninstallation and installation, and then run the script to completely delete the old apk file and database.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

```javascript
Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.3, 24.0.3, 25.0.3, 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

```

## Steps To Reproduce
1.Determine the status of installation and uninstallation
2.Delete the files of the corresponding Android file system

## Expected Results
Users do not need to manually uninstall the old apk and then install the new apk, it can use the latest data file by directly installing the new apk.

Expected Results
Users do not need to manually uninstall the old apk and then install the new apk, it can use the latest data file by directly installing the new apk.

**Comment by cruzach** [comment]
Hi! This isn't a bug report so I'm closing the issue

Whenever a user installs a newer version of your APK (provided the signing signatures match), it will replace the old APK automatically, so you shouldn't have to write any special code for this
