### ISSUE TITLE
Video.setStatusAsync({shouldPlay:false}) updates the isBuffering to true on IOS 9.3

### ISSUE THREAD

**Issue by RealDeanZhao** [expo/expo#1244]
Hi, 
I meet a problem with the [custom expo videoplayer](https://github.com/expo/videoplayer/blob/master/index.js).

**ENV:**
**EXPO 24**
**iOS 9.3**

Try to pause a video by calling **setStatusAsync({shouldPlay:fase})**, the playbackStatus is set incorrectly:
`
{
isPlaying: false,
isBuffering: true
}
`

After pausing the video,  I cannot click the 'PlayIcon' since the isBuffering=true and the spinner won't get disappeared...

Besides, The playbackStatus is ok with iOS11
`
{
isPlaying: false,
isBuffering: false
}
`

Thank you!

**Comment by sjchmiela** [comment]
Hi @RealDeanZhao! Unfortunately I'm not able to reproduce error you described. Could you please provide a Snack demonstrating the bug?

_Note: It is possible that although `shouldPlay` is being set to `false` the player tries to buffer more data. However, this should not take too long, depending on the speed of your network._

**Comment by RealDeanZhao** [comment]
@sjchmiela Thanks for you reply. This can only be reproduced on ios 9.3 no matter it is a simulator or a real device.  My network is good and everything is OK on ios 11.
![untitled](https://user-images.githubusercontent.com/6734408/35049440-fa950f1e-fbda-11e7-88dc-a3a254cbdb2d.gif)

**Comment by RealDeanZhao** [comment]
@sjchmiela [snacks](https://snack.expo.io/@zestxjest/unnamed-snack)

**Comment by sjchmiela** [comment]
We were basing `isBuffering` status property only on [isPlaybackBufferEmpty](https://developer.apple.com/documentation/avfoundation/avplayeritem/1386960-isplaybackbufferempty), I submitted a PR that will also take into account [isPlaybackLikelyToKeepUp](https://developer.apple.com/documentation/avfoundation/avplayeritem/1390348-isplaybacklikelytokeepup) (which in that case was `true`, for which we will return `isBuffering = false`). Thanks for the bug report!

**Comment by RealDeanZhao** [comment]
@sjchmiela Great, thank you so much.
