### ISSUE TITLE
[expo-auth-session] Blank screen after authorizing with facebook

### ISSUE THREAD

**Issue by CaioMars** [expo/expo#12440]
### Summary

When attempting to log in with Facebook in development (Expo Go), user authorizes app to access Facebook's data then the user is redirected and a blank screen lingers on. No response is ever received. When the request is cancelled I get a response of type `dismiss`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

 Expo CLI 4.3.4 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: ^16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

        // FACEBOOK SIGN-IN
        const [
            requestFacebookAuth,
            responseFacebookAuth,
            promptFacebookAuthAsync,
        ] = Facebook.useAuthRequest({
            clientId: "{FBID}",
            redirectUri: "fb{FBID}://authorize",
            responseType: AuthSession.ResponseType.Token,
        });

        React.useEffect(() => {
            console.log(responseFacebookAuth);
            if (responseFacebookAuth?.type === "success") {
            const { access_token } = responseFacebookAuth.params;

            const credential = firebase.auth.FacebookAuthProvider.credential(
                access_token
            );
            // Sign in with the credential from the Facebook user.
            // clientFirebase.auth.signInWithCredential(credential);
            }
        }, [responseFacebookAuth]);

**Comment by Jamedjo** [comment]
@CaioMars The app will return `dismiss` whenever you return to the app before the redirect handler is called. 

From the [docs](https://docs.expo.io/guides/authentication/#facebook) it sounds like the Expo Go client isn't supported: 

> Native auth isn't available in the App/Play Store client because you need a custom URI scheme built into the bundle.

For standalone/bare you'd want to verify that the `redirectUri: "fb{FBID}://authorize"` value appears in the manifest, then that facebook had been configured to redirect there.

**Comment by CaioMars** [comment]
Ok, thanks for the response. How do I add that to the bundle, do you know? I am not familiar manipulating `Info.plist.

Right now I have:

    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>{FBID}</string>
            </array>
        </dict>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>{BUNDLE_ID}</string>
            </array>
        </dict>
    </array>

**Comment by Jamedjo** [comment]
@CaioMars Are you having the same issue on iOS as on Android? The issue description also mentions both managed (Expo Go) / SDK 40 and bare workflow: are you using both?

Have you got an FBID from Facebook and added `facebookScheme: 'fb<YOUR FBID>'` to your app.config.js/app.json?

I'm unfamiliar with Info.plist too, but guess the ejected/built version could be generated using [packages/expo-facebook/plugin/src/withFacebookIOS.ts](https://github.com/expo/expo/blob/935036fba802f6be9343513cd348481b06c223a6/packages/expo-facebook/plugin/src/withFacebookIOS.ts).
