### ISSUE TITLE
Weekly notifications shows multiple times

### ISSUE THREAD

**Issue by dellwatson** [expo/expo#12447]
### Summary

I've set a weekly notification for each morning, monday-saturday, all with same time,
but what i got are 6 notifications for each morning on monday-saturday,
not sure what's wrong, i set the notif on app.js

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40

### Environment

 Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
...
import * as Notifications from "expo-notifications";

NotifInit();
notificationListener();
responseListener();

// this is the notif schedule 
Notifications.scheduleNotificationAsync({
  content: {
    title: "Selamat pagi",
    body: "",
    sound: true,
  },
  trigger: {
    weekday: 2, //MONDAY different day for each Notif
    hour: 4,
    minute: 59, 
    repeats: true,
    channelId: "weekly2", //not sure, seems is not important
  },
});
Notifications.scheduleNotificationAsync({
  content: {
    title: "Selamat pagi",
    body: "",
    sound: true,
  },
  trigger: {
    weekday: 3, //TUESDAY different day for each Notif
    hour: 4,
    minute: 59, 
    repeats: true,
    channelId: "weekly3",
  },
});

... //continue until SATURDAY
Notifications.scheduleNotificationAsync({
Notifications.scheduleNotificationAsync({
Notifications.scheduleNotificationAsync({
Notifications.scheduleNotificationAsync({


export default function App() {
  useEffect(() => {
    registerForPushNotificationsAsync();
    return () => {
   Notifications.removeNotificationSubscription(notificationListener);
      Notifications.removeNotificationSubscription(responseListener);
    };
  }, []);
  const isLoadingComplete = useCachedResources();
  const colorScheme = useColorScheme();
  if (!isLoadingComplete) {
    return null;
  } else {
    return (
      <SafeAreaProvider>
...
```

Do i set it wrong ?  I set in App.js, not sure what's happening, 
i got 6 notifs from monday-saturday instead of 1 notif from monday-saturday

**Comment by cruzach** [comment]
My guess is you're just accidentally running the logic to "schedule" notifications multiple times. For instance, in your current code, each time your save and the app hot reloads, it'll schedule the notifications again. You should either provide an `identifier` so that subsequent calls rewrite the previous one, or be more selective about when you are calling that logic.

By the way, you may want to just use a daily notification trigger- https://docs.expo.io/versions/latest/sdk/notifications/#dailynotificationtrigger

**Comment by dellwatson** [comment]
@cruzach byt why would it be in the same day? 
i set up each notifications for different day with the same time,

i cant use dailynotificationtrigger, since i dont know how to block for specific day (eg: for sunday),
i tried and it is also calling multiple times too.

is the `identifier` same as `channelId` ? 
i will look getAllScheduledNotificationsAsync and see what's the problem, thankyou in advance for the reply

**Comment by cruzach** [comment]
> i set up each notifications for different day with the same time

Yes but you're running that code every time the bundle loads, so it's setting them multiple times. `identifier` is not the same as `channelId`. It is the unique ID of that notification, so if you schedule another with the same identifier, it will overwrite the previously scheduled one
