### ISSUE TITLE
[docs] Android notifications setup

### ISSUE THREAD

**Issue by KurtMar** [expo/expo#12450]
### Summary

I would like to see a note about enabling FCM for Android on the page https://docs.expo.io/versions/latest/sdk/notifications/ under the Android section.

I had two iOS Expo apps with working notifications. I spent many hours trying to figure out why my Android version was not receiving notifications. I finally discovered this page https://docs.expo.io/push-notifications/using-fcm/ and even though I had everything else setup correctly due to my use of firebase in general, I had not uploaded my Server Credentials to Expo.

I'm confident there are many developers who think that the Android notifications will work out of the box just like with iOS.

This would have saved me from buying a $100 test device and I could have relied on my Android testers and simulator. 😄

### Link to the related docs page

https://docs.expo.io/versions/latest/sdk/notifications/

**Comment by cruzach** [comment]
@KurtMar what & where do you think we can add to the docs to clear this up? When you send a notification and haven't uploaded your FCM server key, we return an error saying:
```
Failed to authenticate with the FCM server. Ensure the FCM server key you uploaded is correct.
```

**Comment by cruzach** [comment]
added in https://github.com/expo/expo/commit/40e22c1248e21599915759d5d839e173ef8546ab

**Comment by KurtMar** [comment]
I think that makes it extremely clear, thank you!
