### ISSUE TITLE
Update notificationBody in foreground service of startLocationUpdatesAsync

### ISSUE THREAD

**Issue by mushroomgenie** [expo/expo#12469]
I want to update the notificationBody in the foreground service option of startLocationUpdatesAsync. I am currently storing the latitude and longitude in state and setting the state using TaskManager, but the notificationBody is not getting updated as and when the location changes. Any help would be really appreciated. Major blocker. The location is being updated in the app and I am able to display the changes,I just want to keep updating the foreground notification as well.

### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by cruzach** [comment]
> Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?
> Yes

Closing this issue since we state any non-bug report issues will be closed

Questions like this are better suited for our Forums or Discord
