### ISSUE TITLE
[expo-gl] Memory Leak with createCameraTextureAsync()

### ISSUE THREAD

**Issue by valentinchelle** [expo/expo#12468]
### Summary

createCameraTextureAsync() creates memory leaks when reloading the component or just trying to destroy the texture. For instance, the RAM consumes 10MB more after each fast refresh.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40.0.0

### Environment

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.20.1 - /usr/local/bin/node
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: 0.64.0 => 0.64.0 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

[https://snack.expo.io/@overflozz/github-issue-gl-memory-leak](https://snack.expo.io/@overflozz/github-issue-gl-memory-leak)

Requires to have a camera and open the performance Monitor on expo. Just press several times the buttons "Start Extracting Texture" and "Clean Texture" and you will see the increase in memory in the RAM.

**Comment by feiwu77777** [comment]
I have had the same problem.

**Comment by brentvatne** [comment]
the fastest way to get this fixed is to open a pull request with tests :)

**Comment by valentinchelle** [comment]
> the fastest way to get this fixed is to open a pull request with tests :)

I don't have any solution for this problem, and I am not sure how I could write tests that are able to test memory leaks.

**Comment by brentvatne** [comment]
if you want to investigate a solution that would be appreciated too :) find the root cause, let us know

**Comment by thinhdaotrong** [comment]
any update this issue, I am having same problem
