### ISSUE TITLE
GIF doesn't animate once project is published

### ISSUE THREAD

**Issue by ccheever** [expo/expo#1246]
Some (or maybe all) animated GIFs animate properly in Snacks and in development but only show one frame statically after publishing a project.

https://forums.expo.io/t/gifs-do-not-animate-when-published-to-expo/6313

https://snack.expo.io/SJRlmF8NM1
vs
https://expo.io/@kicktheken/nyancat1

I've confirmed this with a separate repro.
https://exp.host/@ccheever/giftest

**Comment by kicktheken** [comment]
This seems to be fixed in Expo SDK v25.0.0

**Comment by mskuser1** [comment]
@brentvatne - in my case i'm using android version 9.
And i also tried a gif that you use (at least i think it's you) from a snack that you made

the gif :  https://media.giphy.com/media/xUOxf34uHq8VolxF7y/giphy.gif
the snack : https://snack.expo.io/rko5a7RyM

again works fine in development but when published it's just a normal image.

thanks in advance;
