### ISSUE TITLE
Android's windowSoftInputMode isn't configurable

### ISSUE THREAD

**Issue by ArsenyYankovsky** [expo/expo#1247]
Hello,

Right now it's hardcoded to adjustResize so my (and I think not only mine) breaks when this is enabled. As you can see tab bar is being covered:

![151579464286948658](https://user-images.githubusercontent.com/1508345/34897094-aa3e626e-f7ec-11e7-99e3-371b7f36ecbb.png)

The only way I've found to fix that is to build the apk, decompress it using apktool, change the AndroidManifest and compress it again which is probably not the best experience.

Can we have an option in the app.json for that?

**Comment by ArsenyYankovsky** [comment]
Unfortunately using apktool to fix that is not an option since I let expo handle signing process so I can't resign my apk again. Would be nice to have an option to get the keystore from expo website or something.

**Comment by ccheever** [comment]
Hi-

Unfortunately, you'd need to detach to change this.

More info here: https://forums.expo.io/t/how-to-set-android-windowsoftinputmode-adjustresize-in-android-manifest-file/587
