### ISSUE TITLE
Expo splash screen gets hidden even if preventAutoHideAsync is used on iOS (not expo or Android)

### ISSUE THREAD

**Issue by trajano** [expo/expo#12481]
### Summary

[[expo-splash-screen] `SplashScreen.preventAutoHideAsync()` no longer works in iOS · Issue #9286 · expo/expo (github.com)](https://github.com/expo/expo/issues/9286) a closed issue already sort of describes my issue.  However, I am using a managed workflow not bare.

The code which is based on the example functions correctly in Expo (even iOS expo) and Android, but on iOS release builds the splash screen gets hidden and I see the application trying to render too early.

I tried upgrading turtle-cli and expo-cli to the most recent versions and it is still occurring.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

```

  Expo CLI 4.3.4 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.4 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      npm: 6.14.6 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

It's hard to make it at the moment, because it needs to be in the released app.  It does not occur on Expo or Android (where I can just build an APK)

**Comment by RohovDmytro** [comment]
hey, it MIGHT be an issue I am facing couple of weeks now. I was simple ignoring it, but what I have experience is the error about being no able to hide a splash screen. Maybe because iOS is ignoring the auto hiding option.

```` 
"expo-splash-screen": "^0.9.0",
````

**Comment by trajano** [comment]
@RohovDmytro why did you put the package.json line?  Anyway I also tried upgrading to latest of expo-splash-screen as well.

**Comment by trajano** [comment]
My CEO actually had a crazy notion that may work.  Have the initial state for iOS show the splash screen or something similar to the splash screen on iOS rather than relying on Expo to handle it correctly.

**Comment by AdamJNavarro** [comment]
Hey @trajano, we recently updated our [example](https://docs.expo.io/versions/v40.0.0/sdk/splash-screen/#usage) in our docs that might help resolve the issue at hand here. It involves leveraging `onLayout` of your root View to avoid hiding the screen to early.

Cheers,
Adam

**Comment by trajano** [comment]
How recent was the change @AdamJNavarro  because I actually used the approach that was written there a few days ago which solved the behaviour on Android.

**Comment by trajano** [comment]
Just tested on my iOS device.  It seems that's the solution.  The examples needs to be updated so that the 

```
SplashScreen.preventAutoHideAsync()
  .catch(() => { /* reloading the app might trigger some race conditions, ignore them */ });
```

is executed Before the app is started.

Going to see if it has other issues with Android or Expo in a bit.

**Comment by trajano** [comment]
I had no complaints so far with Android and Expo but I think I should keep this open until the example gets updated.

**Comment by sajadghawami** [comment]
> Just tested on my iOS device. It seems that's the solution. The examples needs to be updated so that the
> 
> ```
> SplashScreen.preventAutoHideAsync()
>   .catch(() => { /* reloading the app might trigger some race conditions, ignore them */ });
> ```
> 
> is executed Before the app is started.
> 
> Going to see if it has other issues with Android or Expo in a bit.

i ve been having the same issue for quite some time now... on android it would work without a problem if you put it in a hook, but on ios it just wasnt working.

thank you!

**Comment by sajadghawami** [comment]
Still a problem though ...

**Comment by alexreyes** [comment]
Interesting.. 

If I put `SplashScreen.preventAutoHideAsync()` after `AsyncStorage.getItem()`, the splash screen will auto hide. Example (this code snippet does *not* work): 
```  
useEffect(() => {    
    async function prepare() {
         const log = await AsyncStorage.getItem('loggedIn');
         await SplashScreen.preventAutoHideAsync();
````

However, if I put `SplashScreen.preventAutoHideAsync()` before anything else, the splash screen will *not* auto hide. Example (this code snippet works): 

```  
useEffect(() => {    
    async function prepare() {
         await SplashScreen.preventAutoHideAsync();
         const log = await AsyncStorage.getItem('loggedIn');
````

I'm convinced this is a bug. Just chiming in to say I also experience this when testing on iOS

**Comment by hozjanmarko** [comment]
Also experiencing this issue

**Comment by trajano** [comment]
I think as I have noted over a year ago https://github.com/expo/expo/issues/12481#issuecomment-818387116 just call the function at the top level rather than letting useEffect handle it.

**Comment by OskarD** [comment]
> I think as I have noted over a year ago [#12481 (comment)](https://github.com/expo/expo/issues/12481#issuecomment-818387116) just call the function at the top level rather than letting useEffect handle it.

It's not working for me. It looks like it auto-hides the splash screen almost immediately on load. It only happens on iOS and never on Android

**Comment by yourjhay** [comment]
This is still an issue. not working on iOS, but working on android.

**Comment by marielawhaley** [comment]
This is still an issue

**Comment by rogoja** [comment]
If you are using expo-router, check this solution: https://github.com/expo/expo/issues/23958#issuecomment-1713448169

**Comment by rgomezp** [comment]
Still an issue. Not on expo-router

**Comment by maksim-romanov** [comment]
Same problem

**Comment by quememo** [comment]
same

**Comment by maksim-romanov** [comment]
Resolved to disable new Arch ))))

**Comment by uoon-dev** [comment]
same here

**Comment by front100** [comment]
Everything worked fine on Android  with  expo router and import * as SplashScreen from 'expo-splash-screen' until the latest updates
Now we need to import  SplashScreen  from expo-router itself

`import { SplashScreen } from 'expo-router';`

**Comment by Hosam-hsm** [comment]
I am facing this issue when using expo-splash-screen config plugin specifically. Experiencing this issue in iOS release build in real device only.

SplashScreen.preventAutoHideAsync(); is called in root layout outside the main component.

When Using:

```
  splash:{
    backgroundColor: "#216A4D",
    image: "./assets/splash-icon-dark.png",
  }  
```
in app config file, the splash screen waits for the hideAsync call as expected. 

But using the plugin:

```
[
      "expo-splash-screen",
      {
        backgroundColor: "#216A4D",
        image: "./assets/splash-icon-dark.png",
        dark: {
          image: "./assets/splash-icon-light.png",
          backgroundColor: "#232323",
        },
        imageWidth: 144,
      },
    ] 
```
as recommended now, is causing the splash screen to hide automatically before the hideAsync call.

```
"expo": "~52.0.30",
"expo-splash-screen": "~0.29.21",
"expo-router": "~4.0.17",
```

Tried importing Splashscreen from both "expo-splash-screen" and "expo-router" without success. Any help here?

**Comment by jaaywags** [comment]
I noticed if I had animations disabled (settings -> accessibility -> color and motion -> remove animations) then `SplashScreen.preventAutoHideAsync()` was not respected.
