### ISSUE TITLE
[expo-auth-session] Opening Redirect URI with promptAsync breaks Reddit Client IDs

### ISSUE THREAD

**Issue by dylmye** [expo/expo#12488]
### Summary

The link created by makeRedirectUri is at some stage transformed to all lowercase. This breaks Reddit oAuth because their client IDs are case sensitive (don't ask me!). I'm not sure if this is down to something in `expo-auth-session` or perhaps `expo-web-browser`. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40

### Environment

```
  Expo CLI 4.3.4 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.3 - fake\path\to\nodejs-managed\node.EXE
      Yarn: 1.22.10 - fake\path\to\nodejs-managed\yarn.CMD
      npm: 6.14.9 - fake\path\to\nodejs-managed\npm.CMD
      Watchman: 20201220.042258.0 - fake\path\to\Watchman\bin\watchman.EXE
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project
https://github.com/dylmye/expo-12488-repro

See [comment](https://github.com/expo/expo/issues/12488#issuecomment-819944895)

You can use the following client ID in the auth session setup: "QTDDA2QX_tQfaA". The issue is that the Reddit API client ID is case sensitive.

**Comment by brentvatne** [comment]
you don't need to provide a snack -- a valid alternative is to create a new project and share it on github

**Comment by dylmye** [comment]
Created a minimal reproduction here: https://github.com/dylmye/expo-12488-repro

I [did the following](https://github.com/dylmye/expo-12488-repro/commit/c50f5206c86b6b186630a2f6bac1c897b09db022):
* Ran `expo init` and created the project with the managed blank TS
* Added a scheme to the `app.json` as required for linking
* Implemented the Reddit OAuth example in the docs

**Comment by brentvatne** [comment]
if you'd like to try this within expo go, you will need to use app id that has a redirect url set to your localhost or 127.0.0.1:

<img width="951" alt="Screen Shot 2021-04-15 at 10 23 32 PM" src="https://user-images.githubusercontent.com/90494/114975532-3f76b200-9e39-11eb-9dc3-28a3ac8b2d4b.png">

you can check what redirectUrl is generated, eg: in my logs when running your app i see:

https://www.reddit.com/api/v1/authorize.compact?code_challenge=fXYFgTDdsoJS6XAr9Gna_68iwrxtMKQ0Eq09Y-LWJDU&code_challenge_method=S256&redirect_uri=exp%3A%2F%2F127.0.0.1%3A19000&client_id=4d7YQJKiOz0ivA&response_type=code&state=0kIixtxE16&scope=identity

so exp://127.0.0.1:19000 is the allowed redirect url i set

when you build your app with `expo build:ios` or `expo build:android` it will use the provided `native` option. so, you can switch the clientId used in that context

```
clientId: Constants.appOwnership === 'expo' ? clientIdForExpoGo : clientIdForStandalone
```

**Comment by dylmye** [comment]
Thanks for testing the repro Brent. The problem is, even when setting redirect URI properly, the client ID that has mixed case in the logs is transformed to lowercase when it's actually opened in the browser. I've attached a screen recording. Here's the current config of the app:
![image](https://user-images.githubusercontent.com/7024578/115119348-cd6cad00-9f9f-11eb-9052-4ac45bd881f6.png)

Video is on Android 11 on a Pixel 3a, Google Chrome 89, expo-12488-repro @ 96f814e.

https://user-images.githubusercontent.com/7024578/115119662-7071f680-9fa1-11eb-9f2b-1137ce8a7e2b.mp4

**Comment by dylmye** [comment]
Bumping this :)

**Comment by dylmye** [comment]
bumpy bump

**Comment by dylmye** [comment]
For anyone wondering I resolved this by ejecting from Expo and using react-native-app-auth which works perfectly.

**Comment by FaisalBinAhmed** [comment]
> if you'd like to try this within expo go, you will need to use app id that has a redirect url set to your localhost or 127.0.0.1:
> 
> <img alt="Screen Shot 2021-04-15 at 10 23 32 PM" width="951" src="https://user-images.githubusercontent.com/90494/114975532-3f76b200-9e39-11eb-9dc3-28a3ac8b2d4b.png">
> 
> you can check what redirectUrl is generated, eg: in my logs when running your app i see:
> 
> https://www.reddit.com/api/v1/authorize.compact?code_challenge=fXYFgTDdsoJS6XAr9Gna_68iwrxtMKQ0Eq09Y-LWJDU&code_challenge_method=S256&redirect_uri=exp%3A%2F%2F127.0.0.1%3A19000&client_id=4d7YQJKiOz0ivA&response_type=code&state=0kIixtxE16&scope=identity
> 
> so exp://127.0.0.1:19000 is the allowed redirect url i set
> 
> when you build your app with `expo build:ios` or `expo build:android` it will use the provided `native` option. so, you can switch the clientId used in that context
> 
> ```
> clientId: Constants.appOwnership === 'expo' ? clientIdForExpoGo : clientIdForStandalone
> ```

What was your redirect_uri for standalone app in the reddit pref? @brentvatne

**Comment by FaisalBinAhmed** [comment]
UPDATE: for people struggling with Reddit's redirect URI and expo-auth-session in an installed standalone app, I have figured out a solution.
On[ Reddit app settings page](https://www.reddit.com/prefs/apps), you have to register the redirect uri with your own custom URL scheme. for example: `myapp://redirect`

And then in expo auth's `useAuthRequest` hook you have to provide this as an argument:

```
redirectUri: makeRedirectUri({
	native: "myapp://redirect",
	}),
```

and then finally in your `app.json` file, register your custom URL scheme at `expo.scheme` so that the app can handle the redirect URL after auth is done.

```
{
	"expo": {
		"scheme": "myapp"
}
}
```
