### ISSUE TITLE
In Android Modal - wrapping content in GestureHandlerRootView not fixing react-native-gesture-handler

### ISSUE THREAD

**Issue by Noitidart** [expo/expo#12499]
### Summary

I am trying to get react-native-gesture-handler components to work in a <Modal> from react-native in Android. I followed docs here - Getting Started | React Native Gesture Handler

It stays to wrap in `<GestureHandlerRootView>` for Android because in Android the `<Modal>` renders outsie of the root view, I did this but it doesn’t fix the issue.

I created a snack demo of issue - https://snack.expo.io/@noitidart/frisky-carrot

Here you see a “Tapped here count: 0”. Please try tapping it, you will see it doesn’t increment the counter.

You will see a “RN BUTTON” this works but it is not from react-native-gesture-handler.

### Fix found

Here is working snack - https://snack.expo.io/@noitidart/fixed-gesture-handler-components-in-modal-in-expo

Instead of importing  `GestureHandlerRootView` we have to create our own like this:

```
const GestureHandlerRootViewNative = Platform.OS === 'android'
  ? requireNativeComponent(
      'GestureHandlerRootView',
      // @ts-note: TS is saying only one arg supported. I tested one arg, and it
      // works. But I copied this from
      // `node_modules/react-native-gesture-handler/GestureHandlerRootView.android.js`
      // and they use this 2nd argument, so I'm keeping it.
      { name: 'GestureHandlerRootView', propTypes: { ...ViewPropTypes } }
    )
  : View;
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.0

### Environment

```
  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
        Android NDK: 21.0.6113669
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.0.10 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Please see Snacks in the Summary. Snack of issue and snack of solution.

**Comment by brentvatne** [comment]
can you post this to react-native-gesture-handler? https://github.com/software-mansion/react-native-gesture-handler/issues

**Comment by AdamJNavarro** [comment]
Hey @Noitidart, I'm going to close this. When you get the time, could you please do as Brent asked and create an issue on the react-native-gesture-handler repo? Sorry for not telling you this specifically on your forum post. ><

Cheers,
Adam

**Comment by Noitidart** [comment]
Oh whoops sorry Brent I missed your message. Will do!
