### ISSUE TITLE
Allow more control over app loading experience

### ISSUE THREAD

**Issue by sonaye** [expo/expo#125]
```javascript
<AppLoading renderOwnComponent={<Component />} />
```

After looking into the [source](https://github.com/expo/expo-sdk/blob/master/src/AppLoading.ios.js) of AppLoading, it turns out it's actually a [native](https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Modules/Internal/EXAppLoadingManager.m) component (although I couldn't find the implementation of the view itself `ExponentAppLoading`).

Perhaps we can add an option to `exp.json`, `"loading": { "component": "./appLoading.js" }` that pre-bundles the view desired. This would only be available to standalone builds I believe.

**Comment by jesseruder** [comment]
I agree this is a feature we'll want eventually, but we're not going to be able to use that api. The purpose of the loading screen is to show something while we're loading your JS bundle, so we can't render a JS component while that's happening (otherwise we'd just render your app!). We'll think about an API and hopefully work on this soon.

**Comment by sonaye** [comment]
@jesseruder my idea was to pre bundle that js component with the standalone build itself, so there won't be a need to load it, isn't that possible? or does this has to do with the whole js thread?

**Comment by jesseruder** [comment]
Either way we need to show something before the bridge is loaded. We'll need to think about it more internally - we care about this a lot so want to make it better, but it is a hard problem.

**Comment by dikaiosune** [comment]
Since we're tracking feature requests on Canny now, I added a comment to the existing splash screen improvements request: https://expo.canny.io/feature-requests/p/improved-splash-screen-api.

**Comment by git-hubber** [comment]
Since where talking about the loading/splash screen, can we animate the loading icon in iOS, the same way it is in Android (and not show the spinner)? If not, maybe make the loading icon an Android only setting.

Just an idea. Thanks..
