### ISSUE TITLE
EXPO GO [SDK 41] In order to use RNScreens components your app's activity need to extend ReactFragmentActivity of ReactCompatActivity

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#12500]
### Summary

EXPO GO BETA 2.18.9 is crashing with this error on Android when i upgraded to SDK 41 , the strange thing is that the app launches te first time , if i quit the EXPO GO app and open it again i get this error , and then i have to clear all the app data to in order to start EXPO GO again . i'm on BETA version 2.18.9 .
on IOS it works very well . i tested on many android phones , i got the same error .

In order to use RNScreens components your app's activity need to extend ReactFragmentActivity of ReactCompatActivity

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.3.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\lenovo\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~41.0.0-beta.3 => 41.0.0-beta.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',a
  },
});

**Comment by brentvatne** [comment]
are you saying that on an empty project that you init with `expo init` you see this error?

**Comment by islamouzou** [comment]
> are you saying that on an empty project that you init with `expo init` you see this error?
> 
> i am unable to reproduce this. you will need to share a reproducible example that i can clone and run. happy to reopen the issue if you can do that.

Yes indeed , it happened when i upgraded my project to the BETA SDK , then i tried it with an empty new project and i got the same thing . now if i clear expo go data on my phone and run a project that's on SDK 40 there will be no problem . if i run a project on SDK 41 i'll get the same problem . 

i also tried to change a computer to exclude any other possibilities .

**Comment by brentvatne** [comment]
hi there!

i was able to reproduce this. thank you for reporting, it is fixed now.
