### ISSUE TITLE
[SDK 41] Fails to build: app.json - should NOT have additional property 'nodeModulesPath'.

### ISSUE THREAD

**Issue by brandtnewww** [expo/expo#12502]
### Summary

I can't build an app for production with SDK 41 for iOS or Android. Starting an app in DEV or building via expo build:ios / build:android results in an error message:

Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • should NOT have additional property 'nodeModulesPath'.

I don't have a nodeModulesPath added in app.json. This error also happens on a newly created project (EXPO_BETA=1 expo init).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.1.5 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.4.0/bin/yarn
      npm: 7.0.15 - ~/.nvm/versions/node/v15.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0-beta.3 => 41.0.0-beta.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Init new project via EXPO_BETA=1 expo init. Start App on Simulator or build App via expo build:ios / expo build:android.

**Comment by brentvatne** [comment]
you should update to the latest expo-cli, it's required for using sdk 41+

**Comment by brentvatne** [comment]
from the beta blog post:

> Install the latest version of expo-cli:
> `npm i -g expo-cli` (SDK 41 requires expo-cli@4.3.2 or greater)

**Comment by brandtnewww** [comment]
My bad. Works now!

**Comment by brentvatne** [comment]
thanks @brandtnewww!

**Comment by slorber** [comment]
@brentvatne shouldn't the cli update itself on "expo update" if using it through dependencies? (not installed globally)

It could beconvenient to keep it up to date automatically

**Comment by brentvatne** [comment]
@slorber - that might be a bit tricky. maybe they install expo-cli locally to their project, maybe globally with npm, or with yarn, or with volta, or something else.. lots of cases to consider

**Comment by slorber** [comment]
@brentvatne just bumping the expo cli dep in package.json if it is there can be a good enough solution for me ;)

**Comment by alamgir72435** [comment]
nice
