### ISSUE TITLE
[android] Splash image is displayed briefly when user taps text inputs

### ISSUE THREAD

**Issue by gtaylor44** [expo/expo#1250]
I'm not sure if anybody else has the experienced the same issue but I'm having problems when using the splash option in app.json 

`   
 "splash": {
        "image" : "./assets/images/splash_v3.png",
        "backgroundColor": "#6353A6",
        "resizeMode"  : "contain"
}`

After building a standalone version of the app in Android and testing on a real device (i've tried 2 devices so far), wherever there is an input and the user taps on the input to launch the keyboard, there is a momentary flash of the splash image in the background. It covers the bottom 50% of the screen for about 200ms then disappears. It's quite annoying and a bit of an eyesore.

NB: for some reason, I can't reproduce this on a virtual device via Genymotion (Galaxy S7). 

Does anybody know how to rid this! I could go without the splash image but this would be unfavourable. 

Here is my package.json
`{
  "name": "receipt-tracker",
  "version": "1.0.5",
  "description": "An organisational app for storing receipts. Snap it, forget about it.",
  "author": "Greg Taylor",
  "license": "",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js --watch",
    "start": "react-native-scripts start --port 8081",
    "lint": "eslint --ext .js,.jsx src"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "currency-symbol-map": "^4.0.2",
    "expo": "^24.0.0",
    "native-base": "^2.3.1",
    "npm": "^4.6.1",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
    "react-native-datepicker": "^1.6.0",
    "react-native-elements": "0.16.0",
    "react-native-image-view": "^1.2.2",
    "react-native-scripts": "^1.3.1",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.21",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "eslint": "^1.6.0",
    "eslint-config-defaults": "^7.0.1",
    "eslint-plugin-filenames": "^0.1.2",
    "eslint-plugin-react": "^3.5.1",
    "jest-expo": "^23.0.0"
  }
}`

**Comment by abhishek0058** [comment]
+1

**Comment by terribleben** [comment]
Hey thanks for the report!

Can you mention the name of a device where you have seen it happen? (you said you have seen it on two devices.) Also the Android version if possible.

**Comment by aalices** [comment]
Is you most bottom view's backgroundColor set? If not can you try setting it to some color?

**Comment by gtaylor44** [comment]
Yes, I've tried setting all parent containers with a backgroundColor of #FFF

**Comment by aalices** [comment]
On what devices is this happening?

**Comment by gtaylor44** [comment]
I have found the culprit.

"androidStatusBar": {
    "backgroundColor": "#483c77"
}

Removing this option in app.json fixes the issue. It's related to issue #1065 and is a side effect of android:windowSoftInputMode setting. Seeing the splash screen flash when keyboard opens/closes is not desirable. "androidStatusBar" option does not mix well with splash screen.

**Comment by ide** [comment]
IIRC the status bar and perhaps `windowSoftInputMode` behavior different across Android versions -- could you please tell us the version of Android (and also the device -- some OEMs may modify Android)?

**Comment by gtaylor44** [comment]
Asus Zenfone ze550kl
Android 6.0.1

Oppo A57
Android 6.0

Also happening on Galaxy Tab A
Android 6.0.1
