### ISSUE TITLE
i have an issue with expo sqlite

### ISSUE THREAD

**Issue by mahamaad** [expo/expo#12515]
### Summary

hey i use expo-sqlite in rn bare its work perfectly, i build my app and test in testflight when i send an update to app the data in sqlite is lost,example my app v1.0 and i have some data in sqlite when i uldate app to v2.0 the data in sqlite is lost how to fix it thanks

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\mahamad\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

App.js
import { planInit} from "./db/SQLite";

planInit()
  .then(() => {
    console.log("planSQLite initialzed");
  })
  .catch((e) => console.log("error in init SQLite " + e));
--------
SQLite.js
import * as SQLite from "expo-sqlite";
const plan = SQLite.openDatabase("plans.db");

export const planInit = async () => {
  const promise = new Promise((resolve, reject) => {
    plan.transaction((tx) => {
      tx.executeSql(
        "CREATE TABLE IF NOT EXISTS Plan (id INTEGER PRIMARY KEY NOT NULL,plan TEXT NOT NULL);",
        [],
        () => {
          resolve();
        },
        (_, e) => {
          reject(e);
        }
      );
    });
  });
  return promise;
};

**Comment by brentvatne** [comment]
please post a reproducible example that we can run. more tips on how to do that: https://stackoverflow.com/help/minimal-reproducible-example
