### ISSUE TITLE
facebook login failed in standalone app when facebook app is installed.

### ISSUE THREAD

**Issue by dooboolab** [expo/expo#1251]
expo version 24.
Platform android.

Works ok in ios but facebook login fails when facebook app is installed in device.
It works fine when facebook app it not installed.

I've tried behavior to web, system, native, browser but they all behaves same in android.
Nothing solved this problem.

It always works fine when facebook app is not installed in device.

**Comment by dooboolab** [comment]
I just found the answer..

```
07-05 ...... Invalid key hash. The key hash sL1***************VY= does not match any stored key hashes. Configure your app key hashes at http://developers.facebook.com/apps/150*******778
07-05 ......     at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:191)
```
I found below message on the logcat and registered to facebook app.
The hash key being generated from keytool didn't match.

**Comment by robertobrogi** [comment]
have you find a solution?

**Comment by sbodrero** [comment]
Just add the key hash to your facebook app
