### ISSUE TITLE
EXPO GO KEEPS STOPPING (SAMSUNG GALAXY TAB S5e)

### ISSUE THREAD

**Issue by Jerald042615** [expo/expo#12513]
### Summary

Unable to open EXPO GO app same with App build by expo?

How to fix?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

Latest?

### Environment

expo diagnostics.

### Reproducible demo or steps to reproduce from a blank project

Try to install at Samsung Galaxy Tab S5

**Comment by brentvatne** [comment]
we need more information. are you saying it crashes when you open it? or when you do something specific?

**Comment by Jerald042615** [comment]
Sorry for late response. It crashes on open.

**Comment by jaisonjohn78** [comment]
Same here, I am facing The issue when I scan the QR code ......... It was working so fine but idk why but now it keeps stopping when I scan my project's QR code

**Comment by brentvatne** [comment]
@jaisonjohn78 - does it happen on a brand new project also? or just on your specific app?

**Comment by jaisonjohn78** [comment]
@brentvatne -
I was Working on my Project of eLearning App using React Native (Blank template)

It was Working Perfectly Until  I added Splash Screen for my project and then an error was encountered 

**

> getproperty as object: 'callfunctionreturnresultandflushedqueue' is undefined, expected an object no stack

**

I restarted The machine and clear the cache `expo start -c`

still same error 🙄

and then after 1 day I tried to run my project using expo go (Android ) it just stops and a message " expo go is unfortunately stopped"



### Device Info
POCO M2 Pro (64GB)
6Gb Ram
Octa-core Max 2.35Ghz
Andriod 10

### Expo Go version
Version: 2.21.4 (Latest )

### `expo diagnostics`

Expo CLI 4.7.2 environment info:
    System:
      OS: Windows 10 10.0.19043   
    Binaries:
      Node: 14.17.1 - C:\Node JS\node.EXE
      Yarn: 1.22.10 - C:\Users\jaiso\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Node JS\npm.CMD
    npmPackages:
      expo: ~38.0.8 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ^0.64.2 => 0.64.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

**Comment by brentvatne** [comment]
@jaisonjohn78 - please answer my questions. if you create a new project do you see the error? if not then it's likely some issue with your code and you can just revert it in git to your last known working point if you can't figure out the cause

**Comment by jaisonjohn78** [comment]
@brentvatne - I Just Checked with a new blank project Expo Go is working All good  and Thank you so much now it's working ❤
