### ISSUE TITLE
How to add .db file to assets/db/dbname.db, i use expo-sqlite ?

### ISSUE THREAD

**Issue by mahamaad** [expo/expo#12519]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/sdk/sqlite/#importing-an-existing-database

**Comment by mahamaad** [comment]
thanks but whats value for pathToDatabaseFile i dont know whats this !

**Comment by brentvatne** [comment]
copy and paste it to whichever directory in your project that you want, like you would for an image
