### ISSUE TITLE
Can't re-sign apk signed by Expo since keystore is on the Expo servers

### ISSUE THREAD

**Issue by ArsenyYankovsky** [expo/expo#1252]
Hello,

I used expo to handle the apk signing process and got apk released to the Play Store. Now I'd like to sign the apk myself in order to work around https://github.com/expo/expo/issues/1247 and that's not possible since the keystore is stored somewhere on the expo servers.

I can see lots of scenarios where that would be an issue. If someone had an expo app and wants to publish a native app as a new version.

It would be nice to have an option to download keystore used to sing an app from the expo website or some other way.

**Comment by terribleben** [comment]
Hi, does `exp fetch:android:keystore` solve your problem?

**Comment by ArsenyYankovsky** [comment]
@terribleben Thank you! It's perfect!

**Comment by turcuciprian** [comment]
I'm having an issue regarding this.. I do ```fetch:android:keystore``` and when I do a build with flutter and then I upload the apk in google play developer console, it says the SH1's are different. I don't know what to do. anyone have any ideas. Also if I load the apk on my device it just crashes

**Comment by jameskennethrobinson** [comment]
This is also a problem for me.

**Comment by ehrenmurdick** [comment]
Still a problem for me, today....

**Comment by jjgumucio** [comment]
Which would be the keystore path?

**Comment by Rafaell416** [comment]
the keystore is downloaded into your current directory, if you ran `expo fetch:android:keystore` from your project directory the path would be just `./project_slug_name.jks`
