### ISSUE TITLE
Modal always visible on web

### ISSUE THREAD

**Issue by mleister97** [expo/expo#12538]
### Summary

Hi.
The modal is working fine on Android/iOS. However, it is always visible in Web View (Pressing in expo "Run in web browser").

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\micha\AppData\Roaming\npm\yarn.CMD
      npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Here is a really simple snippet to reproduce:

```js
export default function App() {
    return (
        <View>
            <Modal animationType="fade"
                   transparent={true}
                   visible={false}>

                <Text>
                    My visible=false modal!
                </Text>
            </Modal>
        </View>
    )
}
```

**Comment by cglacet** [comment]
Hello, just got a similar problem with expo 41, I also noticed this upgrade (from 40 to 41) actually downgraded my version of `react-native-web`. (I didn't had this bug before upgrading). After reverting this change it seems like it fixed the issue, what worked for me is this version:

```
"react-native-web": "^0.14.13",
```
