### ISSUE TITLE
Multiple notifications at the same time - only single notification fires

### ISSUE THREAD

**Issue by Rolandisimo** [expo/expo#1253]
The title says it all - I schedule multiple notifications to e.g. 15:30, but only the latest notification triggers the callback. Otherwise, everything works with notifications. They get scheduled, they fire, they can be cleared, et all. 

Here's the example code:

```typescript
Notifications.addListener(async (payload: Notifications.Notification) => {
    switch (payload.origin) {
        case Origin.Received:
        case Origin.Selected:
            console.log("ORIGIN SELECTED") // <-- fires once even with multiple notifications set for the same time
             // ... some code 
             break;

         default:
     }
});
```

This code gets fired whenever an item is created:

```typescript
export async function setItemNotification(item: ItemProps, repeat = true) {
    return await Notifications.scheduleLocalNotificationAsync(
        {
            title: item.name,
            body: "Foo body",
            data: {
                item,
            },
            ios: {
                sound: true,
            },
            android: {
                sound: true,
                priority: "max",
            },
        },
        {
            time: nextNotificationTime(item.notificationTime), // <-- returns number in ms
            repeat: repeat ? 'day' : undefined,
        }
    ) as number;
}
```

Question:
- Is this an expected behaviour or a bug?

P.S. Feel free to ask for any additional info or code examples

**Comment by sjchmiela** [comment]
Hi @Rolandisimo, unfortunately that's how iOS works — when the app is in the background it does not get notified about received **local** notifications, the user has to interact with the notification for OS to notify the application.

On iOS the callback will be called with `origin: received` [only when the notification is received while the app is in the foreground](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622930-application?language=objc) (then the system alert won't be presented to the user).

Android notifies the application even if it is in the background.
