### ISSUE TITLE
Crash on startup (reanimated) if app is closed before splash screen

### ISSUE THREAD

**Issue by dapperappdeveloper** [expo/expo#12540]
### Summary

If the app is closed before fully loading, this error will occur
Problem occurs on a release apk as well, if the app is ended before splash loading, it will crash on next launch
**Uncaught Error: Attempt to invoke virtual method ‘boolean abi40_0_0.host.exp.exponent.modules.api.reanimated.NativeProxy.isAnyHandlerWaitingForEvent(java.land.String)’ on a null object reference**

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.1

### Environment

 Expo CLI 4.3.5 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 29, 30
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.3
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Video here:
https://drive.google.com/file/d/17JgvzjZR-QmXiw8y-uYcB3EcmqShx1Q9/view

Screenshot:
![Screenshot_20210412-142749_Expo Go (1)](https://user-images.githubusercontent.com/82542937/114773602-40c2b480-9d3d-11eb-8bbd-de61094357cf.png)

Code:
```import * as React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import Animated from 'react-native-reanimated';
import BottomSheet from 'reanimated-bottom-sheet';

export default function App() {
  const renderContent = () => (
    <View
      style={{
        backgroundColor: 'white',
        padding: 16,
        height: 450,
      }}
    >
      <Text>Swipe down to close</Text>
    </View>
  );

  const sheetRef = React.useRef(null);

  return (
    <>
      <View
        style={{
          flex: 1,
          backgroundColor: 'papayawhip',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Button
          title="Open Bottom Sheet"
          onPress={() => sheetRef.current.snapTo(0)}
        />
      </View>
      <BottomSheet
        ref={sheetRef}
        snapPoints={[450, 300, 0]}
        borderRadius={10}
        renderContent={renderContent}
      />
    </>
  );
}```

```{
  "expo": {
    "name": "test_app",
    "slug": "test_app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}```

This error is not related to the package BottomSheet from ‘reanimated-bottom-sheet’… the functionality works fine, it is an error with expo loading the reanimated package.
This occurs with other reanimated use cases

Through some research this may be related to Issue in expo 39 in start up in android sometimes or OTA updates but I’m not quite sure

Edit: this also may be related to the crash BaseExperienceActivity.lambda$consumeErrorQueue$0
java.lang.RuntimeException
at.
(BaseExperienceActivity.java:210)
at .(-java:2)

**Comment by brentvatne** [comment]
hi there! reanimated 2 support in sdk < 41 was very experimental. i recommend updating to sdk 41 if you want to use reanimated 2, see https://blog.expo.io/expo-sdk-41-12cc5232f2ef
