### ISSUE TITLE
'expo-location' watchHeadingAsync is inaccurate

### ISSUE THREAD

**Issue by ch4zzzzz** [expo/expo#12548]
### Summary

Usage:
```javascript
import * as Location from 'expo-location';
Location.watchHeadingAsync((value) => {
      // handle value
});
```
Every time I rotate my phone 90 degrees, I record the heading. However, after I rotate the phone in a circle, I get heading：
| ---- | trueHeading | magHeading |
| ---- |  ----  | ----  |
| initial state | 170 | 178 |
| rotate 90° | 265  | 273 |
| rotate 180° | 25 | 30 |
| rotate 270° | 90 | 97 |

Why isn't the difference of each rotation always 90 degrees?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

4.3.5

### Environment

  Expo CLI 4.3.5 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```javascript
import * as Location from 'expo-location';
Location.watchHeadingAsync((value) => {
      // handle value
});
```

**Comment by mrkprdo** [comment]
@ch4zzzzz did you get any work-around on this?
