### ISSUE TITLE
Deep linking uncaught error

### ISSUE THREAD

**Issue by dapperappdeveloper** [expo/expo#12541]
### Summary

When the default created expo app is opened and closed, this bug occurs
Screenshot:
![Screenshot_20210414-164551_Expo Go](https://user-images.githubusercontent.com/82542937/114776986-1d016d80-9d41-11eb-82bc-e142248c226b.png)
Video:
https://drive.google.com/file/d/19QwoXMillw8LidUBFCy9OTyAiC8xAefW/view?usp=sharing

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.0

### Environment

 Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 29, 30
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.3
    npmPackages:
      expo: ~41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

The default blank app generated from expo init app_name

`import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`

**Comment by brentvatne** [comment]
it is impossible to reproduce this from the code that you provided, because this error comes from react navigation! please share an actual reproducible example and we can help!

**Comment by dapperappdeveloper** [comment]
Here is the package.json if it helps, again just the standard starting blank template app from expo init
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~41.0.0",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },
  "private": true
}

**Comment by brentvatne** [comment]
i was able to repro it, thanks for the video, very helpful!

**Comment by dapperappdeveloper** [comment]
No problem, thanks for looking into it

**Comment by brentvatne** [comment]
this will still happen the *first time you open expo go on android* but will be patched in an ota update when you restart the app.

we'll roll out a full new release once we resolve the underlying issue entirely
