### ISSUE TITLE
Unrecognized font family: 'Roboto-Bold'

### ISSUE THREAD

**Issue by aplinxy9plin** [expo/expo#12552]
### Summary

My fonts doesn't working. I importing it using Fonts.loadAsync(). But get error: unrecognized font family 'Roboto'.

- I create new expo project on my machine and get same error. 
- But when I create ios/android build and install apk/ipa all fonts are working.
- But I open my code on Snack and it's working... 

Maybe it's problem of expo or expo-font version?
I use expo: '~40.0.0' and expo-font: '~9.0.0'

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40.0.0

### Environment

  Expo CLI 4.3.4 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.13.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 17.0.2 => 17.0.2
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.15.7 => 0.15.7
      react-navigation: ^4.4.4 => 4.4.4
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@aplinxy9plin/roboto-font-issue

**Comment by brentvatne** [comment]
<img width="668" alt="Screen Shot 2021-04-15 at 9 39 24 PM" src="https://user-images.githubusercontent.com/90494/114972265-0f2c1500-9e33-11eb-949a-f48a73d2117b.png">

<img width="693" alt="Screen Shot 2021-04-15 at 9 40 03 PM" src="https://user-images.githubusercontent.com/90494/114972317-2539d580-9e33-11eb-9521-a82579b06952.png">

<img width="467" alt="Screen Shot 2021-04-15 at 9 40 59 PM" src="https://user-images.githubusercontent.com/90494/114972416-51555680-9e33-11eb-9d5b-9a855140ffa9.png">

<img width="1222" alt="Screen Shot 2021-04-15 at 9 41 13 PM" src="https://user-images.githubusercontent.com/90494/114972423-54e8dd80-9e33-11eb-8e55-33959002c348.png">
