### ISSUE TITLE
pod install freezes at "-> Installing yoga"

### ISSUE THREAD

**Issue by ibash** [expo/expo#1255]
Steps:
1. Create a new expo project
2. Detach the project
3. In the ios directory run `pod install --verbose`

Expected:
Installs pods

Actual:
Freezes

**Comment by noahhayes** [comment]
Same problem here. I just got finished fixing the bug where it was stuck on boost. @ibash did you find a solution?

**Comment by ibash** [comment]
@noahhayes I waited a really long time :) turns out it just took forever (like 1/2 hour or something)
