### ISSUE TITLE
DateTimePicker display='spinner' not working after upgrading to Expo SDK 41

### ISSUE THREAD

**Issue by HenryDeLange** [expo/expo#12555]
### Summary

While using Expo SDK 41 the DateTimePicker always opens in calendar mode, even if I specify 'spinner' (on Android).

If I switch back to Expo SDK 40 then it works as expected.

```
      <DateTimePicker
        mode='date'
        value={new Date()}
        display='spinner'
        onChange={() => null}
      />
```

I tried upgrading and downgrading the version of @react-native-community/datetimepicker, but it didn't help.
I tried to delete my node_modules, cleared my NodeJS cache and cleared the Expo Go cache.
Nothing worked.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.1 environment info:
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  npmPackages:
    expo: ~41.0.0 => 40.0.1
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
    react-native-web: ~0.13.12 => 0.13.18
  Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
import React from 'react';
import { View } from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';

export default function App() {
  return (
    <View>
      <DateTimePicker
        mode='date'
        value={new Date()}
        display='spinner'
        onChange={() => null}
      />
    </View>
  );
}
```

**Comment by brentvatne** [comment]
@cruzach has found the root cause, we'll release an updated sdk 41 expo go for android and standalone app image this afternoon
