### ISSUE TITLE
ImagePicker broken in SDK41 for Web

### ISSUE THREAD

**Issue by buffaloDeveloper** [expo/expo#12560]
### Summary

I created a brand new expo project using SDK41 and used the code provided here:

https://docs.expo.io/versions/latest/sdk/imagepicker/

When you try to run this on the **web**, whenever you select an image it returns {cancelled: true}.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.7.6 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

"expo init" blank project
"expo add expo-image-picker"
replace App.js with the demo code found here: https://docs.expo.io/versions/latest/sdk/imagepicker/
try to pick an image you get {cancelled: true}

**Comment by brentvatne** [comment]
thanks for the report, it looks like this pr didn't land in the sdk-41 release: https://github.com/expo/expo/pull/12420

i'll cherry-pick it and re-release expo-image-picker later today

**Comment by brentvatne** [comment]
fixed in `expo-image-picker@10.1.4`
