### ISSUE TITLE
Couldn't exclude ACCESS_BACKGROUND_LOCATION 

### ISSUE THREAD

**Issue by Sean-HL-Lin** [expo/expo#12567]
### Summary

Hey Guys, 

I failed to publish to google play store as ACCESS_BACKGROUND_LOCATION is added to my app permission list. 

I read the instruction here([https://docs.expo.io/versions/latest/sdk/permissions/#managed-workflow-1](https://docs.expo.io/versions/latest/sdk/permissions/#managed-workflow-1)) and try to exclude the ACCESS_BACKGROUND_LOCATION permission by explicitly mention all other permission in my app.json(see attached image).

However, this is still not working(see attached image). I'm using sdk 39.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

39

### Environment

 Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I ran "expo build: android" to build my android app and tried to publish it to google play store

**Comment by Sean-HL-Lin** [comment]
<img width="815" alt="Screen Shot 2021-04-15 at 21 18 40" src="https://user-images.githubusercontent.com/48516008/114971284-e014a400-9e30-11eb-8007-a53a3fda110f.png">
![Screen Shot 2021-04-15 at 21 21 53](https://user-images.githubusercontent.com/48516008/114971289-e30f9480-9e30-11eb-80fa-e557c5fe4b94.png)

**Comment by Sean-HL-Lin** [comment]
My list of permission looks like this. ![Screen Shot 2021-04-15 at 21 21 53](https://user-images.githubusercontent.com/48516008/114971329-f6226480-9e30-11eb-94e0-75fc41ba0a32.png)

**Comment by brentvatne** [comment]
please refer to https://github.com/expo/expo/issues/11918
