### ISSUE TITLE
exp build:ios, Error validating credentials

### ISSUE THREAD

**Issue by kshitijb** [expo/expo#1256]
Hi,
I keep getting error validating credentials. I might be doing something wrong. But I used to be able to create build fine earlier. Can you help out?

```
Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID 82160030-f8d2-11e7-af1c-b19bf1309d9e, message: Username and/or password is incorrect.
```

**Comment by fxfactorial** [comment]
Hi @kshitijb , what version of exp are you on? Can you please upgrade to latest?

**Comment by kshitijb** [comment]
Hey @fxfactorial Yeah, I changed it to the latest version and it worked. But did something change? I used to be able to login in the older version before.

**Comment by fxfactorial** [comment]
Yes, authentication for build:ios has moved completely client side.

**Comment by kyhnlbyrk** [comment]
I am encountering the same issue. How can I update expo ?
