### ISSUE TITLE
Iterate array in a table of html and print with Print.printToFileAsync

### ISSUE THREAD

**Issue by jordaofs** [expo/expo#12576]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by jordaofs** [comment]
I am trying to print one table inside a html of the Print.printToFileAsync function. But I'm having trouble to iterate through the array and insert the data inside the table.             
 

             <table>
             <thead>
              <tr>
                <th>Item 1</th>
                <th>Item 2</th>
                <th>Item 3</th>
              </tr>
              </thead>
            <tbody>
                ${_.map(itens, (item) => (
                  <tr>
                    <td>{item.code}</td>
                    <td>{item.name}</td>
                    <td>{item.value}</td>
                  </tr>
                  ))}
            </tbody>
            </table>
            
            And I am getting this result:
![image](https://user-images.githubusercontent.com/25749079/115053825-ee58d380-9eb5-11eb-8b87-27d741c1980c.png)

How can I iterate the array to fill the table correctly?

**Comment by brentvatne** [comment]
these questions are better suited for stackoverflow or forums.expo.io, the issue tracker is for bugs
