### ISSUE TITLE
Standalone build failed after upgrading to SDK 41

### ISSUE THREAD

**Issue by ornakash** [expo/expo#12574]
### Summary

My application used to get compiled perfectly on SDK 40 but since I upgraded it to SDK 41, I have to do the building process again and again, until it works - every time I have to wait 20~ minutes for it to compile. When it fails, I see this:

`Configuration on demand is an incubating feature.
> Configure project :app
WARNING: The option setting 'android.useNewApkCreator=false' is experimental.
The current default is 'true'.
AWS Device Farm Plugin version 1.3
Installing unimodules:
 unimodules-core@7.1.0 from /app/turtle/workingdir/android/sdk41/packages/@unimodules/core
 unimodules-react-native-adapter@6.2.2 from /app/turtle/workingdir/android/sdk41/packages/@unimodules/react-native-adapter
 expo-ads-admob@10.0.4 from /app/turtle/workingdir/android/sdk41/packages/expo-ads-admob
 expo-ads-facebook@10.0.4 from /app/turtle/workingdir/android/sdk41/packages/expo-ads-facebook
 expo-analytics-amplitude@10.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-analytics-amplitude
 expo-analytics-segment@10.1.1 from /app/turtle/workingdir/android/sdk41/packages/expo-analytics-segment
 expo-app-auth@10.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-app-auth
 expo-application@3.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-application
 expo-av@9.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-av
 expo-background-fetch@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-background-fetch
 expo-barcode-scanner@10.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-barcode-scanner
 expo-battery@4.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-battery
 expo-brightness@9.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-brightness
 expo-calendar@9.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-calendar
 expo-camera@11.0.2 from /app/turtle/workingdir/android/sdk41/packages/expo-camera
 expo-cellular@3.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-cellular
 expo-constants@10.1.3 from /app/turtle/workingdir/android/sdk41/packages/expo-constants
 expo-contacts@9.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-contacts
 expo-crypto@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-crypto
 expo-device@3.2.0 from /app/turtle/workingdir/android/sdk41/packages/expo-device
 expo-document-picker@9.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-document-picker
 expo-error-recovery@2.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-error-recovery
 expo-face-detector@10.0.1 from /app/turtle/workingdir/android/sdk41/packages/expo-face-detector
 expo-facebook@11.0.5 from /app/turtle/workingdir/android/sdk41/packages/expo-facebook
 expo-file-system@11.0.2 from /app/turtle/workingdir/android/sdk41/packages/expo-file-system
 expo-firebase-analytics@4.0.2 from /app/turtle/workingdir/android/sdk41/packages/expo-firebase-analytics
 expo-firebase-core@3.0.0 from /app/turtle/workingdir/android/sdk41/packages/expo-firebase-core
 expo-font@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-font
 expo-gl-cpp@10.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-gl-cpp
 expo-gl@10.2.0 from /app/turtle/workingdir/android/sdk41/packages/expo-gl
 expo-google-sign-in@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-google-sign-in
 expo-haptics@10.0.0 from /app/turtle/workingdir/android/sdk41/packages/expo-haptics
 expo-image-loader@2.1.1 from /app/turtle/workingdir/android/sdk41/packages/expo-image-loader
 expo-image-manipulator@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-image-manipulator
 expo-image-picker@10.1.3 from /app/turtle/workingdir/android/sdk41/packages/expo-image-picker
 expo-intent-launcher@9.0.0 from /app/turtle/workingdir/android/sdk41/packages/expo-intent-launcher
 expo-keep-awake@9.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-keep-awake
 expo-linear-gradient@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-linear-gradient
 expo-local-authentication@11.0.2 from /app/turtle/workingdir/android/sdk41/packages/expo-local-authentication
 expo-localization@10.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-localization
 expo-location@12.0.4 from /app/turtle/workingdir/android/sdk41/packages/expo-location
 expo-mail-composer@10.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-mail-composer
 expo-media-library@12.0.2 from /app/turtle/workingdir/android/sdk41/packages/expo-media-library
 expo-network@3.1.1 from /app/turtle/workingdir/android/sdk41/packages/expo-network
 expo-notifications@0.11.5 from /app/turtle/workingdir/android/sdk41/packages/expo-notifications
 expo-permissions@12.0.1 from /app/turtle/workingdir/android/sdk41/packages/expo-permissions
 expo-print@10.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-print
 expo-screen-capture@3.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-screen-capture
 expo-screen-orientation@3.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-screen-orientation
 expo-secure-store@10.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-secure-store
 expo-sensors@10.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-sensors
 expo-sharing@9.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-sharing
 expo-sms@9.1.2 from /app/turtle/workingdir/android/sdk41/packages/expo-sms
 expo-speech@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-speech
 expo-splash-screen@0.10.2 from /app/turtle/workingdir/android/sdk41/packages/expo-splash-screen
 expo-sqlite@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-sqlite
 expo-store-review@4.0.2 from /app/turtle/workingdir/android/sdk41/packages/expo-store-review
 expo-structured-headers@1.0.1 from /app/turtle/workingdir/android/sdk41/packages/expo-structured-headers
 expo-task-manager@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-task-manager
 expo-updates@0.5.4 from /app/turtle/workingdir/android/sdk41/packages/expo-updates
 expo-video-thumbnails@5.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-video-thumbnails
 expo-web-browser@9.1.0 from /app/turtle/workingdir/android/sdk41/packages/expo-web-browser
 unimodules-app-loader@2.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-app-loader
 unimodules-barcode-scanner-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-barcode-scanner-interface
 unimodules-camera-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-camera-interface
 unimodules-constants-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-constants-interface
 unimodules-face-detector-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-face-detector-interface
 unimodules-file-system-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-file-system-interface
 unimodules-font-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-font-interface
 unimodules-image-loader-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-image-loader-interface
 unimodules-permissions-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-permissions-interface
 unimodules-sensors-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-sensors-interface
 unimodules-task-manager-interface@6.1.0 from /app/turtle/workingdir/android/sdk41/packages/unimodules-task-manager-interface
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> Task :app:preBuild UP-TO-DATE
> Task :app:extractProguardFiles
> Task :app:preReleaseBuild
> Task :app:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:generateReleaseBuildConfig
> Task :app:javaPreCompileRelease
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
> Task :app:processReleaseGoogleServices
Parsing json file: /app/turtle/workingdir/android/sdk41/android-shell-app/app/google-services.json
> Task :app:checkReleaseAarMetadata
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease
> Task :app:mergeReleaseResources
> Task :app:processReleaseMainManifest
[com.facebook.soloader:soloader:0.8.2] /root/.gradle/caches/transforms-3/cfd0b9e5b303f54f13e669e38ab029ae/transformed/jetified-soloader-0.8.2/AndroidManifest.xml Warning:
	Package name 'com.facebook.soloader' used in: com.facebook.soloader:soloader:0.8.2, com.facebook.soloader:annotation:0.8.2.
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:36:1-94 Warning:
	Element uses-permission#android.permission.SYSTEM_ALERT_WINDOW at AndroidManifest.xml:36:1-94 duplicated with element declared at AndroidManifest.xml:16:3-76
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:23:1-101 Warning:
	uses-permission#android.permission.ACCESS_BACKGROUND_LOCATION was tagged at AndroidManifest.xml:23 to remove other declarations but no other declaration present
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:25:1-87 Warning:
	uses-permission#android.permission.RECORD_AUDIO was tagged at AndroidManifest.xml:25 to remove other declarations but no other declaration present
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:27:1-89 Warning:
	uses-permission#android.permission.WRITE_CONTACTS was tagged at AndroidManifest.xml:27 to remove other declarations but no other declaration present
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:35:1-91 Warning:
	uses-permission#android.permission.READ_PHONE_STATE was tagged at AndroidManifest.xml:35 to remove other declarations but no other declaration present
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:36:1-94 Warning:
	uses-permission#android.permission.SYSTEM_ALERT_WINDOW was tagged at AndroidManifest.xml:36 to remove other declarations but no other declaration present
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:38:1-83 Warning:
	uses-permission#android.permission.READ_SMS was tagged at AndroidManifest.xml:38 to remove other declarations but no other declaration present
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:39:1-99 Warning:
	uses-permission#android.permission.REQUEST_INSTALL_PACKAGES was tagged at AndroidManifest.xml:39 to remove other declarations but no other declaration present
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:42:1-104 Warning:
	uses-permission#com.android.launcher.permission.INSTALL_SHORTCUT was tagged at AndroidManifest.xml:42 to remove other declarations but no other declaration present
/app/turtle/workingdir/android/sdk41/android-shell-app/app/src/main/AndroidManifest.xml:17:9-26:20 Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:17 to replace other declarations but no other declaration present
> Task :app:processReleaseManifest
> Task :app:mergeReleaseNativeDebugMetadata NO-SOURCE
> Task :app:mergeReleaseShaders
> Task :app:compileReleaseShaders
 NO-SOURCE
> Task :app:generateReleaseAssets UP-TO-DATE
> Task :app:mergeReleaseAssets
> Task :app:compressReleaseAssets
> Task :app:processReleaseJavaRes NO-SOURCE
> Task :app:checkReleaseDuplicateClasses
> Task :app:collectReleaseDependencies
> Task :app:sdkReleaseDependencyData
> Task :app:mergeReleaseJniLibFolders
> Task :app:validateSigningRelease
> Task :app:processReleaseManifestForPackage
> Task :app:processReleaseResources
> Task :app:mergeReleaseJavaResource
> Task :app:mergeReleaseNativeLibs
> Task :app:compileReleaseJavaWithJavac
> Task :app:compileReleaseSources
> Task :app:lintVitalRelease
> Task :app:mergeReleaseGeneratedProguardFiles
> Task :app:minifyReleaseWithR8
[stderr] AAPT2 aapt2-4.1.2-6503028-linux Daemon #6: Idle daemon unexpectedly exit. This should not happen.
[stderr] AAPT2 aapt2-4.1.2-6503028-linux Daemon #5: Idle daemon unexpectedly exit. This should not happen.
[stderr] AAPT2 aapt2-4.1.2-6503028-linux Daemon #4: Idle daemon unexpectedly exit. This should not happen.
[stderr] AAPT2 aapt2-4.1.2-6503028-linux Daemon #0: Idle daemon unexpectedly exit. This should not happen.
[stderr] AAPT2 aapt2-4.1.2-6503028-linux Daemon #1: Idle daemon unexpectedly exit. This should not happen.
[stderr] AAPT2 aapt2-4.1.2-6503028-linux Daemon #3: Idle daemon unexpectedly exit. This should not happen.
[stderr] AAPT2 aapt2-4.1.2-6503028-linux Daemon #2: Idle daemon unexpectedly exit. This should not happen.
Error: ./gradlew exited with signal: SIGKILL
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:976:11)
    at async Object.createAndroidShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:396:5)
    at async runShellAppBuilder (/app/turtle/build/builders/android.js:95:9)
    at async Object.buildAndroid [as android] (/app/turtle/build/builders/android.js:43:28)
    at async build (/app/turtle/build/jobManager.js:181:33)
    at async processJob (/app/turtle/build/jobManager.js:118:32)
    at async Object.doJob (/app/turtle/build/jobManager.js:49:5)
    at async main (/app/turtle/build/server.js:66:13)`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-23 | ARM EABI v7a, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I did not check this on a blank project but after research in google I found out that it happens to other users and it indicates that something is wrong in Expo and not in the code. 

Thanks in advance!

**Comment by brentvatne** [comment]
please link to your build page

**Comment by ornakash** [comment]
> please link to your build page

https://expo.io/accounts/nakash/builds/d65cba18-c4e0-49fb-b879-04c546041cbf

**Comment by brentvatne** [comment]
@ornakash - can you try running the build again? possibly an intermittent error

**Comment by brentvatne** [comment]
it looks like you ran the build again afterwards and it completed successfully, let me know if this happens again :)

**Comment by HansAarneLiblik** [comment]
This issue repros with us also
Same conf (Android, SDK 41, managed) and same thing in logs for at least 3 retries

build: https://expo.io/accounts/hansaarneliblik/builds/604367b9-9db0-40d2-9d04-266337166e05

**Comment by HansAarneLiblik** [comment]
Seems like it passed that step now and proceeded wit ha build

```
....
> Task :app:mergeReleaseGeneratedProguardFiles
> Task :app:minifyReleaseWithR8
> Task :app:stripReleaseDebugSymbols
Unable to strip the following libraries, packaging them as they are: libc++_shared.so, libexpo-gl.so, libface_detector_v2_jni.so, libfb.so, libfbjni.so, libfolly_futures.so, libfolly_json.so, libgifimage.so, libglog.so, libglog_init.so, libhermes-executor-debug.so, libhermes-executor-release.so, libhermes-inspector.so, libimagepipeline.so, libjsc.so, libjscexecutor.so, libjsijniprofiler.so, libjsinspector.so, libnative-filters.so, libnative-imagetranscoder.so, libreactnativeblob.so, libreactnativejni.so, libreanimated.so, libstatic-webp.so, libturbomodulejsijni.so, libyoga.so.
> Task :app:packageRelease
> Task :app:assembleRelease
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL
 in 5m 25s
29 actionable tasks: 29 executed
```

**Comment by JPSantistebanQ** [comment]
Same issue SDK 41

https://expo.io/accounts/jpsantq/builds/156062b1-5fbd-4136-9a32-cd4a62a099b7/logs

**Comment by chankokkuan** [comment]
We are facing this issue too.
https://expo.io/accounts/gotsurge/builds/0ec31575-8b5e-4583-b1cf-713d4dddd0e2

Expo CLI: 4.4.1
expo: ^41.0.0 => 41.0.0
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
Expo Workflow: managed

**Comment by brentvatne** [comment]
thanks for the reports! you should be able to re-run your build to have it work, we'll investigate why this is happening intermittently for some folks

**Comment by chankokkuan** [comment]
Failed 6 times in a row and didn't manage to get a successful build for Android after upgraded to SDK 41. Will keep trying to re-run the build. Hope to hear any solution soon.

**Comment by brentvatne** [comment]
@wkozyra95 investigated this and suspects that it is possibly related to memory limits and apps that include large assets, he is testing out increasing that on staging

**Comment by wkozyra95** [comment]
Memory limit was reached sometimes for apps with large assets (not sure if it was about the size of separate files or summary size of all assets). 2 hours ago I released to prod workers with increased memory limit, and I don't see errors like that anymore in logs, please post here if you see that issue again.

**Comment by jadenaxel** [comment]
Same issue 😒😒

**Comment by wkozyra95** [comment]
@jadenaxel I didn't see anything like that in logs(i checked the past 5 days). Can you provide a link to the build with that error?

**Comment by jadenaxel** [comment]
@wkozyra95 https://expo.io/accounts/jondydiaz07/projects/microsofts/builds/aa03dbf0-ed38-4320-b0a3-7bf0d3875b34

**Comment by wkozyra95** [comment]
It's not the same, error displayed in your build logs is totally different and message there is quite clear

```
AAPT: error: invalid color.
```

and you have "backgroundColor":"##E6E6E6" in your app.json

**Comment by jadenaxel** [comment]
@wkozyra95 Thank you.

**Comment by geomen888** [comment]
Same Issue
https://expo.io/accounts/geodoc/builds/d00c790c-495e-421b-b732-7ea996ba1ae1

Expo CLI: 4.4.1
expo: ^41.0.0 => 41.0.0
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1

Build Failed

**Comment by brentvatne** [comment]
@geomen888 - this doesn't look like the same issue. it looks like your google services file is missing. make sure you've committed it to source control

**Comment by AMoktar** [comment]
same issue

**Comment by wkozyra95** [comment]
@AMoktar it should be fixed now

**Comment by am2619015** [comment]
Keeps happening on Android and IOS, but i think is a compatibility issue whit current sdk, when SDK 47 supports react native 0.70.2 this should be fixed

`Execution failed for task ':expo-gl-cpp:buildCMakeRelWithDebInfo[arm64-v8a]'.
> Build command failed.
  Error while executing process /Users/[username]/Library/Android/sdk/cmake/3.18.1/bin/ninja with arguments {-C /Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/.cxx/RelWithDebInfo/212o5a5c/arm64-v8a expo-gl}
  ninja: Entering directory `/Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/.cxx/RelWithDebInfo/212o5a5c/arm64-v8a'
  
  ninja: error: '/Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/build/react-native-0.70.3-debug.aar/jni/arm64-v8a/libjsi.so', needed by '/Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/build/intermediates/cxx/RelWithDebInfo/212o5a5c/obj/arm64-v8a/libexpo-gl.so', missing and no known rule to make it

Task :expo-gl-cpp:buildCMakeRelWithDebInfo[arm64-v8a] FAILED
 needed by '/Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/build/intermediates/cxx/RelWithDebInfo/212o5a5c/obj/arm64-v8a/libexpo-gl.so', missing and no known rule to make it`

**Comment by am2619015** [comment]
Keeps happening on Android and IOS, but i think is a compatibility issue whit current sdk, when SDK 47 supports react native 0.70.2 this should be fixed
```

Execution failed for task ':expo-gl-cpp:buildCMakeRelWithDebInfo[arm64-v8a]'.
> Build command failed.
  Error while executing process /Users/[username]/Library/Android/sdk/cmake/3.18.1/bin/ninja with arguments {-C /Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/.cxx/RelWithDebInfo/212o5a5c/arm64-v8a expo-gl}
  ninja: Entering directory `/Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/.cxx/RelWithDebInfo/212o5a5c/arm64-v8a'
  
  ninja: error: '/Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/build/react-native-0.70.3-debug.aar/jni/arm64-v8a/libjsi.so', needed by '/Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/build/intermediates/cxx/RelWithDebInfo/212o5a5c/obj/arm64-v8a/libexpo-gl.so', missing and no known rule to make it

Task :expo-gl-cpp:buildCMakeRelWithDebInfo[arm64-v8a] FAILED
 needed by '/Users/[username]/Desktop/G900/g900_org/node_modules/expo-gl-cpp/android/build/intermediates/cxx/RelWithDebInfo/212o5a5c/obj/arm64-v8a/libexpo-gl.so', missing and no known rule to make it

```
"react": "18.2.0",
"react-native": "0.70.3",
"expo": "46.0.15",
"expo-gl": "11.4.0",
"expo-three": "^6.2.0",
