### ISSUE TITLE
expo-image-picker. Not correct dimensions for vertical video 

### ISSUE THREAD

**Issue by rusakovic** [expo/expo#12573]
### Summary

`ImagePicker.launchImageLibraryAsync` returns `weight` and `height` for video.
For vertical video it returns not correct dimension. For example, 1280x720, but should be 720x1280.

Maybe it's possible to handle video orientation.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.3.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 7.0.15 - ~/.nvm/versions/node/v15.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.3.5
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. Record vertical video on iPhone (for example, from iPhone SE the resolution will be 720x1280)
2. Save video to iPhone files
3. Check 'info' of file
4. Dimension is 1280x720 that is not correct!
5*. If you share the same file to macOS, the dimension will be correct.

**Comment by dandre-hound** [comment]
Same issue here -- looking into it now.

**Comment by dandre-hound** [comment]
I was able to fix this by referencing the PHAsset inside the info dictionary instead of the AVUrlAsset:

```
    // adding information about asset
    // AVURLAsset *asset = [AVURLAsset URLAssetWithURL:fileURL options:nil];
    // CGSize size = [[[asset tracksWithMediaType:AVMediaTypeVideo] objectAtIndex:0] naturalSize];

    PHAsset *phasset = info[UIImagePickerControllerPHAsset];
    CGSize size = CGSizeMake(phasset.pixelWidth, phasset.pixelHeight);
        
    response[@"width"] = @(size.width);
    response[@"height"] = @(size.height);
    
    if (!response[@"duration"]) {
        // CMTime duration = [asset duration];
        response[@"duration"] = @(phasset.duration);
    }
```

**Comment by rusakovic** [comment]
@dandre-hound  I suppose your suggestion could help to improve this package

**Comment by dandre-hound** [comment]
@rusakovic I could open a PR but I'm not very familiar with java. If I open a PR, do you think someone from the expo team could take over and work on that platform?

**Comment by angusmccloud** [comment]
@rusakovic  - Did you ever find a solution for this?
