### ISSUE TITLE
Error: Unable to deactivate keep awake. However, it probably is deactivated already.

### ISSUE THREAD

**Issue by sachin3072004** [expo/expo#12584]
### Summary

Once I launch the app in the Android emulator and If I press the back button(triangle shaped) and then press the Square shaped button on the Android emulator and try to relaunch the app I see the following error message.

Possible Unhandled Promise Rejection (id: 0): Error: Unable to deactivate keep awake. However, it probably is deactivated already. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.4 - /usr/local/bin/node
      npm: 7.7.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1) Create a new app by using the following command.
npx create-react-native-app notification
2) Following command is used to launch the app.
react-native run-android
3) After app is launched, press back button(Triangle shaped) on android emulator.
4) Now press the Sqaure shaped button on the emulator and launch the app again.

**Comment by cruzach** [comment]
I followed those steps to reproduce, and still couldn't. Does this happen every single time for you? What Android version?

**Comment by sachin3072004** [comment]
Yes, It is happening every single time. Android version:10

**Comment by Gogn** [comment]
Same here, happening only on real Android devices.

**Comment by byCedric** [comment]
Sorry for the delay people. I just opened a PR with a fix based on `expo@42.0.0-beta.2`. If you can't wait until this fix is merged + released, [here is a patch](https://github.com/expo/expo/files/6733504/expo%2B42.0.0-beta.2.patch.txt) that you can use with [patch-package](https://github.com/ds300/patch-package). Rename the `.patch.txt` to `.patch`, Github doesn't accept `.patch` files 😅

**Comment by vinay-khatri** [comment]
Same error on app relaunch after exiting the app with back button.

@byCedric your fix for pull request has failed tests. Hope it doesn't break apps.

Can you tell the command to apply your patch ?

**Comment by bj97301** [comment]
I am having this error on expo 49 with android:
Unable to deactivate keep awake. However, it probably is deactivated already.

any ideas whats going on and why it might be poping up again?
