### ISSUE TITLE
Library not found for -lEXConstants

### ISSUE THREAD

**Issue by Hektar90** [expo/expo#12589]
### Summary

iOS release build fails but it's working with debug build.

<img width="1530" alt="Bildschirmfoto 2021-04-19 um 09 14 13" src="https://user-images.githubusercontent.com/15243732/115196456-36fbd100-a0f0-11eb-8404-325c70d31fa8.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.0 => 0.64.0 
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

I thought this could be related to #5760 but my linker flags looks like this: 

<img width="1651" alt="Bildschirmfoto 2021-04-19 um 09 17 09" src="https://user-images.githubusercontent.com/15243732/115196477-3ebb7580-a0f0-11eb-95e9-73e52ef61dd5.png">

You can reproduce this issue as follows: 

1. Create an new react native project with :  
` npx react-native init Test --template react-native-template-typescript`
(I am using typescript...i don't know if this has an effect on this issue)
2. Install react-native-unimodules and configure it as shown in the [documentation](https://docs.expo.io/bare/installing-unimodules/)
3. Edit scheme in xcode to release and build

**Comment by byCedric** [comment]
Hi @Hektar90, could you provide a reproducible example? You only provided a screenshot, but this is not enough for us to investigate possible issues.

**Comment by Hektar90** [comment]
Hi @byCedric. Sure I just tested it with a bare react native project with ract-native unimodules installed.

You can reproduce this issue as follows: 

1. Create an new react native project with :  
` npx react-native init Test --template react-native-template-typescript`
(I am using typescript...i don't know if this has an effect on this issue)
2. Install react-native-unimodules and configure it as shown in the [documentation](https://docs.expo.io/bare/installing-unimodules/)
3. Edit scheme in xcode to release and build

I am getting the same error

<img width="1651" alt="Bildschirmfoto 2021-04-19 um 13 10 54" src="https://user-images.githubusercontent.com/15243732/115227430-c0230000-a110-11eb-8eed-26f29577aa74.png">

**Comment by Hektar90** [comment]
Fixed the issue. 

My iOS Deployment Target in xCode was 10.0.

I've change it under Build Settings/Deployment/iOS Deployment Target to 11.0 and now it's working. Perhaps it's worth mentioning in the docs for others. 

Cheers

**Comment by gulsher7** [comment]
> Fixed the issue.
> 
> My iOS Deployment Target in xCode was 10.0.
> 
> I've change it under Build Settings/Deployment/iOS Deployment Target to 11.0 and now it's working. Perhaps it's worth mentioning in the docs for others.
> 
> Cheers

thank your very much 💯
