### ISSUE TITLE
How to remove a MANAGE_EXTERNAL_STORAGE permission?

### ISSUE THREAD

**Issue by AntonioHReyes** [expo/expo#12580]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by AntonioHReyes** [comment]
Currently I have the android permissions as an empty array, however the play console has detected that I am using the MANAGE_EXTERNAL_STORAGE permission and I can't find how to remove it from the application

**Comment by ide** [comment]
There have been several reports of this issue across many Android apps (not specific to Expo). Check the permissions inside the APK archive -- there is a good chance you aren't actually requesting `MANAGE_EXTERNAL_STORAGE` and there is an error / false alarm on Google Play's side.

**Comment by AntonioHReyes** [comment]
@ide Reviewing the generated apk and informing me a little more about the issue I have noticed that google asks to add the permission of MANAGE_EXTERNAL_STORAGE if this requestLegacyExternalStorage flag is enabled with which the apk will have access to the files in the root of the storage, however my app does not makes use of those files, do you know if we can disable this flag? or does expo make use of such data?

Also derived from the fact that the only applications that can make use of this permission are those derived from document management as appears in the following article

https://support.google.com/googleplay/android-developer/answer/10467955#zippy=%2Cpermitted-uses-of-the-all-files-access-permission

**Comment by cruzach** [comment]
hey @AntonioHReyes , wrote up a post about this [here](https://github.com/expo/expo/issues/12603), so I'm going to close this issue in favor of that one
