### ISSUE TITLE
How to get gravity vector? 

### ISSUE THREAD

**Issue by HadiModarres** [expo/expo#12582]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

Hi there,

I need to get the gravity vector like outlined at https://developer.apple.com/documentation/coremotion/cmdevicemotion/1616164-gravity
Can you tell me if this is possible with expo-sensors? I haven't been able to find it

I need to detect rotation rate with reference to the world not device frame and I need the gravity vector to combine it with data from DeviceMotion.rotationRate

**Comment by HadiModarres** [comment]
thanks for the help

**Comment by cruzach** [comment]
We state in the issue description that questions will be closed since we use GitHub is for bug reports, and you should use our forums or discord for questions.

You can also text-search "gravity" in our docs and this is the result- https://docs.expo.io/versions/latest/sdk/devicemotion/#arguments

**Comment by HadiModarres** [comment]
The documentation you sent, doesn't give you a gravity vector, that's the acceleration comprised of user acceleration plus gravity. Thanks for teaching me about the critical skill of text search ...
