### ISSUE TITLE
[html-elements] Type definitions for Anchor / A correct?

### ISSUE THREAD

**Issue by davemurphysf** [expo/expo#12588]
### Summary

Hi, I'm opening this as a presumed bug but if I'm wrong, of course feel free to close.

I found the `html-elements` package via Evan's [blog post](https://dev.to/evanbacon/react-native-for-web-developers-1pi0), however the type definitions don't match the examples in Evan's blog or the [readme](https://github.com/expo/expo/tree/master/packages/html-elements#a).

The example in the readme: 
```javascript
import { A } from '@expo/html-elements';

export default () => <A href="#" target="_blank" />;
```
However, Typescript throws the following error:
>Type '{ children: string; href: string; target: string; }' is missing the following properties from type 'Pick<TextProps & ClassAttributes<typeof Text>, "allowFontScaling" | "ellipsizeMode" | "lineBreakMode" | "numberOfLines" | "onLayout" | "onTextLayout" | ... 29 more ... | "ref">': 

Based on my limited knowledge of Typescript utility types, I don't think you can use `Pick` as it is currently used in the type definition:
```javascript
import React from 'react';
export declare const A: React.ComponentType<React.PropsWithChildren<Pick<import("react-native").TextProps & React.ClassAttributes<typeof import("react-native").Text>, "allowFontScaling" | "ellipsizeMode" | "lineBreakMode" | "numberOfLines" | "onLayout" | "onTextLayout" | "onPress" | "onLongPress" | "testID" | "nativeID" | "maxFontSizeMultiplier" | "adjustsFontSizeToFit" | "minimumFontScale" | "suppressHighlighting" | "selectable" | "selectionColor" | "textBreakStrategy" | "accessible" | "accessibilityActions" | "accessibilityLabel" | "accessibilityState" | "accessibilityHint" | "accessibilityValue" | "onAccessibilityAction" | "accessibilityComponentType" | "accessibilityLiveRegion" | "importantForAccessibility" | "accessibilityElementsHidden" | "accessibilityTraits" | "accessibilityViewIsModal" | "onAccessibilityEscape" | "onAccessibilityTap" | "onMagicTap" | "accessibilityIgnoresInvertColors" | "key" | "ref"> & import("../primitives/Text").WebTextProps & {
    href?: string | undefined;
    target?: string | undefined;
}>>;
```

This is what I did to make Typescript happy:
```javascript
<A
    accessible={undefined}
    accessibilityActions={undefined}
    accessibilityComponentType={undefined}
    accessibilityElementsHidden={undefined}
    accessibilityHint={undefined}
    accessibilityLabel={undefined}
    accessibilityLiveRegion={undefined}
    accessibilityState={undefined}
    accessibilityTraits={undefined}
    accessibilityValue={undefined}
    adjustsFontSizeToFit={undefined}
    allowFontScaling={undefined}
    ellipsizeMode="tail"
    href={to}
    importantForAccessibility={undefined}
    lineBreakMode={undefined}
    maxFontSizeMultiplier={undefined}
    minimumFontScale={undefined}
    nativeID={undefined}
    numberOfLines={undefined}
    onAccessibilityAction={undefined}
    onLayout={undefined}
    onLongPress={undefined}
    onTextLayout={undefined}
    selectable={undefined}
    selectionColor={undefined}
    suppressHighlighting={undefined}
    testID={undefined}
    textBreakStrategy={undefined}
>
    Link Text
</A>
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### Environment

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild

### Reproducible demo or steps to reproduce from a blank project
```javascript
import { A } from '@expo/html-elements';
import React from 'react';
import { TextProps } from 'react-native';


const WebNavLink = ({
    to,
    title,
    style,
}: { to: string; title: string } & TextProps) => (
    <A href={to} target="_blank" style={style}>{title}</A>
);

export default WebNavLink;
```

**Comment by byCedric** [comment]
Hi @davemurphysf! Thanks for the issue report, this is definitely not something we'd expect. I think it might be related to [this old typescript issue #20722](https://github.com/microsoft/TypeScript/issues/20722). This might be happening:

- We [use `Omit` on this line](https://github.com/expo/expo/blob/master/packages/html-elements/src/primitives/Text.tsx#L43) to override the `style` and hard code the `accessibilityRole`.
- That same [`Omit` is converted to `Pick`](https://github.com/expo/expo/blob/master/packages/html-elements/build/elements/Anchor.d.ts#L2) when built to definition files ([this is why](https://stackoverflow.com/a/62171054/2277025))
- In the issue linked above, `Pick` changes the behavior of optional properties. That would mean that `Pick<{ foo?: string } | { foo?: string }, 'foo'>` is the same as `{ foo: string }`.

I noticed the `Anchor` isn't the only one with this problem, its every component using `Pick` in their props like `Quote`, `BlockQuote`, and `Time`.
