### ISSUE TITLE
[expo-location][sdk41] startLocationUpdatesAsync got broken in permissions refactoring

### ISSUE THREAD

**Issue by MaRaSu** [expo/expo#12581]
### Summary

On iOS startLocationUpdatesAsync was working in SDK40 with "foreground" permission only i.e. with "allow when in use", with iOS showing a small UI notification to user on location being active when app was in the background. Refactoring of permissions in SDK41 broke that as startLocationUpdatesAsync checks for background permission on iOS, which is not needed.

For Android this type of location service was enabled with PR #12456 - please note that this capability was available all along for iOS until refactoring in SDK41 broke it.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK41

### Environment

  Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
      npm: 7.5.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Please run @byCedric example app "Office Marathon" in iOS in SDK40 vs. SDK41. 

In SDK40 you can start `startLocationUpdatesAsync` with 'when in use" permissions and you do get the location updates when you app is not in foreground or device display is off, with the similar UI notification as in Android foreground service.

in SDK41 refactoring done / committed by @lukmccall in `EXLocation.m` prevents `startLocationUpdatesAsync` without background permissions, which I understood to be 'always' in iOS UI terminology. Again, note that I do not want to ask from user 'always' permission because it's not needed for this use case - it's the same as in Android.

**Comment by MaRaSu** [comment]
As discussed extensively in issue #11854 and later in PR #12456 I continue to dislike this split of location services types to just "foreground" vs. "background" location service because both do indeed exist but so does this "foreground service with a persistent UI notification AND with effectively a background service type of capability" type of service both on iOS and Android. This continues to be a source of confusion.

**Comment by MaRaSu** [comment]
I tested this now on Android Expo Go too and got also `Error: Not authorized to use background location services.`. Used both my own app as well as @byCedric "Office Marathon" (upgraded to SDK41 + did small permissions code changes to use new refactored way of asking via `Location.requestForegroundPermissionsAsync()`.

Android Expo Go v. 2.19.2 and iOS 2.19.1.101.

**Comment by MaRaSu** [comment]
@lukmccall your PR #12594 looks good to me. Before closing this issue, please note my comment on this also failing on Android. Android failure I do not understand because that was exactly what @byCedric fixed earlier with another PR. Could it be missing from the Expo Go App release 2.19.2?

**Comment by lukmccall** [comment]
@MaRaSu changes made by Cedric should be included in the release 2.19.2. I don't know yet why it doesn't work on Android.

**Comment by MaRaSu** [comment]
@lukmccall did you or @byCedric test it as well and have it failing? It would be good if someone could confirm my findings and repeat the problem.

**Comment by lukmccall** [comment]
Unfortunately, I didn't test that yet on Android

**Comment by byCedric** [comment]
I'm testing this now on Android and the Play Store. I think Expo Go might have an older `expo-location` version embedded. If that's the case, an EAS build should solve this (it uses the package versions, not the Expo Go client). I'll edit this comment and add a test link for the play store so you can test it if you want @MaRaSu  😄

**Comment by MaRaSu** [comment]
@byCedric thx for response and explaining how the packages system works with build system! I need to anyways (unfortunately) eject from managed workflow soon to get latest version of react-native-maps in my app so I'll get to test this then also.

**Comment by superyarik** [comment]
today i have rebuild my app on SDK41 using managed workflow and "expo-cli bi" command, send it to testflight, install to iphone 5s.
then i call "requestForegroundPermissionsAsync", approve, then call "requestBackgroundPermissionsAsync", anser "allow when in use" and getting error 
LOCATION_BACKGROUND permission is required to do this operation.
when i try to call "startLocationUpdatesAsync"

everything work before, but looks like #12594 not applies to old iphone @byCedric ?

**Comment by superyarik** [comment]
@lukmccall look like need to reopen it?

**Comment by brentvatne** [comment]
#12594 didn't end up getting included in sdk 41, but it will be included in sdk 42. until then you'll need to customize native code to be able to use the patch ([like this](https://github.com/expo/expo/pull/12594#issuecomment-830628978)) - more info in [this guide](https://docs.expo.io/workflow/customizing/). as for the particular error you see, can you share some code that reproduces it exactly? also do you have UIBackgroundModes set? https://docs.expo.io/versions/v41.0.0/sdk/task-manager/#background-modes-on-ios

**Comment by superyarik** [comment]
@brentvatne 
"UIBackgroundModes": ["location"]
steps to reproduce in https://github.com/expo/expo/issues/12581#issuecomment-848246456

i use redux saga, but it almost like async await logic here

```
const permitionForegroundRusult = yield call(Location.requestForegroundPermissionsAsync);
const permitionBackgroundRusult = yield call(Location.requestBackgroundPermissionsAsync);
const { status: backgroundStatus } = permitionBackgroundRusult;
const { status: foregroundStatus } = permitionForegroundRusult;
if (foregroundStatus === 'granted') {
yield call(Location.startLocationUpdatesAsync, BACKGROUND_LOCATION_UPDATES_TASK, {
                accuracy: Location.Accuracy.High,
                timeInterval: 1000 * 60 * LOCATIONS_UPDATE_PERIOD_IN_MINUTES,
                deferredUpdatesInterval: 1000 * 10,
                distanceInterval: LOCATIONS_UPDATE_DISTANSE_IN_METERS,
                showsBackgroundLocationIndicator: false,
                foregroundService: {
                    notificationTitle: 'title ',
                    notificationBody: 'comment',
                }
            });
}
```

so, as i write before, if i choose "when in use" in requestBackgroundPermissionsAsync, startLocationUpdatesAsync will fall with "LOCATION_BACKGROUND permission is required to do this operation." 
yep, i can see to the backgroundStatus and wrap it all to try catch, but all this steps recuce number of people who can solve quest for sending geolocation in background in my app :(
why it is not included in managed builds for SKD41?
