### ISSUE TITLE
FileSystem method: it always throw error while passing a path contain foreign language words as param. 

### ISSUE THREAD

**Issue by ibearye** [expo/expo#12591]
### Summary

when I pass a path contain some Chinese words to the `FileSystem.getInfoAsync`, `FileSystem.makeDirectoryAsync` or other methods, it throw error that like ‘xxxxxx – file:/// isn’t readable’ or ‘xxxxxx – file:/// isn’t writable’.

when I run the code:

```
FileSystem.getInfoAsync(documentDirectory + '你好')
  .then(value => {
    console.log(value);
  })
  .catch(e => {
    console.log(e.message);
  });
```
the error is like:
```
File 'file:/Users/xxxxx/Library/Developer/CoreSimulator/Devices/DE44D203-53C6-4E51-85EF-73E2D2459FBF/data/Containers/Data/Application/AEBABDB5-6C44-4DA9-A064-0AD1DB84F744/Documents/ExponentExperienceData/%252540bearye%25252FMarker/%E4%BD%A0%E5%A5%BD -- file:///' isn't readable.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.0

### Environment

```
Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.5.0 - /usr/local/opt/nvm/versions/node/v15.5.0/bin/node
      npm: 7.7.5 - /usr/local/opt/nvm/versions/node/v15.5.0/bin/npm
      Watchman: 20201120.183554.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: managed

```

### Reproducible demo or steps to reproduce from a blank project

run the code:
```
import * as FileSystem from 'expo-file-system';
const documentDirectory = FileSystem.documentDirectory;
FileSystem.getInfoAsync(documentDirectory + '你好')
  .then(value => {
    console.log(value);
  })
  .catch(e => {
    console.log(e);
  });
```

this is thrown error :
```
File 'file:/Users/bearye/Library/Developer/CoreSimulator/Devices/DE44D203-53C6-4E51-85EF-73E2D2459FBF/data/Containers/Data/Application/AEBABDB5-6C44-4DA9-A064-0AD1DB84F744/Documents/ExponentExperienceData/%252540bearye%25252FMarker/%E4%BD%A0%E5%A5%BD -- file:///' isn't readable.
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
at node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-file-system/build/FileSystem.js:25:17 in getInfoAsync
at node_modules/expo-file-system/build/FileSystem.js:21:7 in getInfoAsync
at [native code]:null in eval
at [native code]:null in forEach
at node_modules/react-native/Libraries/WebSocket/WebSocket.js:231:8 in _eventEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
at [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by mitsuki1995** [comment]
Same issue for me, and only occur on iOS/macOS.
You can encode your uri or path.
`'你好' -> encodeURI('你好')`

![image](https://user-images.githubusercontent.com/38064997/115652610-294c8280-a360-11eb-9b53-356d3782d52b.png)

In your case, uriString is "file://xxxxx/你好". NSURL does not support Chinese, you will get a null uri, so uri.schema is null, will handle as a local path(but uriString is not a local path).

**Comment by ibearye** [comment]
> Same issue for me, and only occur on iOS/macOS.
> You can encode your uri or path.
> `'你好' -> encodeURI('你好')`
> 
> ![image](https://user-images.githubusercontent.com/38064997/115652610-294c8280-a360-11eb-9b53-356d3782d52b.png)
> 
> In your case, uriString is "file://xxxxx/你好". NSURL does not support Chinese, you will get a null uri, so uri.schema is null, will handle as a local path(but uriString is not a local path).

It works, but not absolutely. If there is one child folder named `你好` in `file://xxx/`, when I call `FileSystem.getInfoAsync` and pass `file://xxx/` as param, error still be thrown.
