### ISSUE TITLE
[AppleAuthentication][docs]  AppleAuthentication.signOutAsync() is not documented 

### ISSUE THREAD

**Issue by wodow** [expo/expo#12598]
### Summary

[AppleAuthentication.signOutAsync()](https://github.com/expo/expo/blob/3f978ec39f1cc69d9672c68dd7ae8b13083c91ff/packages/expo-apple-authentication/src/AppleAuthentication.ts#L61) is not documented in the [package's docs](https://github.com/expo/expo/blob/sdk-41/docs/pages/versions/unversioned/sdk/apple-authentication.md).

This makes it appear as though the package has no sign out function/method.

### Link to the related docs page

https://docs.expo.io/versions/latest/sdk/apple-authentication/#methods

**Comment by brentvatne** [comment]
@Simek - maybe this is a good library to target next for automated docs :)

**Comment by Simek** [comment]
Good idea. I will work on converting this package next, with a backport to v41 docs (if there were no changes since release).

**Comment by wodow** [comment]
Thank you !
