### ISSUE TITLE
[docs] react-native-unimodules installation guide is outdated

### ISSUE THREAD

**Issue by yfunk** [expo/expo#12593]
### Summary

After updating `expo-av` (`^9.0.0  →   ^9.1.2 `) and `react-native-unimodules` (`^0.12.0  →  ^0.13.3`) in my bare workflow app the Android build was failing with the following message, even though the setup was done according to the [documentation](https://docs.expo.io/bare/installing-unimodules/).
```
> Task :expo-permissions:compileDebugKotlin FAILED

e: C:\Users\[...]\node_modules\expo-permissions\android\src\main\java\expo\modules\permissions\requesters\BackgroundLocationRequester.kt: (12, 50): Unresolved reference: R
e: C:\Users\[...]\node_modules\expo-permissions\android\src\main\java\expo\modules\permissions\requesters\BackgroundLocationRequester.kt: (19, 52): Unresolved reference: R
e: C:\Users\[...]\node_modules\expo-permissions\android\src\main\java\expo\modules\permissions\requesters\BackgroundLocationRequester.kt: (40, 36): Unresolved reference: R
```

The solution to this was bumping `buildToolsVersion`, `compileSdkVersion`, `targetSdkVersion` to SDK 30 in my project build settings like [Expo recently did](https://github.com/expo/expo/commit/b488c6555230ac57e8e6cce0b3b03588f3263f93) for all modules. 
```
ext {
    buildToolsVersion = "30.0.0"
    minSdkVersion = 21
    compileSdkVersion = 30
    targetSdkVersion = 30
}
```

The documentation for installing `react-native-unimodules` in a bare React Native App should be updated to reflect these new requirements. I didn't submit a PR myself, because I'm not sure if anything else is outdated, so it would probably be best if someone a little more familiar with the project had a quick look at this.

It also seems  other people [on the forums](https://forums.expo.io/t/unresolved-reference-in-expo-permissions-backgroundlocationrequester-kt/51363) are running into the same issue.

### Link to the related docs page

https://docs.expo.io/bare/installing-unimodules/

**Comment by brentvatne** [comment]
thanks for pointing this out! fixed
