### ISSUE TITLE
"Metro bundler has encountered an internal error" with a new exp project

### ISSUE THREAD

**Issue by onpaws** [expo/expo#1260]
Hi Expo team, @terribleben
This issue is intended for [exp](https://github.com/expo/exp).

For the past ~7 days, new Expo projects created with `exp` crash on startup.
Something is off with Metro bundler.

It's a bummer that the first thing that new Expo users experience is literally a blocking crash like this - I've enjoyed using Expo on previous projects, but unfortunately our team can't even get started at the moment.

Other folks also have this [issue](https://github.com/facebook/metro/issues/110).

Affected platforms: iOS. Haven't checked Android. 
Environments: Physical devices, iOS Simulator.
Template: blank
dev environment: macOS 10.13.2, node 9.4.0, exp 47.4.4

**Comment by brentvatne** [comment]
@onpaws - we need more information than this because I cannot reproduce it. I just did `exp init` and started the project on my phone and simulator and there was no issue. I deleted node_modules and ran `yarn` again and it worked as expected. It's quite possible that this is a bug with npm5 if you're using `npm install` rather than yarn. I'd suggest using yarn because npm5 is very buggy still. for example, if you `exp init` a project and then run `npm install redux --save` inside of the project, if you're using npm5 it will delete every package that you already have installed and only install redux and its dependencies.

**Comment by onpaws** [comment]
Thanks for the quick reply @brentvatne. I'm putting together a repro for you. stay tuned

**Comment by onpaws** [comment]
Right, thanks for the heads up about npm5 bugginess, I'm familiar the history hasn't been perfect.
FWIW I've been using yarn exclusively for this.
Here's my terminal output:

```
paws at Hedy in /tmp
$ yarn global add exp
yarn global v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info @expo/traveling-fastlane-linux@1.2.5: The platform "darwin" is incompatible with this module.
info "@expo/traveling-fastlane-linux@1.2.5" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "exp@47.4.4" with binaries:
      - exp
✨  Done in 2.49s.

paws at Hedy in /tmp
$ node -v
v9.4.0

paws at Hedy in /tmp
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C205

paws at Hedy in /tmp
$ exp -V
47.4.4

paws at Hedy in /tmp
$ exp init repro
? Choose a template type: blank
[exp] Downloading project files...
[exp] Extracting project files...
[exp] Customizing project...
[exp] Starting project...
[exp] Your project is ready at /private/tmp/repro. Use "exp start /private/tmp/repro" to get started.

paws at Hedy in /tmp
$ cd repro/

paws at Hedy in /tmp/repro on master [?]
$ exp start
[exp] Using project at /private/tmp/repro
[exp] Starting React Native packager...
[exp] Scanning folders for symlinks in /private/tmp/repro/node_modules (23ms)
[exp] Loading dependency graph.
[exp] Tunnel connected.
[exp] Expo is ready.
[exp] Dependency graph loaded.
[exp] You can scan this QR code:

                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                

[exp] Your URL is: exp://zx-zuq.paws.repro.exp.direct:80
[exp] Logs for your project will appear below. Press Ctrl+C to exit.
```

**Comment by onpaws** [comment]
Ok, so I'm not sure I understand _how_ but I seem to have just fixed my issue.

**Comment by onpaws** [comment]
Perhaps at some point in the past I installed an exp dependency with npm5? Would that potentially be a cause?

Regardless I'll share this over on the Metro issue thread so other folks can try. Thanks @brentvatne I imagine this will help the other folks who got blocked by this.

**Comment by brentvatne** [comment]
wow that's pretty strange, I wouldn't have expected this to be caused by a global install of exp with npm 5... hum...

**Comment by onpaws** [comment]
So the error came back. :/
I tried my previous fix but no bueno.
Really weird...

How can I best help you reproduce?

**Comment by ide** [comment]
Since we're unable to repro the issue and it looks potentially specific to your computer, I think the best course of action would be to start adding console.log statements under node_modules/metro to bisect where the issue lies. Finding out what that "internal error" is the first step we need.

**Comment by onpaws** [comment]
Thanks @ide appreciate your attention.
Yeah, it seems specific to some [folks](https://github.com/facebook/metro/issues/110).

I'll be giving your suggestion a try when I'm back in the office, should have cycles early next week.

**Comment by skabbes** [comment]
In case anyone finds this issue looking for resolution, I resolved this by upgrading @expo/vector-icons to the latest version.

**Comment by mickadoua** [comment]
@skabbes i update to "@expo/vector-icons": "^6.2.2"  and i still get this error

**Comment by nukes88** [comment]
im using node 8, npm 4, yarn, created a blank new project and am getting this error.
It loads ok the first time, then i press save on any file then this error will pop up.

**Comment by nukes88** [comment]
OK the weird thing is, my errors were coming from my PC at home.
I reformatted it not too long ago so almost everything is newly installed.

At work i did the same steps and everything is working fine.

**Comment by GentryRiggen** [comment]
Fam,
I fixed my issue and like most of them, it's completely my fault. I was refactoring and deleted some files without cleaning up some imports of the deleted files. The only way I found this was to add a console.log like @ide suggested in metro (node_modules/metro/src/lib/formatBundlingError.js).

`function formatBundlingError(error) { console.log(error); }`

**Comment by nukes88** [comment]
doesn't explain my fresh project setup though

**Comment by GentryRiggen** [comment]
@nukes88 did you try adding the console.log?

**Comment by nukes88** [comment]
console doesnt show anything, but i added something to the message:
![image](https://user-images.githubusercontent.com/7161751/35514812-644b62da-0542-11e8-9f16-4af501925ddb.png)
"EBUSY", what does that mean? something "using" something?

**Comment by onpaws** [comment]
@nukes88 thanks for the report.

I agree it may be an `npm` issue, but seeing as I'm on a Mac I don't think it's a Windows-only issue.

**Comment by GentryRiggen** [comment]
@onpaws agreed. I am on a Mac as well. I think this issue is not caused by a singular error. Metro bundled just reports the error generically.

**Comment by pyankoff** [comment]
Had this error after adding `username/repo` git dependency, changing to  `git@github.com:username/repo.git` solved the issue

**Comment by mgambati** [comment]
Removed `"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz"` fork from expo and moved to official one. Everthing working now.

**Comment by sjchmiela** [comment]
Clean new `expo` projects shouldn't have this problem anymore. 🙂

**Comment by NikhilDwa** [comment]
I do had the same problem but the following code worked

step 1
(in project directory) mkdir android/app/src/main/assets

step 2
sudo su

step 3
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

step4
react-native run-android
