### ISSUE TITLE
How to debug styles?

### ISSUE THREAD

**Issue by chiefGui** [expo/expo#1261]
Hey guys!

This question is probably very dumb but I can't figure it myself. So, my question is: how to debug styles on-the-fly with CRNA + Expo?

When developing an webapp, we just open the Inspector in Chrome and voi là, but not sure how to achieve this using the Expo's Client in pair with React Native.

Thank you in advance.

**Comment by riwu** [comment]
![](https://i.imgur.com/D0BnonV.png)
Bring up this window (for physical device, shake it), then click Toggle Element Inspector.

There's a standalone one here as well https://github.com/jhen0409/react-native-debugger

**Comment by terribleben** [comment]
riwu is correct, you can use the react element inspector. There is more documentation [here](https://facebook.github.io/react-native/docs/debugging.html).
