### ISSUE TITLE
react-native-webview cannot be displayed in Expo web

### ISSUE THREAD

**Issue by fungmo** [expo/expo#12611]
### Summary

I try to build my web application with Expo. In the details page, I want to render the Html file of the server. But it cannot be displayed.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41

### Environment

```base
Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.3, 24.0.3, 25.0.3, 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```base
import { WebView } from 'react-native-webview';

<View style={{ flex: 1, width: '100%', height: '100%' }}>
        <WebView source={{ html: '<h1>Hello world</h1>' }} style={{ width: 300, height: 300, marginTop: 20 }} />
</View>

//or

<View style={{ flex: 1, width: '100%', height: '100%' }}>
        <WebView source={{ uri: 'https://www.google.com' }} style={{ width: 300, height: 300, marginTop: 20 }} />
</View>

```

**Comment by brentvatne** [comment]
notice it's not indicated as supported in the docs:

<img width="1171" alt="Screen Shot 2021-04-19 at 8 47 24 PM" src="https://user-images.githubusercontent.com/90494/115334560-7bb75480-a150-11eb-8027-edd516a0206b.png">

you should open a pr against react-native-webview to add support for this, or open an issue there.

**Comment by fungmo** [comment]
@brentvatne 
Oh yes. But are there any alternatives? Can't seem to find a better way.

**Comment by brentvatne** [comment]
you could use an iframe on the web
