### ISSUE TITLE
androidNavigationBar visible property affects androidStatusBar backgroundColor

### ISSUE THREAD

**Issue by allandiego** [expo/expo#12619]
### Summary

setting androidNavigationBar visible to any of acceptable values like 'sticky-immersive' makes androidStatusBar backgroundColor not work

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.2 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 2.4.1 - C:\Users\Diego\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 28.0.3, 29.0.2
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

create base project 
```
expo init my-app
```

in app.json
```json
"androidStatusBar": {
      "hidden": false,
      "translucent": false,
      "barStyle": "light-content",
      "backgroundColor": "#ff0000"
    },
    "androidNavigationBar": {
      "visible": "sticky-immersive",
      "barStyle": "light-content",
      "backgroundColor": "#ff0000"
    },
```

status bar gets black with white text, removing "visible": "sticky-immersive", statusbar color back to red

**Comment by jhcpeixoto** [comment]
The same is happening to me

**Comment by allandiego** [comment]
@jhcpeixoto whats your android version? and device? I was using xiaomi with this bug

**Comment by jhcpeixoto** [comment]
> @jhcpeixoto whats your android version? and device? I was using xiaomi with this bug

Android: 11
Phone: Samsung Galaxy A71
