### ISSUE TITLE
can't use react-native run-android

### ISSUE THREAD

**Issue by kakahero** [expo/expo#1263]
Hi, I use exp init test to create example app, and use exp detach to generate android native code. I can't use react-native run-android to run android app.  

The error message is 

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in root project 'android'. Some candidates are: 'installDevDebug'.

**Comment by ide** [comment]
You'll need to use the `installDevDebug` Gradle target right now. From https://docs.expo.io/versions/latest/guides/expokit.html, the way to run detached apps with ExpoKit is:

> Open the android directory in Android Studio, then build and run the project on an Android device or a Genymotion emulator.
>
> Once the Android project is running, it should automatically request your development url from XDE or exp. You can develop your project normally from here.
