### ISSUE TITLE
An error occurred while executing doInBackground() - Expo Barcode Scanner

### ISSUE THREAD

**Issue by Sheharyar566** [expo/expo#12635]
I am working on an ejected flow and am trying to use expo barcode scanner. However, every once in a while I get this error https://sentry.io/share/issue/f61de236a0cd49e0bf8f49cfc0c1fd6a/ There error didn't occur even once before I added this library. Oh and the error also occurs even when the BarCodeScanner isn't even on the active screen (or the user still hasn't even yet navigated to the screen that embeds the BarCodeScanner.

(The logs from sentry link above)
`
android.os.AsyncTask$4 in done at line 399
java.util.concurrent.FutureTask in finishCompletion at line 383
java.util.concurrent.FutureTask in setException at line 252
java.util.concurrent.FutureTask in run at line 271
android.os.AsyncTask$SerialExecutor$1 in run at line 289
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1167
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 641
java.lang.Thread in run at line 919

RuntimeException
getParameters failed (empty parameters)

android.hardware.Camera in native_getParameters
android.hardware.Camera in getParameters at line 2268
expo.modules.barcodescanner.BarCodeScannerViewFinder$BarCodeScannerAsyncTask in doInBackground at line 198
expo.modules.barcodescanner.BarCodeScannerViewFinder$BarCodeScannerAsyncTask in doInBackground at line 179
android.os.AsyncTask$3 in call at line 378
java.util.concurrent.FutureTask in run at line 266
android.os.AsyncTask$SerialExecutor$1 in run at line 289
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1167
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 641
java.lang.Thread in run at line 919
`

### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by Joshandrews43** [comment]
Same issue, just made a ticket

**Comment by cruzach** [comment]
closing in favor of https://github.com/expo/expo/issues/13049
