### ISSUE TITLE
LocalAuthentication.authenticateAsync() keep returning `app_cancel` error after tapping CANCEL in face confirmation screen

### ISSUE THREAD

**Issue by gnzhen** [expo/expo#12634]
### Steps to reproduce:
Use face recognition, after face is verified, in "Tap confirm to continue" screen, tap the **CANCEL** button.

![image](https://user-images.githubusercontent.com/20655313/115516619-e388af00-a2b8-11eb-9b52-05e03c50718e.png)

The screen will dismiss but `LocalAuthentication.authenticateAsync()` does not return. If I try to call `LocalAuthentication.authenticateAsync()` again, it will always return `{error: app_cancel}` no matter how many times I try to call again.

It only happen for the CANCEL button in the particular screen

### Expected:
Should return `{error: user_cancel}` (like what the function return for other CANCEL button)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Test device: Samsung S10
Android version: 10

expo-local-authentication: "11.0.2"
react-native-unimodules: "0.13.3"
react-native: "0.62.2"

### Reproducible demo or steps to reproduce from a blank project

```javascript
try {
  const result = await LocalAuthentication.authenticateAsync();
  Alert.alert("Result", JSON.stringify(result))
} catch (err) {
  Alert.alert("ERROR!", JSON.stringify(err))
}
```

**Comment by yim-jj** [comment]
same problem

**Comment by Seibold** [comment]
same problem

**Comment by BartDeKrab** [comment]
Also running into the same problem :(

**Comment by aerielcruz** [comment]
This stop gap fix worked for me! Adding `disableDeviceFallback` and `cancelLabel` will result to `user_cancel` instead of `app_cancel`
```
LocalAuthentication.authenticateAsync({
	promptMessage: 'Authenticate',
	disableDeviceFallback: true,
	cancelLabel: 'Cancel',
})
```

**Comment by tmKnight01** [comment]
> 这个权宜之计对我有用！添加`disableDeviceFallback`和`cancelLabel`将导致`user_cancel`而不是`app_cancel`
> 
> ```
> LocalAuthentication.authenticateAsync({
> 	promptMessage: 'Authenticate',
> 	disableDeviceFallback: true,
> 	cancelLabel: 'Cancel',
> })
> ```
> 
> 然后有一个自定义的非生物识别身份验证后备方案

awesome bro,    i fixed  this isssue  by   your way
