### ISSUE TITLE
FileSystem.uploadAsync body is empty iOS

### ISSUE THREAD

**Issue by tomasswood** [expo/expo#12636]
### Summary

Putting an image to a signed AWS URL with `FileSystem.uploadAsync` is resulting in a 0 byte upload. Works fine on Android.

`"expo-file-system": "~11.0.2"`

I have also tried:

`"react-native": "~0.63.4",`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

```  Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/tomasswood/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Uploading to the following signed URL returns `response: 200` but an empty body. When I look in S3, the image is there but it is 0 bytes. Only happens on iOS. Android is working fine.

```
const res = await FileSystem.uploadAsync(signedUrl, imageUrl, {
      httpMethod: 'PUT',
      headers: {
        'Content-Type': 'image/jpeg',
      },
      sessionType: FileSystemSessionType.BACKGROUND,
    });

    console.table(res);
```

**Comment by AchrafBn** [comment]
i have the same issue , did you solve it ?
