### ISSUE TITLE
expo-yarn-monorepo server AppEntry path resolution error (__generated__/AppEntry.bundle)

### ISSUE THREAD

**Issue by MaxEvan** [expo/expo#12642]
### Summary

I am trying to setup a next-js + react native monorepo to be able to share the components  between my mobile app and web using expo. I followed all the procedure for expo-yarn-workspaces etc... I keep getting that error when I try to run my app on my android device:

```
Finished building JavaScript bundle in 19261ms.
Running application on Pixel 4a.
Error: ENOENT: no such file or directory, open '/Users/max/dev/next-js-rn/packages/mobile/http:/192.168.0.146:19000/__generated__/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at getCodeFrame (/Users/max/dev/next-js-rn/packages/mobile/node_modules/metro/src/Server.js:918:18)
    at Server._symbolicate (/Users/max/dev/next-js-rn/packages/mobile/node_modules/metro/src/Server.js:990:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Server._processRequest (/Users/max/dev/next-js-rn/packages/mobile/node_modules/metro/src/Server.js:403:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/max/dev/next-js-rn/packages/mobile/http:/192.168.0.146:19000/__generated__/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false'
}
```

The path resolution in the expo server seems to be flawed and I don't have the time to investigate it now... 

I tried using different versions of expo and react-native, in vain.

I pushed the exact setup I am getting the error with [here](https://github.com/MaxEvan/next-js-react-native-monorepo).

Hopefully someone can help me, thanks!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.0

### Environment

Macbook pro 2020 M1
Big Sur 11.2.3

### Reproducible demo or steps to reproduce from a blank project

https://github.com/MaxEvan/next-js-react-native-monorepo

**Comment by Slapbox** [comment]
@MaxEvan a new version of the package just came out. Did you maybe get upgraded to it? I'm not sure if it's breaking - 1.4.1 vs 1.5.1.

**Comment by MaximeEvangeliste** [comment]
Yup tried 3 versions. Same thing 😑

**Comment by Slapbox** [comment]
Ah that's unfortunate. Have you tried clearing all your `node_modules` folders (at every level of the monorepo) and reinstalling it all?

Also, have you tried clearing your yarn cache? That's the nuclear option and usually makes no difference, but if you want to be certain you can try that.

**Comment by MaximeEvangeliste** [comment]
Yeah tried all of that. Still doesn't change anything. If you want to, I'd invite you to clone the repo I put in the issue and try it to see if the same thing happens on your side 🙂

**Comment by ajsmth** [comment]
hi there - I submitted a PR to your repo there with some fixes - I think the configuration can get a little confusing at times but let me know if that works for you now! Cheers!

**Comment by MaxEvan** [comment]
@ajsmth Hi! Thanks for trying to fix it, but the web one runs perfectly fine as it is. The problem is when I try to run the mobile app with expo on my pixel 4a, I get the error mentioned in my issue. If you check the mobile folder, I configured the app how the expo-yarn-workspace tells me to and it still doesn't work 😑

**Comment by MaxEvan** [comment]
@ajsmth Sorry, just checked and web doesn't seems to not work in this one but I know how to make it work, my main problem is really with the mobile one. Can't get it to run...
