### ISSUE TITLE
[iOS] Video Component doesn't works when published to expo projects

### ISSUE THREAD

**Issue by themakerman** [expo/expo#1264]
Hi guys,

The background video component is working for both android/iOS when i am building locally. However, video doesnt loads when published to expo for iOS. Android is working great.
Can someone please help me out?

P.S : I am loading custom fonts but i don't think thats the problem as locally both iOS and android are working. I have handled custom fonts loading as per docs using setState. Everything works ok but when i scan published qr code the video doesnt loads on iOS.

```
import colorCompareLoginFootage from '../res/colorCompareLoginFootage.mp4';
.
.
.
.
inside render --->
<Video
          source={colorCompareLoginFootage}
          rate={1.0}                              // 0 is paused, 1 is normal.
          volume={1.0}                            // 0 is muted, 1 is normal.
          isMuted={true}                           // Mutes the audio entirely
          resizeMode='cover'                      // Fill the whole screen at aspect ratio.*
          shouldPlay
          isLooping                                  // Continously repeat the video
          style={{ width: Dimensions.get('window').width * 1.5, height: Dimensions.get('window').height }}
/>
```
Package.json file
```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^24.0.0",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
    "react-native-router-flux": "^4.0.0-beta.17",
    "react-native-video": "^2.0.0"
  }
}
```

https://expo.io/@scoreboardtech/screencompare

**Comment by bighoho123** [comment]
I am having the same issue. Working perfectly locally both on ios simulator & LAN.

Based on the publish log, the asset video has been uploaded.

**Comment by bighoho123** [comment]
@themakerman As a workaround, I uploaded the video asset to a public accessible url (amazon s3) and refrerence via {uri:'https://xxxx'} and it works

**Comment by themakerman** [comment]
@bighoho123 i wish i could do that but i don't want any network dependencies to load video. If the asset video is getting uploaded i wonder whats going wrong. Can you share your project?

**Comment by bighoho123** [comment]
I've seen someone posted their [repo](https://snack.expo.io/@sjchmiela/android-native-controls-and-replay-showcase) in #958 . And I compared with mine code the only difference was the way how the asset was referenced. 

I updated mine and it's working.

I haven't tried but I doubt whether this is still an issue when publishing as a standalone app since it's working locally.

**Comment by themakerman** [comment]
@sjchmiela Did you tried loading my project?
https://expo.io/@scoreboardtech/screencompare

it works on Android but iOS doesn't renders video. However both are working locally just fine.

**Comment by sjchmiela** [comment]
Yes @themakerman, I can confirm the problem exists in your app, but unfortunately I don't have a solution off the top of my head. I'll update this thread should I find solutions.

**Comment by sjchmiela** [comment]
Hm… what about this app: https://expo.io/@sjchmiela/atlas? Is the video playing?

**Comment by themakerman** [comment]
@sjchmiela Ok i tried few scenarios:
1) I uploaded my video footage to your atlas snack. It works perfect over snack for both iOS and Android.
2) I changed the code from import video ---> require (old school way). (failed result)
3) I changed the size of the video ---> (failed result) ---> after changing the size even the android one is not working anymore. However over LAN things are still great.
4) I removed the custom fonts and tried all above steps. Didn't helped either.
5) I also made sure assets where uploaded every time using console logs of expo.

![screen shot 2018-01-16 at 11 30 16 pm](https://user-images.githubusercontent.com/14818804/35005653-2457dece-fb1a-11e7-9955-9d64354902e7.png)


After changing the footage size now both of them are not working.
Can there be a problem with Amazon Cloudfront? i think so.....

**Comment by sjchmiela** [comment]
Ok, so just to recap, have you tried republishing a version in which you `require` the video?

**Comment by themakerman** [comment]
yup. The current version should ideally show the video but its not showing. I republished the project for every scenario listed above.

**Comment by themakerman** [comment]
@sjchmiela so i hosted my file on my private amazon s3 server and now both versions are working fine after publishing. I think the amazon asset system used by expo is broken somehow. Right now till it gets fixed i would advice everyone to use amazon s3 to host their file and use uri: as source.

Though when i uploaded asset over snack it was working.

@bighoho123 thanks for the tip.

**Comment by sjchmiela** [comment]
One other thing you could try would be to do what `Video` does internally — load the `Asset` from the module and use it's URI.

```js
import { Asset } from 'expo';
const videoModule = require('./assets/video.mp4');
const videoAsset = Asset.fromModule(videoModule);
const videoSource = { uri: videoAsset.uri };
```

You could also try to grab the URI somehow when the bug occurs and see for yourself if the returned URI looks valid and if it the video downloads properly, etc.

**Comment by themakerman** [comment]
@sjchmiela ok gonna try. Will update you.

**Comment by themakerman** [comment]
@sjchmiela i am out for few days. Give me some time. Will update ASAP

**Comment by lichin-lin** [comment]
I got the same loading failure on ios issue when publish the expo project.
this is my link of the expo project: https://expo.io/@lichin-lin/nextclinicapp

I use the way @sjchmiela provide to load the source (1 image, 1 video)
```javascript
import { Asset } from 'expo';
const videoModule = require('./assets/video.mp4');
const videoAsset = Asset.fromModule(videoModule);
const videoSource = { uri: videoAsset.uri };

const catModule = require('./assets/cat.jpg');
const catAsset = Asset.fromModule(catModule);
const catSource = { uri: catAsset.uri };

...
<Text>{videoSource}</Text>
<Text>{catSource}</Text>
<Image source={catSource} />
<Video source={videoSource} />
```

which give the result:
![expo-video-error](https://user-images.githubusercontent.com/10290616/35479939-5deffd4c-043e-11e8-9ede-d2afdbee2e9c.png)
---
I've try to change the source link directly into the really link where the server hold those file (and I check those file, I can successfully download those image and video).
```javascript
...
<Text>{videoSource}</Text>
<Text>{catSource}</Text>
<Image source={{ uri:  'https://d1wp6m56sqw74a.cloudfront.net/~assets/ae413f45c86be30855810be0409042de'}} />
<Video source={{ uri:  'https://d1wp6m56sqw74a.cloudfront.net/~assets/39dcba8c1b5dc1746861295f159f221b' }} />
```
but end up with the same result, the video still don't show up.

**Comment by nebmesemaou** [comment]
same problem on ios 
Expo Video component not working on ios

**Comment by themakerman** [comment]
@lichin-lin can you check if its same for android? in my case android was working. To solve the problem i used my amazon s3 server to fetch the file and both iOS and android worked.

**Comment by lichin-lin** [comment]
I just change the mp4 link to: https://drive.google.com/uc?export=download&id=1euIebV25Mgrxi67A64vCEDVVqrV1OnLJ
and the problem was solved, iOS and android worked~

**Comment by sjchmiela** [comment]
@lichin-lin, thanks, I downloaded both files and the `diff` showed no difference, so I checked the HTTP communication details — the only difference I noticed were `Content-Type` headers: cloudfront showed `octet-stream` while Google returned `video/mp4`. It seems in the history of AVPlayer we are [not the only one](https://forums.developer.apple.com/thread/52964) who try to play `application/octet-stream` in AVPlayer and fail to do so.

I confirmed this behavior with a local file server. And two identical copies of the files served with different content-types.

@nikki93, do you think it would be possible for AWS to respond with a more precise `Content-Type`?

**Comment by sjchmiela** [comment]
Hi there, I'll close this issue due to inactivity, but feel free to reopen it if you encounter this bug anytime!

**Comment by themakerman** [comment]
@sjchmiela amazon s3 links are not working again. Working on ios simulator. Doesnt works on actual android and ios device. This is now happening over lan before even publishing. Most of my app UI's rely too much on video backgrounds. One thing i have noticed is that after publishing video works on my iphone 7, 6 but doesn't works on my iphone 5 and all android devices.

I never wrote back into the issue cause i felt no one is looking into it seriously from expo team. Please let me know how i can help you to solve this problem. I have to solve this else gonna be in trouble during production. Thanks

**Comment by sjchmiela** [comment]
How many videos are you trying to play at the same time? iOS has an upper limit of a number of videos that can be played simultaneously (which is higher on the simulator and lower on the device).

**Comment by themakerman** [comment]
only 1 @sjchmiela. It works on simulator. On real device it doesn't works for iOS. On android, it doesn't works on sim as well as the real device and also when published.
https://expo.io/@scoreboardtech/mycondominium
https://expo.io/@scoreboardtech/mySaloon

Please check these projects on android (mine version 7.0) also on ios it doesnt works on ios 10.x.x (my device iphone 5). Works on iOS 11 though

**Comment by themakerman** [comment]
@sjchmiela its mp4. What codec is atlas app using. Do you think mp4 has also subcodecs?

**Comment by sjchmiela** [comment]
Yes, but it's rather unlikely for you to have something other than H.264 (I'll check atlas in a couple of minutes). https://en.wikipedia.org/wiki/MPEG-4_Part_14#Data_streams

**Comment by sjchmiela** [comment]
For Atlas (it looks like H.264 and AAC):

`ffmpeg -i video.mp4`:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'ca435649eebfa341eebb69cd1c0ed222.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2017-11-16T21:58:31.000000Z
  Duration: 00:00:54.66, start: 0.000000, bitrate: 661 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 563 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2017-11-16T21:58:31.000000Z
      handler_name    : IsoMedia File Produced by Google, 5-11-2011
```

`AtomicParsley video.mp4 -Tt`:
```
Atom ftyp @ 0 of size: 24, ends @ 24
Atom moov @ 24 of size: 18522, ends @ 18546
     Atom mvhd @ 32 of size: 108, ends @ 140
     Atom iods @ 140 of size: 21, ends @ 161
     Atom trak @ 161 of size: 7740, ends @ 7901
         Atom tkhd @ 169 of size: 92, ends @ 261
         Atom edts @ 261 of size: 36, ends @ 297
             Atom elst @ 269 of size: 28, ends @ 297
         Atom mdia @ 297 of size: 7604, ends @ 7901
             Atom mdhd @ 305 of size: 32, ends @ 337
             Atom hdlr @ 337 of size: 45, ends @ 382
             Atom minf @ 382 of size: 7519, ends @ 7901
                 Atom vmhd @ 390 of size: 20, ends @ 410
                 Atom dinf @ 410 of size: 36, ends @ 446
                     Atom dref @ 418 of size: 28, ends @ 446
                         Atom url  @ 434 of size: 12, ends @ 446
                 Atom stbl @ 446 of size: 7455, ends @ 7901
                     Atom stsd @ 454 of size: 171, ends @ 625
                         Atom avc1 @ 470 of size: 155, ends @ 625
                             Atom avcC @ 556 of size: 49, ends @ 605
                             Atom btrt @ 605 of size: 20, ends @ 625
                     Atom stts @ 625 of size: 40, ends @ 665
                     Atom stss @ 665 of size: 132, ends @ 797
                     Atom stsc @ 797 of size: 52, ends @ 849
                     Atom stsz @ 849 of size: 6568, ends @ 7417
                     Atom stco @ 7417 of size: 484, ends @ 7901
     Atom trak @ 7901 of size: 10645, ends @ 18546
         Atom tkhd @ 7909 of size: 92, ends @ 8001
         Atom mdia @ 8001 of size: 10545, ends @ 18546
             Atom mdhd @ 8009 of size: 32, ends @ 8041
             Atom hdlr @ 8041 of size: 76, ends @ 8117
             Atom minf @ 8117 of size: 10429, ends @ 18546
                 Atom smhd @ 8125 of size: 16, ends @ 8141
                 Atom dinf @ 8141 of size: 36, ends @ 8177
                     Atom dref @ 8149 of size: 28, ends @ 8177
                         Atom url  @ 8165 of size: 12, ends @ 8177
                 Atom stbl @ 8177 of size: 10369, ends @ 18546
                     Atom stsd @ 8185 of size: 105, ends @ 8290
                         Atom mp4a @ 8201 of size: 89, ends @ 8290
                             Atom esds @ 8237 of size: 53, ends @ 8290
                     Atom stts @ 8290 of size: 24, ends @ 8314
                     Atom stsc @ 8314 of size: 316, ends @ 8630
                     Atom stsz @ 8630 of size: 9436, ends @ 18066
                     Atom stco @ 18066 of size: 480, ends @ 18546
Atom mdat @ 18546 of size: 4500954, ends @ 4519500
------------------------------------------------------
Total size: 4519500 bytes; 44 atoms total.
Media data: 4500954 bytes; 18546 bytes all other atoms (0.410% atom overhead).
Total free atom space: 0 bytes; 0.000% waste.
------------------------------------------------------
AtomicParsley version: 0.9.6 (utf8)
------------------------------------------------------
Movie duration: 54.658 seconds (0:54.66) - 658.78* kbp/sec bitrate (*=approximate)
Low-level details. Total tracks: 2
Trk  Type  Handler                    Kind  Lang  Bytes
1    vide  VideoHandler               avc1  und   3845029
     563.17* kbp/s  54.620 sec  AVC Baseline Profile,  Level 3  640x360  (880 macroblocks)
2    soun  IsoMedia File Produced by Google, 5-11-2011  mp4a  eng   655917
     95.99 kbp/s  MPEG-4 AAC Low Complexity/LC Profile    channels: [2]
```

**Comment by themakerman** [comment]
https://s3-ap-southeast-1.amazonaws.com/scoreboardtech/hotelPortrait.mp4

https://s3-ap-southeast-1.amazonaws.com/scoreboardtech/hairSaloon.mp4

Can you please check these two videos with the tool you are using?

**Comment by sjchmiela** [comment]
Results for `hotelPortrait` below. 🙂 

It looks like both your and my videos are valid MP4 files, the only reason that I can think of why the video would not play is higher bitrate of your file; maybe native player waits for the video to buffer too long? I'll investigate it further! 🕵️ 

`ffmpeg -i hotelPortrait.mp4`:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'hotelPortrait.mp4':
  Metadata:
    major_brand     : M4V 
    minor_version   : 1
    compatible_brands: M4V mp42isom
    creation_time   : 2018-04-01T10:17:54.000000Z
  Duration: 00:00:51.86, start: 0.000000, bitrate: 3521 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1064x2304, 3331 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2018-04-01T10:17:54.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2018-04-01T10:17:54.000000Z
      handler_name    : Mainconcept MP4 Sound Media Handler
```

`AtomicParsley hotelPortrait.mp4 -Tt`:
```
Atom ftyp @ 0 of size: 28, ends @ 28
Atom moov @ 28 of size: 10476, ends @ 10504
     Atom mvhd @ 36 of size: 108, ends @ 144
     Atom trak @ 144 of size: 7813, ends @ 7957
         Atom tkhd @ 152 of size: 92, ends @ 244
         Atom mdia @ 244 of size: 7677, ends @ 7921
             Atom mdhd @ 252 of size: 32, ends @ 284
             Atom hdlr @ 284 of size: 68, ends @ 352
             Atom minf @ 352 of size: 7569, ends @ 7921
                 Atom vmhd @ 360 of size: 20, ends @ 380
                 Atom dinf @ 380 of size: 36, ends @ 416
                     Atom dref @ 388 of size: 28, ends @ 416
                         Atom url  @ 404 of size: 12, ends @ 416
                 Atom stbl @ 416 of size: 7505, ends @ 7921
                     Atom stsd @ 424 of size: 177, ends @ 601
                         Atom avc1 @ 440 of size: 161, ends @ 601
                             Atom avcC @ 526 of size: 47, ends @ 573
                             Atom uuid=6b6840f2-5f24-4fc5-ba39-a51bcf0323f3 @ 573 of size: 28, ends @ 601
                     Atom stts @ 601 of size: 136, ends @ 737
                     Atom stsc @ 737 of size: 40, ends @ 777
                     Atom stsz @ 777 of size: 6232, ends @ 7009
                     Atom stco @ 7009 of size: 640, ends @ 7649
                     Atom stss @ 7649 of size: 272, ends @ 7921
         Atom edts @ 7921 of size: 36, ends @ 7957
             Atom elst @ 7929 of size: 28, ends @ 7957
     Atom iods @ 7957 of size: 27, ends @ 7984
     Atom trak @ 7984 of size: 2456, ends @ 10440
         Atom tkhd @ 7992 of size: 92, ends @ 8084
         Atom mdia @ 8084 of size: 2320, ends @ 10404
             Atom mdhd @ 8092 of size: 32, ends @ 8124
             Atom hdlr @ 8124 of size: 68, ends @ 8192
             Atom minf @ 8192 of size: 2212, ends @ 10404
                 Atom smhd @ 8200 of size: 16, ends @ 8216
                 Atom dinf @ 8216 of size: 36, ends @ 8252
                     Atom dref @ 8224 of size: 28, ends @ 8252
                         Atom url  @ 8240 of size: 12, ends @ 8252
                 Atom stbl @ 8252 of size: 2152, ends @ 10404
                     Atom stsd @ 8260 of size: 100, ends @ 8360
                         Atom mp4a @ 8276 of size: 84, ends @ 8360
                             Atom esds @ 8312 of size: 48, ends @ 8360
                     Atom stts @ 8360 of size: 24, ends @ 8384
                     Atom stsc @ 8384 of size: 1360, ends @ 9744
                     Atom stsz @ 9744 of size: 20, ends @ 9764
                     Atom stco @ 9764 of size: 640, ends @ 10404
         Atom edts @ 10404 of size: 36, ends @ 10440
             Atom elst @ 10412 of size: 28, ends @ 10440
     Atom udta @ 10440 of size: 64, ends @ 10504
         Atom ©TIM @ 10448 of size: 23, ends @ 10471					 ~
         Atom ©TSC @ 10471 of size: 17, ends @ 10488					 ~
         Atom ©TSZ @ 10488 of size: 16, ends @ 10504					 ~
Atom uuid=be7acfcb-97a9-42e8-9c71-999491e3afac @ 10504 of size: 6886, ends @ 17390
Atom mdat @ 17390 of size: 22809815 (^), ends @ 22827205
			 (^)denotes a 64-bit atom length

 ~ denotes an unknown atom
------------------------------------------------------
Total size: 22827205 bytes; 51 atoms total.
Media data: 22809815 bytes; 17390 bytes all other atoms (0.076% atom overhead).
Total free atom space: 0 bytes; 0.000% waste.
------------------------------------------------------
AtomicParsley version: 0.9.6 (utf8)
------------------------------------------------------
Movie duration: 51.861 seconds (0:51.86) - 3518.59* kbp/sec bitrate (*=approximate)
Low-level details. Total tracks: 2
Trk  Type  Handler                    Kind  Lang  Bytes
1    vide  Mainconcept MP4 Video Media Handler  avc1  eng   21582144
     3331.98* kbp/s  51.818 sec  AVC Main Profile,  Level 5  1064x2304  (9504 macroblocks)
2    soun  Mainconcept MP4 Sound Media Handler  mp4a  eng   1227655
     189.37 kbp/s  MPEG-4 AAC Low Complexity/LC Profile    channels: [2]
```

**Comment by themakerman** [comment]
@sjchmiela i'll check it out too with lower bit rates. Let me know if you find something as well. will keep you updated on my findings.

**Comment by themakerman** [comment]
@sjchmiela did you found the issue? After updating to new expo client suddenly the videos are working on my android device and sadly the newer apps i am making with videos iOS version is not showing the video -_-. The same video on iOS published with earlier version of sdk is working but with newly published sdk its not. I dont understand if this is client problem or the expo sdk asset problem.

**Comment by sjchmiela** [comment]
I didn't find anything, I'll ping you on https://expo-developers.slack.com for the link. 🙂

**Comment by themakerman** [comment]
:) okies

**Comment by themakerman** [comment]
@sjchmiela should the issue still stay open? or should we document our findings like no .mp4 extension, wrong headers, etc...I think its not completely expo issue and even apple's avplayer shares some problems

**Comment by sjchmiela** [comment]
This issue is still present due to wrong content type header sent by S3. (See explanation at https://github.com/expo/expo/issues/1264#issuecomment-361563781)

If you ever encounter this issue again, try to reencode the file (so its checksum changes) and reupload to S3 again, it should pick up proper file type.

**Comment by simsketch** [comment]
None of the solutions here worked for me so I fired up Premiere and converted to .gif...not ideal, but good enough for my deadline! :^D

**Comment by themakerman** [comment]
@sjchmiela Issue still present. The video working with sdk 24 on iOS but not working with sdk 28. Hmmmm its really getting all the user experience away in production. I dnt want to host on my s3 anymore due to billing....can we have conversation over slack? or can connect me to someone who can help me?

**Comment by themakerman** [comment]
@simsketch Did you figured out the problem?

**Comment by simsketch** [comment]
The .gif ended up being a terrible solution. I went back to serving the file remotely, and it's been working for me in production. if s3 is too expensive for you, try grabbing a box from OVH for about $35/year, that's what i use.
