### ISSUE TITLE
[exp] connect ETIMEDOUT 35.184.55.1:443

### ISSUE THREAD

**Issue by ArsenyYankovsky** [expo/expo#1265]
I get following while trying to run `exp build:android`

```
$ exp build:android
[exp] Checking if current build exists...

[exp] connect ETIMEDOUT 35.184.55.1:443
```

**Comment by ArsenyYankovsky** [comment]
@l0ger This generally means that something is wrong with Expo servers.

**Comment by brentvatne** [comment]
not necessarily - it could be a dns issue. android builds are working as expected at the moment

**Comment by l0ger** [comment]
I build project with out expo and with react-native tool. all things is great.
