### ISSUE TITLE
Where to request or submit updates for Expo dependencies (node_modules)?

### ISSUE THREAD

**Issue by k-ibr** [expo/expo#12656]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by k-ibr** [comment]
Hey everyone,

Since I am fairly new to this all I was wondering where I can submit requests to update node_modules for Expo. In this case its about masked_view, it's having a lot of performance issues and even though I know what needs to be fixed (it has to do with the android Java code), I am wondering where I can submit my fix to and how this can be updated for the expo app itself?

I have done the tests in bare-workflow and the problem is that the masked-view itself is badly maintained. Basically what needs to be done is we need to change `setLayerType(LAYER_TYPE_SOFTWARE, null);` into `setLayerType(LAYER_TYPE_HARDWARE, null);` to enable the hardware enable performance for the views. 

How and where are such requests placed and how does that find its way back into expo. Last update to the expo masked-view is almost a year old.

**Comment by brentvatne** [comment]
hi there! the masked view library lives here: https://github.com/react-native-masked-view/masked-view - you can open a pr there.

the last time we updated masked-view was for 0.1.10, which was the latest version when we were preparing to release sdk 40 5 months ago. we did not update it in sdk 41 for a few reasons, but we will likely proceed with updating it in sdk 42.

thanks for investigating this, i'm sure the react-native-masked-view maintainers will appreciate the help :)

**Comment by k-ibr** [comment]
Thank you so much @brentvatne for the info. Since the SDK updates take quite a while to get and this issue is quite severe I am wondering if there is somehow another way to get this usable? We are using masked view in our production app and this particular bug is causing 12 to 15 fps on Android whereas its 60fps on IOS. So now we have a dilemma:

1. masked view maintainers seem to be somewhat inactive, we brought this to their attention over a month ago and it doesn’t seem to get picked up.
2. even if the PR is to be accepted by them, a potential update to Expo could take months while this bug is causing severe issues to our production app, causing us to not use an important library on Android.

Is there a way for us to manually get this working for our Expo app until its eventually updated, or is there a procedure to fast track these type of severe issues to be patched in faster?

**Comment by k-ibr** [comment]
p.s. here is a video of the issue and the fixed, I already submitted a PR to the MaskedView repo

[Hardware Acceleration OFF](https://www.dropbox.com/s/tp92z4mhwgje2t6/software.webm?dl=0) - performance is so bad it's impacting the recording, sorry.
[Hardware Acceleration ON](https://www.dropbox.com/s/7hc0enqmitf0ijh/hardware.webm?dl=0)
