### ISSUE TITLE
[iOS] One of the `NSLocation*UsageDescription` keys must be present

### ISSUE THREAD

**Issue by DCKT** [expo/expo#12662]
### Summary

Hi !

When I want to request background permission on iOS through **Expo Go with a real device**. 
I receive this error : 
```
[Unhandled promise rejection: Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.]
```

My app.json looks like good to me : 
```
"ios": {
      "supportsTablet": true,
      "infoPlist": {
        "ITSAppUsesNonExemptEncryption": false,
        "UIBackgroundModes": ["location", "fetch"],
        "CFBundleAllowMixedLocalizations": true,
        "NSLocationAlwaysAndWhenInUseUsageDescription": "App requires geolocation to improve the quality of the service",
        "NSLocationAlwaysUsageDescription": "App requires geolocation to improve the quality of the service",
        "NSLocationWhenInUseUsageDescription": "App requires geolocation to improve the quality of the service",
        "NSCameraUsageDescription": "The picture will be used to inform the state of the packages during delivery"
      }
    },
```

Also, when I try in the simulator, the error is `undefined`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-4295205/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-4295205/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Here is a snack implementation, https://snack.expo.io/@dckthomas/frisky-ramen
In the snack, there is a dialog asking for permission but not when it's run from a fresh project like this : https://github.com/DCKT/geofence-expo

**Comment by EvanBacon** [comment]
The infoPlist cannot be updated without a native rebuild, we're currently [refining this workflow](https://blog.expo.io/eas-build-april-preview-update-ebd7dff9dd25) and will have better support for this soon. For now, you can either build in the cloud with `eas build`, the legacy `expo build:ios`, or locally by running `expo eject` and `yarn ios`.

You can continue to test this app in the Expo Go project, but to access the new Info plist, you'll need to use the locally built app.

**Comment by DCKT** [comment]
@EvanBacon Thanks for your response, I did it through `eas` as mentioned and still got rejected with `undefined` error 🤔

**Comment by EvanBacon** [comment]
I don't think I understand, does your `Info.plist` contain the expected keys (NSLocationAlwaysAndWhenInUseUsageDescription, etc.) when you run `expo prebuild` locally?

**Comment by DCKT** [comment]
Yes it does (also in the repro repo)

Le mer. 28 avr. 2021 à 23:25, Evan Bacon ***@***.***> a
écrit :

**Comment by DCKT** [comment]
I mean, in my app.json,not the plist file (I'm using the manage workfkow)

Le mer. 28 avr. 2021 à 23:25, Evan Bacon ***@***.***> a
écrit :

**Comment by bnussman** [comment]
I am getting this same issue after upgrading to Expo SDK 41 and refactoring to use Location.requestBackgroundPermissionsAsync(). 

My app.json has
```json
"ios": {
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "The Beep App uses your location to pick origins, destinations, and predict ride times",
        "NSLocationAlwaysUsageDescription": "The Beep App will use your location to provide ETA's to yourself and others",
        "UIBackgroundModes": [
          "location",
          "fetch"
        ]
      }
    },

```

**Comment by bailakahn** [comment]
Hi i am getting he same issue. I was using expo SDK 40 with `requestPermissionsAsync()`. I upgraded to SDK 41 and now using **requestForegroundPermissionsAsync()** and **requestBackgroundPermissionsAsync().** For the later i get error [Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.].


All the answers i am seing here are for people who are building their app.

Is there a way to get this working on local with expo Go ?

Thank you.

**Comment by bnussman** [comment]
@bailakahn From my experience, Expo Go does not (and never has) the ability to let you use background location. You can only test background location if you have your app built. I could be wrong about that... 

Regardless, I can't get background location working in my app since refactoring to SDK 41. I tried **requestForegroundPermissionsAsync()** and **requestBackgroundPermissionsAsync()**  like you said but got the same error you got. 

I proceeded to reinstall expo-permissions and see if I could get background location working but then got `LOCATION_BACKGROUND permission is required to do this operation.` on a built iOS app. 

If anyone has working background location on SDK 41 I would love to see some example code or receive some clarity unless something is actually broken within Expo

**Comment by DCKT** [comment]
Sorry to push this issue forward, any clue on this case ?

**Comment by Petercopter** [comment]
@bnussman I recently finished adding background location to a managed workflow Expo app, and background location was working in the Expo Go app with 40. It has obviously changed in 41, due to a major overhaul.

You want to start using `Location.getBackgroundPermissionsAsync` instead of `Permissions`, instead of managing permissions in one constant, each function will handle their own permissions (notifications, camera, location, etc).

https://blog.expo.io/expo-sdk-41-12cc5232f2ef

**Comment by bnussman** [comment]
@Petercopter I'm shocked you got background location in Expo Go. Maybe I'm missing something there. 

I am fully aware and acknowledged that I _should_  be using the functions part of expo-location, but they are not working for me. I tired to revert to expo-permissions because I know it worked and thought it still may work because it is just now deprecated. 

I'm still getting 

```
[Unhandled promise rejection: Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.]
```

**Comment by Petercopter** [comment]
@bnussman I think I just realized where the confusion lies. I was doing background location with Expo 40, on the Expo Go 40 app.

With the update to Expo 41, there was also changes made to the Expo Go app that affect how all apps behave. Right now, for instance, background location does not work for me in the Expo Go app, which is 41, and my app is still 40. I got my work done really close to the change, I got lucky.

So now I was working on updating to the 41 SDK, and I changed my permissions calls from the Permissions package to the Location package. With just basic testing, things appear to be working as expected in Android, but not on iOS.

I know this happened with Android, so I'm sure there's changes that affected iOS too:

https://github.com/expo/fyi/blob/master/android-r.md

>You may also observe in SDK <= 40 projects running the latest Play Store version of Expo Go that some functionality doesn't work as intended when using a device with Android R or higher. That's because we didn't backport changes required by the newest Android to the older SDKs. We didn't backport the changes because that would have broken existing applications on already-released SDKs and forced developers to change their code even when they didn't update the SDK version. When you building your app using SDK <= 40 with the expo build:android service, everything should work as it used to. For development purposes, rather than using the Expo Go app from the Play Store you can install an older version of Expo Go by running expo client:install:android in your project directory.

**Comment by brentvatne** [comment]
background location in expo go on ios was not possible from the start. apple is fairly strict about using it in your app on the app store and requires that you provide them with information about why you need it, and so we left it out because we distribute expo go on the store.

you could have used it with [custom expo go clients](https://docs.expo.io/guides/adhoc-builds/), but that was a temporary experiment and we do not support it in sdk 41+. the only way to test background location on sdk41+ on ios currently is by doing a simulator build `expo build:ios -t simulator` -- it's not ideal but [we are working on a better solution](https://blog.expo.io/expo-managed-workflow-in-2021-d1c9b68aa10).

**Comment by Petercopter** [comment]
@brentvatne Thanks for the clarification, and the hard work! This is the first time I've worked in mobile app development. Coming from web development, this is so much more difficult...

**Comment by bumaa7018** [comment]
> @bnussman I recently finished adding background location to a managed workflow Expo app, and background location was working in the Expo Go app with 40. It has obviously changed in 41, due to a major overhaul.
> 
> You want to start using `Location.getBackgroundPermissionsAsync` instead of `Permissions`, instead of managing permissions in one constant, each function will handle their own permissions (notifications, camera, location, etc).
> 
> https://blog.expo.io/expo-sdk-41-12cc5232f2ef

How can u use background location. Can u show me some example please.

**Comment by ansaf-kz** [comment]
I have the same issue, although when I `expo start` and run on IOS simulator it works perfectly(as expected), but when I publish it and run on my device via Expo Go app it fails with the warning message` [Unhandled promise rejection: Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.];`

It doesn't appear on `Location.requestForegroundPermissionsAsync `but on `Location.requestBackgroundPermissionsAsync`.

I use managed workflow, but I also created another expo project with bare workflow, added required keys manually via Xcode and it didn't work too. Unfortunately, my whole app is built on this Location functionality. 

What I also tried is using `Transistorsoft react native geolocation library`, it works perfectly, but I can't run it via Expo Go after publishing.

**Comment by guhanganesamurthi** [comment]
Hi @bnussman, I was able to get background location working in standalone build apps in expo 41 - Managed Workflow. 

**Requesting permission for foreground and background usage:** 
**Note that foreground permission should be asked first.**

 ``` 
        const { granted: fgGranted } =
        await Location.requestForegroundPermissionsAsync();
      if (!fgGranted) {
        return Alert.alert("Required", "Please grant GPS Location");
      }
      const { granted: bgGranted } =
        await Location.requestBackgroundPermissionsAsync();

      if (!bgGranted) {
        return Alert.alert(
          "Location Access Required",
          "App requires location even when the App is backgrounded."
        );
      }

      await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.BestForNavigation,
        timeInterval: 10000,
        foregroundService: {
          notificationTitle: "App Name",
          notificationBody: "Location is used when App is in background",
        },
        activityType: Location.ActivityType.AutomotiveNavigation,
        showsBackgroundLocationIndicator: true,
      });
```
      
**TaskManager Code outside in global scope:**
```
TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
  if (error) {
    console.log(error);
    return;
  }
  if (data) {
    const { locations } = data;
  }
});
```

**app.json changes:**
```   
 "ios": {
      "infoPlist": {
        "UIBackgroundModes": [
          "location"
        ],
        "NSLocationAlwaysAndWhenInUseUsageDescription":"App requires location even when the App is backgrounded."
      }
    },
    "android": {
      "permissions":["ACCESS_COARSE_LOCATION","ACCESS_FINE_LOCATION","ACCESS_BACKGROUND_LOCATION"]
    },
```

**Comment by ansaf-kz** [comment]
Hi @guhanganesamurthi, as I stated above it works perfectly. Could you please try to publish your project after `expo start` and run it on your real device via Expo Go?

**Comment by guhanganesamurthi** [comment]
HI @ansaf-kz , after expo start, it works as expected in Expo Go Android but not in iOS as issue states. Expo suggested building a [custom Expo Go for iOS](https://docs.expo.io/versions/v41.0.0/sdk/task-manager/) to get this working.  But that also has been [cancelled](https://docs.expo.io/guides/adhoc-builds/) for expo 41.

In my above post, I just wanted to showcase that it works in standalone builds.

**Comment by DCKT** [comment]
Hi !

After trying through the new command `expo run:ios` (https://blog.expo.io/introducing-expo-run-commands-835ae8da4813)

It appears that the `Info.plist` file is not generate properly, every `NS*` property present in the `app.json` has not been added.

**Comment by brentvatne** [comment]
@DCKT - can you provide a minimal reproducible example?

**Comment by brentvatne** [comment]
@DCKT - confirmed this is a regression in latest expo cli, investigating

**Comment by DCKT** [comment]
Hi @brentvatne it's working now thanks :)

**Comment by gugagranato** [comment]
@DCKT What did you do to make it work?

**Comment by ongkimlai** [comment]
hi @DCKT - how did you get it to work?

**Comment by brentvatne** [comment]
download the latest version of expo-cli

**Comment by ongkimlai** [comment]
@brentvatne i am still getting the error 
`[Unhandled` promise rejection: Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.]` 
I have included all 4 NSLocation*UsageDescriptions into my app.json, any help?

**Comment by ReidPolis1** [comment]
@ongkimlai Did you resolve this issue? I am getting the same issue and am contemplating reverting back to version 40

**Comment by bnussman** [comment]
I was able to solve this by making sure everything Expo related is updated and ensure you rebuild your app with all of the NSLocation*UsageDescription keys set in your `app.json`

**Comment by ReidPolis1** [comment]
@bnussman I am currently using Expo 3.23.2, and have been advised to not update my expo for risk of a project crash, so I don't know if I can "update everything expo related." If I choose to upload to the app store using version 40, and regular "requestPermissionAsync" with an updated P-List, will this still work for me as well?

**Comment by rachellevanger** [comment]
> Hi @guhanganesamurthi, as I stated above it works perfectly. Could you please try to publish your project after `expo start` and run it on your real device via Expo Go?

@guhanganesamurthi Any progress on this? I'm still unable to get background location to work on Expo Go for iOS.

**Comment by vhonLopez** [comment]
Any updates about this issue?

**Comment by ReidyPlayerOne** [comment]
Yes, I reverted my project back to Expo v.40 and the error went away. Starting at Expo v.41, the repo is depreciated, and they recommend changing how you request for permission. v.40 is still supported for at least another year, so we are sticking with that for now to prevent an overhaul.

**Comment by Razorholt** [comment]
> I was able to solve this by making sure everything Expo related is updated and ensure you rebuild your app with all of the NSLocation*UsageDescription keys set in your `app.json`

Can you please show us how you included the NSLocation in the app.json? Thanks!

**Comment by ReidPolis1** [comment]
For other reasons, we continued forward with SDK 42, and have not been able to resolve the issue, and am unsure how to handle this.

**Comment by bkiac** [comment]
> For other reasons, we continued forward with SDK 42, and have not been able to resolve the issue, and am unsure how to handle this. I keep seeing conflicting information, as some individuals claims you can run background location on Expo Go, while others cannot, and am unsure of how to handle this, as Background location is paramount in the development of our application.

@ReidPolis1  Background location works as expected on Android devices, for iOS, I use the simulator

**Comment by yakhnitskyy** [comment]
Cannot run background location tracking on iOS devices too. Any updates here?

**Comment by EvanBacon** [comment]
Could users who are still encountering this issue after it was closed please open a new issue and link to this one. We need info on the latest reproducible steps so we can assign someone.
