### ISSUE TITLE
Branch deep linking network error: A server with the specified hostname could not be found

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#1266]
Hey guys, I'm trying to use the branch integration but it doesn't seem to be working on iOS. It works on Android.

I get an error that 
```
A server with the specified hostname could not be found.
```
With error code: -1003.

It shows a link

```
exp://open?link_click_id=250114885521806484
```

Anyone know what this is about? In my app.json my scheme is `"scheme": "codePress",` and in Branch, my uri scheme is `codePress://` -- Is that correct?

**Comment by terribleben** [comment]
@janicduplessis any idea how to debug this?

**Comment by A-Zak** [comment]
We're also experiencing the exact same error... /:
I also found that it doesn't work if the app is in the background when I press the link, but if I kill the app before I press the link, it does work...

**Comment by kadoshms** [comment]
Same here. Works fine in Android but not in ios

**Comment by lightninglu10** [comment]
@terribleben @janicduplessis any updates on this? Would love to not have to eject and be able to use branch for my app

**Comment by lightninglu10** [comment]
@jameskennethrobinson just left it... Never found a solution to it. I think in the future we're just going to have to eject.

**Comment by jameskennethrobinson** [comment]
@lightninglu10 did you try and see if newer versions of the branch SDK integrated into expo in the time since you original comment fixed this issue?

**Comment by lightninglu10** [comment]
@jameskennethrobinson nope, haven't tried this but just looked at the docs and it does look different. Hopefully it's working on iOS now!

**Comment by jameskennethrobinson** [comment]
@lightninglu10 thanks for the help! Am integrating branch into my expo app currently and will let you know if it seems like this issue is resolved.

**Comment by lightninglu10** [comment]
@jameskennethrobinson any idea if this has been resolved or not? Did you manage to get branch integrated into expo?

**Comment by jameskennethrobinson** [comment]
Didn’t really test it out. Since I last posted I’ve migrated away from expo
to a vanilla RN project.

Not being able to debug Branch easily on expo was a deal breaker for us,
since our app relies heavily on Branch.

**Comment by AdamJNavarro** [comment]
Hey @lightninglu10,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
