### ISSUE TITLE
Cant Save a file in Device ERR: saveFileAsync Error: This file type is not supported yet

### ISSUE THREAD

**Issue by tigpalmas** [expo/expo#12664]
### Summary

i cant save any kind of file in device. For example, im trying to salve the pdf file in this url http://www.africau.edu/images/default/sample.pdf but gives me the error: 

repo: https://gitlab.com/tigpalmas1/savefileerrorexpo.git

ERR: saveFileAsync Error: This file type is not supported yet
    at Object.promiseMethodWrapper [as callMethod] (VM4 node_modules\expo\AppEntry.bundle:2767)
    at Object.NativeModulesProxy.<computed>.<computed> [as createAssetAsync] (VM4 node_modules\expo\AppEntry.bundle:99525)
    at createAssetAsync$ (VM4 node_modules\expo\AppEntry.bundle:157149)
    at tryCatch (VM4 node_modules\expo\AppEntry.bundle:29052)
    at Generator.invoke [as _invoke] (VM4 node_modules\expo\AppEntry.bundle:29225)
    at Generator.next (VM4 node_modules\expo\AppEntry.bundle:29095)
    at tryCatch (VM4 node_modules\expo\AppEntry.bundle:29052)
    at invoke (VM4 node_modules\expo\AppEntry.bundle:29125)
    at VM4 node_modules\expo\AppEntry.bundle:29155
    at tryCallTwo (VM4 node_modules\expo\AppEntry.bundle:3955)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\tiago\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

import * as React from 'react';
import {Button, Platform, StyleSheet} from 'react-native';

import {  View } from '../components/Themed';

import {LocalizationContext} from "../App";

import Constants from 'expo-constants';
import * as Permissions from 'expo-permissions';
import * as Notifications from 'expo-notifications';
import * as FileSystem from 'expo-file-system';
import * as MediaLibrary from 'expo-media-library';

export default function TabOneScreen(props) {
    const {navigation} = props ||{}
  // @ts-ignore
  const { t, locale, setLocale } = React.useContext(LocalizationContext);

    const downloadFile = ()=>{
        FileSystem.downloadAsync(
            'http://www.africau.edu/images/default/sample.pdf',
            FileSystem.documentDirectory + 'small.pdf'
        )
            .then(({ uri }) => {
                console.log('Finished downloading to ', uri);
                saveFileAsync(uri)

            })
            .catch(error => {
                console.error(error);
            });
    }

    const saveFileAsync = async (file_uri) =>{
        try {
            console.log('salvar arquivo');
            // const { status, permissions } = await MediaLibrary.requestPermissionsAsync();
            const { status, permissions } = await Permissions.askAsync(Permissions.MEDIA_LIBRARY);
            if (status === "granted" && permissions.mediaLibrary.accessPrivileges !== 'limited') {
                const asset = await MediaLibrary.createAssetAsync(file_uri);
                const album = await MediaLibrary.getAlbumAsync('Download');
                if (album === null) {
                    await MediaLibrary.createAlbumAsync('Download', asset, false);
                } else {
                    await MediaLibrary.addAssetsToAlbumAsync([asset], 'Download', false);
                }
                return true;
            }
            return false;
        } catch (error) {
            console.log('ERR: saveFileAsync', error);
            throw error;
        }
    }

  return (
      <View
          style={{
              flex: 1,
              alignItems: 'center',
              justifyContent: 'space-around',
          }}>

          <Button
              title="Press to schedule a notification"
              onPress={async () => {
                  await schedulePushNotification();
              }}
          />

          <Button
              title="Salvar arquivos"
              onPress={downloadFile}
          />
      </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  separator: {
    marginVertical: 30,
    height: 1,
    width: '80%',
  },
});

**Comment by manav-kasare** [comment]
I am facing this issue as well. I am trying to download a .wav file using this code here
```
const callback = downloadProgress => {
      const progress = downloadProgress.totalBytesWritten / downloadProgress.totalBytesExpectedToWrite;
    };
    console.log('downloading', url, title)
    const downloadResumable = FileSystem.createDownloadResumable(
      'https://soundbible.com/grab.php?id=2218&type=wav',
      FileSystem.documentDirectory + title + '.wav',
      {},
      callback
    );
    try {
      setLoader(true);
      const { uri } = await downloadResumable.downloadAsync();
      await saveFile(uri).then((rs) => {
        setLoader(false);
        getAudioFiles();
        alert('File Download Sucessfully!');
      });
    } catch (e) {
      console.log('error while downloading', e)
      console.error(e);
    }
```

**Comment by rahmanharoon** [comment]
Did you find any solution for this issue?

**Comment by Kibryant** [comment]
Solutions?
