### ISSUE TITLE
Expo Device not return any property

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo#12687]
### Summary

After upgrading to SDK 41 expo-device library doesn't return any property of device.
Maybe it has something with security features introduced in Android 11?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Jurica\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by brentvatne** [comment]
which properties specifically are not available? please provide code

**Comment by jurica-penjgusic** [comment]
So I am using this code for getting Device data.

    ```
      let model = {};
      model.brand = Device.brand;
      model.osName = Device.osName;
      model.modelId = Device.modelId;
      model.modelName = Device.modelName;
      model.deviceName = Device.deviceName;
      model.designName = Device.designName;
      model.manufacturer = Device.manufacturer;
      model.productName = Device.productName;
      model.platformApiLevel = Device.platformApiLevel;
```

**Comment by cruzach** [comment]
@jurica-penjgusic this snack seems to be working on Android 11- https://snack.expo.io/@charliecruzan/12687

Please don't open issues with and say that a repro is N/A, in the future any issues opened without a repro will be closed

**Comment by jurica-penjgusic** [comment]
Problem solved!
Apparently we didn't have at all installed expo-device! No clue what was happening. 
Reinstalling node modules and clean build solved it.
