### ISSUE TITLE
Update documentation for Android 11 Linking.canOpenUrl related permissions

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo#12680]
### Summary

I have simple instagram url. "https://www.instagram.com/<-Valid username ->/".

If I run await Linking.canOpenUrl(urlAbove) it returns false.
I think it is some security feature introduced  in Android 11 and there is something called Package Visibility.

Link to topic 
https://stackoverflow.com/questions/64699801/linking-canopenurl-returning-false-when-targeting-android-30-sdk-on-react-native

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

 Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Jurica\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by brentvatne** [comment]
it looks like you can add the `QUERY_ALL_PACKAGES` permission if you want to use this in your standalone app, but you won't be able to modify it in Expo Go, the same as `LSApplicationQueriesSchemes` on ios

**Comment by jurica-penjgusic** [comment]
Tnx Brent for quick response!
For now it will work...
In the future can we expect more granularity over this Packages Visibility?

**Comment by jurica-penjgusic** [comment]
Hi Brent!

I can confirm this permission covers theissue.
Maybe it would be wise to put this permission in default permissions or notice about behaviour in Expo Linking section.

You will know better :)

Keep up with good work!
