### ISSUE TITLE
[iOS][Video] setPositionAsync not working 

### ISSUE THREAD

**Issue by riwu** [expo/expo#1269]
https://github.com/riwu/expo-video-seek
Clone the above and run it on iOS (it works on snack but not on local environment for some reason).

![](https://i.imgur.com/9yrQPW4.png)
```
await this.video.setPositionAsync(2500);
const status = await this.video.getStatusAsync(); // positionMillis is 0
```
The video is set to position of 0 instead of 2500.

Environment: 
node: v9.3.0
yarn: 1.3.2
Mac sierra
iOS 11.2

**Comment by sjchmiela** [comment]
Ha! That's exactly where setting seek tolerance comes in handy. See Expo documentation [on seek tolerance](https://docs.expo.io/versions/latest/sdk/av.html#what-is-seek-tolerance-and-why-would-i-want-to-use-it) and provide `setPositionAsync` with a second argument, like:

```javascript
const status = await this.video.setPositionAsync(offset, {
  toleranceMillisBefore: 0,
  toleranceMillisAfter: 0
});
```

That seems to fix the problem.
