### ISSUE TITLE
To which repo should issues be posted?

### ISSUE THREAD

**Issue by lucfranken** [expo/expo#127]
See:
https://github.com/expo/expo-sdk/issues/53#issuecomment-296453104

Currently it's not clear to me where to report issues to. 

Maybe it would be good to add something in the readme on where to post issues? So it's clear what you prefer?

**Comment by dikaiosune** [comment]
We recently decided to direct issue reports to this repository, and I believe all of the other repos have updated issue templates to make that clear. Thanks for highlighting this!
