### ISSUE TITLE
Facebook login never redirects to app after successful login in Facebook App in Iphone

### ISSUE THREAD

**Issue by deepti-nucleusteq** [expo/expo#12708]
### Summary

Using the code below as given in the documentation. It takes to a page which asks to open the app. The app opens and the login succeeds and then it redirects to the same page again and stays there only.

      

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.5.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 22, 26, 28, 29
        Build Tools: 22.0.1, 23.0.1, 25.0.1, 26.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
        System Images: android-22 | Android TV Intel x86 Atom, android-22 | ARM EABI v7a, android-22 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

    using the code below in an ejected app (bare flow).

      await Facebook.initializeAsync({appId: facbookAppId, appName: 'Fyndr'});
      let { type, token } = await Facebook.logInWithReadPermissionsAsync({
           permissions: ['public_profile', 'email']
      });

       if (type === 'success') { 
     
       }

**Comment by cruzach** [comment]
This indicates you haven't gone through the proper native setup for `expo-facebook`. Are you sure you have the [proper app.json configuration for `expo-facebook`](https://docs.expo.io/versions/latest/sdk/facebook/#configure--appjson), and have run `expo prebuild` (or `expo eject`) _after_ adding that config?

**Comment by deepti-nucleusteq** [comment]
Yes I did here are the entries in info.plist :
```<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb339365493739503</string>
			</array>
		</dict>
	</array>
	<key>FacebookAppID</key>
	<string>339365493739503</string>
	<key>FacebookDisplayName</key>
	<string>Fyndr</string>
```
In the earlier expo version there was a parameter `behaviour: 'web' `,  I used that to  solve the issue but this parameter doesn't work anymore in expo 41.

**Comment by cruzach** [comment]
> It takes to a page which asks to open the app. The app opens and the login succeeds and then it redirects to the same page again and stays there only.

can you provide a video or set of screenshots to show which pages you're referring to?

**Comment by deepti-nucleusteq** [comment]
![image](https://user-images.githubusercontent.com/66106605/116093876-ad866900-a6c4-11eb-90e9-b24e0b8a021d.png)

This screen it is stuck at:
![image](https://user-images.githubusercontent.com/66106605/116094110-e292bb80-a6c4-11eb-863f-d28a97180964.png)

**Comment by cruzach** [comment]
you can't select `Open`?

**Comment by deepti-nucleusteq** [comment]
yeah I do, please see here:
https://drive.google.com/file/d/11ou7YJtZfBKi0rttEmQqL7L-gq3NHue9/view?usp=sharing

**Comment by developer-at-openbar** [comment]
Facing the same problem

**Comment by deepti-nucleusteq** [comment]
> Hello @deepti-nucleusteq , @developer-at-openbar , i was facing the same issue in the video.
> In my case, it conflicts with other `schemes` when application try to openURL. Solved by checking if openURL from facebook then return supper. Hope it can help.
> ![](https://camo.githubusercontent.com/d22f87b097a16a3c706eb0221d76ea2e4760f8dd7c35a527899bc968108b357c/68747470733a2f2f692e696d6775722e636f6d2f5078744c3330312e706e67)

Awesome,  Many Thanks @annguyen-iosdev !! Yes it's working now, below is my code snippet in file  AppDelegate.m :
```- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  NSString *fbScheme = [NSString stringWithFormat:@"fb%@", NSBundle.mainBundle.infoDictionary[@"FacebookAppID"]];
  if ([[url scheme] isEqualToString:fbScheme]) {
      return [super application:application openURL:url options:options];
  }
  return [RCTLinkingManager application:application openURL:url options:options];
}```
