### ISSUE TITLE
interpolate() was renamed to interpolateNode() in Reanimated 2. Please use interpolateNode() instead

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo#12709]
### Summary

SDK 41 is throwing a warning which seems to be slowing down the app itself.

After upgrading to SDK 41 the app navigation animations are running noticeably slower.

Warning displayed on every screen multiple times:
interpolate() was renamed to interpolateNode() in Reanimated 2. Please use interpolateNode() instead

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 25, 26
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.0 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Upgrade to SDK 41 and import   "react-native-reanimated": "~2.1.0"

**Comment by brentvatne** [comment]
this is due to an update in reanimated api, you should find the underlying code using reanimated that is calling the deprecated name and fix it. if it's a library, maybe you need to update it. you can also silence this warning if you want: https://reactnative.dev/docs/debugging#console-errors-and-warnings

**Comment by mikeRChambers610** [comment]
I am not using reanimated in any code. Expo is pulling in the package and now that expo is using reanimated version 2, I am getting glitches all over the place in my app.

**Comment by mikeRChambers610** [comment]
Also, when I update the reanimated package, the app crashes and says "interpolate is not a function"
