### ISSUE TITLE
Test icon badge set in production

### ISSUE THREAD

**Issue by zaharzagrava** [expo/expo#12702]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by zaharzagrava** [comment]
I have this `TaskManager` task defined below. It fetches authentication endpoint, as well as two 
data api endpoints and should set badge count after that:

    import * as TaskManager from 'expo-task-manager';
    import * as Notifications from 'expo-notifications';
    
    // Constants
    import tasksIds from '../constants/tasks';
    
    // Services
    import { api } from '../services/Api';
    
    TaskManager.defineTask(tasksIds.UPDATE_NOTIFICATIONS_BADGE, async () => {
      const sessionResponse = await api.session.get(); // authenticate user
      const unreadNotifications = await api.notifications.getUnread() as any; // get number of unread notifactions
      const unreadRooms = await api.rooms.getUnread() as any; // get number of unread rooms
      await Notifications.setBadgeCountAsync(unreadNotifications.data.unread + unreadRooms.data.unread); // sum up
    });

I have this task registered in my Main component:

    BackgroundFetch.setMinimumIntervalAsync(10); // 10 seconds

    BackgroundFetch.registerTaskAsync(tasksIds.UPDATE_NOTIFICATIONS_BADGE, {
      minimumInterval: 10,
      startOnBoot: true
    });

Locally, the task runs and successull calls `setBadgeCountAsync` with accurate number. The problem is that I cannot test it until production (on TestFlight), and on TestFlight I do not see any changes to badge counter.

How do I test badge counter changes in development? Or at least how do I make it work in production?

**Comment by cruzach** [comment]
Closing since as the template says:

> Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?
> Yes

My best advice would be to inspect the native device logs in your standalone app and see if there are any relevant errors or warnings there
