### ISSUE TITLE
Expo app icon showing instead of my icon

### ISSUE THREAD

**Issue by ziyadparekh** [expo/expo#1270]
I have a detached app and am building it with android studio. However when I install the apk to my device it uses the expo icon instead of the one that I specified in my app.json under both the ‘icon’ property and ‘android.icon’ property as paths to a png file. 

I’ve seen this issue before but seems like the fix was for apps that haven’t detached. This is also affecting notifications. 

Any ideas on how to fix it? Could it be related to the KeyStore?

Thanks

**Comment by jesseruder** [comment]
Hey @ziyadparekh. The detached app should be using the icon from app.json at the time you ran `exp detach`. If you change the icon in app.json after that point it won't be picked up.

**Comment by ziyadparekh** [comment]
Hi @jesseruder. Thanks for the reply. I set the icon before I detached the app and it didn’t work. But regardless, if I want to change the icon for future purposes how would you recommend I go about it?

**Comment by jesseruder** [comment]
Ok thanks, that's definitely an issue and we'll look into it. You can specify the icon the same way as in a normal Android app: https://developer.android.com/studio/write/image-asset-studio.html.

Thanks again for the report!

**Comment by fxfactorial** [comment]
This is fixed in next release.

**Comment by EgidioCaprino** [comment]
Hi @fxfactorial 

How can I re-generate the app icon for an ejected app?
