### ISSUE TITLE
Error: native module cannot be null for expo-store-review on ios

### ISSUE THREAD

**Issue by vuciv** [expo/expo#12713]
### Summary

When importing from expo-store-review, you get the error "native module cannot be null"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 26, 28, 29
        Build Tools: 26.0.2, 28.0.3, 29.0.3
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ^0.16.1 => 0.16.1
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Open a blank managed workflow and include the following line:

`import * as StoreReview from 'expo-store-review';`

**Comment by brentvatne** [comment]
I cannot reproduce this.

```
expo init someproject
cd someproject
expo install expo-store-review expo-linking
```

```js
import { StatusBar } from "expo-status-bar";
import React from "react";
import { Button, StyleSheet, View } from "react-native";
import * as StoreReview from "expo-store-review";

export default function App() {
  return (
    <View style={styles.container}>
      <Button
        title="Request review"
        onPress={() => {
          StoreReview.requestReview();
        }}
      />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

**Comment by brentvatne** [comment]
made a related issue re: expo-linking: https://github.com/expo/expo/issues/12714
