### ISSUE TITLE
Module AppRegistry is not a registered callable module on iOS only

### ISSUE THREAD

**Issue by cescoferraro** [expo/expo#1271]
Ita a very simple app. All it leverages is the BarCodeScanner to do some qrcode validations.
It works just fine on Android, but it crashes on ios saying:

Module AppRegistry is not a registered callable module( calling run application)

Is published here
https://expo.io/@cescoferraro/rambo
Code lives here on master
https://github.com/cescoferraro/rambo

please help!

**Comment by terribleben** [comment]
Hi, the actual error is `undefined is not an object (evaluating 's.Constants.experienceUrl.split')`.

Does this issue only happen in your published app, or are you able to reproduce it in XDE/exp by turning off the "dev" option?

**Comment by cescoferraro** [comment]
not reproducible when turning dev option off.
I am doing the following in order to get an api URL on dev.
@terribleben  What the right way to do this?

```
const ip = Constants.experienceUrl.split(':')[1]
export const apiURL = () => (__DEV__ ? "http:" + ip + ":7000/" : "https://api.onni.live/")
```

**Comment by terribleben** [comment]
Ok.

- For your specific bug, there isn't anything called `experienceUrl` in [Constants](https://docs.expo.io/versions/latest/sdk/constants.html). You might try parsing the components of `Constants. linkingUri` to extract the information you need.
- We're hoping to ship a fix in the next Expo SDK which will hide the "AppRegistry is not a registered..." error, which is annoyingly blocking your real error message.

**Comment by cescoferraro** [comment]
@terribleben that was it! No more errors. But how did you find out the actual error?

**Comment by MorganDream** [comment]
@terribleben Yes, I am stuck with this error, too and want to debug the real issue. It only happens to my detached published app on iphone.

**Comment by githubmss** [comment]
Getting the same issue with the detached published app on iPhone.How can I solve it, it's not displaying any actual error I am using exp sdk version 27.0
