### ISSUE TITLE
AuthRequest throwing error when debugging with RN debugger

### ISSUE THREAD

**Issue by madroneropaulo** [expo/expo#12712]
### Summary

This pull request https://github.com/expo/expo/pull/10298/files introduced some changes that use the synchronous version of the PKCE generateRandom function instead of the async one. Now Expo is throwing this complaint when trying to debug with React Native Debugger:

`Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome`

I'm not 100% sure but I believe it's because the generateRandom is calling sync functions now.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

Expo CLI 4.1.6 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.0/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
    npmPackages:
      expo: ^41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: 0.13.12 => 0.13.12 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

use the useAuthRequest hook from expo-auth-session AND enable RN debugger.

**Comment by TanasieAlexandru** [comment]
I had the same problem, however I was using expo-auth-session as a separate dependency. I had the version 3.2.3 installed. I downgraded to version 3.0.0 and it worked. I had to clear expo cache and npm cache because just installing another version did not seem to work. Until a new version of the package appears that supports debugging I will continue to use version 3.0.0 of  expo-auth-session.

**Comment by stdavis** [comment]
Downgrading to v3.0.0 didn't work for me. :(

**Comment by stdavis** [comment]
This is a huge deal for me. I don't want to downgrade but not having a debugger is such a pain. If someone can point me in the right direction, I'd be happy to work on a PR to fix this. I assume that we would just call some non-sync method during development.

**Comment by alexyangjie** [comment]
The problem lies in the constructor of the `AuthRequest` class in expo-auth-session. 

```
this.state = request.state ?? PKCE.generateRandom(10);
```

This method calls `ExpoRandom.getRandomBase64String()` in expo-random, which is a sync call that fails in the debugger.
