### ISSUE TITLE
[docs]  Installation instructions on expo-file-system for iOS unclear

### ISSUE THREAD

**Issue by SeveHo** [expo/expo#12723]
### Summary

What I did to install the package:
1. expo install expo-file-system
2. npx pod-install

Since I have unimodules already installed I can't really get my heady around this sentence in the install instructions here: [Apart from following those steps, make sure your AppDelegate extends UMAppDelegateWrapper as shown here.](https://github.com/expo/expo/tree/master/packages/expo-file-system#installation-in-bare-ios-react-native-project)

I have two Problems: 
1. The part that says "**those steps**" just point to the page itself. Is my  assumption right that the documentation to installing unimodules should be linked here or are there others steps required?
2. What are the important changes that are linked at "[as shown here](https://gist.github.com/lukmccall/d2b97b2dde0d1aa04a245a369ffdd153)"? For me it seems like that if one follows the unimodules instructions nothing needs to be changed here. @lukmccall Maybe you could points this out please?

### Link to the related docs page

https://github.com/expo/expo/tree/master/packages/expo-file-system#installation-in-bare-ios-react-native-project

### Anything else?

expo v.40
node 15.14

**Comment by lukmccall** [comment]
1. "those steps" should point to https://docs.expo.io/bare/installing-unimodules.
2. Yes, you are right. No additional steps, apart from those in unimodules instructions, are needed. I really don't remember why I linked this gist.
