### ISSUE TITLE
Requiring modules like Expo-AV for permissions seems excessive

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#12721]
### Summary

There used to be a standalone module for permissions. From what I can tell not everyone needed it in unimodules so it was moved out of Expo to its own module. Now individual permissions have been moved out of it to modules like `Expo-AV` this is a questionable decision. Expo-AV is about 2MB, and if all a user needs is microphone permissions, they are going to bringing in a 2MB Pod in order to do it. This leaves me scratching my head and wondering why all of this work was done to move permissions into heavy modules like this.

By comparison in [react-native-permissions](https://github.com/zoontek/react-native-permissions) I can bring in the base plugin for **66kb** and microphone permissions for just **12kb**. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

41 bare

### Reproducible demo or steps to reproduce from a blank project

NA

**Comment by brentvatne** [comment]
why would you request microphone permission without an api that uses that capability? if a library uses microphone, it can provide its own mechanism for requesting permissions. using unimodules permissions infra this is really straightforward: 

1) https://github.com/expo/expo/blob/68b9bccf60b42f9aa59d4c92bb026f0fa0f1e2b4/packages/expo-camera/ios/EXCamera/EXCameraPermissionRequester.m
2) https://github.com/expo/expo/blob/68b9bccf60b42f9aa59d4c92bb026f0fa0f1e2b4/packages/expo-camera/ios/EXCamera/EXCameraManager.m#L333-L351

**Comment by shamilovtim** [comment]
> why would you request microphone permission without an api that uses that capability? if a library uses microphone, it can provide its own mechanism for requesting permissions. using unimodules permissions infra this is really straightforward:
> 
> 1. https://github.com/expo/expo/blob/68b9bccf60b42f9aa59d4c92bb026f0fa0f1e2b4/packages/expo-camera/ios/EXCamera/EXCameraPermissionRequester.m
> 2. https://github.com/expo/expo/blob/68b9bccf60b42f9aa59d4c92bb026f0fa0f1e2b4/packages/expo-camera/ios/EXCamera/EXCameraManager.m#L333-L351
> 
> edit: i don't recall the full context behind this decision, can follow up on it when i'm back from vacation at the beginning of may if nobody else chimes in

There are many apps in the ecosystem which do not roll their own permissions and instead depend on an outside permission manager to do that. Which is what I thought expo-permissions was until the permissions got moved into heavy modules like expo-camera or expo-av. That move made it so we can't use expo-permissions for permissions alone and so I've had to switch to react-native-permissions. That plugin is very minimal and from what I can tell it does a pretty good job at only bringing in what it needs.

**Comment by brentvatne** [comment]
that makes sense. maybe we can just recommend people use react-native-permissions for these use cases. it's not necessary in expo managed apps because every api you can use will have associated permissions requesters available, but as we expand the scope of managed apps so users can install other libraries, react-native-permissions may be a reasonable solution. i'm not crazy about having to work around autolinking to include only specific permissions though, i feel like this is handled more gracefully by having the permissions included by modules that use them.
