### ISSUE TITLE
expo-speech: Speech.speak voice option doesn't work

### ISSUE THREAD

**Issue by xam7247** [expo/expo#12720]
### Summary

Whatever identifier you provide for `voice:` option in `Speech.speak`, it doesn't speak in that voice, and rather speaks in the platform's default voice. 

From the code it seems to be due to line 34:37 in https://github.com/expo/expo/blob/master/packages/expo-speech/src/Speech/ExponentSpeech.web.ts :

   ```
 if ('_voiceIndex' in options && options._voiceIndex != null) {
      const voices = window.speechSynthesis.getVoices();
      message.voice = voices[Math.min(voices.length - 1, Math.max(0, options._voiceIndex))];
    }
```

Its looking for a `'_voiceIndex'` in options passed by user, and if I do pass `_voiceIndex: 3` or any random number, it does speak in that particular voice. 

If you pass `voice: 'Daniel'` (an identifier as obtained from `Speech.getAvailableVoicesAsync()`, it is completely ignored.

I think this is broken since #3186. Just that 'voiceIOS' got changed to 'voice'. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

8.4.0

### Environment

Expo CLI 3.27.8 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-native-web: ^0.15.7 => 0.15.7
      react-navigation: 4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.27.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

The same snack can be used: https://snack.expo.io/@saumyanegi/tts-speech-test

- Try playing with '`voice`' option. Observe that it has no effect. The speech is spoken in your system's default voice set.
- Try commenting out '`voice`' option, and uncommenting '`_voiceIndex`'. Observe that speech is spoken in the correct voice at the given voiceIndex.

**Comment by Razorholt** [comment]
Use the identifier, not the name. For example, in iOS: "com.apple.ttsbundle.Karen-compact"

**Comment by AdamJNavarro** [comment]
Hey @xam7247, as @Razorholt mentioned above, you'll want to pass the identifier property of the voice object rather than the name. However, when fetching the available voices, it seems that on the first call the `identifier` value is being replaced by the `name` value. Subsequent calls seem to return the appropriate identifier value. Can you confirm that's happening for you? You can use this [Snack](https://snack.expo.io/@adamjnav/056889).

**Comment by Razorholt** [comment]
Hey @AdamJNavarro I updated the post regarding the issue you just mentioned. Have you tried the solution I suggested?

**Comment by xam7247** [comment]
Hey @AdamJNavarro, @Razorholt, It makes no difference for me whether I use the name (like `voice: 'Daniel'`) or a raw identifier (like `voice: "com.apple.ttsbundle.Karen-compact"`). It doesn't use the voice, and I can't see why/where it would pick the `voice` property in code, since its looking for a `_voiceIndex` property in code (which does work). 
[Snack](https://snack.expo.io/@saumyanegi/tts-speech-test) reflects this behaviour if you try by uncommenting the `_voiceIndex` property, or `voice` property.

Do you hear different voices (apart from the default voice set on the device) when providing this property ?

Also for me, after the first call (returning a blank array [] due to #11502), all subsequent calls to `Speech.getAvailableVoicesAsync()` return the same array with objects like: 
`{ identifier: "Alice", isDefault: false, language: "it-IT", localService: true, name: "Alice", quality: "Default", voiceURI: "Alice" }`, which does seem right based on the `getVoices()` method defined on line 67:78 in https://github.com/expo/expo/blob/master/packages/expo-speech/src/Speech/ExponentSpeech.web.ts: 
```
getVoices(): WebVoice[] {
    const voices = window.speechSynthesis.getVoices();
    return voices.map(voice => ({
      identifier: voice.voiceURI,
      quality: VoiceQuality.Default,
      isDefault: voice.default,
      language: voice.lang,
      localService: voice.localService,
      name: voice.name,
      voiceURI: voice.voiceURI,
    }));
  },
```
So either I am missing something, or this is broken. I am on "expo-speech": "~8.4.0", if it makes any difference.
