### ISSUE TITLE
[Expo 41] isRTL returns false on right-to-left languages on iOS

### ISSUE THREAD

**Issue by chybisov** [expo/expo#12737]
### Summary

My team work on app with Hebrew support and after updating to SDK41 `isRTL` returns `false` when language set to Hebrew on iOS.

I think last commit to expo-localization package broke this:

SDK40: https://github.com/expo/expo/blob/sdk-40/packages/expo-localization/ios/EXLocalization/EXLocalization.m
SDK41: https://github.com/expo/expo/blob/sdk-41/packages/expo-localization/ios/EXLocalization/EXLocalization.m

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD   
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: ^17.0.2 => 17.0.2
      react-dom: ^17.0.2 => 17.0.2
      react-native: ^0.63.4 => 0.63.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@chybisov/isrtl

1) Set language to Hebrew in iOS Language & Region settings.
2) Run snack.
3) Switch to SDK41 to see wrong behavior.
![image](https://user-images.githubusercontent.com/18644653/116129988-62278700-a6d3-11eb-9ac1-a7effd0f6a83.png)

**Comment by chybisov** [comment]
@IjzerenHein could you please look on this? Thank you!

**Comment by AdamJNavarro** [comment]
Hey @chybisov, thanks for the detailed report on this issue. I was able to reproduce it on a simulator with the OS language set to Hebrew like you mentioned. With that said, please refrain from pinging team members on issues. We have support systems in place to take care of routing and escalation and prefer to not cause unnecessary distraction.

Cheers,
Adam

**Comment by chybisov** [comment]
@AdamJNavarro sorry for that. I’ll patiently wait for the fix 😄

**Comment by EvanBacon** [comment]
Our module interfaces with the native platform's API for dictating if the given language code is RTL. You may find better luck using the React Native module which returns what the layout direction is:

```js
import { I18nManager } from "react-native";
I18nManager.isRTL
```

**Comment by ammar-oker** [comment]
Hello,

I'm still encountering the same issue with the most recent version of Expo on iOS. While the deprecated `Localization.isRTL` provides the accurate result, `I18nManager.isRTL` consistently returns `false`.

**Environment**
```
  expo-env-info 1.0.5 environment details:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 10.1.0 - /opt/homebrew/bin/npm
      Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/ammar/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Reproduction Code**
```jsx
import { Text, View, I18nManager } from 'react-native';
import * as Localization from 'expo-localization';

export default function App() {
  return (
    <View>
      <View>
        {/* Assuming the device's locale is set to 'ar-SA' (Arabic, Saudi Arabia) */}
        <Text>Expo locale: {Localization.locale}</Text>

        {/* Expected: `true`, Received: `true` */}
        <Text>Localization.isRTL (deprecated): {Localization.isRTL ? 'true' : 'false'}</Text>

        {/* Expected: `true`, Received: `false` */}
        <Text>I18nManager.isRTL: {I18nManager.isRTL ? 'true' : 'false'}</Text>
      </View>
    </View>
  );
}

```

```json
{
  "expo": {
    ...
    "plugins": [
      "expo-localization"
    ],
    "extra": {
      "supportsRTL": true
    }
  }
}

```

**Comment by AronBe** [comment]
Actually was facing a similar issue with `I18nManager.isRTL` being always `false`. 

Solution for me: after I removed `"supportsRTL": true` from `extra` and the associated generated info.plist value disappeared, I18nManager forcing RTL started working as expected and was persisted 🤷‍♂️
