### ISSUE TITLE
expo-facebook config plugin always adds NSUserTrackingUsageDescription to Info.plist

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo#12746]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

So EAS build adds NSUserTrackingUsageDescription  property, which then is triggering to update App privacy in App store.
Is there any way to avoid this, because we must ask then that permission and if we don't ask this App store rejects app?

**Comment by cruzach** [comment]
@jurica-penjgusic that is added not by EAS Build, but by one of the packages you're relying on. It could be:
- `expo-facebook`
- `expo-ads-facebook`
- `expo-ads-admob`

**Comment by jurica-penjgusic** [comment]
Alright, we will change title to something appropriate...

We have expo-facebook installed and used for login functionality. 
It is adding NSUserTrackingUsageDescription  to info.plist which is forcing us to update App Privacy in App Store Connect.
So in order to submit for verification we need to say in privacy that we are tracking some data.
When reviewers came they wanted know where is IDFA permission is asked, in our case it wasn't asked at all because we didn't collect data. So they told us  update App privacy to not track data but we can't because App store connect require something to track because of above property.

Any direction would help us a lot.

Tnx

**Comment by cruzach** [comment]
The fact is that the _code_ for requesting IDFA permission is included in `expo-facebook`, which is what I believe is of concern to app review. You can eject your project and remove that key from info.plist and see if Apple accepts the app?

**Comment by jurica-penjgusic** [comment]
Tnx, 
Is there any chance we opt-in some "permissions" on Ios  in future?

**Comment by brentvatne** [comment]
@jurica-penjgusic - you can change the config plugin for your project by using something like [`patch-package`](https://www.npmjs.com/package/patch-package) to remove this line: https://github.com/expo/expo/blob/e0bb254c889734f2ec6c7b688167f013587ed201/packages/expo-facebook/plugin/src/withFacebookIOS.ts#L207-L208 (you will need to modify the build fille: https://github.com/expo/expo/blob/e0bb254c889734f2ec6c7b688167f013587ed201/packages/expo-facebook/plugin/build/withFacebookIOS.js#L167-L168)

that will stop it from adding the permission. alternatively, you can [create a config plugin](https://docs.expo.io/guides/config-plugins/) to remove that key.

**Comment by jurica-penjgusic** [comment]
So I created config plugin and added to plugins section of app.json.
Plugin is called properly.

`module.exports = function withTrackingRemoval(config) {
  if (!config.ios) config.ios = {};
  if (!config.ios.infoPlist) config.ios.infoPlist = {};
  delete config.ios.infoPlist["NSUserTrackingUsageDescription"];
  return config;
};`

I have inspect info.plist and NSUserTrackingUsageDescription property is still there. 
If we output config to console while building project with eas build it shows info.plist empty.
Maybe it is adding those properties later?

**Comment by brentvatne** [comment]
@jurica-penjgusic - if you explicitly add the facebook plugin (right now it's being added automatically in order to support apps where they haven't started using plugins yet) to the `plugins` array then you can control when it executes. the info plist type doesn't include all values, in some cases because you can add any arbitrary string and in other cases because we haven't added it to the type yet. you may need to ts-ignore to get past type checking for this.

cc @EvanBacon re: NSUserTrackingUsageDescription in the plugin - maybe we want to make it possible to opt-out with an option to the plugin

**Comment by jurica-penjgusic** [comment]
If you opt out that property that would be awesome! 
Maybe ask when they are building app do they track users or something like that?
Solution that would be like "click to click" and app is ready for production, in the spirit of what Expo represents...

Tnx for patience and understanding!

**Comment by EvanBacon** [comment]
Related:

- disable permissions: https://github.com/expo/expo/pull/12627
- improve Info.plist type: https://github.com/expo/expo-cli/pull/3442

**Comment by cruzach** [comment]
@jurica-penjgusic just want to reiterate what I said above, if you leave this permission out but include the `expo-facebook` module, your app may be rejected by app review

**Comment by EvanBacon** [comment]
A hacky solution would be to add expo-facebook to the plugin history to prevent it from being run "twice".

`app.json`
```
{
  "_internal": {
    "pluginHistory": {
      "expo-facebook": {}
    }
  }
}
```

This will trick the plugin compiler into thinking that `expo-facebook` has already been run, then prevent any other config plugins registered with the name "expo-facebook" from being invoked.

This may have unintended side-effects though as expo-facebook does more than just adding that permission.

A slightly better solution would be to create a "modifier" that removes the permission, this may not work long term, but it currently it does run after the other plugins since the other plugins aren't using mods yet:

`no-tracking.js`
```js
const { withInfoPlist } = require("@expo/config-plugins");
module.exports = (config) => {
  return withInfoPlist(config, (config) => {
    delete config.modResults["NSUserTrackingUsageDescription"];
    delete config.modResults["SKAdNetworkItems"];
    return config;
  });
};
```

`app.json`
```json
{
  "plugins": ["./no-tracking"]
}
```

Doing any of these things can easily break other modules though and lead to app rejections. Apple scans for included native headers and the native Facebook package that we install with `expo-facebook` will include headers that require user tracking.

**Comment by jurica-penjgusic** [comment]
No worries mates, classic build doesn't add this permission yet. 
This morning I was able to produce binary, expo-facebook included, built with classic build, without NSTracking property.
So we are looking for more classy solution that will work for all of us

**Comment by jurica-penjgusic** [comment]
@cruzach So if we include expo-facebook and that permission is added.
 Then permission is forcing us to update Privacy policy in a way that we are saying we are tracking user.
 On app review reviewer is seeing our updated privacy policy and he is asking where are you asking permission (Can this app track you across websites and apps?). 
 
 If we say we do not track, then  he will say please update privacy policy in way that we say we do not track user.
App store won't let us update policy in way as reviewer said because of NSTracking property. 

So we get stuck between reviewer and app store. Without properly configured app privacy there is no submission for review.
I think reviewer is more concerded about our privacy policy, rather we include expo-facebook or use login funcionality. 
I think they are caring about transparency,
 If you track then say in privacy you track, if not please say in privacy you don't track.

**Comment by jurica-penjgusic** [comment]
Reproducable demo for this.
1) Run expo-init with typescript template selected.
2) Install expo-facebook.
3) Build binaries with classic build for IOS
4) Build binaries with Eas build for IOS
5) Download ipa files.
6) Rename both files from "my-binary-build.ipa" to "my-binary-build.zip"
7) Extract it and locate info.plist under Payload/"App"
8) Compare Info.Plist from both of builds.
Classic build Info.plist should be formatted clean and there would be no NsUserTrackingUsageDescription property
Eas build Info.plist is differently formatted, but if you open it with text editor and Search for above property you should find it. 

```
import React from 'react';
import * as Facebook from 'expo-facebook';
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {

  async function signInWitFacebookAsync() {
    try {
      await Facebook.initializeAsync({appId: "APPId", appName: "APP name"});
      let response: any = await Facebook.logInWithReadPermissionsAsync({permissions: ['public_profile', 'email']});
      if (response.type !== "success") return;
    } catch (e) {

    }
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <StatusBar style="auto"/>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by EvanBacon** [comment]
In https://github.com/expo/expo/pull/12767 I've added a prop to disable the permission for that module. When it lands, you can update `expo-facebook` and add the following to your app.json:

```json
{
  "expo": {
    "plugins": [
      ["expo-facebook", { userTrackingPermission: false }]
    ]
  }
}
```

This will only prevent `expo-facebook` from adding the permission automatically, other modules like expo-ads-facebook or expo-ads-admob can still add the permission.

**Comment by Symyon** [comment]
@EvanBacon can we add this to the expo-facebook documentation? Took a while to find it

**Comment by EquesMedia** [comment]
@EvanBacon, I agree with @Symyon. This information was capital for us (we could not submit the app to Apple Store) and I had to contact support to find this.

**Comment by AbdeenM** [comment]
+1

Our app has been rejected cause of this. it took all day to find that expo-facebook was the one using the App Tracking Transparency framework. about to make another build and submit.

Please add it to the official docs, trust me you will be saving life's :)

Thanks

**Comment by brentvatne** [comment]
added to docs here: https://github.com/expo/expo/commit/c7ebdf7a6fd7c2e58d6c8ce0cd98d519ed19a29e

**Comment by mbuxmann** [comment]
For some reason this doesn't work 

> In #12767 I've added a prop to disable the permission for that module. When it lands, you can update `expo-facebook` and add the following to your app.json:
> 
> ```json
> {
>   "expo": {
>     "plugins": [
>       ["expo-facebook", { "userTrackingPermission": false }]
>     ]
>   }
> }
> ```
> 
> This will only prevent `expo-facebook` from adding the permission automatically, other modules like expo-ads-facebook or expo-ads-admob can still add the permission.
> 
> This should resolve the issue for you.

It seems like it doesn't work in expo 44 SDK. Since when I use expo build:ios, I get the following error: 

Plugin is an unexpected type: object

**Comment by jurica-penjgusic** [comment]
I think plugins works only with eas build command

**Comment by mbuxmann** [comment]
> I think this would work if you build with eas-cli commands

When using eas build -p=ios, I receive the same error.

```
    PluginError: Plugin is an unexpected type: object
    Code: INVALID_PLUGIN_TYPE
```

**Comment by brentvatne** [comment]
@mbuxmann - this should be:

```
     "plugins": [
        "expo-notifications",
        ["expo-facebook", { "userTrackingPermission": false } ],
      ]
```

**Comment by mbuxmann** [comment]
> @mbuxmann - this should be:
> 
> ```
>      "plugins": [
>         "expo-notifications",
>         ["expo-facebook", { "userTrackingPermission": false } ],
>       ]
> ```

Dam... Thank you very much! Sorry for my stupidity.
