### ISSUE TITLE
How to replace keychain file and google cer file ?

### ISSUE THREAD

**Issue by lyquocnam** [expo/expo#1275]
Hi author, i'm already have project on Google Play and AppStore, i want to change my codebase to Expo but problem is i can not change or setup keychain or .cer for current expo project.
it''s only show 1 time when i created expo project and i choose "let expo create...", but i can not find where the files stored to replace them.

**Comment by terribleben** [comment]
To get the files Expo generated, you can run these commands depending on platform:

```
exp fetch:android:keystore
exp fetch:ios:certs
```
If you want to provide other files instead, that is also an option when you run `exp build`.

see `exp --help` for more info.

**Comment by lyquocnam** [comment]
thanks @terribleben i found the way by using: `exp build:android -c` it will remove old keystore :)
