### ISSUE TITLE
Using aliases with babel + webpack crashes Android app

### ISSUE THREAD

**Issue by armenavanesi** [expo/expo#12759]
### Summary

I'm using `webpack.config.js` and `babel.config.js` to configure absolute imports in my project. The project works fine on web, but immediately crashes on Android (I'm using a Google Pixel 2 XL). I don't see any errors in the CLI, etc. These are the only changes in my project at the moment. I've linked to a reproducible example, but here are the contents of the two aforementioned files:

webpack.config.js:
```
const createExpoWebpackConfigAsync = require("@expo/webpack-config");
const path = require("path");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Customize the config before returning it.
  config.resolve.alias['components'] = 'components/';
  config.resolve.alias['containers'] = 'containers/';
  config.resolve.alias['theme'] = 'theme.js';
  // Have also tried this:
  // config.resolve = {
  //   alias: {
  //     components: path.resolve(__dirname, "components/"),
  //     containers: path.resolve(__dirname, "containers/"),
  //     theme: path.resolve(__dirname, "theme.js"),
  //   },
  //   extensions: [".js"],
  // };
  return config;
};
```

and babel.config.js:
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      [
        "module-resolver",
        {
          alias: {
            components: "./components",
            containers: "./containers",
            theme: "./theme.js",
          },
          extensions: [".js"],
        },
      ],
    ],
  };
};


```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

```
  Expo CLI 4.3.4 environment info:
    System:
      OS: macOS Mojave 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.68 => 0.12.68
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

https://github.com/armenavanesi/babel-issue

- run `yarn start`
- run on an Android Device

**Comment by brentvatne** [comment]
unrelated to expo, we have no opinion what you do with your babel aliases :)

**Comment by armenavanesi** [comment]
@brentvatne hmm Expo Go crashes on android without logs, in the CLI it only says `Finished building JavaScript bundle in 34812ms.`. How can I get the output?

**Comment by brentvatne** [comment]
looks to actually be unrelated to babel. i ran it on ios and saw this:

![Screen Shot 2021-04-27 at 11 20 36 PM](https://user-images.githubusercontent.com/90494/116355800-3b3e8300-a7af-11eb-9bd5-f632d2b56f4c.png)

react-native android is sadly notoriously bad at crashing on unexpected values, so it's likely what you encountered here. one of the benefits of making an example even more minimal (eg: if you just had a `View` in each file) is that you would have probably encountered this.

**Comment by armenavanesi** [comment]
@brentvatne that's good to know. Thanks so much for taking the time to look into this!
