### ISSUE TITLE
Expo detached app not running from expo android app

### ISSUE THREAD

**Issue by rastogitech** [expo/expo#1277]
I created a react-native project using create-react-native-app command. Then, I detached with expokit. Now, on using **npm start**, project starts on command line and gives a URL too for the project. Previously, it used to be like: exp://SOME_IP:19000. But now it's **exp467b60b606a94ee495f7e7c826b4034e://172.17.10.90:19000**. Now, if I run project using exp://SOME_IP:19000 then it works well but if I use url exp467b60b606a94ee495f7e7c826b4034e://172.17.10.90:19000 then project doesn't work.

Help!

React-native-cli: 2.0.1
React-native: 0.50.3
Npm: 4.2.0
Node: 7.10.1
Expo: "^23.0.4"
React-native fork: "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz"

**Comment by terribleben** [comment]
Hi, seeing something like `exp<uuid>://` is expected in an ExpoKit project. How are you opening the project? Did you follow the [setup guide](https://docs.expo.io/versions/latest/guides/expokit.html#setting-up-your-project)?

**Comment by SpadarShut** [comment]
Maybe you need to add `assetBundlePatterns` to app.json, see blog post
https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51
