### ISSUE TITLE
Video component still playing in background when navigating to another screen

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo#12786]
### Summary

Video imported from expo-av still plays in the background when navigating to a new screen. When the video is no longer in the view, it should stop playing.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

 Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 25, 26
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.0 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Create project with screens, usually with a drawer using react navigation. Then add video to one of the drawer screens. When navigating between drawer screens the video will never stop playing even though it is out of view.

**Comment by byCedric** [comment]
Hi @mikeRChambers610! I think this is related to `react-navigation` and [how it mounts or unmounts screens](https://reactnavigation.org/docs/navigation-lifecycle/). In short, the screen with the video is probably still mounted. That's why the video won't stop playing. You can however add a lifecycle event listener to manually stop the video on that screen. You should be able to use the [`focus` effect for this](https://reactnavigation.org/docs/function-after-focusing-screen/).

Hope this helps!

**Comment by mikeRChambers610** [comment]
I found that if using react-navigation you can use the below and it works fine. Use state of isMountedVideo to show video or not.

componentDidMount = async () => {
          
              this._navListenerFocus = this.props.navigation.addListener('didFocus', () => {
        
                this.setState({
                  isMountedVideo: true
                })
          
              });
            
              this._navListenerBlur = this.props.navigation.addListener('willBlur', () => {
              
                this.setState({
                  isMountedVideo: false
                })
            
              })

 }


componentWillUnmount = () => {
            this._navListenerFocus.remove();
            this._navListenerBlur.remove();x
         }

**Comment by chimiWangchukWangdi** [comment]
> I found that if using react-navigation you can use the below and it works fine. Use state of isMountedVideo to show video or not.
> 
> componentDidMount = async () => {
> 
> ```
>           this._navListenerFocus = this.props.navigation.addListener('didFocus', () => {
>     
>             this.setState({
>               isMountedVideo: true
>             })
>       
>           });
>         
>           this._navListenerBlur = this.props.navigation.addListener('willBlur', () => {
>           
>             this.setState({
>               isMountedVideo: false
>             })
>         
>           })
> ```
> 
> }
> 
> componentWillUnmount = () => { this._navListenerFocus.remove(); this._navListenerBlur.remove();x }

what will be the equivalent code for a functional component ???
