### ISSUE TITLE
[docs] Missing rate limits for store review requests

### ISSUE THREAD

**Issue by byCedric** [expo/expo#12780]
### Summary

We currently don't list the limitations for iOS (and possibly Android). One developer mentioned this in our discord and would have saved the dev some time if this was listed.

The [App Store guidelines](https://developer.apple.com/app-store/ratings-and-reviews) states:
> The SKStoreReviewController API lets you give users an easy way to provide feedback about your app. You can prompt for ratings up to three times in a 365-day period. Users will submit a rating through the standardized prompt, and can write and submit a review without leaving the app.

### Link to the related docs page

https://docs.expo.io/versions/latest/sdk/storereview/#storereviewrequestreview

**Comment by ccheever** [comment]
Still would be good to update these docs
