### ISSUE TITLE
[Android] Errors from native side crash the app

### ISSUE THREAD

**Issue by James2516** [expo/expo#1278]
https://snack.expo.io/S1u-9-ANf
When i try to load it on Samsung S8+, it gives "Expo keeps stopping".

**Comment by tcdavis** [comment]
Thanks James.  I can repro on an S6 as well.
Not immediately obvious what the issue is, but something in the container2 view: https://snack.expo.io/H1QHipyBM

**Comment by James2516** [comment]
The problem seems to be that `left` instead of `flex-start` is supplied to `alignItems`. 
A friendly message similar to the one shown when running on actual local environment should be displayed instead of crashing the app.

**Comment by AdamJNavarro** [comment]
Hey @James2516,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
