### ISSUE TITLE
isRemoteJSEnabled property for Android devices

### ISSUE THREAD

**Issue by jpJuni0r** [expo/expo#1279]
Currently you can disable remote JS in app.js in `expo.ios.isRemoteJSEnabled` as documented [here](https://docs.expo.io/versions/v24.0.0/guides/configuration.html).

I think the property should be moved from `expo.ios.isRemoteJSEnabled` to `expo.isRemoteJSEnabled` so you can disable remote JS on Android aswell.

**Comment by fxfactorial** [comment]
Hi, thank you for the suggestion. We'll keep it in mind next time this API changes.
