### ISSUE TITLE
expo-image-picker: Not correct dimensions for vertical photo (on Android)

### ISSUE THREAD

**Issue by Aryk** [expo/expo#12803]
### Summary

I have 3 phones, 2 android, 1 ios.

This [photo](https://www.dropbox.com/s/5jol2ft7pbeak3u/photo%20breaking.jpg?dl=1) has an Orientation in the exif of 8 (6 and 8 are portrait modes). 

When calling ImagePicker.launchImageLibraryAsync, on iOS, it returns the correct dimensions 2392 x 5184. However, on both Android phones, it returns 5184 x 2392.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.12.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /Users/aryk/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Download [photo](https://www.dropbox.com/s/5jol2ft7pbeak3u/photo%20breaking.jpg?dl=1)  onto Android phone.

Open with launchImageLibraryAsync, observer that result has width and height flipped. It's a portrait photo but the height is less than the width.

**Comment by dlockwo** [comment]
I can reproduce this bug. I tested with a Pixel 3a emulator. The issue does not occur on API level 28 (Android 9), but does occur on API level 29 (10) and 30 (11).

**Comment by mstach60161** [comment]
It seems that this issue doesn't occur on expo sdk 42. I tried to reproduce it on different android API levels. Could you try it on newer SDK and if still occurs, reopen issue with updated sdk version?

**Comment by pwfcurry** [comment]
I'm also having this issue, on Expo sdk 42 :/ 

As a workaround you can apply a no-op transform:

```ts
ImageManipulator.manipulateAsync(uri, [{ rotate: 0 }], { format: SaveFormat.JPEG, base64: true })
```

@Aryk are you able to reproduce with v42?

**Comment by Aryk** [comment]
@pwfcurry I probably won't get on SDK 42 (and I'll likely just skip to 43 when it comes out).
