### ISSUE TITLE
idToken undefined in result.authentication (authSession with Google)

### ISSUE THREAD

**Issue by howardwu1** [expo/expo#12808]
### Summary

When getting a response back from promptAsync using AuthSession with Google, I get an authentication value with an undefined id_token. I know I can get the id_token by itself but I'm looking for both an access token and id_token in the same response because I can't think of an elegant workaround to get both separately using this library (each would have to prompt the user with a popup, and worse you would have to trigger popups by asking the user to click two buttons or disable pop up blocker)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: * => 17.0.2
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: latest => 4.4.4
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Just using the same code as in the docs -- but not doing it on snack (since you can't even enter your credentials there with google sign in). Other people have also seen this bug, see these links: https://stackoverflow.com/questions/66966772/expo-auth-session-providers-google-google-useauthrequest and https://forums.expo.io/t/expo-auth-session-google-useauthrequest-returns-googles-idtoken-value-as-undefined/49510

**Comment by fermmm** [comment]
I lost an entire day searching how to get the idToken (it's returned as undefined), I'm testing on expo go, everything configured correctly, expo go web proxy credentials, evrything. The only solution that worked for me seems to be this code provided by howard:

```
   const [request, response, promptAsync] = Google.useAuthRequest({
      responseType: "id_token",
      androidClientId: process.env.GOOGLE_CLIENT_ID_ANDROID,
      expoClientId: process.env.GOOGLE_CLIENT_WEB_EXPO,
      scopes: ["email"]
   });
```

As the issue specifies this only returns the idToken, it's a problem if you need any other information.

**Comment by jenwit07** [comment]
Yes I got this problem too ,This issue make me stuck for 1 day

**Comment by GiovanniColonni** [comment]
I adopt the same modification to my code but still not working:
```
TypeError: undefined is not an object (evaluating 'authetication.accessToken')

This error is located at:
    in Login
```
I also try to use useIdTokenAuthRequest but without success, any suggestion ? i use Expo Go for testing

**Comment by Rio-Lv** [comment]
> I adopt the same modification to my code but still not working:
> 
> ```
> TypeError: undefined is not an object (evaluating 'authetication.accessToken')
> 
> This error is located at:
>     in Login
> ```
> 
> I also try to use useIdTokenAuthRequest but without success, any suggestion ? i use Expo Go for testing.
> I'm not sure of one thing, the `expoClientId` is the google ClientId of the web application, with the authorized uris and redirect uris, true ?

Hello there.

Try sticking to using `Google.useIdTokenAuthRequest`

In your app.json file try add a `"scheme": `
like so....
```
{
  "expo": {
    "scheme": "some_name"
  }
}
```
If you dont add a scheme. Your stand alone app wont get any data back.

**Comment by ammarfaris** [comment]
I am also encountering this issue (idToken undefined in result.authentication (authSession with Google) ). 

Using managed workflow with expo and expo-auth-session below (the latest ones):

`
"expo": "~43.0.2",
 "expo-auth-session": "~3.4.2",
`

**Comment by giacomoalonzi** [comment]
Incurred in the same issue guys, anyone solved the issue?
```
"expo": "~43.0.4",
"expo-auth-session": "~3.4.2",
```

**Comment by kapilpau** [comment]
Hi,

I am using `useIdTokenAuthRequest` and it works perfectly when using Expo Go, however, when I build an APK (using `eas build`), params.id_token and authentication are both null. I am providing a valid `androidClientId` and `responseType: "id_token"`. If anyone has any ideas how to fix this, I'd really appreciate it.

**Comment by remcorakers** [comment]
Hi @giacomoalonzi and @kapilpau , I encountered the same issue as you described. After some investigation I discovered my implementation wasn't correct. Maybe you have the same.

When running on native iOS/Android then the response type is always `code` (see also [Google.ts#L259](https://github.com/expo/expo/blob/04519adcd775626a670b0ab71b3660748649b3af/packages/expo-auth-session/src/providers/Google.ts#L259)). The `id_token` in the response from the `promptAsync` method will then empty. Instead, you need to use  the `id_token` parameter in the `params` from the `fullResult` variable. See [Google.ts#L342](https://github.com/expo/expo/blob/04519adcd775626a670b0ab71b3660748649b3af/packages/expo-auth-session/src/providers/Google.ts#L342).

Here a short example:
```
const [request, fullResult, promptAsync] =
  Google.useIdTokenAuthRequest({
    expoClientId: googleExpoClientId,
    iosClientId: googleIosStandaloneClientId,
    androidClientId: googleAndroidStandaloneClientId,
    scopes: ['profile', 'email'],
  });

  const result = await promptAsync();
  if (result.type === 'success') {
    const token = result.params.id_token; // Token is empty when running on iOS/Android, but filled on Expo
  }

  if (fullResult?.type === 'success') {
    const token = fullResult.params.id_token; // Token is always filled, when running on iOS/Android and when running in Expo
  }
```

**Comment by kapilpau** [comment]
@remcorakers hero! That has worked, thank you!

**Comment by hitenvats16** [comment]
I used `useAuthRequest()`. Result after fetching had idToken undefined. Then tried using `useIdTokenAuthRequest` but that result had no accessToken. I want to implement google signin feature and for that i'll need both of them. So please help me asap. :(

**Comment by kapilpau** [comment]
@hitenvats16 see @remcorakers reply above

**Comment by hitenvats16** [comment]
> @hitenvats16 see @remcorakers reply above

I tried it but all i got is idToken only dont'know why..

**Comment by launchpadfalmouth** [comment]
any update on this? facing same problem

**Comment by charlestbell** [comment]
Same issue here. Using Google.useAuthRequest and the idToken on the response object is undefind.

**Comment by farrokh** [comment]
same problem

**Comment by abdullahbayram** [comment]
I have the same problem. 
 "expo": "^44.0.0",  
 "expo-auth-session": "~3.5.0"
 The solution of @fermmm provided by @howardwu1 is working to get id_token(I checked on just ios Simulator), thanks. However, I need also other values. 
 Any update?

**Comment by travishoki** [comment]
Same issues as others. I'm trying to upgrade from expo-google-app-auth -> expo-auth-session. I need the accessToken and the idToken but am not receiving both from the Google.useAuthRequest call.

**Comment by jaykeerti** [comment]
This worked for me pretty well
`import { View, Text } from 'react-native'
import React, { createContext, useContext } from 'react'
import * as WebBrowser from 'expo-web-browser';
import * as Google from 'expo-auth-session/providers/google';
import {
    GoogleAuthProvider,
    onAuthStateChanged,
    signInWithCredential,
    signOut
} from 'firebase/auth';
import {auth} from "./firebase";

WebBrowser.maybeCompleteAuthSession();

const AuthContext = createContext({});

const config = {
    androidClientId:'',
    expoClientId:'',
    responseType: "id_token"
};

export const AuthProvider = ({ children }) => {
    const [request, response, promptAsync] = Google.useAuthRequest(config);

    async function signInWithGoogle () {
        promptAsync();
    }

    React.useEffect(() => {
        if (response?.type === 'success') {
        const credential = GoogleAuthProvider.credential(id_token);
        signInWithCredential(auth, credential);
        }
      }, [response]);

    return (
        <AuthContext.Provider value={{user:null,signInWithGoogle}}>
            {children}
        </AuthContext.Provider>

    )
};

export default function useAuth() {
    return useContext(AuthContext);
}`

**Comment by travishoki** [comment]
> This worked for me pretty well
> 
> ```
> import { View, Text } from 'react-native'
> import React, { createContext, useContext } from 'react'
> import * as WebBrowser from 'expo-web-browser';
> import * as Google from 'expo-auth-session/providers/google';
> import {
>     GoogleAuthProvider,
>     onAuthStateChanged,
>     signInWithCredential,
>     signOut
> } from 'firebase/auth';
> import {auth} from "./firebase";
> 
> WebBrowser.maybeCompleteAuthSession();
> 
> const AuthContext = createContext({});
> 
> const config = {
>     androidClientId:'',
>     expoClientId:'',
>     responseType: "id_token"
> };
> 
> export const AuthProvider = ({ children }) => {
>     const [request, response, promptAsync] = Google.useAuthRequest(config);
> 
>     async function signInWithGoogle () {
>         promptAsync();
>     }
> 
>     React.useEffect(() => {
>         if (response?.type === 'success') {
>         const credential = GoogleAuthProvider.credential(id_token);
>         signInWithCredential(auth, credential);
>         }
>       }, [response]);
> 
>     return (
>         <AuthContext.Provider value={{user:null,signInWithGoogle}}>
>             {children}
>         </AuthContext.Provider>
> 
>     )
> };
> 
> export default function useAuth() {
>     return useContext(AuthContext);
> }
> ```

@jaykeerti Thank you providing code. That's helpful to see. Are you not specifying a `redirectUri`? Without the `redirectUri` I get the `400 "redirect_uri_mismatch"` error. Also, do you have a `expo.scheme` in your app.json? I just can't get this to work in the Android Standalone app no matter what I try.

**Comment by JonLec2** [comment]
> mail'],
> });
How I can use the scope's data?

**Comment by abbottdev** [comment]
Using the above workaround gets under the web client only returns an id_token from what I can tell, not both an id_token and the refresh token. We need this because the JWT you get back you can't use as a refresh token, which means you'd need to call promptAsync() again, whereas it's a much simpler implementation for me to call the "refreshAsync" method to refresh the token.

**Comment by Saifr72000** [comment]
> 

This is only working partially. Again, the issue here is as multiple people experience in the thread, it only returns one of two. Either you get the id_token or you get the accessToken in the response. Dependent upon if your config file is set to responseType = id_token

How can we get both the id_token and the accessToken in the same response?

**Comment by Saifr72000** [comment]
Actually it is not working at all for me. I tried multiple different approaches but something is not quite working with the GoogleAuthProvider.credential() function. It gives the following error: undefined is not an object (evaluating '_auth.GoogleAuthProvider.credential')

<img width="404" alt="Screenshot 2022-12-04 at 17 47 25" src="https://user-images.githubusercontent.com/104276118/205504054-9f32d13e-b3f6-44e8-8b82-03ecc7f5e070.png">

What can I do to fix that?

**Comment by Vincent-liuwingsang** [comment]
Thanks to [browniefed](https://github.com/browniefed) on this [PR](https://github.com/expo/expo/pull/18765)

I managed to get both id_token and access_token by adding the following to useAuthRequest config 
`
     responseType: "id_token token",
     extraParams: {
        nonce: await generateHexStringAsync(16),
     },
     usePKCE: false,
`

**Comment by Saifr72000** [comment]
> 

Hi Vincent, I tried your suggestion but it is giving me the following error in the terminal:

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError

How are you passing the code you suggested to the function? Asking because I see you are using await in front of the generateHexStringAsync(16), await is not allowed unless you are not within async function or?..

Here is my code btw (without the API keys):
import { View, Text, Button, Image } from "react-native";
import React, { useEffect, useState } from "react";
import useAuth from "../hooks/useAuth";
import * as Google from "expo-auth-session/providers/google";
import WebBrowser from "expo-web-browser";
import * as firebase from "firebase/compat";

import {
  GoogleAuthProvider,
  onAuthStateChanged,
  signInWithCredential,
  signOut,
} from "firebase/compat/auth";
import { auth } from "firebase/compat";
import { generateHexStringAsync } from "expo-auth-session";

const config = {
  androidClientId:
    "",
  iosClientId:
    "",
  expoClientId:
    "",
  responseType: "id_token token",
  extraParams: {
    nonce:  await generateHexStringAsync(16),
 },
 usePKCE: false,
  
};
const LoginScreen = () => {
  const [request, response, promptAsync] = Google.useAuthRequest(config);

  async function signInWithGoogle() {
    promptAsync();
  }


  useEffect(() => {
    if (response?.type === 'success') {
      console.log(response);
    /* const credential = GoogleAuthProvider.credential(id_token);
    signInWithCredential(firebase.auth, credential); */
    }
  }, [response]);

  return (
    <View>
      <Button title="login" onPress={signInWithGoogle} />
    </View>
  );
};

export default LoginScreen;

**Comment by Saifr72000** [comment]
I also tried this approach where I pass the extra params within the async function so the await is used correctly for generateHexStringAsync function.

`import { View, Text, Button, Image } from "react-native";
import React, { useEffect, useState } from "react";
import useAuth from "../hooks/useAuth";
import * as Google from "expo-auth-session/providers/google";
import WebBrowser from "expo-web-browser";
import * as firebase from "firebase/compat";

import {
  GoogleAuthProvider,
  onAuthStateChanged,
  signInWithCredential,
  signOut,
} from "firebase/compat/auth";
import { auth } from "firebase/compat";
import { generateHexStringAsync } from "expo-auth-session";

const config = {
  androidClientId:
    "",
  iosClientId:
    "",
  expoClientId:
    "",
  responseType: "id_token token",
  usePKCE: false,
  
};
const LoginScreen = () => {
  const [request, response, promptAsync] = Google.useAuthRequest(config);

  /* async function signInWithGoogle() {
    promptAsync();
  } */

  async function signInWithGoogle() {
    const nonce = await generateHexStringAsync(16);
    promptAsync({ extraParams: { nonce } });
  }

  useEffect(() => {
    if (response?.type === 'success') {
      console.log(response);
    /* const credential = GoogleAuthProvider.credential(id_token);
    signInWithCredential(firebase.auth, credential); */
    }
  }, [response]);

  return (
    <View>
      <Button title="login" onPress={signInWithGoogle} />
    </View>
  );
};

export default LoginScreen;
`

However, this code as well gives me error. It gives me the following error from Google:
"Authorisation error. Error code: 400: invalid_request. Paramater not allowed for this message type: code_challenge_method"

I've tried to set the usePKCE: true, but that doesent help either. Am I doing something incorrect or is there any errors in the packages? 
Appreciate all the help!

**Comment by 1level1** [comment]
Same issue, no access_token or id_token when using native android. 
Based on the OAuth 2.0 protocol, I can exchange the code for access tokens using the token endpoint https://oauth2.googleapis.com/token. This is done by default for web, but for some reason not working for native android.

How can I manually exchange code for access_token using expo-auth-session?
Thanks

**Comment by harismh** [comment]
For me, what worked on Native Android was using the standard "useAuthRequest" from expo-auth-session and doing a web-style auth code flow on Android. This requires you to set up [deep linking on Android](https://docs.expo.dev/guides/deep-linking/#deep-links-on-android) so that Expo can capture the HTTPS redirect. Bonus, doing all of this work automatically gives you a working auth for web, and with some client id switching, on native iOS too. Haven't figured out how to get Expo Go running as like others useProxy gave me auth errors. Below is some code:

```js
import React from "react";
import { Platform, View } from "react-native";
import * as WebBrowser from "expo-web-browser";
import Constants from "expo-constants";
import {
  useAuthRequest as useHttpsAuthRequest,
  useAutoDiscovery,
  makeRedirectUri
} from "expo-auth-session";
import { useIdTokenAuthRequest } from "expo-auth-session/providers/google";
import { GoogleRectangularButton } from "../../../common/GoogleButton";

// auth window won't close without this line
// https://docs.expo.io/guides/authentication/
WebBrowser.maybeCompleteAuthSession();

export default function GoogleLogin({
  config: googleConfig,
  onSuccess,
  onError,
  submitLabel,
  initialEmail
}) {
  const { clientId, clientSecret } = Platform.select({
    ios: { clientId: googleConfig.iosClientId, clientSecret: "" }, // to exchange the auth code on iOS, we'll pass in an empty string as the client secret
    default: {
      clientId: googleConfig.clientId,
      clientSecret: googleConfig.clientSecret
    }
  });

  const isIos = Platform.OS === "ios";
  const discovery = useAutoDiscovery(`https://accounts.google.com`);
  const redirectUri = isIos
    ? makeRedirectUri({
        scheme: Constants.manifest.scheme,
        path: "/--/oauth-redirect"
      })
    : "https://example.app/--/oauth-redirect"; // web will use this (and android too if deep linking is set up)

  const useAuthRequest = isIos ? useIdTokenAuthRequest : useHttpsAuthRequest;
  const [authRequest, , promptAsync] = useAuthRequest(
    {
      redirectUri,
      scopes: ["openid", "profile", "email"],
      ...(isIos ? { iosClientId: clientId } : { clientId }),
      ...(initialEmail ? { extraParams: { login_hint: initialEmail } } : {})
    },
    isIos ? undefined : discovery // useIdTokenAuthRequest doesn't accept discovery like useHttpsAuthRequest does
  );

  const onPress = async () => {
    const authResp = await promptAsync();

    if (authResp.type === "success") {
      const authCode = authResp.params.code;
      const params = {
        client_id: clientId,
        client_secret: clientSecret,
        code_verifier: authRequest.codeVerifier,
        code: authCode,
        grant_type: "authorization_code",
        redirect_uri: redirectUri
      };
      const body = Object.entries(params)
        .map(([key, value]) => `${key}=${encodeURIComponent(value)}`)
        .join("&");

      return fetch(discovery.tokenEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
          Origin: null
        },
        body
      })
        .then(resp => resp.json())
        .then(respJson => console.log(respJson))
        .catch(err => console.error(err));
    }
  };
}
```

**Comment by cothientai** [comment]
> Same issue, no access_token or id_token when using native android. Based on the OAuth 2.0 protocol, I can exchange the code for access tokens using the token endpoint https://oauth2.googleapis.com/token(https://developers.google.com/identity/protocols/oauth2/native-app#exchange-authorization-code). This is done by default for web, but for some reason not working for native android.
> 
> How can I manually exchange code for access_token using expo-auth-session? Thanks

How I did it was by using shouldAutoExchangeCode see my comment at: [https://github.com/expo/expo/issues/18270#issuecomment-1483945639](url)

``` typescript
import Constants, { ExecutionEnvironment } from "expo-constants";

const [request, response, promptAsync] = Google.useIdTokenAuthRequest({
    expoClientId: GOOGLE_PROXY_ID,
    iosClientId: GOOGLE_IOS_ID,
    androidClientId: GOOGLE_ANDROID_ID,
    // ADD THIS TO FORCE THE AUTO EXCHANGE CODE TO GET THE ACCESS TOKEN ONLY WHEN NOT USING THE EXPO GO APP
    shouldAutoExchangeCode:
      Constants.executionEnvironment !== ExecutionEnvironment.StoreClient
        ? true
        : undefined,
  });

useEffect(() => {
    if (response?.type === "success") {
      const { id_token } = response.params;
      console.log(response);
    }
  }, [response]);
```

**Comment by farid-itpath** [comment]
got **id_token** using _Google.useIdTokenAuthRequest_ instead of _Google.useAuthRequest_.
it will not be inside _response.authentication_. find it inside _response.params_
