### ISSUE TITLE
Project stuck at splash screen when opening it from url after expo publish

### ISSUE THREAD

**Issue by KatancicDenisz** [expo/expo#12814]
### Summary

Expected behavior: the project should continue from splash screen to the main screen.  

Problem: I used `expo publish` to publish my project.  At the expo website I sent the project link to my email. When I try to open the project from the email it freezes at the splash screen. If I drag the dropdown menu and click on the expo's refresh button, the project loads correctly. 
If I open the Expo Go app before clicking on the project link, the project loads.
If I scan the QR code  with Expo Go app, the project loads.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0.1

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
import React from "react";
import { Text } from "react-native";

export default function App() {
  return <Text>Hello world</Text>;
}
```

package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@apollo/client": "^3.3.7",
    "@expo-google-fonts/alata": "^0.1.0",
    "@expo-google-fonts/inter": "^0.1.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "5.9.7",
    "@react-native-picker/picker": "1.9.2",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "@turf/turf": "^6.3.0",
    "decode-google-map-polyline": "^1.0.1",
    "expo": "~40.0.0",
    "expo-av": "~8.7.0",
    "expo-font": "~8.4.0",
    "expo-intent-launcher": "~8.4.0",
    "expo-linear-gradient": "~8.4.0",
    "expo-location": "~10.0.0",
    "expo-status-bar": "~1.0.3",
    "geolib": "^3.3.1",
    "graphql": "^15.5.0",
    "lottie-react-native": "~2.6.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-elements": "^3.1.0",
    "react-native-fast-image": "^8.3.4",
    "react-native-geolocation-service": "^5.2.0",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-maps": "^0.27.1",
    "react-native-maps-directions": "^1.8.0",
    "react-native-modal": "^11.7.0",
    "react-native-ratings": "^7.4.0",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.2",
    "react-native-scroll-bottom-sheet": "^0.7.0",
    "react-native-swiper": "^1.6.0",
    "react-native-web": "~0.13.12",
    "rn-sliding-up-panel": "^2.4.5",
    "spherical-geometry-js": "^2.0.0"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "react-native-dotenv": "^2.5.1"
  },
  "private": true
}

```

**Comment by brentvatne** [comment]
https://docs.expo.io/workflow/development-mode/
https://docs.expo.io/workflow/debugging/#production-errors
