### ISSUE TITLE
Expo-Notifications Installation Error

### ISSUE THREAD

**Issue by Vijay1126** [expo/expo#12816]
### Summary

I am trying to install expo-notifications and it is failing because the following (react-native-amcharts) is not found. How can I work around this?

Not found: "https://registry.yarnpkg.com/react-native-amcharts/-/react-native-amcharts-0.0.2-g.tgz"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

expo@38.0.11

### Environment

Expo CLI 4.0.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
      Yarn: 1.22.5 - ~/.nvm/versions/node/v14.8.0/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.11 => 38.0.11 
      react: ^16.13.1 => 16.14.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 4.0.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
expo install expo-notifications
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (4.4.3).                 │
│   You are currently using expo-cli 4.0.4                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
Installing 1 SDK 38.0.0 compatible native module using Yarn.
> yarn add expo-notifications@~0.3.3
yarn add v1.22.5
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/Users/vijayraja/Documents/GitHub/firebeats-react-native-copy/yarn-error.log".
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-amcharts/-/react-native-amcharts-0.0.2-g.tgz: Request failed \"404 Not Found\"".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarnpkg exited with non-zero code: 1
Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/vijayraja/.nvm/versions/node/v14.8.0/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
    ...
    at Object.spawnAsync [as default] (/Users/vijayraja/.nvm/versions/node/v14.8.0/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at YarnPackageManager._runAsync (/Users/vijayraja/.nvm/versions/node/v14.8.0/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:288:31)
    at YarnPackageManager.addAsync (/Users/vijayraja/.nvm/versions/node/v14.8.0/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:241:16)
    at installAsync (/Users/vijayraja/.nvm/versions/node/v14.8.0/lib/node_modules/expo-cli/src/commands/install.ts:129:3)
    at Command.<anonymous> (/Users/vijayraja/.nvm/versions/node/v14.8.0/lib/node_modules/expo-cli/src/exp.ts:346:7)
```

**Comment by brentvatne** [comment]
you have something called `react-native-amcharts` version 0.0.2 in your project. it seems to not exist on the registry, maybe it was removed or there is an intermittent issue. this is totally unrelated to expo. run `yarn` in your project and you will have the same result

**Comment by brentvatne** [comment]
also, please update your expo-cli version when you are prompted to do so, we regularly make improvements

**Comment by Vijay1126** [comment]
You were right, thank you so much!
Do you mind telling me how you knew it was completely unrelated to expo-notifications?
And yes, I will update!

**Comment by brentvatne** [comment]
because the error message told me 😅 

> error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-amcharts/-/react-native-amcharts-0.0.2-g.tgz: Request failed \"404 Not Found\"".
