### ISSUE TITLE
[android] Device country does not represent the actual location of the device

### ISSUE THREAD

**Issue by smithaitufe** [expo/expo#1281]
```js
const [deviceCountry, currentTimeZone] = await Promise.all([      
      Expo.Util.getCurrentDeviceCountryAsync(),
      Expo.Util.getCurrentTimeZoneAsync(),
    ]);
    console.log(deviceCountry, currentTimeZone)
```
returns US Africa/Lagos. While the time zone is correct, the country is not. It returns US instead of Nigeria. What could be responsible?

```js
var url = 'https://freegeoip.net/json/';
    fetch(url)
      .then((response) => response.json())
      .then((responseJson) => {
        //console.log(responseJson);
        result = {
          countryName: responseJson.country_name,
          regionName: responseJson.region_name
        }

        console.log(result)
      })
      .catch((error) => {
        //console.error(error);
      });
```
returns
```js
Object {
"countryName": "Nigeria",
"regionName": "Lagos",
}
```

**Comment by fxfactorial** [comment]
For the country side, at least on iOS, it calls: 

```objc
  NSString *countryCode = [[NSLocale currentLocale] objectForKey:NSLocaleCountryCode];
```
And apple docs seem to imply that that is what is used for you as system locale. 

What did you test this on?

**Comment by smithaitufe** [comment]
@fxfactorial I am using android.

**Comment by terribleben** [comment]
@jesseruder is this expected on Android? how do we determine device country?

**Comment by jesseruder** [comment]
We're doing
```
    Locale current = getReactApplicationContext().getResources().getConfiguration().locale;
    String country = current.getCountry();
```
on Android. This is the same thing that react-native-device-info does: https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L76

I think this is just how the Android OS behaves. Going to close this for now. Thanks for bringing this up @smithaitufe. I can reopen if it turns out we're doing something wrong.

**Comment by adirzoari** [comment]
same issue.. any solution?? @jesseruder  @smithaitufe
