### ISSUE TITLE
[expo-av][android] app crashes when unmounting audio component

### ISSUE THREAD

**Issue by mtroskot** [expo/expo#12822]
### Summary

In my app I have an audio player, which is loading onMount multiple audio files and  on unMount it is unloading them.
App crashes sometimes on unmount.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 21, 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.64.0 => 0.64.0 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Not sure how to reproduce it, it only happens during componentWillUnmount.
During unmount I'm calling.

```
  cleanBuffer = async () => {
    try {
      await this.pauseAsyncSound();
      for await (const key of Object.keys(this.audioBufferTracks)) {
        if (this.checkIfExistsAndIsCreated(key)) {
          const sound = this.audioBufferTracks[key] as Audio.Sound;
          await sound.unloadAsync();
        }
        delete this.audioBufferTracks[key];
      }
    } catch (error) {
      console.log('cleanBuffer error', error);
    }
  };

```
And after that 
`await Audio.setIsEnabledAsync(false);`

 I'm using expo-av 9.1.1.
Here are the crashlytics logs.

Caused by java.util.ConcurrentModificationException
expo.modules.av.AVManager.onHostDestroy

java.util.HashMap$HashIterator.nextNode (HashMap.java:1453)
java.util.HashMap$ValueIterator.next (HashMap.java:1482)
expo.modules.av.AVManager.onHostDestroy (AVManager.java:30)
org.unimodules.adapters.react.services.UIManagerModuleWrapper$3.onHostDestroy (UIManagerModuleWrapper.java:10)
com.facebook.react.bridge.ReactContext.onHostDestroy (ReactContext.java:25)
com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState (ReactInstanceManager.java:26)
com.facebook.react.ReactInstanceManager.onHostDestroy (ReactInstanceManager.java:13)
com.facebook.react.ReactInstanceManager.onHostDestroy (ReactInstanceManager.java:4)
com.facebook.react.ReactDelegate.onHostDestroy (ReactDelegate.java:30)
com.facebook.react.ReactActivityDelegate.onDestroy (ReactActivityDelegate.java:2)
com.facebook.react.ReactActivity.onDestroy (ReactActivity.java:5)
android.app.Activity.performDestroy (Activity.java:8350)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1348)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5552)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5597)
android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:190)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:105)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2386)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:213)
android.app.ActivityThread.main (ActivityThread.java:8178)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1101)

**Comment by nguyen-vo** [comment]
Have you found a way to fix this issue. I just got the same crash report today

**Comment by Sziduska** [comment]
I also got the same crash report today. Did you succeeded to fix this issue?

**Comment by nguyen-vo** [comment]
Not really the only thing I found is this issue

**Comment by kennythompson** [comment]
I am also seeing this issue with a very similar stack trace.

**Comment by akashbudhia** [comment]
I have a bad threshold crash rate - 2.5 %. 95% if cashes are due to this issue and is negatively affecting the ranking of the app.

@brentvatne @cruzach  possible to have someone take a quick look? It’s difficult to come up with repro steps else would have created a snack. Anyone else in the thread facing the same problem can create a snack to reproduce the problem?

**Comment by sikgeit** [comment]
Any news on this , we have also an issue with this.

**Comment by brentvatne** [comment]
this issue needs a reproducible example :) @akashbudhia @sikgeit if you can share one it would be appreciated. https://stackoverflow.com/help/minimal-reproducible-example
