### ISSUE TITLE
Share crash on selecting other option.

### ISSUE THREAD

**Issue by abdelouali** [expo/expo#12829]
### Summary

I try to share a Image with the following code:
`Sharing.shareAsync('file://' + uriFile, {
    mimeType: 'image/png',     
    dialogTitle: 'Title of Image', 
    UTI: 'image/png' `

When I click on a share option, say for example "Snapchat". Everything works and the image can be shared on Snapchat. But when I choose to close the share in snapchat before sharing for selecting another option for example whatsapp. It says. This can't be shared. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40.0.1

### Environment

Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- expo init my-app
- expo install expo-sharing
- expo start

**Comment by brentvatne** [comment]
please provide a reproducible example. https://stackoverflow.com/help/minimal-reproducible-example
