### ISSUE TITLE
The development server returned response error code: 500

### ISSUE THREAD

**Issue by pankaja92** [expo/expo#1282]
Followed [this](https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51) post and updated the sdk to 24.0.0 as I needed expo to support react-native 0.51.0 . Issue [1280](https://github.com/expo/expo/issues/1280)

Now when I run `npm start` everything works fine and when I try to run the app on my moblie using `npm start` I get this error on console

```
05:31:06: Finished building JavaScript bundle in 4387ms
05:31:07: Failed building JavaScript bundle
```

And this on my mobile phone.
```
The development server returned response error code: 500

URL: http://192.168.1.3:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=/home/pankaja/Documents/Projects/react-native/placeMe/node_modules/expo/tools/hashAssetFiles

Body:
{"type":"InternalError","errors":[],"message":"Metro Bundler has encountered an internal error, please check your terminal error output for more details"}
processBundleResult
    BundleDownloader.java:223
access$100
    BundleDownloader.java:41
execute
    BundleDownloader.java:157
emitChunk
    MultipartStreamReader.java:69
readAllParts
    MultipartStreamReader.java:116
onResponse
    BundleDownloader.java:145
c
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:761

```

**Comment by terribleben** [comment]
Thanks for the report. We've had [another report](https://github.com/expo/expo/issues/1282) of the same thing, so I am going to consolidate this into that issue. Unfortunately we don't have a solution for you yet.

**Comment by pankaja92** [comment]
@terribleben So, is this mean that I can't use latest react native version to build an app ? :(

**Comment by rimer10** [comment]
iam facing same problem

**Comment by Jedashford** [comment]
Same here. Created a new project, run-android, get this in the emulator.

The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"type":"InternalError","errors":[],"message":"Metro Bundler has encountered an internal error, please check your terminal error output for more details"}
processBundleResult
    BundleDownloader.java:231
access$100
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:204
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764

**Comment by rimer10** [comment]
iam facing same problem

**Comment by allanesquina** [comment]
I had the same issue here, so what solved my problem was running `npm start` first and then in another terminal tab run `react-native run-android`

**Comment by entropycritical** [comment]
I have the same problem. I started building 2nd project in sdk 26 but it shows the same error in the 2nd project also. it shows the development server returned response error code: 500 without running single code of my project.

**Comment by unpokolokko** [comment]
i am using react-native version 0.55.4 and encounter this problem.

i then downgrade babel-preset-react-native to version 1.9.2 and run yarn referring to this https://github.com/facebook/react-native/issues/15534 

seemed to solve the problem.

**Comment by Johncy1997** [comment]
I have created one app using `react-native init appname`

Then i tried to insert react-native-image-picker in my login form for uploading profile picture for the user.

![whatsapp image 2018-06-15 at 11 27 46 am](https://user-images.githubusercontent.com/25324938/41452372-42c1e766-708f-11e8-96ce-323eaa1eb03f.jpeg)
While running my app `react-native run-android` it throws this error to me..I am facing this last 3days.I dont understand what should i do..Please someone tell me the exact solution to solve this problem.

**Comment by farkhandazeb** [comment]
i have same problem plz guide me anyone and my another question is that every problem of solution will be solve by cmd ??? plz guide me i m the beginner so i have no more idea about react native

**Comment by milkers** [comment]
@farkhandazeb check [here.](https://github.com/facebook/react-native/issues/14209) Basically there is an issue about rn 0.56 and if you downgrade as mentioned in the link your problem should be resolved. Also I suspect the issue only appears on Windows users who sticks with `npm` instead of `yarn` .

**Comment by jonasmodie** [comment]
@milkers am using ubuntu 16.04 LTS and am having the same problem ,i am using npm and watchman , somedays it works on the emulator and does not work on the physical mobile device , someday its vice versa or not working at all , how do i solve or troubleshoot it

**Comment by ravichandrasv** [comment]
Downgrade the following:

react-native init AwesomeProject
cd AwesomeProject
react-native run-android
npm uninstall react-native
npm install --save react-native@0.55.4
react-native run-android
npm install --save babel-core@latest babel-loader@latest
npm uninstall --save babel-preset-react-native
npm install --save babel-preset-react-native@4.0.0
react-native run-android

**Comment by ravichandrasv** [comment]
Downgrade the following:
react-native init Project
cd Project
npm uninstall react-native
npm install --save react-native@0.55.4
npm uninstall --save babel-preset-react-native
npm install --save babel-preset-react-native@4.0.0
react-native run-android

**Comment by chatcha** [comment]
I have same problem.
Someone can help me?
please

**Comment by zaBogdan** [comment]
Same issue... someone?

**Comment by krookten14** [comment]
Same problem with @Ivaniltonbezerra , is there someone who can help?

**Comment by mahendramahi** [comment]
delete node_modules folder  from project
and open package.json change react-native version "react-native": "0.55.2", and
  babel "babel-preset-react-native": "4", after that run yarn install or
npm install and run.

**Comment by BeckhamVinoth** [comment]
@Ivaniltonbezerra  , i fixed this problem using degrading my react-native version . It worked for me ,
my react-native version is :  native -v
react-native-cli: 2.0.1
react-native: 0.56.0 ,
so i uninstalled them (npm uninstall -g react-native-cli) and and installed specific versions (react-native: 0.55.4 and react-native-cli: 1.2.0)

**Comment by hpatel123** [comment]
I have same issue, finding since 2 days.

**Comment by hapablap21** [comment]
@terribleben the "another report" link just links to this issue, and this issue is closed.  Is there another issue I can follow?

**Comment by sebastianoscarlopez** [comment]
> delete node_modules folder from project
> and open package.json change react-native version "react-native": "0.55.2", and
> babel "babel-preset-react-native": "4", after that run yarn install or
> npm install and run.

Thanks!!! This worked for me

**Comment by rajalingam771** [comment]
delete node_modules folder from project
and open package.json change react-native version "react-native": "0.55.2", and
babel "babel-preset-react-native": "4", after that run yarn install or
npm install and run.  

it works for me also

**Comment by Warmachine13** [comment]
Hey guys I am having the same problem but when I close the node and type npm start in prompt my code run anyone know to solve this problem ?

**Comment by gabrielss97** [comment]
> ![error 500](https://user-images.githubusercontent.com/22125059/44312799-373dee80-a3d4-11e8-8367-9cf44e851739.PNG)
> Estou com esse problema e nao consegui resolver ainda :(

Tentou em vez de react-native start dar npm start? comigo deu certo e funcionando usando apenas o npm start dentro da pasta do projeto.
