### ISSUE TITLE
expo-sharing isAvailableAsync returns true on chrome 90.0.4430.93 even though it's not available

### ISSUE THREAD

**Issue by nice-shot** [expo/expo#12823]
### Summary

When using expo-sharing on chrome 90.0.4430.93 the isAbailableAsync check returns true even though the navigator.share functionality doesn't work and raises an error.
Looking at the ExpoSharing.web.ts code, it looks like chrome recently added the navigator.canShare api which should be used together with checking navigator.share exists.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

4.4.3

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Follow the sharing tutorial in https://docs.expo.io/tutorial/sharing/
Instead of showing an alert message when running on chrome, an exception screen appears:

Unhandled Rejection (TypeError): Failed to execute 'share' on 'Navigator': Invalid URL

**Comment by byCedric** [comment]
Hi @nice-shot, could you check the type of `navigator.share` on that chrome version? We might be able to make it a bit more strict on an existing method.

Unfortunately, `canShare` isn't part of the spec. That means that we shouldn't be using it, only when they add it to the spec we can assume that it works everywhere.

![Screenshot 2021-05-05 at 18 51 14](https://user-images.githubusercontent.com/1203991/117179142-1eb7d180-add3-11eb-9363-72016f9bb3cf.png)

**Comment by nice-shot** [comment]
navigator.share is a function type and it seems to work on my machine (opens a Windows share menu). The problem is that it raises an error when given a data url.
When I run the naviagtor.canShare method it returns false and when I look at the MDN docs for the navigator.share API they do recommend using the canShare method to test for file sharing:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by KonradLinkowski** [comment]
The problem is not with `isAvailableAsync`, but with `shareAsync` which tries to share base64. 
It should probably convert it to a blob first  as suggested here: https://stackoverflow.com/a/63948598/5089567

**Comment by KonradLinkowski** [comment]
Bump :)

**Comment by m33ts4k0z** [comment]
Hello, this is still an issue on Chrome 94.0.4606.71 and the docs are not updated with an explanation.

**Comment by masseyB** [comment]
bump
