### ISSUE TITLE
How to custom permission message with expo ?

### ISSUE THREAD

**Issue by lyquocnam** [expo/expo#1283]
Dear author,
Currently i use location permission, and apply said: 
`please specify the intended purpose of using the user's location in the location permission modal alert.`
So how can i do that with expo ?

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/guides/app-stores.html#system-permissions-dialogs-on-ios

**Comment by lyquocnam** [comment]
I add some config in `ios.infoPlist`:
```
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "We need to know your current location to find the near places. Do you allow us to use location service on this device ?"
      }
```
but when openning the app, the message still default.
![simulator screen shot - iphone 6 - 2018-01-19 at 09 50 36](https://user-images.githubusercontent.com/8347826/35132530-4c462f90-fcfe-11e7-834c-e8b3236204ea.png)

Have anyway to change this ?

**Comment by brentvatne** [comment]
<img width="1064" alt="screen shot 2018-01-18 at 6 56 22 pm" src="https://user-images.githubusercontent.com/90494/35132694-501144ac-fc81-11e7-99bd-1aa444eba811.png">

**Comment by dlcardozo** [comment]
The provided link by @brentvatne seems to not be working anymore, here is the new link:

https://docs.expo.io/versions/latest/distribution/app-stores/#system-permissions-dialogs-on-ios

**Comment by rjsajnani1** [comment]
Hi, 
How to i edit my alert so that i can replace "Expo" with my app name

here is my app.json


`
{
  "expo": {
    "name": "demo",
    "slug": "demo",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "facebookDisplayName": "demo",

    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.demo",
      "CFBundleDisplayName": "demo",
     "infoPlist": {
      "CFBundleDisplayName": "demo",
       
      },
      "config":{
        "googleSignIn":{
         
        }
      }
    }
  }
}
`


<img width="256" alt="Screenshot 2019-04-30 at 10 23 15 PM" src="https://user-images.githubusercontent.com/31607484/56969011-d687c800-6b96-11e9-9799-66937f035589.png">

**Comment by kuriel-trivu** [comment]
how to implement this using internationalization?

**Comment by electerious** [comment]
@kuriel-trivu https://docs.expo.io/versions/latest/distribution/app-stores/#localizing-system-dialogs-on-ios
