### ISSUE TITLE
SDK 41 Android notifications don't work in Snack

### ISSUE THREAD

**Issue by AndreyBaryshev** [expo/expo#12833]
### Summary

Snack example from 
https://docs.expo.io/versions/latest/sdk/notifications/#api 
don't work with notifications from expo API (sendPushNotification function in example or Push notifications tool) but works with scheduleNotificationAsync.

Device: Redmi Note 8 Pro

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo snack

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@andreybaryshev/push-notifications

**Comment by cruzach** [comment]
We need more details than "they don't work" to help effectively. To investigate, use your terminal to send push notifications and share the push ticket and receipt https://docs.expo.io/push-notifications/sending-notifications/#http2-api

**Comment by AndreyBaryshev** [comment]
@cruzach Hi! Thanks for your reply!
```
(1) Redmi Note 8 Pro: sendPushNotification body {"to":"ExponentPushToken[X68wntFOD9iMOI0bGo-x6Y]","sound":"default","title":"Original Title","body":"And here is the body!","data":{"someData":"goes here"},"channelId":"default"}
(2) Redmi Note 8 Pro: push tickets {"data":{"id":"f09d21e5-cc6f-42d1-adc1-6c90d15cccdf","status":"ok"}}
(3) Redmi Note 8 Pro: getReceipt postData {"ids":["f09d21e5-cc6f-42d1-adc1-6c90d15cccdf"]}
(4) Redmi Note 8 Pro: Receipt {"data":{"f09d21e5-cc6f-42d1-adc1-6c90d15cccdf":{"status":"ok"}}}
```

1 - post request to 'https://exp.host/--/api/v2/push/send' with body.
2 - response of request (1) contains push ticket id
3 - post request to 'https://exp.host/--/api/v2/push/getReceipts' with body.
4 - response of request (3) 

Problem is that when I use SDK41 - notification popup on phone doesn't appear.
With SDK40 the same code example works well.

P.S. I run tests here [https://snack.expo.io/@andreybaryshev/push-notifications](https://snack.expo.io/@andreybaryshev/push-notifications)

**Comment by cruzach** [comment]
I see, I'm able to reproduce this in Snack as well. Can you try testing the same code in a local project? That's working for me

**Comment by tgxn** [comment]
I can confirm the notification is never displayed though receipt indicated success.
![image](https://user-images.githubusercontent.com/293107/120894455-01cd2300-c64b-11eb-956c-f37bd53e6c02.png)
