### ISSUE TITLE
[expo-av][android] wrong video width

### ISSUE THREAD

**Issue by mtroskot** [expo/expo#12839]
### Summary

SimpleExoPlayerData _onVideoSizeChanged_ returns wrong width. Width is same as video height, thus when using resize mode cover, video is deformed.
On ios no issues.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 3.28.5 environment info:
System:
OS: macOS 10.15.7
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 14.16.1 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 6.14.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.10.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
Android SDK:
API Levels: 21, 26, 28, 29, 30
Build Tools: 28.0.3, 29.0.2, 30.0.2
System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 4.1 AI-201.8743.12.41.7042882
Xcode: 12.4/12D4e - /usr/bin/xcodebuild
npmPackages:
react: 17.0.2 => 17.0.2
react-native: 0.64.0 => 0.64.0
npmGlobalPackages:
expo-cli: 3.28.5
Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@trokiize/android-video-size-wrong

Run app on ios and android device. On android the video is deformed, on ios looks fine.

**Comment by mtroskot** [comment]
@jvgeee I created a PR with a fix for it https://github.com/expo/expo/pull/15579

**Comment by TheRealMikeD** [comment]
This still seems to be broken as of October 30, 2023.
