### ISSUE TITLE
App directory files location?

### ISSUE THREAD

**Issue by lincdh** [expo/expo#12834]
### Summary

I am trying to transfer files from my pc to the react native app directory which should be in _**My PC\Redmi Note 8 Pro\Internal shared storage\Android\data**_(USB plugged to phone) but there is no directory like **_com.my_react_native_app_** exsiting.

Other installed apps on my phone like Facebook, Google have those directories:

![image](https://user-images.githubusercontent.com/21136244/117245540-3c357b80-ae65-11eb-90cb-65c08afb122e.png)

When I try FileSystem.documentDirectory, it shows emulated/0/... folder which i'm not able to access through usb pc file transfer.

What should I do for the app to automatically created the app directory in real device or emulator and it's visible for user to transfer file?

Any help is really appreciated! Thanks!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

System:
OS: Windows 10 10.0.19041
Binaries:
Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
npmPackages:
"expo-file-system": "^11.0.2",
"expo-local-authentication": "^11.0.2",
"react": "17.0.1",
"react-native": "0.64.0",
Devices:
Xiaomi Note 8 Pro

### Reproducible demo or steps to reproduce from a blank project

I created a bare react native app and use expo file system

Run the app on my Xiaomi Note 8 Pro

Plug your my phone to PC through USB

Observe there is no com.my_react_native_app directory existed in the phone storage.

**Comment by byCedric** [comment]
The [`FileSystem.documentDirectory`](https://github.com/expo/expo/blob/501f28d945f2fe90b0c8ab49aef46477728402ee/android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java#L74) is a path provided by [Android's context `getFilesDir`](https://developer.android.com/reference/android/content/Context#getFilesDir()). It's assigned by the OS and symlinked through `/emulated`. Here is a [reddit thread](https://www.reddit.com/r/AndroidQuestions/comments/7nuza6/how_to_access_files_in_storageemulated0/) describing how you can access that through MTP/USB file sharing.

**Comment by wahidshadab** [comment]
@hayr-hotoca I am facing the same issue, have you found any solutions?
