### ISSUE TITLE
Error build for react-native-unimodules@0.13.0 and above when using use_frameworks! in Podfile

### ISSUE THREAD

**Issue by budiTjendra** [expo/expo#12840]
### Summary

Have been trying to upgrade react-native-unimodules@0.12.0 to 0.13.0 or above but failed to do so.

Compilation return error it says

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UMUtilities", referenced from:
      objc-class-ref in EXConstantsService.o
  "_OBJC_CLASS_$_UMExportedModule", referenced from:
      _OBJC_CLASS_$_EXConstants in EXConstants.o
  "_OBJC_METACLASS_$_UMExportedModule", referenced from:
      _OBJC_METACLASS_$_EXConstants in EXConstants.o
  "_UMRegisterModule", referenced from:
      +[EXConstants load] in EXConstants.o
      +[EXConstantsService load] in EXConstantsService.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 3.28.0 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/budi_tjendra/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-24 | Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 16.11.0 => 16.11.0 
      react-native: ^0.63.3 => 0.63.4 
      react-navigation: ^4.3.9 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 3.28.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

this error occur when use_frameworks!  is being used in pod file.

**Comment by budiTjendra** [comment]
I try with other alternatives by downgrade cocoapod to v1.9.3 but I get a different error saying 

In file included from .../node_modules/@unimodules/react-native-adapter/ios/UMReactNativeAdapter/Services/Permissions/EXReactNativeUserNotificationCenterProxy.m:5:
.../node_modules/@unimodules/react-native-adapter/ios/UMReactNativeAdapter/Services/Permissions/EXReactNativeUserNotificationCenterProxy.h:7:9: fatal error: 'UMPermissionsInterface/UMUserNotificationCenterProxyInterface.h' file not found
#import <UMPermissionsInterface/UMUserNotificationCenterProxyInterface.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


For this issue, it  can be solved if someone can add missing dependency inside UMReactNativeAdapter.podspec

require 'json'

package = JSON.parse(File.read(File.join(__dir__, '..', 'package.json')))

Pod::Spec.new do |s|
  s.name           = 'UMReactNativeAdapter'
  s.version        = package['version']
  s.summary        = package['description']
  s.description    = package['description']
  s.license        = package['license']
  s.author         = package['author']
  s.homepage       = package['homepage']
  s.platform       = :ios, '11.0'
  s.source         = { git: 'https://github.com/expo/expo.git' }

  s.dependency 'React-Core'
  s.dependency 'UMCore'
  s.dependency 'UMFontInterface'
  s.dependency 'UMPermissionsInterface' -- missing this line

  if !$ExpoUseSources&.include?(package['name']) && ENV['EXPO_USE_SOURCE'].to_i == 0 && File.exist?("#{s.name}.xcframework") && Gem::Version.new(Pod::VERSION) >= Gem::Version.new('1.10.0')
    s.source_files = "#{s.name}/**/*.h"
    s.vendored_frameworks = "#{s.name}.xcframework"
  else
    s.source_files = "#{s.name}/**/*.{h,m}"
  end
end

**Comment by brentvatne** [comment]
did you have an outdated version of expo-permissions in your project? if you use `EXPO_USE_SOURCE=1 pod install` does the issue persist?

**Comment by budiTjendra** [comment]
I have given it a try,  EXPO_USE_SOURCE=1 pod install does not help.

**Comment by brentvatne** [comment]
can you share a minimal reproducible example please?

**Comment by budiTjendra** [comment]
@brentvatne Here is the example project to reproduce the issue https://github.com/budiTjendra/BareUnimodule

**Comment by leocaseiro** [comment]
Should close this after merged?

**Comment by budiTjendra** [comment]
The current merged only resolves for pod 1.9.3. Need someone help to resolve the issue with pod v.1.10.1.

**Comment by kesha-antonov** [comment]
same issue

**Comment by HatimRehman** [comment]
Seeing this as well.

**Comment by brentvatne** [comment]
try cherry picking https://github.com/expo/expo/pull/12862 to your node_modules, does that help?

**Comment by gri-bchen** [comment]
same issue on pod version 1.10.1.
