### ISSUE TITLE
expo-image-picker doesn't  load image properly

### ISSUE THREAD

**Issue by denisugo** [expo/expo#12841]
### Summary

When I'm trying to load a "panorama" picture (for example width: 600, height: 30) it returns no image with the following parameters:

Object {
  "cancelled": false,
  _**"height": 0,**_
  "type": "image",
  "uri": "correct uri",
  **_"width": 0,_**
}

Important note: I have tested this issue on 4 different (2 iPhones, 1 iPad, 1 Android) devices and only one loads a picture correctly. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

4.3.2

### Environment

Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - /usr/local/bin/node
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

      const result = await ImagePicker.launchImageLibraryAsync({
        allowsEditing: false,
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        quality: 1, //check it later
        exif: false,
        base64: false,
      });
      
      console.log(result)

**Comment by denisugo** [comment]
Found out that the problem can be avoid if the picture is downloaded directly to the device (not from iCloud) with the app, that loads the picture

**Comment by denisugo** [comment]
You can use this uri to check this issue 
[lorem picsum](https://picsum.photos/600/10)

**Comment by mstach60161** [comment]
It looks like this problem does not occur on expo sdk 42. I have tried to reproduce it on different devices. Could you please try this on a newer SDK and if it still occurs, reopen the issue with an updated sdk version?
