### ISSUE TITLE
[eas] - Unable build application with EAS build

### ISSUE THREAD

**Issue by giautm** [expo/expo#12845]
### Summary

I have an error when I build an android app on EAS build. My build ID is `a276ca34-3dae-45c1-a34e-c6133f30fced`.

```
> Task :react-native-community_netinfo:checkReleaseManifest
> Task :react-native-community_masked-view:processReleaseManifest
> Task :react-native-gesture-handler:checkReleaseManifest
> Task :react-native-community_netinfo:processReleaseManifest
> Task :react-native-maps:checkReleaseManifest
> Task :app:bundleReleaseJsAndAssets FAILED
                 Welcome to React Native!
                Learn once, write anywhere
Error: The resource `/build/workingdir/build/apps/xxxxxxxxxx/index.js` was not found.
    at /build/workingdir/build/node_modules/metro/src/IncrementalBundler.js:157:26
    at gotStat (fs.js:1864:21)
    at callback (/build/workingdir/build/node_modules/graceful-fs/polyfills.js:299:20)
    at FSReqCallback.oncomplete (fs.js:183:21)
> Task :react-native-gesture-handler:processReleaseManifest
> Task :react-native-maps:processReleaseManifest
```

**TL/DR: Other issues when I migrate the project to EAS build**

I trying to migrate the current project from SDKv40 to SDKv41 and use EAS build. Because My project is in a mono repo so it has a lot of problems when I build the project.

1) I have an issue with `expo upgrade` when ran it under `apps/foo`. Related to a bug of yarn, https://github.com/yarnpkg/yarn/issues/7807, so I have to downgrade yarn to version `1.18.0` with `yarn policies set-version 1.18.0` to fix the issue.

2) My project uses some private packages hosting on Github Package Registry. So, I have to authenticate with packages. Put, `.npmrc` in the project root doesn't work. I have to ready instruction to find the way is adding an script `eas-build-pre-install` into my package.json for update `~/.npmrc`. (The guide should help me do it faster).

```json
{
    "eas-build-pre-install": "echo \"//npm.pkg.github.com/:_authToken=${NPM_TOKEN}\" >> ~/.npmrc"
}
```

3) My project in the workspace. Yeah, again. EAS complains about modules not found for `expo-constant`,... I checked the symlinks list at [`bare-expo`](https://github.com/expo/expo/blob/70b640021ae9f7c5df7eddddfe7a0b855548a3ee/apps/bare-expo/package.json#L101-L106) but It not enough to resolve the issue.  Finally, the list is below; a lot of modules have to symlinks:
```json
{
  "expo-yarn-workspaces": {
    "symlinks": [
      "@unimodules/core",
      "@unimodules/react-native-adapter",
      "expo-camera",
      "expo-constants",
      "expo-splash-screen",
      "expo-structured-headers",
      "expo-updates",
      "unimodules-app-loader",
      "unimodules-barcode-scanner-interface",
      "unimodules-camera-interface",
      "unimodules-constants-interface",
      "unimodules-face-detector-interface",
      "unimodules-file-system-interface",
      "unimodules-font-interface",
      "unimodules-image-loader-interface",
      "unimodules-permissions-interface",
      "unimodules-sensors-interface",
      "unimodules-task-manager-interface"
    ]
  }
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.0

### Environment

EAS BUILD

### Reproducible demo or steps to reproduce from a blank project

none,

please DM me to get access my repo

**Comment by brentvatne** [comment]
hi! monorepos are very complicated to get right in managed apps on eas build and we're working on improving that. in general it is a lot more difficult to have your build from your repo run on another machine rather than just downloading assets and have a very controlled and simple build process like with `expo build`. 

the build id you linked to seems to have a totally different issue, though: "Error: Provisioning profile and distribution certificate don't match."

**Comment by brentvatne** [comment]
also, one thing i noticed here is:

```
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.io/guides/customizing-metro
```

can you share your metro.config.js? it seems like it could possibly be causing this issue

**Comment by giautm** [comment]
Oh, Sr. Copied wrong build ID. The correct is `a276ca34-3dae-45c1-a34e-c6133f30fced`

**Comment by giautm** [comment]
This is my `metro.config.js`
```js
const { createMetroConfiguration } = require('expo-yarn-workspaces')

module.exports = (() => {
  const workspacesConfig = createMetroConfiguration(__dirname)
  const { sourceExts, assetExts } = workspacesConfig.resolver

  return {
    ...workspacesConfig,
    transformer: {
      ...workspacesConfig.transformer,
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      ...workspacesConfig.resolver,
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  }
})()
```

**Comment by brentvatne** [comment]
can you try running the build locally with the instructions from https://docs.expo.io/build-reference/local-builds/ and see if that helps to understand the source of the issue?

**Comment by brentvatne** [comment]
also do you have index.js in your project directory?

**Comment by giautm** [comment]
Of course, no. In my `package.json`, the`main` field point to `"__generated__/AppEntry.js",`. I also have `App.tsx` next to `package.json`, but there is no `index.js`. Maybe it related to this issue too?

https://github.com/expo/expo/issues/11744#issuecomment-784821966

**Comment by brentvatne** [comment]
there might be some interaction between the prebuild process and expo-yarn-workspaces producing an undesirable result here. can you create `index.js` that just imports `__generate__/AppEntry.js`?

**Comment by giautm** [comment]
Yeah, the first success build `7edb0b49-f66d-4ace-881f-f3fd1d271386`

Just added a new secret. `ENTRY_FILE`. :)))

<img width="611" alt="Screen Shot 2021-05-07 at 05 22 52" src="https://user-images.githubusercontent.com/12751435/117374043-9e8a8c80-aef6-11eb-8e6f-d881c23e1148.png">

**Comment by giautm** [comment]
I have a question about `symlinks` list. Which modules I should symlinks? How can I find them without having to try each module one by one?

**Comment by giautm** [comment]
> "Error: Provisioning profile and distribution certificate don't match." - I think this is fairly self explanatory, there is a problem with the provided app signing credentials

I don't know why they don't match. I just re-created both of them because they expired. Hừm...

**Comment by brentvatne** [comment]
are you changing the bundle id dynamically in app.config.js or something?

**Comment by brentvatne** [comment]
> I have a question about `symlinks` list. Which modules I should symlinks? How can I find them without having to try each module one by one?

our new autolinking implementation won't require this for expo modules: https://github.com/expo/expo/pull/11593

we need to symlink some packages because in podfile and gradle files some package contents are referred to by relative path, eg: https://github.com/expo/expo/blob/70b640021ae9f7c5df7eddddfe7a0b855548a3ee/templates/expo-template-bare-typescript/ios/Podfile#L1-L3

if you had a normal "bare" project then you might potentially change these paths to point to your monorepo root node_modules rather than symlinking to the project node_modules (although i still prefer symlinking), but these files don't exist until `prebuild` runs for managed apps

**Comment by brentvatne** [comment]
we're investigating a good fix for the `index.js` issue that you encountered. i'll also update the documentation to clarify that support for monorepos with managed apps on eas build (wow that's a lot of words) is still a bit rough

**Comment by giautm** [comment]
Thanks @brentvatne, <3

**Comment by giautm** [comment]
> are you changing the bundle id dynamically in app.config.js or something?

Just update: I pick the wrong certificate distribution type (I picked `ALL` instead of `iOS`). Re-generate new certificates fixed the issue.

**Comment by giautm** [comment]
Build error on iOS, look like I have to remove `expo-permissions` from my app. Related https://github.com/expo/expo/pull/11955
```
duplicate symbol '_OBJC_CLASS_$_EXReactNativeUserNotificationCenterProxy' in:
    /Users/expo/Library/Developer/Xcode/DerivedData/ViecCo-gyyyvlbqcgcffydhwooujvtlirif/Build/Intermediates.noindex/ArchiveIntermediates/ViecCo/BuildProductsPath/Release-iphoneos/EXPermissions/libEXPermissions.a(EXReactNativeUserNotificationCenterProxy.o)
    /Users/expo/Library/Developer/Xcode/DerivedData/ViecCo-gyyyvlbqcgcffydhwooujvtlirif/Build/Intermediates.noindex/ArchiveIntermediates/ViecCo/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXReactNativeUserNotificationCenterProxy.o)
duplicate symbol '_OBJC_METACLASS_$_EXReactNativeUserNotificationCenterProxy' in:
    /Users/expo/Library/Developer/Xcode/DerivedData/ViecCo-gyyyvlbqcgcffydhwooujvtlirif/Build/Intermediates.noindex/ArchiveIntermediates/ViecCo/BuildProductsPath/Release-iphoneos/EXPermissions/libEXPermissions.a(EXReactNativeUserNotificationCenterProxy.o)
    /Users/expo/Library/Developer/Xcode/DerivedData/ViecCo-gyyyvlbqcgcffydhwooujvtlirif/Build/Intermediates.noindex/ArchiveIntermediates/ViecCo/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXReactNativeUserNotificationCenterProxy.o)
ld: 7 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by brentvatne** [comment]
it looks like your dependencies are incorrect for sdk 41:

you should have `expo-permissions@12.0.1` but your project has `expo-permissions@10.0.0`

i suspect other deps are also out of date

can you share the project w/ me on github?

**Comment by giautm** [comment]
Nope, I don't have version 10.0.0. I used `expo-permissions@12.0.1`. Is bug maybe on your side?

<img width="419" alt="Screen Shot 2021-05-07 at 07 39 02" src="https://user-images.githubusercontent.com/12751435/117381890-5162e680-af07-11eb-83e7-20f4c4e14c41.png">

**Comment by giautm** [comment]
I just invite you, you can review PR https://github.com/viecco/universal/pull/27

**Comment by brentvatne** [comment]
@giautm - i don't think it's a bug on our side, no. you can try to reproduce this issue by doing a fresh clone of your repo, running `yarn`, and then running `expo prebuild` in your project directory

**Comment by giautm** [comment]
Hey, Let's talk on FB (https://fb.com/giautm) or Twitter (https://twitter.com/giau_tm). I will send you a token to access them.

**Comment by brentvatne** [comment]
i found the problem - in app.config.json you still have "sdkVersion": "40.0.0"

you can actually just remove this field entirely and we will determine it based on your "expo" package version.

the result of the sdk version being wrong here is that we install the appropriate versions of various packages, because we base that entirely off of the sdk version. we ended up installing react-native-unimodules 0.12.0 instead of 0.13.2, and the former brought with it expo-permissions@10.0.0

**Comment by giautm** [comment]
In my app, I still need a way to get the version of the current Expo to display to QC/for debugging suppose.

So, I will read package.json to get version the put it into extra instead. To avoid future mistakes. :'(
