### ISSUE TITLE
Add/Update contact on iOS/Android

### ISSUE THREAD

**Issue by kevinleeTCA** [expo/expo#1284]
I am doing a mobile project using CRNA and expo (build and release).
The current [contacts API only support read](https://docs.expo.io/versions/latest/sdk/contacts.html)
Any plan to hook up Add/Update or even delete ?

I also found a [library](https://github.com/rt2zz/react-native-contacts) which support CURD on contacts for both iOS and Android.

However, this library need the permission for the contacts write (WRITE_CONTACTS) in order to add/update/delete contacts, while Expo only support [read permissions](https://docs.expo.io/versions/latest/sdk/permissions.html#expopermissionscontacts)
```
Expo.Permissions.CONTACTS
The permission type for reading contacts.
```

Any idea on how we can make it work ?

**Comment by kevinleeTCA** [comment]
In order to make eact-native-contacts

We have to run

`react-native link react-native-contacts`

to link the project with the native code, which means we need to `Eject` the project from Expo.

Or else we will always get error

`undefined is not an object (evaluating '_reactNativeContacts2.default.addContact')`

Any other idea or info ? thanks

**Comment by terribleben** [comment]
Hey there, you are correct that for now you would need to [detach to ExpoKit](https://docs.expo.io/versions/latest/guides/expokit.html) if you want to link the `react-native-contacts` library.

We have a [feature request](https://expo.canny.io/feature-requests/p/contacts-api) to support adding a contact in our SDK. Please feel free to upvote that.

**Comment by seanahrens** [comment]
It appears that Expo, as of writing, still does not support add/update contact on Android (only ios). If I must have this feature in my app, must I eject the project from Expo? Or can I use react-native-contacts without ejecting from Expo?

**Comment by mskg** [comment]
Then document is outdated. Since 32, Expo can write contacts on Android, too. 

But the Expo App itself does not acquire the _WRITE permission. You have to add the permission and build an Android native App.
