### ISSUE TITLE
expo watch external module of yarn workspace

### ISSUE THREAD

**Issue by veeramarni** [expo/expo#12856]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by brentvatne** [comment]
not sure i understand what an "external module of yarn workspace" is

it sounds like in your follow up comment you refer to webpack, so you may be interested in the latest release of expo-yarn-workspaces which improves support for web https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces#usage-with-expo-web
