### ISSUE TITLE
How to hide File Picker StorageAccessFramework?

### ISSUE THREAD

**Issue by lincdh** [expo/expo#12863]
### Summary

I just want to obtain the object return from requestDirectoryPermissionsAsync without opening the file picker:
![storageacesss](https://user-images.githubusercontent.com/21136244/117526525-fd7ffc80-afef-11eb-876f-15ac8c8ea29d.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

System:
OS: Windows 10 10.0.19041
Binaries:
Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
npmPackages:
"expo-file-system": "^11.0.2",
"expo-local-authentication": "^11.0.2",
"react": "17.0.1",
"react-native": "0.64.0",
Devices:
Xiaomi Note 8 Pro

### Reproducible demo or steps to reproduce from a blank project

Anytime you use StorageAccessFramework.requestDirectoryPermissionsAsync(), it automatically opens file picker

**Comment by brentvatne** [comment]
that's actually a bit of a simplification, you could use `MANAGE_EXTERNAL_STORAGE` permissions but if you do this you will need to complete an "All files access permission declaration" on Google Play and it's only possible to use in standalone apps currently

**Comment by lincdh** [comment]
If not possible. Is there a way to close file picker in code?
