### ISSUE TITLE
Where to customize the web port number

### ISSUE THREAD

**Issue by fungmo** [expo/expo#12861]
### Summary

After using `expo build:web`, I want to start the service with `npx serve`. But the default port is 5000, I want to change it to another number.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41

### Environment
```base
Expo CLI 4.4.4 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```
## Step1. 
```base
expo build:web
```

## Step2.
```base
cd web-build
npx serve
```

**Comment by byCedric** [comment]
Hi @fungmo! The serve library is a library from Vercel, we don't maintain it. If you have more questions related to serve, you might have more luck on [their repo](https://github.com/vercel/serve#readme)

That being said, you can define the port by using the `-l` or `--listen` flag. Something like this should work:

```
$ npx serve -l 1337
```

Hope this helps!
