### ISSUE TITLE
gl-react-expo load local files "file:///..." -> "Invalid FileSystem URI 'ExponentAsset"

### ISSUE THREAD

**Issue by MobileAppVault** [expo/expo#1287]
Hi,

trying to load local images ( no assets ) from the local document directory to gl-react-expo surface and want to add filter to this image. 

*The app user Workflow is:** User take picture with camera -> picture will stored on local app directory -> user want to add filter on the picture. 

```javascript
import { Surface } from "gl-react-expo";

//...

render() {

    const imageUri = FileSystem.documentDirectory + '/' + this.props.imageName; // for example: DEMO-IMAGE-1.png
    // imageUri: file:///......./DEMO-IMAGE-1.png

    return (
        <Surface>
            <Colorify colorScale={ColorScales.monochrome} interpolation="linear">
                { {  uri: imageUri }}
            </Colorify>
        </Surface>
    );

}
 ```

When I try this... I get the folloing error: `Invalid FileSystem URI 'ExponentAsset-DEMO-IMAGE-1.png', make sure it's in the app's scope.`

**EXPO: 24.0.0**

Already tried different  ` { {  uri: imageUri }}` or ` { imageUri }` and with `require()` I am not able to load dynamic paths.

So is there a solution for that? 

Many thanks for your help!

**Comment by nikki93** [comment]
@MobileAppVault https://github.com/brentvatne/blearexp is an example of using images with gl-react in Expo. I think this may be more specific to gl-react since if you pass an FS path to `gl.texImage2D(...)` in Expo's GLView with `{ localUri: <uri in FS> }` it will work.

**Comment by terribleben** [comment]
Closing for now since I think nikki provided a working example of this. Let us know if you're still running into trouble.

**Comment by nikki93** [comment]
@MobileAppVault To clarify, https://github.com/brentvatne/blearexp/blob/803bcac442e8c30033e3ef3849271ca6393d91fc/App.js#L67-L84 downlaods an image to a local path, and https://github.com/brentvatne/blearexp/blob/803bcac442e8c30033e3ef3849271ca6393d91fc/src/GLImage.js is the component that takes the `source` prop and renders it with a shader. You can probably just use the `GLImage` component as-is.
