### ISSUE TITLE
Blur View not working in SDK 41

### ISSUE THREAD

**Issue by MrLoh** [expo/expo#12870]
### Summary

The BlurView somehow doesn't seem to work for me anymore on iOS. I have reproduced this in a brand new project, not sure whether there is some configuration missing, but this is very weird. It doesn't work either on my device and on my simulator.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.0

### Environment

  Expo CLI 4.4.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.1.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.16.0 - ~/.config/nvm/14.16.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 7.12.0 - ~/.config/nvm/14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I created a brand new bare expo app and added blur view to reproduce. See: 

https://github.com/MrLoh/expo-blur-bug

This should have created a blur on iOS
```jsx
export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
      <BlurView style={{
        position: "absolute" , 
        width: '100%', 
        height: '100%', 
        background: 'red'
        }}></BlurView>
    </View>
  );
}
```

But I got this behavior:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-09 at 20 38 17](https://user-images.githubusercontent.com/1285032/117595488-97d26400-b106-11eb-9436-761d4677676a.png)

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/sdk/blur-view/

there's a working example on the page. blurview didn't change at all in sdk 41

**Comment by brentvatne** [comment]
actually the text is indeed not being blurred properly, creating new issue
