### ISSUE TITLE
BlurView not blurring text properly

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#12871]
### Summary

Text behind a `BlurView` looks like this:

![117595488-97d26400-b106-11eb-9436-761d4677676a](https://user-images.githubusercontent.com/90494/117604690-e681fd00-b10a-11eb-9efb-160ae95ffc77.png)

It should look more like this:

![Screen Shot 2021-05-09 at 9 12 34 PM](https://user-images.githubusercontent.com/90494/117604862-4a0c2a80-b10b-11eb-8ab5-837ae5b4c6da.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.0

### Environment

  ```
  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Using @MrLoh's MCVE from #12870: https://github.com/MrLoh/expo-blur-bug you can see that the text is indeed not blurred.

**Comment by sandergo90** [comment]
+1

**Comment by MrLoh** [comment]
yeah something weird is happening here, I checked carefully, even ensured that the normal blur view worked in a fresh react native package. I'd be happy to help investigate this, just don't know where to start.

**Comment by bbarthec** [comment]
Hey there 👋 
I've created a simple snack app with some more control over blur effect: https://snack.expo.io/@bbarthec/blurview-demo.
Apparently, blur effect on iOS is actually applied, but until `intensity > 60` (default value is `50`) the visible effect is rather similar to container view's `opacity` value manipulation.

If you're looking for visually distinguishable blur effect I suggest setting `intensity > 90` on iOS (use provided snack to find the most accurate value for your scenario).
