### ISSUE TITLE
[eas][android] expo-branch cause app crash

### ISSUE THREAD

**Issue by giautm** [expo/expo#12883]
### Summary

Look like double-linking causes a crash on Android. How I can exclude `expo-branch` on android?

```
E AndroidRuntime: FATAL EXCEPTION: create_react_context
E AndroidRuntime: Process: XXXXX PID: 10110
E AndroidRuntime: java.lang.IllegalStateException: Native module RNBranch tried to override RNBranchModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:55)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

Can I use this config to exclude?
https://github.com/expo/expo/blob/422beec748adabbf0f6be3922e9a7ea6170fb8a2/apps/bare-expo/package.json#L36-L53

Or this config?
https://github.com/expo/expo/blob/1e001f80d902303a40e370c7b996b01c3b088119/apps/bare-expo/package.json#L36-L66

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.0

### Environment

EAS build

### Reproducible demo or steps to reproduce from a blank project

none,

**Comment by Ideopunk** [comment]
Is there a way to use the config in a managed app without exporting?

**Comment by giautm** [comment]
> Is there a way to use the config in a managed app without exporting? 

Hey, I don't known what is export. You just need put config into package.json like the sample app.

**Comment by Ideopunk** [comment]
react-native-unimodules isn't one of my packages. But I'm still waiting on https://github.com/expo/expo/issues/12906 to resolve, so I'll cross this bridge later, haha.

**Comment by giautm** [comment]
> react-native-unimodules isn't one of my packages. But I'm still waiting on https://github.com/expo/expo/issues/12906 to resolve, so I'll cross this bridge later, haha.

Expo has dependency on react-native-unimodules. So, you don't have to install it, just put that config to package.json.

Anw, they have new autolink engine. So, this method will no longer support soon.

I also blocked by issue #12906

**Comment by jvincent-dev** [comment]
were you guys able to successfully migrate from expo-branch to react-native-branch with the plugin? I got Branch.subscribe() to work on iOS, but after I open the link the app crashes most of the time. I've set up the info plist through app.plugin.js and added the lines for AppDelegate using `@expo/expo-config` 's withAppDelegate() and inserting lines of code through config.modResults.content. If you guys have any tips or material I can read, that would be helpful. Thanks in advance

**Comment by robert-nash** [comment]
@jvincent-dev  I would be very interested to hear more about how you figured this out and if you've now got react-native-branch working? 
Thanks!

**Comment by jvincent-dev** [comment]
hey @robert-nash and anyone else having trouble setting up Branch with EAS, I have helped someone else with this and you can find their forum post [here](https://forums.expo.dev/t/eas-react-native-branch-example-config-plugin-working-on-ios-and-android/56017). I hope this helps!

**Comment by robert-nash** [comment]
Thanks @jvincent-dev, that's very helpful!

**Comment by Dakuan** [comment]
unfortunately that patch doesn't work for me:

```
❌  (ios/Birda/AppDelegate.m:102:1)

  100 | return [RNBranch continueUserActivity:userActivity];
  101 | 
> 102 | @end
      | ^ unexpected '@' in program
  103 | 
  104 | #if defined(EX_DEV_LAUNCHER_ENABLED)
  105 | @implementation AppDelegate (EXDevLauncherControllerDelegate)

❌  (ios/Birda/AppDelegate.m:114:7)

  112 | 
  113 | @end
> 114 | #endif
      |       ^ expected '}'
  115 | 

❌  (ios/Birda/AppDelegate.m:114:7)

  112 | 
  113 | @end
> 114 | #endif
      |       ^ missing '@end'
```

**Comment by dmitryame** [comment]
Any latest updates on this?
Now, that with new expo 45 I'm kind of suck, I tried to ask similar question on the expo forum https://forums.expo.dev/t/branch-support-on-expo-managed-eas-build/63894?u=dmitryame
If anyone was able to figure it out -- I'd really appreciate any info sharing.

**Comment by dmitryame** [comment]
@giautm  I'm wondering, if this proposed solution is ready to be used? I'm trying to follow the documentation and on prebuild steps for run:ios and run:android getting a lot errors.

**Comment by giautm** [comment]
> @giautm  I'm wondering, if this proposed solution is ready to be used? I'm trying to follow the documentation and on prebuild steps for run:ios and run:android getting a lot errors.

I'm using it on production. What's the error? Can you share some logs?

**Comment by dmitryame** [comment]
The error I'm getting:
**Branch API key is required: expo.android.config.branch.apiKey**

in app.config.js I've got section:
```
expo: {
    plugins: [
      "@config-plugins/react-native-branch",
      {
        apiKey: "key_live_xxxxxxxxxx",
        iosAppDomain: "link.wisaw.com",
      },
    ],
  },
```

as well as:
```
  android: {
    config: {
      branch: {
        apiKey: "key_live_xxxxxxxxxx",
      },
    },
...
```
and
```
ios: {
    config: {
      usesNonExemptEncryption: false,
      branch: {
        apiKey: "key_live_xxxxxxxxxx",
      },
    },
...
```
Any ideas?

**Comment by giautm** [comment]
Hello @dmitryame, can you try to run `expo config --type prebuild` then verify `apiKey` still exists in the result? I think it missing somewhere in your app.

**Comment by dmitryame** [comment]
running `expo config --type prebuild`
Get following output:
```

Branch API key is required: expo.android.config.branch.apiKey
Error: Branch API key is required: expo.android.config.branch.apiKey
    at Object.withBranchAndroid (/Users/dmitry/hacks/wisaw/WiSaw/node_modules/@config-plugins/react-native-branch/build/withBranchAndroid.js:29:15)
    at withBranch (/Users/dmitry/hacks/wisaw/WiSaw/node_modules/@config-plugins/react-native-branch/build/withBranch.js:7:34)
    at plugin (/Users/dmitry/hacks/wisaw/WiSaw/node_modules/@expo/config-plugins/src/plugins/withRunOnce.ts:38:52)
    at withRunOnce (/Users/dmitry/hacks/wisaw/WiSaw/node_modules/@expo/config-plugins/src/plugins/withRunOnce.ts:24:10)
    at /Users/dmitry/hacks/wisaw/WiSaw/node_modules/@expo/config-plugins/src/plugins/withRunOnce.ts:38:12
    at withStaticPlugin (/Users/dmitry/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/withStaticPlugin.ts:138:12)
    at /Users/dmitry/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/withPlugins.ts:20:43
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/dmitry/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/withPlugins.ts:20:18)
    at withConfigPlugins (/Users/dmitry/.config/yarn/global/node_modules/@expo/config/src/plugins/withConfigPlugins.ts:19:14)

```

**Comment by giautm** [comment]
Can you try to run without the plugin, please? Just comment out the plugin from the expo.config.js to avoid the error, then check the result.

**Comment by dmitryame** [comment]
Indeed, following your suggestion, the apiKey is missing from the results. How (where) am I supposed to add it? I thought, according to the documentation, it goes into the plugin section,

**Comment by giautm** [comment]
Can you double check the config file, you may have both app.json/ and app.config.js / app.config.ts. Some files may overrider your settings. If you still need help, you can contact me via Telegram/ Twitter/ Discord on my profile

**Comment by dmitryame** [comment]
Per https://stackoverflow.com/questions/72125921/how-to-modify-podfile-in-an-expo-managed-react-native-project had to upgrade     "react-native-branch" to "5.4.0" -- seems to finally not give me any errors -- only testing now. 
Thanks for helping.

**Comment by dmitryame** [comment]
One last question, (still learning how this whole new approach with plugins works), is it suggested to add ./ios and ./android generated folders to version control, or it's better to .gitignore them and regenerate as needed?

**Comment by dmitryame** [comment]
I'm coming to the conclusion that ios/ and android/ folders are only needed on the local box to be able to run the apps on Simulator directly (opposed to Expo go) -- there is no need to version control these folders, they will be re-generated on the eas build server (or on local) as needed.

It all finally works! Thank you for your help.

**Comment by wodin** [comment]
Yes, the presence of android/ios directories means you have a "bare" app, rather than a managed app.

See here:
https://forums.expo.dev/t/should-i-exclude-ios/63094/4?u=wodin
