### ISSUE TITLE
webpack fails on web with SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by veeramarni** [expo/expo#12886]
### Summary

When running Web, with latest `expo-yarn-wroksapces@1.5.1` fails with following error. 

```
› Open in the web browser...
(node:86443) UnhandledPromiseRejectionWarning: /Users/full-layout/node_modules/expo-yarn-workspaces/webpack.js:31
    const patterns = workspacePackage.workspaces ?? [];
                                                
SyntaxError: Unexpected token '?'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
```

This points to this line

https://github.com/expo/expo/blob/master/packages/expo-yarn-workspaces/webpack.js#L31

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### Environment

This is related to yarn workspace package and not related to SDK.

### Reproducible demo or steps to reproduce from a blank project

Can try with following webpack config

Here is my webpack config

```
const webpack = require('webpack');
const path = require('path');
const { createWebpackConfigAsync } = require('expo-yarn-workspaces/webpack');

module.exports = async function (env, argv) {
    const config = await createWebpackConfigAsync(env, argv);



    config.plugins.push(
        new webpack.DefinePlugin({
            __CLIENT__: true,
        }),
    );
    config.resolve.symlinks = true;

    return config;
};
```

**Comment by veeramarni** [comment]
Please check the PR, it is working for me and should fix the problem.

**Comment by tsapeta** [comment]
You probably have an older version of node installed on your machine. `??` is a nullish coalescing operator that is supported since v14.0.0 — I'd recommend to update it either way.

**Comment by veeramarni** [comment]
Ok, also there is another fix to support `workspaces.packages`

**Comment by byCedric** [comment]
Also, see #12674 and the discussion in the PRs. We are holding off on this change, we want to focus on supporting newer versions instead, node 14 and 16. It's recommended to use Node 14, [it's the current LTS node version](https://nodejs.org/en/about/releases/). Node 12 is in maintenance mode, meaning it's being phased out and node 10 is already end of life.

**Comment by ide** [comment]
As commented on the other PR, expo-yarn-workspaces currently requires Node 14+, not necessarily LTS. Upgrading to Node 16 should resolve this issue.
