### ISSUE TITLE
Analytics error: Duplicate analytics client created with tag

### ISSUE THREAD

**Issue by mathieumg** [expo/expo#1288]
We ejected (though it might not be related) and started having a lot of instances of this error:

"Duplicate analytics client created with tag: x"

Where x is 0, 1, 2, etc.

I was looking at https://github.com/expo/expo/blob/ios/sdk24/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/SegmentModule.java#L79 and was wondering if there is a way that would cause the `SegmentModule` class to get reinstanciated but not the Analytics object to be reset (wake from sleep, crash handling, etc.), and thus cause the `sCurrentTag` to reset to 0 and eventually lead to that error?

SDK24, Android.

See https://github.com/segmentio/analytics-android/blob/639eedffb24b2af3d1c6500cf5b98c548843526c/analytics/src/main/java/com/segment/analytics/Analytics.java#L1294-L1298

Possibly related: https://github.com/segmentio/analytics-android/issues/538

Thanks a lot!

**Comment by jesseruder** [comment]
Hi @mathieumg! Is this in development mode or in production? Where are you calling `initializeAndroid` in your app?

**Comment by mathieumg** [comment]
Hi @jesseruder !

This happens in production. I am calling [`Expo.Segment.initialize({ androidWriteKey: key, iosWriteKey: key })`](https://docs.expo.io/versions/latest/sdk/segment.html#exposegmentinitialize-androidwritekey-ioswritekey-);

**Comment by jesseruder** [comment]
Ok good to know it's happening in production.

Where are you calling that initialize method from your code? Are you sure you're not calling it more than once over the lifetime of your app?

**Comment by mathieumg** [comment]
Even if I was, the `sCurrentTag++` should be preventing that, no?

It's currently called once at the top of a file we import in some places, so that should work as a singleton within the same lifetime.

Thanks!

**Comment by AdamJNavarro** [comment]
Hey @mathieumg,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
