### ISSUE TITLE
"Uncaught Error: org.json.JSONExeption" Started a new project, chose tabs starter, used QR code to share project to my samsung s6

### ISSUE THREAD

**Issue by acomito** [expo/expo#1289]
This new project mentioned in the title seems to be using v25 of expo (must be out but announced?). I'm getting the "Something went wrong" screen and the log essentially matches this message:

https://forums.expo.io/t/uncaught-error-org-json-jsonexeption-value-doctype-of-type-java-lang-string-cannot-be-converted-to-jsonobject/2487

But, I have 2-3 other projects that are on v24 and getting the same error.

Note, this is only when I'm running it locally and sharing via the tunnel URL. The published versions seem to be working still I think.

**Comment by terribleben** [comment]
Hi, acknowledging this report. Will ask an Android person to take a look.

**Comment by acomito** [comment]
@terribleben I think maybe it's related to the wifi at my coworking space. I'll close this for now. Thanks!
