### ISSUE TITLE
expo-screen-capture:compileDebugKotlin build fails: "onChange" override nothing

### ISSUE THREAD

**Issue by Ppang0405** [expo/expo#12894]
### Summary

Expected: Code work.
Actual: Code do not work

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

WARNING: expo-cli has not yet been tested against Node.js v16.1.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Maintenance LTS)
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <16.0.0 (Current Release)

  Expo CLI 4.4.4 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.1.0 - ~/.asdf/installs/nodejs/16.1.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.11.2 - ~/.asdf/installs/nodejs/16.1.0/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/truongnguyen/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 27, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-S | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1 
      react-dom: 16.14.0 => 16.14.0 
      react-native: 0.64.0 => 0.64.0 
      react-native-web: 0.13.18 => 0.13.18 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

init project from this boilerplate: https://github.com/kanzitelli/rnn-starter
run in M1 Mac. (checked with real device and emulator, both of them fail)

![Screen Shot 2021-05-12 at 00 47 59](https://user-images.githubusercontent.com/33455900/117861676-e2e1a800-b2bb-11eb-8c3c-a04823921a6a.png)

**Comment by brentvatne** [comment]
please share a minimal reproducible example that we can clone and run. we're happy to investigate if we have that.
