### ISSUE TITLE
Access source of examples

### ISSUE THREAD

**Issue by lucfranken** [expo/expo#129]
https://expo.io/@community/image-upload-example

There is no link to get to the source of the example.

This is the primary result for a google search on "expo.io upload image"

Found the source on GitHub (5th Google result): https://github.com/expo/image-upload-example

**Comment by dikaiosune** [comment]
At some point we hope to allow developers (including ourselves) to provide a link to the source code in their exp.json, but we're a little ways off from supporting that.

**Comment by lucfranken** [comment]
@dikaiosune thanks! Ok, but as I understand this one is an official example from Expo right?

**Comment by skevy** [comment]
@lucfranken that's correct, it is not.

**Comment by dikaiosune** [comment]
Created a feature request on Canny for this: https://expo.canny.io/feature-requests/p/opt-in-to-displaying-link-to-source-repository. We'll track it there from now on. Thanks!
