### ISSUE TITLE
Support returning ph:// from MediaLibrary APIs

### ISSUE THREAD

**Issue by yagudaev** [expo/expo#12903]
### Summary

On iOS Assets Library API is depreacted: https://developer.apple.com/documentation/assetslibrary. The MediaLibrary still uses the old `assets-library://` schema. It is incompatible with a few APIs like the sharing API and the FaceDetection API.

Found this comment here that alerted me to that: https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/ios/RNCAssetsLibraryRequestHandler.m#L68.

After a [Twitter conversation ](https://twitter.com/notbrent/status/1392898252513579010?s=20)we found these lines responsible: https://github.com/expo/expo/blob/fffbdb3161449764087dfa6d555ad1f88eb86dfe/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L920-L926

I was quite confused about it as you can see here: https://stackoverflow.com/questions/67422493/getting-a-filesystem-uri-from-assets-in-expo-rn. 

The only workaround I found from the JS API was to copy assets to a cache directory. This is less than ideal as it slows things down quite a bit.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0

### Environment

N/A

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by yagudaev** [comment]
In Bare flow you can use:

```swift
let oldUrl = URL(string: imageUri)!
let assets = PHAsset.fetchAssets(withALAssetURLs: [oldUrl], options: nil)
```

**Comment by StampixSMO** [comment]
Is there any direct way to translate `library-assets://` URIs to `ph://` URIs? This breaks my entire app, because e.g. react-native-fast-image doesn't want to display these URIs either.

**Comment by yagudaev** [comment]
@StampixSMO not directly as far as I know. You can however try one of two workarounds:

1. Copy the asset to the cache directory, it should give you back a `ph://` asset. I do that for the share sheet for example. The code looks like this:

```
// iOS specific
    let uri = savedPhoto.uri
    if (uri.match(/^assets-library:\/\//)) {
      const newUri = FileSystem.cacheDirectory + 'sharable-image.jpg'
      await FileSystem.copyAsync({
        from: uri,
        to: newUri
      })
      uri = newUri
    }
    await Sharing.shareAsync(uri, { UTI: 'image/jpeg', mimeType: 'image/jpeg' })
    ```

2. Use native modules and write your own code. The code I shared in the previous comment will do the conversion, that's all you really need. 

Follow this guide: https://reactnative.dev/docs/native-modules-ios

3. Use https://github.com/react-native-cameraroll/react-native-cameraroll instead, it seems more up to date and has a few nice features like optimizing fetch performance. Sadly, it still doesn't allow you to specify the preferred size, so you can get a thumbnails size instead of a full-res image...

2 and 3 will require you to eject from expo. Number 1 will be a good starting point, although extremely inefficient if you need to process many photos, that's where the other options will come in.

**Comment by StampixSMO** [comment]
Thanks @yagudaev, nr. 1 is not an option for displaying a large number of images, I might go the native route as we're very dependant on expo-media-library.
Thanks!

**Comment by yagudaev** [comment]
@StampixSMO that was my problem too, we analyzed a grid of images to see which ones have faces in them to show the users what we can automatically retouch. I ended up writing native code as you saw above.

Let me know how it goes, I'm actually thinking of re-writing the whole media-library API in native Swift if I can't get good performance out of cameraroll. In fact, I doubt I actually will as we need smaller images for faster face detection, not full-res images. Those two APIs simply don't give that level of control :(.

**Comment by StampixSMO** [comment]
@yagudaev My use case is simply making a photo selector interface, so I do not have that constraint. Will let you know what we end up with, it might be cameraroll.

**Comment by StampixSMO** [comment]
I ended up just rewriting the `asset-library://` URIs to `ph://` URIs by grabbing the ID from the former's query parameters & appending it to the latter.

I did have to install an SDWebImage plugin to support `ph://` URIs though.

**Comment by ajsmth** [comment]
hey there - I've been looking into this issue a bit today - I think the method you might want to use here is `MediaLibrary.getAssetInfoAsync(asset)` which will return a `localUri` containing the `file://` url that can be used with other APIs. This method obtains a local image url via `PHAsset.requestContentEditingInputWithOptions` async block
 
An alternative, as you have noted in SO, would be using something like `PHImageManager requestImageDataForAsset` after obtaining the PHAsset - although this is not done by the MediaLibrary module so you'd have to write your own implementation for that. 

In either case, updating the url here does not immediately solve any integration issues that you've described, as most of these APIs require the `file://` localUri from a `PHAsset`, something that needs to be asynchronously fetched one way or another. That being said I think it's safe to update the `asset-library://` to `ph://` url and I'll try and get this into SDK 43

In the meantime, the an `asset.id` can be used to generate the same `ph://` url like so: 

```js
function getPhotoKitUrl(asset) {
   return `ph://${asset.id.split("/")[0]}`
}
```
