### ISSUE TITLE
expo-document-picker is not working on Android. [TypeError: undefined is not an object (evaluating '_ExpoDocumentPicker.default.getDocumentAsync')]

### ISSUE THREAD

**Issue by RandGor** [expo/expo#12902]
### Summary

I have listener for button.

It works pretty well on Web, but got error on Android `[TypeError: undefined is not an object (evaluating '_ExpoDocumentPicker.default.getDocumentAsync')]`

I see it on emu Android 11 and my phone Android 7.1.2.

Already tried to uninstall app and clean gradle.

Can you tell me how can I solve this? Or please provide any RN app source code that uses `document-picker` and works well.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

"expo-document-picker": "^9.1.2"

### Environment

  Expo CLI 4.4.6 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 15.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 16, 21, 26, 27, 28, 29, 30
        Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.1, 30.0.2
        System Images: android-10 | Google APIs Intel x86 Atom, android-14 | ARM EABI v7a, android-16 | Intel x86 Atom, android-16 | Google APIs ARM EABI v7a, android-16 | Google APIs Intel x86 Atom, android-17 | Google APIs Intel x86 Atom, android-18 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7322048
    npmPackages:
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64 => 0.64.0
      react-native-web: 0.15.5 => 0.15.5
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```
  ChooseFile = async () => {
    console.log('Pick file!')

    getDocumentAsync({
      copyToCacheDirectory: false,
      type: "*/*" // all files
    }).then((file)=>{
      console.log(file);
    }).catch((err)=>{
      console.error("Error:( ", err);
    })
  }
```

**Comment by RandGor** [comment]
I found the solution! It was important to resolve all warnings from unimodules. And check that it was installed properly

**Comment by wnikola** [comment]
> I found the solution! It was important to resolve all warnings from unimodules. And check that it was installed properly

@RandGor 
Could you please elaborate?
