### ISSUE TITLE
Is the Secure Store Encryption instantly setup upon installation?

### ISSUE THREAD

**Issue by efhan-the-unorthodox** [expo/expo#12905]
This is my first time writing an issue or should I say question. So please bear with me if I am breaking any unwritten rules about how to properly ask questions.

Likewise, I have a small question regarding expo SecureStore. 
So I understand that SecureStore allows one to store _sensitive_ information like tokens and what not in which will be encrypted in the Keychain and KeyStore for iOS and Android respectively. The setup is pretty straightforward too for both Expo and Bare Workflow environments.

Given that I am working in a bare RN workflow I simply carried out the following installation process as stated on expo docs for securestore which states to install:

Run
`expo install expo-secure-store` (I actually did `npm install expo-secure-store` and it still workd)
Then in the iOS folder, run `pod install`

However, can I get some insight to whether the values that I store are by default "encrypted" so as to say upon setting a key value pair using `setItemAsync('token', accessToken)`
Will the data be encrypted by default or are there additional steps to setup the encryption?

**Comment by cruzach** [comment]
Hi! It's automatically encrypted, but you do have some additional options you can provide if you'd like: https://docs.expo.io/versions/latest/sdk/securestore/#securestoresetitemasynckey-value-options

We keep GitHub for bug reports- if you have a question, the best place to go is our forums or discord 😄 https://docs.expo.io/next-steps/community/
