### ISSUE TITLE
[ios][eas][expo-branch][managed-workflow] Branch params is always empty when using eas build

### ISSUE THREAD

**Issue by arnaudcombes** [expo/expo#12906]
### Summary

I have migrated my app to 41 SDK, and the new eas build pipeline. When the app is built with the new eas build pipeline (managed workflow), branch does not call the callback with params. So, the deep linking feature is broken.

#### With eas build

` {"error":null,"params":{"+is_first_session":true,"+clicked_branch_link":false,"+rn_cached_initial_event":true},"uri":null}
`

#### With expo build

`{"error":null,"params":{"~marketing":true,"+is_first_session":false,"debug":"true","$marketing_title":"Debug","~creation_source":1,"~id":920259617150271500,"+clicked_branch_link":true}
`

This is same code running with SDK 41. 

Let me know if you need more info guys 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.68
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```ts
import Branch from "expo-branch";
import Constants from "expo-constants";
import * as React from "react";
import { StyleSheet, Text, View } from "react-native";

export default function App() {
    const [params, setParams] = React.useState(null);

    React.useEffect(() => {
        Branch.subscribe(bundle => {
            setParams(bundle);
        });
    }, []);

    return (
        <View style={styles.container}>
            <Text style={styles.paragraph}>{params}</Text>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        paddingTop: Constants.statusBarHeight,
        backgroundColor: "#ecf0f1",
        padding: 8,
    },
    paragraph: {
        margin: 24,
        fontSize: 18,
        fontWeight: "bold",
        textAlign: "center",
    },
});


```

**Comment by giautm** [comment]
Hey @byCedric, can you check this issue. I can confirm issue is happend on iOS build with EAS build.

**Comment by Ideopunk** [comment]
I have the same on iOS with EAS build and expo-branch@4.1.0

**Comment by giautm** [comment]
Het @brentvatne, Do you have any information about this issue? I have to switch back to expo build because this.

**Comment by Ideopunk** [comment]
@arnaudcombes have you found a workaround to this besides switching back to `expo build`?

**Comment by brentvatne** [comment]
[`expo-branch` isn't compatible to EAS Build](https://docs.expo.io/build-reference/migrating/#expo-branch--is-not-supported-on-eas). the long term solution here is likely that we will be deprecating expo-branch and recommending that users who want to use branch should use the official [react-native-branch](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution) library with a [config plugin](https://docs.expo.io/guides/config-plugins/). if someone wants to have a shot at writing a config plugin for this, please do!

**Comment by Ideopunk** [comment]
Would a config plugin for `react-native-branch` be much different from the `expo-branch` plugin? I'm a bit confused about expo-branch becoming deprecated when a config plugin was made for it a few months ago.

**Comment by brentvatne** [comment]
@Ideopunk - when the config plugin was made, the developer doing that work did not realize that there was additional work needed to properly support it. when we looked at what would be needed it became clear that the best path forward was to just use the first-party branch library directly.

there is some additional work beyond what is done in the expo-branch config pluguin, because most of the heavy lifting there is done with the expo-branch unimodule -- like [calling branch methods from appdelegate methods](https://github.com/expo/expo/blob/master/packages/expo-branch/ios/EXBranch/EXBranchManager.m#L10-L40) and [the equivalent android behavior](https://github.com/expo/expo/blob/faafcebd14187674a5285504a731dcc9c46c67fe/packages/expo-branch/android/src/main/java/expo/modules/branch/BranchIntentNotifier.java#L20-L23).

the process of building a config plugin for this library would be to convert the instructions from https://help.branch.io/developers-hub/docs/react-native into a config plugin.

**Comment by Ideopunk** [comment]
Darn. Thanks for clarifying!

**Comment by Aryk** [comment]
Where can I find the current config plugins that was made for expo branch?

**Comment by brentvatne** [comment]
you could try this: https://forums.expo.dev/t/eas-react-native-branch-example-config-plugin-working-on-ios-and-android/56017

**Comment by giautm** [comment]
Hey @brentvatne, Can you make it be become official support under [`config-plugins`](https://github.com/expo/config-plugins/tree/master/packages)?

**Comment by brentvatne** [comment]
i think the best solution here is to upstream a plugin and the related expo module extension to react-native-brach. we can look into this in the new year, after we rolled out some more expo module hooks in sdk 44

**Comment by giautm** [comment]
Okay, I will upgrade our apps to SDKv43 and try eas build again.
