### ISSUE TITLE
Android + react-native-screens + createNativeStackNavigator not keeping orientation on SDK 41.

### ISSUE THREAD

**Issue by Aryk** [expo/expo#12916]
### Summary

After upgrading to SDK 41, I started noticing that my portrait app went landscape **only** on Android devices (I tested it on two android devices).

I looked for the bug and it's due to an issue in the react-native-screens library that I believe is a regression:

https://github.com/software-mansion/react-native-screens/issues/836

I've tried all the fixes the others have tried in the ticket, but **[NOTHING](https://github.com/software-mansion/react-native-screens/issues/836#issuecomment-839687068)** worked for me. Maybe I missed something or maybe something special needs to be done for Expo Managed apps?

I made an MCVE so you guys can see what's happening. For some reason this wasn't happening on SDK 40.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.4 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.12.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /Users/aryk/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/Aryk/expo-repro/tree/android-orientation

**Comment by brentvatne** [comment]
are you building your standalone app with EAS Build? if not, any changes you make to the native code won't be included in your managed app. [more info](https://blog.expo.io/expo-managed-workflow-in-2021-5b887bbf7dbb)

**Comment by Aryk** [comment]
I am not. I'm using the usual `expo build` command. I'm happy to take a look at this to solve the issue, but here is the thing:

This issue is visible on Expo Go as well before I get to the build stage of my app.

In other words, on Android in Expo Go, it rotates, but in iOS in Expo Go, it does not. 

Are you saying that if I try a fix from the [ticket](https://github.com/software-mansion/react-native-screens/issues/836), it will always be broken in Expo Go, but when I build it, it will actually use the code changes I make in the .java files?

And I can only do that *if* I build with EAS?

Thx in advance for your help!  🙏

**Comment by Aryk** [comment]
I am not. I'm using the usual `expo build` command.

I just read the [article](https://blog.expo.io/expo-managed-workflow-in-2021-5b887bbf7dbb) you wrote and I understand things better now, but still not fully. 

I really don't want to do an EAS build because I don't need to trade-off bundle size for a more limited ability to do over the air updates. It's not really an optimization I need right now. Is there no other way to essentially fix my orientation (without of course dropping react-native-screens)?

If I do proceed forward and try the EAS build... you wrote in the article:

> In simple cases, adding libraries outside of the Expo SDK will work fine because React Native automatically links them through Gradle and Cocoapods. But installing native module libraries often involves some **additional configuration** of the native projects, and prebuild only knows how to do this for Expo SDK packages.

For a one line change in react-native-screens, do I need to add a "config plugin" or will it just work if I do an eas build?

Slightly off-topic question. Does the reduced bundle size happen automatically on EAS builds? How does one specify what not to include? Or does it just look in your app and tree-shake and figure out what's unused?  

Thx in advance for your help!  🙏

**Comment by brentvatne** [comment]
you won't need to add a config plugin. here are instructions for how you could migrate: https://docs.expo.io/build-reference/migrating/

**Comment by Aryk** [comment]
Great, I'll give this a shot. As far as making the change.

Is it enough if I just fork the package, make the one line change and then build with EAS, right? 

@cruzach mentioned something about using patch-package, but I'm hoping just a straightforward fork and pointing my package.json to the right sha like `https://github.com/Aryk/react-native-screens.git#54e852095b` is enough.

**Comment by brentvatne** [comment]
fork is fine too. but patch-package is easier imo
