### ISSUE TITLE
[expo-notifications] Task :expo-notifications:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by christiancascone** [expo/expo#12923]
### Summary

I updated Expo SDK to version 41 and I'm not anymore able to build my project, I receive errors about deprecated class on Firebase that expo-notifications is still using.

> Task :expo-notifications:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings
517 actionable tasks: 3 executed, 514 up-to-date
/Users/christian/Documents/dr-app/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/tokens/PushTokenModule.java:8: error: cannot find symbol
import com.google.firebase.iid.FirebaseInstanceId;
                              ^
  symbol:   class FirebaseInstanceId
  location: package com.google.firebase.iid
/Users/christian/Documents/dr-app/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/tokens/PushTokenModule.java:9: error: cannot find symbol
import com.google.firebase.iid.InstanceIdResult;
                              ^
  symbol:   class InstanceIdResult
  location: package com.google.firebase.iid
/Users/christian/Documents/dr-app/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/tokens/PushTokenModule.java:65: error: cannot find symbol
        .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                                                      ^
  symbol:   class InstanceIdResult
  location: class PushTokenModule
/Users/christian/Documents/dr-app/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/tokens/PushTokenModule.java:67: error: cannot find symbol
          public void onComplete(@NonNull Task<InstanceIdResult> task) {
                                               ^
  symbol: class InstanceIdResult
/Users/christian/Documents/VURP/dr-app/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/tokens/PushTokenModule.java:64: error: cannot find symbol
    FirebaseInstanceId.getInstance().getInstanceId()
    ^
  symbol:   variable FirebaseInstanceId
  location: class PushTokenModule
Note: /Users/christian/Documents/dr-app/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ExpoNotificationBuilder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.11.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 17.0.2 => 17.0.2 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.64.1 => 0.64.1 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.6
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

I'm not able to say how to reproduce it. I think that expo-notifications doesn't work anymore after Google updated his libraries.

**Comment by cruzach** [comment]
As it says in the template, Issues without reproducible demos are going to be closed. I tested this on a blank project:
```
expo init (use bare template)
yarn add expo-notifications
cd android && ./gradlew installDebug
```

 and didn't have any issues, and the [version of firebase messaging](https://github.com/expo/expo/blob/master/packages/expo-notifications/android/build.gradle#L92) we use is still supported.
