### ISSUE TITLE
iOS: There was an error with this build 

### ISSUE THREAD

**Issue by nikasvan** [expo/expo#1292]
Hi There trying to build and getting this error. Worked fine couple couple days ago. This is what I see when I run `exp build:status i`

`Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: 6ef0c9a6-6a71-40de-b555-10c3e58714fe
[exp] Run `exp build:status` to monitor it.

 exp build:status           
[exp] There is a new version of exp available (48.0.2).
You are currently using exp 46.0.6
Run `npm install -g exp` to get the latest version
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build.

**Comment by fxfactorial** [comment]
Hi, please upgrade to latest exp and try again.

**Comment by nikasvan** [comment]
Upgrade helped
