### ISSUE TITLE
Camera.recordAsync method doesn't wait Camera.stopRecording to resolve

### ISSUE THREAD

**Issue by THook** [expo/expo#1293]
Hello all,

I've been playing with Expo today for the first time and have problems with recording videos. Basically, the record stop immediately after Camera.recordAsync() is called.

Here is the relevant part of my code :

`
    
     record = async(options) => {
        const { uri } = await this.camera.recordAsync(options)
        this.setState({ uri })
      }
`

And : 

`    

     render() {
         <Camera style={{ flex: 1 }} type={this.state.type} ref={camera => this.camera = camera}>
                 <TouchableOpacity
                    onPressIn={() => this.record({maxDuration: 240})}
                    onPressOut={() => this.camera.stopRecording()}
                  >
                    <Text style={{ fontSize: 18, marginBottom: 10, color: 'white' }}>
                      Hold to record
                    </Text>
                  </TouchableOpacity>
         </Camera>
     }
`

which results in a video of a few milliseconds. You can see the app running at this address : https://expo.io/@hugovillain/camera

As you can see, the promise resolves immediately and `onPressOut` is actually never called. I tried with a simple `onPress` and it works exactly the same way.

Any hint on this?

Thanks!

**Comment by AdamJNavarro** [comment]
Hmmm. I just tested the app on my device and was able to record a 10 second video with no issue. Also, you need to pass the maxDuration value to the recordAsync() function for it to take effect!

**Comment by THook** [comment]
That's strange, I remember the last update of Expo app failing on my phone and have some bugs unrelated to apps while using it, that may be the reason why.. (I updated the code above, which lacked an option argument to reflect your comment)

**Comment by THook** [comment]
Re-downloading the Expo App was the solution indeed! Thanks for your time
