### ISSUE TITLE
Video not playing in background (staysActiveInBackground)

### ISSUE THREAD

**Issue by leocaseiro** [expo/expo#12932]
### Summary

Hi, I'm not able to use `expo-av` to play videos in background using the `staysActiveInBackground` feature.

It's working properly with the `<Audio />` component, but it doesn't work for the `<Video />` component.

I was able to create a [snack](https://snack.expo.io/@leocaseiro/video-play-in-background), but because of the nature of Expo Go, it's not possible to reproduce with that. 
I've tested using the iOS simulator.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.4.4 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.13.0 - ~/.nvm/versions/node/v14.13.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.13.0/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.13.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@leocaseiro/video-play-in-background

**Comment by matt-oakes** [comment]
Coincidently I had the same issue last week too. I've managed to find and fix the issue and opened a PR here:

https://github.com/expo/expo/pull/12950

**Comment by leocaseiro** [comment]
I was hoping that this PR merged and released would fix the issue, but I'm still not able to keep playing a video in background. I've tried using both Expo GO, and even pushing an app to TestFlight.

Unless I'm missing something, or doing something wrong, I'm not able to have a vide playing on background.

This is my source code for the Video Component:


```jsx
import * as React from 'react';
import { View, StyleSheet, Button } from 'react-native';
import { Audio, Video } from 'expo-av';

export default function App() {
  const video = React.useRef(null);
  const [status, setStatus] = React.useState({});

  React.useEffect(() => {
    Audio.setAudioModeAsync({
      allowsRecordingIOS: true,
      playsInSilentModeIOS: true,
      interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,
      interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
      staysActiveInBackground: true,
      shouldDuckAndroid: true,
      playThroughEarpieceAndroid: true,
    });
  }, []);

  return (
    <View style={styles.container}>
      <Video
        ref={video}
        style={styles.video}
        source={{
          uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
        }}
        shouldPlay={true}
        useNativeControls
        resizeMode="contain"
        isLooping
        onPlaybackStatusUpdate={(status) => setStatus(() => status)}
      />
      <View style={styles.buttons}>
        <Button
          title={status.isPlaying ? 'Pause' : 'Play'}
          onPress={() =>
            status.isPlaying
              ? video.current.pauseAsync()
              : video.current.playAsync()
          }
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
  video: {
    alignSelf: 'center',
    width: 320,
    height: 200,
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```

I'm using the following versions of expo, and expo-av:

```
"expo": "~42.0.0",
"expo-av": "~9.2.3",
```

**Comment by paulisloud** [comment]
I've just tested exactly your setup above, but with a slight upgrade to the following:
```
"expo": "~42.0.1",
"expo-av": "^9.2.3",
```
And my audio "statics out" when locking the screen and then stops. Has anyone been able to make process on this?

**Comment by leocaseiro** [comment]
It never worked for me. This issue should not being closed.
We maybe need to open a new one

**Comment by paulisloud** [comment]
@matt-oakes could you verify that your merged PR solved this for you? You seem to be the only one who ever had this working.

**Comment by matt-oakes** [comment]
@paulisloud The merged PR did solve it for me, but there may have been multiple issues and my PR only addressed the ones I was seeing.

**Comment by paulisloud** [comment]
@matt-oakes would you be able to share a minimal reproduction of your working version?

**Comment by matt-oakes** [comment]
Sorry, I won't have time for that right now. I was working on this as part of a client project and have moved on to other projects since.

Your best bet to debug your on application is to either use a [custom development client](https://docs.expo.dev/clients/introduction/) or use the [bare workflow](https://docs.expo.dev/introduction/managed-vs-bare/#bare-workflow) so you can run the app through Xcode. From there, you can set breakpoints on the lifecycle handlers in the native code to see what order they are being called.

From memory, the issue was that the player and player view controller were being set to `nil` incorrectly, which caused iOS to stop playback when going into the background.

The documentation from Apple about background video playback is here: https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/playing_audio_from_a_video_asset_in_the_background

Sorry I can't provide a working example, but you should have enough there to look into the issue further yourself.

**Comment by paulisloud** [comment]
Ok, many thanks for the details you shared. Will see what we can come up with.

**Comment by matt-oakes** [comment]
Good luck!

@brentvatne I think it's worth reopening this issue as there are multiple reports that it is either partial fixed, or not fixed correctly

**Comment by paulisloud** [comment]
Looking at the [Apple docs](https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/playing_audio_from_a_video_asset_in_the_background) @matt-oakes shared above, it appears that it may be worth addressing `applicationWillEnterForeground` (in order to reconnect the AVPlayer when returning to the foreground) as well. I am new to Expo, but based on a quick search through the code base of `expo-av`, I didn't find any calls to this function, so it makes me think even if / when _this_ bug is addressed, the second half of the equation may remain unresolved.

Though perhaps `expo-av` already manages this...

**Comment by matt-oakes** [comment]
The entering forground code is here: https://github.com/expo/expo/blob/93e61eef3bcf17b0fbc9e18a71944ff98aef6d10/packages/expo-av/ios/EXAV/EXAV.m#L129-L137

The name of this method is different because it's using the Unimodules lifecycle listener protocol. This has been moved to "Expo Modules Core" from the upcoming v43 onwards and is defined here: https://github.com/expo/expo/blob/93e61eef3bcf17b0fbc9e18a71944ff98aef6d10/packages/expo-modules-core/ios/Protocols/EXAppLifecycleListener.h

Those methods then call the relivant AV object methods called `appDidForeground`. There are different implementations for audio and video. The video one is here: https://github.com/expo/expo/blob/93e61eef3bcf17b0fbc9e18a71944ff98aef6d10/packages/expo-av/ios/EXAV/Video/EXVideoView.m#L685-L693

**Comment by paulisloud** [comment]
You're a fountain of knowledge @matt-oakes, thank again.

**Comment by matt-oakes** [comment]
No problem!

**Comment by leocaseiro** [comment]
Thank you @byCedric for reopening the issue.

Can you please download the example from the snack link for troubleshooting?

https://snack.expo.dev/@leocaseiro/video-play-in-background

I'm trying to find time to create a repo to replicate the issue.

**Comment by markymc** [comment]
Hi all, I'm seeing what I think is a related issue. In a nutshell, it seems that setting 

```js
Audio.setAudioModeAsync({
  playsInSilentModeIOS: true,
});
```
causes

```jsx
 <Video
      ...
      source={source}
      shouldPlay={shouldPlay}
      useNativeControls
      style={StyleSheet.absoluteFill}
      ...
    />
```

to close a picture-in-picture window when the app is backgrounded. 

Also, even when `playsInSilentModeIOS` is not set, the picture-in-picture window will pause playback when the app is backgrounded, which isn't desired.


This is on both my main project, and a fresh project with just the above code and:

```json
    "expo": "~43.0.2",
    "expo-av": "^10.1.3",
```


I attempted to debug/modify the native code in `expo-av` but realised (I think?) that the node module is making use of the `EXAV.framework` directly so the native source isn't being compiled into my app. Is that correct? If so, is there any way I can patch this myself in the short term? Ideally I'd like to keep playback of the video's audio if the silent switch is turned on.

Thanks!

**Comment by matt-oakes** [comment]
@markymc You can add this to the top of your `Podfile` and then run `pod install` to ask Expo to use source for certain packages:

```ruby
$ExpoUseSources = ["expo-av"]
```

**Comment by markymc** [comment]
Thanks @matt-oakes! Will give that a shot and either me or one of my team will report back. 👍

**Comment by ianbayne** [comment]
Colleague of @markymc here. 

@matt-oakes, I'm a bit confused by the intended functionality of your PR https://github.com/expo/expo/pull/12950. This is to keep the audio for a video (but _only_ the audio) playing when the app is backgrounded, correct? I believe the issue that @leocaseiro and we are having is in regard to the picture-in-picture window dismissing when the app is backgrounded. @leocaseiro, can you confirm if my understanding is correct?

@matt-oakes, following your advice [above](https://github.com/expo/expo/issues/12932#issuecomment-971378468) to allow modifying the native code in `expo-av`, we find that 

https://github.com/expo/expo/blob/b6036c099b8d5609724544594a47e26c76fdaa6e/packages/expo-av/ios/EXAV/Video/EXVideoView.m#L700-L703

is what appears to be causing the picture-in-picture window to close when backgrounding (which I suppose makes sense, since it appears the above code nulls out the player). We've got a `patch-package` patch currently that just reverses the boolean and that seems to work for our use-case:

```objc
if (!stayActive) { 
   _playerViewController.player = nil; 
   _playerLayer.player = nil; 
} 
```

My colleague found the following: https://developer.apple.com/documentation/avkit/avplayerviewcontrollerdelegate/1615817-playerviewcontrollershouldautoma?language=objc. Based on this, perhaps it would be possible to use these delegate methods to maintain a variable that would keep the picture-in-picture window around when desired. Something like

```objc
if (stayActive && !isPlayingInPictureInPicture) {
```

What do you think? (cc @DebbyLee and @uintaam)

**Comment by matt-oakes** [comment]
@ianbayne 👋 My PR was iaming at following these instructions from Apple:

https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/playing_audio_from_a_video_asset_in_the_background

This disconnects the AVPlayer when going into the background to allow it to continue playing the audio in the background.

I'm not sure if Expo AV explicitly supports picture-in-picture mode currently. There isn't any mention of it in the documentation. If it does and this breaks it, then having some way to turn off the diconnection of the AVPlayer is likely the correct solution.

**Comment by matt-oakes** [comment]
Bab bot

**Comment by matt-oakes** [comment]
Bad bot

**Comment by elliotdickison** [comment]
The fix by @matt-oakes is working great for me (expo-av@10.2.1, react-native@0.64.2) - video audio is playable when the app is backgrounded. I am experiencing the issue that others have mentioned though - the video pauses when the app enters the background and I have to resume it with the "now playing" controls. Based on the behavior of many other apps though that seems to be standard iOS behavior and not related to Matt's fix or even Expo. Does anyone know if iOS even allows continuous playback when backgrounding video? I've been diving into the iOS docs and coming up short.

**Comment by leocaseiro** [comment]
Well, I have multiple iOS apps that have that feature, such as VLC, YouTube(premium), PlayerXtreme.

VLC is open source, so maybe someone who is better than me with iOS development can see how they do it.

I found that in the docs, does that help?

https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/playing_audio_from_a_video_asset_in_the_background


This one also https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio

**Comment by leocaseiro** [comment]
I found this article that share some steps to enable that feature: https://mux.com/blog/background-audio-handling-with-ios-avplayer

**Comment by elliotdickison** [comment]
Ok yeah, on a second read through those Apple docs it does appear that the _default_ behavior is to just keep playing. One interesting difference I'm seeing between Apple's recommendation for playing in the background and the way Expo is setup is the way the "did enter background" event is detected. Apple's docs all reference the [applicationDidEnterBackground](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622997-applicationdidenterbackground) method. Expo listens for [UIApplicationDidEnterBackgroundNotification](https://developer.apple.com/documentation/uikit/UIApplicationDidEnterBackgroundNotification) or [UIApplicationDidEnterBackgroundNotification](https://developer.apple.com/documentation/uikit/uiapplicationwillresignactivenotification)  (see [this code](https://github.com/expo/expo/blob/168ee43f71f005baa11edf98e518593443e1807a/ios/versioned/sdk44/ExpoModulesCore/Services/ABI44_0_0EXReactNativeAdapter.m#L194-L228)). I wonder if there's a timing difference between the applicationDidEnterBackground method and one or both those notifications that's causing iOS to pause the video. I've never done native iOS development before, but I'll see if I can get Expo setup locally and play around with this.

**Comment by flexgrip** [comment]
Perhaps looking at how [react-native-video](https://github.com/react-native-video/react-native-video) does it would help. In Xcode you have to set the app to have the permission to keep playing the audio in the background.

In order for RN av to close the loop on video/media, it needs these items:

- [ ] Background playback in iOS
- [ ] Background playback that doesn't get killed by power management in Android
       - To do this reliably on most androids you need to have an active media notification in the tray when the app is backgrounded
- [ ] Lock Screen controls

**Comment by elliotdickison** [comment]
I recently refactored our usage of expo-av's video player (moving from an always-in-fullscreen experience to a more traditional inline player) and we are no longer seeing this problem. The player does not pause when the phone is locked or falls asleep. Unfortunately I still have no idea what the original problem was or how my refactor fixed it.

**Comment by leocaseiro** [comment]
Thank you @elliotdickison.

Are we able to test this on the snack expo? Do I need to refactor anything my example?

**Comment by elliotdickison** [comment]
@leocaseiro Background playback is working for us with a setup very similar to your snack. We first got it working on SDK 46 and it continues to work fine on SDK 47.

**Comment by okoleg** [comment]
is this issue fixed? what is solution? staysActiveInBackground: true, or staysActiveInBackground: false -  no difference,

**Comment by Userkozmin** [comment]
> is this issue fixed? what is solution? staysActiveInBackground: true, or staysActiveInBackground: false - no difference,
I am having same issue, generally with the video background and expo

**Comment by leocaseiro** [comment]
Hi @elliotdickison, are you able to provide an example of the app you had working?

I'm still not experienced with both Pods and Expo. I was trying to fix this issue in an app that I use that was built with Expo: https://github.com/jellyfin/jellyfin-expo/issues/19

But that would be my first time doing some React Native and Expo.

What do you mean by `source` instead of `loadAsync` ? I think I'm using the source prop in my snack.

How do you stop triggering fullscreen mode automatically?

**Comment by elliotdickison** [comment]
Here's how we're calling the component:

```javascript
<Video
  ref={videoElem}
  key={
    // Keying the player by URL allows us to switch videos without causing
    // expo-av to get all mixed up and start playing multiple videos at
    // once.
    videoUrl
  }
  source={
    // overrideFileExtensionAndroid is necessary when loading HLS streams
    // on Android that don't end in ".m3u8"
    { uri: videoUrl, overrideFileExtensionAndroid: "m3u8" }
  }
  positionMillis={0}
  shouldPlay
  useNativeControls
  usePoster={false}
  resizeMode={ResizeMode.CONTAIN}
  progressUpdateIntervalMillis={1000}
  onPlaybackStatusUpdate={onPlaybackStatusUpdate}
  onFullscreenUpdate={onFullscreenUpdate}
  style={
    // We explicitly set the width and height of the player based on the
    // screen size
    { width, height }
  }
/>
```

**Comment by leocaseiro** [comment]
AFAIK still not fixed

**Comment by PrinceD96** [comment]
Same issue on react-native `0.72.0` and expo `49.0.6`. iOS pauses when the app is backgrounded. I am still able to resume audio from lock controls though and then it stays uninterrupted.

**Comment by marekx** [comment]
What I've found is when I set the playsInSilentModeIOS mode:

`      await Audio.setAudioModeAsync({
        allowsRecordingIOS: false,
        staysActiveInBackground: true,
        interruptionModeIOS: InterruptionModeIOS.DuckOthers,
        playsInSilentModeIOS: true, // <- this flag makes it work
        shouldDuckAndroid: true,
        interruptionModeAndroid: InterruptionModeAndroid.DuckOthers,
        playThroughEarpieceAndroid: false,
      });`
      
      Then the audio doesn't stop, and you can clearly see the AVPlayer being unmounted the moment app goes into background as it turns black and restores when coming back to the app. Without it the player continues going and is stopped by what Im assuming is OS since it makes sense for videos not to play with the screen off. 
      
      However that itself has some repercussions, as that flag breaks the audio control widget that appears on lock screen itself resetting it.

**Comment by skfaisal93** [comment]
Still could not figure out to play in background. Can someone working example of it ? I hope this will help lot of people

**Comment by JustJoostNL** [comment]
> Still could not figure out to play in background. Can someone working example of it ? I hope this will help lot of people

Yeah I'd like a working example too.

**Comment by castdrian** [comment]
@ianbayne few years late here, but how did y’all manage to switch your application into pip mode via expo-av? From what I can see the only way to do it is by writing native code in a local expo module

**Comment by skfaisal93** [comment]
@castdrian Can you share your code with us

**Comment by ianbayne** [comment]
> @ianbayne few years late here, but how did y’all manage to switch your application into pip mode via expo-av? From what I can see the only way to do it is by writing native code in a local expo module

Hi @castdrian. Sorry, it's been several years and I no longer have access to the repo in question: It was a client project for a former workplace. Hope you can get it resolved!

**Comment by NicolasDevJS** [comment]
Hi guys, I created an Android and IOD app using expo av and I want to make the controls just play and pause in the background, is this not possible?

**Comment by castdrian** [comment]
> Hi guys, I created an Android and IOD app using expo av and I want to make the controls just play and pause in the background, is this not possible?

expo-Av is deprecated, use the new libs

**Comment by NicolasDevJS** [comment]
> > Hi guys, I created an Android and IOD app using expo av and I want to make the controls just play and pause in the background, is this not possible?
> 
> expo-av is deprecated, use the new libs

Okay, I'm going to Expo Audio tonight (expo-audio), but I still can't figure out a way to control pause in the background as a media control, do you have any ideas?

**Comment by jt6677** [comment]
> > > Hi guys, I created an Android and IOD app using expo av and I want to make the controls just play and pause in the background, is this not possible?
> > 
> > 
> > expo-av is deprecated, use the new libs
> 
> Okay, I'm going to Expo Audio tonight (expo-audio), but I still can't figure out a way to control pause in the background as a media control, do you have any ideas?

I spent a ungodly amount of time on this.  the trick is that you cannot fire pauses from component or hooks. They won't fire when App is in background. 

```
let firstSoundInstance: Audio.Sound | null = null   
1. create sound instance      
const { sound: firstSound } = await Audio.Sound.createAsync( soundFile)
           
2.  store it  firstSoundInstance =firstSound ,   also you can directly use it like  firstSoundInstance.stopAsync() somewhere else. 
3.  setTimeout does not really work in background. 
 
App  development is tricky for me as a pure web React dev. Hooks and components do not behave the same, I think. lol, I wasted so much time to come to this realization.       
```

**Comment by jt6677** [comment]
BTW, expo-av is not deprecated, Expo Audio is alpha with limited documentation. 

I also spent some time with react-native-track-player.   It has better background service registration. Pausing, Playing and switching would just work out-of-box. but it cannot play cross fade. So i have to roll with expo-av.
