### ISSUE TITLE
Can I update react-native-web?

### ISSUE THREAD

**Issue by LorhanSohaky** [expo/expo#12942]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by LorhanSohaky** [comment]
After update from Expo 40 to 41 the version of react-native-web is `~0.13.12`, but after runs `npm audit fix` the version is changed to `^0.16.3`

**Comment by brentvatne** [comment]
react-native-web is roughly tied to releases of react-native. we test against the version that we include. you can upgrade it if it works for your app, but you may encounter problems. we update react-native-web when we update react-native, and we do that according to [this logic](https://github.com/expo/fyi/blob/master/react-native-releases.md)
