### ISSUE TITLE
[SDK41] App crashes in Expo Go client

### ISSUE THREAD

**Issue by bayoremit** [expo/expo#12941]
### Summary

We have a hybrid setup that is both managed and bare. We ejected to the bare workflow a while ago, but still use the Expo Go client for development and testing. This has been working well for us until SDK 41 and I am unable to determine what changed thats causing the Expo Go client to crash on launch now with the errors below (which are not very debuggable). More to be detailed in the repro section.

![Simulator Screen Shot - iPhone 11 - 2021-05-14 at 11 42 14](https://user-images.githubusercontent.com/48926480/118318834-c78abe80-b4ae-11eb-952f-d756c63aef7e.png)

![Simulator Screen Shot - iPhone 11 - 2021-05-14 at 11 42 18](https://user-images.githubusercontent.com/48926480/118318845-cbb6dc00-b4ae-11eb-93cb-9e4291b5a80e.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

```
  Expo CLI 4.4.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2
        System Images: android-21 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: 41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: 0.13.12 => 0.13.12 
    npmGlobalPackages:
      expo-cli: 4.4.6
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

On SDK 40, though we ejected, we were still able to run our app in the Expo Go client with the command
```
EXPO_TARGET=managed expo start --web --no-https --clear --config app.dev.json
```

We created `.expo.` extensions to stub out native libs that were not supported in the Expo Go client. According to the release notes, `.expo.` extensions are no longer supported and this was my first guess on what the issue is OR the deprecation of `EXPO_TARGET=managed`

**Steps taken to update to SDK 41**
- Update `expo-cli` to the latest
- Update `expo` lib to `41.0.1`
- Update `react-native-unimodules` to `0.13.3`
- Leave all other dependencies alone for now
- Update `metro.config.js` to require from `expo/metro-config`

To temporarily bring back the support of the `.expo.` extension, try to run our app in the Expo Go client with the command
```
EXPO_LEGACY_IMPORTS=1 expo start --web --no-https --clear --config app.dev.json
```

With the change above,
- Native builds (bare workflow) works
- Expo web works
- Expo Go client crashes

Any help would be really appreciated, Thanks

**Comment by brentvatne** [comment]
please do not use the `EXPO_LEGACY_IMPORTS=1` environment variable, it's not meant to be something that you can rely on, it is a temporary measure that you can use to potentially help you get your app running. you should use patch-package instead.

**Comment by brentvatne** [comment]
also to clarify: `EXPO_TARGET` and the `.expo` extension are indeed related. the only purpose of setting the target to managed is to tell expo-cli to include the `.expo` extension. we have removed the extension and the target and moved the context check to runtime instead, which makes your bundles work in either environment.

**Comment by bayoremit** [comment]
Thanks @brentvatne , I didnt notice the stack trace pointing to appsFlyer, this helps a lot and your explanation of `EXPO_TARGET` makes a lot of sense. 

Are there any instructions out there on how to use patch-package to re-enable the `.expo` extensions we it is a much cleaner way for us to split btw non-supported libs in our bare path vs managed path

**Comment by brentvatne** [comment]
you can add this in metro.config.js if you want -- under some conditions (eg: env vars) add the .expo.js extension to sourceExts, and in others don't do that. i'd recommend against it though.. it will cause more problems than it's worth imo and it's better to adapt to the dynamic approach because that allows your bundle to run in expo go or in build
