### ISSUE TITLE
[docs] Expo Notifications docs say listeners respond to notifications dismissed, but they do not.

### ISSUE THREAD

**Issue by njdullea** [expo/expo#12946]
### Summary

The Expo Notifications documentation say that listeners respond to users dismissing notifications, but the listener only responds to the user tapping on the notification. 

[Here](https://github.com/njdullea/notification-dismiss-test) is a minimal repo example for testing.

### Link to the related docs page

https://docs.expo.io/versions/latest/sdk/notifications/#features

**Comment by cruzach** [comment]
thanks for pointing this out @njdullea , fixed in https://github.com/expo/expo/commit/928c1778f41e38e5a128a522b40ca248a4aca73f
