### ISSUE TITLE
Background Location has not been configured. To enable it, add `location` to `UIBackgroundModes` in Info.plist file

### ISSUE THREAD

**Issue by bumaa7018** [expo/expo#12958]
How to fix it.  My sdk 40.0 and added 'location` to `UIBackgroundModes` in Info.plist file. But still not working

**Comment by AdamJNavarro** [comment]
Hey @bumaa7018, for things like this please create a post on our [Forums](https://forums.expo.io/). What comes to mind first is that you will need to create a new binary after adding those changes to your `app.json`. If you haven't done so, that will explain why it is not working. If you have built a new ipa, then we can continue the discussion on the forums.

Cheers,
Adam
