### ISSUE TITLE
[SecureStore][iOS][docs] Standalone app build defaults to shared keychain access with other apps published under the same team ID; conflicts documentation.

### ISSUE THREAD

**Issue by carbonatedcoder** [expo/expo#12956]
### Summary

**The `expo-secure-storage` [documentation](https://docs.expo.io/versions/latest/sdk/securestore/) states:**
_"Each Expo project has a separate storage system and has no access to the storage of other Expo projects."_

**Problem:** 
Using all default Expo binary build and library settings, apps built under the same Apple developer Team ID have wildcard access to each other's keychain values, which conflicts with the documentation. This can lead to unexpected consequences if a developer doesn't realize this.

**Example:** 
- Two app binaries on the same device, App 1 and App 2, built under the same Apple developer team ID. 
- App 1 can access all of App 2's keychain keys set by `expo-secure-storage`, and vice versa. 
- If the same key name is accessed/set by both apps, conflicts occur. 
- If App 1 has keys set of `api_key` and `username`, while App 2 has keys set of `api_key` and `secretcode`,  App 1 can access `secretcode`. App 2 can access `username`. Both App 1 and App 2 can access `api_key` and will override other's value, when set.

**Request:**
The build implementation should be updated to reflect the scenario described in the documentation. By default, apps should not have access to another app's keychain items (through a wildcard keychain-access-group), even within the same team ID. Ideally, a build option should be added that opts-into shared groups.

**Related Info:**
- Expo SDK 41, managed workflow, iOS, expo-secure-store 10.1.0
- [Sharing Access to Keychain Items Among a Collection of Apps](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps)
- [Entitlements Troubleshooting](https://developer.apple.com/library/archive/technotes/tn2415/_index.html)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

```
Expo CLI 4.4.7 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.13.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.13.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.4.7
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Steps to verify default wildcard access:
1. Build an iOS binary with default settings.
2. Check the app entitlements of the .ipa, with `codesign -d --ent :- /path/to/the.app`
3. Note `keychain-access-groups`. The wildcard indicates shared access to any keychain values with that prefix, meaning all keys from all apps published under a single team ID.
```
<key>keychain-access-groups</key>
<array>
	<string>[TEAM_ID].*</string>
	<string>com.apple.token</string>
</array>
```

**Comment by brentvatne** [comment]
> "Each Expo project has a separate storage system and has no access to the storage of other Expo projects."

this, in hindsight, is a poorly worded way of communicating our intention, which is: "Each Expo project **within Expo Go** has a separate storage system and has no access to the storage of other Expo projects."

you can use `ios.infoPlist.entitlements` ([listed here](https://docs.expo.io/versions/latest/config/app/)) to customize the access groups. this seems well worth us documenting, thanks for calling it out

**Comment by carbonatedcoder** [comment]
> "Each Expo project has a separate storage system and has no access to the storage of other Expo projects."
> this, in hindsight, is a poorly worded way of communicating our intention, which is: "Each Expo project **within Expo Go** has a separate storage system and has no access to the storage of other Expo projects." the usual default OS sandboxing applies outside of Expo Go, but there isn't anything extra that we do out of the box.

Thanks for the reply and clarification there! I think it'd definitely be a worthwhile addition to consider updating the documentation to further clarify there and potentially call out the iOS default to share keychain access among apps published under the same team.

Going off what the current docs seemed to imply, we had been operating under the assumption that the app's `expo-secure-storage` set keys were sandboxed from our other apps, by default. We had both apps setting a unique value using the same, generic key name. Only once we saw one app literally grabbing and using the value set by the other app is where where we got a little concerned and investigated further ultimately to find out they were being shared.

**Comment by cmeread** [comment]
I have the same issue.
What is the recommended workaround?

**Comment by brentvatne** [comment]
@cmeread - you can modify the entitlements as explained in https://github.com/expo/expo/issues/12956#issuecomment-842692629

**Comment by m-lce** [comment]
Hello,
I have the same issue.
I tried to add ``` ["com.apple.token" ,"[TEAM_ID].com.my_package.my_package"] ``` in ``` ios.entitlements.keychain-access-groups ``` and I can’t see any effect.
When I inspect my ipa package it’s still
```
<key>keychain-access-groups</key>
<array>
	<string>[TEAM_ID].*</string>
	<string>com.apple.token</string>
</array>
```
Did I miss something ?

Thanks.

**Comment by moxorama** [comment]
@m-lce - Did you have a solutions for this?

**Comment by gustavo867** [comment]
> @m-lce - Did you have a solutions for this?
> 
> When I'm trying to add entitlements to app.json, I'm getting error
> 
> ```
>  Provisioning profile "*[expo] <my bundle name> AppStore 2021-07-19T17:32:11.375Z" doesn't match the entitlements file's value for the keychain-access-groups entitlement.
> ```

Did you resolve this issue?? I am with the same error and no solution found

**Comment by dhcmega** [comment]
Hi
I have two published expo apps. Each app is overwriting the other app JWT. Which in turn, makes both apps use the same session. This is terrible for me.
Thanks

**Comment by jledentu** [comment]
Same problem here. The documentation should be updated because we met conflicts between distinct published apps.
