### ISSUE TITLE
Couldn't find expo-tracking-transparency after running expo install expo-tracking-transparency

### ISSUE THREAD

**Issue by tmyuan-ds** [expo/expo#12957]
### Summary

expo install expo-tracking-transparency

Installing 1 other package using Yarn.
> yarn add expo-tracking-transparency
yarn add v1.22.5
[1/4] Resolving packages...
**error An unexpected error occurred: "https://registry.yarnpkg.com/expo-tracking-transparency: Not found".**

yarnpkg exited with non-zero code: 1
Error: yarnpkg exited with non-zero code: 1

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

 Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Users\Ming Yuan\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1) git clone the project
2) run expo install expo-tracking-transparency

**Comment by haydenbleasel** [comment]
Hey @tmyuan-ds, the new unimodule isn't released yet (probably SDK42) but you can use Admob in the meantime. Wrote up a quick explainer on this + the new upcoming unimodule here: https://dev.to/haydenbleasel/implementing-ios-14-5-tracking-transparency-in-expo-sdk41-34id

**Comment by brentvatne** [comment]
this docs page was released a bit early, i just rolled it back. we're planning a patch release to include it in sdk 41 and will update when it's available

**Comment by tmyuan-ds** [comment]
Thanks @haydenbleasel ! This article helps a lot.

**Comment by tmyuan-ds** [comment]
> this docs page was released a bit early, i just rolled it back. we're planning a patch release to include it in sdk 41 and will update when it's available

thanks for the info @brentvatne !
