### ISSUE TITLE
How to get idToken from expo-auth-session Google.useAuthRequest() ?

### ISSUE THREAD

**Issue by dorapax-lab** [expo/expo#12963]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by dorapax-lab** [comment]
Hi,

expo-auth-session Google.useAuthRequest() returns google’s idToken value as undefined.

 `const [request, response, promptAsync] = Google.useAuthRequest({`
 `   expoClientId: 'GOOGLE_GUID.apps.googleusercontent.com',`
 `  androidClientId:  'GOOGLE_GUID.apps.googleusercontent.com',`
 ` })`

response:

`"authentication": TokenResponse {`
`    "accessToken": "received correct access token",`
`    "expiresIn": "3599",`
`    **"idToken": undefined,**`
`    "issuedAt": 1614595369,`
`    "refreshToken": undefined,`
    "scope": "email profile https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email ``openid",`
`    "tokenType": "Bearer",`
`  },`

Is there a way to retrieve the idToken from Google ?

**Comment by AdamJNavarro** [comment]
Hey @dorapax-lab, please use our [Forums](https://forums.expo.io/) for questions about implementation or usage. We reserve Github issues for reproducible and actionable bug reports.

Cheers,
Adam
