### ISSUE TITLE
IOS. Custom sound for push notifications by Expo API

### ISSUE THREAD

**Issue by AndreyBaryshev** [expo/expo#12969]
### Summary

I try to send push notification with custom sound property to IOS device using expoPushToken and Expo API and get error.
Request:
```curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '[{"to":"ExponentPushToken[XXXXXXX]","body":"hello","sound":"ca_ching.wav"}]'```
Response:
```{"errors":[{"code":"VALIDATION_ERROR","message":"\"[0].sound\" must be one of [default, null, object].","isTransient":false}]}%```

Am I rightly understand that exists only one way to use custom sound for push notifications for IOS - it's use APNS API directly without Expo API?

Thanks! Expo the best! :heart:

**Comment by flalex** [comment]
Struggled with the same issue.
I got custom sound at Android using channelId only through the expo service.
But have no idea how to fix it for **iOS** without painful changes at our server side for switching it to direct communication with APNs and FCM.
Is there any easy workaround for that? Seems that issue consists only in passing value for 'sound' field to mobile app through Expo's push notification service.

Would love to help fix it if that's possible.

**Comment by cruzach** [comment]
Expo's push service doesn't currently support sending custom sounds yet ([see our docs](https://docs.expo.io/push-notifications/sending-notifications/#message-request-format)), so I'm not quite sure how you got this working on Android @flalex? an example would be awesome

That being said, we're looking into adding support soon. First we have some client-side changes to make: https://github.com/expo/expo/pull/12782

**Comment by thefinnomenon** [comment]
It works on Android because you set the sound on the channel in the app and then specify the relevant channel in the push notification. I was trying to get this to work on iOS today and I think all that is required is to change the validation in the SDKs and server-side to allow sound to be a custom string. I forked the node sdk and made the change but the server was still complaining.

**Comment by cruzach** [comment]
> I think all that is required is to change the validation in the SDKs and server-side to allow sound to be a custom string

You're correct, Expo's push service doesn't support custom notification sounds yet, although the client-side API (`expo-notifications`) _does_, this way you can use FCM & APNs directly if you need that functionality. We're looking into adding in support soon

**Comment by concept11studios** [comment]
Any update on this? @cruzach Is it possible to do custom sounds if we integrate FCM?

**Comment by Codelica** [comment]
Would love to see custom sound support in the Expo Push Notification Service.  You can add $5/mo to my monthly fee.  $10 if image attachments are supported also.  :)

**Comment by satyamdorville** [comment]
Hello Any news on this ?

**Comment by sohailmadan** [comment]
any update on this?

**Comment by Codelica** [comment]
Hopefully this will be part of the upcoming EAS Notify service.

**Comment by torocsik-marton** [comment]
Is there any update about this? I also need custom sound for push notifications on iOS.

**Comment by redareda9** [comment]
Would love to get it too, but 2 years already happened and no progress on this. So it sounds like it's never going to happen.

**Comment by anderslemke** [comment]
+1 feature request on custom sounds for the Expo Push API ❤️

**Comment by thefinnomenon** [comment]
I still think this change is just allowing the `sound` value being passed through the Push service. I wish we could get some movement on this issue because it is annoying to have to move to a custom push solution just because of this.

**Comment by nathantew14** [comment]
Perhaps you guys can vote for it on uncanny, I made a [new post](https://expo.canny.io/feature-requests/p/custom-notification-sound-support-for-ios) there. Not sure how much use it is, but hey. Better than nothing I guess.

**Comment by Ibrahim-Arif** [comment]
Why is it closed? is it fixed?

**Comment by pedroayres** [comment]
any update about it? How to send a custom sound?

**Comment by fgauna12** [comment]
I sad. Very sad. I'm going to start replacing Expo Push Notifications now.  I don't wanna dooo itttttttttt

**Comment by SiddigHope** [comment]
any updates on this for managed workflow?
