### ISSUE TITLE
Debugging Multiple Errors on Latest iOS 14.5

### ISSUE THREAD

**Issue by rcfrias** [expo/expo#12966]
### Summary

Starting with react native debugging, I realized that using the simulator with iOS 14.5 produces several errors on the simulator.

I am confident this is related with the iOS version, because the exact same scenario, machine, app, code, etc... works as expected when using simulator with iOS 11.4.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

4.4.7

### Environment

Expo CLI 4.4.7 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
      npm: 7.11.0 - ~/.nvm/versions/node/v14.8.0/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /Users/rcfrias/.rvm/gems/ruby-2.4.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 30
        Build Tools: 23.0.2, 24.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 30.0.3
        System Images: android-21 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.7
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Try any debug method (Chrome, VSCODE, Debug tools)  on the iOS simulator with iOS 14.5.

*Setting a breakpoint does stop execution on the desired line of code, but the simulator starts displaying a ton of errors about "Unable to find module for DevMenu" and a couple of seconds afterwards, the error: 

Runtime is not ready for debugging.
 - Make sure Packager server is running.
 - Make sure JavaScript Debugger is running and not paused on a breakpoint or exception and try reloading again.  <- THIS IS OBVIOUSLY THE CASE "BREAKPOINT" BUT NO REASON TO REPORT IT AS AN ERROR.

*After this 2 errors, button bar at the bottom gets unresponsive and I can only reload from cmd+R.

**Comment by brentvatne** [comment]
please post this to https://github.com/facebook/react-native/issues along with a reproducible example. expo doesn't change react-native's debugging behavior at all in a bare workflow app

**Comment by brentvatne** [comment]
i'm able to debug remote js just fine with ios 14.5:

![Screen Shot 2021-05-18 at 4 50 09 PM](https://user-images.githubusercontent.com/90494/118737162-1ca13a00-b7f9-11eb-82a0-7dbb789bf96f.png)

try resetting your ios simulator:

![Screen Shot 2021-05-18 at 4 48 48 PM](https://user-images.githubusercontent.com/90494/118737232-40648000-b7f9-11eb-90a5-cdf2dfb53051.png)

<hr />

it could be something related to your app. if you're using react-native-reanimated@2 for example, that will not work with remote debugging. 

if you can share a reproducible example we can look into this further.
