### ISSUE TITLE
Expo with Remote Debugging not working, get hanged(with ERROR: software caused connection abort and web socket connection no longer valid)?

### ISSUE THREAD

**Issue by jatinverma95** [expo/expo#1296]
Hi, 
I am new to react, developing the App by Expo XDE Create project option. My app runs only when Remote debugging is off and when I start the remote debugging then app got hanged for quite a time and finally, Something went wrong screen came up and I get the following Errors in the Error log: Software caused connection abort and Web socket connection no longer valid. And my app is also not running via the Tunnel connectivity option altogether in any way so I changed the option to LAN as my PC and Phone connected to the same Wifi network and this runs the app but only in (not remote debugging mode) and again gets hanged with the remote debugging option. Although in the browser I am getting the json both in PC and Phone via HTTP protocol + LAN connectivity option of Expo and I am using Windows 10. Why is this so?

Error Report Image:
![image](https://user-images.githubusercontent.com/21130002/35191967-47e7b98a-feae-11e7-9aec-a89da0c5442a.png)

**Comment by nicknovitski** [comment]
I suspect this is related to #438.  Could you try some of the suggestions in [this comment](https://github.com/expo/expo/issues/438#issuecomment-370994663) and let me know if they help?

**Comment by terribleben** [comment]
Closing because we haven't heard about this recently, let us know (preferably in a new issue) if you're still having trouble.
