### ISSUE TITLE
library not found for -lEXConstantssdf sdfds

### ISSUE THREAD

**Issue by gulsher7** [expo/expo#12977]
### Summary

Hey developer i wanna say thank you a lot for this amazing library yesterday i installed this library for video auto play/pause purpose like instagram reels, finally i did this task and make a release build for android, its perfectly working fine in android  but in ios when i  try to make release build then some error is raised during archive build please help i tried lot of solution but nothing happen. 

Thank you, looking forward to solution. 

<img width="1106" alt="Screenshot 2021-05-20 at 4 43 55 AM" src="https://user-images.githubusercontent.com/56266123/118896524-0e9d0780-b926-11eb-9499-7f0396126214.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

9.1.2

### Environment

 Expo CLI 4.4.7 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.10.0 - /opt/homebrew/bin/node
      npm: 7.11.2 - /opt/homebrew/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.4.7
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

<img width="1123" alt="Screenshot 2021-05-20 at 4 52 47 AM" src="https://user-images.githubusercontent.com/56266123/118897104-45bfe880-b927-11eb-8348-07f110cca142.png">

**Comment by brentvatne** [comment]
it looks like you're opening an xcodeproj file rather than xcworkspace

**Comment by gulsher7** [comment]
@brentvatne thanks for reply but i have opened xcworkspace file not xcodeproj file, but i followed bellow mentioned step and issue have resolved please mentioned this step to your docs. We are changing ios version in podfile but it will also change under build settings IOS deployment target. 

https://github.com/expo/expo/issues/12589#issuecomment-822433825

**Comment by brentvatne** [comment]
ah! yeah that's another possible source of this. unfortunate that xcode errors can be so opaque sometimes!
