### ISSUE TITLE
exp build:ios will fail on Windows 10 if username contains spaces

### ISSUE THREAD

**Issue by maximilian-lindsey** [expo/expo#1299]
Hi,

today I tried to run `exp build:ios` using the latest version of exp `v48.0.2` and made sure everything was up to date and runnig well inside Expo, but I encountered a ruby error, telling me that my local user folder could not been mounted. It turned out, this was because my username on my Windows 10 machine containes a `space`.

I created a new user on my PC `without spaces` in the username and everything worked as it should.

Just wanted to let you know about this.

**Comment by fxfactorial** [comment]
Hi, thank you, its a known limitation at the moment.

**Comment by maximilian-lindsey** [comment]
You are welcome. Would be great if you could let me know (here), when it is fixed.

**Comment by thomfre** [comment]
Has this been fixed?

**Comment by quinlanj** [comment]
hi @thomfre, back when we allowed spaces in the username, it was a bug, not a feature.  You should not be able to create a new username containing spaces with any of the expo new account creation tools (ie) website, xde, etc.

**Comment by thomfre** [comment]
My expo user doesn't have spaces. But one of my Windows users does. And I can't get this to work on that computer.
