### ISSUE TITLE
Web Browser doesn't respect safe areas when opened from a modal

### ISSUE THREAD

**Issue by sallar** [expo/expo#12999]
### Summary

When the in-app browser is triggered from a screen that is already a modal (eg. a screen with `stackPresentation: "modal"` option enabled (react-navigation native), it does not respect the phone safe areas and goes under the status bar.

| From a normal screen ✅ | From a modal screen ❌ |
| -------------------- | ------------------- |
| ![image](https://user-images.githubusercontent.com/768052/119134112-654d3300-ba45-11eb-8eaf-d5567e3d9d20.png) | ![image](https://user-images.githubusercontent.com/768052/119134207-86ae1f00-ba45-11eb-9852-ce733d58f986.png) |

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.0

### Environment
```
  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 23.0.1, 27.0.3, 28.0.1, 28.0.3, 29.0.2
        System Images: android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
        Android NDK: 20.0.5594570
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.2.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. Create an empty project with react navigation enabled
2. Use the "native" stack navigator from react navigation package
3. Create a screen with `stackPresentation: "modal"`, so it looks like a native iOS modal
4. From that page, trigger the in-app browser from `expo-web-browser` package

**Comment by chrisscott** [comment]
Fixed for me with Expo 43.

**Comment by tsapeta** [comment]
Taking into account the above comment, I'm closing the issue. Feel free to comment if that's still happening in the latest SDK version.
