### ISSUE TITLE
undefined is not an object (evaluating '_ExpoTaskManager.default.EVENT_NAME')

### ISSUE THREAD

**Issue by Rena-Ivis** [expo/expo#12995]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by Rena-Ivis** [comment]
Hello. I try to start my old project. It works fine a 2 years ago? but now i have error: E/ReactNativeJS: undefined is not an object (evaluating '_ExpoTaskManager.default.EVENT_NAME'). How i can fix it?

**Comment by byCedric** [comment]
Hi @Rena-Ivis, we [don't export anything as `default` from `expo-task-manager`](https://github.com/expo/expo/blob/master/packages/expo-task-manager/src/TaskManager.ts). If you use typescript, synthetic default export might be turned off. You can also work around it by converting:

```
// Not the right way to import:
import TaskManager from 'expo-task-manager';

// Right way to import:
import * as TaskManager from 'expo-task-manager';
import { EVENT_NAME } from 'expo-task-manager';
```

Hope this helps!

**Comment by Rena-Ivis** [comment]
I don't use import { EVENT_NAME } from 'expo-task-manager'; but I use import * as TaskManager from 'expo-task-manager'; already. Maybe you can give me another answer, please?

**Comment by Rena-Ivis** [comment]
Maybe u can explain where is EVENT_NAME used in lib?

**Comment by Rena-Ivis** [comment]
[
![Снимок](https://user-images.githubusercontent.com/25509863/119182518-ae1fde80-ba7b-11eb-9963-825e4586512f.PNG)
](url)

**Comment by Rena-Ivis** [comment]
![2](https://user-images.githubusercontent.com/25509863/119183007-29819000-ba7c-11eb-92e8-4a25b1b09676.PNG)
