### ISSUE TITLE
BarCodeScanner bugs

### ISSUE THREAD

**Issue by jsierles** [expo/expo#130]
https://snack.expo.io/HyiTlAn0e

Tested this with the latest Expo on Android (Nexus 9 tablet, android 7.1) and iOS (iPhone 6s, ios 10.3.1). In neither case does the flash turn on.

**Comment by lucfranken** [comment]
Might relate with other props issues on barcodescanner: https://github.com/expo/expo/issues/121

**Comment by skevy** [comment]
cc @nikki93

**Comment by brentvatne** [comment]
Tracking other bugs here:
- https://github.com/expo/expo-sdk/issues/54
- https://github.com/expo/expo-sdk/issues/53

**Comment by jsierles** [comment]
Might this make it into SDK 17? I've replaced the scanner with `react-native-camera` but it's more crash prone on Android.

**Comment by brentvatne** [comment]
all fixed in sdk18, to be released later today
