### ISSUE TITLE
expo-permission blocks react-native permission request

### ISSUE THREAD

**Issue by mgmskumara** [expo/expo#13008]
### Summary

When expo-permission is installed, we cant use PermissionsAndroid which is come with native or any other to request permission. 
Can request permission, but call back is never fired. I think it handle in expo-permission and not let to handle by others.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

I uninstall expo

### Reproducible demo or steps to reproduce from a blank project

Previously i have used expo managed work flow. 
Then I ejected.
Then I wanted to get location permission in two steps ( First ask foreground permission and then ask background access). For that I have to use import { PermissionsAndroid } from 'react-native'. But when I call
 await PermissionsAndroid.requestMultiple([PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION,
            PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION])
, it hanging inside it and it never finished. 
I think this is due to expo-permission

**Comment by byCedric** [comment]
Hi @mgmskumara! Thanks for the issue report. I'm not sure why `expo-permissions` would block `PermissionsAndroid`, do you have any technical references why you would think that this is happening?

As a side note: with SDK 41 we support asking either [foreground](https://docs.expo.io/versions/latest/sdk/location/#locationrequestforegroundpermissionsasync) or [background permissions](https://docs.expo.io/versions/latest/sdk/location/#locationrequestbackgroundpermissionsasync) separately. You should be able to do what you intended to do with `PermissionsAndroid` using `expo-location` only.

**Comment by mgmskumara** [comment]
Hi,
I have missed your separate methods for background and foreground.  Thanks for updating me.
Anyway I tried to debug in native side to figure it out. My initial guess was super() is not called from your side when you handle the result of permission request. But unfortunately I could not find the exact location of handling. If you have time please check it.

Thank you.
