### ISSUE TITLE
MapView.Marker causes expo client to crash without logs

### ISSUE THREAD

**Issue by jongirard** [expo/expo#1300]
Hi,

As of the latest version of expo released (SDK 24.0) I have encountered an issue with MapView's <MapView.Marker /> component (part of react-native-maps - https://github.com/react-community/react-native-maps#component-api) which causes the expo client to fatally crash without logs of any sort.

```
"expo": "^24.0.0",
    "prop-types": "^15.6.0",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
```

This problem also still occurs as of SDK 25.0 where react-native-maps has been bumped to version 19.0 (as reproducible on snack).

```
"react-native-maps": "0.19.0",
```

https://snack.expo.io/@jongirard/map-crash (comment lines 82-84 for working project, otherwise experience the fatal crash). This is a complete blocker for me at the moment in my project so I'm hoping this is easily fixable.

**Comment by tcdavis** [comment]
Thanks for the Snack!  Not sure what the cause is yet, but we'll investigate.

**Comment by jongirard** [comment]
Thanks! Hoping this can be addressed very soon as I would really like to continue to use Expo for my project

**Comment by jongirard** [comment]
I've been able to fix the issue by changing the formatting of the coordinate prop. My code should have been like ```coordinate={{latitude: 37.78825, longitude: -122.4324 }}``` which works as intended. I didn't realize that there is no type validation in this case which causes a hard crash :)
