### ISSUE TITLE
Error logging with Facebook Expo SDK

### ISSUE THREAD

**Issue by EduGomes18** [expo/expo#13012]
### Summary

Hello everyone, today i started getting this error while logging with facebook and asking for permissions, this occurs when i try to get more permissions and the login webview opens, basicaly i receive a error message : Logging into this app with Facebook is not available at this time.
I think is something with the webview, because i started trying to do a self login flux, following facebook tutorial that is basically open a url with app_id and a redirect url, so i try to do that in a webview and get the same error. Also i try using the sdk behaviour = web, same error too.
Please i need help with this, if someone can give me some ideas on how to deal with it, my app is 99% around facebook sdk D:

![logging-with-facebook-error](https://user-images.githubusercontent.com/61379704/119247014-b8fe7000-bb5c-11eb-9ae5-104d985c0646.jpeg)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40.0

### Environment

  Expo CLI 4.4.8 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.16.0 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.14.0 - /usr/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.3.9 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.4.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@edusnown/logging-into-this-app-with-facebook-is-not-available-at-this-time

**Comment by brentvatne** [comment]
as far as i can tell this is a bug on facebook's side: https://developers.facebook.com/support/bugs/3839475259507329/

**Comment by EduGomes18** [comment]
> as far as i can tell this is a bug on facebook's side: https://developers.facebook.com/support/bugs/3839475259507329/
> 
> please refer to facebook support to get more information. also, i recommend updating to expo sdk 41 for the latest facebook sdk

Thank you for the tips, i`ll try for the new sdk now

**Comment by EduGomes18** [comment]
I`m back asking for help D:, i tryed in a blank project with expo SDK 41.0 and a new facebook app, everything from scratch, i fall at the same issue, so i give up and end when i was trying to use expo-auth-session, when i finish following the docs, i fall at the same issue, here is the web browser redirect error screenshot, same as before D:

maybe i`m missing something, but like i said, i create everything from scratch and following the docs D:

![WhatsApp Image 2021-05-23 at 16 42 17](https://user-images.githubusercontent.com/61379704/119274603-16d79a00-bbe7-11eb-94f8-fbc05cc5b117.jpeg)


this is the steps to reproduce:

import { StatusBar } from "expo-status-bar";
import React, { useState } from "react";
import { StyleSheet, Text, View, Button, Image } from "react-native";
// import * as Facebook from "expo-facebook";

import * as WebBrowser from "expo-web-browser";
import * as Facebook from "expo-auth-session/providers/facebook";
import { ResponseType } from "expo-auth-session";

import { maybeCompleteAuthSession } from "expo-web-browser";

maybeCompleteAuthSession();

const config = {
  clientId: "MY_APP_ID",
  scopes: ["public_profile"],
  language: "pt-BR",
};

export default function App() {

  const [request, response, promptAsync] = Facebook.useAuthRequest(config);

  React.useEffect(() => {
    if (response?.type === "success") {
      const { code } = response.params;
      console.log(code);
    }
  }, [response]);

  return (
    <View style={styles.container}>
      <Button
        disabled={!request}
        title="Login"
        onPress={() => {
          promptAsync();
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f4f4f4",
    alignItems: "center",
    justifyContent: "center",
  },
  fotoContainer: {},
  image: { width: 200, height: 200 },
  text: { fontSize: 18, textAlign: "center" },
});

**Comment by brentvatne** [comment]
as far as i can tell this is on facebook's side, please reach out to facebook support for help

**Comment by EduGomes18** [comment]
okay, i'll try to contact them! thank you again for the support!

**Comment by YahyaBagia** [comment]
@EduGomes18 how did you do it? Got any solution?
