### ISSUE TITLE
Blank screen when using Updates.reloadAsync() in SDK 40

### ISSUE THREAD

**Issue by HarelTussi** [expo/expo#13017]
### Summary

I have upgraded expo SDK to version 40 and when I use OTA updates and Updates.reloadAsync(), I get a blank screen instead of the splash screen

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

await Updates.reloadAsync()

**Comment by byCedric** [comment]
Hi @HarelTussi! Thanks for your issue report. Could you provide a reproducible example? In [this Snack](https://snack.expo.io/@bycedric/expo-issue-13017) everything seems to be working fine using SDK 40.

**Comment by m-deacon** [comment]
@byCedric it's very difficult issue to provide a reproducible demo for this as the Updates module is an on device module. It's happening in all our production apps and for a few people (I'm sure there's more that just aren't noticing it's happening). I see there is another issue mentioning it here: https://github.com/expo/expo/issues/12000

Any suggestions on how to debug / provide a reproducible demo so you can look into it? Here's a video showing the issue, that "Restart app" button triggers this directly `onPress={() => Updates.reloadAsync()}`, should I perhaps be doing it differently?

https://user-images.githubusercontent.com/35782774/120808942-dadaf800-c549-11eb-97f5-d10a6b1d4e65.MP4

**Comment by harel-tussi** [comment]
Anything on that?

**Comment by SergiiKliebanov** [comment]
Hi guys, same issue on SDK 42. 
Method Updates.reloadAsync() hides splash screen on iOS and app continues loading with a blank screen.
