### ISSUE TITLE
Build number not updated when expo-updates applied

### ISSUE THREAD

**Issue by rwanito** [expo/expo#13028]
### Summary

Hi !
I find strange that expo-updates does not update the build number when bundle was updated.

Simply, the build number is important to check if user use the last version and report bugs.
Is it normal or maybe, there is a solution to bypass ?

Thanks for you work !

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.8 environment info:
    System:
      OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v16.1.0/bin/yarn
      npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Change the build number on android and ios both.
Do expo publish
Try to update
See that build version not changed.

**Comment by cruzach** [comment]
the build number is the _native_ build number- it can only be updated when running a new build (`expo build` or `eas build`) https://docs.expo.io/versions/latest/sdk/constants/#constantsnativebuildversion
