### ISSUE TITLE
Expo İmage Picker videoMaxDuration not working on Android

### ISSUE THREAD

**Issue by aliburhankeskin** [expo/expo#13024]
### Summary

Expo İmage Picker videoMaxDuration not working on Android,

‘videoMaxDuration ’ works perfectly on ios.

```
const result = await ImagePicker.launchImageLibraryAsync({

      mediaTypes: ImagePicker.MediaTypeOptions.Videos,

      allowsEditing: true,

      allowsMultipleSelection: false,

      quality: 0.8,

      videoMaxDuration: 20,      

      aspect: [4, 3],

    });

```
result.duration : 33222 (max 20000) (Andorid) 

The error is occurring from samsung galaxy j7 prime device. Android version : 8.1.0.

On Android Device crop of the video operation not showing..

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.0

### Environment

Expo CLI 4.4.6 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-24 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Snack Example => https://snack.expo.io/@milvasoft/imagepickerexample

```
import * as React from 'react';
import { Text, View, StyleSheet,TouchableWithoutFeedback } from 'react-native';
import Constants from 'expo-constants';
import * as ImagePicker from 'expo-image-picker';

export default function App() {

  const _pickVideo = async () => {
    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Videos,
      allowsEditing: true,
      allowsMultipleSelection: false,
      quality: 0.8,
      videoMaxDuration: 20,      
      aspect: [4, 3],
    });

  // Android Device log => { duration : 322200 } (20 seconds should not be output.)
    console.log(result);
  };
    
  return (
    <View style={styles.container}>
      <TouchableWithoutFeedback onPress={_pickVideo}>

        <Text> Choose Video </Text>

      </TouchableWithoutFeedback>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

**Comment by RyflectApp** [comment]
it is still not working on android any update?
