### ISSUE TITLE
jest-expo error with registerRootComponent

### ISSUE THREAD

**Issue by dacevedo12** [expo/expo#13026]
### Summary

Hi folks, thanks for this great SDK.

I was migrating from 40 to 41 when I found this error running the tests:

```
TypeError: Cannot read property 'match' of null

    > 1 | import { registerRootComponent } from "expo"

      at getDevServer (node_modules/react-native/Libraries/Core/Devtools/getDevServer.js:30:19)
      at Object.<anonymous> (node_modules/expo/src/environment/logging.fx.ts:14:27)
      at Object.<anonymous> (node_modules/expo/src/Expo.fx.tsx:3:1)
      at Object.<anonymous> (node_modules/expo/src/launch/registerRootComponent.tsx:1:1)
      at Object.<anonymous> (src/app.tsx:2:1)
      at Object.<anonymous> (src/index.spec.tsx:7:1)
```

My app entry is a custom one (not using the default main in package.json) and I'm calling the `registerRootComponent` function as:

`registerRootComponent(App);`

I'm also using the latest jest-expo preset

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

```
Expo CLI 4.4.8 environment info:
    System:
      OS: Linux 5.10 Deepin 20.2.1 20.2.1
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
      npm: 7.13.0 - ~/.nvm/versions/node/v12.19.0/bin/npm
    npmPackages:
      expo: 41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/refs/tags/sdk-41.0.0.tar.gz => 0.63.2 
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. run `npx expo-cli init test --template blank && cd test`
2. run `npm install jest jest-expo react-test-renderer@16.13.1`
3. change `main` to "App.js" in the package.json and call `registerRootComponent(App);` in App.js as explained in https://docs.expo.io/versions/latest/sdk/register-root-component/#what-if-i-want-to-name-my
4. create a test.js file with:
```
import React from "react";
import renderer from "react-test-renderer";
import App from "./App";

it(`renders correctly`, () => {
  const tree = renderer.create(<App />).toJSON();
  expect(tree).toHaveLength(1);
});
```
5. run `npx jest --preset jest-expo` and it will fail with the error

**Comment by SergueyML** [comment]
Did you find a way to fix this?

**Comment by byCedric** [comment]
`expo-jest` doesn't expect you to include the entry point in the tests. What happens here is that it tried to mock the `expo` package, because there are no native modules (from Android or iOS) available in Jest. In your case, the mock is omitted somehow and tries to load the native source code constants.

If you modify the default entrypoint, these things can happen. Try to split your entrypoint in `index.js` where you import `App.js` and register it with `import { registerRootComponent } from 'expo';`. By splitting it, you remove it from `expo-jest`.

Hope this helps.
