### ISSUE TITLE
exp build:ios not reflecting changes

### ISSUE THREAD

**Issue by julesmoretti** [expo/expo#1303]
Created a new project using `create-react-native-app projectname`

modified the `app.json` as per build instructions.

`npm start` reflects app locally through the iOS simulator.

`exp build:ios` pushes out build, then using the online QR code I can then see the app on my phone.

copy pasted previously used component over the app.js file, refreshed local simulator, works with no error messages and shows new component.

Ran again `exp build:ios` wait for it to complete, scanned QR code from the online project, still shows the original `Open up App.js to start working...`

Why would it not sync up? 

Does the app.json names have to match the package.json name?

Thank you

versions:
```
create-react-native-app version: 1.0.0
npm: 4.6.1
node: v9.4.0
```

package:
```
{
  "name": "project",
  "devDependencies": {
    "react-native-scripts": "1.9.0",
    "jest-expo": "23.0.0",
    "react-test-renderer": "16.0.0"
  },
  "dependencies": {
    "expo": "^23.0.4",
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-keyboard-responsive-view": "^0.1.7",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "^3.5.0",
    "react-navigation": "^1.0.0-beta.27",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2"
  }
}

```

**Comment by julesmoretti** [comment]
I also followed `5. Test it on your device or simulator` from https://docs.expo.io/versions/latest/guides/building-standalone-apps.html and still got the default generic `Open up App.js to start working...` rather than the updated component.

**Comment by tcdavis** [comment]
Can you share your app.json as well?

**Comment by julesmoretti** [comment]
Here you go:

```
{
  "expo": {
    "name": "TelegraphTest",
    "icon": "./src/assets/brands/App-Icon.png",
    "version": "1.0.1",
    "slug": "telegraphsetuptest",
    "sdkVersion": "23.0.0",
    "ios": {
      "bundleIdentifier": "com.appple.telegraphsetuptest"
    },
    "android": {
      "package": "com.apple.telegraphsetuptest"
    }
  }
}
```

**Comment by quinlanj** [comment]
hi @julesmoretti , that's really odd. The app shown in your local simulator shouldnt change if you've gotten your tar.gz file, imported it into the simulator, then changed the contents of `app.js` in your project directory. 

When you ran `exp build:ios` again, where you saw `Open up App.js to start working...`, did you run it in your project directory, or in a blank project directory?

**Comment by julesmoretti** [comment]
@quinlanj it is very odd indeed. And yes that was indeed the tar.gz file downloaded from the online portal. And yes that was run from within the project.

So here would be the exact steps:
```
create-react-native-app TelegraphTest
cd TelegraphTest
npm start
i
```

```
exp build:ios
```

At this point, both the iOS local simulator and online expo look the same.

Then I change the app.js content with other things. The simulator reflects those locally.

```
exp build:ios -t simulator
```
and on pressing enter in less than 2 seconds I get:

```
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Looking for releases...
[exp] Using existing release on channel "default":
  publicationId: 1fd73bb1-scrambled-on-purpose-7c55e
  publishedTime: 2018-01-22T19:04:51.690Z
[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] You can monitor the build at

 https://expo.io/builds/583f07-scrambled-on-purpose-8e356c

[exp] Alternatively, run `exp build:status` to monitor it from the command line.
```

```
exp build:status
```
and get:

```
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS:
[exp] IPA: https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/ios%2F%40jules-scrambled-on-purpose-6568-simulator.tar.gz
```


download tar file
using terminal 
`tar -xvzf just-downloaded-file.tar.gz`
then
`xcrun simctl install booted AppName.app`
`xcrun simctl launch booted com.appple.telegraphsetuptest`

and at this point, I get the unchanged version.

So I wonder if it is normal for exp to confirm the build progress so quickly without uploading files over as the changes I added are pretty substantial?

**Comment by jayeszee** [comment]
@julesmoretti  I had the same issue where it wasn't updating on the standalone. The reason I figured out is that it no longer builds and publishes the app for you. You have to manually publish it to expo and then run ```exp build:ios```

**Comment by julesmoretti** [comment]
@jayeszee thank you that did indeed push it through, it seems to me that, having to use the expo App to push is a bit of a burden compared to the nifty exp build:ios :/

**Comment by w-** [comment]
> The reason I figured out is that it no longer builds and publishes the app for you. You have to manually publish it to expo and then run exp build:ios

This really really  really needs to be explicit in the docs. godammnit. wasted a few hours on this.

**Comment by fxfactorial** [comment]
Hi folks, there is also a `--publish` flag for `exp build:ios`

**Comment by w-** [comment]
> there is also a --publish flag for exp build:ios

@fxfactorial  how did you discover this?

**Comment by fxfactorial** [comment]
exp, like all good unix tools, has a `--help`.

**Comment by w-** [comment]
🤕 of course it does. d'oh.

**Comment by nikasvan** [comment]
Lost lot of hours for this as well. Publishing at first and then running `exp build:ios` (`or exp build:ios --publish`)

**Comment by jayeszee** [comment]
@fxfactorial thats good to know. In previous versions they didn't have that (i used --help before), but its good that they have that now since they changed it.

**Comment by fson** [comment]
Hi everyone! Because the new `--publish` flag for `exp build` has caused a lot of confusion, we've reverted back to the previous default behavior in the latest release (`exp@49.0.1`). Running `exp build:ios` will now automatically publish the app and there's no `--publish` flag anymore. You can just run `exp build:ios` and get an iOS app with the latest code.

For advanced use cases, we've added a new `--no-publish` flag that disables automatic publishing, if you want to manage JS releases separately using `exp publish`.

Sorry about the confusion!
