### ISSUE TITLE
add information to exp diagnostics with envinfo package

### ISSUE THREAD

**Issue by tabrindle** [expo/expo#1304]
First I want to say Expo is awesome, and there are so many things that are so well done in this project. 

I'd like to help out in a similar way to [React Native](https://github.com/facebook/react-native/pull/14428) or [create-react-app](https://github.com/facebook/create-react-app/issues/3380), by adding the [envinfo package](https://www.npmjs.com/package/envinfo) to your cli (and possibly an issue template) to help streamline the issue reporting process. 

That said, `exp diagnostics` is already quite good, but it might be good to add some diagnostic information printed to the console like in `react-native-cli info` or `create-react-app --info`

```
Environment:
  OS:  macOS High Sierra 10.13
  Node:  8.9.4
  Yarn:  1.3.2
  npm:  5.6.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.4 => 0.48.4
```

Since some this information you already have, you can pull in envinfo as a library for the utility functions for getting Xcode and Android Studio versions, as well as npm package versions, and some other neat features (plus anything else you might want - I added duplicate package detection for CRA)

Let me know, and Ill get started on a PR

**Comment by tcdavis** [comment]
@fson was looking at something like this:
```
[exp] Generating diagnostics report...
[exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.5.0
  Yarn: 1.3.2-exp.1
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/fson-380bc8a6-a17c-4b5c-afbc-8a05df21bfed.tar.gz
```

you should coordinate with him, but I think a PR would be appreciated :)

**Comment by tabrindle** [comment]
Yeah that looks like envinfo already :) if there isn't already something in
progress, I'd be happy to work on this. Don't want to step on anyone's toes!

**Comment by fson** [comment]
Yup, the idea was to add envinfo to the `exp diagnostics` command as shown above. I’ve had this on my todo list for a while, but didn’t have time to add it yet. So if you want to contribute a PR to exp that would be great!

**Comment by tabrindle** [comment]
Looks like we can close this! Feel free to open a new issue if you guys want something new or changed.
