### ISSUE TITLE
No experienceId found bare workflow

### ISSUE THREAD

**Issue by Thunermay** [expo/expo#13047]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by brentvatne** [comment]
we need more information

**Comment by Thunermay** [comment]
### Summary
After starting react-native server, followiing error pops up:  
```
[Tue May 25 2021 18:01:35.554]  WARN     Possible Unhandled Promise Rejection (id: 0):
Error: No experienceId found. If it can't be inferred from the manifest (eg. in bare workflow), you have to pass it in yourself.
```
### Managed or bare workflow? If you have ios/ or android/ directories in your project, the answer is bare!
bare

### Environment

Expo CLI 4.4.7 environment info:
System:
OS: Windows 10 20H2
Shell: cmd
Binaries:
Node: 12.18.2
Yarn: 1.22.10
npm: 6.14.5
Managers:
SDKs:
iOS SDK:
Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
IDEs:
IntelliJ IDEA 2021.1.1
npmPackages:
    "@expo/vector-icons": "^12.0.0",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/material-bottom-tabs": "^5.1.14",
    "@react-navigation/native": "^5.2.3",
    "@react-navigation/stack": "^5.2.18",
    "d3": "^5.16.0",
    "expo": "^40.0.1",
    "expo-ads-admob": "^9.0.0",
    "expo-av": "~8.7.0",
    "expo-constants": "~9.3.3",
    "expo-firebase-analytics": "~2.6.0",
    "expo-image-picker": "~9.2.0",
    "expo-in-app-purchases": "^10.1.0",
    "expo-keep-awake": "~8.4.0",
    "expo-linear-gradient": "~8.4.0",
    "expo-linking": "~2.0.1",
    "expo-localization": "~9.1.0",
    "expo-notifications": "~0.8.2",
    "expo-payments-stripe": "~8.4.0",
    "expo-permissions": "~10.0.0",
    "expo-secure-store": "~9.3.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "firebase": "^7.9.0",
    "global": "^4.4.0",
    "i18n-js": "^3.7.1",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.63.2",
    "react-native-awesome-alerts": "^1.3.2",
    "react-native-background-timer": "^2.3.1",
    "react-native-chart-kit": "^6.6.1",
    "react-native-countdown-component": "^2.7.1",
    "react-native-dotenv": "^0.2.0",
    "react-native-elements": "^2.0.0",
    "react-native-flags": "^1.0.0",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-paper": "^3.11.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-svg": "12.1.0",
    "react-native-unimodules": "^0.12.0",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
npmGlobalPackages:
expo-cli: 4.4.7
Expo Workflow: bare

### reproducable Demo  
I'm sorry I can't give a reproducable Demo

**Comment by brentvatne** [comment]
you need to pass the experienceId to expo-notifications as described here https://docs.expo.io/versions/latest/sdk/notifications/#fetching-tokens-for-push-notifications

**Comment by Thunermay** [comment]
I did this but still get the same error message.
Do I have to rebuild the whole App in XCode or is a reload of the app through the metro-server enough?

**Comment by brentvatne** [comment]
should be enough to reload but because i don't have very much information on what is happening on your end you should probably also try rebuild

**Comment by Thunermay** [comment]
I know found the failure. I used the code given from the expo Docs:
```
let experienceId = undefined;
  if (!Constants.manifest) {
    // Absence of the manifest means we're in bare workflow
    experienceId = '@username/example';
  }
  const expoPushToken = await Notifications.getExpoPushTokenAsync({
    experienceId,
  });
```
The problem is, even though I'm in bare workflow, `Constants.manifest` isn't undefined. So I had to "hardcode" `let experienceId = "@username/example"`. Now it works _without_ rebuilding the app, reloading is enough.

**Comment by brentvatne** [comment]
good catch, that is indeed out of date. i believe it should be `if (!Constants.manifest.id)`

**Comment by Thunermay** [comment]
Will you make a pull request and stuff?

**Comment by brentvatne** [comment]
https://github.com/expo/expo/commit/11ca6a28857a2b75a9d0ecdd6fcaa4e3f97b42f3
