### ISSUE TITLE
"orientation: portrait" in app.json does not prevent orientation change

### ISSUE THREAD

**Issue by miladdev85** [expo/expo#13053]
### Summary

On Android there is no way to lock orientation to portrait mode.
"orientation: portrait" in app.json is specified but landscape mode is still possible.

Even using expo-screen-orientation does not lock orientation to portrait mode.

```
  React.useEffect(() => {
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);
  }, []);
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

```
Expo CLI 4.4.9 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 15.8.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.3, 30.0.2, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.9
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. Specify "orientation: portrait" in your app.json file
2. Put your physical Android device in landscape mode

If you want to try it with expo-screen-orientation:
1. Run ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT) on mount:

```
  React.useEffect(() => {
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);
  }, []);
```

**Comment by 012PhokaPitoli** [comment]
V. Sent from my Huawei phone-------- Original message --------From: Milad Hashemi ***@***.***>Date: Wed, 26 May 2021, 09:27To: expo/expo ***@***.***>Cc: Subscribed ***@***.***>Subject: [expo/expo] "orientation: portrait" in app.json does not prevent orientation change (#13053)
Summary
On Android there is no way to lock orientation to portrait mode.
"orientation: portrait" in app.json is specified but landscape mode is still possible.
Even using expo-screen-orientation does not lock orientation to portrait mode.
  React.useEffect(() => {
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);
  }, []);

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment


Expo CLI 4.4.9 environment info:
System:
OS: macOS 11.2.3
Shell: 3.0.2 - /usr/local/bin/fish
Binaries:
Node: 15.8.0 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 7.5.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.9.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
Android SDK:
API Levels: 29, 30
Build Tools: 28.0.3, 29.0.3, 30.0.2, 31.0.0
System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6626763
Xcode: 12.5/12E262 - /usr/bin/xcodebuild
npmPackages:
expo: ~41.0.1 => 41.0.1
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
react-native-web: ~0.13.12 => 0.13.18
npmGlobalPackages:
expo-cli: 4.4.9
Expo Workflow: managed
Reproducible demo or steps to reproduce from a blank project
Specify "orientation: portrait" in your app.json filePut your physical Android device in landscape mode
If you want to try it with expo-screen-orientation:
Run ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT) on mount:
  React.useEffect(() => {
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);
  }, []);

**Comment by brentvatne** [comment]
what android device are you using? and operating system version?

**Comment by miladdev85** [comment]
I'm using Samsung Galaxy S21 on Android 11. I think this behaviour is due to Expo + React Navigation 5.

If I specify screen orientation on each navigation stack, orientation is locked.

So to reproduce, you'll probably need React Navigation 5 as well.

**Comment by brentvatne** [comment]
@miladdev85 - are you using native stack?

**Comment by miladdev85** [comment]
@brentvatne Yes I do

**Comment by brentvatne** [comment]
i see. you should use this https://github.com/software-mansion/react-native-screens/tree/master/native-stack#screenorientation

**Comment by miladdev85** [comment]
@brentvatne Thank you! That's the way I got around my "issue". 

This can be closed now 🙏

**Comment by brentvatne** [comment]
the issue here is that we can lock the orientation but then other apis can go ahead and unlock it or change the lock to another value, so it's not necessarily foolproof. hopefully the existence of this issue is useful for people!

**Comment by sergeu90** [comment]
@brentvatne  Hi. I see that for ios tabs lock screen not working. I opened issue but nobody  help me answer 
https://github.com/expo/expo/issues/13184#issuecomment-856499629
Maybe you help me
