### ISSUE TITLE
requestTrackingPermissionsAsync crashes the builded app if no NSUserTrackingUsageDescription is defined

### ISSUE THREAD

**Issue by RafaelAlthaus** [expo/expo#13059]
### Summary

If the infoPlist in the `app.json` file doesn't have the `NSUserTrackingUsageDescription` key and value, the apps crashes when requestTrackingPermissionsAsync is called. This errors only occurs within the builded app, doesn't matter if is a simulator or achieve build. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.9 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      npm: 6.14.12 - /usr/local/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 30
        Build Tools: 28.0.3, 30.0.3
        System Images: android-30 | Google Play Intel x86 Atom_64, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.9
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- Add `expo-tracking-transparency`;
- Follow the implementation at the doc `https://docs.expo.io/versions/latest/sdk/tracking-transparency/`;
- Build using the cli;
- Run the simulator build or submit to test flight.

**Comment by cruzach** [comment]
Any apps using `expo-tracking-transparency` _must_ define `NSUserTrackingUsageDescription`, otherwise your app will be rejected by Apple. I can add that to the docs, thanks!

**Comment by RafaelAlthaus** [comment]
Yes, took me a few rejected reviews to figure this one out. Even Apple is not clear about the missing string. Thanks, @cruzach!
