### ISSUE TITLE
Unable to resolve module https

### ISSUE THREAD

**Issue by AlexisEspejo** [expo/expo#13060]
### Summary

Hello, I am trying to import the https module to make an instance of an httpsagent but when I deploy the SDK it shows me that it does not get the module.
**I have done all the steps that the console suggests to solve the bug and it is not solved**

undefined Unable to resolve module https from C:\Users\ingal\Desktop\ASTI\src\Helpers\HttpClientAxio.js: https could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  3 | import { Alert } from 'react-native';
  4 | import AsyncStorage from '@react-native-async-storage/async-storage';
> 5 | import * as a from 'https';
    |                     ^
  6 | process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
  7 | console.log(process.env);
  8 | console.log(a);
at node_modules\react-native\Libraries\Utilities\HMRClient.js:320:31 in showCompileError
at node_modules\react-native\Libraries\Utilities\HMRClient.js:227:26 in client.on$argument_1
at node_modules\eventemitter3\index.js:181:21 in emit
at node_modules\metro\src\lib\bundle-modules\HMRClient.js:142:10 in _ws.onmessage
at node_modules\event-target-shim\dist\event-target-shim.js:818:20 in EventTarget.prototype.dispatchEvent
at node_modules\react-native\Libraries\WebSocket\WebSocket.js:231:8 in _eventEmitter.addListener$argument_1
at node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:189:10 in emit
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
at [native code]:null in callFunctionReturnFlushedQueue

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.4.9 environment info:
    System:
      OS: Windows 10 10.0.19042   
    Binaries:
      Node: 15.6.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.12.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

![image](https://user-images.githubusercontent.com/66917532/119699736-c19fc080-be52-11eb-86f3-d1ffe318d81b.png)

**Comment by brentvatne** [comment]
that is a node library: https://nodejs.org/api/https.html

react-native is not node. https://docs.expo.io/workflow/using-libraries/#using-third-party-libraries
