### ISSUE TITLE
[environment][docs] "Download and Setup" doesn't work on Windows

### ISSUE THREAD

**Issue by andyc365** [expo/expo#13068]
### Summary

I am following the "[Download and Setup](https://github.com/expo/expo/blob/master/CONTRIBUTING.md#-download-and-setup)" instruction on my Windows Desktop, but I get stucked at the second step "2. Ensure direnv is installed on your computer.". It seems that [direnv](https://direnv.net/docs/installation.html) is about Unix only, and irrelavant to Windows. Can I try to contribute using my Windows, or I need to have a Mac? Thanks!

### Link to the related docs page

https://github.com/expo/expo/blob/master/CONTRIBUTING.md#-download-and-setup

**Comment by brentvatne** [comment]
hi there! the repo is not set up to work well on windows at the moment. i'd suggest using wsl if you're on windows

**Comment by andyc365** [comment]
Thank you for your reply! I have thought of WSL also, just hope there can have setup documentation on WSL at the same time.

**Comment by byCedric** [comment]
If you are on WSL, you can follow the steps for Linux. That should get you up and running!

**Comment by brentvatne** [comment]
added clarification to contributing that WSL is required to contribute from Windows https://github.com/expo/expo/commit/d01a0a7b010a5844235fb99fd16253913d896cf4
