### ISSUE TITLE
Navigation Bar color not changing in EAS build standalone app?

### ISSUE THREAD

**Issue by kartikeyvaish** [expo/expo#13062]
The navigation Bar color is  not changing even though I've mentioned it in the `app.json` file.

This issue has been discussed [here](https://forums.expo.io/t/navigation-bar-color-not-changing-in-eas-build-standalone-app/52842)
 @brentvatne asked to post an issue regarding this. 

My `app.json` file

```
{
  "expo": {
    "name": "NavigationBar",
    "slug": "NavigationBar",
    "version": "1.2.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#2e2a5a"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "bundleIdentifier": "com.NavigationBar.NavigationBar",
      "buildNumber": "1.0.0",
      "supportsTablet": true
    },
    "android": {
      "package": "com.NavigationBar.NavigationBar",
      "versionCode": 1,
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#2e2a5a"
      }
    },
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#2e2a5a"
    },
    "androidNavigationBar": {
      "barStyle": "light-content",
      "backgroundColor": "#2e2a5a"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

**Expo Go app develeopment Screenshot**

![Expo Go developement Screenshot](https://user-images.githubusercontent.com/55032587/119562307-ce290800-bdc3-11eb-8513-5b1eb6295f47.jpg)

**EAS Build apk screenshot result** `(eas build -p android --profile NavigationBar)`

![EAS Build Screenshot](https://user-images.githubusercontent.com/55032587/119562397-e7ca4f80-bdc3-11eb-8c86-f8f40a1f3e36.jpg)

**Expo Build apk screenshot result** `(expo build:android -t apk)`

![Expo Build Screenshot](https://user-images.githubusercontent.com/55032587/119562996-a0908e80-bdc4-11eb-8302-4887537b7d5a.jpg)

I've added EAS build apk and Expo Build apk links below.

EAS build apk link - https://drive.google.com/file/d/1xNsZPN191h8AgCPImBocBFw-Stk3-CQH/view?usp=sharing

Expo Build apk link - https://drive.google.com/file/d/1bDUOS6J32wTdAoXa_4jy9we8LfzJD69E/view?usp=sharing

Minimal Reproducible [Snack Example](https://snack.expo.io/@kartikeyvaish/navigationbar)

**App.js**

```
import * as React from "react";
import { Text, View, StyleSheet, Button } from "react-native";

export default function App() {
  return (
    <View style={styles.container}>
      <Button title="Random Button" />
      <View style={styles.BottomBar}>
        <Text>Navigation Bar color not changing in EAS Build</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
    padding: 8,
  },
  BottomBar: {
    position: "absolute",
    bottom: 0,
    height: 40,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
});
```

**Comment by kartikeyvaish** [comment]
@brentvatne Any update on this issue?

**Comment by brentvatne** [comment]
we did some refactoring in https://github.com/expo/expo-cli/pull/3539 - need to double check that this fixes the issue

**Comment by kartikeyvaish** [comment]
This is fixed now. Thanks, @brentvatne @EvanBacon.

**Comment by EvanBacon** [comment]
You can now use the `expo-navigation-bar` library to dynamically change the nav bar during runtime as well!

**Comment by injecteer** [comment]
Using "expo": "~45.0.4" now, and the 
```
    "androidNavigationBar": {
      "backgroundColor":"#363636"
    }
```
part is still ignored for EAS build

**Comment by arielmazor** [comment]
so its working in eas build?

**Comment by injecteer** [comment]
not for me

**Comment by kessris** [comment]
not working

**Comment by lgrube3** [comment]
Not working for me either.

**Comment by injecteer** [comment]
upgraded my project's dependencies to:
```
    "expo": "~46.0.7",
    "expo-constants": "^13.2.3"
    "expo-splash-screen": "^0.16.1",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.4",
    "react": "18.0.0",
    "react-dom": "18.0.0",
```
the NavBar color is still ignored.

The issue must be reopenned!

**Comment by bzozoo** [comment]
There are same problem with statusbar too

**Comment by GollyJer** [comment]
It's funny. I think I have the opposite problem.
The app.config.ts (app.json) color works but `getBackgroundColorAsync()` does nothing. Makes it impossible to adjust when the user changes their theme in our app.

**Comment by i-in-range** [comment]
I faced this issue too

**Comment by mhmtbsrglu** [comment]
not applying navigation bar background color in app.json again

**Comment by josiext** [comment]
Not working
