### ISSUE TITLE
[docs] Sourcemap information

### ISSUE THREAD

**Issue by LorhanSohaky** [expo/expo#13065]
### Summary

In the section that explains about the web build there is no mention of the sourcemap that is generated even for prod.

It is interesting to have this documented and it may even become a flag when generating the build

`GENERATE_SOURCEMAP=false expo build:web`

### Link to the related docs page

https://docs.expo.io/workflow/expo-cli/#expo-buildweb

### Anything else?

Another page > https://docs.expo.io/distribution/publishing-websites/#creating-a-build

**Comment by cruzach** [comment]
Can you provide more information on what exactly you'd like changed about the documentation?

**Comment by LorhanSohaky** [comment]
Inform that even in the production build the source map is generated and that this can be deactivated by setting the environment variable

**Comment by cruzach** [comment]
ah I see, thanks for clarifying! Would you like to open a docs PR?

**Comment by LorhanSohaky** [comment]
My English is terrible, you can be willing

**Comment by LorhanSohaky** [comment]
Reopen
