### ISSUE TITLE
[expo-branch] In which file should I set the delayInitToCheckForSearchAds and enableFacebookLinkCheck?

### ISSUE THREAD

**Issue by akichim21** [expo/expo#13066]
## question
We have chosen managed.　

In which file should I set the delayInitToCheckForSearchAds and enableFacebookLinkCheck?

Can't branch.json be handled by expo-branch?

https://github.com/expo/expo/blob/e0bb254c889734f2ec6c7b688167f013587ed201/packages/expo-branch/ios/EXBranch/RNBranch/RNBranchConfig.m

**Comment by cruzach** [comment]
We keep github for bug reports, please post on our forums or discord if you have questions 😄
