### ISSUE TITLE
There was an error publishing your project

### ISSUE THREAD

**Issue by PiTiLeZarD** [expo/expo#1307]
G'day,

I'm coming with another error, really sorry to bother you with this.

When I'm running exp build:android it ends up with:
[exp] Publishing...
[exp] Building iOS bundle
[exp] Tunnel connected.
Building JavaScript bundle [====================================================================================================] 100%[exp] Finished building JavaScript bundle in 24111ms.
[exp] Building Android bundle
[exp] Finished building JavaScript bundle in 21127ms.
[exp] Analyzing assets
[exp] Finished building JavaScript bundle in 21283ms.
[exp] Finished building JavaScript bundle in 21749ms.
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] There was an error publishing your project. Please check for any warnings.
[exp] Error: There was an error publishing your project. Please check for any warnings.
    at Object.<anonymous> (/xdl/src/Project.js:355:11)
    at Generator.throw (<anonymous>)
    at step (/Users/jonathanadami/.npm-packages/lib/node_modules/exp/node_modules/xdl/build/Project.js:1675:191)
    at /Users/jonathanadami/.npm-packages/lib/node_modules/exp/node_modules/xdl/build/Project.js:1675:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

I just rolled back ([due to another issue](https://github.com/expo/expo/issues/1306)) to 41.1.2 with npm install -g exp@47.1.2
└─┬ exp@47.1.2
  ├─┬ inquirer@2.0.0
  │ └─┬ external-editor@1.1.1
  │   └── tmp@0.0.29
  ├── tmp@0.0.33
  └── xdl@47.1.2

I tried with another version (47.1.0) same error.

My app is so popular I need this to work (I'm joking there's 22 installs haha) but yeah if you could point me out in the right direction with this issue I'd be glad! there's a heap of versions here and there I hope I didn't mess something up!

Cheers

**Comment by ChrisChares** [comment]
I'm seeing this as well in our app using version Expo `v25.0.0` and exp `v48.0.2`.  Probably worth noting I'm importing and making use of the newly supported `aws-amplify-react-native` lib.  Works fine on a real device running off a local development server.

Logs: (No warnings)
```
🌮 :scorecard$ EXPO_DEBUG=true exp publish
[exp] Unable to find an existing exp instance for this directory, starting a new one...
[exp] Starting React Native packager...
[exp] Scanning folders for symlinks in /Users/chchares/dev/scorecard/node_modules (13ms)
[exp] Loading dependency graph.
[exp] Dependency graph loaded.
[exp] Tunnel connected.
[exp] Publishing...
[exp] Building iOS bundle
[exp] Finished building JavaScript bundle in 28544ms.
[exp] Building Android bundle
[exp] Finished building JavaScript bundle in 26361ms.
[exp] Analyzing assets
[exp] Finished building JavaScript bundle in 23837ms.
[exp] Uploading assets
Building JavaScript bundle [====================================================================================================] 100%[exp] Finished building JavaScript bundle in 24714ms.
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] There was an error publishing your project. Please check for any warnings.
[exp] Error: There was an error publishing your project. Please check for any warnings.
    at Object.<anonymous> (/xdl/src/Project.js:389:11)
    at Generator.throw (<anonymous>)
    at step (/Users/chchares/.nvm/versions/node/v8.6.0/lib/node_modules/exp/node_modules/xdl/build/Project.js:1710:191)
    at /Users/chchares/.nvm/versions/node/v8.6.0/lib/node_modules/exp/node_modules/xdl/build/Project.js:1710:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by JulianKingman** [comment]
I'm also seeing this on SDK 25, but not I'm not using the fancy `aws-amplify-react-native`, and it was publishing just fine earlier today on SDK 24.
```
[exp] No assets changed, skipped.
[exp] Building sourcemaps
[exp] Finished building JavaScript bundle in 17981ms.
[exp] Finished building JavaScript bundle in 18777ms.
[exp] Uploading JavaScript bundles
[exp] There was an error publishing your project. Please check for any warnings.
[exp] Error: There was an error publishing your project. Please check for any warnings.
    at Object.<anonymous> (/xdl/src/Project.js:389:11)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/exp/node_modules/xdl/build/Project.js:1710:191)
    at /usr/local/lib/node_modules/exp/node_modules/xdl/build/Project.js:1710:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by JulianKingman** [comment]
As a temporary measure, I was able to publish using XDE (got the idea from https://github.com/expo/expo/issues/204)

**Comment by PiTiLeZarD** [comment]
It took a lot of changes in my infrastructure just to test it but I end up with the same conclusion as @JulianKingman : the XDE manages the publish without the error, thanks for that I didn't know the XDE existed :D Good job Expo team, never cease to amaze me!

It's not a solution for me though but I'm happy I can release in the meantime.

**Comment by colinyoung** [comment]
Incidentally, I am also using Expo `v25` and `aws-amplify-react-native` and am experiencing the same inability to deploy from the command line (but XDE 2.22.1 works)

**Comment by ChrisChares** [comment]
Just to chime in again, @JulianKingman's workaround of using the XDE is working for us.

Still seeing this behavior with `exp publish` on `v49.0.3` though.

**Comment by quinlanj** [comment]
hi @PiTiLeZarD @ChrisChares @JulianKingman @colinyoung , sorry for the inconvenience of the publish error. In order to root cause this, could you upload a toy app that still has this error so i can test this on my end (or email it to me at quin@expo.io) ?

I suspect that you all have different causes of the errors, but our library is just catching all of them and outputting `There was an error publishing your project.`.

**Comment by quinlanj** [comment]
Also, please report any additional info you get in the stack trace by running `EXPO_DEBUG=true exp publish`. Thanks so much!

**Comment by fson** [comment]
Version `49.0.6` of exp now has improved logging for publish errors. Could you try installing the latest exp and report the stack trace from running `EXPO_DEBUG=true exp publish`, to help us track down this error. Thanks!

**Comment by colinyoung** [comment]
I'm now getting a "[exp] Request body larger than maxBodyLength limit"

**Comment by allanleonardjr** [comment]
Here's what I get now:

```
[exp] There is a new version of exp available (49.0.7).
You are currently using exp 49.0.6
Run npm install -g exp to get the latest version
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] Uploading /assets/images/floorplan-floor-3.png
[exp] Uploading /assets/images/floorplan-floor-2.png
[exp] Uploading JavaScript bundles
[exp] Request body larger than maxBodyLength limit
[exp] Error: Request body larger than maxBodyLength limit
    at RedirectableRequest.write (/usr/local/lib/node_modules/exp/node_modules/follow-redirects/index.js:66:24)
    at RedirectableRequest.end (/usr/local/lib/node_modules/exp/node_modules/follow-redirects/index.js:78:10)
    at dispatchHttpRequest (/usr/local/lib/node_modules/exp/node_modules/axios/lib/adapters/http.js:228:11)
    at Promise (<anonymous>)
    at httpAdapter (/usr/local/lib/node_modules/exp/node_modules/axios/lib/adapters/http.js:18:10)
    at dispatchRequest (/usr/local/lib/node_modules/exp/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by fson** [comment]
Thanks for sending the new information, it helped me identify the issue. To fix it, I've now increased the `maxBodyLength` limit for requests in the latest `exp` version. Please upgrade and let us know, if that fixes the publishing issue for you.

**Comment by allanleonardjr** [comment]
Thanks @fson!
I'm now able to successfully publish & build with `exp@49.1.0`

**Comment by anp** [comment]
Hi everyone! Sounds like this is resolved. If it's not, please post back and we'll reopen this issue. If you're having other publish errors, please open a new issue. Thanks!

**Comment by colinyoung** [comment]
Works for me too! Thanks for the quick resolution, @fson !

**Comment by clarkgrg** [comment]
I had an issue until I upgraded to the latest version of expo 26.0.0.  Works for me now
