### ISSUE TITLE
presentFormAsync & addContactAsync android

### ISSUE THREAD

**Issue by josaric** [expo/expo#13082]
### Summary

If you use `addContactAsync` on android and you are trying to put the: `[Contacts.Fields.PhoneNumbers]` and you set "digits" field to integer it will add your new contact, but phone number won't be set.
If you set "digits" field to string, an error will be thrown.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.1

### Environment

```
"expo": "~41.0.1",
"expo-contacts": "^9.1.2",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-native": "~0.63.4",
```

### Reproducible demo or steps to reproduce from a blank project

works fine:

```
const data = {
  [Contacts.Fields.PhoneNumbers]: [
    {
      number: "12345",
      isPrimary: true,
      digits : "12345",
      countryCode :'',
      label: '',
      id: "12345"
    }
  ],
};
await Contacts.presentFormAsync(null, data);
```

error thrown:
```
const data = {
  [Contacts.Fields.PhoneNumbers]:[
    {
      number: "123456",
      isPrimary: true,
      digits : "123456", //string
      countryCode :'',
      label: '',
      id: "123456"
    }
  ],
};
await Contacts.addContactAsync(data);
```

saves the contact but not the phone number field:
```
const data = {
  [Contacts.Fields.PhoneNumbers]:[
    {
      number: "123456",
      isPrimary: true,
      digits : 123456, //integer
      countryCode :'',
      label: '',
      id: "123456"
    }
  ],
};
await Contacts.addContactAsync(data);
```

**Comment by dsokal** [comment]
Hi @josaric,
Thanks for reporting. What error is being thrown? 

I tried to reproduce it but it works fine for me. This is what worked:
```
const { status } = await Contacts.requestPermissionsAsync();
if (status !== "granted") {
  console.warn(`status: ${status}`);
  return;
}
await Contacts.addContactAsync(
  // @ts-ignore
  {
    [Contacts.Fields.FirstName]: "Dominik",
    [Contacts.Fields.LastName]: "Sokal",
    [Contacts.Fields.PhoneNumbers]: [
      {
        number: "123456",
        isPrimary: true,
        digits: "123456",
        label: "work",
        id: "123456",
      },
    ],
  }
);
```

As the docs state (https://docs.expo.io/versions/v42.0.0/sdk/contacts/#phonenumber), the `digits` field must be a string.

**Comment by dsokal** [comment]
I'm closing this issue for now. If the problem persists, we'll open the issue again.
