### ISSUE TITLE
Status bar ios dark mode not visible

### ISSUE THREAD

**Issue by Giacomo92** [expo/expo#13083]
### Summary

Hi everyone,
I have a visualization error with the Status Bar component. 
The text is not visible only with iOS and dark mode enable. I cannot reproduce the error on the Snack  link below.

This is a screen from the iOS simulator with dark mode enabled:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-28 at 11 50 37](https://user-images.githubusercontent.com/11694429/119965802-f6269000-bfaa-11eb-8e5e-6766d819e0c3.png)

This is a screen that run the snack on the same device with dark mode enabled:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-28 at 11 59 33](https://user-images.githubusercontent.com/11694429/119967117-4fdb8a00-bfac-11eb-9d50-7ab289dd6457.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

 Expo CLI 4.4.7 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.22.1 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/opt/node@12/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 29, 30
        Build Tools: 29.0.2, 29.0.3, 30.0.2
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.7
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@jack_0/statusbar-issue-ios-dark-mode

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/sdk/status-bar/

**Comment by Giacomo92** [comment]
Hi @brentvatne, thanks for your answer. 
I try to set this value on app.json:
`  "userInterfaceStyle": "light",`
and this is the status bar code updated:
`<StatusBar translucent={true}
                               backgroundColor={hasDarkModeActive ? "#000000" : "#ffffff"}
                               style={"auto"}
                    />`
                    
Now i can see the status bar when the page is loaded, but when I start to type on input field the status bar text disappear.


https://user-images.githubusercontent.com/11694429/120170320-223b4e80-c201-11eb-92ac-c0360410a771.mp4

**Comment by Giacomo92** [comment]
Maybe related to this https://github.com/facebook/react-native/issues/29520?

**Comment by Giacomo92** [comment]
I have solve adding this on app.json:
```
"
```


```
"expo": {
    "userInterfaceStyle": "light"
....
ios": {
      "infoPlist": {
        "UIUserInterfaceStyle" : "Light"
      }
    } 
}
```

and 
`
autoManageStatusBarEnabled={false}` on WebView component

**Comment by brentvatne** [comment]
interesting - i didn't realize webview added some status bar management api. that's too bad, that seems outside of the scope of the project.
