### ISSUE TITLE
BarCodeScanner is using the camera even upon blur

### ISSUE THREAD

**Issue by filiptronicek** [expo/expo#13098]
### Summary

When I blur out of a screen with `<BarCodeScanner>`, I still get the green `Camera in use` badge, which I believe is a bug. I thought it was maybe a bug in `react-native-navigation`, but the `onBarCodeScanned` does not fire when it is blurred. I even tried to conditionally render the `BarCodeScanner` only when the screen was focused, but it did not help.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

```
  Expo CLI 4.4.7 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\filip\AppData\Roaming\npm\yarn.CMD
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: ^17.0.2 => 17.0.2
      react-dom: ^17.0.2 => 17.0.2
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2     
      react-native-web: ^0.16.3 => 0.16.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

The demo is at: 
https://snack.expo.io/@filiptronicek/barcodescanner-blur-bug
The video demo is below (note the green dot in the top right corner persisting upon navigation away):

https://user-images.githubusercontent.com/29888641/120079317-910a9180-c0b3-11eb-8fc6-386db90348a4.mov

**Comment by byCedric** [comment]
Hi @filiptronicek! I [adjusted your snack example](https://snack.expo.io/@bycedric/expo-issue-13098) to use the [`useIsFocused`](https://reactnavigation.org/docs/use-is-focused) hook on the QR screen. It takes about 1-2s before fully removing the camera in use icon.

Uploading RPReplay_Final1622546680.MP4…

**Comment by filiptronicek** [comment]
Thanks, @byCedric, this works! Should this still be considered a bug, when the component itself isn't working when not focused?

**Comment by byCedric** [comment]
No problem! It's expected behavior, React Navigation explains it here https://reactnavigation.org/docs/navigation-lifecycle/#example-scenario. So I wouldn't consider it a bug 😄

**Comment by coralienyr** [comment]
Hello, I have the same problem but for Android @byCedric  if I launch the application from an iphone and I change pages, it's good, the badge `Camera in use` disappears
but if I launch the app from an android and change the page the green `Camera in use` badge is still there

**Comment by elcamin99** [comment]
Hello I have the same issue but for Android @byCedric if I launch the example snack you made from an iphone and I change pages, it's good, the badge disappears
but if I launch the app from an android and change the page the green badge is still there
