### ISSUE TITLE
SDK v25.0.0 ios build missing required iPad icon

### ISSUE THREAD

**Issue by carsonwah** [expo/expo#1309]
Error when uploading ipa via application loader:

<img width="637" alt="2018-01-23 18 01 44" src="https://user-images.githubusercontent.com/25053707/35269936-877acedc-0068-11e8-9181-c4c88621c342.png">

It did not appear back in SDK v24.0.0.

My app.json

```javascript
{
    ...
    "sdkVersion": "25.0.0",
    "icon": "./assets/icons/app.png",  // 1024x1024 png with alpha channel
    "packagerOpts": {
      "assetExts": ["ttf"]
    },
    "ios": {
      "icon": "./assets/icons/app_ios.png",  // 1024x1024 png without alpha channel
      "isRemoteJSEnabled": true,
      "loadJSInBackgroundExperimental": true,
      "supportsTablet": true,
    },
    ...
}
```

exp cli version: 48.0.2
application loader version: v3.7 (1034)

**Comment by carsonwah** [comment]
Just tested v24.0.0 build. It's the same situation. So I guess it is some bugs on the build server?

**Comment by sonaye** [comment]
Same here.
<img width="677" alt="screen shot 2018-01-23 at 4 18 14 pm" src="https://user-images.githubusercontent.com/23000873/35279205-70375d22-005d-11e8-8f20-94ebdafae73f.png">

**Comment by jtklein** [comment]
Same here:
Build id: `8e17d233-4897-4854-a85b-60d9c3fdcf1b`
Contents of the ipa:
![bildschirmfoto 2018-01-23 um 15 01 06](https://user-images.githubusercontent.com/17345891/35279895-bd80d7ca-004e-11e8-8ed2-7019f6258b00.png)

**Comment by namsu95** [comment]
I've just met exactly the same error messages as @carsonwah did.
Exp-cli version 48.0.2 and 47.3.17 showed me the same error. Expo sdk version is 24 and App loader is 3.7.

**Comment by terribleben** [comment]
Thanks for the report, I'm looking into this now.

**Comment by terribleben** [comment]
We are testing a tentative fix. If the testing succeeds then it will still be another couple hours before the fix reaches production.

It turns out that there are a lot of dumb things that can be misconfigured in xcode tooling which all have the same symptom (breaking compiled icon assets).

**Comment by jayeszee** [comment]
Its currently still broken :/ Is there an updated ETA?

**Comment by terribleben** [comment]
We deployed a fix in the last 20 minutes or so which includes the required icons. I'll leave this open until I get some independent verification that it's fixed for others.

**Comment by eduardoruocco** [comment]
Just uploaded a package to app store.
It's working now =)

**Comment by namsu95** [comment]
Now it works for testflight via application loader! thank you!

**Comment by dillonhafer** [comment]
I was able to build and two apps, looks to be working fine ❤️ Thanks for all the work you put into this

**Comment by carsonwah** [comment]
Seems fixed. Thanks for the hard work!

**Comment by terribleben** [comment]
Really sorry for the trouble. Glad it is working.

**Comment by allen6131** [comment]
i am still having this issue

**Comment by jakute** [comment]
I still have the same issue, 
Im using  Xcode Version 9.3 (9E145)
please help

**Comment by jojokinkaid** [comment]
Same issue

ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0."

trying upload with XCode ver. 9.3   By the way, I uploaded the 1024x1024 app icon at iTunes not via XCode.

**Comment by saiHemanthGitHub** [comment]
@terribleben i am getting this issue when trying to upload to app store,How to fix this.
![screen shot 2018-05-17 at 12 10 42 pm](https://user-images.githubusercontent.com/12952098/40160758-3b4a1bf4-59cc-11e8-9bd9-8094b8385c9e.png)

**Comment by D-Blazer** [comment]
i still have this issue, any update on it?
