### ISSUE TITLE
How to get expo-localization *short* locale? I mean, "en-US" and "en-UK" as "en", without having to manipulate the string.

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#13101]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by VictorioMolina** [comment]
This is my code:

`const { locale } = await Localization.getLocalizationAsync()`

**Comment by brentvatne** [comment]
do you mean this? https://docs.expo.io/versions/latest/sdk/localization/#localizationlocale

**Comment by VictorioMolina** [comment]
@brentvatne I solved it using regex. I just wanted to ignore the right part (-MX, -ES, ...), only taking the left one "es".
