### ISSUE TITLE
Error logging with Facebook Expo After Facebook Android App Update

### ISSUE THREAD

**Issue by emrahc** [expo/expo#13105]
### Summary

After last updates of official Facebook App can't login. Facebook lite or previous versions works fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.5.0 environment info:
    System:
      OS: Linux 5.10 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.1.0 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 7.15.0 - /usr/bin/npm
    npmPackages:
      expo: ^41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Try to login with latest expo-facebook package and latest facebook android app.

**Comment by ursNj** [comment]
Same issue, its blocking productions apps.

getting `Error: An error occurred while trying to log in to Facebook` while logging in.

**Comment by brentvatne** [comment]
please contact facebook support

**Comment by lowiebenoot** [comment]
I'm having the same issue. Also found this on the expo forum from a little while ago.

https://forums.expo.io/t/an-error-occurred-while-trying-to-log-in-to-facebook/50785

**Comment by YahyaBagia** [comment]
Same here. Someone found any solution?

**Comment by NounViraneath** [comment]
I have similar problem with Android (bare app).
expo-facebook return 100% Error
`Error: An error occurred while trying to log in to Facebook`
at the first time with FB login,
but succeed after second time...

Possible to reproduce this again by deleting the APP from my facebook.

 "expo": "~41.0.1",
 "expo-facebook": "~11.0.5",

**Comment by AurelienFT** [comment]
I have the same problem in loop.

"expo": "~41.0.1",
"expo-facebook": "~11.0.5",

**Comment by JelHe** [comment]
Hello, our sentry started catch the same error for some Android users. (Can't reproduce this error by myself)
    "expo": "^41.0.0",
    "expo-facebook": "~11.0.5",

**Message**: `An error occurred while trying to log in to Facebook `
**Code**: `ERR_FACEBOOK_LOGIN`

**Full error**:
`{"nativeStackAndroid":[{"lineNumber":11,"file":"LoginManager.java","methodName":"onActivityResult","class":"com.facebook.login.LoginManager"},{"lineNumber":1,"file":"LoginManager.java","methodName":"onActivityResult","class":"com.facebook.login.LoginManager$1"},{"lineNumber":2,"file":"CallbackManagerImpl.java","methodName":"onActivityResult","class":"com.facebook.internal.CallbackManagerImpl"},{"lineNumber":1,"file":"FacebookModule.java","methodName":"onActivityResult","class":"expo.modules.facebook.FacebookModule"},{"lineNumber":2,"file":"ScopedUIManagerModuleWrapper.java","methodName":"onActivityResult","class":"versioned.host.exp.exponent.modules.universal.ScopedUIManagerModuleWrapper"},{"lineNumber":2,"file":"Exponent.java","methodName":"q","class":"i.a.a.b"},{"lineNumber":2,"file":"ReactNativeActivity.java","methodName":"onActivityResult","class":"host.exp.exponent.experience.v"},{"lineNumber":8541,"file":"Activity.java","methodName":"dispatchActivityResult","class":"android.app.Activity"},{"lineNumber":5499,"file":"ActivityThread.java","methodName":"deliverResults","class":"android.app.ActivityThread"},{"lineNumber":5547,"file":"ActivityThread.java","methodName":"handleSendResult","class":"android.app.ActivityThread"},{"lineNumber":51,"file":"ActivityResultItem.java","methodName":"execute","class":"android.app.servertransaction.ActivityResultItem"},{"lineNumber":135,"file":"TransactionExecutor.java","methodName":"executeCallbacks","class":"android.app.servertransaction.TransactionExecutor"},{"lineNumber":95,"file":"TransactionExecutor.java","methodName":"execute","class":"android.app.servertransaction.TransactionExecutor"},{"lineNumber":2307,"file":"ActivityThread.java","methodName":"handleMessage","class":"android.app.ActivityThread$H"},{"lineNumber":106,"file":"Handler.java","methodName":"dispatchMessage","class":"android.os.Handler"},{"lineNumber":246,"file":"Looper.java","methodName":"loop","class":"android.os.Looper"},{"lineNumber":8512,"file":"ActivityThread.java","methodName":"main","class":"android.app.ActivityThread"},{"lineNumber":-2,"file":"Method.java","methodName":"invoke","class":"java.lang.reflect.Method"},{"lineNumber":602,"file":"RuntimeInit.java","methodName":"run","class":"com.android.internal.os.RuntimeInit$MethodAndArgsCaller"},{"lineNumber":1130,"file":"ZygoteInit.java","methodName":"main","class":"com.android.internal.os.ZygoteInit"}]`

Do you have any ideas what gone wrong? Everything was good with the same code until 2021-05-27.

**Comment by meenabassem** [comment]
> I have the same problem in loop.
> 
> "expo": "~41.0.1",
> "expo-facebook": "~11.0.5",

Same here with same versions
the example from the docs works as expected in iOS, doesn't even open browser in android and returns that same error code.
