### ISSUE TITLE
request to https://registry.npmjs.org/expo-template-blank-typescript failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by cracktechnicalinterview** [expo/expo#13102]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by byCedric** [comment]
Hi @cracktechnicalinterview! It seems like this could be a transient error and is related to NPM. I can open [`https://registry.npmjs.org/expo-template-blank-typescript`](https://registry.npmjs.org/expo-template-blank-typescript) without issues, showing the JSON registry data.
