### ISSUE TITLE
expo-camera / expo-barcode-scanner : different behaviours between iOS and Android

### ISSUE THREAD

**Issue by Thibaut-Fatus** [expo/expo#13115]
### Summary

On android, expo-barcode-scanner will detect a barcode anywhere in the frame, versus on iOS it seems to be only on the center of the screen (which is not super specific I must admit)

This still holds if we force the focus by clicking on the part of the screen where the barcode is visible.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

0.41

### Environment

standard snack

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@thibaut-fatus/tactless-ramen

**Comment by byCedric** [comment]
Hi @Thibaut-Fatus! I can't seem to reproduce this on an iPhone 12 pro. On all edges (top-left, top-right, bottom-left, bottom-right) it scans the QR code immediately. What type of device are you using, it could be something hardware-related where the camera quality isn't enough for the barcode algorithm to recognize it.

**Comment by Thibaut-Fatus** [comment]
I tried on an iPhone SE first gen, an iPhone X, and an iPhone 8. All had the same issue

**Comment by Thibaut-Fatus** [comment]
I can try with more phones and give you a list of iPhone model / iOS version which reproduce the issue if needed

**Comment by filiptronicek** [comment]
@Thibaut-Fatus Can't it be version specific? What iOS version have you tried this on?
