### ISSUE TITLE
jest-expo-enzyme - TypeError: window.matchMedia is not a function

### ISSUE THREAD

**Issue by busticated** [expo/expo#13111]
### Summary

using a newly initialized project created with the `blank (TypeScript)    same as blank but with TypeScript configuration` option and with the `jest-expo-enzyme` ([source](https://github.com/expo/expo/tree/master/packages/jest-expo-enzyme)) preset installed, i see the following when trying to run tests:

```
FAIL Web src/components/type/title.test.web.tsx
  ● Test suite failed to run

    TypeError: window.matchMedia is not a function

      at Object.<anonymous> (node_modules/react-native-web/dist/cjs/exports/AccessibilityInfo/index.js:22:74)
      at Object.<anonymous> (node_modules/react-native-web/dist/cjs/index.js:30:49)
      at Object.<anonymous> (node_modules/jest-expo-enzyme/src/serializer.ts:2:1)
      at Object.<anonymous> (node_modules/jest-expo-enzyme/src/setupEnzyme.web.ts:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.153s
Ran all test suites.
```

i tried to mock out the `matchMedia` function using Jest's instructions here:

https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom

...but that doesn't help. i tried both manually importing the mock in my test file as well as loading it via `setupFiles` option in my `jest.config.js` file. as best i can tell, the file is never loaded in either case. more notably, my `title.test.web.tsx` doesn't appear to execute as i'm able to replace its content with gibberish (e.g. `lolnope!`) and i still get the same error about `window.matchMedia`. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41.0.1

### Environment

```
  Expo CLI 4.4.7 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.22.1 - /var/folders/c7/369898450l31qzjh1qrf9x7w0000gn/T/fnm_multishells/1168_1619999818927/bin/node
      npm: 6.14.12 - /var/folders/c7/369898450l31qzjh1qrf9x7w0000gn/T/fnm_multishells/1168_1619999818927/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. run `expo init <path/to/directory> --npm --name test`
2. select the `blank (TypeScript)    same as blank but with TypeScript configuration` option and continue
3. install test dependencies: `npm i jest jest-expo-enzyme --save-dev`
4. in the root of your new project, create a `jest.config.js` file with:

```
const { withEnzyme } = require('jest-expo-enzyme');


module.exports = {
	preset: 'jest-expo-enzyme',
	projects: [
		withEnzyme(require('jest-expo/ios/jest-preset')),
		withEnzyme(require('jest-expo/android/jest-preset')),
		withEnzyme(require('jest-expo/web/jest-preset'))
	],
	setupFiles: [
		'<rootDir>/src/__mocks__/match-media.js'
	]
};
```

5. as described [here](https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom), create the `<rootDir>/src/__mocks__/match-media.js` with:

```js
Object.defineProperty(window, 'matchMedia', {
	writable: true,
	value: jest.fn().mockImplementation(query => ({
		matches: false,
		media: query,
		onchange: null,
		addListener: jest.fn(), // deprecated
		removeListener: jest.fn(), // deprecated
		addEventListener: jest.fn(),
		removeEventListener: jest.fn(),
		dispatchEvent: jest.fn()
	}))
});
```

6. create a test file with the `.test.web.tsx` extension anywhere within the `<rootDir>` with:

```js
it('works', () => {
  expect(1).toBe(1);
});
```

7. run your tests with `jest`

**Comment by olayemii** [comment]
@busticated  did you fix this?
