### ISSUE TITLE
expo-firebase-analytics 4.0.2 not work in stand alone android

### ISSUE THREAD

**Issue by aioia** [expo/expo#13116]
### Summary

I upgraded expo sdk and expo-firebase-analytics packages, then my app can not send analytics data in android stand alone app. It's only android stand alone app. It's work at iOS and web.
I have not changed send code before and after upgrade.

before
expo sdk 40
expo-firebase-analytics:@~2.6.0

after
expo sdk 41
expo-firebase-analytics@~4.0.2

send code
`Analytics.logEvent(_eventName, _properties)`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

stand alone app (expo build:android)

app.config.ts
```
ios: {
...
        googleServicesFile: "GoogleService-Info.plist"
      },
      android: {
...
        googleServicesFile: "google-services.json"
      },
```

### Reproducible demo or steps to reproduce from a blank project

upgrade packages
```
expo sdk 41
expo-firebase-analytics@~4.0.2
```
release
`expo build:android`

check firebase analytics

**Comment by byCedric** [comment]
Hi @aioia! I'm not sure if I understand your local setup. If you are using bare, you can't use `expo build:android`, you either have to build it yourself or use EAS. Could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (without keys) for us to test?

**Comment by aioia** [comment]
OK. I will check it in minimal reproducible example. Then I will come back here.

By the way, 
> If you are using bare, you can't use expo build:android, you either have to build it yourself or use EAS.
I can use "expo build:android --release-channel xxx" still. I can release app store and play store.
SDK is upgraded for 41, and my project have ios/ and android/ directories. Terminal is written "bare" when I use "expo build". 
Is that bug?

Thank you, I use EAS from now for build.

**Comment by IjzerenHein** [comment]
Closing this issue as this appears resolved. Feel free to reopen with additional info if this is still a problem
