### ISSUE TITLE
EAS - APK builds crash in views that use the "react-native-picker-select" package.

### ISSUE THREAD

**Issue by Momoske** [expo/expo#13127]
### Summary

While developing, views using the `react-native-picker-select` package work perfectly fine, and building the app using expo:build also doesn't crash the app.

However, building using `eas build -p android --profile preview` (preview profile having "apk" as buildType) makes the app crash in any view that uses this package. I use multiple pickers throughout my app, and this happens in each of these views, so this should be really easy to reproduce.

Attached below is a screen recording of the issue in action, showing the same app built with expo:build first then using EAS.

https://user-images.githubusercontent.com/27915933/120500861-72610f00-c3c1-11eb-8632-01391fe56d27.mp4

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Really easy steps to reproduce:

- Create a new blank managed expo project using expo init
- Add the `react-native-picker-select` package to the project
- Replace the existing code inside App.js with the code from this snack: https://snack.expo.io/@suposcar/033b23
- Build using `eas -p android --profile preview` (following the docs for an APK build)

Snack built using eas can be downloaded from here if needed: https://turtle-v2-artifacts.s3.amazonaws.com/android/66d077e3-ea5b-490e-ade8-89604051548d-b61543ce82be46ea90c16de69e4268c3.apk
Logs collected by Android on app crash: https://del.dog/ghethunalo.txt

**Comment by brentvatne** [comment]
hi there! this sounds like a bug in the package itself. you can try to reproduce it locally by running `expo run:android` - this will run `expo prebuild` to generate the android and ios directories and then do a build. you can then debug further to see what the crash comes from. we do not do anything special with this package, it works exactly the same with eas build as it would with any react native app.

**Comment by leonelVc19** [comment]
Hi, I have this problem, 
```
Android Bundling failed 3879ms
Unable to resolve "prop-types" from "node_modules\react-native-picker-select\src\index.js"
```

**Comment by cleicastro** [comment]
I have this problem

<img width="882" alt="image" src="https://user-images.githubusercontent.com/50046577/211424199-7c4dd37a-6db0-49a2-9c2c-acaaea578eef.png">
