### ISSUE TITLE
[SDK v25.0.0 Upgrade] Unknown named module: 'react'

### ISSUE THREAD

**Issue by onrige** [expo/expo#1312]
Hello. After upgrading to new sdk version I am getting this error. May be I am missed something? I was upgrading according to the tutorial.

<img width="1280" alt="screen shot 2018-01-23 at 20 32 47" src="https://user-images.githubusercontent.com/14055801/35291035-1eec0786-007d-11e8-88e2-2cad5c9cbabb.png">

Here is my package.json:
```
{
    "@expo/vector-icons": "^6.1.0",
    "axios": "^0.17.0",
    "entities": "^1.1.1",
    "expo": "^25.0.0",
    "expo-analytics": "^1.0.6",
    "immutability-helper": "^2.5.1",
    "lodash": "^4.17.4",
    "native-base": "2.3.1",
    "prop-types": "^15.6.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-dropdownalert": "^3.1.2",
    "react-native-htmlview": "^0.12.1",
    "react-native-image-carousel": "^0.4.4",
    "react-native-image-progress": "^1.0.1",
    "react-native-router-flux": "file:../../open-source/react-native-router-flux/last-react-navigation.tgz",
    "react-native-star-rating": "^1.0.8",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-actions": "^2.2.1",
    "redux-devtools-extension": "^2.13.2",
    "redux-form": "^7.2.0",
    "redux-persist": "^4.10.1",
    "redux-persist-transform-filter": "^0.0.16",
    "redux-saga": "^0.16.0",
    "redux-saga-routines": "^2.2.1",
    "sentry-expo": "~1.7.0"
  }
```

Thanks

**Comment by aulneau** [comment]
I am also having this error.

**Comment by nikki93** [comment]
Try deleting your `node_modules/` directory and installing again (with `npm i` or `yarn`, whichever one you use). Make sure the `react/` directory exists inside `node_modules/`.

**Comment by aulneau** [comment]
@nikki93 Yep -- I have checked that and also removed both `node_modules` and `.expo` to clear everything, but the error persists, I have since reverted to sdk 24

**Comment by nikki93** [comment]
Do new Expo projects (created with, say, `exp init`) work for you?

**Comment by onrige** [comment]
@nikki93 yep
@aulneau did you resolve this issue?

**Comment by onrige** [comment]
Fine. So this is the problem of babel plugin for hot reloading functional components I think. If someone in future will have the same problem - just remove `functional-hmr` plugin from `.babelrc` file. There is a [issue](https://github.com/bvic23/babel-plugin-functional-hmr/issues/9) in plugin repository, so I am closing this one because of it.
