### ISSUE TITLE
[docs] TypeScript: Align docs, template and tsconfig.base.json

### ISSUE THREAD

**Issue by rhoehener** [expo/expo#13141]
### Summary

- create a new project with `expo init . --template expo-template-blank-typescript`
- observe tsconfig.json: it extends [expo/tsconfig.base](https://github.com/expo/expo/blob/master/packages/expo-module-scripts/tsconfig.base.json)
- observe: tsconfig.base: it does not align well with the [TypeScript docs](https://docs.expo.io/guides/typescript/)
- casing for things like ESNext: https://www.typescriptlang.org/tsconfig

![screenshot](https://user-images.githubusercontent.com/13407181/120623919-74c67600-c460-11eb-962c-5b8e38c4578c.png)

### Link to the related docs page

https://docs.expo.io/guides/typescript/

**Comment by rhoehener** [comment]
the change from react-native to react: https://github.com/expo/expo/commit/6993d56a3fc3faa2e3078414c6b326bdf112b8ba#diff-597dea204bec53211242c5a7c69bf2ab9738d74858ef6ca4edcece388174f631

**Comment by byCedric** [comment]
Hi @rhoehener! Thanks for the detailed dissection of this! First up, I think you confusing `expo-module-scripts` for `expo`. The typescript config it expends from is [`expo/tsconfig.base.json`](https://github.com/expo/expo/blob/master/packages/expo/tsconfig.base.json), not [`expo-module-scripts/tsconfig.base.json`](https://github.com/expo/expo/blob/master/packages/expo-module-scripts/tsconfig.base.json). We use the `expo-module-scripts` package internally for each individual modules, some of them including basic React code (hence the `jsx` is set to `react`).

If I compare the docs vs the `expo/tsconfig.base.json`, it's pretty well synced:

```
"compilerOptions": {
  "allowJs": true,
  "esModuleInterop": true,
  "jsx": "react-native",
  "lib": ["DOM", "ESNext"],
  "moduleResolution": "node",
  "noEmit": true,
  "resolveJsonModule": true,
  "skipLibCheck": true,
  "target": "ESNext"
},
```

Hope this helps!

**Comment by rhoehener** [comment]
@byCedric Indeed, I must have picked the first Google result in the expo project... embarassing.

Thanks for clearing that up. And yes, that file is perfectly in sync with the docs!

**Comment by byCedric** [comment]
No worries! It's still a good dissection and always good to validate 😬
