### ISSUE TITLE
Constants.statusBarHeight wrong in Android sdk 25, (24, should be 0) 

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1314]
I noticed some funkiness when I upgraded react navigation and realized it's because react navigation checks Expo.Constants.statusBarHeight for the statusbar height, and it's returning 24 (it should be 0 for android, right?).

**Comment by carsonwah** [comment]
Are you using react-navigation v1.0.0-beta.26? @brentvatne had some [breaking change](https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.26) to fix this [very old issue](https://github.com/react-navigation/react-navigation/issues/12). Maybe you should be remove any padding or height workaround that depends on status bar height.

**Comment by JulianKingman** [comment]
I'm using beta 27, per the [upgrade guide](https://blog.expo.io/expo-sdk-v25-0-0-is-now-available-714d10a8c3f7).

**Comment by carsonwah** [comment]
Since the breaking change in v1.0.0-beta.26 (above link), it should be normal to have statusBarHeight===24 on Android. react-navigation should be able to handle the padding for you. So your code should not have any padding in the header anymore.

**Comment by rubensbarreto** [comment]
Same issue here, our app doesn't have any padding in the header, never had, after upgrading to Expo 25 and React navigation v1.0.0-beta.27, per the upgrade guide, it nows shows an extra space at the top, only on android.

![android](https://user-images.githubusercontent.com/9420303/35597621-9bc5f97c-0606-11e8-8e17-9c30a212fe73.jpeg)

IOS is working normally.

![ios](https://user-images.githubusercontent.com/9420303/35597660-c6ec243c-0606-11e8-86e2-ee5ee51da74a.jpg)

**Comment by terribleben** [comment]
Hi, if you are using react-navigation beta-27, and want to revert to the old behavior, there is an escape hatch code snippet given [here](https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.26).

```js
import { Platform } from 'react-native';
import { SafeAreaView } from 'react-navigation';
if (Platform.OS === 'android') {
  SafeAreaView.setStatusBarHeight(0);
}
```

cc @brentvatne

**Comment by AdamJNavarro** [comment]
Hey @JulianKingman,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
