### ISSUE TITLE
How to remove the background color of the keyboard？

### ISSUE THREAD

**Issue by fungmo** [expo/expo#13156]
### Summary

![image](https://user-images.githubusercontent.com/16655229/120775817-25627180-c556-11eb-8809-1e6bc5e0d7cc.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

```base
Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.3
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

![image](https://user-images.githubusercontent.com/16655229/120776020-5cd11e00-c556-11eb-80e5-45d40b1c6b54.png)

**Comment by byCedric** [comment]
Hi @fungmo, this heavily ties into Android and what type of keyboard the user has. Some keyboards are rendered on top of the app, but most are "cutting the app". [You might get this working by using the method described in this SO thread](https://stackoverflow.com/questions/17978277/making-the-keyboardview-transparent).

Hope this helps!

**Comment by fungmo** [comment]
@byCedric 
Many Thx Cedric
