### ISSUE TITLE
Why is still applying for focus while playing

### ISSUE THREAD

**Issue by codthing** [expo/expo#13155]
### Summary

On the android8.1 platform. After testing, expo-video-player preempts the audio focus of online music playback, causing the music player to pause. Because the audio focus of the music application is quickly preempted by the video, the music loses the audio focus and stops (this focus is preempted because after the voice pop-up box disappears, the current video returns to the foreground and seizes the audio focus, causing the music to lose the audio focus)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

```base
Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.3
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

**To Reproduce**
1. Play video
2. Voice "I want to listen to music"
3. The voice pop-up window "music is about to play", the music is paused after playing for one second

**Expected behavior**
Voice pop-up window "music will be played soon", and music can be played

**Comment by byCedric** [comment]
Hi @fungmo, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for us to work with. Without that, we can't help investigating this issue.

**Comment by fungmo** [comment]
@byCedric 
I'm very sorry, I can only control my own code, this is the result of the evaluation of the platform system. If you need a video scene, maybe I can provide it. To illustrate, I just used expo-video-player very simply, and did not use it destructively. I don't know why this happens.
