### ISSUE TITLE
[docs] expo-updates: removing from project

### ISSUE THREAD

**Issue by justrealmilk** [expo/expo#13167]
### Summary

Instructions for removing expo-updates from project are out of date and result in a broken project.

### Link to the related docs page

https://github.com/expo/expo/blob/master/packages/expo-updates/README.md

**Comment by AdamJNavarro** [comment]
Hey @justrealmilk, can you provide more information? What does a broken project mean? Does this occur on iOS, Android, both?

Cheers,
Adam

**Comment by justrealmilk** [comment]
Broken project as in it will no longer successfully compile!

This is for iOS and building with XCode. I don't know why I didn't post with more error details. I'll fix that.
