### ISSUE TITLE
Jest bug with expo when using another dependency such as @shoutem

### ISSUE THREAD

**Issue by archywilhes** [expo/expo#1316]
Version:

```
 "expo": {
    "sdkVersion": "25.0.0"
  }
```

Jest Test always failed with syntax error 
```
  /Users/a/ArchyBox/lateJan/Archy/node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){


SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
      at Object.<anonymous> (node_modules/@expo/vector-icons/MaterialIcons.js:4:64)
      at Object.<anonymous> (node_modules/@shoutem/ui/components/ImagePreview.js:10:20)
```

Current config for `jest` ("jest-expo": "25.0.0")

```
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
          "node_modules/(?!react-native|expo|@expo|react-navigation|native-base-shoutem-theme|@shoutem/theme|@shoutem/animation|@shoutem/ui|tcomb-form-native)"
    ]
  },
````

Runs fine without third party dependency `@shotem`. Error only arises when added `@shotem` and `"transformIgnorePatterns"`.

**Comment by archywilhes** [comment]
https://github.com/facebook/jest/issues/5381

**Comment by archywilhes** [comment]
related: https://github.com/shoutem/ui/issues/151

**Comment by archywilhes** [comment]
Here is a repo documenting the bug: https://github.com/archywilhes/IntegrationBugWithExpoAndJestAndThirdPartyReactNativeDependencies

**Comment by ide** [comment]
Merging this into another issue for what appears to be the same bug: https://github.com/expo/expo/issues/1317

**Comment by brentvatne** [comment]
try out `jest-expo@25.1.0-beta.0` and let me know if it resolves your problem
