### ISSUE TITLE
expo-facebook - iOS installation

### ISSUE THREAD

**Issue by stharvey** [expo/expo#13169]
### Summary

I am trying to install expo-facebook on my bare workflow app so that it can use Facebook login for authorization.  This is working without any problem on Android however I am struggling to get it to work on iOS.

I have found the installation instructions a little confusing.  On this page: https://docs.expo.io/versions/latest/sdk/facebook/ there is a section which links to "iOS Installation Walkthrough" - https://developers.facebook.com/docs/ios/getting-started/

However when I import https://github.com/facebook/facebook-ios-sdk into Swift Packages I get a build error: 

> Redefinition of module 'FBSDKCoreKit' error

If I don't perform the steps on that page I get a runtime error:

> NSException *	"*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]"

I realise that I must be doing something wrong but I don't find the installation documents are entirely clear.

Thanks.

### Link to the related docs page

https://docs.expo.io/versions/latest/sdk/facebook/

**Comment by cruzach** [comment]
Sorry, that should link to https://developers.facebook.com/docs/ios/getting-started/#step-3---configure-your-project. Updating the docs now

**Comment by cruzach** [comment]
fixed in https://github.com/expo/expo/commit/262065cd89f3c32281da0f4ee25f87fae10c416e
