### ISSUE TITLE
addNotificationReceivedListener is not fired

### ISSUE THREAD

**Issue by tgxn** [expo/expo#13170]
### Summary

Using Snack https://snack.expo.io/@charliecruzan/push-notifications on Android expo go client,

Reproduce:
- Load Snack on Device _(don't use the button that calls `scheduleNotificationAsync` in the snack; that **does** work)_
- Copy token from console to [tester](https://expo.io/notifications), adding `title` and `body`, send.
- Notice notification is received however the page content is never updated
![image](https://user-images.githubusercontent.com/293107/120894139-86b73d00-c649-11eb-801f-19681acafa80.png)

Additionally, `addNotificationResponseReceivedListener` is not fired when the notification is tapped.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

Snack is on 40.0.0 (problem present)

41 tested and found Android has [this issue](https://github.com/expo/expo/issues/12833) so unable to validate.

### Environment

Android / Snack

### Reproducible demo or steps to reproduce from a blank project

as above

**Comment by FelipeACP** [comment]
Do you have "useNextNotificationsApi": true in your app.json?

**Comment by tgxn** [comment]
@FelipeACP As I said, [I'm using Snack which does not have access to `app.json`.](https://forums.expo.io/t/can-not-see-app-json-file/17357)

Looking at the documentation anyway, [`android.useNextNotificationsApi`](https://docs.expo.io/versions/latest/config/app/#usenextnotificationsapi) indicates very little about what it does, stating only  _"A Boolean value that indicates whether the app should use the new notifications API."_

I have downloaded the linked Snack and opened locally in VS Code, to test your theory, _(this is not my issue - my issue is present in Snack)_ Downloading the project and setting this "useNextNotificationsApi" property seems to work.

**Comment by cruzach** [comment]
As we state in the [docs for SDK 40 (which you are using)](https://docs.expo.io/versions/v40.0.0/sdk/notifications/):

> Note that the snack will not work with remote notifications (sent via the Expo Notifications service) on Android when you run it from the snack, because app.json needs to contain the useNextNotificationsApi flag. Unfortunately, Snack doesn't support custom app.json files.

**Comment by rosnaib11** [comment]
Why they keep closing this issue. Until now it doesn't work!
