### ISSUE TITLE
Unhandled Rejection (TypeError): _ExponentCameraManager__WEBPACK_IMPORTED_MODULE_13__.default.requestPermissionsAsync is not a function

### ISSUE THREAD

**Issue by lopeselio** [expo/expo#13179]
### Summary

Unhandled Rejection (TypeError): _ExponentCameraManager__WEBPACK_IMPORTED_MODULE_13__.default.requestPermissionsAsync is not a function

![image](https://user-images.githubusercontent.com/43913734/120916643-6da1a100-c6c8-11eb-8985-b2bc0f870193.png)

# Upon clicking camera button to open camera, i am encountered with this error

![image](https://user-images.githubusercontent.com/43913734/120916691-a2155d00-c6c8-11eb-804c-293d1ae2c33d.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, Web

### SDK Version (managed workflow only)

~40.0.0

### Environment

Expo CLI 4.3.4 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.22.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.12 - /usr/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

**Here I am trying to open camera using the piece of code, Packages used are expo camera and expo image picker**
[Linkt to the repo](https://github.com/lopeselio/Spike-RN/blob/main/components/main/Add.js)

```
import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, Button, Image } from 'react-native';
import { Camera } from 'expo-camera';
import * as ImagePicker from 'expo-image-picker';


export default function Add({ navigation }) {
  const [hasGalleryPermission, setHasGalleryPermission] = useState(null);
  const [hasCameraPermission, setHasCameraPermission] = useState(null);
  const [camera, setCamera] = useState(null);
  const [image, setImage] = useState(null);
  const [type, setType] = useState(Camera.Constants.Type.back);

  useEffect(() => {
    (async () => {
      const cameraStatus = await Camera.requestPermissionsAsync();
      setHasCameraPermission(cameraStatus.status === 'granted');

      const galleryStatus = await ImagePicker.requestCameraRollPermissionsAsync();
      setHasGalleryPermission(galleryStatus.status === 'granted');


    })();
  }, []);

  const takePicture = async () => {
    if (camera) {
      const data = await camera.takePictureAsync(null);
      setImage(data.uri);
    }
  }

  const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      aspect: [1, 1],
      quality: 1,
    });
    console.log(result);

    if (!result.cancelled) {
      setImage(result.uri);
    }
  };


  if (hasCameraPermission === null || hasGalleryPermission === false) {
    return <View />;
  }
  if (hasCameraPermission === false || hasGalleryPermission === false) {
    return <Text>No access to camera</Text>;
  }
  return (
    <View style={{ flex: 1 }}>
      <View style={styles.cameraContainer}>
        <Camera
          ref={ref => setCamera(ref)}
          style={styles.fixedRatio}
          type={type}
          ratio={'1:1'} />
      </View>

      <Button
        title="Flip Image"
        onPress={() => {
          setType(
            type === Camera.Constants.Type.back
              ? Camera.Constants.Type.front
              : Camera.Constants.Type.back
          );
        }}>
      </Button>
      <Button title="Take Picture" onPress={() => takePicture()} />
      <Button title="Pick Image From Gallery" onPress={() => pickImage()} />
      <Button title="Save" onPress={() => navigation.navigate('Save', { image })} />
      {image && <Image source={{ uri: image }} style={{ flex: 1 }} />}
    </View>
  );
}

const styles = StyleSheet.create({
  cameraContainer: {
    flex: 1,
    flexDirection: 'row'
  },
  fixedRatio: {
    flex: 1,
    aspectRatio: 1
  }

})

```

![image](https://user-images.githubusercontent.com/43913734/120916643-6da1a100-c6c8-11eb-8985-b2bc0f870193.png)

![image](https://user-images.githubusercontent.com/43913734/120916691-a2155d00-c6c8-11eb-804c-293d1ae2c33d.png)

**Comment by AdamJNavarro** [comment]
Hey @lopeselio, the repo you linked to leads to a 404. Can you provide an updated repo? Also, can you try adding a safety check with your Camera by calling `isAvailableAsync`? See [here](https://docs.expo.io/versions/v41.0.0/sdk/camera/#cameraisavailableasync-boolean).

Cheers,
Adam

**Comment by alexander01202** [comment]
Hello? How did you solve this?
