### ISSUE TITLE
React Native version mismatch

### ISSUE THREAD

**Issue by judsonkerller** [expo/expo#13172]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by judsonkerller** [comment]
How i fix that?

![image](https://user-images.githubusercontent.com/44353658/120901196-bea18e80-c60f-11eb-815c-8974e88f9e58.png)

![image](https://user-images.githubusercontent.com/44353658/120901207-d0833180-c60f-11eb-960d-548ef2bf5163.png)

**Comment by cruzach** [comment]
https://docs.expo.io/troubleshooting/react-native-version-mismatch/
