### ISSUE TITLE
ScreenOrientation.lockAsync doesn't work on ios tablet

### ISSUE THREAD

**Issue by sergeu90** [expo/expo#13184]
### Summary

` ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE);`

 Not working on the ios tablet(work on iphone but tablet not)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

sdk-40.0.1

### Environment

```
 Expo CLI 4.4.8 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3, 31.0.0, 31.0.0
        System Images: android-24 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.12.76 => 0.12.76 
      expo: 41.0.1 => 41.0.1 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: 0.16.3 => 0.16.3 
      expo-screen-orientation: "3.1.0"
    npmGlobalPackages:
      expo-cli: 4.4.4
    Expo Workflow: managed


```

### Reproducible demo or steps to reproduce from a blank project

`ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE);`

and  if set in app.json `"orientation": 'landscape'` only work for iphone not ipad.

After this call method not apply for the ios tablet.

**Comment by AdamJNavarro** [comment]
Hey @sergeu90, please read this [section](https://docs.expo.io/versions/v41.0.0/sdk/screen-orientation/#warning) of the docs.

Cheers,
Adam

**Comment by sergeu90** [comment]
@AdamJNavarro  I read this section and tried and not successfuly. 
Can we explain how it works. I think it is not working solution

**Comment by lewis221** [comment]
i have the same issue, it's not working
