### ISSUE TITLE
Unhandled Rejection (Error): The method or property expo-file-system.getInfoAsync is not available on web, are you sure you've linked all the native dependencies properly?

### ISSUE THREAD

**Issue by adarshkhatri** [expo/expo#13181]
### Summary

Trying to find the SQLite database file in my expo and react native project.

However `FileSystem.getInfoAsync` is throwing this error:

> Unhandled Rejection (Error): The method or property expo-file-system.getInfoAsync is not available on web, are you sure you've linked all the native dependencies properly?

I have the `SQLite` database like this and it works:

      import * as SQLite from 'expo-sqlite';
      import * as FileSystem from 'expo-file-system';

      const dbName = 'my_db.db'; 
      const db = SQLite.openDatabase(dbName); //db exist, I can run SQL functions

        console.log(FileSystem.cacheDirectory); //is null
        console.log(FileSystem.documentDirectory); //is null

        console.log(FileSystem.getInfoAsync('SQLite/')); //throws the above error

PS I do see ` "expo-file-system": "^11.0.2",` `in my package.json file`. I had install `expo-file-system` via npm. 

What am I doing?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### Environment

Expo CLI 4.4.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      npm: 6.14.6 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.1 => 41.0.1 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ^0.63.0 => 0.63.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 4.4.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Simply install `npm i expo-file-system` and `npm i expo-sqlite`  and add this code in to your project:

```
const dbName = 'my_db.db';
const db = SQLite.openDatabase(dbName);
console.log(FileSystem.cacheDirectory);
console.log(FileSystem.documentDirectory);
```

**Comment by AdamJNavarro** [comment]
Hey @adarshkhatri, this is expected behavior as the `FileSystem` module does not have web support. Please see the Platform Compatibility table below the flow chart [here](https://docs.expo.io/versions/v41.0.0/sdk/filesystem/).

Cheers,
Adam
