### ISSUE TITLE
Unhandled Rejection (TypeError): track.getCapabilities is not a function on Mozilla Firefox

### ISSUE THREAD

**Issue by lopeselio** [expo/expo#13182]
### Summary

**I am trying to access the camera on React Native Web on Chrome and Firefox**
I am using the code from the official Expo documentation here [expo camera](https://docs.expo.io/versions/latest/sdk/camera/)
### I've noticed that On Firefox I am encountering this error:
![image](https://user-images.githubusercontent.com/43913734/120918612-ddb52480-c6d2-11eb-80ad-14d60e307111.png)

Whereas, the same code works completely fine on Chrome as shown below:
![image](https://user-images.githubusercontent.com/43913734/120918653-1523d100-c6d3-11eb-8fca-99bf8b52c0b2.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, Web

### SDK Version (managed workflow only)

^41.0.0

### Environment

Expo CLI 4.3.4 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.22.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.12 - /usr/bin/npm
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Code used 
Also available on snack [code here](https://snack.expo.io/@lion_17/basic-camera-usage)
```
import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { Camera } from 'expo-camera';

export default function App() {
  const [hasPermission, setHasPermission] = useState(null);
  const [type, setType] = useState(Camera.Constants.Type.back);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (hasPermission === null) {
    return <View />;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }
  return (
    <View>
      <Camera type={type}>
        <View>
          <TouchableOpacity
            
            onPress={() => {
              setType(
                type === Camera.Constants.Type.back
                  ? Camera.Constants.Type.front
                  : Camera.Constants.Type.back
              );
            }}>
            <Text> Flip </Text>
          </TouchableOpacity>
        </View>
      </Camera>
    </View>
  );
}

```

**Comment by AdamJNavarro** [comment]
Hey @lopeselio, this is expected behavior. See [here](https://caniuse.com/mdn-api_mediastreamtrack_getcapabilities)

**Comment by CJMcGregor** [comment]
@AdamJNavarro would it be possible to instead check if the "getCapabilities" method exists before calling it?  When developing in Firefox this is problematic because the error is thrown and then the UI freezes

**Comment by fmendez89** [comment]
@CJMcGregor  Yes, is quite annoying getting the "Uncaught Error" every time the cam appears.

**Comment by teckel12** [comment]
@AdamJNavarro The fact that it's not implimented doesn't mean it's expected behavior.  What's expected is that getCapabilities() would work like it does in every other browser.
