### ISSUE TITLE
[Expo Scanner] BarCodeScanner.scanFromURLAsync not working

### ISSUE THREAD

**Issue by thanhchuongbmd** [expo/expo#13199]
### Summary

when I using that method, it throw error "Error: Encountered an exception while calling native method: Exception occurred while executing exported method scanFromURLAsync on module ExpoBarCodeScannerModule: Attempt to invoke virtual method 'int java.lang.Double.intValue()' on a null object reference"

`const resultRead = await BarCodeScanner.scanFromURLAsync(
          result.uri, //uri from image picker or url from web, all of them are fail
        );
`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

 Expo CLI 4.5.0 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.4 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.15.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

`
 const { granted } = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (granted) {
      let result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        quality: 1,
        // base64: true,
      });

      if (result.cancelled == false) {
        console.log("result image", result.uri);

        const resultRead = await BarCodeScanner.scanFromURLAsync(
          result.uri,
          barCodeTypes
        );
        console.log("resultRead", resultRead);

     
      }
    }
`

**Comment by byCedric** [comment]
Hi @thanhchuongbmd! There might be something going on in the native code. I tried to [reproduce the issue here](https://snack.expo.io/@bycedric/expo-issue-13199), but that seems to work fine. Could you provide a small repro where this happens?

**Comment by thanhchuongbmd** [comment]
> Hi @thanhchuongbmd! There might be something going on in the native code. I tried to [reproduce the issue here](https://snack.expo.io/@bycedric/expo-issue-13199), but that seems to work fine. Could you provide a small repro where this happens?

It will work ok if image is qrcode single, I use image from camera taken then it not work, See image below (ios work)
![2021-06-10 14 18 29](https://user-images.githubusercontent.com/67777599/121481865-c0e06000-c9f6-11eb-9ebd-b10d06031a4e.jpg)

**Comment by JaynPan** [comment]
Encounter the same issue here, needs help!

This is the error message

```
E_ARGS_TYPES_MISMATCH Argument of an incompatible class: class java.util.HashMap cannot be passed as an argument to parameter expecting interface java.util.List.

Argument of an incompatible class: class java.util.HashMap cannot be passed as an argument to parameter expecting interface java.util.List.
```

This is my demo code,

```
  "dependencies": {
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-vector-icons": "^8.1.0",
    "react-native-web": "~0.13.12",
    "expo-image-picker": "~10.2.2",
    "expo-barcode-scanner": "~10.2.2"
  },
```

```
import React, { useRef, useState } from "react";
import { View, Button, Platform } from "react-native";
import { BarCodeScanner, Constants } from 'expo-barcode-scanner';
import * as ExpoImagePicker from 'expo-image-picker';

const App = () => {
  const launchImageLibrary = async () => {
    const result = await ExpoImagePicker.launchImageLibraryAsync({
      mediaTypes: ExpoImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      quality: 0.1,
    });

    if (!result.cancelled) {
      return result;
    }

    return null;
  };

  const handlePictureScan = async () => {
    try {
      const grant = await requestCameraRollPermission();

      if (!grant) {
        return;
      }

      const imageResult = await launchImageLibrary();

      if (imageResult) {
        const decodedQRCodeArray = await BarCodeScanner.scanFromURLAsync(imageResult.uri, Constants.BarCodeType);

        if (Array.isArray(decodedQRCodeArray)) {
          console.log(decodedQRCodeArray);
        } else {
          throw new Error('未尋找到 QR Code');
        }
      }
    } catch (error) {
      console.log(error.code, error.message);
    }
  };

  const requestCameraRollPermission = async () => {
    if (Platform.OS === 'web') {
      return false;
    }

    const { status } = await ExpoImagePicker.requestCameraRollPermissionsAsync();

    if (status !== 'granted') {
      console.log('獲取相片膠卷權限失敗', '請至App設定開啟權限才可以上傳照片呦！');
      return false;
    }

    return true;
  };

  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Button title="scan" onPress={() => handlePictureScan()} />
    </View>
  );
};

export default App;
```
