### ISSUE TITLE
How to refresh Google access tokens which are from AuthSession API

### ISSUE THREAD

**Issue by grimmer0125** [expo/expo#13190]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

----

Currently, https://docs.expo.io/guides/authentication/#google will only produce access tokens but no refresh tokens (tested on web). Do not know how to refresh.

**Comment by grimmer0125** [comment]
Currently, https://docs.expo.io/guides/authentication/#google will only produce access tokens but no refresh tokens. Do not know how to refresh.

**Comment by stdavis** [comment]
I've tested this on iOS and found the same issue. I get an access token that expires in 1 hour but no refresh token. How do I refresh my access token?
