### ISSUE TITLE
Lottie rendering issues on android

### ISSUE THREAD

**Issue by sonaye** [expo/expo#132]
This is currently being tracked here https://github.com/airbnb/lottie-android/issues/260.

An update to lottie would be needed in the next sdk to fix these rendering issues, currently lottie is unusable on android with expo, expo currently uses 2.0.0-beta3, latest is beta4 at the moment, possibly there would be a beta5 that is aligned with the timing of the next sdk release, so I don't suggest rushing immediately on it.

**Comment by brentvatne** [comment]
Does beta4 fix the rendering issue? We'll update for next cycle, cc @janicduplessis

**Comment by janicduplessis** [comment]
I'll make sure we update again in the next sdk release.

**Comment by sonaye** [comment]
@brentvatne still waiting for a confirmation on that.

**Comment by skevy** [comment]
@sonaye we've updated to the latest Lottie in SDK 16 -- can you give it another try and let us know if it fixes your issue?

**Comment by sonaye** [comment]
Issue has been detected, PR is on the way https://github.com/airbnb/lottie-react-native/pull/129.

**Comment by sonaye** [comment]
I don't think that this pr is going through any time soon, all airbnb's open sourced products suffer from a lack of support at the moment, perhaps you could manually pull it for the next sdk @janicduplessis?

**Comment by sonaye** [comment]
This is the whole PR, literarily. Using integers instead of doubles significantly reduces the quality of the rendered animations on Android.

<img width="676" alt="screen shot 2017-06-01 at 5 45 44 pm" src="https://cloud.githubusercontent.com/assets/23000873/26685239/300d97ae-46f2-11e7-86a7-01441157d084.png">

**Comment by DieterHolvoet** [comment]
Is there any workaround for the meantime?

**Comment by sonaye** [comment]
^ you build the expo client from source, after removing the highlighted red lines, but this just .. bad.

**Comment by sonaye** [comment]
Are we going to have this patched in the next sdk? cc: @terribleben @brentvatne

**Comment by janicduplessis** [comment]
We’ll update when the PR is merged in lottie-react-native

**Comment by sonaye** [comment]
That could take a while @janicduplessis, how difficult is it to patch these eight lines of code in expo?

**Comment by sonaye** [comment]
@terribleben did something similar with rn-maps in the latest sdk https://github.com/expo/expo/commit/93d5a17f551ae1b3ef67fccd0323119099a21c73, it would nice to have this one as well, especially since it's an extra extra minor fix that changes the whole experience of viewing Lottie animations on Android.

**Comment by sonaye** [comment]
https://github.com/airbnb/lottie-react-native/pull/129 got merged, waiting for a release.

**Comment by sonaye** [comment]
lottie-react-native 1.2.0 just got released, is it too late to land it with sdk 19 @janicduplessis?

**Comment by sonaye** [comment]
Are we going to see the bump in sdk 20? it's still on the older version https://github.com/expo/expo-sdk/blob/master/package.json#L40

**Comment by janicduplessis** [comment]
We've updated lottie to 2.2.0 in sdk 21, this should resolve this issue.

**Comment by sonaye** [comment]
I can confirm that the issue has been resolved. Thanks @janicduplessis!
