### ISSUE TITLE
Interactive not working when sending push notifications

### ISSUE THREAD

**Issue by b7hermelin** [expo/expo#13205]
### Summary

Interactive notifications do not work when sending via  Expo's push service. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I am trying to send interactive code through Expo's push service, but notifications appear without the actions.
Here is the code that sends the notifications:

const notify = async () => {        
   const message = {
      to: expoPushToken,
      sound: 'default',
      title: 'App Notification',
      body: 'And here is the body!',
      _category: `@${Constants.manifest.id}/MyAppName-basic`
    };

    await fetch('https://exp.host/--/api/v2/push/send', {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Accept-encoding': 'gzip, deflate',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(message),
    });

  };
  
  When sending a local notification, it appears correctly and with interactive actions.
  I have also run this snack: https://snack.expo.io/@takwwong5/notificationtesting  on my ios device and am experiencing
  the same behaviour, Local notifications work fine, but push notifications appear without the actions.

**Comment by cruzach** [comment]
you're using `_category`, which is not supported. Please refer to the push notification payload documented here: https://docs.expo.io/push-notifications/sending-notifications/#message-request-format

**Comment by b7hermelin** [comment]
I have tried with "categoryId: basic" but still no actions appear I have also tried "categoryIdentifier: basic" as specified here: 
https://docs.expo.io/versions/latest/sdk/notifications/#setnotificationcategoryasyncidentifier-string-actions-notificationaction-options-categoryoptions-promisenotificationcategory

**Comment by cruzach** [comment]
Your snack is using SDK 39, you must use SDK 41 for categories to work inside of Expo Go. Also, you're not `await`ing your async calls so you're never receiving the Expo Push Token

**Comment by b7hermelin** [comment]
The snack is not mine, it is an example snack that I tried running.
I am indeed using sdk 41, and am also awaiting the calls (the code in the
snack is not mine), furthermore to prove that I do receive the token is the
fact that I get the notifications - only they are missing their actions.

**Comment by cruzach** [comment]
If you'd like this investigated, then please provide your own reproducible demo, otherwise it's unlikely to get attention
