### ISSUE TITLE
[expo-media-library] createAssetAsync() crashes on Android 11

### ISSUE THREAD

**Issue by osamaarefm** [expo/expo#13200]
### Summary

I’ve been using the code below in my app for a while. It downloads a PDF using FileSystem and saves it using the Media Library API.

This works fine on all Android devices except the ones with Android 11, where it breaks on createAssetAsync(). The error is: **“Unable to copy file into external storage”**.

I’m aware that Android 11 introduced changes to its scoped storage, but I haven’t found any documentation on this error. Any suggestion on what to do?

Thanks.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```
FileSystem.downloadAsync(
    // example file
    'http://www.africau.edu/images/default/sample.pdf',
    FileSystem.documentDirectory + 'testFile.pdf'
)
    .then(({ status, uri }) => {
        if (200 === status) {
            saveFileAndroid(uri);
        }
    })
    .catch(e => {
        console.log(e);
    });

const saveFileAndroid = async uri => {
      const { status: existingStatus } = await MediaLibrary.getPermissionsAsync();

      if (existingStatus !== 'granted') {
        return;
      }

      try {
        const asset = await MediaLibrary.createAssetAsync(uri), // This is where code breaks.
          album = await MediaLibrary.getAlbumAsync(appName);

        if (!album) {
          await MediaLibrary.createAlbumAsync(appName, asset, false);
        } else {
          await MediaLibrary.migrateAlbumIfNeededAsync(album);

          await MediaLibrary.addAssetsToAlbumAsync([asset], album, false);
        }
      } catch (e) {
        console.log(e);
      }
    };
```

**Comment by nihal-37-37** [comment]
@osamaarefm did u find any thing?

**Comment by osamaarefm** [comment]
@nihal-37-37 I used `rn-fetch-blob` library to save files instead of `MediaLibrary`. The save function now looks like:

```
const saveFileAndroid = async uri => {
  const fileName = 'testFile.pdf';

  RNFetchBlob.fs.mv(uri.replace('file://', ''), RNFetchBlob.fs.dirs.DownloadDir + '/' + fileName).then(() => {
    Alert.alert('', 'File saved to Downloads folder.');
  });
};
```

**Comment by Abdullah-146** [comment]
> @nihal-37-37 I used `rn-fetch-blob` library to move the downloaded file into "Downloads" folder. The save function now looks like:
> 
> ```
> const saveFileAndroid = async uri => {
>   const fileName = 'testFile.pdf';
> 
>   RNFetchBlob.fs.mv(uri.replace('file://', ''), RNFetchBlob.fs.dirs.DownloadDir + '/' + fileName).then(() => {
>     Alert.alert('', 'File saved to Downloads folder.');
>   });
> };
> ```

hy getting same issue got any solution

**Comment by UdumiziSolomon** [comment]
Same here, Any workaround? @Abdullah-146
