### ISSUE TITLE
Calling getExpoPushTokenAsync() in a detached app gets stuck instead of failing fast (iOS / Android)

### ISSUE THREAD

**Issue by faustoct** [expo/expo#1321]
Trying to get a token, the app get stuck at 
`let token = await Notifications.getExpoPushTokenAsync();` on iOS / Android .

No response, no error , it's waiting forever. I followed the example
https://docs.expo.io/versions/latest/guides/push-notifications.html

My app is Detached (ExpoKit).

**Comment by ide** [comment]
Expo push notifications are not supported in detached apps (mentioned in these docs: https://docs.expo.io/versions/latest/guides/detach.html#should-i-detach). Expo should fail faster with a clearer error message but the feature is not supported.

**Comment by faustoct** [comment]
@ide I see. Is there any suggestion to achieve push notification ? wix/react-native-push-notifications does not work.

**Comment by ide** [comment]
You could try One Signal, which some people have successfully used. This is slightly out of the realm of Expo, though, so we can't help as much.

**Comment by faustoct** [comment]
@ide thank you man. You helped a lot. Will try One Signal.

**Comment by lgandecki** [comment]
for me the promise just never resolved, I wasted a few hours trying to debug this yesterday :) Is there a chance to throw an error when trying to do Notifications.getExpoPushTokenAsync on detached app?

**Comment by faustoct** [comment]
Not supported yet? using 32.0.0 expo

**Comment by ide** [comment]
No changes to this in 32 IIRC (most of the changes were to support notification actions), no plans for this ATM.

**Comment by lgandecki** [comment]
why don't you at least throw? I imagine this is a frustrating experience for many developers :)

**Comment by ide** [comment]
It’s not intentionally this way but the function works in some scenarios so throwing unconditionally doesn’t work well either.
