### ISSUE TITLE
Expo SDK 41 Reanimated2 Causing Glitches

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo#13215]
### Summary

I am NOT using any reanimated2 packages in the actual code but Expo is pulliing in the package for interpolation functions.

My app is very glitchy (only in IOS not android) when using react-navigation due to the reanimated2 package required by expo SDK 41.

This issue had not occured until Expo SDK 41.

The SDK 41 is using "react-native-reanimated": "~2.1.0" where I am seeing lots of glitching in the app.

When I update the package to "react-native-reanimated": "^2.2.0" the app crashes and says "interpolation is not a function".

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 25, 26
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.0 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Use react-navigation in an Expo app using SDK 41. I am specifically using a drawer inside of a tab and when I move from the drawer screen back to the tab page the tab page flashes and I can see the previous page for a split second.

**Comment by mikeRChambers610** [comment]
Any updates?

**Comment by brentvatne** [comment]
you need to use the reanimated version that is installed with `expo install` in managed apps. see: https://blog.expo.io/expo-managed-workflow-in-2021-5b887bbf7dbb

please report issues related to reanimated to the reanimated repository and follow guidelines for submitting a good issue on that repository
