### ISSUE TITLE
Splash screen no respect for `resizeMode:cover` in a standalone app / adds white border

### ISSUE THREAD

**Issue by kadoshms** [expo/expo#1322]
Hey there,

Something really odd is happening with my app's splash screen.
My app.json:
```

{
  "expo": {
    "name": "something",
    "version": "1.0.11",
    "scheme": "something",
    "slug": "something",
    "privacy": "unlisted",
    "sdkVersion": "23.0.0",
    "icon": "./src/assets/image/icon.png",
    "ios": {
      "bundleIdentifier": "com.something.app"
    },
    "notification": {
      "icon": "./src/assets/image/push.png"
    },
    "splash": {
      "image": "./src/assets/image/splash.png",
      "backgroundColor": "#4B3FC9",
      "resizeMode": "cover"
    },
    "orientation": "portrait",
    "android": {
      "package": "com.something.something",
      "versionCode": 4
    }
  }
}
```

And for the splash screen itself I used the provided sketch template: https://docs.expo.io/versions/latest/guides/splash-screens.html

And the result:
<img width="546" alt="untitled-1" src="https://user-images.githubusercontent.com/5352933/35339774-1cab6f36-012a-11e8-9920-5286a12e935c.png">

As you can see I used both backgroundColor & cover, and it still adds this weird white border around the splash image.

Thanks!

**Comment by dillonhafer** [comment]
I have the same issue, and mine doesn't seem to use the `backgroundColor` as well

**Comment by brechtwaeghe** [comment]
I have the same issue with resizeMode cover using SDK 25. 
The default resizeMode (contain) with a full backgroundColor works well.

**Comment by JulianKingman** [comment]
Same problem, iOS doesn't seem to be using backgroundColor (in my case using contain). Using SDK 25.

**Comment by AbdallaMohamed** [comment]
I'm having the same issue as well after updating from SDK 22 to 25.

**Comment by aalices** [comment]
I'm looking into it, sorry for the issue!

**Comment by felipefreitag** [comment]
I'm having the same issue, only on the standalone app - during development, it seems fine. Verified on iOS 11.2.2 and 11.2.5, both simulator and device.

**Comment by jeanfw** [comment]
We're having the same issue, the standalone app seems to be ignoring the `resizeMode: "cover"` and displaying as if we had specified `"contain"`.

The expo client seems unaffected - it displays the same splash screen correctly in `"cover"` mode.

**Comment by ricklove** [comment]
Same problem.

- Background color is ignored.
- Cover is ignored.

**Comment by ethanyuwang** [comment]
Having the same problem here.

**Comment by kadoshms** [comment]
@aalices is there any update on this one ? :)

**Comment by akalra** [comment]
We have what appears to be the same issue visually, though we use 'contain' and a background color to match the background color of the image.

I'm not sure if it's doing that correctly and then adding white borders, or if it's not registering our background color at all (for our image and app, both situations would look identical), or if it's something else entirely.

Thanks!

Ankur

**Comment by terribleben** [comment]
We are expecting to deploy a fix for this before the end of the week.

**Comment by PetrVasilev** [comment]
We have the same problem. Waiting for updates

**Comment by reynaldorodriguez** [comment]
Same problem here, this was working in previous build process, i need to build and release to store today, any updates?

**Comment by terribleben** [comment]
We've deployed a fix, please try `exp build` again and see what you get.

**Comment by VeXell** [comment]
@terribleben It works! Thank you)

**Comment by dillonhafer** [comment]
It's also working for me, used it for 2 Apps ❤️ Thanks again for all the hard work put into this!

**Comment by BenBrostoff** [comment]
Hey all - I experienced the same issue when upgrading from SDK 27 to SDK 28. Any help here would be great 👍
