### ISSUE TITLE
[ios] Items set in `AsyncStorage` and `SecureStore` inaccessible in background tasks when in headless mode.

### ISSUE THREAD

**Issue by drtangible** [expo/expo#13228]
### Summary

In iOS standalone applications, items set in `AsyncStorage` (and `SecureStore`) are inaccessible in background tasks _when app is killed and task subsequently runs in headless mode_.

Seeing this behavior in background tasks run via both `Location.startLocationUpdatesAsync` and  `Location.startGeofencingAsync`.

As one important example, this prevents applications from being able to include an auth token persisted to storage on API requests issued from background tasks.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

```
  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/danielgilbert/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 28, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.0, 30.0.0, 30.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
        Android NDK: 22.0.7026061
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed
```

## Steps for reproducing this issue

* `expo init` with managed Typescript template

* Installed dependencies:
  * `expo install @react-native-async-storage/async-storage`
  * `expo install expo-constants`
  * `expo install expo-notifications`
  * `expo install expo-task-manager`
  * `expo install expo-location`

* Created simple app to test: [`App.tsx`](https://github.com/quicksoinc/task-manager-async-storage/blob/main/App.tsx).

* Added necessary iOS configuration to [`app.json`](https://github.com/quicksoinc/task-manager-async-storage/commit/40853325728c53e02e058286c92aafa09f7958ee#diff-96677aa35debfefd031d9d34d9c70369754ee3acb2d9a9d4090e98612efee6f5) for requesting background location permissions.

* Built it with managed workflow: `expo build:ios -t simulator`

* Ran the app in simulator.
  * Granted necessary permissions
  * Turned on simulated location: `Simulator` --> `Features` --> `Location` --> `City Run`
  * Started location task
  * Verified that task was able to access value stored in `AsyncStorage` when app was in non-headless state.
  * Killed app by pressing `Home` 2x and swipe-closing it.
  * Verified that task was **not** able to access value stored in `AsyncStorage` when app was in a headless state.

<kbd>
<img width="359" alt="Screen Shot 2021-06-09 at 8 37 30 PM" src="https://user-images.githubusercontent.com/169912/121460936-b6748680-c962-11eb-972e-4a02c17ce57e.png">
</kbd>

<kbd>
<img width="359" alt="Screen Shot 2021-06-09 at 8 37 46 PM" src="https://user-images.githubusercontent.com/169912/121460947-ba080d80-c962-11eb-96e5-3b00f4f61a53.png">
</kbd>

_When non-headless, value is accessible. When headless, value is **not** accessible_

* Here's a video of the above, fast forwarding for ~2mins after the app is force-killed before the location task starts picking up changes:

https://user-images.githubusercontent.com/169912/121461136-2125c200-c963-11eb-900f-d1fb4348c4d7.mp4

## Additional notes

* While this example shows trying to access values in `AsyncStorage`, in our production application, we've noticed the same behavior when trying to access values in `SecureStore`.

* For brevity & clarity, didn't include the `SecureStore` in the example app, but I have a branch in the repo that shows the same behavior. (https://github.com/quicksoinc/task-manager-async-storage/pull/1)

<kbd>
<img width="380" alt="Screen Shot 2021-06-09 at 9 06 19 PM" src="https://user-images.githubusercontent.com/169912/121463356-c1311a80-c966-11eb-927c-eff28197942f.png">
</kbd>
<kbd>
<img width="380" alt="Screen Shot 2021-06-09 at 9 06 12 PM" src="https://user-images.githubusercontent.com/169912/121463366-c42c0b00-c966-11eb-9271-39100b36b8aa.png">
</kbd>

* Since this behavior is exhibited in `SecureStore` as well, wondering if it's something about how the application operates in headless mode w/`TaskManager`. Given this, filing the issue here, rather than in the `@react-native-async-storage/async-storage` repo.

* Potentially related issues:
  * expo/expo#5489
  * expo/expo#7278

* Have not yet tested whether this behavior is exhibited in Android as well.

* Was having trouble reproducing this behavior on Expo Go, but was able to repro on standalone app as well as our own production application.

**Comment by drtangible** [comment]
Additional data point here: I'm unable to reproduce this behavior when using `expo run:ios`. Tried doing so to poke around in the native code to understand what's going on.

**Comment by FelipeACP** [comment]
I have a similar application in production that AsyncStorage works in background. - it has foreground service enabled, though.

**Comment by drtangible** [comment]
@FelipeACP 👍   -- I believe the `foregroundService` option is only considered on Android, and I've only been able to reproduce this on iOS so far. Specifically, on:

* iOS standalone apps
* Only then the task is running in headless mode

I'll take a look at whether the reproducible demo noted above impacts Android as well, and update the issue description.

**Comment by FelipeACP** [comment]
> @FelipeACP 👍 -- I believe the `foregroundService` option is only considered on Android, and I've only been able to reproduce this on iOS so far. Specifically, on:
> 
> * iOS standalone apps
> * Only then the task is running in headless mode
> 
> I'll take a look at whether the reproducible demo noted above impacts Android as well, and update the issue description.

You're right, my bad, foreground service is not available for iOS.

In iOS standalone, the behaviour I've seen after the app is killed is deferring all the updates until I open the app - which may have to do with the internet connection being lost. When they do arrive, however, the stored values are present.

I will test your code on my app and see if I can find a pattern.

**Comment by ammarkhan967** [comment]
This is how it work

[11144_challanform_590_1623658709.pdf](https://github.com/expo/expo/files/6647474/11144_challanform_590_1623658709.pdf)

**Comment by falay26** [comment]
I am having this exact same problem, just thinking about ejecting my project after reading your comment ("I'm unable to reproduce this behavior when using expo run:ios").  Is this still the case, all works expectedly when ejected? Or did you find any solutions?

**Comment by drtangible** [comment]
Confirmed that this same behavior exists in SDK 42, when interfacing with both `AsyncStorage` and `SecureStore`:

<img width="578" alt="Screen Shot 2021-07-08 at 12 30 37 PM" src="https://user-images.githubusercontent.com/169912/124979783-5ec04e00-dfe8-11eb-9f61-0649a13db80c.png">

```txt
  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/danielgilbert/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 28, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.0, 30.0.0, 30.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
        Android NDK: 22.0.7026061
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed
```

**Comment by guhanganesamurthi** [comment]
HI @drtangible, facing the same issue. Any workarounds? It would be really helpful.

**Comment by drtangible** [comment]
@guhanganesamurthi -- we have not found a workaround for accessing values in `AsyncStorage` or `SecureStore` when tasks are run in headless mode. We haven't been able to pinpoint or investigate the root cause.

**Comment by drtangible** [comment]
Just bumping to keep context, as we're still impacted this issue.

**Comment by s3131212** [comment]
Confirmed that the problem still exists.

**Comment by jonathan-reisdorf** [comment]
We have this issue as well with `SecureStore` and `CoreBluetooth` on iOS when `willRestoreState` occurs and the app (standalone, not Expo Go) is relaunched while the phone is locked. When the phone is not locked and the app is just in the background, things works for us.
