### ISSUE TITLE
Swiping away Camera or Image Picker does not trigger cancel

### ISSUE THREAD

**Issue by charles-goode** [expo/expo#13221]
### Summary

Calling ImagePicker.launchImageLibraryAsync, brings up the iOS image library modal in PageSheet style. This modal can be cancelled/dismissed by swiping down from the top. When this occurs, it appears the Promise returned by function remains pending indefinitely. I can put a print immediately after `await ImagePicker.launcImageLibraryAsync` and the print will never be called if I closed the modal via swipe. I'm aware that the React Native modal component with the iOS specific presentationStyle PageSheet also has the issue of never calling the onDismiss callback when swiped, so that's probably related. Is there really no binding in native iOS for these modals to know when they've been closed? If so that should be very apparent in documentation so people know what they're getting themselves into. I found #10405 which seems kind of similar, but I'm not sure if expo-document uses the PageSheet modal which is likely the root cause of this problem. Also note that this occurs for ImagePicker.launchCameraAsync too. 

While working on the snack, I noticed that the emulator does not pull up the media library inside of a PageSheet like modal like it does on my device. I'm totally fine with having it open full screen, but I don't see a way to ensure that happens. After searching around on google for a bit, I didn't find anything about why the camera and media library are opening as modal all of a sudden. When I first implemented these features, they were full screen. Does anyone know how when this started happening? Is this an iOS thing or an Expo thing? 

Side issue: the StatusBar fades away when the Camera modal is up (after calling ImagePicker.launchCameraAsync). It appears again whenever the modal is being swiped.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.22.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Here's the snack. Its literally the exact code from the ImagePicker documentation https://snack.expo.io/@charles.goode/crabby-chips. 
* Opening the logs on the bottom of the screen
* Connect with your own iOS device (I'm guessing it needs to be fairly recent iOS like 14.4 or 14.5)
* press the button to open the camera roll
* Assuming you have the modal presentation style, swipe down to close it
* Check the logs to see that the `result` object was never printed out (therefore the promise hasn't resolved even though the picker has been cancelled)

**Comment by ey3bk** [comment]
Any updates on this? Running into the same issue myself

**Comment by charles-goode** [comment]
@ey3bk No update.

**Comment by martinezguillaume** [comment]
I have the same problem !

**Comment by f-g-p** [comment]
Same here, can someone give it a look ? 
thanks !

**Comment by kjscott27** [comment]
Still an issue in SDK42
