### ISSUE TITLE
Application X has not been registered

### ISSUE THREAD

**Issue by yordis** [expo/expo#1323]
I just changed "appKey" to "X" and the application is failing

```
Application X has not been registered
```

I know what it is but I am assuming that Expo is doing the necessary code for me, unless I am missing something out

**Comment by nikki93** [comment]
This is just the name that Expo will use to search for your root component in React Native's `AppRegistry`, so if you haven't registered any component with the name 'X', it won't be found. The default name that Expo searches for is 'main', which is registered by Expo here: https://github.com/expo/expo-sdk/blob/7d29c274c5c7a7b3a5740094b474cd979b930795/src/launch/registerRootComponent.js#L46.

**Comment by yordis** [comment]
@nikki93 I would love to have that explanation there, or maybe I didn't know what I was reading.

I was expecting Expo to use `appKey` for register the app under that name

**Comment by nikki93** [comment]
https://docs.expo.io/versions/latest/guides/configuration.html#appkey -- is a short version of what I said, if less clear. I would suggest not messing around with this option unless you really need it for a justifiable reason.

**Comment by yordis** [comment]
@nikki93 for me was about changing the name for none reason to be honest, just being fancy.
