### ISSUE TITLE
Execution failed for task ':expo-permissions:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by abcabccd** [expo/expo#13233]
### Summary

> Task :expo-permissions:compileReleaseKotlin FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

3 warnings
e: C:\Users\abcab\UnlockMe\node_modules\react-native-unimodules\node_modules\expo-permissions\android\src\main\java\expo\modules\permissions\PermissionsModule.kt: (37, 122): Unresolved reference: ACCESS_BACKGROUND_LOCATION
e: C:\Users\abcab\UnlockMe\node_modules\react-native-unimodules\node_modules\expo-permissions\android\src\main\java\expo\modules\permissions\requesters\LocationRequester.kt: (24, 85): Unresolved reference: Q
e: C:\Users\abcab\UnlockMe\node_modules\react-native-unimodules\node_modules\expo-permissions\android\src\main\java\expo\modules\permissions\requesters\LocationRequester.kt: (25, 39): Unresolved reference: ACCESS_BACKGROUND_LOCATION
e: C:\Users\abcab\UnlockMe\node_modules\react-native-unimodules\node_modules\expo-permissions\android\src\main\java\expo\modules\permissions\requesters\LocationRequester.kt: (56, 89): Unresolved reference: Q
e: C:\Users\abcab\UnlockMe\node_modules\react-native-unimodules\node_modules\expo-permissions\android\src\main\java\expo\modules\permissions\requesters\LocationRequester.kt: (57, 91): Unresolved reference: ACCESS_BACKGROUND_LOCATION

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-permissions:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 50s

    at makeError (C:\Users\abcab\UnlockMe\node_modules\execa\index.js:174:9)
    at C:\Users\abcab\UnlockMe\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async runOnAllDevices (C:\Users\abcab\UnlockMe\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\abcab\UnlockMe\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\abcab\AppData\Roaming\npm\yarn.CMD
      npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: ^0.64.2 => 0.64.2
      react-native-web: 0.16.5 => 0.16.5
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

run yarn react-native run-android --variant=release

build failed for both expo-permissions 12.0.1,11.0.0,
use unimodule and tried downgraded it from 12.0.1 to11.0.0
build still failed.
Problem seems to be migration to core as posted on github

**Comment by pjcaro** [comment]
@abcabccd any solution?

**Comment by AllStackDev1** [comment]
Execution failed for task ':expo-screen-orientation:compileReleaseKotlin'
