### ISSUE TITLE
Deep Linking does not accept query params when I hit the exp://127.0.0.1:19000?test=test

### ISSUE THREAD

**Issue by SharmaDinesh** [expo/expo#13248]
### Summary

Deep Linking does not accept query params when I hit the exp://127.0.0.1:19000?test=test and showing Cannot GET / error.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

dev

### Reproducible demo or steps to reproduce from a blank project

Deep Linking does not accept query params when I hit the exp://127.0.0.1:19000?test=test

**Comment by byCedric** [comment]
Hi @SharmaDinesh! I'm not sure if I understand your issue. What is the use case you are trying to do here? Right now, you are hitting the Expo server that "hosts" the web-based devtool and metro. That might result in a "Cannot GET / error", but that's not related to the actual app. It's related to the web-based devtool not finding the right page to show you.

**Comment by farzd** [comment]
@byCedric my use case is using a magic link to login, so i need query params but get "Cannot GET / error"

**Comment by cruzach** [comment]
This may have been fixed in expo/expo-cli PR #3775- have you tried the most recent version of `expo-cli`?

**Comment by cruzach** [comment]
confirmed this was fixed, please update to `expo-cli@4.11.0`
