### ISSUE TITLE
Expo Push Notifications - Disable notifications in a specific screen doesn't work

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#13243]
### NOTE

On Android, it works as expected. On iOS, testing on iPhone 11 Pro (iOS 14.4), it doesn't.

### Summary

How can I disable showing notifications in my Expo app when the user is in a specific screen?

I am currently designing a chat screen, and I want to disable push notifications when the user is inside it. And I can't get what  I want using Notifications.setNotificationHandler().

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.9.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: ^17.0.1 => 17.0.1 
      react-dom: ^17.0.1 => 17.0.1 
      react-native: ^0.63.4 => 0.63.4 
      react-native-web: ^0.15.0 => 0.15.0 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Currently, I have implemented the following methods in my PushNotifications module:

ExpoNotifications.js
```
export function setNotificationHandler(handler) {
    Notifications.setNotificationHandler(handler);
}

export function hidePushNotifications() {
  setNotificationHandler({
    handleNotification: async () => ({
      shouldShowAlert: false,
      shouldPlaySound: false,
      shouldSetBadge: false,
    }),
  });
}

export function unhidePushNotifications() {
  setNotificationHandler({
    handleNotification: async () => ({
      shouldShowAlert: true,
      shouldPlaySound: true,
      shouldSetBadge: true,
    }),
  });
}

```

And in my Chat screen, in a useEffect, I am doing:

Chat.js
```
useEffect(() => {
  // Do not show push notifications when the user is inside this screen
  hidePushNotifications();

  return () => {
    // When unmounted, unhide push notifications
    unhidePushNotifications();
  };
}, []);
```

For me, this has sense, as I am "hiding" push notifications when the user enters the chat screen, and "unhiding" them when he leaves.

But for some reasons, the notifications still appear inside the chat screen. Why?

How can I solve this issue?

**Comment by VictorioMolina** [comment]
Note: I am importing everything from my custom module correctly, the methods are called.

**Comment by cruzach** [comment]
It seems like a simpler solution might be to only call `Notifications.setNotificationHandler` once, and then determine the behavior inside the callback:

```
Notifications.setNotificationHandler({
  handleNotification: async () =>
    if (someSettingToHideNotifications) {
      return ({
        shouldShowAlert: false,
        shouldPlaySound: false,
        shouldSetBadge: false,
      });
    }
    return ({
      shouldShowAlert: true,
      shouldPlaySound: true,
      shouldSetBadge: true,
    });
});

```

I'm also not 100% sure, but I believe `Notifications.setNotificationHandler` might have to be called in the global scope.

**Comment by VictorioMolina** [comment]
@cruzach but if I have a stack navigator with 2 screens, "MyChats" and "Chat", and I call setNotificationHandler in the global scope of both files:

    - In MyChats, show notifications
    - In Chat, hide notifications

How will the app be able to unhide notifications when going back from Chat to MyChats?

I thought that the way was to unhide when the component hat hides them is unmounted. By the way, in Android is working :/ I will try your solution and to update my iOS.

**Comment by VictorioMolina** [comment]
@cruzach Hey, I implemented what u said, to call it in the global scope, but still having the same problem on iOS. Also, I updated the software to iOS 14.6.

**Comment by cruzach** [comment]
This is working for me- https://snack.expo.io/@charliecruzan/push-notifications-11111

Is it not for you?

**Comment by VictorioMolina** [comment]
Testing the snack in Expo Go works!

But, if I copy the code and add it to one of my app routes, same behavior, not working. I don't know wtf is happening.

**Comment by VictorioMolina** [comment]
Is that caused because of having this line in my app.json?

"notification": {
      ...
      "iosDisplayInForeground": true
 },

**Comment by VictorioMolina** [comment]
Yeah, okey I am stupid.

Thx @cruzach for ur help.
