### ISSUE TITLE
ReferenceError: Property 'b1' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by fungmo** [expo/expo#13255]
### Summary

When I used `yarn android` today, I reported this error. I tried to delete the module and yarn.lock files, and re-yarn did not work.

![image](https://user-images.githubusercontent.com/16655229/121677657-c027f680-cae8-11eb-9bc0-224bf7bfeb8d.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

```base
Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.3
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Try the above steps several times, and restart the computer several times and try again, still this error.

**Comment by byCedric** [comment]
Hi @fungmo, thanks for the issue report. Unfortunately, the reproducible example you mentioned isn't usable for us. We don't have access to your local project. Please provide a repository with this issue. Without that, we won't be able to help you investigate this issue.

**Comment by fungmo** [comment]
@byCedric 
I found the problem, I have an undefined b1 variable in a ts data. So it reported an error at the end.
