### ISSUE TITLE
expo-facebook IOS managed workflow requestPermissionsAsync crash

### ISSUE THREAD

**Issue by izica** [expo/expo#13251]
### Summary

`const response = await Facebook.requestPermissionsAsync();`

crashed on IOS production build

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

`await Facebook.initializeAsync()` works fine
 
 but 
 
 `        
try {
  const response = await Facebook.requestPermissionsAsync();
} catch (e) {
  return;
};`
got instant crash app without any message, try catch doesn't work

**Comment by byCedric** [comment]
Hi @izica! Did you go through all steps in the [configuration section](https://docs.expo.io/versions/latest/sdk/facebook/#ios-standalone-app)? If you did, could you provide [a small repro](https://stackoverflow.com/help/minimal-reproducible-example) with this issue? Without that, we won't be able to help you investigate this issue.

**Comment by izica** [comment]
@byCedric after we added 
ios.infoPlist.NSUserTrackingUsageDescription
in app.json, and full rebuild(not OTA update) problem with crashes was resolved
