### ISSUE TITLE
expo-gl compatibility issue with react native

### ISSUE THREAD

**Issue by shahanija** [expo/expo#13250]
### Summary

I am using `expo-gl@9.0.0` and `expo-gl-cpp@9.0.0`. in bare `react-native @0.63.0` as per the documentation.

But it throws exception "Unsupported" .
So I had to downgrade the packages to  `expo-gl@8.4.0` and `expo-gl-cpp@8.4.0` to make it work. After downgrading to the lower version, it works fine. But I am confused with the version compatibility specified in the document.
i.e.

**Reference**:
[https://www.npmjs.com/package/expo-gl] 

![image](https://user-images.githubusercontent.com/84307446/121653674-93f58100-caba-11eb-8a14-8dfd055e4323.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

 expo-gl:^8.4.0
expo-gl-cpp:^8.4.0
react:16.11.0
react-native:0.63.0
react-native-unimodules:0.11.0

**OS**
Windows 10

### Reproducible demo or steps to reproduce from a blank project

Create a new project with RN @0.63.0 and install the packages with specified versions,

Import `GLView` from `expo-gl`.

It will throw and exception called "Unsupported"

**Comment by byCedric** [comment]
@tsapeta or @bbarthec do you know what might be going on here?

**Comment by tsapeta** [comment]
Is it just "Unsupported" and no more info? No stacktrace? Is it crashing the app or you see it in React Native's redbox?
Generally we're not doing any checks against React Native version, so I think the root problem is somewhere else.
Could it be possible the error come from one these three functions https://github.com/facebook/react-native/blob/06c33e9abe6ed51b1c8bba03982ebce2b6da3860/ReactCommon/jsi/JSCRuntime.cpp#L938-L962 ? Maybe you can find that in logcat?

**Comment by wkozyra95** [comment]
This commit is necessary to to support array buffers in new expo-gl-cpp https://github.com/facebook/react-native/commit/9c32140068463739b91874689f741ea9630d8c3b

you need to have at least 0.63.1 version (but I suggest to always install latest patch version)

**Comment by tsapeta** [comment]
Yeah, that's right — version `9.x.x` requires at least `0.63.1`, not `0.63.0` as said in the README. I've fixed the compatibility table in this commit https://github.com/expo/expo/commit/d7b12c707d7ad707f37c16cd10c3b1e924de7b50 which should soon be released to npm.
Thanks for finding and reporting it us 🙇‍♂️ I'm closing it, but let us know if updating to `0.63.1` doesn't help 😉
