### ISSUE TITLE
SafeAreaView acts differently based on androidStatusBar config

### ISSUE THREAD

**Issue by ckknight** [expo/expo#1326]
`SafeAreaView` was introduced in react-native 0.50.1

In iOS, `SafeAreaView` provides padding to include the StatusBar, and if on iPhone X, also on the bottom to deal with the Home indicator. in Android, `SafeAreaView` is equivalent to `View`.

If `androidStatusBar.backgroundColor` in app.json is specified, then the `SafeAreaView` ostensibly works equivalently to iOS. If not specified, then manual handling and observation of `Expo.Constants.statusBarHeight` has to be taken into account.

**Comment by terribleben** [comment]
There is a workaround given [here](https://github.com/expo/expo/issues/1314#issuecomment-361775086).
