### ISSUE TITLE
Expo-camera works fine in Expo client, but crashes my app when its built on TestFlight

### ISSUE THREAD

**Issue by lgzambello** [expo/expo#13268]
### Summary

`import { Camera } from 'expo-camera';`

I am able to use expo-camera completely fine when I am testing it in Expo client, or even by scanning the QR code to test my app via the Mobile Expo App on iOS. However, any reference of this Camera object in my code will crash my test flight app on iOS. Whether I am using it as a react component, or referencing it like the following, it crashes my app immediately upon startup.
`  const [whichCamera, setWhichCamera] = useState(Camera.Constants.Type.back);`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
      npm: 7.7.6 - ~/.nvm/versions/node/v15.4.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Make any reference to the Camera object as shown above in an expo project, and then run expo publish to update the testFlight app. Immediately upon launching the testFlight app it will crash without any error I can trace. Here is the device information from my crash report:

Device
iPhone 12 Pro
Version
iOS 14.4.2
Battery
85%
Time Zone
America/Los_Angeles
Architecture
arm64e
Connection Type
Wi-Fi
Disk Free
22.21 GB available of 119.09 GB
Screen Resolution
390pts by 844pts

**Comment by cruzach** [comment]
Hi! Please provide a minimal reproducible demo, as in a snack or a link to a github repo that we can build and see the same crash, then I can reopen the issue. You should spend some time going through the native crash logs first to make sure it's not an issue with your code specifically, and is a bug with `expo-camera` - https://docs.expo.io/workflow/debugging/#production-errors

**Comment by lgzambello** [comment]
Here is a github repo where it is reproduced: https://github.com/lgzambello/expo-camera-issue

This app runs fine in the Expo App, but will crash when published to a test flight app.

**Comment by lgzambello** [comment]
This may or may not be related, but I saw a sentry log with the following error. I haven't been able to reproduce it: 
`Invariant Violation: Tried to register two views with the same name ViewManagerAdapter_ExponentCamera`

**Comment by lgzambello** [comment]
Adding more information. Here is the relevant section of the crash report generated.
`Incident Identifier: 7A24BE6F-15E6-4351-B78C-6D9D193E99CF
Hardware Model:      iPhone13,3
Process:             bitclout [1578]
Path:                /private/var/containers/Bundle/Application/90684682-2DBC-4D70-B305-53834D5AEE53/bitclout.app/bitclout
Identifier:          com.gem.bitclout
Version:             1.0.1 (1.0.1)
AppStoreTools:       12E262
AppVariant:          1:iPhone13,3:14
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.gem.bitclout [637]


Date/Time:           2021-06-14 19:22:57.7353 -0700
Launch Time:         2021-06-14 19:22:55.9331 -0700
OS Version:          iPhone OS 14.4.2 (18D70)
Release Type:        User
Baseband Version:    1.42.03
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  2

Last Exception Backtrace:
0   CoreFoundation                	0x192dd586c __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1a7deec50 objc_exception_throw + 60 (objc-exception.mm:565)
2   bitclout                      	0x100654e44 RCTFatal + 668 (RCTAssert.m:145)
3   bitclout                      	0x1006d16a4 -[RCTExceptionsManager reportFatal:stack:exceptionId:suppressRedBox:] + 492 (RCTExceptionsManager.mm:76)
4   bitclout                      	0x1006d20d8 -[RCTExceptionsManager reportException:] + 1532 (RCTExceptionsManager.mm:145)
5   CoreFoundation                	0x192dda8f4 __invoking___ + 148
6   CoreFoundation                	0x192cb1df8 -[NSInvocation invoke] + 448 (NSForwarding.m:3389)
7   CoreFoundation                	0x192cb23cc -[NSInvocation invokeWithTarget:] + 80 (NSForwarding.m:3495)
8   bitclout                      	0x100684e30 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 460 (RCTModuleMethod.mm:584)
9   bitclout                      	0x100686fb4 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 244 (RCTNativeModule.mm:114)
10  bitclout                      	0x100686d18 operator() + 44 (RCTNativeModule.mm:75)
11  bitclout                      	0x100686d18 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 88 (RCTNativeModule.mm:67)
12  libdispatch.dylib             	0x1929c824c _dispatch_call_block_and_release + 32 (init.c:1454)
13  libdispatch.dylib             	0x1929c9db0 _dispatch_client_callout + 20 (object.m:559)
14  libdispatch.dylib             	0x1929d110c _dispatch_lane_serial_drain + 580 (inline_internal.h:2548)
15  libdispatch.dylib             	0x1929d1c5c _dispatch_lane_invoke + 408 (queue.c:3862)
16  libdispatch.dylib             	0x1929dbd78 _dispatch_workloop_worker_thread + 708 (queue.c:6601)
17  libsystem_pthread.dylib       	0x1de881814 _pthread_wqthread + 276 (pthread.c:2211)
18  libsystem_pthread.dylib       	0x1de88876c start_wqthread + 8`
