### ISSUE TITLE
"Failed to schedule the notification. Trigger of type: calendar is not supported on Android" [Not using type field].

### ISSUE THREAD

**Issue by jramosss** [expo/expo#13264]
### Summary

My code is supposed to schedule a notification at an specified hour, but the error in the title is thrown

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

 Expo CLI 4.5.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
      npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ~41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ^0.16.3 => 0.16.3 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@chuls/instantnotification

Some functions are detailed in other files, but i dont think that changes something.

Just touch the button, i expect to get a notification the minute after i press the button, but instead i get the error.

**Comment by cruzach** [comment]
This is happening bc you're using a [calendar trigger input](https://docs.expo.io/versions/latest/sdk/notifications/#calendartriggerinput), which is iOS only. You should use a [date trigger input](https://docs.expo.io/versions/latest/sdk/notifications/#datetriggerinput) instead
