### ISSUE TITLE
[docs] Expo support iMessage Stickers

### ISSUE THREAD

**Issue by bomanimc** [expo/expo#13273]
### Summary

Does Expo support [iMessage Stickers](https://developer.apple.com/imessage/) (without needing to eject the app)? We would like to associate a sticker pack with an app we launched with Expo, and a documentation addition on the build page would be helpful here! 

### Link to the related docs page

https://docs.expo.io/distribution/building-standalone-apps/

**Comment by cruzach** [comment]
Hi! We don't support this right now, but you can add it to our feature request list- https://expo.canny.io/
