### ISSUE TITLE
[android][expo-sms] Error: No messaging application available, Android 11

### ISSUE THREAD

**Issue by curtismgt** [expo/expo#13277]
### Summary

When attempting to use `sendSMSAsync` after checking `isAvailableAsync`, promise rejection is received with `Error: No messaging application available`. This happens on any device, physical or emulated running Android 11 (R, API 30). When using Android 10 (Q, API 29), everything works as expected.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android 11 (R, API 30)

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
      npm: 7.17.0 - ~/.nvm/versions/node/v14.15.5/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. Start a new bare workflow project (we use typescript, unknown if this matters)
2. run `expo install expo-sms`
3. Change `App.tsx` to:
```import React from 'react';
import {StyleSheet, Text, TouchableOpacity, View} from 'react-native';
import * as SMS from 'expo-sms'

export default function App() {
    const send = async () => {
        const isAvailable = await SMS.isAvailableAsync();
        if (isAvailable) {
            await SMS.sendSMSAsync(
                ['5555555555'],
                'My sample HelloWorld message',
            )
        } else {
            console.warn('SMS not available')
        }
    }

    return (
        <View style={styles.container}>
            <TouchableOpacity onPress={send}>
                <Text>Send</Text>
            </TouchableOpacity>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
});
```
4. Start an AVD emulator running Android 11 (R, API 30)
5. Run `npm run android`
6. Press the send button
7. Receive promise rejection `Error: No messaging application available` even though there is a messaging app on the emulator. This also happens on physical devices.

**Comment by vdex42** [comment]
This is also an issue for EAS builds

With _Managed Workflow_ when building with ``expo build:android`` on a physical Pixel 5 ``SMS.sendSMSAsync`` works ok

With _Managed Workflow_ when building with ``eas build`` on a physical Pixel 5 ``SMS.sendSMSAsync`` results in **"Error: No messaging application available"**

With _Managed Workflow_ when building with ``eas build`` on a physical Samsung S8 ``SMS.sendSMSAsync`` works ok

**Comment by curtismgt** [comment]
I can't speak to the EAS stuff, but as far as Bare Workflow is concerned, this is an issue with the Android version. When using Android 10 (Q, API 29), everything works properly. When using Android 11 (R, API 30), the issue is replicated. I will edit the original issue with this information.
