### ISSUE TITLE
Hope to support image rendering in webp format

### ISSUE THREAD

**Issue by fungmo** [expo/expo#13286]
### Summary

I want to render images in webp format in `react-native-webview`. Even if I added in `dependencies` in `android/app/build.gradle`
```base
implementation'com.facebook.fresco:animated-webp:1.10.0'
implementation'com.facebook.fresco:webpsupport:1.10.0'
```
It was not rendered either.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

```base
Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.3
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

I added in `dependencies` in `android/app/build.gradle`
```base
implementation'com.facebook.fresco:animated-webp:1.10.0'
implementation'com.facebook.fresco:webpsupport:1.10.0'
```

**Comment by byCedric** [comment]
Hi @fungmo, the added android dependencies should do the trick. With that, you should be able to render `<Image />` with webp support. But, since you are rendering it in `react-native-webview`, and not just React Native or Expo, I would highly recommend checking with the package maintainers on how to implement it for webview.
