### ISSUE TITLE
[ios] Add introductory offer information to InAppPurchases.getProductsAsync

### ISSUE THREAD

**Issue by cruzach** [expo/expo#13287]
Users need this info

https://developer.apple.com/documentation/storekit/skproduct/2936878-introductoryprice?language=objc
https://developer.apple.com/documentation/storekit/skproduct/3043534-discounts?language=objc
https://developer.apple.com/documentation/storekit/skproductdiscount?language=objc

Should also see if something similar is offered on Android

**Comment by markymc** [comment]
@cruzach Any news on this? Seems pretty important these days.

**Comment by markymc** [comment]
Bump

**Comment by areimann-sf** [comment]
Yes, that information is definitely very important for me. Seems like a feature that should be bumped in priority.

**Comment by openpathgit** [comment]
I would like it a lot!

**Comment by stage88** [comment]
This would be very useful, it is the only thing currently that is preventing me from adopting this package.

**Comment by brentvatne** [comment]
i'd recommend trying out revenuecat's integration for a more fully featured option than what is available as of june 2022 in expo-in-app-purchases. we aren't actively working on this module at the moment so you will likely have more success with revenuecat's library. see this post for more info: https://www.revenuecat.com/blog/using-revenuecat-with-expos-managed-workflow/
