### ISSUE TITLE
[ios] .m3u8 does not play properly in Expo AV 

### ISSUE THREAD

**Issue by akinguyen** [expo/expo#13291]
### Summary

Hi, I have tried to use the .m3u8 video file with Expo Video for both Android and IOS. What I have found was that Android worked pretty well but not the IOS one. For Android, the video displays right the way (very quick regardless of the internet speed). But for IOS, the video will have a black screen and then it slowly plays the video. I currently use Expo SDK 41 and wonder what makes the IOS have a slow loading compared to Android. Also, it will be great if anyone wants to suggest me another way to load and play video immediately or somewhat as fast as how tiktok displays their video. Thank you

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.3.4 environment info:                                                                                 
System:                                                                                                          
OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)                                                                 
Shell: 5.0.16 - /bin/bash                                                                                    
Binaries:                                                                                                        
Node: 10.19.0 - /usr/bin/node                                                                                  
Yarn: 1.22.4 - /mnt/c/Program Files (x86)/Yarn/bin/yarn                                                        
npm: 7.7.5 - /usr/local/bin/npm                                                                              
npmPackages:                                                                                                    
 expo: ^38.0.0 => 38.0.11                                                                                      
 react: 16.11.0 => 16.11.0                                                                                     
 react-dom: 16.11.0 => 16.11.0                                                                             
     react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2                         
react-native-web: ~0.11.7 => 0.11.7                                                                          
npmGlobalPackages:                                                                                               
expo-cli: 4.3.4                                                                                              
Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

`<Video
                    style={{ flex: 1 }}
                    source={{
                      uri: "video.m3u8",
                    }}
                    useNativeControls={false}
                    resizeMode="contain"      
                    isLooping
                    shouldPlay={true}
/>
`

**Comment by LuuchoRocha** [comment]
Just to point it out, I'm using the latest version on RN 0.64.2 on a bare workflow project and the m3u8 videos are loading perfectly and even faster and in better quality than Android. Maybe is some issue with your app? Or maybe is an issue with the video stream? Have you tried another one?
The only difference I've noticed is that Android emits "onReadyForDisplay" when the buffer is actually filled, so, the video is actually playable. Instead, iOS emits the same event just on the metadata load, so, the buffer is still being loaded at this point.

Your reproducible demo is not enough:
```jsx
<Video style={{ flex: 1 }}
               source={{ uri: "video.m3u8", }} 
               useNativeControls={false}
               resizeMode="contain" 
               isLooping shouldPlay={true} />
```
I tried in an empty app with those lines and a private video and it loads just fine in a iPhone 8 using a 20mbps connection
