### ISSUE TITLE
Android rejecting app notifications because "NO_INPUT_CHANNEL"

### ISSUE THREAD

**Issue by jramosss** [expo/expo#13295]
### Summary

App works excelent (sends the notification) when running in expo go App, but when i run it in my phone (having exported the app) the nex log appears (in my adb logcat) E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

 Expo CLI 4.5.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
      npm: 7.17.0 - ~/.nvm/versions/node/v12.20.1/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ~41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ^0.16.3 => 0.16.3 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@chuls/notification

Behavior in expo go app:
Instant Notification works well (sends a notification when pressed)
Next Minute Notification also works (Sends a notification one minute after the button was pressed)

Behavior when the app is exported and running on my phone:
Instant notification does nothing (no logs either)
Next Minute notification does nothing but android logs shows: E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring

**Comment by cruzach** [comment]
I'm not sure that the `INPUT_FEATURE_NO_INPUT_CHANNEL` log is relevant here... you're not `await`ing the call to scheduleNotificationAsync though

Can you try building a new app using this snack code- https://snack.expo.io/@charliecruzan/13295?

**Comment by jramosss** [comment]
That worked, but it`s necessary to make it a react component?

**Comment by cruzach** [comment]
what do you mean by "it"?

**Comment by cruzach** [comment]
closing since this is an issue with JS app code, not with expo-notifications
