### ISSUE TITLE
[exp] iOS: There was an error with this build.

### ISSUE THREAD

**Issue by Arjit-Dhavale** [expo/expo#1331]
I have been trying to build my react native project but getting message 
**iOS: There was an error with this build.**
When I try to browse to the URL to see build logs I get message:
**<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>0A81081317EF8DDE</RequestId><HostId>M6Y7nahGfZ2DBfX+curRyjTavMBvvcByMYs2yQYeerR8Z1QFgYbaKzEPgTMOj268yMBJnQPnvtY=</HostId></Error>**

Below are the command, process and build ID

$ exp build:ios --clear-credentials -c
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Removed existing credentials
? How would you like to upload your credentials?
 I will provide all the credentials and files needed, Expo does limited validati
on

We need your Apple ID/password to ensure the correct teamID and appID

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? xxx@xxxxx.com
? Password? ********
[exp] Validating Credentials...
[exp] You have 1 teams
Only 1 team associated with your account, using Team ID: XXXXXXXX
[exp] 
WARNING! In this mode, we won't be able to make sure your certificates,
or provisioning profile are valid. Please double check that you're
uploading valid files for your app otherwise you may encounter strange errors!

Make sure you've created your app ID on the developer portal, that your app ID
is in app.json as `bundleIdentifier`, and that the provisioning profile you
upload matches that team ID and app ID.

[exp] Please provide your distribution certificate P12:
? Path to P12 file: /Users/dhavaar/Documents/Projects/XXXXXXX/Certificat
es.p12
? P12 password: ***********
[exp] Please provide the path to your push notification cert P12
? Path to P12 file: /Users/dhavaar/Documents/Projects/XXXXXX/Certificat
es.p12
? P12 password: ***********
[exp] Please provide the path to your .mobile provisioning profile
? Path to your .mobile provisioning Profile /Users/dhavaar/Documents/Projects/
XXXXX/XXXXX_AppStore.mobileprovision
[exp] Encrypted certP12,certPassword,pushP12,pushPassword,provisioningProfile,teamId and saved to expo servers
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://XXXXXXXX

[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] You can monitor the build at

 https://expo.io/builds/5bb67660-b39b-4691-91ad-09e7908ad37c

[exp] Alternatively, run `exp build:status` to monitor it from the command line.

Can anyone assist on how to proceed further to check build logs and identify the exact cause of the error?

**Comment by udavf** [comment]
I have same issue since few hours ago
Using usual command exp build:android --release-channel prod-v1.1

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F721FA99A1159552</RequestId><HostId>ylqy42MoYSesmoWWWaJH6GugyN8mI/V+ZDGWrKBBXoS2VHpwRiycL613od1fzbq7wfZdvBOk4y0=</HostId></Error>

**Comment by udavf** [comment]
Build itself seems to going fine. If you wait until it's end, "download" button becomes active

**Comment by Arjit-Dhavale** [comment]
Hello udavf
In my case I am getting failure message.
iOS: There was an error with this build.

So the download never comes active for my build and the view logs is displaying access denied. Is there any other way to get insights into why the build failed?

**Comment by esamelson** [comment]
Hi all - we were having some issues last night that probably caused this. If you try your build again now it should work fine - feel free to reopen if you keep seeing this. We'll have a blog post with some more information next week. Sorry for the trouble!

**Comment by brunon80** [comment]
I'm facing this same problem today, but for iOS, command exp build:ios -c, 
I am getting failure message.
iOS: There was an error with this build.

The error log is:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>95AD3FC38A023BA0</RequestId><HostId>SLI/teY2fvQczFGZQiAJFKUXmqwIoLMVRgFdOf9hdQms1NRFTBBExYEKehFr7U5mov7WHGmfvNk=</HostId></Error>

Build id: bc807bc5-32aa-4a3a-9bfd-5d9eb420264c

**Comment by ide** [comment]
Hi @brunon80 - the internal logs say:
SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)

Did you upload your own Apple certificates perhaps? If not, you could try building again, or try clearing the saved build credentials with the -c option.

**Comment by brunon80** [comment]
I uploaded only my distribution certificate and left expo take care all rest, could this caused the problem?

**Comment by brunon80** [comment]
@ide the new build completed without errors, but I cant access the link of my ipa it return a error of Access Denied on a XML

**Comment by desarrollospyro** [comment]
Same problem today, command exp build:ios -c,
I am getting failure message.
iOS: There was an error with this build.

The error log is:
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>8B25AA322633F71D</RequestId><HostId>jw0TDtCEqGSx9l1ywDj5tpnpBcRjN6taCAlX1xo/fgn+SC1pqBGBq4pA6BP2InZKkqx+NyNpzOc=</HostId></Error>
Build id: 186424b9-a101-442e-917e-86b0e1d151bf

**Comment by brunon80** [comment]
@desarrollospyro my problem was solved when I downloaded the .ipa by the panel:
https://expo.io/builds

because the link that was made available in the terminal, after the build was completed, returned access denied on browser, maybe an active session is needed to download

**Comment by desarrollospyro** [comment]
@brunon80 i can't download the .ipa. The button is disabled :( . I've done the build again and now it's queued. I am waiting ....

Thanx for the advice
