### ISSUE TITLE
expo-localization contains ?? in build

### ISSUE THREAD

**Issue by thgh** [expo/expo#13316]
### Summary

I'm publishing a module that depends on expo-localization, it fails to compile when using it in a create-react-app application. This happens with v10 and not with v8 so my current solution is to set resolutions in package.json to "8".

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### Environment

create-react-app-rewired

### Reproducible demo or steps to reproduce from a blank project

The published module contains: `import { locale, locales } from 'expo-localization'`

The create-react-app throws this in dev mode:
```
Failed to compile.

./node_modules/expo-localization/build/ExpoLocalization.js 20:45
Module parse failed: Unexpected token (20:45)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|   get isRTL() {
>     return rtlDetect.isRtlLang(this.locale) ?? false;
|   },
|
```

**Comment by EvanBacon** [comment]
The issue is that `expo-localization` needs to be targeted by babel and transpiled locally.
