### ISSUE TITLE
Redirect instead of native modal in android (StoreReview.requestReview()) 

### ISSUE THREAD

**Issue by amrhassab** [expo/expo#13321]
### Summary

1. SDK Version: 38
2. Platforms(Android/iOS/web/all): Android
3. "expo-store-review": "~2.1.2"

Works perfectly on IOS but on android it redirects to the store instead of deploying a native modal like the documentation claims. Galaxy s9+, Galaxy s7 edge.

Many have asked this question on the forum and have had their issues closed due to a lack of replies over a  30 day period. Which is why I am positing this here. Any assistance would be greatly appreciated.

p.s yes i use StoreReview.hasAction(); StoreReview.isAvailableAsync(); and I have read the play store guidelines.

Since this works perfectly on IOS I do not believe it is an issue with my code.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

38

### Environment

 Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /Users/amrhassaballah/.rvm/rubies/ruby-2.4.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 25, 26, 28, 30
        Build Tools: 23.0.1, 26.0.1, 28.0.2, 28.0.3, 29.0.2, 30.0.1, 30.0.2
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
const hasAction = await StoreReview.hasAction();
const isAvailable = await StoreReview.isAvailableAsync();

        if (isAvailable && hasAction) {
          await StoreReview.requestReview();
        }
```

**Comment by lieberscott** [comment]
Same issue. Works fine on iOS, crashes on Android. Here is a Snack of the issue: https://snack.expo.dev/@wsox1235/71bf18

**Comment by amrhassab** [comment]
@lieberscott you are forced to update expo whenever you are about 4 versions behind (expo go stops working). I upgraded to expo 42 and it works fine now.
