### ISSUE TITLE
barCodeScanner breaks on HarmonyOS

### ISSUE THREAD

**Issue by zhiyi7** [expo/expo#13335]
### Summary

The BarCodeScanner does not working on HarmonyOS..

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

NONE

### Reproducible demo or steps to reproduce from a blank project

Install the app to any device which running HarmanyOS, the BarCodeScanner not working on that device.

**Comment by AdamJNavarro** [comment]
Hey @zhiyi7, can you provide any more details surrounding the issue? Saying it "is not working" while true doesn't gives us much to work with. Do you have any error logs/crash reports, behavior/visual details?

Cheers,
Adam

**Comment by zhiyi7** [comment]
Hi @AdamJNavarro . Thanks for the response. It can shows the content from the camera, the barcode is also in the area, but nothing happens, the callback isn't be called. just like there is no barcode in the image.
