### ISSUE TITLE
Runtime Version from AndroidManifest truncates tailing zeros making "1.10" into "1.1"

### ISSUE THREAD

**Issue by ex3ndr** [expo/expo#13349]
### Summary

My production app was unable to update via OTA and i found that runtime version has been invalid and update was not applied due invalid runtime version

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.7.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.0
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: 41.0.1 => 41.0.1 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.16.1 => 0.16.1 
    npmGlobalPackages:
      expo-cli: 4.3.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Just set `expo.modules.updates.EXPO_RUNTIME_VERSION` to `1.10` and try to perform OTA.

**Comment by cruzach** [comment]
Is the runtimeVersion in your Update manifest incorrect, or is the version in your AndroidManifest.xml incorrect?

**Comment by ex3ndr** [comment]
Both are correct, the issue is in loading "BareManifest" version since reading from AndroidManifest.xml truncates zeros in floats...

**Comment by jkhales** [comment]
> BareManifest
Hi!, how are you able to conclude that the `0` is being truncated>

**Comment by ex3ndr** [comment]
I modified Java code, built it in release, published to google play internal testing and checked logcat. It turns out when you try to read something from Android Manifest it thinks that 1.10 is Float and truncates everything. Method `getString` does not work due cast error from float.

**Comment by cruzach** [comment]
@ex3ndr are you self-hosting your Updates (using `expo export` instead of `expo publish`)? Also, it would be super helpful if you could share your app.json or app.config.js

**Comment by jkhales** [comment]
Hi, we've repro'd this and are thinking about how to handle a long term fix.  

For your current project, @ex3ndr, would you be able to use a semver like syntax like `1.10.0`? This works for me when I tested it. Other suggestions are discussed here: https://stackoverflow.com/questions/2154945/how-to-force-a-meta-data-value-to-type-string

**Comment by ex3ndr** [comment]
In my case i hit it my production app and eventually switched to single-digit version as work-around.

**Comment by jkhales** [comment]
> In my case i hit it my production app and eventually switched to single-digit version as work-around.

OK. Thanks for letting us know about this!
