### ISSUE TITLE
[XDE] Issue with logging dynamic JSX to the console

### ISSUE THREAD

**Issue by hnordt** [expo/expo#1336]
Hello.

I was building a custom Form component and then my CPU usage went to 500% every time I saved some file and the app needed to reload (live reload disabled, remote debugging disabled). I tried to debug my code for hours and found the issue.

Looks like that XDE has some issue with logging dynamic JSX to the console (I use the word dynamic, because if you move the JSX outside the render fn, it's going to work). 

The following code will work, but the `console.log()` won't be displayed in the XDE console and the app gonna take a while to load, Exponent process will explode to 100-500% CPU usage.

```jsx
import React from "react"
import { TextInput } from "react-native"
import Expo from "expo"

const Form = props => {
  console.log(props.inputs.map(input => input))
  return null
}

const App = () => (
  <Form inputs={[<TextInput />, <TextInput />, <TextInput />]} />
)

Expo.registerRootComponent(App)
```

Now if we move the inputs outside <App /> render's method, it's going to work perfectly fine and the `console.log()` will display the inputs in the XDE console:

```jsx
import React from "react"
import { TextInput } from "react-native"
import Expo from "expo"

const Form = props => {
  console.log(props.inputs.map(input => input))
  return null
}

const inputs = [<TextInput />, <TextInput />, <TextInput />]

const App = () => <Form inputs={inputs} />

Expo.registerRootComponent(App)
```

**React version:** 16.0.0
**React Native version:** `https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz`
**Expo version:** 24.0.0
**Did I eject?** No

Anyone has any idea on what's going on?

**Comment by esamelson** [comment]
Hey there - what a weird issue! 🤔  I don't think it has to do with XDE (I'm able to reproduce by just using `exp start`) but rather just some weird React recursion that's happening behind the scenes. Are you able to work around this by just using your second option?

**Comment by hnordt** [comment]
@esamelson I'm just avoiding logging "dynamic" JSX to the console.

I'm glad you were able to reproduce it too, I thought I was going crazy.

**Comment by esamelson** [comment]
cool, I'm going to go ahead and close this then, as I think this might be an upstream issue. Feel free to reopen if it becomes a blocker for you.

**Comment by jpstrikesback** [comment]
We're seeing this as well
