### ISSUE TITLE
Expo-Camera causes crash in TestFlight Apps

### ISSUE THREAD

**Issue by lgzambello** [expo/expo#13361]
### Summary

`import { Camera } from 'expo-camera';`

I am able to use expo-camera (version 11.0.3) completely fine when I am testing it in Expo client on XCode simulator, or even by scanning the QR code to test my app via the Mobile Expo App on iOS. However, any reference of this Camera object in my code will crash my test flight app on iOS. Whether I am using it as a react component, or referencing it like the following, it crashes my app immediately upon startup.
`const [whichCamera, setWhichCamera] = useState(Camera.Constants.Type.back);`

I was able to log the error in Sentry, but haven't seen any similar errors or resolutions online for this particular package: 
`Invariant Violation: Tried to register two views with the same name ViewManagerAdapter_ExponentCamera`

I have tried clearing my lock file and node_modules folder and reinstalling expo-camera. If I run npm ls expo-camera I only see once instance returned.
`└── expo-camera@11.0.3`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.01

### Environment

Expo CLI 4.5.2 environment info:
System:
OS: macOS 11.2.3
Shell: 5.8 - /bin/zsh
Binaries:
Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
npm: 7.7.6 - ~/.nvm/versions/node/v15.4.0/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
IDEs:
Xcode: 12.5/12E262 - /usr/bin/xcodebuild
npmPackages:
expo: ~41.0.1 => 41.0.1
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
react-native-web: ~0.13.12 => 0.13.18
npmGlobalPackages:
expo-cli: 4.5.2
Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/lgzambello/expo-camera-issue

I reproduced this issue in the example repo above. If you try to publish this repo to a TestFlight App it will cause a crash immediately upon opening the app.

**Comment by AdamJNavarro** [comment]
Hey @lgzambello, this is likely a result of you assigning the `camera` variable to the `Camera` import and then trying to set the ref to it. Can you try changing your code to use the `useRef` method and assigning the `Camera` component's `ref` property to that?

Cheers,
Adam

**Comment by brentvatne** [comment]
how are you building this app for testflight? locally or using expo build or eas build?
