### ISSUE TITLE
Amplify Console new Expo-Web SDK 41 project build errors

### ISSUE THREAD

**Issue by kc-nnenu** [expo/expo#13379]
### Summary

Hi all,

I followed this Publishing Websites - Expo Documentation

trying to build multiple fresh expo SDK 41 web project.

However they all failed with the same build errors: ’
2021-06-23T08:08:18.698Z [WARNING]: error @expo/configure-splash-screen@0.4.0: The engine “node” is incompatible with this module. Expected version “>=12”. Got “10.16.0”
2021-06-23T08:08:18.708Z [WARNING]: error Found incompatible module.
’

I attached the full build logs of one of the fresh expo SDK 41 project.
[log-1.txt](https://github.com/expo/expo/files/6700234/log-1.txt)

Is this a known issues building expo-web on Amplify?

Regards,
Kevin

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.6.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\mrx88\AppData\Roaming\npm\yarn.CMD
      npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

0. expo init, choose tabs (type-script)
1. Add the amplify-explicit.yml file to the root of your repo.
2. Push your local Expo project to your GitHub repository. If you haven't pushed to GitHub yet, follow GitHub's guide to add an existing project to GitHub.
3. Login to the Amplify Console and choose Get started under Deploy. Grant Amplify permission to read from your GitHub account or organization that owns your repo.
4. The Amplify Console will detect that the amplify.yml file is in your repo. Choose Next.
5. Review your settings and choose Save and deploy. Your app will now be deployed to a https://branchname.xxxxxx.amplifyapp.com URL

**Comment by brentvatne** [comment]
use a different node version on amplify.

> The engine “node” is incompatible with this module. Expected version “>=12”. Got “10.16.0”

**Comment by kc-nnenu** [comment]
Thanks Brent,

I added -

frontend:
  phases:
    preBuild:
      commands:
        **- nvm install 14
        - yarn install**

under App build specification under Build settings and this solved the errors.
