### ISSUE TITLE
Keyboard pushes up the screen inside bottom sheet component

### ISSUE THREAD

**Issue by alexandermirzoyan** [expo/expo#13378]
### Summary

The keyboard pushes up the screen when it's opened from the bottom sheet component with app.json `"android": {"softwareKeyboardLayoutMode": "pan"}` config.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

![image](https://user-images.githubusercontent.com/48055294/123058834-3fd39080-d41a-11eb-9975-7aeef4f061ff.png)
![image](https://user-images.githubusercontent.com/48055294/123058890-4cf07f80-d41a-11eb-84b4-17a692d5ed50.png)
![image](https://user-images.githubusercontent.com/48055294/123058946-5bd73200-d41a-11eb-946e-21c4570401c2.png)

**Comment by brentvatne** [comment]
please post issue to the bottom sheet component repository
