### ISSUE TITLE
Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by Nostrus** [expo/expo#13371]
### Summary

After installing and initialising Stripe in a working project using `expo install @stripe/stripe-react-native` my app breaks with:

```
Invariant Violation: Native module cannot be null.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

```
    Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Couldn't reproduce with a blank project, might be a more general issue.

**Comment by cruzach** [comment]
Stripe is only available in SDK 41 and after, and please make sure to use the most recent version of Expo Go

**Comment by Nostrus** [comment]
Thanks for the quick response and the tips! It wasn't clear for me from the docs whether SDK 41 is required or not.

**Comment by cruzach** [comment]
Ah sorry about that- the page exists in the SDK 41 docs- https://docs.expo.io/versions/v41.0.0/sdk/stripe/ 

But not in the SDK 40 or below docs- https://docs.expo.io/versions/v40.0.0/sdk/stripe/ <- this will 404

**Comment by Nostrus** [comment]
Yeah, thanks, I noticed that eventually. But at the first few times when arriving at the page it wasn't clear by simply looking at the text. Maybe it could be a bit more explicit? Similarly to the "Platform Compatibility" table it could be shown which SDK level is required as minimum?
