### ISSUE TITLE
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/ExpoKitApp.app/ExpoKitApp' must be signed with the certificate that is contained in the provisioning profile.

### ISSUE THREAD

**Issue by dima** [expo/expo#1337]
Following up on issue #1167, I am running into the same thing except now with ```Payload/ExpoKitApp.app/ExpoKitApp```, claims to not be signed with the certificate contained in the provisioning profile. I've tried ```exp build:ios``` and ```exp build:ios -c```. Upgraded to the latest expo prior to building, currently running 49.0.1. I've published other apps using expo and this used to work just fine prior to upgrading.

A recent build id is: ```2660f58a-0b86-4d49-9bdb-6ba986770522``` in case you want to check it out.

Any ideas?

**Comment by brentvatne** [comment]
@fxfactorial ping pong

**Comment by fxfactorial** [comment]
hi, not clear what the immediate case could be as our builders have gone through several recent changes unrelated to `exp build:ios`. Could you try again ?

**Comment by francescofiori** [comment]
Same error here using exp@49.0.4.
I also get the this error `description length:10501720`.
Any ideas?

**Comment by dima** [comment]
@fxfactorial Still the same thing

**Comment by dima** [comment]
@fxfactorial I've upgraded to 49.2.2 and did a clean build, managed to get a binary up to the iTunes store without a failure, so hopefully this issue is fixed.
