### ISSUE TITLE
Constants.executionEnvironment is undefined for "standalone" build

### ISSUE THREAD

**Issue by kundansingh86** [expo/expo#13374]
### Summary

Hi, 

My app has a feature of SSO login. In order to achieve this functionality, I'm using `Linking.createURL` to generate a redirect URI, however, it's returning the URL as `myscheme://exp.host/@username/appslug/--/Login` instead of `myscheme://Login`

I'm generating the build through [standalone](https://docs.expo.io/distribution/building-standalone-apps/) process. In further investigation of generating this URL, I found that it's happening because the "hasCustomScheme" function in the "[expo-linking/build/Schemes.js](https://github.com/expo/expo/blob/master/packages/expo-linking/build/Schemes.js)" is returning false. After some more debugging I got to know that it is occurring due to **"Constant.executionEnviornment"**, as it becomes undefined. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

39

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.4 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5 
      react: ^16.9.0 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.3 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Created sample project with SDK 39 and issue appeared, however with the latest 41 version there is no issue.

**Comment by brentvatne** [comment]
you are using sdk 39, this property did not exist in sdk 39
