### ISSUE TITLE
Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.

### ISSUE THREAD

**Issue by devfadl** [expo/expo#13383]
### Summary

hi 
i'm getting this error 
[Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.]  startGeofencingAsync 

also 
Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.

using managed workflow

here is my info.plist in App.json 
"infoPlist": {
        "UIBackgroundModes": [
          "location",
          "fetch"
        ],
        "NSLocationUsageDescription": "App requires geolocation to improve the quality of the service",
        "NSLocationAlwaysAndWhenInUseUsageDescription": "App requires geolocation to improve the quality of the service",
        "NSLocationWhenInUseUsageDescription": "App requires geolocation to improve the quality of the service",
        "NSLocationAlwaysUsageDescription": "App requires geolocation to improve the quality of the service",
      }

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.6.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.15.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ^0.13.18 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.6.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

 await Location.requestBackgroundPermissionsAsync();

**Comment by brentvatne** [comment]
are you seeing this in expo go? those keys don't apply in expo go, they only work in standalone apps. you can only use background location in standalone apps currently.

**Comment by devfadl** [comment]
> are you seeing this in expo go? those keys don't apply in expo go, they only work in standalone apps. you can only use background location in standalone apps currently.
Thanks for reply.


it's working perfectly on ios simulator.

the problem exist also when using TestFlight  .

**Comment by brentvatne** [comment]
please provide a minimal reproducible example
