### ISSUE TITLE
GLView getSupportedExtensions

### ISSUE THREAD

**Issue by SebastianMerz** [expo/expo#1338]
Hello,

I'm using a GLView to port some WebGL code over to mobile, and ran into some issues with code that utilizes OpenGL extensions. I checked `gl.getSupportedExtensions()` and got back an empty array. Did I miss enabling/setting up something, or are all OpenGL extensions currently unsupported in Expo?

**Comment by EvanBacon** [comment]
currently the method (`getSupportedExtensions`) is unimplemented, however this doesn't mean that the extensions aren't supported. I usually reference this: https://github.com/expo/expo/blob/0f1b1d59ecfe6ba99d9998176a072fbb4aca4da6/cpp/UEXGL.cpp#L2302-L2869

**Comment by tsapeta** [comment]
Which extensions do you need? We have recently added support for WebGL 2.0 which has built-in what most WebGL 1.0 extensions do (such as `WEBGL_draw_buffers`, `OES_vertex_array_object`). This should be available in the next SDK.
If you don't want to wait for it and your extension only adds a constant, it's very likely it will work if the constant is already exported to `gl` object or you know the value of the constant.

**Comment by SebastianMerz** [comment]
`OES_vertex_array_object` is the big one.

What's the ETA for the next SDK version?

**Comment by tsapeta** [comment]
Probably 16th of February

**Comment by tsapeta** [comment]
@SebastianMerz 
We just released SDK 26 which introduces WebGL 2.0. I'm sorry to have kept you waiting so long. I hope this new feature will reward you :)
