### ISSUE TITLE
OTAs don't work in Expo 41

### ISSUE THREAD

**Issue by yuliankarapetkov** [expo/expo#13381]
### Summary

I'm trying to do an OTA by publishing to a specific release channel:

```
expo publish --release-channel 123
```

The result in the console is successful:
```
Publish complete
```

However, neither our Android app, nor the iOS one get updated. Everything used to be working fine when we were running on expo `38`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41.0.0

### Environment

Expo CLI 4.5.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.6.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.6.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 4.5.0
    Expo Workflow: managed

**Comment by cruzach** [comment]
Have you built the app on SDK 41 before publishing? For an OTA to be downloaded, the binary itself must be on the same SDK version & release channel. I tested this myself on an iOS build on SDK 41 just now and it's working as expected, so please provide the exact steps to reproduce, starting with a blank project

**Comment by yuliankarapetkov** [comment]
We've built the app on SDK 41 several times so this shouldn't be the case.

**Comment by cruzach** [comment]
Once again, I just tested this myself so please provide the exact steps to reproduce, starting with a blank project

**Comment by brentvatne** [comment]
as @cruzach requested, we need exact steps to reproduce. this is not a problem that we are able to reproduce.

**Comment by yuliankarapetkov** [comment]
@cruzach @brentvatne 

We found the issue and it's on our end - sorry about the false flag! After updating Expo from `39` to `41` we have forgotten to import `Updates` from `expo-updates`, instead of importing it from `expo`. What's weird is that we haven't got any errors neither at compile time, nor at run time.

Anyway, thanks for your help!
