### ISSUE TITLE
Accessing navigator.geolocation with GPS turned OFF in android > 6

### ISSUE THREAD

**Issue by marcosmartinez7** [expo/expo#1339]
Hi, 

im running an expo app, 

 im working on a react-native application, using expo and react-native-maps, and i need to get the latitude and longitud of the user current position.Im using navigator.geolocation API for thatwith the GPS turned on i have no problems, but i need to get the current position without GPS, based on the network provider.The problem is that when the application runs with expo on androiod > 6 i get this error:

> 21:50:53: Finished building JavaScript bundle in 449ms 21:50:55: **Location services are disabled** - node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:80:57 in - node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:347:19 in __invokeCallback - ... 4 more stack frames from framework internals

In IOs and android <=5 it works great.

```
class MyComponent extends Component {

    componentWillMount = () => {    
            this.getCurrentLocation();    
    }
    getCurrentLocation = () =>
         navigator.geolocation.getCurrentPosition(
            (position) => {
                let currentUserPosition = position.coords;
                alert(JSON.stringify(currentUserPosition));
            },
            (error) => {
                console.log(error);
            },
            {
                enableHighAccuracy: false,
                timeout: 20000,
                maximumAge: 0,
                distanceFilter: 10
            }
        );

}
```

And this are my package.json depencendies:

> 
> "dependencies": {
>     "expo": "23.0.4",
>     "native-base": "^2.3.5",
>     "react": "16.0.0",
>     "react-native": "0.50.4",
>     "react-native-extend-indicator": "^0.1.2",
>     "react-native-maps": "^0.19.0",
>     "react-native-maps-directions": "^1.3.0",
>     "react-native-router-flux": "4.0.0-beta.21",
>     "react-navigation": "1.0.0-beta.21",
>     "react-navigation-redux-debouncer": "^0.0.2",
>     "react-redux": "^5.0.6",
>     "redux": "^3.7.2",
>   }

expect that navigator.geolocation get the location based on the network provider in that situation (without gps), the specification saids that..

i also tried with the Geolocation API of expo (tried this example: https://snack.expo.io/@schazers/expo-map-and-location-example) , and with the GPS turned OFF i cant get my location..

is this related with expo? how can i enable location services on android when using the expo app?

thanks in advance

**Comment by esamelson** [comment]
Hi there - that error (`Location services are disabled`) is thrown if no location providers are available, i.e. the user has turned off location services on their device entirely. In this case, there is no way for an app to programmatically get any location information from the device. It sounds like what you want is to switch location services to the "Battery saving" mode, rather than turning them off entirely - have you tried that? https://support.google.com/accounts/answer/3467281?hl=en that should switch it to the network provider.

**Comment by marcosmartinez7** [comment]
Hi, thanks for your answer. 

I want that my application get latitude and longitude of the user ubication without using gps. 

The high accuracy method saids:

High accuracy
This mode uses GPS, Wi-Fi, mobile networks, and other sensors to get the highest-accuracy location. It uses Google's Location service to help estimate your device's location faster and more accurately.

So.. i understand that navigator.geolocation will use wifi or mobile networks (or other sensor) to get the location if GPS is off... but the situation that i am facing is that expo throws that error when my device has the GPS off and the mode is set in high accuracy.

I tried in other devices too, with android 6 and 7 with the same results. 

In version older than 5 i havent experimented this error, it gets the location without GPS on

**Comment by esamelson** [comment]
Hey, sorry you're still having trouble. Can you clarify what you mean when you say "GPS is off"? If you mean that you've turned off Location entirely on the device, that error is expected, as there's no way to get a location in that case.

If you want to use the network provider without the actual GPS, you need to leave Location turned on, but switch to "Battery saving" mode (away from "High accuracy").

**Comment by marcosmartinez7** [comment]
Yes, i mean getting the position based on network provider (IP address, triangulation) and not using the GPS chip

So.. are you telling me that with this api https://docs.expo.io/versions/latest/sdk/location.html i cannot get my latitude and longitude only with WIFI on? im talking about this: https://stackoverflow.com/questions/6694391/android-get-current-location-of-user-without-using-gps-or-internet

thanks in advance

**Comment by esamelson** [comment]
Yes, what you want is possible with the `Location` API you've linked to. However, in the phone settings you must have Location turned on. (Settings app -> Security & Location -> turn Location on). If Location is not turned on, nothing on the phone can get a latitude and longitude, not even using the network provider.

Note that having Location turned on does not necessarily mean that the GPS chip will be used. You've correctly configured your app to use the network provider (and not the GPS) by setting `enableHighAccuracy: false`. But the error you're getting (`Location services are disabled`) is only triggered if you've turned off Location on the phone entirely. You cannot get any latitude/longitude if Location is turned off.

**Comment by marcosmartinez7** [comment]
Hi, 

So the Location api calls this method in android:

https://developer.android.com/reference/android/location/LocationManager.html#getLastKnownLocation(java.lang.String)
Maybe tu use WIFI i have to allow ACCESS_COARSE_LOCATION ?

https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_COARSE_LOCATION

Is there a way to tell expo to include ACCESS_COARSE_LOCATION? Because i cannot touch the AndroidManifest.xml, i dont have access to the native code, that will be only possible if i eject my proyect.

**Comment by esamelson** [comment]
Hey, have you tried configuring `android.permissions` in your project's `app.json`? https://docs.expo.io/versions/latest/guides/configuration.html#permissions If that field is defined, then whatever permissions you specify (along with the default ones) will be included in your app's AndroidManifest.xml, and no others.

**Comment by marcosmartinez7** [comment]
Yes, ive already tried that, but that is in the "Standalone Apps Only. iOS standalone app specific configuration" section, so, i need to create an apk for test it right? I mean, expo in development mode is not using the app.json, im i wrong? 

Is there a way to include something in androidmanifest.xml without generation an apk with exp:build-android ? 

thanks in advance

**Comment by brentvatne** [comment]
probably we need to add support for requesting coarse location permission, it looks like we always request either fine or coarse: https://github.com/expo/expo/blob/2a4739f6224919ec4e913d45cc7c2448747ebb18/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/PermissionsModule.java#L132-L160

**Comment by marcosmartinez7** [comment]
@brentvatne  yeah, COARSE is like the second option, but i dont know why.. and as i said, im trying to not eject the app and work over the expo api

**Comment by marcosmartinez7** [comment]
Im gonna put here the S.O discussion: 

https://stackoverflow.com/questions/48454305/cannot-get-current-position-without-gps-on-react-native-with-navigator-geolocati

It would be important in my opinion that integrate the posibility of location.networn on expo SDK without ejecting the project. 

Let me know you guys if youre gonna work on this, we would really apreciate that

kind regards

**Comment by esamelson** [comment]
@marcosmartinez7 do you have a specific repro case (even another app or website) that successfully gets your wifi location while Location is turned off on the device?

I tried running the live example here https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation and I got `Unable to retrieve location` if I turned off Location.

We can add in the ability to request only ACCESS_COARSE_LOCATION, but I don't think this will do what you want. The user will still need to turn on Location in order for your app to get a wifi location.
