### ISSUE TITLE
[SDK 41] Standalone app crashes on ios when built with EAS while using AsyncStorage

### ISSUE THREAD

**Issue by Infinitism** [expo/expo#13395]
### Summary

When using AsyncStorage from the package recommended by the SDK 41 upgrade, it breaks the standalone ios app when the app is built using "eas build". It works fine on standalone android. 

The way to reproduce this is call AsyncStorage.getItem('key') in app.js and build it with eas build -p ios and submit that version to the store. It will crash the app right away. 

To fix this issue, you'll have to build the app using expo build. 

It has something to do with what native code is used when building the ios standalone app. 

Check this issue for more information: https://github.com/expo/expo/issues/13391

Is there a way we could use EAS build using the native code expo build uses as well?

This is such a major issue and nearly impossible to debug without knowing what caused the error initially as it'll simply crash. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.7.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/refs/tags/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

The way to reproduce this is call AsyncStorage.getItem('key') in app.js and build it with eas build -p ios and submit that version to the store. It will crash the app right away. 

To fix this issue, you'll have to build the app using expo build.

**Comment by brentvatne** [comment]
hi there! please provide a reproducible example. what you have provided is insufficient.

asyncstorage most certainly does not crash in apps built with eas build under normal conditions and so there is something you are doing here that is different than expected. you may, for example, be using the wrong asyncstorage library. as per https://blog.expo.io/expo-sdk-41-12cc5232f2ef you need to use `@react-native-async-storage/async-storage`

**Comment by Infinitism** [comment]
This is what I have that caused the build to fail when built with eas but not expo build.

App.tsx
import AsyncStorage from '@react-native-async-storage/async-storage';

`export default class App extends React.Component {
  async componentDidMount() {
    await Font.loadAsync({
      Roboto: require('native-base/Fonts/Roboto.ttf'),
      Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf'),
      ...Ionicons.font,
      ...MaterialCommunityIcons.font
    });
        
    try {
      const value = await AsyncStorage.getItem('didOnboarding');
      if (value == null) {
        AsyncStorage.setItem('didOnboarding', 'true');
        isFirstLaunch = true
      } else {
        isFirstLaunch = false
      }
    } catch(error) {
      Sentry.Native.withScope((scope) => {
        // Submit errors to the server here?  
        scope.setTag('deetz-error', 'Error with AsyncStorage in App.tsx');
        Sentry.Native.captureException(error);
      });
    }
    this.setState({ isReady: true });
  }`
  
  This crashed the app on eas build but did not with expo build. I just tested it in TestFlight and it worked.

**Comment by brentvatne** [comment]
please create a minimal example that i can clone from github. https://stackoverflow.com/help/minimal-reproducible-example

the code you have provided includes unrelated code, eg: Sentry.

**Comment by Infinitism** [comment]
This is what I have that caused the build to fail when built with eas but not expo build.

App.tsx
import AsyncStorage from '@react-native-async-storage/async-storage';

`export default class App extends React.Component {
  async componentDidMount() {
    await Font.loadAsync({
      Roboto: require('native-base/Fonts/Roboto.ttf'),
      Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf'),
      ...Ionicons.font,
      ...MaterialCommunityIcons.font
    });
        
    try {
      const value = await AsyncStorage.getItem('didOnboarding');
      if (value == null) {
        AsyncStorage.setItem('didOnboarding', 'true');
        isFirstLaunch = true
      } else {
        isFirstLaunch = false
      }
    } catch(error) {
      //log error
    }
    this.setState({ isReady: true });
  }`
  
  This crashed the app on eas build but did not with expo build. I just tested it in TestFlight and it worked.

**Comment by brentvatne** [comment]
please share a github repo and a link to a build page on eas build where you have built it

**Comment by cmaycumber** [comment]
I'm running into the same issue. Everything works fine for local development but after running `eas build` and trying to use the development client I get the error: `[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.`

**Comment by brentvatne** [comment]
> please share a github repo and a link to a build page on eas build where you have built it. i'm eager to help but you need to convince me that this is an issue.

:)

**Comment by cmaycumber** [comment]
> please share a github repo and a link to a build page on eas build where you have built it. i'm eager to help but you need to convince me that this is an issue.

@brentvatne I'm in a relatively complex monorepo. Would just the build URL be helpful at all while I work on a reproduction?

**Comment by brentvatne** [comment]
@cmaycumber - we can wait for your repro! i would say the monorepo is likely the issue. maybe, for example, you don't actually have async-storage listed in your project dependencies - this is needed for react-native autolinking to work.

**Comment by cmaycumber** [comment]
This makes a lot of sense. Let me try a few things first then. 

Thanks for the feedback.

**Comment by Infinitism** [comment]
No, I still run into the issue. I just use expo build instead of eas build because that's what breaks your app in production. I haven't had any issues since I switched to expo build. I'd recommend that over eas build.

**Comment by cmaycumber** [comment]
After taking @brentvatne advice. I was able to solve my issue by moving packages from the root of my monorepo into the expo project.

**Comment by cauldyclark15** [comment]
> No, I still run into the issue. I just use expo build instead of eas build because that's what breaks your app in production. I haven't had any issues since I switched to expo build. I'd recommend that over eas build.

same here, i am using SDK 43 and it looks like `react-native-async-storage/asyncStorage` is broken in EAS build

```
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':react-native-async-storage_async-storage:generateReleaseRFile'.
[stderr] > Could not resolve all files for configuration ':react-native-async-storage_async-storage:releaseCompileClasspath'.
[stderr]    > Could not resolve com.facebook.yoga:proguard-annotations:1.14.1.
[stderr]      Required by:
[stderr]          project :react-native-async-storage_async-storage > com.facebook.react:react-native:0.64.2
[stderr]       > Could not resolve com.facebook.yoga:proguard-annotations:1.14.1.
[stderr]          > Could not get resource 'https://jcenter.bintray.com/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom'.
[stderr]             > Could not GET 'https://jcenter.bintray.com/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom'.
[stderr]                > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/6.9/userguide/build_environment.html#gradle_system_properties
[stderr]                   > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[stderr]       > Could not resolve com.facebook.yoga:proguard-annotations:1.14.1.
[stderr]          > Could not get resource 'https://jcenter.bintray.com/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom'.
[stderr]             > Could not GET 'https://jcenter.bintray.com/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom'.
```
