### ISSUE TITLE
Managing multiple environments for an app

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#134]
From Slack:

> What is common practice to handle different environments with expo, i.e.

> 1) ~Run in DEV mode for expo client~ (you can do this with [Expo.Constants.AppOwnership](https://docs.expo.io/versions/v16.0.0/sdk/constants.html#expoconstantsappownership)
> 2) Build in STAGING mode to publish up in test flight
> 3) Build in RELEASE mode to publish in app store

> how would these be configured in app.json and available as globals within the app?

-----------------------------------------

Currently the only way to release to different environments is by having a slug for each environment (or user) and changing the slug in exp.json (eg: slug `myapp-staging`). It would be better to have first class support for different deployment environments.

**Comment by dikaiosune** [comment]
Moved to a canny request: https://expo.canny.io/feature-requests/p/support-multiple-release-channels

**Comment by oliverbenns** [comment]
I wrote a bash script to handle this: https://github.com/oliverbenns/expo-deploy

**Comment by ChrisWphoto** [comment]
[exp-deploy-cli](https://github.com/Preposterous/exp-deploy-cli) This also look promising.
