### ISSUE TITLE
Upgrade to react-native-screens 3.4.0

### ISSUE THREAD

**Issue by hunterbmt** [expo/expo#13405]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by hunterbmt** [comment]
Could we upgrade to react-native-screen 3.4.0 instead of stopping at 3.3.0 for SDK 42 ?
3.4.0 contains an important patch that impact all ios app using react-native-screens (https://github.com/software-mansion/react-native-screens/pull/986)

**Comment by Razorholt** [comment]
Looks like they listened to you :)
`react-native-screens": "~3.4.0"`

**Comment by brentvatne** [comment]
we did this several days ago already: https://github.com/expo/expo/pull/13370 :)
