### ISSUE TITLE
Deep Links on Android very slow when app open in background

### ISSUE THREAD

**Issue by Garfield1002** [expo/expo#13419]
## Problem
When using deep links on Android when the application is open in the background, the average time between when choosing to open a link with app is `5s`. During this time, the screen is greyed out and not responsive. This makes the use of deep links impossible.

## Expected Behavior
Have the application open instantaneously (or at least in a lot less then 5s..).

## Note
This error does not occur in `Expo Go`.

The application opens properly from the link when it is stopped.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

## Expo
Expo CLI 4.7.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.4 - C:\Program Files\nodejs\node.EXE       
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
        Android NDK: 20.1.5948944
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

## Physical Devices
Samsung Galaxy S6 running Android 7.0
Samsung Galaxy A5 running Android 7.0

### Reproducible demo or steps to reproduce from a blank project

Generate a new expo project (I tested with `blank` and `blank (TypeScript)` projects):
```bash
$ expo init
```

Add support for a [deep link](https://docs.expo.io/guides/linking/#deep-links-on-android) in `app.json`:
```json
"intentFilters": [
        {
          "action": "VIEW",
          "data": [
            {
              "scheme": "https",
              "host": "example.com",
              "pathPrefix": "/"
            }
          ],
          "category": ["BROWSABLE", "DEFAULT"]
        }
      ]
```

Build the application (I chose `apk` and `Generate new keystore`)
```
$ expo build:android
```

Install the `.apk`, and open the application. With the application open in the background, open [https://example.com/](https://example.com/).

**Comment by byCedric** [comment]
Hi @Garfield1002, thanks for the issue report. Unfortunately, I couldn't reproduce this issue. I created a new project based on the blank typescript template. You can see that [in this repository](https://github.com/byCedric/expo-issue-13419). From there I built a [new Android APK](https://github.com/byCedric/expo-issue-13419/runs/2930984376?check_suite_focus=true) and installed it on my device. 

If you can provide a repository where this issue occurs, I would be happy to dig into it!

![example-optimized](https://user-images.githubusercontent.com/1203991/123627916-d89b4f00-d812-11eb-88e3-a924ccf9e106.gif)

In this test, I'm deep linking from CLI from a cold start and from the background state, using:

```bash
$ adb shell am start -a android.intent.action.VIEW -d "https://example.com/" com.bycedric.expoissue13419
```

**Comment by Garfield1002** [comment]
I tried it in the emulator on multiple android versions and it worked fine.

With physical devices the error only occurs on Samsung devices with Android 7.0 (I tested multiple devices).

Thank you for your help.

**Comment by Garfield1002** [comment]
I was also unable to reproduce the error with the galaxy nexus emulator.
