### ISSUE TITLE
Is anyone else not able to load expo iOs app?

### ISSUE THREAD

**Issue by oporter1** [expo/expo#13415]
### Summary

the expo go app is continuously loading, the app itself won't open let alone my app. Is anyone else seeing this? I made sure to update the app, deleted and reinstalled, tried with tunnel/LAN/local...are the servers down or did you stop supporting ios v 14.6?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

14.6

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.3.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.14 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      Android SDK:
        API Levels: 26, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.1 => 41.0.1 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.0.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

it's not a code thing...just an app issue so no demo to put here. 

to reproduce, open the expo go app on iOs and see if it loads.

**Comment by byCedric** [comment]
Hi @oporter1, the servers are up and should support 14.6. If you can provide the exact steps you are trying that don't work for you, we might be able to help. You could try running your app on [the iOS simulator](https://docs.expo.io/workflow/ios-simulator/) and see if that works, it would exclude any issues in the local bundler.
