### ISSUE TITLE
[SDK 42 beta 2] error: package expo.modules.permissions does not exist

### ISSUE THREAD

**Issue by sshquack** [expo/expo#13427]
### Summary

Trying to verify the fix for https://github.com/expo/expo/issues/13407 and https://github.com/expo/expo/issues/13100. So upgraded to SDK 42 beta 2 which now throws `error: package expo.modules.permissions does not exist`

```
/Users/foo/Desktop/code/expo/boring-app/android/app/src/main/java/com/boringapp/so/MainApplication.java:22: error: package expo.modules.permissions does not exist
import expo.modules.permissions.PermissionsPackage;
                               ^
Note: /Users/foo/Desktop/code/expo/boring-app/android/app/src/debug/java/com/boringapp/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.

```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42 beta 2

### Environment

```
❯ expo diagnostics

  Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.n/bin/node
      Yarn: 1.22.10 - ~/.n/bin/yarn
      npm: 7.19.0 - ~/.n/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: next => 42.0.0-beta.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- Same as https://github.com/expo/expo/issues/13407 and https://github.com/expo/expo/issues/13100
- Repro project is at https://github.com/sshquack/boring-app-01

**Comment by brentvatne** [comment]
you need to remove the permissions import from mainapplication because it is not included in react-native-unimodules anymore. see https://github.com/expo/expo/commit/63b5a92b8d2f9cb8abf68daab0e499984cc73097

**Comment by sshquack** [comment]
@brentvatne shouldn't `expo upgrade` take care of that? Or is this something every user upgrading from 41 to 42 have to do manually?

**Comment by sshquack** [comment]
@brentvatne thanks for the context! That trade-off makes sense. I'll watch out for these steps in the upgrade steps blog.

Got past this error. Running into another exception here https://github.com/expo/expo/issues/13428
