### ISSUE TITLE
[SDK 42 Beta] Fails to run in Expo Go TestFlight

### ISSUE THREAD

**Issue by chadwatson** [expo/expo#13437]
### Summary

After upgrading to SDK 42 Beta, I ran `expo start --clear`, scanned the QR code on my iPhone 12 Pro to open the app in Expo Go (downloaded via TestFlight), and the app fails to load.

![IMG_4991](https://user-images.githubusercontent.com/5865074/123845229-8cffa880-d8d9-11eb-9d5c-e4ab44a1e02a.PNG)

<img width="1440" alt="Screen Shot 2021-06-29 at 12 50 12 PM" src="https://user-images.githubusercontent.com/5865074/123845246-9426b680-d8d9-11eb-90c3-7c484b9ecbfa.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK 42 Beta

### Environment

Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.12.0/bin/yarn
      npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0-beta.2 => 42.0.0-beta.2
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.3.5
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I don't think I can reproduce this in a Snack, since SDK 42 Beta is not available there.

**Comment by brentvatne** [comment]
hi there! it looks like you can't reach your server on the network? does it work in a sdk 41 project? can you share a reproducible example? it doesn't need to be in snack

**Comment by chadwatson** [comment]
@brentvatne Upon further investigation the issue appears to have come from attempting to eject prior to the upgrade. I don't think the issue is with the SDK. Thanks.
