### ISSUE TITLE
expo-camera only works on desktop Safari - no chrome or mobile safari

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo#13431]
### Summary

The `Camera` component only works on safari desktop, no chromium browsers. On mobile it fails alltogether.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41

### Environment

```shell
  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

[See this snack](https://snack.expo.io/@mentor/biased-coffee).

Reproduce by:

1. Opening snack in safari, accept permission, see yourself through webcam
2. Opening on chromium and/or mobile safari, no dice

**Comment by byCedric** [comment]
Thanks for reporting this issue. I could only reproduce this on Safari Mobile, but it should be supported since we use the [Media Stream API](https://caniuse.com/?search=MediaStream). Desktop with Firefox, Safari, and Chrome seems to work fine on my end.

<img width="704" alt="Screenshot 2021-06-29 at 12 55 36" src="https://user-images.githubusercontent.com/1203991/123789048-05b43400-d8dd-11eb-87d7-328edaed6b23.png">

- Left is Chrome
- Right is Safari

**Comment by actuallymentor** [comment]
Interesting. For me it only works on desktop Safari, not on iPads or Android `chromium` based browsers.

Let me know if I can supply any other debugging info to get to the bottom of this.

**Comment by Simek** [comment]
@byCedric Can confirm that it's not working on Windows in Chrome, Edge and FF:

### Chrome

<img width="264" alt="Untitled" src="https://user-images.githubusercontent.com/719641/127173530-24b0dde9-0b88-49c8-9077-2d515806a112.png">

### Edge

<img width="278" alt="Untitled" src="https://user-images.githubusercontent.com/719641/127173331-1d384cf1-0474-48df-b1fb-62f11798eb3d.png">

**Comment by zachdixon** [comment]
This may or may not be related, but also having some funky issues with expo-camera in react-native-web. What I've noticed is `requestPermissionsAsync` actually turns on the camera and never turns it off, so when the preview tries to render, it returns an error since it's already running. In the example snack, it works fine, but move the requestPermissionsAsync outside of the if and remove the `Camera` component, and notice the camera still turns on. Is this expected behavior? I've tried `pausePreview` but that didn't work.

**Comment by jackkinsella** [comment]
I'm also encountering this issue when running an Expo app (which works perfectly in Android and iOS native) via Expo Web as a PWA in Safari on my iPad.

I noticed that the camera stream shows if I downgrade to `expo-camera` version 10. However I get the error "The method or property expo-camera.navigator.permissions API is not available on web, are you sure you've linked all native dependencies properties"

Upgrading to `expo-camera` version 11 causes the feed to disappear... however in this case the permission is granted.

**Comment by jackkinsella** [comment]
Still broken in `expo-camera` v12

**Comment by grzabrodskiy** [comment]
Hi everyone, any update on this? I am running into the same issue when using it on the web on mobile (Chrome and Safari)

**Comment by andrioid** [comment]
I stumbled upon this issue, when I thought the Camera stuff was broken on mobile web. Then I found [https://docs.expo.dev/guides/permissions/#permissions-on-web](this in the Expo docs).

> On web permissions like the Camera and Location can only be requested from a secure context, e.g. using https:// or http://localhost. This limitation is similar to Android's manifest permissions and iOS's infoPlist usage messages and enforced to increase privacy.

I tried accessing the application through ngrok (proxy service) and it worked absolutely fine on my iOS, as long as there was *https*. I hope that helps.

**Comment by grzabrodskiy** [comment]
Thanks @andrioid,

I was using _https_, somehow it still did not work.

**Comment by pfndesign** [comment]
it's still exists but only in Safari mobile and i fixed it by mounting the camera when permission is granted
