### ISSUE TITLE
Video recording in some devices give the wrong orientation

### ISSUE THREAD

**Issue by abhishek-raj** [expo/expo#1344]
In some devices(Redmi 1s, Samsung Galaxy S5), the video recorded is in wrong orientation.

https://snack.expo.io/HJj8gkcSG

Here is the code which records the video.

**Comment by abhishek-raj** [comment]
Any updates? @aalices 
Maybe expose option for manually setting orientation for preview and video.
https://stackoverflow.com/questions/3901053/how-to-change-video-orientation-in-mediarecorder-to-portrait

**Comment by brentvatne** [comment]
@aalices is away on vacation at the moment but will be back next week!

**Comment by abhishek-raj** [comment]
@brentvatne Okay. Thank you for updating :D

**Comment by aalices** [comment]
Hello @abhishek-raj, are video always rotated by 90 degrees or it happens only in one screen orientation? Is your screen rotation / app orientation locked?

**Comment by abhishek-raj** [comment]
@aalices Okay, I checked the devices and it seems there isn't a problem with the camera but the playback. The Video component playbacks the video in wrong orientation.

**Comment by abhishek-raj** [comment]
Should I open another issue for Video component or change this issue?

**Comment by terrysahaidak** [comment]
Hello @aalices, I can confirm @abhishek-raj's bug. But need to clarify for you it a little bit. My app is locked to portrait orientation. When I recording a video on my Android devices, I use a local link to it and passing to the video component. It shows me a video upside-down. Right after that, I'm uploading the video to my server and trying with my iPhone as well. The same result. The video is upside-down.
When I'm trying to record a video with my iPhone – everything is good. The video is not upside-down. So the problem is only with android video after recording.

**Comment by condorman** [comment]
Hi, i have same problem with: Android 7.0 (Samsung s7+) . When i record in Portrait orientation the preview camera work fine, but the recorder video is upside-down on device.

**Comment by terrysahaidak** [comment]
Hello, @aalices and @brentvatne. Any updates on it?

**Comment by condorman** [comment]
Hi, I have this problem on different device with Android 7: (Samsung s7+, Samsung A3 etc.. etc..), the video is upside down on 40% of my installed client APP :(.
The "expo/android/cameraview" is a fork of "android/cameraview" and I can not understand why GOOGLE it has not yet been solved this critical BUG
On Android documentation I find this method [setOrientationHint](https://developer.android.com/reference/android/media/MediaRecorder.html#setOrientationHint%28int%29).
I download Expo SDK and change different line code and now the video have the correct portrate orientation on MY device, some users could help to test these changes on other version of android and device?

Code change: File [Camera1.java](https://github.com/expo/expo/blob/master/android/cameraview/cameraview/src/main/api14/com/google/android/cameraview/Camera1.java) **line 573**: the formule
`(360 - (mCameraInfo.orientation + screenOrientationDegrees) % 360) % 360` is good for FRONT camera PREVIEW, but is not good for calculate the output video orientation. so i change in this line:

` private int calcDisplayOrientation(int screenOrientationDegrees, , boolean checkFrontBack) {
        if (checkFrontBack && mCameraInfo.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
            return (360 - (mCameraInfo.orientation + screenOrientationDegrees) % 360) % 360;
        } else {  // back-facing
            return (mCameraInfo.orientation - screenOrientationDegrees + 360) % 360;
        }
    }`

And i change the parameter on **setOrientationHint** for ignore the upside down rotation **on line 736** with:

`mMediaRecorder.setOrientationHint(calcDisplayOrientation(mDisplayOrientation,false));`

I'm getting many complaints related to this problem, I hope in your kind help, thank you!

**Comment by aalices** [comment]
@condorman thanks for your commitment! I've actually managed to fix this by using `calcCameraRotation` instead of `calcDisplayOrientation`. It is also used for setting images rotation. The fix works for Xperia XA2. This would be cool if you test this solution on your devices - if it goes okay, I'll create a PR with the fix.

**Comment by condorman** [comment]
@aalices work fine on my Samsung s7+ and Samsung A3!!!! thank you!!

**Comment by faustoct** [comment]
any update of this fix ?

**Comment by esamelson** [comment]
@faustoct this fix is in SDK 26 which is out now. Are you still seeing this issue on an SDK 26 project?

**Comment by faustoct** [comment]
@esamelson didn't upgrade to SDK 26. Got lot of problem when upgrade to SDK 25. Is there a tutorial, doc or anything to help upgrade without problem?

**Comment by esamelson** [comment]
@faustoct - sorry to hear you had trouble when upgrading before :( have you tried following the instructions here https://blog.expo.io/expo-sdk-v26-0-0-is-now-available-2be6d9805b31 (scroll to bottom, "Upgrading Your App") ?

If you have trouble again this time around, please [post on our forums](https://forums.expo.io/c/help) and we'd be happy to help!

**Comment by faustoct** [comment]
@esamelson thank you. I will have a look at it.

**Comment by faustoct** [comment]
@esamelson what about this constants in app.json
````
...
    "detach": {
      "scheme": "exp3c86f2eb15904f6eae8b68931b551142",
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.3.3-sdk25.0.0-xxxx.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.3.0-sdk25.0.0-xxxx.tar.gz"
    },
...
````

**Comment by abhishek-raj** [comment]
Hey, any way to see which SDK version are we using?
I think I am running on SDK26. Still facing this issue on Redmi 1S. It is on the latest firmware as provided by Mi. Android version 4.4.4. MIUI version 9.2.2.0. 
Expo client version is 2.4.0.
I have selected latest SDK version on snack:

https://snack.expo.io/SkTk6EtsM

**Comment by faustoct** [comment]
I found it where https://github.com/expo/xdl/search?utf8=%E2%9C%93&q=iosExpoViewUrl&type=
````
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.3.3-sdk25.0.0-e7a4361a-631d-4caf-9692-1880d71c394a.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.4.4-sdk26.0.0-3bd935c7-cdd3-4002-8e44-4df857a675f2.tar.gz"
````
Would be nice have it in your docs.

**Comment by esamelson** [comment]
@faustoct - for upgrading android expokit, we suggest right now that you create a new project with `exp init`, run `exp detach` inside of there, and then copy over all of your custom code (including reinstalling other third party native modules). We're working on a better solution so it might be worth waiting for SDK 27 if this would be a big headache for you.

Please post any further questions on the [forums](https://forums.expo.io/c/help) instead, unless they have to do with this specific issue (flipped video recording).

**Comment by esamelson** [comment]
@abhishek-raj - check your app.json file, or the lower right corner of the snack (looks like yours is on SDK 26). It may be an issue with your phone, cc @aalices .

**Comment by abhishek-raj** [comment]
@esamelson Okay. Looks like it is device specific. Will try to find another Android 4.4.4 device and try and report back.
Newer Mi devices work perfectly.

**Comment by faustoct** [comment]
@esamelson Looks like I updated the project successfully without create new one. Let's see if I can run the project/app normally.

**Comment by faustoct** [comment]
@esamelson will keep at version 25.0.0.. for a project in product is very painful recreate the entire project and keep everything working fine analytics, libs, notification, etc. Is there a issue to address it, easy way to upgrade between versions?

**Comment by esamelson** [comment]
@faustoct see https://github.com/expo/expo/issues/1503, and please don't post in this thread any more unless it pertains directly to the original issue! :)

**Comment by abhishek-raj** [comment]
@esamelson @aalices Hey, I can confirm the SDK26 solved the problem with camera on Samsung devices. Also I checked on my Redmi 1s device and it seems it records the video in correct orientation but doesn't play it back in correct orientation.

I have a app which records the video and uploads them to a server. So when I record on Redmi 1s, the video seems that is rotated which isn't. It just plays it back in incorrect orientation(which made me place this device wrongly under the same issue). The video when uploaded and is played back on another device plays in correct orientation. Also any video that is played on this device is rotated. So it's really a problem with the code in the Expo.Video module of the expo client.

I am opening a new issue for the Video component of Expo. Thank you for solving this.
