### ISSUE TITLE
[SDK 42 beta] iOS EAS build failing after upgrading to SDK 42 beta (local build still working)

### ISSUE THREAD

**Issue by bherila** [expo/expo#13441]
### Summary

- Run ` eas build -p ios --clear-cache` after upgrading to SDK 42 beta 

- Tried deleting node_modules, Podfile.lock, Pods and then reinstall everything

```

› Linking   Shone » shonelive
⚠️  ld: duplicate method '+moduleName' in
┌─[category]: RCTAgoraRtcChannelModuleBridge.o react-native-agora/libreact-native-agora.a
└─[class]: RCTAgoraRtcChannelModule.o react-native-agora/libreact-native-agora.a
⚠️  ld: duplicate method '+moduleName' in
┌─[category]: RCTAgoraRtcEngineModuleBridge.o react-native-agora/libreact-native-agora.a
└─[class]: RCTAgoraRtcEngineModule.o react-native-agora/libreact-native-agora.a

❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64


```

Compiles fine with Xcode 12.5 on local mac  (Big Sur 11.4)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Working: Xcode 12.5.1, Mac OSX (Big Sur 11.4)

Not working: ` eas build -p ios --clear-cache`

### Reproducible demo or steps to reproduce from a blank project

I don't have a minimal repro right now but can provide one if needed.

**Comment by brentvatne** [comment]
can you link to your build page please?

**Comment by bherila** [comment]
will update the build profile accordingly, thanks for the pointer! 
yes xcode 12.5 may be needed

Here is the link to the build page. https://expo.io/accounts/shone-live/projects/shone/builds/7f5cd020-1c3b-4ed4-a710-185863df7a09

**Comment by bherila** [comment]
Awesome! Adding setting image to "latest" worked. 

Thanks a lot!

**Comment by gabrielbezerra81** [comment]
I have this same error, but I'm building in Xcode.

My environment is Xcode 12.3, Mac catalina 10.15.7, Expo 42

**Comment by brentvatne** [comment]
@gabrielbezerra81 - read the above. you need to update xcode
