### ISSUE TITLE
iOS App crashes with SIGABRT in TestFlight only

### ISSUE THREAD

**Issue by thomas-shares** [expo/expo#13456]
### Summary

Hi all,
I'm raising a defect here for lack of a better place at the moment. I have built an Expo app and I have a hard crash (SIGABRT). This happens only on iOS and only on iPhones 11 and 12 and only with builds that were done with help of the Expo build service.

Debug builds and optimised local builds all work fine and on Android as well. So all this makes debugging the problem not straight forward. From what I understand I need a DSYM file in order to make the stacktrace (attached) more readable. Any ideas how I could get closer to the cause of this problem as it stops us at the moment from submitting our app to the App Store. Or any ideas on a workaround?

Your help would be much appreciated.
Thomas

[expo.txt](https://github.com/expo/expo/files/6742273/expo.txt)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.7.0 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.18.1 - /usr/local/bin/npm
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

If it is really needed I can try and make a minimal case, but as TestFlight is required for a reproduce this would be very time consuming.

**Comment by brentvatne** [comment]
hi there! unfortunately the error text is not useful and so we will need a reproducible example. most likely some of your app code is causing it to crash. you can try looking in the xcode crashes organizer to see if it gives you better information

**Comment by thomas-shares** [comment]
Hi @brentvatne , thank you for your reply. I have managed to get the `expo run:ios` going. On a simulator this works fine (ie. no crash). But when I run it on a real phone it does crash, but in that case I don't get any debug statements (`console.log()`). Any other ideas how to debug this or how to get debug statements from a real phone?
Thank is advance,
Thomas
ps. I do get log statements from the simulator
pps. if the bug is in my App code, how would you explain that it only crashes on certain iPhones? (Not that I am dismissing the possibility that the bug is in my code, I would like to understand though)
