### ISSUE TITLE
Not to refresh video on end, keep last frame visible, how?

### ISSUE THREAD

**Issue by Aspirationtocode** [expo/expo#1345]
Hello! How can i keep last frame visible on the end of the video?

**Comment by sjchmiela** [comment]
Hi, @Aspirationtocode! Unfortunately I don't think it's possible at the moment. The player rewinds automatically when it finishes to play.

You could implement a custom image-based poster above the Video component that would become visible after the video finishes to play.

**Comment by sjchmiela** [comment]
Although indeed the behavior seems inconsistent between platforms — on iOS `playAsync()` plays the video after it finishes to play, while on Android one has to use `playFromPositionAsync(0)`. Thanks for catching this bug!

**Comment by terribleben** [comment]
We landed a fix for this internally which will be released at some point in the coming couple of weeks probably.

**Comment by Aspirationtocode** [comment]
@terribleben thanks a lot:smiley:
