### ISSUE TITLE
How to publish native modules to expo?

### ISSUE THREAD

**Issue by pi0trpietruszewski** [expo/expo#13454]
I fount [this question](https://forums.expo.io/t/how-to-publish-native-modules-to-expo-as-well/42100) but unfortunately, there is no answer for that.
I would like to build native library with expo support.

### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by AdamJNavarro** [comment]
Hey @pi0trpietruszewski, I would recommend taking a look at this [guide](https://github.com/expo/expo/blob/master/guides/Expo%20Universal%20Module%20Infrastructure.md)!

Cheers,
Adam
