### ISSUE TITLE
Can not build for iOS with - exp build:ios from the terminal

### ISSUE THREAD

**Issue by kyhnlbyrk** [expo/expo#1346]
Hi, I am encountering an issue which I can not build for iOS. The error is:

[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] API Response Error: Cannot read property 'methodAsync' of undefined.

I am using expo v-25. I tried to clear the credentials and re-enter them, but it did not work. I still get the error.

**Comment by fxfactorial** [comment]
Hi, you need to upgrade to latest exp. `npm install -g exp`

**Comment by aria6** [comment]
i has upgrade to latest exp. but still can't build for iOS  :/
anyone have solution for this?
