### ISSUE TITLE
Android issues: ReferenceError: Can't find variable: Intl

### ISSUE THREAD

**Issue by kangpeter5** [expo/expo#13468]
### Summary

Whenever I start the app in Android, I run into `ReferenceError: Can't find variable: Intl`. iOS works fine.
I've tried using `intl` as referenced https://github.com/expo/expo/issues/6536#issuecomment-582009446, but realized this was for typescript and I still get the same error.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.10.0 - ~/.nvm/versions/node/v15.10.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.10.0/bin/yarn
      npm: 7.5.3 - ~/.nvm/versions/node/v15.10.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.12.43 => 0.12.43 
      expo: ~40.0.0 => 40.0.1 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.1 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: 0.13.12 => 0.13.12 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Start expo
2. Open android
3. See error
`
ReferenceError: Can't find variable: Intl

Stack trace:
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
  /Users/etep/Documents/GitHub/kettleos/node_modules/expo/build/environment/react-native-logs.fx.js:27:4 in error
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
  /Users/etep/Documents/GitHub/kettleos/node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
  /Users/etep/Documents/GitHub/kettleos/node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  /Users/etep/Documents/GitHub/kettleos/node_modules/regenerator-runtime/runtime.js:293:29 in invoke
  /Users/etep/Documents/GitHub/kettleos/node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  /Users/etep/Documents/GitHub/kettleos/node_modules/regenerator-runtime/runtime.js:154:27 in invoke
  /Users/etep/Documents/GitHub/kettleos/node_modules/regenerator-runtime/runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
  /Users/etep/Documents/GitHub/kettleos/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
  [native code]:null in flushedQueue
  [native code]:null in invokeCallbackAndReturnFlushedQueue
`

**Comment by brentvatne** [comment]
please provide a project that you can run to reproduce, happy to look if you can do that

**Comment by karimcambridge** [comment]
I'm having this issue too weirdly after updating to expo sdk 42.

**Comment by cuongnv-dev** [comment]
same issue here

**Comment by DJFriar** [comment]
I see this issue when Luxon is loaded. I'm currently on Luxon 2.3.1, with Expo 44.

**Comment by karimcambridge** [comment]
> I see this issue when Luxon is loaded. I'm currently on Luxon 2.3.1, with Expo 44.

Downgrade to luxon ~ 1.9.x
