### ISSUE TITLE
Cannot install/run expo-in-app-purchases

### ISSUE THREAD

**Issue by saeho** [expo/expo#13463]
Problem/Steps:
1. Ejected the managed-workflow app to install expo-in-app-purchases.
2. Installed expo-in-app-purchases
3. Did npx pod-install
4. Attempted to build/run app in simulator.
5. Build command failed with message that said ... "CompileC ... /EXInAppPurchasesModule.o"

Other Info:
When I uninstalled expo-in-app-purchases, the app build + run without errors.
When I re-installed, build failed again.

Using:
Expo SDK 41

**Comment by f-ricci** [comment]
I have recently setup the IAP module. Instead of ejecting, I'm using the bare workflow using the `expo prebuild` command [more info here](https://docs.expo.io/workflow/expo-cli/#expo-prebuild) . Then you can use `expo run:ios` to build the bare app to a target device be it a simulator or a physical device.

Also, there is a new way to build your app using the the `eas-cli` [more info here](https://docs.expo.io/eas/) it takes a few hours to correctly setup everything up to [build it locally](https://docs.expo.io/build-reference/local-builds/) but it's worth the effort.

**Comment by saeho** [comment]
Just tried expo prebuild and it did not work.

Judging by the sheer number of people complaining about the same issue and similar installation issues, I'm going to assume expo-in-app-purchases is dead or permanently broken.

I think I'll use the react-native-iap package in its place unless the documentation is correctly replaced with something that will actually work.

**Comment by cruzach** [comment]
@saeho we can help, but we need a reproducible demo or a full log from your iOS build (like I asked for [here](https://github.com/expo/expo/issues/11085#issuecomment-872555156)). Since following your steps works for me (and for others), it is likely a local issue with your Xcode or project setup, or your package versions & Xcode version

**Comment by saeho** [comment]
@cruzach I will attempt to do an "EAS" build today and send you the log as you suggested, asap.

**Comment by cruzach** [comment]
You don't need to build on EAS to get the logs, you can get them straight from Xcode if that's how you're building now

**Comment by saeho** [comment]
I'm currently building by doing "npm run ios" which does the build before I start the app (?).

Or am I mistaken? Could this be what I'm doing wrong? @cruzach

**Comment by cruzach** [comment]
Use `expo run:ios`, you'll get better logs. Before reporting bugs, make sure you're using the most up-to-date & compatible versions of your packages

**Comment by saeho** [comment]
› Opening the iOS simulator, this might take a moment.
› Planning build
› Compiling expo-font Pods/EXFont » EXFontScaler.m
› Compiling expo-linear-gradient Pods/EXLinearGradient » EXLinearGradientLayer.m
› Compiling expo-in-app-purchases Pods/EXInAppPurchases » EXInAppPurchasesModule.m

❌  (node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:426:10)

  424 |   switch(errorCode) {
  425 |     case SKErrorUnknown:
> 426 |     case SKErrorUnsupportedPlatform:
      |          ^ use of undeclared identifier 'SKErrorUnsupportedPlatform'
  427 |       return 0; // UNKNOWN
  428 |     case SKErrorClientInvalid:
  429 |     case SKErrorPaymentInvalid:


❌  (node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:432:10)

  430 |     case SKErrorPaymentNotAllowed:
  431 |     case SKErrorPaymentCancelled:
> 432 |     case SKErrorOverlayCancelled:
      |          ^ use of undeclared identifier 'SKErrorOverlayCancelled'; did you mean 'SKErrorPaymentCancelled'?
  433 |       return 1; // PAYMENT_INVALID
  434 |     case SKErrorOverlayTimeout:
  435 |       return 4; // SERVICE_TIMEOUT


❌  (node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:434:10)

  432 |     case SKErrorOverlayCancelled:
  433 |       return 1; // PAYMENT_INVALID
> 434 |     case SKErrorOverlayTimeout:
      |          ^ use of undeclared identifier 'SKErrorOverlayTimeout'
  435 |       return 4; // SERVICE_TIMEOUT
  436 |     case SKErrorStoreProductNotAvailable:
  437 |       return 6; // ITEM_UNAVAILABLE


❌  (node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:449:10)

  447 |     case SKErrorInvalidOfferPrice:
  448 |     case SKErrorInvalidOfferIdentifier:
> 449 |     case SKErrorOverlayInvalidConfiguration:
      |          ^ use of undeclared identifier 'SKErrorOverlayInvalidConfiguration'
  450 |     case SKErrorIneligibleForOffer:
  451 |       return 13; // INVALID_IDENTIFIER
  452 |     case SKErrorMissingOfferParams:


❌  (node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:450:10)

  448 |     case SKErrorInvalidOfferIdentifier:
  449 |     case SKErrorOverlayInvalidConfiguration:
> 450 |     case SKErrorIneligibleForOffer:
      |          ^ use of undeclared identifier 'SKErrorIneligibleForOffer'
  451 |       return 13; // INVALID_IDENTIFIER
  452 |     case SKErrorMissingOfferParams:
  453 |       return 14; // MISSING_PARAMS


❌  (node_modules/expo-in-app-purchases/ios/EXInAppPurchases/EXInAppPurchasesModule.m:432:10)

  430 |     case SKErrorPaymentNotAllowed:
  431 |     case SKErrorPaymentCancelled:
> 432 |     case SKErrorOverlayCancelled:
      |          ^ duplicate case value 'SKErrorPaymentCancelled'
  433 |       return 1; // PAYMENT_INVALID
  434 |     case SKErrorOverlayTimeout:
  435 |       return 4; // SERVICE_TIMEOUT

› Compiling expo-application Pods/EXApplication » EXApplication.m
› Compiling expo-blur Pods/EXBlur » EXBlurViewManager.m
› Compiling unimodules-permissions-interface Pods/UMPermissionsInterface » UMPermissionsMethodsDelegate.m
› Compiling expo-web-browser Pods/EXWebBrowser » EXWebBrowser.m
› Compiling react-native Pods/React-jsinspector » InspectorInterfaces.cpp
› Compiling react-native Pods/Yoga » experiments.cpp
› Compiling react-native Pods/Yoga » event.cpp
› Compiling react-native Pods/Yoga » YGValue.cpp
› Compiling react-native Pods/Yoga » Yoga.cpp
› Compiling react-native Pods/Yoga » YGStyle.cpp
› Compiling react-native Pods/Yoga » YGNodePrint.cpp
› Compiling react-native Pods/Yoga » YGNode.cpp
    Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the AppName editor. (in target 'AppName' from project 'AppName')

› 6 error(s), and 1 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.

--

@cruzach Thank you.

**Comment by cruzach** [comment]
What version of Xcode and `expo-in-app-purchases` are you using

**Comment by saeho** [comment]
"expo": "^41.0.0",
"expo-in-app-purchases": "^10.1.1",

XCode is 11.3.1

I can't update to XCode 12 because my OS is not version 11.

I'm updating OS to version 11 now. Then I'll try this again with XCode 12. I hope that's the reason for these errors.

**Comment by cruzach** [comment]
> I can't update to XCode 12 because my OS is not version 11.

That is the reason for the errors. You could always downgrade your expo IAP version, as well

**Comment by saeho** [comment]
Upgrading to XCode 12 worked (I think). Thank you. But I have a different error.

The app crashes with "No suitable image URL loader found for (null)".

Is this because one of the images are null or is there a setting that need to change when changing from managed workflow to bare workflow?

--

Also a side note: "expo run:ios" failed to build. But "npm run ios" worked.
