### ISSUE TITLE
Asset bundling on detached projects (ExpoKit)

### ISSUE THREAD

**Issue by sachabest** [expo/expo#1347]
Via https://docs.expo.io/versions/latest/guides/offline-support.html - what is the general scope of required work to support this? I'm happy to attempt to contribute/help out with the feature but it would be great to document requirements etc.

**Comment by terribleben** [comment]
Thanks for reaching out! We have somebody working on this internally right now. I can't provide an exact ETA, but we want to ship it as soon as it's ready/stable.

**Comment by sachabest** [comment]
Hey Ben - any update on this? Offer still stands to help 😄

**Comment by terribleben** [comment]
We  expect to ship this with SDK 27 shortly 🎉

**Comment by sachabest** [comment]
Woohoo! Thanks Ben. 🎉

**Comment by paneer-tikka** [comment]
@terribleben has this been shipped yet?
