### ISSUE TITLE
Disabling Screen Capture on Android when app is backgrounded does not always work

### ISSUE THREAD

**Issue by ThingCoDanW** [expo/expo#13474]
### Summary

I want to be able to mask potentially sensitive data so that it does not display in the app switcher when the app is backgrounded. On iOS, this is possible by capturing the background event via appstate and displaying an overlay, however this is not possible on Android due to timing (I believe it captures a snapshot for the switcher _before_ the event triggers, rendering it useless).

A workaround for the above is to use Screen Capture to disable snapshots when the app is backgrounded. Expected behaviour is for the app to display a blank screen instead of the snapshot when viewed in app switcher. Actual behaviour varies - sometimes it will work as expected, but often it will not work at all and the snapshot will still be rendered leaving sensitive data visible in the app switcher.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

4.3.0

### Environment

Expo CLI 4.3.0 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 2.4.2 - C:\Users\Dan\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Create new project, add AppState and ScreenCapture
2. Add the following code to the main block of App.jsx/tsx
```
React.useEffect(() => {
		AppState.addEventListener("change", handleBackground);
		return () => {
			AppState.removeEventListener("change", handleBackground);
		};
}, []);

const handleBackground = async(nextState) => {
		if (nextState === "active") {
                     // Re-enable screen capture when app is active
                     await ScreenCapture.allowScreenCaptureAsync();
		} else {
                     // Disable screen capture to prevent OS capturing snapshot
		     await ScreenCapture.preventScreenCaptureAsync();
		}
	};
```
3. Run app on Android device
4. Put app in background, either via home button or app switcher
5. Open app again and repeat step 4 a few times. It seems to fail roughly 1/5 times for me.

**Comment by moxorama** [comment]
You should listen to blur event on Android. 
But it also doesn't work in expo

**Comment by roshan-bisht-lab49** [comment]
Any update on this issue, I am getting the exact same issue for Android for iOS I am just using a BlurView and works as expected but for Android using expo-screen-capture have this inconsistent behaviour
.
