### ISSUE TITLE
Can't add to Video (expo-av) on web an attribute: playsInline (very important on Safari) 

### ISSUE THREAD

**Issue by Aparus** [expo/expo#13480]
### Summary

Video (expo-av) plays on Safari (web) full screen by default. And there is no way to add an important attribute `playsInline`. Please add it's support. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.4.8 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.2.0/bin/npm
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: ^16.13.1 => 16.13.1 
      react-dom: ^16.13.1 => 16.13.1 
      react-native: ^0.63.2 => 0.63.2 
      react-native-web: ^0.13.18 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I hope my issue is simple and clear, even without an example.

**Comment by Hirbod** [comment]
Holy. This one here is huge... And it's not only the `playsinline` thats missing.

1) Not able to set playsinline 
2) The style attribute get lost (can't set width/height). 
It does contain a style but it only contains object-fit  value based on resizeMode.

Without style being applied, I can't get a fullwidth+fullheight background video running on web.

**Comment by Aparus** [comment]
@Hirbod:
> Without style being applied, I can't get a fullwidth+fullheight background video running on web.

I suppose I did full width video, using hook: useDimentions? Sorry, I could forget details... But yes,you should hardcode proportions of video, as 4:3, 16:9 etc :-)

**Comment by Hirbod** [comment]
I ended up creating a `BackgroundVideo.tsx` and `BackgroundVideo.native.tsx` and creating a HTML Native Video Component and Falling back to expo-av on native.

I could not change the video Dimensions in any way, only effecting changes with resizeMode.

**Comment by Hirbod** [comment]
@Aparus while this ticket was left unread by the devs, it landed into SDK 43
https://github.com/expo/expo/pull/13628

So this should be considered as fixed.

**Comment by Aparus** [comment]
> @Aparus while this ticket was left unread by the devs, it landed into SDK 43 #13628
> 
> So this should be considered as fixed.

Thank you! i didn't see this issue, that you referenced to. So cool. :-)
