### ISSUE TITLE
Camera view from expo-image-picker is cropped on iOS 15 beta

### ISSUE THREAD

**Issue by JB1905** [expo/expo#13482]
### Summary

Camera view from expo-image-picker is cropped on iOS 15 beta

https://user-images.githubusercontent.com/28870390/124352978-f813ec80-dc03-11eb-8b8e-482ea4adb7e2.MP4

<img src="https://user-images.githubusercontent.com/28870390/124353025-2e516c00-dc04-11eb-948f-11d6fb34f9ae.jpg" width="300" />

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41/42

### Environment

iPhone 12 mini
iOS 15 beta 2

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@jbiesiada/image-picker-rns

**Comment by dmarkow** [comment]
This is happening to me on iOS 14.6 too, in a bare app. Seems to be from https://github.com/expo/expo/commit/f36294ad1a6c6e066514dd76c4e003e7b600f037. Patching the current release to switch back to `UIModalPresentationOverCurrentContext` fixes this in my app.

**Comment by PsLoS** [comment]
Same issue. Any updates?

**Comment by JB1905** [comment]
@PsLoS please check [the example](https://snack.expo.dev/@jbiesiada/image-picker-rns). The main problem with camera size is solved but there is another problem with modal screens from react-native-screens (@react-navigation/native-stack)
