### ISSUE TITLE
FileSystem.downloadAsync headers issue

### ISSUE THREAD

**Issue by negamaxi-agm** [expo/expo#13487]
### Summary

I develop mobile app that should download images from the server. Server expects me to send `Cookie` header, otherwise I get 401.

Using `FileSystem.downloadAsync` I face two issues:

**Issue 1:** typescript won't let me pass instance of `Headers`, instead it expects me to use only `Record<string,string>`:

![Снимок экрана от 2021-07-04 20-07-17](https://user-images.githubusercontent.com/86593586/124393522-95a21580-dd03-11eb-8caf-aabcd0f48b9c.png)

Which is why I have to use plain objects like this:

![Снимок экрана от 2021-07-04 20-10-28](https://user-images.githubusercontent.com/86593586/124393611-e87bcd00-dd03-11eb-9c24-7d05451433cb.png)

This is not heartbreaking issue, but anyway.

**Issue 2:** server continues to reject my get request with 401 when I use `downloadAsync` with `Cookie` header, but making request with `fetch` works fine:

![Снимок экрана от 2021-07-04 20-15-14](https://user-images.githubusercontent.com/86593586/124393751-94bdb380-dd04-11eb-83e4-dfc00842e803.png)

Probably there is some bug or inconsistency relating to passing headers with `FileSystem.downloadAsync`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41.0.0

### Environment

  Expo CLI 4.7.2 environment info:
    System:
      OS: Linux 5.12 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
      Shell: 5.1.0 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```ts
const url = "https://some.site/with/protected/image.jpg";

const fileUrl = `${FileSystem.documentDirectory}image.jpg`;

const headers = {
  Cookie: "some_secret",
};

FileSystem.downloadAsync(url, fileUrl, { headers }).then(({ status }) => {
  console.log(status) // 401, should be 200
});
```

**Comment by konstantinlois** [comment]
Facing the same problem. A quick fix or workaround would be much appreciated.

**Comment by izuutech** [comment]
Please how did you fix this

**Comment by konstantinlois** [comment]
> Please how did you fix this

In fact, it was an error on my end. The method is working fine for me now 👍
