### ISSUE TITLE
[Expo SDK 42 managed] Fail build

### ISSUE THREAD

**Issue by diazdell91** [expo/expo#13484]
### Summary

Build failed: Compatible version of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add "cache.key" field (it can be set to any value) in eas.json to invalidate the cache.
  - Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.1.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

You have either:
37
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
38
 * changed the constraints of dependency `Stripe` inside your development pod `stripe-react-native`.
39
   You should run `pod update Stripe` to apply changes you've made.
40
[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `1BB92D125BBB408D92BBE329` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
41
Error: Compatible version of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add "cache.key" field (it can be set to any value) in eas.json to invalidate the cache.
  - Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.

**Comment by cruzach** [comment]
Hi! You haven't shared a reproducible demo, so there's not much to go off of to help. You may want to rerun `expo upgrade` and try again to ensure your dependencies are all correct

**Comment by diazdell91** [comment]
> Hi! You haven't shared a reproducible demo, so there's not much to go off of to help. You may want to rerun `expo upgrade` and try again to ensure your dependencies are all correct

Finally, I can find the problem, 
The build fail appeared after updating from SDK 41 to SDK 42, apparently, some compatibility versions of the pods could not be solved, I tried to run expo upgrade but this did not work, I also tried package per packet to try to identify which one is throwing the error, but I didn't find any problem.

The solution was to delete the project from https://expo.io/ - Projects and run eas build again

Thanks! @cruzach

**Comment by wkozyra95** [comment]
@diazdell91 Did you follow the instruction that was directly in the error message?

``
Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add "cache.key" field (it can be set to any value) in eas.json to invalidate the cache.
```
