### ISSUE TITLE
Unfortunately, expo go has stopped - android

### ISSUE THREAD

**Issue by Kulothungan16** [expo/expo#13489]
### Summary

Getting "Unfortunately, expo go has stopped" when trying to open a project in default Expo Go app (PlayStore).

I had checked the issue on two android devices.
Tried reinstalling the app, rebooting the pc and mobile

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "expo": "~42.0.0",
    "expo-status-bar": "~1.0.4",
    "firebase": "8.2.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },
  "private": true
}
```

### Environment

```
  Expo CLI 4.7.2 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 16.4.1 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 7.18.1 - /usr/bin/npm
    npmPackages:
      expo: ~42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. Just create a simple app using `expo init SimpleApp` (managed workflow)
2. Then scan the qr code on your device

### Stacktrace (if a crash is involved)

![WhatsApp Image 2021-07-05 at 11 46 09 AM](https://user-images.githubusercontent.com/63696279/124427158-a34dae80-dd88-11eb-83dd-d80f30972622.jpeg)

Sorry I can't find a gud template that suites my issue.

**Comment by cruzach** [comment]
Hey @Kulothungan16 , can you try reinstalling Expo Go by connecting your device and running `expo client:install:android` from your project directory? This new version should have the fix

**Comment by Kulothungan16** [comment]
@cruzach Working nice, Thanks for the support!
