### ISSUE TITLE
Root userInterfaceStyle does not apply on Android in Expo Go

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#13488]
### Summary

```
{
  "expo": {
    "userInterfaceStyle": "automatic",
  }
}
```

this will not change the user interface style behavior to allow for both light and dark themes, instead you need to set it on the Android key

```
{
  "expo": {
    "userInterfaceStyle": "automatic",
    "android": {
      "userInterfaceStyle": "automatic"
    }
  }
}
```

The root key does work as expected on iOS

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.2 - ~/.nvm/versions/node/v14.15.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.15.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
        Android NDK: 21.0.6113669
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

https://github.com/brentvatne/schemes

Run the project on Android and toggle between light/dark themes, notice the text doesn't update. Now add `"userInterfaceStyle": "automatic"` under the `"android"` key and reload the app (not just fast refresh, full reload) and notice it works as expected.

**Comment by dacevedo12** [comment]
Happens with SDK41 too

**Comment by vahdet** [comment]
Same issue with Expo 42 on Samsung  Galaxy A51.

**Comment by brentvatne** [comment]
this fix will land in sdk 43

**Comment by umrashrf** [comment]
Always returns light on iPhone simulator and always returns dark on iOS.

```
"dependencies": {
  "@expo/metro-config": "^0.1.84",
  "@expo/vector-icons": "^12.0.0",
  "@react-navigation/drawer": "^6.1.4",
  "@react-navigation/native": "^6.0.2",
  "@react-navigation/native-stack": "^6.1.0",
  "babel-preset-expo": "8.3.0",
  "expo": "~42.0.1",
  "expo-constants": "~11.0.1",
  "expo-font": "~9.2.1",
  "expo-image-picker": "~10.2.2",
  "expo-location": "~12.1.2",
  "expo-splash-screen": "~0.11.2",
  "expo-status-bar": "~1.0.4",
  "expo-updates": "~0.8.2",
  "react": "16.13.1",
  "react-dom": "16.13.1",
  "react-native": "0.63.4",
  "react-native-codegen": "^0.0.7",
  "react-native-elements": "^3.4.2",
  "react-native-gesture-handler": "~1.10.2",
  "react-native-reanimated": "~2.2.0",
  "react-native-safe-area-context": "3.2.0",
  "react-native-safe-area-view": "^1.1.1",
  "react-native-screens": "~3.4.0",
  "react-native-unimodules": "~0.14.5",
  "react-native-web": "~0.13.12"
}
```

app.json
```
"expo": {
    "name": "Example",
    "slug": "example",
    "version": "1.0.0",
    "assetBundlePatterns": [
      "**/*"
    ],
    "userInterfaceStyle": "automatic",
    "ios": {
      "bundleIdentifier": "dev.expo.Example",
      "userInterfaceStyle": "automatic",
      "infoPlist": {
        "UIUserInterfaceStyle": "Automatic"
      }
    }
  }
```

**Comment by umrashrf** [comment]
@brentvatne https://snack.expo.dev/@umrashrf89/example

**Comment by callmeberzerker** [comment]
I just started with `expo` but I can confirm that the `useColorScheme()` on Android (real device, Pixel 3XL) returns `light` even though in my system preferences it is set as `dark`.

**Comment by brentvatne** [comment]
@umrashrf - snack does not have an app.json

@callmeberzerker - did you follow the instructions from the original post in the thread?

```
{
  "expo": {
    "userInterfaceStyle": "automatic",
    "android": {
      "userInterfaceStyle": "automatic"
    }
  }
}
```

**Comment by callmeberzerker** [comment]
@brentvatne 

Sorry for the confusion -> after I set `"userInterfaceStyle": "automatic"` in the `android` object it definitely works. Thank you.

I just created a new (first 😅) expo project and I think this should be by default there, correct?

**Comment by brentvatne** [comment]
@callmeberzerker - i think it should default to locking to light mode. not every app wants to build support for light and dark themes upfront, it takes a lot of work and the quickest path to shipping your app is to implement one of those and add support for the other later. if we default to both and developers don't notice because they only use one mode in testing, then their app will look fairly broken when released. so choosing to support dark and light is opt-in.

**Comment by danilosilvadev** [comment]
Also, still having this issue in 2022. Please someone has a workaroung to MIUI in managed flow? the userInterfaceStyle doesnt work in MIUI

**Comment by XiscoB** [comment]
> Also, still having this issue in 2022. Please someone has a workaround to MIUI in managed flow? the userInterfaceStyle doesnt work in MIUI

did u see this already? https://github.com/expo/expo/issues/11261#issuecomment-1014913200
I had an issue and with this i've fixed it, im just now closing tabs :D thought i should leave this link in tabs i had opened with the same issue lol

**Comment by micktg** [comment]
Is this really solved? I still have this issue. The color scheme returns always light with expo go in dev mode on android. 
I did everything according to https://docs.expo.dev/develop/user-interface/color-themes/, but its still always light.
I also installed [expo-system-ui](https://docs.expo.dev/versions/latest/sdk/system-ui#installation) but that does not help

**Comment by MVTTSUN** [comment]
> Обновлять: Даже если я запускаю приложение в режиме «prd», оно возвращает «свет» на Android.
> 
> ```
> npx expo start --no-dev --minify --tunnel
> ```
> 
> Исходное сообщение: Это действительно решено? У меня все еще есть эта проблема. Цветовая схема всегда светится при включении экспозиции в режиме разработки на Android. Я сделал все по [ https://docs.expo.dev/develop/user-interface/color-themes/ ](https://docs.expo.dev/develop/user-interface/color-themes/) , но все равно всегда светло. Я также установил [ expo-system-ui ](https://docs.expo.dev/versions/latest/sdk/system-ui#installation) , но это не помогает.
> 
> На iOS он работает правильно и показывает мне «темно».
> 
> ```
> {
>   "expo": {
>      ...
>     "userInterfaceStyle": "automatic",
>     "splash": {
>      ...
>     },
>     "assetBundlePatterns": [
>      ...
>     ],
>     "ios": {
>       "userInterfaceStyle": "automatic",
>      ...
>     },
>     "android": {
>       "userInterfaceStyle": "automatic",
>       ...
>     },
>     "web": {
>      ...
>     },
>     "extra": {
>      ...
>     }
>   }
> }
> ```

the same problem, I did everything, I registered it in three places in the app, it's still a light theme for android

**Comment by GuilhermeSilva00** [comment]
As configurações no app.json parecem não funcionar ainda. useColorScheme sempre retorna light em modo Release, e apk instalada. Funciona normal no Expo go.

App.json:
{
  "expo": {
     ...
    "userInterfaceStyle": "automatic",
    "ios": {
      "userInterfaceStyle": "automatic"
    },
    "android": {
      "userInterfaceStyle": "automatic"
    }
  }
}

**Comment by GuilhermeSilva00** [comment]
As configurações no app.json parecem não funcionar ainda. useColorScheme sempre retorna light em modo Release, e apk instalada. Funciona normal no Expo go.

App.json:
`{
"expo": {
...
"userInterfaceStyle": "automatic",
"ios": {
"userInterfaceStyle": "automatic"
},
"android": {
"userInterfaceStyle": "automatic"
}
}
}`

**Comment by GuilhermeSilva00** [comment]
The settings in app.json don't seem to work yet. useColorScheme always returns light in Release mode, and installed apk. It works normally in Expo go.

App.json:
`{
  "expo": {
    "name": "lava-carr-brasil",
    "slug": "lava-carr-brasil",
    "version": "1.0.0",
    "assetBundlePatterns": [
      "*/"
    ],
    "userInterfaceStyle": "automatic",
    "ios": {
      "userInterfaceStyle": "automatic"
    },
    "android": {
      "userInterfaceStyle": "automatic"
    }
  }
}`

**Comment by GuilhermeSilva00** [comment]
The settings in app.json don't seem to work yet. useColorScheme always returns light in Release mode, and installed apk. It works normally in Expo go.

App.json: 
`{
  "expo": {
    ...
    "userInterfaceStyle": "automatic",
    "ios": {
      "userInterfaceStyle": "automatic"
    },
    "android": {
      "userInterfaceStyle": "automatic"
    }
  }
}`

**Comment by fbele** [comment]
> Update: Even if I start the app in "prd" mode it returns "light" on android.
> 
> ```
> npx expo start --no-dev --minify --tunnel
> ```
> 
> Original post: Is this really solved? I still have this issue. The color scheme returns always light with expo go in dev mode on android. I did everything according to https://docs.expo.dev/develop/user-interface/color-themes/, but its still always light. I also installed [expo-system-ui](https://docs.expo.dev/versions/latest/sdk/system-ui#installation) but that does not help
> 
> On iOS it works correctly an shows me "dark"
> 
> ```
> {
>   "expo": {
>      ...
>     "userInterfaceStyle": "automatic",
>     "splash": {
>      ...
>     },
>     "assetBundlePatterns": [
>      ...
>     ],
>     "ios": {
>       "userInterfaceStyle": "automatic",
>      ...
>     },
>     "android": {
>       "userInterfaceStyle": "automatic",
>       ...
>     },
>     "web": {
>      ...
>     },
>     "extra": {
>      ...
>     }
>   }
> }
> ```

@mickdewald Does it work for you in iOS simulator, or on your phone via Expo Go? If it's on simulator, how did you get it to work? For me it's exactly the other way around, it works on Android, but iOS always throws 'light'.

**Comment by mickdewald** [comment]
I worked with a real iOS device (iPad).
I have not tested this with an iOS simulator.

**Comment by mrdanielm** [comment]
Yeah I'm also getting this issue, always returning light on the iOS simulator. It did work once though but since it stopped, its never worked again. Tried fully rebuilding still hasn't solved it

**Comment by elliotdickison** [comment]
Just ran into this with SDK 49. I installed `expo-system-ui` and react-native's `useColorScheme` started reporting light mode on Android regardless of the system mode. Disabling remote debugging and adding all the flags to `app.json` did nothing. I uninstalled `expo-system-ui` and `useColorScheme` started working correctly again.

**Comment by Siby1lA** [comment]
> Just ran into this with SDK 49. I installed `expo-system-ui` and react-native's `useColorScheme` started reporting light mode on Android regardless of the system mode. Disabling remote debugging and adding all the flags to `app.json` did nothing. I uninstalled `expo-system-ui` and `useColorScheme` started working correctly again.

You saved me. Thank you
