### ISSUE TITLE
Firebase Analytics don't detect Android and IOS

### ISSUE THREAD

**Issue by JulianValenciaGL** [expo/expo#13507]
### Summary

**I implemented**
`expo-firebase-analytics`

to check events comes from IOS or Android

**actual behavior:**

All events come from web

**Expected behavior:**
When comes events detect which one device comes from

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

39

### Environment

* Operating System version: macOs Big Sur
* Expo version: 39
* Firebase SDK version: ^8.7.0
* Firebase Product: Analytics

### Reproducible demo or steps to reproduce from a blank project

I followed the guide from https://docs.expo.io/versions/latest/sdk/firebase-analytics/

Where I created a project in firebase console: https://console.firebase.google.com/

then, I installed:

* expo-firebase-analytics - ~2.5.0
* firebase - ^8.7.0
* expo-firebase-core - ^3.1.0

then, I updated my app.json with:
```
{
"expo":{
   "ios": {
      "icon": "...",
      "buildNumber": "1",
      "supportsTablet": true,
      "bundleIdentifier": "...",
      "googleServicesFile": "./GoogleService-Info.plist"
},
    "android": {
      "icon": "...",
      "adaptiveIcon": {
        "foregroundImage": "...",
        "backgroundColor": "..."
      },
      "package": "...",
      "versionCode": ..,
      "permissions": []
    },
},
"web": {
      "config": {
        "firebase": {
          "apiKey": "...",
          "authDomain": "...",
          "projected": "...",
          "storageBucket": "...",
          "messagingSenderId": "...",
          "appId": "...",
          "measurementId": "..."
        }
      }
    }
}
```
then I did a test:

```
import * as Analytics from 'expo-firebase-analytics'

Analytics.logEvent('event-test', { test: 10 });
```

then I checked in https://console.firebase.google.com/ to see the devices, just detected the events that comes from the web, even when the test I did, was in IOS:

![error](https://user-images.githubusercontent.com/85369003/124629310-eff7bf00-de46-11eb-9212-f1c6b59b8a33.png)

I tried to follow these guides:

* https://blog.expo.io/using-firebase-analytics-with-expo-222ca84e4d33
* https://github.com/firebase/firebase-js-sdk/issues/2244

but doesn't work

**Comment by LahmerIlyas** [comment]
Facing same issue. Any help

**Comment by IjzerenHein** [comment]
> It sends events to web when running your project in Expo Go- but once you build a standalone app with `expo build` or `eas build`, it should go to the native platforms. Have you tested that?

When running your app in Expo Go, it always logs as a `web` client. This is because Expo Go does not contain the native Firebase SDKs. When you create your own build (as @cruzach mentioned), it will use the native Firebase SDK and you will see events coming from iOS and Android.
