### ISSUE TITLE
expo installation fails everytime

### ISSUE THREAD

**Issue by pouyajabbarisani** [expo/expo#1350]
Here is my error:

⸨            ░░░░░░⸩ ⠏ extract:@expo/traveling-fastlane-linux: sill extract cookie@0.3.1

npm ERR! code EINTEGRITY

npm ERR! sha512-zLAl2gzBs4ddqnmYYVTzQpxnTlF8iK/CMWNpngZfgrhrmzDVzTNNy4+hu0PjKuXIubfyWHy+wtp+wgewOUj9KA== integrity checksum failed when using sha512: wanted sha512-zLAl2gzBs4ddqnmYYVTzQpxnTlF8iK/CMWNpngZfgrhrmzDVzTNNy4+hu0PjKuXIubfyWHy+wtp+wgewOUj9KA== but got sha512-Qj4TP4KrMLUqL4jnnIo8LYyj01wEf2NfICkZh1Dctwct/QNLLYmD8y2kWdKgXxquuWU8+mj+L+aU01RO9dUSNg==. (26689536 bytes)

What is the problem?

**Comment by brentvatne** [comment]
this is a bug with npm: https://github.com/npm/npm/issues/16861

**Comment by brentvatne** [comment]
you can try using yarn! https://yarnpkg.com/
