### ISSUE TITLE
[ SDK 42 ] expo-constants broken in jest test environment after upgrade from 41

### ISSUE THREAD

**Issue by conor909** [expo/expo#13509]
### Summary

Using expo SDK 41 with an  `app.config.js` file and the `extra` property, and running Jest tests, my tests pass.

Upgrading to SDK 42 and running tests, I get failures relating to the `Constants.manifest.extra` being undefined.  Although the `extra` property is available in the app code at run time, it's undefined in the jest environment.

I wasn't able to narrow down the exact cause, but I can see there is breaking changes in `expo-constants` and `jest-expo`.

Switching to an `app.json` instead of `app.config.js`  the `extra` property of manifest becomes available, but only hard coded strings.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

jest-expo test environment 

### SDK Version (managed workflow only)

42

### Environment

```
Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/conor/.rvm/rubies/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

`expo init --template blank@42`
`expo install expo-constants`
`yarn add -D jest-expo`

add the following to `package.json`
```
...
  "jest": {
    "preset": "jest-expo"
  },
...
```

add the following to `App.test.js` file:
```js
import Constants from 'expo-constants'

test('Test constants', async () => {
  expect(Constants.manifest.extra.hello).toBeTruthy()
})
```

Add the following to `app.json`
```
...
    "extra": {
      "hello": "World"
    }
...
```

run `yarn jest App.test.js`

**At this point the tests will pass, as we have access to the `extra` prop, in manifest**

Change the `app.json` file to be `app.config.js`

Then in `app.config.js`, export the json as a default export
```js
export default { ... }
```

run `yarn jest App.test.js`

**At this point the tests will fail**

**Comment by brentvatne** [comment]
we don't support app.config.js in jest yet: https://github.com/expo/expo/pull/7557

**Comment by conor909** [comment]
@brentvatne is that in the documentation of the `jest-expo` package?  It's strange because my tests were working before the SDK upgrade
