### ISSUE TITLE
docs [expo-notifications] - intervals

### ISSUE THREAD

**Issue by ccheney** [expo/expo#13511]
### Summary

The documentation isn't very clear around how to schedule a notification with a custom interval such as:

every 2 days
every 3 days

Let's say it's 4pm and I want to schedule a notification starting tomorrow at 6pm and repeat every two days. Is this even possible using `TimeIntervalNotificationTrigger`? I can schedule the notification with the proper offset so the first notification comes out correct but the offset is added to each repeat (I'd need the offset for the first notification only)

### Link to the related docs page

https://docs.expo.io/versions/latest/sdk/notifications/#timeintervalnotificationtrigger

**Comment by brentvatne** [comment]
in some cases you may need to handle scheduling notifications at specific dates and times on your own. you can, for example, schedule notifications to cover your every 2 day / every 3 day interval for the next month each time you open the app.
