### ISSUE TITLE
undefined is not an object (evaluating '_ExponentSpeech.default.maxSpeechInputLength')

### ISSUE THREAD

**Issue by RazaShehryar** [expo/expo#13515]
### Summary

I've installed react-native-unimodules and setup everything correctly. The app is running fine with expo-speech but when I try to import expo-speech, it gives me error. 

I am importing it like this
import * as Speech from 'expo-speech';

`"expo-speech": "^9.2.0";`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.8 => 0.59.8 
      react-navigation: ^1.0.0-beta.11 => 1.6.1 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

issue in 

`Speech.speak("HELLO WORLD!");`

**Comment by brentvatne** [comment]
notice the import format in the docs: https://docs.expo.io/versions/latest/sdk/speech/

import * as Speech from 'expo-speech';

**Comment by RazaShehryar** [comment]
@brentvatne that's what I wrote above 😅. I am importing it like that way but it's still giving me error

**Comment by brentvatne** [comment]
share a reproducible example project. notice if you go to the documentation there is a working example you can click through.
