### ISSUE TITLE
[expo-notifications][android] Empty notifications received by the users (which are meant to be silent) via FCM

### ISSUE THREAD

**Issue by mustvlad** [expo/expo#13518]
### Summary

Im using AppsFlyer in my app with the option to track the app uninstalls. AppsFlyer does this by sending a silent notification to the device in order to see if it's still active. 

However on Android the notifications which are meant to be silent appear as normal notifications – but with no text. Only an empty notification. 

In AppsFlyer docs, they suggest adding this:

```
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        
        if(remoteMessage.getData().containsKey("af-uinstall-tracking")){
            return;
        } else {
           // handleNotification(remoteMessage);
        }
    }
```

but I cannot see a way to do this cause `expo-notifications` is adding its own notification handler.

Any idea how can I solve this? 
Why is `expo-notifications` not handling the silent notifications properly?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.0

### Environment

Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.17.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Setting the simple app
First you'll need to create a bare expo project. We are gonna test this for **Android**.

Using the `expo-notifications` library we can get the **device_token** by calling `const token = await Notifications.getDevicePushTokenAsync();`. Use a simple `console.log("here's your token:", token.data)` to print the token on the console.

Build and deploy the app to a real Android device (via Android Studio or using `yarn android`). Run it and get **your_device_token** from the console.
 
### Sending the silent notification 

Now, let’s go ahead and create a **POST** request that target the following URL:

`https://fcm.googleapis.com/fcm/send`

Next up, you also need to configure the POST request headers.

```
Content-Type: application/json
Authorization: key=[your_server_key]
```

For the Authorization header, replace `[your_server_key]` with the actual server key that you can obtain from Firebase (Cloud Messaging). Please note that the `key=` prefix must be included as part of the Authorization header.

The notification payload is a JSON formatted string that will be delivered alongside the silent push notification. Here’s a sample of the silent push notification payload.

```
{
  "to": "[your_device_token]",
  "content_available": true,
  "apns-priority": 5,
  "data": {
    "some-key": "some-value"
  }
}
```

At this moment, you will receive an empty notification on your device. This notification should not be visible at all.

**Comment by cruzach** [comment]
AppsFlyer is recommending you edit the native code for notification handling. Since you're using `expo-notifications`, you'll either need to fork it or apply a patch to the package post install.

You can opt to not show a notification with `setNotificationHandler`: https://docs.expo.io/versions/latest/sdk/notifications/#handling-incoming-notifications-when-the-app-is

**Comment by mustvlad** [comment]
Hey @cruzach thanks for the answer!

I'm sorry for the confusion – cause I presented the issue like it's AppsFlyer related – but if you follow the steps in the **Reproducible demo** you can see that this is a general issue with `expo-notifications`. 

It doesn't matter if the silent notification is sent by AppsFlyer or if you send it using the **FCM API** directly. It will still show up for the user as an **empty notification** which is very annoying. 

Also, the `setNotificationHandler` is not helpful as it's working only if the app is running. What if the app is closed? :)

Cheers'

**Comment by onlystard** [comment]
Same issue

**Comment by areksiekiera** [comment]
I can observe the same on 
```
  Expo CLI 4.12.1 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.6.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.82 
      expo: ^42.0.0 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed
```
Standalone app on Android 9

I'm trying to use Notifications.registerTaskAsync() to handle incoming data notifications and only show some of thems.
My background task kicks but android shows empty notification before hand.

I use FCM to send silent notification, but the same I've noticed when using expo notification server (when sending notification with data only).

Here is my POST to FCM 
```
{
    "to": "fVsWejCcT7ePWwhszbRJRI:XXX,
    "priority": "high",
    "data": {
   	"experienceId": "@behobeltd/baobab",
        "some": "data"
      }
}
```

**Comment by mustvlad** [comment]
Was this solved? I don't think it should be closed yet as our customers are complaining about it.

**Comment by Jul1enF** [comment]
I'm having the exact same problem. By any chance, is there someone who found a solution since ?
