### ISSUE TITLE
Manifest missing originalFullName in EAS Build Development Client

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#13513]
### Summary

Manifest is missing `originalFullName` and `currentFullName` (and `id`) when using custom EAS Build Development client.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

Only native and expo packages listed:

```json
{
  "dependencies": {
    "expo": "^42.0.0",
    "expo-application": "~3.2.0",
    "expo-asset": "~8.3.2",
    "expo-auth-session": "~3.3.1",
    "expo-camera": "~11.2.1",
    "expo-constants": "~11.0.1",
    "expo-dev-client": "^0.4.3",
    "expo-device": "~3.3.0",
    "expo-image-picker": "~10.2.2",
    "expo-linear-gradient": "~9.2.0",
    "expo-linking": "~2.3.1",
    "expo-localization": "~10.2.0",
    "expo-notifications": "~0.12.2",
    "expo-random": "~11.2.0",
    "expo-secure-store": "~10.2.0",
    "expo-splash-screen": "~0.11.2",
    "expo-standard-web-crypto": "^1.0.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.8.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-svg": "12.1.1",
    "sentry-expo": "^4.0.0",
  }
}
```    

### Environment

```
Expo CLI 4.7.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.2 - ~\AppData\Local\Temp\yarn--1625626459530-0.2547605146813341\node.CMD
      Yarn: 1.22.10 - ~\AppData\Local\Temp\yarn--1625626459530-0.2547605146813341\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. Create new expo 42 project
2. Create a development client:

```json
{
  "builds": {
    "android": {
      "debug": {
        "workflow": "managed",
        "buildType": "development-client",
        "releaseChannel": "test.42.0",
        "distribution": "internal"
      }
    }
  }
}
```

3. Try to create a redirect URI:

```typescript
const useProxy = Platform.select({ web: false, default: true });
const redirectUri = AuthSession.makeRedirectUri({ useProxy });
```

4. Start `expo start --dev-client`
5. Install the dev client and connect
6. It breaks

I went into `node_modules\expo-auth-session\build\SessionUrlProvider.js` and added console.log({ manifest }). I can see in the log that both originalFullName and currentFullName are missing. 

```shell
expo config --type public
```

This correctly shows `originalFullName` and `currentFullName`.

## Workaround

```typescript
import Constants from 'expo-constants';
Constants.manifest.originalFullName = '@org/project';
```

Right before `AuthSession.makeRedirectUri`

### Stacktrace (if a crash is involved)

SessionUrlProvider.js

> Error: Cannot use AuthSession proxy because the project ID is not defined. Please ensure you have 
the latest version of expo-constants installed and rebuild your native app. You can verify that currentFullName is defined by running `expo config --type public` and inspecting the output.

**Comment by tcdavis** [comment]
Thanks for raising!  While we work to make this smoother I'd recommend using the native option rather than setting originalFullName yourself.

https://docs.expo.io/versions/latest/sdk/auth-session/#authsessionmakeredirecturi
https://docs.expo.io/versions/latest/sdk/auth-session/#authsessionredirecturioptions

**Comment by SleeplessByte** [comment]
Will do. Thanks :)

**Comment by SleeplessByte** [comment]
It's not resolved.

**Comment by byanes** [comment]
I'm having the same issue. Any ideas?

**Comment by SleeplessByte** [comment]
This workaround worked for me @byanes https://github.com/expo/expo/issues/13513#issuecomment-877848357

**Comment by Mistes974** [comment]
Hi @SleeplessByte , I'm facing the same problem, it works everywhere except in the development client and I don't understand the options i should pass...could you share the code for this workaround ? 
Mine look like this : 

 ```
const returnUrl = makeRedirectUri({
      path: "/",
      useProxy: false,
    });    
    
const response = await startAsync({
    authUrl: `${SUPABASE_URL}/auth/v1/authorize?provider=${provider}&redirect_to=${returnUrl}`,
    returnUrl: returnUrl,
});
```

**Comment by BrandonMathis** [comment]
May be worth noting that `releaseChannel` also appears to be missing. The following no longer yields any results `Constants.manifest.releaseChannel`

**Comment by SleeplessByte** [comment]
The `native` option must be set depending to whatever that authentication method requires, @Mistes974 . I do not use `supabase`, so I do not know what's appropiate.

- Auth0: `${SCHEMA}://${AUTH0_SUBDOMAIN}.auth0.com/${PLATFORM}/${AUTH0_PACKAGE_ID}/callback`
- Apple: `${SCHEME}:`
- Facebook: `fb${FACEBOOK_CLIENT_ID}://authorize`
- Google: `${SCHEME}:`
- Spotify: `${SCHEME}://redirect`

You _only_ need this if you _cannot_ (or don't want to) use the proxy.

**Comment by Mistes974** [comment]
Thanks @SleeplessByte , i solved my issue with this  `Constants.manifest.originalFullName = "@mistes974/my_project_slug";
`
```
const socialSignIn = async (provider) => {
     if (__DEV__) {
      Constants.manifest.originalFullName = "@mistes974/my_project_slug";
    }
    const returnUrl = makeRedirectUri({
      path: "/",
      useProxy: false,
    });

    const response = await startAsync({
      authUrl: `${supabaseConfig.url}/auth/v1/authorize?provider=${provider}&redirect_to=${returnUrl}`,
      returnUrl: returnUrl,
    });

   ...
  };
```

**Comment by soullivaneuh** [comment]
I juste created a blank project using `expo init` with the following `console.debug` lines:

```typescript
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import Constants from 'expo-constants';

export default function App() {
  console.debug(
    Constants.manifest?.id,
    Constants.manifest?.originalFullName,
    Constants.manifest?.currentFullName,
  );

  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Output:

```
@soullivaneuh/expo-test undefined undefined
```

According to the official Expo documentation, the
[`currentFullName`](https://docs.expo.dev/versions/latest/config/app/#currentfullname) 
and [`originalFullName`](https://docs.expo.dev/versions/latest/config/app/#originalfullname) are supposed to be auto-generated.

I need this to get a notification token with a specific experienceId (recommended to provide according to the docs, and useful for to group notification sending at my API side), so I fallback to `Constants.manifest.id` as a fallback:

```typescript
  const experienceId = Constants.manifest?.originalFullName || Constants.manifest?.id;
  const token = (await Notifications.getExpoPushTokenAsync({
    experienceId,
  })).data;
```

@tcdavis Is it a recommended way?

**Comment by SleeplessByte** [comment]
It's probably not the recommended way as with eas-updates, `manifest` is no longer set :/

**Comment by isaachinman** [comment]
@brentvatne

Is there any official documentation on this subject?

It seems the absence of `manifest` essentially breaks several/many expo packages when upgrading from 45 to 46-dev-client, and I cannot find any official guidance.

Is the workaround listed above seriously what's still needed, over a year later?

**Comment by soullivaneuh** [comment]
> It's probably not the recommended way as with eas-updates, manifest is no longer set :/

@SleeplessByte I think you are right. I personally solve my issue by using the following:

```
Constants.manifest2?.extra?.scopeKey
```

Important note: The `Constants.manifest2` looks to be provided only when you configure your application for `eas update`.

See also the related comments set on the typing of both manifest properties.

**Comment by danshilm** [comment]
> Is there any official documentation on this subject?
> It seems the absence of manifest essentially breaks several/many expo packages when upgrading from 45 to 46-dev-client, and I cannot find any official guidance.

@isaachinman and @soullivaneuh 
From what I've read, either from the Expo docs (on the EAS debugging/troubleshooting something guide) or from Kim on their Discord ([link](https://canary.discord.com/channels/695411232856997968/920032594232500225/1019265416922681438)), the way to do things from Expo SDK 46 and onwards, is to use `Constants.expoConfig` instead of `Constants.manifest` since that will be null after an update. [Here's](https://github.com/expo/expo/blob/main/packages/%40expo/config-types/src/ExpoConfig.ts) the Typescript interface for whomever needs it.

**Comment by SleeplessByte** [comment]
You can see in eas build that the values are correctly set so even though this issue isn't stale, by switching to eas it will eventually not need fixing.

**Comment by soullivaneuh** [comment]
@danshilm I indeed did found the same thing, using `Constants.expoConfig` starting expo SDK 46.

However, I can not upgrade to that right now because it require react v18 that is not yet supported by my other dependencies

Also, I just figured out that `Constants.manifest2` looks not available when the application come from an `eas build` result directly, but works with Expo Go.

So currently, I don't have any solution about this mess.

**Comment by SleeplessByte** [comment]
Hardcoding the value does work @soullivaneuh

**Comment by soullivaneuh** [comment]
@SleeplessByte Well, if I can avoid hard-coding ugly workaround, I'll prefer. :-)

I do not understand how we can being in such situation.

However, I noticed something:

1. If you publish an app using `eas build`, the `manifest2` property is not present
1. If you do a `eas update` command next after, the updated app will have the property

However, if the `eas update` command is done **before** the `eas build` one, it will lead to the same situation. I assume this is because the built app won't update because it is more recent than the updated version.

**Comment by SleeplessByte** [comment]
> However, if the eas update command is done before the eas build one, it will lead to the same situation. I assume this is because the built app won't update because it is more recent than the updated version.

This is correct.

> Well, if I can avoid hard-coding ugly workaround, I'll prefer. :-)

It seems you're using `eas` anyway. My [ENV variable in-lining](https://github.com/expo/expo/issues/13513#issuecomment-1237238178) works with that without any hardcoding. I'm using that solution in production too :)

**Comment by soullivaneuh** [comment]
> It seems you're using eas anyway.

Yes but I do have this issue using `eas`! By the way, I'm not trying to use the same variables as you, I try to fetch a `extra.apiEndpoint` custom var we defined.

> My https://github.com/expo/expo/issues/13513#issuecomment-1237238178 works with that without any hardcoding. I'm using that solution in production too :)

Indeed, you don't have value hardcoded on your code. However, what a complex custom logic just for a not provided manifest property. :-/ 

I think I'll just be careful of doing a `eas upate` command just after the `eas build` to be sure the app load the configuration correctly until I do the upgrade to SDK 46.

Thanks for the help! :+1:

**Comment by SleeplessByte** [comment]
> Yes but I do have this issue using eas! By the way, I'm not trying to use the same variables as you, I try to fetch a extra.apiEndpoint custom var we defined.

Ah yeah, I moved that all to `config.ts`. 

> Thanks for the help! 👍

No problem!

**Comment by soullivaneuh** [comment]
After an upgrade to `eas update` and Expo v46, I'm back to the `originalFullName` issue, following https://github.com/expo/expo/issues/13513#issuecomment-1146881040.

The variable to use is now `Constants.expoConfig.originalFullName`, stop me if I am wrong.

This variable:

- Is present on `eas build` output
- Is present on `eas update` output usage with Expo Go
- Is not present when used locally with Expo Go

This variable is supposed to be auto-generated in any circumstance, am I right? Without that value, I have no way to provide a unique id to my notifications service, meaning no way to test notifications locally.

The only workaround I found looks like the original one posted by @SleeplessByte:

```ts
// Directly on App.tsx or index.tsx according to your code structure.
import Constants from 'expo-constants';

if (Constants.expoConfig && !Constants.expoConfig.originalFullName) {
  Constants.expoConfig.originalFullName = '@org/project';
}
```

However, I am not supposed to do that. I am missing something or are we facing an Expo bug here?

**Comment by soullivaneuh** [comment]
Hmm I am currently having a crash of my app using the workaround I previously mentioned, with the following error:

```
java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
```

Any clue? :thinking:

**Comment by nightness** [comment]
Expo 45, I'm having this issue, but only when I have `updates: {
      url: 'https://u.expo.dev/...',
    }` no config changes would fix this, until I realized my config is missing when this is specified. After hard coding my legacyExpoProjectFullName in SessionUrlProvider.js, getting past this error. The very next error is alerted me to the face Constants is missing config.

**Comment by brentvatne** [comment]
> @brentvatne
> 
> Is there any official documentation on this subject?
> 
> It seems the absence of `manifest` essentially breaks several/many expo packages when upgrading from 45 to 46-dev-client, and I cannot find any official guidance.
> 
> Is the workaround listed above seriously what's still needed, over a year later?

hi there!

you can use `Constants.expoConfig` to access the app config: https://docs.expo.dev/versions/latest/sdk/constants/

it's documented here in the migration guide to EAS Update: https://docs.expo.dev/eas-update/migrate-to-eas-update/#additional-possible-migration-steps

**Comment by tcdavis** [comment]
The auth session proxy should not be required when working in development builds, and you can instead provide the scheme used in your application to makeRedirectUri. https://docs.expo.dev/versions/latest/sdk/auth-session/#authsessionmakeredirecturioptions

Project name is no longer used in Expo APIs, which have been switched to use the EAS project ID (which can be generated by `eas init)
