### ISSUE TITLE
Android App keeps Closing in App Store Bundle Only

### ISSUE THREAD

**Issue by saeho** [expo/expo#13512]
I ejected my app to bare workflow,

now when I build the app for production, everything is successful and I am able to create a AAB file.

The app runs perfectly fine in emulator without any hitch.

However, once I download and try the app after uploading to Android app store, the app always crashes with "App Keeps Closing" message.

There is no error message. I installed Sentry, but Sentry cannot detect any errors when the error occurs.

I even tried removing most of the code, but nothing seems to undo the crash on startup.

I also tried uninstalling expo-updates from instructions I read in other threads, but that did not have any impact.

Any help would be greatly appreciated.

**Comment by brentvatne** [comment]
https://docs.expo.io/workflow/logging/#optional-manually-access-device-logs
