### ISSUE TITLE
Expo Tracking Transparency is not discovering permissions module

### ISSUE THREAD

**Issue by vladamx** [expo/expo#13521]
### Summary

I want to use expo tracking transparency in existing project so i installed and configured unimodules in existing react native app.
The app correctly builds and i can use Constants from unimodules for example.

After that i installed expo-app-tracking-transparency and when i try to requestPermission i get:

Error: Permissions module not found. Are you sure that Expo modules are properly linked?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

 Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - ~/brew/bin/yarn
      npm: 7.11.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /Users/p3dev/brew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/p3dev/brew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Not included

**Comment by vladamx** [comment]
Resolved after updating react-native-unimodiles to the latest version.

**Comment by vladamx** [comment]
Reopening this since the latest version of react-native-unimodules requires XCode 12.5 which i can not use on CI. When i install react-native-unimodules@0.13.3 the same error re-appears.

**Comment by cruzach** [comment]
[Permissions was removed from react-native-unimodules in v0.13.2](https://github.com/expo/expo/blob/master/packages/react-native-unimodules/CHANGELOG.md). What if you use an earlier version?

**Comment by vladamx** [comment]
Hey @cruzach. Thanks for answering. I've tried with 0.12.0 as well. Still getting : "Permissions module not found. Are you sure that Expo modules are properly linked?"

**Comment by cruzach** [comment]
did you run `npx pod-install` after reinstalling? what version of `expo-tracking-transparency` are you using?

**Comment by vladamx** [comment]
I did pod install. "expo-tracking-transparency": "^1.1.2".

**Comment by cruzach** [comment]
try 1.0.0

**Comment by vladamx** [comment]
@cruzach Works! 

"expo-tracking-transparency": "1.0.0" and
"react-native-unimodules": "12.0.0" are compatible and they are building fine with older Xcode

Closing the issue
