### ISSUE TITLE
Bad `fontFamily` and `color` styles merging on Android with 3 Text nesting levels

### ISSUE THREAD

**Issue by jsamr** [expo/expo#13526]
### Summary

Under complex conditions, nested text styles such as `color` and `fontSize` are not applied correctly. Below are screenshots of the same component rendered in Android (left) and iOS (right). Notice the following inconsistencies in Android:

- Text elements in line 2 to 7 have a wrong `fontSize`;
- Text elements in line 8 are painted white despite given a non-white `color` style.

 The code to reproduce those screens is provided in next section.

<table>
<tr>
<td>

![android](https://user-images.githubusercontent.com/3646758/124793135-13446c00-df24-11eb-8cec-9e648b06bac1.png)

</td>
<td>

![ios](https://user-images.githubusercontent.com/3646758/124793092-0889d700-df24-11eb-8abd-445d6f8ba4b8.png)

</td>
</tr>
</table>

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: Linux 5.12 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 7.16.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.3, 31.0.0, 31.0.0
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ~42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

The bug requires a specific set of conditions to happen (see snack). The following tests have been performed on the aforementioned snack:

- Remove `fontFamily` **monospace** for all styles → could not reproduce bug.
- Remove one Text nesting level (Text  → Text → Text) → could not reproduce bug.
- Remove empty text elements (those with `children=""`) → could not reproduce bug.

[**LINK TO SNACK**](https://snack.expo.io/@jsamr/nested-text-color-bug)

**NB**: I want to stress that the reproduction might look a bit "heavy" in terms of rendered nodes, but try to cut some nodes off and the issue vanishes.

**Comment by brentvatne** [comment]
hi there! text rendering is handled entirely by react-native, please post this issue here: https://github.com/facebook/react-native/isses

**Comment by jsamr** [comment]
@brentvatne Copy that; I resubmitted this issue here https://github.com/facebook/react-native/issues/31826

**Comment by brentvatne** [comment]
thanks! i'm going to close this issue because we try not to mirror issues from other related repositories here because they're not immediately actionable for us.
