### ISSUE TITLE
Expo build `Queued` issue

### ISSUE THREAD

**Issue by korabh** [expo/expo#1353]
I tried to build expo app with 2 accounts and both build are in `Queued` status. 
Build Id:
1: 39951266-8b14-4540-9e92-5c1b5175c910
2: 7f321f89-07a1-4a5b-a168-936939d68fcd

**Comment by sangampandey** [comment]
Same for me, when it can be fixed.

**Comment by brentvatne** [comment]
hi there! we are fixing an issue with the ios build service, it’ll be back up shortly, sorry for the hassle

**Comment by korabh** [comment]
@brentvatne Thanks.

**Comment by brentvatne** [comment]
it's resolved now, the build service is working its way through the queue so you can expect it will get to your build job shortly!

**Comment by gyurobenjamin** [comment]
Is there an issue again? Can't see anything on status pages.

**Comment by korabh** [comment]
@gyurobenjamin Nope.
