### ISSUE TITLE
speak() in expo-speech throws error in react-native 0.64.1

### ISSUE THREAD

**Issue by prattvaidya** [expo/expo#13530]
### Error Description
Calling `Speech.speak("test")` throws the following error:
`TypeError: SpeechEventEmitter.listeners is not a function. (In 'SpeechEventEmitter.listeners(eventName)', 'SpeechEventEmitter.listeners' is undefined)`

### Version Info
This issue is applicable for projects using react-native ^0.64.1.
This issue didn't occur with react-native 0.63.2

### Input/suggestion for fix
This will fix the issue for RN ^0.64.1. However, it won't work for older RN versions.
**File**: expo/packages/expo-speech/src/Speech/Speech.ts  **Line**: 129
```typescript
-   if (SpeechEventEmitter.listeners(eventName).length > 0) {
+   if (SpeechEventEmitter.listenerCount(eventName) > 0) {
```
`listeners()` in `react-native/Libraries/vendor/emitter/EventEmitter.js` has been replaced with `listenerCount()` (refer [this commit](https://github.com/facebook/react-native/commit/b11d6ecbb8bb2f0d6f423be6775e587f4e9b1c4d#diff-53ad587a2f77ca63b6940dbf0026a101e3874de1858e058d217a8f4c04d4987e))

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1 
      react-dom: 16.14.0 => 16.14.0 
      react-native: 0.64.1 => 0.64.1 
      react-native-web: 0.15.1 => 0.15.1 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. Create a bare react-native project with ^0.64.1
2. Configure Expo
3. Install `expo-speech`
4. Import `Speech` from the package and call `Speech.speak("test")`

**Comment by brentvatne** [comment]
it looks like we could fix this by using `SpeechEventEmitter.listenerCount` if it's defined and otherwise using `SpeechEventEmitter.listeners` -- care to open a pr?
