### ISSUE TITLE
expo-splash-screen CLI tool is not working anymore

### ISSUE THREAD

**Issue by exsolisum** [expo/expo#13547]
### Summary

I previously ran yarn run configure-splash-screen -b '#121212' -i app/assets/1/images/splash.png —status-bar-hidden and it worked perfectly since I tried to add the -i option on the same command I get a weird output, could not find anything about it.

$ /Users/path/Code/work/path/app/node_modules/.bin/configure-splash-screen -b '#121212' -i app/assets/1/images/splash.png —status-bar-hidden

Cannot read property 'productType' of undefined

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.8.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ^0.64.1 => 0.64.2 
      react-native-web: ^0.16.0 => 0.16.0 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Install a bare workflow project
run 
yarn run configure-splash-screen -b  '#F4F4F4' -i app/assets/1/images/splash.png --status-bar-hidden
then
yarn run configure-splash-screen -i 'cover' -b  '#F4F4F4' -i app/assets/1/images/splash.png --status-bar-hidden

**Comment by NateVonSmith** [comment]
same, the error i see is ```Cannot convert ExpectedElement to Element when deletionFlag is set``` when running ```yarn expo-splash-screen -r "cover" -b "#FFFFFF" -i "./assets/images/splash.png"``` or ```yarn expo-splash-screen -r "cover" -b "#FFFFFF" -i "../../desktop/splash.png"``` (move location) or ```yarn run configure-splash-screen -r "cover" -b "#FFFFFF" -i "../../desktop/splash.png``` (change command)

**Comment by johnnywang** [comment]
Encountering the same error as @NateVonSmith. Running the command with just `ios` works fine, but `android` and `all` fails, leaving the Android splash screen setup (and the app entirely) in a broken state because `android/app/src/main/res/values/styles.xml` is empty as a result

**Comment by ramisalem** [comment]
Any update on this?

**Comment by roz0n** [comment]
No updates on this?

**Comment by yemd** [comment]
> Still no fix regarding this?

Nope afaik, I rebuilt the problematic project and it is now working fine, but this is **not** a solution

**Comment by charles-goode** [comment]
Seems that this CLI tool is for bare workflow, right? Is there a similarly easy-to-use config plugin for supporting color scheme based splash screens?

**Comment by lqze** [comment]
> 

Thanks for your investigating. Providing all flags prevents the error from occurring.

**Comment by talaikis** [comment]
Tried many variants with `yarn run configure-splash-screen -b '#ffffff' -i ... -r contain --dark-mode-image-path ... --dark-mode-background-color '#000000' --dark-mode-status-bar-background-color '#000000' --status-bar-background-color '#ffffff'`

does not work (Windows, all latest versions)

**Comment by iGroza** [comment]
still same error

**Comment by Abdullah-146** [comment]
reopen
