### ISSUE TITLE
[expo] [android] [sdk 42] Navigation Bar not hidden in production build 

### ISSUE THREAD

**Issue by oanacioara** [expo/expo#13557]
### Summary

Hi! I have my app.json configured to hide the navigation bar on android. https://docs.expo.io/versions/latest/config/app/#androidnavigationbar

This works fine in development mode, using expo, but when I build for production it no longer works. The navigation bar is not hidden.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.0

### Environment

Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- generate a new project
- configure `app.json` to hide the android navigation bar
     - `"androidNavigationBar": { "visible": "sticky-immersive" }`,
- build for production `npx eas-cli build --platform all --profile prod --non-interactive`

**Comment by damianbeles** [comment]
I have the same issue.

**Comment by oanacioara** [comment]
Seems like this is happening only if we build an `.aab`. It is working on an `.apk` build

**Comment by damianbeles** [comment]
@brentvatne maybe you can have a look into it?
I can confirm that only .aab builds have this issue. .apk builds work as expected, the navigation bar is hidden.

**Comment by damianbeles** [comment]
I found out that the issue is not related to the build type, but with how the build is made.

Using `expo build:android` solves the issue. The navigation bar is hidden as expected.

The problem arise when building with eas, namely `npx eas-cli build --platform all --profile prod --non-interactive`.

**Comment by EvanBacon** [comment]
Do you see this warning in your EAS build logs? https://github.com/expo/expo-cli/blob/05e9e9afaad573a85d9137ca22839e12a4289cb6/packages/config-plugins/src/android/NavigationBar.ts#L19

**Comment by damianbeles** [comment]
@EvanBacon yes, we see that warning. So we should expect that this will not be implemented and we should still proceed with `expo build:android` command to build our app?

**Comment by nicubucalaete** [comment]
This is solved in expo SDK 44 as specified here: https://github.com/expo/fyi/blob/master/android-navigation-bar-visible-deprecated.md

**Comment by brentvatne** [comment]
you can use the solution that @nicubucalaete specified in sdk 43 as well. note that expo-navigation-bar will not work in expo go, however

**Comment by EvanBacon** [comment]
The latest CLI will also warn you to use `expo-navigation-bar` when the `visible` property is used. I recommend trying it out since you can now configure the bar dynamically in the app from JS and statically set values like border color with the config plugin.

**Comment by baochungit** [comment]
Is the androidNavigationBar.visible property deprecated in Android 11, API level 30? I actually searched and not found any mention about it. Why don't we still keep it in the EAS production build at now??
