### ISSUE TITLE
SQLite does not block `BEGIN IMMEDIATE TRANSACTION` from multiple JS contexts

### ISSUE THREAD

**Issue by trajano** [expo/expo#13552]
### Summary

SQLite does not block `BEGIN IMMEDIATE TRANSACTION` from multiple JS contexts.  This causes an attempt to start a transaction inside a transaction when using the same (even different) WebSQL.Database instances.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS and Android

### SDK Version (managed workflow only)

40 and 42

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 12.18.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      Yarn: 1.22.10 - ~\scoop\apps\nvm\current\nodejs\nodejs\yarn.CMD
      npm: 6.14.4 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ^0.16.3 => 0.16.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@trajano/sqlite-transaction-block

**Comment by trajano** [comment]
The workaround I have is to use async-mutex on iOS to block the transaction.

**Comment by trajano** [comment]
Here's the snack https://snack.expo.io/@trajano/sqlite-transaction-block open up the log.
Press start transaction a few times

on Android no issue

on iOS it says Error code 1: cannot start a transaction within a transaction"

**Comment by trajano** [comment]
Actually... it's worse in Android.  It actually allows for it silently.

**Comment by barthap** [comment]
I see you're using `db.exec()` to run transactions, which means you have to care about _"thread-safety"_ on your own. All that the method does is just execute the statements given in the array on the native SQLite engine.
Moreover, the SQLite versions on Android and iOS differ, they also depend on Android API versions, so the behavior might also differ 😒 

There is a `db.transaction()` which implements some sort of transaction queueing ([implemented in `node-websql` lib](https://github.com/nolanlawson/node-websql/blob/v1.0.0/lib/websql/WebSQLDatabase.js)), but it executes the `BEGIN;` clause, you cannot set if it's immediate or exclusive.

**Comment by trajano** [comment]
I had to do it because the db.transaction() approach will turn into callback hell.

**Comment by trajano** [comment]
I think this is more of a problem on Expo Go when it reloads it may not close the WebSQL (since it does not expose the close()) method so we can't do a useEffect return to close.
