### ISSUE TITLE
Android pin button doesn't support "Action Launcher" or "Nova Launcher"

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#1356]
> I've noticed that this works fine with the stock Android launcher, but breaks for Action Launcher and Nova Launcher. I'm not sure, but I'm guessing this is still a bug with expo. Pinning things to the home screen from within other apps works with both of these third party launchers without difference. (For example, pinning a file/folder from Google Drive).

> Is it possible to handle this in a way that would work for any launcher system (the way I'm assuming Google Drive does it)?

Moved from this comment https://github.com/expo/expo/issues/491#issuecomment-361324624

**Comment by itslittlejohn** [comment]
Makes sense. I'll take a look if I have a chance!

**Comment by itslittlejohn** [comment]
Before I go too far down the rabbit hole (on my Windows box) does this look like the right place to start?
https://github.com/expo/expo/blob/cc97d38952925b83e11805b91d33e159b754c558/android/expoview/src/main/java/host/exp/exponent/kernel/Kernel.java#L1024-L1048

**Comment by jesseruder** [comment]
Yes, that's the correct place to look @itslittlejohn

**Comment by itslittlejohn** [comment]
Interestingly, it seems that experiences published with an old version of `exp` do not allow pinning, whereas pinning with the latest few versions works fine. So I'm closing this issue as the workaround seems to be upgrade `exp`.

**Comment by FiberJW** [comment]
This seems to be resolved, so I'll close this for now. If you need further support, please make a topic on our [forums](https://forums.expo.io) :)
