### ISSUE TITLE
In iOS simulator, NetInfo.isConnected is always false

### ISSUE THREAD

**Issue by trajano** [expo/expo#13579]
### Summary

In iOS simulator, NetInfo.isConnected is always false, so we need to work around this by checking Constants.appOwnership and Platform.OS === "ios"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.0/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Just do the following

    const netInfo = await NetInfo.fetch();
    const connected =
      netInfo.isConnected && (netInfo.isInternetReachable ?? true);

      console.warn(
        "Connectivity check failed",
        netInfo.isConnected,
        netInfo.isInternetReachable
      );

on iOS you get `false` and `null` but Android works correctly.

**Comment by brentvatne** [comment]
you should post this to the netinfo repo :) https://github.com/react-native-netinfo/react-native-netinfo
