### ISSUE TITLE
SDK 42 is not compatible with react-native-maps according to npm v7

### ISSUE THREAD

**Issue by soullivaneuh** [expo/expo#13576]
### Summary

Because of not matched peer dependencies constraint, it is currently not possible to use react-native-maps on SDK 42:

```
❯ expo install react-native-maps
Installing 1 SDK 42.0.0 compatible native module using npm.
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native-web@0.13.18
npm ERR! node_modules/react-native-web
npm ERR!   react-native-web@"~0.13.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-web@"^0.11" from react-native-maps@0.28.0
npm ERR! node_modules/react-native-maps
npm ERR!   react-native-maps@"0.28.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/sullivan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sullivan/.npm/_logs/2021-07-10T18_36_52_290Z-debug.log
```

This happen on a fresh new project, but also with an upgrade from v41 with `react-native-maps` already installed.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.7.3 environment info:
    System:
      OS: Linux 5.9 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.10.0 - /usr/bin/node
      npm: 7.19.1 - /usr/bin/npm
    npmPackages:
      expo: ~42.0.1 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. `expo init my-app`
1. `cd my-app`
1. `expo install react-native-maps`

**Comment by byCedric** [comment]
Hi @soullivaneuh! Unfortunately, [npm decided to change how they handle optional peer dependencies in npm 7](https://twitter.com/markdalgleish/status/1325755229883621376). This causes some issues with our infrastructure at the moment. We built other parts of Expo, like Snack, to use peer dependencies for dependency detection. 

We will fix this eventually, but it will take some time. In the meantime you can run npm 6, [npm 7 with `--legacy-peer-deps` flag](https://stackoverflow.com/a/66346921/2277025), or use Yarn
