### ISSUE TITLE
Docs are not multilingual [docs] 

### ISSUE THREAD

**Issue by EvanErickson** [expo/expo#13571]
### Summary

Docs are not multilingual. I can convert the docs into Spanish and maybe Mandarin Chinese too. We can convert into languages like Russian too with google translate and then have a Russian / American dev look at it to make sure of the accuracy. Usually google translate is 70% of the way accurate. 

I can do Spanish first, and then move to Chinese if you guys want. I also speak Portuguese but it isn't as good as my Spanish.

**Comment by brentvatne** [comment]
i'd love for docs to be multi-lingual but we're too small of a team right now to make this possible and make sure everything is up to date. this would add a lot of overhead when changing existing docs or adding new pages and we're not at a point where we can accommodate it.

**Comment by brentvatne** [comment]
that said, i do really appreciate your offer to help out! thank you!
