### ISSUE TITLE
Created file get created in a wrong folder using MediaLibrary and dose not accept unknown MediaType

### ISSUE THREAD

**Issue by AlenToma** [expo/expo#13573]
### Summary

I am trying to export my data to an existing file eg a `json` file.

First off files that are of type `.json` wont work and the app simple crash so I had to use something else like a `.pdf`

Now this is not imported for me, what is imported is that the file dose not get created in the right Folder(Download)
and get created under Picture Folder instead and that is very irritating to encounter. 

This has worked before the update but not after.  

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.6.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Simple Create a file using `MediaLibrary`

## Here is my Code 

```js
  exportFileToDownloadFolder = async (loadProgress?: (progress: number) => void) => {
    try {
      const { status } = await MediaLibrary.requestPermissionsAsync();
      if (status === 'granted') {
        var favoriteData = await this.where<DetaliItemSettings>('DetaliItems', { isFavorit: true });
        var len = 1 + favoriteData.length;
        for (var i = 0; i < favoriteData.length; i++) {
          var item = favoriteData[i];

          item.chapterSettings = await this.where<ChapterSettings>('Chapters', { detaliItem_Id: item.id });
          item.id = 0;
          item.chapterSettings.forEach((x) => {
            x.id = 0;
            x.detaliItem_Id = 0;
          });
          await this.onProgress((i / (len) * 100), loadProgress);
        }
        var appsettings = await this.findOne<NovelReaderSettings>('ApplicationSettings');
        if (appsettings)
          appsettings.userIdentifier = "";
        var result = {
          applicationSettings: appsettings,
          items: favoriteData,
          parserSettings: await this.where<ParserSettings>("ParserSettings")
        };

        var album = "Download/NovelManager"; // I am writing Download folder but it get under Picture Folder instead
        let fileUri = FileSystem.cacheDirectory + 'NovelManager.backup.pdf'; // tryied to use .json but the app crash
        await FileSystem.writeAsStringAsync(fileUri, JSON.stringify(result), { encoding: "utf8" });
        const asset = await MediaLibrary.createAssetAsync(fileUri);
        var al = await MediaLibrary.createAlbumAsync(album, asset, true); // Copy First
        await MediaLibrary.deleteAlbumsAsync(al, true); // Remove all
        await MediaLibrary.createAlbumAsync(album, asset, false);// Then Move
        var assets = await MediaLibrary.getAssetsAsync({
          first: 10,
          album: al.id,
          mediaType: MediaLibrary.MediaType.unknown,
          sortBy: MediaLibrary.SortBy.creationTime,
        })
        await this.onProgress((len / (len) * 100), loadProgress);
        if (assets.totalCount > 0) {
          return assets.assets[0].uri; // return this so we could show a notification
        }
        return true;
      }
    } catch (error) {
      console.log(error);
    }
    return false;
  };
```

**Comment by f-ricci** [comment]
I'm experiencing the same issue.

```
const result = await ImageManipulator
          .manipulateAsync(
            photo.uri,
            [resize],
            { compress: 0.8, format: ImageManipulator.SaveFormat.JPEG, base64: false }
          )
          .catch(error => {
            console.log('error', error)
          })

        const photo = await MediaLibrary.createAssetAsync(result.uri)
        await FileSystem.deleteAsync(result.uri, { idempotent: true })
```

This only happens since I have updated all expo libraries to the latest version.

I have tracked the issue down to the file `EXMediaLibrary.m` at `line: 164` where the module for iOS exports the `createAssetAsync` function.

**Comment by eungook** [comment]
I think expo-image-manipulator@9.2.2 has some issues. (but @9.1.0 works well!)
Here is my dependencies.
```
"expo": "^41.0.1",
"expo-image-picker": "~10.1.4",
"expo-image-manipulator": "~9.2.2",
```

**Comment by AlenToma** [comment]
I think that using `MediaLibrary ` to write files other then images is wrong in it self. My issue should be handled by the `FileSystem`
Here is my suggestion.

`FileSystem` should be able to have a property like `DownloadsPath` which return a path to downloads folder. 

And also should be able to handle writing to that folder for which it cant even when I tried.

So I have just build my own `Modules` since I am using bare anyway which worked like a charm.
