### ISSUE TITLE
react-native-maps lib update needed - Crash on Android Polyline, reverted on `0.29.2`

### ISSUE THREAD

**Issue by douglaslondrina** [expo/expo#13584]
### Summary

In `react-native-maps` current expo supported version (0.28.0), there's a crashing bug on using Polyline on Android.
Using any Polyline will cause the crash, really.

There's a workaround, by setting `lineDashPattern`, but that causes a different visual representation for the line.

The offending commit was removed on `0.29.2`, so we need a minor update on Expo 42, preferably.

This bug was reported and discussed on:
https://github.com/react-native-maps/react-native-maps/issues/3823 

("Error while updating property 'lineCap' of a view managed by: AIRMapPolyline")

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.volta/tools/image/node/15.14.0/bin/node
      Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
      npm: 7.7.6 - ~/.volta/tools/image/node/15.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.3 - /Users/douglas/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 26, 27, 28, 29, 30
        Build Tools: 21.1.2, 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-19 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.3 => 4.4.4 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Add any Polyline on Android using react-native-maps

**Comment by byCedric** [comment]
Hi @douglaslondrina, thanks for writing in. Unfortunately, the maintainers from `react-native-maps` only released `0.29.x` as an alpha/beta prerelease. Because of that, we can't upgrade the version in Expo yet. One thing you can try is asking them to release a new `0.28.x` as a stable version, without the offending commit (e.g. `0.28.1`). If they do that, we can start the upgrade internally for Expo Go.

If you absolutely need this, I would recommend [building with EAS](https://docs.expo.io/eas/). You can use `0.29.x` in your dependencies and it would create a new build with that version, it also supports managed projects.

Hope this helps!

**Comment by christopherdro** [comment]
The offending commit was NOT included in v0.28.0. It was initially released with v0.29.0 and reverted in v0.29.2.

**Comment by brentvatne** [comment]
great! thanks for the context @christopherdro.
