### ISSUE TITLE
[expo-media-library] Photos in library are not showing up

### ISSUE THREAD

**Issue by Joshandrews43** [expo/expo#13588]
### Summary

Many photos from the library do not show up correctly when pulling assets from `expo-media-library` using `getAssetsAsync()`. This was initially reported to me by a user when downloading photos from whatsapp, which I confirmed as well as a developer in #10002. However, I have found that it is more than just whatsapp, but many photos saved from various places that arent taken directly from the camera roll.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42.0.0

### Environment

```
  Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1) save a photo from whatsapp 
2) confirm the photo is in your recents or library folder
3) call `MediaLibrary.getAssetsAsync()` on your recents folder
4) The photo will not be in the pulled photos

**Comment by yagudaev** [comment]
@Joshandrews43 can you create a quick demo project and post a link to the github repo? It will help the core team quickly verify the problem.

**Comment by Joshandrews43** [comment]
@yagudaev it seems like it only happens sometimes because on this sample project i just made it seems to be working only sometimes. We both confirmed in #10002 that it was bugged, but on here i got about 4 photos to work and one not working... No idea....

https://github.com/Joshandrews43/media-library-issue

**Comment by Joshandrews43** [comment]
Bump!

**Comment by majirosstefan** [comment]
not completed

**Comment by next6leo** [comment]
yea is not working in some android phone

**Comment by dhmoon91** [comment]
Experiencing this as well. Downloaded photos are not getting pulled in using `media-library`

**Comment by hotaryuzaki** [comment]
is there any solution? or is it any alternative for media library?

**Comment by hotaryuzaki** [comment]
i change to @react-native-camera-roll/camera-roll
need some effort for different API they're using and the upload image handler because the object data structure differences.
but problem solved

**Comment by EzioAuditore12** [comment]
In app.json , you need to enable following permissions on android

permissions

```json
permissions:[
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
        "android.permission.ACCESS_MEDIA_LOCATION",
        "android.permission.READ_MEDIA_IMAGES",
        "android.permission.READ_MEDIA_VIDEO",
]
```
