### ISSUE TITLE
[expo-screen-orientation] couldnt build using Xcode 13 beta

### ISSUE THREAD

**Issue by listiani13** [expo/expo#13589]
### Summary

In Xcode 12.5, I can build just fine. After upgrading to Xcode 13 beta, I ran into this error while running `expo run:ios` / building directly from Xcode
![image](https://user-images.githubusercontent.com/24470609/125383899-54c09580-e3c2-11eb-9a0d-534a952ec5c5.png)

The bug seems to be coming from `expo-screen-orientation`. I use `@expo/match-media`, that's why `expo-screen-orientation` got installed

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v14.17.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/me/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://github.com/listiani13/repro-sdk-42

**Comment by brentvatne** [comment]
hello! care to investigate and send a pr? we don't support xcode 13 beta yet

**Comment by byCedric** [comment]
It might be related to an outdated `expo-screen-orientation` used in `@expo/match-media`. If you use Yarn, you can try to add a resolution to force-overwrite this and test if it works with the newer version. Add this to your `package.json`:

```json
"resolution": {
  "expo-screen-orientation": "^3.0.0"
}
```

**Comment by creativemind1** [comment]
@listiani13 @byCedric @brentvatne   I'm also facing same issue in Xcode 13 beta. I've tried updating expo-screen-orientation to `3.0.0` and even `3.2.1` but still same issue. Can this be fixed please?

**Comment by kkafar** [comment]
Issue fixed by #13898
