### ISSUE TITLE
Could not declare a static getter method called "name"

### ISSUE THREAD

**Issue by HasanAlyazidi** [expo/expo#1358]
### Environment

Environment:
  OS: Windows 10
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/hasan-21b5f751-9ed2-4b39-a5df-5ffba4b3c553.tar.gz

### Steps to Reproduce

1. Create an Expo project
2. Create an ES6 class
3. Declare a static getter method called name
4. Open the project on **Android**

### Expected Behavior

I can declare a static getter method called name, so i can call it from a component.

### Actual Behavior

Once i create a class and declare static getter method called name
```javascript
class User {
  static get name() {
    return 'Expo';
  }
}
```
then i run the project, the following error appears:
**attempting to configurable attribute of unconfigurable property**

![error](https://preview.ibb.co/iWWYDm/Screenshot_20180130_024629.png "Error")

### Reproducible Demo

https://snack.expo.io/SkE8cEpHf

everything works as expected on iOS, but the problem occurs on Android

Thank You Expo Team

**Comment by brentvatne** [comment]
Android uses an old version of JavaScriptCore currently, so there are slight differences in the features that are available. I believe you could install a babel plugin to compile this away for you and have it work on both platforms, but I'm not personally familiar with what the plugin is. You can read more about supported JavaScript features in this doc: https://docs.expo.io/versions/latest/guides/using-modern-javascript.html
