### ISSUE TITLE
Linear Gradient props change

### ISSUE THREAD

**Issue by VinceBT** [expo/expo#136]
Update the props `start` and `end` of LinearGradient component so it fits the one from [the original package](https://github.com/react-native-community/react-native-linear-gradient)

Now they use an object like { x: number, y: number } and not a size-2 array.

**Comment by nikki93** [comment]
cc @brentvatne

**Comment by nikki93** [comment]
@VinceBT feel free to make a PR for this change! could you make it backwards compatible? so that we don't break old code

**Comment by aalices** [comment]
@VinceBT the PR I made has been merged (not sure if it is available for you yet) so check out ;)

**Comment by brentvatne** [comment]
it is available in `expo@18.0.6` :) thanks @aalices!
