### ISSUE TITLE
Hermes enabled makes Android Crash

### ISSUE THREAD

**Issue by haibert** [expo/expo#13603]
### Summary
I have used the [expo documentation](https://docs.expo.io/guides/using-hermes/#standalone-apps-created-with--expo-build) to enable Hermes in my project. When I launch the app starts and crashes right away with the following message, at the end of the message says **in AppContainer (at renderApplication.js:39), js engine: hermes** 

![IMG_0690](https://user-images.githubusercontent.com/31780749/125535178-2e1f6177-627c-414e-9965-b58cb4fe537b.jpg)

TypeError: property is not configurable

This error is located at:
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:448)
    in AnimatedComponent(View) (at createAnimatedComponent.js:459)
    in ForwardRef(AnimatedComponentWrapper) (at TouchableScale.js:54)
    in TouchableWithoutFeedback (at TouchableScale.js:44)
    in ScaleButton (at Thumbnail.js:104)
    in ThumbNail (at DashboardScreen.js:268)
    in RCTView (at View.js:34)
    in View (created by BigListItem)
    in BigListItem
    in BigListItem (created by BigList)
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1250)
    in AndroidSwipeRefreshLayout (at RefreshControl.js:197)
    in RefreshControl (created by BigList)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (created by BigList)
    in RCTView (at View.js:34)
    in View (created by BigList)
    in BigList (at DashboardScreen.js:328)
    in RCTView (at View.js:34)
    in View (at ScreenWrapper.js:38)
    in RCTView (at View.js:34)
    in View (created by NativeLinearGradient)
    in NativeLinearGradient (created by LinearGradient)
    in LinearGradient (at ScreenWrapper.js:25)
    in ScreenWrapper (at DashboardScreen.js:318)
    in DashboardScreen (at createSharedElementScene.tsx:96)
    in RCTView (at View.js:34)
    in View (at createSharedElementScene.tsx:88)
    in SharedElementSceneView (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:620)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:613)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:495)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.tsx:21)
    in GestureHandlerRootView (at StackView.tsx:454)
    in StackView (at createSharedElementStackNavigator.tsx:80)
    in SharedElementStackNavigator (at createSharedElementStackNavigator.tsx:164)
    in WrapNavigator (at navigation.js:151)
    in DashModalStack (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:147)
    in Screen (at ResourceSavingScene.tsx:30)
    in ResourceSavingScene (at DrawerView.tsx:203)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at DrawerView.tsx:182)
    in RCTView (at View.js:34)
    in View (at Drawer.tsx:625)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:448)
    in AnimatedComponent(View) (at createAnimatedComponent.js:459)
    in ForwardRef(AnimatedComponentWrapper) (at Drawer.tsx:618)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:448)
    in AnimatedComponent(View) (at createAnimatedComponent.js:459)
    in ForwardRef(AnimatedComponentWrapper) (at Drawer.tsx:608)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Drawer.tsx:599)
    in DrawerView (at DrawerView.tsx:235)
    in SafeAreaProviderCompat (at DrawerView.tsx:233)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.tsx:21)
    in GestureHandlerRootView (at DrawerView.tsx:232)
    in DrawerView (at createDrawerNavigator.tsx:47)
    in DrawerNavigator (at navigation.js:480)
    in DrawerNav (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:620)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:613)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:495)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in GestureHandlerRootView (at GestureHandlerRootView.android.tsx:26)
    in GestureHandlerRootView (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at navigation.js:554)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at navigation.js:537)
    in AppNavigator (at App.js:59)
    in Provider (at App.js:58)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    **in AppContainer (at renderApplication.js:39), js engine: hermes**
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog
at node_modules/react-redux/lib/utils/Subscription.js:25:11 in notify
at node_modules/react-redux/lib/utils/Subscription.js:96:4 in notifyNestedSubs
at node_modules/react-redux/lib/utils/Subscription.js:101:6 in handleChangeWrapper
at node_modules/redux/lib/redux.js:228:14 in dispatch
at node_modules/redux-thunk/lib/index.js:14:19 in <anonymous>
at node_modules/redux/lib/redux.js:644:17 in dispatch
at http://192.168.66.104:8081/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false:218101:22 in _callee2$
- ... 16 more stack frames from framework internals

Hermes version: 0.5.1
React Native version (if any): 0.63.2
Expo SDK: 42
OS version (if any): Android version 9
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

code example:

`
`
{
    "expo": {
        "name": "EventShare",
        "slug": "EventShare",
        "version": "0.1.0",
        "orientation": "portrait",
        "icon": "./assets/1024.png",
        "splash": {
            "image": "./assets/splash.png",
            "resizeMode": "contain",
            "backgroundColor": "#ffffff"
        },
        "androidStatusBar": {
            "backgroundColor": "#ffffff",
            "translucent": true
        },
        "updates": {
            "fallbackToCacheTimeout": 0
        },
        "assetBundlePatterns": ["**/*"],
        "ios": {
            "supportsTablet": true,
            "userInterfaceStyle": "dark",
            "infoPlist": {
                "NSCameraUsageDescription": "This app uses the camera to take pictures, videos and scan barcodes on from other users."
            },
            "bundleIdentifier": "com.simplyrem.GalleryShare",
            "buildNumber": "1.0.8",
            "icon": "./assets/1024.png"
        },
        "android": {
            "jsEngine": "hermes",
            "adaptiveIcon": {
                "foregroundImage": "./assets/adaptive-icon.png",
                "backgroundColor": "#FFFFFF"
            },

            "userInterfaceStyle": "dark",
            "package": "com.simplyrem.GalleryShare"
        },
        "web": {
            "favicon": "./assets/favicon.png"
        }
    }
}
`

`

## The Expected Behavior

The app should run normally without crashing. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I followed the steps in expos documentation 
1.  add jsEngine field under the android section in app.json 

"android": {
            "jsEngine": "hermes",
}
then ran **eas build --profile development --platform android ** to create the custom client and install.

**Comment by brentvatne** [comment]
hi there! please share a minimal reproducible example project. the instructions you provided are incomplete because we don't have a project to run those against

**Comment by brentvatne** [comment]
happy to reopen if you can provide a reproducible example that demonstrates something is wrong on our end

**Comment by brentvatne** [comment]
perhaps related (since this appears to include navigation code in your stack trace): https://github.com/react-navigation/react-navigation/issues/9627

**Comment by haibert** [comment]
I have created a new public repo of my project! Here it is.

https://github.com/haibert/eventSharePublic

**Comment by brentvatne** [comment]
hey @haibert! can you try to narrow down exactly what is causing this error to identify if it is anything to do with expo code? here's an approach you can take for that: https://expo.fyi/manual-debugging

**Comment by haibert** [comment]
Hey Brent 
I commented out all screens from my navigation stack expect the login and it's not crashing. I'll do further investigation and report back, thank you for getting me started on a path to recovery here.

**Comment by brentvatne** [comment]
@haibert - when errors are coming from an unexpected interaction between a library whose code you aren't familiar with and another tool it can be hard to debug indeed. i recommend just simplifying your app to a "hello world" app (like the App.js you get when you run `expo init`) and then adding code back bit by bit until it breaks
