### ISSUE TITLE
[docs] [expo-facebook] logEventAsync

### ISSUE THREAD

**Issue by edwardkong86** [expo/expo#13606]
### Summary

Hi team, i notice that expo-facebook recently added logEventAsync() & logPurchaseAsync(). I tried to use those function however there was nothing trigger to FB Event Manager. Also there wasn't any documentation about it too. May i know the feature still in development? 

I also notice there is also getAdvertiserIDAsync()and i tried to use the Id to trigger Facebook Activity Event. However it also fail to capture at FB Event Manger too.

Below are the version that i used.
expo SDK: 42
expo-facebook: 11.3.1

I hope that we able to use those method to sending app activities back to facebook.

Thanks.

### Link to the related docs page

https://docs.expo.io/versions/latest/sdk/facebook/

**Comment by cruzach** [comment]
Thanks for filing! Fixed now
