### ISSUE TITLE
Statusbar turns white when the modal is open (only on certain devices)

### ISSUE THREAD

**Issue by mmazzarolo** [expo/expo#1361]
### Environment

[Diagnostics](https://exp-xde-diagnostics.s3.amazonaws.com/matteomostaza-a076dbf6-672c-4481-8f2e-7ae3a7740200.tar.gz)

### Steps to Reproduce

Create a new Expo app and just  show a modal with the `transparent` prop set to `true`. 

### Expected Behavior

The modal should open and show the statusbar beneath it.

### Actual Behavior

The modal opens and shows a white statusbar.
[Screenshot example](https://user-images.githubusercontent.com/20864001/28848476-bf29b6bc-771b-11e7-857f-a6ef7edf17ad.png)

### Reproducible Demo

```
import React from "react";
import { Modal, View } from "react-native";

export default class App extends React.Component<{}> {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <Modal transparent={true} style={{ flex: 1 }}>
          <View style={{ backgroundColor: "blue", flex: 1 }} />
        </Modal>
      </View>
    );
  }
}
```

[The issue has been reported multiple time here](https://github.com/react-native-community/react-native-modal/issues/50). 

The following devices have the issue:

* Google Nexus 9 - 6.0.0 - API 23
* Google Nexus 5 - 5.1.0 - API 22

The following devices work as expected:

* 10.1_WGXA_Tablet_API_26

I guess it might be related to the API then, as the StatusBar Expo docs suggest.

Please notices that apps created using react-native (react-native init AppName) work correctly on all devices mentioned above, only Expo apps have the issue.

Let me know if you need further infos!

**Comment by jimmylee** [comment]
Thanks for reporting! Assigning this to @jesseruder who can help reassign this to the right expert.

**Comment by mmazzarolo** [comment]
I was wrong, unfortunately the issue happens on `10.1_WGXA_Tablet_API_26` too.

**Comment by GollyJer** [comment]
Hi.  Was troubleshooting this today and landed here.
Someone did come up with a fix but their package requires `react-native link`.

Maybe the code can inspire a fix on the Expo side?
[https://github.com/listenzz/react-native-modal-translucent](https://github.com/listenzz/react-native-modal-translucent)

**Comment by bschnelle** [comment]
any update on this?
