### ISSUE TITLE
[expo-av] - Sometimes audio doesn't play when replay is triggered in short intervals (1000ms)

### ISSUE THREAD

**Issue by ErickMaeda** [expo/expo#13623]
### Summary

**Expected behavior**
When using expo-av `replayAsync` method the audio should replay whenever the method is invoked.

**What's happening**
In some devices (**Moto g5 Android 8.1.9 and Galaxy S2 tablet Android 7**) sometimes the audio is skipped and not played. No error is presented, even when trying to catch the exception.  [Here](https://user-images.githubusercontent.com/12499837/125702663-8de4f8aa-5f89-45a6-932f-0df7de32c3f9.mp4) is a link to a video demonstrating the issue.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.0 & 38.0.0

### Environment

```
Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 30.0.3
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-S | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

We narrowed down the issue to this prototype. It uses `setInterval` to call `replayAsync` at fixed intervals.
https://github.com/vgrocha/expo-av-bug-replay/blob/main/App.js#L33

We only noticed this issue in few Android devices. Ex: **Moto g5 Android 8.1.9 and Galaxy S2 tablet Android 7**

**Comment by Madhav-Malhotra** [comment]
I just couldn't get expo-av to work in general on Moto G6, Android 9 or on the web. Details [here](https://github.com/expo/expo/issues/14291)

**Comment by gsevla** [comment]
Exact same problem on Moto G7 Play with Android 10.
