### ISSUE TITLE
I run "expo publish", I get this error: Missing module "hermes-engine/win64-bin/hermesc" in the project

### ISSUE THREAD

**Issue by asalha** [expo/expo#13626]
### Summary

I upgraded recently from SDK 41 to SDK 42 and enabled hermes by following the instructions here: https://docs.expo.io/guides/using-hermes/

I am on Windows 11, I run the following EAS build smoothly without any problem:
````
eas build --clear-cache --platform android
````
The apk is generated and it has a reduced size and it is lightening fast at launch.
The problem comes when I make changes to the code and run "expo publish" for OTA updates, it gives the following error:
````
Missing module "hermes-engine/win64-bin/hermesc" in the project.This usually means hermes-engine is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.
````

Hermes engine is installed under react-native as seen in the screenshot below:
![hermes-error](https://user-images.githubusercontent.com/4199314/125747625-449a2755-ce34-4d69-8844-a7f2b8cca93a.jpg)

Although not necessary, I installed hermes-engine (npm i hermes-engine) and tried again, same problem.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.7.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

On SKD 42, enable hermes, run eas build and then "expo publish".

**Comment by Kudo** [comment]
hi there!
it is interesting that your hermes-engine is nested inside `/yourRepo/node_modules/react-native/hermes-engine`.
could you help to clarify these questions?

1. after `npm i hermes-engine`, will hermes-engine exist in `/yourRepo/node_modules/hermes-engine`?
2. did you use `--global-style` during npm install in your repo?
3. does metro exist in your repo, e.g. `/yourRepo/node_modules/metro`? if metro is not there, supposedly `expo start` will not work as well.
4. is your repo is a monorepo?
5. if you are okay with it, sharing `dependencies`, `peerDependencies`, and `devDependencies` in your package.json would be super helpful.

would like to clarify the reason why hermes-engine is nested installed. thank you for reporting this issue to us.

**Comment by ecreeth** [comment]
@Kudo this is happening on Windows.

https://github.com/expo/expo-cli/blob/08f9484949d0ab083992fad53dcde7d25faa5142/packages/dev-server/src/HermesBundler.ts#L71

```js
const resolvedPath = resolveFrom.silent(projectRoot, `hermes-engine/${platform}/hermesc`);
```
Never is gonna find the file without the **.exe** extension. This solved the problem.
We need to add the extension dynamically on Windows

**Comment by Kudo** [comment]
@ecreeth thank you for the solution. the change is merged and will let you know once we releasing new version.

@asalha i am thinking if the solution might not help for you because the nested `node_modules/react-native/node_modules/hermes-engine`. if you still encounter the issue even after the fix, please let us know. thanks!

**Comment by Kudo** [comment]
hi there!
we've published new version of expo-cli with the fix. please try with the latest version and let us know if the issue still happens.

**Comment by asalha** [comment]
Hello, sorry for the very late reply.

> 1. after `npm i hermes-engine`, will hermes-engine exist in `/yourRepo/node_modules/hermes-engine`?

Yes, it was always there after I installed it.
> 2. did you use `--global-style` during npm install in your repo?

No
> 3. does metro exist in your repo, e.g. `/yourRepo/node_modules/metro`? if metro is not there, supposedly `expo start` will not work as well.

Yes sure, it's there.
> 4. is your repo is a monorepo?

No.
> 5. if you are okay with it, sharing `dependencies`, `peerDependencies`, and `devDependencies` in your package.json would be super helpful.

Here they are:
````
  "dependencies": {
    "@react-native-community/datetimepicker": "3.5.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "6.0.0",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "date-fns": "^2.22.1",
    "expo": "^42.0.0",
    "expo-app-auth": "~10.2.2",
    "expo-application": "~3.2.0",
    "expo-camera": "~11.2.2",
    "expo-constants": "~11.0.1",
    "expo-dev-client": "^0.4.5",
    "expo-device": "~3.3.0",
    "expo-facebook": "~11.3.1",
    "expo-font": "~9.2.1",
    "expo-google-sign-in": "~9.2.1",
    "expo-image-manipulator": "~9.2.2",
    "expo-image-picker": "~10.2.2",
    "expo-localization": "~10.2.0",
    "expo-location": "~12.1.2",
    "expo-media-library": "~12.1.2",
    "expo-notifications": "~0.12.3",
    "expo-permissions": "^12.1.1",
    "expo-screen-orientation": "^3.2.1",
    "expo-secure-store": "~10.2.0",
    "expo-status-bar": "~1.0.4",
    "expo-task-manager": "~9.2.2",
    "expo-updates": "~0.8.2",
    "firebase": "8.2.3",
    "i18n-js": "^3.8.0",
    "lodash": "^4.17.21",
    "patch-package": "^6.4.7",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-confirmation-code-field": "^7.1.0",
    "react-native-dropdown-picker": "^5.1.17",
    "react-native-elements": "^3.4.1",
    "react-native-geocoding": "^0.5.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-maps": "0.28.0",
    "react-native-numeric-input": "^1.9.0",
    "react-native-pager-view": "5.0.12",
    "react-native-popup-menu": "^0.15.10",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-scroll-bottom-sheet": "^0.7.0",
    "react-native-tab-view": "^3.0.1",
    "react-native-toast-message": "^1.4.9",
    "sentry-expo": "^4.0.0",
    "expo-linking": "~2.3.1"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@sentry/cli": "^1.67.1",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "@typescript-eslint/eslint-plugin": "^4.24.0",
    "@typescript-eslint/parser": "^4.24.0",
    "eslint": "^7.27.0",
    "eslint-plugin-react": "^7.23.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "typescript": "~4.0.0"
  },
````

**Comment by asalha** [comment]
> hi there!
> we've published new version of expo-cli with the fix. please try with the latest version and let us know if the issue still happens.

Hello Kudo, I have bad news:
1. I installed the latest expo-cli
2. I added `"jsEngine": "hermes"` to my `app.json`
3. I ran a new `eas build`, everything was ok
4. I downloaded the build and installed the app on my phone
5. I confirm the app size is a lot smaller and startup is a lot faster => hermes is working fine and the app worked normally
6. I added a new screen and ran `expo publish`: I got the same error as before saying the hermes-engine is not installed
7. I installed hermes using npm: `npm i hermes-engine`
8. I ran again `expo publish` => everything went well, I opened the app and I got message an alert (from expo-updates) saying there's a new update, restart your app
9. I restarted the app => IT CRASHED
10. I ran `eas build` because I installed a new package
11. I downloaded the app, on open => CRASHED AGAIN
12. I thought it's my code the problem, so I started the app in Expo Go => everything is fine, no crash or any error on Sentry too.

Any idea what's happening?

**Comment by Kudo** [comment]
@asalha custom `npm i hermes-engine` is risky because the hermes version might be different and that's my guess to the crash. we should clarify why react-native depended hermes-engine being placed nested inside `node_modules/react-native/node_modules` but not metro. i've tried to initiate a project with dependencies & devDependencies exactly like you shared and having this error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react-native-vector-icons@8.1.0
npm ERR! node_modules/react-native-vector-icons
npm ERR!   peer react-native-vector-icons@">7.0.0" from react-native-elements@3.4.2
npm ERR!   node_modules/react-native-elements
npm ERR!     react-native-elements@"^3.4.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-native-numeric-input@"^1.9.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react-native-vector-icons@4.6.0
npm ERR! node_modules/react-native-vector-icons
npm ERR!   peer react-native-vector-icons@"^4.*" from react-native-numeric-input@1.9.0
npm ERR!   node_modules/react-native-numeric-input
npm ERR!     react-native-numeric-input@"^1.9.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/kudo/.npm/eresolve-report.txt for a full report.
```

could you check your `package-lock.json` to see there are multiple hermes-engine version to make the nested dependency happens?

**Comment by mirik999** [comment]
In my case i have the same problem but hermes-engince located in node_modules folder in priject ( not in nested react-native/node_modules ) 
I cant run expo publish 
Got an error 
```
Building Hermes bytecode for the bundle - platform[android]
Missing module "hermes-engine/win64-bin/hermesc" in the project.This usually means hermes-engine is not installed. Please verify that dependencie
s in package.json include "react-native" and run `yarn` or `npm install`.
```

**Comment by Kudo** [comment]
@mirik999 what is your expo-cli version ? (you could execute `expo --version` to check)
please make sure to use the latest v4.9.1.

**Comment by asalha** [comment]
> could you check your `package-lock.json` to see there are multiple hermes-engine version to make the nested dependency happens?

Hello @Kudo, sorry for the late reply. Here's a copy of my package-lock.json file
https://drive.google.com/file/d/1z9XpMU8bCK9xHoChbJMbzSm-k5lF5z2a/view?usp=sharing

**Comment by Kudo** [comment]
@asalha that is interesting. i am not sure how it happens to make hermes-engine nested in your package-lock.json, but reinstall react-native did help.

```shell
npm uninstall react-native
npm install --save https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
```

**Comment by asalha** [comment]
> @asalha that is interesting. i am not sure how it happens to make hermes-engine nested in your package-lock.json, but reinstall react-native did help.
> 
> ```shell
> npm uninstall react-native
> npm install --save https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
> ```

Wow, it did work!!! Thank you so much.

**Comment by Kudo** [comment]
> > @asalha that is interesting. i am not sure how it happens to make hermes-engine nested in your package-lock.json, but reinstall react-native did help.
> > ```shell
> > npm uninstall react-native
> > npm install --save https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
> > ```
> 
> Wow, it did work!!! Thank you so much.
> 
> The weird thing is that I removed `node_modules` completely before and ran `npm install` and I got `hermes-engine` inside `node_modules` of `react-native`. I didn't understand what was happening.

glad to hear it works for you.
removing only node_modules is not enough since npm will install packages based on package-lock.json and your package-lock.json has hermes-engine nested inside react-native. you could try to remove both `node_modules` and `package-lock.json`, then supposedly `npm install` again should also works for you.

**Comment by asalha** [comment]
> > > @asalha that is interesting. i am not sure how it happens to make hermes-engine nested in your package-lock.json, but reinstall react-native did help.
> > > ```shell
> > > npm uninstall react-native
> > > npm install --save https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
> > > ```
> > 
> > 
> > Wow, it did work!!! Thank you so much.
> > The weird thing is that I removed `node_modules` completely before and ran `npm install` and I got `hermes-engine` inside `node_modules` of `react-native`. I didn't understand what was happening.
> 
> glad to hear it works for you.
> removing only node_modules is not enough since npm will install packages based on package-lock.json and your package-lock.json has hermes-engine nested inside react-native. you could try to remove both `node_modules` and `package-lock.json`, then supposedly `npm install` again should also works for you.

Yep, you were right from the beginning. No `hermes-engine` in `react-native` anymore, that's why it worked. Thanks
