### ISSUE TITLE
Expo SDK 42: Expo Document picker does not return correct uri

### ISSUE THREAD

**Issue by syazwancode** [expo/expo#13627]
### Summary

I am using the expo document picker to let the user select a pdf file and send it to the server. 

It was working previously when I was running on expo SDK 41 until I upgrade it to Expo SDK 42.

Before this, it was returning a uri starting with file:///data/ where now, it returns a uri starting with /data. 

I tried to append the uri to include file:// at the front but its not working either.

Previous version:
- "expo": "~41.0.1",
- "expo-document-picker": "~9.1.2",

Current version:
- "expo": "^42.0.0",
- "expo-document-picker": "~9.2.4",

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

see snack expo 42 (incorrect uri): https://snack.expo.io/@syazwan.dev/sdk42-document-picker

see snack expo 41 (expected uri): https://snack.expo.io/@syazwan.dev/sdk41-document-picker

**Comment by pedrohenriquebraga** [comment]
Same here

**Comment by kartikeyvaish** [comment]
Same Here

**Comment by syazwancode** [comment]
@pedrohenriquebraga @kartikeyvaish @lukmccall have you tried this fix? is it working?

**Comment by pedrohenriquebraga** [comment]
> @pedrohenriquebraga @kartikeyvaish @lukmccall have you tried this fix? is it working?

Yes, i tried add the file scheme manually, but not work

**Comment by kartikeyvaish** [comment]
I tried,
```javascript
const PickImage = async () => {
  try {
    const response = await DocumentPicker.getDocumentAsync({
      type: "image/*",
    });

    console.log(response);
  } catch (error) {}
};
```

I got this as a response

```javascript
{
  "name": "IMG-20210723-WA0031.jpg",
  "size": 90090,
  "type": "success",
  "uri": "/data/user/0/com.socio/cache/DocumentPicker/da212d4a-7139-41d6-b972-5d026ff989b6.jpg",
}
```

So, it's not fixed. @lukmccall @mstach60161

**Comment by lukmccall** [comment]
@kartikeyvaish did you apply this fix manually? This fix hasn't been published yet.

**Comment by ErikHasp** [comment]
We have found a workaround until this change is published:
```
export const fromFile = (uri: string) => {
  if (Platform.OS === 'android') return encodeURI(`file://${uri}`)
  else return uri
}
```

```
...
const doc = await DocumentPicker.getDocumentAsync({type: 'application/pdf'})
const correctUri = fromFile(doc.uri)
...
```
