### ISSUE TITLE
iOS Build Failed: Unable to generate IPA. unable to build and sign IPA

### ISSUE THREAD

**Issue by Arjit-Dhavale** [expo/expo#1362]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.11.4
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

### Steps to Reproduce

I am trying to create a build for MDM InHouse Distribution. I am following following steps before I start the build:
1. Create App ID in Apple Developer Account. Ensured same BundleID is used in app.json
2. Create production distribution certificate (selected in house distribution option) and then export to .p12 file. Performed this action manually and using "exp fetch:ios:certs" command. No difference identified.
3. Created production mobile provision profile and exported same.
4. Ensured correct team id is selected.

Below is the command used to create build and complete action trail:

exp build:ios --clear-credentials -c
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Removed existing credentials
? How would you like to upload your credentials?
 I will provide all the credentials and files needed, Expo does limited validati
on

We need your Apple ID/password to ensure the correct teamID and appID

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? XXXXXXX@icloud.com
? Password? **********
[exp] Validating Credentials...
[exp] You have 3 teams
1) 4BYCEW9T8X "xxxxxx" (In-House)
2) 7645SX35DF "xxxxxxx" (Company/Organization)
3) UYZQLBFRJB "xxxxxxx" (In-House)
? Which Team ID to use? 3) UYZQLBFRJB "xxxxxx" (In-House)
[exp] 
WARNING! In this mode, we won't be able to make sure your certificates,
or provisioning profile are valid. Please double check that you're
uploading valid files for your app otherwise you may encounter strange errors!

Make sure you've created your app ID on the developer portal, that your app ID
is in app.json as `bundleIdentifier`, and that the provisioning profile you
upload matches that team ID and app ID.

[exp] Please provide your distribution certificate P12:
? Path to P12 file: /Users/dhavaar/Documents/Projects/Release/XXXXXX/Ce
rtificates.p12
? P12 password: ***********
[exp] Please provide the path to your push notification cert P12
? Path to P12 file: /Users/dhavaar/Documents/Projects/Release/XXXXXXX/Ce
rtificates.p12
? P12 password: ***********
[exp] Please provide the path to your .mobile provisioning profile
? Path to your .mobile provisioning Profile /Users/dhavaar/Documents/Projects/Re
lease/XXXXXXXX/XXXXXXX.mobileprovision
[exp] Encrypted certP12,certPassword,pushP12,pushPassword,provisioningProfile,teamId and saved to expo servers
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://exp.host/@arjitdhavaleey/iInsights

[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] You can monitor the build at

 https://expo.io/builds/58a6d704-6a6d-420a-879f-b624fde1a922

[exp] Alternatively, run `exp build:status` to monitor it from the command line.

While checking the build information on the URL I receive following:

running shell app builder
extracting build configuration from app.json
[04:36:22] Using gulpfile /usr/local/turtle-agent/tools-public/gulpfile.js
[04:36:22] Starting 'ios-shell-app'...
IosIcons: setting image functions to alternative sharp implementations
Using manifest: {"description":"XXXXXXXXX","icon":"./assets/Icon-1024.png","iconUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/7d5a0521bf415363dff02b9866cb4c04","ios":{"buildNumber":"1.0.1","bundleIdentifier":"XXXXXXXXXX","isTabletOnly":true,"supportsTablet":true},"name":"iInsights","orientation":"landscape","primaryColor":"#000000","privacy":"public","scheme":"XXXXX","sdkVersion":"25.0.0","slug":"iInsights","splash":{"backgroundColor":"#000000","image":"./assets/Icon-1024.png","imageUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/7d5a0521bf415363dff02b9866cb4c04","resizeMode":"contain"},"version":"1.0.1","id":"@arjitdhavaleey/iInsights","revisionId":"1.0.1-r.o3dVdQM1vv","publishedTime":"2018-01-30T12:40:04.675Z","bundleUrl":"https://d1wp6m56sqw74a.cloudfront.net/%40arjitdhavaleey%2FiInsights%2F1.0.1%2F2475e8f698af825b99b01f852fb569cf-25.0.0-ios.js","releaseChannel":"default"}
Modifying NSBundle configuration at /tmp/turtle/7afaabb9-1c2f-4335-a935-a825c1034c89/archive/Release/ExpoKitApp.xcarchive/Products/Applications/ExpoKitApp.app...
Using shell config: { isShell: true,
manifestUrl: 'https://exp.host:443/@arjitdhavaleey/iInsights',
releaseChannel: 'default' }
Configuring iOS Launch Screen...
2018-01-30 04:36:24.472 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.489 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.540 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.541 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.541 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.541 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.542 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.543 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.546 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.546 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.546 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.547 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.547 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
2018-01-30 04:36:24.547 ibtoold[33902:975760] WARNING: Unhandled destination metrics: (null)
Compiling resources...
Using manifest: {"android":{"package":"host.exp.exponent","publishBundlePath":"../android/app/src/main/assets/kernel.android.bundle"},"description":"","extra":{"amplitudeApiKey":"081e5ec53f869b440b225d5e40ec73f9"},"icon":"https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png","iconUrl":"https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png","ios":{"bundleIdentifier":"host.exp.exponent","publishBundlePath":"../ios/Exponent/Supporting/kernel.ios.bundle","supportsTablet":true},"isKernel":true,"kernel":{"androidManifestPath":"../android/app/src/main/assets/kernel-manifest.json","iosManifestPath":"../ios/Exponent/Supporting/kernel-manifest.json"},"loading":{"hideExponentText":false,"icon":"https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png","iconUrl":"https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png"},"name":"exponent-home","notification":{"color":"#000000","icon":"https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon-blue-circle.png","iconUrl":"https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon-blue-circle.png"},"orientation":"portrait","packagerOpts":{"config":"./_universe/rn-cli.config.js"},"primaryColor":"#cccccc","privacy":"unlisted","scheme":"exp","sdkVersion":"25.0.0","slug":"home","version":"25.0.0","id":"@exponent/home","revisionId":"25.0.0-r.3ygrzLgjpL","publishedTime":"2018-01-16T23:47:17.627Z","bundleUrl":"https://d1wp6m56sqw74a.cloudfront.net/%40exponent%2Fhome%2F25.0.0%2Fc1a154450d896116f345f81d67126ac8-25.0.0-ios.js","releaseChannel":"default"}
Cleaning up iOS...
[04:36:30] Finished 'ios-shell-app' after 7.98 s
done running shell app builder
Assuming that client will run creating app on dev center ruby code
done creating app on dev center
building and signing IPA
Executing command: security cms -D -i /tmp/turtle/7afaabb9-1c2f-4335-a935-a825c1034c89/provisioning-7afaabb9-1c2f-4335-a935-a825c1034c89/7afaabb9-1c2f-4335-a935-a825c1034c89.mobileprovision
done retrieving provisioning profile
Checking if teamID is present in keychain and that certificate is valid...
decoding p12 certificate
verifying certificate is installed
Executing command: security find-identity -v -s (XXXXXXXXXX)
confirmed team ID is present in keychain
Chose export method: enterprise
writing export-options.plist file...
building IPA
Executing command: fastlane gym -n 7afaabb9-1c2f-4335-a935-a825c1034c89-unsigned.ipa --workspace /usr/local/turtle-agent/shellAppWorkspaces/ios/default/ExpoKitApp.xcworkspace --scheme ExpoKitApp --archive_path /tmp/turtle/7afaabb9-1c2f-4335-a935-a825c1034c89/7afaabb9-1c2f-4335-a935-a825c1034c89.xcarchive --skip_build_archive true -i 61CF284AD9D87E00139A8F42AAD59B37C69A689C --export_options /tmp/turtle/7afaabb9-1c2f-4335-a935-a825c1034c89/provisioning-7afaabb9-1c2f-4335-a935-a825c1034c89/export-options.plist --export_method enterprise --export_xcargs OTHER_CODE_SIGN_FLAGS="--keychain /tmp/turtle-agent/2075e5f0-05ba-11e8-80e3-0050568e4b9e.keychain" -o /tmp/turtle/7afaabb9-1c2f-4335-a935-a825c1034c89/7afaabb9-1c2f-4335-a935-a825c1034c89-build --verbose
**Unable to generate IPA.
unable to build and sign IPA**

I tried performing exactly same steps to create certificates and provisioning profile but rather than using In House distribution, used another team account for deployment to App Store and that build works fine. 

Need to deploy this to ASAP and need assistance. Can you please look at build id and provide further information on why it can't generate ipa file?

Thank you.

**Comment by jimmylee** [comment]
Assigning this to @terribleben to verify if this is an issue & update if necessary.

**Comment by terribleben** [comment]
Hey there, adding @fxfactorial who wrote the codesigning part of this. The only time I've seen "unable to build and sign IPA" in the past is when there is an issue or inconsistency with the provided cert/profile, so the underlying codesigning command fails. But Edgar can maybe provide more suggestions.

**Comment by fxfactorial** [comment]
Hi, looks like the front end of build:iOS worked correctly and this is a turtle builder issue

**Comment by Arjit-Dhavale** [comment]
Hello @terribleben 
We suspected that there might be issue with cert/profile but we are using exact same process to create the cert and profile for enterprise distribution as we used for app store.
In the expo build logs we are noticing that when 
Chose export method: enterprise   (e.g. build id 58a6d704-6a6d-420a-879f-b624fde1a922)
then we get unable to build and sign IP
but when
Chose export method: app-store  (e.g. build id 9308b46a-ed2b-49bd-9099-4953c1ec92b2)
then it works without any issue

We also tried to let expo handle certificates but it ends up creating app store distribution certificate and profile where as we want enterprise (in house) deployment.

I am new to Expo so any help and guidance on how to resolve this is appreciated. 

Thank you.

**Comment by fxfactorial** [comment]
@Arjit-Dhavale Currently, exp will only create app store distribution certs. If you want us to build enterprise builds, then you should upload the enterprise dist cert, push cert and provisioning instead of letting exp create certs for you. 

Future version of exp could let you make enterprise things as an option. I assume if you picked enterprise, then you'd want exp to make the three files all as enterprise?

**Comment by Arjit-Dhavale** [comment]
Hello @fxfactorial 
Thank you for the note. We have also tried generating enterprise dist cert, push cert and provisioning profile instead of letting exp create the certs. When we provide these certificates we can see that exp is using 
Chose export method: **enterprise** (e.g. build id 58a6d704-6a6d-420a-879f-b624fde1a922)
but the build fails.

We also generated app store certificates using the same method (to validate our cert creation process) and provided that instead of letting exp create app store certs. We noticed that exp is using
Chose export method: **app-store** (e.g. build id 9308b46a-ed2b-49bd-9099-4953c1ec92b2)
and build is success and we have our ipa file for same.

So, we are assuming that the certificate generation process is fine but exp is having some issues to build and sign ipa file when distribution certificates are provided. Can this be verified?

Thank you.

**Comment by fxfactorial** [comment]
The actual building that you see in the logs isn’t done by exp but by another program, aka the lines about export.

I added ability of exp to now generate enterprise based files for you. Can you upgrade exp, do a build:ios -c, and make certs again but pick yes for when it asks you if it is an enterprise account.

**Comment by Arjit-Dhavale** [comment]
Hello @terribleben and @fxfactorial 
We are now able to generate ipa file using enterprise store distribution certificate. Thank you a ton for all help and support.
We can close this issue now!!!

**Comment by nbatwara** [comment]
I am getting the exact same issue as @Arjit-Dhavale even though I'm using the `--apple-enterprise-account` flag. To create the provision profile I chose 'In House' Distribution but the standalone build fails at exactly this: 

ExpoKitApp.xcworkspace --scheme ExpoKitApp --archive_path /tmp/turtle/01963796-679a-4a6e-b5af-8069a8f4d244/01963796-679a-4a6e-b5af-8069a8f4d244.xcarchive --skip_build_archive true -i 5009F46315F3F6175ABE0A60DDBC1A2AAA4D68DE --export_options /tmp/turtle/01963796-679a-4a6e-b5af-8069a8f4d244/provisioning-01963796-679a-4a6e-b5af-8069a8f4d244/export-options.plist --export_method enterprise --export_xcargs OTHER_CODE_SIGN_FLAGS="--keychain /tmp/turtle-agent/b54de441-2c48-11e8-af06-0050568eed5c.keychain" -o /tmp/turtle/01963796-679a-4a6e-b5af-8069a8f4d244/01963796-679a-4a6e-b5af-8069a8f4d244-build --verbose
**Unable to generate IPA.
unable to build and sign IPA**

Any fix? Suggestions?

**Comment by zhaozhiming** [comment]
Hi, I have the same problem.   
I upload my p12 and mobileprovision files and use the `exp build:ios -e` command to build but failed. Please help. @fxfactorial @terribleben   
And I have my private key in my keychain for a distribution cert that I was using. @nbatwara   
Thanks.

```
? Which Team ID to use? 1) XXXXXXX "XXXXXXX" (In-House)
23:48:09 [exp]
WARNING! In this mode, we won't be able to make sure your certificates,
or provisioning profile are valid. Please double check that you're
uploading valid files for your app otherwise you may encounter strange errors!

Make sure you've created your app ID on the developer portal, that your app ID
is in app.json as `bundleIdentifier`, and that the provisioning profile you
upload matches that team ID and app ID.

23:48:09 [exp] Please provide your distribution certificate P12:
? Path to P12 file: /XXXXXXXX/Certificates.p12
? P12 password: [hidden]
23:49:10 [exp] Please provide the path to your push notification cert P12
? Path to P12 file: /XXXXXX/push_Certificates.p12
? P12 password: [hidden]
23:49:32 [exp] Please provide the path to your .mobile provisioning profile
? Path to your .mobile provisioning Profile /XXXXXX/laudion2018.mobileprovision
......
building and signing IPA
Executing command: security cms -D -i /private/tmp/turtle/862ca21b-a0cc-40c0-a847-de9eb85d1d4b/provisioning/862ca21b-a0cc-40c0-a847-de9eb85d1d4b.mobileprovision
done retrieving provisioning profile
Checking if teamID is present in keychain and that certificate is valid...
decoding p12 certificate
verifying certificate is installed
Executing command: security find-identity -v -s (XXXXXXXXXX)
confirmed team ID is present in keychain
Chose export method: enterprise
writing export-options.plist file...
building IPA
Executing command: fastlane gym -n unsigned.ipa --workspace /usr/local/turtle-agent/shellAppWorkspaces/ios/default/ExpoKitApp.xcworkspace --scheme ExpoKitApp --archive_path /private/tmp/turtle/862ca21b-a0cc-40c0-a847-de9eb85d1d4b/archive.xcarchive --skip_build_archive true -i 9DCD06C4DAF37FAF7D62DBAD9F86EAB17B49CDCB --export_options /private/tmp/turtle/862ca21b-a0cc-40c0-a847-de9eb85d1d4b/provisioning/export-options.plist --export_method enterprise --export_xcargs OTHER_CODE_SIGN_FLAGS="--keychain /private/tmp/turtle-agent/37fecee6-3cd7-11e8-8a97-0050568eb402.keychain" -o /private/tmp/turtle/862ca21b-a0cc-40c0-a847-de9eb85d1d4b/build --verbose
Unable to generate IPA.
unable to build and sign IPA
```
