### ISSUE TITLE
Can't sign in to two different dev clients at the same time on Android 9

### ISSUE THREAD

**Issue by wodin** [expo/expo#13643]
### Summary

I built and installed Android dev clients for two different apps. I logged into the first, successfully, but when I tried logging into the second, the redirect back to the dev client at the end of the login process prompted to choose between both dev clients. When I chose the correct one, I was still not logged in. I have not tested this on iOS.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

```
  "dependencies": {
    "expo": "~42.0.1",
    "expo-dev-client": "^0.4.4",
    "expo-file-system": "~11.1.3",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-progress": "^5.0.0",
    "react-native-svg": "12.1.1",
    "react-native-tesseract-ocr": "^2.0.3",
    "react-native-web": "~0.13.12"
  },
```

### Environment

```
  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.4.2 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.18.1 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

I am testing out EAS Build and Development Clients on my Galaxy S8.

I created [one project](https://github.com/wodin/expo-zip-example), built the dev client with `eas build` and installed it on my phone. I ran it and signed in and was able to load the experience.

I then created [another project](https://github.com/wodin/expo-ocr-example), built the dev client with `eas build` and installed it on my phone alongside the first. I ran it and tried to sign in, but was unable to.

After I clicked on the sign in button it opened the login page in the web browser. I entered my username and password. It asked for an OTP, which I entered. It verified the OTP, but when it tried to redirect back to the dev client something went wrong:

Instead of just redirecting to the second dev client it prompted me to choose between the two dev clients. When I chose the correct one it switched back to the dev client, but I was still not logged in.

The app name, slug, package etc. were all different in both dev clients, so I don't know why it would not be able to redirect to the correct app directly.

**Comment by esamelson** [comment]
Hey @wodin ! I'm actually unable to reproduce this myself. Here are the exact steps I'm following; could you let me know if & where they differ from how you're able to reproduce the issue?

- expo init dev-client-1 (blank)
- yarn add expo-dev-client (0.4.4)
- expo run:android, with Android device connected to computer
- Wait for app to build and load on device, then press Profile in the dev menu, Sign In to an account with OTP enabled, everything works great
- expo init dev-client-2 (blank)
- yarn add expo-dev-client
- expo run:android
- Wait for app to build and load on device (dev-client-1 also still running in background), press Profile in dev menu, Sign In to an account with OTP enabled
- Choose to redirect back to dev-client-2
- Now both dev clients are signed in

**Comment by wodin** [comment]
Hi @esamelson 

Thanks for checking.

Before trying to compile the first app with EAS Build I tried `expo run:android`, but I got build errors that I gave up on.
I actually don't even have to log in to one client to reproduce the problem. I just have to have both installed at the same time.

I re-did it all now:

```
$ expo init dev-client-1
✔ Choose a template: › blank               a minimal app as clean as an empty canvas
[...]
$ cd dev-client-1
$ expo install expo-dev-client@0.4.4
$ git commit -a -m "Install dev client"
$ eas build --profile development --platform android
✔ Linked to project @wodin/dev-client-1
✔ Your Android project is not configured to build with EAS. Set it up now? … yes

✔ Generated eas.json

📝  Android application id Learn more.
✔ What would you like your Android application id to be? … com.wodin.devclient1

✔ Can we commit these changes to git for you? › Yes
✔ Commit message: … Configure EAS Build for Android
✔ Committed changes
✔ Using remote Android credentials (Expo server)
✔ Generate a new Android Keystore? … yes
✔ Created keystore
✔ Uploaded to EAS 12s

Build details: https://expo.io/accounts/wodin/builds/43567341-0295-446b-91bd-1d3bcd0f612b

Waiting for build to complete. You can press Ctrl+C to exit.
✔ Build finished

[QR code]

🤖 Open this link on your Android devices (or scan the QR code) to install the app:
https://expo.io/accounts/wodin/builds/43567341-0295-446b-91bd-1d3bcd0f612b
```

Download dev client 1 APK onto Samsung Galaxy S8
Btw, it would be useful if the APK included the slug name instead of only a UUID.
Rename APK to dev-client-1.apk
Install APK

```
$ expo init dev-client-2
✔ Choose a template: › blank               a minimal app as clean as an empty canvas
[...]
$ cd dev-client-2
$ expo install expo-dev-client@0.4.4
$ git commit -a -m "Install dev client"
$ eas build --profile development --platform android
[...]
✔ What would you like your Android application id to be? … com.wodin.devclient2
[...]
Build details: https://expo.io/accounts/wodin/builds/07448216-6527-47e5-9210-a6b1fcb61ef1

Waiting for build to complete. You can press Ctrl+C to exit.
✔ Build finished

[QR code]

🤖 Open this link on your Android devices (or scan the QR code) to install the app:
https://expo.io/accounts/wodin/builds/07448216-6527-47e5-9210-a6b1fcb61ef1
```

Download dev client 2 APK onto Samsung Galaxy S8
Rename APK to dev-client-2.apk
Install APK

Open dev-client-1
Acknowledge welcome message
Press "Profile"
Press "Sign in to your account"
Browser opens to "Log in to Expo" page.
Log in and enter OTP
After OTP verifies, I am prompted to choose between the two dev clients:

![Screenshot of "Open with" choice](https://user-images.githubusercontent.com/4579020/125906330-fdd5fe5b-7713-485f-80c2-833d115e0688.jpg)

I choose dev-client-1 and am taken back to the Profile section of dev-client-1 which still shows the "Sign in to your account" and "Sign up for Expo" buttons.

**Comment by esamelson** [comment]
Hmmm, I'm still unable to reproduce (I'm using a Google Pixel 2). I wonder if this issue is specific to Samsung devices.  Have you seen this on any other devices, by chance?

**Comment by wodin** [comment]
I only have this device to test on, unfortunately.
What is the redirect url? Would the scheme for both clients be the same?

**Comment by wodin** [comment]
Workaround:

When asked to choose a dev client, choose it ans press the "Always" button. You will not yet be logged in. But if you repeat the login it will work.
After that you can go into the App info for the app and clear the Set as default option. Then you can repeat the process for any other dev clients.

**Comment by esamelson** [comment]
Ah, I'm glad you mentioned Android 9 -- that was the missing piece here. I was able to reproduce this behavior on an Android 9 emulator (confirmed it seems to be fixed by Android 10 and 11). Thank you for the report and the workaround!

**Comment by esamelson** [comment]
this is still a known issue we're tracking internally, so going to remove the stale label, though we have no timeline for a fix right now

**Comment by wodin** [comment]
I have just tested again and it is still a problem.

**Comment by wodin** [comment]
It's still a problem

**Comment by wodin** [comment]
Pretty sure it's still a problem

**Comment by wodin** [comment]
I no longer have easy access to the Galaxy S8, but I tried this again in an emulator.
The behaviour is a bit different these days, or maybe because of differences between the emulator and the phone, but the result is basically the same. If I have two different dev clients installed at the same time, I cannot login to them, unless I tell Android that I *always* want to use one of them.
