### ISSUE TITLE
Expo-auth-session for Google with server-side flow

### ISSUE THREAD

**Issue by PiotrNap** [expo/expo#13642]
I wanted to ask if it's possible to use expo-auth-session for Google and send the **code** to my backend server to exchange it for **access token**. Currently I'm receiving **invalid_grant** error from Google APIs, but when I tweak the expo-auth-session code to not use the **code challange** I'm able to exchange it for user **access token.**

Since I cannot set any params to my redirect URI, my server doesn't know about **code verifier**. So I guess that's a reason why I'm receiving this error (?)

### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by EvanBacon** [comment]
There used to be a guide for this in [guides/authentication](https://github.com/expo/expo/blob/b4a91758c77d9f23ed75ffd7a3f03811e5cb86ae/docs/pages/guides/authentication.md). You can use that as a reference for getting everything setup. Could you maybe share a repro so I can understand what was misconfigured.

**Comment by devpgcs** [comment]
@PiotrNap Did you find a solution for this? I'm facing the same issue 😞

**Comment by PiotrNap** [comment]
@devpgcs hi, i've moved away from Expo and I'm using Google Node.js Api on my backend. I'm creating an auth url with it and sending it to frontend to open a browser. There should be examples on internet that you can look up. Hope this helps you
