### ISSUE TITLE
[bare-expo] can't launch on iOS

### ISSUE THREAD

**Issue by mnightingale** [expo/expo#13656]
### Summary

On master branch launching the bare-expo app with `yarn ios` like https://github.com/expo/expo/blob/master/CONTRIBUTING.md#-download-and-setup says  to results in:

>[Fri Jul 16 2021 13:24:00.526]  ERROR    Error: expo-linking needs access to the expo-constants manifest (app.json or app.config.js) to determine what URI scheme to use. Setup the manifest and rebuild: https://github.com/expo/expo/blob/master/packages/expo-constants/README.md

It appears to be broken with https://github.com/expo/expo/commit/a7ac343f276ed7ec4c89b23ae6428999f3d864d4

I'm not sure how to fix it but switching to the commit before the above it runs successfully.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/opt/node@14/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/mnightingale/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 29, 30
        Build Tools: 22.0.1, 23.0.2, 23.0.3, 24.0.1, 24.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-22 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0-alpha.0 => 42.0.0-alpha.0
      react-native: 0.63.2 => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```
npm run setup:native
cd apps/bare-expo
yarn ios
```

**Comment by dbarkman** [comment]
Hi, we're seeing the same thing, does your app build successfully in Xcode?
`yarn ios` isn't working but building and running from Xcode works fine.

**Comment by Kudo** [comment]
hi there!
thanks for reporting this issue.
this should be fixed via https://github.com/expo/expo/commit/1440c9b7b4693f7c242699c9945efc3dc5f9c0f9.
please let us know if still encounter the problem from the latest code.

**Comment by dani-mp** [comment]
I'm still experiencing this issue in the latest master (after the _fix_ were merged). I asked about this in the forums: https://forums.expo.dev/t/constants-manifest-is-null-because-the-embedded-app-config-could-not-be-read/55014.

As I mention there, I don't currently have a workaround because even though I can build the expo-bare app via Xcode directly, once the JavaScript loads, the app throws the error about not having access to `expo-constants`.

**Comment by terenceodonoghue** [comment]
Gave `expo-constants@next` a try on a clean Expo project, but getting the same error as described the author. Also tried `expo upgrade` and (per post-upgrade instructions) `pod install` but no joy.

**Comment by aminsaedi** [comment]
I still get this error
```
ERROR    Error: expo-linking needs access to the expo-constants manifest (app.json or app.config.js) to determine what URI scheme to use. Setup the manifest and rebuild: https://github.com/expo/expo/blob/master/packages/expo-constants/README.md
```

**Comment by Kudo** [comment]
hi there! we may need more information to troubleshoot. please help to provide these if that works for you.
- managed workflow or bare workflow
- expo-constants version, getting it from `yarn why expo-constants`
- is the error happening in release build or only in debug build?

**Comment by aminsaedi** [comment]
I also tried updating `expo-constants` using `npm i expo-constants@11.1.0` and then rebuild using `expo build:ios` but the app crash when I install .app file on a simulator

**Comment by Nice-zrd** [comment]
I am currently using "expo constants": "^ 11.0.1". The problem still exists. Do you have any solutions?

**Comment by aminsaedi** [comment]
In my case it was beacause of a white space at the end of my expo user name. it was "aminsaedi " I just created a new account and the problem fixed.

**Comment by Seanmclem** [comment]
Randomly experiencing this issue after launching my app again after a few days

**Comment by erenkulaksiz** [comment]
Hello, so I encountered this issue and wanted to comment my solution. I use app.config.ts as config file and i put my scheme with process.env.EXPO_APP_SCHEME, you need to remove process.env and manually write your project's scheme. Wasted around 4 hours.
