### ISSUE TITLE
expo-screen-orientation Xcode 13 "Multiple methods named 'orientation' found with mismatched result, parameter type or attributes"

### ISSUE THREAD

**Issue by 0x7fs** [expo/expo#13668]
### Summary

When trying to build build expo-screen-orientation under Xcode 13, there is an error in `handleDeviceOrientationChange:` when accessing `orientation` on `[notification.object orientation]` where multiple `orientation` options exist since `object`'s type is `id`.

<img width="988" alt="Screen Shot 2021-07-17 at 4 23 21 PM" src="https://user-images.githubusercontent.com/2429786/126048562-f076e532-bf44-4b7c-a754-72192b1201c9.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.7.0 - /usr/local/bin/node
      npm: 7.4.3 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/mick/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.0/13A5192j - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.74
      expo: ^40.0.1 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4.4.3 => 4.4.3
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Add `expo-screen-orientation` to a blank, bare project and attempt to build it using Xcode 13.

**Comment by felipevyg** [comment]
Upgrading to 3.3.0 fixed for me.
