### ISSUE TITLE
launchImageLibraryAsync in expo-image-picker does not fire after app goes to the background in Android

### ISSUE THREAD

**Issue by asalha** [expo/expo#13665]
### Summary

If I use ImagePicker once, then send the standalone app to the background by clicking the back button on Android until the app is closed, then open the app again, ImagePicker does not work. On debugging in a standalone app, I found that launchImageLibraryAsync did not fire.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

In Expo client, everything works as expected because the scenario below does not apply, please try the scenario below in a standalone app. I did not try in on iOS because I am on Windows.

Reproduction steps in a standalone app:
1. Open app
2. Click on button to pick image
3. Select image
4. Crop it
5. I get the image as expected

Then click the back button in Android multiple times until you get out of the app.
Repeat the steps above:
1. Open app
2. Click on button to pick image
3. Select image
4. BOOM... The picker is closed WITHOUT asking to crop the image and does not get any image because launchImageLibraryAsync did NOT fire.

If I kill the app and try again, everything works as expected.

**Comment by asalha** [comment]
I have updated to version 10.2.3 and the issue is still there!

**Comment by tisalmin** [comment]
Still happens with 11.0.x version(s) and it doesn't really matter if allowEditing is true or false - the launch camera/ image picker functions are not returning to my code. Anyone else seeing this still?
