### ISSUE TITLE
copy , paste not working on IOS simulator expo go app

### ISSUE THREAD

**Issue by vishnuc** [expo/expo#13661]
### Summary

Hi , I was not able to copy / paste inside my react native projects TextInput. , I use 12.5.1 IOS simulator

But I was able to copy paste text using command+x and command+v in other ios simulator default apps like messages.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.2 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

I thought some bug in my react native project and I even upgraded SDK of expo to 42 , still same issue.

Later I found that copy paste is not working in Expo Go app in first place.where I click + on to right and in the input where it asks to enter project url..

Command+x and then command + V does not do anything
selecting text and then clicking cut and then paste does nothing.

**Comment by brentvatne** [comment]
https://user-images.githubusercontent.com/90494/125998047-908f3ab4-4816-4b6a-ad21-7bead8e8a3e9.mov

seems that there may be a problem with your simulator. you could double check that this option is set
<img width="594" alt="Screen Shot 2021-07-16 at 12 17 49 PM" src="https://user-images.githubusercontent.com/90494/125998117-d781026a-0def-430b-8733-ee39c7e8ab1b.png">

**Comment by vishnuc** [comment]
HI , I am using apple m1 chip and IOS simulator 12.5.1 , can you confirm your version please.

Also I am not able to paste in expo go app only ,,  I am able to paste on other apps in ios simulator

**Comment by brentvatne** [comment]
hi @vishnuc - this could be a bug with m1. i was using ios 14.5 on my simulator with xcode 12.5.1

**Comment by vishnuc** [comment]
Ok will this be fixed in future ? because it was not working only inside EXPO Go App.

**Comment by brentvatne** [comment]
possibly! it seems like a bug with the m1 simulator itself though, maybe apple will fix that

**Comment by vishnuc** [comment]
if bug in m1 simulator itself , copy paste should not working in their default apps like messages , reminder app right !!

**Comment by brentvatne** [comment]
@vishnuc - you would think so! but some bugs behave in different ways. i can tell you that on a non-m1 mac copy and paste works as expected in the simulator. there have been a number of weird quirks with m1

**Comment by vishnuc** [comment]
Let me try to change to Rosetta and check.

**Comment by brentvatne** [comment]
here's a related issue encountered by flutter users: https://github.com/flutter/flutter/issues/74970#issuecomment-858170914

**Comment by imhazige** [comment]
I am not using a m1 Mac, the problem is
Works with ios 16
NOT work on ios15.5

**Comment by CarlsonYuan** [comment]
Not work on iOS 15.0 simulator
M1 Pro

**Comment by urkin-dev** [comment]
Can't paste on iOS 15.4, iOS 14.0 simulators but it works fine on iOS 16.4
