### ISSUE TITLE
Firebase with offline-persistence: Importing from 'firebase/firestore' imports the memory-only build instead of the normal build in React Native

### ISSUE THREAD

**Issue by a-zen** [expo/expo#13670]
### Summary

Firebase before 8.2.7 has a bug, where the path to the memory-only build is wrong. After upgrading to Expo 41 / 42, when using firebase with offline-persistence (expo-firestore-offline-persistence) upon start the app produces the error:

`Importing from 'firebase/firestore' imports the memory-only build instead of the normal build in React Native`

because Expo 41 / 42 sets the version of firebase to 8.2.3:

`"firebase": "8.2.3"`.

The fix is to use a at least version 8.2.7 of firebase:

`"firebase": "~8.2.7"`.

Be aware that the fix currently produces an error:

````
Some dependencies are incompatible with the installed expo package version:
 - firebase - expected version: 8.2.3 - actual version installed: 8.2.10
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
````

For more information please see

https://firebase.google.com/support/release-notes/js#version_827_-_february_11_2021
https://github.com/firebase/firebase-js-sdk/issues/5156

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41,42

### Environment

  Expo CLI 4.8.1 environment info:
    System:
      OS: Linux 5.10 Arch Linux
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.5.0 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 7.17.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 19, 28, 29
        Build Tools: 24.0.2, 26.0.2, 27.0.3, 28.0.3, 29.0.2
        System Images: android-19 | ARM EABI v7a, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

See https://github.com/firebase/firebase-js-sdk/issues/5156 for a code example.

**Comment by rcb4t2** [comment]
+1 to the OP. Also for mods, when considering bumping the Expo firebase version, Firebase JS version 8.4.1 supports the storage emulator, which is very helpful. Between there and the current version 8.8.1 there are mostly bug fixes across the lib, which would be nice to have in

Please consider bumping the Expo version to the current 8.8.1 or at least to 8.4.1 (8.4.0 has a regression)

**Comment by IjzerenHein** [comment]
Hi! I've created a PR that updates the firebase-js-sdk to `8.10.0`. This should land in Expo SDK 43, but you can already override the version in `package.json` by setting it manually.

**Comment by rcb4t2** [comment]
@IjzerenHein ya know, when we comment on an issue for a huge software project, we expect we'll never be heard and that it'll never be fixed. It warms our little hearts to see a swift fix to this! Thank you for your hard work!
