### ISSUE TITLE
App crash with Expo Client 2.21.5 and 2.21.4 for android with expo-pixi.

### ISSUE THREAD

**Issue by viveksc1994** [expo/expo#13672]
### Summary

- For Android, **Issue in expo client - 2.21.4 and 2.21.5**. So, Workaround is downgrade expo client 2.19.6 - https://d1ahtucjixef4r.cloudfront.net/Exponent-2.19.6.apk
- For iOS, working fine with the latest version - https://dpq5q02fu5f55.cloudfront.net/Exponent-2.21.3.tar.gz
- - Standalone apk is working fine with expo-pixi
- linked issue - https://github.com/expo/expo-pixi/issues/187

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40, 41, 42

### Environment

expo-gl: ~9.2.0 and  expo-pixi: ^1.2.0 (checked with expo  40, 41, 42)

### Reproducible demo or steps to reproduce from a blank project

reproducable snack at https://snack.expo.io/@viveksc1994/signature-pad-crash
reproducible gitcode at https://github.com/viveksc1994/sinaturepad-crash

try to write/signature in screen with expo client 2.21.5 android app and it will give an error.
try with expo client 2.19.6 and it is working. 
 
Warning: 
```
[Unhandled promise rejection: TypeError: this.nativeVaoExtension.createVertexArrayOES is not a function. (In 'this.nativeVaoExtension.createVertexArrayOES()', 'this.nativeVaoExtension.createVertexArrayOES' is undefined)]

Stack trace:
  node_modules\pixi-gl-core\src\VertexArrayObject.js:27:4 in VertexArrayObject
  node_modules\pixi.js\lib\core\renderers\webgl\utils\Quad.js:80:53 in Quad
  node_modules\pixi.js\lib\core\renderers\webgl\managers\FilterManager.js:96:8 in FilterManager
  node_modules\pixi.js\lib\core\renderers\webgl\WebGLRenderer.js:306:51 in _initContext
  http://192.168.1.3:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:316181:24 in WebGLRenderer
  node_modules\pixi.js\lib\core\autoDetectRenderer.js:62:30 in autoDetectRenderer
  http://192.168.1.3:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:334761:65 in _callee$
```

Error:
```
TypeError: undefined is not an object (evaluating '_this.renderer._update')

Stack trace:
  node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
```

**Comment by wkozyra95** [comment]
It seems that pixi is trying to use webgl extensions that we do not support. I'll look into that more, for now you can use below workaround

```js
class Workaround extends ExpoPixi.Signature {
  constructor(props, context) {
    super(props, context)
    oldOnContextCreate = this.onContextCreate;
    this.onContextCreate = (gl) => {
      gl.getExtension = () => null;
      gl.getSupportedExtensions = () => [];
      oldOnContextCreate(gl);
    }
  }
}
```

**Comment by leoflood** [comment]
did anyone fix this?

**Comment by kirtikapadiya** [comment]
App crash with Expo SDK 44.0.6 for android with expo-pixi 2.0.0.
Reproducible git code at https://github.com/kirtikapadiya/expo-pixi-signature-crash.

**Comment by wkozyra95** [comment]
@kirtikapadiya it should be fixed in the next expo-pixi release. In a meantime you can workaround it by adding
`delete global.WebGLRenderingContext` after pixi import. (best place to add that is your entry point after all imports)

**Comment by kirtikapadiya** [comment]
@wkozyra95 `delete global.WebGLRenderingContext `  after pixi import not working on RealMi, Redmi note 10 with android version 11.

**Comment by wkozyra95** [comment]
are you saying that it does not work on those devices, but it works on the others, or it does not work on anything you tried?

if it does not work on all devices:
- your example project had mismatched dependencies, I ran `expo doctor --fix-dependencies` to fix it
- can you update that example repo with how you added that `delete` stement?

if it does not work only on specific devices create a separate issue, with with description of the issue and logs from `adb`

**Comment by kirtikapadiya** [comment]
@wkozyra95  new issue created https://github.com/expo/expo/issues/16512

**Comment by kirtikapadiya** [comment]
@wkozyra95  App crash on specific device with expo-pixi:2.0.0 and expo 44.
New issue created https://github.com/expo/expo/issues/16512 and also add device adb log file.
