### ISSUE TITLE
Safe area not respected on the bottom area for Android

### ISSUE THREAD

**Issue by trajano** [expo/expo#13686]
### Summary

The safe area on iOS renders the bottom tab navigation correctly in that it spreads all the way to the bottom, but on Android, it gets cut off.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40, 42

### Environment

Android

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@trajano/bottom-tab-navigation

**Comment by trajano** [comment]
On emulator
![image](https://user-images.githubusercontent.com/110627/126201588-ad7b8f23-cc93-4844-9f3b-64a2cd326ef7.png)

**Comment by brentvatne** [comment]
post this to react-navigation or react-native-safe-area-context if you believe it's a bug :)

**Comment by trajano** [comment]
https://github.com/react-navigation/react-navigation/issues/9749

Notes changing the app theme, but there's no setting I can find in https://docs.expo.io/versions/latest/config/app/

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/config/app/#androidnavigationbar

**Comment by trajano** [comment]
@brentvatne right which one am I supposed to use to enable it though?  None of them sound like what I need.

**Comment by KeitelDOG** [comment]
Not an Expo issue though, but I have a problem like this, when I use a Comment Input in absolute position at the very bottom (0), 1/3 of it is hidden under the bottom bar of Android with the bottom 3 keys, back, home and menu. SaveAreaView is an ancestor. If I use bottom 10 or 20 for example, it goes up and it's ok, but then it goes to high on a device with no bottom bar.

I wonder how can I detect that the screen have that bottom bar, and which height it is to apply an offset. Cause SaveAreaView is not working with the bottom.
