### ISSUE TITLE
expo-clipboard triggers "Invariant Violation: Native module cannot be null"

### ISSUE THREAD

**Issue by gglucass** [expo/expo#13688]
### Summary

Not sure why, but the latest version of expo-clipboard triggered an "Invariant Violation: Native module cannot be null" error on iOS. Downgrading expo-clipboard to 1.0.2 resolved the issue. That fixes it for me on the short term, but might be something for someone to look into?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.8 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.2.0 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.13.0 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

No time for this now, but happy to do this tomorrow upon request :-)

**Comment by brentvatne** [comment]
a reproducible example would be useful here :) thanks
