### ISSUE TITLE
[expo-image-picker] getPendingResultAsync always returns empty array

### ISSUE THREAD

**Issue by ivopr** [expo/expo#13687]
### Summary

Everything seems fine, `launchCameraAsync` and `launchMediaLibraryAsync` end with success, image is loaded correctly, but when `Don't keep activities` is activated (or when device is low on RAM) the main activity is disposed of, then you select an image, the app restart and the function prints me an empty array.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\ivopr_olrewqi\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ~42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

[check here](https://github.com/ivopr/eip-gpra), just `yarn` and `yarn android` with the emulator (or device) with `Don't keep activities` on.

**Comment by ivopr** [comment]
As it seems, in a emulator with android 11, when `allowsEditing` is enabled it does nothing too. And yes, i've followed the [installation instructions for a bare project](https://github.com/expo/expo/tree/master/packages/expo-image-picker). As soon as I click on an image or click the 'ok' checkmark on camera, the activity just ends. Gonna test in Android 9. But my hopes aren't realy that high for this to work, since my physical device is running 9 and the getPendingResultAsync also returned an empty array there.

**Comment by m-ret** [comment]
I am having exactly this issue. With Android 11, latest EXPO SDK (42).

My code:
```js
const pickImage = async () => {
    (async () => {
      if (Platform.OS !== "web") {
        const {
          status,
        } = await ImagePicker.requestMediaLibraryPermissionsAsync();
        if (status !== "granted") {
          alert("Sorry, we need camera roll permissions to make this work!");
        }
      }
    })();

    await ImagePicker.getPendingResultAsync();

    const prepareResult = await ImagePicker.launchImageLibraryAsync({
      quality: 0.1,
      capture: false,
      aspect: [4, 3],
      allowsEditing: false,
      allowsMultipleSelection: false,
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
    });

    const androidResult = await ImagePicker.getPendingResultAsync();

    const result = androidResult?.length ? androidResult[0] : prepareResult;

    if (!result.cancelled) {
      const localUri = result.uri;
      const filename = localUri.split("/").pop();
      const match = filename ? /\.(\w+)$/.exec(filename) : "";
      const type = match ? `image/${match[1]}` : `image`;
      const formData = new FormData();
      formData.append("file", { uri: localUri, name: filename, type });

      fetch(`${API}/uploadAvatar`, {
        method: "POST",
        headers: {
          Authorization: bearer,
          "X-Requested-With": "XMLHttpRequest",
          "Content-Type": "application/json",
        },
        body: formData,
      })
        .then((response) => response.json())
        .then((json) => setImage(json.file))
        .catch((err) => Alert.alert("There was an error uploading your profile picture."));
    }
  };
```
It allows me to select an image from the gallery, but as soon as the gallery is closed, it goes straight to the `.catch` method on the fetch. I've been with this issue for a week already. 

I am using the `getPendingResultAsync` function https://docs.expo.dev/versions/latest/sdk/imagepicker/#imagepickergetpendingresultasync which has a note

>Note: Make sure that you handle MainActivity destruction on Android. See ImagePicker.getPendingResultAsync.

So, what is the problem about?

**Comment by stdavis** [comment]
This looks like a duplicate of #11103 to me.

**Comment by thariqwarsa** [comment]
maybe this thread can help [https://github.com/expo/expo/issues/19509](https://github.com/expo/expo/issues/19509)
