### ISSUE TITLE
Android Build Fails, Execution failed for task ':app:exponentPrebuildStep' (fixed by increasing inotify limit)

### ISSUE THREAD

**Issue by lulzimfazlija** [expo/expo#1369]
I am facing an error when building my detached application with the following error:
Error:Execution failed for task ':app:exponentPrebuildStep'.Process 'command './.expo-source/android/detach-scripts/prepare-detached-build.sh'' finished with non-zero exit value 1

I am running a Linux OS, Ubuntu 16.04.

**Comment by jesseruder** [comment]
Hi @lulzimfazlija! Can you try running that command on it's own? Just run `./prepare-detached-build.sh` from the that directory. That should give a better error message.

Also what SDK version are you on?

**Comment by nickyhajal** [comment]
I am having this same issue and receive the following error when I run prepare-detached-build.sh alone:

```
[exp] Error: Can't find package.json
[exp] Cannot read property 'sdkVersion' of null
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.
```

**Comment by fxfactorial** [comment]
From what directory did you run `prepare-detached-build.sh`?

**Comment by nickyhajal** [comment]
The directory is: 

`/my/project/directory/.expo-source/android/detached-scripts/prepare-detached-build.sh`

**Comment by fxfactorial** [comment]
What directory were you in when you ran the script?

**Comment by nickyhajal** [comment]
I was in: 

`/my/project/directory/.expo-source/android/detached-scripts/`

**Comment by fxfactorial** [comment]
Can you try it while you are in `/my/project/directory`

**Comment by nickyhajal** [comment]
Yep - that works, and I'm now able to Gradle Sync in Android Studio 👍 

Thanks!

**Comment by nickyhajal** [comment]
Perhaps not appropriate to post in this thread (but not sure if it's related), but when I build I now get the error: 

`Error:(13, 25) error: cannot find symbol class ExponentActivity`

<img width="550" alt="mainactivity_java_-_android_-____dropbox_work_jetto_mobile_android_" src="https://user-images.githubusercontent.com/1079625/35762455-96e09310-085c-11e8-86f1-d912edb21554.png">

**Comment by lulzimfazlija** [comment]
for me this has fixed: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by ide** [comment]
I'm going to close this out because the original issue has been resolved by increasing the inotify limit. This is an issue related to Watchman more than it is related to Expo or React Native, and the way to increase this limit depends on your OS. This thread may have more details: https://github.com/facebook/watchman/issues/163.
