### ISSUE TITLE
Can't run application after cleaning node_modules: Unable to resolve module ./LocalAssets 

### ISSUE THREAD

**Issue by max-frai** [expo/expo#13706]
### Summary

```
Failed building JavaScript bundle.
Unable to resolve module ./LocalAssets from /Users/max/.../node_modules/expo-asset/build/Asset.js: 

None of these files exist:
  * node_modules/expo-asset/build/LocalAssets(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * node_modules/expo-asset/build/LocalAssets/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
> 1 | import { Platform } from '@unimodules/core';
  2 | import { getAssetByID } from './AssetRegistry';
  3 | import * as AssetSources from './AssetSources';
  4 | import * as AssetUris from './AssetUris';
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.14.0 - /usr/local/bin/node
      npm: 7.16.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.3 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I removed node_modules from project folder and after `npm i` and clean install I can't run it on ios because of problem: `Unable to resolve module ./LocalAssets`

**Comment by djpeacher** [comment]
Same here. I just reset my `node_modules` and ran into the same error. Looks like [expo-asset](https://www.npmjs.com/package/expo-asset) was updated to 3 hours ago to `8.3.3`.

I added `"expo-asset": "8.3.2"` to my `package.json` as a quick fix until the package is fixed.

**Comment by brentvatne** [comment]
clear your metro cache: `expo start -c`

you can tell from the error trace that it is pointing to a line of code that doesn't correspond with the message, indicating a likely cache issue:

```
None of these files exist:
  * node_modules/expo-asset/build/LocalAssets(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * node_modules/expo-asset/build/LocalAssets/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
> 1 | import { Platform } from '@unimodules/core';
```

notice that the above import has nothing to do with `LocalAssets`

**Comment by djpeacher** [comment]
Learned something new! Thanks @brentvatne, that fixed it for me!
