### ISSUE TITLE
Cannot use AuthSession proxy because the project ID is not defined.

### ISSUE THREAD

**Issue by NiketanG** [expo/expo#13714]
### Summary

I am trying to use Expo App Auth in a Bare Workflow. I've succesfully installed unimodules and the following packages:
`expo-constants`, `expo-linking`, `expo-auth-session`.

For the login process, I am using [`supabase`](https://supabase.io/). Given below is the code. 

```
import * as AuthSession from "expo-auth-session";

const redirectUri = AuthSession.makeRedirectUri({
	native: "com.myapp://",
    useProxy:false
});

const authUrl = `htttps://supabaseproject.supabase.co/auth/v1/authorize?provider="google"&redirect_to=${redirectUri}`;

const signIn = async () => {
	const authRes = await AuthSession.startAsync({
		authUrl,
		returnUrl: redirectUri,
	});
};
```

However, this results in an unhandled promise rejection with the error
```
Error: Cannot use AuthSession proxy because the project ID is not defined. Please ensure you have the latest version of expo-constants installed and rebuild your native app. You can verify that originalFullName is defined by running `expo config --type public` and inspecting the output.
```

I ran `expo config --type public` and it successfully emits the originalFullName and currentName. I also tried setting it explicitly in `app.json` and `app.config.js`.
Even after rebuilds, the issue persists.

I tried to check if originalFullName exists in the Constants.manifest and it doesnt; 
The manifest is null in bare workflow.
```
import * as Constants from "expo-constants";

console.log(Constants.default.null)
```

So I set it explicitly before calling AuthSession like this
```
if (Constants.default.manifest === null) {
	Constants.default.manifest = {};
	Constants.default.manifest.currentFullName = "@nikketan/myapp";
	Constants.default.manifest.originalFullName = "@nikketan/myapp";
}
```

But this too doesnt work and the error persists. 

Is there anything I am missing ?

Thanks

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: Linux 5.12 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
      Shell: 3.3.1 - /usr/bin/fish
    Binaries:
      Node: 15.11.0 - /usr/bin/node
      Yarn: 1.22.4 - ~/.npm-global/bin/yarn
      npm: 7.20.0 - ~/.npm-global/bin/npm
      Watchman: 20210425.225316.0 - /usr/local/bin/watchman
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.64.2 => 0.64.2 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- Create a bare workflow using Create React Native app,
- App Expo Unimodules, configure. 
- Add Expo constants, app auth , expo-random and web browser.

- Use the code given above in a login page to login.

**Comment by ArjunBhushan** [comment]
+1

**Comment by 10000multiplier** [comment]
Experiencing the same error in managed workflow.

**Comment by iamshadmirza** [comment]
+1

**Comment by fnky** [comment]
I found a solution, but I'm not sure why this is related. However, we were using EAS Update as generated by the `eas update:configure` command as outlined in [this documentation](https://docs.expo.dev/eas-update/migrate-to-eas-update/).

We added the fields that looked something like this:

```json
{
  "updates": {
    "url": "<URL TO UPDATE ENDPOINT>"
  },
  "runtimeVersion": {
    "policy": "sdkVersion"
  }
}
```

Here's the kicker. After this change, the renderer would error with the error outlined in this issue. Adding the fields from `expo config --type public` fixed this error, but caused another issue:

When prompting for the auth, directing to `auth.expo.io/...` the endpoint would fail with the following error:

```
ValidationError: "returnUrl" must be a valid uri
```

Undoing the above changes, removing `runtimeVersion` and falling back to the default `updates` config fixed the issue:

```
"updates": {
  "fallbackToCacheTimeout": 0
},
```

[This section may be a clue](https://docs.expo.dev/build/updates/#previewing-updates-in-development-builds), but still not sure why it would not just get the manifest correctly.

I don't know if this is a feature or a bug, but the error messages and documentation isn't clear on what may not work when using EAS Update.

**Comment by veeramarni** [comment]
Above comment didn't work. Did anyone find a solution for this issue?

**Comment by bendoerr** [comment]
> Did anyone find a solution for this issue?

Never found a solution. Gave up trying to use the proxy.

**Comment by iamshadmirza** [comment]
I added this at the top where I'm using `AuthSession` and it's working for me.

```
if (Constants.manifest)
  Constants.manifest.originalFullName = '@account/project_name;
```

**Comment by iliastsergoulas** [comment]
> I added this at the top where I'm using `AuthSession` and it's working for me.
> 
> ```
> if (Constants.manifest)
>   Constants.manifest.originalFullName = '@account/project_name;
> ```

I tried this but no success. Does anyone else have a suggestion?

**Comment by otaviogaiao** [comment]
I'm having the same problem in managed workflow. Tried @iamshadmirza workaround, but it didn't work.

**Comment by byanes** [comment]
Having the same issue in a managed workflow, it was working before I started using EAS. This is really affecting our developing process since without the proxy testing oAuth workflows locally becomes a nightmare. Any ideas of how to fix this?

**Comment by wschurman** [comment]
The PR (https://github.com/expo/expo/pull/17327) adds an argument to the function so that you can specify `originalFullName` without the hack.

Overall, we suggest using the non-proxied set of auth tools this library provides in combination with a development client build, but for now we'll continue to support EAS update manifests in combination with the library with this new argument. Sorry for the thrash.

I'll close this issue once a new version of the library is released.

**Comment by wschurman** [comment]
This has been released in expo-auth-session 3.6.1. https://github.com/expo/expo/commit/98e9664e2c37baa2b71a8bc3c43f8f9e24a391c3

The new argument is `projectNameForProxy` https://docs.expo.dev/versions/latest/sdk/auth-session/#authsessionoptions

It may be supplied with `@<account_name>/<project_name>` as the value to continue using the auth proxy with EAS update manifests.

Sorry for the breakage!

**Comment by byanes** [comment]
Thank you for taking to the time to look into this! I gave this a try and the old error regarding the project id is gone, but now I get:

```
ValidationError: "returnUrl" must be a valid uri
```

This was also refrenced in one of the [comments above](https://github.com/expo/expo/issues/13714#issuecomment-1010914665). Should I open a new issue for this?

**Comment by wschurman** [comment]
> Thank you for taking to the time to look into this! I gave this a try and the old error regarding the project id is gone, but now I get:
> 
> ```
> ValidationError: "returnUrl" must be a valid uri
> ```
> 
> This was also refrenced in one of the [comments above](https://github.com/expo/expo/issues/13714#issuecomment-1010914665). Should I open a new issue for this?

Yep, that's probably best.

**Comment by Nikita-Chernenko** [comment]
> The PR (#17327) adds an argument to the function so that you can specify `originalFullName` without the hack.
> 
> Overall, we suggest using the non-proxied set of auth tools this library provides in combination with a development client build, but for now we'll continue to support EAS update manifests in combination with the library with this new argument. Sorry for the thrash.
> 
> I'll close this issue once a new version of the library is released.

Hi, thank you for adding the parameters, now it works!

May you describe the solution without the prox + development client a little bit more? I want to migrate but not sure how to do it exactly
