### ISSUE TITLE
The _array type is missing  please add it to  SqlLite.types.ts [docs] 

### ISSUE THREAD

**Issue by castilloroberto** [expo/expo#13723]
### Summary

![image](https://user-images.githubusercontent.com/68355475/126508435-4e604c80-fdb5-4b86-a236-feb8d7d5c4ba.png)

types
![image](https://user-images.githubusercontent.com/68355475/126508538-43a70032-d315-42d8-92b0-9593993a87c7.png)

I'm trying to add it, but it does not appers on my autocomplete
![image](https://user-images.githubusercontent.com/68355475/126508790-6e44e219-8d63-4111-be02-9b079fe84627.png)

**Comment by Simek** [comment]
This issue has been fixed in:
* #13826
