### ISSUE TITLE
exp build always fails for simulator type

### ISSUE THREAD

**Issue by onrige** [expo/expo#1372]
### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.7.0
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/onrige-9f270a6c-07aa-4a07-927e-b5a0c3d2e5b0.tar.gz

### Steps to Reproduce

1. run `exp build:ios --type simulator`
2. see `failed` in build log

### Expected Behavior

There is should be no errors

### Actual Behavior

There is an error

### Reproducible Demo

Check this [build](https://expo.io/builds/61fbb6b3-d84d-4717-9d65-e318420aec2f) for example

**Comment by anp** [comment]
Hi! So sorry about this. We discovered that a recent change had made assumptions about app names being in ASCII. We have a proposed fix and will be testing and deploying it early next week!

**Comment by anp** [comment]
If others find this issue, it should only affect simulator builds of apps with 100% non-ASCII names.

If you find yourself with this issue, you can work around it temporarily by using some ASCII characters in your app name.
