### ISSUE TITLE
App crashes when leaving screen using @stripe/stripe-react-native

### ISSUE THREAD

**Issue by Brotakuu** [expo/expo#13732]
### Summary

**Describe the bug**
The app will crash when you leave the screen with `<CardField />` and the user did not input anything.

**To Reproduce**

Reproducible on the [demo snack](https://snack.expo.dev/@charliecruzan/stripe-react-native-example?platform=mydevice)

Go to setup future payments screen with `<CardField />`
Try to leave the screen without entering anything in.

Here is a [video of the error on the demo snack](https://streamable.com/9jyz4h)

**Expected behavior**
Should be able to leave the screen even if nothing is entered

**Screenshots**
Here is a [video of the error on the demo snack](https://streamable.com/9jyz4h)

**Additional context**
I noticed, that if the user enters any input, they can go back with out any issues.

Since this was marked as usable for production, we pushed this build to production already. Is there a quick fix that we can deploy?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

 - OS Version: 13.4.1 
 - Model: iPhone SE
 - Expo SDK: 42
- Expo type: Managed
- Stripe Version: "@stripe/stripe-react-native": "0.1.4",

### Reproducible demo or steps to reproduce from a blank project

Here is a [video of the error on the demo snack](https://streamable.com/9jyz4h)

**Comment by cruzach** [comment]
closing in favor of https://github.com/stripe/stripe-react-native/issues/449

**Comment by Brotakuu** [comment]
@cruzach 

This issue is fixed in [https://github.com/stripe/stripe-react-native/pull/436](https://github.com/stripe/stripe-react-native/pull/436) stripe-react-native **0.2.0** 

Is it possible to get it upgraded for Expo 43? Or at least upgrade to stripe-react-native **0.1.5** which fixes this issue https://github.com/stripe/stripe-react-native/pull/337 ?
