### ISSUE TITLE
Recent issues with push notifications

### ISSUE THREAD

**Issue by itslittlejohn** [expo/expo#1373]
### Environment
Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/itslittlejohn-9acc4240-3ee4-42b5-b55f-f9593ce5d49a.tar.gz

### Steps to Reproduce

1. Create new navigation template project with XDE
2. Add `register.js` -> https://github.com/itslittlejohn/push-test/blob/master/register.js
3. import and call within `App.componentWillMount` (this works)
4. successfully debug app locally on device
5. verify that device push notification is stored in server/database (all good)
6. trigger lambda function (using `exponent-server-sdk-node`) to send notifications to all subscribers (reports back `[ [ { status: 'ok' } ] ]`)
7. never receive push notification on device

### Expected Behavior

I expected to receive a push notification on my physical device at some point.

### Actual Behavior

I never receive a push notification. I understand that delivery is not guaranteed right away, but I have not received a single token after debugging this issue for a few days and getting OK responses from the expo server. So I don't believe the problem is with my code, but there may be something else going on, I'm just not sure how to approach it at this point. I have tested this with my Nexus 6P and other Android models I have in the house. So I do not believe it is a specific issue with my device, since no phones receive notifications. 

### Reproducible Demo

This app is a published working example of what I did.
https://exp.host/@itslittlejohn/push-test

Code repository is [here](https://github.com/itslittlejohn/push-test).

It's tricky to test since I'm not including the public test URL of my AWS endpoint for subscribing in `register.js`. But if someone wants to try to reproduce this, they can open the published version of this app (identical otherwise) and I can verify that the subscription was created (and trigger a push). I could then paste the log output of the push receipts here. 

The most recent push token that I've registered for my Nexus is `ExponentPushToken[oj4iK4CRA7Ry8gDCrtawef]`.

**EDIT**

I just added https://github.com/itslittlejohn/push-test/blob/master/test-push.js

which is basically an exact copy of what I have in my push lambda function. Testing it locally gives me the same OK response, but no actual token is received.

**Comment by ide** [comment]
It sounds like you’re testing only with Android. Have you tried setting the priority flag to high?

**Comment by itslittlejohn** [comment]
Actually, no, I hadn't tried that. Though I just tried adding that to my script and it didn't do anything for me. 
```js
expo
  .sendPushNotificationAsync({
    to: 'ExponentPushToken[oj4iK4CRA7Ry8gDCrtawef]',
    title: 'Some Title',
    priority: 'high',
  })
  .then(console.log)
  .catch(console.error)
```
=> `{ status: 'ok' }`

**Comment by itslittlejohn** [comment]
@ide Just got a test notification from you, I believe. 
![image](https://user-images.githubusercontent.com/2136925/35754611-05099560-0832-11e8-8c40-decd7eb517ec.png)

**Comment by ide** [comment]
@itslittlejohn Yeah, that was from me. I just used a test HTTP client to send you a notification:

```
https://exp.host/--/api/v2/push/send
Content-Type: application/json

{
  "to": "<your token>",
  "title": "Hi @itslittlejohn, this is James from Expo",
  "body": "Just sending you a test notification.",
  "priority": "high"
}
```

**Comment by itslittlejohn** [comment]
So I'm able to get it working with this:
```
curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '{
  "to": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]",
  "title":"hello",
  "body": "world"
}'
```
...but still not with the node script. I'll focus there and report back what I find.

**Comment by ide** [comment]
Could it have to do with the title and body fields? We know that you’re getting back status: ok which means you’re able to connect to the Expo servers and Expo is able to forward the notification. We also know your phone can receive notifications with cURL, for example. So it seems like the issue is with the payload that your lambda endpoint is sending to the Expo servers.

**Comment by itslittlejohn** [comment]
Very interesting. A good lesson in debugging I suppose.

```js
expo
  .sendPushNotificationAsync({
    to: 'ExponentPushToken[oj4iK4CRA7Ry8gDCrtawef]',
    title: 'Some Title',
    // body: '',
  })
  .then(console.log)
  .catch(console.error)
```
Uncommenting the `body` line causes it to work. Otherwise it the notification never arrives, though the response is the same. 

Logically, this also fails for me:
```
curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '{
  "to": "ExponentPushToken[oj4iK4CRA7Ry8gDCrtawef]",
  "title":"hello"
}'
```

Thoughts on this? I double checked the documentation and `body` is marked as optional.. though I'm fairly sure I wasn't including that field before this stopped working, so maybe something  changed on your servers? Seems like it's a required field now.

**Comment by itslittlejohn** [comment]
Marking this as closed now since I have a workaround, but still I'm curious what happened!
