### ISSUE TITLE
Problems with compiling ejected ExpoKit app with the Firebase/Firestore Pod.

### ISSUE THREAD

**Issue by danmatthews** [expo/expo#1374]
*Hi guys, please read the whole report before saying this is an issue for the Google/Firebase guys to sort - it may well be, but i think it might have a conflict with something in Expo/Expokit as it builds fine on a Vanilla `react-native` app*

*The point of posting this here is that i believe if there's a collision issue with ExpoKit, it may cause problems for other Pods as well as the Firebase/Firestore one specifically.

### Environment

https://exp-xde-diagnostics.s3.amazonaws.com/danmatthews-4f0370a0-ba5f-4ea1-a8a2-e2b56d626bdb.tar.gz.

### Steps to Reproduce

✅  = Yep, it does, for me at least.

1. Create a new `create-react-native-app`.
2. Verify app running with `yarn start` and Expo app for iOS.
3. Eject app to Expokit
4. Run `npm install` to set up new dependencies
5. Run `pod install` in the iOS folder.
6. Verify runs and builds in both debug and release configurations ✅ 
7. Add the firebase pods to your `Podfile` (Firebase/Core, Firebase/Auth, and Firebase/Firestore) and run `pod install`.
8 Re-open Xcode and verify that it still builds for both schemes ✅ 
9. Install react-native firebase `npm install react-native-firebase --save`
10. Link it using RN - `react-native link react-native-firebase`.
11. Attempt to build for either configuration - both fail. ❌ 

### Expected Behavior

The app would compile and run as normal.

(Write what you thought would happen.)

### Actual Behavior

Xcode spits out a bunch of "semantic issues" - you can see a screenshot of one such error below (there are either 36 errors for debug scheme, or 24 for release).

![screen shot 2018-02-02 at 15 52 09](https://user-images.githubusercontent.com/149426/35741962-0dc6011c-0831-11e8-984d-5adb668c4c85.png)

The error is marked as coming from RNFirebase - however, it has been noted here: 
https://github.com/invertase/react-native-firebase/issues/758 

That extraneous header paths might have caused problems, and using the invertase fork of `react-native-google-sign-in` seems to have solved the problem for some.

Unfortunately, i can't test removing the Expo pods to build, as that produces a build error of it's own, and using the non-expo fork of React native also causes an error as your fork calls a certain constructor not available in Vanilla RN.

I realise this might be something to do with **my machine**, so if anyone could point me in the right direction to look, i would be immensely greatful as this is stopping delivery of app builds to a client.

Please check out the demo i've put up on github below and see if you can spot my error and/or if it builds okay for you using the steps to reproduce.

### Reproducible Demo

https://github.com/danmatthews/bugbuild-rnfirebasexpo

<span style="color:green">Thank you!</span>

**Comment by terribleben** [comment]
Hey there, I've never seen this particular problem before, and I'm not aware of any unusual CocoaPods or linker configuration that Expo performs which would cause this.

It's possible that one of our (numerous) other dependencies is interacting badly with RNFirebase, maybe by defining the `gpr_types` header somewhere else. Without any other info, this is my suspicion. Right now we do depend on `GoogleSignIn`, among others. CocoaPods automatically adds various `Pods/Headers/.../Public` header search paths to all installed pods.

I notice your project's [Podfile](https://github.com/danmatthews/bugbuild-rnfirebasexpo/blob/master/ios/Podfile) doesn't seem to contain the [RNFirebase pod](https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase.podspec). Are you linking it manually (without CocoaPods)? That could lead to trouble.

**Comment by danmatthews** [comment]
Hey @terribleben - thanks for answering!

I've tried adding their pod directly (after noticing they had a podspec file in the repo), but it's not in their installation instructions, and it doesn't appear on cocoapods (https://cocoapods.org/?q=rnfirebase).

I've forked Expo and am requiring that from my project rather than , and tried removing the GoogleSignin pod, but i still get the errors, so i'll press on and try removing other dependencies later tonight.

I'm not the only one experiencing this particular problem according to the issue thread i've posted, but people seem to be able to clone and run the reproducible example i've provided without errors.

Do you have any idea what might effecting Xcode's builds system-wide? i.e. something i've installed or changed? I've tried removing `brew` libraries installed, and also a few global `npm` packages, but nothing seems to fix it. It *did* work, then just stopped and i have no idea why.

Could it be High Sierra?

Thanks for any insight you can provide,
Dan.

**Comment by terribleben** [comment]
`react-native link` should use their `podspec` [automatically](https://github.com/facebook/react-native/pull/15460), even if it's not on the cocoapods spec repo. I'm wondering whether it was skipped because they don't have the podspec in the root of their repository.

I don't know of anything in your system that would make it behave differently for you. It's possible something in your $PATH is causing your environment to work differently during xcodebuild, but I doubt it. It seems more likely a conflicting header issue to me.

I haven't had time to run your repo myself yet, will try to find time for that this week.

**Comment by EvanBacon** [comment]
Our official fix for this is to use `expo-firebase` here is an example: https://github.com/evanbacon/expo-native-firebase
