### ISSUE TITLE
Error updating permissions descriptions

### ISSUE THREAD

**Issue by joaops95** [expo/expo#13744]
### Summary

Hello, I'm trying to publish my app in the App store but I'm always receiving this message from apple:
We noticed that your app requests the user's consent to access the location, but doesn't sufficiently explain the use of the location in the purpose string.
I'm updating the app.config.js with
  
      
infoPlist:{
          CFBundleAllowMixedLocalizations: true,
          NSLocationAlwaysUsageDescription: "Turning on location services allows Power Dot to show which chargers are closest to you, reducing the distance you need to travel to charge your vehicle.",
          NSLocationAlwaysAndWhenInUseUsageDescription: "Turning on location services allows Power Dot to show which chargers are closest to you, reducing the distance you need to travel to charge your vehicle.",
          NSLocationUsageDescription: "Turning on location services allows Power Dot to show which chargers are closest to you, reducing the distance you need to travel to charge your vehicle."
        },

But it seems it's not updating in the request popup
![attachment Screenshot-0722-101624](https://user-images.githubusercontent.com/38008727/126757722-7d75ff85-3c22-4c11-902e-71a0f426c46f.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.22.2 - /usr/bin/node
      npm: 6.14.13 - /usr/bin/npm
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.3 => 4.4.4 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

infoPlist:{
          CFBundleAllowMixedLocalizations: true,
          NSLocationAlwaysUsageDescription: "Turning on location services allows Power Dot to show which chargers are closest to you, reducing the distance you need to travel to charge your vehicle.",
          NSLocationAlwaysAndWhenInUseUsageDescription: "Turning on location services allows Power Dot to show which chargers are closest to you, reducing the distance you need to travel to charge your vehicle.",
          NSLocationUsageDescription: "Turning on location services allows Power Dot to show which chargers are closest to you, reducing the distance you need to travel to charge your vehicle."
        },

**Comment by byCedric** [comment]
Hi @joaops95, thanks for writing in. Could you share the full structure of your `app.config.js`, showing exactly where `infoPlist` is located. You can strip the sensitive parts and things like the bundle/package name. It would also be helpful to know the exact command you've used after changing the `app.config.js`.

**Comment by joaops95** [comment]
Hey Cedric! Is good to hear from you!
Here's my app.config.js
`

let developmentMode = false;
let apiUrl = "";
let iosClientId = ``;
let androidClientId = `x`;
let reservedClientId = `c`;
let expoClientId = ``
const SentryDsn = "https://707a6193e3314909b4e2d370366100fe@o337311.ingest.sentry.io/5668739";

if(developmentMode){
    apiUrl = "xxx";
}

export default {
    name: "Power Dot",
    slug: "PowerDot",
    owner: "outdare",
    scheme: "powerdot",
    icon:"./assets/icon.png",
    version: "1.6",
    splash: {
      image: "./assets/emptyloading.png",
      resizeMode: "contain",
      backgroundColor: "#ffffff"
    },
    platforms: [
      "ios",
      "android"
    ],
    orientation: "portrait",
    updates: {
      fallbackToCacheTimeout: 0
    },
    assetBundlePatterns: [
       "**/*"
    ],
    notification: {
      icon: "./assets/notifications.png",
      color: "#FFF",
      androidMode: "default"
    },
    web: {
      config: {
        firebase: {
          appId: "",
          apiKey: "",
          measurementId: "G-D997"
        }
      }
    },
    ios: {
        supportsTablet: true,
        usesAppleSignIn:true,
        buildNumber: "2.0",
        googleServicesFile: "./GoogleService-Info.plist",
        bundleIdentifier: "xxxx.PowerDot",
        infoPlist:{
          CFBundleAllowMixedLocalizations: true,
          NSLocationAlwaysUsageDescription: "Power Dot is an Electric vehicle charging company, soit requires the location to let people navigate throughout the chargers, knowing their geographic position.",
          NSLocationAlwaysAndWhenInUseUsageDescription: "Power Dot requires your location so that we can centre the map on you & show you where the charger locations are",
          NSLocationUsageDescription: "Power Dot is an Electric vehicle charging company, soit requires the location to let people navigate throughout the chargers, knowing their geographic position."
        },
        config: {
          googleSignIn: {
            reservedClientId: reservedClientId,
          },
          googleMapsApiKey: ""
        },
      },
    description: "",
    // All values in extra will be passed to your app.
    extra: {
      AppleAppID: "",
      AnalyticsID:"",
      expoClientId:expoClientId,
      iosClientId:iosClientId,
      androidClientId:androidClientId,
      apiUrl:apiUrl,
      SentryDsn:SentryDsn
    },
    android: {
        package: "com.powerdot",
        versionCode: 7,
        googleServicesFile: "./google-services.json",
        permissions: ["READ_EXTERNAL_STORAGE","WRITE_EXTERNAL_STORAGE", "NOTIFICATIONS"],
        config: {
          googleMaps: {
            apiKey: ""
          },
          googleSignIn: {
            apiKey: "",
            certificateHash: ""
          },  
        }
      },
  };`

After updating I just do
`
expo:build ios --release-channel production
 `

**Comment by byCedric** [comment]
Hi @joaops95, thanks for that. It looks like everything is in order and properly set in your latest IPA build. I think you are also using `expo build:ios` instead of `expo:build ios` right?

I took a look at the info plist here:

![Screenshot 2021-07-27 at 16 42 22](https://user-images.githubusercontent.com/1203991/127174823-d6d3550b-8b6c-493d-895d-d0bbb4df80a1.png)

The only thing I can think of is that Apple isn't happy with the actual description itself. Maybe you have to be more specific in each case. You might be able to get more clarification on what needs to be done from Apple themselves. 

I'll close this issue because this doesn't seem like a bug. It's most likely related to the vague review from Apple.

Good luck!
