### ISSUE TITLE
Setting enableHermes doesn't work

### ISSUE THREAD

**Issue by hannojg** [expo/expo#13742]
### Summary

Setting the enableHermes property doesn't have any effect when setting up expo with a custom dev client. The engine stays JSC.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "^0.4.5",
"expo-updates": "~0.8.1",
"expo": "~42.0.1",

### Environment

```
  Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.1, 30.0.2, 30.0.3
        System Images: android-23 | Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
        Android NDK: 20.1.5948944
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

**Outline:**
* Create an expo dev client as described here: https://docs.expo.io/clients/getting-started/
* Run `expo run:android`, the android dir gets created
* Enable Hermes as described here: https://docs.expo.io/guides/using-hermes/
* Run the app manually with expo run:android or via android studio (not using eas)

I created a task which logs which engine is being used and it still prints JSC:
```groovy
task foo() {
    println 'ENABLE HERMES? ' + enableHermes
    println 'Engine: ' + findProperty('expo.jsEngine')
    println 'All Properties: ' + getProperties()
}
```

**Comment by Kudo** [comment]
hi there!
for bare workflow app, please make sure the settings setup like https://expo.fyi/hermes-android-config. especially to add `expo.jsEngine=hermes` in `android/gradle.properties`.

**Comment by hannojg** [comment]
ahh okay, I see, thank you! Haven't found this in the documentation. I guess this can be closed, right?

**Comment by Kudo** [comment]
going to close this. if you still encounter related issues, please let us know. thank you!
