### ISSUE TITLE
expo-camera does not record video when using quality prop

### ISSUE THREAD

**Issue by mfy5013** [expo/expo#13759]
### Summary

I was on SDK 40 and have a feature within my app that records a video using expo-camera. This is how i did it:
`            const video = await this.camera.recordAsync({
                quality: Camera.Constants.VideoQuality['720p'],
                maxDuration: CameraConstants.MAX_VIDEO_LENGTH,
                maxFileSize: CameraConstants.MAX_VIDEO_SIZE_BYTES
            })`

After upgrading to SDK 42 that same code starts recording the video but then immediately stops it. When i remove the quality argument, it works fine.

Happens in iOS on expo go app, did not test on android or binaries

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

iOS in Expo Go

### Reproducible demo or steps to reproduce from a blank project

this.camera.recordAsync({
                quality: Camera.Constants.VideoQuality['720p'],
                maxDuration: CameraConstants.MAX_VIDEO_LENGTH,
                maxFileSize: CameraConstants.MAX_VIDEO_SIZE_BYTES
            })

**Comment by samuelvisscher** [comment]
Thank you! I couldn't figure out why my camera suddenly stopped working, and when I removed the video quality it indeed started working again.
