### ISSUE TITLE
[expo-notifications] Background notification tasks not working

### ISSUE THREAD

**Issue by jcalem** [expo/expo#13767]
### Summary

I followed the [expo notification](https://docs.expo.io/versions/latest/sdk/notifications/#handling-incoming-notifications-when-the-app-is-1) here, but have not been unsuccessful getting the background notification task to be performed. I send a push notification via:
 `curl --location --request POST 'https://exp.host/--/api/v2/push/send' \
--header 'Content-Type: application/json' \
--data-raw '{
  "to": "ExponentPushToken[***************]",
  "title":"Testing",
  "body": "Testing body",
  "content-available": 1,
  "data": {
      "type": "testType"
  }
}'`
The notification is received but the background task is not performed. In the device logs I can see the background task is registered (I'm testing on an iPhone 11 on a TestFlight build):
```
Jul 25 14:28:04 ComBingedapp(UserNotifications)[35196] <Notice>: [com.bingedapp] Creating a user notification center
Jul 25 14:28:04 ComBingedapp[35196] <Notice>: EXTaskService: Restoring tasks configuration: {
    "@jcalem/Binged-app" =     {
        appUrl = "https://expo.io:443/@jcalem/Binged-app";
        tasks =         {
            "BACKGROUND-NOTIFICATION-TASK" =             {
                consumerClass = EXBackgroundRemoteNotificationConsumer;
                consumerVersion = 0;
                name = "BACKGROUND-NOTIFICATION-TASK";
                options =                 {
                };
            };
        };
    };
}
```
And the notification is displayed: 
```
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Received remote notification request 98FF-3C16 [ waking: 0, hasAlertContent: 1, hasSound: 0 hasBadge: 0 hasContentAvailable: 0 hasMutableContent: 0 pushType: Alert]
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Process delivery of push notification 98FF-3C16
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Error>: No data found at /var/mobile/Library/UserNotifications/0F01E0E1-A979-4946-BEDC-12EC59173DDD/Categories.plist
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Badge can be set for notification 98FF-3C16: 0 [ canBadge: 1 badgeNumber: (null) ]
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: Getting effectiveSectionInfo for section identifier: com.bingedapp
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Getting effective section info
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: Getting requested effective section info (sync)
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: Got effective section info [ result: 0 ]
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Got effective section info [ hasResult: 1 ]
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: Getting effectiveSectionInfo for section identifier: com.bingedapp
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Getting effective section info
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: Getting requested effective section info (sync)
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: Got effective section info [ result: 0 ]
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Got effective section info [ hasResult: 1 ]
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [Persisting notification 98FF-3C16: 1 [applicableSettings: 1]
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Saving notification 98FF-3C16: 1 [ hasAlertContent: 1, shouldPresentAlert: 1 ]
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: Saving file at /var/mobile/Library/UserNotifications/0F01E0E1-A979-4946-BEDC-12EC59173DDD/DeliveredNotifications.plist with 16 items
Jul 25 14:28:15 SpringBoard(CoreServicesInternal)[63] <Notice>: kExcludedFromBackupXattrName set on path: <private>
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Delivered user visible push notification 98FF-3C16
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Error>: No data found at /var/mobile/Library/UserNotifications/0F01E0E1-A979-4946-BEDC-12EC59173DDD/PendingNotifications.plist
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Load 0 pending notification dictionaries
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Error>: No data found at /var/mobile/Library/UserNotifications/0F01E0E1-A979-4946-BEDC-12EC59173DDD/Categories.plist
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Notice>: [com.bingedapp] Adding notification 98FF-3C16 [ hasAlertContent: 1, shouldPresentAlert: 1 hasSound: 0 shouldPlaySound: 1 ]; destinations 270: (
    NotificationCenter,
    LockScreen,
    Alert,
    Forwarding
)
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Error>: No data found at /var/mobile/Library/UserNotifications/0F01E0E1-A979-4946-BEDC-12EC59173DDD/Categories.plist
Jul 25 14:28:15 SpringBoard(UserNotificationsServer)[63] <Error>: No data found at /var/mobile/Library/UserNotifications/0F01E0E1-A979-4946-BEDC-12EC59173DDD/Categories.plist
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: BBDataProviderProxy com.bingedapp has enqueued a bulletin request
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: BBDataProviderProxy com.bingedapp is now sending enqueued bulletin request to BBServer
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: BBDataProvider: Add bulletin to destinations 270: (
    NotificationCenter,
    LockScreen,
    Alert,
    Forwarding
)
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: Publishing bulletin for section <com.bingedapp>: subsectionIDs: (null), bulletinID = <AFABFBA5-9B4C-445F-BA9F-921EF713184B>, expiration date = <Sun Aug  1 14:28:15 2021>, expiration events <0>
Jul 25 14:28:15 SpringBoard(BulletinBoard)[63] <Notice>: BBServer: Publish bulletin AFABFBA5-9B4C-445F-BA9F-921EF713184B to feeds 1067: (
    NotificationCenter,
    LockScreen,
    Banner,
    LockedBanner,
    Forwarding
)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.4.7 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 7.11.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.8.3 - /Users/jcalem/.rvm/rubies/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.7
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Add remote-notification to UIBackgroundModes:
```
"infoPlist": {
   ...
   "UIBackgroundModes": [
       "remote-notification"
   ]
}
```
2. Define background task (globally scoped)
```
const BACKGROUND_NOTIFICATION_TASK = 'BACKGROUND-NOTIFICATION-TASK';

TaskManager.defineTask(BACKGROUND_NOTIFICATION_TASK, ({ data, error, executionInfo }) => {
    // Update state
});
```
I've been able to get BackgroundFetch working with the same task body so I know this part works
3. Register the task in a top level component

```
...
useEffect(() => {
   Notifications.registerTaskAsync(BACKGROUND_NOTIFICATION_TASK);
}, [])
...
```
4. Add "content-available": 1 to push notification payload

**Comment by cruzach** [comment]
As we state in the docs:

> Under normal circumstances, the “content-available” flag should launch your app if it isn’t running and wasn’t killed by the user, however, this is ultimately decided by the OS so it might not always happen.

I've seen this myself, and what helped was to fully kill all backgrounded apps, relaunch my app, and then try sending the notification again. You should also make sure "Background App Refresh" is allowed for your application in Settings

**Comment by AlexandreMouyen** [comment]
Hello,

I did totally the same, but on iOS, I have this warning : " Error: Background remote notifications have not been configured. To enable it, add `remote-notification` to `UIBackgroundModes` in the application's Info.plist file.]".

In any case, on the documentation they say: "Handling incoming notifications when the app is not in the foreground (not supported in Expo Go)" but here: https://blog.expo.dev/expo-sdk-42-579aee2348b6 they say "SDK 42 brings support for two highly-requested expo-notifications features: handling push notifications while your app is in the background, and using custom notification sounds in your managed workflow app", where is the truth?

Thanks.

**Comment by cruzach** [comment]
> Error: Background remote notifications have not been configured. To enable it, add remote-notification to UIBackgroundModes in the application's Info.plist file.]

Did you configure this? The docs state: "In order to handle notifications while the app is backgrounded on iOS, you must add remote-notification to the ios.infoPlist.UIBackgroundModes key in your app.json, and add "content-available": 1 to your push notification payload"

Your managed workflow app is different from running your project in Expo Go, so both of those statements are true. The managed workflow supports background notification handling in **standalone** apps.

**Comment by kevinhylant** [comment]
@cruzach So if I am seeing the following error when running my app via Expo Go (managed), is this expected?  I have the proper plist key & value `UIBackgroundModes: ['remote-notification'],` and have tried both killing & reinstalling the expo go app but still see the same Error message.

> Error: Background remote notifications have not been configured. To enable it, add remote-notification to UIBackgroundModes in the application's Info.plist file.]

If backgrounded remote notification handling & async task definitions only work when running the app itself outside of Expo Go, how do you recommend debugging the async task code?

**Comment by cruzach** [comment]
The docs explicitly state "Handling incoming notifications when the app is not in the foreground **(not supported in Expo Go)**". You can test that behavior by either running `expo run:ios`, building your standalone app, or by using the `expo-dev-client` library

> when the documentation mentions including "content-available": 1 in the push notification payload, does that mean to include it in the data key as below?

If you're using APNs directly, please refer to the APNs docs for where to place keys

**Comment by kevinhylant** [comment]
@cruzach thank you for clarifying - maybe I missed that or read it & wasn't fully clear what that meant due to the double-negative. Appreciate your help!

**Comment by cruzach** [comment]
Sure thing! By the way- which double negative?

**Comment by chris-chao** [comment]
Were you able to get this working?

I am running Expo 42 on my custom `expo-dev-client`.

I have `"UIBackgroundModes": ["remote-notification"]` in the `infoPlist` field.

I have my `BACKGROUND_NOTIFICATION_TASK` defined and registered.

This is my task definition, which is defined outside of my React component: 
`TaskManager.defineTask(
  BACKGROUND_NOTIFICATION_TASK,
  ({ data, error, executionInfo }) => {
    console.log("Received a notification in the background!");
    console.log(data);
    // Do something with the notification data
  }
);`

`await TaskManager.isTaskRegisteredAsync(BACKGROUND_NOTIFICATION_TASK);` returns `true`.

`await TaskManager.getRegisteredTasksAsync();` returns 
`Array [
  Object {
    "options": Object {},
    "taskName": "BACKGROUND-NOTIFICATION-TASK",
    "taskType": "remote-notification",
  },
]`

I'm using Expo's Push API `expo-server-sdk-node`. Here is my notification obj (I've tried putting `content-available` in both the top-level field as well as `data` field):

`{
        to: receiver.pushToken,
        sound: 'default',
        title: title,
        body: notificationData.message,
        data: {
          ...notificationData.screenData,
          notificationID: notification.id,
          listID: notificationData.listID,
          message: notificationData.message,
          creatorId: notificationData.creatorId,
          type: notificationData.type,
          timestamp: Date.now(),
          'content-available': 1,
        },
        'content-available': 1,
}
`

However, my defined task does not get triggered when sending a notification while my app is backgrounded.

**Comment by cruzach** [comment]
Expo's push API does not accept the `content-available` key. You'll need to send directly through APNs. Please refer to the Push API documentation: https://docs.expo.dev/push-notifications/sending-notifications/

**Comment by AlexandreMouyen** [comment]
I use this code:

```js
registerForPushNotifications().then((t) => setPushToken(t));

// This listener is fired whenever a notification is received while the app is foregrounded
      notificationListener.current =
        Notifications.addNotificationReceivedListener(() =>
          fetchNotifications(false)
        );

      // This listener is fired whenever a user taps on or interacts with a notification (works when app is foregrounded, backgrounded, or killed)
      responseListener.current =
        Notifications.addNotificationResponseReceivedListener(
          async (response) => {
            const {
              appointment_id: aptId,
              notification_id: notifId,
              type,
            } = response?.notification?.request?.content?.data || {};

            if (type === 'NEW_APPOINTMENT') {
              await readNotification(notifId);
              await fetchNotifications(false);
              setId(aptId);
            }
          }
        );
      return () => {
        Notifications.removeNotificationSubscription(
          notificationListener.current
        );
        Notifications.removeNotificationSubscription(responseListener.current);
      };
```

And it is totally working on Expo Go, on standalone build and on EAS build.

**Comment by kevinhylant** [comment]
> Sure thing! By the way- which double negative?

Sorry for the slow response but I'm referring to "Handling incoming notifications when the app is not in the foreground (not supported in Expo Go)". << This sentence just reads weirdly to me & wasn't very clear even though I had read it before reaching out to you.

**Comment by Stevemoretz** [comment]
> The docs explicitly state "Handling incoming notifications when the app is not in the foreground **(not supported in Expo Go)**". You can test that behavior by either running `expo run:ios`, building your standalone app, or by using the `expo-dev-client` library
> 
> > when the documentation mentions including "content-available": 1 in the push notification payload, does that mean to include it in the data key as below?
> 
> If you're using APNs directly, please refer to the APNs docs for where to place keys

Are you sure?
Why this wasn't mentioned in the docs?

The docs is really unclear about how to do this and what even can happen in the background task! Can I use redux in there for example?

**Comment by humoyun** [comment]
We are also experiencing this issue right now, unfortunately could not solve them yet with only `expo-notifications`

Basically, there are 3 cases we need to handle to provide stable push notifications:
- [x] app is foregrounded -> `addNotificationReceivedListener`
- [x] app is backgrounded/closed and user taps notification -> `addNotificationResponseReceivedListener`
- [ ] app is backgrounded/closed ()
   - should be able to handle via `registerTaskAsync(BACKGROUND_NOTIFICATION_TASK)` but not working as expected in iOS (Android should work according to expo docs, but I did not test it yet)
- [?] app is killed

Our current solution for all cases so that we do not miss any notifications:
- making API call to fetch all notifications (as long as your server supports) and add them into your local storage (redux, ..) and show them in your Notifications Screen (every time)

**Comment by workheights** [comment]
Do most Expo developers reply on sending notifications directly through APNs for iOS instead of using Expo's push notification system?

I suppose I'm just surprised this isn't a bigger issue that it's currently not possible using Expo's Push API to increment the app badge count when receiving notifications.

Maybe I'm still misunderstanding? @Stevemoretz

**Comment by brentvatne** [comment]
@workheights - yes it is possible. set the badge count through the notification payload: https://docs.expo.dev/push-notifications/sending-notifications/#formats

**Comment by Abdallah-Ben** [comment]
Hello @jcalem @brentvatne  
I am having an issue with updating the state ( context API) from inside the TaskManager ( as it's defined in the global scope), first of all, is it possible to do so ? if the answer is Yes, could you please give me an example on how to implement this. Thank you.

**Comment by mudbath-andrewsymons** [comment]
> Expo's push API does not accept the `content-available` key. You'll need to send directly through APNs. Please refer to the Push API documentation: https://docs.expo.dev/push-notifications/sending-notifications/

@cruzach are you please able to confirm that this is still the case, and if possible could you please explain why Expo's push API does not accept the `content-available` key? (and will it ever accept this key?)

We are trying to update the iOS badge count with the background task following the docs, and the docs simply say _Please note: In order to handle notifications while the app is backgrounded on iOS, you must add remote-notification to the ios.infoPlist.UIBackgroundModes key in your app.json, and add "content-available": 1 to your push notification payload. Under normal circumstances, the “content-available” flag should launch your app if it isn’t running and wasn’t killed by the user, however, this is ultimately decided by the OS so it might not always happen._

The docs don't confirm that you would then have to go through APNs directly, and this is the only place I can find where `content-available` is mentioned.

If I could please have some confirmation that we would need to switch to use the native device token instead of the expo push token, and send directly to APNs, then I can communicate with the backend team and project manager that we MUST do this and allocate our resources accordingly.

Thank you 🙏

**Comment by jjanyan** [comment]
I spoke with someone at Expo and when I asked about the content-available flag, this was the response:

> Hi - the content available flag isn't part of the Expo push notification service's public interface. If you use another APNs provider you can set it though

It also sounded like it wasn't on the 2022 roadmap either. 

We've since migrated to AWS' SNS for iOS pushes

**Comment by mgscreativa** [comment]
Thanks @jjanyan ! Not a deal breaker for me as in our use case, notifications are offered at a best effort agreenment, but two things:

- The documentation need to state that limitation clearly
- Expo should add that functionality for iOS in the future

**Comment by kevinhylant** [comment]
Agreed about adding it. It feels like a pretty low lift, no? Maybe I’m missing something about the complexity given how common of a use case it is

**Comment by Stevemoretz** [comment]
> I spoke with someone at Expo and when I asked about the content-available flag, this was the response:
> 
> > Hi - the content available flag isn't part of the Expo push notification service's public interface. If you use another APNs provider you can set it though
> 
> It also sounded like it wasn't on the 2022 roadmap either.
> 
> We've since migrated to AWS' SNS for iOS pushes

That's bad news, we also migrated to FCM and surprisingly this feature was supported out of the box and without any problems, took me a day to set it up and make it running.

**Comment by mgscreativa** [comment]
Maybe we should upvote this https://expo.canny.io/feature-requests/p/background-notification-support-for-expo-notifation-service-api

**Comment by mgscreativa** [comment]
Hi @Stevemoretz ! sorry to bother, woul yo be so kind to share if there's need to use an Expo  dev build to integrate FCM for Android and iOS? Also,what's the cost of FCM service?

Thanks!

**Comment by Stevemoretz** [comment]
> Hi @Stevemoretz ! sorry to bother, woul yo be so kind to share if there's need to use an Expo dev build to integrate FCM for Android and iOS? Also,what's the cost of FCM service?
> 
> Thanks!

Hi how you doing?
If by expo dev build, you mean a custom build then yes, I used eas and built it really easy, I used the rn-firebase library and it has eas support out of the box so really easy to setup.

Regarding your second question FCM is completely free, as a matter of fact expo notification (for Android only) is using the FCM.

**Comment by seanholahan** [comment]
Does anyone know if this BACKGROUND_NOTIFICATION_TASK/content-available IOS issue has been resolved in expo 46? 

As i see it, IOS expo apps do not have a clean way to increment badge count on the client side, and the only option right now is to keep track of badge count on server side which does not seem desirable at least for me.

**Comment by ahmed-sharief5** [comment]
Hi Guys,
I found out a solution in order to use content-available: 1 flag in expo server sdk.
Just use `"_contentAvailable": true` in your payload
Example payload
`{ to: <push_token>, "_contentAvailable": true}`

Just use the above payload. For me it worked like a charm

**Comment by ckcks12** [comment]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/12825679/225808911-c7a8a452-153f-4356-8a98-af201d81b70f.png">

seems it doesn't even pass payload(request.data)..?

**Comment by dwbelliston** [comment]
> [ahmed-sharief5](/ahmed-sharief5)

Did you have a reference for where you found this? Thanks!

**Comment by dwbelliston** [comment]
For me it turned out to be an issue with the 'Do not disturb' setting on my phone haha. Sharing for another idea to troubleshoot

**Comment by ahmed-sharief5** [comment]
@dwbelliston I found out this in official documentation of firebase. Does it works for you after disabling "Do not disturb"?

**Comment by ahmed-sharief5** [comment]
@magrinj Please check your configuration in expo react native side for notification handling.

**Comment by dwbelliston** [comment]
> @dwbelliston I found out this in official documentation of firebase. Does it works for you after disabling "Do not disturb"?

Yes, my issue was that my iphone had a do not disturb mode on.. which doesnt allow any banners. So my configuration worked and I am getting notifications foreground and background. Took me way too long to figure that out haha.

**Comment by jamespb97** [comment]
> Hi Guys, I found out a solution in order to use content-available: 1 flag in expo server sdk. Just use `"_contentAvailable": true` in your payload Example payload for ios `{ to: <push_token>, "_contentAvailable": true}`
> 
> Example payload for android `{ to: <push_token>, priority: "high"}`
> 
> Just use the above payload. For me it worked like a charm

Unbelievably this is working for us. Using `BACKGROUND-NOTIFICATION-TASK` to update our badge count.
@ahmed-sharief5 how did you find this solution?

**Comment by l2aelba** [comment]
```
{
  _contentAvailable: true,
}
```

This is work, but background will run just one time only till your re-open the app.

**Comment by statico** [comment]
Confirmed, `_contentAvailable: true` works for iOS. Thank you @ahmed-sharief5

**Comment by mgscreativa** [comment]
Confirmed! At least I now hit the background task!

```
curl --location --request POST 'https://exp.host/--/api/v2/push/send' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXX' \
--data-raw '{ "to": "ExponentPushToken[***********************]", "title":"Test Background Push 🚀", "body": "Este mensaje debería llegar con la app en background", "_contentAvailable": true, "data": {"msgId":"xxxxxxxxxxxxxxxxxxxxx","link":"https://www.google.com"} }'
```

**Comment by ErionTp** [comment]
> Hi Guys, I found out a solution in order to use content-available: 1 flag in expo server sdk. Just use `"_contentAvailable": true` in your payload Example payload for ios `{ to: <push_token>, "_contentAvailable": true}`
> 
> Example payload for android `{ to: <push_token>, priority: "high"}`
> 
> Just use the above payload. For me it worked like a charm

2 days researching. I could not handle notification tap when app was in the background or killed, the below code was not triggered:

    const subscription = Notifications.addNotificationResponseReceivedListener((response: Notifications.NotificationResponse) => {
      console.log('OnTap response: ', response);
    });
    
Using the expo push notification tool https://expo.dev/notifications wont help, so in postman i added: `"_contentAvailable": true,`

the payload becomes:

    {
         "to": "ExponentPushToken[your token]",
         "_contentAvailable": true,
         "sound": "default",
         "title": "Hello from Postman!",
         "body": "This is a test notification.",
         "data": { "some_key":"some_value" },
         "priority": "high",
         "channelId": "default",
    }

only now i'm able to handle notification click.

**Comment by nathantew14** [comment]
> Hi Guys, I found out a solution in order to use content-available: 1 flag in expo server sdk. Just use `"_contentAvailable": true` in your payload Example payload for ios `{ to: <push_token>, "_contentAvailable": true}`
> 
> Example payload for android `{ to: <push_token>, priority: "high"}`
> 
> Just use the above payload. For me it worked like a charm

@ahmed-sharief5 

I am absolutely bewildered that this works, and that it is not documented.

**Comment by nathantew14** [comment]
> Hello @jcalem @brentvatne I am having an issue with updating the state ( context API) from inside the TaskManager ( as it's defined in the global scope), first of all, is it possible to do so ? if the answer is Yes, could you please give me an example on how to implement this. Thank you.

@Abdallah-Ben did you ever find a solution?

**Comment by maioradv** [comment]
On my development build tested using a pysical device the task manager works and do the callback everytime the app is not open but in background but in my production build with android the task manager callback for remote notification does nothing also with priority set to high

anyone tried task manager with remote notification callback in production?
