### ISSUE TITLE
Hermes support 

### ISSUE THREAD

**Issue by suzigit** [expo/expo#13769]
### Summary

I have a very simple app working on EXPO42. I can test it on Android by creating apks using "eas build --local --platform android". If I added Hermes following these instructions https://docs.expo.io/guides/using-hermes/ the new apk do not work anymore. The app crashes after some time.
I read that the support is experimental. If I cannot have hermes supported by expo, should I eject expo? 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

EXPO42

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.21.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://docs.expo.io/guides/using-hermes/

**Comment by cruzach** [comment]
> The app crashes after some time.

What do the crash logs point to? You haven't provided a reproducible demo so I'm going to close this for now, but can re-open it once you do provide a sample GH repo with a minimal project that reproduces the crash
