### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by Hunsu** [expo/expo#1376]
### Environment
  OS: Linux 4.13
  Node: 8.1.4
  Yarn: 1.0.1
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/hunsuexp-1c483c6f-406e-48b1-bf55-570171e5418d.tar.gz

### Steps to Reproduce

I'm using the module https://github.com/WhatAKitty/react-native-fetch-mock/i and I got the error 'Can't find variable: Symbol'. Normally Symbol works with expo according tohttps://docs.expo.io/versions/latest/guides/using-modern-javascript.html

It was fixed when I added babel-polyfill but then I got warnings:

Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Provider`, expected a single ReactElement.

### Expected Behavior
Symbol works with Expo

### Actual Behavior

![screenshot from 2018-02-02 19-46-21](https://user-images.githubusercontent.com/6278443/35749431-ccb41b5c-0851-11e8-96ac-6e9adf0897a4.png)
![screenshot from 2018-02-02 19-45-59](https://user-images.githubusercontent.com/6278443/35749432-ccd764a4-0851-11e8-94a8-9a1291efcf66.png)

### Reproducible Demo

Here is reproduction repo https://github.com/Hunsu/react-native-fetch-mock-issue-5 on commit b43934e08e98f64ad5e2b7fe3cfc85408e726ab2

After yarn install you will get the error about the Symbol.

On the last commit you will get the error about the props.

**Comment by anp** [comment]
Hi! I think the docs for JS features JSC supports may be incorrect. I don't think Symbol works on Android right now, so having it work with the polyfill is correct. I'll follow up internally and make sure we update those docs, sorry! Hopefully we'll be able to update JSC soon and support Symbol in the near future.

**Comment by Hunsu** [comment]
Ok thanks. What about the props validation errors when using the polyfill?

**Comment by anp** [comment]
I'm not sure about those. Do you think you could provide a minimal repro of the issue on [Snack](https://snack.expo.io) and open a new issue with it?

**Comment by Hunsu** [comment]
I couldn't reproduce it on Snack but you can reproduce the issue with the app I provided here.

**Comment by ide** [comment]
I could be mistaken but the bug looks specific to the components in `react-native-material-ui` rather than with Expo. I'd recommend adding console.log statements or using the remote debugger to step through prop-types and react-native-material-ui to figure out the root cause. Please tell us if it is an issue with Expo.

**Comment by Hunsu** [comment]
It also happens with other libraries and my own components. I did tried to add the console.log statements but the app crashes.
I will try to debug the issue.

**Comment by Hunsu** [comment]
I tried to debug the app but the errors disappear when debugging.

**Comment by EvanBacon** [comment]
@Hunsu did you try debugging with `exp start --no-dev --minify` that will emulate how it runs in prod

**Comment by Hunsu** [comment]
No I didn't try try that command. But if it runs like in prod, props validation errors won't show.

**Comment by Tai13492** [comment]
You should try 
npm install --save es6-symbol
Then,
import 'es6-symbol/implement'; 
At the starting point of your project (App.js/index.js).
This will solve your problem but it may lead you to another problem if you are using mobx in your project. 
The way to solve it is to downgrade your mobx version to 4.x.x (mobx version >= 5 will crash)
Hope this helps.

**Comment by Hunsu** [comment]
The other issue was caused by styled-components and was fixed a month ago.

**Comment by gyurobenjamin** [comment]
I'm on Expo 28 and still a problem.
