### ISSUE TITLE
App does not work on Expo 42

### ISSUE THREAD

**Issue by suzigit** [expo/expo#13763]
### Summary

I was using @firebase/firestore and "expo-firestore-offline-persistence" to save and read saved objects without native code. I upgraded to Expo SDK42 and now I have this exception.

FirebaseError: You are using the memory-only build of Firestore. Persistence support is only available via the @firebase/firestore bundle or the firebase-firestore.js build.

I noticed that expo-firestore-offline-persistence is a very simple lib-https://github.com/nandorojo/expo-firestore-offline-persistence/issues/19 so I think the error is not there. 

How to deal with that? I would like to avoid going to native.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

EXPO42

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.21.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

import firebase from "firebase/app";
import 'firebase/firestore';

const firebaseConfig = { ... }  // apiKey, authDomain, etc. (see above)

firebase.initializeApp(firebaseConfig);

const db = firebase.firestore();

firebase
  .firestore()
  .enablePersistence()
  .catch((err) => {
        console.log("**** ERROR ON ENABLING PERSISTENCE=", err);
  });

EXPO DOES NOT SHOW ANY SCREEN WHEN THIS CODE IS REFERENCED. If I comment firebase, the app runs.

**Comment by pehagg** [comment]
Cloud this be related to https://github.com/expo/expo/issues/13670?

**Comment by a-zen** [comment]
@pehagg yes this is the same issue as #13670 that I reported.
@suzigit upgrading to a newer firebase version should fix your issue.

**Comment by suzigit** [comment]
I tried to uninstall firebase and install the new version by using expo install firebase@8.8.1. However, I noticed that package.json still points to an old version. 
So, I first changed package.json, removed the node_modules and used npm install. It seems that it now updates correctly.
The app is working.
