### ISSUE TITLE
Chromium v92 breaks a lot of flex layout in Expo Web

### ISSUE THREAD

**Issue by AlastairTaft** [expo/expo#13768]
Upon release of Chromium v92 it broke a lot of places of our production web app.

### Chromium v91
![chromium v91 example](https://p187.p2.n0.cdn.getcloudapp.com/items/JruD0GZo/af2b76b2-bff6-47db-9ecd-81a6eff4a062.jpg?source=viewer&v=81423a34eae3400d01078f413a1945fe)

### Chromium v92
![chromium v92 example](https://p187.p2.n0.cdn.getcloudapp.com/items/Z4uKO1Ng/77852ef3-20fe-4f47-a472-7a084b4a1d7a.jpg?source=viewer&v=7a2e4781d9df528c57d879dab1e66af5)

### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by AdamJNavarro** [comment]
Hey @AlastairTaft, could you please provide a minimal reproducible example that we can clone and run? Screenshots while helpful as a visual are not useful for debugging locally.
