### ISSUE TITLE
"Failed to load" when debug Reactnative with Expo + Genymotion + Chrome.

### ISSUE THREAD

**Issue by peacemind** [expo/expo#1377]
This is the error message from Chrome console.
/////////////
Failed to load http://packager.hj-52i.peacemindlou.expo-geo-redux.exp.direct/node_modules/expo/AppEntry.delta?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=F:\GitProject\ReactNative\Geo\expo-geo-redux\node_modules\expo\tools\hashAssetFiles: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:19001' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
(index):188 Uncaught (in promise) TypeError: Failed to fetch
////////////////
I did install the "Allow-Control-Allow-Origin" for Chrome.  
I also follow the debugging instruction in Expo. turn the Expo to LAN and enable the Remote JS Debugging feature in Genymotion.

### Environment

Environment:
  OS: Windows 10
  Node: 6.10.0
  Yarn: 0.27.5
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/peacemindlou-d9775816-4397-42cd-a953-b808b50a5500.tar.gz

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by anp** [comment]
Hi! It's pretty difficult to help here without more information about what's going on here. What exactly are you trying to do when you see this error? Is it when you're first setting up the debugger?

**Comment by peacemind** [comment]
It's working now after I restart everything (Gynymotion and Expo).  Thanks.
