### ISSUE TITLE
expo-facebook not sending app events to facebook

### ISSUE THREAD

**Issue by omarst9** [expo/expo#13770]
### Summary

I am currently using the latest expo SDK 42 and expo-facebook "~11.3.1". When i try to log App events in Facebook there seems to be no events coming from the iOS devices at all but events from Android devices are showing as expected. 

This issue includes the Auto events and standard events. On further inspection, the Facebook developer console shows that the facebookSDK being used is too old and needs to be upgraded. I'm not sure if this is the cause of the issue. I've attached an image to show what Facebook is displaying in their developer console. 

![facebook-console](https://user-images.githubusercontent.com/40017704/126950361-1edbeb76-620b-4554-a16a-aae8f1bb25d3.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-S | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.3 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```
const initFacebook = async () => {
      await Facebook.initializeAsync({
        appId: facebookAppId,
      })
      try {
      const { status } = await requestTrackingPermissionsAsync();

      if (status == 'granted') {
        console.log('Tracking enabled');

          await Facebook.setAutoLogAppEventsEnabledAsync(true);
          await Facebook.setAdvertiserIDCollectionEnabledAsync(true);

        }else{
          console.log("Tracking disabled")
          await Facebook.setAutoLogAppEventsEnabledAsync(false);
         await Facebook.setAdvertiserIDCollectionEnabledAsync(false);
        }
      }catch (err) {
        throw err
      }
    }
```

**Comment by cruzach** [comment]
Is this only happening on iOS 14.5 for you? Tested on 14.4 and it's working for me

**Comment by cruzach** [comment]
Have you called [`setAdvertiserTrackingEnabledAsync`](https://docs.expo.io/versions/latest/sdk/facebook/#setadvertisertrackingenabledasyncenabled)? Otherwise, according to Facebook, "Event handling in iOS 14: will drop events if setAdvertiserTrackingEnabled is called with false in iOS 14" - [source](https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md#800)

**Comment by omarst9** [comment]
I'm running on iOS 14.6 but don't have access to devices below 14.5. 

i did miss `setAdvertiserTrackingEnabledAsync` so i've added it on top of the other 2 calls. I still don't see any events coming through to FB. I will publish my change to the app store and will monitor the events coming through to see if anything comes from iOS.

Will get back to you once that happens.

Did you add anything to your app.json other than `facebookScheme` and `facebookAppId` for it to work on 14.4?

**Comment by cruzach** [comment]
No- I tested this using our test app which can be found here: https://github.com/expo/expo/tree/master/apps/native-component-list

facebook app events-specific screen can be found here: https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/FacebookAppEventsScreen.tsx

**Comment by omarst9** [comment]
After getting the app published on the App Store i started seeing seeing events coming through from iOS devices. It most likely was because of the missing `setAdvertiserTrackingEnabledAsync`.

**Comment by jorgeruvalcaba** [comment]
> After getting the app published on the App Store i started seeing events coming through from iOS devices. It most likely was because of the missing `setAdvertiserTrackingEnabledAsync`.

Thank you, @omarst9! I finally made event tracking work 😄
