### ISSUE TITLE
await Updates.reloadAsync() does not work reliablely on IOS [VIDEO ADDED]

### ISSUE THREAD

**Issue by alimertcakar** [expo/expo#13775]
### Summary

  Updates.reloadAsync()  works 1 out of 10 times. App restarts but does not get updated.
End result is app self updates dozens of times which is very annoying.

Example repo to reproduce: 
https://github.com/alimertcakar/Expo-bug-report

I'm currently sending it to apple testflight, I will add a video when it is done.

I've been debugging since a while and it is not a problem on my end (I believe, i tried a lot)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40.0.0

### Environment

  Expo CLI 4.7.2 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\User\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: 40.0.1 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ^0.16.5 => 0.16.5
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/alimertcakar/Expo-bug-report

Needs to be on production.
UpdateControl line 69,  await Updates.reloadAsync(); does not always work.

To reproduce: 
1: Deploy it to testflight,
2: `expo publish` a new update,
3: Open the app, click "UPDATE",
4: App restarts,
5: Oh no, It is not updated! Go to the 3rd step.

Important note: Try it couple of times, sometimes it works without a problem, sometimes you have to click "Update" 10 times to restart the app. **Change more than one file**
Change text form multiple files. More files you change = more times you need to reupdate. Not kidding.

**Comment by alimertcakar** [comment]
Added video:

https://user-images.githubusercontent.com/56369392/127112348-fd18c48f-97c2-4595-9dbd-066a5191f889.mp4

Don't forget to change multiple files. Our users experience 9-10 times update check sometimes. yikes :(

**Comment by byCedric** [comment]
Hi @alimertcakar, thanks for writing in! I'm looking at your `UpdateControl.jsx` code and I noticed you aren't waiting for `Updates.fetchUpdateAsync` to complete. One thing I suspect what's going on is this:

1. `appStateVisible` is changed → _running `checkForUpdates()`_
2. `Updates.checkForUpdateAsync` returns new manifest → _setting update available state + render `ButtonOrderAll`_
3. `ButtonOrderAll` is pressed → _running `applyUpdate()`_

In this scenario, you could press the "UPDATE" button even before `Updates.fetchUpdateAsync` is completed. When this happens, it simply reloads the same bundle it previously had.

You do have the `isDownloadingNewUpdate` state value, but this is used incorrectly as it's only set right before reloading the app. This should be set right before `Updates.fetchUpdateAsync` and you should use it to set a loading indicator on your button for example. Only after the `fetchUpdateAsync` is done, you should be able to press the reload button.

Hope this helps!

**Comment by alimertcakar** [comment]
> Hi @alimertcakar, thanks for writing in! I'm looking at your `UpdateControl.jsx` code and I noticed you aren't waiting for `Updates.fetchUpdateAsync` to complete. One thing I suspect what's going on is this:
> 
> 1. `appStateVisible` is changed → _running `checkForUpdates()`_
> 2. `Updates.checkForUpdateAsync` returns new manifest → _setting update available state + render `ButtonOrderAll`_
> 3. `ButtonOrderAll` is pressed → _running `applyUpdate()`_
> 
> > Note that `Updates.checkForUpdateAsync` _does not_ download the actual update.
> 
> In this scenario, you could press the "UPDATE" button even before `Updates.fetchUpdateAsync` is completed. When this happens, it simply reloads the same bundle it previously had.
> 
> You do have the `isDownloadingNewUpdate` state value, but this is used incorrectly as it's only set right before reloading the app. This should be set right before `Updates.fetchUpdateAsync` and you should use it to set a loading indicator on your button for example. Only after the `fetchUpdateAsync` is done, you should be able to press the reload button.
> 
> Hope this helps!

This definitely was the case! I thought it was an ios related issue since it worked on all android devices perfectly. Turns out we all had fast android devices!

Thank you very much for your help, i was definitely stuck with this. It was only annoying because i had the update the production app manually for other fixes. Thank you very much again, you saved me a lot of trouble, i just couldn't see it.

**Comment by byCedric** [comment]
Haha no problem, sometimes another set of eyes can help! I'm glad we figured it out without too much effort 😄  Have fun developing the app!
