### ISSUE TITLE
White screen on app load on production apps as of today

### ISSUE THREAD

**Issue by martsie** [expo/expo#1378]
New production builds are showing up with a white screen as of today. I've rolled back my git repo to a previous build of the app and gone through steps to try and debug the issue but haven't been able to get anywhere.

I'm posting here because it may be an issue with Expo's publishing system. I'm also getting random 'Metro bundling errors' on occasion when running exp publish now (never seen those errors before). It doesn't appear to be a javascript bug as Sentry isn't reporting anything.

So just to recap: App works fine in dev mode, when publishing the app flickers and goes white. I've tried restoring to previous version on GIT which I know definitely worked and they have the same issue.

Anybody having similar issues?

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

**Comment by terribleben** [comment]
Hi,

- Are you seeing this on an iOS or Android device?
- Is this a detached (ExpoKit) project, or just a normal Expo project?
- What happens when you run locally with dev=false and minify=true?

**Comment by tankers746** [comment]
Seeing a white screen immediately after the splash screen on a standalone app built with expo build:ios.
App loads fine after the white screen, unsure if this is a new issue as I wasn't getting the splash screen until today (thanks for the fix). Not sure if the issue occurs when running locally as it loads too quickly.

**Comment by martsie** [comment]
This issue seems to have resolved itself without any real code changes on my end. It was happening on both detached exposit projects and normal projects.

Thanks for the tip about dev=false and minify=true - I will give that a go next time if I have issues with production that aren't occurring in dev.

**Comment by tankers746** [comment]
Resolved on its own without rebuilding the app.

**Comment by Elitebigboss90** [comment]
I am having similar issue, 
open app--->splash screen--->white screen(10s - 1 min)--->home screen.

it's on iOS but I haven't confirmed on Android if it have this issue too. 
I am using detached expoKit with Apploading in my app.js.

```
<AppLoading
            startAsync={this._loadResourcesAsync}
            onError={this._handleLoadingError}
            onFinish={this._handleFinishLoading}
          />

async _loadResourcesAsync(){
    const images = [
      require('./src/assets/home/img_flower_red.png'),
      require('./src/assets/home/img_flower_blue.png'),
      require('./src/assets/home/img_flower_yellow.png'),
      require('./src/assets/home/img_flower_rustyred.png'),
      require('./src/assets/home/img_empty_bottom_flower.png'),
    ];

    const cacheImages = images.map((image) => {
      return Asset.fromModule(image).downloadAsync();
    });

    return Promise.all(cacheImages)
  }

```

and I am using assetBundlePatterns to support offline bundle.
```
"assetBundlePatterns": [
      "./src/assets/*",
      "./src/assets/images/*",
      "./src/assets/element/*",
      "./src/assets/home/*",
      "./src/assets/login/*",
      "./src/assets/edit/*",
      "./src/assets/mmine/*",
      "./src/assets/subset/*",
      "./src/assets/forumEmoji/*",
      "./src/assets/novel/*",
    ],
```

this issue is happended on both Simulator( white screen last about a moment, less than 1s, but still can see it.) and real device(from iPhone 6 - iPhone X, the newer device is, the less white screen time have).

**Comment by adnanmitf09** [comment]
I got the same issue and hours of wandering around, I was able to fix this:
**Short answer:** 
Run following command in project directory via terminal.

`expo publish `

Explanation:
iOS release build use js bundle located at `os/epluribus/Supporting/shell-app.bundle`
Android release build use js bundle located at `android/app/src/main/assets/shell-app.bundle`
These bundles does not update automatically for ejected projects. So you will lead to a white screen because there is either an old bundle or not at all.

In addition to publishing the bundles online, `expo publish` command creates / modifies the following files (the bundles and configuration files describing where to find the bundles online):

```
android/app/src/main/java/host/exp/exponent/generated/AppConstants.java
android/app/src/main/assets/shell-app-manifest.json
android/app/src/main/assets/shell-app.bundle
ios/react-native-scaffold/Supporting/shell-app-manifest.json
ios/react-native-scaffold/Supporting/shell-app.bundle
```

Thus you would have the same bundle in both debug and release build.

**Comment by AlexanderBalson** [comment]
Had this issue very recently. Had cases where it would go to white screen, and others where it would get stuck on the splash. Running `expo publish` before building for iOS has seemed to have done the trick. After uninstalling and installing a new build the app through testflight, I've been able to force close the app, restart the phone, go between apps, and it all seems to be working fine now. Thanks @adnanmitf09 for that!

**Comment by shake314** [comment]
Having the same problem. Splash image appears for a few seconds and then everything turns to white.

`{
  "name": "Front",
  "displayName": "Front",
  "expo": {
    "name": "Front",
    "slug": "Front",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "assets/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "package": "com.xxx.xxx"
    }
  }
}`

Am I doing something wrong?

**Comment by dhiazfathra** [comment]
Resolved after running `npm update expo` and then rebuilding the app.

**Comment by brentvatne** [comment]
white screen could just mean that there is some fatal error when rendering your app. you could add sentry or enable prod mode in development and check it out
