### ISSUE TITLE
expo-notifications for SDK 40 does not have removeAllNotificationListeners  [docs] 

### ISSUE THREAD

**Issue by Andrea-Arguello** [expo/expo#13791]
### Summary

SDK 39 and lower expo-notification documentation and code include a ```removeAllNotificationListeners()``` function. This is no longer present in SDK 40, but the documentation does not mention this, nor does it say how to substitute this function in already existing code.

### Link to the related docs page

https://docs.expo.io/versions/v40.0.0/sdk/notifications/

**Comment by brentvatne** [comment]
hello! you can see more information around this in the changelog, and in this pr https://github.com/expo/expo/pull/10883

here is the associated changelog entry:

> - Removed `removeAllNotificationListeners` method. You can (and should) still remove listeners using `remove` method on `Subscription` objects returned by `addNotification…Listener`. ([#10883](https://github.com/expo/expo/pull/10883) by [@sjchmiela](https://github.com/sjchmiela))
