### ISSUE TITLE
app icon select/setup

### ISSUE THREAD

**Issue by fungmo** [expo/expo#13798]
### Summary

I want to make the rounded corners of the app icon a bit more rounded, can I use code to achieve it? Can you give a guide to the relevant configuration for the native android configuration?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.3

### Environment

```base
 Expo CLI 4.8.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

> This is the icon I want：
![image](https://user-images.githubusercontent.com/16655229/127174355-6bfe1d85-bd97-4a92-ac4a-64867e219620.png)

> This is the app icon I generated with android studio:
![image](https://user-images.githubusercontent.com/16655229/127175253-d0011f0f-4475-4a63-83c6-599aec9e1875.png)

**Comment by byCedric** [comment]
Hi @fungmo, I would recommend reading through the [guidelines on app icon customization from Android](https://developer.android.com/google-play/resources/icon-design-specifications). Long story short, it's not possible because Android is "reshaping" this by themselves. It differs per vendor/launchscreen and even per Android version.
