### ISSUE TITLE
Feature Request: Apple HealthKit and Google Fit

### ISSUE THREAD

**Issue by chrissm79** [expo/expo#138]
I have a project that requires reading data from Apple HealthKit and Google Fit and it's the only thing holding me back from using Expo on a project. These are rather large APIs and I understand that Expo attempts to keep similar APIs for both platforms so I'm proposing that only a subset of features be integrated into Expo.

I found the following libraries for each platform to reference:

Apple HealthKit - [react-native-apple-healthkit](https://github.com/GregWilson/react-native-apple-healthkit#inithealthkit)
Google Fit - [react-native-google-fit](https://github.com/StasDoskalenko/react-native-google-fit)

For my particular use case I just need to **read** data (no need to write). I listed features below that are supported by both libraries.

- Is Available
- Authorize/Init
- Steps
- Observe Steps
- Weight
- Distance

*Google Fit does provide access to [additional data types](https://developers.google.com/fit/android/data-types) that are not currently available in the repo*

If there's anything I can do to help I'd love to pitch in!

**Comment by terribleben** [comment]
FYI, we added many of these things as part of the [pedometer](https://docs.expo.io/versions/latest/sdk/pedometer.html) module in SDK 17.

**Comment by chrissm79** [comment]
@terribleben That's awesome!!!
