### ISSUE TITLE
EXGLViewManager errors in XCode after SDK25 update

### ISSUE THREAD

**Issue by nickyhajal** [expo/expo#1380]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.2.0
  Yarn: 0.17.10
  npm: 3.10.9
  Watchman: 4.7.0
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/nickyhajal-a088524a-8123-4dbc-a7d2-839a359beee5.tar.gz

---

Just went through all the ExpoKit update steps (as I've done a few times before) but I am getting 3 errors in `EXGLViewManager.m` (after cleaning and building):

```
<project>/ios/Pods/ExpoKit/ios/Exponent/Versioned/Modules/Api/GL/EXGLViewManager.m:82:68: Too few arguments provided to function-like macro invocation
```

```
<project>/ios/Pods/ExpoKit/ios/Exponent/Versioned/Modules/Api/GL/EXGLViewManager.m:77:38: Expected ';' after top level declarator
```

```
<project>/ios/Pods/ExpoKit/ios/Exponent/Versioned/Modules/Api/GL/EXGLViewManager.m:93:5: Missing '@end'
```

<img width="1425" alt="exglviewmanager_m_and_search_ _exglview" src="https://user-images.githubusercontent.com/1079625/35768716-2a5dffa6-08c6-11e8-87a0-cbd94826da1d.png">

Any ideas what may be happening and how I can resolve these issues?

Thank you!

**Comment by terribleben** [comment]
It looks like you're missing [this commit](https://github.com/expo/expo/commit/b425117955dbbca23b23ca1c558393e7af3ad071). Are you sure you have the latest [ExpoKit code](https://github.com/expo/expo/releases) for SDK 25 in your project's Podfile?

**Comment by nickyhajal** [comment]
Yep - you're right, so sorry about that! I changed the version but looks like the file didn't save before I reran `pod install` 😆 

Thanks so much!
