### ISSUE TITLE
Calendar.createEventAsync - entire `url` parameter is url-encoded

### ISSUE THREAD

**Issue by grossvogel** [expo/expo#13804]
### Summary

When using the `url` parameter with `Calendar.createEventAsync` (and presumably also `Calendar.updateEventAsync`), the link added to the event is not functional if it contains a protocol, port, or path.

If the event details contain `url: "https://github.com/expo"` then the calendar event's URL will be created as `https%3A%2F%2Fgithub.com%2Fexpo`, with slashes, colons, etc. URL-encoded despite being functional parts of the URL itself. The URL _looks_ correct when you view the event, but it will be inactive because of the invalid format, and editing the event reveals the encoding issue.

I'm on version `8.3.0` but it looks like [`master` is still using URLHostAllowedCharacterSet](https://github.com/expo/expo/blob/0edb5e5a76f300b55bbc29a5937b244872935b20/packages/expo-calendar/ios/EXCalendar/EXCalendar.m#L384) as of right now. (I don't really read Objective-C, but [this forum post](https://forums.expo.io/t/calendar-url-encoded/31202) identified that character set as the problem and it makes sense to me.)

<details>

<summary>screenshots</summary>

![Screen Shot 2021-07-27 at 3 45 14 PM](https://user-images.githubusercontent.com/802805/127226527-f466d37c-7db0-4dae-a7ec-f8717f32e33f.png)

![Screen Shot 2021-07-27 at 3 45 04 PM](https://user-images.githubusercontent.com/802805/127226526-036e529d-256b-4126-815a-e0c23676cb97.png)

</details>

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.1.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.17.3 - ~/.asdf/installs/nodejs/14.17.3/bin/node
      npm: 6.14.13 - ~/.asdf/installs/nodejs/14.17.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /Users/jason/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-native: 0.61.5 => 0.61.5 
      react-native-web: ^0.14.8 => 0.14.8 
      react-navigation: ^4.4.0 => 4.4.0 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```
import * as Calendar from "expo-calendar";

async function addTestEvent() {
  const defaultCalendar = await Calendar.getDefaultCalendarAsync();

  const eventDetails = {
    title: "test event",
    startDate: "2021-07-17T03:00:00.000Z",
    endDate: "2021-07-17T05:00:00.000Z",
    timeZone: "America/Chicago",
    allDay: false,
    url: "https://github.com/expo",
  };

  await Calendar.createEventAsync(defaultCalendar.id, eventDetails);
}

```

**Comment by Aryk** [comment]
I'm experiencing the same issue. It's really sad...no deep linking  back to the app :(

**Comment by Aryk** [comment]
This issue seems to have existed for at least 2 years? Any chance we can get this at least queued up?

https://forums.expo.dev/t/calendar-url-encoded/31202/2

**Comment by Aryk** [comment]
Any updates on this?

**Comment by HenrisHub** [comment]
this is still an issue on expo 52.

**Comment by daves28** [comment]
This is still an issue and it prevents us from being able to include a functioning deeplink to our app from the calendar event.

**Comment by justindavies** [comment]
Just adding my +1 to this, I came across the issue today
