### ISSUE TITLE
Constants.deviceName / Device.deviceName does not seem to update when user changes device name in settings

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#13816]
### Summary

As far as I can tell in my testing so far `Constants.deviceName` and `Device.deviceName` are set to the device name when the app first launches. If the user closes the app, changes the device name, and then relaunches the app `Constants.deviceName` will still report its initial value and not the current value the user has added.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.5.0 - /var/folders/vr/lwvvgqr9747_mfbnzq31bkt40000gn/T/yarn--1627487369356-0.25415191014312755/node
      Yarn: 1.18.0 - /var/folders/vr/lwvvgqr9747_mfbnzq31bkt40000gn/T/yarn--1627487369356-0.25415191014312755/yarn
      npm: 7.19.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.1 => 41.0.1 
      react-native: 0.63.4 => 0.63.4 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@tiltshift/01baa7

**Comment by cruzach** [comment]
We're just pulling from [`UIDevice`](https://developer.apple.com/documentation/uikit/uidevice/1620014-currentdevice?language=objc) for this one, so maybe the problem lies in there? You could make sure that's whats being run by setting a breakpoint in the xcode debugger [here](https://developer.apple.com/documentation/uikit/uidevice/1620014-currentdevice?language=objc) and investigate the properties of the currentDevice object

**Comment by ide** [comment]
If you force quit the app and re-launch, does the new name take?

**Comment by chrisdrackett** [comment]
yeah, if you force quit and re-launch it gets the correct name.

**Comment by ide** [comment]
Sounds like the issue is that the device name is populated as a constant. We probably won't fix this for expo-constants since that library is slowly on its way out but addressing this for expo-device makes sense but will require API changes that might be best to introduce after Turbomodules (2023).
