### ISSUE TITLE
getExpoPushTokenAsync does not work in a production application in google play 

### ISSUE THREAD

**Issue by georgeMorales** [expo/expo#13818]
### Summary

Please help! I have an app in production on Google play and Notifications.getExpoPushTokenAsync does not work.
The fact is that I have everything well configured, it works and I receive notifications with Expo Go and the same project also works if I generate an apk and install it on my phone, I receive the notifications and the token is generated, but the same version that I upload to Google Play no longer generates the token for me. How is that possible?
It's been several days and I can't find the solution, please help, I need to implement the notifications for my application to be successful.
The .apk file tested on my phone locally works, however the .aab file uploaded to play store does not work.
Thanks!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

SDK 42

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 4.5.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
        System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

`
async function registerForPushNotificationsAsync() {
  let token;
  if (Constants.isDevice) {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log(token);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  return token;
}
`

**Comment by cruzach** [comment]
To debug this, run `adb logcat` and then open the app and try to get the push token. It should print an error message that gives you more information on how to debug this. If it's working in Expo Go, this generally means there's a certificate issue with how you've configured FCM

**Comment by georgeMorales** [comment]
A couple of hours ago I was able to solve the problem, the fact is that in the credentials I had in API Restrictions not to restrict the key, but in Application Restrictions if I had Apps for Android and now I have set to none.
As I saw in the documentation and in the posts of people who had a similar problem, they always made reference to API Restrictions, I did not realize about Application Restrictions.
Thanks @cruzach
