### ISSUE TITLE
can't skip daily repeated notification on some day Or schedule daily notification starts from tomorrow

### ISSUE THREAD

**Issue by BiskremMuhammad** [expo/expo#13823]
### Summary

There is no way to skip a day from a daily repeated notification.. 
or another way around, start a daily repeated notification starting from tomorrow for example but not today. can't also do that!.

so what I want to achieve is:
I have to schedule a daily notification to remind the user to open the app, at "1:00 pm" for example.
so when the user opens the app before that time, he shouldn't be reminded this day. so I want to skip the previously repeating habit. or use `cancelScheduledNotificationAsync(identifier: string)` to cancel the current one, and start a new repeated one but starting from tomorrow.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.2 - /usr/local/bin/node
      npm: 7.19.1 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

**Comment by cruzach** [comment]
You can achieve the behavior you're looking for by using `WeeklyNotificationTrigger` (android) and `CalendarNotificationTrigger` (ios). You'll need to cancel the scheduled notification and reschedule a new one when/if the user opens the app
