### ISSUE TITLE
[expo-notifications] removeNotificationSubscription() doesn’t work

### ISSUE THREAD

**Issue by dennisbouwpas** [expo/expo#13828]
### Summary

I need functionality to remove/enable the Notifications listener
In case if the user decides he doesn’t want to see notifications, he can disable it in the app settings screen.

But when I try removeNotificationSubscription() function
And then send a notification with https://expo.dev/notifications
And I still can see that notification on my device.
Am I doing something wrong?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```javascript
import * as Notifications from 'expo-notifications';
import React from 'react';
import { Text, View, Button } from 'react-native';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function App() {
  const [notificationData, setNotificationData] = React.useState();
  let subscription = React.useRef().current;

  async function registerToken() {
    const expoPushToken = await Notifications.getExpoPushTokenAsync();
    console.log('expoPushToken: ', expoPushToken.data);
  }

  const subcribeToBotifications = () => {
    subscription = Notifications.addNotificationReceivedListener((notification) => {
      console.log('NOTIFICATION: ', notification);
      setNotificationData(notification);
    });
    return () => subscription.remove();
  };

  const removeNotificationSubcsription = () => {
    subscription.remove();
    Notifications.removeNotificationSubscription(subscription.remove);
    Notifications.removePushTokenSubscription(subscription.remove);
  };

  React.useEffect(() => {
    registerToken();
    subcribeToBotifications();
  }, []);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <Text> {JSON.stringify(notificationData)} </Text>
      <Button title="Remove listener" onPress={removeNotificationSubcsription} />
    </View>
  );
}

```

**Comment by byCedric** [comment]
Hi @dennisbouwpas, I don't think anything is wrong with `expo-notifications`. This issue seems to originate from your usage of `useRef`. When you change the `subscription` value, you overwrite the `useRef`'s `current` value, you are not actually changing the ref's value.

I [copied this pattern into a Snack](https://snack.expo.dev/@bycedric/expo-issue-13828), and you could see some warnings popping up. Even if it did work, it's still prone to other issues related to rerendering.

<img width="907" alt="Screenshot 2021-07-29 at 16 57 06" src="https://user-images.githubusercontent.com/1203991/127515261-5f4d424f-3860-44f9-a3d2-22a5c533eff8.png">


Hope this helps!

**Comment by byCedric** [comment]
The code you send uses the `useRef` values out of the scope of where they live. This won't work as those values don't exist in that spot. I closed this issue because it's not an issue with `expo-notifications`, it's an issue with the implementation of this in your app.

**Comment by dennisbouwpas** [comment]
@byCedric So the example in documentation is wrong?

**Comment by byCedric** [comment]
No, the example in the docs is working as expected. The code you sent is not the code we host on docs.expo.io, and have the issues I described. ESLint should help you discover these types of issues:

<img width="449" alt="Screenshot 2021-07-29 at 17 15 44" src="https://user-images.githubusercontent.com/1203991/127518523-4a90347d-339b-48dd-81b7-87e1e4c0055f.png">
