### ISSUE TITLE
app crashes on iOS and android when built

### ISSUE THREAD

**Issue by hoodweb** [expo/expo#1382]
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.4
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^23.0.4 => 23.0.6
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/kristian-22e9a8e6-9bf1-46e1-a66a-6babe5687304.tar.gz
```
### Steps to Reproduce

I am creating an app which sends some local notifications and communicates with an external API. Everything seems to work fine in expo. I've made it so some notifications happen instantly, so i can test them. Then running a test build for iOS and Android. However after showing the splash screen, both apps crash.

### Expected Behavior

To work the same as in expo.

### Actual Behavior

Crash after showing splash for a second

(Write what happened. Add screenshots!)

Here is a screen recording of my .app file running in a sim. http://recordit.co/UD1YJ2rIts
Here is a screenshot of the error screen on android
![screenshot_20180205-095355_1024](https://user-images.githubusercontent.com/17528424/35795946-32bce586-0a5b-11e8-8753-9387f318147c.png)
![screenshot_20180205-095645_1024](https://user-images.githubusercontent.com/17528424/35795957-3d6623a8-0a5b-11e8-8726-b20fe93c0c35.png)

Here is a gist of my project
https://gist.github.com/hoodweb/cb576737068e10001e4e1c600964c108

Really hope someone is able to help, thank you

**Comment by hoodweb** [comment]
It appears that changing the SDK version to `23.0.0`works?

**Comment by ide** [comment]
To explain what is going on:

The error message says that the JS in your project uses React Native (JS) 0.50.x. You always must use the corresponding native version. In this case, React Native (native) 0.50.x is included with Expo SDK 23: https://docs.expo.io/versions/latest/sdk/index.html.
