### ISSUE TITLE
Invalid signature, JAR_SIG_NO_SIGNATURES [android]

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1383]
### Environment
  OS: macOS High Sierra 10.13.3
  Node: 8.6.0
  Yarn: Not Found
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

### Steps to Reproduce

This occurred when updating an expo project with a different slug to the same build package name.

1. Change slug name in app.json
2. `exp build:android` -  it doesn't find the existing keystore, so use exp fetch:android:keystore from the app with the prior slug.
3. `exp build:android -c` - Build with the keystore I just fetched

### Expected Behavior

I can upload the newly built apk with the new slug to the app with the same package name.

### Actual Behavior
Error:
`You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR: JAR_SIG_NO_SIGNATURES: No JAR signatures`

<img width="973" alt="screen shot 2018-02-05 at 2 15 09 pm" src="https://user-images.githubusercontent.com/1566400/35823884-065ad0ba-0a7f-11e8-8935-3f0a7523cfe6.png">

I'm trying the build again, to see if it makes a difference.

**Comment by JulianKingman** [comment]
In the build log, there's a line that says:
`jarsigner error: java.lang.RuntimeException: keystore load: Keystore was tampered with, or password was incorrect`

**Comment by JulianKingman** [comment]
I'm a dunce, I misread the `fetch:keystore` output and thought the passwords were the same for keystore and key.

**Comment by verzil** [comment]
FOR ANY THAT THOUGHT THEY ARE THE SAME, look closely or diff em. because they are not the same! ;( ;( ;( and be careful how you copy that too.
