### ISSUE TITLE
[docs] Editing app.json ( Manifest ) with OTA update ( publish command )

### ISSUE THREAD

**Issue by ioness** [expo/expo#13834]
### Summary

1) Build and publish binary in both app stores.

2) Modify app.config.js scheme property

3) Create an alert window showing Constants.manifest.scheme

4) expo publish --release-channel pro-6

5) Your scheme has changed it is no longer what it was when you built the standalone.

Documentation says the scheme cannot be changed by publishing.

This is a huge deal for me because I am white labeling and expect to publish into different apps with one expo publish command ( And if scheme changes it breaks my App ) 

### Link to the related docs page

https://docs.expo.io/workflow/publishing/#limitations

**Comment by brentvatne** [comment]
the scheme built into the binary can't change over the air but the manifest does change

**Comment by ioness** [comment]
> the scheme built into the binary can't change over the air but the manifest does change

Really thanks for answering.

SHORT VERSION (No need to read more if you don't want to)
 is there any way I can identify a specific standalone that wont be altered by publish ?

LONG VERSOIN:
I need to create many standalones running the same code.

Each standalone needs its own logo, scheme and will be listed as a different App in the stores.

All have the same slug and release channel so that if I find a bug, I can patch is publishing once.

But my code needs to know which standalone is running, for example if Constants.manifest.extra.which === 'foo', show a different color palette or a different main menu ( While the rest of the app is the same ).

But if manifest gets updated when I publish, is there any way I can identify a specific standalone that wont be altered by publish?

**Comment by ioness** [comment]
I am using expo-application Application.applicationId instead ( com.foo.app ) and now everything works as intended.

Again thanks a lot for the swift response!

**Comment by sadi304** [comment]
Sorry for reopening this one. But what is the clear approach here? I mean scheme changes now works with publishing only. So does it need to be rebuilt in standalone apk for actually working? Not sure the gotcha's here. @ioness can you share some insights?

**Comment by ioness** [comment]
> Sorry for reopening this one. But what is the clear approach here? I mean scheme changes now works with publishing only. So does it need to be rebuilt in standalone apk for actually working? Not sure the gotcha's here. @ioness can you share some insights?

I am not sure what is it that you want to do but I will do my best:

When you build a standalone, what is in your app.json / app.config.json is applied to the binary WHEN you build it.

After that, whatever changes you make in your app.json will not be applied so if you change your permissions, icons, splash or whatever it will NOT APPLY.

What happens (And this thread is about that) is that when you do a OTA update, your manifest do change (But as I said, changes are not applied to the binary).

To overcome that, in my current situation I started relying on expo-application applicationId to identify whitelabel apps.

Sorry for the delay and hope my reply is useful.

**Comment by sadi304** [comment]
@ioness thanks for replying. 

yeah i got the flow but was a bit confused as changing app.json manifest and adding scheme fixes the `Linking.createURL` call which would otherwise crash if there is no scheme. But ota publishing fixes the error but probably wont work as expected because native binary is not updated with new scheme. It was a bit confusing thats why wanted to know more.

**Comment by ioness** [comment]
> @ioness thanks for replying.
> 
> yeah i got the flow but was a bit confused as changing app.json manifest and adding scheme fixes the `Linking.createURL` call which would otherwise crash if there is no scheme. But ota publishing fixes the error but probably wont work as expected because native binary is not updated with new scheme. It was a bit confusing thats why wanted to know more.

That is right, you need a new binary to modify the scheme
