### ISSUE TITLE
LocalAuthentication not recognizing FaceId In android devices

### ISSUE THREAD

**Issue by YouginaCh** [expo/expo#13833]
### Summary

I'm using the expo-local-authentication to fetch biometrics type available , regarding the  official doc , to get enrolled biometrics ( faceId / fingerPrint ) we  choose to go first with the method **LocalAuthentication.supportedAuthenticationTypesAsync();** , but actually in andoird Face ID could no be identified !!!  so any idea about this please 

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

latest   "expo-local-authentication": "^11.1.1",

### Environment

React native environment , 
react-native-unimodules successfully installed and configured.
 "react": "17.0.1"
 "react-native": "0.64.1", 

### Reproducible demo or steps to reproduce from a blank project

        const [biometricstypes, setbiometricstypes] = useState<LocalAuthentication.AuthenticationType[]>([]);
	React.useEffect(() => {
		getBiometricsTypes();
	}, []);

	const getBiometricsTypes = async () => {
		let biometricRecords = await LocalAuthentication.supportedAuthenticationTypesAsync();
		if (!biometricRecords) {
			LoggerService.log('No Biometrics Found');
		} else {
			setbiometricstypes(biometricRecords);
			LoggerService.log(biometricRecords);
		}
	};

**Comment by edwardkes** [comment]
@YouginaCh Did you what causes the problem? I also have this issue on my Galaxy S9+.

**Comment by CorinneKelly** [comment]
any updates on this issue?

**Comment by CorinneKelly** [comment]
@YouginaCh @edwardkes is your device running Android 9? It looks like Face Authentication integration is not setup on Android 9, it only supports fingerprint. Face Authentication became available on Android 10.

https://source.android.com/security/biometric

**Comment by emmanuelfrancis** [comment]
Any update on this ticket? 
I am using expo-local-authentication": "~12.0.1" and on Nokia 5.3 with Android 11.
