### ISSUE TITLE
Task registered with Notifications.registerTaskAsync() task not firing on iOS.  Custom Client 

### ISSUE THREAD

**Issue by haibert** [expo/expo#13837]
### Summary

I have installed expo-task-manager in my custom client to be able run tasks in response to notifications received in the app. On Android when a notification is sent the background test function fires while the app is in the background, but not on iOS. I have added "UIBackgroundModes": ["remote-notification"] to my infoPlist in my app.json. I am even able to confirm the task has actually registered when I console log it using the code below on iOS

```
const test = await TaskManager.getRegisteredTasksAsync()
console.log(test)
```

Not sure why the task is not running. I am successfully receiving the notifications from the expo notification tool but they are not triggering the background task on iOS.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

add expo-task-manager to project
add expo notifications to project
add the following to your app.json

```
 "ios": {
            "infoPlist": {
                "UIBackgroundModes": ["remote-notification"]
            },

```
use code bellow to a test task. and then use the expo notification tool to send a notification to your app while it is in the background. 
```
import * as Notifications from 'expo-notifications'
import * as TaskManager from 'expo-task-manager'

const BACKGROUND_NOTIFICATION_TASK = 'BACKGROUND-NOTIFICATION-TASK'

TaskManager.defineTask(
    BACKGROUND_NOTIFICATION_TASK,
    ({ data, error, executionInfo }) => {
        console.log('Received a notification in the background!')
        console.log(data)
        // Do something with the notification data
    }
)

Notifications.registerTaskAsync(BACKGROUND_NOTIFICATION_TASK)
```

**Comment by haibert** [comment]
I want to add, I read this on the apple developer documentation. Do you think it is relevant to this issue? 

**Create a Background Notification**
To send a background notification, create a remote notification with an aps dictionary that includes only the content-available key, as shown in Listing 1. You may include custom keys in the payload, but the aps dictionary must not contain any keys that would trigger user interactions.

Listing 1 Sample payload for a background notification
```
{
   "aps" : {
      "content-available" : 1
   },
   "acme1" : "bar",
   "acme2" : 42
}
```
Additionally, the notification’s POST request should contain the apns-push-type header field with a value of background, and the apns-priority field with a value of 5. The APNs server requires the apns-push-type field when sending push notifications to Apple Watch, and recommends it for all platforms. For more information, see Create and Send a POST Request to APNs.

**Comment by cruzach** [comment]
Hi, thanks for trying out the dev client and this new notifications feature. As we state in the notifications docs:

> Please note: In order to handle notifications while the app is backgrounded on iOS, you must add remote-notification to the ios.infoPlist.UIBackgroundModes key in your app.json, **and add "content-available": 1 to your push notification payload**. 

So yes, you do need to add `"content-available": 1` to your payload. For information on communicating directly with APNs, refer to [these docs](https://docs.expo.dev/push-notifications/sending-notifications-custom/)

**Comment by haibert** [comment]
> Hi, thanks for trying out the dev client and this new notifications feature. As we state in the notifications docs:
> 
> > Please note: In order to handle notifications while the app is backgrounded on iOS, you must add remote-notification to the ios.infoPlist.UIBackgroundModes key in your app.json, **and add "content-available": 1 to your push notification payload**.
> 
> So yes, you do need to add `"content-available": 1` to your payload. For information on communicating directly with APNs, refer to [these docs](https://docs.expo.dev/push-notifications/sending-notifications-custom/)

Can we do this using the expo notifications service? We are going to have the back end people implement expo notifications server side.

**Comment by cruzach** [comment]
@haibert can you send me an email at cruzan@expo.io?
