### ISSUE TITLE
Expo `.ttf` fonts don't load using SDK 42 and `expo-font@9.2.1`

### ISSUE THREAD

**Issue by hanford** [expo/expo#13839]
### Summary

Font loading doesn't seem to work with `.ttf` fonts. It used to... but trying to upgrade to the latest Expo SDK results in errors. There is more information in the reproduction repo below, code is identical to the documentation over [here](https://docs.expo.dev/versions/latest/sdk/font/#example-functions).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Mac OS 11.4
Node 14
Latest expo (42)

### Reproducible demo or steps to reproduce from a blank project

https://github.com/hanford/expo-font-bug

**Comment by hanford** [comment]
Maybe related: https://github.com/expo/expo/issues/13358

**Comment by rodneyrehm** [comment]
same for Bare Workflow: https://forums.expo.dev/t/sdk42-expo-fonts-wont-load-ttf/54884/6

**Comment by dashcraft** [comment]
I'm running into this same issue, using the new dev client build, it breaks when loading any ttf fonts through expo's asset loading mechanism.

**Comment by dashcraft** [comment]
@EvanBacon is there any way to get some visibility into these ttf loading issues? With the new dev client builds going out, it works great, but all ttf fonts break in the app on build.

**Comment by EvanBacon** [comment]
@dashcraft interesting, if this is happening in dev then it might be a metro.config.js / expo-cli issue -- in production it's probably an expo-updates update. I'm investigating it as a metro issue, and I've linked the issue to the updates team for them to check out as well.

**Comment by dashcraft** [comment]
@EvanBacon saving the day once again! Thank you!

**Comment by dlombardi** [comment]
This is still not working for me.  The Font.loadAsync() call is "hanging" and not resolving with imported .ttf fonts.  My app is not loading as a result. I'm running 9.2.1 on a managed workflow build and am using yarn and `yarn.lock`.

**Comment by mattThousand** [comment]
This is still an issue in `42.0.4` - installing `expo-fonts` with yarn has no effect in my project :/

**Comment by dashcraft** [comment]
Ummm no this is still an issue?

**Comment by dashcraft** [comment]
@EvanBacon can we disable the stale indicator until this is taken care of?
