### ISSUE TITLE
❌  ld: library not found for -lEXClipboard in new dev client

### ISSUE THREAD

**Issue by arvidnilber** [expo/expo#13846]
### Summary

expo-clipboard does not seem to work in the new dev-client workflow (SDK 42). There seems to be no plugin config available for expo-clipboard, and you can't use @react-native-community/clipboard because it doesn't have a plugin config either. Is there a workaround for this issue right now?

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

 "expo-clipboard": "~1.1.0",

### Environment

  Expo CLI 4.9.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 15.12.0 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.6.3 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-S | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.9.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

No time for this.

**Comment by cruzach** [comment]
Hi! `expo-clipboard` doesn't need a config plugin. You should be able to just `yarn add expo-clipboard`, then `npx pod-install`, then rebuild a new dev client. 

Issues without reproducible demos will likely be closed, just FYI

**Comment by arvidnilber** [comment]
Still the same error. Tried with both expo prebuild and expo run:ios, still doesn't start.

**Comment by cruzach** [comment]
Can you share a link to a GitHub repo that reproduces the issue?

**Comment by arvidnilber** [comment]
Just tried this method in a brand new expo-init project, and the app started without any issues. This can be closed. Need to debug this further. Thank you.

**Comment by brentvatne** [comment]
it sounds like maybe you were running the xcodeproj rather than xcworkspace

**Comment by arvidnilber** [comment]
No building with Xcode works. It's just `expo run:ios` that is crashing, but it did not crash when I tried to reproduce it with a fresh Expo project.

**Comment by brentvatne** [comment]
happy to investigate if you can share a reproducible example

**Comment by arvidnilber** [comment]
Yeah I can't share the source code of the app, under NDA, and I can't reproduce it. Couldn't find any version mismatches and compared a lot of common files. Building with Xcode works just fine so I don't think I'll need your help, but thanks anyways @brentvatne
