### ISSUE TITLE
Expo Facebook Login - Behavior: 'native' doesn't work

### ISSUE THREAD

**Issue by tungvi** [expo/expo#1384]
i'm currently testing out Expo Facebook login on my standalone app. It work perfectly with behavior = 'web' but does not open any window at all if I changed the behavior to 'native'

Here is the code snippet:
`
  async FacebookLogIn() {
    const { type, token } = await Expo.Facebook.logInWithReadPermissionsAsync(APP_SECRET_ID, {
        permissions: ['public_profile', 'email', 'user_friends','user_events'],
        behavior: (__DEV__)?'web':'native',
      });
    if (type === 'success') {
      alert(token);
    }
  }
`

**Comment by ide** [comment]
Sorry about this confusing behavior. In iOS 9+, the FB SDK changed so that "native" opens a web browser anyway: ttps://stackoverflow.com/a/32621036. And, tangentially related, in iOS 11+ the "system" option was removed by Apple. We'll be updating the docs to reflect these external changes.
