### ISSUE TITLE
Kaspersky Anti-Virus Reported Expo Installation as a virus/infected!

### ISSUE THREAD

**Issue by murat-kaya** [expo/expo#1385]
Dear Team,

Kasperksy reported your installation file as a virus here below details.

![expoksn](https://user-images.githubusercontent.com/9800967/35845146-14489790-0b22-11e8-84d7-bbe9f00fbe48.PNG)
File Exp​o​ ​X​D​E​.exe. is infected.
Scan result File is infected 
Detected threats UDS:DangerousObject.Multi.Generic 
File size 77.49 MB 
File type PE64/EXE 
Scan date Feb 06 2018 09:36:16 
Databases release date Feb 06 2018 05:39:37 UTC 
MD5 6ec3eef2b8d38b66dd38e7fed188afa5 
SHA1 3e66b9e4fd2b39d55493190268ab1ca122923432 
SHA256 e9ce19343797eedd9b7504598714d598d1530c499cfd788b0deb18c3bb781c6c

**Comment by jimmylee** [comment]
Hey @murat-kaya! Im glad you caught this, we've had other reports of Kasperksy reporting our installation file as a virus.

Would it be possible for you to visit https://virusdesk.kaspersky.com and report this as a false detection? That would be really helpful for us.

**Comment by murat-kaya** [comment]
Hi jimmylee, 

i've already done (reporting as false positive to kasp.) before send this post. When they replied i will inform you again.

Regards,
Murat

**Comment by murat-kaya** [comment]
Hi Jimmylee,

It is validated as clean.

Reply message from kaspersky:

Hello,

Sorry, it was a false detection. It will be fixed.
Thank you for your help.

Best regards,
Rassokhin Kirill, Malware Analyst, Kaspersky Lab

**Comment by jimmylee** [comment]
Awesome! Thank you so much @murat-kaya !

**Comment by murat-kaya** [comment]
Dear jimmyle,

Another case that i think important but related with kasperksy itself (kind of bug, and i am writing to them also)

**Problem:** 
If you install the application at a time when Kaspersky regards it as a virus, Kaspersky will not allow access even if the database is updated and looks clean. So you must close your anti-virus to work with Expo.

Although Kaspersky looks at the application as clean, it still seems to prevent access to the application somewhere (bug may be).

**Workaround**
If you change the Expo executable name with any, it will run without any problem.

Before change 
![expo1](https://user-images.githubusercontent.com/9800967/35904302-b3127ac2-0bf3-11e8-9194-7bcc240797b9.PNG)

After change
![expo2](https://user-images.githubusercontent.com/9800967/35904304-b33ab76c-0bf3-11e8-81b4-8d1da091624a.PNG)
