### ISSUE TITLE
[docs] [expo-notifications] info about notification icon on bare app without expo dep

### ISSUE THREAD

**Issue by Grohden** [expo/expo#13866]
### Summary

I'm always confused by the term `bare workflow` but I'm assuming it to be a ejected expo project

My project isn't a expo ejected one, but I've added unimodules and installed `expo-notifications` alone, I could get notifications to work fine (despite it having conflicted with `@react-native-firebase/messaging`).. but the icon setting doesn't work for me.. I'm unsure if its a doc problem or other thing.. let me see if I can explain it:

To change the icons, there's a lot of docs scattered around, but eventually you get here
https://github.com/expo/expo/tree/master/packages/expo-notifications

For icon it says:
> To setup, just add the config plugin to the plugins array of your `app.json` or `app.config.js`:
> ...
> Then rebuild the app. If you're using the bare workflow, make sure to run `expo prebuild` first (this will apply the config plugin using prebuilding).

(There's also some places that says to use `expo.notifications` instead.. I'm not sure what is correct, but I've tried both)

I've added the needed entry, but when I run `expo prebuild` it doesn't work saying:

```
Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.
```

And it's correct, I don't depend on expo and I don't want to depend on it (I don't want to downgrade RN)

So... I've took my time to debug the expo package and find where it tries to find the icon (prebuild must generate something some place else right?), and I found that the expo package uses a `meta-data` from manifest with the name
`expo.modules.notifications.default_notification_icon` and points it to a drawable...

(I was stupid on this one.. I could have read what the plugin generated instead of debugging the expo package 😞 )

So I have copied my resources to the android drawables folder and added the manifest entry:
```xml
    <meta-data
      android:name="expo.modules.notifications.default_notification_icon"
      android:resource="@drawable/notifications_icon"
      />
```

And it worked...

So my questions that fit the 'update docs' are:
* After adding unimodules am I expected to depend on expo?
  * If not, how I'm supposed to be using the expo prebuid to generate the notification manifest meta-data?
  * If not, can we document it on the linked URL that we can add manually the needed meta-data entries?
  * If yes, could we update the docs pointing that? 
 * I will need to do the same for iOS since prebuild doesn't work when there's no expo dependency?

Edit:
I was looking at closed issues now, and there's this comment here that mentions the meta-data that needs to be added manually
https://github.com/expo/expo/issues/10837#issuecomment-718024718

but as noted by the comment bellow, that mentioned code doesn't exist at the current URL, so can we restore it?

### Link to the related docs page

https://github.com/expo/expo/tree/master/packages/expo-notifications

**Comment by cruzach** [comment]
fixed here- https://github.com/expo/expo/tree/master/packages/expo-notifications#configure-for-android

thanks for the report!
