### ISSUE TITLE
Pressing small "L" on android causes going back to menu

### ISSUE THREAD

**Issue by hannojg** [expo/expo#13878]
### Summary

When pressing "l" in an input on an android emulator the app closes and the dev client start page is opened again. It's not documented anywhere, nor is it configurable. It is not great for the developer experience and feels like a bug.

https://user-images.githubusercontent.com/16821682/127782849-24f99098-1631-4e85-a285-d9370554bc3a.mov

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "^0.4.5",
"react-native": "~0.63.4",
"expo-updates": "~0.8.1",

### Environment

  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.1, 30.0.2, 30.0.3
        System Images: android-23 | Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-R | Google APIs Intel x86 Atom
        Android NDK: 20.1.5948944
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```bash
expo init DevClientAndroidPressL
cd DevClientAndroidPressL
yarn add expo-dev-client
expo run:android 
```

Then add a text input to the app and enter the small letter "L".

**Comment by lukmccall** [comment]
This was fixed by https://github.com/expo/expo/pull/13794. The fix will be available in the new version of the dev-client (it wasn't published yet). 

So I'm closing this issue for now. If the new version won't resolve the problem for you, feel free to reopen it.
