### ISSUE TITLE
Invariant Violation: No callback found when using local NPM module

### ISSUE THREAD

**Issue by arcln** [expo/expo#13882]
### Summary

When replacing an NPM module (react-native-webview) by its local version (using file:./...), I get the following error :

```
Invariant Violation: No callback found with cbID 2 and callID 1 for module <unknown>.
Args '[{"app_state": "active"}]'
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.3

### Environment

  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 3.3.1 - /usr/local/bin/fish
    Binaries:
      Node: 16.3.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

* Clone compatible react-native-webview version : `git clone --branch v11.6.2 git@github.com:react-native-webview/react-native-webview.git`
* Build react-native-webview : `cd react-native-webview && yarn && cd ..`
* Init new blank expo project `expo init test`
* Install local module into project : `cd test && expo install file:../react-native-webview`
* Import `WebView` into App component : `import WebView from 'react-native-webview'`
* Run and see the error : `expo start`

**Comment by cruzach** [comment]
In the managed workflow, you need to use the module version that is supported by that particular SDK version. This is done for you if you use `expo install`. If you want to work with newer versions of packages or edit their native code yourself, you'll need to use the `expo run:[android | ios]` commands

**Comment by arcln** [comment]
Thanks, this got me further. However using `expo run:ios`, I am now facing this error : `Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`.

I tried to clear all sort of caches as I found on the Internet, but without success. Do you have any suggestions?
