### ISSUE TITLE
jest-expo failed testing createCacheKeyFunction

### ISSUE THREAD

**Issue by joseocabarcas** [expo/expo#13886]
### Summary

Hi, I'm having trouble updating to SDK 42 to run unit tests.
I am having this error with jest-expo

```
Cannot find module 'fbjs-scripts/jest/createCacheKeyFunction'
    Require stack:
    - C:\Users\jocab\WorkSpaceElenas\elenas\app\node_modules\jest-expo\src\preset\assetFileTransformer.js
    - C:\Users\jocab\WorkSpaceElenas\elenas\app\node_modules\@jest\transform\build\ScriptTransformer.js
    - C:\Users\jocab\WorkSpaceElenas\elenas\app\node_modules\@jest\transform\build\index.js
    - C:\Users\jocab\WorkSpaceElenas\elenas\app\node_modules\jest-runtime\build\index.js
    - C:\Users\jocab\WorkSpaceElenas\elenas\app\node_modules\jest-runner\build\testWorker.js
    - C:\Users\jocab\WorkSpaceElenas\elenas\app\node_modules\jest-worker\build\workers\processChild.js

    Require stack:
      node_modules/jest-expo/src/preset/assetFileTransformer.js
      node_modules/@jest/transform/build/ScriptTransformer.js
      node_modules/@jest/transform/build/index.js
      node_modules/jest-runtime/build/index.js
      node_modules/jest-runner/build/testWorker.js
      node_modules/jest-worker/build/workers/processChild.js
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

 Expo CLI 4.9.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.3 - C:\Users\jocab\AppData\Local\Temp\yarn--1627936221009-0.16358276054367216\node.CMD
      Yarn: 1.22.4 - C:\Users\jocab\AppData\Local\Temp\yarn--1627936221009-0.16358276054367216\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20200424.164118.0 - C:\Users\jocab\watchman\windows\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^42.0.0 => 42.0.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by joseocabarcas** [comment]
This is `jest.config.js`

const expoPreset = require("jest-expo/jest-preset.js");

```
module.exports = {
  preset: "jest-expo",
  transformIgnorePatterns: [
    "node_modules/(?!(jest-)?react-native|@react-native|unimodules-permissions-interface|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|native-base|@sentry/react-native|@segment/analytics-react-native/.*|@ui-kitten)|@wootric/react-native-wootric/.*|@ui-kitten",
    // "node_modules/@ui-kitten",
  ],
  // transform: expoPreset.transform,
  testPathIgnorePatterns: ["<rootDir>/node_modules"],
  // setupFiles: [...expoPreset.setupFiles, "<rootDir>/setUpFileJest.js"],
  setupFiles: ["<rootDir>/setUpFileJest.js"],
  setupFilesAfterEnv: ["@testing-library/jest-native/extend-expect"],
  coverageReporters: ["text", "cobertura", "lcov"],
  moduleNameMapper: {
    "\\.svg": "<rootDir>/__mocks__/svgMock.js"
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  verbose: true,
  collectCoverageFrom: [
    "**/*.{ts,tsx}",
    "!**/coverage/**",
    "!**/node_modules/**",
    "!**/babel.config.js",
    "!**/jest.setup.js",
  ]
};
```

**Comment by crcass** [comment]
I was able to get around this issue by adding `fbjs-scripts` as a `devDependency` in my `package.json`

**Comment by byCedric** [comment]
This issue happens if you are using a newer React Native version, e.g. `0.64.2`. In this React Native version, `fbjs-scripts` is removed. We will fix this when we upgrade our internal React Native version to `0.64.x`. For now, the best workaround would be to use @crcass's workaround.

**Comment by joseocabarcas** [comment]
Yes, I downgraded to the version 0.63 and it is fixed. For now, I will use @crcass workaround.
