### ISSUE TITLE
Background JS loading not behaving as expected in SDK 25, leading to slow app launch

### ISSUE THREAD

**Issue by ArsenyYankovsky** [expo/expo#1389]
I have a production app built with sdk 24 (I'm not upgrading to sdk 25 since the startup of the app is much slower with that) with loadJSInBackgroundExperimental enabled. 
I also have following in my app.json
```
    "assetBundlePatterns": [
      "assets/fonts/*",
      "node_modules/@expo/vector-icons/fonts/*"
    ],
```
which is supposed to bundle everything I have inside the app.

The issue is that at the first start with a slow internet connection app is stuck at loading screen until it loads all of the assets or js bundle (not sure which).

I also get following error in Sentry:

```
Error: Could not download from 'https://d1wp6m56sqw74a.cloudfront.net/~assets/d2285965fe34b05465047401b8595dd0'
  at None (app:///main.ios.bundle:18:806)
  at None (app:///main.ios.bundle:18:860)
  at value (app:///main.ios.bundle:20:3368)
  at None (app:///main.ios.bundle:20:1141)
  at value (app:///main.ios.bundle:20:2507)
...
(1 additional frame(s) were not displayed)
```

I'm pretty sure it used to be working for me because I tested it with Charles proxy.

Is there any way to disable loading assets and js bundle at all to make sure first app start (which can be last in case someone has to wait for THAT long) takes reasonable time or at least doesn't depend on Expo backend? That would be the only real solution I see.

**Comment by ArsenyYankovsky** [comment]
It takes up to 8 seconds with Charles throttling enabled for the app to start because it tries to get `https://exp.host:443/@arsenyyankovsky/spark-fiction/index.exp` even though I have `isRemoteJSEnabled` set to `true`. I'll post a screenshot of all the requests and my app.json in an hour or so.

**Comment by ArsenyYankovsky** [comment]
My app.json:

```
{
  "expo": {
    "name": "Spark Fiction",
    "description": "Spark Fiction is a collection of short fictional stories. Stories are around 1000 words so they are readable in about 5 minutes. ",
    "slug": "spark-fiction",
    "privacy": "public",
    "sdkVersion": "25.0.0",
    "version": "1.0.19",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "png"
      ]
    },
    "android": {
      "versionCode": 19,
      "icon": "./assets/images/android.icon.png",
      "package": "com.sparkfiction.mobile",
      "config": {
        "googleSignIn": {
          "apiKey": "",
          "certificateHash": ""
        }
      },
      "permissions": []
    },
    "androidStatusBar": {
      "backgroundColor": "#FFFFFF"
    },
    "ios": {
      "icon": "./assets/images/ios.icon.png",
      "supportsTablet": true,
      "bundleIdentifier": "com.sparkfiction.ios",
      "isRemoteJSEnabled": false,
      "buildNumber": "1.0.19",
      "config": {
        "googleSignIn": {
          "reservedClientId": ""
        }
      }
    },
    "facebookScheme": "",
    "facebookAppId": "",
    "facebookDisplayName": "Spark Fiction",
    "assetBundlePatterns": [
      "assets/fonts/",
      "node_modules/@expo/vector-icons/fonts/",
      "node_modules/react-navigation/src/views/assets/**"
    ],
  }
}
```


And there is the log of requests on the application startup:
[expo_loading.txt](https://github.com/expo/expo/files/1700791/expo_loading.txt)

None of the assets are being loaded, it's just some calls to facebook's graphql and https://exp.host:443/@arsenyyankovsky/spark-fiction/index.exp that make all the wait time.

**Comment by ArsenyYankovsky** [comment]
It's not only the first launch that is affected. Second and further launches have two "blocking" facebook and exp.host calls (up to 5 seconds combined).

**Comment by ArsenyYankovsky** [comment]
@terribleben @esamelson Please not that there is also fb analytics request to `graph.facebook.com` which is blocking an app on the splash screen too. Thanks.

**Comment by terribleben** [comment]
Hey everyone who was taking a look at this thread - can you try with SDK 26? We redid the way the app fetches updates.

We didn't pay special attention to requests made by our third party libs like Facebook. It's possible you'll still see network traffic from those. Let us know if it seems to be adversely affecting your app launch.
