### ISSUE TITLE
expo FirebaseRecaptcha  : IOS crash at start

### ISSUE THREAD

**Issue by Nrjwolf** [expo/expo#13893]
### Summary

Just import line make my app crash on IOS

`import { FirebaseRecaptchaVerifierModal, FirebaseRecaptchaBanner } from 'expo-firebase-recaptcha';
`

[testflight_feedback (1).zip](https://github.com/expo/expo/files/6923716/testflight_feedback.1.zip)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.0

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 30.0.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Add line

`import { FirebaseRecaptchaVerifierModal, FirebaseRecaptchaBanner } from 'expo-firebase-recaptcha';
`

**Comment by cruzach** [comment]
Does your app only crash in a standalone version on TestFlight? for example, this snack has that import but doesn't crash- https://snack.expo.dev/@charliecruzan/supportive-waffles

**Comment by Nrjwolf** [comment]
> Does your app only crash in a standalone version on TestFlight? for example, this snack has that import but doesn't crash- https://snack.expo.dev/@charliecruzan/supportive-waffles

Hey, I got what the problem was. I didn't add plist/json configs for mobile. It will be better if you add line to FirebaseRecaptcha docs about this page https://docs.expo.dev/versions/latest/sdk/firebase-core/

Because right now it seems like all what I need is webconfig.
