### ISSUE TITLE
Feature Request: Add full firebase functionality via react-native-firebase

### ISSUE THREAD

**Issue by IljaDaderko** [expo/expo#139]
I've been following guys over at [react-native-firebase](https://github.com/invertase/react-native-firebase) And it seems like like library is maturing very fast and tests are getting stronger. It is currently in alpha, but assuming release is around the corner, is this something expo would be willing to add in to let us use full native firebase functionality? i.e. Analytics / Crash reporting / Dynamic links etc..

**Comment by terribleben** [comment]
Closing in favor of https://expo.canny.io/feature-requests/p/full-native-firebase-integration
