### ISSUE TITLE
Assets from node_modules aren't loaded from address they're hosted from

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#13908]
### Summary

URL path for monorepo dependency containing assets is incorrect. Found the asset at another URL, but Expo fails to load it. (See first comment for details)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.x

### Environment

```
Expo CLI 4.9.1 environment info:
    System:
      OS: Windows 7 6.1.7601
    Binaries:
      Node: 12.21.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - C:\Users\MyUser\AppData\Local\watchman\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 23
        Build Tools: 23.0.1, 23.0.3, 26.0.2
    IDEs:
      Android Studio: Version  2.3.0.0 AI-162.3871768
    npmPackages:
      react: * => 17.0.2
      react-dom: * => 17.0.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Unsure currently.

**Comment by Slapbox** [comment]
**Wrong URL that Expo tries to load:** http://192.168.1.200:19000/assets/../rn/our-assets-rn/src/threaded/makeReady.html?platform=android&hash=23bf6192ebb19c552e7ab02901a45577?platform=android&dev=true&hot=false&minify=false

**URL that I found the asset at:** http://192.168.1.200:19000/node_modules/our-assets-rn/src/threaded/makeReady.html?platform=android&hash=23bf6192ebb19c552e7ab02901a45577?platform=android&dev=true&hot=false&minify=false

**Require statement looks like this:**

```js
const threadModule = Asset.fromModule(
  require('our-assets-rn/src/threaded/makeReady.html')
);
``

**File structure looks like:`**

- /
  - packages
    - mobile (contains Expo project. We run `expo start` from here)
    - rn
      - our-assets-rn
        - src
          - makeReady.html


Does anyone know why it might be looking at `assets/../rn/our-assets-rn` instead of the URL the asset is actual hosted at, `node_modules/our-assets-rn`? Being able to put our assets into their own monorepo package would be _huge_ for us.

Thanks for reading.

**Comment by brentvatne** [comment]
https://github.com/facebook/metro/issues/290
