### ISSUE TITLE
Expo breaks on Gradle 7.0.0 because of Maven

### ISSUE THREAD

**Issue by nixolas1** [expo/expo#13917]
### Summary

In Gradle 7.0.0 the maven plugin is gone, which many expo parts use. At least camera, barcode scanner and constants.
This causes it to break the build.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: ^0.64.2 => 0.64.2 
    npmGlobalPackages:
      expo-cli: 4.9.1

### Reproducible demo or steps to reproduce from a blank project

Upgrade to gradle 7.0.0 in android studio, with expo-barcode-scanner installed. Try building.

**Comment by stigi** [comment]
I believe this is the same issue as https://github.com/expo/expo/issues/12774. There's a workaround mentioned in [one of the comments](https://github.com/expo/expo/issues/12774#issuecomment-903216681), which requires patching the lib though.

**Comment by perpetuatingcuriosity** [comment]
React Native supports gradle 7.0 as of 65.1: https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0651

Can this be actioned now?

**Comment by Kudo** [comment]
duplicated as #12774. i am closing this and keep update in #12774. thank you!

**Comment by yfeleke** [comment]
In my case, I was on expo 45 but there was another react-native package that depended on @unimodules/core. I had to remove the package and no longer have an outdated react-native package pulling in the old build.gradle file with the issue. 

Steps to solve:
Find out the package that sourced the gradle error with 'maven' plugin
$> npm ls <packagename>
remove or update the parent package.

This can also cause a duplicate import error in ios b/c the dynamic linking (post migration) and unimodules/core will try to pull in the same libs
