### ISSUE TITLE
Adding 'json' to AssetExts breaks @expo/vector-icons

### ISSUE THREAD

**Issue by allenhj** [expo/expo#1391]
### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 7.7.4
  Yarn: 1.2.1
  npm: 4.1.2
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/allenhj-080a27fa-656e-40a0-ab1a-aa18842aa78c.tar.gz

### Steps to Reproduce

We're building an AR application that displays 3D text using Expo, Expo-three, and Three.js (`THREE.TextBufferGeometry`). In order to use Three's `FontLoader`, we need to supply a JSON font. To do this, we need to add 'json' to our `AssetExts` so that `Asset.fromModule` can cache and retrieve a local file. 

(Write your steps here:)

1. Add 'json' to App.json's `AssetExts`
2. Include icons from `@expo/vector-icons` in a component
3. Build app
4. Warning: "Warning: Failed prop type: Invalid prop `name` of value `user` supplied to `Icon`, expected one of []."

### Expected Behavior

Icons would display. 

### Actual Behavior

All icons display as "?" icon.

### Reproducible Demo
https://github.com/AlphabetCity/AlphabetCity-Native-App/tree/ar-letters

**Comment by EvanBacon** [comment]
@allenhj Here is how to load text into three.js without using json as an asset: https://snack.expo.io/@bacon/three-text
