### ISSUE TITLE
Expo Camera Black Screen

### ISSUE THREAD

**Issue by dondragon2** [expo/expo#13919]
### Summary

I am getting a black screen when I try to show the camera using the expo-camera. The preview screen is always black no matter what I try, cleaning, fresh project. same issue.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

```
"expo-camera": "^11.2.2",
 "react-native-unimodules": "^0.14.6",
```

```
Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: ^0.63.3 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

below is the code that is being used.
```
import { useIsFocused } from '@react-navigation/native';
import { Camera } from 'expo-camera';
import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

const TestScanner = () => {
  const [hasPermission, setHasPermission] = useState<boolean | null>(null);
  const isFocused = useIsFocused();

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (!isFocused) {
    return null;
  }

  if (hasPermission === null) {
    return <View />;
  }
  if (!hasPermission) {
    return <Text>No access to camera</Text>;
  }
  const onCameraReady = () => {
    console.log('camera ready');
  };

  return (
    <Camera style={styles.camera} onCameraReady={onCameraReady} type={Camera.Constants.Type.back}>
      <View style={styles.buttonContainer}>
        <Text style={styles.text}> camera </Text>
      </View>
    </Camera>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  camera: {
    flex: 1
  },
  buttonContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    margin: 20
  },
  button: {
    flex: 0.1,
    alignSelf: 'flex-end',
    alignItems: 'center'
  },
  text: {
    fontSize: 18,
    color: 'white'
  }
});

export default TestScanner;
```

**Comment by dondragon2** [comment]
In addition to the above I added a `onMountError` function and it is showing the following message.

**_Camera component could not be rendered - is there any other instance running?_**

**Comment by cruzach** [comment]
Have you followed the [bare workflow setup instructions](https://github.com/expo/expo/tree/master/packages/expo-camera#installation-in-bare-react-native-projects)?

**Comment by dondragon2** [comment]
> Have you followed the [bare workflow setup instructions](https://github.com/expo/expo/tree/master/packages/expo-camera#installation-in-bare-react-native-projects)?

Yes, I have. It seems to be working now for iOS but with Android I am getting that onMountError.

**Comment by cruzach** [comment]
Same error message here- https://github.com/expo/expo/issues/2068

It's useful to search for the error to see if anyone else has already solved your issue

**Comment by dondragon2** [comment]
> Same error message here- #2068
> 
> It's useful to search for the error to see if anyone else has already solved your issue

Agreed. I found that already. That is not the same issue that I am having and I even tried that and it didn't work. I posted here as a last resort as I was not finding any solution online.

**Comment by cruzach** [comment]
I see, and this is tested in a fresh bare workflow project initiated with `expo init`?

**Comment by dondragon2** [comment]
> I see, and this is tested in a fresh bare workflow project initiated with `expo init`?

This is with a react native project with expo modules installed with unimodules also

**Comment by cruzach** [comment]
Try it with a bare workflow project init'd with `expo init`, to rule out issues with your setup of unimodules

**Comment by dondragon2** [comment]
I create a new react project with the following dependencies and went through the unimodules installation instructions and I get the same result, black Screen.

```
  "dependencies": {
    "expo-barcode-scanner": "^10.2.2",
    "expo-camera": "^11.2.2",
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-unimodules": "^0.14.6"
  }```

**Comment by dondragon2** [comment]
same result with the `expo init` bare workflow.
```  "dependencies": {
    "expo": "~42.0.1",
    "expo-barcode-scanner": "~10.2.2",
    "expo-camera": "~11.2.2",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.8.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-unimodules": "~0.14.5",
    "react-native-web": "~0.13.12"
  },

**Comment by yachaka** [comment]
Same issue here

**Comment by dondragon2** [comment]
I am not entirely sure how this got resolved me now but a couple things I noticed in our code.
1. We were using react-native-permissions package instead of the one that comes with the expo packages.
`const status = await Permissions.request(PERMISSIONS.IOS.CAMERA);`
change to
`const { status } = await BarCodeScanner.requestPermissionsAsync();`

2. Ensure that we were using the latest `expo-modules-core` by ensuring that the `react-native-unimodules` is up to date and configured based on the latest documentation.

But I think for me it may have been the mixing of the permissions package that was causing the issue.

**Comment by MANTENN** [comment]
Still getting black screen, these are my deps. 

```
{
  "name": "---",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "expo": "^45.0.0",
    "expo-blur": "^11.1.0",
    "expo-camera": "^12.2.0",
    "expo-modules-core": "^0.9.1",
    "expo-web-browser": "^10.2.0",
    "react": "17.0.2",
    "react-native": "0.68.1",
    "react-native-map-link": "^2.9.3",
    "react-native-mmkv": "^2.3.3",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-svg": "^12.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^27.5.0",
    "@types/react": "^18.0.9",
    "@types/react-native": "^0.67.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.6.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by MANTENN** [comment]
> > Have you followed the [bare workflow setup instructions](https://github.com/expo/expo/tree/master/packages/expo-camera#installation-in-bare-react-native-projects)?
> 
> Yes, I have. It seems to be working now for iOS but with Android I am getting that onMountError.

How does it work for you? I copied the code and paste it. I even did the permissions for IOS in the Info.plist and its not working.

**Comment by MANTENN** [comment]
This works:  https://github.com/teslamotors/react-native-camera-kit. Didn't have to ask for permissions—looks like a bridge problem with expo. So weird.

**Comment by SalmanK81099** [comment]
So if anyone is still having this issue, I resolved it by using the right ratio, if you use the ref object from the camera we have a function there called [getSupportedRatiosAsync](https://docs.expo.dev/versions/latest/sdk/camera/#getsupportedratiosasync), if you use this you can see which ratios are supported by the current device so you can check the ratio you are using if it is supported by the device you can use it or use any ratio from the array response from the above function and it should resolve the issue.

**Comment by sokoya** [comment]
> So if anyone is still having this issue, the problem is related to the ratio being used that is unsupported on a device. I resolved it by using the right ratio, if you use the ref object from the camera we have a function there called [getSupportedRatiosAsync](https://docs.expo.dev/versions/latest/sdk/camera/#getsupportedratiosasync), if you use this you can see which ratios are supported by the current device so you can check the ratio you are using if it is supported by the device you can use it or use any ratio from the array response from the above function and it should resolve the issue.

Please what SDK Version are you using.
I am using SDK 45 and Camera is black in production, works fine on Expo Go

**Comment by andrody** [comment]
> ratio
same thing, I am using SDK 46 and Camera is black in production, works fine on Expo Go

**Comment by sokoya** [comment]
> @sokoya
> same thing, I am using SDK 46 and Camera is black in production, works fine on Expo Go

Sorry about that, I can imagine… it took me a whole 1 week.

can’t really figured out the solution, but I upgraded to sdk47

**Comment by latobibor** [comment]
> @SalmanK81099 
> So if anyone is still having this issue, the problem is related to the ratio being used that is unsupported on a device. I resolved it by using the right ratio, if you use the ref object from the camera we have a function there called [getSupportedRatiosAsync](https://docs.expo.dev/versions/latest/sdk/camera/#getsupportedratiosasync), if you use this you can see which ratios are supported by the current device so you can check the ratio you are using if it is supported by the device you can use it or use any ratio from the array response from the above function and it should resolve the issue.

Well I have tried that but got instead:

> Error: Call to function 'ExponentCamera.getSupportedRatios' has been rejected. → Caused by: Camera is not running

**Comment by MANTENN** [comment]
> So if anyone is still having this issue, the problem is related to the ratio being used that is unsupported on a device. I resolved it by using the right ratio, if you use the ref object from the camera we have a function there called [getSupportedRatiosAsync](https://docs.expo.dev/versions/latest/sdk/camera/#getsupportedratiosasync), if you use this you can see which ratios are supported by the current device so you can check the ratio you are using if it is supported by the device you can use it or use any ratio from the array response from the above function and it should resolve the issue.

thats odd because it was black on iphone 13 pro max for me

**Comment by alexander0205** [comment]
In case if the black screen is always and you are using android, try to add in your AndroidManifest.xml file .

`android:hardwareAccelerated="true"`

**Comment by sonnv174** [comment]
I also had this problem on my iPhone 13 Pro, but on iPhone X the camera was still showing.

**Comment by feri-irawan** [comment]
> @sokoya same thing, I am using SDK 46 and Camera is black in production, works fine on Expo Go

same thing

**Comment by josiext** [comment]
Same here!

**Comment by josiext** [comment]
Solved updating to expo-camera 16.0.14

**Comment by LemireCoding** [comment]
I am having an issue on expo-camera android devices (tested on google pixel 6a and s21 pro) Where the preview freezes on record and can never stop recording please

**Comment by Gedoz** [comment]
> In case if the black screen is always and you are using android, try to add in your AndroidManifest.xml file .
> 
> `android:hardwareAccelerated="true"`

I added this code to `app.config.ts` so that every time I run `npx expo prebuild`, it is automatically included.

```
import { ExpoConfig, ConfigContext } from "expo/config";
import { withPlugins, withAndroidManifest } from "expo/config-plugins";

const withHardwareAcceleration = (config) => {
  return withAndroidManifest(config, (config) => {
    const androidManifest = config.modResults.manifest;

    if (androidManifest.application && androidManifest.application[0]) {
      androidManifest.application[0].$["android:hardwareAccelerated"] = "true";
    }

    return config;
  });
};

export default (context: ConfigContext): ExpoConfig => {
  const config = {
    ...context.config
  } as ExpoConfig;

  return withPlugins(config, [
    ...,
    withHardwareAcceleration
  ]);
};
```

**Comment by andrea-deluca-deepcube** [comment]
For those who have a similar error and are using **nativewind** for styling, **try removing** any classes like "**flex-1**" in favor of react's native style native { flex: 1 }. 

I hope I saved you from a headache
