### ISSUE TITLE
expo-auth-session not handling deep links

### ISSUE THREAD

**Issue by bruno-brant** [expo/expo#13922]
### Summary

I'm creating an expo application that must authenticate with IdentityServer4. I've triple checked the documentation and it seems I've followed every step; however, AuthSession isn't handling the redirect correctly - in fact, React Navigation handles the link and shows a not found screen (that is there from the tabs template).

Now, I'm not completely sure whether the deep link (`exp://192.168.15.15:19000/--/expo-auth-session?code=F89B4EA9074AE3127DFF9C06143305929B6A737390D31CB2EC7D6AF126DE093A&scope=openid+profile+offline_access&state=GlIRZoqYw9&session_state=gydz3ihHaRYxX5CrsLOrXGrJ_hANwBWNWPhLWt8nlKg.2E96C1DFEB201803ED9A6D2B7BE92701`) was supposed to be handled by auth-session directly or if something is missing in the docs and I'm the one supposed to handle it manually, but it seems confusing - more so when I realized that `promptAsync` returns all data and therefore no redirect was necessary.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.1

### Environment

 Expo CLI 4.8.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.3.0 - C:\Aplic\nodejs\node.EXE
      npm: 7.15.1 - C:\Aplic\nodejs\npm.CMD
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Create a new expo app using the cli. Use the tabs template.
2. Install expo-auth-session and expo-random;
3. Following the guide, call `useAuthRequest` with the necessary parameters to log into a identityserver instance (you can probably use https://demo.identityserver.com/). 
4. After the browser is opened and you enter the credentials, the app suffers a redirect, but React Navigation will show the Not Found page.

**Comment by EvanBacon** [comment]
Seems related to https://github.com/expo/expo/issues/13248

**Comment by bruno-brant** [comment]
@EvanBacon not sure. In my case it seems expo is not registering itself to handle the deep links (if I understood correctly how that should be working). On reason that maybe happening is some conflict with React Navigation, but I couldn't find any docs explaining how it actually works.

Right now I handling the deep linking through Navigation (expo-auth-session links will send the user to the login screen, which is a no-op since the app is already on said screen).

**Comment by felix-lambert** [comment]
I have the same problem. Any help would be appreciated

**Comment by duplxey** [comment]
I have the exact same problem. Has anyone figured out how to solve this?

**Comment by bmarden** [comment]
@bruno-brant did you ever find a resolution to this?

**Comment by ggbono** [comment]
i'm facing with the same issue, using expo-auth-session for login with Google and auth0 api for authorization as oauth, anyone who has any idea?
