### ISSUE TITLE
SVG Text TSpan dy behaves differently on Android and iOS

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#1393]
### Environment

sdk 23 -24-25

### Steps to Reproduce
This issue https://github.com/react-native-community/react-native-svg/issues/377 happens due to the embedded version of react-native-svg equal to 5.5.1

### Expected Behavior

use a fresher version (6 is rc) of react-native-svg or msand’s fork 

### Actual Behavior

react-native-svg equal to 5.5.1

### Reproducible Demo

https://snack.expo.io/@lc3t35/tspan-dy-demo

**Comment by ccheever** [comment]
Thanks for this report! Very helpful.

**Comment by slava-lu** [comment]
It would also be good if Expo guys put the library version in docs so that we new where the problem is.  And please upgrade SVG as rather useful module -  Victory Native does not work now,

**Comment by lc3t35** [comment]
@slava-lu this is exactly what I was asking for in my post at expo.io's forum : https://forums.expo.io/t/which-versions-of-react-native-svg-are-built-with-each-sdk/6075

**Comment by Elijen** [comment]
I can confirm this is causing some ugly issues: https://github.com/FormidableLabs/victory-native/issues/255

**Comment by robertobrogi** [comment]
yep i have the same problem...

**Comment by Elijen** [comment]
@robertobrogi As mentioned in the other issue it should work fine with `victory-native@~0.15.0`

**Comment by terribleben** [comment]
We'll be updating rn-svg in Expo as soon as possible because we've resolved the upstream issue that was preventing us from updating earlier. https://github.com/react-native-community/react-native-svg/issues/603
