### ISSUE TITLE
Blank area close to bottom nav bar

### ISSUE THREAD

**Issue by rodolfobarretoweb** [expo/expo#13938]
### Summary

The bug behavior can be seen in the video below:
https://linguix.s3.sa-east-1.amazonaws.com/WhatsApp+Video+2021-08-05+at+12.47.23.mp4

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.14.0/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

```

### Reproducible demo or steps to reproduce from a blank project

I don't know how to reproduce this error. So far I noticed this eventually happens without doing anything specific.

**Comment by brentvatne** [comment]
hi there! we can't help without a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). this is likely a bug in your own code. if you're having trouble figuring out the root cause then try [something like this](https://expo.fyi/manual-debugging)
