### ISSUE TITLE
Android keystore with incorrect password!

### ISSUE THREAD

**Issue by ramadis** [expo/expo#1394]
I downloaded my android keystore via `exp fetch:android:keystore` and the console printed out the necessary credentials:

```
Keystore password: ********-****-****-****
Key alias:         **************
Key password:      ********-****-****-****
```
However, when the signing system keeps saying the password is incorrect. I have a few doubts.

1. Is the alias the one printed by `exp` or should I decode it in base64 (Since it is a base64 encoded string)?
2. The password seems to be incorrect. Which one should I use, is it encrypted, encoded, or how can I access it?

Thank you very much!

**Comment by anp** [comment]
Hi! Can you tell me how you're testing this?

**Comment by ramadis** [comment]
@anp Through the most painful and slow process: I'm rebuilding the apk through expo system, uploading the downloaded keystore and trying different parameters for `alias/key pass/keystore pass`

**Comment by anp** [comment]
Where are you uploading the keystore? Google Play?

**Comment by anp** [comment]
Also, are you trying to upload an app that was already published once without Expo?

**Comment by ramadis** [comment]
@anp To the second question: No, the app was only published via expo. About the keystore: When choosing to build with android through `exp build:android` the console prompts to choose between using expo credentials and using my own keystore. Since the first option wasn't working, I chose to retrieve the keystore using `exp fetch:android:keystore` and go with the second option, using the credentials given by the console.

This is where I am right now. When signing with the credentials given out by `exp`, the sigining system keeps saying `Incorrect password`.

**Comment by anp** [comment]
Hm, I'm sorry, that sounds like a problem. Can you paste the output of trying to upload the keystore?

**Comment by ramadis** [comment]
@anp Well, the only significative lines are these:

```
...
BUILD SUCCESSFUL
Total time: 8 mins 0.288 secs
jarsigner error: java.lang.RuntimeException: keystore load: Keystore was tampered with, or password was incorrect
Process exited with non-zero code: 1
...
```

Not sure if theres much information there anyway. The main issue is, why is it failing to sign the apk, given that I put in the same credentials that `exp` printed out in the console when I fetched the keystore?

Thanks Adam!

**Comment by anp** [comment]
What process is outputting these lines?

**Comment by ramadis** [comment]
@anp These lines are the ones outputted by the `expo` building system. The error happens when the `jarsigner` is not able to use the keystore to sign the apk.

**Comment by anp** [comment]
Can you paste the build log URL for this build?

**Comment by ramadis** [comment]
This is one of the many builds with the incorrect password issue: https://expo.io/builds/fb4f64f1-0204-4d2b-9c26-75a3e7cfbef5

**Comment by ramadis** [comment]
@anp any updates on the issue?

**Comment by anp** [comment]
Hi! Sorry about that. I've pinged a couple of people internally to take a look at this build. Just to confirm I'm understanding the order correctly:

1. you ran a build for a project other than calma, and let Expo generate the keystore
2. in the project from 1, you ran `exp fetch:android:keystore` and saved the output
3. in calma, you uploaded the keystore with the credentials from 2 and saw this behavior happen

Can you try the following?

1. install Java on your computer if you haven't already, and make sure you have the `keytool` command line program available
2. do number 2 from above again, and re-fetch the keystore and credentials from your other project
3. run `keytool -keypasswd -keystore <keystore path> -alias <key alias> -storepass <keystore password> -keypass <key password> -new <key password>`, substituting the values in angle brackets as appropriate
4. if that fails, can you try running a build for your other project and posting the build logs for that? if that succeeds, can you try running `exp build:android -c` in calma, and upload the keystore file you redownloaded?

It would be great if you could post back and let me know whether my understanding of what you've tried is correct, and what happened when you tried each of the steps you suggested. Thanks!

**Comment by anp** [comment]
Hi! If you're still having issues with this can you please reply back and I'll reopen? Thanks!

**Comment by Jesserhee** [comment]
I put the path of my .jks file what I downloaded from expo fetch
and copy and paste the information below also I got from expo fetch.

Keystore password: 
Key alias: 
Key password:

but I got this message after I copy and paste all of those information 
when the expo build asks me them.

Unable to find an existing exp instance for this directory, starting a new one...
