### ISSUE TITLE
[docs] Expo notification icon

### ISSUE THREAD

**Issue by jramosss** [expo/expo#13940]
### Summary

In the expo notifications page we have an example to set the notification icon IF you are using eas build, but there is no example available in any other cases, that caused many problems and im still not able to set a custom notification icon, just getting a blank square.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/notifications/

**Comment by cruzach** [comment]
Under the "Installation" section of that docs page, we have:

> If you're installing this in a bare React Native app, you should also follow these additional installation instructions.

which link [here](https://github.com/expo/expo/tree/master/packages/expo-notifications), and when you scroll down you'll see `Expand to view how the notification icon and the default color can be customized in a plain React Native app`

**Comment by jramosss** [comment]
I dont use bare workflow and still cant get it to work

**Comment by cruzach** [comment]
if you're using the managed workflow, and all you have is a blank white square as the notification icon, it means your icon doesn't follow google's recommended format. This is covered in our [notifications faq](https://docs.expo.dev/push-notifications/faq/#my-notification-icon-on-android-is-a)
