### ISSUE TITLE
The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly

### ISSUE THREAD

**Issue by KrisLau** [expo/expo#13944]
### Summary

I installed the unimodules successfully and I'm currently still able to use expo packages. However, whenever I try to run `jest` to run my unit tests, I run into this error:
```
The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly
```

Jest config in package.json:
```
"jest": {
    "preset": "react-native",
    "setupFiles": [
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation|@unimodules/.*|unimodules|expo(nent)?|@expo(nent)?/.*)/"
    ]
  }
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 3.06 GB / 15.89 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Reproducible demo or steps to reproduce from a blank project

Install jest into bare workflow
Install unimodules 
Run jest command

**Comment by byCedric** [comment]
Hi @KrisLau, can you provide a reproducible example? Without that, we can't help you debug what's going on.

**Comment by KrisLau** [comment]
@byCedric I tried to repro it in a new repo but I was not able to and unfortunately, my current repo can't be shared because it's for work :'(. However I did find some new information I think? When I click on the call stack it sends me to the `import { requireNativeViewManager } from './NativeViewManagerAdapter';` in `@unimodules/react-native-adapter/src/index.ts`

```
TS6142: Module './NativeViewManagerAdapter' was resolved to '/Users/newuser/Desktop/Prototype/node_modules/@unimodules/react-native-adapter/src/NativeViewManagerAdapter.tsx', but '--jsx' is not set.
```

**Comment by KrisLau** [comment]
Sorry to keep bombing this thread but I managed to figure it out. It looks like it was cause by importing the test method from an index file with a bunch of other methods in it like this:
```
// utils/index.js
export {validateEmail as validateEmail} from './input-validation';
export {validatePassword as validatePassword} from './input-validation';
```
so I just changed the import in the test files from `import {validatePassword} from '../src/utils';` to `import {validatePassword} from '../src/utils/input-validation';`
I'm not sure how that causes the error but I'll close the thread since I'm not getting the error anymore
