### ISSUE TITLE
[expo-av] Permissions module not found. Are you sure that Expo modules are properly linked?

### ISSUE THREAD

**Issue by aclopesjr** [expo/expo#13941]
### Summary

I've got a bare RN project and use expo libs.

"react": "17.0.1",
"react-native": "0.64.0",
"expo-av": "^9.0.0",
"expo-barcode-scanner": "^10.1.2",
"expo-gl": "~9.1.1",
"expo-haptics": "8.3.0",
"expo-location": "^10.0.0",
"expo-notifications": "^0.11.5",
"expo-three": "^5.4.0",

Location works fine, but av is throwing an exception when try to get permission status.

When I try the code below:
`const hasPermission = await Audio.getPermissionsAsync();`

Throws this exception on iOS:
Permissions module not found. Are you sure that Expo modules are properly linked?

And throws this exception on Android:
Permissions module is null. Are you sure all the installed Expo modules are properly linked?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

"expo-av": "^9.0.0"

### Environment

ExceptionsManager.js:180 Error: Permissions module not found. Are you sure that Expo modules are properly linked?
    at Object.promiseMethodWrapper [as callMethod] (NativeModules.js:104)
    at Object.NativeModulesProxy.<computed>.<computed> [as getPermissionsAsync] (NativeModulesProxy.native.js:15)
    at getPermissionsAsync$ (Recording.js:114)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:189
    at tryCallTwo (core.js:45)

### Reproducible demo or steps to reproduce from a blank project

```
private askForPermission = async () => {
    try {
      const hasPermission = await Audio.getPermissionsAsync();
      if (hasPermission.status === Audio.PermissionStatus.UNDETERMINED) {
        return await Audio.requestPermissionsAsync();
      }
      return hasPermission;
    } catch (error) {
      throw error;
    }
  };
```

**Comment by byCedric** [comment]
Hi @aclopesjr! Can you provide a reproducible example for us to test with? It looks like you might be running into the similar issue https://github.com/expo/expo/issues/13957#issuecomment-894242653, I'm not sure if this is also the same for you since I don't know your project. Might still be good to try though.

**Comment by aclopesjr** [comment]
@byCedric you are right. I uptaded react-native-unimodules and now it's working. I had the same problem with expo-barcode-scanner, but in this case I had to update the expo-location lib also. It seems there is a mismatch around it. Is there any doc which describes the match dependency versions?
