### ISSUE TITLE
[firebase-analytics] view_item event will be error in Android

### ISSUE THREAD

**Issue by tasugi** [expo/expo#13954]
### Summary

I've tried to send `view_item` (described in [this page](https://firebase.google.com/docs/analytics/measure-ecommerce?hl=en#web-v8) ) event to Firebase.

In iOS, `expo-firebase-analytics` works great and events were successfully sent to my Firebase server.

But in Android, sent events were error events. Firebase says `items` are wrong format.

I fond this messages from Android logcat. I hope this info help to solve the problem!

```
2021-08-06 17:30:59.715 14609-1062/com.example.app W/FA: All ArrayList elements must be of type Bundle. Value type, name: class java.util.HashMap, items
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - ~/.anyenv/envs/nodenv/versions/14.15.3/bin/node
      Yarn: 1.22.10 - ~/.anyenv/envs/nodenv/versions/14.15.3/bin/yarn
      npm: 7.11.1 - ~/.anyenv/envs/nodenv/versions/14.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
  useEffect(() => {
    if (id && name) {
      Analytics.logEvent("view_item", {
        items: [{ item_id: id, item_name: name }],
      });
    }
  }, [id, name]);
```

**Comment by gustavoteodoro** [comment]
Looks like the `expo-firebase-analytics` is not working on Android anymore. Any update about it?
