### ISSUE TITLE
Inconsistent Audio.Sound.create behavior between Android and iOS

### ISSUE THREAD

**Issue by steve-prod** [expo/expo#1395]
Issue related to https://github.com/expo/expo/issues/425:

I'm using react native to build an audio messaging app.  Workflow is as follows:

1. User logs into app by entering username and password on login screen.
2. Username and password are sent to server
3. Server checks credentials and, if credentials are valid, sets a session ID in the cookie in the response
4. On next user screen, a list of received messages are displayed.  First the app makes a REST call to get the messages' metadata (message URI, creator, timestamp, etc...) and then uses that data (message URIs specifically) when calling Expo.Audio.Sound.create().

On the app generated for iOS, the cookie-based session ID is sent with the call to the server (see server log below  (all sessions shown have already been deleted :P)) and the audio data is retrieved (status 200).  On the app generated for Android, however, the session ID is NOT sent with the call to the server and the server responds with a 401.

<img width="1032" alt="server_log" src="https://user-images.githubusercontent.com/24657085/35956330-cf803e96-0c49-11e8-8a5a-d3abf3fdc780.png">

I believe I have identified the reason why the cookie is being sent by the iOS device and not the Android device.  I went through the source code for iOS AVPlayerData.m and found this line of code:
Version 25: https://github.com/expo/expo/blob/master/ios/versioned-react-native/ABI25_0_0/Expo/Core/Api/AV/ABI25_0_0EXAVPlayerData.m#L112.  
Versioned: https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Core/Api/AV/EXAVPlayerData.m#L112
Lines 112 and 113 appear to set the cookies, as desired.  

Would it be possible to get similar code for Android?  I think it would go in or near createUnloadedPlayerData:
Version 25: https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi25_0_0/host/exp/exponent/modules/api/av/player/PlayerData.java#L94.  
Versioned: https://github.com/expo/expo/blob/master/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/av/player/PlayerData.java#L94

I would be happy to submit a pull request if you thought this would useful and appropriate. Do you think PlayerData.java is where such fix would go?

**Comment by steve-prod** [comment]
Does "yourApplicationName" need to be changed when used in the SharedCookiesDataSourceFactory constructor (https://github.com/expo/expo/blob/master/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/av/player/SimpleExoPlayerData.java#L89)?  I see it in the Android request's User-Agent in the server log in the previous comment above.  Could that be causing the cookie not to load?

**Comment by sjchmiela** [comment]
Nope, `"yourApplicationName"` doesn't matter here too much, `userAgent` is only used to… set the user agent of the DataSource (only in constructor of the factory, see [code](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi25_0_0/host/exp/exponent/modules/api/av/player/SharedCookiesDataSourceFactory.java#L21-L28)).

The cookies are set based on a shared instance of HTTP client for this URL: [code](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi25_0_0/host/exp/exponent/modules/api/av/player/SharedCookiesDataSourceFactory.java#L41).

How do you send the authenticating request (the sign in)?

**Comment by steve-prod** [comment]
I use an XMLHttpRequest to POST FormData.  Would that account for the difference between Android and iOS behavior?

**Comment by steve-prod** [comment]
Login is [here](https://github.com/steve-prod/bespoke-audio-mobile/blob/master/components/LoginScreen.js#L67-L82) 
Metadata retrieval is [here](https://github.com/steve-prod/bespoke-audio-mobile/blob/master/components/InboxScreen.js#L132-L157)
(Attempted) Sound creation is [here](https://github.com/steve-prod/bespoke-audio-mobile/blob/master/components/InboxScreen.js#L203-L216)

**Comment by sjchmiela** [comment]
Thanks for catching this bug! Unfortunately, it is a bug. I'll try to address it as soon as possible. It looks like the list of cookies returned from OkHttpClient's cookie jar [is empty](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi25_0_0/host/exp/exponent/modules/api/av/player/SharedCookiesDataSourceFactory.java#L41). We should probably somehow try to access the cookie jar held by `NetworkingModule`.

**Comment by steve-prod** [comment]
Yes, it looks like ReactNativeStaticHelpers.getOkHttpClient() creates a new CookieJar instance everytime it's called (code [here](https://github.com/expo/expo/blob/cc97d38952925b83e11805b91d33e159b754c558/android/expoview/src/main/java/host/exp/exponent/ReactNativeStaticHelpers.java#L92)).
