### ISSUE TITLE
expo-camera : Error: Permissions module is null.

### ISSUE THREAD

**Issue by devSeb** [expo/expo#13957]
### Summary

Problem with the permission of the lib expo-camera.
The camera on a mobile doesn't start and I have many error in console 

`Error: Permissions module is null.`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

expo-camera: 11.2.2

### Environment

"dependencies": {
    "@expo/vector-icons": "^12.0.5",
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/auth": "^12.1.0",
    "@react-native-firebase/firestore": "^12.1.0",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/material-bottom-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "@reduxjs/toolkit": "^1.5.1",
    "expo-barcode-scanner": "^10.1.2",
    "expo-camera": "^11.2.2",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-date-picker": "^3.3.1",
    "react-native-geolocation-service": "^5.3.0-beta.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-multi-selectbox": "^1.5.0",
    "react-native-paper": "^4.9.1",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.2.0",
    "react-native-svg": "^12.1.1",
    "react-native-unimodules": "^0.13.3",
    "react-native-vector-icons": "^8.1.0",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-persist": "^6.0.0"
  },

### Reproducible demo or steps to reproduce from a blank project

I test with an android ( api 24 ) connected with firebase.
I have in my app 'expo-barcode-scanner' and i didn't have problems.

Step to reproduce : 
1) expo install expo-camera

2) add permission in android manifest
`<uses-permission android:name="android.permission.CAMERA" />`

3) add module expo camera in maven
```
  allprojects { 
     repositories {

    // * Your other repositories here *

    // * Add a new maven block after other repositories / blocks *
      maven {
        // expo-camera bundles a custom com.google.android:cameraview
        url "$rootDir/../node_modules/expo-camera/android/maven"
      }
    }
   }
```

start the protect
**Error: Permissions module is null.**
click on the button to show camera ... error in log + camera doesn't launch.

I try with this le Permission component in react-native to check if I have a permission

```
// state local
 const [hasPermission, setHasPermission] = useState(null);
 // function
 const requestCameraPermission = async () => {
        console.log('requestCameraPermission')
        try {
            const granted = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.CAMERA,
                {
                    title: "Cool Photo App Camera Permission",
                    message:
                        "Cool Photo App needs access to your camera " +
                        "so you can take awesome pictures.",
                    buttonNeutral: "Ask Me Later",
                    buttonNegative: "Cancel",
                    buttonPositive: "OK"
                }
            );
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                setHasPermission(true)
                console.log("You can use the camera");
            } else {
                console.log("Camera permission denied");
                setHasPermission(false)
            }
        } catch (err) {
            console.warn(err);
        }
    };

   // result of requestCameraPermission : You can use the camera
  //  Error  : Attempt to invoke interface method 'boolean expo.modules.interfaces.permission.Permission.hasGrantedPermissions(java.lang.string[]) on a null object reference
```

My composant to launch the Camera component: 
```

import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, TouchableOpacity, PermissionsAndroid } from 'react-native';
import { Camera } from 'expo-camera';

export default function CameraPicture() {
    const [hasPermission, setHasPermission] = useState(null);
    const [type, setType] = useState(Camera.Constants.Type.back);

    useEffect(() => {
       
        (async () => {
            const { status } = await Camera.requestPermissionsAsync();
            console.log('useEffect status ', status)
            setHasPermission(status === 'granted');
        })();

    }, []);

    if (hasPermission === null) {
        return <View />;
    }
    if (hasPermission === false) {
        return <Text>No access to camera</Text>;
    }
    return (
        <View style={{ flex: 1 }}>
            
                <View style={styles.container}>
                    <Camera style={styles.camera} type={type}>
                        <View style={styles.buttonContainer}>
                            <TouchableOpacity
                                style={styles.button}
                                onPress={() => {
                                    setType(
                                        type === Camera.Constants.Type.back
                                            ? Camera.Constants.Type.front
                                            : Camera.Constants.Type.back
                                    );
                                }}>
                                <Text style={styles.text}> Flip </Text>
                            </TouchableOpacity>
                        </View>
                    </Camera>
                </View>
           
        </View>
    );
}

const styles = StyleSheet.create({
    container: {},
    camera: {},
    buttonContainer: {},
    button: {},
    text: {},
});

```
I make something wrong ? thanks for help

**Comment by byCedric** [comment]
Hi @devSeb, your `react-native-unimodules` seems to be outdated. Please try to upgrade to at least `react-native-unimodules@0.14.x`. See [the changelog for more info](https://github.com/expo/expo/blob/master/packages/react-native-unimodules/CHANGELOG.md#0140--2021-05-25).

**Comment by devSeb** [comment]
@byCedric  Thanks you so much. I updated in the last react-native-unimodules ( 0.14.6 ) and it's work perfectly.

**Comment by byCedric** [comment]
No problem, glad you got it working! 😄
