### ISSUE TITLE
svg property strokeWidth on Android: react-native-svg

### ISSUE THREAD

**Issue by namnn89** [expo/expo#1396]
### Environment
i use expo version 25.0.0, and i use `react-native-svg-charts`.
Android: Error, 
IOS working fine
### Steps to Reproduce
                  <AreaChart
                        style={{ height: 200 }}
                        dataPoints={this.state.charts}
                        contentInset={ { top: 30, bottom: 30 } }
                        curve={shape.curveNatural}
                        svg={{
                            fill: 'rgba(134, 65, 244, 0.2)',
                            stroke: 'rgb(134, 65, 244)',
                        }}
                    />

### Actual Behavior
![27935154_977801265707723_124054054_n](https://user-images.githubusercontent.com/20234482/35958966-0b4d233a-0cd6-11e8-8235-0951167101be.jpg)

**Comment by terribleben** [comment]
Hi! We currently use rn-svg 5.5.1 in Expo, in which `strokeWidth` is a float, not a string. You may need to downgrade your version of your charts library to work with the older SVG version.

We'll probably update rn-svg to a newer version in an upcoming SDK.

**Comment by lordcatalien** [comment]
Is this Expo 25.0 that uses 5.5.1?
