### ISSUE TITLE
Document the different EXIF behaviors between iOS and Android camera components

### ISSUE THREAD

**Issue by yehudahkay** [expo/expo#1397]
```
 this.camera.takePictureAsync({base64: true}).then(data => {
                fetch('url', {
                    method: 'POST',
                    headers: {
                        Accept: 'application/json',
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        data: data.base64
                    })
                })
```
Testing on nexus 5x the picture is uploaded with the correct orientation that it was taken.

Testing on ipad with ios 9.3.5 and iphone x with ios 11 the picture is rotated 90 degrees.

I've tested now using the actual image not base64 and same issue. launchCameraAsync() works properly.

**Comment by yehudahkay** [comment]
It turns out this is an incredibly confusing issue related to the fact that the browser doesn't respect the exif data. There seems to be solutions for ios 

https://stackoverflow.com/questions/10307521/ios-png-image-rotated-90-degrees

not sure if that would be relevant for the camera?

I used a php solution

https://stackoverflow.com/questions/19456036/detect-exif-orientation-and-rotate-image-using-imagemagick

There is also a javascript solution

https://github.com/blueimp/JavaScript-Load-Image

Maybe the documentation can say something about all this?

**Comment by yehudahkay** [comment]
This seems to work but I think the camera should handle this, also I'm having issues with the camera not rotating for android?

```
if (data.exif.Orientation){
                    arr.push({rotate: -data.exif.Orientation})
                }
if (arr.length){
                    Expo.ImageManipulator.manipulate(data.uri, arr).then((data) => this.uploadPicture(data))
                }
                else {
                    this.uploadPicture(data)
                }
```

**Comment by yehudahkay** [comment]
Just discovered that ImageManipulator also reorients the ios picture when resizing, so again seems to me that the camera should do this. Too much confusion otherwise. For instance I originally tried to rotate and resize which again gives unexpected output because on resize it already rotates.

**Comment by ZackLeonardo** [comment]
I have tried different orientation setting is in app.json. The problem is still there. And exif.Orientation is always -90. It's correct for the digital camera itself, maybe this is because it doesn't get the information of rotation sensor.

**Comment by cruzach** [comment]
Hi- Tested this on a [snack](https://snack.expo.io/@charliecruzan/arrogant-banana) (forgive me, it's not super clean code since I repurposed a different snack), and didn't see this behavior. Also, [a similar issue](https://github.com/expo/expo/issues/2512) mentioning ImageManipulator stated the same behavior was solved in SDK 31. If you see this bug, please open up a new bug report with a repro, and we'll look into it 👍
