### ISSUE TITLE
[docs] MailComposer docs clarification required for Android

### ISSUE THREAD

**Issue by ldwight** [expo/expo#13977]
### Summary

MailComposer does not support HTML in Android

Currently, the doc says isHtml  is used to indicate "Whether the body contains HTML tags so it could be formatted properly. Not working perfectly on Android."

In fact, it does not work in Android at all.

Obviously, it would be better to fix it so that it did work in Android, but as this has been an issue for at least a year (https://forums.expo.dev/t/mailcomposer-html-content-android/40412), the documentation should reflect the sad reality.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/mail-composer/

**Comment by MattWeiler** [comment]
This is still an issue in 2024.

Is there a good reason why HTML emails can't be sent on Android?
