### ISSUE TITLE
Include stripe-react-native 0.2.0 in Expo 43

### ISSUE THREAD

**Issue by Brotakuu** [expo/expo#13979]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by Brotakuu** [comment]
0.1.5 contains important fix to <CardField> where it could not be dismissed. https://github.com/stripe/stripe-react-native/pull/337

0.2.0 fixes a common crash https://github.com/stripe/stripe-react-native/issues/391

**Comment by Legym** [comment]
Just wanted to post my experience as well.

https://github.com/stripe/stripe-react-native/issues/371

stripe-react-native 0.2.0 fixes the issue of validating payments. Currently customers are not able to submit payments using stripe-react-native if it is not on version 0.2.0.

**Comment by cruzach** [comment]
Hi! We will definitely upgrade this once we release SDK 43. In the meantime, you can use the most recent version of `stripe-react-native` in development with `expo-dev-client` and EAS Build
