### ISSUE TITLE
SecureStore - getItemAsync() returns unresolved Promise

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [expo/expo#13978]
### Summary

The same happens with [AsyncStorage](https://github.com/react-native-async-storage/async-storage/issues/604). Storing a key/value pair is working fine, while trying to access the saved value results in:

```js
Promise {
  "_U": 0,
  "_V": 0,
  "_W": null,
  "_X": null,
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ^0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```js
import * as React from 'react';
import { View } from 'react-native';
import { Button, TextInput } from 'react-native-paper';
import * as SecureStore from 'expo-secure-store';

async function saveValue(key, value) {
  await SecureStore.setItemAsync(key, value);
}

async function getValue(key) {
  let result = await SecureStore.getItemAsync(key);
  if (result) {
    return result;
  }
}

const SomeComponent = () => {
  const [value, setValue] = React.useState('');

  return (
    <View>
      <TextInput
        value={value}
        onChangeText={(value) => setValue(value)}
      />
      <Button
        onPress={() => saveValue('someKey', value)}
      />
      <Button
        onPress={() => console.log(getValue('someKey'))}>
        Get Value
      </Button>
    </View>
  );
};
```

**Comment by ide** [comment]
These are async functions. You need to await the promise.

**Comment by BunnyTheLifeguard** [comment]
> These are async functions. You need to await the promise.

Isn't that what `let result = await SecureStore.getItemAsync(key);` is supposed to do?

**Comment by ide** [comment]
Yes, but `getValue()` still returns a promise. You need to await the promise to get the value with which its fulfilled.

* promises: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
* async functions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#description
> Async functions always return a promise. If the return value of an async function is not explicitly a promise, it will be implicitly wrapped in a promise.
