### ISSUE TITLE
Failed to compile 

### ISSUE THREAD

**Issue by its-shubham2323** [expo/expo#13991]
### Summary

Failed to compile
D:/Signal/signal/node_modules/expo/AppEntry.js
Error: ENOENT: no such file or directory, open 'D:\Signal\signal\node_modules\expo\AppEntry.js'
This error occurred during the build time and cannot be dismissed.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, Web

### SDK Version (managed workflow only)

4.9.1

### Environment

Failed to compile
D:/Signal/signal/node_modules/expo/AppEntry.js
Error: ENOENT: no such file or directory, open 'D:\Signal\signal\node_modules\expo\AppEntry.js'
This error occurred during the build time and cannot be dismissed.

### Reproducible demo or steps to reproduce from a blank project

No

**Comment by brentvatne** [comment]
> Reproducible demo or steps to reproduce from a blank project

;)
