### ISSUE TITLE
Problem with react-native-maps

### ISSUE THREAD

**Issue by gustavomanolo** [expo/expo#13999]
### Summary

i'm using react-native-maps (working fine with Expo client), but i had to create a custom dev client because i need to use "react-native-fast-image", now when i create a custom dev client for Android (eas build --profile development --platform android) my map doesn't load, just loads a blank window.
![Screenshot_2021-08-10-14-53-06-506_com cityflag tampico inspector](https://user-images.githubusercontent.com/199295/128926320-e58a5af1-331c-47ca-a58e-7104ca658c7c.jpg)

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "^0.4.7",
"expo-updates": "~0.8.1",
"react-native-maps": "0.28.0",
"react-native-fast-image": "^8.3.7",

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.20.3 - ~/.nvm/versions/node/v14.17.3/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

`<MapView
        // minZoomLevel={5}
        onMarkerDeselect={() => {
          setFlagSelected(null);
        }}
        onPress={(e) => {
          if (Platform.OS === "android") {
            setFlagSelected(null);
          }
        }}
        showsMyLocationButton={false} // Android only
        moveOnMarkerPress={false} // Android only
        zoomControlEnabled={false} // Android only
        showsUserLocation={true}
        ref={mapRef}
        style={styles.map}
        customMapStyle={mapStyle}
        onRegionChangeComplete={(region) => {
          if (region.latitudeDelta <= 0.4) {
            if (loading === false) {
              setShowMapRefresh(true);
            }
          } else {
            // TODO: Display message to "increase zoom area"
          }
        }}
        onMapReady={_mapReady}
        initialRegion={initMapRegion}
        pitchEnabled={!loading}
        rotateEnabled={!loading}
        zoomEnabled={!loading}
        scrollEnabled={!loading}
      >
        {flags.map((flag, index) => (
          <Marker
            key={flag._id}
            coordinate={{
              latitude: flag.location.coordinates[1],
              longitude: flag.location.coordinates[0],
            }}
            pointerEvents="auto"
            tracksViewChanges={false}
            title={flag.flag_category_name}
            // description={flag.description}
            onPress={(e) => {
              // Android
              _showMarkerBottomSheet(flag);
            }}
            onSelect={(e) => {
              // iOS
              _showMarkerBottomSheet(flag);
            }}
          >
            {Platform.OS === "ios" && (
              <Image
                source={require("../../../assets/marker_location4.png")}
                style={{ width: 35, height: 35, marginBottom: 35 }}
              />
            )}
          </Marker>
        ))}
      </MapView>`

**Comment by brentvatne** [comment]
make sure it's configured properly. custom dev client requires same configuration as standalone apps: https://docs.expo.dev/versions/latest/sdk/map-view/#configuration

**Comment by gustavomanolo** [comment]
It's configured correctly, it was working perfectly before creating the dev-client also have in the Play Store, but once i created the custom dev client the map view went blank.

**Comment by tindery** [comment]
I'm having the same issue, did you manage to solve this?
