### ISSUE TITLE
imagemanipulator resize with height doesnt work

### ISSUE THREAD

**Issue by yehudahkay** [expo/expo#1400]
I tried on nexus 5x

`Expo.ImageManipulator.manipulate(image.uri, [{resize: {width: 2592}}]).then(image => {})
`
which worked. But

`Expo.ImageManipulator.manipulate(image.uri, [{resize: {height: 2592}}]).then(image => {})
`
Didn't change the image

**Comment by terribleben** [comment]
Hi, can you provide a [snack](https://snack.expo.io) that reproduces the issue?

**Comment by yehudahkay** [comment]
Hi @terribleben I tried using snack unfortunately it was unresponsive on my devices but perhaps you can get some mileage out of the snack I created https://snack.expo.io/Sk_hnMA8M

I tried this code locally and it seems that on both of my android and ios devices using {height: $height} resizes to a size close to the requested height but not exactly the requested height. For instance if I try height 1000 it resizes to 1055, width 1000 correctly resizes to width 1000. Using my original value of 2592 results in a height of 2647 while the width will be correct at 2592.
