### ISSUE TITLE
GIF is not animating on SDK 42 - iOS - Expo Publish and Apple Store 

### ISSUE THREAD

**Issue by ruiqbarbosa** [expo/expo#14002]
### Summary

GIF is not animating when using the published application on Apple Store (iOS). Using expo LAN instead works fine. On the other hand, in Android devices, everything seems fine (expo Lan and Play Store).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Steps to reproduce
1. Create a blank project.
2. Add a GIF image and test it in Expo LAN. It works as expected
3. Use expo publish command, or deploy to the Apple Store
4.  Test it on real devices
5. The GIF is not animating

### Demos
- Running on Expo Lan - Gif is animating:

https://user-images.githubusercontent.com/65962530/128936692-34a90050-2a41-4840-9401-f299dfcefd85.mp4

- Running by application published on Apple Store - Gif is not working: 

https://user-images.githubusercontent.com/65962530/128936709-eb0d0ad3-9e41-4b2f-85cc-d04a91251c75.mp4

**Comment by s3131212** [comment]
I encountered the same problem recently and solved it through `expo upgrade` (even when I was using SDK 42). It updated some dependencies and magically solved the problem.
Hope this helps.

**Comment by ruiqbarbosa** [comment]
@s3131212 Many thanks, that fixed the issue! I think the problem was in the _expo-asset_ library. Once it was updated to 8.3.3 version, the Gif started to work.
