### ISSUE TITLE
[expo-notifications] [iOS] Notifications.addNotificationResponseReceivedListener callback not finishing execution

### ISSUE THREAD

**Issue by thefinnomenon** [expo/expo#14004]
### Summary

When my app is in the background, receives an interactive notification, and the user selects one of the actions, it should trigger my NotificationResponseReceivedListener and execute its callback, posting the selected action to the server. This is exactly what happens on Android, but on iOS, it does not respect the asynchronous fetch call and only manages to log the fact that the callback was triggered. I figured it might be the Expo Go client so I created an Ad Hoc distribution with the dev-client and have the same issue.

Looking at the Apple resources, this is a normal use case. I think the completion handler for `userNotificationCenter(_:didReceive:withCompletionHandler:)` is not being handled correctly and being called prematurely.
https://developer.apple.com/documentation/usernotifications/handling_notifications_and_notification-related_actions
https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.6.0 - ~/.nvm/versions/node/v15.6.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.6.0/bin/yarn
      npm: 7.4.0 - ~/.nvm/versions/node/v15.6.0/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Initialize a managed Expo project.
2. Add interactive push notification code (register push notification token, setNotificationCategoryAsync and addNotificationResponseReceivedListener).
3. Add some logging and a fetch to the addNotificationResponseReceivedListener callback.
4. Build a standalone iOS app.
5. Open the app and then background it.
6. Send push notification to it and select an action.
7. This should trigger the addNotificationResponseReceivedListener callback but the fetch won't complete.

**Comment by cruzach** [comment]
Hi, can you share a repro instead of just the steps? I put those steps together in this snack and it seems to work fine: https://snack.expo.dev/@charliecruzan/14004

**Comment by thefinnomenon** [comment]
@cruzach Thanks for making the Snack. It works fine until you add the `opensAppInForeground: false` option,
`await Notifications.setNotificationCategoryAsync('my-id', [{identifier: 'id', buttonTitle: 'helloo', options: {opensAppToForeground: false}}])`

Now, if you schedule the push notification and background the app, the action will be console logged but the fetch never happens.

**Comment by cruzach** [comment]
I think this is an iOS limitation that `fetch` cannot be run while the app is backgrounded. For running network requests while the app is backgrounded, you'll need to use something like https://docs.expo.dev/versions/latest/sdk/background-fetch/

**Comment by thefinnomenon** [comment]
I have been reading through the iOS docs and it doesn't mention any limitations nor do they mention needing any special entitlements like `remote-notification` or `background-fetch`.

I replaced the fetch with an await on a timeout to test if the problem is specifically with fetch or with async/await in general.
- `opensAppToForeground: true` -> app is foregrounded, first log prints, waits, second log prints
- `opensAppToForeground: false` -> it only prints the first log

There is a note on this page about async,
https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter

> **Concurrency Note**
> You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:
>
> `optional func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse) async`

Here is a similar issue on SO.
https://stackoverflow.com/questions/64400085/alamofire-api-call-from-background-mode-from-usernotificationcenter-not-working

**Comment by cruzach** [comment]
Out of curiosity- do you see the same behavior if you just have that await on a timeout set to run after tapping a button? so:
- tap button
- immediately background app
- is the code in the timeout executed?

**Comment by thefinnomenon** [comment]
https://snack.expo.dev/@thefinnomenon/14004
Server logs -> https://glitch.com/edit/#!/destiny-abundant-cord?path=README.md%3A1%3A0

I threw the timeout test into schedulePushNotification() and I can't really say if it is handled correctly because I can't see the console logs till I foreground the app again and when I do that, it seemingly executes the rest of the code. I added a fetch post test to see the exact timing of when the fetch is executed and in both cases it is when the app is finally foregrounded again.

**Comment by thefinnomenon** [comment]
@r0bs Unfortunately I moved away from this project without resolving this issue. I'm still not 100% sure if this is an iOS limitation or not but it works in Android.

**Comment by r0bs** [comment]
Thanks for your quick response. 

I build an example and also modified yours. 

What I did observe is that there is only a loose connection between the _AppState_ being _inactive_ or _background_ and the execution of async functions: It seems in most cases async functions are executed for some time (30s maybe) after the _AppState_ changed to _background_. 

Also there seems to be a connection to the number of components in the app (the less components, the longer async actions are executed when a NotificationResponseReceivedListener is triggered).

**Comment by thefinnomenon** [comment]
Good to know and yeah I couldn't get it consistent enough for my use case. Pretty annoying because my Android users could respond through the push notification action but on iOS I had to foreground the app in order to POST their response. Let me know if you manage to reliably send a POST off of an interactive push notification.
