### ISSUE TITLE
expo-av Audio not sending headers when using GET request for audio file

### ISSUE THREAD

**Issue by AlexThomas90210** [expo/expo#14019]
### Summary

I am trying to play a sound from a protected resouce on cloudfront, I need to send the cookie header with the request to give permissions to access the site, when adding he headers in the source I can see they are not being sent with the request

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.12.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.11.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /Users/alex/.rvm/gems/ruby-2.5.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

        let { sound: playbackObject } = await Audio.Sound.createAsync({ 
            uri: getUrlForTrack(trackData.getTrack),
            headers: {
                "test": 'yes',
                "cookie": cookie,
                'Authorization': 'Bearer xyz'
            }
         },{
             rate: 1,
             positionMillis: audioPlayerData.audioPlayer.currentlyAt * 1000,
             shouldPlay: audioPlayerData.audioPlayer.isPlaying
         })

**Comment by varrios** [comment]
hey, did you manage to find the solution? I encountered similar problem when trying to authenticate with HTTP Basic auth
