### ISSUE TITLE
Expo Svg (Translate)?

### ISSUE THREAD

**Issue by mfrknv** [expo/expo#1401]
Expo svg does not support transfrom translate.
` <G id="Canvas" transform="translate(488 -1378)">` not working?

**Comment by terribleben** [comment]
Hello! Expo SDK 23-25 use react-native-svg version 5.5.1.

Please follow our issue template (i.e. tell us something about your environment, your expected behavior, observed behavior, and ideally provide a reproducible demo) and someone might be able to take a look.
