### ISSUE TITLE
Dev-Client Crashes When Building JS Bundle After Adding Native Package + Config Plugins

### ISSUE THREAD

**Issue by amitferman** [expo/expo#14021]
### Summary

I am trying to use Bluetooth Classic on iOS with [react-native-bluetooth-classic](https://github.com/kenjdavidson/react-native-bluetooth-classic) along with a basic config plugin I wrote. Since running 'expo add react-native-bluetooth-classic', when I create a dev-client and scan the QR code, the bundle crashes immediately without errors.

GitHub: https://github.com/amitferman/bluetooth-classic-demo

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

expo-dev-client: 0.4.7
expo: 42.0.3
eas-cli: 0.23.0

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

expo init bluetooth-classic-demo
cd bluetooth-classic-demo
expo add expo-dev-client
expo add react-native-bluetooth-classic
.......At this point the dev client can't open the bundle
Then I added in bluetooth-classic-plugin.js to configure info.plist
.......Same behavior

### Stacktrace (if a crash is involved)

[xcode-build-dff54d2e-3ab9-4b63-8dfb-5dc758d178bf (1).log](https://github.com/expo/expo/files/6972110/xcode-build-dff54d2e-3ab9-4b63-8dfb-5dc758d178bf.1.log)

**Comment by amitferman** [comment]
After working on this further, this does not seem to be caused by a bug on Expo. Closing issue.

**Comment by vivek-pai** [comment]
Hey, let me know if you happen to get classic working...I'm currently exploring bluetooth with expo and ran into your posts.

**Comment by amitferman** [comment]
I have moved away from this recently and haven't found a solution. I tried writing a config plugin to modify the info.plist property specified in the react-native-bluetooth-classic documentation, but this had no impact when I ran the application on the dev client. (Though when I introspected the info.plist props it seemed to have set the property correctly.) I suspect Expo doesn't allow modifying the specific plist property, though I may be wrong. I can send you the plugin if you'd like (just a single JS file) but let me know if you make any progress on this since I am still curious.

**Comment by vivek-pai** [comment]
Yeah, if you could...that would be great! I ran into the same issue that just adding the package to package.json resulted in a crash on startup - I suppose the plugin is necessary.

**Comment by amitferman** [comment]
Sure. I was having the same issue. Here's my code.
bluetooth-classic-plugin.js in project root:
const withBLC = (config) => {
  // Ensure the objects exist
  if (!config.ios) {
    config.ios = {};
  }
  if (!config.ios.infoPlist) {
    config.ios.infoPlist = {};
  }
  config.ios.infoPlist.UISupportedExternalAccessoryProtocols = ['com.apple.m1'];
  return config;
};

module.exports = withBLC;
`
app.json (snippet):
`
"plugins": [
      "./bluetooth-classic-plugin"
    ]
`
If you run `expo config --type introspect` after adding this config plugin it appears that the infoPlist prop contains the correct key/value for UISupportedExternalAccessoryProtocls, but it still crashed on startup for me. Please let me know if you get this working or if you have any ideas!

**Comment by amitferman** [comment]
Aha! This works. What was I thinking 7 days ago 😆. The complete plugin is:
const withBLC = (config) => {
  // Ensure the objects exist
  if (!config.ios) {
    config.ios = {};
  }
  if (!config.ios.infoPlist) {
    config.ios.infoPlist = {};
  }
  config.ios.infoPlist.UISupportedExternalAccessoryProtocols = ['com.apple.m1'];
  config.ios.infoPlist.NSBluetoothPeripheralUsageDescription = "Some Description (PeripheralUsage)"; 
  config.ios.infoPlist.NSBluetoothAlwaysUsageDescription = "Some Description (AlwaysUsage)";
  return config;
};

module.exports = withBLC;

**Comment by vivek-pai** [comment]
Sweet. Works for me, too! Good job.

**Comment by amitferman** [comment]
@vivek-pai You can also use ['with-rn-Bluetooth-classic'](https://www.npmjs.com/package/with-rn-bluetooth-classic) and it might be more convenient.
