### ISSUE TITLE
Exponent Server SDK Ruby gem is outdated

### ISSUE THREAD

**Issue by pablonahuelgomez** [expo/expo#1402]
First of all, thanks for the great work you're doing with Expo.

Currently, the Ruby SDK is outdated and there're some issues to look into,
see: https://github.com/expo/exponent-server-sdk-ruby/issues

I've just submitted a PR to refactor the code and use the latest response
structures that Expo is offering, see:  https://github.com/expo/exponent-server-sdk-ruby/pull/8

**Comment by ide** [comment]
We are looking for one or two maintainers for the gem and are using it in production. Is this something you would be interested in doing? https://github.com/expo/exponent-server-sdk-ruby/issues/7

**Comment by pablonahuelgomez** [comment]
Hi @ide, thanks for your quick response. And yes, I would like to work on the maintenance of the gem.
