### ISSUE TITLE
glView.createCameraTexture throws error in bare workflow

### ISSUE THREAD

**Issue by DominikScholz** [expo/expo#14031]
### Summary

I want to get access to a camera view's framebuffer in a bare workflow project like in this example: [GLCameraScreen.tsx](https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/GL/GLCameraScreen.tsx). It works using the managed workflow but with the bare workflow the promise from the `createCameraTexture` call always throws the following error: [GLObjectManagerModule.java#L103](https://github.com/expo/expo/blob/master/packages/expo-gl/android/src/main/java/expo/modules/gl/GLObjectManagerModule.java#L103)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

 Expo CLI 4.10.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
      npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7395685
    npmPackages:
      react: 17.0.1 => 17.0.1
      react-native: 0.64.1 => 0.64.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Here is a Snack of the working, managed version: [testCameraTexture](https://snack.expo.dev/@thraein/bf50dd) (adapted from [GLCameraScreen.tsx](https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/GL/GLCameraScreen.tsx), to use new permission system & catch promises)

Running this code from Snack as managed project results in the correct camera preview with inverted colors.
When running as a bare project (using react-native-unimodules), it throws the `[Error: ExponentGLObjectManager.createCameraTextureAsync: Expected a CameraView]` error, and returns in line 75 of the GLCameraScreen.tsx due to the camera texture being null.

**Comment by wkozyra95** [comment]
I tested that by downloading snack -> expo eject -> build and everything works correctly.

**Comment by DominikScholz** [comment]
thank you very much!, you are right it worked with ejecting, so I must have made an error during the creation of the bare workflow
