### ISSUE TITLE
Multiple deep links do not work on Android

### ISSUE THREAD

**Issue by pr0da** [expo/expo#14032]
### Summary

Standalone build (built with EAS) only supports the first configured deep link, every other intent filter entry is ignored, and won't end up in the generated `AndroidManifest.xml`. Expected behavior would be: every configured deep link, should be end up as a supported link.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.17.0 - ~/.nvm/versions/node/v12.14.1/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-30 | Google Play Intel x86 Atom
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Add multiple intent filters under `expo.android.intentFilters` in `app.json`, eg.:

```
"intentFilters": [
    {
      "action": "VIEW",
      "data": {
        "scheme": "https",
        "host": "share.example.app"
      },
      "category": ["BROWSABLE", "DEFAULT"]
    },
    {
      "action": "VIEW",
      "data": {
        "scheme": "https",
        "host": "share-alternative.example.app"
      },
      "category": ["BROWSABLE", "DEFAULT"]
    }]
```

2. Create a standalone build with EAS (distribution does not really matter, can be store, internal, internal + development client)

3. Test the configured deep links, only the first one will open the app. You can also check the "Advanced / Open by default / Supported links" in the "App info", it only contains the first deep link.

**Comment by pr0da** [comment]
Worked around by grouping the intent filters differently, the following works as expected:

```
"intentFilters": [
    {
      "action": "VIEW",
      "data": [{
        "scheme": "https",
        "host": "share.example.app"
      },  {
        "scheme": "https",
        "host": "share-alternative.example.app"
      }],
      "category": ["BROWSABLE", "DEFAULT"]
    }]
```

**Comment by EmmanuelSkapple** [comment]
@pr0da in you app.json, you have the line expo.scheme ? or only the expo.android.intentFilters?

**Comment by pr0da** [comment]
Yes, schema was also set.
