### ISSUE TITLE
expo-clipboard throwing undefined is not an object (evaluating '_expoClipboard.default.setString')

### ISSUE THREAD

**Issue by alejandrosaldarriagaGL** [expo/expo#14049]
### Summary

When you use the method:

`Clipboard.setString(url)`

You get:

`undefined is not an object (evaluating '_expoClipboard.default.setString')`

SDK 42

Tested on android

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.22.1/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

yarn add expo-clipboard

include it in a file

`import Clipboard from 'expo-clipboard'`

use it

`onPress={() => Clipboard.setString(url)}`

Error shows up

**Comment by cruzach** [comment]
You need to import with `import * as Clipboard from 'expo-clipboard';`, see the docs and the example there https://docs.expo.dev/versions/latest/sdk/clipboard/

**Comment by ajohnson1031** [comment]
I figured out that Clipboard.default.setString(string); works.
