### ISSUE TITLE
Expo FileSystem createDownloadResumable not working 

### ISSUE THREAD

**Issue by kaulsalil88** [expo/expo#1405]
### Environment

https://exp-xde-diagnostics.s3.amazonaws.com/kaulsalil88-9a29564a-d781-4094-a300-dcf63770b2a0.tar.gz.

"expo": "^21.0.0",
"expo-env": "^1.1.0",
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz"
My App has been detached from expo

### Steps to Reproduce

(Write your steps here:)

1. Trying to download audio from  using createDownloadResumable its failing . When i use downloadAsync its working as expected .

### Expected Behavior

Expected the createDownloadResumable to download the audio

### Actual Behavior

It threw an exception .download progress is -243
2018-02-09 20:00:42:857 hcl-concerts[18449:304921] 2018-02-09 20:00:42.857 [info][tid:com.facebook.react.JavaScript] error in downloadSongUpdateProgress
2018-02-09 20:00:42:861 hcl-concerts[18449:304921] 2018-02-09 20:00:42.861 [error][tid:com.facebook.react.JavaScript] { [Error: Unable to save file to local URI]
  line: 6255,
  column: 24,
  sourceURL: 'http://10.1.202.18:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=/Users/ttn/WebstormProjects/snf-react-native-app/hcl-concerts-react-native/node_modules/expo/tools/hashAssetFiles',
  framesToPop: 1,
  code: 'E_UNABLE_TO_SAVE',
  nativeStackIOS: 
   [ '0   hcl-concerts                        0x00000001087d77c6 RCTJSErrorFromCodeMessageAndNSError + 134',
     '1   hcl-concerts                        0x0000000108730108 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.216 + 184',
     '2   hcl-concerts                        0x00000001082943c2 __132-[EXFileSystem _downloadResumableCreateSessionWithUrl:withScopedPath:withUUID:withOptions:withResumeData:withResolver:withRejecter:]_block_invoke.298 + 418',
     '3   hcl-concerts                        0x000000010828726b -[EXDownloadDelegate URLSession:downloadTask:didFinishDownloadingToURL:] + 155',
     '4   CFNetwork                           0x0000000112aec0b2 __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke + 38',
     '5   Foundation                          0x000000010c85e22f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7',
     '6   Foundation                          0x000000010c85e091 -[NSBlockOperation main] + 68',
     '7   Foundation                          0x000000010c85c54e -[__NSOperationInternal _start:] + 778',
     '8   libdispatch.dylib                   0x000000011420d33d _dispatch_client_callout + 8',
     '9   libdispatch.dylib                   0x00000001142129f3 _dispatch_block_invoke_direct + 592',
     '10  libdispatch.dylib                   0x000000011420d33d _dispatch_client_callout + 8',
     '11  libdispatch.dylib                   0x00000001142129f3 _dispatch_block_invoke_direct + 592',
     '12  libdispatch.dylib                   0x0000000114212783 dispatch_block_perform + 109',
     '13  Foundation                          0x000000010c85855c __NSOQSchedule_f + 342',
     '14  libdispatch.dylib                   0x000000011420d33d _dispatch_client_callout + 8',
     '15  libdispatch.dylib                   0x00000001142185f9 _dispatch_main_queue_callback_4CF + 628',
     '16  CoreFoundation                      0x0000000113365e39 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9',
     '17  CoreFoundation                      0x000000011332a462 __CFRunLoopRun + 2402',
     '18  CoreFoundation                      0x0000000113329889 CFRunLoopRunSpecific + 409',
     '19  GraphicsServices                    0x000000011558d9c6 GSEventRunModal + 62',
     '20  UIKit                               0x000000010f40f5d6 UIApplicationMain + 159',
     '21  hcl-concerts                        0x000000010813ab1f main + 111',
     '22  libdyld.dylib                       0x0000000114087d81 start + 1',
     '23  ???                                 0x0000000000000001 0x0 + 1' ],
  userInfo: { NSLocalizedDescription: 'Unable to save file to local URI' },
  domain: 'RCTErrorDomain' }
![simulator screen shot - iphone 8 plus - 2018-02-09 at 20 01 11](https://user-images.githubusercontent.com/8721680/36032561-6d2dce16-0dd4-11e8-8bd0-6c131fe9f69b.png)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
https://github.com/kaulsalil88/ExpoDownloadDemo/blob/master/index.js
my method is the download method . Please help

**Comment by fxfactorial** [comment]
Hi, I will try to reproduce and report back

**Comment by kaulsalil88** [comment]
Hi fxfactorial let me know if i can provide further info . will try updating my project to API to level 22 and report the findings

**Comment by kaulsalil88** [comment]
One of my collegues had this  code working on expo API level 22

**Comment by kaulsalil88** [comment]
@fxfactorial  please close this if this has been assigned to you turns out its an regression bug please
refer https://github.com/expo/expo/issues/739
