### ISSUE TITLE
Screencapture does not prevent screen recording in Video full screen

### ISSUE THREAD

**Issue by swapyhacker** [expo/expo#14055]
### Summary

in my app i have to prevent my video so that user cannot take screen shots and also cannot record video so i used usePreventScreenCapture() hook its working fine everywhere but in full screen mode i can record screen easily please resolve this issue 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

Expo CLI 4.4.8 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      npm: 7.14.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

`<div data-snack-id="@swapy_singh/video" data-snack-platform="web" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#F9F9F9;border:1px solid var(--color-border);border-radius:4px;height:505px;width:100%"></div>
<script async src="https://snack.expo.dev/embed.js"></script>`

**Comment by byCedric** [comment]
Hi @swapyhacker, thanks for the issue report. Unfortunately, I can't reproduce this issue using both the example for `expo-av` and `expo-screen-capture` ([here](https://snack.expo.dev/@bycedric/expo-issue-14055)). In this Snack, I can't take a screenshot when the video is stopped, played and in fullscreen. Could you provide a repro where the issue occurs?

**Comment by EvanBacon** [comment]
Duplicate https://github.com/expo/expo/issues/10834
