### ISSUE TITLE
[docs] expo/packages/expo-secure-store/README.md leads to deprecated package

### ISSUE THREAD

**Issue by tomasikp** [expo/expo#14054]
### Summary

Installation in bare react native projects links to deprecated `react-native-unimodules`

### Link to the related docs page

https://github.com/expo/expo/blob/master/packages/expo-secure-store/README.md

**Comment by byCedric** [comment]
Hi @tomasikp, thanks for mentioning this! I'm combining this issue into #14057, let's continue there.
