### ISSUE TITLE
expo-secure-store requires @unimodules/core (deprecated)

### ISSUE THREAD

**Issue by federicomia** [expo/expo#14057]
### Summary

Import of ExpoSecureStore in bare react native projects leads to error (unable to resolve module @unimodules/core). However @unimodules/core is deprecated and refers to expo-modules-core which I have added to the project. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.2 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.20.3 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 31
        Build Tools: 29.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.1 => 0.64.1 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- yarn add expo-modules-core
- yarn add expo-secure-store
- npx pod-install
- import from expo-secure-store

**Comment by valeb7** [comment]
Same issue here. +1

**Comment by ptsimpso** [comment]
I'm also running into this issue. @byCedric does the expo-secure-store actually require us to install unimodules as described in https://docs.expo.dev/bare/installing-unimodules/ for bare react-native projects?

Because if so, the documentation described at that link does not seem to be compatible with react-native 0.65.1. When I make the prescribed changes to the AppDelegate files, I get a few errors.
