### ISSUE TITLE
ImageManipulator on Android rescales image to device screen size on invoking

### ISSUE THREAD

**Issue by randomjunk** [expo/expo#1406]
### Environment

Seen on various Android devices, HTC One M9, Galaxy S8, S5

### Steps to Reproduce

```
const { width: pWidth, height: pHeight, uri} = await this.camera.takePictureAsync();

const { width, height } = await ImageManipulator.manipulate(
      uri,
      [ { rotate: 90 } ],
      { format: 'jpeg'},
    );

console.log("IMG:: ", pWidth, pHeight, width, height);
```

On HTC One M9 this results in:

    IMG:: 3456 4608 1152 864

so image is now 1/4 the resolution.

### Expected Behavior

Image should be the same size unless I resize it (consistent with behaviour on iOS).
ie:

    IMG:: 3456 4608 4608 3456

### Why this is happening…

Looking at the code expo does:
```
ImageLoader.getInstance().loadImageSync(decoded,
          new DisplayImageOptions.Builder()
              .cacheOnDisk(true)
              .build());
```

The default behaviour on ImageLoader is to apply `ImageScaleType.IN_SAMPLE_POWER_OF_2` to target the device screen size, which is what we see happening.

This would need to be configured with `ImageScaleType.NONE` to prevent this from happening.

### Demo (on Android)

https://snack.expo.io/S1rU0o38z

**Comment by aalices** [comment]
Thanks for finding the bug and the solution, fixing!

**Comment by ken0x0a** [comment]
Hello,

Is this solved?

My code was working fine @ ios before, but now I need to resize before crop @ ios (development environment & using Expo Client app).

Is this related to this issue?

My dependencies are here,

```json
    "expo": "32.0.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.3.tar.gz",
```

I didn't upgrade "expo" version, but upgrade Expo client app on iPhone.

**Comment by ken0x0a** [comment]
```ts
```

**Comment by ken0x0a** [comment]
```ts
// before
await ImageManipulator.manipulateAsync(
      image!.url!,
      [{ crop: { ...realOffset, ...trimSize } }],
      {
        format: 'jpeg',
        compress: 1,
      },
    )
// now
await ImageManipulator.manipulateAsync(
      image!.url!,
      [
        { resize: { width: image.width, height: image.height } },
        { crop: { ...realOffset, ...trimSize } },
      ],
      {
        format: 'jpeg',
        compress: 1,
      },
    )
```

**Comment by ken0x0a** [comment]
I'm sorry if I did something about `assign` or `unassign`. 
I don't know where I tapped.
That's something unintended action.
I assume I don't have assign or unassign,.
