### ISSUE TITLE
expo hangs on splash when run with expo start --no-dev --minify

### ISSUE THREAD

**Issue by raphyz** [expo/expo#14086]
### Summary

The Expo app hangs on splash screen when run with expo start --no-dev --minify
When run with npm start it works OK

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.4.0 - /usr/local/bin/node
      npm: 7.20.6 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I started a new project using : expo start projname
then I cd to it and run :expo start --no-dev --minify
I go to the internal expo url:  exp://my_ip:19000 on my android device
and I hang on the splash screen
If I reload the app from the expo reload option (when rolling the screen on my device) it will reload and work well

**Comment by cruzach** [comment]
This happens with a brand new expo project created with `expo init`?

**Comment by raphyz** [comment]
yes!

**Comment by cruzach** [comment]
What version of Expo Go? Does the same behavior happen running on a different device or simulator?

**Comment by raphyz** [comment]
The Expo Go I use is from 6.2021.  When I tried to run it on a different device it worked, so I start to think it might be an issue with my first device. I will close the case.
