### ISSUE TITLE
TaskManager may be asking for more entitlements than necessary (location)

### ISSUE THREAD

**Issue by jedahan** [expo/expo#14098]
### Summary

https://github.com/expo/expo/blob/master/packages/expo-task-manager/plugin/src/withTaskManager.ts#L10-L13

With SDK42, we want to track receiving notifications in the background. This uses the TaskManager, which adds 'location' to the UIBackgroundModes requested entitlement.

Is the location entitlement necessary? App store reviewer is (rightfully) asking why we need this, and "trust us we don't use it" is not the best response we can give.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.4 - /opt/homebrew/opt/node@14/bin/node
      npm: 6.14.14 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

```

### Reproducible demo or steps to reproduce from a blank project

Init a new app, and add the following to App.{js,tsx}

```
import * as TaskManager from 'expo-task-manager'

TaskManager.defineTask('notification_received', ({ data, error }) => {
  if (error) return console.error(error)

  console.log({event: 'notification_received', ...data })
})

useEffect(() => {
  Notifications.registerTaskAsync('notification_received')
  return () => void Notifications.unregisterTaskAsync('notification_received')
}, [])
```

Build, and observe that the location background mode has been requested, even though location services are not being used.

**Comment by cruzach** [comment]
Yeah, we should probably only add these if you explicitly say to

separately- @EvanBacon do you think the `UIBackgroundModes` should go into each individual package (i.e. `expo-location`, `expo-background-fetch`)?

**Comment by EvanBacon** [comment]
Sorry about that, it'll be fixed in the next version.
