### ISSUE TITLE
Google Play Services 9.8.0 alternatives

### ISSUE THREAD

**Issue by jSkrills** [expo/expo#1409]
### Environment

I have recently detached to expoKit in hopes to do some app inviting via firebase dynamic links or something similar. I am having issues getting a clean build when targeting and deploying to an android device via Android Studio.  I am attempting to use the React Native Firebase library to do this. Here are the versions of the key players: 

"expo": "^24.0.2",
"firebase": "^4.2.0",
"react": "16.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
"react-native-firebase": "^3.2.4",

### Steps to Reproduce
When following the [rnfirebase docs](https://rnfirebase.io/docs/v3.2.x/getting-started) I get to a place when configuring for the android platform where they "and the o.g. [firebase docs](https://firebase.google.com/docs/dynamic-links/android/receive), in case I wanted to just omit rnfirebase altogether" want me to use this: (compile "com.google.android.gms:play-services-base:11.6.0" )in the  android/app/build.gradle file.

As you can imagine Android Studio barks at me about a version mismatch and I am left with a choice to move everything up or down. There are more details about the exact exception messages that I was seeing and what I have tried at the bottom of this thread: https://github.com/invertase/react-native-firebase/issues/446. 

I have also unsuccessfully tried the workaround here: https://github.com/expo/expo/issues/799

I understand that expo is relying on this specific version of the services. I would love to get to a place where I can use firebase dynamic links in any capacity.  

I was hoping someone may be able to shed some light on possible workarounds or paths to get this done. If it basically just can't be done for whatever reason I'd also be interested in hearing other possible popular suggestions used with your tooling to do invites and notifications. Also if it can't be done I'd obviously like to know when, if ever, to expect more up to date usage with the google play services pieces.

**Comment by JakeNolan** [comment]
@jesseruder @fxfactorial Is there anything else that I can provide you guys?

**Comment by EvanBacon** [comment]
RNFirebase has a couple big collision errors with Expo. I would recommend you use [`expo-firebase`](https://github.com/evanbacon/expo-native-firebase) which is a version that works with Expo.
