### ISSUE TITLE
Inconsistent asset loading between iOS and Android EAS Builds

### ISSUE THREAD

**Issue by jedahan** [expo/expo#14107]
### Summary

I expect to be able to see textures on meshes in a release android application, like we do with the release iOS application. Textures load fine in Expo Go on both platforms.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

```
Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.4 - /opt/homebrew/opt/node@14/bin/node
      npm: 6.14.14 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Check out https://github.com/jedahan/expo-sdk42-expo-gl/tree/main

Create iOS and Android builds with `npm run build`

Note that the globe is textured on iOS, but not Android

**Comment by jedahan** [comment]
Updated the example to be in the main branch, one file: 

Snack here: https://snack.expo.dev/@jedahan-reaktor/gl-texture-loading

The bug shows up on the web too, but I wonder if its for a different reason...

**Comment by cruzach** [comment]
This only happens inside of the `Drawer` navigator, right @jedahan ?

**Comment by jedahan** [comment]
It happens even if it is outside the `Drawer` navigator, *as long as `createDrawerNavigator` is called somewhere in the app.

**Comment by jedahan** [comment]
It might be that the Drawer uses react-native-reanimated, and something funky is happening there
