### ISSUE TITLE
Google Sign In SHA1 signature from Standalone App [Windows]

### ISSUE THREAD

**Issue by towfiqi** [expo/expo#1410]
I have integrated google maps in my expo project. To integrate the map properly, I am following this doc:
https://docs.expo.io/versions/latest/sdk/map-view.html

The thing is, In step 9, I am asked to run this command:

`keytool -list -printcert -jarfile growler.apk | grep SHA1 | awk '{ print $2 }'`

But running the following command throws this error in terminal: 
 `Error: 'grep' is not recognized as an internal or external command`

So can you guys kindly update the doc with windows equivalent solution for step 9?

Thanks

**Comment by towfiqi** [comment]
Found the solution in Expo forum, kindly add it to the doc:
`keytool -list -printcert -jarfile myapp.apk`

**Comment by fxfactorial** [comment]
Hi @towfiqi
