### ISSUE TITLE
camera on ios rotates image in landscape

### ISSUE THREAD

**Issue by yehudahkay** [expo/expo#1411]
Thank you I really think the framework has a lot of promise and it is fascinating working with it.

I set up a snack with the camera code from https://docs.expo.io/versions/latest/sdk/camera.html. On iOS when you try to turn the device from portrait to landscape the camera image is oriented wrong. Android is not having this issue.

https://snack.expo.io/HkFt896If

In general I don't seem to be able to use the camera component as it seems buggy on ios. Another bug I filed is https://github.com/expo/expo/issues/1397 which got labeled as docs but it really should be labeled as a bug i think.

**Comment by andrzey** [comment]
I experience it to. No matter in what orientation I take a picture, the exif-tag says the Orientation is -90. Any idea how to save the image with the correct orientation?

**Comment by yehudahkay** [comment]
Check this out https://github.com/expo/expo/issues/1397

**Comment by andrzey** [comment]
@yehudahkay I saw the post earlier but didn't quite understand it until now! But do you know if the react-native Cameraroll respexts exif data when it saves images to the cameraroll? Because either way I am manipulating the exif.orientation-data, the orientation doesn't change.

**Comment by yehudahkay** [comment]
@andrzey I think this might be an actual bug related to what your orientation setting is in app.json. I didn't have time to test it yet so I closed the issue. Maybe you can figure it out and repost as a new issue. Let me know.

**Comment by ZackLeonardo** [comment]
@yehudahkay I have tried different orientation setting is in app.json. The problem is still there.

**Comment by PavelPolyakov** [comment]
🤚,

I also experienced that on iOS my photos are stored horizontally, so I've applied this image manipulation trick:
```
photo = await ImageManipulator.manipulate(
                      photo.uri,
                      [{ rotate: -photo.exif.Orientation }],
                    );
                    console.log(photo);
                    await CameraRoll.saveToCameraRoll(photo.uri);
```

And the image is rotated, but it's still stored as normal horizontal photo where width > height. What have I missed?

Thanks!

**Comment by yehudahkay** [comment]
@PavelPolyakov what happens if you resize without rotate? I think it rotates in that case...
