### ISSUE TITLE
bundledNativeModules.json is not tracking the correct stripe-react-native library

### ISSUE THREAD

**Issue by simonshout** [expo/expo#14113]
### Summary

When using [stripe-react-native](https://github.com/stripe/stripe-react-native) it is expected that the `bundledNativeModules.json` is managing the dependency version correctly. 

Currently the `bundledNativeModules.json` is tracking the library `stripe-react-native` and not `@stripe/stripe-react-native`

This issue was discovered when trying to sync dependabot versions with expo managed versions.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

42

### Environment

diagnostics not needed for this issue

### Reproducible demo or steps to reproduce from a blank project

install expo and view the `bundledNativeModules.json` under `node_modules/expo/*`
look for `stripe-react-native`

**Comment by cruzach** [comment]
We are actually tracking the correct version on [the sdk-42 release branch](https://github.com/expo/expo/blob/sdk-42/packages/expo/bundledNativeModules.json), so I'm not sure why `expo install` isn't referring to that one if your project is on SDK 42

**Comment by cruzach** [comment]
fixed in https://github.com/expo/expo/commit/88e1b75bc7b96b0aea0cd43add796d64a86f75bb
