### ISSUE TITLE
ImagePicker modal does not open in correct view dimensions

### ISSUE THREAD

**Issue by max-frai** [expo/expo#14129]
### Summary

When I launch: `ImagePicker.launchImageLibraryAsync` fullscreen modal opens on ios. But it's overlapping default ios header and does not have margin from top by default. When I tap something on the screen, it "jumps" to correct position.

![img](https://user-images.githubusercontent.com/24208746/130216032-8d357eea-6564-4a72-a390-23435e085b3f.jpg)

https://user-images.githubusercontent.com/24208746/130216040-1413ec53-e730-47bd-abd6-3d157f9ce471.MOV

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.3

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.0 - /usr/local/bin/node
      npm: 7.19.1 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.3 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
import * as ImagePicker from "expo-image-picker";

const Test = () => {
    useEffect(() => {
        async logic() {
          await ImagePicker.launchImageLibraryAsync({
                mediaTypes: ImagePicker.MediaTypeOptions.Videos,
                allowsEditing: true,
                quality: 1,
            });
        }
        logic();
    }, []);
    return <View></View>;
}

export default Test;
```

**Comment by byCedric** [comment]
Hi @max-frai! We've seen this before on iOS 15 in other apps as well. What iOS version are you using?

**Comment by max-frai** [comment]
@byCedric Hello! I made a minimum repo with this problem, you can try it out also: https://github.com/max-frai/ExpoModalsTest

Here is my devices where it fails:
iPhone 12 Pro (ios 15.0, also problem was on 14.7)
iPhone 10 (ios 14.7.1)

**Comment by cruzach** [comment]
I think this is at least in part due to https://github.com/expo/expo/pull/12897

**Comment by cruzach** [comment]
Ah, but looks like this should be fixed in https://github.com/expo/expo/pull/14068/. It'll be available in the next SDK release, or you can use EAS Build to pull those changes in now
