### ISSUE TITLE
React native maps crashes on android with EAS builds

### ISSUE THREAD

**Issue by chairmansir** [expo/expo#14135]
### Summary

I have been using MapView from react-native-maps for a while now but ever since we moved towards EAS for our standalone builds, the map simply does not load and even crashes the app after about 40 seconds of being initialised. Within that 40 second period all activities on the app lags: button taps, navigating to another screen, panning on the map itself. This doesn’t happen when the binary is built using expo build. MapView works normal when used on Expo Go.

I am currently using version 0.28.0 of react-native-maps, but the same issue occurs on previous and alpha versions of the package

I have attached a recording below of this behaviour
[https://drive.google.com/file/d/1Zedt9SM881ZGVSoKHHUnr3MCABhSGqpy/view?usp=sharing](url)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Running the most basic example of MapView and building using EAS for the android platform

`<MapView provider={PROVIDER_GOOGLE} style={styles.modalStyle} />`

**Comment by brentvatne** [comment]
you need to configure it properly. run `adb logcat` to see your logs with your device connected and you'll see more info about what is misconfigured. read the docs carefully :)

**Comment by MobinAkhter** [comment]
Had the same problem. 
If you are intending to publish app on Play Store then it should be good because it works for me on production build (which I installed from google play as internal tester).
Make sure to add Expo SHA1 fingerprint to the API key rather than adding it from google play console.

**Comment by SciupaCodice** [comment]
I have problems with react-native-map-clustering, I published my app on google play store and It works fine, but for some devices It crashes when opened the map. I'm using "react-native-map-clustering": "^3.4.2" and "expo-location": "~17.0.1".

import MapView from "react-native-map-clustering";
<MapView 
  ref={mapRef}
  style={[styles.map]}
  initialRegion={mapRegion}
  customMapStyle={mapStyles}
  showsMyLocationButton={true}
  showsUserLocation={true}
  provider="google"
  showsBuildings={false}
  followsUserLocation={true}
  radius={8}
><MapView>
