### ISSUE TITLE
React Navigation official

### ISSUE THREAD

**Issue by gtaylor44** [expo/expo#1413]
Could you let me know when Expo 26 is being released.

React Navigation finally went out of beta and there's a feature that I'm dying (not literally) to use. Tab event listeners should* finally be available.

Or is it ok to use the latest React Navigation version with Expo 25? 

https://github.com/react-navigation/react-navigation/issues/51

**Comment by LouisJS** [comment]
Well. It has nothing to do with Expo. just update your 'react-navigation' dependency.

**Comment by nikki93** [comment]
Yeah you can use the latest one with Expo!
