### ISSUE TITLE
expo permission always denied after expo build 

### ISSUE THREAD

**Issue by rafalWili** [expo/expo#14137]
### Summary

expo permission is denied after I push my changes to the "expo build" - to google play - internal test environment. 
It working fine when I use development mode "yarn start" but after "expo publish" it won't open the camera or save files on the device.

any ideas ? 

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "devtools": "react-devtools"
  },
  "dependencies": {
    "@babel/core": "^7.8.6",
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/cameraroll": "^4.0.4",
    "@react-native-community/checkbox": "^0.5.8",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-community/picker": "1.6.0",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-picker/picker": "1.16.1",
    "@react-navigation/devtools": "^5.1.22",
    "babel-preset-expo": "^8.3.0",
    "expo": "42.0.0",
    "expo-camera": "~11.2.2",
    "expo-file-system": "~11.1.3",
    "expo-image-deep-zoom": "^2.1.2",
    "expo-image-manipulator": "^9.2.2",
    "expo-image-picker": "~10.2.2",
    "expo-linking": "~2.3.1",
    "expo-media-library": "~12.1.2",
    "expo-network": "~3.2.0",
    "expo-permissions": "~12.1.1",
    "expo-sharing": "~9.2.1",
    "expo-web-browser": "~9.2.0",
    "formik": "^2.2.8",
    "lottie-ios": "3.1.8",
    "lottie-react-native": "^4.0.2",
    "native-base": "^2.15.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.63",
    "react-native-bem-check-box": "^1.0.0",
    "react-native-dropdown-picker": "^5.1.21",
    "react-native-elements": "^3.4.1",
    "react-native-formik": "^1.7.8",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-material-textfield": "^0.16.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-render-html": "^5.1.1",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-select-input-ios": "^2.0.5",
    "react-native-spinning-image": "^1.0.2",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-vector-icons": "^8.1.0",
    "react-native-web": "~0.13.7",
    "react-native-webview": "11.6.2",
    "react-navigation": "^4.3.9",
    "react-navigation-drawer": "^2.4.13",
    "react-navigation-header-buttons": "^4.0.2",
    "react-navigation-hooks": "^1.1.0",
    "react-navigation-stack": "^2.7.0",
    "react-navigation-tabs": "^2.8.13",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "rn-fetch-blob": "^0.12.0",
    "sanitize-html": "^2.4.0",
    "uuid": "^8.3.2",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.3.0",
    "redux-logger": "^3.0.6"
  },
  "private": true
}

### Environment

 Expo CLI 4.7.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Users\rafal.wilinski\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: 42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63 => 0.63.4
      react-native-web: ~0.13.7 => 0.13.18
      react-navigation: ^4.3.9 => 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

`    

    let downloadhandler = async (url) => {
    // Downloading the file
    let {status} = await Camera.requestPermissionsAsync();
    let fileLocation = FileSystem.documentDirectory + "test.jpg";
   let uri =  FileSystem.downloadAsync(url, fileLocation)
    .then(({uri}) => {
        // Saving the file in a folder name `MyImages`       
        if (status === "granted") {
          console.log('granted permision ', uri);          
         //  const asset = await MediaLibrary.createAssetAsync(uri);
            //  MediaLibrary.createAlbumAsync("MyImages", asset, false);
        }else{
          console.log('not granted');
          Alert.alert( 'Permissions', 'You need to grant camera Permissions to use this app.', [{ text: 'OK'}]);
        }
        // Sharing the downloded file - this is a working share function 
       //. Sharing.shareAsync(fileLocation);
      
    })
    .catch(error => {
        console.error(error);
    });
}`

### Stacktrace (if a crash is involved)

no crash

**Comment by byCedric** [comment]
Hi @rafalWili! It might be valuable to see the response from `Camera.requestPermissionsAsync`. There are limits related to how often you request permissions. If that limit is reached, the permission will be denied automatically with the `canAskAgain` property set to `false`. In this case, you have to explain to the user why you need the permission and how to grant access by [opening the app settings page with `Linking`](https://medium.com/toprakio/react-native-how-to-open-app-settings-page-d30d918a7f55).

Hope this helps!

**Comment by rafalWili** [comment]
Thank you for your response @byCedric. 
Is there a way to reset those attempts of limitations or a way to check how many attempts have been left?

**Comment by byCedric** [comment]
> Thank you for your response @byCedric.
> Is there a way to reset those attempts of limitations or a way to check how many attempts have been left?

I'm afraid Android doesn't do that. So that would be hard to check, the only option you would have is checking the `canAskAgain` property.

**Comment by rafalWili** [comment]
ah yes, good point. thanks for your advice @byCedric .

**Comment by ncoen97** [comment]
@rafalWili Hi! You should close the issue.
