### ISSUE TITLE
Expo on iOS and android crashes when using expo-linear-gradient

### ISSUE THREAD

**Issue by Josefpa** [expo/expo#14147]
### Summary

When Ever I launch the app for testing in the expo app the app crashes on the android simulator, and on my iPhone 11.

Works on web?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

expo-cli 4.10.0 

### Environment

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ChatDoor`.

This error is located at:
    in RCTView (at View.js:34)
    in View (at chatDoor.js:46)
    in RCTView (at View.js:34)
    in View (at chatDoor.js:30)
    in RCTView (at View.js:34)
    in View (at chatDoor.js:16)
    in RCTView (at View.js:34)
    in View (at chatDoor.js:14)
    in ChatDoor (at App.js:56)
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at App.js:54)
    in RNCSafeAreaView (at App.js:28)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at App.js:26)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue

### Reproducible demo or steps to reproduce from a blank project

import React from 'react';
import { StyleSheet, Image, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';

export default function ChatDoor({nameOfChat, chatIcon}){

    return(

<View>
  
  <View style={{
        flexDirection: 'row',
        padding: 20,

    }}>

        <View><Image 
                source={{uri: 'https://picsum.photos/200/200'}}
                style={{width:  50, 
            height: 50,
            borderRadius: 100,}}>
        </Image></View>

{/*Name and Content*/}
<View style={{flexDirection: 'column',
paddingLeft:20,
paddingTop: 5}}>

    {/*Name of Chat*/}
    <View>
        <View><Text>                
               {nameOfChat}</Text>
        </View>
    </View>

            {/*Content*/}

            
        <View>
        <LinearGradient
        colors={['#EE7535', '#F04F4D',]}
        style={{
                borderRadius: 100,
                paddingLeft:10,
                padding: 3,
            flexDirection: 'row' }}
      > 
      
      <Image source={{uri: 'https://picsum.photos/200/200'}}
                style={{width:  20, 
                        height: 20,
                        borderRadius: 100,}}></Image>

      <Text style={{fontSize:15,
                    paddingLeft: 10,
                    fontVariant: 'gradient',}}>SIEMA</Text>
      
      </LinearGradient>

        </View>
    

        </View>

  </View>
  </View>

    )

}

const styles = StyleSheet.create({
    button: { 
        borderRadius: 100,
        backgroundColor:    'black',
        

    },

    buttonText: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 15,
        padding: 8,

    }
})

**Comment by Narvey** [comment]
Still happens: https://snack.expo.dev/66Bzm4tVB
