### ISSUE TITLE
Expo-segment-analytics app lifecycle events are not being called on builded apps

### ISSUE THREAD

**Issue by MorenoMdz** [expo/expo#14155]
### Summary

We got all custom events to be called correctly, on both Android and iOS, but, unless I misunderstood the documentation, we are not getting any lifecycle events, things like:
* Application Opened
* Application Updated
* Application Backgrounded 

The default ones are Application Opened, Application Installed, Application Updated.

The list of events can be found [here](https://segment.com/docs/connections/spec/mobile/).

Since expo-segment-analytics is a wrapper around the iOS and Android modules, so for example the iOS SDK accepts these as initial config options:
```
let configuration = AnalyticsConfiguration(writeKey: "YOUR_WRITE_KEY")
configuration.trackApplicationLifecycleEvents = true // Enable this to record certain application events automatically!
configuration.recordScreenViews = true // Enable this to record screen views automatically!
Analytics.setup(with: configuration)
```

Looking at the Expo wrapper, there is no reference for those being initialized, so the questions I have are:

* By default, should those tracking be enabled or disabled?

* Can we enabled those in case it is disabled, or is there a limitation in how Expo wrap those?

* If those are supposed to be tracked by default, at least Session tracking, are we doing something wrong in the way we have it setup?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42

### Environment

>   Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.20.3 - ~/.nvm/versions/node/v14.17.4/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Our setup has an analytics file with: 
```
import * as Segment from 'expo-analytics-segment'

const androidWriteKey = 'FHPyXBpIFxRaFNG7uNWjVTgrmyIE0tU3'
const iosWriteKey = 'hEXfSWwOFvyCkcGOcAaGCUqalInLw58D'

/**
 * Initialize the whole analytics tracking here
 */
export async function analyticsInit() {
  console.log('...Initializing Segment...')
  Segment.initialize({
    androidWriteKey,
    iosWriteKey,
  })
}

/**
 * When the user opts in or out of analytics
 * This sets for all calls based on the logged in userId
 * @param option boolean
 * @returns void
 */
export async function updateUserTracking(option: boolean) {
  return Segment.setEnabledAsync(option)
}
```

We then call `analyticsInit()` at our App.jsx

And we import Segment and call the necessary track (identify, track, etc) methods at the other screens.

**Comment by cruzach** [comment]
FYI Segment has recently released a brand new react native library that is Expo-compatible, and it is likely that we will deprecate `expo-analytics-segment` in favor of their new library. 

I recommend trying out this new library if you're looking for the best Segment experience: https://github.com/segmentio/analytics-react-native/blob/master/README.md
