### ISSUE TITLE
Undefined is not an object (evaluating 'React.PropTypes.Number') error

### ISSUE THREAD

**Issue by nikasvan** [expo/expo#1415]
### Environment

https://exp-xde-diagnostics.s3.amazonaws.com/nikasv-fea1fc64-30ce-4ed8-8771-c566c92f8536.tar.gz.

### Steps to Reproduce

Updating from 21.0.0 to 22.0.0

### Expected Behavior

Not having **Undefined is not an object (evaluating 'React.PropTypes.Number') error**

### Actual Behavior

When updating from 21.0.0 to 22.0.0(following those steps https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6 ) I get this error:

[Image](https://i.stack.imgur.com/9okLC.png)

this is my package.json.

`{
  "name": "APP",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.5.0",
    "jest-expo": "^22.0.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^22.0.0",
    "prop-types": "^15.6.0",
    "react": "16.0.0-beta.5",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",
    "react-native-autocomplete-input": "3.3.1",
    "react-native-check-box": "2.0.0",
    "react-native-easy-toast": "1.0.9",
    "react-native-elements": "0.13.0",
    "react-native-global-props": "1.1.1",
    "react-native-htmlview": "0.12.1",
    "react-native-modal-dropdown": "0.5.0",
    "react-native-modalbox": "1.4.2",
    "react-native-parallax-scroll-view": "0.20.1",
    "react-native-tag-input": "0.0.14",
    "react-native-vector-icons": "4.2.0",
    "react-navigation": "^1.0.0-beta.27"
  },
  "rnpm": {
    "assets": [
      "./src/assets/fonts/"
    ]
  }
}`

Having hard time figuring out why updating messed up the app. Most likely it is an proptypes update thing, I am not currently not using any proptypes in the app. Any ideas?

**Comment by AdamJNavarro** [comment]
Hey @nikasvan, PropTypes moved from being under React to its own package: https://github.com/facebook/prop-types Since you mentioned you're not using prop-types on your own, it's likely one of your dependencies is using proptypes and the author or maintainer may not have updated it for a while. You'll have to make the change yourself so proptypes are imported from the prop-types library instead of react.

**Comment by nikasvan** [comment]
Hi @AdamJNavarro dependencies that i use at this time, seem to be updated for PropTypes change. If I am not mistaken Expo comes with _react-native-side-menu_ and from searching I found that this is the reason for the bug [Image 1](http://prntscr.com/idqg0r). As soon as I remove first 3  _React.PropTypes.number_ I get this error [Image 2](http://prntscr.com/idqi00)

**Comment by AdamJNavarro** [comment]
No problem. Just double checked and neither the blank project or tab navigation project of Expo comes bundled with react-native-side-menu so it's probably another one of your dependencies that installed it. With that said, if you don't need that package, the quickest way to remedy the situation would be to remove it. If you do need it, you'll need to change the import statement like I mentioned above and change all the React.PropTypes.x to PropTypes.x

**Comment by nikasvan** [comment]
In addition to @AdamJNavarro 's answer I ran `npm outdated` and updated all modules that are 'old'(in package.json). After updating error is gone.
