### ISSUE TITLE
Lottie : Safe to Use ?

### ISSUE THREAD

**Issue by LouisJS** [expo/expo#1416]
### Environment

"expo": "^25.0.0",
"react": "16.2.0",
"react-native": "0.52.0",

### Question

I'd like to use the Lottie implementation of Expo in my professional project.
Is there any progress on this Component to make it live outside the 'DangerZone' ?

Is it deprecated ?

**Comment by ide** [comment]
DangerZone means that the API may change in ways that affect prior SDK versions and there is little commitment to stability. In general, APIs that aren't in DangerZone may have breaking changes between SDK versions. For example, an API outside of DangerZone may change from SDK 24 to 25, but the old API will continue to work for SDK 24 projects. APIs in DangerZone have no such guarantee -- a new release of the Expo client may break DangerZone APIs of older SDK versions.
