### ISSUE TITLE
gradlew fails when called from parent directory with Error: Cannot find module 'expo-modules-autolinking'

### ISSUE THREAD

**Issue by DavidJFowler** [expo/expo#14165]
### Summary

`android/gradlew` build fails when called from the parent directory of the project.
e.g. With the following structure:

s
|-react-native-app
&nbsp;&nbsp;&nbsp;|-android

where `package.json` is in directory `s/react-native-app`

if I run 
`android/gradlew -p android clean :app:assembleRelease`
from working directory `react-native-app` it succeeds.

But running `react-native-app/android/gradlew -p react-native-app/android clean :app:assembleRelease`
from working directory `s` fails.

```
Error: Cannot find module 'expo-modules-autolinking'
Require stack:
- /Users/runner/work/1/s/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:134:12)
    at Object.runInThisContext (vm.js:310:38)
    at internal/process/execution.js:81:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:80:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/runne
...

   Task :unimodules-react-native-adapter:compileReleaseJavaWithJavac FAILED
/Users/runner/work/1/s/react-native-app/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/ModuleRegistryAdapter.java:26: error: cannot find symbol
    mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);
                                                                  ^
  symbol:   class ExpoModulesPackageList
  location: class org.unimodules.adapters.react.ModuleRegistryAdapter
```

This causes problems building in appcenter when the react native project is not in the root directory of the repository.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.1

### Environment

```
Expo CLI 4.10.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.17.0 - D:\nodejs\node.EXE
      Yarn: 1.22.11 - D:\npm\yarn.CMD
      npm: 6.14.13 - D:\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Create a new app with `expo init`, choose the blank typescript template.
Eject with `expo eject`
cd to parent directory of application.
Run
`my-app/android/gradlew -p my-app/android clean :app:assembleRelease`

**Comment by byCedric** [comment]
Hi @DavidJFowler, thanks for reporting this issue! I have to dig into how AppCenter is executing React Native builds, but for now, I would recommend stick with unimodules. While it says it's being deprecated, we haven't fully released the new core system that should replace this part. 

I think your issue originates from the fact that we use Node module resolve methods to find the proper paths to the native files (included in the node packages). We use this method, instead of hardcoding paths, to improve support for monorepos and (non)hoisted dependencies. If I understand it correctly, you have something like this:

```
my-app          // Executing from here fails
└── android     // Executing from here succeeds
    └── gradlew // Executing from here succeeds
```

**Comment by DavidJFowler** [comment]
Hi @byCedric,

Thanks for your reply.

> If I understand it correctly, you have something like this:
> 
> ```
> my-app          // Executing from here fails
> └── android     // Executing from here succeeds
>     └── gradlew // Executing from here succeeds
> ```

Almost, go up one level:
```
s                   // Executing from here fails
└── my-app          // Executing from here succeeds
    └── android      
        └── gradlew
```

**Comment by byCedric** [comment]
Right, thanks! So that would let the Node module resolution fail because `node_modules` is located in `my-app` (and not in `s`). I'll forward this internally to find a fix before we release the new system.

**Comment by mellisdesigns** [comment]
We also have experienced this after updating our dependencies for both our app packages (sitting in a mono repo) to Expo SDK 42

Further to this, we can actually get android building successfully locally within a monorepo by setting the `NODE_PATH` using `export NODE_PATH=/users/user/projects/monorepo/package/my-react-native-app/node_modules` and then running the command mentioned above in the root directory.

With App Center though it seems the gradle build agent or metro takes over the `NODE_PATH` environment and ignores anything we have set in App Center Environment Variables or as part of the prebuild scrips.

We are also heavily stuck and have android builds failing ... would love some idea if a fix is on the way or whether we should downgrade to Expo SDK 41? (I still need to check if the downgrade works)

**Comment by lincolnf** [comment]
I have hit this issue as well, I have a patch that seems to work so far.

just applied it using a postinstall script

```
diff --git a/node_modules/@unimodules/react-native-adapter/scripts/autolinking.gradle b/node_modules/@unimodules/react-native-adapter/scripts/autolinking.gradle
index 1e5903e..6a6a30c 100644
--- a/node_modules/@unimodules/react-native-adapter/scripts/autolinking.gradle
+++ b/node_modules/@unimodules/react-native-adapter/scripts/autolinking.gradle
@@ -44,7 +44,7 @@ class ExpoAutolinkingManager {
     String[] args = convertOptionsToCommandArgs('resolve', this.options)
     args += ['--json']
 
-    String output = exec(args)
+    String output = exec(args, this.projectDir)
     Object json = new JsonSlurper().parseText(output)
 
     cachedResolvingResults = json
@@ -56,7 +56,7 @@ class ExpoAutolinkingManager {
     return json.modules.collect { new ExpoModule(it) }
   }
 
-  static void generatePackageList(Project project, Map options) {
+  static void generatePackageList(Project project, Map options, File dir) {
     String[] args = convertOptionsToCommandArgs('generate-package-list', options)
 
     // Construct absolute path to generated package list.
@@ -80,11 +80,11 @@ class ExpoAutolinkingManager {
       args += '--empty'
     }
 
-    exec(args)
+    exec(args, dir)
   }
 
-  static String exec(String[] commandArgs) {
-    Process proc = commandArgs.execute()
+  static String exec(String[] commandArgs, File dir) {
+    Process proc = commandArgs.execute(null, dir)
     StringBuffer outputStream = new StringBuffer()
     proc.waitForProcessOutput(outputStream, System.err)
     return outputStream.toString()
@@ -193,6 +193,6 @@ if (rootProject instanceof ProjectDescriptor) {
       // TODO(@tsapeta): Temporarily muted this error — uncomment it once we start migrating from autolinking v1 to v2
       // logger.error('Autolinking is not set up in `settings.gradle`: generated package list with expo modules will be empty.')
     }
-    ExpoAutolinkingManager.generatePackageList(project, options)
+    ExpoAutolinkingManager.generatePackageList(project, options, rootProject.projectDir)
   }
 }
```

**Comment by TomCorvus** [comment]
Hi there,
@byCedric do you think this issue will be fixed in next Expo SDK release? I have the same error with AppCenter in monorepo.
I saw that the next SDK could be released at the end of September or October. (every 3 months)

Thanks

**Comment by DavidJFowler** [comment]
Hi @byCedric ,

Any update on this?

Thanks
