### ISSUE TITLE
[expo-splash-screen] Status bar color turns white during splash screen loading

### ISSUE THREAD

**Issue by arcln** [expo/expo#14176]
### Summary

When using `expo-splash-screen` to configure an Android splash screen, the status bar color is not working as expected.
It turns white during loading, ignoring configured color. This also occurs on a release build (without dev server & bundle download).

<img src="https://user-images.githubusercontent.com/25459464/130769362-9b20dc9a-d526-447f-9244-bc242da1a3cf.gif" width="200" height="auto">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

Ejected from SDK 42.0.0 | expo-splash-screen 0.5.0

### Environment

  Expo CLI 4.10.1 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.3.1 - /usr/local/bin/fish
    Binaries:
      Node: 16.7.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.20.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 13.0/13A5201i - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

From a newly created & ejected project :

```bash
expo-splash-screen -p android -b '#ffffff' --dark-mode-background-color '#000000' --dark-mode-status-bar-style 'light-content' --status-bar-style 'dark-content' --dark-mode-status-bar-background-color '#ff0000' --status-bar-background-color '#ff0000'
```

Run & notice the status bar is white during bundle download. Am I missing something?

**Comment by arcln** [comment]
I fixed it by setting the `colorPrimary` and `colorPrimaryDark` items in my app's style :

`values/styles.xml` :

```xml
<item name="colorPrimary">@color/colorPrimary</item>
<item name="colorPrimaryDark">@color/colorPrimaryDark</item>
```

Then in `values/colors.xml` (light mode) :

```xml
<color name="colorPrimary">#FFFFFF</color>
<color name="colorPrimaryDark">#FFFFFF</color> <!-- this one is used for light mode too -->
```

And in `values-night/colors.xml` (night mode) :
```xml
<color name="colorPrimary">#000000</color>  <!-- this one is used for dark mode too -->
<color name="colorPrimaryDark">#000000</color>
```

Not sure why this is required tho. Feel free to close if you think this is a good enough solution. I personally don't think so.

**Comment by aenniw** [comment]
Moved fix to `config-plugin`

`fix-night-colors.js`:

```js
const { AndroidConfig, withAndroidColorsNight } = require('@expo/config-plugins');
const { assignColorValue } = AndroidConfig.Colors;

module.exports = config => withAndroidColorsNight(config, async config => {
    config.modResults = assignColorValue(config.modResults, {
        name: 'colorPrimaryDark',
        value: '#000000'
    })
    return config;
})
```

refference plugin in `app.json`

```json
{
  "expo": {
    ...
    "plugins": [
      "./fix-night-colors"
    ]
  }
}

```

**Comment by muathime** [comment]
this worked for me
`"splash": {
      "image": "./assets/images/full_roam_splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#0A2240"
    },`

**Comment by vikassharma108** [comment]
Same issue with me, I am using a background image as a splash screen, so using a backgroundColor on splash object creating a messy splash screen. Any fixes for this to hide that white bar or display the status bar above splash screen?

**Comment by luizaacampos** [comment]
Same issue here, I'm already using resizeMode and the status bar is still white. 
Any other fixes for that?

**Comment by Witillan** [comment]
After the build mine was also white. It worked for me by adding "Status Bar" from "expo-status-bar" with "style" property of value "auto"

![image](https://github.com/expo/expo/assets/56703868/4bc47bc6-a594-4f8e-ab2b-ee44815bea88)
![image](https://github.com/expo/expo/assets/56703868/53d0c97a-f7bb-4f0a-91d4-edfff20a11b4)

**Comment by davidbaselj** [comment]
> After the build mine was also white. It worked for me by adding "Status Bar" from "expo-status-bar" with "style" property of value "auto"
> 
> ![image](https://user-images.githubusercontent.com/56703868/255651180-4bc47bc6-a594-4f8e-ab2b-ee44815bea88.png) ![image](https://user-images.githubusercontent.com/56703868/255650108-53d0c97a-f7bb-4f0a-91d4-edfff20a11b4.png)

@Witillan thank you 🙏. This works.

**Comment by rreis27** [comment]
@davidbaselj @Witillan I'm seeing the same behavior, is the solution proposed to be incorporated in the app.js (import and return statement)?

**Comment by budwol** [comment]
having the same issue. i need a black status bar on splash when dark mode and white when bright mode. 
actually it's turning white on dark mode. editing the styles.xml is a very suboptimal solution because it will be overwritten by expo prebuild.

**Comment by rklomp** [comment]
Anyone found a solution for this?
