### ISSUE TITLE
error: duplicate class: host.exp.exponent.BuildVariantConstants

### ISSUE THREAD

**Issue by ethanyuwang** [expo/expo#1417]
### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.9.4
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/ethanyuwang-876dcc3b-6909-4dc3-9f80-bbd98e17dd98.tar.gz

ExpoKit
### Steps to Reproduce

(Write your steps here:)

Detached to ExpoKit, trying to make React Native Firebase to work and followed this https://github.com/EvanBacon/expo-native-firebase. Ran into a million problems and now this:

```
Information:Gradle tasks [:app:assembleDevDevRemoteKernelProdDebug, :react-native-firebase:assembleDebug]
/Users/ethanwang/Github/reactnative/Glever/android/app/src/devRemoteKernel/java/host/exp/exponent/BuildVariantConstants.java
Error:(5, 8) error: duplicate class: host.exp.exponent.BuildVariantConstants
/Users/ethanwang/Github/reactnative/Glever/android/app/src/dev/java/host/exp/exponent/BuildVariantConstants.java
Error:(5, 8) error: duplicate class: host.exp.exponent.BuildVariantConstants
Error:Execution failed for task ':app:compileDevDevRemoteKernelProdDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED in 3s
Information:3 errors
Information:0 warnings
Information:See complete output in console
```

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by nikki93** [comment]
Can you try `./gradlew clean` where the `gradlew` file is and trying again?

**Comment by ethanyuwang** [comment]
@nikki93 
Hi I tried to clean but ran into this error:

```
Ethans-MacBook-Pro:android ethanwang$ ./gradlew clean --stacktrace
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
     Required by:
         project :
   > Could not find com.android.tools.build:gradle:3.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
     Required by:
         project : > com.google.firebase:firebase-plugins:1.1.1 > com.google.firebase:crash-plugin:1.1.1

```

**Comment by ethanyuwang** [comment]
@nikki93 
I just tried that and still got the same error

**Comment by ethanyuwang** [comment]
I "fixed" it by reducing the flavors to one:

 // Specifies two flavor dimensions.
```
  flavorDimensions "dev"

  productFlavors {
    // Define separate dev and prod product flavors.
    dev {
      // dev utilizes minSDKVersion = 21 to allow the Android gradle plugin
      // to pre-dex each module and produce an APK that can be tested on
      // Android Lollipop without time consuming dex merging processes.
      dimension "dev"
      minSdkVersion 21
    }
    ...
  }
```

**Comment by EvanBacon** [comment]
> Ran into a million problems and now this:

I wrote a version of RNFirebase that actually works with Expo. [The repo you referenced](https://github.com/evanbacon/expo-native-firebase), now uses expo-firebase-* and has far better documentation on how to integrate and use Firebase features in ExpoKit.
