### ISSUE TITLE
expo-av requires jcenter (by using old exoplayer dependency)

### ISSUE THREAD

**Issue by radko93** [expo/expo#14185]
### Summary

React Native 0.65 removed jcenter dependency. Unfortunately `expo-av` still depends on jcetner to get exoplayer. Newer versions of exoplayer do not depend on jcenter as listed here https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer?repo=jcenter
I guess it might not be trivial to update exoplayer but it might be a big issue for expo in the long run to depend on Jcenter.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Any android app.

### Reproducible demo or steps to reproduce from a blank project

No need for a demo, follow the steps of upgrading to RN 0.65 in a standalone RN app (remove jcenter dependency).

**Comment by liamjones** [comment]
For reference - the newer versions are in the Google Maven repo: https://maven.google.com/web/index.html?q=exoplayer#com.google.android.exoplayer:exoplayer

**Comment by oliver-the-uap** [comment]
As @liamjones points out maven has newer version of exoplayer (2.13 through latest), but the current android/build.gradle for expo-av insists on exoplayer 2.9.2 (with an associated comment that newer versions require some change that would break the current usage within expo-av).

Anyhow, for those interested in a workaround:

add jcenter() back into your app's `android/build.gradle` file, as per:
```
..
allprojects { 
  repositories {
    ...all other entries...
    jcenter()
  }
}
```
Putting it last should, I think, means it's the least preferred place for android to look, and thus only the things that can't be found elsewhere - namely v2.9.2 of exoplayer - should be pulled from it.

There was some chat early this year about jcenter being closed, but, whilst new versions can no longer be added to it, the owners say they'll leave it up in read-only mode indefinitely:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by jeffreymb** [comment]
This is a duplicate of #12226

**Comment by TPXP** [comment]
This has become more visible since `jcenter()` is not anymore present in the React-Native app template, systematically causing a build error when adding expo-av to a bare react-native app. Perhaps we could add a note in expo-av's install steps to avoid confusion?

**Comment by radko93** [comment]
We're getting constant errors from bintray:

```Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.```

**Comment by cjhines** [comment]
This is becoming very pressing. Total CI shutdown because of `expo-av`.

**Comment by dmitriy-komarov** [comment]
People over internet see such issues, not only Expo users.
But Expo users can not build at all due to [workaround](https://github.com/react-native-camera/react-native-camera/issues/2490) (turn off network while building) does not work for cloud.

Online services became dependent on each other too much. I guess Expo developers should configure internet-less environment for such cases - and use them by default. 

This is not just a stability problem, but a **security** one: this is not secure to execute code from internet each time user asks to build something. JCenter could became not broken, but hacked (i. e. Log4J)... and what will be with user's sources and keys inside Expo cloud?

**Comment by brentvatne** [comment]
> But Expo users can not build at all due to workaround (turn off network while building) does not work for cloud.

@dmitriy-komarov - you can build locally if you want: https://docs.expo.dev/build-reference/local-builds/

also, we deployed a mitigation to bypass jcenter and fall back to our maven cache instead. 

> This is not just a stability problem, but a security one: this is not secure to execute code from internet each time user asks to build something. JCenter could became not broken, but hacked (i. e. Log4J)... and what will be with user's sources and keys inside Expo cloud?

i'm not sure i understand your concern here. eas build works the same as most ci services. if you would like to build a different sort of environment around the same build process, you can use `eas build --local` as described in the link that i shared

**Comment by dmitriy-komarov** [comment]
@brentvatne, I mean as far Expo cloud always downloads some files from external sources without any rewieving them, this can be a security issue in case content of these files will be spoofed by hacker (attack on used repo - JCenter currently). As I understood Expo CI relies on external Java code identified just by URL, nothing else. Does not sound too secure: what if there will be code injection causing embedding some adware into a build? This is just an example, the consequences could be even more destructive.

P. S.: Local building requires some extra configuration on my machine, but this is offtopic.

**Comment by brentvatne** [comment]
EAS does not do anything different than what would happen locally. The code needed to build your app needs to be downloaded at some point, whether that's on your machine when you run the build or on EAS the result is exactly the same. What you're describing is essentially one of the downsides of using package repositories in any application - you have to trust that the repository will be kept secure. Occasionally there are indeed malicious packages published to npm, for example, and you can mitigate the risk of this by using lockfiles (the default behavior in npm and yarn) and security analysis tools.

**Comment by mcrombie** [comment]
@brentvatne Is there a timeline of when you guys plan on upgrading exoplayer to pull from the google maven repo? This is becoming pressing for our project.

**Comment by brentvatne** [comment]
@mcrombie - here's a wip PR: https://github.com/expo/expo/pull/16123

when this ships we'll release an sdk 44 compatible update

**Comment by yaroslavnikiforov** [comment]
I am getting this error during the build in the newly created app:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.9.2.
     Searched in the following locations:
       - file:/Users/yaroslav/projects/Test/node_modules/react-native/android/com/google/android/exoplayer/exoplayer/2.9.2/exoplayer-2.9.2.pom
       - file:/Users/yaroslav/projects/Test/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer/2.9.2/exoplayer-2.9.2.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer/2.9.2/exoplayer-2.9.2.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.9.2/exoplayer-2.9.2.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer/2.9.2/exoplayer-2.9.2.pom
     Required by:
         project :app > project :expo > project :expo-av
   > Could not find com.google.android.exoplayer:extension-okhttp:2.9.2.
     Searched in the following locations:
       - file:/Users/yaroslav/projects/Test/node_modules/react-native/android/com/google/android/exoplayer/extension-okhttp/2.9.2/extension-okhttp-2.9.2.pom
       - file:/Users/yaroslav/projects/Test/node_modules/jsc-android/dist/com/google/android/exoplayer/extension-okhttp/2.9.2/extension-okhttp-2.9.2.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/extension-okhttp/2.9.2/extension-okhttp-2.9.2.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/extension-okhttp/2.9.2/extension-okhttp-2.9.2.pom
       - https://www.jitpack.io/com/google/android/exoplayer/extension-okhttp/2.9.2/extension-okhttp-2.9.2.pom
     Required by:
         project :app > project :expo > project :expo-av
   > Could not find com.yqritc:android-scalablevideoview:1.0.1.
     Searched in the following locations:
       - file:/Users/yaroslav/projects/Test/node_modules/react-native/android/com/yqritc/android-scalablevideoview/1.0.1/android-scalablevideoview-1.0.1.pom
       - file:/Users/yaroslav/projects/Test/node_modules/jsc-android/dist/com/yqritc/android-scalablevideoview/1.0.1/android-scalablevideoview-1.0.1.pom
       - https://repo.maven.apache.org/maven2/com/yqritc/android-scalablevideoview/1.0.1/android-scalablevideoview-1.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/yqritc/android-scalablevideoview/1.0.1/android-scalablevideoview-1.0.1.pom
       - https://www.jitpack.io/com/yqritc/android-scalablevideoview/1.0.1/android-scalablevideoview-1.0.1.pom
     Required by:
         project :app > project :expo > project :expo-av
```

```
Expo CLI 5.1.1 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.2 => 0.67.2 
    npmGlobalPackages:
      expo-cli: 5.1.1
    Expo Workflow: bare
```

Steps:
`npx react-native init Test`
`npx install-expo-modules`
`expo install expo-av`

Is it related?

**Comment by brentvatne** [comment]
@yaroslavnikiforov - it is related. you'll need to add jcenter to your build.gradle to be able to resolve this package for now, until the pr referenced above lands. refer to https://github.com/expo/expo/blob/main/apps/bare-expo/android/build.gradle if you're not sure where jcenter is required

**Comment by yaroslavnikiforov** [comment]
@brentvatne, thanks for the answer. This temporary solution works.

**Comment by brentvatne** [comment]
sdk 45 no longer depends on jcenter

**Comment by liquidvisual** [comment]
@brentvatne How do you install `11.2`? I just ran `expo install expo-av` from the docs but it seems to install `10.2.1` by default.

**Comment by radko93** [comment]
@liquidvisual are you on SDK 45?
