### ISSUE TITLE
[Android][expo-notifications][RN0.65] app crashes on launch "Cannot read property 'addProxiedListener' of null"

### ISSUE THREAD

**Issue by Yonom** [expo/expo#14186]
### Summary

After upgrading to RN 0.65 with expo-notifications installed and imported in code, I am getting the following error and warnings on app launch:

<table>
   <tr>
      <td><img width="300" alt="Screen Shot 2021-08-26 at 11 49 31" src="https://user-images.githubusercontent.com/1394504/130943832-fe4b9763-2b93-4cf7-a062-2512d1be1bb3.png"></td>
      <td><img width="300" alt="Screen Shot 2021-08-26 at 11 54 30" src="https://user-images.githubusercontent.com/1394504/130943862-b02e1124-e301-4f39-bda9-d0312b0c92db.png"></td>
      <td><img width="300" alt="Screen Shot 2021-08-26 at 11 54 21" src="https://user-images.githubusercontent.com/1394504/130943852-9683d899-4b07-4643-bea7-4a431dea5da9.png"></td>
  </tr>
</table>

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.7.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 24, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.3 => 42.0.3 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: ^0.65.1 => 0.65.1 
      react-native-web: ^0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- create blank project
- upgrade to RN 0.65 using the upgrade helper tool
- install expo-notifications
- add `import * as Notifications from 'expo-notifications';` to App.js
- (in my case, typescript compiler removes the Notifications import if I do not use the import anywhere, might not be needed in a JS only setup) use the import somewhere in code e.g. `console.log(Notifications)`

**Comment by cruzach** [comment]
Yeah same as https://github.com/expo/expo/issues/14092, will keep this open for now until we add in RN 65 support

**Comment by jkadamczyk** [comment]
@cruzach I think it is not the same since, this one crashes on Android, while #14092 was an iOS issue. I spoke with @tsapeta about this one and after his release with iOS fixes, this one is still there. The patch @Yonom provided worked for me but it logs warnings to console
```
 WARN  EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
```

**Comment by lukmccall** [comment]
The fix is now available for bare workflow with react-native-unimodules@0.14.8 (which bundles @unimodules/core@7.1.2 and @unimodules/react-native-adapter@6.3.7). Let me know if it works or not 😉
