### ISSUE TITLE
Expo snack dependency issue (erroneous imports not cleared when removed)

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1418]
### Steps to Reproduce
I created a snack, and accidentally mistyped an import (something like `import {View} from 'ren'`). The result is, even though I've changed the import, expo snack still believes the module `ren` has been imported, and produces errors because that relies on `fs`.

### Expected Behavior
Wrong imports should be fixable, or there should be a way to clear the cache, or ideally visibility of the package.json file (even just a list where you can remove packages).

### Actual Behavior
Erroneous imports are not removed

### Reproducible Demo
Snack in question is here: https://snack.expo.io/@buishi/react-navigation-redux-bug

**Comment by tcdavis** [comment]
Thanks Julian.  Yes, we've actually been hard at work addressing this and should be ready to release soon.

In the mean time, here's your snack with the offending import removed: https://snack.expo.io/HJmyuhyPG

**Comment by JulianKingman** [comment]
Thanks! Shall I close this then?

**Comment by tcdavis** [comment]
An update to new dependency handling is not live.  You should be able to remove any offending imports from your project by deleting them from package.json.
