### ISSUE TITLE
[iOS] Error in LogInAsync function

### ISSUE THREAD

**Issue by pedrofolim** [expo/expo#14193]
### Summary

Expected Behavior
In iOS, I get the user, token, etc. as expected once the user is authenticated.

Actual Behavior
In iOS, the following error is logged on pressing the login button:
error [TypeError: undefined is not an object (evaluating 'clientId.split')]

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.0

### Environment

Expo CLI 4.10.1 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.3.0 - /var/folders/2m/_4wfyxt161z2b63rs_1_t0cw0000gn/T/yarn--1630003050393-0.17614106541175834/node
      Yarn: 1.22.11 - /var/folders/2m/_4wfyxt161z2b63rs_1_t0cw0000gn/T/yarn--1630003050393-0.17614106541175834/yarn
      npm: 7.20.3 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 31
        Build Tools: 28.0.3, 29.0.2, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ^0.17.1 => 0.17.1 
    Expo Workflow: managed

✨  Done in 7.62s.

### Creating simple authentication with expo-google-app-auth. I have a sign in button and the following LogInAsync function:

`handleSignInGoogle = async () => {
    try {
      const {type, accessToken, user } = await Google.logInAsync({
        androidClientId: GOOGLE_AND_CLIENT_ID,
        androidStandaloneAppClientId: GOOGLE_AND_CLIENT_ID,
        iosClientId: GOOGLE_IOS_CLIENT_ID,
        iosStandaloneAppClientId: GOOGLE_IOS_CLIENT_ID,
        scopes: ['profile', 'email'],
      })

      if(type === 'success') {
        console.log("user: ", user)
        await this.setState({
          signedIn: true,
        })
        this.props.navigation.navigate('Home')

      } else {
        console.log("cancelled")
      }
    } catch(e) {
      console.log("error", e)
    }
  }
`

### Version expo-google-app-auth
`expo-google-app-auth": "^8.2.2`

### Error message
`Erro undefined is not an object (evaluating 'guid.split')`

### Error Stack
`
isValidGUID@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:144652:26
guidFromClientId@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:144691:35
getPlatformGUID@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:144645:32
logInAsync$@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:144719:35
tryCatch@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:29024:23
invoke@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:29197:32
tryCatch@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:29024:23
invoke@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:29097:30
http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:29127:19
tryCallTwo@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:3882:9
doResolve@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:4046:25
Promise@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:3905:14
callInvokeWithMethodAndArg@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:29126:33
enqueue@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:29131:157
http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:29148:69
logInAsync@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:144704:38
signInWithGoogle@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:144392:31
_performTransitionSideEffects@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:55974:22
_receiveSignal@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:55916:45
onResponderRelease@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:55825:34
invokeGuardedCallbackImpl@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13231:21
invokeGuardedCallback@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13325:42
invokeGuardedCallbackAndCatchFirstError@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13329:36
executeDispatch@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13401:48
executeDispatchesInOrder@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13421:26
executeDispatchesAndRelease@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:14494:35
forEach@[native code]
forEachAccumulated@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:13563:22
runEventsInBatch@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:14518:27
runExtractedPluginEventsInBatch@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:14597:25
http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:14573:42
batchedUpdates$1@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:25221:20
batchedUpdates@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:14480:36
_receiveRootNodeIDEvent@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:14572:23
receiveTouches@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:14625:34
__callFunction@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:3196:36
http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:2928:31
__guard@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:3150:15
callFunctionReturnFlushedQueue@http://192.168.0.118:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:2927:21
callFunctionReturnFlushedQueue@[native code]
`

### Configuration gcloud
Application restrictions: iOS apps
Accept requests from an iOS application with one of these bundle identifiers: host.exp.exponent

**Comment by cruzach** [comment]
You've shared two different error messages: `Erro undefined is not an object (evaluating 'guid.split')` and `error [TypeError: undefined is not an object (evaluating 'clientId.split')]`.

Seems like there's an issue with the value of `GOOGLE_IOS_CLIENT_ID` you're passing in
