### ISSUE TITLE
exponent-server-sdk-node returns `Error: Expected Exponent to respond with undefined receipts but got undefined`

### ISSUE THREAD

**Issue by gregbenner** [expo/expo#1419]
The push server for Node `exponent-server-sdk-node` always returns 
```Error: Expected Exponent to respond with undefined receipts but got undefined```
even though the messages are working and going through. 

Reading the source code it looks like something is expected to be returned that isn't.

**Comment by nicknovitski** [comment]
You mean [these lines here](https://github.com/expo/exponent-server-sdk-node/blob/fe050108b83f2811d7ebf9b2c6f13404c078ee6a/src/ExpoClient.js#L78-L86), right?  From the error message, it seems as if `messages`, the argument to `sendPushNotificationsAsync`, is not an array.  Can you post an example of the code you're running which produces the error?

(Assigning @ide because he knows more about push notifications than me.)

**Comment by ide** [comment]
I agree with @nicknovitski's analysis -- are you sure you're passing in an array?

**Comment by gregbenner** [comment]
Yarg sorry my bad thought it was a one off. It still sends the push notification.
I went overkill and refactored
`exec(
      `curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '${JSON.stringify(pushMessage)}'`,
      (error, stdout, stderr) => {
        console.log('stdout: ' + stdout);
        console.log('stderr: ' + stderr);
        if (error !== null) {
          console.log("exec error: " + error);
        }
      }
    )`

**Comment by gregbenner** [comment]
@ide Oh it is an error I think I've tried
 ```const pushMessage = {
      to,
      sound: "default",
      body: message,
      data: {
        ticket_id
      },
      badge
    };
    await expo.sendPushNotificationAsync(pushMessage);```

and sendPushNotificationsAsync([pushMessage]) both hang forever

**Comment by gregbenner** [comment]
![screenshot from 2018-02-21 16-43-25](https://user-images.githubusercontent.com/1177690/36507101-ae511cda-1726-11e8-93bf-189f48495028.png)

**Comment by gregbenner** [comment]
Or the single  version. both hang and the computer gets hot but they do send 1 push notification... no error is thrown nothing is returned. 

![screenshot from 2018-02-21 16-47-16](https://user-images.githubusercontent.com/1177690/36507348-63d7731a-1727-11e8-8f27-ce0e02da2e81.png)

**Comment by gregbenner** [comment]
``require("dotenv").config();
const exec = require("child_process").exec;
const micro = require("micro"),
  { json, send } = micro,
  Expo = require("expo-server-sdk"),
  fs = require("fs"),
  { verify } = require("jsonwebtoken"),
  Router = require("micro-http-router"),
  { Client } = require("pg"),
  { PORT, JWT } = process.env,
  client = new Client(),
  router = new Router({ debug: true }),
  expo = new Expo(),
  Raven = require("raven")
    .config(
      "https://19c0e6f778e2433189201a9d89a2321a:52dfb3ccde234faf9308aa8fa582cc45@sentry.io/287600"
    )
    .install();

const statusOk = 200,
  okMessage = "ok";

client.connect().catch(e => console.log(e));

const captureAndLog = message => {
  console.log(message);
  Raven.captureMessage(message);
};

const findUserByZen = async zendesk_user_id =>
  await client
    .query(
      `SELECT * FROM "public"."clients" WHERE zendesk_user_id = ${zendesk_user_id}`
    )
    .catch(e => console.log("caught", e));

const updateUnreadCount = async (id, unread_message_count) =>
  await client
    .query(
      `UPDATE clients SET unread_message_count = ${Number(
        unread_message_count
      )} WHERE id = '${id}'`
    )
    .catch(e => console.log("caught", e));

router.get("/", (req, res) => "🤖");

router.post("/pushmessage", async (req, res) => {
  let arrayPushMessage = [];
  try {
    const body = await micro
      .json(req)
      .catch(e => captureAndLog(`caught this: ${e}`));
    captureAndLog(`incoming ${JSON.stringify(body)}`);
    const { rows } = await findUserByZen(body.zendesk_user_id).catch(e =>
      captureAndLog(`caught this: ${e}`)
    );
    const user = rows[0];

    if (!user) return captureAndLog("no user found");

    let { expo_push_token, unread_message_count: badge, id } = user;
    badge++; // one new zendesk message each webhook
    await updateUnreadCount(id, badge).catch(e =>
      captureAndLog(`caught this: ${e}`)
    );
    if (!Expo.isExpoPushToken(expo_push_token)) {
      const message = `You are not a token, Frodo! ${expo_push_token}`;
      return captureAndLog(message);
    }

    const { ticket_id, message } = body;
    const to = expo_push_token;
    const pushMessage = {
      to,
      sound: "default",
      body: message,
      data: {
        ticket_id
      },
      badge
    };
    try {
      exec(
        `curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '${JSON.stringify(
          pushMessage
        )}'`,
        (error, stdout, stderr) => {
          console.log("stdout: " + stdout);
          console.log("stderr: " + stderr);
          if (error !== null) {
            console.log("exec error: " + error);
          }
        }
      );
    } catch (e) {
      console.log("a big error ", e);
    }
    send(res, statusOk, okMessage);
  } catch (e) {
    console.log("a massive mistake ", e);
    send(res, statusOk, okMessage);
  }
});

const server = micro((req, res) => router.handle(req, res));

server.listen(PORT);

console.log(`micro is listening on port: ${PORT}`);

// Micro expects a function to be exported
module.exports = () => console.log("YOLO");

**Comment by gregbenner** [comment]
I'm fairly certain it is the library, expo-server-sdk, creating an endless loop, even stepping into the function nothing is returned. Also when I replace with the curl example above, everything works fine. It could be waiting for something to return that is never returned? it kills the event loop and no more posts are received on my endpoint. Yes it could be something i'm using or doing, but it's very strange curl works but the library doesn't seem to as I demonstrated above.

**Comment by gregbenner** [comment]
The one thought I had is, if it was expecting a return of some sort on a different port or protocol I would have to open it on google cloud engine vm. curl is returning correctly right now ```stdout: {"data":{"status":"ok"}}```

**Comment by ide** [comment]
This might not be related but in the past I've found Raven to sometimes override some low-level networking internals of Node, which can cause issues. I'd try commenting out the Raven import and everything that depends on it to see if that helps. You can see that the Expo library code is doing a straightforward `fetch` call. There's not much special there: https://github.com/expo/exponent-server-sdk-node/blob/master/src/ExpoClient.js#L111-L134

**Comment by gregbenner** [comment]
Will try that out, thank you for the debugging tips :)

**Comment by HugoSanchez** [comment]
Hi, I'm having the exact same issue, don't really know what could be wrong.

My code is super simple, I'm trying to send a notification, only when a specific event happens so I'm not really batching them. Here's the code:

```
let notification = {
      to: user.expoToken, 
      title: 'New Transaction!', 
      body: 'You have a new transaction', 
      data: transferData
    }
    let notificationReceipt = await expo.sendPushNotificationsAsync(notification)
```

When running this, the notification gets sent and received in the device, but I get the following error:

```
(node:7217) UnhandledPromiseRejectionWarning: Error: Expected Expo to respond with undefined tickets but got undefined
    at Expo.<anonymous> (/home/hugo/ProjectMalaysia/sikaris/node_modules/expo-server-sdk/build/ExpoClient.js:76:32)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hugo/ProjectMalaysia/sikaris/node_modules/expo-server-sdk/build/ExpoClient.js:4:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:7217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What am I doing wrong? What's the right way to do this?

Thanks!
Hugo

**Comment by gregbenner** [comment]
Hey @HugoSanchez not sure the exact issue but I would first try wrapping your await in a try catch.
This should give you some better debugging info
``` try { await expo.sendPushNotificationsAsync(notification) } catch(e) { console.log(e)} ```
it might be returning nothing and that is the bug?

**Comment by HugoSanchez** [comment]
Hi, thanks for getting back.

It's funny, when I use try catch, the catch block gets executed, and prompts the following object:

```
{ Error: Expected Expo to respond with undefined tickets but got undefined
    at Expo.<anonymous> (/home/hugo/ProjectMalaysia/sikaris/node_modules/expo-server-sdk/build/ExpoClient.js:76:32)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hugo/ProjectMalaysia/sikaris/node_modules/expo-server-sdk/build/ExpoClient.js:4:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  data: { status: 'ok', id: '6951d360-dee9-4a9f-b2f0-bf2fef9cef38' } }
```

As you can see, the error object contains 'data' which is that object that I was actually expecting!

Any ideas?

Thanks, 
Hugo

**Comment by ide** [comment]
@HugoSanchez You need to pass an array into that method instead of a single object.
