### ISSUE TITLE
Notification Icons not working on Android

### ISSUE THREAD

**Issue by ecerroni** [expo/expo#142]
I can use a custom notification icon only if points to an external url. I cannot make it work with a png contained in the asset folder.

Even so the other small icon on the phone top bar is always the expo one even though I set it up in the exp.json file.

```
import Expo from 'exponent'  // using expo 14.0

const notification = {
  title: 'Title of the reminder',
  body: 'Message of the reminder',
  android: {
    icon: '../assets/images/notification.png', // this doesn't work unless I put an external url like http://example.com/images/notification.png
    vibrate: [ 0, 250 ]
  }
}
const schedulingOptions = {
  time: (new Date()).getTime() + 1000,
  repeat: 'hour'
}

Expo.Notifications.scheduleLocalNotificationAsync(notification, schedulingOptions)



/* exp.json */
"icon": "./assets/images/loadingIcon.png",
  "notification": { // all icon are picked up but this one for notifications. Always showing expo default icons
    "icon": "./assets/images/notification.png"
  },
  "loading": {
    "icon": "./assets/images/loadingIcon.png",
    "hideExponentText": true
  },
```

**Comment by aalices** [comment]
@ecerroni Documentation says that LocalNotification property `android/ios.icon` is a `URL of icon to display in notification drawer` - that is basically why you can't get an asset working as the icon - but this could be a great enhancement I think. Anyway, setting the `notification.icon` in `exp.json` is not respected as you mentioned - I'm trying to work it out

**Comment by ecerroni** [comment]
@skevy I agree it can be closed. Anyway what bugged me was that it was showing when using an external url even when set in runtime.

However I confirm it works on a standalone app.
