### ISSUE TITLE
Pod install fails with ios "use_unimodules"

### ISSUE THREAD

**Issue by cybexai** [expo/expo#14200]
### Summary

I've been working on my project on a MacBook Pro 2017 with MacOS BigSur with no issue, i moved to a MacBook Pro 2012 with MacOS Catalina and i cannot install pods on my iOS project. The issue seems to be "unimodules"

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

"expo-updates": "~0.5.4"

### Environment

Expo CLI 4.10.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.14 - /usr/local/bin/npm
      Watchman: 20210821.022905.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.5.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 29.0.3, 31.0.0
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.0 => 41.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: ~0.64.0 => 0.64.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

=> cd ios
=> pod install

### Stacktrace (if a crash is involved)

[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/macbookair/Documents/ReactNativeProjects/KolaBusinessManager/ios/Podfile:9
 #  -------------------------------------------
 #  target 'KolaBusinessManager' do
 >    use_unimodules!
 #    config = use_native_modules!
 #  -------------------------------------------

**Comment by chrisbobbe** [comment]
> I've been working on my project on a MacBook Pro 2017 with MacOS BigSur with no issue, i moved to a MacBook Pro 2012 with MacOS Catalina and i cannot install pods on my iOS project.

Are you running a different version of CocoaPods between the two environments?

**Comment by cybexai** [comment]
it's the same version, yes i did yarn install before pod install.

**Comment by esamelson** [comment]
Hi @cybexai , thanks for the issue report. Unfortunately, the reproducible example you mentioned isn't usable for us, since we don't have access to your local project. Could you try creating a new project from scratch (`expo init --template bare-minimum@sdk-41` and see if you run into the same issue?

**Comment by cybexai** [comment]
thanks the issue seems to be Catalina and previous versions of MacOS. I installed MacOS BigSur and all went fine
