### ISSUE TITLE
react-native-safe-area-context duplication

### ISSUE THREAD

**Issue by Arcalise08** [expo/expo#14201]
### Summary

Hey there guys. I wanted to report a problem I'm seeing within new bare projects. It seems the standalone sdk of expo includes react-native-safe-area-context and installing that module standalone(as required within react navigation) will give you all kinds of bugs. The only fix I've found is navigating to the expo folder and deleting the module. I'm sure there must be a better way to resolve this.

Running without removing the folder will try to register two native views RNCSafeAreaView(quoting that from memory not positive on the name) which errors out.

running 
```
npm list react-native-safe-area-context
```
shows the following

```
+-- UNMET DEPENDENCY expo@42.0.3
| `-- UNMET DEPENDENCY react-native-safe-area-context@3.2.0
`-- UNMET DEPENDENCY react-native-safe-area-context@3.2.0

npm ERR! missing: expo@42.0.3, required by TESTAPP
npm ERR! missing: react-native-safe-area-context@3.2.0, required by TESTAPP
npm ERR! missing: react-native-safe-area-context@3.2.0, required by expo@42.0.3
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\(USERNAME)\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

initialize expo as bare project then install react-native-safe-area-context(through npm or expo install)

**Comment by Arcalise08** [comment]
I'd like to mention that using 
```
expo install react-native-safe-area-context
```
does solve this problem locally. However when anyone pulls my code and uses ` npm install`. they are forced to `npm rm react-native-safe-area-context` then use expo to install it back. its not a pretty solution by any means.

**Comment by Fistynuts** [comment]
Same issue here on Windows when running my app in the Android simulator. The Expo-bundled version of `native-safe-area-context` is conflicting with the version installed using `npm`. I haven't yet found a workaround that works for me. 

The error I see is: 
```
WARNING
Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.

Stack trace:
  node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
  node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
  node_modules\regenerator-runtime\runtime.js:63:39 in tryCatch
  node_modules\regenerator-runtime\runtime.js:294:21 in invoke
  node_modules\regenerator-runtime\runtime.js:119:20 in define$argument_2
  node_modules\regenerator-runtime\runtime.js:63:39 in tryCatch
  node_modules\regenerator-runtime\runtime.js:155:19 in invoke
  node_modules\regenerator-runtime\runtime.js:190:10 in PromiseImpl$argument_0
  node_modules\react-native\node_modules\promise\setimmediate\core.js:45:4 in tryCallTwo
  node_modules\react-native\node_modules\promise\setimmediate\core.js:200:12 in doResolve
  ...
ERROR
Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider

Stack trace:
  node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
  node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
  node_modules\regenerator-runtime\runtime.js:63:39 in tryCatch
  node_modules\regenerator-runtime\runtime.js:294:21 in invoke
  node_modules\regenerator-runtime\runtime.js:119:20 in define$argument_2
  node_modules\regenerator-runtime\runtime.js:63:39 in tryCatch
  node_modules\regenerator-runtime\runtime.js:155:19 in invoke
  node_modules\regenerator-runtime\runtime.js:190:10 in PromiseImpl$argument_0
  node_modules\react-native\node_modules\promise\setimmediate\core.js:45:4 in tryCallTwo
  node_modules\react-native\node_modules\promise\setimmediate\core.js:200:12 in doResolve
```

**Comment by Arcalise08** [comment]
> Same issue here on Windows when running my app in the Android simulator. The Expo-bundled version of `native-safe-area-context` is conflicting with the version installed using `npm`. I haven't yet found a workaround that works for me.
> 
> The error I see is:
> 
> ```
> WARNING
> Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.
> 
> Stack trace:
>   node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
>   node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
>   node_modules\regenerator-runtime\runtime.js:63:39 in tryCatch
>   node_modules\regenerator-runtime\runtime.js:294:21 in invoke
>   node_modules\regenerator-runtime\runtime.js:119:20 in define$argument_2
>   node_modules\regenerator-runtime\runtime.js:63:39 in tryCatch
>   node_modules\regenerator-runtime\runtime.js:155:19 in invoke
>   node_modules\regenerator-runtime\runtime.js:190:10 in PromiseImpl$argument_0
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:45:4 in tryCallTwo
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:200:12 in doResolve
>   ...
> ERROR
> Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider
> 
> Stack trace:
>   node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
>   node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
>   node_modules\regenerator-runtime\runtime.js:63:39 in tryCatch
>   node_modules\regenerator-runtime\runtime.js:294:21 in invoke
>   node_modules\regenerator-runtime\runtime.js:119:20 in define$argument_2
>   node_modules\regenerator-runtime\runtime.js:63:39 in tryCatch
>   node_modules\regenerator-runtime\runtime.js:155:19 in invoke
>   node_modules\regenerator-runtime\runtime.js:190:10 in PromiseImpl$argument_0
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:45:4 in tryCallTwo
>   node_modules\react-native\node_modules\promise\setimmediate\core.js:200:12 in doResolve
> ```

Please navigate into your node modules folder, find expo and manually delete react-native-safe-area-context. that will solve your issue for the moment.

its not a great solution but it does work

**Comment by Fistynuts** [comment]
> Please navigate into your node modules folder, find expo and manually delete react-native-safe-area-context. that will solve your issue for the moment.
> 
> its not a great solution but it does work

Thank you, this does indeed work around the problem.
