### ISSUE TITLE
[expo-in-app-purchases] getProductsAsync(items) does not reflect changed localised price for particular country in android.

### ISSUE THREAD

**Issue by dorapax-lab** [expo/expo#14207]
### Summary

I have added app subscription in google play console. I set default price as 1 USD.
Based on the exchange rate 1 USD = 1.49 AUD

Then I changed the localised price for country Australia manually in google play console (1.49 AUD to 2 AUD).

Expected Behaviour:
When I retrieve products using `getProductsAsync(items)` It should show the subscription price as 2 AUD.

Current Behaviour:
When I retrieve products using `getProductsAsync(items)` It shows the subscription price as 1.49 AUD.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.17.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.65.1 => 0.65.1 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```
      const { responseCode, results } = await getProductsAsync(items)

      if (responseCode === IAPResponseCode.OK) {
        if (results && results.length > 0) {
          const sub = results.find((o) => o.productId === subscribeId)
          console.log(sub)
        }
      }
```

**Comment by cruzach** [comment]
> Then I changed the localised price for country Australia manually in google play console (1.49 AUD to 2 AUD).

You changed the price of the product? Maybe this change takes some time have effect or you need to re-request products

**Comment by dorapax-lab** [comment]
Hi, Actually I found that to reflect the regional price it is not enough to release the app as **closed test**. You need the **approval** as well. Regional prices are reflecting after I got the approval from **Google Play** for **closed test**. So this is not an issue. I will close this issue.

Thanks & Regards.
