### ISSUE TITLE
Expo Workspaces -  Unable to resolve module

### ISSUE THREAD

**Issue by Braden1996** [expo/expo#14210]
### Summary

Hello!

I have been moving a React Native project, within a monorepo, over to a managed Expo workflow. However, I am having quite a lot of difficulty configuring the various bundlers to behave appropriately in a Yarn 2 Workspaces environment. I have gotten Expo web (`react-native-web` via WebPack) to bundle and work as expected.

Unfortunately, I'm seeing some weird errors when bundling via Metro for iOS or Android. In particular, the module resolution seems to be ignoring assets (trying to import as source or directory barrel file) and also not finding source-files which are in fact there (can be resolved in-editor via TypeScript).

I've taken quite a bit of time to extract the monorepo structure and create a reproducible demo of the problem here: https://github.com/Braden1996/monorepo-template

My hope is, once this is solved, this can serve as quite a nice template for the community.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42.0.3

### Environment

Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.4 - /var/folders/gg/1bvc0mtd34qf25qnwxcwvbyh0000gn/T/fnm_multishells/2553_1630156392755/bin/node
      Yarn: 3.0.0 - /opt/homebrew/bin/yarn
      npm: 6.14.14 - /var/folders/gg/1bvc0mtd34qf25qnwxcwvbyh0000gn/T/fnm_multishells/2553_1630156392755/bin/npm
      Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 31
        Build Tools: 29.0.2, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.3 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ^0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/Braden1996/monorepo-template

**Comment by yograf** [comment]
+1

**Comment by Braden1996** [comment]
A small update to share... After a good few hours slugging away, I've got this working. The strategy is pretty gross and probably earned me a nice cozy spot in Hell.

For posterity, I've documented the high-level idea in the repository README. If anyone has a more elegant solution, please do share! :)

**Comment by barthap** [comment]
The monorepo with Expo is tricky, but hopefully this will change in next SDK, when the new autolinking comes in. See https://github.com/expo/expo/pull/13901#issuecomment-894530030

Have you seen https://github.com/byCedric/eas-monorepo-example ?

**Comment by Braden1996** [comment]
> The monorepo with Expo is tricky, but hopefully this will change in next SDK, when the new autolinking comes in. See [#13901 (comment)](https://github.com/expo/expo/pull/13901#issuecomment-894530030)
> 
> Have you seen https://github.com/byCedric/eas-monorepo-example ?

Hey @barthap, thanks for the reply. I've read bits and bobs about the upcoming improvement to monorepo support and am keen to try it out.

As for the `eas-monorepo-example`, I did base some of my repo around that. However, Yarn's hoisting was making things difficult. For example, `expo` was being hoisted to the workspace root but `react-native` was not. This meant Expo was unable to resolve `react-native` itself.
