### ISSUE TITLE
expo-updates doesn't load published bundle

### ISSUE THREAD

**Issue by schnAlex** [expo/expo#14211]
### Summary

As I have been upgrading from ExpoKit to the bare workflow shortly I noticed a difference in behavior using expo-updates.
In ExpoKit our ci/cd was like running expo publish storing the created bundle and manifest files on cloud storage.
so when ever we did build a native app bundle we were able to download those files and include them in the native app bundle. the JS bundle loaded by the native app was the one created by expo publish.

Now when we specify a bundle path in "app.json" and include the created files in the native build. the JS bundle that is loaded is the one created by the react-native-scripts (main.jsbundle) and the bundle published with "expo publish" is not downloaded.

I assume that is because of the timestamp comparison since we publish before we run the native build.

My question would be is there a way to force expo-updates to use a specific bundle path instead of the default "main.jsbundle" and "app.manifest" etc.

Or maybe there is some clarification on the difference between the files created by the expo publish command and the files created during the build process

for ease I would suggest focusing on the iOS native wrapper. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 24, 28, 29, 30
        Build Tools: 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.2
        System Images: android-25 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6200805
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.2 => 0.63.4 
      react-native-web: ^0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- Setup Expo in bare workflow
- setup expo-updates
- edit app.json:
  "ios":{
      "publishBundlePath": "ios/myapp/Supporting/shell-app.bundle",
      "publishManifestPath": "ios/myapp/Supporting/shell-app-manifest.json"
  }
- run expo publish
- build IPA in xcode

**Comment by cruzach** [comment]
Hey! Can you explain why you want to not use the default bundle and manifest? You can probably do some hacking to get this to work the way you want, but it seems like it could be pretty brittle as opposed to making your app work with the default React Native flows
