### ISSUE TITLE
exp build:ios does not work for apple accounts with space in password

### ISSUE THREAD

**Issue by ericvicenti** [expo/expo#1421]
This is obscure and you probably shouldn't worry about it, but I had to change my apple password because it had a space in it, in order for me to build with `exp build:ios` and the managed expo process.

There was of course not a good error for this. I would have been totally blocked if I didn't have the hunch that the space was throwing your service off.

**Comment by AdamJNavarro** [comment]
Thanks for the heads-up! Very obscure.

**Comment by fxfactorial** [comment]
Sorry about that, that is annoying. 

Took a quick gander at the code and methinks its more how `inquirer` handles this input, because all that is called is: 

```
    return inquirer.prompt(appleCredsQuestions);
```

Where 

```
const appleCredsQuestions = [
  {
    type: 'input',
    name: 'appleId',
    message: `What's your Apple ID?`,
    validate: nonEmptyInput,
  },
  {
    type: 'password',
    name: 'password',
    message: `Password?`,
    validate: nonEmptyInput,
  },
];
```
