### ISSUE TITLE
expo-av RecordingStatus is missing metering value

### ISSUE THREAD

**Issue by nbonatsakis** [expo/expo#14234]
### Summary

When using one of the built-in audio recording presets that has `isMeteringEnabled` set to true, status updates on `Recording` objects do not include `metering` values. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40.0.1

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.2 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.20.3 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.67 => 0.12.67 
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
await Audio.requestPermissionsAsync()
        await Audio.setAudioModeAsync({
            allowsRecordingIOS: true,
            playsInSilentModeIOS: true,
        })

const {recording} = await Audio.Recording.createAsync(
            Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY,
            (status: Audio.RecordingStatus) => {
                console.log(`LEVEL ${status.metering}`) // is always `undefined`
            })
```

**Comment by filipecatraia** [comment]
I'm bumping this since it wasn't ever handled.

We're facing the same issue but only on Android, iOS has never failed. We track when `metering` is `undefined` by logging an error via Bugsnag, which then lets us figure out in which situations this happens. We've seen this about a thousand times per day, on Androids 9–12, and device make doesn't seem to matter much (Samsung, Huawei, Xiaomi, Nokia, etc.)

If metering isn't possible on a wide range of devices and/or operating system combinations, then there should be a significant warning in the documentation.

**Comment by segun-flexible** [comment]
> I'm bumping this since it wasn't ever handled.
> 
> We're facing the same issue but only on Android, iOS has never failed. We track when `metering` is `undefined` by logging an error via Bugsnag, which then lets us figure out in which situations this happens. We've seen this about a thousand times per day, on Androids 9–12, and device make doesn't seem to matter much (Samsung, Huawei, Xiaomi, Nokia, etc.)
> 
> If metering isn't possible on a wide range of devices and/or operating system combinations, then there should be a significant warning in the documentation.
> 
> Still, I appreciate how hard the Expo team works! 💪 We rely on `metering` to detect when a user has stopped talking, and that works quite well on iOS, so thanks for looking into it.

hey bro, have you later found alternative way to measure metering while recording or play sound?

**Comment by Zakisb** [comment]
bumping this again. facing similar issues years later

**Comment by erickayalarias** [comment]
same issue, for android at least this is not working but IOS is working as expected

**Comment by filipecatraia** [comment]
> > I'm bumping this since it wasn't ever handled.
> > We're facing the same issue but only on Android, iOS has never failed. We track when `metering` is `undefined` by logging an error via Bugsnag, which then lets us figure out in which situations this happens. We've seen this about a thousand times per day, on Androids 9–12, and device make doesn't seem to matter much (Samsung, Huawei, Xiaomi, Nokia, etc.)
> > If metering isn't possible on a wide range of devices and/or operating system combinations, then there should be a significant warning in the documentation.
> > Still, I appreciate how hard the Expo team works! 💪 We rely on `metering` to detect when a user has stopped talking, and that works quite well on iOS, so thanks for looking into it.
> 
> hey bro, have you later found alternative way to measure metering while recording or play sound?

Nope, we went bankrupt before Expo managed to fix this! But hey, at least the issue is closed ;)
