### ISSUE TITLE
[iOS] ImagePicker allowsEditing moving focus a bit on select

### ISSUE THREAD

**Issue by jhalborg** [expo/expo#1423]
Starting note: I also posted this on the [forums](https://forums.expo.io/t/ios-imagepicker-allowsediting-moving-focus-a-bit-on-select/7220)
### Environment

iOS, Expo SDK 25, Client

### Steps to Reproduce
Ive noticed that the images picked using the [ImagePicker](https://docs.expo.io/versions/latest/sdk/imagepicker.html) using the allowsEditing option is actually a bit off.

If I pick the portraitmode waterfall stock image, and resize it so the top is just above the topmost rocks on the right side, and seperate the cut-in in the middle in the bottom, I notice that the resulting image actually includes some space above the top and cuts off similar space from the bottom.

Images with some annotations for illustration, I hope it makes sense:
[image 1](https://expo-discourse-uploads.s3-us-west-1.amazonaws.com/original/2X/f/f43d55151678a5045c4f8a22547eefae0210fe7e.jpg)
[image 2](https://expo-discourse-uploads.s3-us-west-1.amazonaws.com/original/2X/f/fae35d86c45ae772725befcb096d63a986e5106e.png)
### Expected Behavior

Why is this? It’s very confusing as a user (and programmer for that matter :wink: ). Any way to disable it or remedy it?

I think it works fine on Android, but the example is fidgy on the Android for some reason - the image disappears almost instantly after having been added.

### Reproducible Demo
https://snack.expo.io/S14MFwgDf

**Comment by terribleben** [comment]
Hi! I agree, this behavior is confusing. ImagePicker on iOS is just a small wrapper around [UIImagePickerController](https://developer.apple.com/documentation/uikit/uiimagepickercontroller), a "canned" UI maintained by Apple. So we actually can't control any of the behavior there, and it's exactly the same in any non-Expo, non-React-Native app which uses UIImagePickerController.

If you want a custom UI, the best approach is to build an alternative version yourself using our Camera, CameraRoll and ImageManipulator APIs.

Sorry we can't fix it! Hope this answer was helpful.

**Comment by jhalborg** [comment]
Hey @terribleben - Thanks for getting back so quickly. I was afraid this was the case, but wanted to make sure.

**Comment by jhalborg** [comment]
@terribleben - I'm sorry to bring this up again, but I still believe there's some error somewhere. I just tried creating a native iOS project that simply picks an image from the library with `imagePicker.allowsEditing = true` and shows the result, and the image is cropped perfectly. 

It struck me that the offset is somewhat close to the height of the `StatusBar`, could that have anything to do with it?

**Comment by jhalborg** [comment]
Hehe, @terribleben wants nothing to do with this nonsense @brentvatne :) Sorry for the double tag, but I'm afraid the issue might be lost if it does not get an assignee or a label :)

Have a great weekend

**Comment by rwb392** [comment]
I found this bug ticket while experiencing an issue where I can't select the entirety of an already square image on iOS when using:
`ImagePicker.launchImageLibraryAsync({
      allowsEditing: true,
      aspect: [1, 1],
      mediaTypes: 'Images',
    });`
Photo I'm trying to pick: [Link](https://i.imgur.com/sG7BjWs.jpg)
Photo of me trying to pick it: [Link](https://i.imgur.com/x8k9Wz5.jpg)

After reading all this, I discovered that I too was also experiencing weird changes between the area I tried to crop vs the area that it actually cropped.
Trying to crop an image: [Link](https://i.imgur.com/EqjdZvz.jpg)
Result of cropping: [Link](https://i.imgur.com/YpjT6Z7.jpg)

After doing some more searching, I found this [Apple forum post](https://forums.developer.apple.com/thread/98274) about this issue in iOS 11 indicating that @terribleben is probably right and that it's probably an iOS problem, not an Expo problem.

That being said, has anyone found a good solution or alternative to cropping square photos on iOS? And should this ticket be open with the "help wanted" status? And if so, where would one start if they wanted to help?

**Comment by jhalborg** [comment]
Any way we can get this moving somehow? If it's a known bug on iOS 11, could Expo perhaps offset the cropping to match as a workaround? There's little we can do as developers using Expo's API

**Comment by grsmvg** [comment]
Also just bumped into this. Would be nice if it got fixed somehow, since this is the only way to do native cropping in Expo right? If you take a photo in portrait, and then crop, it's even weirder. Then there are whole portions of the photo that you can never get within the square frame.

**Comment by miklschmidt** [comment]
Hoping #3092 fixes the issue. For now, i found a quite workable workaround based on @jhalborg observation about the status bar. Just hide it while the picker is visible:

```
if (Platform.OS === 'ios') {
	StatusBar.setHidden(true);
}
const media = await ImagePicker.launchImageLibraryAsync({
	mediaTypes: 'Videos',
	allowsEditing: true,
	quality: 0.7,
});
if (Platform.OS === 'ios') {
	StatusBar.setHidden(false);
}
```

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. Recent posts indicate this remains an issue, could one of you please open a new issue with a repro case? We'll get it appropriately assigned and we'll be happy to investigate.

Cheers,  
Adam

**Comment by jhalborg** [comment]
Done, https://github.com/expo/expo/issues/3459
