### ISSUE TITLE
[Android][expo-in-app-purchases][RN0.65.1] can not do purchaseItemAsync() [TypeError: Cannot read property 'addProxiedListener' of null]

### ISSUE THREAD

**Issue by dorapax-lab** [expo/expo#14241]
### Summary

I updated my react native version 0.63.4 -> 0.65.1. After that I can not do `purchaseItemAsync()` and I'm getting this error `[TypeError: Cannot read property 'addProxiedListener' of null]`. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.10.0 environment info:
System:
OS: macOS 11.2.3
Shell: 5.8 - /bin/zsh
Binaries:
Node: 14.15.5 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 7.17.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.10.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
IDEs:
Xcode: 12.4/12D4e - /usr/bin/xcodebuild
npmPackages:
expo: ~42.0.1 => 42.0.3
react: 17.0.2 => 17.0.2
react-dom: 17.0.2 => 17.0.2
react-native: 0.65.1 => 0.65.1
react-native-web: ~0.13.12 => 0.13.18
npmGlobalPackages:
expo-cli: 4.10.0
Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```
import { purchaseItemAsync } from 'expo-in-app-purchases'

purchaseItemAsync(product.productId)
```

**Comment by cruzach** [comment]
Same as #14092, will keep this open for now until we add in RN 65 support
