### ISSUE TITLE
Getting Notification Token Failing on iOS

### ISSUE THREAD

**Issue by ewein** [expo/expo#1424]
My app uses push notifications and everything is working great on Android but on certain iOS devices its failing to get the notification token. It's failing on iOS 11.2.1 on an iPhone 7. If you install the app fresh from the store on iOS it will sometimes crash when you accept the NOTIFICATIONS permission so maybe this is related to that?

### Steps to Reproduce

In your Main component run the following code in your componentDidMount method:
```
    _generateNotificationToken = async () => {
        const { status: existingStatus } = await Permissions.getAsync(
            Permissions.NOTIFICATIONS
        );

        let finalStatus = existingStatus;

        if (existingStatus !== 'granted') {
            const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
            finalStatus = status;
        }

        // Stop here if the user did not grant permissions
        if (finalStatus !== 'granted') {
            return;
        }

        // Get the token that uniquely identifies this device
        Notifications.getExpoPushTokenAsync().then((token) => {
            this.props.dispatch(saveNotificationToken(token));
        }).catch(err => {
            alert("2: " + JSON.stringify(err));
        });
    };
```

Here is the error that is being caught and alerted:

![image1](https://user-images.githubusercontent.com/2450286/36217379-1e5e9dca-1166-11e8-9740-90bb995f9d28.png)
![image2](https://user-images.githubusercontent.com/2450286/36217382-20c1da50-1166-11e8-9cf2-f8ed200cb850.png)

**Comment by ide** [comment]
Just to confirm - is this a standalone app made with exp build (not detached -- which don't support push notifications)?

**Comment by ewein** [comment]
Yeah its a standalone app made with exp build.

**Comment by 6foot7** [comment]
any news on this? I'm having exact same issue.
![img_1382](https://user-images.githubusercontent.com/647941/38350792-35ea3df0-38ad-11e8-9aae-bcbb69f14545.PNG)

**Comment by ide** [comment]
It looks like these issues are in SDK 25. Can you upgrade to SDK 26 and see if that resolves the issue?

**Comment by 6foot7** [comment]
Thank you, just to inform you, I upgraded to SDK 26 and also rebuild my project completely by creating a new project from the Expo XDE (Initially I had created my app with CRNA) and copying all my files into that new project . Now it's working!

**Comment by ide** [comment]
We haven’t had reports of this in the latest and supported SDK (28); closing.
