### ISSUE TITLE
React native maps bug on the web

### ISSUE THREAD

**Issue by Tozare** [expo/expo#14255]
### Summary

I want to use react-native-maps library in my expo snack. Everything works in IOS through QR code. However, when I want to preview the project on the web platform, I get following error: "Unable to fetch module snackager-1/react-native-maps@0.28.0 for web.". 
Is it bug? Or is it just impossible to use maps in expo web preview?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

42

### Environment

Unable to fetch module snackager-1/react-native-maps@0.28.0 for web.

### Reproducible demo or steps to reproduce from a blank project

Link of the snack: https://snack.expo.dev/@tozare/d4eb58

**Comment by EvanBacon** [comment]
`react-native-maps` currently does not support web. Currently it just has an [empty shim for the map view](https://github.com/react-native-maps/react-native-maps/blob/master/lib/components/MapView.web.js).

**Comment by Tozare** [comment]
Will it be supported?

**Comment by Simek** [comment]
> Will it be supported?

This is the question to ask to the package maintainers. 🙂 There is already a discussion about web support in theirs repo: 
* https://github.com/react-native-maps/react-native-maps/issues/3861

**Comment by ezekiel747** [comment]
@Simek  yeah, docs also say support is experimental: https://docs.expo.dev/versions/latest/sdk/map-view/#configuring-for-web
But the support just _isn't there at all._

For those who might want to try an alternative for the time being: https://github.com/react-native-maps/react-native-maps/issues/3475#issuecomment-723502091

**Comment by EvanBacon** [comment]
My understanding is that some community members are working on a replacement for `react-native-maps` since it's no longer supported.
