### ISSUE TITLE
BlurView doesn't work over ScrollView

### ISSUE THREAD

**Issue by wspl** [expo/expo#1425]
### Environment

iPhone 7s with iOS(11.2.5)

Expo Client

### Steps to Reproduce

[https://snack.expo.io/rk_vYtMwM](https://snack.expo.io/rk_vYtMwM)

Steps:

1. Scan the QRCode generated by snack
2. Scroll screen

### Actual Behavior

BlueView stuck and become a blank view with opacity,
Lost dynamic blurry effect.

Demo Video: [https://drive.google.com/file/d/1aZrft3qcEIAYX0if4Us9gkdsxqxQNb36/view?usp=sharing](https://drive.google.com/file/d/1aZrft3qcEIAYX0if4Us9gkdsxqxQNb36/view?usp=sharing)
(The video has not been edited, these are all one-time happen)

**Comment by AdamJNavarro** [comment]
Hey @wspl,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
