### ISSUE TITLE
expo-facebook login stopped working on android WebViews

### ISSUE THREAD

**Issue by rabie-khlifi** [expo/expo#14258]
``does expo-facebook still supports login on android after **Facebook deprecating support on android WebViews** ? 
**if not** - how to do it ?
cuz following the docs didint help and even my old apps (already published on playstore) stopped working
i get the following errors
![image](https://user-images.githubusercontent.com/37998395/131830193-e3393839-1c4a-4a75-838c-ed070d5dc103.png)
![image](https://user-images.githubusercontent.com/37998395/131830636-2c4f8938-619d-4c19-b802-fe448e22d761.png)

**Comment by rabie-khlifi** [comment]
still not working for me nth in the docs or forums helped

**Comment by rabie-khlifi** [comment]
any news

**Comment by pawan779** [comment]
same issue

**Comment by xLesterGG** [comment]
Experienced this as well, I think that the only way for it to work is to have the FB app in your phone for it to work

**Comment by rabie-khlifi** [comment]
> Experienced this as well, I think that the only way for it to work is to have the FB app in your phone for it to work

i have the FB app installed and i had the same issue it worked fine on ios , but on android no luck the problem still exists also on some other popular apps like tinder tested that few weeks ago its cuz of the new facebook changes, expo needs to address that asap

**Comment by MariemHachani** [comment]
same here

**Comment by derekurizar** [comment]
Same here...

**Comment by derekurizar** [comment]
@rabie-khlifi @MariemHachani  Hey I fixed the error! You need to fill all the basic information in facebook developers for your app, and you need to enable the advanced access for `public_profile` and `email` in App Review -> Request tab.

**Comment by xLesterGG** [comment]
using the latest version of `expo-facebook` fixes the issue, it opens a different kind of prompt which isnt the embedded browser.

**Comment by summerkiflain** [comment]
@xLesterGG can you please mention exactly which version of `expo-facebook` fixes this issue?

**Comment by xLesterGG** [comment]
> @xLesterGG can you please mention exactly which version of `expo-facebook` fixes this issue?

I only tried `11.2.0` it works just fine

**Comment by bekir-arkulpa** [comment]
same problem, updating to latest expo-facebook version did not help, problem only occurring on android 11, with facebook app it works but if facebook app is not installed the error above happens and facebook does not let login with web view.
