### ISSUE TITLE
[expo-camera] [expo-barcode-scanner] Does not call scan events in app-bundle version

### ISSUE THREAD

**Issue by ethanrose** [expo/expo#14263]
### Summary

Scan events work perfectly in development running in expo/metro. When I build the app-bundle and put on the play store, scan events no longer happen. Tried with expo-camera and expo-barcode-scanner, same results.

Usage:
```
                <Camera
                    onBarCodeScanned={loading ? undefined : handleBarCodeScanned}
                    style={[StyleSheet.absoluteFillObject, styles.scanContainer]}
                    barCodeScannerSettings={{
                        barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
                    }}
                />
```

Testing on Moto E 2020. Haven't tested on iOS yet.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Render the expo-camera or expo-barcode-scanner component with a scan event handler
2. Build app-bundle and deploy to play store
3. Download app - scan events no longer get called.

**Comment by ethanrose** [comment]
https://github.com/expo/expo/issues/3886 < Found this related one that is still open from 2019. Surely it's a tough bug to fix, but I wonder if there's at least a workaround.

**Comment by ethanrose** [comment]
Update: The scan event also doesn't fire in iOS testflight deployments (on my iphone), even though it works just fine in local dev.

My internal testers (android only so far) said scanning works as expected.

Makes me wonder if somehow it's only an issue on phones that also run the dev build.........

**Comment by ethanrose** [comment]
Okay weird update:

My Android deployment wasn't working on my dev device for 2 days straight, but then started magically working without pushing an update.

My iOS deployment wasn't working on my dev device still at that point, so I pushed a new version, and now scans are working on both Android and iOS.

I'm at a loss for why this happened. But feel free to close since I have no consistently reproducible steps.

😭

**Comment by esdu-weptile** [comment]
I had same issue and spend couple hours to figure out but couldn't. Adding  @koale/useworker package to project fix it. Thank you @ethanrose
