### ISSUE TITLE
Audio ducking behavior not working as expected

### ISSUE THREAD

**Issue by ethantran** [expo/expo#1426]
### Environment

Simple expo project using Audio and Video tested on iOS 6s+ device

### Steps to Reproduce

1. Clone https://github.com/ethantran/videoaudio
2. Turn on music from a music app (spotify)
3. Press AudioSetIsEnabledAsyncTrue
4. Press setAudioModeAsync
5. Press createSound
6. Press playAsyncSound
7. Notice that the music is ducked as expected
8. Press stopAsyncSound
9. Notice that the music volume does not rise as expected
10. Press playAsyncSound again
11. Notice that the music turns off instead of repeating step 7
12. Reload app and try with video (the video has no sound and I even tried muting and setting volume to 0)
13. Press playAsyncVideo
14. Notice that the music is not lowered or turned off as expected from a video with no sound and muted
15. Press stopAsyncVideo
16. Press playAsyncVideo again
17. Notice that the music is stopped instead of repeating step 14
18. Play sound and let it run to its end
19. Notice that the music volume does not rise unless you press stopAsyncSound

**Comment by sjchmiela** [comment]
Wow! Nice catch!

I was able to reproduce everything you described except "9. Notice that the music volume does not rise as expected".

Looking into this!

**Comment by sjchmiela** [comment]
Looks like the behavior described in 11. is not a bug, but a proper behavior — `EXAV` [resets the category](https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Core/Api/AV/EXAV.m#L303) to `AVAudioSessionCategorySoloAmbient` when deactivating session (and session is being deactivated when you stop playing all the medias).

**Comment by ethantran** [comment]
Ok thanks for confirming. So what is the best way or is it even possible to prevent background music from being disabled while still transitioning from one video or audio or having a video with no audio and different audio playing on top of video occasionally? I am trying to demo a fitness app with video of exercises and some sounds like bells for timers or voice actors for indication of the next exercise. It would be ideal for the user to be able to experience this with their background music without the background music stopping.

**Comment by sjchmiela** [comment]
You could `setAudioModeAsync` each time the player stops — try:

1. Clone https://github.com/ethantran/videoaudio
2. Turn on music from a music app (spotify)
3. Press AudioSetIsEnabledAsyncTrue
4. Press setAudioModeAsync
5. Press createSound
6. Press playAsyncSound
7. Notice that the music is ducked as expected
8. Press stopAsyncSound
9. **Press setAudioModeAsync**
10. Notice that the music volume **does** rise as expected
11. Press playAsyncSound again
12. Notice that the music **is ducked as expected**
13. Reload app and try with video (the video has no sound and I even tried muting and setting volume to 0)
14. Press playAsyncVideo
15. Notice that the music is not lowered or turned off as expected from a video with no sound and muted
16. Press stopAsyncVideo
17. **Press setAudioModeAsync**
18. Press playAsyncVideo again
19. Notice that the music **is not lowered or turned off**
20. Play sound and let it run to its end
21. Notice that the music volume does **not** rise unless you press stopAsyncSound **=> you would have to call `stopAsync` when a status update callback is called with `didJustFinish = true`**.

I'm working on a fix to this issue.
