### ISSUE TITLE
Using expo-location returns [Unhandled promise rejection: Error: Location provider is unavailable. Make sure that location services are enabled.]

### ISSUE THREAD

**Issue by sammy532** [expo/expo#14269]
### Summary

I am using `expo-location` as described [here](https://docs.expo.dev/versions/v42.0.0/sdk/location/) : 

```
(async () => {
      let { status } = await Location.requestForegroundPermissionsAsync();
      if (status !== "granted") {
        setErrorMsg("Permission to access location was denied");
        return;
      }

      let location = await Location.getCurrentPositionAsync();
      setLocation(location);
    })();
```

My dependencies from `package.json`:` "expo-location": "~12.1.2" and "expo": "^42.0.0",` I am testing an huawei. I tried all suggestions from [here](https://github.com/expo/expo/issues/5504)  but non of them worked:

- I tried using `accuracy: Location.Accuracy.Highest` - it didnt work
- I tried using `accuracy: Location.Accuracy.Lowest` - it didnt work
- I tried using `watchPositionAsync` it also didnt work
- I changed my `app.json` by adding ```
"permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "ACCESS_BACKGROUND_LOCATION"
      ]```

even though I shouldnt have to (as explained in the docs). Again it didnt work

My app is heavily dependent on location services, I would greatly appreciate a working solution!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.11.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.21.1 - ~/.nvm/versions/node/v12.18.4/bin/npm
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I just used the demo from the [docs](https://docs.expo.dev/versions/v42.0.0/sdk/location/)

**Comment by daimessdn** [comment]
I also have the same issue in Samsung Galaxy J4+ (bare workflow). But it works on Android Emulator (I'm currently using Android Studio Arctic Fox (2020.3.1) using Android emulator API S x86_64 on Ubuntu 20.04). So strange... :thinking:

**Comment by fcsonline** [comment]
You have more information here: https://github.com/expo/expo/issues/14248

**Comment by daimessdn** [comment]
@fcsonline : Nice, thanks. I'll check it out while trying other packages as alternatives.

**Comment by sammy532** [comment]
> @fcsonline : Nice, thanks. I'll check it out while also trying other packages as alternatives.

@fcsonline Please, let us know if you have any luck!

**Comment by tsapeta** [comment]
Closing in favor of #14248
