### ISSUE TITLE
[docs] react-native-unimodules readme and expo-modules-core readme are circular

### ISSUE THREAD

**Issue by kseniamukhortova** [expo/expo#14275]
### Summary

The README for react-native-unimodules is misleading.
1. It says that it's deprecated in favor of expo-modules-core, but expo-modules-core package itself refers to react-native-unimodules as a prerequisite.
2. It references https://expo.fyi/expo-modules-core-migration which doesn't exists.

So it's absolutely not clear how to use expo libraries in bare react-native projects.

### Link to the related docs page

https://github.com/expo/expo/blob/master/packages/react-native-unimodules/README.md

**Comment by tsapeta** [comment]
This https://github.com/expo/expo/commit/f8cb68dc81c4d2a0ec3d0e22c3a449fe01500100 should fix the problem. I'm sorry for confusion 🙈
