### ISSUE TITLE
Can't display image when there is a _ in the subdomain

### ISSUE THREAD

**Issue by solisoft** [expo/expo#14274]
### Summary

If I try to load https://cms.fasty.ovh/asset/o/2580c8dc-f0b7-4af2-8235-926e00104ee7?_from=Y21z it works but if I try to load https://vitaliseur_staging.fasty.ovh/asset/o/e6545639-39ea-4bbe-ab4e-04229aab1d23?_from=dml0YWxpc2V1cl9zdGFnaW5n it fail

I tested with several subdomains and it's always the same issue.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.1

### Environment

 Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```html
<Image source={{ uri: "https://vitaliseur_staging.fasty.ovh/asset/o/e6545639-39ea-4bbe-ab4e-04229aab1d23?_from=dml0YWxpc2V1cl9zdGFnaW5n" }} />
```
It will fail because of the `_`

**Comment by brentvatne** [comment]
this is odd, i'm not sure what is causing it. i can upload that exact image to github and load it just fine:

![e6545639-39ea-4bbe-ab4e-04229aab1d23](https://user-images.githubusercontent.com/90494/132584458-a709dfe0-dc92-46f1-89f9-d3d5f7952abb.jpeg)

i was able to reproduce this in a bare react-native app also, so it appears to be a bug in the upstream Image component. the error reported in the Image `onError` callback is just "Android internal error" 🤔
