### ISSUE TITLE
expo-facebook events are not displaing in the app events manager

### ISSUE THREAD

**Issue by futureinapps** [expo/expo#14278]
### Summary

When I'm calling `logEventAsync` on iOS events do not display in AppEvents Manger, but on Android work perfectly

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /Users/user/.rvm/rubies/ruby-2.5.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 19, 23, 25, 26, 27, 28, 29, 30
        Build Tools: 25.0.2, 26.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1 
      react-native: ^0.64.2 => 0.64.2 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. I've set everything from facebook guide to the info.plist file (FBAppid, ClientToken, SKAdNetwork settings)
2. I'm calling this in component did mount of root component (i've tried different variations but they are not working):

```
public static async configureFBSDK() {
    if (Platform.OS === 'ios') {
      await Facebook.setAutoLogAppEventsEnabledAsync(false);
      await Facebook.setAdvertiserIDCollectionEnabledAsync(false);
      await Facebook.setAdvertiserTrackingEnabledAsync(false);
      const ATT_CHECK = await check(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY);
      if (ATT_CHECK === RESULTS.DENIED) {
        const ATT = await request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY);
        if (ATT === RESULTS.GRANTED) {
          await Facebook.setAdvertiserTrackingEnabledAsync(true);
          await Facebook.setAdvertiserIDCollectionEnabledAsync(true);
          await Facebook.setAutoLogAppEventsEnabledAsync(true);
          await Facebook.initializeAsync({});
        }
      } else if (ATT_CHECK === RESULTS.GRANTED) {
        await Facebook.setAdvertiserTrackingEnabledAsync(true);
        await Facebook.setAdvertiserIDCollectionEnabledAsync(true);
        await Facebook.setAutoLogAppEventsEnabledAsync(true);
        await Facebook.initializeAsync({});
      }
    } else {
      await Facebook.initializeAsync({});
    }
  }
}
```

**Comment by motogod** [comment]
same issue here

package.json:
```
{
  "name": "testexpofacebook",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~43.0.2",
    "expo-facebook": "~12.0.3",
    "expo-status-bar": "~1.1.0",
    "expo-tracking-transparency": "~2.0.3",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

Here is my step for iOS:

1. expo init testExpoFacebook
2. expo install expo-facebook
3. set iOS bundle id: hos.exp.Exponent on Facebook iOS dashboard
4. expo install expo-permissions
4. edit app.json
```
{
  "expo": {
    "name": "testExpoFacebook",
    "slug": "testExpoFacebook",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "infoPlist": {
        "NSUserTrackingUsageDescription": "need permissions"
      }
    },
    "android": {
      "package": "com.testMyExpo.myExpo",
      "versionCode": 1,
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "facebookAppId": "<MY_FACEBOOK_DASHBOARD_ID>",
    "facebookAutoLogAppEventsEnabled": true,
    "plugins": [
      [
        "expo-tracking-transparency",
        {
          "userTrackingPermission": "This identifier will be used to deliver personalized ads to you."
        }
      ]
    ]
  }
}
```
App.js

import React, {useEffect} from 'react';
import {StyleSheet, Text, View, Platform, TouchableOpacity} from 'react-native';
import * as Facebook from 'expo-facebook';
import {
  requestTrackingPermissionsAsync
} from 'expo-tracking-transparency';

```
export default function App() {
  Facebook.initializeAsync({
    appId: '<<MY_FACEBOOK_DASHBOARD_ID>>',
  });

  useEffect(() => {
    (async () => {
      const {status} = await requestTrackingPermissionsAsync();
      if (status === 'granted') {
        console.log('Yay! I have user permission to track data');
      } else {
      }
    })();
  }, []);

  const testLog = async () => {
    console.log('testLog 1');
    if (Platform.OS === 'android') {
      console.log('testLog android');
      Facebook.logEventAsync('testAndroidEvent', {
        testAndroidKey: 'testAndroidValue',
      })
        .then((v) => console.log('testLog v', v))
        .catch((e) => console.log('testLog e', e));
    } else {
      Facebook.logEventAsync('testIOSEvent', {testIOSKey: 'testIOSValue'})
        .then((v) => console.log('testIOSEvent v', v))
        .catch((e) => console.log('testIOSEvent e', e));
      console.log('testLog ios');
    }
  };

  return <SomeView onPress={() => testLog()} />
  );
}
```
Android simulator and device: 
testLog function can display event on Facebook event manager dashboard 

iOS simulator and device: 
testLog function can't display event on Facebook event manager dashboard  after I have user permission to track data permission.

**Comment by crjc** [comment]
I am also experiencing this issue. Android works fine, iOS not at all.

**Comment by amberv0** [comment]
up for this issue. I tried pretty much everything, and still seeing no events. In Facebook it's also showing this
![image](https://user-images.githubusercontent.com/11645756/150592998-da528746-f2a5-457e-8d57-62717658ffb4.png)

**Comment by fes300** [comment]
same here, not working at all on iOS

**Comment by Lucas-Meowtel** [comment]
Any update?

**Comment by amberv0** [comment]
It's insane how such an important integration (as it's needed to run facebook ads with conversion optimization) is not fixed for MONTHS. I guess I just shouldn't use Expo for my next project, to avoid this kind of problems.

**Comment by brentvatne** [comment]
we recommend using react-native-fbsdk-next: https://github.com/thebergamo/react-native-fbsdk-next/

see the [expo installation instructions](https://github.com/thebergamo/react-native-fbsdk-next/#expo-installation)

we are deprecating expo-facebook in sdk 45 and removing it in sdk 46 because there is no need to duplicate efforts now that with EAS Build and expo-dev-client it's possible to use react-native-fbsdk-next in managed apps
