### ISSUE TITLE
Android  With Expo - com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by pabeda-bt** [expo/expo#1427]
### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: 24.0.0 => 24.0.0
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/pabeda-7362d136-53a8-499b-89bd-586ea26beab0.tar.gz

We are working on a detached version of expo on Android

### Steps to Reproduce
We are trying to use a 3th party library in android project. Here is what I do in my build gradle file.
```
...
repositories {
  maven { url 'https://maven.fabric.io/public' }
  maven { url 'https://dl.bintray.com/getpoi/maven/' }
}
...
```

```
...
dependencies {
  compile 'com.getpoi:POIBeaconSDK:3.7.0'
...
```
```
...
android {
  compileSdkVersion 26
  flavorDimensions "default"
  defaultConfig {
    applicationId 'com.pabeda.catchman'
    targetSdkVersion 25
    minSdkVersion 19
    versionCode 2
    versionName '1.0.2'
    multiDexEnabled true
...
```
And here is my full grade file : https://paste.ubuntu.com/p/wjp7xnZvMr/

Here is what I am adding to MainApplication.java

```
  @Override
  protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    MultiDex.install(this);
  }
```
as shown here : https://developer.android.com/studio/build/multidex.html#mdex-gradle

(Write your steps here:)

1. detach expo
2. add the lines to grade on android studio project
3. clean and rebuild project

### Expected Behavior
Expected result is building the project successfully. 

(Write what you thought would happen.)

### Actual Behavior
We are getting  this error : 

```
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDev19Debug'.

java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

**Comment by fxfactorial** [comment]
I don't think you need to do this `   MultiDex.install(this);` because we already do in expokit

**Comment by pabeda-bt** [comment]
No way, using or not using MultiDex.install(this) not helps me :(

**Comment by AdamJNavarro** [comment]
Hey @pabeda-bt,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
