### ISSUE TITLE
Can build Android app since Expo SDK42

### ISSUE THREAD

**Issue by TomCorvus** [expo/expo#14283]
### Summary

When I try to build the Android App with AppCenter and Expo SDK42, there is an error with `@unimodules/react-native-adapter`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

``` Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 3.0.1 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: ~0.64.2 => 0.64.2 
      react-native-web: ^0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Hi 👋 

I updated my project from SDK41 to SDK42 and I have an issue to build the Android App with AppCenter.
I find this similar issue and this comment but I did all steps and nothing's working:
https://github.com/expo/expo/issues/13475#issuecomment-877296024

```
/Users/runner/work/1/s/packages/project1/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/ModuleRegistryAdapter.java:26: error: cannot find symbol
    mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);
                                                                  ^
  symbol:   class ExpoModulesPackageList
  location: class org.unimodules.adapters.react.ModuleRegistryAdapter
1 error
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unimodules-react-native-adapter:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I try with NodeJS 12 and 14, clean .gradle cache, npm cache, yarn cache, update Gradle to 6.9, remove node_modules folder without success.
The version of react-native-adapter:
```yarn why @unimodules/react-native-adapter
 └─ react-native-unimodules@npm:0.14.6
   └─ @unimodules/react-native-adapter@npm:6.3.5 (via npm:~6.3.4)
```

Sadly, this command `./gradlew clean assembleRelease` is working and I can't build on AppCenter.

Is there something I can do to build the app with AppCenter without this error?

Thanks for your help and your reply.

**Comment by brentvatne** [comment]
are you saying that building this locally works but on appcenter it doesn't? if so, you should debug what is different about running on appcenter vs your local machine. perhaps some caching is occurring causing the old version to be used.

**Comment by TomCorvus** [comment]
Hi @brentvatne,

Thanks for your reply. I sent a ticket to AppCenter support. I really think that something's wrong during process. Maybe cache or something.

I close this issue for now.
