### ISSUE TITLE
GeoLocation dont work on Android

### ISSUE THREAD

**Issue by Casy** [expo/expo#1428]
Hi, im having a problem with expo and GeoLocation on an Android device, i try to get the position but the callback never get called

     import { Constants, Location, Permissions } from 'expo';

     let { status } = await Permissions.askAsync(Permissions.LOCATION);
     console.log('status', status);
     let providers = await Location.getProviderStatusAsync()
     console.log('providers', providers);

     navigator.geolocation.getCurrentPosition(
       localizacion => console.log('localizacion', localizacion),
       error => console.log('err', err)
     );

    let position = await Location.getCurrentPositionAsync({})
    console.log('position', position);

This is the result:
> status granted

> providers {networkAvailable: true, passiveAvailable:
> true, gpsAvailable: true, locationServicesEnabled: true}

I try setting a google api key, but does the same

This are my dependencies:

      "dependencies": {
        "expo": "^23.0.0",
        "react": "16.0.0",
        "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz"
       } 

    expo -> "sdkVersion": "23.0.0"

**Comment by tcdavis** [comment]
Does this example work for you: https://snack.expo.io/rk4Uzc4vM?

**Comment by aalices** [comment]
Can you also check out my comment here: https://github.com/expo/expo/issues/426#issuecomment-353018163 ?
