### ISSUE TITLE
Expo crashes On iOS build (standalone)

### ISSUE THREAD

**Issue by addtek** [expo/expo#14292]
### Summary

I have recently upgraded my project form Expo SDK 31 to 42, together with all packages.
After building iOS `.ipa` file and uploaded to TestFlight using Transporter, when I then download the  app, it crashes immediately after `MapView` gets rendered. But this crash doesn't happen on simulator during development.

I have tried to debug this issue with several different approaches but yet nothing really helpful.
(Just be sure I have followed all the required instructions for using react-native-map in Expo)

## This my app.json config for ios
![Screen Shot 2021-09-04 at 7 20 48 PM](https://user-images.githubusercontent.com/47563562/132112987-58df4dec-46af-47b2-9a06-a7ac1662c221.png)

## Crash log from AppStoreConnect
<img width="487" alt="Screen Shot 2021-09-04 at 7 22 59 PM" src="https://user-images.githubusercontent.com/47563562/132112989-dc964b9b-01b8-4afc-a205-064ccd7b9b48.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.0

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.5 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.14 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Create a new project
Add react-native-google-map
Render a sample <MapView>
run `expo build:ios`

**Comment by brentvatne** [comment]
we need a reproducible example. 

try following these steps again from scratch: https://docs.expo.dev/versions/latest/sdk/map-view/#deploying-google-maps-to-an-ios-standalone
