### ISSUE TITLE
`scheduleNotificationAsync` ignores `minute` if `0`

### ISSUE THREAD

**Issue by josephstein** [expo/expo#14293]
### Summary

When attempting to set a scheduled notification with `minute` set to `0`, it is ignored and instead the current time's minute is captured:

```
await scheduleNotificationAsync({
  content: {
    title: 'Look at that notification',
    body: "I'm so proud of myself!",
  },
  trigger: {
    hour: 9,
    minute: 0,
    repeats: true,
  },
})
```

For example, if this code executes at 11:28am local time, the trigger will actually be set to figure at 9:28 (not 9:00 as expected). This is likely due to javascript's falsy behavior for `0`'s.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.0.0/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

First, ensure `Notifications.getPermissionsAsync()` is called and is `authorized`. Then somehow trigger the following code block:

```
```
await scheduleNotificationAsync({
  content: {
    title: 'Look at that notification',
    body: "I'm so proud of myself!",
  },
  trigger: {
    hour: 9,
    minute: 0,
    repeats: true,
  },
})
```

**Comment by cruzach** [comment]
tested on iOS and android with this snack, and wasn't able to reproduce

- https://snack.expo.dev/@charliecruzan/14293
