### ISSUE TITLE
Can't use Reanimated 2 in my Expo project.

### ISSUE THREAD

**Issue by buitrbao222** [expo/expo#14317]
### Summary

So I followed [Expo's Reanimated guide](https://docs.expo.dev/versions/latest/sdk/reanimated/#installation) but I stumbled upon this error:
`Error: If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation`

This error only appears on a local environment.
I replicated the whole codebase onto Snack and started the app on Expo Go totally fine.
Here's my Snack: https://snack.expo.dev/@buitrbao222/expo-reanimated-2

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Step 1: Create an Expo project (I used Managed workflow - blank)

Step 2: Run `expo install react-native-reanimated`

Step 3: Add `plugins: ['react-native-reanimated/plugin']` into `babel.config.js`
Your `babel.config.js` file should now look like this:
```javascript
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
```

Step 4: Copy & paste the whole code block from the [API Usage section](https://docs.expo.dev/versions/latest/sdk/reanimated/#api-usage) into your App.js file (replacing the whole file), and rename the function to App (not sure if this is important or not, but I did it anyway)
Your `App.js` should now look like this:
```javascript
import Animated, {
  useSharedValue,
  withTiming,
  useAnimatedStyle,
  Easing,
} from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React from 'react';

export default function App() {
  const randomWidth = useSharedValue(10);

  const config = {
    duration: 500,
    easing: Easing.bezier(0.5, 0.01, 0, 1),
  };

  const style = useAnimatedStyle(() => {
    return {
      width: withTiming(randomWidth.value, config),
    };
  });

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
      }}
    >
      <Animated.View
        style={[
          { width: 100, height: 80, backgroundColor: 'black', margin: 30 },
          style,
        ]}
      />
      <Button
        title="toggle"
        onPress={() => {
          randomWidth.value = Math.random() * 350;
        }}
      />
    </View>
  );
}
```

Step 5: Run `expo start`

Step 6: Open your app on Expo Go

Step 7: You should now see the following error on your command line preventing the app from opening:
```
Error: If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

Error: If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals
```

**Comment by brentvatne** [comment]
restart metro and clear the cache. `expo start -c`. if this doesn't help, share your project. you can verify that this works as expected with `npx create-react-native-app -t with-reanimated2`

**Comment by buitrbao222** [comment]
> restart metro and clear the cache. `expo start -c`. if this doesn't help, share your project. you can verify that this works as expected with `npx create-react-native-app -t with-reanimated2`

That is my whole project. I'm just trying out Reanimated for the first time. Running `expo start -c` didn't change anything.
`npx create-react-native-app -t with-reanimated2` didn't work too.
Still the same logs with error when I start the app:
```
If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation
at node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

Error: If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation

This error is located at:
    in AnimatedStyleUpdateExample (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

Error: If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation

This error is located at:
    in AnimatedStyleUpdateExample (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals
```

**Comment by buitrbao222** [comment]
Why is this happening to me
![image](https://user-images.githubusercontent.com/57611063/132728382-bf2dd646-2352-443a-9de7-82ba2a4fafbc.png)

**Comment by brentvatne** [comment]
i just ran `npx create-react-native-app -t with-reanimated2` then cd'd into the directory and ran `expo start`, i opened it in ios simulator and it worked as expected.

it's hard to say what is happening on your machine. if it's just this exact project as referenced above, then it seems likely to be a caching error. this error is happening because the babel plugin isn't being used, and i'm not sure why that would be the case aside from some caching issue.

**Comment by buitrbao222** [comment]
> i just ran `npx create-react-native-app -t with-reanimated2` then cd'd into the directory and ran `expo start`, i opened it in ios simulator and it worked as expected.
> 
> it's hard to say what is happening on your machine. if it's just this exact project as referenced above, then it seems likely to be a caching error. this error is happening because the babel plugin isn't being used, and i'm not sure why that would be the case aside from some caching issue.

I'm running on my Android device, Redmi Xiaomi Note 5 Pro with Android 9.
It's happening on all projects using Reanimated 2 I could find online, even the with-reanimated2 example from expo.
I even reinstalled Node.js and expo-cli but nothing has changed.
Thanks for your help anyways.

**Comment by buitrbao222** [comment]
Found the problem. It was because I was running the app in Remote JS Debugging mode and the new APIs in Reanimated 2 are incompatible with it. After running the app without debugging (`expo start --no-dev`) everything worked as expected.
