### ISSUE TITLE
Unexpected token 'export' when using expo-updates in app.config.js

### ISSUE THREAD

**Issue by cvburgess** [expo/expo#14312]
### Summary

When using expo-updates in the app.config.js file (following the docs) I get this error:

```
Unexpected token 'export'
.../node_modules/expo-updates/build/index.js:1
export * from './Updates';
```

This makes sense as the process is probably not being run in an ESM context.

How should I proceed?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.2.0 - /usr/local/bin/node
      npm: 7.20.5 - /usr/local/bin/npm
      Watchman: 2021.08.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.15.0 => 0.15.0 
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Add `import * as Updates from "expo-updates";` or `const Updates = require("expo-updates/build/Updates");` to `app.config.js`.

Running any expo command will now fail.

**Comment by brentvatne** [comment]
you can't import expo-updates from app.config.js, it is not a react-native environment, it is just a plain node environment
