### ISSUE TITLE
ImagePicker - Quality of the image

### ISSUE THREAD

**Issue by yonjuukyuu** [expo/expo#14320]
### Summary

I'm using the ImagePicker.launchImageLibraryAsync and i want the image size in (kb/mb) to decrease, and i assume the quality between 0 -1 does that ?
 im trying to compress it with quality: 0 and maxWidth/maxHeight but at the end, the image stays the same around 1.5mb to 5mb. Any chance to compress it below 150kb its an avatar image would make no sence to upload a 5mb photo for an avatar

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42.0

### Environment

 Expo CLI 4.5.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\user\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-navigation: ^4.4.3 => 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

  let result = await ImagePicker.launchImageLibraryAsync({
            mediaTypes: ImagePicker.MediaTypeOptions.Images,
            allowsEditing: true,
            aspect: [3, 3],
            quality: 0,
            maxWidth: 150,
            maxHeight: 150,
          });

**Comment by brentvatne** [comment]
use expo-image-manipulator or some code on your own server to compress it if you want to modify it further outside of expo-image-picker
