### ISSUE TITLE
Problem Prelod asset SVG in Android

### ISSUE THREAD

**Issue by robertobrogi** [expo/expo#1432]
Hi, i have a problem with prelod asset in Android... i use React.native-uri for icon UI and in app.js create the  _cacheResourcesAsync... but i have error in prelod app in EXPo

React:16.2.0
Expo 25.0.0

`
async componentWillMount() {

        const [dummy, deviceCountry, currentTimeZone] = await Promise.all([
            I18n.initAsync(),
            Expo.Util.getCurrentDeviceCountryAsync(),
            Expo.Util.getCurrentTimeZoneAsync(),
            this._loadAssetsAsync(),
            this._cacheResourcesAsync()
        ]);

        this.setState({appIsReady: true}); // when all above promises above are resolved
    }`

` 
_loadAssetsAsync = async () => {
        //await I18n.initAsync();
        await Font.loadAsync({
            KlavikaRegular: require('./assets/fonts/Klavika/KlavikaRegular.otf'),
            KlavikaBold: require('./assets/fonts/Klavika/KlavikaBold.otf'),
            KlavikaLight: require('./assets/fonts/Klavika/KlavikaLight.otf'),
            ProximaNovaSemibold: require('./assets/fonts/ProximaNova/ProximaNovaSemibold.otf'),
            ProximaNovaRegular: require('./assets/fonts/ProximaNova/ProximaNovaRegular.otf'),
        });
    };

    _cacheResourcesAsync = async () => {
        const images = [
            require('./assets/images/edit.svg'),
            require('./assets/images/F_icon.svg'),
            require('./assets/images/world.svg'),
            require('./assets/images/align-justify.svg'),
            require('./assets/images/sign-out.svg'),
            require('./assets/images/btronIcon/b_view.png'),
            require('./assets/images/btronIcon/b_home.png'),
            require('./assets/images/news/money-bill.svg'),
            require('./assets/images/news/calendar-alt.svg'),
            require('./assets/images/news/clock.svg'),
            require('./assets/images/news/globe.svg'),
            require('./assets/images/news/map-marker-alt.svg'),
            require('./assets/images/info/newspaper.svg'),
            require('./assets/images/info/simulatore.jpg'),
            require('./assets/images/info/lottiDaVendere.jpg'),
            require('./assets/images/info/iconPlanet.svg'),
            require('./assets/images/info/play-circle.svg'),
            require('./assets/images/info/citylivecamera1.jpg'),
            require('./assets/images/info/cctv.svg'),
            require('./assets/images/info/avanzamento.jpg'),
            require('./assets/images/info/cityinfoplanetambientecostruito.jpg'),
            require('./assets/images/info/cityinfoplanetrisorseeco.jpg'),
            require('./assets/images/info/cityinfoplanetsistemitecnologici.jpg'),
            require('./assets/images/info/cityinfoplanetsocieta.jpg'),
            require('./assets/images/info/eye.svg'),
            require('./assets/images/info/lottiVenduti.jpg'),
            require('./assets/images/info/pilastroAmbienteCostruito.svg'),
            require('./assets/images/info/pilastroRisorseTecnologiche.svg'),
            require('./assets/images/info/pilastroRisosrseEnergetiche.svg'),
            require('./assets/images/info/pilastroSocieta.svg'),
            require('./assets/images/tabBar/building.svg'),
            require('./assets/images/tabBar/user.svg'),
            require('./assets/images/tabBar/home.svg'),
            require('./assets/images/tabBar/life-ring.svg'),
            require('./assets/images/tabBar/services.svg'),
            require('./assets/images/tabBar/users.svg'),
            require('./assets/images/arrow/chevron-right.svg'),
            require('./assets/images/arrow/chevron-left.svg'),
            require('./assets/images/searchInputBox/search.svg'),
            require('./assets/images/checkbox/check.svg'),
            require('./assets/images/security/user.svg'),
            require('./assets/images/security/plus.svg'),
            require('./assets/images/security/sync.svg'),
            require('./assets/images/security/map-marker.svg'),
            require('./assets/images/security/phone.svg'),
            require('./assets/images/cardHome/thermometer-half.svg'),
            require('./assets/images/cardHome/tint.svg'),
            require('./assets/images/cardHome/plug.svg')
        ];

        const cacheImages = images.map((image) => {
            return Asset.fromModule(image).downloadAsync();
        });

        return Promise.all(cacheImages)

    }`

`
render() {

        if (!this.state.appIsReady) {
            return (
                <AppLoading
                    onError={console.warn}
                />
            );
        }

        return (
            <Provider store={store}>
                <SafeAreaView style={styles.safeArea}>
                    <Root/>
                </SafeAreaView>
            </Provider>
        );
    }`

In IOS is all Fine..... 

the error is: 

Uncaught Error: unexpected url: file///data/user/0/host.exp.exponent/cache/ExperienceData/nameApp/ExponentAsset.svg

**Comment by tcdavis** [comment]
Can you reproduce this in https://snack.expo.io?

**Comment by GregoryBabonaux** [comment]
Got the same problem here. 

```
     Asset.loadAsync([
        require('./assets/images/user.svg'),
        require('./assets/images/settings.svg'),
        require('./assets/images/logout.svg'),
        require('./assets/images/security.svg'),
         ...
      ]),
```

No error on IOS but, on Android, i've an error : 

console.error: "got error", {"line": 22102, "column": 31" ...} in node_modules/expo/tools/hashAssetFiles.js

I use react-native-remote-svg for displaying SVGs from assets folder. It works perfectly on Android as long i not use loadAsync.

Are SVG compatibles with loadAsync ?

**Comment by Roshdy** [comment]
upgraded to sdk 32, then rolled back to 31. Started facing the same issue
