### ISSUE TITLE
Cached document from DocumentPicker doesn’t exist

### ISSUE THREAD

**Issue by Devalo** [expo/expo#14335]
### Summary

Hello. I've posted a new thread on the forums some weeks ago, regarding cached documents from DocumentPicker.
You can find the thread here: https://forums.expo.dev/t/cached-document-from-documentpicker-doesnt-exist/55975

Getting a document:
```const doc = await DocumentPicker.getDocumentAsync()```
prints out:
```
Object {
  "name": "sample.pdf",
  "size": 3028,
  "type": "success",
  "uri": "/data/user/0/host.exp.exponent/cache/ExperienceData/%40stephanbv%2FtestAppDocumentPicker/DocumentPicker/ba010cfe-6faa-402d-9f4f-728bfa12820b.pdf",
}
```

If I check if the file exists:
``` const info = await FileSystem.getInfoAsync(doc.uri)```
It doesn't: 
```
Object {
  "exists": false,
  "isDirectory": false,
}
```
if I add ```copyToCacheDirectory: false``` to the ```.getDocumentAsync()```method, I get:
```
Object {
  "name": "IMG_20210827_175330.jpg",
  "size": 28932,
  "type": "success",
  "uri": "content://com.android.providers.media.documents/document/image%3A18",
}
```
And it does exist:
```
Object {
  "exists": true,
  "isDirectory": false,
  "size": 28932,
  "uri": "content://com.android.providers.media.documents/document/image%3A18",
}
```
This, however doesn't help me, as I can't seem to figure out a way to turn that uri to a base64 string.

If I use the ```ImagePicker.launchCameraAsync()``` I get the correct file uri, and the document exists.

Something tells me there is something wrong with DocumentPicker. Any suggestions ?

Link to test project: https://github.com/Devalo/expo-document-error

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      npm: 6.14.12 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 30, 31
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/Devalo/expo-document-error

**Comment by brownbl1** [comment]
I can also reproduce this on the latest sdk with a new sample project. The thing is, the file does exist, the uri that's returned is just wrong. You can parse off the file name and do `FileSystem.cacheDirectory + 'DocumentPicker' + '/' + fileName` and you'll likely find that it works as espected.
