### ISSUE TITLE
Cache error

### ISSUE THREAD

**Issue by nikasvan** [expo/expo#1433]
### Environment

https://exp-xde-diagnostics.s3.amazonaws.com/nikasv-f3789f7a-44ae-4a17-87c8-bd429a9fa18e.tar.gz.

### Steps to Reproduce

After running `npm start` and the `i` I am getting some error with cache http://prntscr.com/ifkuz6. This happened all of a sudden while working.

### Expected Behavior

To run the app as usual

**Comment by tcdavis** [comment]
Does running `watchman watch-del-all && rm -rf node_modules && rm -fr $TMPDIR/react-* && npm i` resolve it for you?

**Comment by nikasvan** [comment]
No luck :( @tcdavis

**Comment by nikasvan** [comment]
@tcdavis Stupid mistake, had unnecessary import in App.js.
