### ISSUE TITLE
[expo-ads-admob][bare workflow][Android] NullPointerException Context cannot be null

### ISSUE THREAD

**Issue by yaroslavnikiforov** [expo/expo#14336]
### Summary

On Android sometimes users get NullPointerException. Here is the stack trace from Sentry:

```
com.google.android.gms.common.internal.Preconditions in checkNotNull at line 11
com.google.android.gms.ads.InterstitialAd in <init> at line 3
expo.modules.ads.admob.AdMobInterstitialAdModule in recreateInterstitialAdWithAdUnitID at line 143
expo.modules.ads.admob.AdMobInterstitialAdModule in access$100 at line 21
expo.modules.ads.admob.AdMobInterstitialAdModule$1 in run at line 78
android.os.Handler in handleCallback at line 938
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loop at line 246
android.app.ActivityThread in main at line 8512
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 602
com.android.internal.os.ZygoteInit in main at line 1139
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
"react-native": "0.63.4",
"expo-ads-admob": "10.0.4",
"react-native-unimodules": "^0.12.0",
```

Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.14.0 => 16.14.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: 0.63.4 => 0.63.4
      react-navigation: 4.0.10
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

It is hard to reproduce, but this happens in about 2% of cases.

**Comment by cruzach** [comment]
This unlikely to get attention without a reproducible demo

**Comment by yaroslavnikiforov** [comment]
So the crash happens on this line: 
```
private void recreateInterstitialAdWithAdUnitID(String adUnitID) {
    if (mInterstitialAd != null) {
      mInterstitialAd = null;
    }

    mInterstitialAd = new InterstitialAd(mActivityProvider.getCurrentActivity()); // crash here
    mInterstitialAd.setAdUnitId(adUnitID);

    new Handler(Looper.getMainLooper()).post(new Runnable() {
...
```
under `expo-ads-admob/android/src/main/java/expo/modules/ads/admob/AdMobInterstitialAdModule.java`

Any ideas why this can happen and maybe it is possible to add some checks to prevent this? What is missing when an error fires?

**Comment by yaroslavnikiforov** [comment]
Pull request: [https://github.com/expo/expo/pull/14477](https://github.com/expo/expo/pull/14477)
