### ISSUE TITLE
iOS MapView with Google Provider Crash expo 25.0.0

### ISSUE THREAD

**Issue by ahmetabdi** [expo/expo#1434]
iOS MapView with Google Provider Crash expo 25.0.0

```
import { MapView } from 'expo';

class MapScreen extends Component {
  render() {
    console.log(MapView.PROVIDER_GOOGLE) = 'google'
    return(
      <View style={styles.container}>
        <MapView provider={MapView.PROVIDER_GOOGLE}>
        </MapView>
      </View>
     )
  )
}
```

**Comment by terribleben** [comment]
Can you provide a [snack](https://snack.expo.io/) reproducing this?

Have you tried the [community example](https://expo.io/@community/native-component-list) which includes a [google map demo screen](https://github.com/expo/native-component-list/blob/master/screens/MapsScreen.js)? As far as I know it's working fine.
