### ISSUE TITLE
MediaLibrary.getAssetInfoAsync does not provide location data (gps) on Android 11

### ISSUE THREAD

**Issue by mik0205** [expo/expo#14361]
### Summary

await MediaLibrary.getAssetInfoAsync(asset, {});

does not provide location data (gps) on Android 11, on Android 10 it works:

Android11:

asset: name=DSC_0866_1.JPG id=6156 creationTime=1595940961000 location= **null**
asset: name=DSC_0865_1.JPG id=6332 creationTime=1595940935909 location= **null**
asset: name=DSC_0864_1.JPG id=6215 creationTime=1595940929505 location= **null**

Android 10:

asset: name=DSC_0866_1.JPG id=1957 creationTime=1595940961884 location= **{"longitude":10.199166388888889,"latitude":56.153890277777776}**

asset: name=DSC_0865_1.JPG id=1801 creationTime=1595940935909 location= **{"longitude":10.199166388888889,"latitude":56.153890277777776}**

asset: name=DSC_0864_1.JPG id=1448 creationTime=1595940929505 location= **{"longitude":10.199166388888889,"latitude":56.153890277777776}**

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

SDK42

### Environment

 Expo CLI 4.8.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@mik/testmedialibrarylocationdatas

**Comment by cruzach** [comment]
maybe this is due to new location permission on Android 11? c @byCedric maybe

**Comment by ajsmth** [comment]
agreed ^ although it looks like this is as recent as Android 10 -- see: https://developer.android.com/training/data-storage/shared/media#media-location-permission
