### ISSUE TITLE
App uses wrong JS bundle after publish then version update

### ISSUE THREAD

**Issue by peroh** [expo/expo#14372]
### Summary

After updating an app via the app store to a new version (and release channel), the updated app uses the JS bundle from a previous release channel.

Deleting the app and re-installing uses the the new bundle on the correct release channel.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41.0.0

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
      npm: 7.20.6 - ~/.nvm/versions/node/v14.16.1/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- EAS build app version 1.0 to release channel "1.0"
- Submit to store
- Publish an update to release channel "1.0"
- EAS build app version 1.1 to release channel "1.1"
- Submit to store
- Update from version 1.0 to 1.1 via app store
- App still uses JS bundle on release channel "1.0"
- Delete app and re-install
- App now uses JS bundle on release channel "1.1"

**Comment by brentvatne** [comment]
are you using `runtimeVersion` at all?

**Comment by peroh** [comment]
> are you using `runtimeVersion` at all?

I don't believe so? We just set a `releaseChannel` in `eas.json` and publish to that via `expo publish`.

I am using `expo-updates` to periodically check for/fetch/apply updates.

**Comment by jkhales** [comment]
taking a look. Thanks for the write up!

**Comment by peroh** [comment]
> taking a look. Thanks for the write up!

Thanks @jkhales - keen to know if you can reproduce!

**Comment by jkhales** [comment]
@peroh repro'd and identified a fix. Working on PR now.

**Comment by soda-michael** [comment]
Hello, @jkhales. Can I know the status of this issue? We are suffering from this issue too.
