### ISSUE TITLE
Expo.GLView readPixels return array of zeros 

### ISSUE THREAD

**Issue by tcdavis** [expo/expo#1437]
### Steps to Reproduce

see getImageData in: https://snack.expo.io/@bacon/get-image-data-rgba-expo-+-exgl
and the thread here: https://forums.expo.io/t/expo-glview-readpixels-return-array-of-zeros/7275
and here: https://forums.expo.io/t/cant-readpixels-in-gl-after-drawing-an-image/6165

### Expected Behavior

Should return the pixel data

### Actual Behavior

readPixels returns an array containing 0

### Reproducible Demo

https://snack.expo.io/@bacon/get-image-data-rgba-expo-+-exgl

**Comment by ohnoleo** [comment]
Running into this issue myself.
Can read from a custom-created frame-buffer, but when I do so with the default on ios I get all 0s returned and gl.getError() returns gl.INVALID_OPERATION (1282)

**Comment by Matt-F-Wu** [comment]
Is there any updates on this issue? @ohnoleo  Hi, how did you create/read from custom-created framebuffer? Thanks :-)
