### ISSUE TITLE
Moment.js Crashing Expo on iOS

### ISSUE THREAD

**Issue by lordcatalien** [expo/expo#1438]
### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.0.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9Q98q
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

App's Target: Android, iOS

### Steps to Reproduce

I've required moment.js in a component
`const moment = require('moment');`

It works fine on iOS Emulator, but when I run on the device, the app freezes and eventually Expo crashes. 

### Expected Behavior

I thought it would work the same on the device (iPhone 6) as it does in the iOS Emulator

### Actual Behavior

This is the code for my component:
https://snack.expo.io/BJPjKyBPG

And my package JSON:
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "axios": "^0.17.1",
    "expo": "^25.0.0",
    "moment": "^2.20.1",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-timer": "^1.3.1",
    "react-navigation": "^1.0.0-beta.21"
  },
  "devDependencies": {}
}

**Comment by Naoto-Ida** [comment]
@lordcatalien Mind me asking how you figured this out?

**Comment by lordcatalien** [comment]
@Naoto-Ida I don't know. It just started working without me making changes. Maybe it was an XDE Caching issue?
