### ISSUE TITLE
[expo-sqlite] - executeSql operation blocks UI thread(keyboard typing)

### ISSUE THREAD

**Issue by rholic-openpath** [expo/expo#14381]
### Summary

Our app has a search field to find foods.

On every change in the text field, we wait 500ms and then we execute a search query in expo-sqlite.

While the executeSql function is executing, our keyboard keys are delayed as if the searching is blocking the UI thread.

Is this a limitation of the library? of iOS sqllite queries? Is there a way we can work around this, without making the user hit a search button after they finish typing, so we can keep the searching occurring as they type letters?

Note: the queries take around 300ms to 500ms, so the delay of typing a new key is while those are occuring

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.10.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
const onChangeSearchBarText = (text) => {
            clearTimeout(searchDebounceTimer.current)
            searchDebounceTimer.current = setTimeout(() => {
               searchByString(text)
            },  500)
  }

const searchByString = (searchString ) => {
           db.transaction(
                    tx => {
                        tx.executeSql(
                            searchString + " LIMIT 1"
                            ,
                            [],
                            (txObj, resultSet) => {
                                let _array = resultSet.rows._array
                                setSearchResults(_array)
                            }
                        );
                    },
                    (error) => {
                        console.log("Error searching database by string", error);
                    },
                    (success) => {
                        console.log("Successfully searched database")
                    }
                );

}

return <View> 
<TextInput
         onChangeText={onChangeSearchBarText}
</TextInput>
</View>
```

**Comment by AdamJNavarro** [comment]
Hey @rholic-openpath, I don't see any programmed delay  on executing the queries in your code as you mentioned in your description. Right now it looks like your executing a query every time the text input value changes. Can you provide a complete reproduction case that we can run on our end locally?

**Comment by rholic-openpath** [comment]
Sure,  i've edited the initial post to show the programmed delay. Let me know if this works for you.
