### ISSUE TITLE
NSUserTrackingUsageDescription translations don't seem to work with app.json

### ISSUE THREAD

**Issue by jaamofi** [expo/expo#14392]
### Summary

**Expected behavior**
According to [documentation](https://docs.expo.dev/distribution/app-stores/?redirected#localizing-your-ios-app) the permission query strings for ios should be translatable via app.json ios.infoPlist -object and defined translation files.

If I understood correctly, setting up app.json as described and adding NSUserTrackingUsageDescription to translation files should result in a translated description string in App Tracking Transparency prompt.

**Actual behavior**
Setting up NSUserTrackingUsageDescription directly in app.json ios.infoPlist object works fine, attempting to have translated versions as described in documentation will result in prompt having some kind of default string from expo-tracking-transparency -library.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.20.1 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/.npm-global/bin/yarn
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 30
        Build Tools: 30.0.3, 31.0.0
        System Images: android-28 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

**app.json**

`
{
  "expo": {
    ...
    "ios": {
      "infoPlist": {
        "CFBundleAllowMixedLocalizations": true
      }
    },
    "locales": {
      "en": "./locales/en.json",
      "fi": "./locales/fi.json"
    }
  }
}
`

**en.json**
`
{
  "NSUserTrackingUsageDescription": "Lorem ipsum"
}
`

**Test**
Deploy as a stand-alone build and run it either in device or simulator, as Expo Go App always shows a default description in prompt ignoring the app-specific prompt.

**Comment by cruzach** [comment]
is this built with `expo build`, or `eas build`? 

Do other translations work, and it's only `NSUserTrackingUsageDescription` that doesn't? that would rule out any setup issues

**Comment by jaamofi** [comment]
> is this built with expo build, or eas build?

expo build

> Do other translations work, and it's only NSUserTrackingUsageDescription that doesn't? that would rule out any setup issues

Other i18n in the project works, unfortunately for other similar permission descriptions in app.json I cannot say as the project doesn't currently have those and I don't have another project set up just now to test with.

**Comment by cruzach** [comment]
Can you share a link to a github repo that reproduces this? It would help to see your full app.json and translation files

**Comment by jaamofi** [comment]
> Can you share a link to a github repo that reproduces this? It would help to see your full app.json and translation files

Unfortunately not, as it is a client project. If it is required I can try to put up a clean repo at some point. If it's of any help, I managed to track the showing default query to [this file](https://github.com/expo/expo/blob/master/packages/expo-tracking-transparency/plugin/src/withTrackingTransparency.ts).

**Comment by cruzach** [comment]
Yes, that defines the default case, but it doesn't explain why iOS isn't applying the translation. You can modify the default message by passing in `ios.infoPlist.NSUserTrackingUsageDescription` to app.json

**Comment by jaamofi** [comment]
Before setting up a clean repo I re-tried this with separate translation files only for permissions and adding CFBundleDisplayName to them, which seems to have worked, so I suspect using one of the generic translation files for this was somehow problematic. That's pretty much the only thing I didn't try changing last time.

Anyhow thanks for your patience and apologies for the inconvenience!

**Comment by madflanderz** [comment]
I have the same issue. Does anyone knows a solution?
