### ISSUE TITLE
exp build:ios fails when domain name contains hyphen

### ISSUE THREAD

**Issue by steve-prod** [expo/expo#1439]
### Environment

[exp] Generating diagnostics report...
[exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/steve-prod-c9eb726b-9faf-4421-9669-285a24e1c5b3.tar.gz

App's target is iOS

### Steps to Reproduce

app.json file is:
{
  "expo": {
   "name": "Bespoke-Audio",
   "icon": "./favicon.png",
   "version": "0.1.0",
   "slug": "bespoke-audio",
   "sdkVersion": "25.0.0",
   "ios": {
     "bundleIdentifier": "com.bespoke-audio.app"
   },
   "android": {
     "package": "com.bespoke-audio.app"
   }
  }
}

Running 'exp build:ios' fails with the following error:
[exp] Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v25.0.0/guides/configuration.html.
[exp]  • Field: android.package - 'android.package' should be a reverse DNS notation unique name for your app. For example, host.exp.exponent, where exp.host is our domain and Expo is our app..

Error goes away when hyphen is removed from domain.

### Expected Behavior

Build should work for domains containing hyphens.

**Comment by terribleben** [comment]
I believe it is actually [not valid to have a hyphen](https://developer.android.com/guide/topics/manifest/manifest-element.html#package) in your Android package. This does seem to give people [trouble](https://stackoverflow.com/questions/10954030/valid-name-for-android-package-name) who have a hyphen in their domain name, even outside Expo. Sorry about that.

**Comment by steve-prod** [comment]
🤦‍♂️  Sorry.  And thank you!
