### ISSUE TITLE
Pedometer.requestPermissionsAsync() does not open up a window to confirm permissions

### ISSUE THREAD

**Issue by nelarsen97** [expo/expo#14390]
### Summary

Pedometer.requestPermissionsAsync() does not open up a window to confirm permissions, like it does for other libraries, such as when using MediaLibrary.requestPermissionsAsync(). This happens whether or not the proper permissions are listed in android.permissions in the app.json file.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.0

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD  
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ^42.0.3 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ^0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Just run Pedometer.requestPermissionsAsync(), on a bare-bones project with expo-sensors installed. It will not ask for permissions, and will simply return:
Object {
  "canAskAgain": true,
  "expires": "never",
  "granted": true,
  "status": "granted",
}

**Comment by cruzach** [comment]
the `ACTIVITY_RECOGNITION` is auto-granted in ANdroid 9 and below

> If the system-auto grants the android.permission.ACTIVITY_RECOGNITION permission, your app retains the permission after you update your app to target Android 10. However, the user can revoke this permission at any time in system settings.

**Comment by nelarsen97** [comment]
Ah, interesting. I was unaware of this. However, this is not my issue. I am/was running the app on Android 10, and the function still returns as 'auto-granted', with no prompt. I put that in quotes because although the function returns as 'granted', if I go into the app settings, the permission is not granted.

**Comment by Jleeowl** [comment]
> the `ACTIVITY_RECOGNITION` permission is auto-granted in ANdroid 9 and below
> 
> > If the system-auto grants the android.permission.ACTIVITY_RECOGNITION permission, your app retains the permission after you update your app to target Android 10. However, the user can revoke this permission at any time in system settings.

I've tested on Android 10 and above and it seems that the prompt doesn't show.

**Comment by Jleeowl** [comment]
I cannot seem to receive a runtime permission prompt 

> Ah, interesting. I was unaware of this. However, this is not my issue. I am/was running the app on Android 10, and the function still returns as 'auto-granted', with no prompt. I put that in quotes because although the function returns as 'granted', if I go into the app settings, the permission is not granted.

Can confirm that this is the case on my Android 12 as well. The permission for `ACTIVITY_RECOGNITION` does not even appear on the applications permissions manager.

**Comment by lqze** [comment]
This needs to be re-opened.

Pedometer does not work in android.
