### ISSUE TITLE
undefined is not an object (evaluating 'RNLinkedInSessionManager.configure')

### ISSUE THREAD

**Issue by Jmadih** [expo/expo#144]
Hello guys,
I've integrate the linkedIn authentication but i've had this error : 
![error](https://cloud.githubusercontent.com/assets/13162886/25565948/4e14b2ee-2dd1-11e7-8565-9b4fbf33f845.PNG)

My package.json : 
`  "dependencies": {
    "axios": "^0.15.3",
    "expo": "16.0.0",
    "native-base": "^2.0.13",
    "react": "^15.5.4",
    "react-native": "^0.43.4",
    "react-native-linkedin-sdk": "0.0.4",
    "react-native-vector-icons": "^4.0.0",
    "react-navigation": "^1.0.0-beta.9"
  },`

Thank you.

**Comment by btk** [comment]
Package `react-native-linkedin-sdk` is a native package, and expo does not support native packages. If you want to use that package and it is vital for your project, you need to `eject` your app, then add the library that you want to use.

Expo also supports;
- Google authentication: https://docs.expo.io/versions/v16.0.0/sdk/google.html
- Facebook authentication: https://docs.expo.io/versions/v16.0.0/sdk/facebook.html

You might want to use one of them instead linkedin, if doing authentication with linkedin is not vital for your app.

**Comment by dikaiosune** [comment]
@btk thanks for the explanation here.

@Jmadih I'm giving this a close, but we're always evaluating what native modules to include and we may circle back to this at some point.

**Comment by Jmadih** [comment]
@btk @dikaiosune thanks guys !
I guess that Linkedin is not totally compatible with react-native yet.
