### ISSUE TITLE
Branch showShareSheet does nothing

### ISSUE THREAD

**Issue by appjitsu** [expo/expo#1440]
### Environment
"expo": "25.0.0",
"react": "^16.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",

### Steps to Reproduce
```
componentWillMount() {
    this.createBranchUniversalObject();
  }

async createBranchUniversalObject() {
    const { med } = this.props.navigation.state.params;

    this._branchUniversalObject  = await Expo.DangerZone.Branch.createBranchUniversalObject(
      `med_${med._id}`,
      {
        title: med.name,
        metadata: {
          screen: 'MedLinkScreen',
          params: JSON.stringify({ medId: med._id }),
        },
      }
    );
    console.log('branch object', this._branchUniversalObject); <--- i see this
}

async onShareLinkPress(){
    console.log('sharing...'); <--- i see this
    const { med } = this.props.navigation.state.params;

    const shareOptions = {
      messageHeader: med.name,
      messageBody: `I thought you might be interested in this medication...`,
    };
    console.log('shareOptions', shareOptions); <--- i see this
    await this._branchUniversalObject.showShareSheet(shareOptions); <--- nothing happens
}
```

### Expected Behavior
Should show the share dialog

### Actual Behavior
Nothing happens

### Reproducible Demo
none

**Comment by appjitsu** [comment]
OK So this works when the app is deployed to TestFllight, but not in the emulator. Is this on purpose? It's a pain to test if I can't test in the emulator. Anything I can do?

**Comment by terribleben** [comment]
Hey there, sorry about the annoyance. As noted in the [docs](https://docs.expo.io/versions/latest/sdk/branch.html), this API will only work with standalone apps (e.g. those created with `exp build`). It won't work in Expo Client. We wish we could provide it in both situations, but Branch depends on project-specific configuration at the native level before it can do anything.
