### ISSUE TITLE
Image picker gives strange error

### ISSUE THREAD

**Issue by sammy532** [expo/expo#14415]
### Summary

I am using image picker library as shown in the documentation. Instead of uploading the image which I have selected it gives me the following error: 

```
[Unhandled promise rejection: Error: Can not save result to the file.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
at node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-av/build/Audio/Recording.js:113:7 in getPermissionsAsync
at node_modules/expo-av/build/Audio/Recording.js:113:7 in getPermissionsAsync
at node_modules/react-native-gifted-chat/lib/Composer.js:70:24 in <global>
```
My code: 

```
export async function pickImageAsync(onSend) {
  if (await getPermissionAsync(Permissions.CAMERA_ROLL)) {
    let result;
    try {
      result = await ImagePicker.launchImageLibraryAsync({
        allowsEditing: false,
        mediaType: ImagePicker.MediaTypeOptions.Images,
        title: "Select Photo from Gallery",
        quality: 1,
      });
    } catch (error) {
      console.log(error);
    }
    if (result && !result.cancelled) {
      onSend([{ image: result.uri }]);
      return result.uri;
    }
  }
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.11.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.21.1 - ~/.nvm/versions/node/v12.18.4/bin/npm
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Just used the example in the demo

```
export async function pickImageAsync(onSend) {
  if (await getPermissionAsync(Permissions.CAMERA_ROLL)) {
    let result;
    try {
      result = await ImagePicker.launchImageLibraryAsync({
        allowsEditing: false,
        mediaType: ImagePicker.MediaTypeOptions.Images,
        title: "Select Photo from Gallery",
        quality: 1,
      });
    } catch (error) {
      console.log(error);
    }
    if (result && !result.cancelled) {
      onSend([{ image: result.uri }]);
      return result.uri;
    }
  }
}
```

**Comment by Simek** [comment]
Can you try to replicate this issue using Snack? It works correctly for me using this code:
* https://snack.expo.dev/@simek/image-picker

Also can you try to use `requestMediaLibraryPermissionsAsync` from `ImagePicker` instead of `getPermissionAsync` in your code? The example usage is here:
* https://docs.expo.dev/versions/latest/sdk/imagepicker/#usage

**Comment by sammy532** [comment]
It seems I have been trying with corrupted images, so my bad! The code is working fine!

**Comment by stdavis** [comment]
@sammy532 It may be helpful to close this issue.

**Comment by sammy532** [comment]
Closing the issue
