### ISSUE TITLE
[docs] redirecting from browser with custom scheme doesn't work as described

### ISSUE THREAD

**Issue by brownbl1** [expo/expo#14422]
### Summary

In the linking guide, at the very end there is a comment with a code example that describes how to automatically redirect from an https url to a custom scheme in a mobile browser. It uses javascript that doesn't work on Android Chrome. In fact, I haven't been able to find any way to do this in javascript that isn't blocked by the browser. It seems that Chrome considers redirection without user interaction to be a security issue.

The docs should be updated to reflect this state of affairs, or else, if I'm actually missing something, new code should be added that works with the latest Chrome.

Also, the example expo project at https://expo.dev/@community/with-webbrowser-redirect that is linked on that page is not compatible with the latest SDK. It would be nice if it could be updated.

### Link to the related docs page

https://docs.expo.dev/guides/linking/#when-to--not--use-deep

**Comment by mudassir-rafiq-007** [comment]
I'm also facing this issue. I can open app using deep link on iOS from Safari but the same can't be achieved with Chrome for android
