### ISSUE TITLE
Permissions explanations not being overwritten by ios.infoPlist in app.json

### ISSUE THREAD

**Issue by steve-prod** [expo/expo#1443]
I'm trying to get my app published in the Apple App Store.  Pursuant to their feedback, I'm trying to provide a custom description for asking for microphone access.

I'm following procedure from [System permissions dialogs on iOS](https://docs.expo.io/versions/latest/guides/app-stores.html#system-permissions-dialogs-on-ios).

My app.json has the form:

```
{
  "expo": {
     "name": "My App Name",
     "icon": "./favicon.png",
     "version": "0.1.2",
     "slug": "my-app-name",
     "sdkVersion": "25.0.0",
     "ios": {
       "bundleIdentifier": "com.myapp.app",
       "infoPlist": {
           "NSMicrophoneUsageDescription": "This app uses the microphone to record audio messages that maybe sent privately to an individual or published publicly for any user to listen to."
       }
     },
     "android": {
       "package": "com.myapp.app"
     }
  }
}
```

However, when prompting the user for microphone permissions, the app still says "Allow Expo experiences to access your microphone"

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

target is iOS. Tested on an iPhone X.

### Steps to Reproduce

See app.json above.

### Expected Behavior

Text in app.json corresponding to NSMicrophoneUsageDescription's value should be shown rather than the text found [here](https://github.com/expo/expo/blob/master/exponent-view-template/ios/exponent-view-template/Supporting/Info.plist#L37).

**Comment by terribleben** [comment]
Interesting. As far as I know this code hasn't changed in awhile.

Is your project detached (using ExpoKit)?

**Comment by steve-prod** [comment]
Code is publicly available [here](https://github.com/steve-prod/bespoke-audio-mobile).  
I've been using the build process [here](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html). 
I have not detached the project.
I am not using release channels or any other advanced publishing options.
I began project development with sdk 25.0.0 and am still using it.

**Comment by terribleben** [comment]
Thanks, very helpful! Seems like a bug, though it's not [obvious from a quick glance](https://github.com/expo/universe/blob/master/dev/xdl/src/detach/IosNSBundle.js#L240-L243) how this could have broken. I think many people use this feature. I'll try to reproduce sometime this week.

**Comment by steve-prod** [comment]
Awesome! Thanks!

**Comment by steve-prod** [comment]
Created a minimal proof-of-bug from Expo's audio-recording-example repo [here](https://github.com/steve-prod/audio-recording-example).  

I created an app with create-react-native-app and added the contents from [audio-recording-example](https://github.com/expo/audio-recording-example).
  
The only change I made was to add an [ios.infoPlist entry](https://github.com/steve-prod/audio-recording-example/blob/master/app.json#L21-L23) for NSMicrophoneUsageDescription in the app.json file.

Same behavior is exhibited where default permissions request text appears, rather than text in infoPlist entry in app.json.

Could it be a problem with create-react-native-app?

**Comment by steve-prod** [comment]
Does the project need to be detached?  I've been following the directions for [Building Stand Alone Apps](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html).  It doesn't mention anything about detaching the project.  I'm not using any custom native modules.

I traced the stack of the code you [linked to above](https://github.com/expo/xdl/blob/master/src/detach/IosNSBundle.js#L240-L243).  Eventually it brought me back to the README.md, specifically the section on building Standalone Apps for [iOS](https://github.com/expo/expo#ios-1).  At the beginning of the [Standalone Apps](https://github.com/expo/expo#standalone-apps) section, it says

> If you don't need custom native code outside of the Expo SDK, head over to our documentation on building standalone apps without needing Android Studio and Xcode.

Does adding an ios.infoPlist entry to app.json count as needing custom code outside of the Expo SDK?  I don't believe the instructions in the [iOS](https://github.com/expo/expo#ios-1) section are in [Building Stand Alone Apps](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html), but seem necessary if you want to customize any permissions request.

This may just be a documentation issue.  Or I may just be thick.  Please advise.

**Comment by terribleben** [comment]
You're doing it right, you don't need to be detached to use this feature. In fact it won't work if you detach (since you would just have raw access to the Info.plist file itself).

**Comment by steve-prod** [comment]
I couldn't get it to work, so I just changed strings in the source code instead (an inelegant solution, but it got the job done).

I think there may be one or more steps missing from the documentation.

As I see it, here's the stack for overwriting permissions strings:
[IosNSBundle._configureInfoPlistAsync()](https://github.com/expo/xdl/blob/master/src/detach/IosNSBundle.js#L240-L243)
[IosNSBundle.configureAsync()](https://github.com/expo/xdl/blob/master/src/detach/IosNSBundle.js#L436)
[IosShellApp._configureAndCopyShellAppArchiveAsync()](https://github.com/expo/xdl/blob/master/src/detach/IosShellApp.js#L191) and/or [Detach.detachIOSAsync()](https://github.com/expo/xdl/blob/master/src/detach/Detach.js#L262)
[IosShellApp.createIOSShellAppAsync](https://github.com/expo/xdl/blob/master/src/detach/IosShellApp.js#L272)
[createIOSShellAppWithArguments()](https://github.com/expo/expo/blob/master/tools-public/gulpfile.js#L102)
[gulp task ios-shell-app](https://github.com/expo/expo/blob/master/tools-public/gulpfile.js#L130)

So... it seems like if you don't detach a project, the only way you can ever change a permissions string is to run the ios-shell-app gulp task with an info.plist file.  Or am I missing something?

It looks like the initial permission request string values get read from the source code in [generate-dynamic-macros.generateIOSBuildConstantsFromMacrosAsync()](https://github.com/expo/expo/blob/master/tools-public/generate-dynamic-macros.js#L217).

**Comment by terribleben** [comment]
> the only way you can ever change a permissions string is to run the ios-shell-app gulp task with an info.plist file.

This is what our build server does when you run `exp build:ios`. I'm still planning on taking a look at your issue this week.

**Comment by steve-prod** [comment]
Ohhhhhh, that's embarrassing.  I thought it would just show up when you ran it in the client.  This probably isn't even a valid issue then.  I'll go ahead and close this issue and resubmit my app.  Will reopen issue if permissions don't change.  Sorry for the inconvenience.

**Comment by terribleben** [comment]
No worries! Maybe I can make this more clear in the documentation. Thanks for the feedback.

**Comment by steve-prod** [comment]
My app was approved about 30 minutes ago, so the permissions updating clearly works.  A note in the documentation about this behavior (updated permissions request text not showing up on the client but actually being in the build) would probably be useful for new Expo developers like myself.

**Comment by knawaz771** [comment]
Hello @terribleben, Hope you are doing great. I've recently started using expo and find it's really great tool. I'm also following your comments/replies on different topics and they were a great help. I have just encountered an issue and really couldnt my head around and then landed on this thread which exactly as mine. I'm using following settings in my app.json to support portrait and upsidedown orientation

"infoPlist": {
          "UISupportedInterfaceOrientations": [
              "UIInterfaceOrientationPortrait",
              "UIInterfaceOrientationPortraitUpsideDown"
          ]
      },

above settings don't reflect on TestFlight build. Is there anyway you could help what's causing these settings not to reflect in TestFlight Build ?
