### ISSUE TITLE
Error: Permissions module is null. Are you sure all the installed Expo modules are properly linked?

### ISSUE THREAD

**Issue by jadonhansen** [expo/expo#14445]
### Summary

A recent bug that arose was one involving expo location to not fetch a users location on Android anymore due to Google Plays API changes. The fix was given here [issues/14248](https://github.com/expo/expo/issues/14248#issuecomment-917460378) - to upgrade expo location to version `12.1.3`.
I installed the latest version, verified that it was building with that version but then got this error while attempting to get a users location: `[Error: Permissions module is null. Are you sure all the installed Expo modules are properly linked?]`. So I installed the expo permissions module, rebuilt, but got the same error.
I have read elsewhere that this could be a unimodules issue but am unsure because upgrading to the latest unimodules version gives me a different error.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      npm: 7.21.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Unfortunately I am not able to create a demo for this as my project is huge.
But you can try an expo project with these package versions:
`"expo-location": "^12.1.3",
"react-native-unimodules": "~0.13.3",
"expo-permissions": "~12.0.1"`
and the above expo environment to reproduce.

Simple code implementation:
```
try {
    const { status } = await Location.requestForegroundPermissionsAsync();

    if (status !== "granted") console.log('no permissions);
    else {
        const locat = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Highest });
    }
} catch (error) {
    console.error(error);
}
```

**Comment by tempranova** [comment]
Did you find out what the problem was here? I also upgraded to 12.1.3 but receiving the same error as before, like this description.
