### ISSUE TITLE
Camera: Expose or pay attention to `videoMaxZoomFactor` on iOS

### ISSUE THREAD

**Issue by yehudahkay** [expo/expo#1444]
Thanks for the great framework!

I tried the example of the camera https://expo.io/@community/camerja

On nexus 5x the zoom buttons work but don't affect the picture taken (it is taken without zoom)

On ipad ios 9.3.5 the buttons don't do anything

**Comment by yehudahkay** [comment]
Its a 3rd generation ipad. Perhaps it is related to videoMaxZoomFactor?

I can confirm that the camera launched using launchCameraAsync has zoom on both devices, but the problem is that on Android the image is retained on the device. There seems to be an open issue for that.

**Comment by yehudahkay** [comment]
Just to add another comment, it is definitely related to videoMaxZoomFactor. Also on ipad air only some zoom is supported but not maximum, so a slider with 0 - 1 doesn't work properly for the ipad air. So there should be a way to get the videoMaxZoomFactor or have the zoom take this into account.

The main problem is android though, where the zoom doesn't affect the picture taken. We can't release our app on android because of this.

**Comment by yehudahkay** [comment]
Hi @terribleben, does this still need more info? Also the issue isn't only on my ipad, it seems all ios devices are affected. It is not taking into account videoMaxZoomFactor which differs on device, although the documentation seems to be saying it should.

**Comment by terribleben** [comment]
Thanks for the reminder, I think this is something we should fix in the SDK.

**Comment by aalices** [comment]
Well, we do use these value: https://github.com/expo/universe/blob/master/exponent/ios/Exponent/Versioned/Core/Api/Components/Camera/EXCamera.m#L250
What iPhones did you test?

**Comment by yehudahkay** [comment]
We've tested on a few iPhones and a few iPads. Seems that the newer the device the better the zoom. The older the device the zoom maxes out at a lower number say .3 or so, a little newer device .5, a little newer .7 etc we are using a slider for Zoom which probably made this more apparent.

**Comment by yehudahkay** [comment]
Hi, i've tested now on iphone 5s and ipad 2018 and the issue is present as well. These are the newest ios devices i have at the moment.

**Comment by yehudahkay** [comment]
I can confirm that the bug exists as well on iphone 6 however on iphone x the zoom works properly between 0 and 1

**Comment by aalices** [comment]
@yehudahkay can you create a comparison gifs that show behavior on a device that works fine and one where zoom looks wrong? We might rethink the `zoom` prop and give the users more control over it.

**Comment by yehudahkay** [comment]
Ok, thanks for looking into this! I recorded a video on the nexus 5x (the iphone x would look similar but I don't own one) and on the 2018 ipad (the iphone 6 displays similar behavior but I don't own one). 

![ezgif com-resize 1](https://user-images.githubusercontent.com/9964988/41969053-e9d98ec2-7a0e-11e8-8870-cc7d051f6db0.gif)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9964988/41968967-a4f11fd2-7a0e-11e8-8121-85875791ba40.gif)

**Comment by aalices** [comment]
I think, iPad works fine but the preview is so zoomed that any further zooming in is barely visible. You might want to lower the slider step and maybe decrease the maximum value to something less than 1. Check out this feature request: https://expo.canny.io/feature-requests/p/setting-camera-zoom-to-specific-value and upvote if you find it more intuitive :)

**Comment by yehudahkay** [comment]
Hi, no the ipad doesn't zoom after approx .5. Also how would I know which devices can zoom and which can't?

**Comment by yehudahkay** [comment]
I also spent a long time trying to help understand the issue here. The default camera on the ipad doesn't behave this way (it seems that it stops trying to zoom at .5 :-), so it's hard for me to understand why this wouldn't be considered a bug.

**Comment by aalices** [comment]
As you noticed it is very device-specific. We just select a value between 1.0 and a max zoom value that a device provides. Anyway I'll try to do some native debugging if I manage to get an iPad

**Comment by yehudahkay** [comment]
Thanks!!!! Again I saw this on iphone 6 and 5s as well. I don't know about 6s.
