### ISSUE TITLE
[expo-sensor] Accelerometer listener invoke remove function throw `Cannot read properties of undefined (reading 'removeSubscription')` error in React Native 0.65

### ISSUE THREAD

**Issue by shinken008** [expo/expo#14449]
### Summary

With debugger, i find React Native 0.65 NativeEventEmitter remove removeSubscription event，so throw error.

How to used:
```js
import { Accelerometer } from 'expo-sensors'

const listener = Accelerometer.addListener(() => {})

listener.remove() // throw error
```

I noticed that this problem is fixed in the master branch, https://github.com/expo/expo/blob/6763ed73b996917a87d85396297620476f29219d/packages/expo-modules-core/src/EventEmitter.ts#L72, but the master branch has differences from the SDK branch, so please fix it in the SDK branch，thanx.

I currently use the alpha version(`@unimodules/core@7.2.0-alpha.0` and `@unimodules/react-native-adapter@6.5.0-alpha.0`) to replace `@unimodules/core@7.1.2` and `@unimodules/react-native-adapter@6.3.7`, there may be hidden problems.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

@unimodules/core@7.1.2
@unimodules/react-native-adapter@6.3.7
"expo-sensors": "^10.2.2"
"react-native-unimodules": "^0.14.8"
react-native@0.65.1

nodejs@14.16.0

### Reproducible demo or steps to reproduce from a blank project

```js
import { Accelerometer } from 'expo-sensors'

const listener = Accelerometer.addListener(() => {})

listener.remove() // throw error
```

**Comment by shinken008** [comment]
https://github.com/expo/expo/blob/c69fda4c66f7c21bb50acd6d26234a5b5ae12c19/packages/%40unimodules/react-native-adapter/src/EventEmitter.ts#L72

**Comment by bbarthec** [comment]
Hello shinken008 👋 
Thank you for reporting this issue. Apparently there's some change in `RN@0.65` affecting EventEmitter. [`react-native-unimodules@0.14.9`](https://www.npmjs.com/package/react-native-unimodules/v/0.14.9) and thus [`@unimodules/react-native-adapter@6.3.8`](https://www.npmjs.com/package/@unimodules/react-native-adapter/v/6.3.8) now contain the respective fix for this regression 🔧 
I'm tentatively closing this issue, but if the problem persists for some reason please be welcome to reopen 😊
