### ISSUE TITLE
[expo-local-authentication] BiometricPrompt - callback does not use protected KeyStore data to authenticate the user when valid biometrics

### ISSUE THREAD

**Issue by derrickatb** [expo/expo#14456]
### Summary

We recently had our security team do an audit of our application. They found a security vulnerability within the 'expo-local-authentication' package.

The expo-local-authentication package supports biometric authentication and relies on the “BiometricPrompt” class (which manages authentication mechanisms) and an application dialogue box that asks the user to authenticate. The application uses a callback from this class to determine whether a biometric authentication attempt was successful. However, the success handler of the callback does not use protected KeyStore data to authenticate the user when valid biometrics are supplied. Therefore, it is possible to tamper with the authentication flow and bypass biometric authentication.

Their recommendation is:

Implement fingerprint authentication securely by creating an Android KeyStore key, and initialize a cipher object with this key. The key must have the setUserAuthenticationRequired and setInvalidatedByBiometricEnrollment flags set to true. Additionally, the key must have the setUserAuthenticationValidityDurationSeconds flag set to -1. Create a BiometricPrompt.CryptoObject object using this cipher object. Implement the ”BiometricPrompt.AuthenticationCallback.onAuthenticationSucceeded” callback, which will retrieve a cipher object from the parameter. Use this cipher object to decrypt other crucial data (i.e. the session key or a secondary symmetric key), which can then be used to decrypt application data. For more information, please refer to https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05f-Testing-Local-Authentication.md

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.9.1 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.21.1 - /usr/local/bin/npm
      Watchman: 2021.09.06.00 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 31.0.0
        System Images: android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1
      react-dom: ^16.13.1 => 16.14.0
      react-native: ^0.64.2 => 0.64.2
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

This method where the security vulnerability is present:
```
private final BiometricPrompt.AuthenticationCallback mAuthenticationCallback = 
new BiometricPrompt.AuthenticationCallback () {
            @Override
            public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult result) {
              mIsAuthenticating = false;
              mBiometricPrompt = null;
              Bundle successResult = new Bundle();
              successResult.putBoolean("success", true);
              safeResolve(successResult);
            }
```

**Comment by derrickatb** [comment]
@cruzach Just following up, let me know if there's anything else you need from me.
It looks like people can use software like [Frida](https://frida.re/docs/frida-cli/) to call the onAuthenticationSucceeded method to bypass the entire biometric auth process if they have access to someone's physical device.

**Comment by byCedric** [comment]
Hi @derrickatb! Sorry for the delay. So, I want to fully understand what possible attack vectors derive from our current implementation. If I understand correctly, the current attack vectors are:
- If the phone is stolen and connected to a computer, they would be able to bypass the local auth prompt.
- If the device is infected with a malicious application (with root access), they would be able to bypass the prompt.

In both these cases, I'm not sure if getting past a local auth prompt is the most severe threat here. If the phone is captured, they might be able to bypass most security measures by hardware tweaks. And if the device is infected with malware, they might as well install keyloggers.

Can you describe, in broad terms, how the attack vector applies to your implementation within the app? Maybe that helps us understand the severity of the attack vector a bit better.

> Also as a side note, I found [this security research blogpost](
https://blog.nviso.eu/2021/04/06/a-closer-look-at-the-security-of-react-native-biometric-libraries/) describing the issue you flagged as well. Posting it here so we won't lose it.

**Comment by derrickatb** [comment]
> In both these cases, I'm not sure if getting past a local auth prompt is the most severe threat here. If the phone is captured, they might be able to bypass most security measures by hardware tweaks. And if the device is infected with malware, they might as well install keyloggers.

Yes, that is a really good point. 

> Can you describe, without going into specifics, how the attack vector applies to your implementation within the app? Maybe that helps us understand the severity of the attack vector a bit better.

We implement the package as is suggested in the docs. Believe your points above outline the same attack vectors our security team identified. I actually found another [package](https://github.com/SelfLender/react-native-biometrics) which can provide a more secure way of authenticating with Biometrics, but does require a backend which defeats the purpose of a local authentication based system.

Not sure if it would be beneficial or not for expo to offer a version that implements something similar or not, given there are other solutions out there.

**Comment by jakubboguski** [comment]
Hi @derrickatb! Can you share what path you took to solve this problem?

We are struggling with the same concerns and looking for suggestions. To other readers, there is the article describing characteristics in detail: https://blog.nviso.eu/2021/04/06/a-closer-look-at-the-security-of-react-native-biometric-libraries/

**Comment by kokenjr** [comment]
> Hi [@derrickatb](https://github.com/derrickatb)! Can you share what path you took to solve this problem?
> 
> We are struggling with the same concerns and looking for suggestions. To other readers, there is the article describing characteristics in detail: https://blog.nviso.eu/2021/04/06/a-closer-look-at-the-security-of-react-native-biometric-libraries/

@jakubboguski Did you ever find a solution to this?

**Comment by tamlyn** [comment]
The Expo [SecureStore](https://docs.expo.dev/versions/latest/sdk/securestore/) package now supports protecting encrypted values with biometrics. As I understand it, this cannot be circumvented with a tool like Frida because the system will only decrypt the payload after a successful biometric check.
