### ISSUE TITLE
expo-facebook not picking up facebook app id from app.json

### ISSUE THREAD

**Issue by kolosy** [expo/expo#14453]
### Summary

We're using the `expo-facebook` module for FB auth. For some reason, when upgrading from SDK40 to SDK42, our FB integration stopped working. I traced it to FB not seeing the app id, even though it is provided.

app.json:
```
    "facebookScheme": "fb[app id]",
    "facebookAppId": "[app id]",
    "facebookDisplayName": "app name",
```

Info.plist (I pulled this out of the simulator build's ipa file)
```
	<key>FacebookAppID</key>
	<string>[our app id]</string>
	<key>FacebookAutoInitEnabled</key>
	<false/>
	<key>FacebookAutoLogAppEventsEnabled</key>
	<false/>
	<key>FacebookDisplayName</key>
	<string>[app name]</string>
```

I got the functionality back by hard coding the app id in to the call to `Facebook.initializeAsync`. The documentation states that these are either-or (passing it as a param or setting it in app.json). Are we doing something wrong or is there a bug here?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.1.0 - ~/.asdf/installs/nodejs/15.1.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.8 - ~/.asdf/installs/nodejs/15.1.0/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /Users/kolosy/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Just the fb sample without a supplied appId to the initialization call should suffice. App.json with a defined `facebookAppId` is needed as well.

```
async function logIn() {
  try {
    await Facebook.initializeAsync();
    const {
      type,
      token,
      expirationDate,
      permissions,
      declinedPermissions,
    } = await Facebook.logInWithReadPermissionsAsync({
      permissions: ['public_profile'],
    });
    if (type === 'success') {
      // Get the user's name using Facebook's Graph API
      const response = await fetch(`https://graph.facebook.com/me?access_token=${token}`);
      Alert.alert('Logged in!', `Hi ${(await response.json()).name}!`);
    } else {
      // type === 'cancel'
    }
  } catch ({ message }) {
    alert(`Facebook Login Error: ${message}`);
  }
}
```

**Comment by EmersonGarrido** [comment]
in try add 
`await Facebook.initializeAsync({
      appId: "FACEBOOK APP ID",
      appName: 'FACEBOOK APP NAME',
      version: 'v9.0',
      domain: 'WEB SITE'
    });`
    
  example :
  `import * as Facebook from "expo-facebook";

export async function signIn() {
  try {
   await Facebook.initializeAsync({
      appId: "FACEBOOK APP ID",
      appName: 'FACEBOOK APP NAME',
      version: 'v9.0',
      domain: 'WEB SITE'
    });`

    const {
      type,
      token } =
      await Facebook.logInWithReadPermissionsAsync({
        permissions: ['public_profile', 'email', 'instagram_basic', 'pages_show_list'],
      });

    console.log(type);
    if (type === "success") {
      return token;
    } else {
      type === "cancel";
    }
  } catch ({ message }) {
    alert(`Facebook Login Error: ${message}`);
  }

}
`

**Comment by kolosy** [comment]
Yes, that works but that's exactly my point -- the docs state that you _either_ need to set the configs in app.json, _or_ pass them as params to the initialization call. I don't want those config parameters hard-coded in the app, but am having to because the `app.json` values are being ignored for some reason.

**Comment by EmersonGarrido** [comment]
On my android as well as on iphone the settings in app.json work

However, the IOS emulator is logging in with EXPO and not with my appId, on android it works perfectly.

**Comment by kolosy** [comment]
that's documented functionality -- if you use Expo Go on iOS, it'll use Expo's fb app id. That's a separate conversation.

**Comment by adamjuhasz** [comment]
We have similar behavior in #14498, however in Android but iOS for us was fine

**Comment by BrodaNoel** [comment]
I provided some info about this bug in https://github.com/expo/expo/issues/13842

**Comment by BrodaNoel** [comment]
No so fast my friend. This buy still a thing.

**Comment by BrodaNoel** [comment]
Hey @github-actions, seems like we'll have this conversation during year.
Still there. Sadly.

**Comment by BrodaNoel** [comment]
Bad boy.
The bug still there… Only fixable with plugins.

Be careful people.

Broda Noel

**Comment by Nezran** [comment]
Hi ! 

Thanks to make the issue still open, i have trouble with the facebook login too, on Android only. @BrodaNoel How did you make it work ?

Have a nice day
