### ISSUE TITLE
Video should play with sound if user presses play, even if phone ringer is off

### ISSUE THREAD

**Issue by wfried** [expo/expo#1445]
### Environment

In iOS target

[4mEnvironment:[0m
  OS: macOS Sierra 10.12.6
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

[4mPackages:[0m (wanted => installed)
  expo: ^24.0.0 => 24.0.2
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0

### Steps to Reproduce

1. Turn off your iPhone ringer with the hardware switch.
2. Play a streaming video embedded into an Expo app

### Expected Behavior

Like other video players on iPhone, including video played with the native Photos app or YouTube, the sound should play along with the video. The phone ringer switch should have nothing to do with this.

### Actual Behavior

The video plays silently.

### Reproducible Demo

This is the default behavior of the video control. The issue is really a design choice, and Expo should be consistent with other apps in this regard.

**Comment by terribleben** [comment]
Are you passing the [playsInSilentModeIOS](https://docs.expo.io/versions/latest/sdk/audio.html#playsinsilentmodeios--a-boolean-selecting-if-your-experiences-audio-should-play-in-silent-mode-on-ios-this-value-defaults-to-false) flag to `setAudioModeAsync`?

**Comment by wfried** [comment]
Thanks. That makes a difference for other sounds, like an MP3 file, but not for streaming video.

**Comment by terribleben** [comment]
Hmm, @sjchmiela maybe we should ensure that the flag works for these as well

**Comment by wfried** [comment]
One more note: on an Android 8.0.0. device, the default behavior worked as expected. We are only seeing this issue on iOS. Thanks for looking at this.

**Comment by wfried** [comment]
Thanks for looking at that. Seems like the default behavior should also match the native players, like the iPhone Photos app, and industry leaders, like YouTube. Would you consider that too?

**Comment by sjchmiela** [comment]
It seems this flag works properly for videos too, @terribleben (just checked).

Are you suggesting, @wfried, to make videos play sound even when this flag is off or are you suggesting to make the videos play sound by default without needing to explicitly [`setAudioModeAsync`](https://docs.expo.io/versions/latest/sdk/audio.html#expoaudiosetaudiomodeasyncmode)?

At the moment the default behavior is not to play any sounds when the _Ring/Silent switch_ is set to _silent_ and programmers are invited to customize the behavior however they need. 🙂

To mimic the default behavior of Apple applications and industry leaders you'd need to call

```js
Audio.setAudioModeAsync({
  ...
  playsInSilentModeIOS: true,
});
```

when opening your application.

**Comment by wfried** [comment]
Thanks @sjchmiela. Yes, I was suggesting that the default behavior of Expo should match the default behavior of the native applications.

But in the meantime, the below is what we have tried and it doesn't seem to change the behavior. Do you have any suggestions?  Thanks!

```
await Audio.setAudioModeAsync({                                                                                                
    playsInSilentModeIOS: true,                                                                                                           
    allowsRecordingIOS: false,                                                                                                                                                                                   
    interruptionModeIOS: Audio. INTERRUPTION_MODE_IOS_DUCK_OTHERS,                                                                         
ؚ    shouldDuckAndroid: true,                                                                                                           
    interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS,                                                                 
});
```

And the code where we embed the video:
```
    <Video
            source={{uri: this.page.videoUrl}}
            rate={1.0}
            volume={1.0}
            isMuted={false}
            useNativeControls={true}
            resizeMode="contain"
            style={{
              backgroundColor: GRAY_BLUE,
              width: CONTENT_WIDTH,
              height: CONTENT_WIDTH / VIDEO_RATIO,
              marginTop: 20 + 0.5 * EXTRA_PADDING,
              marginBottom: 20 + 2 * EXTRA_PADDING,
            }}
```

**Comment by sjchmiela** [comment]
Hm, that should work, could you provide me with a Snack so I can play around with it?

**Comment by sjchmiela** [comment]
Hello there, I'll close this issue due to inactivity, but feel free to reopen it if you encounter this bug anytime!

**Comment by cem2ran** [comment]
@sjchmiela Here's a minimal reproducible example on snack: https://snack.expo.io/@cem2ran/video-without-sound-when-playsinsilentmodeios-is-true

As mentioned previously, a quite hacky way of making this work is to play an audio file before playing video. This seems to make it work, but I would consider this a bug.

This issue appears to be related to this as well: https://github.com/expo/expo/issues/211
