### ISSUE TITLE
assetBundledPatterns not allowing offline access to assets on Android

### ISSUE THREAD

**Issue by trentcowden** [expo/expo#14469]
### Summary

Adding asset file paths to `assetBundledPatterns` in `app.json` is not allowing them to be accessed offline on Android. Upon opening a standalone apk for the first time, the app is unable to display an asset that has been included in `assetBundledPatterns`. The image loads offline just fine on an iOS simulator build.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.0

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      npm: 7.20.1 - ~/.nvm/versions/node/v14.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Reproducible demo can be found on [this repo](https://github.com/trentcowden/waha-offline-bug-repro). 

### For verifying that this works on iOS:
1. Clone the repo.
2. Build a standalone iOS simulator build using `expo build:ios -t simulator`. 
3. Extract the `.app` file from the downloaded `tar.gz` file and drag the `.app` file onto an iOS emulator.
4. Turn off WiFi.
5. Open the app.
6. You'll see a picture of the Seattle space needle load after a few seconds. The asset is available immediately offline.

### For verifying that this doesn't work on Android:
1. Build a standalone apk using `expo build:android -t apk`. 
2. Drag the apk onto an Android emulator or download it onto an Android phone. 
3. Turn on airplane mode on the emulator/phone.
4. Open the app.
5. You will NOT see a picture of the Seattle space needle no matter how long you wait. The app will be stuck. The asset is unavailable offline.

If you monitor the network traffic while opening the apk WITH internet, you'll notice that it's making a request to CloudFront to get the image asset. See video (ignore other network traffic that is happening on my computer. The important one is the `.cloudfront.net` one):

https://user-images.githubusercontent.com/37824478/133942153-bb4afddd-e7e5-4f6e-bba8-bf40f9cf8c51.mov

I used the [Charles web proxy](https://www.charlesproxy.com) and [this guide](https://mdapp.medium.com/the-android-emulator-and-charles-proxy-a-love-story-595c23484e02) to view the network traffic. According to the [Expo offline support docs](https://docs.expo.dev/guides/offline-support/), using `assetBundledPatterns`,
> Expo can bundle assets into your standalone binary during the build process so that they will be available immediately, even if the user has never run your app before. This is important if: - **Your users may not have internet the first time they open your app**.

**Comment by jkhales** [comment]
Thanks, taking a look.

**Comment by byCedric** [comment]
Hi @trentcowden! Thanks for writing up a good issue report, with an example repository, videos, and steps to reproduce. We've just deployed a fix to Turtle, so you should be able to create a new build without this issue. The issue itself was related to how we resolve the local assets using hashes.

If it's not working for you, feel free to ping me directly on [Twitter](https://twitter.com/cedricvanputten) or Discord (@cedric)!

**Comment by trentcowden** [comment]
Just tested and can confirm it's working now! Thank you @byCedric!
