### ISSUE TITLE
Known high severity security vulnerability in expo/xdl

### ISSUE THREAD

**Issue by steve-prod** [expo/expo#1446]
I've received the following message from Github for the past couple repos I've checked in:

<img width="512" alt="screen shot 2018-02-18 at 6 52 16 pm" src="https://user-images.githubusercontent.com/24657085/36361136-76015cb8-14de-11e8-8b16-fd84dfdbc7de.png">

expo/xdl's package.json calls for "auth0-js": "^7.4.0" which seems to correspond to 7.6.1.
Should this be updated?

**Comment by jimmylee** [comment]
Hey @steve-prod we are working on this now. I'm going to assign this to @fson to close once he lands the PR.

**Comment by fson** [comment]
If you are worried about the message from GitHub, note that XDL is not affected by this vulnerability because it doesn’t use the vulnerable API (auth0.popup.callback()).

However, to stop people getting false alarms about the library version, we’re updating the dependency in the next release.

**Comment by fson** [comment]
Closing this as xdl has been using v9.3.3 of the package for a while now.
