### ISSUE TITLE
Constants.manifest is null because the embedded app.config could not be read

### ISSUE THREAD

**Issue by darrylyoung** [expo/expo#14475]
### Summary

When running my app — a bare workflow project — I now notice the following warnings in my console.

After running `npx pod-install`:

```
Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-constants
```

After running the app:

```
 WARN  Constants.manifest is null because the embedded app.config could not be read. Ensure that you have installed the expo-constants build scripts if you need to read from Constants.manifest.
```

Note that `expo-constants` was updated from `~11.0.1` to `^11.0.2` a couple of weeks ago while also updating to React Native `0.65.1`. It looks like the same issue mentioned in #11888 but that was resolved a while ago so I'm not sure what's happening with my project at the moment.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.11.0 environment info:
  System:
    OS: macOS 11.6
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.n/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  npmPackages:
    expo: ^42.0.3 => 42.0.3
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-native: ^0.65.1 => 0.65.1
  npmGlobalPackages:
    expo-cli: 4.11.0
  Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

I'm unable to share code from my project but if this helps, here's some further context. I'm using these Expo-related packages, I'm in the bare workflow, and I'm testing on an iOS 14.5 Simulator. I know for sure that before updating to React Native `0.65.1` (at the same time I updated the `expo-constants` package) I wasn't seeing these warnings.

```
"react": "^17.0.2",
"react-native": "^0.65.1",
"expo": "^42.0.3",
"expo-app-loading": "^1.1.2",
"expo-apple-authentication": "~3.2.1",
"expo-application": "~3.2.0",
"expo-asset": "^8.3.3",
"expo-auth-session": "~3.3.1",
"expo-constants": "^11.0.2",
"expo-device": "~3.3.0",
"react-native-unimodules": "^0.14.8",
```

If there's anything else I can provide to help, please let me know. As always, thank you all so much for the work you've put into Expo and for any support here.

**Comment by runata** [comment]
Having exact same issue here.

**Comment by prscX** [comment]
Hi: Encountered similar issue. Could anyone please help us in order to fix the issue. Please find below my package.json dependencies:

```
{
    "expo-crypto": "9.2.0",
    "expo-document-picker": "9.2.4",
    "expo-file-system": "11.1.3",
    "expo-localization": "10.2.0",
    "expo-local-authentication": "11.1.1",
    "expo-mail-composer": "10.2.2",
    "expo-permissions": "12.1.1",
    "expo-speech": "9.2.1",
    "react-native-unimodules": "0.14.8",
    "react-native": "0.66.0",
}
```

Thanks
</ Pranav >

**Comment by TPXP** [comment]
Same issue here, it seems that the simple fact of importing `expo-constants` (as done in `expo-av` for example) causes the bundler to evaluate every property of the exported object (at least in dev?). I'm also getting other warnings from the same file.

```
Constants.installationId has been deprecated in favor of generating and storing your own ID. Implement it using expo-application's androidId on Android and a storage API such as expo-secure-store on iOS and localStorage on the web. This API will be removed in SDK 44.
Constants.deviceId has been deprecated in favor of generating and storing your own ID. This API will be removed in SDK 44.
Constants.linkingUrl has been renamed to Constants.linkingUri. Consider using the Linking API directly. Constants.linkingUrl will be removed in SDK 44.
Constants.manifest is null because the embedded app.config could not be read. Ensure that you have installed the expo-constants build scripts if you need to read from Constants.manifest.
```

Exporting `getManifest` directly from `expo-constants` (and making sure other modules call this function directly) may fix the issue.

**Comment by SamRichards** [comment]
Exact same here. Thanks for raising.

**Comment by brentvatne** [comment]
would someone be able to share a minimum reproducible example? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by gwalshington** [comment]
Similar issue reported here: 

https://github.com/expo/expo/issues/8231

**Comment by TPXP** [comment]
Hello,

I tried to reproduce it with the latest Expo Framework without using unimodules and the warning was not raised. So I'm guessing it's related to unimodules.

**Comment by anirudh-eka** [comment]
We have the same issue as well

**Comment by avik-efcom** [comment]
on 1.5.22 everything worked fine, today I got this error:
`Constants.manifest is null because the embedded app.config could not be read. Ensure that you have installed the expo-constants build scripts if you need to read from Constants.manifest.`
and the splash screen stack.. after 5 minute or less I got more error
![image](https://user-images.githubusercontent.com/72505851/166206347-5356236d-b646-496a-b0af-0d46020de240.png)

I don't re-install the npm or something just load the app.
(I try to reinstall the npm on a duplicate folder and I got some errors)
