### ISSUE TITLE
Upgrading from sdk 24 to sdk 25 breaks react-native-maps-clustering

### ISSUE THREAD

**Issue by dylancompanjen** [expo/expo#1448]
After following the steps to upgrade from SDK 24 to SDK 25 I get the following bug:
Unable to resolve module 'react-native-maps' from 'Users/my-username/project/node_modules/react-native-maps-clustering/MapView/MapWithClustering.js': Module does not exist in the module map.

If I switch back to SDK 24, uninstall / reinstall node_modules the bug disappears.

Is this related to react-native-maps being updated in the latest SDK?

**Comment by quinlanj** [comment]
hi @dylancompanjen -- if you run `rm -rf node_modules` and install the packages again, does it still give you the same error?
