### ISSUE TITLE
Enable staysActiveInBackground for Video on iOS (please reopen issue #12932)

### ISSUE THREAD

**Issue by leocaseiro** [expo/expo#14486]
I would like to request to reopen the issue https://github.com/expo/expo/issues/12932 which would get more attention, as the latest PR tried to fix the issue, but it didn't fix it.

In the docs, we mentioned that `staysActiveInBackground` should keep the audio playing while the video is in the background, however, the video is pausing on iOS, and so is the audio.

**Comment by leocaseiro** [comment]
I would like to request to reopen the issue https://github.com/expo/expo/issues/12932 which would get more attention, as the latest PR tried to fix the issue, but it didn't fix it.

Many thanks,

**Comment by byCedric** [comment]
Hi @leocaseiro, thanks for writing in. Could provide an example repo where this happens, and post it in the thread of #12932? That would help us a lot, and we should be able to debug more about what's going on. For now, let's continue the conversation in that issue.
