### ISSUE TITLE
[docs] EAS expo.dev/register-device page: Warn if not using Safari

### ISSUE THREAD

**Issue by markstreich** [expo/expo#14487]
### Summary

The page for registering iOS devices (`https://expo.dev/register-device/{uuid}`) (which is generated by running `eas device:create` as documented [here](https://docs.expo.dev/build/internal-distribution/)) could warn if opened from a browser other than Safari. 

On that page, it asks you to tap "Download" then tap "Allow", but the "Allow" option only comes up in Safari (or at least it did not work when I tested in Chrome), so ends up being a confusing experience.

[screenshot of page](https://user-images.githubusercontent.com/1214573/134128051-6aff5416-b028-4c7a-855b-ffb86dcba1f4.png)

**Comment by brentvatne** [comment]
it looks like this is supported in the latest chrome:

![Group 1 (11)](https://user-images.githubusercontent.com/90494/150240374-9522b954-e333-47a1-9556-152302ad9cc1.png)
