### ISSUE TITLE
multiple methods named 'orientation' found with mismatched result

### ISSUE THREAD

**Issue by jjrdevspace01** [expo/expo#14488]
### Summary

including both expo-screen-orientation and expo-file-system results build error on expo run ios. Removing either package resolves the problem

```
❌  (node_modules/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationRegistry.m:141:121)

  139 | - (void)handleDeviceOrientationChange:(NSNotification *)notification
  140 | {
> 141 |   UIInterfaceOrientation newScreenOrientation = [EXScreenOrientationUtilities interfaceOrientationFromDeviceOrientation:[notification.object orientation]];
      |                                                                                                                         ^ multiple methods named 'orientation' found with mismatched result, parameter type or attributes
  142 |   [self interfaceOrientationDidChange:newScreenOrientation];
  143 | }
  144 |

```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4.4.4 => 4.4.4
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

expo install expo-screen-orientation
expo install expo-file-system
expo run ios

**Comment by byCedric** [comment]
Hi @jjrdevspace01, thanks for the issue report. Unfortunately, I can't reproduce this issue. Can you provide a repository where this issue happens for you?

**Comment by raspasov** [comment]
Having the same issue. Happened after upgrading to the latest Xcode 13.0 (just released).

Adding the type explicitly seems to fix it, do you think this is correct? 

```objc
- (void)handleDeviceOrientationChange:(NSNotification *)notification
{
  UIDevice *device = notification.object;
  UIInterfaceOrientation newScreenOrientation = [EXScreenOrientationUtilities interfaceOrientationFromDeviceOrientation:[device orientation]];
  [self interfaceOrientationDidChange:newScreenOrientation];
}
```

**Comment by Sewb21** [comment]
I also had this issue, using `npm install expo-screen-orientation@next` seemed to sort it for me see https://github.com/expo/expo/pull/13898#issuecomment-916395222
