### ISSUE TITLE
expo / react-native : eject a simple project -> error "cannot read property 'ressources' of null"

### ISSUE THREAD

**Issue by devSeb** [expo/expo#14494]
### Summary

I create a new project and i would like to eject my project.
here my differents steps

-> expo init my-project
-> add lib 
-> commit + push in a branch master
-> create a new branch "mobile"
-> expo eject the project

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

"expo": "~42.0.1",

### Environment

my package.json 
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.8",
    "expo": "~42.0.1",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.8.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-unimodules": "~0.14.5",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.5",
    "redux": "^4.1.1",
    "redux-persist": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },

### Reproducible demo or steps to reproduce from a blank project

My reproduce steps

-> expo init my-project
-> add lib ( in my package.json)
-> commit + push in a branch master
-> create a new branch "mobile"
-> expo eject the project

Error

Cannot read property 'resources' of null
TypeError: Cannot read property 'resources' of null
    at removeColorItem (E:\DEV\projects\folder\project\node_modules\@expo\config-plugins\src\android\Colors.ts:39:16)
    at Object.assignColorValue (E:\DEV\projects\folder\project\node_modules\@expo\config-plugins\src\android\Colors.ts:72:10)
    at setSplashColorsForTheme (E:\DEV\projects\folder\project\node_modules\@expo\prebuild-config\src\plugins\unversioned\expo-splash-screen\withAndr
oidSplashStyles.ts:79:17)

thanks for help

**Comment by brentvatne** [comment]
what version of expo-cli were you using?

**Comment by devSeb** [comment]
My expo-cli version is 4.4.8

**Comment by brentvatne** [comment]
you should be using a more recent version of expo-cli, we recommend that you always stay up to date. please update to 4.11.0
