### ISSUE TITLE
Expo has Svg dependency v5.5.1 but Victory-Native charts library requires v6.1.0

### ISSUE THREAD

**Issue by ChenCodes** [expo/expo#1449]
### Steps to Reproduce
1. yarn add victory-native
2. Run an app containing basic victory-native code (sample code that I used from this issue: [](https://github.com/FormidableLabs/victory-native/issues/257))
3. Observe the UI of the graph that was generated.

### Expected Behavior
I expected that the y-axis label would not overlap the y-axis. 

### Actual Behavior
The y-axis label overlapped the y-axis. 
<img width="287" alt="screen shot 2018-02-19 at 12 14 26 pm" src="https://user-images.githubusercontent.com/7213887/36396475-45064ab6-1573-11e8-9c44-0532ae86f37b.png">

I think the solution for this is that Expo should probably upgrade it's Svg dependency to be the latest one so that victory-native charts won't have any UI issues.

Thanks in advance for the help!

**Comment by terribleben** [comment]
Hello! We'll be updating SVG in the next version of our SDK. See [here](https://github.com/expo/expo/issues/1422) and [here](https://github.com/expo/expo/issues/1393) for more info. I'll leave this issue open so others with the same question can find it.

**Comment by nbaghiro** [comment]
Are we able to use [https://github.com/FormidableLabs/victory-native#readme](url) with expo right now? 

It gives me react-native-svg not found error, so it still requires detaching I guess?
