### ISSUE TITLE
in China can not use the google servers

### ISSUE THREAD

**Issue by TuomaXu** [expo/expo#145]
In China most phones on android do not have google servers,
and have not access to https://play.google.com 
so can not install the expo client app
how can i work it?
thanks

**Comment by dikaiosune** [comment]
Unfortunately, it will be a little while before we can support Chinese users reliably. It would require duplicating many elements of our infrastructure and we're currently a very small team. It's definitely on our wishlist of things we'd like to do, but it probably won't be in the near future when we can support this.

**Comment by sonaye** [comment]
@dikaiosune I think a direct apk link is available somewhere, you don't have to download expo from the stores to be able to use it as far as i know. cc: @jesseruder

**Comment by jesseruder** [comment]
http://expo.io/--/api/v2/versions/download-android-apk

**Comment by TuomaXu** [comment]
@jesseruder thanks very much , I am a  ios developer 
now use ReactNative make the Apps that can cross two platforms
