### ISSUE TITLE
Can't use custom fonts with SVG (or react-native-art)

### ISSUE THREAD

**Issue by fhelwanger** [expo/expo#1450]
### Environment

Environment:
  OS: Windows 10
  Node: 8.6.0
  Yarn: 1.2.1
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/fhelwanger-4deb5b43-5b8f-4a73-a5ba-dc5910b65855.tar.gz

### Steps to Reproduce

1. Load some custom font:

```js
await Font.loadAsync({
  IndieFlower: require('./assets/fonts/IndieFlower.ttf')
});
```

2. Try to render some `ReactNative.ART.Text` using this font:

```js
<ART.Surface height={50} width={100}>
  <ART.Text
    font={{
      fontFamily: 'IndieFlower',
      fontSize: 14
    }}
    fill="#000"
  >
    {'<ART.Text/>'}
  </ART.Text>
</ART.Surface>
```

### Expected Behavior

The custom font is displayed.

### Actual Behavior

* On iOS, the app crashes with the `Unrecognized font family` error.
* On Android, no error is thrown but the default font is shown instead.
* If I use the default `ReactNative.Text`, the font is displayed correctly.

### Reproducible Demo

https://github.com/fhelwanger/ReactNativeArtExpoFontTest

1. Start the project:

```
git clone https://github.com/fhelwanger/ReactNativeArtExpoFontTest.git
yarn install
yarn start
```

2. Open the project on Expo Client.

**Comment by brentvatne** [comment]
you probably should not use it -- https://docs.expo.io/versions/latest/sdk/art.html

> you almost definitely want to use Svg instead of this unless you are really sure you want to use ART for some reason.

[Svg](https://docs.expo.io/versions/latest/sdk/svg.html)

**Comment by fhelwanger** [comment]
Thanks! Sorry about that.

I updated the example to use `Expo.Svg` instead.

https://github.com/fhelwanger/ReactNativeArtExpoFontTest/blob/0b985f1586f9323bfa4440a44750a43300b97290/App.js#L35-L39

Now, no error is thrown, but the default font is shown on both iOS and Android.

**Comment by fhelwanger** [comment]
I also tested it using `react-native` and `react-native-svg` without `create-react-native-app` and `expo`. This way, the custom font is displayed correctly.

**Comment by brentvatne** [comment]
see this guide: https://docs.expo.io/versions/latest/guides/using-custom-fonts.html

**Comment by iameli** [comment]
This appears to still be a problem.

**Comment by AdamJNavarro** [comment]
Hey @fhelwanger,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
