### ISSUE TITLE
Network error when sending PDF from Document Picker with FormData

### ISSUE THREAD

**Issue by ewein** [expo/expo#14513]
### Summary

I’m running into a Network error when I try to upload a PDF that was selected through Document Picker. The PDF is sent as Form Data with Axios. This issue only occurs on Android (SDK 42) and only with documents from Document Picker. Images are all working fine using ImagePicker as well. My code for this was working fine for months then after upgrading to SDK 42 it is now failing with no changes from my end. If I submit an image from ImagePicker it works correctly but if I select the same image through DocumentPicker it fails. I also noticed the uri returned from Document Picker on Android only does not include the leading “file://”, not sure if that causes any problems. I have tried appending the missing “file://” to the uri but that doesn’t seem to do anything.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      npm: 6.14.14 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

To select the PDF:

```
import * as DocumentPicker from 'expo-document-picker'; // "expo-document-picker": "9.2.4"

const data = await DocumentPicker.getDocumentAsync({
     type: 'application/pdf'
});
```

We then apply it to our Form Data:

```
const form = new FormData();
form.append("doc", {
     ...data,
     type: mime.getType(data.uri) // we use the mime package to determine the type
}); 
```

We then send it to our Node (HapiJS backend) via AXIOS passing in the `'content-type': 'multipart/form-data'` header.

Below is the error we are receiving:

```
{
  "message": "Network Error",
  "name": "Error",
  "stack": "createError@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:241425:26\nhandleError@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:241335:27\ndispatchEvent@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:33389:31\nsetReadyState@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:32554:33\n__didCompleteResponse@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:32370:29\nemit@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:4020:42\n__callFunction@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:3204:36\nhttp://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:2936:31\n__guard@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:3158:15\ncallFunctionReturnFlushedQueue@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:2935:21\ncallFunctionReturnFlushedQueue@[native code]",
  "config": {
    "url": "https://53c2-24-71-244-159.ngrok.io/submit",
    "method": "post",
    "data": {
      "_parts": [
        [
          "doc",
          {
            "size": 680351,
            "name": "testing.pdf",
            "uri": "/data/user/0/host.exp.exponent/cache/ExperienceData/%40myapp%2Fmyapp/DocumentPicker/74cc1ce0-eb40-42ee-9350-839b6c44fd95.pdf",
            "type": "application/pdf"
          }
        ]
      ]
    },
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Authorization": "JSON-WEB-TOKEN-HERE",
      "Content-Type": "multipart/form-data"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    }
  }
}
```

**Comment by NCMoseley** [comment]
We are having the same problem at our office, I hope someone knows why this is happening.
