### ISSUE TITLE
Getting `this.refs.signatureCanvas.takeSnapshotAsync is not a function` when trying to capture a signature in android

### ISSUE THREAD

**Issue by Muirik** [expo/expo#14514]
### Summary

I am using `react-native-signature-pad` to capture a signature (just in Android, as ExpoPixi does not work for Android) in my react-native app:

```
      { Platform.OS === 'ios' ?
        (
          <ExpoPixi.Signature
            ref='signatureCanvas'
            style={componentStyles.expoSignature}
            strokeWidth={3}
            strokeAlpha={0.5}
          />
        ) : (
          <SignaturePad 
            ref='signatureCanvas'
            style={componentStyles.expoSignature}
          />
 
        )
      }
```

This calls various functions based on user actions. One is a `capture` that calls `_onSave()`, which looks like this:

```
      async _onSave() {
        const signatureImage = await this.refs.signatureCanvas.takeSnapshotAsync({
          format: 'png',
          quality: 0.1,
          result: 'file',
        });
        
        await this.refs.signatureCanvas.clear();
    
        const convertedSignature = await ImageManipulator.manipulateAsync(
          signatureImage.uri,
          [{rotate: -90}],
          {
            compress: 0,
            format: ImageManipulator.SaveFormat.PNG,
            base64: true,
          }
        );
    
        await FileSystem.deleteAsync(signatureImage.uri, {idempotent: true});
        await FileSystem.deleteAsync(convertedSignature.uri, {idempotent: true});
    
        if(this.props.onSave) this.props.onSave(convertedSignature.base64);
    
        this.setState({
          visible: false
        });
      }

```
What I'm getting as a result is this:

> [Unhandled promise rejection: TypeError:
> this.refs.signatureCanvas.takeSnapshotAsync is not a function. (In
> 'this.refs.signatureCanvas.takeSnapshotAsync({]

I am using `async/await` with this function, so I'm not sure what the issue is. 

NOTE: This is not a problem using iPhone, just android, which confused me further, as both implementations end up calling the same functions.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

`  async _onSave() {
    const signatureImage = await this.refs.signatureCanvas.takeSnapshotAsync({
      format: 'png',
      quality: 0.1,
      result: 'file',
    });
    
    await this.refs.signatureCanvas.clear();

    const convertedSignature = await ImageManipulator.manipulateAsync(
      signatureImage.uri,
      [{rotate: -90}],
      {
        compress: 0,
        format: ImageManipulator.SaveFormat.PNG,
        base64: true,
      }
    );

    await FileSystem.deleteAsync(signatureImage.uri, {idempotent: true});
    await FileSystem.deleteAsync(convertedSignature.uri, {idempotent: true});

    if(this.props.onSave) this.props.onSave(convertedSignature.base64);

    this.setState({
      visible: false
    });
  }

  _onCancel() {
    this.setState({
      visible: false
    });

    this.refs.signatureCanvas.clear();

    if(this.props.onCancel) this.props.onCancel();
  }

  _onClear() {
    this.refs.signatureCanvas.clear();
    if(this.props.onClear) this.props.onClear();
  }
  
  render() {
    if(this.state.visible) {
      return (
        <View style={componentStyles.container}>
          { Platform.OS === 'ios' ?
            (
              <ExpoPixi.Signature
                ref='signatureCanvas'
                style={componentStyles.expoSignature}
                strokeWidth={3}
                strokeAlpha={0.5}
              />
            ) : (
              <SignaturePad 
                ref='signatureCanvas'
                style={componentStyles.expoSignature}
              />
     
            )
          }

          {(() => {
            if(this.state.overlay) {
              return (
                <View style={componentStyles.statusContainer}>
                  <View style={componentStyles.statusText}>
                    {this.state.overlay}
                  </View>
                </View>
              );
            }
          })()}

          <TouchableOpacity
            style={componentStyles.clearText}
            onPress={this._onClear.bind(this)}
          >
            <Text style={this.props.actionStyle}>Clear</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={componentStyles.cancelText}
            onPress={this._onCancel.bind(this)}
          >
            <Text style={this.props.actionStyle}>Cancel</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={componentStyles.signText}
            onPress={this._onSave.bind(this)}
          >
            <Text style={this.props.actionStyle}>Capture</Text>
          </TouchableOpacity>
        </View>
      );
    } else {
      return (
        <View></View>
      );
    }
  }`

**Comment by brentvatne** [comment]
post an issue to react-native-signature-pad :)
