### ISSUE TITLE
Error: Problem validating fields in app.json

### ISSUE THREAD

**Issue by prodeniser** [expo/expo#1451]
### Actual Behavior
I got the following message when starting up my first project:
```
Starting packager...
***ERROR STARTING PACKAGER***

Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v25.0.0/guides/configuration.html.
 • Field: slug - 'slug' should match pattern "^[a-zA-Z0-9\-]+$".
Packager started!
```

### Steps to Reproduce
I just updated my node to version 9.5.0 And wanted to try my hand at using create-react-native-app

1. Installed node 9.5.0 using homebrew
2. installed create-react-native-app using `npm install -g create-react-native-app`
3. created my app within a folder using `create-react-native-app project_name`
4. cd into the folder and used `npm start`

### Expected Behavior
Is it necessary to use yarn? I've not used it before but notice lots of the help that was output was saying to use `yarn start`? Is this actually causing me an issue or is this error unimportant?

I apologize if I'm not posting in the right place in any way. I'm newer to online community as a whole as I'm beginning my professional exploration of programming. If I am in error please accept my apologies and if possible point me somewhere I should be! I landed here after searching for my issue and finding similar posts here, but none identical (that I could find).

**Comment by jimmylee** [comment]
Hey @prodeniser! Welcome to Expo :)

To help you debug this issue, would you mind sharing with me your `app.json`? Also could you share with me your NPM version?

A lot of this isn't your fault, I think there are a lot of small booby traps that sometimes spring up in unexpected ways. Regardless, we'll definitely help you get through this!

Look forward to hearing from you soon.

**Comment by prodeniser** [comment]
Thanks for the prompt reply! Here is what I've got, let me know if this is helpful or not.

app.json:
```
{
  "expo": {
    "sdkVersion": "25.0.0"
  }
}
```
`npm -v` gives me the answer of 5.6.0 as the version I am running!
As a reminder the app.json has not been messed with me yet at all. In following a tutorial all I did was create-react-native-app and then attempted to run with npm. In between my post and your reply I also attempted a `yarn start` and got the same outcome. Hopefully this can give some clues.

**Comment by iamclaytonray** [comment]
Hey @prodeniser - I'm not sure why that error is occurring. I'm newer to Expo. Can you add this to you `app.json` and see if your build works?

app.json:

```json
{
  "expo": {
    "sdkVersion": "25.0.0",
    "slug": "project_name"
  }
}
```

**Comment by bnowak008** [comment]
I just ran into this problem.  It's because the project name has the underscore.  Doesn't comply with the fields pattern.
• Field: slug - 'slug' should match pattern "^[a-zA-Z0-9\-]+$".

**Comment by ashokips** [comment]
i am developing an react native app i facing error like 
D:\manickavasagam\july\init method\normalinit>react-native run-android
Scanning folders for symlinks in D:\manickavasagam\july\init method\normalinit\node_modules (51ms)
JS server not recognized, continuing with build...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

FAILURE: Build failed with an exception.
]
* What went wrong:
A problem occurred configuring root project 'normalinit'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.3.3.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:2.3.3.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/75.126.118.188] failed: Connection refused: connect
      > Could not resolve com.android.tools.build:gradle:2.3.3.
         > Could not get resource 'https://maven.google.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom'.
            > Could not HEAD 'https://maven.google.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom'.
               > Connect to maven.google.com:443 [maven.google.com/216.58.196.163] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED



in my machine
  java 8
gradle v 4.8.1
i am new to android studio in that build gradle  classpath 'com.android.tools.build:gradle:2.1.3'
in gradle properties distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip


kindly solve my problem

**Comment by ide** [comment]
@ashokips looking at your stack trace, the problem seems unrelated to the one in this issue to me and looks like you are having a problem with your computer's configuration or bare React Native -> can you please look at this issue more closely and determine whether your problem is related, and if not, open a new issue in the repos that are more related to your problem? If there is a problem with Expo specifically, we can look into it.
