### ISSUE TITLE
expo-notifications relies on Constants manifest, installationId, deviceId, and linkingUrl and throws warnings in bare projects 

### ISSUE THREAD

**Issue by MEsteves22** [expo/expo#14510]
### Summary

I'm using expo-notifications version 0.12.3 in a bare project, and it throws the following yellow box warnings:

`Constants.manifest is null because the embedded app.config could not be read. Ensure that you have installed the expo-constants build scripts if you need to read from Constants.manifest.`

`Constants.installationId has been deprecated in favor of generating and storing your own ID. Implement it using expo-application's androidId on Android and a storage API such as expo-secure-store on iOS and localStorage on the web. This API will be removed in SDK 44.`

`Constants.deviceId has been deprecated in favor of generating and storing your own ID. This API will be removed in SDK 44.`

`Constants.linkingUrl has been renamed to Constants.linkingUri. Consider using the Linking API directly. Constants.linkingUrl will be removed in SDK 44.`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.18.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 25, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.64.2 => 0.64.2 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by cruzach** [comment]
`expo-notifications` doesn't rely on `Constants. installationId `, `Constants.deviceId`, or `Constants. linkingUrl`, make sure to check the rest of your project for these.

`Constants.manifest` is only used as a fallback if no `projectId` or `experienceId` is provided to `getExpoPushTokenAsync` (but I do recommend adding those build scripts!)

**Comment by MEsteves22** [comment]
I only started having these warnings when I installed expo-notifications in my project. Before that, everything was fine. That's why I thought it did rely on these constants.

I'm going to check the rest of my project thought. 

Thanks!

**Comment by LudoLamerre** [comment]
Hi, 
Did you find a solution to this issue?
Thanks in advance

**Comment by MEsteves22** [comment]
Hello, 

No, unfortunately, I'm still having the same problem.

**Comment by LudoLamerre** [comment]
Did you try to log Constants like it is described in [react-native-unimodules installation tutorial](https://docs.expo.dev/bare/installing-unimodules/#usage)
```js
import { Constants } from 'react-native-unimodules';
console.log(Constants.systemFonts);
```
For me the problem came from a bad configuration of **react-native-unimodules** so I retake all the line of react-native-unimodules installation tutorial meticulously and the import of expo-notifications don't throw again this error.

Good luck.

**Comment by MEsteves22** [comment]
Thank you for your answer! 

I will try what you said and review my configuration of react-native-unimodules. Maybe I did miss something at the time.

**Comment by MEsteves22** [comment]
I configured `react-native-unimodules` again (some steps had changed), but I'm still having the same problem. The warnings are always showing up because of expo-notifications, more specifically, because of `getExpoPushTokenAsync`.

At the moment, I'm not having any problem because of this. I am not using `expo-constants` and `getExpoPushTokenAsync` in my project. It's just annoying to have these warnings, but I'll use LogBox to silence them.

**Comment by hotaryuzaki** [comment]
is there any solution?

**Comment by MEsteves22** [comment]
@hotaryuzaki I did not find a solution to my problem at the time. However, I was able to solve my problem when `expo` SDK 43 was released. With this new version, `react-native-uimodules` was replaced by the `expo` package so I uninstalled `react-native-uimodules` from my project and followed the new installation steps for bare React Native projects (https://github.com/expo/expo/tree/master/packages/expo-notifications). I stopped having warnings after this.

**Comment by Dinkelborg** [comment]
I just installed expo-firebase-analytics and created a custom hook for it - now I suddenly saw this warning. 
No idea where its from as I'm not using react-native-uimodules so it might have different sources too

**Comment by rodrix** [comment]
> I just installed expo-firebase-analytics and created a custom hook for it - now I suddenly saw this warning. No idea where its from as I'm not using react-native-uimodules so it might have different sources too

Same here

**Comment by brentvatne** [comment]
@rodrix - create a new issue with a reproducible example if you are encountering an issue
