### ISSUE TITLE
Remove react-native-splash-screen and replace it with react-native-bootsplash

### ISSUE THREAD

**Issue by silencer07** [expo/expo#14528]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by silencer07** [comment]
The said library is not maintained anymore and can interfere with notifications because it needs another activity to perform.

react-native-bootsplash it the way

**Comment by byCedric** [comment]
Hi @silencer07! We don't use `react-native-splash-screen` in the Expo templates, or packages. We have our own `expo-splash-screen` which is actively maintained. You are free to switch to a different splash screen if you want to, but we don't enforce either `react-native-splash-screen`, `react-native-bootsplash`, or our own `expo-splash-screen`.

Hope this helps!
