### ISSUE TITLE
[expo-network] Unable to access network information

### ISSUE THREAD

**Issue by DimaShustal** [expo/expo#14527]
### Summary

`Network.getNetworkStateAsync()` return Promise with error "ERR_NETWORK_NO_ACCESS_NETWORKINFO Unable to access network information" on Android if Internet is not reachable. There are all necessary permissions (`android.permission.ACCESS_NETWORK_STATE`, `android.permission.ACCESS_WIFI_STATE`) in the bundle. iOS works fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
 Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/dmitry/.rvm/gems/ruby-2.4.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

This is how I use getNetworkStateAsync function:

```
import {useEffect, useState} from 'react';
import * as Network from "expo-network";
import {Alert} from "react-native";

export default function useIsInternetReachable() {
  const [isInternetReachable, setIsInternetReachable] = useState(undefined);

  useEffect(() => {
    async function init() {
      try {
        const networkState = await Network.getNetworkStateAsync();

        setIsInternetReachable(networkState ? networkState.isInternetReachable : false);
      } catch (e) {
        Alert.alert('useIsInternetReachable error:', e.message);
      }
    }

    init();
  }, []);

  return isInternetReachable;
}

```

**Comment by cruzach** [comment]
What android version is this? Depending on if its below SDK 29 or not, then the problem is occurring somewhere [here](https://github.com/expo/expo/blob/9cd697533d64cdee216c641b792fda7952d1afcf/packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.java#L150-L179). SInce you're in the bare workflow, I recommend you run this through the android studio debugger to find out which line is causing what error

**Comment by cruzach** [comment]
Sorry- accidentally closed

**Comment by DimaShustal** [comment]
Android version - 28, tomorrow will try it on 30 version. About debugger I will try to find out the line and let you know.

**Comment by palatshq** [comment]
I'm having the same issue in a managed app. I have not done anything with permissions though, may that be it? According to the docs they should be added automatically.

**Comment by yash03112000** [comment]
@DimaShustal any update on this? I am facing the the same issue in Android8 device. It is working fine in Android 11 device. I am using eas build expo SDK43

**Comment by yash03112000** [comment]
@cruzach have you figured out what line is causing this error?
