### ISSUE TITLE
White screen after exp publish

### ISSUE THREAD

**Issue by wrightmk** [expo/expo#1452]
I have a detached application that currently runs fine in development, but when I publish my app using exp publish all I receive is a white screen. 

scan published qr --> splash screen --> white screen

Is this a known issue with expo?

Environment:
OS: macOS High Sierra 10.13
Node: 9.4.0
Yarn: 1.3.2
npm: 5.6.0
Xcode: 9.2 
Android Studio: 3.0.1

Packages:
expo: ^23.0.0
react: ^16.0.0
react-native: https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz

**Comment by jimmylee** [comment]
@wrightmk thanks for posting!

Leaving this github issue for reference: https://github.com/expo/expo/issues/1378

**Comment by wrightmk** [comment]
So it looks like if I view my application in closed alpha testing from the play store, the javascript is updated from when I exp published.  I guess there's just a bug in the preview url that XDE sends you (after you press 'publish') that results in a white screen.
