### ISSUE TITLE
AV API "Playback Status object":  isPlaying attribute issue

### ISSUE THREAD

**Issue by T-S-Chikaka** [expo/expo#14536]
### Summary

When using the Audio api, you can get an object that describes the status of the audio playing. On IOS when playing the audio object the isPlaying attribute remains FALSE, even while playing. When pausing the audio the isPlaying attribute has a material delay is flipping the isPlaying attribute. 

This is a major issue as the isPlaying attribute is important in order to make UI changes. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.0.

### Environment

Expo CLI 4.12.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
      npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
      Watchman: 2021.08.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 28, 29, 30
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-14 | ARM EABI v7a, android-15 | ARM EABI v7a, android-15 | Intel x86 Atom, android-16 | ARM EABI v7a, android-16 | Intel x86 Atom, android-17 | ARM EABI v7a, android-17 | Intel x86 Atom, android-18 | ARM EABI v7a, android-18 | Intel x86 Atom, android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-20 | Android Wear ARM EABI v7a, android-20 | Android Wear Intel x86 Atom, android-21 | Android TV ARM EABI v7a, android-21 | Android TV Intel x86 Atom, android-21 | Android Wear ARM EABI v7a, android-21 | Android Wear Intel x86 Atom, android-21 | ARM EABI v7a, android-21 | Intel x86 Atom, android-21 | Intel x86 Atom_64, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Android TV ARM EABI v7a, android-22 | Android TV Intel x86 Atom, android-22 | Android Wear ARM EABI v7a, android-22 | Android Wear Intel x86 Atom, android-22 | ARM EABI v7a, android-22 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Android TV ARM EABI v7a, android-23 | Android TV Intel x86 Atom, android-23 | Android Wear ARM EABI v7a, android-23 | Android Wear Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-N | Android TV Intel x86 Atom, android-N | Intel x86 Atom, android-N | Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

import React, { FC, useEffect, useState, createContext } from 'react'
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native'
import { episodes } from '../../mockData/stations'
import { Audio } from 'expo-av'
import { pauseVocals } from '../Helpers/AudioControllers'
import { Sound } from 'expo-av/build/Audio'

const Player: FC = () => {
  const [currentVocalTrack, setCurrentVocalTrack] = useState({})
  const [vocalPlaybackObj, setVocalPlaybackObj] = useState(null)
  const [vocalSoundStatus, setVocalSoundStatus] = useState(null)

  const pauseAudio = async playbackObjs => {
    try {
      const status = await playbackObjs.pauseAsync()
      setVocalSoundStatus(status)
      console.log("pause status", status);
    } catch (error) {
      console.log('error pausing: ', error);
    }
  }

  const resumeAudio = async playbackObjs => {
    try {
      const status = await playbackObjs.playAsync()
      setVocalSoundStatus(status)
      /console.log("resume status", status);
    } catch (error) {
      console.log('error pausing: ', error);
    }
  }

  const handleVocalPlaybackObj = async audio => {
      if(vocalPlaybackObj == null ) {
        try {
          const {
            sound: soundObject,
            status,
          } = await Audio.Sound.createAsync({uri: audio}, { shouldPlay: true })
          soundObject.setProgressUpdateIntervalAsync(3000)
          setVocalPlaybackObj(soundObject)
          setVocalSoundStatus(status)
          console.log(' initial status', status);
        } catch (error) {
          console.log('error playing: ', error);
        }  

        return
      }
      //pause audio
      if (vocalSoundStatus.isPlaying && vocalSoundStatus.isLoaded) {
          pauseAudio(vocalPlaybackObj)
          return
      }
      //resume audio
      if(!(vocalSoundStatus.isPlaying) && vocalSoundStatus.isLoaded) {
        resumeAudio(vocalPlaybackObj)
        return
      }
  }

useEffect(() => {
 console.log('vocal sound status', vocalSoundStatus?.isPlaying)
}, [vocalSoundStatus]);

  return (
    <View style={styles.container}>
      <View style={styles.row}>
        <TouchableOpacity onPress={() => handleVocalPlaybackObj("https://hwcdn.libsyn.com/p/a/0/7/a07a71a9312a8644/Star_Wars_-_The_Force_Awakens.mp3?c_id=62813327&cs_id=62813327&destination_id=759218&expiration=1630060232&hwt=03e8c74a868df24b5a299be1dd397336")} style={styles.button}>
          <Text style={styles.text}>Play</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={() => pauseAudio(vocalPlaybackObj)} style={styles.button}>
          <Text style={styles.text}>Pause</Text>
        </TouchableOpacity>
      </View>
      <View style={styles.row}>
        <TouchableOpacity onPress={() => resumeAudio(vocalPlaybackObj)} style={styles.button}>
          <Text style={styles.text}>Resume</Text>
        </TouchableOpacity>
      </View>
    </View>
  )
}
//634
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  row: {
    flexDirection: 'row',
    marginBottom: 30,
  },
  text: {
    fontSize: 30,
    color: 'white',
    textAlign: 'center',
  },
  button: {
    backgroundColor: 'red',
    padding: 15,
    borderRadius: 10,
    margin: 10,
    width: 160,
  },
  button2: {
    backgroundColor: 'blue',
    padding: 15,
    borderRadius: 10,
    margin: 10,
    width: 180,
  },
})

export default Player

To Reproduce:

1) copy this component into an expo project
2) Change root component to this component
3) run project
4) press play and read console output to seek status updates

**Comment by jasongaare** [comment]
hitting this too right now - did you find any solution?
