### ISSUE TITLE
ExponentCameraModule.takePicture got 4 arguments, expected 3

### ISSUE THREAD

**Issue by Plorax** [expo/expo#1454]
https://github.com/expo/expo/blob/43656ac07ecbc1337bff2479e4023359a7d21b22/android/expoview/src/main/java/abi26_0_0/host/exp/exponent/modules/api/components/camera/CameraModule.java#L194

When I call takePictureAsync on the camera component it throws an exception:
"ExponentCameraModule.takePicture got 4 arguments, expected 3"

Looking at this java component/module "CameraModule.java" I can clearly see it has three arguments. Why is it being called with 4 arguments and where ?

Is it something I can change on my side ?

  "dependencies": {
    "babel-core": "^6.26.0",
    "expo": "^25.0.0",
    "moment": "^2.20.1",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-buttons": "^0.0.11",
    "react-dom": "^16.2.0",
    "react-motion": "^0.5.2",
    "react-native": "^0.51.0",
    "react-native-camera": "^0.12.0",
    "react-native-extended-stylesheet": "^0.8.0",
    "react-native-maps": "^0.19.0",
    "react-native-material-dropdown": "^0.7.1",
    "react-native-material-ripple": "^0.7.5",
    "react-native-material-textfield": "^0.12.0",
    "react-native-modal-datetime-picker": "^4.13.0",
    "react-native-network-info": "^3.0.0",
    "react-native-remote-svg": "^1.0.1",
    "react-native-vector-icons": "^4.5.0"
  }

"devDependencies": {
    "concurrently": "^3.5.1",
    "eslint": "^4.15.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "jest-expo": "^24.0.0",
    "react-native-scripts": "1.8.1",
    "react-test-renderer": "16.2.0",
    "rimraf": "^2.6.2",
    "tslint": "^5.9.1",
    "typescript": "^2.7.1"
  },

**Comment by ccheever** [comment]
Here are the arguments it takes from JS:
https://docs.expo.io/versions/latest/sdk/camera.html#takepictureasync

Just an options object
options (object) —

A map of options:

quality (number) — Specify the quality of compression, from 0 to 1. 0 means compress for small size, 1 means compress for maximum quality.

base64 (boolean) — Whether to also include the image data in Base64 format.

exif (boolean) — Whether to also include the EXIF data for the image.



What are you trying to call it with?

**Comment by Reddemonfox** [comment]
Same Issue with me. I am sending empty object inside takePictureAsync

**Comment by quinlanj** [comment]
hey @Reddemonfox , if calls to `takePictureAsync` is not working as specified in the docs, could you make a new issue, plus a repro (in snakc.expo.io preferably) for it? this issue was opened quite a while ago and a lot has changed since then. thanks!

**Comment by Reddemonfox** [comment]
Hey, It started working once I update the expo version to 27. So I am closing this issue.
