### ISSUE TITLE
Image picker removes exif data from copied file

### ISSUE THREAD

**Issue by Dakuan** [expo/expo#14568]
### Summary

When you use `ImagePicker.launchImageLibraryAsync` it will extract the exif data from the image, and relay that if the `{exif: true}` option is provided. However, when the selected image is copied to the temp folder, the exif data is missing from the copied image. This means that if the image is uploaded, the image on the server will not have the exif data. This behaviour has not been requested, and shouldn't happen. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.9.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v16.5.0/bin/yarn
      npm: 7.20.2 - ~/.nvm/versions/node/v16.5.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.9.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@dakuan/exif-removed

**Comment by Simek** [comment]
Hi @Dakuan, 

the `exif-parser` package you are using in the code outputs JSON in different format than the `ImagePicker`. The `LensModel` property you are looking for is located in `tags` not in `exif` after the parse. 

You can see your example with the fix in there:
* https://snack.expo.dev/@simek/exif-removed

**Comment by Dakuan** [comment]
heya, thats not working for me:

![image](https://user-images.githubusercontent.com/633621/135393897-06cba15c-3b26-4935-bdb0-f5bec2841516.png)


same if I use the [piexifjs](https://github.com/hMatoba/piexifjs) lib:

```
Object {
  "0th": Object {
    "274": 1,
    "34665": 38,
  },
  "1st": Object {},
  "Exif": Object {
    "40961": 65535,
    "40962": 5472,
    "40963": 3648,
  },
  "GPS": Object {},
  "Interop": Object {},
  "thumbnail": null,
}
```

**Comment by Simek** [comment]
> heya, thats not working for me:

Sorry, but I did not understand the problem, can you clarify? Is my Snack example not working for you, or you are talking about other code? 

I'm not sure why you expect the different libraries to output exactly the same result. Currently for me it looks like the issues you are experiencing are not related to Expo.

**Comment by Dakuan** [comment]
Your updated snack is not retuning exif data for me. Same goes for when the file is eventually uploaded to cloud storage. its not reformatting, its removing the data entirely

**Comment by Simek** [comment]
> Your updated snack is not retuning exif data for me. 

This it weird, it might be related to the specific image you are trying to use. Snack works for me fine of the few test devices. 

Also you need to remember that not all photos on the device will have the lens data, for example iOS screenshot do not have that property set at all, same for the most images download form the web.

![IMG_7063](https://user-images.githubusercontent.com/719641/135461632-e2ae98b1-b2bf-4630-9518-bcb657dafa49.PNG)

**Comment by Dakuan** [comment]
before expo
![image](https://user-images.githubusercontent.com/633621/135461899-9ab87d8a-bbbe-4413-84d1-ea696480d157.png)

after expo:
![image](https://user-images.githubusercontent.com/633621/135462040-b13f636a-ac66-445d-a777-4e10231ac9e9.png)

your snack:
![image](https://user-images.githubusercontent.com/633621/135462246-424d10e7-2891-46bd-b282-9890eb70213b.png)

**Comment by Simek** [comment]
Still it looks like for me like `exif-parser` issue, since it's the library responsible for parsing the base64 string. 

The `ImagePicker` returns correct EXIF (before value) as your example shows in the first place. It's one of your manipulation on that file which move/removes/inavlidates EXIF data.

**Comment by Simek** [comment]
> Our app is for pro wildlife photographers. Their photos are straight from camera, or via adobe lightroom and contain _lots_ of exif data. I've scraped all the files in the storage bucket, they are all blank. Images are not processed at all by our app. Just uploaded to GCloud.

Did you try to use `uploadAsync` (https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemuploadasyncurl-fileuri-options) in your case instead of using `readAsStringAsync` and re-parsing image it back just to send it?

**Comment by BrodaNoel** [comment]
This issue is still reproducible
