### ISSUE TITLE
[expo-app-loading] Component Exception, element type is invalid with version 1.1.3

### ISSUE THREAD

**Issue by cameronmurphy** [expo/expo#14579]
### Summary

I upgraded to `expo-app-loading` 1.1.3 and my app now crashes with this error.

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.12.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.3.1 - /usr/local/bin/fish
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 3.0.2 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 7.24.1 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2021.09.13.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

After running `expo init`, run `expo install expo-app-loading` and change `App.js` to look like this.
```
export default function App() {
  const [isReady, setIsReady] = useState(false);

  setTimeout(() => setIsReady(true), 1000);

  if (!isReady) {
    return <AppLoading />;
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}
```

**Comment by brentvatne** [comment]
this error means you are not importing the component correctly. you didn't share your full code so it's hard to tell exactly, but you should write:

```
import AppLoading from 'expo-app-loading';
```

**Comment by cameronmurphy** [comment]
This response means you didn't even run my example. I have updated the issue to include my import statements.

**Comment by brentvatne** [comment]
i could not have possibly run your example because it was incomplete at the time that i responded.

it looks like you are using `expo-app-loading@^1.1.3` - this is not the recommended version for sdk 42. it currently has the `next` tag and isn't installed by default when you run `expo install expo-app-loading`. you should always use `expo install` when installing expo packages and any time you opt into a version that isn't installed by that the docs may not apply.

however, you are absolutely correct that in the *unreleased version 1.1.3* there is a regression caused by [this commit](https://github.com/expo/expo/pull/13396/files#diff-f7290d2eba0aba5ceff18b7ba50b45d3a3d5fae5f783c6958da5a42c4aae1b28) that changes the default import. @Simek will follow up on this!

**Comment by cameronmurphy** [comment]
Ah, I stumbled upon this error because I use `yarn upgrade-interactive` to bump dependencies, then `expo upgrade` to restrict expo dependencies back to versions compatible with my SDK version. Because 1.1.3 falls under `^@1.1.2` it wasn't downgraded. Thank you.

**Comment by cameronmurphy** [comment]
It actually doesn't look like I'm the first person to have this issue with Yarn 3 and Expo, FYI

https://github.com/yarnpkg/berry/issues/3472

**Comment by brentvatne** [comment]
interesting, i hadn't realized that this was how yarn conceptualized npm tags. thanks for sharing!

**Comment by asallem** [comment]
pour ma part j'ai eu ce problème car j'utilisais "import { AppLoading } from "expo";" alors que désormais il l'importer de 'expo-app-loading'. => import { AppLoading } from 'expo-app-loading';
