### ISSUE TITLE
[expo-av] Cannot record in the background on Android

### ISSUE THREAD

**Issue by berkcoker** [expo/expo#14573]
### Summary

Cannot record audio in the background on Android. Once the app is backgrounded, the audio goes silent in newer Android versions.

The solution is to include a foreground service in the expo-av library. Should not be a huge lift, since this functionality already exists in expo-location. Or maybe this warrants a new expo-foreground-service package for Android?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.12.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

[https://snack.expo.dev/@berkcoker/background-audio-recording](https://snack.expo.dev/@berkcoker/background-audio-recording)

**Comment by joseph-jordan** [comment]
@berkcoker have you found a workaround for this issue?

**Comment by berkcoker** [comment]
Our workaround is to use bareflow for Android builds... We eject and adjust AndroidManifest.xml right before queueing for a build, which we've automated with Github Actions so that we don't have to deal with this locally. After all, the bareflow is necessary only for the foreground service...
