### ISSUE TITLE
Playing audio on Android error

### ISSUE THREAD

**Issue by FacuAcosta** [expo/expo#146]
HI guys! I'm trying to make a simple app that plays a sound whenever you press a button. At the moment, If I press the button it plays the sound just once and If I play It again:

- On iOS: It does nothing, It's not playing the audio again.

- On Android: It's giving me an exception/error with no title or whatsoever, like this: 

![screenshot_20170502-124131](https://cloud.githubusercontent.com/assets/19332669/25616534/45fbc81c-2f35-11e7-8023-aa056c2257d7.png)

What am I missing? The code I have is really simple and I don't know what to do to play the sound again and to solve the error.

```
{.............}
componentDidMount() {
		Audio.setIsEnabledAsync(true);
		Audio.setAudioModeAsync({
			allowsRecordingIOS: false,
			interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
			playsInSilentLockedModeIOS: true,
			shouldDuckAndroid: true,
			interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
		});

		this.getSoundLoaded();
	}

	getSoundLoaded = async () => {
		try { 
			if (this.sound === null) {
				this.sound = new Expo.Audio.Sound({
					source: require('../assets/audio/audio_sample.mp3')
				});
			}
			await this.sound.loadAsync();
			this.setState({ status: await this.sound.getStatusAsync() });
			return this.sound;
		} catch (error) {
			console.log(error);
		}
	}
        //This function is called in onPress on a TouchableHighlight
	playButtonPressed = async () => {
		if (this.sound != null) {
			//await this.sound.setIsLoopingAsync(this.state.loopingType === 1);
			await this.sound.playAsync();
		}		
	}

{.............}
```

**Comment by gkufera** [comment]
Hi @FacuAcosta!

The function `playAsync()`plays the sound from the current position of the sound. If the sound has already finished, it won't play unless you reset the position of the sound.

In a future version of the Audio API (probably SDK17), we will allow you to pass in a position as an argument to `playAsync`, so that `this.sound.playAsync(0)` will seek to the beginning of the sound and then play from that point. In SDK16, however, you need to call `setPositionAsync()` separately.

```
// This will work:
playButtonPressed = async () => {
  if (this.sound != null) {
    await this.sound.setPositionAsync(0);
    await this.sound.playAsync();
  }		
}
```

That Android bug is bizarre though -- it shouldn't give an error for this, it should just make no sound! I will look into that.

Let me know if you have any more questions or if anything was unclear. Thanks!

**Comment by FacuAcosta** [comment]
Hi @gkufera !

Thank you so much for your help! The iOS version perfectly works now, but I guess I've found a bug with the Android version because It's giving me the same exception. 

Anyway, I had to rebuild the project using just react-native and adding react-native-sound module to It because I needed It for an important project. If you get to fix the bug just let me know so I can keep using Expo, Thanks!

**Comment by ethanx94** [comment]
Getting an unhandled promise rejection. Cannot load null source when specifying a local source. However if I do a similar technique through Snack online, I get no errors at all.

```javascript
class App extends React.Component {
  playSound = async () => {
    await Expo.Audio.setIsEnabledAsync(true);
    const sound = new Expo.Audio.Sound({
      source: require('./assets/sounds/sound.m4a')
    });
    await sound.loadAsync();
    await sound.playAsync();
  };
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.playSound}>
          <Text style={styles.paragraph}>
            {'Touch To Play Sound'}
          </Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```

**Comment by gkufera** [comment]
Hi @ethanx94! Sorry for the confusion, but it looks like you are using outdated syntax to play your sound. As of SDK17, we require the source passed as a parameter to `loadAsync()`, not `new Sound()`. Here is a potential fix with the correct syntax:
```
...
  playSound = async () => {
    await Expo.Audio.setIsEnabledAsync(true);
    const sound = new Expo.Audio.Sound();
    await sound.loadAsync(require('./assets/sounds/sound.m4a'));
    await sound.playAsync();
  };
...
```

Also @ethanx94 in the future, we would like to ask that you open a new issue for a new bug. Thanks and let me know if you encounter any more problems / have any more questions!

@FacuAcosta -- I think that SDK17 should fix the Android error that you experienced. Are you able to test again to see if this is still occurring? We also provide the convenience function `this.sound.playFromPositionAsync(0)` starting in this SDK as well.

Thanks!
