### ISSUE TITLE
Accelerometer is not working on first run in Android 

### ISSUE THREAD

**Issue by TheHemantKaushik** [expo/expo#1460]
### Environment

Android

### Steps to Reproduce

When I run sample code the given on [Expo Accelerometer documentation]((https://docs.expo.io/versions/latest/sdk/accelerometer.html)). It is showing 0 for x, y, z axis. When I press back button and run app again, it is showing values for all the 3 axis x, y and z.

1. create new app using Expo
2. copy Accelerometer sample code given in documentation
3. run app on Android platform (show 0 values for x, y and z)
4. press back (do not remove from recents apps)
5. open app again (show actual values for x, y and z)

### Expected Behavior

App should show data for x, y and z axis.

### Actual Behavior

App is showing 0 for all the three values.

![1-not-working](https://user-images.githubusercontent.com/28451375/36540565-df0c4040-1800-11e8-885b-b838757f2d36.png)
![2-working](https://user-images.githubusercontent.com/28451375/36540566-df4fc5ea-1800-11e8-9f2e-62f3a3213cf5.png)

### Reproducible Demo

https://docs.expo.io/versions/latest/sdk/accelerometer.html

**Comment by sjchmiela** [comment]
Hi, @TheHemantKaushik, thanks for reporting the issue! Fortunately, we're aware of this bug and are already forking on a fix for it (https://github.com/expo/universe/pull/2089). It should get merged soon! 🙂

**Comment by TheHemantKaushik** [comment]
Hi @sjchmiela, could you please let me know any expected date? I'm waiting for this bug to be fixed.

**Comment by parulgarg004** [comment]
Hello @sjchmiela 

I'm facing the same issue, can you please tell me when we can expect update for this fix?

**Comment by jesseruder** [comment]
@TheHemantKaushik @parulgarg004 the fix for this will go out in our next major release in approximately 2 weeks

**Comment by colinux** [comment]
To people affected: as a workaround I rollbacked to Expo 24.0.0 (and dependencies…) which does not seem to be affected by this bug.

**Comment by TheHemantKaushik** [comment]
Hi @jesseruder,
I know you guys are working hard for next major release.
Could you please let me know when this major release is rolling out? I am eagerly waiting for it.
Thanks

**Comment by parulgarg004** [comment]
Hello @sjchmiela 
Can you please update on tentative date for this fix.

**Comment by sjchmiela** [comment]
Hi all, all I can say is

> we release SDK 26 in the next few days.

as @terribleben said in https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. Sorry for the delay!
