### ISSUE TITLE
Android - String index out of range: 0 - FAILURE: Build failed with an exception. (App Center)

### ISSUE THREAD

**Issue by Aleksandern** [expo/expo#14607]
### Summary

I can't build Android release on Microsoft App Center.

I've got the error.
```
Starting a Gradle Daemon (subsequent builds will be faster)
Gradle 6.9
FAILURE: Build failed with an exception.
* Where:
Settings file ‘/Users/runner/work/1/s/mobile/android/settings.gradle’ line: 2
* What went wrong:
A problem occurred evaluating settings ‘ projname’.
> String index out of range: 0
```

But I can build locally without any problem.
Maybe somebody has any suggestions what's the problem?

`android/settings.gradle`
```
rootProject.name = 'projname'
apply from: new File(["node", "--print", "require.resolve('react-native-unimodules/package.json')"].execute().text.trim(), "../gradle.groovy"); includeUnimodulesProjects()
apply from: new File(["node", "--print", "require.resolve('@react-native-community/cli-platform-android/package.json')"].execute().text.trim(), "../native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'

```

`build.gradle`
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "23.0.7599858"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.1")
    }
}
```

`package.json`
```
    "react-native": "0.65.1",
    "react-native-unimodules": "^0.14.7",
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

  "dependencies": {
    "@dudigital/react-native-zoomable-view": "^1.1.3",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^6.0.2",
    "@react-native-picker/picker": "^1.8.3",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^6.0.7",
    "@sentry/react-native": "^3.0.1",
    "axios": "^0.21.4",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "expo-blur": "^9.0.3",
    "expo-image-manipulator": "^9.2.2",
    "expo-image-picker": "^10.2.3",
    "formik": "^2.2.9",
    "javascript-time-ago": "^2.3.8",
    "lodash": "^4.17.21",
    "luxon": "^2.0.2",
    "moment": "^2.29.1",
    "native-base": "^2.15.2",
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-animatable": "^1.3.3",
    "react-native-camera": "^4.1.1",
    "react-native-dotenv": "^3.2.0",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-fast-image": "^8.3.7",
    "react-native-formik": "^1.7.8",
    "react-native-fs": "^2.18.0",
    "react-native-fullwidth-image": "^0.1.3",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-modal": "^13.0.0",
    "react-native-permissions": "^3.0.5",
    "react-native-picker-select": "^8.0.4",
    "react-native-qrcode-scanner": "^1.5.4",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.6.0",
    "react-native-share": "^7.0.2",
    "react-native-unimodules": "^0.14.7",
    "react-native-vector-icons": "^8.1.0",
    "react-native-version-number": "^0.3.6",
    "react-native-zip-archive": "^6.0.3",
    "react-redux": "^7.2.5",
    "redux-devtools-extension": "^2.13.9",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-persist-expo-fs-storage": "^2.1.0",
    "redux-saga": "^1.1.3",
    "reduxsauce": "^1.2.1",
    "yup": "^0.32.9"
  },

### Environment

can't run

### Reproducible demo or steps to reproduce from a blank project

run on Microsoft App Center

**Comment by maxjmay** [comment]
Hi, I'm getting the same error on App Center, what did you do to resolve it?

**Comment by Aleksandern** [comment]
Hi
We have a mono repo and there was a path issue in `android/settings.grandle`.
For example the have the following string in our file:
```
apply from: new File(["node", "--print", "require.resolve('react-native-unimodules/package.json')"].execute().text.trim(), "../gradle.groovy"); includeUnimodulesProjects()
```

It works okay from the mobile folder but it doesn't work from the root folder so we should update our line like this:

```
apply from: new File(["node", "--print", "require('path').resolve('mobile/node_modules/react-native-unimodules/package.json')"].execute().text.trim(), "../gradle.groovy"); includeUnimodulesProjects()
```
