### ISSUE TITLE
App crash while sending an error object as second parameter in Alert.alert()

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#14627]
### Summary

App crash (get closed) while sending an error object as second parameter in Alert.alert()

Reproducible in: https://snack.expo.dev/@brodanoel/alert-crash

Didn't test it on Android.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

https://snack.expo.dev/@brodanoel/alert-crash

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@brodanoel/alert-crash

**Comment by byCedric** [comment]
Hi @BrodaNoel, I agree that the crash isn't ideal. But, as [the RN docs state](https://reactnative.dev/docs/alert#alert), the second parameter must be a string. You can easily fix that by [converting the error object to a string before calling the alert](https://snack.expo.dev/@bycedric/expo-issue-14627). Unfortunately, it is common that React Native APIs tend to respond in an unexpected way when using the wrong types. We try to guard these types in our packages though.

Hope this helps!
