### ISSUE TITLE
GLView has no depth buffer on Android

### ISSUE THREAD

**Issue by leops** [expo/expo#1462]
### Environment

Expo: 25.0.0

Tested on devices:
- Samsung Galaxy Tab S3 (Android 7.0)
- Google Nexus 9 (Android 7.1.1)
- Google Pixel 2 (Android 8.1.0)

### Steps to Reproduce

1. Create an empty app with `expo-graphics` and `expo-three`
2. Create an `ExpoGraphics.View` rendering a scene from `expo-three`
3. Fill the scene with a mesh and some lights
4. Turn off backface culling (by setting `side: THREE.DoubleSide` on the mesh material) to make the problem more apparent

### Expected Behavior

The faces of the mesh should be properly sorted using a depth buffer.

### Actual Behavior

Depth sorting is not enabled, and the faces are incorrectly sorted.

The origin of the problem can be easily traced to [this line](https://github.com/expo/expo/blob/43656ac07ecbc1337bff2479e4023359a7d21b22/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/gl/GLView.java#L306), which requires a zero-sized depth buffer for the GLView (`EGL10.EGL_DEPTH_SIZE, 0`), making it impossible to enable any kind of depth sorting.

### Reproducible Demo

https://snack.expo.io/HkAvD_hPM

**Comment by nikki93** [comment]
Thanks for reporting -- we'll set the `EGL10.EGL_DEPTH_SIZE` to `16` to address this. We have a new Android client version hitting the Play Store soon and can get it into that, I'll post back here when it's going to come out!

**Comment by nikki93** [comment]
In the mean time -- you can render to a framebuffer that has a depth attachment and then render that framebuffer to the default framebuffer. This would add another render step but just as a workaround till the release.

**Comment by nikki93** [comment]
Fixed in https://github.com/expo/expo/commit/1b6ed8072332e1e03147c7e69a8572d9f1ed89ae, will come out when SDK 26 hits the stores.
