### ISSUE TITLE
Branch NativeLink support - Upgrade expo-branch to Aug 17 (5.0.4) release of react-native-branch

### ISSUE THREAD

**Issue by Aryk** [expo/expo#14631]
### Summary

Here is the related discussion I had with @wodin : 

https://forums.expo.dev/t/branch-nativelink-is-it-supported/57157/4

Basically [PrivateRelay for iCloud+](https://www.theverge.com/2021/6/10/22526881/apple-icloud-plus-privacy-subscription-services-revenue-wwdc-2021) users on iOS 15 kills Branch functionality [completely](https://blog.branch.io/nativelink-solution-to-challenges-caused-by-ios-15/). The SDK already [solved it](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/667#issuecomment-901058396) on version 5.0.4 of react-native-branch but expo-branch needs to be upgraded in the Expo SDK (I'm using managed workflow).

My expectation was that the Oct release of SDK 43 would have this Aug 17 version of branch, but apparently [it does not](https://github.com/expo/expo/blob/sdk-43/packages/expo-branch/package.json#L37).

Obviously, the easiest thing would be to get expo-branch on the latest version for SDK 43 release. Would this be possible to do? Otherwise...it could render expo-branch **unusable for 25% of all smartphones** (50% being iphone * 50% using private relay which is enabled by default for icloud paying customers).

Not sure if I could just bump the react-native-branch version myself but if there are some linking required or what not, it likely won't work.

I'd be happy to pay a developer too to get this working. It's crucial attributing installs for my project.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

I know I'm not on 43 yet...but I will be...

  Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.12.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/aryk/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

None

**Comment by kennethlynne** [comment]
Any news on this? We want to use this in an enterprise app to handle deep links, but then I found this issue.

**Comment by brentvatne** [comment]
i would suggest using EAS Build for your app and then using the library provided by Branch directly. more info on how you can do that in this forums post: https://forums.expo.dev/t/eas-react-native-branch-example-config-plugin-working-on-ios-and-android/56017

**Comment by Aryk** [comment]
@kennethlynne - in case you decide to roll your own...maybe this is helpful:

https://forums.expo.dev/t/branch-nativelink-is-it-supported/57157/13?u=tennisbum

**Comment by kennethlynne** [comment]
Thanks for the follow-up guys will investigate both suggestions. We're using EAS build, but there are contradicting information in the documentation about what to do when you want to use branch on EAS (https://docs.expo.dev/versions/latest/sdk/branch/ indicates that expo-branch should work just fine, official branch documentation says you need to eject (https://help.branch.io/developers-hub/docs/react-native#option-1-pure-react-native-app)).

Since there is a valid suggestion on the forums for how to implement it, but not a proper implementation in expo-branch I guess it is because Expo does not want to maintain it? Or has just no one got around to make a PR for it (I could help out)?

**Comment by kennethlynne** [comment]
We decided to work around branch for now without the integration :(. If there is a solution readily available but not merged is it because expo do not want to support it or should someone make a PR for it?

**Comment by brentvatne** [comment]
you can use branch with eas build with this package: https://www.npmjs.com/package/@config-plugins/react-native-branch
