### ISSUE TITLE
IOS Standalone Apps can’t Push Token 

### ISSUE THREAD

**Issue by TrongVT** [expo/expo#1463]
Why IOS Standalone Apps can’t Push Token?
when I Building Standalone Apps on iOS.
Please,thank all,

**Comment by ide** [comment]
Our uptime monitoring indicates that iOS push notifications are working and other developers haven’t reported an issue, so currently it seems likely there is an issue with your app code, configuration, or server code.

**Comment by TrongVT** [comment]
thanks @ide ...i got it.
