### ISSUE TITLE
Pressing on grouped push notifications on Android does not trigger the event listener

### ISSUE THREAD

**Issue by d4rky-pl** [expo/expo#14634]
### Summary

Android by default groups notifications from the same app when a certain threshold of them is reached. This group of notifications can still be pressed and it will open the app but the `addNotificationResponseReceivedListener` is not triggered when it happens

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - /var/folders/kc/w3zg_rmd6vnd_5w22fw154yh0000gn/T/yarn--1633355334586-0.43974177278349735/node
      Yarn: 1.22.5 - /var/folders/kc/w3zg_rmd6vnd_5w22fw154yh0000gn/T/yarn--1633355334586-0.43974177278349735/yarn
      npm: 6.14.4 - ~/.asdf/installs/nodejs/12.16.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

**Warning: this will behave slightly differently depends on if it's run via Expo Go or as standalone app**

Snack: https://snack.expo.dev/@helpling/push-notifications

To trigger the issue, press the "Schedule a notification" button 10 times and background the app, then wait a moment. Android will first display all notifications one after another but it will group them after a while. Then, press those grouped notifications in the notifications panel.

- In Expo Go pressing on the notification group will open Expo Go app, main menu. The specific Snack will not be launched.
- In standalone app, pressing on the notification group will open the app. The event listener will not be triggered though. Expanding the group and then pressing a single notification works correctly.

I would attach a built APK as well but GitHub does not allow me to :)

**Comment by d4rky-pl** [comment]
Still a problem

**Comment by d4rky-pl** [comment]
I'm starting to see no point in reporting any further issues with Expo...

**Comment by jakemadash** [comment]
I've just discovered this myself. Any updates Expo team?
