### ISSUE TITLE
Unable in install 'react-native-track-player' with Expo managed workflow

### ISSUE THREAD

**Issue by LisharBahar** [expo/expo#14642]
### Summary

Unable in install react-native-track-player

> npm install --save react-native-track-player
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.6" from react-native-track-player@2.1.1
npm ERR!   node_modules/react-native-track-player
npm ERR!     react-native-track-player@"*" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native-windows@0.65.4
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.63.0" from react-native-track-player@2.1.1
npm ERR!   node_modules/react-native-track-player
npm ERR!     react-native-track-player@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.1 - /usr/local/bin/node
      npm: 7.19.1 - /opt/homebrew/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 30
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Ran 'expo install react-native-track-player' and got an error

**Comment by wodin** [comment]
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps

Try:
npm install --legacy-peer-deps react-native-track-player

(--save is implied in recent versions of npm.)

Note: The installation instructions for react-native-track-player mention enabling Swift support. So you might need a config plugin to do that. Off hand I don't know what changes that makes to the project.

**Comment by byCedric** [comment]
As @wodin mentioned, it's a common error with npm 7+ ([see this comment](https://github.com/expo/expo/issues/14532#issuecomment-927863413)). You should be able to workaround it with the `--legacy-peer-deps` flag
