### ISSUE TITLE
ios/2.14.6 tag branch is removed from git, older version app not build. kindly update immediately

### ISSUE THREAD

**Issue by raghulrajnkl** [expo/expo#14661]
ios/2.14.6 tag branch is removed from git, older version app not build. kindly update immediately

**Comment by cruzach** [comment]
Not sure what this is referring to- please provide more info and we can reopen. Have a feeling this is related to the expokit tags: https://forums.expo.dev/t/expokit-pod-install-fails-sdk-37/54583/12
