### ISSUE TITLE
Video, unloadAsync() and loadAsync() not working in WEB

### ISSUE THREAD

**Issue by JoshLi15** [expo/expo#14669]
### Summary

I want to use the unload- and loadAsync method as intended to change my video resource and destroy it at the end. On Android/IOS everything works as intended but not in web. The only way that I managed to change the video resource was by setting the source via a state update but the problem with the unloading still existed.. 
I couldn't find any other problems with the other video methods in web,
My current expo-av version is 9.1.2 because of the issue expo/expo#13553, but with 9.2.3 the problem was the same.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.12.1 environment info:
    System:
      OS: Linux 5.9 Manjaro Linux
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 16.8.0 - /usr/bin/node
      npm: 7.21.1 - /usr/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.82 
      expo: ^42.0.3 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@josh55/videoproblems

Use the Action Button to trigger the chain of stopping -> unloading -> loading new resource -> playing.

**Comment by bananemo** [comment]
@JoshLi15 I'm also encountering the same problem. When I use loadAsync and unloadAsync, it doesn't work on the web. Did you find a solution in the end? And can you share how did you do the state update to load the video? I tried to do that but it doesn't work.
