### ISSUE TITLE
EAS managed build fails on `createReleaseExpoManifest` in monorepo

### ISSUE THREAD

**Issue by thomas-coldwell** [expo/expo#14663]
### Summary

I've just moved my managed app to a monorepo following [this](https://github.com/byCedric/eas-monorepo-example) guide. I can run it fine locally, but when I run EAS build it fails at `createReleaseExpoManifest` (part of `expo-updates`) stating fromDir expected type of string but got undefined. I've taken a look and it appears that it occurs at this line https://github.com/expo/expo/blob/master/packages/expo-updates/scripts/createManifest.js#L27 where the `projectRoot` isn't resolved correctly above it and is undefined when it is then used to try and resolve the metro config. Will keep digging and see if I can resolve it and if it successfully builds without `expo-updates`

![Screenshot 2021-10-06 at 21 03 06](https://user-images.githubusercontent.com/31568400/136275006-b77bdfcf-cf7b-441e-a9f2-c79a26a06af7.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42

### Environment

System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.5 - ~/.nvm/versions/node/v12.22.5/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v12.22.5/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v12.22.5/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Steps to reproduce:
- Follow steps for monorepo setup with EAS managed build as per https://github.com/byCedric/eas-monorepo-example
- Add `expo-updates` as a dependancy
- Error is then produced when `eas build` is run

**Comment by byCedric** [comment]
Hi @thomas-coldwell! Did you run the `eas build` command in the app directory? Another possible option I can think of is the `metro.config.js` in your app, not having a link to `__dirname` (as [listed here](https://github.com/byCedric/eas-monorepo-example/blob/main/apps/managed/metro.config.js#L3)). It would be helpful if you can create a repo with your current setup, with that we would be able to do some tests.

Hope this helps!

**Comment by pycraft114** [comment]
how is it solved?
