### ISSUE TITLE
Expo-AV: Android video dimensions are always a square, iOS works fine

### ISSUE THREAD

**Issue by jvgeee** [expo/expo#14677]
### Summary

When using expo-av's Video component on IOS, the video's width and height are calculated and displayed correctly.

When using it on Android, the video's height calculates correctly, but the width gets set to the height.

This is particularly bad when using `resizeMode="contain"`; the video tries to display a square and is completely warped.

On IOS: `width: 607, height: 1080` (correct!)
On Android: `width: 1080, height: 1080`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.4

### Environment

Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.5/bin/yarn
      npm: 7.17.0 - ~/.nvm/versions/node/v14.15.5/bin/npm
      Watchman: 2021.10.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.71 => 0.12.82
      expo: ^42.0.1 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: ^17.0.2 => 17.0.2
      react-native: github:expo/react-native#sdk-42.0.0 => 0.63.2
      react-native-web: ^0.16.3 => 0.16.5
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

This is a similar issue to https://github.com/expo/expo/issues/12839, but I believe it's something to do with the calculation of the video's dimensions during `onReadyForDisplay`. See this snack (I've adapted @mtroskot's)

Here's a demo: https://snack.expo.dev/@jvggoodwork/android-video-size-wrong

The relevant code:

```

export default function App() {
  const [dimensions, setDimensions] = useState({width: 0, height: 0})

  return (
    <View style={styles.container}>
       <View>
          <Text>Width: {dimensions.width}</Text>
          <Text>Height: {dimensions.height}</Text>
       </View>
      <Video
         source={video}
         shouldPlay={false}
         resizeMode={"cover"}
         style={{ flex: 1 }}
         onReadyForDisplay={({naturalSize}) => {
            console.log(naturalSize)
            // On android this will be a square
            // on IOS the dimensions are correct
            const {width, height} = naturalSize
            setDimensions({width, height})
         }}
       />
    </View>
  );
}
```

**Comment by jvgeee** [comment]
For anyone else facing this issue, the only solution I've found is to hard-code (somewhere) the width and height of the video for use on Android. In my case, I needed to use `resizeMode="stretch"` for it to display correctly; if I used `resizeMode="contain"` it didn't work properly and came out squashed.

I'm also manually altering the size of the video (to replicate "contain") by getting the screen width, e.g.

```
import {Dimensions, ViewStyle, View} from 'react-native'
import {Video, ResizeMode} from 'expo-av'

const App = ({videoProps) => {
 // Get screen width
 const {width: screenWidth} = Dimensions.get("window")

 // calculate ratio of screen to video width
  const delta = screenWidth / width

  const VIDEO: ViewStyle = {
    // Set the width and height to fit in the screen
    width: width * delta,
    height: height * delta,
    flex: 0,
  }

  return (
    <View style={styles}>
      <Video
        {...videoProps}
        style={VIDEO}
        resizeMode={ResizeMode.STRETCH}
      />
```

**Comment by TheNerdGuyLulu** [comment]
This is still an issue!

**Comment by kirgy** [comment]
I'm still seeing this issue. All videos on Android have incorrect dimensions.

**Comment by kirgy** [comment]
This provided a "cover" effect in my android.

```
const backgroundVideo = require("../myVideo.mp4");

// the known dimensions of the video file
const VIDEO_DIMENSIONS = { width: 607, height: 1080 };

export default function OnboardingScreen({
  navigation,
}: RootStackScreenProps<"Onboarding">) {
  const { width: screenWidth, height: screenHeight } = useWindowDimensions();

  const videoStyle: ViewStyle = useMemo(() => {
    let delta = 1;

    if (VIDEO_DIMENSIONS.width < screenWidth) {
      delta = delta * (screenWidth / VIDEO_DIMENSIONS.width);
    } else {
      delta = delta * (VIDEO_DIMENSIONS.height / screenHeight);
    }

    return {
      width: VIDEO_DIMENSIONS.width * delta,
      height: VIDEO_DIMENSIONS.height * delta,
    };
  }, [screenWidth, screenHeight]);

  return (
    <Flex position="relative" h="100%" w="100%">
      <Flex
        height="100%"
        width="100%"
        alignItems="center"
        justifyContent="center"
      >
        <Video
          style={{
            ...videoStyle,
          }}
          source={backgroundVideo}
          resizeMode={ResizeMode.STRETCH}
        />
      </Flex>
    </Flex>
  );
}

```

**Comment by TheRealMikeD** [comment]
Still broken. 
expo 46.0.9
expo-av 12.0.4
