### ISSUE TITLE
Expo.Video: playAsync/pauseAsync lag (iOS)

### ISSUE THREAD

**Issue by Elijen** [expo/expo#1467]
There is very long lag produced when video is paused/resumed using playAsync/pauseAsync methods. On video pause, it takes almost 2 seconds until `onPlaybackStatusUpdate` is triggered with new playbackStatus. When video is resumed it fast forwards 1 or 2 seconds before resuming normal play.

Using native controls does not produce the same lag. 

https://snack.expo.io/S1h4l6xuM

**Comment by mikeynova** [comment]
Any update with this? I'm experiencing this issue as well.

**Comment by riwu** [comment]
> onPlaybackStatusUpdate is triggered 2 seconds after pausing — the callback (programmatically) isn't supposed to be called right after changing the playback state

The [doc below](https://docs.expo.io/versions/latest/sdk/av.html#playbackobjectsetonplaybackstatusupdateonplaybackstatusupdatesets-a-function-to-be-called-regularly) will need to be updated then:
>`onPlaybackStatusUpdate` will be called whenever a call to the API for this `playbackObject` completes (such as `setStatusAsync()`, `getStatusAsync()`, or `unloadAsync()`)
