### ISSUE TITLE
Errors while building for iOS

### ISSUE THREAD

**Issue by clementino36** [expo/expo#1468]
### Environment

`exp diagnostics` 

Environment:
  OS: Windows 10
  Node: 8.1.2
  Yarn: 1.2.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  expo: ^24.0.0 => 24.0.2
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/clementino36-1288ae7a-a9b8-4612-9613-def97f2da95f.tar.gz

### Steps to Reproduce
` exp build:ios -c`

![capt](https://user-images.githubusercontent.com/6041593/36662090-94704aa6-1add-11e8-8623-27c4df689c38.PNG)

I'm not sure where to run `EXP_DEBUG=true`, i've tried `EXP_DEBUG=true exp build:ios -c` but it gives me `'EXP_DEBUG' is not recognized as an internal or external command`.
I've also tried putting it in my `.env.production` file but it doesn't log anything.

Here's my app.json:
``` javascript
{
  "expo": {
    "sdkVersion": "24.0.0",
    "privacy": "unlisted",
    "name": "Aidoo Technician",
    "icon": "./src/assets/commons/boilerplate_icon.png",
    "splash": {
      "image": "./src/assets/commons/splashscreen.png",
      "resizeMode": "cover"
    },
    "orientation": "portrait",
    "version": "1.0.0",
    "slug": "aidoo-technician-prod",
    "ios": {
      "bundleIdentifier": "com.emixis.aidooTechnician",
      "supportsTablet": true
    },
    "android": {
      "package": "com.emixis.aidooTechnician",
      "versionCode": 1,
      "permissions": [
        "CAMERA"
      ]
    }
  }
}
```

My exp version is 49.2.2.
Thanks!

**Comment by quinlanj** [comment]
hi @clementino36 , can you try with `EXPO_DEBUG=true`, so run `EXPO_DEBUG=true exp build:ios -c` and tell us what the debugging logs were?

**Comment by clementino36** [comment]
Hi, as I said, I'm not sure where to run `EXP_DEBUG=true`, i've tried `EXP_DEBUG=true exp build:ios -c` but it gives me `'EXP_DEBUG' is not recognized as an internal or external command, operable program or batch file.`

**Comment by esamelson** [comment]
Hi @clementino36 - as quin suggested, can you try with `EXPO_DEBUG` rather than `EXP_DEBUG`? :)

For windows, I believe you can run:
```set EXPO_DEBUG=true
exp build:ios```

**Comment by fxfactorial** [comment]
@clementino36 To set an environment variable in powershell, you do `$env:EXPO_DEBUG='true'`. 

`getAddrInfo: Name or service Unknown` makes it sound like a network problem. Do you have special network configuration happening or on a strange wifi network? I would try with other networks.

**Comment by clementino36** [comment]
@esamelson my bad for the typo.
Here's what i get with EXPO_DEBUG=true
```
[exp] Running: bash.exe -c PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /mnt/c/Users/Student/AppData/Roaming/npm/node_modules/exp/node_modules/@expo/traveling-fastlane-linux/traveling-fastlane-1.4.5-linux-x86_64/validate_apple_credentials "c.debellefroid@emixis.com ***********"
getaddrinfo: Name or service not known
getaddrinfo: Name or service not known
getaddrinfo: Name or service not known
getaddrinfo: Name or service not known                                                                                                                                                        getaddrinfo: Name or service not known
                                                                                                                                                                                              [exp] Error while gathering & validating credentials
[exp] {}
[exp] Reason:Unknown reason, raw:"Could not receive latest API key from iTunes Connect, this might be a server issue."
[exp] Error: Reason:Unknown reason, raw:"Could not receive latest API key from iTunes Connect, this might be a server issue."
    at Object._callee4$ (C:\Users\Edgar\universe\dev\exp\src\commands\build\auth.js:127:11)
    at tryCatch (C:\Users\Student\AppData\Roaming\npm\node_modules\exp\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\Student\AppData\Roaming\npm\node_modules\exp\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Student\AppData\Roaming\npm\node_modules\exp\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\Student\AppData\Roaming\npm\node_modules\exp\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Student\AppData\Roaming\npm\node_modules\exp\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

@fxfactorial i've tried on two different wifi networks, no success. Plus i forgot to mention that i was able to build before i upgraded to exp version 49. I went from 45 to 49.

**Comment by fxfactorial** [comment]
Going from 45 to 49 was a jump in how authentication is done, now it is done via ruby code on your local machine and that ruby code is complaining. 

Googling that message gives these results https://www.google.com/search?q=Could+not+receive+latest+API+key+from+iTunes+Connect%2C+this+might+be+a+server+issue.&ie=utf-8&oe=utf-8

Which makes it sound like something is off with the network or the ruby code itself. 

Are you using anything special in networking, proxy or something configured odd? 

Do you have fastlane installed on the windows machine? Or the WSL layer?

**Comment by clementino36** [comment]
I haven't configured anything in particular on my network, can't tell much more about that i'm afraid..
Fastlane is not installed on the windows machine and I don't know what the WSL layer is so I guess not.

**Comment by fxfactorial** [comment]
Is this a machine that you're allowed to use exclusively? It might have been the case that something at one time asked for permission to use internet and then was denied and hence this process can't get internet. 

Can you try 

```
bash.exe -c 'dig google.com'
```

**Comment by clementino36** [comment]
Not sure what you mean by exclusively ? 
`bash.exe -c 'dig google.com'` gives me this:

```
socket.c:1915: internal_send: 109.88.203.3#53: Invalid argument
socket.c:1915: internal_send: 62.197.111.140#53: Invalid argument
socket.c:1915: internal_send: 2a02:2788:fff0:7::3#53: Invalid argument
socket.c:1915: internal_send: 109.88.203.3#53: Invalid argument
socket.c:1915: internal_send: 62.197.111.140#53: Invalid argument
socket.c:1915: internal_send: 2a02:2788:fff0:7::3#53: Invalid argument
socket.c:1915: internal_send: 109.88.203.3#53: Invalid argument
socket.c:1915: internal_send: 62.197.111.140#53: Invalid argument
socket.c:1915: internal_send: 2a02:2788:fff0:7::3#53: Invalid argument

; <<>> DiG 9.9.5-3ubuntu0.10-Ubuntu <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by fxfactorial** [comment]
I mean do you have to share the computer with other users? 

Okay so it looks like something is messed up with your WSL installation. 

I recommend you try deleting and reinstalling the Ubuntu app via the windows app store (or whatever Linux distribution you had installed via the windows app store). Once you have that working, then exp build:ios should work.

**Comment by clementino36** [comment]
No I don't have to share my computer.
Thanks for your time, I will try that tomorrow and tell you what right after.

**Comment by clementino36** [comment]
The reason for the `dig` command to fail was my Firewall. I disabled it and it worked fine, i'm now able to run `exp build:ios` smoothly.
Thanks again :)

**Comment by rishiankush** [comment]
@esamelson where do I need to set 
EXPO_DEBUG=true

**Comment by esamelson** [comment]
Hi @rishiankush - you need to set it in your terminal window, e.g. `EXPO_DEBUG=true exp build:ios` on mac/linux or
```
set EXPO_DEBUG=true
exp build:ios
```
for windows.

However, this won't actually change the behavior of exp at all, it will just output a bit more information for debugging purposes. If you're having trouble, it's best to [post on our forums](https://forums.expo.io) or [open a new issue](https://github.com/expo/expo/issues).
