### ISSUE TITLE
Camera permission only requested on first load on ios

### ISSUE THREAD

**Issue by yehudahkay** [expo/expo#1470]
Thanks for the great framework!

On ios the camera permission is only requested on the first load, but after that the camera permission is not requested again. const {status} = await Permissions.askAsync(Permissions.CAMERA)

Example: Open https://expo.io/@community/camerja in expo by typing in the url, not by using qr. Deny the permission. Then try opening again. No permission is requested.

The same behavior is exhibited testing an app with testflight

It seems also that the ios expo client app has the same issue, if you deny permissions to the qr code you can't request them again

Seems like this is perhaps an ios limitation? https://stackoverflow.com/questions/29980832/request-permissions-again-after-user-denies-location-services . Perhaps add to docs?

**Comment by aalices** [comment]
Hello @yehudahkay  - that's right - it is an iOS limitation and every app will behave like this and it is not up to Expo. The only way to allow the permission after denying it before is to go to Settings and toggle it manually.

**Comment by yehudahkay** [comment]
On Android much more convenient! I added a note to users. My only comment is to add that to the expo permission docs. Thanks for all!
