### ISSUE TITLE
[exp] Cannot start new build, as there is a build in progress

### ISSUE THREAD

**Issue by laijnaloo** [expo/expo#1471]
My build has been stuck in this state for a couple of days now and I wonder if there is any way to solve it? Seems like it is something that the Expo internal team have to do, so I wonder if it is possible that you can kill it?

Here is the build-url that I got from expo: https://expo.io/builds/0ed008d6-f759-44a3-bf75-51c48458e339 , however it is currently only returning 'internal server error', does anyone know what that is and how to solve it?

**Comment by quinlanj** [comment]
hi @laijnaloo , you need to be logged in as the user who triggered the build in order to see that page. 

If you want to cancel your build, go to the build dashboard and click `cancel` under your build (ie) https://expo.io/@notbrent/growler-prowler/builds

**Comment by quinlanj** [comment]
afaik, this isnt a bug, so im going to go ahead and close this issue. if you need any additional help, please post on forums.expo.io . Thanks!
