### ISSUE TITLE
new FirebaseRecaptchaVerifier(token) throws undefined error

### ISSUE THREAD

**Issue by dqii** [expo/expo#14716]
### Summary

When I call
```
new FirebaseRecaptchaVerifier(token);
```

Sometimes I get a 
```
verifier._reset is not a function. (In 'verifier._reset()', 'verifier._reset' is undefined)
at node_modules/@firebase/auth/dist/esm2017/index-80a96710.js:6288:52 in _generateEventId
```

Afaik, it happens sporadically. It will not happen 10 times in a row, then it will happen 10 times in a row, and I'm not sure what fixes it.

I added ```_reset() {}``` to build/FirebaseRecaptchaVerifier.js as a patch.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.4 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.14 - /usr/local/bin/npm
      Watchman: 2021.09.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0-beta.3 => 43.0.0-beta.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Wanted to share in case it helped anyone else

**Comment by byCedric** [comment]
Hi @dqii! Linking this to #14780, it seems like we are missing some Firebase methods with the latest version. Unfortunately, this is not something we can fix, Firebase has to expose it. That's why I created an issue on their repo (linked in #14780). 

After getting access to the methods, we can work on improving the `expo-firebase-recaptcha` package!

**Comment by morganlaneap** [comment]
Google have updated firebase to export these methods now. Will this issue be looked at soon?

**Comment by mattThousand** [comment]
Having the same issue - would love it if this could be looked at soon 🙇‍♂️

**Comment by brettpoulin** [comment]
I also have a project waiting on this ... +1
Thanks for the great work!

**Comment by mattThousand** [comment]
Gentle nudge on this issue 🤗 🙏

**Comment by leohck** [comment]
Same problem here,
Thanks for the initiative and project, please fix this bug  if you can.

**Comment by mattThousand** [comment]
looks like the fix has been merged here (thank you!): https://github.com/expo/expo/pull/15102

could someone push a version to npm (`expo-firebase-recaptcha` package) so that we can pull it down from `@next`? 🙇‍♂️

**Comment by mattThousand** [comment]
^^ 🙏

**Comment by dqii** [comment]
I think this ended up getting pushed: https://github.com/expo/expo/pull/15102
