### ISSUE TITLE
expo upgrade/install jest ts-jest should install version 26

### ISSUE THREAD

**Issue by trajano** [expo/expo#14727]
### Summary

When doing `expo install jest/tsjest` or `expo upgrade` , it does not lock the versions of `ts-jest` and `jest` to 26 which is what `jest-expo` requires.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.12.1 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 12.18.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      Yarn: 1.22.10 - ~\scoop\apps\nvm\current\nodejs\nodejs\yarn.CMD
      npm: 6.14.4 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ^42.0.0 => 42.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

`expo install jest`

You'll get `jest@27` which is not compatible with `jest-expo`

**Comment by Simek** [comment]
Hi @trajano, are you sure about that? I can see in the `jest-watch-typeahead` source for `0.6.2` in here:
* https://github.com/jest-community/jest-watch-typeahead/blob/v0.6.2/package.json#L60

and in Warn message you have posted:

> ... jest-watch-typeahead@0.6.2 requires a peer of **jest@^26.0.0** ...

that the resolved version of `jest-watch-typeahead` requires Jest 26 as a peer dependency.

Also, from quick skim over the [Changelog](https://github.com/jest-community/jest-watch-typeahead/blob/main/CHANGELOG.md), it looks like Jest 27 support has been added in later `0.6.4` release.

**Comment by trajano** [comment]
Weird I notice the files too.  It's weird that I see that message

│   },
  59   │   "peerDependencies": {
  60   │     "jest": "^26.0.0"
  61   │   },

**Comment by trajano** [comment]
Ah you're right, I found that my `jest` is 27.x.  Maybe `expo install jest` should install `26`
