### ISSUE TITLE
`expo-secure-store@11.0.1` exception with Expo SDK 43.0.0-beta.3

### ISSUE THREAD

**Issue by thedoublejay** [expo/expo#14722]
### Summary

I'm testing our project with Expo SDK 43 Beta. I tested it on a clean expo go run. Everything seems to work well. The problem lies when it's running on a device with existing data store via `expo-secure-store`. The previous version of `expo-secure-store` is `10.2.0`. 

I tried building the APK via EAS and installing it on my device. When I opened the device, the app is not functioning well. I tried to view the logs, I found an exception:

`8327  8525 W ExpoSecureStore: javax.crypto.AEADBadTagException` 
`8327  8525 W ExpoSecureStore:       at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)`
`8327  8525 W ExpoSecureStore:       at javax.crypto.Cipher.doFinal(Cipher.java:2055)`
`8327  8524 E ReactNativeJS: [Error: Could not decrypt the item in SecureStore]`

I have attached the exception log for reference.
[2.txt](https://github.com/expo/expo/files/7336815/2.txt)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 4.12.1 environment info:
System:
OS: Windows 10 10.0.22000
Binaries:
Node: 16.11.1 - C:\Program Files\nodejs\node.EXE
npm: 7.16.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 2020.3.0.0 AI-203.7717.56.2031.7678000
npmPackages:
expo: next => 43.0.0-beta.3
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2
react-native-web: 0.17.1 => 0.17.1
Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Attached APK https://expo.io/artifacts/eas/kT5XfyMTRRfjD2rZDTcorJ.apk

**Comment by wschurman** [comment]
Looking into this now.

**Comment by thedoublejay** [comment]
@wschurman Yup, working fine now with Expo SDK 43.0.0-beta.4. I have added the SDK version on `app.json`. Not sure if it helps with the secure-store issue but it's working fine now. Thanks
