### ISSUE TITLE
`shouldAutoExchangeCode` has no effect when using Google.useAuthRequest

### ISSUE THREAD

**Issue by glocore** [expo/expo#14726]
### Summary

Setting the `shouldAutoExchangeCode` config option to `false` in `Google.useAuthRequest` returns an access token instead of a server code.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.3.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /var/folders/nl/7nhj_tj55hb95890154kmmh00000gn/T/yarn--1634124260671-0.15493386789194696/node
      Yarn: 1.22.10 - /var/folders/nl/7nhj_tj55hb95890154kmmh00000gn/T/yarn--1634124260671-0.15493386789194696/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.3.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Create a new Google Client ID by following the steps at https://docs.expo.dev/guides/authentication/#development-in-the-expo-go-app
2. Use the following code to trigger the auth flow:
```jsx
const [request, response, promptAsync] = Google.useAuthRequest({
  expoClientId: '<GOOGLE_GUID>.apps.googleusercontent.com',
  shouldAutoExchangeCode: false,
});

React.useEffect(() => {
  if (response?.type === 'success') {
    const { authentication } = response;
    console.log({ authentication });
  }
}, [response]);

// jsx
<Button onPress={() => promptAsync()} title="Google" />
```
3. Observe the following `authentication` object after login:
```js
{
  "authentication": TokenResponse {
    "accessToken": "...",
    "expiresIn": "3598",
    "idToken": undefined,
    "issuedAt": 1634123306,
    "refreshToken": undefined,
    "scope": "email profile https://www.googleapis.com/auth/userinfo.email openid https://www.googleapis.com/auth/userinfo.profile",
    "state": "sBVfR3HBwQ",
    "tokenType": "Bearer",
  },
}
```

**Comment by allandiego** [comment]
if you set responseType: 'code' it returns code to exchange for access token
