### ISSUE TITLE
Push Notifications not vibrating more than twice

### ISSUE THREAD

**Issue by FelipeACP** [expo/expo#14736]
### Summary

Income Push Notifications won't vibrate more than twice regardless of the length of the array supplied to `vibrationPattern`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.11.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4.4.3 => 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- Create a custom channel and set `vibrationPattern` to an array longer than 4 (eg: [0, 500, 250, 500, 250, 500, 250])
- Send a push notification with the previous channelId.
- Device vibrates only twice.

Sample configuration
```
Notifications.setNotificationChannelAsync("evacuation", {
      name: "leave immediately",
      description: "Triggered when emergency requires evacuation warnings",
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: Array(8).fill(250),
      sound: "default",
      lightColor: "#FF231F7C",
      enableVibrate: true,
    })
```
Or clone the [Example Repo](https://github.com/FelipeACP/vibration_bug_example)

**Comment by cruzach** [comment]
when you [`getNotificationChannelAsync`](https://docs.expo.dev/versions/latest/sdk/notifications/#getnotificationchannelasyncidentifier-string-promisenotificationchannel--null
), does it show the correct vibration pattern?

**Comment by FelipeACP** [comment]
`vibrationPattern`  was set to Array(31).fill(250) and returned:

```
"vibrationPattern": Array [
    0,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
    500,
  ],
```

Probably some old value cached that was not refreshed, but it didn't vibrate more than twice anyway.
