### ISSUE TITLE
Issue with firebase 9 and sdk 43

### ISSUE THREAD

**Issue by ottob** [expo/expo#14734]
### Summary

When I tried to upgrade my project from sdk 42 to 43 and firebase js from 8.10 to 9.1.2 access to firestore stopped working and I get an error:
> @firebase/firestore:, Firestore (9.1.2): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.

Using a normal web project accessing the same firestore instance works fine (same network, same firebase js version).

Other people seems to have the same problem: https://github.com/firebase/firebase-js-sdk/issues/1674#issuecomment-939510410

Workaround is using this option:
```ts
const firestore = initializeFirestore(firebaseApp, {
   experimentalForceLongPolling: true,
})
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 20200920.192359.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0-beta.3 => 43.0.0-beta.3 
      react-native: 0.64.2 => 0.64.2 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. EXPO_BETA=1 expo init firestorebug
2. expo install firebase@next

Add some code to try to access firestore: https://github.com/ottob/firestorebug

https://github.com/ottob/firestorebug/blob/81b5b7bea1118731e7624b149702c9aa4503c748/App.tsx#L13-L18

**Comment by ottob** [comment]
It seems like there exists a less intrusive workaround `useFetchStreams: false` that reverts to how it worked in firebase 8:
https://github.com/firebase/firebase-js-sdk/issues/1674#issuecomment-944041831

**Comment by sampajano** [comment]
> Ah, so if they are using fetch streams, that might be the exact issue. Although fetch is available in React Native, it might not fully support streams: [facebook/react-native#27741](https://github.com/facebook/react-native/issues/27741).

Yes! Firebase requires streaming and that's probably why it breaks with `useFetchStreams: true` which was turned on by default with Firebase SDK V9.

A recent PR was made to revert back to using XHR for React Native:
https://github.com/firebase/firebase-js-sdk/pull/5643

After that hopefully no workaround would be necessary anymore :)

**Comment by titocosta** [comment]
This issue is not solved yet for me, on iOS simulator, android simulator, android phone, both local emulators and firebase.
I am using firebase version 9 and expo, both most recent versions as of May 4, 2022.
The `experimentalForceLongPolling: true` and the `useFetchStreams: true` workarounds together and independently don't work for me.

**Comment by artvichi** [comment]
still have an issue on android (ios and web work for us)
