### ISSUE TITLE
Audio will be silently on playAsync() immediately after  stopAsync()

### ISSUE THREAD

**Issue by watanabeyu** [expo/expo#1473]
### Environment

in iOS target.

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.2.1
  Yarn: 0.27.5
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

### Steps to Reproduce

1. Audio.setAudioModeAsync() on componentDidMount()
```js
Audio.setAudioModeAsync({
  allowsRecordingIOS: false,
  interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
  playsInSilentModeIOS: true,
  shouldDuckAndroid: true,
  interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
});
```
2. Press play button
  * if not loaded audio, load from uri `playbackObject.loadAsync({uri:xxx})`
  * play audio `playbackObject.playAsync()`
3. One more press the play button
  * stop audio `playbackObject.stopAsync()`
  * play audio `playbackObject.playAsync()`

### Expected Behavior

Sound also appears in silent mode

### Actual Behavior

It is silently.

But, below is ok.
1. Audio.setAudioModeAsync() on componentDidMount()
2. Press play button
3. Press stop button
4. Press play button

or 

1. Audio.setAudioModeAsync() on componentDidMount()
2. Press play button1
3. Press play button2

### Reproducible Demo

https://snack.expo.io/SJdn1jzuM

**Comment by esamelson** [comment]
Hey @watanabeyu - thanks for taking the time to create this demo! Unfortunately I'm not able to reproduce the problem :( Here are the steps I'm taking - could you tell me if I'm doing something wrong?

1. Turn sound off on iPhone
2. Open snack and press "play music 1", hear music
3. Press "stop music", music stops
4. Press either "play music 1" or "play music 2"
5. Hear music again, works fine (??)

If these are the steps you're taking as well, and it doesn't work for you, could you let us know what type of device you're testing on?

Thanks very much!

cc @sjchmiela

**Comment by watanabeyu** [comment]
Hi @esamelson - thanks for reply.

Please again below step.
I want to sound appears in silent mode, but sound not appears in step4.
1. Turn sound on iPhone, but silent mode on.
2. Open snack
3. Press music1   <-- sound appears
4. Press again music1   <-- sound not appears

**my ios environment**
* iphone8
* iOS : 11.0.3
* expo client : latest release(2.3.0)

Thank you and best regards,

**Comment by terribleben** [comment]
Hey there, can you try calling `setPositionMillis(0)` before the second call to `playAsync`, or alternatively using the `replayAsync` method, and see if one of those methods solves your issue?

**Comment by watanabeyu** [comment]
Hi @terribleben ,I try `setPositionAsync(0)` before `playAsync`, sounds appear!
Thanks!
```js
await this.playbackObject.stopAsync();
await this.playbackObject.setPositionAsync(0)
await this.playbackObject.playAsync();
```
But `stopAsync()` should be equivalent to `setStatusAsync({ shouldPlay: false, positionMillis: 0 })`,  why needs `setPositionAsync(0)` ?

**Comment by sjchmiela** [comment]
Hi @watanabeyu! Frankly speaking, it seems strange for `playAsync` to require a separate `setPositionAsync` after `stopAsync`.

In my opinion this issue may be connected to https://github.com/expo/expo/issues/1426 — when all sounds of the experience seize to play, the audio category is programmed to be reset not to play in silent mode (obviously a bug).

Could you please try to swap out the `setPositionAsync(0)` and replace it with another call to `setAudioModeAsync`? Or could you check if this bug also occurs when the silent switch is set to _Ring_? (If the sounds play all right, this would mean that your bug is certainly occurring due to the audio mode reset.)

**Comment by watanabeyu** [comment]
@sjchmiela Thanks to reply.
When `setAudioModeAsync`?  
I set `Audio.setAudioModeAsync()` when componentDidMount, is correct?


> Could you please try to swap out the setPositionAsync(0) and replace it with another call to setAudioModeAsync?

I created a new snack, that set `Audio.setAudioModeAsync()` after `this.playbackObject.stopAsync()`.
https://snack.expo.io/B1vqWdDYG
```js
await this.playbackObject.stopAsync();
await Audio.setAudioModeAsync({
  allowsRecordingIOS: false,
  interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
  playsInSilentModeIOS: true,
  shouldDuckAndroid: true,
  interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
});
await this.playbackObject.playAsync();
```
This will appear sounds.


> Or could you check if this bug also occurs when the silent switch is set to Ring?

No.
Sounds will appear, even if the silent switch is set to Ring, when below.
```js
await this.playbackObject.stopAsync();
await this.playbackObject.playAsync();
```

**Comment by sjchmiela** [comment]
Thank you for trying all that!

From what you wrote I suspect the problem occurs due to resetting of the Audio Mode. Working on a fix for that!

**Comment by watanabeyu** [comment]
@sjchmiela Thanks!!!
Best Regards!
