### ISSUE TITLE
Reanimated crashes iOS app on Expo SDK 43

### ISSUE THREAD

**Issue by thomas-coldwell** [expo/expo#14746]
### Summary

Just created a fresh (managed workflow) project with Expo SDK 43 and installed reanimated using `expo install react-native-reanimated`, followed the instructions to add it as a plugin in the `babel.config.js` file, built a standalone version using `eas build` which builds without any issues, installed the app on my iPad (iOS 14.4.2) and it crashes on launch. Did this as a test as I was having the issue in a much larger project and Sentry caught the error as `If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation`.

Same project builds and launches successfully on Android

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.5 - ~/.nvm/versions/node/v12.22.5/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v12.22.5/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v12.22.5/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0-beta.3 => 43.0.0-beta.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Minimal reproducible demo of this occurring (blank app with just a single `useSharedValue` hook): https://github.com/thomas-coldwell/reanimated-sdk-43.git

- Clone project
- `yarn`
- `eas device:create` to install profile for iOS device
- `eas build --profile development --platform ios`
- Install build and upon launch app crashes

**Comment by shoes22** [comment]
I am experiencing this same issue with SDK 43, and reanimated 2.2.2, bare workflow and EAS build on iOS. 

Same error as you, `If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation`.

Android runs fine.

**Comment by cbarceloc** [comment]
I still face that problem using the release version in ios (in dedug mode everything works fine), any fix?

**Comment by Kudo** [comment]
please share us a repo of [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). it's hard to us to help an issue that we cannot reproduce in house.

**Comment by cbarceloc** [comment]
ah I had to upgrade expo-updates from 0.10.0 to 0.10.15. Now it works. Thanks!

**Comment by enesozturk** [comment]
I was also having this issue in **v43** and just upgraded to **v44 beta**, now it works! Thanks.
