### ISSUE TITLE
Custom action in intent filter

### ISSUE THREAD

**Issue by superyarik** [expo/expo#14740]
### Summary

using [docs](https://docs.expo.dev/guides/linking/) trying to create following intent filter:

```
<intent-filter>
    <data android:scheme="lifepaymyappid" />
    <action android:name="com.lifepay.pay" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
</intent-filter>
```

in app.json android section create this:
```
"intentFilters": [
  {
    "action": "com.lifepay.pay",
    "data": [
      {
        "scheme": "lifepaymyappid"
      }
    ],
    "category": [
      "BROWSABLE",
      "DEFAULT"
    ]
  }
],
```

but in AndroidManifest.xml file receive 
```
<intent-filter>
  <data android:scheme="lifepaymyappid"/>
  <action android:name="android.intent.action.com.lifepay.pay"/>
  <category android:name="android.intent.category.BROWSABLE"/>
  <category android:name="android.intent.category.DEFAULT"/>
</intent-filter>
```

looks like builder not allow to add my custom action, so return it joined with hardcoded string?
`<action android:name="android.intent.action.com.lifepay.pay"/>`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 14.18.0 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.10.04.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-navigation: 4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

problem described above

**Comment by moustaouiSalaheddine** [comment]
try this
```

"intentFilters": [
  {
    "action": "VIEW",
    "autoVerify": true,
    "data": [
      {
              "scheme": "https",
              "host": "example.com",
              "pathPrefix": "/"
      }
    ],
    "category": [
      "BROWSABLE",
      "DEFAULT"
    ]
  }
],
```
The value of action is only view
Action: android.intent.action.VIEW
https://developer.android.com/training/app-links/verify-site-associations#auto-verification

**Comment by superyarik** [comment]
this should be reopened
