### ISSUE TITLE
Error: "Geocoder is not running" after NavigationActions.reset

### ISSUE THREAD

**Issue by edgareler** [expo/expo#1474]
### Environment

Ubuntu running Expo XDE, and the issue happens only on Android clients. The Expo SDK v25 is the first which returned an error, but the previous SDKs just got stuck on the `Location.reverseGeocodeAsync` call (within the conditions described below).

### Steps to Reproduce

On the main screen of my app I get the user position and call the `Location.reverseGeocodeAsync` to get his address. The code is basically this:

```javascript
let position = await Location.getCurrentPositionAsync({
  enableHighAccuracy: true,
});

let location = {
  latitude: position.coords.latitude,
  longitude: position.coords.longitude
};

try {
  let res = await Location.reverseGeocodeAsync(location);
  console.log('Address: ', res[0]);
} catch (err) {
  console.error('Error when geocoding: ', err);
}
```
This code works properly when the App opens. As I use `StackNavigator` from React Navigation, the next screen of my app is accessed by `this.props.navigation.navigate('ScreenName')`. At this next screen, if I run the `Location.reverseGeocodeAsync` the code still works properly.

The issue happens after the user finish the process on this screen and I call `StackNavigator` to return to Home screen:
```javascript
backHome() {
  const resetAction = NavigationActions.reset({
    index: 0,
    actions: [
      NavigationActions.navigate({ routeName: 'Home'})
    ]
  });
  this.props.navigation.dispatch(resetAction);
}
```
As soon as the Home screen opens and tries to run `Location.reverseGeocodeAsync`, the error `E_CANNOT_GEOCODE` is thrown, as described below.

### Expected Behavior

The `Location.reverseGeocodeAsync` should always call the native reverseGeocode on Android.

### Actual Behavior

For some reason, the Geocoder is being paused, and the "Geocoder is not running." is bein returned. The error happens on this line: https://github.com/expo/expo/blob/master/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/LocationModule.java#L423
If the user returns to the Home screen with the Back button (instead of the `NavigationActions.reset`) the Geocoder is not paused.

![Screenshot of the error](https://edgar.systems/Screenshot_20180227-114101.jpg)

**Comment by esamelson** [comment]
Hey @edgareler - thanks for reporting this bug. Would you be able to provide us with a runnable example we can use to repro & debug the issue? A [snack](https://snack.expo.io) might be the easiest way to do this. Thanks :)

**Comment by edgareler** [comment]
@esamelson check this: https://snack.expo.io/@edgareler/reverse-geocoder-issue

It's not "perfectly" replicated, but try to get the address, navigate to Screen 2, get the address again, navigate to Home, then open another app or go to the Home Screen of your device and return to the app, you'll then see the Geocoder error.

**Comment by machester4** [comment]
I have the same error and I do not use navigation. There are times when it works well and other times it does not work. I get a warn with the same message "`Geocoder is not running`" I think the problem is with the google key. If I can know the exact cause I will comment here.

**Comment by machester4** [comment]
The problem is when the application goes into the background, when returning to the first plane Geocoder will not work. you can reproduce this error using the snack on a physical device.

**Comment by robertobrogi** [comment]
yep i have the same problem.... i use expo 25.0.0... there is any solution?

thanks

**Comment by edgareler** [comment]
@esamelson can you please remove the label `status: needs more info`? Because, as you can see above, this is a confirmed issue.

Thanks.

**Comment by esamelson** [comment]
Hi, yes and just wanted to acknowledge that we've seen this and understand it's a bug. I can't promise any timeframe for a fix, as we're a small team and this is a busy time for us, but we hope to get to it soon. Thanks everyone for the information.

**Comment by watadarkstar** [comment]
@aalices @esamelson did this ever get fixed?

**Comment by esamelson** [comment]
@watadarkstar yes, this was fixed at the time the issue was closed, in April (SDK 27). Are you still seeing the same issue?

**Comment by watadarkstar** [comment]
@esamelson I'm on SDK 26 so maybe thats why

**Comment by mfelix5** [comment]
hi all, I am getting the "Geocoder is not running" error on Android when attempting to reverse geocode. Similar to this issues outlined above, geocoding works the first time you try it in the app after granting permissions. After that, every attempt results in the error. I am using SDK 32. Any insight would be appreciated.

async componentDidMount() {
   let status = await this.askForPermissions();
   if (status === "granted") {
     try {
       let location = await Location.getCurrentPositionAsync({
         enableHighAccuracy: false,
         maximumAge: 300000
       });
       let address = await this.getAddress(
         location.coords.latitude,
         location.coords.longitude
       );
       this.setState({ (deleted for brevity) });
     } catch (e) {
       (deleted for brevity)
     }
   } else {
     (deleted for brevity)
   }
 }

 getAddress = async (lat, lon) => {
   try {
     let address = await Location.reverseGeocodeAsync({
       latitude: lat,
       longitude: lon
     });
     return address;
   } catch(e) {
     console.log("error:", e)
   };
 }

**Comment by codGmer** [comment]
i've got the same issue with SDK 32. Also with navigation.

**Comment by brentvatne** [comment]
@codGmer - if you can create a reproducible example (tips here: https://stackoverflow.com/help/mcve) and create a new issue we can help!
