### ISSUE TITLE
Asynchronous functions not resolving, Google Login

### ISSUE THREAD

**Issue by ElectronicManuel** [expo/expo#1475]
I am using google login for my app, it works fine in local production mode and in a standalone app, but when using local development mode or running the app from expo, the async/await function does not resolve and nothing happens.
The same behavior occurs when using the firebase-js sdk to authenticate a user with username / password.

### Environment

Environment:
  OS: Windows 10
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

Targets for the app are the android & ios expo client and standalone versions for both.

The problem occurred when testing on a Samsung Galaxy S8+ with Android 7.0 and Expo v2.3.0, however it worked as expected on an LG-G6 with Android 7.0 and Expo v2.3.0

### Steps to Reproduce

1. Open snack at [https://snack.expo.io/@aurora-apps/google-login-test](https://snack.expo.io/@aurora-apps/google-login-test)
2. Click Login with Google / Login with Facebook buttons
3. Close the login window

### Expected Behavior

An Alert should popup, informing me the login was cancelled

### Actual Behavior

Nothing happens, asynchronous function does not resolve

### Reproducible Demo

Snack at [https://snack.expo.io/@aurora-apps/google-login-test](https://snack.expo.io/@aurora-apps/google-login-test)

**Comment by terribleben** [comment]
Also linking this issue: https://github.com/expo/expo/issues/1429 Looks like one person in that thread resolved their issue by changing the parameters they were passing. We might have a case where we should be surfacing an error in production but it's hanging silently instead.

**Comment by jackxbritton** [comment]
I'm running into this issue as well with a MotoG3 on Android 6.0. There is no issue on a Galaxy S6 with Android 7.0. This is of course using the Expo app.

**Comment by aalices** [comment]
Hello @ElectronicManuel , I've been trying to find the reason of your problem and I found out that the promise actually resolves but the `Alert` does not appear 🤔  I just slightly modified your snack and after calling `logInWithReadPermissionsAsync` I've added a simple `console.log(type)` and it logs `cancel` . So the concern is now.. why the alert does not appear :O
