### ISSUE TITLE
[expo-av] New audio recording configuration for iOS on SDK43 introduces issues

### ISSUE THREAD

**Issue by berkcoker** [expo/expo#14760]
### Summary

The default configuration for audio recording on iOS was changed on SDK43, in favor of using the .m4a extension with RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC. This configuration works when the user makes an audio recording on their device and listens back to the same audio on that iOS device. However, when that audio file is uploaded to say cloud storage, and downloaded on a MacBook to listen back on Quicktime, it doesn't behave well. Quicktime complains about the file being corrupted, and ffmpeg reports invalid data / problematic moov atom.

The solution is to use the .aac extension.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.12.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 2021.10.11.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@berkcoker/m4a-configuration-for-ios

Should add code to test out uploading to the cloud (added a comment on snack on where to add this.)

**Comment by mnightingale** [comment]
In addition to the above I tested the new defaults from [here](https://github.com/expo/expo/blob/67e0d981c45eeddf770b1e01b5e982604f7d0610/packages/expo-av/src/Audio/Recording.ts#L118-L143) 

`.m4a` with `Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC` and I don't seem to have any issue with the file produced, can playback in Quicktime/VLC/Chrome.

For reference I just ran this in the simulator and looked at the local recording output file.

```console
$ file "m4a mpeg4aac new defaults.m4a"
m4a mpeg4aac new defaults.m4a: ISO Media, Apple iTunes ALAC/AAC-LC (.M4A) Audio
```

```console
$ afinfo "m4a mpeg4aac new defaults.m4a" 
File:           m4a mpeg4aac new defaults.m4a
File type ID:   m4af
Num Tracks:     1
----
Data format:     2 ch,  44100 Hz, 'aac ' (0x00000000) 0 bits/channel, 0 bytes/packet, 1024 frames/packet, 0 bytes/frame
                no channel layout.
estimated duration: 5.106939 sec
audio bytes: 39835
audio packets: 222
bit rate: 61821 bits per second
packet size upper bound: 371
maximum packet size: 371
audio data file offset: 57344
optimized
audio 225216 valid frames + 2112 priming + 0 remainder = 227328
format list:
[ 0] format:	  2 ch,  44100 Hz, 'aac ' (0x00000000) 0 bits/channel, 0 bytes/packet, 1024 frames/packet, 0 bytes/frame
Channel layout: Stereo (L R)
----
```

```console
$ ffmpeg -i "m4a mpeg4aac new defaults.m4a"
...
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'm4a mpeg4aac new defaults.m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2021-10-16T21:17:11.000000Z
  Duration: 00:00:05.15, start: 0.000000, bitrate: 150 kb/s
  Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 61 kb/s (default)
    Metadata:
      creation_time   : 2021-10-16T21:17:11.000000Z
      vendor_id       : [0][0][0][0]
...
```
