### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK"

### ISSUE THREAD

**Issue by ibogdan94** [expo/expo#1476]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.6.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/akela-a0b3da34-335d-42f1-80e1-175c9ed342ea.tar.gz

### Steps to Reproduce

(Write your steps here:)

1. cd ios
2. pod install
3. 
```bash
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.3.3`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `GLog` from `../node_modules/react-native/third-party-podspecs/GLog.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/2.3.3`) was resolved to 2.3.3, which depends on
      Google-Mobile-Ads-SDK (~> 7.22.0)

None of your spec sources contain a spec satisfying the dependency: `Google-Mobile-Ads-SDK (~> 7.22.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

```

### Expected Behavior

Install all dependencies successfully 

### Actual Behavior

Cannot Install all dependencies successfully (see step 3)

How I can fix it?

**Comment by ibogdan94** [comment]
Looks like when I export ios and android from expo, Podfile missed many dependencies for ios builds

**Comment by ibogdan94** [comment]
I found the solution
Leave it here, maybe someone faced with this problem

```bash
brew install openssl
brew upgrade openssl
brew install ruby
brew link --overwrite ruby
```

**Comment by terribleben** [comment]
As the cocoapods output printed, you should just be able to `pod repo update`. No need to `brew install` anything.

**Comment by ibogdan94** [comment]
@terribleben this does not help, I tried
