### ISSUE TITLE
MapView onRegionChange/onRegionChangeComplete no longer works with panning

### ISSUE THREAD

**Issue by ethantran** [expo/expo#1477]
### Environment

iPhone 6S+
Expo 25

### Steps to Reproduce

https://snack.expo.io/HJ146h7dG

Mapview using google provider with onRegionChange handler. 

Try to move around map using thumb.

### Expected Behavior

The map moves when you move your thumb on the screen.

### Actual Behavior

The map stops moving after it moves a little bit.

**Comment by terribleben** [comment]
Hey there! This snack works fine for me on my iPhone SE. I'm able to pan and zoom as expected. Can you provide more details?

**Comment by ethantran** [comment]
It works on v22, which is what I upgraded my app from. Once I change the version at bottom right to 25 it breaks.

**Comment by terribleben** [comment]
Ah yeah, I can see the issue now.

We upgraded our copy of React Native Maps to v0.19.0 in SDK 25. Maybe this is an issue with that library. Do any of [these](https://github.com/react-community/react-native-maps/issues?utf8=%E2%9C%93&q=is%3Aissue+onregionchange) look the same?

**Comment by ethantran** [comment]
Yeah it looks like I'll have to downgrade for now. https://github.com/react-community/react-native-maps/issues/1995
