### ISSUE TITLE
SDK 43 While trying to resolve module `firebase` from  ...

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#14772]
### Summary

So i upgraded my project from 42 to 43 Beta , all is fine except when i install firebase module i get this error , i even tried to start a blank project and import the firebase , the same error occurs . i think it has something to do with migrating unimodules to expo in the new SDK 

While trying to resolve module `firebase` from file `D:\GUITLAB\Taxi Teranga\taxi_Teranga_Beta\screens\SignupLogin\PhoneVerification.js`, the package `D:\GUITLAB\Taxi Teranga\taxi_Teranga_Beta\node_modules\firebase\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`D:\GUITLAB\Taxi Teranga\taxi_Teranga_Beta\node_modules\firebase\index`. Indeed, none of these files exist:    * D:\GUITLAB\Taxi Teranga\taxi_Teranga_Beta\node_modules\firebase\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)   * D:\GUITLAB\Taxi Teranga\taxi_Teranga_Beta\node_modules\firebase\index\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 4.12.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\lenovo\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ~43.0.0-beta.4 => 43.0.0-beta.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Just create a blank project 

install firebase module

import it in App.js you'll get the error .

**Comment by barthap** [comment]
Are you using the "Exotic" transformer by @EvanBacon?

It looks like it's the same problem as here: https://twitter.com/nightstomp/status/1449083131127025665?s=21
