### ISSUE TITLE
"Error: Could not read file or parse EXIF tags" in getAssetAsync

### ISSUE THREAD

**Issue by xabierun** [expo/expo#14777]
### Summary

When executing expo-media-library's getAssetAsync, I rarely get an error in MediaLibraryUtils.java's putAssetsInfo.

`for (int i = 0; i < limit && !cursor.isAfterLast(); i++) {`

The error occurs in the for statement above, and if there is even one error file, the return value will not be what is expected.
By inserting try/catch in the for statement, it will be possible to exclude only the files that have errors.
Is it possible for you to make the above modification?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.12.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nodebrew/current/bin/node
      Yarn: 1.22.10 - ~/.nodebrew/current/bin/yarn
      npm: 6.13.4 - ~/.nodebrew/current/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: 42.0.3 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

`
    const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);

    if (status !== "granted") {
      console.log("Camera roll permission denied");
      return;
    }

    let results: any;

    try {
      results = await MediaLibrary.getAssetsAsync({
        first: 20
      });
    } catch (e) {
      /* handle error */
      console.log(e.message);
      return;
    }
`

### stack trace

`
Error: Could not read file or parse EXIF tags
`

`
{
arguments: ["Error",{"nativeStackAndroid":[{"lineNumber":-2,"file":"FileInputStream.java","methodName":"open0","class":"java.io.FileInputStream"},{"lineNumber":200,"file":"FileInputStream.java","methodName":"open","class":"java.io.FileInputStream"},{"lineNumber":150,"file":"FileInputStream.java","methodName":"<init>","class":"java.io.FileInputStream"},{"lineNumber":103,"file":"FileInputStream.java","methodName":"<init>","class":"java.io.FileInputStream"},{"lineNumber":5191,"file":"ExifInterface.java","methodName":"initForFilename","class":"androidx.exifinterface.media.ExifInterface"},{"lineNumber":3926,"file":"ExifInterface.java","methodName":"<init>","class":"androidx.exifinterface.media.ExifInterface"},{"lineNumber":182,"file":"MediaLibraryUtils.java","methodName":"putAssetsInfo","class":"expo.modules.medialibrary.MediaLibraryUtils"},{"lineNumber":52,"file":"GetAssets.java","methodName":"doInBackground","class":"expo.modules.medialibrary.GetAssets"},{"lineNumber":22,"file":"GetAssets.java","methodName":"doInBackground","class":"expo.modules.medialibrary.GetAssets"},{"lineNumber":333,"file":"AsyncTask.java","methodName":"call","class":"android.os.AsyncTask$2"},{"lineNumber":266,"file":"FutureTask.java","methodName":"run","class":"java.util.concurrent.FutureTask"},{"lineNumber":1162,"file":"ThreadPoolExecutor.java","methodName":"runWorker","class":"java.util.concurrent.ThreadPoolExecutor"},{"lineNumber":636,"file":"ThreadPoolExecutor.java","methodName":"run","class":"java.util.concurrent.ThreadPoolExecutor$Worker"},{"lineNumber":764,"file":"Thread.java","methodName":"run","class":"java.lang.Thread"}],"userInfo":null,"message":"Could not read file or parse EXIF tags","code":"E_UNABLE_TO_LOAD"}], 
logger: console
}
`

**Comment by varora1406** [comment]
I am also facing same issue
