### ISSUE TITLE
SDK 43 - PhoneAuthProvider and other classes from firebase/auth 9.1.0 are exported as undefined

### ISSUE THREAD

**Issue by eliachiarucci** [expo/expo#14780]
### Summary

Hi everyone, I started an Expo app some days ago, I'm now trying to implement phone-based authentication, I initially started with the SDK 42 and manually installed firebase 9.1.2 as the [documentation](https://docs.expo.dev/guides/using-firebase/) already uses the new modular Firebase API (that's confusing).

Everything was working fine until I got stuck at the classes from firebase/auth, which exports as undefined.
So I tried upgrading my project to SDK 43, but without any luck.

I even tried to create a new SDK 43 project from scratch running `expo install firebase` but still, it doesn't work.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

Expo 42 and Expo 43

### Environment

  Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0-beta.4 => 43.0.0-beta.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Installation:
```
EXPO_BETA=1 expo init
expo install firebase
```

in the code:
```
import { PhoneAuthProvider } from "firebase/auth";
console.log(PhoneAuthProvider); // undefined
```

**Comment by dqii** [comment]
I think the fix was made to the Firebase JS SDK in 9.2.0 (https://github.com/firebase/firebase-js-sdk/issues/5638)

**Comment by dqii** [comment]
I tried updating to 9.2.0 but get the same error.

**Comment by dqii** [comment]
Some details for the cause of the error here: https://github.com/firebase/firebase-js-sdk/issues/5688
It seems the RecaptchaVerifier is missing a ._reset method
@byCedric

**Comment by Bruno-Lages** [comment]
I know it doesn't help anything, but I'm dealing with the same problem

**Comment by yoavTaieb** [comment]
Tried adding  ".current._reset = () => {}" but it also throw an error
