### ISSUE TITLE
react-native-maps@0.19.0 requires a peer of react@16.0.0 and react-native@0.51.0

### ISSUE THREAD

**Issue by iegik** [expo/expo#1478]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.53.3
    react: 16.2.0

### Steps to Reproduce

```
npm install expo@latest # expo@25.0.0
```
### Expected Behavior

No warnings

### Actual Behavior

```
npm WARN react-native-maps@0.19.0 requires a peer of react@16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-maps@0.19.0 requires a peer of react-native@0.51.0 but none is installed. You must install peer dependencies yourself.
```

https://github.com/react-community/react-native-maps/blob/v0.19.0/package.json#L36
Please keep this open until https://github.com/react-community/react-native-maps/issues/2045 will solved

**Comment by terribleben** [comment]
Hey there, would you mind specifying "expected behavior" as well? This doesn't seem like a bug to me, it seems like a couple harmless warnings.

**Comment by iegik** [comment]
Yes, it is a couple harmless warnings.
