### ISSUE TITLE
How to force screen orientation programmatically?

### ISSUE THREAD

**Issue by weeravit** [expo/expo#148]
Do you have any idea?

Thank you

**Comment by brentvatne** [comment]
Hello! You can edit the [orientation](https://docs.expo.io/versions/v16.0.0/guides/configuration.html#orientation) in `exp.json` but you can't change that at runtime. This is a known issue and we hope to resolve it soon.

**Comment by dikaiosune** [comment]
Hi! We support this in the [ScreenOrientation API](https://docs.expo.io/versions/v18.0.0/sdk/screen-orientation.html) as of SDK 18. Thanks!
