### ISSUE TITLE
Problem with host on iOS simulator 

### ISSUE THREAD

**Issue by ibogdan94** [expo/expo#1480]
Looks like my mobile app can't get info from Expo XDE

https://www.dropbox.com/s/sant4gl0soezxpm/Screenshot%202018-02-28%2014.44.28.png?dl=0

How I can fixed it?

**Comment by terribleben** [comment]
Hmm, your screenshot looks normal to me. Are you able to open `localhost:80` in your iOS Simulator's Safari app? Also, can you try restarting the project in XDE and then rebuilding your detached app from Xcode?
