### ISSUE TITLE
sdk43 android bare build fails to assembleRelease

### ISSUE THREAD

**Issue by awinograd** [expo/expo#14819]
### Summary

I cannot build a new bare android project created with expo SDK 43 beta. Please see the repro steps below.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43 beta

### Environment

  Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - ~/.nodenv/versions/16.9.1/bin/node
      Yarn: 1.22.11 - ~/.nodenv/versions/16.9.1/bin/yarn
      npm: 7.21.1 - ~/.nodenv/versions/16.9.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/awinograd/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0-beta.4 => 43.0.0-beta.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. EXPO_BETA=1 expo init
2. select bare project
3. cd android
4. ./gradlew assembleRelease

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade   
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/awinograd/programming/sdk43/test43/node_modules/expo/android/build/intermediates/aapt_friendly_merged_manifests/release/aapt/AndroidManifest.xml:2: AAPT: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'expo'.
```

**Comment by awinograd** [comment]
Here are the contents of the AndroidMainfest.xml file referenced in the OP

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="expo"
    android:versionCode="1"
    android:versionName="43.0.0-beta.4" >

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="30" />

</manifest>
```

**Comment by brentvatne** [comment]
i can't repro this and build works as expected on eas build. 

are you sure you didn't change something in your project after initializing it?

**Comment by awinograd** [comment]
Thanks @brentvatne for investigating. That change in commands did the trick. Sorry for the false report 😄
