### ISSUE TITLE
[docs] countryCode in expo-contacts with wrong return value

### ISSUE THREAD

**Issue by BrtqKr** [expo/expo#14813]
### Summary

Docs state that [Phonenumber](https://docs.expo.dev/versions/latest/sdk/contacts/#phonenumber) countryCode should return it in a +number prefix format, but in reality on ios it returns it as a country tag or something like that. For example for the US I'm getting 'us' instead of '+1'. 

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/contacts/#phonenumber

### Anything else?

This could probably be treated as a bug as well, because codes in that format are kind of useless in terms of using the number in the app.

**Comment by slytter** [comment]
Yes, this is still a problem

**Comment by Cheesetouched** [comment]
Not sure why this issue is closed. This is still very much an issue.
