### ISSUE TITLE
Jest-expo still depends on an outdated version of Jest

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#14823]
### Summary

Jest-expo is depending on v26 (1 major version old) and before that depended on v25 when v25 was a major version old. It seems to struggle to stay current and this causes issues in our projects downstream with tests. Could we make sure that jest-expo depends on a modern version of Jest?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

NA

### Reproducible demo or steps to reproduce from a blank project

NA

**Comment by justindra** [comment]
Just something to take into account as I've just run into this issue. Is the fact that `react-scripts` still uses jest v26 and it complains about the fact that there are two different versions of Jest. This is an issue for us that run both a React and React Native project in a monorepo with Yarn Workspaces. There's workarounds but it's not a smooth sailing thing. So upgrading to v27 may make it worse. Ideally if we could specify our own version of Jest would be great!
