### ISSUE TITLE
[expo-in-app-purchases] purchase.acknowledged is not set to true when calling finishTransactionAsync

### ISSUE THREAD

**Issue by mvanroon** [expo/expo#14828]
### Summary

According to the docs, calling `finishTransactionAsync` should acknowledge a purchase and set `purchase.acknowledged` to `true`. This is currently not the case. As a result, transactions are verified multiple times, functionalities get unlocked multiple times and `finishTransactionAsync` is called multiple times for a single purchase

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0.0

### Environment

Expo CLI 4.12.7 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/michiel/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ^0.17.1 => 0.17.5
    npmGlobalPackages:
      expo-cli: 4.12.7
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. Set up a purchase listener like so:

```typescript
setPurchaseListener(({ responseCode, results }) => {
  if (responseCode === IAPResponseCode.OK) {
    if (!results) return
    results.forEach(async (purchase) => {
      if (!purchase.acknowledged) {
        console.log(purchase)
        await finishTransactionAsync(purchase, false)
      }
    })
  }
})
```

2. Purchase an item on a physical Android device
3. Purchase gets logged. `finishTransactionAsync` is called.
4. Purchase a second item
5. Both purchases get logged, meaning calling `finishTransactionAsync` the first time on the first purchase did not set acknowledged to `true`

Please let me know if you require more info or research

**Comment by fobos531** [comment]
The exact same thing happens for me on iOS as well

**Comment by polcats** [comment]
It seems like this issue still exists.
`finishTransactionAsync` is called on the first purchase, but it does not seem to set `acknowledged` to `true`

**Comment by mvanroon** [comment]
Sure.

**Comment by polcats** [comment]
> Sure.

Thanks for the response. This is now resolved.

It seems like the caching in [InAppPurchases.getPurchaseHistoryAsync](https://docs.expo.dev/versions/latest/sdk/in-app-purchases/#inapppurchasesgetpurchasehistoryasyncoptions) affected it. 
Setting `useGooglePlayCache` to `false` resolved my issue.
