### ISSUE TITLE
HTTP 520 when trying to connect to LAN url in iOS Expo Client

### ISSUE THREAD

**Issue by EdmundMai** [expo/expo#1483]
I'm trying to start an app on an iOS simulator (tried it on my iPhone too) but I'm getting this:

<img width="399" alt="glass_and_iphone_7_ _ios_10_3__14e269_" src="https://user-images.githubusercontent.com/1857068/36799780-fa4cd3c2-1c7b-11e8-8888-22b54778ffd9.png">

I'm on the same network so I don't get why it doesn't work. Neither the QR code nor the URL works

**Comment by terribleben** [comment]
Hey there, we've seen a case in the past where some specific routers don't support connecting over a LAN address. This seems to be true more often with corporate networks and coffee shops. You could try the following:

- See if `192.168.1.102:19000` works in the device's web browser. If not, it's probably an issue with that network configuration.
- Try switching to a tunnel (if using a device) or to localhost (if using simulator). Tunnel is slower, but will work even across different networks.

**Comment by sjchmiela** [comment]
I'll let myself close this issue due to inactivity. 🕙 IMHO Ben provided much information about how to try to mitigate this issue. 🙂
