### ISSUE TITLE
Change Rate speed to default value. when pause and play from nativecontroller.

### ISSUE THREAD

**Issue by mohib06** [expo/expo#14830]
### Summary

When i'm do pause and play from native controller at that time rate value automatically change to 1.
For example if i give rate={0.25}
when i do pause and play from native controller it's convert to normal speed and in output it's give rate={1}.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

video_Ref Object {
  "didJustFinish": false,
  "durationMillis": 4034,
  "hasJustBeenInterrupted": false,
  "isBuffering": false,
  "isLoaded": true,
  "isLooping": false,
  "isMuted": false,
  "isPlaying": false,
  "pitchCorrectionQuality": "Varispeed",
  "playableDurationMillis": 4034,
  "positionMillis": 2358,
  "progressUpdateIntervalMillis": 50,
  "rate": 1,
  "shouldCorrectPitch": true,
  "shouldPlay": true,
  "target": 4809,
  "uri": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  "volume": 1,
}

### Reproducible demo or steps to reproduce from a blank project

1. start video with 0.25 rate speed.
2. click on pause and play again.
3. not video play at normal speed 1.

**Comment by brentvatne** [comment]
please provide a proper reproducible example: https://stackoverflow.com/help/minimal-reproducible-example
