### ISSUE TITLE
expo-constants insonsistent among Android and iOS

### ISSUE THREAD

**Issue by cederom** [expo/expo#14834]
### Summary

`expo-constants@11.0.2` has inconsistent behavior between Android and iOS:
1. Does not respect values from `app.json` (also tried `app.config.js`).
2. Does not respect `version` field (works on Android but not on iOS).
3. Does not respect `extra` field (works on Android but not iOS).

I am using macOS 11.6 for development with up to date Android Studio, XCode, and `expo-cli`.

`app.json`:
```
{
 "expo": {
  "version": "1.2.3local"
 }
}
```

Using with:
```
import Constants from 'expo-constants';

let version = Constants.manifest.version;
```

1. On Android `version` has correct value from `app.json`, also sees `extra` object.
2. On iOS `version` has some other value not from `app.json`, does not see `extra` object..

Please fix!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42.0.4

### Environment

```

  Expo CLI 4.12.7 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /opt/local/bin/zsh
    Binaries:
      Node: 16.11.1 - /opt/local/bin/node
      npm: 8.1.0 - /opt/local/bin/npm
      Watchman: 0.0.0 - /opt/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 21, 25, 26, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.4 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.14.13 => 0.14.13 
    npmGlobalPackages:
      expo-cli: 4.12.7
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Use `app.json` to define version type (local, lan, development, production). See it works on Android but does not work on iOS.

iOS seems to generate values on its own and does not respect values from `app.json`.

**Comment by brentvatne** [comment]
in bare projects, the value is embedded when you run a build, so if you run another build then it will be consistent
