### ISSUE TITLE
Expo crash when navigation back after press Marker Map in publish version, but debug version is worked

### ISSUE THREAD

**Issue by toanhosss** [expo/expo#1484]
I implement MapView on Expo SDK 24.0.2
import { Location, Permissions, Constants, MapView } from 'expo';

I render list marker view in Map and added handler switch marker in onPress:
`loadMarker = (data) => {
    if (data != null && data.length > 0) {
      return data.map( (item, index) => {
        return (
          <MapView.Marker
            style={{ zIndex: index }}
            key={index}
            coordinate={item.coords[parseInt((item.coords.length - 1) / 2)]}
            onPress={(e) => { this.selectDirectionHandler(e, index) }}
            onSelect={(e) => {this.selectDirectionHandler(e, index)}}
            >
            <InformationMarker
              duration={item.duration.text}
              distance={item.distance.text}
            />
          </MapView.Marker>
        )
      });
    }
  }`
In debug mode, it's work normal. But when publish to staging, Map marker can't press and Expo crash without error log when press back navigation

**Comment by fxfactorial** [comment]
Hi, can you make a snack that shows this happening? 

snack.expo.io

**Comment by toanhosss** [comment]
I have re-publish on staging and now it worked although I don't change anything code.
