### ISSUE TITLE
self-hosted multimanifest cannot be read by Android app

### ISSUE THREAD

**Issue by melanger** [expo/expo#14847]
### Summary

I have self-hosted over-the-air updates and I created a multimanifest. When I view logs (`adb logcat`) from an Android app created by `expo build`, I see that the manifest is not parsed, because the Android app expects a single object and not an array. The problem seems to be around this line:

https://github.com/expo/expo/blob/8a8ed4433790414a8b229064cd3a0795e3d428f4/packages/expo-updates/android/src/main/java/expo/modules/updates/loader/FileDownloader.java#L128

The logs say:

```
Failed to parse manifest data
org.json.JSONException: Value [{"name":"App name", .....}] of type org.json.JSONArray cannot be converted to JSONObject
 	at org.json.JSON.typeMismatch(JSON.java:112)
 	at org.json.JSONObject.<init>(JSONObject.java:169)
 	at org.json.JSONObject.<init>(JSONObject.java:182)
 	at expo.modules.updates.loader.FileDownloader$2.onResponse(FileDownloader.java:8)
 	at expo.modules.updates.loader.FileDownloader$4.onResponse(FileDownloader.java:1)
 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:3)
 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 	at java.lang.Thread.run(Thread.java:923)
```

This means that the app effectively ignores OTA.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  Expo CLI 4.12.1 environment info:
    System:
      OS: Linux 5.11 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 7.24.2 - /koc-expo/node_modules/.bin/npm
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.82 
      expo: ^42.0.0 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.14.0 => 0.14.13 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
npx expo export --non-interactive --max-workers 1 --public-url "https://example.com/ota/alpha" --merge-src-url "https://example.com/media/sdk41.tar.gz" --merge-src-url "https://example.com/media/sdk40.tar.gz"

# exported files are uploaded so that they are served from https://example.com/ota/alpha/
# exported files are compressed into sdk42.tar.gz and uploaded to be served from https://example.com/media/sdk42.tar.gz (after upgrading to SDK 43 in this case)

npx expo build:android --non-interactive --no-publish --release-channel alpha -t app-bundle --public-url "https://example.com/ota/alpha/android-index.json"
```

**Comment by melanger** [comment]
The bug is not fixed as far as I am concerned.

**Comment by ide** [comment]
Multimanifests is an old feature that isn't included in the Expo Updates specification, which is our primary focus until support for the old updates format is eventually removed from the expo-updates module. The specification is documented here: https://docs.expo.dev/technical-specs/expo-updates-0/. I mention this since given the number of issues it is possible the best way forward is to run your own updates server that implements the linked spec. There is a sample server here: https://github.com/expo/custom-expo-updates-server. EAS Update also implements the spec. In the meantime we can update the docs to reflect what the code actually supports.

**Comment by melanger** [comment]
Thanks for the links. I found references to multimanifests in other manuals (it was either for publishing or for self hosted OTA), so I thought multimanifests should be used for apps with multiple SDK support.

If it is an old feature which is going to be removed, I am going to use a different solution (I am self-hosting OTA, so I can put the SDK version in the URL and publish for each SDK on a different URL, which is what I am doing now).

Feel free to close this, but it would be great to update the docs to reflect the current state (and the future plans).

**Comment by ide** [comment]
> I can put the SDK version in the URL and publish for each SDK on a different URL, which is what I am doing now

Yes! Recommend this. In the future this approach will become more important once you start customizing the native code in your app. Each time you change the JS–native interface, you're changing the runtime used to run your updates. To keep track of this change, Expo Updates has a concept called the "runtime version", which is a string that distinguishes one runtime from another. Each preset SDK is a runtime, and each SDK version is basically a runtime version.

**Comment by ide** [comment]
> it would be great to update the docs

We're updating the docs shortly (https://github.com/expo/expo/pull/15967). Thank you for being understanding!
