### ISSUE TITLE
[expo-notifications] getDevicePushTokenAsync incompatible with latest Firebase APIs

### ISSUE THREAD

**Issue by jamesisaac** [expo/expo#14860]
### Summary

`react-native-firebase` v12 (released May 2021) followed the latest changes upstream Firebase SDKs, which included the removal of Firebase Instance IDs.  See https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#breaking-changes and https://firebase.google.com/docs/projects/manage-installations#retrieving-an-identifier

Latest version of expo-notifications still seems to be using the now unsupported method of getting a token, see: https://github.com/expo/expo/blob/5a8b4ede46d96231a87da87dc924a037aa7be882/packages/expo-notifications/android/src/main/java/expo/modules/notifications/tokens/PushTokenModule.java#L64

This results in the error:

> Error: Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;

**Workaround**: Downgrading to `react-native-firebase` v11 solves the issue.

I couldn't find anything in the docs talking about this incompatibility.  All I see is recommendations like *"You are free to use any native Firebase packages such as react-native-firebase in the bare workflow."* in https://docs.expo.dev/guides/setup-native-firebase/#bare-workflow-setup

Related issues: #14482

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
  Expo CLI 4.12.1 environment info:
    System:
      OS: Linux 5.14 Arch Linux
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 31.0.0
    npmPackages:
      expo: ^43.0.0 => 43.0.0 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.1 => 0.66.1 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- Create a bare React Native project.
- Follow Expo docs to add the Notifications module, including installing latest `react-native-firebase`.
- Make a call to `Notifications.getDevicePushTokenAsync()`

**Comment by dqii** [comment]
Was there a reason this wasn't pushed?

**Comment by JacobPozaic** [comment]
I also have this problem, I was able to temporarily fix it by using the following packages in my package.json: 
```
"@react-native-firebase/app": "^14.5.0",
"@react-native-firebase/iid": "^11.5.0",
```

NOTE: This does create another issue where you cannot use EAS to build because of the legacy peer dependency that iid@11.5.0 has on app@11.5.0, and downgrading app to 11.5.0 causes run-time issues.

NOTE: You may also need to put this code in somewhere to get this to work ( even though it looks like expo should be doing this anyways using the google-services.json, I don't really know it just was something that ended up working for me ):
```
import firebase from "@react-native-firebase/app";
if (!firebase.apps.length) {
    firebase.initializeApp( {
        appId: "1:xxxxx:android:xxxxxxxxxx",
        apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        databaseURL: "https://your-app-name-or-whatever.firebaseio.com/",
        projectId: "xxxxxxxxxxx",
        storageBucket: "gs://you-app-name-or-whatever.appspot.com/",
        messagingSenderId: "xxxxxxxxx"
    } ).catch( console.error );
}else {
    firebase.app(); // if already initialized, use that one
}
```

**Comment by tobiasr** [comment]
Also wondering, any updates on this? This forces projects to use quite old versions of react-native-firebase?

**Comment by ethan-park-is** [comment]
> Also wondering, any updates on this? This forces projects to use quite old versions of react-native-firebase?

you can use config plugin with the latest version of react-native-firebase as below comment suggested
https://github.com/expo/expo/pull/15010#issuecomment-1018242147
