### ISSUE TITLE
FirebaseRecaptchaVerifierModal freezes time to time

### ISSUE THREAD

**Issue by ButuzGOL** [expo/expo#14864]
### Summary

FirebaseRecaptchaVerifierModal freezes time to time
seems like issue with captcha sometimes it opens another it wont open and freezes

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

^42.0.0

### Environment

xpo CLI 4.11.0 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /Users/butuzgol/.rvm/rubies/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 25, 26, 27, 28, 30
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 31.0.0
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
<FirebaseRecaptchaVerifierModal
        // attemptInvisibleVerification
        ref={recaptchaVerifier}
        firebaseConfig={FIREBASE}
        languageCode={currentUser.language}
        cancelLabel={t('base.cancel')}
        // appVerificationDisabledForTesting={!IS_PROD}
      />

export const preSignInPhoneNumber = async (
  data: PreSignInPhoneDataType,
  options: { recaptchaVerifier: any },
) => {
  console.log('%capiCalls.ts line:129 data', 'color: #007acc;', data);
  const PhoneProvider = getFirebase().auth.PhoneAuthProvider;
  const provider = new PhoneProvider();
  console.log('%capiCalls.ts line:132 PhoneProvider', 'color: #007acc;', PhoneProvider);
  console.log(
    '%capiCalls.ts line:133 object',
    'color: #007acc;',
    options.recaptchaVerifier.current,
  );
  let verificationId;
  try {
**/// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! This step freezes and no try catch or next goes** 
    verificationId = await provider.verifyPhoneNumber(
      data.phoneNumber,
      options.recaptchaVerifier.current,
    );

  } catch (e) {
    console.log('%capiCalls.ts line:145 e', 'color: #007acc;', e);
  }
  console.log(
    '%capiCalls.ts line:137 object',
    'color: #007acc;',
    options.recaptchaVerifier.current,
  );
  return verificationId;
};
```

**Comment by expelledboy** [comment]
I have the same issue... it just hangs. @ButuzGOL Did you mange to solve this?
