### ISSUE TITLE
Debugging still not working with reanimated 2 features in use.

### ISSUE THREAD

**Issue by sstephans** [expo/expo#14889]
### Summary

I installed the new sdk 43 and updated all my dependencies including using the new react-native syntax instead of the github. At first I was able to use the debugger with reanimated 2 code. Today (2-3 days into development with the new sdk), I cannot use debugger mode. The app gives me an error (not a warning) that in order to use reanimated 2 I need to go through the installation instructions. I have already configured my babel config and confirmed it's working outside of debug mode. 

It was my understanding that the new sdk fixed the debugging issue with reanimated 2. So what's going on?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

edit: I had my definitions backwards. I'm on a managed workflow.

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

SDK 43.

### Environment

This happens on all devices. Android simulated, android physical, and xcode ios simulated. It happens on my PC desktop windows 10 environment, as well as my laptop macbook air on latest OS.

### Reproducible demo or steps to reproduce from a blank project

Install expo sdk 43.
Follow the installation instructions for reanimated 2.
Alter the app component to use reanimated 2 features like useSharedValue.
Open the app.
Switch to debugger mode. 
App should give the error.

**Comment by sstephans** [comment]
I have confirmed that debugging does not work on a fresh install of managed workflow apps if reanimated 2 features are on the screen.

1. `expo init`
2. Choose typescript blank
3. In project directory: `expo install react-native-reanimated`
4. Add babel plugin
```typescript
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
```
5. `expo start --clear`
6. The app starts. 
7. Turn off debug mode.
8. Modify App.tsx to include a reanimated to feature (here I use `useSharedValue`
```typescript
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import {useSharedValue} from 'react-native-reanimated';

export default function App() {
  const test = useSharedValue(0);
  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
9. See that the app still runs with debug mode off.
10. Open menu and turn on remote debugging
11. App reloads and gets this error
![image](https://user-images.githubusercontent.com/29578272/141506074-1e2cdabe-4598-4697-b89a-08371c21146d.png)

**Comment by AlanSl** [comment]
Same issue here, not stale, please don't close it @github-actions bot.

I'm also finding that if I force react-native-reanimated 1.x to be used instead of 2.x to avoid this issue, the whole expo build fails silently, nothing in any consoles, apps just fail with a generic "Sorry something went wrong" error screen, nothing in device logs.

**Comment by brentvatne** [comment]
@sstephans @AlanSl - I tried @sstephans steps and I was able to debug remote js. here is the repository: https://github.com/brentvatne/sstephans
