### ISSUE TITLE
NativeAnimatedModule.getValue is not a function 

### ISSUE THREAD

**Issue by lfoliveir4** [expo/expo#14884]
### Summary

I currently have an expo project on a monorepo. When I upgraded React Native to version 0.66.1, when I build the app, it crashes the Animation API.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 25, 26, 28, 29, 30
        Build Tools: 26.0.2, 28.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.5
      react: 17.0.2 => 17.0.2
      react-native: 0.66.1 => 0.66.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

At startup of my application running `yarn start`

### Stacktrace (if a crash is involved)

![image](https://user-images.githubusercontent.com/32423942/138726429-05c3d143-1ca2-4e8b-952b-0830bb47ce81.png)

**Comment by lfoliveir4** [comment]
@lukmccall Thanks for the interaction! Is there a forecast of the expo support for the RN 66?

**Comment by lukmccall** [comment]
We plan to add support for RN 66 in the current cycle. So it should come live during the next 3 weeks. However, I can't promise anything right now.

**Comment by lukmccall** [comment]
Hey @lfoliveir4, I was adding the support for RN 0.66. Here you can see the PR https://github.com/expo/expo/pull/15242. Unfortunately, I wasn't able to reproduce your issue. Could you provide the part of the js code which causes this error?

**Comment by lfoliveir4** [comment]
Hi! @lukmccall  I can't provide my code, but to reproduce the error was to upgrade react native to version 0.66 and change the React version to 17.0.2 as suggested by the [react native upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.66.1)

**Comment by lukmccall** [comment]
I did the same this as you and still, I can't reproduce that. I managed to run each example from https://reactnative.dev/docs/animations.

**Comment by lfoliveir4** [comment]
@lukmccall I can't extract my code for ca. This happened when I was updating my react native to version 0.66 in a pre-expo SDK version.

**Comment by lfoliveir4** [comment]
I recently noticed that your PR #15242 has been merged. How do I manage to install the SDK of the expo that supports the RN 0.66?

**Comment by lukmccall** [comment]
@lfoliveir4 the new version is live right now - `0.7.1`. However, I'm not sure if this will help in your case. Please, try. If this doesn't help, I need more information, because I wasn't able to reproduce this bug.
