### ISSUE TITLE
corrupted bundled assets contain an XML file instead of an image, possibly related to @2x vs. @3x

### ISSUE THREAD

**Issue by MikePodgorniy** [expo/expo#1488]
### Environment
**app.json**
```
"assetBundlePatterns": [
      "App/**/*.png",
      "App/**/*.jpg",
      "App/**/*.json",
      "App/Components/Form/assets/*.png",
      "assets/fonts/*.ttf"
    ],
```
**exp diagnostics**
```
[exp] Generating diagnostics report...
[exp] You can join our slack here: https://slack.expo.io/.
[exp] Cannot find module 'envinfo'
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.
```

**Target = Android**

### Steps to Reproduce

1. exp ba
2. https://expo.io/builds/272d4361-b68c-475e-a6a2-b8f960acf348
3. Download apk
4. Rename apk -> zip
5. unpack 

### Expected Behavior

All assets are correct

### Actual Behavior

**./assets/shell-app-manifest.json** 
contains 173 assets

**./assets/assets_XXX.png** contains 
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>7CF62E1B609328ED</RequestId><HostId>0StI+MwHlzWE2srD/FSgJXtyWjx7xcKkhOSZ8v9n+PWTdTDdhRNou8OnpKAJaKUgHBRK7cJVJkE=</HostId></Error>
```

![2018-03-02 12 13 08](https://user-images.githubusercontent.com/5052136/36894526-5454b760-1e14-11e8-8a4a-141fbed7ea85.png)

**Comment by jesseruder** [comment]
Hi! What version of `exp` do you have?

**Comment by MikePodgorniy** [comment]
```
exp --version
49.2.2
```

**Comment by spezzino** [comment]
I did see corrupted images only when @2x or @3x assets were loaded. I removed those assets and kept only one size (without @x).

**Comment by janicduplessis** [comment]
This is fixed in the latest sdk release.
