### ISSUE TITLE
App renders borders differently in the Expo app vs iOS simulator

### ISSUE THREAD

**Issue by jaredlunde** [expo/expo#149]
Hi there,

I'm running into an issue in rendering borders within the Expo app on the iPhone. The first screenshot shows the app rendering correctly within the iOS simulator and the second is the same app rendered within the Expo app on the iPhone. Also pictured is the correct rendering of borderRadius on TextInput components.

![simulator screen shot may 3 2017 5 15 15 pm](https://cloud.githubusercontent.com/assets/86995/25685347/097adb54-3024-11e7-8106-fdfe13b979b5.png)
![img_0007](https://cloud.githubusercontent.com/assets/86995/25685354/0f7435f0-3024-11e7-90d5-e18ec545fd12.png)

**Comment by brentvatne** [comment]
hello! can you please reproduce this on http://snack.expo.io/ for us? thanks! :)

**Comment by jaredlunde** [comment]
Interesting - I couldn't reproduce the issue so I did a fresh install of `create-react-native-app` and the same app renders correctly now. I'm not sure what went wrong but I'm glad it's fixed. Sorry for using your time and thanks for the link!

**Comment by malangaveuday** [comment]
Hey,  I am having the same issue many times and this issue is only for IOS.  
On the android same code is working fine.

I am using the Ubuntu 16.04.
