### ISSUE TITLE
expo app playing sounds on return from multitasking

### ISSUE THREAD

**Issue by amansahil** [expo/expo#1490]
For some reason when I return from multitasking to the app , the click sound that I have programmed in, plays. It doesn't play the sound if the function was never called while the user was using the app. 
So for example if the user used the app without ever triggering the sound it won't play when returning from the multitasking screen. However , if the user has triggered the sound once or more than once the sound will play that many times on return. 
This behavior can also be noticed when pulling down the notification bar or when a pop up notification appears for low battery.

Code:
`class Home extends Component {`

 ` Play() {`
    `this.clickSound();`
  `}`

  `async clickSound() {`
    `const soundObject = new Expo.Audio.Sound();`
    `try {`
      `await soundObject.loadAsync(loadedClickSound);`
      `await soundObject.playAsync(loadedClickSound);`
    `} catch (error) {`
    `}`
  `}`
  `render() {`
    `return (`
     ` <Button
        title="PLAY"
        large
        onPress={() => this.Play()}
      />`
`);`
`}`
`}`
Things I have tried :

1) Adding soundObject.unloadAsync() in componentWillUnmount

2) The same thing but right after the sound plays. Although this just causes the sound not to play at all.

Note: I only have an IOS device not sure if the issue can be recreated on android

Second Note: This isn't the same as #1329, cause in that case, the un-played sounds played afterwards

**Comment by jesseruder** [comment]
Hey @amansahil! That sounds like a crazy bug. Can you make a Snack out of this code so it's easier for us to test?

**Comment by ide** [comment]
As a workaround for now, one thing you could do is subscribe to playback status events. There is a piece of data in that event that tells you when the clip has finished. When that happens, you would tell the sound to stop — this sets its internal state so that it doesn’t try to play again until you next tell it to.

**Comment by amansahil** [comment]
@jesseruder 

Just made it, just pull the notification bar or re enter the app on IOS and it will recreate the problem

https://snack.expo.io/B1y4HpwdM

**Comment by otaviogaiao** [comment]
Its happening to me too. Whenever my app comes back from background the sound replays.

**Comment by platbr** [comment]
+1
Same issue here.

**Comment by ide** [comment]
Thank you for the reports. This appears to be an bug with Expo iOS and is a known issue. We don't have a fix slated for SDK 26 but please see my post above for a conceptual workaround. There is a small example here: https://github.com/ide/love-languages/blob/6fd73d3c85a13db60fbc0c22b26d88b3feeb3cbe/app/assets/Sounds.js#L39-L43

**Comment by otaviogaiao** [comment]
Thank you @ide. Your solution solved the problem on iOS. 
if I don't register the listener on playbackStatus, it kinda works on Android too, with just a little bug: The sound only plays after the first time. (Mine is a barcode scanner, so when I scan the second qrcode, the sound plays). But thats acceptable for now.

`  
const beepSound = require("../../assets/sounds/beep-07.mp3");

async componentDidMount() {
    this.beep = new Audio.Sound();
    if (Platform.OS === "ios") {
      this.beep.setOnPlaybackStatusUpdate(playbackStatus =>
        this.handlePlaybackStatusUpdate(this.beep, playbackStatus)
      );
    }
    this.beep.loadAsync(beepSound);
  }

  handlePlaybackStatusUpdate(sound, playbackStatus) {
    if (playbackStatus.didJustFinish) {
      sound.stopAsync();
    }
  }

  async playBeep() {
    try {
      await this.beep.replayAsync();
    } catch (err) {
      console.log("erro tocando som", err);
    }
  }`

**Comment by pavelsly** [comment]
+1
Same issue here.

**Comment by sjchmiela** [comment]
This issue has been fixed in https://github.com/expo/expo/commit/3835682976a0ec1c0604654546f5e6f5c77c8de5, which will ship in SDK 26. :)
