### ISSUE TITLE
[expo-file-system] FileSystem.downloadAsync never rejects promise if device is offline or URL is invalid on iOS

### ISSUE THREAD

**Issue by jakob-p** [expo/expo#14902]
### Summary

When running FileSystem.downloadAsync on iOS while the device is offline or the URL is invalid the promise returned by downloadAsync never is rejected (or resolved).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 27, 28, 29, 30
        Build Tools: 29.0.2, 30.0.3
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

This snacks shows that the promise of FileSystem.downloadAsync is not rejected on iOS if the URL is invalid:

https://snack.expo.dev/@jakobpfab/filesystem-downloadasync-not-rejecting-on-invalid-url-on-ios

When running this on Android, an alert shows up that the promise of FileSystem.downloadAsync got rejected, on iOS nothing happens.

**Comment by neiker** [comment]
4 years later, `FileSystem.downloadAsync` still does not resolve or reject when downloading fails
