### ISSUE TITLE
presentIOSFullScreenPlayer causes video to stop playing

### ISSUE THREAD

**Issue by snly2386** [expo/expo#1491]
### Environment

 IOS, Expo 24
### Steps to Reproduce

1. Render the expo Video component
2. Call {videoRef}.presentIOSFullScreenPlayer()
3. Video will subsequently stop playing visually after 1-2 seconds, despite the progressbar incrementing.

### Expected Behavior

Expected the video to play normally without interruption.

### Actual Behavior
When playing a video and calling the videoRef.presentIOSFullScreenPlayer, the video will cease playing after 1-2 seconds visually.  You can still see the progress bar incrementing though.

### Reproducible Demo

Link to snack here: https://snack.expo.io/rJ8j5uP_z

**Comment by sjchmiela** [comment]
Hi @snly2386!

Can you reproduce the issue on the device too? I just checked and on the device it seems to work just fine:

![screenrecording_03-14-2018 18-46-10](https://user-images.githubusercontent.com/1151041/37421076-ae5456c8-27b8-11e8-9822-c5738fb2fc71.gif)

However, in the Appetize Simulator the video seems to freeze indeed.

I guess we're not the only ones bumping into this: https://github.com/react-native-community/react-native-video/issues/479.

**Comment by snly2386** [comment]
Yes you're right.  On device, it worked without any problems.

**Comment by sjchmiela** [comment]
Great! Do you think in that case we could close this issue? If the fullscreen player works properly on the device I think the main priority behavior is covered (😄) and it may be extremely difficult to debug why it works properly on the device but not in the simulator. If it's crucial to you to get it working in the Simulator I can try to poke around, but I can't promise anything. 😞
