### ISSUE TITLE
Expo SDK 43 points to an incompatible version of react-native-maps

### ISSUE THREAD

**Issue by bartvanandel** [expo/expo#14940]
### Summary

Just upgrated our app from Expo SDK 42 to 43, only to find out that this introduced a dependency clash when react-native-maps is also used, making `npm install` fail. The issue is however also present in the current version of react-native-maps, so an actual fix will have to wait until this related issue is resolved: https://github.com/react-native-maps/react-native-maps/issues/3992 (more details there as well).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

43

### Environment

_NB: this could only be retrieved *after* running `npm install --force`_

  Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.12.0 - C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      npm: 8.1.0 - C:\ProgramData\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    npmPackages:
      expo: ~43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```sh
npm i -g expo-cli
mkdir expo-test
expo init                       # and accept all defaults...
cd my-app
expo install react-native-maps  # this errors out due to dependency conflicts,
                                # but it does add the package to package.json
npm install --force             # this resolved it for our situation, no guarantees though
```

**Comment by brentvatne** [comment]
@bartvanandel - appreciated!

**Comment by bartvanandel** [comment]
The upstream issue has been fixed! See linked remote issue for more info.

**Comment by bartvanandel** [comment]
@brentvatne @byCedric I could prepare a PR but I'm quite sure that the time it would take me to create one plus review cycle is far larger than the time it takes you to update the dependency directly. So, how to proceed?

**Comment by brentvatne** [comment]
@bartvanandel - i updated the version to 0.28.1, you should get this when you run `expo install react-native-maps` now

thanks for following up!
