### ISSUE TITLE
Splash Image does not disappearing after navigating to a different screen

### ISSUE THREAD

**Issue by LastxTemplar** [expo/expo#1494]
### Environment

Environment:
  OS: Windows 10
  Node: 6.11.0
  Yarn: Not Found
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3934792

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/radegastdigital-25339f95-3752-4164-953f-1f4e0e449442.tar.gz

Publishing on iOS and Android.

### Actual Behavior

I am using a splash screen image in my app.json. That image still remains even when the app navigates to the next screen.
This ONLY happens on the live version of the app that I download from the play/app store, this never happens in my local environment.

Better way to show it is in a video.

[Video Link Here](https://www.youtube.com/watch?v=46quDjHgLpQ&feature=youtu.be)

### Expected Behavior

Splash Image should have disappeared

**Comment by brentvatne** [comment]
cc @jesseruder / @esamelson / @aalices

**Comment by aalices** [comment]
Can you try setting the screen background color to white? (the most bottom <View> or some other component)

**Comment by LastxTemplar** [comment]
That's exactly what I did to fix the issue, it worked, but this is still an unexpected behaviour.

**Comment by aalices** [comment]
You're right! I will definitely try to get rid of it

**Comment by kodbilenadam** [comment]
The issue remains today:

`{
  "expo": {
    "name": "test-projesi",
    "description": "A very interesting project.",
    "slug": "test-projesi",
    "privacy": "public",
    "sdkVersion": "30.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}
`

**Comment by esamelson** [comment]
@kodbilenadam - thanks, we're aware of this issue. For now, the simplest workaround is to simply add a root `View` component behind the rest of your app with a background color of white (or anything else).

**Comment by skurpi** [comment]
Why is this issue closed if the problem is still there? I'm also still experiencing it with sdk 31

**Comment by ricardovf** [comment]
Also have this problem. Using the workaround of setting the background for now. Spent some time to debug it as it only happens outside expo...

**Comment by zilahir** [comment]
the problem persits, setting the background color is a workaround which i am fine with.

**Comment by tomfinney** [comment]
This happened to me just now on v32. It's just weird that it doesn't occur locally in the dev version but does happen on a production built version and the only solution is to effectively to cover up the splash screen with a background colour which I guess is fine?
