### ISSUE TITLE
Upgrade GoogleSignIn to support XCode 13, Apple Silicon M1 and expo 43 and iOS Simulator

### ISSUE THREAD

**Issue by RohovDmytro** [expo/expo#14963]
### Summary

Boild for iOS in simulator failes with `expo-google-sign-in` package.

````
 in /Users/username/Documents/universage/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn(GIDEMMErrorHandler_3a47e13d8ca81b41e9cdb7ef5468004a.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/username/Documents/universage/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn' for architecture arm64

````

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment
````
 Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 25, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-24 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM 64 v8a, android-28 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.1 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
    Expo Workflow: bare
````

### Reproducible demo or steps to reproduce from a blank project

1. expo init
2. add expo-google-sign-in
3. launch iOS emulator for M1 build.

The app fails to start.

This happens because the underlying library has an old version which does not support m1 macs.

Related:
https://github.com/firebase/firebase-ios-sdk/issues/7208
https://github.com/google/GoogleSignIn-iOS/issues/26
https://github.com/google/GoogleSignIn-iOS

The GoogleSignIn-iOS v6 adds support for M1.

**Comment by tr4g** [comment]
no news???

**Comment by brentvatne** [comment]
we recommend using [@react-native-google-signin/google-signin](https://github.com/react-native-google-signin/google-signin) instead. [we will deprecate expo-google-signin in sdk 44](https://github.com/expo/expo/pull/15295)
