### ISSUE TITLE
Push notification sound on standalone iOS app does not work

### ISSUE THREAD

**Issue by gunzino** [expo/expo#1496]
### Environment
Environment:
  OS: Linux 4.10
  Node: 8.9.4
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Target: Standalone app on iOS

### Steps to Reproduce

Send push notification to standalone app. If I send the same data with token from Expo app, sound plays. Also I do not see 'Allow sounds' in notification configuration on my app in iOS.

### Expected Behavior

Sound should play

### Actual Behavior

Sound does not play

**Comment by brentvatne** [comment]
cc @terribleben - the issue appears to be that sound will play in response to a push notif in expo client but not in standalone in @gunzino's experience

**Comment by gunzino** [comment]
Removing the app and installing again from the app store solved the problem.

**Comment by terribleben** [comment]
Hey there, since reinstalling solved it, I suspect it was a system permissions issue. Let me know if you're still seeing this.
