### ISSUE TITLE
Cannot read property 'requestForegroundPermissionsAsync' of undefined

### ISSUE THREAD

**Issue by KrustySama** [expo/expo#14960]
### Summary

I recently update my bare RN project to the latest version. My project is working normally on an Android emulator and I'm able to access anything that requires location permission.
However, when I try to build the app on the iOS emulator. I keep getting this error
`Cannot read property 'requestForegroundPermissionsAsync' of undefined`
I also do not see the location permission pop-up in my iOS app anymore. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

 Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.4.2 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.18.1 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/admin/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 21, 26, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.66.1 => 0.66.1 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Unfortunately, I am not able to create a demo for this as my project is huge and private.
But this is the list of expo packages that I use.

`
    "expo-location": "^12.0.4",
    "react-native-unimodules": "^0.14.0",
`

This is my implementation
```

import { getForegroundPermissionsAsync, getLastKnownPositionAsync } from "expo-location";

const { status } = await getForegroundPermissionsAsync();
      if (status === "granted") {
        const location = await getLastKnownPositionAsync();
        if (location) {
          console.log({ location: location });
        }
      }
```

**Comment by brentvatne** [comment]
more info on the latest version of these packages: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc

> Unfortunately, I am not able to create a demo for this as my project is huge and private.

this page provides some good guidance on how to do this: https://stackoverflow.com/help/minimal-reproducible-example

happy to look into it if you provide a reproducible example!
