### ISSUE TITLE
Expo Notifications lagging behind

### ISSUE THREAD

**Issue by cheymonty** [expo/expo#14974]
### Summary

I am using Expo Notifications, and on my standalone ios and android app, my notifications are only getting sent after another notification is sent.
ex:
send → test1
– nothing
send → test2
– user gets test1 but not test2
send → test3
– user gets test2 but not test3

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42.0.0

### Environment

Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I removed some AWS stuff, but this is the code I have using the nodejs expo server sdk. 
```
const { Expo } = require('expo-server-sdk');
const HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Credentials': true,
  'Access-Control-Allow-Headers': '*',
};

const expo = new Expo();

module.exports.send_announcement = withSentry(async (event) => {
  const body = JSON.parse(event.body);

  // return 500 if no announcement
  if (!body.announcement) {
    return {
      statusCode: 500,
      body: 'missing announcement',
    };
  }

  const tokens = [];
  let last;

  // scan has 1MB limit, so while loop allows us to get all tokens
  do {
    const items = await ddb.scan(params).promise();
    items.Items.forEach((item) => tokens.push(item));
    params.ExclusiveStartKey = items.LastEvaluatedKey;
    last = items.LastEvaluatedKey;
  } while (last);

  // construct message for each token
  const messages = tokens.map((token) => ({
    to: token.token,
    title: 'App name',
    sound: 'default',
    body: body.announcement,
    priority: 'high',
  }));

  const errors = [];

  // chunk them to send in batches, sometimes chunks ended up being undefined?
  const chunks = expo.chunkPushNotifications(messages);
  const tickets = [];
  if (chunks) {
    (async () => {
      for (let chunk of chunks) {
        try {
          const ticketChunk = await expo.sendPushNotificationsAsync(chunk);
          tickets.push(...ticketChunk);
        } catch (error) {
          errors.push(error);
        }
      }
    })();
  } else {
    (async () => {
      for (let message of messages) {
        try {
          const ticketChunk = await expo.sendPushNotificationsAsync(message);
          tickets.push(...ticketChunk);
        } catch (error) {
          errors.push(error);
        }
      }
    })();
  }

  // receipts are returned after notifications have been delivered
  const receiptIds = [];
  tickets.forEach((ticket) => {
    if (ticket.id) {
      receiptIds.push(ticket.id);
    }
  });

  // checking receipts for errors
  const receiptIdChunks = expo.chunkPushNotificationReceiptIds(receiptIds);
  receiptIdChunks.forEach((chunk) => {
    (async () => {
      try {
        const receipts = await expo.getPushNotificationReceiptsAsync(chunk);

        receipts.forEach((receiptId) => {
          const { status, message, details } = receipts[receiptId];
          if (status === 'error') {
            errors.push({ status, message, details });
          }
        });
      } catch (error) {
        errors.push(error);
      }
    })();
  });

  if (errors.length !== 0) {
    return {
      statusCode: 500,
      body: JSON.stringify(errors),
    };
  }

  return {
    statusCode: 200,
    headers: HEADERS,
  };
});
```

**Comment by BrodaNoel** [comment]
I'm not sure what is going on here, but I think I'm having some similar problem since last week.

Usually when I send Push Notifications to ALL the users, I get ~200 users opening the app. On Saturday I sent Push Notifications to ALL users and only 2 users opened it. King of weird... It seems like none of them were sent, or something weird.

But there is something weird there: I got the notification in my phone, so, technocally it's been sent, but, none of my friends who have my app installed received anything

**Comment by cheymonty** [comment]
I figured out the issue. I was using await for some of the expo functions, but I did not await the parent functions.
add **await** in front of the functions so they become
```
await (async() => {
      for (let chunk of chunks) {
        try {
          const ticketChunk = await expo.sendPushNotificationsAsync(chunk);
          tickets.push(...ticketChunk);
        } catch (error) {
          errors.push(error);
        }
      }
    })();
```
```
await (async () => {
      try {
        const receipts = await expo.getPushNotificationReceiptsAsync(chunk);

        receipts.forEach((receiptId) => {
          const { status, message, details } = receipts[receiptId];
          if (status === 'error') {
            errors.push({ status, message, details });
          }
        });
      } catch (error) {
        errors.push(error);
      }
    })();
```
should also consider using standard for loops instead of forEach loops, as they do not work well with `async/await`
