### ISSUE TITLE
@expo/next-adapter now installs next.js 12 by default, but its babel config causes issues in next 12

### ISSUE THREAD

**Issue by codinsonn** [expo/expo#14971]
### Summary

Tried to do a minimal repro with a next.js implementation ([moti#14](https://github.com/nandorojo/moti/issues/14#issuecomment-955243098)) but ran into some issues when adding next.js via `"@expo/next-adapter": "^3.1.6"`'s `yarn next-expo`. The command finishes just fine, but the files created, namely `babel.config.js`, are missing some edits to get it working with next.js 12.

Specific issues seem to be related to `@expo/next-adapter/babel`:
- `'@babel/plugin-proposal-private-property-in-object'` & `'@babel/plugin-proposal-private-methods'` should have same `{ loose: boolean }` setting
- `yarn next dev` Does not work: `Warning: useTransformReactJsxExperimental has been renamed to useTransformReactJSXExperimental (capitalized JSX) in react-native@0.64.0`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.2 => 0.16.6 
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

### Minimal repro

1. `npx create-react-native-app -t with-moti`
2. `expo upgrade` -> Update SDK 42 to 43
3. `expo install @expo/next-adapter`
4. `yarn next-expo` -> Testing this in-browser already seems to fail for some other babel plugin related reasons

**Comment by Simek** [comment]
> * `yarn next dev` Does not work: `Warning: useTransformReactJsxExperimental has been renamed to useTransformReactJSXExperimental (capitalized JSX) in react-native@0.64.0`

I have also stumble upon this message, it is only a warning, and Expo web project works correctly for me even with older property name.

**Comment by AMSTKO** [comment]
> '@babel/plugin-proposal-private-property-in-object' & '@babel/plugin-proposal-private-methods' should have same { loose: boolean } setting

For this warning I updated my babel config and needed to install the packages,

`npm install --saveDev @babel/plugin-proposal-private-methods @babel/plugin-proposal-private-property-in-object`

babel.config.js

```js
module.exports = {
  presets: [
    '@expo/next-adapter/babel',
  ],
  plugins: [
    ["@babel/plugin-proposal-private-methods", { "loose": true }],
    ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
  ]
};
```

not the best solution for the moment

**Comment by VISHAWANATH953** [comment]
const isLocal = request.startsWith('.') || // Always check for unix-style path, as webpack sometimes
                                ^

TypeError: Cannot read properties of undefined (reading 'startsWith')

getting this error when running it

**Comment by ericvicenti** [comment]
I am experiencing the same error as @VISHAWANATH953 after upgrading from next 11 to next 12, with the latest version of expo next adapter

Example repo is here: https://github.com/ericvicenti/expo-next12-adapter-repro

**Comment by jose-munoz-dsny** [comment]
> const isLocal = request.startsWith('.') || // Always check for unix-style path, as webpack sometimes ^
> 
> TypeError: Cannot read properties of undefined (reading 'startsWith')
> 
> getting this error when running it

same error here

**Comment by iam-yan** [comment]
> const isLocal = request.startsWith('.') || // Always check for unix-style path, as webpack sometimes ^
> 
> TypeError: Cannot read properties of undefined (reading 'startsWith')
> 
> getting this error when running it

**+ 1**

**Comment by niyowski** [comment]
[This](https://github.com/expo/expo/issues/14971#issuecomment-962458561) and [this](https://github.com/expo/expo-cli/issues/4195) solved my issues.

**Comment by chrisarts** [comment]
Im not an expert on babel configs but lots of hours researching about this I have this:

now FlatLists doesnt crash on native and I can launch web and native at the same time (I dont use monorepo)
```
// @generated: @expo/next-adapter@4.0.4
// Learn more: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md#shared-steps
function isWebCaller(caller) {
  // console.log('CALLER: ', caller);
  return !!(caller && caller.name !== 'metro');
}
module.exports = function (api) {
  // api.cache(true);
  const isWeb = api.caller(isWebCaller);
  const presets = ['@expo/next-adapter/babel'];
  const defaultConfig = {
    presets,
    plugins: [
      [
        'module-resolver',
        {
          root: '.',
          extensions: ['.tsx', '.ts', '.js', '.json', '.mjs', 'jsx'],
          alias: {
            '@i18n': './src/i18n',
            '@graphql': './src/graphql',
            '@screens': './src/screens',
            '@components': './src/components',
            '@layouts': './src/layouts',
            '@config': './src/config',
            '@constants': './src/constants',
            '@hooks': './src/hooks',
            '@services': './src/services',
            '@utils': './src/utils',
            '@navigation': './src/navigation',
          },
        },
      ],
      'react-native-reanimated/plugin',
    ],
  };
  if (isWeb) {
    return {
      ...defaultConfig,
      plugins: [
        ['@babel/plugin-transform-react-jsx', { loose: true }],
        ['@babel/plugin-proposal-class-properties', { loose: true }],
        ['@babel/plugin-proposal-private-methods', { loose: true }],
        ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
        ...defaultConfig.plugins,
      ],
    };
  }
  return defaultConfig;
};
```

**Comment by kodunmi** [comment]
Any solution yet ?

**Comment by fbryo21** [comment]
I have the same issue here. Anyone can help? @expo
