### ISSUE TITLE
Expo push notification app metadata usage & volumes

### ISSUE THREAD

**Issue by mailtobash** [expo/expo#1497]
I am looking to introduce notifications in my app and wanted to know details on Expo push notification service. I tried asking in the slack channel but could not get a response there.

1. Usually push notification services use metadata about the app/data from the app in exchange for notification services. What kind of data is used by the expo push notification platform?
2. The app has a big volume of users, so the notifications will be big in volume. Is there a restriction on the number of notifications or how do I know that expo platform can handle all the notifications? Is there any enterprise support?

Thank you.

**Comment by mailtobash** [comment]
Well #2 has been answered, I do see enterprise support and pricing on the website.
But it would be great if someone could let me know what app data/metadata will be used by expo for push notifications

**Comment by ide** [comment]
1. We don't store nor share/sell/etc. push notifications or their metadata. We just send the push notification payloads to our push providers (Apple & AWS).

2. If your notification load is high enough to significantly impact our costs we might ask you to help cover them but our intent is not to make money off it, just to cover the costs. Realistically how what do you envision your notification workload to look like?

**Comment by terribleben** [comment]
Hey there, I'm going to close this for now - let us know if you have more info about the volume of pushes you anticipate sending. As @ide mentioned, we don't store or sell information about your app or its push notifications. Good luck with your project! :)

**Comment by mailtobash** [comment]
Hey @terribleben ,
Thank you for the update. I should have closed it earlier.
