### ISSUE TITLE
DocumentPicker documentation expects to set usesIcloudStorage config which is not documented

### ISSUE THREAD

**Issue by janschloss** [expo/expo#14976]
### Summary

Hello,

in this part of the documentation https://docs.expo.dev/versions/latest/sdk/document-picker/

> For iOS, outside of the Expo Go app, the DocumentPicker module requires the iCloud entitlement to work properly. You need to set the usesIcloudStorage key to true in your app.json file as specified here.

There is a link to https://github.com/expo/expo/blob/master/docs/pages/workflow/configuration.md#ios

Which redirects to https://docs.expo.dev/versions/latest/config/app/#ios

Which does not contain the described key usesIcloudStorage.

**Is this still needed to make DocumentPicker work on iOS?**

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS, Web

### SDK Version (managed workflow only)

Current

### Environment

It's just a documentation issue.

### Reproducible demo or steps to reproduce from a blank project

It's just a documentation issue.

**Comment by Simek** [comment]
Hi @janschloss, I can see the `usesIcloudStorage` property on the `config/app` page:
* https://docs.expo.dev/versions/latest/config/app/#usesicloudstorage

<img width="1151" alt="Screenshot 2021-10-31 at 17 12 07" src="https://user-images.githubusercontent.com/719641/139592514-e5ac8302-339d-4bfb-8931-8db8a11f5832.png">

Are you sure that you were not looking at older version on the config page?

**Comment by janschloss** [comment]
@Simek I'm not sure what happend there, maybe it was an old version yeah, I can confirm that now it shows for me, too, weird. Thanks!
