### ISSUE TITLE
Expo Location reverseGeocodeAsync add distance in return. 

### ISSUE THREAD

**Issue by josedavidgc** [expo/expo#14970]

**Comment by josedavidgc** [comment]
In the Geolocation.reverseGeocode Async method in the results, the distance that the returned address is from the coordinates must be added. When Google does not have the address of those coordinates, it returns the closest one and that brings confusion. Given the distance, you can set the address or not. HERE maps always return the distance of that direction with respect to the coordinates in the Reverse Geocode

**Comment by byCedric** [comment]
Hi @josedavidgc! I'm not sure if I follow, do you want the distance of the address compared to the provided coordinate? And based on this, you want to determine if this address is "close enough" to prefill as an address?

I'm not sure where in the response we would get that distance. We have 2 types of geocoding:
1. [Google Geocoding API](https://github.com/expo/expo/blob/master/packages/expo-location/src/LocationGoogleGeocoding.ts#L55-L70), which is just a simple request to [Google's API from JS side](https://developers.google.com/maps/documentation/geocoding/overview#GeocodingResponses) (works on Android, iOS and web)
2. [Android Geocoding API](https://github.com/expo/expo/blob/master/packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java#L407-L437), which is the native one
3. [iOS CoreLocation Geocoding API](https://github.com/expo/expo/blob/master/packages/expo-location/ios/EXLocation/EXLocation.m#L285-L320), which is also the native one

Feel free to create a PR adding the functionality you describe, I'd be happy to review it! But, I'm not sure if that's available in these APIs.
