### ISSUE TITLE
errors installing Expo modules 

### ISSUE THREAD

**Issue by evanbinyang** [expo/expo#14985]
### Summary

install expo modules failed following guide :https://docs.expo.dev/bare/installing-expo-modules/

Automatic installation by 'npx install-expo-modules' error is :

[!] Invalid `Podfile` file: wrong number of arguments (given 2, expected 1).

I found it popped by https://github.com/expo/expo/blob/master/packages/expo-modules-autolinking/scripts/ios/autolinking_manager.rb line 45:

pod_options = {
            :path => podspec_dir_path,
            :testspecs => tests.include?(package.name) ? ['Tests'] : []
          }.merge(global_flags, package.flags)

It given 2 arguments when Hash merging.

My pod env is:

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin20]
    RubyGems : 3.2.30
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.20.1
Ruby lib dir : /Users/byang/.rbenv/versions/2.5.8/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/byang/.rbenv/versions/2.5.8/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43.0.1

### Environment

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin20]
    RubyGems : 3.2.30
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.20.1
Ruby lib dir : /Users/byang/.rbenv/versions/2.5.8/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/byang/.rbenv/versions/2.5.8/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0

### Reproducible demo or steps to reproduce from a blank project

install Expo modules in a existing project created with npx react-native init.

**Comment by Kudo** [comment]
@evanbinyang could you share your `ios/Podfile`?

**Comment by evanbinyang** [comment]
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'XXXApp' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'XXXAppTests' do
    inherit! :complete
    # Pods for testing
  end


  post_install do |installer|
    react_native_post_install(installer)
  end
end

**Comment by evanbinyang** [comment]
many thanks, it works after upgrading Ruby.

**Comment by evanjmg** [comment]
upgrading to ruby 3 doesn't solve this. https://giters.com/expo/expo/issues/14983

**Comment by brentvatne** [comment]
@evanjmg - could you share your `ios/Podfile`?

**Comment by evanjmg** [comment]
```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '12.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'SampleProject' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  # end

  post_install do |installer|
    react_native_post_install(installer)

    # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
    # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

end
```

**Comment by brentvatne** [comment]
and what error do you get when running `npx install-expo-modules`?

**Comment by evanjmg** [comment]
npx install-expo-modules
npx: installed 121 in 16.677s
✔ Expo modules minimum iOS requirement is 12.0. This tool will change your iOS deployment target to 12.0. Do you want to continue? … yes
› Updating your project...
Uncaught Error AssertionError [ERR_ASSERTION]: Project file "MainApplication" does not exist in android project for root

**Comment by brentvatne** [comment]
it looks like you don't have a MainApplication.java or MainApplication.kotlin in your android directory

**Comment by evanjmg** [comment]
shouldn't require this as what if I don't want to have any android dependencies?

**Comment by evanjmg** [comment]
same issue after installing

**Comment by evanjmg** [comment]
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233)

**Comment by brentvatne** [comment]
what version of cocoapods do you have?

**Comment by evanjmg** [comment]
cocopods 1.5.0

**Comment by evanjmg** [comment]
upgraded cocoapods and resolved my issue. Strange how I did this before and my shell didn't update.

**Comment by brentvatne** [comment]
good to hear! we support cocoapods >= 1.10.0

**Comment by cubesmeta** [comment]
How did you upgrade your cocoapods? Seems to be a few ways?

**Comment by aaronsmulktis** [comment]
> many thanks, it works after upgrading Ruby.

I got no errors about Ruby... but this was EXACTLY what unblocked me after 2 days of troubleshooting. THANK YOU!!!
I had been making such great progress, feeling like a champ, thankful for the shoulders of the giants I am standing on, and then:

```$ expo run:ios
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: undefined method `exists?' for File:Class.

 #  from /Users/smokey/Internal/AllRise/code/AllRise/ios/Podfile:13
 #  -------------------------------------------
 #  target 'AllRise' do
 >    use_expo_modules!
 #    use_modular_headers!
 #  -------------------------------------------
```
