### ISSUE TITLE
Cannot use animateToBearing and animateToViewingAngle in react-native-maps function

### ISSUE THREAD

**Issue by toanhosss** [expo/expo#1498]
I implement google maps in react-native-maps on Expo latest version SDK 25.0.0,
<Expo.MapView
          style={styles.mapContent}
          provider={this.state.provider}
          showsUserLocation={true}
          region={this.props.gpsDirection.regionData}
          onMapReady={this.onMapReady}
          ref={ref => this.mapRef = ref}
          followsUserLocation={true}
          showsCompass={true}
>
I get this error when call animateToBearing or animateToViewingAngle:
this.mapRef.animateToBearing(45, 1000);
Error:
undefined is not an object (evaluating 'this._mapManagerCommand(name).apply')

**Comment by terribleben** [comment]
Hey there,

There's an example of `animateToViewingAngle` in our community example app [here](https://github.com/expo/native-component-list/blob/master/screens/MapsScreen.js#L85). Does that work for you? Note that this method isn't available with Google Maps on iOS.
