### ISSUE TITLE
FirebaseRecaptchaVerifierModal: TypeError: verifier._reset is not a function. (In 'verifier._reset()', 'verifier._reset' is undefined)]

### ISSUE THREAD

**Issue by p3p4r** [expo/expo#14994]
### Summary

- Firebase SDK version: 9.2.0

I'm implementing firebase phone auth but getting an error.
After the error is shown, I get the message with the code. The problem is that I can't save the code received in the request.

Similar issue here: https://githubmemory.com/repo/firebase/firebase-js-sdk/issues/5688

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

9.20

### Environment

- Firebase SDK version: 9.2.0

I'm implementing firebase phone auth but getting the below error:

verifier._reset is not a function. (In 'verifier._reset()', 'verifier._reset' is undefined) when getting token
```
 const auth = getAuth();
  const phoneProvider = new PhoneAuthProvider(auth);

  const id = await phoneProvider.verifyPhoneNumber(
    this.state.phoneNumber, //valid
    this.recaptchaVerifier.current //valid
  ); // throughs the message here
  
 //not reaching here
 console.log(id)
```
I Trigger the recaptcha but receive this error message from the promise:
**[Unhandled promise rejection: TypeError: verifier._reset is not a function. (In 'verifier._reset()', 'verifier._reset' is undefined)]**

After the error is shown, I get the message with the code. The problem is that I can't save the code received in the request.

Similar issue here: https://githubmemory.com/repo/firebase/firebase-js-sdk/issues/5688

### Reproducible demo or steps to reproduce from a blank project

- Trigger the Firebase verifyPhoneNumber() or signInWithPhoneNumber() with the FirebaseRecaptchaVerifierModal.

**Comment by brentvatne** [comment]
duplicate: https://github.com/expo/expo/issues/14716
