### ISSUE TITLE
Blank White after leaving the app in the background for a long time.

### ISSUE THREAD

**Issue by zaura-payments** [expo/expo#14990]
### Summary

This only happens in my built application, when I open my app for the first time it launches fine and I am presented with the correct content. However when I push the app to the background and then leave it there for a long duration (12+ hours) then reopen it, I am presented with a blank white screen.

I have Sentry setup in my application and no errors are thrown when this bizarre issue happens, this is making it very difficult to debug why its actually happening. This is present on both Android and iOS, the issue also seems to persist after closing the app down after a long period of time and then opening it again. If I then close it down a second time and reopen it, it is fixed.

This issue only occurs when I leave the app for a long time, if I was to open the app and then leave it in the background for 20 minutes - the issue does not occur. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 17.0.2 => 17.0.2
      react-dom: 16.13.1 => 16.13.1
      react-native: ^0.63.1 => 0.63.4
      react-native-web: ^0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- Create a react native expo project.
- Build to a device (Android or iOS it doesn't matter)
- Open your application.
- Put the application in the background and leave it for a long period of time (12+ hours)
- Open the application again OR close the app and reopen it.
- Presented with a blank white screen which can only be resolved by closing the app and reopening again.

**Comment by cruzach** [comment]
@zaura-payments have you verified this happens with a totally blank project? `expo init` then `expo build`?

**Comment by devth** [comment]
If you google for things like:

- [expo blank white screen](https://www.google.com/search?q=expo+blank+white+screen&rlz=1C5GCEM_enUS995US995&sxsrf=APq-WBsUMIxsUDdqd3MXS7nnSWbkOCrzPA%3A1646764678699&ei=hqInYtifKqK90PEPhPSj2As&ved=0ahUKEwjY-s69lLf2AhWiHjQIHQT6CLsQ4dUDCA8&uact=5&oq=expo+blank+white+screen&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECc6BwgAEEcQsANKBAhBGABKBAhGGABQtgJYtgJg_QNoAXABeACAAYkBiAGJAZIBAzAuMZgBAKABAcgBCMABAQ&sclient=gws-wiz)
- [react native white screen of death](https://www.google.com/search?q=react+native+white+screen+of+death&rlz=1C5GCEM_enUS995US995&sxsrf=APq-WBudD5TbJnI1DUaNx8dhusiTSPWClw%3A1646764680796&ei=iKInYv6VMIid0PEPruWO8AU&ved=0ahUKEwj--c6-lLf2AhWIDjQIHa6yA14Q4dUDCA8&uact=5&oq=react+native+white+screen+of+death&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECc6BwgjELADECc6BwgAEEcQsAM6BQgAEJECOgsILhCABBCxAxCDAToRCC4QgAQQsQMQgwEQxwEQowI6CwgAEIAEELEDEIMBOgUIABCABDoOCC4QgAQQsQMQxwEQowI6BAgAEEM6BwgAELEDEEM6CwguEIAEELEDENQCOgoIABCxAxCDARBDOgsIABCxAxCDARCRAjoKCAAQgAQQhwIQFDoGCAAQFhAeSgQIQRgASgQIRhgAUO5JWONmYMZnaAZwAXgBgAGwAogB3yaSAQgwLjMxLjEuMZgBAKABAcgBCcABAQ&sclient=gws-wiz)

You'll find many results. Some of them old/outdated, some new and helpful. Ultimately there are a million reasons why this happens (I recently discovered I was missing an `await` in some code that runs in the Background when a user tracks a new HealthKit Activity).

I wonder if Expo could provide some tips/docs on debugging this. I'm running into it again and it's very slow and hard to debug or repro, especially when it only happens in the background.

For me, the current debug cycle looks like:

1. try an idea for a fix or add some logging to my (bare Expo) code
2. push to EAS and wait for ~30 min for a new TestFlight build
3. install the new build, put the app in the background, and go about my day
4. track some activity in HealthKit
5. wait hours until iOS decides to fully background my app and the HealthKit new workout event gets mysteriously called, completely outside my control
6. open the app 6 or 12 or 18 hours later and see if the white screen repros
7. if not, wait another day or two
8. repro the white screen, go to step 1

Pain.

It's probably more of a general React Native problem. But Expo has a reputation for making RN bearable (and sometimes downright pleasant!)
