### ISSUE TITLE
[RN 0.66.1] What is the right way of configurating a Podfile?

### ISSUE THREAD

**Issue by realtril** [expo/expo#14992]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by realtril** [comment]
This is what I have for now:

`
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '12.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'test' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )


  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
end
`

But this generated podfile from 43 upgrade is not letting to build and android. Trying to find the right way for configuring a Podfile with 0.66.1 react native version.

**Comment by Simek** [comment]
Hi @realtril, every version of Expo SDK is tailored for the specific version of React Native, which can be seen in docs:
* https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a

Using the newest version then listed one in table could lead to the unexpected problems and issues. 

Future version of the Expo SDK will support RN 0.66, but for now it's recommended to stay on 0.64.

**Comment by realtril** [comment]
@Simek , got it... So is there another way to support android 12 without upgrading a react native?

**Comment by Simek** [comment]
AFAIK there is no easy workaround for that, you need to wait for the RN 0.66 support in Expo.

Can you share the build error you are seeing when using the given above Podfile?

**Comment by realtril** [comment]
Now I'm good with using Podfile from the expo migration guide. 

But I can't do android build due this error:
<img width="1063" alt="Screen Shot 2021-11-02 at 11 49 20 AM" src="https://user-images.githubusercontent.com/53015418/139824256-988d4ffa-8c87-4468-971e-2e6398cda4d4.png">

**Comment by Kudo** [comment]
although expo sdk still sticks at react-native 0.64, most expo modules should be compatible with newer react-native. if not, please let us know.

your gradle error seems to be `com.linkedin.dexmaker:2.21.0` only available on jcenter maven repo. please try to add `jcenter()` back into your build.gradle or upgrade dexmaker to latest version.

**Comment by darrylyoung** [comment]
Hi, @Kudo.

Regarding your comment, is there any way to get an idea which Expo modules currently _aren't_ compatible with React Native versions greater than the Expo-suggested version? I guess not as it's just extra work to maintain something like this but I figured I'd ask anyway as I'm in the process of upgrading to SDK 43 but would like to use 0.66.1. Thank you.

**Comment by Kudo** [comment]
yes, we didn't fully test that. we just make sure expo modules will work great with sdk supported version. otherwise, it used to be user report an issue and we check if we can solve it.

**Comment by realtril** [comment]
@Kudo I have managed to fix my builds with returning jcenter() to the build.gradle. Thank you!

The only question I have - is it kind of safe to use expo 43 with react native 0.66.1 OR is it would be better to wait for 44 version?

**Comment by Kudo** [comment]
@realtril it depends on which expo modules you used. at least i tried expo-device with rn 0.66.1 and it worked fine. you can check the doc about how to adapt expo modules: https://docs.expo.dev/bare/installing-expo-modules/. if you encounter any incompatible issues, please open an issue and let us know.
