### ISSUE TITLE
Test fails on fresh project with tabs template (Cannot find module 'react-test-renderer')

### ISSUE THREAD

**Issue by apaatsio** [expo/expo#14991]
### Summary

Tests fail on a fresh project with the tabs template. Error message: `Cannot find module 'react-test-renderer' from 'components/__tests__/StyledText-test.js'`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

SDK 43

### Environment

```
  Expo CLI 4.12.10 environment info:
    System:
      OS: Linux 5.14 Manjaro Linux
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    IDEs:
      Android Studio: AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```
expo init --template tabs foo
cd foo
npm test
```

**Comment by apaatsio** [comment]
Workaround is to install react-test-renderer manually: `npm install --save-dev react-test-renderer@17.0.1`

**Comment by byCedric** [comment]
Thanks for reporting this! I added the missing dependency and upgraded jest to the right version.
