### ISSUE TITLE
ImagePicker restarts application and carries previously selected image over. 

### ISSUE THREAD

**Issue by ChristianTucker** [expo/expo#1499]
### Environment

Targets: Android  (Pushing to ExpoClient right now)

### Steps to Reproduce

Here's my code that I'm using:

```javascript
let result = await ImagePicker.launchImageLibraryAsync({
    mediaType: 'Images',
    allowsEditing: true,
    aspect: [1, 1],
    quality: 0.65
})
```

The issue occurs during the transition of selecting an image and moving towards the `allowsEditing` screen. Please note that this happens regardless of file size and it seems to be completely random as to when the restart happens (After the steps are followed). It may restart on a certain image and then be fine afterwards.

### Expected Behavior

When selecting an image through the ImageLibrary it should transition to the "Editing" screen without restarting the application. 

### Actual Behavior

I'm trying to use the ImagePicker API to launch the ImageLibrary. When I select an image the application restarts. When I go back to the screen to select an image there are then multiple ImagePicker's available. I have to select my image and then exit out (or cancel) the others. The amount of stacked imagepickers depends on how many times the application restarts. There is no RedBox here. The app just restarts immediately.

**NOTE: ** after the restart the Image is selected and ready to be edited once you load the ImageLibrary again. You can then edit the image you just selected, and then it takes you to the page to edit the image you selected before the application restarts. 

### Reproducible Demo

-- Reproducible demo is provided in the steps to reproduce since it's just calling the simple ImagePicker function and using it until the issue happens.

**Comment by nicknovitski** [comment]
Hi Christian, could you link a simple [snack](snack.expo.io) that reproduces the problem?  That's what we mean by "Reproducible demo".

**Comment by ChristianTucker** [comment]
@nicknovitski  Sorry about that, the code provided was literally the "Reproducible demo" so I figured anyone could copy and paste it into snack.

Here's the snack URL:  https://snack.expo.io/rJDqfDROf

Just to cover all the bases, I've added all of the code that's in my app into this snack, as you can see it's still very simple and straightforward. There's logging for each step so you can see where the application "Restarts". 

Typically it restarts between the transition of selecting an image and moving it to the native "Editing" page.

**Comment by terribleben** [comment]
One random thought: This might be a side effect of the Expo `ErrorRecovery` module auto-restarting the app after hitting a fatal error.

**Comment by terribleben** [comment]
Linking this issue which seems related: https://github.com/expo/expo/issues/1539

**Comment by sebastian-schlecht** [comment]
I'm also seeing this without the editing part. The app just seems to die randomly after taking a picture. Sometimes you can take up to ten images or more in a row but eventually it will die.

**Comment by sjchmiela** [comment]
I've just tested the Snack provided on SDK31 and it worked as expected. I think the issue may have been resolved in recent versions of Expo SDK. I'll close this issue tentatively, feel free to reopen it if you encounter it again! 🙂
