### ISSUE TITLE
[expo-clipboard] getStrinyAsync - "Unhandled promise rejection" when fetching selected text

### ISSUE THREAD

**Issue by salvadoruriel** [expo/expo#15004]
### Summary

getStringAsync fails and shows this warning when trying to fetch text from a clipboard that was previously selected and copied.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.0

### Environment

expo diagnostics

  Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

See the docs' Snack https://docs.expo.dev/versions/latest/sdk/clipboard/

1. Open the Android emulator/device,
2. Open Google (or anywhere you can type).
3. Type something, select that text and copy.
4. Open the snack, press "View Copied Text" button
5. Nothing happens, if using expo developer tools the error/warning will show.

**Comment by brentvatne** [comment]
wrap your call to `getStringAsync` with try/catch to handle the error

**Comment by salvadoruriel** [comment]
That doesn't solve the problem, is expo-clipboard incapable of handling this type of copy-paste?
More specifically from the error: "Cannot convert argument of type class android.text.SpannableString"

**Comment by salvadoruriel** [comment]
I realized the title might be misleading, this is about getStringAsync's failure when trying to fetch this kind of copied text.

**Comment by brentvatne** [comment]
that looks like a legitimate issue for us to handle! can you create a new issue for that? thanks!

**Comment by private-jil** [comment]
Happens with me too, on a ColorOS (v. 11.1) Android device.  Please fix!!
