### ISSUE TITLE
[expo-analytics-amplitude] android setUserIdAsync doesn't allow `null`

### ISSUE THREAD

**Issue by awinograd** [expo/expo#15007]
### Summary

I get the following error when calling `setUserIdAsync(null)`

> Error: Encountered an exception while calling native method: Exception occurred while executing exported method setUserIdAsync on module ExpoAmplitude: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter userId

However, this use case is valid to represent logging out a user and was supported until the [kotlin rewrite](https://github.com/expo/expo/commit/b24fdd04d30ff97a02de3d01439e66ba9efce929#diff-c4a9300eb8571ef48f5d800be952b05892473d65e1a4d8796318f433a94bea08R49). 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - ~/.nodenv/versions/16.9.1/bin/node
      Yarn: 1.22.11 - ~/.nodenv/versions/16.9.1/bin/yarn
      npm: 7.21.1 - ~/.nodenv/versions/16.9.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/awinograd/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.0 
      react-native: 0.64.2 => 0.64.2 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. Call `setUserIdAync(null)` on android

**Comment by cruzach** [comment]
thanks @awinograd, I think this should be an easy fix by changing [this line](https://github.com/expo/expo/blob/master/packages/expo-analytics-amplitude/android/src/main/java/expo/modules/analytics/amplitude/AmplitudeModule.kt#L49) to 

```
  fun setUserIdAsync(userId: String?, promise: Promise) =
```

**Comment by tsapeta** [comment]
Hi @awinograd, I just published my fix from #15028 in version `11.0.4` (`next` tag on npm), please let me know if that solved the issue for you 😉

**Comment by awinograd** [comment]
11.0.4 works great! Thanks @tsapeta

**Comment by yonitou** [comment]
Hi, 

Just saw this thread and updated the package to 11.0.4. It's not working from my side .. I still got this error : 

`Encountered an exception while calling native method: Exception occurred while executing exported method setUserIdAsync on module ExpoAmplitude: Parameter specified as non-null is null: method kotlin.j0.d.s.e, parameter userId`

Do you have any idea ?
