### ISSUE TITLE
Expo shows blue screen if not online.

### ISSUE THREAD

**Issue by Summonshr** [expo/expo#1500]
Why is it constantly asking for an online resource when my app has nothing to do online?

When I build standalone apk and install it offline. It runs perfectly. 

It will work smoothly as expected if I keep working offline. No issues here.

But if I ever go online, the app cannot start again in offline mode. I just have to be online if I am to use this app.

On my debug, it is showing unable to resolve cloudfront.net which means it is probably trying to take some resources from internet.

Why? It worked perfectly offline previously.

**Comment by nicknovitski** [comment]
By default, all expo apps check for updates at your published url, served by cloudfront.  We've written [a guide for customizing the update and offline behaviors of your app](https://docs.expo.io/versions/latest/guides/offline-support.html).  Let me know if it leaves you with any more questions.

**Comment by Summonshr** [comment]
Thank you very much. Do not use App Loading component at all. And you won't
end up with this error.
