### ISSUE TITLE
In App Purchase -  Billing V4 - Error after expo build:android 

### ISSUE THREAD

**Issue by devGuerra** [expo/expo#15003]
### Summary

Hello,

i am developing an app with expo sdk 43 and in app purchases. Developing through expo run: android I can test in-app purchases without any problems. However when I run or expose build: android to generate an appbundle, I get stuck in the google store with this error.

![Captura de tela 2021-11-02 121100](https://user-images.githubusercontent.com/6579736/139875614-2422cbcc-fa4c-4fa7-a19e-7365ec842c32.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

windows 11

geting error Command failed: wmic os get Caption

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@devguerra/expo

i this snack i put only my dependencies.

**Comment by devGuerra** [comment]
I solve this bug generating .aab in android studio and upload with expo publish:android, in expo build:android i got error on upload

**Comment by cruzach** [comment]
As it says in the [docs](https://docs.expo.dev/versions/latest/sdk/in-app-purchases/#installation), `expo-in-app-purchases` is only available in the bare workflow (so not `expo build:android`). But you can use it with `eas build`!
