### ISSUE TITLE
ExpoModulesCore/ConcreteViewProp.swift > Fatal error

### ISSUE THREAD

**Issue by charles-goode** [expo/expo#15012]
### Summary

On a recent production build of our iOS app (built by the EAS server), everything seems to be working fine except for pressing/swiping on certain push notifications. For which, our sentry service reports the following error:
```
EXC_BREAKPOINT
ExpoModulesCore/ConcreteViewProp.swift > Fatal error
```
Due to a build issue we are having with android, I can't say for sure whether there's a similar issue for android. We trigger push notifications with a number of different cloud functions, but only the notifications from a particular cloud function are having this issue. I haven't been able to replicate this issue in our dev-client. 

More than likely, this is occuring because of something we are doing wrong. Yet, the fact that the error comes from expo but gives very little helpful information on debugging, indicates this is a place where error logging could be improved from the SDK side. 

I first mentioned this in another thread I found from googling this crash, and was told it could relate to `expo-linear-gradient` which we use quite heavily (just over 40 uses with lots of parameterizations too). Was told to @tsapeta from #14948 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

  ```Expo CLI 4.12.8 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.1 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.12.8
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Since this is push notification related, as far as I can tell, I can't snack it. Also since I don't know where the bad code is, I can't share code which may be at fault. For clarity, we've been using push notifications successfully for a really long time in the same manner. Only after upgrading to expo 43 and making a production build, did something go wrong.

**Comment by MorganV** [comment]
I believe I have suggested a workaround here: https://github.com/expo/expo/issues/14948#issuecomment-958146373

**Comment by tsapeta** [comment]
@MorganV, you said

> It turns out that (at least for me) this code crashes silently

Does that mean it's still not working but at least not crashing? 😅

**Comment by MorganV** [comment]
> @MorganV, you said
> 
> > It turns out that (at least for me) this code crashes silently
> 
> Does that mean it's still not working but at least not crashing? 😅

To clarify -- it crashes, but does not seem to log anything. In my case I caught the crash via Sentry first and then while running a custom dev client from XCode.

**Comment by tsapeta** [comment]
As the similar issue https://github.com/expo/expo/issues/14948 has already been closed, I think I can also close this one. Let me know if you're still encountering it though 😉
