### ISSUE TITLE
lastNotificationResponse returns null or undefined when app is killed

### ISSUE THREAD

**Issue by mfmurray** [expo/expo#15016]
### Summary

lastNotificationResponse is not working when app is killed. It shows either null or undefined when you click on a notification.

```
export default function App() {
  const lastNotificationResponse = Notifications.useLastNotificationResponse();

  React.useEffect(() => {
    console.log({ lastNotificationResponse });
  }, [lastNotificationResponse]);

  return (
    <Text>App</Text>
  );
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.1

### Environment

Expo CLI 4.12.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\mike\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~42.0.1 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Kill App
2. Send Notification
3. Click on Notification

**Comment by RodolfoGS** [comment]
Duplicated https://github.com/expo/expo/issues/14078

**Comment by mfmurray** [comment]
Yes, I'm using Expo Go. Is there another way to test Notifications on IOS besides TestFlight?

**Comment by cruzach** [comment]
`expo run:ios` or create an internal distribution build with EAS Build

**Comment by cruzach** [comment]
Closing since this is expected, will reopen if you see the same behavior on standalone builds

**Comment by onlyhope** [comment]
I am seeing this on a standalone build run within TestFlight. I'm using  Notifications.useLastNotificationResponse. Exampel code below:


```
export default function App() {
  const lastNotificationResponse = Notifications.useLastNotificationResponse();

  useEffect(() => {
    const payload = _.get( lastNotificationResponse, 'notification.request.trigger.payload', {} );
    if( payload.link ) {
      Linking.openURL( payload.link );
    }
  }, [lastNotificationResponse] );
...
```
