### ISSUE TITLE
expo-dev-menu is causing EAS built bare app to crash on first load

### ISSUE THREAD

**Issue by dereknelson** [expo/expo#15013]
### Summary

when the app is launched for the first time, it brings up the expo dev menu briefly and promptly crashes. [video](https://user-images.githubusercontent.com/6868432/139949330-37d4716e-cdc5-40fa-91af-ae234a6823b9.MP4)
built with eas profile:
```
    "preview": {
      "distribution": "internal",
      "ios": {
        "simulator": false
      }
    },
```
has these packages installed: 
```
"expo-dev-client": "^0.6.3",
"expo-dev-launcher": "^0.8.4",
"expo-dev-menu": "^0.8.4",
"expo-dev-menu-interface": "^0.4.1",
```
sentry error:
```
Cannot remove an observer <EXSplashScreenService 0x281d62f00> for the key path "rootViewController" from <EXDevMenu.DevMenuWindow 0x106b41690> because it is not registered as an observer.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43 (not managed)

### Environment

  Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 8.1.1 - ~/.nvm/versions/node/v14.15.1/bin/npm
      Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare

eas-cli/0.34.0 darwin-x64 node-v14.15.1

### Reproducible demo or steps to reproduce from a blank project

here's a screenshot of the [sentry error](https://prnt.sc/1y7a5si)

**Comment by dereknelson** [comment]
side note eas-cli didn't come up by running expo-diagnostics, i ran eas --version & feel like that would be useful context to have by default

**Comment by tevonsb** [comment]
I have the same issue, following upgrade to `sdk43` my `run` and `build` generate:

```
The following build commands failed:
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'expo-dev-menu' from project 'Pods')
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'expo-dev-launcher' from project 'Pods')
        PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/xx/Library/Developer/Xcode/DerivedData/OXOOwner-fpoilcorujnzlkgulaoirajyysnf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-90A22A838B66CAB1A15B8A3A947BFF6D.sh (in target 'FBReactNativeSpec' from project 'Pods')
(3 failures)
```

**Comment by Kudo** [comment]
please update `expo-splash-screen@0.13.5` with #15026 change. that should fix the issue. thank you!
