### ISSUE TITLE
KeepAwake component doesn't work when video player is full screen

### ISSUE THREAD

**Issue by jacokok** [expo/expo#1501]
### Environment
I only managed to test on Android

### Steps to Reproduce

1. Play video
2. Make video fullscreen
3. The screen will sleep depending on the display settings of device

### Expected Behavior

The device display should not dim or sleep while video playing fullscreen

### Actual Behavior

Screen first dims then sleeps

### Reproducible Demo

https://snack.expo.io/H13Dglndf

**Comment by nicknovitski** [comment]
Thank you so much for making a reproduction!  Unfortunately, when I try to open it on my own android, it crashes with `TypeError: null is not an object (evaluating 'playbackObject.presentFullScreenPlayer`.  Could you fix that, so I could see the issue?

**Comment by jacokok** [comment]
Hi, updated the snack to have the bare minimum.

https://snack.expo.io/rktbCM6dG

Open the video in full screen mode. Then depending on device settings the screen will dim.
Thank you so much!

**Comment by rafaelsorto** [comment]
Hi, I am having the same issue.  If you have a Component with Video and KeepAwake it works as long as you don't change the video to Fullscreen. Once the Video is changed to FullScreen, KeepAwake stops working and the screen goes to sleep.

As a workaround what I am doing right now is using a Modal to cover the entire screen, grow the video with flex: 1 and having KeepAwake included as well. It looks as if it is fullscreen but if the user decides to actually change it to fullscreen it will go to sleep :'(
Best Regards,
Rafael

**Comment by amowu** [comment]
I also have the same problem, when in full screen mode, it will enter sleep mode.

**Comment by terribleben** [comment]
Landed fix internally, will ship with SDK 29
