### ISSUE TITLE
Expo-AV not work for iOS

### ISSUE THREAD

**Issue by aldobel** [expo/expo#15021]
As the title suggests, the <Video /> component of Expo-av works very well with Android, but not iOS (in this case only .mp4 files are running).  can you help me?  Thanks

**Comment by aldobel** [comment]
As the title suggests, the <Video /> component of Expo-av works very well with Android, but not iOS (in this case only .mp4 files are running).  can you help me?  Thanks

**Comment by Simek** [comment]
Hi @aldobel, please re-create the issue and provide all the necessary information listed in the issue template.

It also would be nice if you can provide the minimum reproducible example or Snack which shows the issue/error/crash you are experiencing.
