### ISSUE TITLE
Getting rid of unneccessary permissions in AndroidManifest.xml

### ISSUE THREAD

**Issue by realtril** [expo/expo#15029]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by realtril** [comment]
This is what kind of permissions I have in `android/app/src/main/AndroidManifest.xml`

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.USE_FINGERPRINT" />
<uses-permission android:name="android.permission.VIBRATE" />
```

But for some of the reason in the build, in AndroidManifest.xml file ( `build/intermediates/merged_manifests/debug/AndroidManifest.xml `) I have this permissions:

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.USE_FINGERPRINT" />
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```
Trying to find a way how to get rid of:

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

**Comment by EvanBacon** [comment]
You can create a config plugin to remove the permissions via https://developer.android.com/studio/build/manage-manifests `tools:node="remove"` [example](https://github.com/expo/expo-cli/blob/9b98ca5974e9436c046ca42d00d7d90b18e3048f/packages/config-plugins/src/android/Permissions.ts#L26)
