### ISSUE TITLE
Android billing permission

### ISSUE THREAD

**Issue by Tismont** [expo/expo#15036]
### Summary

I want to add in app product in my android app but when i go to google console and I try to add in app purchase in my app It is telling me that i need to add the BILLING permission to my APK. I already added it there and uploaded to console but I still can not create the in app product because It is telling me that the billing permission is missing. I made the app in Expo. 
How can I fix this?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.12.11 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Here are my permissions from my AndroidManifest.xml "

```
  <uses-permission android:name="com.android.vending.BILLING"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by cruzach** [comment]
This is a place for bugs in the Expo SDK, not for general troubleshooting. For that, you should post on our [forums](https://forums.expo.dev/). I also recommend sharing the error message google sent you.
