### ISSUE TITLE
androidNavigationBar props in app.json not working

### ISSUE THREAD

**Issue by mwegener-com** [expo/expo#15030]
### Summary

As the title says, androidNavigationBar settings in app.json are not working in expo dev client.
The navigation bar remains default. 
It's working fine in expo go app.

Code:
```
"androidNavigationBar": {
			"barStyle": "dark-content",
			"backgroundColor": "#FFFFFF"
		},
```
<img width="402" alt="Bildschirmfoto 2021-11-03 um 17 58 59" src="https://user-images.githubusercontent.com/64470126/140129584-b6e9ecea-a160-4aad-bfd9-e4af35316fd3.png">

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

```json
{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~43.0.0",
    "expo-dev-client": "^0.6.3",
    "expo-status-bar": "~1.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.2",
    "react-native-web": "0.17.1",
    "expo-splash-screen": "~0.13.3",
    "expo-updates": "~0.10.5",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

### Environment

    Expo CLI 4.12.11 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.0.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.11
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- expo init test
- yarn add expo-dev-client
- add code from above to app.json
- expo run:android --device

**Comment by esamelson** [comment]
Hi @mwegener-com - thanks for the report. You're right, it appears that changing this value has no effect at runtime. I've opened a ticket for this internally; we'll try and get this fixed soon.

As a workaround, you can still change these values at build time. If your project is fully managed and you don't have an android folder on disk, then you just need to make a new build for the new settings in app.json to take effect. If you do have your android project on disk, you can edit the color in **android/app/src/main/res/values/colors.xml** and add or remove the line `<item name="android:windowLightNavigationBar">true</item>` in **android/app/src/main/res/values/styles.xml**, then make a new build.

**Comment by EvanBacon** [comment]
This is now resolved in SDK 44 with the addition of `expo-navigation-bar`. You must have `expo-navigation-bar` installed in your project in order to use this key in custom clients (`expo prebuild` will warn this).

**Comment by esamelson** [comment]
still planning to fix

**Comment by lukmccall** [comment]
I think that was fixed in the https://github.com/expo/expo/pull/16711.

**Comment by DavidFilipeG** [comment]
I have same problem
```javascript
"androidNavigationBar": {
      "visible": "immersive"
    },
```
When I'm developing the app (npx expo start) the navigation bar behaves as expected but when I build an apk it is always visible and I don't want that behavior.

**Comment by kanthi0802** [comment]
@DavidFilipeG `androidNavigationBar` is deprecated now. This [link](https://github.com/expo/fyi/blob/main/android-navigation-bar-visible-deprecated.md) has the recommended approach now
