### ISSUE TITLE
[expo-av][ios] Looping video crashing on iOS 15

### ISSUE THREAD

**Issue by reinhardholl** [expo/expo#15039]
### Summary

Our app uses expo-av to play a video on loop and also play a few sounds using `Audio.Sound` throughout this video. 

This has been working fine for the last few months but recently we have been noticing an error log and a few reports from customers that the videos would randomly stop and so would the sounds. Restarting the video works fine and continues like normal until it fails again.

We get the following error: 
`An unknown error occurred (-16156) - The AVPlayerItem instance has failed with the error code -11800 and domain "AVFoundationErrorDomain". | An unknown error occurred (-16156) - The AVPlayerItem instance has failed with the error code -11800 and domain "AVFoundationErrorDomain".
`

Any ideas would be super helpful! 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

bare

### Reproducible demo or steps to reproduce from a blank project

Looping video on iOS 15

**Comment by reinhardholl** [comment]
It turns out this was one of the audio clips that crashes the whole underlying media service. After receiving the `An unknown error occurred (-16156)` error, all other playing media fails with `The AVPlayerItem instance has failed with the error code -11819 and domain "AVFoundationErrorDomain"`, which to me means the underlying media service has crashed/stopped. 

We "preload" all our resources to the `cache` folder using `FileSystem.downloadAsync`. I managed to fix our crashes be removing the preload and streaming directly from web.. Like mentioned before, this has been working for months and only started giving issues on iOS 15. I wonder if something has changed regarding the `cache` folder?

**Comment by yolpsoftware** [comment]
@reinhardholl have you found out anything? I'm having the same problem - the audio service crashes and then I get `error code -11819`, and no audio is played anymore.

**Comment by reinhardholl** [comment]
@yolpsoftware nope, we still get it :(

**Comment by yolpsoftware** [comment]
Possibly related: #18125
