### ISSUE TITLE
App freezes in dev mode (not in prod mode, also not with remote debugging)

### ISSUE THREAD

**Issue by htrappmaier** [expo/expo#15035]
### Summary

app freezes WITHOUT remote debugging mode ...
It also doesn't freeze in production mode and with different older apps.
What I see is 
--> Error: EISDIR: illegal operation on a directory, read at Object.readSync (node:fs:723:3) <--
during debugging.
expo-sdk: 43, cli: 4.12.11, node: v16.13.0, npm: 7.15.0, expoGo: 2.22.2
IOS & Android

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

expo-sdk: 43, cli: 4.12.11, node: v16.13.0, npm: 7.15.0, expoGo: 2.22.2

### Environment

Expo CLI 4.12.11 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.15.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20200730.120504.0 - C:\Users\herma\AppData\Local\watchman\watchman.EXE
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ^43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

metro.config.js:
const { getDefaultConfig } = require("@expo/metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig(__dirname);
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer"),
      assetPlugins: ['expo-asset/tools/hashAssetFiles']  //notwendig, ansonsten keine BackButtons & weitere Assets in IOS
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();

**Comment by thalesog** [comment]
i'm having the same issue.

**Comment by TomasSestak** [comment]
same issue, but on mac - no custom client

new package.json:
{
	"scripts": {
		"start": "expo start",
		"android": "expo start --android",
		"ios": "expo start --ios",
		"web": "expo start --web",
		"eject": "expo eject"
	},
	"dependencies": {
		"@expo-google-fonts/fira-sans": "^0.1.0",
		"@expo/metro-config": "^0.1.72",
		"@ptomasroos/react-native-multi-slider": "https://github.com/ptomasroos/react-native-multi-slider",
		"@react-native-async-storage/async-storage": "^1.15.0",
		"@react-native-community/datetimepicker": "^3.5.2",
		"@react-native-community/hooks": "^2.6.0",
		"@react-native-community/masked-view": "^0.1.10",
		"@react-native-community/netinfo": "6.0.2",
		"@react-native-picker/picker": "2.1.0",
		"@react-navigation/bottom-tabs": "^5.11.11",
		"@react-navigation/native": "^5.9.4",
		"@react-navigation/stack": "^5.14.5",
		"@reduxjs/toolkit": "^1.6.2",
		"axios": "^0.24.0",
		"buffer": "^6.0.3",
		"date-fns": "^2.23.0",
		"dayjs": "^1.10.6",
		"expo": "^43.0.1",
		"expo-analytics-segment": "^11.0.3",
		"expo-app-loading": "^1.2.1",
		"expo-application": "^4.0.0",
		"expo-asset": "^8.4.3",
		"expo-av": "^10.1.3",
		"expo-blur": "^10.0.3",
		"expo-camera": "^12.0.3",
		"expo-clipboard": "^2.0.3",
		"expo-constants": "^12.1.3",
		"expo-crypto": "^10.0.3",
		"expo-device": "^4.0.3",
		"expo-document-picker": "^10.0.3",
		"expo-file-system": "^13.0.3",
		"expo-gl": "^11.0.3",
		"expo-haptics": "^11.0.3",
		"expo-image-picker": "^11.0.3",
		"expo-linear-gradient": "^10.0.3",
		"expo-local-authentication": "^12.0.1",
		"expo-secure-store": "^11.0.3",
		"expo-sharing": "^10.0.3",
		"expo-splash-screen": "^0.13.5",
		"expo-status-bar": "^1.1.0",
		"expo-updates": "^0.10.12",
		"just-clone": "^3.2.1",
		"lottie-react-native": "4.0.3",
		"query-string": "^7.0.1",
		"react": "^17.0.2",
		"react-dom": "^17.0.2",
		"react-hook-form": "^7.18.1",
		"react-native": "0.64.2",
		"react-native-collapsible": "^1.6.0",
		"react-native-confirmation-code-field": "^7.1.0",
		"react-native-dropdown-picker": "^5.2.3",
		"react-native-gesture-handler": "^1.10.2",
		"react-native-get-random-values": "^1.7.0",
		"react-native-keyboard-aware-scroll-view": "^0.9.4",
		"react-native-reanimated": "^2.2.0",
		"react-native-responsive-screen": "^1.4.2",
		"react-native-safe-area-context": "3.3.2",
		"react-native-screens": "~3.8.0",
		"react-native-signature-canvas": "^4.3.0",
		"react-native-snap-carousel": "^3.9.1",
		"react-native-svg": "12.1.1",
		"react-native-web": "^0.13.12",
		"react-native-webview": "11.13.0",
		"react-number-format": "^4.6.4",
		"react-redux": "^7.2.6",
		"rodnecislo": "^1.6.0",
		"sentry-expo": "^4.0.0",
		"styled-components": "^5.3.3",
		"styled-system": "^5.1.5",
		"uuid": "^8.3.2"
	},
	"devDependencies": {
		"@babel/core": "~7.9.0",
		"@types/": "react-native-community/hooks",
		"@types/node": "^15.12.1",
		"@types/react": "^17.0.34",
		"@types/react-native": "0.64.2",
		"@types/react-native-snap-carousel": "^3.8.3",
		"@types/react-redux": "^7.1.18",
		"@types/styled-components-react-native": "^5.1.2",
		"@types/styled-system": "^5.1.11",
		"@types/uuid": "^8.3.1",
		"babel-plugin-module-resolver": "^4.1.0",
		"prettier": "^2.3.2",
		"typescript": "^4.4.4"
	},
	"private": true
}



old working package.json:

{
	"scripts": {
		"start": "expo start",
		"android": "expo start --android",
		"ios": "expo start --ios",
		"web": "expo start --web",
		"eject": "expo eject"
	},
	"dependencies": {
		"@expo-google-fonts/fira-sans": "^0.1.0",
		"@expo/metro-config": "^0.1.72",
		"@ptomasroos/react-native-multi-slider": "https://github.com/ptomasroos/react-native-multi-slider",
		"@react-native-async-storage/async-storage": "~1.15.0",
		"@react-native-community/datetimepicker": "3.5.2",
		"@react-native-community/hooks": "^2.6.0",
		"@react-native-community/masked-view": "0.1.10",
		"@react-native-community/netinfo": "6.0.0",
		"@react-native-picker/picker": "1.16.1",
		"@react-navigation/bottom-tabs": "^5.11.11",
		"@react-navigation/native": "^5.9.4",
		"@react-navigation/stack": "^5.14.5",
		"@reduxjs/toolkit": "^1.6.2",
		"axios": "^0.21.1",
		"buffer": "^6.0.3",
		"date-fns": "^2.23.0",
		"dayjs": "^1.10.6",
		"expo": "^42.0.4",
		"expo-analytics-segment": "^11.0.3",
		"expo-app-loading": "1.1.2",
		"expo-application": "~3.2.0",
		"expo-asset": "~8.3.3",
		"expo-av": "~9.2.3",
		"expo-blur": "~9.0.3",
		"expo-camera": "~11.2.2",
		"expo-clipboard": "~1.1.0",
		"expo-constants": "~11.0.1",
		"expo-crypto": "~9.2.0",
		"expo-device": "~3.3.0",
		"expo-document-picker": "~9.2.4",
		"expo-file-system": "~11.1.3",
		"expo-gl": "~10.4.2",
		"expo-haptics": "~10.1.0",
		"expo-image-picker": "~10.2.2",
		"expo-linear-gradient": "~9.2.0",
		"expo-local-authentication": "~11.1.1",
		"expo-secure-store": "~10.2.0",
		"expo-sharing": "~9.2.1",
		"expo-splash-screen": "~0.11.2",
		"expo-status-bar": "~1.0.4",
		"expo-updates": "~0.8.2",
		"just-clone": "^3.2.1",
		"lottie-react-native": "4.0.2",
		"query-string": "^7.0.1",
		"react": "16.13.1",
		"react-dom": "16.13.1",
		"react-hook-form": "^7.11.1",
		"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
		"react-native-collapsible": "^1.6.0",
		"react-native-confirmation-code-field": "^7.1.0",
		"react-native-dropdown-picker": "^5.1.21",
		"react-native-gesture-handler": "~1.10.2",
		"react-native-get-random-values": "~1.7.0",
		"react-native-keyboard-aware-scroll-view": "^0.9.4",
		"react-native-reanimated": "~2.2.0",
		"react-native-responsive-screen": "^1.4.2",
		"react-native-safe-area-context": "3.2.0",
		"react-native-screens": "~3.4.0",
		"react-native-signature-canvas": "^4.3.0",
		"react-native-snap-carousel": "^3.9.1",
		"react-native-svg": "12.1.1",
		"react-native-web": "~0.13.12",
		"react-native-webview": "11.6.2",
		"react-number-format": "^4.6.4",
		"react-redux": "^7.2.5",
		"rodnecislo": "^1.6.0",
		"sentry-expo": "^4.0.0",
		"styled-components": "^5.3.0",
		"styled-system": "^5.1.5",
		"uuid": "^8.3.2"
	},
	"devDependencies": {
		"@babel/core": "~7.9.0",
		"@types/": "react-native-community/hooks",
		"@types/node": "^15.12.1",
		"@types/react": "~16.9.35",
		"@types/react-native": "~0.63.2",
		"@types/react-native-snap-carousel": "^3.8.3",
		"@types/react-redux": "^7.1.18",
		"@types/styled-components-react-native": "^5.1.1",
		"@types/styled-system": "^5.1.11",
		"@types/uuid": "^8.3.1",
		"babel-plugin-module-resolver": "^4.1.0",
		"prettier": "^2.3.2",
		"typescript": "^4.4.3"
	},
	"private": true
}

**Comment by Kudo** [comment]
hi there! we may need more information about this. is this happened to both on Expo Go Android v2.22.3 and Expo Go iOS v2.22.2? which is not happened to `expo build`, `expo run:ios`, `expo run:android`, and `eas build`.

**Comment by thalesog** [comment]
> hi there! we may need more information about this. is this happened to both on Expo Go Android v2.22.3 and Expo Go iOS v2.22.2? which is not happened to `expo build`, `expo run:ios`, `expo run:android`, and `eas build`.

Hi @Kudo, 
I'm running with `expo-dev-client` and EAS build, as my project uses custom modules.
let me know if i can provide something else to help

**Comment by htrappmaier** [comment]
Hi Kudo,
thx for your quick reply: Only in in development mode, IOS v2.22.2 as well as Android v2.22.3.
Build & eas are ok.

**Comment by brentvatne** [comment]
@thalesog - can you provide a reproducible example project that we can clone and run?

**Comment by frauke227** [comment]
I am having a very similar issue - the app freezes when starting after building JS bundle. I am on Android ExpoGo2.22.3, Cli: 4.12.11, node v16.7, npm: 8.1.2. 
For some reason, I cannot start remote debugging  - so I am not sure it would work then.

**Comment by htrappmaier** [comment]
pls see to reproduce: https://github.com/htrappmaier/FreezingError

**Comment by brentvatne** [comment]
@htrappmaier - can you share your yarn.lock or package-lock.json in that repository?

**Comment by brentvatne** [comment]
@htrappmaier - also, that repo includes *a lot* of dependencies and code that i suspect is unrelated to the problem. could you try narrowing it down a bit further? https://expo.fyi/manual-debugging

**Comment by ramiel1999** [comment]
Okay I have been battling with this for 5 hours and I guess I am into something. I am developing an app, and I have been using expo-cli version 4.12.8 I believe. I updated today to 4.12.11, and I am experiencing the same issue. App works in remote debug but freezes in expo go.

I was so frustrated to the point where I removed all dependencies and then installing them one by one until the app breaks. Here is what I found:

When the expo-cli initializes a new app. It installs uuid version 3.4.0 which can be seen in package-lock.json; however, I am alson using uuid in my project so I was doing what any other developer does. npm install --save uuid which installs the latest version: 8.3.2 and use it in my app as I wanted to. This  is where things break. I am not sure why expo-cli installs v3.4.0 and why it breaks when installing latest version. 

Try it for yourself by cloning your project, removing uuid from package.json and run your app. It should run fine but with uuid v3.4.0. Dont try to simply remove uuid from package json and running npm install. I tried and I guess because of some cache or something it doesnt work. Clone your project, remove uuid from package.json and npm install && npm start

Let me know if it fixes your issues, but still this shouldnt be a solution. I want to use latest version of uuid to use uuid.validate() method which is not available in v3.4.0

**Comment by brentvatne** [comment]
@ramiel1999 - can you try going back to expo-cli@4.12.11 and creating metro.config.js with the following contents:

```
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

module.exports = config;
```

after that, run `expo start` again and let me know if that resolves the issue. this would be very very helpful to know!

**Comment by ramiel1999** [comment]
what do you mean by going back to expo-cli@4.12.11? I am already on that version

**Comment by brentvatne** [comment]
@ramiel1999 - perfect, then stay on that version and try the above

**Comment by ramiel1999** [comment]
@brentvatne app is working fine after adding metro.config.js. May I ask what changes here? Do I need to do this for every project that uses uuid?

**Comment by brentvatne** [comment]
@ramiel1999 - can you do one more thing for me? delete metro.config.js that you just created, then install expo-cli@4.12.12 and try again

**Comment by htrappmaier** [comment]
@brentvatne - all right,  you can find the changes in the repo

**Comment by ramiel1999** [comment]
@brentvatne yes I updated to expo-cli@4.12.12 and it works fine without metro.config.js. Thank you

**Comment by brentvatne** [comment]
@ramiel1999 - i was able to reproduce with the uuid package like you suggested! https://github.com/brentvatne/uuidont

confirmed that expo-cli@4.12.12 and @expo/metro-config@0.2.8 resolve this!

@htrappmaier please update expo-cli and if you have @expo/metro-config@0.2.7 in your project then update it to @expo/metro-config@0.2.8

**Comment by EvanBacon** [comment]
Appears to be related to the controversial new Node.js functionality not working with Metro bundler as expected. https://github.com/nodejs/node/issues/33460

**Comment by htrappmaier** [comment]
@brentvatne - Good job, thank you for your speedy handling.
