### ISSUE TITLE
expo-splash-screen:  No native splash screen registered for given view controller

### ISSUE THREAD

**Issue by mwegener-com** [expo/expo#15031]
### Summary

I have problems with the expo-splash-screen.
I am working with the expo-dev-client.

When I add the expo-splash-screen module to my app, every time I launch it on iOS, I get the message "No native splash screen registered for given view controller". 
Partially this results in my content not being rendered, but the splash screen remains.

Unfortunately, I can't find the reason for this problem.
In a newly set up Expo managed project, the error does not occur.

I can rule out that it is due to my UI, because even if I just display a view + text in App.js, the error message appears.
I think that it is because of the combination of expo-splash-screen with another plugin.

Maybe someone can help me narrow down or find the error.
Best thanks

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.12.11 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.0.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.12.11
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- expo run:ios --device
- boot app

## Package.json

```json
"dependencies": {
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/checkbox": "^0.5.8",
    "@react-native-community/datetimepicker": "3.5.2",
    "@react-native-firebase/app": "^12.9.2",
    "@react-native-firebase/auth": "^12.9.0",
    "@react-native-firebase/firestore": "^12.9.0",
    "@react-native-firebase/storage": "^12.9.0",
    "@react-native-picker/picker": "2.1.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@types/lodash": "^4.14.176",
    "@types/react-redux": "^7.1.19",
    "expo": "^43.0.0",
    "expo-blur": "~10.0.3",
    "expo-dev-client": "~0.6.3",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.5",
    "lodash": "^4.17.21",
    "prop-types": "^15.7.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.2",
    "react-native-collapsible": "git://github.com/oblador/react-native-collapsible.git#reanimated",
    "react-native-dropdown-picker": "^5.1.27",
    "react-native-fast-image": "^8.5.11",
    "react-native-geocoding": "^0.5.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-crop-picker": "^0.36.4",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-maps": "0.28.0",
    "react-native-modal": "^13.0.0",
    "react-native-navigation-bar-color": "^2.0.1",
    "react-native-pager-view": "5.4.6",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-styled-text": "^1.1.1",
    "react-native-svg": "12.1.1",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-uuid": "^2.0.1",
    "react-native-web": "0.17.1",
    "react-navigation": "^4.4.4",
    "react-redux": "^7.2.5",
    "redux": "^4.1.1",
    "redux-thunk": "^2.3.0",
    "with-rn-image-crop-picker": "^0.2.0"
  },
```

**Comment by Kudo** [comment]
hi there! minimal reproducible examples are required for bug reports. please see https://stackoverflow.com/help/minimal-reproducible-example for more information on how to create one. once you share a minimal reproducible example, i'm happy to reopen it.
