### ISSUE TITLE
Cannot read property 'startObserving' of undefined in production builds

### ISSUE THREAD

**Issue by SergiOnGit** [expo/expo#15044]
### Summary

I installed expo-notifications. It works in debug mode, but after I build apk and install it in my phone app started crashing as soon as I open it.

I have firebase crashlytics installed and it caught the error.

Here is full error:

```
Fatal Exception: com.facebook.react.common.c
TypeError: Cannot read property 'startObserving' of undefined, js engine: hermes, stack: addListener@1:604167 setNotificationHandler@1:953996 anonymous@1:737225 loadModuleImplementation@1:83230 guardedLoadModule@1:82778 metroRequire@1:82406 anonymous@1:650112 loadModuleImplementation@1:83230 guardedLoadModule@1:82778 metroRequire@1:82406 anonymous@1:648490 loadModuleImplementation@1:83230 guardedLoadModule@1:82778 metroRequire@1:82406 anonymous@1:594394 loadModuleImplementation@1:83230 guardedLoadModule@1:82778 metroRequire@1:82406 anonymous@1:89604 loadModuleImplementation@1:83230 guardedLoadModule@1:82735 metroRequire@1:82406 global@1:81992
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.12.11 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0
        System Images: android-24 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ^43.0.1 => 43.0.1
      react: 17.0.2 => 17.0.2
      react-native: 0.66.2 => 0.66.2
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

I don't think this is about code. App crashes during startup before any react code loads, but works in debug.

**Comment by cruzach** [comment]
As we state in the issue template, bug reports without reproducible demos will be closed.
