### ISSUE TITLE
FileSystem downloadAsync appearing to download image but the root folder of URI returned is empty

### ISSUE THREAD

**Issue by dereknelson** [expo/expo#1504]
### Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: Not Found
  react: Not Found
  react-native: ^0.52.0 => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/prodigynelson-a7f3cb6e-a870-4487-aae4-0cbee1eba463.tar.gz

### Steps to Reproduce
Snack: https://snack.expo.io/rypVQTp_z

### Expected Behavior
I am trying to display an image that I downloaded to the cache, but using the URI that is returned by downloadAsync makes the image blank (I am passing it style props).

### Actual Behavior
Even though it says that the image was downloaded, I console log the contents of the folder that contains all my caches and it says it's empty: [screenshot 1](https://files.slack.com/files-pri/T04Q3JTLV-F9KLAL9SQ/image.png), [screenshot 2](https://files.slack.com/files-pri/T04Q3JTLV-F9KM2ACV8/image.png), [screenshots side by side](http://prntscr.com/inuurf) and the image component returns empty. 

### Reproducible Demo
See snack link

**Comment by brentvatne** [comment]
I changed the url from `https:metoo-assets.s3.amazonaws.com/static/media/avatars/3/photo_6B7NH7L.jpg` to `https://metoo-assets.s3.amazonaws.com/static/media/avatars/3/photo_6B7NH7L.jpg` and it worked for me

**Comment by machester4** [comment]
I had the same problem and the only **temporary solution** I found is to move the image to the gallery


` let {  uri  } = await FileSystem.downloadAsync(this.props.item.imgUrl, FileSystem.cacheDirectory + ${this.props.item}.jpg`); // **here github does not correctly represent the concatenation using ``**
```
const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);

if (status === 'granted') {

  CameraRoll.saveToCameraRoll(uri).then((uriGallery) => {
      //here you have the url of the gallery to be able to use it
  });

}
```

**Comment by prodigynelson** [comment]
@machester4 that's a decent workaround but I will be caching tens of images, I can't move all of those to the gallery

**Comment by nikki93** [comment]
@prodigynelson did you make sure to make the directory first (with https://docs.expo.io/versions/latest/sdk/filesystem.html#expofilesystemmakedirectoryasyncfileuri-options)? Also if you want to save the image for a while then `FileSystem.documentDirectory` works better than `FileSystem.cacheDirectory` (which may be cleared across restarts of the app).

**Comment by prodigynelson** [comment]
@nikki93 yes the directory was created, and I did not know that cacheDirectory may be cleared across restarts, I will switch to that

**Comment by prodigynelson** [comment]
@nikki93 here is the full code - I am using redux saga to dispatch actions that will cache each image.
Saga.js

    import { FileSystem } from 'expo';
    import { put, select, takeEvery, takeLatest, all, fork } from 'redux-saga/effects';
    import { createAction } from 'redux-actions';
    import * as ImageCache from './cache';

    const folder = `${FileSystem.documentDirectory}metoo-cache`;

    const getLoading = (state) => state.cache.loading;

    const fetch = function* ({ payload }) {
        var folderInfo = yield FileSystem.getInfoAsync(folder);
        if (!folderInfo.exists) yield FileSystem.makeDirectoryAsync(folder);
        const loading = yield select(getLoading);
        if (loading.includes(payload.uri)) {
            return;
        }

        const output = `${folder}/${payload.uri}`;
        console.log('folderPath',output)
        const localFile = yield FileSystem.getInfoAsync(output);
        if (localFile.exists) {
            yield put(ImageCache.actions.success({
                uri: payload.uri,
                local: localFile.uri,
            }));
            return;
        }
        yield put(ImageCache.actions.download(payload.uri));
        console.log('payload',payload)
    
        const downloaded = yield FileSystem.downloadAsync(payload.uri, output, { md5: true });
        console.log('downloaded',downloaded)

        folderInfo = yield FileSystem.readDirectoryAsync(folder);
        console.log('reading from', folder, 'folderInfo',folderInfo)


        yield put(ImageCache.actions.success({
            uri: payload.uri,
            local: { uri: downloaded.uri, md5: downloaded.md5 }
        }));
    };

SmartImage.js

    import React from 'react';
    import PropTypes from 'prop-types'
    import { bindActionCreators } from 'redux';
    import { connect } from 'react-redux';
    import { Image } from 'react-native';
    import { actions as ImageCacheAction } from '../../redux/cache';

    class NotDumbImage extends React.Component {
        static propTypes = {
            localUri: PropTypes.string,
            source: PropTypes.shape({
            uri: PropTypes.string.isRequired,
            }).isRequired,
            imageCacheAction: PropTypes.shape({
                fetch: PropTypes.func.isRequired,
            }).isRequired,
        };

        static defaultProps = {
            localUri: null,
        };

        componentWillMount() {
            this.props.imageCacheAction.fetch(this.props.source);
        }

        shouldComponentUpdate(nextProps) {
            return this.props.local !== nextProps.local;
        }
        
        getSource = () => {
            if (!this.props.local) return require('../../../assets/icons/loading-icon.png')
                 return { uri: this.props.local.uri };
         }
        
        render() {
            const source = this.getSource()
        
            console.log('this',this.props, 'source', source)
            return (
               <Image
                  style={[this.props.style, { borderColor: 'blue' }]}
                  source={{ uri: source.uri }}
                   />
            );
        }
    }

    export default connect(
            (state, props) => {
                const { loading, loaded } = state.cache;
                return {
                    loading: loading.includes(props.source.uri),
                    local: loaded[props.source.uri],
                };
            },
            (dispatch) => ({
                imageCacheAction: bindActionCreators(ImageCacheAction, dispatch)
            }),
       )(NotDumbImage);

Notice I console log 'source', to see that it is [indeed being passed the correct path to the localURI](https://user-images.githubusercontent.com/6868432/37116616-d11c2ed4-221c-11e8-885a-21bb242c09c3.png), however the [image is blank](https://user-images.githubusercontent.com/6868432/37116696-0ad2200c-221d-11e8-91d1-2ef9e94d76a6.png).

**Comment by nikki93** [comment]
@prodigynelson just to make sure -- `propTypes` and `defaultProps` here don't reflect the actual layout of your props that you're expecting at runtime right?

**Comment by prodigynelson** [comment]
@nikki93 correct, I found this caching example from https://medium.com/one-more-thing-studio/caching-your-images-on-react-native-with-expo-7bff361dbd54, you can ignore those

**Comment by nikki93** [comment]
@prodigynelson You may need to specify `width` and `height` in the `style` of the `Image`.

**Comment by prodigynelson** [comment]
@nikki93 I do, that is passed in as part of the style props.

**Comment by prodigynelson** [comment]
@nikki93 [it does exist](https://user-images.githubusercontent.com/6868432/37122679-7c9fe662-222f-11e8-83bc-5983b9c98bc5.png)

**Comment by nikki93** [comment]
Not the directory, but the path of the image.

**Comment by prodigynelson** [comment]
@nikki93 [it does not exist, ](https://user-images.githubusercontent.com/6868432/37122983-8d1a3a14-2230-11e8-8ffb-602e7a349a04.png) even though it was just downloaded

**Comment by brentvatne** [comment]
looks like if you use the full url as the filename that doesn't work, @nikki93 maybe we need to establish what acceptable filenames are and validate? https://snack.expo.io/r1dW-EROf works because i changed the filename we're saving to disk

**Comment by joshsiegl1** [comment]
@prodigynelson I'm seeing this same issue, did you ever find a solution?

**Comment by dereknelson** [comment]
@joshsiegl1 sorry I missed this, was combing through old issues and found it.
IIRC it was an issue with using sagas, I'm not sure if you're using it for image caching like I am but if you are I have [public gists of my caching component](https://gist.github.com/dereknelson/cfd249dea35014fef540f4203b96b6e3#file-notdumbimageactions-js) which has worked fine for me
