### ISSUE TITLE
[SDK43][iOS] initialProperties passed to RCTRootView are not set in production

### ISSUE THREAD

**Issue by Yonom** [expo/expo#15041]
### Summary

I have followed the setup steps for @react-native-firebase/messaging (Firebase Cloud Messaging) and setup a headless check as is described here.

https://rnfirebase.io/messaging/usage#background-application-state

Relevant code:

```objc
NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];

// Find the `RCTRootView` instance and update the `initialProperties` with your `appProperties` instance
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                             moduleName:@"nameOfYourApp"
                                             initialProperties:appProperties];
```

However, in production, isHeadless seems to be `null` instead of boolean. I suspect this is because `expo-updates` replaces the root view with its own and does not apply the initialProperties provided to the original root view.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
❯ expo diagnostics                    

  Expo CLI 4.12.11 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/Cellar/node@16/16.13.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/Cellar/node@16/16.13.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 24, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.11
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- `expo init -y`
- `yarn add @react-native-firebase/app @react-native-firebase/messaging
- Setup a firebase project and download the GoogleService-Info.plist  / google-services.json
- Setup the `@react-native-firebase/app` config plugin
- `expo prebuild`
- Apply the native changes described here https://rnfirebase.io/messaging/usage#background-application-state
- Add a console log in index.js:`console.log(isHeadless)`
- Build the app for production `expo run:ios --configuration Release` and look at the logs (in a tool like Flipper)

**Comment by Kudo** [comment]
@Yonom for this customization case, you may use the expo-updates manual setup. here is the guide to do it: https://docs.expo.dev/bare/installing-updates/#customizing-automatic-setup-for-ios

passing `initialProperties` makes sense IMO. as we are planning to enhance expo-update auto setup in next sdk. i'll try to cover this case in mind. thank you!

**Comment by eeynard** [comment]
@Yonom I'm curious, did you found a workaround to this problem ? I have the same exact one and it is pretty blocking for us since a simple push notification will wake up our app and activate background localisation for our users even if then didn't intentionally open the app.

**Comment by Yonom** [comment]
You can setup expo-updates manually (see Kudo's answer. That should fix the problem
