### ISSUE TITLE
iOS Development Client won't build with Hermes enabled on fresh install

### ISSUE THREAD

**Issue by sjusaitis** [expo/expo#15053]
### Summary

Expected behaviour: could initialise a fresh Expo project, enable Hermes engine, and build a custom development client for iOS.

Actual behaviour: the custom development client build crashes on `Compiling react-native Pods/React-Core » RuntimeAdapter.cpp` stating that `'hermes/hermes.h' file not found`

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "^0.6.3",
"expo-updates": "~0.10.5",

### Environment

 Expo CLI 4.12.11 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
      Watchman: 2021.08.23.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.11
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- `expo init` (selecting Managed > blank)

Then in project folder...
- Add `"jsEngine": "hermes"` to app.json
- `yarn add expo-dev-client`
- `expo run:ios`
... and the development client build fails with crash below

### Stacktrace (if a crash is involved)

› Compiling react-native Pods/React-Core » RuntimeAdapter.cpp

❌  (node_modules/react-native/ReactCommon/hermes/inspector/RuntimeAdapter.h:12:10)

  10 | #include <memory>
  11 | 
> 12 | #include <hermes/hermes.h>
     |          ^ 'hermes/hermes.h' file not found
  13 | 
  14 | #ifndef INSPECTOR_EXPORT
  15 | #ifdef _MSC_VER

**Comment by brentvatne** [comment]
i can't reproduce this. can you share your project? followed your provided steps and works as expected: https://github.com/brentvatne/sjus

**Comment by sjusaitis** [comment]
Thanks for looking into this.

- Here's my test project that fails: https://github.com/sjusaitis/expo-hermes-test
- Cloned your package, and failed in the same way for me (on `expo run:ios`)

Also tried:
- A blank `create-react-native-app` which failed in the same way (on `expo run:ios`)
- `react-native init` and switched on Hermes, which builds fine! 

Is it something to do with react-native version 0.64.2? As if I bump react-native version to the latest 0.66.2 in my test project, then `expo run:ios` builds without the error (haven't done this in the repo above, just on my local machine).
