### ISSUE TITLE
NotificationReceivedListener did not triggered in foreground on iOS 14

### ISSUE THREAD

**Issue by birdcatcher** [expo/expo#15060]
### Summary

Just run the code on ios device and press the button. Nothing happen. It is expected that the alert is showed and the msg is displayed in the app.

When using notification tool to send msg and if Expo Go is in the background, the notification is showed.

So the problem is when app is in the foreground.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

The expo docs push-notification sample snack does NOT work on ios when Expo Go on the foreground. It did NOT trigger the NotificationReceivedListener.

https://docs.expo.dev/push-notifications/overview/

### Reproducible demo or steps to reproduce from a blank project

Just run the code on ios device and press the button. Nothing happen.

When using notification tool to send msg and if Expo Go is in the background, the notification is showed.

So the problem is when app is in the foreground.

**Comment by cruzach** [comment]
The issue here isn't the listener, it's that push notifications do not work in projects running through Snack. You can use local notifications in snack, like this:
```
await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail! 📬",
      body: 'Here is the notification body',
      data: { data: 'goes here' },
    },
    trigger: { seconds: 2 },
  });
  ```
  
  But for push notifications, you'll need to run the project locally with expo-cli

**Comment by majirosstefan** [comment]
I am using 
     "expo-notifications": "0.14.1",
     "expo": "~44.0.0",
     "react-native": "0.64.3",
    
and even remote notifications (not local) are not working in foreground - Notifications.addNotificationReceivedListener is never called

**Comment by ToniIltanen** [comment]
Notifications.addNotificationReceivedListener I have the same issue, with expo 50. local scheduled notifications work, but not the ones sent through api. The listener never gets any messages
