### ISSUE TITLE
'Not authorized to use location services' error while using Location SDK with Linking

### ISSUE THREAD

**Issue by Xyzor** [expo/expo#1506]
### Environment

  OS: Linux 4.13
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

### Steps to Reproduce

1. Create an async function
2. In that function, call `Location.geocodeAsync(randomAddress)`
3. Try to open a link with `Linking.openURL()` right after the geocodeAsync method

### Expected Behavior

To be able to call this method multiple time.

### Actual Behavior

Works only the first time.

### Reproducible Demo

[Snack demo](https://snack.expo.io/@xyzor/location-service-unauthorization-bug-demo)

**Comment by dwkoogt** [comment]
I have the same problem with SDK 29.
Just upgraded as instructed in https://blog.expo.io/expo-sdk-v29-0-0-is-now-available-f001d77fadf

Not authorized to use location services
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:78:57 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:398:4 in __invokeCallback

**Comment by remcorakers** [comment]
Two days ago an update was pushed to the Expo client in the App Store that fixes this issue. See also #2042.
