### ISSUE TITLE
Updating to RN version 0.66 and migrating to expo modules from unimodules package 

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#15062]
### Summary

getting error:

ExpoModulesPackage
Couldn't get expo modules list.
java.lang.NoSuchMethodException: i.a.b.getPackageList 

<img width="1142" alt="Screenshot 2021-11-05 at 9 02 54 AM" src="https://user-images.githubusercontent.com/11364449/140454250-399a0525-4b85-4799-bed0-e845ef164c0c.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

0.43.0.1

### Environment

  Expo CLI 4.12.11 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.11 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: 43.0.1 => 43.0.1 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.1 => 0.66.1 
    npmGlobalPackages:
      expo-cli: 4.12.11
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- I uninstalled my previous unimodules package, removed exact changes which I made when installing unimodules using my git history. 

- created a new project with RN 0.66 and installed expo modules using `npx install-expo-modules`

- applied same changes to my project.

- Everything works well in debug mode, but when I am creating release apk. it's instantly crashing and build works fine in newly created project. certainly issue is related to my project but error coming in from module. Any idea why this is hapening?

**Comment by shubhamdeol** [comment]
@Kudo 
I am having this crash because I have proguard rules enabled. Is there any proguard config for expo core module?
Please let me know

**Comment by Kudo** [comment]
yes, i am fixing it. thank to let us know the issue.

**Comment by shubhamdeol** [comment]
@Kudo thanks. Take you time.
If you can suggest me some quick fix for now, that would be really great.

**Comment by shubhamdeol** [comment]
@Kudo  Thanks :)

**Comment by Kudo** [comment]
publish `expo@43.0.2` with the fix. please check if that works for you when you get a chance. thank you!
