### ISSUE TITLE
Excluding expo modules from package.json has no effect in bare workflow

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#15064]
### Summary

The bare workflow docs outline [steps for excluding Expo modules](https://docs.expo.dev/bare/installing-expo-modules/#excluding-specific-modules-from-autolinking) which I assumed would be good to thin out the binary a little bit and save some space.

However after excluding modules like expo-constants, I was able to log out functions from expo-constants on my iOS simulator, confirming that expo constants had never been excluded. I have not tested the other expo modules I excluded since I get the impression that the recommended key in package.json isn't actually doing anything.

 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
  Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.3.0 - /usr/local/bin/fish
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.3/bin/npm
      Watchman: 2021.09.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/admin/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.6 => 0.16.6
      expo: ^43.0.1 => 43.0.1
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.65.1 => 0.65.1
      react-native-web: ^0.16.3 => 0.16.5
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

In package.json:

```
"expo": {
    "autolinking": {
      "exclude": ["expo-application, expo-asset, expo-constants, expo-file-system, expo-font, expo-keep-awake"]
    }
  }
```

**Comment by byCedric** [comment]
Hi @shamilovtim, can you provide a repository for us to test with?

**Comment by Kudo** [comment]
after you update `package.json`, please make sure to remove `ios/Pods` and use `npx pod-install` to update Pods.

**Comment by brentvatne** [comment]
perhaps we should update docs with some information about this

**Comment by shamilovtim** [comment]
Could have sworn I deleted mods multiple times. I can check though.

**Comment by shamilovtim** [comment]
I looked and it's definitely linked in the lockfile, and I definitely deleted pods and pod installed multiple times to double check.

**Comment by shamilovtim** [comment]
<img width="1020" alt="Screen Shot 2021-11-05 at 2 50 18 PM" src="https://user-images.githubusercontent.com/3495974/140563313-5d0419c3-f306-416c-bf40-a349136661de.png">

**Comment by shamilovtim** [comment]
@brentvatne @Kudo did you see my screenshot?

**Comment by Kudo** [comment]
@shamilovtim i've just checked the example your shared. please double check your package.json

```diff
  "expo": {
    "autolinking": {
-     "exclude": ["expo-application, expo-asset, expo-constants, expo-file-system, expo-font, expo-keep-awake"]
+     "exclude": ["expo-application", "expo-asset", "expo-constants", "expo-file-system", "expo-font", "expo-keep-awake"]
    }
  }
```

**Comment by taylorkline** [comment]
Thank you for this thread. I was wondering why it was still in my `node_modules/`. I can confirm that it is removed from my `ios/Pods` after adding the appropriate `exclude` entry.

**Comment by Bilal-Txend** [comment]
Hy when i exclude the expo module from package json like this and after that when i install the node module again its still exist in it. anyone can help
"expo": {
    "autolinking": {
      "exclude": [
        "expo-keep-awake"
      ]
    }
  },
