### ISSUE TITLE
AuthSession Facebook Firebase throws “Cannot parse ID Token” after passing FacebookAuthProvider.credential(access_token)

### ISSUE THREAD

**Issue by mudiman** [expo/expo#15078]
### Summary

Implementated the exact same code using facebook example in link https://docs.expo.dev/guides/authentication/#facebook. 

It only provide access_token or code but not id token which is what firebase credential expects

`import * as React from 'react';
import * as WebBrowser from 'expo-web-browser';
import * as Facebook from 'expo-auth-session/providers/facebook';
import { ResponseType } from 'expo-auth-session';
import { initializeApp } from 'firebase/app';
import { getAuth, FacebookAuthProvider, signInWithCredential } from 'firebase/auth';
import { Button } from 'react-native';

// Initialize Firebase
initializeApp({
  /* Config */
});

WebBrowser.maybeCompleteAuthSession();

export default function App() {
  const [request, response, promptAsync] = Facebook.useAuthRequest({
    responseType: ResponseType.Token,
    clientId: '<YOUR FBID>',
  });

  React.useEffect(() => {
    if (response?.type === 'success') {
      const { access_token } = response.params;
      
      const auth = getAuth();
      const provider = new FacebookAuthProvider();
      const credential = provider.credential(access_token);
      // Sign in with the credential from the Facebook user.
      signInWithCredential(auth, credential);
    }
  }, [response]);

  return (
    <Button
      disabled={!request}
      title="Login"
      onPress={() => {
        promptAsync();
      }}
    />
  );
`}``

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

42.0.4

### Environment

Expo CLI 4.12.12 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.18.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - D:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    npmPackages:
      expo: ^42.0.4 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Press login button
You will be direct to authorization prompt of expo after exception Facebook login page will be shown
After accepting it  you are back to app with facebook access_token

{
  "authentication": TokenResponse {
    "accessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "expiresIn": "5140635",
    "idToken": undefined,
    "issuedAt": 1636256273,
    "refreshToken": undefined,
    "scope": undefined,
    "state": "iuKOG4RcLP",
    "tokenType": "bearer",
  },
  "error": null,
  "errorCode": null,
  "params": Object {
    "access_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "data_access_expiration_time": "1644032271",
    "exp://192.168.10.2:19000/--/expo-auth-session": "",
    "expires_in": "5140635",
    "state": "iuKOG4RcLP",
  },
  "type": "success",
  "url": "exp://192.168.10.2:19000/--/expo-auth-session#access_token=XXXXXXXXXXXXXXXXXXXXXXXXXX&data_access_expiration_time=1644032271&expires_in=5140635&state=iuKOG4RcLP",
}

**Comment by Lidorc145** [comment]
same issue. for me....
