### ISSUE TITLE
 Does Expo uses accelerometer by default in managed workflow and if it does, how can we disable it?

### ISSUE THREAD

**Issue by sardarwaseemjaved** [expo/expo#15072]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by sardarwaseemjaved** [comment]
- SDK Version: 41.0.0
- Platforms(Android/iOS/web/all): Android
- Add the appropriate “Tag” based on what Expo library you have a question on.
- “orientation”: “portrait”
![image](https://user-images.githubusercontent.com/25973338/140514919-034f39bd-41d5-445a-99c6-bea70a0764a7.png)
It seems like my production app is using accelerometer but I haven’t used it anywhere.
I am not using facebook ads or any other facebook related package. Can someone tell me if expo uses accelerometer by default? If it is being used by default then is there a way to disable it. Thanks

**Comment by brentvatne** [comment]
it does not
