### ISSUE TITLE
[SDK 43] Foreground service of Background location dissapears and App crashes

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#15081]
### Summary

Hello , i've been having trouble with background location crash and foreground service dissapearing from notification tray.

Testing on android 10 and 11 , on Redmi Phones

1 - Starting background location with the foreground service then killing the app will make the service dissapear .
2 - The App crashes at start if it was killed while background location is running : 

- open the APP.
- start background location .
-  close the app .
- wait for about 20 min 
- start the app .
it will crash .

The issues mentionned  happens in SDK 43 , 

in SDK42 the app doesn't crash but the foreground service dissapears and sometimes it appears again by itself .

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ~43.0.0 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

[backgroundLocationTest.zip](https://github.com/expo/expo/files/7492666/backgroundLocationTest.zip)

This is a simple demo : ,
- just build an apk with expo build or eas build , 
- start the app , allow permissions and click the button
- quit the app .
(issue 1) The foreground service dissapears .
- wait for about 20 or more minutes and try to start the app again .
(issue 2) the App will stuck at splash screen . then it will launch again if you close and start

**Comment by damiano216** [comment]
I have similar trouble. Have been using the expo getCurrentPositioAsync service for some time and it worked great. Yesterday out of nowhere it stopped working. Has something changed from your side expo team?

**Comment by khelifioussama** [comment]
Same Problem Here , app Stuck in splash screen Memory Problem

**Comment by Guuri11** [comment]
same here
