### ISSUE TITLE
Expo updates will cause iPad rotation to fail

### ISSUE THREAD

**Issue by zhigang1992** [expo/expo#15085]
### Summary

iPad rotation is wrong

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 12.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.1 - /usr/local/bin/npm
      Watchman: 2021.08.23.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

On brand new expo project,

run `expo run:ios --configuration Release -d` and select iPad

Expected behavior
![Screen Shot 2021-11-08 at 12 53 22 PM](https://user-images.githubusercontent.com/1057756/140686260-e96233c3-edc4-4a61-9ae0-233fe24fd4e5.png)
![Screen Shot 2021-11-08 at 12 53 24 PM](https://user-images.githubusercontent.com/1057756/140686262-37ac97b4-9d17-436e-8585-f4d948f8f573.png)
 
Actual behavior
![Screen Shot 2021-11-08 at 12 54 47 PM](https://user-images.githubusercontent.com/1057756/140686339-196c1222-6c32-45a3-8509-489be7d8a8c6.png)
![Screen Shot 2021-11-08 at 12 54 50 PM](https://user-images.githubusercontent.com/1057756/140686344-3a17a084-8bd1-4799-9450-785b0a8e8d96.png)

If we set `EXUpdatesAutoSetup` to false in `Expo.plist` then it works correctly

If we follow https://docs.expo.dev/bare/installing-updates/ custom setup, it will also work correctly

**Comment by sjusaitis** [comment]
I am also experiencing the same issue on iPhone. It only happens on Release builds (not Debug). Setting `EXUpdatesAutoSetup` to false fixed it for me as well.

**Comment by Kudo** [comment]
thanks for reporting this issue. i am closing this as duplicated of #14967. will follow up on that thread.
