### ISSUE TITLE
Expo media library corrupted error when calling MediaLibrary.addAssetsToAlbumAsync

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#15094]
### Summary

I am using expo-media-library V.13.0.3 i.e latest with expo core module in my bare workflow.
I tried to debug the error but could not understand the native side code much.

Please check attached screenshot. 

Path in ```fileInAlbum``` looks like a path to file. then why its falling into ```!fileInAlbum.isFile()``` .

<img width="1283" alt="Screenshot 2021-11-08 at 7 39 16 PM" src="https://user-images.githubusercontent.com/11364449/140756677-e98ef856-6c96-4b9d-86f4-f5fe2167d79d.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

0.43.0.1

### Environment

 Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.11 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.1 => 43.0.1 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.1 => 0.66.1 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- Create a new project 
- add expo modules to it
- install latest version of expo package, expo media library, expo camera, expo-image-picker
- tried taking picture and storing it to user's download's folder. 

Link to reproducible example.
- https://github.com/shubhamdeol/test-expo-core

This is giving error(Expo media library corrupted) at-least on my device, I am on android 10.

**Comment by shubhamdeol** [comment]
Update:
When I remove this check ```!fileInAlbum.isFile()``` files are getting saved to my downloads folder. 
Please let me know, why is this happening.

**Comment by shubhamdeol** [comment]
The file ```fileInAlbum``` referring to does not exist in my phone, I have no idea from where it is picking up this file.

**Comment by shubhamdeol** [comment]
any update on this?

**Comment by aiahsan** [comment]
Any Update?

**Comment by channyeintun** [comment]
The issue still exists.
I am experiencing the same situation.
Any one got the solution?

**Comment by mudassir-rafiq-007** [comment]
You need to delete your Expo Go/Expo Dev Client app and then restart your mobile/device. This fixed this issue for me.
