### ISSUE TITLE
Error while updating property 'url' of a view managed by: ExponenetVideo

### ISSUE THREAD

**Issue by faustoct** [expo/expo#1509]
My env
npm 4.6.1
Exp 49.2.2
Expo 42.2.2
react-native-cli 2.0.1
react-native 0.50.3

```
Trying to use Video tag suddenly got the error: **Error while updating property 'url' of a view managed by: ExponenetVideo**

null

Failed resolution of: Lcom/google/android/expoplayer2/trackselection/AdaptiveVideoTrackSelection$Factory;

Didn't find class
"com.google.android.exoplayer2.trackselection.AdaptiveVideoTrackSelection$Factory" on path: DexPathList[[zip file "/data/app/com.x-1/base.apk"], nativeLibraryDirectories=[/data/app/com.x-1/lib/arm, /data/app/com.x-1/base.apk!/lib/armeabi-v7a, /system/lib, /vender/lib]]
```

Suddenly it started to happen how can I solve it ?

**Comment by nicknovitski** [comment]
😟 Well that's no good. It does look like [that class was recently renamed](https://github.com/google/ExoPlayer/commit/ce5c0c18f952caa19b863345252fd267804d7e83)...

The latest release of exp is 50.0.5, could you upgrade and see if the problem stays around?

**Comment by esamelson** [comment]
Closing due to a lack of activity. If you're still experiencing this issue, please open a new ticket and let us know how to reproduce it. Thanks!!

**Comment by puja1234** [comment]
Getting same issue :( . Expo sdk 23.0.0 used . Please help
