### ISSUE TITLE
Uncatchable exception causes app crash when using ImageManipulator manipulateAsync() crop with invalid parameters on SDK 42 and 43

### ISSUE THREAD

**Issue by swingthrough** [expo/expo#15098]
### Summary

When using `crop` in `ImageManipulator.manipulateAsync()` and passing invalid parameters, meaning the crop rectangle is out of bounds of the original image, app crashes and the underlying exception is not caught via `try/catch` block, and the app crashes without feedback.
I was able to notice in device logs through `adb logcat` command that there was a java exception related to image manipulator:
`Caused by: java.lang.IllegalArgumentException: Invalid crop options have been passed. Please make sure the requested crop rectangle is inside source image.`
This happens both for SDK 42 and 43.
However on SDK 41 the exception is properly caught via the `catch` clause.

Here are the versions of ImageManipulator that are installed on specific SDKs when running `expo install expo-image-manipulator`:
- SDK 41: "expo-image-manipulator": "~9.1.0" -> exception caught properly
- SDK 42: "expo-image-manipulator": "~9.2.2" -> not caught, app crashes
- SDK 43: "expo-image-manipulator": "~10.1.2" -> not caught, app crashes

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42 and 43

### Environment

Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.3.0/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
      Watchman: 2021.08.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 31.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 23.0.7599858
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Here is a snack where I experimented with it:

https://snack.expo.dev/@swingthrough/imagemanipulator-crop-bug---uncatchable-exception

Both on SDK 42 and 43 the behavior of the snack is as follows:
- Pick a random image from gallery
- Resize the image to 42x42,
- then I try to crop with dimensions 44x44, that's when the app crashes.

However, if you change SDK to 41, the exception is caught and you can see it in output in the console.

Those extra console logs after resizing are due to another bug that happens with the version of ImageManipulator that comes with SDK 42, where manipulation result contains incorrect height (just the resulting `height` property, the image is resized correctly) - this does not happen with the version that comes with SDK 41 or SDK 43, but that's for another issue.

**Comment by swingthrough** [comment]
I've been looking into this further and what I found is that this issue was introduced when expo-image-manipulator code was converted from Java to Kotlin - PR #13231

If you look at the [changed files](https://github.com/expo/expo/pull/13231/files#), you can see in the deleted [`ImageManipulatorModule.java`](https://github.com/expo/expo/blob/6508aa015667225b78d2a0bbbf1290460b82658f/packages/expo-image-manipulator/android/src/main/java/expo/modules/imagemanipulator/ImageManipulatorModule.java#L133), the method [`processBitmapWithActions()`](https://github.com/expo/expo/blob/6508aa015667225b78d2a0bbbf1290460b82658f/packages/expo-image-manipulator/android/src/main/java/expo/modules/imagemanipulator/ImageManipulatorModule.java#L125) had a dedicated `try/catch` block on line 134 for handling the crop action.

This is how the actions inside `processBitmapWithActions()` were iterated:
```java
for (Action action : actions) {
  if (action.getResize() != null) {
    bitmap = resizeBitmap(bitmap, action.getResize());
  } else if (action.getRotate() != null) {
    bitmap = rotateBitmap(bitmap, action.getRotate());
  } else if (action.getFlip() != null) {
    bitmap = flipBitmap(bitmap, action.getFlip());
  } else if (action.getCrop() != null) {
    try {
      bitmap = cropBitmap(bitmap, action.getCrop());
    } catch (IllegalArgumentException e) {
      promise.reject(ERROR_TAG + "_CROP_DATA", e);
      return;
    }
  }
}
```

The [`cropBitmap()`](https://github.com/expo/expo/blob/6508aa015667225b78d2a0bbbf1290460b82658f/packages/expo-image-manipulator/android/src/main/java/expo/modules/imagemanipulator/ImageManipulatorModule.java#L120) method explicitly throws `IllegalArgumentException` if the provided parameters are invalid.


However in the new `ImageManipulatorModule.kt` there is a method [`runActions()`](https://github.com/expo/expo/blob/7f4450a5df5acd0cf106e07136e369473caba04d/packages/expo-image-manipulator/android/src/main/java/expo/modules/imagemanipulator/ImageManipulatorModule.kt#L62), which iterates the actions like this:

```kotlin
private fun runActions(bitmap: Bitmap, actions: Actions, saveOptions: SaveOptions, promise: Promise) {
    val resultBitmap = actions.actions.fold(bitmap, { acc, action -> action.run(acc) })
// ...
```

Actions now have separate classes extending interface [`Action`](https://github.com/expo/expo/blob/7f4450a5df5acd0cf106e07136e369473caba04d/packages/expo-image-manipulator/android/src/main/java/expo/modules/imagemanipulator/actions/Action.kt), which provides the `run()` method. 

Inside of [`CropAction.kt`](https://github.com/expo/expo/blob/7f4450a5df5acd0cf106e07136e369473caba04d/packages/expo-image-manipulator/android/src/main/java/expo/modules/imagemanipulator/actions/CropAction.kt) you can see this part:

```kotlin
override fun run(bitmap: Bitmap): Bitmap {
    require(
      originX <= bitmap.width &&
        originY <= bitmap.height &&
        originX + width <= bitmap.width &&
        originY + height <= bitmap.height
    ) { "Invalid crop options have been passed. Please make sure the requested crop rectangle is inside source image." }
    return Bitmap.createBitmap(bitmap, originX, originY, width, height)
  }
```
 
If the result of [`require()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html) is false, it will throw `IllegalArgumentException`.

However the exception is not handled anywhere.

This is my first time looking into Kotlin code, so I have no idea how it could be handled nicely here, as `CropAction` does not have access to the promise so it could reject it. Neither is there a property to check specifically for crop action as it was done previously in the Java version with `action.getCrop() != null`. Maybe with some reflection of the class type, but that doesn't feel right.

For my current purposes I just did a quick dirty fix via [patch-package](https://www.npmjs.com/package/patch-package) and wrapped the whole code of `runActions` method with `try/catch`, rejecting the promise in case the Exception is thrown.
Expo Go as well as build via `expo build:android` ignores this patch so I used EAS Build and tried both:
-  a standalone `apk` build
-  custom development client build via [`expo-dev-client`](https://docs.expo.dev/clients/getting-started/) and then run `expo start --dev-client`

It works on both, app no longer crashes, and the exception is now propagated to JS where I can handle it. Even if I don't handle it, apk build does not crash anymore (it did before the patch) and running the app on dev client shows me a Warning `Possible Unhandled Promise Rejection...`, instead of crashing the whole client.

**Comment by swingthrough** [comment]
One other thing that comes to mind, shouldn't there be some kind of top level exception handler in Expo Go, so in case there is buggy native code that does not handle the exception, it wouldn't crash the Expo Go client without any feedback?

I don't know the inner workings of Expo Go and whether this would be possible at least for expo modules, but in case it would, would it also be possible for `expo-dev-client` where for example I would add some extra native libraries that expo doesn't support, and they would throw an exception, it would not crash the client?

**Comment by neilco** [comment]
This is for anyone that comes across this particular issue: I found that the bitmap passed to the CropAction was rotated by 90° and it was causing the [pre-condition](https://github.com/expo/expo/blob/dea87522e78893ff20ad3ffbf44ae62cec276d65/packages/expo-image-manipulator/android/src/main/java/expo/modules/imagemanipulator/actions/CropAction.kt#L12) to fail. Ideally, this exception should be caught by `runActions` and the Promise rejected, rather than fatally crashing. 

As a workaround, try flipping the origin x & y coordinates and the width & height in your crop config.

**Comment by pke** [comment]
The crop action could also flip the values itself, couldn't it?

Anyway it should protect all calls of actions with a try/catch.

**Comment by duressaJemal** [comment]
I am still having this issue with sdk 49. and is there a way to know which parameters values are invalid.

**Comment by ClaytonIsWorking** [comment]
bump
