### ISSUE TITLE
exp convert repeats prompt for project description on every keypress

### ISSUE THREAD

**Issue by veswill3** [expo/expo#151]
I just coverted a react native project to expo using `exp convert`. When it asked for a project description, it repeated the prompt after every keypress I made. It still seems to have worked, it was just odd.

I was going to post this issue at https://github.com/expo/exp/issues/new, but it told me to post it here, so I hope that is appropriate.

**Comment by skevy** [comment]
cc @brentvatne

**Comment by skevy** [comment]
@veswill3 evidently, we're going to deprecate this feature in the next release of `exp`, so I'm going to head and close this. Thanks so much for reporting!
