### ISSUE TITLE
compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by africanfruit** [expo/expo#15101]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by byCedric** [comment]
Hi @africanfruit, unfortunately I'm not sure how we can help. With the error message alone, we can't do much. If you think this is an issue in Expo, please open a new bug report with all the information we ask you. Only that way, we are able to take a look.

**Comment by dnovacik** [comment]
Sorry to revive this, but in case this happens to anyone else, make sure you have the right sdk version installed - the same as is in the android/build.gradle

**Comment by keithdmoore** [comment]
For me, I had to add: jcenter() to the repositories in build.gradle
