### ISSUE TITLE
Firebase Analytics not working on web even with Firebase installed

### ISSUE THREAD

**Issue by jojenki** [expo/expo#15105]
### Summary

I followed the documentation for getting Firebase Analytics running[1], which works for Android but not for web. I have installed firebase@8.2.3 per the comment in [2] but am still receiving the error when my app loads on web.

[1] https://docs.expo.io/versions/latest/sdk/firebase-analytics/#installation
[2] https://github.com/expo/expo-cli/issues/3066#issuecomment-800589530

### Environment

  Expo CLI 4.3.0 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 15.4.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ^0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Firefox 86.0.1 (64-bit)

### Error output

Unhandled Rejection (Error): Firebase JS Analytics SDK is not available: Firebase JS SDK is not installed: firebase.apps is undefined

### Reproducible demo or steps to reproduce from a blank project

This gives me a similar error, although it's complaining about 'firebase.analytics' is not a function as opposed to 'firebase.apps':

```
expo init
Name: firebase-test
Template: tabs (TypeScript)
cd firebase-test
npm install firebase@8.2.3
expo install expo-firebase-analytics
```

Update `firebase-test/navigation/index.tsx`'s `Navigation` function to be:

```
  // The initial route name is needed in multiple places, so set it once to prevent it from getting
  // out of sync.
  const INITIAL_ROUTE_NAME = "Root";

  // Keep track of the current state and, when it changes, record it.
  const [ currRoute, setCurrRoute ] = React.useState(INITIAL_ROUTE_NAME);
  React.useEffect(() => {
    if (currRoute) {
      Analytics.setCurrentScreen(currRoute);
    }
  }, [ currRoute ]);
  // Helper method to recursively find the current active route.
  // @ts-ignore
  const getActiveRouteName = (navigationState) => {
    if (!navigationState) return undefined;
    const route = navigationState.routes[navigationState.index];
    // Parse the nested navigators
    if (route.state) return getActiveRouteName(route.state);
    return route.name;
  }

  return (
    <NavigationContainer
      linking={LinkingConfiguration}
      theme={colorScheme === 'dark' ? DarkTheme : DefaultTheme}
      onStateChange={state => {
        setCurrRoute(getActiveRouteName(state) || currRoute);
      }}>
      <RootNavigator />
    </NavigationContainer>
  );
```

Finally, run `expo start` and open it in a web browser.

I wonder if this failure is because I'm not doing the rest of the install in this example, e.g. updating app.json with my Firebase secrets and adding my google-services.json file. I am doing that in my real project; I'm just not doing it here for this example because I don't know how to fake that and am not going to share those secrets publicly.

**Comment by LinusU** [comment]
I ran into this issue, and fixed it by upgrading like so:

```diff
-     "firebase": "8.2.3",
+     "firebase": "^9.9.1",
```

It was pinned at 8.2.3 because that is what Expo used to enforce...

> As of SDK 43, the Expo SDK no longer enforces or recommends any specific version of Firebase to use in your app.
