### ISSUE TITLE
[expo-screen-orientation] lockAsync(OrientationLock.LANDSCAPE) locks only one landscape direction

### ISSUE THREAD

**Issue by justblender** [expo/expo#15107]
### Summary

`ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE)` doesn't allow using either landscape directions and only locks you into `LANDSCAPE_LEFT` on an iOS device (haven't tested this for Android). 

I've tried to mitigate this through `ScreenOrientation.lockPlatformAsync()` by passing both orientations for iOS, but it still doesn't seem to change anything around.

I did find this [workaround](https://ossgit.org/jellyfin/jellyfin-expo/src/commit/cdc0de2ff7367aec0a4b803f9f5278cfc019497e/screens/HomeScreen.js#L164) on the Internet, but, as usual, this didn't play out too well.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /opt/homebrew/opt/node@14/bin/node
      npm: 6.14.14 - /opt/homebrew/opt/node@14/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.1 => 43.0.1 
      react: 17.0.2 => 17.0.2 
      react-native: 0.64.2 => 0.64.2 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Snack demo: https://snack.expo.dev/2vsun_3r6

**Comment by byCedric** [comment]
Hi @justblender! I can't seem to reproduce this issue on my iPhone 12 (iOS 15.0.2). Is it possible that there were older locks (or a system-wide lock) active when testing this?

**Comment by justblender** [comment]
Oh my god, I'm an idiot. 

Completely forgot to mention that I've had a system-wide lock enabled, but due to the fact that I've only recently switched to an iOS device I thought that iOS behaviour would be similar to Android, and thus would mirror device orientation in landscape, ignoring locks completely (see YouTube app for an example). It doesn't. 

Shouldn't have made this issue at 4 AM. 😅 
Sorry for wasting your time, closing this now.
