### ISSUE TITLE
Expo.Util.reload() does not load the latest js version (Android)

### ISSUE THREAD

**Issue by mattosborn** [expo/expo#1510]
The [docs](https://docs.expo.io/versions/latest/sdk/util.html#expoutilreload) for `Expo.Util.reload()` state:
`This will fetch and load the newest available JS supported by the device’s Expo environment.`

This is incorrect. If you call `reload` after a publish then the update will only be fetched in the background on reload. Calling it a second time will load the new version, assuming it is already fetched. 

### Environment

appOwnership: standalone
OS: Android 25
sdkVersion: 25.0.0

### Steps to Reproduce

1. Open app
1. Publish new js version
1. Call `Expo.Util.reload()` 
1. App will load into the same (old) version
1. Call `Expo.Util.reload()` a second time
1. App will load into the new version

### Expected Behavior

According to the docs the app should load the new js version on the first reload.

### Actual Behavior

App fetches on first reload and only loads the new version on the second reload

### Notes

This makes it impossible to create a good UX for pushing updates to devices because:
- An update requires 2 app restarts
- There is no way to reliably block between the first and second restart

The closest I can get is:
1. Poll the manifest url (`https://expo.io/<username</<project>/index.exp?sdkVersion=<sdk_ver>&release-channel=<release_channel>`) to see if a new version is available and present a restart option when one is available
1. Manually check the manifest url on load
1. If a new version is available then block and wait for the [newVersion event](https://docs.expo.io/versions/latest/sdk/util.html#expoutiladdnewversionlistenerexperimentallistener).
1. `reload` on the newVersion event.

But this could lead to a dead-end state as there is no guarantee the `newVersion` event will ever fire.

Ideally there would be a method to force the check for a new version and fetch it if there is one. This would allow for better UX patterns - either automatic or user initiated update fetching followed by a single app restart.

**Comment by esamelson** [comment]
Hey @mattosborn - last week we published a minor update to Android which should actually fix this issue. If you update your Expo client to 2.3.2 (or make a new build of a standalone app), reload should load the new version right away. Let me know if you try that and it still doesn't work.

**Comment by appjitsu** [comment]
Is there a way to detect new JS versions published through the XDE and then automagically restart the app? Or maybe give the user the option to restart?

**Comment by ianmartorell** [comment]
It seems there'll be something via Expo.Updates on sdk26, see [here](https://expo.canny.io/feature-requests/p/add-a-exposync-api-to-manually-trigger-app-refresh-when-available).

**Comment by esamelson** [comment]
Hi @appjitsu - I responded to your other question [here](https://github.com/expo/expo/issues/1122). In the future, please post questions like this to our [forums](https://forums.expo.io/) instead! That will help other people with the same question find an answer :)

**Comment by esamelson** [comment]
Also, this issue is obsolete as of SDK 26, as `Updates.reload` and `Util.reload` (deprecated) will follow whatever `updates` configuration you have in app.json. See [here](https://docs.expo.io/versions/latest/guides/configuring-ota-updates) for more details.

Going to close this for now. Feel free to open a new issue for post on the forums if there are any questions about the new API.
