### ISSUE TITLE
Unable to integrate Realm DB using Expo-Dev-Client.

### ISSUE THREAD

**Issue by vipinjoshiMeta** [expo/expo#15111]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by vipinjoshiMeta** [comment]
I'm trying to Integrate Realm DB with expo using expo-dev-client.
I've followed all the steps correctly as its written on expo docs [ to integrate a react-native package into an expo project]
& its working fine for at some points.

I can be able to insert data on db.
but while reading data from db its sending me back a list of empty objects.

Below my code snippets

### DATABASE-HELPER FILE : - 
`import Realm from "realm";

export const STATE_DATA_SCHEMA = "State_List";

export const StateSchema = {
    name: STATE_DATA_SCHEMA,
    primaryKey: "id",
    properties: {
        id: "int",
        name: "string"
    }
};

/**
 * Setting database options for Realm.
 * This function defines the path, schema version and all sub schemas (defined above) that needs to be included in the current Realm instance.
 */
const databaseOptions = {
    path: "testDB.realm",
    schema: [
        StateSchema,
    ],
    schemaVersion: 1,
    deleteRealmIfMigrationNeeded: true
}

// Insertion working fine.
export const insertStates = (states): Promise =>
    new Promise(async (resolve, reject) => {
        Realm.open(databaseOptions).then(async realm => {
            realm.write(async () => {
                states.forEach(element => {
                    realm.create(STATE_DATA_SCHEMA, element, true)
                })
                resolve(states)
            })
        }).catch(error => {
            console.log('Schema_Helpers.js insertStates error  --> ', error)
            reject(error)
        })
    });

// here realm.objects returning empty objects.
export const getStates = (): Promise =>
    new Promise(async (resolve, reject) => {
        Realm.open(databaseOptions).then(realm => {
            let allStates = realm.objects(STATE_DATA_SCHEMA);
            // let stateList: [] = allStates.sorted('name', false)

            console.log(typeof allStates)

            console.log(JSON.stringify({...allStates}))

            console.log('[0] =', JSON.stringify({...allStates["0"]}))

            console.log('ArrayFrom =', JSON.parse(JSON.stringify(Array.from(allStates))))

            // console.log(JSON.stringify(allStates))
            // resolve(stateList)
            resolve([])
        }).catch(error => {
            console.log('Schema_Helpers.js getAllStates error  --> ', error)
            reject(error)
        })
    });

/**
 * This line actually creates a realm object that will have all the schemas as per our definitions.
 */
export default new Realm(databaseOptions)`

### This is the Response I'm getting

object
{"0":{},"1":{},"2":{}}
[0] = {}
ArrayFrom = Array [
  Object {},
  Object {},
  Object {},
]

Thanks

**Comment by themakerman** [comment]
Hey @EvanBacon @brentvatne possible if you guys can help us out on this? or maybe point us to someone?

**Comment by tcdavis** [comment]
Please fill out the issue templates to give us the information we would need to help you.
We're not experts on the Realm API and it sounds like you have been able to install the module successfully, so the Realm team or community would be more likely to assist you.

**Comment by chinamcafee** [comment]
@vipinjoshiMeta  I have the same problem: https://github.com/expo/expo/issues/15303
Have you resovle it already?
Any help is appreciated

**Comment by vipinjoshiMeta** [comment]
@chinamcafee can you share your package.json

**Comment by chinamcafee** [comment]
> 

I found that I use react-native-reanimated 2.x in my package.json, when I use react-native-reanimated 1.x, realm can works well on Android devices. It seems because realm does not yet support Hermes.
Thanks a lot.

More infos:
https://github.com/realm/realm-js/issues/3710
