### ISSUE TITLE
Question about expo and static assets

### ISSUE THREAD

**Issue by marcosmartinez7** [expo/expo#1511]
Hi,

im developing a react native application using expo 23

im using exp build:android to publish the project to a expo account

the question is, when i run the application (scanning the QR code with the expo client), how does the expo server handle the static assets? 

for example, if i have a background image in a resources/img/background.png in my application, and i use it in one of my components like:

> <ImageBackground resizeMode='cover' source={require('resources/img/background.png')} 
>      {someContent} 
> </ImageBackground>

it is garanteed that when the expo client (the ios/android application of Expo) retrieves the app, there will be no changes in the expo server? (source code or something that will fire a re-bundle of my application) 

thanks in advance

**Comment by tcdavis** [comment]
I'm not sure I understand your question, could you try reframing it?

`exp build` produces an application you can submit to the app stores that can include bundled copies of your assets so the application can run without an internet connection.
`exp publish` rebundles & updates the js for your app logic along with any assets, which will then be available to previously built versions of your app.

if you don't republish, nothing about your built app will change.

**Comment by marcosmartinez7** [comment]
When i use the expo client like: exp start i create a tunnel between my expo client (expo app in my smartphone) and my computer

if i make a change in the source code, then the javascript bundle with be rebuilded, and i can see that in the console of my terminal of exp in my computer

when i publish a project to https://expo.io/@someAccount and i scan the QR code from my client, i assume that the process is similar..

but im experimenting diferrent behaviours between using an app published in https://expo.io/@someAccount and running locally 

for example, assets are rendered slower, and in some situations the app crashes (tunnel between my expo app client and the expo server times out?) 

is there a way to get a log of what is happening behind when i publish a project and i make it public? 

if the question is still not clear please let me know

kind regards

**Comment by marcosmartinez7** [comment]
So i have read a little and do some test and i want to reformulate my question. 

The thing is that in react native the images are loaded in another thread, so is common that if you have a background image the content of the component renders before the background image, and you see the "standard" white background for a while.

some people said that in a release  (ipa, apk) the files are boundle so you dont have the problem of expo getting the images from HTTP request to the expo server, so the delay isnt visible.

because i want to show my application on expo i have found this:

>         await  Expo.Asset.fromModule(require('../../design/img/main-bg.jpg')).downloadAsync();

extracted from here: https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets.html

and after that, downloading the images in my splash screen then i didnt have the problem described before

so .. the question is, im ok with dowloading images from expo server but, im putting lines of code that are not necessary in a release right? 

i mean, the line of code:        

>  await  Expo.Asset.fromModule(require('../../design/img/main-bg.jpg')).downloadAsync();

is not required if i just made an .ipa and use just <Image source ={require('....')}>

so.. how does expo, when turns the JS code into java/objective-c process that lines?

what does expo does with the Expo module?

kind regards

**Comment by janicduplessis** [comment]
Hi @marcosmartinez7 

Assets in Expo are NOT bundled by default, even in standalone apps (exp build ipa/apk), and are always downloaded from the network.

Like you mentioned you can use Asset.downloadAsync to preload some assets but they will still be downloaded from network in standalone apps.

A somewhat better alternative is to use [Bundled Assets](https://docs.expo.io/versions/latest/guides/offline-support.html#bundle-your-assets-inside-your-standalone-binary) (SDK 24+). You can specify a glob pattern in your manifest and all assets that match it will be included in your ipa/apk when you run exp build. Note that this solution doesn't work in the expo client though since we cannot bundle assets for every applications.

**Comment by marcosmartinez7** [comment]
Hi @janicduplessis 

Thanks for your answer! 

So, if i want to generate with expo a ipa/apk for production release, to upload to apple store/google play and i dont use Bundled Assets then the users of those applications will be requesting to the expo server the assets? i thouught that `exp build` will bundle all the code, including resources

So, the only way to "full package" the application for production release is to use Bundle Assets? 

Thanks!

**Comment by janicduplessis** [comment]
@marcosmartinez7 Exactly!

**Comment by obyno50** [comment]
you guys have done a great job @expo, can you make it so that the app can bundle everything together so that the apk build will not require internet for first use cause in Most places in Africa,there is slow or no internet connection.

**Comment by GitHubGreg** [comment]
Just to comment on the question from @obyno50, I believe offline assets are now available:
https://docs.expo.io/versions/latest/guides/offline-support.html
