### ISSUE TITLE
[expo-linear-gradient] border-color, border-radius on ios doesn't behave right

### ISSUE THREAD

**Issue by astriskit** [expo/expo#15118]
### Summary

When using expo-linear-gradient, in android border-color and border-radius works fine; but on ios it doesn't behave correctly. 
In a particular case a gradient with borderTopLeftRadius and borderTopRightRadius along with borderColor is configured - though android platform gave intended results; On iOS it didn't quite resulted correctly. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

^41.0.0

### Environment

 Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/npm-global/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/ajwkslwIt

Playing snack in ios vs android shows the difference.

**Comment by kbrandwijk** [comment]
React-Native's Image has the same issue. Only RN View has a whole bunch of logic built in for dealing with cornerRadii on iOS: https://github.com/facebook/react-native/blob/main/React/Views/RCTView.m#L652. Applying the style to a wrapper View instead makes it behave the same on both platform. I would not consider this a 'bug' in LinearGradient.
