### ISSUE TITLE
AnimatedRegion not defined in expo

### ISSUE THREAD

**Issue by abhitheawesomecoder** [expo/expo#1512]
react-native-maps AnimatedRegion is not defined in expo and thus I am not able to implement this example in my expo app :

https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedMarkers.js

**Comment by terribleben** [comment]
Hey there, thanks for the report. We update our copy of React Native maps periodically. [SDK 25 contains React Native maps v0.19.0](https://blog.expo.io/expo-sdk-v25-0-0-is-now-available-714d10a8c3f7). We'll provide an update next time we update our SDK.
