### ISSUE TITLE
Keyboard avoider pushes text input way too high on Android but works great on iOS

### ISSUE THREAD

**Issue by Rohansi** [expo/expo#15143]
### Summary

`KeyboardAvoidingView` pushes the `TextInput` unexpectedly high on Android vs. working great on iOS. This is blocking the Rust companion app from upgrading from SDK 40 but it's also broken in SDK 40 or earlier (we just have a mystery workaround for it that only works in SDK 40).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40+?

### Environment

```
  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^43.0.0 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Git: https://github.com/Rohansi/expo-tabs-chat-layout
SDK 43: https://snack.expo.dev/@rohans/github.com-rohansi-expo-tabs-chat-layout@sdk43
SDK 40: https://snack.expo.dev/@rohans/github.com-rohansi-expo-tabs-chat-layout@sdk40

`TextInput` not focused:
![android 1](https://user-images.githubusercontent.com/1319884/141160742-21b0001e-a928-4eae-8572-c20fb9a82170.png)
`TextInput` focused, keyboard open:
![android 2](https://user-images.githubusercontent.com/1319884/141160777-7de2b288-4c4d-4eb6-8544-731769c4c6b6.png)

**Comment by brentvatne** [comment]
I expect this is a bug with react-native's KeyboardAvoidingView, have you tried any other approaches to adjusting for the keyboard height? KeyboardAvoidingView is notoriously not-very-robust

**Comment by Rohansi** [comment]
I'm not aware of other approaches but the concern I have with alternatives is they may end up being quite janky.

I have experimented with using the option React Navigation provides to hide the bottom tab bar when the keyboard is opened but it looks horrendous. The keyboard slides up, pushing the tabs up, then the tabs slide down... quite a downgrade.

**Comment by brentvatne** [comment]
you can subscribe to keyboard events directly and adjust the view however you see fit, and write your own KeyboardAvoidingView that works well for your app: https://reactnative.dev/docs/keyboard

**Comment by Rohansi** [comment]
Yeah I expect that to be just as janky because IIRC the keyboard events only fire **after** the keyboard opens or closes. Plus the delay to re-render the components... it's doomed to never be a smooth experience. It's an option but an ugly one. 😄 

Surely there must be a way to do this smoothly in React Native somehow?

**Comment by brentvatne** [comment]
KeyboardAvoidingView just [uses the Keyboard APIs](https://github.com/facebook/react-native/blob/main/Libraries/Components/Keyboard/KeyboardAvoidingView.js), so you can get the same results as that library but without the bugs that you are experiencing by using Keyboard directly. You're right that the events are limited to after open/close, which isn't ideal, but I'm not personally aware of a better way to handle this.
