### ISSUE TITLE
Failed to obtain exclusive lock on token file.  Please ensure the following file is not locked by another process: /Users/hide/.itmstransporter/UploadTokens/userid.token

### ISSUE THREAD

**Issue by teamhide** [expo/expo#1514]
I've tried to Upload my application made with React Native(Expo XDE) to App store.

I'm using Xcode Application Loader.

While I add ipa file to Application Loader, It throws error like this.

```
Cannot proceed with delivery: an existing transporter instance is currently uploading this package
```
```
Failed to obtain exclusive lock on token file.  Please ensure the following file is not locked by another process: /Users/hide/.itmstransporter/UploadTokens/hideui-MacBook-Pro.local_UP757U927C_1356647666.itmsp.token
```

How can I solve this issue?

**Comment by tcdavis** [comment]
This is an issue with application loader, so I would look there.  It seems like either there is, or at least Application Loader thinks there is, another version already trying to load the app.
