### ISSUE TITLE
A file base navigation system with expo's own navigation would be great (Something like NextJS).

### ISSUE THREAD

**Issue by vikrant0526** [expo/expo#15149]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by Simek** [comment]
Hi @vikrant0526, the issues are not the right place for the feature suggestions.

Please use the [Discussion tab](https://github.com/expo/expo/discussions), post the thread on the [Expo Forums](https://forums.expo.dev/) or suggest the change on the [Expo Canny Board](https://expo.canny.io/).
