### ISSUE TITLE
react-native-image-crop-picker

### ISSUE THREAD

**Issue by Mubashir1044** [expo/expo#1515]
### Environment

Environment:
  OS: Windows 10
  Node: 8.7.0
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/mubashir-0ac1b6ae-7680-4b1b-98dd-8ce2fbae3199.tar.gz

My Target App is Android
### Steps to Reproduce
Actually I am trying to select multiple images in one iteration. So I tried this module to do it show error
### Expected Behavior
Able to select multiple images in one iteration.

 Actual Behavior
show the following error.
Undefined is not an object (Eveluating '_react_NativeImageCropPicker2.default.openPicker

**Comment by tcdavis** [comment]
Can you reproduce your issue on https://snack.expo.io?

**Comment by Mubashir1044** [comment]
ok

**Comment by JLarky** [comment]
@tcdavis yes https://snack.expo.io/S1wiQ34YG
