### ISSUE TITLE
Size of app in increased by 3 to 4 mb when migrating from expo-unimodules to expo core 

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#15160]
### Summary

Size of app in increased by 3 to 4 mb when migrating from expo-unimodules to expo core 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

 Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.11 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.1 => 0.66.1 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- create project with expo unimodules
- uninstall unimodules
- install expo core 
- app size increases

Are ProguardRules are correctly written for expo core package?
Can we fix the issue by writing our own proguard rules?

**Comment by Kudo** [comment]
hi there! proguard rules is supported even though we did not turn it on by default. could you please provide a repo url to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). i did a simple verification, from a `react-native init --version 0.66` project to adapt unimodules and expo-modules, the size is decreased.

```sh
$ apkanalyzer -h apk file-size rn066um/android/app/build/outputs/apk/release/app-release.apk
30.7MB
$ apkanalyzer -h apk file-size rn066ex/android/app/build/outputs/apk/release/app-release.apk
30.6MB
```

for sdk42 and sdk43 comparison, the size is increased from react-native 0.63 and react-native 0.64. as far as i can tell, expo-modules-core are mostly java/kotlin code, so here is dex comparison:

```sh
apkanalyzer -h apk compare sdk42/android/app/build/outputs/apk/release/app-release.apk sdk43/android/app/build/outputs/apk/release/app-release.apk | grep '\.dex'
8.4MB   8.7MB   293.3KB /classes.dex
2.6MB   2.2MB   -439.7KB        /classes2.dex
```

i am happy to help if you can share a minimal reproducible example for us to troubleshoot. i'll reopen this issue once confirmed expo-modules-core increase 3-4MB apk size.

**Comment by shubhamdeol** [comment]
Thanks for your response. I am still trying to figure this out. 
I think issue I am facing is due to the fact that I have updated react native version. 

https://github.com/facebook/react-native/issues/32463

on React native repo, there is already an issue open about size increase due to version change.
