### ISSUE TITLE
ERR! Invalid package name "@types/": name can only contain URL-friendly characters when eas building

### ISSUE THREAD

**Issue by TomasSestak** [expo/expo#15163]
### Summary

![Screenshot 2021-11-12 at 14 40 59](https://user-images.githubusercontent.com/27310585/141476261-50f7f80c-698c-4a95-9bf9-3695c71a4584.png)

I have "@types/": "react-native-community/hooks", in my devDependencies of package.json and after running `eas build --profile development --platform ios` build fails with the error seen on the screenshot

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.1 => 43.0.2 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: ^0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I think summary is pretty clear here

**Comment by byCedric** [comment]
Hi @TomasSestak! I'm not sure what you are trying to achieve in the code you sent, but this error is not coming from Expo. npm package names can't end with a `/`, [see this SO answer for more rules](https://stackoverflow.com/a/50379762). If this somehow works with yarn, make sure to commit the lockfile. Only with the `yarn.lock`, EAS will install the dependencies with yarn.

I'm closing this issue because it's coming from npm, and there is not much we can do to solve this.

**Comment by TomasSestak** [comment]
> Hi @TomasSestak! I'm not sure what you are trying to achieve in the code you sent, but this error is not coming from Expo. npm package names can't end with a `/`, [see this SO answer for more rules](https://stackoverflow.com/a/50379762). If this somehow works with yarn, make sure to commit the lockfile. Only with the `yarn.lock`, EAS will install the dependencies with yarn.
> 
> I'm closing this issue because it's coming from npm, and there is not much we can do to solve this.

Thank you for quick reply, what do you mean by commit? I thought apps are build from the whole repo you have when runnning the command.
