### ISSUE TITLE
[expo-file-system] : Message Digest Generated Using Broken Cryptography API

### ISSUE THREAD

**Issue by realtril** [expo/expo#15162]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by realtril** [comment]
The following code locations within the App use the deprecated CC_MD functions to generate a message digest:

-[NSData (EXFileSystem) md5String] calls _CC_MD5()

```
The following related source code symbols were identified:

-[EXSessionUploadTaskDelegate setResponseData:]
-[EXSessionUploadTaskDelegate responseData]
-[EXFont initWithCGFont:]
@"%02x"
-[_OBJC_CLASS_$_NSMutableString stringWithCapacity:]
-[(id) bytes]
-[(id) length]
```

**Comment by brentvatne** [comment]
can you open a pull request to fix the issue? thanks!

**Comment by realtril** [comment]
Why the issue is closed?🥴
