### ISSUE TITLE
build failing with "yarn exited with non-zero code: 1"

### ISSUE THREAD

**Issue by haibert** [expo/expo#15172]
### Summary

Hello all,

My eas cloud builds are failing with the following error: "yarn exited with non-zero code: 1" for both android and iOS.

```
Running yarn in the root dir of your repository 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[stderr] error eslint@8.2.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.15.1"
[stderr] error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn exited with non-zero code: 1
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.10.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.2 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I don't have a reproducible repo for this yet, I am creating it but just wanted to submit the issue incase its a quick and easy fix.

**Comment by Simek** [comment]
Hi @haibert,

I think that the error which is causing the issue is a few lines above the last log message:
> [stderr] error Found incompatible module.

Can you share your `package.json` content?

**Comment by haibert** [comment]
I was able to get rid of the issue by uninstalling eslint. Seems like the version I have installed   '8.2.0' is not compatible with the version of node expo uses during the build. I guess I will have to downgrade eslint or remove it before builds, correct?

**Comment by Simek** [comment]
That's good to hear! 🙂 

Generally it looks like the issue you were experiencing was not directly related to the ESLint version, rather to the Node version declared in ESLint `package.json`:
> The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.15.1"

AFAIK, when using latest release from `7` major, everything should be fine, also please ensure that `eslint` is listed in `devDependencies`. Feel free to re-open this issue or create the new one, if you will have any other issues!

**Comment by amy-r** [comment]
I'm getting this same error. Locally the project spins up just fine but the build on EAS is failing. Package json looks like this:

```{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll",
    "lint": "eslint .",
    "postinstall": "husky install"
  },
  "lint-staged": {
    "**/*": "prettier --write --ignore-unknown"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@reduxjs/toolkit": "^1.6.2",
    "@types/react-redux": "^7.1.20",
    "@types/remote-redux-devtools": "^0.5.5",
    "expo": "~42.0.1",
    "expo-asset": "~8.3.2",
    "expo-constants": "~11.0.1",
    "expo-font": "~9.2.1",
    "expo-linking": "~2.3.1",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-web-browser": "~9.2.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-svg": "12.1.1",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.5",
    "remote-redux-devtools": "^0.5.16"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.4.0",
    "@typescript-eslint/parser": "^5.4.0",
    "eslint-config-airbnb": "^19.0.0",
    "eslint-plugin-react": "^7.27.0",
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "eslint": "^8.2.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react-native": "^3.11.0",
    "husky": "^7.0.4",
    "jest-expo": "~41.0.0-beta.0",
    "lint-staged": "^11.2.6",
    "prettier": "2.4.1",
    "typescript": "^4.4.4"
  },
  "private": true
}

**Comment by MoSattler** [comment]
Same problem here - is there any work around?
