### ISSUE TITLE
[Expo 43] react-native not found in monorepo

### ISSUE THREAD

**Issue by abeaclark** [expo/expo#15173]
### Summary

I have been using a monorepo with Expo 42.
Upgrading to 43, I've followed the steps / moved away from unimodules, but getting the following error:

```
  2 | // load remote logging for compatibility with custom development clients
  3 | import './environment/logging.fx';
> 4 | import './environment/react-native-logs.fx';
    |                       ^
  5 | // load expo-asset immediately to set a custom `source` transformer in React Native
  6 | import 'expo-asset';
  7 | import Constants, { ExecutionEnvironment } from 'expo-constants';
Unable to resolve module react-native from /Users/dev1/projects/olympia/venice/node_modules/expo/build/Expo.fx.js: react-native could not be found within the project or in these directories:
  ../../node_modules/expo/node_modules
  ../../node_modules

````

It seems like it's not prepared to have expo located at the project root?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.23.0-20210726.1745 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.11.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

I will work on getting this together

**Comment by brentvatne** [comment]
happy to investigate when you have an example ready!

**Comment by abeaclark** [comment]
Thanks @brentvatne I was finally able to get this to work. Retraced the migration guide and ended up running `expo install ...` on all of my depedencies. Seemed to sort something out.

**Comment by brentvatne** [comment]
you can also use `expo doctor` to verify that dependency versions are aligned with the sdk version in your project, to save you having to run `expo install` for each of them

**Comment by veeramarni** [comment]
@abeaclark I'm facing the same issue for a monrepo project, could provide steps to resolve it?

**Comment by abeaclark** [comment]
hey @veeramarni -- 

The workflow that seemed to finally work for me was:
* Go through all dependencies and make sure I have the latest version (many expo can do for you, but some it doesn't know how to upgrade)
* Make sure to run `expo install` on these so they are correctly linked

I never did pin it down to a specific issue, but after trying many things, that seemed to work

**Comment by gablabelle** [comment]
@abeaclark @brentvatne I have the same issue in turborepo with latest expo.

If you run `yarn install` from the expo app i.e `apps/mobile` react-native is not hoisted to the workspace root `node_modules` and even removed if it was there before. react-native will be installed in `app/mobile/node_modules` instead.

If you run `yarn add react-native@0.64.3` in `apps/mobile`, then react-native is properly hoisted and everything works until the next time you'll run `yarn install` in `apps/mobile`.

When doing `yarn install` after `turbo clean` at the root of the workspace, react-native is not hoisted either.
