### ISSUE TITLE
Correct way to handle multiple users logging and using the same Expo Push Token

### ISSUE THREAD

**Issue by haibert** [expo/expo#15177]
### Summary

Hello all,

Hope you’re well, just had a quick question about expo notifications implementation.

Tokens are given per device, and I believe one cannot create a new token on demand. For these reasons I’m running into an issue where if user B logs into a phone used by user A, they start to receive notifications meant for user A. How’s this situation supposed to be handled ? Do I have to remove the expo token of user A from our sever when they log out ? That seems to be the most reasonable way to go about it but just wanted to make sure.

Just to avoid having this issue closed I want to mention I have posted this in the expo forums but did not get any responses so I'm trying my luck here guys, thank you. 
### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.10.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.2 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

None needed.

**Comment by cruzach** [comment]
> Do I have to remove the expo token of user A from our sever when they log out ?

Yeah, exactly this 👍
