### ISSUE TITLE
[expo-linear-gradient] black-transparent gradient becomes white-transparent in aab only

### ISSUE THREAD

**Issue by mRcSchwering** [expo/expo#15170]
### Summary

I want to create a black-transparent gradient `<LinearGradient colors={["black", "transparent"]} />`. In _Expo Go_ and a standalone _.apk_ it gets rendered properly. But when I create an _.aab_ (`expo build:android -t app-bundle`), upload it to Playstore, install it on my Android it shows as a white-transparent gradient.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

4.12.11

### Environment

Expo CLI 4.12.11 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.9.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/bin/yarn
      npm: 7.21.1 - /usr/local/bin/npm
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      expo-linear-gradient: ~10.0.3 => 10.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Add a black-transparent gradient like below.
2. Build an _.aab_ with `expo build:android -t app-bundle`
3. Upload it to Google Playstore
4. Install it on an Android device
5. See a white-transparent gradient

```
import { LinearGradient } from "expo-linear-gradient";

// in a render
        <LinearGradient
          colors={["black", "transparent"]}
          style={[styles.pickerGradient, { height: 200 }]}
        />
```

**Comment by mRcSchwering** [comment]
**Edit** Ok I figured it has to do with the dark mode. Switching on dark mode makes the _black-transparent_ gradient _white-transparent_. However, I don't really understand how I can create a _black-transparent_ gradient in dark mode now?!

- **black-transparent** becomes **white-transparent** in dark mode
- **white-transparent** stays **white-transparent** in dark mode

**Comment by mRcSchwering** [comment]
I think this is related to these issues:

- [How to change MIUI force dark mode on expo? (SO)](https://stackoverflow.com/questions/66128823/how-to-change-miui-force-dark-mode-on-expo)
- [How to force APP in light mode (github)](https://forums.expo.dev/t/how-to-force-app-in-light-mode/33038)
- [How can I force light mode on MIUI? (github)](https://github.com/expo/react-native-appearance/issues/60)

**Comment by byCedric** [comment]
Hi @mRcSchwering! Thanks for the additional research. I'm not sure what we can do to combat custom implementions of darkmode in certain Android versions. One thing you could try is [manually adding this code](https://stackoverflow.com/a/62732689) to disable this behavior for your app. You [could make a config plugin](https://docs.expo.dev/guides/config-plugins/) for this as well, but might be better to try and eject (with `expo prebuild`) first to see if this works.

**Comment by mRcSchwering** [comment]
Thanks. By now I created a linear gradient using only background color (this seems to be unaffected by the dark mode thing): https://stackoverflow.com/a/69955769/5562431
