### ISSUE TITLE
Unable to resolve module css address

### ISSUE THREAD

**Issue by nerdferby** [expo/expo#15178]
### Summary

JavaScript bundle for Android device fails to resolve module css address

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

4.13.0

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files (x86)\nodejs\node.EXE
      npm: 8.1.0 - C:\Program Files (x86)\nodejs\npm.CMD
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

expo init my-app

[App.js.txt](https://github.com/expo/expo/files/7532707/App.js.txt) (uncomment import)
[base.module.css.txt](https://github.com/expo/expo/files/7532708/base.module.css.txt)

Run on device via QR code
Building JavaScript bundle: error
Unable to resolve module ./static/styling/base.module.css from ...
None of these files exist:
  * static\styling\base.module.css(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * static\styling\base.module.css\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  2 | import React from 'react';
  3 | import { StyleSheet, Text, View } from 'react-native';
 4 | import styles from "./static/styling/base.module.css"

**Comment by byCedric** [comment]
Hi @nerdferby! Unfortunately, this is expected behavior. There is [no concept of CSS in React Native](https://reactnative.dev/docs/style). You might be able to make it work by adding a custom transpiler in between, but I'm not sure if that exists already.


Hope this helps!
