### ISSUE TITLE
Build field with Execution failed for task ':app:compileReleaseJavaWithJavac'

### ISSUE THREAD

**Issue by akshaykatale99** [expo/expo#15187]
### Summary

Getting this error while building android app using `gradlew assembleDebug`.

		android\app\src\main\java\com\wadp\woocom\generated\BasePackageList.java:9: error: method asList in class Arrays cannot be applied to given types;
    		return Arrays.<Package>asList(
                 ^
  		required: T[]
  		found: ConstantsPackage,DocumentPickerPackage,ErrorRecoveryPackage,FileSystemPackage,FontLoaderPackage,ImageLoaderPackage,ImagePickerPackage,KeepAwakePackage,LinearGradientPackage,LocationPackage,PermissionsPackage,SplashScreenPackage,SQLitePackage,UpdatesPackage
  		reason: varargs mismatch; ImagePickerPackage cannot be converted to Package
  		where T is a type-variable:
    		T extends Object declared in method <T>asList(T...)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

		Expo CLI 3.21.5 environment info:
		System:
		OS: Windows 10 10.0.19043
		Binaries:
		Node: 12.22.3 - C:\Program Files\nodejs\node.EXE
		npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
		Watchman: 20200816.222424.0 - C:\Users\Akshay\AppData\Local\watchman\bin\watchman.EXE
		IDEs:
		Android Studio: Version 4.1.0.0 AI-201.8743.12.41.6953283
		npmPackages:
		expo: ~39.0.2 => 39.0.3
		react: 16.13.1 => 16.13.1
		react-dom: 16.13.1 => 16.13.1
		react-native: ~0.63.3 => 0.63.3
		react-native-web: ~0.13.12 => 0.13.18

### Reproducible demo or steps to reproduce from a blank project

getting this error after updating build.gradle file

		ext {
        		buildToolsVersion = "29.0.2"
		        minSdkVersion = 24
		        compileSdkVersion = 29
		        targetSdkVersion = 29
    		}

to
    		
    	ext {
        		buildToolsVersion = "30.0.3"
		        minSdkVersion = 24
		        compileSdkVersion = 30
		        targetSdkVersion = 30
    		}

**Comment by byCedric** [comment]
Hi @akshaykatale99! [Support for SDK 39 has been dropped with the release of SDK 43](https://blog.expo.dev/expo-sdk-43-aa9b3c7d5541). Starting from SDK 41, [both the `compileSdkVersion` and `targetSdkVersion` are set to 30 by default](https://github.com/expo/expo/blob/sdk-41/templates/expo-template-bare-minimum/android/build.gradle#L7-L8). I would recommend upgrading to at least SDK 41 to upgrade these versions.

Hope this helps!

**Comment by sreyahalder** [comment]
I'm also getting this issue, but I have the same SDK configuration that version 41 provides:

``
 {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
    }
``

**Comment by khalidahmada** [comment]
Same problem here! too

**Comment by JuarezCout** [comment]
Same problem here too with this SDK configuration:

```
buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '31.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '21')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '31')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '31')
        if (findProperty('android.kotlinVersion')) {
            kotlinVersion = findProperty('android.kotlinVersion')
        }
        frescoVersion = findProperty('expo.frescoVersion') ?: '2.5.0'

        if (System.properties['os.arch'] == 'aarch64') {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = '24.0.8215888'
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = '21.4.7075529'
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.1.1')
        classpath('com.facebook.react:react-native-gradle-plugin')
        classpath('de.undercouch:gradle-download-task:5.0.1')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
