### ISSUE TITLE
expo-updates using old channel's update

### ISSUE THREAD

**Issue by zhigang1992** [expo/expo#15181]
### Summary

expo-updates apply wrong code when release-channel changes.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
  Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 12.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.1 - /usr/local/bin/npm
      Watchman: 2021.08.23.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.2 => 0.16.6
      expo: ^43.0.1 => 43.0.1
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.5 => 0.17.5
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

When we have 

native build 1 -> release channel 1 on production

submitting 

native build 2 -> release channel 2 to AppStoreConnect

before the build is reviewed and released.

We publish an OTA update on channel 1

When app is released, and user upgraded to native build 2

Their JS code is still from channel 1, which is incompatible and caused crashes.

**Comment by ide** [comment]
Hi, we've accepted your bug report and this is a known problem we're looking into. We've identified the root cause but are currently working through some unexpected behavior in the Android OS APIs.

**Comment by zhigang1992** [comment]
hey @ide is there an update on this?

We are doing our next launch, and this issue is block us from doing so. 😭

**Comment by ide** [comment]
I believe we have a fix for this with our Q4 release this year.
