### ISSUE TITLE
XDE stuck at loading

### ISSUE THREAD

**Issue by riwu** [expo/expo#1518]
https://exp-xde-diagnostics.s3.amazonaws.com/riwu-4016b7cc-b844-4c65-a1f5-b6d93d9eeb8d.tar.gz

![](https://i.imgur.com/Oez0MBF.png) 

Get stuck there permanently

**Comment by riwu** [comment]
Resolved itself after some waiting and restarts, no idea what happened.

**Comment by ccheever** [comment]
Glad restarting things fixed stuff for you. Sorry for the trouble. :/
