### ISSUE TITLE
Cannot sign in using expo-google-sign-in (https://docs.expo.dev/versions/latest/sdk/google-sign-in/) library for EAS build.

### ISSUE THREAD

**Issue by basit3407** [expo/expo#15182]
### Summary

I was able to sign in via google using expo-google-sign-in library when using classic expo - build. However when i migrated to eas-build i am not able to sign in. no idToken is returned on signing in via expo-google-sign-in. credentials for both the builds i.e expo-build and eas-build are exactly same.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^43.0.2 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I prepared the test repo for this case.
https://github.com/basit3407/expo-google-signInTest. read me is attached in this repo

steps to reproduce:

1. git clone https://github.com/basit3407/expo-google-signInTest
2. npm install
3. register app in firebase and get google-services.json (must add finder prints SHA 1 certificate)
4. copy-paste google-services.json to root directory
5. run expo build:android -t apk
6. once built. download apk, install and open the app.
7. click on Google SignIn Button. modal will be shown with google ids. click on any id and token will be shown.
8. uninstall the app and again go to terminal and run eas build -p android --profile production
9. repeate steps 6 and 7.
10. This time upon selecting googleId in the modal nothing will happen.token will still be null as no token was returned from the expo-google-sign-in library

**Comment by jurica-penjgusic** [comment]
Me too.
Luckily, we have resolved by exchanging access token for id token on server side and get client data from that id token

**Comment by basit3407** [comment]
@jurica-penjgusic  can you please share the relevant code on client and server side? That would be really kind and helpful.

**Comment by basit3407** [comment]
@jurica-penjgusic  . I like this approach. Only issue was that while using classic expo build we were getting idToken on client side using expo-google-sign-in library and sending that token to server side to get the JWT. On migrating to eas build , expo-google-sign-in is returning null for id token.  So a great workaround as suggested by you would be to get the access token on client side and send that access token to server side where we would get the idToken from server token. Please correct me if i made some error in understanding your approach. Would test this tomorrow.

**Comment by basit3407** [comment]
Though i must say this is an issue and expo team should resolve this at the earliest. Id token should be returned using expo-google-sign-in. Because this would be a problem for apps which doesn't have server side.

**Comment by jurica-penjgusic** [comment]
Totally agree with you! 
If we are asking openid, profile and email scopes, then idtoken should be returned.
As far as go for exchanging access token for id, I think you got that right.

**Comment by basit3407** [comment]
ok so i finally got the problem. in eas build we also have to the pass the webclientid option to GoogleSignIn.initAsyc method. i think expo build gets it from google-services.json so we don't have to pass it.
