### ISSUE TITLE
[jest-expo SDK43] upgrade to sdk 43 break jest test

### ISSUE THREAD

**Issue by giovannimanzoni** [expo/expo#15193]
### Summary

I can't run jest test with SDK43. No problem with SDK 42. I open a ticket here also: https://forums.expo.dev/t/expo-jest-typescript-break-jest-test-in-sdk43/58984

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.14 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 20210222.215625.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

git clone https://github.com/elgsantos/expo-template-typescript-jest.git
cd expo-template-typescript-jest
yarn
yarn test -> ok
expo upgrade 42
yarn test -> ok
expo upgrade 43
yarn test -> fail ->

yarn run v1.22.15
$ jest
 FAIL  src/helpers/calc/sum.spec.ts
  ● Test suite failed to run

    /home/andro/apps/test/expo-template-typescript-jest/node_modules/@react-native/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)

 FAIL  ./App.spec.tsx
  ● Test suite failed to run

    /home/andro/apps/test/expo-template-typescript-jest/node_modules/@react-native/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        1.895 s, estimated 8 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Simek** [comment]
Hi @giovannimanzoni,

I think that you should open the issue in the custom template repository. 

From the error you have provided it looks like that template code, config or dependencies definition are the root cause of the problem. 

Also the fact that the template was not updated in last several months might be an additional indicator towards the initial diagnosis.

Unfortunately templates, if not maintained, tend to become outdated quite fast.

**Comment by byCedric** [comment]
To add more context to this one, as Simek said, this is a 3rd party template so we can't provide full support. The issue here is that it doesn't transpile flow code properly. You can see that `node_modules/@react-native/polyfills/error-guard.js` is just a JavaScript file (.js) but has types in it (`type ErrorHandler`), which is flow.

Hope this helps!

**Comment by giovannimanzoni** [comment]
> Hi @giovannimanzoni,
> 
> I think that you should open the issue in the custom template repository.
> 
> From the error you have provided it looks like that template code, config or dependencies definition are the root cause of the problem.
> 
> Also the fact that the template was not updated in last several months might be an additional indicator towards the initial diagnosis. Unfortunately templates, if not maintained, tend to become outdated quite fast.
> 
> You can also make sure that the Jest configuration for your project or in the template is up to date with the one listed in docs:
> 
> * https://docs.expo.dev/guides/testing-with-jest/#jest-configuration

But this is only an example as tamplate ! I can not be able to run jest with expo sdk43 in any way ! I try so many way but no one work.

**Comment by giovannimanzoni** [comment]
> To add more context to this one, as Simek said, this is a 3rd party template so we can't provide full support. The issue here is that it doesn't transpile flow code properly. You can see that `node_modules/@react-native/polyfills/error-guard.js` is just a JavaScript file (.js) but has types in it (`type ErrorHandler`), which is flow.
> 
> Hope this helps!

Can you provide me any example with expo sdk 43 and jest ? Thanks.

**Comment by TiKevin83** [comment]
Upgrading from 42 to 43 I was able to partially fix this by following #14679 however I'm now getting an issue where during a jest test the Image module `import { image } from 'react-native'` is importing as the entirety of react-native including Image again as one of its properties.

**Comment by Simek** [comment]
> Can you provide me any example with expo sdk 43 and jest ? Thanks.

@giovannimanzoni You can just use `expo init` with `bare-minimum` or `tabs` template. Both of them include basic Jest setup:
* https://github.com/expo/expo/tree/master/templates/expo-template-bare-minimum
* https://github.com/expo/expo/tree/master/templates/expo-template-tabs

> I'm now getting an issue where during a jest test the Image module import { image } from 'react-native' is importing as the entirety of react-native including Image again as one of its properties.

Hi @TiKevin83, please report your problem as a separate issue. Including a reproducible demo or Snack should ensure that your ticket gets an attention.
