### ISSUE TITLE
Include information about M1 in Android Studio emulator setup guide

### ISSUE THREAD

**Issue by Jonatthu** [expo/expo#15199]
### Summary

https://docs.expo.dev/workflow/android-studio-emulator/#step-1-set-up-android-studios-tools

The docs no longer are updated for MAC monterrey
The last part of the guide won't work due new restrictions on the OS.
$sudo cp ~/Library/Android/sdk/platform-tools/adb /usr/bin

Could we get an updated guide for this? I am having a hard time to build android locally.

### Environment

Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/npm/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: bare
    
    
Mac apple sillicon (Chip)    m1 max

### Please specify your device/emulator/simulator platform, model and version

Android 

### Error output

› Building app...
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.9/userguide/gradle_daemon.html
Process command line: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin/java -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/jonatthu/.gradle/wrapper/dists/gradle-6.9-all/dooywd8nv05k16orzxge2b1bs/gradle-6.9/lib/gradle-launcher-6.9.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.9
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Reproducible demo or steps to reproduce from a blank project

No repro other than the OS

**Comment by olivermontalbano** [comment]
Is there any update on this? I'm having a really difficult time getting android to build properly.

**Comment by brentvatne** [comment]
@olivermontalbano - have you tried out the guide linked above? https://dev.to/davidkou/develop-android-apps-using-react-native-setup-on-mac-m1-and-troubleshooting-38bj

**Comment by Aryk** [comment]
@brentvatne - I have JDK 17 installed. Is there no way to get `expo run:android --device` working on a newer version of java? Do we have to switch the JAVA_HOME to JDK 8 whenever we need to run `expo run:android --device`?

**Comment by brentvatne** [comment]
@Aryk - as far as i know JDK 8 is required for react-native <= 66

**Comment by jereloh** [comment]
> @brentvatne - I have JDK 17 installed. Is there no way to get `expo run:android --device` working on a newer version of java? Do we have to switch the JAVA_HOME to JDK 8 whenever we need to run `expo run:android --device`?
> 
> For others that had problems getting expo run: android working, here are the sources that helped me on my mac book pro:
> 
> * [Download Java 8](https://www.oracle.com/java/technologies/downloads/#java8-mac) - make sure to set JAVA_HOME
> * [Set android env variables](https://stackoverflow.com/questions/29391511/where-is-android-sdk-root-and-how-do-i-set-it)
> * [Accept license agreements](https://stackoverflow.com/a/43003932)

Thanks!, Can confirm that it works on my m1 pro, using zulu-8.jdk native, emulating android arm64 Tiramisu. 👍

**Comment by karlhorky** [comment]
I was trying to set up also getting these confusing "empty" child process `onexit` error messages mentioned [in expo/expo-cli#3595](https://github.com/expo/expo-cli/issues/3595#issuecomment-981664409):

```
$ yarn start --android

...

Error
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Really not sure what these are about, pretty bad error messaging here.

After trying a bunch of things unsuccessfully, carefully following the Android Studio Emulator guide in the Expo docs worked: 

https://docs.expo.dev/workflow/android-studio-emulator/

Some additional things that may help you:

1. The **React Native CLI Quickstart** tab on [the React Native environment setup docs](https://reactnative.dev/docs/environment-setup)
2. Running `npx react-native doctor`
