### ISSUE TITLE
Remove watchPositionAsync

### ISSUE THREAD

**Issue by fredjens** [expo/expo#152]
Have som problems with calling the function to remove watchPositionAsync.

This is my code:

```
const getLocation = (position) => {
  console.log(position);
}

const location = Location.watchPositionAsync({
enableHighAccuracy: true,
}, getLocation);
```

As i [read the docs](https://docs.expo.io/versions/v15.0.0/sdk/location.html) `location` are returning a remove function, which i call like this:
```
location.remove();
``` 

But it is returning undefined.
Am I doing something wrong?
Anyone else having similar problem?

**Comment by sonaye** [comment]
it's async, implement it asynchronously.

**Comment by skevy** [comment]
@fredjens @sonaye is correct. The correct code would be:

```javascript
const location = await Location.watchPositionAsync({
  enableHighAccuracy: true,
}, getLocation);
```

**Comment by fredjens** [comment]
Thank you!
