### ISSUE TITLE
Google reject app because of Location

### ISSUE THREAD

**Issue by SBRKH** [expo/expo#15203]
### Summary

Hello,

I’m trying to push my application to Google Store.
I’m using SDK 43 and EXPO-CLI 4.13.0

I don’t use any location packages but Google refuse my app because apparently I use one package which use that.

>     Issue with your app
>     Unclear feature description
>     We were unable to identify the feature that requires access to location in the background based on the declaration you submitted. Please resubmit a declaration with a clear description or additional information regarding the one feature that requires access to location in the background. Even if your app has multiple features that require access to location in the background, please only select one feature and resubmit your declaration form.
> 

When I’m looking expo builds, I see that expo install expo-localization.
![image](https://user-images.githubusercontent.com/19284534/141970634-51a9ef7d-c5c4-4adf-9919-f548f91f1923.png)

How can I remove all the packages using location ?

I try some solutions that I found but nothing work.

Thank you for your help !

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.3 - /usr/local/bin/npm
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

app.json : `"android": {
      "icon": "assets/xxxxx/android/icon.png",
      "package": "fr.xxxx",
      "versionCode": 4300xxxxx,
      "permissions": [
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
        "CAMERA"
      ]
    }`
build
try to publish

**Comment by brentvatne** [comment]
> When I’m looking expo builds, I see that expo install expo-localization.

if you use `expo build` then every module will be included, [this is how the 'classic build service' works](https://blog.expo.dev/expo-managed-workflow-in-2021-5b887bbf7dbb); however, background location permissions will not be added by default. you can read [this thread](https://github.com/expo/expo/issues/11918) for info.

you may also want to use [eas build](https://docs.expo.dev/build/introduction/) instead
