### ISSUE TITLE
Update "expo install react-native-reanimated" ]because ~2.2.0 is broken for Web.

### ISSUE THREAD

**Issue by ngokevin** [expo/expo#15217]
### Summary

When doing `expo install react-native-reanimated`, it installs v2.2.0 which is broken for Web (they have a typo). We should update the version it points to, potentially getting `react-native-reanimated` devs to patch the v2.2 line.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

v43

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.7 => 0.16.7
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
yarn add moti
expo install react-native-reanimated
```

```
import {MotiView} from 'moti';

function Test () {
  return <MotiView animate={{opacity: 1}}/>
}
```

```TypeError: undefined is not an object (evaluating 'component.previousStyle') (setNativeProps)``` because they pass in `undefined` always due to a typo.

**Comment by brentvatne** [comment]
sdk 43 uses: `"react-native-reanimated": "~2.2.0"` - this means that any patch release of reanimated for 2.2.x will be installed. as soon as they patch the library and do a patch release it should be available. i'm going to close this because it's an issue in reanimated and not the expo codebase.

**Comment by IlyaTaidi** [comment]
currently having a similar issue with a fresh install of Expo and Moti web view. Cant resolve react-native-reanimated module in @motify/core
