### ISSUE TITLE
ImagePicker not working on android with {base64:true}

### ISSUE THREAD

**Issue by leaphawk** [expo/expo#1521]
### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.6.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

**Target** :Android & iOS
### Here's Reproducible Demo
[https://snack.expo.io/@leaphawk/imagepicker-android-bug](url)

### Expected Behavior
Image should be picked & base64 string should be attached to the result.
### Actual Behavior
 But nothing is returned whenever base64 is truthy.

**Comment by aalices** [comment]
Hello @leaphawk , `quality` options should be a value between 0 and 1 and you're using 100 - that results in an error - however, it should be exposed so you know what went wrong, sorry for that!

**Comment by leaphawk** [comment]
@aalices Yeah, It works. Thanks.
