### ISSUE TITLE
lazyImports = true doesn't seem to enable Inline Requires

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#15229]
### Summary

I wasn't seeing any way to confirm `inlineRequires` were being enabled so I went and added some logging statements in `./node_modules/@expo/metro-config/node_modules/metro-react-native-babel-transformer/src/index.js` to ensure it was adding `babel-preset-fbjs/plugins/inline-requires` to the Babel configuration.

Even though React Native 0.64.x says [`inlineRequires` are enabled by default](https://blog.logrocket.com/whats-new-in-react-native-0-64/#inlinerequiresenabledbydefault), and even with `lazyImports` set to `true`, it seems they're disabled?

At line 195 I changed the code to:

```js
  if (options.inlineRequires) {
    console.log('inlineRequires is ENABLED')
    extraPlugins.push(inlineRequiresPlugin);
  } else console.log('inlineRequires is DISABLED')
```

Only **"inlineRequires is DISABLED"** ends up being printed, even when running `expo -c`.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 7 6.1.7601
    Binaries:
      Node: 14.17.4 - C:\nodejs64-v14.x\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.14 - C:\nodejs64-v14.x\npm.CMD
      Watchman: 4.9.4 - C:\Users\User\AppData\Local\watchman\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 23
        Build Tools: 23.0.1, 23.0.3, 26.0.2
    IDEs:
      Android Studio: Version  2.3.0.0 AI-162.3871768
    npmPackages:
      expo: ~43.0.0 => 43.0.3
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Not available at this time.

**Comment by byCedric** [comment]
Hi @Slapbox, we have some [documentation around `lazyImports` here](https://github.com/expo/expo/blob/3e3b6f6f0853296bc3b11bf344cc296f18a0e14d/packages/babel-preset-expo/README.md#lazyimports). You are most likely running into the `null` value here, which means it's handled by RN itself. The LogRocket article you sent is also not fully complete, there is a lot more you probably need to do to really gain on a lot of performance (as [mentioned by the official React Native docs](https://reactnative.dev/docs/ram-bundles-inline-requires#inline-requires)).

Hope this helps!

**Comment by Slapbox** [comment]
@byCedric the value is `true` in our configuration. Can you clarify what the expected behavior is when `lazyImports === true`?
