### ISSUE TITLE
requestForegroundPermissionsAsync is always returning denied.

### ISSUE THREAD

**Issue by clevadani** [expo/expo#15225]
### Summary

requestForegroundPermissionsAsync returns the permissions popup when developing on expo, but only returns denied in the standalone app. The permissions dialog doesn't even show up.
I will be glad if someone can point me in the right direction.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

~42.0.1

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.7.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.20.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
let { status } = await Location.requestForegroundPermissionsAsync()
        alert(`Checking location status: ${status}`)
        if (status !== 'granted') {
          alert('Permission to access location was denied')
          return
        }
```

**Comment by byCedric** [comment]
Hi @clevadani! There is an unspecified limit on how many times you can ask for permissions. We also return the `canAskAgain` property we receive from Android to inform about that. If that's set to `false`, you can't ask again through the permission modal. Unfortunately, that's not something we can fix, it's a policy from Android. During testing, you might run into this.

In these cases, it's best to [show the rationale behind the permission and why it's required](https://developer.android.com/guide/topics/permissions/overview#best-practices) with a button that links users to the app settings. The [app settings part is mentioned in the background location guide from Android](https://developer.android.com/training/location/permissions#request-background-location), and you can [use `Linking.openSettings()` to open it](https://docs.expo.dev/versions/latest/sdk/linking/#linkingopensettings).

Hope this helps!

**Comment by joan-saum** [comment]
Hi @byCedric!
I'm encountering the same problem as @clevadani 
When i'm developing in expo, everything works fine. But when I try my app in production environment, the permission dialog doesn't show up and `requestForegroundPermissionsAsync` instantly resolve with "denied".

I checked the app settings, and the location permission is not denied so the native permissions popup should show up. Is there any recent change in expo-location which can cause this effect?

**Comment by joan-saum** [comment]
Resolved.
In my `app.json` I had `"permissions": [],` instead of
```
"permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION"
      ],
```
