### ISSUE TITLE
EAS build crash when the entryfile is not index.js and ENTRY_FILE variable is not set

### ISSUE THREAD

**Issue by AamuLumi** [expo/expo#15232]
### Summary

When you're entryfile is not `index.js`(for example, `index.ts`), EAS crash when trying to generate the app.manifest for expo-updates (Pods/EXUpdates). There's no precise error when the issue occured and is hard to debug.

The reason is [the projectRoot variable](https://github.com/expo/expo/blob/ad28204781a0555e471f231b80dcb2d88a337433/packages/expo-updates/scripts/createManifest.js#L16) is `undefined` when the `entryFile` cannot be resolved. And a crash happen when the script reach [this line](https://github.com/expo/expo/blob/ad28204781a0555e471f231b80dcb2d88a337433/packages/expo-updates/scripts/createManifest.js#L23), because you cannot change the current directory with `undefined`.
So the script should return an understandable error when the `projectRoot` variable is undefined before the `process.chdir(projectRoot)`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

  ```
  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.11.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

- Repository : https://github.com/AamuLumi/expo-entryFile-crash
- `yarn install`
- `expo run:ios --configuration=Release` (equivalent to build cmd of EAS)

The bug is resolved when you rename `index.ts` to `index.js`, but the current error is hard to understand.

**Comment by veeramarni** [comment]
Look like it is already in documents https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in

**Comment by AamuLumi** [comment]
You're right. But in my case, I lost a lot of hours to find the reason of the crash, because the only thing I got is : `The "directory" argument must be of type string. Received undefined`

In this case, expo should show an intentional error text explaining the error instead of a good ol' node crash without any pertinent information.

**Comment by byCedric** [comment]
I agree that the error message isn't "optimal" at the moment. Changing the entrypoint has a lot of implications, it affects the bundler, native code on both Android and iOS, and even Expo Assets or Updates might need to know about it. That's why it's not supported at the moment. While we try to give useful feedback at any point in the development cycle, there are things that we can't validate and have to assume. E.g. if you change your whole project structure, we can't validate every single folder or file and give you meaningful feedback bout it. Best to stick with some best practices.

As @veeramarni correctly mentioned, the best you can do is just import the TS file in the default JS entrypoint.

**Comment by AamuLumi** [comment]
I perfectly understand what the implications behind changing the entrypoint are. And that's exactly why [my PR](https://github.com/expo/expo/pull/15234) isn't trying to add this feature.

The problem here is if you didn't see the little point in the documentation linked by @veeramarni, you can't debug the bug except by editing the whole `eas build` code. The only message you can get is a node.js crash error without any information. 
Is editing the whole library code the behavior intended for a user to use EAS? I don't think so.

You speak about validating the whole project structure, but it's irrelevant. We speak here about validating **only** the entryfile. And you can easily do that by adding just an `else` case to the code loading the entryfile.

The issue I brought to you is EAS is **crashing**, not **stopping with an error**. Maybe I haven't been clear on the purpose of my issue, and I'm sorry for that in this case. If EAS simply shows a message telling `Use index.js for the entryfile`, I'm totally ok because the software handles the error case.

**Comment by liemdo** [comment]
@AamuLumi Are you able to make it work with ios? My app works perfectly fine before sdk 43 by adding `export ENTRY_FILE=index.ts` to the Bundle React Native code & images step in XCode but it doesn't work with expo 43 for some reason.

**Comment by AamuLumi** [comment]
@liemdo Yes. You just have to rename your entry file to `index.js` and remove any TS code from the file.

**Comment by Alipatel05** [comment]
Hi I am facing this issue after migrating to expo 45 sdk its crashing in android prod build and working just fine for iOS and on development server did you manage to solve this?

**Comment by AamuLumi** [comment]
@Alipatel05 You should provide more informations about your bug if you want some help (like logs etc.).

Anyway, there's already all I can say in this issue : 
1 - Check if you have an `index.js` file. 
2 - If it's a `index.ts` Typescript file, rename it to `index.js` and remove TS code.
3 - If it's named differently from `index.js`, add `ENTRY_FILE=myEntrypointFile.js eas build`.

If this won't work, you should open a new issue, because mine has been fixed by adding more informations about the crash in eas (read discussion and see https://github.com/expo/expo/pull/15234).

**Comment by Alipatel05** [comment]
@AamuLumi The thing is there are no logs when it comes to crash apart from what i got from adb logcat which is not specific it just says 
`Error getting package info: [package name]`
can you please elaborate more on where to put `ENTRY_FILE=myEntrypointFile.js eas build` as i already have index.js and in app.json i have used entryPoint property point towards that index.js

**Comment by AamuLumi** [comment]
Seems your error is completely unrelated from this issue (maybe because this issue is centered on iOS and yours is on Android). 

Open a new issue, maintainers will probably help you.

**Comment by atajadod** [comment]
Hi,
I have the same issue with Android. iOS build works fine. I don't have any custom entry file, the same old app.tsx.
I have done everything I could have thought. but still getting the error:
```
_[stderr] Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point._
```
I am using eas build. I even added the ENTRY_FILE in the eas.json. 
```
{
  ...
  "build":{
     ...
     "env": {
              "ENTRY_FILE":"node_modules/expo/AppEntry.js"
        }
  }
}
```
any advice?
Thank you.

**Comment by AamuLumi** [comment]
This is funny, because the purpose of this issue and the associated PR is adding your specific error message.

I repeat the same thing than I wrote in the previous comment : __this issue is an issue centered on a crash without any error message on iOS__. This issue is fully resolved.
Your issue is on Android and is not a crash but an error message (the error message I added with a PR because, without it, it was a crash).

It seems you have a configuration error.
You speak about an `app.tsx` entryfile, but as explained in [this comment](https://github.com/expo/expo/issues/15232#issuecomment-975498795), `.tsx` entrypoint are not supported.

You should open a new issue with a reproducible example following the issue template, and maintainers will help you on the problem.

**Comment by atajadod** [comment]
Thank you, @AamuLumi. 
You are right; I should have created a new issue for this. However, I think the error message I am getting is confusing since I am not using any custom entry point, and it used to be working before migrating to SDK 47.
Regards.

**Comment by atajadod** [comment]
My issue was related to the latest bug in SDK47.  
Just in case someone else ended up here, this is what fixed my issue.
[Expo 47: console.log in app.config.ts crashes build in expo-updates/scripts/createManifest.js](https://github.com/expo/expo/issues/19997)

**Comment by MaxInMoon** [comment]
I encountered this issue with expo@48.

Fixed it by renaming `index.ts` to `index.js`...

**Comment by berenteb** [comment]
> I encountered this issue with expo@48 and Typescript.
> 
> Fixed it by renaming `index.ts` to `index.js`...

Solved it for me, thank you! I was afraid of doing so, but noticed there is only one import and is not typescript specific at all!

**Comment by frednomoon** [comment]
Figured I would chime in on this to also say that renaming `index.ts` to `index.js` solved the problem. Super weird imo that this has been a known issue since 2021 but no fix. Issue should be re-opened.

**Comment by sanborN93** [comment]
@frednomoon You are right. Renaming index.ts to index.js is the way to go! Ty.

**Comment by mattlo** [comment]
I get there's a fix... but it's a silly workaround. Seems low hanging fruit to make `.ts` work and the impact is great to many using TypeScript.

**Comment by lucksp** [comment]
> I encountered this issue with expo@48 and Typescript.
> 
> Fixed it by renaming `index.ts` to `index.js`...

kinda...on android...now iOS fails because

> Error: Unable to resolve module ./index.ts from /Users/lucksp/dev/myflyid/.: 
None of these files exist:
*index.ts(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
*index.ts/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
    at ModuleResolver.resolveDependency (/Users/lucksp/dev/myflyid/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (/Users/lucksp/dev/myflyid/node_modules/metro/src/node-haste/DependencyGraph.js:271:43)
    at /Users/lucksp/dev/myflyid/node_modules/metro/src/lib/transformHelpers.js:171:21
    at Server._resolveRelativePath (/Users/lucksp/dev/myflyid/node_modules/metro/src/Server.js:1132:12)
    at async Server.requestProcessor [as _processBundleRequest] (/Users/lucksp/dev/myflyid/node_modules/metro/src/Server.js:448:37)
    at async Server._processRequest (/Users/lucksp/dev/myflyid/node_modules/metro/src/Server.js:381:9)
› Stopped server

on Expo SDK 48
