### ISSUE TITLE
[expo-notifications][managed workflow][EAS Build][Android] custom sound not playing in locally scheduled notifications

### ISSUE THREAD

**Issue by basit3407** [expo/expo#15239]
### Summary

I am scheduling notifications locally with custom sound but custom sound is not playing. Infact no notification alert is shown. even though show alert and shouldPlaySound is set to true in setNotificationsHandler. It should also be mentioned that color also remains the same even though i have added the custom color in expo-notifications plugin in app.json as well as notification channel and notification content input.

i checked the notification settings of the device in which i installed the apk. notification channel is present and default ringtone of this channel is also set to the custom sound. however it just doesn't play when the notification comes

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. git clone https://github.com/basit3407/testing-custom-sound-notifications
2. npm install
3. eas build -p android --profile preview
4. download apk from https://expo.dev/accounts/[yourAccountId]/projects/[AppName]/builds/[buildNumber]
5. install and open on physical android device (no emulator)
6. click on button to schedule notification

Expected Behaviour:
Notification alert should be shown and custom sound should be played after 5 seconds. Also tint color of notification alert should be that which was set in expo-notifications plugin

Actual Behaviour:
No Notification alert is shown and no sound is played. tint color of notifications plugin is still default color

**Comment by basit3407** [comment]
I think it was because of the default notification channel. I deleted all the channels. Set the new new channel with new channel identifier and it started working.

**Comment by oaojmiguel** [comment]
Hello, @basit3407 ! Greetings.
May I ask you what changes exactly you did to your repo/example that made the custom notification sound to work?
That's a great news!

**Comment by basit3407** [comment]
@oaojmiguel  

Nothing special. Just followed this guide .

https://docs.expo.dev/versions/latest/sdk/notifications/

They have separate heading for custom sounds. Although it is only applicable in eas build.  

1st configure notification channel woth custom sound and then schedule new notification and assign that notification channel to it.

Cheers.

**Comment by adamblvck** [comment]
For anyone ever stumbling upon the same issue (custom sound notifications not triggering for local notifications on android) it's important to _not include the sound variable in your content body_.

Setting the sound field somehow triggers an old internal code for Android 8 and below, and won't make the custom sound play on modern android phones.

```javascript
// Prepare the notification channel
await Notifications.setNotificationChannelAsync('new-emails', {
  name: 'E-mail notifications',
  importance: Notifications.AndroidImportance.HIGH,
  sound: 'email-sound.wav', // <- for Android 8.0+, see channelId property below
});

// Eg. schedule the notification
await Notifications.scheduleNotificationAsync({
  content: {
    title: "You've got mail! 📬",
    body: 'Open the notification to read them all',
    // sound: 'email-sound.wav', <-- is is only for android 8 and below, REMOVE THIS PART for Android 8+
  },
  trigger: {
    seconds: 2,
    channelId: 'new-emails', // <- for Android 8.0+, see definition above
  },
});
```
