### ISSUE TITLE
Change the "window" background color

### ISSUE THREAD

**Issue by joaosardinha** [expo/expo#1523]
How do we change the background color of the app when it's transitioning between scenes? The issue is when using dark backgrounds on the app, changing scenes will flash a white background. Here's a gif of what I mean:
![white-blip](https://user-images.githubusercontent.com/15181917/37261511-f2da01ba-2594-11e8-95ca-4983dd884707.gif)

On native android this is achievable by setting the `<android:windowBackgroundColor>` property to the app's theme, and on React Native without Expo by using the classes RCTRootView/ReactRootView.

Is there a way to achieve it?

**Comment by jesseruder** [comment]
The splash screen doesn't disappear until you app has rendered, so you're probably just rendering a white screen somewhere. Can you post code that repros this on snack?

**Comment by joaosardinha** [comment]
It isn't the Splash screen, it's everytime a new screen(scene?) is opened, I'm using react native router flux, maybe it's related to that. Basically when `Actions.someScene()` is called

**Comment by jesseruder** [comment]
Ok, this can definitely be fixed in your code in that case. Just put a black view behind everything.

**Comment by terribleben** [comment]
Hey there, as @jesseruder pointed out, I think you can just style your App's root component (or whichever component in the hierarchy is visible) to have a different color background. If you think that solution won't work, it'd be really helpful to see a [Snack](https://snack.expo.io) which demonstrates the behavior. Thanks!

**Comment by ckknight** [comment]
If you have an app that can rotate between portrait and landscape, then the `rootView` will show during rotation. This can be extremely apparent if your app has a dark background, as the white will shine through.
