### ISSUE TITLE
LocalAuthentication issue on android

### ISSUE THREAD

**Issue by bahinapster** [expo/expo#15247]
### Summary

Hello, 

i'm trying to use the expo-local-authentication module in my app.

but i faced an issue with the device bellow
huawei phone, android 10
no biometrics enrolled
pattern protection enabled

 "expo": "^43.0.3",
 "expo-local-authentication": "^12.0.1"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

bare app

### Reproducible demo or steps to reproduce from a blank project

When i call LocalAuthentication.authenticateAsync the app goes to pattern protection and i get the response bellow 
Auth results:  {"error": "user_cancel", "success": false, "warning": "Authentication canceled"}

**Comment by byCedric** [comment]
Hi @bahinapster! The local authentication was built using [biometric prompt](https://developer.android.com/training/sign-in/biometric-auth) from Android. Unfortunately, [Huawei's own implementation is a totally different framework](https://developer.huawei.com/consumer/en/doc/development/Security-References/bioauthnprompt_x-0000001050267874) and bc of that, won't work properly.

I'm also not aware of an alternative React Native library that works on both Google's Android, and Huawei's Android. If you do find one, please share it.

Hope this helps!
