### ISSUE TITLE
Can't open project on iOS

### ISSUE THREAD

**Issue by Ronnyrr** [expo/expo#1524]
![screen shot 2018-03-12 at 16 08 56](https://user-images.githubusercontent.com/4519142/37292110-7a22c5d2-2610-11e8-991f-764b94ea1617.png)
### Environment
**Environment:**
  OS: macOS High Sierra 10.13.3
  Node: 8.1.2
  Yarn: 1.2.1
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

**Packages: (wanted => installed)**
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

I've created an app using `create-react-native-app` and ejected right after running `yarn install`. Ejected with ExpoKit. 

### Steps to Reproduce
I'm unable to open my project on my mobile phone. iPhone 8 with iOS11.2.6. Latest Expo Client app from the App Store. 

Steps I took:

1. Created the project
2. Followed the steps to build my project from https://docs.expo.io/versions/latest/guides/expokit.html
3. Hit the play button in Xcode

This works fine. The project is running in the iOS simulator without any problems.
But when I try to manually run it, it doesn't work. I've tried:

4. Run `exp start` in the terminal from project root
5. Copy the link and paste it in the Expo Client app

And:
6. Started XDE
7. Scanned QR-code

And
8. Hit `cmd + I` from XDE the run in simulator

None of them worked. Only the latter showed an error in XDE:
 

### Expected Behavior
App opens in iOS simulator from XDE or on my phone after scanning the QR-code.

### Actual Behavior
While scanning, the QR-code seems to be recognized. 
The camera disappears, but the project isn't loaded. The app just does nothing with the scanned code. I've also tried scanning other QR-codes online. Those **do** work.

When I use the simulator via XDE it doesn't run either.
Instead an error is shown about building the project in Xcode. See image in attachment.

But like I'd told in my steps it's already build via Xcode.

### Reproducible Demo
This is the link from running `exp start` from my terminal:
[http://exp0b70c4455ad3486581e6f4aa018074bb://s3-s2k.ronnyrr.crnatest-expokit.exp.direct:80](http://exp0b70c4455ad3486581e6f4aa018074bb://s3-s2k.ronnyrr.crnatest-expokit.exp.direct:80)

Thanks in advanced for the help!

**Comment by ccheever** [comment]
Hi--

It looks like you have a detached app. You'll need to use Xcode to build your native code and then put that on your phone to be able to open it.

The standard Expo client can't open projects that are detached because it doesn't include any custom native code that you write.
