### ISSUE TITLE
EAS iOS build failed: Compatible version of some pods could not be resolved. Fully Managed Workflow

### ISSUE THREAD

**Issue by durgesh2007** [expo/expo#15248]
### Summary

iOS build failed:
Compatible version of some pods could not be resolved.
You are seeing this error because either:

Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that update value of "cache.key" field in the eas.json to invalidate the cache.
Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.
Tried as per above error message said cache.key to invalid or any string in eas.json file
No fix yet, need a more clear idea about this error.

eas.json file:

{
"build": {
"preview": {
"ios": {
"node": "16.13.0",
"simulator": true,
"cache": {
"key": "181121"
}
}
},
"release": {},
"release-stage": {
"ios": {
"releaseChannel": "stage",
"image": "latest",
"cache": {
"disabled": true,
"key": "17112021"
}
}
},
"cli": {
"version": ">= 0.35.0",
"requireCommit": true
}
}

Environment
C:_Projects\XXX>expo diagnostics

Expo CLI 4.12.10 environment info:
System:
OS: Windows 10 10.0.19042
Binaries:
Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 4.0.0.0 AI-193.6911.18.40.6626763
Expo Workflow: managed

C:_Projects\XXX>eas diagnostics

EAS CLI 0.36.1 environment info:
System:
OS: Windows 10 10.0.19042
Binaries:
Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
Utilities:
Git: 2.27.0.

Error output
Installing pods
Installing unimodules:
expo-app-auth@10.2.2 from ../node_modules/expo-app-auth/ios
expo-application@3.1.2 from ../node_modules/expo-application/ios
expo-constants@10.1.3 from ../node_modules/expo-constants/ios
expo-device@3.2.0 from ../node_modules/expo-device/ios
expo-error-recovery@2.1.0 from ../node_modules/expo-error-recovery/ios
expo-facebook@11.0.5 from ../node_modules/expo-facebook/ios
expo-file-system@11.0.2 from ../node_modules/expo-file-system/ios
expo-font@9.1.0 from ../node_modules/expo-font/ios
expo-image-loader@2.1.1 from ../node_modules/expo-image-loader/ios
expo-keep-awake@9.1.2 from ../node_modules/expo-keep-awake/ios
expo-localization@10.1.0 from ../node_modules/expo-localization/ios
expo-location@12.0.4 from ../node_modules/expo-location/ios
expo-modules-core@0.4.8 from ../node_modules/expo-modules-core/ios
expo-network@3.1.1 from ../node_modules/expo-network/ios
expo-notifications@0.11.6 from ../node_modules/expo-notifications/ios
expo-permissions@12.0.1 from ../node_modules/expo-permissions/ios
expo-splash-screen@0.13.5 from ../node_modules/expo-app-loading/node_modules/expo-splash-screen/ios
expo-structured-headers@1.0.1 from ../node_modules/expo-structured-headers/ios
expo-updates@0.5.5 from ../node_modules/expo-updates/ios
unimodules-app-loader@2.1.0 from ../node_modules/unimodules-app-loader/ios
unimodules-barcode-scanner-interface@6.1.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
unimodules-camera-interface@6.1.0 from ../node_modules/unimodules-camera-interface/ios
unimodules-constants-interface@6.1.0 from ../node_modules/unimodules-constants-interface/ios
unimodules-core@7.1.2 from ../node_modules/@unimodules/core/ios
unimodules-face-detector-interface@6.1.0 from ../node_modules/unimodules-face-detector-interface/ios
unimodules-file-system-interface@6.1.0 from ../node_modules/unimodules-file-system-interface/ios
unimodules-font-interface@6.1.0 from ../node_modules/unimodules-font-interface/ios
unimodules-image-loader-interface@6.1.0 from ../node_modules/unimodules-image-loader-interface/ios
unimodules-permissions-interface@6.1.0 from ../node_modules/unimodules-permissions-interface/ios
unimodules-react-native-adapter@6.2.2 from ../node_modules/@unimodules/react-native-adapter/ios
unimodules-sensors-interface@6.1.0 from ../node_modules/unimodules-sensors-interface/ios
unimodules-task-manager-interface@6.1.0 from ../node_modules/unimodules-task-manager-interface/ios
Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
expo-modules-core, expo-splash-screen
Auto-linking React Native modules for target XXXXXXXX: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNReanimated, RNSVG, RNScreens, RNVectorIcons, lottie-react-native, react-native-geolocation-service, react-native-maps, react-native-safe-area-context, react-native-view-shot, react-native-viewpager, and stripe-react-native
Analyzing dependencies
Fetching podspec for DoubleConversion from ../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec
Fetching podspec for Folly from ../node_modules/react-native/third-party-podspecs/Folly.podspec
Fetching podspec for glog from ../node_modules/react-native/third-party-podspecs/glog.podspec
Adding spec repo trunk with CDN https://cdn.cocoapods.org/
CocoaPods 1.11.2 is available.
To update use: sudo gem install cocoapods
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.2
[!] CocoaPods could not find compatible versions for pod "ExpoModulesCore":
In Podfile:
ExpoModulesCore (from ../node_modules/expo-modules-core/ios)
Specs satisfying the ExpoModulesCore (from ../node_modules/expo-modules-core/ios) dependency were found, but they required a higher minimum deployment target.
[stderr] [!] <PBXResourcesBuildPhase UUID=XXXXXXXXXXXXXXX> attempted to initialize an object with an unknown UUID. XXXXXXXXXXXXXXXX for attribute: files. This can be the result of a merge and the unknown UUID is being discarded.
Error: Compatible version of some pods could not be resolved.
You are seeing this error because either:

Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that update value of "cache.key" field in the eas.json to invalidate the cache.
Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.
Reproducible demo or steps to reproduce from a blank project
https://github.com/durgesh2007/sample-facebook-login-code

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

--> C:_Projects\XXX>expo diagnostics

Expo CLI 4.12.10 environment info:
System:
OS: Windows 10 10.0.19042
Binaries:
Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 4.0.0.0 AI-193.6911.18.40.6626763
Expo Workflow: managed

--> C:_Projects\XXX>eas diagnostics

EAS CLI 0.36.1 environment info:
System:
OS: Windows 10 10.0.19042
Binaries:
Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
Utilities:
Git: 2.27.0.

--> C:\_Projects\Meel\XXXX>expo diagnostics
 Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ^0.16.0 => 0.16.5
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/durgesh2007/sample-facebook-login-code

**Comment by byCedric** [comment]
Hi @durgesh2007! It seems like you have versions of Expo SDK libraries that are not compatible with `"expo": "~41.0.1"`. 
- The new Expo modules core was introduced in SDK 43, so you should not have that in your project at all. 
- Looking at your `package-lock.json`, you also have multiple versions of `expo-modules-core`, looks like [`0.4.8`](https://github.com/durgesh2007/sample-facebook-login-code/blob/main/package-lock.json#L6808-L6816) and [`0.2.0`](https://github.com/durgesh2007/sample-facebook-login-code/blob/main/package-lock.json#L6523-L6527). 
- Next to `expo-modules-core`, you also have multiple versions of `expo-splash-screen` in your project. Both [`0.13.5`](https://github.com/durgesh2007/sample-facebook-login-code/blob/main/package-lock.json#L6566-L6575) and [`0.10.3`](https://github.com/durgesh2007/sample-facebook-login-code/blob/main/package-lock.json#L6868-L6874) are there.

To make sure you always install the right version for the SDK you are using, we recommend you use `expo install <package>`. This avoids exactly the issue you are running into. It will take some effort to "untangle" these libraries and use the appropriate versions for SDK 41, I would heavily recommend running `npm install` and `expo upgrade 41`. It warns you that you are already on SDK 41, but it will also fix your dependencies for this specific version.

Hope it helps!

**Comment by durgesh2007** [comment]
Dear @byCedric, 
Thanks for your quick response.

**Comment by falola0021** [comment]
i have similar problem

**Comment by ajhopen** [comment]
SDK 44.  Similar issue...pretty obvious what the problem is but how to solve this is escaping me.  Error from eas build for ios:

```
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    EXFirebaseCore (from `../node_modules/expo-firebase-core/ios`) was resolved to 4.1.0, which depends on
      Firebase/Core (= 7.7.0) was resolved to 7.7.0, which depends on
        Firebase/CoreOnly (= **7.7.0**)
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 13.1.1, which depends on
      Firebase/CoreOnly (= **8.10.0**)
```

So how do I resolve this version conflict?   I'm using Windows primarily...I have access to a Mac but have zero experience fiddling with PODs.  In my last release, I used SQLite, no problems. Now I have Firebase auth and Firestore.  My eas build for Android works and launches but no luck writing to Firestore or getting Firebase auth to work.  Maybe this conflict is also causing issues in my Android build?  Everything runs like a champ on Expo Go.  Stuck now for days.

**Comment by Andrewryanhyde** [comment]
Having exactly the same issue as above ^

**Comment by imhilla** [comment]
`
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    EXFirebaseCore (from `../node_modules/expo-firebase-core/ios`) was resolved to 3.1.0, which depends on
      Firebase/Core (= 7.7.0) was resolved to 7.7.0, which depends on
        Firebase/CoreOnly (= 7.7.0)
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 12.9.3, which depends on
      Firebase/CoreOnly (= 8.8.0)
[stderr] [!] use_native_modules! skipped the react-native dependency 'pow-react-native-intl-phone-input'. No podspec file was found.
[stderr] 
[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `EA3A06DEFE704DD5992330B5` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
- Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
Error: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add the "cache.key" field (it can be set to any value) in eas.json to invalidate the cache.
  - Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.`
  - Had the same issue

**Comment by davidcort** [comment]
Same issue.

**Comment by durgesh2007** [comment]
Please refer this issue maybe help: https://github.com/expo/eas-cli/issues/774
The same issue posted in eas-cli was fixed by updating expo-sdk

**Comment by trannble** [comment]
@[ajhopen](https://github.com/ajhopen) How did you check and ensure @react-native-firebase/firestore was removed?

**Comment by adscud** [comment]
I have the same issue, any updates ?

**Comment by imhilla** [comment]
Resolved on my end, always check packages that may have multiple versions
used, remove them and try using expo Install package name or run expo
doctor.

**Comment by widescape** [comment]
👍 Using `expo doctor` was very helpful to resolve the issue (incompatible package versions).

**Comment by Talent-Roy** [comment]
Just like the error message says, add the cache key to your `eas.json` file under builds.production like so:

```
{
  "build": {
    "production": {
      "cache": {
        "key": "string" // <- this can be set to any value
      }
    }
}
```

**Comment by Norfeldt** [comment]
I find it strange that this does not work:

```json
  "build": {
    "simulator": {
      "channel": "staging",
      "ios": {
        "simulator": true
      },
      "developmentClient": true,
      "env": {
        "APP_ENVIRONMENT": "development"
      },
      "cache": {
        "disabled": true
      }
    },
```

**Comment by Norfeldt** [comment]
`eas build --clear-cache` worked for me

**Comment by brianmuks** [comment]
> 👍 Using `expo doctor` was very helpful to resolve the issue (incompatible package versions).

Very helpful. You saved my day. Thanks

**Comment by Durotemy** [comment]
i have the same issue 

Error: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Some of the pods used in your project depend on different versions of the same pod. See logs for more information.
  - If you are caching Podfile.lock using "cache" field in eas.json, then versions there might not match required values in Podspecs of some installed libraries. To fix this, you can re-run build command with "--clear-cache" option, or select "Clear cache and retry build" on the build page.
  
  what do i do

**Comment by Durotemy** [comment]
i have the same issue 

Error: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Some of the pods used in your project depend on different versions of the same pod. See logs for more information.
  - If you are caching Podfile.lock using "cache" field in eas.json, then versions there might not match required values in Podspecs of some installed libraries. To fix this, you can re-run build command with "--clear-cache" option, or select "Clear cache and retry build" on the build page.
  
  what do i do

**Comment by Ayowalexy** [comment]
@Durotemy 
Have you been able to resolve the issue? Facing a similar issue here

**Comment by Durotemy** [comment]
@Ayowalexy  when i build,  it works perfectly on android but fails on ios

here's my package.json
{
  "name": "nerve",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-native-community/datetimepicker": "7.6.1",
    "@react-native-community/hooks": "^3.0.0",
    "@react-native-community/netinfo": "11.1.0",
    "@react-native-picker/picker": "^2.6.1",
    "@react-navigation/bottom-tabs": "^6.5.12",
    "@react-navigation/drawer": "^6.6.7",
    "@react-navigation/native": "^6.1.10",
    "@react-navigation/stack": "^6.3.21",
    "apisauce": "^3.0.1",
    "babel-plugin-module-resolver": "^5.0.0",
    "cross-spawn": "^7.0.3",
    "dayjs": "^1.11.10",
    "expo": "~50.0.4",
    "expo-app-loading": "^2.1.1",
    "expo-blur": "~12.9.1",
    "expo-camera": "~14.0.4",
    "expo-clipboard": "~5.0.1",
    "expo-constants": "~15.4.5",
    "expo-dev-client": "~3.3.8",
    "expo-device": "~5.9.3",
    "expo-document-picker": "~11.10.1",
    "expo-file-system": "~16.0.5",
    "expo-font": "~11.10.2",
    "expo-haptics": "~12.8.1",
    "expo-image-manipulator": "~11.8.0",
    "expo-image-picker": "~14.7.1",
    "expo-linking": "~6.2.2",
    "expo-location": "~16.5.3",
    "expo-mail-composer": "~12.7.1",
    "expo-media-library": "~15.9.1",
    "expo-notifications": "~0.27.6",
    "expo-print": "~12.8.1",
    "expo-secure-store": "~12.8.1",
    "expo-sharing": "~11.10.0",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-store-review": "~6.8.3",
    "expo-updates": "~0.24.10",
    "flutterwave-react-native": "^1.0.4",
    "formik": "2.2.10",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "6.5.1",
    "query-string": "^7.0.2",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.73.4",
    "react-native-animatable": "^1.4.0",
    "react-native-confetti": "^0.1.0",
    "react-native-confetti-cannon": "^1.5.2",
    "react-native-device-info": "^10.12.0",
    "react-native-document-picker": "^9.1.1",
    "react-native-dropdown-select-list": "^2.0.5",
    "react-native-elements": "^3.4.3",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-html-to-pdf": "^0.12.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-maps": "1.10.0",
    "react-native-maps-directions": "^1.9.0",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-modern-datepicker": "^1.0.0-beta.91",
    "react-native-progress": "^5.0.1",
    "react-native-public-ip": "^1.0.2",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-size-matters": "^0.4.2",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "14.1.0",
    "react-native-text-ticker": "^1.14.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.6.4",
    "yup": "^0.32.11",
    "yup-password": "^0.2.2",
    "yup-phone": "^1.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "eslint": "8.10.0"
  },
  "private": true,
  "resolutions": {
    "@expo/config-plugins": "~7.8.2",
    "@expo/prebuild-config": "~6.7.0"
  }
}
