### ISSUE TITLE
[expo updates] Various bugs and crashes when an OTA patch is applied

### ISSUE THREAD

**Issue by computerjazz** [expo/expo#15253]
### Summary

I ran into various bugs and crashes that occurred on app reload after a new OTA patch was applied in an expo bare workflow project. I eventually found fixes for all of them, but I'm documenting here as a reference for future developers. These aren't necessarily bugs with expo-updates, but are potential gotchas as a result of initializing JS twice (once on launch, once on reload when patch applies). It would be nice if expo-updates could more reliably reload the app from a "clean slate" to avoid these issues.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment
```
Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
      Watchman: 2021.11.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- [iOS]: After OTA patch is applied, react native gesture handler events don't work, reanimated styles are not applied. 
   - Solution: wrap the app root in a `GestureHandlerRootView` component.
- [Android]: App crashes when patch is applied, then patch is applied successfully on relaunch, `Abort` error reported in Sentry. This was the trickiest one to solve. The sentry error included a reference to Reanimated: `reanimated::EventHandler::receiveEvent` but that seems to be a red herring. After running `logcat` when the patch applies I saw: `java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by Timing`, followed by `Invoking JS callback after bridge has been destroyed.` and `JNI DETECTED ERROR IN APPLICATION: java_object == null` and finally `Runtime aborting...`.  The Reanimated error above seems to be a side effect of that abort, not the cause.

  After much trial and error, I found that this issue was caused because I have `SplashScreen.hide()` called in a `setTimeout` at the root of my app. This comment helped narrow that down: https://github.com/facebook/react-native/issues/32149#issuecomment-937393641 . 
  - Solution: call `clearTimeout` before calling `Updates.reloadAsync()`
- [iOS/Android]: `Cannot use t "__Schema" from another module or realm. Ensure that there is only one instance of "graphql" in the node_modules directory.`
  - Solution: bumping `graphql` to >= 15.5.1 fixed it: https://github.com/graphql/graphql-js/releases/tag/v15.5.1

**Comment by brentvatne** [comment]
which version of expo-updates is installed in your app?

**Comment by computerjazz** [comment]
ah yeah, that was another piece of the puzzle. I noticed several patch releases going into expo-updates and I upgraded as I saw those go in. However, all of the issues above were still there using:
```
expo-updates@~0.10.15:
  version "0.10.15"
```
