### ISSUE TITLE
contentOffset.y gives different values on different android versions

### ISSUE THREAD

**Issue by borasumer** [expo/expo#15256]
### Summary

When I get the y value in onMomentumScrollEnd, it gives me the height of the scrollView as I scroll, iOS gives me correct height which is index*renderedItemHeight, and the android on expo slack device also gives me the correct height, but on a physical android device I get slightly altered numbers, and not sure why it is that way. My physical device is running on Android 11.

Value I get from my device that runs the expo slack app

SM-G975W:
ev.nativeEvent.contentOffset.y: 64.85713958740234

Values I get from the Android device on the expo slack app
Android SDK built for x86:
ev.nativeEvent.contentOffset.y: 65

65 is the height of the rendered item, but on my physical device is 64.85713958740234 for some reason, can't wrap my mind around this.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.12.11 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.6.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.11
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

[Expo Snack](https://snack.expo.dev/@borasumer/function-component-example)

**Comment by brentvatne** [comment]
this sounds like an issue with react-native. you may want to try searching https://github.com/facebook/react-native/issues to see if this has been reported or fixe
