### ISSUE TITLE
`exp publish` hangs on CircleCI when using SDK 25

### ISSUE THREAD

**Issue by Zacqary** [expo/expo#1525]
Posted about this here: https://forums.expo.io/t/exp-publish-hangs-on-building-android-bundle-on-circleci/7713

### Environment

```
Environment:
  OS: Linux 4.4
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0

Diagnostics report:
-[exp] Request failed with status code 500
[exp] Error: Request failed with status code 500
    at createError (/home/circleci/project/product-ui/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/circleci/project/product-ui/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/circleci/project/product-ui/node_modules/axios/lib/adapters/http.js:191:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

App target is iOS and Android

### Steps to Reproduce

1. Create a project that uses Expo SDK 25
1. Create a job for this project on CircleCI that executes `exp publish`
1. Run the job and watch the output

### Expected Behavior

iOS and Android bundles will build and publish to Expo.

### Actual Behavior

`Building Android bundle` reaches 100%, and then nothing happens. No error message, nothing. Depending on your CircleCI settings, the job will time out in 10-20 minutes because of no output.

### Workaround

Downgrading to SDK 24 allows the build and publish to succeed as expected.

**Comment by ccheever** [comment]
Thanks for the report. We'll start looking at this. Sorry about that.

**Comment by ccheever** [comment]
Hi-

I think a workaround for now would be to pass in `--max-workers=1` to `exp`.

jest isn't aware of how to find out the correct number of cpus when its inside of a docker container
and there's some bug somewhere in its multi-worker IPC stuff that deadlocks when there are too many workers for the resources available.

I believe this is fixed in the code now for the upcoming SDK26 release but this workaround should work for now with SDK25.
https://github.com/expo/universe/blob/f91f1f6a9bdbdaf69cbeae40f775830648a2171f/tools/powertools/src/XDL.js#L192

**Comment by Zacqary** [comment]
@ccheever `exp publish --max-workers=1` fails on `unknown option `--max-workers'`. Is there some other way I should be passing it?

**Comment by Zacqary** [comment]
Looks like updating to exp 50.x.x made this work. `--max-workers 1` was the syntax
