### ISSUE TITLE
Stuck on "Checking for new update"

### ISSUE THREAD

**Issue by DJ-Icebear** [expo/expo#15250]
### Summary

JS-bundle produced by `expo-build` hangs on "checking for new update". Running `expo start --dev-client` in the same state works and loading the bundle from there with the same dev-client works fine.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

    "expo-dev-client": "~0.6.3",
    "expo": "~43.0.3",
    "expo-updates": "~0.10.15",
    
Dev-client generated by `eas build --profile development --platform android`
 from: `eas-cli/0.37.0 darwin-x64 node-v14.18.0`
 
 

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v14.18.0/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/prototyp/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 18, 21, 22, 23, 24, 25, 28, 29, 30
        Build Tools: 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 27.0.0, 27.0.1, 28.0.3, 29.0.2, 30.0.2
        System Images: a...google_apis | Google APIs Intel x86 Atom Sys..., a...-tv | Android TV ARM EABI v7a System..., a... | Android TV Intel x86 Atom Syst..., a...ear | Android Wear ARM EABI v7a Syst..., a...ndroid-wear | Android Wear Intel x86 Atom Sy..., a...-23 | Intel x86 Atom, a... | Intel x86 Atom_64, a...pis | Google APIs ARM EABI v7a Syste..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ..., a... | Android TV Intel x86 Atom Syst..., a...fault | ARM 64 v8a, a...ult | ARM EABI v7a, a...-24 | Intel x86 Atom, a... | Intel x86 Atom_64, a..._apis | Google APIs ARM 64 v8a System ..., a...pis | Google APIs ARM EABI v7a Syste..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ..., a...s_playstore | Google Play Intel x86 Atom Sys..., a... | Android TV Intel x86 Atom Syst..., a...ear | Android Wear ARM EABI v7a Syst..., a...ndroid-wear | Android Wear Intel x86 Atom Sy..., a..._apis | Google APIs ARM 64 v8a System ..., a...pis | Google APIs ARM EABI v7a Syste..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ..., a...s_playstore | Google Play Intel x86 Atom Sys..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...google_apis | Google APIs Intel x86 Atom Sys...
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.3 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. expo init
2. Install one native package (I used `react-native-agora` which requires WebRTC)
3. Create a custom development client using `eas build`
4. Install .apk on real Android device (Samsung Galaxy S20+)
5. Run `expo start --dev-client` and make sure the app works and is able to run.
6. Run `expo publish`
7. Scan QR-code and open on same Android device
8. First time I do this, my app is stuck on the splash screen, showing the text at the bottom: "New update available, downloading"
9. All subsequent times I try opening the published URL, the app is suck on same splash screen, showing "Checking for new update"

**Comment by DJ-Icebear** [comment]
I can add that running `expo --dev-client` in production mode also works

**Comment by brentvatne** [comment]
i'm going to reopen this issue for now because it was created before we updated the issue template to always ask for a reproducible example rather than just steps. also shared with the dev client team

**Comment by tcdavis** [comment]
Hi @DJ-Icebear,

> My use-case is that I want to quickly load different javascript bundles with the same development client, without the need for rebuilding. (as long as the runtime is compatible of course)

This is precisely why we built expo-dev-client, and I have just confirmed that it does work in the versions you are using.

A couple clarifying questions, since I don't think I can understand what you are doing from your description:

> 7. Scan QR-code and open on same Android device

What QR code are you scanning?  How did you generate it?

> this problem was solved by removing the "developmentClient": true flag from my eas build profile. 

Does this mean that when you install and launch the resulting APK you are not stuck on checking for new update?

**Comment by rifle2000** [comment]
I have the similar problem. In local environment everything works fine and application runs but if I publish app (expo publish) and try to open it from generated link it stuck on splash with message "Checking for new update..."

**Comment by rifle2000** [comment]
Ok so update on my part. My problem was absent "scheme" in app.json (despite it isn't used in expo app but I am using expo-linking lib). I went back and forth to confirm this and it is reproducible. (https://docs.expo.dev/guides/linking/#in-a-standalone-app)
Problem is that I read many people have this issue and "cures" it in many different ways so the problem may have different origins. There is no way of diagnosing this because in development everything seems fine then you go publish and surprise surprise it doesn't work and give nothing which tells you what's wrong.

**Comment by tcdavis** [comment]
Hi @rifle2000, I suspect there is something we could improve to make the issue(s) you and @DJ-Icebear encountered easier to resolve, but we'll need some more help from you to understand how you got stuck on the "checking for new update" screen. 

How were the "generated links" created? How did you try to open them?

**Comment by rifle2000** [comment]
When I run expo publish the links are at the end of the process. They look like https://expo.dev/@<user>/<project>. At the link You get qr code to scan with expo go and manual link - exp://.....
It isn't so important because I went publish second time and then issue appeared. I didn't have to scan that link. Just opened Expo go and touched recent projects. Expo tried to update the app but got stuck on splash screen and message New update available, downloading... . When You kill it after a while and try tu run again it get stuck on splash again with message "Checking for new update".

**Comment by tcdavis** [comment]
I think I do understand, thank you! If I do understand, though, I am not able to reproduce on my end.
To make sure I have the steps correctly, you are:
running expo publish
opening the project in Expo Go (on Android?) by scanning the QR code from the expo.dev URL
everything works as you expect
making some change and running expo publish again
selecting the app from the "recently opened" section in Expo Go
at this point you encounter the issue

Is that correct?

**Comment by rifle2000** [comment]
Yes it is correct and yes - on Android.
If it will help You I can publish that "broken" app on my release channel for You so You hopefully can see or diagnose on Your side.

**Comment by tcdavis** [comment]
:) thanks, but I don't think that would help to diagnose.  
As a first stab, you might try reducing your fallbackToCacheTimeout to 0 to see if that helps.
If not, you could also create a new project with expo init and going through the steps above to determine if the issue is in your project or related to your device.

**Comment by rifle2000** [comment]
I will try to create simple project and reproduce. From what I am seeing I can conclude that problem lays somewhere in running app in expo go. Update is downloaded but app cannot run. When I kill app on splash screen and try to run it again then it doesn't try to download it again. It seems like it crashes but doesn't give any error. It happened to me before. When published app crashed then it went to expo splash and stayed there.
When I fix the app and publish again it behaves the same giving the same messages but it runs after short while.

**Comment by DJ-Icebear** [comment]
Hey! @tcdavis  Thanks for a quick response!

> A couple clarifying questions, since I don't think I can understand what you are doing from your description:
> > 7. Scan QR-code and open on same Android device
> What QR code are you scanning? How did you generate it?

I'm scanning the QR-code on the project page linked in the output after running `expo publish`, so for example `https://expo.dev/@estercare/esterapp` in my case.
> > this problem was solved by removing the "developmentClient": true flag from my eas build profile.
> Does this mean that when you install and launch the resulting APK you are not stuck on checking for new update?

Yeah exactly. Building a apk without `developmentClient: true` allows me to load the release-channel's js-bundle like I expect. So unlike @rifle2000 I'm using a custom dev-client - not Expo Go.

But maybe there's no error here, it's my expectation that is wrong - I expect to be able to create a custom dev-client and then be able to load any release-channel's js-bundle in that one, as long as they are natively compatible.

We've set up publishing to different release-channels when pushing to different branches, so my use case is that I want to:
1. Build and install a custom dev-client
2. Do expo publish to release-channel 'test'
3. Scan the resulting QR-code and run that js-bundle on my installed dev-client
4. Do another expo publish to release-channel 'staging'
5. Scan the resulting QR-code and run that js-bundle on my installed dev-client

Is this supposed to be possible? 🤔  This is something you can do when using the Expo Go app instead of a custom dev-client right?

**Comment by tcdavis** [comment]
This is possible, but not via the QR on the project page yet.
What you'll need to do instead is use the QR code generation service https://docs.expo.dev/development/development-workflows/#qr-codes
After running `expo publish` the command will report the Manifest URL you should use. It should look something like https://exp.host/@estercare/esterapp/index.exp

**Comment by davidcort** [comment]
I have this same error in Expo SDK 44.

Th expo publish works "fine" but when Expo Go launch the app with the legend in the bottom: "New update available, downloading". 
Freeze in this point :(

**Comment by brentvatne** [comment]
@davidcort - check out https://github.com/expo/fyi/blob/main/splash-screen-hanging.md

**Comment by davidcort** [comment]
I discovered the error. 
In my case i have to use expo run:android and expo run:ios for install a SDK named Zendrive. When publish my app this only runs in Expo Go which not compatible with the native code from Zendrive. The app crash with a message that Zendrive is null :(
If a use expo build, works and I can upload the ipa and the bundle android to the Stores.

**Comment by brentvatne** [comment]
you could create a development build for an expo-go-like experience but with any native module :) https://docs.expo.dev/development/introduction/

**Comment by davidcort** [comment]
Wow O.o 
I will take a look tomorrow

Thanks!! :D

**Comment by robozb** [comment]
I experienced same error

**Comment by mungruez** [comment]
Same issue as in the image. I have to download Android Studio and emulate
