### ISSUE TITLE
[android] Cannot read from bundled database. Works on iOS, but not on Android.

### ISSUE THREAD

**Issue by Stophface** [expo/expo#15267]
### Summary

I have a database pre-populated which I have saved here: `/android/app/src/main/assets/foo.db`. I want to move the database from assets to the Document Directory for my App to read from it. I do this like so:

        if (!(await FileSystem.getInfoAsync(FileSystem.documentDirectory + 'SQLite')).exists) {
          await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + 'SQLite');
        }

        await FileSystem.downloadAsync(
            Asset.fromModule(require('../../android/app/src/main/assets/foo.db')).uri,
            FileSystem.documentDirectory + "SQLite/foo.db"
        );

Then i want to access the database like this

        const someDb = SQLite.openDatabase('foo.db');
        someDb.transaction(tx => {
            tx.executeSql("SELECT * FROM bar", [], (tx, results) => {
                for (let i = 0; i < results.rows.length; i++) {
                    console.log(results)
                }
            });
        });

This works on iOS perfectly (note, on iOS I have the database stored in `src/assets/foo.db`). On Android, it seems like SQLite cannot access the database. The `console.log(results)` simply logs nothing. This is weird because when I check with

    console.log(await FileSystem.getInfoAsync(FileSystem.documentDirectory + `SQLite/foo.db`))

The database exists. 
For what its worth, this is my `metro.config.js` file

```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const { getDefaultConfig } = require('@expo/metro-config');
const defaultConfig = getDefaultConfig(__dirname);

module.exports = {
  resolver: {
    assetExts: [...defaultConfig.resolver.assetExts, 'db', 'json'],
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};

```

and `app.json`

```
{
  "name": "AppName",
  "displayName": "AppName",
  "assetBundlePatterns": [
    "**/*"
  ],
  "packagerOpts": {
    "assetExts": ["db", "json"]
  }
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

"expo-asset": "^8.3.3",
"expo-file-system": "^11.1.3",
"expo-location": "^12.1.2",
"expo-sqlite": "^9.2.1",
"expo-task-manager": "^9.2.2",
"@expo/metro-config": "^0.1.84",

### Reproducible demo or steps to reproduce from a blank project

Not sure if that would be helpful here.

**Comment by byCedric** [comment]
Hi @Stophface! A reproducible example or demo isn't just helpful, it's required for us to investigate your issue. Can you create a small repository where you encounter this issue?

**Comment by Stophface** [comment]
Hey Cedric,
thanks for your reply. I am struggling to set up an example project. Creating and empty project and then trying and running it just won't work. Typical React-Native. Why would a fresh created project run from the beginning... Anyway. I'll close this issue till I get it done. Thanks!
