### ISSUE TITLE
react-native-maps is not working with eas-build

### ISSUE THREAD

**Issue by Ayush6543** [expo/expo#15268]
### Summary

I am trying to make react-native-maps work but whenever I open my project it closes and shows ```Something went wrong``` in expo development client.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

``` "expo": "~43.0.2",
 "expo-dev-client": "~0.6.3",
 "react": "17.0.1",
 "react-dom": "17.0.1",
 "react-native": "0.64.3",
 "react-native-maps": "^0.28.0"
```

### Environment

```
Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.5.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.7.5 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```
import * as React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet, Text, View, Dimensions } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <MapView style={styles.map} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
});
```

**Comment by byCedric** [comment]
Hi @Ayush6543! Did you follow the steps to configure `react-native-maps`, [as described here](https://docs.expo.dev/versions/latest/sdk/map-view/#configuration)?

> No additional configuration is necessary to use react-native-maps in Expo Go. However, once you want to deploy your standalone app you should follow instructions below.

**Comment by mulenatni** [comment]
the same error please

**Comment by bleedingAyush** [comment]
I read google maps docs and it is saying that I will need to pay for it, to get it working.

**Comment by BudAzimbud** [comment]
> aps docs and it is saying that I will need to pay for it, to get it working.
so we have api key google maps?
