### ISSUE TITLE
Can fcm work with expo?

### ISSUE THREAD

**Issue by ivandiazmolina** [expo/expo#1526]
Hi!
Its possible to have expo with fcm? now my application works with fcm and I'm migrating it to expo, I dont want to have 2 methods with 2 tokens (token fcm and token expo)

Thanks in advance. Regards!

**Comment by esamelson** [comment]
Hi there @ivandiazmolina - unfortunately it is not possible to use FCM with Expo currently :( You'll need to either move entirely over to Expo's push service, or detach and install something like react-native-fcm in order to use both.
