### ISSUE TITLE
expo-location silently adds the the permission "ACTIVITY_RECOGNITION" to AndroidManifest.xml

### ISSUE THREAD

**Issue by syedaffanhamdani** [expo/expo#15264]
### Summary

Even for a bare minimum example as described in [documentation](https://docs.expo.dev/versions/latest/sdk/location/), `expo-
location` module adds the permission "ACTIVITY_RECOGNITION". As a developer I find it bad to add permissions that my app does not need at all.  

Please see the steps to reproduce section below for details how to reproduce it. 

Originally I observed this in manage workflow. 

In order to debug further I switched to bare workflow with `expo prebuild` and then in the android directory ran `./gradlew app:assemble`.

Following log was observed in `/android/app/build/outputs/logs/manifest-merger-debug-report.txt` file

```
ADDED from [io.nlopez.smartlocation:library:3.2.11] ~/.gradle/caches/transforms-3/1265c3081b09f8b5e8adbeb5b2d76e1a/transformed/jetified-library-3.2.11/AndroidManifest.xml:15:5-98
	android:name
		ADDED from [io.nlopez.smartlocation:library:3.2.11] ~/.gradle/caches/transforms-3/1265c3081b09f8b5e8adbeb5b2d76e1a/transformed/jetified-library-3.2.11/AndroidManifest.xml:15:22-95
uses-permission#com.google.android.gms.permission.ACTIVITY_RECOGNITION

```

Now question was which package is adding the dependency to 'io.nlopez.smartlocation' library? answer lies in [expo-location package](https://github.com/expo/expo/blob/2b728c42a42b25223c723d0107f80e7cbfc3e5e1/packages/expo-location/android/build.gradle#L74)

Can someone please guide how to get rid of this permission?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    npmPackages:
      expo: ~43.0.2 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I created a bare minimum project [here](https://github.com/syedaffanhamdani/expo-location-bare/tree/main)

Steps used to create the above project: 
1. create a new expo project with `expo init YOUR_PROJECT_NAME`.   
2. chose option blank template (type script)
3. Copy the dependencies in project.json and location code in App.tsx as described in the  [documentation](https://docs.expo.dev/versions/latest/sdk/location/)
4. add "permissions":[] to android section of app.json so that minimum permissions are generated. 
5. run `eas build --platform android` -> it asks to create a profile, follow along.
7. Add the following to eas profile build section:
```
    "dev": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      }
    },
```
8. Inspect the generated apk with your favorite tool. Mine is aab (`aapt dump permissions YOUR_APK_NAME`)
9. ACTIVITY_RECOGNITION is visible in the permission list

**Comment by syedaffanhamdani** [comment]
I generated the apk using expo build:android --type apk, resulted apk does not has "ACTIVITY_RECOGNITION" permission. So it seems like this has something to do with eas

**Comment by syedaffanhamdani** [comment]
I dug a bit deeper on it. expo build:android calls ends up in  [ expo xdl AndroidShellApp.js#L377](https://github.com/expo/xdl/blob/25dcbab83d532812fdf5f4c1c24a508259e588fa/packages/xdl/src/detach/AndroidShellApp.js#L377) 

which in modifies removes the permissions added by transitive dependencies  [here](https://github.com/expo/xdl/blob/25dcbab83d532812fdf5f4c1c24a508259e588fa/packages/xdl/src/detach/AndroidShellApp.js#L941) 

Such a mechanism seems to be missing for the eas build. 

@byCedric  am I going in the right direction? Does it make sense to add such a blacklisted permission list in [expo-updates](https://github.com/expo/expo/blob/master/packages/expo-updates/scripts/createManifest.js) if yes I can work on it and create a pull request.

Many thanks in advance.

**Comment by johnculviner** [comment]
I was having a similar issue. Try using 
[android.blockedPermissions](https://docs.expo.dev/versions/latest/config/app#blockedpermissions) keys in your [app config](https://docs.expo.dev/workflow/configuration).

Reference: https://docs.expo.dev/guides/permissions/#android

**Comment by lorissikora** [comment]
Sorry for necro-bumping, but it seems like this fix no longer works. Has anybody found a solution to this issue?

**Comment by JamesHemery** [comment]
I'm having the same problem, and despite adding it to blockedPermissions it continues to give me an error on the Google Play Store...

```
<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" tools:node="remove"/>
```

![image](https://github.com/user-attachments/assets/1da424b7-fcd6-4b8c-9cf5-c651a5f4901a)

**Comment by Exulenood** [comment]
Can confirm:
Editing the app.config.ts worked:
```
android: {
    permissions: [
        "ACCESS_COARSE_LOCATION",
       ...
      ],
      blockedPermissions: ["ACTIVITY_RECOGNITION"],
 ...
 ```
 As desired, the app is no longer recognised as "health app" on the play store.
