### ISSUE TITLE
Expo camera more zoomed in than default iPhone Camera

### ISSUE THREAD

**Issue by cooperjbrandon** [expo/expo#1527]
When implementing the expo camera, the camera is more zoomed in than default iOS native camera. (Both cameras have zoom of 0 on). Has anyone else noticed this? Is there a way to have the expo camera be less zoomed than 0?

Here is a snack of what I'm talking about:

https://snack.expo.io/@brandon_altschool/camera-snack3

It’s pretty straight forward (just renders the expo-camera component).

If you run that code, and then switch to the ios native camera, you’ll notice that the ios native camera is more zoomed out than the expo camera. Both cameras have zoom of 0.

Corresponding issue in the expo forum: https://forums.expo.io/t/expo-camera-more-zoomed-in-than-default-iphone-camera/7371

**Comment by aalices** [comment]
Hi @cooperjbrandon thanks for noticing this! I'm looking into it and will let you know if I manage to fix this.

**Comment by aalices** [comment]
Hey! Yeah, I found the reason but having this highest quality preview/photos is not possible when recording a video or having face detector on so I am working on the best solution to be able to use the best quality :)

**Comment by cooperjbrandon** [comment]
Thanks for the update!

**Comment by jeremiahk** [comment]
I see the issue is closed, but I am still seeing it on Expo 31.0.2.

**Comment by joehdodd** [comment]
@jeremiahk Yeah, I'm having the same issue on Expo 32.0.0.

**Comment by codeurge** [comment]
I'm still seeing this issue on 32.0.0 as well. Switching back and forth between the RN camera and the default Camera app, it appears the Expo camera is using a zoom / mode similar to the "Portrait" setting whereas the other modes "Photo, Square, etc" are more zoomed out to start than Portrait.

I haven't looked at the Expo code at all to verify this, just throwing out an observation.

**Comment by jesse-wang** [comment]
Why is there no one taking care of this issue?

**Comment by juanpujol** [comment]
v33.0.7 same issue.

**Comment by atait-tva** [comment]
Is this issue still being worked on? We are developing an application which will be used to take photo's of larger machines from different sides. In the current state the photographer needs to take a position at a distance from each side of each machine which is a major loss of time.

**Comment by impactcolor** [comment]
Plus 1 million

**Comment by ksairi** [comment]
any updates?

**Comment by niltype22** [comment]
I ran into this issue as well

**Comment by niltype22** [comment]
@aalices has this been deprioritized or just forgotten?

**Comment by simonjacks1986** [comment]
Has anyone had any luck with this issue? I'm stumped!

**Comment by IDEDOnline** [comment]
Just +1 to keep the thread open as it seems to be getting a general lack of attention.

**Comment by sean-johnson** [comment]
+1.     2 years and counting, pretty important issue

**Comment by brentvatne** [comment]
why are you piling on to this thread when there is an open issue already? :P 

https://github.com/expo/expo/issues/5437
