### ISSUE TITLE
Document Picker crash app when open .srt file

### ISSUE THREAD

**Issue by solominh** [expo/expo#15274]
### Summary

- Document Picker cause app crash when opening a strange file type on iOS (in my case .srt file)
- This only happen on real device iPad and iPhone 12 simulator when open strange file type .srt file (fine with pdf file)
- iPhone 11 real device is fine when open .srt file
- In Expo SDK 42, iPad can not open .srt file (cannot select .srt file)
- In Expo 43, iPad can open but crash 

- Error messages:
  - Failed to associate thumbnails for picked URL
  - Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x600002e5cc30 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
  - Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]'

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

- iPhone 12 (iOS 15) simulator
- iPad gen 6 real device

### Reproducible demo or steps to reproduce from a blank project

Opening .srt (subtitle file type) will crash app

**Comment by solominh** [comment]
Reproducible demo or steps to reproduce from a blank project:
https://snack.expo.dev/M24z-WKgN

Step 1: Download .srt file
Step 2: Open .srt file => app crash

**Comment by solominh** [comment]
- I have located the bug => mimeType is null for .srt file 
![image](https://user-images.githubusercontent.com/13938331/143289441-1e239b7a-7534-4d70-bb79-53cebdcec91f.png)

- My current fix is just add a constant string
![image](https://user-images.githubusercontent.com/13938331/143289621-ac023bc9-6d54-4f25-8e7d-6c960a1e4eb2.png)

**Comment by andrii-yar** [comment]
I still have this issue in expo 52 with new arch, but it's for more file types, including pdf.
I pick files like that: 

```
const handleFilesPick = async () => {
		try {
			const result = await DocumentPicker.getDocumentAsync({
				type: '*/*',
				multiple: true,
				copyToCacheDirectory: true,
			});

			if (result.canceled) {
				onError?.('File picking was canceled');
				return;
			}

			setFiles(result.assets.length ? result.assets : null);
			onSuccess?.(result);

			// Close the action sheet after selecting files
			onClose?.();
		} catch (err) {
			console.error('Error picking document:', err);
			onError?.('File picking was canceled');
		}
	};
```
any thoughts why the native module throws errors?

Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x600000d908a0 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found"
UserInfo={NSDescription=Generation not found}}}
