### ISSUE TITLE
expo-web-browser WebBrowser.openAuthSessionAsync doenot allow app switch for MFA etc on Android

### ISSUE THREAD

**Issue by GSingh01** [expo/expo#15276]
### Summary

```
"expo-linking": "^2.4.2",
"expo-web-browser": "^10.0.3"
```
### Issue:
expo-web-browser WebBrowser.openAuthSessionAsync doenot allow app switch, as a result if user wants to enter a secure code that is received via another notification or app then upon switch the browser is dismissed.

Setting showRecents to true allows this but then browser remains open causing issues during next session.

### Expected:
Browser should not close upon switching app and should get closed when redirected back to app.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

not applicable since issue is in expo-web-browser

### Reproducible demo

```
WebBrowser.openAuthSessionAsync(
        "https://my/login/url",
        "myapp://auth",
      );
```

OR
```

WebBrowser.openAuthSessionAsync(
        "https://my/login/url",
        "myapp://auth",
        {
          showInRecents: true
        }
      );
```

**Comment by brentvatne** [comment]
`showInRecents` is indeed a good workaround at the moment. see existing issue https://github.com/expo/expo/issues/8072

**Comment by GSingh01** [comment]
@brentvatne i dont understand why this is closed, going from above post, this is still not fixed. Can we please fix this since it can be a major issue with MFA.

**Comment by GSingh01** [comment]
also @brentvatne another similar lib had issue and below seesm to solve it to some extent but expo-web-browser doesnot have that forceCloseOnRedirection option
https://github.com/proyecto26/react-native-inappbrowser/issues/153

**Comment by brentvatne** [comment]
@GSingh01 - you are welcome to open a pull request to fix it or to use that other library :) we will work on it at some point but it's not a priority at the moment.

**Comment by GSingh01** [comment]
@brentvatne so spent lot of time setting up expo on my local to contribute and found out that if i run it using bare workflow app it works as expected but if i use expo go app it doesnot redirect correct, f
The test i ran from 
1. cd to apps/bare-expo 
2. **expo run:android** for bare work flow and **expo start** for expo go
3. APIs ->  WebBrowser 
4. **Toggle off Recents** and and **toggle on Should prompt**
5. Click Open web auth session 

follow above steps in bare workflow app vs expo go app and you will notice it work fine in bare workflow whereas go app fails to redirect back.

Any insight will be helpful
