### ISSUE TITLE
'React/RCTEventDispatcherProtocol.h' file not found

### ISSUE THREAD

**Issue by dfabreguette-ap** [expo/expo#15271]
### Summary

After I added "expo-web-browser" module, the error showed up after a "pod install" from ios folder.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.1 - ~/.nvm/versions/node/v15.8.0/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/davidfabreguette/.rvm/rubies/ruby-2.7.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.15.0 => 0.15.0 
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ^0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. I added 'expo-web-browser' npm module with a "yarn add"
2. I ran "pod install" from ios folder
3. I cleaned up build folders with xcode
4. I ran the app with xcode
5. I encountered the following error : 'React/RCTEventDispatcherProtocol.h' file not found

<img width="1498" alt="Capture d’écran 2021-11-22 à 12 37 39" src="https://user-images.githubusercontent.com/7055931/142867073-1cab29d6-3e5b-4df6-826b-7ee30a529bb7.png">

**Comment by dfabreguette-ap** [comment]
I think I found my problem here, as my RN version was 0.63.4 (not 65+) :

<img width="921" alt="Capture d’écran 2021-11-22 à 14 15 02" src="https://user-images.githubusercontent.com/7055931/142868188-c4370a65-3cbc-493e-b3c0-8fe7ccb6c802.png">

I'm trying out the upgrade and I'll close the issue myself if it's working.
Sorry for the fake report !

**Comment by byCedric** [comment]
No problem, glad you found the cause 😄  I would also want to recommend installing Expo modules with `expo install <package>`, this works for both yarn and npm but takes your current Expo SDK version into account. It would find the right version for your RN/Expo version, and install the one compatible!

Hope this helps!

**Comment by dfabreguette-ap** [comment]
@byCedric thanks ! I was confused by this command ! (wether to use yarn or expo).
It solved my issue even though I have some other things to solve due to my RN upgrade :/
Have a nice day ;)

**Comment by dfabreguette-ap** [comment]
Actually I still have a problem, since last Expo SDK is supporting RN until v0.64.
how can that happen ? Have an expo module using a RN 0.65 feature not yet supported by Expo SDK ? 

https://blog.expo.dev/expo-sdk-43-aa9b3c7d5541
https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/?redirected

**Comment by dfabreguette-ap** [comment]
here's the reference : https://github.com/expo/expo/blob/d4c4ca832c776c89ea39097ef0413ac9f6c017f1/packages/expo-modules-core/ios/NativeModulesProxy/EXNativeModulesProxy.mm#L46

**Comment by byCedric** [comment]
I think in your case, you might be using a version of `expo-web-browser` we released as a fix for some people. We are always continuing work on the next SDK. Because you are running SDK 41, you shouldn't have any `expo-modules-core` references.

If this happened after installing `expo-web-browser`, it means you installed a version that's too new for the SDK you are using. What happened when running `expo install expo-web-browser`?

**Comment by dfabreguette-ap** [comment]
All right, I think this is the issue, since I installed it with yarn.
I'm removing it with yarn, then re-installing it with expo.

**Comment by byCedric** [comment]
It should update the version if you have it installed already, but removing it and installing again should work too

**Comment by byCedric** [comment]
@dfabreguette-ap, did you resolve this?

**Comment by dfabreguette-ap** [comment]
@byCedric yes sorry for  the delay ! I had to downgrade back to SDK41, uninstall / reinstall expo-web-browser module and it worked !
Thanks for your time !
