### ISSUE TITLE
Dev client build fails xcodebuild in expo-modules-core

### ISSUE THREAD

**Issue by butterfly-valley** [expo/expo#15281]
### Summary

Identical issue to #14948. My Mac only supports Xcode 12.4 which is fine since I do EAS builds now and do not need it other than for screenshots. Now when I tried to manually downgrade the SDK to version 41 which in theory is compatible with my Xcode I got the same error. I then proceeded to create a dummy project, downgraded Expo to SDK 41 but the error persists as per below. Note that Xcode version needs to be 12.4 to reproduce the error correctly. I have also installed expo-dev-client as described in the issue above to no avail.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

Expo SDK 41

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

git clone https://github.com/butterfly-valley/test_sdk-41.git
npm i
expo run:ios

**Comment by butterfly-valley** [comment]
So it seems that despite me specifying SDK as 41 in package.json upon dependency installation the version is bumped to 43, can someone explain how to cleanly downgrade to SDK 41 from 43? Thank you.

**Comment by byCedric** [comment]
The Expo SDK version is determined by the installed module version in your `node_modules/expo` folder. From your `package.json`, I see that the SDK version is set to 43. That means it will assume and use Expo SDK 43. Setting this back to `41.x.x`, removing your `node_modules` and reinstalling them should get you back on SDK 41.

You can also run `expo upgrade 41`, which will do that and use all Expo module versions compatible with SDK 41.

Hope this helps!
