### ISSUE TITLE
EAS Build Location.requestBackgroundPermissionsAsync() NullPointerException

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#15288]
### Summary

I'm developing an app on expo since SDK 38 , today i faced a problem with expo-notifications , so i had to use eas build in order to patch the module . however there is an issue with expo-location **on EAS BUILD ONLY** 

if i call **Location.requestBackgroundPermissionsAsync()**; while the app is **backgrounded**   i get this Exception :

`java.lang.RuntimeException: Unable to resume activity {com.nexus.taxiTerangaChauffeur/com.nexus.taxiTerangaChauffeur.MainActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4519)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4551)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7889)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:220)
        at expo.modules.location.LocationModule.handleBackgroundLocationPermissions(LocationModule.java:874)
        at expo.modules.location.LocationModule.lambda$requestBackgroundPermissionsAsync$3$LocationModule(LocationModule.java:216)
        at expo.modules.location.-$$Lambda$LocationModule$soRisceyv7rPN0v7taQGQLORMXw.onResult(Unknown Source:4)
        at org.unimodules.adapters.react.permissions.PermissionsService$createListenerWithPendingPermissionsRequest$1.onRequestPermissionsResult(PermissionsService.kt:255)
        at com.facebook.react.ReactActivityDelegate$2.invoke(ReactActivityDelegate.java:171)
        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:102)
        at com.facebook.react.ReactActivity.onResume(ReactActivity.java:57)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1457)
        at android.app.Activity.performResume(Activity.java:8264)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4509)`

this happens on **SDK 42 AND 43** + **EAS BUILD** , **works great on Expo build**

SDK 42 "expo-location": "~12.1.2",
SDK 43 "expo-location": "~13.0.4",

So i think it's an EAS Related issue .

So i'm stuck , either  broken notifications with expo build , or a broken location with EAS BUILD

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42, 43

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ~42.0.1 => 42.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ^0.17.5 => 0.17.5
    Expo Workflow: managed

### Reproducible demo

My code is simple , i have a socket.io event listener , when the app is backgrounded and i send a message to this listener the exception happens .

` socket.on(cancelBooking, async function (passengerData) {
        let { status } = await Location.requestBackgroundPermissionsAsync();

      });`

**Comment by syedaffanhamdani** [comment]
Could you also share the permissions generated in AndroidManifest,xml by EAS?

**Comment by islamouzou** [comment]
@syedaffanhamdani where can i find the generated AndroidManifest,xml  ?? i'm on managed workflow and i used eas build

**Comment by syedaffanhamdani** [comment]
You inspect the generated apk file by using tools such as aapt or aapt2 which are part of Android Build Tools:
`aapt d badging PATH_TO_YOUR_APK`
More info [here](https://developer.android.com/studio/command-line/aapt2)
If you have Android Studio installed you should have build tools installed automatically.

**Comment by syedaffanhamdani** [comment]
Also please double check the [Background Location Methods requirements](https://docs.expo.dev/versions/latest/sdk/location/#background-location-methods)

**Comment by islamouzou** [comment]
@syedaffanhamdani i did what you asked , these are the permissions included in the APK :

` <uses-permission
        android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-permission
        android:name="android.permission.CAMERA" />

    <uses-permission
        android:name="android.permission.CAMERA_ROLL" />

    <uses-permission
        android:name="android.permission.FOREGROUND_SERVICE" />

    <uses-permission
        android:name="android.permission.INTERNET" />

    <uses-permission
        android:name="android.permission.MEDIA_LIBRARY" />

    <uses-permission
        android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-permission
        android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <uses-permission
        android:name="android.permission.RECORD_AUDIO" />

    <uses-permission
        android:name="android.permission.SYSTEM_ALERT_WINDOW" />

    <uses-permission
        android:name="android.permission.VIBRATE" />

    <uses-permission
        android:name="android.permission.WAKE_LOCK" />

    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-permission
        android:name="android.permission.ACCESS_NETWORK_STATE" />
`

**Comment by islamouzou** [comment]
@syedaffanhamdani  These are the permissions :

<uses-permission
        android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-permission
        android:name="android.permission.CAMERA" />

    <uses-permission
        android:name="android.permission.CAMERA_ROLL" />

    <uses-permission
        android:name="android.permission.FOREGROUND_SERVICE" />

    <uses-permission
        android:name="android.permission.INTERNET" />

    <uses-permission
        android:name="android.permission.MEDIA_LIBRARY" />

    <uses-permission
        android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-permission
        android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <uses-permission
        android:name="android.permission.RECORD_AUDIO" />

    <uses-permission
        android:name="android.permission.SYSTEM_ALERT_WINDOW" />

    <uses-permission
        android:name="android.permission.VIBRATE" />

    <uses-permission
        android:name="android.permission.WAKE_LOCK" />

    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-permission
        android:name="android.permission.ACCESS_NETWORK_STATE" />

**Comment by byCedric** [comment]
I think Android does not allow you to request permissions outside of the user's scope. If the app is already backgrounded, that means the user doesn't see the permission request. It has to be requested before the app is backgrounded, and has to be granted by the user.

Can you provide an example repo where we can trigger this exact error?

**Comment by islamouzou** [comment]
@byCedric Thank you for looking into this , maybe you're right , but how do you explain the fact that the exception only triggers on EAS ? maybe it's handled somehow on expo build , i don't know .

Anyway , i have created a minimal example and checked again the exception 👍 


Steps to reproduce : 

1 -  Open the app ,
2 - The App will ask for foreground location permission  , Grant it .
3 -  The app will connect through socket.io to the server in the code .
4 -  Put the app in background state
5 - Go to this url :  http://taxiteranga.northeurope.cloudapp.azure.com:4000/test  ( everytime you enter the url or refresh the page it will send a socket message to the app )
6 - put the app back to foreground state , at this point it will crash .

if you build this with the classic expo build , there is no crash 


thank you again for looking into this . 


[backgroundLocationPermissionTest.zip](https://github.com/expo/expo/files/7597169/backgroundLocationPermissionTest.zip)

**Comment by islamouzou** [comment]
@byCedric Any luck reproducing the bug ?
