### ISSUE TITLE
exp build:ios cant generate ipa without paid account

### ISSUE THREAD

**Issue by marcosmartinez7** [expo/expo#1528]
Hi, 

i want to generate a .ipa from my expo app

i have generated an .apk with exp build:android without any problems, but when i run exp build:ios i get this error:

**exp build:ios**

then i put my Apple id and password and i get:

> 
> ? What's your Apple ID? ***********
> ? Password? ********
> [exp] Validating Credentials...
> Error: spawn C:\Windows\system32\bash.exe ENOENT
>     at exports._errnoException (util.js:1020:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:367:16)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> 

exp version 49.2.2
npm version 3.10.10
exp sdk in app.json     "sdkVersion": "25.0.0",

**Comment by marcosmartinez7** [comment]
After a little research i have found this: https://forums.expo.io/t/not-able-to-create-ipa-file-using-command-exp-build-ios-c/6885/4

i did that (running this command in Windows PowerShell: "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux")
)

i also update my exp client to the latest version and changed the package.json dependencies according to this guide: https://blog.expo.io/expo-sdk-v25-0-0-is-now-available-714d10a8c3f7

now im getting this error:


> ? What's your Apple ID? ******
> ? Password? ********
> [exp] Validating Credentials...
> W i n d o w s   S u b s y s t e m   f o r   L i n u x   h a s   n o   i n s t a   l e d   d i s t r i b u t i o n s .
>  D i s t r i b u t i o n s   c a n   b e   i n s t a l l e d   b y   v i s i t    g   t h e   W i n d o w s   S t o r e :
>  h t t p s : / / a k a . m s / w s l s t o r e
>  P r e s s   a n y   k e y   t o   c o n t i n u e . . .
> 
> [exp] Error while gathering & validating credentials
> [exp] undefined
> [exp] Set EXPO_DEBUG=true in your env to view the stack trace.

any ideas? ...

**Comment by marcosmartinez7** [comment]
This solved that issue: https://stackoverflow.com/questions/44829878/trying-to-use-bash-on-windows-and-got-no-installed-distributions-message

i manage to create a unix account

now expo get stuck in validating credentials... 

i am missing something about the ios standalone building?

**Comment by esamelson** [comment]
Hi @marcosmartinez7 - unfortunately you need a paid account in order to create an ipa for TestFlight distribution :( (true everywhere, not just on Expo). Sorry about that! If you want to test without a paid account you'll need to just use the Expo client app.

**Comment by shajeerpk** [comment]
Hi 

first you enable  linux bash
https://blogs.technet.microsoft.com/canitpro/2016/06/07/step-by-step-enabling-bash-on-windows-10/
then check if bash is availble(search  in start menu),then download linux 

there are two option to download   linux

###  1: using cmd **lxrun /install**  
![image](https://user-images.githubusercontent.com/15422533/47473494-68f48b00-d845-11e8-99d7-a5b13a95ba59.png)

2: goto microsoft store then download ubundu
![image](https://user-images.githubusercontent.com/15422533/47473713-4f077800-d846-11e8-9eae-bb99235bb9e7.png)

then serch **ubundu**  in your start menu  ,you will get ubundu terminal
then run following command 

# To immediately start using Bash from the current default Ubuntu distro
lxrun /install /y

# Now, let us try switching into Bash
bash

# Before doing anything in Bash, also ensure your Bahs is updated and upgraded
sudo apt-get update
sudo apt-get upgrade

**Comment by Struemmeck** [comment]
> Hi @marcosmartinez7 - unfortunately you need a paid account in order to create an ipa for TestFlight distribution :( (true everywhere, not just on Expo). Sorry about that! If you want to test without a paid account you'll need to just use the Expo client app.

Hi @esamelson, 
What kind of [paid account](https://developer.apple.com/support/compare-memberships/) is needed? **Apple Developer Program** or **Apple Developer Enterprise Program**?

**Comment by igorbrandao** [comment]
@Struemmeck any of them will work. Enterprise variant is just if you are a company/organisation of some sort instead of an individual.

**Comment by Benzer1406** [comment]
I have the same issue. Why would I need a paid account when I can create an .ipa file with xCode without having a paid account. Apple changed its policy and allows to create .ipa files for pure private testing purposes for free accounts. Why does expo does not support that?

**Comment by AkitakiKou** [comment]
Some suggest ejecting to ExpoKit and then using Xcode to build an `.ipa` file without paid account, but I don't see why Expo itself can't support this. It's totally possible in Xcode, and doesn't violate any terms.

**Comment by esamelson** [comment]
hey @Benzer1406 @AkitakiKou - this is not possible because Apple does not expose or document a public API to do this. If you look at the fastlane docs (an industry standard tool which Expo uses behind the scenes for many Xcode-related tasks) it does not support free accounts either. It's possible in theory, but either Apple needs to publicly document the API or someone needs to figure out (read: reverse engineer) what Xcode is doing, and neither of those things have happened yet 🙂 hope this helps!

**Comment by AkitakiKou** [comment]
> hey @Benzer1406 @AkitakiKou - this is not possible because Apple does not expose or document a public API to do this without Xcode. If you look at the fastlane docs (an industry standard tool which Expo uses behind the scenes for many Xcode-related tasks) it does not support free accounts either. It's possible in theory, but either Apple needs to publicly document the API or someone needs to figure out (read: reverse engineer) what Xcode is doing, and neither of those things have happened yet slightly_smiling_face hope this helps!

Thanks for the kind reply, now I understand why Expo can't support it.

**Comment by IAmAbhishekTomar** [comment]
I chose expo because of lot of good things but after 2 month of development I am slowly realised I made the wrong choice .....

always use pure react native... ☹️☹️☹️☹️
And YES everyone right about this not possible to run 🏃‍♀️ standalone app without paying $99 💰 

Dollars 💵 $ - 99
Rupees ₹ - 6,773.10
Piso - 5,083.79

I don’t have in any currency 💴😔😔😔
I think 🤔- IOS Development is only for rich 🤑  people’s because you have to pay 💰 this 99$ every year........

Thank you everyone for support.
@Expo Team do something about this.
