### ISSUE TITLE
`jest-expo` can't find base config in a monorepo

### ISSUE THREAD

**Issue by shauns** [expo/expo#15282]
### Summary

See previous closed issue: https://github.com/expo/expo/issues/11754

The issue manifests as per the linked issue, "Linking requires a build-time setting 'scheme' in the project's Expo config (app.config.js or app.json) for bare or production apps."

Have done some digging and the issue lies in `jest-expo` and `readExpoConfig`:

```
// This file is under <package>/node_modules/jest-expo/src and we want to
// start looking for app.json under <package>
const nextDirectory = path.resolve(__dirname, '..', '..', '..');
const projectRoot = path.dirname(findUpPackageJson(nextDirectory));
```

This code will not find the project root correctly when `jest-expo` has been hoisted in a monorepo. Changing `nextDirectory` to `process.cwd()` works if running `jest` from within a specific package, but of course no guarantee of that.

I couldn't find anything else in the code base that attempts to find the most relevant `package.json` automatically - re-using that would be ideal. Am happy to submit a PR given a steer there.

Note: symlinking `jest-expo` via `expo-yarn-workspaces` doesn't help, as `__dirname` represents the original location, not the symlinked one.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.0.14 - ~/.nvm/versions/node/v15.3.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

Will provide a stripped down demo once I have one, but hopefully the bug itself is quite clear-cut in the meantime.

**Comment by neb42** [comment]
As a workaround for this I've created an `app.json` at the monorepo root containing:
```
{
  "expo": {
    "scheme": "test-scheme"
  }
}
```

**Comment by shauns** [comment]
This is definitely a bug -- I'm happy to look into a fix, I think the main thing is:

> I couldn't find anything else in the code base that attempts to find the most relevant package.json automatically

That's effectively the bug, the logic for this being insufficiently robust. Am I incorrect to assume that this sort of need exists elsewhere in the codebase? As would make most sense to reuse/match that behaviour.

**Comment by buster95** [comment]
> As a workaround for this I've created an `app.json` at the monorepo root containing:
> 
> ```
> {
>   "expo": {
>     "scheme": "test-scheme"
>   }
> }
> ```

This work for me, but what's the reason to do this?
