### ISSUE TITLE
[Android] Swipe gesture between screens not working properly

### ISSUE THREAD

**Issue by ruiqbarbosa** [expo/expo#15291]
### Summary

After the update to SDK 43, the swipe gesture between screens started not working properly in Android. The screen that is being "swiped" instead of getting in front, automatically passes to the back.

The error can be checked in this [demo](https://gyazo.com/5c3cd47f31197dd4f33265c057fd4167).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^43.0.0 => 43.0.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

Works fine in expo SDK 41 and 42: [demo](https://gyazo.com/036fbc79b53da9ba727a51cf58a75957)

**Not working** in SDK 43: [demo](https://gyazo.com/5c3cd47f31197dd4f33265c057fd4167)

You can check here a [Snack Link](https://snack.expo.dev/@reiomelete/stack-navigator-%7C-react-navigation) reproducing the problem.

**Comment by davidduarteabreu** [comment]
Having the same issue, since I have updated my app to expo SDK 43, please fix that as soon as possible!

**Comment by CarlosBras** [comment]
I have encountered the same issue, please resolve.

**Comment by bowbowbow** [comment]
I have encountered the same issue, too.

**Comment by IsaqueAkamine** [comment]
I have encountered the same issue, too.
