### ISSUE TITLE
White background on all icons

### ISSUE THREAD

**Issue by shettyrahul8june** [expo/expo#153]
Can someone  please let me know about removing the white background that appears on font icons?

      <Ionicons style={ backButton } name="ios-arrow-dropleft" size={ 32 } color="#000" />

![image](https://cloud.githubusercontent.com/assets/8545078/25712694/f171ecb8-310f-11e7-8350-99297da1e143.png)

Thanks in anticipation.

**Comment by sonaye** [comment]
`style={[backButton, { backgroundColor: 'transparent' }]}`

**Comment by skevy** [comment]
@shettyrahul8june @sonaye is correct -- you need to specify the background color as transparent.

**Comment by shettyrahul8june** [comment]
@sonaye @skevy  Thanks a lot.
