### ISSUE TITLE
Zoom doesn't affect camera picture taken on android

### ISSUE THREAD

**Issue by yehudahkay** [expo/expo#1530]
Hi, thanks for the framework!

We have tested the camerja expo app using both nexus 5x and galaxy s8, the zoom changes the view to be more zoomed but the picture is always taken without zoom.

We have the same issue in our app built with the camera component (on ios it does affect picture taken)

**Comment by esamelson** [comment]
Hi, this will be fixed in SDK 26 when it comes out. We're switching back to using an older native Camera API which works better than the one in SDK 25, and it looks like that solves this issue. Sorry for the inconvenience :( @aalices - do you know of any workarounds for this until then?

**Comment by aalices** [comment]
Sorry for that! Yes, this will be fixed after moving to older Camera API but I'll also fix this for the newer one. Unfortunately, I can't think of a reasonable workaround :(

**Comment by ricardovf** [comment]
@aalices is there any update on this? On Android, using the last version of expo, the zoom is not considered when using takePictureAsync. As a workaround im using ImageManipulator.manipulateAsync, but it consumes additional time, so it would be good to get it done on the takePictureAsync. Thanks
