### ISSUE TITLE
[expo-av] Can't set any styles to <Video> on react-native-web

### ISSUE THREAD

**Issue by hirbod** [expo/expo#15319]
### Summary

Setting a `style` prop to `<Video>` won't apply any styles to the actual `<video>` element on **Web**. Not sure if react-native-web is the real problem here or expo-av, since using the default HTMLElement `<video>` (lowercase) works as intended.

The `<Video>` element will be wrapped into a `<div>` and the styles will be applied to the parent `<div>` instead of the HTML5 `<video>` Element. What I've seen so far is, that the Video element always receives an inline style with `object-fit` (value `none` if nothing was supplied) and maybe removing other styles.

This cause various issues on iOS Safari, since the video needs `width: 100%;` and `height: 100%` to fit the parent.
The fitting works without width/height on default desktops but not on iOS Safari, resulting into a cropped video. 

```tsx
  <Video
    style={{
        flex: 1,
        width: 220,
        height: 220,
        alignSelf: "center",
    }}
    source={item.asset}
    resizeMode="cover"
    isLooping
    shouldPlay
    isMuted
   />
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.8 => 0.16.8 
      expo: ^43.0.3 => 43.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed
```

### Reproducible demo

```tsx
import { Video } from "expo-av";

  <Video
    style={{
        flex: 1,
        width: 220,
        height: 220,
        alignSelf: "center",
    }}
    source={item.asset}
    resizeMode="cover"
    isLooping
    shouldPlay
    isMuted
   />
```

**Comment by hirbod** [comment]
not stale

**Comment by hirbod** [comment]
Not stale

**Comment by mlaythe** [comment]
I'm running into the same issue

**Comment by peh** [comment]
still the same in expo@46 expo-av@12.0.2

**Comment by bladey** [comment]
Having the same issue.

**Comment by hirbod** [comment]
Will be fixed with https://github.com/expo/expo/pull/18549
