### ISSUE TITLE
EAS build vs expo build: code executing differences, REPOs with 2 demos of bug (images and fonts)

### ISSUE THREAD

**Issue by psnet** [expo/expo#15326]
### Summary

I tried both build systems and behavior of “back” button in android is different:

In old classic expo build when I press “back” app is not really closed, it is running in background, when I run app again it is opened immediately.

In new EAS build when I press “back” button and run it again (all with same 2 seconds delay) I see splash loading screen which stays visible much less time than when app is really closed (“cold” start) but splash screen means that app is loading again (!) but app was not really (fully) closed. Some code of app works like it is cold start (inits) and some code (mostly animations with “useNativeDriver”) is still running.

This looks very strange.

Are big differences in handling “back” button in these build systems and why on new EAS build I see splash startup screen every time I open app even after 2 seconds? On old expo build system the same code base works as expected (no splash screen on reopen app)

Original discussion is here https://forums.expo.dev/t/eas-build-vs-expo-build-code-executing-differences/59384

The same problem has other users. Such strange behavior is in any project.

--------------

As expo team asked for working examples, I did it. How it was:
---

I just started clear new empty project on SDK 43 and EAS 0.37. With default template demo code all works same as in classic expo build, so I thought maybe problem is elsewhere...

I look how my apps are starting and what can show splash screen and found that I use `expo-asset` module which awaits for assets to be loaded and during that it shows default loader via `expo-app-loading` module.

I caught this bug and made working example. The same code, but different behavior when I press "back" button on android and then after 2 seconds (no matter really how much time) I open app again:

- With classic expo build: app is showing immediately with images, no splash screen visible

- With EAS build: app is quickly showing splash screen (that means assets are loaded again! but WHY?!) and then app is showing and then images are appearing like it is first time "cold" start - every image is loaded with little delay)

So... that means EAS build AND/OR `expo-asset` module produce bug(s). And it is really visible.

P.S. Later I tested this with fonts, same behavior as with assets. See below 2 bug demo examples.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42 and 43

### Environment

SDK: 42 and 43
eas: 0.37.0
node js: v16.6.1
npm: 7.20.3
os: win 10

### Reproducible demo

I caught and tested this with one image, but for better visible effect I added example with 3 big images.

Bug demo # 1 with images
---

Repo with reproducible bug and how to test instructions:
https://github.com/psnet/eastest

Recorded video of this bug with and slowed it 2 times for better visual checking:
https://www.youtube.com/watch?v=9PaCMu4TOPU

Bug demo # 2 with fonts
---

Repo with reproducible bug and how to test instructions:
https://github.com/psnet/eastest2

Recorded video of this bug with and slowed it 2 times for better visual checking:
https://www.youtube.com/watch?v=rkgFkDZVcEo

**Comment by psnet** [comment]
Originally posted this for [EAS cli](https://github.com/expo/eas-cli/issues/799), but I was redirected to this repo

**Comment by doctorrokter** [comment]
As I said in https://forums.expo.dev/t/eas-build-vs-expo-build-code-executing-differences/59384 I can confirm that on my end as well!

However, I use `expo-font`. Behavior is absolutely the same as described in the author's post!

**Comment by islamouzou** [comment]
I can confirm the problem , eas build is not ready for production yet . beside the back button , there is also an issue when launching the app  , when you launch it for the first time it launches from the start , if you kill it and immediatly open it again , it will launch with the latest states and screen as if it was not killed .

**Comment by psnet** [comment]
>there is also an issue when launching the app , when you launch it for the first time it launches from the start , if you kill it and immediatly open it again , it will launch with the latest states and screen as if it was not killed at all .

Yes, I saw this too but it is not easy to catch this.

**Comment by islamouzou** [comment]
> > there is also an issue when launching the app , when you launch it for the first time it launches from the start , if you kill it and immediatly open it again , it will launch with the latest states and screen as if it was not killed at all .
> 
> Yes, I saw this too but it is not easy to catch this.

It happens to me all time , i have a big project i don't know what's causing this exactly , but i'll try to make a demo when i have time . i'm glad that others are facing the same problem :D

**Comment by psnet** [comment]
>i'm glad that others are facing the same problem :D

I hope, expo team can catch these bugs too, because they did not saw problem before real examples were made even if few users approved that problem exists.

**Comment by Kudo** [comment]
with #15378, this would be fixed and the change will be landed in the sdk 44 (coming soon).
