### ISSUE TITLE
[expo-updates] The "directory" argument must be of type string. Received undefined (sdk 43)

### ISSUE THREAD

**Issue by liemdo** [expo/expo#15325]
### Summary

After upgrading to expo 43, expo-updates can't build in EAS with the error

> › Executing expo-updates Pods/EXUpdates » [CP-User] Generate app.manifest for expo-updates
> 
> ❌ Metro encountered an error:
> The "directory" argument must be of type string. Received undefined

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.11.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: 43.0.3 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo

Even though I already set the `ENTRY_FILE` variable in the Bundle React Native code & images steps in Xcode, it still doesn't work as before

> export NODE_BINARY=node
> export ENTRY_FILE=index.ts
> export PROJECT_ROOT="$PROJECT_DIR"/..
> 
> ../node_modules/expo-constants/scripts/get-app-config-ios.sh
> ../node_modules/expo-updates/scripts/create-manifest-ios.sh
> 
> `node --print "require('path').dirname(require.resolve('react-native/package.json')) + '/scripts/react-native-xcode.sh'"`
>

**Comment by byCedric** [comment]
Hi @liemdo! [In our docs we list this as limitation at the moment](https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in):

> If your app depends on a custom "main" entry point, you will need to remove that field from package.json and then create index.js in the root of your project and use registerRootComponent to register your root component. For example, if your app root component lives in src/App.tsx, your index.js should look like the following:
> ...
> Support for custom entry points is in progress and is coming soon.

It may help if you can provide a small repository where we can test your setup. Once we have full support for this, we can validate it with your repo.

Hope it helps!

**Comment by thangavel-21** [comment]
TypeError: Cannot read property 'ExpoUpdates' of undefined, js engine: hermes
 i am facing this error how can i fix this issue ?

**Comment by liemdo** [comment]
Putting `export ENTRY_FILE=index.ts` in Bundle React Native code & images step doesn't work anymore. However, the build succeeds if I define the env variable `ENTRY_FILE=index.ts` in eas.json

**Comment by thangavel-21** [comment]
> Putting `export ENTRY_FILE=index.ts` in Bundle React Native code & images step doesn't work anymore. However, the build succeeds if I define the env variable `ENTRY_FILE=index.ts` in eas.json

In react native, I'm using expo package with support of react-native-unimodules package. In this scenario I'm getting the following error.
TypeError: Cannot read property 'ExpoUpdates' of undefined, js engine: hermes

Packages:

react-native": "0.64.2,
react-native-unimodules": "^0.12.0",
expo/react-native-action-sheet": "^3.8.0",
expo-asset": "^8.1.7",
expo-av": "^9.0.0",
expo-constants": "^9.1.1",
expo-file-system": "^9.0.1",
expo-font": "^8.2.1",
expo-image-manipulator": "^8.2.1",
expo-image-picker": "^8.3.0",
expo-location": "^8.2.1",
expo-media-library": "^11.0.0",
expo-permissions": "^11.0.0",
expo-video-thumbnails": "^5.1.0",

**Comment by FlawaCLV** [comment]
@thangavel-21 I have the same issue. How did you manage to fix it?

**Comment by JB-CHAUVIN** [comment]
Same issue with SDK 49 : 

```
yarn run v1.22.19
$ expo start --android ''
Starting project at /Users/cegedim/Documents/Perso/Perso/RuninTwo/app-backend/mobile
Starting Metro Bundler
› Opening exp://192.168.1.15:8081 on SM_A515F
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.parse (node:path:1450:5)
    at Object.downloadExpoGoAsync (/Users/cegedim/Documents/Perso/Perso/RuninTwo/app-backend/mobile/node_modules/@expo/cli/build/src/utils/downloadExpoGoAsync.js:78:36)
    at async ExpoGoInstaller.ensureAsync (/Users/cegedim/Documents/Perso/Perso/RuninTwo/app-backend/mobile/node_modules/@expo/cli/build/src/start/platforms/ExpoGoInstaller.js:110:32)
    at async AndroidPlatformManager.openProjectInExpoGoAsync (/Users/cegedim/Documents/Perso/Perso/RuninTwo/app-backend/mobile/node_modules/@expo/cli/build/src/start/platforms/PlatformManager.js:62:31)
```
