### ISSUE TITLE
Camera feed is scaled incorrectly on ChromeOS

### ISSUE THREAD

**Issue by mattosborn** [expo/expo#1532]
### Environment

ChromeOS (v64)

### Steps to Reproduce

View a camera feed on a ChromeOS device

### Actual Behavior

Camera feed is scaled incorrectly (vertically stretched)

Resizing the app with the feed open fixes the issue temporarily (until feed is destroyed and recreated).

**Comment by terribleben** [comment]
Hey, is it possible to open a [Feature Request](https://expo.canny.io/feature-requests) with some details about what you think we should support? That enables other people to upvote it and gives us a clean way to keep track of what people want. Thanks! :)
