### ISSUE TITLE
[docs] TaskManager: Task "background-fetch" failed:, [TypeError: undefined is not an object (evaluating 'BackgroundFetch.Result.Failed')]`

### ISSUE THREAD

**Issue by audrew** [expo/expo#15320]
### Summary

I have tried many methods, but this error appears no matter what. I noticed that with older expo-background-fetch versions BackgroundFetch.Result.NewData Result keyword becomes green. But then I receive errors about unimodules which is for bare workflow.  I use expo 43. I think the problem is because of BackgroundFetch.Result.NewData is undefined because the function is triggered until this point. I tried other methods with import, without success too. Please help

```TaskManager: Task "background-fetch" failed:, [TypeError: undefined is not an object (evaluating 'BackgroundFetch.Result.Failed')]```

This is my code, just in case you wonder:

``` 
const [isRegistered, setIsRegistered] = useState(false);
const [status, setStatus] = useState(null);
const BACKGROUND_FETCH_TASK = 'background-fetch';

// 1. Define the task by providing a name and the function that should be executed
// Note: This needs to be called in the global scope (e.g outside of your React components)
TaskManager.defineTask(BACKGROUND_FETCH_TASK, async () => {
    try{
    if (!TaskManager.isTaskDefined(BACKGROUND_FETCH_TASK)) {
        TaskManager.defineTask(BACKGROUND_FETCH_TASK, now);
    }
const now = Date.now();
console.log(`Got background fetch call at date: ${new Date(now).toISOString()}`);

// Be sure to return the successful result type!
return now ? BackgroundFetch.Result.NewData : BackgroundFetch.Result.NoData;
} catch (error) {
    BackgroundFetch.Result.Failed;
}
});

// 2. Register the task at some point in your app by providing the same name, and some configuration options for how the background fetch should behave
// Note: This does NOT need to be in the global scope and CAN be used in your React components!
async function registerBackgroundFetchAsync() {
    try {
return BackgroundFetch.registerTaskAsync(BACKGROUND_FETCH_TASK, {
// minimumInterval: 60 * 15, // 15 minutes
minimumInterval: 5,
stopOnTerminate: false, // android only,
startOnBoot: true, // android only
})
console.log("task registered");
} catch (error) {
console.log("task register failed");
}
}

// 3. (Optional) Unregister tasks by specifying the task name
// This will cancel any future background fetch calls that match the given name
// Note: This does NOT need to be in the global scope and CAN be used in your React components!
async function unregisterBackgroundFetchAsync() {
return BackgroundFetch.unregisterTaskAsync(BACKGROUND_FETCH_TASK);
}

React.useEffect(() => {
checkStatusAsync();
}, []);

const checkStatusAsync = async () => {
const status = await BackgroundFetch.getStatusAsync();
const isRegistered = await TaskManager.isTaskRegisteredAsync(BACKGROUND_FETCH_TASK);
setStatus(status);
setIsRegistered(isRegistered);
};

const toggleFetchTask = async () => {
if (isRegistered) {
    await unregisterBackgroundFetchAsync();
} else {
    await registerBackgroundFetchAsync();
}

checkStatusAsync();
};

    return (
    <View style={styles.screen}>
        <View style={styles.textContainer}>
        <Text>
            Background fetch status:{' '}
            <Text style={styles.boldText}>{status}</Text>
        </Text>
        <Text>
            Background fetch task name:{' '}
            <Text style={styles.boldText}>
            {isRegistered ? BACKGROUND_FETCH_TASK : 'Not registered yet!'}
            </Text>
        </Text>
        </View>
        <View style={styles.textContainer}></View>
        <Button
        title={isRegistered ? 'Unregister BackgroundFetch task' : 'Register BackgroundFetch task'}
        onPress={toggleFetchTask}
        />
    </View>
    );
}
```

How to solve this? Spend couple days with no success

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/background-fetch/?redirected

### Anything else?

I have used all expo-background-fetch npm versions.

**Comment by audrew** [comment]
BackgroundFetchResult.Failed : 3 - An attempt to download data was made but that attempt failed.

**Comment by Simek** [comment]
Hello @audrew, thank you for reporting the problem! 👍 

Latest release of `background-fetch` has a breaking change which removed the aliases for the enums:
* https://github.com/expo/expo/blob/master/packages/expo-background-fetch/CHANGELOG.md#1000--2021-09-28

It means that unfortunately the Snack example in doc is a bit outdated, which might cause your confusion. 

You need to replace `BackgroundFetch.Result` and `BackgroundFetch.Status` with respectively `BackgroundFetch.BackgroundFetchResult` and `BackgroundFetch.BackgroundFetchStatus` which should fix the `undefined` problem.

I will update the problematic example in docs soon, thank for catching that!

**Comment by audrew** [comment]
Thanks a lot! That's a shame that expo documentation gets old. I will try to introduce an updated version. Once again thanks a lot! If I can help you out with a donation, let me know.

**Comment by Simek** [comment]
Thank you for the kind words! It was my mistake in the first place, I have forgot to updated the example when I was refactoring the code, to support autogenerated API docs feature in this package. 😅 

Also the updated example should be visible in docs, I have merged the fix for this problem earlier today:
* #15332

Let me know if the hint about rename or updated docs have helped solve your issue.
