### ISSUE TITLE
expo:build include a lot of permissions by default

### ISSUE THREAD

**Issue by kiveemusic9** [expo/expo#15324]
**Command:** `expo build:android -t app-bundle`

21 Permissions  included by default

**app.json:** 
```
...
    "android": {
      "permissions": [],
...
```

am i missing something?

**Comment by harshjadon9** [comment]
### **Same issue!!**

**Comment by byCedric** [comment]
Please [see the docs](https://docs.expo.dev/versions/v43.0.0/config/app/#permissions):
> To use ONLY the following minimum necessary permissions and none of the extras supported by Expo in a default managed app, set permissions to []. The minimum necessary permissions do not require a Privacy Policy when uploading to Google Play Store and are:
• receive data from Internet
• view network connections
• full network access
• change your audio settings
• prevent device from sleeping 

If you need to further customize the permissions, you'd have to eject and build with EAS. You can read more [about force-removing permissions here](https://docs.expo.dev/guides/permissions/#bare-workflow-1). Only do this if you know what you are doing, as it might break functionality from Expo modules

Hope this helps!

**Comment by kiveemusic9** [comment]
> ...
>     "android": {
>       "permissions": [],
> ...

As i have already defined the permissions as shown in the expo documentation.
what am i missing?

**Comment by punksta** [comment]
I am having the same issue. I have `"permissions": []` but eas build adds the following permissions.

```
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.RECORD_AUDIO"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  ```

I like managed project, it's very convenient. But I don't want to confuse google play users with unnecessary permissions. My app doesn't need `modify audio settings` or `read/write external storage`

**Comment by gansbrest** [comment]
@punksta were you able to figure out how to remove these permissions? or did you revisit you approach somehow?
