### ISSUE TITLE
expo-barcode-scanner : Scan output cannot be null   

### ISSUE THREAD

**Issue by orchsik** [expo/expo#15327]
### Summary

The moment the user just just just opens the camera, the app crashes.
It's not an error that always appears, it's the same process, but it happens accidentally.
Our service runs the app and performs barcode recognition at least a few hundred times.
I am using expo-barcode-scanner in react-native project.
I use expo-unimodules. not react-unimodules. 

**error log** 
**expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground
BarCodeScannerAsyncTask.java, line 36**
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
  at android.os.AsyncTask$4.done(AsyncTask.java:415)  
  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)  
  at java.util.concurrent.FutureTask.setException(FutureTask.java:252)  
  at java.util.concurrent.FutureTask.run(FutureTask.java:271)  
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)  
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)  
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:923) Caused by: java.lang.IllegalArgumentException: Scan output cannot be null  
  at expo.modules.barcodescanner.scanners.ZxingBarCodeScanner.scan(ZxingBarCodeScanner.kt:56)  
  at expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:36)  
  at expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground(BarCodeScannerAsyncTask.java:6)  
  at android.os.AsyncTask$3.call(AsyncTask.java:394)  
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)  ... 4 more
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 25, 28, 29, 30, 31
        Build Tools: 23.0.1, 28.0.3, 29.0.1, 29.0.2, 30.0.2
        System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel 
x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs 
Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^43.0.2 => 43.0.2
      react: 16.13.1 => 16.13.1
      react-dom: ^16.13.1 => 16.13.1
      react-native: 0.63.2 => 0.63.2
    Expo Workflow: bare

### Reproducible demo

the barcode camera settings are as follows.

```javascript
<Camera
          useCamera2Api={false}
          type={Camera.Constants.Type.front}
          flashMode={Camera.Constants.FlashMode.off}
          ratio="16:9"
          barCodeScannerSettings={{
            barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
          }}
          onBarCodeScanned={scanned ? undefined : (event) => { setScanned(true) }}
/>
```

### Opinions
The code below is expo-barcode-scanner.
android>src>main>java>expo>modules>barcodescanner>scanners>ZxingBarCodeScanner.kt
The result of scan(source: LuminanceSource) may return null, which seems to be the cause of the problem.
source

```kotlin
override fun scan(data: ByteArray, width: Int, height: Int, rotation: Int): BarCodeScannerResult {
    // rotate for zxing if orientation is portrait
    var innerData = data
    var innerWidth = width
    var innerHeight = height
    if (rotation == 0) {
      val rotated = ByteArray(innerData.size)
      for (y in 0 until innerHeight) {
        for (x in 0 until innerWidth) {
          val sourceIx = x + y * innerWidth
          val destIx = x * innerHeight + innerHeight - y - 1
          if (sourceIx >= 0 && sourceIx < innerData.size && destIx >= 0 && destIx < innerData.size) {
            rotated[destIx] = innerData[sourceIx]
          }
        }
      }
      innerWidth += innerHeight
      innerHeight = innerWidth - innerHeight
      innerWidth -= innerHeight
      innerData = rotated
    }
    return requireNotNull(
      scan(generateSourceFromImageData(innerData, innerWidth, innerHeight))
    ) { "Scan output cannot be null" }
  }

  private fun scan(source: LuminanceSource): BarCodeScannerResult? {
    var barcode: Result? = null
    var bitmap: BinaryBitmap? = null
    try {
      bitmap = BinaryBitmap(HybridBinarizer(source))
      barcode = mMultiFormatReader.decodeWithState(bitmap)
    } catch (e: NotFoundException) {
      // No barcode found, result is already null.
    } catch (t: Throwable) {
      t.printStackTrace()
    }
    if (bitmap == null || barcode == null) {
      return null
    }
    val cornerPoints = ArrayList<Int>() // empty list
    val type = GMV_FROM_ZXING[barcode.barcodeFormat] ?: return null
    return BarCodeScannerResult(type, barcode.text, cornerPoints, bitmap.height, bitmap.width)
  }
```
android>src>main>java>expo>modules>barcodescanner>BarCodeScannerViewFinder.kt
It seems to work in this order
camera open -> onPreviewFrame -> scanForBarcodes -> barCodeScanner.scan
fun scanForBarcodes(camera: Camera?, mImageData: ByteArray)
Could it be that the image data does not come in?

**Comment by barbhackk** [comment]
Hi,

See the #15309 issue. It's not the best practice but it can unblock you.

Regards,

**Comment by rasck** [comment]
We experience the same. It blocks us from releasing to Google Play Store because the _Pre-Launch report testing_ is crashing our app. We are on managed flow.

The only work around is to leave managed flow and modify the java files?

**Comment by orchsik** [comment]
The problem seems to be that the QR scanner works as soon as the camera opens.
As soon as it is opened, the incoming source seems to be empty.
The camera opened and the QR scan was processed 2 seconds later.
I'll test it out and come back.

**Comment by rasck** [comment]
I think this is related to:
https://github.com/expo/expo/issues/15309#issuecomment-985633307

Hopefully fixed in: https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/CHANGELOG.md#1120--2021-12-03

**Comment by naor10** [comment]
> I think this is related to: [#15309 (comment)](https://github.com/expo/expo/issues/15309#issuecomment-985633307)
> 
> Hopefully fixed in: https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/CHANGELOG.md#1120--2021-12-03

It seems that the crash has been fixed, but no barcodes are detected.

**Comment by Fabzien** [comment]
> > I think this is related to: [#15309 (comment)](https://github.com/expo/expo/issues/15309#issuecomment-985633307)
> > Hopefully fixed in: https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/CHANGELOG.md#1120--2021-12-03
> 
> It seems that the crash has been fixed, but no barcodes are detected.

Same behavior for me

**Comment by orchsik** [comment]
11.2.0 — 2021-12-03
🐛 Bug fixes
Fixed crashes caused by the Zxing scanner on Android.
https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/CHANGELOG.md#1120--2021-12-03
