### ISSUE TITLE
EAS build vs expo build: code executing differences

### ISSUE THREAD

**Issue by claudiofus** [expo/expo#15323]
### Summary

Referring to [#799](https://github.com/expo/eas-cli/issues/799) I'm facing a similar issue. I'm using firebase storage v. 9.5.0  to download files to use in my app with code in Reproducible demo. Since I've distributed apps created and deployed with `eas-cli 0.37.0` with `EAS build --auto-submit`, I'm having a lot of `ReadObject FAILED_PRECONDITION` that didn't exists before as you can see from this image of GCP.
![image](https://user-images.githubusercontent.com/18471299/143764356-98178494-af6c-404d-a701-41a36b82f5b2.png)

After the upgrade to `eas-cli 0.38.1`, I built the same project with `eas build -p android --profile informatica-apk` and `npx cross-env APP_ENV=informatica expo build:android --no-wait -t apk`. The first didn't work because app stops immediately after launch and I'm currently searching the problem because Sentry is not catching the error, the second works fine.

Thank you for your job and I hope these info can help you.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.1

### Environment

```
Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ^43.0.1 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed
```

### Reproducible demo

```
import Constants from 'expo-constants';
import {initializeApp, getApps} from "firebase/app";
import {getStorage, ref, listAll, getDownloadURL} from "firebase/storage";

const firebaseConfig = {
    apiKey: 'xxxxxxxxxxxxxxxx',
    projectId: 'xxxxxx-xxxxx',
    storageBucket: 'xxxxxxx.com',
};
let storage;

if (getApps().length === 0) {
    initializeApp(firebaseConfig);
    storage = getStorage();
}

async function saveFile(fileName, fileContent) {
    console.log(`salvo il file: ${fileName}`);
    return await AsyncStorage.setItem(fileName, JSON.stringify(fileContent));
}

async function getFile(reference) {
    const fileName = reference.name;
    const url = await getDownloadURL(ref(storage, Constants.manifest.slug + '/' + fileName));
    return {fileName, url};
}

async function getReference() {
    const reference = ref(storage, Constants.manifest.slug);
    return listAll(reference);
}

async function prepareResources() {
    const references = await getReference();
    const finalArray = references.items.map(async (category) => {
        const {fileName, url} = await getFile(category);
        const fileContent = await fetch(url);
        const jsonFileContent = await fileContent.json();
        saveFile(fileName, jsonFileContent);
        return fileName;
    });

    await Promise.all(finalArray);
}

prepareResources();
```

**Comment by emmbyiringiro** [comment]
In case the app automatically crashed before launching without error traces via Sentry.  Probably it happens before Sentry service library  initialized.

Due to multitude of dependencies packages, It should be other issue not related to  Firebase (Storage).

In that situation you can run `adb logcat` while your app run in Android device with Developer mode enabled vis USB debugging.

https://developer.android.com/studio/command-line/logcat
