### ISSUE TITLE
[docs] [StoreReview] Difference between `hasAction` and `isAvailableAsync`

### ISSUE THREAD

**Issue by Kerumen** [expo/expo#15337]
### Summary

On the StoreReview docs page, there is 2 methods to check if the review is available. We have `hasAction()` and `isAvailableAsync()`. It seems that they both do more or less the same thing. Why should I use one over the other?

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/storereview

**Comment by barbhackk** [comment]
Hi,

Looking at the code the hasAction() method calls isAvailableAsync() and at the same time checks the information in the app.json (storeUrl ()) file. If the app config (app.json) does not contain store URLs and native store review capabilities are not available then the promise will fulfill to false (this in the [doc](https://docs.expo.dev/versions/latest/sdk/storereview/#storereviewhasaction) 😁)

isAvailableAsync() only check native store review capabilities.

[https://github.com/expo/expo/blob/master/packages/expo-store-review/src/StoreReview.ts](https://github.com/expo/expo/blob/master/packages/expo-store-review/src/StoreReview.ts)

**Comment by Kerumen** [comment]
@barbhackk Thanks for your detailed answer.
Do we need both method? I think only one is enough. Plus, the `hasAction` one lacks the prefix `Async` even though its a promise, as it appears to be a convention for Expo.

**Comment by barbhackk** [comment]
Hi,

It is true that we could keep only hasAction ()
The expo team will be able to decide on the question 🤣 but not me 🤣

**Comment by brentvatne** [comment]
it looks like this function was implemented specifically for web: https://github.com/expo/expo/pull/2781

see the implementation: https://github.com/expo/expo/blob/c8e8de37062e307f177321bdfa101da96b6211be/packages/expo-store-review/src/StoreReview.ts#L84-L86

i agree that lacking async suffix is confusing. this module could use some cleanup here.

**Comment by Kerumen** [comment]
I can open a PR to clean the module!
