### ISSUE TITLE
Expo client crashes instantly on open on iOS with Segment.initialize()

### ISSUE THREAD

**Issue by jhalborg** [expo/expo#1535]
### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^24.0.0 => 24.0.2
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/brandheroes-70e87670-9bff-4868-aafa-011f26bc05cf.tar.gz

iOS, Expo Client

### Steps to Reproduce

The Expo app is instant crashing when I initialize Segment. The device log says:

```
com.apple.CoreSimulator.SimDevice.6A0A1897-66B0-45E7-8FB7-AC4F562404F5[6053] (com.apple.WebKit.Networking.01C31F32-FA1E-455E-8F8E-D876B7B68DAB[6176]): Service exited with abnormal code: 1
```

Everything works fine on Android. Tried on different simulators, and on physical device as well. Using SDK 24.

### Expected Behavior

That Segment would initialize and allows calls to it afterwards, as it does on Android and should according to docs 😄 

### Actual Behavior
The Expo client app crashes instantly with no error message. The simulator log consistently writes
```
com.apple.CoreSimulator.SimDevice.6A0A1897-66B0-45E7-8FB7-AC4F562404F5[6053] (com.apple.WebKit.Networking.01C31F32-FA1E-455E-8F8E-D876B7B68DAB[6176]): Service exited with abnormal code: 1
```
when crashing. 

### Reproducible Demo
https://snack.expo.io/H19fhhLFz

I cannot share my write keys, so some are needed for testing.

__________

Note: Repost from [forums](https://forums.expo.io/t/expo-client-crashes-instantly-on-open-on-ios-with-segment-initialize/7838), as I think this is probably a bug in the Expo client or the Segment SDK integration on iOS

**Comment by terribleben** [comment]
What happens if you change `iOSWriteKey` to `iosWriteKey` in your example?

**Comment by jhalborg** [comment]
It works flawlessly, thanks! Going to add a PR to the docs with an explicit note to make sure that the params are matching case.

**Comment by terribleben** [comment]
Sorry you ran into trouble. Sometimes type errors can crash React Native because it doesn't validate JS types coming over the bridge into native code (because it would be performance-prohibitive).

**Comment by jhalborg** [comment]
No, I'm sorry for missing it :-) Thanks for helping!
