### ISSUE TITLE
Getting error when receiving push notifications 

### ISSUE THREAD

**Issue by jackmatrix** [expo/expo#1536]
When i send push notification with expo, the target device receive the notification without problem but a red screen appear and display the following error :

```
undefined is not an object (evaluating 'subscription.listener.apply')

```

yet, when i press `dismiss` the notification message is received.

i don't know what is causing this error.

I set notification handling according to expo docs :

```
componentDidMount(){
      this._notificationSubscription = Notifications.addListener(this._handleNotification);
    }


_handleNotification = (notification) => {
     // handle notification payload
 }; 

componentWillUnmount(){
      this._notificationSubscription && this._notificationSubscription.remove()

    }
```

Will this red screen be displayed when my app will go in production ?

Any suggestion to fix it ?

**Comment by sjchmiela** [comment]
What SDK version are you using? Are you sure you're not adding an undefined listener anywhere else (see https://github.com/facebook/react-native/issues/13403)?

The red screen will crash your application in production.

**Comment by jackmatrix** [comment]
fixed. The problem was caused because i put notification listener in several parts of my app.

Once i remove all extra notification handler to keep just only one ? the error disappear and everything is fine.

**Comment by sjchmiela** [comment]
Happy to hear it! 🙂 

### For future reference

From my recent testing it would seem that having multiple notification handlers is supported properly.

I guess you could had passed an `undefined` notification handler in one of the _several parts of your app_ (it's fairly easy, all you need is a typo in `addListener` 😕).
