### ISSUE TITLE
How to pass initial props from ExpoKit project to Android?

### ISSUE THREAD

**Issue by tgehrs** [expo/expo#154]
Is there any information on how to do this? It appears with regular RN you can use 
`reactRootView.startReactApplication(mReactInstanceManager, "UIExplorerApp", initialProperties)`

I am a bit confused on using RNObject to accomplish this in the same way. Putting the following in my onCreate does not seem to pass the arguments through:

`mReactRootView.call("startReactApplication", args);`

where args is a POJO:
```java
  public class Args extends Object{
    public RNObject reactInstanceManager;//seems that this should be an instance of ReactInstanceManager, unsure of how to access that...
    public String moduleName;
    public Bundle launchOptions = new Bundle();

  }
```

Is there a recommended way to accomplish this?

**Comment by tgehrs** [comment]
Was able to put together a solution, it is a bit hacky so I am interested to see if there are any downsides to doing it this way or suggestions for a better solution.

In MainActivity.java override the startReactInstance method to include variables in the manifest:
```java
  @Override
  protected void startReactInstance() {
    try {
      mManifest.put("token", "mytoken");
    } catch (JSONException e) {
      e.printStackTrace();
    }
    super.startReactInstance();
  }
```

Then inside of your root component you can define the propTypes:
```javascript
  static propTypes = {
    exp: React.PropTypes.object,
  }
```

If you are using CRNA, you will need to adjust your package.json so that "main" points to the root component ```"main": "./App.js"```, and you will need to register your root component with the AppRegistry `AppRegistry.registerComponent('main', () => App)`. The token variable can now be accessed!

```javascript
  constructor(props) {
    super(props)
    console.log(props.exp.manifest.token)
  }
```

**Comment by skevy** [comment]
@jesseruder would you be able to assist here?

**Comment by jesseruder** [comment]
@tgehrs we don't have a great api to do this but your solution of overriding `startReactInstance` should continue working for a while. I'll make a note to make this easier, thanks for bringing it up.

**Comment by tgehrs** [comment]
@jesseruder + @skevy thanks to you both for taking a look!

Would the following solution be worth me making a PR?

Add an overridable JSONObject nativeProps to ExponentActivity similar to the patterns you already have for [publishedUrl](https://github.com/expo/expo/blob/52387f484f6099f3a6e7fb473fb4871f724dcd98/android/expoview/src/main/java/host/exp/expoview/ExponentActivity.java#L40), developmentUrl, etc. 

Inside of either [startReactInstance](https://github.com/expo/expo/blob/52387f484f6099f3a6e7fb473fb4871f724dcd98/android/expoview/src/main/java/host/exp/expoview/ExponentActivity.java#L218) or [onManifestLoaded](https://github.com/expo/expo/blob/52387f484f6099f3a6e7fb473fb4871f724dcd98/android/expoview/src/main/java/host/exp/expoview/ExponentActivity.java#L140) insert k:v of "nativeProps":nativeProps()

Make a default in the [template](https://github.com/expo/expo/blob/449d5c84e46a2076480996dc2338b9f0f8153103/exponent-view-template/android/app/src/main/java/detach/app/template/pkg/name/MainActivity.java):
```java
  @Override
  public JSONObject nativeProps() {
    return new JSONObject();
  }
```

If this doesn't make sense I totally understand, but I am happy to contribute if I can. Great project btw!!

**Comment by jesseruder** [comment]
@tgehrs thanks for the offer! I'm changing some of this code right now so I'll just add this along with my changes. Should be able to get it out for SDK 17.

**Comment by tgehrs** [comment]
right on @jesseruder !

**Comment by jesseruder** [comment]
This is fixed in SDK 17 detach. MainActivity now has
```
  @Override
  public Bundle initialProps(Bundle expBundle) {
    // Add extra initialProps here
    return expBundle;
  }
```

**Comment by lmichailian** [comment]
The initial props on android are passed only on the onCreate lifecycle ?

**Comment by mschipperheyn** [comment]
How does this work on iOS? The initialProperties key doesn't seem to be accessible in AppDelegate.m
