### ISSUE TITLE
Unable to build as expo.modules does no exist error

### ISSUE THREAD

**Issue by jdiida** [expo/expo#15402]
### Summary

I worked through the instructions on how to use expo modules in an existing react native app ( was not created using expo cli).

https://docs.expo.dev/bare/installing-expo-modules/

Now, when I added the modules in MainApplication.java file

import expo.modules.ApplicationLifecycleDispatcher;
import expo.modules.ReactNativeHostWrapper;

I get an error: 

```
MainApplication.java:18: error: package expo.modules does not exist
import expo.modules.ApplicationLifecycleDispatcher;
                   ^

```
Do I need to install any dependencies prior, not sure how?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

4.13.0

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Expo Workflow: managed

### Reproducible demo

package com.appmobile;

import android.app.Application;
import android.content.Context;

import android.content.res.Configuration;
import androidx.annotation.NonNull;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;

import expo.modules.ApplicationLifecycleDispatcher;
import expo.modules.ReactNativeHostWrapper;

public class MainApplication extends Application implements ReactApplication {
// ....
}

**Comment by samih7** [comment]
@jdiida Did you end up solving this? Facing the same issue here

**Comment by jdiida** [comment]
I started a new project using NX. I faced the same issues as the expo modules were not showing when the project is loaded in Android Studio. I had to manually add the expo packages to the dependencies in Packages.json

And that seemed to be picked up correctly and worked for me

**Comment by samih7** [comment]
@jdiida We also have an NX project with both `expo` and `expo_modules_core` in the `node_modules`, along with `expo-video-thumbnails` and `expo-image-picker`. Still, no luck so far, stuck with that same error…
Did you have to do any special setup in the Android project?

**Comment by samih7** [comment]
@jdiida 

`package.json`:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/13098005/157726604-7806fc08-7958-45f0-86cc-7c90e948d8e7.png">

Android Studio packages:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/13098005/157726383-e47f2f23-89a6-4616-a669-c10f80a983fa.png">
<img width="342" alt="image" src="https://user-images.githubusercontent.com/13098005/157726512-14a6e66a-c734-464a-9d9d-1854f15733a2.png">

Android Studio error:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/13098005/157726279-16b74eca-97d0-486f-92f3-0a9a0401f623.png">

**Comment by jdiida** [comment]
Umm weird!

Can you ensure the packages are in packages.JSON in your react-native app project not in NX root workspace

**Comment by samih7** [comment]
@jdiida It worked! 🎉  

Although not used directly (hence not done automatically by NX), the `expo` package needed to be included in the app's `package.json` and not just at the root level. 

Many thanks

**Comment by jdiida** [comment]
Happy I helped 👍🏼

**Comment by iit2008047** [comment]
i am also facing the issue .. my node_modules are hoisted at root level

**Comment by waldjdida** [comment]
@iit2008047 I have created a sample project for you.

https://github.com/waldjdida/nx-sunday-expo

Hope it helps
