### ISSUE TITLE
Image Caching no longer works after updating standalone version

### ISSUE THREAD

**Issue by prodigynelson** [expo/expo#1540]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/prodigynelson-6565a600-d1aa-4181-b1d9-a525433ed6ba.tar.gz

This issue is referring to a standalone build

### Steps to Reproduce

I use redux saga / Expo.FileSystem.downloadAsync to download and cache images. My setup was working fine, until I built a new standalone and submitted that to TestFlight. Upon updating the TestFlight version of the app on my device, none of the images would display. My SmartImage class' render looks like this: 

    render() {
        const source = this.getSource()
        if (!this.props.localUri) {
                return (
                <View style={[this.props.style, { backgroundColor: Colors.grayColor, justifyContent: 'center' }]} >
                    <ActivityIndicator animating={true} size="small" />
                </View>
            )
        }
        return (
            <Image
                style={this.props.style}
                source={this.props.localUri}
                resizeMode={this.props.resizeMode}
            />
        );
    }

### Expected Behavior

The image cache to work, as it did before I updated the app.

### Actual Behavior

Instead of the image container displaying the activity indicator, it is just blank - meaning the localUri was downloaded by an action, and that link is used.  

### Reproducible Demo

I don't know how to provide a reproducible demo because I tried reinstalling the expo app and I don't have this problem. Is there something I am unfamiliar with (in terms of how local storage works)? Does the FileSystem.documentDirectory link change between versions of the app?

**Comment by prodigynelson** [comment]
More context: I use redux saga to dispatch cache actions, and the cache action would fail due to FileSystem.makeDirectoryAsync throwing [this error](http://prntscr.com/irq5w4) ONLY on the very first mounting of the app. 

If I run this code in my redux saga action, it throws the above error

    const folder = `${FileSystem.documentDirectory}metoo`;
    var folderInfo = yield FileSystem.getInfoAsync(folder);
    if (!folderInfo.exists) yield FileSystem.makeDirectoryAsync(folder);
If I run this code in my SmartImage component (this is before I dispatch the action) it works fine.

    const folder = `${FileSystem.documentDirectory}metoo`;
    var folderInfo = await FileSystem.getInfoAsync(folder);
    if (!folderInfo.exists) await FileSystem.makeDirectoryAsync(folder);
Note the only difference between the two are "yield" and "await"

This is a very specific edge case but maybe it'll uncover some bigger issue with FileSystem ¯\_(ツ)_/¯

**Comment by EvanBacon** [comment]
* can you reprod without redux-saga? 🤔
* make sure the root is setup by starting the caching from the `componentDidMount`
* lol also ditch that stone-age yield stuff 😂💙

**Comment by nikki93** [comment]
Yes, a directory needs to exist to download to it.

**Comment by prodigynelson** [comment]
@nikki93 gotcha.
The answer that comes to mind is this - I have several smart image components being rendered on the same page. If the directory hasn't been created, it is likely that the first one called begins creating the directory, and it hasn't been created before the other components are rendered, and so they also try to create the directory. I will move the create directory to the componentWillMount of my app.js file and hopefully that will fix this whole thing

**Comment by nikki93** [comment]
Ah oops ya — the flag equivalent to `-p` of `mkdir‘ does this. Just pass `intermediates: true` as an option.

**Comment by prodigynelson** [comment]
Closing because I believe this is an edge case - rebuilt my image caching system and have not had an issue with downloadAsync
