### ISSUE TITLE
unable to install expo modules and expo java module does not get loaded

### ISSUE THREAD

**Issue by jdiida** [expo/expo#15408]
### Summary

unable to complete the steps as shown in here: https://docs.expo.dev/bare/installing-expo-modules/

I have added the line below to settings.gradle

```
apply from: new File(["node", "--print", "require.resolve('../expo/package.json')"].execute(null, rootDir).text.trim(), "../node_modules/expo/scripts/autolinking.gradle")
useExpoModules()
```

and when I refresh the list in Android Studio 

![image](https://user-images.githubusercontent.com/48318632/144515530-a1fa709a-ae9d-437d-8e40-b725863a8e0f.png)

you can see that expo java module is missing therefore  cannot add expo.modules.ReactActivityDelegateWrapper

![image](https://user-images.githubusercontent.com/48318632/144515907-c1a69494-6eb5-4cd6-8b8c-1c4971cfa9cb.png)

![image](https://user-images.githubusercontent.com/48318632/144515744-9c93c220-22b7-436a-8cf9-a935890d0ffd.png)

I spent hours but no joy and I don't know whether is my env or I am missing something out

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

4.13.0

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Expo Workflow: managed

### Reproducible demo

settings.gradle file:

```
rootProject.name = 'appMobile'

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesSettingsGradle(settings)

include ':app'

apply from: new File(["node", "--print", "require.resolve('../expo/package.json')"].execute(null, rootDir).text.trim(), "../node_modules/expo/scripts/autolinking.gradle")
useExpoModules()
```

packages.json
dependencies

- "expo": "^43.0.3",
- "expo-auth-session": "^3.4.2",
- "expo-random": "^12.0.1",

MainActivity.java

package com.appmobile;

```
import com.facebook.react.ReactActivity;
import expo.;
import com.facebook.react.ReactActivityDelegate;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "main";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegateWrapper(this,
      new ReactActivityDelegate(this, getMainComponentName())
    );
  }
}
```

**Comment by jdiida** [comment]
since I am using nx monorepo for some reason when installing expo, the process does not add expo to packages.json file,
so I had to add it manually and that seemed to fix the issue

**Comment by priyamishra-tech** [comment]
Did you get any solution @jdiida, in my case expo already exists in package.json. But everytime I get the same error - "expo modules not found". please help

**Comment by jdiida** [comment]
See https://github.com/expo/expo/issues/15402

**Comment by herbieduah** [comment]
Check any folder names leading to your project have a space
