### ISSUE TITLE
Calendar API Event Retrieval sending back Objective C error

### ISSUE THREAD

**Issue by yogert96** [expo/expo#1541]
### Environment

iOS, Android

### Steps to Reproduce

Using this code in an expo project

```    
async getCalendar() {
      await Expo.Permissions.askAsync('calendar');
      const cal = await Expo.Calendar.getCalendarsAsync(Expo.Calendar.EntityTypes.EVENT);
      console.log(cal[1]);
      const yesterday = new Date();
      yesterday.setDate(yesterday.getDate() - 1);
      const nextYear = new Date();
      nextYear.setFullYear(nextYear.getFullYear() + 1);
      const events = await Expo.Calendar.getEventsAsync(cal[1].id, yesterday, nextYear);

      events.forEach(function(element) {
        console.log(element);
      });
      // this.setState({calendar:Expo.Calendar.getEventsAsync(cal.id, new Date(), new Date()).toString()});
}; 
```

1. Insert Date Objects into getEventsAsync()
2. Receive a native error related to the Date params

### Expected Behavior

Retrieve all of the events from the calendar ID

### Actual Behavior

I get this error (Objective C I think):
<img width="350" alt="screen shot 2018-03-16 at 1 34 11 am" src="https://user-images.githubusercontent.com/4098066/37507748-2761d2e2-28be-11e8-8977-6aacf1dd0d61.png">

(Write what happened. Add screenshots!)

### Reproducible Demo
https://snack.expo.io/SyS8oJKtz

**Comment by terribleben** [comment]
Looks like the `id` parameter is supposed to be an array, not a string. Here's a working example:

https://github.com/expo/native-component-list/blob/master/screens/EventsScreen.js#L56

And the docs:

https://docs.expo.io/versions/latest/sdk/calendar.html#calendarids-array--array-of-ids-of-calendars-to-search-for-events-in-required
