### ISSUE TITLE
Error:Execution failed for task ‘:app:exponentPrebuildStep’ 

### ISSUE THREAD

**Issue by lukmiller** [expo/expo#1543]
getting this error on linux
Error:Execution failed for task ‘:app:exponentPrebuildStep’.

    Process ‘command ‘./detach-scripts/prepare-detached-build.sh’’ finished with non-zero exit value 127

any solution?

env config:
Linux mint 18.x,
react-native 0.52.0,
expo: 25
node: 9.8.0
npm: 5.6.0

**Comment by jesseruder** [comment]
Hi @lukmiller, can you run that command separately and see if it gives you an error message?

**Comment by lukmiller** [comment]
@jesseruder, Thank you ... I have managed to solve the problem.

**Comment by Freshchris01** [comment]
@lukmiller How did you solve it?

**Comment by pcowgill** [comment]
For me, the `one-time instructions` at the bottom of this helped https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4

**Comment by sonaye** [comment]
I was getting a similar error on a fresh `eject` with SDK `29.0.0`, I migrated recently to `expo-cli`, installing `exp` as a dev dependency as well fixed this for me.

**Comment by anishone** [comment]
I had the same issue for remote builds(on cloud). Adding exp package to the environment helped! Thanks for the tip @sonaye

**Comment by sjchmiela** [comment]
Thank you all for providing solutions that helped you with the problem! 🙂 I'll let myself consider this issue resolved.
