### ISSUE TITLE
EAS Build : InfoPlist.strings error: Build input file cannot be found

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#15441]
### Summary

When building with EAS, the ios build fails with this error : 

```
› Copying   ios/Shares/Supporting/Expo.plist ➜ ./Expo.plist

› Compiling Shares » SplashScreen.storyboard

› Copying   ios/Shares/Supporting/fr.lproj/InfoPlist.strings ➜ fr.lproj/InfoPlist.strings


❌  error: Build input file cannot be found: '/Users/laurent/Work/shares/fameapp/ios/Shares/Supporting/fr.lproj/InfoPlist.strings' (in target 'Shares' from project 'Shares')

▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	CopyStringsFile /Users/expo/Library/Developer/Xcode/DerivedData/Shares-glmscuytdlrzalexasprhocggmax/Build/Intermediates.noindex/ArchiveIntermediates/Shares/InstallationBuildProductsLocation/Applications/app.app/fr.lproj/InfoPlist.strings /Users/laurent/Work/shares/fameapp/ios/Shares/Supporting/fr.lproj/InfoPlist.strings (in target 'Shares' from project 'Shares')

▸ (1 failure)

** ARCHIVE FAILED **

The following build commands failed:

	CopyStringsFile /Users/expo/Library/Developer/Xcode/DerivedData/Shares-glmscuytdlrzalexasprhocggmax/Build/Intermediates.noindex/ArchiveIntermediates/Shares/InstallationBuildProductsLocation/Applications/app.app/fr.lproj/InfoPlist.strings /Users/laurent/Work/shares/fameapp/ios/Shares/Supporting/fr.lproj/InfoPlist.strings (in target 'Shares' from project 'Shares')

(1 failure)

Exit status: 65

+-------------+-------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.185.1                 |

| sdk         | iPhoneOS15.0.sdk        |

+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project

It's hard to tell what's causing the error, so we wrote some guides on how

to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/

Before submitting an issue on GitHub, please follow the guide above and make

sure your project is set up correctly.

fastlane uses `xcodebuild` commands to generate your binary, you can see the

the full commands printed out in yellow in the above log.

Make sure to inspect the output above, as usually you'll find more error information there

[stderr] [!] Error building the application - see the log above

Error: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

```
Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 29, 30, 31
        Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.3 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.3.0
    Expo Workflow: bare
```

### Reproducible demo

No

**Comment by lc3t35** [comment]
I built then manually with XCode without problem.
fyi Android build went fine also with EAS.

**Comment by lc3t35** [comment]
@brentvatne can you just check that localizing (in my case French) the app messages such as NSCameraUsageDescription with Supporting/fr.lproj/InfoPlist.strings is well managed by eas process ?

**Comment by lc3t35** [comment]
@brentvatne can you please check that ArchiveIntermediates includes Supporting localized InfoPList.strings, the file Supporting/fr.lproj/InfoPlist.strings is in my code (and XCode find it as I was able to build and submit to store "manually"). I think there is a problem with the copy you make.

**Comment by sbichenko** [comment]
I have the same problem and also have localized strings.

**Comment by sbichenko** [comment]
Here's what helped: deleting the local 'ios' folder and duplicating the keys from English locale into `expo.ios.infoPlist` section.

**Comment by robsonbbs** [comment]
Removing `locales` from my `app.json` and moving my descriptions to `ios.infoPlist` did the trick, but now I don't have translations for those descriptions.

@brentvatne Seems like there is an issue to copy InfoPlist.strings generated using `locales`.

I think you can reproduce this following these 3 steps:

1 - Create a project that uses `locales` on app.json pointing to some iOS permission descriptions. Example:

**app.json:**
```
{
  "expo": {
    ...
    "locales": {
      "en": "./src/utils/locale/infoPlist/en.json",
      "pt": "./src/utils/locale/infoPlist/pt.json"
    }
    ...
  }
}
```

**./src/utils/locale/infoPlist/en.json:**
```
{
    "NSCameraUsageDescription": "We need to access your camera to allow you to scan QR codes and attach photos to checklists",
    "NSLocationWhenInUseUsageDescription": "We need to access your location to be able to collect tasks check-in and check-out locations"
}
```

**./src/utils/locale/infoPlist/pt.json:**
```
{
    "NSCameraUsageDescription": "Precisamos de acesso a câmera para que você possa escanear qrcodes e inserir fotos nos questionários",
    "NSLocationWhenInUseUsageDescription": "Precisamos da sua localização para coletar o local de checkin e checkout das suas atividades"
}
```

2 - Generate `ios/` folder using `expo prebuild`
3 - Try to build it using eas build

**Comment by mackenziekira** [comment]
I ran into this issue too and was able to resolve it by manually editing the strings file path in `project.pbxproj` from `<absolute-local-path-to-app>/ios/Rivet/Supporting/en.lproj/InfoPlist.strings` to `en.lproj/InfoPlist.strings`. 

Can't rerun `expo prebuild` after doing this, or the changes will get overwritten, but that's true of many other changes to bare projects also.

**Comment by DatMoser** [comment]
Been facing the same problem since ejecting from the managed workflow. Super annoying. Managed to solve it by adding the Info.plist manually to ios/Info.plist and referencing it via Xcode. Then I created localized Strings files and added the translations for the respective keys to them. It now runs locally and builds via eas, but every time I start the server I get asked to clean the ios directory because it is now apparently malformed. 
Already tried to add the keys to the infoPlist section for cleanup and rebuild, but it doesn't work. 

Actually kind of disappointed.

**Comment by EvanBacon** [comment]
@giautm is going to investigate this further. Sorry for the inconvenience.

**Comment by davinun99** [comment]
I have the same problem, what's the correct way to generate an app with eas and traductions? What are the steps?

**Comment by ArtKullashi** [comment]
Problem still there. Should we create a new issue?
