### ISSUE TITLE
BarCodeScanner Component not supported on the web while the doc says web compatible

### ISSUE THREAD

**Issue by Azuxul** [expo/expo#15442]
### Summary

When trying to use BarCodeScanner Component on web platform it show the following message : 
"BarCodeScanner Component not supported on the web"

But the Expo SDK documentation for v43 says it is compatible for web (https://docs.expo.dev/versions/v43.0.0/sdk/bar-code-scanner/)

Even when trying to use the example of the Expo SDK documentation I get the same message (https://snack.expo.dev/@geunievre/basic-barcodescanner-usage). For v42 it is not shown as compatible. It may be a documentation issue.

![screenshot](https://user-images.githubusercontent.com/11092555/144759335-9b34edf5-510c-46bc-948f-24601ae2da00.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

expo 43.0.2, expo barcodescanner 11.1.2

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@geunievre/basic-barcodescanner-usage

**Comment by byCedric** [comment]
Hi @Azuxul! The specialized barcode component isn't available on web, but all other logic for the barcode is available. You can use `expo-camera` to render the view on web (and native), and use the barcode events from the `Camera` to make it work on web. [I made a Snack from your demo that includes this](https://snack.expo.dev/@bycedric/expo-issue-15442)

Hope this helps!

**Comment by sunnylqm** [comment]
Thank you @byCedric for the workaround but I think this issue should be reopened so we can subscribe to see if there is a final fix to close it in the future. That's how issues being tracked right?

**Comment by austinchen12** [comment]
@byCedric not sure if your example is outdated but if you add any other code type (except qr), it doesn't work. It's reproducible with your snack app and locally when I play around with it

**Comment by IdoLevi235** [comment]
> @byCedric not sure if your example is outdated but if you add any other code type (except qr), it doesn't work. It's reproducible with your snack app and locally when I play around with it

Thanks @byCedric for this distinction - that only the qr code is supported. Is there a way I can scan a bar code type of upc_ean on web ?  That is the one we need in our case.

Regards
