### ISSUE TITLE
[expo-branch] SDK 43 Android - missing "fallbackToCacheTimeout": 30000 in app.json causing expo-branch to crash.

### ISSUE THREAD

**Issue by Aryk** [expo/expo#15443]
### Summary

After upgrading to SDK 43 Managed, when I create my branch universal object, my application is crashing when I call `generateShortUrl` on Android devices. **On iOS it works**

This has something to do with the manifest/installation layer of the app. 

I made an MCVE where generateShortUrl worked, so it was likely something in my app.json.

I ported as much of my applications app.json to the MCVE as I could in hopes of reproducing the crash and I was successfully able to reproduce the crash.

*After spending 23 hours* debugging, recompiling, tweaking something, and then rebuilding, redownloading, uninstalling reinstalling, etc (I probably did this about 30 times throughout the course of this), I was able to narrow it down to one thing.

So this error:

```
12-05 12:05:29.615 26616 26691 W System.err: Caused by: com.facebook.react.common.JavascriptException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
12-05 12:05:29.615 26616 26691 W System.err: 	at host.exp.exponent.ReactNativeStaticHelpers.handleReactNativeError(ReactNativeStaticHelpers.kt:8)

```

which was causing expo-branch to crash on generateShortUrl was caused by **not** having fallbackToCacheTimeout in my app.json.

```json
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD"
    },
```

goes to 

```json
    "updates": {
      "fallbackToCacheTimeout": 30000,
      "enabled": true,
      "checkAutomatically": "ON_LOAD"
    },
```

I believe this is an optional field but seems to be required if you want to get expo-branch working. How that makes any sense, I'll leave that to the expo team to figure out, but it is what it is. 

I hope you guys can figure out what's happening behind the scenes bc this was very time consuming and tedious to debug.

## Expo MCVE

https://github.com/Aryk/expo-repro/tree/branch-android-bug

**Make sure to add your own branch API key**

**Comment by brentvatne** [comment]
where's the mcve?

**Comment by Aryk** [comment]
@brentvatne - added to description above.

 I went and stripped away even more of the packages to really get it minimal for you.

Thanks for looking into this 🙏 

I'm going to be upgrading to SDK 44 this week as well, looking forward to getting newer updated libraries!

**Comment by brentvatne** [comment]
just as a heads up - we may not actually get around to investigating and fixing this. we are in maintenance mode with `expo build` and encourage everyone to move to eas build, and we are in the process of deprecating expo-branch and providing appropriate tooling so that developers can use react-native-branch directly instead.

**Comment by Aryk** [comment]
Thanks @brentvatne ... it's probably not required that you fix this since adding that line solves the issue.

However, I urge you to add it to the expo-branch documentation so that anyone who isn't on EAS will know about this outstanding issue and not run into the same problem as me.

**Comment by Aryk** [comment]
Also, was reading through your change log @brentvatne : 

"Deprecates setCurrentScreen and removes the native API calls to support the latest Firebase SDKs. (#4366 by @IjzerenHein)"

I'm not sure if 4366 is the right ticket there...it has to do with Expo Camera

**Comment by zaidyft** [comment]
Logged in just to say thanks to original post. Appreciate you sharing the solution here.

**Comment by Aryk** [comment]
@zaidyft you're welcome! I'm glad it helped someone it was really a nasty bug. 

Well, I got down to a point where I was adding, recompiling and then removing it and recompiling and noticed one worked and one didn't. 

I got to it through process of elimination...removing bits and pieces from my app.json until it worked.
