### ISSUE TITLE
EAS build: Suppressing Long timer warning in Production (android)

### ISSUE THREAD

**Issue by ankitmaloo** [expo/expo#15446]
### Summary

Firebase SDK has a warning that comes up when running on Android. The usual fix is updating the timer in node modules for development. 

How do I update this when I am building (and deploying) this in production through EAS build? 

Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 363133ms)
at node_modules/@firebase/webchannel-wrapper/dist/index.js:25:1215 in <anonymous>
at node_modules/@firebase/webchannel-wrapper/dist/index.js:29:855 in E
at node_modules/@firebase/webchannel-wrapper/dist/index.js:29:740 in E
at node_modules/@firebase/webchannel-wrapper/dist/index.js:28:225 in Qa$argument_1
at node_modules/@firebase/webchannel-wrapper/dist/index.js:26:1234 in <anonymous>
at node_modules/@firebase/webchannel-wrapper/dist/index.js:15:355 in d
at node_modules/@firebase/webchannel-wrapper/dist/index.js:13:416 in b.prototype.get
at node_modules/@firebase/webchannel-wrapper/dist/index.js:43:1339 in <anonymous>
at node_modules/@firebase/webchannel-wrapper/dist/index.js:43:1312 in qc
at node_modules/@firebase/webchannel-wrapper/dist/index.js:43:1269 in <anonymous>
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:592:4 in setReadyState
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:357:4 in __didReceiveIncrementalData
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.1.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.17.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

Use firebase, and fire up the app on android. It would keep showing the warning whenever you do something which fetches data from firebase.

**Comment by brentvatne** [comment]
warnings don't show up in release builds. if you want to make a change to node_modules use patch-package: https://www.npmjs.com/package/patch-package
