### ISSUE TITLE
JSX Video memory leak

### ISSUE THREAD

**Issue by James2516** [expo/expo#1544]
If a video component is declared with this format: `<Video source={{uri: 'http://techslides.com/demos/sample-videos/small.mp4' }} />`, do we still need to maintain a `ref` to it and call `unloadAsync` when the component unmounts?

Is there anything else we have to take note of when dealing with AV resources to prevent memory leak?

Also, does `videoRef.loadAsync` have performance benefits over the above JSX declaration if we don't need the video interface (i.e. width/height 0)?

**Comment by sjchmiela** [comment]
Hi, @James2516!

> If a video component is declared with this format: <Video source={{uri: 'http://techslides.com/demos/sample-videos/small.mp4' }} />, do we still need to maintain a ref to it and call unloadAsync when the component unmounts?

No, `unloadAsync` has the same effect as unmounting the Video component.


> Is there anything else we have to take note of when dealing with AV resources to prevent memory leak?

No, everything should be done automatically for you.


> Also, does videoRef.loadAsync have performance benefits over the above JSX declaration if we don't need the video interface (i.e. width/height 0)?

If you don't need video-video, but just would like to play the audio of a video, you could use the Sound API. That may have smaller memory and performance overhead compared to using `<Video />`.

**Comment by James2516** [comment]
> If you don't need video-video, but just would like to play the audio of a video, you could use the Sound API. That may have smaller memory and performance overhead compared to using <Video />.

The video is already cached locally, for some screens only the audio part is needed so I'd reuse the already cached video. In this case, should I use JSX (so that its consistent with other components that do use the video-video), or would using `videoRef.loadAsync` over JSX reduce memory/performance overhead? (does `<Video />` still get mounted as a view even when the width/height is 0?)

**Comment by sjchmiela** [comment]
That sounds like a good idea!

In your situation I would use `Sound.create()`, because as you suspect, `<Video />` is mounted as a view no matter what its dimensions are (and to be able to use `videoRef.loadAsync` you would need to declare `<Video />` as a view).

**Comment by James2516** [comment]
Oh I misread your last paragraph, was not aware that `Sound.create()` can be called on an video resource, thanks!
