### ISSUE TITLE
[Android] no matching outputFormat for VORBIS recording encoding

### ISSUE THREAD

**Issue by James2516** [expo/expo#1546]
https://docs.expo.io/versions/latest/sdk/audio.html#outputformat-

```
outputFormat :
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_DEFAULT
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_THREE_GPP
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_MPEG_4
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_AMR_NB
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_AMR_WB
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_AAC_ADIF
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_AAC_ADTS
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_RTP_AVP
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_MPEG2TS
Expo.Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_WEBM

audioEncoder :
Expo.Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_DEFAULT
Expo.Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AMR_NB
Expo.Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AMR_WB
Expo.Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AAC
Expo.Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_HE_AAC
Expo.Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AAC_ELD
Expo.Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_VORBIS
```

There is `RECORDING_OPTION_ANDROID_AUDIO_ENCODER_VORBIS` but none of the `outputFormat` works with it.

**Comment by sjchmiela** [comment]
Nice catch, in fact Android does not support encoding Vorbis (https://developer.android.com/guide/topics/media/media-formats.html#audio-formats) even though `AudioEncoder` defines `AudioEncoder.VORBIS` (https://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder.html#VORBIS).

Will remove from the docs.

**Comment by terribleben** [comment]
Merged the docs change, will go out with next SDK

**Comment by pedrovarela86** [comment]
Code still have VORBIS as Encoder..

**Comment by sjchmiela** [comment]
Hm, there's no VORBIS in 

https://github.com/expo/expo/blob/354fd052759c223c56811ddd61fface87ad1fbec/packages/expo/src/av/Audio/Recording.ts#L48-L57

Maybe your editor autocompletes some old definitions?
