### ISSUE TITLE
Expo Push Notification 504 Gateway Timeout

### ISSUE THREAD

**Issue by okeybond** [expo/expo#15460]
### Summary

Not the first issue raised on this (expo-server-sdk)  but closed advising on retries and using the SDK, which I am using. I feel the underlying issues should be fixed or the status board reflect the current state of the system. I currently do 20 retries if the push was not successful with a wait time in between request of 2 sec. The issue persist.
Please advise on the best way to around this.
![Screenshot_20211207-131739](https://user-images.githubusercontent.com/48156152/145038513-3b65dc04-5cbf-4af0-b30c-e95531cee199.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

N/A

### Reproducible demo

Using the expo Server SDK (expo-server-sdk) @ 5pm GMT

**Comment by giekus** [comment]
Hey, I've contacted the support a few weeks ago on the exact same issue, this is the response:
`Hi! Timeouts can happen when our push server is under significant load. We advise adding in retry logic and exponential backoff.`

I don't know what others think, but this is total bullshit to me. No service should ever throw a timeout to the user, even if it's under a significant load. Push some of the notifications to the queue or something like that when the load is significant..

I can't really give you an advise on this issue, we are doing retries and those errors are just thrown randomly.

**Comment by brentvatne** [comment]
the expo push service is a free service that comes with some limitations, such as needing to retry in case of timeouts. if you'd like to bypass the service and send notifications directly via apns and fcm, see the ["Sending Notifications with APNs & FCM" guide](https://docs.expo.dev/push-notifications/sending-notifications-custom/). we plan to address these issues but we have our engineering resources focused on other products at this time. it's on our roadmap to improve the notification service in terms of reliability and features, and to integrate it into our paid service offerings, including providing an SLA.

**Comment by ide** [comment]
> No service should ever throw a timeout to the user, even if it's under a significant load. Push some of the notifications to the queue or something like that when the load is significant.

The Expo push notification service uses a queuing model. When there is a high volume of requests, the servers that enqueue push notifications can be under very high load and respond with an HTTP error -- in this case, a 504 error status.

Separate from 504 statuses and the frequency of errors, API requests over the internet to any service can and do fail for several reasons and retries are always required -- Expo or otherwise.

**Comment by sealabcore** [comment]
Does payload size affect the probability of receiving a gateway timeout? I noticed that when we started sending bulk push notifications that we get significantly more gateway timeouts as opposed to sending one-off requests to the expo push service. We are following the recommended concurrency of requests and not seeing any "too many request" errors.

Thoughts?
