### ISSUE TITLE
Push notifications wont work for standalone apps, android

### ISSUE THREAD

**Issue by azaabudeen** [expo/expo#1547]
For some reason I won't get push notifications on android and on expo...
only my app receives the notifications ( Expo App ), stand alone wont work for anyone...
more details:

https://stackoverflow.com/questions/49347524/react-native-cant-receive-expo-push-notification-on-stand-alone-app

**Comment by AlexanderPPetrov** [comment]
+1 After build  I am not able to receive notification if my app is closed. Works only in foreground

**Comment by jesseruder** [comment]
Hi @azaabudeen, please follow the issue template. It's hard to understand what's going on.
