### ISSUE TITLE
Encountered an exception while calling native method: Exception occurred while executing exported method composeAsync on module ExpoMailComposer

### ISSUE THREAD

**Issue by whitesnow9291** [expo/expo#15473]
### Summary

This is source code
```
const isavailable = await MailComposer.isAvailableAsync()
    if (isavailable) {
      const options = {
        subject: 'Hello world',
        recipients: ['EMAIL'] // I set actual email here
      }
      try {

        const result = await MailComposer.composeAsync(options)
      } catch (error) {
        console.info(error)
      }
    } else {
      alert('Not supported')
    }
```
It shows this error in console 

Encountered an exception while calling native method: Exception occurred while executing exported method composeAsync on module ExpoMailComposer: length=0; index=-1
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-mail-composer/build/MailComposer.js:25:0 in <global>
at node_modules/expo-mail-composer/build/MailComposer.js:25:0 in <global>

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

~43.0.2

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.3 - ~/.nvm/versions/node/v14.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-24 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

const isavailable = await MailComposer.isAvailableAsync()
    if (isavailable) {
      const options = {
        subject: 'Hello world',
        recipients: ['EMAIL'] // I set actual email here
      }
      try {

        const result = await MailComposer.composeAsync(options)
      } catch (error) {
        console.info(error)
      }
    } else {
      alert('Not supported')
    }

**Comment by MariemDbch** [comment]
there is a solution ? please
