### ISSUE TITLE
For web, Audio.loadAsync doesn't use passed headers

### ISSUE THREAD

**Issue by andrewmwhite** [expo/expo#15471]
### Summary

On web, the `playbackObject.loadAsync` method in the Audio Playback API (https://docs.expo.dev/versions/latest/sdk/av/#playback-api) appears to throw out the `headers` passed as part of the first parameter (`source` object) and not send them with the request to the server to load the audio.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.0 - ~\AppData\Local\Volta\tools\image\node\16.13.0\node.EXE
      Yarn: 1.22.17 - ~\AppData\Local\Volta\tools\image\yarn\1.22.17\bin\yarn.CMD
      npm: 8.1.3 - ~\AppData\Local\Volta\tools\image\npm\8.1.3\bin\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~43.0.0 => 43.0.1
      react: ~17.0.1 => 17.0.2
      react-dom: ~17.0.1 => 17.0.2
      react-native: ~0.64.3 => 0.64.3
      react-native-web: ~0.17.1 => 0.17.5
    Expo Workflow: managed
```

### Reproducible demo

See: https://snack.expo.dev/@andrewmwhite/playing-sounds

You can see the 401 in console and that there's no "authorization" header set in the request in your dev tools. If you check with curl/httpie/whatever you can verify that that the URL expects an authorization header value of "mellon", with which you'll get an actual MP3 file

Other notes:

- There appear to be some tests of this functionality https://github.com/expo/expo/blob/89bdf43cf2d83817ec5a8a4f0472d8f69684cb41/apps/test-suite/tests/Audio.js#L184 but my attempt to enable those tests with this diff against master resulted in all the Audio tests failing. 
    ```
    diff --git a/apps/bare-expo/e2e/TestSuite-test.web.js b/apps/bare-expo/e2e/TestSuite-test.web.js
    index 622b227df6..76e6a60cb4 100644
    --- a/apps/bare-expo/e2e/TestSuite-test.web.js
    +++ b/apps/bare-expo/e2e/TestSuite-test.web.js
    @@ -6,6 +6,7 @@ import { expectResults } from './utils/report';
     
     const TESTS = [
       'Basic',
    +  'Audio',
       'Asset',
       'AuthSession',
       'Constants',
    ```
    I'm not sure that I have the Audio tests integrated correctly; they don't appear to run when using the basic testing procedure in the contributing docs.
- I _think_ the actual issue is here: https://github.com/expo/expo/blob/d7cecc36d55f0f88581e615699ca071d5f4853f3/packages/expo-av/src/ExponentAV.web.ts#L188
    `nativeSource` at that point should be an object including the `uri` and `headers` but the latter are ignored with that initialization of `source`. 

I can probably dig more later this week. If anyone has any insights on how to run the correct tests and what to expect from them, that would be appreciated.

**Comment by visitsb** [comment]
`ExponentAV.web.ts` renders HTML audio tag on web in `expo-av`. 

But, the limitation is browser's [HTML Audio tag](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio) support for `url:string`, hence there is [no way](https://stackoverflow.com/a/9992962) to pass in headers on web.

The option that **works** for web to [fetch using headers first, then convert to an in-memory blob](https://gist.github.com/praveenpuglia/61a296064815f19f391f2c84f12f134b), and use `URL.createObjectURL(blob)` to get `url` to pass into `expo-av loadAsync(uri), createAsync(uri)` methods.
