### ISSUE TITLE
[expo-camera][eas] Could not find com.google.android:cameraview

### ISSUE THREAD

**Issue by giautm** [expo/expo#15483]
### Summary

I build the managed apps with eas build then got the error.

<img width="1138" alt="Screen Shot 2021-12-09 at 05 31 33" src="https://user-images.githubusercontent.com/12751435/145302087-2c3a53e7-9d08-4e26-ad68-c832b5cb9490.png">

I think it's related to configure for Android. But, why the plugin didn't configure it?

https://github.com/expo/expo/blob/master/packages/expo-camera/README.md#configure-for-android

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.0

### Environment

EAS Build

### Reproducible demo

None.

**Comment by brentvatne** [comment]
you can use patch-package to pull in this commit: https://github.com/expo/expo/commit/1cffe4872ab59deb615396666185c0bc2769d21f#diff-22e3d4fd4a3340493b8527930ac08708771d94cdc5e8a26947cbbf894f4e3838

we'll release this in the next version of expo-camera

**Comment by giautm** [comment]
Yes, it's a monorepo. I will trying to use patch-packge. Thank you, <3

**Comment by giautm** [comment]
The build was successful. So, I close this issue. <3
