### ISSUE TITLE
EAS Build: Android applinks (intent filters or deeplink config) do not work with autoFilter:true in EAS build

### ISSUE THREAD

**Issue by ankitmaloo** [expo/expo#15486]
### Summary

Hi 
I have been using EAS build to distribute and run on production. 

I use android intentfilters to directly open the app (when the auto verify is true). 

Config in reproducible demo

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42.0

### Environment

Expo CLI 4.13.0 environment info:
System:
OS: macOS 11.6
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 16.1.0 - /usr/local/bin/node
Yarn: 1.22.11 - /usr/local/bin/yarn
npm: 7.17.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.10.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
IDEs:
Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
npmPackages:
expo: ^42.0.0 => 42.0.5
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: ~0.63.4 => 0.63.4
react-native-web: ~0.13.12 => 0.13.18
npmGlobalPackages:
expo-cli: 4.13.0
Expo Workflow: managed

### Reproducible demo

```
"intentFilters": [
        {
          "autoVerify": true,
          "action": "VIEW",
          "data":
          {
              "scheme": "https",
              "host": "mydomain.com",
              "pathPrefix": "/applogin"
            },
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
      ]
```

This config works on expo build and applinks are auto verified, so the link directly opens the app. But on EAS build the app is not directly opened and it asks for how to open the app. 
Am I missing something when it comes to applinks (deeplinks) in android

In androidManifest.xml, it takes this form:

```
  <intent-filter android:autoVerify="true">
        <data android:scheme="https" android:host="mydomain.com" android:pathPrefix="/applogin"/>
        <data android:scheme="exp+appname"/>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <category android:name="android.intent.category.DEFAULT"/>
      </intent-filter>

```
Still does not work as intended. I have also hosted the file on /.well-known/assetlinks.json and it works with the expo build workflow. Not the app link workflow.

**Comment by brentvatne** [comment]
try this with expo-cli@5.0.0-rc.4 (you will need to set `"expoCli": "5.0.0-rc.4"` in your build profile) - it should be resolved

**Comment by ankitmaloo** [comment]
Thank you for the response. Will check and let you know.

**Comment by ankitmaloo** [comment]
Seems like I am missing something. I tried setting expo CLI at various places but it still gives an error. 

`{
  "cli": {
    "version": ">= 0.35.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "staging": {
      "expoCli": "5.0.0-rc.4",
      "android": {
        "buildType": "apk"
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
`

This says: 

Error: eas.json is not valid [ValidationError: "build.staging.expoCli" failed custom validation because 5.0.0-rc.4 is not a valid version]


Probably needs a new EAS CLI validation :)

**Comment by brentvatne** [comment]
that looks like an issue with eas-cli validation indeed. you can work around it by adding `npm i -g expo-cli@5.0.0-rc.4` in a [pre install hook](https://docs.expo.dev/build-reference/how-tos/#eas-build-specific-npm-hooks)

**Comment by ankitmaloo** [comment]
Tried it. Did not work. 

List of the things I tried. (along with changes to eas.json as suggested previously - as a standalone test)

1. Pre Install Hook. 
`  "scripts": {
    "eas-build-pre-intall":"npm i -g expo-cli@5.0.0-rc.4",
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },`

2 Post Install Hook 
 ```
 "scripts": {
    "eas-build-post-intall":"npm i -g expo-cli@5.0.0-rc.4",
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
```

3. tried as array in data field
`"android": {
      "package": 
      "intentFilters": [
        {
          "autoVerify": true,
          "action": "VIEW",
          "data":[
          {
              "scheme": "https",
              "host": "example.com",
              "pathPrefix": "/applogin"
            }],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
      ]
    },`

4. tried without an array: 
```
"data":
          {
              "scheme": "https",
              "host": "example.com",
              "pathPrefix": "/applogin"
            },
```

5. added it to package.json just in case. 

6. The weirdest thing is that it works on expo build command. 

Is there a way to enable this verification for android: https://developer.android.com/training/app-links/verify-site-associations#review-results because it would help with testing, and also tell me what the error is. I tried doing that, but it needs an android 12 device which I dont have.

**Comment by brentvatne** [comment]
@ankitmaloo - you can make any change that you want to your native project using [config plugins](https://docs.expo.dev/guides/config-plugins/) - you can refer to existing config plugins (eg: in the expo/expo and expo-cli repos) to find something similar.

**Comment by chrusch** [comment]
I'm having what I am guessing is the same issue. The app is installed on my Android phone, but the auto-verification does not seem to be triggering. As far as I can tell, all of my configuration is correct. Could someone shed some light on what the issue is or how it can be resolved?

**Comment by karanmartian** [comment]
hi same issue. auto verify not working and now app links are also not working in Android 12 and above

**Comment by ajimenezdev** [comment]
@janfranco27 I'm experiencing the same issue you described.
By any chance have you already created that plugin to add the intent-filter and it is open source?

**Comment by janfranco27** [comment]
Hey @ajimenezdev I ended up relying on this implementation https://github.com/expo/expo-cli/issues/4180#issue-1123103466
Looks like someone at the Expo team also experienced this and provided a plugin in that ticket. You can find it under the section `withAndroidVerifiedLinksWorkaround.js`. Hope it helps!

**Comment by janfranco27** [comment]
Related to https://github.com/expo/expo-cli/issues/4180

**Comment by desnor** [comment]
Hi @ankitmaloo  with regard to 
> Tried it. Did not work.
> 
> List of the things I tried. (along with changes to eas.json as suggested previously - as a standalone test)
> 
> 1. Pre Install Hook.
> 
> ```
>   "scripts": {
>     "eas-build-pre-intall":"npm i -g expo-cli@5.0.0-rc.4",
>     "start": "expo start --dev-client",
>     "android": "expo run:android",
>     "ios": "expo run:ios",
>     "web": "expo start --web",
>     "eject": "expo eject"
>   },
> ```
> 
> 2 Post Install Hook
> 
> ```
> "scripts": {
>    "eas-build-post-intall":"npm i -g expo-cli@5.0.0-rc.4",
>    "start": "expo start --dev-client",
>    "android": "expo run:android",
>    "ios": "expo run:ios",
>    "web": "expo start --web",
>    "eject": "expo eject"
>  },
> ```
> 
> 3. tried as array in data field
> 
> ```
> "android": {
>       "package": 
>       "intentFilters": [
>         {
>           "autoVerify": true,
>           "action": "VIEW",
>           "data":[
>           {
>               "scheme": "https",
>               "host": "example.com",
>               "pathPrefix": "/applogin"
>             }],
>           "category": [
>             "BROWSABLE",
>             "DEFAULT"
>           ]
>         }
>       ]
>     },
> ```
> 
> 4. tried without an array:
> 
> ```
> "data":
>           {
>               "scheme": "https",
>               "host": "example.com",
>               "pathPrefix": "/applogin"
>             },
> ```
> 
> 5. added it to package.json just in case.
> 6. The weirdest thing is that it works on expo build command.
> 
> Is there a way to enable this verification for android: https://developer.android.com/training/app-links/verify-site-associations#review-results because it would help with testing, and also tell me what the error is. I tried doing that, but it needs an android 12 device which I dont have.

I notice that your `npm` script name looks to have a typo in it - `"eas-build-pre-intall":"npm i -g expo-cli@5.0.0-rc.4"` where it has `intall` instead of `install`. Not sure that it would resolve the issue by the sound of it, but might get you further seeing it will be triggered when you expect?
