### ISSUE TITLE
Alert.alert without message kills apps even after refreshing

### ISSUE THREAD

**Issue by fullhdpixel** [expo/expo#1548]
Unrecognized selector sent to instance was thrown while invoking alertWithArgs on target AlertManager

![image](https://user-images.githubusercontent.com/7371397/37571169-568b47f0-2af9-11e8-8eb9-931736883f9f.png)
  
### Steps to Reproduce

https://snack.expo.io/SJG9v82Kz

**Comment by fullhdpixel** [comment]
See: https://stackoverflow.com/questions/41942681/alert-alert-alertmanager-with-params-exception

**Comment by terribleben** [comment]
Hey there, thanks for the report. Alert is [part of React Native](https://facebook.github.io/react-native/docs/alert.html). Expo doesn't provide any different or special Alert API, we simply include everything that's part of core React Native. Do you think you could [open an issue there](https://github.com/facebook/react-native) if you think there's a bug in React Native? Thanks!

**Comment by fullhdpixel** [comment]
Cool, I posted it there. sorry for the inconvenience
