### ISSUE TITLE
Keybaord glitch when dark theme is used

### ISSUE THREAD

**Issue by punksta** [expo/expo#15485]
### Summary

Keyboard colors are glitching when text input gets focus if dark theme is applied globally. It only occurs for autoFocus view.

Pay attention on the keyboard colors:

https://user-images.githubusercontent.com/13404754/145337037-39449bf2-e533-410a-90b7-00e15aa9952f.mov

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43.0.3, also 42.x

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /opt/homebrew/Cellar/node@16/16.13.1/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - /opt/homebrew/Cellar/node@16/16.13.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: Arctic Fox 2020.3.1 Patch 3 Arctic Fox 2020.3.1 Patch 3
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

1. Apply dark theme globally(command shift a in simulator). 
2. Use light theme in the app.
3. create a screen with autofocus input
4. enter a screen
5. pay attention on colors of the keyboard.

```
<TextInput
          autoFocus
        />
```

### workaround:
I managed to fix it by focusing on textinput manually instead of using autoFocus. The fix is unstable and works only for some views.

```
  const inputRef = useRef<TextInput>()
  useEffect(() => {
    inputRef.current?.focus()
  }, [])
  
  return (
      <TextInput
          keyboardAppearance={'light'}
          ref={inputRef}
        />
  )
  ```

**Comment by brentvatne** [comment]
this isn't in the scope of expo's tools, this is something you can post an issue to react-native about.

**Comment by great2lrn** [comment]
@punksta Were you able to solve this? I'm facing the same issue!

**Comment by mleister97** [comment]
Same issue here :(
