### ISSUE TITLE
exp build:ios -t simulator stops working

### ISSUE THREAD

**Issue by ivan-navarro-75** [expo/expo#1549]
Environment:
  OS: Linux 4.13
  Node: 7.10.1
  Yarn: 1.5.1
  npm: 4.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: 23.0.4 => 23.0.4
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Steps to Reproduce

Create a iOS build for simulator with 
`exp build:ios -t simulator
`
Install the generated app.tar.gz on an iPhone simulator 

Once the app is installed instead of open the actual app the Expo client is launched.

![screenshot](https://user-images.githubusercontent.com/25500541/37609488-85bef32e-2b9d-11e8-86ba-5116281cd684.png)

**Comment by jesseruder** [comment]
Hey @ivan-navarro-75. Are you opening the app by clicking the new icon in the simulator? I just tested this out and it worked for me. Can you upload the app.tar.gz somewhere for us to take a look?

**Comment by ivan-navarro-75** [comment]
We created a super simple app just to test the issue and also failed.
This is the link expo provided us
https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/ios%2F%40bmagnan%2Ftest-app-slug-c9aa8477-53cf-4e88-87c3-20c06e3c68b1-simulator.tar.gz

**Comment by ivan-navarro-75** [comment]
Upgrading the exp cli to 50.0.1 fixed our issue. Anyway, still don't know what causes the issue first, because at some point it just stop working.
Closing the issue.
