### ISSUE TITLE
Using react-native-svg with Expo.

### ISSUE THREAD

**Issue by MarcusHurney** [expo/expo#155]
Is it possible to use the react-native-svg npm module with Expo? I saw in the medium article about Expo v16.0.0 that npm modules that have a peer dependency with React 15.4.0 will no longer work in Expo. (https://blog.expo.io/expo-sdk-v16-0-0-is-now-available-2151d555a580)

I've found this to be true for react-native-svg. The client app on my iphone will crash if I try to use react-native-svg to render an SVG. I don't get a specific error, expo just crashes. I've narrowed the cause of the crash down to react-native-svg so I'm sure that's the cause. Is it still possible to use it somehow with expo v16.0.0?

**Comment by skevy** [comment]
It seems that react-native-svg has been updated to support RN 0.44 (the version of RN that Expo SDK 16 is based on) on their master branch, but they have not yet cut a release. I would recommend using master (and maybe bugging the authors to release?)

**Comment by skevy** [comment]
Scratch that -- they just didn't tag a release.

What is the error you're encountering?

Also, you can simply `import { Svg } from 'expo'`. You don't have to install react-native-svg separately as we include it with the SDK.

**Comment by MarcusHurney** [comment]
When I run npm install I get the warning "react-native-svg@4.4.1 requires a peer of react@>=15.4.0 but none was installed." 

When my app crashes, the Expo client on my iphone simply crashes and I'm not given an error in the logs. I recursively removed all dependencies to test what was making my app crash and it's react-native-svg. It's strange to me that I don't even get an error in the logs though.

**Comment by brentvatne** [comment]
Hi @MarcusHurney!

> When I run npm install I get the warning "react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed."

expo-sdk depends on:

`"react-native-svg": "https://github.com/expo/react-native-svg/archive/4.4.1.tar.gz",`

You'll want to remove react-native-svg from your package.json because expo-sdk includes it.

**Comment by brentvatne** [comment]
Here's an example of it working: https://snack.expo.io/rJYH-BKJW

**Comment by MarcusHurney** [comment]
Awesome. I have it working now. Thank you for the support!

**Comment by GumboFroehn** [comment]
Sorry for gravedigging but I have a somewhat related question. I need to use a fork of react-native-svg since there are some issues with rendering raster images. Is there any way I can "force" expo to not use the master branch?

**Comment by hoang-innomizetech** [comment]
hi all,

I am using latest expo 32.0.5 version. My project also used victory-native for charts, it requires react-native-expo, but when I install to my project, I got this error **Tried to register two views with the same name RNSVGRect**. Does anyone know how to get this working?

Thank all

**Comment by schomper** [comment]
Hi @hoang-innomizetech ,

By following the advice in the top answer on this question I was able to resolve this issue for myself.
https://stackoverflow.com/questions/49468040/can-victory-native-be-used-with-expo

**Comment by hoang-innomizetech** [comment]
@schomper yeah, I read this one. Actually, we are able to make this work with expo 29.0.0, but when we trying to upgrade to the latest expo 32, we got the above error.

**Comment by zxl634** [comment]
Just ran into the same problem again with SDK 32 (I posted the SO question and answer referred to above) and just confirmed that using yarn instead of npm solved it again
