### ISSUE TITLE
MainActivity is not relaunched after a fatal error on detached Android

### ISSUE THREAD

**Issue by alxyuu** [expo/expo#1550]
### Environment

Android, ExpoKit

### Steps to Reproduce

1. Run JS in production mode
2. Induce an uncaught JS error
3. Press reload on the error screen (if below the auto reload buffer, otherwise it will reload automatically)

### Expected Behavior

MainActivity should be relaunched

### Actual Behavior

ShellAppActivity is launched instead. This is problematic as custom native modules are no longer loaded, as well as any other customizations made to MainActivity.

### Reproducible Demo

Build and run on android: https://github.com/alxyuu/android-error-activity
It should say `TestModule available: Yes` initially, but change to `No` after pushing the button to crash the app

**Comment by jesseruder** [comment]
Thanks @alxyuu. FYI we're probably going to get rid of this error screen and give the developer a callback instead.

**Comment by alxyuu** [comment]
@jesseruder the issue is also present when the app auto reloads to recover from an error, without the error screen. I don't suppose a fix would make it in time for sdk26?

**Comment by esamelson** [comment]
Hi @alxyuu - thanks for the report and the super easy repro. This will be fixed in 26 👍

**Comment by esamelson** [comment]
Closing this as SDK 26 expokit is out as of now. Please reopen if the issue persists on 26.
