### ISSUE TITLE
[SDK44] EAS build + Background location freezes the App

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#15504]
### Summary

if you kill the app while background location is on , the app is not killed if you launch it again it will go back to the same screen as if it was only backgrounded , i confirmed this with Splash screen

to demonstrate this , i made a simple app with background location and Splash screen that's hidden manually after 4 seconds of app launch

Steps to reproduce :

-- make a build with eas build --

1- Open the app . ( splash screen will take 4 seconds to hide )
2- Click the button and grant location permissions .
3- background task should start , you can see the foreground service .
4 - Kill the app .
5 - start it again , it will start without splash screen , as if it was backgrounded 
[eas_backgroundlocation_sdk44.zip](https://github.com/expo/expo/files/7696119/eas_backgroundlocation_sdk44.zip)
.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^44.0.0-beta.1 => 44.0.0-beta.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

Steps to reproduce :

-- make a build with eas build --

1- Open the app . ( splash screen will take 4 seconds to hide )
2- Click the button and grant location permissions .
3- background task should start , you can see the foreground service .
4 - Kill the app .
5 - start it again , it will start without splash screen , as if it was backgrounded 
[eas_backgroundlocation_sdk44.zip](https://github.com/expo/expo/files/7696119/eas_backgroundlocation_sdk44.zip)

**Comment by brentvatne** [comment]
can you share the logs that you observe when the app crashes?

**Comment by islamouzou** [comment]
> can you share the logs that you observe when the app crashes?

It doesn't crash with an exception , it's just not killed , the app starts directly without splash screen , and all the states remain the same as if it was only backgrounded. even  socket.io connection ID stays the same so the App is not really killed if you kill it while background location is working  , if i disable background location and kill it , it will start normally . it happens only with eas build .

**Comment by brentvatne** [comment]
got it, thanks. if you'd like to proceed with investigating it further, you can run `expo prebuild` and then compile the app locally in android studio and debug. any other information you discover would be helpful for us when we are free to work on this

**Comment by islamouzou** [comment]
> got it, thanks. if you'd like to proceed with investigating it further, you can run `expo prebuild` and then compile the app locally in android studio and debug. any other information you discover would be helpful for us when we are free to work on this

I'll do that , you're welcome .

**Comment by islamouzou** [comment]
Any news about this :( ????

**Comment by islamouzou** [comment]
@Kudo  Any news about this :( ????

**Comment by Kudo** [comment]
hi @islamouzou, i looked into this today and don't think that is an issue.
because there is the background task, the react instance keeps running even the Activity be destroyed. the `SplashScreen.preventAutoHideAsync()` in your App.js will not be re-executed again. if you want to have same experience for your case, one way to do this is binding `SplashScreen.preventAutoHideAsync()` in component lifecycle.
e.g.

```js
export default function App() {
  const [splashSetupReady, setSplashSetupReady] = useState(false);
  useEffect(() => {
    SplashScreen.preventAutoHideAsync();
    setSplashSetupReady(true);
  }, []);

  return (splashSetupReady && <ContentView />);
}

function ContentView() {
  useEffect(() => {
    setTimeout(() => {
      SplashScreen.hideAsync();
    }, 4000);
  }, []);

  return (
    <View style={styles.container}>
      // ...
    </View>
  );
}
```

**Comment by islamouzou** [comment]
@Kudo  thanks for your reply 

However , in expo build it works as expected , even if the task is running .

the splash screen doesn't really bother me , but in my project i want  the to always execute the first screen  , which in my case fetches the user data  and a lot of other verifications . but with this behaviour even the previous  states are still the same .

for example :

when i enter the App , the first screen where the data are fetched is AuthLoading , when i fetch all the data it navigates automatically to the MapScreen . with eas build behaviour , the Authloading is ignored it goes directly to the last screen that the user was in before killing the app . so a lot of states aren't getting updated this way .

with expo build  it always starts with the splash screen then Authloading to verify some informations then to the MapScreen , that's the behaviour i'm looking for . How can i achieve this ??

**Comment by Kudo** [comment]
i would say a standalone app from `expo build` has some difference to an eas build or a react-native app. IIRC, for instance, the default react instance lifecycle in standalone app may bind to Activity. so the difference would be expected.

is it possible to bind your AuthLoading logic also into a component lifecycle like the splash code snippet above?

**Comment by islamouzou** [comment]
@Kudo  I'll let you know once i get the hang of it . thank you so much for looking into this . ^^
