### ISSUE TITLE
[SDK44] EAS Build fail for reanimated@2.3.0

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#15503]
### Summary

EAS is failing to build app with the newer version of react-native-reanimated 2.3.0 and react-native-gesture-handler 2.0.0 , here is the error : 

I tried to go back to previous version   "react-native-reanimated": "~2.2.0" , "react-native-gesture-handler": "~1.10.2", and the build succeded .

`[stderr] Caused by: com.android.tools.r8.utils.b: Type com.swmansion.reanimated.BuildConfig is defined multiple times: /root/workingdir/build/node_modules/react-native-reanimated/android/build/.transforms/03bf09f2beb08b3a40b233f7109d06bc/transformed/classes/classes.dex, /root/workingdir/build/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes2.dex
[stderr] 	at com.android.tools.r8.utils.T0.error(SourceFile:1)
[stderr] 	at com.android.tools.r8.utils.T0.a(SourceFile:2)
[stderr] 	at com.android.tools.r8.utils.R0.b(SourceFile:6)
[stderr] 	at com.android.tools.r8.utils.R0.a(SourceFile:24)
[stderr] 	at com.android.tools.r8.utils.R0.a(SourceFile:10)
[stderr] 	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
[stderr] 	at com.android.tools.r8.utils.R0.a(SourceFile:6)
[stderr] 	at com.android.tools.r8.graph.O0$c.f(SourceFile:3)
[stderr] 	at com.android.tools.r8.dex.a.a(SourceFile:294)
[stderr] 	at com.android.tools.r8.dex.a.a(SourceFile:222)
[stderr] 	at com.android.tools.r8.D8.d(D8.java:6)
[stderr] 	at com.android.tools.r8.D8.b(D8.java:1)
[stderr] 	at com.android.tools.r8.utils.Y.a(SourceFile:36)
[stderr] 	... 38 more`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^44.0.0-beta.1 => 44.0.0-beta.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

`[stderr] Caused by: com.android.tools.r8.utils.b: Type com.swmansion.reanimated.BuildConfig is defined multiple times: /root/workingdir/build/node_modules/react-native-reanimated/android/build/.transforms/03bf09f2beb08b3a40b233f7109d06bc/transformed/classes/classes.dex, /root/workingdir/build/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes2.dex
[stderr] 	at com.android.tools.r8.utils.T0.error(SourceFile:1)
[stderr] 	at com.android.tools.r8.utils.T0.a(SourceFile:2)
[stderr] 	at com.android.tools.r8.utils.R0.b(SourceFile:6)
[stderr] 	at com.android.tools.r8.utils.R0.a(SourceFile:24)
[stderr] 	at com.android.tools.r8.utils.R0.a(SourceFile:10)
[stderr] 	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
[stderr] 	at com.android.tools.r8.utils.R0.a(SourceFile:6)
[stderr] 	at com.android.tools.r8.graph.O0$c.f(SourceFile:3)
[stderr] 	at com.android.tools.r8.dex.a.a(SourceFile:294)
[stderr] 	at com.android.tools.r8.dex.a.a(SourceFile:222)
[stderr] 	at com.android.tools.r8.D8.d(D8.java:6)
[stderr] 	at com.android.tools.r8.D8.b(D8.java:1)
[stderr] 	at com.android.tools.r8.utils.Y.a(SourceFile:36)
[stderr] 	... 38 more`

**Comment by brentvatne** [comment]
you can pull in this patch for now: https://github.com/software-mansion/react-native-reanimated/pull/2713

we're waiting for it to be rolled out in a patch release

**Comment by brentvatne** [comment]
react-native-reanimated@2.3.1 is shipped with expo sdk 44 now
