### ISSUE TITLE
[android] app.json: `android.icon` prop not overriding `icon`

### ISSUE THREAD

**Issue by mwegener-com** [expo/expo#15524]
### Summary

The prop `android.icon` is not overriding the default `icon` prop.
If I build my app with eas build --profile preview --platform android, always the default icon is set as the home screen icon, even if I specify a custom android icon.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.0.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 7.0.3 - /usr/local/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.2, 30.0.0, 32.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.4 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

app.json:
```json
{
	"expo": {
		"name": "Cabernet und Co",
		"slug": "CabernetUndCo",
		"version": "0.0.1",
		"orientation": "portrait",
		"icon": "./assets/icon.png",
		"splash": {
			"image": "./assets/splash.png",
			"resizeMode": "contain",
			"backgroundColor": "#FFFFFF"
		},
		"updates": {
			"fallbackToCacheTimeout": 0
		},
		"assetBundlePatterns": ["**/*"],
		"androidNavigationBar": {
			"barStyle": "dark-content",
			"backgroundColor": "#FFFFFF"
		},
		"android": {
			"googleServicesFile": "./config/google-services.json",
			"config": {
				"googleMaps": {
					"apiKey": "..."
				}
			},
			"icon": "./assets/icon_android.png",
			"package": "com.mwegener.cabernetco"
		},
		"ios": {
			"googleServicesFile": "./config/GoogleService-Info.plist",
			"config": {
				"googleMapsApiKey": "..."
			},
			"bundleIdentifier": "com.mwegener.cabernetco"
		},
		"plugins": [
			"@react-native-firebase/app",
			"expo-community-flipper",
			[
				"with-rn-image-crop-picker",
				{
					...
				}
			]
		],
		"web": {
			"favicon": "./assets/favicon.png"
		}
	}
}
```

eas.json:
```json
{
	"build": {
		"base": {
			"env": {}
		},
		"preview": {
			"distribution": "internal",
			"ios": {
				"cocoapods": "1.11.2"
			}
		}
	},
	"cli": {
		"version": ">= 0.39.0",
		"requireCommit": true
	}
}
```

Default icon:
![icon](https://user-images.githubusercontent.com/64470126/145736093-7ca3d640-3922-4296-b307-caa3bcc3af43.png)

Android icon:
![icon_android](https://user-images.githubusercontent.com/64470126/145736113-c0ae5419-1464-46af-9344-689aa560885b.png)

**Comment by brentvatne** [comment]
@mwegener-com - for future reference, what you have provided is not a minimal reproducible example. please in the future follow these guidelines: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mwegener-com** [comment]
Amazing, thanks @EvanBacon!
