### ISSUE TITLE
Expo 44 Beta Update Results in Reanimated 2 worklet error

### ISSUE THREAD

**Issue by CodingItWrong** [expo/expo#15522]
### Summary

I followed the instructions in the [Expo 44 beta blog post](https://blog.expo.dev/expo-sdk-44-beta-is-now-available-75d9751b0a18) to update my app. It ran fine on web, but when I attempted to run it on iOS I get two errors, one of which is "Error: Requiring module "node_modules/react-native-reanimated/src/Animated.js", which threw an exception: Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.0-beta.1

### Environment

```
Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.2.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/josh/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0-beta.1 => 44.0.0-beta.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed
```

### Reproducible demo

This issue is specifically about updating a project, so the reproduction seems like it needs to be a link to the project. Here is a link to a branch where you can see this occur: https://github.com/CodingItWrong/surely-expo/pull/68

Steps to reproduce:

- yarn install
- yarn start
- run on iOS simulator

**Comment by CodingItWrong** [comment]
Full error output is:

```
Error: Requiring module "node_modules/react-native-reanimated/src/Animated.js", which threw an exception: Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:211180:3 in global code
```

**Comment by CodingItWrong** [comment]
The other error that occurs on app start is https://github.com/expo/expo/issues/15523

**Comment by brentvatne** [comment]
@CodingItWrong - can you create a minimal reproducible example? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by brentvatne** [comment]
ah, i see. your project is indeed missing the reanimated plugin: https://github.com/CodingItWrong/surely-expo/blob/expo-44-beta/babel.config.js

https://docs.expo.dev/versions/latest/sdk/reanimated/#installation

**Comment by CodingItWrong** [comment]
@brentvatne Thanks for the help for my project. But thinking about the upgrade in general, should this be added to the upgrade steps? If my project works in Expo 43 but errors in Expo 44 after `expo upgrade` upgrades Reanimated, then it seems like a link to Reanimated instructions for updating would be valuable in the upgrade documentation.

**Comment by AlexMachin1997** [comment]
Do you need to do anything special besides following the instructions for the installation ?

I'm in the process of updating my app to use SDK 44 but I'm still having this issue even after installing reanimated and providing the neccessary config.

**Comment by CodingItWrong** [comment]
@AlexMachin1997 The only change I needed to make to get it working in my app was this:

https://github.com/CodingItWrong/surely-expo/pull/68/commits/49f2f60c1ced1c4fea4b32a41bb994518ab5dfd0

Feel free to compare the overall setup to my app to see if it reveals any info to you; it's open-source

**Comment by markmccoid** [comment]
Also, remember that once you make that change to your babel config, you should use 

`yarn start --clear`

If you don't clear, the error will persist.
