### ISSUE TITLE
Unable to generate IPA. Standalone build fails 

### ISSUE THREAD

**Issue by nbatwara** [expo/expo#1553]
I am getting the exact same issue as issue #1362  even though I'm using the --apple-enterprise-account flag. To create the provision profile I chose 'In House' Distribution but the standalone build fails at exactly this:

ExpoKitApp.xcworkspace --scheme ExpoKitApp --archive_path /tmp/turtle/01963796-679a-4a6e-b5af-8069a8f4d244/01963796-679a-4a6e-b5af-8069a8f4d244.xcarchive --skip_build_archive true -i 5009F46315F3F6175ABE0A60DDBC1A2AAA4D68DE --export_options /tmp/turtle/01963796-679a-4a6e-b5af-8069a8f4d244/provisioning-01963796-679a-4a6e-b5af-8069a8f4d244/export-options.plist --export_method enterprise --export_xcargs OTHER_CODE_SIGN_FLAGS="--keychain /tmp/turtle-agent/b54de441-2c48-11e8-af06-0050568eed5c.keychain" -o /tmp/turtle/01963796-679a-4a6e-b5af-8069a8f4d244/01963796-679a-4a6e-b5af-8069a8f4d244-build --verbose
Unable to generate IPA.
unable to build and sign IPA

Any fix? Suggestions?

Build also fails when I let expo handle all certs and credentials with the following error:

14:39:28 [exp] Error while gathering & validating credentials
14:39:28 [exp] Reason:You are not allowed to perform this operation. Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support You are not allowed to perform this operation. Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support, raw:{"responseId":"a6e2c9ad-ad5f-4afa-b3dd-035e62f13fa8","resultCode":1200,"resultString":"You are not allowed to perform this operation. Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support","userString":"You are not allowed to perform this operation. Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support","creationTimestamp":"2018-03-19T18:39:27Z","protocolVersion":"QH65B2","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action","httpCode":200}

I have admin privileges on the team account with the ability to create/delete certs and provisioning profiles.

PLEASE HELP!

**Comment by terribleben** [comment]
Hey there, really sorry you're running into trouble.

It's possible your profiles/certs are in some inconsistent state. I think your best strategy is to clear out your certificates and provisioning profiles (by manually deleting them from the Apple Developer website), then start over with `exp build:ios -c` and see if "let expo handle it" will succeed after that.

@dsokal any idea about "You are not allowed to perform this operation" ? I've never seen that specific message before.

**Comment by nbatwara** [comment]
Hey I actually solved the the issue just this morning. It was an issue with a missing private key in my keychain for a distribution cert that I was using. I'm going to close the issue now. Thank you!
