### ISSUE TITLE
SDK 44 - RCTBridge required dispatch_sync to load RNGestureHandlerModule

### ISSUE THREAD

**Issue by Hirbod** [expo/expo#15532]
### Summary

After upgrading to  44.0.0-beta.1, I get following yellow box warning, which I haven't seen before.

```[javascript] RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo

-

**Comment by brentvatne** [comment]
https://github.com/software-mansion/react-native-gesture-handler/issues/722

upstream

**Comment by Hirbod** [comment]
@brentvatne this error never happened for me, just after the upgrade to SDK 44.
Don't you think it is related or related to RNGH v2?

**Comment by brentvatne** [comment]
@Hirbod - probably!

**Comment by Hirbod** [comment]
I posed the solution at the upstream thread.
