### ISSUE TITLE
Unable to download the latest react-antive-gesture-handler on expo snack 

### ISSUE THREAD

**Issue by paulwongx** [expo/expo#15540]
When using Expo Snack. Whenever I try to import `react-native-gesture-handler` it defaults to ~1.10.2. Changing the number doesn't allow upgrading the package and there's no cli (as far as I'm aware) that allows one to download the latest version.

How can you download the latest version of the package? Or is this something just not possible?

**Comment by brentvatne** [comment]
react-native-gesture-handler is included in the Expo SDK and the version provided by the SDK version selected for Snack will be used
