### ISSUE TITLE
exp detach Cannot find module 'path-exists'

### ISSUE THREAD

**Issue by 3axap4eHko** [expo/expo#1554]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: ^16.2.0 => 16.2.0
  react-native: 0.52 => 0.52.3

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/3axap4ehko-61c4c3a3-a853-40f9-a7da-039de79066cc.tar.gz

### Steps to Reproduce

1. `EXPO_DEBUG=true exp detach`

### Expected Behavior

Should finish without errors
### Actual Behavior

```bash
12:16:43 [exp] Cannot find module 'path-exists'
12:16:43 [exp] Error: Cannot find module 'path-exists'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at _load_pathExists (/xdl/src/detach/installPackageAsync.js:4:1)
    at /xdl/src/detach/installPackageAsync.js:19:34
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/exp/node_modules/xdl/build/detach/installPackageAsync.js:23:191)
    at /usr/local/lib/node_modules/exp/node_modules/xdl/build/detach/installPackageAsync.js:23:437
    at new Promise (<anonymous>)
```

**Comment by terribleben** [comment]
@fson is this possibly related to the "install Expo's fork of React Native" code?

@3axap4eHko there's a slight chance this is related to your usage of npm 5, so if you're still stuck, you might try using a different version of npm.

**Comment by marf** [comment]
Same problem here

**Comment by fson** [comment]
Hey all, this should be fixed in the latest version of exp (50.0.5).

**Comment by StudioAleph** [comment]
I have the same error:

`
17:43:16 [exp] D:\projects\SefrTaSad\images\connection.gif: Cannot find module '
D:\projects\SefrTaSad\node_modules\exponent\tools\hashAssetFiles'
17:43:16 [exp] Failed building JavaScript bundle.
17:44:18 [exp] D:\projects\SefrTaSad\images\connection.gif: Cannot find module '
D:\projects\SefrTaSad\node_modules\exponent\tools\hashAssetFiles'
17:44:18 [exp] Failed building JavaScript bundle.
17:44:22 [exp] D:\projects\SefrTaSad\images\connection.gif: Cannot find module '
D:\projects\SefrTaSad\node_modules\exponent\tools\hashAssetFiles'
17:44:22 [exp] Failed building JavaScript bundle.
17:44:36 [exp] D:\projects\SefrTaSad\images\connection.gif: Cannot find module '
D:\projects\SefrTaSad\node_modules\exponent\tools\hashAssetFiles'
17:44:36 [exp] Failed building JavaScript bundle.
17:46:01 [exp] D:\projects\SefrTaSad\images\connection.gif: Cannot find module '
D:\projects\SefrTaSad\node_modules\exponent\tools\hashAssetFiles'
17:46:01 [exp] Failed building JavaScript bundle.
`

**Comment by StudioAleph** [comment]
when I run exp build:android it gives me this error
