### ISSUE TITLE
Eas free ios device build

### ISSUE THREAD

**Issue by Stevemoretz** [expo/expo#15554]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

Can we use, xcode free provisioning to build an app for an ios device?
Push notification and some features are not available in the simulator.

https://steemit.com/xcode/@ktsteemit/xcode-free-provisioning

**Comment by brentvatne** [comment]
we don't support this provisioning method because it doesn't seem to be supported by the api that we use for generating credentials
