### ISSUE TITLE
Unable to remove Android permissions for ExpoKit app

### ISSUE THREAD

**Issue by riwu** [expo/expo#1555]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003
  Gradle: 4.1

Packages: (wanted => installed)
  expo: ^24.0.0 => 24.0.2
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/riwu-7a379159-d0a4-4352-bd59-ddbd1ea9471f.tar.gz

### Steps to Reproduce

I specified limited permissions in [app.json](https://github.com/riwu/expo-android-permissions/blob/master/client/app.json#L13) and tried to remove permissions via the [AndroidManifest](https://github.com/riwu/expo-android-permissions/blob/master/client/android/app/src/main/AndroidManifest.xml#L263) as well. 

But [my app on Google Play](https://play.google.com/store/apps/details?id=riwu.slions) still lists all permissions in the world:
![](https://i.imgur.com/FGUEeh0.png)

[Here's the generated manifest-merger-release-report](https://gist.github.com/riwu/85dd60a4720c3dd52325002da079cf79).

The Github repo I linked above is an exact clone of the actual source except `src` folder (which contains only javascript) is removed, so it should be compilable.

**Comment by esamelson** [comment]
Hi @riwu - have you tried just deleting these lines? https://github.com/riwu/expo-android-permissions/blob/master/client/android/app/src/main/AndroidManifest.xml#L29 Removing them should fix the problem for you. I think they would have been removed automatically when you detached if you had specified limited permissions in app.json at that point, but after detaching, the app.json settings don't have any bearing anymore.
