### ISSUE TITLE
App Crashes when using face detection with camera

### ISSUE THREAD

**Issue by aarangara** [expo/expo#15551]
### Summary

I have a button in my view that opens a camera which has face detection enabled. 

On some of the android devices, as soon as I click the button that is supposed to open the camera, the app crashes immediately. Below is what I get in app crash report

```
java.lang.IllegalArgumentException: Invalid image data size
  at com.google.android.gms.vision.Frame$Builder.setImageData (Frame.java:13)
  at com.google.firebase.ml.vision.common.FirebaseVisionImage.zza (FirebaseVisionImage.java:152)
  at com.google.android.gms.internal.firebase_ml.zzri.zza (zzri.java:11)
  at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.detectInImage (FirebaseVisionFaceDetector.java:25)
  at expo.modules.facedetector.ExpoFaceDetector.detectFaces (ExpoFaceDetector.java:112)
  at expo.modules.camera.tasks.FaceDetectorTask.execute (FaceDetectorTask.java:40)
  at expo.modules.camera.ExpoCameraView$1.onFramePreview (ExpoCameraView.java:142)
  at com.google.android.cameraview.CameraView$CallbackBridge.onFramePreview (CameraView.java:604)
  at com.google.android.cameraview.Camera1.onPreviewFrame (Camera1.java:766)
  at android.hardware.Camera$EventHandler.handleMessage (Camera.java:1227)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8595)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

The moment I disable the face detection, it works fine.

I think my issue is similar to this issue - https://github.com/expo/expo/issues/2422 (this one was for bar code scanning).

And I guess the fix would be similar as well - to make a check for image data size before making the call to detectInImage or wrap it in a try-catch block to prevent this exception from crashing the app (https://github.com/expo/expo/pull/2772)

May be something like this in `packages/expo-face-detector/android/src/main/java/expo/modules/facedetector/ExpoFaceDetector.java` :
<img width="669" alt="image" src="https://user-images.githubusercontent.com/2873128/145995758-947b8c37-6304-47c3-8f47-f5c82a035510.png">

A similar issue was also reported here by another dev :  #https://forums.expo.dev/t/expo-standalone-android-app-crashes-with-face-detector-error/41222

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.0

### Environment

  Expo CLI 4.12.11 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.11.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.6.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /Users/a.r/.rvm/rubies/ruby-2.4.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 21, 25, 26, 27, 28, 29
        Build Tools: 21.1.2, 25.0.0, 26.0.2, 28.0.3, 29.0.2
        System Images: android-21 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.11
    Expo Workflow: bare

### Reproducible demo

https://snack.expo.dev/@aarangara/groaning-stroopwafels

I have tried it on 3 tablets with following results

Lenovo Tab M10 - app crashes 97% of the time  (running Android 10)
Samsung Galaxy Tab A7 Lite - app crashes 90% of the time  (running Android 11)
Samsung Galaxy Tab A7 10.4" Tablet - app crashes 10% of the time (running Android 11)

**Comment by aarangara** [comment]
@bbarthec - can you re-open this issue as it was auto-closed?

**Comment by anutting** [comment]
We're seeing this cause a crash in my project. Is there anything I can do on the React side to handle it?

**Comment by aarangara** [comment]
> We're seeing this cause a crash in my project. Is there anything I can do on the React side to handle it?

I have disabled face detection in my app until this is fixed in expo as I am not sure how to fix it on React side.

**Comment by anutting** [comment]
We're still experiencing crashes like this on Android

**Comment by aarangara** [comment]
@bbarthec - did you get a chance to look into this?
