### ISSUE TITLE
[ios, android] Expo.takeSnapshotAsync truncate (crop) image height

### ISSUE THREAD

**Issue by rodrix** [expo/expo#1557]
Hi, I need to take a screenshot of a entire (large on height) ScrollView.
I'm using Expo.takeSnapshotAsync to take the screenshot, but the returned image is truncated (croped) on height, hiding some part of ScrollView content.

This behavior could observed on both platforms, ios and android, using expo sdk v25.0.0.

Any tip is welcome.

Thanks!

Edited:
Working sample can be found on:
https://snack.expo.io/rJ9_BTWqz

**Comment by nikki93** [comment]
What view are you taking the snapshot of? Make sure it's some view that contains all the stuff you want to snapshot, like the root view of your application or such.

**Comment by rodrix** [comment]
Hey @nikki93, look at this sample snippet based on my use case:

```
 render() {
 		return (
                              <BaseContainer screenTitle="Title"
                                  <ScrollView ref={(ref) = this.screenshotIt = ref}
 	                              <TextBlah Blah Blah</Text
 	                              <View style={styles.someStyle}
 	                                    <CommonInfoComponent/>

                                              /*This iteration generates a large content, resizing the ScrollView bounds*/
                                              {this.props.arrayBolado.map((element, index) = (
 		                                 <View key={i} ... some iterable stuff ...</View 
                                              )}
                                              ...
                                        </View
                                   </ScrollView
                               </BaseContainer
                           );
 }
```

**Comment by terribleben** [comment]
Hey @rodrix, would it be possible to provide a [Snack](https://snack.expo.io) that reproduces the view you're trying to capture, and also your usage of `takeSnapshotAsync` ?

**Comment by rodrix** [comment]
Hi @terribleben, thanks to reply.

The working sample can be found on:
https://snack.expo.io/rJ9_BTWqz

Obs:
Even if you set the height of screenshot, the image will be cropped.

If you need some more clarification, let me know. Thanks!

**Comment by rodrix** [comment]
Any news? :}

**Comment by rodrix** [comment]
So far, no good.
I can't found any workaround, my app still in development and the feature that use expo screenshot, is not deployed on app stores yet.
My b plan is create a server side workarout, using IReport or something else

**Comment by rodrix** [comment]
News?

**Comment by sjchmiela** [comment]
If I understand correctly this has been fixed in `react-native-view-shot` v2, which is now included in Expo. 🎉
