### ISSUE TITLE
I want Expo to upgrade SDK 43 but install SDK 44

### ISSUE THREAD

**Issue by ahmetbasdan** [expo/expo#15577]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by ahmetbasdan** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/18085857/146201669-63994ada-796e-4dee-b214-3efa89f087a3.png)

**Comment by brentvatne** [comment]
which expo-cli version do you have installed?

**Comment by ahmetbasdan** [comment]
I canceled the EXPO_BETA environment. Fixed thanks
