### ISSUE TITLE
[SDK 44] Monorepo renders blank screen

### ISSUE THREAD

**Issue by nandorojo** [expo/expo#15585]
### Summary

I upgraded to SDK 44 in the Moti Example app. It's in a monorepo.

When I run `expo start --web`, everything works fine.

But the iOS app renders a blank screen:

![image](https://user-images.githubusercontent.com/13172299/146253692-e5f91f55-a3d2-4235-8870-ef3fa8e938c0.png)

I tried all the classic stuff, like reinstalling expo go on the simulator, deleting node modules, `expo start -c`, etc. 

Doing `expo run:ios` fixed it, so I'll just stick to that. But I wanted to share the issue. I also tried the esbuild minifier.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```sh
Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30
        Build Tools: 29.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.39.0
      expo-cli: 5.0.1
    Expo Workflow: managed
```

### Reproducible demo

Currently this is happening in the `moti` repo on the `expo-module-scripts` branch: https://github.com/nandorojo/moti/tree/expo-module-scripts

- `yarn`
- `cd examples/with-expo`
- `yarn ios`

Since I'm not sure how actionable this is since I fixed it with a custom dev client, I'll just close this after sharing.

**Comment by nandorojo** [comment]
Closing since this got fixed with `expo run:ios`. But the issue remains for `expo start`.

**Comment by raarts** [comment]
I have the same or a similar problem. It's in a monorepo where I already have an expo project. This is the second one. Web gives a blank screen (expo init with tabs template). iOS emulator says the following:

```
Unable to resolve module ./defaultTransitions from /Users/raarts/work/novantum/education/athena/node_modules/react-native-reanimated/src/reanimated2/layoutReanimation/index.ts: 

None of these files exist:
  * ../../node_modules/react-native-reanimated/src/reanimated2/layoutReanimation/defaultTransitions(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  * ../../node_modules/react-native-reanimated/src/reanimated2/layoutReanimation/defaultTransitions/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  2 | export * from './animationBuilder';
  3 | export * from './defaultAnimations';
> 4 | export * from './defaultTransitions';
    |                ^
  5 |

ABI44_0_0RCTFatal
__37-[ABI44_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```
