### ISSUE TITLE
[Snack] Unable to re-save to profile 

### ISSUE THREAD

**Issue by riwu** [expo/expo#1558]
Pretty minor issue:
When we save a project on snack, it will [prompt us to save it to our Expo profile](https://i.imgur.com/ifg7GVC.png). 
If we decline it, there's no way to bring that prompt up again, thus requiring duplicating the files in a new project to get the prompt again.

**Comment by schazers** [comment]
Hi! Thanks for the report - you are correct! We are aware of this and plan to change it when we can. Have fun snack-ing :)

**Comment by tcdavis** [comment]
Sorry, I have wanted to fix this for sooo long.
If you reload the page and save you'll get the option to save to profile again.
