### ISSUE TITLE
Error installing FBAudienceNetwork

### ISSUE THREAD

**Issue by abhitheawesomecoder** [expo/expo#1559]
When I try to pod install after detaching I get the error below :

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/k2/p5qfxfq92kn5nyc4qxrrjvp00000gn/T/d20180321-2767-15zj1r8/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-4.27.2.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.9M    0 14.9M    0     0   139k      0 --:--:--  0:01:49 --:--:--  191k
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

**Comment by terribleben** [comment]
Thanks for the report. It looks like your computer was having transient connectivity issues while trying to download the library for installation. Can you try again with a consistent internet connection?

If the problem persists, can you paste the following here?

- Output of `pod --version`
- Contents of `package.json`
- Contents of `Podfile`
- If `Podfile.lock` exists, look up what value it has for `FBAudienceNetwork`

**Comment by cesarve77** [comment]
It was a problem in facebook developer network, now is working.

You can close the issue 

thanks

**Comment by singleseeker** [comment]
It doesn't work again. Any update?

**Comment by aftabaig** [comment]
Any solution to this? I am getting the same exception during "pod install"

**Comment by new-soul** [comment]
Me too.

**Comment by kyungjoongo** [comment]
same issue.

**Comment by new-soul** [comment]
> same issue.

Pull the last version which has the pod file local.

**Comment by new-soul** [comment]
> same issue.

Pull the last version which has the pod file local.

**Comment by kyungjoongo** [comment]
> > same issue.
> 
> Pull the last version which has the pod file local.

how to pull  last version which has the pod file local.?????

**Comment by kyungjoongo** [comment]
same error message 
--------------------------
Installing FBAudienceNetwork (5.0.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/1h/ckmts8m17lbdy8jxf74ywyqw0000gn/T/d20180927-18437-1qooeoj/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.0.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2301k    0 2301k    0     0  27668      0 --:--:--  0:01:25 --:--:-- 27570
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)


[!] Automatically assigning platform `ios` with version `9.0` on target `genius001` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by felix-cao** [comment]
Same issue,  please reopen the issue

**Comment by houmie** [comment]
Same issue here. What is the solution?

**Comment by dustturtle** [comment]
I can download the file in the site. but what's wrong about the script? anybody to solve this?

**Comment by dustturtle** [comment]
Why this is closed?> this is a serious issue!

**Comment by iTarek** [comment]
While lot of developers have this problem why ignore it. I have the same problem

```
[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/xd/_f0kws4j5_z08tk62zyyp8000000gn/T/d20181113-45744-1hh3ki5/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.1.0.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.7M    0 14.7M    0     0  64442      0 --:--:--  0:03:59 --:--:--     0
curl: (56) Unexpected EOF 
```

**Comment by dustturtle** [comment]
I have got this done.  If you use vpn or some proxy, in terminal you may need to run codes like this:export ALL_PROXY=socks5://127.0.0.1:1086 (I use shadowsocks)

**Comment by daysv** [comment]
Same issue in china.

**Comment by zilan830** [comment]
I also have this problem

**Comment by dustturtle** [comment]
@daysv @zilan830 see my posts, I have got this done. in China.

**Comment by zilan830** [comment]
你可以说中文了~哈哈哈哈哈哈哈哈

**Comment by Pines-Cheng** [comment]
same issue.

**Comment by majirosstefan** [comment]
same in Europe ->>>
 
[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/d2/wn3hh79179s7_t1j7kyrpsr00000gn/T/d20190204-5188-12nl8rp/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.1.1.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6062k    0 6062k    0     0   110k      0 --:--:--  0:00:54 --:--:--  114k
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

**Comment by majirosstefan** [comment]
well, for me it seems to be only problem with net connection, got it working finally.

**Comment by ChrisRyuGS** [comment]
same issue in Korea

**Comment by sanjukhunt** [comment]
I am also fetching the same issue. Even try with older tag version but still get same error

**Comment by jhessin** [comment]
+1
Same issue

**Comment by akagaeng** [comment]
I resolve this issue as follows.

Pod version

I tried on `v1.6.1` and `v1.5.2`. But it fails. (Mac app version)
So I uninstalled every version of cocoapods. 

```
$ gem uninstall cocoapod
```

And I install cocoapod again with gem.

```
$ gem install cocoapods -v 1.5.3
```

My cocoapod version is now `v1.5.3`

```
$ pod --version
1.5.3
```

In ios directory,  run pod install.

```
<your project directory>/ios $ pod install
```

Finally is it successfully installed!

```
Pod installation complete! 
There are 54 dependencies from the Podfile and 63 total pods installed.
```

**Comment by Davidzhu001** [comment]
any solution?

**Comment by jhessin** [comment]
The only solution I have found is retrying about 5-10 times. It eventually works.

**Comment by Davidzhu001** [comment]
@jhessin lol, thanks

**Comment by Davidzhu001** [comment]
i don't know why, facebook has this kinda low issue

**Comment by cloudy-ninja** [comment]
I got the same error.

============================
[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/lz/qlm3ynvj5sz3t1h3ngm9grd00000gn/T/d20190421-99262-1jevit9/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.1.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42.1M    0 42.1M    0     0   627k      0 --:--:--  0:01:08 --:--:-- 1076k
curl: (16) Error in the HTTP2 framing layer

**Comment by oxyii** [comment]
`4.99.0` - the same error but `4.99.3` works fine for me

**Comment by iRemark** [comment]
Why ignore it? I have the same problem. lose hope...
Installing FBAudienceNetwork (5.4.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/gk/175qkbwd14ncymq_dg3j1xf80000gn/T/d20190820-3742-5vwfym/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.4.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (7) Failed to connect to developers.facebook.com port 443: Operation timed out
