### ISSUE TITLE
Detox tests will not run on iOS 14.5 or 15.0 after upgrading to Expo 43

### ISSUE THREAD

**Issue by curtismgt** [expo/expo#15595]
### Summary

After upgrading to Expo 43 our Detox test suite will no longer run on iOS 14.5 or 15.0. **I have built a new bare RN app (`npx react-native init`) and Detox works perfectly**. However, if I build a new bare Expo app Detox fails with 'Signal 11'. This is related to [Detox Issue #3123](https://github.com/wix/Detox/issues/3123). From what I can tell this is due to something called "isa swizzling", which I don't understand and is above my pay-grade. It's almost definitely some sort of interaction between Detox and Expo. With the popularity of Detox for e2e tests and the popularity of the Expo SDK/libraries this seems like a fairly critical problem.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
  Expo CLI 5.0.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.11.08.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 30.0.2, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^8.3.0 => 8.5.1 
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.0
    Expo Workflow: bare
```

### Reproducible demo

1. Install Xcode 13.1 (comes with iOS 15 simulators)
2. Install iOS 14.4 simulators `Xcode->Preferences->Components->iOS 14.4 Simulator`
3. Run `expo init -t bare-minimum --npm --name testDetox`
4. Install Detox globally `npm install -g detox`
5. Install Detox and jest `npm install  --save-dev detox jest`
6. Run `detox init`
7. Replace `apps:ios` in `.detoxrc.json` with this: 
```
{
      "type": "ios.app",
      "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/testDetox.app",
      "build": "xcodebuild -workspace ios/testDetox.xcworkspace -scheme testDetox -configuration Release -sdk iphonesimulator -derivedDataPath ios/build | xcpretty"
}
```
8. Run `detox build --configuration ios`
9. Run `detox test --configuration ios`
10. **Tests fail with Signal 11**
11. Replace `devices:simulator` in `.detoxrc.json` with this:
```
{
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 11",
        "os": "iOS 14.4"
      }
}
```
12. Run `detox test --configuration ios`
13. Tests run properly (failing but fail for legitimate reasons)

**Comment by brentvatne** [comment]
seems unrelated to expo itself
