### ISSUE TITLE
[docs] broken link - how to build a mono repo is broken

### ISSUE THREAD

**Issue by mconnor** [expo/expo#15594]
### Summary

on [./docs/pages/build/setup.md](https://github.com/expo/expo/blob/master/docs/pages/build/setup.md)

the copy is:
_Is your project inside of a monorepo? Follow these instructions._

### Link to the related docs page

https://github.com/expo/expo/blob/master/docs/pages/build/setup.md

**Comment by brentvatne** [comment]
the link brings you here:

![Screen Shot 2021-12-16 at 6 33 51 PM](https://user-images.githubusercontent.com/90494/146479504-719cadb0-d5b3-4b71-b5c4-50fc3f113ef8.png)

this link works.

**Comment by brentvatne** [comment]
however, we should update these instructions and also point to our [new monorepo guide](https://docs.expo.dev/guides/monorepos/) cc @byCedric
