### ISSUE TITLE
tools-public not working because too old xdl dep

### ISSUE THREAD

**Issue by gre** [expo/expo#156]
`Uncaught TypeError: renderExpoKitPodspecAsync is not a function` when i try to `./generate-files-ios.sh` ( https://github.com/expo/expo/blob/335453f7681e0816b7d68fc3eb38a1ac5a54db5a/tools-public/generate-dynamic-macros.js#L19 )

it’s because in `node_modules/xdl/build/detach/IosPodsTools.js`, there is `renderExponentKitPodspecAsync` not `renderExpoKitPodspecAsync`

`“xdl”: “33.0.0"` is set in tools-public/package.json, it's too old to work I think.

actually even latest npm released 40.0.0 have the same issue, so maybe you need to bump xdl first?

I even tried to dep to `"github:expo/xdl"` but I get a `Error: Cannot find module 'xdl'`

**Comment by skevy** [comment]
cc @jesseruder

**Comment by gre** [comment]
also, maybe you should add a `prepublish: "npm run build"` in the **xdl** lib package.json so that a github dep works ;)

**Comment by jesseruder** [comment]
You can just run npm build in node_modules/xdl until we push the new version. We explicitly don't add that to the prepublish hook because we don't want all consumers of the library to have to run it.

**Comment by brentvatne** [comment]
@gre https://github.com/expo/expo-dev should make it a lot easier to work with this! let me know if you run into any issues with it :)

**Comment by Elijen** [comment]
@brentvatne Using a different repo does not solve the issue with the current one. Shouldn't this issue be still open? Or is the current repo deprecated?
