### ISSUE TITLE
[SDK44] reanimated 2 conditional rendering trouble on first start up

### ISSUE THREAD

**Issue by dpnick** [expo/expo#15600]
### Summary

I found a strange behavior while trying to use `react-native-reanimated` layout animation. As you can see in my demo bellow, I have a simple conditional rendering, at the component mount it should display a spinner for 3000ms and then a list of (transparent for demo purpose) items. However, on the first render after the 3000ms the spinner AND the list are visible.

If I reload the project everything works as expect. But as soon as I completely restart the app, this behavior happen.

I was able to reproduce this behavior in a fresh new app, I will include the steps bellow.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - /usr/local/bin/node
      npm: 7.15.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        Android NDK: 23.0.7344513-beta4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: next => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.1
    Expo Workflow: managed

### Reproducible demo

```
$ EXPO_BETA=1 expo init --npm
$ # Choose "blank (TypeScript)"
$ expo install react-native-reanimated react-native-screens
```

babel.config.js
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
```

App.tsx
```
import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import Animated, {
  FadeInUp,
  FadeOutDown,
  Layout,
} from 'react-native-reanimated';

const AnimatedView = Animated.createAnimatedComponent(View);

export default function App() {
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    const timeout = setTimeout(() => setIsLoading(false), 3000);
    return () => {
      clearTimeout(timeout);
    };
  }, []);

  return (
    <View style={styles.container}>
      {isLoading ? (
        <ActivityIndicator size='large' color='red' />
      ) : (
        <AnimatedView
          entering={FadeInUp}
          exiting={FadeOutDown}
          layout={Layout.springify()}
          style={styles.scrollContainer}
        >
          {[...Array(10).keys()].map((value) => (
            <View style={styles.row} key={value}>
              <Text>row n°{value}</Text>
            </View>
          ))}
        </AnimatedView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContainer: {
    flex: 1,
    width: '100%',
  },
  row: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    height: 50,
  },
});
```

**Comment by brentvatne** [comment]
hi there! this is best suited for https://github.com/software-mansion/react-native-reanimated/issues unless you have reason to believe this issue only occurs in expo go

**Comment by brentvatne** [comment]
i ran this code with `expo run:ios` which will compile the app and run it outside of expo go, and i confirmed that the behavior is the same - so this issue belongs on the react-native-reanimated repository

**Comment by dpnick** [comment]
Hi @brentvatne, thanks for your help, I will open an issue there!
