### ISSUE TITLE
[SDK44] Background Location Foreground service is killed with App

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#15604]
### Summary

I just discovered a strange issue with expo-location , i attached a mini project to demonstrate the issue .

if i start background task with foreground service and kill the app the task will take some time before it begins and for the foreground service to show and sometimes it doesn't even start .

But if i start background task and kill the app then open the app again and start it again and kill the app it will stick and doesn't dissapear . well the second behaviour is what i'm looking for but i want to only start it once cause that makes sense .

Steps to reproduce : 

1 - open the app .
2 - click the start location button .
3 - kill the app . ( the foreground service will stop along with the task )

4 - now open the app again .
5 - click the start location button .
6- kill the app . (the Foreground will remain actif along with the location task )

[testApp.zip](https://github.com/expo/expo/files/7731933/testApp.zip)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.1 environment info:
System:
OS: Windows 10 10.0.19042
Binaries:
Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 2020.3.0.0 AI-203.7717.56.2031.7583922
npmPackages:
babel-preset-expo: 9.0.1 => 9.0.1
expo: ^44.0.0 => 44.0.0
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.3 => 0.64.3
react-native-web: 0.17.1 => 0.17.1
Expo Workflow: managed

### Reproducible demo

[testApp.zip](https://github.com/expo/expo/files/7731933/testApp.zip)

**Comment by MarkusAbtion** [comment]
Hi @islamouzou 
Did you find the solution for this?
