### ISSUE TITLE
Expo Speech: How to pick a voice

### ISSUE THREAD

**Issue by bhakta0007** [expo/expo#1560]
### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Steps to Reproduce

I see the API has language option. However, the phone has multiple voices available for the same language. (e.g. https://github.com/ak1394/react-native-tts has this support and works on android/IOS). does the expo API have an option to list available voices and pick one?

(Write your steps here:)

1. 
2.
3.

### Expected Behavior

API should allow for choosing a voice

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by schazers** [comment]
Hi there! Please use our forums at https://forums.expo.io/ to ask questions about functionality. That way, everyone there can help answer you quickly, and everyone can benefit from searching for that same issue. 

If you ask there and are confident that the feature doesn't exist within Expo's SDK, please either create  a new feature request on Canny, or upvote the request one already there if it exists. https://expo.canny.io/feature-requests
