### ISSUE TITLE
[docs] SDK 44 expo-firebase-analytics has wrong bug (I think)

### ISSUE THREAD

**Issue by Aryk** [expo/expo#15601]
### Summary

Go here: https://github.com/expo/expo/blob/master/CHANGELOG.md#-breaking-changes-1

Deprecates setCurrentScreen and removes the native API calls to support the latest Firebase SDKs. (#4366 by @IjzerenHein)

4366 has nothing to do with Firebase, it's an Expo-Camera ticket.

### Link to the related docs page

https://github.com/expo/expo/blob/master/CHANGELOG.md#-breaking-changes-1

**Comment by brentvatne** [comment]
thanks https://github.com/expo/expo/commit/aed35e2058ef1cd24944a5f1cab235a9dc137494
