### ISSUE TITLE
eas build error, [android.manifest]: withAndroidManifestBaseMod: permission.includes is not a function

### ISSUE THREAD

**Issue by ParthNandaniya** [expo/expo#15610]
I run command `eas build --platform android --local`, it's giving build error. looks like there is no documentation for this.

can someone check please ?

`- Config syncing
✖ Config sync failed
[stderr] [13:49:34] [android.manifest]: withAndroidManifestBaseMod: permission.includes is not a function

[stderr] [13:49:34] TypeError: [android.manifest]: withAndroidManifestBaseMod: permission.includes is not a function
[stderr]     at /build/node_modules/@expo/config-plugins/src/android/Permissions.ts:98:21
[stderr]     at Array.map (<anonymous>)
[stderr]     at prefixAndroidPermissionsIfNecessary (/build/node_modules/@expo/config-plugins/src/android/Permissions.ts:97:22)
[stderr]     at setAndroidPermissions (/build/node_modules/@expo/config-plugins/src/android/Permissions.ts:114:31)
[stderr]     at /build/node_modules/@expo/config-plugins/src/android/Permissions.ts:21:31
[stderr]     at action (/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
[stderr]     at interceptingMod (/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
[stderr]     at action (/build/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27)
[stderr]     at interceptingMod (/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at evalModsAsync (/build/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
[stderr]     at compileModsAsync (/build/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
[stderr]     at configureManagedProjectAsync (/build/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
[stderr]     at prebuildAsync (/build/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:90:21)
[stderr]     at actionAsync (/build/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:34:3)
node exited with non-zero code: 1`

**Comment by Svarto** [comment]
@ParthNandaniya did you find a solution to this?
