### ISSUE TITLE
SDK 44 dev client build failing: Execution failed for task ':expo-updates:kaptDebugKotlin'.

### ISSUE THREAD

**Issue by haibert** [expo/expo#15620]
### Summary

Upgraded project from 43 to 44, attempting to rebuild a dev-client for android after update and I am getting the following error:  

[stderr] > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
[stderr] > java.lang.reflect.InvocationTargetException (no error message)

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

        "expo-dev-client": "~0.7.2",
        "expo-updates": "~0.11.2",
        "expo": "^44.0.0",
        "expo-app-loading": "~1.3.0",
        "expo-application": "~4.0.1",
        "expo-av": "~10.2.0",
        "expo-barcode-scanner": "~11.2.0",
        "expo-camera": "~12.1.0",
        "expo-constants": "~13.0.0",
        "expo-device": "~4.1.0",
        "expo-file-system": "~13.1.0",
        "expo-font": "~10.0.4",
        "expo-haptics": "~11.1.0",
        "expo-image-manipulator": "~10.2.0",
        "expo-image-picker": "~12.0.1",
        "expo-linear-gradient": "~11.0.0",
        "expo-media-library": "~14.0.0",
        "expo-notifications": "~0.14.0",
        "expo-sqlite": "~10.1.0",
        "expo-status-bar": "~1.2.0",
        "expo-task-manager": "~10.1.0",

### Environment

  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.10.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.1
    Expo Workflow: managed

### Reproducible demo

I cannot provide a reproducible demo at the moment, i will try to create one in the next day or two

### Stacktrace (if a crash is involved)

FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':expo-updates:kaptDebugKotlin'.
[stderr] > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
[stderr]    > java.lang.reflect.InvocationTargetException (no error message)
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by RohovDmytro** [comment]
@haibert , did you manage to fix the issue?..

**Comment by haibert** [comment]
> @haibert , did you manage to fix the issue?..

I downgraded expo updates back to 10.15 or what ever the sdk 43 version was.
