### ISSUE TITLE
Cherry pick firebase js fix to sdk 26

### ISSUE THREAD

**Issue by harisvsulaiman** [expo/expo#1562]
There was an issue with js sdk for firebase Firestore not working with expo. 
https://github.com/firebase/firebase-js-sdk/issues/283

It has now been solved. 
https://github.com/facebook/react-native/commit/d52569c4a1b6bd19792e4bda23e3a8c3ac4ad8df

Can you cherry pick that into the next sdk?

**Comment by schazers** [comment]
Thanks for the report! I've introduced @ide as he works on the react native releases.

**Comment by ide** [comment]
That commit is in RN 0.55 and we've already started processing RN Android for SDK 26 so most likely that commit will go out with SDK 27, but there is a chance it will go out with SDK 26 if we need to rebuild it for a critical reason.

In general, the best way to get a feature like this into Expo is to land it upstream in React Native in a final release.

**Comment by ide** [comment]
Update: we think we can include this with SDK 26. We don't have an ETA or roadmap for SDK 26 yet, and will include notes about the update on blog.expo.io.
