### ISSUE TITLE
[SDK44] EAS Execution failed for task ':expo-image-picker:compileReleaseKotlin'

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#15629]
### Summary

I'm getting an EAS BUILD ERROR WITH expo-image-picker

here are the logs `[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (25, 36): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (131, 39): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (133, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (138, 71): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (140, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (193, 7): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (195, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (200, 39): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (202, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (325, 8): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (327, 9): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (376, 8): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (378, 9): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (381, 46): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (383, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (4, 36): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (40, 9): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (42, 9): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt: (11, 36): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt: (32, 39): Unresolved reference: ifNull
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':expo-image-picker:compileReleaseKotlin'.
[stderr] > Compilation error. See log for more details
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 7m 16s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
470 actionable tasks: 470 executed
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^44.0.0 => 44.0.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

any project with "expo-image-picker": "~12.0.1",

**Comment by islamouzou** [comment]
Happens with expo-updates as well

**Comment by pheuter** [comment]
@islamouzou I was seeing a similar issue, what made you close it?

**Comment by islamouzou** [comment]
@pheuter thanks for replying , i just closed the wrong issue , my bad . do you have the same problem with  I expo-image-picker ??

**Comment by pheuter** [comment]
@islamouzou Yes, I have the same problem when building Expo SDK v44 in EAS. I also have #15635 as an issue but it appears to have been closed prematurely.

**Comment by islamouzou** [comment]
@pheuter  do you know how to use patch-package ?

**Comment by pheuter** [comment]
Don't think so.

**Comment by islamouzou** [comment]
@pheuter Okay , so i suggest that you change the version of expo-image-picker to "expo-image-picker": "11.0.1" in your package.json that should fix your problem for now .

**Comment by pheuter** [comment]
Right, so don't use the versions recommended automatically by expo when u upgrade to v44.

**Comment by islamouzou** [comment]
Yes , and If you want to patch the package for the last versionof expo-image-picker yourself you have to install" patch-package" in your project 

yarn add patch-package postinstall-postinstall

then add this line in your package.json in the script section  "postinstall": "patch-package" , like this :

 "scripts": {
+  "postinstall": "patch-package"
 } 


then you need to modify the expo-image-picker in node-modules folder inside your project ,
Go to this file 
/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt

Replace this line 
`import expo.modules.core.utilities.ifNull`
With this 
`+import expo.modules.core.utilities.KotlinUtilities.ifNull` 

Now execute this command inside your project : 

`npx patch-package expo-image-picker` 

You'll notice a new folder called patches inside your project , you're good to go .

now build with eas and it should be solved .

**Comment by pheuter** [comment]
@islamouzou How was this resolved? I'm still seeing the issue on EAS build servers using the version of the library recommended by `expo upgrade` for SDK v44.

**Comment by islamouzou** [comment]
@pheuter 

i don't have this problem anymore , i don't know how it got fixed  , can you show me the build logs ? (gradle phase )

**Comment by pheuter** [comment]
```
 Task :expo-image-loader:javaPreCompileRelease
> Task :expo-image-loader:compileReleaseJavaWithJavac
> Task :expo-image-loader:bundleLibCompileToJarRelease
> Task :expo-image-manipulator:generateReleaseBuildConfig
> Task :expo-image-manipulator:compileReleaseKotlin
> Task :expo-image-manipulator:javaPreCompileRelease
> Task :expo-image-manipulator:compileReleaseJavaWithJavac
> Task :expo-image-manipulator:bundleLibCompileToJarRelease
> Task :expo-image-picker:generateReleaseBuildConfig
> Task :expo-image-picker:compileReleaseKotlin FAILED
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (25, 36): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (131, 39): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (133, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (138, 71): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (140, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (193, 7): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (195, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (200, 39): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (202, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (325, 8): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (327, 9): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (376, 8): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (378, 9): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (381, 46): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (383, 7): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (4, 36): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (40, 9): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (42, 9): 'return' is not allowed here
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt: (11, 36): Unresolved reference: ifNull
[stderr] e: /root/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt: (32, 39): Unresolved reference: ifNull
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':expo-image-picker:compileReleaseKotlin'.
[stderr] > Compilation error. See log for more details
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 7m 9s
```

**Comment by islamouzou** [comment]
@pheuter  can you try the patch-package solution , you didn't understand how to do it ?

**Comment by pheuter** [comment]
@islamouzou I understand it, I just think that it is exactly what the name suggests, a patch, and not a proper fix. If it works as a temporary bandage that's great, but that doesn't mean this issue is properly resolved.

**Comment by islamouzou** [comment]
@pheuter Not really , it's a proper fix but just for you , if you see the logs you'll notice the error is 

`Unresolved reference: ifNull` , when i checked to see where it came from , i found that instead of importing ifNull from

**Comment by pheuter** [comment]
A proper fix is if the latest published version of `expo-image-picker` that is automatically installed when you run `expo upgrade` to Expo SDK v44 works out of the box. I don't see how you can resolve this issue if the solution you deployed is to manually edit code inside of `node_modules`.

**Comment by islamouzou** [comment]
@pheuter i know what you mean , but the important thing is to get things working . i closed this because it works fine for me now without the patch , i thought it's been fixed . but apparently no .

For now you can use expo build , or use the patch , and since this isn't fixed for everyone i'll reopen the issue .

**Comment by pheuter** [comment]
Thanks for clarifying your reasoning, makes sense 👍

**Comment by pheuter** [comment]
@islamouzou Thanks to @brentvatne's help I believe I was able to resolve this issue by removing the `@unimodules/core` dependency that was still hanging around in my codebase. It was affecting not just `expo-image-picker` but other dependencies as well.

**Comment by imhazige** [comment]
Why close this issue, I encounter the same on EAS build. my sdk version is 44, 
expo-image-picker is ~12.0.1

**Comment by Thix-Bilz** [comment]
I encounter the same error
Execution failed for task ':expo-image-picker:compileReleaseKotlin'.
expo-image-picker is ~14.3.2 with "expo": "^49.0.0"

**Comment by brentvatne** [comment]
hi there. please create a new issue with a minimal reproducible example @Thix-Bilz. thanks!
