### ISSUE TITLE
EAS build error for `expo-localization`

### ISSUE THREAD

**Issue by pheuter** [expo/expo#15635]
### Summary

```
 Compiling @react-native-community/masked-view Pods/RNCMaskedView » RNCMaskedView-dummy.m
› Compiling @unimodules/core Pods/UMCore » UMErrorCodes.m
› Compiling @unimodules/core Pods/UMCore » UMCore-dummy.m
› Packaging @react-native-community/masked-view Pods/RNCMaskedView » libRNCMaskedView.a
› Compiling expo-localization Pods/ExpoLocalization » LocalizationModule.swift

❌  (node_modules/expo-localization/ios/LocalizationModule.swift:14:5)

  12 |     }
  13 | 
> 14 |     function("getLocalizationAsync") {
     |     ^ cannot find 'function' in scope
  15 |       return Self.getCurrentLocalization()
  16 |     }
  17 |   }
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLocalization' from project 'Pods')
▸ 	CompileSwift normal arm64 /Users/expo/workingdir/build/node_modules/expo-localization/ios/LocalizationModule.swift (in target 'ExpoLocalization' from project 'Pods')
▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLinearGradient' from project 'Pods')
▸ (3 failures)
** ARCHIVE FAILED **
The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLocalization' from project 'Pods')
	CompileSwift normal arm64 /Users/expo/workingdir/build/node_modules/expo-localization/ios/LocalizationModule.swift (in target 'ExpoLocalization' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLinearGradient' from project 'Pods')
(3 failures)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.185.1                 |
| sdk         | iPhoneOS15.0.sdk        |
+-------------+-------------------------+
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0

### Environment

```
Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.2.0 - ~/.nvm/versions/node/v17.2.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v17.2.0/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v17.2.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

Any project with `"expo-localization": "~12.0.0"`

**Comment by brentvatne** [comment]
https://github.com/brentvatne/pheuter

does not repro. please share a proper reproducible example in a new issue when you have a chance to make one

**Comment by pheuter** [comment]
@brentvatne Help me understand the situation. I have a proprietary codebase for my company's app that's been building fine on Expo SDK v43, and when the only changes I make are running `expo upgrade` to upgrade to v44, the builds fails _on EAS_ with the error above.

Given all this information, you think it's prudent to close this issue because I haven't spent enough time "narrowing down the root cause of the issue" specific to the expo-localization library during the v44 upgrade? Again without any code changes to the actual app?

As a paying customer on the EAS Production plan, this leaves an extra sour taste in my mouth.

**Comment by brentvatne** [comment]
@pheuter - the priority here is to keep an issues list that is actionable. closing issues without a reproducible example is a mechanism that allows us to guard our time and ensure it's spent on the most important issues, and that the time we spent is directed entirely towards fixing the issue.

you can think about it like this: if 10 people open one issue each and only 9 of those are real bugs, then if we had to try to reproduce all of those on our own and we timeboxed reproducing the issues to 15 minutes, that would take 2.5 hours and we would only have one actionable issue out of it. we wouldn't have even started fixing it yet at that point.

**Comment by pheuter** [comment]
@brentvatne The problem here is you're not engaging with the content of my issue beyond the surface level. If you did, you'd notice that the issue can only be reproduced on the EAS build servers during native XCode compilation of a dependency that Expo controls: `expo-localization`. I'd love to help you help me here, but I have no clue what to do given the nature of the issue, and I don't see anything on https://expo.fyi/manual-debugging that's relevant to the EAS build issue I'm articulating here.

**Comment by brentvatne** [comment]
@pheuter - i understand that you are frustrated, sorry about that. the doc i linked you to helps you to determine what the root cause of an issue is. it's important as developers that we learn how to narrow down root causes of issues, because that is often the first step to fixing it. that is all i am asking for here.

**Comment by pheuter** [comment]
> it's important as developers that we learn how to narrow down root causes of issues, because that is often the first step to fixing it. that is all i am asking for here.

@brentvatne I completely agree with you on this, the frustrating part for me is in this particular case, the nature of the issue eludes any clear debugability in my judgement, which can be flawed. I appreciate your patience in the meantime, not my intention to be difficult for the sake of being difficult.

**Comment by brentvatne** [comment]
my thought process in this issue was: i saw your reproducible demo steps, i tried them, they did not reproduce for me. so i stopped there because i lacked any more information on how to proceed.

you have more information than me -- you have your project where this reproduces on hand. so you could try removing all proprietary code, see if it reproduces. then try removing modules large chunks at a time and see again. if you have pared it down to a "hello world" app with minimal dependencies and it still reproduces, that's great to know too and you should share that project. this is the process i'd hope for you to follow.

**Comment by pheuter** [comment]
@brentvatne Fair enough, a lesson I'll personally take away from this is to be better about creating reproducible repos, even if the source of the issue isn't easily reproducible using `expo r` or local dev clients.

> i saw your reproducible demo steps, i tried them, they did not reproduce for me. so i stopped there because i lacked any more information on how to proceed.

One ask I have in return is to maybe try to reproduce by actually submitting project with latest `expo-localization` dep to eas build and seeing if it failed during the Xcode build there, which is what my issue described from the beginning. If you have in fact done that and it worked, then it's all on me, that wasn't clear to me and I apologize for any misunderstanding.
