### ISSUE TITLE
Duplicate interface definition for class 'RCTModuleRegistry'

### ISSUE THREAD

**Issue by Bardiamist** [expo/expo#15649]
### Summary

I can't build project after update expo from 43.0.4 to 44.0.0.

Error mesage from React-Core and [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values)
```
/Users/bardiamist/Documents/proj/proj-mobile/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h:424:1: Duplicate interface definition for class 'RCTModuleRegistry'
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.2.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.4 - /usr/local/bin/npm
      Watchman: 2021.12.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2
        System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.0 => 44.0.0 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.4 => 0.66.4 
    npmGlobalPackages:
      expo-cli: 5.0.1
    Expo Workflow: bare

### Reproducible demo

https://github.com/Bardiamist/expo_random

**Comment by renchap** [comment]
I am hitting the same issue.

Can it be related to https://github.com/expo/expo/pull/15626 ? It seems it fixed a similar issue, but in expo-random (which is not used by my project)

**Comment by Bardiamist** [comment]
https://github.com/LinusU/react-native-get-random-values/pull/33

**Comment by Bardiamist** [comment]
Yea, conditional imports is the reason. https://github.com/LinusU/react-native-get-random-values/pull/33 resolves it.
