### ISSUE TITLE
Contact getContactByIdAsync API not working

### ISSUE THREAD

**Issue by jurosh** [expo/expo#1564]
### Environment

Environment:
  OS: Windows 10
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.7.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: ^16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/jurosh-cbe5f27b-45bd-42dc-ab30-0a113d661cc3.tar.gz

Tested targets:

Android (MIUI 9)
VS Emulator for Anroid

### Steps to Reproduce

1. Get contacts with `Expo.Contacts.getContactsAsync(options)` so we will know `contact.id`
2. Try to get single contact with `Expo.Contacts.getContactByIdAsync(options)`

```
await Expo.Contacts.getContactByIdAsync({
    fields: [],
    id: 'SOME_CONTACT_ID'
  });
```

### Expected Behavior

Should return single contact.

### Actual Behavior

```
Uncaught Error: no such column: contact_id (code 1), whilte compiling: SELECT sort_key, photo_uri, nickname, send_to,......
Fatal Error
```

![screenshot_2018-03-21-21-42-38-970_host exp exponent](https://user-images.githubusercontent.com/1630137/37738866-a0d5ca18-2d58-11e8-86d3-97e2ab705bbc.png)

### Reproducible Demo

Contact API is not working in snack.expo - not even getting of all contacts. So cannot reproduce there. :/

**Comment by schazers** [comment]
Hi Jurosh, I've made a two example Snacks which should confirm and demonstrate how to use the APIs. Since it appears to be working, I've put it onto our forums so others may benefit in case they have a similar problem:

https://forums.expo.io/t/getcontactbyidasync-usage/8055

I'm closing this issue here - please follow up on the forums with questions, thx!

**Comment by jurosh** [comment]
Thanks @schazers yea looks like I must made some error in Snack :o hm..
But when I copy your code to real device it's failing with same reported error.

First call returns ID (1), but getting single contact failed.

**Comment by schazers** [comment]
Ah, I'm sorry, I made a silly mistake - I tested on an iOS device, not an Android one. It looks like there may be an bug - thank you for the report! We'll look into it.

@esamelson - are you the right person to report this to? If not, would you mind forwarding to whomever is?

**Comment by jurosh** [comment]
Hack 👍 I didn't saw that too... mee also guilty, but it's just morning.. that's fine :D

**Comment by aalices** [comment]
Hi, this was fixed some time ago but looks like the fix was not included in SDK 25 🤔 hope to get the change available very soon!

**Comment by esamelson** [comment]
Hi @jurosh - sorry about this. Next time we do an Android release, it will include this fix for SDK 25. We don't always announce minor releases, so I'll do my best to keep you posted!
