### ISSUE TITLE
ReactCommon/ReactCommon/TurboModuleUtils.h:13:10: 'folly/Optional.h' file not found

### ISSUE THREAD

**Issue by aaryavrate** [expo/expo#15644]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by aaryavrate** [comment]
.

**Comment by jordangrant** [comment]
How to solve this?

**Comment by Cado21** [comment]
yo.. there's no solution why it's closed?

**Comment by raid5** [comment]
Dupe of https://github.com/expo/expo/issues/16021 with a bit more context, but still no solution besides downgrading to SDK 42.
