### ISSUE TITLE
[docs] runtimeVersion format is never explicitly defined

### ISSUE THREAD

**Issue by apiel51** [expo/expo#15647]
### Summary

In the `runtimeVersion` field description on the app.json reference page, the format of the field is never outlined despite the [Runtime versions and updates](https://docs.expo.dev/eas-update/runtime-versions/#custom--runtimeversion) and [Runtime Versions](https://docs.expo.dev/distribution/runtime-versions/) pages referencing the format definition. Would be happy to create a PR, but not sure what the supported format is :/

### Link to the related docs page

https://docs.expo.dev/versions/latest/config/app/#runtimeversion

**Comment by zlanich** [comment]
This is still not solved, as far as I can see. The page linked to for the format does not contain the format.
