### ISSUE TITLE
[SDK44][iOS] expo-updates: Unknown receiver 'EXUpdatesDevLauncherController'

### ISSUE THREAD

**Issue by hirbod** [expo/expo#15645]
### Summary

I've upgraded my project to SDK44. I followed all the instructions to setup expo-modules and installed `expo-updates`.
When I try to build my custom dev client, the build fails with:

```
Unknown receiver 'EXUpdatesDevLauncherController', did you mean 'EXDevLauncherController'?
Replace -äEXUpdatesDevLauncherController' with 'ExDevLauncherController'
```

Packages are installed, pods have been installed as well.

I am not sure if this is a "managed project" or a "bare project" (I mean, since I am running `expo prebuild`, I do have the ios/ and android/ folder, but I only use config-plugins etc.) and XCode only to build my dev client.

<img width="1160" alt="Bildschirmfoto 2021-12-19 um 08 02 46" src="https://user-images.githubusercontent.com/504909/146666773-e15d60ec-ffc2-4c86-af7f-e2b7430b9fe1.png">

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

```
    "expo": "^44.0.0",
    "expo-app-loading": "~1.3.0",
    "expo-application": "~4.0.1",
    "expo-blur": "~11.0.0",
    "expo-constants": "~13.0.0",
    "expo-dev-client": "~0.7.2",
    "expo-device": "~4.1.0",
    "expo-font": "~10.0.4",
    "expo-haptics": "~11.1.0",
    "expo-intent-launcher": "~10.1.0",
    "expo-keep-awake": "~10.0.1",
    "expo-linking": "~3.0.0",
    "expo-modules-core": "~0.6.3",
    "expo-notifications": "~0.14.0",
    "expo-splash-screen": "~0.14.0",
    "expo-status-bar": "~1.2.0",
    "expo-system-ui": "~1.1.0",
    "expo-updates": "^0.11.2",
```

### Environment

```  
Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.1
    Expo Workflow: bare
```

### Reproducible demo

-

**Comment by jwoo92** [comment]
@Hirbod Are you importing `EXUpdatesDevLauncherController` at the top of your `AppDelegate.m` file like this?

```objective-c
#import "AppDelegate.h"

#if defined(EX_DEV_MENU_ENABLED)
@import EXDevMenu;
#endif

#if defined(EX_DEV_LAUNCHER_ENABLED)
#include <EXDevLauncher/EXDevLauncherController.h>
#import <EXUpdates/EXUpdatesDevLauncherController.h>
#endif

#import <React/RCTBridge.h>
...
```

**Comment by Hirbod** [comment]
@jwoo92 no I didn’t as I am on the managed workflow with a custom dev client. As I am not on the bare workflow, I don’t touch any native files (unless a config plug-in does it for me).

**Comment by jeffreyvanhees** [comment]
Exactly the same error here. Local build and EAS build as well. Following.

**Comment by hirbod** [comment]
Has anybody a clue how to fix this? I tried to install sentry and ended up with this error message again..

**Comment by hirbod** [comment]
@jwoo92 it is indeed that missing import.
This should be added there automatically but it is not happening. For now I'll most likely have to write my own config plugin to patch this one here...

```
#import <EXUpdates/EXUpdatesDevLauncherController.h>
```

**Comment by hirbod** [comment]
I've deleted everything one more time and added "expo-updates" to the custom dev client plugins and now it looks like its working!

**Comment by fguitton** [comment]
> added "expo-updates" to the custom dev client plugins

Hello, could you please elaborate on this and tell us about how you went about solving this issue ?
We have been having this `expo-updates` issue creeping in for the past few weeks and it's really not giving up.

Thank you for any pointer 🌴

**Comment by hirbod** [comment]
@fguitton I've added `expo-updates` into app.config.ts (under expo.plugins), made sure I have the newest version of expo-updates, expo-dev-client, expo-modules, expo-application and expo-constants.

After that I ran `expo prebuild --clean` and that missing line `#import <EXUpdates/EXUpdatesDevLauncherController.h>` wasn't missing anymore and it worked out for me.
