### ISSUE TITLE
ld: 12 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by aaryavrate** [expo/expo#15648]
### Summary

Duplicate symbols in Xcode build for Expo ejected repo.  

duplicate symbol '_EXCanAskAgain' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_EXExpiresKey' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_EXGrantedKey' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_EXPermissionExpiresNever' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_EXStatusKey' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_OBJC_CLASS_$_EXPermissionsService' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_OBJC_IVAR_$_EXPermissionsService._moduleRegistry' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_OBJC_IVAR_$_EXPermissionsService._requesters' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_OBJC_IVAR_$_EXPermissionsService._requestersByClass' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_OBJC_METACLASS_$_EXPermissionsService' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXPermissionsService.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXPermissionsService.o)
duplicate symbol '_OBJC_CLASS_$_EXReactNativeUserNotificationCenterProxy' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXReactNativeUserNotificationCenterProxy.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXReactNativeUserNotificationCenterProxy.o)
duplicate symbol '_OBJC_METACLASS_$_EXReactNativeUserNotificationCenterProxy' in:
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/ExpoModulesCore/libExpoModulesCore.a(EXReactNativeUserNotificationCenterProxy.o)
    /Users/prabhatsingh/Library/Developer/Xcode/DerivedData/mirrorhellodrcom-hhsnjfwejyphcvavkwwceasjcnjg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter/UMReactNativeAdapter.framework/UMReactNativeAdapter(EXReactNativeUserNotificationCenterProxy.o)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.1
    Expo Workflow: bare

### Reproducible demo

Try to build after expo eject

https://github.com/creativetimofficial/ct-material-kit-pro-react-native

**Comment by anisamh18** [comment]
did find a solution ?

**Comment by doranteseduardo** [comment]
Same issue here on fresh project.

**Comment by lukasa1993** [comment]
any love for this? seems deal breaker

**Comment by vladivanciu** [comment]
Try to fix this for 5 days.... Any solution ?

**Comment by phasooni** [comment]
Same here - I am getting the exact same result when ejecting from expo and trying to build the app

**Comment by aaryavrate** [comment]
Once ejected, make sure that expo is upgraded to latest. Remove unimodules from every corner of your project.

**Comment by stuckj** [comment]
I hit this as well. Make sure to check in your `yarn.lock` file (or `package-lock.json` if you're using npm). Search for `@unimodules`. I had `@unimodules/core` and `@unimodules/react-native-adapter` installed via optional dependencies from a library we directly depended on. Weirdly, this didn't affect us while the app was in a monorepo. We migrated it to its own repository using the git `filter-repo` plugin and we started hitting the problem for iOS only (with the exact same yarn config. Weird. :-P I updated the dependency and it removed the @unimodule libraries from `yarn.lock` which fixed it for us. Also had to update to the latest version of `@expo/match-media` as `0.1.0` wanted the `@unimodules/core` library still. `0.3.0` worked though.

**Comment by xcdincay** [comment]
> Same issue here on fresh project.
> 
> Update: Be sure that, if you are on SDK 44, you have not installed react-native-unimodules

Did i have to install react-native-unimodules or not ?

**Comment by hssdiv** [comment]
Had same issue after upgrading old expo app to sdk-43 and trying to eas build

After I removed 'react-native-unimodules' I needed to update multiple libraries that had unimodules dependencies, I found them through searching .lock file like @stuckj said
