### ISSUE TITLE
[SDK44][Android] App not opening via Expo Go

### ISSUE THREAD

**Issue by thedoublejay** [expo/expo#15650]
### Summary

When running locally, it works on iOS but on Android (Samsung devices, Android 12 and Android 10), it's stucked on white screen after Splash screen. Using latest Expo Go. It was working well with SDK43. Tried viewing logs via `adb logcat`, found these exceptions:

```
unknown:ReactContextBaseJavaModule: Unhandled SoftException
unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
unknown:ReactContextBaseJavaModule:    at abi44_0_0.com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
unknown:ReactContextBaseJavaModule:    at abi44_0_0.com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:1)
unknown:ReactContextBaseJavaModule:    at abi44_0_0.com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:1)
unknown:ReactContextBaseJavaModule:    at abi44_0_0.com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:7)
unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:1)
unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:4)
unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:4)
unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:2)
unknown:ReactContextBaseJavaModule:    at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:7)
unknown:ReactContextBaseJavaModule:    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:3)
unknown:ReactContextBaseJavaModule:    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
unknown:ReactContextBaseJavaModule:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
unknown:ReactContextBaseJavaModule:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
unknown:ReactContextBaseJavaModule:    at java.lang.Thread.run(Thread.java:920)
```

and

```
unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi44_0_0.com.facebook.react.views.picker.ReactDialogPickerManager
unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi44_0_0.com.facebook.react.uimanager.LayoutShadowNode
unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi44_0_0.com.facebook.react.views.drawer.ReactDrawerLayoutManager
unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi44_0_0.com.facebook.react.views.picker.ReactDropdownPickerManager
unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi44_0_0.com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
unknown:ViewManagerPropertyUpdater: Could not find generated setter for class abi44_0_0.com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.1 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 7.16.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      @expo/metro-config: 0.3.4 => 0.3.4
      @expo/webpack-config: ~0.16.2 => 0.16.14
      expo: ^44.0.0 => 44.0.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

1. Clone [branch](https://github.com/DeFiCh/wallet/tree/thedoublejay/bump_expo)
2. Run `npm ci` on root directory
3. Run project `expo start --clear`
4. Scan QR via Expo Go - Android
5. After splash screen, stucked on white screen

**Comment by nata-sch-21** [comment]
I have a similar issue. the app is tucked on a splash screen. SplashScreen.hideAsync() doesn't work

**Comment by thedoublejay** [comment]
Ok managed to fix the issue. Need to add flex display on the `GestureHandlerRootView` for it to work.

**Comment by superyarik** [comment]
@thedoublejay hi, can you explain your fix? have same error, have "react-navigation-drawer": "^2.7.0", how to fix it?

**Comment by thedoublejay** [comment]
@superyarik For me, I just added some styling on the `GestureHandlerRootView`. Not sure if we have the same issue
