### ISSUE TITLE
[iOS] On SDK 43 property 'reactDelegate' not found on object of type 'AppDelegate' won't Build

### ISSUE THREAD

**Issue by musubipapi** [expo/expo#15668]
### Summary

Running bare workflow with SDK 43 results in the following error:
 
`Property 'reactDelegate' not found on object of type 'AppDelegate *'`

![image](https://user-images.githubusercontent.com/24968343/146872700-64fbf751-9cab-4de7-9846-477cca11ea7c.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 32
        Build Tools: 29.0.2, 30.0.2
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=43.0.0-* <44.0.0 => 43.0.4 
      react: 17.0.2 => 17.0.2 
      react-native: ^0.66.1 => 0.66.4 
    npmGlobalPackages:
      expo-cli: 5.0.1
    Expo Workflow: bare

### Reproducible demo

npx install-expo-modules -s 43.0.0
Build App

**Comment by lehaidangdev** [comment]
In AppDelegate.h

Change 

`@interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate>
`
to
`@interface AppDelegate : EXAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate>
`

**Comment by Kudo** [comment]
@musubipapi the `reactDelegate` is for SDK 44. i tested with the `npx install-expo-modules -s 43.0.0` command on a react-native 0.66 project, that will not modify the project code for `self.reactDelegate`. can you double check for that?

**Comment by musubipapi** [comment]
yup it works now -- thank you!

**Comment by Kudo** [comment]
thanks for the confirmation. i'm going to close this issue. if there's any other problems, please open new issue.

**Comment by Kailash-MAF** [comment]
Working after this change.
Thanks

**Comment by Kailash-MAF** [comment]
> In AppDelegate.h
> 
> Change
> 
> `@interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate> ` to `@interface AppDelegate : EXAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate> `

Working after this change
Thanks
