### ISSUE TITLE
[SDK43][iOS][expo-media-library] Asset uri is being returned as a PHAsset which causes issues sending it through FormData

### ISSUE THREAD

**Issue by PedroRestrepo** [expo/expo#15664]
### Summary

Previous on SDK42, when we were getting the assets through `MediaLibrary.getAssetsAsync`, we would get the `uri` in the format `assets-library://asset/asset.<FORMAT>?id=<ID>`. That worker great as we are using to send those images to our backend for processing through `FormData`.

Since upgrading to SDK43, we noticed that now the `uri`s are being returning as `ph://<ID>`. This currently causes issues when we try to send it to our backend:
`No suitable URL request handler found for ph-upload://<ID>`

<img  height="500" src="https://user-images.githubusercontent.com/7490699/146830537-60e14ad0-6565-4306-afcc-34892eb2bc5e.png" />

Currently the expo documentation for the [`Asset`](https://docs.expo.dev/versions/latest/sdk/media-library/#asset), mentions that it should be in the format `asset://` on iOS. We did not see any mentions of breaking changed in the [release documentation](https://blog.expo.dev/expo-sdk-43-aa9b3c7d5541)

We have tried the following things to find a workaround:
- Manually generate the asset url: didnt give any errors, but the image had no content
- Getting the local uri through `MediaLibrary.getAssetInfoAsync`: same issue
- Getting the uri through the `FileSystem.getInfoAsync`: was just getting a blank uri even though it acknowledged that the image exists
```json
  {
    "exists": true,
    "isDirectory": false,
    "modificationTime": 1639337174.423153,
    "uri": null,
  },
```

The only similar issues that I have found are:
- https://github.com/react-native-cameraroll/react-native-cameraroll/issues/52
- https://stackoverflow.com/questions/70337776/expo-sdk-43-no-suitable-url-request-handler-found-for-ph-upload

This seems like a bug or change in behavior of `getAssetsAsync`. Please advice if there is something we are missing when getting the assets or if there is a valid way to transform iOS `PHAssets` to something we can send to our backend for processing.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 5.0.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 12.22.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      babel-preset-expo: 8.5.1 => 8.5.1
      expo: ^43.0.0 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

Snack with the issue reproduce: https://snack.expo.dev/@pedrorestrepo/43---expo-media-library-ios-issue

If you want to see what is the output for Expo 42, feel free to change the Expo version in the bottom right corner or use this snack: https://snack.expo.dev/@pedrorestrepo/42---expo-media-library-ios-issue

**Comment by Daleth50** [comment]
i've face a similar issue, fixed using [getAssetInfoAsync](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibrarygetassetsasyncassetsoptions) to get the localUri.

**Comment by michaeltaii** [comment]
I faced the same issue too, getAssetInfoAsync doesn't help

**Comment by nakedgun** [comment]
Same issue updating to **SDK 44**. However, using `getAssetInfoAsync()` and `localUri` does work - at least on iOS 15 and Android 12. Have not tested other OS versions.

**Comment by michaeltaii** [comment]
> Same issue updating to **SDK 44**. However, using `getAssetInfoAsync()` and `localUri` does work - at least on iOS 15 and Android 12. Have not tested other OS versions.

For iOS are you running it on physical device or simulator?

**Comment by nakedgun** [comment]
> > Same issue updating to **SDK 44**. However, using `getAssetInfoAsync()` and `localUri` does work - at least on iOS 15 and Android 12. Have not tested other OS versions.
> 
> For iOS are you running it on physical device or simulator? Cause this issue doesn't seem to appear on Android but on iOS only for my case

It's an iOS only issue, caused by this commit: https://github.com/expo/expo/pull/14173 (SDK 43). It works fine for me on a simulator (iOS 15) and physical devices (iOS 15 and iOS 12), but only using `getAssetInfoAsync()` and `localUri` (which doesn't return the new `ph://*` scheme).

This change was listed in the [changelog for SDK 43](https://github.com/expo/expo/blob/dae2841391388ede01694872a21714a9824e3b47/CHANGELOG.md?plain=1#L769), but not under breaking changes, which I guess it should be. The [docs](https://docs.expo.dev/versions/latest/sdk/media-library/#asset) haven't been updated either - they still reference iOS returning `assets://*` rather than `ph://*`. 

Maybe @ajsmth can chime in for what the best practices are on handling `ph://` assets for file uploads like this. Then we should probably update the readme and docs accordingly, since this is a fairly common use case for developers to handle.

**Comment by michaeltaii** [comment]
> > > Same issue updating to **SDK 44**. However, using `getAssetInfoAsync()` and `localUri` does work - at least on iOS 15 and Android 12. Have not tested other OS versions.
> > 
> > 
> > For iOS are you running it on physical device or simulator? Cause this issue doesn't seem to appear on Android but on iOS only for my case
> 
> It's an iOS only issue, caused by this commit: #14173 (SDK 43). It works fine for me on a simulator (iOS 15) and physical devices (iOS 15 and iOS 12), but only using `getAssetInfoAsync()` and `localUri` (which doesn't return the new `ph://*` scheme).
> 
> This change was listed in the [changelog for SDK 43](https://github.com/expo/expo/blob/dae2841391388ede01694872a21714a9824e3b47/CHANGELOG.md?plain=1#L769), but not under breaking changes, which I guess it should be. The [docs](https://docs.expo.dev/versions/latest/sdk/media-library/#asset) haven't been updated either - they still reference iOS returning `assets://*` rather than `ph://*`.
> 
> Maybe @ajsmth can chime in for what the best practices are on handling `ph://` assets for file uploads like this. Then we should probably update the changelog and docs accordingly, since this is a fairly common use case for developers to handle.

This works. Thanks a lot!

**Comment by DLawla** [comment]
@ajsmth, regarding this stale issue, do we have an expo-recommended way of dealing with `ph://` assets for upload yet?
