### ISSUE TITLE
[iOS] Video - onFullscreenUpdate only works with manual fullscreen calls

### ISSUE THREAD

**Issue by michchan** [expo/expo#1566]
If "useNativeControls" is true, the callback is only triggered on android but not iOS.

Please refer to this
https://forums.expo.io/t/video-onfullscreenupdate-only-works-with-manual-fullscreen-calls/8014

SDK Version: 25
iOS: 11.2

**Comment by sjchmiela** [comment]
Thank you for posting this report! I can confirm this is an issue and I've addressed this in an upstream pull request https://github.com/expo/universe/pull/2258.

**Comment by amowu** [comment]
It looks like hasn't been fixed in this expo@26.0.0

**Comment by sjchmiela** [comment]
Yup, the fix has been merged into SDK 27, which should be released shortly, let's keep our fingers crossed!

**Comment by FreakTheMighty** [comment]
@sjchmiela is it possible to test the release candidate?

**Comment by terribleben** [comment]
SDK 27 was released yesterday (except for `exp build:ios` which is still pending at the time of writing this comment): https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4

**Comment by sjchmiela** [comment]
Hi @FreakTheMighty, sorry for asking, but are you sure you're checking for the callback being called on SDK 27? This is the latest release and at the same time the only one for which callback should be called both when `presentFullscreenPlayer` is called and when fullscreen player is shown due to native control button tap. 🙂

**Comment by FreakTheMighty** [comment]
@sjchmiela 🤦‍♂️ , this was my first time updating expo. After following [the directions](https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4#be15), its working.

Apologies

**Comment by sjchmiela** [comment]
No problem @FreakTheMighty, I'm happy that it worked! 🙂
