### ISSUE TITLE
[SDK 44][iOS][Managed] "orientation" in app.json is *completely* ignored [MCVE included]

### ISSUE THREAD

**Issue by Aryk** [expo/expo#15666]
### Summary

After upgrading to SDK 44 from 43, the "orientation" setting in app.json is no longer honored on iOS.

It is now **not possible** to lock your phone to portrait on iOS on SDK 44 Managed.

This is on standalone iOS, not through Expo Go. In Expo Go and standalone Android, it works. On iOS it doesn't.

I have a very simple MCVE, but really any "Hello World" app will have this issue on standalone iOS.

I have tried this on iphone 8 and iphone X, both showed this issue so very likely not device-specific.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.12.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/aryk/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.14.1
      expo-cli: 5.0.1
    Expo Workflow: managed

### Reproducible demo

https://github.com/Aryk/expo-repro/tree/sdk44-orientation-bug

**Comment by Aryk** [comment]
@Kudo The MCVE I have here does **not** have expo-updates or the expo-screen-orientation installed and the expo.orientation is still ignored. Do you know if your fix here: https://github.com/expo/expo/pull/15608 will fix that as well?

**Comment by Aryk** [comment]
@brentvatne I made a very simple MCVE to show this core piece of basic functionality is broken on Expo's newest release. If you need anything else from me to get this resolved quickly let me know as I cannot deploy my app if I cannot lock the orientation. 

cc @cruzach

**Comment by Aryk** [comment]
Thanks for looking into this @Kudo! Let me know if there is anything more I can do to help you get this resolved!

**Comment by Aryk** [comment]
Hey @Kudo hows this one looking? Do you think it will be a pretty easy fix that can go out with the next expo minor update?

**Comment by Kudo** [comment]
hey! sorry for your waiting. the root cause is different to #15608. i am trying to come out a solution. in the meantime, you could give EAS Build a shot. i can confirm the app works fine coming from EAS Build.

**Comment by Aryk** [comment]
Hey @Kudo that makes sense because I updated my libraries yesterday with expo upgrade and still got the same issue.

I've tried switching to EAS but have gotten issue after issue, or there will be a config plugin missing for a library or it won't be tested well, etc, etc.

I've been developing on Expo Managed since SDK 36 on the same project. I'd very much like to stay on managed because I'm a solo developer with no experience in iOS or Android development. 

Given this affects 100% of developers using the SDK44 Managed  on iOS, I'd like to wait for a solution on this. If you think it's going to take a long time to get this out, please let me know. 

If you can somehow get this resolved in the coming days it would the best Christmas present I got all year! 🎅 🎁

**Comment by Kudo** [comment]
Hi @Aryk, i had a solution in #15715 and going for our internal review. hopefully to get it published in this week. in the meantime, i am glad to know more details about the issues you encountered in EAS build. please share us what's the problem. thank you!

**Comment by Aryk** [comment]
@Kudo that's awesome to hear! 🥳 Looking forward to hearing the next steps for getting these changes.

I will definitely let you know about the EAS build issues when I revisit it. I had issues about 6 weeks ago at the build step with a very nebulous error. I know many times the issues work themselves out with more bug fixes and development on EAS. I have months of changes ready to go out on our next release (including going from SDK 41 to SDK 44), so I don't want to introduce more variables into this deploy once we get orientation locked, but I will follow up if we encounter any problems when I do upgrade to EAS.

**Comment by Kudo** [comment]
@Aryk we've deployed the fix to production, please help to check whether the new build generated by `expo build` works for you.
and i am looking forward to hearing the EAS build issues from you.

**Comment by Aryk** [comment]
@Kudo just rebuilt the app with `expo build` and it works **great**! 🚀 🔥 

Thanks for rolling this out quickly, now we're off to submit this to the app store! 

I will definitely be following up with you regarding the EAS issues. The first one I remember was that expo-branch is effectively getting support dropped for it:

https://github.com/expo/expo/issues/14631#issuecomment-975319696
https://docs.expo.dev/build-reference/migrating/#expo-branch--is-not-supported-on-eas

`If Branch support is a blocker for you, you can try to build your own config plugin to add react-native-branch to your app today.`

config plugins require some in-depth knowledge of how iOS and Android apps are compiled and are out of my area of expertise.

I found [this](https://forums.expo.dev/t/eas-react-native-branch-example-config-plugin-working-on-ios-and-android/56017/3) after I attempted the EAS build the first time and I'm going to give it a shot next time I try, but I'm still not sure this will work and Expo isn't involved so I don't have their support on getting react-native-branch to work if I switch to EAS. My plan was to wait until I can hire a developer with more in depth knowledge before making the switch to EAS.

**Comment by Kudo** [comment]
@Aryk thanks for sharing the insight.
on EAS build, the [config-plugins](https://docs.expo.dev/guides/config-plugins/) is the future of setup native changes. for react-native-branch, the fantastic community is having a great pr and this is my preference: https://github.com/expo/config-plugins/pull/28

**Comment by Aryk** [comment]
Thanks @Kudo 

I did find a small issue with orientation btw. This seems to be affecting both iOS and Android. For the first 400ms of the app open, if you open the app horizontally you will see the splash screen be horizontal.

Is there anything we can do about this?

https://user-images.githubusercontent.com/525212/148454324-b419f7a2-bfd5-4b2a-aa00-7ca0bd7b2efb.mp4
