### ISSUE TITLE
Unable to resolve module foreach

### ISSUE THREAD

**Issue by zgordon02** [expo/expo#15674]
### Summary

1. Install expo notifications v`0.14.0`
2. import expo notifications in App.js `import * as Notifications from 'expo-notifications';`
3. Observe the error below
<img width="431" alt="Screen Shot 2021-12-21 at 10 48 34 AM" src="https://user-images.githubusercontent.com/90853783/146969672-efa8b750-cd62-4a29-9866-217bbbf969f8.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
      npm: 7.24.0 - ~/.nvm/versions/node/v16.9.1/bin/npm
      Watchman: 2021.12.20.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: Arctic Fox 2020.3.1 Patch 3 Arctic Fox 2020.3.1 Patch 3
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare

### Reproducible demo

All I am doing is importing expo-notifications `import * as Notifications from 'expo-notifications';`

**Comment by byCedric** [comment]
Hi @zgordon02! Thanks for writing in. The `foreach` dependency is a nested dependency, required by `is-typed-array`. The full dependency path would be:

`expo-notifications@0.13.3` → `assert@2.0.0` → `util@0.12.4` → `is-typed-array@1.1.8` → `foreach@2.0.5`

You should halve `foreach@2.0.5` in your `node_modules`, if not, try regenerating the lockfile and reinstalling your `node_modules`.

Hope this helps!
