### ISSUE TITLE
remote update not working with expo publish

### ISSUE THREAD

**Issue by ahmetbasdan** [expo/expo#15686]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by ahmetbasdan** [comment]
My Expo SDK 44
I runed eas build --profile production 
i downloaded my app from play store
I runed expo publish --release-channel prod
my app is not updated

Eas.json
![Screenshot_1](https://user-images.githubusercontent.com/18085857/147065667-bf274fcb-55ba-4b2f-9451-b13d9877140b.png)

**Comment by MasoudJB** [comment]
Any update on this? Could you find the problem?
