### ISSUE TITLE
Bottom sheet scroll view is not interacting with bottom sheet anymore

### ISSUE THREAD

**Issue by byCedric** [expo/expo#15681]
### Summary

Starting from Expo Go 2.23.2, the `BottomSheetScrollView` is not "interacting" with the bottom sheet itself anymore on iOS. In Expo Go 2.22.x, everything seems to work fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.6.1/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v16.6.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 21, 26, 28, 29, 30
        Build Tools: 26.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
        System Images: android-21 | Google APIs ARM EABI v7a, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-23 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/byCedric/expo-go-bottom-sheet-scroll-view-issue (code supplied by gorhom)

### Expo Go `2.22.4`

https://user-images.githubusercontent.com/1203991/147000975-228690dc-19cf-42ee-9e7a-c9f646190513.mov

### Expo Go `2.23.2`

https://user-images.githubusercontent.com/1203991/147000889-222447ba-65a7-402e-a347-65967b2073ff.mov

**Comment by gorhom** [comment]
Thanks @byCedric for reporting this, let me know if you need help debugging this further.

**Comment by haibert** [comment]
Any updates on this guys ?

**Comment by branaust** [comment]
Getting a similar response

**Comment by haenah** [comment]
Same problem here

**Comment by sina3p2p** [comment]
+1

**Comment by sina3p2p** [comment]
@branaust No help

**Comment by Adil-U** [comment]
+1

**Comment by absolon2** [comment]
+1

**Comment by NastuzziSamy** [comment]
To fix this issue, I had to import `gestureHandlerRootHOC` to wrap my main view:

```typescript
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler';

export const Main = gestureHandlerRootHOC((props) => (
	<View>
               { /* your applications */ }
	       { /* your modals here */ }
	</View>
));

export const App = () => (
        <SafeAreaProvider>
               { /* your applications */ }
	       { /* your modals here */ }
	</SafeAreaProvider>
);

export default App;
```

And it works fine :)

**Comment by iM-GeeKy** [comment]
Is there any solution for this? While there are many good recommendations none seem to resolve the initial example provided above from @byCedric.

**Comment by anders0l** [comment]
This issue happen only on iOS on new Expo GO app with managed workflow.
Affected all scrollable components that was imported from react-native-bottom-sheet lib.
On iOS production build and on Android there is no issues.

Related
[https://github.com/gorhom/react-native-bottom-sheet/issues/800](https://github.com/gorhom/react-native-bottom-sheet/issues/800)
[https://github.com/gorhom/react-native-bottom-sheet/issues/803](https://github.com/gorhom/react-native-bottom-sheet/issues/803)
[https://github.com/gorhom/react-native-bottom-sheet/issues/818](https://github.com/gorhom/react-native-bottom-sheet/issues/818)
