### ISSUE TITLE
expo-tracking-transparency not working on iOS 15+

### ISSUE THREAD

**Issue by FlawaCLV** [expo/expo#15689]
### Summary

This plugin is working on my phone (iPhone 12 pro & iOS 15.1.1) but my app is constantly rejected by Apple. The Alert is prompt on my phone but apparently not working on Apple's phone which is iOS 15.2.

Also, `iOSTrackingTransparency.isAvailable()` doesn't return a `Boolean` but all exported code by the plugin.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ~44.0.0 => 44.0.1
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: ~0.17.5 => 0.17.5
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.1
    Expo Workflow: bare

### Reproducible demo

```typescript
const isAvailable = iOSTrackingTransparency.isAvailable()
if (isAvailable) await iOSTrackingTransparency.requestTrackingPermissionsAsync()
```

**Comment by monti-python** [comment]
Same issue here... Tracking Transparency alert is not showing up on an app compiled with `eas build` (managed workflow). The same app compiled with `expo build` Is popping up the alert as expected

**Comment by gabriel-moresco** [comment]
what did you do to solve this?
@FlawaCLV @monti-python

**Comment by FlawaCLV** [comment]
@gabriel-moresco yes by using another package `expo-ads-admob`

```typescript
import { isAvailableAsync, requestPermissionsAsync } from 'expo-ads-admob'

const isAvailable = await isAvailableAsync()
if (Platform.OS === 'ios' && isAvailable) await requestPermissionsAsync()
```

**Comment by yandiro** [comment]
I've run some tests on Browser stack to figure out why it would work on older devices, but not on newer ones, _despite always working on the Simulator._

## Test Results
The app used for testing did not have any other permissions request (like push notifications).

### Does NOT work on (real devices):
iPhone 12 Pro iOS 16
iPhone 14 Pro iOS 16
iPhone 13 iOS 16
iPhone 14 iOS 16
iPhone 15 iOS 17

### Works on (real devices):
iPhone 12 Pro iOS 14
iPhone 12 Pro iOS 17
iPhone 13 Pro iOS 15
iPhone 12 iOS 17
iPhone 13 iOS 15

The behaviour when it works is, as expected: the permission request pops up.
The behaviour when it DOESN'T work is: the permission request never pops up.

App.js

```
onMount() {
    this.initFbSdk();
}

initFbSdk() {
    Settings.initializeSDK();
    return requestTrackingPermissionsAsync()
        .then(({status}) => {
            if (status === 'granted') {
                Settings.setAdvertiserTrackingEnabled(true);
            }
        })
        .catch(e => {
            console.error('Failed to request tracking permissions:', e);
        })
}
```

**Comment by yandiro** [comment]
Got it to work, thanks to [this post](https://stackoverflow.com/questions/71337292/problem-with-the-apple-apptrackingtransparency-in-expo) on Stackoverflow.

You need to make sure the function is called when the app is in the foreground. However, adding an event listener to AppState does not work because it is not fired when the app is started (only when switching between apps), so I did this:

```
    initFbSdk() {
        if (AppState.currentState === 'active') {
            Settings.initializeSDK();
            requestTrackingPermissionsAsync()
                .then(({status}) => {
                    if (status === 'granted') {
                        Settings.setAdvertiserTrackingEnabled(true);
                    }
                })
                .catch(e => {
                    console.error('Failed to request tracking permissions: ', e);
                })
        } else {
            setTimeout(() => {
                this.initFbSdk();
            }, 100);
        }
    }
```

**Comment by FlawaCLV** [comment]
Yes, I manage to make it work with `expo-ads-admob` and `expo-tracking-transparency` when wrap in a setTimeout like so:

```typescript
onNavigationReady() {
    setTimeout(async () => {
      // expo-tracking-transparency
      const isAvailable = iOSTrackingTransparency.isAvailable()
      if (Platform.OS === 'ios' && isAvailable) await iOSTrackingTransparency.requestTrackingPermissionsAsync()
    }, 3000)
  }
```

`onNavigationReady` in when my `<NavigationContainer />` from `@react-navigation/native` is ready.

Bottom line, make sure your app is full launch when requesting the App Tracking Transparency permission.

**Comment by yandiro** [comment]
Got it to work, thanks to [this post](https://stackoverflow.com/questions/71337292/problem-with-the-apple-apptrackingtransparency-in-expo) on Stackoverflow.

You need to make sure the function is called when the app is in the foreground / fully loaded. However, adding an event listener to AppState does not work because it is not fired when the app is started (only when switching between apps), so I did this:

```
    initFbSdk() {
        if (AppState.currentState === 'active') {
            Settings.initializeSDK();
            requestTrackingPermissionsAsync()
                .then(({status}) => {
                    if (status === 'granted') {
                        Settings.setAdvertiserTrackingEnabled(true);
                    }
                })
                .catch(e => {
                    console.error('Failed to request tracking permissions: ', e);
                })
        } else {
            setTimeout(() => this.initFbSdk(), 100);
        }
    }
```
