### ISSUE TITLE
[SDK44][iOS] EAS iOS build failed, RCTEventEmitter error

### ISSUE THREAD

**Issue by TrustyTechSG** [expo/expo#15683]
### Summary

All build use to be fine with SDK 43, just upgraded to SDK 44 with no code changes, then EAS iOS build failed with RCTEventEmitter error.

(ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h:15:1)

  13 |  * events to be observed by JS.
  14 |  */
> 15 | @interface RCTEventEmitter : NSObject <RCTBridgeModule, RCTJSInvokerModule, RCTInvalidating>
     | ^ duplicate interface definition for class 'RCTEventEmitter'
  16 | 
  17 | @property (nonatomic, weak) RCTBridge *bridge;
  18 | 

❌  (ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h:17:40)

  15 | @interface RCTEventEmitter : NSObject <RCTBridgeModule, RCTJSInvokerModule, RCTInvalidating>
  16 | 
> 17 | @property (nonatomic, weak) RCTBridge *bridge;
     |                                        ^ property has a previous declaration
  18 | 
  19 | - (instancetype)initWithDisabledObservation;
  20 | 

❌  (node_modules/@intercom/intercom-react-native/ios/IntercomEventEmitter.h:9:35)

   7 | #endif
   8 | 
>  9 | @interface IntercomEventEmitter : RCTEventEmitter
     |                                   ^ definition of 'RCTEventEmitter' must be imported from module 'React.RCTEventEmitter' before it is required
  10 | @end

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.1
    Expo Workflow: managed

### Reproducible demo

*

**Comment by Kudo** [comment]
duplicated issue of #15622 and should be fixed.
