### ISSUE TITLE
Expo Go keeps crushing when trying to login to my account

### ISSUE THREAD

**Issue by GSolari79** [expo/expo#15697]
### Summary

I have an Android 8.0.0 tablet and expo client keeps crushing when trying to login to my account.

I get the browser popup to use my username and password. I see then tick green button for successfully logging in and when it should return back to expo go it crushes with no message.

This behaviour occurred a couple of days ago and it's irrelevant with any development project as its on expo go side. It's not related to my app, I just try to login to my expo account.

I use the latest version of expo go 2.23.2

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

The crush does not occur during any development.

### Reproducible demo

It's just me trying to login through expo go to my expo account. I do not run any developed app.

**Comment by Henrique-Oliveira** [comment]
i have the same issue described here, there is any solution available?

**Comment by alinnit** [comment]
Same issue, might be a browser issue since it using the default browser.

**Comment by GSolari79** [comment]
Do we have any news on that?

**Comment by alinnit** [comment]
> Do we have any news on that?

Yeah, I set my default browser to be Chrome and it worked.
Good luck

**Comment by baruishigold** [comment]
Aug 1: the issue still persist. :(

**Comment by ParadoxicalSerenity** [comment]
I have this problem on iOS too. When I first made my account it logged in no problem I logged out and now I can no longer log back in or create a new account without Expo Go crashing

**Comment by GSolari79** [comment]
Me too with iOS too. It's very frustrating.

**Comment by andrewmartin** [comment]
Having this and it's driving me nuts, hopefully someone can help.

**Comment by OkancanCosar** [comment]
sept 3: the issue still persist. :(

**Comment by otgxanc** [comment]
September 18, issue still persist on IOS.
