### ISSUE TITLE
Expo push token is not being created in android standalone app

### ISSUE THREAD

**Issue by hatim85f** [expo/expo#15692]
### Summary

I am tryin to solve that issue long time and nothing worked, ExpopushToken is not being created in android standlone app while it's working as expected in ios. I followed the documentaions literally and created everything needed with unrestricted google cloud platform key the key was not created automatically and I did create one
The token is going to my server where should I save users data as an empty string from android

code are taken exactly from documentations, google-services file are added exactly as mentioned in the main root and uploaded app credentials to server

```
 const registerForPushNotificationsAsync = async () => {
    let token;
    if (Constants.isDevice) {
      const { status: existingStatus } =
        await Notifications.getPermissionsAsync();
      let finalStatus = existingStatus;
      if (existingStatus !== "granted") {
        const { status } = await Notifications.requestPermissionsAsync();
        finalStatus = status;
      }
      if (finalStatus !== "granted") {
        alert("Failed to get push token for push notification!");
        return;
      }
      token = (await Notifications.getExpoPushTokenAsync()).data;
    } else {
      alert("Must use physical device for Push Notifications");
    }

    if (Platform.OS === "android") {
      Notifications.setNotificationChannelAsync("default", {
        name: "default",
        importance: Notifications.AndroidImportance.MAX,
        vibrationPattern: [0, 250, 250, 250],
        lightColor: "#FF231F7C",
      });
    }

    return token;
  };

  useEffect(() => {
    registerForPushNotificationsAsync().then((token) =>
      setExpoPushToken(token)
    );

    notificationListener.current =
      Notifications.addNotificationReceivedListener((notification) => {
        setNotification(notification);
      });

    responseListener.current =
      Notifications.addNotificationResponseReceivedListener((response) => {
        console.log(response, "response");
      });


    return () => {
      Notifications.removeNotificationSubscription(
        notificationListener.current
      );
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);
```
and in app.json

```
    "plugins": [
      [
        "expo-notifications",
        {
          "icon": "./assets/mainLogo.png",
          "color": "#ffffff",
          "sounds": [
            "./assets/notificationsound.wav",
            "./assets/notificationsoundothers.wav"
          ]
        }
      ],
      ["expo-image-picker"],
      ["expo-camera"]
    ],
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "notification": {
      "icon": "./assets/logo2.png",
      "color": "#e8e8e8",
      "iosDisplayInForeground": true,
      "androidMode": "collapse",
      "androidCollapsedTitle": "New Notification"
    },
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.12.0 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

```
 const registerForPushNotificationsAsync = async () => {
    let token;
    if (Constants.isDevice) {
      const { status: existingStatus } =
        await Notifications.getPermissionsAsync();
      let finalStatus = existingStatus;
      if (existingStatus !== "granted") {
        const { status } = await Notifications.requestPermissionsAsync();
        finalStatus = status;
      }
      if (finalStatus !== "granted") {
        alert("Failed to get push token for push notification!");
        return;
      }
      token = (await Notifications.getExpoPushTokenAsync()).data;
    } else {
      alert("Must use physical device for Push Notifications");
    }

    if (Platform.OS === "android") {
      Notifications.setNotificationChannelAsync("default", {
        name: "default",
        importance: Notifications.AndroidImportance.MAX,
        vibrationPattern: [0, 250, 250, 250],
        lightColor: "#FF231F7C",
      });
    }

    return token;
  };

  useEffect(() => {
    registerForPushNotificationsAsync().then((token) =>
      setExpoPushToken(token)
    );

    notificationListener.current =
      Notifications.addNotificationReceivedListener((notification) => {
        setNotification(notification);
      });

    responseListener.current =
      Notifications.addNotificationResponseReceivedListener((response) => {
        console.log(response, "response");
      });


    return () => {
      Notifications.removeNotificationSubscription(
        notificationListener.current
      );
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);
```

**Comment by hatim85f** [comment]
@brentvatne can you give me a help here please

**Comment by hatim85f** [comment]
I figured out the issue for whom may pass here In Expo docs it's mentioned that you have to check the api key downloaded with google-services.json file and make sure it's the same yours.... it will not be yours and if you change to your api key it will not work. keep it as it is downloaded and it will work

I figured this after spending 5 days in searching with no results

**Comment by ShyGuy189540** [comment]
Did you have to set up Firebase Notifications?

**Comment by hatim85f** [comment]
@ShyGuy189540 ofcourse I did

**Comment by ShyGuy189540** [comment]
Was it as simple as getting the code from the Firebase website and adding it to your EAS project?

**Comment by Zernach** [comment]
> Was it as simple as getting the code from the Firebase website and adding it to your EAS project? and by EAS project, I mean the area where the Android push key lives in the expo.dev console

https://github.com/expo/expo/blob/master/docs/pages/push-notifications/using-fcm.md

**Comment by jasim00021** [comment]
> I figured out the issue for whom may pass here In Expo docs it's mentioned that you have to check the api key downloaded with google-services.json file and make sure it's the same yours.... it will not be yours and if you change to your api key it will not work. keep it as it is downloaded and it will work
> 
> I figured this after spending 5 days in searching with no results

i have also fees this issue but i cant understand your logic please describe this with more details
