### ISSUE TITLE
no such module 'ExpoModulesCore'

### ISSUE THREAD

**Issue by copper123** [expo/expo#15696]
### Summary

no such module 'ExpoModulesCore' error when expo run on simulator

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

{
  "name": "myviroapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "expo start --dev-client",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.14",
    "@react-native-community/datetimepicker": "^4.0.1",
    "@react-navigation/material-top-tabs": "^6.0.6",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "@viro-community/react-viro": "^2.20.2",
    "eas-cli": "^0.38.3",
    "expo": "^43.0.4",
    "expo-barcode-scanner": "^11.1.2",
    "expo-constants": "^12.1.3",
    "expo-notifications": "^0.13.3",
    "expo-screen-orientation": "^4.0.3",
    "expo-web-browser": "^10.0.3",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-calendars": "^1.1270.0",
    "react-native-gesture-handler": "^2.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modal-datetime-picker": "^13.0.0",
    "react-native-modal-selector": "^2.1.0",
    "react-native-pager-view": "^5.4.9",
    "react-native-parsed-text": "^0.0.22",
    "react-native-qrcode-svg": "^6.1.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.0",
    "react-native-side-menu-updated": "^1.3.2",
    "react-native-svg": "^12.1.1",
    "react-native-swiper-flatlist": "^3.0.16",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.0.0",
    "react-native-webview": "^11.15.0",
    "react-native-youtube-iframe": "^2.2.1"
  },
  "optionalDependencies": {
    "fsevents": "^2.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/runtime": "^7.15.3",
    "@react-native-community/eslint-config": "^3.0.0",
    "babel-jest": "^27.0.6",
    "eslint": "^7.32.0",
    "jest": "^27.0.6",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-native-codegen": "^0.0.7",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.2.0 - /opt/homebrew/bin/node
      npm: 8.1.4 - /opt/homebrew/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 30, 31
        Build Tools: 30.0.2, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.4 => 43.0.4 
      react: 17.0.2 => 17.0.2 
      react-native: 0.65.1 => 0.65.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo

The command below works for physical device
expo run:ios --device Iphone6

but the command for simulator is not working, do I miss anything
expo run:ios --device and choose one simulator, and it will show the error message below.

❌  (/Users/xxxxx/Desktop/starter-kit/ios/Pods/Target Support Files/Pods-myviroapp/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ no such module 'ExpoModulesCore'
   9 | 
  10 | @objc(ExpoModulesProvider)
  11 | public class ExpoModulesProvider: ModulesProvider {

› 1 error(s), and 0 warning(s)

**Comment by okpalaChidiebere** [comment]
I am getting thesame error. 

When i run `npx create-react-native-app` appName and choose the "default template" then run `pod install` followed by `yarn ios` to start the project on iOS emulator iPhone 13  i get the same error.

I opened the project on XCode Version 13.2.1 (13C100) to see the Swift Compiler error "No such Module 'ExpoModuleCore'"

Side Note, When i open the project on thesame iOS emulator device through Expo Client, Everything works just fine

**Comment by greenafrican** [comment]
@copper123 @okpalaChidiebere 

Try opening project.xcworkspace (and not project.xcodeproj) in Xcode and run via simulator.

**Comment by okpalaChidiebere** [comment]
@greenafrican I actually got it running on SDK 44. I had to migrate from bash to zsh and remove everything in ~/.bash_profile in my Mac. 

This recent [issue](https://github.com/expo/expo/issues/15723) helped me solve it

**Comment by app-c** [comment]
incompatibildade com versiao do node...precisa ser instalado nodeJs v14

**Comment by jesse-savary** [comment]
Solved on my M1 Mac by modifying my Podfile:
```
  post_install do |installer|
    ...

    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" # this line in particular
    end

    ...
  end
```

**Comment by JackKenney** [comment]
> @copper123 @okpalaChidiebere
> 
> Try opening project.xcworkspace (and not project.xcodeproj) in Xcode and run via simulator.

I also had to follow these steps
https://stackoverflow.com/a/60090102
