### ISSUE TITLE
adding @react-navigation/drawer breaks v44 via Reanimated?

### ISSUE THREAD

**Issue by acomito** [expo/expo#15691]
### Summary

- start new expo project
- expo install @react-navigation/drawer
- expo install react-native-reanimated
- expo install react-native-gesture-handler
- add "react-native-reanimated/plugin" to babel config
- import @react-navigation/drawer and then createDrawerNavigator()

```
Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

~44.0.0

### Environment

```
  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 5.0.1
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/acomito/expo-bug-44

**Comment by acomito** [comment]
possibly related to https://github.com/expo/expo/issues/15600 ?

**Comment by acomito** [comment]
Okay an update... I was able to get this working without an error

BUT

If i put the expo project inside of another project (as a monorepo), I get the error again. Consistently. I put it in that folder, I get it. I take it out, it's gone.

Really strange... any reason expo couldn't be in a monorepo?

**Comment by AlexMachin1997** [comment]
Yeah I'm also having problems with re-animated since upgrading to v44 of the Expo SDK.

This is the issue I'm seeing:

![image](https://user-images.githubusercontent.com/29917195/147272332-686a942b-e3f5-4c76-9e53-307fc8c1a1d4.png)

Not entirely sure what I'm missing....

**Comment by acomito** [comment]
Mine was very strange... it worked outside of our monorepo but not inside the monorepo. I could slide the project out of the monorepo, it worked. Slide the expo project folder back into the monorepo and run it... didn't work.

No idea how expo even knows what folder it is living in but I'm keeping it separate for now.

**Comment by cm-nutrien** [comment]
Monorepo issues are probably related to how your node_modules are hoisted. In a monorepo they tend to get pulled up into the root of the project but react native will be looking for many of its dependencies at the workspace/project level. Metro config is where to go to implement a fix for that I believe. 

That said, its just one possible problem. I'm dealing with issues related to reanimated and upgrading to 43/44 myself and don't have answers beyond this suggestion.

**Comment by AlanSl** [comment]
I'm having a similar problem with react-native-reanimated via @react-navigation/drawer failing inside a monorepo.

@acomito have you followed the docs on setting up Expo inside a 
monorepo workspace https://docs.expo.dev/guides/monorepos/ and is your babel config including the reanimated plugin in the expo app workspace root, or in the monorepo root?

I've been getting something slightly different; I get the same "maybe you forgot to add Reanimated's babel plugin?" if the babel config is not in the workspace directory, but if it is, the whole build fails silently: expo logs hang at "Starting Metro Bundler" and the apps crash with generic "Something went wrong" messages and nothing in device logs (happens for me with reanimated v2.x and v1.x).

**Comment by sean-m-oleary** [comment]
I have similar issues. Is there a resolution out there for this? We're dead in the water on our 44 upgrade because of this.

**Comment by naraB** [comment]
@acomito Could you share how you go it to work without an error?

**Comment by acomito** [comment]
Hi all, my only solution was to move expo outside of the monorepo

**Comment by YogiHa** [comment]
having the same issue, in a project that expo is the root project (not having monorepo or any equivalent) :/
