### ISSUE TITLE
Streaming logs to a terminal

### ISSUE THREAD

**Issue by KidkArolis** [expo/expo#157]
It would be so sweet.
Is there a way to do that already?

Reading logs in this tiny square is suboptimal.

![image](https://cloud.githubusercontent.com/assets/324440/25775389/02f3c0dc-329c-11e7-8a48-fee4598fd45c.png)

**Comment by ccheever** [comment]
You can use the `exp` command line tool that we provide. 
Guide to different techniques here: https://docs.expo.io/versions/v16.0.0/guides/logging.html

**Comment by KidkArolis** [comment]
Awesome, thanks!

Getting this though:

```
$ exp start --clear --ios
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] exp is already running for this project. Exiting...
```

Grepped my processes for anything suspicious, nothing relevant seems to be running. Shall I file a separate issue :-"
