### ISSUE TITLE
undefined is not an object (evaluating 'u.Platform.select') Evaluating expo-linking.js on Snack

### ISSUE THREAD

**Issue by anis-m-cesi** [expo/expo#15704]
### Summary

I am trying to use the expo-linking package. After installing it as well as its dependencies, I get the error :

`
undefined is not an object (evaluating 'u.Platform.select')
    Evaluating expo-linking.js
`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web (Firefox)

### SDK Version (managed workflow only)

43.0

### Environment

(For the environment part, please note this is happening on expo snack)

### Reproducible demo

This bug seems to occur in this tutorial, for example : https://docs.expo.dev/guides/authentication/#dropbox
Open on snack, install dependencies and fix the missing ',' at line 26. Finally try to build the application on mobile phone. I used my real device as well as iOS and Android emulators.

But really just trying to `import * as Linking from 'expo-linking'` will do the same. Is it because I'm using snack ?

**Comment by howardwu1** [comment]
I'm seeing this also on version 43 -- just tried updating from 41 which did work. version 42 also doesn't work. I'm guessing expo 42 and onward ended up deleting a package maybe
