### ISSUE TITLE
Inverted Datamatrix not read on Android

### ISSUE THREAD

**Issue by f-g-p** [expo/expo#15711]
### Summary

Negative datamatrix image is not detected by the camera scanner on Android. It works fine with the original datamatrix. 
(it works with both on iOS

the datamatrix example: 
![image](https://user-images.githubusercontent.com/8312942/147390369-9b62dd0d-ddbd-485b-be8e-bfd280a170ad.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.0

### Environment

Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/felixpignard/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 31
        Build Tools: 31.0.0
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: bare

### Reproducible demo

https://snack.expo.dev/@fgp/biased-apple

**Comment by martinezguillaume** [comment]
Same problem here !
