### ISSUE TITLE
useIdTokenAuthRequest returns id_token: null in built APK

### ISSUE THREAD

**Issue by kapilpau** [expo/expo#15713]
### Summary

I have an app which I am trying to add Google Auth to. I have followed the [docs guide](https://docs.expo.dev/guides/authentication/#google) and it works when I'm developing in the Expo Go environment, however, as soon as I try and use it in a built APK (using `eas build`), it no longer returns an id_token. I am using the `useIdTokenAuthRequest` function and providing valid a clientID.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 8.2.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    npmPackages:
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.0 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

```
import * as Google from 'expo-auth-session/providers/google';

export default function LoginScreen(props) {

       const promptAsync = Google.useIdTokenAuthRequest({
           androidClientId: "client_id"
       })[2];

       const googleSignIn = async () => {
        const credential = await promptAsync();
        if (credential?.type === "success") {
            if (credential.params.id_token) {
                setDisableBtn(true);
                const token = await third_party_login(credential.params.id_token, "google");
                if (!token)
                    setDisableBtn(false);
            } else {
                simpleErrorToast("Error logging you in.", "An error occurred when trying to log you in with Google. Please try again later.")
            }
        }
    }

    return (
         <Button onClick={() => googleSignIn()}><Text>Sign in with Google</Text></Button>
    )
}

**Comment by kapilpau** [comment]
For workaround see: https://github.com/expo/expo/issues/12808#issuecomment-1002245022

**Comment by MortensenC** [comment]
I know it's an old issue, how did you solved it?
I saw that you were setting **androidClientId** but if it's a managed workflow you have to set the **expoClientId**. Everything is working on EXPO app with the **expoClientId** but after I generated the APK is requesting for the **androidClientId**. I added the **androidClientId** but now I'm receiving an error from Firebase `Firebase: Error (auth/argument-error)` I don't know what else I can you with this.
