### ISSUE TITLE
[Camera] Camera app doesn't seem to be working with either `expo-dev-client` or `bare-workflow` on android.

### ISSUE THREAD

**Issue by a-eid** [expo/expo#15718]
### Summary

I've been trying to get `expo-camera` to work with `expo-dev-client` locally & using eas. but it seem to be failing on android.

<img width="341" alt="Screen Shot 2021-12-27 at 22 27 18" src="https://user-images.githubusercontent.com/19273413/147505105-0306f4e4-aa16-49fa-a62d-f152d5b89fbc.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```bash

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.7.0 - ~/.n/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.20.3 - ~/.n/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Reproducible demo

- steps to reproduce 

[bare workflow]
- init a bare work flow & install expo-camera then try to run on android.

[managed workflow]
clone example/with-dev-client & install `expo-camera` then try to run the app on android.

**Comment by zaubara** [comment]
Install expo-barcode-scanner. And while you're at it, install expo-face-detector as well - that seems to be mandatory with SDK44 now.

**Comment by a-eid** [comment]
@zaubara that seems to have fixed the issue, thank you.
