### ISSUE TITLE
ImageManipulator "base64" option is enabled if you pass false

### ISSUE THREAD

**Issue by serhiipalash** [expo/expo#1571]
### Environment

expo: 25.0.0
react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz

### Steps to Reproduce

Do this
```
import { ImagePicker, ImageManipulator } from 'expo'

const pickerResult = await ImagePicker.launchImageLibraryAsync({})

const uri = pickerResult.uri

const actions = []

actions.push({ resize: { width:50, height: 50 } })

const manipulatorResult = await ImageManipulator.manipulate(uri, actions, {
   base64: false, // FALSE!!!
})

console.log( manipulatorResult.base64 ) // base64 is in Manipulator result. BUG!!! 
```

### Expected Behavior

When user pass `false` to "base64" option there should not be base64 in ImageManipulator result.

### Actual Behavior

When I pass `false` to "base64" option I see base64 in ImageManipulator result.

### Reproducible Demo

https://snack.expo.io/H1dREQOcM

**Comment by nicknovitski** [comment]
Huh!  I'm reproducing it on my iOS device, but not on an android.

That is really weird.  Thank you for pointing it out,

**Comment by aalices** [comment]
Oops! Sorry for that, fixing!

**Comment by serhiipalash** [comment]
@aalices, btw, ImageManipulator result in `base64` format returns without `data-uri` prefix.

Isn't this a bug?

From docs
> It can contain also base64 - it is included if the base64 saveOption was truthy, and is a string containing the JPEG/PNG (depending on format) data of the image in Base64—prepend that with 'data:image/xxx;base64,'

https://docs.expo.io/versions/latest/sdk/imagemanipulator.html#returns

You can test it in my demo https://snack.expo.io/H1dREQOcM

**Comment by aalices** [comment]
@serhiipalash , the docs tells the user to add the data-uri "amnually", that's intended

**Comment by serhiipalash** [comment]
@aalices sorry, it was misunderstanding of this `—prepend ...`.

**Comment by gs-mtripathi** [comment]
I am not getting base64 at all. sdkVersion 30. What am I missing?
