### ISSUE TITLE
Implicit declaration of function 'RCTTransformFromTargetRect' is invalid in C99

### ISSUE THREAD

**Issue by kevgrig** [expo/expo#15712]
### Summary

After upgrading from Expo SDK 43 to SDK 44, I can no longer build an iOS bare project with `@react-native-community/image-editor`. See https://github.com/callstack/react-native-image-editor/issues/102

Since RN wasn't upgraded, I'm wondering if this is related to something else SDK 44 changed, or if you know how to debug this?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
% expo diagnostics

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2021.12.20.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare
```

### Reproducible demo

1. `expo init testimageeditor`
2. `cd testimageditor`
2. `expo install @react-native-community/image-editor`
3. `expo eject`
4. XCode } Open } ios/testimageeditor.xcworkspace
5. Product } Build

**Comment by jordangrant** [comment]
![Screen Shot 2022-01-08 at 1 06 30 AM](https://user-images.githubusercontent.com/7986493/148633640-a560a739-d046-4f82-a403-98b3f2d03651.png)
