### ISSUE TITLE
Upgrade react-native-maps to 0.20.x

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#1572]
Hi guys, please can you upgrade this dependency on SDK 26 it fixes few bugs from 0.19.x,

Thanks !!!

**Comment by AdamJNavarro** [comment]
Hey @outaTiME,

Good news! In SDK26, react-native-maps will be upgraded to version 0.20.x

One small thing, in the future could you please avoid making an issue for something like this and either post in the Community Slack or on our Forums. The more we can reduce clutter in our issues tab, the better we can get around to identifying and fixing genuine issues. Thanks!

Cheers,

Adam

**Comment by outaTiME** [comment]
Hi @AdamJNavarro ... 
np i will post this kind of "enhancements" on forums, thanks !!!
