### ISSUE TITLE
[iOS] SDK 43 and RN 0.64.2 property 'reactDelegate' not found on object of type 'AppDelegate *'

### ISSUE THREAD

**Issue by gsevla** [expo/expo#15728]
### Summary

I was using react-native-unimodules (since sdk 41) and I have upgraded react-native version to 0.64.2 (it worked for android and ios). So I followed https://github.com/expo/fyi/blob/main/expo-modules-migration.md to use expo modules instead unimodules so this problem came out.

[There's an issue](https://github.com/expo/expo/issues/15668) with the same bug(at least it seems to be) but I can't solve with the same trick.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 24, 28, 29, 30
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Arctic Fox 2020.3.1 Patch 2 Arctic Fox 2020.3.1 Patch 2
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

AppDelegate.h
```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

#import <Expo/Expo.h>

@interface AppDelegate : EXAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate>

@property (nonatomic, strong) UIWindow *window;

@end

```

AppDelegate.m
```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNSplashScreen.h"
#import <React/RCTConvert.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  // rn 0.64.2
  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [self.reactDelegate createRootViewWithBridge:bridge
                                                     moduleName:@"Opi"
                                              initialProperties:nil];

   if (@available(iOS 13.0, *)) {
       rootView.backgroundColor = [UIColor systemBackgroundColor];
   } else {
       rootView.backgroundColor = [UIColor whiteColor];
   }

  // expo unimodules migration
  // RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  // RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"main" initialProperties:nil];
  // id rootViewBackgroundColor = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"RCTRootViewBackgroundColor"];
  // if (rootViewBackgroundColor != nil) {
  //   rootView.backgroundColor = [RCTConvert UIColor:rootViewBackgroundColor];
  // } else {
  //   rootView.backgroundColor = [UIColor whiteColor];
  // }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [RNSplashScreen show];  // here
  // or
  //[RNSplashScreen showSplash:@"LaunchScreen" inRootView:rootView];
  // expo 43
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  return YES;
}

//- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
//{
//  // If you'd like to export some custom RCTBridgeModules that are not Expo modules, add them here!
//  return @[];
//}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

**Comment by developerdanx** [comment]
any news or solution? I'm having the same problem.

**Comment by gsevla** [comment]
No @developerdanx =/

Then thought: what if I got the latest version of expo (that supports the same react native versions)? And It worked as expected!

It seems that ` @interface AppDelegate : EXAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate>` is only available from SDK 44. It's weird because react native itself uses reactDelegate, but when we add expo it becomes unavailable.

Can't figure out what's going on, but the last SDK was used as a "workaround".

Hope it helps. And don't forget to update your expo libs after an SDK upgrade.

**Comment by Kudo** [comment]
the `reactDelegate` was introduced in sdk 44. please either upgrade to sdk 44 or remove the `reactDelegate` code. in sdk 44, the AppDelegate should be like this:
https://github.com/expo/expo/blob/5d6ccde6366b94961f774ed563192348aaf143a9/templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.m#L36-L46

**Comment by cgarcial-mx** [comment]
@Kudo I've been looking for this solution the last 2 days. Thanks
