### ISSUE TITLE
[SDK44][bare-code-scanner][Android] QR Code not working after using "back" button

### ISSUE THREAD

**Issue by Fabzien** [expo/expo#15733]
### Summary

When using "bare-code-scanner", after scanning a QR Code then navigate to a result page if I hit "back" button no more QR is scanned. On iOS QR code is well scanned in this case.

Behavior:

Case 1 (Bug):

1. Scanning a QR & display my result screen
2. Click back button
3. Trying scanning another QR = **Not detected**

Case 2:

1.  Scanning a QR & display my result screen
2.  Click back button (so back to my "camera screen") then back again to my main screen
3.  Click on "Scan QR" button
4.  Scanning a QR = **Detected then display my result screen**

This issue is opened following this thread: https://github.com/expo/expo/pull/15393

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD   
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~44.0.0 => 44.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: managed

### Reproducible demo

You can find a reproducible demo here:

https://snack.expo.dev/@fabzien/bare-code-scanner-report-issue

To reproduce (Android only):

1.    Click "Go to QRCodeScanner"
2.    Scan any QR Code
3.    Click "Back" on next screen
4.    Click "Tap to Scan Again"
5.    Try to scan another QR code = Failed

SDK 44 isn't supported on Snack so it's using SDK 33 but you can import it then upgrade to SDK 44.

**Comment by nadarian** [comment]
I am on expo `44.0.3` and expo-barcode-scanner '11.2.0' and I confirm that after pressing back button the scanner does not work anymore.

**Comment by luiszp5** [comment]
I am on expo 44.0.4 and"expo-barcode-scanner": "~11.2.0" and I have the same problem when I change of screen the scanner does not work I think its something in onBarCodeScanned prop

**Comment by Fabzien** [comment]
Are we the only one with this issue ?

**Comment by gcourtemanche** [comment]
I'm having the same issue, I'm on
`expo`: 44.0.6
`expo-camera`: 12.1.2
`expo-barcode-scanner`: 11.2.1

**Comment by ThomasSpindler** [comment]
I'm having the same issue, I'm on
expo: 44.0.0
expo-camera: 12.1.2
expo-barcode-scanner: 11.2.0

**Comment by ThomasSpindler** [comment]
A workaround would be to give the `Camera` component a key prop. `onBarCodeScanned` triggers a key value modification which rerenders the `Camera`. The `Camera ` is reset and able to scan again.

Hope it helps

**Comment by antaymard** [comment]
> 

It works

**Comment by Fabzien** [comment]
> A workaround would be to give the `Camera` component a `key` prop. `onBarCodeScanned` triggers a `key` value modification which rerenders the `Camera`. The `Camera` is reset and able to scan again.
> 
> Hope it helps

As you can see in my example I don't use `Camera` component so I added a `key` prop on my `BarCodeScanner` component and this key prop is update in `onBarCodeScanned` but I still have the same **behavior**.

I added a log in my render to be sure it's re-render.

`<BarCodeScanner key={this.state.num}`

`
 handleBarCodeScanned = (result) => {
                this.setState(state => ({ num: state.num + 1 }));
}
`

any ideas?

**Comment by FrancescoBonizzi** [comment]
> Are we the only one with this issue ?

Same here!

**Comment by eadz** [comment]
Somehow I have "12.1.2" installed but the version in github is "12.1.0" ? https://github.com/expo/expo/blob/master/packages/expo-camera/package.json

**Comment by emilisz** [comment]
> I am on expo 44.0.4 and"expo-barcode-scanner": "~11.2.0" and I have the same problem when I change of screen the scanner does not work I think its something in onBarCodeScanned prop

This Solved "between screens" problem.
`import { useIsFocused } from '@react-navigation/native';`
`const isFocused = useIsFocused();`
`return(`
`{isFocused &&`
    `<Camera />`
`}`
`)`

**Comment by Fabzien** [comment]
My workaround so far.

I added a new return "Home" button on my screen after a QR code scan:

```javascript
                        <TouchableOpacity
                            style={Style.leftBottomIconContainer}
                            onPress={() => this.props.navigation.navigate('Home')}
                        >
```

And I removed the default return button by using "headerLeft":

```javascript
    Result: {
        screen: Result,
        navigationOptions: () => ({
            headerStyle: Style.header,
            headerTitleStyle: Style.headerTitle,
            headerLeft: ()=> null,
            title: I18n.t('code014'),
        })
```

Users have to click on "Scan QR code" again but it's working so far on iOS and Android

**Comment by eadz** [comment]
This issue has not been fixed, can it be reopened?

**Comment by AndonMitev** [comment]
Yes i'm experiecing this issue when i scan and press `Scan again` qr code component is not rendering

**Comment by BitesizedLion** [comment]
Also had this happen...
