### ISSUE TITLE
[Expo SDK v44] React-Native-Gesture-Handler issue after upgrading to latest version of the SDK

### ISSUE THREAD

**Issue by AlexMachin1997** [expo/expo#15737]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

Hi everyone,

So I've recently upgraded to the latest version of the Expo SDK and I'm having a weird issue related to react-native-gesture-handler. When I load up the application now I get the following error message in the console

![image](https://user-images.githubusercontent.com/29917195/147666410-2345649b-033d-4af8-b82c-786bff039d6b.png)

I'm entirely sure what's causing the issue, based on what I've seen from the Expo SDK v44 release blog the only breaking change for 'react-native-gesture-handler' is you now need to wrap your entire application in a 'GestureHandlerRootView' but that hasn't resolve the issue unfortunately.

I've been having a look online and so far I haven't see anyone else with my issue.

If anyone is able to assist with my issue it would be greatly appreciated, sorry if the is is the wrong place to post this sort of question.

Thank's

Alex

**Comment by okpalaChidiebere** [comment]
Follow the installation steps here and you should be fine
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation


For ios, all you need is after adding the Reanimated2 package is `pod install`
For android, you need to do is edit the android/app/src/main/java/MainApplication.java 

The wrap your app
```
registerRootComponent(() => (
  <GestureHandlerRootView style={{ flex: 1 }}>
    <App />
  </GestureHandlerRootView>
));
```
NOTE: the Flex: 1 styling is important

There is a bug right now of react-native-reanimated@2.3.0 not fully compactable with expo44 right now in Android side. I suggest you use version react-native-reanimated@2.2.0

**Comment by AlexMachin1997** [comment]
Hey @okpalaChidiebere 

Ah thought it would be something like that.

I installed the version you reccomended and it actually loads the application 😄 Expo gives me a warning (see image) but it's fine for now.

![image](https://user-images.githubusercontent.com/29917195/147792693-9236bea3-37f3-473d-9fa0-1ce205d36224.png)


Thank's for the assistance it's greatly appreciated😃
