### ISSUE TITLE
App got freeze when I enable the JS remote debugger in SDK 43 and 44

### ISSUE THREAD

**Issue by jazzy-pm** [expo/expo#15732]
### Summary

In SDK 42 my JS remote debugger enable is working fine with app after updating my SDK 44 my app got freeze on splash screen when I enable the JS remote debugger and if I disabled it then my app is working fine. I tried both platform IOS and android both seems to have same issue.

Let me know if I want to updgrade or downgrade any version to resolve this issue

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

` Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.10.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.3 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed`

### Reproducible demo

Below is my packasge.json dependencies

`"@babel/preset-typescript": "^7.16.5",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "7.1.3",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "@unimodules/core": "~7.2.0",
    "accordion-collapse-react-native": "^0.4.0",
    "axios": "^0.18.0",
    "expo": "^44.0.0",
    "expo-ads-admob": "~12.0.0",
    "expo-analytics-segment": "~11.1.0",
    "expo-app-loading": "~1.3.0",
    "expo-asset": "~8.4.4",
    "expo-camera": "~12.1.0",
    "expo-constants": "~13.0.0",
    "expo-device": "~4.1.0",
    "expo-file-system": "~13.1.0",
    "expo-font": "~10.0.4",
    "expo-image-picker": "~12.0.1",
    "expo-local-authentication": "~12.1.0",
    "expo-localization": "~12.0.0",
    "expo-notifications": "~0.14.0",
    "expo-permissions": "~13.1.0",
    "expo-secure-store": "~11.1.0",
    "expo-sharing": "~10.1.0",
    "expo-splash-screen": "~0.14.0",
    "expo-updates": "~0.11.2",
    "immutable": "^4.0.0-rc.12",
    "js-base64": "^2.5.1",
    "moment": "^2.24.0",
    "native-base": "^2.13.5",
    "number-to-words": "^1.2.4",
    "numeral": "^2.0.6",
    "prop-types": "^15.7.2",
    "react": "17.0.1",
    "react-native": "0.64.3",
    "react-native-actionsheet": "^2.4.2",
    "react-native-app-intro-slider": "^2.0.1",
    "react-native-base64": "^0.0.2",
    "react-native-datepicker": "^1.7.2",
    "react-native-display": "^1.0.8",
    "react-native-easy-grid": "^0.2.0",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-fs": "^2.13.3",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-i18n": "https://github.com/xcarpentier/ex-react-native-i18n.git",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-maps": "0.29.4",
    "react-native-masked-text": "^1.13.0",
    "react-native-otp-inputs": "^3.2.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-segmented-control-tab": "^3.3.1",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-swipeout": "^2.3.6",
    "react-native-webview": "11.15.0",
    "react-redux": "^7.2.2",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.5",
    "redux-loop-symbol-ponyfill": "^2.2.2",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0",`

**Comment by rikoriswandha** [comment]
The problem probably related to reanimated version 2. [Link](https://docs.expo.dev/versions/latest/sdk/reanimated/) shows a warning: The new APIs in react-native-reanimated@2 use React Native APIs that are incompatible with Remote JS Debugging. Consequently, you can only debug apps using these APIs using Flipper, which is not yet available in the Expo managed workflow. You will be unable to use Remote JS Debugging if you use the new APIs from Reanimated 2. Remote JS Debugging will continue to work if you only use the APIs that were also available in Reanimated 1.

**Comment by jazzy-pm** [comment]
Thanks for the solution, the issue is with the new version 2.3.0, I tried on 2.2.0 and its working fine for me.
