### ISSUE TITLE
project iOS build failed after upgrading sdk version to 44 (umbrella directory not found)

### ISSUE THREAD

**Issue by iKoru** [expo/expo#15749]
### Summary

After I upgraded expo sdk from 43 to 44, I'm facing iOS build errors. 
Some of them has been resolved, but I couldn't find the solution for this one. 
Please give me some hints. below is the error message.

⚠️  (/Users/(UserName)/Library/Developer/Xcode/DerivedData/(project name)-fpsfqwuotwecxtbofsfpimvwsbrn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-Core.build/module.modulemap:2:12)

  1 | module React {
> 2 |   umbrella "../../Public/React-Core/React"
    |            ^ umbrella directory '../../Public/React-Core/React' not found [-Wincomplete-umbrella]
  3 | 
  4 |   export *
  5 |   module * { export * }

❌  (/Users/(UserName)/Library/Developer/Xcode/DerivedData/(project name)-fpsfqwuotwecxtbofsfpimvwsbrn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-Core.build/module.modulemap:5:10)

  3 | 
  4 |   export *
> 5 |   module * { export * }
    |          ^ inferred submodules require a module with an umbrella
  6 | }
  7 | 

--------------------

I've heard that react-native version for sdk 44 has not changed as 0.64.3, so I don't think that this is react-native problem.

I tried ``pod deintegrate && pod install``  several times and nothing changes.
I can see this error when running expo run:ios or build on Xcode. ``pod install`` finishes successfully.

FYI, I'm using M1 Mac and it worked fine when using sdk 43.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 2.4.2 - /usr/local/bin/yarn
      npm: 8.1.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.0 => 0.3.0 
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

my Podfile is like below

```
# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport=true
$FirebaseSDKVersion = '8.9.1'

platform :ios, '12.0'
pod 'Firebase/Analytics'

target '(project name)' do
  # use_unimodules!
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath], :hermes_enabled => false)

  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'
  use_frameworks! :linkage => :static

  pod 'iOSPhotoEditor', :git => '(custom GitHub repository)', :branch => 'master'
  pod 'TZImagePickerController', :git => '(custom GitHub repository)', :branch => 'master'
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name.include?('iOSPhotoEditor')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5'
        end
      end
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
#    flipper_post_install(installer)
  end
  
  # Follow [Flipper iOS Setup Guidelines](https://fbflipper.com/docs/getting-started/ios-native)
  # This is required because iOSPhotoEditor is implemented using Swift and we have to use use_frameworks! in Podfile
  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
    'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Flipper-Fmt', 'Flipper-Boost-iOSX', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native', 'EXPermissions','UMPermissionsInterface']
  
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
        if pod.name.start_with?('RNFB') || pod.name.start_with?('KakaoSDK')
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
        if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
          def pod.build_type;
            # Uncomment the line corresponding to your CocoaPods version
            Pod::BuildType.static_library # >= 1.9
            # Pod::Target::BuildType.static_library # < 1.9
          end
        end
      end
  end


  # use_flipper!
  # post_install do |installer|
  # flipper_post_install(installer)
  # end

end
```

**Comment by Kudo** [comment]
interesting! might be related to `use_frameworks! :linkage => :static`. i'll take a look.

**Comment by joix97b** [comment]
Removing `use_frameworks! :linkage => :static` didn't help for me.

-------
Environment
Expo CLI 5.0.3 environment info:
System:
OS: macOS 12.1 (Apple Silicon)
Shell: 3.2.57(1)-release (x86_64-apple-darwin21) - /bin/bash
Binaries:
Node: 16.8.0 - /usr/local/bin/node
Yarn: 1.22.10 - /opt/homebrew/bin/yarn
npm: 7.21.0 - /usr/local/bin/npm
Watchman: 2021.08.30.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.2 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
IDEs:
Android Studio: 2020.3 AI-203.7717.56.2031.7935034
Xcode: 13.2/13C90 - /usr/bin/xcodebuild
npmPackages:
@expo/metro-config: ^0.3.0 => 0.3.0
babel-preset-expo: 9.0.1 => 9.0.1
expo: ^44.0.1 => 44.0.1
react: 17.0.2 => 17.0.2
react-dom: 17.0.2 => 17.0.2
react-native: 0.66.0 => 0.66.0
react-native-web: 0.17.1 => 0.17.1
npmGlobalPackages:
expo-cli: 5.0.3
Expo Workflow: bare

**Comment by Kudo** [comment]
after removing `use_frameoworks!`, please reinstall pods: `rm -rf ios/Pods && npx pod-install`

**Comment by iKoru** [comment]
@Kudo Thanks for the answer, but do you mean I should remove use_frameworks! sentence in pod file? Because one of my dependencies need it.

**Comment by Kudo** [comment]
hi there! we've published the expo packages to address the issue. please try to upgrade packages by `yarn add expo@~44.0.4`. supposedly that would also upgrade `expo-modules-autolinking`. please make sure it is true by `yarn why expo-modules-autolinking` and the returned version should be `0.5.5`.

if this doesn't work for you, please let us know.

**Comment by iKoru** [comment]
@Kudo Thanks for quick updates, but I got a new error when building project. I posted new issue #15800 . Could you please check it again?

**Comment by iKoru** [comment]
I found the same issues on expo forum, but there are no solutions here, too.
https://forums.expo.dev/t/could-not-find-module-expomodulescore-for-target-x86-64-apple-ios-simulator-found-arm64-arm64-apple-ios-simulator-m1-mac/60050
