### ISSUE TITLE
[docs] [MapView] Fingerprint instructions don't take development clients into account

### ISSUE THREAD

**Issue by kbrandwijk** [expo/expo#15747]
### Summary

If you build a development client using EAS, on Android the _development_ keystore (debug.keystore) is used. So if you go and create an API key, you need the fingerprint for the debug.keystore instead. Otherwise, you get the 'grey map' symptom that you get for using the wrong fingerprint.

The docs don't mention this scenario. I created this issue instead of creating a PR, because I'd like to discuss the solution first:

- Obtaining the `debug.keystore` fingerprint is not straightforward, you need to run `expo prebuild` locally to get access to the file, then run keytool on it to get the fingerprint
- On the other hand, as `debug.keystore` comes from the template, the fingerprint is actually the same for everyone. The docs could just mention: 'For development clients, create an API key that uses fingerprint `5E:.....:25`. But I wanted to verify that thought with the Expo team first.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/map-view/

**Comment by tcdavis** [comment]
Thanks for bringing to our attention @kbrandwijk!
You're right that that value should work for any project created from one of our templates, so for most developers creating a key from that fingerprint will be the fastest way to get productive.
Not everyone trying to use MapView in a dev client will be coming from a template, so we do think the method of directly finding your fingerprint should be documented as well
