### ISSUE TITLE
Expo updates not working

### ISSUE THREAD

**Issue by sweebee** [expo/expo#15759]
### Summary

I've just created a new clean app with ```fallbackToCacheTimeout``` set to ```8000```. I've build the app with ```eas build -p ios --auto-submit```.

When I change something and run ```expo publish```, it runs fine. But closing and opening the app wont download the update. I've also checked if the app checks for updates with a proxy, but I see no calls to ```expo.host/...```.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

```
 Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - /usr/local/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.12.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.3
    Expo Workflow: managed

```

### Reproducible demo

-

**Comment by IgorNoskov** [comment]
I have the same problem. @sweebee, did you try EAS Update https://docs.expo.dev/eas-update/migrate-to-eas-update/?

**Comment by sweebee** [comment]
I solved it. I was used to expo, which doesn't require to install expo-updates. with EAS build its not included. after installing it and rebuilding it worked.
