### ISSUE TITLE
[expo-media-library] App crashes when getting video with getAssetsAsync on Android 8, 9

### ISSUE THREAD

**Issue by aeroholic** [expo/expo#15762]
### Summary

App crashes without error message when getting media including video with getAssetsAsync on Android 8 and 9.
Hermes, JSC, Expo Go and Standalone all give the same result.
Works fine on android 11 and iOS

"expo": "^44.0.3",
"expo-media-library": "~14.0.0", // I also checked on 13.0.0

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.3

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.3 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^44.0.3 => 44.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

```
import * as MediaLibrary from "expo-media-library";

try {
    const media = await MediaLibrary.getAssetsAsync({
            mediaType: [MediaLibrary.MediaType.video],     // [MediaLibrary.MediaType.photo] works find
        });
} catch (e) {
    console.log(e)
    // App crashes without error message on Android 8, 9
}
```

**Comment by ANTARES-KOR** [comment]
Experienced Same Issue..!

**Comment by jonelvinnaorbe** [comment]
isn't there a fix yet?

**Comment by chancesmith** [comment]
Getting the same on iPhone as well.
expo v43

**Comment by EmmanuelSkapple** [comment]
same here !!

**Comment by gikami** [comment]
Тоже такая же проблема на всех телефонах до 9 версии андроид, с 9 у всех вылет. И это чисто проблема с видео.

**Comment by superyarik** [comment]
facing same issue!

**Comment by superyarik** [comment]
same error on SDK45 with classic build

**Comment by superyarik** [comment]
may be this error related 
`2022-05-24 22:27:51.444 4769-17632/? E/SEC_DRM_PLUGIN_Omafl: OmaPlugin::onOpenDecryptSession(fd)::Drm2IsDrmFileByExtFd::file is NOT DRM by extension`

**Comment by aeroholic** [comment]
@superyarik No, I made it to only load photos on old devices(Platform.OS === "android" && Platform.Version < 29)
Instead, I added a video album next to the photo album on Old Devices, and when the user presses video album, the image picker is launched.
`
const imageObject = await ImagePicker.launchImageLibraryAsync({
            mediaTypes: ImagePicker.MediaTypeOptions.Videos,
            quality: 1,
        });
`
On other devices, photos and videos are displayed together in each album, as originally intended.

**Comment by aeroholic** [comment]
@superyarik No, I made it to only load photos on old devices(Platform.OS === "android" && Platform.Version < 29)
Instead, I added a video album next to the photo album on Old Devices, and when the user presses video album, the image picker is launched.
`
const imageObject = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Videos, quality: 1 });
`
On other devices, photos and videos are displayed together in each album, as originally intended.

**Comment by dbconfig** [comment]
same error ;(

**Comment by gikami** [comment]
Проблема актуальна и решения не найдено. Только заплатки. Есть те кто нашел решение? Может есть альтернатива или самому написать код с получением видео файлов?

**Comment by superyarik** [comment]
@gikami we are implementing on old androids another way to get media, like @aeroholic post

**Comment by bananemo** [comment]
Experiencing the same issue on Android 7

**Comment by superyarik** [comment]
looks like old androids support not in favor in expo dev team

**Comment by MegaCreatives** [comment]
Is there a resolution available for the recurring problem we are encountering?
