### ISSUE TITLE
no deobfuscation file associated with this App Bundle     [EAS BUILD]

### ISSUE THREAD

**Issue by sunset1234321** [expo/expo#15761]
### Summary

When submit to google play
```

Warning
There is no deobfuscation file associated with this App Bundle. If you use obfuscated code (R8/proguard), uploading a deobfuscation file will make crashes and ANRs easier to analyse and debug. Using R8/proguard can help reduce app size. Learn more

Warning
This App Bundle contains native code, and you've not uploaded debug symbols. We recommend that you upload a symbol file to make your crashes and ANRs easier to analyse and debug. Learn more
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

NA

### Reproducible demo

Build with eas build.  
Upload the bundle to play store .

**Comment by brentvatne** [comment]
you can enable debug symbols if you want: https://stackoverflow.com/questions/63373245/how-to-add-debug-symbols-to-build-gradle

we may enable this by default in the future. we do not currently.

**Comment by andreasciamanna** [comment]
@brentvatne or someone else, could you please provide more details on how to do that when using a managed workflow?

As far as I know, the above link can only help with bare workflows, and the last thing want to do is switch to the bare workflow.

Maybe there is something I can see in the `app.json` or `eas.json`?

**Comment by andreasciamanna** [comment]
Maybe I can answer my question.

I've found this: https://stackoverflow.com/questions/73193134/obfuscate-an-expo-file

I'm going to give it a try in our next build.

**Comment by Tieantono** [comment]
> Maybe I can answer my question.
> 
> I've found this: https://stackoverflow.com/questions/73193134/obfuscate-an-expo-file
> 
> I'm going to give it a try in our next build.

I'm still getting the same warning when I uploaded the `.aab` file.

**Comment by andreasciamanna** [comment]
> I'm still getting the same warning when I uploaded the `.aab` file.

I'll most likely publish an update today, so I can check if it works for me.

I'll post an update here.

**Comment by LandoSot** [comment]
> > I'm still getting the same warning when I uploaded the `.aab` file.
> 
> I'll most likely publish an update today, so I can check if it works for me.
> 
> I'll post an update here.

Did it works?

**Comment by andreasciamanna** [comment]
So, it seems to be working fine.

While preparing the new release, I got no warnings about deobfuscation on the Play Store.

Probably it's unrelated, but it is worth mentioning that we faced some issues with the app crashing on Android, after publishing, and as soon as the app started.
This led to some additional changes in the Proguard configuration:

```json
"plugins": [
  [
    "expo-build-properties",
    {
      "android": {
        "enableProguardInReleaseBuilds": true,
        "extraProguardRules": "-keep public class com.horcrux.svg.** {*;}",
        "allowBackup": false
      }
    }
  ]
],
```

**Comment by rishabh-udacity** [comment]
Hey, thanks for sharing this! How do you obfuscate and ios build?

**Comment by aramis-it** [comment]
> So, it seems to be working fine.
> 
> While preparing the new release, I got no warnings about deobfuscation on the Play Store.
> 
> Probably it's unrelated, but it is worth mentioning that we faced some issues with the app crashing on Android, after publishing, and as soon as the app started. This led to some additional changes in the Proguard configuration:
> 
> "plugins": [
>   [
>     "expo-build-properties",
>     {
>       "android": {
>         "enableProguardInReleaseBuilds": true,
>         "extraProguardRules": "-keep public class com.horcrux.svg.** {*;}",
>         "allowBackup": false
>       }
>     }
>   ]
> ],

Does this method still valid in 2025?

**Comment by birosikm** [comment]
Yes, still valid. I just used it.

**Comment by mkhbragg** [comment]
FYI - `enableProguardInReleaseBuilds` is no longer supported in Expo SDK 54. You can still use `extraProguardRules`.

**Comment by watsaket00** [comment]
I'm using Expo 54 and Setup like this

The property enableProguardInReleaseBuilds in Expo's build configuration has been deprecated as of SDK 54. You should now use enableMinifyInReleaseBuilds instead. This change aligns with updates in the underlying Android tooling, where R8 is the recommended tool for code minification and obfuscation, replacing Proguard.

If you previously used:
```json
{
  "plugins": [
    [
      "expo-build-properties",
      {
        "android": {
          "enableProguardInReleaseBuilds": true
        }
      }
    ]
  ]
}
```
You should update it to:
```json
{
  "plugins": [
    [
      "expo-build-properties",
      {
        "android": {
          "enableMinifyInReleaseBuilds": true
        }
      }
    ]
  ]
}
```
This will enable R8 minification in your release builds, which is the modern and supported approach for reducing app size and obfuscating code in Android apps built with Expo SDK 54 and later. For more details, see the Source: [Expo SDK 54 changelog](https://expo.dev/changelog/sdk-54-beta) and the Source: [expo-build-properties documentation](https://docs.expo.dev/versions/latest/sdk/build-properties/#installation).

**Comment by Brosfeer** [comment]
> I'm using Expo 54 and Setup like this
> 
> The property enableProguardInReleaseBuilds in Expo's build configuration has been deprecated as of SDK 54. You should now use enableMinifyInReleaseBuilds instead. This change aligns with updates in the underlying Android tooling, where R8 is the recommended tool for code minification and obfuscation, replacing Proguard.
> 
> If you previously used:
> 
> {
>   "plugins": [
>     [
>       "expo-build-properties",
>       {
>         "android": {
>           "enableProguardInReleaseBuilds": true
>         }
>       }
>     ]
>   ]
> }
> You should update it to:
> 
> {
>   "plugins": [
>     [
>       "expo-build-properties",
>       {
>         "android": {
>           "enableMinifyInReleaseBuilds": true
>         }
>       }
>     ]
>   ]
> }
> This will enable R8 minification in your release builds, which is the modern and supported approach for reducing app size and obfuscating code in Android apps built with Expo SDK 54 and later. For more details, see the Source: [Expo SDK 54 changelog](https://expo.dev/changelog/sdk-54-beta) and the Source: [expo-build-properties documentation](https://docs.expo.dev/versions/latest/sdk/build-properties/#installation).

Did u use this with the configuration to the metro.confige.js ?? or just setting up those in the app.json and it work ??

**Comment by Brosfeer** [comment]
> So, it seems to be working fine.
> 
> While preparing the new release, I got no warnings about deobfuscation on the Play Store.
> 
> Probably it's unrelated, but it is worth mentioning that we faced some issues with the app crashing on Android, after publishing, and as soon as the app started. This led to some additional changes in the Proguard configuration:
> 
> "plugins": [
>   [
>     "expo-build-properties",
>     {
>       "android": {
>         "enableProguardInReleaseBuilds": true,
>         "extraProguardRules": "-keep public class com.horcrux.svg.** {*;}",
>         "allowBackup": false
>       }
>     }
>   ]
> ],

Did u use this only ? I mean without any other configuration to the metro.confge ? Please help !
