### ISSUE TITLE
Expo local notification not working in android when time format 12 hour

### ISSUE THREAD

**Issue by souravpradhan980** [expo/expo#15775]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by souravpradhan980** [comment]
This is My Code: hear trigger is 24-hour format but my android is 12-hour format it is not working Please give the solution -- is there any option to enter trigger with 12-hour format? Please help me

`Notifications.scheduleNotificationAsync({

            content: {
                title: "My First Notification",

                body: "This is local notification Sending"
            },
            trigger: {
                hour: 13,
                minute: 13,

                repeats: true
            }
        });`
![local-notification-issue](https://user-images.githubusercontent.com/68933126/147948360-324efb8e-76bb-4096-aeda-d2b655f92bf6.PNG)

**Comment by souravpradhan980** [comment]
on android 24 hour format working fine but not working in 12 hour format please help me some one

**Comment by byCedric** [comment]
Hi @souravpradhan980, it should not matter if the phone is set to 12 or 24 hours. It's just being translated, so 13:13 will be 1:13pm. The docs might help you further on this issue: https://docs.expo.dev/versions/v44.0.0/sdk/notifications/#schedulenotificationasyncnotificationrequest-notificationrequestinput-promisestring
