### ISSUE TITLE
Question about release channels

### ISSUE THREAD

**Issue by marcosmartinez7** [expo/expo#1577]
In the release channels documentation it saids:

> "On the production stack, release v1 of your app by running exp publish --release-channel prod-v1. You can build this version of your app into a standalone ipa by running exp build:ios --release-channel prod-v1. **You can push updates to your app by publishing to the prod-v1 channel. The standalone app will update with the most recent compatible version of your app on the prod-v1 channel.(1)**
> If you have a new version that you dont want v1 users getting, release v2 of your app by running exp publish --release-channel prod-v2 and building it with exp build:ios --release-channel prod-v2. Users with the prod-v2 ipa will only be pulling releases from that channel.
> You can continue updating v1 of your app with exp publish --release-channel prod-v1, and users who havent updated to the latest prod-v2 ipa in the Apple App Store will continue receiving the latest prod-v1 releases."

Suppose that i release a production v1 version, i generate the ipa/apk by using exp build:[platform
] --release-channel prod-v1, and after some months, i want to release a new version of my application to the AppStore/PlayStore.

According to documentation, i can push an update to the prod-v1 channel and the standalone app will update with the most recent comptible version of my app for that channel (1)

**The question is, this guarantees that when i submit my new prod-v1 version to AppStore/PlayStore the users will get a prompt to update the app?** 

**Or this is just a way to have multiple versions of my application using just expo and expo client?**

Kind regards,
Marcos

**Comment by AdamJNavarro** [comment]
Hey @marcosmartinez7,

Can you do me a favor and move this to our forums? https://forums.expo.io/

We try our best to keep our Issues tab limited to genuine issues and bugs so it's easier for us to maintain.

Thanks,

Adam
