### ISSUE TITLE
[expo-in-app-purchases] Error on any purchase in Expo v43 "Sending `Expo.purchasesUpdated` with no listeners registered."

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/expo#15770]
### Summary

After setting up the IAPs precisely as specified and testing it on a device, I'm seeing the reported error. This is a reopening of https://github.com/expo/expo/issues/9082.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.22.7 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.11.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
        Build Tools: 19.1.0, 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.3, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 28.0.2, 28.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react-native: 0.64.3 => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.39.0
    Expo Workflow: bare

### Reproducible demo

Set up as specified in docs, purchase handler won't be invoked on successful purchase.
Verified in expo-in-app-purchases v12.0.0 and 12.1.0

EDIT: Same issue on Expo 44 (after fixing upgrade issues, especially one with react-native-reanimated that required a patch). Will be trying `react-native-iap` tomorrow.

**Comment by garrett-gottlieb** [comment]
I added some debugs to the js file in the package. This is a bug with the `eventEmitter`. I'm only ever seeing the middle console log here:
```js
export function setPurchaseListener(callback) {
  if (purchaseUpdatedSubscription) {
    console.log('REMOVING EXISTING PURCHASE LISTENER')
    purchaseUpdatedSubscription.remove()
  }

  console.log('SETTING PURCHASE LISTENER', {
    PURCHASES_UPDATED_EVENT,
    eventEmitter,
  })
  purchaseUpdatedSubscription = eventEmitter.addListener(
    PURCHASES_UPDATED_EVENT,
    result => {
      console.log('PURCHASE EVENT', result)
      callback(result)
    }
  )
}
```
It seems that the event emitter isn't receiving events from the native event emitter because the native event emitter never gets the listener attached.
Here's the console log:
```
SETTING PURCHASE LISTENER 
{PURCHASES_UPDATED_EVENT: "Expo.purchasesUpdated", eventEmitter: EventEmitter}
PURCHASES_UPDATED_EVENT: "Expo.purchasesUpdated"
eventEmitter: EventEmitter
_eventEmitter: NativeEventEmitter
_disableCallsIntoModule: false
_nativeModule:
addListener: ƒ ()
connectAsync: ƒ ()
disconnectAsync: ƒ ()
finishTransactionAsync: ƒ ()
getProductsAsync: ƒ ()
getPurchaseHistoryAsync: ƒ ()
purchaseItemAsync: ƒ ()
removeListeners: ƒ ()
__proto__: Object
_subscriber: EventSubscriptionVendor
_currentSubscription: null
_subscriptionsForType:
Expo.purchasesUpdated: [EmitterSubscription]
RCTDevMenuShown: [EmitterSubscription]
appStateDidChange: [EmitterSubscription]
appearanceChanged: [EmitterSubscription]
collectBugExtraData: [EmitterSubscription]
collectRedBoxExtraData: [EmitterSubscription]
didCompleteNetworkResponse: (32) [empty × 32]
didReceiveNetworkData: (32) [empty × 32]
didReceiveNetworkDataProgress: (32) [empty × 32]
didReceiveNetworkIncrementalData: (32) [empty × 32]
didReceiveNetworkResponse: (32) [empty × 32]
didSendNetworkData: (32) [empty × 32]
didUpdateDimensions: [EmitterSubscription]
keyboardDidHide: (7) [EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription]
keyboardDidShow: (7) [EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription]
keyboardWillHide: (7) [EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription]
keyboardWillShow: (7) [EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription, EmitterSubscription]
onGestureHandlerEvent: [EmitterSubscription]
onGestureHandlerStateChange: [EmitterSubscription]
toggleElementInspector: (3) [EmitterSubscription, EmitterSubscription, EmitterSubscription]
url: (4) [empty × 3, EmitterSubscription]
websocketClosed: (2) [EmitterSubscription, EmitterSubscription]
websocketFailed: (2) [EmitterSubscription, EmitterSubscription]
websocketMessage: (2) [EmitterSubscription, EmitterSubscription]
websocketOpen: (2) [EmitterSubscription, EmitterSubscription]
__proto__: Object
__proto__: Object
__proto__: EventEmitter
_listenerCount: 1
_nativeModule:
addListener: ƒ ()
connectAsync: ƒ ()
disconnectAsync: ƒ ()
finishTransactionAsync: ƒ ()
getProductsAsync: ƒ ()
getPurchaseHistoryAsync: ƒ ()
purchaseItemAsync: ƒ ()
removeListeners: ƒ ()
__proto__: Object
__proto__: Object
__proto__: Object
```

**Comment by jb9229** [comment]
i'm suffering from the same error at "Location.watchPositionAsync"

Who can help you?

**Comment by raresluncan** [comment]
I also have this same problem. Why is this issue closed?
