### ISSUE TITLE
Error in pod install

### ISSUE THREAD

**Issue by tiavina-mika** [expo/expo#15783]
### Summary

when I run `yarn ios` or `pod install` i've go this error:
 #import <ExpoModulesCore/EXSingletonModule.h>
           ^ 'ExpoModulesCore/EXSingletonModule.h' file not found

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.18.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.12.20.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30, 32
        Build Tools: 29.0.2, 30.0.2, 32.0.0
        System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

https://snack.expo.dev/@tiavina-mika/1da2fd

**Comment by brentvatne** [comment]
likely what is happening here is that you are using expo-modules-core on sdk 42. it is not supported until sdk 43 and greater. see https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc for more info

**Comment by onedanshow** [comment]
What worked for me was updating the iOS target deployment to `13.0`. Was on `7.0` before. Clearly safe to do so: https://developer.apple.com/support/app-store/

**Comment by onedanshow** [comment]
Actually, the trick was to add `expo-modules-core` into `package.json` directly (instead of as a dependency). So `yarn add expo-modules-core`.
