### ISSUE TITLE
Can't login to newly created account

### ISSUE THREAD

**Issue by patrickpissurno** [expo/expo#1578]
Hey. I'm currently having a problem to create my account. I downloaded the Expo Client on my iPhone and used it to sign-up. Then, I received the following message: "**We have detected suspicious login behavior and further attempts will be blocked. Please contact the administrator**".

Still, I received the confirmation email and confirmed my account. The issue is: **I can't sign-in**. Neither on my iPhone, nor on the browser. I always receive the following message: "I**nvalid token specified**".

I even tried reseting my password to see if it would make a difference, but it didn't. Please help me fix my issues with my account, as I just can't start using Expo without this.

Steps to reproduce:
1. Go straight to the iOS App Store and download Expo client
2. Tap create new account and register one
3. Confirm your email and try to sign-in

I know I should probably be posting this in the forums, but as I can't sign-in, how I'm supposed to do that?

**It seems that some other people are having a related issue: [https://forums.expo.io/t/exp-we-have-detected-suspicious-login-behavior-and-further-attempts-will-be-blocked-please-contact-the-administrator/8273/2](https://forums.expo.io/t/exp-we-have-detected-suspicious-login-behavior-and-further-attempts-will-be-blocked-please-contact-the-administrator/8273/2)**

My Expo username: patrickpissurno

Thanks

**Comment by tcdavis** [comment]
We believe this is resolved, can you try signing in again?

**Comment by Tommydreamer57** [comment]
Signing in works now, but the + button to add new projects is missing, so there is nowhere to type in a url to connect to an app

**Comment by patrickpissurno** [comment]
I can confirm that the sign-in issue is solved. Thanks. @Tommydreamer57 could you please open an a new issue to report that problem? I think I also have it. I can't find a + button too (but I must admit that this is my first time using Expo)
