### ISSUE TITLE
Getting "exp is already running for this project" when using CLI

### ISSUE THREAD

**Issue by KidkArolis** [expo/expo#158]
```
$ exp start --clear --ios
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] exp is already running for this project. Exiting...
```

Any ideas how I could figure out what's going on?

**Comment by terribleben** [comment]
Do you have:
- XDE running the same project already?
- Another terminal somewhere else running `exp` in the same directory?

**Comment by KidkArolis** [comment]
No to both :)

**Comment by ccheever** [comment]
Are you on a Mac? Can you do something like `ps auxwww | grep exp` and see if there are other instances of `exp` running?

**Comment by KidkArolis** [comment]
I did, there weren't. Ok, let me see if I can still reproduce and Ill jump
into debugger.

**Comment by KidkArolis** [comment]
Yup, can reproduce, didn't dig deeper than this, but seems like it's checking http://localhost:80 .. which seems wrong cause indeed I am running a server on port 80.

![image](https://cloud.githubusercontent.com/assets/324440/25820483/44acad70-3429-11e7-9a7d-ea128e9b83e7.png)

**Comment by jesseruder** [comment]
What do you have in your project's `.expo/packager-info.json` file?

**Comment by KidkArolis** [comment]
```js
{
  "packagerPort": null,
  "packagerPid": null,
  "expoServerPort": null,
  "expoServerNgrokUrl": null,
  "packagerNgrokUrl": null,
  "ngrokPid": null
}
```

**Comment by jesseruder** [comment]
Ok I think I understand the bug. For now you'd probably have to stop the other server before starting `exp`. We can take a look at this soon.

**Comment by uipoet** [comment]
Is there a workaround in the meantime? Having to stop my server on port 80 any time I need to restart exp is frustrating.

**Comment by uipoet** [comment]
I found that by manually editing `.expo/packager-info.json` to `{"expoServerPort": 19000}` before `exp start`, I could avoid having to stop my process running  on port 80.

**Comment by uipoet** [comment]
Now I'm automating this with the following line in my `package.json`:
```JSON
"start": "echo \"{\\\"expoServerPort\\\": 19000}\" > .expo/packager-info.json && exp start",
```

The issue does not occur in macOS, only Linux.

**Comment by dikaiosune** [comment]
cc @fson -- I can't assign to you but it seems like a good thing to fix in line with other things you've been doing.

**Comment by terribleben** [comment]
I think maybe I've managed to reproduce this:

- one project is already running at localhost:19000
- try to run a second packager (for a totally unrelated project) where settings.json says "localhost" and packager-info.json says "19000"
- second instance of exp will mistakenly think it's already running

I think it's possible to get into this state by starting/stopping some projects at weird times such that they manage to accidentally both claim the same port.

**Comment by huy-lv** [comment]
I got same problem and found a solution here: open .expo/packager-info.json and edit two line 
```
"expoServerPort": 19000,
"packagerPort": 19001,
```
to 19002 and 19003 (or some free ports). :D
