### ISSUE TITLE
Error building detached Android project with react-native-voice

### ISSUE THREAD

**Issue by dixya** [expo/expo#1580]
I am trying to use react-native-voice in a freshly detached expo app and getting build error.
During building, I got SDK Build 23.0.2 is too low for ':react-native-voice', Minimum required is 25.0.0. Expo suggests not to update any recommended version after detaching. 
I tried both way, updating and not updating and none of it worked.
Can you please suggest me what should I do ?

**Comment by watadarkstar** [comment]
I also getting this error!

**Comment by sjchmiela** [comment]
I've just confirmed that an Expo project ejected on SDK31 does build successfully even when `react-native-voice` is linked. 🎉
