### ISSUE TITLE
[expo-dev-launcher] - iOS App stays back - crash because of StatusBar and UIViewControllerBasedStatusBarAppearance in custom dev client

### ISSUE THREAD

**Issue by hirbod** [expo/expo#15801]
### Summary

Following up with @brentvatne comment that 
`UIViewControllerBasedStatusBarAppearance` set to `true` should be possible with custom dev clients.

Source: https://github.com/software-mansion/react-native-screens/pull/642

## Why?
react-native-screens has a very nice StatusBar Management built in.

## Crashing
I've tried to use this prop but my App stays black and won't show up any content.

```
RCTStatusBarManager module requires that the UIViewControllerBasedStatusBarAppearance to be false.
```
I've made sure that no component is importing StatusBar.
I am not sure if expo-app-loading or expo-splash-screen is also interfering with this, but the only thing I've found that might be the issue was this line and import in expo-dev-launcher:

https://github.com/expo/expo/blob/master/packages/expo-dev-launcher/bundle/views/LauncherApp.tsx#L42

I tried to patch-package the import and this line but it did not fix the issue for me, so I am not 100% confident that this is the root cause or just one of the root-causes.

Any help is appreciated.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "^0.8.0",

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      react-dom: 17.0.2 => 17.0.2 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Reproducible demo

-

### Stacktrace (if a crash is involved)

RCTStatusBarManager module requires that the UIViewControllerBasedStatusBarAppearance to be false.

**Comment by endruuu** [comment]
I didn't face this issue.

But, in my case, I needed to use a library that requires UIViewControllerBasedStatusBarAppearance to be set to true.
Fortunately, it's just a matter of warning popup when it is set to false.

So, my workaround was to set the value to be conditional:
- true when in release mode
- false when in debug mode

Since Expo dev client doesn't appear in release mode -- hence we can set it to true, this workaround worked.

To set the UIViewControllerBasedStatusBarAppearance to have conditional value, you can create a user defined setting in project.pbxproj, e.g. ENABLE_CONTROLLED_STATUS_BAR, with value of YES and NO.

Then, in info.plist, you can use:
```
<key>UIViewControllerBasedStatusBarAppearance</key>
<string>$(ENABLE_CONTROLLED_STATUS_BAR)</string>
```

**Comment by endruuu** [comment]
But, yes, it would be great if Expo dev client doesn't force the UIViewControllerBasedStatusBarAppearance value.
I tried removing this [line](https://github.com/expo/expo/blob/master/packages/expo-dev-launcher/bundle/views/LauncherApp.tsx#L42), or use expo-status-bar, but still didn't work.

**Comment by pnadj** [comment]
Same issue

**Comment by a-eid** [comment]
adding 

```json      
"infoPlist": {
  "UIViewControllerBasedStatusBarAppearance": true,
}
```

to `app.json` `expo.ios` seems to work locally on the simulator with `expo prebuild`.

but when building the app with xcode on my device I get the issue again.

**Comment by hirbod** [comment]
@lukmccall @tsapeta I can confirm that this issue has been fixed!
