### ISSUE TITLE
New Update available. Downloading...  Screen stuck in production build in android

### ISSUE THREAD

**Issue by akash-saha-1** [expo/expo#15815]
### Summary

after expo build running the apk file stuck on  splash screen new update available downloading.. But running fine in dev mode

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Production

### Reproducible demo

 "dependencies": {
    "@expo/ngrok": "^2.5.0",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "expo": "^44.0.0",
    "expo-av": "~10.2.0",
    "expo-keep-awake": "~10.0.1",
    "expo-status-bar": "~1.2.0",
    "native-base": "^3.2.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-paper": "^4.11.1",
    "react-native-sound": "^0.11.1",
    "react-native-vector-icons": "^9.0.0",
    "react-native-web": "0.17.1"
  },

![image](https://user-images.githubusercontent.com/65488464/148368984-18f06b6b-9fe8-443c-8b6e-1e5a16febdd7.png)

**Comment by stylder** [comment]
I have the same trouble

**Comment by byCedric** [comment]
Hi @akash-saha-1 and @stylder! Can either one of you share a small working repository where this issue happens? The "New update available, downloading..." message should not be present in production builds because it's a development indicator. But, to debug where this is coming from, we would need a working repository.

**Comment by akash-saha-1** [comment]
Here is the link of repo. where the issue is there. Please checkout this and help us to solve this issue.
https://github.com/akash-saha-1/focus-time-app

**Comment by Richard1984** [comment]
Same problem.

**Comment by Richard1984** [comment]
Any solution? @akash-saha-1

**Comment by akash-saha-1** [comment]
@Richard1984 , I solved this by expo eject and converting the app to core react native app and then all worked well.

**Comment by brentvatne** [comment]
here are some debugging tips: https://docs.expo.dev/workflow/debugging/
also: https://expo.fyi/splash-screen-hanging

**Comment by CharleeJennings** [comment]
Any resolution yet? same issue occurring here

**Comment by brentvatne** [comment]
closed because no reproducible example provided. 

here are some debugging tips: https://docs.expo.dev/workflow/debugging/
also: https://expo.fyi/splash-screen-hanging

**Comment by BFMarks** [comment]
Still an issue - unusable

**Comment by katayama8000** [comment]
> Here is the link of repo. where the issue is there. Please checkout this and help us to solve this issue. https://github.com/akash-saha-1/focus-time-apk

link is dead.

**Comment by jcubic** [comment]
For me, the only way to solve the invalid state of Expo is to delete the emulator in Android Studio and add a new one again. This will install the Expo Go app on a phone again. It seems this is the only way to restart the expo if it ends in an invalid state.

**Comment by icaroov** [comment]
The problem still persists and apparently has no definitive cause, it appears to be random.

**Comment by jonahx** [comment]
I've got the same issue.

**Comment by TheOnenOnlyJP** [comment]
Same issue here

**Comment by ravinder-gs** [comment]
The same issue occurs on both iOS and Android, making it impossible to work. Every time, I have to restart the entire system to make it work.

**Comment by bezenson** [comment]
@ravinder-gs Seems like I have exactly the same issue. Just decided to try recommended framework and it works soo bad. After stopping process in terminal and starting again, on android and ios app is stuck on splash screen with "New Update available. Downloading..." message. Only after I restart my mac it works again, but also it is not allowed to stop the process. Did you resolve an issue?

**Comment by ravinder-gs** [comment]
@bezenson For me, the problem was with the VS Code terminal. As soon as I ran the app in the Mac terminal, it worked.

**Comment by Degn** [comment]
> [@bezenson](https://github.com/bezenson) For me, the problem was with the VS Code terminal. As soon as I ran the app in the Mac terminal, it worked.

Still works
