### ISSUE TITLE
Dev menu is sideways in landscape only app

### ISSUE THREAD

**Issue by c-fitzmaurice** [expo/expo#15835]
### Summary

In an iOS iPad only, landscape only app, the dev menu in a custom Expo Dev Client (built using EAS build) comes into the screen from the side of the iPad in the wrong orientation.

![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-01-07 at 13 13 08](https://user-images.githubusercontent.com/3401771/148588865-0461f888-a3db-4923-9505-7571fb5b9b25.png)

Important parts from `app.config.js`:

```
orientation: 'landscape',
ios: {
  isTabletOnly: true,
  supportsTablet: true,
  requireFullScreen: true,
},
'platforms': [
  'ios',
]
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

```
expo-dev-client@0.8.0
expo-dev-launcher@0.10.0

expo-updates-interface@0.5.0
expo-updates@0.11.3
```

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.3.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

Update `app.config.js` like this:

```
orientation: 'landscape',
ios: {
  isTabletOnly: true,
  supportsTablet: true,
  requireFullScreen: true,
},
'platforms': [
  'ios',
]
```

**Comment by byCedric** [comment]
Hi @c-fitzmaurice! Can you share a small working repository where you run into this issue? Only with that, we are able to help you debug and/or fix the issue 😄

**Comment by c-fitzmaurice** [comment]
@byCedric Thanks, you can find a sample repo here: https://github.com/c-fitzmaurice/sideways

Screenshots from a fresh install:
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-01-10 at 11 12 19](https://user-images.githubusercontent.com/3401771/148799696-39c4fb03-9280-42e0-81c2-0a94d93b8dd2.png)
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-01-10 at 11 12 23](https://user-images.githubusercontent.com/3401771/148799709-ee996f08-7932-4630-a831-3d2faf165b51.png)
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-01-10 at 11 13 56](https://user-images.githubusercontent.com/3401771/148799718-b1a9f41f-ab54-458b-914e-2bee8a99f50f.png)

**Comment by c-fitzmaurice** [comment]
Any information on this? The app seems to always open in landscape upside down and rotate as well? Thanks!

**Comment by c-fitzmaurice** [comment]
After updating to Expo `45` and Expo Dev Client `0.9.5` with `orientation: 'landscape'` in my `app.config.json` this is still present. The dev menu only presents itself from the side of the screen in portrait mode. This makes the reload button almost unpressable.

@byCedric Any update on this? There is also the reproduction repo here: https://github.com/c-fitzmaurice/sideways

![Simulator Screen Shot - iPad (9th generation) - 2022-05-10 at 13 15 41](https://user-images.githubusercontent.com/3401771/167685395-fa2cb465-7bc5-4545-ac5a-9f67afc8eef5.png)

**Comment by c-fitzmaurice** [comment]
@byCedric on the iPad Pro 11 inch, the reload button is not clickable. 

![image](https://user-images.githubusercontent.com/3401771/168319322-129a44fc-d6de-4cc9-a831-53d292bbb7a7.jpeg)

**Comment by adel8555** [comment]
Same issue...

**Comment by c-fitzmaurice** [comment]
Confirmed `expo-dev-client@1.2.0` fixed this issue for me! THANK YOU!

![image](https://user-images.githubusercontent.com/3401771/184727085-9be60bf4-dce7-40b6-88ef-294f97c7ddce.png)

**Comment by lukmccall** [comment]
Fixed by https://github.com/expo/expo/pull/18509.
