### ISSUE TITLE
Expo build is not working

### ISSUE THREAD

**Issue by claudiofus** [expo/expo#15832]
### Summary

I've just created a build with `expo build:ios --no-wait -t archive`, but I'm not able to download the `.ipa` file. From this [page](https://status.expo.dev/), it seems all fine. Is anyone facing the same issue?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed
```

### Reproducible demo

Create a build with `expo build:ios --no-wait -t archive` and download `.ipa` file from [expo.dev](expo.dev) website

**Comment by claudiofus** [comment]
This problem has been resolved

**Comment by claudiofus** [comment]
Occasionally this problem occurs again, now it's not possible to download `.ipa` from build page.

**Comment by byCedric** [comment]
Hi @claudiofus! Can you share the exact link to your Expo app where you can't download the `.ipa` file?

**Comment by claudiofus** [comment]
This is the main URL but it's working again now: [https://exp-shell-app-assets.s3.us-west-1.amazonaws.com](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com)

**Comment by claudiofus** [comment]
Hello again, the bucket to the AWS S3 storage is not working now, could you please check? Thank you
