### ISSUE TITLE
EXPO error  "While resolving module `expo/build/launch/registerRootComponent` ",  

### ISSUE THREAD

**Issue by bobwatcherx** [expo/expo#15842]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by byCedric** [comment]
Hi @bobwatcherx! This file should be in your `node_modules/expo` folder. You can see the file here: https://github.com/expo/expo/blob/master/packages/expo/build/launch/registerRootComponent.js

One thing to note is that we export this method from the `expo` package. So you shouldn't need to import it from `expo/build/launch/registerRootComponent`. If you import it directly from your entry point, I would recommend to change:

```js
// Change this line
import registerRootComponent from 'expo/build/launch/registerRootComponent';

// To
import { registerRootComponent } from 'expo';
```

Hope this helps!

**Comment by bobwatcherx** [comment]
> Hi @bobwatcherx! This file should be in your `node_modules/expo` folder. You can see the file here: https://github.com/expo/expo/blob/master/packages/expo/build/launch/registerRootComponent.js
> 
> One thing to note is that we export this method from the `expo` package. So you shouldn't need to import it from `expo/build/launch/registerRootComponent`. If you import it directly from your entry point, I would recommend to change:
> 
> ```js
> // Change this line
> import registerRootComponent from 'expo/build/launch/registerRootComponent';
> 
> // To
> import { registerRootComponent } from 'expo';
> ```
> 
> Hope this helps!

when I first created a project with expo .  and run with EXPO GO .  i get an error like that.  I will try your way
