### ISSUE TITLE
pip installs the wrong Python exponent server sdk version by default

### ISSUE THREAD

**Issue by seandmatthews** [expo/expo#1585]
pip installing exponent-server-sdk without specifying a version installs 0.1.3
0.0.14 is listed as the latest version in your github repo.

I'm not 100% certain of why this happens, but I suspect that both versions exist on pypi (Searching on the "old" pypi lists the correct 0.0.14 and searching on the "new" pypi gives the 0.1.3 version) and because you broke semver, pip is tricked into installing the older package.

I haven't gone to a great deal of trouble testing this on machines that aren't my primary development machine, so it's possible that the issue exists only for users who already had 0.1.3 installed. (As pip install --upgrade won't actually upgrade) I doubt this somewhat because even uninstalling and reinstalling the package still gives 0.1.3 back by default.

Obviously you can just pass a version when pip installing, so this is probably isn't a super high priority issue; I've already fixed it for myself at least, but I figured you guys may want to know.

**Comment by brentvatne** [comment]
cc @ccheever

**Comment by wli** [comment]
@brentvatne @ccheever FYI v0.1.4 and v0.2.0 were released so this issue is obsolete.

**Comment by FiberJW** [comment]
This seems to be resolved, so I'll close this for now. If you need further support, please make a topic on our [forums](https://forums.expo.io) :)
