### ISSUE TITLE
[docs] "Environment variables in Expo" page is wrong

### ISSUE THREAD

**Issue by carlos3g** [expo/expo#15859]
### Summary

Hello, everyone!

There is a wrong information in the [Using a dotenv file](https://docs.expo.dev/guides/environment-variables/#using-a-dotenv-file) section in [Environment variables in Expo](https://docs.expo.dev/guides/environment-variables) page. It says it's possible to use [motdotla/dotenv](https://github.com/motdotla/dotenv) with react-native, but this isn't true since this package depends on modules only available in Node.js environment!

### Link to the related docs page

https://docs.expo.dev/guides/environment-variables/#using-a-dotenv-file

### Anything else?

I thought about editing this page myself, but I believe we need to discuss first if it's better to remove the entire section or just replace the package and its usage.

See these links for more information:
* https://stackoverflow.com/a/39046690/13274020
* https://github.com/motdotla/dotenv/blob/master/lib/main.js
* https://github.com/motdotla/dotenv/issues/574

**Comment by byCedric** [comment]
Hi @carlos3g! This section only describes how to load dotenv files in `app.config.js` and how to hook it up in babel (so you can use it in your react native app). It does not talk about directly importing `dotenv` in a react native app.

Hope this helps!
