### ISSUE TITLE
issue on Facebook.loginWithReadPermissionAsync

### ISSUE THREAD

**Issue by Rehan-Imran** [expo/expo#15857]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

I am using expo-faceook to provide a feature to login using faceook.
Below you will find the code to how i am using it

```js
try {
  setLoading(true)
  await Facebook.initializeAsync({appId,appName})
  const { type, token } = await Facebook.logInWithReadPermissionsAsync({
    permissions: ['public_profile', 'email'],
  })

  if (type === 'success') {
    let queryPath = ?token=${token}
    if (props.fromOtp) {
      if (props.otp.phone) {
        queryPath = ?token=${token}&phone=${props.otp.phone}
      } else {
        // alert('App Encountered an error, please close the app and try again')
      }
    }  
    HttpClient.get(/auth/fbUserSignInWithAppSDK${queryPath}).then((response) => {
      props.onLoginSuccess(res)
    })
  } else {
    setLoading(false)
  }
} catch ({ message }) {
  setLoading(false)
  alert(Facebook Login Error: ${message})
}
```

at this portion i am facing issues as i am not able to redirect to facebook page.
I tries to debug the issue and i released that...

```
const { type, token } = await Facebook.logInWithReadPermissionsAsync({
    permissions: ['public_profile', 'email'],
})
```

... after this code the application fails and control goes to Catch. Can someone kindly help me out with this issue?

**Comment by Rehan-Imran** [comment]
I am using expo-faceook to provide a feature to login using faceook. 
Below you will find the code to how i am using it

try {
      setLoading(true)
      await Facebook.initializeAsync({appId,appName})
      const { type, token } = await Facebook.logInWithReadPermissionsAsync({
        permissions: ['public_profile', 'email'],
      })
      if (type === 'success') {
        let queryPath = `?token=${token}`
        if (props.fromOtp) {
          if (props.otp.phone) {
            queryPath = `?token=${token}&phone=${props.otp.phone}`
          } else {
            // alert('App Encountered an error, please close the app and try again')
          }
        }
        HttpClient.get(`/auth/fbUserSignInWithAppSDK${queryPath}`).then((response) => {
          props.onLoginSuccess(res)
        })
      } else {
        setLoading(false)
      }
    } catch ({ message }) {
      setLoading(false)
      alert(`Facebook Login Error: ${message}`)
    }

at this portion i am facing issues as i am not able to redirect to facebook page.
I tries to debug the issue and i released that...

      const { type, token } = await Facebook.logInWithReadPermissionsAsync({
        permissions: ['public_profile', 'email'],
      })

... after this code the application fails and control goes to Catch. Can someone kindly help me out with this issue?

**Comment by byCedric** [comment]
Hi @Rehan-Imran! Did you follow all steps required in https://docs.expo.dev/versions/latest/sdk/facebook/#registering-your-app-with-facebook?

If so, can you create a new issue, from the bug issue template, with a repo? The snippet you provided has some syntax issues.
