### ISSUE TITLE
[LocalAuthentication] FaceID return error "unknown -1004, User interaction is required"

### ISSUE THREAD

**Issue by erichou668** [expo/expo#15856]
### Summary

I develop one code for two app, but after I add LocalAuthentication feature on SDK 44 for these app, it will have a issue  "unknown -1004, User interaction is required" if I install the two apps on one iPhone. The latest installed app face id is ok, but other app face id will return error "unknown -1004, User interaction is required". I see a solution that the two use different sdk version, will fix the issue. But I must use the same sdk version for the two app. Could you please help to fix the bug?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

"unknown -1004, User interaction is required"

### Reproducible demo

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import * as LocalAuthentication from "expo-local-authentication";

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
      <TouchableOpacity
            style={{width:100,height:50}}
            onPress={() => {
              LocalAuthentication.authenticateAsync({
                promptMessage: "Access your Account",
                fallbackLabel: "Enter passcode",
                cancelLabel: "Cancel",
                disableDeviceFallback:true,
            }).then((result) => {
                console.log(result);
                alert(JSON.stringify(result));
                if (result.success) {
                    console.log("auth successfully");
                    alert("auth successfully");
                } 
                }
            });
            }}
        >
            <Text style={{fontSize:16}}>Face id</Text>
        </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by dhcmega** [comment]
Hi, did you solve it? I'm facing the same error on iOS, SDK43, iPhone 6, thank you!
