### ISSUE TITLE
[docs] Deprecated info in in-app purchase

### ISSUE THREAD

**Issue by Gentlee** [expo/expo#15858]
### Summary

It asks to configure unimodules, but they are deprecated.
So how to use this module in react-native app (not expo)?

### Link to the related docs page

https://github.com/expo/expo/tree/master/packages/expo-in-app-purchases

### Anything else?

How to use expo modules currently in RN app? I can't find proper doc.

**Comment by kbrandwijk** [comment]
Maybe they got updated recently, but I don't see any reference to unimodules in those specific docs (anymore).
