### ISSUE TITLE
[nextjs] Runtime-Errors When Trying To Open [On Android]

### ISSUE THREAD

**Issue by TheKruspe** [expo/expo#15868]
### Summary

I cloned [this example](https://github.com/expo/examples/tree/master/with-nextjs) and then integrated Next-Auth (`yarn add next-auth`). I can run the application via `npm start` - which leads to Next.js serving the project on `http://localhost:3000` - which works as expected. When starting via `expo start` and then loading the project on my Android device, the app crashes:

	TypeError: this._url.endsWith is not a function. (In 'this._url.endsWith('/')', 'this._url.endsWith' is undefined)
	at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
	at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
	at node_modules\react-native\Libraries\Core\ExceptionsManager.js:176:19 in handleException
	at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
	at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
	at node_modules\metro-runtime\src\polyfills\require.js:203:6 in guardedLoadModule
	at http://192.168.2.2:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:118908:3 in global code

	Invariant Violation: "main" has not been registered. This can happen if:
	* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
	* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
	at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
	at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
	at node_modules\react-native\Libraries\Core\ExceptionsManager.js:176:19 in handleException
	at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
	at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
	at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:372:8 in __guard
	at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:115:4 in callFunctionReturnFlushedQueue

So I decided to create a new project with newer dependencies.

    expo init --template blank
    cd Test
    yarn add @expo/next-adapter
    yarn add next-expo
    yarn next dev

This showed the following error:

    	ready - started server on 0.0.0.0:3000, url: http://localhost:3000
	/docs/messages/swc-disabled
	The project's Babel config is invalid: Cannot read properties of undefined (reading 'uid')
	TypeError: Cannot read properties of undefined (reading 'uid')
		at Object.statSync (C:\Users\Me\Test\node_modules\next\dist\compiled\@vercel\nft\index.js:1:293416)
		at isFile (C:\Users\Me\Test\node_modules\resolve\lib\sync.js:12:23)
		at loadAsFileSync (C:\Users\Me\Test\node_modules\resolve\lib\sync.js:123:17)
		at loadNodeModulesSync (C:\Users\Me\Test\node_modules\resolve\lib\sync.js:192:25)
		at Function.resolveSync [as sync] (C:\Users\Me\Test\node_modules\resolve\lib\sync.js:98:17)
		at resolveStandardizedName (C:\Users\Me\Test\node_modules\@expo\webpack-config\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
		at resolvePreset (C:\Users\Me\Test\node_modules\@expo\webpack-config\node_modules\@babel\core\lib\config\files\plugins.js:58:10)
		at loadPreset (C:\Users\Me\Test\node_modules\@expo\webpack-config\node_modules\@babel\core\lib\config\files\p    at createDescriptor (C:\Users\Me\Test\node_modules\@expo\webpack-config\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
		at C:\Users\Me\Test\node_modules\@expo\webpack-config\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
	error Command failed with exit code 1.

I manged to get get around this using a resolution in `package.json`:

    "resolutions": {
        "resolve": "1.20.0"
    }

I am not sure that this is a good idea because now I get a bunch of warnings

	Warning: useTransformReactJsxExperimental has been renamed to useTransformReactJSXExperimental (capitalized JSX) in react-native@0.64.0
	Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
	The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
			["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
	to the "plugins" section of your Babel config.
	Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.

and a familiar error in the end:

	C:\Users\Me\Test\node_modules\next\dist\build\webpack-config.js:663
			const isLocal = request.startsWith('.') || // Always check for unix-style path, as webpack sometimes
									^

	TypeError: Cannot read properties of undefined (reading 'startsWith')
		at handleExternals (C:\Users\Me\Test\node_modules\next\dist\build\webpack-config.js:663:33)
		at webpackConfig.externals (C:\Users\Me\Test\node_modules\next\dist\build\webpack-config.js:772:24)
		at C:\Users\Me\Test\node_modules\@expo\webpack-config\webpack\addons\withUnimodules.js:162:58
		at C:\Users\Me\Test\node_modules\next\dist\compiled\webpack\bundle5.js:42205:21
		at deprecated (node:internal/util:124:12)
		at handleExternals (C:\Users\Me\Test\node_modules\next\dist\compiled\webpack\bundle5.js:42353:8)
		at next (C:\Users\Me\Test\node_modules\next\dist\compiled\webpack\bundle5.js:42331:9)
		at handleExternals (C:\Users\Me\Test\node_modules\next\dist\compiled\webpack\bundle5.js:42336:7)
		at C:\Users\Me\Test\node_modules\next\dist\compiled\webpack\bundle5.js:42433:5
		at Hook.eval [as callAsync] (eval at create (C:\Users\Me\Test\node_modules\next\dist\compiled\webpack\bundle5.js:141512:10), <anonymous>:37:1)
	error Command failed with exit code 1.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android
Windows

### SDK Version (managed workflow only)

44

### Environment

**Cloned project with Next-Auth:**
  
Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ^44.0.0 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

**New project:**

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ~44.0.0 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

I couldn't create a snack, because it won't resolve `next` or `next-adapter`.

The (latest) issue can be reproduced by following the steps I mentioned (the same that are written [here ](https://github.com/expo/examples/blob/master/with-nextjs/README.md).

**Comment by trajano** [comment]
I got the same issue too namely with `new URL(someString)` with Expo 47 only on Android
