### ISSUE TITLE
[RN 0.64][SDK 44][Android] expo package no longer compatible with RN 0.64 (expo issue)

### ISSUE THREAD

**Issue by drpiou** [expo/expo#15867]
### Summary

New React Native 0.64.3 project with expo SDK 44 just does not compile:
`Task :expo:compileDebugKotlin FAILED`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.n/bin/node
      Yarn: 1.22.17 - ~/.n/bin/yarn
      npm: 6.14.15 - ~/.n/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 28, 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
    IDEs:
      Android Studio: Arctic Fox 2020.3.1 Patch 4 Arctic Fox 2020.3.1 Patch 4
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.1 => 17.0.1
      react-dom: ^17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: ^0.17.5 => 0.17.5
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

1. Start RN project: `npx react-native init AwesomeProject --version 0.64.3`
2. Add expo web: `npm i -S react-native-web react-dom expo`
3. Run on Android: `npm run android`

**Comment by drpiou** [comment]
Possible solution: downgrade expo to SDK 42 (expo SDK 43 has the same issue).

**Comment by byCedric** [comment]
Hi @drpiou! Adding Expo to a plain React Native project [requires more steps](https://docs.expo.dev/bare/installing-expo-modules/) after installing it. Please follow the docs to do that, or just start from our bare template: `$ expo init -t blank ./AwesomeProject`
