### ISSUE TITLE
[expo-sqlite][android] Attempting to upgrade compile and target SDK version to 31

### ISSUE THREAD

**Issue by kkelley-leftbrain** [expo/expo#15864]
### Summary

After attempting to upgrade our `compileSdkVersion` and `targetSdkVersion` from 30 -> 31, as well as an Android Studio update, I am no longer able to build our app.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

^39.0.0

### Environment

  
```
Expo CLI 4.5.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.2.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.13.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.3 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.5.0
    Expo Workflow: bare
```

### Reproducible demo

Prior to our last release (July 2021) we've upgraded our target and compile SDK versions to `30` per [the playstore requisites](https://developer.android.com/google/play/requirements/target-sdk). All good there. 

In preparing for our next rollout, at some point I attempted to upgrade those again, this time to `31` ( as well as downloading Android 12 Platform/Tools (SDK 31) ). 

This seems to have been due to a transient issue (see: not necessary) so I attempted to merely set them back to `30` again i.e. 
```
android/build.gradle
buildscript {
    ext {
        buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        androidXCore = "1.6.0" // added after some of the below troubleshooting
    }
```

In addition, I upgraded Android Studio (Arctic Fox) 
```
Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 20, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin
```
... which may have added some (or all of the) fuel to the fire).

When attempting to build my application, I've started encountering several errors seeming to come from the gradle `CheckAarMetadataWorkAction` task. Specifically it keeps landing on the following error:

```
> Task :app:checkAppstoreReleaseAarMetadata FAILED
Execution failed for task ':app:checkAppstoreReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > /Users/kevinkelley/leftbrain-app/node_modules/expo-sqlite/android/build/intermediates/aar_metadata/release/aar-metadata.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

where `appstore` is a productFlavor and `release` is a buildtype/signing config.  To clarify, this issue is only occurring in `release` mode, debug builds/runs fine.

At this point I've found a lot of info relating to an `androidx.core:core-ktx` upstream issue that surfaced a few months back, and have tried:

 - [cache busting](https://stackoverflow.com/a/50545862)
 - Tweaking the buildToolsVersion, compile/targetSdkVersion as mentioned above following these (below) and others
   - [attempt 1](https://stackoverflow.com/questions/68221505/task-appcheckdebugaarmetadata-failed-when-run-react-native-run-android)
   - [attempt 2 (less viable)](https://stackoverflow.com/questions/64521804/execution-failed-for-task-appcheckdebugaarmetadata) 
   - [attempt 3](https://stackoverflow.com/questions/69037481/android-app-wont-build-the-mincompilesdk-31-specified-in-a-dependencys-an)

Ultimately this boiled down to trying to force some of the upgraded upstream features to a downgraded version (as far as I can tell).  It looked something like the following (collectively):

```
configurations.all {
    resolutionStrategy { 
        force 'androidx.work:work-runtime:2.6.0' 
        force 'androidx.core:core-ktx:1.6.0'
        force 'androidx.browser:browser:1.2.0'
    }
}
```

but alas, this is still not working for me.

Before rambling much further, is this an issue of just being in the wrong version across the board? Maybe a good idea to do a RN version / Gradle(s) version upgrades? I'm stumping pretty hard and feel like this is potentially a larger expo-dependency issue or a red herring that just snags here first in terms of build order.

**Comment by kkelley-leftbrain** [comment]
![image](https://user-images.githubusercontent.com/71667995/149001632-a3041b54-0e82-4144-b0a2-4c3de15a3220.png)

Following up; I'm confused at why this specific package is having an issue, because the sibling packages are configured almost identically. In addition, the task (above) that I would assume is responsible for creating/writing to that folder is passing successfully, and is only later failed. I don't know enough about kotlin or the worker tasks to understand what might be missing here; does anyone know if I'm getting warmer?

![image](https://user-images.githubusercontent.com/71667995/149001978-edca86a4-332e-4a61-a822-e6b7934939a3.png)

**Comment by axeldelafosse** [comment]
Related: just tried upgrading to 31 but `expo-updates` failed to build:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-updates:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```

**Comment by kkelley-leftbrain** [comment]
I really wish I could provide more insight on this - for now (since `expo-sqlite` is being included as a transient dependency, i.e. we have no direct use for it) my only resolve has to simply remove it via the android/app/build.gradle
```
...
dependencies { 
   ...
   addUnimodulesDependencies([exclude: [ ... , 'expo-sqlite']])
   ...
}
```

I have seen a handful of other users complaining of the Android Studio + kotlin upgrade combos putting them in a bad state, but I really can't determine the missing piece.

If anyone is able to shed light on this for others (though I'm not entirely sure how), it would be greatly appreciated.

**Comment by charlzyx** [comment]
Run. In android dir `./gradlew app:dependencies > dep.txt` to check who depend neo sqlite， in my case， by  flipper

**Comment by kkelley-leftbrain** [comment]
Appreciate the reply @charlzyx . It looks like throughout the report it is coming through another unimodule, namely `expo-updates`: 

``` 
...
+--- project :expo-updates
|    +--- project :unimodules-core
|    +--- com.facebook.react:react-native:+ -> 0.63.3 (*)
|    +--- androidx.room:room-runtime:2.1.0
|    |    +--- androidx.room:room-common:2.1.0
|    |    |    \--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    +--- androidx.sqlite:sqlite-framework:2.0.1
|    |    |    +--- androidx.annotation:annotation:1.0.2 -> 1.2.0
|    |    |    \--- androidx.sqlite:sqlite:2.0.1
|    |    |         \--- androidx.annotation:annotation:1.0.2 -> 1.2.0
|    |    +--- androidx.sqlite:sqlite:2.0.1 (*)
...
```

Probably getting warmer overall, but I still don't grasp why during the compile steps that sqlite is left out of those AAR-metadata-generation steps and ultimately fails the build?

I initially had thought perhaps some bad setup with flavors/signging-configs/build-variant but since this issue has popped up only recently (and after an android studio upgrade) I'm thinking its more along the lines of being awkwardly versioned (see: RN, Expo, kotlin, etc).

**Comment by kkelley-leftbrain** [comment]
Going to close this - didn't see any other traffic and my workaround avoids the initial issue. Happy to lend a hand if anyone else encounters a similar situation. 

Cheers.
