### ISSUE TITLE
I can't test my app in iOS with Expo

### ISSUE THREAD

**Issue by subwat** [expo/expo#1586]
Hi, I have some problems when i try to run my app on phones that have iOS, but in Android don't have this problem. I'm coding in Sublime Text, not in XDE and executing my project in terminal, with commands '`npm start`' and reading the QR Code. I'm coding in Windows 10.

The erro that appears is

 "C:/Users/adria/Desktop/App/src/Imgs/image.png: Cannot find module 'C:/Users/adria/Desktop/App/node_moduless/expo/tools/hashAssetFiles'.

In the first time i did think that image is with wrong name or wrong directory, and i go to the code and certify that is correctly. So, i resolve to try in my Android and for my surprise, work correctly.

My package.json

> {
>   "name": "App",
>   "version": "0.1.0",
>   "private": true,
>   "devDependencies": {
>     "react-native-scripts": "1.11.1",
>     "jest-expo": "25.0.0",
>     "react-test-renderer": "16.2.0"
>   },
>   "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
>   "scripts": {
>     "start": "react-native-scripts start",
>     "eject": "react-native-scripts eject",
>     "android": "react-native-scripts android",
>     "ios": "react-native-scripts ios",
>     "test": "node node_modules/jest/bin/jest.js"
>   },
>   "jest": {
>     "preset": "jest-expo"
>   },
>   "dependencies": {
>     "expo": "^25.0.0",
>     "react": "16.2.0",
>     "react-native": "0.52.0",
>     "react-navigation": "^1.5.8"
>   }
> }
>

I try to remove the image from my project and try run again, and have the same problem but with another image, from react-navigation 

> C:\Users\adria\Desktop\App\node_modules\react-navigation\src\views\assets\back-icon.png

**Comment by mssngr** [comment]
I had a similar issue. The iOS Expo app just had an update that removes the QR Code functionality, and your Expo app on iOS will not work until you update it. Hope that's the issue you're facing, since it's an easy fix.

**Comment by mekela** [comment]
> `` The iOS Expo app just had an update that removes the QR Code functionality, and your Expo app on iOS will not work until you update it. Hope that's the issue you're facing, since it's an easy fix.

How I can test my app without QR Code? 
@mssngr

**Comment by mssngr** [comment]
If you're using the `exp` cli like I am, you'll use `exp start` like normal, then press `s` when the dev server is booted up and type in your phone number or email so Expo can send a link to your project directly to your phone.

**Comment by quinlanj** [comment]
Hi @subwat , can you try the suggestions provided by @mssngr ? Closing this issue for now.

**Comment by mssngr** [comment]
I noticed recently that I have to do `exp send -s <insert phone number or email>` before I do `exp start` to send the link to my phone, now. Not sure what changed from a few days ago.

**Comment by EvanBacon** [comment]
@mssngr on iOS you can no longer test other users projects :( we had to remove the QR scanner as well... If you point the native iphone camera at a QR it'll open the associated `exp://` link 🤐

**Comment by mssngr** [comment]
I didn't hear it from you! 🤐

**Comment by revskill10** [comment]
@EvanBacon THe link from email and sms couldn't be clicked. So how to open then ?

**Comment by amnnzri** [comment]
same issue... when i command to send through email and i click it become blank... please help me

**Comment by Luckygirlllll** [comment]
welcome to the buggy expo, I can't open it through the link as well, link opens safari and then nothing happens....

**Comment by revskill10** [comment]
Facebook product is well-known for stability.
Now this Expo stuffs are nearly impossible to get working.
So my conclusion is that, Facebook doesn't use Expo for its product.
So why React Native recommends using a thing that's they're not sure if it's usable or stable enough ?

**Comment by wilfredonoyola** [comment]
Hi, I am trying run my app in iOS with Expo, but this does not recognize my app. It is very frustrate because I followed the steps from react native docs.

Let me know if that I exist some bug with Expo App.

Thanks
