### ISSUE TITLE
Unable to use @apollo/client in expo 44.0.0

### ISSUE THREAD

**Issue by acomito** [expo/expo#15860]
### Summary

I have a new v44 project, when I try to import apollo client, I get this error

```
Metro has encountered an error: While trying to resolve module `@apollo/client` from file `/Users/anthony/Desktop/data/mobile/screens/HomeScreen/index.tsx`, the package `/Users/anthony/Desktop/data/mobile/node_modules/@apollo/client/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/anthony/Desktop/data/mobile/node_modules/@apollo/client/main.cjs`. Indeed, none of these files exist:

  * /Users/anthony/Desktop/data/mobile/node_modules/@apollo/client/main.cjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /Users/anthony/Desktop/data/mobile/node_modules/@apollo/client/main.cjs/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json): /Users/anthony/Desktop/data/mobile/node_modules/metro/src/node-haste/DependencyGraph.js (436:17)

  434 |
  435 |         if (error instanceof InvalidPackageError) {
> 436 |           throw new PackageResolutionError({
      |                 ^
  437 |             packageError: error,
  438 |             originModulePath: from,
  439 |             targetModuleName: to

ABI44_0_0RCTFatal
__37-[ABI44_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

This is putting our project at a hard stop. After I've been repping expo really hard, I'm looking like an idiot atm 😂. Hoping I can get through this sooner than later.

Surprisingly I don't see any other issues other than one open PR. I thought expo uses apollo/graphql in their own internal projects? (I noticed some PRs around using apollo+codegen).

Is there a workaround or has anyone had a chance to review the open PR?

https://github.com/expo/expo/pull/15836

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

https://github.com/expo/expo/pull/15836

**Comment by acomito** [comment]
Okay. Found the solution.

add metro.config.js to your root then do

```
const { getDefaultConfig } = require("metro-config");
const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();
exports.resolver = {
  ...defaultResolver,
  sourceExts: [...defaultResolver.sourceExts, "cjs"],
};

```

**Comment by byCedric** [comment]
@acomito Glad you found the root cause, I do want to recommend to use `expo/metro-config` instead of `metro-config`. It includes some other stuff we need for Expo itself, see [this guide for more info](https://docs.expo.dev/guides/customizing-metro/).

**Comment by andrerpena** [comment]
@acomito Thanks a lot but when I do that, although the original problem is fixed, now all imports from `@apollo/client` are `undefined`. Any idea? I also posted this on SO https://stackoverflow.com/questions/71733802/im-unable-to-load-apollo-client-on-a-react-native-expo-app

**Comment by andrerpena** [comment]
@byCedric Apparently `getDefaultValues` doesn't exist if you use `expo/metro-config` 

```
const { getDefaultConfig } = require("expo/metro-config");
const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();
exports.resolver = {
  ...defaultResolver,
  sourceExts: [...defaultResolver.sourceExts, "cjs"],
};
```

> getDefaultConfig.getDefaultValues is not a function
TypeError: getDefaultConfig.getDefaultValues is not a function
    at Object.<anonymous> (/Users/andrepena/git/anglio-mobile-rn/metro.config.js:2:56)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)

**Comment by tetogomez** [comment]
@andrerpena  I have the same problem!

I have been trying with different apollo versions but I haven't found anything

**Comment by andrerpena** [comment]
@tetogomez You have to use `EXPO_USE_EXOTIC`

```
  "scripts": {
    "start": " expo start",
    "android": "EXPO_USE_EXOTIC=1 expo start --android",
    "ios": "EXPO_USE_EXOTIC=1 expo start --ios",
    "web": "EXPO_USE_EXOTIC=1 expo start --web",
    "eject": "EXPO_USE_EXOTIC=1 expo eject",
    "graphql-generate": "graphql-codegen --config codegen.yml"
  },
```

**Comment by andrerpena** [comment]
@tetogomez Use this `metro.config.js`

```
const { getDefaultConfig } = require('@expo/metro-config');

const config = getDefaultConfig(__dirname, {
    // Initialize in exotic mode.
    // If you want to preserve `react-native` resolver main field, and omit cjs support, then leave this undefined
    // and skip setting the `EXPO_USE_EXOTIC` environment variable.
    mode: 'exotic',
});

module.exports = config;
```

The `exotic` thing makes Metro to be able to find the weird `cjs` module that `@apollo/client` exports

**Comment by Nicomalacho** [comment]
@andrerpena we used that approach and it worked in most of the cases, but when doing a proper build we had some weird issues with the navigation, like freezing in the splash screen until we touch the screen. 

We decided to use an older version of the apollo client included in [apollo boost](https://www.npmjs.com/package/apollo-boost) and it works smoothly 

hopefully, someday it gets fixed by apollo

**Comment by Muhammad-Bilal-7896** [comment]
> @tetogomez Use this `metro.config.js`
> 
> ```
> const { getDefaultConfig } = require('@expo/metro-config');
> 
> const config = getDefaultConfig(__dirname, {
>     // Initialize in exotic mode.
>     // If you want to preserve `react-native` resolver main field, and omit cjs support, then leave this undefined
>     // and skip setting the `EXPO_USE_EXOTIC` environment variable.
>     mode: 'exotic',
> });
> 
> module.exports = config;
> ```
> 
> The `exotic` thing makes Metro to be able to find the weird `cjs` module that `@apollo/client` exports

Hi Thank you so much for your solution. Worked for me 100% correctly. Thanks again.
