### ISSUE TITLE
Use of undeclared identifier 'EXAppDefines'

### ISSUE THREAD

**Issue by Yandamuri** [expo/expo#15871]
### Summary

I am trying to migrate from `react-native-unimodules` to `Expo` and followed this [guide](https://dev.to/wbroek/migrate-from-react-native-unimodules-to-expo-modules-25c6) for migration. After completing the process successfully and ran the project from Xcode, I am facing following error in `EXAppDefinesLoader.m`,

> Use of undeclared identifier 'EXAppDefines'

This is how `EXAppDefinesLoader.m` file looks like,

<img width="726" alt="Screenshot 2022-01-11 at 5 27 46 PM" src="https://user-images.githubusercontent.com/31983789/148938615-5da0b736-f4d4-47e4-ae90-17b3bee08784.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

    Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.0.0 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-* <45.0.0 => 44.0.4 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.0 => 0.64.0 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

here is reproducible demo code,

         #import <Expo/EXAppDefinesLoader.h>

        #import <ExpoModulesCore/ExpoModulesCore.h>
        #import <React/RCTDefines.h>

       @implementation EXAppDefinesLoader

       + (void)load
       {
              BOOL APP_DEBUG;
              [EXAppDefines load:@{
                  #if DEBUG
                       @"APP_DEBUG": @(YES),
                  #else
                       @"APP_DEBUG": @(NO),
              #endif
                       @"APP_RCT_DEBUG": @(RCT_DEBUG),
                       @"APP_RCT_DEV": @(RCT_DEV),
              }];
          }

        @end

Note: Please use this code in a project migrating from `react-native-unimodules` to `Expo`

**Comment by Simek** [comment]
Hi @Yandamuri, can you revert all the changes from the mentioned guide and try the steps from Expo FYI guide (http://expo.fyi/expo-modules-migration) instead?

**Comment by Yandamuri** [comment]
Hi @Simek I reverted all the old changes and followed [https://github.com/expo/fyi/blob/main/expo-modules-migration.md](http://expo.fyi/expo-modules-migration). I ended up with following error,

<img width="726" alt="Screenshot 2022-01-15 at 5 22 10 PM" src="https://user-images.githubusercontent.com/31983789/149620885-d39d41f3-d287-4080-b3dc-a82b849e8fd8.png">

I didn't face any error while installing `node_modules` or `pod install`. But facing this error when I ran project from Xcode.

Can you please help me to get rid of this error?

**Comment by byCedric** [comment]
Hi @Yandamuri, please provide a repo for us to help you debug this. With just the error messages, we can't really help you. `EXImageLoader` is a valid dependency and is used in some of the Expo modules. You can [see all references here](https://github.com/expo/expo/search?q=EXImageLoader&type=code).

**Comment by Yandamuri** [comment]
Hi @Simek I reverted all the old changes and followed [https://github.com/expo/fyi/blob/main/expo-modules-migration.md](http://expo.fyi/expo-modules-migration). I ended up with following error,

<img width="726" alt="Screenshot 2022-01-15 at 5 22 10 PM" src="https://user-images.githubusercontent.com/31983789/149620885-d39d41f3-d287-4080-b3dc-a82b849e8fd8.png">

I didn't face any error while installing `node_modules` or `pod install`. But facing this error when I ran project from Xcode.

Can you please help me to get rid of this error?

**Comment by Yandamuri** [comment]
@byCedric Issue got resolved after installing `expo-image-loader`. Thank you for your suggestion.

**Comment by Yandamuri** [comment]
@byCedric after resolving `EXImageLoader` issue I Ama getting `Library not found for -lFolly` error. I didn't understand if it is any `expo` package. 

But I can surely say one thing that, I am facing all these errors after running `npm install expo`  and `expo upgrade 43`(For migrating from `react-native-unimodules` to `Expo`).

What Can I do to get rid of this error?

**Comment by henrymoulton** [comment]
@Yandamuri what did you do to solve these errors?

**Comment by Yandamuri** [comment]
@henrymoulton Which error you are specifically talking about?

**Comment by henrymoulton** [comment]
I wonder if you know what exact issue fixed "Use of undeclared identifier 'EXAppDefines" I'm following the expo FYI guide and still getting it

**Comment by Yandamuri** [comment]
@henrymoulton 
1.Delete current project and create new one(Better clone from old project)

2.Do all necessary changes mentioned the expo FYI guide(http://expo.fyi/expo-modules-migration). Here is the trick I guess(I am not sure). If you have to modify `AppDelegate.m` then go to `ProjectRoot Folder => iOS => <Project Name> => AppDelegate.m.`. which means do not do any changes from Xcode.

3.After doing all changes do `pod install`.

4.Now open Xcode(Don't open Xcode until completing all changes mention in expo FYI guide.) and run project

If doesn't work please your repo then I will look into it.

**Comment by tj-mc** [comment]
I am also facing this issue after following the [Expo Modules](https://docs.expo.dev/bare/installing-expo-modules/) setup guide for a Bare RN app. Unfortunately I can't share the repo.

**Comment by juzer-z** [comment]
Facing the same issue after running `expo upgrade 43` in and Bare RN app

**Comment by alexandrebouttier** [comment]
after having tried many solutions the passage from expo 44 to expo 43 solved this problem for me too, thank you

**Comment by tj-mc** [comment]
> the passage from expo 44 to expo 43 solved this problem for me too
Can you describe more what you mean by this @alexandrebouttier ?

**Comment by Nanle21** [comment]
Any solution for this please?

**Comment by tj-mc** [comment]
@Nanle21 In my case, the parent repository was also named 
`react-native` which confused the `expo_patch_react_imports` script in the Podfile.

**Comment by ygorlf** [comment]
Make sure that react-native-unimodules is not listed in your package.json, I made the migration guide but didn't remove the lib from my dependencies. After that do:

```console
rm -rf node_modules
```

```console
yarn install
```

```console
cd ios && pod install
```

That was my case and its fixed now

**Comment by onedanshow** [comment]
Adding `yarn add expo-modules-core` into `package.json` (instead of as a dependency) cleared this up for me.

**Comment by moemish-uci** [comment]
Thanks @onedanshow, cleared my error too!
