### ISSUE TITLE
expo - problem during first activation

### ISSUE THREAD

**Issue by oron11** [expo/expo#1587]
I downloaded from the website the nodejs and followed the steps from this guide: https://facebook.github.io/react-native/docs/getting-started.html

I downloaded the Expo.client app in the appstore on myiPhone 8plus and using my private lan with my computer.

I'm in the step that I need to press 's' in my computer in order to send to my phone the app(I don't have the possibility to scan Qr code in iPhone). I sent it couple of times by message and email, and when I'm trying to open the link it's open the Expo app and doing: "Opening project..." and than the app just exit by itself.

I have iPhone 8 plus with latest iOS 11.3
Expo.client version 2.4.2

Thanks for everyone!

**Comment by esamelson** [comment]
Hi @oron11 - could you try updating to the latest Expo client (version 2.4.7)? The previous version had some bugs related to opening projects, but they should be fixed now.

Sorry you ran into this!

**Comment by oron11** [comment]
@esamelson I did updtaed the Expo.client version to 2.4.7 now the app doesn't crush, It said to me 
that there is a problem.
I tried also with android phone galaxy Note8, and it said to me that was some problem with the lan, 
All the phones are in the local private lan of my house.

**Comment by EvanBacon** [comment]
@oron11 try running `exp start --tunnel` sometimes LAN can be a pain. If there is an error sometimes it won't print over LAN 😱

**Comment by terribleben** [comment]
Sounds like a connection/tunnel issue. Let us know if you're still having trouble.

**Comment by oron11** [comment]
@EvanBacon How I can use tunnel?
I didn't understand when I need to write this command.

**Comment by ide** [comment]
@oron11 Evan is suggesting you install exp (https://docs.expo.io/versions/latest/workflow/exp-cli) and then run `exp start --tunnel` from your terminal. It will start up a tunnel that gives you a URL that's accessible over the internet.

**Comment by ide** [comment]
Is your project under C:\Users\USER? Usually you'd have it in a subdirectory somewhere.

**Comment by oron11** [comment]
@ide Thank you! now it's working
