### ISSUE TITLE
Is there a migration guide for switching to expo 44 (from expo 43)?

### ISSUE THREAD

**Issue by realtril** [expo/expo#15887]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by dqii** [comment]
https://blog.expo.dev/expo-sdk-44-4c4b8306584a
The breaking changes section would probably be most helpful

**Comment by byCedric** [comment]
Closing as @dqii answered it. Also, in the docs: https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/#sdk-44
