### ISSUE TITLE
[expo-media-library] usePermissions return type definition error

### ISSUE THREAD

**Issue by colinux** [expo/expo#15884]
### Summary

`usePermissions` hook returns a `[status, requestPermission]` with `status` being `null | PermissionResponse` (as indicated in the doc). However the type definition for `status` is only `PermissionResponse`.

https://github.com/expo/expo/blob/fadd71f60b8b429e6602bcb33ee57fb66f07bdc6/packages/expo-media-library/src/MediaLibrary.ts#L437

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 3.1.1 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2022.01.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.15 => 0.16.15
      expo: ^44.0.4 => 44.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.5 => 0.17.5
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

```ts
const [status, requestPermission] = MediaLibrary.usePermissions();
if (status.accessPrivileges === "none") {
   // ...
}
```

Typescript should warn about `status` being possibly `null`, but it's not and this code crashes.

**Comment by byCedric** [comment]
Hi @colinux! This is an interesting type issue, but I'm not sure what's going on yet. In the `createPermissionHook` we use a generic as `PermissionResponse`. That's because some of our libraries add more properties to the permission response, but they do adhere to a basic structure. Here are the current types:

1. The "base" permission hook:
    - Accepts a generic permission response type compatible with the base `PermissionResponse` structure ([source](https://github.com/expo/expo/blob/fadd71f60b8b429e6602bcb33ee57fb66f07bdc6/packages/expo-modules-core/src/PermissionsHook.ts#L30))
    - Because we have no idea of the permission is granted, we default to `null` in the status ([source](https://github.com/expo/expo/blob/fadd71f60b8b429e6602bcb33ee57fb66f07bdc6/packages/expo-modules-core/src/PermissionsHook.ts#L35))
    - The eventual status response type is explicitly combined with `null` ([source](https://github.com/expo/expo/blob/fadd71f60b8b429e6602bcb33ee57fb66f07bdc6/packages/expo-modules-core/src/PermissionsHook.ts#L33))

2. When creating a new permission hook for a module, it inherits the type from the "base" permission hook:
    - This still includes the generic `PermissionResponse | null` type for status ([source](https://github.com/expo/expo/blob/fadd71f60b8b429e6602bcb33ee57fb66f07bdc6/packages/expo-modules-core/src/PermissionsHook.ts#L77-L82))

The types should be correct because of the above inherit chain. One thing I can think of that typescript might not enforce this `null` value because `"strictNullChecks"` is set to false. Can you try setting this to true in your `tsconfig.json`? E.g.

```json
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

**Comment by colinux** [comment]
Hi, you're totally right. The `strictNullChecks` option was missing in the new project I'm working on. There are no problem at all. Sorry for the noise and thanks for your time !

**Comment by byCedric** [comment]
No problem! Always nice to talk about it 😄
