### ISSUE TITLE
Installing expo-gl-ccp provokes a 'NDK is not installed' for android

### ISSUE THREAD

**Issue by medmo7** [expo/expo#15886]
### Summary

I just installed `expo-gl` and `expo-gl-cpp` on my app, but I can't build anymore, I get `NDK is not installed` in android studio.

I installed ndk side by side and cmake in the sdk manager in android studio, and invalidated cache and restarted but the issue is still happening.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

 Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.11.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.0.0 - /usr/local/bin/npm
      Watchman: 2021.10.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: 43.0.0 => 43.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.1
    Expo Workflow: bare

### Reproducible demo

I Just installed the package

**Comment by medmo7** [comment]
Setting the NDK in **Files> Project Structure> Modules> NDK Version** in Android studio resolves the issue, but I wonder why installing a module needs the android settings to be modified

**Comment by byCedric** [comment]
Some modules require extensive and complex compilation methods, `expo-gl` is one of them. They need to be set up in the environment where you built the app. EAS comes preconfigured with an NDK, [and you can even specify the exact version](https://docs.expo.dev/build-reference/eas-json/#ndk).

Closing because this is environment-related.
