### ISSUE TITLE
 Error: Exception in HostObject::get for prop 'NativeUnimoduleProxy': java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Any, js engine: hermes

### ISSUE THREAD

**Issue by nomi9995** [expo/expo#15899]
### Summary

I just migrated to the expo from `react-native-unimodules`. this error is happening only for android when I open app on android.

I also did a patch to `expo-file-system` may be it is due to that patch
https://github.com/expo/expo/issues/15632#issuecomment-1000943427

here is the full error log
```
Error: Exception in HostObject::get for prop 'NativeUnimoduleProxy': java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Any, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

**if I uninstall the app and reinstall the app then this error is gone.**

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28, 29, 30, 31
        Build Tools: 26.0.0, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.0.2 => 9.0.2 
      expo: ^44.0.4 => 44.0.4 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.66.4 => 0.66.4 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

I think it will be reproduced when you will use the same version of RN and expo which I am using.
you have to update the existing app in mobile for reproducing instead of installing fresh APK

**Comment by photorouletteadmin** [comment]
We are also seeing this after migrating from react-native-unimodules to expo-modules. Did you find a solution, @nomi9995?

**Comment by nomi9995** [comment]
@photorouletteadmin no, I did not find any solution, I just uninstall the app and reinstall the app for testing purposes. I am. waiting for new version of `expo-file-system`

**Comment by photorouletteadmin** [comment]
I think it might be the same issue as this one: https://github.com/expo/expo/issues/15924

**Comment by photorouletteadmin** [comment]
I patched in using [patch-package](https://github.com/ds300/patch-package) and this patch (expo-localization+12.0.1.patch):

```
diff --git a/node_modules/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.kt b/node_modules/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.kt
index d93e0d1..edc70f7 100644
--- a/node_modules/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.kt
+++ b/node_modules/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.kt
@@ -24,11 +24,11 @@ class LocalizationModule(context: Context) : ExportedModule(context) {
 
   override fun getName() = "ExpoLocalization"
 
-  override fun getConstants(): Map<String, Any> {
-    val constants = HashMap<String, Any>()
+  override fun getConstants(): Map<String, Any?> {
+    val constants = HashMap<String, Any?>()
     val bundle = bundledConstants
     for (key in bundle.keySet()) {
-      constants[key] = bundle[key] as Any
+      constants[key] = bundle[key] as Any?
     }
     return constants
   }
```

**Comment by yashsway** [comment]
> @photorouletteadmin no, I did not find any solution, I just uninstall the app and reinstall the app to make it run for testing purposes. I am. waiting for the new version of `expo-file-system`

faced the same issue with testing an internal build using android emulator. uninstalling and reinstalling in my emulator worked for me.
