### ISSUE TITLE
Can not sign up

### ISSUE THREAD

**Issue by zjxpcyc** [expo/expo#1589]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please use `exp send` with exp, the “Send” button with XDE, or the "s" hotkey with create-react-native-app to send your project development URL to your phone by SMS or email.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Steps to Reproduce

(Write your steps here:)

1. Open https://expo.io/signup
2. Fill the form
3. Clikc "Create your account"

### Expected Behavior

(Write what you thought would happen.)

Sign up successfully

### Actual Behavior

(Write what happened. Add screenshots!)

There is an error
```bash
An unknown error occurred
```

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by quinlanj** [comment]
Hi @zjxpcyc, sorry you encountered this -- its usually due to the username being taken already. We'll make a point of fixing this in the near future.
