### ISSUE TITLE
Can't get headers to link in detached expo project

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#159]
I read [here](https://docs.expo.io/versions/v16.0.0/guides/expokit.html#ios) that to get headers to be properly linked, you have to link to the headers in the Pods folder (i.e. `Pods/Headers/Public`).

For whatever reason, I still get missing header errors, so I also tried the following in both recursive and non-recursive mode:
`Pods/Headers/Public`
`Pods/Headers/Public/React`
`$(SRCROOT)/Pods/Headers/Public`
`$(SRCROOT)/Pods/Headers/Public/React`
`$(PROJECT_DIR)/Pods/Headers/Public/React`
`$(PODS_ROOT)/Headers/Public`

Am I missing something?

<img width="1406" alt="screen shot 2017-05-07 at 8 59 54 am" src="https://cloud.githubusercontent.com/assets/1566400/25781154/9f31e200-3303-11e7-9ab5-8d10fae68b06.png">

**Comment by terribleben** [comment]
Your screenshot doesn't show which build target you are editing. Make sure you follow the docs instructions with regard to the native dependency's target (e.g. RNFS), rather than for your app's target.

**Comment by JulianKingman** [comment]
Sorry, I didn't mean to cut it off, I attached a full screenshot.

I think that you mean to get the path relative to the root of the linked library, is that right? I'm not very well versed with Xcode, I tried variations like this:
`$(SRCROOT)/../../ios/Pods/Headers/Public`
`$(SRCROOT)/../ios/Pods/Headers/Public`
`$(SRCROOT)/../../../ios/Pods/Headers/Public`

Is that getting on the right track? They didn't seem to work...

<img width="1512" alt="screen shot 2017-05-08 at 2 15 42 pm" src="https://cloud.githubusercontent.com/assets/1566400/25818523/d9ab7be4-33f8-11e7-8e69-924c2ad2009e.png">

**Comment by JulianKingman** [comment]
Even using absolute paths doesn't seem to work:
`/Users/Julian/OneDrive/Meteor/ebook-reader/ios/Pods/Headers/Public/React`

**Comment by terribleben** [comment]
Just to sanity check, does your `Pods/Headers/Public` folder actually contain the react native headers?

**Comment by JulianKingman** [comment]
Yes (under `React`). 

After some trial and error, and careful observation of the library paths (which are annoyingly different in each one), I got rid of the lexical errors (using things like this: `$(SRCROOT)/../../../ios/Pods/Headers/Public`). Now I have an `Apple Mach-O Linker Error`, which is an unfortunately general error that's difficult to debug. Anyway, I solved my initial problem (kind of), do you think I should close this? It might be handy to note in the docs that you don't literally link with `Pods/Header/Public`, but maybe most people know that...

**Comment by terribleben** [comment]
You're right. I'll think about how I can rewrite that paragraph in the docs to be clearer.

If you look over all the logspew that comes alongside the Linker error, there should be more details about which symbols are confusing the linker-- usually either a duplicate symbol or a missing symbol.

I think the best bet is to continue this conversation on the [forums](forums.expo.io) since we are trying to move help topics over there. So feel free to open a topic there and ping me if you want. Sorry linking libs in Xcode generally just an annoying realm... welcome to native land! 😛

**Comment by JulianKingman** [comment]
@terribleben That's why I love expo! I started a topic [here](https://forums.expo.io/t/linking-library-mach-o-linker-error/601).
