### ISSUE TITLE
(SDK 43) Expo Go closes on iOS when choosing a ".pages" document with DocumentPicker.getDocumentAsync() 

### ISSUE THREAD

**Issue by Lucas-Meowtel** [expo/expo#15905]
### Summary

The steps are just two:
1 - Open the document picker
2 - Choose a ".pages" document
And the result is that the Expo Go app closes **immediately** (Both on emulator and physical iPhone).

In the code below it won't even enter into the catch, it crashes at the exact moment I select the document.

It works perfect with all the rest of the extensions and on Android it doesn't crashes.

![Expo Go crashes](https://user-images.githubusercontent.com/86300889/149394950-6fdf5e57-c907-49d6-80cc-666252e17cc0.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.3 - /usr/local/bin/npm
      Watchman: 2022.01.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.5.1 => 8.5.1 
      expo: ^43.0.0 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.35.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

```
<Button
        title="Upload Resume"
        onPress={() => {
          DocumentPicker.getDocumentAsync().then( result => {
            if (result.type === 'success') {
              console.log('Worked!!')
            }
          }).catch( error => {
            throw new Error(error)
          })
        }}
      />
```

**Comment by imagina** [comment]
Same issue here. Any workaround in the meantime?
