### ISSUE TITLE
Upgrading from 42 to 43/44 breaks FCM push notifications

### ISSUE THREAD

**Issue by jezzgoodwin** [expo/expo#15904]
### Summary

We can send push notifications using https://fcm.googleapis.com/fcm/send to our Expo SDK 42 app successfully. When upgrading to 43 or 44, notifications no longer show up, even though the success response from FCM is the same.

Interestingly, on SDK 43 or 44, I can send notifications using the expo notification tool (we save both Expo token and Device token for each user). And I can also send an FCM "notification payload" style message which does show up (but this type of notification cannot be interacted with properly unlike the "data payload" notification which we have been using and which your documentation https://docs.expo.dev/push-notifications/sending-notifications-custom/#fcm-server suggests).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 12.22.8 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^43.0.0 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed
```

### Reproducible demo

Here is an example of the api request we make to FCM:

```javascript
{
	"to": "abcxyz", /* device token retrieved using Notifications.getDevicePushTokenAsync() */
	"priority": "normal",
	"data": {
		"experienceId": "@me/myApp", /* our experienceId in the format "@username/slug" */
		"message": "Here is a message to display on the phone",
		"body": {
			"eventId": 123 /* we use this property for app navigation when the user presses on the notification */
		}
	}
}
```

I am not making any code changes other than upgrading the SDK version.

**Comment by pwfcurry** [comment]
We had the same problem - see https://github.com/expo/expo/issues/15158#issuecomment-1017726258

Also previously this was comparing against `id` in the manifest - it now appears to be checking the `originalFullName` field.

**Comment by jezzgoodwin** [comment]
Thanks @pwfcurry and @randomjunk for this find.

To confirm. Renaming `experienceId ` to `scopeKey` in the api json fixes the issue.

**Comment by jezzgoodwin** [comment]
Closing as a fix has been found and documentaiton updated
