### ISSUE TITLE
"System Events" error when launching IOS simulator

### ISSUE THREAD

**Issue by Nicolas-vrcc** [expo/expo#1590]
Hello,
When I scan the QR code to test my app everything works fine but when I try to run it locally with the IOS simulator I get this error:
`"Error installing or running app. Error: Command failed: osascript -e tell app "System Events" to count processes whose name is "Simulator""`

How to fix this ?

Thanks

**Comment by nikki93** [comment]
Do you have Simulator.app (part of Xcode) installed?

**Comment by terribleben** [comment]
You can also try opening a terminal and running the command yourself to see if you can get clearer error information.

`osascript -e tell app "System Events" to count processes whose name is "Simulator""`

Let us know if you find any other details.

**Comment by daniel** [comment]
I have the same issue. If I start Simulator manually from Xcode (9.4.1) and run this (note: I added single quotes)

`osascript -e 'tell app "System Events" to count processes whose name is "Simulator"'`

I get

`28:69: execution error: System Events got an error: Application isn’t running. (-600)`

**Comment by daniel** [comment]
Restarting Mac fixed the issue.

The issue was also discussed in the Expo forum: https://forums.expo.io/t/unable-to-open-ios-simulator/778/4

**Comment by leimonio** [comment]
Also, note that if you're running script `yarn start` from VSCode might be because VSCode terminal won't have correct permissions. You can try instead terminal.

**Comment by michaelcohen716** [comment]
restarting mac didnt fix issue for me. simulator opens but expo doesn't. any other thoughts on remedy?
