### ISSUE TITLE
App goes blank after Updates.reloadAsync()

### ISSUE THREAD

**Issue by keithschacht** [expo/expo#15911]
### Summary

In order to auto-update, upon launch, our app runs `Updates.checkForUpdateAsync()` and then `Updates.reloadAsync()`. The process typically works. But about 1 out of 10 times the app goes completely white and the user has to kill it and re-launch.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42.0.0

### Environment

Expo CLI 5.0.3 environment info:
  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.14.0
    Yarn: 1.22.5
    npm: 7.7.6
  NpmGlobalPackages:
    eas-cli: 0.43.0
   Expo Workflow: managed

### Reproducible demo

Unfortunately, this is a difficult issue to reproduce. We can’t do updates in development so we are trying to debug this in our staging environment (a mirror of production). Our repro steps are to push a trivial update to Expo, when the build completes, relaunch the app. We have to do it about 10 times before we’ll get a freeze case.

The key code is: App.tsx runs:
```
newUpdate = await checkForAppUpdate()
If (newUpdate) await forceUpdate()
```

And then our library for these two methods is simple:
```
import * as Updates from 'expo-updates'
import {Platform} from "react-native"

export const checkForAppUpdate = async (): Promise<boolean> => {
    if (Platform.OS == "web" || __DEV__) return false
    try {
        const update = await Updates.checkForUpdateAsync()
        return update.isAvailable
    } catch (e) {
        console.error(e)
        return false
    }
}

export const forceUpdate = async () => {
    try {
        const result = await Updates.fetchUpdateAsync()
        if (result.isNew) {
            await Updates.reloadAsync()
        }
    } catch (e) {
        console.error(e)
    }
}
```

**Comment by krschacht** [comment]
Since I haven't gotten any comments on this issue, I'll try promoting this. It's an issue which I'm still stuck on. In my detailed attempts to debug it, I've added lots of logging and confirmed that: the app is successfully querying Expo and learning that there is an update, it's downloading the update (fetchUpdateAsync) and logging the full result object that it gets. But when it hits await Updates.reloadAsync() it's failing in some deep way. The screen is white and killing the app doesn't unstick it. But no exception is being thrown on that line.

**Comment by brentvatne** [comment]
@krschacht - could you try updating your app to sdk 44? happy to help if you can come up with a reproducible example on the latest sdk.

**Comment by keithschacht** [comment]
Yes, I got this solved. I can’t remember the exact specifics but it had to
do with an incompatibility between the binary we had built and the bundled
code that was being downloaded. We changed a plist value or dependency
(something that required a new binary to be built) and there was an issue.
I can’t remember if the binary was updated but the dependency change was
being left out of our bundle build, or the other way around, our bundle was
being built with this but our binary was not being built properly with it.

We debugged by rolling back until we got everything working again and
stepping forward every change on both sides.

**Comment by krschacht** [comment]
This update code in our app is intertwined with initializing the account and a bunch of other init stuff. I removed a bunch of that and am trying to copy & paste some code that should be stand-alone and anonymized a bit. No promises that it will work as-is since I could have broken something in my pasting of pieces. But this should give you a good roadmap to follow. Good luck. I can't help much beyond this:

In App.tsx
```
    useEffect(() => {
        // our app can be in a few different modes, we have some extra checks and only do this once if our app is initializing
        onAppLoad() // async but we are not waiting
    }, [])

    const onAppLoad = async () => {
        try {
            await tryToUpdate() // we also call tryToUpdate in other situations where the app receives a signal from the back-end or when the app is backgrounded & foregrounded, but I'm leaving that code out.
        } catch (error) {
            console.error(error)
            emergencyCheckForUpdates()
            throw error
        }
    }

    const tryToUpdate = async () => {
            if (await checkForAppUpdate()) {
                await forceUpdate()
            }
    }

export const checkForAppUpdate = async (): Promise<boolean> => {
    if (Platform.OS == "web" || __DEV__) return false

    try {
        const update = await Updates.checkForUpdateAsync()
        return update.isAvailable
    } catch (e) {
        // log something
        return false
    }
}

export const forceUpdate = async () => {
    Updates.addListener((e) => {
        // extra logging, log: {
        //   type: e.type,
        //    manifest: (e as any).manifest ?? '',
        //    message: (e as any).message ?? '',
        // }
    })

    try {
        const result = await Updates.fetchUpdateAsync()

        if (result.isNew) {
            await Updates.reloadAsync()
        }
    } catch (e) {
     // log stuff
    }
}

// A pure update function with no dependencies, to be used if app load fails in an attempt
// to recover an unexpected app load exception before the usual update flow.
export const emergencyCheckForUpdates = async () => {
    if (Platform.OS == "web" || __DEV__) return false

    try {
        const update = await Updates.checkForUpdateAsync()
        const isAvailable = update.isAvailable
        if (isAvailable) {
            const result = await Updates.fetchUpdateAsync()
            if (result.isNew) {
                await Updates.reloadAsync()
            }
        }
    } catch (e) {
        console.error(e)
        throw e
    }
}
```

**Comment by mgscreativa** [comment]
Thanks! confirmed I'm doing it right.

**App.tsx**
```
...
...
import { setupUpdates } from './app/hooks';
...
...

export default function App() {
  setupUpdates();
...
...
```

**hooks/setupUpdates.ts**
```
import * as Updates from 'expo-updates';
import { Platform } from 'react-native';
import { useEffect } from 'react';

export default async function setupUpdates() {
  useEffect(() => {
    checkForUpdate()
      .then(() => null)
      .catch(() => null);
  }, []);
}

const checkForUpdate = async () => {
  if (Platform.OS === 'web' || __DEV__) {
    return false;
  }

  try {
    const update = await Updates.checkForUpdateAsync();

    if (update.isAvailable) {
      const result = await Updates.fetchUpdateAsync();

      if (result.isNew) {
        await Updates.reloadAsync();
      }
    }
  } catch (e) {
    console.error(e)
    throw e
  }
};



```
