### ISSUE TITLE
[expo-facebook-login] permissions: [email] not working

### ISSUE THREAD

**Issue by kubilaytural** [expo/expo#15916]
### Summary

I'm trying to `facebook login`  with expo.  I set up `expo-facebook package` after creating an example project.

I followed the document and added the email permission as follows.
`await Facebook.logInWithReadPermissionsAsync({
     permissions: ['public_profile', 'email'],
  })`

But this doesn't work for me. Even though I gave email permission during Facebook login. (Note: name and id are working correctly )

| My facebook login code block |
| -------------| 
|<img width="726" alt="Screen Shot 2022-01-14 at 9 21 10 PM" src="https://user-images.githubusercontent.com/23127307/149565679-44c9206e-b09b-484c-a0f4-323679e22e90.png">|

## Workaround:
I temporarily added the fields I need as parameters to the facebook graph request url. And it worked correctly!

`
const response = await fetch(
        `https://graph.facebook.com/me?fields=id,name,email,birthday&access_token=${token}`)
  `

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
      Watchman: 2021.08.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 31.0.0
        System Images: android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Bug Video
https://user-images.githubusercontent.com/23127307/149564734-8c6812b5-11c6-432c-bfd2-47c9118142dd.mov

**Comment by kubilaytural** [comment]
**MySolution-Workaround:**
I temporarily added the fields I need as parameters to the facebook graph request url. And it worked correctly!

const response = await fetch(https://graph.facebook.com/me?fields=id,name,email,birthday&access_token=${token}`)
`

**Comment by kelley-sharp** [comment]
Hi @kubilaytural! Thanks for reporting this! The call to fetch authenticated user information goes to Facebook and not through expo-facebook, so in your case, where you want data other than the public profile, you would need to provide the fields in your API call. Maybe we should update our docs with links to the [Facebook API docs](https://developers.facebook.com/docs/graph-api/reference/user/#fields) so this solution is more clear. 

Glad you were able to figure this out!
