### ISSUE TITLE
[Android Only] QRcode scan dont work with SDK25&26.

### ISSUE THREAD

**Issue by solonote** [expo/expo#1591]
There are some android phones cannot detect qrcode with SDK 25&26

**Comment by namxam** [comment]
I just tested 25 and 26 on a fairly new android phone with Android 8 and seeing the same issues. Cannot get Camera nor BarcodeScanner to recognise any kind of barcode (1d and 2d).

**Comment by N1ghtly** [comment]
Same problem here... Used to work perfectly.

**Comment by aalices** [comment]
Are you using `ratio` prop? Setting a proper one (when the preview is not distorted) could sometimes solve the issue.

**Comment by solonote** [comment]
Hi, @aalices, I looked into Expo source code and pretty sure it is caused by some devices don't support **com.google.android.gms.vision.barcode** which SDK 25、26、27 using.  And I tested ratio prop and each other prop, not working. Could we just change it back to **com.google.zxing** or provide it as an option? As me know, zxing is a good lib of barcode and it is supported by almost devices. Thanks again!!

**Comment by julien-meichelbeck** [comment]
I'm not using the ratio prop and it does not work with SDK25 : 
```js
        <BarCodeScanner
          onBarCodeRead={this.handleBarCodeRead}
          style={StyleSheet.absoluteFill}
          barCodeTypes={[BarCodeScanner.Constants.BarCodeType.qr]}
        />
```

**Comment by N1ghtly** [comment]
Why is this closed? This is preventing us from launching our app, the barcodescanner is absolutely useless right now.

**Comment by aalices** [comment]
Not sure why the author closed this,  reopening this for now.  I'm planning to create a fallback to `zxing`, hopefully this will be out with next SDK

**Comment by N1ghtly** [comment]
Thanks a lot. What ratio prop are you talking about btw? There seems to be none in the documentation. The preview is not distorted, fwiw.
