### ISSUE TITLE
facebookScheme not used in info.plist

### ISSUE THREAD

**Issue by vliegelientje** [expo/expo#15928]
### Summary

Logging in in iOS with expo-facebook is not working because the value of facebookScheme is not copied to info.plist, yielding an error "fb<app-id> is not registered as a URL scheme. Please add it in your info.plist". Android works fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43.0.0

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 12.21.0 - /usr/bin/node
      npm: 8.1.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ~43.0.2 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

{
  "expo": {
    ..

    "facebookScheme": "fb461103202160564",
    "facebookAppId": "461103202160564",
    "facebookDisplayName": "Duizenden",
    "facebookAutoLogAppEventsEnabled": false,
    "facebookAdvertiserIDCollectionEnabled": false,
..
}

**Comment by JackkFi5h** [comment]
Same issue, did you manage to resolve?

**Comment by marcfrankel** [comment]
Bump as I have the same issue

**Comment by aliexalter** [comment]
I have same issue on device when I use expo build:ios  and then submit archive to TestFlight. On simulator I use expo prebuild to generate ios and android folder then add fb<App ID> under CFBundleURLSchemes and it works fine.
On device it says Safari cannot find URL. How can we copy fb<App ID> on expo managed workflow under CFBundleURLSchemes in iOS builds.

**Comment by Ravnurin** [comment]
Am also experiencing this exact issue on an EAS ad hoc distribution build on iOS

**Comment by marcfrankel** [comment]
So I'll update this with what worked for me. We actually had it set up correctly but for this change to work, we had to delete our Android and iOS folders and then rebuild them (Example: expo run:ios). Seems like some cached build file causes the issue.

**Comment by Exploding** [comment]
This is a workaround that worked for me, using a custom plugin that appends to the CFBundleURLSchemes list in `info.plist`

Create a plugin `withUrlScheme.js`:

```
const withInfoPlist = require("@expo/config-plugins").withInfoPlist;

const withUrlScheme = (config, schemes) => {
  return withInfoPlist(config, (config) => {
    config.modResults.CFBundleURLTypes.push({ CFBundleURLSchemes: schemes });
    return config;
  });
};

module.exports = withUrlScheme;
```

Add plugin to `app.json` plugins array:
```
["./plugins/withUrlScheme", ["YOUR-FB-SCHEME"]]
```

**Comment by Qamarkh** [comment]
@vliegelientje are you able this issue? I have tried all solutions but it's not resolving. The plug-in solution given by @Exploding also not working.
Any help will be appreciated 
Thanks
Qamar

**Comment by aliexalter** [comment]
After running expo prebuild open iOS folder and manually enter values for FB scheme URL in info.plist. Also add it under app.json in last of expo object expo:{ ... facebookScheme: "fb***"}
Then run expo build.

**Comment by Qamarkh** [comment]
> After running expo prebuild open iOS folder and manually enter values for FB scheme URL in info.plist. Also add it under app.json in last of expo object expo:{ ... facebookScheme: "fb***", facebookAppId: "", facebookDisplayName: ""} Then run expo build.
> 
> You can check this working on my app too
> 
> https://apps.apple.com/gb/app/cash-out-simple-expense-track/id1483762315

Hi @aliexalter thanks for quick reply. Great its working the issue I was adding these fields :{ ... facebookScheme: "fb***", facebookAppId: "", facebookDisplayName: ""}  inside infoPlist{} object. By adding inside expo{} object in bottom make the things working 
Thank you very much.
Qamar
