### ISSUE TITLE
[expo-av]  Cannot complete operation because the Video component has not yet loaded

### ISSUE THREAD

**Issue by mtroskot** [expo/expo#15925]
### Summary

I'm using the ref object for loading/unloading videos. While the screen is mounted both of them work, but if the screen unmounts in the useEffect cleanup function an error is thrown ` Cannot complete operation because the Video component has not yet loaded`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
      Watchman: 2021.11.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 26, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@trokiize/video-unload-not-working

**Comment by megantaylor** [comment]
Please re-open, I am seeing these errors on Web a lot. Specifically in the context of Video elements in a FlatList-based carousel, where we have tried to pause the video when its not the centered element, or when the element is unmounted. 

"expo": "50.0.6",
"expo-av": "13.10.5"

**Comment by CavalcanteLeo** [comment]
> Please re-open, I am seeing these errors on Web a lot. Specifically in the context of Video elements in a FlatList-based carousel, where we have tried to stop the video when its not the centered element, or when the element is unmounted.
> 
> "expo": "50.0.6", "expo-av": "13.10.5"

similar to my issue, where I implemented something similar to reels, where I can only see one per time, and I need to stop and unload all the others that is offscreen
