### ISSUE TITLE
[expo-video-thumbnails][bug][ios][sdk44] memory leak / high memory consume lead to quick crash

### ISSUE THREAD

**Issue by Hirbod** [expo/expo#15927]
### Summary

Generating a video thumbnail from a video leads to massive memory consumption without release, causing app to eventually crash.

The consumed memory is in relation to the video format (hd, 2k, 4k). (the bigger the resolution the higher the consumption)
But usually, generation of a single thumbnail creates 10-16MB of memory increase. I don't use any base64 output.
I am generating a lot of thumbnails (since I am building a Camera Video Editing App). After a couple of tries, I reached 1GB of RAM and the app crashed at 1.5GB on my iPhone 13 Max Pro.

I also tried to use FileSystem to remove the generated file (after I've used ImageManipulator, to shrink my thumb size from 4k to 150px). The leak is not caused by ImageManipulator, I've tested that couple of times.

I think that the generated Thumbnail is kept in-memory and does not get released after the thumbnail was generated.
I had to swap to ffmpeg to generate the thumbs.

FFMPEG consumes a fair amount of RAM (30-50MB, depending on video size up to 200MB) of RAM while creating the thumbnail, but it is faster and it will FULLY release the used memory once done.

```tsx
      const outputFile = `${FileSystem.cacheDirectory}VideoThumbnails/${hashCode(path)}.jpg`;
      FFmpegKit.execute(
        `-y -hide_banner -loglevel error -i ${path} -vf "thumbnail" -frames:v 1 -vf scale=150:-2 -q:v 6 ${outputFile}`
      ).then(async (session) => {
        const returnCode = await session.getReturnCode();

        if (ReturnCode.isSuccess(returnCode)) {
          setThumbnail(outputFile);
          currentThumbnail.current = outputFile;
        } else if (ReturnCode.isCancel(returnCode)) {
          // CANCEL
        } else {
          // ERROR
        }
      });
```

While all of this might not be an issue for people generating 1 or 2 thumbnails, the occupied RAM will never be released even for them. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK 44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      react-dom: 17.0.2 => 17.0.2 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

```tsx
      try {
        const { uri } = await VideoThumbnails.getThumbnailAsync(path, {
          quality: 1,
        });
        setThumbnail(uri);
      } catch (e) {
        console.log(e);
      }
```

**Comment by bulgr0z** [comment]
Hi @Hirbod @byCedric , this bug has been present for a few versions already, I fixed it on my end but have been way too busy to submit a proper PR with the patch (sorry).

In `EXVideoThumbnailsModule.m`, the references are never released after use, a call to `CGImageRelease` is missing.

````
  [...]
  NSURL *fileURL = [NSURL fileURLWithPath:newPath];
  NSString *filePath = [fileURL absoluteString];

  // Releasing the image will stop the memory leak from happening.
  CGImageRelease(imgRef);
````
