### ISSUE TITLE
[EAS][Android][SDK 44 Managed] app crashes when opening any modal (including Alert.alert)

### ISSUE THREAD

**Issue by Aryk** [expo/expo#15926]
### Summary

With encouragement from @Kudo I decided to dive into the EAS abyss again and tried to get my app back up to feature parity so I can complete the switch. This time, I was successful in getting the app to compile to APK. 

However, whenever a modal is opened anywhere in my app, including if I use Alert.alert from react-native, the app immediately crashes.

This did not happen before with normal expo build.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.1 - /usr/local/Cellar/node@16/16.13.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/Cellar/node@16/16.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/aryk/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.9 => 0.3.9 
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      expo-cli: 3.11.3
    Expo Workflow: managed

### Reproducible demo

Unfortunately, I don't have one yet, but I was hoping to get this on your guys plate, and I ran adb logcat to show you how it's crashing. It would be extremely time intensive to remove deps and recompile with EAS. Each EAS build takes about 20 minutes to run and I would probably need to do that 20 times, so call it probably 15 hours - 20 hours to maybe debug this. 

Maybe somebody familiar with EAS might be able to give me some pointers where to start or what to look for. 

This is the error:

```
--------- beginning of crash
01-15 19:47:00.242 28538 28608 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-15 19:47:00.242 28538 28608 E AndroidRuntime: Process: com.tribefy.tribefy, PID: 28538
01-15 19:47:00.242 28538 28608 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 't.match'), stack:
01-15 19:47:00.242 28538 28608 E AndroidRuntime: <unknown>@2942:760
01-15 19:47:00.242 28538 28608 E AndroidRuntime: n@2942:1166
01-15 19:47:00.242 28538 28608 E AndroidRuntime: <unknown>@363:1724
01-15 19:47:00.242 28538 28608 E AndroidRuntime: value@30:896
01-15 19:47:00.242 28538 28608 E AndroidRuntime: value@47:3492
01-15 19:47:00.242 28538 28608 E AndroidRuntime: <unknown>@47:747
01-15 19:47:00.242 28538 28608 E AndroidRuntime: value@47:2538
01-15 19:47:00.242 28538 28608 E AndroidRuntime: value@47:719
01-15 19:47:00.242 28538 28608 E AndroidRuntime: value@-1
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
01-15 19:47:00.242 28538 28608 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

```

I followed the EAS migration guide to a "T" (I think), but I'm getting some javascript error somewhere in the native modules: `undefined is not an object (evaluating 't.match')`. I was thinking this was due maybe to a config plugin but all I have is sentry expo:

```
  "plugins": [
      "sentry-expo",
    ],
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "tribefy",
            "project": "tribefy-react-native",
            "authToken": "token"
          }
        }
      ]
    },
```

Again, never saw this before on `expo build` but encountered it on EAS.

Packages are all up-to-date I believe as well. I ran `expo upgrade` yesterday:

```json
  "dependencies": {
    "@cylution/react-native-fake-caret": "^1.0.3",
    "@expo/config-plugins": "^4.0.16",
    "@expo/metro-config": "^0.3.9",
    "@expo/react-native-action-sheet": "^3.10.0",
    "@expo/vector-icons": "^12.0.0",
    "@giautm/react-native-branch": "^0.0.9",
    "@kesha-antonov/react-native-action-cable": "1.0.5",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/datetimepicker": "4.0.0",
    "@react-native-community/hooks": "^2.8.1",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "7.1.3",
    "@react-native-community/slider": "4.1.12",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/material-top-tabs": "^6.0.6",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
    "@sentry/react-native": "^3.2.11",
    "async-mutex": "^0.3.2",
    "axios": "^0.24.0",
    "babel-root-slash-import": "^1.1.0",
    "bluebird": "^3.7.2",
    "chrono-node": "^2.3.1",
    "color": "^3.1.3",
    "crypto-js": "^4.1.1",
    "expo": "^44.0.0",
    "expo-app-loading": "~1.3.0",
    "expo-application": "~4.0.1",
    "expo-asset": "~8.4.6",
    "expo-av": "~10.2.0",
    "expo-blur": "~11.0.0",
    "expo-calendar": "~10.1.0",
    "expo-camera": "~12.1.0",
    "expo-clipboard": "~2.1.0",
    "expo-constants": "~13.0.0",
    "expo-contacts": "~10.1.0",
    "expo-crypto": "~10.1.1",
    "expo-dev-client": "~0.8.0",
    "expo-device": "~4.1.0",
    "expo-face-detector": "~11.1.1",
    "expo-file-system": "~13.1.0",
    "expo-firebase-analytics": "~6.0.0",
    "expo-font": "~10.0.4",
    "expo-haptics": "~11.1.0",
    "expo-image-crop": "^1.0.4",
    "expo-image-manipulator": "~10.2.0",
    "expo-image-picker": "~12.0.1",
    "expo-intent-launcher": "~10.1.0",
    "expo-linking": "~3.0.0",
    "expo-localization": "~12.0.0",
    "expo-location": "~14.0.1",
    "expo-media-library": "~14.0.0",
    "expo-notifications": "~0.14.0",
    "expo-print": "~11.1.0",
    "expo-random": "~12.1.1",
    "expo-sensors": "~11.1.0",
    "expo-sharing": "~10.1.0",
    "expo-sms": "~10.1.0",
    "expo-splash-screen": "~0.14.1",
    "expo-store-review": "~5.1.0",
    "expo-system-ui": "~1.1.0",
    "expo-task-manager": "~10.1.0",
    "expo-updates": "~0.11.4",
    "expo-video-player": "^1.6.1",
    "expo-video-thumbnails": "~6.1.0",
    "expo-web-browser": "~10.1.0",
    "firebase": "8.2.3",
    "global": "^4.4.0",
    "haversine": "^1.1.1",
    "humanize-duration": "^3.27.0",
    "invert-color": "^2.0.0",
    "libphonenumber-js": "^1.7.30",
    "lodash": "4.17.11",
    "lottie-react-native": "5.0.1",
    "luxon": "^1.21.3",
    "mobx": "^5.15.1",
    "mobx-react": "^6.1.4",
    "mobx-state-tree": "^3.15.0",
    "mst-gql": "^0.10.0",
    "mst-persist": "^0.1.3",
    "nanoid": "^3.1.12",
    "native-base": "2.13.15",
    "patch-package": "^6.4.7",
    "pluralize": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-appearance": "~0.3.3",
    "react-native-branch": "^5.2.1",
    "react-native-canvas": "^0.1.37",
    "react-native-copilot": "^2.5.1",
    "react-native-deck-swiper": "^2.0.5",
    "react-native-error-boundary": "^1.1.1",
    "react-native-fast-image": "^8.5.11",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-google-places-autocomplete": "^2.3.0",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-progress": "^1.1.1",
    "react-native-interactive-walkthrough": "^1.0.12",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-map-link": "^2.8.1",
    "react-native-modal": "^13.0.0",
    "react-native-modal-datetime-picker": "^13.0.1",
    "react-native-pager-view": "5.4.9",
    "react-native-parsed-text": "^0.0.22",
    "react-native-picker-select": "^6.3.4",
    "react-native-progress": "^5.0.0",
    "react-native-qrcode-svg": "^6.0.6",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-snap-carousel": "4.0.0-beta.6",
    "react-native-sortable-grid-with-fixed": "^2.1.0",
    "react-native-super-grid": "^4.1.3",
    "react-native-svg": "12.1.1",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-tab-view": "^3.1.1",
    "react-native-tiny-toast": "^1.0.7",
    "react-native-toast-message": "^1.4.9",
    "react-native-webview": "11.15.0",
    "sentry-expo": "^4.0.0",
    "throttle-debounce": "^2.1.0",
    "typescript": "~4.3.5",
    "uuid": "^8.3.2"
  }
```

**Comment by byCedric** [comment]
Hi @Aryk! I'm not sure if we can help much with these stack traces, they aren't pointing to something specific other than "You have a JS type error". One thing you could try is creating a build outside EAS. The main difference between `expo build` and `eas build` is that `eas build` ejects your project before building it. You can do that locally too, but without minifying the JS code 😄 

If you could share the stack trace on Android when you run the following commands, that would be helpful:

- `$ git checkout -b throwaway` (just to be able to revert everything easily, up to you)
- `$ expo run:android --device` (connect your device before running this)
- `$ adb logcat`

**Comment by Aryk** [comment]
Hey @byCedric, thanks for steering me in the right direction. That made it **MUCH** easier to resolve.

Getting `expo run:android --device` working was sort of a pain as I documented [here](https://github.com/expo/expo/issues/15199#issuecomment-1016245855).

However, I found the issue. Apparently in the new version on EAS, when you use `AppState.addEventListener("focus", focusListener);` for Android, you guys pass through undefined for the appState bc it's not considered a change.

In the past, I believe Expo would pass through the current value or atleast pass through a string. That's why it would blow up when a modal showed bc the appstate was "blurred".

**Comment by Zolboo05** [comment]
@Aryk How can I solve this issue on my code? Modal appear when expo notification received. Then after that app crashes. I do expo upgrade and change SDK 43 to SDK 44 and it's still crash. I have changed change Modal library but It's still crashing. Do you have any idea?

**Comment by Aryk** [comment]
Use adb logcat to see how the crash is happening. Then from the stack trace we can start narrowing it down... from my stack trace you can see the t.match error so there was some kind of string matching that it was trying to do but then blowing up...

**Comment by bkamrani** [comment]
Just a tip: do you have any fix or patch in your `node_modules` directory which is applied manually after the traditional build? In that case, this should be implemented as `postinstall` script in `package.json` so that EAS build applies it. 

This was the cause of the crash in my case, where I needed to change the following in `/node_modules/react-native-safe-area-view/index.js` after the build. 
`this.view._component.measureInWindow` **--->** `this.view.getNode().measureInWindow`

Defining this change as a `postintall` took care of it.
