### ISSUE TITLE
initBarcodeScanner$lamda-3(...) must not be null

### ISSUE THREAD

**Issue by unit-002** [expo/expo#15933]
### Summary

just migrated to expo modules and upgraded my expo-camera from 11.2.2 to 12.0.3.

I tested it with the example on the documentation but I'm still getting this error I am not even using a barcode scanner.
Build is successful and there is no error on the console.

![image](https://user-images.githubusercontent.com/79749223/149717864-22910d0b-72c2-4163-bdbf-2513b7e59429.png)

How do I fix this?
thanks.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

I also upgraded the expo dependencies
```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.15",
    "expo": ">=44.0.0-0 <45.0.0",
    "expo-asset": "^8.4.6",
    "expo-camera": "^12.0.3",
    "expo-constants": "^13.0.0",
    "expo-file-system": "^13.2.0",
    "expo-gl": "^11.1.1",
    "expo-gl-cpp": "^11.1.0",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-fs": "^2.18.0",
},
```

### Reproducible demo

I used the sample code in the documentation

```
import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { Camera } from 'expo-camera';

export default function App() {
  const [hasPermission, setHasPermission] = useState(null);
  const [type, setType] = useState(Camera.Constants.Type.back);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestCameraPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (hasPermission === null) {
    return <View />;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }
  return (
    <View style={styles.container}>
      <Camera style={styles.camera} type={type}>
        <View style={styles.buttonContainer}>
          <TouchableOpacity
            style={styles.button}
            onPress={() => {
              setType(
                type === Camera.Constants.Type.back
                  ? Camera.Constants.Type.front
                  : Camera.Constants.Type.back
              );
            }}>
            <Text style={styles.text}> Flip </Text>
          </TouchableOpacity>
        </View>
      </Camera>
    </View>
  );
}
```

**Comment by byCedric** [comment]
Hi @unit-002, it looks like something went wrong during migration with the newer module registry. If [this is `null`](https://github.com/expo/expo/blob/sdk-44/packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.kt#L181), the registry isn't properly set.

Can you share a repository with the code you are using that triggers this issue? The package.json you mentioned also contains mixed versions for older SDKs, I would recommend running `expo upgrade 44` to make sure all dependencies are also updated for this Expo SDK.

**Comment by unit-002** [comment]
I am using react native cli, how do i expo upgrade with this? and currently I am using the sample code below to test the camera.

**Comment by unit-002** [comment]
Ok now I found out what's causing this error.

similar issue in this post #15547, I tried what they did and it works.

I have to install `expo-barcode-scanner` even thought I'm not going to use it, just so to make the null error go away.
which also gives my file an additional 20mb of size. 

I have too many unused dependencies.

**Comment by TomCorvus** [comment]
I have the same problem since `expo-camera: ~12.1.0`.
I tried to install `expo-barcode-scanner` and I have this error:
![Screenshot_1642501342](https://user-images.githubusercontent.com/3451011/149921207-b73c5788-cd70-428e-8db4-787f7a468575.png)

Then I installed `expo-face-detector`. There is no crash when the camera is launching but I have this error when I try to take a picture:
![Screenshot_1642502259](https://user-images.githubusercontent.com/3451011/149921407-2561e7ff-c9ac-4c4c-a85e-42c80f6b754d.png)

**Comment by unit-002** [comment]
I added this one on my android/build.grade because I was having error with my build before. Don't know if this will help.

android/build.grade 
```
dependencies {
  .
  .
  classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10"

}
```

**Comment by TomCorvus** [comment]
https://github.com/expo/expo/pull/16167 fixes this.
@unit-002 you can close this issue I think.

**Comment by yonitou** [comment]
Hi,

Sorry but I just installed expo-camera@12.1.2 on my app (running on expo 44) and I'm still having the same issue : when sending the app from background to foreground with a screen using camera, it will crash on Android.

The bug is still present. Do you have any more infos ?

**Comment by TomCorvus** [comment]
@yonitou Did you set Kotlin Gradle plugin in `android/build.grade`?

**Comment by yonitou** [comment]
@TomCorvus nope, never touched it.

**Comment by TomCorvus** [comment]
@yonitou try to set it in `android/build.grade`, it maybe fix your problem.
I know that I had to set it to fix build error on Android.

**Comment by unit-002** [comment]
> Hi,
> 
> Sorry but I just installed expo-camera@12.1.2 on my app (running on expo 44) and I'm still having the same issue : when sending the app from background to foreground with a screen using camera, it will crash on Android.
> 

I've read somewhere that expo-camera@12.1.X and higher only works with react native ver 0.65 and higher so if  you are using versions below that this error will appear. That is why I downgraded mine to 12.0.3 since I'm using RN ver 0.63

**Comment by yonitou** [comment]
Hi @unit-002 , 

Thanks for your answer. This is really weird since `expo@44` didn't upgrade the RN ver to 0.65 (I'm up-to-date and my RN version is stuck at 0.64.3)

Why would them fix a bug in a version that is not compatible with the actual RN version ?

**Comment by unit-002** [comment]
> Hi @unit-002 ,
> 
> Thanks for your answer. This is really weird since `expo@44` didn't upgrade the RN ver to 0.65 (I'm up-to-date and my RN version is stuck at 0.64.3)
> 
> Why would them fix a bug in a version that is not compatible with the actual RN version ?

Not sure why either.
