### ISSUE TITLE
Whitescreen by importing useState (Only in Prod. mode with minify)

### ISSUE THREAD

**Issue by konipro** [expo/expo#15930]
### Summary

Hi,

my app does not launch in **production mode** (whitescreen).
In dev mode, or production mode without '--minify' everything works perfectly. 

I found the source. However, this one does not make sense to me.

When I run the import as follows, the app does not work:
```
import React, { useEffect } from "react"
function EntiresOverviewPage() {
    return <Text>123</Text>
}
export default EntiresOverviewPage
```

This is how the app works:
```
import React from "react"
function EntiresOverviewPage() {
    return <Text>123</Text>
}
export default EntiresOverviewPage
```

Elsewhere in the app I use the exact same syntax to impose 'useState' I have the same problem with 'useEffect'.

Unfortunately I do not get on at all, and hopes someone can help me. 
Thanks for your help!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

Hi,

my app does not launch in **production mode** (whitescreen).
In dev mode, or production mode without '--minify' everything works perfectly. 

I found the source. However, this one does not make sense to me.

When I run the import as follows, the app does not work:
```
import React, { useEffect } from "react"
function EntiresOverviewPage() {
    return <Text>123</Text>
}
export default EntiresOverviewPage
```

This is how the app works:
```
import React from "react"
function EntiresOverviewPage() {
    return <Text>123</Text>
}
export default EntiresOverviewPage
```

Elsewhere in the app I use the exact same syntax to impose 'useState' I have the same problem with 'useEffect'.

Unfortunately I do not get on at all, and hopes someone can help me. 
Thanks for your help!

**Comment by byCedric** [comment]
The code you provided should crash in both cases, it's missing an import for `<Text>`. I'm not sure how you set up your project, but this should be the right code:

```js
import React from 'react';
import { Text } from 'react-native';

function EntiresOverviewPage() {
    return <Text>123</Text>
}

export default EntiresOverviewPage
```

You should be able to use `import React, { useEffect } from 'react';` with the default Expo project configuration.

Hope this helps

**Comment by konipro** [comment]
Hi Cedric, 
thanks for your help.

I have imported 'Text' of course. Somehow it got dropped in the code example. Sorry for that.

Unfortunately I am not allowed to publish the source code, which files do you need?

**Comment by konipro** [comment]
Four of us have looked over it. Over 10 hours. I'm sure it's because of the imports. More precisely, when minifying the imports. 

Here's a Video: https://www.youtube.com/watch?v=EuJisISWw2Q

**Comment by konipro** [comment]
Jesus. I am the happiest programmer.

- The minifyn the variables are renamed e.g. 'LoginPage' becomes "a".
- My navigator mapped the screens. 
- When mapping I used the var name as ScreenName
- In Dev mode my 'LoginPage' is then called e.g. 'LoginPage', in Prod. mode it is not.
- How the variable is called later, and which routes don't work then, is not predictable.
