### ISSUE TITLE
[expo-image-picker] update image cropper android library

### ISSUE THREAD

**Issue by n0mer** [expo/expo#15931]
### Summary

https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8 - "Android-Image-Cropper" used in expo-camera is not maintained since 2018. There is alternative fork: https://github.com/CanHub/Android-Image-Cropper/

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

n/a

### Reproducible demo

https://github.com/CanHub/Android-Image-Cropper/

**Comment by cemo** [comment]
JCenter is down and this is not enhancement anymore. This must be resolved as quickly as possible.

**Comment by EesaJacobs** [comment]
I've experienced this issue in a bare react native project that includes Expo SDK Components (Image Picker being one). The issue is not experienced on iOS (12+) but experienced on Android. @yvbeek's answer #14391 worked for now.

**Comment by hemantmanchanda63** [comment]
I am facing an issue with the expo-image-picker while selecting an image. I need to send the selected image to an API. It works fine on iOS, but on Android, the image resolution increases 10 times, causing issues. Below, I have attached the code for reference.

` export const openPicker = async (
  options: ImagePicker.ImagePickerOptions,
  width?: number,
  height?: number
): Promise<ImagePicker.ImagePickerAsset[]> => {
  const { granted } = await ImagePicker.requestMediaLibraryPermissionsAsync();
  if (!granted) {
    throw new Error("Permission to access the media library is required.");
  }

  const result = await ImagePicker.launchImageLibraryAsync({
    mediaTypes: ImagePicker.MediaTypeOptions.Images,
    allowsMultipleSelection: true,
    ...options,
  });
  if (result.canceled) {
    return [];
  }


  if (width && height) {
    // Resize the selected images if width and height are provided
    const resizedImages = await Promise.all(
      result.assets.map(async (asset) => {
        const manipulatedImage = await ImageManipulator.manipulateAsync(
          asset.uri,
          [{ resize: { width, height } }],
          { compress: 1, format: ImageManipulator.SaveFormat.JPEG }
        );
        return {
          ...asset,
          uri: manipulatedImage.uri,
        };
      })
    );
    return resizedImages;
  } else {
    return result.assets;
  }
}; `
