### ISSUE TITLE
getCurrentPositionAsync() returns location which is far from actual location

### ISSUE THREAD

**Issue by Yandamuri** [expo/expo#15948]
### Summary

I am using `Location.getCurrentPositionAsync()` with `accuracy 6` to get the accurate location. But when I try to ge the current location I am getting the location which is almost 1KM or sometimes more than 1KM far from current location. And this is happening frequently. If we think `getCurrentPositionAsync()` is giving `cached` location , But I have never been to that location.

<img width="1029" alt="Screenshot 2022-01-18 at 11 55 31 AM" src="https://user-images.githubusercontent.com/31983789/149882728-0610833b-85fb-4690-816f-861981337e8e.png">
(This issue is raised in Android devices only)

The above screen is a reference to show the difference between actual location and fetched location.

1. Does `Location.getCurrentPositionAsync()` uses `Google Maps`  or `Apple Maps` to fetch location? if so why the **Fetched Location** and **Actual Location** are different(Please check above attached screen)?

2. If `Location.getCurrentPositionAsync()` doesn't use  the `Google Maps`  or `Apple Maps`, Then May I know how location fetching process is happening?

3. Are there any chances that `Location.getCurrentPositionAsync()` returns `cached` location even though **accuracy** is set to **6**?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

      Expo CLI 5.0.3 environment info:
     System:
         OS: macOS 11.6
         Shell: 5.8 - /bin/zsh
    Binaries:
         Node: 14.0.0 - /usr/local/bin/node
         npm: 6.14.4 - /usr/local/bin/npm
    Managers:
        CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
        iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
        Android Studio: 4.2 AI-202.7660.26.42.7351085
        Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
        expo: >=44.0.0-* <45.0.0 => 44.0.4 
        react: 17.0.1 => 17.0.1 
        react-native: 0.64.0 => 0.64.0 
     npmGlobalPackages:
        expo-cli: 5.0.3
     Expo Workflow: bare

### Reproducible demo

     Location.getCurrentPositionAsync({
		accuracy: 6
      }).then(currentPosition => {
		console.log('Current Posiiton', currentPosition);
      });

From the above console.log we can get `latitude, longitude` which we can compare with actual coordinates form **Google Maps**

**Comment by brentvatne** [comment]
we use the underlying platform apis, the result can only be as good as what we are given from ios and android operating systems.
