### ISSUE TITLE
aztec qr code scanner stops reading after \0

### ISSUE THREAD

**Issue by AdriDevelopsThings** [expo/expo#15940]
### Summary

When you try to scan an aztec code with the expo barcode scanner and the aztec code contains a \0x00 the barcode scanner stops scanning.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

```javascript
import { BarCodeScanner } from 'expo-barcode-scanner';
import { useEffect, useState } from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
import { Buffer } from 'buffer'

export default function App() {
  const [hasPermission, setHasPermission] = useState<boolean|null>(null)
  const [scanned, setScanned] = useState(false)

  useEffect(() => {
    (async () => {
      const { status } = await BarCodeScanner.requestPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  const handleBarCodeScanned = (data: any) => {
    setScanned(true);
    console.log(Buffer.from(data.data, 'utf-8').toString('hex')) // the code until \x00 will be logged
    alert(JSON.stringify(data))
  };

  if (hasPermission === null) {
    return <Text>Requesting for camera permission</Text>;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }

  return (
    <View style={styles.container}>
      <BarCodeScanner
        onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
        style={StyleSheet.absoluteFillObject}
      />
      {scanned && <Button title={'Tap to Scan Again'} onPress={() => setScanned(false)} />}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```
You can try it with this qr code (it contains a \x00 byte):
![muster pdf-003 pbm](https://user-images.githubusercontent.com/45321107/149831639-0898fe11-7c84-47dd-9f2e-cc392a37a25d.png)

**Comment by AdriDevelopsThings** [comment]
On android, there is a similar problem: If you run the code on android and scan the code, you will get `#UT010080000070,Unknown encoding` as data. So binary data in Aztec codes are not scannable on android because the data is not decodeable. Maybe a binary barcode data option is necessary.

**Comment by AdriDevelopsThings** [comment]
The problem isn't solved?

**Comment by animaonline** [comment]
Any updates?
