### ISSUE TITLE
Cached images show up blank after updating app version via testflight 

### ISSUE THREAD

**Issue by dereknelson** [expo/expo#1594]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/prodigynelson-c8a88d49-fa11-4f5d-8ff3-5e8b39fbc2f0.tar.gz

iOS Standalone

### Steps to Reproduce

My code works fine until I update standalone via testflight. 
In my app.js, I have this code: 
`async componentWillMount(){`
`        const folder = '${FileSystem.documentDirectory}metoo';`
`        var folderInfo = await FileSystem.getInfoAsync(folder);`
`        if (!folderInfo.exists) await FileSystem.makeDirectoryAsync(folder);`
 `   }`
Gist of related code: https://gist.github.com/dereknelson/cfd249dea35014fef540f4203b96b6e3

### Expected Behavior
I expected the images to load without issue like they had every time in the past.

### Actual Behavior
Images are blank: [how they should look](http://prntscr.com/izwlp8) vs [how they actually look](http://prntscr.com/izwnpr).
Note, if I publish with code that purges the local cache and starts over, the images will cache again and work until I update the version on testflight.

### Reproducible Demo
I can't seem to reproduce this in the expo app as it only occurs when I update the standalone version.

**Comment by nikki93** [comment]
Can you check `.getInfoAsync(...)` on an individual image after the update to see if those files still exist? BTW, you are using `local: downloaded.uri` (https://gist.github.com/prodigynelson/cfd249dea35014fef540f4203b96b6e3#file-notdumbimageactions-js-L32) but I think you want to do `downloaded.fileUri` (check the returned values at https://docs.expo.io/versions/latest/sdk/filesystem#expofilesystemdownloadasyncuri-fileuri-options).

**Comment by prodigynelson** [comment]
@nikki93 how would I get the result of the getInfoAsync() in a standalone? Also, I use downloaded.uri because that's what returned by [downloadAsync()](https://user-images.githubusercontent.com/6868432/38220762-0ac79ff0-36aa-11e8-9452-b5798bb298cd.png)

**Comment by prodigynelson** [comment]
@nikki93 I logged the error via sentry, and [it would seem that the file still exists](https://user-images.githubusercontent.com/6868432/38221044-8fcd78ea-36ab-11e8-8a38-74077743fa03.png)

**Comment by nikki93** [comment]
Regarding `downloaded.uri` --> you are right, sorry about that one. Will investigate the actual standalone download issue.

**Comment by prodigynelson** [comment]
@nikki93 no worries, there was definitely room for misconception. Looking forward to finding out what the issue is, do you have any ideas for a temporary workaround? I want to publish something that purges the cache only after it's been updated but I haven't come up with a way that definitely purges the cache once and only once, and only after it's been updated

**Comment by ewein** [comment]
I am also having this issue, seems images stored at `Expo.FileSystem.documentDirectory` are blank after doing an update from the App Store as well.

**Comment by prodigynelson** [comment]
@ewein in the mean time, a slightly hacky and imprecise workaround: I use redux to manage cache, and after I submit a new bundle, I set something that purges the cache. To start, I made a property called "purgedCache" and set it to false, and if it was false, purge the cache. 

I've had to do it more than once, so I update the name in my reducer to purgedCacheV2, V3 and so on. Like I said, it's imprecise because I haven't found a way to ensure that it only purges the cache if the standalone version is updated but it's better than your users not having images.

**Comment by nikki93** [comment]
If you can still test both versions, can you print the value of “`Expo.FileSystem.documentDirectory`” in each case?

**Comment by prodigynelson** [comment]
@nikki93 will get to testing it, however in the meantime think this may be pertinent information: a solution I've found is resetting my cache in the [store](http://i.prntscr.com/iZbibme0RsGKO9ZGTGEVyg.png) to its initial state: the way I decide to download an image is based on if it's not currently being downloaded, or if it's already downloaded. 

It's almost always the same image link, which would result in the same [hash computed](https://gist.github.com/prodigynelson/cfd249dea35014fef540f4203b96b6e3#file-notdumbimageactions-js-L14), therefore downloading to the [same filepath](https://gist.github.com/prodigynelson/cfd249dea35014fef540f4203b96b6e3#file-notdumbimageactions-js-L19). If a file already existed at that filepath, I'd imagine that downloading a new image would not work, correct?

Will update with results of seeing the value of document directory, but I have to submit a new bundle to apple to test so it may be a day or two.

**Comment by prodigynelson** [comment]
@nikki93 if by `Expo.FileSystem.documentDirectory` you meant "readDirectoryAsync", the directory still contains the files that were downloaded. After purging the cache and downloading the pictures again, the array of files in the directory is still the same length, however, the images are displayed again.

**Comment by ewein** [comment]
Has this been fixed?

**Comment by dereknelson** [comment]
@nikki93 hey, any progress? Is there anything else I can try to test to speed this along?

**Comment by dereknelson** [comment]
@esamelson hi, sorry for the late reply - that is exactly what happens, and when I append the path to documentDirectory at runtime it works fine. Thanks for clearing that up!

How should I go about requesting a change to the document directory docs to make that clear? As it stands, it says:

> file:// URI pointing to the directory where user documents for this app will be stored. Files stored here will remain until explicitly deleted by the app. Ends with a trailing /. Example uses are for files the user saves that they expect to see again.

Specifically, "Files stored here will remain until explicitly deleted by the app" is what caused my confusion, as I couldn't find any other references to the documentDirectory path changing after updates.

**Comment by dereknelson** [comment]
For anybody coming across this thread in the future, all you have to do is append your filepath to the document directory link. For me, that looks like this: 

```
const folder = `${FileSystem.documentDirectory}yourPath`;

//inside of a class or function
const { local, source, style } = this.props
const hash = md5(source.uri)
const split = source.uri.split('.')
const type = split[split.length - 1]

//appending directory
const filepath = `${folder}/${hash}.${type}`;

return (
    <Image style={style} source={{ uri: file }}/>
);
```
