### ISSUE TITLE
Ignoring TextInput keyboardType in web target on iPad in Safari

### ISSUE THREAD

**Issue by karatekid430** [expo/expo#15947]
### Summary

1. `expo init` and create new blank project (currently Expo 44)
2. App.js to be `import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, TextInput, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <TextInput keyboardType="number-pad" style={styles.textInput} />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textInput: {
    width: 300,
    height: 80,
    borderWidth: 1,
  },
});`
3. `yarn start`
4. Press run in web browser
5. Go to iPad Simulator, open Safari, `localhost:19006`
6. In toolbar in MacOS go I/O, Hardware, and deselect `Connect hardware keyboard`
7. Tap in the text input in the Expo app
8. Observe how keyboard is not numeric

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.2 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.20.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 25, 27, 28, 29, 30
        Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-21 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, TextInput, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <TextInput keyboardType="number-pad" style={styles.textInput} />
      <StatusBar style="auto" />
    </View>
  );
}

// Note now on iPad in Safari, the keyboard is not a number pad, whether we change keyboardType to "numeric" or "number-pad"

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textInput: {
    width: 300,
    height: 80,
    borderWidth: 1,
  },
});

**Comment by karatekid430** [comment]
Okay GitHub is messing with the code so I cannot provide code sample. Wonder if it will let me attach a file

**Comment by karatekid430** [comment]
https://pastebin.com/ArD9xGru code example

**Comment by Shing-Ho** [comment]
Provide a snack.
