### ISSUE TITLE
[expo-updates] Failed to download new update on ios

### ISSUE THREAD

**Issue by thanhchuongbmd** [expo/expo#15946]
### Summary

When call fetchUpdateAsync() function, it throw exception with message "Failed to download new update" on ios. Android work ok!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.23.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.3.0 => 8.3.0 
      expo: ^42.0.0 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

_checkUpdates = async () => {
    try {
      const update = await Updates.checkForUpdateAsync();
      if (update.isAvailable) {
        await Updates.fetchUpdateAsync();
      
      }
    } catch (e) {
      console.log("Error while trying to check for updates", e);
    }
  };

**Comment by dedan** [comment]
I'm experiencing the same issue

**Comment by thanhchuongbmd** [comment]
> Hi @dedan and @thanhchuongbmd, did any of you find I solution?

I'm using code-push

**Comment by luisflorido** [comment]
This issue is still happening, any updates?

**Comment by thanhchuongbmd** [comment]
I has removed ios folder and eject again. It's work ok.

**Comment by RohitKaushal7** [comment]
Update working fine on android but says "failed to download new update" on iOS.
