### ISSUE TITLE
 Unable to find a specification for `ExpoModulesCore` depended upon by `EXApplication`

### ISSUE THREAD

**Issue by MEsteves22** [expo/expo#15959]
### Summary

Since upgrading expo to SDK 44, I get the following error while running `pod install --repo-update`:

` Unable to find a specification for ExpoModulesCore depended upon by EXApplication`

I also upgraded all the other expo packages I was using. I am currently using the following packages and versions:
- expo: 44.0.5
- expo-keep-awake: 10.0.1
- expo-notifications: 0.14.0
- expo-secure-store: 11.1.0

I am using react-native version 0.67.0.

Is someone also having this problem?

Thank you!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 437.14 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Reproducible demo

I get the error while running `pod install --repo-update`.

**Comment by byCedric** [comment]
Hi @MEsteves22, please provide a repository for us to test with. `expo-modules-core` is a direct dependency of `expo` ([source](https://github.com/expo/expo/blob/master/packages/expo/package.json#L77)). So, if that's not installed, I would recommend reinstalling your `node_modules` again. But, without a repo, that's the only thing I can do for you.

Hope it helps!

**Comment by MEsteves22** [comment]
Thank you for your answer! 

Sorry for not providing a repo, I didn't think it was needed.

I will do what you suggested :)

**Comment by mendesbarreto** [comment]
> Thank you for your answer!
> 
> Sorry for not providing a repo, I didn't think it was needed.
> 
> I will do what you suggested :)

@MEsteves22 Do you were able to fix this error? because I am having the same problem 🥲

**Comment by MEsteves22** [comment]
@mendesbarreto I solved my problem by deleting my project from my computer and cloning it again 😅 Then, I reinstalled all my `node_modules` and pods. After that, it started to work.

**Comment by samih7** [comment]
@mendesbarreto Were you able to get it sorted out? I'm also having the same issue and removing `node_modules` + `Pods` didn't help

**Comment by pe-johndpope** [comment]
npm i -g npm@latest

/Users/johndpope/.nvm/versions/node/v14.19.0/bin/npm -> /Users/johndpope/.nvm/versions/node/v14.19.0/lib/node_modules/npm/bin/npm-cli.js
/Users/johndpope/.nvm/versions/node/v14.19.0/bin/npx -> /Users/johndpope/.nvm/versions/node/v14.19.0/lib/node_modules/npm/bin/npx-cli.js
+ npm@8.5.2
added 67 packages from 18 contributors, removed 294 packages and updated 143 packages in 3.334s

I'm running node 14 and seeing same problem - if that helps. going to bump to later version.

**Comment by tibbe** [comment]
Next up, trying to raise the minimum iOS version:

```
% git diff ios/Podfile
diff --git a/app/ios/Podfile b/app/ios/Podfile
index 41c2d50..4ec49bf 100644
--- a/app/ios/Podfile
+++ b/app/ios/Podfile
@@ -1,7 +1,7 @@
 require_relative '../node_modules/react-native/scripts/react_native_pods'
 require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 
-platform :ios, '11.0'
+platform :ios, '12.0'
 install! 'cocoapods', :deterministic_uuids => false
 
 target 'benetics' do
```

**Comment by mharlowfod** [comment]
Just wanted to leave a comment here if anyone is seeing similar issues relating to Expo, ExpoModulesCore, and cocoapods configuration: @pe-johndpope 's fix above did resolve my pod install failures, and specifically it was the following two linges:

`require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")`

and

`use_expo_modules!`

For reference, the reason I ended up in a weird state was due to the fact that expo doesn't seem to have an option to generate the iOS and Android directories for new projects. So I was copy-pasting projects into an expo project, but didn't have the boilerplate necessary podfile to make everything work. I'm probably missing something in that process as well - I'd be curious to see any documentation or howtos that are out thre.

**Comment by tj-mc** [comment]
In my case I faced this error when integrating Expo Modules to a Bare RN `0.67.2` Project. However, the project is a monorepo with multiple targets in the Podfile. This custom structure meant the auto patch failed.

I added this snippet (from the setup guide) to the very end and everything works now.

```
use_expo_modules!

post_integrate do |installer|
  begin
    expo_patch_react_imports!(installer)
  rescue => e
    Pod::UI.warn e
  end
end
```

**Comment by focux** [comment]
In case anyone runs into the same issue as me, my problem was that I created a monorepo and forgot to add a `package.json` on the root folder of the workspace. I guess Expo uses that under the hood to get the root `node_modules` for the hoisted dependencies.

**Comment by estebanjb1989** [comment]
In my case I've had to add `use expo_modules!` and worked

**Comment by Michael-Davison** [comment]
getting a similar error.

[!] Unable to find a specification for `EXUpdatesInterface` depended upon by `EXUpdates`
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
pod exited with non-zero code: 1

None of the solutions posted here have worked.

**Comment by doender** [comment]
> getting a similar error when I run eas build -p ios expo managed app.
> 
> [!] Unable to find a specification for `EXUpdatesInterface` depended upon by `EXUpdates` You have either:
> 
> * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.
>   pod exited with non-zero code: 1
> 
> None of the solutions posted here have worked.

@Michael-Davison I'm running into the the same error. Did you find a fix for this?

**Comment by munroAllie** [comment]
> > getting a similar error when I run eas build -p ios expo managed app.
> > [!] Unable to find a specification for `EXUpdatesInterface` depended upon by `EXUpdates` You have either:
> > 
> > * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> > * mistyped the name or version.
> > * not added the source repo that hosts the Podspec to your Podfile.
> >   pod exited with non-zero code: 1
> > 
> > None of the solutions posted here have worked.
> 
> @Michael-Davison I'm running into the the same error. Did you find a fix for this?

I have this issue after updating my packages. Any fix found yet?

**Comment by Dat-Mobile** [comment]
run this command and it's good to go
`npx install-expo-modules@latest`

**Comment by pistonsky** [comment]
Took me 3 pomodoro sessions to fix this stuff!
