### ISSUE TITLE
Installing expo-linking fails. The package "colors" is not found.

### ISSUE THREAD

**Issue by DamageESP** [expo/expo#15952]
### Summary

When trying to install expo-linking, that fails because the `colors` package could not be found. This might be related to the recent news related to that package's maintainer "Marak" ([more info](https://fossa.com/blog/npm-packages-colors-faker-corrupted/))

$ expo install expo-linking
Installing 1 SDK 44.0.0 compatible native module using Yarn.
> yarn add expo-linking@~3.0.0
yarn add v1.22.17
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.npmjs.org/colors/-/colors-1.4.2.tgz: Request failed \"404 Not Fou
info If you think this is a bug, please open a bug report with the information provided in "**".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarnpkg exited with non-zero code: 1

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

44.0.0

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~44.0.0 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

Not applicable.

**Comment by Simek** [comment]
Hello @DamageESP, thank you for the report. 

I have checked the package dependencies tree and our [lock file](https://github.com/expo/expo/blob/master/yarn.lock#L6296-L6299) and it looks like the one of other packages which you are using forces the newer versions of `colors` package. Also, in the clean Expo project I was able to successfully run the `expo install expo-linking` command.

Can you try to add this section to your `package.json` file:
```json
  "resolutions": {
    "colors": "1.4.0"
  },
```

**Comment by DamageESP** [comment]
That did the trick, @Simek. Thanks a lot!
