### ISSUE TITLE
Issues while migrating from react-native-unimodules to Expo --> Library not found for -lFolly

### ISSUE THREAD

**Issue by Yandamuri** [expo/expo#15956]
### Summary

I am trying to migrate from react-native-unimodules to Expo and followed this [guide](https://github.com/expo/fyi/blob/main/expo-modules-migration.md) for migration. After completing the process successfully and ran the project from Xcode, I am facing following error,

<img width="894" alt="Screenshot 2022-01-19 at 11 02 21 AM" src="https://user-images.githubusercontent.com/31983789/150070051-6845a17b-4fad-457a-822a-c22c205ede5c.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

     Expo CLI 5.0.3 environment info:
    System:
        OS: macOS 11.6
        Shell: 5.8 - /bin/zsh
    Binaries:
        Node: 14.0.0 - /usr/local/bin/node
        npm: 6.14.4 - /usr/local/bin/npm
    Managers:
       CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
        iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
       Android Studio: 4.2 AI-202.7660.26.42.7351085
       Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
       expo: >=44.0.0-* <45.0.0 => 44.0.4 
       react: 17.0.1 => 17.0.1 
       react-native: 0.64.0 => 0.64.0 
    npmGlobalPackages:
       expo-cli: 5.0.3
       Expo Workflow: bare

### Reproducible demo

If we look at the error we can understand that issue is because of some missing library and not with any specific code. So I am unable to share any specific code.

But I can surely say one thing that, I am facing all these errors after running npm install expo and expo upgrade 43(For migrating from react-native-unimodules to Expo).

**Comment by byCedric** [comment]
Hi @Yandamuri! Without a repository where we can reproduce the issue you encounter, we can't do much to help you. Even for missing libraries, you still have a project where you can trigger the error.

The only thing I can think of is this issue. It might be similar and the fix might work for you too:
- https://github.com/facebook/react-native/issues/32572#issuecomment-968571696
