### ISSUE TITLE
"This experience uses an unsupported version of Expo"

### ISSUE THREAD

**Issue by arnoldbird** [expo/expo#1595]
### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/arnoldbird-accb5143-f337-4fde-809e-2ed974c91ab0.tar.gz

### Steps to Reproduce

I am trying to move src code from a project into a new expo project.  When I run the simulator, I see an error...

"Error: This experience uses an unsupported version of Expo (SDK 26.0.0).  You may need to update Expo Client on your device."

To reproduce:
1) Create a new app as described in the CRNA readme file:
$ npm install -g create-react-native-app
$ create-react-native-app my-app
2) Copy src and package.json from existing project into the new app.
3) Delete node_modules and then run npm install.
4) Run the simulator with npm start or react-native run-ios.

You will see the error.

### Expected Behavior

I expected I would be able to re-use code from an existing app in this newly created app.

### Actual Behavior

The error, as mentioned above.  App will not run.  See screenshot in first comment below.

**Comment by arnoldbird** [comment]
![simulator screen shot - ipad air 2 - 2018-04-02 at 16 37 40](https://user-images.githubusercontent.com/1728052/38215084-99c9c9e6-3694-11e8-9122-c01f98213796.png)

**Comment by arnoldbird** [comment]
I think I was able to fix this by changing the SDK version in app.json to 25.0.0.  However, now I am seeing another error.  I will open a separate issue.

**Comment by raphael4ndrade** [comment]
I had the same problem. I did this to solve by doing this:

Go to Simulator > Hardware > Erase All Content and Settings....

After that run again npm start and the Expo App will be dowloaded again in your simulator.
Hopefully it'll work with you guys.

**Comment by robblovell** [comment]
On my simulator this worked: 

With the device that isn't working running, go to the Simulator menu and select:
```
Simulator > Reset Content and Settings
```
You will need to do this with each device that you have previously tested or loaded with Expo.

**Comment by terribleben** [comment]
Hi, you can also just update the Expo app on the simulator/device. You don't need to reset content and settings (though this will also work).

**Comment by legendero** [comment]
if you don't want to reset your simulator, deleting 'EXPO' app is enough, delete it the rerun the simulator and it'll work.
