### ISSUE TITLE
@expo/vector-icons transform mangles & breaks react-native-vector-icons import statements

### ISSUE THREAD

**Issue by vladp** [expo/expo#15970]
### Summary

I use react-native-vector icons extensively. I do not have use for expo/vector-icons.
However, during build process expo's transform touches my source files with `import Ionicons from 'react-native-vector-icons/Ionicons';` and tries to convert them into `"@expo/vector-icons/Ionicons" `. 
From expo, the only thing I am using is expo-av.  

I am including expo in package.json, because the documentation (even for bare projects) states to include expo into settings.gradle (to pull modules that are necessary like const, etc)
```
apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute(null, rootDir).text.trim(), "../scripts/autolinking.gradle");
useExpoModules()
apply from: new File(["node", "--print", "require.resolve('@react-native-community/cli-platform-android/package.json')"].execute(null, rootDir).text.trim(), "../native_modules.gradle");
applyNativeModulesSettingsGradle(settings)
```

expo-av allows me to specify the icons I want for the player controls (so I use react-native-vector icons).
But since the upgrade from unimodules to the new build system, the above problem prevents me from using react-native-vector-icons

-------
                                                     
```                                                      
warning: the transform cache was reset.
debug Checking for a newer version of React Native
debug Current version: 0.64.3
debug Cached release version: 0.60.0
debug Checking for newer releases on GitHub
                    Welcome to Metro!
              Fast - Scalable - Integrated



To reload the app press "r"
To open developer menu press "d"

debug Latest release: 0.60.0
info Reloading app...
transform[stderr]: Could not resolve "@expo/vector-icons/Ionicons" in file /home/v/devel/mine/myproj/mob/rn.common/src/js.app/mdk/RNVI.android.js.
transform[stderr]: Could not resolve "@expo/vector-icons/Ionicons" in file /home/v/devel/mine/myproj/mob/rn.common/src/js.app/mdk/RNVI.android.js.
 BUNDLE  ./index.android.js 

```

-------

RNVI.android.js

```
// @flow
import Ionicons from 'react-native-vector-icons/Ionicons';
import Icon from 'react-native-vector-icons/Ionicons';
export {Ionicons, Icon};
```
------
package.json
```
{...

  "devDependencies": {
    "@babel/cli": "^7.16.7",
    "@babel/core": "^7.12.9",
    "@babel/preset-flow": "^7",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2",
    "@types/jest": "^26.0",
    "@types/react-native": "~0.64.12",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26",
    "babel-plugin-module-resolver": "^4",
    "eslint": "^7.32",
    "flow-bin": "^0.169",
    "flow-typed": "^3",
    "jest": "^26.6.3",
    "jetifier": "^1",
    "metro-react-native-babel-preset": "^0.66",
    "npm-run-all": "^4",
    "react-native-gradle-plugin": "^0.0.3",
    "react-test-renderer": "17.0.2",
    "ts-jest": "^24",
    "typescript": "~4.3.5"
  },
  "jest": {
    "preset": "react-native",
    "codegenConfig": {
      "libraries": []
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  },
  "dependencies": {
    "@react-native-community/checkbox": "^0",
    "@react-native-community/slider": "^4.1.12",
    "@react-native-community/toolbar-android": "^0.2",
    "@react-native-picker/picker": "2.2.1",
    "expo": "~44.0.5",
    "expo-av": "~10.2.0",
    "js-search": "^2",
    "prop-types": "^15",
    "pubsub-js": "^1",
    "react": "17.0.1",
    "react-native": "0.64.3",
    "react-native-markdown-display": "^6",
    "react-native-modal": "^13",
    "react-native-vector-icons": "^9",
    "react-router-native": "^6.2",
    "tree-model": "^1",
    "unmutable": "^0"
  },
  "expo": {
    "autolinking": {
      "exclude": [
        "@expo/vector-icons",
        "react-native-webview"
      ],
      "ios": {
        "exclude": [
          "expo-keep-awake",
          "expo-font"
        ]
      }
    }
  }


...}
```
------
react-native.config.js
```
const ios = require('@react-native-community/cli-platform-ios');
const android = require('@react-native-community/cli-platform-android');
const path = require('path');


module.exports = {
    project: {
	android:{
	    sourceDir: './u1b',
	    packageName:"com.mypoj", //must match package name in the AndroidManifest.xml 
	    assetsPath: path.resolve(__dirname+'../rn.common/src/js.app/img'),
	}
    },
    
  dependencies: { // exclude deps
    'react-native-webview': {
      platforms: {
          ios: null,
	  android:null
      },
    },
    '@expo/vector-icons':{
          platforms: {
          ios: null,
	  android:null
      },
    }
  }, 
    
};
```
-------------
metro.config.js

```
const path = require('path');

const myNodeModulesRootDir_abs=path.resolve(__dirname+'/node_modules');
console.log("myNodeModulesRootDir_abs="+myNodeModulesRootDir_abs);

module.exports = {
  resetCache: true,
  resolver: {
      nodeModulesPaths: [myNodeModulesRootDir_abs],
      useWatchman: false,
      extraNodeModules: {'js.app': path.resolve(__dirname + '../rn.common/src/js.app')}
   },
  
   watchFolders: [
    path.resolve(__dirname),
    path.resolve(__dirname, "../rn.common/src/js.app"),
  ],
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};

```
---------

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare
Also my JS require special paths (see metro.config.js).  

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.5

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.15 Pop!_OS 21.10
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 14.15.4 - /bin/node
      Yarn: 1.22.17 - /bin/yarn
      npm: 8.3.0 - /bin/npm
    npmPackages:
      expo: ~44.0.5 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

Result is that my app ends up having  no icons when it runs.
(because I do not include @expo/vector-icons at all, and do not use those icons names, instead our source code tracks icon names used in  react-native-vector-icons)

To reproduce simply create a file in any project that imports react-native-vector-icons (see RNVI.android.js below).  Add react-native-vector-icons into package.json (as shown below).   

As it can be seen not only I do not include @expo/vector-icons into my project.   I also actively trying to exclude it from my project... however this does not seem to help and the transformer during build's packaging step still thinks, for some reason, that  it needs to rewrite my import statements that import react-native-vector-icons.
 
---
```                                                                                                      
warning: the transform cache was reset.
debug Checking for a newer version of React Native
debug Current version: 0.64.3
debug Cached release version: 0.60.0
debug Checking for newer releases on GitHub
                    Welcome to Metro!
              Fast - Scalable - Integrated



To reload the app press "r"
To open developer menu press "d"

debug Latest release: 0.60.0
info Reloading app...
transform[stderr]: Could not resolve "@expo/vector-icons/Ionicons" in file /home/v/devel/mine/myproj/mob/rn.common/src/js.app/mdk/RNVI.android.js.
transform[stderr]: Could not resolve "@expo/vector-icons/Ionicons" in file /home/v/devel/mine/myproj/mob/rn.common/src/js.app/mdk/RNVI.android.js.
 BUNDLE  ./index.android.js 

```
----

RNVI.android.js

```
// @flow
import Ionicons from 'react-native-vector-icons/Ionicons';
import Icon from 'react-native-vector-icons/Ionicons';
export {Ionicons, Icon};
```
------
package.json
```
{...

  "devDependencies": {
    "@babel/cli": "^7.16.7",
    "@babel/core": "^7.12.9",
    "@babel/preset-flow": "^7",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2",
    "@types/jest": "^26.0",
    "@types/react-native": "~0.64.12",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26",
    "babel-plugin-module-resolver": "^4",
    "eslint": "^7.32",
    "flow-bin": "^0.169",
    "flow-typed": "^3",
    "jest": "^26.6.3",
    "jetifier": "^1",
    "metro-react-native-babel-preset": "^0.66",
    "npm-run-all": "^4",
    "react-native-gradle-plugin": "^0.0.3",
    "react-test-renderer": "17.0.2",
    "ts-jest": "^24",
    "typescript": "~4.3.5"
  },
  "jest": {
    "preset": "react-native",
    "codegenConfig": {
      "libraries": []
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  },
  "dependencies": {
    "@react-native-community/checkbox": "^0",
    "@react-native-community/slider": "^4.1.12",
    "@react-native-community/toolbar-android": "^0.2",
    "@react-native-picker/picker": "2.2.1",
    "expo": "~44.0.5",
    "expo-av": "~10.2.0",
    "js-search": "^2",
    "prop-types": "^15",
    "pubsub-js": "^1",
    "react": "17.0.1",
    "react-native": "0.64.3",
    "react-native-markdown-display": "^6",
    "react-native-modal": "^13",
    "react-native-vector-icons": "^9",
    "react-router-native": "^6.2",
    "tree-model": "^1",
    "unmutable": "^0"
  },
  "expo": {
    "autolinking": {
      "exclude": [
        "@expo/vector-icons",
        "react-native-webview"
      ],
      "ios": {
        "exclude": [
          "expo-keep-awake",
          "expo-font"
        ]
      }
    }
  }


...}
```
------
react-native.config.js
```
const ios = require('@react-native-community/cli-platform-ios');
const android = require('@react-native-community/cli-platform-android');
const path = require('path');


module.exports = {
    project: {
	android:{
	    sourceDir: './u1b',
	    packageName:"com.mypoj", //must match package name in the AndroidManifest.xml 
	    assetsPath: path.resolve(__dirname+'../rn.common/src/js.app/img'),
	}
    },
    
  dependencies: { // exclude deps
    'react-native-webview': {
      platforms: {
          ios: null,
	  android:null
      },
    },
    '@expo/vector-icons':{
          platforms: {
          ios: null,
	  android:null
      },
    }
  }, 
    
};
`
-------------
metro.config.js
```
const path = require('path');

const myNodeModulesRootDir_abs=path.resolve(__dirname+'/node_modules');
console.log("myNodeModulesRootDir_abs="+myNodeModulesRootDir_abs);

module.exports = {
  //projectRoot: path.resolve(__dirname+'/../rn.common'),
  resetCache: true,
  resolver: {
      nodeModulesPaths: [myNodeModulesRootDir_abs],
      useWatchman: false,
      extraNodeModules: {'js.app': path.resolve(__dirname + '../rn.common/src/js.app')}
   },
  
   watchFolders: [
    path.resolve(__dirname),
    path.resolve(__dirname, "../rn.common/src/js.app"),
  ],
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```

---

**Comment by brentvatne** [comment]
you don't need to use the babel preset if you don't want to - you can use the react-native preset or any other one that you'd like. also note that you can modify the babel config to stop aliasing react-native-vector-icons to @expo/vector-icons - this is what is causing it: https://github.com/expo/expo/blob/c399bb4a7406bf025189c30a4ecbed1b421c9c7e/packages/babel-preset-expo/index.js#L113-L129

**Comment by vladp** [comment]
thank you! I was searching for the offending magical transfomer that was doing this to my code.

With regards to not using expo babel presets.  The preset is part of the template for bare projects:

https://github.com/expo/expo/blob/main/templates/expo-template-bare-minimum/babel.config.js
will I be loosing some function, or subjecting myself to some incompatibility down the road (if now stop using the presets: ['babel-preset-expo'] ) ?

**Comment by brentvatne** [comment]
if you don't use web it doesn't matter too much. we provide defaults in our babel preset that we think will be useful for most people.

**Comment by vladp** [comment]
Ok thank you. I also have my app running on web, but again, I use react-native-web + react-native-vector-icons there, not expo's wrapper of the RN icons.   

Your recommendation makes sense, and I will ignore the babel-preset-expo.
Will close the issue.
