### ISSUE TITLE
SDK44 breaks iOS build of @nozbe/watermelondb

### ISSUE THREAD

**Issue by Yarkhan** [expo/expo#15986]
### Summary

Upgrading or initiating a new bare project to Expo SDK44, either via `install--expo-modules` or by `expo eject`, breaks the iOS build with the following messages:

`Swift Compiler Error: Cannot find 'installWaterMelonJSI' in scope`
`Swift Compiler Error:  Cannot find 'watermelondbProvideSyncJson'`

Workaround: Use SDK43 instead SDK44
`install--expo-modules --sdk-version 43.0.0` 

Or, if starting a new project
`expo init --template blank@43.0.2`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment
```
  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.2.0 - ~/.nvm/versions/node/v14.18.2/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/appleuser/.gem/ruby/3.0.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Reproducible demo

Create a new expo project
`expo --init --name expo-watermelon --template --blank`

Eject it, and choose a package name for Android & iOS
```
cd expo-watermelon
expo eject
```

Install WatermelonDB . The only extra steps required for reproducing this bug is adding the following pods to the Podfile. For full installation follow https://nozbe.github.io/WatermelonDB/Installation.html.
```
pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true
pod 'simdjson', path: '../node_modules/@nozbe/simdjson'
```

`yarn add @nozbe/watermelondb`

Install Pods.
`pod install`

Build via XCode or via terminal . Both fail.

**Comment by brentvatne** [comment]
@Kudo has opened https://github.com/Nozbe/WatermelonDB/pull/1249 to fix this

you can pull in his patch using patch-package in the meantime

**Comment by KrisLau** [comment]
@brentvatne Would this be an issue for WatermelonDB or Expo? It seems to be caused by Expo since WatermelonDB did not have an issue in my project until I migrated to expo modules from unimodules.
