### ISSUE TITLE
EAS build distribution: internal failed with latest SDK 44 and expo-document-picker

### ISSUE THREAD

**Issue by kevinL5** [expo/expo#15987]
### Summary

Hello,

My EAS build failed at "**Run fastlane**" step with latest SDK 44 and `expo-document-picker` installed

iCloudContainerEnvironment is missing in configuration, even when provided in `app.json`

⚠️ Bug happen only with profile `distribution: internal`

```
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 
"iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided" 
UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "iCloudContainerEnvironment": 
expected one of {Development, Production}, but no value was provided}
```

Thank for your help 🙏 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.3.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 25, 26, 30
        Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 30.0.3, 31.0.0
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### How to reproduce : 

1. Create an new app with latest SDK (44) (`expo init my-app`)
2. Add expo-document-picker (`expo install expo-document-picker`)
3. Follow the documentation steps ([Link](https://docs.expo.dev/versions/latest/sdk/document-picker/))

- create an iCloud Container and name it `iCloud.<your_bundle_identifier>`
- set the `usesIcloudStorage` key to true in `app.json`
- add expo-document-picker plugin in `app.json`
```
  "plugins": [
    [
      "expo-document-picker",
      {
        "appleTeamId": "YOUR_TEAM_ID",
        "iCloudContainerEnvironment": "Production"
      }
    ],
 ```
 
4. Build with EAS for iOS and select a profile with `distribution: internal` (`eas build --platform ios --profile preview`)
⚠️ Bug happen only with `distribution: internal`

**Comment by EvanBacon** [comment]
Should be fixed in https://github.com/expo/expo/pull/15774

**Comment by kevinL5** [comment]
Thanks @EvanBacon for your reply. I just tested and this fix the problem 🎉 

I think to permanently solve the problem, it would be necessary to:
- Release a new version of `expo-document-picker` with [#15774](https://github.com/expo/expo/pull/15774) included
- Update the [documentation](https://docs.expo.dev/versions/latest/sdk/document-picker/) to add `iCloudContainerEnvironment`

**Comment by Silvest89** [comment]
@EvanBacon Any ETA on a new release for `expo-document-picker` ?

**Comment by ydatech** [comment]
I have the same problem and waiting for the new release for `expo-document-picker` @EvanBacon

**Comment by brentvatne** [comment]
expo-document-picker@10.1.1 is released with this fix

**Comment by kevinL5** [comment]
Perferct, thanks :)
