### ISSUE TITLE
Issue using code recieved using Facebook.useAuthRequest on server side to get access_token

### ISSUE THREAD

**Issue by davidmetcal** [expo/expo#15980]
Hi,

I've been trying to use the AuthSessions to handle my social logins. I have been successful up to a point in that I am able to retrieve an access_token directly using response type token and use this to gain access to user details. However I am trying to implement the Auth Code flow and running into some 

```
	const [fbRequest, fbResponse, fbPromptAsync] = Facebook.useAuthRequest({
		clientId: {myClientId},
		responseType: ResponseType.Code,
	});
```
The above gives me a response and when I look at the params.code I pass this code to my server to then exchange it for my access_token. At this point I'm wondering if there is something I am missing as I am unable to exchange the code successfully server side for the access token.

```
	FB.api(
		'oauth/access_token',
		{
			client_id: appId,
			client_secret: appSecret,
			redirect_uri: redirectUri,
			code: code,
		},
		function (res) {
			if (!res || res.error) {
				console.log(!res ? 'error occurred' : res.error);
				return;
			}

			var accessToken = res.access_token;
			var expires = res.expires ? res.expires : 0;
			console.log(accessToken);
		}
	);
```
I keep getting the same error below:

 `message: 'Invalid code verifier. Code verifier should be a cryptographically random string using the characters A-Z, a-z, 0-9, and the punctuation characters -._~ (hyphen, period, underscore, and tilde), between 43 and 128 characters long.',`

Am I missing something to do with the code that is causing this to fail? I noticed in the initial request I have a codeChallenge and codeVerifier, do I need to so something with these to ensure the Auth Code flow works correctly?

**Comment by davidmetcal** [comment]
Ok so I finally figures it out - the issue was the I wasn't sending the code_verifier along with my request to exchange the Auth Code for a token. I ended up sending this code_verifier to my API server then adding this to the request so it looked something like this:

```
	FB.api(
		'oauth/access_token',
		{
			client_id: appId,
			client_secret: appSecret,
			redirect_uri: redirectUri,
			code_verifier: code_verifier,
			code: code,
		},
		function (response) {
			if (!response || response.error) {
				console.log(!response ? 'error occurred' : response.error);
				return;
			}

			var accessToken = response.access_token;
		})
```

This then finally gave me the accessToken I was looking for that I can then use to exchange for user details server side.

**Comment by DukeNuken** [comment]
I have the same problem. Where did you get that "code_verifier" param? I mean from Facebook.useAuthRequest in response came  2 params: "code" and  "state". So where did you get "code_verifier" param?

**Comment by yosmanyga** [comment]
The `code_verifier` is obtained from `request.codeVerifier`.

`const [request, response, promptAsync] = Facebook.useAuthRequest(...`
