### ISSUE TITLE
FB ads Unsupported top level event type "onLoggingImpression" dispatched

### ISSUE THREAD

**Issue by craig1123** [expo/expo#1598]
### Steps to Reproduce

1. Open the android simulator using Genymotion. This message pops up immediately.

<img width="560" alt="screen shot 2018-04-02 at 5 39 45 pm" src="https://user-images.githubusercontent.com/17581359/38221516-24848424-369d-11e8-8c85-912b378d66ba.png">

I found a similar issue at https://github.com/callstack/react-native-fbads/issues/87. But it looks like expo hasn't updated the native code yet

**Comment by esamelson** [comment]
Hi @craig1123  - thanks for letting us know about this bug. The fix will go out with SDK 27.
