### ISSUE TITLE
Stream microphone audio to Speech to Text Service

### ISSUE THREAD

**Issue by pnadj** [expo/expo#15994]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by pnadj** [comment]
I'm trying to stream audio data recorded from the microphone using expo-av to a SST service (google cloud, rev.ai etc). Is this possible? I am only able to get the uri after I have finished recording, but I was looking to use filesystem to maybe stream the audio data in an ArrayBuffer

**Comment by brentvatne** [comment]
this is not possible with the current expo-av api, you may need to use another library for this

**Comment by j8jacobs** [comment]
@pnadj Any updates on this? Where you able to get a solution, expo-av or other?
