### ISSUE TITLE
Simulator no long works -- "unsupported version of Expo (SDK 26.0.0)"

### ISSUE THREAD

**Issue by arnoldbird** [expo/expo#1599]
### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/arnoldbird-780b8c92-3599-4903-9593-4bf40a0316f3.tar.gz

### Steps to Reproduce

1) Create a new app with create-react-native-app
2) Run npm start
3) Type i to start the iOS simulator

### Expected Behavior

Simulator should run the app.

### Actual Behavior

"There was a problem loading this experience... Error: This experience uses an unsupported version of Expo (SDK 26.0.0).  You may need to update Expo Client on your device."

![simulator screen shot - ipad air 2 - 2018-04-03 at 07 58 31](https://user-images.githubusercontent.com/1728052/38247933-d1f9d65a-3714-11e8-95b7-c4ecaa0f2d85.png)

**Comment by arnoldbird** [comment]
The solution is at https://github.com/react-community/create-react-native-app/issues/113#issuecomment-289325092

**Comment by terribleben** [comment]
Just to add more info for anybody finding this thread:

The message says "You may need to update Expo Client on your device." Indeed, you should update Expo Client on your device to resolve this issue.

We'll make sure the error message is clearer in the future. Sorry about the confusion.

**Comment by arnoldbird** [comment]
In my case, Expo Client needed to be updated in the simulator, rather than on my device.  To update Expo in the simulator, I restarted the simulator (Hardward > Restart), deleted Expo from the simulator, and then exited.  

Then, when you run the simulator the next time, it will go through the process to install the latest Expo Client.

**Comment by nipasarker01** [comment]
It works ..thanks @arnoldbird

**Comment by nonoyek** [comment]
thankiew very much arnoldbird solution is working well

**Comment by jakesyl** [comment]
You don't even need to restart. Just delete it and rerun the simulator
