### ISSUE TITLE
Task :expo-updates:compileDebugKotlin FAILED: 'onWillCreateReactInstanceManager' overrides nothing

### ISSUE THREAD

**Issue by GGsparta** [expo/expo#15995]
### Summary

I am tring do debug my application on Android by running `expo run:android`. I have no issues with the basic `expo start` on Web/Android. Here is the output I get at the end. I can't find anything about this issue anywhere.

```
[...]
> Task :expo-updates:compileDebugKotlin FAILED
e: C:\project\node_modules\expo-updates\android\src\main\java\expo\modules\updates\UpdatesPackage.kt: (39, 7): 'onWillCreateReactInstanceManager' overrides nothing
e: C:\project\node_modules\expo-updates\android\src\main\java\expo\modules\updates\UpdatesPackage.kt: (45, 7): 'onDidCreateReactInstanceManager' overrides nothing
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-updates:compileDebugKotlin'.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\EdenQuest\EdenSteer\node_modules\.bin\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16
      expo: ^44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

No demo available sorry, if it is closed that's okay, I just can't find anything about this issue elsewhere. However, here's the list of dependencies:

package.json:
```
[...]
  "dependencies": {
    "@expo/webpack-config": "~0.16.2",
    "@expo/vector-icons": "^12.0.5",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
    "babel-plugin-inline-import": "^3.0.0",
    "chokidar": "^3.5.2",
    "core-js": "^3.20.2",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-plugin-import": "^2.25.4",
    "expo": "^44.0.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "^0.11.5",
    "hoek": "^6.1.3",
    "immer": "^9.0.7",
    "joi": "^17.5.0",
    "lottie-react-native": "5.0.1",
    "native-base": "3.2.1",
    "react": "17.0.1",
    "react-dev-utils": "^12.0.0",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "https://github.com/software-mansion/react-native-gesture-handler#62e9eb66bced3b4c55042399d761baee7d961140",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-svg": "12.1.1",
    "react-native-unimodules": "~0.15.0",
    "react-native-web": "0.17.1",
    "react-native-web-lottie": "^1.4.4",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "sharp-cli": "^1.15.0",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "svgo": "^2.8.0",
    "topo": "^3.0.3",
    "yarn": "^1.22.17"
  },
```

**Comment by byCedric** [comment]
Hi @GGsparta! You can see these overwrites [here](https://github.com/expo/expo/blob/master/packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesPackage.kt#L39-L49). They should overwrite a couple of things from the [`ReactNativeHostHandler`](https://github.com/expo/expo/blob/master/packages/expo-modules-core/android/src/main/java/expo/modules/core/interfaces/ReactNativeHostHandler.java), which is part of the new Expo Modules system.

Now I see that you have `react-native-unimodules`, which is deprecated and should be fully replaced by the new [`expo-modules-core`](https://github.com/expo/expo/tree/master/packages/expo-modules-core) (a direct dependency of `expo`). You could try removing this dependency, reinstalling node_modules and just try to build it again. It could interfere with the new Expo modules core.

If that doesn't help, I would recommend opening up a new issue but with a repository with that error you describe. Without it, we can only guess, unfortunately.

Hope this helps!

**Comment by GGsparta** [comment]
Removing this dependency worked for me! Thank's a lot for considering my issue!

**Comment by Slapbox** [comment]
Same issue but we don't use `react-native-unimodules` anywhere.

@byCedric can you confirm for me which version of `expo-modules-core` should be used with SDK 44? Is there some resource I could check for that?
