### ISSUE TITLE
Reports of Expo Client 2.4.x crashing after enabling Remote Debugging and then Refreshing

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1600]
One possible report: https://github.com/react-community/create-react-native-app/issues/618

Possible repro steps:

- Enable remote debugging, this should work fine
- Do some work
- Eventually refresh the app (with remote debugging still enabled)
- Expo Client will crash

**Comment by joshsiegl1** [comment]
@terribleben I'm seeing this issue as well, was working fine before the update

**Comment by terribleben** [comment]
Hey there, I just tried to reproduce this and I didn't encounter the issue. Here's what I did:

- Use `exp init` to create a new "tabs" project running Expo SDK 26
- Run the project with `exp r --localhost`
- Open on iOS simulator with Expo Client 2.4.6 by typing `exp send --ios`
- Enable remote debugging from the Expo menu
- Make some changes to my project's JS
- Press Cmd+R to reload

The app loads fine and does not crash for me.

I also tried some variations, for example I tried pressing "Refresh" from the Expo menu instead of using Cmd+R. I also tried deliberately introducing a syntax error in my JS, refreshing, fixing the error, and refreshing again. Remote JS debugging is enabled the whole time, and the app is still working for me.

Can anybody who is encountering this issue let me know if you did something differently from what I did? Or if there is any other factor that I didn't account for?

**Comment by joshsiegl1** [comment]
@terribleben My issue has been resolved, thanks for replying and looking into it. For me I was testing on a physical iOS device, it seemed to have something to do with the Windows Firewall, of which I disabled and things started functioning normally. Expo Client 2.4.6 would hang at 100% (during the javascript package bundling) forcing me to restart the packager and the app, I'd then go back into the app and it would crash.  

Disabling the Windows Firewall rectified that entire issue for me, although it wasn't happening with previous versions of the Expo Client with the firewall enabled as previously mentioned.

**Comment by theonlydaleking** [comment]
@terribleben Just tried to re-create this. It used to rebuild to 100% and then crash, it doesn't crash anymore it just gets stuck at downloading js bundle 100.00%. It's now at least manageable 

For reference, I first saw this using create-react-native-app. I haven't tested this with exp init.

**Comment by terribleben** [comment]
We pushed a fix in Expo Client 2.6.7 (and newer) which addressed an issue with similar symptoms. Can anybody who saw the issue  in the first place let me know if it seems fixed to you now?

**Comment by theonlydaleking** [comment]
Checked and confirmed now working. 

The only way I could get it to break was by doing obscure stuff. eg. I put a `console.log()` outside of a render function and the app froze on Downloading bundle 100%. However, I don't think this is an issue.

**Comment by terribleben** [comment]
Thanks for verifying. I'm going to tentatively close this, since I believe it's fixed.

Since this issue is old and has symptoms that might be caused by a variety of things, I'm going to lock the thread, in order to encourage people to open a fresh issue report if you find something similar in the future.

Also, for the case where the bundler gets stuck at 99% or 100% (mentioned in some other comments), I believe that is a separate issue and we've recently landed some fixes for that:

- https://github.com/expo/xdl/commit/13a2019a4aa94964dcce73bd545e56c02ebb4d92
- https://github.com/expo/xdl/commit/045ef93b030fde2cbb5a0775a97067ad5f3dd42a
