### ISSUE TITLE
Error when running react-native run-android

### ISSUE THREAD

**Issue by AlexandreMaistret** [expo/expo#16018]
### Summary

Hi,

I am trying to create a react-native app with expo but it always fails when I am trying to run react-native run-android.

- I am creating a react-native with : `npx react-native init MyAppName --version 0.66.0`
- I run `npx react-native run-android` to check if everything is alright => all good
- Then I followed the documentation of Expo.dev to install expo in my react-native app by running `npx install-expo-modules`
- Then I try to run the app by running `npx react-native run-android` and I have an error:
`ENOENT: no such file or directory, open d:…\MyAppName\node_modules\expo-constants\android\build\generated\assets\expo-constants\debug\app.config`

I tried :
-  launch `cd android && gradlew clean` => error still occuring
- manual installation by running `npm install expo` and then following the steps of the documentation => error still occuring
- clean project in android studio => => error still occuring
- delete build folder in android => error still occuring
- delete build folder in node_modules\expo-constants\android => error still occuring

I did not have any issue when I was using react-native-unimodules.

Does someone have a solution ?
Thank you

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

>=44.0.0-0 <45.0.0

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 8.1 6.3.9600
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.2.1 - C:\PROGRAM FILES (X86)\YARN\BIN\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.
0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 30.0.2
        System Images: android-19 | ARM EABI v7a, android-19 | Google APIs Intel
 x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google Play Int
el x86 Atom
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.5
      react: 17.0.2 => 17.0.2
      react-native: 0.66.0 => 0.66.0
    Expo Workflow: bare

### Reproducible demo

This what I did to add expo to my react-native project:
- I am creating a react-native with : `npx react-native init MyAppName --version 0.66.0`
- I run `npx react-native run-android` to check if everything is alright => all good
- Then I followed the documentation of Expo.dev to install expo in my react-native app by running `npx install-expo-modules`
- Then I try to run the app by running `npx react-native run-android` and I have an error:
`ENOENT: no such file or directory, open d:…\MyAppName\node_modules\expo-constants\android\build\generated\assets\expo-constants\debug\app.config`

**Comment by pnadj** [comment]
Is there a reason you're not initiating with expo

expo init my-project

**Comment by AlexandreMaistret** [comment]
I need to install loads of other npm libraries and on my previous projects it worked way better when starting whith a bare project than starting directly with expo.

**Comment by brentvatne** [comment]
@AlexandreMaistret - it's best to share a version of your repository that we can clone directly from github (the issue template asks for this too).

i followed your repro instructions and it worked as expected for me. please create a new issue with a cloneable reproducible example when you have one!
