### ISSUE TITLE
'folly/Optional.h' file not found

### ISSUE THREAD

**Issue by gracedmarks** [expo/expo#16021]
### Summary

I tried to run iOS React Native project with expo-modules-core and the build can be completed because of the error 'folly/Optional.h' file not found from ExpoModulesCore.

![Screen Shot 2022-01-23 at 4 59 51 AM](https://user-images.githubusercontent.com/73297926/150656856-d1fc1495-f8aa-44ba-bec6-da654044d076.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2022.01.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

![Screen Shot 2022-01-23 at 5 04 16 AM](https://user-images.githubusercontent.com/73297926/150656888-cd0c7224-96b1-483c-91e7-86087501b972.png)

**Comment by gracedmarks** [comment]
Are you experiencing the same issue? I downgrade expo version from 44 to 42

**Comment by arbabahmed1997** [comment]
Yes experiencing the same issue, after downgrading expo to 42, pods are not installing with error Invalid `Podfile` file: cannot load such file node_modules/expo/scripts/autolinking. 
Have you experienced this error as well?

**Comment by gracedmarks** [comment]
try removing node_modules using `rm -rf node_modules` and install again

**Comment by jbcorry** [comment]
Having this same issue after installing expo-in-app-purchases.

**Comment by TheDuc** [comment]
Having the same issue here after installing `expo-local-authentication` and following this [guide](https://docs.expo.dev/bare/installing-expo-modules/).
In that guide the autolink script is added to the podfile, not sure how to downgrade to SDK 42 as it does not have that script.
Is there a way to install the folly dependency manually or so?

**Comment by raid5** [comment]
I'm hitting this exact same issue. What is the workaround?

**Comment by dungnguyen10989** [comment]
> 

Upgrade to react-native ver >= 0.66.0, it removes Folly, and upgrades to RCT-Folly 2021.06.28.xx.

**Comment by amie-wilt** [comment]
hey @TheDuc, I followed the same guide and am having the same issue, did you get this figured out?

**Comment by huy-lv** [comment]
how to resolve this problem guys?
