### ISSUE TITLE
[expo-image-picker] undefined is not an object

### ISSUE THREAD

**Issue by gracedmarks** [expo/expo#16020]
### Summary

undefined is not an object (evaluating '_ExponentImagePicker.default.requestMediaLibraryPermissionsAsync')

Here's the code 💻

```
// Camera & Image Picker
import * as ImagePicker from 'expo-image-picker';


const openImagePicker = async () => {
    try {
        // Ask the user for the permission to access the media library 

        const permissionResult = await ImagePicker.requestMediaLibraryPermissionsAsync()


        if (permissionResult.granted === false) {
            alert("You've refused to allow this appp to access your photos!");
            return;
        } 

        const result = await ImagePicker.launchImageLibraryAsync();

        // Explore the result
        console.log(result);

        if (result.cancelled === false) {
            setPickedImagePath(result.uri);
            console.log(result.uri);
        }
    } catch (error) {
        alert('Error Occur: ' + error.message)
        closeSheet()
    }
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2022.01.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

[https://i.stack.imgur.com/xOacj.png](url)

**Comment by yarinsn** [comment]
same here

**Comment by gracedmarks** [comment]
I managed to fix that by downgrading expo to 42, just a workaround not the explicit solution.

**Comment by yarinsn** [comment]
As i experienced it only on the standalone version, I tried rebuilding my app and publishing it again (ios) and it worked. I didnt need to downgrade (using expo 44).

**Comment by seanbarker096** [comment]
https://stackoverflow.com/a/74163723/12119984 might help

Try calling some other methods on that Native Module too. If they all throw that error maybe there was an issue during the build when adding the module, or a build issue more generally

**Comment by gustavo-herrera-cabrera** [comment]
I solved this problem by changing the import location. 
From:
- `import * as ImagePicker from "expo-image-picker";`
to:
- `import * as ImagePicker from "expo-image-picker/src/ImagePicker";`

**Comment by DiegoVSouza** [comment]
> I solved this problem by changing the import location. From:
> 
> * `import * as ImagePicker from "expo-image-picker";`
>   to:
> * `import * as ImagePicker from "expo-image-picker/src/ImagePicker";`

I solved this by updating the SDK to the latest version and changing the import location

**Comment by mikeRChambers610** [comment]
It is working fine on IOS but on android I am getting below error:

[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'result.assets[0]')][Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'result.assets[0]')]

Im on SDK 47 using latest version of expo-image-picker.

**Comment by mikeRChambers610** [comment]
I am reproducing the issue here  #21354

https://snack.expo.dev/@mikechambers610/image-picker-snack?platform=ios

**Comment by Tchaikovsky1114** [comment]
> It is working fine on IOS but on android I am getting below error:
> 
> [Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'result.assets[0]')][Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'result.assets[0]')]
> 
> Im on SDK 47 using latest version of expo-image-picker.

i got same issue.
only android has not assets array.
just has cancelled: undefined

**Comment by migerusantte** [comment]
Facing the same exact issue in SDK 47, any updates on this?

**Comment by Said20hr** [comment]
Same here : undefined is not an object (evaluating 'result.assets[0]')

**Comment by migerusantte** [comment]
Kind of aligned with what @lsharples1 mentioned, I was able to solve my issue doing first an eas dev build (I'm using expo) and then launching the development server, that way the library worked without any problems.

This happens with all the libraries that require at least some native stuff to work properly, so have that in mind

**Comment by Said20hr** [comment]
I solved the issue with downgrading the SDK to 44, you need to go to package.json
`"dependencies": {
  "expo": "~44.0.0",
  ...
}
`
