### ISSUE TITLE
Build Stuck in 2h+

### ISSUE THREAD

**Issue by casperstr** [expo/expo#1602]
Build usually finishes in under 5min. 
My build has now been stuck for 2h plus. 
ID: ecfae4ce-2af0-47e6-90dd-652ae81b7df6

**Comment by terribleben** [comment]
Hi, going to close this old issue. Hopefully you've had a chance to try your build again. :)

**Comment by lylest** [comment]
everytime  that typed npm start on expo and my computer stucks
