### ISSUE TITLE
[Unhandled promise rejection: SyntaxError: JSON Parse error: Unrecognized token '﻿'] with ANDROID platform only

### ISSUE THREAD

**Issue by hatim85f** [expo/expo#16026]
### Summary

I am trying to fetch data from rest api, fetching function is working perfect in ios platform while fails in android. I am using #Expo-Cli version 5.0.3 ( latest version ) , 

I beleive it's a bug in this version as I am getting the error only in android platform 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

```js
export const getData= (language) => {
  return async (dispatch) => {
    const response = await fetch("my-link");

    const resData = await response.json();

    // console.log(resData.MAIN);
  };
};
```

**Comment by barthap** [comment]
Hello,

It looks like your response might be malformed (or empty string).
- Try replacing `response.json()` with `response.text()` and compare the raw response on Android and iOS.
- make sure that your `"my-link"` is a valid URL
- Check the `response.ok` and `response.status` - maybe request just failed?
- Check if you have internet access on Android device/emulatroe (e.g. open that URL in a browser)
