### ISSUE TITLE
[expo-navigation-bar]Navigation bar turns gray when setting the background color to transparent

### ISSUE THREAD

**Issue by Sai-Smaran** [expo/expo#16036]
### Summary

When I set the background color of the navigation bar to "transparent", the background color turns gray

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 7 6.1.7601
    Binaries:
      Node: 12.22.9 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Reproducible demo

```javascript
import React from "react"
import { setBackgroundColorAsync } from "expo-navigation-bar";

export default function App() {
  React.useEffect(()=>{
    setBackgroundColorAsync("transparent");
  });
  return null;
}
```

**Comment by gufril15** [comment]
try using rgb

**Comment by page403** [comment]
i still facing this issues. rgba value alpha is work, but the navigation bar turned into black or white bg. didn't transparent. when set the rgba alpha value to 0.5 the transparent kinda work but on top of native navigationbar. so its just turn gray.

any idea?

**Comment by visibait** [comment]
This issue should be reopened. You can't set the navigation bar color to transparent.

**Comment by yepMad** [comment]
The bar turns into a transparent white/black, not fully transparent
