### ISSUE TITLE
[Notifications][Android]Custom sound is not working on the Android device after upgrade to Expo44

### ISSUE THREAD

**Issue by GuoXiaoyang** [expo/expo#16030]
### Summary

Recently I upgraded my Expo SDK version from 40 to 44. And custom sound is not working on the Android device.

For example I used the `schedulePushNotification` method to  schedule a local push notification, and I found only if I remove the `sound` attribute or set it true in the content(this attribute is for Android 7.1 below), the notification can popup and make custom sound normally.

```
async function schedulePushNotification() {
  await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail! 📬",
      body: "Here is the notification body",
      sound: 'moego.wav', // remove this attribute data or set it true, then it works properly, but it will not be compatible for Android below 7.1?
      data: { data: "goes here" },
    },
    trigger: { seconds: 2, channelId: "moego-test" },
  });
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

Expo 44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
      Watchman: HEAD-49f3831 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

https://github.com/GuoXiaoyang/moego-release-test/tree/feature-notification

**Comment by ramiel1999** [comment]
were you able to fix this? I am trying to make custom notification sound work on android 6 but there is no sound
