### ISSUE TITLE
"iOS: Build waiting in queue" for over 2 hours now. What's wrong?

### ISSUE THREAD

**Issue by jansenmaarten** [expo/expo#1603]
https://expo.io/builds/d5e1ceaf-62f0-4cd3-b40b-90f4478c108a

**Comment by benlonsdale** [comment]
Same here

**Comment by muniperez** [comment]
Same problem! https://expo.io/builds/e1a9e7ec-18db-471d-a8b5-c4755e07526e

**Comment by ide** [comment]
iOS builds are currently being processed more slowly than usual. We are looking into speeding up the builders today and we'll post updates here: https://expo.statuspage.io/

**Comment by terribleben** [comment]
Hi all, we think the issue has indeed been resolved for a couple weeks. (sorry, just catching up to this old issue.) Let us know if you have trouble again. If so, a new thread is more likely to get noticed.
