### ISSUE TITLE
[SDK41] Expo Location reverseGeocodeAsync returns different data for iOS and android

### ISSUE THREAD

**Issue by edotappstore** [expo/expo#16031]
### Summary

Location reverseGeocodeAsync returns different data for iOS and Android.

Example 1: 
Android returns "city":"Mormugao" while iOS returns "city":"Vasco Da Gama" for a same given location.
![image](https://user-images.githubusercontent.com/98312418/150755263-17f8596f-a257-4db2-b441-c648857745d4.png)

Example 2:
Android returns "city":null while iOS returns "city":"Margoa" when coordinates of a stadium is passed in the function.
![image](https://user-images.githubusercontent.com/98312418/150756077-5dfdd132-ba23-4907-b294-86322c3c69cc.png)

Example 3:
Android returns only "postalCode" as null while iOS returns "city", "postalCode" as null, when coordinates of a point in the sea is passed in the function.
![image](https://user-images.githubusercontent.com/98312418/150756776-bc046803-7a41-47ef-b6b2-94ed4347cafe.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.12.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\edot\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo

let locationData = await Location.reverseGeocodeAsync({ latitude: this.state.latitude, longitude: this.state.longitude });

console.log(`Platform - ${Platform.OS}:-`);
console.log(locationData[0]);

**Comment by brentvatne** [comment]
the data returned is dependent on what the api on the platform returns. this is intentional, they wrap the native apis exposed by the platform and it's not possible to normalize to the same format.
