### ISSUE TITLE
Which `package.json` is being referred to in EAS Build mono repo docs?

### ISSUE THREAD

**Issue by peterferguson** [expo/expo#16035]
### Summary

In the [How to set up EAS Build with a monorepo](https://docs.expo.dev/build-reference/how-tos/#how-to-set-up-eas-build-with) it is not immediately clear which `package.json` is being referred to.

My assumption is that it should be the `apps/my-app/package.json`. Since the provided snippet seems to navigate to the root of the monorepo.

```json
{
  "scripts": {
    "postinstall": "cd ../.. && yarn build"
  }
}
```

I am not sure if this is correct. If someone wants to clarify I can submit a pr to update the docs from 

> add a postinstall step to `package.json` in your project

to 

> add a postinstall step to `apps/my-app/package.json` in your project

or 

> add a postinstall step to `package.json` in your projects app directory

 

### Link to the related docs page

https://docs.expo.dev/build-reference/how-tos/#how-to-set-up-eas-build-with

**Comment by brentvatne** [comment]
it is indeed referring to the app package.json. the code there is just an example and the actual postinstall script that you run depends on whatever your repo needs to set itself up (if additional setup is required after installation)
