### ISSUE TITLE
expo-image-picker allowsEditing=false crashes on EAS Build on Android

### ISSUE THREAD

**Issue by Overdash** [expo/expo#16042]
### Summary

Using expo-image-picker: when `allowsEditing=false` the Android bundle built **specifically using EAS build on a managed workflow** crashes. 
* We can not reproduce this in development using exp-cli and thus cannot get a stacktrace for it. 
* Using `expo build` seems to work, but our pipeline uses EAS.

We've done multiple iterations with our own code and tried to have 2 image picker buttons, one where `allowEditing` is `true`, another where `false`. The `false` creates the issue. We also tried when omitted - same issue (as it defaults the prop to `false`)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Issue on EAS Build created binary for Android - works fine locally.

### Reproducible demo

```javascript
import * as ImagePicker from "expo-image-picker";

export const imageFromDevice = async (fromGallery = true) => {
	const imagePickerFn = fromGallery ? ImagePicker.launchImageLibraryAsync : ImagePicker.launchCameraAsync;
	const { status } = await ImagePicker.getMediaLibraryPermissionsAsync();

	// Check we got permission
	if (status !== "granted") {
		// err msg
		return null;
	}

	return await imagePickerFn({
		base64: true,
		mediaTypes: ImagePicker.MediaTypeOptions.Images,
		allowsEditing: true, // take the entire image; we have no way to allow for *optional* cropping - if true user HAS to crop.
		aspect: [1, 1],  // has no effect on iOS (always square)
		quality: 0.6,  // we don't want super high quality lol
	});
};
```

**Comment by Overdash** [comment]
@brentvatne I've added another repro as you deemed the previous one inadequate

**Comment by brentvatne** [comment]
@Overdash - give us a repository that we can clone as described in the template please :)
