### ISSUE TITLE
[expo-ads-admob] iOS preloaded interstitial not showing

### ISSUE THREAD

**Issue by MPBogdan** [expo/expo#16045]
### Summary

Hello,

Taking in consideration that an interstitial ad takes couple of seconds to load I am preloading them. On iOS (real&emulated) the preloaded ad is not showing when await `AdMobInterstitial.showAdAsync()` is called. Another odd thing is that `interstitialDidOpen` event is triggered even if the ad is not showing and `await AdMobInterstitial.getIsReadyAsync()` returns true after `AdMobInterstitial.showAdAsync()` is called.
If I am not preloading them and call 
`await AdMobInterstitial.setAdUnitID(unitID);
await AdMobInterstitial.requestAdAsync({ servePersonalizedAds: personalizedAds });
await AdMobInterstitial.showAdAsync();`
it's working without any problem.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 4.12.12 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ~43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

```
import AsyncStorage from "@react-native-async-storage/async-storage";
import { AdMobInterstitial } from 'expo-ads-admob';
import { Platform } from "react-native";
import * as Device from 'expo-device';

export default async function showInterstitial() {
    let loadingAd = await AsyncStorage.getItem("loadingAd")
    let unitId 

 if (Device.isDevice) {
        if (Platform.OS === "ios") {
            console.log("real device ios")
            unitID = "ca-app-pub-3940256099942544/4411468910"
        } else if (Platform.OS === "android") {
            console.log("real device android")
            unitID = "ca-app-pub-3940256099942544/8691691433"
        }
    } else {
        if (Platform.OS === "ios") {
            console.log("emulated device ios")
            unitID = "ca-app-pub-3940256099942544/4411468910"
        } else if (Platform.OS === "android") {
            console.log("emulated device android")
            unitID = "ca-app-pub-3940256099942544/8691691433"
        }
    }

    let isReady = await AdMobInterstitial.getIsReadyAsync()
    if (!isReady) {
        if (loadingAd === "false") {
            if (unitID != undefined) {
                console.log(new Date().toString() + " Preload ad")
                await AsyncStorage.setItem("loadingAd", "true")
                await AdMobInterstitial.setAdUnitID(unitID);
                await AdMobInterstitial.requestAdAsync({ servePersonalizedAds: true });
                console.log(new Date().toString() + " Done preloading ad")
                await AsyncStorage.setItem("loadingAd", "false")
            }
        } else {
            console.log(new Date().toString() + "Ad is already loading")
        }
    } else {
        console.log(new Date().toString() + "Ad is already ready")
    }

    if (someReasonToShowAd) {
        let adIsReady = await AdMobInterstitial.getIsReadyAsync()
        if (adIsReady) {
            console.log("Displaying ad")
            await AdMobInterstitial.showAdAsync();
        }
}
```

This function is called every time when user is triggering some actions (changing screens or have some predefined actions on screens (e.g. value of dropdown changed)).

Note: Sometimes the ad is shown shortly(under 1s) and closes by itself.

**Comment by MPBogdan** [comment]
If a sleep before the ` await AdMobInterstitial.showAdAsync()` is called then the ad will start. I think this have something to do with the rendering/re-rendering when the user is triggering an action which also calls this method.
Code after rework:
`{....
if (someReasonToShowAd) {
        let adIsReady = await AdMobInterstitial.getIsReadyAsync()
        if (adIsReady) {
            await sleep(1000)
            console.log("Displaying ad")
            await AdMobInterstitial.showAdAsync();
        }
....
}

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}
`

Although this is working I think that it will cause issues with AdMob accidental clicks therefore AdMob can limit the ads.

**Comment by VictorioMolina** [comment]
Same problem here. https://github.com/expo/expo/issues/17536

**Comment by ornakash** [comment]
Same issue here
