### ISSUE TITLE
Support for React Native 0.67

### ISSUE THREAD

**Issue by ursnj** [expo/expo#16040]
### Summary

Expo is breaking with react-native 0.67 with following error:

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/nj/Desktop/projects/xxx/node_modules/expo/android/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating project ':expo'.
> Plugin with id 'maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

0.43

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 2022.01.17.00 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

Try with react-native 0.67

**Comment by brentvatne** [comment]
hello! we didn't add support for react-native@0.67 yet, it made a few changes that we'll need to account for.

note our policy on react-native versions: https://docs.expo.dev/versions/latest/#support-for-other-react-native-versions

**Comment by Bardiamist** [comment]
I hope it will be soon. Now waiting and don't reverting react-native.

Here is the issue https://github.com/expo/expo/issues/12774 but without the ability to leave comments

**Comment by brentvatne** [comment]
here's a pr that will add support for react-native 67: https://github.com/expo/expo/pull/16080

we'll likely release this sometime next week. you can use patch-package until then.

**Comment by brentvatne** [comment]
this is supported in expo@44.0.6

**Comment by RobTS** [comment]
The dependencies for unimodules still need to be updated, as that module will install dependencies not updated.

**Comment by chakrihacker** [comment]
> The dependencies for unimodules still need to be updated, as that module will install dependencies not updated.
> 
> Edit: Also, it looks like @unimodules/core does not have a new release yet, breaking RN apps integrating unimodules.

I faced an issue unable to find expo-core-modules. But this is only on next js. I just added the package and everything is working fine.

**Comment by brentvatne** [comment]
@RobTS - unimodules does not exist anymore, it was renamed to expo modules and lives in the expo package now. https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc

**Comment by smn-snkl** [comment]
@brentvatne how do I start a new expo project with expo@44.0.6 ? When I install the latest expo-cli and run expo init, it still uses an older expo version ...

**Comment by brentvatne** [comment]
@smn-snkl - check your lockfile, it will indeed install the correct version - "~44.0.0" tells npm to get the latest patch version (the last 0) for the major version (44) and minor version (the second 0)

**Comment by smn-snkl** [comment]
@brentvatne or is it possible to use your templates with the current expo-cli version? But it seems that templates need to be hosted on npm so they can be used...

So if you have a quick tip what the easiest way to start a new expo bare project with rn67+ is, I'd highly appreciate it :)
