### ISSUE TITLE
Margin Vertical Percentage Bug in Expo 26?

### ISSUE THREAD

**Issue by r1nkel** [expo/expo#1605]
Before expo 26, marginVertical using percentage behave as it should be for its child.
In expo 26, marginVertical using percentage effecting its child element?

### Expected Behavior
marginVertical using percentage should behave same as before.

### Actual Behavior

![capture](https://user-images.githubusercontent.com/8698419/38309434-4c287c8a-3844-11e8-92ab-95dbbcc05204.JPG)

The 1st is using 2% marginVertical.
the 2nd is using 10% marginVertical.

### Reproducible Demo
https://snack.expo.io/HJn7ZLMjG

**Comment by ide** [comment]
The main change that would have affected this would have been the upgrade from React Native 0.52 (SDK 25) to 0.54 (SDK 26). There were some changes to the layout system and text component implementations (more on iOS, though) that may have affected this. In summary, this is how React Native now behaves.
