### ISSUE TITLE
expo-gl crash in iOS Release builds with React Native 0.66.4

### ISSUE THREAD

**Issue by scarlac** [expo/expo#16057]
### Summary

Adding expo-gl and expo-three to an Expo 44 bare workflow with Expo modules causes a crash on iOS but only in Release builds. Debug builds work fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
rn66gl % expo diagnostics       

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.5 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.4 => 0.66.4 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Reproducible demo

```
$ npx react-native init rn66gl --version 0.66.4
$ cd rn66gl
$ npx install-expo-modules
$ expo install expo-gl
$ expo install expo-three
$ cd ios
$ pod install
$ cd ..
$ xed ios/
```
Edit the current scheme, select "Build Configuration: Release"
![Screen Shot 2022-01-25 at 08 43 03](https://user-images.githubusercontent.com/895369/151020594-d870e801-83e3-4b55-b61e-54956be5c2ac.jpg)

![Screen Shot 2022-01-25 at 08 43 15](https://user-images.githubusercontent.com/895369/151020776-802259f5-fb12-4b43-979a-812eac869ecf.jpg)

"Debug executable" doesn't seem to matter, but I did it so I could see the stack better.
Select a local simulator target (it also seems to happen on final builds).
Note that I am using an Macbook Pro with an M1 Pro chip.

Press Run button. App compiles without issues, launches, briefly shows something and then crashes/halts with the following stack trace:
![Screen Shot 2022-01-25 at 08 45 32](https://user-images.githubusercontent.com/895369/151021058-4fb6e9f1-4a7b-4c4b-a513-8cece134f032.jpg)

The error message is:
```
com.facebook.react.JavaScript (9): EXC_BAD_ACCESS (code=1, address=0x65)
```

The code it stops on is:
```
JSObjectSetProperty(
      ctx_,
      objectRef(object),
      stringRef(name),
      valueRef(value),
      kJSPropertyAttributeNone,
      &exc);
```

Issue seems to be reproducible even after removing expo-three, so it's isolated to `expo-gl`

**Comment by brentvatne** [comment]
this seems likely due to changes in react-native 0.66. expo sdk 44 targets react-native 0.64, and we test against that, so you may encounter issues in some circumstances with newer versions (we usually try to resolve them as they arise). ([more info](https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a)).

a pr to fix support for react-native 0.66 would be welcome!
