### ISSUE TITLE
expo-linking 

### ISSUE THREAD

**Issue by MarouaniALA** [expo/expo#16069]
### Summary

The goal is to open a page in the app when I get a notification.
in expo it works with Linking in the foreground but not in the background.

I used `registerTaskAsync()` of expo-notification to handling incoming notifications when the app is in background.

expected behavior when `Linking.openURL()` executed, it opens the application even if the application is in the background but in fact the redirect is done directly after coming back to the foreground by opening the application manually 

```
    const redirectUrl = Linking.createURL('FullScreenNotif', {
        queryParams: {id},
    });
    Linking.openURL(redirectUrl);
```

PS: I know that expo Go doesn't support background notification handle so I tested by building a stand-alone app

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 4.5.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 14.17.6 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2
    npmPackages:
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.5.0
    Expo Workflow: managed

### Reproducible demo

i tried to get it work on snack but there is an [issue](https://github.com/expo/snack/issues/117) with deeplinking
link [snack](https://snack.expo.dev/@marouaniala/navigationcontainer-|-react-navigation) for demo

**Comment by brentvatne** [comment]
as far as i know, neither ios nor android allow you to perform such an operation in the background. if you can point to any examples of another app doing his i'd be curious to see it

**Comment by MarouaniALA** [comment]
@brentvatne  there is much apps that can be opened from background like uber driver, messenger, whatsapp, truecaller (they open the app even if it is killed not only in the background)

**Comment by MarouaniALA** [comment]
@brentvatne this [lib](https://www.npmjs.com/package/react-native-invoke-app) work's on bare workflow.  It invokes the app to be opened from the background but it works only on android and i should eject my app and that's what am trying to avoid

**Comment by brentvatne** [comment]
oh interesting, this does seem like you can *open your own app from the background* in some cases *on android only*. although the library you linked to doesn't actually work on android 10+, [which requires a different approach](https://stackoverflow.com/questions/59419653/cannot-start-activity-background-in-android-10-android-q) and [has a bunch of limitations](https://developer.android.com/guide/components/activities/background-starts). 

either way, `Linking.openURL` does not explicitly support this use case. you can try installing and using the library that you linked to by [using expo-dev-client](https://docs.expo.dev/development/introduction/) or bare workflow but ymmv

**Comment by MarouaniALA** [comment]
yes i tested the linked lib on android 11 and it worked using expo-dev-client but i don't know if there is an other solution to bring app to the foreground using the expo sdk Or just open a full screen notification like this attachment
![WhatsApp Image 2022-01-26 at 2 32 21 AM](https://user-images.githubusercontent.com/25243369/151096558-e588ffcd-b7e2-4914-a5c9-ffe6e96dce0d.jpeg)

**Comment by MarouaniALA** [comment]
this [lib](https://github.com/react-native-webrtc/react-native-callkeep)  uses the same concept

**Comment by brentvatne** [comment]
i'm not familiar with these apis and the expo sdk does not currently offer an api to accomplish this goal, so hopefully you can find what you need in a library on https://reactnative.directory/ :)

**Comment by MarouaniALA** [comment]
thnx for your reply i will try an other approach or eject my app
