### ISSUE TITLE
App upgraded to Expo 44 does not run on Android 5.0

### ISSUE THREAD

**Issue by ht512512** [expo/expo#16062]
### Summary

Upgraded my app to Expo 44. After that, on Android 5.0, it shows the splash screen and then a white blank screen. Higher android version (8, 9, 10, 11) work fine.

Expo Client 2.23.2 from play store has the same behavior on Android 5 - splash and then blank.

Expected behavior: 
If 5.0 is supported it should work fine (like on other android versions). 
If 5.0 is not supported then the min sdk version should be updated so that the app store won't allow installation on 5.0 devices.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.5.1 - /usr/bin/yarn
      npm: 8.1.1 - ~/.nvm/versions/node/v14.15.0/bin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

Since the expo client 2.23.2 exhibits the same behavior, the following steps will reproduce it.

On an Android 5.0 device, install Expo Go 2.23.2 from Google Play Store and launch it. 
It displays Expo splash screen and displays a white blank screen after that. Does not get to the main Expo screen.

**Comment by brentvatne** [comment]
dup of #15822

**Comment by ht512512** [comment]
@brentvatne 
HI, It is not exact duplicate. There are two issues.
1. Expo Go 2.23.2, the version currently on the play store does not work on Android 5.0 (spalsh and then blank screens). This is a duplication of #15822 
2. App build with SDK 44  does not work on Android 5.0 (spalsh and then blank screens). This can be reproduced easily by creating a blank app with expo init, building on expo build and then installing & running it on Android 5.0.
The issue #2 is equally serious. It results in a user allowed to download and install app on 5.0 only to see it being DOA, which of course makes the developer look really horrible. If it is not going to work on 5.0, it would be nice if the installation was not allowed on 5.0 as well.
Thanks
Hemant

**Comment by brentvatne** [comment]
re: 2 - is this happening when you build with `expo build:android` or `eas build`?

**Comment by ht512512** [comment]
Ok. WIll try out EAS Build and let you know.
Thanks.

**Comment by ht512512** [comment]
@brentvatne 
I have got the eas build setup but not able to remove reanimated. Reanimated Babel plugin removal breaks the app with error, "Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?" I will appreciate any suggestions. I really would like to not give up on Android 5.0 :)
Thanks.
Hemant

**Comment by hamdidamar** [comment]
After a few months we are here together. We get this error too. Did you find a solution? We still cant open our apps on android 5.1. And the app still wait on splash screen.

**Comment by kholildev** [comment]
me too
