### ISSUE TITLE
expo-web-browser can have incorrect status bar color

### ISSUE THREAD

**Issue by jparkrr** [expo/expo#16063]
### Summary

When opening a webbrowser using `WebBrowser.openBrowserAsync`, the status bar is the wrong color. My app doesn't support dark mode and cannot at this time, but it seems like `SFSafariViewController` expects it to be dark.

I found this issue on stackoverflow that seems relevant, so hopefully this is easy to fix.
https://stackoverflow.com/questions/33172960/sfsafariviewcontroller-status-bar-style

![image](https://user-images.githubusercontent.com/872456/151052128-092958bb-b2f9-4d16-9ecb-c00c96fd16d1.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.3 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2022.01.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/justin/.gem/ruby/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

https://github.com/jparkrr/webview-statusbar-bug

**Comment by predam** [comment]
I need to integrate the browser view into the app design, but I can't find a way to fix the status bar color.
Any news on that?

```javascript
const open = async () => {
  await WebBrowser.openBrowserAsync(data.url, {
    toolbarColor: "#ffffff"
  });
};
```
![IMG_E2C2F55D7A02-1](https://user-images.githubusercontent.com/9632910/169627976-db0478d2-82ea-4afc-884c-29d94a9cec39.jpeg)

**Comment by erickreutz** [comment]
Also running into this issue
