### ISSUE TITLE
Duplicate splash screens on Android 12 with expo-splash-screen; upgrade to new Splashscreen API required?

### ISSUE THREAD

**Issue by keith-kurak** [expo/expo#16084]
### Summary

Seems like this might go hand-in-hand with an upgrade to Android SDK 31, but didn't see it already on the issues list, so figured I'd get it on the board just in case that it looks like expo-splash-screen would need to be updated to use Android 12's new Splashscreen API (see: https://developer.android.com/guide/topics/ui/splash-screen/migrate). It appears that the second of the two fallbacks is being invoked, as expo-splash-screen uses an Activity-based splash screen (per the link above):
> If your existing splash screen is implemented using a dedicated Activity, launching your app on devices running Android 12 or higher results in duplicate splash screens: the new system splash screen displays, followed by your existing splash screen activity.

[Created a video](https://photos.app.goo.gl/5bNL51xZmzk77Tp97) showing our bare app loading on a Pixel 4a running Android 12 and then a test managed app that I built with the default splash screen doing the same thing. You'll see exactly the fallback as Google describes it, with the app icon being shown and then transitioning to the actual splash screen.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /var/folders/xz/f7gw6gb509n2whbvh19b8mrh0000gn/T/yarn--1643228715836-0.6327139417443315/node
      Yarn: 1.22.4 - /var/folders/xz/f7gw6gb509n2whbvh19b8mrh0000gn/T/yarn--1643228715836-0.6327139417443315/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /Users/keith/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.15.0 => 0.15.0 
      babel-preset-expo: ^8.4.1 => 8.4.1 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.3.7 => 4.4.3 
    Expo Workflow: bare

### Reproducible demo

1. `expo init` a "minimal" app
2. `expo build:android` (or eject and build bare, doesn't seem to matter)
3. Run it on Android 12 (confirmed on Pixel 4a)

**Comment by Iyaaan** [comment]
any update on this

**Comment by StefanBratanov** [comment]
Same here with bare workflow

```
"expo": "~44.0.6",
"expo-splash-screen": "~0.14.2"
```

**Comment by sahzhang** [comment]
Still having issues with this, any updates?

**Comment by AliMohammad93** [comment]
I have the same problem 
is there any solution ?

**Comment by llamaluvr** [comment]
@AliMohammad93 

The maintainer of [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash) has advised that his package supports this new splashscreen setup, so you could use that instead. I imagine this will be fixed in the Expo package eventually, as they move to target API 31+. Even with expo-splashscreen, you can minimize the impact by creating a splashscreen that closely matches your adaptive icon.

**Comment by AliMonam** [comment]
Same issue, any solution?

**Comment by AliMohammad93** [comment]
This problem is due to default splash screen in Android 12
To to resolve it you can only replace the default splash screen with a transparent screen
Go to res/values/styles.xml and edit the file like this

` <style name="Theme.App.SplashScreen" parent="AppTheme"> 

    <item name="android:windowBackground">@drawable/splashscreen</item>

    <item name="android:windowIsTranslucent">true</item> // add this line

  </style>`

**Comment by kesteer** [comment]
As @AliMohammad93 has mentioned, the only way I can see to fix this is a workaround until Expo handles this natively. 

Btw, thanks for the code snippet!

**Comment by murat0** [comment]
Thank you for all your comments - however what if we are on the managed workflow? Even if you give up on the custom splash screen you still can't control the native one ui 4 by calling preventAutoHideAsync and/org hideAsync(). Any ideas?

**Comment by wafisher** [comment]
I was able to get it working with this in case @AliMohammad93's comment wasn't clear.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/3514570/174523282-58d141f6-e1a3-4006-8025-0f23ae0c0d73.png">

**Comment by anhquan291** [comment]
I'm still facing the same issue even when I already added 
```
 <item name="android:windowIsTranslucent">true</item>
```
Any solutions please. Thanks

**Comment by Yandamuri** [comment]
Facing the same issue with `expo: 44.0.0`

**Comment by michaek** [comment]
If that's what does the trick, this may be the right config plugin to accomplish it in the managed workflow:

```
const {
  AndroidConfig,
  withAndroidStyles,
} = require("@expo/config-plugins");

const withSplashWindowIsTranslucent = (config) => {
  return withAndroidStyles(config, async (config) => {
    config.modResults = await configureFullScreenDialog(config.modResults);
    return config;
  });
};

async function configureFullScreenDialog(
  styles
) {
  const splashScreen = styles.resources.style.find(
    style => style.$.name === "Theme.App.SplashScreen"
  );

  if (splashScreen) {
    splashScreen.item = splashScreen.item.filter(item => item.$.name !== "android:windowIsTranslucent");
    splashScreen.item.push(
      AndroidConfig.Resources.buildResourceItem({
        name: 'android:windowIsTranslucent',
        value: true
      })
    );
  }

  return styles;
}

module.exports = withSplashWindowIsTranslucent;
```

I'll reiterate that this doesn't seem like something that should be in userland, but rather part of the default splash screen configuration.

**Comment by t0ma5h** [comment]
Still an issue.

**Comment by t0ma5h** [comment]
For anyone with struggling with managed workflow, add this plugin to apply the fix mentioned above.

Create a `./plugins` folder, and add `withExpoSplashScreen.js`:

``` 
const { withAndroidStyles, AndroidConfig } = require('@expo/config-plugins');

function setSplashScreenTransparent(styles) {
  styles = AndroidConfig.Styles.assignStylesValue(styles, {
    add: true,
    parent: {
      name: 'Theme.App.SplashScreen',
    },
    name: `android:windowIsTranslucent`,
    value: 'true',
  });

  return styles;
}

module.exports = function withExpoSplashScreen(config) {
  return withAndroidStyles(config, baseConfig => {
    baseConfig.modResults = setSplashScreenTransparent(baseConfig.modResults);
    return baseConfig;
  });
};
```

in you `app.json` or `app.config.js` add the following: 

```
....
plugins: [
        './plugins/withExpoSplashScreen.js',
        ........
]
```

**Comment by prashantkumar23** [comment]
Issue is still there

**Comment by leotomas837** [comment]
> I'm still facing the same issue even when I already added
> 
> ```
>  <item name="android:windowIsTranslucent">true</item>
> ```
> 
> Any solutions please. Thanks

@anhquan291 Did you find any solution? Not working for me too.

**Comment by leotomas837** [comment]
Any workaround? Having the following doesn't to work using managed workflow... (`styles.xml` checked using `npx expo prebuild . --yarn -p android`).

```xml
<style name="Theme.App.SplashScreen" parent="AppTheme">
  <item name="android:windowBackground">@drawable/splashscreen</item>
  <item name="android:windowIsTranslucent">true</item>
</style>
```

**Comment by cfreear** [comment]
There's another open issue on this that has newer feedback from the expo team #20244

**Comment by ponikar** [comment]
You can use `react-native-bootsplash` library with expo. that library has native splash screen support the problem is you have to create a small plugin that setup the splash screen for you in both android and iOS. 

I did some workaround on this lately and it was working for android, here's the code. Hopefully this will work. 
https://github.com/ponikar/react-native-bootsplash/tree/exp/expo-support/expo/plugin/src/android

**Comment by ziyoshams** [comment]
don't use `react-native-bootsplash` if you are using `expo-updates`. You will have a white splash after your splash screen.

**Comment by kesteer** [comment]
To anyone interested; I've written an extremely basic ExpoConfig plugin for managed workflows. 

```ts

import { ConfigPlugin, withAndroidStyles } from '@expo/config-plugins';

const withFixAndroidSplashScreen: ConfigPlugin = (config) => {
  config = withAndroidStyles(config, async (config) => {
    const androidStyles = config.modResults.resources;
    if (!androidStyles?.style) {
      throw new Error('styles.xml is not in the expected format!');
    }

    // Add translucent window for anything over Android 12
    const splashScreenStyle = androidStyles.style?.find((style) => style.$.name === 'Theme.App.SplashScreen');
    if (!splashScreenStyle) {
      throw new Error('Theme.App.SplashScreen is not in the expected format!');
    }

    splashScreenStyle?.item.push({
      _: 'true',
      $: {
        name: 'android:windowIsTranslucent',
      },
    });

    return config;
  });

  return config;
};

// eslint-disable-next-line import/no-default-export
export default withFixAndroidSplashScreen;
```

Feel free to use/edit it if you'd like to until Expo updates this to be natively handled with a flag or something.

**Comment by markoorn** [comment]
Any updates on this?

**Comment by jacobhummel** [comment]
My Android app has been rejected twice in a row and as far as I can tell this is why =/

## App config

```json
"expo-splash-screen": "~0.26.4",
"expo": "~50.0.14",
```

```ts
splash: {
        image: './assets/splash.png',
        backgroundColor: '#1942FF',
        resizeMode: 'cover'
}
```

## Rejection

![image](https://github.com/expo/expo/assets/1299567/cfce71f3-a7cd-4ee5-b2af-aaf30f272b27)


## Pre-launch Report 

![image](https://github.com/expo/expo/assets/1299567/4c8a269e-ff40-42d1-b85b-7a05ef8721a4)

![image](https://github.com/expo/expo/assets/1299567/ad01fe16-8b94-4ea6-9bdd-1ba229146929)

**Comment by aminnoura** [comment]
Any solution for this? I also face the same problem.

**Comment by albertorg** [comment]
same problem

**Comment by Nantris** [comment]
Is this not addressed? You can spend 100 hours or more building a well polished app just to run into this, and worse to find it closed.

Can we get this reopened?

**Comment by MikeKovarik** [comment]
+1

**Comment by Nantris** [comment]
@brentvatne could we please get this re-opened? Our app has two splash screens and a loading screen now. It's not a great look.

A suitable workaround in my view would be documentation on replicating the default Android splash screen as an image so that (hopefully) the second splash screen would be indistinguishable from the first, but I don't have time to try that just hoping that it works given that (to my knowledge) each attempt would require a new build.

**Comment by brentvatne** [comment]
hi @Nantris - we are tracking this in #29440
