### ISSUE TITLE
Cannot see manual input in expo-dev-client when the keyboard is showing.

### ISSUE THREAD

**Issue by jparkrr** [expo/expo#16081]
### Summary

On an iPhone X, a custom client doesn't allow the user to paste in a manual url in some cases. The input is covered by the keyboard.

https://user-images.githubusercontent.com/872456/151216789-cfb96c91-def1-41fe-8b8d-c9503339c866.MP4

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

```
expo-dev-client@0.8.2
├─ expo-dev-launcher@0.10.2
```

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.3 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2022.01.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/justin/.gem/ruby/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

Here is an [iOS simulator build](https://github.com/expo/expo/files/7943905/8aabe45c-3b16-4149-a012-3b985ef1965c-184d2a5f45f3450c9caeb696d0d22135.1.tar.gz) with expo-dev-client 0.8.2. Running on an iPhone X simulator and activating the keyboard will show the issue.

**Comment by lukmccall** [comment]
Thanks for your report. We will try to fix that soon.
