### ISSUE TITLE
Enable FlashMode in BarcodeScanner

### ISSUE THREAD

**Issue by devdandi** [expo/expo#16089]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by rissois** [comment]
Agreed this is a positive feature for BarcodeScanner (as well zoom) if the BarcodeScanner module is to reach parity with Camera.

There is an existing issue with flashMode for Web #12638

**Comment by brentvatne** [comment]
you can use the camera module for bar code scanning as well. expo-barcode-scanner is a bit of a legacy library in that it existed before we added bar code scanning capabilities to expo-camera, and we only kept it around to ensure that folks wouldn't be forced to migrate and deal with some possibly slightly different behavior. i'd suggest trying expo-camera for your task and see if it does what you need.
