### ISSUE TITLE
Dev client on bare workflow is missin local network permission on ios. No development in LAN possible

### ISSUE THREAD

**Issue by TimoGoetze** [expo/expo#16090]
### Summary

After eas prebuild and building dev client for ios and android to use real devices in local network for development, i would expect to have ios set the 

https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking

But it is not and furthermore there is no settings screen entry for the development client app.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

all SDK 44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0
        System Images: android-29 | Google Play Intel x86 Atom
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

expo init myapp
cd myapp
eas prebuild
cd android
---change something - eg. maven dependency --
 eas build --profile development --platform all

install on android and ios. Android works, ios cannot connect to metro and does not ask for a permission. Expo Go on same device can connect to this metro bundler.

**Comment by TimoGoetze** [comment]
additional Info: This only happens on the first install and when you start the app using ios camera and barcode. If you enter ip adress of metro server manually then permission dialog asks for local network permission and things work. but when you use barcode, permission dialog does not come up and no connection can be made.

**Comment by brentvatne** [comment]
this key is only needed for ios 9 and lower, the local network permission prompt introduced in ios 14 is still required regardless of whether you provide this key or not. the problem is that apple gives us no api to force this prompt, and so we have to do it indirectly by making a dummy request. it seems like sometimes this doesn't actually work, and no prompt is displayed. it's unclear under which exact circumstances this happens. if you have any more insight into this, please let us know

**Comment by TimoGoetze** [comment]
well, as it happens when i start the dev client initially via the camera, might it be a timing issue and it would help to wait? OR if the permission is not granted already, to prefill the manual connection string so one can initiate the first attempt via user interaction?

**Comment by tcdavis** [comment]
@TimoGoetze Thanks for the report and sharing your workaround 😄  We're exploring how we can improve the way we acquire the permission to make things more reliable.

**Comment by bradjones1** [comment]
Not stale

**Comment by trajano** [comment]
Is there a way of making it ask again or have it in settings? I can't find my dev client in the settings app.
