### ISSUE TITLE
[SDK 43 Managed][react-native-google-places-autocomplete] Compatibility

### ISSUE THREAD

**Issue by HappyCoding999** [expo/expo#16095]
### Summary

APK gets into stuck at splash screen with managed workflow mode when import react-native-google-places-autocomplete module in order to implement google places search.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2, 32.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ~43.0.2 => 43.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

no idea.

**Comment by brentvatne** [comment]
note: this is not a bug in expo tooling as far as i can tell. perhaps there is an issue in the library you are trying to use. if you narrow this down to a bug on our end, please create a reproducible example and a new issue. others refer to the resources above.
