### ISSUE TITLE
Update react-native-maps

### ISSUE THREAD

**Issue by babenzele** [expo/expo#161]
According to [this comment](https://github.com/airbnb/react-native-maps/issues/1280#issuecomment-298819282) at `airbnb/react-native-maps`, v0.13.0 is the version to use for the least problems. 

Could we update this package in expo?

**Comment by terribleben** [comment]
Yes, thanks for asking. This will be updated in SDK 17, which we're planning to roll out next week.

**Comment by sonaye** [comment]
https://github.com/airbnb/react-native-maps/releases/tag/v0.15.0 is the latest available.

**Comment by terribleben** [comment]
Hi! We updated to 0.14, but I just looked at the change log for 0.15 (which is only a few days old) and the only change is renaming a file, so for the purposes of Expo they are the same.

We also just pulled in [this bugfix](https://github.com/airbnb/react-native-maps/pull/1115) which fixes animateToCoordinate, something several developers have asked about.

**Comment by terribleben** [comment]
This was released with SDK 17 today.
