### ISSUE TITLE
Audio recording playback routes to phone receiver only on iOS

### ISSUE THREAD

**Issue by James2516** [expo/expo#1610]
From the [docs](https://docs.expo.io/versions/latest/sdk/audio#allowsrecordingios--a-boolean-selecting-if-recording-is-enabled-on-ios-this-value-defaults-to-false-note-when-this-flag-is-set-to-true-playback-may-be-routed-to-the-phone-receiver-instead-of-to-the-speaker):

> allowsRecordingIOS : a boolean selecting if recording is enabled on iOS. This value defaults to false. NOTE: when this flag is set to true, playback may be routed to the phone receiver instead of to the speaker.

But there's no configuration to set playback to phone receiver for Android. 

Can this inconsistency be fixed? Perhaps with a `useReceiverAndroid` flag.

**Comment by esamelson** [comment]
@sjchmiela -- do you know if this is possible?

**Comment by sjchmiela** [comment]
From my short testing it looks like when `allowsRecordingIOS` is `true`, playback is always routed to the phone receiver. Did it work like this for you too, @James2516?

If yes and it is repeatable for you too, I'll try to make the `useReceiverAndroid` flag. 🙂

**Comment by James2516** [comment]
@sjchmiela that's right, please add the flag for android.

Also, can the behavior be changed such that it only route to the phone receiver when there is an ongoing recording?

Hope you can fix https://github.com/expo/expo/issues/1708 first though as it completely breaks the app :(

**Comment by James2516** [comment]
There is also a weird/unexpected behavior with the API:
1. Set `allowsRecordingIOS` to `true`
2. plays an audio/video
3. can no longer record until step 1 is repeated

**Comment by esamelson** [comment]
Hi, we've landed a fix for this internally which will go out with our next release. I'll reopen this issue to continue tracking until then.

**Comment by sjchmiela** [comment]
https://docs.expo.io/versions/v30.0.0/sdk/audio#playthroughearpieceandroid--set-to-true-to-route 🎉
