### ISSUE TITLE
Expo-Camera (web): QR code not recognized with inverted colors

### ISSUE THREAD

**Issue by rissois** [expo/expo#16103]
### Summary

A QR code with a black foreground, white background is recognized. However, a white foreground and black background is not recognized. Possibly already fixed for BarCodeScanner, but not applied to Camera/Web (#1736).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### Environment

Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare

### Reproducible demo

I opened the Snack below on my computer and went to the Web tab (I needed to hit the [expand/maximize](https://snack.expo.dev/dist/assets/d93a5d445d7b7a8be13f38362a9dcf7e.png) button to get Web to work). Then I opened the below QR codes on my phone and switched between showing them to my computer's camera.

https://snack.expo.dev/@claypot/62b702

[Here are two identical QR codes for https://expo.dev/](https://imgur.com/a/cRl0oSr). The only difference is inverting the foreground and background colors. White codes on black backgrounds were not registered, while the black code on white background is immediately detected.

Issue #1736: It seems like it was fixed for BarCodeScanner, but not the Camera module, which is required for web (#15442).

**Comment by rissois** [comment]
Please check src/useWebQRScanner

```
const qrWorkerMethod = ({ data, width, height }: ImageData): any => {
  // eslint-disable-next-line no-undef
  const decoded = (self as any).jsQR(data, width, height, {
    inversionAttempts: 'dontInvert', // should this be attemptBoth? https://www.npmjs.com/package/jsqr
  });

  let parsed;
  try {
    parsed = JSON.parse(decoded);
  } catch (err) {
    parsed = decoded;
  }

  if (parsed?.data) {
    const nativeEvent: BarCodeScanningResult = {
      type: 'qr',
      data: parsed.data,
    };
    if (parsed.location) {
      nativeEvent.cornerPoints = [
        parsed.location.topLeftCorner,
        parsed.location.bottomLeftCorner,
        parsed.location.topRightCorner,
        parsed.location.bottomRightCorner,
      ];
    }
    return nativeEvent;
  }
  return parsed;
};
```

**Comment by brentvatne** [comment]
@rissois - try modifying the file in the build directory instead

**Comment by rissois** [comment]
@brentvatne Thanks for the advice, I was able to get it working and have submitted a [pull request](https://github.com/expo/expo/pull/16106)
