### ISSUE TITLE
expo-linear-gradient fails to show more than two colors on IOS

### ISSUE THREAD

**Issue by TheSilentHorizon** [expo/expo#16105]
### Summary

We have a background for our application which consists of more then 2 gradient colors. While in Android it displays correctly, in IOS it fails to show the third color (tested on IPhone XR with IOS 15).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

And pictures to show the error:

IOS:
![iosbug](https://user-images.githubusercontent.com/29006783/151460221-cbf3c9ce-dfb5-4a67-879c-260e9a024407.png)

Android (How it should look):
![WhatsApp Image 2022-01-28 at 00 25 45](https://user-images.githubusercontent.com/29006783/151460325-ea420e5b-ae48-417e-b355-129ba14779ab.jpeg)

### Reproducible demo

```
import React, {Component} from "react";
import {LinearGradient} from "expo-linear-gradient";


export default class Custom_gradient extends Component{
    render(){
        return(
            <LinearGradient
                start={[0.1,0.0]} end={[1.0,1.0]} colors={['#0000FF', '#000000', '#5e2f8b']} style={[{height:"100%",width:"100%"},this.props.style]}>
                {this.props.children}
            </LinearGradient>
        )
    }
}
```

**Comment by brentvatne** [comment]
this was fixed in https://github.com/expo/expo/pull/15955 and deployed in expo-linear-gradient@11.0.1

this is not available in expo go at the moment, but you can use expo-dev-client to see this in development, and your apps built with EAS Build with this SDK version will work as expected

**Comment by SrBrahma** [comment]
@brentvatne any idea when this will be available for Expo Go?

And, just as a curiosity, as I am using Expo for 2 years and getting to know more about it everyday hehe:

How Expo Go works regarding it / why it doesn't have the expo-linear-gradient patch?
