### ISSUE TITLE
SDK 44 Broke Monorepo Support

### ISSUE THREAD

**Issue by bnussman** [expo/expo#16104]
### Summary

When running `expo start` and opening an app in **Expo Go** on my iPhone 13, the app can't load and throws two errors shown below.
![Screen Shot 2022-01-27 at 6 14 00 PM](https://user-images.githubusercontent.com/6440455/151459374-935551d4-350d-4179-8d37-f1b5c290ad3b.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.volta/tools/image/node/16.13.0/bin/node
      Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
      npm: 8.1.0 - ~/.volta/tools/image/node/16.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: managed

### Reproducible demo

The monorepo can be found [here](https://gitlab.nussman.us/beep-app/beep). Running `expo prebuild` does not fix anything. I've tried many different metro configs, but no metro config makes a difference.

**Comment by bnussman** [comment]
Savage!

**Comment by CruelMoney** [comment]
@bnussman Having the same issue. I noticed [this pull request ](https://github.com/expo/expo/pull/15812) concerning a typo in the metro config, but unfortunately, it didn't fix the issue. Might be worth a try though.

**Comment by brentvatne** [comment]
let me know when there is a minimal reproducible example and we are happy to look!

**Comment by rhyek** [comment]
I have a reproducible example with both npm workspaces and pnpm:

npm: https://github.com/rhyek/expo-monorepo-issue/tree/npm
pnpm: https://github.com/rhyek/expo-monorepo-issue/tree/pnpm

Each branch has a readme with instructions and the error they yield.

**Comment by brentvatne** [comment]
we don't provide explicit support for npm or pnpm workspaces, we currently recommend yarn workspaces and that's all we have bandwidth to support. that said, if you follow the monorepo guide here and just use npm workspaces where relevant it should work fine: https://docs.expo.dev/guides/monorepos/

notice that index.js / main step.

**Comment by byCedric** [comment]
yarn: https://github.com/bycedric/eas-monorepo-example

**Comment by rhyek** [comment]
Thanks. That was helpful. In case it helps anyone else:

Changes needed for npm workspaces:
https://github.com/rhyek/expo-monorepo-issue/compare/npm...npm-fixed

Changes needed for pnpm:
https://github.com/rhyek/expo-monorepo-issue/compare/pnpm...pnpm-fixed
