### ISSUE TITLE
Camera stopped working on web

### ISSUE THREAD

**Issue by CodySwannGT** [expo/expo#16110]
### Summary

Just trying to run the demo snack [from here](https://docs.expo.dev/versions/latest/sdk/camera/) now throws the following error:

https://capture.dropbox.com/cqTOieM2WOyuiJb0?src=ss

![image](https://user-images.githubusercontent.com/292923/151483179-9f073cfc-501a-4295-9ad9-dc2afccaa377.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

44.0.5

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16 
      expo: ^44.0.5 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

````
import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { Camera } from 'expo-camera';

export default function App() {
  const [hasPermission, setHasPermission] = useState(null);
  const [type, setType] = useState(Camera.Constants.Type.back);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestCameraPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (hasPermission === null) {
    return <View />;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }
  return (
    <View style={styles.container}>
      <Camera style={styles.camera} type={type}>
        <View style={styles.buttonContainer}>
          <TouchableOpacity
            style={styles.button}
            onPress={() => {
              setType(
                type === Camera.Constants.Type.back
                  ? Camera.Constants.Type.front
                  : Camera.Constants.Type.back
              );
            }}>
            <Text style={styles.text}> Flip </Text>
          </TouchableOpacity>
        </View>
      </Camera>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
  buttonContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    margin: 20,
  },
  button: {
    flex: 0.1,
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  text: {
    fontSize: 18,
    color: 'white',
  },
});
````

**Comment by byCedric** [comment]
Hi @CodySwannGT! I can't seem to reproduce that error. Did you add any custom code to the example? The hooks should be fine, they aren't conditionally rendered and should not trigger that error.

In case you did add custom code, can you provide a repro with that code?

**Comment by CodySwannGT** [comment]
Hi @byCedric - nope nothing custom at all. My entire app was just the code I pasted above.

For more completeness, here's the package.json. Also, I should note, this was working fine until recently. I can't tell you what broke it because it wasn't found for a couple weeks.

```
{
  "main": "node_modules/expo/AppEntry.js",
  "version": "2.12.1",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "login": "expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD",
    "build:shared": "../scripts/build/build.sh",
    "build:web": "STAGE=$REACT_APP_STAGE expo build:web",
    "publish:web": "STAGE=$REACT_APP_STAGE expo publish --non-interactive",
    "test": "jest --passWithNoTests"
  },
  "dependencies": {
    "@apollo/client": "3.4.16",
    "@gorhom/bottom-sheet": "^4.1.5",
    "@hookform/resolvers": "^2.8.2",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/datetimepicker": "4.0.0",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/masked-view": "0.1.11",
    "@react-native-community/netinfo": "7.1.3",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-native-segmented-control/segmented-control": "2.4.0",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/core": "^6.1.0",
    "@react-navigation/elements": "^1.2.1",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "amazon-cognito-identity-js": "^5.2.0",
    "aws-amplify": "^4.3.10",
    "aws-amplify-react-native": "6.0.2",
    "aws-appsync": "4.1.4",
    "aws-appsync-auth-link": "3.0.7",
    "aws-appsync-subscription-link": "3.0.9",
    "card-validator": "^8.1.1",
    "expo": "^44.0.5",
    "expo-analytics": "^1.0.16",
    "expo-app-loading": "~1.3.0",
    "expo-asset": "~8.4.6",
    "expo-blur": "~11.0.0",
    "expo-branch": "~5.1.0",
    "expo-camera": "~12.1.0",
    "expo-constants": "~13.0.1",
    "expo-device": "~4.1.0",
    "expo-font": "~10.0.4",
    "expo-image-picker": "~12.0.1",
    "expo-linking": "~3.0.0",
    "expo-local-authentication": "~12.1.0",
    "expo-location": "~14.0.1",
    "expo-navigation-bar": "~1.1.1",
    "expo-notifications": "~0.14.0",
    "expo-permissions": "~13.1.0",
    "expo-secure-store": "~11.1.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-system-ui": "~1.1.0",
    "expo-updates": "~0.11.5",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-hook-form": "^7.17.2",
    "react-native": "0.64.3",
    "react-native-chart-kit": "^6.11.0",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-get-random-values": "~1.7.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-masked-text": "^1.13.0",
    "react-native-pager-view": "5.4.9",
    "react-native-paper": "^4.11.1",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "12.1.1",
    "react-native-tab-view": "^3.0.1",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-web": "0.17.1",
    "react-native-web-webview": "^1.0.2",
    "react-native-webview": "11.15.0",
    "react-native-youtube-iframe": "^2.0.1",
    "react-navigation-header-buttons": "7.0.1",
    "sentry-expo": "^4.0.0",
    "yup": "^0.32.10"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@expo/webpack-config": "~0.16.2",
    "babel-plugin-import-graphql": "^2.8.1",
    "file-loader": "^6.2.0",
    "jest-expo": "^44.0.0",
    "process": "^0.11.10",
    "react-refresh": "^0.10.0",
    "resolve-from": "^5.0.0"
  },
  "private": true,
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/babel.config.js",
      "!**/jest.setup.js"
    ],
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect"
    ]
  }
}

```

**Comment by grzabrodskiy** [comment]
Hi everyone,

I am experiencing the same issue. I just created a brand-new expo project and copied the example from expo-camera page. It gives me the same error (hooks), and works ok on iOS.

Also my old projects with camera continue to work. The only notable thing I have done recently is upgraded expo-cli to the latest version (5.3.0), but I don't see how it can be an issue.

**Comment by FibHeap** [comment]
We have the same issue. We identified that for some reason the `@kolae/useworker` package is installing react@16. If we delete `rm -rf node_modules/expo-camera/node_modules/react` it works. 

please see the  output of  `npm ls -a`
[npm.txt](https://github.com/expo/expo/files/8289351/npm.txt)

our quick fix is to add 
`"postinstall": "rm -rf node_modules/expo-camera/node_modules/react"`

**Comment by CodySwannGT** [comment]
Is there something else you did, because just deleting that module gives us this error: 

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: ENOENT: no such file or directory, open '/Users/cody/workspace/javascript/serverless/propswap/react-native-client/node_modules/expo-camera/node_modules/react/index.js'
```

**Comment by CodySwannGT** [comment]
scratch that. Just needed to restart the app

**Comment by YasinTeamProjekt** [comment]
> scratch that. Just needed to restart the app

Did you delete the package _@kolae/useworker_ to fix the issue?
Did it work after your restart?

**Comment by CodySwannGT** [comment]
Yes it worked after the restart. Thank you!

**Comment by FibHeap** [comment]
@byCedric could please take another look at this issue? The cause seems to be a mismatched react version.

**Comment by prog3dh-udesa** [comment]
> We have the same issue. We identified that for some reason the `@kolae/useworker` package is installing react@16 although all the rest is react@17. If we delete `rm -rf node_modules/expo-camera/node_modules/react` it works.
> 
> please see the output of `npm ls -a` [npm.txt](https://github.com/expo/expo/files/8289351/npm.txt)
> 
> ```
> │ ├─┬ @koale/useworker@4.0.2
> │ │ ├── dequal@1.0.1
> │ │ └─┬ react@16.14.0
> │ │   ├── loose-envify@1.4.0 deduped
> │ │   ├── object-assign@4.1.1 deduped
> │ │   └── prop-types@15.8.1 deduped
> ```
> 
> our quick fix is to add `"postinstall": "rm -rf node_modules/expo-camera/node_modules/react"`

This works for me, Thanks a lot!!

**Comment by dicklarsson** [comment]
You can fix this by using the "override" feature of package.json. Works like a charm.
This example forces every sub dependency to use React 18 regardless what they describe in their package.json. 
Hope it helps. Peace 🤍
```
,
  "overrides": {
    "react": "18.0.0"
  },
  ```

**Comment by sourabhsingla1997** [comment]
<img width="748" alt="Screenshot 2023-01-20 at 11 39 20 AM" src="https://user-images.githubusercontent.com/42861582/213629063-bed94b91-c02f-44a3-9a77-0a7882b8f71e.png">


Still getting this error, while upgrading to 
"react": "^18.2.0",
 "react-native": "^0.71.0",
 "expo": "^47.0.13",
"expo-camera": "~13.1.0"


tried: "postinstall": "rm -rf node_modules/expo-camera/node_modules/react"

**Comment by LucasATS** [comment]
> <img alt="Captura de tela 2023/01/20 às 11h39 20h" width="748" src="https://user-images.githubusercontent.com/42861582/213629063-bed94b91-c02f-44a3-9a77-0a7882b8f71e.png">
> 
> Ainda estou aceitando este erro ao atualizar para "react": "^18.2.0", "react-native": "^0.71.0", "expo": "^47.0.13", "expo-camera": " ~13.1.0"
> 
> tentei: "postinstall": "rm -rf node_modules/expo-camera/node_modules/react"

I also have this problem
