### ISSUE TITLE
Unable to resolve module expo-modules-core from expo-camera/build/Camera.js

### ISSUE THREAD

**Issue by frankied003** [expo/expo#16119]
### Summary

Been trying to install expo-camera for a few hours now and nothing is working. Keeps saying that expo-modules-core could not be found in node-modules, and it wasn't. I've tried installing expo-modules-core, but that led to a whole bunch of errors.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      npm: 6.14.11 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.65.1 => 0.65.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare

### Reproducible demo

No demo as of right now, will create one. Just want to get a start on this issue cause usually I'm able to solve library errors, but stuck here.

**Comment by byCedric** [comment]
Hi @frankied003! I think you are missing the `expo` package, that contains the core of our modules. Without that, the core system is missing and you'll run into this error. For more info: https://docs.expo.dev/bare/installing-expo-modules/

Hope this helps!

**Comment by Othniel-dell** [comment]
Hi,
check the directory and re-run npm install expo
and let see

i had a similar issue 
and what i did was to do npm uninstall expo and npm install expo again
i was however in the wrong directory ..
