### ISSUE TITLE
Redirect from successful AuthSession sign-in causes application bundle to reload

### ISSUE THREAD

**Issue by colinyoung** [expo/expo#1612]
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report: <snipped>

App Target: Android as a detached app
```

### Steps to Reproduce

1. Start XDE/exp packager
1. Plug in android device or start a Genymotion emulator
1. `cd android; ./gradlew installDevDebug`
1. On the app, click the button and login via FB
1. The app bundle reloads before the application is displayed again.

### Expected Behavior

1. Application does not reload bundle after using URL scheme to redirect back to detached app.

(Write what you thought would happen.)

1. Application does reload bundle, which interrupts the `AuthSession.startAsync` promise, and prevents successful login.

### Reproducible Demo

https://github.com/colinyoung/expo-auth-session-issue-example/

@brentvatne

**Comment by colinyoung** [comment]
Thank you @esamelson - I wasn’t sure if that other issue was a dupe or not. Should be said that, because the Linking.getInitialURL() is present, you can relatively easily extract the idToken from that url. Getting the refreshToken isn’t quite as easy though I think. Depends on the service.

**Comment by esamelson** [comment]
Hi @colinyoung - this has fixed with SDK 27, so I'm going to go ahead and close this issue.
