### ISSUE TITLE
Expo uses old app icons that have been deleted

### ISSUE THREAD

**Issue by armenavanesi** [expo/expo#16128]
### Summary

Add app icons to a fresh app and then build it. Then, delete the old app icons and add completely new ones. After building the app again, it is still built with the old ones. I know that this is not a device cache as the app shows up in my downloads list (pre-install) with the old icons. I have not tested this on iOS yet.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42 and 44

### Environment

```
  Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed
```

### Reproducible demo

- Create any project using `expo init`
- Build app using `expo build` e.g `expo build:android -t apk`
- Verify the app icon that is displayed on the downloaded apk
- Delete the icon files under assets, e.g `adaptive-icon.png`, etc. and add new ones
- Build the app again
- Download or install it. You will notice the original icons.

https://snack.expo.dev/@mutual/anxious-popsicle

**Comment by maxcotech** [comment]
why was this closed as completed? it hasnt even been fixed

**Comment by MatkoMilic** [comment]
same issue
