### ISSUE TITLE
Camera request: still/freeze frame during takePhotoAsync

### ISSUE THREAD

**Issue by wbyoung** [expo/expo#1613]
As requested by [the `react-native-camera` team](https://github.com/react-native-community/react-native-camera), I'm opening a duplicate issue here. Full description copied below of https://github.com/react-native-community/react-native-camera/issues/1438.

---

I'd like to be able to capture a photo and have the experience be similar to the built in camera. Currently, the video preview continues beyond pressing the shutter & then a preview will show a prior frame from the video. This feels very odd when using the camera vs. the native experience.

### Steps to reproduce

1. With a mounted `RNCamera` component, call `takePhotoAsync`
2. Replace component w/ `<Image source={ ... } />` with the `uri` from the capture

### Does it work with Expo Camera?

It probably works the same way. I'll open an issue there as well.

### Expected behaviour

The (video) preview should be able to be frozen during the capture of the still image to mimic what happens when using the built in camera. (At least on iOS, that's how it works. I presume Android is the same, but don't have a device.)

### Actual behaviour

The component continues to show the video preview beyond what will be the actual captured image leading to an inconsistent user experience vs. the built in camera.

### Environment
- **Node.js version**: 9.5.0
- **React Native version**: 0.54.2
- **React Native platform + platform version**: iOS 11.2.5

### react-native-camera
**Version**: 1.0.2

**Comment by esamelson** [comment]
Hi @wbyoung - thanks for the report. We're aware of this issue, and I think @aalices might be looking into a fix for this soon.

**Comment by wbyoung** [comment]
@esamelson @aalices thanks! Let me know if I can help in any way.

**Comment by aalices** [comment]
Hello @wbyoung this is a nice coincidence cause yesterday I created a very similar internal issue. I'm planning to - as you requested - add a preview freeze while the picture is being taken and also an ability to have a promise resolved right after the picture is taken but not yet saved as encoding and saving take much time (at least on Android, not that much on iOS). But I'm not yet sure when I'm going to be implement it

**Comment by jasongornall** [comment]
Just stumbled on this... why is this closed? how do I prevent the freeze frame when taking a takePhotoAsync?

**Comment by Ribeiro-Tiago** [comment]
@jasongornall the solution I found was to use to use the `onPictureSave` to handle my post-picture logic and when resolving the promise to use `this.camera.pausePreview()`. It's not as great as I'd like but it's relatively better. So something like: 

```
this.camera.takePictureAsync({
    onPictureSaved: (result) => {
        // do stuff with picture
    }
}).then(() => this.camera.pausePreview())
```

**Comment by Okipa** [comment]
This work well on iOS but prevent Android to do something in `onPictureSaved`.
