### ISSUE TITLE
[expo-image-picker] launchImageLibraryAsync not saving file locally on ios

### ISSUE THREAD

**Issue by austintackaberry** [expo/expo#16136]
### Summary

On iOS, `launchImageLibraryAsync` appears to work without errors, but when I go to upload the file, it is not available. I checked the application data and found that the image was not saved locally.

I have seen this behavior running Debug mode on physical iPhone 8 Plus with iOS 15.3. `launchCameraAsync` works without any issues.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      npm: 8.1.4 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Reproducible demo

When I run the code below, and check the `response.uri`, it is not in the application data.
```
const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync()
if (status === "granted") {
  const response = await ImagePicker.launchImageLibraryAsync({
    mediaTypes: ImagePicker.MediaTypeOptions.Images,
    base64: false,
    exif: false,
  })
console.log(response)
}
```

Example response:
```
{
   height: 4032,
   uri: 'file:///var/mobile/Containers/Data/Application/7BF4E3CF-F201-471E-B7D3-AF11AD7AFDC8/Library/Caches/ImagePicker/04FF0291-5B0F-43C4-9001-96B67615D273.jpg',
   type: 'image',
   width: 3024,
   cancelled: false
}
```

**Comment by austintackaberry** [comment]
I have discovered that this issue only happens when "Optimize iPhone Storage" setting is on

![Image from iOS (1)](https://user-images.githubusercontent.com/29493001/151680618-30d055cb-eed7-479b-9184-d07efd291465.png)

**Comment by kelley-sharp** [comment]
Hi @austintackaberry! We can't reproduce this uri not-being present, even with icloud optimized storage available. The example response seems fine to me, the uri of the image is scoped to the app's folder.  You mentioned 

> "but when I go to upload the file, it is not available",

but you didn't share how you upload that image. Could you provide the code and a bit more context to what is failing for you exactly?

**Comment by AlexandreMouyen** [comment]
Hello there, 

I have the same problem on iOS and Android. Some images seem to be not saved on FileSystem.

I checked right after launchImageLibraryAsync the return of FileSystem.getInfoAsync() and exists is false.

**Comment by Neiso** [comment]
Don't know if my problem is similar but **launchImageLibraryAsync** works fine, I'm able to use the uri to display the image in an `<Image source={{uri: result.uri}} />` component but when trying to get info with ** FileSystem.getInfoAsync** app crashes only on iOS with absolutely no error, warning, whatever In expo go
