### ISSUE TITLE
Installing the dev client replaces the real app

### ISSUE THREAD

**Issue by konstantinlois** [expo/expo#16138]
### Summary

Hello there, thanks for taking the time to look into this. This might not be a bug report in the traditional sense, but i'd still like to bring it up.

When I try to install the internal distribution build of my app (custom dev client), which I've generated with eas, on my device, it tries to update the real standalone app (the one that I've already submitted to Play Store). When I accept the app to be "updated" it fails. If I uninstall the standalone app and try to install the custom dev client afterwards it works. So my question is: Is this the intended behavior? For me it would be very useful to keep the real standalone app on my phone and not having to delete it everytime I want to work on the app.

Thanks again for your time.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~0.8.2"

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

1. Create fresh Expo project (expo init etc.)
2. Create standalone app (for example via eas)
3. Install standalone app on device
4. Create internal distribution build (custom dev client) via eas
5. Download internal distribution build to device
6. Try to install it

Problem: dev client doesn't install as long as standalone app is installed (tries to replace it and fails)

Note: Tested on Samsung Galaxy S8 Edge

**Comment by kbrandwijk** [comment]
This behavior is intended, if the bundle/package identifier doesn't change between the development client and the production build, both Android and iOS will consider it to be the same app, it is in fact the _only_ thing the OS looks at.
You could build your development client with a different identifier (manually or through some app.config.js logic), but be aware that things that depend on the app identifier (notifications and possible other integrations?) could have an issue with that.

**Comment by konstantinlois** [comment]
Thank you for the quick response.

I see now why it might be useful to have the same bundle identifier (notifications etc.). Though in my case I would still prefer using a different bundle identifier instead of having to uninstall the app everytime. Do you maybe have a quick 1 liner at hand on how one might go about this in the app.config.js (i.e. how to differentiate between standalone and dev client)? I suppose one could maybe make use of the global __DEV__ variable?

Thanks again for the help.

**Comment by kbrandwijk** [comment]
You can define an environment variable in your eas build profile, that you read in app.config.js.

**Comment by konstantinlois** [comment]
Ah right, that's the way. Thanks!

**Comment by brentvatne** [comment]
this doc is a good guide on how to install multiple variants of your app on a single device: https://docs.expo.dev/build-reference/variants/

**Comment by konstantinlois** [comment]
Must have overlooked that one. Great examples, thanks!
