### ISSUE TITLE
Error for conditional exports

### ISSUE THREAD

**Issue by SimonAM** [expo/expo#16130]
### Summary

Importing a library using conditional exports fails. That is, the library that exports two versions:

- One for cjs in packagename/dist/cjs
- One for ES-modules in packagename/dist/esm

 See also [stackoverflow question](https://stackoverflow.com/questions/70760119/importing-hybrid-package-in-react-native-typescript-expo). 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      npm: 8.1.4 - ~/.nvm/versions/node/v14.16.0/bin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

```
expo init hybrid-test-app
npm i fp-ts-std --save
```

Then in any file: 
```
import {pick} from "fp-ts-std/Record";
pick(["hello"], {hello: "world"})
```

(cant provide snack, since the package "fp-ts-std" is not available.

**Comment by byCedric** [comment]
Hi @SimonAM! Thanks for writing in, it seems that you are running into the same issue as `@apollo/client@3.5.4` ran into with Metro. Metro simply doesn't support the cjs/esm syntaxes and extensions yet. You can fix that by adding a `metro.config.js` with these extensions.

But be aware, `fp-ts-std` uses regex expressions that aren't supported in the default JS runtime of React Native. The functionality they use is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes, but that won't work in React Native. I would recommend opening an issue on their repo to try and get this fixed.

To at least get Metro in a working state:

```
$ expo init AwesomeApp
$ expo install fp-ts-std
$ expo install fp-ts monocle-ts newtype-ts // Add the required peer deps
``` 

Then, create a **metro.config.js** file with the following content:

```
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);
// Add support for cjs/esm modules
config.resolver.sourceExts.push('cjs');

module.exports = config;
```

Hope this helps!
