### ISSUE TITLE
Erro on building - React/UIView+React.h file not found

### ISSUE THREAD

**Issue by raisiqueira** [expo/expo#1614]
Hi! I ejected my app created with _CRNA_, i selected "export with ExpoKit". After the process has finished, i run the "pod install" command from ios folder, but on xCode after building return the error: React/UIView+React.h file not found

![captura de tela 2018-04-06 as 09 21 04](https://user-images.githubusercontent.com/2914170/38421127-7ccc63a4-397c-11e8-98e9-bfd97f421309.png)

![captura de tela 2018-04-06 as 09 17 34](https://user-images.githubusercontent.com/2914170/38421131-80c292a8-397c-11e8-9e01-b99a790483da.png)

**Diagnostic**

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.4.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/raisiqueira-8bff2630-e123-428b-b3a3-391b6db35fdc.tar.gz

**Comment by raisiqueira** [comment]
I downgraded _CocoaPods_ to 1.4 and its works perfectly!

**Comment by appjitsu** [comment]
@raisiqueira what command did you use to do that?

**Comment by appjitsu** [comment]
nvm i figured it out.

sudo gem uninstall cocoapods
sudo gem install cocoapods -v 1.4.0

works great!

**Comment by terribleben** [comment]
Hey all, as this thread shows, there was a problem with ExpoKit and CocoaPods 1.5.0 (which was just released a week ago).

I just pushed a newer ExpoKit tag, `ios/2.4.8`, which is compatible with CocoaPods 1.5.0. So downgrading CocoaPods is no longer needed, as long as you use the newer ExpoKit tag.

**Comment by iuliuvisovan** [comment]
This terribleben guy needs a statue

**Comment by kiidbrian** [comment]
@terriblebean you're a hero

**Comment by articobandurini** [comment]
Excuse me for a stupid question, but how to switch to ExpoKit tag ios/2.4.8 ?

**Comment by Zak-JS** [comment]
@articobandurini Inside your pod file (in the iOS directory), look for ExpoKit and there will be a tag number there that you can change. Then just run a pod install.

**Comment by lanceharper** [comment]
After updating to `ios/2.4.8`, `UEXGL.h` is not found.

**Comment by iuliuvisovan** [comment]
Do you have "GL" as a ExpoKit subspec dependency? (in Podfile, under "ExpoKit", where you should also have "CPP" and "Core" already you should also have "GL") (source)[https://blog.expo.io/expo-sdk-v26-0-0-is-now-available-2be6d9805b31]

**Comment by lanceharper** [comment]
@iuliuvisovan Gah - I neglected to go through the blog post in as much detail as I should have. First time detaching and then upgrading with Cocoapods so I missed a step. Thank you so much!

**Comment by watadarkstar** [comment]
Upgrading to `ios/2.4.8` worked for me. Thanks you!

**Comment by fcaride** [comment]
Somehow Upgrading to ios/2.4.8 it makes me stop working my native library, its like its not loading, any thoughts? 😢

**Comment by watadarkstar** [comment]
Make sure you follow the blog post to upgrade to SDK 26/27

**Comment by fcaride** [comment]
Yeah, i had to remove the app from the device before installing it. I think its a bug of expo. Because i have to remove it every time i push play in xcode. If not my library wont work :/

**Comment by nitishdhar** [comment]
Updated to ios/2.4.8, now getting 

No visible @interface for 'EXViewController' declares the selector 'loadReactApplication'

file AppDelegate.m (line 23)
