### ISSUE TITLE
ImagePicker videoMaxDuration not working on iPhone

### ISSUE THREAD

**Issue by haibert** [expo/expo#16146]
### Summary

I have set the videoMaxDuration value to 10, for 10 seconds, but when the Camera Roll launches I can select videos that are greater than 10 seconds in length. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.12.20.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.44.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@haibert/videomaxduration-issue

Make sure to screen record something for more than 10 seconds so you have a video longer than 10 seconds in your camera roll. Then you will see that you can still see the videos that are longer than 10 seconds.

**Comment by emmbyiringiro** [comment]
`videoMaxDuration` works well with camera recording. For uploaded video, always check whether video duration exceeds your app limit threshold before uploadingg

**Comment by haibert** [comment]
I see, thank you for clarifying 👍🏻
