### ISSUE TITLE
Dev Client build failed for iOS

### ISSUE THREAD

**Issue by p4bl1t0** [expo/expo#16147]
### Build/Submit details page URL

https://expo.dev/accounts/pablo_botta/projects/rn-webrtc/builds/e5549006-36a6-405f-ac4c-181524702ec2

### Summary

iOS dev client build is failing while Android is working. The projects has only the react-native-web-rtc package.

### Managed or bare?

Managed

### Environment

```
➜  rn-webrtc git:(master) ✗ eas diagnostics

  EAS CLI 0.45.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    Utilities:
      Git: 2.8.1 - /usr/local/bin/git
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      expo-dev-client: ~0.8.0 => 0.8.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 4.2.1
    Project workflow: managed
```

### Error output

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios12.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/DoubleConversion -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/EXApplication -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/EXConstants -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/EXErrorRecovery -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/EXFont -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/EXJSONUtils -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/EXKeepAwake -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/EXManifests -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/EXUpdatesInterface -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/Expo -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/ExpoModulesCore -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/FBReactNativeSpec -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/RCT-Folly -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/RCTTypeSafety -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-Core -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-CoreModules -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-RCTAnimation -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-RCTBlob -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-RCTImage -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-RCTLinking -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-RCTNetwork -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-RCTSettings -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-RCTText -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-RCTVibration -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-cxxreact -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-jsi -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-jsiexecutor -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-jsinspector -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/React-perflogger -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/ReactCommon -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/Yoga -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/expo-dev-launcher -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/expo-dev-menu -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/expo-dev-menu-interface -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/glog -L/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/react-native-webrtc -F/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos -F/Users/expo/workingdir/build/ios/Pods/../../node_modules/expo-file-system/ios -F/Users/expo/workingdir/build/ios/Pods/../../node_modules/expo-splash-screen/ios -F/Users/expo/workingdir/build/ios/Pods/../../node_modules/react-native-webrtc/apple -F/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/XCFrameworkIntermediates/EXFileSystem -F/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/XCFrameworkIntermediates/EXSplashScreen -F/Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos/XCFrameworkIntermediates/WebRTC -filelist /Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/IntermediateBuildFilesPath/rnwebrtc.build/Debug-iphoneos/rnwebrtc.build/Objects-normal/arm64/rnwebrtc.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/IntermediateBuildFilesPath/rnwebrtc.build/Debug-iphoneos/rnwebrtc.build/Objects-normal/arm64/rnwebrtc_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/BuildProductsPath/Debug-iphoneos -Xlinker -final_output -Xlinker /Applications/rnwebrtc.app/rnwebrtc -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/IntermediateBuildFilesPath/rnwebrtc.build/Debug-iphoneos/rnwebrtc.build/Objects-normal/arm64/rnwebrtc.swiftmodule -ObjC -lDoubleConversion -lEXApplication -lEXConstants -lEXErrorRecovery -lEXFont -lEXJSONUtils -lEXKeepAwake -lEXManifests -lEXUpdatesInterface -lExpo -lExpoModulesCore -lFBReactNativeSpec -lRCT-Folly -lRCTTypeSafety -lReact-Core -lReact-CoreModules -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReact-perflogger -lReactCommon -lYoga -lc -lexpo-dev-launcher -lexpo-dev-menu -lexpo-dev-menu-interface -lglog -lreact-native-webrtc -lsqlite3 -lstdc++ -framework AVFoundation -framework AudioToolbox -framework CoreAudio -framework CoreGraphics -framework CoreVideo -framework EXFileSystem -framework EXSplashScreen -framework GLKit -framework JavaScriptCore -framework MobileCoreServices -framework VideoToolbox -framework WebRTC -ObjC -lc++ -lPods-rnwebrtc -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/IntermediateBuildFilesPath/rnwebrtc.build/Debug-iphoneos/rnwebrtc.build/Objects-normal/arm64/rnwebrtc_dependency_info.dat -o /Users/expo/Library/Developer/Xcode/DerivedData/rnwebrtc-adpobnwgwznprfbjaqulrrsjtzpm/Build/Intermediates.noindex/ArchiveIntermediates/rnwebrtc/InstallationBuildProductsLocation/Applications/rnwebrtc.app/rnwebrtc
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Reproducible demo or steps to reproduce from a blank project

Setup project
```
expo init project (mangaed)
yarn install react-native-webrtc @config-plugins/react-native-webrtc expo-dev-client
eas build --profile development --platform ios 
```

app.json is:

```
{
  "expo": {
    "name": "rn-webrtc",
    "slug": "rn-webrtc",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.movilizame.rn-webrtc"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.movilizame.rtc"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "@config-plugins/react-native-webrtc",
        {
          "cameraPermission": "Allow $(PRODUCT_NAME) to access your camera",
          "microphonePermission": "Allow $(PRODUCT_NAME) to access your microphone"
        }
      ]
    ]
  }
}
```
iOS dev client build is failing while Android is working. The projects has only the react-native-web-rtc package. Already tryed switching the build ios image. 

eas.json is:
```
{
  "cli": {
    "version": ">= 0.45.1"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "image": "macos-big-sur-11.4-xcode-12.5"
      }
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

```

also try with: macos-big-sur-11.4-xcode-13.0

**Comment by kbrandwijk** [comment]
I've transferred the issue to the expo/expo repo, because the remaining issue isn't an issue with the EAS CLI, but rather either with the webrtc package in combination with Expo.

**Comment by brentvatne** [comment]
the config plugin should be fixed to disable bitcode properly as of version 2.0.1, with this commit: https://github.com/expo/config-plugins/commit/8ed4e44aee06b1f692ceb2778b53e6741c431836

**Comment by p4bl1t0** [comment]
Hi! Thanks!

This is the code I was working on. Just the webrtc + expo with the example code:

https://github.com/p4bl1t0/rn-webrtc
