### ISSUE TITLE
Android Face Unlock - cancel breaks biometrics auth

### ISSUE THREAD

**Issue by gregdburns** [expo/expo#16155]
### Summary

When an Android user has a phone with Face Unlock, biometrics authentication will break when they press the cancel button that is launched on the OS.  This is potentially only on certain Android devices (Samsung).

To reproduce (see linked Expo snack):

- Use an Android app with Face Unlock capabilities.  Face Unlock should be enabled on the device.
- Open Mobile app 
- Observe the following:
- [ ] Supported Auth Types: should show Face biometrics
- [ ] Has Hardware: should be true
- [ ] Is Enrolled: should be true
- [ ] Enrolled Level: should be 2
- Press the "Authenticate" button
- Scan face when prompted
- Press the "cancel" button, rather than the "proceed" button

After doing this, the OS biometrics UI will close, but pressing on the "Authenticate" button will no longer relaunch the biometrics authentication.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed

Reproduced on this device:
Android 11
Samsung Galaxy A51
Model Number SM-A515U1
One UI Version: 3.1

### Reproducible demo

https://snack.expo.dev/@blackline/android-face-unlock-bug

**Comment by zbagdzevicius** [comment]
I reproduce the same, seems like I have created duplicate ticket https://github.com/expo/expo/issues/16705

**Comment by gregdburns** [comment]
Bumping this to avoid auto-close.

**Comment by gregdburns** [comment]
Not stale

**Comment by JuanRdBO** [comment]
Not stale. I have this error too on the latest version
