### ISSUE TITLE
EAS Build: When using FCM to send notifications for Android, the notification icon does not show up. 

### ISSUE THREAD

**Issue by ankitmaloo** [expo/expo#16159]
### Summary

So, I have a social media app, and instead of using Expo to send notifications (which fail if the app is in background or device caching is strict like it is on One Plus, Oppo, Redmi etc) I was using Firebase to send notifications. 

The notification icon does not show up. I tried two ways. 

1. through the normal app json
```
 "expo": {
...
    "notification":{
      "icon":"./assets/android/mipmap-xhdpi/icon_name.png"
    },
...
  }
```

2. Config plugin
```
 "expo": {
    "notification":{
      "icon":"./assets/android/mipmap-xhdpi/icon_name.png"
    },
    "plugins": [
      [
        "expo-notifications",
        {
          "icon": "./assets/android/mipmap-xhdpi/icon_name.png",
          "color": "#27c4d9"
        }
      ]
    ]
  }
```

In both the cases there is a grey space when I send notification using FCM legacy api (https://fcm.googleapis.com/fcm/send) 

Please help. Am I missing something? The sizes are what you get from Android studio. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.1.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.17.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

1. Try for EAS build
2. Have the android assets and icons as specified by Google and Android
3. In App Json, use the config plugin to set expo notifications. 
4. Use FCM legacy API to send notifications.
(A word of caution here: Use the notification key to send notifications. The reason is that data does not work if app is not running in background, and many users have complained about not getting notifications. notification key works everywhere. It's just an update notification, not something users would need to tap on)
5. See the notification show up. Instead of icon when you see the notification you see a grey space. Depending on the icon set, sometimes that space is round, else it is square.

**Comment by joelodd** [comment]
@ankitmaloo Did you manage to resolve this? Do your remember how you did it?

Can you please share?

Thank you.

**Comment by andrisole92** [comment]
@joelodd I solved it....

You need a specific Icon format, I believe square 96x96 px...

You can use this generator: https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit

It has to be white icon on transparent background...

And specify in config like this:


```

{
	"expo": {
               ...
		"notification": {
			"icon": "./assets/icon_sq_96.png",
			"color": "#373092"
		},
		...
```
