### ISSUE TITLE
expo in monorepo - fresh install error: expected hoisted manifest for \"metro-react-native-babel-preset#@babel/core#@babel/helper-compilation-targets#browserslist\"

### ISSUE THREAD

**Issue by i8ramin** [expo/expo#16153]
### Summary

Adding a new expo project to an existing monorepo by [following the docs here](https://docs.expo.dev/guides/monorepos/). this is a fresh install using the blank project with TS. when running `yarn install`, getting the following error:

```
error An unexpected error occurred: "expected hoisted manifest for \"metro-react-native-babel-preset#@babel/core#@babel/helper-compilation-targets#browserslist\"".
```

Removing `yarn.lock` and issuing `yarn install` does seem to solve the problem, but that is not a viable option for us. Any ideas what could be causing this?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS, Web

### Environment

```
❯ expo diagnostics

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.18.0 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed
````

### Reproducible demo

```
> expo init packages/mobile --no-install --yarn

# followed instructions at https://docs.expo.dev/guides/monorepos/ and made appropriate changes

# from root of monorepo
> yarn install 

error An unexpected error occurred: "expected hoisted manifest for \"metro-react-native-babel-preset#@babel/core#@babel/helper-compilation-targets#browserslist\"".

info If you think this is a bug, please open a bug report with the information provided in "/Users/ramin/Work/carrot/yarn-error.log".

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by i8ramin** [comment]
Not sure if is a true solution, but manually adding this to the expo package devDependencies seems to have fixed the issue (for now). will report back if it continues to happen after this:
```
  "devDependencies": {
    ....
    "metro-react-native-babel-preset": "~0.64.0",
  },
```

**Comment by brentvatne** [comment]
hi there! i followed these instructions a couple days ago and had no issues. please share a reproducible example and we're happy to investigate!

**Comment by ariccio** [comment]
No idea what's going on, but I'm hitting this same error when doing an `expo upgrade`. I had to discover (and turn on) the `EXPO_DEBUG` environment variable (`expo upgrade` apparently supports this, but is undocumented) to get the yarn error message:

```
An unexpected error occurred: "expected hoisted manifest for \"babel-preset-expo#metro-react-native-babel-preset#@babel/core#@babel/helper-compilation-targets#browserslist\"".
```

Let me see if I can work around this?

**Comment by ariccio** [comment]
Hmm, no. I'll have to work on this later.
Possibly related issues:
https://github.com/yarnpkg/yarn/issues/7244
https://github.com/yarnpkg/yarn/pull/1866
https://github.com/yarnpkg/yarn/issues/1861
https://github.com/MaxLeiter/sortablejs-vue3/issues/1
https://github.com/polkadot-js/common/issues/921
https://github.com/razorpay/react-native-razorpay/issues/108

**Comment by hirbod** [comment]
I had a similar issue when I was trying to upgrade from SDK 44 to SDK 45.
I tried different approaches but what did just work fine for me was to delete `yarn.lock` and `node_modules` and hit "yarn" afterwards - thats it, bug was gone.

**Comment by flexbox** [comment]
confirmed here as well

```
An unexpected error occurred: "expected hoisted manifest for \"metro-react-native-babel-transformer#@babel/core#@babel/helper-compilation-targets#browserslist\""
```

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/360936/216089919-52259b47-4db0-41f9-af13-54360de538a9.png">

following @hirbod solution fixed the issue

here is a PR as an example https://github.com/flexbox/react-native-bootcamp/pull/149/commits/12cd8c42cdca2c66589aec75abef327e77076f7e

**Comment by conoremclaughlin** [comment]
Same issue running `expo upgrade` or `npx expo install --fix` to get to v48. Fixed with @hirbod's solution.

**Comment by pranshuchittora** [comment]
Was happening due to dep version mismatch. 
These are the versions which has worked for me

```
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.9",
    "@babel/preset-env": "^7.14.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "metro-react-native-babel-preset": "^0.73.5"
```
