### ISSUE TITLE
ImagePicker dont work when Display size changed

### ISSUE THREAD

**Issue by x4AEKx** [expo/expo#16150]
### Summary

When change Display Size in device (Settings > Display > Advanced > Display Size [change Display size other than default] )
ImagePicker.launchImageLibraryAsync doesnt work

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Expo CLI 4.12.0 environment info:
    System:
      OS: Linux 5.11 Ubuntu Impish Indri (development branch) 21.10 (Impish Indri)
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 12.21.0 - /usr/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.13.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    IDEs:
      Android Studio: AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ^39.0.0 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: bare

### Reproducible demo

When change Display Size in device (Settings > Display > Advanced > Display Size [change Display size other than default] )
ImagePicker.launchImageLibraryAsync doesnt work

**Comment by brentvatne** [comment]
it looks like your project uses expo sdk 39, which is over a year old. if you can reproduce this on sdk 44 please create a new issue with a reproducible example
