### ISSUE TITLE
'ExpoModulesCore/ExpoModulesCore.h' file not found

### ISSUE THREAD

**Issue by Preshonyee** [expo/expo#16169]
### Summary

When I run `eas build --platform ios` for both the bare and managed workflow, I get the error "Fastlane build failed with unknown error".

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

"@expo/vector-icons": "^12.0.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "axios": "^0.25.0",
    "expo": "~44.0.0",
    "expo-asset": "~8.4.4",
    "expo-constants": "~13.0.0",
    "expo-dev-client": "~0.8.3",
    "expo-font": "~10.0.4",
    "expo-linking": "~3.0.0",
    "expo-splash-screen": "~0.14.0",
    "expo-status-bar": "~1.2.0",
    "expo-web-browser": "~10.1.0",
    "radnik": "^0.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-autogrow-textinput": "^5.4.0",
    "react-native-feather": "^1.1.2",
    "react-native-gesture-handler": "^2.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-reanimated": "^2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1",
    "rn-keyboard-sticky-view": "^1.0.4"

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.4.0 - /opt/homebrew/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 8.3.1 - /opt/homebrew/bin/npm
      Watchman: 2021.08.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

![CleanShot 2022-02-02 at 17 43 59@2x](https://user-images.githubusercontent.com/19210093/152198143-726d9575-33da-4991-a14d-5e5503f3a9c3.png)

**Comment by brentvatne** [comment]
https://docs.expo.dev/build-reference/troubleshooting/

**Comment by KrisLau** [comment]
@Preshonyee did you ever figure this out?

**Comment by niloriver** [comment]
This bug is very real. 

I'm struggling right now with this.
If I found a solution I'll come back here.

**Comment by KrisLau** [comment]
> This bug is very real.
> 
> I'm struggling right now with this. If I found a solution I'll come back here.

Might be this https://github.com/expo/expo/issues/15783#issuecomment-1005153199

**Comment by onedanshow** [comment]
What worked for me was updating the iOS target deployment to `13.0`. Was on `7.0` before. Clearly safe to do so: https://developer.apple.com/support/app-store/

**Comment by onedanshow** [comment]
Actually, the trick was to add `expo-modules-core` into `package.json` directly (instead of as a dependency). So `yarn add expo-modules-core`.

**Comment by brentvatne** [comment]
@onedanshow - that should definitely not be necessary - the expo package brings this dependency in. perhaps you have an older version of the expo package installed in your project? can you share your package.json?

**Comment by onedanshow** [comment]
@brentvatne You are correct. I had an old `@types/expo` down the dev dependencies I hadn't noticed that was outdated and causing issue. I had inherited this app and didn't notice that!

**Comment by christianrank** [comment]
Another hint for anyone who is stuck on this error:

For me it was solved by uninstalling `react-native-unimodules`.
