### ISSUE TITLE
iOS: Whiles a Modal is open, first Alert Dialog or ActionSheet shows underneath Modal

### ISSUE THREAD

**Issue by trevorkirpaul** [expo/expo#1616]
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.2.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: ^16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/trevorkirpaul-5de24453-f1c5-411c-bbcd-8afe85a8e25b.tar.gz
```

Target Platform: **iOS**

### Steps to Reproduce

`iOS device or iOS simulator only`
1. Open a modal
2. Open an alert
3. First alert shows up underneath the modal. All of the following alerts show up as intended, in front of the modal. This issue also happened with [actionSheets](https://facebook.github.io/react-native/docs/actionsheetios.html). That first 'orphan' alert will linger behind after the modal is closed.

### Expected Behavior

I expect the first modal or actionSheet to be visible and in front of the modal. I also expect it to not linger behind when the modal is closed.

### Actual Behavior

First alert that fires will pop up underneath the modal. Following alerts will show up as intended, in front of the modal.

This issue also happens with [actionSheets](https://facebook.github.io/react-native/docs/actionsheetios.html).

<a href="https://cl.ly/41421D1M1t0F" target="_blank"><img src="https://d2ffutrenqvap3.cloudfront.net/items/2b1y0y40342Q1j0q3B46/Screen%20Recording%202018-04-06%20at%2011.24%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>

### Reproducible Demo

[Published project](https://expo.io/@trevorkirpaul/modal-modal-bug)
[Repo](https://github.com/trevorkirpaul/modal-issue)

**Comment by trevor-atlas** [comment]
This issue also happens with `ImagePicker.launchImageLibraryAsync()` and `ImagePicker.launchCameraAsync()` and occurs with the react-native `Modal` and https://github.com/react-native-community/react-native-modal which is a commonly suggested replacement

**Comment by trevorkirpaul** [comment]
I'm still getting the issue if I use that library.
I tested it in the [giithub repo] I linked.

**Comment by brentvatne** [comment]
Hi people!

You can use the Expo Modal API instead of the React Native one, like this: https://snack.expo.io/ByEqo7Bif

I’ll work on getting some documentation up shortly. The main differences between the react-native Modal API and this are:

- you need to use ModalHost at the root of your app, like a Provider. you should also ideally put it inside of any Providers so it has the same context available
- only the context that is available to the ModalHost is available to Modal

**Comment by ericmorgan1** [comment]
See discussion in this thread for additional details.
https://forums.expo.io/t/actionsheetios-alert-appear-behind-modal/8338

**Comment by cantide5ga** [comment]
Still in my investigation phase on the migration from `react-native-modal` to fix this (thanks for the work-around), but is anyone using `<ModalHost />` along with Redux `<Provider />` and `redux-thunk`?  Dispatch has stopped working when we wrap the app with `<ModalHost />`, but within Redux `<Provider />`.

**Comment by LouisJS** [comment]
Would be nice to have a simple animation at the Modal opening. 💪

**Comment by trevorkirpaul** [comment]
Since I'm also using react-navigation, I'm wrapping my root stack nav in ModalHost. I'm not noticing any issues at all with redux.

If you're also using react-navigation then perhaps that could help

**Comment by brentvatne** [comment]
@trevor-atlas - please read my comment carefully and then describe whether or not you have actually followed it, and what you mean by "breaks" -- your comment is far too vague to possibly provide you with any assistance

> The main differences between the react-native Modal API and this are:
>
> - you need to use ModalHost at the root of your app, like a Provider. you should also ideally put it inside of any Providers so it has the same context available
> - only the context that is available to the ModalHost is available to Modal

**Comment by dylancompanjen** [comment]
It breaks Modals that are using a StackNavigator inside.

**Comment by forkbomb** [comment]
The solution with ModalHost saved my life! thx bro!

**Comment by dylancompanjen** [comment]
I was trying the ModalHost / Modal solution from Expo again but found that the same bug also appears when using a nested Modal.

**Comment by appjitsu** [comment]
I really really really don't want to have to switch my modal code over. This would be a huge pain in the ass. When is the bug going to be fixed? This is affecting our app for ios store review.

**Comment by terribleben** [comment]
We're expecting to ship a native fix for this next week.

**Comment by appjitsu** [comment]
Awesome!

**Comment by appjitsu** [comment]
Any news on this?

**Comment by jordyvanraaij** [comment]
I'm still patiently waiting for this fix as well.. any updates on the estimate?

**Comment by terribleben** [comment]
We released iOS 2.5.9, with a fix for this, today. It's available in the app store, simulator build, and also in our `exp build:ios` servers.

**Comment by jordyvanraaij** [comment]
Thanks Ben, great job!

**Comment by appjitsu** [comment]
@terribleben thanks! Is there release notes for this?

**Comment by AndrewSouthpaw** [comment]
Still noticing strange behavior for modals + alerts in iOS (at least), this time related to dismissing the modal while alerting: #1883.
