### ISSUE TITLE
EAS build: SecureStore returns null for all keys after upgrading to a binary built with EAS

### ISSUE THREAD

**Issue by numsu** [expo/expo#16175]
### Summary

I have a production build of my app built with SDK version 38 using `expo build`. I am upgrading my app from SDK version 38 to 44 along with a bunch of changes.

If I build the app with `eas build` and release the application in TestFlight or for internal testing in Google Play, the app no longer has any access to the previous information stored in SecureStore. They return null.

However, if I build the app with `expo build` and release it, the app has access to the information.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^44.0.0 => 44.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.5 => 0.17.5
      react-navigation: 4.4.4 => 4.4.4
    Expo Workflow: managed

### Reproducible demo

1. Create a new app that uses SecureStore
2. Build the application using `expo build`
3. Publish the application to TestFlight or Google Play (a simple apk installation might suffice) and install it on a device
4. Store something to SecureStore
5. Build the application again using a different version code with `eas build`
6. Install the new version to the device
7. Try to get the information stored in previous version, it returns null
8. Downgrade the version
9. Confirm that again, you do have access to the information stored

**Comment by travisseh** [comment]
Same thing happens to me but only sometimes (we have an app in beta right now and just recently switched to EAS build and it's happened to a few users but not everyone)

**Comment by martin-ecatch** [comment]
I just noticed the same problem after switching to EAS build. It works fine if I build using "expo build". It only affects iOS.
There are some differences in the build metadata (visible in AppStoreConnect), one thing that jumps out is that the "keychain-access-groups" is missing from the entitlements for builds using "eas build". Could that be the cause of the problem?

**Comment by martin-ecatch** [comment]
Update: my suspicion was correct. Adding the missing keychain-access-groups into app.json (in ios -> entitlements) fixed it.
This is an easy workaround.
It's a bug in eas build + SecureStore that should probably be addressed... Anybody able to fix it in expo and submit a PR for that?

**Comment by pranavtad** [comment]
We are having this same exact issue migrating from `expo build` to `eas build`. @martin-ecatch it seems that you were able to resolve using keychain-access-groups. Trying to implement this but having some trouble figuring out the right configuration. Would you be able to shed a little bit more insight as to how you implemented the workaround?

**Comment by martin-ecatch** [comment]
Just add the following into your app.json:
  "ios": {
    "entitlements": {
      "keychain-access-groups": ["XXXXXXXX.*", "com.apple.token"]
    },
  },
where XXXXXXXX is your apple "Team ID". How to find out your Team ID? Login to App Store Connect, click on your name (right top corner), then "Edit Profile" and it'll take you to a screen that will have "Team ID" on it.

Another way to see/check this is go to your app in App Store Connect -> TestFlight tab -> pick a build -> Build Metadata and at the bottom there's Store Information section that has "Entitlements". You should see "keychain-access-groups: ( "XXXXXXX.*", "com.apple.token" ).

Hope it helps.

**Comment by jtrotoux** [comment]
I confirm @martin-ecatch solution ! Thank you so much !

**Comment by patwritescode** [comment]
@martin-ecatch thank you for writing all this up. This was extremely helpful for us having the same issue.

**Comment by gregdburns** [comment]
We also experienced this issue when migrating from expo build to EAS.  @martin-ecatch - thanks a ton for the workaround!  Worked like a charm.

**Comment by animaonline** [comment]
This happened to my app after building it with EAS, however it has also happened afterwards, would appreciate some official input from Expo.

**Comment by gregdburns** [comment]
@animaonline you mean that the issue still happens after you apply the workaround that Martin came up with?  If so, you may want to run `eas config` and verify that your entitlements are set up with the correct values.

**Comment by animaonline** [comment]
@gregdburns I applied Martin's workaround yesterday, so I'm not certain that it'll do the trick, fingers crossed, though.

**Comment by entiendoNull** [comment]
In my case it seems only like certain items cannot be retrieved from the secure store, while others can. 
When running the app through ExpoGO I experience no problems at all. But at Testflight, some of the data stored in the SecureStore is retrievable while other only returns `null`.
I have tried @martin-ecatch approach, and the app builds just fine but the same issue persists.

I am using the managed workflow, and ExpoSDK45

**Comment by numsu** [comment]
Still not resolved. It's weird to have a bot to delete issues when discussion ends even if no member of Expo has acknowledged the issue.

**Comment by Dulatech** [comment]
I also getting a similar issue. I have recently updated to SDK 47 for my mobile app and switched to EAS build from Classic Build. 

I can build my app fine but when I publish it, the AsyncStorage/SecureStore data does not transfer between the versions of the iOS app on TestFlight.

@martin-ecatch I have even set up my Entitlements in my app.json for iOS:
```
"entitlements": {
        "keychain-access-groups": ["XXXXXXXX.*", "com.apple.token"]
      } 
```

Could it still be my entitlements? It seems my iOS EAS build and Classic build do not match. 
![Screenshot_11](https://user-images.githubusercontent.com/43552938/206262919-bdaff18a-6d3c-4283-931c-7886d27d0c3c.png)
![Screenshot_12](https://user-images.githubusercontent.com/43552938/206262951-41f83b2e-d7e7-417b-af55-fc08228c943c.png)

**Comment by vinaciotm** [comment]
> Just add the following into your app.json: "ios": { "entitlements": { "keychain-access-groups": ["XXXXXXXX.*", "com.apple.token"] }, }, where XXXXXXXX is your apple "Team ID". How to find out your Team ID? Login to App Store Connect, click on your name (right top corner), then "Edit Profile" and it'll take you to a screen that will have "Team ID" on it.
> 
> Another way to see/check this is go to your app in App Store Connect -> TestFlight tab -> pick a build -> Build Metadata and at the bottom there's Store Information section that has "Entitlements". You should see "keychain-access-groups: ( "XXXXXXX.*", "com.apple.token" ).
> 
> Hope it helps.

How to fix "asyncStorage loss data after upgrade expo SDK", for android devices?

**Comment by dhcmega** [comment]
I'm facing the same problem. When the app is built using `eas build` in iOS it has an empty secureStore.
It would not surprise me that the problem comes from the app's name changed.

@Dulatech have you been able to solve it? thanks!

**Comment by Dulatech** [comment]
Hi @dhcmega, the issue is still persisting on my end. I am still waiting for a response from expo staff.

**Comment by ChronSyn** [comment]
As a follow-up to this issue - with some limited testing, the solution of setting `SHARED_PREFERENCES_NAME` mentioned above seems to resolve the issue on Android.

This can be done with patch-package (hardcode the name according to the project unless you're feeling adventurous and know enough Java to be able to read the account name from the app.json file and encode the resulting string).

**Comment by DB1703** [comment]
> Just add the following into your app.json: "ios": { "entitlements": { "keychain-access-groups": ["XXXXXXXX.*", "com.apple.token"] }, }, where XXXXXXXX is your apple "Team ID". How to find out your Team ID? Login to App Store Connect, click on your name (right top corner), then "Edit Profile" and it'll take you to a screen that will have "Team ID" on it.
> 
> Another way to see/check this is go to your app in App Store Connect -> TestFlight tab -> pick a build -> Build Metadata and at the bottom there's Store Information section that has "Entitlements". You should see "keychain-access-groups: ( "XXXXXXX.*", "com.apple.token" ).
> 
> Hope it helps.

I added the entitlements as descripted here, even appers now on the build on testflight but the data is still been wiped out.

**Comment by DB1703** [comment]
> Hi @dhcmega, the issue is still persisting on my end. I am still waiting for a response from expo staff.

@dhcmega I checked your issue, i have the same issue, even still with the entitlements added, did it worked for you?
