### ISSUE TITLE
Expo APK in website too old

### ISSUE THREAD

**Issue by lucaszanella** [expo/expo#1617]
The apk provided in https://expo.io/tools is too old, I cannot even access my snacks, only my projects. I need to run snack on emulator so I cannot scan the QR Code and pasting the link didn't work for me. So I couldn't run it in any way on my emulator.

Can you guys put a newer apk there?

**Comment by tcdavis** [comment]
v2.4.0 is the latest version of the Android client.
What happens when you paste the link?

**Comment by lucaszanella** [comment]
That's strange. In the emulator I cannot see my snacks listed. In the phone they show.

**Comment by terribleben** [comment]
Hi! The apk and ipa files on the website are correct right now.
