### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Android 12

### ISSUE THREAD

**Issue by ZukaGap** [expo/expo#16184]
### Summary

This error caused, when I was trying to login with Facebook.(I have this issue only android 12)

used packages:
"expo": "40.0.0",
"expo-facebook": "11.3.1",
"react-native": "~0.63.4",

`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

I try to install this - `implementation 'androidx.work:work-runtime-ktx:2.7.0'` but **It's not** working for me.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

SDK version 31

### Environment

System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 68.67 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Android TV Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Reproducible demo

...

**Comment by gurbela** [comment]
Any update for this?

**Comment by vrgimael** [comment]
This issue should be reopened, this also started happening to me recently when we switched to `targetSdkVersion = 31`.

My project builds fine after setting `implementation 'androidx.work:work-runtime-ktx:2.7.1'`, however this error still happens when running some functions, specifically when calling `startLocationUpdatesAsync` from `expo-location` in my case (but it looks like this happens in many other functions too).

Any ideas or workarounds would be very much appreciated

**Comment by StefanBratanov** [comment]
> This issue should be reopened, this also started happening to me recently when we switched to `targetSdkVersion = 31`.
> 
> My project builds fine after setting `implementation 'androidx.work:work-runtime:2.7.1'`, however this error still happens when running some functions, specifically when calling `startLocationUpdatesAsync` from `expo-location` in my case (but it looks like this happens in many other functions too).
> 
> Any ideas or workarounds would be very much appreciated

I get same issue using `expo-notifications` . Did you find a way around it? Setting `work-runtime` to 2.7.0 didn't work for me.

```
03-07 13:11:28.215 13676 14266 E expo-notifications: Action expo.modules.notifications.NOTIFICATION_EVENT failed: com.xx.xxx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
03-07 13:11:28.215 13676 14266 E expo-notifications: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

**Comment by Tythiras** [comment]
I am also having the same issue with expo-notifications, scheduling a locale notification.

I suspect it's also resulting in an issue with showing the notifications.

Implementing androidx.work:work-runtime:2.7.1 is not fixing anything for me.

**Comment by hareruya-maro** [comment]
I had the same problem.
It works by rewriting the following two `PendingIntent.FLAG_UPDATE_CURRENT` to `PendingIntent.FLAG_IMMUTABLE`.
However, I'm not sure if this fix is ​​appropriate.

https://github.com/expo/expo/blob/c243570e6a1690ed2cbe02cade3ed9f6fb01c76a/packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/NotificationsService.kt#L431

https://github.com/expo/expo/blob/c243570e6a1690ed2cbe02cade3ed9f6fb01c76a/packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/NotificationsService.kt#L465

**Comment by alexis-dlgado** [comment]
Hi there! 
<img width="471" alt="Screen Shot 2022-04-22 at 18 11 34" src="https://user-images.githubusercontent.com/93948284/164845973-a0a4b7c8-49dc-470f-a3de-5bcf3a8f858e.png">

I would like to re-open this issue, I have the same issue when I try to install the APK created by EAS. 

I have implemented the dependency `androidx.work:work-runtime:2.7.1 ` And also the added the property `android:exported="true"`  but does not work.

So, any ideas on what might is causing this error?

**Comment by yousefamar** [comment]
Has anyone managed to fix this? This issue should definitely be reopened!

**Comment by ourmaninamsterdam** [comment]
We're also seeing this issue on Android 12. The following fixes and issues appear to be related:

* https://github.com/expo/expo/pull/17333
* https://github.com/expo/expo/pull/17334
* https://github.com/expo/expo/issues/17276

However, ASFAIK they've yet to be released. This is a blocker for our app.

**Comment by douglassimaodev** [comment]
Where are you guys adding this line: implementation 'androidx.work:work-runtime:2.7.1'?

**Comment by Waheed388** [comment]
I don't have androidx.work:work-runtime in Gradle and I am also getting this exception

**Comment by douglassimaodev** [comment]
@Waheed388 I got it solved my changing the project configuration, instead of 12 I used 11 and error was gone

**Comment by Ashleyv6** [comment]
> Where are you guys adding this line: implementation 'androidx.work:work-runtime:2.7.1'?

you should add it here: `../../android/app/build.gradle` inside dependecies:
`dependencies {
    def work_version = "2.7.1"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    //test and espresso necessary for geolocation configuration
    androidTestImplementation 'androidx.test:runner:1.1.1'                   // or higher
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'   // or higher
    implementation 'com.android.support:multidex:1.0.3'
    implementation platform('com.google.firebase:firebase-bom:29.0.4')
    implementation 'com.google.firebase:firebase-analytics'

    // (Java only)
   // implementation("androidx.work:work-runtime:$work_version")

    // Kotlin + coroutines
    implementation("androidx.work:work-runtime-ktx:$work_version")

    // optional - RxJava2 support
    implementation("androidx.work:work-rxjava2:$work_version")

    implementation 'androidx.work:work-runtime:2.7.1'
}`

**Comment by Brune04** [comment]
> @Waheed388 I got it solved my changing the project configuration, instead of 12 I used 11 and error was gone

@douglassimaodev are you meaning that you changed the version of expo-facebook from 12 to 11? I'm having this same issue when trying to login with Facebook on Android

**Comment by zagoorland** [comment]
> > @Waheed388 I got it solved my changing the project configuration, instead of 12 I used 11 and error was gone
> 
> @douglassimaodev are you meaning that you changed the version of expo-facebook from 12 to 11? I'm having this same issue when trying to login with Facebook on Android

Same problem here on Android 12 and Expo 46 here! App crashes after fb loging

**Comment by douglassimaodev** [comment]
No sorry, from visual studio android project I changed the target from android 12 to 11 and I stop getting this error

**Comment by zagoorland** [comment]
> No sorry, from visual studio android project I changed the target from android 12 to 11 and I stop getting this error

Where exactly did you changed the target? In which file?

**Comment by douglassimaodev** [comment]
Right click in android project -> properties -> Application

then in Compile using android version: Target Framework change to Android 11.0(R)

**Comment by AhmedTouti** [comment]
install the last version react-native-Share

**Comment by Namoku** [comment]
> install the last version react-native-Share

Why this will work?

**Comment by NATADIPA** [comment]
Most of the people asking to add dependency androidx.work:work-runtime:2.7.1 but it did not works it crashes everytime can any one suggest better idea to avoid above mentioned issue ?

**Comment by Robiullah2244** [comment]
Does anyone find a solution? Please help me.

**Comment by Ashleyv6** [comment]
ok, what I did was:

1. Update all packages to see if all of them are already for SDK version 31/32/33
2. (In my case it's Flutter) I had to update Flutter version at least 3.3.2
3.  `flutter clean`
4. and change version on build.gradle/app to `'androidx.work:work-runtime:2.7.1'`

**Comment by patgoley-tts** [comment]
Adding `androidx.work:work-runtime:2.7.1` fixed the crash for me but I don't understand why. Can anyone provide context and in which, if any, version of expo fixes this?

**Comment by raqib850** [comment]
I am still getting this issue on react active using build-tools ver 31. Any fixes ?

**Comment by next6leo** [comment]
me too
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
    }
    repositories {
        google()
        mavenCentral() 
        maven {url 'https://repo.huaweicloud.com/repository/maven/' } 
        maven { url 'https://developer.huawei.com/repo/' }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        classpath 'com.huawei.agconnect:agcp:1.5.2.300'
        classpath('de.undercouch:gradle-download-task:5.0.1')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by maartenvandillen** [comment]
For me upgrading both expo-location and expo-task-manager packages solved the problem.

**Comment by Yandamuri** [comment]
@maartenvandillen to what version you upgraded both packages?
