### ISSUE TITLE
Feature Request: Cmd+F to Find Phrase in Logs in Expo IDE

### ISSUE THREAD

**Issue by codekiln** [expo/expo#1618]
Feature Request: Cmd+F to Find / Search for Phrase in Logs in Expo IDE
  
### Environment

$ exp diagnostics
05:16:43 [exp] Generating diagnostics report...
05:16:43 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS Sierra 10.12.5
  Node: 9.5.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 8.3.3 Build version 8E3004b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/codekiln-56398dc7-3673-43d7-bf6b-50b21e8c9e15.tar.gz

### Steps to Reproduce

1. Connect iOS phone to expo IDE and run app on phone
2. Focus Expo IDE log from iOS device
3. Press Cmd+F

### Expected Behavior

An ability to find within the logs appears

### Actual Behavior

Nothing happens

### Workaround
[`exp start`](https://docs.expo.io/versions/latest/guides/exp-cli.html)

**Comment by sjchmiela** [comment]
Hey, @codekiln! `exp` and XDE has been recently deprecated in favor of Expo CLI (for more info see [this blog post](https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c)). Fortunately, this issue should be resolved in Expo CLI, where all the logs are searchable in dev tools in browser! 🎉
