### ISSUE TITLE
On TestFlight, an app stucks on the splash screen.

### ISSUE THREAD

**Issue by AngelDev727** [expo/expo#16180]
### Summary

An app works fine via the expo app (both on simulator and on real device) but when I try to run the standalone app (.ipa) that I downloaded to TestFlight, it stuck on the splash screen.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

package.json
================
{
  "version": "0.1.1",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/poppins": "^0.2.0",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/datetimepicker": "4.0.0",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-native-picker/picker": "2.2.1",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "@stripe/stripe-react-native": "0.2.3",
    "axios": "^0.24.0",
    "cors": "^2.8.5",
    "dotenv": "^10.0.0",
    "expo": "^44.0.0",
    "expo-app-loading": "~1.3.0",
    "expo-camera": "~12.1.0",
    "expo-checkbox": "~2.0.0",
    "expo-constants": "~13.0.1",
    "expo-dev-client": "~0.8.3",
    "expo-document-picker": "~10.1.1",
    "expo-facebook": "~12.1.0",
    "expo-file-system": "~13.1.2",
    "expo-font": "~10.0.4",
    "expo-google-app-auth": "~8.3.0",
    "expo-image-picker": "~12.0.1",
    "expo-location": "~14.0.1",
    "expo-notifications": "~0.14.0",
    "expo-splash-screen": "~0.14.1",
    "firebase": "9.2.0",
    "formik": "2.1.4",
    "moment": "^2.29.1",
    "qs": "^6.10.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-actionsheet": "^2.4.2",
    "react-native-calendars": "^1.1268.0",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-date-picker": "^4.1.1",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-image-picker": "^4.1.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-maps": "0.29.4",
    "react-native-modal-datetime-picker": "^13.0.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-stripe-identity": "^0.0.1",
    "react-native-svg": "12.1.1",
    "react-native-switch": "^2.0.0",
    "react-native-view-slider": "^1.1.1",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.15.0",
    "react-redux": "^7.2.6",
    "rn-expo-paypal-integration": "^1.2.0",
    "rn-pdf-reader-js": "^4.1.1",
    "socket.io-client": "^2.1.1",
    "yup": "0.27.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.9.0",
    "@types/socket.io-client": "^3.0.0",
    "babel-preset-expo": "9.0.2",
    "standard-version": "^7.1.0",
    "standard-version-expo": "^1.0.3"
  },
  "private": true
}

### Environment

OS: Mac Monterey
node : v16.13.1
yarn: 1.22.17
npm: 8.2.0
watchman: 2022.01.03.00

### Reproducible demo

Here is app.config.js
=================
import 'dotenv/config';

export default {
  expo: {
    name: 'XXX',
    slug: 'XXXX',
    privacy: 'public',
    owner: 'xxxx',
    platforms: ['ios', 'android'],
    version: '1.0',
    orientation: 'portrait',
    icon: './src/assets/icon.png',
    splash: {
      image: './src/assets/splash.png',
      resizeMode: 'cover',
      backgroundColor: '#ffffff'
    },
    plugins: [
      ["expo-notifications", {
        "icon": "./assets/favicon.png",
        "color": "#ff0000",
        "sounds": ["./assets/dinheiro.wav"],
        "mode": "production"
      }],
      ["expo-location", { "isAndroidBackgroundLocationEnabled": false }],
      ["expo-image-picker", { "photosPermission": "The app accesses your photos to let you share them with your friends." }]
    ],
    updates: {
      fallbackToCacheTimeout: 0
    },
    assetBundlePatterns: ['**/*'],
    scheme: 'com.googleusercontent.apps.865330437158-6utfjhqbc3pps1au9kahl5pgv9pntd7p',
    ios: {
      buildNumber: "0.1.4",
      usesIcloudStorage: true,
      supportsTablet: true,
      bundleIdentifier: "com.breakzen.breakzen",
      infoPlist: {
        NSLocationWhenInUseUsageDescription: "The Breakzen App uses your location to find nearby others",
        NSLocationAlwaysUsageDescription: "The Breakzen App will use your location to find nearby others",
        UIBackgroundModes: ["location", "fetch"],
        LSApplicationQueriesSchemes: [
          "fbapi",
          "fbauth",
          "fb-messenger-share-api",
          "fbauth2",
          "fbshareextension"
        ],
        CFBundleURLTypes: [{CFBundleURLSchemes: ["fb595598541722630"]}],
        NSLocationWhenInUseUsageDescription: "App will use your location to get nearby users",
        NSLocationAlwaysUsageDescription: "App will use your location to get nearby users"
      },
      config: {
        googleSignIn: {
          reservedClientId: "XXXX"
        }
      },
      googleServicesFile: "./GoogleService-Info.plist"
    },
    android: {
      ...
    },
    extra: {
      ....
    }
  }
};

**Comment by marcushf** [comment]
Same here

**Comment by brentvatne** [comment]
https://github.com/expo/fyi/blob/main/splash-screen-hanging.md

**Comment by ferasabufares** [comment]
@AngelDev727  same problem here if you fix it can you please share with me how to fix this problem

**Comment by ferasabufares** [comment]
@marcushf did you manage to fix it ?

**Comment by ferasabufares** [comment]
same problem +1

**Comment by jonnycraze** [comment]
I upgraded from sdk 42 to 43 and now have this issue. I can't roll back because iOS now requires v15. Any help would be GREATLY appreciated on this issue.

I cannot find an error when running on an emulator or physical device. Everything loads fine. 

Likewise my apk built on sdk 43 works fine in production.

**Comment by brentvatne** [comment]
@jonnycraze - have you tried debugging with this guide? https://github.com/expo/fyi/blob/main/splash-screen-hanging.md
worst case, you can proceed to https://github.com/expo/fyi/blob/main/manual-debugging.md. let us know what you find and if you have a reproducible example that demonstrates some bug in an expo tool

**Comment by jonnycraze** [comment]
I'm making my way through the manual debugging process. It is especially difficult and slow because the error cannot be produced in any type of local environment, it is only in the ipa package.

**Comment by jonnycraze** [comment]
@brentvatne It appears I've found the offending dependency. When I exclude the package `@stripe/stripe-react-native` everything works as expected in the built APK in TestFlight.

Now I have to try and figure out why.

**Comment by jonnycraze** [comment]
In my case the issue had to do with Stripe React Native. When using this with Expo it is required to be deployed using the EAS build when building an ipa. I missed this requirement and was building using the Expo Build process - resulting in a splash screen that never resolves. Hopefully this thread helps someone else in the future with this same issue.

**Comment by rachythecaffeinated** [comment]
I also have a similar issue and not sure what is causing it... will report back when solved 😅
