### ISSUE TITLE
`expo-face-detector` won't detect face features

### ISSUE THREAD

**Issue by BrianValente** [expo/expo#16183]
### Summary

Hello! We are having a problem after upgrading from SDK 42 to 44 in our app.
We use `expo-face-detection` combined with `expo-camera`, and we noticed that we are no longer receiving the position of face features.
Here's what the `onFacesDetected` callback is receiving:

SDK 42:
![image](https://user-images.githubusercontent.com/3992081/152365124-efa30375-45b1-488a-9f00-086686dbddf4.png)

SDK 43/44:
![image](https://user-images.githubusercontent.com/3992081/152365142-5d56ead1-5ff1-45a4-bbc1-d1790dc278e5.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v15.14.0/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 2021.12.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7231092
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

Switch between SDK 42 and 43 and see the difference in logs.

https://snack.expo.dev/@brianvalente/face-detection-issue

**Comment by brentvatne** [comment]
fixed by @Simek in #16114 and deployed in expo-face-detector@11.1.3
