### ISSUE TITLE
FBSDKInternalUtility always returns isFacebookAppInstalled equal to 0

### ISSUE THREAD

**Issue by serhiipalash** [expo/expo#1619]
This bug only affects iOS standalone app's Facebook login because only `facebook-ios-sdk` detects is Facebook app installed and changes UI depending on this
https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.m#L364`
  
### Environment

| software         | version
| ---------------- | -------
| expo | 26.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz

`exp diagnostics` output

<img width="1111" alt="screen shot 2018-04-08 at 1 04 16 pm" src="https://user-images.githubusercontent.com/14208343/38466589-2c119d26-3b34-11e8-9b9b-104bc748e75d.png">

App's target is iOS Standalone

### Steps to Reproduce

On any Expo standalone app on iOS try to login with Facebook with behavior "browser" when you have installed Facebook app. Then remove Facebook app from your device and try to do the same.

You will always see the same UI.
This is a bug.

### Expected Behavior

Should work in the way like it works in [Wolt app](https://wolt.com/en)

If I set behavior "browser" for Facebook login and Facebook app is installed on the device, on iOS user should see UI with "Log in with the Facebook app" button and be able to login without entering email and password

<img width="376" alt="screen shot 2018-04-08 at 1 12 22 pm" src="https://user-images.githubusercontent.com/14208343/38466220-8c047024-3b2e-11e8-888a-15a8fdfee686.png">

If I set behavior "browser" for Facebook login and Facebook app is not installed on the device, on iOS user should see UI without "Log in with the Facebook app" button

<img width="377" alt="screen shot 2018-04-08 at 1 15 22 pm" src="https://user-images.githubusercontent.com/14208343/38466247-fdcd9aaa-3b2e-11e8-8fd6-57a6c9323685.png">

### Actual Behavior

When I set behavior "browser" for Facebook login and Facebook app is installed on the device, on iOS I see UI without "Log in with the Facebook app" button

<img width="377" alt="screen shot 2018-04-08 at 1 15 22 pm" src="https://user-images.githubusercontent.com/14208343/38466309-1110d2de-3b30-11e8-8cc7-27fabe625d22.png">

### Reproducible Demo

The only thing you can test is to see how UI looks for different auth urls using browser dev tools

<img width="1680" alt="screen shot 2018-04-08 at 1 26 12 pm" src="https://user-images.githubusercontent.com/14208343/38466365-be70963a-3b30-11e8-847f-2826471c85b3.png">

[Left url ](https://m.facebook.com/login.php?skip_api_login=1&api_key=289934484538965&signed_next=1&next=https%3A%2F%2Fm.facebook.com%2Fv2.11%2Fdialog%2Foauth%3Fredirect_uri%3Dfb289934484538965prod%253A%252F%252Fauthorize%252F%26display%3Dtouch%26state%3D%257B%2522challenge%2522%253A%2522QRoivwO5jQod0BbYNVb3xg8vJ1k%25253D%2522%252C%25220_auth_logger_id%2522%253A%252220696EA8-047F-4795-A090-53157AE85979%2522%252C%2522com.facebook.sdk_client_state%2522%253Atrue%252C%25223_method%2522%253A%2522sfvc_auth%2522%257D%26scope%3Demail%252Cuser_friends%26response_type%3Dtoken%252Csigned_request%26default_audience%3Dfriends%26return_scopes%3Dtrue%26auth_type%3Drerequest%26client_id%3D289934484538965%26ret%3Dlogin%26sdk%3Dios%26fbapp_pres%3D1%26sdk_version%3D4.29.0%26local_client_id%3Dprod%26logger_id%3D20696EA8-047F-4795-A090-53157AE85979&cancel_url=fb289934484538965prod%3A%2F%2Fauthorize%2F%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3D%257B%2522challenge%2522%253A%2522QRoivwO5jQod0BbYNVb3xg8vJ1k%25253D%2522%252C%25220_auth_logger_id%2522%253A%252220696EA8-047F-4795-A090-53157AE85979%2522%252C%2522com.facebook.sdk_client_state%2522%253Atrue%252C%25223_method%2522%253A%2522sfvc_auth%2522%257D%26e2e%3D%257B%2522init%2522%253A71153.327056124996%257D%23_%3D_&display=touch&locale=en_US&logger_id=20696EA8-047F-4795-A090-53157AE85979&_rdr)

[Right url](https://m.facebook.com/login.php?skip_api_login=1&api_key=289934484538965&signed_next=1&next=https%3A%2F%2Fm.facebook.com%2Fv2.11%2Fdialog%2Foauth%3Fredirect_uri%3Dfb289934484538965prod%253A%252F%252Fauthorize%252F%26display%3Dtouch%26state%3D%257B%2522challenge%2522%253A%2522QRoivwO5jQod0BbYNVb3xg8vJ1k%25253D%2522%252C%25220_auth_logger_id%2522%253A%252220696EA8-047F-4795-A090-53157AE85979%2522%252C%2522com.facebook.sdk_client_state%2522%253Atrue%252C%25223_method%2522%253A%2522sfvc_auth%2522%257D%26scope%3Demail%252Cuser_friends%26response_type%3Dtoken%252Csigned_request%26default_audience%3Dfriends%26return_scopes%3Dtrue%26auth_type%3Drerequest%26client_id%3D289934484538965%26ret%3Dlogin%26sdk%3Dios%26fbapp_pres%3D0%26sdk_version%3D4.29.0%26local_client_id%3Dprod%26logger_id%3D20696EA8-047F-4795-A090-53157AE85979&cancel_url=fb289934484538965prod%3A%2F%2Fauthorize%2F%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3D%257B%2522challenge%2522%253A%2522QRoivwO5jQod0BbYNVb3xg8vJ1k%25253D%2522%252C%25220_auth_logger_id%2522%253A%252220696EA8-047F-4795-A090-53157AE85979%2522%252C%2522com.facebook.sdk_client_state%2522%253Atrue%252C%25223_method%2522%253A%2522sfvc_auth%2522%257D%26e2e%3D%257B%2522init%2522%253A71153.327056124996%257D%23_%3D_&display=touch&locale=en_US&logger_id=20696EA8-047F-4795-A090-53157AE85979&_rdr)

The difference between urls is only in one character 
on left 
`fbapp_pres=1`
on right
`fbapp_pres=0`

I think the problem is in your private `FBSDKInternalUtility`
<img width="1233" alt="screen shot 2018-04-08 at 1 42 30 pm" src="https://user-images.githubusercontent.com/14208343/38466507-d985cb50-3b32-11e8-922e-a68faff70c5e.png">

It always returns 0 in this line in facebook-ios-sdk
```
loginParams[@"fbapp_pres"] = @([FBSDKInternalUtility isFacebookAppInstalled]);
```

I would fix it by myself, but it is not possible as it is in your private module :)

@terribleben please fix it.

**Comment by terribleben** [comment]
Thanks for the report - I'll see if I can get a chance to reproduce and dig in. I suspect either we need to update the Facebook dependency or possibly we forgot to include one of facebook's `ApplicationQueriesSchemes`.

**Comment by serhiipalash** [comment]
Great, thanks!

But be aware that all screenshots that I have added describes scenario when user is not signed in https://www.facebook.com/ in Safari.

Safari is the environment for "browser" behavior, and if you are already signed in on Facebook website, you will always see this

<img width="374" alt="screen shot 2018-04-09 at 12 08 53 am" src="https://user-images.githubusercontent.com/14208343/38472594-b2ceb956-3b8a-11e8-8eea-86d7541f6a3d.png">

**Comment by terribleben** [comment]
It looks like our app builder code had a regression where it stopped adding the Facebook application scheme to your Expo app's configuration. I've committed a change to fix this which will go out next time we deploy our app builder.

In the meantime, I think a workaround would be to add `[ "fbapi", "fb-messenger-api", "fbauth2'", "fbshareextension" ]` to your `app.json` under `ios.infoPlist.LSApplicationQueriesSchemes`, for example

```
"ios": {
  "infoPlist": {
    "LSApplicationQueriesSchemes": [ "fbapi", "fb-messenger-api", "fbauth2'", "fbshareextension" ]
  }
}
```

After we deploy the change and close this ticket, the workaround will no longer be needed (because it will be added automatically as long as your app has a `FacebookAppID`).

**Comment by serhiipalash** [comment]
@terribleben thanks a lot!

I think this is a very useful feature as it allows user to not enter email and password and login into our Facebook app in one click.

**Comment by djamalouch** [comment]
We experienced the same problem. I just tried the workaround, but it didn't work for me.

When do you think can we expect the next deployment to the app builder that resolves this issue?

**Comment by terribleben** [comment]
@djamalouch did you rebuild after making the change? The app.json change is applied to your native Info.plist only when you rebuild with `exp build:ios`.

**Comment by serhiipalash** [comment]
@terribleben I just build new release and tested it. Sorry, but this didn't help
```
"ios": {
  "infoPlist": {
    "LSApplicationQueriesSchemes": [ "fbapi", "fb-messenger-api", "fbauth2'", "fbshareextension" ]
  }
}
```
all works the same like it was before.

**Comment by djamalouch** [comment]
@terribleben Yes I rebuilt it.

**Comment by terribleben** [comment]
🤔 I guess I need to have another look. Thanks for letting me know

**Comment by serhiipalash** [comment]
Hi @terribleben!
Will this bug be fixed in Expo 27 ?

**Comment by djamalouch** [comment]
Maybe there is a chance for a working workaround until this issue is fixed? It is really annoying for our users to type in their passwords for a facebook login...

**Comment by serhiipalash** [comment]
I have just updated Expo to 27 and all works! Thanks @terribleben !

**Comment by serhiipalash** [comment]
Everything works for us. I am closing this issue. Thanks again @terribleben
