### ISSUE TITLE
Flow for all public facing APIs

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#162]
Moved from: https://github.com/expo/expo-sdk/issues/36

**Comment by dikaiosune** [comment]
@ide is this going to happen as a product of the recent sdk work you've been doing?

**Comment by ide** [comment]
Sort of - I fixed all the existing Flow types and added some to FileSystem but am not directly working towards increasing coverage.

**Comment by danielmartinprieto** [comment]
Hi! I'm having a hard time finding the official Flow definitions for expo - I've started using flow-typed and the cli created stubs for it, because it couldn't find them either. What am I doing wrong? How can I enable/get Flow definitions for Expo?

Thanks.

**Comment by ide** [comment]
The official Flow definitions are included inline with the code itself. We don't use flow-typed because of the spatial coupling it introduces in a structured design sense.

**Comment by danielmartinprieto** [comment]
@ide hey, thanks for answering!

That's great, then. Do you know why I am getting this `'expo' Required module not found`? How can I tell Flow where to find these definitions?

Thanks again!

**Comment by ide** [comment]
Do you perhaps have all node_modules ignored under flowconfig?

**Comment by danielmartinprieto** [comment]
No all `node_modules`, but I've been adding more and more subdirectories of it until I was able to get a decent amount of Flow errors of my code, otherwise it felt almost useless. I've checked my `.flowconfig` file and I've seen this under `[ignore]`:
```
; Ignore missing expo-sdk dependencies (temporarily)
; https://github.com/expo/expo/issues/162
.*/node_modules/expo/src/*
```
I didn't add this, I've checked and it's included in CRNA. If you follow that issue in the comment and its referenced ones, you end up in this one, haha.

**Comment by ide** [comment]
The Flow types are included with the code we publish to npm so they're most likely on your computer. If you can debug why Flow can't see them I expect Flow types will just start working for you then.

**Comment by danielmartinprieto** [comment]
I've removed that line in the ignore section but still don't get any Flow errors when I use something from 'expo' in an incorrect way, for instance:
```javascript
// @flow
import { Constants } from 'expo';

const log = (something: number) => console.log(something);
log(3); // no Flow error 
log(Constants.deviceName); // no Flow error :(
log('hi there'); // Flow error
```

**Comment by ide** [comment]
Constants doesn't have every field typed because they're sent from native. Browse around here for something that has types: https://github.com/expo/expo-sdk/tree/3af2763fc97abdb879f3455a71816c899f8617e5

**Comment by danielmartinprieto** [comment]
Mmm, it seems that `Constants` is not properly typed yet, but other APIs work already for me!

**Comment by ide** [comment]
Yeah Flow typings like this are tricky because of the expensive coupling they introduce between JS and native. I'd rather be honest and have no types than the wrong type so if we're likely to forget to update a type it's probably better for most developers to read the docs site instead.

**Comment by danielmartinprieto** [comment]
Agree, but I would push Flow/Typescript forward, they give you a lot of confidence (when they work, hehe). I don't come from a JavaScript background and it's great to have something similar like in other typed languages. The problem is that everything is evolving super fast and we spend a lot of time fixing issues with the IDEs, third party dependencies, the tools themselves...

**Comment by bolinfest** [comment]
Is there any sort of CI build that verifies that a new Expo project is Flow clean? I just created a new project and had all sorts of issues. I ended up copying [this `.flowconfig`](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/.flowconfig), but this gave me trouble:

```
[version]
^0.56.0
```

I ended up trying a number of different Flow versions. Eventually, I decided to do:

```
$ find . -name .flowconfig
./node_modules/react-native/.flowconfig
./node_modules/lottie-react-native/.flowconfig
./node_modules/react-native-maps/.flowconfig
```

I looked at `./node_modules/react-native/.flowconfig` and it had:

```
[version]
^0.61.0
```

so I installed that locally. Things almost worked, but I had to add the following suppression:

```
[options]
; Added this one for an issue in node_modules/react-native/Libraries/Components/ScrollResponder.js.
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(>=0\\.\\([5-6][0-6]\\|[1-4][0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=react_native_fb\\)?)\\)
```

After all that, I still get one Flow error:

```
Error: screens/HomeScreen.js:13
 13: import { WebBrowser } from 'expo';
                                ^^^^^^ expo. Required module not found


Found 1 error
error Command failed with exit code 2.
```

I'm not sure why this is causing an error whereas this line has no issues:

```
import { AppLoading, Asset, Font } from 'expo';
```

Regardless, having this much trouble with a project out of the box is extremely frustrating.

**Comment by anp** [comment]
@bolinfest hi! We do ensure that flow passes in our internal CI, and we specify the flow version here: https://github.com/expo/expo-sdk/blob/master/package.json#L69. Version 0.61.0 should be compatible, and it currently passes AFAICT.

Maybe you could try shutting down your flow server and reinstalling node_modules?

**Comment by bolinfest** [comment]
OK, I'll try again. Last night I built the XDE from source (at tag 2.22.1) and created a new app from scratch through the XDE UI and ran into the issues above. I had to create my own `.flowconfig` (which I stole from `create-react-native-app`, as I linked to above): is that part expected? Should I be copying it from somewhere else?

**Comment by sjchmiela** [comment]
We've recently moved away from Flow to TypeScript. 🙂 I don't think we plan to support Flow anymore.
