### ISSUE TITLE
Response from useAuthRequest is null on web when passing windowName _self as promptOptions

### ISSUE THREAD

**Issue by joranb** [expo/expo#16200]
### Summary

I have an app using Keycloak for auth, using authorization code with PKCE. If I don't pass promptOptions everything works (but then the Keycloak login screen comes in a popup on web). Setting promptOptions with windowName: "_self" I get redirected inside the same tab, as people normally want on web. The problem is that when redirecting from the same tab the authResponse is null after login, so I don't get the authorization code so I can ask for an access token. 

Is there something else I need to do? Or did I stumble upon a bug? When I am redirected the url contains the following:
http://localhost:19006/?state=lpC9LdfAhI&session_state=cc28d33a-629b-4a2f-8e5c-b26ed67d2789&code=ef979957-8ee9-hhb4-908f-d5cd75941ea1.cc28d88a-629b-4a2f-8e5c-b26ed67d2789.5cc83c9c-7700-433b-8af1-dd52fda1d63e

So I got everything I need, I obviously could extract it from the URL, verify state and use the code to get my access token. But it would be really nice if it did work with the AuthSession library in the same way as it does when you login via the popup browser window.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

44.0.6

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      @expo/metro-config: ^0.3.6 => 0.3.9
      @expo/webpack-config: ~0.16.2 => 0.16.16
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

Code example to reproduce:
```
    const promptOptions: AuthRequestPromptOptions = {
        windowName: "_self"
    }
    const [request, authResponse, promptAuthentication] =
        AuthSession.useAuthRequest(
            {
                responseType: AuthSession.ResponseType.Code,
                clientId: "myClientID",
                scopes: [],
                codeChallenge: "myChallenge",
                codeChallengeMethod: CodeChallengeMethod.S256,
                redirectUri: AuthSession.makeRedirectUri({
                    native: "myRedirectUri",
                    useProxy: false,
                }),
            },
            discovery
        );
    React.useEffect(() => {
        if (authResponse?.type === "success") {
            AuthSession.exchangeCodeAsync(
                {
                    clientId: "myClientId",
                    redirectUri: AuthSession.makeRedirectUri({
                        native: "myRedirectUri",
                    }),
                    code: authResponse?.params.code,
                    extraParams: {
                        client_secret: "",
                        code_verifier: request.codeVerifier ? request.codeVerifier : "",
                    },
                },
                {tokenEndpoint: "myTokenEndpoint"}
            ).then((tResponse) => {
                signIn(tResponse);
            });
        }
    }, [authResponse]);
```
    
Sign in button:
    
```
   <Button
            text="Sign in"
            onPress={() => {
                    promptAuthentication(promptOptions).then((r) => console.log("AuthResult: " + r));
            }}
     />
```

**Comment by joranb** [comment]
Still a valid issue, when using _self it opens in the same tab, that means it leaves the web app entirely and loads it fresh after redirect upon login. Probably need to handle it differently in that case since the promise never fulfills. Instead of creating a lot of code for web (storing state locally, checking it upon return and so on) we have currently solved it with these AuthRequestPromptOptions:

```
  const features: WebBrowserWindowFeatures = {
    popup: false,
  };

  const options: AuthRequestPromptOptions = {
    windowFeatures: features,
  };
```
With these options set the Keycloak login page opens in a new tab instead of a popup. This solves some of our problems, since Safari on iOS among others blocks popup windows by default, and treats users as idiots by not even letting them know that a popup has been blocked. This way at least the app is not broken, and it looks way better than the popup, but still not as good as it would with same tab though, like it would have been in a normal React app using the Keycloakjs adapter.

**Comment by plevko** [comment]
Any chance this will be fixed ? 
Still can't use same window authentication on WEB.

`promptAsync({ windowName: '_self' });`

**Comment by joranb** [comment]
@plevko Wouldn't hold my breath. We just implemented it manually ourselves like this: https://gist.github.com/joranb/7e4d4c4c961b0a3b755b3433dfcff3b6

You could easily do the same, although it would be nice if the library handled it for us.

**Comment by plevko** [comment]
> @plevko Wouldn't hold my breath. We just implemented it manually ourselves like this: https://gist.github.com/joranb/7e4d4c4c961b0a3b755b3433dfcff3b6
> 
> You could easily do the same, although it would be nice if the library handled it for us.

Thanks for the code! 
I would expect expo to handle this for us, its really a basic use case.
