### ISSUE TITLE
App fails to start on Expo Go for the first time if `runtimeVersion` is defined in app.json

### ISSUE THREAD

**Issue by nabn** [expo/expo#16208]
### Summary

If `runtimeVersion` is defined in app.json, the app fails to start with the message

> No launchable updates found in the database

Steps to reproduce:
 - create a new app: `expo init my-app`
 - run the dev server `yarn ios`
 - verify that the app is running ok on Expo Go app on a simulator
 - *delete the app from simulator*
 - add `runtimeVersion` property with any value to `app.json`
 - install and run the app in expo go again (pressing `i` on the dev server or through the web interface)
 - the app fails to launch
 
 If Expo Go isn't deleted after the app launches for the first time, it continues to work regardless of the presence of `runtimeVersion` in `app.json`
 
 expo-cli version: `5.0.3`
 expo client version: `2.23.2.101`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

~44.0.0

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.2.0 - /var/folders/vw/90f_69y944g411s20r01h0v00000gn/T/fnm_multishells/10159_1644195465875/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.0 - /var/folders/vw/90f_69y944g411s20r01h0v00000gn/T/fnm_multishells/10159_1644195465875/bin/npm
      Watchman: 2022.01.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 30, 32
        Build Tools: 29.0.3, 30.0.2, 32.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

Freshly inited expo project except for the following change to app.json:
```
{
  "expo": {
    "name": "my-app",
    "slug": "my-app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "runtimeVersion": "1.0.0",                    <---------------
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

**Comment by jkhales** [comment]
Hey @nabn ,

The problem is that `Expo Go` only works with standard expo SDK runtimes. So, in your case `exposdk:44.0.0` should work.

If you wanted to do a custom runtime version, you need to use a dev client: https://docs.expo.dev/development/getting-started

This could be better explained, inspired by your question, @jonsamp is writing something up now. 🙏

**Comment by nabn** [comment]
Thanks @jkhales. We were able to eventually figure it out. Maybe it's possible to have better messaging around why the app failed to start when this happens.

**Comment by natelohn** [comment]
@nabn Could you explain what you did to fix this? I'm currently trying to work through the same (or a similar) issue right now. 
I've tried changing my `runtimeVersion policy` to `sdkVersion` instead of `nativeVersion` (my preferred choice) as described here: https://docs.expo.dev/eas-update/runtime-versions/ but that still does not work on the iPhone 11 Pro Max simulator. Here is my `app.json`:

> `{
  "expo": {
    "name": "App Name",
    "slug": "app-name",
    "version": "1.0.0",
    "runtimeVersion": {
      "policy": "nativeVersion"
    },
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "buildNumber": "4",
      "supportsTablet": true,
      "bundleIdentifier": "******"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "******",
      "versionCode": 4
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
`

**Comment by jonsamp** [comment]
@nabn Do you have all the minimum requirements for EAS Update? https://docs.expo.dev/eas-update/getting-started/#prerequisites

Also, I wrote up a debugging guide which might help you get to the bottom of the issue: https://docs.expo.dev/eas-update/debug-updates/

If you go through the steps above and are still unable to get your app running, please open a new issue with a reproduction (or with detailed steps on how to reproduce) and we will address it asap.

**Comment by xicond** [comment]
I'v got error `runtimeVersion:should be string`
```
$ eas -v
★ eas-cli@0.57.0 is now available, please upgrade.
Proceeding with outdated version

eas-cli/0.52.0 darwin-x64 node-v12.22.11

eas update --branch default --message "First EAS"

Failed to published updates
    CombinedError: [GraphQL] Manifest Validation Error:
    runtimeVersion:should be string
    This is likely a problem with your app.json, or app.config.js

```

**Comment by jdubs1994** [comment]
So what did you do to fix the issue? @nabn

**Comment by nabn** [comment]
Vaguely recall that the problem was I had a fractional value for `runtimeVersion` (like 0.1.1) and changing that to a whole number fixed it. I've since moved to a different project unfortunately, so my recollection might not be accurate.

**Comment by jonsamp** [comment]
@xicond What runtime version do you have in your app config?

-- We are currently fixing another edge case with runtime versions and I'd love to fix them all!

**Comment by jdubs1994** [comment]
@jonsamp it seems like expo go and eas runtime versions both want separate values. Or only current work around is removing the runTimeVersion from app.json so we can still run expo go. In order for us to use OTA updates we add the runTimeVersion back in a build script step for prod. Is this on y'all's radar? This is for a barework flow. It's a work around but it would be great if expo go just ignored runTimeVersion so we don't have to remove it in order to get it to work.

**Comment by carissacks** [comment]
In [this](https://github.com/expo/expo/issues/18631) issue, specifically [this comment](https://github.com/expo/expo/issues/18631), the writer highlighted [this](https://docs.expo.dev/build/updates/#previewing-updates-in-development-builds) part in the documentation
> Updates published with the runtimeVersion field can't be loaded in Expo Go; instead, you should use [expo-dev-client](https://docs.expo.dev/clients/introduction/) to create a development build.

So I think it's intentional? CMIIW

**Comment by lucasdzuc** [comment]
@natelohn I tested this and it worked

"runtimeVersion": {
    "policy": "sdkVersion",
    "nativeVersion": "46.0.0"
}

**Comment by kendallroth** [comment]
> In [this](https://github.com/expo/expo/issues/18631) issue, specifically [this comment](https://github.com/expo/expo/issues/18631), the writer highlighted [this](https://docs.expo.dev/build/updates/#previewing-updates-in-development-builds) part in the documentation
> 
> > Updates published with the runtimeVersion field can't be loaded in Expo Go; instead, you should use [expo-dev-client](https://docs.expo.dev/clients/introduction/) to create a development build.
> 
> So I think it's intentional? CMIIW

Qhile it may be intentional, it is quite confusing and unfortunately not well-spelled out (especially alternatives). Would be awesome if we could get some provided clarity around this, especially on whether Expo Go is intended to be used alongside Expo Update (and alternatives if not).

**Comment by kakha13** [comment]
My solution change app.json following data
```
"runtimeVersion": {
    "policy": "nativeVersion"
  }
```
