### ISSUE TITLE
any quick way to install a production app in android?

### ISSUE THREAD

**Issue by sunset1234321** [expo/expo#16205]
### Summary

it runs perfectly in expo go.

also run perfectly in test flight,

however, crash in internal testing in the android play store.

I am reducing my code bit by bit and trying to build and submit it to the play console to test when will it "not crash".

but "eas build“ android takes a long time, any quick way to install the build app on android?
 

### Link to the related docs page

https://docs.expo.dev/distribution/uploading-apps/

**Comment by byCedric** [comment]
Please see:
- `expo run:android` - https://docs.expo.dev/bare/hello-world/
- https://docs.expo.dev/build-reference/local-builds/
