### ISSUE TITLE
IOS Release Build Failed: Could not find the expected embedded asset at-rules.json. Check that expo-updates is installed correctly.

### ISSUE THREAD

**Issue by sumanbhattarai** [expo/expo#16219]
### Summary

My React Native app works fine in iOS debug mode. But, when I tried to run the app in release mode from xCode, the build is failed. However, in android, it works fine in both debug and release mode.
`File /Xcode/DerivedData/myapp-ewjafyqwkgvybabvuzpfqtubujvv/Build/Products/Release-iphonesimulator/ios.app/main.jsbundle does not exist. This must be a bug with.`

Then I tried generating the main.jsbundle manually by running the following command and adding this main.jsbundle in Copy Bundle Resources in Build Phases from XCode.
`npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`

Still, I am not being able to build the ios app in release mode but this time the build succeed but the app doesn't show anything in screen and the error i got in Xcode is:
`Could not find the expected embedded asset at-rules.json. Check that expo-updates is installed correctly.`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.5.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.19.1 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

1. In your bare workflow, open the project for iOS in XCode.
2. Select `release` in `edit scheme` from the `product`.
3. Build the application.

**Comment by sumanbhattarai** [comment]
.

**Comment by wrsulliv** [comment]
@sumanbhattarai Were you able to resolve this issue?  I am having the same problem.

**Comment by sumanbhattarai** [comment]
@wrsulliv No. But i get rid of expo by created a new react native cli project and copied all the files and used alternative packages for expo related packages.

**Comment by chefk5** [comment]
Any solution?

**Comment by bfar97** [comment]
Having the same issue!
