### ISSUE TITLE
expo-haptics not working on standalone app

### ISSUE THREAD

**Issue by qaws5503** [expo/expo#16218]
### Summary

Hi everyone, I always develop in the Expo Go app before and everything works fine. Recently I build my standalone app by `expo build:android -t apk` and install it in my android phone. Then I found `expo-haptics` doesn't work on standalone app.

The [docs](https://docs.expo.dev/versions/latest/sdk/haptics/#configuration) here says permission will add automatically. Which means don't need any extra steps to use in standalone app. What's the problem here?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.0

### Environment

```
Expo CLI 4.13.0 environment info:
  System:
    OS: macOS 11.6
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.09.06.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  npmPackages:
    expo: ^43.0.0 => 43.0.3
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-web: 0.17.1 => 0.17.1
    react-navigation: ^4.4.4 => 4.4.4
  npmGlobalPackages:
    expo-cli: 4.13.0
  Expo Workflow: managed
```

### Reproducible demo

example code from [docs](https://docs.expo.dev/versions/latest/sdk/haptics/#usage)

```
import * as React from "react";
import { StyleSheet, View, Text, Button } from "react-native";
import * as Haptics from "expo-haptics";

export default function test() {
  return (
    <View style={{ flex: 1 }}>
      <Button
        title="Success"
        onPress={() =>
          Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)
        }
      />
      <Button
        title="Error"
        onPress={() =>
          Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error)
        }
      />
      <Button
        title="Warning"
        onPress={() =>
          Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning)
        }
      />
    </View>
  );
}

```

**Comment by brentvatne** [comment]
did you set `permissions` in app.json? this will change default permissions. if so you should ensure that the vibrate permission is included

**Comment by qaws5503** [comment]
Hi @brentvatne , thanks for your reply. I solve it by adding `"android.permissions":["VIBRATE"]`.

And I felt some thing weird here. Because I didn't have `"android.permissions"` before! But it still doesn't vibrate when I call `Haptics.notificationAsync`. And when I dig in, I think I found the problem.

I also had to use `expo-image-picker`, so I followed the [docs](https://docs.expo.dev/versions/latest/sdk/imagepicker/#example-appjson-with-config-plugin) and add `"plugins"` to use it.
I think maybe `"plugins"` will auto write `"android.permissions"`, so even if I didn't have `"android.permissions"` before. Expo-cli still detect I have `"android.permissions"`, which let `expo-haptics` doesn't auto create permissions.

Maybe you can update the doc of `expo-haptics` to let them know that if using `"plugins"`, still need to manual write `"android.permissions":["VIBRATE"]`.

Thanks for your help!!

**Comment by EvanBacon** [comment]
@qaws5503 you can disable the auto plugin by tricking the memoization into thinking `expo-image-picker` has already been applied, simply register `expo-image-picker` in the `_internal.pluginHistory` object:

```
{
    "expo": {
        "_internal": {
            "pluginHistory": {
                "expo-image-picker": {}
            }
        }
    }
}
```

You can view the results with `expo config --type prebuild` and checking the `android.permissions` array.
Ultimately, the Android permissions in the legacy `expo build` are pretty faulty so I recommend moving to `eas build` as soon as possible.

**Comment by brentvatne** [comment]
@qaws5503 - you are right that this is an unintended side effect of config plugins on the classic build service (`expo build`). sorry for introducing that confusion. i do recommend migrating to EAS Build instead because [we'll stop supporting it after SDK 46](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60)

**Comment by qaws5503** [comment]
Okay! Thanks for the help and explanation. I'll try `eas bulid` in the future.

Happy coding🎉
