### ISSUE TITLE
Expo Notification 401 Error "Project not permitted"

### ISSUE THREAD

**Issue by RiccardoPizzutti** [expo/expo#16215]
### Summary

Hi everybody, 

i get this error when trying to send a push notification to an Android device: 

```json
{
    "data": {
        "id": "MESSAGE-ID",
        "status": "error",
        "message": "Failed to authenticate with the FCM server. Ensure the FCM server key you uploaded is correct.",
        "details": {
            "error": "InvalidCredentials",
            "fault": "developer",
            "fcm": {
                "httpStatus": 401,
                "response": "<HTML>\n<HEAD>\n<TITLE>PROJECT_NOT_PERMITTED</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#FFFFFF\" TEXT=\"#000000\">\n<H1>PROJECT_NOT_PERMITTED</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n"
            }
        }
    }
}
```

What i have tried so far: 
- Made shure, the API Key in google-services.json is valid and unrestricted
- Made shure the auto generated key by FCM is valid and unrestricted
- The Server Key from FCM "Cloud Messaging" is valid and correctly set in Expo credentials
- I also tried an alternative Cloud Messaging Key
- Deleted the whole Google Project and Setup everything from scratch with new Keys 
- Tried to use "useNextNotificationsApi": true"
- Sent messages with the same FCM/GCP-Key and -Restrictions directly via FCM with Device Token - works perfect

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.3.2 - ~/.nvm/versions/node/v14.17.5/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

I tried the Expo-Notification-Tool and this HTTP-Request via Postman: 

curl --location --request POST 'https://exp.host/--/api/v2/push/send' \
--header 'Content-Type: application/json' \
--data-raw '{
  "to": "ExponentPushToken[PUSH-TOKEN]",
  "title":"hello",
  "body": "world"
}'

Both respond with the noted error

**Comment by byCedric** [comment]
Hi @RiccardoPizzutti! How did you generate the `ExponentPushToken`? These are tied to the project identifiers, we call them experience ids (e.g. `@bycedric/myapp`, or `@<owner>/<slug>`. If the token is created inside a dev project, e.g. different owner or different slug, the FCM credentials won't be available.

**Comment by MaximeBrt** [comment]
i have the same problem while trying to push a notification from the FCM with postman. 
<HTML>

<HEAD>
	<TITLE>PROJECT_NOT_PERMITTED</TITLE>
</HEAD>

<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
	<H1>PROJECT_NOT_PERMITTED</H1>
	<H2>Error 401</H2>
</BODY>

</HTML>

i checked the key several times and when i change something i have either the "key invalid" error or no error at all because the problem is from the application.
This is what I send : 


{ 
 "notification": {
  "title": "First Notification", 
  "body": "Hello from Jishnu!!"
 },
 "to" : "Generated key"
}

**Comment by mickaeljoody** [comment]
Same error...

**Comment by MaximeBrt** [comment]
i used the older version of firebase cloud messaging and used the other key generated and it worked

**Comment by raminnoodle** [comment]
Same here for me here also.

> i used the older version of firebase cloud messaging and used the other key generated and it worked

What version?

**Comment by QuentinBellus** [comment]
For anyone finding this thread: I had the same issue, I just followed this, and it solved it!
https://stackoverflow.com/a/72504546

(I had to enable also Cloud Messaging API in my case)
