### ISSUE TITLE
Module not found: Can't resolve '../../Utilities/Platform'

### ISSUE THREAD

**Issue by iboxgithub** [expo/expo#16227]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by iboxgithub** [comment]
Hi, 
follow up on https://github.com/expo/web-examples/issues/89 and https://github.com/expo/web-examples/issues/73, the same error still happens when trying (from the basic expo Tabs template example) to run "yarn web" from a Bare workflow. 

Anyone else with this issue? Or no one is even trying Web anymore?

**Comment by brentvatne** [comment]
hi there! please share an example where we can reproduce this and we can investigate. this is not happening for others. i initialized both tabs template and bare template projects and both ran as expected on web.

**Comment by iboxgithub** [comment]
Hi @brentvatne,
 that would be awesome if you could take a look! this is the repo to reproduce my project: [test3](https://github.com/iboxgithub/test3)
This [lib](https://github.com/DoubleSymmetry/react-native-track-player) might have something to do with it but is not referenced in the error stack... 
I also opened the point on [this forum](https://github.com/Appboy/appboy-react-sdk/issues/119#issuecomment-1036369064)

**Comment by brentvatne** [comment]
oh i see. this is not related to expo tools. that library does not appear to support web.

**Comment by iboxgithub** [comment]
do you know why though? if you could hint at how to make it happen it would be awesome, I am willing to dive in and help them with a PR but I would need somewhere to look at first as with this error message I have no clue :(

**Comment by wrsulliv** [comment]
Ok, I was finally able to solve my own instance of this problem:

After running the "Debug in Exponent" launch target from VSCode (installed via React Native Tools), I noticed a line was added to `app.json`:

```
"entryPoint": ".vscode/exponentIndex.js"
```

Removing that line fixed my web build.

@iboxgithub  @brentvatne just tagging in case this helps

**Comment by jason840917gmail** [comment]
Still Happening with the latest version of Expo CLI 6.1.0 and SDK 47, It would be good to clarify that the Web doesn't work in the main site before people choose your technology, what a waste of time.

**Comment by XxQuickSilverZz** [comment]
> Still Happening with the latest version of Expo CLI 6.1.0 and SDK 47, It would be good to clarify that the Web doesn't work in the main site before people choose your technology, what a waste of time.

still the same today....
