### ISSUE TITLE
exp build:ios - unable to build and sign IPA

### ISSUE THREAD

**Issue by leomayleomay** [expo/expo#1622]
the issue mentioned in https://github.com/expo/expo/issues/1305 still persists

exp version: 51.4.0

build ID: `a6294978-1168-4267-ba92-5bf08167618f`

**Comment by tcdavis** [comment]
Can you try building again?

**Comment by leomayleomay** [comment]
@tcdavis still not working, build IDs: 
```
53d08ed7-05e5-47f9-b71c-03cbe3a9f75d (without -c)
ba4facfe-8f9e-4aed-89df-a30417b3c567 (with -c)
```

**Comment by tcdavis** [comment]
I think something might be off with your provisioning profile.  Can you build again and choose to have us handle your credentials to confirm?

**Comment by leomayleomay** [comment]
@tcdavis I tried to have Expo handle the credentials for me, and here's another error I've got

![image](https://user-images.githubusercontent.com/48898/38530725-339c4464-3cc0-11e8-92fa-06209d718a67.png)

**Comment by tcdavis** [comment]
You'll need to revoke one of your existing certificates so we can create one for you

**Comment by ericmorgan1** [comment]
See if any of these solutions works:
https://forums.expo.io/t/errors-on-exp-build-ios/8686/6

**Comment by leomayleomay** [comment]
@ericmorgan1 cheers, will check that out :)

**Comment by leomayleomay** [comment]
@tcdavis it seems to be working, but the IPA is size of 170MB? haha, that's unexpected

**Comment by leomayleomay** [comment]
the build works by letting Expo handle all the certificate generation, great thanks go to @tcdavis and @ericmorgan1
