### ISSUE TITLE
[docs] how to install local package

### ISSUE THREAD

**Issue by jankapunkt** [expo/expo#16239]
### Summary

I have a package that is working with RN+expo when installing from npm registry. However, when installing the exact same package from a local folder it will not find the package but only returns

```bash
packageXYZ could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
```

### Link to the related docs page

https://docs.expo.dev/workflow/using-libraries/#using-third-party-libraries

https://docs.expo.dev/build-reference/private-npm-packages/

### Anything else?

None of the docs tell me how to do it, so I assume this is simply a missing topic. I see this relevant, since I need to test packages with my running project when developing them, right?

**Comment by brentvatne** [comment]
this is a good question, metro does not make this very easy because it doesn't support symlinks. a couple alternatives:

- run `npm pack` inside of your library and then `npm install path/to/the/packed/file.tgz` from your project
- use a monorepo: https://docs.expo.dev/guides/monorepos/

**Comment by jankapunkt** [comment]
Thanks a lot for helping me out here, the `npm pack` version works as expected! This issue can be closed from my end, unless you think this should be added to the guide somewhere.

**Comment by technoplato** [comment]
> metro does not make this very easy because it doesn't support symlinks

Hey @brentvatne - since support for symlinks was added to metro in RN72, would you expect this to work now?

https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks

**Comment by brentvatne** [comment]
@technoplato - ymmv! you may need to do additional configuration for metro to ensure your symlinked packages' dependencies are handled correctly

**Comment by technoplato** [comment]
> @technoplato - ymmv! you may need to do additional configuration for metro to ensure your symlinked packages' dependencies are handled correctly

Thank you - will check that out

**Comment by wnadurski** [comment]
@technoplato did you manage to make it work?

**Comment by 2ico** [comment]
Anyone knows why `npm link` doesn't work?
