### ISSUE TITLE
Lot of deprecated warnings!

### ISSUE THREAD

**Issue by mgscreativa** [expo/expo#1623]
Hi! Today I upgraded expo to v26 for my CRNA project and started to get lot of warning messages

> 
> YellowBox.js:82 Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.
> 
> Please update the following components: ExpoRootComponent, RootErrorBoundary, View

Is there any way to get rid of them, because I think lot of Expo components still use `componentWillMount`.

Thanks!

**Comment by brentvatne** [comment]
see the section about "React lifecycle methods" in release notes https://blog.expo.io/expo-sdk-v26-0-0-is-now-available-2be6d9805b31

**Comment by mgscreativa** [comment]
Great warnings gone by adding console.disableYellowBox = true; to App.js!

Thanks!
