### ISSUE TITLE
[expo-barcode-scanner](iOS only) EAS Fastlane build failed

### ISSUE THREAD

**Issue by TrustyTechSG** [expo/expo#16234]
### Summary

EAS Fastlane build failed once add "expo-barcode-scanner": "^11.2.1", simply remove "expo-barcode-scanner" build will become fine.

EAS console error:

Compiling Pods/ZXingObjC » ZXRGBLuminanceSource.m

❌  (ios/Pods/ZXingObjC/ZXingObjC/core/ZXRGBLuminanceSource.m:62:40)

  60 |     _left = 0;
  61 |     _top = 0;
> 62 |     _luminances = [[ZXByteArray alloc] initWithArray:pixels length:width * height];
     |                                        ^ no visible @interface for 'ZXByteArray' declares the selector 'initWithArray:length:'
  63 |   }
  64 |   return self;
  65 | }
› Compiling Pods/ZXingObjC » ZXProductResultParser.m
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	CompileC /Users/expo/Library/Developer/Xcode/DerivedData/EasyBusMobile-cgeabdytddfhapfhdxsgtejpmgqr/Build/Intermediates.noindex/ArchiveIntermediates/EasyBusMobile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/ZXingObjC.build/Objects-normal/arm64/ZXRGBLuminanceSource.o /Users/expo/workingdir/build/ios/Pods/ZXingObjC/ZXingObjC/core/ZXRGBLuminanceSource.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'ZXingObjC' from project 'Pods')
▸ (1 failure)
** ARCHIVE FAILED **

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.1.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.1.1
    Expo Workflow: managed

### Reproducible demo

EAS build link: https://expo.dev/accounts/trustytech/projects/easybus-mobile/builds/788ce70a-d70f-4901-9f2c-5707d47f78c3

**Comment by brentvatne** [comment]
would you be able to share a reproducible example? i initialized a project and installed expo-barcode-scanner and it built successfully.

**Comment by TrustyTechSG** [comment]
> would you be able to share a reproducible example? i initialized a project and installed expo-barcode-scanner and it built successfully. maybe you are using another library that depends on ZXingObjC?
> 
> note that this doesn't look specific to eas build - you should also be able to reproduce this locally with `expo run:ios` (which runs `expo prebuild`, so you will want to [clean up after debugging](https://expo.fyi/prebuild-cleanup))

Hi @brentvatne , thank you for your quick response, sorry here is the reproducible repo：https://github.com/TrustyTechSG/ZXingErrorReproduce

EAS build on this repo should facing the same ZXing error. if you remove expo-barcode-scanner, build will become fine.

**Comment by brentvatne** [comment]
hey @TrustyTechSG - thanks for sharing! could you please try removing some of your dependencies and narrowing it down to the minimal set of dependencies to reproduce this error? it looks like there are about 70 dependencies in your project

**Comment by TrustyTechSG** [comment]
> hey @TrustyTechSG - thanks for sharing! could you please try removing some of your dependencies and narrowing it down to the minimal set of dependencies to reproduce this error? it looks like there are about 70 dependencies in your project

Hi @brentvatne , by narrowing down the dependencies, I found out it is caused by the printing dependency which also using ZXing, which caused the build issue I think, Im closing this issue now. Thank you.
