### ISSUE TITLE
Cannot open my project

### ISSUE THREAD

**Issue by sandervspl** [expo/expo#1624]
I am unable to open any generated link from any Expo product (CLI and XDE). The iOS client shows an app in 'recently in development', but nothing happens when I'm pressing the link. Everything worked perfectly fine before I ejected from CRNA and with the QR scanner. Am I doing something wrong? Am I skipping (a) step(s)? The documentation on this is terrible to say the least.

**Comment by sandervspl** [comment]
Fixed it by creating a new blank project, and moving over my source code to that blank project.

**Comment by terribleben** [comment]
Hi! Really sorry you ran into issues with this. Looks like we missed this issue when you opened it. We can probably help out  if you provide a bit more information. Would you mind posting on the [forums](http://forums.expo.io/) if you're still having issues?
