### ISSUE TITLE
expo client:install:ios for custom dev clients

### ISSUE THREAD

**Issue by bkasten-rbi** [expo/expo#16258]
There is a very handy command to install `Expo Go` on simulators with `expo client:install:ios`. Our company is now making our own custom dev clients via EAS, and I was wondering if there was plans to have a simple mechanism to install the latest dev clients from eas. 

Currently our devs have to go to EAS directly and download the .app, unzip it and drag it to the simulator. Would love to simplify and automate this process

**Comment by brentvatne** [comment]
this is definitely something that we want to build at some point.

it could be possible for you to build a similar tool on your own until we provide something for this. for example, you could do `eas build:list --buildProfile development --json` and then use jq to parse out the `artifacts.buildUrl` and then curl it

**Comment by brentvatne** [comment]
i'm going to close this because we use issues for bug reports but i want to acknowledge that this is indeed on our radar and something we're thinking about

**Comment by blainekasten** [comment]
Awesome, thanks for the direction!
