### ISSUE TITLE
Video plays in incorrect orientation on some devices(Redmi 1s)

### ISSUE THREAD

**Issue by abhishek-raj** [expo/expo#1625]
### Environment
Android(Expo Experience and Standalone)

### Steps to Reproduce
1. Open the snack on android on Redmi 1s(Android 4.4.4)

### Expected Behavior
Video playing in correct orientation

### Actual Behavior
Video isn't playing in correct orientation.
Note - The big buck bunny plays in correct orientation. Just the videos recorded on the device doesn't play correctly. I don't know how to get the video details. Here is the link to a sample video that doesn't play correctly - 

https://govideestorage.blob.core.windows.net/asset-882eff81-31f4-481e-b27b-c4edcac1df7c/something.mp4?sv=2012-02-12&sr=c&si=420893bb-b4e5-4f56-8ef5-d276f1fdfe4a&sig=fap8OkFOR9BxBQW8OT4zb9fhSvBRvVLw8SX9yU3upcA%3D&st=2018-04-09T21%3A05%3A50Z&se=2018-05-09T21%3A05%3A50Z

### Reproducible Demo

https://snack.expo.io/ryVbqUFiG

**Comment by abhishek-raj** [comment]
All videos recorded from any phone be it iPhone or Android the video doesn't play correctly. I can provide more sample videos if you want.

Also the big buck bunny from the http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4 plays correctly.

**Comment by cruzach** [comment]
The minimum Android version we support now [is Android 5](https://docs.expo.io/versions/latest/introduction/installation/#mobile-client-expo-for-ios-and-android). If you see this behavior on a supported version and a more recent SDK, please open a new issue. (I tested this on SDK 34 with [this snack](https://snack.expo.io/@charliecruzan/examplerecordasync) and didn't see any problems)
