### ISSUE TITLE
[expo-media-library] createAssetAssync not working on Android 11 even with permissions

### ISSUE THREAD

**Issue by lucasvndrl** [expo/expo#16257]
### Summary

Hi there, so, I am facing a issue with expo-media-library: when I try to download a file from my app, first I ask for permission using MediaLibrary.requestPermissionsAsync(), which is granted and I already checked that. But even so, I always get this error: Unable to copy file into external storage. in createAssetAsync. Browsing through the internet I noticed that others devs had already faced that issue or something alike, but I didn't find any solution :\ Can someone help me? 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

"expo": "^42.0.3"

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.22.17 - /usr/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    npmPackages:
      babel-preset-expo: 8.4.1 => 8.4.1 
      expo: ^42.0.3 => 42.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@lpedroza.external/forlorn-french-fries

**Comment by brentvatne** [comment]
hi there! have you read this doc yet? https://github.com/expo/fyi/blob/main/android-r.md

**Comment by lucasvndrl** [comment]
New update: I was running some tests on my physical phone instead of a emulator trying to figure out what to do and these were my consoles: 

       const albumName = 'Download'

       const album = await MediaLibrary.getAlbumAsync(albumName)

        console.log(album) // here I get the album with his ID and Assets in it, because my phone does have a Download folder.

        const test = await MediaLibrary.albumNeedsMigrationAsync(albumName)

        console.log(test) // here I get "Couldn't find album" error which is odd since one console.log behind the album exists

So, right now I don't think that the main issue is *only* in the createAssetAsync

**Comment by brentvatne** [comment]
@lucasvndrl - can you possibly try creating a reproducible example repo using sdk 44 and walk us through the exact steps we should follow, including which exact android version you are using, in order to reproduce the issue? this would be helpful for us to be able to investigate further. also cc @lukmccall, who last worked on expo-media-library and may have insight
