### ISSUE TITLE
[expo-updates] Updates.reloadAsync() does not work normally when switching to foreground.

### ISSUE THREAD

**Issue by k22pr** [expo/expo#16264]
### Summary

If the app has been on the background for a long time, we are preparing to run it again.

```ts
  React.useEffect(() => {
    AppState.addEventListener("change", _handleAppStateChange);

    return () => {
      AppState.removeEventListener("change", _handleAppStateChange);
    };
  }, []);

  const _handleAppStateChange = async (nextAppState: any) => {
    if (appState.current.match(/inactive|background/) && nextAppState === "active") {
      console.log("App has come to the foreground!");
      await Updates.reloadAsync();
    } else {
    }

    appState.current = nextAppState;
    setAppStateVisible(appState.current);
  };
```

However, if run reloadAsync within AppState.addEventListener, the app will crash and stop on the splash screen.

Please let me know if I miss something or if there is something wrong.

Please refer to the attached link for Snack.

Thank you.

---

Check the update of the starting point and reload.✅

Click the button to reload the reload.✅

Reload when switching to the foreground in the background.❌

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 5.1.1 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^43.0.0 => 43.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

## Snack
https://snack.expo.dev/@total.trade/expo-reload-test

### Test device
 - Galaxy S10(SM-G973N)
 - Xiaomi Mi Note 9

**Comment by brentvatne** [comment]
can you try this on sdk 44?

**Comment by k22pr** [comment]
@brentvatne 
Yes, it occurs the same in SDK 44.
And no Exception appears.

**Comment by k22pr** [comment]
The same issue occurs even when the reload button is pressed after switching to the foreground.

If give 7 second delay as setTimeout, it will operate normally.


```ts

  const _handleAppStateChange = async (nextAppState: any) => {
    if (appState.current.match(/inactive|background/) && nextAppState === "active") {
      console.log("App has come to the foreground!");
      setTimeout(async () => {
        try {
          await Updates.reloadAsync();
          console.log("end");
        } catch (e) {
          console.error(e); //Can't see.
        }
      }, 7000);
    }
}
```

Is there a possible cause?

**Comment by laithalshabi** [comment]
+1

**Comment by FrenchMajesty** [comment]
Yes, same issue here. I'm finding that I need to kill my app completely and re-open it in order for the JS bundle to get updated, despite calling `Updates.reloadAsync()`.

```
eas-cli/3.9.0 darwin-x64 node-v16.19.1
expo 48.0.10
```

**Comment by yamak-app** [comment]
+1 it crash on ios not working sdk 49

**Comment by MarouaniALA** [comment]
not working on sdk 49

**Comment by pacehutt** [comment]
Not working in production build with expo sdk 49
