### ISSUE TITLE
expo-av: Pausing video is slow

### ISSUE THREAD

**Issue by Livijn** [expo/expo#16262]
### Summary

I use the `<Video />` component from the [expo-av package](https://docs.expo.dev/versions/latest/sdk/video/). Whenever I try to pause a video, it's a small delay. It feels like the video is "winding down". However, sometimes it pauses immediately. 

This does NOT happen in the simulator, but it happens when running the app on my physical device via Expo Go. My phone is a iPhone 12 Pro with iOS 15.3.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

>  Expo CLI 5.0.3 environment info:
>     System:
>       OS: macOS 12.1
>       Shell: 5.8 - /bin/zsh
>     Binaries:
>       Node: 17.3.0 - /usr/local/bin/node
>       Yarn: 1.22.17 - /usr/local/bin/yarn
>       npm: 8.3.0 - /usr/local/bin/npm
>     Managers:
>       CocoaPods: 1.10.1 - /usr/local/bin/pod
>     SDKs:
>       iOS SDK:
>         Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
>     IDEs:
>       Android Studio: Arctic Fox 2020.3.1 Patch 3 Arctic Fox 2020.3.1 Patch 3
>       Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ^44.0.0 => 44.0.6
>       react: 17.0.1 => 17.0.1
>       react-dom: 17.0.1 => 17.0.1
>       react-native: 0.64.3 => 0.64.3
>       react-native-web: 0.17.1 => 0.17.1
>     npmGlobalPackages:
>       eas-cli: 0.41.1
>       expo-cli: 5.0.3
>     Expo Workflow: managed

### Reproducible demo

Will provide later

**Comment by Livijn** [comment]
Fixed by using the `progressUpdateIntervalMillis` prop.

**Comment by hirbod** [comment]
This issue is 100 % legit

**Comment by hirbod** [comment]
And there is already an issue for his as well
https://github.com/expo/expo/issues/5297

**Comment by hirbod** [comment]
@Livijn I've fixed the issue and it got approved by Expo. Will be in the next release :)

**Comment by Livijn** [comment]
Care to link the PR?

**Comment by hirbod** [comment]
Its autolinked -> https://github.com/expo/expo/pull/16578

**Comment by Livijn** [comment]
> Its autolinked -> #16578

Ah, yeah thanks! Was on mobile app so didn't see / think of it :)

**Comment by bbarthec** [comment]
Some changes in the following packages that may fix this issue have just been published to npm under `next` tag 🚀

| 📦 Package | 🔢 Version | ↖️ Pull requests | 📝 Release notes |
|:--:|:--:|:--:|:--:|
| [expo-av](https://www.npmjs.com/package/expo-av/v/11.1.0) | 11.1.0 | #16578 | [CHANGELOG.md](https://github.com/expo/expo/blob/main/packages/expo-av/CHANGELOG.md) |

If you're using bare workflow you can upgrade them right away. We kindly ask you for some feedback—even if it works 🙏

They will become available in managed workflow with the next SDK release 👀

Happy Coding! 🎉
