### ISSUE TITLE
[expo-notifications][android] Data-only FCM notification shows an empty item in the tray

### ISSUE THREAD

**Issue by wschurman** [expo/expo#16261]
### Summary

Data messages in android https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages are notifications that are handled by the app. In expo-notifications, it seems that all notifications are handled by the library (all notifications are data notifications). 

When these don't contain a body or title the expected behavior is to not show the notification in the tray (foreground or background). Note that when in the foreground the behavior can be set via `setNotificationHandler` but this doesn't apply to background.

The bug is that these are shown as a blank notification in the tray and drawer.

![Screenshot_20220210-205622](https://user-images.githubusercontent.com/189568/153540068-9869af76-1ac2-44e4-9684-304c3299e595.png)
![Screenshot_20220210-205617](https://user-images.githubusercontent.com/189568/153540072-e913de42-92a0-4355-bc7d-3deaea70096c.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.8.0 - ~/.volta/tools/image/node/16.8.0/bin/node
      Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
      npm: 7.21.0 - ~/.volta/tools/image/node/16.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        Android NDK: 22.0.6917172-beta1
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

1. Create expo app (`expo init repro-app`), choose typescript (though shouldn't matter, just using ts for repro code)
2. Follow the setup steps for `expo-notifications` on Android: https://docs.expo.dev/versions/latest/sdk/notifications/ 
3. Put the following in App.ts

```typescript
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import React, { useState, useEffect, useRef } from 'react';
import { Text, View, Platform } from 'react-native';
import { Notification } from 'expo-notifications';
import { Image } from 'react-native';
import { Subscription } from 'expo-modules-core';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: false,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function App() {
  const [expoPushToken, setExpoPushToken] = useState<string | undefined>('');
  const [devicePushToken, setDevicePushToken] = useState<string | undefined>('');
  const [notification, setNotification] = useState<Notification | undefined>();
  const notificationListener = useRef<Subscription>();
  const responseListener = useRef<Subscription>();

  useEffect(() => {
    registerForPushNotificationsAsync().then(([token, deviceToken]) => {
      setExpoPushToken(token);
      setDevicePushToken(deviceToken);
    });

    // This listener is fired whenever a notification is received while the app is foregrounded
    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      console.log(notification);
      setNotification(notification);
    });

    // This listener is fired whenever a user taps on or interacts with a notification (works when app is foregrounded, backgrounded, or killed)
    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      console.log(response);
    });

    return () => {
      if (notificationListener.current) {
        Notifications.removeNotificationSubscription(notificationListener.current);
      }
      if (responseListener.current) {
        Notifications.removeNotificationSubscription(responseListener.current);
      }
    };
  }, []);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-around',
      }}>
      <Text>Your expo push tokend: {expoPushToken}</Text>
      <Image source={require('./assets/icon.png')} style={{width: 100, height: 100}} />
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>Title: {notification && notification.request.content.title} </Text>
        <Text>Body: {notification && notification.request.content.body}</Text>
        <Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
      </View>
    </View>
  );
}

async function registerForPushNotificationsAsync(): Promise<[string | undefined, string | undefined]> {
  let token;
  let deviceToken;
  if (Constants.isDevice) {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return [undefined, undefined];
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    deviceToken = await (await Notifications.getDevicePushTokenAsync()).data;
    console.log(token);
    console.log(deviceToken);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  return [token, deviceToken];
}
```

3. Plug in development device (I'm using recent pixel but it shouldn't matter)
4. `expo run:android`
5. Copy the expo push token from the console log.
6. Send push notification via expo push notification api: https://docs.expo.dev/push-notifications/sending-notifications/

```
{
	"to": "ExponentPushToken[...]",
	"data": {"hello": "world"}
}
```
7. See that it is shown in the tray
8. Copy the device token from the console log.
9. Send push notification via FCM directly: https://docs.expo.dev/push-notifications/sending-notifications-custom/

```
{"to":"...","priority":"normal","data":{"experienceId":"@wschurman/brex-repro","scopeKey":"@wschurman/brex-repro","hello":"world"}}
```
10. See that it is also shown in the tray.

**Comment by josephyanks** [comment]
@sausti Wondering if this fix is still sufficient... I've noticed that in version `0.27.6`, if `shouldShowAlert` is set to `true`, the background notifications will still display. If you change `NotificationsHandler#onNotificationReceived` to include the `shouldPresent()` check, it prevents this behavior.

```
  override fun onNotificationReceived(notification: Notification) {
    val context = appContext.reactContext ?: return
+    if (!notification.shouldPresent()) return
    val task = SingleNotificationHandlerTask(context, handler, moduleRegistry, notification, this)
    tasksMap[task.identifier] = task
    task.start()
  }
```

**Comment by Aldo-Garza** [comment]
> @sausti Wondering if this fix is still sufficient... I've noticed that in version `0.27.6`, if `shouldShowAlert` is set to `true`, the background notifications will still display. If you change `NotificationsHandler#onNotificationReceived` to include the `shouldPresent()` check, it prevents this behavior.
> 
> ```
>   override fun onNotificationReceived(notification: Notification) {
>     val context = appContext.reactContext ?: return
> +    if (!notification.shouldPresent()) return
>     val task = SingleNotificationHandlerTask(context, handler, moduleRegistry, notification, this)
>     tasksMap[task.identifier] = task
>     task.start()
>   }
> ```

The issue is still present, even though the sent notification does not include neither title neither body as can be seen
![image](https://github.com/expo/expo/assets/131987767/92426538-4bd0-4467-982c-87be2f3308f4)
I noted that an empty title and body is added 
![image](https://github.com/expo/expo/assets/131987767/0ac20d5b-c6a6-42d9-8cf4-543b6cafef60)
shouldShowAlert is set to true on the notification handler

**Comment by daankennes** [comment]
@Aldo-Garza, did you find a solution?
