### ISSUE TITLE
expo-font: fonts not loading in through Font.loadAsync

### ISSUE THREAD

**Issue by curtisd14** [expo/expo#16263]
### Summary

Upgraded my project from expo 44.0.5 to 44.0.6 which took on new expo-fonts upgrade to 10.0.5. Since this, Font.loadAsync is unable to load in custom fonts

![Screenshot at 2022-02-11 10-10-34](https://user-images.githubusercontent.com/73228968/153574584-861b940b-1083-4de0-8b69-2527e84385be.png)

Code loading in fonts has not changed since upgrade
![Screenshot at 2022-02-11 10-13-39](https://user-images.githubusercontent.com/73228968/153574664-95e2fff9-6563-43c5-9562-730147020b88.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44.0.6

### Environment

Expo CLI 5.1.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed

### Reproducible demo

1.) Upgrade project to expo 44.0.6
2.) Run expo start to load project with code to load fonts in similar to below
![Screenshot at 2022-02-11 10-13-39](https://user-images.githubusercontent.com/73228968/153574802-49912a73-c82c-4bde-8de2-6d92a1881824.png)

**Comment by johnli-codaio** [comment]
Running into this as well, did you get a fix?

**Comment by peterkuiper** [comment]
Same here, still haven't found a solution other than downgrading.

**Comment by jameswilddev** [comment]
Experiencing the same problem after upgrade.

**Comment by mertafor** [comment]
There is a problem with 10.2.1, `Font.loadAsync` doesn't load the font. Works fine with 10.2.0. I'm using  `useCachedResources` hook which comes with default template :

```
export default function useCachedResources() {
  const [isLoadingComplete, setLoadingComplete] = useState(false);
  
  useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {
        SplashScreen.preventAutoHideAsync();

        // Load fonts
        await Font.loadAsync({
          ...Ionicons.font,
          'fontLight': require('../assets/fonts/interLight.ttf'),
          'fontRegular': require('../assets/fonts/interRegular.ttf'),
          'fontSemiBold': require('../assets/fonts/interSemiBold.ttf'),
          'fontBold': require('../assets/fonts/interBold.ttf'),
        });
      } catch (e) {
        // We might want to provide this error information to an error reporting service
        console.warn(e);
      } finally {
        setLoadingComplete(true);
        SplashScreen.hideAsync();
      }
    }

    loadResourcesAndDataAsync();
  }, []);

  return { isLoadingComplete };
```
