### ISSUE TITLE
[docs] Crypto docs nits.

### ISSUE THREAD

**Issue by tylerchambers** [expo/expo#16273]
### Summary

> expo-crypto enables you to hash (encrypt) data in an equivalent manner to the Node.js core crypto API.

hashing != encrypting. expo-crypto does not provide any encryption functionality. Deleting `(encrypt)` would fix it.

> [Cryptographic hash function](https://developer.mozilla.org/en-US/docs/Glossary/Cryptographic_hash_function) is an algorithm that can be used to generate a checksum value.

Hashes are not the same as checksums. A checksum is intended to verify (check) the integrity of data and identify data-transmission errors, while a hash is designed to create a unique digital fingerprint of the data.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/crypto/

**Comment by brentvatne** [comment]
thanks for pointing this out! fixed in https://github.com/expo/expo/commit/f6a0d82691f83193e19d1520110ff7490e081f9f
