### ISSUE TITLE
[EXPO-AV] Restore audio from other backgrounded apps when INTERRUPTION_MODE_IOS_DO_NOT_MIX  is used

### ISSUE THREAD

**Issue by Balintataw** [expo/expo#16272]
### Summary

Currently when using setAudioModeAsync and setting interruptionMode, any *_DO_NOT_MIX option kills all audio playing in other backgrounded apps. That audio then remains killed and does not restart. Is this intended behaviour? Is it possible to restart it or potentially just reduce backgrounded app audio volume to zero without killing it completely? We have a scenario where we want spoken audio from our app to be clearly heard over any background app audio and using DUCK does not lower volume sufficiently.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

No sdk. Using react-native-unimodules: "0.14.10"

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.3.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/Jossendal/.rvm/gems/ruby-2.6.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 25, 27, 28, 29, 30, 31
        Build Tools: 23.0.1, 25.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.0, 29.0.2, 29.0.3, 30.0.2
        System Images: android-21 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2
      react-native: 0.66.0 => 0.66.0
      react-navigation: 4.4.0 => 4.4.0
    npmGlobalPackages:
      eas-cli: 0.33.1
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

Unlikely sorry.

**Comment by brentvatne** [comment]
as far as i know ducking is the best option for this. if you know of an underlying ios api that can be used to handle this bettr then please let us know.

**Comment by RRaideRR** [comment]
It's not possible to set a specific volume for the ducked audio - right?

@Balintataw what did you end up doing?

@brentvatne I can observe that behavior from other apps - so somehow these apps managed to do it as well. Take as an example Spotify and Instagram:
I play a Spotify song. I switch to Instagram. I watch a video. The Spotify song stops here and the full volume is on the Instagram video. If the Instagram video finished or if I close Instagram, the Spotify song resumes automatically.

**Comment by RRaideRR** [comment]
As far as I see,

for iOS one has to notify the other apps (e.g. Spotify) that my app's audio session ended:
https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions/1616534-interruptspokenaudioandmixwithot


for Android one has to abandon audio focus once my app's sound has finished:
https://developer.android.com/guide/topics/media-apps/audio-focus


Unfortunately, I have never written any native code so I guess it won't be easy to me to make these adjustments to expo-av.

**Comment by RRaideRR** [comment]
This is now a feature request :-):

https://expo.canny.io/feature-requests/p/expo-av-restore-audio-from-background-apps
