### ISSUE TITLE
"ViewManagerAdapter_ExpoLinearGradient" was not found in the UIManager.

### ISSUE THREAD

**Issue by lfoliveir4** [expo/expo#16277]
### Summary

This issue is related to the expo-linear-gradient library linking. After installing this library, in iOS environment the library does not work causing the application to break. [The same issue](https://github.com/expo/expo/issues/5066) has already been reported and fixed for the android platform only.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.2

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
      Watchman: 2022.01.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.2 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

`expo install expo-linear-gradient`
`cd ios && pod install`
`expo start` and run on iOS simulator

<img width="443" alt="image" src="https://user-images.githubusercontent.com/32423942/153693447-8827b8fd-be4d-466c-aaab-c54770b94832.png">

**Comment by brentvatne** [comment]
can't reproduce this. you probably need to rebuild the project or ensure that you've installed expo modules properly. if you share a reproducible example we can help
