### ISSUE TITLE
Nested Modal Freeze/Crash

### ISSUE THREAD

**Issue by ericmorgan1** [expo/expo#1627]
### Attention

Reproducible Snack:
https://snack.expo.io/ry5e75Yof
  
### Environment

Snack / iOS

### Steps to Reproduce

Host a Modal inside of a Modal

* Previous behavior using native `Modal` was that nested `Modals` would cover each other up.
* It was recently recommended to use the Expo `Modal` and `ModalHost`.

There are two potential issues I've found:

First, in some cases when you have nested `Modals`, when you try to open them, the app will freeze. Eventually it will crash with a red screen error, although it takes several minutes. I haven't seen the crash on Snack, but it does freeze.
** To reproduce this: Remove the `ModalHost` from the `SomeComponent` class in the Snack.

Second, if you have nested Modals, you can prevent the freezing/crash mentioned above by also having a nested `ModalHost`. The downside to this is that the nested Modal will appear within the original modal rather than completely covering it, which was the behavior of the native `Modal`.
** To reproduce this: Open the first modal in the Snack, then open the second modal. Notice the green header of the original modal is still visible.

Use case:
You may want to have a modal with "Ok" and "Cancel" buttons on the top.
Within this modal, you might want more modals with "Ok" and "Cancel" buttons.
Example #1: A location search list that pulls up a modal, lets you search for a location, or cancel out.
Example #2: A modal that lets you choose a location and a date, which both pull up their own modals.

See the image below:
A DatePicker inside of a Modal. 
Now imagine if this DatePicker/Modal was launched from another Modal which also has a cancel button.
You would have stacked cancel buttons, which can be confusing.
(Maybe not the best design, but I think it's a realistic possibility)

![img_9282](https://user-images.githubusercontent.com/10346191/38531669-a615ef8e-3c36-11e8-9609-04e08aa07058.PNG)

### Expected Behavior

Expect
1) Nested modals don't freeze/crash
2) Modals cover other modals (maybe)

### Actual Behavior

1) Nested modals freeze/crash if there isn't another ModalHost
2) Modals don't cover each other

### Reproducible Demo

Reproducible Snack:
https://snack.expo.io/ry5e75Yof

**Comment by terribleben** [comment]
Hi there. We have a change pending internally that should rewrite the way we host modals in order to interop better with React Native's modal api. Tracking it in this [slightly different issue](https://github.com/expo/expo/issues/1616). We expect that improvement to ship in our next minor release.

**Comment by terribleben** [comment]
Sorry for the slow followup here. We did ship our modal improvements - can you try your usecase again and let us know if you're still seeing problems?

**Comment by ericmorgan1** [comment]
Thanks @terribleben 
Looks like sdk 28 has everything looking good.
Reference: https://snack.expo.io/HyiM7N6zX
