### ISSUE TITLE
Cannot find module '@babel-plugin-proposal-class-properties/babel-plugin'

### ISSUE THREAD

**Issue by nihil-pro** [expo/expo#16284]
### Summary

Logs for your project will appear below. Press Ctrl+C to exit.
iOS Bundling failed 961ms
App.tsx: Cannot find module '@babel-plugin-proposal-class-properties/babel-plugin'
Require stack:
- /Users/konstantinroman/Desktop/Important projects/newApp/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/konstantinroman/Desktop/Important projects/newApp/node_modules/@babel/core/lib/config/files/index.js
- /Users/konstantinroman/Desktop/Important projects/newApp/node_modules/@babel/core/lib/index.js
- /Users/konstantinroman/Desktop/Important projects/newApp/node_modules/metro-transform-worker/src/index.js
- /Users/konstantinroman/Desktop/Important projects/newApp/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/konstantinroman/Desktop/Important projects/newApp/node_modules/jest-worker/build/workers/processChild.js
Error: Cannot find module '@babel-plugin-proposal-class-properties/babel-plugin'

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

~44.0.0

### Environment

System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
      Watchman: 2022.01.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.44.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

```
module.exports = function(api) {
  api.cache(false);
  return {
    presets: ['@babel-preset-expo'],
    plugins: ['@babel-plugin-proposal-class-properties']
  };
};
```

```
"devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "typescript": "~4.3.5"
  },
```

**Comment by byCedric** [comment]
Your babel file seems to be invalid. Both the `presets` and `plugins` doesn't reference the right modules. Both start with an `@` symbol, indicating to babel that this is the organization of the package template `<org>/babel-plugin`. Change your babel config to the version below, I think that should fix it.

```
module.exports = function(api) {
  api.cache(false);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['@babel/plugin-proposal-class-properties']
  };
};
```

**Comment by nihil-pro** [comment]
I’m trying different ways, but no one works. Even template’s from expo init. Only first works fine. Templates with typescript don’t works. Empty typescript project doesn’t fast refresh, if I add mobx, it doesn’t work because of class properties.

now I start with js, but I really want typescript (
