### ISSUE TITLE
[expo-notifications][ios] Notification Settings missing

### ISSUE THREAD

**Issue by Rasha-Dj** [expo/expo#16287]
### Summary

It is not possible to access Notification Settings for my app anymore. The app does prompt the user to allow notifications, but when user clicks "App Settings" button the app doesn't have notification settings as an option. It's as if something is off with permissions.

I suspect there could be an issue with how expo-notifications work with my APN key and app, but I don't know how to debug this (this is where I could use some tips).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

Production issue

### Reproducible demo

Production issue

**Comment by byCedric** [comment]
Hi @Rasha-Dj! If the app settings are incorrect on iOS, [your app would crash instead](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources). 

![image](https://user-images.githubusercontent.com/1203991/153884274-bcf5029b-c2f2-42c3-9fb3-9e64b9e26234.png)

It might be related to some weirdness with spotlight, as described [here](https://jilaxzone.com/2021/10/05/heres-how-to-fix-missing-notifications-on-ios-15-and-ipados-15/), [here](https://developer.apple.com/forums/thread/92552), and [here](https://www.reddit.com/r/ios/comments/qpb03b/apps_not_showing_up_in_settingsnotifications/).

Hope this helps!
