### ISSUE TITLE
iPad Double-Splash Screen: shows phone splash, then tablet splash (standalone only)

### ISSUE THREAD

**Issue by ansonhoyt** [expo/expo#1628]
After adding `ios.splash.tabletImage` with a scaled image, we noticed something odd when testing a simulator build on the iPad:
1. the default `splash.image` shows for a second (not expected)
2. then `ios.splash.tabletImage` shows for a second
3. finally, the app renders.

Works fine in the iOS Expo Client. The problem showed up when we loaded a standalone build in iOS Simulator with an iPad.

app.json excerpt
```
{
  "expo": {
    "sdkVersion": "26.0.0",
    "splash": {
      "image": "./img/eita-splash.png"
    },
    "ios": {
      "splash": {
        "tabletImage": "./img/eita-splash3x.png",
      },
}
```

### Environment

```
$ exp diagnostics
08:40:41 [exp] Generating diagnostics report...
08:40:41 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  expo: ~26.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/tiu-0ee7863c-207f-4971-a47e-e1b9d5a51a74.tar.gz
```

### Steps to Reproduce

1. Define a different image for `ios.splash.tabletImage` and `splash.image`
2. Build for iOS Simulator: `exp build:ios -t simulator --release-channel production`
3. Launch the app

### Expected Behavior

Upon launch on an iPad simulator:
* `ios.splash.tabletImage` shows for a bit
* the app shows

### Actual Behavior

Upon launch on an iPad simulator:
* `splash.image` shows for a bit
* `ios.splash.tabletImage` shows for a bit
* the app shows

(for iPhone, shows only `splash.image`, as expected)

Attached screencast showing the double-splash:
![video](https://user-images.githubusercontent.com/543751/38559806-fa86c668-3ca1-11e8-8f5e-9db393222b85.gif)

**Comment by ansonhoyt** [comment]
Also noticed iPhone Expo Client doesn't show `splash.image` if an empty `ios.splash` is defined. Perhaps `ios.splash` isn't merged with `splash`? I was assuming i could selectively override things.

**Comment by terribleben** [comment]
Thanks for the report, definitely looks like a regression on our end.

**Comment by tsapeta** [comment]
Closing this as it's pretty old issue and we no longer support SDK26 and ExpoKit.
