### ISSUE TITLE
[ SDK 44 ] Can't open app in expo go when update to sdk 44

### ISSUE THREAD

**Issue by qaws5503** [expo/expo#16293]
### Summary

I was using expo sdk 43 before, and always use `expo start` to create a local host and work on my android phone.

Now I want to use `eas update` in the future, so I've read this [article](https://blog.expo.dev/expo-sdk-44-4c4b8306584a) and followed the Managed workflow to upgrade to sdk44.
And then followed the docs [here](https://docs.expo.dev/eas-update/migrate-to-eas-update/) to install `expo-updates@0.11.2`.

And after I successfully upgrade to sdk44. When I type `expo start` and want to open on my phone, it says "Something went wrong, Could not load exp://192.168.2.52:19000".

And when I click the view error log, it says "Uncaught Error: java.lang.Exception: Incompatible SDK version".
I test it on a iOS simulator still can't open.

I've use `eas build -p android` to build an apk, and install it in my phone. Then everything works fine.
So does I miss any extra installation? or it really has a bug when upgrade from sdk43 to sdk44?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

expo diagnostics:
```
  Expo CLI 5.1.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2021.09.06.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.1.2
    Expo Workflow: managed
```

expo go:
```
android client version: 2.23.2
iOS client version: 2.23.2.101
```

### Reproducible demo

I create a new project by `expo init`. And it can run on my device.

So I think this can't be reproduce, because this is an issue about upgrading from sdk43 to sdk44.

**Comment by byCedric** [comment]
Hi @qaws5503! Sorry to hear you are running into this. Unfortunately, I can't reproduce this on a new project using `expo init`. There might be something going on in your project that causes this. And because of that, we would need a repro from you to investigate this behavior.

What I did:

```bash
# Create SDK 43 project
$ expo init ./test-app -t expo-template-blank@^43
$ cd test-app

# Start with Expo Go version for SDK 43
$ expo client:install:ios
$ expo start --ios

# Upgrade to SDK 44 and update Expo Go
$ expo upgrade 44
$ expo client:install:ios
$ expo start --ios
```

**Comment by qaws5503** [comment]
SOLVED: Thanks for @byCedric reply. I solve this problem by just `expo publish`, since the `eas update` now is still in preview stage.
I think the problem is my project's sdk was 43 before I published, which isn't the same on my local. So Expo Go complain about "Incompatible SDK version". So I just update it using `expo publish`.

**Comment by accompso-ltd** [comment]
I have this issue too but am not subscribed to expo so unable to run eas update. 

If I submit the app to expo to host it will hang on "new update available, downloading"? 

again it occurred when updating from 43 to 44.

**Comment by mcottingham** [comment]
> I was configuring `eas update` and ran into the same behaviour and error, i.e. `Uncaught Error: java.lang.Exception: Incompatible SDK version` and am unable to use Expo Go or the iOS simulator.`
> 
> I can resolve if I set `runtimeVersion` to `"policy": "sdkVersion"`. Any other value of `runtimeVersion` leads to the issue.

I can't upvote this answer enough!  I had done the same thing, I configured EAS build and update per the expo 44 documentation and it wrote a value into the `runtimeVersion` property in `app.json`.  I took me 2 days to figure this one out, and the resolution was just to remove the `runtimeVersion` property altogether.

**Comment by atif7865** [comment]
same issue here. SDK 46, did east configure and now I can't open the Expo Go on my phone or the simulator. So frustrating ..

**Comment by usmansbk** [comment]
Thanks... `runtimeVersion` was the issue here

**Comment by dcsan** [comment]
how do you configure this? I show in `app.json` 

```
"runtimeVersion": "1.0.0",
```

instead should it be 

```
"runtimeVersion": {
"policy": "sdkVersion"
}
```

**Comment by mcottingham** [comment]
@dcsan I encourage you to look at the eas documentation for runtime versions.
https://docs.expo.dev/eas-update/runtime-versions/

You'll see that when you set the runtimeVersion to `sdkVersion` that it will use the current expo SDK version as the runtime version.

> The "sdkVersion" policy will set the runtime version to the current SDK version of a project. For instance, if the project is on Expo SDK 1.0.0, the runtime version with this policy will be "exposdk:1.0.0". This runtime version will update any time we update the project's Expo SDK. So, if we ran expo upgrade and installed Expo SDK 2.0.0, then the runtime version would become "exposdk:2.0.0".
> This runtime version policy is perfect if you are not including custom native code in your project and the only native changes you make are when upgrading Expo SDKs.


Expo SDK 46 introduces a new runtime version policy called `appVersion` that is more suited for projects that have native code that changes between builds.

**Comment by dcsan** [comment]
thanks! to my surprise these two are interchangable and now we're happy buildin' again

```
"runtimeVersion": "1.0.0",

"runtimeVersion": {
    "policy": "sdkVersion"
}
```

**Comment by web-2017** [comment]
> I was configuring `eas update` and ran into the same behaviour and error, i.e. `Uncaught Error: java.lang.Exception: Incompatible SDK version` and am unable to use Expo Go or the iOS simulator.`
> 
> I can resolve if I set `runtimeVersion` to `"policy": "sdkVersion"`. Any other value of `runtimeVersion` leads to the issue.

yea, its work for me, just paste sdkVersion

**Comment by monkeyK1n9** [comment]
I had this same issue. Thanks to everyone, the community is amazing.

**Comment by michaek** [comment]
It appears this issue should not be closed. Per https://github.com/expo/expo/issues/16293#issuecomment-1111168392, the [runtimeVersion configuration options](https://docs.expo.dev/eas-update/runtime-versions/) for `eas update` are incompatible with Expo Go, and that should be considered a bug.

**Comment by kendallroth** [comment]
Can confirm that this is still an issue. After setting `runtimeVersion.policy` to `appVersion`, I can no longer open the app in Expo (even when testing). This is not mentioned anywhere in the docs, so I assume it is a bug?

> Incompatible SDK version or no SDK version specified. This version of Expo Go only supports the following SDKs (runtimes): 47.0.0, 46.0.0, 45.0.0. A development build must be used to load other runtimes.

After a bit more scraping around, I found a tiny reference to this in the EAS Build docs ([link](https://docs.expo.dev/build/updates/#previewing-updates-in-development-builds)), but _nothing_ about it in the EAS Update docs. This seems like an oversight, as this information is both difficult to find _and_ does not have a clear alternative workflow explained well. Quite likely due to the relative new nature of these projects, but still something that would be awesome to get updated/clarified!

**Comment by mwelwankuta** [comment]
I encountered the same issue and was able to fix it just setting the `runtimeVersion.policy` in the `app.json` to `sdkVersion`

**Comment by dabdu** [comment]
> thanks! to my surprise these two are interchangable and now we're happy buildin' again
> 
> ```
> "runtimeVersion": "1.0.0",
> 
> "runtimeVersion": {
>     "policy": "sdkVersion"
> }
> ```

Thank you, This works

**Comment by steviec** [comment]
Agreed with @kendallroth. This is incredibly confusing. I'd recommend:
- explicitly stating on the [runtime versions page](https://docs.expo.dev/eas-update/runtime-versions/) that using the `appVersion` flag will immediately prevent you from running Expo Go. The information is buried in [this page](https://docs.expo.dev/eas-update/runtime-versions/) that I didn't need to read at any step in setting up EAS Updates.
- adding a more helpful error message than "Incompatible SDK version or no SDK version specified" in Expo Go. Even just saying "Incompatible SDK version, no SDK version specified, or using runtime policy that is not 'sdkVersion'" would have immediately helped me know what was going on. 
- but even better: why couldn't Expo Go support this? The `appVersion` flag is super useful, and it's really a shame that Expo Go can't be used if I choose to use the falg. I suppose I'll switch back to using `sdkVersion`, but that's not nearly as useful to me, since expo dev client adds quite a bit more overhead to my dev process than Expo Go.

**Comment by steviec** [comment]
Here's a quick hack that allows you to use `appVersion` and Expo go.

In `package.json`:
```
"start": "USING_EXPO_GO=true expo start",
```

Hat tip to @zetter for the inspiration here: https://github.com/expo/expo/issues/18631#issuecomment-1256449111


In `app.config.ts`:
```
policy: process.env.USING_EXPO_GO ? 'sdkVersion' : 'appVersion',
```

**Comment by michaek** [comment]
@byCedric, you caused this issue to be closed a year ago by marking it as not reproducible. Since then, multiple reporters have provided information on how to reproduce the original issue. Can you please reopen this? Thanks!

**Comment by michaek** [comment]
Regardless of whether it is documented, as a user I can't accept that opting into a different release version compatibility strategy should break a development tool.

**Comment by vahidinline** [comment]
> "policy": "sdkVersion"

"policy": "sdkVersion" does not work on bare workflow, needs to be set manually

**Comment by vandercijr** [comment]
> > "policy": "sdkVersion"
> 
> "policy": "sdkVersion" does not work on bare workflow, needs to be set manually

Could you give more details about this please ?
