### ISSUE TITLE
[SDK44] EAS Execution failed for task ':expo-image-picker:compileReleaseKotlin

### ISSUE THREAD

**Issue by imhazige** [expo/expo#16291]
### Summary

Refer this same error.
https://github.com/expo/expo/issues/15629#issuecomment-998320584

I have try the workaround, it is not working.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

> Task :expo-image-picker:compileReleaseKotlin FAILED
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (25, 36): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (131, 39): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (133, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (138, 71): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (140, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (193, 7): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (195, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (200, 39): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (202, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (325, 8): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (327, 9): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (376, 8): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (378, 9): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (381, 46): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (383, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (4, 36): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (40, 9): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (42, 9): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt: (11, 36): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt: (32, 39): Unresolved reference: ifNull
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':expo-image-picker:compileReleaseKotlin'.
[stderr] > Compilation error. See log for more details
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 8m 12s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
419 actionable tasks: 419 executed
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

### Reproducible demo

> Task :expo-image-picker:compileReleaseKotlin FAILED
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (25, 36): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (131, 39): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (133, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (138, 71): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (140, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (193, 7): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (195, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (200, 39): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (202, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (325, 8): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (327, 9): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (376, 8): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (378, 9): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (381, 46): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (383, 7): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (4, 36): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (40, 9): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerOptions.kt: (42, 9): 'return' is not allowed here
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt: (11, 36): Unresolved reference: ifNull
[stderr] e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerUtils.kt: (32, 39): Unresolved reference: ifNull
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':expo-image-picker:compileReleaseKotlin'.
[stderr] > Compilation error. See log for more details
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 8m 12s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
419 actionable tasks: 419 executed
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

**Comment by imhazige** [comment]
I have tried change expo-image-picker to 11.0.1, does not work.

Have try patch,  it will throw other error.

Tried on both cloud build and local build, same behavior.

**Comment by imhazige** [comment]
We have paid for the expo service, so your solution is just close our issue while it stuck us days?

**Comment by brentvatne** [comment]
hi @imhazige! bug reports require reproducible examples whether you're a paid customer or not.

that said, i can tell from looking at your error logs that there seems to be an issue with the version of expo-modules-core installed. try checking if you have multiple versions of expo-modules-core installed - `yarn why expo-modules-core` or look in your package-lock.json if you use npm. you should only have one version of it and it should be installed as a dependency of the `expo` package

**Comment by brentvatne** [comment]
more info on support in our support terms: https://expo.dev/support-terms
you can also contact via the contact form so we can associate it with your expo account: https://expo.dev/contact

**Comment by imhazige** [comment]
Hey, @brentvatne 

Thank you so much, yes, it have many version of expo-modules-core.

info Has been hoisted to "expo-modules-core"
info Reasons this module exists
   - Hoisted from "@bugsnag#expo#expo-constants#expo-modules-core"
   - Hoisted from "@bugsnag#expo#@bugsnag#plugin-expo-app#expo-constants#expo-modules-core"
   - Hoisted from "@bugsnag#expo#@bugsnag#plugin-expo-device#expo-constants#expo-modules-core"
   - Hoisted from "@bugsnag#expo#@bugsnag#delivery-expo#expo-crypto#expo-modules-core"
   - Hoisted from "@bugsnag#expo#@bugsnag#plugin-expo-device#expo-device#expo-modules-core"
   - Hoisted from "@bugsnag#expo#@bugsnag#delivery-expo#expo-file-system#expo-modules-core"
info Disk size without dependencies: "1.57MB"
info Disk size with unique dependencies: "1.63MB"
info Disk size with transitive dependencies: "1.69MB"
info Number of shared dependencies: 4
=> Found "expo#expo-modules-core@0.6.3"
info This module exists because "expo" depends on it.
info Disk size without dependencies: "2.02MB"
info Disk size with unique dependencies: "2.08MB"
info Disk size with transitive dependencies: "2.14MB"
info Number of shared dependencies: 4



======
expo-constants@~12.1.3:
  version "12.1.3"
  resolved "https://registry.yarnpkg.com/expo-constants/-/expo-constants-12.1.3.tgz#bec48a42a7760b010450961c209bb4b1158b9cd6"
  integrity sha512-HXlMTPn9pnJdMju3WcwX4oEB7EOECOTzdIPaG3JEluygqzafwKLMR8BE82+64jgAxlGIWZsYl+3Ni9wuTFQeYw==
  dependencies:
    "@expo/config" "^5.0.9"
    expo-modules-core "~0.4.4"
    uuid "^3.3.2"
===========
expo-crypto@~10.0.3:
  version "10.0.3"
  resolved "https://registry.yarnpkg.com/expo-crypto/-/expo-crypto-10.0.3.tgz#b6516759617c9d22e230fad7f9673d480df802c8"
  integrity sha512-sTxJHMlRVqmMTKuz0EVbigFOpUUCCNQiCUZQJIJA+m7c5RwJqTahkDJBp+ZfWgRWCiSZo+01EsJNigF4/HQvPg==
  dependencies:
    expo-modules-core "~0.4.4"
============
expo-device@~4.0.3:
  version "4.0.3"
  resolved "https://registry.yarnpkg.com/expo-device/-/expo-device-4.0.3.tgz#da2229f1e5a38c795c9b8a023e65d520d327d4e5"
  integrity sha512-T04QT90wHYMt+YcyartCez1QF94KPV39LdWbcU00hE5V/tVgUT1Wv3g7p0T2suWeoWRPdgIT9LOlO+DXjIPqWA==
  dependencies:
    expo-modules-core "~0.4.4"
    ua-parser-js "^0.7.19"
==============

expo-file-system@~13.0.3:
  version "13.0.3"
  resolved "https://registry.yarnpkg.com/expo-file-system/-/expo-file-system-13.0.3.tgz#f8b3c47e0e7ecfd767043ed4c0aba6b207367678"
  integrity sha512-i65brB1Nd0upWigXMXrN4YSvj5cP77tB4hNCXoWYVaqRKpUnVlEku2FjQ/xVfIWLJMYrFHHC0Kgz/OKsNzQTpg==
  dependencies:
    "@expo/config-plugins" "^4.0.2"
    expo-modules-core "~0.4.4"
    uuid "^3.4.0"
==============

**Comment by brentvatne** [comment]
try updating your bugsnag library to the latest version

**Comment by imhazige** [comment]
Hey, @brentvatne 

It works now, thank you for same our time.

**Comment by heithemkacem** [comment]
any body still facing this issue in sdk51 , just downgrade the version if expo-image-picker to version 15 
-npx expo install expo-image-picker@15
