### ISSUE TITLE
Push Notification Implement with Amazon SNS Documentation not exists

### ISSUE THREAD

**Issue by berkaygurbuz** [expo/expo#16297]
I want to use Amazon SNS to push notification but there is nowhere to follow guide. There are a lot of people complaine about this issue in the stackoverflow, expo forums etc.

### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by byCedric** [comment]
https://dev.to/aws-builders/the-guide-to-implement-push-notifications-with-react-native-expo-and-aws-amplify-4imn
