### ISSUE TITLE
Unable to use selectPrinterAsync for the new Print API on iPad, works on iPhone

### ISSUE THREAD

**Issue by waltershub** [expo/expo#1630]
Trying to Select A printer on iOS using the new Print API 
~~~
  DangerZone.Print.selectPrinterAsync().then(printer => console.log(printer));
~~~

On the iPad nothing happens, on the iPhone it works as expected (the select printer dialog pops up and lets me select one and then prints out the object) the iPad Pro 12.9 inch and iPhone are running iOS 11 and running on the same wifi network. The printing in other apps works as expected from the iPad. 
I have tried it on the simulators with the same result.

(Update printing works the problem is only the select print api)

**Comment by brentvatne** [comment]
Related issue: https://github.com/christopherdro/react-native-print/issues/46

**Comment by terribleben** [comment]
Related fix: https://github.com/christopherdro/react-native-print/commit/e32ae60d846f6f725518dd0c9622aa69b1ede6ee

**Comment by waltershub** [comment]
@terribleben I still have the problem with the version 0.5.0 of react native print, I am using an Ipad pro 12.9 not sure if that makes a diif

**Comment by terribleben** [comment]
From the [Apple docs](https://developer.apple.com/documentation/uikit/uiprinter/1620442-printerwithurl), the printer url is just "the location of the printer on your network". So if you happen to know the address of your printer on your network, you can hard-code it. I don't think iOS exposes a clean method for scanning your network for devices, though apparently there are some [decently complex third-party libraries](https://stackoverflow.com/questions/17953119/how-scan-devices-in-a-lan-network) for it. But it seems like we should just get the printer dialogue to work cleanly and save everybody the trouble.

**Comment by waltershub** [comment]
@terribleben update I tried runinng the  RNPrintExample and this is what i got in the xcode log

~~~
 RNPrintExample[3876:3485037] TCP Conn 0x1c0173f80 Failed : error 0:61 [61]
~~~

I Then tried it running at as a iphone on the Ipad and then dialog did come up.  so it seems its not an issue with the ipad but something to do with full screen.

**Comment by waltershub** [comment]
@terribleben I am able to get the printing dialog working the my detached project if clicked select printer and then change the screen orientation(either way works)
[detach test repo](https://github.com/waltershub/detach-test-print)

![img_0004](https://user-images.githubusercontent.com/20269810/38748433-0cf70c64-3f1c-11e8-9136-3e82d2d864e4.jpeg)

**Comment by brownbl1** [comment]
Any update on this? Just getting caught up on the issues.

**Comment by thomasviaud** [comment]
It was fixed in SDK v28.0.0. Thanks! [Blog post](https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530)

**Comment by terribleben** [comment]
Indeed this was fixed in SDK 28.

**Comment by ceeesrt** [comment]
is there any example code for this? i'm trying to use this but i have no idea how :(
please HELP !
