### ISSUE TITLE
Built apk file is frozen on splash screen. 

### ISSUE THREAD

**Issue by YuryKorovko** [expo/expo#1631]
Hello! I have a problem with built apk file using expo. 
The built apk file works fine on Genymotion emulator - Nexus 5 (API 19) and doesn't work on the physical phone - Samsung J7 pro.
**https://github.com/YuryKorovko/swipeandshop link to the project.** 
Please, help me. 

P.S. I tried solutions described in the previous questions but they didn't help me

**Comment by schazers** [comment]
Hi Yury,
I'm moving this to our forums at forums.expo.io where we can help people like you with individual issues: https://forums.expo.io/t/apk-runs-on-genymotion-but-not-device/8833

(We'll open a github issue if it's part of a larger problem!)

If you can provide a bit of extra info requested there, someone may be able to help you more quickly, thanks!
