### ISSUE TITLE
[expo-notifications][android] No way to create push notification without "repeats"

### ISSUE THREAD

**Issue by ejkkan** [expo/expo#16319]
### Summary

In android when trying to create a push notification with "repeats" : false, or not appending it at all, the sdk throws:
`[Unhandled` promise rejection: Error: Failed to schedule the notification. Trigger of type: calendar is not supported on Android.]`

In my case, I would like to create a one time push notification on weekday 4 this current week.
Right now the android API only accepts recurring push notifications, unless using a "timeInterval", which can't be used for this use case.

Does the android OS not have any way of scheduling dates at all? Or is it the expo SDK lacking the functionality?

Best regards

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

^44.0

### Environment

local with emulator

### Reproducible demo

Example with weekly scheduling:

 // throws:  calendar is not supported on Android.
const weeklytTriggerInputBad = {
      channelId: 'default',
      hour: state.time.getHours(),
      minute: state.time.getMinutes(),
      weekday: day,
      repeats: false,
 };

 // works
const weeklytTriggerInputOk = {
      channelId: 'default',
      hour: state.time.getHours(),
      minute: state.time.getMinutes(),
      weekday: day,
      repeats: true
 };

**Comment by thespacemanatee** [comment]
+1 I'm having the exact same issue. Using bare workflow. This only works on iOS for me atm.
