### ISSUE TITLE
expo-local-authentication permissions for biometrics influence LocalAuthentication.hasHardwareAsync() and  LocalAuthentication.isEnrolledAsync();

### ISSUE THREAD

**Issue by AdrianBordeianu** [expo/expo#16317]
### Summary

When using expo-local-authentication, I want to achieve the functionality of redirecting to app settings if the app does not have permission to use Face ID.

So, a workflow would be:
1. when prompted with the permissions pop-up, press Don't Allow to use Face ID
2. use LocalAuthentication.hasHardwareAsync() and  LocalAuthentication.isEnrolledAsync(); and observe that both of them will return false;
3. => when the permission is denied, your app says that the device does not have hardware scanner / biometrics configured on the phone

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 5.1.2 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2, 30.0.3, 32.0.0
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.66.4 => 0.66.4 
    npmGlobalPackages:
      expo-cli: 5.1.2
    Expo Workflow: bare

### Reproducible demo
```

const hasHardware = await LocalAuthentication.hasHardwareAsync();
const hasEnrolledBiometric = await LocalAuthentication.isEnrolledAsync();
const authLevel = await LocalAuthentication.getEnrolledLevelAsync();

console.log(hasHardware, hasEnrolledBiometric, authLevel);
```

Consider the Face ID permission denied by the user, these methods will return false, false, 1.

hasHardwareAsyns & isEnrolledAsync present wrong information about the device, saying that it does not have biometric hardware and biometrics are not enrolled.

**Comment by sergiucheregi** [comment]
Having the same issue.
