### ISSUE TITLE
AR Camera position and rotation

### ISSUE THREAD

**Issue by andrewbest** [expo/expo#1633]
I am having an issue with the AR camera matrixWorld. Getting the x rotation seems to fail when the y rotation is near PI/2.

The important piece of code is this:
    // Get camera matrices
    this.position = new THREE.Vector3();
    var quaternion = new THREE.Quaternion();
    var scale = new THREE.Vector3();
    this.camera.matrixWorld.decompose( this.position, quaternion, scale );
    this.rotation = new THREE.Euler().setFromQuaternion( quaternion, 'XYZ' );

The project works in a Snack:
https://snack.expo.io/@blamsoft/ar-camera-matrices

1) Use the snack to display the rotation amounts when the screen is tapped.
2) Rotate the phone so that the y rotation is PI/2 or near 1.57.
3) Slightly tip the phone to change the x rotation away from zero. 
4) You will then see that the x rotation increases greatly (as opposed to what it is at other y rotations).

**Comment by schazers** [comment]
Hi Andrew! Thanks for the detailed report. We'll take a look :)

**Comment by andrewbest** [comment]
That is the only way I could find to get the camera rotation. The goal is to shoot some objects out in the direction that the phone is facing. It works most of the time but fails as described. If there is another way to get the camera rotation/direction I would use it.

**Comment by andrewbest** [comment]
I am trying out DangerZone.DeviceMotion rotation for this.

**Comment by andrewbest** [comment]
DeviceMotion could be used to do this. However, there is a problem with DeviceMotion.

See https://github.com/expo/expo/issues/1655.

**Comment by andrewbest** [comment]
It looks like there is a simpler solution. camera.getWorldDirection() seems to give more accurate results.

**Comment by andrewbest** [comment]
camera.getWorldDirection() can be used. Closing the case.
