### ISSUE TITLE
SwiftUI Preview no longer work after expo integration

### ISSUE THREAD

**Issue by tien** [expo/expo#16353]
### Summary

After integrating Expo to a bare project from running `npx install-expo-modules`, SwiftUI Preview no longer work.

Any preview update will result in the following crash: ``ExpoModulesCore/ExpoAppDelegate.swift:260: Fatal error: Expo modules provider must implement `ModulesProviderProtocol` ``

Ignoring the fatal error will result in a blank non-responsive preview

I've tried using a custom `AppDelegate` that doesn't implement `EXAppDelegateWrapper` when under preview mode by doing:

```objc
int main(int argc, char * argv[]) {
  @autoreleasepool {
    bool isPreview = [NSProcessInfo.processInfo.environment[@"XCODE_RUNNING_FOR_PREVIEWS"] isEqualToString:@"1"];
    NSString *appDelegate = isPreview ? NSStringFromClass([PreviewAppDelegate class]) : NSStringFromClass([AppDelegate class]);
    return UIApplicationMain(argc, argv, nil, appDelegate);
  }
}
```

But the same issue still persist

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.15 - /opt/homebrew/bin/yarn
      npm: 8.4.1 - /opt/homebrew/bin/npm
      Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/tien.nguyenkhac/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.2 => 0.67.2 
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: bare

### Reproducible demo

Repository with reproduction: https://github.com/tien/ExpoSwiftUIPreview

Contains 2 commits:
- before expo with working SwiftUI Preview
- after expo integration where SwiftUI Preview no longer work

**Comment by tien** [comment]
Any update on this? I can try to see if I can fix this myself if I'm given some guidance.

**Comment by samih7** [comment]
@tien Solved this on a React Native project by downgrading to Expo `43.0.4`

**Comment by Kudo** [comment]
hi @tien! thanks for your kind information. i just clone you example and it works for me. could you help to double check if i did something different?

```sh 
$ git clone https://github.com/tien/ExpoSwiftUIPreview.git
$ cd ExpoSwiftUIPreview/
$ expo run:ios
```

**Comment by tien** [comment]
@Kudo you need to open [SwiftUIView.swift](https://github.com/tien/ExpoSwiftUIPreview/blob/master/ios/SwiftUIView.swift) using XCode, there you can see the preview no longer work with Expo integrated.

**Comment by Kudo** [comment]
thanks @tien. i can repro the issue and having the possible solution in #16733
