### ISSUE TITLE
Unable to get unique device id without ejecting expo

### ISSUE THREAD

**Issue by code4muktesh** [expo/expo#16369]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by mariomurrent-softwaresolutions** [comment]
There was already an issue: https://github.com/expo/expo/issues/825

But you could write an adapter for that plugin you mentioned

**Comment by byCedric** [comment]
Thanks @mariomurrent-softwaresolutions! That's right, as [James mentioned](https://github.com/expo/expo/issues/825#issuecomment-403101698):

> If you wish to take on this risk, you can detach and add the module yourself. The platform inconsistencies, app review risk, and privacy concerns are some of the reasons why we don't provide this tracking capability. Additionally, the maintenance cost of adding an external module adds up so we are judicious in what we choose. Overall, we are working to move Expo to more of a self-service model where the ExpoKit (i.e. detached) workflow is smoother and you build the app on your own machine with full control without being blocked on Expo for adding new modules, app builder queues, and other places where Expo can be a bottleneck today.

You can always use dev clients together with EAS to keep a similar experience like Expo Go, but with the flexibility of bare (and thus being able to install react-native-device-info).

**Comment by nrooban** [comment]
No need to eject. To get the device UniqueId in expo project

1. `npm install react-native-device-info`
2. `expo run:ios` or `expo run:android`

Please note: `expo start` will throw an error

**Comment by erdincakdogan** [comment]
> No need to eject. To get the device UniqueId in expo project
> 
> 1. `npm install react-native-device-info`
> 2. `expo run:ios` or `expo run:android`
> 
> Please note: `expo start` will throw an error

this is not working anymore. You can create uuid for devices and after that you can use it
