### ISSUE TITLE
Expo dev client using expo start

### ISSUE THREAD

**Issue by yesIamFaded** [expo/expo#16360]
### Summary

Basically my question is if it is possible to use Expo Dev Clients with `expo start`.

Please refer to this: https://github.com/henninghall/react-native-date-picker/issues/458

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

"expo-dev-client": "~0.7.2",
"expo": "^42.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",

But also not working with SDK 44.0 and "expo-dev-client": "~0.8.4",

### Environment

  Expo CLI 5.1.2 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      npm: 7.20.5 - C:\Dev\npm\npm\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

Creating a new app and just using this DateTimePicker (https://github.com/henninghall/react-native-date-picker) with **`expo start`** gives the error: 

```
                    <DatePicker 
                        date={this.state.activityDate}
                        modal
                        title="Bitte Datum wählen"
                        locale="de"
                        mode="date"
                        open={this.state.showPicker}
                        onDateChange={(date) =>  {
                            console.log(date)
                            this.setState({
                                activityDate: date
                            })
                        }}
                        onCancel={() => {
                            this.setState({
                                showPicker: false
                            })
                        }}
                        onConfirm={() => {
                            this.setState({
                                showPicker: false
                            })
                        }}
                    />
```

### Stacktrace (if a crash is involved)

TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePicker.openPicker')

This error is located at:
    in DatePickerAndroid (created by DatePickerWrapper)
    in DatePickerWrapper (created by Main)
    in RCTView (created by View)
    in View (created by Main)
    in RCTView (created by View)
    in View (created by Main)
    in Main (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:172:19 in handleException
at node_modules\react-native\Libraries\Core\ReactFiberErrorDialog.js:43:2 in showErrorDialog
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15792:34 in logCapturedError
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15884:20 in update.callback
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7199:2 in callCallback
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7220:20 in commitUpdateQueue
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:16632:25 in commitLifeCycles
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19216:22 in commitLayoutEffects
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:93:4 in invokeGuardedCallbackProd
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:318:2 in invokeGuardedCallback
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18952:29 in commitRootImpl
at node_modules\scheduler\cjs\scheduler.development.js:468:23 in unstable_runWithPriority
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18791:17 in commitRoot
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18192:12 in performSyncWorkOnRoot
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5911:33 in runWithPriority$argument_1
at node_modules\scheduler\cjs\scheduler.development.js:468:23 in unstable_runWithPriority
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5906:23 in flushSyncCallbackQueueImpl
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5893:28 in flushSyncCallbackQueue
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18211:28 in batchedUpdates$1
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2534:29 in batchedUpdates
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2680:16 in _receiveRootNodeIDEvent
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2800:27 in receiveTouches
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:414:4 in __callFunction
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:113:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:365:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:112:4 in callFunctionReturnFlushedQueue

**Comment by byCedric** [comment]
Hi @yeslamFaded! Expo start can be used, but you'd have to use `expo start --dev-client`. That starts the bundler in the right way to run on dev clients. It's similar to `expo run:`, but without building the app. 

Keep in mind that you can't use Expo Go to preview the app, you have to use the dev client. This library adds native code to your app, which isn't available in Expo Go.

Hope this helps!

**Comment by yesIamFaded** [comment]
Okay it actually works, thank you! 

My Question now is, if I start my app with `expo start --dev-client` how can I test it on IOS? Is this even possible on Windows? When I scan the QR Code with an IPhone it says it cant find anything.  When I access the app over the expo go app it crashes with my error - obviously.

**Comment by AhmedAlatawi** [comment]
For me, I had to go thru these steps before i could run `expo start --dev-client` successfully (for Android):

1. Set up an `EAS` account
2. Run `npm install -g eas-cli`
3. In the project root dir, run `eas build:configure`
4. Run `eas build --profile development --platform android`
5. Wait for the build to be generated
6. Click on the generated build link and download the build locally
7. Drag and drop it into my Android simulator
8. Finally, run `expo start --dev-client`, and then press the "a" key to open the app on the simulator

**Comment by LucasLFurini** [comment]
Currently I'm experiencing a weird error when I try to use dev-client on my device (iphone), I was able to install the dev-client and run the server, but when I scan the generated QR code, it stays in the splash screen for a few seconds and then throws me an error:
"No bundle URL present
Make sure you're running a packager server or have included a .jsbundle file in your application bundle"

I'm running the command expo start --dev-client and I have my mac and Iphone connected to the same internet connection

When I try to open in my Ios simulator, it works fine, anyone has any clues of what can be causing it?

**Comment by kdawgwilk** [comment]
@LucasLFurini I am also experience that exact same issue. 
- Produced a development client using eas
- Installed the build on my physical device
- Run expo start --dev-client
- No bundle url present error
Items I checked

- Made sure I am on the same wifi
- Tried plugging device in through USB
- Force quitting the app and relaunching using the QR code

**Comment by davidcort** [comment]
I have the same issue with Expo SDK 48. With Expo SDK 47 was fine. 
The error: "Safari no can connect with the sever".

**Comment by davidcort** [comment]
Ok, i resolved it !!

First, update the cli global on your machine / Mac / Windows, anyway. 
On my Mac: expo start --dev-client

Second: Add the correct scheme in your Info.plist:

`<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.app.xx</string> // Your Bundle Identifier !!
				<string>app-1-xxxxx-xxxxxxx-xxxxxx</string> // From firebase for phone authentication. This not matters.
			</array>
		</dict>
	</array>`

Third: Use **expo start --dev-client**, instead npx expo start --dev-client.

And works!! 

At least for me ...  xD
