### ISSUE TITLE
Android push notifications -`googleServicesFile` relative path might be breaking stuff

### ISSUE THREAD

**Issue by danibjor** [expo/expo#1636]
As discussed in the issue #1330 - there are issues with the push notifications.

Tried the "solution" provided after my last comment, and in the meantime the issue was closed.

Anyhow,

Doin as the guide suggests works fine, android stand alone now gets push notifications (expo app not so much, so still and issue with development) https://docs.expo.io/versions/latest/guides/using-fcm

Now, when you try to build the project from Expo XDE, we now get a new error 

```
11:03:49 Building JavaScript bundle: finished in 9442ms.
11:03:58 Failed to publish package: ENOENT: no such file or directory, open './google-services.json'
```
The file `google-services.json` is in the root directory of the project (side by side with `app.json`).

CLI tools was installed today. XDE updated to latest version a few days ago (yesterday?)

**Comment by schazers** [comment]
Hi there, thanks for the report. We'll look into the issue of it working on standalone apps but not in the expo client. 

I'm not sure what's going on with your other issue about google-services, but we should file it as a separate github issue. Would you be able to provide a link to the repo for that second part?

**Comment by PrestonStahley** [comment]
I have the same issue.

I followed the [FCM guide](https://docs.expo.io/versions/latest/guides/using-fcm) to get push notifications working in Android standalone app, but I now get the above error when publishing in XDE.

![screenshot_041318_071307_pm](https://user-images.githubusercontent.com/1296828/38826746-efdfbc3a-416d-11e8-8da5-4d777f4278ec.jpg)

https://forums.expo.io/t/android-push-notifications-received-in-expo-client-but-not-in-standalone/8879

**Comment by danibjor** [comment]
HI @schazers, as @PrestonStahley this is when you hit publish from Expo XDE. 

Running `exp build:android` from the terminal (Mac) works like a charm, but not the Publish button in Expo XDE.

This worked before i updated the project as per the FCM guide. 

![image](https://user-images.githubusercontent.com/2149381/38864489-2acef036-423b-11e8-99da-3f2f3d4e1665.png)

**Comment by danibjor** [comment]
Seems like using the full path instead of relative works from Expo IDE. Not good for source control tough - but for a single developer, sorta OK.

`app.json:`
```Javascript
"android": {
            "googleServicesFile": "/Users/daniel/projects/<customer>/<project>/google-services.json",
            "icon": "./icon-android.png",
```

![image](https://user-images.githubusercontent.com/2149381/38864863-4ffca370-423c-11e8-82bd-abdd79c3242c.png)

**Comment by PrestonStahley** [comment]
I worked around the issue by dropping a copy of my google-services.json file into the Expo XDE directory. Seems like a bug in the `googleServicesFile` path parsing that will hopefully be fixed.

**Comment by muniperez** [comment]
@danibjor solution worked for me. My Tunnel wouldn't work when I had google-services.json in my app.json, but writing the complete path seems to have fixed the problem.

**Comment by esamelson** [comment]
Hi all -- sorry for the delay here. We've landed a fix for this bug and it will ship with a new version of XDE soon. In the meantime, you'll need to use one of the workarounds provided here (use an absolute rather than relative path, drop the `google-services.json` file into the XDE working directory, or just use `exp` instead). Really sorry for the inconvenience!
