### ISSUE TITLE
Expo-Facebook not redirecting to application

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo#16368]
### Summary

We are using expo-facebook for user authentication. 
On IOS devices we have noticed some issues. When user have facebook application installed and 
trying to login into our application, modal is open which is asking user to login with facebook application. After hitting button Continue user is redirected to modal which says again, Login with app.

So user is in some kind of a loop. 

Reproducable with following criteria:
1) Ios Device
2) Facebook application installed
3) Logged out from Safari facebook web app.
4) Correct config and implementation of facebook flow.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

  System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

```
import React from "react";
import Constants from "expo-constants";
import * as Facebook from 'expo-facebook';
import { Text, View, StyleSheet, Image } from "react-native";
import { TouchableOpacity } from "react-native-gesture-handler";

const appName = Constants.manifest?.extra?.appName;
const facebookId = Constants.manifest?.extra?.facebookAppId;

interface Props {
  show: boolean;
}

export const FacebookLoginProvider = React.memo(({show}: Props) => {


  async function signInWitFacebookAsync() {
    try {
      await Facebook.initializeAsync({appId: facebookId, appName: appName});
      let response: any = await Facebook.logInWithReadPermissionsAsync({permissions: ['public_profile', 'email']});
      if (response.type !== "success") return;
    } catch (e) {
    } 
  }

  if (!show) return <View style={{height: 70, width: '100%'}}/>;

  return (
    <TouchableOpacity onPress={signInWitFacebookAsync}>
      <Text>Login with facebook</Text>
    </TouchableOpacity>
  )
});
```

**Comment by jurica-penjgusic** [comment]
Closing this issue.
To fix this we have omitted "facebookId" property in app.json file.
It seems on IOS when property is omitted, login flow is using web authentication and there is no bug.
Android flow is untouched.

Br

**Comment by BrodaNoel** [comment]
Fixed on SDK 46, if you migrate from `expo-facebook` to the new `react-native-fbsdk-next` library
