### ISSUE TITLE
expo-camera doesn't launch onBarCodeScanned when using internal distribution

### ISSUE THREAD

**Issue by yonitou** [expo/expo#16374]
### Summary

Hi

I just started to use internal distribution on my managed workflow for iOS and Android. 

I'm using the Camera component from `expo-camera` package to use the `onBarCodeScanned` prop. 

Everything works perfectly fine on Expo Go and on production. 

**But** : Now that I ran my internal distribution build (which means apk and ipa files) => this function is never called anymore. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

```
 expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /Users/yonitouboul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.1.3
    Expo Workflow: managed

```

### Reproducible demo

1. Install `expo-camera` package
2. Add this boilerplate on a screen : 
 ```
	<Camera
	onBarCodeScanned={() => console.log("hello")}
	style={[StyleSheet.absoluteFill]}
/>
```
3. Run the app with internal distribution 
4. Nothing will happen

**Comment by Engazan** [comment]
same issue working only in Expo go

https://github.com/expo/expo/issues/16503

**Comment by VNDRN** [comment]
I've noticed the same issue in our app. The solution I've found is to install the expo-barcode-scanner package. You don't have to use it, just have it installed in your project.
