### ISSUE TITLE
Get Calendars on Android just hangs upon subsequent calls. No Response. No Error.

### ISSUE THREAD

**Issue by kishanio** [expo/expo#1637]
### Environment

  OS: macOS Sierra 10.12.6
  Node: 6.11.5
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

App Target : Android

### Steps to Reproduce

1. Android Live Device. Grant Calendar Permission. Granted.
2. Fetch Calendars using Expo.Calendar.getCalendarsAsync(). Returns array. 
3. Send App to background or kill and return to app. Check if permission is granted and try to fetch calendars again. There's no response or error. 

### Expected Behavior

Return Array of Calendars. 

### Actual Behaviour

No Response.

**Comment by schazers** [comment]
Hi! Thanks for the detailed report. We'll have a look.

**Comment by esamelson** [comment]
Hi @kishanio - really sorry for the long delay here. I've tried to reproduce this behavior as you described, and I am unable to. Could you tell us which Android device/OS you saw this on? And is there any chance you might be able to provide a [snack](https://snack.expo.io/) that reproduces this?

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
