### ISSUE TITLE
[expo-media-library] createAssetAsync() on iOS throws: This file type is not supported yet

### ISSUE THREAD

**Issue by timoisalive** [expo/expo#16383]
### Summary

I'm trying to add an image captured with `react-native-view-shot` into photos. Android performs as expected, but iOS throws `This file type is not supported yet` error. The required file type extension seems to be in place, the `uri` is something like this:

`/Users/***/Library/Developer/CoreSimulator/Devices/1C98873B-B902-40D7-BFBE-47810F8662E3/data/Containers/Data/Application/15D1F710-C902-40DC-B910-731BA20971F2/tmp/ABI44_0_0ReactNative/30EF0F17-BB12-4D8B-AFD5-DB74845C9696.jpg`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.2
        System Images: android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom_64, android-31 | ARM 64 v8a, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8005941
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: managed

### Reproducible demo

```
// App.tsx

import { createAssetAsync, usePermissions } from "expo-media-library";
import { useRef } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { captureRef } from "react-native-view-shot";

export default function App() {
  const viewRef = useRef();

  const [_, requestPermission] = usePermissions();

  const captureImage = async (ref) => {
    try {
      const permission = await requestPermission();

      if (permission.granted) {
        const uri = await captureRef(ref.current, { format: "jpg" });

        const asset = await createAssetAsync(uri);

        if (asset) {
          console.log("Success:", asset);
        }
      }
    } catch (error) {
      console.log("Fail:", error);
    }
  };

  return (
    <View ref={viewRef} style={styles.container}>
      <Pressable
        style={{ width: 100, height: 100, backgroundColor: "green" }}
        onPress={() => captureImage(viewRef)}
      />
      <Text>Open up App.tsx to start working on your app!</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

**Comment by byCedric** [comment]
Hi @timoisalive! I've tested your example, but that seems to work fine on both my Android 11 (OnePlus 6) as well as on my iOS 15.1.1 (iPhone 13 Pro). It might be that the simulator is missing some apps to fully support view shot, but I'm not sure what that would be. There isn't a lot we can do from our end, you might be able to get more help on the view shot repo.

Hope this helps!

**Comment by timoisalive** [comment]
Hi @byCedric, thanks for your message! It does appear to work on my iPhone indeed, I guess I only tried on the simulator then.

However, I find the error strange, as the `react-native-view-shot` library seems to work as expected. The captured image shows fine (also on simulator) if I place it in an `Image` component! How come the `expo-media-library` throws such an error?

**Comment by timoisalive** [comment]
@byCedric Just bumped into this same topic with another app I work with, this time NOT using the `react-native-view-shot` but `expo-image-picker`. I get the same error when trying to use the `uri` I get from `ImagePicker.launchImageLibraryAsync()`.

**Comment by murat0** [comment]
We are experiencing the very same error, the URI just fails to work with expo-media-library, on iOS. However one of our developers reported that he isn't experiencing the same on his simulator with the exact same codebase. Thus I am thinking it might be an environment related issue.

**Comment by briantanabe** [comment]
I'm running into this issue using saveToLibraryAsync as well

```
Saving: /Users/tanabs/Library/Developer/CoreSimulator/Devices/794A056F-3D24-4873-9B59-A355011F0718/data/Containers/Data/Application/2C80DA2A-14BC-4D4B-85C2-9F617FA3023A/tmp/ABI44_0_0ReactNative/CB9A68D4-87A0-44BB-819D-FA9EC0DBF7BA.jpg

This file type is not supported yet.
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:27:27 in moduleName.methodInfo.name
at node_modules/expo-media-library/build/MediaLibrary.js:184:7 in addAssetsToAlbumAsync
at node_modules/expo-media-library/build/MediaLibrary.js:164:7 in saveToLibraryAsync
```

**Comment by whyaftab** [comment]
Same issue

**Comment by professorkolik** [comment]
Same here, stopped working

**Comment by jsheffers** [comment]
Same here.  SDK 46

**Comment by foolem** [comment]
Same here, SDK 46
