### ISSUE TITLE
Expo dev client does not work with eas build inside of a monorepo

### ISSUE THREAD

**Issue by shanedaugherty** [expo/expo#16382]
### Summary

The expected behavior is that `eas build` for `expo-dev-client` works for apps inside of a monorepo. This is a blocker because in order to use the `dev-client` we need to first do an `eas build`. 

Right now the iOS builds fail due to a conflict when installing the pods:
```Analyzing dependencies
[!] There are multiple dependencies with different sources for `expo-dev-launcher` in `Podfile`:
- expo-dev-launcher (from `../node_modules/expo-dev-launcher`)
- expo-dev-launcher (from `../../../node_modules/expo-dev-launcher`)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.3.9 => 0.3.9 
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.1.3
    Expo Workflow: managed

### Reproducible demo

- `npx lerna init`
- add this to root package.json `"workspaces": ["packages/app"]`
- `cd packages && expo init app (select blank typescript)`
- delete `package.lock.json` and `node_modules` in root and run `npm install` again
- `cd packages/app && expo install expo-dev-client`
- follow instructions to setup dev client https://docs.expo.dev/clients/introduction
- make mono repo changes to `metro.config.js` and add `index.js` as described here https://docs.expo.dev/guides/monorepos/

Now that everything is set up, run `eas build --profile development --platform all`.

If all goes well, your iOS build will fail when installing pods with the following error:
```
Analyzing dependencies
[!] There are multiple dependencies with different sources for `expo-dev-launcher` in `Podfile`:
- expo-dev-launcher (from `../node_modules/expo-dev-launcher`)
```

**Comment by byCedric** [comment]
Hi @shanedaugherty! Can you provide a repository with the exact state of the code? To me, it seems like this could be a hardcoded path in your podfile that shouldn't be there (related to importing the dev client).
