### ISSUE TITLE
expo-ads-admob package crashes build at runtime 

### ISSUE THREAD

**Issue by deepnothing** [expo/expo#16381]
### Summary

I am trying to integrate googles Admob service into my expo initialized react native app via the expo-ads-admob package. the package works successfully in the expo-go development environment, however when I build the app and via eas build --profile development --platform ios and install it onto my phone, it immediately closes as soon as I open it. I have already removed all imports of the Admob components within the app so it seems like just installing the package itself causes the app to crash at runtime. Since the app builds successfully, there are no error messages I can use to start debugging, any help would be greatly appreciated. This is the configuration in my app.json if that's relevant
```
{
  "expo": {
    "name": "MyApp",
    "slug": "MyApp",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#FFF"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-TESTID"
      },
      "bundleIdentifier": "com.package.identifier"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFF"
      },
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-TESTID"
      },
      "package": "com.package.identifier"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

```
expo-dev-client: 0.8.4,
expo-ads-admob:12.0.1

```

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files (x86)\nodejs\npm.CMD
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

expo init new app
expo install expo-dev-client
expo install expo-ads-admob
eas build --profile development --platform ios
expo start --dev-client

### Stacktrace (if a crash is involved)

no errors during testing in Expo-go only after successful build and install

**Comment by MahitMehta** [comment]
Same, I have been struggling with this for a couple hours. lmk if you find a fix.

**Comment by deepnothing** [comment]
after days of searching... try adding this to your app.json under "ios" ```
"buildNumber": "your-build-number",
"infoPlist": {
        "GADIsAdManagerApp": true
      }
```

**Comment by EvanBacon** [comment]
I've added this to our internal issue tracker, thanks for reporting.

**Comment by MahitMehta** [comment]
After struggling for a whole day to get expo version of admob library to work I decided to just switch over to another react library. I’m currently using react-native-firebase/admob

**Comment by giautm** [comment]
> After struggling for a whole day to get expo version of admob library to work I decided to just switch over to another react library. I’m currently using @react-native-firebase/admob and it works brilliantly!

Hi @MahitMehta, look like the package `@react-native-firebase/admob` was dropped by its owner. So, It don't get update anymore and also does not exist in [their repository](https://github.com/invertase/react-native-firebase/tree/main/packages).
