### ISSUE TITLE
expo gl sample not rendering

### ISSUE THREAD

**Issue by wiulma** [expo/expo#16390]
### Summary

I'm tring to setup a brand new expo-gl sample app.
I started from scratch with a new bare react native app.
I added expo sdk 44 and expo-gl module (and the others needed modules), but the app didn't work.
At some point I read this [issue](https://github.com/expo/expo/issues/15811), and I downgraded expo sdk version to 43
But it still doens't work.

Test device: Poco X3 Pro

do you have any suggestions?
thanks! :-)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      npm: 7.24.0 - /opt/homebrew/bin/npm
      Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 31.0.0, 32.0.0
        System Images: android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
        Android NDK: 23.1.7779620
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=43.0.0-0 <44.0.0 => 43.0.5 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.65.1 => 0.65.2 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

[broken sample](https://snack.expo.dev/@wiulma/71595c)

**Comment by SerSerch** [comment]
I also had a problem when changing branches with different versions (44 and 43 versions). I cleared the cache, then reinstalled modules several times, cleared the application storage on the device. At some point, everything returned to normal on version 43. I don't know exactly what the problem was.

**Comment by SerSerch** [comment]
https://docs.expo.dev/troubleshooting/clear-cache-windows/

**Comment by wiulma** [comment]
> https://docs.expo.dev/troubleshooting/clear-cache-windows/

ok, thanks for the tips
I usually clean metro cache when restart it, and often I run a "reinstall" command, that cleans all mentioned caches (maybe not the npm one), delete node_modules and pods  and then install all dependency. I also clean derived data quite often. So...I'm quite sure it's not a cache releted issue, but I'll try again to clean all the caches.
