### ISSUE TITLE
Camera indicator light remains on even when Camera is unmounted

### ISSUE THREAD

**Issue by dlee** [expo/expo#16404]
### Summary

When `<Camera>` is mounted and then unmounted, the camera indicator (small green dot on iOS) remains on.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /var/folders/mx/x89f7k_11mg1cp27tzlcjfw00000gp/T/yarn--1645518732919-0.7175452398183182/node
      Yarn: 1.22.5 - /var/folders/mx/x89f7k_11mg1cp27tzlcjfw00000gp/T/yarn--1645518732919-0.7175452398183182/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.02.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 24, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 30.0.2, 30.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
    IDEs:      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: ^0.67.2 => 0.67.2 
      react-native-web: ~0.17.5 => 0.17.6 
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/bNsd4hjv9

**Comment by byCedric** [comment]
Hi @dlee! I can reproduce the behavior, although I have a feeling it's because React( Native) is trying to reuse the Camera component for the view. We probably need to do some more debugging to find out if the camera component is fully unmounted, and if the camera is fully shut down when doing so.

I modified your example a bit, [in this version](https://snack.expo.dev/@bycedric/expo-issue-16404) I've added a `key=` property to force-unmount the Camera component if it is toggled off. It might be an easy workaround for you.

Hope it helps!

**Comment by emrahc** [comment]
I use 
expo sdk 44
"expo-camera": "~12.1.2",
unfortunately key work around didn't work for me

**Comment by raazatul7** [comment]
Still facing this issue, any update? 
I'm using expo barcode scanner!

**Comment by aaonduollar** [comment]
This remains an issue, at least on my end.

**Comment by eprice122** [comment]
Seeing this issue as well

**Comment by ScreamZ** [comment]
Experiencing the same issue randomly, also with expo-video that remains playing in the background where it should be unmounted.

I'm trying to investigate a bug isolation, it's pretty hard

**Comment by epolat-github** [comment]
Still an issue. I unmount the view but camera indicator stays visible until I close the application. Also phone keeps heating, means that camera component is actually open in the background or smt

**Comment by dorthwein** [comment]
Still an issue however a work around for me was to wrap the component in a conditional mount based on useState and umounting the camera component explicitly during clean up. 

My bet is react-navigation or react is caching the component or not quite removing it right away during dismount.

```
export const PhotoComponent = () => {
  const camera = useRef();
  
  /* https://github.com/expo/expo/issues/16404 */
  const [mountedKey, setMountedKey] = useState(false);
  useEffect(() => {
    setMountedKey(dayjs().toISOString());
    
    return () => {
      setMountedKey(false);
    };
  }, []);

  return (
    <SafeAreaView>
      {mountedKey ? (
        <Camera ref={camera} key={mountedKey} />
      ) : (
        <View />
      )}

    </SafeAreaView>
  );
};


```

**Comment by epolat-github** [comment]
> Still an issue however a work around for me was to wrap the component in a conditional mount based on useState and umounting the camera component explicitly during clean up.
> 
> My bet is react-navigation or react is caching the component or not quite removing it right away during dismount.
> 
> ```
> export const PhotoComponent = () => {
>   const camera = useRef();
>   
>   /* https://github.com/expo/expo/issues/16404 */
>   const [mountedKey, setMountedKey] = useState(false);
>   useEffect(() => {
>     setMountedKey(dayjs().toISOString());
>     
>     return () => {
>       setMountedKey(false);
>     };
>   }, []);
> 
>   return (
>     <SafeAreaView>
>       {mountedKey ? (
>         <Camera ref={camera} key={mountedKey} />
>       ) : (
>         <View />
>       )}
> 
>     </SafeAreaView>
>   );
> };
> ```

This one didn't work for me unfortunately. Why is this issue still closed? It's been a year but we are still experiencing

**Comment by TowhidKashem** [comment]
> > Still an issue however a work around for me was to wrap the component in a conditional mount based on useState and umounting the camera component explicitly during clean up.
> > My bet is react-navigation or react is caching the component or not quite removing it right away during dismount.
> > ```
> > export const PhotoComponent = () => {
> >   const camera = useRef();
> >   
> >   /* https://github.com/expo/expo/issues/16404 */
> >   const [mountedKey, setMountedKey] = useState(false);
> >   useEffect(() => {
> >     setMountedKey(dayjs().toISOString());
> >     
> >     return () => {
> >       setMountedKey(false);
> >     };
> >   }, []);
> > 
> >   return (
> >     <SafeAreaView>
> >       {mountedKey ? (
> >         <Camera ref={camera} key={mountedKey} />
> >       ) : (
> >         <View />
> >       )}
> > 
> >     </SafeAreaView>
> >   );
> > };
> > ```
> 
> This one didn't work for me unfortunately. Why is this issue still closed? It's been a year but we are still experiencing

If you're using React Navigation you need to use the useFocusEffect callback, useEffect will only run once with an empty `[]` dependency array...

```
  useFocusEffect(
    useCallback(() => {
      setMountCamera(true);

      return () => {
        setMountCamera(false);
      };
    }, [])
  );

  {mountCamera && <Camera {...} />
```

This worked for me.

**Comment by Rhysjc** [comment]
Still an issue, none of the above work.

**Comment by barimehdi77** [comment]
I tried all above work arounds and still none of them worked for me

**Comment by yezzer** [comment]
@TowhidKashem's fix works on Expo Go iOS, but not on Chrome MacOS. Not tried other platforms yet.

**Comment by anhquan291** [comment]
Facing the same issue! None of the solutions work! Any help guys? Thanks

**Comment by anhquan291** [comment]
Hi @raazatul7 , Have you found a solution yet? I also tried `Vision-Camera` but facing the same issue. iOS version 16.4. Thanks

**Comment by raazatul7** [comment]
> 
```

useFocusEffect(
    useCallback(() => {
      setMountCamera(true);

      return () => {
        setMountCamera(false);
      };
    }, [])
  );

  {mountCamera && <Camera {...} />
```

I used this solution on iOS 15 I guess, not sure about 16.4

**Comment by abdirahmn1** [comment]
Having the same issue on IOS 15.7, have tried all kinds of workarounds but the problem still exists!, hope it gets fixed soon :(

**Comment by pfndesign** [comment]
I fixed this issue by mounting the camera when the screen is focused AND camera permission is granted
