### ISSUE TITLE
Audio finish causes Speech to fade to silent on iOS

### ISSUE THREAD

**Issue by duckbrain** [expo/expo#1641]
### Environment

```bash
$ exp diagnostics10:52:45 [exp] Generating diagnostics report...
10:52:45 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: Linux 4.14
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/ec2-software-f05b33f3-5268-45f5-84a9-918002a518b2.tar.gz
```

Target: iOS

### Steps to Reproduce

1. Use the `Expo.Speech.speak` function to say a message with TTS
2. While the sound is still playing, create a `Expo.Audio` that plays a shorter sound that completes before the speech.

### Expected Behavior

I expected the speech to continue unless I call `Expo.Speech.stop()` or it completes.

### Actual Behavior

Speech fades to silence after the sound completes on iOS. This same behavior could also be observed in Expo SDK 25 using the [work-around for #1409](https://github.com/expo/expo/issues/1490#issuecomment-371341347). I do not observe this behavior on Android, the speech plays through to the end.

### Reproducible Demo

1. Open the snack: https://snack.expo.io/@ec2-software/sound-and-speech-sample
2. Press the "Say Something button"
3. Press the "Play a sound" button while speech is occuring

**Comment by schazers** [comment]
Thanks for the detailed report! Sounds like it could be an issue with the iOS Audio Session Category.

**Comment by sjchmiela** [comment]
Yup, unfortunately `EXAV` doesn't check whether `EXSpeech` is… speaking when it demotes the audio session after an item finishes to play (neither does the `EXAudioSessionManager` track both `EXAV` and `EXSpeech` not to switch session off while any of the modules are busy).

Good catch, @duckbrain!

**Comment by cruzach** [comment]
Updated snack for SDK 36 - https://snack.expo.io/@charliecruzan/sound-and-speech-sample

**Comment by duckbrain** [comment]
Just tested the snack (updated to Expo 43.0.0) on an iOS device. It now seems to work most of the time, but a few times while mashing the "Play a Sound!" button, it did fade out. There may be a race.

This is basically fixed, but I'll leave it to the maintainers if they'd like to close the issue, as this is likely a new bug.
