### ISSUE TITLE
how to restart app in dev client

### ISSUE THREAD

**Issue by marchingband** [expo/expo#16410]
### Summary

I call Updates.reloadAsync() but it fails because `You cannot use the Updates module in development mode in a production app.`

How can I restart my app in dev mode?
Thanks!

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-updates": "~0.10.15",
"expo-dev-client": "~0.6.3",

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.5.1 => 8.5.1 
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

const errorHandler = e => {
  firebase.database().ref('/errors/').push(e)
  Alert.alert(
    "ALERT", 
    "Sorry there was an error, click to restart the app",
    [
      {
        text:'OK',
        onPress:()=>Updates.reloadAsync()
      }
    ],
    {cancelable: false}
  )
}

**Comment by esamelson** [comment]
Hi @marchingband -- you can reload your app in development by opening the dev menu (shake device, or three-finger long press if you have that enabled) while your app is running and pressing "Reload" from that screen.
