### ISSUE TITLE
[expo-apple-authentication] undefined is not an object (evaluating 'appleCredential.identityToken')

### ISSUE THREAD

**Issue by JackkFi5h** [expo/expo#16415]
### Summary

I followed all the steps on this thread diligently https://medium.com/nerd-for-tech/apple-google-authentication-in-expo-apps-using-firebase-997125440032 to get expo-apple-authentication setup with firebase for my expo managed app. I, unfortunately, can't seem to work out what is causing the issue of the error **undefined is not an object (evaluating 'appleCredential.identityToken')** and am looking for help! I have configured apple sign-in on my developer account, ios.usesAppleSignIn has been added to the app.json, so I am clueless as to what's causing it. Also the firebase stuff should be irrelevant to this issue as the issue seems to be nothing returning from the **AppleAuthentication.signInAsync()** method.

Thanks

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 31
        Build Tools: 29.0.3, 30.0.2
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-navigation: ^3.13.0 => 3.13.0
    Expo Workflow: managed
```

### Reproducible demo

```

import * as AppleAuthentication from "expo-apple-authentication";
import * as Crypto from "expo-crypto";

...

async signInWithApple() {
    const nonce = Math.random().toString(36).substring(2, 10);

    return Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256, nonce)
      .then((hashedNonce) => {
        console.log(hashedNonce);
        AppleAuthentication.signInAsync({
          requestedScopes: [
            AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
            AppleAuthentication.AppleAuthenticationScope.EMAIL,
          ],
          nonce: hashedNonce,
        });
      })
      .then((appleCredential) => {
        console.log(appleCredential);
        const { identityToken } = appleCredential;
        const provider = new firebase.auth.OAuthProvider("apple.com");
        const credential = provider.credential({
          idToken: identityToken,
          rawNonce: nonce,
        });
        return firebase.auth().signInWithCredential(credential);
        // Successful sign in is handled by firebase.auth().onAuthStateChanged
      })
      .catch((error) => {
        // ...
      });
  }

```

**Comment by byCedric** [comment]
Hi @JackkFi5h! The `appleCredentials` are coming from `AppleAuthentication.signInAsync`, but in your snippet this code never gets passed.

Your snippet contains a double `.then` chain on a promise, which is fine and can help write good code. But, it's also a common pitfall of "hiding" responses. What happens in the 2nd `.then` is that you get the results of the previous `.then`, if it's completed successfully.

In your case, you never returned the response of `AppleAuthentication.signInAsync` for the next `.then` callback. Which means, you don't get any value for `.then((appleCredential) ...`. Change this line and you should get it working:

```diff
      .then((hashedNonce) => {
        console.log(hashedNonce);
-       AppleAuthentication.signInAsync({
+       return AppleAuthentication.signInAsync({
          requestedScopes: [
            AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
            AppleAuthentication.AppleAuthenticationScope.EMAIL,
          ],
          nonce: hashedNonce,
        });
      })
      .then((appleCredential) => {
        console.log(appleCredential);
```

Hope this helps!
