### ISSUE TITLE
AR world rotates on iPhone when switching to lanscape

### ISSUE THREAD

**Issue by andrewbest** [expo/expo#1642]
One more AR issue today.

When creating a new snack with the Basic AR example, landscape orientation will rotate the world in some cases.

Here is a new snack, the App.js code was copied directly from the original snack.
Edit: https://snack.expo.io/@blamsoft/ar-world-rotates

Here is the original snack.
https://snack.expo.io/Hk1C_YqjW

On my iPhone 7, landscape mode is not working, the world rotates and moves with the camera. On my iPad Pro things work as expected.

**Comment by andrewbest** [comment]
Sorry, this could be a false alarm. Sometimes it works correctly. I'll do some more testing.

**Comment by schazers** [comment]
Okay, thanks for all of these AR reports! Let us know if you figure this one out :)

**Comment by andrewbest** [comment]
I think the old snack and the new snack are the same. This one doesn't seem to be an actual bug. You can close it.

**Comment by schazers** [comment]
Ok, thanks!

**Comment by andrewbest** [comment]
Haven't seen this bug. Will close since it's not reproducible.
