### ISSUE TITLE
Linking with release-channel and queryParams open wrong version within expo go.

### ISSUE THREAD

**Issue by JosephMarotte** [expo/expo#16423]
### Summary

This was only tested on android.

When opening generated by `Linking.createURL("/one", { queryParams: { hello: "world" } })` within a published version with specified `release-channel` it opens the wrong version.

The generated URL is : `exp://exp.host/@josephmarotte/react-navigation-test/--/one?hello=world&release-channel=issue1`
```
adb shell am start -W -a android.intent.action.VIEW -d "exp://exp.host/@josephmarotte/react-navigation-test/--/one?hello=world&release-channel=issue1"
```

Open the default release-channel.

Another possible generated url (which is not opened) is `exp://exp.host/@josephmarotte/react-navigation-test/--/one?release-channel=issue1&hello=world`

This second one open the correct release-channel.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
      Watchman: 20201120.183554.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: managed
```

### Reproducible demo

You can use the url I provided above.

1. Initialize a project with react-navigation template.
2. Generate url from within the app with `createURL` and `queryParams` (eg : add `{Linking.createURL("/one", { queryParams: { hello: "world" } })}
` to one of the existing screens
3. 2. Publish a version within a --release-channel (eg: `expo publish --release-channel issue1`)
4. Attempt to access the url --> wrong release is opened.

If needed [a repo with the above step taken](https://github.com/JosephMarotte/react-navigation-issue-example-repo)

**Comment by lindan4** [comment]
I am facing this issue with release channels as well. Has anyone found a solution?
