### ISSUE TITLE
[docs] app.config.js updates.url is too vague

### ISSUE THREAD

**Issue by ShaneMcNamara** [expo/expo#16428]
### Summary

I'm attempting to migrate from the classic build system to EAS. I'm self hosting my files and would usually use `expo build:ios --public-url`. [As described here, I'm trying to add the update url to my app.config.js](https://docs.expo.dev/distribution/hosting-your-app/#building-the-standalone-app).

It's unclear to me what that URL is meant to be. I've got two different JSON files, one for Android and one for iOS. Should the URL be the root of the directory that contains both? Or should it be a link to the specific file depending on which build I'm doing?

I've tried both of the above and the app won't perform OTA updates, so maybe it's something else. The docs should have clear and explicit examples for both iOS and Android.

### Link to the related docs page

https://docs.expo.dev/versions/latest/config/app/#url

**Comment by byCedric** [comment]
hi @ShaneMcNamara! The `--public-url` is something related to self-hosting updates, it's the absolute URL (not file path) that points to the update manifest hosted on a custom server. You can't use this to switch configurations. 

You should only have a single `app.config.js` file, within this file you can add any logic to return a different configuration. We don't have an option to change the path to a different configuration.

Hope this helps

**Comment by ShaneMcNamara** [comment]
Hi @byCedric,

Thanks for the response. I've been using self hosted updates for over a year with classic builds, but your answer is still unclear to me. What is the "update manifest"? 

When I use `expo export --public-url=https://myendpoint/{buildNumber}` it creates a `dist` directory that looks like this:

├── android-index.json
├── ios-index.json
├── assets
│   └── 1eccbc4c41d49fd81840aef3eaabe862
└── bundles
      ├── android-01ee6e3ab3e8c16a4d926c91808d5320.js
      └── ios-ee8206cc754d3f7aa9123b7f909d94ea.js

Which one of these is my update manifest? Do I need to use the `Platform` module to dynamically choose `android-index.json` or `ios-index.json` based off the OS? 

I would build my iOS and Android apps using classic like this:
`expo build:ios --public-url=https://myendpoint/{buildNumber}/ios-index.json`
`expo build:android --public-url=https://myendpoint/{buildNumber}/android-index.json`

Please don't close the issue, as the **original problem of poor documentation** still exists.

**Comment by byCedric** [comment]
I see, but the examples are here right?

![image](https://user-images.githubusercontent.com/1203991/155766541-cff76079-b72b-4850-a22c-feec96d421d4.png)

**Comment by ShaneMcNamara** [comment]
No those are not examples for EAS, those are examples for `expo build` i.e. classic.

EAS uses `eas build` and requires that I set the `updates.url` in `app.config.js`

**Comment by ShaneMcNamara** [comment]
Maybe to make it clearer, let's use those examples. 

If I have these two update files:

- https://expo.github.io/self-hosting-example/ios-index.json
- https://expo.github.io/self-hosting-example/android-index.json

What is my `updates.url` in `app.config.js`?

1. `https://expo.github.io/self-hosting-example`
2. `https://expo.github.io/self-hosting-example/${Platform.select({ android: 'android-index.json', ios: 'ios-index.json'  })}`
3. Two `app.config.js` with different urls
4. Something else

Whichever one it is of the above, should be in the documentation as an example.
