### ISSUE TITLE
iPad initial orientation rotates to portrait when the device is in landscape orientation

### ISSUE THREAD

**Issue by luanzt** [expo/expo#16431]
### Summary

Default I set expo.orientation: 'default' to auto rotate according to device orientation.
However when I put the ipad in landscape, close the app completely and reopen the app, it seems to initially open in landscape orientation as expected, but after a while it automatically rotates to portrait.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

System:
      OS: macOS 11.6.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.5.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.1 - /usr/local/bin/npm
      Watchman: 2022.02.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.3 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: managed

### Reproducible demo

Here is demo: https://streamable.com/denir5

**Comment by successful-fella** [comment]
I'm having same issue. Were you able to find a fix?

**Comment by luanzt** [comment]
I think it have fixed in Expo SDK 45 @successful-fella

**Comment by successful-fella** [comment]
I am having same problem on all latest SDKs - 44, 45 & 46. But thanks for replying I will give it a try again.

**Comment by jordanful** [comment]
Same issue here.
