### ISSUE TITLE
Expo SDK upgrade destroys App Icons/look

### ISSUE THREAD

**Issue by yesIamFaded** [expo/expo#16432]
### Summary

My App was working/looking fine. I decided to update React Dependencies so I ran `expo upgrade`. 

I got my App running now but there is something weird that happend. The Icons and Buttons do not look like before, without changing the code. 

Here is how it looks: 
![expo upgrade icons](https://user-images.githubusercontent.com/48751859/155493466-f2f26692-7508-4f98-b18d-d9d916654f12.PNG)

As you can see the Icons / Checkbox and Text are cut off. Also the App seems a bit slower.. 

Any help is appreciated.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44.0

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19043        
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      npm: 7.20.5 - C:\Dev\npm\npm\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.0.10 => 4.4.4
    Expo Workflow: managed

### Reproducible demo

Nothing to show here... my code hasnt changed and it was working before.

**Comment by EvanBacon** [comment]
> The Icons and Buttons do not look like before, without changing the code.

Presumably you changed most of the code by running `expo upgrade`, this could be an upstream issue with `react-native` or `@expo/vector-icons` it's a bit hard to determine with the given info.

**Comment by yesIamFaded** [comment]
Okay I get that but what am I ment to do now? I changed the stylings so it looks ok but it is much slower and with that slowness there are some buttons that can be pressed which should not be able to and which was not possible. But because it is slower now the buttons can be reached if you click fast enough 😟
