### ISSUE TITLE
Fetch Fails with "Network request failed" only on Android

### ISSUE THREAD

**Issue by jmedran** [expo/expo#16451]
### Summary

Hi Expo Team - On Android async Fetch request fails with an ambiguous "Network request failed" error only on Android. iOS works great. This happens both locally in Expo Go, and in a production apk build on a physical device. Oddly enough, this only happens for ONE endpoint. Currently, I call 4 endpoints using fetch, and 3 work on Android. I highly doubt this is an issue with my server, because the fetch call that fails never makes it to the server. Greatly appreciate any help!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

SDK 44

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.npm-global/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0 => 44.0.4
      react: ^17.0.1 => 17.0.2
      react-native: ^0.64.3 => 0.64.3
      react-navigation: ^4.4.0 => 4.4.4
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: managed

### Reproducible demo

**Fetch call that fails:**
```
export const updateEmailAction = (newEmail) => {
  return dispatch => {
    dispatch(triggerUpdateEmail());
    return getAuthToken(newEmail).then(request => {
      fetch(UPDATE_EMAIL_ENDPOINT, request)
      .then(response => {
        if(response.status === 200){
          dispatch(updateEmailSuccess())
        }else throw Error(response.error);
        })
        .catch(e => {
          console.log("ERROR", e.message);
          dispatch(updateEmailError())
        });
    })
  };
}
``` 

where `getAuthToken()` is:

```
const getAuthToken = (newEmail) => {
  return firebase.auth().currentUser.getIdToken().then((idToken) =>{
    const request = {
      method: 'POST',
      headers:{
        'Authorization': `Bearer ${idToken}`
      },
      body: newEmail
    }
    return request;
  });
}
```

**Note:** `getAuthToken` works fine and is not the cause of the issue. The issue happens with `fetch()`

**Fetch call that works:**
```
export const deleteAccountAction = () => {
  return dispatch => {
    dispatch(triggerDeleteAccount());
    return getAuthToken().then(request => {
      fetch(DELETE_USER_ENDPOINT, request)
        .then(response => {
          dispatch(deleteAccountSuccess(response))
        })
        .catch(e => {
          console.log(e);
          dispatch(deleteAccountError())
        });
    })
  };
}
```

As you can see, these fetch calls are essentially configured the same. The main difference is the URL to which they point. As I previously mentioned, the server isn't receiving the request for the failed fetch. Its not rejecting the request, the fetch just isn't happening. So strange. Please help - I've been scouring the internet for days without any lead. The error "Network request failed" is far too ambiguous. Thank you!

**Comment by edenriquez** [comment]
My team and I spend the last 2 days debugging this after update to expo 44 as well and we saw the same behaviour, we had to rollback to a previous version because of this.

**Comment by raajnadar** [comment]
I had similar issue with axios and android expo managed, What I did was using flipper to inspect the request & response headers, I found that with axios for api the content type was not correct it was not sending the boundary.

https://github.com/axios/axios/issues/4406#issuecomment-1046035267

https://github.com/axios/axios/issues/4406#issuecomment-1049125278

The best way to debug is using the flipper or remote js debug & compare the working api call request & response with the not working one.

**Comment by ezratechdev** [comment]
Am facing a similar issue.Am trying to upload a file using form data.Has there been a fix to this?

**Comment by hugoqueiros-parfois** [comment]
My app was making the fetch like 2 days ago, and now it gives me this error. It was some expo update? Any updates?

**Comment by margins200** [comment]
Another option! scan the QR code with expo clients

**Comment by ulrich-cyber** [comment]
I get the same error for my login form with expo go but when I launch it on the web everything works fine

**Comment by abdulmuksith3** [comment]
I suffer from the same issue only on some Android devices. Any solution yet?

Managed  Workflow
Expo: 44.0.0
RN: 0.64.3

**Comment by WillenOLeal** [comment]
Having the same issue on expo SDK 46

**Comment by louischan** [comment]
In my case, the issue was caused by incomplete SSL certificate chain on the web server. Adding the intermediate certificate solved it.

**Comment by ewfian** [comment]
> In my case, the issue was caused by incomplete SSL certificate chain on the web server. Adding the intermediate certificate solved it.

Same case here.

**Comment by dmahajan980** [comment]
I'm facing the same issue on Expo SDK 47 (managed workflow) for Android.

**Comment by dmahajan980** [comment]
Okay, so I was able to get through this by setting the `Content-Type` header.

```javascript
fetch(<SOME_URL>, {
  ...
  headers: {
    ...
    'Content-Type': 'application/json'
  }
})
```

**Comment by danyhiol** [comment]
I also have this same issue on both the emulator and the device on **android(only)**.
After some searching and debugging, I could extract the error from adb: `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.` And after googling for hours, couldn't find any way of solving this. I ended up thinking this was an issue with the server: `https://<domain>:<port>/`. But requests to the same server are working on IOS and on WEB or tools such as Postman. Some solutions suggest adding [mimeType](https://stackoverflow.com/questions/68089031/axios-post-formdata-not-working-properly-in-react-native) to the `formData` option. But I am not posting a file, but some parameters. In fact, my server accepts only `formData`. Moreover, not all requests are failing.

**Comment by danyhiol** [comment]
@garrettg123 can you elaborate? Where do I make this change? My server is not local, but remote: `https://<domain>:<port>/`. If you mean [this](https://forums.expo.dev/t/react-native-fetch-remote-http-request-throws-network-request-failed-on-android-device/34886), I doubt it would help because of the remote host.

**Comment by vincentdesmares** [comment]
> I saw this error while using localhost in development (which works on iOS). Changing this to my machine's static ip (eg. 192.168.0.100) fixes this on Android, although it's a bit annoying when it changes.

I can confirm that switching my Graphql calls from **http://localhost:8080** to **http://191.168.1.16:8080** solved the issue.

I had only the problem on Android (emulator and phone) but not on IOS and web.

**Comment by saibbyweb** [comment]
> In my case, the issue was caused by incomplete SSL certificate chain on the web server. Adding the intermediate certificate solved it.

For hosted backends, it definitely has something to do with SSL. As a temporary fix, changing the url prefix to `http` from `https` worked for me.

**Comment by ZuulAndRibbon** [comment]
> In my case, the issue was caused by incomplete SSL certificate chain on the web server. Adding the intermediate certificate solved it.

the same case.Because u don't do this action that .crt and .ca-bundle files have not been combined in one .crt file before uploading to server.You need to do this action before configure ssl in nginx.conf

**Comment by linonetwo** [comment]
Another case: If your site is using *.crt/*.key SSL pairs, try use *.pem/*.key instead. *.pem file include the necessary root cert for Android devices that does not know your SSL issuer.

**Comment by sovetski** [comment]
I had the same error and my problem was coming from .env file, my keys were not prefixed.

I changed `API_URL `to `EXPO_PUBLIC_API_URL `and it worked.

Docs: https://docs.expo.dev/guides/environment-variables/

**Comment by adamwoolhether** [comment]
> I saw this error while using `localhost` in development (which works on iOS). Changing this to my machine's static ip (eg. `192.168.0.100`) fixes this on Android, although it's a bit annoying when it changes.

This did it for me too, i have to set my backend to listen on the same IP as my macbook, rather than "localhost". Only then can I connect the App with my Android device or simulator.

This isn't an issue with iOS or iOS simulator.

**Comment by jan-czerwinski** [comment]
> I saw this error while using `localhost` in development (which works on iOS). Changing this to my machine's static ip (eg. `192.168.0.100`) fixes this on Android, although it's a bit annoying when it changes.

thank you! fixed for me too. 
previously it worked on physical android, ios simulator, and not on android simulator

**Comment by athenadever** [comment]
> I also have this same issue on both the emulator and the device on **android(only)**. After some searching and debugging, I could extract the error from adb: `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.` And after googling for hours, couldn't find any way of solving this. I ended up thinking this was an issue with the server: `https://<domain>:<port>/`. But requests to the same server are working on IOS and on WEB or tools such as Postman. Some solutions suggest adding [mimeType](https://stackoverflow.com/questions/68089031/axios-post-formdata-not-working-properly-in-react-native) to the `formData` option. But I am not posting a file, but some parameters. In fact, my server accepts only `formData`. Moreover, not all requests are failing.

Hi, @danyhiol 
Have you solve above issue?
If so, can you reply me?
Thanks

**Comment by pedroPike** [comment]
Ive had the same problem!

**Comment by ViaAnthroposBenevolentia** [comment]
To those of you who are encountering this error on Android emulators:

Even if you don't make any calls to your localhost or manual fetches, but, for example, use supabase-js sdk's methods that make these requests, then it might be indeed a Network error. 

I.e. your android emulator simply doesn't have access to internet. To resolve this, you might want to cold restart your android emulator as suggested in here: https://stackoverflow.com/questions/42736038/android-emulator-not-able-to-access-the-internet

As of for me this happens when the emulator is running for a long time on Mac. When I cold boot the emulator (or other methods such as rebuilding/reinstalling) the issue resolves. 

Hope this helps :)
