### ISSUE TITLE
Problem upgrading to SDK 26

### ISSUE THREAD

**Issue by marcosmartinez7** [expo/expo#1645]
Hi, 

im having issues upgrading an app from sdk 21 to sdk 26.

I have followed this steps: 

1) In app.json, change sdkVersion to "26.0.0"
2) In package.json, change these dependencies:
- react-native to "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz"
- expo to "^26.0.0"
- react to ("16.3.0-alpha.1" — this exact version) 
- react-navigation to "1.5.8" 

Previously, i was using:
- expo ^21.0.2
- react-navigation ^1.0.0-beta.21"
- react": "^16.0.0-alpha.12",
 - react-native": "^0.48.4"

Now im getting this error, i oont know where start to search or debug.. any ideas?

![app](https://user-images.githubusercontent.com/14795944/38686428-a7f222b2-3e4a-11e8-8942-9763e41b6dba.png)

This are the full dependencies:

```
 "dependencies": {
    "@expo/vector-icons": "^5.2.0",
    "expo": "^21.0.2",
    "install": "^0.10.1",
    "moment": "^2.19.1",
    "moment-timezone": "^0.5.14",
    "native-base": "^2.3.2",
    "npm": "^5.4.2",
    "prop-types": "^15.6.0",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.48.4",
    "react-native-communications": "^2.2.1",
    "react-native-directed-scrollview": "^1.3.0",
    "react-native-inputs": "^0.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.4.1",
    "react-native-lazyload-components": "^1.0.1",
    "react-native-maps": "^0.16.4",
    "react-native-material-design-searchbar": "^1.1.7",
    "react-native-material-dropdown": "^0.6.0",
    "react-native-material-textfield": "^0.10.2",
    "react-native-rest-client": "^0.1.1",
    "react-native-root-toast": "^2.2.0",
    "react-native-snackbar-component": "^1.0.8",
    "react-native-textinput-effects": "^0.4.1",
    "react-navigation": "^1.0.0-beta.21",
    "react-navigation-redux-debouncer": "^0.0.2",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  }

```

Kind regards

**Comment by marcosmartinez7** [comment]
That error was asociated with a circular dependency in my code, that dependency wasnt a problem in previous react native versions. Please close this issue

**Comment by ccheever** [comment]
glad you figured it out

**Comment by danilomiranda** [comment]
@marcosmartinez7 what was the dependency? I'm facing problems with the upgrade too
