### ISSUE TITLE
Selecting a file using Expo Document Picker is crashing iOS application on iOS simulator and iOS device

### ISSUE THREAD

**Issue by pallavi08sharma** [expo/expo#16450]
### Summary

I am using Expo document picker to select a file from my device. But, as soon as I am selecting a file, the iOS application in iOS simulator and in an iOS device is getting crashed.

EXPO SDK version : 44.0.0
Expo Document Picker : 10.1.3

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

 expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@pallavi08sharma/documentpickerissue

**Comment by tommymetz** [comment]
This is happening to me too and I can't seem to find a solution. Although it's not crashing the built app for me, just the simulator.

**Comment by ibrag474** [comment]
Crashes for me on simulator and built app too. SDK 44.0.6, expo-document-picker@10.2.1
