### ISSUE TITLE
Audio starts from the beginning when using m3u8 in expo-av

### ISSUE THREAD

**Issue by TheNerdGuyLulu** [expo/expo#16458]
### Summary

After the video finishes playing, the audio starts again from the beginning while showing the last video frame.
Video uses m3u8 format.

Expected behavior:
Video and audio should stop when reaching the end.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.5.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.4.1 - /usr/local/bin/npm
      Watchman: 2022.02.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Beta 2 Chipmunk 2021.2.1 Beta 2
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.65.1 => 0.65.1 
    Expo Workflow: bare
```

### Reproducible demo

<VideoContainer
            source={{ uri: 'https://3520.cdn.video.taxi/4uCRIMfJWr82/stream.m3u8' }}
            onReadyForDisplay={() => setIsVideoReady(true)}
            resizeMode="contain"
            useNativeControls
          />

**Comment by TheNerdGuyLulu** [comment]
This hack is a workaround.

```
onPlaybackStatusUpdate={status => {
    if (isIos && status.didJustFinish) {
         videoRef.current?.unloadAsync();
         videoRef.current?.loadAsync({ uri });
    }
}}
```

**Comment by junedomingo** [comment]
Same here. Works fine on android

"expo": "^44.0.6",
"expo-av": "^10.2.1",

Thanks @TheNerdGuyLulu for the workaround!🙏

**Comment by jpalumickas** [comment]
We have the same problem, thanks @TheNerdGuyLulu for this temporarily hack!

**Comment by RocketRonz** [comment]
This problem still exists in the latest expo-av (11.2.3). It does not occur on Android with m3u8 or iOS with MP4s, so the problem is specific to the HLS format on iOS.

I realise there is a workaround but I'm using setInterval instead of onPlaybackStatusUpdate (to workaround a different problem with expo-av), so never receive the didJustFinish state. Any chance this can be looked into for the next expo-av release?
