### ISSUE TITLE
Deep linking from expo dev client

### ISSUE THREAD

**Issue by cyrilmarceau** [expo/expo#16484]
Hello,

I built my application with expo dev client. So I'm trying to update my code to make it work with deep linking.
I have this url during the build: exp+<myscheme>://expo-development-client/?url=http%3A%2F%2F<domain.fr>%3A<port>

When I click on the link from an email it finds the application to launch but remains stuck on a black screen without starting the app. No console.log appears in my app.js

`const prefix = Linking.createURL("/");

export const linking = {
    prefixes: [prefix],
   ...
}`

**Comment by SupriyaPKalghatgi** [comment]
@cyrilmarceau I am somewhat stuck with similar issue
Are you trying on `Expo Go` or is it `Standalone app`?

**Comment by cyrilmarceau** [comment]
I build app with eas for use it with expo-dev-client so it's a standalone app.

**Comment by SupriyaPKalghatgi** [comment]
> When I click on the link from an email it finds the application to launch but remains stuck on a black screen without starting the app. No console.log appears in my app.js

If you run your app and then receive push notification (without going through email), is your deep linking working as expected?

**Comment by cyrilmarceau** [comment]
I don't do push notification for the moment

**Comment by SupriyaPKalghatgi** [comment]
Oh! I thought so from your statement in issue description 
I am stuck at deep linking with push notifications for standalone app

**Comment by cyrilmarceau** [comment]
The problem must be similar, only me it's from an email and you from the push notifications

**Comment by SupriyaPKalghatgi** [comment]
I have defined `app.json` with 👇🏻 
```
. . .
"scheme": "myapp",
. . .
"android": {
      "adaptiveIcon": {
        "foregroundImage": ".icon.png",
        "backgroundColor": "#FFF"
      },
      "versionCode": 1,
      "permissions": [
        . . .
      ],
      "useNextNotificationsApi": true,
      "intentFilters": [
        {
          "action": "VIEW",
          "autoVerify": true,
          "data": [
            {
              "scheme": "myapp",
              "host": "app"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
      ],
      "package": "com.myapp.app",
      "googleServicesFile": "./google-services.json"
    },
. . .
```

And include with push notification, deep link to route
```
{ "url": "myapp://screenOne" }
```
I receive notification, but does not route. And get this error
`java.net.SocketTimeoutException: failed to connect to /<my phone device IP> (port 19000) from /<some other IP> (port 48802) after 10000ms`

**Comment by SupriyaPKalghatgi** [comment]
@cyrilmarceau If its a standalone app, then try displaying `alert` or `toast` in place of `console.log` to check what is not running for you
Make use of anyone of above to check if the token generated and the one you are mentioning in email are same, then check if `addNotificationReceivedListener` and `addNotificationResponseReceivedListener` is reached or not

**Comment by cyrilmarceau** [comment]
And what did you do in your backend in url when you send your notif or email ?

**Comment by SupriyaPKalghatgi** [comment]
Currently all I am doing in my backend is saving token
Whereas I am sending Push Notifications through Expo API

**Comment by SupriyaPKalghatgi** [comment]
```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[<token>]",
  "title": "Title",
  "body": "Your Message",
  "data": { "url": "myapp://path" },
  "channelId": "default"
}'
```

**Comment by cyrilmarceau** [comment]
Yes that it's working I have switch to the current IP and my view is find and when is open.

**Comment by SupriyaPKalghatgi** [comment]
Sorry I am not clear as to what you are saying

**Comment by cyrilmarceau** [comment]
I changed the IP in the link that I send in the mail and when the application is open and I open this link, my path is well found in the application

**Comment by SupriyaPKalghatgi** [comment]
Nice that you got it working

**Comment by SupriyaPKalghatgi** [comment]
Did you get it working with standalone too?

**Comment by cyrilmarceau** [comment]
Yes it's working
