### ISSUE TITLE
App crashes on picking HEIC image

### ISSUE THREAD

**Issue by GermaVinsmoke** [expo/expo#16483]
### Summary

We are using expo-image-picker. When we are trying to upload a HEIC image file from iOS device, the app is crashing.

```
    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      aspect: [1, 1],
      allowsEditing: true,
      quality: 1,
      presentationStyle: 0,
    });
```

Tried to console log the **result** but it returns nothing in case of HEIC image.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.4 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.14 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.1.2
    Expo Workflow: managed
```

### Reproducible demo

Try selecting a HEIC image and it'll crash.

**Comment by jirr** [comment]
I'm facing the same issue. Did you find a solution or workaround @GermaVinsmoke ?

**Comment by GermaVinsmoke** [comment]
Nope, nothing. Still facing the issue. Funny that no one's ready to check this problem XD

**Comment by thecompoundingdev** [comment]
Same error on iOS. Picking images on iOS is a gamble, crashes my app 1/3 times

**Comment by filippo-fonseca** [comment]
I'm having the same issue, someone please help :/

**Comment by L4znet** [comment]
Same here :(

**Comment by GermaVinsmoke** [comment]
The issue is still there.

**Comment by GermaVinsmoke** [comment]
Okay, wait for some days and you'll have the repo. I've also not tested it again.

**Comment by behenate** [comment]
Hi, I've tried to recreate the issue but the picker worked every time. Have you tried newer versions of the SDK? If you have problems on the newest version of the SDK please upload the minimal reproducible example.
