### ISSUE TITLE
expo-camera "onBarCodeScanned" not triggering when jsEngine is "hermes"

### ISSUE THREAD

**Issue by Engazan** [expo/expo#16503]
### Summary

Today, we have to switch barcodescanner package for "expo-camera" so we build our app with "eas build" and we noticed that in Real app "onBarCodeScanned" is not triggered

Expo go
- working

Real app build 
- not working

jsEngine 
- hermes

Real Device
- iPhone 12

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.0.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.1.3
    Expo Workflow: managed

### Reproducible demo

```tsx

const [scanned, setScanned] = useState(false);

return (
<Camera
                onBarCodeScanned={
                    scanned ? undefined : (args) => {
                        alert('scanned')
                        setScanned(false)
                    }
                }
>
</Camera>
)
```

**Comment by VNDRN** [comment]
I've noticed the same issue in our app. The solution I've found is to install the expo-barcode-scanner package. You don't have to use it, just have it installed in your project.

**Comment by Szulerinio** [comment]
Had the same problem on 
android 10 
using 
Expo Workflow: managed

SDK 44
expo 44.0.4 
expo-camera 12.1.2
react 17.0.1 
react-native 0.64.3
expo-cli 5.3.0 

Installing expo-barcode-scanner worked for me

**Comment by Engazan** [comment]
> Had the same problem on android 10 using Expo Workflow: managed
> 
> SDK 44 expo 44.0.4 expo-camera 12.1.2 react 17.0.1 react-native 0.64.3 expo-cli 5.3.0
> 
> Installing expo-barcode-scanner worked for me

Yes bud it doesnt offer perfect aspect ratio fit, so camera cant be 100% width and 100% height on some android devices even when you do a few hacks to make it looks like it its terrible

**Comment by anders0l** [comment]
1 year passed, same issue on Android on after eas build

SDK 48
expo 48.0.10
expo-camera 13.2.1
react 18.2.0
react-native 0.71.8
expo-cli 6.3.10

Same solution - install the expo-barcode-scanner, even if not used

Please update docs or fix it
That's ugly

**Comment by acarlstein** [comment]
Greetings, will you help me?



I created a simple  text QR code using [qr.io](https://qr.io/?gad_source=1&gclid=CjwKCAiAq4KuBhA6EiwArMAw1DnpTm9utBoeNj1Qa6hVxlcFAjx34kWrktGXkbeVzBhsuUPXhmFZFBoC_24QAvD_BwE) but for some unknown reason, the `onBarCodeScanned` isn't working. 

I'm not sure if this bug has been reintroduced into the new version of Expo or if my code has a bug.


I tried different barcode types and even tried what is below:
```
barCodeScannerSettings={{ barCodeTypes: ['qr'] }}

barCodeScannerSettings={{ barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr] }}

barCodeScannerSettings={{ barCodeTypes: ['qr', BarCodeScanner.Constants.BarCodeType.qr] }}
```


These are the dependencies in *package.json:*
```
"dependencies": {
    "@assets/images": "./assets",
    "@expo/vector-icons": "^14.0.0",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@ui-library/components": "./app/Components",
    "@ui-library/templates": "./app/Templates",
    "expo": "~50.0.5",
    "expo-barcode-scanner": "~12.9.2",
    "expo-camera": "~14.0.3",
    "expo-constants": "~15.4.5",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.6",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "patch-package": "^8.0.0",
    "punycode": "^2.3.1",
    "react": "18.2.0",
    "react-native": "0.73.2",
    "react-native-modal": "^13.0.1",
    "react-native-qrcode-svg": "^6.3.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "^14.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "metro": "^0.80.5"
  },
```

And this is the code in question *QRCodeReader.js:*
```javascript
import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, TouchableOpacity }  from 'react-native';
import { Camera } from 'expo-camera';
import { BarCodeScanner } from 'expo-barcode-scanner'

import { MaterialCommunityIcons } from '@expo/vector-icons';

const QRCodeReader = ({ navigation }) => {

    const [hasPermission, setHasPermission] = useState(null);
    const [type, setType] = useState(Camera.Constants.Type.back);
    const [permission, requestPermission] = Camera.useCameraPermissions();

    requestPermission()

    useEffect(() => {
        (async () => {
            const { status } = await Camera.requestCameraPermissionsAsync();
            setHasPermission(status === 'granted');
            console.log("Permission is granted?", status);
        })();
    }, []);

    if (hasPermission === null) {
        return <Text>No access to camera</Text>;
    }

    if (hasPermission === false) {
        return <Text>No access to camera</Text>;
    }

    function toggleCameraType() {
        setType(current => (current === Camera.Constants.Type.back ? Camera.Constants.Type.front : Camera.Constants.Type.back));
    }

    const processBarCodeScanned = (...args) => {
        console.warn("processBarCodeScanned", args);
        this.props.onScanResult(args)
    }

    return (
        <View style={styles.container}>
            <Camera
                onBarCodeScanned={(...args) => processBarCodeScanned}
                barCodeScannerSettings={{
                    barCodeTypes: ['qr', BarCodeScanner.Constants.BarCodeType.qr],
                }}
                style={styles.camera}
                type={{ type }}
            />
            <TouchableOpacity
                onPress={() => toggleCameraType}
                style={{
                    borderWidth: 1,
                    borderColor: 'rgba(0,0,0,0.2)',
                    alignItems: 'center',
                    justifyContent: 'center',
                    width: 70,
                    position: 'absolute',
                    bottom: 10,
                    right: 10,
                    height: 70,
                    backgroundColor: '#fff',
                    borderRadius: 100,
                }}>
                <MaterialCommunityIcons name="camera-flip" size={24} color="black" />
            </TouchableOpacity>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    camera: {
        flex: 1,
    },
    buttonContainer: {
        flex: 1,
        backgroundColor: 'transparent',
        flexDirection: 'row',
        margin: 20,
    },
    button: {
        flex: 0.1,
        alignSelf: 'flex-end',
        alignItems: 'center',
    },
    text: {
        fontSize: 18,
        color: 'white',
    },
});

export default QRCodeReader;
```

Thank you in advance for any help you can provide. Have a nice day :)

**Comment by l5** [comment]
Same again here, Feb 2024. Tested with Android.

**Comment by felipejh** [comment]
Same here using the `CameraView` from `expo-camera/next`.

**Comment by jarnove** [comment]
I got it to work without installing the expo-barcode-scanner package with the following code:

```
import { CameraView } from 'expo-camera/next';

<CameraView onBarcodeScanned={...}..
```

Watch out with onBarcode (new) & onBarCode (old) because the naming changed.

**Comment by JoPoTe** [comment]
Same issue @VNDRN 's solution of having the expo-barcode-scanner package installed resolves it. Wish they updated the docs.

**Comment by RaGuL2k23** [comment]
> ```tsx
>  alert('scanned')
> ```

thanks man great work

**Comment by Abdulazeez-98** [comment]
I am on "expo": "50.0.17" and "expo-camera": "~14.1.3" . The problem is still present. Installing expo-barcode-scanner solved the issue with Android but not iOS. However, BarCodeScanner component (from expo-barcode-scanner ) worked fine on both platforms.
I hope this issue is fixed in Expo SDK v51.

**Comment by sydneymlambo** [comment]
> I got it to work without installing the expo-barcode-scanner package with the following code:
> 
> ```
> import { CameraView } from 'expo-camera/next';
> 
> <CameraView onBarcodeScanned={...}..
> ```
> 
> Watch out with onBarcode (new) & onBarCode (old) because the naming changed.

This worked for me

**Comment by nolife08021** [comment]
facing same issue on web platform, onBarcodeScanned not trigger
```
 <CameraView
     style={{ flex: 1 }}
      facing={"front"}
      barcodeScannerSettings={{
        barcodeTypes: ["qr"],
      }}
      onBarcodeScanned={(e) => {
        console.log(e);
      }}
>
```

**Comment by informagenie** [comment]
Sometime, you lose a lot of time scanning an invalid QR Code or a not scannable QR Code.

For instance, the QR Code shown in Google SERP when searching "qr code".

Try to scan another QR Code.
