### ISSUE TITLE
[expo-camera] Camera crashing when enabling flash on Android Barcode Scanner

### ISSUE THREAD

**Issue by weisensee** [expo/expo#16520]
### Summary

Hi :)

I'm trying to enable/disable the flash when scanning a barcode.

In the expo managed environment, my app is crashing when I turn on the flash.

We're not seeing any logs from react native in the console.

We are getting this log, repeatedly via `adb logcat`: 

> FATAL EXCEPTION: main
> Process: host.exp.exponent, PID: 10495
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.media.Image$Plane[] android.media.Image.getPlanes()' on a null object reference
> 	at h.f.c.b.c$d.onImageAvailable(Camera2.java:2)
> 	at android.media.ImageReader$1.run(ImageReader.java:837)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7839)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Maybe we are managing state wrong, but we have tried a few different things and keep getting the above log about `android.media.Image.getPlanes()`

Any help would be appreciated

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.1/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.2.0
    Expo Workflow: managed

### Reproducible demo

I created a demo repository which you can see here: [github repo](https://github.com/weisensee/camera-demo)

Not including a snack because this has to be run on expo 44, on a physical device, and I didn't see a way to switch the snack to v44.

**Comment by pweisensee** [comment]
This issue does not seem fixed even with the commit from here: [Fix null pointer exception](https://github.com/expo/expo/commit/6147a9c57cf7dc0550ada12565b36b46bd977120)

@tsapeta any thoughts? Seems to happen in standalone and within Expo Go.

**Comment by pweisensee** [comment]
@byCedric @brentvatne any suggestions if we're seeing this issue? Is flash compatible with barcode scanning using the `expo-camera`?

**Comment by pweisensee** [comment]
This seems to be a bug with the Camera2 API, I believe reverting to the old Android Camera API with `useCamera2Api={false}` fixes the issue for now
