### ISSUE TITLE
Updating with new Updates API 

### ISSUE THREAD

**Issue by James2516** [expo/expo#1652]
I want my app to
- Don't check updates before app is loaded (so app is loaded asap)
- Check for updates whenever app is opened, and auto refresh the app immediately if an update is downloaded
 
Would the following code achieve what I want?
`fallbackToCacheTimeout: 0`

```
AppState.addEventListener('change', async () => {
  const { isAvailable } = await Updates.checkForUpdateAsync();
  if (isAvailable) {
    await Updates.fetchUpdateAsync();
    Updates.reload(); // i assume this will use the above fetched content instead of re-fetching
  }
});
```

Should I set `checkAutomatically` to `ON_ERROR_RECOVERY` too to prevent double checking since I'm already checking it in the above code?

**Comment by schazers** [comment]
Hi James! If you wouldn't mind, please use our forums for personal help rather than filing a github issue. You'll get help more quickly because more people will see it more quickly, and more people may benefit from reading the solution!

I've moved this here: https://forums.expo.io/t/updating-with-updates-api/8907

**Comment by outaTiME** [comment]
Hi @schazers , this questions is not answered in the forum, although @esamelson proposed a solution it only works for a fresh start, and not when it goes from background to foreground, how can I deal with this scenario? I need my app can be updated in a fresh start and also when it goes from background to foreground.

I reported this case in forum but I didn't get an answer yet. 

https://forums.expo.io/t/ota-updates-download-event-not-fired/9835

Is this something you plan to review?
For the moment it seems to be the best way to handle updates is submitting them to the stores.
