### ISSUE TITLE
source-login-scripts.sh breaks with some zsh options

### ISSUE THREAD

**Issue by seeligd** [expo/expo#16525]
### Summary

if one has `zsh` configured with `setopt extendedglob`, the the following line fails to execute:
https://github.com/expo/expo/blob/main/packages/expo-module-scripts/templates/scripts/source-login-scripts.sh#L10

```
setopt extendedglob
current_shell=$(ps -cp "$$" -o comm="" | sed s/^-//)
> zsh: no matches found: s/^-//
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 1.22.10 - ~/Workspace/mobile-app/node_modules/.bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
      Watchman: 2022.02.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/dseelig/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.2, 31.0.0, 32.0.0, 32.0.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.6 => 44.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.67.2 => 0.67.2
      react-native-web: 0.17.0 => 0.17.0
    Expo Workflow: bare

### Reproducible demo

```
# running zsh
setopt extendedglob
current_shell=$(ps -cp "$$" -o comm="" | sed s/^-//)
# fails

unsetopt extendedglob
current_shell=$(ps -cp "$$" -o comm="" | sed 's/^-//')
# works

```

**Comment by Simek** [comment]
Can confirm the issue, CC @Kudo since he is more familiar with this code.

**Comment by Kudo** [comment]
awesome! since you know where exactly the problem and having a solution, do you mind to create a pr for us?
