### ISSUE TITLE
Create download link

### ISSUE THREAD

**Issue by James2516** [expo/expo#1653]
<img src="https://i.imgur.com/lUFfORJ.png" width="300" />

Not sure what this is called, but on Android an app is able to bring up this window, and if I select, say Gmail, it will automatically create a file attachment in Gmail.

How can I achieve this with Expo v26?

**Comment by schazers** [comment]
Hi James,

I believe this is a tutorial for what you want: http://codingmiles.com/react-native-inbuilt-share-library/

Also, as I mentioned in the previous post, please use our forums! You'll get faster answers and help other people :)
