### ISSUE TITLE
expo-av: pitchCorrectionQuality does not show effect, only in iOS

### ISSUE THREAD

**Issue by HisonKahng** [expo/expo#16542]
### Summary

      await sound.setStatusAsync({ rate: rateSound, shouldCorrectPitch: true, pitchCorrectionQuality: 'Medium'})
      await sound.setRateAsync(1.0, true, 'High')

do not make any change in iOS but pitch correction is well done in Android. 
This is the same phenomena either in bare & managed workflow. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
      Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: managed

### Reproducible demo

import * as React from 'react';
import { Text, View, StyleSheet, Button } from 'react-native';
import { Audio } from 'expo-av';

export default function App() {
  const [sound, setSound] = React.useState();
  let playListUri = 'https://ia600500.us.archive.org/5/items/aesop_fables_volume_one_librivox/fables_01_01_aesop.mp3';
  let rateSound = 1.0

  async function playSound() {
    console.log('Loading Sound');
    const { sound } = await Audio.Sound.createAsync({uri: playListUri});
    setSound(sound);

    console.log('Playing Sound');
    await sound.playAsync(); 
  }

  async function SlowDownSound() {
    if(rateSound > 0.1){
      rateSound = rateSound - 0.1
 //sound.setRateAsync, sound.setStatusAsync both of them also do not make effect in iOS
      // await sound.setRateAsync(rateSound, true, true)
      await sound.setStatusAsync({ rate: rateSound, shouldCorrectPitch: true, pitchCorrectionQuality: 'Medium'})
    }
    console.log('Slow Down Sound', rateSound);

  }

  async function SpeedUpSound() {
    if(rateSound < 32.0){
      rateSound = rateSound + 0.1
      await sound.setStatusAsync({ rate: rateSound, shouldCorrectPitch: true, pitchCorrectionQuality: 'Medium'})
    }
    console.log('Speed Up Sound', rateSound);

  }

  async function StopSound() {
    console.log('Stop Sound');
    await sound.unloadAsync()
  }

  React.useEffect(() => {
    return sound
      ? () => {
          console.log('Unloading Sound');
          sound.unloadAsync(); }
      : undefined;
  }, [sound]);

  return (
    <View style={styles.container}>
            <Text>{'Reproducible demo ...'}</Text> 

      <Button title="Play Sound" onPress={playSound} />
      <Text>{'\n'}</Text> 
      <Button title="Slow Down " onPress={SlowDownSound} />
      <Text>{'\n'}</Text> 
      <Button title="Speed Up " onPress={SpeedUpSound} />
      <Text>{'\n'}</Text> 
      <Button title="Stop " onPress={StopSound} />
      <Text>{'\n\n\n * Comment: First, please press Play Sound, and hear the sound, after that, press "Slow Down" once, twice, and three times... Only in iOS the voice is DISTORTED when you press the "slow down" three times - speed down to x0.7 by the log- but NOT in Android.'}</Text> 
      <Text>{' I am not sure that this is one of the shortness of iOS and superiority of Android. '}</Text> 

    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 10,
  },
});

**Comment by mnightingale** [comment]
Use `Audio.PitchCorrectionQuality.Medium` not "Medium".

**Comment by HisonKahng** [comment]
@mnightingale  Thank you, you saved my week !
