### ISSUE TITLE
ImagePicker.requestMediaLibraryPermissionsAsync doesn't ask ACCESS_MEDIA_LOCATION

### ISSUE THREAD

**Issue by jparksecurity** [expo/expo#16548]
### Summary

I can't get an image asset info on Android if I call `ImagePicker.requestMediaLibraryPermissionsAsync` to request permission.

It works fine on iOS, or I call `MediaLibrary.requestPermissionsAsync` to request permissions, then I can get an image asset info on Android after following [the instruction for ACCESS_MEDIA_LOCATION](https://github.com/expo/expo/issues/15273#issuecomment-1005440392)

The error message is

> Cannot access ExifInterface because of missing ACCESS_MEDIA_LOCATION permission

The problem is `ImagePicker.requestMediaLibraryPermissionsAsync` asks only write and read permissions but `MediaLibrary.requestPermissionsAsync` asks write, read, and `ACCESS_MEDIA_LOCATION` permissions.

Related issue: #15273

I tried to fix it but decided to close because it is more complicated than I thought. Ref: #16541

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  ```
expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.3, 30.0.2
        System Images: android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    Expo Workflow: managed
```

### Reproducible demo

I can't provide the reproducible demo because we need EAS build to confirm this issue.

At Expo SDK 44, we can't get an image asset info even if we call `MediaLibrary.requestPermissionsAsync` without EAS build.

Related issue: #15273

**Comment by BrodaNoel** [comment]
@jparksecurity have you found a workaround? I have this same issue.
Have you checked the SDK 45 beta? Any progress there?

I just finished reading the comments were made in your PR, and I don't understand something:
I am currently asking for the permissions with `MediaLibrary.requestPermissionsAsync()`, but then, I launch the library with `ImagePicker.launchImageLibraryAsync`, and the permissions are not there. Only present for iOS (and for some old Android versions, I guess).

Any progress there? Anything you discovered?

**Comment by BrodaNoel** [comment]
Quick question for @barthap and @bbarthec , which your answer may help em to create a workaround:

We know that in SDK 44:
- Calling `ImagePicker.launchImageLibraryAsync` won't provide the EXIF data
- Accessing lat+lng is not that easy as accessing to EXIF data, and we must use `MediaLibrary.getAssetInfoAsync` in order to get that information.

So, it seems like, this could be a possible workaround:
- I request the permissions (including ACCESS_MEDIA_LOCATION) using `MediaLibrary.requestPermissionsAsync`
- I pick up a photo using `ImagePicker.launchImageLibraryAsync`
- I get the full data of the selected image, using `MediaLibrary.getAssetInfoAsync`.

Now... The problem is that `MediaLibrary.getAssetInfoAsync` ask for an [Asset](https://docs.expo.dev/versions/v45.0.0/sdk/media-library/#asset) as first parameter... But... The object retrieved by `ImagePicker.launchImageLibraryAsync` doesn't provide any ID.

The question:
Is there a way to get the ID of the asset in `ImagePicker.launchImageLibraryAsync` response? So then I can get the assetInfo (`MediaLibrary.getAssetInfoAsync`) of that asset using the Media Library?

Thanks!

Love you all!

**Comment by BrodaNoel** [comment]
@jparksecurity are you sure the fix is in the main branch? I didn't see any PR fixing this problem.

On Monday I will be upgrading the app to SDK 45 (I got released yesterday), so, I'll take a look.

Could you please point the file where you are seeing the fix in 'main'? So I can check if it was included in SDK 45 (because I don't even see it in the release changes)

**Comment by BrodaNoel** [comment]
What seems to be in 'main' is the fix for the bug related to the permission, BUT, if you pick up an image with 'ImagePicker.launchImageLibraryAsync', it still doesn't give you the EXIF/lat-lng

**Comment by jparksecurity** [comment]
@BrodaNoel aha, I see. I misunderstood your issue. I had an issue with getting an image because of the permission, but I didn't need EXIF/lat-lng.

I haven't tried to get EXIF/lat-lng, so I'm not sure how to fix it. However, I think getting SDK 45 is not answer if you want EXIF/lat-lng. Have you tried EAS build or bare workflow?

If so, have you added `<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />` to `AndroidManifest.xml` when you test this?

**Comment by jparksecurity** [comment]
no!

**Comment by DanielAndrews43** [comment]
The issue is still occurring for us on Expo 46

**Comment by AlexJWayne** [comment]
I'm seeing this on _some but not all_ Android users. Having trouble replicating it and finding a work around, however.

**Comment by BrodaNoel** [comment]
> I'm seeing this on _some but not all_ Android users. Having trouble replicating it and finding a work around, however.

That's probably because they are Android 10+. Check the android version.

**Comment by hnqlv** [comment]
Have anyone found a solution for this?

**Comment by uplne** [comment]
Any updates on this? I am on version 49 and I still can't get Lat/Lon from ImagePicker.

**Comment by adamita** [comment]
I still have this issue!
I added the ACCESS_MEDIA_LOCATION to manifest and ask for permission with requestMediaLibraryPermissionsAsync, but I never get the GPS location data in the exif. (I am using Samsung Galaxy S23 with latest OS)

**Comment by tpCodeX** [comment]
Hi! I'm working on the SDK 50 and I have the same problem. 
I'm using the useMediaLibraryPermission hook, but when I call 'requestPermission', nothing happens! 

`const pickImage = async () => {
    if(status?.granted!==true){
      const givedPermission=await ImagePicker.getMediaLibraryPermissionsAsync()
    if(givedPermission.granted===true){
      let userImage = await ImagePicker.launchImageLibraryAsync({
        mediaTypes:ImagePicker.MediaTypeOptions.Images,
        allowsEditing:true,
        aspect:[4,3],
        quality:1
      })
      if(!userImage.canceled){
        setImageSrc(userImage.assets[0].uri)
        setPickedImage(userImage)
        // let format = pickedImage.assets[0].fileName?.split(".")[1]
        // pickedImage.assets[0].fileName="profilePicture."+format
      }
    }
  }
  }`
  I'm trying this, but actually don't know what i'm doing wrong :C
  
  Hope someone could help me please! i'm stuck :/

**Comment by galamkoti** [comment]
Hi @tpCodeX 
try to explicitly get the permission using the below code , because the default permission seems to be not working
const {status:mediaStatus}= await ImagePicker.requestMediaLibraryPermissionsAsync();
    if(mediaStatus=='granted'){
      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        aspect: [1,1],
        quality: 0.25,
      });
      if (!result.canceled) {
        const newImages = [...images];
        newImages[selectedImageBox] = result.assets[0].uri;
        setImages(newImages);
      }
    }

**Comment by tpCodeX** [comment]
> Hi @tpCodeX try to explicitly get the permission using the below code , because the default permission seems to be not working
> 
> "const {status:mediaStatus}= await ImagePicker.requestMediaLibraryPermissionsAsync(); if(mediaStatus=='granted'){ const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, aspect: [1,1], quality: 0.25, }); if (!result.canceled) { const newImages = [...images]; newImages[selectedImageBox] = result.assets[0].uri; setImages(newImages); } }"

@galamkoti 
Thankyou!!!
