### ISSUE TITLE
Production app crash: No method delimiterOffset in class Lokhttp3/internal/Util

### ISSUE THREAD

**Issue by chvanlennep** [expo/expo#16552]
### Summary

Expo SDK44, ejected to bare workflow

I have this production android app crash which has been frustratingly difficult to reproduce, but is being reported by Sentry very frequently:

_No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in base.apk!classes3.dex)_

It seems to only happen when a user updates our app to a newer version via the play store.

Looking through our dependencies, I've found the following packages depend on okhttp3:

- React Native (0.64.3): okhttp3 / okhttp3-url-connection : 3.12.12
- expo-file-system (13.1.4): okhttp3 / okhttp3-url-connection : 3.10.0
- expo-updates (0.11.6): okhttp3 / okhttp3-url-connection: 3.12.1
- exoplayer (2.13.2): okhttp3: Taken from RN default (3.12.12)

I am wondering if these differing versions could be the culprit?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: bare

### Reproducible demo

A production app crash which has been difficult to reproduce locally with our own physical devices or emulators. Not specific to an API level or particular device.

**Comment by computerjazz** [comment]
I'm seeing the same thing, did you find a fix?
