### ISSUE TITLE
[docs] Expo "schemes" and makeRedirectUri

### ISSUE THREAD

**Issue by foxtree** [expo/expo#16554]
### Summary

* Is it expected that the `https://auth.expo.io` proxy URLs should work as a redirect in "Standalone" apps, eg: TestFlight?

* What is meant by "it can't be updated with an update," below?   (Does this mean that if a scheme was specified for a TestFlight build, it can't be updated?)

>[Usage in standalone apps](https://docs.expo.dev/versions/latest/sdk/auth-session/#usage-in-standalone-apps)
app.json
```
{
  "expo": {
    "scheme": "mycoolredirect"
  }
}
```
>
> In order to be able to deep link back into your app, you will need to set a scheme in your project app.config.js, or app.json, and then build your standalone app (it can't be updated with an update). If you do not include a scheme, the authentication flow will complete but it will be unable to pass the information back into your application and the user will have to manually exit the authentication modal (resulting in a cancelled event).

Strangely, it seems the following to works in TestFlight, but it does not work if the scheme is omitted from here and/or `app.config.ts`:

```
const redirectUri = makeRedirectUri({
  useProxy: true,
  native: `https://auth.expo.io/@${EXPO_OWNER}/${EXPO_SLUG}`,
  // native: `${BUNDLE_IDENTIFIER}://`,
  scheme: `${BUNDLE_IDENTIFIER}`, // scheme specified in app.config.ts
});

```

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/auth-session/

**Comment by alessandrocapra** [comment]
Still relevant and not clear, can someone please clarify?
