### ISSUE TITLE
Device Motion orientation fixed north would improve app development

### ISSUE THREAD

**Issue by andrewbest** [expo/expo#1655]
Core Motion allows you to have a fixed frame of reference for rotation. Since we are moving the camera around in a 3D world, a fixed frame of reference is necessary to know which orientation the camera is pointing in the world. For example, you would want to know exactly what direction you are facing and angle within a three.js world. Currently, the X rotation is arbitrary and changes when reloading the app.

This change would effect Dangerzone DeviceMotion rotation.

In the file: expo/ios/Exponent/Kernel/Services/EXSensorManager.m

Line 199:
startDeviceMotionUpdatesUsingReferenceFrame:CMAttitudeReferenceFrameXArbitraryCorrectedZVertical

That should be changed to:
startDeviceMotionUpdatesUsingReferenceFrame:CMAttitudeReferenceFrameXTrueNorthZVertical

This would solve the problem of https://github.com/expo/expo/issues/1633.

**Comment by schazers** [comment]
Thank you for your many detailed reports!

**Comment by andrewbest** [comment]
It looks like camera.getWorldDirection() can give good results for three.js. This perhaps is still something to think about for other applications.

**Comment by andrewbest** [comment]
If someone really wants this they can change it in a detached project. Closing the case.
