### ISSUE TITLE
Stripe & EAS : CompileSwiftSources error

### ISSUE THREAD

**Issue by AleksCallebat** [expo/expo#16577]
### Summary

Hello,

I have Stripe installed in my project using 
`expo install @stripe/stripe-react-native`

I have checked whether I had any other stripe installation going on, to no avail.

When I run `eas build -p ios`, I get a compilation error at the "run FastLane" stage : `
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Stripe' from project 'Pods')`

and 
`CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoModulesCore' from project 'Pods')`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: managed

### Reproducible demo

import { useStripe } from '@stripe/stripe-react-native';

**Comment by AleksCallebat** [comment]
Also, it runs smoothly using `expo start` on a simulator or on a phone using expo, just bugs when deploying. It builds with an expo build:ios, but the submitted binary get stuck in splash screen and I haven't been able to debug this since I couldn't replicate the error

**Comment by BerkeAras** [comment]
- same error -
-

**Comment by hanburger97** [comment]
Anyone resolved this?

**Comment by AleksCallebat** [comment]
So I eventually solved it with some obscure thread : there was a space in the folder name, which isn't supported (go and guess that this is the issue based on the error^^). 
After removing the space the error disappeared.

**Comment by hanburger97** [comment]
which file did you remove the space? and do you still have the link to the obscure thread?
thanks so much @AleksCallebat

**Comment by jenniferleelowry** [comment]
It was Target Support Files, I think 
/ios/Pods/Target Support Files
