### ISSUE TITLE
expo-yarn-workspaces audits critical due to immer version

### ISSUE THREAD

**Issue by wmcheung** [expo/expo#16573]
I'm using `expo-yarn-workspaces` v.1.7.0 in my project and ran `yarn audit --level critical` 

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Prototype Pollution in immer                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ immer                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=9.0.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ expo-yarn-workspaces                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ expo-yarn-workspaces > @expo/webpack-config >                │
│               │ react-dev-utils > immer                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1054457                     │

```

I followed the path according to the audit and @expo/webpack-config is not using the latest `react-dev-utils` version.
The latest `react-dev-utils` already uses the patched immer version.

https://github.com/expo/expo-cli/blob/main/packages/webpack-config/package.json
https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/package.json#L68

According to https://security.snyk.io/vuln/SNYK-JS-IMMER-1540542, it exposes a few types of attacks that could cause major problems.

Can this issue be resolved by version bumping @expo/webpack-config to use the latest `react-dev-utils` and have expo-yarn-workspaces use the latest version of @expo/webpack-config?

**Comment by byCedric** [comment]
Hi @wmcheung! Unfortunately, I believe the later versions of `react-dev-utils` is missing a lot of functionality that we require (but I might be mistaken here). Upgrading this would be very difficult. The attack vectors in these types of audits, especially related to development packages, are usually non-applicable. I would recommend [reading the post Dan Abramov wrote some time ago](https://overreacted.io/npm-audit-broken-by-design/). In this case, `react-dev-utils` only run on your machine and only you have access to your local machine. If you don't DDoS yourself, you should be fine. The package version isn't installed in the bundle from a binary.

If this is a blocker for you, I would recommend [checking out our improved monorepo support](https://docs.expo.dev/guides/monorepos/). Starting from SDK 43, you no longer need `expo-yarn-workspaces` to use Expo projects inside monorepos. It kind-of avoids this issue from this package, but it might still be installed from other sources. Either way, it could be worth checking this out as a workaround.

Hope this helps!

**Comment by wmcheung** [comment]
Hi @byCedric thanks for replying. All makes sense now! We can close this issue 😊
