### ISSUE TITLE
simple WebBrowserOpenOptions ignored in openAuthSessionAsync on ios 11+

### ISSUE THREAD

**Issue by o5faruk** [expo/expo#16580]
### Summary

> If there is no native AuthSession implementation available (which is the case on Android) these params will be used in the browser polyfill. If there is a native AuthSession implementation, these params will be ignored.

As stated in documentation, the options will be ignored in ios 11+ because it has native implementation available. The issue is that simple option such as `dismissButtonStyle` cant be changed from `cancel` to `done` or `controlsColor` cant be changed to custom color.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

> expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.3.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
      Watchman: 2021.09.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.5 => 43.0.5 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.4 => 0.66.4 
    Expo Workflow: bare

### Reproducible demo

        await WebBrowser.openAuthSessionAsync("https://expo.dev/", `https://expo.dev/`, {
            dismissButtonStyle: "close",
            controlsColor: "#ffffff",
            readerMode: true,
            toolbarColor: "#ffffff",
        });

**Comment by rafabulsing** [comment]
Still a problem in SDK 52 :(
