### ISSUE TITLE
expo build:ios not working

### ISSUE THREAD

**Issue by matheusmirandaferreira** [expo/expo#16598]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by matheusmirandaferreira** [comment]
### Error
I ran the command expo build:ios and got an internal server error from apple
`Apple 403 detected - Access forbidden`

### Environment

```
  Expo CLI 5.3.0 environment info:
    System:
      OS: Ubuntu 20.04.2 LTS 
    Binaries:
      Node: 14.18.2 
      yarn: 1.22.15 
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0
      react: 17.0.1
      react-native: 0.64.3
    Expo Workflow: managed
```

**Comment by abumalick** [comment]
You probably need to accept changes in the terms and condition from apple. You should try to connect to apple developer website with the owner account.

**Comment by byCedric** [comment]
I think what @abumalick said is right, it's likely an issue with your Apple account. I would recommend taking a look at https://appstoreconnect.apple.com/ and see if there are things you need to accept or confirm.
