### ISSUE TITLE
Disable hot/live in web project

### ISSUE THREAD

**Issue by drpiou** [expo/expo#16593]
### Summary

Disabling the hot replacement/live reload have no effect using a custom webpack mentioned in the Expo documentation. If I put `hot` and `liveReload` (and also `inline`) in a custom webpack, it still reloads on save.

For mobile devices like iOS and Android, it's pretty easy: you shake and toggle the correct option. But I'm surprised that this option does not exists in web (like `Press l | toggle Live reload` or `Press h | toggle HMR`).

The reason why I want to disable hot/live are because I use some instances of the same page (like I open once localhost:19006 in Chrome and Safari to test two users) and so it will refresh constantly even if I'm not in front of the page (I mean, I go to my code, edit it, save it -> pages refresh, then edit again and save again -> pages refresh again, and so on... until I finally go to one of my browser to check the changes).

I mean, this produces a lot of unnecessary stuff: refreshes, cpu usage, initial requests, ... Especially when it comes to work on a webapp, not just a simple website with static data.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

44.0.2

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.n/bin/node
      Yarn: 1.22.17 - ~/.n/bin/yarn
      npm: 6.14.15 - ~/.n/bin/npm
      Watchman: 2022.03.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 28, 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.19 => 0.16.19
      expo: ~44.0.2 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

- Start an expo project with bare workflow.
- Add "webpack.config.js" using `expo customize:web`.
- Edit "webpack.config.js":
  - `config.devServer.hot = false;`
  - `config.devServer.inline = false;`
  - `config.devServer.liveReload = false;`
- Run web using `expo web --dev`.
- Change something in your code, page will still refresh.

**Comment by byCedric** [comment]
Hi @drpiou! The main difference between web and native hot reloads is the place where this is configured. On Metro, we can disable it from the client-side (the app/phone), but on web (webpack) we need to change the configuration instead. Currently, we use [this plugin to get hot reload working](https://github.com/expo/expo-cli/blob/main/packages/webpack-config/src/webpack.config.ts#L469-L470). You have two options to change this behavior:

1. Start webpack in production mode to disable it when you don't need it.
2. Filter out the `HotModuleReplacementPlugin` from `webpack` inside the plugins array to remove hot reload from the config. Something like this should do that:
```js
const { HotModuleReplacementPlugin } = require('webpack');
...
config.plugins = config.plugins.filter(plugin => !(plugin instanceof HotModuleReplacementPlugin));
```

Hope this helps!

**Comment by drpiou** [comment]
Hello @byCedric, many thanks for your help. It does prevent the hot reloading, which is what I needed. Sorry for the late reply, this can be closed :)
