### ISSUE TITLE
expo-dev-launcher plugin inject code to AppDelegate everytime when run prebuild

### ISSUE THREAD

**Issue by XHMM** [expo/expo#16606]
### Summary

I created an expo v44 project and installed `expo-dev-client`,
when I runned `expo prebuild -p ios` multiple times, I found that this code was inject repeatly:
<img width="942" alt="image" src="https://user-images.githubusercontent.com/24786522/158024873-62d2d96d-d772-4180-a7d1-1fabe274eb9f.png">
I found the issue may caused by [expo-dev-launcher](https://github.com/expo/expo/blob/62af5d5acbbb451671821bcfb9e561222d8e32bf/packages/expo-dev-launcher/plugin/src/withDevLauncherAppDelegate.ts#L33), the extra `$&` made `appDelegate.includes(DEV_LAUNCHER_APP_DELEGATE_ON_DEEP_LINK)` always return `false`?

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo-dev-client: "~0.8.4"

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 31.0.0
        System Images: android-30 | Google Play Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: Arctic Fox 2020.3.1 Patch 4 Arctic Fox 2020.3.1 Patch 4
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo

1. `expo init`
2. `npm i expo-dev-client`
3. `expo prebuild -p ios` # run this command multiple times

view your `AppDelegate.m` file, you will find this code exists multiple times, it should only exist once 
```  
#if defined(EX_DEV_LAUNCHER_ENABLED)
  if ([EXDevLauncherController.sharedInstance onDeepLink:url options:options]) {
    return true;
  }
```

**Comment by Yonom** [comment]
Related https://github.com/expo/expo-cli/issues/3961#issuecomment-961498737

**Comment by tcdavis** [comment]
In the meantime, you can pass `--clean` to `expo prebuild` to avoid the issue as @Yonom points out 🙏

**Comment by hirbod** [comment]
I can confirm @ajsmth comment that it does not break - it's just a bit annoying. While I was debugging I found out that I was doing something very similar with and dangerous config plug-in I've wrote.. just found out that I have added my snippet 300 times (I am working on the app quite a while without ever recreating the project with --clean). 😀
