### ISSUE TITLE
Pedometer Module: Android - watchStepCount does not update - Permission is not being requested correctly.

### ISSUE THREAD

**Issue by lqze** [expo/expo#16605]
### Summary

Expected behaviour:

Value of `stepCount` should increase when device is physically moved. Walking with the device in a short distance (e.g., around a 15m^2 room) should trigger the step count to update as per its subscription.

Actual behaviour:

Permission will state granted.
However, `stepCount` will not increase. 
Calling `Pedometer.requestPermissionAsync()` will return `granted`.

Additional notes:

It seems like the only solution people have come up with is ejecting from Expo.
I believe this is a worst-case scenario, and at the very least Expo docs should be updated to reflect incompatibility with Android.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Run `expo start`
Or view through provided snack.

### Reproducible demo

https://snack.expo.dev/@humaan/android-pedometer-expo-sdk44

Run this snack on your physical device, or make a new project using the code for a very simple repro.

This is the code ripped straight from the documentation (minus the `styles`) and removed `getStepCount` as it is documented as not supported.

**Comment by lqze** [comment]
Update:

After further testing, I am 99.99% certain this is to do with Android's `ACTIVITY_RECOGNITION` permission not being permitted, as a result of it not being requested.

There is no prompt for this permission to come up during the lifecycle of attempting to access the Pedometer this way.

Similar to [Issue#13131](https://github.com/expo/expo/issues/13131#issuecomment-880841231), by ejecting from `expo` and using a third-party permissions module, I am able to successfully get a request/prompt/dialog window for **Activity Recognition** from the application. 

Using `pedometer` from `expo-sensor` then works once the dialogue window has granted permission.

**Comment by lqze** [comment]
Still broken.

Docs should be updated at the very least.

**Comment by remobaer** [comment]
@lqze any updates on this?

**Comment by lqze** [comment]
> @lqze any updates on this?

It still doesn't work. 

The expo usage example implies permissions should be granted but they are not. If you can actually grant ACTIVITY_RECOGNITION (e.g., with rn permission handler) then it will work.

**Comment by remobaer** [comment]
> > @lqze any updates on this?
> 
> It still doesn't work.
> 
> The expo usage example implies permissions should be granted but they are not. If you can actually grant ACTIVITY_RECOGNITION (e.g., with rn permission handler) then it will work.

Hello @lqze , thanks for the quick reply.


I am able to get  {"android.permission.ACTIVITY_RECOGNITION": "granted"}, and the step tracker also works on certain android phones, but e.g Samsung A30 (Android 11) doesn't return anything (Pedometer.watchStepCount()). 

Did did you manage to get it working on your side? is this an expo issue?

**Comment by lqze** [comment]
Title for this issue should potentially be changed.

The permission request window is not being prompted.

If you call `Pedometer.requestPermissionsAsync()`, it will not ask for permission from the user. Tested on a Samsung Galaxy S20+, Samsung A12, and a Huawei P30.

> I am able to get {"android.permission.ACTIVITY_RECOGNITION": "granted"}, and the step tracker also works on certain android phones, but e.g Samsung A30 (Android 11) doesn't return anything (Pedometer.watchStepCount()).

As mentioned in initial issue post, I can get the same result. I think it might be due to this https://github.com/expo/expo/blob/sdk-44/packages/expo-sensors/src/Pedometer.ts#L78-L79

**Comment by remobaer** [comment]
> Title for this issue should potentially be changed.
> 
> The permission request window is not being prompted.
> 
> If you call `Pedometer.requestPermissionsAsync()`, it will not ask for permission from the user. Tested on a Samsung Galaxy S20+, Samsung A12, and a Huawei P30.
> 
> > I am able to get {"android.permission.ACTIVITY_RECOGNITION": "granted"}, and the step tracker also works on certain android phones, but e.g Samsung A30 (Android 11) doesn't return anything (Pedometer.watchStepCount()).
> 
> As mentioned in initial issue post, I can get the same result. I think it might be due to this https://github.com/expo/expo/blob/sdk-44/packages/expo-sensors/src/Pedometer.ts#L78-L79

Interesting find. is it then necessary to use `Pedometer.requestPermissionsAsync()`?

I've currently implemented it via  `PermissionsAndroid.request()`, but yeah, same result

**Comment by lqze** [comment]
`PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACTIVITY_RECOGNITION)` is only achievable in the bare workflow, as you need RN 0.68 as a minimum. Managed expo cannot make use of it as current SDK is tied to RN 0.64

**Comment by lqze** [comment]
@Jleeowl I feel like that would definitely be the culprit.

**Comment by Jleeowl** [comment]
Further updates in my testing, since I am using `eas build` over the classic `expo build` which gives me access to the `config-plugins`.

Specifically, referring to this section of the documentation, https://docs.expo.dev/guides/config-plugins/#modifying-the-androidmanifestxml

I managed to modify the `AndroidManifest.xml` to include the required permission tag (i.e., `<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />`) in the resulting Android build/package.

With that, I can now see the corresponding permission in the application settings, and manually enable it for my application. This results in the pedometer working as intended.
![a91d5b90-e923-48d5-bf86-60db121eeb29](https://user-images.githubusercontent.com/5959650/162174645-42f7db59-8cc3-48c2-b570-76d670ebd6de.jpg)

However, as originally mentioned by @lqze. On the implementation level, `Pedometer.requestPermissionAsync()` does not seem to prompt the user for runtime permission as it should, and just returns `granted` even when the permission is denied on the application level.

**Comment by ahmad-crossplatform** [comment]
So in short we cannot have this in managed app right ? that is a bummer . it would be nice to have Permissions like as an expo module so developers could stay in their expo go zone .

**Comment by JohnBerd** [comment]
We can get ACTIVITY_RECOGNITION permissions by adding ACTIVITY_RECOGNITION in the permission array in app.json.
So no need for an EAS build for that.

Don't use com.google.android.gms.permission.ACTIVITY_RECOGNITION like it is written in the [documentation](https://docs.expo.dev/versions/latest/config/app/) because it doesn't work.

I am just stuck at asking this permission directly in the app. It seems to be impossible with Expo and I have to do it manually like @Jleeowl did

**Comment by kul-sudo** [comment]
Any updates?

**Comment by vikramsingh13** [comment]
Any updates to this? Pedometer.requestPermissionsAsync() is still returning granted but Pedometer.watchStepCount() is not going up

**Comment by RoyalHippopotamus** [comment]
Any news here?

**Comment by superyarik** [comment]
looks like problem in all expo-sensors modules:

```
const dm = await DeviceMotion.getPermissionsAsync();
    console.log(dm);
    const ac = await Accelerometer.getPermissionsAsync();
    console.log(ac);
    const br = await Barometer.getPermissionsAsync();
    console.log(br);
    const gs = await Gyroscope.getPermissionsAsync();
    console.log(gs);
    const ls = await LightSensor.getPermissionsAsync();
    console.log(ls);
    const mg = await Magnetometer.getPermissionsAsync();
    console.log(mg);
    const mg2 = await MagnetometerUncalibrated.getPermissionsAsync();
    console.log(mg2);
    const pd = await Pedometer.getPermissionsAsync();
    console.log(pd);
```

all result is 
`{"canAskAgain": true, "expires": "never", "granted": true, "status": "granted"}`

but if we check 
```
    PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.ACTIVITY_RECOGNITION).then((permissionStatus) => {
        console.log(permissionStatus);
    });
```
we have `false`

**Comment by NicKZ-gene** [comment]
> Ok so the solution is working fine for me (thanks @JohnBerd and @Jleeowl for the inspiration), I'm using Expo Managed SDK 46 and @expo-config-plugin. **I did not make tests on a wide set of Android devices**.
> 
> Create a new file where you want in your project folder architecture. I have it directly in the root folder. Name it "something.plugin.js" (I named it android-manifest.plugin.js). And fill it with this :
> 
> ```
> const { withAndroidManifest } = require('@expo/config-plugins');
> 
> module.exports = function androiManifestPlugin(config) {
>   return withAndroidManifest(config, async (configProps) => {
>     const androidManifest = configProps.modResults.manifest;
> 
>     androidManifest.$ = {
>       ...androidManifest.$,
>       'xmlns:tools': 'http://schemas.android.com/tools',
>     };
> 
>     const activityPerm1 = { $: { 'android:name': 'android.permission.ACTIVITY_RECOGNITION' } };
>     const activityPerm2 = { $: { 'android:name': 'com.google.android.gms.permission.ACTIVITY_RECOGNITION' } };
> 
>     androidManifest['uses-permission'].push(activityPerm1);
>     androidManifest['uses-permission'].push(activityPerm2);
> 
>     return configProps;
>   });
> };
> ```
> 
> Finally, just add this in your app.config.js or app.json in the plugin area :
> 
> ```
> plugins: [
>       './android-manifest.plugin.js',
>     ],
> ```
> 
> Build your app and enjoy. You can now use following lib to check if Activity Recognition is granted or not, and if not then request it : `import { PermissionsAndroid } from 'react-native';` OR `import GoogleFit from 'react-native-google-fit';` OR `anything else`

I have tried this way to get the permission, but the permission message still does not pop up. Has anyone tried this solution and solved the problem?

**Comment by superyarik** [comment]
@NicKZ-gene it's possible that you forgot to delete the "android" and "ios" folders after that, run the command "npx expo prebuild", and rebuild the application?

As for myself, I switched to using the "react-native-permissions" package for permissions flow, because similar functions in the expo-sensor package do not work for me.

A minor configuration in the package.json file is needed.
```
"reactNativePermissionsIOS": [
  "Motion"
],
"scripts": {
  ...
  "eas-build-post-install": "npx react-native setup-ios-permissions && npx pod-install",
...
}
```

And now we can read and request permissions.
```
import { check, PERMISSIONS, RESULTS, request } from 'react-native-permissions';

export const getMotionPermissionsAsync = async () => {
    try {
        let res;
        if (IS_IOS) {
            res = await check(PERMISSIONS.IOS.MOTION);
        } else {
            res = await check(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION);
        }
        return res;
    } catch (error) {
        return Promise.reject();
    }
};

export const isMotionAvailableAsync = async () => {
    try {
        return (await getMotionPermissionsAsync()) !== RESULTS.UNAVAILABLE;
    } catch (error) {
        return false;
    }
};

export const requestMotionPermissionsAsync = async () => {
    try {
        let res;
        if (IS_IOS) {
            res = await request(PERMISSIONS.IOS.MOTION);
        } else {
            res = await request(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION, rationale);
        }
        return res;
    } catch (error) {
        return null;
    }
};
```

**Comment by NicKZ-gene** [comment]
> @NicKZ-gene it's possible that you forgot to delete the "android" and "ios" folders after that, run the command "npx expo prebuild", and rebuild the application?
> 
> As for myself, I switched to using the "react-native-permissions" package for permissions flow, because similar functions in the expo-sensor package do not work for me.
> 
> A minor configuration in the package.json file is needed.
> 
> ```
> "reactNativePermissionsIOS": [
>   "Motion"
> ],
> "scripts": {
>   ...
>   "eas-build-post-install": "npx react-native setup-ios-permissions && npx pod-install",
> ...
> }
> ```
> 
> And now we can read and request permissions.
> 
> ```
> import { check, PERMISSIONS, RESULTS, request } from 'react-native-permissions';
> 
> export const getMotionPermissionsAsync = async () => {
>     try {
>         let res;
>         if (IS_IOS) {
>             res = await check(PERMISSIONS.IOS.MOTION);
>         } else {
>             res = await check(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION);
>         }
>         return res;
>     } catch (error) {
>         return Promise.reject();
>     }
> };
> 
> export const isMotionAvailableAsync = async () => {
>     try {
>         return (await getMotionPermissionsAsync()) !== RESULTS.UNAVAILABLE;
>     } catch (error) {
>         return false;
>     }
> };
> 
> export const requestMotionPermissionsAsync = async () => {
>     try {
>         let res;
>         if (IS_IOS) {
>             res = await request(PERMISSIONS.IOS.MOTION);
>         } else {
>             res = await request(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION, rationale);
>         }
>         return res;
>     } catch (error) {
>         return null;
>     }
> };
> ```

Thanks for the helping. I am working on the android right now and I do not have ios and android files. My files structure is 
<img width="201" alt="截屏2023-10-12 下午8 39 10" src="https://github.com/expo/expo/assets/57031199/22098c4d-0bc0-48d6-8df5-a4deb4432abf">
And  I wrote the request permission like this:

```
const requestCameraPermission = async () => {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACTIVITY_RECOGNITION,
      {
        title: 'Cool Exercise App Activity Recognition Permission',
        message:
          'Cool Exercise App needs access to your Activity Data ' +
          'so you can track the activity of user',
        buttonNeutral: 'Ask Me Later',
        buttonNegative: 'Cancel',
        buttonPositive: 'OK',
      },
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log('You can use the activity permission');
    } else {
      console.log('activity permission denied');
    }
 
};
```
However, I still cannot get permission.

**Comment by superyarik** [comment]
@NicKZ-gene did you rebuild your application? If yes, I can suggest the following: check the full list of permissions for your APK file - if it does not contain android.permission.ACTIVITY_RECOGNITION and com.google.android.gms.permission.ACTIVITY_RECOGNITION, then most likely the problem lies in the plugin or how it is connected to Expo.

**Comment by NicKZ-gene** [comment]
> @NicKZ-gene did you rebuild your application? If yes, I can suggest the following: check the full list of permissions for your APK file - if it does not contain android.permission.ACTIVITY_RECOGNITION and com.google.android.gms.permission.ACTIVITY_RECOGNITION, then most likely the problem lies in the plugin or how it is connected to Expo.

Sorry I am so new of developing the expo go project. Where I can find the APK file?
Right now I try to solve the ACTIVITY_RECOGNITION like this:
1. I created the android-manifest.plugin.js file and write this
`const { withAndroidManifest } = require("@expo/config-plugins");

module.exports = function androiManifestPlugin(config) {
  return withAndroidManifest(config, async (configProps) => {
    const androidManifest = configProps.modResults.manifest;

    androidManifest.$ = {
      ...androidManifest.$,
      "xmlns:tools": "http://schemas.android.com/tools",
    };

    const activityPerm1 = {
      $: { "android:name": "android.permission.ACTIVITY_RECOGNITION" },
    };
    const activityPerm2 = {
      $: {
        "android:name":
          "com.google.android.gms.permission.ACTIVITY_RECOGNITION",
      },
    };

    androidManifest["uses-permission"].push(activityPerm1);
    androidManifest["uses-permission"].push(activityPerm2);

    return configProps;
  });
};
`

2. I added this file into app.js and also add the permission into app.js\
`{
  "expo": {
    "name": "MoveMate",
    "slug": "MoveMate",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./src/assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./src/assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.anonymous.MoveMate"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./src/assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "permissions": [
        "android.permission.ACTIVITY_RECOGNITION"
      ],
      "package": "com.anonymous.MoveMate"
    },
    "web": {
      "favicon": "./src/assets/favicon.png"
    },
    "plugins": ["./android-manifest.plugin.js"]
  }
}`

3. I requested the permission by using the PermissionAndroid like I said before

But I still cannot get the permission. Could you tell me which part I need to solve to get the permission?
My expo version is `"expo": "~49.0.10",`
My react native version is ` "react-native": "0.72.5",`
My android version is API 29 which is android 10.

**Comment by superyarik** [comment]
@NicKZ-gene  It seems like you're trying to do this in the Expo Go app, but adding permissions requires building your own standalone app with dev client enabled. It might be helpful for you to read about EAS Build and adding third-party modules to your app.

**Comment by NicKZ-gene** [comment]
> @NicKZ-gene It seems like you're trying to do this in the Expo Go app, but adding permissions requires building your own standalone app with dev client enabled. It might be helpful for you to read about EAS Build and adding third-party modules to your app.

Thank you so much for the helping! I am working in eas build right now and trying to add the APK file into the physical device to check whether the permission works or not. However, do I need to install APK to the physical device every time to check the functionality?

**Comment by superyarik** [comment]
@NicKZ-gene each change in the native part of the application (such as permissions, packages that use native code) requires rebuilding the application and installing it on the device(emulator).

**Comment by Jleeowl** [comment]
> Ok so the solution is working fine for me (thanks @JohnBerd and @Jleeowl for the inspiration), I'm using Expo Managed SDK 46 and @expo-config-plugin. **I did not make tests on a wide set of Android devices**.
> 
> Create a new file where you want in your project folder architecture. I have it directly in the root folder. Name it "something.plugin.js" (I named it android-manifest.plugin.js). And fill it with this :
> 
> ```
> const { withAndroidManifest } = require('@expo/config-plugins');
> 
> module.exports = function androiManifestPlugin(config) {
>   return withAndroidManifest(config, async (configProps) => {
>     const androidManifest = configProps.modResults.manifest;
> 
>     androidManifest.$ = {
>       ...androidManifest.$,
>       'xmlns:tools': 'http://schemas.android.com/tools',
>     };
> 
>     const activityPerm1 = { $: { 'android:name': 'android.permission.ACTIVITY_RECOGNITION' } };
>     const activityPerm2 = { $: { 'android:name': 'com.google.android.gms.permission.ACTIVITY_RECOGNITION' } };
> 
>     androidManifest['uses-permission'].push(activityPerm1);
>     androidManifest['uses-permission'].push(activityPerm2);
> 
>     return configProps;
>   });
> };
> ```
> 
> Finally, just add this in your app.config.js or app.json in the plugin area :
> 
> ```
> plugins: [
>       './android-manifest.plugin.js',
>     ],
> ```
> 
> Build your app and enjoy. You can now use following lib to check if Activity Recognition is granted or not, and if not then request it : `import { PermissionsAndroid } from 'react-native';` OR `import GoogleFit from 'react-native-google-fit';` OR `anything else`

I am going to share a very crude sample, of a workaround that I use on some of my expo projects in order to get the Pedometer working for Android. Props to @jayveenW for suggesting this approach.

https://github.com/Jleeowl/expo-playground/tree/sample-expo-pedometer-app

Hope this helps anyone that is still struggling to make this package work on their project.

**Comment by NicKZ-gene** [comment]
Thanks for the helping. I finally get it to work right now. However, the watchStepCounts function is not updating very quickly. It looks like it will update when I actually stop in one position. Is it normal?

**Comment by naki2** [comment]
``I have done like @Jleeowl said, but it doesn't seem to work for me. When I do a build, I guess that it should trigger the Android system to display a permission request dialog, right? I'm requesting the permission and using the Pedometer.watchStepCount() in different parts of the code, I don't if that matters tho.
I'm asking the permission like this:
```
const requestPermission = async () => {
        try {
            console.log("request permissions")
            const result = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.ACTIVITY_RECOGNITION,
                {
                    title: "Pedometer Permission",
                    message: "This app requires permission to count your steps.",
                    buttonNeutral: "Ask Me Later",
                    buttonNegative: "Cancel",
                    buttonPositive: "OK",
                }
            );
            if (result === PermissionsAndroid.RESULTS.GRANTED) {
                setIsPermissionGranted(true);
            }
        } catch (error) {
            console.error("Error requesting permission:", error);
        }
    };
   useEffect(() => {
        requestPermission();
    }, [])
```
As you can see I don't want to ask for the permission and use the step count at the same moment, I don't know if that is possible.
Some idea of what is happening? Thanks a lot
