### ISSUE TITLE
Push Notifications return 'Not Found'

### ISSUE THREAD

**Issue by martsie** [expo/expo#1661]
Recently the exact same CURL script we were using before for Push notifications has stopped working with the api endpoint simply returning the text 'Not Found'.

```
curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '{
  "to": "ExponentPushToken[xxxxx]",
  "title":"Hi",
  "body": "This is a test push notification"
}'
```

I've also noticed the documentation now includes square brackets in the url for the CURL example which seems to break CURL.

**Comment by ide** [comment]
Hi - can you try including `accept: application/json` as well?

**Comment by martsie** [comment]
I have tried that as well and no luck. I've tried both in Postman and terminal, in Postman what's interesting is that I have the exact same configuration set up from around December where it was working fine - has anything changed since then? Does the response "Not Found" mean anything to Expo (as in is that returned by Expo somewhere?).

**Comment by martsie** [comment]
Aha I figured it out, some of the double quotes were being encoded as quote marks and postman's font wasn't distinguishing between them! If somebody else bumps into this issue in the future re write all your quotes manually and try again.

**Comment by IbrahimApp** [comment]
Just change your breckets ""

**Comment by divonelnc** [comment]
Hi, I am having the same issue. The request in POSTMAN returns "Not Found".

url: https://exp.host/--/api/v2/push/send

```
headers: {
        Accept: 'application/json',
        'Accept-encoding': 'gzip, deflate',
        'Content-Type': 'application/json',
      }
```
```
body: {
'to': 'ExponentPushToken[xxxxxx]',
'title': 'Title of the Notification',
'body': 'Body of the Notification'
}
```
I am not using double quotes so I don't think that's it

The token that I use is the one returned by `Notifications.getExpoPushTokenAsync()` in my react-native app.
