### ISSUE TITLE
[expo-background-fetch] Function never running, or running only for once

### ISSUE THREAD

**Issue by Oxrang3** [expo/expo#16620]
### Summary

I am creating an application where I want to sync the user's data after each minute (Like that in GMail , Discord etc). So I am using this code:

```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import * as BackgroundFetch from 'expo-background-fetch';
import * as TaskManager from 'expo-task-manager';

const BACKGROUND_FETCH_TASK = 'background-fetch';

// 1. Define the task by providing a name and the function that should be executed
// Note: This needs to be called in the global scope (e.g outside of your React components)
TaskManager.defineTask(BACKGROUND_FETCH_TASK, async () => {
  const now = Date.now();

  console.log(`Got background fetch call at date: ${new Date(now).toISOString()}`);

  // Be sure to return the successful result type!
  return BackgroundFetch.BackgroundFetchResult.NewData;
});

// 2. Register the task at some point in your app by providing the same name, and some configuration options for how the background fetch should behave
// Note: This does NOT need to be in the global scope and CAN be used in your React components!
async function registerBackgroundFetchAsync() {
  return BackgroundFetch.registerTaskAsync(BACKGROUND_FETCH_TASK, {
    minimumInterval: 60 * 1, // 1 minute
    stopOnTerminate: false, // android only,
    startOnBoot: true, // android only
  });
}

// 3. (Optional) Unregister tasks by specifying the task name
// This will cancel any future background fetch calls that match the given name
// Note: This does NOT need to be in the global scope and CAN be used in your React components!
async function unregisterBackgroundFetchAsync() {
  return BackgroundFetch.unregisterTaskAsync(BACKGROUND_FETCH_TASK);
}

export default function BackgroundFetchScreen() {
  const [isRegistered, setIsRegistered] = React.useState(false);
  const [status, setStatus] = React.useState(null);

  React.useEffect(() => {
    checkStatusAsync();
  }, []);

  const checkStatusAsync = async () => {
    const status = await BackgroundFetch.getStatusAsync();
    const isRegistered = await TaskManager.isTaskRegisteredAsync(BACKGROUND_FETCH_TASK);
    setStatus(status);
    setIsRegistered(isRegistered);
  };

  const toggleFetchTask = async () => {
    if (isRegistered) {
      await unregisterBackgroundFetchAsync();
    } else {
      await registerBackgroundFetchAsync();
    }

    checkStatusAsync();
  };

  return (
    <View style={styles.screen}>
      <View style={styles.textContainer}>
        <Text>
          Background fetch status:{' '}
          <Text style={styles.boldText}>
            {status && BackgroundFetch.BackgroundFetchStatus[status]}
          </Text>
        </Text>
        <Text>
          Background fetch task name:{' '}
          <Text style={styles.boldText}>
            {isRegistered ? BACKGROUND_FETCH_TASK : 'Not registered yet!'}
          </Text>
        </Text>
      </View>
      <View style={styles.textContainer}></View>
      <Button
        title={isRegistered ? 'Unregister BackgroundFetch task' : 'Register BackgroundFetch task'}
        onPress={toggleFetchTask}
      />
    </View>
  );
}

```

Here, when the background function is registered, the app runs that function only once, and somethimes it happens that it does not even fire that function. I guess that function should be called when the users exists the app or  sends it to the background? It does fire it, but only once. Is it natural, some bug or my mistake?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

5.3.0

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.16 undefined
      Shell: 3.3.1 - /usr/bin/fish
    Binaries:
      Node: 16.6.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/bin/yarn
      npm: 7.19.1 - /usr/local/bin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: managed
```

### Reproducible demo

The example has been taken for the docs - https://docs.expo.dev/versions/latest/sdk/background-fetch/

**Comment by JorensM** [comment]
I am having the same issue!

**Comment by Tran-Minh23** [comment]
Having the same issue, I copied code from the docs, and I couldn't even see any log message...

**Comment by JorensM** [comment]
@Oxrang3 it appears that android has a minimum interval of 15 minutes between running a background task. I don't have the time to test it yet, but maybe the task will run after 15 minutes.

**Comment by JorensM** [comment]
@Tran-Minh23 did you exit the application? The task only starts running when you exit your app.

**Comment by Tran-Minh23** [comment]
@JorensM So this background fetch only works when exit the application. I'm looking for a background task when the app is running

**Comment by JorensM** [comment]
@Tran-Minh23 you don't need expo-background-fetch module for that. You can just create a setInterval function.

**Comment by Tran-Minh23** [comment]
@JorensM Yeah, but I'm trying to implement expo-fetch. I exit and using the application, but no log shows.

**Comment by elly0t** [comment]
Similar case here, any help will be much appreciated

It was working before until I upgrade to Expo SDK 44. After that, the callback function in `.defineTask` never gets called.
I've checked the Expo task with `isTaskRegisteredAsync` and can confirm it's there

Here's my simplified code: 
```
ExpoTaskManager.defineTask('TASK_NAME', (data) => {
  console.log(data)
});

...

async function startRecordingLocations() {
  await ExpoLocation.startLocationUpdatesAsync('TASK_NAME')
}

// then triggers startRecordingLocations
```

**Comment by NadeemKhanFh** [comment]
its not working

**Comment by devstamenov** [comment]
Having the same Issue

**Comment by GHUApsynet** [comment]
As some people pointed out [https://github.com/expo/expo/issues/3582](here), it seems that the only way to have a working background task is to tie it with the _startLocationUpdatesAsync_ function.

An example very similar to the doc :

`import React from "react";
import { Button, View, StyleSheet } from "react-native";
import * as TaskManager from "expo-task-manager";
import * as Location from "expo-location";

const LOCATION_TASK_NAME = "background-location-task";
const FETCH_INTERVAL = 10;

const requestPermissions = async () => {
  const { status: foregroundStatus } =
    await Location.requestForegroundPermissionsAsync();
  if (foregroundStatus === "granted") {
    const { status: backgroundStatus } =
      await Location.requestBackgroundPermissionsAsync();
    if (backgroundStatus === "granted") {
      await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.BestForNavigation,
        timeInterval: FETCH_INTERVAL,
      });
    }
  }
};

const PermissionsButton = () => (
  <View style={styles.container}>
    <Button onPress={requestPermissions} title="Enable background location" />
  </View>
);

TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }: any) => {
  if (error) {
    console.log(error);
    return;
  }
  if (data) {
    console.log("Here");
    console.log(data.locations);
  }
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
});

export default PermissionsButton;
`

This should display a "Here" and locations data in your console, every 10 seconds.

**Comment by GHUApsynet** [comment]
As a comment pointed out in #3582, it seems that to create a background task, you need to tie it with the _startLocationUpdatesAsync_.

Here's an example that worked for me :

```
import React from "react";
import { Button, View, StyleSheet } from "react-native";
import * as BackgroundFetch from "expo-background-fetch";
import * as TaskManager from "expo-task-manager";
import * as Location from "expo-location";

const LOCATION_TASK_NAME = "background-location-task";
const FETCH_INTERVAL = 5000;

const requestPermissions = async () => {
  const { status: foregroundStatus } =
    await Location.requestForegroundPermissionsAsync();
  if (foregroundStatus === "granted") {
    const { status: backgroundStatus } =
      await Location.requestBackgroundPermissionsAsync();
    if (backgroundStatus === "granted") {
      await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.BestForNavigation,
        timeInterval: FETCH_INTERVAL,
      });
    }
  }
};

const PermissionsButton = () => (
  <View style={styles.container}>
    <Button onPress={requestPermissions} title="Enable background location" />
  </View>
);

TaskManager.defineTask(LOCATION_TASK_NAME, async ({ data, error }: any) => {
  if (error) {
    console.log(error);
    return;
  }
  if (data) {
    try {
      const now = Date.now();
      const currentTime = new Date(now).toISOString();
      console.log(currentTime);
      return currentTime
        ? BackgroundFetch.BackgroundFetchResult.NewData
        : BackgroundFetch.BackgroundFetchResult.NoData;
    } catch (err) {
      console.log(err);
      return BackgroundFetch.BackgroundFetchResult.Failed;
    }
  }
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
});

export default PermissionsButton;
```

This should display the current time in the console. 

Note : If you put the app was in the background, it's not gonna be displayed in the console because your console will be disconnected from your device. So instead, I made a task that send a GET request toward my server, and while the app was in the background, my server's logs indicated that the request were still coming in.

**Comment by Hosam-hsm** [comment]
I'm facing the same issue on expo 50.0.14. Background fetch function is not being executed upon registering it. But I am able to manually trigger the background fetch using Instruments app.

**Comment by Hosam-hsm** [comment]
Having the same Issue in expo 50.0.14. Asking permission for location to handle background fetch is not ideal.

**Comment by IlkhomKurbanov** [comment]
> @Tran-Minh23 you don't need expo-background-fetch module for that. You can just create a setInterval function with plain javascript.

setInterval will get supperessed right after app is backgrounded

**Comment by Beckmann0o** [comment]
The same thing is happening in my application, I define tasks with taskmanager and register them with bagground fetch. I can see that the task is registered but never executed. Could anyone solve it? I am using expo sdk 51

**Comment by Beckmann0o** [comment]
Could you share how you solved it, what is the instrument application? I can't run background fetch in expo work flow, I'm using sdk 51.

**Comment by Beckmann0o** [comment]
Could you share how you solved it, what is the instrument application? I can't run background fetch in expo work flow, I'm using sdk 51.

**Comment by Beckmann0o** [comment]
> Me enfrento al mismo problema en la expo 50.0.14. La función de recuperación en segundo plano no se ejecuta al registrarla. Pero puedo activar manualmente la búsqueda en segundo plano usando la aplicación Instruments.


Could you share how you solved the problem? Thank you so much !

**Comment by davidfrk** [comment]
Facing the same problem. I tested it on multiple devices; it works on some of them but never triggers or triggers only once on others. The original post describes it very well. Trying to find a clue as to what makes it work on some devices but not on others.

**Comment by kiorq** [comment]
Facing a similar issue, i suspect that the function isn't beling loaded properly, but i have no proper way to debug this... spent so much time on this already and I can't tell what is going on.

**Comment by chicomoedas2** [comment]
Hello, i scheduled a task that should ran each five minutes, and it did work when i run through Expo, but, when i build, it doesn't work, is there any permission that i should type  on my manifest that isn't on doc?

I'm currenlty on expo 50.0.19 and api level 34, and i used expo backgrounf fetch and expo task manager 

expo-background-fetch": "~11.8.1"
"expo-task-manager": "~11.7.3"



Is there any way to guarantee 100% sure that my task is gonna run, even ignoring the priority levels?
