### ISSUE TITLE
Can't get IOS notifications push token

### ISSUE THREAD

**Issue by thibaultfischer** [expo/expo#16622]
### Summary

When calling getDevicePushTokenAsync or getExpoPushTokenAsync on an ios device, The promise never resolved and never throw.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.11 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/thibaultfischer/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 30, 31
        Build Tools: 28.0.3, 29.0.2, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.3.0 => 8.3.0 
      expo: ^42.0.0 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
    Expo Workflow: bare

### Reproducible demo

export const registerForPushNotificationsAsync = async () => {
  try {
    if (Constants.isDevice) {
      const status = await getNotificationsPermissionStatus();
      if (status !== Permissions.PermissionStatus.GRANTED) {
        return;
      }
      const token = await Notifications.getExpoPushTokenAsync();
      return token.data;
    }
  } catch (err) {

Here we never go in the catch and we never reach the "return token.data" line

**Comment by DBarbero** [comment]
I'm having a similar issue with **getExpoPushTokenAsync** on a physical android device. This error shows up in the console:

`Expected a JSON response from server when fetching Expo token, received response: {"type":"default","status":200,"ok":true,"statusText":"","headers":{"map":{"content-length":"70","content-type":"application/json; charset=utf-8","date":"Tue, 15 Mar 2022 15:30:18 GMT","etag":"\"46-LTTgIrls+db17VIo6kM8J2ThgPU\"","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Accept-Encoding, Origin","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN"}},"url":"https://exp.host/--/api/v2/push/getExpoPushToken","bodyUsed":true,"_bodyInit":{},"_bodyText":"[object Blob]"}.
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:235815:18 in parseResponse$
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:26989:18 in tryCatch
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:27159:23 in Generator.invoke [as _invoke]
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:27031:22 in Generator.throw
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:26989:18 in tryCatch
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:27061:21 in invoke
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:27073:14 in <unknown>
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:31842:13 in tryCallOne
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:31943:16 in <unknown>
at http://192.168.0.120:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:32383:20 in <unknown>`

**Comment by dty717** [comment]
Enable the Push Notifications Capability
<img src ="https://docs-assets.developer.apple.com/published/dd2f56dbe9/f3327ebb-70be-4a12-9a76-b1a8badc0cd0.png"/>

reference:https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns

**Comment by clemaccountable** [comment]
@Kudo sorry to tag you but we're in desperate need of help here.
I'm experiencing the same issue and after putting some logs and a try catch in the expo-notifications module itself, it seems the `getDevicePushTokenAsync` function is the culprit. This is the one that never resolves, and also never throws an error.

```js
export default async function getExpoPushTokenAsync(options = {}) {
    try {
    const devicePushToken = options.devicePushToken || (await getDevicePushTokenAsync());
    } catch (e) {
      // this is never reached
    } finally {
      // this is never reached
    }
```

I've carefully followed the [expo setup guide](https://docs.expo.dev/push-notifications/push-notifications-setup/) all over again, as well as the [expo-notifications installation instructions](https://docs.expo.dev/versions/latest/sdk/notifications/).
Also had a look at [this issue](https://github.com/expo/expo/issues/7921) and [that one](https://github.com/expo/expo/issues/8757) but none of those have a clear solution.

The troubleshooting section of the expo-notifications page was also not helpful.

**Comment by clemaccountable** [comment]
After digging just a little further in `getDevicePushTokenAsync`, i've surrounded `nativeTokenPromise` with a try catch and got an error message:
```
[expo-notifications] Error encountered while updating the device push token with the server: {"errors":[{"code":"VALIDATION_ERROR","message":"\"deviceToken\" must be a string.","isTransient":false}]}
```

```js
    nativeTokenPromise = PushTokenManager.getDevicePushTokenAsync();
    try {
      devicePushToken = await nativeTokenPromise;
      nativeTokenPromise = null;
    } catch (e) {
      console.log('e', JSON.stringify(e));
    }
```

I didn't find any topic related to this error on the internet. Any idea where this error comes from?

**Comment by thibaultfischer** [comment]
Ok, found the problem : 
We are use Intercom react native library, and setting it up we added this line : 
<img width="906" alt="image" src="https://user-images.githubusercontent.com/92362985/172317743-b245a190-ebb2-4a7e-a6c4-0c34b2f66117.png">

But now the didRegisterForRemoteNotificationsWithDeviceToken is not returning anything, so the expo getDevicePushTokenAsync never resolves.....

**The solution :** 
**If you are using a third party library that asks you to implement something in didRegisterForRemoteNotificationsWithDeviceToken method, make sure to return to keep expo notifications working :** 
`return [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];`
<img width="933" alt="image" src="https://user-images.githubusercontent.com/92362985/172318348-ce3fc58b-8cd8-4e9d-af4b-1990da0cde9d.png">

**Comment by simon-tannai** [comment]
I got the same issue than @thibaultfischer: Intercom react library seems to have an issue with notification token. The fix proposed by @thibaultfischer is working fine:
In the file `ios/MyApp/AppDelegate.m`, I replaced:
```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    [IntercomModule setDeviceToken:deviceToken];
}
```
By:
```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    [IntercomModule setDeviceToken:deviceToken];
    return [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
```

Then, I updated the `getExpoPushTokenAsync()` params to add the `experienceId` and `applicationId`: 
```javascript
import { applicationId } from 'expo-application';

[...]

  const { data: expoPushToken } = await Notifications.getExpoPushTokenAsync({
    experienceId: '@my_company/my-project',
    applicationId,
    development: 'dev' === Constants.manifest.extra.ENVIRONMENT,
  });
```
