### ISSUE TITLE
Expo app crashes after launch on iOS when built locally with Turtle CLI

### ISSUE THREAD

**Issue by hudymvol** [expo/expo#16639]
### Summary

Hey,

I have recently faced a weird problem that's probably connected to the most recent breaking change in App Store described here (https://status.expo.dev/incidents/c52fybftz9z3).

I am using Turtle CLI to build an app locally, build succeeds, but the application is crashing almost immediately after launching.

When the application is build using classic builds (`expo build:ios`), it works fine.

As far as it was explained, the problem might be that builds are produced with the bitcode. Can Turtle CLI (or managed Expo app) be configured to produce builds without the bitcode?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.6

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 30
        Build Tools: 29.0.2, 29.0.3, 30.0.1
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.19 
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

### Reproducible demo

Steps to reproduce an issue:

```
// Step 1
APP_ENV="development" expo export --clear --dev --public-url http://127.0.0.1:8000

// Step 2
npx http-server -p 8000 dist

// Step 3
EXPO_IOS_DIST_P12_PASSWORD="<password>" turtle build:ios --team-id <team_id> --dist-p12-path <path> --provisioning-profile-path <path> --public-url http://127.0.0.1:8000/ios-index.json --allow-non-https-public-url --type simulator --output App.tar.gz 

// Step 4
tar xvzf App.tar.gz 

// Step 5 - Install app on currently opened iOS simulator
xcrun simctl install booted App.app/
```

After executing all the steps above, click on the application icon and notice splash screen is shown for approximately a second and then the application crashes.

In crash logs I can see:

```
Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer$
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean compare:]: nil a$
terminating with uncaught exception of type NSException
abort() called
```

**Comment by byCedric** [comment]
Hi @hudymvol! Yes, if you upgrade to `turtle-cli@0.25.0`, bitcode should be disabled. You can [check our changelog here](https://github.com/expo/turtle/blob/master/CHANGELOG.md#0250---2022-03-11). Assuming that's the issue, you should be able to build your app successfully. Let us know if it doesn't!

**Comment by hudymvol** [comment]
Hi @byCedric, thanks for a quick response! 

I have updated Turtle CLI to the latest version (`0.25.0`), executed the same steps as described above and still seeing the same error in a simulator.

Tried to set different values for `ios.debug` field in `app.json`, but still without any success.

**Comment by hudymvol** [comment]
@byCedric is it possible to reopen it?

Updating didn't help, maybe someone else experiences the same issue.

**Comment by byCedric** [comment]
Hi again @hudymvol! I can't seem to reproduce the issue you are experiencing. One thing to note is that I was using turtle-cli from scratch because I didn't have it installed yet. One thing you could try is purging the SDK 44 shell app from turtle, that should be installed at `~/.turtle/workingDir/ios/sdk44`. If you can remove this folder and try again, maybe that will fix it.

**Comment by hudymvol** [comment]
That seemed to help, I was able to successfully build clean Expo project, so obviously something is wrong on my side, thanks a lot for your time!
