### ISSUE TITLE
[expo-clipboard] causes expo build to fail

### ISSUE THREAD

**Issue by theafolayan** [expo/expo#16638]
### Summary

Trying to build a project with Expol Clipboard in use causes my build to fail with the following output

---------------------------

Compiling expo-clipboard Pods/EXClipboard » ClipboardModule.swift

❌  (node_modules/expo-clipboard/ios/EXClipboard/ClipboardModule.swift:11:5)

   9 |     name("ExpoClipboard")
  10 | 
> 11 |     function("getStringAsync") { () -> String in
     |     ^ cannot find 'function' in scope
  12 |       return UIPasteboard.general.string ?? ""
  13 |     }
  14 | 

❌  (node_modules/expo-clipboard/ios/EXClipboard/ClipboardModule.swift:38:5)

  36 |   @objc
  37 |   func clipboardChangedListener() {
> 38 |     sendEvent(onClipboardChanged, [
     |     ^ cannot find 'sendEvent' in scope
  39 |       "content": UIPasteboard.general.string ?? ""
  40 |     ])
  41 |   }
› Compiling expo-constants Pods/EXConstants » EXConstantsService.m
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'EXClipboard' from project 'Pods')
▸ 	CompileSwift normal arm64 /Users/expo/workingdir/build/node_modules/expo-clipboard/ios/EXClipboard/ClipboardModule.swift (in target 'EXClipboard' from project 'Pods')
▸ (2 failures)

---------------

I believe this is as a result of #15046  and #15004

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43.0.2

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2021.09.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 30, 32
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 32.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.67.3 => 0.67.3 
    npmGlobalPackages:
      eas-cli: 0.48.0
    Expo Workflow: managed
```

### Reproducible demo

```js
import * as Clipboard from 'expo-clipboard'; 
  const copyAddress = () => Clipboard.setString(address); 

 useEffect(() => {
    const subscription = Clipboard.addClipboardListener(({ content }) => {
      openAlert(`${content} copied!`);
      setTimeout(() => closeAlert(), 4000);
    });

    return () => {
      Clipboard.removeClipboardListener(subscription);
    };
  }, []);
```

**Comment by barthap** [comment]
You most likely have a version mismatch - in issue description you say you're using `Expo SDK 43.0.2`, but in package.json you have `expo@44.0.6`.

Which version of `expo-clipboard` do you have installed?
- `expo@44` is compatible with `expo-clipboard@~2.1.0`
- `expo@43` is compatible with `expo-clipboard@~2.0.3`
