### ISSUE TITLE
Task 'installDebug' not found in root project 'android'. Some candidates are: 'installDevDebug'.

### ISSUE THREAD

**Issue by nahidmbstu** [expo/expo#1665]
i have device connected and showing. but getting this error.

----------------> react-native run-android
Scanning folders for symlinks in /home/ubuntu/code/expos/apollo/node_modules (8ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Parallel execution with configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/ubuntu/Public/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in root project 'android'. Some candidates are: 'installDevDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.581 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by terribleben** [comment]
Hi, is your project an Expo project? a `create-react-native-app` project? Or just a plain React Native project?

**Comment by Manoj002** [comment]
Hello @terribleben ,
i do have same error and yes i have a create-react-native-app project which i ejected from expo

**Comment by ashutoshshubam** [comment]
@Manoj002 
i do have same error can you help.

**Comment by sergkulikovskyi** [comment]
+1, expo project, ejected using https://docs.expo.io/versions/latest/expokit/expokit.html, ios seems to work fine, but react-native run-android always returns this error

**Comment by sjchmiela** [comment]
Hey all! `react-native run-android` unfortunately isn't compatible with ExpoKit projects. To run Android ExpoKit project use `./run.sh` script in `android` directory. 🙂 (It runs `./gradlew :app:installDevMinSdkDevKernelDebug`.)

**Comment by Manoj002** [comment]
@ashutoshshubam, hello there i stopped working on expo, that time this was only the solution i had
