### ISSUE TITLE
Expo go Fast Refresh - non stop refreshing

### ISSUE THREAD

**Issue by rbq10** [expo/expo#16664]
### Summary

After running yarn add to update a library -  `react-native-keyboard-accessory` and starting up the app, expo go keep fast refreshing non-stop until the app crashes on both IOS and Android. 

Has anyone else faced this problem before?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

-

### Reproducible demo

yarn add react-native-keyboard-accessory

That's literally all I did.

**Comment by zachrizzo** [comment]
this is happening to me, expo go continues to refresh even when I'm not making any changes

**Comment by colehennnig** [comment]
I was just having this problem and disabling "Fast Refresh" on the expo go app seemed to work.

**Comment by EZsunshine** [comment]
If your project folder is inside of OneDrive/iCloud/Dropbox etc, and enabled syncing, that may cause expo keep refreshing. You can either stop syncing or move your project folder outside of your cloud folder.

**Comment by JakimLi** [comment]
I got the same issue, it's keep refreshing, and in the terminal it keep printing: 
"(node:8697) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension."

**Comment by JakimLi** [comment]
I got the same issue, it's keep refreshing, and in the terminal it keep printing: 
"(node:8697) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension."

**Comment by No898** [comment]
I had same problem, i tried figure it why its happening(no errors), but before i find out it just stopped. 

Little bit weird, because same code, i tried 2x reload app, 2x times clean start app and it didnt work, after third start clean app without any changes i working normal...

**Comment by muratclk** [comment]
It is an inconsistent bug. Sometimes it doesn't stop rendering and says:
"Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension."
and sometimes it doesn't  say anything. I think it is not about "react-native-keyboard-accessory" because i didn't instal this library. Still throwing error sometimes
