### ISSUE TITLE
Margin affects padding inside Button

### ISSUE THREAD

**Issue by nikolal** [expo/expo#1667]
### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Environment

Environment:
  OS: OS X El Capitan 10.11.6
  Node: 8.4.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 8.2.1 Build version 8C1002
  Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/openratio-88260d5c-700e-47fe-837f-71437e6e2595.tar.gz

### Steps to Reproduce

1. uncomment marginTop

### Expected Behavior
- Text inside button should be centralized

### Actual Behavior
- Text is moved on top of the button

### Reproducible Demo
- https://snack.expo.io/SJhhndX3G

**Comment by nikolal** [comment]
Just to add.
 Everything worked as expected before v26 update.

**Comment by jimmylee** [comment]
Hey @nikolal thank you for taking the time to write this report, I've assigned @ide who is the most knowledgable about react native updates. Hopefully he will have some time to help take a look.

**Comment by ide** [comment]
Hi @nikolal - thanks for providing the Snack. It look like you aren't using any Expo-specific code in your demo and this is most likely just how React Native now works. As you can see there were several commits to the layout library in React Native: https://github.com/facebook/react-native/commits/master?after=ff9b3c6517d6427b8ca0cec2660555152be3d028+34&path%5B%5D=ReactCommon&path%5B%5D=yoga

**Comment by nikolal** [comment]
Hi @ide 
Thanks for the fast response. 
I created the same issue on React Native repo, since I believe this isn't intended  behaviour. It is breaking styles of several apps of mine.

**Comment by FlaviooLima** [comment]
[Related](https://github.com/facebook/react-native/issues/19164)
