### ISSUE TITLE
Expo dev client not opening on Android phone using minimal app example

### ISSUE THREAD

**Issue by advanw** [expo/expo#16674]
### Summary

These are the steps that I  take:
- Create an app using https://docs.expo.dev/development/getting-started/ using TypeScript, Empty setup
- Run "expo start --dev-client"
- The output is looking good, QR is displayed
- I scan the QR code using Expo Go on my Android phone (Android 10)

Expected behaviour:
- The app is opened on my phone

Actual behaviour
- Nothing happens
- See the video: https://streamable.com/91scvi

When I use "expo start", and then scan the QR code, I get the choice to use "Development Build" or "Expo Go". Clicking "Development Build" opens a browser and nothing happens (blank screen). Clicking "Expo Go" opens the app as would be expected.

![screenshot-blank](https://user-images.githubusercontent.com/9381181/158831880-e4351f8d-c18d-44ed-8381-bb2be8420a30.png)

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

"dependencies": {
    "expo": "~44.0.0",
    "expo-dev-client": "~0.8.4",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1"
  },

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.9 Ubuntu 20.10 (Groovy Gorilla)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 8.4.0 - /usr/local/bin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo

- Create an app using https://docs.expo.dev/development/getting-started/ using TypeScript, Empty setup

### Stacktrace (if a crash is involved)

No logs are displayed.

**Comment by byCedric** [comment]
Hi @advanw! When using the dev client, you have to install the app on your phone too. Expo Go can't be used with dev clients, it's a full replacement for the Expo Go app instead. Instead of just starting the metro bundler, try running this instead:

```
$ expo run:android --device
``` 

This will build your dev client app locally, and with the `--device` property, it will prompt you to install it directly on any ADB-connected device. After the app is built _and_ installed, it will start up the metro bundler equally to how you start it with `expo start --dev-client`.

Hope this helps!

**Comment by WillSmithTE** [comment]
@byCedric to clarify, if I want to use `--tunnel` on my real device not connected to my PC, I would have to connect it once, run `expo run:android --device` and select my device, and then in future I could use it with tunnelling without being connected?
