### ISSUE TITLE
Cannot build android flavors with a Development build

### ISSUE THREAD

**Issue by dogfootruler-kr** [expo/expo#16686]
### Summary

I was following this [documentation](https://docs.expo.dev/build-reference/variants/#example-configuring-development-and-production-variants-in-1) to configure a development/staging/production variants in a bare project, it works fine with iOS but not for android.

As soon as I add the flavors to my build.gradle I can't run my application on android anymore.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~0.8.4"

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 6.14.16 - /usr/local/opt/node@14/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 30
        Build Tools: 29.0.2, 30.0.2, 32.0.0
        System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.2 => 44.0.2 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo

[Here](https://github.com/dogfootruler-kr/animated-guacamole)

**Comment by esamelson** [comment]
Hi @dogfootruler-kr -- sorry you're running into this issue! What happens when you try to run on Android?

**Comment by dogfootruler-kr** [comment]
Hello @esamelson , sorry I completely forgot to share the error logs... 

My `eas.json` looks like this:
```
{
  "cli": {
    "version": ">= 0.47.0"
  },
  "build": {
    "development": {
      "node": "14.19.1",
      "releaseChannel": "development",
      "developmentClient": true,
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleDevelopmentDebug"
      }
    },
    "staging": {
      "node": "14.19.1",
      "releaseChannel": "staging",
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleStagingRelease"
      }
    },
    "production": {
      "node": "14.19.1",
      "releaseChannel": "production",
      "android": {
        "gradleCommand": ":app:bundleProductionRelease"
      }
    }
  }
}
```

and I added the flavors in my `app/build.gradle` like this:
```
    flavorDimensions "env"
    productFlavors {
        production {
            dimension "env"
            applicationId 'com.myapp'
        }
        staging {
            dimension "env"
            applicationId 'com.myappstg'
        }
        development {
            dimension "env"
            applicationId 'com.myappdev'
        }
    }
```

```
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

> Configure project :expo-dev-menu
DevMenu will replace JNI library.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/patrice/Documents/Github/my-app/node_modules/expo-dev-menu/android/build.gradle' line: 105

* What went wrong:
A problem occurred evaluating project ':expo-dev-menu'.
> Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 22s
/Users/patrice/Documents/Github/my-app/android/gradlew exited with non-zero code: 1
Error: /Users/patrice/Documents/Github/my-app/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/patrice/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
    ...
    at spawnAsync (/Users/patrice/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/Users/patrice/.config/yarn/global/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/Users/patrice/.config/yarn/global/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/Users/patrice/.config/yarn/global/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:143:9)
error Command failed with exit code 1.
```

**Comment by esamelson** [comment]
Thanks for the extra details @dogfootruler-kr , and for providing a repo. I've been able to reproduce the error and track down the source. We should have a fix out in the next release of the `expo-dev-client` package, but if this is blocking you in the meantime, you can add the fix from #16799 locally using patch-package.

**Comment by dogfootruler-kr** [comment]
Hello @esamelson,

the patch works perfectly fine for my development and staging but not for my production one has I use the gradleCommand: `:app:bundleProductionRelease` and the `getCurrentFlavor()` function is missing a pattern matching for task that contains `bundle`.

I fixed it locally by changing the function to:
```
def getCurrentFlavor() {
  Gradle gradle = getGradle()
  String taskRequestName = gradle.getStartParameter().getTaskRequests().toString()
  Pattern pattern

  if (taskRequestName.contains("assemble")) {
    pattern = Pattern.compile("assemble(\\w+)(Release|Debug)")
  } else if (taskRequestName.contains("bundle")) {
    pattern = Pattern.compile("bundle(\\w+)(Release|Debug)")
  } else {
    pattern = Pattern.compile("generate(\\w+)(Release|Debug)")
  }
  Matcher matcher = pattern.matcher(taskRequestName)

  if (matcher.find()) {
    return matcher.group(1)
  }
  return ""
}
```

Do you want me to create a PR?

Cheers

**Comment by lukmccall** [comment]
> Do you want me to create a PR?

That would be awesome ;) Thanks in advance.

**Comment by dogfootruler-kr** [comment]
@lukmccall Here you go ! [16936](https://github.com/expo/expo/pull/16936)

**Comment by renatost** [comment]
The proposed solution here doesn't address the case when you run android (or iOS) locally with expo run:android --variant developmentDebug. 
taskRequestName becomes installDevelopmentDebug so we are missing another if:

`else if (taskRequestName.contains("install")) {
    pattern = Pattern.compile("install(\\w+)(Release|Debug)")
  }`
