### ISSUE TITLE
Asking for location permissions hangs forever on iOS standalone

### ISSUE THREAD

**Issue by Devtron718** [expo/expo#1668]
### Environment

Standalone iOS app, iOS 11.2.1,  expo 25.00

### Steps to Reproduce
 
`Permissions.askAsync(Permissions.LOCATION)` never resolves on iOS standalone app. Works in iphone simulator, when ran via expo client on iphone device (with `--no-dev`), as well as android devices.

In this example code, the first alert is seen, but then no alert to ask for permissions nor the one after saying the status.

The code:
```
function locationPermission() {
    Alert.alert(
        'ABOUT TO ASK FOR LOCATION PERMISSION',
        '',
        [
            {text: 'Yup', onPress: () => null},
        ]
    )
    let { status } = await Permissions.askAsync(Permissions.LOCATION)
    Alert.alert(
        'LOCATION PERMISSION STATUS',
        status,
        [
            {text: 'Yup', onPress: () => null},
        ]
    )
}
```

### Expected Behavior

Should prompt user asking for location permissions

### Actual Behavior

No prompt and the promise never resolves with a status (again, this only happens in iOS standalone apps. all other environments ive tested in work beautifully)

**Comment by Devtron718** [comment]
it looks like removing
```
"ios": {
  "infoPlist": {
    "NSLocationAlwaysUsageDescription": "stuff",
    "NSLocationWhenInUseUsageDescription": "stuff"
  }
}
```
from my app.json resolved the issue

**Comment by wassgha** [comment]
Why is this issue closed? Removing those lines makes it impossible to pass the itunes review process. Is there an actual solution to this?

For some reason it started happening to me although it didn't happen before and this behavior is only observed on standalone apps (whether on the simulator or not), using the expo client works fine.
