### ISSUE TITLE
Gradle detected a problem with task :expo-constants:createDebugExpoConfig

### ISSUE THREAD

**Issue by rob-johansen** [expo/expo#16695]
### Summary

After installing React Navigation following these two[^1][^2] pages of instructions, I'm seeing the following new output when I run `npx react-native run-android`:

```
Execution optimizations have been disabled for task ':expo-constants:createDebugExpoConfig' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/rob/code/lettery/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:checkDebugAarMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/rob/code/lettery/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/rob/code/lettery/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/rob/code/lettery/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:compileDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/rob/code/lettery/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:generateDebugBuildConfig' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/rob/code/lettery/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:javaPreCompileDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/rob/code/lettery/android'. Reason: Task ':expo-constants:createDebugExpoConfig' uses this output of task ':app:mergeDebugShaders' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

The Gradle page[^3] referenced in the above output summarizes:

> This error indicates that you have a task which depends on another, but that no explicit or implicit dependency is declared between those two tasks.

So I have two questions:

1. Any idea why this only started after installation of React Navigation?
2. My app still runs in development, but should I be concerned?

[^1]: https://reactnavigation.org/docs/getting-started
[^2]: https://reactnavigation.org/docs/hello-react-navigation
[^3]: https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.2 environment info:
  System:
    OS: macOS 12.2
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.01.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 25, 28, 29, 30, 31
      Build Tools: 25.0.2, 28.0.3, 29.0.1, 29.0.2, 30.0.2, 30.0.3, 32.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  npmPackages:
    expo: >=44.0.0-0 <45.0.0 => 44.0.6 
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
  npmGlobalPackages:
    expo-cli: 5.2.0
  Expo Workflow: bare
```

### Reproducible demo

This is the entirety of my app at the moment (yes, I'm just getting started 🙂 ):

```tsx
import React, { useCallback, useEffect, useState } from 'react'
import { createNativeStackNavigator } from '@react-navigation/native-stack'
import { getItemAsync } from 'expo-secure-store'
import { hideAsync, preventAutoHideAsync } from 'expo-splash-screen'
import { NavigationContainer } from '@react-navigation/native'
import { Text, View } from 'react-native'

const { Navigator, Screen } = createNativeStackNavigator()

const Welcome = (): JSX.Element => {
  return (
    <View>
      <Text>Welcome Screen</Text>
    </View>
  )
}

const App = (): JSX.Element | null => {
  const [loaded, setLoaded] = useState(false)

  useEffect((): void => {
    const getLocalData = async (): Promise<void> => {
      try {
        await preventAutoHideAsync()

        const token: string | null = await getItemAsync('token')

        if (token) {
          // TODO .... Fire off a request to find this user by token.
        }
      } catch (err) {
        console.warn(err)
      } finally {
        setLoaded(true)
      }
    }

    getLocalData()
  }, [])

  const onReady = useCallback(async (): Promise<void> => {
    if (loaded) {
      await hideAsync()
    }
  }, [loaded])

  if (!loaded) {
    return null
  }

  return (
    <NavigationContainer onReady={onReady}>
      <Navigator screenOptions={{ headerShown: false }}>
        <Screen component={Welcome} name='Welcome' />
      </Navigator>
    </NavigationContainer>
  )
}

export default App
```

**Comment by neelspansare** [comment]
Did you find a solution to this issue?

**Comment by rob-johansen** [comment]
@neelspansare No, but it's not blocking my project. Come to think of it, I'm not even sure it's an issue with expo since it only started after I installed React Navigation. 🤷‍♂️

**Comment by Md-Mudassir47** [comment]
Restarting my mac & then doing a clean install and build fixed the issue

**Comment by Tonytodo24** [comment]
I made my project by using CRNA, it worked well at first, but the same problem happened after I installed expo modules, why there's so many problems with EXPO, jesus.

**Comment by algarcia-vector** [comment]
I am having the same issue, I started new react native project, and installed Expo modules and getting this warnings :(

**Comment by anpriyadar** [comment]
Any Ways to fix these warnings ?

**Comment by ahnafnafee** [comment]
I got this issue when I limit the memory of my WSL containers using `.wslconfig`. So to fix it, I went to `C:\Users\{username}\.wslconfig` and removed any kind of memory and processor limitations. That solved the Gradle memory issues for me.

**Comment by doougui** [comment]
Any updates on this? I'm using MacOS here and this error appeared after upgrading to Expo SDK 45

**Comment by camilo86** [comment]
Seeing the same issue here on a blank new project

**Comment by nixolas1** [comment]
Same here, at it is severely impacting the build-time when running `react-native android`. It seems the build step is never cached, so it takes up time _every_ time I want to launch the app on my phone, even when no changes have been made.

**Comment by PanamaDonne** [comment]
+ 1

**Comment by atif7865** [comment]
same issue here, any updates on this?

**Comment by RileySeaburg** [comment]
Same issue

**Comment by m-jachym** [comment]
Hey @vankhoa01  @rob-johansen 
Did you solve this issue?

**Comment by ThunbergOlle** [comment]
Same issue

**Comment by joseasanchezzz91** [comment]
same issue here, any updates on this?   :-(

**Comment by innocodes** [comment]
I am facing the same issue as well. This is causing my build to fail whenever I run './gradlew assembleDebug'
Looking forward to a fix.

**Comment by jaymeeu** [comment]
facing the same issue. Has anybody found a solution?

**Comment by pixelsomatic** [comment]
Facing the exactly same issue. There's some kind of solution for this?

**Comment by mrcameron999** [comment]
Same issue here

**Comment by ejkkan** [comment]
Was this ever resolved? 
Any workaround out there?

**Comment by xiaoyu2006** [comment]
Same

**Comment by Gabsop** [comment]
Same here

**Comment by nasyarobby** [comment]
Having this issue after adding expo.

**Comment by sohailykhan94** [comment]
> Hi my friends, I got same issue when upgrade Android Target API to 33 And it's blocking my project Is there any solution to fix it ?
> 
> Thank you so much

Hey just wanted to share my fix. I was able to get it working by:
- Remove `withConfig` and forego plugin chaining.
- Use `withBuildProperties` directly.
- Clear android folder and run `npx expo run:android` from scratch.

```js
// Something like this
export default withBuildProperties(config, {
  android: {
    compileSdkVersion: 32,
  },
})
```

**Comment by earonesty** [comment]
closed.... even though everyone encounters this....

**Comment by LYevhen** [comment]
@earonesty Hey, I'm having same issue, I can't see solutions here, but ticket is closed, could You please let community know what is the reason of closing ticket if it is not solved ?
It seems that it is not one person issue.
I'm migrating from old api to
"expo": "^48.0.19",
"react-native": "0.71.11"

But I'm pointed to newer gradle doc 'Please refer to https://docs.gradle.org/7.5.1'

Can provide more details for packages I'm using.

**Comment by earonesty** [comment]
i just wiped everything, rebuilt, played with various settings, upgraded things, and now it works.   (js ecosystem is a house of cards)

**Comment by LYevhen** [comment]
Maybe it is good oportunity to share Your experience  with comunity and what helped You could help others?

**Comment by victorbalssa** [comment]
I fixed this issue by downgrading gradle to version `7.6.2`
following this [StackOverflow answer](https://stackoverflow.com/a/33892937/6817463):
- I deleted content of `.gradle` folder in my project root.
- open android studio, click File->Project structure, then change gradle version to `7.6.2`.
- rebuild
