### ISSUE TITLE
Android - Constant confirmation dialogs when moving an asset to an album 

### ISSUE THREAD

**Issue by alexstanbury** [expo/expo#16694]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by alexstanbury** [comment]
I'm seeing inconsistencies on how moving an asset to an album behaves. On a Samsung tablet (Android 11) and Pixel 6 (Android 12) I constantly get a pop up asking me 'Allow APP_NAME to modify this photo'. If I choose not to move the asset but instead just copy it then I don't get the permission popup. On a Xiaomi phone (Android 10) I have no such problem.

I am aware of and have read the information at https://github.com/expo/fyi/blob/main/android-r.md

The documentation makes no mention of this hindrance, so I can only assume it is a bug with the permissions somehow.

```
export const moveImageToDeviceGallery = async ({
  albumName,
  imageURL,
}: {
  albumName: string;
  imageURL: string;
}) => {
  const response = await MediaLibrary.requestPermissionsAsync(false);
  if (response.granted) {
    const mediaAsset = await MediaLibrary.createAssetAsync(imageURL);
    const album = await MediaLibrary.getAlbumAsync(albumName);
    if (album) {
      await MediaLibrary.addAssetsToAlbumAsync([mediaAsset], album, false);
    } else {
      await MediaLibrary.createAlbumAsync(albumName, mediaAsset, false);
    }
    const assetsFromAlbum = await MediaLibrary.getAssetsAsync({
      first: 1,
      album: album,
      sortBy: MediaLibrary.SortBy.creationTime,
    });
    const asset = await assetsFromAlbum.assets[0];
    deleteFile(imageURL);
    return asset.uri;
  } else {
    return null;
  }
};
```

**Comment by leon-envoi** [comment]
I'm having a same issue, pls help!

**Comment by superyarik** [comment]
same issue

**Comment by kdkcom1234** [comment]
same issue, too
