### ISSUE TITLE
barCodeScannerSettings -> barCodeTypes is not work in Android 

### ISSUE THREAD

**Issue by iivu** [expo/expo#16697]
### Summary

Use `Camera` component with ` barCodeScannerSettings={{ barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr] }}` to scan QR code, not only QR codes are scanned, but other types of codes are also scanned.

My test device : MI 6 / Android 9

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - D:\Environment\Node.js\node.EXE
      Yarn: 1.22.15 - D:\Environment\Node.js\yarn.CMD
      npm: 8.5.5 - D:\Environment\Node.js\npm.CMD
    Expo Workflow: managed

### Reproducible demo

```js
import React from "react"
import { Camera } from "expo-scanner"
import { BarCodeScanner } from "expo-barcode-scanner"

const handleBarCodeScanned = ({ data,type }) => {
  console.log(type)
  console.log(data)
}

export const BarcodeScanner = () => (
  <Camera
    type={Camera.Constants.Type.back}
    onBarCodeScanned={handleBarCodeScanned}
   // not work below line
    barCodeScannerSettings={{ barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr] }}
  />
)

```

**Comment by iivu** [comment]
#7352
#11632

**Comment by BadrBelhiti** [comment]
I'm having the same problem with Android (Samsung Galaxy S10+ / Android version 12). Expo SDK version 44 and Expo app version 2.24.4. It scans the QR code correctly (type 256), but also sometimes scans type 1024 if I open the camera too close to the QR code. The code:
```
    const handleBarCodeScanned: BarCodeScannedCallback = ({ type, data }) => {
        console.log(BarCodeScanner.Constants.BarCodeType.qr)
        alert(`Bar code with type ${type} and data ${data} has been scanned!`);

        navigation.reset({index: 1, routes: [{name: "LoggedIn"}, {name: "EventInfo"}]})
    };

    if (hasPermission === null) {
        return <Text>Requesting for camera permission</Text>;
    }
    if (hasPermission === false) {
        return <Text>No access to camera</Text>;
    }

    return (
        <View style={styles.container}>
            <BarCodeScanner
                onBarCodeScanned={handleBarCodeScanned}
                style={StyleSheet.absoluteFillObject}
                barCodeTypes={[BarCodeScanner.Constants.BarCodeType.qr]}
                type="back"
            />
        </View>
    );
```
Of course, we can just add an if statement in the callback to ensure only the proper code is handled. This will achieve the intended functionality, but ideally we don't want to try every type of code since the scanning will be slower and it results in significantly greater battery usage in iOS per the docs: https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/#supported-formats

**Comment by cfreear** [comment]
Also seeing this on a Pixel 6 Pro running Android 12 using this snack:

https://snack.expo.dev/@cfreear/basic-barcodescanner-usage

Its configured to only scan qr and code39 yet I was able to scan the aztec code on wikipedia here:

https://en.wikipedia.org/wiki/Aztec_Code

**Comment by OneLoneFox** [comment]
I can confirm the bug, reproducible on a Mi 9T - Android 10

**Comment by Rehankhalil462** [comment]
I can confirm the bug, barcodeTypes is not working . It is scanning all types of barcode despite of only mentioned types.

**Comment by cfreear** [comment]
I've updated my snack to sdk v47.0.0 and `"expo-barcode-scanner": "~12.1.0"` and I'm still able to scan the aztec barcode on wikipedia on a pixel 6 pro

**Comment by 999666-zk** [comment]
默认不是可以识别到所有？但是我的在android上识别不了条形码，ios上面是正常的，我的android设备是【小米8，android10】，使用的版本是"expo-barcode-scanner": "~11.3.0"，这个原因可能是怎么造成的？

**Comment by cfreear** [comment]
@brentvatne would my snack at https://snack.expo.dev/@cfreear/basic-barcodescanner-usage not count as a reproducible example?
