### ISSUE TITLE
[expo-camera] Bug. Reinitialising camera on video start recording and stop 

### ISSUE THREAD

**Issue by rusakovic** [expo/expo#16698]
### Summary

When start recording on iOS device, camera is reinitialising  during 1-2 secs and records black video.

Expected result: after calling `recordAsync()` camera is not restarting as it's done perfect in Android.

Tested on iPhone 7 (iOS 15.4)

https://user-images.githubusercontent.com/17801144/159138703-3a9fd799-dc54-425a-9c21-c9454525d6c0.mp4

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

```
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/maxrusakovic/.rubies/ruby-3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6
      react: 17.0.2 => 17.0.2
      react-native: ^0.67.3 => 0.67.3
 "expo-camera": "~12.1.2",
    "expo-face-detector": "~11.1.3"
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

```

### Reproducible demo

https://snack.expo.dev/@wegosi/basic-camera-usage

**Comment by mnightingale** [comment]
Is this the same as the long discussion on #1057 and PR to fix it #16290
I've not looked at the changes but it looks like it'd also need doc changes.

**Comment by rusakovic** [comment]
> Is this the same as the long discussion on #1057 and PR to fix it #16290 I've not looked at the changes but it looks like it'd also need doc changes.

Thank you for your help.
Tried to implement these changes.
I don't know if it's a separate issue now.
@polnikale Do you have such issue?
I use iPhone 7 without camera stabilization.

![IMG_6273](https://user-images.githubusercontent.com/17801144/159794806-ec628614-a78d-45bd-b0c4-e0a501aadc0e.jpg)

**Comment by rusakovic** [comment]
Ok, I tried with 'back' camera on iPhone 7.
And https://github.com/expo/expo/pull/16290 is not working, unfortunately.  Still, reinitialising.

**Comment by rusakovic** [comment]
Video on iPhone 7 with https://github.com/expo/expo/pull/16290 changes.
https://user-images.githubusercontent.com/17801144/159797068-e957485a-71c3-49f5-901c-6841b4062545.mov

**Comment by polnikale** [comment]
@rusakovic to be honest, when deploying, we found that my code still has a few flaws. I've already fixed them locally, but wasn't able to bring it to PR yet as I've been quite busy, to be honest. I will try to update the PR within a few days.

However, it should still work, I think. Could you share the code of your usage of the camera? As far as I remember, I've added the
`defaultRecordSettings` prop, where you should pass all the data. And then recordAsync should be completely empty. In this case, no reinitialization happen

**Comment by rusakovic** [comment]
@polnikale
Thank you for your reply! You're right. I removed settings from `recordAsync` , move to `defaultRecordSettings`, Camera is still reinitialising, but twice quicker than before.

Also, maybe you have possibility to check/test with https://docs.expo.dev/versions/latest/sdk/facedetector/

I'm using Camera with this package. I tried to disable/enable it with your changes, but Camera still reinitialising. 

If you have time to commit you latest updates - will be great!

**Comment by polnikale** [comment]
@rusakovic 

I haven't worked with facedetector, to be honest. Will try to take a look, but I can't promise anything.
Regarding the commits, I'll prepare them later this evening

**Comment by polnikale** [comment]
Good evening, @rusakovic

I've pushed all the changes. It appeared there were not much of them. Still, you could check and see if it helps you. In case it doesn't I think you should dig into the `commitConfigurations` calls

**Comment by ziyadm** [comment]
I also noticed this when testing, and it's pretty jarring. Anything we can do to help push this fix through?

**Comment by GreenCurveDev** [comment]
Hi, I just raised the same issue #18234 before finding this thread. It would be fantastic to have a fix as at present I am contemplating ejecting the app from Expo - I really (really) don't want to but I have just created a video sharing App and this is a fundamental feature that needs to be at a minimum comparable with other apps in a similar space. Happy (seriously) to donate if this will help in any way with prioritisation :)
