### ISSUE TITLE
Android Splash Screen: image not contained (standalone only)

### ISSUE THREAD

**Issue by cguyer** [expo/expo#1670]
After doing some testing on Android (standalone), we noticed that our splash image was not being contained (default) It works fine in the Expo Client and the iOS standalone version.

There seems to be a closed issue #1037 which relates to this and has recent comments about the standalone splash not working as intended.

app.json excerpt
```
{
  "expo": {
    "sdkVersion": "26.0.0",
    "splash": {
      "image": "./img/eita-splash.png"
    }
}
```
  
### Environment
```
$ exp diagnostics
14:26:15 [exp] Generating diagnostics report...
14:26:15 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  expo: ~26.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/cguyer-486ee31f-a324-4a14-af17-c2d168d04fdf.tar.gz
```

### Steps to Reproduce

1. Define splash image
2. Build for Android: exp build:android --release-channel production
3. Launch app

### Expected Behavior

Splash image is contained like iOS
![expoandroidsplash](https://user-images.githubusercontent.com/516385/39011818-89f84f8e-43e0-11e8-9726-c32bca912def.png)

### Actual Behavior

Upon launch of app, image is not contained and shows larger then expected.
![standaloneandroidsplash](https://user-images.githubusercontent.com/516385/39011820-8db7d19e-43e0-11e8-8a81-bcf2618e409f.png)

**Comment by terribleben** [comment]
Reopening the other issue. Thanks for the report.
