### ISSUE TITLE
Weird Versioning Issue with Node

### ISSUE THREAD

**Issue by josephlee3150** [expo/expo#16700]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/62917969/159183870-0d2e427d-a509-46d5-85d4-40118b30b368.png">

When I try to use expo with node version 14.0.0 it asks me to use version 12.0.0 and when I change to 12.0.0 it asks me to use node version 14.0.0. What is the issue here?

**Comment by byCedric** [comment]
Hi @josephlee3150, it seems like you are running multiple Expo CLI versions from different node instances on nvm. I would recommend switching to Node 16 and reinstall `expo-cli` globally.

```
$ nvm use 16.14.2
$ npm remove -g expo-cli
$ npm install -g expo-cli
```

Hope this helps!
