### ISSUE TITLE
[expo-local-authentication] LocalAuthentication.authenticateAsync unexpected bahavior on Samsung

### ISSUE THREAD

**Issue by zbagdzevicius** [expo/expo#16705]
### Summary

on LocalAuthentication.authenticateAsync() call, promise is hanging in the background in case if user clicks "CANCEL" in  "verified. Tap confirm to continue" step, it should be resolved and handled. As on second and further authenticateAsync function calls returned payload is always {error: 'app_cancel', success: false} without any biometric prompt. I checked other applications ( non-expo), and I'm being prompted like expected in same scenario, so it's not OS or package usage related problem, should be package implementation uncovered case or something like this ( perhaps ).

( on huawei, iOS and other regular android devices it seems to be working fine )

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Device environment:

Reproducible on Samsung galaxy S20 FE on both expo go & standalone app. ( But also reproducible on most samsung devices that has confirmation biometric step ( confirm / cancel )

App development environment:

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

1. call LocalAuthentication.authenticateAsync()
2. authenticate using face-id / fingerprint / pin
3. in "Verified. Tap confirm to continue" screen clicks "CANCEL"
4. promise is pending, nothing is returned
5. call LocalAuthentication.authenticateAsync()  again
6. {error: 'app_cancel', success: false} payload returned without prompt for biometrics auth

**Comment by zbagdzevicius** [comment]
up

**Comment by michelle-chiang** [comment]
Are there any updates on this?

**Comment by tmKnight01** [comment]
I encountered this problem in June 2024 and there is no progress yet？

**Comment by alainib** [comment]
still have this error. any fix ?

**Comment by lucaventura** [comment]
Having this issue as well.
