### ISSUE TITLE
[expo-44.0.6]package expo.modules.adapters.reanimated does not exist

### ISSUE THREAD

**Issue by mtroskot** [expo/expo#16704]
### Summary

Android build is not working with reanimated 2.5.0

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
      Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.67.2 => 0.67.2 
    Expo Workflow: bare

### Reproducible demo

error: package expo.modules.adapters.reanimated does not exist new expo.modules.adapters.reanimated.EXReanimatedPackage(),

**Comment by Filippo39** [comment]
Same issue

**Comment by KROSF** [comment]
@mtroskot here a reproducible example https://github.com/muchobien/ownda-app/pull/144

**Comment by ConorCorp** [comment]
Same issue

**Comment by KROSF** [comment]
[Here](https://github.com/software-mansion/react-native-reanimated/issues/3088) is a workaround

**Comment by MahmoudNafiseh** [comment]
I solved the issue by changing the react-native-reanimated package from 2.5.0 to 2.4.1, like this: 

package.json: 
`		"react-native-reanimated": "2.4.1",
`


yarn.lock: (make sure to change from 2.5.0 to 2.4.1 in "resolved" && "version" too)
```
"react-native-reanimated@>= 1.0.0", "react-native-reanimated@2.4.1":
  "integrity" "sha512-kvf7ylGlwa5hxMQ+wpPFjQrI2c6eexf53/xRo+dvXBNefGmSYaYR5sFtD0XMMzIPQlkCB9tJ0Pu9+2WCQUY7Cg=="
  "resolved" "https://registry.npmjs.org/react-native-reanimated/-/react-native-reanimated-2.4.1.tgz"
  "version" "2.4.1"
  dependencies:
    "@babel/plugin-transform-object-assign" "^7.10.4"
    "@types/invariant" "^2.2.35"
    "invariant" "^2.2.4"
    "lodash.isequal" "^4.5.0"
    "mockdate" "^3.0.2"
    "react-native-screens" "^3.4.0"
    "string-hash-64" "^1.0.3"

```

Podfile.lock: 
`  - RNReanimated (2.4.1):
`

**Comment by aprilmintacpineda** [comment]
I downgraded to 2.4.1 for now while expo hasn't updated their end yet.

**Comment by chaiwa-berian** [comment]
Same issue on `react-native-reanimated 2.5.0`, using `react-native-reanimated` in a `bare bone react native` project.

**Comment by KROSF** [comment]
Adding this to your  `package.json` fixes it
```json
"expo": {
    "autolinking": {
      "exclude": [
        "react-native-reanimated"
      ]
    }
  },
```

copied from https://github.com/software-mansion/react-native-reanimated/issues/3088

**Comment by Kumar2106** [comment]
I am getting the same issues, i have tried with downgrading the react-native-reanimated version but that does not seems to work in my case.

**Comment by alyywehby** [comment]
I am getting the same issues on android. I am already using a downgraded version of "react-native-reanimated": "^2.3.1"
expo-cli: 5.3.0
"expo": "~44.0.0",
"react": "17.0.1",
"react-native": "0.64.3",
node version: v14.17.1
npm version: 6.14.13
