### ISSUE TITLE
Paste from clipboard doesn't work in iOS simulator run on MacBook with M1 chip

### ISSUE THREAD

**Issue by stanislaw-code-and-pepper** [expo/expo#16713]
### Summary

Pasting from clipboard doesn't work in an app run in Expo Go. It's not an issue with the simulator because I can copy and paste text in other apps in the simulator e.g. Safari. I can also copy and paste things from outside the simulator to Safari in the simulator. It's possible to select a text in my app, copy it, and past it to another app in the simulator or to my VS Code outside.
The problem occurs only in simulators with iOS > 13.7, so the workaround is to install an older version.

I'm using MacBook Pro M1

Similar unsolved issues:
https://github.com/expo/expo/issues/13661
https://github.com/flutter/flutter/issues/74970

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.48.1
      expo-cli: 5.2.0
    Expo Workflow: managed

### Reproducible demo

https://user-images.githubusercontent.com/100682087/159446278-c4f74804-e293-42ad-98b2-f558544791ff.mov

**Comment by tanjingchuan** [comment]
i encounter same problem, In my mac studio. can not paste content from my mac to simulator

**Comment by n13** [comment]
It's finally working - not sure how this was fixed - flutter or iOS simulator? 

Simulator: iOS 15.5
Version 13.4.1 (977.2)
SimulatorKit 618
CoreSimulator 802.6.1

XCode: Version 13.4.1 (13F100)

Flutter: 
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (3 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

Between those three, not sure who made this fix, but copy paste works again, and I am happy.

**Comment by scarlac** [comment]
This is an Xcode/iOS simulator issue from what I've gathered. I am googling this issue and have noticed that it worked in the past. It doesn't seem to be Expo-specific but users are complaining about this in Apple forums as well, and to this day it's still an outstanding issue. I don't know if it's fixed in the latest Xcode 14 beta though. Users in the forums are saying it generally works in iOS 13 simulators but 14+ doesn't. Some say pasting twice helps (which I've had to do as well) but that stopped working in recent versions.

**Comment by n13** [comment]
> This is an Xcode/iOS simulator issue from what I've gathered. I am googling this issue and have noticed that it worked in the past. It doesn't seem to be Expo-specific but users are complaining about this in Apple forums as well, and to this day it's still an outstanding issue. I don't know if it's fixed in the latest Xcode 14 beta though. Users in the forums are saying it generally works in iOS 13 simulators but 14+ doesn't. Some say pasting twice helps (which I've had to do as well) but that stopped working in recent versions.

Update: It is still a little flakey and sometimes it fails but for the most part it works now. Sometimes I have to hit paste multiple times for it to take hold. Or restart the simulator. The simulator will have the notification badge saying that something was copied, but it won't show in the text field.

**Comment by nicolas-miari** [comment]
I'm having the issue on an **intel** Mac.

**Comment by Nikolai17** [comment]
I'm having the issue on an intel Mac too

**Comment by ajay-zartek** [comment]
I’m having the same issue.

**Comment by thangflydino** [comment]
I'm having the issue on an intel Mac too

**Comment by tcs-vheble** [comment]
Same here

**Comment by shiftytab** [comment]
I'm having the issue on a m2 mac.

**Comment by xwartz** [comment]
iOS 16.1 works fine

**Comment by rahulVermaSimpplr** [comment]
same issue sometimes it works but sometimes don't.

**Comment by ichiwa** [comment]
same issue here.

**Comment by felipejoribeiro** [comment]
same issue

**Comment by nemrosim** [comment]
@philpettican118 thank you. **iOS 16.2**: Working, confirm.

**Comment by finessevanes** [comment]
The above still doesn't work. I've toggled it on/off, restarted my machine, nothing seems to work.

**Comment by atianren** [comment]
@nemrosim thank you all the same,IOS 16.1, M1, work for me.
