### ISSUE TITLE
TypeError: null is not an object (evaluating ‘_ExpoRandom.default.getRandomBytes’)

### ISSUE THREAD

**Issue by ballza95** [expo/expo#16719]
### Summary

Im use expo-auth-session/providers/google with expo dev client

monorepo

expo sdk 44

install : expo install expo-auth-session expo-random expo-web-browser

open app crash show

TypeError: null is not an object (evaluating ‘_ExpoRandom.default.getRandomBytes’)

im use * See the guide for more info on usage: [Google Authentication](https://docs.expo.dev/guides/authentication/#google).

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

  Expo CLI 5.2.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 28, 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-S | Google APIs ARM 64 v8a, android-S | Google APIs Intel x86 Atom_64
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.11 => 0.3.12 
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.17.0
    Expo Workflow: managed

### Reproducible demo

// expo install expo-web-browser expo-auth-session expo-random
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, View, Text, Image, Button } from 'react-native';
import * as Google from 'expo-auth-session/providers/google';
import * as WebBrowser from 'expo-web-browser';

WebBrowser.maybeCompleteAuthSession();

export default function App() {
  const [accessToken, setAccessToken] = React.useState();
  const [userInfo, setUserInfo] = React.useState();
  const [message, setMessage] = React.useState();

  const [request, response, promptAsync] = Google.useAuthRequest({
    androidClientId: "694235095257-fkbf1u81sm5ii76om74j5b7h8u4v2m7a.apps.googleusercontent.com",
    iosClientId: "694235095257-qnub27n3o6s0e3lo1sneio03o6ka5k9m.apps.googleusercontent.com",
    expoClientId: "694235095257-7t7h7mv877d2jfu7r508ct1egmesbqdm.apps.googleusercontent.com"
  });

  React.useEffect(() => {
    setMessage(JSON.stringify(response));
    if (response?.type === "success") {
      setAccessToken(response.authentication.accessToken);
    }
  }, [response]);

  async function getUserData() {
    let userInfoResponse = await fetch("https://www.googleapis.com/userinfo/v2/me", {
      headers: { Authorization: `Bearer ${accessToken}`}
    });

    userInfoResponse.json().then(data => {
      setUserInfo(data);
    });
  }

  function showUserInfo() {
    if (userInfo) {
      return (
        <View style={styles.userInfo}>
          <Image source={{uri: userInfo.picture}} style={styles.profilePic} />
          <Text>Welcome {userInfo.name}</Text>
          <Text>{userInfo.email}</Text>
        </View>
      );
    }
  }

  return (
    <View style={styles.container}>
      {showUserInfo()}
      <Button 
        title={accessToken ? "Get User Data" : "Login"}
        onPress={accessToken ? getUserData : () => { promptAsync({useProxy: false, showInRecents: true}) }}
      />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userInfo: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilePic: {
    width: 50,
    height: 50
  }
});

**Comment by byCedric** [comment]
Hi @ballza95! I think there might be a missing module in your dev client, specifically, the `expo-random` package. Can you try to run `$ yarn why expo-random` and share it here? If it's missing, you can try adding it manually with `$ expo install expo-random` and rebuild your dev client. That should get you get to a working state!

Hope this helps!

**Comment by cool-acid** [comment]
I'm also getting this error in Android (haven't tested it on iOS)
Error: `TypeError: null is not an object (evaluating '_ExpoRandom.default.getRandomBytes')`

`expo`: 44.0.0
`expo-random`: 12.1.1
`expo-auth-session`: 3.5.0

**Comment by ballza95** [comment]
@byCedric thx you.

Im use $ expo install expo-random but forget import expo-random in dependencies with package.json project in monorepo.

This makes the lib unable to link.

**Comment by byCedric** [comment]
@ballza95 great job finding that!

@cool-acid If you run into that specific error, `expo-random` isn't linked inside the native part of your app. It means that you probably have to rebuild the app in order to get it on the native side. If that doesn't work for you, please open a new issue.

**Comment by emiliogaines** [comment]
I have the same problem.

    "expo": "~45.0.4",
    "expo-random": "~12.2.0",
    "expo-auth-session": "~3.6.1",

and I get

> Cannot read property 'getRandomBytes' of null

from line

`    if (ExpoRandom.getRandomBytes) {
        return ExpoRandom.getRandomBytes(validByteCount);
    }`

I have re-installed node_modules several times and even tried different versions.
I am using managed workflow.

**Comment by thedoublejay** [comment]
I have the same issue as @emiliogaines. Same packages versions. Only happened on SDK 45, iOS production build (from TestFlight). Cannot reproduce on Expo builds. I've tried rebuilding it multiple times. Same result.

**Comment by emiliogaines** [comment]
I actually just solved my problem. Seemed to be a problem when I migrated to Firebase v9, don't know if you are using it @thedoublejay. 
[Here](https://i.imgur.com/Rn7vPuK.png) is my commit that fixed it.

**Comment by mgretz** [comment]
I have the same issues - which version of Firebase 9.x.x did you youe @emiliogaines?

**Comment by emiliogaines** [comment]
@mgretz I'm currently on 9.8.1. Did you see my change in the screenshot? I also migrated all my firebase code to the v9 version, not sure if it's a must but might as well.

**Comment by sergiycheck** [comment]
I just got the same error:
```bash
 ERROR  TypeError: null is not an object (evaluating '_ExpoRandom.default.getRandomBytes')

This error is located at:
    in GoogleAuthentication (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

I tried downgrading to **"expo-random": "12.1.2"** but this didn't worked.
[Link to the project](https://github.com/sergiycheck/react-native-learning/tree/main/expo-learning)
additional screen
![image](https://user-images.githubusercontent.com/29612247/210016255-87a575c8-4bd3-4b91-9358-51192445d0e6.png)

**Comment by next6leo** [comment]
why this issue close. no solution
