### ISSUE TITLE
BlurView doesn't work on Android

### ISSUE THREAD

**Issue by raphaeltm** [expo/expo#16715]
### Summary

[BlurView](https://docs.expo.dev/versions/latest/sdk/blur-view/) is listed as working on Android, but even in the provided Snack in the documentation it doesn't.

Screenshot of current Platform Compatibility for Expo 44 (version I'm using):
![image](https://user-images.githubusercontent.com/910895/159537823-791330b1-7bf2-4267-b84b-00cdc18e39f6.png)

Screenshots of the example in the Snack iOS (working) vs Android (not working):
![image](https://user-images.githubusercontent.com/910895/159538281-f25f282b-9242-41d0-88cd-4b59b391d59b.png)
![image](https://user-images.githubusercontent.com/910895/159538362-ecbb882f-294a-47bd-bf3a-ba5c9a0848fb.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.16 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    npmPackages:
      @expo/metro-config: ^0.3.11 => 0.3.11 
      expo: ^44.0.5 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.3.0
    Expo Workflow: managed
```

### Reproducible demo

Just run the Snack linked from the BlurView documentation:
https://docs.expo.dev/versions/latest/sdk/blur-view/https://docs.expo.dev/versions/latest/sdk/blur-view/

**Comment by raphaeltm** [comment]
Never mind. Just noticed this in the docs:
> On Android, it falls back to a semi-transparent view.

I would argue that this means it's not compatible with Android. I find it misleading.

**Comment by okwast** [comment]
I agree. The green checkmark definitely indicates that it is blurring which it is not. I mean the whole purpose of these indicators are that one does not need to read the documentation to understand if it is working or not. I would suggest some yellowish indicator for Android there to show it doesn't break, but it doesn't really do its job.

**Comment by raphaeltm** [comment]
@okwast definitely. I believe it's actually not the first time I ran into this, but had forgotten, which makes me find it particularly egregious. If it's marked as supported, but it's not blurring, it shouldn't be called BlurView. Maybe something like `FeatureView: highlights content by either blurring or dimming background elements depending on the OS.` or something along those lines...

**Comment by schematis** [comment]
Is there a reason that we can't mimic how @react-native-community/blur supports it (or at least how [this commit](https://github.com/Kureev/react-native-blur/pull/455/files) shows it?

**Comment by dominictobias** [comment]
Yeah it doesn't work at all on Android. Outside of Expo I remember it being more picky about when and where it worked, but think I got it working (probably with the `@react-native-community/blur` package mentioned above)

**Comment by dominictobias** [comment]
I tried `@react-native-community/blur` instead and it works..
