### ISSUE TITLE
[android] tapping a notification while an experience is running in the background causes all notifications to be dismissed

### ISSUE THREAD

**Issue by MettaProgrammer** [expo/expo#1671]
When calling `Notifications.dismissNotificationAsync(notificationId)` it dismisses the entire stack of notifications in Android at least visually as when another notification comes through they are all there.

**Comment by ide** [comment]
I understand there to be an issue that you can't dismiss just one notification but could you please clarify what you mean by:
> as when another notification comes through they are all there
?

**Comment by MettaProgrammer** [comment]
Sorry probably should have added some more context. 

What I meant is that if I dismiss a notification it dismisses the whole stack however if I then receive a new notification the stack comes back with all of the previous notifications minus the one I dismissed. 

Is that clear now?

**Comment by esamelson** [comment]
Hi @MettaProgrammer - sorry for the delay here. I'm unable to reproduce the issue as you've described it. Could you tell us which Android device/OS you're seeing this behavior on, and give a list of steps to reproduce it?

**Comment by outaTiME** [comment]
hi @esamelson, same here ... 

im running on android 6.0.1 (with Expo 26).

basically i send few push notifications from "Push notifications tool" to my android device (app in background) 

![image 2018-05-09 10 54 09](https://user-images.githubusercontent.com/140472/39818450-4f7ac1e2-5377-11e8-8a27-0b462f6e8216.jpg)

when I open a specific notification my react native app handles it with "selected" as origin, then when app is active in foreground it displays a basic alert with the notification data, and on android my app dismisses it to make it dissapear from tray bar, this is causing all notifications to be removed, not only the one I selected.

this is how android works or just an issue? btw on iOS work as expected ... 

```
_handleNotificationMessage = (notification) => {
  this.setState({
    notification
  });
}
componentDidUpdate(prevProps, prevState) {
  const {
    appState,
    notification
  } = this.state;
  if (appState === 'active' && notification) {
    const { data = {}, notificationId } = notification;
    // dismiss when show (Android only)
    if (notificationId) {
      Notifications.dismissNotificationAsync(notificationId);
    }
    Alert.alert(
      'Notification',
      data.message,
      [
        {
          text: 'Accept',
          onPress: () => {
            this.setState({
              notification: null,
            });
          }
        },
      ],
      { cancelable: false }
    );
  }
}
```

thanks !!!

**Comment by esamelson** [comment]
Hi @outaTiME - thanks for letting us know about this. Since this is going to be a breaking change, we'll need to wait until the next SDK (28) to fix this. Really sorry for the inconvenience!

**Comment by machester4** [comment]
when I press on a push notification the app opens with the error: "`expo sdk 26.0.0 is not valid SDK version`" this will also be solved in SDK 28? **I am currently using SDK 27 and this only happens in the production version.**

**Comment by esamelson** [comment]
Hi @machester4 - this sounds like a different, unrelated bug. Could you open a [new issue](https://github.com/expo/expo/issues) and post some more details, along with a reproducible example? Thanks so much!

**Comment by machester4** [comment]
ok, thanks for the quick response.
