### ISSUE TITLE
Promise rejection when receiving permission.notifications

### ISSUE THREAD

**Issue by matwii** [expo/expo#1672]
So I followed the example for notifications on the Expo docs and I'm getting this warning:
[Unhandled promise rejection: Error: Unrecognized permission notifications]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:123:42 in createErrorFromErrorData
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:80:57 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:400:4 in __invokeCallback
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:139:28 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:316:6 in __guardSafe
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:138:17 in invokeCallbackAndReturnFlushedQueue

I'm also not getting the token and it won't ask me for permission at all.
Anyone know how to fix this? I've tried deleting node modules and installing them again, but it didn't work.

**Comment by matwii** [comment]
So I managed to fix the promise rejection by updating Expo to SDK 26, but nothing happens when I use this code on iOs:

        console.log(status);``const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        console.log(status);``

**Comment by uncvrd** [comment]
@matwii did you figure out why that console.log status doesn't print anything? I receive `undetermined` which is not correct either

**Comment by gentlefox** [comment]
@uncvrd `undetermined` is the iOS way of saying not granted.
