### ISSUE TITLE
Expo / React Native storage limitations

### ISSUE THREAD

**Issue by SKempin** [expo/expo#16738]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

I'm looking at file storage options using Expo and it seems that Async Storage is the only supported option. However it is documented that there is a 6MB limit on Android for this. I'm curious, how do native apps like Netflix/Spotify (for example) utilise hundreds of MB's of storage space? Is this not possible with Expo / React Native? I need to store around 50mb of JSON data.

Thanks

**Comment by hirbod** [comment]
While you clearly ignored the issue template, you can achieve this with RN, but you will need to use FileSystem for it.

https://docs.expo.dev/versions/latest/sdk/filesystem/

**Comment by SKempin** [comment]
@hirbod The template wasn't clear, so apologies for that.
