### ISSUE TITLE
'React/RCTEventDispatcherProtocol.h' file not found

### ISSUE THREAD

**Issue by bmitioglov** [expo/expo#16743]
### Summary

After doing `expo eject` I ran `expo run:ios` and see this error "'React/RCTEventDispatcherProtocol.h' file not found"

I don't have any idea what might be a reason and how to fix it.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

"react-native": "~0.63.4"
"expo": "~42.0.1"
MacOS: 12.0.1

package.json: 

"dependencies": {
    "@aws-amplify/datastore-storage-adapter": "^1.2.2",
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^7.1.9",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/elements": "^1.3.1",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
    "@shoutem/ui": "^4.6.5",
    "aws-amplify": "^4.3.10",
    "aws-amplify-react-native": "^6.0.1",
    "axios": "^0.21.4",
    "expo": "~42.0.1",
    "expo-app-loading": "^1.2.1",
    "expo-font": "^9.2.1",
    "expo-location": "~12.1.2",
    "expo-secure-store": "~10.2.0",
    "expo-sqlite": "~9.2.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-date-picker": "^4.1.1",
    "react-native-elements": "^3.4.2",
    "react-native-form-select-picker": "^0.0.12",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-linear-gradient": "~2.5.6",
    "react-native-maps": "^0.28.0",
    "react-native-modal": "^12.1.0",
    "react-native-number-please": "^1.0.5",
    "react-native-photo-view": "shoutem/react-native-photo-view#0ffa1481f6b6cb8663cb291b7db1d6644440584d",
    "react-native-picker-select": "^8.0.4",
    "react-native-responsive-linechart": "^5.7.1",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-sectioned-multi-select": "^0.8.1",
    "react-native-svg": "^12.1.1",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-switch-selector": "^2.2.0",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "~6.6.0",
    "react-native-web": "~0.11.0",
    "react-native-webview": "~11.0.0",
    "react-redux": "^7.2.5",
    "redux": "^4.1.1",
    "redux-thunk": "^2.4.1",
    "expo-splash-screen": "~0.11.2",
    "expo-updates": "~0.8.1",
    "react-native-reanimated": "~2.2.0",
    "react-native-unimodules": "0.14.10"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },

### Reproducible demo

Create managed expo project with expo 42.0.1
Add the specified dependencies to package.json 
Execute `expo eject`
Run `expo run:ios`

**Comment by bmitioglov** [comment]
Full error message looks like this:

❌  (node_modules/expo-app-loading/node_modules/expo-modules-core/ios/NativeModulesProxy/EXNativeModulesProxy.m:9:9)

   7 | #import <React/RCTComponentData.h>
   8 | #import <React/RCTModuleData.h>
>  9 | #import <React/RCTEventDispatcherProtocol.h>
     |         ^ 'React/RCTEventDispatcherProtocol.h' file not found
  10 | 
  11 | #import <ExpoModulesCore/EXNativeModulesProxy.h>
  12 | #import <ExpoModulesCore/EXEventEmitter.h>

**Comment by byCedric** [comment]
Hi @bmitioglov! It seems that you are using an incompatible version of `expo-app-loading`, and possibly others. In the error message, you can see that it's trying to load `expo-modules-core`, which is a replacement for `@unimodules` and was introduced in SDK 43. For SDK 42, [`expo-app-loading@1.1.2` should be used](https://github.com/expo/expo/blob/sdk-42/packages/expo/bundledNativeModules.json#L19).

I would recommend running `$ expo doctor --fix-dependencies` in your project before ejecting, and then try to eject after that fix.

Hope this helps!
