### ISSUE TITLE
App stops working after inserting "googleServicesFile" with relative path to file

### ISSUE THREAD

**Issue by muniperez** [expo/expo#1675]
### Steps to Reproduce

1. Follow the official Expo documentation to add FCM to your app
2. Include
```
{
  ...
  "android": {
    "googleServicesFile": "./google-services.json",
    ...
  }
}
```
3. Your app will stop working

### Expected Behavior
The app should work
### Actual Behavior
Expo XDE console shows the following message right after the React Navite Packager starts:
```
Switched to a LAN URL because the tunnel appears to be down. Only devices in the same network can access the app. You can restart the project to try reconnecting.
```
### Reproducible Demo

1) Download a ```google-services.json``` from your Firebase console and put it in the root of your project
2) Insert this code in your ```app.json```
```
{
  ...
  "android": {
    "googleServicesFile": "./google-services.json",
    ...
  }
}
```
This is what the Expo docs say - [Using FCM for Push Notifications](https://docs.expo.io/versions/latest/guides/using-fcm)

Refresh your project, it will stop working.

### Solution

Add the full path to the ```google-services.json``` file on your ```googleServicesFile``` entry.
Example: ```/Users/<username>/<projects-folder>/<project>/google-services.json```

Then everything works.

**Comment by terribleben** [comment]
Thanks. Going to group this issue with the other one for our own tracking purposes: https://github.com/expo/expo/issues/1636
