### ISSUE TITLE
How i can force enable light mode in my application and disable dark mode?

### ISSUE THREAD

**Issue by redirexStudio** [expo/expo#16772]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by redirexStudio** [comment]
I saw very much solution but without Expo and i haven't found just any solution for expo. My version of SDK: 44

**Comment by byCedric** [comment]
Please see: https://docs.expo.dev/versions/v44.0.0/config/app/#userinterfacestyle
