### ISSUE TITLE
Expo-sqlite gives syntax error on queries that are correctly formatted

### ISSUE THREAD

**Issue by marsmallos** [expo/expo#16776]
### Summary

I'm trying to run a basic query like so:

```
INSERT INTO composers (
            lastName,
            firstName,
            birthDate,
            deathDate
        ) VALUES (
            'name', 
            'lastname', 
            '1930', 
            '2000'
        ) 
        ON CONFLICT (lastName, firstName, birthDate, deathDate) DO
        UPDATE SET
            lastName = excluded.lastName,
            firstName = excluded.firstName,
            birthDate = excluded.birthDate,
            deathDate = excluded.deathDate
```

The table is setup like so:

```
CREATE TABLE IF NOT EXISTS composers (
            composerId INTEGER PRIMARY KEY AUTOINCREMENT,
            lastName	TEXT,
            firstName	TEXT,
            birthDate	TEXT,
            deathDate	TEXT,
            UNIQUE(lastName, firstName, birthDate, deathDate)
);
```

However, when running the INSERT query I'm getting a syntax error like so
```

near "ON": syntax error (Sqlite code 1 SQLITE_ERROR): , while compiling: INSERT INTO composers (
                        lastName,
                        firstName,
                        birthDate,
                        deathDate
                ) VALUES ('name', 'lastname', '1930', '2000') ON CONFLICT (lastName, firstName, birthDate, deathDate) DO
                UPDATE SET
                    lastName = excluded.lastName,
                    firstName = excluded.firstName,
                    birthDate = excluded.birthDate,
                    deathDate = excluded.deathDate, (OS error - 88:Socket operation on non-socket)
```

However, if I create the same table and copy paste the EXACT same query into the "DB browser for SQLite" program and run it, or run similar sqlite queries in a nodejs project I'm working on using the "sqlite3" package, this query runs as expected without errors.

I can correct the syntax error given by expo-sqlite by adding a semicolon after the VALUES part like so: VALUES ('name', 'lastname', '1930', '2000'); However, if I add the semicolon to the copypasted query in "DB browser for SQLite" or my nodejs project, I get a syntax error near ON. Furthermore, the query with the semicolon in expo-sqlite seems to not run the ON CONFLICT part, because I have added a success callback with a console.log which is not firing. So it's still not actually working as intended.

This seems like a bug to me or what else might be going on? Can you guide me to an alternative query that will work in expo-sqlite that I can use in the meantime that accomplishes the same thing?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~44.0.0 => 44.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

PS. I don't know why it says bare since I set the project to "managed" when I started out and haven't fiddled with any settings since, I have just installed packages and written code.

### Reproducible demo

const db = SQLite.openDatabase("repapp.db");

db.transaction((tx) => {

    tx.executeSql(`
        CREATE TABLE IF NOT EXISTS composers (
            composerId INTEGER PRIMARY KEY AUTOINCREMENT,
            lastName	TEXT,
            firstName	TEXT,
            birthDate	TEXT,
            deathDate	TEXT,
            UNIQUE(lastName, firstName, birthDate, deathDate)
        );
        `,
        [],
        (success) => console.log(success),
        (tx, error) => {console.log(tx); console.log(error); return false;}
    );
            
    tx.executeSql(`
        INSERT INTO composers (
            lastName,
            firstName,
            birthDate,
            deathDate
        ) VALUES (
            'name', 
            'lastname', 
            '1930', 
            '2000'
        ) 
        ON CONFLICT (lastName, firstName, birthDate, deathDate) DO
        UPDATE SET
            lastName = excluded.lastName,
            firstName = excluded.firstName,
            birthDate = excluded.birthDate,
            deathDate = excluded.deathDate
        `,    
        [], (_, resultSet) => {
            //console.log(JSON.stringify(rows));
            const insertId = resultSet.insertId ? resultSet.insertId : 0;
            console.log("INSERTED COMPOSER")
            console.log(insertId)                
        },
        (tx, error) => {console.log(tx); console.log(error); return false;}
    );
});

**Comment by epolat-github** [comment]
I have the same problem. My query works on IOS perfectly but fails on Android. This issue makes the package unusable, since it doesn't work on Android.

**Comment by Jacksonishere** [comment]
@epolat-github @marsmallos Did y'all ever find a resolution to this? We deployed a feature and discovered this is happening to android users that are on older version < android 10...

**Comment by epolat-github** [comment]
@Jacksonishere As far as I remember, no. Maybe [new SQLite of Expo](https://docs.expo.dev/versions/v50.0.0/sdk/sqlite-next/) can help? I haven't tried it yet.

**Comment by Jacksonishere** [comment]
It is due to android os < 11 have SQLiite 3.22.0 or lower which doesn't have UPSERT yet. Thread I posted yesterday: https://stackoverflow.com/questions/78573302/expo-sqlite-syntax-error-on-older-android-versions-for-correctly-formatted-error
