### ISSUE TITLE
NullPointerException com.google.android.cameraview.Camera2 in collectCameraInfo

### ISSUE THREAD

**Issue by martinezleoml** [expo/expo#16785]
### Summary

Using the latest version of expo-camera, we have bug reports from Redmi Note 9 Pro users for whom our app crashes when they try to take pictures.

Here is the stacktrace we get (from Sentry):
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.SortedSet.last()' on a null object reference
    at com.google.android.cameraview.Camera2.collectCameraInfo(Camera2.java:700)
    at com.google.android.cameraview.Camera2.start(Camera2.java:281)
    at com.google.android.cameraview.CameraView.start(CameraView.java:284)
    at expo.modules.camera.ExpoCameraView.onHostResume(ExpoCameraView.java:299)
    at expo.modules.adapters.react.services.UIManagerModuleWrapper$3.onHostResume(UIManagerModuleWrapper.java:127)
    at com.facebook.react.bridge.ReactContext$1.run(ReactContext.java:200)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7562)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

We're using Camera2 API (through [useCamera2Api](https://docs.expo.dev/versions/latest/sdk/camera/#usecamera2api) prop), but we were unable to reproduce on our side as we don't have access to this kind of Android device.

More information about the device
- Device: Redmi Note 9 Pro
- Model ID: QKQ1.191215.002
- OS: Android 10

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  ```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.7.2 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.2 - /opt/homebrew/bin/npm
      Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare
```

### Reproducible demo

https://snack.expo.dev/@martinezleoml/expo-camera---redmi-note-9-pro-crash

**Comment by martinezleoml** [comment]
Just wanted to leave additional information regarding this bug: the crash occurs when the camera is initialising, not when the user triggers the capture button.

**Comment by martinezleoml** [comment]
I found this interesting analysis about the issue: https://blog.krybot.com/a?ID=01600-b5b20131-8a84-43fa-a8f1-4d4ea17c4522

It seems that there is a bug on Google's CameraView framework. Someone opened a PR to fix it but since the project is deprecated (in favour of CameraX), it's still open: https://github.com/google/cameraview/pull/267

**Comment by Filippo39** [comment]
I have the same problem, the device models on which it happens are:
- POCO X3 NFC
- Mi 11 Lite
- Redmi Note 11
-

**Comment by martinezleoml** [comment]
Also happening on Redmi 7A.

**Comment by webdevmario** [comment]
I'm able to reproduce on the Xiaomi Redmi Note 9 (Android 10). App crashes when initializing the camera.

**Comment by aman-technyx** [comment]
facing on redmi note 11

**Comment by martinezleoml** [comment]
Same here, not resolved :/

**Comment by aman-technyx** [comment]
> Same here, not resolved :/

maybe we need to wrap the crashed code in try catch in -> node_module then patch package !!!

**Comment by aramhovsepyan** [comment]
+1

**Comment by explodingcamera** [comment]
Still occurs in expo 47 (Redmi Note 10 in my case)

**Comment by aramhovsepyan** [comment]
An ugly workaround is wrapping the crashed code and switching to cameraX on exception.

**Comment by buddbro** [comment]
I still have issues with it on Xiaomi Redmi Note 11
