### ISSUE TITLE
ITMS-90725: SDK Version Issue - Starting April 25, 2022, all iOS apps submitted to the App Store must be built with the iOS 15 SDK or later

### ISSUE THREAD

**Issue by viveksc1994** [expo/expo#16784]
I am getting a warning while submitting app to app store.

This app was built with the iOS 14.1 SDK. Starting April 25, 2022, all iOS apps submitted to the App Store must be built with the iOS 15 SDK or later, included in Xcode 13 or later.

Seems like Expo build servers will need update.

**Comment by hesingon** [comment]
Hello, has this been resolved? Still having this problem as of now

**Comment by budiryan** [comment]
Hi, having the same problem as well!

**Comment by mgdeveloper1406** [comment]
hello, having the same problem as well!

ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS 14.1 SDK. All iOS apps submitted to the App Store must be built with the iOS 15 SDK or later, included in Xcode 13 or later."

![Captura](https://user-images.githubusercontent.com/99666081/166503331-9398a80f-8e4e-4d11-b9ff-04c59e9fab72.JPG)

**Comment by cameronbrandcoders** [comment]
I just wanted to add my name to the list of people this isn't working for. We have plans to migrate our build process to EAS, but for now we need the classic `build:ios` working.

<img width="544" alt="Screen Shot 2022-05-03 at 1 57 30 PM" src="https://user-images.githubusercontent.com/50501074/166513051-ff2a9a37-d82e-48b8-97c5-814e99631dca.png">

**Comment by vasuchawla** [comment]
Not working for me as well

**Comment by vkbmca** [comment]
I can able to upload my app to appstore 3 days before, I tested completed app with My mobile IOS 15.4.1. It works well. Then I uploaded app through Xcode Version 12.4 (12D4e). Apple checked my app and Rejected my app and shown some Guidelines to fix issue. I fixed it today and tried to upload and got error message saying 

ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS 14.4 SDK. All iOS apps submitted to the App Store must be built with the iOS 15 SDK or later, included in Xcode 13 or later."

How can i resubmit my app to replace rejected app.

**Comment by smartlortuf** [comment]
Having the same problem

**Comment by SohanChotia** [comment]
Had same issue last night, found out that

Apple is forcing all new submissions to use ios 15 SDK and XCode 13 after April 25
https://developer.apple.com/news/?id=2t1chhp3

Was using Expo SDK 41, upgraded to 43, rebuild it and submitted, and it was accepted.
Expo SDk 43 said, they using XCode 13.

So upgrade your Expo sdk and rebuild, it will be fine ...

**Comment by mgdeveloper1406** [comment]
> Had same issue last night, found out that
> 
> Apple is forcing all new submissions to use ios 15 SDK and XCode 13 after April 25 https://developer.apple.com/news/?id=2t1chhp3
> 
> Was using Expo SDK 41, upgraded to 43, rebuild it and submitted, and it was accepted. Expo SDk 43 said, they using XCode 13.
> 
> So upgrade your Expo sdk and rebuild, it will be fine ...

I will try this, thanks!

**Comment by mckenziekennelly13** [comment]
Have the same issue. Any updates? Thanks.

**Comment by brentvatne** [comment]
if you are using any sdk version below 43, you need to update.

**Comment by penguin-jedi** [comment]
But sdk41 isn't deprecated yet. Why upgrading is the only workaround?

**Comment by jessietang** [comment]
> 

how i know the expo@43 is which version related the expo-cli?

**Comment by brentvatne** [comment]
@jessietang - it's the version of the expo package in your package.json

**Comment by vaibhavverma9** [comment]
I am running into the same issue, but I am on 46.0.17...

This is my package.json:
```
{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "android-build": "eas build --platform android"
  },
  "dependencies": {
    "@apollo/client": "^3.3.8",
    "@expo/config-plugins": "^5.0.0",
    "@foursquare/pilgrim-sdk-react-native": "^1.1.3",
    "@gorhom/bottom-sheet": "^2",
    "@react-native-async-storage/async-storage": "^1.17.9",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-picker/picker": "2.4.2",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^5.14.2",
    "@segment/analytics-react-native": "^2.7.0",
    "@segment/sovran-react-native": "^0.4.5",
    "apollo-link-ws": "^1.0.20",
    "axios": "^0.21.1",
    "expo": "~46.0.17",
    "expo-application": "~4.2.2",
    "expo-av": "~12.0.4",
    "expo-blur": "~11.2.0",
    "expo-clipboard": "~3.1.0",
    "expo-constants": "~13.2.4",
    "expo-contacts": "~10.3.0",
    "expo-dev-client": "~1.3.1",
    "expo-device": "~4.3.0",
    "expo-file-system": "~14.1.0",
    "expo-image-picker": "~13.3.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-linking": "~3.2.2",
    "expo-location": "~14.3.0",
    "expo-media-library": "~14.2.0",
    "expo-notifications": "~0.16.1",
    "expo-sharing": "~10.3.0",
    "expo-sms": "~10.2.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-store-review": "~5.3.0",
    "expo-updates": "~0.14.7",
    "firebase": "8.2.3",
    "graphql": "^15.5.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-confetti-cannon": "^1.5.2",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-google-mobile-ads": "^7.0.1",
    "react-native-google-places-autocomplete": "^2.2.0",
    "react-native-maps": "0.31.1",
    "react-native-paper": "^4.11.2",
    "react-native-progress": "^5.0.0",
    "react-native-purchases": "4.6.2",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-size-matters": "^0.4.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-view-shot": "3.3.0",
    "react-native-web": "~0.18.7",
    "react-navigation": "^4.4.4",
    "sentry-expo": "~5.0.0",
    "subscriptions-transport-ws": "^0.9.18",
    "typescript": "^4.9.3"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1"
  },
  "private": true,
  "name": "simmer2",
  "version": "1.0.0"
}
```

And my eas-cli version is 2.7.1. 

Here is the specific error:

Asset validation failed (90725)
SDK Version Issue. This app was built with the iOS SDK. All iOS apps submitted to the App Store must be built with the iOS 15 SDK or later, included in Xcode 13 or later. 

Asset validation failed (90135)
The executable could not be re-signed for submission to the App Store. The app may have been built or signed with non-compliant or pre-release tools.

**Comment by brentvatne** [comment]
@vaibhavverma9 - if you submitted your app from your own machine and have an older version of xcode, that could be the problem. if you use eas submit, we will use the latest version of xcode so you won't have that problem. use eas submit

**Comment by FeelHippo** [comment]
We were facing the same issue with our Github CI/CD deployment workflow to TestFlight, and this is how it was fixed:

- update *.yml workflow:
```
jobs:
  deploy_testflight_ios:
    name: Deploy TestFlight - iOS
    runs-on: macos-latest

...

        env:
          // https://github.com/fastlane/fastlane/issues/20910#issuecomment-1338965999
          ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD: false
          XCVERSION: "14.1.0"
...
```

- update ios/Flutter/AppFrameworkInfo.plist with the current MinimumOSVersion
```
  <key>CFBundleVersion</key>
  <string>1.0</string>
  <key>MinimumOSVersion</key>
  // https://stackoverflow.com/a/68146788/10708345
  <string>16.1</string>
</dict>
</plist>
```

- update ios/Gemfile.lock with the current fastlane version
```
    // https://stackoverflow.com/a/73771951/10708345
    fastlane (2.210.0)
```

- update ios/Podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # https://stackoverflow.com/a/63955114/10708345
    target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
    end
    # Start of the permission_handler configuration
    target.build_configurations.each do |config|
      # https://stackoverflow.com/a/75883614/10708345
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      # https://github.com/TimOliver/TOCropViewController/issues/533#issuecomment-1245332415
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
```
