### ISSUE TITLE
expo-camera onBarCodeScanned not trigger on production.

### ISSUE THREAD

**Issue by Nurmehemmed** [expo/expo#16791]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by Nurmehemmed** [comment]
It works on Expo Go well but not work on production mode. P.s it was working 1-2 weeks ago.

**Comment by rdfito** [comment]
Hi, same happens to me.

package.json:
"expo": "~44.0.0",
"expo-camera": "~12.1.2",

**Comment by Nurmehemmed** [comment]
> Hi, same happens to me.
> 
> package.json: "expo": "~44.0.0", "expo-camera": "~12.1.2",

Hi. I replace expo-camera Camera component with BarCodeScanner and it works now well.
https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

**Comment by rdfito** [comment]
> > Hi, same happens to me.
> > package.json: "expo": "~44.0.0", "expo-camera": "~12.1.2",
> 
> Hi. I replace expo-camera Camera component with BarCodeScanner and it works now well. https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

I was looking for alternatives, thank you 👍

**Comment by n-ii-ma** [comment]
Same thing is happening for me on SDK 49.
