### ISSUE TITLE
Detached app - running on ios is still looking for experience at exp:// instead of using bundled js

### ISSUE THREAD

**Issue by lgandecki** [expo/expo#1679]
### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0 => 16.3.0
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:

  https://exp-xde-diagnostics.s3.amazonaws.com/lgandecki-7e186349-e7b5-48db-8852-db19565c536e.tar.gz

Building for ios

### Steps to Reproduce

create-react-native-app ejectedExpoTest
ejected to expoKit
builds in xcode to simulator - works
archive and send to testflight 

### Expected Behavior

I should see the same thing I see in my simulator.

### Actual Behavior

After installing from testflight I get
"No experience found at exp://exp.host/@lgandeci/ejectedexpotest" error

I originally done this with an working app with expo, that I had to detach. I was super confused why all the versions send to testflight looked exactly the same even though everything worked in simulator. Now I assume that it just opens the exp://exp.host link instead of using the bundled js from react-native. In this case, since I never published using expo and detached right away, there is nothing there and I get an error.

Please help :)

### Reproducible Demo

I don't think the repro is helpful here, but there you go: https://github.com/lgandecki/ejected-expo-test

**Comment by lgandecki** [comment]
as always, 5 minutes after commenting.. I think I get it. closing for now.

**Comment by lgandecki** [comment]
so if anyone googles this - the exp build doesn't work for detached projects anymore so you can't create the experience that way - But! you still ARE supposed to publish (for example using expo xde). Looks like Xcode build never bundles your js code for the app store submission, it will use the experience link there, it only uses the js code when running on simulator (so you get the real life reloads that way)

**Comment by terribleben** [comment]
An Xcode Release build will bundle a cache of your JS with the native binary, and load updates from your published url (`expo.io/@your-name/your-slug`).

An Xcode debug build will load your JS from your local packager.

**Comment by terribleben** [comment]
That sounds like a great use case for publishing with [release channels](https://docs.expo.io/versions/latest/distribution/release-channels). If you do this, be sure and read the docs on how to [change the ExpoKit configuration](https://docs.expo.io/versions/latest/distribution/release-channels#using-release-channels-with-expokit) to point at that specific release channel.

**Comment by yogen-darji-hs** [comment]
hi All,

Is there any way to use publishedUrl in developmentUrl in EXBuildConstants.plist file?

I want to generate simulator build with "published url" for Facebook App Review process.

As default developmentURL will not work without expo.

Please help

**Comment by EvanBacon** [comment]
@yogen-darji-hs your issue will be addressed in the [appropriate thread](https://forums.expo.io/t/expo-detached-app-generate-ios-simulator-build-for-facebook-app-review/12235). Please do not ask questions in unrelated issues.
