### ISSUE TITLE
More informative log message when logging functions, objects, and other

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#168]
```
function someFunc(a, b) {
  // some code
}
```

- `console.log(someFunc)` currently prints `null`
- Ideally it would print `function someFunc(a, b) { }`
- It should also print anonymous functions nicely

These improvements would go into xdl/exp/xde

More info: https://github.com/react-community/create-react-native-app/issues/168
Moved from: https://github.com/expo/xdl/issues/9

**Comment by charlesvinette** [comment]
Functions should print fine in next SDK release 
https://github.com/expo/universe/pull/267

**Comment by tetreault** [comment]
@charlesvinette When is that supposed to be? This is tripping me up too.

**Comment by brentvatne** [comment]
SDK18 is scheduled for week of June 12. If you want to fix this now you can patch console.log to pre-process the logs and do something different for functions:

```
import Expo from 'expo';
let oldConsoleLog = console.log;
console.log = /* do some processing on the log, then call oldConsoleLog with the same params */
```

**Comment by dikaiosune** [comment]
@brentvatne can we close? I believe the new console logging released recently, correct?

**Comment by brentvatne** [comment]
yup
