### ISSUE TITLE
Please re-open bug https://github.com/expo/expo/issues/11806 about audio not working on iphones.

### ISSUE THREAD

**Issue by kmichnicki** [expo/expo#16808]
### Summary

Please re-open the following bug:
https://github.com/expo/expo/issues/11806

I'm experiencing the same issue. I've already commented there with as much information as I am aware of to help you reproduce the issue. Please let me know if there is any other information you need.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44.0.06

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: bare

### Reproducible demo

Mp3 audio works on android, but not on ios, specifically iphone 11.

here are the versions that I have installed.
"expo": "^44.0.6",
"expo-av": "^10.2.1",
"expo-cli": "^5.3.0",

My code is something like
```
Audio.Sound.createAsync(require("something.mp3"), {volume: 1})
    .then(({ sound }) => {
        sound.playAsync();
     });
```
I run expo publish and then try the app out on my iphone using expo go.

**Comment by hirbod** [comment]
I can't reproduce this. Working for me with external and internal audio. 

Are you sure your device silent switch is not set to mute? 
Audio won't play when the device is in silent mode, unless you overwrite this with:

```ts
      await Audio.setAudioModeAsync({
        playsInSilentModeIOS: true,
      }); 
```

before you play the audio.

**Comment by KrisLau** [comment]
> I can't reproduce this. Working for me with external and internal audio.
> 
> Are you sure your device silent switch is not set to mute? Audio won't play when the device is in silent mode, unless you overwrite this with:
> 
> ```ts
>       await Audio.setAudioModeAsync({
>         playsInSilentModeIOS: true,
>       }); 
> ```
> 
> Make sure to run this before you play the audio file.

Lol I'm dumb and spent days trying to fix this because i didn't realize the silent mode switch was on
