### ISSUE TITLE
Why does writing a string to a file and then reading the same file as a string result in different strings?

### ISSUE THREAD

**Issue by ryancole** [expo/expo#16806]
### Summary

Writing a string to a file and then reading the same file results in different strings.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43.0.0

### Environment

PS C:\Users\Ryan\source\repos\WIB-mobile> npx expo-env-info

  expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      babel-preset-expo: 8.5.1 => 8.5.1
      expo: ^43.0.0 => 43.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

I'm trying to write some code to save photo data to a file.

I read in the photo data, which comes in as base64 string from react native (Expo), and then I decode it. I immediately write that decoded string to a file.

When I read that file that should contain all of the photo data, all I'm getting back are 4 characters when I expect many megabytes-worth of characters.

Does anybody know how to write this decoded base64 string to a file using Expo? Is this a bug? Below is my code ...

      const fileUri = `${directoryPath}/${today.getTime()}/${fileName}`;

      // this reads us the base64 encoded image data
      const imageString = await FileSystem.readAsStringAsync(
        image.uri,
        { encoding: FileSystem.EncodingType.Base64 }
      );

      const fooString = Base64.decode(imageString);

      // write the decoded photo data to a file
      await FileSystem.writeAsStringAsync(fileUri, fooString);

      // read back the file so we can make sure all the data was written
      const blah = await FileSystem.readAsStringAsync(fileUri);

      const photoInfo = await FileSystem.getInfoAsync(fileUri);

      console.log({
        fileUri,
        fooStringLength: fooString.length,
        blahLength: blah.length,
        equals: blah === fooString,
        photoInfo
      });

You can see it's pretty straightforward, so I must be missing something? Below is the output of that `console.log` ...

    Object {
      "blahLength": 4,
      "equals": false,
      "fileUri": "file:///var/mobile/Containers/Data/Application/33EB7A6F-AA1A-42BF-B252-9A5088A906C6/Documents/ExponentExperienceData/%2540anonymous%252FWIB-mobile-12902e68-9c57-4230-a3df-aaa355c3edf1/20220328184945/1648511392902/Right.jpg.enc",
      "fooStringLength": 2953317,
      "photoInfo": Object {
        "exists": true,
        "isDirectory": false,
        "modificationTime": 1648511394.334474,
        "size": 4415423,
        "uri": "file:///var/mobile/Containers/Data/Application/33EB7A6F-AA1A-42BF-B252-9A5088A906C6/Documents/ExponentExperienceData/%2540anonymous%252FWIB-mobile-12902e68-9c57-4230-a3df-aaa355c3edf1/20220328184945/1648511392902/Right.jpg.enc",
      },
    }

You can see the lengths don't match. Also, if I print out both `fooString` and `blah`, which are the before and after strings for comparison, the `fooString` looks correct to me and how I expect it to look but the `blah` is only like 4 characters worth of data. Below is the incorrect content of `blah` string and the file ...

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/HVXXf.png

**Comment by ryancole** [comment]
I modified an existing snack to show my situation. This snack gives the option to take a photo or select an existing photo. I put my code in the select an existing photo from the photo library handler. This snack shows that when I write my data to a file and then read it back the data does not match. Any ideas why?

https://snack.expo.dev/@rcoleils/camera

**Comment by geoffdaw** [comment]
I have been investigating a problem that seems to be related when reading an image chosen by ImagePicker. I too am getting a 4 character result but if I use Base64 instead of UTF8 it works fine.

The code I am running is: 

```
        FileSystem.getInfoAsync(res.uri)
        .then (res => {
          console.log(res);
          FileSystem.readAsStringAsync(res.uri, { encoding: FileSystem.EncodingType.UTF8})
          .then (info => {
            console.log(info.length);
            console.log(info);
            FileSystem.readAsStringAsync(res.uri, { encoding: FileSystem.EncodingType.Base64})
            .then (info => {
              console.log(info.length);
            })
            })
        })
```

The console output is: 

```
Object {
  "exists": true,
  "isDirectory": false,
  "modificationTime": 1654272126,
  "size": 340371,
  "uri": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252FGalleryLoader-661d9475-1955-4d5f-a90e-0cd69449bfb9/ImageManipulator/3d63394f-ed34-4b76-acb3-aa3de13db428.jpg",
}
4
����
453828
```

### Environment
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.2.1 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

"expo-file-system": "~13.1.4"

### Platform
Android Emulator
