### ISSUE TITLE
expo config plugins requires to disable auto-linking for some packages on expo bare workflow

### ISSUE THREAD

**Issue by KROSF** [expo/expo#16819]
### Summary

expo config plugins require to disable auto-linking for packages that works great without expo or expo managed workflow,

but in a bare project, some fails because they add some workarounds to work with expo like [@react-native-google-signin/google-signin](https://github.com/react-native-google-signin/google-signin/tree/v7.2.2) or expo add some workarounds to work reanimated <= 2.5.0

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

43, 44

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /var/folders/bw/vfyrwpdd6rjcbxmbxmpzsn680000gn/T/frum_36356_1648590335326/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 1 Bumblebee 2021.1.1 Patch 1
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.3 => 43.0.3 
      react: 17.0.2 => 17.0.2 
      react-native: ^0.65.1 => 0.65.1 
    Expo Workflow: bare

### Reproducible demo

for reanimated 2.5.0 > https://github.com/muchobien/ownda-app/tree/issues/expo-reanimated

for google-sign-in >
- Create a bare project
- Add expo@43
- Add  @react-native-google-signin/google-signin
- yarn run ios

### Related issues

- https://github.com/react-native-google-signin/google-signin/issues/1047
- https://github.com/software-mansion/react-native-reanimated/issues/3088

**Comment by Kudo** [comment]
hi there! for reanimated, this pr https://github.com/software-mansion/react-native-reanimated/pull/3113 is going fix the problem. for google-signin, this pr https://github.com/react-native-google-signin/google-signin/pull/1042 should addressed the problem as well. ideally, we should try to be compatible for non expo projects as much as possible and excluding modules from autolinking  should not be necessary. if there're any other broken modules, please let us know. thank you!
