### ISSUE TITLE
Unable to read file returned from `DocumentPicker`

### ISSUE THREAD

**Issue by riwu** [expo/expo#1681]
### Environment
```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/riwu-1fee4770-788f-458d-9176-1739c4b5f9cc.tar.gz
```
### Reproducible Demo
```
import React from 'react';
import { Button, View, Text } from 'react-native';
import { DocumentPicker, FileSystem } from 'expo';

class App extends React.Component {
  state = {
    data: null,
  };
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center' }}>
        <Button
          title="Click"
          onPress={async () => {
            const result = await DocumentPicker.getDocumentAsync({
              type: '*/*',
            });
            if (result.type === 'cancel') return;
            console.log('uri', result.uri);
            try {
              const info = await FileSystem.getInfoAsync(result.uri);
              this.setState({ data: info });
              console.warn('info', info);
              const content = await FileSystem.readAsStringAsync(result.uri);
              console.warn('content', content);
              this.setState({ data: content });
            } catch (e) {
              this.setState({ data: e.message })
            }
          }}
        />
        <Text>{JSON.stringify(this.state.data)}</Text>
      </View>
    );
  }
}

export default App;
```
https://snack.expo.io/@riwu/documentpicker

I selected a plain text file.

On Android it fails at `FileSystem.readAsStringAsync` with 
> Error: Unsupported scheme for location 'content://com.android.providers.downloads.documents/document/19778'.]

On iOS it fails at `FileSystem.getInfoAsync` with 
> Error: File 'file:///private/var/mobile/Containers/Data/Application/86126CD3-95A3-4F10-ABD7-6EFE0772A9FC/tmp/host.exp.Exponent-Inbox/a.txt' isn't readable.]

**Comment by terribleben** [comment]
@aalices should DocumentPicker files be readable by Expo FileSystem?

**Comment by aalices** [comment]
IMO it should, like ImagePicker does, @janicduplessis if there wasn't any particular reason for not saving an Expo's internal file I'll add this

**Comment by rodrix** [comment]
Hi Dream Team, I'm stucked with this issue too. 
Some news?
Thnx. :}

**Comment by randomor** [comment]
It's not very obvious from the docs. Found the solution here: https://forums.expo.io/t/read-a-contents-from-dropbox-with-documentpicker-filesystem/1976/5

Essentially, we have to download the file first:
```
FileSystem.downloadAsync(
  pickerResponse.uri,
  FileSystem.documentDirectory + 'get_data_from_dropbox.json'
).then(({ uri }) => {
  console.log('Finished downloading to ', uri)
  FileSystem.readAsStringAsync(uri).then(fileResponse => {
    console.log(fileResponse)
  })
}).catch(error => {
  console.error(error)
})
```

**Comment by riwu** [comment]
@randomor thanks, works for iOS but not Android, `downloadAsync` rejected with error:
> unexpected url: content://com.android.providers.downloads.documents/document/19894

Hope the API can be changed to allow reading of file content directly rather than having to create a copy via `downloadAsync` first...

**Comment by narender2031** [comment]
content://com.android.contacts/contacts/10720/photo 
how can access this from with expo. how can I read it with the file system?
