### ISSUE TITLE
Scroll events don't work for Expo Web

### ISSUE THREAD

**Issue by camello222** [expo/expo#16822]
### Summary

Scroll related listeners (like onScroll) from ScrollView and corresponding childs, like FlatList, are not working on Expo for Web, while they do for mobile. This divergence is unexpected, and you can verify it following the repro steps of repro section below.

You can see my full sample here: [flatlist-simple](https://snack.expo.dev/@camello222/flatlist-simple)
While the events are logged for the iOS implementation during scroll, they are not for Web.

This is the listener I am adding:

```
...
return (
    <SafeAreaView style={styles.container}>
      <FlatList
        data={DATA}
        renderItem={renderItem}
        keyExtractor={item => item.id}
        onScroll={(event) => {
          console.log("scroll");
        }}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: StatusBar.currentHeight || 0,
  },
...
```

Scroll events do work for "react native for web" (see [codesandbox](https://codesandbox.io/s/peaceful-hamilton-s2k1i?file=/src/App.js:161-645) and try it there), natively, but somehow, with Expo managed implementation, they don't work, which should be a bug or lack of support that should be explicitly stated..

I haven't found a way to workaround this issue. Necolas suggested in [this](https://github.com/necolas/react-native-web/issues/1827) post, that we add #root style overrides, but I am not sure how to achieve that through Expo's managed workload, as his solution was implemented for 'react native for web'.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

 "expo": "~44.0.0",     "expo-status-bar": "~1.2.0",     "react": "17.0.1",     "react-dom": "17.0.1",     "react-native": "0.64.3",     "react-native-web": "0.17.1"

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo

Sack demo: [flatlist-simple](https://snack.expo.dev/@camello222/flatlist-simple)

I took the flatList demo from Expo documentation and just placed more items in the DATA list and added console.log("scroll") to the onScroll listener.

1) Use dev tools to view logs from Web version and you will see nothing is logged when you scroll.
2) Change to iOS or Android version, and "scroll" events are indeed logged.

**Comment by byCedric** [comment]
Hi @camello222! [I updated your example with a fix that should enable the `onScroll` event handler.](https://snack.expo.dev/@bycedric/expo-issue-16822) Its due to the FlatList's ScrollView being the content's height on web (and let the browser handle the scroll). By setting a specific height to the FlatList, the ScrollView handling the events is picking it up properly. [See this comment for more info](https://github.com/necolas/react-native-web/issues/1592#issuecomment-905970879)

Hope this helps!

**Comment by camello222** [comment]
@byCedric Did you verify whether your fix works? It doesn't for me. I don't see any events being logged in the developer's console...

**Comment by naytun** [comment]
My solution is to add ` contentContainerStyle={{aspectRatio: 1}}` to the FlatList.
