### ISSUE TITLE
Webp images are not being loaded on iOS 13 and below versions

### ISSUE THREAD

**Issue by ggepenyan** [expo/expo#16827]
I'm using SDK 44 and webp images are not being loaded on ios 13 and below versions. They load on higher versions and all android devices. Is there any way I can fix it?

**Comment by byCedric** [comment]
Hi @ggepenyan, unfortunately this is an iOS limitation. WebP support only landed on iOS 14+, [as the documentation points out](https://developer.apple.com/documentation/uniformtypeidentifiers/uttype/3551599-webp). 
![image](https://user-images.githubusercontent.com/1203991/160884879-e7422a25-c300-44c9-b56d-ca1ff897f02b.png)

You could try adding custom native libraries that work around that limitation, such as:
- [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image)
- [react-native-webp-format](https://github.com/Aleksefo/react-native-webp-format)

Hope this helps!
