### ISSUE TITLE
Expo Updates runtimeVersion cannot end with 0 on Android, 0 is removed

### ISSUE THREAD

**Issue by AronBe** [expo/expo#16838]
### Summary

- Setting `runtimeVersion` in `app.json` to `1.20` will get rounded to `1.2` on Android when retrieving through `Updates.runtimeVersion`. 
- As a result, OTA update cannot be delivered for version `1.20` as they are not considered compatible probably. 
- `AndroidManifest` displays the runtimeVersion value correctly as `1.20`

The issue has already been mentioned here https://github.com/expo/expo/issues/13349 but the underlying problem was not resolved and linked PR probably resolved something else.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.21.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 26, 27, 28, 30, 31, 32
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 32.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
          "expo-updates": "~0.11.6",
    Expo Workflow: bare

### Reproducible demo

reproduction by running `expo run:android --variant release`: https://github.com/AronBe/expo-runtime-version-error

See result:
<img src='https://user-images.githubusercontent.com/32416348/160919943-8ef4a0da-ed9b-43d8-a207-2633670d328e.png' width='400'>

**Comment by ide** [comment]
IIRC the issue is that Android doesn't use strong typing and the string "1.20" is coerced to a float. Based on https://github.com/expo/expo/pull/13365 it sounds like we have made it possible to store the versions of runtimes prefixed with `string:` so that Android forcibly parses them as strings rather than floats.

**Comment by AronBe** [comment]
@ide Thanks for explanation of the PR. Prefixing with `string:` works for `expo-updates` library as the PR assumed...
![image](https://user-images.githubusercontent.com/32416348/161739455-704ecf1e-3603-4397-9327-f27e6c1f8997.png)

...but having `"runtimeVersion": "string:1.20"` in `app.json` breaks other things
1. I get following error when trying to run `expo publish`
> Error: Problems validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: runtimeVersion - 'runtimeVersion' should be a a string beginning with an alphanumeric character followed by any combination of alphanumeric character, "_", "+", ".","(",")" or "-". Example: "1.0.3a+"..
 • Field: runtimeVersion - 'runtimeVersion' should be a an 'exposdk:' prefix followed by the SDK version of your project. Example: "exposdk:44.0.0"..
 • Field: runtimeVersion - should be object.
 • Field: runtimeVersion - should match exactly one schema in oneOf.
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.

2. Also getting linting warning, probably from Expo VS code extension
> String does not match the pattern of "^[a-zA-Z\d][a-zA-Z\d._+()-]*$".

**Comment by ide** [comment]
We're rolling out a change soon that will reject floatlike strings that end in zero.

There are probably still some values that can slip through the cracks: namely floatlike strings that describe a number that can't be expressed with IEEE 754.

You can avoid the problem altogether by not using floatlike strings. Using semver strings with two dots/periods avoids the issue.

**Comment by ide** [comment]
Closing since this was addressed (disallow version strings that can be misinterpreted by Android) for SDK 45+ apps.

**Comment by shane-sg** [comment]
@ide I'm not understanding the following suggestion.

> You can avoid the problem altogether by not using floatlike strings. Using semver strings with two dots/periods avoids the issue.

You could still end up with a trailing `0` at the end with semver.  

```1.2.10```

**Comment by ide** [comment]
1.2.10 won't get coerced to a float so that won't cause a problem. 1.20 was the problem in the original report.

**Comment by shane-sg** [comment]
Oof... this is one of those questions that you wish that you didn't ask after you see the answer 🤣

Thanks for the response!
