### ISSUE TITLE
Keyboard is unresponsible with Performance monitor

### ISSUE THREAD

**Issue by comav** [expo/expo#16835]
### Summary

It is unable to type with the Performance monitor enabled because the keyboard is irresponsible. Occurs on Android 12 (MIUI 13)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.0

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.16 Fedora Linux 35 (Workstation Edition)
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo

```
import { StyleSheet, View, TextInput } from 'react-native';
export default function App() {
  return (
    <View style={styles.container}>
      <TextInput
        value='sample'
    />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by kollinmurphy** [comment]
I'm having the same issue with a managed project using SDK 46 on Android 12.

**Comment by srinivastalnikar** [comment]
same issue here
