### ISSUE TITLE
blank AppLoading

### ISSUE THREAD

**Issue by eeeman1** [expo/expo#1684]
All greetings, I use the component of AppLoading, there are two problems - I want to say that when the download occurs, I see just a white screen.
Besides it works incorrectly, if in some kind of a fetch request comes undefined to me, the promise will still continue despite the result.

```
    async loadResourcesAsync() {
        
        return Promise.all([

            Font.loadAsync({
                'budicons': require('../../assets/fonts/fontello.ttf'),
                'FiraSansExtraCondensed': require('../../assets/fonts/FiraSansExtraCondensed-Regular.ttf'),
                'FiraSansExtraCondensedBold': require('../../assets/fonts/FiraSansExtraCondensed-Bold.ttf')
            }),

            fetchManager(
                'getGames',
                null,
                data => {
                    // console.log(data);
                    data ? this.props.setData('GET_GAMES', data) : null;
                }),

            fetchManager(
                'index',
                null,
                data => {
                    // console.log(data);
                    data ? this.props.setData('INDEX_DATA', data) : null;
                }),

            fetchManager(
                'checkAuth',
                null,
                data => {
                    // console.log(data);
                    data && data.result ? this.props.setData('CHECKOUT', data) : null;
                })

        ])

    }

.....

<AppLoading
                                    startAsync={this.loadResourcesAsync}
                                    onError={(err) => this.setState({error: err})}
                                    onFinish={() => this.setState({isLoadingComplete: true})}
                                />

```
for example, if there is an incorrect address in the fetch request, promise will still continue to work and the AppLoading will start the onFinish

"expo": "^25.0.0"

"sdkVersion": "25.0.0",

**Comment by anp** [comment]
Hi! It's going to be pretty difficult to figure out exactly what's going on in this case without a reproducible example. If you're able to reproduce this on [Snack](https://snack.expo.io) and share it here, that would be phenomenal. If the problem doesn't occur there, please try to make a blank Expo project and add just enough code until you see the behavior again, upload it to GitHub, and post a link here. I'll give this a close in the meantime, but we'll re-open if you can help us identify the bug here. Thanks!

**Comment by eeeman1** [comment]
To reproduce the problem, you just need to add the AppLoading component to any place in the application
