### ISSUE TITLE
Media Library - Delete assets doesn't work on Android

### ISSUE THREAD

**Issue by nartydev** [expo/expo#16848]
### Summary

Hello,

I want to delete assets with media library but when I call MediaLibrary in my epic I receive an error:
`Could not delete file`, I send an array of id give by `MediaLibrary.getAssetsAsync()`

I have also tried with react-native-fs library but that doesn't work also.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo

https://snack.expo.dev/O8XKIs2Yh

I have try to reproduce something in Snack but that doesn't work when we need to permissions

**Comment by burak4ydin** [comment]
same issue with android 12

**Comment by jonasguerra** [comment]
Still without solution, same problem here, expo 46

**Comment by nartydev** [comment]
Yes I'm already in the same situation

**Comment by joeburmon** [comment]
I'm on sdk 49, and I think this problem still exist :(

**Comment by mathieupost** [comment]
Also having this issue on Android with SDK 50 & 51. Also tried `expo-file-system` to delete using the file uri, but gives a `java.io.IOException Location 'file://.....' isn't deletable.`

Anyone found another library or a workaround?

**Comment by cesarjhony** [comment]
I have the same problem here on Android 14, expo sdk51

**Comment by helloukey** [comment]
Same issue
