### ISSUE TITLE
[expo-in-app-purchases] getProductsAsync always returns a results array of 1 product even when there are more products added to Google Play Console

### ISSUE THREAD

**Issue by ancarofl** [expo/expo#16849]
### Summary

[expo-in-app-purchases] **getProductsAsync** always returns a results array of one product even when there are more products added to Google Play Console.
The product with an earlier creation date is always shown, as such:
If I only include one id in in the productIds array then it's retrieved correctly. However if there is more than one id, only the earliest created one is shown.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      npm: 8.5.5 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.2 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo

```
import React, { useState } from 'react'
import { Button, FlatList, Platform, SafeAreaView, StyleSheet, Text, View } from 'react-native'
import * as InAppPurchases from 'expo-in-app-purchases';

const Products = () => {
    const [ disabled, setDisabled ] = useState(false);

    const productIds = Platform.select({
        android: ['product_id_1', 'product_id_2'], // add your own
    });

    const showProducts = async () => {
        await InAppPurchases.connectAsync().then(() => {
            setDisabled(true);
        });

        const { responseCode, results } = await InAppPurchases.getProductsAsync(productIds);
        if (responseCode === InAppPurchases.IAPResponseCode.OK) {
            console.log(results); // this should return the valid product_id_1 and product_id_2 results, instead only one is returned
        }

        await InAppPurchases.disconnectAsync().then(() => {
            setDisabled(false);
        });
    }

    return (
        <SafeAreaView style={styles.container}>
            <View style={styles.container}>
                <Button title={'Show products'} onPress={() => showProducts()} disabled={disabled} /> 
            </View>
        </SafeAreaView>
    )
}

export default Products;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
});
```

**Comment by ancarofl** [comment]
It works now. It probably has to do with having waited a couple of hours. Nonetheless if only one id was in the productIds array, the product was returned correctly even if it had just been added. That seems weird.

**Comment by cameronnapoli** [comment]
I'm seeing the same issue. @ancarofl Did this problem ever happen again after your issue was resolved?

**Comment by ancarofl** [comment]
@cameronnapoli It has not happened to me since then. Did waiting fix it for you as well?

**Comment by cameronnapoli** [comment]
Also only happened once for me

**Comment by RohovDmytro** [comment]
Happening to me semi-randomly. I've added a new subscription and it's just not being loaded. Only 1 product is loaded. Looking deeper...
