### ISSUE TITLE
Lottie autoplay is not working with Expo SDK 44

### ISSUE THREAD

**Issue by danielu221** [expo/expo#16858]
### Summary

When using Lottie with default setup I am unable to play animation using autoplay attribute, it shows only a first frame and animation doesn't start. When I am using the same project without Expo it is working properly.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: managed

```

### Reproducible demo

My code:
```
<View>
          <LottieView
              source={require('../assets/success-lottie.json')}
              style={{width: 300, height: 300}}
              autoPlay={true}
              loop={false}
          />
          <Text
              category="h1"
              style={{textAlign: 'center', color: theme['color-primary-500']}}>
            Email sent
          </Text>
</View>
```

Lottie versions installed via: `expo install lottie-react-native`:
 ```
"lottie-ios": "3.2.3",
"lottie-react-native": "5.0.1",
```

**Comment by hozjanmarko** [comment]
Having the same issue on the managed workflow, cannot get any animation to start.

**Comment by DJFriar** [comment]
I am having this issue on my iOS device, but not my Android device.

`expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.8.0 - /opt/homebrew/bin/node
      npm: 8.5.5 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: managed`

**Comment by logicman** [comment]
> Same issue here: worked around it like this.
> 
> Not working:
> 
> ```
> const ref = useRef<AnimatedLottieView>(null);
> 
>     useEffect(() => {
>         ref.current?.play();
> 
>         return () => {
>             ref.current?.reset();
>         }
>     }, []);
> ```
> 
> Working workaround:
> 
> ```
> const ref = useRef<AnimatedLottieView>(null);
> 
>     useEffect(() => {
>         setTimeout(() => ref.current?.play());
> 
>         return () => {
>             ref.current?.reset();
>         }
>     }, []);
> ```

I am having the same issue. Tried your code and it still doesn't work. The lottie animation shows up as static before my data is loading (does not animate)....

**Comment by logicman** [comment]
> Same issue here: worked around it like this.
> 
> Not working:
> 
> ```
> const ref = useRef<AnimatedLottieView>(null);
> 
>     useEffect(() => {
>         ref.current?.play();
> 
>         return () => {
>             ref.current?.reset();
>         }
>     }, []);
> ```
> 
> Working workaround:
> 
> ```
> const ref = useRef<AnimatedLottieView>(null);
> 
>     useEffect(() => {
>         setTimeout(() => ref.current?.play());
> 
>         return () => {
>             ref.current?.reset();
>         }
>     }, []);
> ```

Thanks. This works sometimes...if I save and see the simulator it shows me a static lottie image. However, then when I goto the editor, make an error, save and then fix the error and save and come back to the simulator....it "sometimes" shows me the animation. I am also using React Native Debugger and simulating a slow connection. 

Seems extremely strange! Any idea what might be going on?

**Comment by pensivej** [comment]
Same here. Any progress on this?

**Comment by Kastango** [comment]
Same here.

**Comment by ScreamZ** [comment]
Same issue here, strangely working, ping me when you get some fix ahah :p

**Comment by brentvatne** [comment]
if someone can demonstrate that this is an issue in our usage of lottie i'm happy to investigate, but as far as i know this is just an upstream lottie issue https://github.com/lottie-react-native/lottie-react-native/issues/832

**Comment by brentvatne** [comment]
here's a repository where i attempted to reproduce the issue and could not: https://github.com/brentvatne/test-lottie-autoplay

**Comment by jacksonHendric** [comment]
@brentvatne  Still having the exact same issues. I've tried all the solutions in #832 but it's very hit or miss. Has anyone been able to solve this? It's creating a lot of broken ui elements after working great for a long time. 
Also why does expo downgrade the package version to 5.0.1?

**Comment by brentvatne** [comment]
@jacksonHendric - please create a new issue with a minimal reproducible example if you are experiencing this. expo installs the lottie version that is compatible with the sdk version you are using. sdk 46 uses 5.1.3 https://github.com/expo/expo/blob/main/packages/expo/bundledNativeModules.json#L87

**Comment by asdelatoile** [comment]
I use the event "onLayout" for autoplay
`
<LottieView
  ref={lottieViewRef}
  onLayout={() => {
    lottieViewRef.current?.play();
  }}
  source={loadingAnimation}
  loop
/>
`

**Comment by mordechaim** [comment]
@asdelatoile Genious solution, this seems to solve the issue for me (since it only happens occasionally I can't yet confirm)

**Comment by jacksonHendric** [comment]
I have tried this before, I can’t explain why it’s  unstable but sometimes,
this doesn’t work.

The weirdest issue. I don’t understand how no one else has run I to this
with expo 45.

I have tried with new projects as well with the same issue.

Only solution that seems to work is to useEffect and run the animation on
mount which is just super hacky.

**Comment by RickyAvina** [comment]
Issue still exists with expo 47.0.12, @asdelatoile's solution worked for me however.

**Comment by jossai1** [comment]
> I use the event "onLayout" for autoplay (SDK 46) `<LottieView ref={lottieViewRef} onLayout={() => {lottieViewRef.current?.play()}} source={loadingAnimation} loop />`

worked for me

**Comment by denisfelic** [comment]
I encountered this issue when using version `^6.3.1` of the `lottie-react-native` library. However, when I switched to version "5.1.6," the problem was resolved. It's important to ensure that you include the autoPlay property in your configuration.

I confirmed this solution while testing it on a managed workflow in the Android emulator. Here's the updated snippet with the working version:

```
"lottie-react-native": "5.1.6"
```

By using version 5.1.6 and including the autoPlay property, you should be able to resolve the issue successfully.
