### ISSUE TITLE
Playerdata.java error causing crashes in production 

### ISSUE THREAD

**Issue by amansahil** [expo/expo#1686]
Some of my users are experiencing crashes in the app or the audio stops playing for them. And going through the records it seems to be at playerdata.java. The reports show this

java.lang.OutOfMemoryError:
` at abi26_0_0.host.exp.exponent.modules.api.av.player.PlayerData.progressUpdateLoop (PlayerData.java:146)
  at abi26_0_0.host.exp.exponent.modules.api.av.player.PlayerData.access$000 (PlayerData.java:19)
  at abi26_0_0.host.exp.exponent.modules.api.av.player.PlayerData$1.run (PlayerData.java:151)`

So I use audio as background music for the game which is continuously looped and there is audio played when user interacts with app.

Note: No crashes in iOS yet

Here is a snack on how my audio is set up: https://snack.expo.io/Bk4M1J6hf

After a while of redirecting mounting the components a few times due to the redirect or just by pressing the button a few times continuously all audio stops 

This is the error I get when I add a catch statement to playbgSound();

Encountered an error while setting status!
```
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:80:57 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:400:4 in __invokeCallback
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:139:28 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:316:6 in __guardSafe
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:138:17 in invokeCallbackAndReturnFlushedQueue
```

**Comment by sjchmiela** [comment]
Hi @amansahil, thanks for the report! Yeah, this looks like Android-specific problem, let's hope it has no iOS equivalents. 😃 I see two different issues mentioned here:

1. `OutOfMemoryError`
2. `Encountered an error while setting status!`

So, a couple of questions:

- Could you try the latest SDK 27? Maybe the problems were solved in the latest release. 🙂 
- Why are you setting `isLooping` to `-1`? I think it'd be better if it was a boolean, as per the [documentation](https://docs.expo.io/versions/v27.0.0/sdk/av#islooping--a-boolean-describing-if-the).
- Do you have some more specific scenarios when the two issues occur? I wasn't able to reproduce this issue with the Snack provided, should I tap the button `x` times, or wait for the error to occur? 🤔

**Comment by amansahil** [comment]
@sjchmiela All you need to do is press the button a few times , then the audio will stop. The app won't crash. However any future audio sessions will not play. This is the error that's logged.

**Comment by sjchmiela** [comment]
Ok, so there are two things:

1. I think Expo Snack isn't compatible with MP3 files (you cannot import an MP3 file and `require` it as you would do with an image or a JS{,ON} file). So I changed `loadedSuccessSound` to `{ uri: '…' }`.
2. Then I encountered the `Encountered an error while setting status!` error; I inspected it and found out it was actually saying that it was not possible to use value of type `String` (`"-1"`) as `Boolean`.

The second error occurred due to running `setIsLoopingAsync('-1')`. I changed it to `setIsLoopingAsync(false)` and it worked properly since then (i. e. tapping the button starts to play another instance of the music).

Could you please try this Snack and see whether using the API like there fixes the issues described? https://snack.expo.io/SklZHD3Rz

**Comment by amansahil** [comment]
@sjchmiela I have used MP3 before, now the background music does continue to play, however the click sound goes away, I've just replaced the audio with a click sound. Just repeatedly click on the button without stop, the click audio will stop.

**Comment by amansahil** [comment]
@sjchmiela Wouldn't replayAsync only work on something that's already played.

**Comment by sjchmiela** [comment]
I don't think so, but you could always programatically use `playAsync` first time and then `replayAsync`. 🙂

**Comment by amansahil** [comment]
@sjchmiela The problem continues to persists, however using replayAsync did sort out an issue with the audio I was facing on iOS though, so cheers to that.

**Comment by mattwkelly** [comment]
Why was this closed? We're seeing this issue as well. It's the #1 source of crashes in our app currently.

**Comment by sjchmiela** [comment]
Hi, @mattwkelly, sorry to hear that! Are you using SDK30? Could you, please, open a new issue with more debugging details? 🙂
