### ISSUE TITLE
EAS builds always report colorScheme = light on Android

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#16864]
### Summary

When building with EAS (dev-client, and apk), `useColorScheme`  and `Appearance.getColorScheme()` always return `light`.

⚠️This may be an upstream issue in `react-native`, but in that case it's good that this issue exists here as well.

**Other platforms**

- Works on web, not tested on iOS. 
- Works with a previously build app on classic (expo-build) (SDK 43).
- Reproducible on Snack, Expo Go (Android).

(Web)
![image](https://user-images.githubusercontent.com/1964376/161165295-a1e9f66a-593a-44af-8d5b-fda98f438c4a.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.4.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\.yarn\bin\yarn.CMD
      npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 28.0.3, 29.0.3, 30.0.0, 31.0.0, 32.0.0
        System Images: android-30 | Google Play Intel x86 Atom
    npmPackages:
      @expo/webpack-config: ~0.16.19 => 0.16.19
      expo: ~44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
  ```

### Reproducible demo

```typescript
import { useColorScheme } from 'react-native'

export default function App() {
  const scheme = useColorScheme()
  return <Text>{scheme}</Text>
}
```

https://snack.expo.dev/@derk-jan/colorscheme-is-always-light

**Comment by brentvatne** [comment]
hi there! can you share a project that we can clone on github? snack isn't great for this because the snack app is locked to light mode

**Comment by SleeplessByte** [comment]
Ugh. When making a fresh project, again, for you, I found out that I was missing a "new" property when upgrading the "old" project:


https://docs.expo.dev/guides/color-schemes/#managed-projects

> The available options are: `automatic` (follow system appearance settings and notify about any change user makes), `light` (restrict app to support light theme only), and `dark` (restrict app to support dark theme only). If this key is absent, the app will default to the `light` style.

```json
{
  "expo": {
    "userInterfaceStyle": "automatic"
  }
}
```

It then continues:

> In EAS Build and custom development builds you'll need to install the native module `expo-system-ui` otherwise the `userInterfaceStyle` property will be ignored. Running `expo config --type introspect` will warn if the project is misconfigured:
> ```text
> » android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
> ```

Fun fact: fresh projects with `npx expo-cli init` and then choosing `TypeScript (tabs)` is _missing_ this package:

![image](https://user-images.githubusercontent.com/1964376/162327816-33171bf0-8d29-471f-bf37-77aef3864a76.png)

And it complains during build:

![image](https://user-images.githubusercontent.com/1964376/162327883-8c7a2976-984f-4fe9-900e-c1d736d316a5.png)

Yet, it works. 

If I _remove_ this line, it doesn't work. 

@brentvatne I don't know if you want to take some action here. At least it's not a real bug, and rather me not upgrading "correctly". I find it peculiar that the old default was "it works" and the new default is "it's `light`", but alas, I can continue my work. It is concerning that the docs say that if you don't have a package it will not work, but yet it does, and that the standard template heavily relies on color scheme but doesn't have this package.

**Comment by brentvatne** [comment]
@SleeplessByte - thanks for catching that! I'll add expo-system-ui to the tabs template

**Comment by SleeplessByte** [comment]
Also: it will work in eas build without that package, but not in the devclient without that package, which was interesting 🤔🙃

**Comment by brentvatne** [comment]
https://github.com/expo/expo/commit/42ac1eb97f691c5067ca3844614b3cd7e00d921a

this will go out with sdk 45 around the end of the month
