### ISSUE TITLE
[babel-preset-expo] v8.5.0 breaks `babel-plugin-module-resolver` when using JSON Babel config

### ISSUE THREAD

**Issue by jhogervorst** [expo/expo#16879]
### Summary

When using version 8.5.0 or later of `babel-preset-expo`, `babel-plugin-module-resolver` no longer works. When using an aliased import, an error “Unable to resolve module” is shown.

As everything worked fine up to version 8.4.1, and it’s broken when using version 8.5.0, I suspect some change in version 8.5.0 is causing this problem.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /opt/homebrew/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.5.5 - /opt/homebrew/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.5.0 => 8.5.0 
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: managed
```

### Reproducible demo

See repo: https://github.com/jhogervorst/module-resolver-test

Check out the first commit (https://github.com/jhogervorst/module-resolver-test/commit/57c01517fcf853c3c37884c9d66b3f0e147f594d) to see the project in a working state, using version 8.4.1 of `babel-preset-expo`.

Check out the last commit to see the error occurring:

```
Unable to resolve module test/Module from module-resolver-test/App.js: test/Module could not be found within the project or in these directories:
  node_modules
```

**Comment by byCedric** [comment]
Hi @jhogervorst! Thanks for writing in. It seems like an issue when using `babel.config.json`. If you use the default `babel.config.js`, it does seem to work fine:

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolver',
        {
          root: ['./'],
          alias: {
            test: './test',
          },
        },
      ],
    ],
  };
};
```
