### ISSUE TITLE
`updates.url` property in app.json bug

### ISSUE THREAD

**Issue by Stevemoretz** [expo/expo#16889]
### Summary

I've stuck with this in the last 2 days.
trying to get this to work : https://docs.expo.dev/distribution/hosting-your-app/
I'm also using the EAS build.

It doesn't work at all.

at the end I tried to put `"fallbackToCacheTimeout": 300000` the weird thing is that the app loads instantly without waiting on the splash screen and it never loads the new version no logs about, any request to my github page also!

app.json : 

```json
{
  "expo": {
    "name": "ota-app",
    "slug": "ota-app",
    "version": "1.0.4",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 300000,
      "url" : "https://stevemoretz.github.io/expo-ota-app/"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.stevemoretz.otaapp"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

eas.json :

```json
{
  "cli": {
    "version": ">= 0.48.2"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "channel": "preview",
      "ios": {
        "distribution": "internal",
        "simulator": true
      },
      "android": {
        "distribution": "internal",
        "buildType": "apk"
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

Building with : eas build --profile preview

The result is : `This is the native app.`
But it should clearly become : https://github.com/Stevemoretz/expo-ota-app/blob/0edd043615935e1d6d94f30b58baeff6609b1831/App.js#L7 ie : `This is the OTA Update!`

After installing and opening the app on the simulator despite the value of `fallbackToCacheTimeout` it instantly shows `This is the native app.`

Here are the logs when I open the app: 
https://gist.github.com/Stevemoretz/f2c601cb69bdbf70cfb1823ddc6e9757

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.2 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29, 32
        Build Tools: 28.0.3, 29.0.2, 29.0.3
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: managed

"expo-updates": "~0.11.6",

### Reproducible demo

Here's my minimal example : 
https://github.com/Stevemoretz/expo-ota-app

1. `expo export --public-url https://stevemoretz.github.io/expo-ota-app/`
2. commit to -> https://github.com/Stevemoretz/expo-ota-app/tree/gh-pages
3. open the app it won't get the OTA

Here's the app : https://expo.dev/artifacts/eas/dsxKfHBshiSTn1rrw73Hh2.tar.gz built for simulator.
Here's the online preview : https://appetize.io/app/dg48fnkyecr48pmh54fh811pz0?device=iphone8&osVersion=13.7&scale=75&proxy=intercept
___

I have also tried with local servers at first for my real app, but couldn't get it work there also.

**Comment by Stevemoretz** [comment]
Searching git in console gave me this : 
default	04:08:29.236301+0430	useractivityd	SIMULATOR: Updating existing item, D5311F3B-D699-46E2-AC56-604FFBC7FFD9 4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163/https://github.com/expo/expo-cli/issues/2129


I was using my app process as filter in the last log.

**Comment by Stevemoretz** [comment]
I found this in the logs, that I shared in the gist.
`EXUpdates: Could not emit error event. Did you set the bridge property on the controller singleton?`

**Comment by Stevemoretz** [comment]
I built as production profile for android too:

```
{
  "cli": {
    "version": ">= 0.48.2"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "channel": "preview",
      "ios": {
        "distribution": "internal",
        "simulator": true
      },
      "android": {
        "distribution": "internal",
        "buildType": "apk"
      }
    },
    "production": {
      "android": {
        "buildType": "apk"
      }
    }
  },
  "submit": {
    "production": {}
  }
}
```

Here are the android logs :

```
04-02 13:08:26.756   971 11282 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.stevemoretz.otaapp/.MainActivity bnds=[645,370][856,656]} from uid 10058 on display 0
04-02 13:08:26.759   971 11282 I ActivityManager: ActivityRecord info: ActivityInfo{531e24f com.stevemoretz.otaapp.MainActivity}, euid: 0
04-02 13:08:26.784   971  2133 I ActivityManager: Start proc 29547:com.stevemoretz.otaapp/u0a159 for activity com.stevemoretz.otaapp/.MainActivity
04-02 13:08:26.802  1767  1848 D ScenarioService: new above launcher pkgs: [com.stevemoretz.otaapp]
04-02 13:08:26.804   588   629 D bdatd   : [BiDispatcher.cpp] dispatchInfo# level: 6, tag: BDAT_TAG_SCENE_CHANGED, time: 04-02 13:08:26.797, data: name=com.stevemoretz.otaapp
04-02 13:08:26.877 29547 29547 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.stevemoretz.otaapp-1/lib/arm64 flags = 0]
04-02 13:08:26.878 29547 29547 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.stevemoretz.otaapp/lib-main flags = 1]
04-02 13:08:26.878 29547 29547 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.stevemoretz.otaapp-1/lib/arm64 flags = 0]
04-02 13:08:26.878 29547 29547 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.stevemoretz.otaapp/lib-main flags = 1]
04-02 13:08:26.878 29547 29547 V fb-UnpackingSoSource: locked dso store /data/user/0/com.stevemoretz.otaapp/lib-main
04-02 13:08:26.923 29547 29547 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.stevemoretz.otaapp/lib-main (from syncer thread)
04-02 13:08:26.923 29547 29547 V fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.stevemoretz.otaapp/lib-main (syncer thread started)
04-02 13:08:27.026 29547 29547 D SoLoader: libjscexecutor.so not found on /data/data/com.stevemoretz.otaapp/lib-main
04-02 13:08:27.026 29547 29547 D SoLoader: libjscexecutor.so found on /data/app/com.stevemoretz.otaapp-1/lib/arm64
04-02 13:08:27.099 29547 29574 D SoLoader: libreactnativejni.so not found on /data/data/com.stevemoretz.otaapp/lib-main
04-02 13:08:27.099 29547 29574 D SoLoader: libreactnativejni.so found on /data/app/com.stevemoretz.otaapp-1/lib/arm64
04-02 13:08:27.099   971  2129 D HwNetworkManagementService: appName = com.stevemoretz.otaapp  is not in the mAdViewMap! reply none
04-02 13:08:27.099   971  2129 D HwNetworkManagementService: appName = com.stevemoretz.otaapp  is not in the mAdIdMap! reply none
04-02 13:08:27.100 29547 29574 D SoLoader: libfbjni.so not found on /data/data/com.stevemoretz.otaapp/lib-main
04-02 13:08:27.101 29547 29574 D SoLoader: libfbjni.so found on /data/app/com.stevemoretz.otaapp-1/lib/arm64
04-02 13:08:27.120 29547 29547 I art     :   at void com.stevemoretz.otaapp.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:19)
04-02 13:08:27.120 29547 29547 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.stevemoretz.otaapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.stevemoretz.otaapp-1/lib/arm64, /data/app/com.stevemoretz.otaapp-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
04-02 13:08:27.121 29547 29547 I art     :   at void com.stevemoretz.otaapp.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:19)
04-02 13:08:27.135 29547 29547 D HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f0d0007, context : com.stevemoretz.otaapp.MainActivity@23be65b, Nhwext : 0, get Blur : disable
04-02 13:08:27.135 29547 29547 D HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f0d0007, context : com.stevemoretz.otaapp.MainActivity@23be65b, Nhwext : 0, get Blur : disable
04-02 13:08:27.139 29547 29547 D ActivityThread: add activity client record, r= ActivityRecord{cef5e9c token=android.os.BinderProxy@6ed355 {com.stevemoretz.otaapp/com.stevemoretz.otaapp.MainActivity}} token= android.os.BinderProxy@6ed355
04-02 13:08:27.181   971  2129 V HwPhoneWindowManager: updateSystemUiColorLw window=Window{516d7d1 u0 com.stevemoretz.otaapp/com.stevemoretz.otaapp.MainActivity},EmuiStyle=0,StatusBarColor=0xffffffff,NavigationBarColor=0xff000000
04-02 13:08:27.322 29547 29547 D SoLoader: libyoga.so not found on /data/data/com.stevemoretz.otaapp/lib-main
04-02 13:08:27.322 29547 29547 D SoLoader: libyoga.so found on /data/app/com.stevemoretz.otaapp-1/lib/arm64
04-02 13:08:27.415   971   993 I ActivityManager: Displayed com.stevemoretz.otaapp/.MainActivity: +639ms
04-02 13:08:27.512   971  2128 V HwPhoneWindowManager: updateSystemUiColorLw window=Window{516d7d1 u0 com.stevemoretz.otaapp/com.stevemoretz.otaapp.MainActivity},EmuiStyle=0,StatusBarColor=0x0,NavigationBarColor=0xff000000
04-02 13:08:27.615   971   993 I WindowManager: Destroying surface Surface(name=Starting com.stevemoretz.otaapp) called by com.android.server.wm.WindowStateAnimator.destroySurface:2056 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:907 com.android.server.wm.WindowState.destroyOrSaveSurface:2172 com.android.server.wm.AppWindowToken.destroySurfaces:366 com.android.server.wm.WindowStateAnimator.finishExit:587 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:513 com.android.server.wm.WindowAnimator.updateWindowsLocked:311 com.android.server.wm.WindowAnimator.animateLocked:738 
04-02 13:08:28.211 29547 29578 D SoLoader: libreactnativeblob.so not found on /data/data/com.stevemoretz.otaapp/lib-main
04-02 13:08:28.211 29547 29578 D SoLoader: libreactnativeblob.so found on /data/app/com.stevemoretz.otaapp-1/lib/arm64
```

Also I changed the code a bit to make the updates manual to get more information.

https://github.com/Stevemoretz/expo-ota-app/tree/manual-update

Now Because of my changed App.js:

```jsx
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import {useEffect, useState} from "react";
import * as Updates from "expo-updates";

export default function App() {
  const log = async (object) => {
    console.log(object);
    await fetch("https://eo7smyw28ydqjai.m.pipedream.net",{
      method : "POST",
      body : JSON.stringify(object)
    })
    setLogText(JSON.stringify(object))
  }

  const [logText, setLogText] = useState("");
  useEffect(()=>{
    (async () => {
      try {
        const update = await Updates.checkForUpdateAsync();
        await log(update);
        if (update.isAvailable) {
          await Updates.fetchUpdateAsync();
          await log({
            msg : "updated!! "
          });
          await Updates.reloadAsync();
        }
      } catch (e) {
        await log({
          exception : "exception : " +  e.toString()
        });
      } finally {
        await log(Updates.manifest);
      }
    })()
  },[]);
  return (
    <View style={styles.container}>
      <Text>This is the OTA!</Text>
      <Text>{logText}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

I get this exception : Failed to parse manifest data

**Comment by Stevemoretz** [comment]
Here we can see a similar problem : 
https://stackoverflow.com/questions/70983032/expo-react-native-self-hosted-ota-not-working

**Comment by Stevemoretz** [comment]
Adding 
`"runtimeVersion": "1.0.8"` to app.json changed the exception to :

`The data couldn’t be read because it isn’t in the correct format.`

**Comment by Stevemoretz** [comment]
Sounds like it needs this : https://github.com/expo/custom-expo-updates-server
in order to work :)

Still working on it but sounds weird that it wasn't mentioned in the docs that, that method wasn't even supported by EAS builds.

**Comment by Stevemoretz** [comment]
I could manage to get it work without assets, but it crashes with any assets included.

my output example was :

```
{
    "id": "bf2abe58-3e66-b988-36a0-dbcd3aa6d962",
    "createdAt": "2022-04-02T12:46:24.286Z",
    "runtimeVersion": "1.0.9",
    "assets": [
        {
            "hash": "24272cdaeff82cc5facdaccd982a6f05b60c4504704bbf94c19a6388659880bb",
            "key": "4f1cb2cac2370cd5050681232e8575a8.png",
            "contentType": "image/png",
            "url": "http://localhost:5000/assets?asset=updates/1.0.9/assets/4f1cb2cac2370cd5050681232e8575a8&runtimeVersion=1.0.9&platform=ios"
        }
    ],
    "launchAsset": {
        "hash": "6055338d31f003945e1d46d4042c4525cf60ba042f8b2435dba154b2a69b3272",
        "key": "08d622e8bcd3eee01dc32341f3e25515.bundle",
        "contentType": "application/javascript",
        "url": "http://localhost:5000/assets?asset=updates/1.0.9/bundles/ios-08d622e8bcd3eee01dc32341f3e25515.js&runtimeVersion=1.0.9&platform=ios"
    }
}
```

Both of the links work, if used manually (with postman for example) but app crashes without even getting the that part.

```
my local sever requests after opening the app:

```
GET / 200 714 {} {"host":"localhost:5000","accept":"multipart/mixed,application/expo+json,application/json","expo-channel-name":"preview","expo-runtime-version":"1.0.9","accept-language":"en-us","expo-updates-environment":"BARE","accept-encoding":"gzip, deflate","expo-accept-signature":"false","expo-api-version":"1","user-agent":"otaapp/1 CFNetwork/1220.1 Darwin/19.6.0","expo-json-error":"true","connection":"keep-alive","expo-platform":"ios","expo-release-channel":"default"}

GET / 304 - {} {"host":"localhost:5000","expo-release-channel":"default","accept":"multipart/mixed,application/expo+json,application/json","expo-channel-name":"preview","expo-runtime-version":"1.0.9","accept-language":"en-us","expo-updates-environment":"BARE","accept-encoding":"gzip, deflate","expo-accept-signature":"false","expo-api-version":"1","if-none-match":"W/\"2ca-0pin1zsMeNWCrTQ2vHXxWn6RVt4\"","expo-json-error":"true","user-agent":"otaapp/1 CFNetwork/1220.1 Darwin/19.6.0","expo-platform":"ios","connection":"keep-alive"}

GET /assets?asset=updates/1.0.9/bundles/ios-0848a37c5690604401dfbb0e911bc993.js&runtimeVersion=1.0.9&platform=ios 200 - {} {"host":"localhost:5000","expo-api-version":"1","expo-channel-name":"preview","expo-platform":"ios","expo-updates-environment":"BARE","accept":"*/*","accept-language":"en-us","user-agent":"otaapp/1 CFNetwork/1220.1 Darwin/19.6.0","accept-encoding":"gzip, deflate","connection":"keep-alive"}
```

crash log :

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[4]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2049e77f _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff2049c9a7 -[__NSPlaceholderArray initWithCapacity:].cold.1 + 0
	4   CoreFoundation                      0x00007fff20323ee6 -[__NSPlaceholderArray initWithObjects:count:] + 154
	5   CoreFoundation                      0x00007fff2040d325 +[NSArray arrayWithObjects:count:] + 40
	6   otaapp                              0x0000000103504000 -[EXUpdatesDatabase addNewAssets:toUpdateWithId:error:] + 1102
	7   otaapp                              0x00000001034fe1b6 __29-[EXUpdatesAppLoader _<…>
```

**Comment by raphaelmsr** [comment]
Hey Expo team!

> Sounds like it needs this : https://github.com/expo/custom-expo-updates-server in order to work :)
> 
> Still working on it but sounds weird that it wasn't mentioned in the docs that, that method wasn't even supported by EAS builds.

Same issue here, this is very weird. I do not understand the mix between EAS Updates and Expo Updates old-mechanism.
Even in the https://docs.expo.dev/distribution/hosting-your-app/ page it is written that you can use both `eas build` and `expo export --public-url`.

What is the use for a custom expo updates server then ? A bit of clarification would be highly appreciated ! Thanks in advance

**Comment by vasilevich** [comment]
face the same issue, please clarify, would like to self host the js files.

Thanks!

**Comment by jonsamp** [comment]
Hi everyone, I wanted to chime in to clear up some confusion and also help guide how you can create your own updates server.

Every expo app that has the expo-updates library installed makes a request to fetch any new update manifests. If a new update manifest is available, then the expo-updates library (running on a user's device) will fetch any missing assets specified in the manifest.

The expo-updates library can requests update manifests from any update server. Previously (pre 2022) we were developing Expo's Classic Updates service, and now we are developing EAS Update. Both services responded to requests from expo-updates with manifests and assets. However, you can also create your own update server (like this issue is asking about).

The most current doc on creating your own update server is: [https://docs.expo.dev/eas-update/custom-updates-server/](https://docs.expo.dev/eas-update/custom-updates-server/), which provides an example server: [https://github.com/expo/custom-expo-updates-server](https://github.com/expo/custom-expo-updates-server).

When started updating the expo-updates library to have more functionality (as we developed EAS Update), we changed the shape of the update manifest so that it complies with this protocol: [https://docs.expo.dev/technical-specs/expo-updates-0/](https://docs.expo.dev/technical-specs/expo-updates-0/)

That is some background, now let me address some individuals in this thread:

@Stevemoretz I'm glad you found the newer reference server. Sorry that it was not linked in the doc you found originally. We are still in the process of rolling out EAS Update and this non-EAS Update doc got bundled in with the EAS Update docs. I can put up a PR to fix that. Also, it looks like I already addressed your asset loading issue here: https://github.com/expo/custom-expo-updates-server/issues/3#issue-1190630070

@raphaelmsr I hope the explanation above helps clarify the differences between expo-updates (open source library), Classic Updates (legacy service by Expo), and EAS Update (current service by Expo). Please let me know if you have more questions about what things are.

@vasilevich Give the example server a shot. It's README.md should provide instructions on how to get it set up: https://github.com/expo/custom-expo-updates-server. Let me know or create an issue on it if it is not working for you. Also, the field you need is `expo.updates.url` not `expo.app.updates.url` (remove `app`) in your app config.

**Comment by Stevemoretz** [comment]
> Hi everyone, I wanted to chime in to clear up some confusion and also help guide how you can create your own updates server.
> 
> Every Expo app that has the expo-updates library installed makes a request to fetch any new update manifests. If a new update manifest is available, then the expo-updates library (running on a user's device) will fetch any missing assets specified in the manifest.
> 
> The expo-updates library can request update manifests from any update server. Previously (pre-2022) we were developing Expo's Classic Updates service, and now we are developing EAS Update. Both services responded to requests from expo-updates with manifests and assets. However, you can also create your own update server (like this issue is asking about).
> 
> The most current doc on creating your own update server is https://docs.expo.dev/eas-update/custom-updates-server/, which provides an example server: https://github.com/expo/custom-expo-updates-server.
> 
> When we started updating the expo-updates library to have more functionality (as we developed EAS Update), we changed the shape of the update manifest so that it complies with this protocol: https://docs.expo.dev/technical-specs/expo-updates-0/
> 
> That is some background, now let me address some individuals in this thread:
> 
> @Stevemoretz I'm glad you found the newer reference server. Sorry that it was not linked in the doc you found originally. We are still in the process of rolling out EAS Update and this non-EAS Update doc got bundled in with the EAS Update docs. I can put up a PR to fix that. Also, it looks like I already addressed your asset loading issue here: [expo/custom-expo-updates-server#3 (comment)](https://github.com/expo/custom-expo-updates-server/issues/3#issue-1190630070)
> 
> @raphaelmsr I hope the explanation above helps clarify the differences between expo-updates (open source library), Classic Updates (legacy service by Expo), and EAS Update (current service by Expo). Please let me know if you have more questions about what things are.
> 
> @vasilevich Give the example server a shot. Its README.md should provide instructions on how to get it set up: https://github.com/expo/custom-expo-updates-server. Let me know or create an issue on it if it is not working for you. Also, the field you need is `expo.updates.url` not `expo.app.updates.url` (remove `app`) in your app config.

Thank you for clarification, yes you have fixed the bug on assets, the current issue with the current implementation is that it needs a server to compute the manifest and asset urls, this seems basically static host support sounds to be dropped eg : github pages hosting, right now the best that could be done for putting the download load from your server to github (I didn't have the time to try this) is that you host your assets statically but use the server to provide the link to them, this however I guess needs you to have your bundle both on github and on your server too (for calculations), long story short even thought this server gives you more flexibility the current export implementation doesn't consider hosting statically as an option, which could create a lot of issues talking bandwidth wise, for updating many users at the same time with a VPS or something.

**Comment by vasilevich** [comment]
@jonsamp Thank you for the help, I indeed managed to host updates with your server solution successfully,
I launched the nextjs server, and routed it through a NGINX reverse proxy (as a path to the web version of the app)
 and it works well. as expected,  just need to change the version number in  the manifest.json for it to catch on.

I followed the docs and set it up on my own VPS and all seems well,
The main issues I face from your github doc example, tho it might be a simple eslint/tslint issue is that,
when I put these values https://github.com/expo/custom-expo-updates-server/blob/main/expo-updates-client/app.json#L18-L22
in my app.json, expo tools claim to not recognize these values and have potential to cause issues durning compilation.
hope the docs can clarify if these values are even needed

Thanks again!

**Comment by jonsamp** [comment]
@vasilevich Here is the schema we use expo tools is [this schema](https://exp.host/--/api/v2/project/configuration/schema/45.0.0).

It is possible that you're experiencing this issue: https://github.com/expo/vscode-expo/issues/87

**Comment by vasilevich** [comment]
@jonsamp Hi, thanks again for your response,   the Ide I use is intelij ultimate,
and the issue also happens when I compile through the cli(has nothing to do with the IDE)
so I guess I need to apply the schema.

do you have an example how can I apply the schema you linked? 

Thanks again!

**Comment by Ddv0623** [comment]
Hi @jonsamp, We plan to build a React Native app that uses expo-updates for OTA updates.
In our use case, we want to set the updates.url programmatically in code. Is Expo support for it right now?
Can you show me how to do that?
If Expo does not support it I am willing to do some code change to support it. In that case can you give a hint where should I start. I do try to take a look on Expo source code. but it is a bit too much and I just want to use Expo-Updates only.

**Comment by Ddv0623** [comment]
> Hi @jonsamp, We plan to build a React Native app that uses expo-updates for OTA updates. In our use case, we want to set the updates.url programmatically in code. Is Expo support for it right now? Can you show me how to do that? If Expo does not support it I am willing to do some code change to support it. In that case can you give a hint where should I start. I do try to take a look on Expo source code. but it is a bit too much and I just want to use Expo-Updates only.

After post this. I find out about app.config.js of Expo but there are limitations about not supporting Promise. So I still need some way to set the URL to the server where hosted javascript bundle.

**Comment by jonsamp** [comment]
Hello again!

@vasilevich I don't have a great answer at the moment. The code for the VSCode extension we make is [here](https://github.com/expo/vscode-expo). There might be some code in there that helps, but I'm not totally sure if that will be the solution to your problem. Fingers crossed it will help in some way.

@Ddv0623 Glad you found **app.config.js**. We support setting different values based on an environment variable. If a Promise is necessary, I wonder if you could create a script that makes the call, inserts the correct value (either into app.config.js itself or sets an environment variable), then sends the project to be built with the correct value. Maybe I am missing the mark on your question? If there's a specific use case for using a Promise, I'd love to hear more.

Also, thanks for following up, and sorry for the slow responses. I hope development has gone well in the meantime.
