### ISSUE TITLE
Text component adjustsFontSizeToFit property does not work for Web app

### ISSUE THREAD

**Issue by RocketRonz** [expo/expo#16882]
### Summary

Setting the adjustsFontSizeToFit property to true should resize the text so it fits within its containing View.

This works on both Android and iOS when numberOfLines and fontSize are set, but the same code does not work when running in the browser.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
System:
OS: Windows 10 10.0.19044
Binaries:
Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 4.1.0.0 AI-201.8743.12.41.7042882
npmPackages:
expo: ^44.0.0 => 44.0.5
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.3 => 0.64.3
react-native-web: 0.17.1 => 0.17.1
Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@rocketronz/expo-text-bug

**Comment by brentvatne** [comment]
this field is not supported for web, no such property exists for the web platform.

**Comment by RocketRonz** [comment]
Ok, thanks. The issue you linked to was closed a couple of years ago so doesn't look like this functionality will be added for the web platform any time soon. I'll look into writing my own component that works out the optimal font size using the layout.
