### ISSUE TITLE
bundledAssets add option to not hash the filename 

### ISSUE THREAD

**Issue by ahmetabdi** [expo/expo#1689]
Example

`"bundledAssets":["asset_d87ae6bbffc317928dc1f6d3747be460.jpg"]`

test.jpg is being renamed to `asset_d87ae6bbffc317928dc1f6d3747be460`

**Comment by anp** [comment]
Hi! Could you provide some more detail about what problem this will solve for you?

**Comment by ahmetabdi** [comment]
@anp  react-native-maps does a string replacement on the location of a file

E.g. `some_path/{z}/{x}/{y}.png` gets replaced to `some_path/1/1/1.png`

It's current not possible to do this when the bundled assets are being renamed and seem to be missing its folder structure

**Comment by nielsrolf** [comment]
Hello, any updates? Is this still impossible?
