### ISSUE TITLE
Alert text buttons on Android blue in Expo Go but black in EAS builds

### ISSUE THREAD

**Issue by jeffcad** [expo/expo#16898]
### Summary

The color of the text buttons (eg. 'OK') on Android Alert.alert modals is blue when using Expo Go with 'expo start' or 'expo publish', but black when built with EAS for internal distribution or Play Store. They should be blue, to hint that they are pressable text.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.0

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed

### Reproducible demo

App.js
```
import { StyleSheet, View, Alert, Button } from 'react-native'

export default function App() {
  const alert = () => {Alert.alert('Android - Blue or Black?', 'OK is blue on Expo Go, black built with EAS')}
  return (
    <View style={styles.container}>
      <Button title='Show Alert' onPress={alert} />
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  }
})
```
eas.json
```
{
  "cli": {
    "version": ">= 0.48.2"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```
package.json dependencies
```
"dependencies": {
    "expo": "~44.0.0",
    "react": "17.0.1",
    "react-native": "0.64.3",
    "expo-updates": "~0.11.6"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
```

**Comment by newfylox** [comment]
Don't know if it's related but my alerts and modals had bad background and text colors on Android. I noticed that the issue was occuring when my phone had `settings -> display -> dark theme` turned on.

But the problem is that if we don't set property `userInterfaceStyle` in `app.json`, it's supposed to have `light` as default value (which was my case). I had to force set it to `userInterfaceStyle: "light"` to make it work with EAS Build. It was working great on Expo Go before that.

**Comment by jeffcad** [comment]
Comment to keep issue open

**Comment by newfylox** [comment]
Haven't test on SDK 46 yet, maybe it could work?

**Comment by jeffcad** [comment]
> Haven't test on SDK 46 yet, maybe it could work?

Unfortunately, it seems to not be fixed in SDK 46.

**Comment by jeffcad** [comment]
This is still not fixed in SDK 47. It's strange, because this seems like something that should be very quick to fix for somebody who knows what they're doing.
