### ISSUE TITLE
native stack statusbar management is not compatible with expo-dev-client ?

### ISSUE THREAD

**Issue by a-eid** [expo/expo#16900]
### Summary

I always get `RCTStatusBar requires that the UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO` 

native-stack requires the `UIViewControllerBasedStatusBarAppearance` to be set to `true` in order to use it's `StatusBar` features. 

PS: I change it in `app.json` and build the app with EAS or `expo run:ios`

I don't use `StatusBar` from `react-native` nor `expo-status-bar` 

we manage it via the [native stack](https://github.com/software-mansion/react-native-screens/tree/main/native-stack#statusbarstyle)

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.3.1 - ~/n/bin/npm
      Watchman: 2022.02.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/ahmedelshentenawy/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
        Android NDK: 20.1.5948944
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 1 Bumblebee 2021.1.1 Patch 1
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: managed
    ```

### Reproducible demo

WIP, will post it soon.

**Comment by tcdavis** [comment]
Hi @a-eid, this appears to be the same as https://github.com/expo/expo/issues/15801. Please let me know if that's not correct

**Comment by a-eid** [comment]
Hey @tcdavis, that seem to be the same issue indeed.
