### ISSUE TITLE
WebBrowser.openAuthSessionSync() doesn't work on Safari and Firefox due to pop-up blocking

### ISSUE THREAD

**Issue by jrc** [expo/expo#16902]
### Summary

Reopening https://github.com/expo/expo/issues/10459, which went stale but it's still a problem.

In short: WebBrowser.openAuthSessionSync() doesn't work on Safari and Firefox due to pop-up blocking.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

44

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.4.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.2 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.1.1
    Expo Workflow: bare

```

### Reproducible demo

```
import * as WebBrowser from 'expo-web-browser';
```

```
      <Button
        onPress={async () => {
          await WebBrowser.openAuthSessionAsync('https://www.example.com', 'https://www.google.com');
        }}
        title={'Hello World'}
      />
```

**Comment by jrc** [comment]
My current workaround looks like this. I would love to hear better ideas.

        try {
            if (Platform.OS === 'web') {
                /*
                    Due to https://github.com/expo/expo/issues/10459
                    (reopened as https://github.com/expo/expo/issues/16902)
                    WebBrowser.openAuthSessionAsync() results in the exception 
                    "Error: Popup window was blocked by the browser or failed to
                    open. This can happen in mobile browsers when the window.open()
                    method was invoked too long after a user input was fired."

                    When this happens, retrying with WebBrowser.openBrowserAsync()
                    has no effect, and cleaning up via WebBrowser.dismissAuthSession()
                    doesn't help either.
                    
                    Workaround by checking the user agent for Safari for now.
                */
                const userAgent = window.navigator.userAgent;
                if (userAgent.indexOf('AppleWebKit') !== -1 && userAgent.indexOf('Chrome') === -1) {
                    console.warn('Safari detected. Using workaround for Auth0 logout.');
                    await WebBrowser.openBrowserAsync(logoutUrl); // open new tab
                    window.close(); // close new tab
                }
                else {
                    await WebBrowser.openAuthSessionAsync(logoutUrl, redirectUrl);
                }
            }
        }
        catch (err) {
            console.error(err);
        }

**Comment by sreuter** [comment]
I've posted an update on https://github.com/expo/expo/issues/10459 which hopefully should provide clarity and a solution to this issue.

**Comment by jrc** [comment]
Closing as dupe of https://github.com/expo/expo/issues/10459
