### ISSUE TITLE
Detached Android Standalone app doesn't include js bundle

### ISSUE THREAD

**Issue by proguru58** [expo/expo#1690]
Hi I have built a signed apk and installed on my Android from detached project.

I am getting an error "could not load"

It seems like it is trying to load the bundle from Internet.

How can I embed the js bundle inside apk so it can run without internet connection?

Thanks

**Comment by kozhin** [comment]
+1
In Russia expo.io is banned and we need to deliver release version bundle without connection to Expo's servers.

**Comment by esamelson** [comment]
Hi - this is coming in SDK 27 which should be shipping very soon, so hold tight!

**Comment by proguru58** [comment]
@kozhin I have used their one-time update guide and it worked here!

**Comment by kozhin** [comment]
@proguru58 great! Thanks!

**Comment by terribleben** [comment]
Closing because we resolved this in SDK 27. 🎉 Let us know if you're still running into any trouble.
