### ISSUE TITLE
`expo run:android` Execution failed for task ':expo:compileDebugKotlin'.

### ISSUE THREAD

**Issue by Livijn** [expo/expo#16907]
### Summary

I am trying to run `expo run:android` but it is throwing an error:

> Task :expo:compileDebugKotlin FAILED
> e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
> e: /Users/fredrik/.gradle/caches/transforms-3/237076f67658440e344a90648c21f016/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.1.
> etc...

It's basically the same as #15989 but I am using `expo-file-system@13.1.4`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/Documents/code/dogs-app/node_modules/.bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo

No demo should be required for this.

**Comment by Livijn** [comment]
If I manually add this to `build.gradle` it works.

```
buildscript {
    ext {
        kotlinVersion = "1.6.0"
   }
}
```

**Comment by Livijn** [comment]
Created a plugin for the kotlinVersion: https://gist.github.com/Livijn/8be31941f09368e968718637fdcdbae3

**Comment by karlhorky** [comment]
This is `buildscript.ext.kotlinVersion` update worked, thanks!

I changed it using `sed` on the command line:

```bash
sed -i'' -e 's/kotlinVersion = "1.4.21"/kotlinVersion = "1.6.0"/g' android/build.gradle
```

So that the build can be automated: [upleveled/hotline-bling-codealong@`2407af0` (#47)](https://github.com/upleveled/hotline-bling-codealong/pull/47/commits/2407af0de38d9db21956b3ff77a0378e77c93c74)

**Comment by jonelvinnaorbe** [comment]
Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)

**Comment by Ikalli** [comment]
> Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)

I was stucked in the same issue and this worked for me

**Comment by jonelvinnaorbe** [comment]
> > Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)
> 
> I was stucked in the same issue and this worked for me

I'm glad it worked on your end too, happy coding @Ikalli

**Comment by Tristan1075** [comment]
> Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)

You saved my day ! Thanks

**Comment by CCB-cerivera** [comment]
> Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)

you're the best I love

**Comment by doougui** [comment]
> Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)

You are a f god. Thanks!

**Comment by oelerpearler** [comment]
> Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)

Saved my day as well, thanks a lot! I understand the function, but can you explain why allprojects.configurations.all.resolutionStrategy.force is even required at all? What is this exactly doing for the build?

**Comment by nadybee** [comment]
> Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)
🙏🏼 thank you!

**Comment by LucasRobert123** [comment]
Bom dia, eu estou usando a sdk 46 do expo, estava dando esse erro, mas ai atualizei a versão do react-native pra 0.69.7, como diz nesse link [https://github.com/facebook/react-native/issues/35210](url), mas ai o app fecha assim que termina o build.
Alguém sabe o que pode ser?

"dependencies": {
    "@hookform/resolvers": "^2.8.10",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-community/netinfo": "9.3.0",
    "@react-native-picker/picker": "2.4.2",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.7.0",
    "axios": "^0.27.2",
    "buffer": "^6.0.3",
    "cpf-cnpj-validator": "^1.0.3",
    "expo": "^46.0.0",
    "expo-av": "~12.0.4",
    "expo-camera": "~12.3.0",
    "expo-clipboard": "~3.1.0",
    "expo-file-system": "~14.1.0",
    "expo-font": "~10.2.0",
    "expo-image-manipulator": "~10.4.0",
    "expo-image-picker": "~13.3.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-local-authentication": "~12.3.0",
    "expo-sharing": "~10.3.0",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.7",
    "immer": "^9.0.14",
    "intl": "^1.2.5",
    "jwt-decode": "^3.1.2",
    "mime": "^3.0.0",
    "object-to-formdata": "^4.4.2",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-hook-form": "^7.31.1",
    "react-native": "0.69.7",
    "react-native-azure-speech-text": "LucasRobert123/react-native-azure-speech-text",
    "react-native-bcrypt": "^2.4.0",
    "react-native-dash": "^0.0.11",
    "react-native-document-picker": "^8.1.0",
    "react-native-dotenv": "^3.3.1",
    "react-native-exit-app": "^1.1.0",
    "react-native-file-viewer": "^2.1.5",
    "react-native-floating-label-input": "^1.3.14",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-get-random-values": "~1.8.0",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-reanimated": "~2.9.1",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "12.3.0",
    "react-native-ux-cam": "^5.4.2",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0",
    "react-use-websocket": "3.0.0",
    "realm": "^10.20.0-beta.5",
    "styled-components": "^5.3.5",
    "uuid": "^8.3.2",
    "vanilla-masker": "^1.2.0",
    "yup": "^0.32.11"
  },

**Comment by jjorian** [comment]
> Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)

thanks ,saved my time

**Comment by ansh** [comment]
You can also use `expo-build-properties` package and set the `kotlinVersion` in `app.json` which is a far simpler solution!

https://docs.expo.dev/versions/latest/sdk/build-properties/

**Comment by eloge257** [comment]
w

**Comment by shahriar-prepmock** [comment]
> Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)

Saved my day. Thanks a lot.

**Comment by jonelvinnaorbe** [comment]
> > Try this [fix](https://github.com/expo/expo/commit/02fb0a91694af1d32226f8bc26ec8a88648c3131)
> 
> Saved my day. Thanks a lot.

Glad to help you, but can you remove your thumbs down reaction on my comment? I think you just mis-clicked it.

**Comment by wassimbj** [comment]
For anyone still facing this issue, i fixed it with this 

run `npx expo-doctor` gave me a great hint which that `expo-permissions` must be removed for my current SDK version (51) and that it might cause issues when building the app; 
The npm package readme also clearly states that 
> This library has been replaced by module-specific permission methods.

So all i had to do is **remove expo-permissions from my package.json**
 
I then ran `npx expo install --fix` to upgrade some packages

ran `npx expo run:<platform>` and it worked just fine

**Comment by artypineda** [comment]
I had to also remove expo-permissions on EXPO SDK 51. The question is... will i need it later on!?
