### ISSUE TITLE
EAS Build: Failed to parse or read package.json

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo#16908]
### Summary

Eas build of custom development client triggers `Failed to parse or read package.json: package.json does not exist in /Users/expo/workingdir/build/app`.

Local running of `npm start` works fine (in old build of dev client).

Project structure:

```
/
  / app /
     / src / 
    package.json
    eas.json
    app.config.js
  / backend /

```

![image](https://user-images.githubusercontent.com/9071382/161576296-1baa31ca-cd93-4250-9663-6560b0dec082.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: bare
```

### Reproducible demo

N/A.

**Comment by wkozyra95** [comment]
Based on `expo-env-info` output you provided your project is bare not managed, so I'm assuming you ejected accidentally by running `expo prebuild` or `expo run:ios`, is that correct? Delete android and ios directories to get back to the managed project.

Is your package.json gitingored?
I see you have preinstall hook, can you show what you are doing there?
You can reproduce the state of your project on eas by running `eas build:inspect --stage archive`, it will make a copy of your project in the same way that eas cloud build would

**Comment by actuallymentor** [comment]
Perhaps I misunderstand the managed/ejected state.

Using the custom development client is ejected by default? I did run expo prebuild for that yes. 

I have no pre build scrips.

The output of `eas build:inspect` does show NO package.json. Is there a reason that this would be the case? I do for example have `*.json` in my `.gitignore` but do have the file committed...

**Comment by wkozyra95** [comment]
> I do for example have *.json in my .gitignore but do have the file committed...

This is the problem, when you add a rule to gitignore, then those changes are not applied retroactively if files are already committed, so in your case package.json is gitngored, but it is still in the repo because it was already there when the gitignore rule was added

**Comment by actuallymentor** [comment]
> then those changes are not applied retroactively if files are already committed, so in your case package.json is gitngored, but it is still in the repo because it was already there when the gitignore rule was added

@wkozyra95 no.

I created the `.gitignore` and then added the file with `git add -f`. This is a pretty standard practice and I'm not sure why `eas` would rely for the `.gitignore` for anything?

**Comment by actuallymentor** [comment]
Ok so update: it was the `.gitignore` file. Is there any documentation on this behaviour?

My default development flow is to `.gitignore` all files that are potentially compromising (`*.{json,key,plist}`) and to force-commit those that are ok.

It `makesnosensetome.gif` that `eas` would rely on the `.gitignore` to determine what files are uploaded to the build service. Especially since for example it is a common practice to:

1. `.gitignore` secrets like `google-services.json`
2. Write `${{ secrets.google }}` to `google-services.json` in the CI environment
3. Run a build command

**Comment by wkozyra95** [comment]
>  Is there any documentation on this behaviour?

https://github.com/expo/fyi/blob/main/eas-build-archive.md

If you want your builds to reflect exactly what is in your git state you can add `"cli": {"requireCommit": true}` in the root of your eas.json, but it will require you to commit your changes before building

> This is a pretty standard practice and I'm not sure why eas would rely for the .gitignore for anything?

because we don't want to upload node_modules/native build directories and secrets

> and to force-commit those that are ok.

if you want to protect yourself from accidentally committing stuff like this, the better alternative would be to use
```
*.json
!package.json
```

**Comment by actuallymentor** [comment]
Thanks for your responses. I appreciate it.

> If you want your builds to reflect exactly what is in your git state you can add "cli": {"requireCommit": true} in the root of your eas.json, but it will require you to commit your changes before building

Awesome. I can work with that.

> because we don't want to upload node_modules/native build directories and secrets

You need the secrets though. The `app.config.js` needs (in the case of Firebase) access to the application files. Technically they are not "secret" as they are embedded on build time, but I certainly don't want to commit them.

> if you want to protect yourself from accidentally committing stuff like this, the better alternative would be to use

If by "better" you mean "eas compatible" yes :)

**Comment by actuallymentor** [comment]
> If you want your builds to reflect exactly what is in your git state you can add "cli": {"requireCommit": true} in the root of your eas.json, but it will require you to commit your changes before building

Nevermind this will not work as it doesn't track files that are not committed.

Basically that puts me back where we started: The only way to make eas work with uncommitted and ignored files is to temporarily rewrite the `.gitignore` file...

Any suggestions?

**Comment by wkozyra95** [comment]
The recommended flow would be to either commit that in repo in plain text or encrypted (and pass git-crypt key via secrets mechanism)

> ignored files is to temporarily rewrite the .gitignore file...

you can use .easignore (it was mentioned in the link I sent in previous comment), it will replace .gitignore, but it does not work with `requireCommit: true` option

**Comment by actuallymentor** [comment]
Apologies, I skipped too vigorously and will attempt to use `.easignore`.

I think it makes sense to add this info to https://docs.expo.dev/build-reference/variables/, I can PR if you like?

**Comment by actuallymentor** [comment]
Ok, so I'll be closing this issue but will leave some breadcrubms for future googlers:

EAS uses `.gitignore` by default to determine what files to send to the build server. You can override this with `.easignore` as per [this file](https://github.com/expo/fyi/blob/main/eas-build-archive.md).

If any files are missing in eas, try `eas build:inspect --stage archive` to see if it is really missing or it is a code bug. If it is really missing check the above files.

@wkozyra95 I'm still happy to PR but await your greenlight.

**Comment by kbrandwijk** [comment]
The build process pages (https://docs.expo.dev/build-reference/ios-builds/ and the equivalent for Android) also mention in the 'local steps' checking the `requireCommit` setting. I think adding something there (at a minimum a link to that FYI page, or potentially something additional about 'checking for a .easignore file') makes the most sense to me.

Additionally, I think this could also be added to the [What if my project builds locally but not on EAS Build?](https://docs.expo.dev/build-reference/troubleshooting/#what-if-my-project-builds-locally-but) part of the troubleshooting guide.

**Comment by actuallymentor** [comment]
Is this something I can PR for or is it in your pipeline already?

**Comment by PawelGIX** [comment]
I have similar issue 
![image](https://github.com/expo/expo/assets/391153/fd7775c6-0304-46c2-9021-4a1ff4055052)

Any idea whats wrong? I have package.json

**Comment by Penedokaren** [comment]
Thank you, I was having this problem but now it's been solved
