### ISSUE TITLE
iOS initial notification prop missing when the app is launched with a notification

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1691]
Based on the [resurgence of activity in this thread](https://github.com/expo/expo/issues/785#issuecomment-383646184), it sounds like we had a regression here.

**Comment by feliperaul** [comment]
@terribleben This issue has a commit and milestone M27 attached. Is this a minor or major release (because SDK 27 is already released, right?)

**Comment by ide** [comment]
The milestone numbers and SDK versions are unrelated; they just happen to have some overlap right now.

The commit attached to this issue is currently slated to go out with a minor release.

**Comment by terribleben** [comment]
We released a fix for this today with Expo iOS runtime version 2.5.9, which is now available in the app store, simulator, and on the `exp build:ios` servers.

**Comment by feliperaul** [comment]
@terribleben Sorry if this is a dumb question, but all we need is re-publish to get this fixed, no need to update our SDK version? I'm confused because you didn't mension SDK v 25.0.x or something like this.

**Comment by ide** [comment]
You will need to rebuild -- Ben's comment is saying that the binary was updated and the fix was applied to existing SDK versions.

**Comment by feliperaul** [comment]
@ide Thanks, you guys rock.

**Comment by botmane** [comment]
Hello @ide @terribleben 

Could you update the documentation because it seems outdated (it requires using "props.ext.notification") whereas using  "Notifications.addListener( this._handleNotification );" is enough in any case.

https://docs.expo.io/versions/v28.0.0/guides/push-notifications#notification-handling-timing
![image](https://user-images.githubusercontent.com/6231769/43861476-3f5bf498-9b57-11e8-896e-b9fecabb71eb.png)

Thanks,

**Comment by superyarik** [comment]
now i see "props.exp.unreadNotifications" when application open from closed state(android).
and no data from notificaion in "props.exp.notification"

sdk 29
also i found it defenition in https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/notifications/PushNotificationHelper.java
