### ISSUE TITLE
EXKernelLinkingManager will always send nil URLs for universal links

### ISSUE THREAD

**Issue by dodgecm** [expo/expo#1692]
### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 7.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/guilded-1e357d22-0f9b-4218-ade3-b47e6fbdbd7c.tar.gz

Target: iOS ExpoKit

Relevant method in [EXKernalLinkingManager](https://github.com/expo/expo/blob/37c89e032b2a6f6935962bdc2b773f3f666a6d85/ios/Exponent/Kernel/Services/EXKernelLinkingManager.m#L25):

```
- (void)openUrl:(NSString *)urlString isUniversalLink:(BOOL)isUniversalLink
{
  NSURL *url = [NSURL URLWithString:urlString];
  ...
  EXKernelAppRegistry *appRegistry = [EXKernel sharedInstance].appRegistry;
  EXKernelAppRecord *destinationApp = nil;
  NSURL *urlToRoute = nil;

  if (isUniversalLink && [EXShellManager sharedInstance].isShell) {
    destinationApp = [EXKernel sharedInstance].appRegistry.standaloneAppRecord;
  } else {
    ...
    }
  }

  if (destinationApp) {
    [[EXKernel sharedInstance] sendUrl:urlToRoute.absoluteString toAppRecord:destinationApp];
  } else {
    ...
  }
}
```

Reproduction steps are:
1) Open a universal link in iOS safari that points to my app.

I've omitted the else blocks to show the problematic code path.  If it's a universal link and a destination app is found, `urlToRoute` is never set, which ends up causing a crash in [EXLinkingManager](https://github.com/expo/expo/blob/f5df1f535ffda5bc6c353f328625b2f2da8951f7/ios/Exponent/Versioned/Core/Internal/EXLinkingManager.m#L53).

**Comment by terribleben** [comment]
Thanks for the report and the codepath. Janic is working on updating our Branch dep right now so he'll probably hit/fix this in the meantime.

**Comment by terribleben** [comment]
Also, we maybe (?) already fixed this in SDK 27, such that the RHS is `url` instead of `nil` by default:

https://github.com/expo/expo/blob/edadd97729d2d3a8c21d7b29cd6a1465a912d97c/ios/Exponent/Kernel/Services/EXKernelLinkingManager.m#L34

**Comment by dodgecm** [comment]
Yes, that looks like it should fix the problem, I'm going to go ahead and close this.
