### ISSUE TITLE
Pedometer.watchStepCount not firing at all Samsung A30. (android 11)

### ISSUE THREAD

**Issue by remobaer** [expo/expo#16920]
### Summary

I've implemented the Pedometer.watchStepCount() as per the documentation (https://docs.expo.dev/versions/latest/sdk/pedometer/)

Though permission is requested and give, watchStepCount() doesn't fire at all (no error visible either)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.4 - /usr/local/opt/node@14/bin/node
      npm: 6.14.14 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 25, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.3 => 0.67.3 
    Expo Workflow: bare

### Reproducible demo

const subscription = Pedometer.watchStepCount((result) => {
      console.log('fire', result);
      setTrackedSteps(result.steps);
      dispatch(setSteps(result.steps));
});

permission Is requested through:
 PermissionsAndroid.request('android.permission.ACTIVITY_RECOGNITION' as Permission) which returns granted

**Comment by lqze** [comment]
Same as #16605 

If you urgently need this to work, I'm going to suggest ejecting :/.

**Comment by remobaer** [comment]
@lqze I'll get the testing device back later this week, will give it a shot then. thx

**Comment by remobaer** [comment]
> Same as #16605
> 
> Since you are in the bare workflow, please use `react-native-permissions` to request `ACTIVITY_RECOGNITION`. Let us know if this works.

before I forget. I actually get the user-request popup which the user can allow, and it returns granted. I just heard back from a friend that it worked on his Samsung. Very strange

**Comment by lqze** [comment]
@remobaer In bare or managed workflow?

And how is permission being requested?

**Comment by remobaer** [comment]
> @remobaer In bare or managed workflow?
> 
> And how is permission being requested?

Bare workflow, permission is requested via `PermissionsAndroid.request()`

**Comment by take** [comment]
looks like pedometer isn't working from SDK 33 - https://github.com/expo/expo/issues/9463
