### ISSUE TITLE
[expo-av] Rest of app is dimmed when a `<Video>` is showing without full screen brightness

### ISSUE THREAD

**Issue by Livijn** [expo/expo#16924]
### Summary

Rest of app is dimmed when a `<Video>` is showing without full screen brightness. It's hard to explain but in the picture below you can see a small video. That video has a LOT more brightness than the rest of the app. The whites are very different. 

This also happens in the default iOS Photos app, so I guess this is some iOS behaviour. But it does not happen in Instagram, which is built with RN. 

![IMG_3944](https://user-images.githubusercontent.com/349311/161756085-46a60b0b-49ed-4e39-9e3f-539fd79c3957.jpg)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

System:
  OS: macOS 12.1
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 16.14.0 - /usr/local/bin/node
  Yarn: 1.22.18 - ~/Documents/code/dogs-app/node_modules/.bin/yarn
  npm: 8.5.5 - /usr/local/bin/npm
Managers:
  CocoaPods: 1.11.2 - /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
IDEs:
  Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
  Xcode: 13.3/13E113 - /usr/bin/xcodebuild
npmPackages:
  expo: ^44.0.0 => 44.0.6
  react: 17.0.1 => 17.0.1
  react-dom: 17.0.1 => 17.0.1
  react-native: 0.64.3 => 0.64.3
  react-native-web: 0.17.1 => 0.17.1
npmGlobalPackages:
  eas-cli: 0.48.2
  expo-cli: 5.3.0
Expo Workflow: managed

### Reproducible demo

Should not be needed

**Comment by Livijn** [comment]
Actually seems to be the same on Instagram etc as well.

**Comment by dandre-hound** [comment]
We are thinking this has something to do with HDR videos on iPhone 12 and newer. @Livijn did you ever find a solution?

**Comment by Livijn** [comment]
@dandre-hound Yeah, it only applies to HDR videos. Haven't found a solution and I stopped looking since I found out that it's the same on Instagram. But please share if you find a solution.

**Comment by IliasseWahbi** [comment]
Same issue here on my iphone 13 pro.

**Comment by buildnewapp** [comment]
Today (2024-11-07 19:39:59) this issue still exists.
