### ISSUE TITLE
How to add Enterprise Mobility Management (EMM) in react native app

### ISSUE THREAD

**Issue by anil1712** [expo/expo#1694]
### Expected Behavior

Actually, I want to Set up managed configurations for the enterprise market apps to satisfy particular requirements set by a company's policies.

For example, an enterprise might require that approved apps allow the enterprise administrator to:
1. Whitelist or blacklist URLs for a web browser
2. Configure whether an app is allowed to sync content via cellular, or just by Wi-Fi
3. Configure the app's email settings

I found [this](https://developer.android.com/work/managed-configurations) for java android developer. 
How can I achieve the same as react native developer? 

(Write what you thought would happen.)

### Actual Behavior
No detailed documentation found to develop an app for the enterprise market.

**Comment by terribleben** [comment]
Hello there! This sounds like a good question for our [forums](http://forums.expo.io/). Since we try to keep this venue limited to bugs/issues with Expo's software, I'm going to close this. Please go ahead and open a discussion on the forum.
