### ISSUE TITLE
SAF createFileAsync() ignores the given parentUri and always uses the tree root

### ISSUE THREAD

**Issue by tehvgg** [expo/expo#16954]
### Summary

I'm using the SAF to create a directory inside the shared storage, specifically inside `Pictures`. This works, but when I try to create a file inside my subdirectory, the file is created as a sibling inside `Pictures` instead.

Looking through the source, it looks like `getNearestSAFFile()` always returns the tree root for directories via `fromTreeUri()`, only returning `fromSingleUri()` for files. This makes it impossible to write to my nested directory even though I have permissions.

I'm not sure if this is a bug or if it was written this way for a specific reason, but the docs say nothing about only being able to create files at the root (they say to give a `parentUri` for the folder to create the file in).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.4

### Environment

```
System:
    OS: Windows 10 10.0.19043
Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
npmPackages:
    @expo/metro-config: ^0.3.7 => 0.3.7
    @expo/webpack-config: ^0.16.2 => 0.16.13
    babel-preset-expo: 8.5.1 => 8.5.1
    expo: ^43.0.0 => 43.0.4
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-web: 0.17.1 => 0.17.1
Expo Workflow: managed
```

### Reproducible demo

```javascript
const picturesUri = StorageAccessFramework.getUriForDirectoryInRoot('Pictures');
const permissions = await StorageAccessFramework.requestDirectoryPermissionsAsync(picturesUri);
if (permissions.granted) {
    const dirUri = await StorageAccessFramework.makeDirectoryAsync(picturesUri, 'myDir');
    const fileUri = await StorageAccessFramework.createFileAsync(dirUri, 'myFile', 'text/plain');
}
```

`fileUri` should be:
`content://com.android.externalstorage.documents/tree/primary%3APictures/document/primary%3APictures%2FmyDir%2FmyFile.txt`
but it is: 
`content://com.android.externalstorage.documents/tree/primary%3APictures/document/primary%3APictures%2FmyFile.txt`
instead, ignoring my valid `parentUri`.

**Comment by tehvgg** [comment]
It also looks like if I call `deleteAsync()` with an SAF URI of a file, and that file doesn't exist at that location, `getNearestSAFFile()` returns the tree root again and `deleteAsync()` sees it exists and deletes the entire tree root...

**Comment by tevelmantsur** [comment]
same issue

**Comment by Oussamaab1998** [comment]
did you found any solution please

**Comment by Andreas-UI** [comment]
Any solution?
