### ISSUE TITLE
[expo-intent-launcher][android] Calendar Event intent - ClassCastException: Double cannot be cast to Long

### ISSUE THREAD

**Issue by frankcalise** [expo/expo#16958]
### Summary

When you supply the IntentLauncher with extra for the Event insert intent, the beginTime/endTime parameters are ignored because they are not considered a long. JavaScript always sending a double.

I'm not sure in all cases that we would want to just convert double to long, however is it possible to support this in some way for this particular intent? I would be happy to work on a PR if some direction on how it should be solved was provided.

From logcat:
```
04-07 11:12:04.941 27464 27464 W Bundle  : Key beginTime expected Long but value was a java.lang.Double.  The default value -1 was returned.
04-07 11:12:04.944 27464 27464 W Bundle  : Attempt to cast generated internal exception:
04-07 11:12:04.944 27464 27464 W Bundle  : java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo

Here is a reproducible demo:
https://snack.expo.dev/@frankcalise/intentlauncher-events

**Comment by jsoldi** [comment]
Was this ever fixed or is there a workaround?

**Comment by horaciorivero** [comment]
same problem

**Comment by brianomchugh** [comment]
I am hitting this same error in 2025
