### ISSUE TITLE
Android emulator Permissions.askAsync(Permissions.NOTIFICATIONS) returns granted

### ISSUE THREAD

**Issue by mradziwon** [expo/expo#1695]
### Environment

expo v26 & v27
Genymotion Android Emulator

### Steps to Reproduce

Everything works fine on expo 25, `Permissions.askAsync(Permissions.NOTIFICATIONS)` returns status undetermined on Android emulator and iOS simulator. Problem started after updating expo to v26 and v27. iOS works fine but not Android. On Android emulator notification status is `granted` and `Notifications.getExpoPushTokenAsync` never resolves.

### Expected Behavior

`Permissions.askAsync(Permissions.NOTIFICATIONS)` returns status different than `granted` and `Notifications.getExpoPushTokenAsync` is never executed.

### Actual Behavior

`Permissions.askAsync(Permissions.NOTIFICATIONS)` returns status `granted` and `Notifications.getExpoPushTokenAsync` is executed and never resolves.

**Comment by aalices** [comment]
Hello @mradziwon have you experienced this problem only after downloading the newest Expo Client that came out with SDK 27 or was this happening before?

**Comment by mradziwon** [comment]
Wow, It's strange. I just reverted back to expo v25 and `Permissions.askAsync(Permissions.NOTIFICATIONS)` returns status `granted` too. Is it possible that breaking change was in `Expo Client for Android`?

**Comment by colinyoung** [comment]
There seems to have been a somewhat undocumented change in the askAsync/getAsync where the Expo Client 27 is now asking you to grant permission _again_ for each individual Expo app (slug). It would be great to have this more documented/called out in this ticket

**Comment by sjchmiela** [comment]
You're right, @colinyoung, in SDK 27 we've introduced a change to how Permissions work, now they're granted on per-experience basis (see the commit by @aalices: https://github.com/expo/expo/commit/62dd63564aad0eb5e21b035b144c1332a72afb81).

**Comment by FreshBreadLux** [comment]
I've also run into the same behavior: Permissions.askAsync on the Android emulator returns granted and getExpoPushToken is executed and is never resolved. @mradziwon did you wind up finding a workaround for this on the Android emulator?

**Comment by mradziwon** [comment]
@FreshBreadLux I think you can just update expo or use guard clause where you check `if (Platform.OS === 'android' && __DEV__) return;`

**Comment by terribleben** [comment]
Hey all, can anyone confirm if they're seeing this on iOS as well? We have a [pending fix](https://github.com/expo/expo/issues/1960) for similar behavior on iOS, not sure if this thead is Android-only.

**Comment by ide** [comment]
May be related to https://github.com/expo/expo/issues/1881 (no repro though)

**Comment by mradziwon** [comment]
@terribleben everything works fine on my iOS simulator. I have only problem with Android emulators.

**Comment by FreshBreadLux** [comment]
I'm seeing the same behavior that @mradziwon is seeing: works fine on iOS simulator, but askAsync resolves to granted on Android emulators.

**Comment by yasso1am** [comment]
In my situation, askAsync resolves to undefined on Android. This is for `Permissions.CAMERA_ROLL`

**Comment by sjchmiela** [comment]
Hi all, a lot has changed in Expo codebase since April or July and my guess is that any new problems won't be related to whatever has caused the original issue of this thread. Please open new issues if they arise and I'll let myself close this issue. 🙂
