### ISSUE TITLE
Error: Task 'background-fetch' not found for app ID 'mainApplication'.

### ISSUE THREAD

**Issue by Tim4497** [expo/expo#16969]
### Summary

Error: Task 'background-fetch' not found for app ID 'mainApplication'.
When I add your Demo to my App

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/Documents/Arbeit/VMZ/sensorcollector/node_modules/.bin/node
      npm: 8.5.5 - ~/Documents/Arbeit/VMZ/sensorcollector/node_modules/.bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: ^17.0.2 => 17.0.2 
      react-native: 0.67.4 => 0.67.4 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo

```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import * as BackgroundFetch from 'expo-background-fetch';
import * as TaskManager from 'expo-task-manager';

const BACKGROUND_FETCH_TASK = 'background-fetch';

// 1. Define the task by providing a name and the function that should be executed
// Note: This needs to be called in the global scope (e.g outside of your React components)
TaskManager.defineTask(BACKGROUND_FETCH_TASK, async () => {
  const now = Date.now();

  console.log(`Got background fetch call at date: ${new Date(now).toISOString()}`);

  // Be sure to return the successful result type!
  return BackgroundFetch.BackgroundFetchResult.NewData;
});

// 2. Register the task at some point in your app by providing the same name, and some configuration options for how the background fetch should behave
// Note: This does NOT need to be in the global scope and CAN be used in your React components!
async function registerBackgroundFetchAsync() {
  return BackgroundFetch.registerTaskAsync(BACKGROUND_FETCH_TASK);
}

// 3. (Optional) Unregister tasks by specifying the task name
// This will cancel any future background fetch calls that match the given name
// Note: This does NOT need to be in the global scope and CAN be used in your React components!
async function unregisterBackgroundFetchAsync() {
  return BackgroundFetch.unregisterTaskAsync(BACKGROUND_FETCH_TASK);
}

export default function BackgroundFetchScreen() {
  const [isRegistered, setIsRegistered] = React.useState(false);

  React.useEffect(() => {
    checkStatusAsync();
  }, []);

  const checkStatusAsync = async () => {
    const status = await BackgroundFetch.getStatusAsync();
    const isRegistered = await TaskManager.isTaskRegisteredAsync(BACKGROUND_FETCH_TASK);
    setIsRegistered(isRegistered);
  };

  const toggleFetchTask = async () => {
    if (isRegistered) {
      await unregisterBackgroundFetchAsync();
    } else {
      await registerBackgroundFetchAsync();
    }

    checkStatusAsync();
  };
}
```

**Comment by Yandamuri** [comment]
Facing same error

**Comment by tkvclub01** [comment]
same error

**Comment by Yandamuri** [comment]
Can some one from expo team respond please?

**Comment by ahmad-crossplatform** [comment]
Same error

**Comment by tarieltairov** [comment]
same error

**Comment by EdizK** [comment]
Same error

**Comment by rockneverdies55** [comment]
having same error on android as well

**Comment by SoloOrchid** [comment]
solved this with `Notifications.removeNotificationSubscription`

**Comment by Yandamuri** [comment]
@SoloOrchid Can you please explain where to make these changes?

**Comment by mikekreeki** [comment]
Same issue

**Comment by melissa07** [comment]
Same issue on iOS simulator and device !

**Comment by LosGer** [comment]
I think this error is caused because a physical device is required for push notifications. I do not get it when I run on the expo app on a device.

**Comment by melissa07** [comment]
@LosGer In my case it's my background location fetch task that is causing the issue. So I don't think it's related to push notifications specifically. Also I've tried on my physical device and I still get the same error.

**Comment by Yandamuri** [comment]
as @LosGer explained, This is related to background location and I have also faced in real device.

**Comment by nikitaKulishEscola** [comment]
In my case the application listen for location changes in the background mode and I also get that Error.
To improve it - before use Location.stopLocationUpdatesAsync(taskName) you need to call Location.hasStartedLocationUpdatesAsync(taskName) to make sure that such a task exists.

I think all similar errors related to trying refer a task that does not yet exist or no longer exist.

**Comment by Tim4497** [comment]
> Hi there! It looks like your issue requires a minimal reproducible example, but it is invalid or absent.

**Comment by pfcodes** [comment]
What causes this?

**Comment by thoth-seshat** [comment]
having the same issue with "fetch" just using it to clear a clipboard

**Comment by thoth-seshat** [comment]
Ok, so for anyone else getting this error, this seems to happen when you try to call either register or unregister on a task that doesn't exist or hasn't been defined. 

For instance, I tried to to `await BackgroundFetch.unregisterTaskAsync(BACKGROUND_TASK.CLEAR_CLIPBOARD);` before I registered the task which resulted in the error.

**Comment by allexradu** [comment]
If anyone still has problems, I've fixed this problem by checking if the task is registered before trying to execute it.

` 
import * as TaskManager from 'expo-task-manager'
const isRegistered =
      await TaskManager.isTaskRegisteredAsync(UPDATE_LOCATION_TASK)

if (isRegistered) {
 await BackgroundFetch.registerTaskAsync(UPDATE_LOCATION_TASK, {
        minimumInterval: isAndroid ? 15 * 60 : undefined,
        stopOnTerminate: false, // android only,
        startOnBoot: true, // android only
      })
} else {
return <Spinner/>
}
`

**Comment by fsvapat** [comment]
Alternatively, I would suggest using `TaskManager. unregisterTaskAsync` instead of `BackgroundFetch.unregisterTaskAsync`, especially if your unregister call is in a `useEffect`.
