### ISSUE TITLE
[docs] Mention Camera Roll permissions changes to ImagePicker methods starting in SDK 27

### ISSUE THREAD

**Issue by n2ctech** [expo/expo#1696]
After following the instructions to upgrade from 26 to 27, ImagePicker.launchCameraAsync() and ImagePicker.launchImageLibraryAsync() don't seem to work anymore

**Comment by hskb10** [comment]
Ditto on the issue for iOS, working on Android.

**Comment by hskb10** [comment]
iOS solution: Permissions.askAsync(Pemission.CAMERA_ROLL)
Android: Works!

Have a great day!

**Comment by terribleben** [comment]
Hey all, you're right, camera roll permissions are now required to use these methods. This is a breaking change that we forgot to add to the [release notes](https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4). I've corrected the release notes to include this change.

**Comment by terribleben** [comment]
Actually it looks like our SDK 27 docs [do already mention that you need this permission](https://docs.expo.io/versions/v27.0.0/sdk/imagepicker). Since I've also added it to the release notes, I'm going to close this.

**Comment by AnawatLo** [comment]
I am having the same issue In expoXDE show
" Unhandled promise rejection: Error: Missing camera roll permission. "

**Comment by domialex** [comment]
We have to ask both **CAMERA** and **CAMERA_ROLL** on **iOS**, is there a way to do this without making 2 requests?

**Comment by jamesedmonston** [comment]
@domialex Same issue for me.

**Comment by martsie** [comment]
Caught us off guard too, luckily we caught it right before launch ... it's a strange change. I would expect the default to be to ask for the required permissions unless settings dictate otherwise rather than exceptioning but at least the exception message is verbose.
