### ISSUE TITLE
expo v27 Android app with websocket is crashing

### ISSUE THREAD

**Issue by mradziwon** [expo/expo#1698]
### Environment

expo v27
Genymotion Android Emulator

### Description

Android app with websockets is crashing with error - `WebSocketModule.close got 1 arguments, expected 3`. iOS works fine.
Bug probably related to RN version used in v27 - link to [issue](https://github.com/facebook/react-native/issues/18696) in RN repo.

**Comment by terribleben** [comment]
It looks like maybe they fixed this in React Native 0.55.3. Expo's SDK 27 is currently on 0.55.2. What happens if you temporarily install React Native 0.55.3 in your local JS and try running? Does it fix the issue? This info would help us know whether we can safely pull in the change.

**Comment by seiichi** [comment]
@terribleben 

I have the same issue.
After I replace SDK 27 with RN 0.55.3 temporarily, the issue seems to be fixed.

**Comment by ide** [comment]
@seiichi Thank you for verifying the fix. We have released https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz which has the commit from 0.55.3 that fixes this issue.

**Comment by bamne123** [comment]
Please update docs as well, it still shows old link.

**Comment by docaustyne** [comment]
We currently have this problem, both our production apps on IOS and Android get to remain in the welcome screen forever and wont move forward. We urgently need help with this issue

**Comment by mikechambers610** [comment]
I am getting this issue when clicking an image on a page where I have a subscription to appsync. IOS is working fine though.
