### ISSUE TITLE
Typescript: SQLStatementErrorCallback "Type 'void' is not assignable to type 'boolean"

### ISSUE THREAD

**Issue by realjjaveweb** [expo/expo#16984]
### Summary

In these files:
https://github.com/expo/expo/blob/main/packages/expo-sqlite/src/SQLite.types.ts
https://github.com/expo/expo/blob/main/packages/expo-sqlite/build/SQLite.types.d.ts

The `SQLStatementErrorCallback` is defined with a return type `boolean` - this is not documented in SDK docs neither in code comments the type also doesn't seem to be used in repo for typing elsewhere.

The success counterpart `SQLStatementCallback` and also the transaction variants are all typed as returning `void`. So I am assuming this is a typo and probably should also be typed as `void` or JSDocs comment added what boolean under what circumstances should be returned if it really is needed (**_not retuning in regular JS doesn't seem to affect it_**). It can be bypassed by specifying `: any` or `: boolean` and returning true/false however that creates unclear unnecessary code in both cases.
Therefore when you don't specify the type to mirror the statement callabck, it creates a typescript error "Type 'void' is not assignable to type 'boolean".

Thank you very much for your work. The package otherwise works just fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

44

### Environment

irelevant (typscript design flaw)

### Reproducible demo

// The error IS reproducible on TS Playground
```
import { openDatabase, SQLError, SQLResultSet, SQLTransaction } from "expo-sqlite";

openDatabase("somedbname.db").transaction((tx: SQLTransaction) => {
    tx.executeSql(
        "SELECT * FROM sometable",
        [],
        (_: SQLTransaction, { rows, insertId }: SQLResultSet) => {},
        (_: SQLTransaction, error: SQLError) => {}
        // ^^^^^ TS Error: "Type 'void' is not assignable to type 'boolean'"
    );
});

```

**Comment by cmoel** [comment]
I ran into this as well. The type for `SQLStatementErrorCallback` [says it returns a boolean](https://github.com/expo/expo/blob/b5b86a9a4abdcd529e923ea9e4aca4093bf8ad10/packages/expo-sqlite/src/SQLite.types.ts#L89-L90), though it isn't documented. On v44 of the Expo SDK, I found that returning `false` didn't forward the error to the `SQLTransactionErrorCallback` from [transaction](https://github.com/expo/expo/blob/b5b86a9a4abdcd529e923ea9e4aca4093bf8ad10/packages/expo-sqlite/src/SQLite.types.ts#L38-L42) and returning `true` did.

**Comment by Tamar-J** [comment]
I ran into this as well (SDK 46 - Bare Workflow).

**Comment by epolat-github** [comment]
This is still an issue. I want to return the error object itself, not a boolean. I am on SDK 47 - Managed workflow.

**Comment by janusqa** [comment]
Any progress on this? I have the same issue.

**Comment by cleaver** [comment]
I ran into this issue while trying to figure out what the boolean return value should be for `SQLStatementErrorCallback`. Since this API is modelled on WebSQL, it turns out that the return value is essentially `rollback transaction?`. If you return `false`, it will just keep going to the next statement of the transaction. In most cases, you'd want to return `true` as you probably want to roll back the transaction.

Assuming you're wrapping this in a promise, your code might look something like:

```ts
const promise = new Promise((resolve, reject) => {
  database.transaction((tx) => {
    tx.executeSql(
      `STATEMENT THAT WILL FAIL...`,
      [ ...parameters ],
      (_, result) => {
        resolve(result);
      },
      (_, error) => {
        reject(error);
        return true;
      }
    );

    tx.executeSql(
      `NEXT STATEMENT`, ...
    );
  });
});

promise
  .then((result) => { /* Do something */})
  .catch((error) => { console.log(error); });
```

I haven't really tested this out, so please let me know if it doesn't work, or corrections are required.

If this does the trick, then it works according to specification and we should probably close this one.

**Comment by gojayevmurad** [comment]
.
