### ISSUE TITLE
useBackgroundPermissions, requestPermission not working

### ISSUE THREAD

**Issue by tamis-laan** [expo/expo#16990]
### Summary

The hook 'useBackgroundPermissions' from the expo-location package does not work properly. 

```javascript
	const [status, requestPermission] = useBackgroundPermissions()
        requestPermission()
```
When calling `requestPermission` no permission window is shown. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

"expo-location": "~14.0.1",

### Environment

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

### Reproducible demo

	const [status, requestPermission] = useBackgroundPermissions()
        requestPermission()

**Comment by byCedric** [comment]
@tamis-laan Please see my sort-of guide for the background permission here https://github.com/expo/expo/issues/16701#issuecomment-1080693258. The one that's interesting for you is:
> 2. **From Android 11, you need foreground permission before asking background permission**

Hope this helps!
