### ISSUE TITLE
Android build crashes with SDK 44 and Expo Updates 0.11.6

### ISSUE THREAD

**Issue by thibaultfischer** [expo/expo#16998]
### Summary

When upgrading the compileSdkVersion to 31, Android build crashes.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.11 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.2 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo

Here is a link to a repository created to reproduce the issue, it's an expo init project with expo-updates install, nothing more.

[Minimal project to reproduce](https://github.com/tfisc/expo-updates-sdk-44-error/)

yarn install

Create a local.properties at ./android/.local.properties to add your android sdk path with this line : 

sdk.dir=/path-to-your-android-sdk

cd android
./gradlew assembleRelease => Build successfull

go to ./android/build.gradle
bump compileSdkVersion and targetSdkVersion from 30 to 31

./gradlew assembleRelease => Build Failed

* What went wrong:
Execution failed for task ':expo-updates:kaptReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by byCedric** [comment]
Seems similar to #16949.
