### ISSUE TITLE
Expo doesn't work with yarn workspaces

### ISSUE THREAD

**Issue by spearson23** [expo/expo#1699]
### Description

If an expo project is a workspace in a yarn workspace project, it will not work. 
More globally, expo won't look in parent directories node_modules for modules.

Note that the example project is setting react-native and expo to 'nohoist' in yarn workspaces, because expo won't even load without that. The only work around to this issue is to set all dependencies in the expo project to 'nohoist', but that defeats the purpose of yarn workspaces. Plus, expo should know to look in parent directory node_modules for files (and it appears to be trying, but somehow failing).

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/spearson23-705b92b9-0cd0-41a8-ad79-2c31532d2593.tar.gz

### Steps to Reproduce

1. git clone https://github.com/spearson23/expo-yarn-workspaces.git
2. cd expo-yarn-workspaces/
3. yarn install
4. cd packages/expo/
5. exp start
6. (In new terminal) exp ios

### Expected Behavior

1. App runs correctly

### Actual Behavior

Get Error: Unable to resolve module 'immutable' from '/HOME_DIR/expo-yarn-workspaces/packages/expo/App.js': Module 'immutable' does not exist in the Hast module map or in these directories: /HOMEDIR/expo-yarn-workspaces/node_modules

Even though immutable is in that directory.

**Comment by brentvatne** [comment]
we don't support this explicitly, so ymmv. you will want to look into the woefully underdocumented rn-cli.config.js, for example https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/rn-cli.config.js we use it to use react-navigation from a parent dir. afaik we do nothing different from react-native / metro's defaults here. have you managed to get this working on other react-native apps, or do you have some other information that leads you to believe that this is an expo specific issue?

**Comment by kevinwolfcr** [comment]
If this works for someone, this is the `rn-cli.config.js` I am using:

```js
/* eslint-disable import/no-extraneous-dependencies */
const getWorkspaces = require('get-yarn-workspaces')
const path = require('path')

function getConfig(from) {
  const workspaces = getWorkspaces(from)
  const roots = [
    path.resolve(from),
    path.resolve(from, '..', '..', 'node_modules'),
  ].concat(workspaces)

  const config = {
    getProjectRoots: () => roots,
    watchFolders: roots,
  }

  return config
}

module.exports = getConfig(__dirname)
```
