### ISSUE TITLE
app.json is used instead of exp.json

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#170]
See react-community/create-react-native-app#114 for the actual error raised. The project has both app.json and expo.json, and having app.json used instead of expo.json is causing problems.

I think we may want to try to standardize on app.json? Or try merging the keys in both?

**Comment by nsisodiya** [comment]
Today, I am trying to publish a demo app and facing lots of confusion between exp.json and app.json

IMHO - lets keep app.json. because when I used CRNA, it create app.json.
And all the keys inside exp.json, can be moved inside "expo" key of app.json !!

**Comment by brentvatne** [comment]
that's the plan, we will remove exp.json and replace it with app.json likely in the next release

**Comment by dikaiosune** [comment]
The template projects now default to app.json. It'll be some time before we can deprecate exp.json fully, but this should resolve the issue for new projects.
