### ISSUE TITLE
[android][expo-splash-screen] preventAutoHide throw "No native splash screen registered..." inconsistently

### ISSUE THREAD

**Issue by theohdv** [expo/expo#17008]
### Summary

We didn't manage to reproduce this issue locally, so I can't give a specific reproduction schema. As it seems to happen randomly, I think it's not a setup issue.
Not sure it's related, but it has happened since a release which enabled Hermes and upgraded RN from '0.64.x' to `0.65.x`.

Sentry is reporting the following issue:
```
No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android).
```

with the following stacktrace:

![Screenshot 2022-04-11 at 18 13 21](https://user-images.githubusercontent.com/26060802/162784560-321ec71e-e6f3-4a42-bc7a-8701940a3df8.png)

We don't call preventAutoHide method ourselves as we are using expo `<AppLoading />` component.

The stacktrace shows that it comes from https://github.com/expo/expo/blob/main/packages/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreen.kt#L121

I assume that `SplashScreenScreen.show` in [SplashScreenReactActivityLifecycleListener](https://github.com/expo/expo/blob/main/packages/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenReactActivityLifecycleListener.kt#L17) has not been called yet

Is it possible that expo `<AppLoading />` [constructor](https://github.com/expo/expo/blob/sdk-44/packages/expo-app-loading/src/AppLoadingNativeWrapper.tsx#L13) is called before `SplashScreenScreen.show` in the `SplashScreenReactActivityLifecycleListener` ?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-25 | Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

We didn't manage to reproduce this issue locally, so I can't give a specific reproduction schema. The issue has been reported by sentry in production code.

**Comment by shamilovtim** [comment]
Can confirm the warning goes away when I comment out Apploading
