### ISSUE TITLE
TypeError: undefined is not a function (near '...TaskManager.defineTask...')

### ISSUE THREAD

**Issue by jb9229** [expo/expo#17015]
### Summary

expo Task Manager is not working in iOS
![Simulator Screen Shot - iPhone 13 - 2022-04-12 at 18 48 50](https://user-images.githubusercontent.com/3200647/162933108-a15c4bb7-4cc3-4b68-b9bd-78f544321d92.png)

could i edit
````
#import <UMCore/UMAppDelegateWrapper.h>

@interface AppDelegate : UMAppDelegateWrapper <RCTBridgeDelegate>
````
now i am using 'EXAppDelegateWrapper', it is not support "expo task manager"??

https://docs.expo.dev/versions/latest/sdk/task-manager/

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

sdk 44

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.8.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.50.0
    Expo Workflow: managed

node 14.17.x also same

### Reproducible demo

https://docs.expo.dev/versions/latest/sdk/task-manager/
official expo task manager example

````
import React from 'react';
import { Text, TouchableOpacity } from 'react-native';
import * as TaskManager from 'expo-task-manager';
import * as Location from 'expo-location';

const LOCATION_TASK_NAME = 'background-location-task';

const requestPermissions = async () => {
  const { status } = await Location.requestPermissionsAsync();
  if (status === 'granted') {
    await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
      accuracy: Location.Accuracy.Balanced,
    });
  }
};

const PermissionsButton = () => (
  <TouchableOpacity onPress={requestPermissions}>
    <Text>Enable background location</Text>
  </TouchableOpacity>
);

TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
  if (error) {
    // Error occurred - check `error.message` for more details.
    return;
  }
  if (data) {
    const { locations } = data;
    // do something with the locations captured in the background
  }
});

export default PermissionsButton;
````

**Comment by byCedric** [comment]
Hi @jb9229! For the task manager, you'll need to use your own build and not Expo Go. So I would check these things:
1. Are you using a custom dev client, or built a production app?
2. Did you add `expo-task-manager` after the first build, and did not do a rebuild? (because you'll need to rebuild since it contains native APIs that aren't included in the first build without `expo-task-manager`).

Hope this helps!

**Comment by jb9229** [comment]
Thank you to reply @byCedric 

1. i am used custom dev client(expo client:ios and expo run:ios), I didn't understand exactly(built a production app?) but i built development app.
<img width="170" alt="스크린샷 2022-04-18 오후 5 05 06" src="https://user-images.githubusercontent.com/3200647/163777554-d1a1f410-5c28-44cb-a225-5154b1acd37e.png">

2. yes i am rebuild it several times.
  - eas build --profile development --platform ios
  - 
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-04-18 at 17 52 46](https://user-images.githubusercontent.com/3200647/163783644-7b3e0c1a-f20c-45ad-8d06-f6b088c3034c.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-04-18 at 17 52 33](https://user-images.githubusercontent.com/3200647/163783662-9a67231a-02c8-4ab3-b7fd-36b26df39dcc.png)

**Comment by trajano** [comment]
@jb9229 were you able to find the issue? I got it on my experiments app.  I get occasional logs that says 
> Task 'background-fetch' failed: undefined is not a function
