### ISSUE TITLE
[docs] reversed vs reserved in Google Auth docs is causing confusion

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1701]
https://github.com/expo/expo/issues/1053#issuecomment-384495262

**Comment by cruzach** [comment]
This is definitely confusing, but you can now simply bundle your `GoogeService-Info.plist` instead, thanks to [922](https://github.com/expo/expo-cli/pull/922). Paves the way to deprecate providing the actual reverse client ID itself in app.json
