### ISSUE TITLE
Error when installing Expo modules

### ISSUE THREAD

**Issue by raminious** [expo/expo#17012]
### Summary

An attempt to install Expo modules failed due to the following guide: https://docs.expo.dev/bare/installing-expo-modules/

Automatic installation by `npx install-expo-modules`:

```
ramin [rnexpo]  → npx install-expo-modules
✔ Expo modules minimum iOS requirement is 12.0. This tool will change your iOS deployment target to 12.0. Do you want to continue? … yes
› Updating your project...
Uncaught Error Error: [android.mainActivity]: withAndroidMainActivityBaseMod: Unable to find ReactActivityDelegate new instance code block.
    at setModulesMainActivity (/Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1423054)
    at /Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1422000
    at action (/Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1212818)
    at interceptingMod (/Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1211282)
    at action (/Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1188612)
    at async interceptingMod (/Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1211276)
    at async evalModsAsync (/Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1194978)
    at async Object.compileModsAsync (/Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1193696)
    at async runAsync (/Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1420141)
    at async /Users/ramin/.npm/_npx/d80a5a2fd0b43bdc/node_modules/install-expo-modules/build/index.js:2:1420561
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

5.3.1

### Environment
```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      npm: 8.5.4 - ~/.nvm/versions/node/v14.19.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.0 => 0.68.0 
    npmGlobalPackages:
      expo-cli: 5.3.1
    Expo Workflow: bare
```

### Reproducible demo

```
npx react-native init myApp
cd myApp
npx install-expo-modules
```

**Comment by Kudo** [comment]
hi there! do you mind to share your `MainActivity.java` content? in some cases we find the automatic `install-expo-modules` cannot fulfill every use cases when projects have difference setup. we would suggest [the manual installation](https://docs.expo.dev/bare/installing-expo-modules/#manual-installation) as an alternative.

**Comment by raminious** [comment]
Hi @Kudo 
Thanks for quick reply!

Sure, this is the MainActivity file: https://gist.github.com/raminious/7c7f802046b9ae7aedba7d02014054db

I also tried the manual installation method. There seems to be a discrepancy between the manual and the files I have.
For example, I couldn't find `RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge` in my [ios/MyApp/AppDelegate.m](https://gist.github.com/raminious/317dac75dba7cfe0b96ee717dc90a4a3) so it prevented me to continue working on that.

**Comment by Kudo** [comment]
@raminious nice! i didn't notice you're in react-native 0.68. for 0.68, we will add the support as well as updated `install-expo-modules` from the next expo sdk. that would be hopefully released in early May.

**Comment by raminious** [comment]
Awesome!!! 🚀

**Comment by Kudo** [comment]
thanks. i'm closing this issue. if the new expo sdk doesn't work for you then, please feel free to reopen or create a new issue.

**Comment by uloco** [comment]
So does this mean, there is currently no way to use `expo-modules` at all with `react-native@0.68.1`?

**Comment by raminious** [comment]
@uloco it seems

**Comment by uloco** [comment]
Oh I just have seen that this issue is only related to android. I don't know the differences between our projects but I was able to follow the manual instructions in expo and upgrade helper and make android build. Nevertheless I have issues with iOS, because the migration guide references code I could not find / change.

**Comment by felipejoribeiro** [comment]
Can't run `npx install-expo-modules` yet, it prompts the same error, i'm trying to install expo libs in my native react app.

**Comment by Kudo** [comment]
@felipejoribeiro if you are using the latest install-expo-modules@0.3.2, do you mind to share your MainActivity.java? maybe there's some inconsistency between your MainActivity.java and react-native@0.68's that install-expo-modules doesn't cover.

**Comment by felipejoribeiro** [comment]
Here it is:

```
package com.snackin;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "Snackin";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
   * you can specify the rendered you wish to use (Fabric or the older renderer).
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new MainActivityDelegate(this, getMainComponentName());
  }

  public static class MainActivityDelegate extends ReactActivityDelegate {
    public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
      super(activity, mainComponentName);
    }

    @Override
    protected ReactRootView createRootView() {
      ReactRootView reactRootView = new ReactRootView(getContext());
      // If you opted-in for the New Architecture, we enable the Fabric Renderer.
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      return reactRootView;
    }
  }
}
```
I recently created the project.

**Comment by Kudo** [comment]
@felipejoribeiro thanks! the MainAcitivty.java works for me. could you help to check which install-expo-modules version you have (`npx install-expo-modules --version`)?

**Comment by Kudo** [comment]
@felipejoribeiro that's it. the latest version is 0.3.2. npx somehow cache the outdated version. i tried to [cleanup npx cache](https://stackoverflow.com/a/66019858) last time i came across the issue.

**Comment by felipejoribeiro** [comment]
thank you @Kudo ! That solved the problem. Best regards.
