### ISSUE TITLE
Stuck on Splash Screen on iOS device when installing viro package.

### ISSUE THREAD

**Issue by bigxalx** [expo/expo#17029]
### Summary

When I install [viro](https://github.com/ViroCommunity/viro) in a brand new expo project, and follow their official documentation (they provide a config plugin), the resulting dev client gets stuck on the splash screen on iOS Device. 

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

"@viro-community/react-viro": "^2.23.0"
"expo": "~44.0.0",
"expo-dev-client": "~0.8.4",
"react-native": "0.64.3",
Expo CLI: 5.3.1

### Environment

    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.8.0/bin/yarn
      npm: 8.6.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.50.0
      expo-cli: 5.3.1
    Expo Workflow: bare

### Reproducible demo

I followed the [official docs](https://viro-community.readme.io/docs/integrating-with-expo) to install with Expo: 

- I run `expo init`. I chose Template with Typescript and Tabs. 
- I install Viro: `yarn add @viro-community/react-viro`
- I add the config plugin to app.json
- I install expo dev client: `expo install expo-dev-client` (As far as I know I need to do this because Viro installs native packages that don't work with the standard Expo client). 
- Now I run the build with `expo run:ios -d` to launch on my device. 

The app starts and shows the splash screens. It successfully connects to Metro, bundles and downloads Javascript but keeps showing the splash screen forever. 
If I create a production build via `expo run:ios --configuration Release -d`, the app works. If I run the dev build on iOS Simulator or on Android (device or simulator), the app works. 

I did some troubleshooting and found the following: 
I tried running this project: https://github.com/vnovick/viro-expo-eas-sample and it works. It uses the same versions of the packages described below. However, if I run `expo prebuild --clean` on this project, and then build, I get the same behaviour as described above.

**Comment by bigxalx** [comment]
Yes. That’s why I included the info about the GitHub repo with the sample integration. That seems to be about a month old and was obviously built with expo (and works). It uses the same package versions. That made me think that it may be an issue of the more recent versions of the expo CLI? 

Additionally, the behavior is very similar to, and the log output from Xcode is identical to this issue: https://github.com/expo/expo/issues/16523, giving me reason to believe it might be related to expo tooling. 

I am not sure about this at all, and wanted to bring this to your awareness. 

Of course I also created an issue on viro’s GitHub.

**Comment by lukmccall** [comment]
Hi, @bigxalx, I think that bug was fixed in the `expo-dev-client@0.9.3`. Could you try the newest version?

**Comment by bigxalx** [comment]
I did try it, but couldn't get it to work. 
It now gives me a `UIAccessibilityTraits` Error. Been looking through Viro's issues and found other references. At this point i am pretty sure the problem lies with the Viro Framework. We eventually gave up decided against using it.
