### ISSUE TITLE
Scoped permissions: Don't re-prompt in existing ExpoKit projects

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1702]
See: https://forums.expo.io/t/ios-users-getting-re-prompted-for-already-granted-permissions-in-sdk-27/9269

**Comment by aalices** [comment]
Going to follow Eric's solution for iOS

**Comment by terribleben** [comment]
This is fixed in our standalone builder as of yesterday. For people using detached projects, the `ios/2.5.6` tag (and newer) contains this fix.
