### ISSUE TITLE
Web barStyle in app.json doesn't change the PWA status bar colour for iOS in standalone PWA mode

### ISSUE THREAD

**Issue by chinesehemp** [expo/expo#17038]
### Summary

I have an expo web project which I'm building as a PWA. For the life of me, I can't work out how to change the status bar background colour using app.json. Here's my app.json config for web barStyle.

```
      "barStyle": "black-translucent",
```

In the web_build/index.html file, I see the correct meta tag applied...

```
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
```

But when running in iOS simulator and on real iPhone 12 Pro, I see the following and I can't change it no matter what settings for "barStyle" I've tried "black", "default", and "black-translucent" with no effect on the actual appearance of the bar style.

<img width="451" alt="Screenshot 2022-04-13 at 09 51 52" src="https://user-images.githubusercontent.com/58605231/163140149-770fd767-c352-42ab-abc5-dc3e9b841d64.png">

Is there a way to fix this? I have a black app bar header which looks awful with the status bar in white above.

Thank you.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 3.2.2 - /usr/local/bin/fish
    Binaries:
      Node: 16.4.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.19 => 0.16.20 
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.1
    Expo Workflow: bare
```

### Reproducible demo

Not possible as the issue can be only reproduced when running as a PWA on iOS.

**Comment by JonathanRadotski** [comment]
Hi there, it seems I encountered the same issue as shown here:
<img src="https://github.com/expo/expo/assets/41282463/bccf33b7-ae4f-4e65-94ff-5671c2e21197"/>
Did you happen to know the fix yet? @chinesehemp

**Comment by anastakozz** [comment]
Hi! [This](https://firt.dev/ios-14.5/#status-bar-change) article helped to solve the problem . black-translucent just seems to be totally deprected... try to use this: 
<img width="629" alt="Screenshot 2024-07-02 at 18 53 32" src="https://github.com/expo/expo/assets/117598324/e2b71323-6d1a-4603-8826-4f6077497ef1">
