### ISSUE TITLE
Android - no available extractors error

### ISSUE THREAD

**Issue by msvajhartGH** [expo/expo#17047]
### Summary

On android if the file type is not at the end of the uri string expo-av doesn't know what video extractor to use.

In my use case we add a query string JWT to the end of a video for security of the video asset. This disrupts how Expo-AV reads file type.

https://stream.mux.com/QJEvayiCDLkkPP8n28sczqHKK9NVtJhi9URXOaeIXT00.m3u8?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpKQVVJMUg3dG0zS3dzdzVWVW5hVlJCamlRbjAyMlZtMDFVTTk0eHNKVTAwOEEifQ.eyJleHAiOjE2NDk5NTU1NDgsImF1ZCI6InYiLCJzdWIiOiJRSkV2YXlpQ0RMa2tQUDhuMjhzY3pxSEtLOU5WdEpoaTlVUlhPYWVJWFQwMCJ9.MTfacvxT5h9sw_icpMVVMpgseTK0XdJp4DHM13BaB2R1uuDQMFL9WoFdY3Lzb0WA3C-RP_mOZpl4lbeItO1Wi7p6eiAFIEh31pOZDl0dDxXbNTPrUkTR9vfcuTYmD0z-wxvPg6suaEJOOo5pN4Uy8rGGofCb3ndrw_FXlWNqSelFyTPPFHUWxBRMC9vTtm5XXuecvd8nXOKNCw1xr7Igq-qohozEK2jNzBKjdqltdb-8L-qJX5dBcwD_fXQSgl65-bH_qMoJlP4kA0zODszfWlarZwFgb9OxE5PMeSZl6MrtgznIM3vfgz3N_FN7hqzxRzmLKox3BVHW_DzjEkzH_w

[Unhandled promise rejection: Error: h.f.c.d.q0.f0: None of the available extractors (e, g, i, e, g, e, d0, c, d, w, b, b) could read the stream.]

Please add a way for me to tell the player what type of video is being played instead of trying to parse a uri string.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

"expo": "^44.0.0",

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Reproducible demo

[snack](https://snack.expo.dev/@msvajhart/video)

in the snack example i put three video views.
1 with just a token
1 with no token
1 with a token and a querystring that contains the file type at the end. (this hack is how im getting around the problem right now but it is starting to have issues with the video provider, i shouldnt have to add this heck, just let me define the video file type in a prop to source={uri: "<url>>token=1234", type: "m3u8"})

**Comment by 13627491210** [comment]
i have the same issue, Have you solved it ?

**Comment by byrnehollander** [comment]
I was able to fix this by setting [`overrideFileExtensionAndroid`](https://docs.expo.dev/versions/latest/sdk/av/#playback-api):

```
<Video source={{ uri: muxLinkWithJWT, overrideFileExtensionAndroid: "m3u8" }} />
```
