### ISSUE TITLE
Expo Device `isDevice` error

### ISSUE THREAD

**Issue by Rcuz8** [expo/expo#17055]
### Summary

An error throws when using `Device.isDevice` from `expo-device`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.7.1 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.5.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 32
        Build Tools: 29.0.2, 32.0.0
        System Images: android-29 | Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.64.1 => 0.64.1 
      react-native-web: ^0.17.1 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

```
import Device from "expo-device";

export async function getPushToken(): Promise<string> {
  console.log(Device.isDevice); // Error throws here
  return "";
}
```

Error:
```
Possible Unhandled Promise Rejection (id: 1):
TypeError: undefined is not an object (evaluating 'expo_device_1.default.isDevice')
```

**Comment by brentvatne** [comment]
note the correct import format from the docs:

```js
import * as Device from 'expo-device';
```

https://docs.expo.dev/versions/latest/sdk/device/#api
