### ISSUE TITLE
Lack of documentation in expo-dev-client

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#17073]
### Summary

There is an important thing missing in https://docs.expo.dev/development/getting-started/

> and installing the resulting build on your device.

it doesn’t say HOW to install it on the device. Should I EAS submit and download it from TestFlight as I do with the prod build? Or is there other way?

I have been avoiding using expo-dev-client since it exists, mainly because I don’t have information about how to proceed in that step.

thanks 😊!

### Link to the related docs page

https://docs.expo.dev/development/getting-started/

### Anything else?

Love you all

**Comment by byCedric** [comment]
Hi @BrodaNoel and @stefanleoussis! It's part of our EAS build documentation. If you want to install something on your phone for testing purposes, [you can build for "internal distribution"](https://docs.expo.dev/build/internal-distribution/). You can also submit it to test flight of course, but with the internal distribution build, the only thing you need to do is:
> When the build completes, you will be given a URL that you can share with your team to download and install the app. 

If you have a fully set up mac, with Xcode, you can also just run `expo run:ios --device` to build and start it directly on your device.

Hope this helps!

**Comment by BrodaNoel** [comment]
@byCedric let me double check if I got it right:

If I follow the documentation in https://docs.expo.dev/build/internal-distribution/, I should be able to have installed in my phone the Production **AND the Internal Distribution version** of my app, **where the Internal Distribution version will be the expo-dev-client app that will replace my Expo Go** (so, **I will still be able to code and see the app refreshing when saving a change in a file**)

**Comment by BrodaNoel** [comment]
I see 2 documentations that are quite similar:
- https://docs.expo.dev/build/internal-distribution/
- https://docs.expo.dev/build-reference/variants/

Are we sure that we have to follow the doc for Internal Distribution, in order to have the "dev env" build installed in the device? ("dev env": allows me to code in my computer, and see the changes in the app with the auto-refresh).
Or should we follow the doc for "build-reference / variants", which has some references to `"developmentClient": true` (which feels like it's the way to have the dev-env working)
