### ISSUE TITLE
ImagePicker Promise Rejects on First Attempt Though Permission.CAMERA Granted

### ISSUE THREAD

**Issue by geirman** [expo/expo#1707]
### Summary
Granting camera access then immediately using that access with `ImagePicker` results in a promise rejection `[Error: Missing camera or camera roll permission.]`. 

### Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.2.1
  Yarn: 1.2.1
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/geirman-9b12d065-1f0c-42c8-9884-9be91c7f5621.tar.gz

Expo Client

### Steps to Reproduce

1. Load the demo app below
2. Tap "Pick from Camera" button
3. Tap to authorize camera access
4. RESULT: camera fails to launch, note the output of console.log
5. Tap "Pick from Gallery" button
6. Tap to authorize camera roll access
7. RESULT: camera roll launches as expected, note output of console.log
8. Tap "Pick from Camera" again
9. RESULT: camera launches, note the output of console.log (everything is fine at this point)

### Expected Behavior

**For bullet 4** above, I expect camera launch and the following output after taking a photo...

```
camera granted
cameraRoll SUCCESS Object {
  "cancelled": false,
  "height": 2848,
  "type": "image",
  "uri": "file:///...54B7F932-9E42-443D-8B25-B41892A4C283.jpg",
  "width": 4288,
}
```

**For bullet 7** above, I expect **camera roll** to launch and the following output after taking a photo...

```
cameraRoll granted
cameraRoll SUCCESS Object {
  "cancelled": false,
  "height": 2848,
  "type": "image",
  "uri": "file:///.../54B7F932-9E42-443D-8B25-B41892A4C283.jpg",
  "width": 4288,
}

```
### Actual Behavior
Camera is not working correctly on first attempt. To spite being "granted" access, the promise rejects and the following is the output. Repeatedly tapping "Pick from Camera" will repeatedly result in a promise rejection. However, once I "Pick from Gallery", then "Pick from Camera" will start working as expected. 

```
camera granted
camera Object {
  "error": [Error: Missing camera or camera roll permission.],
}
camera SUCCESS undefined
```

### Reproducible Demo
https://snack.expo.io/@geirman/permissions-camera-camera-roll

```
import React, { Component } from 'react';
import { View, StyleSheet, Button } from 'react-native';
import { Constants, Permissions, ImagePicker } from 'expo';


export default class App extends Component {
  pickFromGallery = async () => {
    const permissions = Permissions.CAMERA_ROLL;
    const { status } = await Permissions.askAsync(permissions);

    console.log(permissions, status);
    if(status === 'granted') {
      let image = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: 'Images',
      }).catch(error => console.log(permissions, { error }));
      console.log(permissions, 'SUCCESS', image);
    }
  }

  pickFromCamera = async () => {
    const permissions = Permissions.CAMERA;
    const { status } = await Permissions.askAsync(permissions);

    console.log(permissions, status);
    if(status === 'granted') {
      let image = await ImagePicker.launchCameraAsync({
        mediaTypes: 'Images',
      }).catch(error => console.log(permissions, { error }));
      console.log(permissions, 'SUCCESS', image);
    }
  }



  render() {
    return (
      <View style={styles.container}>

        <Button
          title="Pick from Camera"
          onPress={this.pickFromCamera}
        />
        <Button
          title="Pick from Gallery"
          onPress={this.pickFromGallery}
        />

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
});

```

**Comment by esamelson** [comment]
Hi @geirman - this may have changed recently due to some changes to our permissions handling, but according to the [docs](https://docs.expo.io/versions/v26.0.0/sdk/imagepicker#expoimagepickerlaunchcameraasyncoptions) you need both CAMERA and CAMERA_ROLL permissions to use the `launchCameraAsync` method on iOS, at least. Was this not the case for you in the past?

**Comment by giautm** [comment]
@esamelson :  I also have the same problem, I make sure to have executed `Permissions.askAsync()` to both permissions. But, sentry still reports this problem with iOS user.
<img width="633" alt="screen shot 2018-04-27 at 19 38 22" src="https://user-images.githubusercontent.com/12751435/39391199-fd13b216-4ac9-11e8-8e96-5bbad58e82e6.png">
above code added by recommends from @aalices to fix same issues on Android.

<img width="831" alt="screen shot 2018-04-28 at 09 49 05" src="https://user-images.githubusercontent.com/12751435/39391193-e7051e1a-4ac9-11e8-83c3-d7b19445d000.png">

**Comment by geirman** [comment]
@esamelson Actually, up until now, I never even bothered to check the Permissions. I just used the ImagePicker without even checking and it was working fine until I tested on Android and iPad tablets. That is when I noticed the issue.

**Comment by giautm** [comment]
@geirman : After pressed to the button that shows ImagePicker, iOS show an alert to asking permissions from User. But after I press OK to accept the permission, nothing to happen then. An exception thrown in the background and Sentry still report it: `Missing camera or camera roll permission.`

**Comment by joduplessis** [comment]
Having the same issue using ImagePicker.launchImageLibraryAsync.

**Comment by seanking11** [comment]
I solved this after being told to look at the [upgrade guide](https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4). I was doing everything right with asking for permissions, however, I hadn't followed the proper instructions updating my dependencies and my app.json file, etc.

**Comment by giautm** [comment]
I resolved this problem by the upgrade to SDKv27 (from SDKv24). Unhappy with this experience, the old SDK not stable when the new SDK was released. 👎

**Comment by joduplessis** [comment]
Also agree here, would be nice to see some stability releases happening.

**Comment by esamelson** [comment]
Understood

**Comment by sigma-react** [comment]
I am getting similar issue after allowing permissions required as per new SDK, now issue of error is resolved but we are unable to open camera now for taking image

**Comment by edupooch** [comment]
I was having the same issue on Android using the expo client v 2.5.0. I downgraded the app version back to v2.4.0 and it worked as expected.

**Comment by kukuandroid** [comment]
I'm still facing the issue after upgrading to Expo v27. OMG, someone please help ('crying')

**Comment by wagnercsfilho** [comment]
Same issue after upgrading to Expo v27 😢

**Comment by giautm** [comment]
Did you use `Permissions.askAsync()` in your code?

**Comment by geirman** [comment]
Upgraded to Expo v27

With the following code...

```
  pickFromCamera = async () => {
    const permissions = Permissions.CAMERA_ROLL;
    const { status } = await Permissions.askAsync(permissions);

    console.log(`[ pickFromCamera ] ${permissions} access: ${status}`);
    this.handleModalDismiss();
    if (status !== 'granted') {
      Sentry.captureException(new Error(`[ pickFromCamera ] ${permissions} access: ${status}`));
    } else {
      let image = await ImagePicker.launchCameraAsync().catch(error => console.log({ error }));
      this.maybeEmailImage(image);
    }
  };
```

I receive the following log output in Expo...


```
[ pickFromCamera ] camera access: granted
Object {
  "error": [Error: Missing camera or camera roll permission.],
}
```

**Comment by esamelson** [comment]
Hi -- you need to request *both* `CAMERA` and `CAMERA_ROLL` permissions to use this method in SDK 27. Again, sorry for the confusion here.

**Comment by jhalborg** [comment]
Just did, `exp diagnostics`:

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^24.0.0 => 24.0.2
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0
```

**Comment by aalices** [comment]
🤔 `24.0.3` should be installed, can you try using `npm update` ?

**Comment by jhalborg** [comment]
Using yarn, ran the following command `"nuke": "rimraf node_modules && watchman watch-del-all && yarn install",` using `yarn nuke`

**Comment by jhalborg** [comment]
Confirmed. I force-updated by setting the following dependency:

`"expo": "^24.0.3",`

which resolves to that exact version. Why it didn't before is beyond me.

**Comment by esamelson** [comment]
@jhalborg if you're using yarn, it will always resolve to the exact version in the yarn.lock file, rather than just grabbing the most up-to-date version each time. Force-updating as you've done is the correct solution in that case.

**Comment by jhalborg** [comment]
@esamelson - AFAIK, carets work the same in `npm` and `yarn` :) . When I had `^24.0.0` it resolved to `24.0.2`. According to [yarn docs](https://yarnpkg.com/lang/en/docs/dependency-versions/#toc-caret-ranges), caret ranges work the same as with `npm`.

**Comment by robertobrogi** [comment]
wtf! i had update expo 27 but doesn't work the camera.... i change the code but in ios doen't work.....
whats wrong?!?!?!?!
now i have the app in prod and not working the camera!

` takePhoto = async () => {
        this.closeModal()
        //const { status } = await Permissions.askAsync(Permissions.CAMERA);

        const res = await Promise.all([
            Permissions.askAsync(Permissions.CAMERA),
            Permissions.askAsync(Permissions.CAMERA_ROLL)
        ]);

        console.log(res)
        if(res.some((status)=>status === 'granted')) {
            console.log('res')
            let result = await ImagePicker.launchCameraAsync({
                allowsEditing: true,
                aspect: [4, 3],
                base64: true,
                quality: 0.2
            });

            if (!result.cancelled) {
                this.setStateAsync({photo: 'data:image/png;base64,' + result.base64});
                this.setStateAsync({pathImg: result.uri});
            }
        }
    };`

**Comment by brentvatne** [comment]
@robertobrogi - give me some example project where this happens please, I can't reproduce the issue on my end

**Comment by robertobrogi** [comment]
the problem is here:
res.some((status)=>status === 'granted')

the resoult is false but the obj is:

`
Array [
  Object {
    "expires": "never",
    "status": "granted",
  },
  Object {
    "expires": "never",
    "status": "granted",
  },
]`

**Comment by geirman** [comment]
In Expo v27, I have the following code working. My strategy now is to request both `CAMERA` and `CAMERA_ROLL` permissions regardless which button is pressed. Though this code is working, I still have one problem I'm trying to figure out which is that `hasPermissions` executes twice, so I end up with twice the number of permission request modals (2x for camera, 2x for camera roll). This is probably an issue with my specific implementation though. I still have to dig into it, so if anyone has any thoughts...I'm all ears.

Oh, and one other issue. On failure, I'd love to send the user to the app settings where they can manually authorize camera and camera roll. The below `Alert` works on iOS, but the android intent  (`ACTION_MANAGE_APPLICATIONS_SETTINGS`) drops the user into the settings screen for all apps. This might be because Expo is the proxy app, so I'm hoping this behaves differently once I publish as a standa-alone-app. Any thoughts on this would be great too...

Hope it's not inappropriate that I mention these side issues, but here's the working code in it's entirety aside from the aformentioned caveats. 

```
hasPermissions = Promise.all([
    Permissions.askAsync(Permissions.CAMERA),
    Permissions.askAsync(Permissions.CAMERA_ROLL),
  ])
    .then(r => r.filter(o => o.status === 'granted'))
    .then(permissions => {
      if (permissions.length !== 2) {
        return new Error('Camera & Camera Roll Permissions Required');
      }
      console.log({ permissions });
      return true;
    });
  pickFromGallery = async () => {
    this.handleModalDismiss();

    this.hasPermissions
      .then(async () => await ImagePicker.launchImageLibraryAsync({ mediaTypes: 'Images' }))
      .then(this.maybeEmailImage)
      .catch(error => {
        console.log(`[ pickFromGallery ] ${error}`);
        Sentry.captureException(new Error(`[ pickFromGallery ] ${error}`));
        this.permissionsAlert();
      });
  };

  pickFromCamera = async () => {
    this.handleModalDismiss();

    this.hasPermissions
      .then(async () => await ImagePicker.launchCameraAsync())
      .then(this.maybeEmailImage)
      .catch(error => {
        console.log(`[ pickFromCamera ] ${error}`);
        Sentry.captureException(new Error(`[ pickFromCamera ] ${error}`));
        this.permissionsAlert();
      });
  };

  permissionsAlert = () =>
    Alert.alert(
      'Permissions Required',
      'This app requires Camera & Camera Roll access to function properly. Please go to settings to enable manually (or restart the app).',
      [
        { text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel' },
        {
          text: 'Settings',
          onPress: () =>
            layout.isIOS
              ? Linking.openURL('app-settings:')
              : IntentLauncherAndroid.startActivityAsync(
                  IntentLauncherAndroid.ACTION_MANAGE_APPLICATIONS_SETTINGS
                ),
        },
      ]
    );
```

**Comment by bruno-edo** [comment]
@brentvatne - I was having the same issue that @robertobrogi described (with my code being very similar to his).

When I removed the `"permissions"` attribute from my `app.json` file the camera started working again (with the user being prompted to give the app access to `CAMERA` and `CAMERA_ROLL`).

So if your `app.json` file looks anything like the one below, the `Permissions.askAsync()` method will not work correctly on standalone apps and the camera will not open because of that. This started happening after Expo's version 25.0.0.

```javascript
"android": {
      "package": "my.app",
      "versionCode": 3,
      "permissions": [
        "CAMERA"
      ]
    }
```

**Comment by geirman** [comment]
@brentvatne @bruno-edo 
I'm not totally clear of the correct approach then. Should I be using both the Permissions API and app.json to correctly obtain permissions? Sounds like I won't really know if it's going to work until I build my standalone app

**Comment by bruno-edo** [comment]
@geirman - Seems like using both Permissions API and app.json `"permissions"` makes the promises get rejected.

I'm only using the Permissions API on my code for now and it works on my standalone app, I'd recommend doing the same for now.

**Comment by aalices** [comment]
`CAMERA_ROLL` stands for Android's `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`, can you try adding those and check if this works?

**Comment by bruno-edo** [comment]
@aalices just built my standalone app with these permissions on app.json:

```javascript
"permissions": [
    "CAMERA",
    "READ_EXTERNAL_STORAGE",
    "WRITE_EXTERNAL_STORAGE"
]
```
With these configuration both `Permissions.askAsync` and `ImagePicker.launchCameraAsync` worked as intended.

I believe the docs should be updated to address the issues between the Permissions API and the app.json `"permissions"`, because right now there's no way to know the cause of this weird behaviour by just reading them.

**Comment by vadimsg** [comment]
If android is crashing when you request both permissions with Promise.all() try to ask them one by one.
```
const cameraPermission = await Permissions.askAsync(Permissions.CAMERA);
const cameraRollPermission = await Permissions.askAsync(Permissions.CAMERA_ROLL);
```

**Comment by geirman** [comment]
I also noticed that Android would crash sometimes when requesting permissions, so inspired by @vadimsg's suggestion, I rewrote my `hasPermissions` function like so...

It's much cleaner, easier to understand, and also prompts the user only when attempting to access the camera or gallery rather than on screen load.  All upsides. 

On iOS though, I noticed that it works great so long as permissions are granted straight away, but if initially denied then enabled through settings, the permissions prompt displays for a split second, dissappears, then the UI becomes unresponsive forcing me to restart the app. I cannot get it working unless I uninstall/reinstall and accept all permissions. (sad trombone)

```
  hasPermissions = async () => {
    const { CAMERA, CAMERA_ROLL } = Permissions;
    const permissions = {
      [CAMERA]: await Permissions.askAsync(CAMERA),
      [CAMERA_ROLL]: await Permissions.askAsync(CAMERA_ROLL),
    };

    if (permissions[CAMERA].status !== 'granted' || permissions[CAMERA_ROLL].status !== 'granted') {
      return Promise.reject(new Error('Camera & Camera Roll Permissions Required'));
    }
    return Promise.resolve(true);
  };
```

Also, thanks @bruno-edo for confirming that the solution by @aalices works. I've updated my `app.json` in the same way as yours and that seems to be working for me as well...

```
    "permissions": [
      "CAMERA",
      "READ_EXTERNAL_STORAGE",
      "WRITE_EXTERNAL_STORAGE"
    ],
```

@aalices I did try `ACTION_APPLICATION_DETAILS_SETTINGS` as well, but the result was the exact same as `ACTION_MANAGE_APPLICATIONS_SETTINGS`

**Comment by aalices** [comment]
@geirman can you make a gif showing your issue? I cannot reproduce :(
Re: IntentLauncher - the intent you're trying to run requires additional parameter: https://developer.android.com/reference/android/provider/Settings#action_application_details_settings
but I also found this: https://expo.canny.io/feature-requests/p/intentlauncherandroid-missing-intent-with-data-url-support so bad news - it might not work :|

**Comment by geirman** [comment]
@aalices I was going to do one better and create a reduced use case, but in doing so I noticed I couldn't reproduce it either. That's when I realized I had some code dismissing a separate modal, but it was dismissing the permissions modal instead. With a second modal still open, the UI was locked up. So, that's no longer an issue. Thanks!

[Here's a link to the reduced case repo if you're curious](https://github.com/geirman/expo-permissions-camera-cameraroll). Could be useful to point others to if they're looking for example code of doing this. I think it's pretty robust. 

As for the intent, it doesn't seem that critical any longer. Every time the user tries to access the camera or camera roll, I'm executing `hasPermissions()`, which will re-prompt them if permissions haven't yet been granted. But great to know about the `data URI` required. Thanks for sleuthing that out! You've been super helpful!

**Comment by vko-online** [comment]
All you have to do is

```
const { status } = await Permissions.getAsync(Permissions.CAMERA_ROLL)
if (status !== 'granted') {
  await Permissions.askAsync(Permissions.CAMERA_ROLL)
}
const result = await ImagePicker.launchImageLibraryAsync({
  allowsEditing: true,
  aspect: [HEIGHT, WIDTH],
  mediaTypes: ImagePicker.MediaTypeOptions.Images
})
```

**Comment by kumarryogeshh** [comment]
Not working for me, even after permissions status is 'granted', I get 'Unhandled promise rejection: Error: Missing camera roll permission'

**Comment by geirman** [comment]
@kumarryogeshh
Which code did you try? Which version of expo are you using? Using my code above with Expo SDK v27, on Android, it works great. Haven't tested standalone iOS yet.

@aalices 
As a standalone app, `ACTION_APPLICATION_DETAILS_SETTINGS` turned out to be a noop, whereas `ACTION_MANAGE_APPLICATIONS_SETTINGS` drops the user into the list of all apps in settings. Any other suggestions?

**Comment by robertobrogi** [comment]
... in ios not working....
i have expo 27 and:

`let res = await Promise.all([
            Permissions.askAsync(Permissions.CAMERA),
            Permissions.askAsync(Permissions.CAMERA_ROLL)
        ]);`

the result is:

`Array [
  Object {
    "expires": "never",
    "status": "granted",
  },
  Object {
    "expires": "never",
    "status": "granted",
  },
]`

when i call the camera not workin the await not responding....

`if(res[0].status === 'granted' && res[1].status === 'granted') {
            console.log('aaaaaaa')
            let result = await ImagePicker.launchCameraAsync({
                allowsEditing: true,
                aspect: [4, 3],
                base64: true,
                quality: 0.2
            });

            console.log(result)

            if (!result.cancelled) {
                this.setStateAsync({photo: 'data:image/png;base64,' + result.base64});
                this.setStateAsync({pathImg: result.uri});
            }
        }`

**Comment by robertobrogi** [comment]
work just one time when call me the permission and the second time, when i tap the butto nfor open the camera, not working..... 
Frustration

**Comment by dale-french** [comment]
On my side it works locally on Expo but as soon as I publish to the Play Store it asks for permissions for both CAMERA and CAMERA_ROLL but the camera does not open.

Permissions:
```
"permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "CAMERA",
        "READ_EXTERNAL_STORAGE",
        "READ_INTERNAL_STORAGE",
        "RECORD_AUDIO",
        "READ_PHONE_STATE",
        "READ_CONTACTS",
        "android.permission.CHANGE_CONFIGURATION",
        "com.google.android.c2dm.permission.RECEIVE",
        "android.permission.ACCESS_NETWORK_STATE"
]
```
Asking for both permissions in code:
```
const { cameraStatus } = await Permissions.askAsync(Permissions.CAMERA);
const { cameraRollStatus } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
```

**Comment by aalices** [comment]
@dale-french you also have to add `"WRITE_EXTERNAL_STORAGE"` because the photo is saved to your device's gallery.

**Comment by dale-french** [comment]
@aalices that works - thanks!

**Comment by anp** [comment]
Hi everyone! Please excuse me if I'm misreading this, but I *think* the various issues here have been resolved and/or documented so I'll give this a close. Please post back if I'm wrong about that (preferably with a summary of what's still missing) and we'll reopen.

**Comment by geirman** [comment]
I agree and probably should have closed it myself, but the conversation has been lively.

**Comment by anp** [comment]
No problem at all! Just doing a little housekeeping :D.

**Comment by soikatesc** [comment]
Not working at all. Camera is not launching even though status is granted. 


const { status } = await Permissions.getAsync(Permissions.CAMERA_ROLL);

    	if (status !== 'granted') {
  			await Permissions.askAsync(Permissions.CAMERA_ROLL)
		}

		const result = await ImagePicker.launchImageLibraryAsync({
		  allowsEditing: true,
		  aspect: [HEIGHT, WIDTH],
		  mediaTypes: ImagePicker.MediaTypeOptions.Images
		})

		console.log(result);

**Comment by jkmf** [comment]
In my case this did the trick:
await Promise.all([
	await Permissions.askAsync(Permissions.CAMERA_ROLL),
	await Permissions.askAsync(Permissions.CAMERA)
]).then(...)

and setting permissions in app.json: 
"CAMERA",
"WRITE_EXTERNAL_STORAGE"
