### ISSUE TITLE
Expo AV returns an error each time I try to start a recording

### ISSUE THREAD

**Issue by Kellie-Brighty** [expo/expo#17095]
### Summary

I expect that when I tap on my record button, the recording session should start.

Instead, I get a persistent error, an I don't know how to Fix that. 

[Error: Prepare encountered an error: Error Domain=NSOSStatusErrorDomain Code=561145203 "(null)"]

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

10.2.0

### Environment

[expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\Desktop\chatpay-mobile\node_modules\.bin\yarn.CMD
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed](url)

### Reproducible demo

Expo AV keeps returning this error => [Error: Prepare encountered an error: Error Domain=NSOSStatusErrorDomain Code=561145203 "(null)"]... each time I try to start an audio recording.

Here's my snack link. The problem can be reproduced with the available code on there,

https://snack.expo.dev/@kelly_owoju/kellys-snack

**Comment by hirbod** [comment]
Did you also try using your systems voice memo app? Is that by chance an iPhone 7?
Ich remember this code and it was a faulty chip/microphone on my end.
