### ISSUE TITLE
expo-gl is requiring unimodules-core 

### ISSUE THREAD

**Issue by unit-002** [expo/expo#17094]
### Summary

I am using `expo": ">=44.0.0-0 <45.0.0"` ver on my react native bare workflow. I am also  using `@tensorflow/tfjs-react-native"` which requires `expo-gl` and `expo-gl-cpp`. 

I was using react-native-unimodules before and my app works perfectly since last year but now I am trying to upgrade and migrate to expo modules so that I can use the latest expo camera version, but with expo gl  I get an error:

```
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.   
   > Could not resolve project :unimodules-core.
     Required by:
         project :app
      > No matching configuration of project :unimodules-core was found. The consumer was co
nfigured to find a runtime of a component, as well as attribute 'com.android.build.api.attri
butes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.
   > Could not resolve project :unimodules-react-native-adapter.
     Required by:
         project :app
      > No matching configuration of project :unimodules-react-native-adapter was found. The
 consumer was configured to find a runtime of a component, as well as attribute 'com.android
.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.
```
Then I installed @unimodules/core, @unimodules/react-native-adapter and unimodules-app-loader but then another error appear:

```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#org.unimodules.core.AppLoader#react-native-he
adless@value value=(org.unimodules.adapters.react.apploader.RNHeadlessAppLoader) from [:unim
odules-react-native-adapter] AndroidManifest.xml:14:13-88
        is also present at [:expo-modules-core] AndroidManifest.xml:14:13-86 value=(expo.mod
ules.adapters.react.apploader.RNHeadlessAppLoader).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidMan
ifest.xml:12:9-14:91 to override.
```
Then I added the suggestion to my  AndroidManifest.xml like this:

```
<application
......
   <meta-data
     tools:replace="android:value"
     android:name="org.unimodules.core.AppLoader#react-native-headless"
     android:value="org.unimodules.adapters.react.apploader.RNHeadlessAppLoader"
   />
</application>
```
then I get another error:
```
* What went wrong:
Execution failed for task ':unimodules-react-native-adapter:compileDebugKotlin'.
```
I change the version of  kotlin in my build.gradle to the same version as my android studio from:
`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"`
to
`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"`

then I get another error:
```
* What went wrong:
Execution failed for task ':expo-modules-core:compileDebugKotlin'.
```
Doesn't expo-module sdk 43 above already have expo-module-core?

I don't know what to do after this. I'm stuck.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
React native 0.63.4
expo": ">=44.0.0-0 <45.0.0"
```

### Reproducible demo

android/build.gradle
```
buildscript {
    ext {
        buildToolsVersion = "31.0.0-rc1"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.2")

        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            // expo-camera bundles a custom com.google.android:cameraview
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

package.json
```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.3",
    "@tensorflow-models/mobilenet": "^2.1.0",
    "@tensorflow/tfjs": "^3.9.0",
    "@tensorflow/tfjs-react-native": "^0.7.0",
    "@unimodules/core": "^7.1.2",
    "@unimodules/react-native-adapter": "^6.3.9",
    "expo": ">=44.0.0-0 <45.0.0",
    "expo-asset": "^8.4.6",
    "expo-barcode-scanner": "^11.2.1",
    "expo-camera": "^12.0.3",
    "expo-constants": "^13.0.2",
    "expo-file-system": "^13.1.4",
    "expo-gl": "^11.1.2",
    "expo-gl-cpp": "^11.1.1",
    "expo-keep-awake": "^10.0.2",
    "expo-speech": "^10.1.1",
    "jpeg-js": "^0.4.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-fs": "^2.18.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-vector-icons": "^8.1.0",
    "unimodules-app-loader": "^3.0.1"
  },
```

**Comment by byCedric** [comment]
Hi @unit-002! It seems that TensorFlow is using an outdated version of both `expo-gl` and `expo-gl-cpp`. These versions still include unimodules, but that has been deprecated and replaced by expo-modules-core. Using them both likely cause unexpected issues as they are both doing similar tasks internally.

To fix this, TensorFlow has to update their usage of these libraries. You could create a PR to help them upgrade. There is not a lot we can do to fix this issue on our end, unfortunately.

Hope this helps!

**Comment by unit-002** [comment]
> Hi @unit-002! It seems that TensorFlow is using an outdated version of both `expo-gl` and `expo-gl-cpp`. These versions still include unimodules, but that has been deprecated and replaced by expo-modules-core. Using them both likely cause unexpected issues as they are both doing similar tasks internally.
> 
> To fix this, TensorFlow has to update their usage of these libraries. You could create a PR to help them upgrade. There is not a lot we can do to fix this issue on our end, unfortunately.
> 
> Hope this helps!

I see. Thanks a lot.
