### ISSUE TITLE
Improve usefulness of error messages with exp build

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#171]
- [ ] "Cannot read property 'ids' of undefined" when trying to build for android from https://github.com/expo/exp/issues/23

**Comment by brentvatne** [comment]
@skevy - is this issue related? https://github.com/expo/exp/issues/43
if not, can you create an issue on expo/expo to track it with more info?

**Comment by dikaiosune** [comment]
Pretty sure that the error in OP description was fixed ~2 exp releases ago. Still lots of error reporting work to do with standalone builds, but those are all tracked separately AFAICT.
