### ISSUE TITLE
Expo 44 does not set up react-native-reanimated with expo-dev-client

### ISSUE THREAD

**Issue by abumalick** [expo/expo#17102]
### Summary

When setting up react-native reanimated 2.3 with expo-dev-client. I would expect that the android setup from reanimated documentation https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/ is made automatically by expo. I expect this because reanimated is a package supported by the expo app.

However, when I generate the android folder and check the files, the setup is not done. If the setup is not supposed to be done automatically, we should at least add some documentation in https://docs.expo.dev/versions/latest/sdk/reanimated/ and eventually provide an expo plugin.

Here is a related issue: https://github.com/software-mansion/react-native-reanimated/issues/2702#issuecomment-1096282710

PS: I answer `managed` workflow in the following because I believe that using expo dev client is still `managed`. Please tell me if I should change it to `bare`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: bare

### Reproducible demo

Initiate a new project, then, setup expo dev client, add react-native-reanimated and launch the android dev client build:
```
expo install expo-dev-client
expo install react-native-reanimated 
expo run:android
```

Check android folder for setup from https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/

Example repository here: https://github.com/abumalick/expo-reanimated-dev-client

**Comment by abumalick** [comment]
Here is a plugin that adds the required configuration, it was built on top of the gist of https://github.com/software-mansion/react-native-reanimated/issues/2702#issuecomment-1096282710 , I modified it to add proguard rules to the file instead of including a new proguard file.

```ts
/* eslint-disable no-shadow */
import {
  ConfigPlugin,
  createRunOncePlugin,
  withDangerousMod,
  withMainApplication,
} from "@expo/config-plugins";
import fs from "fs";

const pkg = require("../../package.json");

const withReanimated: ConfigPlugin<void> = (config) => {
  config = withMainApplication(config, (config) => {
    if (config.modResults.language === "java") {
      config.modResults.contents = addToMainApp(config.modResults.contents);
    } else {
      throw new Error(
        "Reanimated is only supported for Java Main Application files",
      );
    }
    return config;
  });
  return withProGuardRules(config);
};

function addToMainApp(content: string) {
  const publicClassIndex = content.indexOf(
    "import java.lang.reflect.InvocationTargetException;",
  );
  const getJSMainText =
    '    @Override\n  protected String getJSMainModuleName() {\n    return "index";\n  }';

  content =
    content.substring(0, publicClassIndex - 1) +
    "import com.swmansion.reanimated.ReanimatedJSIModulePackage;\n" +
    content.substring(publicClassIndex - 1);

  content = content.replace(
    getJSMainText,
    getJSMainText +
      `
      \n\t\t@Override
      protected JSIModulePackage getJSIModulePackage() {
        return new ReanimatedJSIModulePackage();
      }`,
  );

  return content;
}

const withProGuardRules: ConfigPlugin<void> = (config) =>
  withDangerousMod(config, [
    "android",
    (config) => {
      const proGuardRulesFilePath = `${config.modRequest.platformProjectRoot}/app/proguard-rules.pro`;
      let fileContents = fs.readFileSync(proGuardRulesFilePath, "utf8");
      fileContents += `
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }`;
      fs.writeFileSync(proGuardRulesFilePath, fileContents, "utf8");
      return config;
    },
  ]);

export default createRunOncePlugin(
  withReanimated,
  `${pkg.name}-withReanimated`,
  pkg.version,
);
```

**Comment by abumalick** [comment]
The plugin should make sure that `jsEngine: "hermes",` is set in the config. It is not present in my snippet and should be added

**Comment by jeff-polls** [comment]
I am also running into this. Thank you for digging into it @abumalick , unfortunately your plugin didn't work for me.

Very frustrating to upgrade to the latest Expo SDK and now I can't use Dev Client. Expo Team will this be fixed by an update to the reanimated plugin?

**Comment by brentvatne** [comment]
@jeff-polls - can you please elaborate on the issue? a minimal reproducible example would be most helpful. i cannot reproduce this. please note also that in the original issue @abumalick left out the reanimated plugin from their babel.config.js, which is likely at least part of their problem
