### ISSUE TITLE
Expo-firebase-analytics: tracking screen view events...

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#17103]
### Summary

I am using the following code to track the Analytics 'screen_view' event:

```

analytics.logEvent("screen_view", {
  screen_name: "Home",
});

```

As it says in the [Expo documentation](https://docs.expo.dev/versions/latest/sdk/firebase-analytics/#analyticssetcurrentscreenscreenname-screenclassoverride), we should use the property 'screen_name'.

In the dashboard of the event (in the UI of the Firebase's console) I am not getting any tracked data (title of the screen, duration of the user inside the screen...) for the screen view event.

I have noticed that, in the [Firebase docs](https://firebase.google.com/docs/analytics/screenviews#web-version-8), it says that we should use the `firebase_screen` property, and not the `screen_name`, as follows:

```

analytics.logEvent("screen_view", {
  firebase_screen: "Home",
});

```

What's the correct way? Also, should I create the custom definition for the 'screen_view' property?

Thank you.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

^44.0.0

### Environment

 expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.4.0 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.5 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3 
      react-native-web: ^0.17.5 => 0.17.5 
    Expo Workflow: managed

### Reproducible demo

This code:

```
export default function App() {
  useEffect(() => {
    const timer = setTimeout(
      () => {
        analytics.logEvent("screen_view", { 
          screen_name: App.name, 
        });
      },
      3000
    );

   return () => timer();
  }, []);

  return <></>;
}
```

**Comment by VictorioMolina** [comment]
It seems its a bug in the documentation (?).

I have been testing the Realtime Dashboard, and using 

analytics.logEvent("screen_view", {
  firebase_screen: "Home",
});

works fine!

In the other hand, `screen_name` doesn't track the screen views!

**Comment by IngyuTae** [comment]
@VictorioMolina Hmm... It seems not solved yet https://github.com/expo/expo/issues/16179

**Comment by moxorama** [comment]
Still  not solved
