### ISSUE TITLE
[expo-branch] Canonical identifier is null every time except in app startup...

### ISSUE THREAD

**Issue by thahermps** [expo/expo#17114]
### Summary

I am facing strange issue. When the app is not yet launched and I am tapping on branch link it is opening the app and I am getting canonical identifier. From this point, as app is already launched, when I am tapping the branch link again I am getting canonical identifier as null doesn't matter I tap various branch links and app is in foreground or background.

I have been chasing the issue more than 2 weeks, tried upgrading expo sdk, tried adding logs and sentry. But none of them got worked. Unable to debug as we can test this in only standalone builds. Awaiting for help from the team now.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

43.0.0

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.5.1 => 8.5.1 
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      expo-cli: 5.3.1
    Expo Workflow: managed

### Reproducible demo

 Branch.subscribe(async bundle => {
      if (bundle && bundle.params && !bundle.error) {
        // `bundle.params` contains all the info about the link.
        let identifier = bundle.params.$canonical_identifier;
        Alert.alert('Branch Link', 'Canonical Identifier:' + identifier);
      }
    });

**Comment by shaikzaffar21** [comment]
Hi @thahermps , I'm also facing the same issue. 
Can anyone know how to handle this?

**Comment by brentvatne** [comment]
we recommend using the official branch library

https://docs.expo.dev/versions/latest/sdk/branch/

> This module will be removed in SDK 46. There will be no replacement that works with the classic build service (expo build) because [the classic build service has been superseded by EAS Build](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60). With EAS Build, you should use the official [react-native-branch](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution) library with [@config-plugins/react-native-branch](https://github.com/expo/config-plugins/tree/master/packages/react-native-branch) instead.
