### ISSUE TITLE
[expo-notifications] Disable push notification reception (local only)

### ISSUE THREAD

**Issue by xD3CODER** [expo/expo#17126]
### Summary

I use the expo-notifications package only to present local notifications to the user.
In parallel I use Onesinal to manage push notifications.
The problem is that expo also displays push notifications, so I get all my push notifications twice.

This behavior is solved if I uninstall `expo-notifications` completely
I can also check if it is a push notification in the `handleNotification` callback of `Notifications.setNotificationHandler` but it works only if the app is in foreground.

Is there a way to disable the reception of push notifications on the `expo-notifications` side ?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.18 - ~/WebstormProjects/app/node_modules/.bin/yarn
      npm: 8.7.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 28, 30, 31
        Build Tools: 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.6 => 44.0.6 
      react: 18.0.0 => 18.0.0 
      react-native: 0.68.0 => 0.68.0 
    npmGlobalPackages:
      eas-cli: 0.50.0
      expo-cli: 5.3.1
    Expo Workflow: bare

### Reproducible demo

Install both `react-native-onesignal` and `expo-notifications` on a bare workflow

**Comment by smn-snkl** [comment]
Have you found a solution? Trying the same thing …

**Comment by andrejpavlovic** [comment]
I imagine we would need to add some native logic to check if the notification is local in before allowing it to proceed to `expo-notifications` or another handler. I think I'm hitting the same issue, but with `react-native-marketingcloudsdk`. Will post here once I figure out a solution.

**Comment by lgrube3** [comment]
Any updates? I'd love to use Expo Notifications for getting the native token and handling permissions but not for displaying notifications on the device.
