### ISSUE TITLE
Crash on Calendar API with createEventAsync function

### ISSUE THREAD

**Issue by SleepyFanjo** [expo/expo#1714]
### Environment

Environment:
  OS: Linux 4.13
  Node: 8.1.2
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: 27.0.0 => 27.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

### Steps to Reproduce

1. Create a new calendar and get its id with `const calId = await Calendar.createCalendarAsync(myCalendar)`
2. This is interpreted as an integer
3. Use this id to add an event to your newly created calendar : `const eventId = await Calendar.createEventAsync(calId, myEvent)`

When the function is called, expo just crashes, not falling into my catch and not letting me know what is wrong.
After some hours of searching, I tried a different approach which works.

1. If first create my calendar, get the id back
2. I reload my calendar list using getCalendarsAsync()
3. And then I find the calendar I just created in the list using a find and a '==' comparison (not '===' as id in the calendar object is a string and id returned by createCalendarAsync is an integer)
4. Finaly I use the id from the calendar object to create my event and it works just fine

So I think, the first thing is that the app crashes if you give an integer as calendarId in createEventAsync, you have to give the id as a string instead.
The second thing is that this should be consistent between the id returned by createCalendarAsync et the id expected for createEventAsync whether it is a string or an integer.

I hope this will help some people who fall on the same problem than me.

**Comment by jesseruder** [comment]
Hi @SleepyFanjo. Can you let us know if this is iOS or Android? Also would be useful to have a Snack of this so that we can test whether it's fixed. Thanks!

**Comment by SleepyFanjo** [comment]
Hi @jesseruder 

Sure thing, here is the snack link : https://snack.expo.io/r1VE6fw6z (just press on synchronize button) to see it crash.

The problem appear on Android, unfortunately I don't have an iOS device at hand to test if it breaks on iOS too.

**Comment by esamelson** [comment]
Hi @SleepyFanjo - sorry for the super slow followup here. We'll try and look into this as soon as we can. Thanks for the report and the repro case.

**Comment by SleepyFanjo** [comment]
Hi @xims,

Yes, that is the problem that I reported, your solution seems much better though. Mine is waaaaaay overkill.
That is not a big deal but I think the type should be consistent between what is returned and what is expected, either it is a string or a number.

**Comment by tsapeta** [comment]
Closing this issue as #3004 should have fixed that but we accidentally didn't close this issue when merging the PR 🙂
