### ISSUE TITLE
EAS build failed at Run gradlew (Execution failed for task ':expo-location:compileDebugJavaWithJavac')

### ISSUE THREAD

**Issue by erliskryeziu** [expo/expo#17155]
### Summary

I am trying to build a development client with expo dev client through eas-cli service, and when building for android platform, my build failed at Run Gredlew phase, as you can see in the photo below. It seems that the problem is expo-location. Any kind of help would be great?

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

    "expo-dev-client": "^0.8.4",
    "expo-updates": "~0.11.6",
    "expo-location": "~14.0.1",

EAS.json file:
{
  "cli": {
    "version": ">= 0.51.0"
  },
  "build": {
    "development": {
      "distribution": "internal",
      "developmentClient": true,
      "android":{
        "gradleCommand":":app:assembleDebug"
      },
      "ios": {
        "buildConfiguration": "Debug"
      }
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

### Environment

Expo CLI 5.2.0 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.51.0
      expo-cli: 5.2.0
    Expo Workflow: bare

### Reproducible demo

FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':expo-location:compileDebugJavaWithJavac'.
[stderr] > Compilation failed; see the compiler error output for details.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 3m 59s

### Stacktrace (if a crash is involved)

<img width="1094" alt="Screen Shot 2022-04-21 at 15 26 18" src="https://user-images.githubusercontent.com/48479325/164468719-9b617459-d023-4e5b-a8be-323d0325cad4.png">

**Comment by PaddyLock** [comment]
I'm getting a similar error when running

eas build -p android --profile preview

on a managed workflow

<img width="1172" alt="Screenshot 2022-05-11 at 14 55 49" src="https://user-images.githubusercontent.com/539158/167867516-ddc3b689-f75e-4e95-94e1-938298b9c739.png">

**Comment by alexander01202** [comment]
Anyone solved this yet?

**Comment by newme616** [comment]
same problem after upgrading to SDK 46

**Comment by hocineismail** [comment]
the biggest mistake i made, i used expo for my project, what the hell is going with expo, one month before i was able to build my project but not now , i think i have to use react-native without this sh*t,

**Comment by trentmercer** [comment]
having this issue as well

**Comment by keith-kurak** [comment]
Hi! Based on the information provided, we tried to reproduce under Expo 46 with the provided eas.json and specified packages installed, but did not see the error (or any other). If you can create a minimal reproduction as a github repo that we can download try building, feel free to reopen under a new issue. Thank you!
