### ISSUE TITLE
expo-file-system uploadAsync multiple bugs

### ISSUE THREAD

**Issue by siddharth-kt** [expo/expo#17169]
### Summary

There are 2 issues associated with uploadAsync() parameters. (as in below code.)
1) On passing any null value (like "id: null" passed in below code) in parameters, it gives error.
    [Error: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference]
2) On passing any number value (like "number: 3" passed in below code) in parameters.
    It is passed as integer/number but in backend it comes out like "3.0" (string + float).

NOTE :
1) Below code is referenced from : https://github.com/expo/expo/pull/13318.
2) Its not documented in actual FileSystem docs. Kindly do this also.
3) Also see : https://expo.canny.io/feature-requests/p/callback-support-for-filesystemuploadasync

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    Expo Workflow: managed

### Reproducible demo

 const task = FileSystem.createUploadTask(
  'http://192.168.0.136:3000/binary-upload',
  asset.localUri,
{
    uploadType: FileSystem.FileSystemUploadType.MULTIPART,
    fieldName: "file",
    parameters: {
        id: null,
       number: 3
    },
  },
  data => {
    console.log({ data });
  }
);

task.uploadAsync().then(x => {
  console.log({ x });
});

**Comment by hirbod** [comment]
Parameters have to be strings.

**Comment by siddharth-kt** [comment]
Yeah, @hirbod thanks 👍
