### ISSUE TITLE
App frozen in dev mode - monorepo

### ISSUE THREAD

**Issue by b-steel** [expo/expo#17167]
### Summary

Setup a demo project exactly the same as the one outlined in [Working with Monorepos](https://docs.expo.dev/guides/monorepos/). Running `yarn workspace cool-app start` will start the app and the page looks as expected.  
If you run `yarn workspace cool-app add uuid` then start the app (same method as before) the app is stuck on the splash screen. However if you turn on "debug remote JS" then the app works as intended. Running in production mode also works fine.

Seems to be similar to [#15035](https://github.com/expo/expo/issues/15035)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

 expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.49.0
      expo-cli: 5.3.2
    Expo Workflow: managed

### Reproducible demo

[github](https://github.com/b-steel/expo-monorepo-uuid)

**Comment by b-steel** [comment]
@wcastand Update: I upgraded expo to SDK 45 and things seem to work now

**Comment by wcastand** [comment]
i update the expo go app and it was fine yeah, i can't update to sdk. 45 yet since lottie-react-view doesn't work. but thanks for keeping me update ! :)
