### ISSUE TITLE
Local png images are not showing in TestFlight

### ISSUE THREAD

**Issue by Michaelrecycle** [expo/expo#17175]
### Summary

Similar to this issue https://github.com/facebook/react-native/issues/31525,  my local png images are not showing up in testflight but do in dev. I used eas build and eas submit. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo

`<Image source={props.image} style={styles.image} />`
and 
`<Component  image={require("../../assets/avatar-circle.png")}`

**Comment by conoremclaughlin** [comment]
Having the same issue. Local images aren't loading in TestFlight via `eas build` or in `expo run:ios --configuration Release`.

**Comment by conoremclaughlin** [comment]
FYI @Michaelrecycle and anyone else who encounters this issue, the documentation says the expo metro config is extended when run through the expo cli, but that looks like that's not the case for `--configuration Release` builds, like what is used in `eas build` when submitting to TestFlight. Our metro config was operating under this assumption so we fixed this by extending the expo/metro config and returning the full config instead of only a partial:
```
const { getDefaultConfig } = require('expo/metro-config');
const defaultConfig = getDefaultConfig(__dirname);

defaultConfig.resolver.sourceExts = [
  ...defaultConfig.resolver.sourceExts,
  'cjs',
];
module.exports = defaultConfig;
```

**Comment by araymond11** [comment]
A big thanks to @conoremclaughlin ! Your solution works perfectly.

**Comment by josefnorlin** [comment]
> Having the same issue. Local images aren't loading in TestFlight via `eas build` or in `expo run:ios --configuration Release`.

This is also true for production builds.

This solution should come as standard on first install.
