### ISSUE TITLE
Для жителей России, столкнувшимися с блокировками РКН // For all Russian users

### ISSUE THREAD

**Issue by p0liper** [expo/expo#1717]
Hello to all.
Due to unlawful RKN blocks, I started a transparent proxy server for exp.host and expo.io.
This server **is not, was not and will not** collect your data (this server is a just transparent proxy).
You should modify your /etc/hosts (%windir%\system32\drivers\etc\hosts) file, appending that:
```
185.28.103.178 exp.host
185.28.103.178 expo.io
```

===
Привет всем.
Ввиду незаконной блокировки ресурса Роскомнадзором, я запустил свой транспарентный сервер для проектов exp.host и expo.io.
Данный сервер **не собирает, не собирал и не будет собирать** Ваши данные (этот сервер является всего лишь прозрачным прокси сервером, который подтвержден SSL сертификатом exp.host и expo.io)
Вы должны отредактировать Ваш файл /etc/hosts (%windir%\system32\drivers\etc\hosts), путем добавления следующих строк:
```
185.28.103.178 exp.host
185.28.103.178 expo.io
```

Спасибо за внимание!

**Comment by yanislavb** [comment]
![image](https://user-images.githubusercontent.com/9640308/39589073-a4147d52-4f16-11e8-8eaa-a7c25921c28f.png)
![image](https://user-images.githubusercontent.com/9640308/39589120-b9ebe8d6-4f16-11e8-8843-e5773bded520.png)

Доказательства "прозрачности" прокси сервера и сайта

**Comment by p0liper** [comment]
И да, если какие то узлы заблокированы, Вы можете написать об этом в специальном issue, и эти узлы будут туннелированы:
https://github.com/p0liper/unrkn/issues/1
