### ISSUE TITLE
[docs] [expo-location] Missing documentation about LocationAccuracy & Permissions

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#17183]
### Summary

In https://docs.expo.dev/versions/latest/sdk/location, there is some documentation about Permissions and Usage, but there is something important missing:

I don't know when to use COARSE, and when to use FINE location.

In my code I have:
```
Location.getCurrentPositionAsync({
  accuracy: Location.LocationAccuracy.Balanced,
}
```

I don't know if my permissions should be this:
```
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION"
      ],
```

or this

```
      "permissions": [
        "ACCESS_COARSE_LOCATION"
      ],
```

If you check this: `expo-location/build/Location.types.d.ts`, you will see:
```
/**
 * Enum with available location accuracies.
 */
export declare enum LocationAccuracy {
    /**
     * Accurate to the nearest three kilometers.
     */
    Lowest = 1,
    /**
     * Accurate to the nearest kilometer.
     */
    Low = 2,
    /**
     * Accurate to within one hundred meters.
     */
    Balanced = 3,
    /**
     * Accurate to within ten meters of the desired target.
     */
    High = 4,
    /**
     * The best level of accuracy available.
     */
    Highest = 5,
    /**
     * The highest possible accuracy that uses additional sensor data to facilitate navigation apps.
     */
    BestForNavigation = 6
}
```

But... It's not clear WHEN I have to add the `_FINE_` permission. Is it necessary for `BestForNavigation`? for `Highest`? for `High`? Maybe I'm adding `_FINE_` and I don't really need it.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/location

### Anything else?

Love you all

**Comment by BrodaNoel** [comment]
👾

**Comment by amandeepmittal** [comment]
Hey @BrodaNoel, Android docs [here](https://developer.android.com/training/location/permissions#foreground) only specify using  FINE when the app requires very precise location access. Expo module `expo-location` adds all three permissions (COARSE, FINE, FORGROUND_SERVICE) automatically for each Expo project for similar reasons.

**Comment by BrodaNoel** [comment]
It's not o my important to specify how to remove the FINE, but also to explain WHEN to use those all different values.

For me, there is just no difference between them.

**Comment by BrodaNoel** [comment]
If I use in my code: LocationAccuracy.Lowest, what's the permission I should add? (And so on for all the LocationAccuracy enum values)
