### ISSUE TITLE
Masking phone number using *67 code not working on iOS.

### ISSUE THREAD

**Issue by vinayn-mend** [expo/expo#17199]
### Do you understand that any Expo CLI issues opened in the core Expo repository will be closed?

Yes

**Comment by wodin** [comment]
This looks like something that Apple disallows:

## [Phone Links](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html):
> To prevent users from maliciously redirecting phone calls or changing the behavior of a phone or account, the Phone app supports most, but not all, of the special characters in the tel scheme. Specifically, if a URL contains the * or # characters, the Phone app does not attempt to dial the corresponding phone number.
