### ISSUE TITLE
[docs] expo modules setup with react-native v0.68.1

### ISSUE THREAD

**Issue by uloco** [expo/expo#17192]
### Summary

The expo modules setup docs refer to `AppDelegate.m` but react-native version 0.68.1 changed this to `AppDelegate.mm` and the references in the docs are not the same in the current version. How do we use expo modules with react-native 0.68.1?

### Link to the related docs page

https://docs.expo.dev/bare/installing-expo-modules/

### Anything else?

Even if the docs page is outdated, is there currently a non documented way to do this? Since I am in the middle of the react-native update already I don't want to revert all changes I made so far.

**Comment by hirbod** [comment]
This did also break a config-plugin of mine, which tried to change some values with regexp. 
Is there a way to change Swift Delegate files now?

**Comment by vkozinec** [comment]
Same problem here, we are trying with react 0.68.1 and expo is failing. We are using biometrics from expo.

**Comment by uloco** [comment]
I found out as a workaround you can setup a new app with expo-cli or upgrade an existing react-native init app to the latest beta of `expo@45.0.0-beta.9` and apply those changes from AppDelegate.mm and other java files one by one.

**Comment by KrisLau** [comment]
Not sure if this was added after your post but for anyone looking at this now there are instructions for the AppDelegate.mm now in https://docs.expo.dev/bare/installing-expo-modules/#manual-installation

**Comment by uloco** [comment]
Great then I think we can close this.  @KrisLau Thanks for pointing out.
