### ISSUE TITLE
launchImageLibraryAsync doesn't open despite status 'granted'

### ISSUE THREAD

**Issue by FreakTheMighty** [expo/expo#1720]
### Environment

$ exp diagnostics
14:40:36 [exp] Generating diagnostics report...
14:40:36 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.6.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.1 => 25.0.1
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/gishdeveloper-6f46979a-ebe8-4a6d-9c29-7bfc78758515.tar.gz

iOS, Expo Client and Standalone

### Steps to Reproduce

Broken: https://snack.expo.io/@freakthemighty/photo-permissions-new-25
Working: https://snack.expo.io/@freakthemighty/photo-permission-issues

Using New SDK 25
1. Using the first Snack
1. Tap "Get Photo"
1. Deny permission request
1. Got to app settings
1. Enable photo permissions
1. Return to the snack, tap "Get Photo"
1. Notice the status is "granted", but no gallery opens

### Expected Behavior

Once permissions have been granted the gallery should open

### Actual Behavior

The permission status is "granted", but no gallery opens

### Reproducible Demo

Broken: https://snack.expo.io/@freakthemighty/photo-permissions-new-25
Working: https://snack.expo.io/@freakthemighty/photo-permission-issues

**Comment by FreakTheMighty** [comment]
Also worth mentioning, when I push this to our TestFlight build it fails silently, but I can't tell exactly what's going on there.

**Comment by schazers** [comment]
possibly related: https://forums.expo.io/t/when-i-try-to-use-image-picker-in-the-expo-client-i-get-unhandled-promise-rejection-error-user-rejected-permissions/9526/5

**Comment by aalices** [comment]
SDK 25 will be fixed probably this week, sorry all for the bug! Any other version should work just ok
