### ISSUE TITLE
EAS build failed with "Could not find 'bundler'" on ios

### ISSUE THREAD

**Issue by hi-paul** [expo/expo#17213]
### Summary

Until yesterday, it worked with the same source code but today eas build failed on ios

<img width="1125" alt="무제 2" src="https://user-images.githubusercontent.com/43771519/165260972-7a9ac003-02d7-45ff-a1d4-cbd192653d15.png">
.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.21
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.37.0
      expo-cli: 4.12.10
    Expo Workflow: managed

### Reproducible demo

EAS build ID that fails is `1e3df02d-ca6f-4128-bc8c-735c615c2622`.

**eas.json**
<img width="517" alt="무제" src="https://user-images.githubusercontent.com/43771519/165261542-112b7b3c-cd6c-4ee1-89b9-ca4ccedd99c8.png">

**Comment by hi-paul** [comment]
EAS build works after deleting gemfile.lock file in project root. I am using fastlane in circleCI. Do I have to delete gemfile.lock?

**Comment by wildseansy** [comment]
I have the same issue.  I even had  `"bundler"` version defined in the [eas.json](https://docs.expo.dev/build-reference/eas-json/#bundler), but EAS build still says that the version specified is not defined.  When I print out `bundle --version` it prints out the correct version number on the EAS build server
