### ISSUE TITLE
(iOS)  Expo hosted app does not get push notifications token

### ISSUE THREAD

**Issue by KevinColemanInc** [expo/expo#1722]
# Problem

My [snack](https://snack.expo.io/ry1oaL2pG) is not able to show me the notification.  It gets stuck in `Notifications.getExponentPushTokenAsync()`.
  
### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.11.1
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: Not Found
  react: Not Found
  react-native: Not Found

Target:
iOS 11.3.1
iPhone X

### Steps to Reproduce

1. Open expo app on iPhone X; iOS 11.3.1
2. Select the Snack from the projects menu.

### Expected Behavior

It should display the notifications token.

### Actual Behavior

![image](https://user-images.githubusercontent.com/2381771/39672621-f999a9ee-5157-11e8-999d-8139075aa976.png)

**Comment by ide** [comment]
Have you tried getExpoPushTokenAsync? The other method is deprecated and maybe removed. You must also have permission to show notifs before getting a token.

**Comment by KevinColemanInc** [comment]
Solve! thanks
