### ISSUE TITLE
expo detached app ios build failed with react-native-onesignal

### ISSUE THREAD

**Issue by proguru58** [expo/expo#1725]
I have followed the instructions for React Naive SDK setup for react-native-onesignal and got the following error message in compiling ios building in my expo detached xcode project.

/React/Core/Base/RCTConvert.h:13:9: 'React/RCTAnimationType.h' file not found

**Comment by AdamJNavarro** [comment]
Hey @proguru58,

If the react-native-onesignal doesn't have a podspec file, you'll want to follow these instructions. https://docs.expo.io/versions/v27.0.0/expokit/expokit#if-the-library-doesnt-support-cocoapods-react-native Hopefully that will help you successfully build.

Cheers,

Adam

**Comment by lulzimfazlija** [comment]
I am having exact problem as @proguru58 , did anyone solved this? Have you @proguru58? I am using react native 0.54 and "react-native-onesignal": "^3.1.4".

@AdamJNavarro I don't think we should be using cocoa pods at all for OneSignal, I heard it should work without specifying into pod file... not quite sure!

**Comment by proguru58** [comment]
@AdamJNavarro @lulzimfazlija 

I have solved this problem by upgrading react-native-onesignal to 3.2.1

The package has podspec file. You can link native module through pod install.
