### ISSUE TITLE
Expo Face Detection doesnt work well in landscape mode

### ISSUE THREAD

**Issue by alexnguyen98** [expo/expo#17250]
### Summary

When testing expo face detection on portrait mode it was working well, until when tried on landscape mode it didnt work consistently that well.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 8.3.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

### Reproducible demo

```
import React, { useState, useRef } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Camera, FaceDetectionResult } from 'expo-camera';
import { Face } from 'expo-camera/build/Camera.types';
import * as FaceDetector from 'expo-face-detector';
import { usePermission } from '../../hooks/usePermission';

const faceDetectorSettings = {
  mode: FaceDetector.FaceDetectorMode.accurate,
  detectLandmarks: FaceDetector.FaceDetectorLandmarks.none,
  runClassifications: FaceDetector.FaceDetectorClassifications.none,
  minDetectionInterval: 1000,
};

const styles = StyleSheet.create({
  camera: {
    flex: 1,
  },
  buttonContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    flexDirection: 'row',
  },
  button: {
    padding: 10,
    backgroundColor: 'black',
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  text: {
    fontSize: 18,
    color: 'white',
  },
});

type Props = {
  cameraDirection: 'front' | 'back';
  active: boolean;
};

export const FaceCamera: React.FC<Props> = ({ cameraDirection, active }) => {
  const [faceRes, setFaceRes] = useState<Face | null>(null);
  const ref = useRef<Camera>(null);

  const { hasPermission } = usePermission();

  const handleFacesDetected = (result: FaceDetectionResult) => {
    const data = result.faces[0];
    setFaceRes(data);
    console.log('face');
  };

  const boxStyle = {
    width: faceRes?.bounds.size.width,
    height: faceRes?.bounds.size.height,
    left: faceRes?.bounds.origin.x,
    top: faceRes?.bounds.origin.y,
    position: 'absolute',
    borderColor: 'blue',
    borderWidth: 1,
  };

  if (hasPermission === null) {
    return <View />;
  }

  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }

  return (
    <Camera
      ref={ref}
      type={cameraDirection}
      onFacesDetected={active ? handleFacesDetected : undefined}
      faceDetectorSettings={faceDetectorSettings}
      autoFocus={Camera.Constants.AutoFocus.on}
      style={styles.camera}
    >
      <View style={styles.buttonContainer}>{faceRes && <View style={boxStyle as any}></View>}</View>
    </Camera>
  );
};

```

**Comment by LuizHGodoy** [comment]
same behavior testing on ipad mini 2

**Comment by rahuldasgupta** [comment]
same issue on Android, the faces count is inncorrect on landscape (although works perfectly on portrait)

**Comment by claitonlovato** [comment]
Hi, Is there any updates on this issue? I am having pretty much the same behaviour as this thread, detector works well in Android and iOS in Portrait mode, but iOS in Landscape doesnt work well. Would be nice to have an update if anyone found a workaround or solution
