### ISSUE TITLE
Expo SDK 45 Beta-8 [ios] - Crash and bricked app when toggled "local dev tools"

### ISSUE THREAD

**Issue by hirbod** [expo/expo#17263]
### Summary

After upgrading to Expo SDK 45, I toggled the "local dev tools" switch and my app instantly bricked. No restart, nothing helps, only deleting and reinstalling.

![IMG_9009](https://user-images.githubusercontent.com/504909/165820296-d5229d5f-b20c-4055-a632-033df4874e0a.PNG)

SDK 45 Beta 8, custom dev client

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45 Beta.8

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.1 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/opt/node@14/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.51.0
      expo-cli: 5.4.3
    Expo Workflow: bare
```

### Reproducible demo

Not yet

**Comment by ajsmth** [comment]
thanks for this - we have a PR that might end up solving this https://github.com/expo/expo/pull/17248 @lukmccall

**Comment by hirbod** [comment]
@ajsmth you're welcome. While you guys are at this:
My app ALWAYS reconnects to metro and reloads when I shake the device or use the 3 finger gesture to open the dev-menu in custom dev client (since SDK 44 and iOS only). Is this related? This reload does also cause expo-notifications and mmkv/jsi-helper crash.

This is not happening on Android. It is pretty annoying.

**Comment by hirbod** [comment]
I will check that on the simulator later. I've send you a video meanwhile via Twitter DM because I can't share it here. 

I will report back soon.

**Comment by lukmccall** [comment]
Hi @hirbod, my PR will resolve the app crashes problem on iOS. I don't know about the reconnect problem, but it didn't occur in my tests.

**Comment by hirbod** [comment]
@lukmccall @ajsmth we've been able to reproduce the bug with a fresh project in custom-dev-client. It is just enough to enable Hermes. As soon as Hermes is activated, the issues arise (always reloading the App when the dev-menu slides up the first time).

As long we don't use expo-notifications or mmkv/jsi-helper, the app just reloads and works - but when we use one of these packages, it causes a crash since something weird with the bridge is going on. Repro is coming. I will create a new ticket.

**Comment by lukmccall** [comment]
The issue with remote debugging was fixed by https://github.com/expo/expo/pull/17248.
