### ISSUE TITLE
Device And Expo Server Not In The Same LAN

### ISSUE THREAD

**Issue by kirkcola** [expo/expo#1726]
Hey,

My development enviroment is connected to several LANs,

but my cellphone and my laptop are not in the same network,

how can I decide which LAN expo listens but not using tunnel?

Thanks!

**Comment by ide** [comment]
Do any of the approaches here work for you? https://github.com/react-community/create-react-native-app/issues/60#issuecomment-287081523

**Comment by kirkcola** [comment]
@ide Thanks! It works! 😃
