### ISSUE TITLE
expo-local-authentication does not work for Samsung PIN

### ISSUE THREAD

**Issue by CKalnasy** [expo/expo#17262]
### Summary

PIN authentication on Samsung devices does not work, `authenticateAsync`'s promise is never resolved.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/mobile/node_modules/.bin/yarn
      npm: 6.14.7 - ~/mobile/node_modules/.bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.56 => 0.1.84
      babel-preset-expo: 8.5.1 => 8.5.1
      expo: ^43.0.0 => 43.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.50.0
      expo-cli: 5.4.2
    Expo Workflow: bare

### Reproducible demo

100% reproducible on Samsung note 10+ running Android 9. I think most Samsung devices should all have the same problem.

1. Setup a PIN on device
2. Attempt to authenticate device calling `await authenticateAsync()`
3. Enter PIN code
4. UI for entering PIN is dismissed
5. Promise is never resolved and app hangs on the await

What I'm seeing is that when [LocalAuthenticationModule's](https://github.com/expo/expo/blob/main/packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt#L248-L256) onActivityResult function is called, we are calling onActivityResult on the biometric fragment but the requestCode doesn't match what the biometric fragment expects so it ignores our function call.
Here's BiometricFragment.java's onActivityResult function

```
public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (requestCode == REQUEST_CONFIRM_CREDENTIAL) {
        mViewModel.setConfirmingDeviceCredential(false);
        handleConfirmCredentialResult(resultCode);
    }
}
```

In LocalAuthenticationModule.java we get passed what seems like a random value for requestCode as it never was the same for me. If I hardcode requestCode to 1 (REQUEST_CONFIRM_CREDENTIAL) then this works as expected

**Comment by Erin69** [comment]
on LocalAuthentication.authenticateAsync() call, promise is hanging in the background in case if user clicks "CANCEL" in "verified. Tap confirm to continue" step, it should be resolved and handled.

**Comment by bbarthec** [comment]
I've tried to reproduce the problem, but with no luck (I was using `Samsung J3` running `Android 9`)
I've used following steps:
1. `expo init 17262-local-authentication-samsung-android-9 --template blank@sdk-43` && `cd 17262-local-authentication-samsung-android-9`
2. Used following app code (also available [on snack](https://snack.expo.dev/@bbarthec/localauthentication-demo)):
<details>
<summary>See app code</summary>

```jsx
import * as React from "react";
import { Text, View, StyleSheet, Button, Alert } from "react-native";
import * as LocalAuthentication from "expo-local-authentication";
import * as Device from 'expo-device';

export default () => {
  const login = React.useCallback(async () => {
    try {
      let results = await LocalAuthentication.authenticateAsync();
      if (results.success) {
        Alert.alert("alert", "login success");
      } else {
        Alert.alert("alert", JSON.stringify(results));
      }
      // LocalAuthentication.cancelAuthenticate();
    } catch (err) {
      Alert.alert("alert", "login fail: " + err);
      console.log(err);
    }
  }, []);

  return (
    <View style={styles.container}>
      <Text>Device brand: {Device.brand}</Text>
      <Text>Device model name: {Device.modelName} ({Device.productName})</Text>
      <Text>Android version: {Device.osVersion} (API {Device.platformApiLevel})</Text>
      <Button title="login" onPress={login}></Button>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
    padding: 8,
  },
});

```
</details>

3. `expo start`
4. Used the `Expo Go` freshly installed from `Play Store`
5. See results:
<video src="https://user-images.githubusercontent.com/16623003/169506019-46f5595a-0607-482d-97cb-e9cc4c3fa651.mov" />

**Comment by bbarthec** [comment]
@CKalnasy as you're referring to the native code could you possibly be hitting this error in standalone app that is built using Expo classic build services?
