### ISSUE TITLE
SDK45: Unable to resolve module uuid/v5 in expo go

### ISSUE THREAD

**Issue by ramiel1999** [expo/expo#17261]
### Summary

Initializing a new sdk45 beta project and using "uuid" in expo go throws the following error
```
iOS Bundling failed 1021ms
Unable to resolve module uuid/v5 from {file paths}/node_modules\expo\build\environment\getInstallationIdAsync.js: uuid/v5 could not be found within the project or in these directories:
  node_modules\expo\node_modules
  node_modules
  1 | import * as Application from 'expo-application';
> 2 | import uuidv5 from 'uuid/v5';
    |                     ^
  3 | let installationId;
  4 | const UUID_NAMESPACE = '29cc8a0d-747c-5f85-9ff9-f2f16636d963'; // uuidv5(0, "expo")
  5 | export default async function getInstallationIdAsync() {
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~45.0.0-beta.4 => 45.0.0-beta.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.1 => 0.68.1
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/ramiel1999/expo-sdk45-uuid

**Comment by mlecoq** [comment]
The following patch can be used as a workaround 

```
diff --git a/node_modules/expo/build/environment/getInstallationIdAsync.js b/node_modules/expo/build/environment/getInstallationIdAsync.js
index 75366e4..32ed319 100644
--- a/node_modules/expo/build/environment/getInstallationIdAsync.js
+++ b/node_modules/expo/build/environment/getInstallationIdAsync.js
@@ -1,5 +1,5 @@
 import * as Application from 'expo-application';
-import uuidv5 from 'uuid/v5';
+import {v5 as uuidv5} from 'uuid';
 let installationId;
 const UUID_NAMESPACE = '29cc8a0d-747c-5f85-9ff9-f2f16636d963'; // uuidv5(0, "expo")
 export default async function getInstallationIdAsync() {
```

**Comment by brentvatne** [comment]
fixed in `expo@45.0.0-beta.9`

**Comment by brentvatne** [comment]
found another issue related to uuid usage, created an issue here https://github.com/expo/expo/issues/17270

**Comment by trevorallred** [comment]
For anyone who runs into this same problem, I got this exact error in a yarn monorepo where another package had included uuid version 8.3.2. Removing that solved the issue.

**Comment by davidzech27** [comment]
I discovered that by removing another package in the monorepo which had uuid as a dependency, the issue went away. However, removing uuid in that package wasn't an option. The only thing that has solved the issue has been setting config.resolver.disableHierarchicalLookup to false in metro.config.js, going against [what is recommended in the docs](https://docs.expo.dev/guides/monorepos/#modify-the-metro-config). Still looking for a better solution, if anyone has one.

**Comment by IAmNatch** [comment]
> The only thing that has solved the issue has been setting config.resolver.disableHierarchicalLookup to false in metro.config.js

I had this same issue and resolved it by instead making sure that my other app using UUID shared the same version as the expo required in it's package.json.

**Comment by chen-rn** [comment]
> I discovered that by removing another package in the monorepo which had uuid as a dependency, the issue went away. However, removing uuid in that package wasn't an option. The only thing that has solved the issue has been setting `config.resolver.disableHierarchicalLookup` to false in `metro.config.js`, going against [what is recommended in the docs](https://docs.expo.dev/guides/monorepos/#modify-the-metro-config). Still looking for a better solution, if anyone has one.

What are the negative consequences of setting HierarchicalLookup to false?

Also, curious if you found a better solution to this!

**Comment by chen-rn** [comment]
I'm running a yarn 3 monorepo.
Another fix that I found to this is to add  ` "uuid": "^3.4.0"` into your root package.json's resolution.

![Screenshot 2023-01-28 at 8 38 11 PM](https://user-images.githubusercontent.com/36214945/215305195-2afccb01-dc02-4eaf-815a-8f689969d16f.png)

**Comment by dslounge** [comment]
I ran into the same issue and ended up here. I managed to solve it for myself, but I don't understand the root cause of the problem. I'm also on a yarn workspaces monorepo.

the expo package requires `"uuid": "3.4.0"`, but for some reason, the npm install doesn't install that version. `react-scripts` from my web project (same monorepo) requires a higher version, and I think because all the sub dependencies go into the root project's `node_modules`, `3.4.0` gets clobbered by anything else in the system. You can take a look by running `npm list uuid`.

My fix was just to add  `"uuid": "3.4.0"` to my expo project's package.json. That makes sure it's at least installed in the mobile `node_modules` (not `../node_modules`), and metro will find it there. Hope that makes sense.

**Comment by chen-rn** [comment]
yea that might be a better idea than putting it in the root resolution!

**Comment by grabbou** [comment]
I just run into it too and can confirm that listing `uuid` 3.4.0 fixes the issue. Probably related to some deduplication in a workspace where packages get hoisted. 

@brentvatne would be great to document/fix in the upcoming release, I guess this may come particularly common for those transitioning to a monorepo.

**Comment by grabbou** [comment]
I just run into it too and can confirm that listing `uuid` 3.4.0 fixes the issue. Probably related to some deduplication in a workspace where packages get hoisted.

**Comment by ScreamZ** [comment]
Can't wait for pnpm support in mono-repo

**Comment by qhhonx** [comment]
I tried to run [spacedrive mobile-app](https://github.com/spacedriveapp/spacedrive/blob/main/CONTRIBUTING.md#mobile-app) but got issue like here posted.
- For ios, I got `Unable to resolve "uuid/v5" from "../../node_modules/expo/build/environment/getInstallationIdAsync.js"`

- For android, I got `Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported, js engine: hermes`

Tried some actions by above posted:

> setting `config.resolver.disableHierarchicalLookup` to false in `metro.config.js`

By "setting config.resolver.disableHierarchicalLookup to false in metro.config.js" **works for me**.

> Another fix that I found to this is to add ` "uuid": "^3.4.0"` into your root package.json's resolution.

By "adding ` "uuid": "^3.4.0"` into your root package.json's resolution" did not fix for me.



> My fix was just to add `"uuid": "3.4.0"` to my expo project's package.json.

By "adding ` "uuid": "^3.4.0"` to my expo project's package.json" did not fix for me.

**Comment by morten-olsen** [comment]
Adding an override into the root `package.json` did it for me (Though may cause other problems for anything that depends on a different version

```
  "pnpm": {
    "overrides": {
      "uuid": "3.4.0"
    }
  },
```

**Comment by TroyDL** [comment]
Really seems like this should be reopened if people are still experiencing it?  (hint: I am)  Trying to upgrade my app's expo version to 49 is causing it for me.

**Comment by Wander95** [comment]
I was experiencing the same issue following the expo documentation and using version 49, what actually did work was setting

```javascript
config.resolver.disableHierarchicalLookup = false
```

Mentioned in

> config.resolver.disableHierarchicalLookup

**Comment by juanevp** [comment]
In a monorepo using yarn classic I had to add in the root package.json:
```json
  "resolutions": {
    "expo/uuid": "3.4.0"
  }
```
to force (only) expo to use the old version of uuid. And in metro.config.js:
```
config.resolver.disableHierarchicalLookup = false
```
Only then metro considered the node_modules directory inside the expo package for the uuid resolution.

**Comment by jimmynguyen1308** [comment]
Just encountered this issue (again) in Expo version 49.

Although i am pretty sure this is case-by-case issue at this point, I fixed this by "downgrading" Expo to v49.0.0 (my last version was 49.0.6)

Don't know what is cooking here but hope it helps

**Comment by ddehghan** [comment]
in a yarn monorepo i had to set this:

  config.resolver.disableHierarchicalLookup = false;

contrary to the docs which says this should be set to true.

**Comment by maks-io** [comment]
> Adding an override into the root `package.json` did it for me (Though may cause other problems for anything that depends on a different version
> 
> ```
>   "pnpm": {
>     "overrides": {
>       "uuid": "3.4.0"
>     }
>   },
> ```

I can confirm this also works for me, in a pnpm monorepo, with expo version `49.0.18`.
