### ISSUE TITLE
Expo Updates checkForUpdateAsync resolves isAvailable: no for Bare Workflow

### ISSUE THREAD

**Issue by dereknelson** [expo/expo#17267]
### Summary
The issue has to do with [these lines in this file](https://github.com/expo/expo/blob/master/packages/expo-updates/ios/EXUpdates/SelectionPolicy/EXUpdatesLoaderSelectionPolicyFilterAware.m#L10-L28).

I followed the bare configuration for expo-updates. the config results in EXUpdates finding the remote bundle when running in Release mode.

![image](https://user-images.githubusercontent.com/6868432/165845229-6bac130b-1a0a-471f-9505-85622ee8dda6.png)

at top level invocation, newUpdate and launchedUpdate exist (notably the manifest, commitTime, bundleUrl do as well).
![image](https://user-images.githubusercontent.com/6868432/165846346-fc184e2b-958b-487e-b3ab-2713daae722a.png)

step over function execution one time, it becomes nil.
![image](https://user-images.githubusercontent.com/6868432/165845068-6ba5737e-f51a-4eee-b135-019775503f15.png)

this eventually results in line 28
```return [launchedUpdate.commitTime compare:newUpdate.commitTime] == NSOrderedAscending``` 
evaluating false as they are both nil. checkForUpdateAsync resolves with `{ isAvailable: no }`
additionally, Updates.manifest is an empty object.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.1.1 - ~/.nvm/versions/node/v14.15.1/bin/npm
      Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.66.3 => 0.66.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.4.3
    Expo Workflow: bare

### Reproducible demo
https://github.com/dereknelson/expo-ota-repro

**Comment by dereknelson** [comment]
@esamelson hey, noticed you were the contributor of EXUpdatesLoaderSelectionPolicyFilterAware.m - just sanity checking, is there something strange going on with pointers here after the file was split?

**Comment by brentvatne** [comment]
@dereknelson - can you possibly share a reproducible example that we can clone and run?

**Comment by dereknelson** [comment]
@brentvatne working on it, will follow up with that tomorrow

**Comment by dereknelson** [comment]
@brentvatne added repro

**Comment by dereknelson** [comment]
not sure what changed but it works now. if i had to guess it was a little rm, a little -rf and some node_modules
