### ISSUE TITLE
Regression in support for react-native-get-random-values

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#17270]
### Summary

react-native-get-random-values uses `NativeModules.ExpoRandom.getRandomBase64String(byteLength)` to polyfill `crypto.getRandomValues()` in Expo Go:

https://github.com/LinusU/react-native-get-random-values/blob/455f9dbbedad370c094090615b4c88031a09191b/index.js#L26-L34

In converting `expo-random` to use JSI, we break this polyfill. We should fix this because it is documented in the extremely popular [`uuid` package](https://www.npmjs.com/package/uuid).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2022.01.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        Android NDK: 21.0.6113669
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0-beta.9 => 45.0.0-beta.9
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.1 => 0.68.1
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.50.0
      expo-cli: 5.4.2
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/brentvatne/secure-random-example-45

**Comment by brentvatne** [comment]
Note: you can work around this right now by using `expo-standard-web-crypto` instead of `react-native-get-random-values`:

```
expo install expo-random expo-standard-web-crypto
```

```js
import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View } from "react-native";
import { v4 } from "uuid";
import { polyfillWebCrypto } from "expo-standard-web-crypto";

polyfillWebCrypto();

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <Text>{v4()}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

**Comment by hirbod** [comment]
@brentvatne should I make a PR in the uuid Repo and add a section for SDK 45+ using the "new method" with `polyfillWebCrypto`?

**Comment by hirbod** [comment]
I submitted a PR:
https://github.com/uuidjs/uuid/pull/627/files

**Comment by hirbod** [comment]
As I understand it, from Expo SDK45 it makes more sense to use the modules directly from Expo. Of course, I could be wrong.

**Comment by brentvatne** [comment]
@ramiel1999 - it is a good solution, i'd recommend it

**Comment by LinusU** [comment]
Thanks for the PR! This is fixed in the following release of `react-native-get-random-values`:

[🚢 1.8.0 / 2022-05-02](https://github.com/LinusU/react-native-get-random-values/releases/tag/v1.8.0)

**Comment by brentvatne** [comment]
bumped the version of `react-native-get-random-values` in our list of modules managed by `expo install` / `expo upgrade` so this should be updated automatically for folks upgrading to sdk 45 https://github.com/expo/expo/commit/6c0d8f661ede35f590fa7378fd0fe0c27bd79d4c

**Comment by mnightingale** [comment]
I'm not sure if it's related to this but I'm getting a failure launching bare-expo.

> Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.

If I follow the workaround linked above I can get it working.

**Comment by tsapeta** [comment]
@mnightingale which version of `react-native-get-random-values` and `expo-random` do you have?

**Comment by mnightingale** [comment]
Not sure what was up with it but `yarn cache clean` and following CONTRIBUTING.md again seems to have sorted it.

**Comment by peterpme** [comment]
Hello! Could it be that this was re-introduced as a regression in SDK48 on Android?

I'm seeing `undefined is not a function` pointing to the line:

```
return global.ExpoModules.ExpoRandom.getRandomBase64String(byteLength..)
```

coming from getRandomValues -> getRandomBase64

I have tried:
- nuking node_modules, yarn cache clean
- upgrading to android sdk 33 in the emulator and clean installing expo
- installing `expo-random` and `react-native-get-random-values`

With no luck. Am I forgetting something? Thank you!

**Comment by tsapeta** [comment]
@peterpme After a quick look, I don't think it could cause a regression, but we'll take a look at that.

`expo-random` is generally deprecated in SDK 48, we merged it into `expo-crypto` which now has some new cool features, including `getRandomValues` and `randomUUID` functions. Maybe you could use them directly without `react-native-get-random-values`?

**Comment by LinusU** [comment]
@tsapeta I don't know if you have read #7209, but there is some more background in there.

Usually when people are using `react-native-get-random-values` it's because they are using some package which weren't made specifically for React Native/Expo, and depend on the global `crypto.getRandomValues` to be available. This is available in the browsers, Deno, Node.js, etc.

I've been trying for more than four years (https://github.com/facebook/react-native/pull/20686, #7209 😅) to get this into React Native or Expo so that all of these packages would just work. And if this is something that is of interest to Expo I would be very happy to submit a PR for this. @brentvatne also took a stab at it here #9716, so maybe you have some input?

Having `crypto.getRandomValues` just work out-of-the-box without any setup for the user would be such a great benefit to the ecosystem, since `Math.random()` shouldn't be used for anything important, and all other javascript environments have moved over to `crypto.getRandomValues`.

`react-native-get-random-values` only polyfills if `typeof global.crypto.getRandomValues !== 'function'`, so if e.g. SDK 49 would get support for it there wouldn't be any conflicts for people already using it.

-----

That being said, the part of the code that maintains different Expo SDK versions is here:

https://github.com/LinusU/react-native-get-random-values/blob/0a48c10a395c19affb9e24044a31e6e56afbf20a/index.js#L30-L34

So maybe we just need to add something new for SDK 48 support? Maybe `global.ExpoModules.ExpoCrypto` instead of `global.ExpoModules.ExpoRandom`?

**Comment by tsapeta** [comment]
Yeah, I know the context and will be happy if we finally make it happen to get this into Expo. We have an alternative polyfill for `crypto.getRandomValues` in the [`expo-standard-web-crypto`](https://github.com/expo/expo/blob/main/packages/expo-standard-web-crypto/src/index.ts) package we made a long time ago (I almost forgot about it), but it requires the user to invoke a function that polyfills (which is not perfect in my opinion).

In SDK 48 we moved `expo-random` into `expo-crypto` with the intention to get `expo-crypto` functionality closer to Web Crypto, so we also added `getRandomValues` and `randomUUID` in there. Now I think we're on a good path to polyfill it 🙂

The question remains: how and when to do that? Ideally if we do this on the native side before the JS bundle is loaded so the user will not need to import anything. But what if React Native (or Hermes) eventually adds this feature? There would be no way for the user to opt-out if `expo-crypto` is installed. What are your thoughts about this?

> So maybe we just need to add something new for SDK 48 support? Maybe global.ExpoModules.ExpoCrypto instead of global.ExpoModules.ExpoRandom?

Yes, would be great if we can add another case to your library to try to use `expo-crypto` before `expo-random`. Btw. now it's better to use `global.expo.modules.ExpoCrypto`, however the old key path still works. I can submit a PR if you want, but probably I won't be able to do that before the stable release of SDK 48 😅

**Comment by LinusU** [comment]
> The question remains: how and when to do that? Ideally if we do this on the native side before the JS bundle is loaded so the user will not need to import anything. But what if React Native (or Hermes) eventually adds this feature? There would be no way for the user to opt-out if expo-crypto is installed. What are your thoughts about this?

Yeah, this is not straight forward. My first PR was actually to add this as C++ code to React Native, and I still think that that would be the best path forward. Or, in this day and age, add it to Hermes.

In fact, I just opened a feature request and offered to make a PR: https://github.com/facebook/hermes/issues/915

If that doesn't move forward I think that it would be okay for Expo to polyfill on startup, if not available.

Would it be possible to move specifically `global.expo.modules.ExpoCrypto.getRandomBase64String` to some kind of Expo core, so that it would be available regardless of wether the `expo-crypto` module is installed or not? Or even better would be to expose a function that fills a typed array directly, instead of going via Base64!

In that case the Expo entrypoint could simply be updated to include something like:

```js
if (typeof global.crypto !== 'object') {
  global.crypto = {}
}

if (typeof global.crypto.getRandomValues !== 'function') {
  global.crypto.getRandomValues = global.expo.modules.ExpoCore.getRandomValues
}
```

Or maybe even better, register the function from the native code directly on `global.crypto.getRandomValues`.

**Comment by tsapeta** [comment]
I'm afraid it's not the thing that the JS engine should do. This is one of the Web APIs, which are implemented by the browser not the JS engine itself as they are not part of the language.

> Would it be possible to move specifically global.expo.modules.ExpoCrypto.getRandomBase64String to some kind of Expo core, so that it would be available regardless of wether the expo-crypto module is installed or not?

I think this is exactly the same case as with the JS engine vs the browser. There are many other APIs that need polyfills in React Native, if we add one then we should add the others as well. I would rather be in favor of not bloating the JS runtime and adding too much into the core if this is not necessary. That being said, polyfilling it automatically when `expo-crypto` is installed sounds like a good compromise. I'll add this to our roadmap for SDK 49 😉 

> Or even better would be to expose a function that fills a typed array directly, instead of going via Base64!

This is exactly what the new `getRandomValues` [does](https://github.com/expo/expo/blob/a2cc5e74550c399188be109d7761995819db7375/packages/expo-crypto/ios/CryptoModule.swift#L58-L69) 🙂 Fully native, called through JSI (as every function of a native expo module).

> Or maybe even better, register the function from the native code directly on global.crypto.getRandomValues.

Yes, I think we'll go this way 👍

**Comment by LinusU** [comment]
> I'm afraid it's not the thing that the JS engine should do.

I can absolutely see that point of view, but I think that Expo is more than a JS engine. In my eyes it's a runtime similar to a browser, Node.js, Deno, etc. And since all of them include `crypto.getRandomValues` out-of-the-box, I think it makes sense for Expo to do it as well.

A downside of polyfilling automatically when `expo-crypto` is installed is that the dependency will look unused. But I guess that's a small price to pay though.

**Comment by tiagocpeixoto** [comment]
As a workaround, I made a polyfill considering that `expo-standard-web-crypto` depends on `expo-random` which is now deprecated in Expo SDK v48.

Here is my code based on the `expo-standard-web-crypto` shim:

```
import { getRandomValues as expoCryptoGetRandomValues } from "expo-crypto";

class Crypto {
  getRandomValues = expoCryptoGetRandomValues;
}

const webCrypto = typeof crypto !== "undefined" ? crypto : new Crypto();


(() => {
  if (typeof crypto === "undefined") {
    Object.defineProperty(window, "crypto", {
      configurable: true,
      enumerable: true,
      get: () => webCrypto
    });
  }
})();
```

**Comment by aleqsio** [comment]
@peterpme Could you check to see if the same issue occurs when calling getRandomValues directly from `expo-crypto`? What argument are you passing to the function?

**Comment by marcato15** [comment]
So, is there any path forward? I just tried upgrading to Expo 48 but I am encountering this issue. It's b/c of an underlying dependency needs the getRandomValues and I can't get past the `Error: Native module not found`. I tried the crypto-shim.ts to no avail. 

I'm growing tired of the Expo approach of both trying to be the default runtime for react native but also saying "not our problem" when they upgrade and break things that have been a part of the ecosystem for years.

**Comment by aleqsio** [comment]
Here's the current state of this issue for anyone searching for resolutions:
1. The `react-native-get-random-values` package has been migrated to using `expo-random` so it should not error, but it will throw deprecation warnings.
2. `Error: Native module not found` issue is unexpected at this point and might indicate you need to update `react-native-get-random-values`.
3. The recommended way to get random values in an Expo project is to use install `expo-crypto` and use the `getRandomValues` function from it – it closely matches the Web API
4. If you need a polyfill for a 3rd party package expecting `window.crypto.getRandomValues`, you can use `expo-standard-web-crypto` or the `crypto-shim.js` file [posted above](https://github.com/expo/expo/issues/17270#issuecomment-1445149952). You need to make sure it's run or imported in the top of the App.ts file.

**Comment by aleqsio** [comment]
@marcato15 
I'd love to help you debug this issue further! Can you share more details and a reproduction in a new issue?

**Comment by Raigen** [comment]
I am trying to upgrade to expo 48, but new builds in expo go fail with
```
 ERROR  Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported, js engine: hermes
 ```
We are using `uuid` and `react-native-get-random-values` in version 1.8.0, which is the latest version afaik and it worked until now.  With expo 48 it does not throw a deprecation, it throws a hard error, so this is not compatible anymore.
I tried using `expo-standard-web-crypto`, but it does not seem to do anything.
```
import { polyfillWebCrypto } from 'expo-standard-web-crypto'

polyfillWebCrypto()
```
I tried this in our `App.tsx` and in our `index.js`, where `react-native-get-random-values` was imported, but neither worked.
It does not seem to kick in.

For context: We have a mono repo setup with a web app, a node api and the mobile app. We also have a utils package where we are using `uuid`. So it is not an explicit dependency of the mobile package.
As I stated initially, all of this worked just fine with expo 47 and `react-native-get-random-values`.

**Comment by aleqsio** [comment]
@Raigen would you have some time to reproduce this into a sample app? I'd like to look into the code and see that's happening, but it might be better to do with specific package versions.

**Comment by s-kuniyoshi** [comment]
I am in the process of upgrading from Expo46 to Expo48, but I encountered this error. 
I am using FirebaseJSSDK v9.8.1, and the library is trying to generate a unique ID when adding a Document, which is causing this error.

**Comment by s-kuniyoshi** [comment]
https://github.com/LinusU/react-native-get-random-values/issues/41#issuecomment-1481910504
This patch work fine for me.

**Comment by aleqsio** [comment]
Unfortunately I'm unable to reproduce this in a clean SDK48 project, `
  console.log(global.ExpoModules.ExpoRandom.getRandomBase64String(10));
`
works just fine. 
Would really appreciate someone sharing a reproduction 🙏

**Comment by marcato15** [comment]
Sorry, I'm working on this but decided to try and switch fully to prebuild. Will report back if I am still encountering the issue.

**Comment by Raigen** [comment]
I have to correct myself, we are using `nanoid` for generating our own ids. But `uuid` is still a dependency of some packages we use.
I used `yarn why uuid` and got a some results from expo packages.
```
$ yarn why uuid
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "uuid"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "uuid@8.3.2"
info Has been hoisted to "uuid"
info Reasons this module exists
   - "workspace-aggregator-db2d0185-1d35-4852-a00a-b6c898b05e40" depends on it
   - Hoisted from "_project_#firebase-tools#uuid"
   - Hoisted from "_project_#firebase-tools#universal-analytics#uuid"
   - Hoisted from "_project_#@<monorepo>#api#firebase-admin#@google-cloud#storage#uuid"
   - Hoisted from "_project_#@jest#core#@jest#reporters#node-notifier#uuid"
   - Hoisted from "_project_#@<monorepo>#mobile#expo#@expo#cli#@expo#rudder-sdk-node#uuid"
   - Hoisted from "_project_#@<monorepo>#app#react-scripts#webpack-dev-server#sockjs#uuid"
   - Hoisted from "_project_#@<monorepo>#mobile#expo#@expo#cli#@expo#dev-server#@expo#bunyan#uuid"
[...]
=> Found "expo-constants#uuid@3.4.0"
info This module exists because "_project_#@<monorepo>#mobile#expo-constants" depends on it.
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "92KB"
info Disk size with transitive dependencies: "92KB"
info Number of shared dependencies: 0
[...]
=> Found "expo-file-system#uuid@3.4.0"
info This module exists because "_project_#@<monorepo>#mobile#expo-file-system" depends on it.
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "92KB"
info Disk size with transitive dependencies: "92KB"
info Number of shared dependencies: 0
=> Found "expo-notifications#uuid@3.4.0"
info This module exists because "_project_#@<monorepo>#mobile#expo-notifications" depends on it.
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "92KB"
info Disk size with transitive dependencies: "92KB"
info Number of shared dependencies: 0
=> Found "expo#uuid@3.4.0"
info This module exists because "_project_#@<monorepo>#mobile#expo" depends on it.
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "92KB"
info Disk size with transitive dependencies: "92KB"
info Number of shared dependencies: 0
```
I looked up expo-constants and it seems to only use uuid in a `.web.` file.
I found it in `expo-file-system` here: https://github.com/expo/expo/blob/sdk-48/packages/expo-file-system/src/FileSystem.ts#L356
Which to me looks like it would also be executed on react native. We do use file downloads AFAIK.
`expo-notifications` uses it in files without any platform indicator in the filename, but I do not know how that works internally or which parts we actually use, so I can not say if that could be a reason.

There is also still `firebase-tools` using `uuid`, so I guess even if expo packages stop using an API that expo is not supporting, we might be stuck here. I still do not really understand why the workarounds do not work, but I am also only working with expo for 3 months now and don't know what funny things we might do from older versions. The only thing I can say for sure is that `react-native-get-random-values` works just fine with 47 and does not work anymore with 48 with no other difference than the expo updates.
I might be able to try a reproducer next week. This has no priority for us right now, but I hope to get more time for it soon. Last time we upgraded expo it was 3 major versions, we do not want to repeat that :D

**Comment by LinusU** [comment]
@Raigen and others having problem, could you please try with version 1.9.0 of `react-native-get-random-values`?

**Comment by Raigen** [comment]
@LinusU No, it is still not working. It seems like the patch is being applied too late. The error comes from `node_modules/expo/build/logs/RemoteLogging.js` which uses uuidv4 to generate a session id.
So this might not even have anything to do with `react-native-get-random-values` anymore.

I do not understand how this is an issue for some people, but not most. Because if `uuid` does not work because in RN/hermes/metro/expo there is no `crypto` by default, then how comes that expo itself uses `uuid` and it seems to work in general.
Also in iOS simulator I am getting this: #17261

I will check for a similar issue or open a new one, I think it became clear that this is not related anymore to the runtime crypto `react-native-get-random-values` provides but something else while build time.

**Comment by zlanich** [comment]
I'm also currently having this issue on Android using `npx expo start --tunnel` on android. `undefined is not a function` - `global.ExpoModules.ExpoRandom.getRandomBase64String()`. `react-native-get-random-values` upgraded to `1.9`, still no luck.

**Comment by tsapeta** [comment]
@zlanich I have some questions:
- Do you have the remote debugger turned on? This function is synchronous so it's just not available in this context.
- Do you have `expo-random` or `expo-crypto` installed and which version? Also what's your version of the `expo` package?

**Comment by zlanich** [comment]
@tsapeta I'm updating my comment above as I go. I'm not sure it notifies you when I update it though.

**Comment by jdhorner** [comment]
Since the last message here was only a bit more than a month ago, I'm going to take a chance. I'm in Expo version 48, and was switching from using the old `uuid` + `react-native-get-random-values` to instead use only the "Crypto" package from expo directly. I only need to generate random UUIDs, so the: 
```js
import * as Crypto from 'expo-crypto'
// later
const uuid = Crypto.randomUUID(); // has an error
```
But I kept getting told 
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: _ExpoCrypto.default.randomUUID is not a function
```
The only way to get random UUIDs that I can figure out is to replicate @brentvatne's solution from the first comment: 
```js
import { v4 } from 'uuid';
import { polyfillWebCrypto } from 'expo-standard-web-crypto';

polyfillWebCrypto();
// later
const uuid = v4(); // works fine
```

Have I missed something to get the Crypto package working correctly in Expo 48?

**Comment by suvam0451** [comment]
> I am trying to upgrade to expo 48, but new builds in expo go fail with
> 
> ```
>  ERROR  Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported, js engine: hermes
> ```
> 
> We are using `uuid` and `react-native-get-random-values` in version 1.8.0, which is the latest version afaik and it worked until now. With expo 48 it does not throw a deprecation, it throws a hard error, so this is not compatible anymore. I tried using `expo-standard-web-crypto`, but it does not seem to do anything.
> 
> ```
> import { polyfillWebCrypto } from 'expo-standard-web-crypto'
> 
> polyfillWebCrypto()
> ```
> 
> I tried this in our `App.tsx` and in our `index.js`, where `react-native-get-random-values` was imported, but neither worked. It does not seem to kick in.
> 
> For context: We have a mono repo setup with a web app, a node api and the mobile app. We also have a utils package where we are using `uuid`. So it is not an explicit dependency of the mobile package. As I stated initially, all of this worked just fine with expo 47 and `react-native-get-random-values`.

I faced the same issue with a mono-repo setup (at least one other web ui workspace having ^9.0.0 `uuid` dependency).

The problem could not be detected initially, because I was using pnpm. But, when I switched to yarn (berry) workspaces, I had to replace the web ui codebase with alternative generators to avoid the hard error.

No poly-filling (`react-native-get-random-values`, `expo-standard-web-crypto`, `expo-random`, `expo-crypto`) was working in the mobile codebase.

I hope this report will be useful to anyone else facing similar issue and someone more knowledgeable can help us figure out a better way to handle this for mono-repo setups 👍

**Comment by Michaelsulistio** [comment]
@aleqsio My usecase falls under the 3rd category you mentioned:

```
If you need a polyfill for a 3rd party package expecting window.crypto.getRandomValues, you can use expo-standard-web-crypto or the crypto-shim.js file https://github.com/expo/expo/issues/17270#issuecomment-1445149952. You need to make sure it's run or imported in the top of the App.ts file.
```

I'm trying to create my own polyfill `crypto-shim.js` but the issue is that the 3rd party package import always runs before my `crypto-shim.js`. I'm on Expo SDK 49 using the new `app/` based expo-router so I don't have a `App.ts` file.

3rd party package:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.crypto = void 0;
console.log("in 3rd party");
exports.crypto = typeof globalThis === 'object' && 'crypto' in globalThis ? globalThis.crypto : undefined;
//# sourceMappingURL=crypto.js.map
```

The `in 3rd party` line always gets logged before any of my shims, no matter where I place it. Do you know why the 3rd party code is running first? Where can run my polyfills so that they're actually polyfilled in time for the imports?

**Comment by nickfrosty** [comment]
@Michaelsulistio this is the perfect solution for using expo router! Thanks!

**Comment by ericyliu** [comment]
tried @Michaelsulistio solution, but im getting two errors:

```
Error: Cannot find native module 'ExpoCrypto', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by liambigras** [comment]
I'm using expo 48. Managed to get it working by uninstalling expo-random and already had expo-crypto installed. Also uninstalled react-native-get-random-values. I'm just relieved it works now.

**Comment by Chasewhip8** [comment]
@Michaelsulistio Thank you so much dude, anyone using expo router, you need to define a custom entrypoint and polyfill from there first. Make sure to clear your cache if it just drops you back to the expo start screen.

**Comment by Streudal** [comment]
> @aleqsio My usecase falls under the 3rd category you mentioned:
> 
> ```
> If you need a polyfill for a 3rd party package expecting window.crypto.getRandomValues, you can use expo-standard-web-crypto or the crypto-shim.js file https://github.com/expo/expo/issues/17270#issuecomment-1445149952. You need to make sure it's run or imported in the top of the App.ts file.
> ```
> 
> I'm trying to create my own polyfill `crypto-shim.js` but the issue is that the 3rd party package import always runs before my `crypto-shim.js`. I'm on Expo SDK 49 using the new `app/` based expo-router so I don't have a `App.ts` file.
> 
> 3rd party package:
> 
> ```
> "use strict";
> Object.defineProperty(exports, "__esModule", { value: true });
> exports.crypto = void 0;
> console.log("in 3rd party");
> exports.crypto = typeof globalThis === 'object' && 'crypto' in globalThis ? globalThis.crypto : undefined;
> //# sourceMappingURL=crypto.js.map
> ```
> 
> The `in 3rd party` line always gets logged before any of my shims, no matter where I place it. Where can I run my polyfills so that they're actually polyfilled in time for the imports?
> 
> If I edit `node_modules/expo-router/entry.js`, then it finally polyfills before the import. Is there a way I can insert my polyfills into `node_modules/expo-router/entry.js`?
> 
> ```
> // `@expo/metro-runtime` MUST be the first import to ensure Fast Refresh works
> // on web.
> import "@expo/metro-runtime";
> 
> // DO POLYFILL/SHIM CODE HERE
> console.log("this will execute before 3rd party imports");
> 
> // This file should only import and register the root. No components or exports
> // should be added here.
> import { renderRootComponent } from "expo-router/src/renderRootComponent";
> 
> import { App } from "./_app";
> 
> renderRootComponent(App);
> ```
> 
> EDIT: solved by changing the `"main": "index.js",` in `package.json` then doing the polyfill code in there.
> 
> index.js:
> 
> ```
> // POLYFILLS/SHIMS
> import {getRandomValues as expoCryptoGetRandomValues} from 'expo-crypto';
> 
> // getRandomValues polyfill
> class Crypto {
>   getRandomValues = expoCryptoGetRandomValues;
> }
> 
> const webCrypto = typeof crypto !== 'undefined' ? crypto : new Crypto();
> 
> (() => {
>   if (typeof crypto === 'undefined') {
>     Object.defineProperty(window, 'crypto', {
>       configurable: true,
>       enumerable: true,
>       get: () => webCrypto,
>     });
>   }
> })();
> 
> 
> import 'expo-router/entry';
> ```

@Michaelsulistio This solution didn't work for me but I took its inspiration and just decided to use the `patch-package` library to create a patch for the `expo-router` module that adds the following line to the file: 

```import 'react-native-get-random-values'``` ( with a comment for organization)

so here's what you would get: 

BEFORE:
```
// `@expo/metro-runtime` MUST be the first import to ensure Fast Refresh works
// on web.
import "@expo/metro-runtime";

// This file should only import and register the root. No components or exports
// should be added here.
import { renderRootComponent } from "expo-router/src/renderRootComponent";

import { App } from "./_app";

renderRootComponent(App);
```

AFTER:
```
// `@expo/metro-runtime` MUST be the first import to ensure Fast Refresh works
// on web.
import "@expo/metro-runtime";

// POLYFILLS
import 'react-native-get-random-values';

// This file should only import and register the root. No components or exports
// should be added here.
import { renderRootComponent } from "expo-router/src/renderRootComponent";

import { App } from "./_app";

renderRootComponent(App);
```

For some background context, I just needed the polyfill for packages that were relying on it causing it to prompt warnings when running my app. I do not have `expo-crypto` installed and I did try that and it made no difference.

Here are the versions of things I am using: 
* "expo": "~49.0.9"
* "expo-router": "2.0.0"
* "react-native-get-random-values": "1.9.0"

**Comment by Jeanclaudeaoun** [comment]
After trying all the above recommendations, nothing worked for my case 

The only thing that FINALLY worked is merging the global.crypto with 'expo-crypto' in the polyfills 

// polyfills.js
```
import * as crypto from 'expo-crypto';
global.crypto = { ...global.crypto, ...crypto };
```

**Comment by rocketraman** [comment]
> As a workaround, I made a polyfill considering that `expo-standard-web-crypto` depends on `expo-random` which is now deprecated in Expo SDK v48.

Just an update on this... `expo-standard-web-crypto` now works with `expo-crypto` so the custom shim from comment https://github.com/expo/expo/issues/17270#issuecomment-1445149952 is no longer necessary for third-party components that need `Crypto.getRandomValues()`.

Just do this as early as possible -- I do it in `index.js` before `registerRootComponent`:

```
import { polyfillWebCrypto } from 'expo-standard-web-crypto';
polyfillWebCrypto();
```
