### ISSUE TITLE
[docs] Missing docs for cancelling network tasks

### ISSUE THREAD

**Issue by wodin** [expo/expo#17279]
### Summary

`cancelAsync` is not documented.

This was implemented in #13318

### Link to the related docs page

https://docs.expo.dev/versions/v45.0.0/sdk/filesystem/

### Anything else?

Not sure if BackgroundFetch or TaskManager docs should be updated too.

**Comment by wodin** [comment]
@lukmccall any chance cancelAsync can be documented? Should the BackgroundFetch or TaskManager docs be updated too?

**Comment by wodin** [comment]
The docs are still missing...

**Comment by Simek** [comment]
This issue has been fixed in:
* https://github.com/expo/expo/pull/20103
