### ISSUE TITLE
exp start and exp start --lan does not work after detaching

### ISSUE THREAD

**Issue by aprilmintacpineda** [expo/expo#1727]
here's exactly what I did:

- `exp detach`
- npm installed => https://github.com/balthazar/react-native-zeroconf
- wrote a few lines of codes

`exp start --lan`.

```
20:09:31 [exp] Using project at ~my project dir
20:09:32 [exp] Warning: You are using npm version 5.6.0. There may be bugs in this version, use it at your own risk. We recommend version latest.
20:09:58 [exp] Starting Metro Bundler on port 19001.
20:09:59 [exp] Metro Bundler ready.
20:10:01 [exp] Tunnel connected.
20:10:02 [exp] Expo is ready.

20:10:02 [exp] Your URL is: exp673d4361a35f4c2e876ca8c417fbb791://192.168.1.10:19000
20:10:02 [exp] Logs for your project will appear below. Press Ctrl+C to exit.
```

I can see the link on my android device's expo app, but when I tap on it, nothing happens.

###### diagnostics

```
Environment:
  OS: Linux 4.13
  Node: 8.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/aprilmintacpineda-e1fe08f7-7ce4-4824-9fb4-6fadbc0ab420.tar.gz
```

**Comment by aprilmintacpineda** [comment]
I see, sorry I skipped reading this -> https://docs.expo.io/versions/v25.0.0/expokit/expokit.html. My bad. BTW, how do I become an official contributor of expo?

**Comment by terribleben** [comment]
Hi! We accept pull requests if you want to contribute. Just be sure and drop us a line on Slack and make sure your proposed change is something we can handle, before spending a lot of time on it. (See also: [Contributing](https://github.com/expo/expo#contributing))
