### ISSUE TITLE
SDK 45 Beta 8 [Android] Cannot access expo.modules.updatesinterface.UpdatesInterface

### ISSUE THREAD

**Issue by thespacemanatee** [expo/expo#17288]
### Summary

After running `expo upgrade` to SDK 45 beta 8, the same line of code here in `MainApplication.java` `onCreate()` method:

```java
if (BuildConfig.DEBUG) {
    DevLauncherController.getInstance().setUpdatesInterface(UpdatesDevLauncherController.initialize(this));
}
```

is giving a new error:

```
Cannot access expo.modules.updatesinterface.UpdatesInterface
```

I have already tried Invalidating Caches, cleaning and rebuilding the project to no avail. Reverted back to SDK 44 and it immediately started working again.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

SDK 45 beta-8

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
        Android NDK: 21.4.7075529
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0-beta.8 => 45.0.0-beta.8 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
    Expo Workflow: bare
```

### Reproducible demo

```java
@Override
public void onCreate() {
    super.onCreate();
    // If you opted-in for the New Architecture, we enable the TurboModule system
    ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    SoLoader.init(this, /* native exopackage */ false);
    DevLauncherController.initialize(this, getReactNativeHost());
    if (BuildConfig.DEBUG) {
        DevLauncherController.getInstance().setUpdatesInterface(UpdatesDevLauncherController.initialize(this));
    }
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    ApplicationLifecycleDispatcher.onApplicationCreate(this);
}
```

**Comment by mackenziekira** [comment]
@thespacemanatee did you find a workaround for this? I am running into it too

**Comment by thespacemanatee** [comment]
> @thespacemanatee did you find a workaround for this? I am running into it too

I just left it commented out. Looking at the method signature, I don't think it does much? Especially since it only runs on debug releases. Perhaps the documentation is outdated and this is no longer needed @byCedric

**Comment by thespacemanatee** [comment]
@mackenziekira @byCedric not sure if this is the proper workaround but this code works instead:
`DevLauncherUpdatesInterfaceDelegate.INSTANCE.initializeUpdatesInterface(this);`
and seems to do the same thing as:
`DevLauncherController.getInstance().setUpdatesInterface(UpdatesDevLauncherController.initialize(this));`
which is currently not working (`Cannot access expo.modules.updatesinterface.UpdatesInterface`)

**Comment by ariccio** [comment]
Yeah, as a novice mobile developer who does NOT want to learn java (for reasons best described as "religious"), I'm really glad to have a turnkey option like expo, but it's been wildly flaky for me. Things break all the time for reasons that are mysterious to me. That I find java to be impenetrable with fewer than 8 cups of coffee only makes it harder. I find it easier to read x86 assembly, and write disgusting patches in C++ than I do figuring out that `DevLauncherUpdatesInterfaceDelegate.INSTANCE.initializeUpdatesInterface` does the same thing as `DevLauncherController.getInstance().setUpdatesInterface`. I've lost weeks of development time total to weird issues like this. The only more annoying issue I've had was when Google's OAuth API had an incredibly insidious issue with package names (which I still do not understand).

*shakes fist at java programmers*

Sidenote: my build still does not work! I hit an `error: package DevLauncherUpdatesInterfaceDelegate does not exist`. Do I have to import something? I tried `import expo.modules.updates.DevLauncherUpdatesInterfaceDelegate;`, but that does not exist. I am about to try `import expo.modules.devlauncher.DevLauncherUpdatesInterfaceDelegate;` and wait the ten minutes for the rebuild.

**Comment by ariccio** [comment]
You know what's super weird? I'm seeing this again right now, even though I definitely have the correct import:
`import expo.modules.devlauncher.DevLauncherUpdatesInterfaceDelegate;`
