### ISSUE TITLE
[docs] expo barcodescanner

### ISSUE THREAD

**Issue by kirill-dev-pro** [expo/expo#17281]
### Summary

expo-barcode-scanner doesnt supported on web but doc says it is supported since sdk 43. `BarCodeScanner` component return `BarCodeScanner Component not supported on the web` message

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

**Comment by byCedric** [comment]
Hi @kirill-dev-pro, please see https://snack.expo.dev/@bycedric/basic-barcode-scanner-usage-on-web as example.
