### ISSUE TITLE
Paid Individual Apple Developer Account not recognized because it is not a team.

### ISSUE THREAD

**Issue by scott-mains** [expo/expo#17298]
> Hi @marcosmartinez7 - unfortunately you need a paid account in order to create an ipa for TestFlight distribution :( (true everywhere, not just on Expo). Sorry about that! If you want to test without a paid account you'll need to just use the Expo client app.

Hi @esamelson, 
What kind of [paid account](https://developer.apple.com/support/compare-memberships/) is needed? **Apple Developer Program** or **Apple Developer Enterprise Program**?

_Originally posted by @Struemmeck in https://github.com/expo/expo/issues/1528#issuecomment-458230297_

I developed an app on Expo for a friend who has a paid Apple Developer Program individual account.  We created a expo organization to share the app for testing.  Now we want to distribute.  He has an Apple Developer Distribution and Private key which he was able to export to me and which I now have tried to upload to the iOS credentials for the expo organization.  however, I get the message that there is no team associated with his account.  how can this be.  He has a paid account.

How can we distribute his app on his paid account through expo?

**Comment by byCedric** [comment]
You can use EAS submit with an Apple Developer Program. If you are running into issues, I would recommend reading https://docs.expo.dev/distribution/uploading-apps/#22-if-you-choose-to-upload-your. We document the steps you need to take to set up your Expo account with the Apple App Store credentials.

If that fails, you can also try to manually upload the app.
