### ISSUE TITLE
How to manage CALL_PHONE android permission?

### ISSUE THREAD

**Issue by FakhruddinAbdi** [expo/expo#1729]
According to expo document, we can just manage specific list of permission which doesn't include some android permissions like `Call_phone`.

how we should manage it using expo?

**Comment by ide** [comment]
I think you need to detach and modify the AndroidManifest.xml file; this is not a permission included with the Expo AndroidManifest.xml file.

**Comment by FakhruddinAbdi** [comment]
Its really nightmare to detach for such a small issue.
Any workaround or roadmap to support android permissions ?

**Comment by FakhruddinAbdi** [comment]
@riwu i have an App with customer to customer business model. when someone in the app want to buy something,  he need to call to provided number directly from the app which is a very common use case.

For now i just downgraded to expo version 26 which works fine, but Im not sure how it will works in production with sdk 26 and how it grant the permission

**Comment by riwu** [comment]
@FakhruddinAbdi but how does your app make the phone call? What library/API are you using?

**Comment by FakhruddinAbdi** [comment]
React native [`Linking`](https://facebook.github.io/react-native/docs/linking.html) library does it. ex: Linking.openURL('tel:xxxxxxxxx');
