### ISSUE TITLE
[Expo SDK 45] - react-native-appearance error when building via EAS

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#17301]
### Summary

I'm getting the following error, when building my app for android via EAS, which was upgraded to SDK 45:

Installing Android SDK Platform 31 in /home/expo/Android/Sdk/platforms/android-31
131 "Install Android SDK Platform 31 (revision: 1)" complete.
132 "Install Android SDK Platform 31 (revision: 1)" finished.
133 [stderr] FAILURE: Build completed with 2 failures.
134 [stderr] 1: Task failed with an exception.
135 [stderr] -----------
136 [stderr] * Where:
137 [stderr] Build file '/home/expo/workingdir/build/node_modules/react-native-appearance/android/build.gradle' line: 23
138 [stderr] * What went wrong:
139 [stderr] A problem occurred evaluating project ':react-native-appearance'.
140 [stderr] > Plugin with id 'maven' not found.
141 [stderr] * Try:
142 [stderr] > Run with
143 [stderr] --stacktrace option to get the stack trace.
144 [stderr] > Run with --info or --debug option to get more log output.
145 [stderr] > Run with --scan to get full insights.
146 [stderr] ==============================================================================
147 [stderr] 2: Task failed with an exception.
148 [stderr] -----------
149 [stderr] * What went wrong:
150 [stderr] A problem occurred configuring project ':react-native-appearance'.
151 [stderr] > compileSdkVersion is not specified. Please add it to build.gradle
152 [stderr] * Try:
153 [stderr] > Run with --stacktrace option to get the stack trace.
154 [stderr] > Run with --info or --debug option to get more log output.
155 [stderr] > Run with --scan to get full insights.
156 [stderr] ==============================================================================
157 [stderr] * Get more help at https://help.gradle.org
158 [stderr] BUILD FAILED in 4m 1s

I followed the upgrade steps in the Docs and then just run the EAS build.
Same error applies, when building locally.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/opt/nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/opt/nvm/versions/node/v14.17.5/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 26, 27, 29, 30, 31
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0-beta.9 => 45.0.0-beta.9 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

Since it is a build Issue, I don't know how to build a reproducible demo.

**Comment by Kudo** [comment]
hi there! react-native-appearance is deprecated in favor of [the official appearance from react-native](https://reactnative.dev/docs/appearance) in [expo sdk 42](https://docs.expo.dev/versions/v42.0.0/sdk/appearance/). you can just use the `Appearance` and `useColorScheme` from `react-native` without changing or installing other native modules. if there's any further questions, please let us know. thank you!

**Comment by mariomurrent-softwaresolutions** [comment]
Interesting, but why has it worked until now?

**Comment by mariomurrent-softwaresolutions** [comment]
Ah I see. So maybe this should be mentioned in the upgrade manual as well? Last chance to remove the deprecated API

**Comment by Kudo** [comment]
it's already [mentioned in sdk 43](https://blog.expo.dev/expo-sdk-43-aa9b3c7d5541) 😅

**Comment by mariomurrent-softwaresolutions** [comment]
Damn, must have missed that one during the upgrade - or I just did not remove the package, because my usages were already updated.
Thanks for helping me it :) Helped me get to the next error :D
