### ISSUE TITLE
How to get a radial-gradient background with expo?

### ISSUE THREAD

**Issue by vecpeng** [expo/expo#17304]
Just like this in css:
```html
background-color: radial-gradient(80.41% 88.9% at 50.13% 32.58%, #FFB5B5 17.19%, rgba(130, 153, 153, 0) 100%)
```

**Comment by wodin** [comment]
Questions like this should be asked on forums.expo.dev

One way to do it, I think, is with an SVG. e.g. https://snack.expo.dev/@wodin/radial-gradient
