### ISSUE TITLE
[SDK 45] Using sampling profiler with Hermes not possible

### ISSUE THREAD

**Issue by evelant** [expo/expo#17307]
### Summary

On SDK 45 there is seemingly no way to open the react-native developer menu so it is not possible to start the sampling profiler and use `react-native profile-hermes` to download and analyze profiles from devices.

AFAIK the hermes sampling profiler is the only possible way to profile JS performance actually running on a device.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

```
"expo": "next",
"expo-dev-client": "~0.9.3",
"react-native": "0.68.1",
```

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 16.14.2 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 3.2.0 - /opt/homebrew/bin/yarn
      npm: 7.18.1 - /opt/homebrew/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 3 Bumblebee 2021.1.1 Patch 3
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed
```

### Reproducible demo

N/A, observe that there is no way to access the react-native developer menu to start the sampling profiler

**Comment by Kudo** [comment]
hi there! could you describe how you trying to open the developer menu? for me, both pressing 'm' key in expo-cli terminal ui and `adb shell input keyevent 82` works me. 🤔

**Comment by evelant** [comment]
@Kudo I'm referring to the plain react-native developer menu, not the expo developer menu. In previous versions of expo there was an option in the expo developer menu to open the react-native developer menu, that appears to be missing now.

**Comment by Kudo** [comment]
@evelant sorry i may misunderstand. is that what you want? 

<img src="https://user-images.githubusercontent.com/46429/166246016-fe1eacde-d5ec-4815-811d-b33ca59294d5.png" height="600" />

**Comment by evelant** [comment]
Yes, as far as I can tell there's no way to access that sampling profiler start/stop in SDK 45

**Comment by Kudo** [comment]
oh that's true. the feature was missing in the new expo-dev-menu ui. i'll label the issue and we'll try to follow up with this. thanks!

**Comment by evelant** [comment]
@Kudo it would also be nice if [hermes profile transformer](https://github.com/react-native-community/hermes-profile-transformer) could be integrated into the expo CLI. Right now in order to use `react-native profile-hermes` (automatically downloads and converts the trace from a device) in a managed project it's necessary to create a dummy react-native project with the same package id and run it there.

**Comment by evelant** [comment]
Since it's impossible to start the sampling profiler in SDK 45 now the only way to use sampling profiler is to make a separate branch of an app where expo is ejected. That's a pretty big pain, it would be awesome if the hermes sampling profiler was usable by default with expo. It's the first useful working on-device code profiling tool for react-native since years ago when facebook decided to internalize their systrace tools and stop releasing them.

**Comment by lukmccall** [comment]
That option will be restored in the next version of dev-client.
Also, you can access the same functionality via chrome. See https://reactnative.dev/docs/hermes/#debugging-js-on-hermes-using-google-chromes-devtools.

**Comment by evelant** [comment]
@lukmccall just FYI that is not the same functionality -- the debugger and the sampling profiler are different things. There is no way to profile performance with hermes other than the sampling profiler and the hermes profile transformer tool. It cannot be done with chrome devtools.

**Comment by sannajammeh** [comment]
This is not a closed issue.

**Comment by shirakaba** [comment]
Still a problem as of SDK 49 on iOS.

The React Native [profiling with Hermes docs](https://reactnative.dev/docs/profile-hermes#record-a-hermes-sampling-profile) suggest that there should be a "Enable Sampling Profiler" option in the dev menu, but there isn't:

<img width="434" alt="image" src="https://github.com/expo/expo/assets/14055146/6b7b7a84-67c2-47d5-b31b-b308504b7adb">

As mentioned above, the "Debugger" option is different.

**Comment by stevekuznetsov** [comment]
@lukmccall could we please re-open this issue?

**Comment by stevekuznetsov** [comment]
One thing I have noticed is the "JavaScript Profiler" tab in Chrome Dev Tools that gets opened when you go through the Expo Dev Menu does work - I wonder if that is itself using the Hermes Sampling Profiler under the hood? This is different from the "Performance" tab I learned. @evelant regarding your previous comment in 2022, do you know if the landscape has changed since then, and do you think the "JavaScript Profiler" in Chrome Dev Tools is now another way to profile Hermes aside from the sampler CLI?

**Comment by shirakaba** [comment]
I'm pretty sure this reproduces on a fresh template but would have to confirm.

(yes I know I'm talking to a bot)
