### ISSUE TITLE
 SDK44 Unable to resolve module uuid/v5 in expo go

### ISSUE THREAD

**Issue by jorgebaralt** [expo/expo#17308]
### Summary

When installing expo-image-picker notice that uuid is using a depricated import. 

iOS Bundling failed 1021ms
Unable to resolve module uuid/v5 from {file paths}/node_modules\expo\build\environment\getInstallationIdAsync.js: uuid/v5 could not be found within the project or in these directories:
  node_modules\expo\node_modules
  node_modules

   1 | import * as Application from 'expo-application';
> 2 | import uuidv5 from 'uuid/v5';
    |                     ^
  3 | let installationId;
  4 | const UUID_NAMESPACE = '29cc8a0d-747c-5f85-9ff9-f2f16636d963'; // uuidv5(0, "expo")
  5 | export default async function getInstallationIdAsync() {
  
  This issue was fixed in the SDK45 Beta. but its also failing on 44, can we add the same fix? 
  here is the link of the mentioned bug 
  https://github.com/expo/expo/issues/17261

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

SDK44

### Environment

    System:
      m1 mac
    npmPackages:
      expo: ~44.0.0
      react: 17.0.1
      react-dom: 17.0.1
      react-native: 0.64.3 
    Expo Workflow: managed

### Reproducible demo

https://github.com/ramiel1999/expo-sdk45-uuid

**Comment by brentvatne** [comment]
this was fixed in expo@45.0.0-beta.9 - bump the version in your project :)
