### ISSUE TITLE
[Expo SDK 45] iOS EAS build config plugin sync failed

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#17303]
### Summary

I'm getting the following error, when building my app for iOS via EAS, which was upgraded to SDK 45:

1 Creating native project directories (./ios and ./android) and updating .gitignore
2 ✔ Created native project | gitignore already synced
3 - Adding Metro bundler config
4 - Updating your package.json scripts, dependencies, and main file
5 ✔ Updated package.json and added index.js entry point for iOS and Android
6 - Config syncing
7 ✖ Config sync failed
8 [stderr] [03:38:23] [ios.xcodeproj]: withIosXcodeprojBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
9 [stderr] Please report this as an issue on https://github.com/expo/expo-cli/issues
10 [stderr] [03:38:23] UnexpectedError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
11 [stderr] Please report this as an issue on https://github.com/expo/expo-cli/issues
12 [stderr]     at getAppDelegateFilePath (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/ios/Paths.ts:52:11)
13 [stderr]     at getAppDelegate (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/ios/Paths.ts:114:20)
14 [stderr]     at Object.getSourceRoot (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/ios/Paths.ts:119:23)
15 [stderr]     at setNotificationSounds (/Users/expo/workingdir/build/node_modules/expo-notifications/plugin/build/withNotificationsIOS.js:39:57)
16 [stderr]     at /Users/expo/workingdir/build/node_modules/expo-notifications/plugin/build/withNotificationsIOS.js:19:9
17 [stderr]     at action (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
18 [stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/expo-notifications/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
19 [stderr]     at action (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:228:14)
20 [stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
21 [stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
22 [stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
23 [stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
24 [stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
25 [stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
26 [stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
27 [stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
28 bash exited with non-zero code: 1

I followed the upgrade steps in the Docs and then just run the EAS build.
Same error applies, when building locally.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/opt/nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/opt/nvm/versions/node/v14.17.5/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 26, 27, 29, 30, 31
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0-beta.9 => 45.0.0-beta.9 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

Since it is a build Issue, I don't know how to build a reproducible demo.

**Comment by brentvatne** [comment]
@mariomurrent-softwaresolutions - my suggestion for creating a reproducible example is to do the following:

1. run `expo prebuild -p ios --clean` locally
2. does it fail with the same error you provided above? if so, go to 1. does it succeed? try adding back some of the changes you made since the last failed attempt at running `prebuild`, do this until you narrow down the exact library or config plugin that causes the issue for you. now try to reproduce it in a blank new project with this same thing.

let me know how that goes, happy to investigate when you can narrow it down!

**Comment by mariomurrent-softwaresolutions** [comment]
@brentvatne It is acutely as the log output states. The expo-notifications Module does not work.

I removed it and at least iOS is now building via EAS

**Comment by danscan** [comment]
FWIW I just ran into this issue. I'm also using `expo-notifications`, and it looks like its config plugin may be expecting an `AppDelegate.m` rather than the new `AppDelegate.mm`.

**Workaround**:
```
yarn remove expo-notifications
expo prebuild --clean
expo install expo-notifications
```

**Comment by brentvatne** [comment]
@danscan - which version of expo-notifications was installed? can you share your output from `yarn why @expo/config-plugins` also?

**Comment by danscan** [comment]
@brentvatne Sorry for the delay!

> which version of expo-notifications was installed?
`expo-notifications@0.15.2`

> can you share your output from yarn why @expo/config-plugins also?
```
yarn why v1.22.17
[1/4] Why do we have the module "@expo/config-plugins"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
info 
=> Found "@expo/config-plugins@4.0.15"
info Has been hoisted to "@expo/config-plugins"
info Reasons this module exists
   - Hoisted from "expo-barcode-scanner#@expo#config-plugins"
   - Hoisted from "expo-dev-client#@expo#config-plugins"
   - Hoisted from "expo-local-authentication#@expo#config-plugins"
   - Hoisted from "expo-notifications#@expo#config-plugins"
   - Hoisted from "expo-system-ui#@expo#config-plugins"
   - Hoisted from "expo-updates#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-launcher#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-menu#@expo#config-plugins"
   - Hoisted from "expo#expo-file-system#@expo#config-plugins"
info Disk size without dependencies: "2.74MB"
info Disk size with unique dependencies: "4.84MB"
info Disk size with transitive dependencies: "9.06MB"
info Number of shared dependencies: 55
info 
=> Found "@expo/config#@expo/config-plugins@4.1.5"
info This module exists because "@expo#config" depends on it.
info Disk size without dependencies: "1.88MB"
info Disk size with unique dependencies: "3.59MB"
info Disk size with transitive dependencies: "7.7MB"
info Number of shared dependencies: 51
info 
=> Found "expo-community-flipper#@expo/config-plugins@4.1.0"
info This module exists because "expo-community-flipper" depends on it.
info Disk size without dependencies: "1.56MB"
info Disk size with unique dependencies: "3.66MB"
info Disk size with transitive dependencies: "7.88MB"
info Number of shared dependencies: 55
info 
=> Found "@config-plugins/react-native-ble-plx#@expo/config-plugins@4.1.0"
info This module exists because "@config-plugins#react-native-ble-plx" depends on it.
info Disk size without dependencies: "1.56MB"
info Disk size with unique dependencies: "3.66MB"
info Disk size with transitive dependencies: "7.88MB"
info Number of shared dependencies: 55
info 
=> Found "sentry-expo#@expo/config-plugins@4.1.4"
info This module exists because "sentry-expo" depends on it.
info Disk size without dependencies: "1.6MB"
info Disk size with unique dependencies: "3.31MB"
info Disk size with transitive dependencies: "7.42MB"
info Number of shared dependencies: 51
info 
=> Found "expo-constants#@expo/config-plugins@4.1.4"
info Reasons this module exists
   - "expo-constants#@expo#config" depends on it
   - Hoisted from "expo-constants#@expo#config#@expo#config-plugins"
info Disk size without dependencies: "1.87MB"
info Disk size with unique dependencies: "3.58MB"
info Disk size with transitive dependencies: "7.7MB"
info Number of shared dependencies: 51
info 
=> Found "expo-updates#@expo/config#@expo/config-plugins@4.1.4"
info This module exists because "expo-updates#@expo#config" depends on it.
info Disk size without dependencies: "1.87MB"
info Disk size with unique dependencies: "3.58MB"
info Disk size with transitive dependencies: "7.7MB"
info Number of shared dependencies: 51
info 
=> Found "jest-expo#@expo/config-plugins@4.1.4"
info Reasons this module exists
   - "jest-expo#@expo#config" depends on it
   - Hoisted from "jest-expo#@expo#config#@expo#config-plugins"
info Disk size without dependencies: "1.87MB"
info Disk size with unique dependencies: "3.58MB"
info Disk size with transitive dependencies: "7.7MB"
info Number of shared dependencies: 51
info 
=> Found "@expo/prebuild-config#@expo/config-plugins@4.1.4"
info Reasons this module exists
   - "expo-splash-screen#@expo#prebuild-config" depends on it
   - Hoisted from "expo-splash-screen#@expo#prebuild-config#@expo#config#@expo#config-plugins"
info Disk size without dependencies: "1.87MB"
info Disk size with unique dependencies: "3.58MB"
info Disk size with transitive dependencies: "7.7MB"
info Number of shared dependencies: 51
info 
=> Found "@expo/cli#@expo/config-plugins@4.1.4"
info Reasons this module exists
   - "expo#@expo#cli" depends on it
   - Hoisted from "expo#@expo#cli#@expo#config#@expo#config-plugins"
info Disk size without dependencies: "1.87MB"
info Disk size with unique dependencies: "3.58MB"
info Disk size with transitive dependencies: "7.7MB"
info Number of shared dependencies: 51
info 
=> Found "@expo/metro-config#@expo/config-plugins@4.1.4"
info Reasons this module exists
   - "expo-updates#@expo#metro-config#@expo#config" depends on it
   - Hoisted from "expo-updates#@expo#metro-config#@expo#config#@expo#config-plugins"
info Disk size without dependencies: "1.87MB"
info Disk size with unique dependencies: "3.58MB"
info Disk size with transitive dependencies: "7.7MB"
info Number of shared dependencies: 51
Done in 0.61s.
```

**Comment by danscan** [comment]
Turns out the issue is that `@expo/config-plugins@4.0.15` is the issue. It doensn't support `.mm` AppDelegates, and in my case it's being hoisted via the expo modules you can see in the `yarn why` output in my previous message.

Going to figure out and share a workaround now.

More context: below is the output from `expo prebuild`. The same issue is happening locally as well as in EAS at the Prebuild step.

```
$ expo prebuild --clean && ./scripts/post-prebuild.sh
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding, so you can revert the changes made by this command if necessary.

✔ Would you like to proceed? … yes

✔ Cleared android, ios code
⠼ Creating native project directories (./ios and ./android) and 
✔ Created native projects | gitignore already synced
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.dev/guides/customizing-metro

✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 665ms
✖ Config sync failed
[ios.xcodeproj]: withIosXcodeprojBaseMod: Could not locate a valid AppDelegate at root: "/Users/dscanlon/app"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Could not locate a valid AppDelegate at root: "/Users/dscanlon/app"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegateFilePath (/Users/dscanlon/Documents/Genesis/genesis-app/node_modules/@expo/config-plugins/src/ios/Paths.ts:52:11)
    at getAppDelegate (/Users/dscanlon/Documents/Genesis/genesis-app/node_modules/@expo/config-plugins/src/ios/Paths.ts:114:20)
    at Object.getSourceRoot (/Users/dscanlon/Documents/Genesis/genesis-app/node_modules/@expo/config-plugins/src/ios/Paths.ts:119:23)
    at setNotificationSounds (/Users/dscanlon/Documents/Genesis/genesis-app/node_modules/expo-notifications/plugin/build/withNotificationsIOS.js:39:57)
    at /Users/dscanlon/Documents/Genesis/genesis-app/node_modules/expo-notifications/plugin/build/withNotificationsIOS.js:19:9
    at action (/Users/dscanlon/Documents/Genesis/genesis-app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
    at interceptingMod (/Users/dscanlon/Documents/Genesis/genesis-app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
    at action (/Users/dscanlon/Documents/Genesis/genesis-app/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:228:14)
    at interceptingMod (/Users/dscanlon/Documents/Genesis/genesis-app/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/dscanlon/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/dscanlon/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/dscanlon/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/dscanlon/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/dscanlon/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/dscanlon/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/dscanlon/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
error Command failed with exit code 1.
```

**Comment by danscan** [comment]
Workaround: https://github.com/expo/expo/issues/17610#issuecomment-1135304084
> Workaround via [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/):
>
> `package.json`
> ```json
> {
>   // ...
>   "resolutions": {
>     "@expo/config-plugins": "4.1.5"
>   }
> }
> ```
