### ISSUE TITLE
Cannot run expo 27.0.1

### ISSUE THREAD

**Issue by seenickcode** [expo/expo#1731]
Hello, I'm getting an error when running expo via `create-react-native-app`:

![screenshot_2018-05-07_20-27-16](https://user-images.githubusercontent.com/75833/39712770-549b31b8-5235-11e8-9995-117fc76da654.png)

These are my `package.json` dependencies:
```
"dependencies": {
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "^0.54.2"
  }
```

The steps I've performed:
1. Tried to downgrade to react-native 0.54.2
2. Wiped my emulator's data completely
3. `rm -rf node_modules`
4. `yarn install`
5. `yarn start`

Here's what I see when starting my Android emulator.
```
20:26:11: Starting Android...

 › Press a to open Android device or emulator.
 › Press s to send the app URL to your phone number or email address
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)

20:26:24: Warning: Unable to resolve manifest assets. Icons might not work. Unable to perform cache refresh for /home/seenickcode/.cache/expo/schema-27.0.0.json: Error: read ECONNRESET.
20:26:31: Warning: Problem validating app.json: Unable to perform cache refresh for /home/seenickcode/.cache/expo/schema-27.0.0.json: Error: read ECONNRESET.
20:27:03: Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 7.0.0, 8.0.0, 9.0.0
```

Is this related to https://github.com/expo/expo/issues/1077 and if so, what is a full solution?

Thanks,

**Comment by ide** [comment]
It looks like your JS is newer than your sdkVersion and you might have an outdated Expo client too. Get the latest version from Google Play (description says something about RN 0.55) and follow the instructions here: https://docs.expo.io/versions/v27.0.0/

**Comment by seenickcode** [comment]
I've updated the global `create-react-native-app` npm package and started fresh with a new project to try. Due to either a blacklisted `expo.io` domain from where I am or significant connection issues, I'll have to abandon this ticket and try when I'm back in the US.  Thanks for your quick reply / help @ide .

**Comment by inetkid** [comment]
workaround:
npm -s i ws
