### ISSUE TITLE
No scrollEnd apis work on expo web

### ISSUE THREAD

**Issue by Ryanjso** [expo/expo#17312]
### Summary

None of the scroll end APIs work on web for a `SectionList`, however `onMomentumScrollEnd` works on `iOS` (and maybe android, unsure)
- onMomentumScrollEnd
- onScrollEndDrag
- onScrollAnimationEnd

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

"expo": "~44.0.0"

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: ^18.0.0 => 18.0.0 
      react-dom: ^18.0.0 => 18.0.0 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.50.0
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@ryanjso/expo-issue

**Comment by brentvatne** [comment]
you can track this in the related react-native-web issue: https://github.com/necolas/react-native-web/issues/2249
