### ISSUE TITLE
[iOS] eas build fail, due to symbol not found for architecture(git lfs(Large File Storage))

### ISSUE THREAD

**Issue by jb9229** [expo/expo#17317]
### Summary

I think the framework library file used in the map is over 100m, so there is a fastlane error.
(related issue:  [https://stackoverflow.com/questions/70972588/fastlane-mapbox-framework-architecture-arm64-symbol]()

I couldn't find the option to set in the document below
[https://docs.expo.dev/submit/eas-json/](url)

Error Message:(eas build, run fastlane)
````
ld: ignoring file /Users/expo/workingdir/build/ios/Pods/NMapsMap/framework/NMapsMap.framework/NMapsMap, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
❌  Undefined symbols for architecture arm64
┌─ Symbol: _OBJC_CLASS_$_NMFCameraPosition
└─ Referenced from: objc-class-ref in libreact-native-nmap.a(RCTConvert+NMFMapView.o)

❌  ld: symbol(s) not found for architecture arm64
````
- simulater build is same(symbol(s) not found for architecture x86_64)
- local build is success

how can i solved??

### What platform(s) does this occur on?

iOS

### SDK Version

44

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.8.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.20 
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.50.0
      expo-cli: 5.3.1
    Expo Workflow: bare

### Reproducible demo

// eas.json

"alphaRelease": {
      "distribution": "internal",
      "ios": {
        "buildConfiguration": "Release",
        "scheme": "groundAlpha"
      },
    }

**Comment by lawrence-laz** [comment]
Having a similar problem, but different symbols:
```
❌  Undefined symbols for architecture arm64
┌─ Symbol: _AVMetadataObjectTypeCodabarCode
└─ Referenced from: l001 in EXBarCodeScanner(EXBarCodeScanner.o)

❌  ld: symbol(s) not found for architecture arm64


❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Not sure if such linking errors might have a common root cause, or should this be treated as a separate thing?

**Comment by brentvatne** [comment]
@lawrence-laz - you'll need to provide `expo diagnostics` info and also a link to your build page: https://docs.expo.dev/build-reference/troubleshooting/#how-to-ask-a-good-question

**Comment by jb9229** [comment]
> Having a similar problem, but different symbols:
> 
> ```
> ❌  Undefined symbols for architecture arm64
> ┌─ Symbol: _AVMetadataObjectTypeCodabarCode
> └─ Referenced from: l001 in EXBarCodeScanner(EXBarCodeScanner.o)
> 
> ❌  ld: symbol(s) not found for architecture arm64
> 
> 
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Not sure if such linking errors might have a common root cause, or should this be treated as a separate thing?

I think EAS need the lfs setting true
<img width="730" alt="스크린샷 2022-05-06 오전 9 44 00" src="https://user-images.githubusercontent.com/3200647/167049059-8cee91b1-15f1-4e59-8fa1-c8d16b355148.png">

**Comment by brentvatne** [comment]
are you using git lfs in your repo?

you can do anything you want on the machine in pre and post install hooks: https://docs.expo.dev/build-reference/how-tos/#eas-build-specific-npm-hooks - so run whatever code you need here.

**Comment by jb9229** [comment]
thank you @brentvatne 

I solved the issue using "eas-build-pre-install"

**Comment by jb9229** [comment]
@brentvatne 

Can I set iOS and Android separately?

"eas-build-pre-install-iOS": ?
"eas-build-pre-install-android": ?

pre-install hook error at android build(Due to unnecessary ios installation)
````
Script 'eas-build-pre-install' is present in package.json, running it...
yarn run v1.22.17
$ apt-get install git-lfs && git-lfs install
[stderr] E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
[stderr] E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
[stderr] error Command failed with exit code 100.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn exited with non-zero code: 100
````

**Comment by bandhavya** [comment]
Observing the same issue as https://github.com/expo/expo/issues/17317#issuecomment-1118999048 with expo sdk 45.

**Comment by charlzyx** [comment]
> Having a similar problem, but different symbols:
> 
> ```
> ❌  Undefined symbols for architecture arm64
> ┌─ Symbol: _AVMetadataObjectTypeCodabarCode
> └─ Referenced from: l001 in EXBarCodeScanner(EXBarCodeScanner.o)
> 
> ❌  ld: symbol(s) not found for architecture arm64
> 
> 
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Not sure if such linking errors might have a common root cause, or should this be treated as a separate thing?

same with you

**Comment by rafhpabustan** [comment]
> Having a similar problem, but different symbols:
> 
> ```
> ❌  Undefined symbols for architecture arm64
> ┌─ Symbol: _AVMetadataObjectTypeCodabarCode
> └─ Referenced from: l001 in EXBarCodeScanner(EXBarCodeScanner.o)
> 
> ❌  ld: symbol(s) not found for architecture arm64
> 
> 
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Not sure if such linking errors might have a common root cause, or should this be treated as a separate thing?

Exactly my error as well [SDK 45]

**Comment by hodgln** [comment]
> Having a similar problem, but different symbols:
> 
> ```
> ❌  Undefined symbols for architecture arm64
> ┌─ Symbol: _AVMetadataObjectTypeCodabarCode
> └─ Referenced from: l001 in EXBarCodeScanner(EXBarCodeScanner.o)
> 
> ❌  ld: symbol(s) not found for architecture arm64
> 
> 
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Not sure if such linking errors might have a common root cause, or should this be treated as a separate thing?

Also having this issue.

**Comment by mattmarcello** [comment]
I'll just chime in here and say I am having the exact same issue.

**Comment by mattmarcello** [comment]
Okay, so, it is important to note that simply upgrading Xcode is not sufficient here.  You need to make sure the correct version of Xcode is in your path using the `xcode-select` utility.  

You can run `npx expo-env-info` to verify that the correct version is your path and referenced by expo.

**Comment by a-eid** [comment]
having the same issue locally 

```
❌  Undefined symbols for architecture x86_64
┌─ Symbol: _AVMetadataObjectTypeCodabarCode
└─ Referenced from: l001 in EXBarCodeScanner(EXBarCodeScanner.o)


❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)



› 3 error(s), and 1 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```


```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/zeal/mobile-apps/node_modules/.bin/yarn
      npm: 8.3.1 - ~/n/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/ahmedelshentenawy/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
        Android NDK: 20.1.5948944
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 3 Bumblebee 2021.1.1 Patch 3
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 6.0.1
    Expo Workflow: bare
```

**Comment by virginia-duca** [comment]
I am having this same issue after installing expo-barcode-scanner on my react native app

```
Undefined symbols for architecture x86_64:
  "_AVMetadataObjectTypeCodabarCode", referenced from:
      l001 in EXBarCodeScanner(EXBarCodeScanner.o)
      l014 in EXBarCodeScanner(EXBarCodeScanner.o)
      l001 in EXBarCodeScanner(EXBarCodeScannerUtils.o)
      l007 in EXBarCodeScanner(EXBarCodeScannerUtils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Usually i build the trough Xcode on the simulator, but i've been getting this error when i tried to build now. I need a solution other than updating the Xcode, because I'm stuck with the 13.2.1 version, my mac can't support the updates.

**Comment by brentvatne** [comment]
@virginia-duca - you can either:

- build with eas build instead (it lets you pick the xcode version)
- roll back to an older version of expo-barcode-scanner
- use patch-package to remove the offending `AVMetadataObjectTypeCodabarCode`

**Comment by sebastienlabine** [comment]
@brentvatne could we have an option in expo-build-property to actually pick the right xcode version?

**Comment by brentvatne** [comment]
@sebastienlabine - i'm not sure i understand the question. are you using eas build or building locally? if you're building locally, install whatever version of xcode you like - config plugins have no say in that. if you're using eas build, you can pick the image to use: https://docs.expo.dev/build-reference/infrastructure/

**Comment by sebastienlabine** [comment]
@brentvatne yes, sorry. I realized I could actually change it on my CI server. I just thought an option could have been available in the expo-build-properties plugin to select the xcode version based on the project and not the server. A simple edit to the fastfile allows it.

[Fastlane documentation](https://docs.fastlane.tools/actions/xcversion/)

**Comment by toddor** [comment]
Had the same problem and couldn't update Xcode version because of an old macbook..
What worked for me was installing an older version of expo-barcode-scanner:

`yarn add expo-barcode-scanner@11.2.1`

**Comment by mguerrero-exe** [comment]
> Having a similar problem, but different symbols:
> 
> ```
> ❌  Undefined symbols for architecture arm64
> ┌─ Symbol: _AVMetadataObjectTypeCodabarCode
> └─ Referenced from: l001 in EXBarCodeScanner(EXBarCodeScanner.o)
> 
> ❌  ld: symbol(s) not found for architecture arm64
> 
> 
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Not sure if such linking errors might have a common root cause, or should this be treated as a separate thing?

Same error Here

**Comment by ngima** [comment]
Any updates on it?

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/23276565/207228008-dea19824-c7d1-4f2e-b0df-30120657eaae.png">

Having similar problem since last Friday

**Comment by mguerrero-exe** [comment]
> Had the same problem and couldn't update Xcode version because of an old macbook.. What worked for me was installing an older version of expo-barcode-scanner:
> 
> `yarn add expo-barcode-scanner@11.2.1`

It didn't worked for me either...

**Comment by ngima** [comment]
Disabling bitcode worked for me.

@mguerrero-exe you should try
https://github.com/expo/expo/issues/20440#issuecomment-1352530370

**Comment by mguerrero-exe** [comment]
> Disabling bitcode worked for me.
> 
> @mguerrero-exe you should try [#20440 (comment)](https://github.com/expo/expo/issues/20440#issuecomment-1352530370)

Nope doesn't work for me
```
Undefined symbols for architecture arm64:
  "_AVMetadataObjectTypeCodabarCode", referenced from:
      l001 in EXBarCodeScanner(EXBarCodeScanner.o)
      l014 in EXBarCodeScanner(EXBarCodeScanner.o)
      l001 in EXBarCodeScanner(EXBarCodeScannerUtils.o)
      l007 in EXBarCodeScanner(EXBarCodeScannerUtils.o)
ld: symbol(s) not found for architecture arm64
```

**Comment by delfouly** [comment]
@toddor this worked for me

**Comment by delfouly** [comment]
> Had the same problem and couldn't update Xcode version because of an old macbook.. What worked for me was installing an older version of expo-barcode-scanner:
> 
> `yarn add expo-barcode-scanner@11.2.1`

this worked for me
