### ISSUE TITLE
[expo-image-picker] Crash when trying to call launchCameraAsync to get an image

### ISSUE THREAD

**Issue by chimame** [expo/expo#17347]
### Summary

The application crashes when I introduce `expo-image-picker` and call launchCameraAsync as specified in the [documentation](https://docs.expo.dev/versions/latest/sdk/imagepicker/).

The camera starts immediately after calling launchCameraAsync. Then the application crashes when I take a picture with the camera and select the image. So it works fine until the camera is launched, but crashes when it tries to acquire an image.

As per this [issue](https://github.com/expo/expo/issues/9101), if I go back without taking a photo after launching the camera once and then launch the camera again to take a photo, I may be able to get it.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 3.0.2 - /usr/bin/fish
    Binaries:
      Node: 16.13.1 - /tmp/yarn--1651720947618-0.5496521237718734/node
      Yarn: 1.22.17 - /tmp/yarn--1651720947618-0.5496521237718734/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

https://github.com/chimame/react-native-camera-crash-sample

I submit the code for the crashing sample I created.
It crashes both when using Expo Go and when built with EAS.

**Comment by mayromyller** [comment]
I'm having the same problem here. In my case, I only have this problem when I use a higher resolution in megapixels. Have solution?

**Comment by matias1543** [comment]
I have the same problem in sdk45. My device is a Motorola E20.

**Comment by chimame** [comment]
Is there something wrong with using the camera in expo?

**Comment by Nxtra** [comment]
Seeing the same behavior on the Samsung A20 here.
Camera is just not opening on `launchCameraAsync`

**Comment by joebarrero** [comment]
> Hello everyone, I had the same problem, in several Samsung devices, in addition to several other devices as well.
> 
> I ended up finding a solution, which took the permissions directly from the React Native package and implemented it in my app, and to my surprise and relief, it worked perfectly, both running through the expo and also after the build. Following example code:
> 
> ```
> import { PermissionsAndroid } from "react-native"
> 
> async function pickImageFromCamera() {
>   const granted = await PermissionsAndroid.request(
>     PermissionsAndroid.PERMISSIONS.CAMERA
>   )
> 
>   if (granted === PermissionsAndroid.RESULTS.GRANTED) {
>     setOpenCamera(true)
> 
>     const result = await ImagePicker.launchCameraAsync({
>       mediaTypes: ImagePicker.MediaTypeOptions.Images,
>       aspect: [4, 3],
>       base64: true,
>       quality: 1
>     })
> 
>     if (!result.cancelled) {
>      // your logic
>     }
>   }
> }
> ```
> 
> Hope this helps.

Adding a different permissions request didn't help me.  I'm experiencing the same error after ensuring that I have the permissions.

**Comment by federicogomezlara** [comment]
We're having this issue on a Realme 8 5G, our application crashes after taking a picture

**Comment by meianuraluca** [comment]
I have the same problem on all the devices I tried, both ios and android. When I try to open the gallery, I get the following error: **Cannot read property 'launchImageLibraryAsync' of undefined** . I tried with other methods of the package and it is the same situation. I can only access hooks and enums from ImagePicker

Expo Sdk: 47
expo-image-picker:14.0.2

Has anyone found a solution??

**Comment by wesleyrafael** [comment]
Did anyone find a workaround? I'm having the same issue

**Comment by siddharth21s** [comment]
> I have the same problem on all the devices I tried, both ios and android. When I try to open the gallery, I get the following error: **Cannot read property 'launchImageLibraryAsync' of undefined** . I tried with other methods of the package and it is the same situation. I can only access hooks and enums from ImagePicker
> 
> Expo Sdk: 47 expo-image-picker:14.0.2
> 
> Has anyone found a solution??

I'm facing the same issue with SDK v49 and image-picker version: ~14.3.2

**Comment by mayromyller** [comment]
Please try this:

Comment on the part that asks for permission. When we only use `ImagePicker.launchCameraAsync` it already requests permission. I did this and managed to fix it 100%.

```
async function pickImageFromCamera() {
    // const { granted } = await ImagePicker.requestCameraPermissionsAsync()

    // if (granted) {
      const result = await ImagePicker.launchCameraAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        aspect: [4, 3],
        base64: true,
        quality: 0.5
      })
    // }
  }
```

**Comment by ARIARCHI-MZ** [comment]
Hi everyone I have an issue for **ImagePicker.launchCameraAsync** with###  IOS version **17 and expo SDK 50**.
both getCameraPermissionsAsync and getMediaLibraryPermissionsAsync are **granted** but ImagePicker.launchCameraAsync doesnt executed.
Camera opens for less than a second and then closes automatically , is there any solution for it?

**Comment by marko-mazibrada-codeup** [comment]
> Hi everyone I have an issue for **ImagePicker.launchCameraAsync** with### IOS version **17 and expo SDK 50**. both getCameraPermissionsAsync and getMediaLibraryPermissionsAsync are **granted** but ImagePicker.launchCameraAsync doesnt executed. Camera opens for less than a second and then closes automatically , is there any solution for it?

Same here, we use camera inside react-query and on ios it closes immediately but on android it works as expected

`import { useMutation } from '@tanstack/react-query';
import { randomUUID } from 'expo-crypto';
import * as ImagePicker from 'expo-image-picker';

import { useUploadImage } from './useUploadImage';
import { useGetPresignedUrl } from '../query/useGetPresignedUrl';

import { ImageType } from '@/components/molecules/UploadCard';
import { prepareImageUploadPayload } from '@/utils/upload.utils';

const actionsMap = {
  pick: ImagePicker.launchImageLibraryAsync,
  take: ImagePicker.launchCameraAsync
};

type MutateType = {
  action: 'pick' | 'take';
  img?: ImageType;
};

export const usePickOrTakeImage = (
  setIsVisible: React.Dispatch<React.SetStateAction<boolean>>,
  setImage: React.Dispatch<React.SetStateAction<ImageType | undefined>>
) => {
  const { mutateAsync: getPresignedUrl } = useGetPresignedUrl();
  const { mutateAsync: uploadImage } = useUploadImage();

  return useMutation({
    mutationFn: async ({ action }: MutateType) => {
      setIsVisible(false);

      // No permissions request is necessary for launching the image library
      const result = await actionsMap[action]({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        aspect: [105, 150],
        quality: 1
      });

      if (!result.canceled) {
        const blob = await prepareImageUploadPayload(result.assets[0]);
        // @ts-ignore
        const imageName = `${randomUUID()}_${blob?.data?.name ?? result.assets[0].fileName}`;
        const selectedImage = {
          s3Id: imageName
        };

        setImage(selectedImage);
        const presignedUrl = await getPresignedUrl(imageName);
        if (!presignedUrl) throw new Error('Failed to get presigned URL');

        return uploadImage({
          presignedUrl,
          blob,
          fileName: selectedImage.s3Id
        }).then(r => selectedImage);
      }
    }
  });
};
`

When we try basic example in our app, without mutations it works as expected

**Comment by achuinard** [comment]
On Android, I oddly found that removing `react-native-keyboard-controller` and the corresponding `<KeyboardProvider>`, my app did not crash anymore when returning from the camera.
