### ISSUE TITLE
device supports, but apk only supports armeabi-v7a

### ISSUE THREAD

**Issue by aprilmintacpineda** [expo/expo#1734]
#### What I am doing

- I detached my project to expoKit with `exp detach`.
- I opened `Android/` with my Android Studio.

###### Fast forward to successful build.

Note that I did not change anything here but Android Studio asked me to download and install an SDK, which I did that led to successful build.

- I clicked on `run icon`.
- AVD launched, I can see my hardware device there with a message besides it that says `device supports, but apk only supports armeabi-v7a`.

I honestly don't know what's causing this error. My Physical device is a VivoV9 with android version 8.1.0

Any help would be appreciated. Thanks!

**Comment by esamelson** [comment]
Hi @aprilmintacpineda - have you [enabled USB debugging](https://developer.android.com/studio/debug/dev-options) on your device?

**Comment by ckitterl** [comment]
> what is the answer??? I have enabled usb debugging.

If you forgot to install OEM USB drivers? see https://developer.android.com/studio/run/oem-usb

**Comment by FlimsyBanana** [comment]
I had this same issue as well, and simply turning usb debugging off, disconnecting the phone, turning it back on, and reconnecting to the computer worked fine, though I am not completely sure as to why this works.
