### ISSUE TITLE
Expo.io Availability Issues from Russia

### ISSUE THREAD

**Issue by seenickcode** [expo/expo#1735]
I just wanted to note something that may affect adoption by developers in Russia. I'm currently on a family trip here in Russia and noticed either our ISP here or the powers that be here have blacklisted expo.io. I have to use a VPN to access this website. I wanted to teach my brother-in-law here React Native using Expo but because using a VPN is so slow, I will have to skip Expo.

**Comment by nicknovitski** [comment]
It's not expo.io specifically, but the IPs owned by cloud services which are used by us, or more specifically, by Telegram. See #1717
