### ISSUE TITLE
[SDK 45] EAS build for iOS failing with native file error

### ISSUE THREAD

**Issue by thecoorum** [expo/expo#17360]
### Summary

After upgrading to beta SDK 45 EAS build failing almost at the end on compiling `AppDelegate.m`

```
(ios/track/AppDelegate.m:40:24)

  38 | - (RCTBridge *)initializeReactNativeApp:(NSDictionary *)launchOptions
  39 | {
> 40 |   RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];
     |                        ^ definition of 'EXReactDelegateWrapper' must be imported from module 'ExpoModulesCore' before it is required
  41 |   RCTRootView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"main" initialProperties:nil];
  42 |   rootView.backgroundColor = [UIColor whiteColor];
  43 |   UIViewController *rootViewController = [self.reactDelegate createRootViewController];

❌  (ios/track/AppDelegate.m:82:49)

  80 |   return [[EXDevLauncherController sharedInstance] sourceUrl];
  81 |   #else
> 82 |   return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
     |                                                 ^ no visible @interface for 'RCTBundleURLProvider' declares the selector 'jsBundleURLForBundleRoot:fallbackResource:'
  83 |   #endif
  84 |  #else
  85 |   return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK 45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.18 - ~/.yvm/shim/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /Users/thecoorum/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 27, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: next => 45.0.0-beta.9
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.1 => 0.68.1
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

-

**Comment by Kudo** [comment]
hi there! for sdk 45, the file should be AppDelegate.mm. if you are running with a managed workflow, it's worth to try `expo prebuild --clean` command for re-generating the android and ios folders with updated contents.

**Comment by thecoorum** [comment]
Hey @Kudo, I found that change while was taking a look upgrade helper. Thanks for quick reply
