### ISSUE TITLE
Inverted QR code is not recognized by BarcodeScanner

### ISSUE THREAD

**Issue by jonathanort** [expo/expo#1736]
### Steps to reproduce
1. Run expo snack on Android device
https://snack.expo.io/BJlFFcp2g

2. Try scanning this code using an Android device
![generate](https://user-images.githubusercontent.com/5676848/39757495-4e5e5cce-52cd-11e8-8360-9c1ebd37d4d4.png)

### Expected behaviour
The QR code should be scanned and display the correct result

### Actual behaviour
The QR code is not recognized

**Comment by EvanBacon** [comment]
It works if I hold my phone upside down... I'm not seeing anything in the source code that would prevent this. I'll keep digging though https://github.com/expo/universe/blob/8e06a7c4b190e45ca0ec75612405381d87fde253/exponent/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/components/barcodescanner/BarCodeScannerViewFinder.java

**Comment by xiang510** [comment]
I also got this question.Please

**Comment by EvanBacon** [comment]
BarCode module has been rewritten. Closing.

**Comment by danikane** [comment]
@EvanBacon Thanks a lot! Is this change going in SDK 31?

**Comment by jorgeluisrezende** [comment]
Sorry for revive this issue, but, i'm still having this problem... i'm using the expo sdk version 32
