### ISSUE TITLE
getPurchaseHistory return empty array

### ISSUE THREAD

**Issue by jphorvath** [expo/expo#17375]
### Summary

The issue reported in 'getPurchaseHistory return empty array #11105' was not solved.

On both platform iOS and adroid getPurchaseHistory returns an empty array => []

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: bare

### Reproducible demo

import {
  connectAsync,
  getPurchaseHistoryAsync,
} from 'expo-in-app-purchases';

componentDidMount() {
       await connectAsync();
 
       const {
              responseCode,
              results,
              errorCode,
       } = await getPurchaseHistoryAsync({ useGooglePlayCache: false });
 
       console.log(responseCode) // 0
       console.log(results) // []

 };

**Comment by Nebel69** [comment]
Wrap RNIap.getPurchaseHistory() around initConnection() and an endConnection() call. Perhaps also give RNIap.finshTransaction more time to finish before requesting the purchase history to make sure the latest purchases are included.
[Choice ADVANTAGE](https://www.choiceadvantage.one/)
