### ISSUE TITLE
[SDK 45.0.1][expo-dev-client] No reconnect to Metro possible, blank screen after reload

### ISSUE THREAD

**Issue by hirbod** [expo/expo#17389]
### Summary

SDK 45.0.1 and expo-dev-client 0.9.5 handled all the long lasting DX issues and crashes. Thanks a ton.
After upgrading, I found a small issue, which is a bit annoying:

1) Open your app with dev-client
2) Select your server to load your bundle
3) Use your app
4) Background your app
5) Wait 2 or 3 minutes (keep app backgrounded)
6) CLI will output 
```
Cannot connect to Metro.

Try the following to fix the issue:
- Ensure that Metro is running and available on the same network
- Ensure that the Metro URL is correctly set in AppDelegate
```
7) This is expected, since the OS killed the Socket connection.
8) Open developer menu and hit "reload"
9) App will be blank and white

I am not sure why expo-dev-client can't reconnect to Metro in first place. I am also handling WebSockets in my App which can recover after a day. It looks like there is no real integrated mechanism to try to reconnect to the running CLI instance.

I can just restart the App and everything is fine, but doing so I always lose my current state and can't test backgrounded scenarios correctly, because Metro connection is lost.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

0.9.5

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.1 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/opt/node@14/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.51.0
      expo-cli: 5.4.3
    Expo Workflow: bare
```

### Reproducible demo

None. Grab any with current dev-client and follow my steps.

**Comment by raajnadar** [comment]
I think this is similar bug report? https://github.com/expo/expo/discussions/17089

**Comment by hirbod** [comment]
Might be related, indeed
