### ISSUE TITLE
[SDK 45] android block permissions warning looped

### ISSUE THREAD

**Issue by ivopr** [expo/expo#17380]
### Summary

Now we can remove permissions from our apps with `android.blockedPermissions`, that's fantastic. but what isn't fantastic is that with it came also a loop in the warning `» android: block-permissions: No permissions provided` making it be spammed in the terminal.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.10 Arch Linux
      Shell: 5.8.1 - /usr/sbin/zsh
    Binaries:
      Node: 16.15.0 - /usr/bin/node
      Yarn: 1.22.18 - /usr/bin/yarn
      npm: 8.8.0 - ~/ictio/app/node_modules/.bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.0 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

Create a new project, add a config plugin (such as `expo-image-picker`), leave `android.blockedPermissions` empty or don't define it. You should be able to see the message at least 2 times when initiating a build, and an infinite number of times when running the app with `expo start`.

[repro on upgraded project from SDK 44](https://github.com/demonicat/karma/tree/506b1d4123dcdae218202b57f798e2746e70d036)
[repro on clean initialized project on SDK 45](https://github.com/ivopr/expo-17380)

**Comment by Kakasi-Daniel** [comment]
I'm occurring the same issue.

**Comment by esegebart** [comment]
Experiencing the same issue.

**Comment by kbrandwijk** [comment]
I tried to reproduce this on a newly initialized SDK 45 project, but I'm not seeing the warning on build, prebuild, or start. Could you share a reproducible example?

**Comment by ivopr** [comment]
I've tried from a blank app and upgrading an old app from 44, and both didn't do that, so you're correct. Next, I'll try with some native modules. The project I'm working that is giving me this can't be shared, but the main difference between the ones I tested to it is the native modules, such as `expo-image-picker`, `expo-location`, `react-native-firebase` and `react-native-google-sign-in`. I'll give you a return in a bit.

**Comment by ivopr** [comment]
Hey, @kbrandwijk, the issue occurs exactly as I pointed on the previous comment.
[here](https://github.com/demonicat/karma/tree/506b1d4123dcdae218202b57f798e2746e70d036) is a repro. This project was upgraded from 44, not clean inited. I'll test with the clean inited one now.

**Comment by palatshq** [comment]
Hi, I'm trying to release a new version of our app with an updated SDK and I get the same warning. Will it affect our product?

**Comment by ivopr** [comment]
@palatshq AFAIK it is just a warning. Was seemingly solved (I didn't test, but looking at the code on the linked PR, it makes me believe that it was) on the linked PR. Shouldn't affect any funcion of your app, since it actually is just an if made to trigger the warning. Resuming in less words. it's safe to ignore it, Just like 90% of the warnings out there. And no, I didn't search for a papear stating this percentage, it's purely make believe.

**Comment by FatmaMahmoud698** [comment]
after I updated my SDK I can see this warring, what should I do to solve it?

**Comment by ivopr** [comment]
@FatmaMahmoud698 just wait a bit for the next release.

**Comment by andrconstruction** [comment]
I have a build problem for ios with the eas
![image](https://user-images.githubusercontent.com/7435330/168336620-42643170-2fa9-4964-a880-c8b6402b78a3.png)

**Comment by brentvatne** [comment]
@andrconstruction - can you share a link to your build page? also this doesn't appear to be what is reported in thi sissue, there is no 'looping' going on here there is a single warning :)

**Comment by andrconstruction** [comment]
> @andrconstruction - can you share a link to your build page? also this doesn't appear to be what is reported in thi sissue, there is no 'looping' going on here there is a single warning :)

https://expo.dev/accounts/andrace/projects/kdapp/builds/cf9e824b-2315-4e5d-8f67-1736944dd31e

**Comment by ivopr** [comment]
Hey, @kbrandwijk, @brentvatne, I noticed that yesterday version 5.4.4 of expo-cli was released, on the changelog it includes the PR that appeared to fix this. After updating the cli today, I still get
```
~/i/app ❯❯❯ yarn wsl --dev-client                                                                                     main ✱ ◼
yarn run v1.22.18
$ REACT_NATIVE_PACKAGER_HOSTNAME=$(netsh.exe interface ip show address "Wi-Fi" | grep 'IP Address' | sed -r 's/^.*IP Address:\W*//') expo start --dev-client
Starting project at /home/ivopr/ictio/app
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
Developer tools running on http://localhost:19002
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
Starting Metro Bundler
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▀▀▄▄▀▀▄ ▄▀█▄█▄██▄██▀█ ▄▄▄▄▄ █
█ █   █ █▀███ ▄█▄▀▀    █▀█▀█▀ █ █   █ █
█ █▄▄▄█ █▄▄█▀▀██ ▄ ▄▄█▄ ▄ ▄▀█▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ ▀▄█ ▀ █ █▄█▄█▄█ █ █▄▄▄▄▄▄▄█
█ ▄▀▀█▄▄ █ █▄▀▀██ ▄▄▀ █▄ ▄▄ ▀█▀██ ▄▀███
█ █  █▄▄█ ▄▄█▀ ▄▄▄█▄▀▀▄▄▀ █ ▄ ██▄█▀▄  █
███  █▀▄██▀▀▄▄▄█▄ █▄▀▄█▀ █▀█  ▄▄ █▀█▄██
█ ▀▄█▄▄▄▀█ ▀ ▄██▀██ █▀▄▀██▄  █ █▄█ ▀ ▄█
███▀ ▀█▄▀▄█▄▄▀▀▀█▄▄▄▀▄██▀█▄   █▄▀▄▄ ███
██▀▀▀██▄▀▄▀ ▄▀▀█▄█▄█▄█▄▀ █▄█▄▀▀█▄█▀▄▄ █
█▄▄ ▄▀ ▄▀██▄█▄█ ▄█▄ ▀ ██ ▀ ▀ █▄▄   ▄▀▄█
█▄█▀▄▄ ▄▀ ▄█ ▄█▀▀▀██▀▀█▀▀██ ▄▀  ▀█▀▄▄ █
█▀▀▄█▀ ▄█▀▄▄█▀  █▄█▄▄ ▄█▀ ██  ▀▄▀█▄█ ██
█ █▄ ▀▀▄ █▄▀█▀  ▄ ▄▄▀▀▄██▄▄█▄▄█▀ ▀    █
█▄██▄██▄█ █ █▄█▄ ▄█▀▀▄██▀█ ▄█ ▄▄▄ ▄ ▄▄█
█ ▄▄▄▄▄ █  █▀▄▄ ▄▄▄▄▄▀▄▀ ▄▄██ █▄█ ▀▄█ █
█ █   █ ██  ▄▀▀█▀  ▄▀▀██ ▄   ▄  ▄▄ ▄▀ █
█ █▄▄▄█ █▀ ██▀ ▄▄██ ▀▀█████▀█ ▄▀ █▀▄▄ █
█▄▄▄▄▄▄▄█▄▄█▄▄▄█▄██▄▄▄▄█▄▄███▄▄▄██▄██▄█

› Metro waiting on exp+ictiobiometria://expo-development-client/?url=http%3A%2F%2F10.0.0.105%3A8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu
› Press d │ show developer tools
› shift+d │ toggle auto opening developer tools on startup (disabled)

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Started Metro Bundler
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
» android: block-permissions: No permissions provided
Android Bundling JavaScript [================================                                ] 49%
```

Not sure if it's util, but these are the plugins I have declared on `app.config.js`
```
    "@react-native-firebase/app",
    "@react-native-firebase/crashlytics",
    "@react-native-firebase/perf",
    "@react-native-google-signin/google-signin",
    "expo-image-picker",
    "expo-location",
```

Also, this is something I've found now, having for example
```
android: {
    blockedPermissions: ["ACCESS_COARSE_LOCATION"],
    permissions: ["CAMERA", "ACCESS_FINE_LOCATION", "FOREGROUND_SERVICE"],
    ...
  },
```
will still trigger the warnings

**Comment by snndmnsz** [comment]
i am also having the same problem. It's constantly printing in every 5 sec  in terminal and I can't stop it. My mobile app works fine tho

![pic](https://user-images.githubusercontent.com/42818330/169920185-f8b44c04-efe4-4759-8723-24d41b0259a1.png)

**Comment by PopAna1997** [comment]
I'm still looking too for the solution :( it's very uncomfortable because this warning keep showing in the console after each re-render of the component

**Comment by brentvatne** [comment]
I can't reproduce this with expo-cli@5.4.7.

If you are experiencing this in your project then it is likely that you have a version of `@expo/config-plugins` installed that is lower than `@expo/config-plugins@4.1.5`. You can run `npm why @expo/config-plugins` to see where that comes from.

**Comment by snndmnsz** [comment]
As you said i did `npm i @expo/config-plugins` again and the yellow errors are no longer visible. Thank you @brentvatne .....

**Comment by pycraft114** [comment]
@brentvatne same thing happens even when using 4.1.5 config plugins, after the expo build process. I build android packages through expo build no eas build. does that affect this behaviour?
