### ISSUE TITLE
expo@45 expo-av@11.2.3 and expo-camera@12.1.2 not work on iOS

### ISSUE THREAD

**Issue by zhiqingchen** [expo/expo#17395]
### Summary

just use Video sample code, but initWithEXAV didn't called.

downgrade to 44 or use Android, it works fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment
```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v16.10.0/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.1
      react: 17.0.2 => 17.0.2
      react-native: 0.68.1 => 0.68.1
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: bare
```
### Reproducible demo

https://github.com/zhiqingchen/expo-reproduce

**Comment by zhiqingchen** [comment]
![image](https://user-images.githubusercontent.com/1876158/167291871-81f6ed1c-9349-44c1-a032-fa83c3438643.png)

**Comment by zhiqingchen** [comment]
```jsx
import * as React from 'react';
import { View, StyleSheet, Button } from 'react-native';
import { Video, AVPlaybackStatus } from 'expo-av';

export default function App() {
  const video = React.useRef(null);
  const [status, setStatus] = React.useState({});
  return (
    <View style={styles.container}>
      <Video
        ref={video}
        style={styles.video}
        source={{
          uri: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
        }}
        useNativeControls
        resizeMode="contain"
        isLooping
        onPlaybackStatusUpdate={status => setStatus(() => status)}
      />
      <View style={styles.buttons}>
        <Button
          title={status.isPlaying ? 'Pause' : 'Play'}
          onPress={() =>
            status.isPlaying ? video.current.pauseAsync() : video.current.playAsync()
          }
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
  video: {
    alignSelf: 'center',
    width: 320,
    height: 200,
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

```

**Comment by hirbod** [comment]
I am a heavy user of expo-av and its working perfectly on iOS and Android.

**Comment by zhiqingchen** [comment]
> I am a heavy user of expo-av and its working perfectly on iOS and Android.

latest version？

**Comment by hirbod** [comment]
Yes. I also helped a lot for SDK 45 beta testing and fixing.

**Comment by zhiqingchen** [comment]
@hirbod  Thanks for the reply.
That's strange, do you know if snack.expo.dev can provide the Expo v45 environment, It should be possible to reproduce.

**Comment by hirbod** [comment]
I think SDK45 support for snack is coming soon.

**Comment by fobos531** [comment]
I'm experiencing the exact same issue. It's like the component don't get mounted at all, since the the video doesn't even start loading. It's even more confusing as I know that @hirbod makes really extensive use of expo-av and it seems to work perfectly for him.

**Comment by hirbod** [comment]
I will investigate your repro later and have a look what might be wrong

**Comment by Poheart** [comment]
Had the exactly the same issues as well on iOS with expo-av@11.2.3 /w SDK 45 and Hermes, android works fine.

**Comment by hirbod** [comment]
I just made a repro with EXPO SDK 45 locally, using Expo GO and a custom dev client as well. I could not reproduce this. The App is running and the video is playing. I am not sure if you guys made some mistakes with the bare project (the expo-modules-core part is crucial). 

https://user-images.githubusercontent.com/504909/167312356-b507b412-35de-459f-bddd-13bfcafb8556.MP4

Here is my repro as a download. https://we.tl/t-wiy7HZrdbG

**Comment by fobos531** [comment]
> I just made a repro with EXPO SDK 45 locally, using Expo GO and a custom dev client as well. I could not reproduce this. The App is running and the video is playing. I am not sure if you guys made some mistakes with the bare project (the expo-modules-core part is crucial).
> 
>  RPReplay_Final1652037727.MP4 
> Here is my repro as a download. [we.tl/t-wiy7HZrdbG](https://we.tl/t-wiy7HZrdbG)

Just tested on a fresh project in Expo Go, and that specific configuration seems to work.

expo-modules-core part? Which part is that? My current setup is managed workflow with a dev client.

**Comment by hirbod** [comment]
Ok, managed workflow with dev client should handle the setup automatically.

**Comment by fobos531** [comment]
Okay, I managed to reproduce it. Repro here: 

https://github.com/fobos531/expoav-repro

What I did is: take @hirbod's [we.tl/t-wiy7HZrdbG](https://we.tl/t-wiy7HZrdbG) repro.
Execute:
```
expo install expo-dev-client
```

Add `import 'expo-dev-client'` to App.js
Created a developmentClient build using EAS.
Tried running the code in the dev client. Same issue as described here in this thread.

I don't know if it's device specific or something else - the phone I'm testing on is an iPhone 12.

**Comment by hirbod** [comment]
What happens when you do not import expo dev client? (It's recommended but not required to import it)

**Comment by hirbod** [comment]
I followed @fobos531 steps and I was able to reproduce the issue. Need to dig a bit deeper. Super odd that my package works and yours not. Main difference I see at first sight was dev-client + I am using hermes and you not. I will test out some scenarios

**Comment by hirbod** [comment]
Ok, some more findings

```tsx
  useEffect(() => {
    video.current.loadAsync({
      uri: "https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
    });
  }, []);
```

Does load the video. So we have an issue with the initial load.

**Comment by hirbod** [comment]
Looks like that I totally forgot that I was also fighting with a regression, lol
https://github.com/expo/expo/pull/17036

See my comment 10 days ago. My findings have been that I could not load a video without calling `loadAsync`.
@bbarthec @Pickleboyonline did we messed up something?

**Comment by zhiqingchen** [comment]
> Looks like that I totally forgot that I was also fighting with a regression, lol [#17036 (comment)](https://github.com/expo/expo/pull/17036#issuecomment-1113206489)
> 
> See my comment 10 days ago. My findings have been that I could not load a video without calling `loadAsync`. @bbarthec @Pickleboyonline @barthap did we messed up something?
> 
> The reason why this slipped through for me was, that I am loading my videos imperatively and not declaratively (only one spot used to load it via source prop, which did indeed trigger a regression for me, but I did not investigate this further)
> 
> So a workaround for all of you folks right now is to use `loadAsync` until loading via prop is fixed.

Nice job.
I found the same problem with the camera component, is it the same reason?

**Comment by TomCorvus** [comment]
Hi here,
I have the same problem with `expo-camera: ~12.2.0` since I update Expo to SDK 45.
I changed nothing but after ask me permissions, the camera doesn't launch.
Everything works fine on Android.

**Comment by hirbod** [comment]
No, expo-camera should not be related to this. There might be something else going on. I am not even sure if the last PR was the cause or something else between expo-av 11.1 and 11.2.3

I am not using expo-camera though, can't help here

**Comment by zhiqingchen** [comment]
I found that all props of video component are not working, not just source prop, it should be a generic problem.

**Comment by radko93** [comment]
I can reproduce this in bare React Native app as well (RN 0.68.2).

**Comment by brentvatne** [comment]
this is resolved with `expo@45.0.2` - thank you for the report!

**Comment by mephisto83** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/7797183/167974535-c414832b-9088-4044-bd61-0a7a0837638c.png">
That doesn't seem to exist

**Comment by brentvatne** [comment]
@mephisto83 - sdk 45.0.0 uses expo@^45.0.0. the expo package version != sdk version. open your package.json and change the "expo" version to ^45.0.2
