### ISSUE TITLE
[android] target SDK version issues warning on Play Store

### ISSUE THREAD

**Issue by skabbes** [expo/expo#1739]
This is just basically an FYI, when submitting new builds to the Google Play Store, this warning is issued:

<img width="938" alt="screenshot 2018-05-09 13 07 12" src="https://user-images.githubusercontent.com/592178/39831550-7c5b4a48-538a-11e8-8d2c-7fe43350ec5f.png">

> Your app currently targets API level 25 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance.

Starting August 2018, seems like Google will prevent new apps, and November 2018 they will prevent app updates.

[This](https://developer.android.com/distribute/best-practices/develop/target-sdk) was linked in the warning message for more details.

**Comment by nicknovitski** [comment]
Thanks!  We are planning to update the the `targetSdkVersion` to 26 by August.
