### ISSUE TITLE
[expo-image-picker] [android only] EXIF/lat-lng data not being pulled

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#17399]
### Summary

Seems like when we want to get LAT+LNG information from a photo taken with Android (since API leven 29, Android 10), using `expo-image-picker`, it doesn't work anymore (not even adding `ACCESS_MEDIA_LOCATION` in the permissions).

You can get more information about this bug in:
- https://github.com/expo/expo/pull/16541 (PR kiiiiind of a biiiiit related)
- https://github.com/expo/expo/issues/16548 (issue associated to the PR)

I would say the most important information is here: https://github.com/expo/expo/pull/16541#issuecomment-1060959583, in the first point.

> the current way of requesting location from EXIF tags in expo-image-picker (see ExifDataHandler class in ImagePickerUtils.kt and exifTags in ImagePickerConstants.kt) doesn't work any longer. Reading the location is now more complex, you can see the putAssetInfo() in AssetUtils.kt in expo-media-library for the working implementation.

So... In some way, we have to move the complex-logic from `expo-media-library` (I guess) to `expo-image-picker`, in order to be able to get the exif data.

We also have another workaround, but currently it's not doable because of a lack of an `id` in `expo-media-picker`. Check the full description I left in this comment: https://github.com/expo/expo/issues/16548#issuecomment-1116808876
To sum up the comment: `expo-media-picker` doesn't provide us the `exif/lat-lng` data, but we could get it using `MediaLibrary.getAssetInfoAsync`. The problem is that `MediaLibrary.getAssetInfoAsync` is asking for an `assetId`, and `ImagePicker.launchImageLibraryAsync` is not retrieving any kind of `assetId`.

As a temporal workaround, seems like I will have to migrate the whole "upload file" flow from `expo-image-picker` to `expo-media-library`. Right?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44 (and probably 45. will test it soon)

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.3.2 - ~/.nvm/versions/node/v14.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 27, 31
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 27.0.3, 28.0.3, 29.0.2
        System Images: android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed
```

### Reproducible demo

https://snack.expo.dev/@brodanoel/no-exif

**Comment by BrodaNoel** [comment]
@barthap thanks for the quick response!

A workaround with path+eas would be super awesome, honestly.

The only problem is that I don't have knowledge in iOS nor Android. I could only help you in the JS part, so, I won't be able to help you to help me that much hehehe.

But... if you tell me: "replace this and this with this and this", I should be able to modify everything and create the patchs (I already have some patch for some issues I have with Facebook login, so, I already have that knowledge).

**Comment by barthap** [comment]
Ok, I provided a quick patch, _it turned out to be more tricky than I initially thought, due to some weird URI EXIF permissions on Android, left some comments in the diff_

The most important job is done for `Android >= Q` by the `Bundle.putExifLocationForUri()` function at the bottom of the diff. If something's not working, that's the first place to look for problems.

<details>
<summary>Here's the diff (click to unfold)</summary>

```diff
diff --git a/node_modules/expo-image-picker/android/src/main/AndroidManifest.xml b/node_modules/expo-image-picker/android/src/main/AndroidManifest.xml
index 794d6e15ac..831aaecafc 100644
--- a/node_modules/expo-image-picker/android/src/main/AndroidManifest.xml
+++ b/node_modules/expo-image-picker/android/src/main/AndroidManifest.xml
@@ -7,6 +7,7 @@
     <!-- Required for picking images from camera roll -->
     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
+    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
 
     <application>
       <activity
diff --git a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerConstants.kt b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerConstants.kt
index 3df8fd4af2..70a5200700 100644
--- a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerConstants.kt
+++ b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerConstants.kt
@@ -143,9 +143,10 @@ object ImagePickerConstants {
     arrayOf("string", ExifInterface.TAG_GPS_H_POSITIONING_ERROR),
     arrayOf("double", ExifInterface.TAG_GPS_IMG_DIRECTION),
     arrayOf("string", ExifInterface.TAG_GPS_IMG_DIRECTION_REF),
-    arrayOf("double", ExifInterface.TAG_GPS_LATITUDE),
+    // commented-out from here, they're added in other places
+//    arrayOf("double", ExifInterface.TAG_GPS_LATITUDE),
     arrayOf("string", ExifInterface.TAG_GPS_LATITUDE_REF),
-    arrayOf("double", ExifInterface.TAG_GPS_LONGITUDE),
+//    arrayOf("double", ExifInterface.TAG_GPS_LONGITUDE),
     arrayOf("string", ExifInterface.TAG_GPS_LONGITUDE_REF),
     arrayOf("string", ExifInterface.TAG_GPS_MAP_DATUM),
     arrayOf("string", ExifInterface.TAG_GPS_MEASURE_MODE),
diff --git a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
index 3e84862370..9b457a8e37 100644
--- a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
+++ b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
@@ -1,12 +1,15 @@
 package expo.modules.imagepicker
 
 import android.Manifest
+import android.annotation.SuppressLint
 import android.app.Activity
 import android.content.Context
 import android.content.Intent
+import android.content.pm.PackageManager
 import android.graphics.Bitmap
 import android.media.MediaMetadataRetriever
 import android.net.Uri
+import android.os.Build
 import android.os.Bundle
 import android.provider.MediaStore
 import android.util.Log
@@ -167,7 +170,8 @@ class ImagePickerModule(
           putExtra(Intent.EXTRA_MIME_TYPES, arrayOf("image/*", "video/*"))
         }
       }
-
+      // if it does not work, try replacing with ACTION_OPEN_DOCUMENT
+      // read about the difference here: https://stackoverflow.com/questions/36182134/what-is-the-real-difference-between-action-get-content-and-action-open-document
       action = Intent.ACTION_GET_CONTENT
     }
 
@@ -178,14 +182,43 @@ class ImagePickerModule(
 
   //region helpers
 
-  private fun getMediaLibraryPermissions(writeOnly: Boolean): Array<String> {
-    return if (writeOnly) {
-      arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE)
-    } else {
-      arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE)
+  private fun getManifestPermissions(context: Context): Set<String> {
+    val pm: PackageManager = context.packageManager
+    return try {
+      val packageInfo = pm.getPackageInfo(context.packageName, PackageManager.GET_PERMISSIONS)
+      packageInfo.requestedPermissions?.toSet() ?: emptySet()
+    } catch (e: PackageManager.NameNotFoundException) {
+      Log.e("expo-media-library", "Failed to list AndroidManifest.xml permissions")
+      e.printStackTrace()
+      emptySet()
     }
   }
 
+  /**
+   * Checks, whenever an application represented by [context] contains specific [permission]
+   * in `AndroidManifest.xml`:
+   *
+   * ```xml
+   *  <uses-permission android:name="<<PERMISSION STRING HERE>>" />
+   *  ```
+   */
+  private fun hasManifestPermission(context: Context, permission: String): Boolean =
+    getManifestPermissions(context).contains(permission)
+
+  @SuppressLint("InlinedApi")
+  private fun getMediaLibraryPermissions(writeOnly: Boolean): Array<String> {
+    // ACCESS_MEDIA_LOCATION should not be requested if it's absent in android-manifest
+    val shouldAddMediaLocationAccess =
+      Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q &&
+        hasManifestPermission(context, Manifest.permission.ACCESS_MEDIA_LOCATION)
+
+    return listOfNotNull(
+      Manifest.permission.WRITE_EXTERNAL_STORAGE,
+      Manifest.permission.READ_EXTERNAL_STORAGE.takeIf { !writeOnly },
+      Manifest.permission.ACCESS_MEDIA_LOCATION.takeIf { shouldAddMediaLocationAccess }
+    ).toTypedArray()
+  }
+
   private fun launchCameraWithPermissionsGranted(promise: Promise, cameraIntent: Intent, pickerOptions: ImagePickerOptions) {
     val imageFile = createOutputFile(
       mContext.cacheDir,
diff --git a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImageResultTask.kt b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImageResultTask.kt
index 0c8254baaf..4916906767 100644
--- a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImageResultTask.kt
+++ b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImageResultTask.kt
@@ -2,9 +2,13 @@ package expo.modules.imagepicker.tasks
 
 import android.content.ContentResolver
 import android.net.Uri
+import android.os.Build
 import android.os.Bundle
+import android.provider.DocumentsContract
+import android.provider.MediaStore
 import android.util.Base64
 import android.util.Log
+import androidx.annotation.RequiresApi
 import androidx.exifinterface.media.ExifInterface
 import expo.modules.core.Promise
 import expo.modules.core.errors.ModuleDestroyedException
@@ -20,6 +24,7 @@ import kotlinx.coroutines.suspendCancellableCoroutine
 import java.io.ByteArrayOutputStream
 import java.io.File
 import java.io.IOException
+import java.lang.UnsupportedOperationException
 import kotlin.coroutines.resume
 import kotlin.coroutines.resumeWithException
 
@@ -119,11 +124,55 @@ open class ImageResultTask(
       }
 
       // Explicitly get latitude, longitude, altitude with their specific accessor functions.
-      exifInterface.latLong?.let { latLong ->
-        putDouble(ExifInterface.TAG_GPS_LATITUDE, latLong[0])
-        putDouble(ExifInterface.TAG_GPS_LONGITUDE, latLong[1])
-        putDouble(ExifInterface.TAG_GPS_ALTITUDE, exifInterface.getAltitude(0.0))
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
+        putExifLocationForUri(contentResolver, uri)
+      } else {
+         // Used in API < 29.
+         // fills [Bundle] with latitude and longitude or skips if fail
+        exifInterface.latLong?.let { latLong ->
+          putDouble(ExifInterface.TAG_GPS_LATITUDE, latLong[0])
+          putDouble(ExifInterface.TAG_GPS_LONGITUDE, latLong[1])
+          putDouble(ExifInterface.TAG_GPS_ALTITUDE, exifInterface.getAltitude(0.0))
+        }
+      }
+    }
+  }
+
+  /**
+   * API 29+ adds "scoped storage" which requires extra permissions (`ACCESS_MEDIA_LOCATION`) to access photo data.
+   * Reference: [Android docs](https://developer.android.com/training/data-storage/shared/media#location-info-photos)
+   * @returns [Bundle] with latitude and longitude or `null` if fail
+   * @throws UnsupportedOperationException when `ACCESS_MEDIA_LOCATION` permission isn't granted
+   */
+  @RequiresApi(api = Build.VERSION_CODES.Q)
+  @Throws(UnsupportedOperationException::class, IOException::class)
+  private fun Bundle.putExifLocationForUri(contentResolver: ContentResolver, photoUri: Uri) {
+    try {
+      // The DownloadsProvider URI doesn't allow to get EXIF Location, so we do a hack:
+      // extract the media ID from that URI and convert it to the MediaStore External Content URI
+      // which is equivalent of URIs used by expo-media-library (for which EXIF works)
+      // taken from https://stackoverflow.com/questions/34696787/a-final-answer-on-how-to-get-exif-data-from-uri
+      val rawId = DocumentsContract.getDocumentId(photoUri)
+      val id = if (rawId.contains(':')) rawId.split(':')[1] else rawId
+      val mediaUri = Uri.withAppendedPath(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id)
+      // Exception occurs here if ACCESS_MEDIA_LOCATION permission isn't granted
+      val finalUri = MediaStore.setRequireOriginal(mediaUri)
+
+      contentResolver.openInputStream(finalUri)?.use { stream ->
+        val exifInterface = ExifInterface(stream)
+        exifInterface
+          .latLong
+          ?.let { (lat, lng) ->
+            putDouble(ExifInterface.TAG_GPS_LATITUDE, lat)
+            putDouble(ExifInterface.TAG_GPS_LONGITUDE, lng)
+            putDouble(ExifInterface.TAG_GPS_ALTITUDE, exifInterface.getAltitude(0.0))
+          }
       }
+    } catch (e: UnsupportedOperationException) {
+      throw UnsupportedOperationException("Cannot access ExifInterface because of missing ACCESS_MEDIA_LOCATION permission")
+    } catch (e: Throwable) {
+      Log.w("expo-media-library", "Could not parse Location EXIF tags for $photoUri")
+      e.printStackTrace()
     }
   }
 }

```

</details>


And the version to download: 
[image-picker-exif.patch.zip](https://github.com/expo/expo/files/8659419/image-picker-exif.patch.zip)

**Comment by barthap** [comment]
Personally I tested it with SDK 45, but as long as there were no significant Android changes in changelog, this should work with 44 too, but line numbers might differ slightly

**Comment by BrodaNoel** [comment]
I upgraded to SDK 45, but found too many unrelated issues.
I'm downgrading to SDK 44 again, and will try the code there.
Thanks!

**Comment by BrodaNoel** [comment]
@barthap I just published a new version with that patch included.
Let's see what happens in some hours 🤞

I see you wrote `// if it does not work, try replacing with ACTION_OPEN_DOCUMENT`.

What do you mean with "if it doesn't work"? An app crash? Or EXIF data not present?

Again: Thank you for taking the time on working on it.

**Comment by BrodaNoel** [comment]
Users are reporting this weird behavior. I'm rolling back the change.

Quite weird because I am not receiving any kind of error in Sentry.

https://user-images.githubusercontent.com/1837969/171510305-0ad6f29d-88d4-4a75-a20d-98a8ccf55d18.MOV

**Comment by barthap** [comment]
This looks weird - like image-picking flow was interrupted and thus not finished correctly - but I cannot tell much more without Android Studio debugger, or any minimal app/demo that could reproduce.

However, my code shouldn't interrupt the image picking flow. In case of failure, it should just continue silently by setting location to undefined. That's a pity you don't get any Sentry error, android native logs would help here - I'm talking about these lines:
```kt
} catch (e: Throwable) {
  Log.w("expo-media-library", "Could not parse Location EXIF tags for $photoUri")
  e.printStackTrace()
}
```
I'm not familiar with Sentry here, but maybe it could be helpful to collect this error somehow. From what I quickly found, you'd need to do:
- I assume you're using `@sentry/react-native` and `sentry-expo`
- at the top of the file: `import io.sentry.Sentry` (or `io.sentry.core.Sentry` 🤷 )
- in the `catch` block - something `Sentry.captureException(e)` - I am basing on [these docs](https://docs.sentry.io/platforms/java/usage/).

But all of these are blind guesses.

> I see you wrote `// if it does not work, try replacing with ACTION_OPEN_DOCUMENT.`

I left this comment for myself and forgot to remove it, afaik this shouldn't matter at all

**Comment by BrodaNoel** [comment]
I tried again, and still not a clue about the reason of that behavior. Really weird.
Seems like I have to wait until SDK 46 :(

Is there a way to check the status of this issue in your (expo) backlog?

Thanks!

**Comment by brentvatne** [comment]
@BrodaNoel - the status of this issue is that we need a way to reproduce it before we can investigate it further, as @barthap suggested above

**Comment by BrodaNoel** [comment]
@brentvatne @barthap https://snack.expo.dev/@brodanoel/no-exif

In the snack, I added the steps to reproduce.
I didn't fully tested it on a real device because I have not Android >=10.
I'm trying to find some friend with it to try it.

**Comment by BrodaNoel** [comment]
In the simulator, I can see the error is reproducible

<img width="1438" alt="Screen Shot 2022-06-15 at 14 40 31" src="https://user-images.githubusercontent.com/1837969/173890959-84f338cb-1edb-420c-8c57-f86dd746fb1a.png">

**Comment by BrodaNoel** [comment]
@brentvatne @barthap please let me know if I can do any other thing to help figuring out what is going on here.
I have 10.000 users blocked by this, so, I'm totally willing to help in any thing.

**Comment by BrodaNoel** [comment]
Shouldn't I be able to create a image picker using "expo-media-library"?

That should be a workaround, right? Because there I will get the full EXIF data.

Or what about adding the asset is in expo-media-picker, so I can use it to get the EXIF in expo-media-library?

**Comment by barthap** [comment]
- I'm waiting for this module to finish being refactored before we can investigate it further.
- I don't quite understand your repro - what do you mean by _"(it DO NOT work with photos downloaded from internet with EXIF data. That EXIF is not "cleaned" my Android. Android only clean the EXIF data of photos taken with your phone)"_? It sounds like it's Android issue that it doesn't share EXIF data for some photos.
- What is `expo-media-picker`? 
- I personally don't have real Android 10+ device either. And on emulator my patch/diff worked

**Comment by barthap** [comment]
Some updates:
I was blocked from working on this until the very last week before SDK 46 beta release, but:
- The workaround with `expo-media-library` should now be possible in some cases - image picker now returns `assetId` - [see docs here](https://docs.expo.dev/versions/v46.0.0/sdk/imagepicker/#imageinfo).
  - The limitation is that asset IDs cannot be extracted in some cases (Android limitation). When picker interface is opened, the user can get the image either from Gallery / recents, Downloads or File system.
    - When choosing from Gallery, ID will be always available
    - When choosing from Downloads, ID will be available on Android 10+
    - When choosing from File system, ID will not be available - we can do nothing about this
- I'm afraid some of these limitations also apply to EXIF tags retrieval, as (without getting too deep into Android technical internals) it might require the asset metadata to get info like location.
- In SDK 46 beta, the way EXIF tags are retrieved has changed in a way I don't really like, so please report any regressions you find - I'm going to rewrite it properly.

Side note: I haven't observed the behaviour you're talking about - photos taken by phone are no different from photos downloaded when it comes to location data. 🤷

**Comment by BrodaNoel** [comment]
> When choosing from Downloads, ID will be available on Android 10+

That won't be a problem because android less than 10 always retrieve the full EXIF data.

What I will do is something like this:

- pick the image
- - if the EXIF location data is there, use it. (Android <10)
- - if the EXIF location data is NOT there, get the EXIF data using the AssetId. (Android >=10)


By doing it, it will cover all the cases, besides the System files on android >=10 (which is good enough)

I don't have Android so I don't understand it quite good, but, what happens if a user upload a file from the computer to the phone? Will it be system file?

**Comment by BrodaNoel** [comment]
@barthap I have some updates here.

I've been talking with one of the users of my app that struggle a lot with this issue (the one who reported the lack of GPS data).

After upgrading to SDK 46, and implementing these changes, he wold me that the EXIF data still was NOT there.
So, I told him about these 3 different ways to pick up the photo.
He was clearly using always "option 3" (File system). He tried the Gallery, and said: "I've uploaded the photo via using the Samsung Gallery App. Now it works!".

So... My question now is... Is there a way to BLOCK the user to use File System, and force them to always use only Gallery ro Downloads?

**Comment by BrodaNoel** [comment]
After more research I found something even more weird.

My code now is this:

```
- Pick up a photo, getting `exif` and `assetId`
- If the photo has EXIF, get the location from there.
- If the photo has NOT EXIF, and the `assetId` is defined, get the full "additionalExif" data by using the `assetId`.
```

After that, I save in my backend:
- The photo
- The main EXIF
- The "Additional Exif"

I just saw that ACTUALLY, with this user I mentioned, the "Additional Exif" is NULL... So... I never actually got it. That means that the user changed from "File System" to "Samsung Gallery App" and now the GPS location data is in the MAIN EXIF data. I didn't even have to get the additional data (using the AssetId)... So... this whole upgrade wasn't even necessary. My user could clearly just used the Samsung Gallery App 3 months ago, and it was going to work well...

It's like... Samsung's users could use File System, or Samsung Gallery App since always, and it always were going to work well if they used Samsung Gallery App instead of File System.

Is there a way to block File System? Will that result on the user not being able to pick some photos? Or are they all present in Gallery App?

Sorry for my lack of knowledge in Android. I've never used one :/

**Comment by BrodaNoel** [comment]
Here more details:

```js
const options = {
  mediaTypes: ImagePicker.MediaTypeOptions.Images,
  allowsEditing: false,
  exif: true,
};

ImagePicker.launchImageLibraryAsync(options).then(async response => {
  const { assetId, uri, exif = {} } = response;

  let gpsData = {
    lat: null,
    lng: null,
  };

  // If I have the GPS data in the main `exif`, use it.
  let hasGPS = !!exif.GPSLatitude;

  if (hasGPS) {
    gpsData.lat = exif.GPSLatitude;
    gpsData.lng = exif.GPSLongitude;
  }

  let assetData = {};

  if (assetId) {
    // I get the `assetData` even if we already got the GPS. Just to hydrate the photo with more info
    assetData = await MediaLibrary.getAssetInfoAsync(assetId);

    // But... If we don't have the GPS data in the main EXIF, let's try to find it here.
    if (!hasGPS) {
      // GPS data may be present in: `assetData.location`
      if (assetData.location && assetData.location.latitude) {
        gpsData.lat = assetData.location.latitude;
        gpsData.lng = assetData.location.longitude;
        hasGPS = true;
      } else if (
        assetData.exif &&
        assetData.exif['{GPS}'] &&
        assetData.exif['{GPS}'].Latitude
      ) {
        // GPS data may be present in this new crazy non-standard format: `assetData.exif['{GPS}'].Latitude`
        const gps = assetData.exif['{GPS}'];

        gpsData.lat = gps.Latitude;
        gpsData.lng = gps.Longitude;
        hasGPS = true;
      } else if (assetData.exif && assetData.exif.GPSLatitude) {
        // GPS data may be present in `assetData.exif.GPSLatitude`
        gpsData.lat = assetData.exif.GPSLatitude;
        gpsData.lng = assetData.exif.GPSLongitude;
        hasGPS = true;
      }
    }
  }

  actions.userPhotos.save({
    uri,
    lat: gpsData.lat,
    lng: gpsData.lng,
    exif: {
      ...exif,
      assetData,
    },
  })
}
```

If you check this ^^^, in the backend I will always save the `exif` data with the original/main `exif`, and then, inside `exif.assetData` I will save all the info that I get from `await MediaLibrary.getAssetInfoAsync(assetId);`.

With this user I mentioned, `exif.assetData` is ALWAYS `{}`, which means that while using `Samsung Gallery App` I actually COULD NOT get the `AssetId`... But now, at least `Samsung Gallery App` is providing the GPS data in the main exif (the user was clearly always using the File System).

So... Kind of crazy... We'll have to add a new 4th option like "Samsung Gallery App", where Asset ID is also non-pressent.

**Comment by BrodaNoel** [comment]
Get out of here

**Comment by vbylen** [comment]
I also just noticed that when a video file is picked `expo-image-picker` is returning `{ type: 'image' }` instead of `{ type: 'video' }`.  

This is on the latest version `14.0.0`

**Comment by gabrielfurini** [comment]
I can confirm the issue is still there only on Androids and SDK 47

**Comment by firepked** [comment]
On Samsung Tablet I had to go to the Camera App (Since we use the System Camera here I guess)

Then in the Settings of the App and enable Geo Tagging. 

Android asks to give permissions then to the camera app. 


Doing this did solve  the Problem for me

**Comment by Chrischuck** [comment]
Any update on this? I created issue #21786 to highlight the difference. Expo is able to extract exif data for the image in the example repo I provided but cannot do so for android

**Comment by oaydogmus** [comment]
I'm also experiencing the same issue for SDK 50.
I cannot get lat/long info with launchImageLibraryAsync. Also as mentioned, there is no asset ID (using Recent and Albums) that I can use for MediaLibrary.
Any updates regarding the issue?

**Comment by tlmader** [comment]
Also running into this issue. I'm currently lacking a way to uniquely identify if the same photo has been picked twice, to avoid duplicate uploads.
