### ISSUE TITLE
 Request failed with status code 401 on exp build:android

### ISSUE THREAD

**Issue by perryutkonos** [expo/expo#1740]
### Environment

Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: Not Found
  npm: 6.0.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

### Steps to Reproduce

(Write your steps here:)

1. I run create-react-native-app HelloWord2
2. cd HelloWord2
3. exp start - on device i see could not load exp://vm-cma.nikitindev.helloword2.exp.direct:80
4. exp ba - in terminal Request failed with status code 401

### Expected Behavior

i want run app on the device or get link to get apk

### Actual Behavior

I have Warning: .end() was called twice. This is not supported in superagent - http://prntscr.com/jft672
on device i see could not load exp://vm-cma.nikitindev.helloword2.exp.direct:80 - http://prntscr.com/jft7br
in terminal Request failed with status code 401 - http://prntscr.com/jft6hj

### Reproducible Demo

https://snack.expo.io/H1kj9Tx0z - is the simple app, i can`t create from my PC

P.S sorry for my English

**Comment by nicknovitski** [comment]
401 means "unauthorized".  Is it possible your firewall is blocking these requests?  [See this comment](https://github.com/expo/expo/issues/438#issuecomment-370994663) and the discussion thread around it for ideas.

Does `exp start --lan` behave any differently?

**Comment by LifeIsPizza** [comment]
@nicknovitski Having the same issue.

Everything runs fine, `exp start --lan` works and the app runs merrily on my android device (it's just a simple Hello world app).

But when I try any build, either `build:android` or `build:ios` I get this. Here's a stack trace for you:

> 03:09:34 [exp] Request failed with status code 401
> 03:09:34 [exp] Error: Request failed with status code 401
>     at createError (/usr/lib/node_modules/exp/node_modules/axios/lib/core/createError.js:16:15)
>     at settle (/usr/lib/node_modules/exp/node_modules/axios/lib/core/settle.js:18:12)
>     at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/exp/node_modules/axios/lib/adapters/http.js:191:11)
>     at IncomingMessage.emit (events.js:187:15)
>     at endReadableNT (_stream_readable.js:1086:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

And my diagnostics:
**Environment:**
  OS: Linux 4.16
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

**Packages: (wanted => installed)**
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

**Comment by nicknovitski** [comment]
Are you using the latest version of exp?  `exp --version` to find out, it should be 53.1.0, you can install it again to upgrade.

**Comment by LifeIsPizza** [comment]
Yes I got the latest version.

**Comment by LifeIsPizza** [comment]
Same issue being mentioned here:
https://forums.expo.io/t/account-request-failed-with-status-code-401/9664/2

**Comment by nicknovitski** [comment]
It could be that some part of your account data has been corrupted in our system.  According to that post, you should be able to get around the problem for now by creating a new account.  Try that to be sure, but so we can track down the problem, what are the usernames of your current accounts?

**Comment by LifeIsPizza** [comment]
@nicknovitski Gonna reply only here, saw your post on the expo forums as well.
`exp logout` and `exp login` did not fix my issue. However, I tried to `exp logout` and then `exp register` for a new account through the CLI. My main account (not working) was created on the website and is named "pizzamarinara". The account I created with the CLI is named "pizzamarinara2" and it seems to work now. Currently building the Android apk as "pizzamarinara2" as I'm writing this.

**Comment by quinlanj** [comment]
hi @LifeIsPizza @perryutkonos , we just pushed a fix for this issue. Could you try:
1. running `exp build:android`
2. if it fails, run `exp logout && exp login` then `exp build:android`
3. if it still fails, lmk? 
thanks, and sorry for the inconvenience

**Comment by perryutkonos** [comment]
In my case, `exp logout` and `exp login`, don't work. But i delete account and recreate him and.. its helped me. Old account name contained capital letters, now only lowercase letters (NikitinDev -> nikitindev). Maybe has bug for capital letters in account name?
