### ISSUE TITLE
EAS build failed with "Undefined symbols for architecture arm64'" on ios

### ISSUE THREAD

**Issue by harrydeluxe** [expo/expo#17417]
### Summary

Since the update to SDK 45, the following error message appeared with eas build

![Bildschirmfoto 2022-05-09 um 23 19 55](https://user-images.githubusercontent.com/272485/167500507-3b2556ce-42ea-4c5a-ab4a-b9342445e699.png)

### What platform(s) does this occur on?

iOS

### SDK Version

45

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.0 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.51.0
      expo-cli: 5.4.3
    Expo Workflow: bare

### Reproducible demo

EAS build ID that fails is 94fc588c-3519-45ed-b7f2-46c7ed27471c

**Comment by brentvatne** [comment]
hey there! you need to use xcode 13.2 or 13.3 - the missing symbol is not available in 13.0: https://developer.apple.com/documentation/avfoundation/avmetadataobject/objecttype/3915814-codabar?changes=latest_minor

here's the xcode 13.3 image information: https://docs.expo.dev/build-reference/infrastructure/#image--macos-monterey-123-xcode-133--alias--latest. you can use the `"image"` property in your build profile.

**Comment by orome** [comment]
I'm having a similar problem (#20012) with a different symbol (`_objc_msgSend$topLayoutGuide`) with Xcode 12.2.1.

**Comment by vagnerwentz** [comment]
I'm having a similar problem too [(#20350)](https://github.com/expo/expo/issues/20350) with the expo-camera XCode
/usr/bin/xcodebuild -version Xcode 13.4.1

**Comment by cameronsutter** [comment]
@vagnerwentz I'm having the same problem. Did you find a solution?

**Comment by richardcoder** [comment]
> @vagnerwentz I'm having the same problem. Did you find a solution?

https://github.com/expo/expo/issues/20350#issuecomment-1346043084, hope this helps

**Comment by themtaysw** [comment]
I am experiencing the same issue for the last 2 days consecutively: 

<img width="1094" alt="Screenshot 2024-11-01 at 15 49 45" src="https://github.com/user-attachments/assets/a74039f9-150f-45bd-8452-e0d85c6dd7b6">

**Comment by mazghul** [comment]
[themtaysw](https://github.com/themtaysw) I am too facing this issue today, any luck ?

**Comment by themtaysw** [comment]
> [themtaysw](https://github.com/themtaysw) I am too facing this issue today, any luck ? 

hey, checl the 1st comment from a guy referring the expo docs, they probably released new image supporting xcode 16, or whatever... anyway i looked for the last image supporting xcode v14.5-15.6 (or something similar), and provided that into eas.json ios: image and build went just fine 😃

**Comment by priska96** [comment]
I have a simliar issue. with latest sdk and also set eas.json ios: image to use the latest one. But build fails due to this. any suggestions?

<img width="1207" alt="Bildschirmfoto 2024-11-26 um 14 52 59" src="https://github.com/user-attachments/assets/92fe3128-7ecb-4384-a4bb-55aaa6f93be0">
