### ISSUE TITLE
[SDK 45] Cannot inline bytecode built with JVM target 11

### ISSUE THREAD

**Issue by Bardiamist** [expo/expo#17424]
### Summary

> Task :expo-local-authentication:compileDebugKotlin FAILED e: /Users/bardiamist/Documents/my-proj/node_modules/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt: (41, 76): Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.0.0 - /opt/homebrew/bin/node
      Yarn: 1.22.15 - /opt/homebrew/bin/yarn
      npm: 8.6.0 - /opt/homebrew/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: 45.0.2 => 45.0.2 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: bare
 ```

### Reproducible demo

I'll provide later if it's not common issue

**Comment by barthap** [comment]
The Expo SDK 45 libraries are targeting Java 11 and your project is targeting Java 8 which causes this error.

Not 100% sure, but if you want to migrate to Java 11, you probably want to add this to your `android/app/build.gradle`:
```groovy
android {
  compileSdkVersion safeExtGet("compileSdkVersion", 31)

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }

  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_11.majorVersion
  }

  // ...
```
Or modify these lines about Java 11 from `node_modules/expo-local-authentication/android/build.gradle` to still use Java 8

**Comment by Bardiamist** [comment]
I use Java 11. As I understand, error mean that `expo-local-authentication` was build by Java 8.
SDK 44 worked fine.

**Comment by barthap** [comment]
Hmm, `expo-local-authentication` should be built with Java 11:
https://github.com/expo/expo/blob/48ae350d8059f9bcd83e9a6b2922fbff8a7d2661/packages/expo-local-authentication/android/build.gradle#L64-L71

Are you sure you're using the latest `expo-local-authentication@~12.2.0`? These lines should be present in its `build.gradle`

**Comment by Bardiamist** [comment]
>Are you sure you're using the latest expo-local-authentication@~12.2.0?

Yes, I updated `expo-local-authentication` from `12.1.1` to `12.2.0`

**Comment by Bardiamist** [comment]
I really forgot to update `expo-local-authentication` version in the `packege.json`. Sorry, thanks for help:)
