### ISSUE TITLE
build ios Standalone build failed!

### ISSUE THREAD

**Issue by phamtrungdung** [expo/expo#1742]
https://expo.io/builds/bce755c3-576e-4ead-8579-4723ab2cf7cc

[stderr] [19:37:27] 'ios-shell-app' errored after 15 s
[stderr] [19:37:27] Error: Process exited with non-zero code: 1
[stderr]     at ChildProcess.child.on (/usr/local/turtle-agent/tools-public/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
[stderr]     at emitTwo (events.js:125:13)
[stderr]     at ChildProcess.emit (events.js:213:7)
[stderr]     at maybeClose (internal/child_process.js:927:16)
[stderr]     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by Danjavia** [comment]
I have the exact problem! :(

**Comment by tcdavis** [comment]
Hi Pham, sorry about that.  We're going to need to investigate why your build failed.

**Comment by terribleben** [comment]
Hi, can you try again? I ran a test build for this app and it succeeded. It may have been an intermittent issue.

**Comment by ahmad4zan** [comment]
Hi @terribleben,
i have the same exact error log, could you try for this build?
https://expo.io/builds/2783bc14-5526-4c56-b73e-58a25210cd14

I'm currently trying to build using exp build:ios --apple-enterprise-account

**Comment by orehush** [comment]
Hello,
@terribleben. Are any updates here?
I have the same issue (https://expo.io/builds/b70a7557-9402-42d8-b5c1-902cb4b4da96):

generating IPA...
[stderr] [07:23:49] 'ios:build-and-sign-ipa' errored after 24 s
[stderr] [07:23:49] Error: Process exited with non-zero code: 1
[stderr]     at ChildProcess.child.on (/usr/local/turtle-agent/tools-public/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
[stderr]     at emitTwo (events.js:125:13)
[stderr]     at ChildProcess.emit (events.js:213:7)
[stderr]     at maybeClose (internal/child_process.js:927:16)
[stderr]     at Socket.stream.socket.on (internal/child_process.js:348:11)
[stderr]     at emitOne (events.js:115:13)
[stderr]     at Socket.emit (events.js:210:7)
[stderr]     at Pipe._handle.close [as _onclose] (net.js:545:12)
unable to build and sign IPA

**Comment by terribleben** [comment]
@ahmad4zan and @orehush - your errors aren't the same as the original issue. Can you please open different threads (either on the [forums](http://forums.expo.io/) or as issues) if you are stuck?

I haven't heard back from @phamtrungdung about the original report, but I was unable to reproduce the issue (a build on that app worked for me), so I'm going to close this.
