### ISSUE TITLE
Expo SDK 45, android build always fails with errors related to expo plugins

### ISSUE THREAD

**Issue by bandhavya** [expo/expo#17437]
### Summary

My package.json
"axios": "^0.21.1",
    "expo": "45.0.1",
    "expo-font": "~10.0.3",
    "expo-camera": "^12.0.3",
    "expo-av": "^10.2.1",
    "expo-barcode-scanner": "^11.1.2",
    "expo-web-browser": "^10.0.3",
    "expo-device": "^4.0.3",
    "expo-network": "^4.0.3",
    "expo-location": "^13.0.4",
    "expo-contacts": "^10.0.3",
    "expo-calendar": "^10.0.3",
    "expo-splash-screen": "~0.15.1",
    "expo-document-picker": "^10.1.3",
    "hermes-engine": "0.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.1",
    "react-native-web": "~0.17.5",
    "@react-native-async-storage/async-storage": "^1.15.14",
    "react-native-bundle-splitter": "^2.1.0",
    "react-native-safe-area-context": "3.3.2",
    "@react-native-community/datetimepicker": "^6.1.3",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-picker/picker": "^1.16.3",
    "react-native-circular-progress": "^1.3.7",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.1",
    "@react-navigation/native": "^6.0.0",
    "react-native-pager-view": "^5.2.1",
    "react-native-vector-icons": "~8.1.0",
    "expo-status-bar": "~1.3.0"

I have expo-location, expo-modules-core, expo-av, expo-font and one more failing always with kotlin version and Plugin id maven not found error.

So I had updated all these packages manually by going throough build.gradle and updating the java version to 11, kotlin to 1.6.10, changing maven to maven-publish as mentioned in https://lifesaver.codes/answer/plugin-with-id-maven-not-found-12774

<img width="1118" alt="Screenshot 2022-05-10 at 6 24 58 PM" src="https://user-images.githubusercontent.com/12510202/167633335-6f59dd03-e053-454b-a336-3f8e9a967905.png">
This was the error so just checked the build.gradle file of expo-modules-core

<img width="869" alt="Screenshot 2022-05-10 at 6 27 37 PM" src="https://user-images.githubusercontent.com/12510202/167633899-a1c988bf-52d7-4f56-b5cf-7d3bc97a6a75.png">
Updating the file as below:

<img width="869" alt="Screenshot 2022-05-10 at 6 30 47 PM" src="https://user-images.githubusercontent.com/12510202/167634445-3bd9ba69-10e5-4d11-b7aa-5ad4cd3ea998.png">

After all these changes done. Im still getting errors :expo:compileDebugFailed which says to delete the ios and android folder and eject again as mentioned here https://stackoverflow.com/questions/70572758/react-native-error-task-expocompilereleasekotlin-failed
After deleting and executing expo eject is again giving same above error to update the build.gradle files of expo plugins.

So why all these issues are coming up? I have updated the Android Studio to the latest and also xcode to latest.

How to get rid of these compilation errors ?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45

### Environment

node version: 14.15.1
gradle: 7.3.3
 "react": "17.0.2",
 "react-dom": "17.0.2",
"react-native": "0.68.1",

### Reproducible demo

Seems to replicable on migrating to latest version and updating android studio

**Comment by hirbod** [comment]
You also need to upgrade your packages. For example, you're using expo-av 10.2.1 - while the current version for SDK 45 is 11.2.3.

Did you run `expo upgrade`? This should normally bump all relevant versions for you.

**Comment by bandhavya** [comment]
Thanks @hirbod I had updated the packages. build was successful after that.

**Comment by bandhavya** [comment]
On running the app, preview throws error related to RNGestureHandlerModule. Please check https://github.com/software-mansion/react-native-gesture-handler/issues/2050#issuecomment-1126671472
