### ISSUE TITLE
🤖 [Android v12] SDK 45 Crash with PendingIntent (Tested on EAS BUILD)(With Workaround Patch ✅)

### ISSUE THREAD

**Issue by ScreamZ** [expo/expo#17432]
### Summary

# 🥳 Workaround

Can be fixed for Managed/Bare Workflow with a custom configuration plugin (or some changes to build.gradle) while waiting for a patch, see https://github.com/expo/expo/issues/17432#issuecomment-1124801250.

# 📝 Original issue 

## ✅ No issue on Android 11 or below
When I use my Android 11 "One plus" phone it works.

## ❌ Starting Android 12, build succeed but app startup crashes
With a Google Pixel 5 Android 12, I get the following error:

```
FATAL EXCEPTION: pool-3-thread-1
Process: com.power.stride.staging, PID: 31865
java.lang.IllegalArgumentException: com.power.stride.staging: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

## 🕵🏻‍♂️ Observations

- It crashes without booting the JavaScript, as the dev-client screen is not shown.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
ENGINE : HERMES
```

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
      Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
      npm: 8.5.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.2 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed
```

```json
{
  "name": "my_project",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build:tailwind": "tailwindcss --input input.css --output tailwind.css --no-autoprefixer && tailwind-rn",
    "dev:tailwind": "concurrently \"tailwindcss --input input.css --output tailwind.css --no-autoprefixer --watch\" \"tailwind-rn --watch\""
  },
  "dependencies": {
    "@formatjs/intl-datetimeformat": "^5.0.1",
    "@formatjs/intl-getcanonicallocales": "^1.9.2",
    "@formatjs/intl-locale": "^2.4.47",
    "@formatjs/intl-numberformat": "^7.4.3",
    "@formatjs/intl-pluralrules": "^4.3.3",
    "@gorhom/bottom-sheet": "^4",
    "@hookform/resolvers": "^2.8.8",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@stadtkatalog/openinghours": "^3.2.0",
    "@stripe/stripe-react-native": "^0.9.0",
    "@xstate/react": "^3.0.0",
    "axios": "^0.27.1",
    "expo": "^45.0.0",
    "expo-apple-authentication": "~4.2.1",
    "expo-auth-session": "~3.6.0",
    "expo-barcode-scanner": "~11.3.0",
    "expo-camera": "~12.2.0",
    "expo-dev-client": "~0.9.5",
    "expo-font": "~10.1.0",
    "expo-haptics": "~11.2.0",
    "expo-linking": "~3.1.0",
    "expo-localization": "~13.0.0",
    "expo-location": "~14.2.2",
    "expo-notifications": "~0.15.2",
    "expo-random": "~12.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-store-review": "~5.2.0",
    "expo-updates": "~0.13.1",
    "expo-web-browser": "~10.2.0",
    "geolib": "^3.3.3",
    "i18next": "^21.6.16",
    "lodash-es": "^4.17.21",
    "lottie-react-native": "5.0.1",
    "luxon": "^2.3.2",
    "react": "17.0.2",
    "react-countdown": "^2.3.2",
    "react-dom": "17.0.2",
    "react-hook-form": "^7.30.0",
    "react-i18next": "^11.16.7",
    "react-native": "0.68.2",
    "react-native-clusterer": "focux/react-native-clusterer#67d4c3e797c37f9ca388f33d7fa84337aad954fb",
    "react-native-confirmation-code-field": "^7.3.0",
    "react-native-fast-image": "^8.5.11",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-maps": "0.30.1",
    "react-native-pager-view": "5.4.15",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-shadow-2": "^6.0.4",
    "react-native-snap-carousel": "4.0.0-beta.6",
    "react-native-svg": "12.3.0",
    "react-native-web": "0.17.7",
    "react-use": "^17.3.2",
    "recoil": "^0.7.2",
    "swr": "^1.3.0",
    "tailwind-rn": "^4.2.0",
    "xstate": "^4.31.0",
    "yup": "^0.32.11",
    "yup-password": "^0.2.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/lodash-es": "^4.17.6",
    "@types/luxon": "^2.3.1",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.67.6",
    "@types/react-native-snap-carousel": "^3.8.5",
    "babel-plugin-module-resolver": "^4.1.0",
    "concurrently": "^7.1.0",
    "postcss": "^8.4.12",
    "prettier": "^2.6.2",
    "prettier-plugin-tailwindcss": "^0.1.10",
    "tailwindcss": "^3.0.24",
    "typescript": "~4.3.5"
  },
  "resolutions": {
    "@types/react": "~17.0.21"
  },
  "private": true,
  "volta": {
    "node": "16.14.2",
    "yarn": "1.22.18"
  }
}
```

![image](https://user-images.githubusercontent.com/6640835/167610902-065f36c1-6443-4c2e-af85-c5019af56fc1.png)

### Reproducible demo

Not sure how, I've no idea what's causing that :'(

**Comment by fobos531** [comment]
It might be helpful to specify the list of expo packages that you're using in the app @ScreamZ

**Comment by ScreamZ** [comment]
@fobos531 
```
"expo": "^45.0.0",
    "expo-app-loading": "~2.0.0",
    "expo-apple-authentication": "~4.2.1",
    "expo-auth-session": "~3.6.0",
    "expo-barcode-scanner": "~11.3.0",
    "expo-dev-client": "~0.9.5",
    "expo-font": "~10.1.0",
    "expo-haptics": "~11.2.0",
    "expo-linking": "~3.1.0",
    "expo-localization": "~13.0.0",
    "expo-location": "~14.2.2",
    "expo-random": "~12.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-store-review": "~5.2.0",
    "expo-updates": "~0.13.1",
    "expo-web-browser": "~10.2.0",
    ```

**Comment by tknuts** [comment]
But why? Did you remember: 

https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in

**Comment by tknuts** [comment]
Where do you add: **implementation 'androidx.work:work-runtime:2.7.0-alpha05'** 
in a managed Expo app ?

**Comment by ScreamZ** [comment]
> But why? Did you remember:
> 
> https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in

I don't have any custom main entrypoint. I don't think the issue is related to that…

>Where do you add: implementation 'androidx.work:work-runtime:2.7.0-alpha05'
in a managed Expo app ?

The core team of @brentvatne should implement the fix I guess if this is verified being the issue, in the meantime I'll make a custom config plugin just like this one and test if it works, I'll edit my comment when I get more insights : https://github.com/expo/config-plugins/blob/main/packages/android-jsc-intl/src/withAndroidJscIntl.ts

**Comment by ourmaninamsterdam** [comment]
@ScreamZ @tknuts We're getting the same error Pending Intent issue on SDK43 and notifications do not work on Android 12, bare workflow. I commented just today on this closed issue:  https://github.com/expo/expo/issues/16184

**Comment by ScreamZ** [comment]
I'm totally not an expert on working with Expo Config Plugins and the API is pretty opaque and not documented about `withAppBuildGradle` function.

However I managed to make the following plugin for Android, and it seems to work.
@brentvatne @tsapeta Can you guys have a look at it?

```js
// test-fix.js
const { withAppBuildGradle } = require("@expo/config-plugins");

module.exports = function withAndroidXWorkRuntimeFix(config) {
  // Return the modified config.
  return withAppBuildGradle(config, (c) => {
    c.modResults.contents = c.modResults.contents.replace(
      /dependencies\s?{/,
      `dependencies {
        implementation 'androidx.work:work-runtime-ktx:2.7.0'`,
    );

    return c;
  });
};

// app.json (or equivalent)
{
  // … other configs
  plugins: [
    "./test-fix",
    // …Others plugins
  ]
}
```

**Comment by ourmaninamsterdam** [comment]
@ScreamZ I'm using bare workflow. Unfortunately adding `implementation 'androidx.work:work-runtime-ktx:2.7.0'` to dependencies in android/app/build.gradle didn't work for us.

**Comment by tknuts** [comment]
> 

Did not work for me :-( My problem is related to:
java.lang.IllegalArgumentException: com.memberlink.app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by ScreamZ** [comment]
Try 
```
 def work_version = "2.7.0"

// (Java only)
implementation "androidx.work:work-runtime:$work_version"
// Kotlin + coroutines
implementation "androidx.work:work-runtime-ktx:$work_version"`,
```

as I updated the script above. It works for me

**Comment by tknuts** [comment]
> ~**EDIT : Does not seems to work**~ **EDIT** Seems to work finally (take care of rm -rf node_modules before)
> 
> I'm totally not an expert on working with Expo Config Plugins and the API is pretty opaque and not documented about `withAppBuildGradle` function.
> 
> However I managed to make the following plugin for Android : Can you try it on your side too
> 
> ```js
> // test-fix.js
> const { withAppBuildGradle } = require("@expo/config-plugins");
> 
> module.exports = function withAndroidXWorkRuntimeFix(config) {
>   // Return the modified config.
>   return withAppBuildGradle(config, (c) => {
>     c.modResults.contents = c.modResults.contents.replace(
>       /dependencies\s?{/,
>       `dependencies {
>       def work_version = "2.7.0"
> 
>       // (Java only)
>       implementation "androidx.work:work-runtime:$work_version"
>       // Kotlin + coroutines
>       implementation "androidx.work:work-runtime-ktx:$work_version"`,
>     );
> 
>     return c;
>   });
> };
> 
> 
> 
> // app.json (or equivalent)
> {
>   // … other configs
>   plugins: [
>     "./test-fix",
>     // …Others plugins
>   ]
> }
> ```
> 
> For Bare workflow add to `app/build.gradle` in `dependencies`
> 
> ```groovy-gradle
> def work_version = "2.7.0"
> // (Java only)
> implementation "androidx.work:work-runtime:$work_version"
> // Kotlin + coroutines
> implementation "androidx.work:work-runtime-ktx:$work_version"`,
> ```

Are you not missing the }(end bracket) to `dependencies {` ?

**Comment by kesha-antonov** [comment]
> Try
> 
> ```
>  def work_version = "2.7.0"
> 
> // (Java only)
> implementation "androidx.work:work-runtime:$work_version"
> // Kotlin + coroutines
> implementation "androidx.work:work-runtime-ktx:$work_version"`,
> ```
> 
> as I updated the script above. It works for me

Thanks
This works

```android/app/build.gradle```
```
dependencies {
    ...
    
    // FIX FOR EXPO PendingIntent https://github.com/expo/expo/issues/17432
    def work_version = "2.7.0"
    // (Java only)
    implementation "androidx.work:work-runtime:$work_version"
    // Kotlin + coroutines
    implementation "androidx.work:work-runtime-ktx:$work_version"
```

**Comment by tknuts** [comment]
After uninstalling existing version in Google Play(not updating), it works with your plugin fix :-)

**Comment by Kudo** [comment]
the problem seems come from react-native-maps and `react-native-maps@0.30.2` has fixed the crash. if it doesn't work, please let us know.

**Comment by ScreamZ** [comment]
> the problem seems come from react-native-maps and `react-native-maps@0.30.2` has fixed the crash. if it doesn't work, please let us know.

Did you bump the `expo install` package version?

**Comment by Kudo** [comment]
@ScreamZ yes we did. let me know if it doesn't work for you.

**Comment by ScreamZ** [comment]
@Kudo Seems to work, I let the fix around just in case it's needed further for some other package.

**Comment by Kudo** [comment]
cool, thanks!

**Comment by mdtechcs** [comment]
@Kudo how to update react-native-maps@0.30.2 for managed workflow  for     "expo": "^45.0.0",

**Comment by Kudo** [comment]
@mdtechcs `expo install react-native-maps`

**Comment by mdtechcs** [comment]
@Kudo not working Actually the issue is with expo-facebook  but not sure how to fix

**Comment by ScreamZ** [comment]
@Kudo That's the issue, my fix seems to work on any library @mdtechcs you could keep it awaiting for a global fix, or maybe expo could try to guess if it's relevant to merge it

**Comment by ScreamZ** [comment]
What if you don't change the gradle command and just set 
```
 "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      ```

**Comment by Kudo** [comment]
@mdtechcs could you share your crash stacktrace? let's make sure the crash is from androidx.work first. if crash is from androidx.work, then execute `./gradlew :app:dependencies > dep.log` and figure out which library added the androidx.work dependency in the dep.log.

**Comment by mdtechcs** [comment]
> What if you don't change the gradle command and just set
> 
> ```
>  "distribution": "internal",
>       "android": {
>         "buildType": "apk"
>       },
> ```

@ScreamZ  nope doesn't seem to be working for me .. even I tried `eas build --platform android` standard command to trigger android build but its failing

**Comment by mdtechcs** [comment]
@Kudo 

Here is error logs. I am using expo managed workflow so ./gradlew :app:dependencies > dep.log doesn't work

` Caused by: java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.facebook.AccessTokenManager.setTokenExpirationBroadcastAlarm(AccessTokenManager.java:164)
        at com.facebook.AccessTokenManager.setCurrentAccessToken(AccessTokenManager.java:130)
        at com.facebook.AccessTokenManager.setCurrentAccessToken(AccessTokenManager.java:110)
        at com.facebook.AccessToken.setCurrentAccessToken(AccessToken.java:245)
        at com.facebook.login.LoginManager.finishLogin(LoginManager.java:719)
        at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:242)
        at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:181)
        at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:81)
        at expo.modules.facebook.FacebookModule.onActivityResult(FacebookModule.kt:62)
        at expo.modules.adapters.react.services.UIManagerModuleWrapper$4.onActivityResult(UIManagerModuleWrapper.java:174)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:328)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:828)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:113)
        at expo.modules.ReactActivityDelegateWrapper.onActivityResult(ReactActivityDelegateWrapper.kt:145)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
        at android.app.Activity.dispatchActivityResult(Activity.java:8382)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5291)`

**Comment by Kudo** [comment]
@mdtechcs cool! it looks like it related to outdated facebook sdk. maybe it's worth for you to try [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/#expo-installation) because we are deprecating expo-facebook in next sdk.

**Comment by andrejpavlovic** [comment]
For me upgrading react-native-maps to v0.30.2 or higher fixed the issue.

<details>
  <summary>I also put together a slightly refactored version of work-runtime plugin from above comment.</summary>

```javascript
// 
// eslint-disable-next-line import/no-internal-modules
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode')
const { withAppBuildGradle, createRunOncePlugin } = require('@expo/config-plugins')

function withAndroidxWorkRuntimeWorkaround(config) {
  // Return the modified config.
  return withAppBuildGradle(config, (c) => {
    // eslint-disable-next-line no-param-reassign
    c.modResults.contents = mergeContents({
      src: c.modResults.contents,
      newSrc: `    def work_version = "2.7.0"

    // (Java only)
    implementation "androidx.work:work-runtime:$work_version"
    // Kotlin + coroutines
    implementation "androidx.work:work-runtime-ktx:$work_version"`,
      anchor: /dependencies\s?{/,
      offset: 1,
      tag: 'my-app(androidx.work:workaround)',
      comment: '//',
    }).contents

    return c
  })
}

module.exports = createRunOncePlugin(
  withAndroidxWorkRuntimeWorkaround,
  'withAndroidxWorkRuntimeWorkaround',
  '1.0.0'
)
```
</details>

**Comment by ScreamZ** [comment]
We definitely need some documentation on this kind of function like `createRunOncePlugin` and `mergeContents`

**Comment by mdtechcs** [comment]
@andrejpavlovic the refactored version of your also giving me same error. 

```
  AssertionError: Wrong number of arguments provided for static config 
    plugin, expected either 1 or 2, got 3
    Code: ERR_ASSERTION
```

I am curious if that worked for you in managed workflow?

**Comment by koukoujohn** [comment]
I have the same kind of crash on an Android 10 device. I have done the fix above with maps but this seems to be a different error.

When I remove stripe-react-native or downgrade it to the expo 44 supported version of @stripe/stripe-react-native: 0.2.3 the developer client doesnt crash on startup.

If I create a clean expo app with only stripe react native 0.6.1 installed (and config plugin setup correctly) the dev client doesn't crash though. This is what's confusing me. Can it be a conflict with another dependency?

Also when I load the same build on android 12 Android studio emulator I don't get the same crash.

App is Managed, EAS built android developer client, Expo 45

<details>
  <summary>Environment</summary>
  
     EAS CLI 0.52.0 environment info:
        System:
          OS: Windows 10 10.0.19044
        Binaries:
          Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
          npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
        Utilities:
          Git: 2.33.0. - /mingw64/bin/git
        npmPackages:
          expo: ^45.0.4 => 45.0.4
          expo-dev-client: ~0.9.6 => 0.9.6
          expo-updates: ~0.13.1 => 0.13.1
          react: 17.0.2 => 17.0.2
          react-dom: 17.0.2 => 17.0.2
          react-native: 0.68.2 => 0.68.2
          react-native-web: 0.17.7 => 0.17.7
          react-navigation: ^4.4.4 => 4.4.4
        Project workflow: managed

</details>

<details>
  <summary>package.json</summary>

    {
      "main": "./index.js",
      "scripts": {
        "dev": "expo start --dev-client",
        "otaprod": "cross-env ENV=production expo publish --release-channel",
        "otastag": "cross-env ENV=staging expo publish",
        "devandroid": "eas build --profile development --platform android",
        "devios": "eas build --profile development --platform ios",
        "stagandroid": "eas build --profile staging --platform android",
        "stagios": "eas build --profile staging --platform ios --auto-submit",
        "prodandroid": "eas build --profile production --platform android",
        "prodios": "eas build --profile production --platform ios --auto-submit",
        "eject": "expo eject"
      },
      "dependencies": {
        "@eva-design/eva": "2.0.0",
        "@expo/react-native-action-sheet": "^3.6.0",
        "@intercom/intercom-react-native": "^3.0.3",
        "@react-native-async-storage/async-storage": "~1.17.3",
        "@react-native-community/masked-view": "0.1.10",
        "@react-native-community/netinfo": "8.2.0",
        "@sentry/react-native": "^3.4.2",
        "@stripe/stripe-react-native": "0.6.1",
        "@ui-kitten/components": "^5.1.0",
        "@ui-kitten/eva-icons": "^5.0.0",
        "apisauce": "^1.0.2",
        "config-plugin-react-native-intercom": "^1.4.0",
        "expo": "^45.0.4",
        "expo-apple-authentication": "~4.2.1",
        "expo-application": "~4.1.0",
        "expo-asset": "~8.5.0",
        "expo-auth-session": "~3.6.1",
        "expo-blur": "~11.1.0",
        "expo-clipboard": "~3.0.1",
        "expo-constants": "~13.1.1",
        "expo-dev-client": "~0.9.6",
        "expo-device": "~4.2.0",
        "expo-firebase-analytics": "~7.0.0",
        "expo-firebase-core": "~5.0.0",
        "expo-font": "~10.1.0",
        "expo-intent-launcher": "~10.2.0",
        "expo-linear-gradient": "~11.3.0",
        "expo-linking": "~3.1.0",
        "expo-localization": "~13.0.0",
        "expo-location": "~14.2.2",
        "expo-notifications": "~0.15.2",
        "expo-permissions": "~13.2.0",
        "expo-random": "~12.2.0",
        "expo-splash-screen": "~0.15.1",
        "expo-status-bar": "~1.3.0",
        "expo-system-ui": "~1.2.0",
        "expo-updates": "~0.13.1",
        "formik": "^1.5.7",
        "geolib": "^3.3.3",
        "i18next": "^19.5.0",
        "lodash": "^4.17.11",
        "lottie-react-native": "5.0.1",
        "memoizee": "^0.4.14",
        "moment": "^2.27.0",
        "numeral": "^2.0.6",
        "react": "17.0.2",
        "react-content-loader": "^6.0.3",
        "react-dom": "17.0.2",
        "react-i18next": "^11.7.0",
        "react-native": "0.68.2",
        "react-native-animatable": "^1.3.2",
        "react-native-big-list": "^1.4.3",
        "react-native-console-time-polyfill": "^1.2.1",
        "react-native-country-picker-modal": "^2.0.0",
        "react-native-easy-toast": "^1.2.0",
        "react-native-eva-icons": "^1.1.0",
        "react-native-fast-image": "^8.5.11",
        "react-native-formik": "^1.7.6",
        "react-native-gesture-handler": "~2.2.1",
        "react-native-image-zoom-viewer": "^3.0.1",
        "react-native-keyboard-aware-scroll-view": "^0.9.1",
        "react-native-maps": "0.30.2",
        "react-native-modal": "^13.0.0",
        "react-native-paper": "^2.16.0",
        "react-native-reanimated": "~2.8.0",
        "react-native-redash": "^16.2.2",
        "react-native-safe-area-context": "4.2.4",
        "react-native-screens": "~3.11.1",
        "react-native-svg": "12.3.0",
        "react-native-tab-view": "^2.16.0",
        "react-native-web": "0.17.7",
        "react-native-webview": "11.18.1",
        "react-navigation": "^4.4.4",
        "react-navigation-drawer": "^2.7.0",
        "react-navigation-stack": "^2.10.4",
        "react-navigation-tabs": "^2.11.0",
        "react-redux": "^7.1.0",
        "recompose": "^0.30.0",
        "redux": "^4.0.5",
        "redux-saga": "^1.0.5",
        "seamless-immutable": "^7.1.4",
        "sentry-expo": "^4.2.0",
        "socket.io-client": "^2.2.0",
        "uuid": "^3.4.0",
        "yup": "^0.27.0"
      },
      "devDependencies": {
        "babel-eslint": "^10.1.0",
        "babel-preset-expo": "~9.1.0",
        "eslint": "^7.6.0",
        "cross-env": "^7.0.3",
        "eslint-config-airbnb": "^18.2.0",
        "eslint-config-google": "^0.14.0",
        "eslint-plugin-import": "^2.22.0",
        "eslint-plugin-jsx-a11y": "^6.3.1",
        "eslint-plugin-react": "^7.20.6",
        "eslint-plugin-react-hooks": "^4.0.8",
        "prettier": "2.0.5",
        "reactotron-apisauce": "^3.0.0",
        "reactotron-react-native": "^3.6.4",
        "reactotron-redux": "^3.1.1",
        "reactotron-redux-saga": "^4.2.2",
        "@babel/core": "^7.12.9"
      },
      "private": true
    }

</details>

<details>
  <summary>Error message caught from Android Studio</summary>

    2022-05-21 12:20:53.105 30836-30836/com.my-app E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.my-app, PID: 30836
        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my-app/expo.modules.devlauncher.launcher.errors.DevLauncherErrorActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
            at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
            at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
            at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:219)
            at android.app.ActivityThread.main(ActivityThread.java:8668)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
         Caused by: java.lang.NullPointerException
            at expo.modules.devlauncher.launcher.errors.DevLauncherErrorActivity.onCreate(DevLauncherErrorActivity.kt:31)
            at android.app.Activity.performCreate(Activity.java:8214)
            at android.app.Activity.performCreate(Activity.java:8202)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247) 
            at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
            at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
            at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 
            at android.os.Handler.dispatchMessage(Handler.java:110) 
            at android.os.Looper.loop(Looper.java:219) 
            at android.app.ActivityThread.main(ActivityThread.java:8668) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 

</details>

**Comment by ragasjohn** [comment]
Hello, 

I am having the same problem as you referred in the beggining. Android build crashes on devices but on EXPO works
I am sure is react-native-maps since I am getting this warning

_Some dependencies are incompatible with the installed expo package version:
 - react-native-maps - expected version: 0.30.2 - actual version installed: 0.31.1_

I have the following packages

  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.1.2",
    "@react-native-community/netinfo": "8.2.0",
    "@react-native-picker/picker": "2.4.0",
    "@react-native/normalize-color": "^2.0.0",
    "@react-navigation/drawer": "6.3.3",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@rneui/base": "^4.0.0-rc.1",
    "@rneui/themed": "^4.0.0-rc.1",
    "@use-expo/font": "^2.0.0",
    "axios": "^0.23.0",
    "date-fns": "^2.25.0",
    "expo": "^45.0.0",
    "expo-app-loading": "~2.0.0",
    "expo-asset": "~8.5.0",
    "expo-file-system": "~14.0.0",
    "expo-firebase-analytics": "~7.0.0",
    "expo-font": "~10.1.0",
    "expo-image-manipulator": "~10.3.1",
    "expo-image-picker": "~13.1.1",
    "expo-linking": "~3.1.0",
    "expo-location": "~14.2.2",
    "expo-network": "~4.2.0",
    "expo-status-bar": "~1.3.0",
    "expo-store-review": "~5.2.0",
    "expo-updates": "~0.13.2",
    "expo-web-browser": "~10.2.1",
    "firebase": "^9.4.0",
    "galio-framework": "^0.8.0",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-actions-sheet": "^0.5.8",
    "react-native-axios": "^0.17.1",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-loading-spinner-overlay": "^3.0.0",
    "react-native-maps": "^0.31.1",
    "react-native-modal-dropdown": "git+https://github.com/siemiatj/react-native-modal-dropdown.git",
    "react-native-pager-view": "5.4.15",
    "react-native-root-toast": "^3.3.0",
    "react-native-screens": "~3.11.1",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.0.0",
    "react-native-webview": "11.18.1"
  },
  "devDependencies": {
    "@types/react": "~17.0.21",
    "babel-preset-expo": "~9.1.0",
    "typescript": "~4.3.5"
  },

Can you help?

Thanks 
Yannis

**Comment by alexander01202** [comment]
@ScreamZ  what do you mean by `Take care of rm -rf node_modules before doing the following manipulation.`

What does it do and how do I take care of it/run the code. I am using expo managed workflow.

**Comment by alexander01202** [comment]
> @ScreamZ yes we did. let me know if it doesn't work for you.

It doesn't work for me. It tells me its incompatible with expo and doesn't fix the error

**Comment by paulmthiebauth** [comment]
It would great to know WHY these PendingIntent errors are happening. I'm facing this issue right now, and as much as I just want to get the issue resolved, I'd really like to know why it's happening :/
