### ISSUE TITLE
BarcodeScanner not working for barcodes (only for QR codes) on Huawei P40 lite

### ISSUE THREAD

**Issue by vents04** [expo/expo#17444]
### Summary

Expo's barcode scanner performs exactly as expected on most devices I have tested except the Huawei P40 Lite. It just does not fire the onBarCodeScanned event and therefore nothing happens. The same barcodes I am trying to scan with the Huawei are scannable through Xiaomi, and Samsung devices. 

Expo: 44.0.0
React-native: 0.64.3
Expo-barcode-scanner: 11.2.0
Device maker: Huawei
Device model: P40 Lite
EMUI version: 12.0
Android version: 10 (a wild guess due to the fact that it is not shown in the sys info page)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 13.14.0 - ~\node_modules\.bin\node.CMD
      npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: managed

### Reproducible demo

The code that I am utilizing is an exact copy of that on expo's barcode scanner docs  - https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

**Comment by CodeFromAnywhere** [comment]
Same problem on Samsung

**Comment by darkoje** [comment]
the same problem on Samsung and Google Pixel

**Comment by nickticket2u** [comment]
on huawei mate 30 pro and non-pro, cannot scan QR or barcode. even the Expo Go app cannot scan the metro bundler qr code

**Comment by JoschuaSchneider** [comment]
We are also experiencing this issue with multiple customers, all on android.
We are on SDK 45 and expo-barcode-scanner 11.3.0.

After some time scanning (in our case pdf417) qr-codes stop working permanently and the callback is not being called anymore.
Barcodes continue to work.

**Comment by s-kuniyoshi** [comment]
I'm having this problem too.
On Huawei Mate10 Pro, Pixel 4a, Pixel6 and so on..

**Comment by nickticket2u** [comment]
> I'm having this problem too. On Huawei Mate10 Pro, Pixel 4a, Pixel6 and so on..

does your Expo Go app also have this problem? on my two Huawei, even the Expo Go app cannot scan the QR code from metro builder
