### ISSUE TITLE
eas build ios fails every time 

### ISSUE THREAD

**Issue by AMoktar** [expo/expo#17458]
### Summary

I'm trying to build ios but failing every time since few hours ago.

I've tried diffrent apps, I also tried success builds from yesterday but today failing without any code changes 

I think this is a bug with expo eas
can anyone confirm ?

### What platform(s) does this occur on?

iOS

### SDK Version

44, 45

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 30
        Build Tools: 28.0.3, 30.0.2, 30.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

```
expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 30
        Build Tools: 28.0.3, 30.0.2, 30.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

Waiting for build to complete. You can press Ctrl+C to exit.
✖ Build failed

🍎 iOS build failed:
Unknown error. Please see logs.

Thanks

**Comment by fobos531** [comment]
Without any additional context I would say its this: https://github.com/expo/eas-cli/issues/1099

**Comment by tknuts** [comment]
Not it.  My eas build was successful and I submitted the app to "Internal test" in Play Store. But if terminates immediately on open. I can't retrieve any error details.
