### ISSUE TITLE
Android Internal Distribution Failure (react-native-maps)

### ISSUE THREAD

**Issue by iM-GeeKy** [expo/expo#17456]
### Summary

**What is actually happening?**

Adding `"react-native-maps": "0.30.1"` causes Android 12 builds to crash on open. However reverting to the last stable version in SDK 44 `"react-native-maps": "0.29.4"` seems to not cause this issue.

**Expected Behavior**

Using the suggested version of `"react-native-maps": "0.30.1"` for SDK 45 should not cause Android 12 builds to crash.

**Additional Notes**

It looks like this was addressed in their repository https://github.com/react-native-maps/react-native-maps/issues/4215 and included in https://github.com/react-native-maps/react-native-maps/releases/tag/v0.31.0 so perhaps we can officially update to the version that seems to resolve the issue.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45.0.2

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29, 31
        Build Tools: 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.2
        System Images: android-26 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.2 => 45.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

https://github.com/iM-GeeKy/test

**Comment by SohelIslamImran** [comment]
I'm facing this issue
https://github.com/react-native-maps/react-native-maps/issues/4235

**Comment by iM-GeeKy** [comment]
Resolved by https://github.com/expo/expo/issues/17478.
