### ISSUE TITLE
Expo solution for activity Lock/Unlock event on phones

### ISSUE THREAD

**Issue by oron11** [expo/expo#1747]
Hi everyone,

In order to run my app I need to know about the activity of the user on the phone,
While the app is running on the background.
If there is a cross platform solution for react native I'll be happy to know.

Thank you.

**Comment by terribleben** [comment]
Hi there, I believe you can use the [AppState](https://facebook.github.io/react-native/docs/appstate.html) API for this. Good luck with your project! :)

**Comment by oron11** [comment]
Hi @terribleben, Perhaps you misunderstand me.
AppState is just for the app from what I read in the document(Background or not),
I need to know when to user has locked or unlocked the phone regardless from the app.

**Comment by terribleben** [comment]
Ah, sorry, I misunderstood.

On iOS there is no way to hear about events that don't directly affect your app. So you can know when your own app gets backgrounded (including if the device was locked while your app was visible), but you can't listen for generic "phone lock" events.

**Comment by oron11** [comment]
How can I use an Android project in react? I'm not sure how to detach

**Comment by terribleben** [comment]
detaching is a way to use custom native code (Java and Objective-C) in your project. It will be harder and more work for you to maintain, but offers the ability to use other native APIs. Check out the guides [here](https://docs.expo.io/versions/latest/expokit/).

**Comment by oron11** [comment]
@terribleben First, Thank you very much for your help.
Secondly, In this guide: https://docs.expo.io/versions/latest/expokit/detach.html
The link in phase 2 is broken.

**Comment by terribleben** [comment]
Sorry about that. Yes, [this](https://docs.expo.io/versions/latest/distribution/building-standalone-apps#2-configure-appjson) should be the right link.
