### ISSUE TITLE
New Expo Go [2.24.3] crashes with expo-facebook

### ISSUE THREAD

**Issue by brunohkbx** [expo/expo#17476]
### Summary

I've been trying to fix the Facebook login in my app with expo-facebook but after updating Expo Go to the new version it keeps crashing.
I created a Facebook app at https://developers.facebook.com/ and added Expo Go info in the Android section as in the image below - it works fine with Expo Go 2.23.2. I followed all steps detailed [here](https://docs.expo.dev/versions/latest/sdk/facebook/)

![Screenshot from 2022-05-12 02-10-44](https://user-images.githubusercontent.com/6487206/167996584-0488e05f-b079-4eb5-b1e1-485f040dab8a.png) 

 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 3.1.0 - /usr/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    SDKs:
      Android SDK:
        API Levels: 26, 29, 30
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.2
        System Images: android-22 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-29 | Android TV Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.3.2
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@bruno.castro/expo-facebook-bug

**Comment by brunohkbx** [comment]
Found this with logcat
```
05-13 01:02:45.455 16104 16104 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=-1, data=Intent { (has extras) }} to activity {host.exp.exponent/host.exp.exponent.experience.ExperienceActivity}: java.lang.IllegalArgumentException: host.exp.exponent: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
05-13 01:02:45.455 16104 16104 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: host.exp.exponent: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
05-13 01:02:45.455 16104 16104 E AndroidRuntime:        at versioned.host.exp.exponent.modules.universal.ScopedUIManagerModuleWrapper.onActivityResult(ScopedUIManagerModuleWrapper.kt:2)
05-13 01:02:45.455 16104 16104 E AndroidRuntime:        at host.exp.exponent.experience.b.onActivityResult(ReactNativeActivity.kt:2)
```

**Comment by yavorganev** [comment]
I have the same issue. Happens with expo sdk 43 and 44 and compatible expo-facebook versions installed using expo install.

**Comment by brunohkbx** [comment]
cc @brentvatne

**Comment by markstreich** [comment]
Started seeing this in production (Sentry) after upgrading from 43 to 45 (bare workflow). None of these errors were tracked in prior versions.

100% Android 12 OS

```
java.lang.IllegalArgumentException: [redacted]: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

Although I don't really know what it means or if it's relevant, the breadcrumbs in Sentry directly before the Exception all seem to follow the pattern Started -> Resumed -> Paused

<img width="522" alt="Screen Shot 2022-06-27 at 15 08 10" src="https://user-images.githubusercontent.com/1214573/175938462-5c97ead2-dabe-416b-9fa3-46e2914c2b27.png">

**Comment by shamilovtim** [comment]
bump

**Comment by brentvatne** [comment]
expo-facebook is deprecated in sdk 45 and removed in sdk 46, so i'm going to close this since we won't fix it.
