### ISSUE TITLE
EXPO 45 - Standalone App crash on startup in Android 12 device/emulator

### ISSUE THREAD

**Issue by viveksc1994** [expo/expo#17478]
### Summary

I have created a demo expo project with expo45 (With some of packages that I am using in my project) and created a build with EAS. Now I have installed APK on many Android 12 devices. and On startup of app, it is crashing.

- Working fine with expo channel with Android 10, 11, 12
- **Not working with standalone apk with Android 12**
- Working with standalone apk with Android 10,12

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

EXPO 45 

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ^45.0.0 => 45.0.3
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Reproducible demo

Reproducible Git - https://github.com/viveksc1994/demo_crash_expo45_android12

APK of same repo - https://turtle-v2-artifacts.s3.amazonaws.com/android/ad877365-a48a-4060-b2a6-d3f8f72a3829-2670e568f5a14571b2e1c7449f71991e.apk

When you try to install APK in Android 12 it is going to crash.

**Comment by viveksc1994** [comment]
![Expo_45_with_EAS_build](https://user-images.githubusercontent.com/10026278/168029872-06c96c01-d0ba-4d10-b204-772dfe5d6c28.jpg)
Some of devices showing errors as per this.

**Comment by tknuts** [comment]
I have the same issue, but just checked your Git, aren't you missing this: 

https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in

**Comment by ScreamZ** [comment]
Seems related to my https://github.com/expo/expo/issues/17432 ?

**Comment by viveksc1994** [comment]
> I have the same issue, but just checked your Git, aren't you missing this:
> 
> https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in

**Comment by viveksc1994** [comment]
I found that, this is causing an issue with `react-native-maps` after removing this, It is working as expected without crashing it.
and I have updated reproducible Git - https://github.com/viveksc1994/demo_crash_expo45_android12 for the same. 
(Kept only `react-native-maps` with default packages to avoid confusion with other packages)

**Comment by iM-GeeKy** [comment]
> I found that, `react-native-maps` is causing an issue, After removing this, It is working as expected without crashing it. and I have updated reproducible Git - https://github.com/viveksc1994/demo_crash_expo45_android12 for the same. (Kept only `react-native-maps` with default packages to avoid confusion with other packages)

This sounds like the same issue I opened a few days ago https://github.com/expo/expo/issues/17456

**Comment by ScreamZ** [comment]
Check my workaround for this issue on #17432

**Comment by Kudo** [comment]
please upgrade `react-native-maps@0.30.2` which should fix the issue. if it doesn't work, please let us know.

**Comment by jack-sparroow** [comment]
> ![Screenshot_2022-05-12-12-40-00-119_com miui bugreport](https://user-images.githubusercontent.com/10026278/168030801-cbc26e3c-f10e-4018-a032-80ab43f06b44.jpg)
> 
> Some of devices showing errors as per this.

how did you got this feedback ?
