### ISSUE TITLE
Unable to start monorepo project following docs

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#17475]
### Summary

I'm setting up a new expo project and want to use a mono repo. I've done this before the unofficial way, but was excited to try the new official way. Steps I followed:

1. Setup a new project with yarn 2.
2. Made sure to switch from pnp -> node-modules
3. added expo via the cli
4. followed the instructions here: https://docs.expo.dev/guides/monorepos/

At this point I tried to start up the project and I get the following error:

```
Starting project at /Users/cwd/Developer/mono-test/native
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Starting Metro Bundler
Missing package "metro/src/lib/attachWebsocketServer" in the project at: /Users/cwd/Developer/mono-test/native
This usually means `react-native` is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.
Error: Missing package "metro/src/lib/attachWebsocketServer" in the project at: /Users/cwd/Developer/mono-test/native
This usually means `react-native` is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.
    at resolveFromProject (/Users/cwd/.config/yarn/global/node_modules/@expo/dev-server/src/metro/importMetroFromProject.ts:21:11)
    at importFromProject (/Users/cwd/.config/yarn/global/node_modules/@expo/dev-server/src/metro/importMetroFromProject.ts:27:18)
    at Object.importMetroLibAttachWebsocketServerFromProject (/Users/cwd/.config/yarn/global/node_modules/@expo/dev-server/src/metro/importMetroFromProject.ts:49:10)
    at Object.createDevServerAsync (/Users/cwd/.config/yarn/global/node_modules/@expo/dev-server/src/metro/createDevServerAsync.ts:63:33)
    at runMetroDevServerAsync (/Users/cwd/.config/yarn/global/node_modules/@expo/dev-server/src/MetroDevServer.ts:75:22)
    at startDevServerAsync (/Users/cwd/.config/yarn/global/node_modules/xdl/src/start/startDevServerAsync.ts:69:49)
    at startAsync (/Users/cwd/.config/yarn/global/node_modules/xdl/src/start/startAsync.ts:74:41)
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

45

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 3.2.0 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/chrisdrackett/mono-test

**Comment by chrisdrackett** [comment]
Out of curiosity I also tried this on yarn 1, but get the same result.

**Comment by chrisdrackett** [comment]
I figured this out. I had an old version of expo-cli in an old version of yarn that I was unaware of. In previous projects we've just installed expo-cli within the project itself, but I was trying to do things the correct way this time and ended up using a *very* old version of expo-cli.

**Comment by MiguelNiblock** [comment]
I'm getting this same error after following the same guide. I already made sure I'm using the latest expo cli version, the latest expo sdk, and the latest yarn version. I'm still not able to get past this same error.

**Comment by hernancasillas** [comment]
Getting the same error. I've been working with and old version of expo sdk and when I updated to the latest, I started getting this error. Thanks in advance.

**Comment by RtlCyclone** [comment]
Same error, i have the latest expo version

**Comment by KieQuang** [comment]
same issues when start new project with expo sdk 45

**Comment by M4nk1n** [comment]
Try `installConfig.hoistingLimits` at `native/package.json`.

```json
"installConfig": {
  "hoistingLimits": "workspaces"
}
```

Or refer to my repo.
https://github.com/M4nk1n/expo-yarn-monorepo

**Comment by mr-chidex** [comment]
getting the same error with latest version of expo

**Comment by pritamp17** [comment]
> Try `installConfig.hoistingLimits` at `native/package.json`.
> 
> ```json
> "installConfig": {
>   "hoistingLimits": "workspaces"
> }
> ```
> 
> Or refer to my repo. https://github.com/M4nk1n/expo-yarn-monorepo
this worked thanks👍

**Comment by spiroalisandratos** [comment]
why is this case closed both attachWebsocketServer.js and attachedWebsocketServer.js.flow are missing from new expo init installs.

Have these files been deprecated?  I though there might have been an issue with react-native however the same issue isn't present, when you bootstrap with react-native  init, you don't get this error and the files are there.
