### ISSUE TITLE
Cannot set position when playing mp4 [Android]

### ISSUE THREAD

**Issue by AdamGerthel** [expo/expo#17479]
### Summary

Setting the position on an mp4 file that is playing doesn't work. No error is thrown. The bug only appears on Android. We caught the bug in our project which is using the bare workflow on SDK 44, but it's reproducible in snacks too.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.4 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.66.4 => 0.66.4 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

https://snack.expo.dev/@insats/expo-av-mp4-position-bug-android

**Comment by hirbod** [comment]
Looks like an old issue: https://github.com/expo/expo/issues/885
But couple of years ago, the issue was AAC.

**Comment by AdamGerthel** [comment]
Interesting. The files we're using are AAC Mp4's. It's the same format that's by default used by iTunes/Apple Music, YouTube, and Android AFAIK. Since it works on iOS but not on Android, I'm thinking it's still a bug, just that it, perhaps, only occurs with AAC files?

**Comment by hirbod** [comment]
It is definitely a bug. I tested it and can confirm it

**Comment by hirbod** [comment]
Not stale

**Comment by khushal87** [comment]
This is definitely not stale. The issue is pretty much evident with aac files as well.
