### ISSUE TITLE
Failed to start the app - bug with immer

### ISSUE THREAD

**Issue by PeterAbdalla** [expo/expo#17473]
### Summary

The app stopped starting after upgrading to SDK 45.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45

### Environment

expo start

While trying to resolve module `immer` from file `/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.production.min.js`, the package `/node_modules/immer/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/immer/dist/immer.esm.mjs`. Indeed, none of these files exist:
 */node_modules/immer/dist/immer.esm.mjs(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
  */node_modules/immer/dist/immer.esm.mjs/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)

### Reproducible demo

tried to add this metro.config.js, but it didn't work.

const { getDefaultConfig } = require('expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

// this
defaultConfig.resolver.sourceExts.push('cjs');

module.exports = defaultConfig;

**Comment by alphaxsmile** [comment]
```
const { getDefaultConfig } = require('expo/metro-config');
const defaultConfig = getDefaultConfig(__dirname);
defaultConfig.resolver.sourceExts.push('mjs');
module.exports = defaultConfig;

```
use `mjs` instead of `cjs`
