### ISSUE TITLE
Document the use case for `reloadFromCache` vs. `reload`, or deprecate `reload` if there is no good use case

### ISSUE THREAD

**Issue by riwu** [expo/expo#1748]
### Environment
expo: 27.0.0

[`Updates.reload()`](https://docs.expo.io/versions/v27.0.0/sdk/updates#expoupdatesreload) will reload the app even when there's no update, so one should **always** check for update first before calling it:
1. `checkForUpdateAsync`
2. `fetchUpdateAsync` // optional
3.  `reload`

But in this case, we can simply replace `reload` with `reloadFromCache`, unless step 2 is skipped, which is generally not desirable as we want to minimise the time period the user is being shown a white screen.

Hence the `reload` API should be removed to avoid confusion/misuse.

**Comment by terribleben** [comment]
Thanks for the suggestion! I agree it is confusing now. I'm not sure we want to completely delete the `reload` API, but maybe we should deprecate or rename it, or just write docs that are more clear about this.

**Comment by esamelson** [comment]
We're working on a new Updates module at this time, so we are not going to make any API changes to the current one to reduce unnecessary churn. Going to go ahead and close this issue.
