### ISSUE TITLE
expo-camera: onBarCodeScanned does not recognize barcodes on Web (Chrome Browser).

### ISSUE THREAD

**Issue by somnathdegmailcom** [expo/expo#17480]
### Summary

The Camera barcode scanner can scan QR codes on the **Web platform** but it is not able to scan any other barcodes like EAN13, EAN8, CODE128 etc. Works properly in Android APK and Expo In Android. The debug code on the handler method was never call for barcodes.

I have tested the application in 
    Expo on Android Mobile - Working.
    **Expo on Web - Not working.**
    Build APK and deployed to original device - Working.
    **On Desktop Chrome Browser (Web) - Not working.
    On Android Mobile Chrome Browser (Web) - Not working.**
    Not yet tested on iOS.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

44.0.0

### Environment

npx: installed 2 in 5.304s

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD  
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.1 => 0.68.1
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Reproducible demo

import React, { useState, useEffect } from "react";
import { useFocusEffect } from "@react-navigation/native";
import {
  Dimensions,
  Platform,
  StyleSheet,
  Text,
  View
} from "react-native";
import { Camera, PermissionStatus, BarCodeScanningResult } from "expo-camera";

export default function BarcodeReaderScreen({ navigation }: any) {
  // Take permission from the user to access the camera...
  const [shouldHide, setShouldHide] = useState(false);
  useFocusEffect(() => {
    setShouldHide(false);
    return () => {
      setShouldHide(true);
    };
  });

  const [hasPermission, setHasPermission] = useState(false);
  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestCameraPermissionsAsync();
      setHasPermission(status === PermissionStatus.GRANTED);
    })();
  }, []);

  const [expo, setType] = useState("back");

  if (hasPermission === null) {
    return <Text>Requesting for camera permission</Text>;
  }

  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }

  const handleBarCodeScanned = (props: BarCodeScanningResult) => {
    console.log("Inside handleBarCodeScanned");
    console.log(props.data);    
  };

  return shouldHide ? null : (
    <View style={styles.container}>
      <Camera
        onBarCodeScanned={handleBarCodeScanned}
        barCodeScannerSettings={{
          barCodeTypes: ["ean13", "ean8", "code128", "upc-a","qr"],
        }}
        style={styles.camera}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignSelf: "center",
    width: width * 0.8,
    height: height * 0.8,
    marginRight: 5,
    marginLeft: 5,
    marginTop: 10,
    paddingTop: 20,
    paddingBottom: 20,
    backgroundColor: 'red',
  },
  camera: {
    flex: 1,
  },
});

**Comment by krupaliempirebs** [comment]
Yes i have the same problem with web barcode scanning. Did you found any solution for that?

**Comment by xposionn** [comment]
facing the same issue, this method not getting invoked when im openning the app via my iphone chrome browser

**Comment by t0ma5h** [comment]
Same bug

**Comment by xposionn** [comment]
Any update ?

**Comment by nolife08021** [comment]
same issue on 
```
"expo-camera": "~15.0.16",
"expo": "^51.0.0",
```
