### ISSUE TITLE
AV module audio bug in web

### ISSUE THREAD

**Issue by psnet** [expo/expo#17497]
### Summary

SDK: 44,
Platform: web

For `av` module when creating sound and audio device is blocked, `status` property show `isLoaded` is ok.

Snack to reproduce: https://snack.expo.dev/@sepu/sound-status-test

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

44

### Environment

Reproduced on expo snack

### Reproducible demo

https://snack.expo.dev/@sepu/sound-status-test

**Comment by byCedric** [comment]
Hi @psnet! I'm not sure if I understand the issue. If your device is blocking audio I don't think the [`new Audio` specification](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio#specifications) will be erroring. Can you share the links from MDN that define this behavior?

**Comment by byCedric** [comment]
Hi @psnet, I think there are two things here:

1. The Media spec doesn't say anything about blocked content. The links you mentioned are related to the content loading states of the audio element, like `HAVE_NOTHING` or `HAVE_CURRENT_DATA`. It doesn't say anything about "blocked device" policies, which brings me to point 2.

2. Google decided it was "annoying" to play a sound when a page is loaded without interaction. They call this the "[Autoplay Policy](https://developer.chrome.com/blog/autoplay/)" in Chrome. It's not really defined in the spec, so I'm not sure how we can integrate that in the web part of the audio player. 

That being said, you can still check if you are running into this. By using [`Audio.Sound.playAsync`](https://docs.expo.dev/versions/v45.0.0/sdk/av/#returns-4), you'll get a status object. In that object you can check for `isLoaded`, which means there are no issues with the file, buffering, or other state issues (from the spec). And if that's true, you can check if the audio is playing or not. If its not, it's likely blocked by Chrome. E.g. something like this:

```js
// Set the position + volume of the audio
await sound.setStatusAsync({ volume: 0.1, positionMillis: 0 });
// Try and play it
const playStatus = await sound.playAsync();

// If there were no loading issues, but it's not playing, it's likely blocked
if (playStatus.isLoaded && !playStatus.isPlaying) {
  setStatus('Likely blocked by chrome');
}
```

Hope it helps!

**Comment by psnet** [comment]
Ok, maybe this is this it, thanks
