### ISSUE TITLE
RecordingSettings unable to be customized to certain extension like .mp3

### ISSUE THREAD

**Issue by flyinghawker** [expo/expo#1750]
I am trying to send voice message by using expo audio module, as noted in document, it may support .caf, .mp3... extensions for **iOS specifically.** Here is a preset recording settings:

```
export const RECORDING_OPTIONS_PRESET_LOW_QUALITY: RecordingOptions = {
  android: {
    extension: '.3gp',
    outputFormat: RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_THREE_GPP,
    audioEncoder: RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AMR_NB,
    sampleRate: 44100,
    numberOfChannels: 2,
    bitRate: 128000,
  },
  ios: {
    extension: '.caf',
    audioQuality: RECORDING_OPTION_IOS_AUDIO_QUALITY_MIN,
    sampleRate: 44100,
    numberOfChannels: 2,
    bitRate: 128000,
    linearPCMBitDepth: 16,
    linearPCMIsBigEndian: false,
    linearPCMIsFloat: false,
  },
};
```
But I got the caf file as big as half MB for JUST 2 seconds. I am newbie to audio related topic, so I am trying to search and find mp3 format may be smaller, so directly modify ios extension to be .mp3, but it is showing that I even can not create recorder. 
**Please help me with custom recording setting or how to compress the audio file size practically with expo audio module.  Thanks.**

**EDIT:**
I have tried other extensions as noted in link [iPhone Audio File Formats](https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/CoreAudioOverview/CoreAudioEssentials/CoreAudioEssentials.html#//apple_ref/doc/uid/TP40003577-CH10-SW57)
seems only **.caf and .wav** works and with them I can modify other parameters as well. But the size still big, I am assuming **mp3** will be better option for me but expo seems not supporting it.

**Comment by terribleben** [comment]
According to [these docs](https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/CoreAudioOverview/CoreAudioEssentials/CoreAudioEssentials.html#//apple_ref/doc/uid/TP40003577-CH10-SW26), 

> neither MP3 nor AAC recording is available. This is due to the high CPU overhead, and consequent battery drain, of these formats.

So, it seems like mp3 recording is simply not supported by iOS. Sorry about that. :(  I suggest trying the formats given in that guide which do work, and seeing which one has the smallest file size.

**Comment by flyinghawker** [comment]
@terribleben OK, I see. Thanks for your reply.

**Comment by Danelund** [comment]
@flyinghawker how did you resolve this - am facing the same issue
