### ISSUE TITLE
Ngrok tunnel error when run `expo start --tunnel` using npm script

### ISSUE THREAD

**Issue by illiakovalenko** [expo/expo#17518]
### Summary

`expo start --tunnel` can't be started using npm script, it throws error:
**Starting Metro Bundler**
**CommandError: ngrok tunnel took too long to connect.**

Using `expo start --tunnel` without npm script, it works as expected

### What platform(s) does this occur on?

Android, iOS

### SDK Version

45

### Environment

-info-1.0.3.tgz 1401ms (cache miss)
 expo-env-info 1.0.3 environment info:
   System:
     OS: Windows 10 10.0.18363
   Binaries:
     Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
     npm: 8.1.0 - ~\AppData\Roaming\npm\npm.CMD
   SDKs:
     Android SDK:
       API Levels: 22, 23, 25, 26, 27, 28, 29
       Build Tools: 23.0.1, 28.0.3, 29.0.2
       System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
   IDEs:
     Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
   npmPackages:
     expo: ~45.0.0 => 45.0.3
     react: 17.0.2 => 17.0.2
     react-dom: 17.0.2 => 17.0.2
     react-native: 0.68.2 => 0.68.2
     react-native-web: 0.17.7 => 0.17.7
   Expo Workflow: managed

### Reproducible demo

1. Add `expo start --tunnel` as a `start` script to the `package.json`
2. Run `npm run start`

**ER**: no errors, app starts successfully
**AR**: CLI throws an error, and the process is stopped
**CommandError: ngrok tunnel took too long to connect.**

**Comment by jaexplorer** [comment]
I can't get tunnel working period.

`Error starting tunnel Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle`

**Comment by jaexplorer** [comment]
@illiakovalenko 
I got tunnel working by uninstalling expo then
installing
expo-cli 3.11.9
and then nvm use v12.22.0

**Comment by illiakovalenko** [comment]
@jaexplorer Sometimes it's working, sometimes not
for me seems like they need to increase timeout, it can take more time to start ngrok

**Comment by SpeedOfSpin** [comment]
I tried installing ngrok again and it worked for me

npm i -g @expo/ngrok

**Comment by BenediktLueth** [comment]
The problem still exists and is causing a lot of pain in day-to-day development. I would strongly support @illiakovalenko's suggestion to increase the timeout. Please let me know if this problem will be addressed in the near future.

**Comment by http-samc** [comment]
@BenediktLueth I was able to solve this by adding the package as a dev dependency in addition to globally.

Specifically, I added this line to my package.json's devDependencies:

`"@expo/ngrok": "^4.1.3"`

Not sure why the error message tries to get you to install the package globally when it appears to be an error with the specific project's dependencies.

**Comment by shkibrahim** [comment]
getting the same issue . Do anyone has a good solution for this?

**Comment by madicke12** [comment]
lunch the command with sudo it worked for me

**Comment by abettermap** [comment]
Reinstalling worked for me as well (using Homebrew):

```sh
brew install ngrok
```
