### ISSUE TITLE
Set app offline but not working in Android

### ISSUE THREAD

**Issue by zhaozhiming** [expo/expo#1751]
Hi, I have set my app to support offline follow the [offline guide](https://docs.expo.io/versions/v26.0.0/guides/offline-support).
This is my app.json:
```json
    "sdkVersion": "26.0.0",
    "assetBundlePatterns": [
      "./src/assets/*",
    ],
    "updates": {
      "enabled": false,
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "fallbackToCacheTimeout": 0
    }
```
But I find every time my app loaded it will goto the exp.host site. I use Charles to fetch the app network info and the info as follow:

![image](https://user-images.githubusercontent.com/1436694/39984636-63c2118a-578e-11e8-86af-8ca67fcf53d4.png)

The exp.host site can’t access in my area, so it make my app launch very slow.
Somethings it was token even 5 minutes to open my app.
How could I make my app don’t access exp.host site?
Thanks.

### Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.0
  Yarn: 1.5.1
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

**Comment by esamelson** [comment]
Hi @zhaozhiming - thanks for the report. Are you seeing this behavior on iOS or Android? (or both?)

**Comment by zhaozhiming** [comment]
Both. iOS and Android have the same problem.

**Comment by esamelson** [comment]
Hi @zhaozhiming - I think this is because the app is fetching the Expo client app's JavaScript bundle as well. All standalone apps used to use a shared JavaScript bundle that would control various parts of the app's lifecycle. This is not used anymore, but the network requests are likely still there.

We'll see what we can do about removing them, but I can't promise this will be done on any given timeframe. Can I ask what your use case is for needing to disable these requests? They should not affect the app's startup time in any way.

**Comment by zhaozhiming** [comment]
@esamelson Should I provide other info？

**Comment by zhaozhiming** [comment]
@esamelson The `https://exp.host` access is very slow in my country([see this](https://en.wikipedia.org/wiki/Great_Firewall)).   
In my case the app sometimes will take 5~10 minutes to launch.  
I can set the proxy in my phone to open my app quickly. But not everyone has a mobile phone proxy. 
Is there a temporary solution to make the app not to access the `exp.host` site? Something like modify the code under the `node_modules/expo`?

**Comment by zhaozhiming** [comment]
I have already set my app to offline, but it still go to connect the internet. I think this way has some  unreasonable.

**Comment by zhaozhiming** [comment]
Yes, I have make a new build. 
I refetch the app launching network info and I found not only `exp.host` but also `graph.facebook.com` will be access.
These sites were difficult to  access(can access but very slow) sometimes in my area.I think the reason is this.
So if I can make my app not to access these sites, then the app will launch fast. And I think the app no need to access these sites, right? 

![image](https://user-images.githubusercontent.com/1436694/40229973-80b68dc4-5ac8-11e8-943d-8e924b811d8b.png)

**Comment by zhaozhiming** [comment]
My thought is when the app set to offline, it will only connect the sites which the app want to, the other sites connection should be banned. I thinks this is the `really` offline.

**Comment by zhaozhiming** [comment]
Oh, I found this problem only found in android but not iOS. I fetch the app network info in iOS app.   
The app will not to access `exp.host` and `graph.facebook.com` site.

![image](https://user-images.githubusercontent.com/1436694/40288718-1d9d3352-5ce7-11e8-9915-1d3bd4bdd4c2.png)

**Comment by esamelson** [comment]
@zhaozhiming ok thanks, that's very helpful to know. We'll see what we can do about this.

**Comment by zhaozhiming** [comment]
I have a little confused now. I have 2 iOS app.   
The network of first app as above, do not go to access the `exp.host`. 
But the second app will go to access the site.

![image](https://user-images.githubusercontent.com/1436694/40417319-0dfea7c4-5eb2-11e8-951d-c2b22999bf61.png)
 
These two iOS app have the same offline config, the different is one is use `SDK 26.0.0`, the other use `SDK 27.0.0`.
```js
    "updates": {
      "enabled": false,
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "fallbackToCacheTimeout": 0
    }
```

**Comment by zhaozhiming** [comment]
Finally I found the slow reason of my app is because one http request(neither the `expo.host` nor `graph.facebook.com`) in my `AppLoading` module sometimes became slow.   
Thanks for your help and please forgive my mistakes. @esamelson

**Comment by beanbechoi** [comment]
i have got same issue with android (but iOS not got this issue): with app.json below
"updates": {
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "enabled": false
    },
when android open app this alway point to https://exp.host
![screen shot 2018-10-31 at 4 09 10 pm](https://user-images.githubusercontent.com/2383308/47777452-5687bf00-dd27-11e8-9010-617c7b44a083.png)
Please let me know how to remove that. I don't want to connect exp.host every time i open app.
