### ISSUE TITLE
Problem with fonts with expo version 27.0.1

### ISSUE THREAD

**Issue by shamanking** [expo/expo#1752]
Any one can help me! Thank you!

When I add library: @expo/videoplayer
It has error 'Unrecognized font family material'

When I use Icon
import { Ionicons } from '@expo/vector-icons';
It has error 'unrecognized font family ionicons'

When I use createIconSet:
import { createIconSet } from '@expo/vector-icons';
It has error 'unrecognized font family foundation'

So, I can not use any Icon component.

I see @expo/vector-icons has been integrated in expo version 27.0.1,
![screen shot 2018-05-14 at 4 20 32 pm](https://user-images.githubusercontent.com/5752503/39991360-8326cede-5799-11e8-979e-9867374a4a5f.png)

**Comment by terribleben** [comment]
Hey there, can you provide a [snack](https://snack.expo.io) which reproduces this behavior? I believe we have fonts working in several of our examples on SDK 27, such as the Expo "tabs" template project available in XDE. You might try comparing your code to one of those examples to see what is different.

**Comment by shamanking** [comment]
Thanks @terribleben , my error arise when I detach expo to the exist project. Now, I use Expo.registerRootComponent, instead of AppRegistry.registerComponent and it works.
