### ISSUE TITLE
[SDK 45] [expo-av] Unmounted Video plays after switching the app to foreground

### ISSUE THREAD

**Issue by justblender** [expo/expo#17539]
### Summary

Starting from SDK 45, `expo-av@11.2.3` doesn't destroy unmounted Video components and resumes their playback after switching the app from background to foreground.

This issue does not occur in SDK 44 with `expo-av@10.2.1`, although I don't think there's a problem with AV. Possibly it's something within `expo-core-modules`?

Here's a quick recording that showcases this bug (listen with audio): 

https://user-images.githubusercontent.com/6288237/168903942-b0abf33c-0387-4e86-a31c-89371d42d082.mp4

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

``` 
 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 14.18.3 - ~/.local/share/nvm/v14.18.3/bin/node
      Yarn: 3.2.0 - /opt/homebrew/bin/yarn
      npm: 8.5.4 - ~/.local/share/nvm/v14.18.3/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.4 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-native: 0.68.0 => 0.68.0
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: bare
```

### Reproducible demo

-

**Comment by barthap** [comment]
Hello, I think that's a problem of `expo-av` rather than `expo-modules-core`. Between 10.2.1 and 11.2.3 there were some changes in the iOS codebase, like #17036.
Could you please provide a minimal reproducible demo of this issue? I couldn't reproduce it on my test app

**Comment by justblender** [comment]
> Hello, I think that's a problem of `expo-av` rather than `expo-modules-core`. Between 10.2.1 and 11.2.3 there were some changes in the iOS codebase, like #17036.

Hello! Indeed, I saw that PR and didn't notice anything wrong with it at first glance, but after further testing I can assure that `expo-av@11.2.0` doesn't suffer from this issue (#17036 was landed in 11.2.1). 

I was first thinking about `expo-modules-core` because module registration was refactored in SDK 45 and it caused issues such as #17395. I thought maybe it could be in the same waters and `EXViewManager` was just acting funny.

> Could you please provide a minimal reproducible demo of this issue? I couldn't reproduce it on my test app

I'm unable to reproduce it in a new managed workflow project :( I'll investigate more what's happening within my app and will let you know if I manage to reproduce it.

**Comment by hirbod** [comment]
Are you using by ANY chance `LayoutAnimation` from reanimated?

**Comment by justblender** [comment]
> Are you using by ANY chance `LayoutAnimation` from reanimated? Like anywhere in the app. Doesn't matter if it's the current screen, but a simple mounted LayoutAnimation screen from reanimated anywhere?

@hirbod I do. 

Interesting. I thought that bug only affected the screens to which the layout animations were applied. I tried removing them from every surface of my content view screen, but that didn't help out. Should've read your issue more thoroughly.

Funnily enough, reverting back #17036 fixed the issue in my scenario. Doesn't really make sense why. Gonna try removing any references to layout animations tomorrow and see if that helps.

**Comment by hirbod** [comment]
It's just a guess though. I hope I don't drive you to the wrong direction but thats just the only thing that comes to my mind because I could never reproduce your issue without the usage of LayoutAnimation.

Are you also using any `setAudioModeAsync`? Any special XCode entitlements? `staysActiveInBackground: true`?

**Comment by hirbod** [comment]
@Pickleboyonline could you think of any scenario why #17036 could restart audio when the app returns from App Switcher (or Background)?

**Comment by justblender** [comment]
> It's just a guess though. I hope I don't drive you to the wrong direction but thats just the only thing that comes to my mind because I could never reproduce your issue without the usage of LayoutAnimation.

Are you kidding me?! It's a great food for thought -- I didn't expect that bug in Reanimated to be **that** severe. Now at least I'll be more careful in any other occurring issues. The app is complex, so I would expect something interestingly related to pop-up rather sooner or later. I greatly appreciate your help!

> Are you also using any `setAudioModeAsync`? Any special XCode entitlements? `staysActiveInBackground: true`?

Yep.

I guess it's only up to the testing on my end, I'm gonna post an update later today after getting some sleep and catching up with my work.

**Comment by hirbod** [comment]
Yes, the issue is unfortunately super severe, thats why REA is fully rewriting LayoutAnimation currently.
It does also do weird stuff on Android (specially when used with react-native-svg).

**Comment by hirbod** [comment]
There might be race conditions indeed, but the real reason is that LayoutAnimation keeps a strong reference and unloading will unload your main element but there is a snapshot. I think the best guy for this is indeed @Pickleboyonline

**Comment by Pickleboyonline** [comment]
@hirbod I think you might be onto it. I agree with you that the strong reference would prevent the video from entirely unloading and thereby prevent the video from executing its end of lifecycle events. 

My guess is that when we put all of Expo Video's functionality on the Main thread SWM's LayoutAnimation is somehow able to get ahold of and keep a strong reference to the Expo Video.

I believe once SWM gets this fixed we should be OK. Though, I would like the Expo Video to stop playing sound and unlist its event listeners when it unmounts (or if LayoutAnimation is preventing unmounting at least when we explicitly call `unloadAsync()`).

I'll try to whip up a solution if I get a chance.

Also, I noticed some issues around Expo Video's pausing and playing functionality. It doesn't really cause the UI to freeze like previously but I've noticed it skipped time when pausing/playing. I don't remember this exactly being an issue with Expo 44 with my patch but it seems to be apparent in the latest 45. I'll put a more detailed report of my findings if I still see this happening. Just putting this out there here in case any of you have experienced the same thing.

**Comment by Pickleboyonline** [comment]
As for when the audio starts playing when the app switches from foreground to background, I think it lies with the Reanimated being able to take a "snapshot" of the view like @barthap mentioned. 

My plan is to put together a test app paired with the Xcode debugger to see what is going on.

**Comment by mikob** [comment]
@Pickleboyonline any updates on this? I'm getting the same issue. I put the video in a pager view and when the page is switched it should be unmounted, but it keeps playing. New instances of the video are created and play over eachother if I switch back and forth to the same video.

**Comment by hirbod** [comment]
There is nothing this library could do. LayoutAnimation rewrite for iOS is mostly done afaik, should be a matter of time.

**Comment by chimiWangchukWangdi** [comment]
This issue is still there
