### ISSUE TITLE
Log and Warn statements are not pretty printed /color highlighted anymore

### ISSUE THREAD

**Issue by Penguin98kStudio** [expo/expo#17532]
### Summary

In Normal Expo, warnings are yellow in color
and console.log statements are prertty printed

both of these behaviours don't work in beta, and its more diffuclt to read this, tho I appreciate the LOG label before log statements, I would really appreciate if the logs were pretty printed

### Expo Beta:
![image](https://user-images.githubusercontent.com/36449676/168835775-a3215c09-a90c-443e-82a6-2bb07cd9f9d1.png)

### Expo Global:
![image](https://user-images.githubusercontent.com/36449676/168835928-224b647d-41ea-4175-829c-89cdd202a28f.png)

### What platform(s) does this occur on?

Android

### SDK Version

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.13 KDE neon 5.24
      Shell: 3.4.1 - /usr/bin/fish
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.9.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed

### Reproducible demo

...

**Comment by brentvatne** [comment]
this is an intended change in the local CLI - it's a tradeoff we made in order to simplify and improve the reliability of the logging infrastructure
