### ISSUE TITLE
StrictMode error

### ISSUE THREAD

**Issue by mxstbr** [expo/expo#1753]
### Environment

  OS: macOS High Sierra 10.13.4
  Node: 10.1.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: Not Found

#### Packages: (wanted => installed)
  expo: Not Found
  react: 16.2.0 => 16.2.0
  react-native: Not Found

#### Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/mxstbr-baf39aaa-b0b4-40ce-97c6-b76115ec322e.tar.gz

### Steps to Reproduce

1. Run https://github.com/withspectrum/spectrum
2. Open in Android, either simulator or an actual device

### Expected Behavior

The app runs on Android, just like it does on iOS

### Actual Behavior

It crashes on startup with the following error:

<img width="617" alt="screen shot 2018-05-14 at 15 44 40" src="https://user-images.githubusercontent.com/7525670/40001254-1fbf42be-578e-11e8-9d1a-420d10f58969.png">

Based on the file referenced in the error, this seems to be a problem in `hashAssetFiles.js`.

### Reproducible Demo

https://github.com/withspectrum/spectrum

**Comment by terribleben** [comment]
I've pinged the team about this to see if anybody knows.

From searching around the internet, it seems like this is a somewhat common symptom in React Native. Have you changed any of these recently?

- babel
- A library which makes use of babel
- Your metro bundler settings, such as whether you're minifying your app

**Comment by mxstbr** [comment]
None of those were changed recently. It could be something in my code but it's suspicious that it runs perfectly fine on iOS but not on Android... 🤔 (also it should output a better error if that was the case)

**Comment by esamelson** [comment]
@mxstbr have you tried any of the workarounds listed in this thread? https://github.com/facebook/react-native/issues/11389 Notably, it seems like the issue goes away if you turn on Remote JS Debugging.

**Comment by mxstbr** [comment]
Will try that in development mode, but that won't help me when I build the app, right? 🤔 (it also happens in the built app)

**Comment by mxstbr** [comment]
> it seems like the issue goes away if you turn on Remote JS Debugging.

Can confirm that the issue goes away in development if turning on remote JS debugging, but I probably don't want to enable that in prod mode?

**Comment by mxstbr** [comment]
Ping, any ideas how to fix this for real? How can I help figuring out where this is coming from?

**Comment by tcdavis** [comment]
@mxstbr The issue @esamelson pointed to seems to line up with what you're experiencing, but that seems to have stuck around for a while so who knows if it's all the same issue.  
Have you tried babel-plugin-transform-strict-mode and/or babel-plugin-transform-remove-strict-mode?
If you can create a repro case in either expo or RN it would help localize the issue

**Comment by mxstbr** [comment]
When I open the URL that the error points to, it shows me this JSON: (`http://192.168.8.124:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=%2FUser%2Fmxstbr%2Fprojects%2Fwithspectrum%2Fspectrum%2Fmobile%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles`)

```JSON
{
  "type": "TransformError",
  "lineNumber": 0,
  "errors": [
    {
      "description": "/Users/mxstbr/projects/withspectrum/spectrum/mobile/node_modules/@expo/vector-icons/fonts/Entypo.ttf: Cannot find module '/User/mxstbr/projects/withspectrum/spectrum/mobile/node_modules/expo/tools/hashAssetFiles'",
      "lineNumber": 0
    }
  ],
  "name": "SyntaxError",
  "message": "/Users/mxstbr/projects/withspectrum/spectrum/mobile/node_modules/@expo/vector-icons/fonts/Entypo.ttf: Cannot find module '/User/mxstbr/projects/withspectrum/spectrum/mobile/node_modules/expo/tools/hashAssetFiles'",
  "stack": "Error: Cannot find module '/User/mxstbr/projects/withspectrum/spectrum/mobile/node_modules/expo/tools/hashAssetFiles'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:475:25)\n    at Module.require (internal/modules/cjs/loader.js:598:17)\n    at require (internal/modules/cjs/helpers.js:11:18)\n    at /Users/mxstbr/projects/withspectrum/spectrum/mobile/node_modules/metro/src/Assets/index.js:279:33\n    at Generator.next (<anonymous>)\n    at step (/Users/mxstbr/projects/withspectrum/spectrum/mobile/node_modules/metro/src/Assets/index.js:327:347)\n    at /Users/mxstbr/projects/withspectrum/spectrum/mobile/node_modules/metro/src/Assets/index.js:327:577\n    at new Promise (<anonymous>)"
}
```

Does that help narrow it down maybe?

**Comment by iamrommel** [comment]
I'm bangin my head for this issue for two days, and already searched, the react-native, stackoverflow, and lastly this expo repo. I was not able to reproduce the issue on during development, but whenever i built the standalone app for android, this issue appears after installing the APK. Am i the only one in this planet that have this issue.

I'm not sure where to start debugging!

![screenshot_20180714-204923](https://user-images.githubusercontent.com/177265/42724608-f36ac450-87a7-11e8-9e7d-9e73cd6e7984.png)

**Comment by docaustyne** [comment]
https://github.com/expo/expo/issues/737
![image](https://user-images.githubusercontent.com/5130885/48500445-29fd9800-e83b-11e8-8b7d-d173ff4781ce.png)

I also have this issue and its getting frustrating, so frustrating
