### ISSUE TITLE
[docs] Broken link in Guides -> Development Builds -> Getting Started

### ISSUE THREAD

**Issue by bpringe** [expo/expo#17535]
### Summary

The link at the end of the document (["any capabilities you have added yourself"](https://docs.expo.dev/development/extending-the-dev-menu/)) is broken.

I'm not sure to where it's supposed to link in the current documentation.

### Link to the related docs page

https://docs.expo.dev/development/getting-started/#installing--expo-dev-client--in-your-project

**Comment by lukmccall** [comment]
This link was removed 😅
Thanks for your report 🏅
