### ISSUE TITLE
expo-ads-admob: Interstitial ad cannot be presented the second time.

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#17536]
### TEST

You can test everything in this [snack](https://snack.expo.dev/ps3KG-rZh).

### Summary

I have implemented my `openInterstitial` method as follows:

```
  const getInterstitialAdId = () =>
    Device.isDevice && !__DEV__ ? INTERSTITIAL_ID : TEST_INTERSTITIAL_ID;

  const openInterstitial = useCallback(
    async ({
      onLoad,
      onFailToLoad,
      onOpen,
      onClose,
      onLeaveApplication,
    } = {}) => {
      try {
        await AdMobInterstitial.setAdUnitID(getInterstitialAdId());

        // Avoid EEA problems
        await AdMobInterstitial.requestAdAsync({ servePersonalizedAds: false });

        //
        // Event listeners
        //
        AdMobInterstitial.addEventListener("interstitialDidLoad", onLoad);
        AdMobInterstitial.addEventListener("interstitialDidFailToLoad", onFailToLoad);
        AdMobInterstitial.addEventListener("interstitialDidOpen", onOpen);
        AdMobInterstitial.addEventListener("interstitialDidClose", handleOnClose);
        AdMobInterstitial.addEventListener("interstitialWillLeaveApplication", onLeaveApplication);

        await AdMobInterstitial.showAdAsync();
      } catch (err) {
        console.log(err);
      }

      function handleOnClose(...args) {
        AdMobInterstitial.removeAllListeners(); // <-  Removing all listeners when it is closed!
        onClose?.(...args);
      }
    },
    []
  );
```

And for some reason, in my iOS physical device, I can open it for a first time, but the second one I get the error:

> Error: Add cannot be presented.

In the other hand, in my iOS EMULATOR, it works perfectly, I can display it multiple times without getting errors.

What's wrong? Why am I getting this error?

--Note: I am testing in **development** mode, with the common Interstital test id:  "ca-app-pub-3940256099942544/5135589807" of the AdMob documentation.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

^44.0.0

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.4.0 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.5 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3 
      react-native-web: ^0.17.5 => 0.17.5 
    Expo Workflow: managed

### Reproducible demo

Just open an interstitial multiple times using the following code:

```
import React, {
  createContext,
  useState,
  useCallback,
  useEffect,
  useMemo,
} from "react";
import * as Device from "expo-device";
import {
  isAvailableAsync,
  setTestDeviceIDAsync,
  AdMobInterstitial,
  AdMobRewarded,
} from "expo-ads-admob";

import { AdMobProviderPropTypes } from "./utils";
import {
  TEST_DEVICE_ID,
  TEST_INTERSTITIAL_ID,
  INTERSTITIAL_ID,
  TEST_REWARDED_ID,
  REWARDED_ID,
} from "./utils/blockIdentifiers";

const AdMobContext = createContext(null);

export default AdMobContext;

export function AdMobProvider({ children }) {
  const [isAvailable, setIsAvailable] = useState(false);

  const prepareAdmob = async () => {
    if (__DEV__) {
      // Set the identifier for the test device
      await setTestDeviceIDAsync(TEST_DEVICE_ID);
    }

    // Check the ads availability for the current device
    const isAvailable = await isAvailableAsync();

    setIsAvailable(isAvailable);
  };

  const getInterstitialAdId = () =>
    Device.isDevice && !__DEV__ ? INTERSTITIAL_ID : TEST_INTERSTITIAL_ID;

  const getRewardedAdId = () =>
    Device.isDevice && !__DEV__ ? REWARDED_ID : TEST_REWARDED_ID;

  const openInterstitial = useCallback(
    async ({
      onLoad,
      onFailToLoad,
      onOpen,
      onClose,
      onLeaveApplication,
    } = {}) => {
      try {
        await AdMobInterstitial.setAdUnitID(getInterstitialAdId());

        // Avoid EEA problems
        await AdMobInterstitial.requestAdAsync({ servePersonalizedAds: false });

        //
        // Event listeners
        //
        AdMobInterstitial.addEventListener("interstitialDidLoad", onLoad);
        AdMobInterstitial.addEventListener("interstitialDidFailToLoad", onFailToLoad);
        AdMobInterstitial.addEventListener("interstitialDidOpen", onOpen);
        AdMobInterstitial.addEventListener("interstitialDidClose", handleOnClose);
        AdMobInterstitial.addEventListener("interstitialWillLeaveApplication", onLeaveApplication);

        await AdMobInterstitial.showAdAsync();
      } catch (err) {
        console.log(err);
      }

      function handleOnClose(...args) {
        AdMobInterstitial.removeAllListeners();
        onClose?.(...args);
      }
    },
    []
  );

  useEffect(() => {
    prepareAdmob();
  }, []);

  const value = useMemo(
    () => ({
      isAdMobAvailableInDevice: isAvailable,
      openInterstitial,
    }),
    [isAvailable, openInterstitial]
  );

  return (
    <AdMobContext.Provider value={value}>
      {children}
    </AdMobContext.Provider>
  );
}
```

I am using
   - "expo-ads-admob": "~12.0.0",

**Comment by VictorioMolina** [comment]
[Unhandled promise rejection: Error: Add cannot be presented]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:27:27 in moduleName.methodInfo.name
at node_modules/expo-ads-admob/build/AdMobInterstitial.js:33:14 in requestAdAsync
at node_modules/expo-ads-admob/build/AdMobInterstitial.js:23:39 in requestAdAsync
at node_modules/expo-ads-admob/build/AdMobInterstitial.js:23:39 in requestAdAsync
at app/contexts/AdMob/AdMobContext.jsx:124:12 in useCallback$argument_0

**Comment by VictorioMolina** [comment]
I have also test in other iOS device (iPhone 12), and the error is still present. Its confusing because my iOS emulator runs everything OK.

**Comment by brentvatne** [comment]
> Deprecated. This module will be removed in SDK 46. There will be no replacement that works with the classic build service (expo build) because [the classic build service has been superseded by EAS Build](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60). With EAS Build and [Development Builds](https://docs.expo.dev/development/introduction/), you should use [react-native-google-mobile-ads](https://github.com/invertase/react-native-google-mobile-ads) instead.

https://docs.expo.dev/versions/v45.0.0/sdk/admob/

**Comment by TestCK** [comment]
@VictorioMolina , were you able to resolve this issue. Even i am facing this issue. And we wont be able to switch to [react-native-google-mobile-ads](https://github.com/invertase/react-native-google-mobile-ads) right now.

**Comment by NOxDriver** [comment]
I'm facing the same.

**Comment by 99Jannis99** [comment]
I'm dacing the same issue

**Comment by elwheshi** [comment]
Same issue for me when using iOS physical device

**Comment by tienduong1988** [comment]
I'm facing the same issue when using iOS physical device. Any progress, please?

**Comment by ornakash** [comment]
> I'm facing the same issue when using iOS physical device. Any progress, please?

I ended up migrating to react-native-mobile-ads

**Comment by NOxDriver** [comment]
> > I'm facing the same issue when using iOS physical device. Any progress, please?
> 
> I ended up migrating to react-native-mobile-ads

Is there a way to do this without converting to a bare app?

**Comment by ali27001** [comment]
ı have the problem too

**Comment by ornakash** [comment]
> > > I'm facing the same issue when using iOS physical device. Any progress, please?
> > 
> > 
> > I ended up migrating to react-native-mobile-ads
> 
> Is there a way to do this without converting to a bare app?

You don't have to convert it to a bare app, you can use prebuild, try that
