### ISSUE TITLE
expo-clipboard error

### ISSUE THREAD

**Issue by khelifioussama** [expo/expo#17548]
### Summary

Hello Team ,
while using expo-clipbard with SDK 44 ( 44.0.6 ) and Clipboard (3.0.1) I am getting this error 
[Unhandled promise rejection: Error: The method or property Clipboard.setStringAsync is not available on android, are you sure you've linked all the native dependencies properly?]

`import * as React from 'react';
import { View, Text, Button, StyleSheet } from 'react-native';
import * as Clipboard from 'expo-clipboard';

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.23
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

export default function App() {
  const [copiedText, setCopiedText] = React.useState('');
  const copyToClipboard = async () => {
    await Clipboard.setStringAsync('hello world');
    };
  return (
    < View style={styles.container}>
      < Button title="Click here to copy to Clipboard" onPress={copyToClipboard} />
      < Text style={styles.copiedText}>{copiedText}</Text>
    </ View>
  );
}

**Comment by barthap** [comment]
`expo-clipboard@3.0.1` needs SDK 45 to work. In SDK 44 you need to use `expo-clipboard@~2.1.0` which has only method `setString()` (without Async)

**Comment by ShedrachJonah11** [comment]
![Screenshot 2023-11-26 at 10 38 10 AM](https://github.com/expo/expo/assets/99442773/306d58c4-3130-4739-bdcd-0c13b009aef0)

**Comment by ShedrachJonah11** [comment]
please i am having this issues on dev client. what do i do
hoping to get a response

**Comment by ShedrachJonah11** [comment]
import * as Clipboard from 'expo-clipboard';  
// function to copy clipboard
  const copyToClipboard = async () => {
    Clipboard.setString(message);
  };
