### ISSUE TITLE
Expo-firebase-analytics not compatible with react-native-firebase with EAS on IOS

### ISSUE THREAD

**Issue by troylutton-qsuper** [expo/expo#17543]
### Summary

There is a podspec version incompatibility between Expo's Firebase analytics React-native-firebase when using EAS.  I am using react-native-firebase as a plugin from in EAS managed.

The error appears to be because expo-firebase-analytics is using Firebase/CoreOnly (= 8.14.0) whereas react-native-firebase requires Firebase/CoreOnly (= 8.15.0).

I tried to use an older version of react-native-firebase but I can only go back several patch versions to where Expo 45 compatibility was introduced.

**The simple fix seems to be to upgrade expo-firebase-analytics to v8.15.0.  As side note Android is working perfectly.**

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    EXFirebaseAnalytics (from `../node_modules/expo-firebase-analytics/ios`) was resolved to 7.0.0, which depends on
      Firebase/Core (= 8.14.0) was resolved to 8.14.0, which depends on
        Firebase/CoreOnly (= 8.14.0)

    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 14.9.1, which depends on
      Firebase/CoreOnly (= 8.15.0)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 11.6.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.4
    Expo Workflow: managed

### Reproducible demo

# install expo firebase analytics
expo install expo-firebase-analytics

# https://rnfirebase.io/#expo
yarn add @react-native-firebase/app
yarn add @react-native-firebase/crashlytics

# do local prebuild produces same result as eas build
expo prebuild --clean

**Comment by barthap** [comment]
I'm not a fan of mixing expo-firebase-* with react-native-firebase. Why don't you use `@react-native-firebase/analytics` instead of the expo counterpart?

**Comment by troylutton-qsuper** [comment]
thanks @barthap that's essentially what we've done now to get around the issue.  Thanks for your help and closing issue.

**Comment by GlenTiki** [comment]
If the official response is to not use `expo-firebase-analytics` anymore (since it depends on `react-native-firebase` packages), can this package be deprecated? Or if this isn't desired, can the issue be addressed at expo's core?

**Comment by barthap** [comment]
It is going to be finally deprecated soon.

**Comment by great-ian** [comment]
have any ideas? 
cuz I'm stuck with this.
keep failing on the prebuild stage...

**Comment by barthap** [comment]
What errors? Any logs maybe?

**Comment by barthap** [comment]
The yellow error tells you everything 🙄 
You have version mismatch between `react-native-firebase` packages. You have `"@react-native-firebase/app":  "14.1.1"` and `"@react-native-firebase/firestore":  "15.1.1"` in your `package.json` dependencies. 

You need to either:
- ensure both of them are **14.1.1**, then re-run yarn/npm install and pod install
- ensure both of them are **15.1.1**, but be aware that in **v15 there was a breaking change** so you need to [follow the instructions from the changelog ("breaking changes" section)](https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#1500-2022-06-20)

**Comment by great-ian** [comment]
thank you for your quick answer.
I corrected packages' version as you said, but it still doesn't work. 
I have to figure out all the packages btw. 
Thanks, again.

**Comment by barthap** [comment]
Another problem might be that you're using both `expo-firebase-core` and `@react-native-firebase/app`

**Comment by TowhidKashem** [comment]
> It is going to be finally deprecated soon.

Hey, I was using `expo-firebase-analytics` for a while then had the need to add `react-native-crashalytics` to my app which lead to me having the same issue as the OP in this thread.

I want to replace `expo-firebase-analytics` with `@react-native-firebase/analytics`, problem is I'm on managed workflow and there doesn't seem to be an existent plugin for `@react-native-firebase/analytics` at the moment to get it to work for managed users using custom dev clients:

<img width="1105" alt="Screen Shot 2022-07-16 at 12 16 34 AM" src="https://user-images.githubusercontent.com/1139927/179311897-83c2fde1-8704-4e3b-bfdb-739ca2e970da.png">

When `expo-firebase-analytics` is deprecated will you guys also be releasing a config plugin for us managed folks? or is there already one I'm not aware of somewhere out there on the interwebs? 🤞

**Comment by barthap** [comment]
When reading the react-native-firebase docs at rnfirebase.io, there is information, that not all of their packages require config plugin.
![image](https://user-images.githubusercontent.com/278340/179314674-9c1fc30d-1e9e-4652-aee6-936d226bd85b.jpeg)

Analytics do work without the plugin so you're good to go 😁

**Comment by TowhidKashem** [comment]
Ha I came back to comment nevermind cause I just saw this:

https://github.com/invertase/react-native-firebase/issues/5629#issuecomment-903172565

Removing it from the pugins array in app config worked like a charm, thanks!

**Comment by 90dy** [comment]
Using @react-native-firebase/analytics solved the issue

**Comment by karimdakroury** [comment]
> Another problem might be that you're using both `expo-firebase-core` and `@react-native-firebase/app`

How to solve this problem? i have firebase and expo-firebase-recaptcha
