### ISSUE TITLE
Link "Follow these instructions" in expokit detach docs does not work

### ISSUE THREAD

**Issue by spedy** [expo/expo#1754]
https://docs.expo.io/versions/latest/expokit/detach

In

**Section 2. Make sure you have the necessary keys in app.json**

_Follow these instructions before continuing to the next step_ link does not work, returns 404.

**Comment by terribleben** [comment]
Thanks! Fixed here https://github.com/expo/expo-docs/commit/c732c7ab002ef911e53b37c4feb8b0058dc58051 and will go out next time we deploy docs.
