### ISSUE TITLE
expo-av: [Error: Prepare encountered an error: recorder not provided.]

### ISSUE THREAD

**Issue by cleandevcode** [expo/expo#17540]
### Summary

At first, it works so I could record but after that, I could not record again because of the below error.

`[Error: Prepare encountered an error: recorder not provided.]`

Thank you.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
React-native: 0.68.1
expo: >=45.0.0-0 < 46.0.0
expo-av: ^11.2.3
```  

I tested it on iphone 6s `15.4.1`.

### Reproducible demo

This is my code base.

```
const startRecording = async () => {
    try {
      await Audio.requestPermissionsAsync();
      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
        staysActiveInBackground: false,
      });

      const { recording, status } = await Audio.Recording.createAsync(
        Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY
      );

    } catch (error) {
      console.log("Failed to start Recording", error);
    }
  };

  const stopRecording = async () => {
    await recording.stopAndUnloadAsync();
    const uri = recording.getURI();
    return uri;
  };
```

**Comment by devbalmuda** [comment]
i got this error too

**Comment by cleandevcode** [comment]
Of course I tested it with real device

**Comment by jdmg94** [comment]
I have this same issue with the real device, the default format `.m4a` freezes the event loop and `.mp4` gives me no tracks on player

**Comment by di-sukharev** [comment]
expo-av 15.0.1
expo 52.0.19
react-native 0.76.5

ios simulator

same issue
