### ISSUE TITLE
White screen for IOS stand alone build

### ISSUE THREAD

**Issue by kaulsalil88** [expo/expo#1755]
### Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/rajat-ttn-2e62ce39-6f9a-4e8a-bfda-ba55bb067520.tar.gz

Standalone

### Steps to Reproduce
1.)Screen getting replaced by white screen on ios stand along build .  It is working for expo client , published builds for both android and ios . But when i create stand alone builds it is showing a white  only for the ios stand alone build .

### Expected Behavior

It  should display the screens normally for all the platforms and build types .

(Write what you thought would happen.)

### Actual Behavior
The screen flickers and shows a blank white screen .

(Write what happened. Add screenshots!)
In the App.js there a single component which has four buttons which are used to change the rendered screen .This issue does not exist for a stand-alone Android app, app opening in expo-client on IOS or Android. It occurs specifically for ios standalone builds. Since it is working for published  apps and not stand alone apps I am assuming some thing is breaking there . PFA the screen shots of the build on respective platforms .
Android Screen Shot : ![screenshot_20180515-184759 1](https://user-images.githubusercontent.com/8721680/40059541-ef732adc-5871-11e8-9738-72121005c585.png)
Ios Screen Shot : 
![img_20180515_185102](https://user-images.githubusercontent.com/8721680/40059614-21cf5ef6-5872-11e8-9495-c54de18aad12.jpg)
I am stuck on this issue for the past 3 days . Any help will really be appreciated . In case more info is required I will share the same .

**Comment by anp** [comment]
Hi! This seems like a tricky one. Do you think you could make a minimal version of this app that reproduces the issue and upload that to GitHub? (i.e. as little code as is necessary to reproduce the issue here).

**Comment by kaulsalil88** [comment]
@anp  I am making a minimal version of the app which will replicate the issue , i had one doubt that what is the difference in the stand alone app made using expo and the published apps . since when i publish the app and open it on the expo ios client it is working properly but not for the stand alone ios app . For android it works in both the cases .

**Comment by kaulsalil88** [comment]
@anp  My collegue finally managed to figure the issue out . The  latest version of expo and react-navigation werent working well together . We made some changes there and then it started working . The main difference we found was that initialRouteName  key needed to  be defined inside StackNavigatorConfig and we were passing it inside navigationOptions object  . The main thing that I cant figure out why was this happening only for the stand alone build(ios only ) and not the published builds . We wasted a lot of time making stand alone builds . We even set the  --no-dev and --minify flag in the  exp cli to replicate the stand alone build but werent able to reproduce  . Please close the issue .

**Comment by jakeasmith** [comment]
Holy crap this one was aggravating. Thank you for coming back to share your solution. Cheers.
