### ISSUE TITLE
Expo ads facebook banner not displayed 

### ISSUE THREAD

**Issue by HamzaAitOumghar** [expo/expo#17555]
### Summary

I want to integrate facebook ads in my app using expo-ads-facebook (11.0.3). I added a Banner but when i start the app using expo r -c i get an error  : 
error SyntheticEvent {
  "_dispatchInstances": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "_dispatchListeners": [Function onError],
  "_targetInst": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "bubbles": undefined,
  "cancelable": undefined,
  "currentTarget": ReactNativeFiberHostComponent {
    "_children": Array [],
    "_internalFiberInstanceHandleDEV": FiberNode {
      "tag": 5,
      "key": null,
      "type": "ViewManagerAdapter_CTKBannerView",
    },
    "_nativeTag": 457,
    "viewConfig": Object {
      "NativeProps": Object {
        "accessibilityActions": "Array",
        "accessibilityHint": "String",
        "accessibilityLabel": "String",
        "accessibilityLiveRegion": "String",
        "accessibilityRole": "String",
        "accessibilityState": "Map",
        "accessibilityValue": "Map",
        "alignContent": "String",
        "alignItems": "String",
        "alignSelf": "String",
        "aspectRatio": "number",
        "backgroundColor": "Color",
        "borderBottomWidth": "number",
        "borderEndWidth": "number",
        "borderLeftWidth": "number",
        "borderRightWidth": "number",
        "borderStartWidth": "number",
        "borderTopWidth": "number",
        "borderWidth": "number",
        "bottom": "mixed",
        "collapsable": "boolean",
        "display": "String",
        "elevation": "number",
        "end": "mixed",
        "flex": "number",
        "flexBasis": "mixed",
        "flexDirection": "String",
        "flexGrow": "number",
        "flexShrink": "number",
        "flexWrap": "String",
        "height": "mixed",
        "importantForAccessibility": "String",
        "justifyContent": "String",
        "left": "mixed",
        "margin": "mixed",
        "marginBottom": "mixed",
        "marginEnd": "mixed",
        "marginHorizontal": "mixed",
        "marginLeft": "mixed",
        "marginRight": "mixed",
        "marginStart": "mixed",
        "marginTop": "mixed",
        "marginVertical": "mixed",
        "maxHeight": "mixed",
        "maxWidth": "mixed",
        "minHeight": "mixed",
        "minWidth": "mixed",
        "nativeID": "String",
        "onLayout": "boolean",
        "opacity": "number",
        "overflow": "String",
        "padding": "mixed",
        "paddingBottom": "mixed",
        "paddingEnd": "mixed",
        "paddingHorizontal": "mixed",
        "paddingLeft": "mixed",
        "paddingRight": "mixed",
        "paddingStart": "mixed",
        "paddingTop": "mixed",
        "paddingVertical": "mixed",
        "position": "String",
        "proxiedProperties": "Map",
        "renderToHardwareTextureAndroid": "boolean",
        "right": "mixed",
        "rotation": "number",
        "scaleX": "number",
        "scaleY": "number",
        "shadowColor": "Color",
        "start": "mixed",
        "testID": "String",
        "top": "mixed",
        "transform": "Array",
        "translateX": "number",
        "translateY": "number",
        "width": "mixed",
        "zIndex": "number",
      },
      "bubblingEventTypes": undefined,
      "directEventTypes": Object {
        "onAdError": Object {
          "registrationName": "onAdError",
        },
        "onAdPress": Object {
          "registrationName": "onAdPress",
        },
        "onLoggingImpression": Object {
          "registrationName": "onLoggingImpression",
        },
      },
      "uiViewClassName": "ViewManagerAdapter_CTKBannerView",
      "validAttributes": Object {
        "accessibilityActions": true,
        "accessibilityHint": true,
        "accessibilityLabel": true,
        "accessibilityLiveRegion": true,
        "accessibilityRole": true,
        "accessibilityState": true,
        "accessibilityValue": true,
        "alignContent": true,
        "alignItems": true,
        "alignSelf": true,
        "aspectRatio": true,
        "backgroundColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "borderBottomWidth": true,
        "borderEndWidth": true,
        "borderLeftWidth": true,
        "borderRightWidth": true,
        "borderStartWidth": true,
        "borderTopWidth": true,
        "borderWidth": true,
        "bottom": true,
        "collapsable": true,
        "display": true,
        "elevation": true,
        "end": true,
        "flex": true,
        "flexBasis": true,
        "flexDirection": true,
        "flexGrow": true,
        "flexShrink": true,
        "flexWrap": true,
        "height": true,
        "importantForAccessibility": true,
        "justifyContent": true,
        "left": true,
        "margin": true,
        "marginBottom": true,
        "marginEnd": true,
        "marginHorizontal": true,
        "marginLeft": true,
        "marginRight": true,
        "marginStart": true,
        "marginTop": true,
        "marginVertical": true,
        "maxHeight": true,
        "maxWidth": true,
        "minHeight": true,
        "minWidth": true,
        "nativeID": true,
        "onLayout": true,
        "opacity": true,
        "overflow": true,
        "padding": true,
        "paddingBottom": true,
        "paddingEnd": true,
        "paddingHorizontal": true,
        "paddingLeft": true,
        "paddingRight": true,
        "paddingStart": true,
        "paddingTop": true,
        "paddingVertical": true,
        "position": true,
        "proxiedProperties": true,
        "renderToHardwareTextureAndroid": true,
        "right": true,
        "rotation": true,
        "scaleX": true,
        "scaleY": true,
        "shadowColor": Object {
          "diff": null,
          "process": [Function processColor],
        },
        "start": true,
        "style": Object {
          "alignContent": true,
          "alignItems": true,
          "alignSelf": true,
          "aspectRatio": true,
          "backfaceVisibility": true,
          "backgroundColor": Object {
            "process": [Function processColor],
          },
          "borderBottomColor": Object {
            "process": [Function processColor],
          },
          "borderBottomEndRadius": true,
          "borderBottomLeftRadius": true,
          "borderBottomRightRadius": true,
          "borderBottomStartRadius": true,
          "borderBottomWidth": true,
          "borderColor": Object {
            "process": [Function processColor],
          },
          "borderEndColor": Object {
            "process": [Function processColor],
          },
          "borderEndWidth": true,
          "borderLeftColor": Object {
            "process": [Function processColor],
          },
          "borderLeftWidth": true,
          "borderRadius": true,
          "borderRightColor": Object {
            "process": [Function processColor],
          },
          "borderRightWidth": true,
          "borderStartColor": Object {
            "process": [Function processColor],
          },
          "borderStartWidth": true,
          "borderStyle": true,
          "borderTopColor": Object {
            "process": [Function processColor],
          },
          "borderTopEndRadius": true,
          "borderTopLeftRadius": true,
          "borderTopRightRadius": true,
          "borderTopStartRadius": true,
          "borderTopWidth": true,
          "borderWidth": true,
          "bottom": true,
          "color": Object {
            "process": [Function processColor],
          },
          "decomposedMatrix": true,
          "direction": true,
          "display": true,
          "elevation": true,
          "end": true,
          "flex": true,
          "flexBasis": true,
          "flexDirection": true,
          "flexGrow": true,
          "flexShrink": true,
          "flexWrap": true,
          "fontFamily": Object {
            "process": [Function processFontFamily],
          },
          "fontSize": true,
          "fontStyle": true,
          "fontVariant": true,
          "fontWeight": true,
          "height": true,
          "includeFontPadding": true,
          "justifyContent": true,
          "left": true,
          "letterSpacing": true,
          "lineHeight": true,
          "margin": true,
          "marginBottom": true,
          "marginEnd": true,
          "marginHorizontal": true,
          "marginLeft": true,
          "marginRight": true,
          "marginStart": true,
          "marginTop": true,
          "marginVertical": true,
          "maxHeight": true,
          "maxWidth": true,
          "minHeight": true,
          "minWidth": true,
          "opacity": true,
          "overflow": true,
          "overlayColor": Object {
            "process": [Function processColor],
          },
          "padding": true,
          "paddingBottom": true,
          "paddingEnd": true,
          "paddingHorizontal": true,
          "paddingLeft": true,
          "paddingRight": true,
          "paddingStart": true,
          "paddingTop": true,
          "paddingVertical": true,
          "position": true,
          "resizeMode": true,
          "right": true,
          "rotation": true,
          "scaleX": true,
          "scaleY": true,
          "shadowColor": Object {
            "process": [Function processColor],
          },
          "shadowOffset": Object {
            "diff": [Function sizesDiffer],
          },
          "shadowOpacity": true,
          "shadowRadius": true,
          "start": true,
          "textAlign": true,
          "textAlignVertical": true,
          "textDecorationColor": Object {
            "process": [Function processColor],
          },
          "textDecorationLine": true,
          "textDecorationStyle": true,
          "textShadowColor": Object {
            "process": [Function processColor],
          },
          "textShadowOffset": true,
          "textShadowRadius": true,
          "textTransform": true,
          "tintColor": Object {
            "process": [...(truncated to the first 10000 characters)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43.0.2

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

```
import * as FacebookAds from "expo-ads-facebook";

FacebookAds.AdSettings.addTestDevice(FacebookAds.AdSettings.currentDeviceHash);

export default function App() {
  return (
    <Provider store={store}>
      <NavigationContainer>
        <Tabs />
        <View
          style={{
            alignItems: "center",
            // marginBottom: 20,
          }}
        >
          <FacebookAds.BannerAd
            placementId="IMG_16_9_APP_INSTALL#placementId"
            type="standard"
            onPress={() => console.log("click")}
            onError={(error) => console.log("error", error)}
          />
        </View>
      </NavigationContainer>
    </Provider>
  );
}

```

**Comment by byCedric** [comment]
Hi @HamzaAitOumghar! Sorry you are running into this! Unfortunately, we've deprecated this module in SDK 45 and we will remove it in SDK 46. Because of that, I think it might be better to try https://github.com/callstack/react-native-fbads instead. [From our docs](https://docs.expo.dev/versions/latest/sdk/facebook-ads/):

> Deprecated. This module will be removed in SDK 46. There will be no replacement that works with the classic build service (expo build) because [the classic build service has been superseded by EAS Build](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60). With EAS Build and [Development Builds](https://docs.expo.dev/development/introduction/), you should use [react-native-fbads](https://github.com/callstack/react-native-fbads) instead.

You should be able to use it with [EAS build](https://docs.expo.dev/build/introduction/) and a [custom dev client](https://docs.expo.dev/development/getting-started/) (also if you are in the managed workflow). I'll keep this issue open, but it will likely be closed once we remove the module in SDK 46. 

Hope this helps!

**Comment by HamzaAitOumghar** [comment]
Hi @byCedric the problem is either react-native-fbads is not working in expo :  https://github.com/callstack/react-native-fbads/issues/326
