### ISSUE TITLE
Security layer for Firebase google-services.json file

### ISSUE THREAD

**Issue by maximveksler** [expo/expo#17566]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by maximveksler** [comment]
https://medium.com/nerd-for-tech/secure-your-firebases-google-services-json-file-in-android-16680f8e5fb4 the default expo projects shipped today call for unsecured patterns for handling the google-service.json file.

**Comment by maximveksler** [comment]
Left here for community / google reference.

Clearly not the way expo team prefers to handle feature requests however I believe problem is common enough to be reference from several locations.

**Comment by brentvatne** [comment]
can you link me to any authoritative information on google's own documentation that explains the need for this and what their suggested approach is? it's not clear to me that this solves anything, it maybe just makes it slightly more inconvenient to access these keys.
