### ISSUE TITLE
[Gatsby] Does not work with Expo 

### ISSUE THREAD

**Issue by alejomendoza** [expo/expo#17573]
### Summary

Went through the Gatsby installation steps. Got when running `yarn gatsby develop`:

```
TypeError: getResolve is not a function
  
  - webpack.config.js:767 
    [skyhitz]/[gatsby]/src/utils/webpack.config.js:767:26
  
  - withUnimodules.ts:203 
    [skyhitz]/[@expo]/webpack-config/src/addons/withUnimodules.ts:203:52
  
  - ExternalModuleFactoryPlugin.js:21 
    [skyhitz]/[webpack]/lib/ExternalModuleFactoryPlugin.js:21:21
  
  - util:124 deprecated
    node:internal/util:124:12
    

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

45

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nodenv/versions/16.14.2/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - ~/.nodenv/versions/16.14.2/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.6
    Expo Workflow: managed

### Reproducible demo

`yarn gatsby develop`

**Comment by clarksandholtz** [comment]
@alejomendoza  can you describe what the intended use is for the two together?

**Comment by alejomendoza** [comment]
We have a cross platform app, we want to improve SEO on the web side while having one code base for iOS and Android.

**Comment by clarksandholtz** [comment]
So is there code that you want to be running both in your app and on your website?

**Comment by devbalmuda** [comment]
How about using the react snap or react snapshot to pre rendering ? It can help to set the SEO things.
