### ISSUE TITLE
In App Purchase - Native Module Cannot Be Null Error

### ISSUE THREAD

**Issue by frumpish** [expo/expo#17581]
### Summary

Cannot install and run In App Purchases API even in a bare minimum starter project. The instructions for bare workflow and IAP on documentation is followed.
https://docs.expo.dev/bare/hello-world/
https://docs.expo.dev/versions/v45.0.0/sdk/in-app-purchases/

Installement:
```
expo init --template bare-minimum (Name the app etc.)
expo install expo-in-app-purchases
npm install expo-in-app-purchases
npx pod-install
```

When API is imported to App.js, it fails with error:
<img width="337" alt="Ekran Resmi 2022-05-20 10 06 58" src="https://user-images.githubusercontent.com/8101737/169472687-00ccc58c-4230-4e69-a9b4-5c4a543128d6.png">

```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.0.26:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:121155:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

App.js
```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import * as InAppPurchases from 'expo-in-app-purchases';
export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

package.json
```
{
  "name": "iaptest",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~45.0.0",
    "expo-in-app-purchases": "~13.0.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-web": "0.17.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

```

app.json
```
{
  "expo": {
    "name": "iaptest",
    "slug": "iaptest",
    "version": "1.0.0",
    "assetBundlePatterns": [
      "**/*"
    ]
  }
}

```

metro.config
```
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

module.exports = getDefaultConfig(__dirname);

```

Index.js
```
import { registerRootComponent } from 'expo';

import App from './App';

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App);

```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      npm: 8.4.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.4.6
    Expo Workflow: bare

### Reproducible demo

Snack uses Expo 44.0.0 yet when package.json is updated accordingly, it still gives the same error.
[Snack link](https://snack.expo.dev/@eddyildiz/iap)

**Comment by byCedric** [comment]
Hi @frumpish! I think the error on both Snack and local project refers to the same thing. If the native module is `null`, that means the `expo-in-app-purchase` module isn't present in your native app build. It means that the API is just not available on the native side, which makes sense for Snack.

That being said, it should work for your local project in bare. Did you rebuild the app binary after running this?
```
expo init --template bare-minimum (Name the app etc.)
expo install expo-in-app-purchases
npm install expo-in-app-purchases
npx pod-install
```

It should work if you start your project with something like `expo run:ios -d <DEVICE_UUID>`.

**Comment by andrisole92** [comment]
I have the same problem after running

`expo install expo-location`

still can't get my app running.

**Comment by brentvatne** [comment]
@andrisole92 - see @byCedric's suggestion above. you need to run pod install. alternatively, use `expo run:ios` which will do that for you each time you run it
