### ISSUE TITLE
GLView crashes Expo on Android in Genymotion

### ISSUE THREAD

**Issue by ghost** [expo/expo#1758]
### Problem summary

During the React Native workshop at React Europe 2018 I think I've hit a bug in Expo. None of the examples provided by Gaetan Renaudeau for his session on gl-react ran in my Android simulator on Genymotion. As soon as Expo launches, it just crashes.

I've tested the same code on an actual Android phone & tablet as well as on my iPhone, and it runs great on all these devices. Almost everyone else in the workshop was using a MacBook Pro and running the code in the iOS simulators, and no-one seemed to experience any problems, so I think it's safe to say that the problem is limited to the Android simulator alone. 

### Expected Behavior

gl-react apps should run without crashing.

### Actual Behavior

Expo crashes when running gl-react apps in an Android simulator on Genymotion. Stacktrace shows that it's a GLView crash.
I'm running a Google Nexus 5 virtual device with Android 6.0.0 API 23 on Genymotion version 2.12.1 on Ubuntu Linux 18.04 LTS 64-bit (native Linux, not in a VM). Please see the attached screenshots and stacktrace of the error for more details.

**Stacktrace:**
[stacktrace.txt](https://github.com/expo/expo/files/2007810/stacktrace.txt)

**Screenshots:**
![genymotion](https://user-images.githubusercontent.com/31992177/40100919-02f067f4-58e6-11e8-9db4-f5f4d51fe7dc.png)
![nexus_sim](https://user-images.githubusercontent.com/31992177/40100921-04cb0980-58e6-11e8-8e86-fa5e79bba8e4.png)
![nexus_config](https://user-images.githubusercontent.com/31992177/40100928-0a6a24a2-58e6-11e8-91fc-169b07e72328.png)

### Reproducible Demo

1. Clone Gaetan's repo at https://github.com/gre/workshop-gl-react-expo
2. Install Genymotion and create a virtual device
3. Launch the example app from the repo in Expo on the Android simulator
4. See how Expo crashes immediately after launching

**Comment by esamelson** [comment]
@nikki93 @EvanBacon is this a known issue, that some GL functionality is not available on emulators?

**Comment by tsapeta** [comment]
I'm not sure it that worked on Genymotion emulator but I've been using AVD emulator and it's been working fine. I'll try to reproduce it on Genymotion.

**Comment by tsapeta** [comment]
Are you still facing this issue? I wasn't able to reproduce it and a lot of time has passed, so I'm closing this but feel free to comment here if this is still happening 🙂
