### ISSUE TITLE
expo-updates freezes application on android. 

### ISSUE THREAD

**Issue by hassanAwanAlvi** [expo/expo#17587]
### Summary

I just want to restart my expo app, I don't really need an update package. Mostly I use it for Language switch or workspace switching. 

I am using this function to restart my application.

```
import {reloadAsync} from 'expo-updates';
const Restart = async () =>{
    if(Platform.OS=="web")
    {
        window.location.reload()
    }
    else{
        
        await reloadAsync();
        

    }
}
```

It works fine on IOS, but on android, it freezes the application. 
Android logs are 

2022-05-20 16:35:48.216 26051-26118/ E/UpdatesModule: Failed to relaunch application
    java.lang.Exception: No launchable update was found. If this is a bare workflow app, make sure you have configured expo-updates correctly in android/app/build.gradle.

<img width="1852" alt="Screenshot 2022-05-20 at 4 47 53 pm" src="https://user-images.githubusercontent.com/17249527/169564920-4da4d752-5442-4d76-b217-353d9fd58057.png">

### SDK Version

45.0.0

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 8.10.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: bare

### Reproducible demo

init a new project. 
Add expo-updates 

run expo run:android --variant release

**Comment by hassanAwanAlvi** [comment]
Any response?

**Comment by mukash** [comment]
Facing same issue!!!!!
