### ISSUE TITLE
Dropbox folder not shown for DocumentPicker

### ISSUE THREAD

**Issue by riwu** [expo/expo#1759]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/riwu-9c2951f7-06e6-4e15-a010-5e6941aa0799.tar.gz

### Steps to Reproduce
https://snack.expo.io/@riwu/document-picker-dropbox

When using `ImagePicker.launchImageLibraryAsync`, the Dropbox and Gallery folders are shown on the sidebar for the user to select: 
<img src="https://i.imgur.com/AVGlTye.jpg" height="400px" />

However, these folders are not shown for `DocumentPicker` and the users have no way of selecting a file from their Dropbox:
<img src="https://i.imgur.com/pbhwAvK.jpg" height="400px" />

**Comment by joshg2k** [comment]
+1 this issue as it's relevant to our project

**Comment by victordudyk** [comment]
+1  this issue as it's relevant to our project

**Comment by RichardFevrier** [comment]
👍

**Comment by clems36** [comment]
Hey @esamelson this is still the case, any plans on using `ACTION_GET_CONTENT` for the document picker ?

**Comment by riwu** [comment]
-stale
