### ISSUE TITLE
Video works in iOS simulator, Expo Go app, Android device, but *not* on iPhone via TestFlight

### ISSUE THREAD

**Issue by pors** [expo/expo#17594]
### Summary

Using `expo-av` I try to show a video in my app. It works on all platforms but not for iOS in "production" via TestFlight.

Video works in iOS simulator, Expo Go app, Android device, but not on iPhone via TestFlight.

I use the exact example from the documentation, see snack below.

No errors.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.2.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.21 => 0.16.23
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.1
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: managed
```

### Reproducible demo

https://snack.expo.dev/@tositsa/video

**Comment by pors** [comment]
Screenshot. Pressing on "Play" has no effect.

![2022-05-21 18 08 24](https://user-images.githubusercontent.com/1078320/169657613-39677b7d-21d9-49f1-9152-b47e225cbc5b.jpg)

**Comment by EHF32** [comment]
I'm having the same problem, any workaround?

**Comment by byCedric** [comment]
Hi! What happens if you run your project locally in production mode? E.g. `expo run:ios --configuration Release` or `expo run:android --variant Release` (optionally with `--device` to run it directly on your phone). If there are errors, they should be visible that way.

**Comment by pors** [comment]
@byCedric Hi! Thanks for replying! 

The command `expo run:ios --configuration Release` results in `error: API request failed`. First time I use the `expo run` command. Seems very useful. I'll try and see if I can solve this.

**Comment by justblender** [comment]
Could you try upgrading `expo` package to version `45.0.4`? Based on your environment it seems like you're using `expo@45.0.1`, which has a severe bug within `expo-modules-core`. Refer to #17395 for more info.

**Comment by pors** [comment]
> What happens if you run your project locally in production mode? E.g. `expo run:ios --configuration Release` or `expo run:android --variant Release` (optionally with `--device` to run it directly on your phone). If there are errors, they should be visible that way.

I do indeed got an error then `[CoreFoundation] AddInstanceForFactory: No factory registered for id <CFUUID 0x600001382f40> F8BB1C28-BAE8-11D6-9C31-00039315CD46`

And the problem is also there in the simulator now.

**Comment by pors** [comment]
> @pors and @EHF32, could you try upgrading `expo` package to version `45.0.4`? Based on your environment it seems like you're using `expo@45.0.1`, which has a severe bug within `expo-modules-core`. Refer to #17395 for more info.

Yes that solved it (in the simulator)! Thanks!

I'll do another build via EAS and will close this issue.

**Comment by pors** [comment]
Also works on device with TestFlight, thanks!
