### ISSUE TITLE
Receiving IAPErrorCode.SERVICE_UNAVAILABLE when listing IAP products on Android

### ISSUE THREAD

**Issue by stevenmusumeche** [expo/expo#17604]
### Summary

I have IAP setup and working fully on iOS.  I am now trying to get it working on Android, using a physical device (`npx react-native run-android`).  However, when attempting to list the products using the same code (with getProductsAsync), I'm receiving IAPResponseCode.ERROR and IAPErrorCode.SERVICE_UNAVAILABLE.  I believe that I've setup the subscription in Google Play Store correctly.

Product ID: premium.monthly.v1
Benefits: Access to all features
Monthly, auto-renewing
173 countries / regions
Active

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.0 - ~/.nvm/versions/node/v16.9.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.9.0/bin/yarn
      npm: 7.21.1 - ~/.nvm/versions/node/v16.9.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.3.0 => 8.3.0
      expo: ^42.0.0 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

### Reproducible demo

```
  useEffect(() => {
    async function fetchProducts() {
      try {
        await connectAsync();
        const { responseCode, results, errorCode } = await getProductsAsync(
          items,
        );
        if (responseCode === IAPResponseCode.OK && results) {
          // success
        } else {
          // this block is hit when running on Android
          console.error({ errorCode, responseCode });
        }
      } catch (e) {
        // error
      }
    }

    fetchProducts();
  }, [actions, executeCompletePurchase, user]);
```

**Comment by byCedric** [comment]
Hi @stevenmusumeche! Error code `SERVICE_UNAVAILABLE` [is related to network connections](https://github.com/expo/expo/blob/main/packages/expo-in-app-purchases/src/InAppPurchases.types.ts#L93), somehow the GPlay store can't be reached to fetch the in-app purchase data. can that be correct? If so, try running from another network or phone to see if there is anything network related that might be throwing things off.

**Comment by stevenmusumeche** [comment]
@byCedric I've found the issue was that the device I was testing on was not using the Google account associated with my application.
