### ISSUE TITLE
SDK 45 expo-modules-core errors

### ISSUE THREAD

**Issue by TalTomax** [expo/expo#17609]
### Summary

Hey, i followed this guide: https://blog.expo.dev/expo-sdk-45-f4e332954a68 to upgrade to SDK 45 from SDK 44.

After running "expo upgrade" the output is: 

✅ The following packages were updated:
expo-av, expo-battery, @react-native-community/netinfo, @react-native-async-storage/async-storage, expo-barcode-scanner, expo-file-system, expo-image-manipulator, @react-native-community/slider, @react-native-masked-view/masked-view, react-native-web, react-dom, expo-keep-awake, expo-status-bar, expo-screen-orientation, react-native-gesture-handler, react, react-native-screens, expo-splash-screen, react-native, expo-camera, react-native-safe-area-context, expo-modules-core, react-native-reanimated, expo-image-picker, jest-expo, jest, typescript, @babel/core, @types/react, @types/react-native, expo

🚨 The following packages were not updated. You should check the READMEs for those repositories to determine what version is compatible with your new set of packages:
@react-navigation/native, @react-navigation/stack, @reduxjs/toolkit, axios, events, expo-video-player, i18next, moment, react-i18next, react-native-aes-crypto, react-native-animatable, react-native-device-info, react-native-event-listeners, react-native-material-menu, react-redux, redux-persist, @types/jest

I run the command expo prebuild to sync with Android studio.

**I tried to build the project and got the following errors:**
node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/AppLoaderProvider.java:3: error: package android.content does not exist import android.content.Context;
node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/AppLoaderProvider.java:4: error: package android.content.pm does not exist
import android.content.pm.PackageManager;
node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/AppLoaderProvider.java:5: error: package android.util does not exist
import android.util.Log;
.......
run the command: npx react-native run-android --variant=release print the same errors.
I tried to delete node_modules/package-lock.json/sync project with gradle file but nothing helps.

expo start command works fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/opt/node@16/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/opt/node@16/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
        Build Tools: 29.0.2, 32.0.0, 32.1.0, 33.0.0, 33.0.0
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.6
    Expo Workflow: bare

### Reproducible demo

{
  "name": "myapp",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/babel.config.js",
      "!**/jest.setup.js"
    ]
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/netinfo": "8.2.0",
    "@react-native-community/slider": "4.2.1",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@reduxjs/toolkit": "^1.8.1",
    "axios": "^0.26.1",
    "events": "^3.3.0",
    "expo": "^45.0.0",
    "expo-av": "~11.2.3",
    "expo-barcode-scanner": "~11.3.0",
    "expo-battery": "~6.2.0",
    "expo-camera": "~12.2.0",
    "expo-file-system": "~14.0.0",
    "expo-image-manipulator": "~10.3.1",
    "expo-image-picker": "~13.1.1",
    "expo-keep-awake": "~10.1.1",
    "expo-modules-core": "~0.9.2",
    "expo-screen-orientation": "~4.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-video-player": "^2.0.4",
    "i18next": "^21.8.3",
    "jest": "^26.6.3",
    "jest-expo": "^45.0.0",
    "moment": "^2.29.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-i18next": "^11.16.9",
    "react-native": "0.68.2",
    "react-native-aes-crypto": "^2.1.0",
    "react-native-animatable": "^1.3.3",
    "react-native-device-info": "^8.7.1",
    "react-native-event-listeners": "^1.0.7",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-material-menu": "^2.0.0",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-web": "0.17.7",
    "react-redux": "^7.2.8",
    "redux-persist": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/jest": "^27.5.1",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.67.6",
    "typescript": "~4.3.5"
  },
  "private": true
}

**Comment by byCedric** [comment]
Hi @TalTomax! Did you also try `expo run:android` (optionally with `--device` if you want to run it on a phone instead). We also support the `--variant Release` flag if you want to test in production mode.

**Comment by TalTomax** [comment]
> Hi @TalTomax! Did you also try `expo run:android` (optionally with `--device` if you want to run it on a phone instead). We also support the `--variant Release` flag if you want to test in production mode.

I will check it, but what if i want to build bundle apk to deploy to store?

**Comment by haywhy2019** [comment]
did you solve this yet? ....im stuck here too been on it all day

**Comment by TalTomax** [comment]
> @TalTomax! did you solve this yet? ....im stuck here too been on it all day

Sorry, not yet. I'm still on sdk 44 waiting for fix.

**Comment by dimaportenko** [comment]
I was able to solve the issue with run Upgrade Assistance and upgrading Android Gradle Plugin to the latest version.       

![CleanShot 2022-05-30 at 22 04 57@2x](https://user-images.githubusercontent.com/6594232/171048814-364676cc-5953-4fd3-b59d-6511063b7016.png)

**Comment by haywhy2019** [comment]
Thank you for your response.

**Comment by TalTomax** [comment]
@dimaportenko WOW! works like magic thank you!!

**Comment by aprilmintacpineda** [comment]
Fix when not using Android Studio:

1. On `android/gradle/wrapper/gradle-wrapper.properties`, set `distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip`
2. On `android/build.gradle`, set `classpath("com.android.tools.build:gradle:7.2.1")`
3. Rebuild

**Comment by ericmesmo** [comment]
> Fix when not using Android Studio:
> 
>     1. On `android/gradle/wrapper/gradle-wrapper.properties`, set `distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip`
> 
>     2. On `android/build.gradle`, set `classpath("com.android.tools.build:gradle:7.2.1")`
> 
>     3. Rebuild

For me doesnt work

**Comment by AdnanAshraf-gol** [comment]
https://github.com/expo/expo/issues/17609#issuecomment-1250151928

it didnt  work for me either 
any other solution?

**Comment by AdnanAshraf-gol** [comment]
> Fix when not using Android Studio:
> 
> 1. On `android/gradle/wrapper/gradle-wrapper.properties`, set `distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip`
> 2. On `android/build.gradle`, set `classpath("com.android.tools.build:gradle:7.2.1")`
> 3. Rebuild

it didnt work for me either
any other solution?

**Comment by dimaportenko** [comment]
It happened to me when my react-native version was below the version of expo 45 going out of the box. I think the best solution would be to update react native version.

**Comment by anatelli10** [comment]
Downgrading from JDK 19 to JDK 17 resolved the issue for me.
