### ISSUE TITLE
Expo video - Help about full screen

### ISSUE THREAD

**Issue by safacaki** [expo/expo#1761]
Hi everybody, my problem is very easy but i cant find fixed. I'm using expo video compoment and use 
useNativeControls= {true} feature. I'm doing video full screen but video zooming. How can i disable this? Detailed images below

<img width="353" alt="ekran resmi 2018-05-16 17 26 09" src="https://user-images.githubusercontent.com/6898758/40123800-b703448e-592f-11e8-84e6-976696a359de.png">
<img width="359" alt="ekran resmi 2018-05-16 17 26 31" src="https://user-images.githubusercontent.com/6898758/40123801-b725704a-592f-11e8-92e2-33caba6bfe40.png">

**Comment by ccheever** [comment]
I'm confused about exactly what the problem is. What are the two images showing?

**Comment by esamelson** [comment]
Hi @safacaki - have you tried setting the [`resizeMode` prop](https://docs.expo.io/versions/v27.0.0/sdk/video#resizemodea-string-describing-how-the-video-should) to `RESIZE_MODE_CONTAIN`?
