### ISSUE TITLE
Expo-auth-session - redirectUri

### ISSUE THREAD

**Issue by hrdyjan1** [expo/expo#17617]
### Summary

Hello, I've been trying to set up auth session, but I don't know, how to configure the project. I am struggling with redirecting - back to the app.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ^45.0.4 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.67.2 => 0.67.2
    Expo Workflow: bare

### Reproducible demo

**The question is:**
How do I get from workflow: Reality, to workflow: Expectation.

I also tried some Linking catch, but it also didn't work in my case.
Project workflow is based on https://docs.expo.dev/guides/authentication/. 
Even a little help would be great.

![expo-auth-session_redirect-uri_error](https://user-images.githubusercontent.com/28002757/169875695-ff70779e-5f5b-4794-a006-7640c340f79d.png)

```
import * as AuthSession from 'expo-auth-session';
import * as WebBrowser from 'expo-web-browser';
import React from 'react';
import {Button} from 'react-native';

WebBrowser.maybeCompleteAuthSession();

function Page() {
  const [, , promptAsync] = AuthSession.useAuthRequest(
    {
      redirectUri: 'https://www.fake_my_app.com/verify', // Fake http redirectUri
      clientId: '123ABCD456', // Fake client id
      responseType: 'token',
      scopes: ['openid'],
    },
    {
      tokenEndpoint: 'https://fake_open_id.com/token/',
      authorizationEndpoint: 'https://fake_open_id.com/authorization/',
    },
  );

  return <Button title="Handle auth" onPress={() => promptAsync()} />;
}

export {Page};

```

**Comment by hrdyjan1** [comment]
@jan-karnik Long story short, we used a different approach without expo-auth-session.
(CZ: Pracovali jsme s RN v0.65, tam nefungovalo takřka nic. Ani Expo ani react-native-app-auth. Po pár dnech práce jsem to vyřešil oblikou přes ten react-native-app-auth a parsování URL, zásah do nativního kódu na androidu a úprava zdrojáku AppAuth pro iOS. To bylo dost komplikovaný řešení ale fungovalo. Nedávno jsme aktualizovali na RN 0.70 a tam ten react-native-app-auth už funguje hezky. Takže bych doporučil aktualizovat. Kdyby ještě něco tak piš.)

**Comment by jan-karnik** [comment]
Díky za zprávu! To zní jako sranda.. Ty píšeš, že bare workflow, tzn. tu react-native-app-auth nepoužíváte s Expem ale s čistým RN, je to tak? Každopádně vyzkouším s Expem a uvidím jestli zafunguje:) 

Kdyby se povedlo hodím sem pak komentář, kdyby tu někdo hledal alternativu k nefungující redirectUri pro Android Standalone workflow. 
Dík za info

**Comment by hrdyjan1** [comment]
Ano, čistý RN.

**Comment by jan-karnik** [comment]
For anyone struggling to get `expo-auth-session` **Android** in the standalone workflow, working. 
This worked for me: https://github.com/expo/expo/issues/12044#issuecomment-1145899190

Setting up android intent filter to intercept the attempt to redirect back to the app..

**Comment by jurakin** [comment]
Tiež podobný problém,`openAuthSessionAsync` síce zachytí `redirectUri`, ale expo router tiež a snaží sa na ňu navigovať. Vyriešil som pridaním componentu, ktorý vráti router o krok dozadu. (nemusím sa hrať s Android intent filtrami + cross platform)

```tsx
import { Loading } from "@/lib/components";
import { useRouter } from "expo-router";
import { useEffect } from "react";

export default () => {
  const router = useRouter();

  useEffect(() => {
    if (router.canGoBack()) {
      router.back();
    } else {
      router.replace("/");
    }
  }, []);

  return <Loading />;
};
```
