### ISSUE TITLE
Detached app with ExpoKit crashes on Android

### ISSUE THREAD

**Issue by domialex** [expo/expo#1762]
I had to detach since I need to do background geofencing and I encountered this error.

### Steps to Reproduce

1. `create-react-native-app` test
2. `yarn eject` with ExpoKit
3. add `keepRuntimeAnnotatedClasses false` in Gradle because of #1166
4. Build and run

`E/com.amplitude.api.DeviceInfo: Encountered an error connecting to Google Play Services
                                java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                    at com.amplitude.api.DeviceInfo$CachedInfo.getAndCacheGoogleAdvertisingId(DeviceInfo.java:207)`

It seems the Amplitude SDK crashes, anyway to fix this?

**Comment by esamelson** [comment]
Hi @domialex - this error can be a red herring. Is your project running (`exp start`) at the time you make the build?

**Comment by domialex** [comment]
Yes I did the `ext start`, still the same error.
It's a clean **create-react-native-app** project.

**Comment by esamelson** [comment]
@domialex have you tried making a release build (`./gradlew assembleProdRelease`)? Note that you'll need to publish your expo project first (`exp publish`) since a release build, by default, will grab the most recent published version of your JS.

**Comment by domialex** [comment]
I can't run this command because I'm on Windows and #1607 . Any ideas?

**Comment by esamelson** [comment]
Hi @domialex - I'm unclear as to why that issue would prevent you from running the gradle command. Could you explain more? What about if you try making a `prodRelease` build from Android Studio?

**Comment by domialex** [comment]
Sure, there's no .bat file generated in the android folder. How can I run this command in another way?

**Comment by esamelson** [comment]
@domialex you could [make a release build from inside of Android Studio](https://developer.android.com/studio/run/) (choose a release build variant), or you could try [generating a gradle wrapper yourself](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:adding_wrapper).

**Comment by domialex** [comment]
Ok it works in prodRelease. Very weird, any ideas why this happens?

**Comment by esamelson** [comment]
Glad to hear it! Sorry for the inconvenience. There's a known issue with multidex not working properly in debug builds with older versions of Android. The actual crash was probably slightly earlier in your adb logs.

Going to go ahead and close this now as the normal workaround seems to be working for you.

**Comment by domialex** [comment]
Thanks your help, keep up the good work.
