### ISSUE TITLE
GIFs not animated in builds created via EAS build

### ISSUE THREAD

**Issue by Chrissi2812** [expo/expo#17627]
### Summary

In the Expo Go App the Gif is animated as expected but once I built it via EAS Build it becomes static.
Don't know if this only regards remote Gifs

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.24.2 - ~\AppData\Roaming\npm\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 19, 22, 23, 25, 26, 27, 30
        Build Tools: 22.0.1, 23.0.3, 24.0.3, 25.0.3, 27.0.3, 30.0.3, 31.0.0
        System Images: android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-22 | Android TV ARM EABI v7a, android-22 | Android TV Intel x86 Atom, android-22 | Android Wear ARM EABI v7a, android-22 | Android Wear Intel x86 Atom, android-22 | ARM EABI v7a, android-22 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64
    npmPackages:
      expo: ~45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed
```

### Reproducible demo

Git Repo: https://github.com/Chrissi2812/expo-issue-repro/tree/eas-gif-not-animated
EAS Build (APK): https://expo.dev/accounts/pixel-kraft/projects/expo-broken/builds/de2061af-5005-4605-aad7-08782a883234 

1. Created new project via `expo init my-app --npm`
2. Basic eas config created via `eas build:configure`
3. Add a GIF to App.tsx `<Image style={{ width: 100, height: 100 }}  source={{ uri: 'https://c.tenor.com/MYZgsN2TDJAAAAAC/this-is.gif' }}>`
4. Build with preview profile `eas build --profile=preview`

**Comment by Kudo** [comment]
a new release of template is necessary, we will release today or tomorrow with other fixes. i'll also update here once we published the new version. thanks for your waiting.

**Comment by Kudo** [comment]
hi there! we've released the fix. please let us know whether it works for you. thank you!

**Comment by a-eid** [comment]
@Kudo do we need to include a plugin or something, gifs are not working with `expo prebuild` & `expo run` commands.

**Comment by Kudo** [comment]
@a-eid if you did run prebuild before, you could try to do `expo prebuild --clean` again. making sure `android/build.gradle` should have frescoVersion as #17636

**Comment by Chrissi2812** [comment]
Yes it works perfect. Have tested it in 2 projects with managed workflow.
I didn't run `expo prebuild`, but for managed projects this is done on the EAS servers, right?
