### ISSUE TITLE
[SDK45][expo-analytics-amplitude] Deprecated library in sdk 45 without any other option for managed projects (@amplitude/react-native needs pod install to work)

### ISSUE THREAD

**Issue by WolfgangTorres** [expo/expo#17632]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by WolfgangTorres** [comment]
The amplitude library is being deprecated in sdk 45, in the [expo-analytics-amplitude](https://docs.expo.dev/versions/latest/sdk/amplitude/) documentation it sends to the official Amplitude library in which it asks to do a `pod install` and due to this it is impossible to use the library for managed projects.

How are we going to use amplitude in managed projects if you deprecate the library? Or is there something I'm missing that makes it possible?

**Comment by byCedric** [comment]
Hi @WolfgangTorres! It's correct that we are deprecating `expo-analytics-amplitude`, and that would result in you being unable to use that library in Expo Go. But, we do have an alternative for that.

We can now build your app with custom native libraries, including `@amplitude/react-native`. That would be [our EAS Build service](https://docs.expo.dev/build/introduction/). Just like Turtle, we'll build the app on our servers and return you the flavor of the build you want.

Besides EAS Build, we also have [custom dev clients](https://docs.expo.dev/development/introduction/). It's basically a customized version of Expo Go, but using only your used native modules (including custom, and again, including `@amplitude/react-native` :)).

Hope this helps!
