### ISSUE TITLE
Android: Cannot read packageName from /expo/android/app/src/main/AndroidManifest.xml

### ISSUE THREAD

**Issue by alejomendoza** [expo/expo#1764]
Build fails when running `cd android; ./run.sh; cd ..` due to this error. 
![screen shot 2018-05-16 at 7 25 38 pm](https://user-images.githubusercontent.com/5351127/40150415-1c7b244e-593f-11e8-8e16-9c729b8b33cf.png)

**Comment by themakerman** [comment]
@alejomendoza how did you solved this?

**Comment by sen-miao** [comment]
@themakerman, you need two steps to solve it
First, copy expoview module AndroidManifest.xml to app/src/main directory
Second, './run.sh'

**Comment by IOpuk** [comment]
@sen-miao Thanks!

**Comment by new-soul** [comment]
I copy expo/template-files/android/AndroidManifest to app/src/main directory.
