### ISSUE TITLE
[expo 45.0.4] not able to connect to debugger

### ISSUE THREAD

**Issue by veeramarni** [expo/expo#17643]
### Summary

After upgrading from expo 44.0.4 to 45.0.4 we are able to open the debugger from ios simulator. This is a show stopper for us so we downgraded back to 44.0.4. I don't see any existing issue on it so create a this ticket.

When the debugger is enabled we get this error and a blank app screen. We don't have this issue in v44.

![image](https://user-images.githubusercontent.com/3382355/171846915-864b4861-74a7-4cf7-9ace-69baecb4eff9.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45.0.4

### Environment

npx expo-env-info
npx: installed 2 in 2.293s

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.19.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/Documents/development/workspace/projects/Exclusive/pubngo/node_modules/.bin/yarn
      npm: 6.14.11 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

https://github.com/cdmbase/fullstack-pro

The mobile code is in https://github.com/cdmbase/fullstack-pro/tree/master/portable-devices/mobile

from root, you can start mobile

`yarn && yarn build && lerna exec --scope=*mobile-device yarn watch`

you need to have `lerna` installed globally if it didn't work.

**Comment by esamelson** [comment]
Hey @veeramarni - sorry you are having trouble with the upgrade. It looks like your project is pretty sizable, so I'd recommend trying to pare down and create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). This can help narrow down the issue (in which case we might be able to help investigate further) or you might even figure it out along the way!

**Comment by Ray-Frost** [comment]
Same issue.

**Comment by hhhien2903** [comment]
Same issue
