### ISSUE TITLE
SecureStore does not support large strings

### ISSUE THREAD

**Issue by Gitii** [expo/expo#1765]
### Environment
Environment:                                                                                                
  OS: Windows 10                                                                                            
  Node: 8.10.0                                                                                              
  Yarn: 1.5.1                                                                                               
  npm: 5.6.0                                                                                                
  Watchman: Not Found                                                                                       
  Xcode: N/A                                                                                                
  Android Studio: Not Found                                                                                 
                                                                                                            
Packages: (wanted => installed)                                                                             
  expo: 27.0.2-rc.0 => 27.0.2-rc.0                                                                          
  react: 16.3.1 => 16.3.1                                                                                   
  react-native: expo/react-native#sdk-27 => 0.55.2                                                                           
                                                                                                            
The target is android.

### Steps to Reproduce
1. Check out https://github.com/Gitii/native-component-list
2. Start App on android (only android is relevant for me)
3. Navigate to SecureStore-screen
4. Fill in a key of your choice but leave value as is
5. Press "Store value with key". It will work.
6. Press "Get value with key". It will fail: **"Could not decrypt the item in SecureStore"**

### Expected Behavior

The string should be read from SecureStore.

### Actual Behavior

The operation fails and retrieval of the string is not possible.

### Reproducible Demo

https://github.com/Gitii/native-component-list
Just clone, setup app as usual and follow "Steps to Reproduce".

It is a forked example repo, I just modified a single line to generate a large string for the sake of simplicity.

### Remarks

Usually strings smaller than ~82000 work for me.
If getItemAsync works for you, please increase the string length (e.g. double it).

If such large strings are not supported, the documentation should be updated accordingly.
Currently there are not limitations listed: https://docs.expo.io/versions/latest/sdk/securestore.

Best regards,

Gitii

**Comment by esamelson** [comment]
Hi @Gitii -- thanks for the report. We'll look into this and/or update the docs accordingly.

**Comment by hammod27** [comment]
@esamelson any update on this? I am having issues storing strings larger than ~13000 characters (using a LG G Pad tablet).

**Comment by a-fortunato** [comment]
We've been facing this issue too.
Fixed it changing the content we were sending to setItemAsync and so making it smaller, but it would have been nice if the docs were updated, it'd be easier to find and fix the problem.

**Comment by ide** [comment]
Large strings are not supported. If you want to chunk yourself at the application layer you can try that. It sounds like what we need to do is set a cap that works across most phones (2KiB maybe) and document + throw an error.

**Comment by Slapbox** [comment]
@ide, thanks for addressing this!
