### ISSUE TITLE
Video from ImagePicker is unplayable on many devices (HEVC)

### ISSUE THREAD

**Issue by cchbr** [expo/expo#17673]
### Summary

Selecting a video from ImagePicker.launchImageLibraryAsync on IOS and uploading it returns a video encoded with HEVC, which can't be played on Chrome, Firefox or Android. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.20.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ^45.0.0 => 45.0.1
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare

### Reproducible demo

let result = await ImagePicker.launchImageLibraryAsync({
    mediaTypes: ImagePicker.MediaTypeOptions.All,
    allowsEditing: true,
    aspect: [4, 3],
    quality: 1,
});

const uploadResult = await FileSystem.uploadAsync(url, result.uri, {
    httpMethod: 'POST',
    uploadType: FileSystem.FileSystemUploadType.MULTIPART,
    fieldName: 'demo_vid'
    });

**Comment by hirbod** [comment]
Might be worth a shot at the forums or canny for a feature request though!

**Comment by brentvatne** [comment]
seems like a neat idea, i marked this as a feature request though :)
