### ISSUE TITLE
Publish node-websql fork as a proper package

### ISSUE THREAD

**Issue by robertjd** [expo/expo#1767]
Hi there,

The [expo-sdk](https://github.com/expo/expo-sdk) is depending on a Github tarball for the node-websql package:

https://github.com/expo/expo-sdk/blob/master/package.json#L65

This causes a problem for my situation.  I use an NPM mirror (artifactory) on our internal network, and we use a self-signed certificate to talk with the mirror (we tell NPM to use the mirror with the self-signed cert).  This works fine when we're consuming packages that actually exist in the NPM registry (as they are pulled from public NPM into the mirror on demand) but this breaks when we have to request a URL outside of the mirror, such as github, because the certificate chain fails when the NPM client tries to talk to Github.

Could you please consider publishing your fork of node-websql as a proper forked package, with a different name, and consume it as a standard NPM package?  Perhaps you could publish it as `@expo/node-websql`?

Thank you!

**Comment by esamelson** [comment]
Hi @robertjd - thanks for pointing this out. I've just published `expo@27.0.2` which depends on npm package `@expo/websql@1.0.1` instead. Going to go ahead and close this.

**Comment by robertjd** [comment]
Awesome, thank you so much @esamelson !
