### ISSUE TITLE
SDK 45 + Dev Client + Android – Unable To Find Development Servers

### ISSUE THREAD

**Issue by garviand** [expo/expo#17675]
### Summary

When I build the Dev Client on Android and try to run it, I get this screen (both on physical device and emulator):

<img width="619" alt="Screen Shot 2022-05-28 at 12 12 15 PM" src="https://user-images.githubusercontent.com/2416232/170835913-b52bddd7-ef9f-45a5-998c-8cb5bff9ae32.png">

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

expo-dev-client: 0.9.6

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      npm: 6.14.17 - ~/Code/PairUp/pairup-mobile/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.7
    Expo Workflow: bare

### Reproducible demo

I can't tell if any of the application code affects this issue. It runs on the iOS dev client and I don't get any errors. I understand that a demo may be needed but I'm unsure how to describe a reproducible method.

**Comment by ajsmth** [comment]
it seems as thought the url received by the app is not quite right - how are you loading the deep link?

**Comment by garviand** [comment]
@ajsmth I open a virtual android device in Android Studio and then press `a` in the Expo CLI to automatically open Expo Go on the Android Device, which is when the attached screen shows. Note that this process works correctly with the iOS simulator.

**Comment by garviand** [comment]
@ajsmth not sure if this is helpful but I just created an android build using:

`eas build --profile development --platform android`

**eas.json**
```
{
  "cli": {
    "version": ">= 0.52.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

And when I installed it on my device and opened it went to this screen (with no error messages):

![Screenshot_20220531-122654](https://user-images.githubusercontent.com/2416232/171236345-7854f2cc-dea3-4ecb-ac3b-3efe44f0c141.png)

**Comment by ajsmth** [comment]
Hmm I've just tested this out myself and wasn't able to reproduce - can you provide a repro that I can clone and try on my end? I'm fairly certain your issue is configuration related and not a bug!

**Comment by chakafasano88** [comment]
I ran into a similar issue where an error was thrown, "Server cannot be reached".

Once you create an expo development build by running `eas build --profile development --platform android` you can then scan the QR code in your terminal OR go to the expo link. This will install your development app to you phone. 

Once installed, run `expo start --dev-client`.  Then, scan the QR code in your terminal window, it will open the development application for you.

I had issues adding the direct server url, but scanning the QR code worked.

**Comment by nickwelp** [comment]
I'm running into this issue right now. EAS builds the the developmental build, pushes it to the Android device, and then says "Server cannot be reached." What's additionally strange is this problem just emerged for this first time this morning with no code changes. Starting with dev client, and scanning the QR code, it asks me to pick an App to open the QR code with. The EAS build app is not there, nor is Expo Go or anything else Expo related. 

I also am not able to add the direct URL. I'm sure this problem will remain closed but if you run into this issue too, know you're not alone! If I fix it I'll report back

**Comment by nickwelp** [comment]
I had this same issue. I'm reporting back to say that my kid had jimmied with the router had blocked some port communications,  and once I fixed that it resolved this issue.
