### ISSUE TITLE
How are the Magnetometer Measurements calibrated? 

### ISSUE THREAD

**Issue by dmenneck** [expo/expo#17678]
### Summary

The official Magnetometer expo website does not explain how to calibrate the values of Magnetometer. Unfortunately I could not find the corresponding source code.

Can you help me to find the code?

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/magnetometer/#api

**Comment by Simek** [comment]
Hello @dmenneck, Magnetometer is a part of the sensors package:
* https://github.com/expo/expo/tree/main/packages/expo-sensors

The default Magnetometer is calibrated (so no calibration is needed for the general use-case), we also have the uncalibrated version, which outputs raw data. The implementation depends on the native platform code:
* https://github.com/expo/expo/tree/main/packages/expo-sensors/android/src/main/java/expo/modules/sensors/modules
* https://github.com/expo/expo/tree/main/packages/expo-sensors/ios/EXSensors/Modules/SensorModules

The doc page you have linked have a paragraph about this at the start:
> You can access the calibrated values with `Magnetometer` and uncalibrated raw values with `MagnetometerUncalibrated`.

**Comment by dmenneck** [comment]
Hi @Simek, thanks for your quick answer!

Unfortunately I'm not yet familiar with native ios and android code. 
Can you show me where to find the function that receives raw magnetometer data and returns the calibrated data? 

I was wondering if the calibration follows a specific procedure or a scientific paper. I need this information for my thesis.

**Comment by Simek** [comment]
Out implementation follows the platform specific guides, we do not calibrate data manually, that it's done by native systems:
* https://source.android.com/devices/sensors/sensor-types#magnetic_field_sensor
  > The readings are calibrated using:
  > Temperature compensation
  > Factory (or online) soft-iron calibration
  > Online hard-iron calibration
* https://developer.apple.com/documentation/coremotion/cmdevicemotion/1616140-magneticfield
  > [...] these values reflect the earth’s magnetic field plus surrounding fields, minus device bias

**Comment by dmenneck** [comment]
Thank you so much!

**Comment by barthap** [comment]
Recently I was working on a college project in which there was manual magnetometer calibration basing on `expo-sensors` data, maybe it will be useful in any way 🙄: https://github.com/barthap/fifs
There is a Matlab script in `magnetometer_calibration` that parses the CSV sensor data from the app, then performs the calibration and displays some plots. Let me know if you have any questions 😉

**Comment by stefanmijicswe** [comment]
@barthap can you explain me what does reading actually are from expo magnetometer? How do you use that data to calcualte degrees of turn?
