### ISSUE TITLE
[iOS] Reports of Cmd+D developer menu failing to appear in SDK 27 ExpoKit

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1768]
Reports here: https://forums.expo.io/t/unable-to-ios-dev-menu-after-upgrading-to-sdk27-on-expokit/9883/3

**Comment by nfrush** [comment]
I'm on ios/2.5.9 and having this issue. Is there a quick work around atm?

**Comment by terribleben** [comment]
I've identified the issue and will have a fix available later today.

**Comment by terribleben** [comment]
Hi, I've pushed a fix for this. You can update your ExpoKit pod dependency to `ios/2.5.10` to get the fix. Be sure and re-run `pod install` once you make that change. Let me know if that works for you.
