### ISSUE TITLE
react-native-slider [docs] 

### ISSUE THREAD

**Issue by SimonAM** [expo/expo#17683]
### Summary

The [docs](https://docs.expo.dev/versions/latest/sdk/slider/) describes using [react-native-community/react-native-slider](https://github.com/react-native-community/react-native-slider). However, expo installs `  "react-native-slider": "^0.11.0",`  when i run: `expo install react-native-slider`.

Can i manually install and use the react-native-community version?

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/slider/

**Comment by Simek** [comment]
The docs has been updated in https://github.com/expo/expo/pull/17805.

You should use the renamed community package, sorry for the confusion! 🙂
