### ISSUE TITLE
The react-native-opencv3 used in SDK 45 was built with an expo-gl-cpp error

### ISSUE THREAD

**Issue by mingmingshen** [expo/expo#17680]
### Summary

install react-native-opencv3 , build gradle error, error only on Android, iOS fine

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JSI_LIB
linked by target "expo-gl" in directory /Users/shenmingming/Desktop/App/FaceKey/node_modules/expo-gl-cpp/cpp

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 8.5.5 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.19 => 0.16.19 
      expo: ^45.0.4 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-native: ^0.68.2 => 0.68.2 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 5.4.6
    Expo Workflow: bare

### Reproducible demo

yarn add  react-native-opencv3
yarn run android

**Comment by ajnozari** [comment]
Having the same issue, something has gone wrong when using android studio

**Comment by kuldip-simform** [comment]
I am having the same issue. If anyone has solved this, please guide me.
