### ISSUE TITLE
SDK 45 - `expo-random@12.2.0` - null getRandomBytes

### ISSUE THREAD

**Issue by thedoublejay** [expo/expo#17682]
### Summary

I'm having issues with my project with expo-random. It's throwing null on getRandomBytes. (Expo SDK 45, expo-cli@5.4.7). This specific issue is only for iOS production builds.

It works on production using expo-random@12.1.2 but not locally. Locally expo-random@12.2.0 works but not with production builds.

Tried to update, uninstall, clear packages and all. Still not working.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.3.17 => 0.3.17 
      @expo/webpack-config: ~0.16.21 => 0.16.24 
      expo: ^45.0.4 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.4.7
    Expo Workflow: managed

### Reproducible demo

This is my build on EAS - https://expo.dev/accounts/defichain/projects/wallet/builds/6c2a0582-7604-4e81-b62c-4d87e876f7e8

![Image from iOS](https://user-images.githubusercontent.com/25013382/170926146-28edae85-9ffd-4eec-be03-7766649fef57.png)

**Comment by fullstackninja864** [comment]
I have the same problem. The Expo SDK version is 45.

**Comment by brentvatne** [comment]
hi there! happy to help but we need a clonable and runnable repository

**Comment by thedoublejay** [comment]
Hi @brentvatne, this is our repo - https://github.com/DeFiCh/wallet/tree/thedoublejay/bump_package. This branch uses `expo-random@12.2.0`. The app is build thru EAS. This issue is only for iOS. It works locally. Only on final app builds via EAS.

1. Once build is done, open the app
2. Click on Create a Wallet
3. Toggle "I understand it is my responsibility..."
4. Click on Show my 24 words
5. Error (React boundary)

The error is due to the issue raised `getRandomBytes is null`. Hope it helps!

**Comment by stdavis** [comment]
@thedoublejay I'm experiencing the same issue. Did you ever get your issue resolved?

**Comment by thedoublejay** [comment]
@stdavis Working fine now on our end. We upgraded it to Expo SDK 46 and now there are no issues.

**Comment by stdavis** [comment]
I got it sorted. I had to run `npx expo install expo-random`. For some reason I lost that dependency during my sdk version bump.
