### ISSUE TITLE
No project ID specified In app.json, unable to sign manifest

### ISSUE THREAD

**Issue by yonitou** [expo/expo#17693]
### Summary

Summary

Hi,

Just upgraded from SDK 44 to SDK 45.

Everytime I'm launching my app or reloading the JS bundle, I'm having this warning : No project ID specified in app.json, unable to sign manifest

<img width="955" alt="Capture d’écran 2022-05-30 à 21 25 06" src="https://user-images.githubusercontent.com/61981305/171050412-d1e7e70e-b04f-406f-8417-3072fe2d4b20.png">

Never had this warning before and I don't know if this is important or not. I'm also using EAS Updates.

PS : I'm using app.config.ts instead of app.json

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45

### Environment

```expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /Users/yonitouboul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.7
    Expo Workflow: managed```

### Reproducible demo

Upgrade to expo SDK 45 and run expo start

**Comment by mister-conor** [comment]
I encountered this issue also. We upgraded to Expo 45 so I ran the command `eas update:configure` to configure updates as we had been previously using `expo publish` for OTA updates. Expo 45 does not support updates for free tier right now, but it will be available later in 2022 according to the [Expo 45 release notes](https://blog.expo.dev/expo-sdk-45-f4e332954a68).

From the link:

**_Later this year, we’ll release EAS Update to all accounts, allow secure end-to-end code signing, and much more. Stay tuned!_**

I fixed the issue by removing the changes that the command `eas update:configure`  had made to the app.json file. I removed the "updates" and "runtimeVersion" sections in the app.json. I also uninstalled the `expo-updates` package as it is of no use until it is made available to the free tier.

I hope this helps someone else. It is frustrating that Expo had previously made `expo publish` commands available to all users but now the updates are only available to paid accounts until later this year. We used the OTA updates quite alot to deploy different versions to testers and also for patches to production versions of our app.

**Comment by ide** [comment]
To fix the original issue, you need to specify your EAS project ID under `exp`→`extra`→`eas`→`projectId`. You can get your project ID from https://expo.dev/accounts/[account]/projects/[project]

<img width="780" alt="s" src="https://user-images.githubusercontent.com/379606/176079438-fee053b7-2e66-444a-81f9-de0df25af575.png">

The EAS project ID is necessary when using Expo Go, which is a prebuilt development client managed by the Expo team. If you create a [development build](https://docs.expo.dev/development/build/) of your own app, you don't need this ID.

**Comment by LuuCongQuangVu** [comment]
I was run eas init , but expo go log error : mainfest download was successfull but signature was incorrect. I change project from expo build to eas build

**Comment by ivnnv** [comment]
For those coming from looking at the `getExpoPushTokenAsync` warning thrown at Expo Go on classic build apps.

How to fix it:

1) Copy your from your `project` id at your project page at expo.dev as screenshoted above by IDE.
2) Make the `projectId` available as environment variable, for example using [Expo.Constants +  direnv method](https://docs.expo.dev/guides/environment-variables/#reading-the-variables-from-application-code)
3) Pass the projectId to getExpoPushTokenAsync()

```
const expoToken = await Notifications.getExpoPushTokenAsync({
  projectId: Constants.expoConfig.extra.easProjectId,
});
```

**Comment by yxrael** [comment]
projectId doesn't exist until you compile your first build. If you don't need a build yet just

`eas build:configure`

and you'll get the projectId on the route

`Constants.expoConfig.extra.easProjectId`
