### ISSUE TITLE
GetContactByIdAsync throws error when loading contact with lots of data

### ISSUE THREAD

**Issue by vincentwongso** [expo/expo#1769]
### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.3.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  expo: ^27.0.2-rc.0 => 27.0.2-rc.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/vincentwongso-18c4beee-cf7d-4f1d-958a-34fda1d74369.tar.gz

Target: Android 7.1 (device and emulator)

### Steps to Reproduce
getContactByIdAsync throws error while trying to load contact that has lots of content (multiple phone numbers, addresses, and emails).

### Expected Behavior

It should load the contact normally.

### Actual Behavior

Throws an error:

```
Error: Couldn't read row 6, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at createErrorFromErrorData (07b8578c-dc92-4bbf-9…7-95bc6f969fc1:2342)
    at 07b8578c-dc92-4bbf-9…7-95bc6f969fc1:2294
    at MessageQueue.__invokeCallback (07b8578c-dc92-4bbf-9…7-95bc6f969fc1:2736)
    at 07b8578c-dc92-4bbf-9…7-95bc6f969fc1:2481
    at MessageQueue.__guardSafe (07b8578c-dc92-4bbf-9…7-95bc6f969fc1:2649)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (07b8578c-dc92-4bbf-9…7-95bc6f969fc1:2480)
    at debuggerWorker.js:70
```
Possibly related to this issue:
https://github.com/facebook/react-native/issues/12529

### Reproducible Demo

You can use the following snack to reproduce the issue, you just need to update the contactId value with the contact that has lots of content:
https://snack.expo.io/rJlD26oAM

You might want to export to local XDE to get the error, if you're using snack it will usually crash the expo app.

**Comment by esamelson** [comment]
Hi @vincentwongso - thanks for the report. We'll look into this.
