### ISSUE TITLE
Expo-image-picker@12.0.1 can't upload videos < 15 sec on iOs simulator/devices

### ISSUE THREAD

**Issue by cyberquizm** [expo/expo#17694]
### Summary

After selecting the video file with length < 15 sec on SImulator (iPhone 8/11) I'm getting the system error (xcode): "This media cannot be used".

...
[javascript] 'MEDIA RESULT', { height: 480,
  duration: 10467,
  uri: 'file:///Users/user/Library/Developer/CoreSimulator/Devices/941FDE31-321B-4636-B8ED-D3E770F0CBB8/data/Containers/Data/Application/2C4E6F2A-987D-48A4-BB04-119E269262AB/Library/Caches/ImagePicker/5FBC9120-D929-4DC7-BB38-BC8E885BB5E6.mov',
  type: 'video',
  cancelled: false,
  width: 848 }
[javascript] Possible Unhandled Promise Rejection (id: 1):
**Error: This media cannot be used**.
promiseMethodWrapper@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.myapp.app:2560:45
...

On real devices selecting video fails too.

But video files >= 15 sec are successfully picked up and uploaded.

Can't find any description for the given error by the system and I'm very surprised with such bug. Any thoughts?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.9.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.4 => 0.66.4 
    Expo Workflow: bare

### Reproducible demo

let result = await MediaPicker.launchImageLibraryAsync({
                mediaTypes: MediaPicker.MediaTypeOptions.All
            });

**Comment by Supsource** [comment]
The same, is happening with me, have you got any solution yet?
