### ISSUE TITLE
Expo publish stuck on Bundling iOS

### ISSUE THREAD

**Issue by fweffort** [expo/expo#17690]
### Summary

When trying to run expo publish it gets stuck @ around 97% on **iOS Bundling JavaScript**

It doesn't fail, just gets stuck!

### What platform(s) does this occur on?

Android, iOS

### SDK Version

44

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.1, 30.0.2, 31.0.0, 33.0.0
        System Images: android-29 | Android TV Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.7
    Expo Workflow: bare

### Reproducible demo

Well, not exactly a code, but how could I get a code?

```
 expo publish

› Expo SDK: 44.0.0
› Release channel: default
› Workflow: Bare

Building optimized bundles and generating sourcemaps...
Warning: Invalid version react-native@0.68.2 for expo sdkVersion 44.0.0. Use react-native@0.64.3
Starting Metro Bundler
Started Metro Bundler
iOS Bundling JavaScript [==============================================================  ] 97%
```

**Comment by jferrettiboke** [comment]
What do you get if you run `expo doctor`?
