### ISSUE TITLE
Mismatch between expo-cli & new versioned local expo CLI

### ISSUE THREAD

**Issue by yonitou** [expo/expo#17696]
### Summary

Hello there, 

Just upgraded from expo 44 to 45 and read your blog post regarding the new versioned expo CLI (https://blog.expo.dev/new-versioned-expo-cli-cf6e10632656)

The issue I'm having is that it seems, randomly, expo will switch by itself between these two tools version. 

For example, right now, if I'm using `expo -V` I'm getting : `Unknown or unexpected option: -V` and if I use `expo -v` I'm getting `0.1.4` which doesn't seem to be my expo-cli version. 

When I run expo start, it's using the new beta expo cli. What can I do to ensure that I'm using the v. 5.4.7 that I installed globally ? It's pretty frustrating and led me to many errors last night. 

Thanks a lot,

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45

### Environment

``` expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /Users/yonitouboul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.7
    Expo Workflow: managed```

### Reproducible demo

Hard to say since I "only" upgraded to SDK 45 to run into this.

**Comment by brentvatne** [comment]
it's not clear to me how you could have been accidentally running the local CLI, because it will only run the local copy if you have the appropriate env var set: `EXPO_USE_BETA_CLI=1`

if you can help me to reproduce this locally without setting that env var i'd be very curious to help!
