### ISSUE TITLE
Investigate orphaned XDE processes

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#177]
Moved from https://github.com/expo/xde/issues/101

**Comment by lucfranken** [comment]
<img width="535" alt="schermafbeelding 2017-05-10 om 08 47 48" src="https://cloud.githubusercontent.com/assets/1609379/25886328/6926ebfe-355d-11e7-91fb-dd6771e4a76a.png">

This is the situation on a rebooted system (for reproducing https://github.com/expo/expo/issues/124). Started Expo XDE once and clicked Open in iOS simulator twice.

Any indication on how many processes there should be?

**Comment by sjchmiela** [comment]
Closing this issue as XDE has been recently replaced with Expo CLI. Read more at https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c. 🙂
