### ISSUE TITLE
After calling Updates.reloadAsync() Android app crashes with error

### ISSUE THREAD

**Issue by arnau-rius** [expo/expo#17702]
### Summary

After calling Updates.reloadAsync(), Android app crashes with error
```
IllegalStateException
java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.swmansion.reanimated.layoutReanimation.NativeMethodsHolder.isLayoutAnimationEnabled()' on a null object reference
```
It is called inside this function:
```ts
export async function reloadApp() {
  const { deviceType } = getConstants();
  if (deviceType === DeviceType.WEB) {
    window.location.reload();
  } else {
    try {
      await Updates.reloadAsync();
    } catch (error) {
      logError({ message: 'Could not reload the app', error });
    }
  }
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Patch 1 Chipmunk 2021.2.1 Patch 1
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.51.0
    Expo Workflow: managed

### Reproducible demo

----------

**Comment by OneHatRepo** [comment]
I'm seeing this too.

**Comment by d4rky-pl** [comment]
If you run into this issue and lose your hair while googling it - make sure you're not updating the UI or any other state after running `reloadAsync`. In our case the problem was caused by mobx-state-tree code that looked like this:

```javascript
installNow: flow(function* () {
  self.updating = true
  Updates.reloadAsync()
}),
```

The `flow` wraps all state changes in a transaction that MST then commits after the function is done, this caused a re-render of a component during the code refreshing which in turn caused the `java.lang.NullPointerException` like the one from the original report.
