### ISSUE TITLE
Custom fonts not loading expo + react-native init

### ISSUE THREAD

**Issue by sourcebit-apps** [expo/expo#1770]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please use `exp send` with exp, the “Send” button with XDE, or the "s" hotkey with create-react-native-app to send your project development URL to your phone by SMS or email.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: Not Found
  npm: 6.0.1
  Watchman: 4.7.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/sbapps-e824e82a-4922-4552-880b-09a9e35a6d52.tar.gz

### Steps to Reproduce

(Write your steps here:)

I have a react native project which I initialised with react-native init 'Sample Project' and installed expo with npm i exp. For the custom fonts I installed them with react-native link. Now when I refer to the font in my js file like below:
```
input: {
        fontFamily: "RobotoCondensed-Light",
        fontWeight: "300", //light
        fontStyle: 'normal',
        fontSize: 16,
        width: DEVICE_WIDTH - 60,
        textAlign: 'left',
        paddingLeft: 2,
        textAlignVertical: 'center',
        marginTop: 30,
        height: 40,
    },
```
The problem is I'm not able to see the font on my Android device. If I do any change in fontFamily string like fontFamily: "junk value", still it works and doesn't give any error. Not sure, what is happening?

Im running the code by below commands:-

exp start
npm start
Do I need to run react-native run android command to see the changes? If yes, then how can I use expo to the app on my device wirelessly?

Thanks for the help. Appreciate your response.

### Expected Behavior

Custom fonts should load in the app

(Write what you thought would happen.)

### Actual Behavior

Custom fonts not loading in the app
(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by esamelson** [comment]
Hi @sourcebit-apps. You'll need to start a new project using either [XDE](https://docs.expo.io/versions/v27.0.0/guides/up-and-running.html) or `exp init` (after running `npm i -g exp` to install `exp` as a global command line tool), instead of using `react-native init`.

This is because `react-native init` just creates a vanilla React native project without any of Expo's extra native modules, such as the font loading module. These extra native modules cannot be installed via npm, so the only way to get them is to start with an Expo project from the beginning. That is what you get with XDE or `exp init`.

Hope that makes sense. Let us know if we can help in any other way!

**Comment by sourcebit-apps** [comment]
Ok..But when I used  create react native command to create the project I
was able to see the fonts.Does that not make vanilla react project?

**Comment by esamelson** [comment]
Hi @sourcebit-apps - no, create-react-native-app creates a project with all of the Expo stuff set up already. You can eject to vanilla react native from there, but that means losing all of the Expo modules.

**Comment by sourcebit-apps** [comment]
I need to have iOS and andorid folders in my project as I will be doing
native app dev also. And I also need expo to be used with custom
fonts.Please suggest is there a way to do this.

**Comment by esamelson** [comment]
@sourcebit-apps you can [detach to ExpoKit](https://docs.expo.io/versions/v27.0.0/expokit/detach) which will allow you to add your own native modules & native code while also keeping all of Expo's native modules, including font loading.

**Comment by sourcebit-apps** [comment]
Hi Eric,

Thanks for the help.I was able to load the fonts.
