### ISSUE TITLE
On TestFlight, an app stucks on the splash screen.

### ISSUE THREAD

**Issue by Mistik** [expo/expo#17721]
### Summary

An app works fine via the expo app (both on simulator and on real device) but when I try to run the standalone app (.ipa) that I downloaded to TestFlight, it stuck on the splash screen.
 

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Package versions

{
  "name": "senpatt",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~44.0.0-beta.0",
    "expo-linking": "~3.0.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "~0.11.7",
    "expo-web-browser": "~10.1.0",
    "onesignal-expo-plugin": "^1.0.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-onesignal": "^4.3.10",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.15.0",
    "sharp-cli": "^1.15.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

### Environment

N/A

### Reproducible demo

TestFlight (any device)

**Comment by Mistik** [comment]
When I run the project in the simulator its fine, issue is just on testflight, but I need testflight, because I want to test out the push notifications

**Comment by dungkaka** [comment]
Same for me but on both iOS and Android, test on expo app is all good, but when I build apk or abb, app stuck on splash screen.

**Comment by conoremclaughlin** [comment]
Same. App runs fine in development but crashes immediately on TestFlight.

**Comment by conoremclaughlin** [comment]
Not sure if this helps the folks in this thread, but we fixed this by switching to `eas build` vs `expo build`. We missed in the documentation expo build is deprecated for the run builds.

**Comment by brentvatne** [comment]
https://github.com/expo/fyi/blob/main/splash-screen-hanging.md
