### ISSUE TITLE
Cannot use `PRODUCT_BUNDLE_IDENTIFIER` in `CFBundleURLSchemes`

### ISSUE THREAD

**Issue by MrXyfir** [expo/expo#17727]
### Summary

I have an ejected Expo app. I set up a build scheme in xcode so I can build a separate app for staging and have them both installed on a device at the same time. To do this, they need separate Bundle IDs, so I use the `PRODUCT_BUNDLE_IDENTIFIER` variable in various places.

I get an error when I try to run `npm run ios` / `expo run:ios`:

```
› Installing on iPhone 13
› Opening on iPhone 13 (com.myapp.id)
› Opening $(PRODUCT_BUNDLE_IDENTIFIER)://expo-development-client/?url=http%3A%2F%2F192.168.1.18%3A8081 on iPhone 13
› Opening the iOS simulator, this might take a moment.
CommandError: Couldn't open iOS app with ID "$(PRODUCT_BUNDLE_IDENTIFIER)://expo-development-client/?url=http%3A%2F%2F192.168.1.18%3A8081" on device "iPhone 13".
The app might not be installed, try installing it with: expo run:ios -d AA4A861A-A966-4B9F-AC10-F8CBC2276C15
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
The request to open "$(PRODUCT_BUNDLE_IDENTIFIER)://expo-development-client/?url=http%3A%2F%2F192.168.1.18%3A8081" failed.
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
        The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for "$(PRODUCT_BUNDLE_IDENTIFIER)://expo-development-client/?url=http%3A%2F%2F192.168.1.18%3A8081"
        Application info provider (FBSApplicationLibrary) returned nil for "$(PRODUCT_BUNDLE_IDENTIFIER)://expo-development-client/?url=http%3A%2F%2F192.168.1.18%3A8081"
```

Through trial and error I found the issue was here in my `Info.plist`:

```xml
        <key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>$(HOST_APP_URL_SCHEME)</string>
				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
		</dict>
	</array>
```

Replacing `$(PRODUCT_BUNDLE_IDENTIFIER)` with `com.myapp.id` allows it to build.

### What platform(s) does this occur on?

iOS

### SDK Version

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.2.0 - /usr/local/bin/node
      npm: 8.9.0 - /usr/local/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.7
    Expo Workflow: bare
```

### Reproducible demo

Add the following to your `Info.plist`:

```xml
        <key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>myapp</string>
				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
		</dict>
	</array>
```

Run `npm run ios` or `expo run:ios`

---

Edit: Upon further testing and research it looks like Expo just doesn't handle this use case well at all. It gives different errors at just about every turn unfortunately.

**Comment by MrXyfir** [comment]
For anyone else trying to achieve the same goal of having multiple apps with separate bundle identifiers here's the brief outline of what I did:

1 - Duplicate my Targets (in my instance, for a staging app)

<img width="166" alt="image" src="https://user-images.githubusercontent.com/12347375/171753166-b8bc6503-a9ac-478e-9e37-136a592c4224.png">

2 - Duplicate the necessary `.plist` files for each target and update the variables you wish to change within them

<img width="257" alt="image" src="https://user-images.githubusercontent.com/12347375/171753251-3a9062c3-d8d2-4347-8d4b-a5a81fd357a1.png">

3 - Update the bundle identifier, `.plist` file references, and any other config changes needed for each new target

<img width="440" alt="image" src="https://user-images.githubusercontent.com/12347375/171753322-d3fec091-9e7f-4cfd-80c8-0ac4f13b9557.png">

4 - Build!

<img width="517" alt="image" src="https://user-images.githubusercontent.com/12347375/171753529-cec507d6-8956-407f-9d17-c7fef0661ef5.png">

---

It's not as clean a fix compared to if Expo would support referencing a few variables vs requiring hardcoded values, but it's a quick solution.

**Comment by harlandjp** [comment]
Is there a chance this will be fixed? 🙏 
Auth0 requires us to use `PRODUCT_BUNDLE_IDENTIFIER` in `CFBundleURLSchemes` and the provided workaround is not ideal.
