### ISSUE TITLE
Android adaptive icon size that expo generates is too small.

### ISSUE THREAD

**Issue by dubchoi** [expo/expo#17728]
### Summary

According to https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

> In Android 7.1 (API level 25) and earlier, launcher icons were sized at 48 x 48 dp. You must now size your icon layers using the following guidelines:
> Both layers must be sized at 108 x 108 dp.

However, expo is still generating adaptive icon foreground images at 48dp. This is mostly not noticeable for the app icon itself, but on the new splash screens for Android 12+, the adaptive icon shows up on launch and is heavily pixelated as a result.

The generated @mipmap/ic_launcher_foreground files should be at 108 x 108dp.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Just set up a normal managed expo project and build for android as below.

### Reproducible demo

1. Make sure you have a 1024x1024 image to use as the foreground of the icon: `./assets/images/adaptive-icon.png`
2. Have something like following in `app.json`

```
{
  "expo": {
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#000"
      },
      ..
    },
    ..
  }
```

3. Run `expo run:android`

4. Confirm the size of the generated `android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png`
This is expected to be 108x108dp, which at xxxhdpi, the image should be 432x432px.
However, the actual image is 192x192px (48x48dp).

5. Also confirm all the images are too small at all the various mipmap-{density} folders.

**Comment by hirbod** [comment]
I can confirm this as well! I am in the middle of preparing my Android launch and wasn’t sure why it looked so pixelated.

**Comment by Qonditive** [comment]
any news ?

**Comment by Ryley-Dennis** [comment]
Same thing happening here. Tried with and without adaptive icon

**Comment by brentvatne** [comment]
@Ryley-Dennis - can you share a minimal reproducible example?

**Comment by Norfeldt** [comment]
I too have problems with the android icon size. When launching the app it zooms in the adaptive icon and it becomes clear that it's low res.


![Oct-20-2022 11-35-26](https://user-images.githubusercontent.com/678806/196913010-fcba8841-f471-4371-9587-b1f889d66d59.gif)

I event tried to have the @2x and @3x in the hope that expo would know what to do. But guessing that they are not needed.

<img width="302" alt="Screenshot 2022-10-20 at 11 37 24" src="https://user-images.githubusercontent.com/678806/196913484-a53af488-77da-4b3c-b589-ee70fb29937c.png">

**Comment by Julioevm** [comment]
Same here with adaptive-icon.

**Comment by baronha** [comment]
Same here with adaptive-icon.

**Comment by Norfeldt** [comment]
@brentvatne haven't looked at this since, but recall SDK 52 mentioned something about fixing the android splash screen, isn't that right?

**Comment by brentvatne** [comment]
> @brentvatne haven't looked at this since, but recall SDK 52 mentioned something about fixing the android splash screen, isn't that right?

https://expo.dev/changelog/2024/11-12-sdk-52#big-improvements-to-expo-splash-screen
