### ISSUE TITLE
expo-auth-session not redirecting back to app when using facebook OAuth

### ISSUE THREAD

**Issue by PeterAbdalla** [expo/expo#17723]
### Summary

I am trying to build Oauth flow using an expo-auth-session. The app supports login through both facebook and google, when using google Oauth the Authentication flow redirects back to application. But while using facebook authentication, the authentication is successful, but the browser is not redirecting back to app, it just keeps crashing the app in production, while in development using Expo Go, it redirects back to the app normally.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

production

### Reproducible demo

function MainLogin() {
  const dispatch = useDispatch();
  const [request, response, promptAsync] = Facebook.useAuthRequest({
      scopes: ['public_profile', 'email'],
      clientId: FACEBOOK_AUTH_CLIENT_ID,
      androidClientId: FACEBOOK_AUTH_CLIENT_ID,
      iosClientId: FACEBOOK_AUTH_CLIENT_ID,
      clientSecret: FACEBOOK_AUTH_CLIENT_SECRET,
      prompt: Prompt.Login,
      responseType: ResponseType.Token,
    });
    const [requestG, responseG, promptAsyncG] = Google.useAuthRequest({
      expoClientId: GOOGLE_AUTH_CLIENT_ID,
      androidClientId: GOOGLE_AUTH_ANDROID_CLIENT_ID,
      iosClientId: GOOGLE_AUTH_IOS_CLIENT_ID,
    });
    useEffect(() => {
      if (response?.type === 'success')
        dispatch(login({ token: response.params.access_token, platform: 'facebook' }));
    }, [response]);
    useEffect(() => {
      if (responseG?.type === 'success')
        dispatch(login({ token: responseG.params?.access_token, platform: 'google' }));
    }, [responseG]);
}

**Comment by code4muktesh** [comment]
Facing same issue with Facebook. Working with expo go but redirecting to app on real android device. Getting blank screen with url https://m.facebook.com/v12.0/dialog/oauth/confirm

**Comment by sumitmaithani123** [comment]
@code4muktesh  have you find any solution I'm facing same problem?

**Comment by ombogdanJoinToIt** [comment]
same

**Comment by sumitmaithani123** [comment]
@ombogdanJoinToIt bro use react-native-fbsdk-next package it will solve all problems but it not work on expo it will work on react-native cli just move to cli and see documentation of that package
