### ISSUE TITLE
Splash Screen disappears (white screen) before the app finishes loading (iOS only)

### ISSUE THREAD

**Issue by gabriel-moresco** [expo/expo#17746]
### Summary

Hello, my app's splash screen is disappearing, and a white screen appears until the app fully loads.

This only occurs on iOS and with Expo in Production Mode, or when the app is published on the App Store.
On android or in Development Mode it does not occur.

In the example I use the command `await new Promise((resolve) => setTimeout(resolve, 5000))` to simulate the app loading delay.

https://user-images.githubusercontent.com/45923448/171930513-e40ba1c2-fb31-47f6-a878-4f02f7a9cab4.mp4

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    npmPackages:
      expo: ~45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed
```

### Reproducible demo

```ts
import React, { useState, useEffect, useCallback } from 'react'
import { Text, View } from 'react-native'
import * as SplashScreen from 'expo-splash-screen'

export default function App() {
  const [appIsReady, setAppIsReady] = useState(false)

  useEffect(() => {
    async function prepare() {
      try {
        await SplashScreen.preventAutoHideAsync()
        await new Promise((resolve) => setTimeout(resolve, 5000))
      } catch {
      } finally {
        setAppIsReady(true)
      }
    }

    prepare()
  }, [])

  const onLayoutRootView = useCallback(async () => {
    if (appIsReady) {
      await SplashScreen.hideAsync()
    }
  }, [appIsReady])

  if (!appIsReady) {
    return null
  }

  return (
    <View
      style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: 'red' }}
      onLayout={onLayoutRootView}
    >
      <Text>test</Text>
    </View>
  )
}
```

**Comment by brentvatne** [comment]
repro'd here https://github.com/brentvatne/splashyrepro

**Comment by barthap** [comment]
I think I've found a workaround for this case. Try calling `SplashScreen.preventAutoHideAsync()` outside app component, in global scope:
```js
import * as SplashScreen from "expo-splash-screen";

SplashScreen.preventAutoHideAsync();

export default function App() {
  // ...
}
```
From what I discovered, when `preventAutoHideAsync` is called in `useEffect`, it is already too late to prevent it from auto-hide, because the app is already loaded.

**Comment by gabriel-moresco** [comment]
> I think I've found a workaround for this case. Try calling `SplashScreen.preventAutoHideAsync()` outside app component, in global scope:
> 
> ```js
> import * as SplashScreen from "expo-splash-screen";
> 
> SplashScreen.preventAutoHideAsync();
> 
> export default function App() {
>   // ...
> }
> ```
> 
> From what I discovered, when `preventAutoHideAsync` is called in `useEffect`, it is already too late to prevent it from auto-hide, because the app is already loaded.

This workaround worked for me. Thank you so much.
