### ISSUE TITLE
[expo-facebook] [SDK44] Error can't press button to continue with small device under 5.8 inch like IphoneX

### ISSUE THREAD

**Issue by VanLong-official** [expo/expo#17748]
### Summary

Some of my clients use devices less than 5.8 inches in size most of the time can't press the continue button to be able to login to Facebook. This error appears on both Android and Ios devices. Especially the iPhone X.
![Screen Shot 2022-05-27 at 08](https://user-images.githubusercontent.com/76549723/171975192-31ed6f8c-bcbb-40c5-9b96-d53244125ea0.png)
![IMG_0094](https://user-images.githubusercontent.com/76549723/171975410-6c7d86ec-944c-4587-ad91-3a46fd4ad42f.PNG)
![Screen Shot 2022-06-04 at 09 41 46](htt
![Screen Shot 2022-06-04 at 09 38 28](https://user-images.githubusercontent.com/76549723/171975475-8469062d-3098-473a-a04b-5151d7cd06cb.png)
ps://user-images.githubusercontent.com/76549723/171975464-761e9bc0-74c9-41e5-a939-0f9be1f6247d.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

react native start

### Reproducible demo

await Facebook.initializeAsync({
        appId: 'app_id',
        appName: 'name_app',
        autoLogAppEvents: false,
      });
      const { type, token, expires } =
        await Facebook.logInWithReadPermissionsAsync({
          permissions: FB_LIST_PERMISSIONS,
        });

const FB_LIST_PERMISSIONS = [
  'public_profile',
  'email',
  'pages_manage_metadata',
  'pages_read_engagement',
  'pages_show_list',
  'pages_read_user_content',
  'pages_manage_posts',
  'pages_manage_engagement',
  'read_page_mailboxes',
  'pages_messaging',
  'pages_messaging_subscriptions',
  'ads_read',
  'page_events',
  'instagram_basic',
  'instagram_manage_messages',
  'instagram_manage_comments',
  'pages_show_list',
];

**Comment by brentvatne** [comment]
this doesn't look related to expo, it seems like there is some issue with fb sdk. try switching to https://github.com/thebergamo/react-native-fbsdk-next/#expo-installation
