### ISSUE TITLE
ExpoUpdateDelegateHandler nil ios sdk 45.0.0

### ISSUE THREAD

**Issue by caferyukseloglu** [expo/expo#17749]
### Summary

Hi, I am updating old react native project to new version. I created clean build up, with all packages installed fresh. However in release mod, Expo Update stops to project at splash screen. rootViewModul unexpectedly found nil. Why this is happening and how to fix this. Thank you. Expo-updates 0.13.1

let rootView = RCTRootView(bridge: bridge!, moduleName: self.rootViewModuleName!, initialProperties: self.rootViewInitialProperties)

self.rootViewModuleName! = nil the error thread 1: Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45.0.0

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.0.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.6.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-navigation: ^3.11.0 => 3.13.0 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo

{
  "name": "*m****",
  "displayName": "m*****",
  "expo": {
    "name": "m*****",
    "slug": "m*****",
    "owner": "cafer",
    "version": "1.0.1",
    "sdkVersion": "45.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#FFA500"
    },
    "updates": {
      "enabled": true,
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "bundleIdentifier": "com.s******.m******",
      "buildNumber": "1.9.1"
    },
    "android": {
      "package": "com.s******.m******",
      "versionCode": 86
    }
  }
}

Envo:
const getEnvVars = (env = Updates.manifest.releaseChannel) => {
  if (__DEV__) {
    return ENV.dev;
  } else {
    return ENV.default;
  }
};

**Comment by mackenziekira** [comment]
This is happening for us too, both when building the app locally and when trying to open our app in the custom dev client built via EAS. We are also in the bare workflow, upgrading to Expo 45

**Comment by levani** [comment]
I had the same problem after making all changes from [RN Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.68.1). Fixed it by creating blank expo project and replacing `AppDelegate.mm` from there.

**Comment by brentvatne** [comment]
thanks for sharing that @mackenziekira. 

in case anyone else misses it, this is covered in the sdk 45 blog post:

> Update your AppDelegate.mm (you should have moved from .m to .mm in the previous step) update your Expo module configuration as done in [this diff](https://github.com/expo/expo/commit/b5764e22ad204fc44bed55cfeb38c78bb2bbdbcf).

https://blog.expo.dev/expo-sdk-45-f4e332954a68

**Comment by caferyukseloglu** [comment]
React Native 0.69.5 with expo-update same error fixed by following:
`//UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"main", initProps);
  UIView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"main" initialProperties:initProps];`
