### ISSUE TITLE
Text inside of <View> crashes the app without notification

### ISSUE THREAD

**Issue by denis-n** [expo/expo#1775]
Hi,

I'm learning React Native and have been using latest Expo with Android emulator on Windows.
OS: Windows 8.1
Android Emulator: Nexus 5X API P

Inside of App.js's render method I had a component, which was returning in render method this: 
**`<View>My text</View>`**

I know now that it's a mistake, but Expo kept crushing without telling what is wrong. I created a new instance of Android emulator and Expo kept crushing again. 

It stopped crushing after adding `<Text>` tag: 
**`<View><Text>My text</Text></View>`** 

Thank you for your app. I hope it will be easy to fix.

**Comment by brownbl1** [comment]
If I try to run the following
```js
import React from 'react'
import { View } from 'react-native'

export default class App extends React.Component {
  render() {
    return <View>Hello World</View>
  }
}
```

I get the following error message:
![image](https://user-images.githubusercontent.com/2136925/40316629-edb008c6-5cec-11e8-8587-0a1fba445d30.png)

Is this not what you're seeing in the emulator window? If not, I think you have a different issue. I agree that it's not the most descriptive error message, but it's not a problem with expo.

**Comment by denis-n** [comment]
I tested it again - Expo silently stops to work again.
Here is the branch - https://github.com/denis-n/react-native-tech-stack/tree/expo-stops
Check the last commit - you will see what modifications make Expo stop working.

**Comment by denis-n** [comment]
I started the emulator from command line and noticed this text in console:

![image](https://user-images.githubusercontent.com/4423231/40318056-08aa9634-5d2c-11e8-849d-e42bae35e709.png)

![image](https://user-images.githubusercontent.com/4423231/40318077-1b334a08-5d2c-11e8-8ccc-b17bd6730d91.png)

**Comment by Roshdy** [comment]
You have to use <Text> component so your code should be like:

```
import React from 'react'
import { View, Text } from 'react-native'

export default class App extends React.Component {
  render() {
    return <View><Text>Hello World</Text></View>
  }
}

```

**Comment by brentvatne** [comment]
this is an upstream react-native issue
