### ISSUE TITLE
Native custom module is not exposed by expo go and archive but work in emulator

### ISSUE THREAD

**Issue by jannikov** [expo/expo#17764]
### Summary

On iOS, when using an Expo bare workflow and Expo module to include native code, linking does not seem to work.

For example, when running within a simulator, custom module is linked and methods can be accessed within the application.
When running on a physical device, custom module is not linked and error is thrown (as described below) where module isn't exported from "expo-modules-core".

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.9
    Expo Workflow: bare

### Reproducible demo

Creates two projects with expo-cli:

1. npx expo-create-module
2. expo init (bare template)
3. linked module to client

### Client application snack 
https://snack.expo.dev/@juri.annikov/github.com-jannikov-expo-linking-issue:my-bare-app

### Native expo module - can't create snack, module doesn't have App.js
https://github.com/jannikov/expo-linking-issue/tree/master/expo-juri

### Emulator screen (ExpoJuri module is there)
<img width="462" alt="image" src="https://user-images.githubusercontent.com/26857385/172216494-d05aacb9-5c66-405c-a982-8e191de34fc3.png">

### Expo go on IPhone 13 pro max gives next error

```
The native view manager required by name (ExpoJuri) from NativeViewManagerAdapter isn't exported by expo-modules-core. Views of this type may not render correctly. Exported view managers: [ExpoAppleAuthenticationButtonSignUpBlack, ExpoVideoView, ExpoBlurView, ExpoAdsAdMobBannerView, AdOptionsView, ExpoAppleAuthenticationButtonSignUpWhite, ExpoAppleAuthenticationButtonSignInWhite, ExpoLinearGradient, ExpoAppleAuthenticationButtonContinueWhiteOutline, ExpoBarCodeScannerView, ExpoAppleAuthenticationButtonSignInWhiteOutline, ExponentGLView, ExpoAppleAuthenticationButtonContinueBlack, ExpoAppleAuthenticationButtonSignUpWhiteOutline, MediaView, ExpoAppleAuthenticationButtonSignInBlack, ExpoAppleAuthenticationButtonContinueWhite, CTKBannerView, AdIconView, CTKNativeAd, ExponentCamera, ExpoAdsPublisherBannerView].
at node_modules/expo-modules-core/build/NativeViewManagerAdapter.native.js:11:8 in requireNativeViewManager
at node_modules/expo-juri/build/ExpoJuriView.js:3:19 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo-juri/build/ExpoJuri.js:2:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at App.js:5:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at index.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:200:44 in guardedLoadModule
at http://192.168.1.21:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:120873:3 in global code
```

**Comment by ristokitsing** [comment]
I'm having the same problem, anyone from Expo team can respond to this?

**Comment by brentvatne** [comment]
you can’t add custom native modules in expo go. you need to use a development build for that

**Comment by brentvatne** [comment]
https://docs.expo.dev/development/introduction/
