### ISSUE TITLE
Initializing FirebaseRecaptcha on Android crashes when attemptInvisibleVerification props is true

### ISSUE THREAD

**Issue by giacomoalonzi** [expo/expo#17774]
### Summary

Using FirebaseRecaptchaVerifierModal with `attemptInvisibleVerification` prop on Android can cause an app crash on mount/unmount the screen.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/giacomoalonzi/.rvm/gems/ruby-2.7.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 32
        Build Tools: 32.0.0, 32.1.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.5 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.9
    Expo Workflow: bare
```

### Reproducible demo

in a scree includes

```
<FirebaseRecaptchaVerifierModal
          ref={recaptchaVerifier}
          firebaseConfig={app.options}
          attemptInvisibleVerification
        />
```
on android randomly this could make a crash when the screen will be mounted, or sometimes when the screen will be unmounted (eg. navigate to another path)

a workaround that I found is the following:

`attemptInvisibleVerification={!!isIos()}`

Hope this can help to solve the issue!

Thanks

**Comment by Neiso** [comment]
Solved in on Android using this:
```javascript          
<FirebaseRecaptchaVerifierModal
          ref={recaptchaVerifier}
          firebaseConfig={app.options}
          attemptInvisibleVerification
          androidHardwareAccelerationDisabled
/>
```

**Comment by SarthakU** [comment]
> Solved in on Android using this:
> 
> ```js
> <FirebaseRecaptchaVerifierModal
>           ref={recaptchaVerifier}
>           firebaseConfig={app.options}
>           attemptInvisibleVerification
>           androidHardwareAccelerationDisabled
> />
> ```

Facing the same issue and this did not work for me.

**Comment by giacomoalonzi** [comment]
> > Solved in on Android using this:
> > ```js
> > <FirebaseRecaptchaVerifierModal
> >           ref={recaptchaVerifier}
> >           firebaseConfig={app.options}
> >           attemptInvisibleVerification
> >           androidHardwareAccelerationDisabled
> > />
> > ```
> 
> Facing the same issue and this did not work for me.

Same here, still crashing!  
The only workaround is this ` attemptInvisibleVerification={!!isIos()}`
