### ISSUE TITLE
New version of app loading a JS bundle from the previous version

### ISSUE THREAD

**Issue by gregdburns** [expo/expo#17770]
### Summary

We deployed a version of our app (1.3.0) to the app stores (Google Play Console and Apple App Store) roughly a month ago.  In the past week, we've deployed a new version of the app to the stores (1.4.0).

Despite the fact that the app stores show the 1.4.0 information (version numbers, descriptions, etc.), when the 1.4.0 app is loaded it launches the 1.3.0.

Our hypothesis is that 1.4.0 is loading the 1.30 JS bundle for some reason, despite the fact that they both use different release channels.

We do use expo-updates (0.11.6), and have OTA turned on.

This issue happens on both Android and iOS apps / stores.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44.0.0

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed

### Reproducible demo

App bundles can be provided, however we do not wish to put these out publicly.

The following code is run when both versions of the app loads, to check for updates:

```
const result = await Updates.checkForUpdateAsync()
if (result.isAvailable) {
    await Updates.fetchUpdateAsync()
    await Updates.reloadAsync()
}
```

Version 1.3.0 was built using `expo build --release-channel version1.3.0`

Version 1.4.0 was built using `expo build --release-channel version1.4.0`

**Comment by gregdburns** [comment]
If it's helpful - the problem goes away when I clear the storage/cache for the app and reload it.  At that point 1.4.0 loads without any issues.

**Comment by brentvatne** [comment]
this should be resolved in sdk 45, let us know if the issue persists

**Comment by gregdburns** [comment]
Confirmed with our latest release that this issue no longer happens.  Thanks very much @brentvatne !
