### ISSUE TITLE
[docs] "Uploading Server Credentials" section - where to find the "Server key"?

### ISSUE THREAD

**Issue by armenavanesi** [expo/expo#17771]
### Summary

The instructions on [Uploading Server Credentials](https://docs.expo.dev/push-notifications/using-fcm/#uploading-server-credentials) say:

1. At the top of the sidebar, click the gear icon to the right of Project Overview to go to your project settings.
2. Click on the Cloud Messaging tab in the Settings pane.
3. Copy the token listed next to Server key.

I'm unable to see anything about a Server key on this page. This is what I'm seeing:

![Screen Shot 2022-06-07 at 9 41 02 am](https://user-images.githubusercontent.com/59288041/172266746-2d2d5062-3056-448e-b418-4cc4c5adc147.png)

Do I need to hit "Generate key pair" and upload that?

### Link to the related docs page

https://docs.expo.dev/push-notifications/using-fcm/#uploading-server-credentials

**Comment by barthap** [comment]
Yeah, it's in the "legacy" section now:
<img width="1005" alt="Screenshot 2022-06-14 at 10 43 50" src="https://user-images.githubusercontent.com/278340/173535094-28782b30-3290-42a6-902c-0a06609a5eba.png">

**Comment by isaachinman** [comment]
@barthap Any word on plans to migrate to the new API? I was unable to find any official LTS schedules.
