### ISSUE TITLE
Use of LinearGradient component in Typescript expo template gives warning

### ISSUE THREAD

**Issue by aniketicloud** [expo/expo#17779]
### Summary

- In new typescript template project, after installing `expo-linear-gradient` and using `LinearGradient` component, the typescript gives following warning.
- `'LinearGradient' cannot be used as a JSX component.
  Its instance type 'LinearGradient' is not a valid JSX element.
    Types of property 'refs' are incompatible.
      Type '{ [key: string]:`
<img width="956" alt="image" src="https://user-images.githubusercontent.com/54700318/172573492-2bcfd1a2-bfc3-4e46-8f47-66b006019a3a.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

SDK 45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD  
    npmPackages:
      expo: ~45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed

### Reproducible demo

- run => expo init my-project 
- select typescript
- run=> expo install expo-linear-gradient
- import it in any .tsx file => import { LinearGradient } from "expo-linear-gradient";
- use the imported component => `<LinearGradient
        colors={["rgba(0,0,0,0.8)", "transparent"]}
      />`

**Comment by Simek** [comment]
Hello @aniketicloud, unfortunately I cannot reproduce the issue using the example code form `LinearGradient` docs in a newly created project.

Please make sure that you have the correct version of `react` and `react-native` types installed. You can also try running `expo doctor` which might help you localize the problem in your project. 

This also might be Editor settings/extensions related issue, so without the full repro project we won't be able to help you that much.

**Comment by aniketicloud** [comment]
- I also tried setting up from another laptop. 
- Same warning.
- Wait. I will publish my repo

**Comment by brentvatne** [comment]
if you add `import * as React from 'react';` at the top of your source this will resolve the issue - so this seems to be caused by the fact that we are using the new react jsx transform. we must be doing something wrong in expo-linear-gradient to not play nicely here.

**Comment by Simek** [comment]
I have followed the reproduction steps, but unfortunately I cannot repro this problem, which indicates to me that the types package resolution is to blame in there.

<img width="1050" alt="Screenshot 2022-07-14 at 00 29 05" src="https://user-images.githubusercontent.com/719641/178848072-ad206b27-754a-42d3-b6a2-0d6983cfa289.png">

**Comment by brentvatne** [comment]
I can't reproduce this anymore either. Not sure what changed but it seems like this is not an issue any longer
