### ISSUE TITLE
ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

### ISSUE THREAD

**Issue by rajeshgrapedata** [expo/expo#17781]
### Summary

App store build submission is failed with the below error.

We identified one or more issues with a recent delivery for your app,  AppName. Please correct the following issues, then upload again.

**ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.**

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.8.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-navigation: ^4.4.0 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

App store build submission is failed with the below error.

We identified one or more issues with a recent delivery for your app,  AppName. Please correct the following issues, then upload again.

**ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.**

**Comment by lekterable** [comment]
Hi, @rajeshgrapedata how did you resolve this?

**Comment by Gguigre** [comment]
Hello @rajeshgrapedata I am in the same situation with my team.
I saw that you closed the issue, and it would be very helpful if you could give an insight on what you did to solve this on your side !

**Comment by rajeshgrapedata** [comment]
Hey Guys, If you used the classic build system try the below command and reconnect your Apple account using the existing provisional profile and certificate.

```
expo build:iso -c
```
Once build is done .ipa size will increase automatically (it included required swift files)

**Comment by Gguigre** [comment]
Thank's for the update 
On our side, we regenerated a new provisionning profile from the apple dev console, and it all went good.
Maybe your solution would have been easier, but still posting if it can help someone !

**Comment by rohith-thummanapally** [comment]
hey hi, how to resolve the issue in expo dev client (EAS) system

**Comment by ShumGG** [comment]
@rohith-thummanapally make sure you dont have ```distribution: internal``` when building

**Comment by elyobo** [comment]
@ShumGG but... what if I want to do an internal distribution? Why should that not work?
