### ISSUE TITLE
Crash on iOS when choosing a long extension document with DocumentPicker.getDocumentAsync()

### ISSUE THREAD

**Issue by imagina** [expo/expo#17786]
### Summary

The steps are just two:
1 - Open the document picker
2 - Choose a ".pages" document or any file with a extension with more than 4 or 5 characters 
And the result is that the Expo Go app closes immediately (Both on emulator and physical iPhone).

In the code below it won't even enter into the catch, it crashes at the exact moment I select the document.

It works perfect with all the rest of the extensions and on Android it doesn't crashes.

![image](https://user-images.githubusercontent.com/758247/172715711-08c067c2-42e5-4949-a559-e25de6f2507b.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

Expo CLI 5.0.3 environment info:
System:
OS: macOS 12.0.1
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 14.18.0 - /usr/local/bin/node
Yarn: 1.22.17 - /usr/local/bin/yarn
npm: 8.1.3 - /usr/local/bin/npm
Watchman: 2022.01.03.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.2 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
IDEs:
Android Studio: 2020.3 AI-203.7717.56.2031.7935034
Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
npmPackages:
babel-preset-expo: 8.5.1 => 8.5.1
expo: ^43.0.0 => 43.0.5
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.3 => 0.64.3
react-native-web: 0.17.1 => 0.17.1
npmGlobalPackages:
eas-cli: 0.35.0
expo-cli: 5.0.3
Expo Workflow: managed

### Reproducible demo

<Button
        title="Upload Resume"
        onPress={() => {
          DocumentPicker.getDocumentAsync().then( result => {
            if (result.type === 'success') {
              console.log('Worked!!')
            }
          }).catch( error => {
            throw new Error(error)
          })
        }}
      />

**Comment by cdeviabylte** [comment]
Same issue here.

**Comment by Simek** [comment]
Can confirm, it looks like the crash might be related to the unknown MIME types. 

Opening all the following stub files using https://snack.expo.dev/@simek/document-picker-crash-ios Snack leads to the Expo Go crash:
* `*.pages`
* `*.sketch`
* `*.hex`
* `*.x`, `*.xx`, `*.xxx`, `*.xxxx`, `*.xxxxx`

**Comment by brentvatne** [comment]
this should be fixed in sdk 45 with https://github.com/expo/expo/commit/40ef7d693cc273ed5efc3d25621e8ef852ec5663
