### ISSUE TITLE
Error on init with template using @chip/ in name from 5.4.7 onward

### ISSUE THREAD

**Issue by tacomanator** [expo/expo#17788]
### Summary

`expo init myproject --template @realm/expo-template-ts` works fine in 4.5.6,
but from 4.5.7 to 4.5.9 it results in an error such as the following:

```
Error: ENOENT: no such file or directory, open '~/.expo/template-cache/@realm/expo-template-ts-0.3.0.tgz'
⠋ Downloading template.%
```

Expo appears to be downloading the template file to `~/.expo/template-cache/expo-template-ts-0.3.0.tgz`, but expo-cli is looking for it in ~/.expo/template-cache/_@realm_/expo-template-ts-0.3.0.tgz

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.4.9
    Expo Workflow: managed

### Reproducible demo

npm install -g expo-cli@5.4.9
expo init myproject --template @realm/expo-template-ts

**Comment by MeteorRyan** [comment]
Thanks, believe I hit the same issue and couldn't figure it out

`yarn global add expo-cli@5.4.6`

And I was able to download the template

**Comment by brentvatne** [comment]
fixed in latest expo-cli
