### ISSUE TITLE
[docs] Missing flag in documentation

### ISSUE THREAD

**Issue by GiovanniCapizzi** [expo/expo#17797]
### Summary

I'm using expo-location, I've read the docs and I could not make geofence work on Android 10+ (real device).
The error was: `Not authorized to use background location services.`. 
I had to add to my `app.json` this flag in the android section :

```      
"permissions": [
        "ACCESS_BACKGROUND_LOCATION"
]
```

      
 Am I missing something from the documentation? 

Here is the official doc where I took the flag: [link](https://developer.android.com/training/location/background).

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/location/

**Comment by brentvatne** [comment]
https://github.com/expo/expo/commit/059698ad9a686c126a358894c8215909ac06c7ef
