### ISSUE TITLE
Gyroscope code from docs not working

### ISSUE THREAD

**Issue by davidgithub1980** [expo/expo#1779]
"expo": "^27.0.1",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
"react-navigation": "^2.0.1"

Hi, there appears to be trouble with the Gyroscope part of the Expo docs. Accelerometer is doing fine.

Copy pasting the Gyroscope docs code to quickly get it running and tuning on a real physical device, the listener receives no updates now matter how frantically the phone is tilted etc. The story goes well with the accelerometer (i.e. its listener receives updates). Can you help?

**Comment by quinlanj** [comment]
hi @davidgithub1980 -- what phone model are you using, and can you post a snack of your code (ie) snack.expo.io ? I copy-pasted the demo app, and it seems to work on my test device (Nexus 5) https://snack.expo.io/@quinlanj/gyroscope .

**Comment by davidgithub1980** [comment]
Hi @quinlanj You are right. My bad. Despite having quite a new device - Sony Xperia XA1 ULTRA -, it lacks gyroscope support :-( Maybe, just like Modernizerr for web development, unsupported feature might cast some type of (console) message.
