### ISSUE TITLE
[docs] Slider

### ISSUE THREAD

**Issue by AtilaDev** [expo/expo#17790]
### Summary

Hi, there is a bug in documentation regarding the Slider component:

In the Expo docs: 
```
expo install react-native-slider
```

But this doesn't work. Maybe do you wanted to say:

```
expo install @react-native-community/slider 
```

### Link to the related docs page

https://docs.expo.dev/versions/v45.0.0/sdk/slider/

**Comment by Simek** [comment]
This issue has been solved in https://github.com/expo/expo/pull/17805.
