### ISSUE TITLE
Consistency issue between SecureStore and LocalAuthentication on Biometric strength

### ISSUE THREAD

**Issue by taylorkline** [expo/expo#17804]
### Summary

SecureStore [rejects if `BIOMETRIC_STRONG` is not available](https://github.com/expo/expo/blob/21d4420641648e1fd9353121b31ec074506813cd/packages/expo-secure-store/android/src/main/java/expo/modules/securestore/AuthenticationHelper.kt#L128), with the following message:

> No hardware available for biometric authentication. Use expo-local-authentication to check if the device supports it.

However, [LocalAuthentication only checks if `BIOMETRIC_WEAK` or higher](https://github.com/expo/expo/blob/21d4420641648e1fd9353121b31ec074506813cd/packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt) authenticators are available.

Therefore, it is feasible that `LocalAuthentication` indicates that the device has authenticators, but `SecureStore` rejects on `requireAuthentication`.

Proposed solutions:

- Disallow weak authenticators entirely and search only for `BIOMETRIC_STRONG` in `LocalAuthentication`
  - I'm currently doing this locally with `patch-package`
- Or, allow the user to specify they only want `BIOMETRIC_STRONG` authenticators via a param to `supportedAuthenticationTypesAsync`, and document that only `BIOMETRIC_STRONG` is supported with `SecureStore` + `requireAuthentication`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

This is not environment dependent.

### Reproducible demo

As this depends on hardware, this is not reproducible. Please view the links to the code in question.

**Comment by taylorkline** [comment]
Polite pings to @j-piasecki @fguitton @lukmccall and @byCedric 😃

**Comment by bbarthec** [comment]
Hey @taylorkline 👋
I understand the problem and I after reading proposed solutions of yours I think the better option would be to follow this one:
> - Or, allow the user to specify they only want BIOMETRIC_STRONG authenticators via a param to supportedAuthenticationTypesAsync, and document that only BIOMETRIC_STRONG is supported with SecureStore + requireAuthentication

So desired steps are:
1. make `LocalAuthentication` accept some parameter or expose some additional API to check against different levels of biometric auth available on the device
2. add some documentation/clarification around `SecureStore` working only if `BIOMETRIC_STRONG` is satisfied by the device

As I see you've done some work with this:
> I'm currently doing this locally with patch-package
do you mind trying delivering some PR with the implementation? 👀

**Comment by bbarthec** [comment]
@taylorkline, that's great that you've succeeded in solving it on your own 👏 

It would be super awesome if you would find some time to shape a PR with this other solution we've discussed above 👀 But no hurries here! 😉 

And congrats on moving to your new house 😉 I guess your new place is awesome (or at least much better then the previous one) 😁

**Comment by fguitton** [comment]
This is still relevant as it might relate to a conversation surrounding insecure result-based local authentication rather than event-based.

**Comment by fguitton** [comment]
Not stale :balloon:

**Comment by taylorkline** [comment]
And thank you for the review @lukmccall and @amandeepmittal

**Comment by jacksondoherty** [comment]
I'm working on an app that stores a sensitive keypair. I'd love to recommend that users turn on strong biometrics if their device supports it. The current solution above only indicates if strong biometrics are enrolled (ex. via `canUseBiometricAuthentication()` in `SecureStore`). It cannot tell you that a device is _capable_ of strong biometrics but does not have them enrolled.
