### ISSUE TITLE
expo doctor leads to Failed to find dependency tree for expo-modules-autolinking

### ISSUE THREAD

**Issue by ansh** [expo/expo#17803]
### Summary

I recently migrated my managed expo project to expo-dev-client and whenever I run `expo start --dev-client` it tells me some of my packages are outdated. 

I ran `expo doctor` to fix it but I get the error `Failed to find dependency tree for expo-modules-autolinking`

### What platform(s) does this occur on?

Android, iOS

### SDK Version

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.8
    Expo Workflow: managed

### Reproducible demo

I do not have a reproducible demo but installing `expo-cli` version 5.4.9 fixed this issue for me and might be helpful for others

**Comment by ansh** [comment]
Also, just a note but now when I run `expo doctor` it gives me the following error:

```
❯ expo doctor --fix-dependencies
✖ Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/prebuild-config failed. This validation is only available on Node 16+ / npm 8.
```

**Comment by dmdmd** [comment]
@ansh I had the same problem and "solved" it by adding the following resolution in `package.json`

```
  "resolutions": {
    "expo-modules-autolinking": "~0.8.1"
  },
```

I think this is a temporary fix due to some packages still indirectly calling an old version of `expo-modules-autolinking`.

**Comment by brentvatne** [comment]
> Also, just a note but now when I run `expo doctor` it gives me the following error:
> 
> ```
> ❯ expo doctor --fix-dependencies
> ✖ Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
> ✖ Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
> ✖ Dependency tree validation for @expo/prebuild-config failed. This validation is only available on Node 16+ / npm 8.
> ```
> 
> There is no where in the documentation that says that I need Node 16+ or npm 8 to run `expo doctor`

this is a new feature in `expo doctor` and we can only make it work with node 16+ and so we add a warning here about it. previously it would fail in an unhandled way without useful context and so the warning we provide about node version is meant to help to understand why this is happening.

this is self documenting in that you run the command and you will see that for this specific feature of this command this node version is required

**Comment by danstepanov** [comment]
A bit confused by this.
```
➜  myapp git:(main) ✗ npm -v
8.13.2
➜  myapp git:(main) ✗ node -v
v16.14.2
➜  myapp git:(main) ✗ expo doctor
✖ Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/prebuild-config failed. This validation is only available on Node 16+ / npm 8.

🎉 Didn't find any issues with the project!
```

**Comment by stevenbrown-85** [comment]
Did anyone find find a resolution to this? I'm getting the same issues and unable to build with eas. I've tried using resolutions but no joy!

**Comment by sirtok4** [comment]
Any news?

**Comment by Arnav7501** [comment]
anything?

**Comment by Shaunmak1214** [comment]
any news????

**Comment by ansh** [comment]
Just upgrade your node version. That is the only way.

**Comment by danharten-sovtech** [comment]
I still get this error on node 20.
