### ISSUE TITLE
react-native-community dependencies crashing in a monorepo

### ISSUE THREAD

**Issue by mattrabe** [expo/expo#17800]
### Summary

I'm experiencing fatal `requireNativeComponent: "RNCPicker" was not found in the UIManager.` and `requireNativeComponent: "RNCSlider" was not found in the UIManager.` when I build and run an iOS app from my monorepo.

I'm a little unsure where this ticket belongs... it pertains to Expo in a monorepo, as well as @react-native-picker/picker and @react-native-community/slider. Since the error I am experiencing is the same for both of those dependencies I believe it is related more to Expo rather than those packages.
 
I have a yarn workspaces monorepo that has a structure like this:

```
repo/
├─ apps/
│  ├─ expo-app-1/
│  │  ├─ package.json
│  ├─ expo-app-2/
│  │  ├─ package.json
├─ packages/
│  ├─ ui-library/
│  │  ├─ package.json
├─ package.json
```

The ui-library package contains components that are used by both expo-app-1 and expo-app-2, and both expo-app-1 and expo-app-2 list ui-library as a package.json dependency.

The ui-library package includes package.json dependencies for @react-native-picker/picker and @react-native-community/slider. It has two components - let's call them Picker and Slider - which use those dependencies.

I experience the following:

* Running locally (`expo start`) on a physical iOS device works fine - no error. Picker works fine, Slider works fine.
* When I build expo-app-1 or expo-app-2 using (`eas build`), install on a physical iOS device (using TestFlight), and access a screen which uses the Picker or Slider component I get a fatal crash with the following error:
    - `requireNativeComponent: "RNCPicker" was not found in the UIManager.` or `requireNativeComponent: "RNCSlider" was not found in the UIManager.`

**BUT** - if I add @react-native-picker/picker and @react-native-community/slider as package.json dependencies directly to the expo-app-1 and expo-app-2 packages, build in the same way, and run in the same way, **no error occurs and the Picker and Slider components work fine.** Those apps do NOT import from those package dependencies anywhere - only ui-library does.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45.0.4

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2022.03.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.9
    Expo Workflow: managed

### Reproducible demo

# packages/ui-library

**package.json**

```
{
  "name": "@rnc-deps/ui",
  "private": true,
  "main": "./src/index.ts",
  "dependencies": {
    "@react-native-community/slider": "4.2.1",
    "@react-native-picker/picker": "2.4.0",
    "expo": "^45.0.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "styled-components": "^5.3.3"
  }
}
```

**src/index.ts**

```
export { default as Picker } from './components/Picker'
```

**src/components/Picker/index.tsx**

```
import React from 'react'

import {
  StyledItem,
  StyledPicker,
} from './styles'

function Picker() {
  return (
    <StyledPicker>
      <StyledItem label='one' value={1} />
      <StyledItem label='two' value={2} />
    </StyledPicker>
  )
}

export default React.memo(Picker)
```

**src/components/Picker/styles.ts**

```
import styled from 'styled-components/native'
import { Picker } from '@react-native-picker/picker'

export const StyledPicker = styled(Picker)`
`

export const StyledItem = styled(Picker.Item)`
`
```

# apps/expo-app

**package.json**

```
{
  "name": "@rnc-deps/expo-app",
  "private": true,
  "main": "index.js",
  "scripts": {
    "start": "cross-env APP_ENV=local expo start --clear",
    "build": "eas build"
  },
  "dependencies": {
    "@rnc-deps/ui": "^0.0.8",
    "expo": "^45.0.0",
    "expo-application": "~4.1.0",
    "expo-asset": "~8.5.0",
    "expo-constants": "~13.1.1",
    "expo-dev-client": "~0.10.0",
    "expo-device": "~4.2.0",
    "expo-linking": "~3.1.0",
    "expo-splash-screen": "~0.15.1",
    "expo-system-ui": "~1.2.0",
    "expo-updates": "~0.13.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "sentry-expo": "^4.2.0",
    "styled-components": "^5.3.3"
  },
  "devDependencies": {
    "cross-env": "^7.0.3"
  }
}
```

**eas.json**

```
{
  "build": {
    "production": {
      "node": "16.13.2",
      "developmentClient": false,
      "android": {
        "buildType": "app-bundle"
      },
      "ios": {
        "image": "latest"
      },
      "env": {
        "APP_ENV": "production",
        "SENTRY_ENABLED": "true"
      }
    },
    "qa": {
      "extends": "production",
      "android": {
        "buildType": "apk"
      },
      "env": {
        "APP_ENV": "qa",
        "SENTRY_ENABLED": "true"
      }
    },
    "development": {
      "extends": "production",
      "android": {
        "buildType": "apk"
      },
      "env": {
        "APP_ENV": "development",
        "SENTRY_ENABLED": "true"
      }
    }
  },
  "cli": {
    "version": ">= 0.48.2"
  },
  "submit": {
    "production": {}
  }
}
```

**src/index.js**

```
/* This file is required as per https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in */

import { registerRootComponent } from 'expo'

import App from './src/App'

// registerRootComponent calls AppRegistry.registerComponent('main', () => App)
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App)
```

**src/App/index.tsx**

```
import React from 'react'
import * as Sentry from 'sentry-expo'

import { Picker } from '@rnc-deps/ui'

Sentry.init({
  dsn: 'https://xxx.ingest.sentry.io/yyy',
  enableInExpoDevelopment: true,
  debug: true,
  environment: process.env.APP_ENV,
})

function App() {
  return <Picker />
}

export default App
```

**Comment by brentvatne** [comment]
it's necessary to include modules linked via react-native-community autolinking as direct dependencies in your app package.json otherwise they won't be linked. transitive dependencies are *not linked* with react-native-community autolinking (however this does work for expo modules with our autolinking implementation). https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
