### ISSUE TITLE
Expo Camera uses incorrect focus value for iOS when autoFocus prop is bool

### ISSUE THREAD

**Issue by yhkaplan** [expo/expo#17806]
### Summary

Autofocus on iOS is being set to `AVCaptureFocusModeAutoFocus` when autoFocus prop on Camera is set to `true`. `AVCaptureFocusModeAutoFocus` only focuses once then stops, while [AVCaptureFocusModeContinuousAutoFocus](https://developer.apple.com/documentation/avfoundation/avcapturefocusmode/avcapturefocusmodecontinuousautofocus?language=objc) is the desired value that's set when "on" is passed to the autoFocus prop and is the more expected behavior. 

I can make a PR, but I wonder what layer it would be best to convert the value in?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

Latest

### Environment

n/a

### Reproducible demo

`<Camera autoFocus />`

**Comment by kbrandwijk** [comment]
We would definitely welcome a PR. Have a look at the existing code where the `autoFocus` JavaScript value is translated to the native property.
