### ISSUE TITLE
ImageManipulator: Invalid crop options has been passed. Please make sure the requested crop rectangle is inside source image.

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#17807]
### Summary

I am cropping an image (h: 2243px, w: 1683px) using the following properties:

```
const actions = [
   {
       crop: {
          originX: 0,
          originY: 0,
          width: 1683, // same as the image width!
          height: 1683,
       },
   },
];

const manipulatedPhoto = await ImageManipulator.manipulateAsync(
    photo.uri,
    actions,
    saveOptions
);
```

As you can see, the crop rectangle is inside the source image, because originX and originY is equal to 0.

For some (unexpected?) reason, I am getting this error:

> Invalid crop options has been passed. Please make sure the requested crop rectangle is inside source image.

And, in order to fix it, I have to subtract one pixel to the width of the crop rectangle.

Is this a bug? Or is `crop.rectangle.width === photo.width` is illegal? 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

^44.0.0

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.12.1 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^44.0.0 => 44.0.5 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3 
      react-native-web: ^0.17.5 => 0.17.5 
    Expo Workflow: managed

### Reproducible demo

Crop an image with the dimensions __1683x2243__ and run the following:

```
const actions = [
   {
       crop: {
          originX: 0,
          originY: 0,
          width: 1683, // same as the image width!
          height: 1683,
       },
   },
];

const saveOptions = {
    format: ImageManipulator.SaveFormat.JPEG,
    compress: 0.75,
    base64: false,
};

const manipulatedPhoto = await ImageManipulator.manipulateAsync(
    photo.uri,
    actions,
    saveOptions
);

```

**Comment by VictorioMolina** [comment]
Testing on iPhone 12 Pro 14.4

**Comment by jurica-penjgusic** [comment]
I think it is related to https://github.com/expo/expo/issues/17875 and https://github.com/expo/expo/issues/17847

**Comment by daves28** [comment]
This is still an issue in 2025, it shouldn't be marked as completed. Appears on Android for me.
