### ISSUE TITLE
Unable to build exterprise apple ipa

### ISSUE THREAD

**Issue by ahmad4zan** [expo/expo#1780]
### Environment

 OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/ahmad4zan-2a3fbd13-6766-43b8-b541-89d12828c731.tar.gz

Currently trying to build an enterprise ipa

### Steps to Reproduce

1.  exp build:ios --apple-enterprise-account
2. Failed |14:43:26 [exp] Standalone build failed!
### Expected Behavior

I should get an ipa download link

### Actual Behavior

|14:43:26 [exp] Standalone build failed!
<img width="1236" alt="screen shot 2018-05-22 at 2 54 18 pm" src="https://user-images.githubusercontent.com/2517241/40346640-0e28f0b6-5dd0-11e8-9be6-cd9343121bfe.png">

build link
https://expo.io/builds/0d420371-951f-4b24-93a6-89a75ec964f2

**Comment by schazers** [comment]
Possibly related: https://forums.expo.io/t/unable-to-build-and-sign-ipa/10047

**Comment by schazers** [comment]
Hi @ahmad4zan - we've just deployed some changes to the build service that should output more helpful errors. Would you mind running it again and letting us know what it outputs?

**Comment by ahmad4zan** [comment]
<img width="1244" alt="screen shot 2018-05-23 at 8 56 29 am" src="https://user-images.githubusercontent.com/2517241/40397834-6327927e-5e67-11e8-8a2e-00a6bb42abe3.png">
<img width="1182" alt="screen shot 2018-05-23 at 8 56 34 am" src="https://user-images.githubusercontent.com/2517241/40397835-635e1f56-5e67-11e8-8e7f-74c6c999f1dd.png">
Hi, this is the error message that i've received.

https://expo.io/builds/0d420371-951f-4b24-93a6-89a75ec964f2

**Comment by dsokal** [comment]
@ahmad4zan 
This time we **really** deployed some changes to the build service (previously we only thought we did it) and we're getting more detailed errors from "generating IPA" step. Could you run `ios:build` again and send us build id / url? Thanks!

**Comment by ahmad4zan** [comment]
<img width="621" alt="screen shot 2018-05-24 at 12 05 34 am" src="https://user-images.githubusercontent.com/2517241/40436766-48ffca18-5ee6-11e8-85af-4396a6bb3933.png">
Hi, currently i have this problem when i'm signing in. should i make as a new issue?

Happen after i did
exp build:ios --apple-enterprise-account

**Comment by nicknovitski** [comment]
I recommend logging in to apple's developer website and checking if you need to accept their new privacy terms.

**Comment by ahmad4zan** [comment]
<img width="1198" alt="screen shot 2018-05-24 at 5 23 59 am" src="https://user-images.githubusercontent.com/2517241/40451898-b3e52680-5f12-11e8-927a-7c20283398f7.png">
<img width="1070" alt="screen shot 2018-05-24 at 5 23 50 am" src="https://user-images.githubusercontent.com/2517241/40451899-b417476e-5f12-11e8-86ee-bc259a3a8b79.png">
The previous error is dismissed by accepting the terms. but this is the the error i've got with with the newest compilation. I've also updated the bundleIdentifier to match with the provisioning  profile

build link - https://expo.io/builds/5e4643f7-eb84-4d83-895b-7dcc590642ab

**Comment by dsokal** [comment]
@ahmad4zan 
We have more detailed logs which we intentionally hide from users. The problem is, your provisioning profile is not associated with distribution certificate which you have uploaded to our servers. 
Please check this thread - https://forums.expo.io/t/ios-standalone-build-failed/10007/8

**Comment by ahmad4zan** [comment]
I've resolve the error by removing the --apple-enterprise-account
