### ISSUE TITLE
viewManagersMetadata is undefined for expo-camera

### ISSUE THREAD

**Issue by ahdam** [expo/expo#17818]
### Summary

I'm trying to install expo-camera in a RN project.
It's a BARE workflow, but I'm not sure why "npx expo-env-info" returns: "Expo Workflow: managed".
I followed [this guide ](https://docs.expo.dev/bare/installing-expo-modules/)for installing expo modules.

"react-native": "0.66.4",
"expo": "^45.0.5",
"expo-camera": "~12.2.0",
"expo-modules-core": "^0.9.2",

Just trying to integrate the Camera into a page returns this errors:

TypeError: Cannot read properties of undefined (reading 'viewManagersMetadata') 
ExceptionsManager.js:184 Error: Requiring module "node_modules/expo-camera/build/index.js", which threw an exception: TypeError: Cannot read properties of undefined (reading 'viewManagersMetadata') 
TypeError: Cannot read properties of undefined (reading 'Camera')

(iOS works fine)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.18 - ~/apps/tp/mobile-app/node_modules/.bin/yarn
      npm: 6.14.8 - ~/apps/tp/mobile-app/node_modules/.bin/npm
      Watchman: 2022.01.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 26, 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 32.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.4.9
    Expo Workflow: managed

### Reproducible demo

`<Camera type={Camera.Constants.Type.front} />`

**Comment by ahdam** [comment]
@sergiulucaci I upgraded React Native to 0.68.2

**Comment by ENGR-MANSOOR** [comment]
Can you please guide me about this issue as i am facing same too and my react native version is 0,70,0

**Comment by yousrasd** [comment]
Same here, running into same issue with ReactNative 0.70.2

**Comment by yousrasd** [comment]
@ahdam did you do anything special when you upgraded to RN 0.68.2 to link/configure expo-camera? Even tried with 0.68 and it still failed with same error!

**Comment by fukemy** [comment]
any solution?

**Comment by HeyItsJs** [comment]
I am facing same issue with react native 0.72.1. Did you guys find any solution?

**Comment by AlexisLeclercq** [comment]
not sure if it will help you but for my case the `expo-modules-core` was not linked from `MainApplication.java` and `MainActivity.java`.

I needed to follow [https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-android](https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-android) and it worked.

I'm using RN 0.72.4 with Hermes
