### ISSUE TITLE
[expo-speech] Unable to control text volume

### ISSUE THREAD

**Issue by Tenpeter** [expo/expo#17815]
### Summary

I'm unable to control the volume of the spoken text, according to the api documentation https://docs.expo.dev/versions/latest/sdk/speech/, we can pass volume parameter to control the volume but it doesn't work.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

45

### Environment

Snack

### Reproducible demo

https://snack.expo.dev/@lekgwaraj/speech

**Comment by barthap** [comment]
It's undocumented 🙄, but volume currently is a web-only parameter. It is a number ranging `0.0 - 1.0` (1 is the default).
