### ISSUE TITLE
ExpoKit add custom react-native-lottie library

### ISSUE THREAD

**Issue by loic-lopez** [expo/expo#1781]
Hi,

I would like to know if it is possible to override lottie library by official lottie library from ExpoKit dependency in PodFile?

Thanks for reply.

**Comment by schazers** [comment]
Hi! Do you think you could post this question to our forums at https://forums.expo.io/ and we could help you there? I think some other people might have the same issue in the future and if we put it on the forums, it’ll be a lot easier for other people to find the answer later.

**Comment by loic-lopez** [comment]
Yes no problem and in which section of the forum?

**Comment by schazers** [comment]
The "Help with Expo" section is great for questions like this. Thanks!

**Comment by loic-lopez** [comment]
Thanks again!

I will leave the link after i posted on the forum.

**Comment by loic-lopez** [comment]
Link :[]( https://forums.expo.io/t/expokit-add-official-react-native-lottie-library/10063)
