### ISSUE TITLE
Document Picker not working on IOS Bare Workflow

### ISSUE THREAD

**Issue by cawil-ai** [expo/expo#17827]
### Summary

Hello, I have been working on an app for my client which provides uploading specific documents. My previous co-developer uses expo-document-picker for uploading documents and when I was testing to an IOS Simulator, it never worked. I have followed this documentation on how to manage icloud also: [DocumentPicker - Expo Documentation](https://docs.expo.dev/versions/latest/sdk/document-picker/#bare-workflow) but it seems it never worked… I have also included some specific app.json for icloud like I included usesIcloudStorage and the plugins… I dont know why it is never worked

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      npm: 8.5.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

<img width="722" alt="Screen Shot 2022-06-12 at 7 30 15 PM" src="https://user-images.githubusercontent.com/60929947/173269859-810d9988-24ff-4277-b4ed-4ae2132f473e.png">
const selectFileIdPicture = async () => {
     const res = await DocumentPicker.getDocumentAsync({ type: "image/*" });
     console.log(res);
     if (res.type === "success") {
       alert(res);
       setFileNameIdPicture(res.name);
       setFileUriIdPicture(res.uri);
     }
  };

It is in bare workflow and i cant put a snack output

**Comment by douglasjunior** [comment]
@cawil-ai can you solve the issue?
