### ISSUE TITLE
expo-file-system: FileSystem.uploadAsync errors not from the server return an HTML document

### ISSUE THREAD

**Issue by Chip-L** [expo/expo#17820]
### Summary

When using the FileSystem.uploadAsync to send the file up to the server, if the user enters an incorrect URL, the response body is an HTML document. This makes it difficult to capture the error message in to a state to display in a component.

So, if I go set up my function as so:
`const response = await FileSystem.uploadAsync( "http://bad-url.com", pathToImage, {httpMethod: "POST"});`

Then my resposnse.body is:
```
<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```
If the server sends back an error response, the response is added to the body, as expected. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

45.0.0

### Environment

expo-env-info 1.0.3 environment info:
	System:
		OS: Windows 10 10.0.19044
	Binaries:
		Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
		Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
		npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
	npmPackages:
		expo: ~45.0.0 => 45.0.0
		react: 17.0.2 => 17.0.2
		react-dom: 17.0.2 => 17.0.2
		react-native: 0.68.2 => 0.68.2
		react-native-web: 0.17.7 => 0.17.7
	Expo Workflow: managed

### Reproducible demo

link to snack: https://snack.expo.dev/@chiptest1/imageupload

```
const upload = async () => {
  setMessage('');
  setErrMessage('');

  if (pickedImagePath) {
    try {
      const response = await FileSystem.uploadAsync(URL, pickedImagePath, {httpMethod: 'POST',});

      if (response.status >= 200 && response.status < 300) {
        const body = JSON.parse(response.body);
        setMessage(body.msg);
      } else {
        setErrMessage(`${response.status} Error: ${response.body}`);
      }
    } catch (err) {
      console.error(err);
      setErrMessage(err.message);
    }
  }
};
```

**Comment by brentvatne** [comment]
add headers to indicate you want a json response if that's what you prefer :) https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemuploadasyncurl-fileuri-options

**Comment by Chip-L** [comment]
I thought I'd tried that... :( Thanks!

**Comment by R-Art-project** [comment]
headers: {
              "Content-Type": "application/json",       // <--------------- this line in your header
              Authorization: `Bearer ${authContext.token}`,
},
