### ISSUE TITLE
[docs] Snack example for "web workaround" fails with CORS error

### ISSUE THREAD

**Issue by gregfenton** [expo/expo#17824]
### Summary

On the page for [Handling Platform Differences](https://docs.expo.dev/tutorial/platform-differences/), the SNACK example launches an app that when you go to upload an image with Web, it fails with a CORS error.

Steps to repro:

1. Go to the above docs page
2. Click the button to launch the SNACK
3. Make sure you have WEB selected
4. When WEB starts up, click the PICK A PHOTO image and select a photo to upload
5. Check the JS console

**Expected**: the photo gets posted without issues

**Actual**:
```
Access to fetch at 'https://api.anonymousfiles.io/' from origin 'https://snack-web-player.s3.us-west-1.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Link to the related docs page

https://docs.expo.dev/tutorial/platform-differences/

### Anything else?

This was raised yesterday & today linojon aand LifeSword on the Discord server in the #expo channel.

**Comment by kbrandwijk** [comment]
Additional into: the website redirects to a torrent site now, and the API used by anonymous-files throws a 526 from Cloudflare, so it seems this file upload service is no longer available in this form.

**Comment by shelmire** [comment]
@amandeepmittal In the short term perhaps this page should be removed for now, or at least we can add a big red warning at the top saying the example is not working any longer but you're looking for a workaround. A non-working example in a tutorial is alarming, and when I encounter things like this I usually decide not to utilize the technology. I don't know which is preferable in this case - I can open a PR if you let me know. Creating an alternative example should probably be done by someone with more RN/expo experience than me.
