### ISSUE TITLE
How can i receive android broadcast with expo

### ISSUE THREAD

**Issue by kirning** [expo/expo#1783]
Can I get android broadcast information with expo? For example, low battery notification.

**Comment by ccheever** [comment]
Hi-

You can vote on or comment on or add feature requests for Expo here: 
https://expo.canny.io/feature-requests

Here is one specifically for battery charging information:
https://expo.canny.io/feature-requests/p/battery-statuscharging-api

Unfortunately, that feature isn't part of the SDK yet.

In the meantime, you could detach to ExpoKit and add your own native code or some module like react-native-device-battery (which I haven't tested but seems like it might work) if you like.
https://docs.expo.io/versions/latest/expokit/detach#__next
https://github.com/robinpowered/react-native-device-battery

Good luck!
