### ISSUE TITLE
[expo-in-app-purchases] connectAsync() never resolves on Android if not connected to Play Store

### ISSUE THREAD

**Issue by arcln** [expo/expo#17830]
### Summary

`InAppPurchases.connectAsync()` never returns when not connected to Play Store.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45.0.0

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    Expo Workflow: bare

### Reproducible demo

* Start a fresh Android emulator, I used a Pixel 4 on API 31.
* Call `InAppPurchases.connectAsync()`
* Notice it never resolves
* (optional) Open Play Store app and login
* (optional) Re-call `InAppPurchases.connectAsync()`, notice it works as expected.

**Comment by brentvatne** [comment]
i'd recommend trying out revenuecat's integration for a more fully featured option than what is available as of june 2022 in expo-in-app-purchases. we aren't actively working on this module at the moment so you will likely have more success with revenuecat's library. see this post for more info: https://www.revenuecat.com/blog/using-revenuecat-with-expos-managed-workflow/
