### ISSUE TITLE
expo-camera peer dependency conflict with npm 7+ due to @koale/useworker

### ISSUE THREAD

**Issue by stevehs17** [expo/expo#17846]
### Summary

The expected behavior is that when I install expo-camera in a React Native app created by running `npx react-native init`, which uses react 17.0.2, there will be a version of react that satisfies all peerDependencies. 

However, I get this error: `Unable to find a version of react that satisfies the following peerDependencies: 17.0.2 and ^16.0.0 || ^17.0.0 || ^18.0.0 and ^16.8.0 and ^16.0.0 || ^17.0.0 and ^16.8.0 || ^17.0.0`. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.11.1/bin/yarn
      npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
      Watchman: 2022.05.23.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 25, 27, 29, 30, 31
        Build Tools: 27.0.3, 29.0.2, 30.0.1, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Reproducible demo

Run the following commands:

`npx react-native init expovideo`
`cd expovideo`
`npx install-expo-modules@latest`
`expo install expo-camera`

Then run `npx check-peer-dependencies --findSolutions`. The output includes this:
❌  Unable to find a version of react that satisfies the following peerDependencies: 17.0.2 and ^16.0.0 || ^17.0.0 || ^18.0.0 and ^16.8.0 and ^16.0.0 || ^17.0.0 and ^16.8.0 || ^17.0.0

The error is due to the package @koale/useworker:
❌ react ^16.8.0 is required by @koale/useworker@4.0.2) (17.0.2 is installed)

**Comment by brentvatne** [comment]
https://github.com/alewin/useWorker/issues/123

**Comment by stevehs17** [comment]
Thank you @brentvatne 

I haven't been having problems building since I'm using yarn. However, I am concerned about the underlying problem rather than the symptom. What would be involved in fixing the underlying problem?

**Comment by brentvatne** [comment]
correct - updating the react dependency for `@koale/useworker` is one solution. another is to move off of that dependency in expo-camera

**Comment by stevehs17** [comment]
Thanks, @brentvatne

**Comment by Buddimal-Liyanapathirana** [comment]
ran to this error and fixed it after running the command  **npx expo install expo-updates**

**Comment by minifisk** [comment]
Wait what? You aren't putting priority on an issue where those that use expos latest SDK can ask users for permissions to use the camera? Don't you find that a pretty central functionality that we as developers should be able to use with your software?

**Comment by freewill777** [comment]
i'm still having this issue

**Comment by sunnyrod** [comment]
The "Basic Camera usage" example from [expo-camera usage doc](https://docs.expo.dev/versions/latest/sdk/camera/#usage) works in Expo Snack web view, see example: 
https://snack.expo.dev/@sunnyr/basic-camera-usage
[basic-camera-usage.zip](https://github.com/expo/expo/files/12208139/basic-camera-usage.zip)

I have attached zip of project export from Expo Snack.

Extracting the `package.json` reveals that the example also uses react@18. **What is Expo Snack doing differently that allows it to use expo-camera@13.2.1 which has dependency on @koale/useworker@4.0.2?**


```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.18",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "expo-camera": "~13.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

The `package-lock.json` shows that @koale/useworker@4.0.2 has a peerDependency on react@16:
```json
...
    "node_modules/expo-camera/node_modules/@koale/useworker": {
      "version": "4.0.2",
      "resolved": "https://registry.npmjs.org/@koale/useworker/-/useworker-4.0.2.tgz",
      "integrity": "sha512-xPIPADtom8/3/4FLNj7MvNcBM/Z2FleH85Fdx2O869eoKW8+PoEgtSVvoxWjCWMA46Sm9A5/R1TyzNGc+yM0wg==",
      "dependencies": {
        "dequal": "^1.0.0"
      },
      "peerDependencies": {
        "react": "^16.8.0"
      }
    },
...
```

**Comment by abramfh** [comment]
Any updates?

My application uses camera and it is no longer possible to generate builds for the play store using expo , because of this problem, as I did not find a solution I am having to abandon expo
