### ISSUE TITLE
QR code scanner does not work on QR codes with a black background

### ISSUE THREAD

**Issue by WouterVanHecke** [expo/expo#17849]
### Summary

Expected behaviour: The QR scanner can scan the QR code.
Actual behaviour: The `onBarCodeScanned` never gets fired.

When the QR code has a black background around it.
Even some phones can't handle a small white border around it, a bigger white border does work

Doesn't work:
![Screenshot 2022-06-14 at 12 39 29](https://user-images.githubusercontent.com/17174428/173558795-c4e26f5a-891a-4421-acef-66cc394ce9c2.png)

Doesn't work for quite some phones
![Screenshot 2022-06-14 at 12 40 02](https://user-images.githubusercontent.com/17174428/173558882-10eddd86-ca80-4581-aa3e-12f9996d2763.png)

Does work:
![Screenshot 2022-06-14 at 12 43 16](https://user-images.githubusercontent.com/17174428/173559455-c15ea017-4423-4006-8b96-0371246836c2.png)

Does work:
![Screenshot 2022-06-14 at 12 44 36](https://user-images.githubusercontent.com/17174428/173559683-5169cfc4-0244-450a-8293-7e5c29d9e51a.png)

An other case is the Binance API management qr code key you can scan, in dark mode, the scanner doesn't work.
I hope this is enough info.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.3 => 0.66.3 
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: bare

### Reproducible demo

```js
import React, { useState } from 'react';
import { ActivityIndicator, View } from 'react-native';
import { BarCodeScanner } from 'expo-barcode-scanner';
import { Camera, PermissionStatus } from 'expo-camera';
import { useDidMount } from 'rooks';

const QRCodeScannerComponent: React.FC<Props> = () => {
  const [cameraPermission, setCameraPermission] = useState<PermissionStatus>(
    PermissionStatus.UNDETERMINED,
  );

  useDidMount(async () => {
    const { status } = await Camera.getCameraPermissionsAsync();

    setCameraPermission(status);

    if (status !== PermissionStatus.UNDETERMINED) {
      return;
    }

    const {
      status: requestStatus,
    } = await Camera.requestCameraPermissionsAsync();
    setCameraPermission(requestStatus);
  });

  /**
   * On code scan callback
   */
  const handleRead = (code) => {
      console.log(code.data);
  };

  if (cameraPermission === PermissionStatus.UNDETERMINED) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <ActivityIndicator color='gray' size="large" />
      </View>
    );
  }

  return (
    <View style={{flex: 1}}>
      <Camera
        onBarCodeScanned={handleRead}
        barCodeScannerSettings={{
          barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
        }}
      />
    </View>
  );
};

export default QRCodeScannerComponent;
```

**Comment by brentvatne** [comment]
this looks like it is an issue with google mobile vision, which is what the expo barcode scanner uses on android: https://github.com/googlesamples/android-vision/issues/62
