### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke interface method 'java.lang.Object java.util.SortedSet.last()' on a null object reference with expo-camera and useCamera2Api

### ISSUE THREAD

**Issue by TomCorvus** [expo/expo#17848]
### Summary

Hi 👋
Since I define `useCamera2Api` prop on Camera component, I have crashes on some Android devices.

<img width="1021" alt="Capture d’écran 2022-06-14 à 11 55 06" src="https://user-images.githubusercontent.com/3451011/173549885-b35d1a39-7995-42b8-9d63-4baa95bc4334.png">

Here the list:
- Xiaomi 11 Lite 5G NE (11)
- realme 8 Pro (12)
- Redmi Note 8 (11)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 3.2.1 - /usr/local/bin/yarn
      npm: 8.9.0 - /usr/local/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.5 => 45.0.5 
      react: ^17.0.2 => 17.0.2 
      react-native: ~0.68.2 => 0.68.2 
      react-native-web: ^0.18.0 => 0.18.0 
    npmGlobalPackages:
      eas-cli: 0.8.1
      expo-cli: 5.4.3
    Expo Workflow: bare
```

### Reproducible demo

Hard to provide reproducible demo, but try Camera component with `useCamera2Api` prop with defined devices above.

**Comment by enestatli** [comment]
Hello,

I'd like to reopen the issue regarding the fatal exception that occurs when using expo-camera with useCamera2Api. The issue seems to be related to a NullPointerException when invoking the java.util.SortedSet.last() method on a null object reference.

While the issue was previously closed, I've encountered this problem consistently in my environment and have confirmed that the problem persists. It's causing significant disruptions in my project, and I believe it's crucial to address it to ensure the stability of the module.

Thank you for your dedication to maintaining the quality of the module, and I'm looking forward to collaborating towards a resolution.


**Environment:**
```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/enestatli/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 30, 31, 33, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.12.0
    Expo Workflow: bare
```
