### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by VishalVema** [expo/expo#1784]
I am getting this error when i am trying to setup Expo push notifications 

the screenshot of my error is attached below

the Code that i am using 

`import Expo ,{ Permissions, Notifications } from 'expo';
import { AsyncStorage } from 'react-native';
import axios from 'axios';

const PUSH_ENDPOINT = 'http://rallycoding.herokuapp.com/api/tokens';
export default async () => {
let previousToken = await AsyncStorage.getItem('pushtoken');    
if(previousToken){
    return;
}else{
  let { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);

  if(status !== 'granted'){
      return;
  }

  let token = await Notifications.getExpoPushTokenAsync();

  console.log('token ',token)
  await axios.post(PUSH_ENDPOINT, {token: {token} });
  AsyncStorage.setItem('pushtoken', token)
}
};

`

My app.json File contains this

`{
  "expo": {
    "name": "food-aladdin",
    "description": "This project is really great.",
    "slug": "food-aladdin",
    "privacy": "public",
    "sdkVersion": "27.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}
`

my package.json file contains code below

`{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz"
  }
}
`

![whatsapp image 2018-05-23 at 2 40 45 pm](https://user-images.githubusercontent.com/22855727/40415022-7837bbb4-5e97-11e8-8a3f-560aac721275.jpeg)

**Comment by ccheever** [comment]
I think the root of your problem is that you need to be using `Permissions.NOTIFICATIONS` rather than `Permissions.REMOTE_NOTIFICATIONS`.

Here is a Snack that has mostly your code that kinda works.
https://snack.expo.io/SJGw2r717

**Comment by luklapp** [comment]
@ccheever THANK YOU! It was working in the last releases though – is this a breaking change?
