### ISSUE TITLE
React Native version mismatch - release variant

### ISSUE THREAD

**Issue by ahdam** [expo/expo#17844]
### Summary

When trying to run the app on an **Android** device using **release variant** I get the following error:

```
E/ReactNativeJS: React Native version mismatch.
    
    JavaScript version: 0.57.1
    Native version: 0.67.4
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.18 - ~/apps/tp/mobile-app/node_modules/.bin/yarn
      npm: 6.14.8 - ~/apps/tp/mobile-app/node_modules/.bin/npm
      Watchman: 2022.01.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 26, 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 32.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.4 => 0.67.4 
    npmGlobalPackages:
      expo-cli: 5.4.9
    Expo Workflow: bare

### Reproducible demo

I tried to run the app on a device using **release variant**, because when I try to create a signed APK, the app crashes. 
The same thing happens with the **release variant**

**Debug mode works ok.**

**Comment by brentvatne** [comment]
run `npm why react-native` in your project to learn more about why an old version is installed

**Comment by brentvatne** [comment]
possibly you have another bundler open? or you are using a stale embedded bundle?

either way, this isn't a bug w/ expo so it's better to post to https://forums.expo.dev/ or stackoverflow to get some help debugging

**Comment by ahdam** [comment]
No other bundlers open. I removed all cache using: 

```
rm -rf node_modules 
npm cache clean --force 
npm install 
watchman watch-del-all 
rm -rf $TMPDIR/haste-map-*
rm -rf $TMPDIR/metro-cache
```
