### ISSUE TITLE
Bundle Assets for Expokit SDK 27 not working

### ISSUE THREAD

**Issue by michchan** [expo/expo#1785]
The fonts and images cannot be loaded when the production app is opened,
given that:

- I have used a wildcard assetsBundlePatterns,
- I have noticed hashed file names are added to shell-manifest.json when publishing the app, and
- In my app, image sources are imported using require directly and @expo/vector-icons are used.

This occurs on both Android and iOS.

**Comment by ccheever** [comment]
There is a step you need to run for asset bundling in SDK27. It's described in the release notes here.
https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4

Try that!

**Comment by michchan** [comment]
@ccheever No... I did follow that instruction of course... I said that there are hashed filenames on the shell-manifest.json. I just don’t know why the images and fonts are not loaded. Or may I ask is it related to how to access it? I just use require(‘/path’) to access that.
