### ISSUE TITLE
Expo-facebook and AuthSession Facebook login does not redirect to eas built app

### ISSUE THREAD

**Issue by ibrag474** [expo/expo#17861]
### Summary

After clicking continue on fb login page, white empty page opens up and nothing more happens.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.13 Linux Mint 20.3 (Una)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      npm: 8.12.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    IDEs:
      Android Studio: AI-211.7628.21.2111.8092744
    npmPackages:
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.1
      expo-cli: 5.4.9
    Expo Workflow: managed

### Reproducible demo

To reproduce:
1. Use Android device.
2. Implement facebook login with expo-facebook or AuthSession.
3. Build app with eas.
4. Try to login

**Comment by ibrag474** [comment]
@brentvatne what is missing???

**Comment by godsonisrael** [comment]
I am facing the same issues as well. Can you please post the solution if you found one? Thanks.

**Comment by dembal1990** [comment]
+1
I have a same issue with android standalone app.

**Comment by sumitmaithani123** [comment]
@brentvatne @dembal1990 @godsonisrael  is anybody find solution I have a same issue?
