### ISSUE TITLE
[expo-camera] java.lang.Object java.util.SortedSet.last()

### ISSUE THREAD

**Issue by DCKT** [expo/expo#17868]
### Summary

Hi,

I recreate an issue because [this one has been closed without being resolved](https://github.com/expo/expo/issues/16292), this occures on SDK 44 & 45 has well.
I had a screenshot of the error by a user of my app.

![IMG_20220615_103139](https://user-images.githubusercontent.com/1548421/173787505-d29ddc5d-c90f-47fb-bca4-039caa5ca1cd.jpg)

For the example, you can still use the one from the previous ticket, nothing has changed yet.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-8610242/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-8610242/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.5 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.9
    Expo Workflow: managed

### Reproducible demo

[Here a repo with my camera solution](https://github.com/DCKT/expo-camera-bug) (my original codebase is in ReScript sorry for that)
We didn't manage to reproduce this at my company.

[The main part is located here I guess](https://github.com/DCKT/expo-camera-bug/blob/main/src/Camera.res#L119). I tried a trick seems on another issue with `getAvailablePictureSizesAsync ` but it didn't works.

**Comment by RodrigoAWeber** [comment]
I found a similar problem.

Scenario, every time the component with the Camera lost focus, an empty View is returned:

```
state = {
	ratio: undefined;
}

render() {
	if (!this.props.isFocused) {
		return <View />
	}

	return (
		<Camera 
			onCameraReady={ ... Load Aspect Ratio with `getSupportedRatiosAsync` and save it in the save}
			ratio={this.state.ratio}
			...
		/>
	)
}
```

When gaining focus, the Camera is loaded again, but this time the state already had the ratio value, so the error occurred. The solution in this scenario is to set undefined when you lose focus and leave the screen to load the ratio again in the `onCameraReady` event. Calling the `getSupportedRatiosAsync` function.

**Comment by brentvatne** [comment]
hey all! the provided examples are not minimal reproducible examples. please provide a clonable repository without any extraneous code, using javascript and not rescript

**Comment by efstathiosntonas** [comment]
@RodrigoAWeber Hi, thanks for providing a workaround on this one, can you confirm that the solution is stable after 1 year?

**Comment by RodrigoAWeber** [comment]
@efstathiosntonas  I'm still using the alternative solution in the project.
