### ISSUE TITLE
[v27] iOS App in TestFlight with numeric release-channel crashes

### ISSUE THREAD

**Issue by WillemLabu** [expo/expo#1787]
## Bug Report

It seems that iOS builds that target a `--release-channel` that is an integer cause a crash when installed through TestFlight.

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^27.0.2 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2
```

### Target

- [x] Stand-alone
- [x] iOS
- [x] Android
- [ ] Client
- [ ] ExpoKit

Affected OS
- [x] iOS
- [ ] Android

### Steps to Reproduce

1. `exp publish --release-channel 1`
2. `exp build:ios --release-channel 1`
3. Download the built `ipa`
4. Upload the file to TestFlight using Application Loader
5. Download the app in TestFlight
6. Open the app on an iOS device

### Expected Behaviour

The app should open.

### Actual Behaviour

The splash screen defined in `app.json` is shown, but the app then closes.

### Logs

I did manage to tail the Console logs of a device as the app crashed using XCode. Here are the pertinent out-takes.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 0x1766ab80'
*** First throw call stack:
(0x1b824df7 0x1aa87077 0x1b82a505 0x1b828579 0x1b74d3d8 0x1bedbfa3 0x1be1a8bf 0x1bdcf2d7 0xeea05 0xee507 0xd3163 0xd35ff 0xd2f43 0x1103e1 0xc15bd 0xbf5ed 0xc0fc5 0xc0e67 0xc094b 0xc185b 0x110a21 0x1106dd 0xd335f 0xd2f43 0x1103e1 0xc15bd 0xc0901 0xc5109 0xc4ab9 0x208e85b5 0x209556c7 0x20955661 0x20b5d3c9 0x20b5010b 0x20b670e5 0x1b7e0653 0x1b7e0037 0x1b7de4f1 0x1b72d533 0x1b72d341 0x1cf04bfd 0x2093be27 0x20936551 0x275f7 0x1aef750b)
```

**Comment by terribleben** [comment]
Yeah, looks like we probably need to coerce that value to be a string when we parse your app's manifest JSON.

We'll investigate fixing it on the native side; in the meantime, you can probably avoid this behavior by using a non-numeric release channel name.

**Comment by WillemLabu** [comment]
Yep.

To confirm the solution: Built with `exp build:ios --release-channel v1` and retraced steps 3 - 6 and it loads fine.

**Comment by terribleben** [comment]
Really appreciate the thorough and useful bug report :)

**Comment by WillemLabu** [comment]
🎉
