### ISSUE TITLE
[expo-image-picker] Photo from ImagePicker.requestCameraPermissionsAsync() overwrites some of the image taken with black pixels when iPad orientation is LANDSCAPE_LEFT

### ISSUE THREAD

**Issue by frederikchrlarsen** [expo/expo#17875]
### Summary

When capturing a photo using ImagePicker.requestCameraPermissionsAsync() AND the device is oriented in the "LANDSCAPE_LEFT" orientation, the resulting image is "corrupt" with around half of it being black pixels.

I have only been able to reproduce this on iOS. I reproduced it on:
iOS 15.5 
iOS 15.6,
iOS 16 Beta

In the video demonstration below, you can see that a black bar appears in the image, when it is taken in LANDSCAPE_LEFT. When the image later is recaptured in LANDSCAPE_RIGHT, the black bar disappears:
 
![ezgif-5-4949b27deb](https://user-images.githubusercontent.com/17592802/173845303-e13c6adb-989d-42d4-ad4c-69d247fe24e0.gif)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.1 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@qinspect/image-picker

**Comment by jurica-penjgusic** [comment]
Same issue as here [https://github.com/expo/expo/issues/17847](url)

**Comment by brentvatne** [comment]
expo-image-picker on iOS is a thin wrapper around UIImagePickerController, and so the issue you are experiencing here is most likely a bug in UIKit / iOS. You may be able to find a description of this issue in an existing ticket on Apple's ticketing system: https://openradar.appspot.com/search?query=UIImagePickerController - if not, you could file an issue there. You can work around this by finding another library that implements this functionality or using expo-camera or another camera library to capture the image instead.

**Comment by adclark1** [comment]
I too was seeing a black bar on the bottom of some photos being chosen with launchImageLibraryAsync until I stopped providing a "quality".

**Comment by kuwahub** [comment]
I also use an iOS camera, and the bottom of the photo turns black only when the photo Orientation = 6 (exif).
Both "launchCameraAsync" and "launchImageLibraryAsync" are fired.
NG: sdk45, sdk46
OK: sdk44

"launchImageLibraryAsync" was fixed by removing "quality", but "launchCameraAsync" was not.

It happens only on iOS, Android is fine.

**Comment by reececox** [comment]
There is an issue in expo-image-picker, specifically with UIImage+fixOrientation.swift. Here's a patch to fix it:

```
diff --git a/node_modules/expo-image-picker/ios/UIImage+fixOrientation.swift b/node_modules/expo-image-picker/ios/UIImage+fixOrientation.swift
index bce72e2..0f20760 100644
--- a/node_modules/expo-image-picker/ios/UIImage+fixOrientation.swift
+++ b/node_modules/expo-image-picker/ios/UIImage+fixOrientation.swift
@@ -15,7 +15,7 @@ extension UIImage {
     case .down,
          .downMirrored:
       transform = transform
-        .translatedBy(x: self.size.width, y: self.size.width)
+        .translatedBy(x: self.size.width, y: self.size.height)
         .rotated(by: .pi)
     case .left,
          .leftMirrored:
```

**Comment by JacobJaffe** [comment]
> There is an issue in expo-image-picker, specifically with UIImage+fixOrientation.swift. Here's a patch to fix it:
> 
> ```
> diff --git a/node_modules/expo-image-picker/ios/UIImage+fixOrientation.swift b/node_modules/expo-image-picker/ios/UIImage+fixOrientation.swift
> index bce72e2..0f20760 100644
> --- a/node_modules/expo-image-picker/ios/UIImage+fixOrientation.swift
> +++ b/node_modules/expo-image-picker/ios/UIImage+fixOrientation.swift
> @@ -15,7 +15,7 @@ extension UIImage {
>      case .down,
>           .downMirrored:
>        transform = transform
> -        .translatedBy(x: self.size.width, y: self.size.width)
> +        .translatedBy(x: self.size.width, y: self.size.height)
>          .rotated(by: .pi)
>      case .left,
>           .leftMirrored:
> ```

This works! 
Thank you for finding this, @reececox . I've opened this as a PR:
https://github.com/expo/expo/pull/19185
