### ISSUE TITLE
[expo-web-browser] openAuthSessionAsync redirectURL is not optional

### ISSUE THREAD

**Issue by yvbeek** [expo/expo#17887]
### Summary

According to the [documentation](https://docs.expo.dev/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl-options), the `redirectURL` argument for the `openAuthSessionAsync` function is optional. Unfortunately if we don't pass a `redirectURL` we run into the following error:
```
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Argument at index '1' couldn't be cast to type URL
→ Caused by: Cannot convert 'Optional(<null>)' to URL
```

The TypeScript definition for this function also doesn't mark the argument as optional.

This is causing issues in our project, because the page that we are using will automatically perform the redirect for us, so we wouldn't need a `redirectURL` in our use-case.

What would be the best way to work-around this issue?
Could you please change the code and type definitions so that `redirectURL` is optional?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 6.14.17 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - :snip:/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 28, 29, 30, 31
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Android TV Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Android TV Intel x86 Atom
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.5 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    Expo Workflow: bare

### Reproducible demo

https://snack.expo.dev/@yvbeek/95f003

**Comment by brentvatne** [comment]
@tsapeta - we discussed this a bit on slack and you were planning on looking into it, context here: https://exponent-internal.slack.com/archives/D9YRPTM9T/p1654602094040369
