### ISSUE TITLE
[Sdk 27 detached] - Linking `getInitialURL` does not return full path, and `Linking.parse` returns an `[Object object]` literal

### ISSUE THREAD

**Issue by kadoshms** [expo/expo#1788]
Hey there,

I have two issues with the Linking api in my detached expo app [sdk 27]

First issue:

`Linking.getInitialURL()` returns a partial url.
I used the following link:

`<a href="wxg://path?x=y" />click</a>`

And in the app:

```
        Linking.getInitialURL().then(
            (url) => console.log('my url', url)
        );
```

The result:

![image](https://user-images.githubusercontent.com/5352933/40484882-a8dc0fd0-5f65-11e8-8eaa-12ac0a49d73c.png)

As you can see, the path and params are totally ignored.

Using the provided example:

![image](https://user-images.githubusercontent.com/5352933/40484984-edd7980c-5f65-11e8-8062-1118c2efcf21.png)

The result output:

![image](https://user-images.githubusercontent.com/5352933/40485003-f9206f90-5f65-11e8-85ce-a8ed1da5c692.png)

I guess it has something with the new implementation of the linking API in sdk 27, since I used those features before and they worked fine accept to some other known issues.

Thanks.

**Comment by jesseruder** [comment]
Is this iOS or Android?

**Comment by kadoshms** [comment]
@jesseruder am I still missing details?

**Comment by esamelson** [comment]
Hi @kadoshms - thanks for the report. Are you seeing this in a debug or release build (or both)?

**Comment by kadoshms** [comment]
Hey @esamelson, I saw this in debug

**Comment by esamelson** [comment]
Hi @kadoshms - I'm not able to reproduce this. Are you sure that the app is not running the background when you try to open the link? If it's running in the background, you should get the URL with `Linking.addEventListener(...)` rather than `Linking.getInitialURL()`.

Regarding the `[object Object]` string literal you're getting, could you provide more code (ideally the whole component this is happening in)? I'm not able to repro that either, and having more context would help.

**Comment by onka13** [comment]
Hi @esamelson,

I've same problem about linking. "Linking.getInitialURL" does not return full path.  "Linking.addEventListener" catches the full path  If app is running.

`       
var urlHandler = (url) => {
            console.log('url is: ', url)
}
 Linking.getInitialURL().then(urlHandler).catch(err => console.error('An error occurred', err))
        Linking.addEventListener('url', e => {
            urlHandler(e.url)
        })`

- Close the app. (sure not running)
- click link (myapp://test?param1=a&param2=b)
- app will be opened
- log => url is: myapp://
- click link again (app still running)
- log => url is: myapp://test?param1=a&param2=b

I've test in debug and publish mode in Android.

Environment:
  OS: Windows 10
  Node: 8.5.0
  Yarn: 1.7.0
  npm: 6.0.0

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Android Manifest;

```
< activity
      android:name=".LauncherActivity"
      android:exported="true"
      android:launchMode="singleTask"
      android:screenOrientation="portrait"
      android:theme="@android:style/Theme.Translucent.NoTitleBar">
      <intent-filter>
        <data android:scheme="myapp"/>

        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
      </intent-filter>
    </activity>
```

**Comment by esamelson** [comment]
Hi @onka13 - I think you need to make some modifications to your AndroidManifest file. Could you make it look as follows:

```
<activity
      android:name=".LauncherActivity"
      android:exported="true"
      android:launchMode="singleTask"
      android:screenOrientation="portrait"
      android:theme="@android:style/Theme.Translucent.NoTitleBar">
    </activity>

(...)

    <activity
      android:name=".MainActivity"
      android:launchMode="singleTask"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:theme="@style/Theme.Exponent.Splash"
      android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <data android:scheme="myapp"/>

        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>

        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
```

Basically you need to move the `intent-filter` section you pasted into your message from `LauncherActivity` to `MainActivity`.

Apologies for the trouble. This can sometimes happen when upgrading from an older SDK version, but shouldn't be necessary moving forward. Let me know if that fixes things!

**Comment by onka13** [comment]
Hi @esamelson - Thank you very much. it's working now.
