### ISSUE TITLE
Expo published project overwrite the app in app stores

### ISSUE THREAD

**Issue by 445759567** [expo/expo#17893]
### Summary

I see the version I published using "expo publish" in the app I downloaded from app store. (Have tried both android and iOS)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^44.0.0 => 44.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed

### Reproducible demo

1. Download my app in app store, I can see the correct app content
2. Use "expo publish" to publish a DEV version of app 
3. Open the app again, the app content shows the one I published to expo

Anyone facing this issue??

**Comment by brentvatne** [comment]
hi there! this is exactly what `expo publish` is for, and intended behavior.

learn more about how publishing updates works: https://docs.expo.dev/workflow/publishing/

learn more about how you can use release channels to target specific builds with updates: https://docs.expo.dev/distribution/release-channels/
