### ISSUE TITLE
How to disable expo build-in ads, including Admob and FacebookAds, since that cause warning installing apk. This issue is very important to all chinese!

### ISSUE THREAD

**Issue by OPChips** [expo/expo#1789]
In China, for expo's build-in ads SDK - Admob and FacebookAds, when I install the apk in some appStore, like XiaoMi, the Android system detect the ads and then prompt warning info like finding ads. It have confusing me for long time, then how to disable the ads SDK, or is there any other solution?
![screenshot1 of problem](https://s7.postimg.cc/zd0006rq3/IMG_3207.png)
![screenshot2 of problem](https://s7.postimg.cc/b998c3463/IMG_3208.png)

**Comment by jesseruder** [comment]
For now you would have to detach and manually remove those dependencies. We want to make this more configurable but that probably won't happen for a few months.

**Comment by OPChips** [comment]
@jesseruder My project has ejected, and in ios, using cocoapods to manage dependencies. I am confused that how to remove the ads dependencies relating to many files in ios and android. Can you help me?

**Comment by jesseruder** [comment]
Hi @OPChips, it's the same as any other iOS project. Remove the pod from the Podfile and reinstall.

**Comment by esamelson** [comment]
Hi there, this is now best supported using either the bare workflow or ejecting to ExpoKit and removing the ads libraries. Going to close this issue as it's old and inactive.

**Comment by donni106** [comment]
@esamelson we cannot remove it from being included in managed projects?

**Comment by esamelson** [comment]
@donni106 as of this current moment it is not possible to remove these modules from managed builds. It's in our roadmap for the future to allow more customizable builds in the managed workflow but we don't have an ETA for that yet.
