### ISSUE TITLE
Same deep linking on Dev Client and production app

### ISSUE THREAD

**Issue by CarlosBM18** [expo/expo#17895]
### Summary

We found that when we had a Dev Client and a production version of our app installed on the same device and we try to open the app from the development server, such as with the command `a` for Android, this prompt appears:
![Screenshot 2022-06-16 at 12 41 24](https://user-images.githubusercontent.com/30117015/174290478-8e849ee1-115a-4271-9d81-3d71b8fdca77.png)
.

We saw that both apps share the same `slug` which is `exp+myappslug://...`. So we think that this is causing the problem.

In iOS happens something similar, but instead of the prompt to select one, appears an alert to open the production app.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

`"expo": "^45.0.4",
    "expo-dev-client": "~1.0.0",`

### Environment

` System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.4 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    Expo Workflow: bare`

### Reproducible demo

Install the production app and the Dev Client of your app on the same device. Try to open your app from the development server.

**Comment by brentvatne** [comment]
if you have two different apps using the same uri schemes this is exactly what is expected to happen. if you want to discuss this further and explain what your desired outcome is and how to achieve it, you can head over to https://forums.expo.dev or the discussions tab on this github repo

**Comment by CarlosBM18** [comment]
Hi! Thanks for your response. We've found that `expo-dev-client` adds [this scheme](https://github.com/expo/expo/blob/main/packages/expo-dev-client/plugin/src/getDefaultScheme.ts#L29) for every build of the same app, so the production app and the dev client are sharing the same scheme. And that's probably why this problem is happening to us because both apps have the same scheme which is `exp+projectname`.
