### ISSUE TITLE
EXPO AV - missing constants? (INTERRUPTION_MODE_ANDROID_DUCK_OTHERS and INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS)

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#17908]
### Summary

Previously, before upgrading to the last version of `expo-av` __(~11.2.3)__, I was doing the following in order to configure my audio player:

```javascript
import { Audio } from "expo-av";

export const AUDIO_PLAYER_MODE = {
  allowsRecordingIOS: false,
  interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS,
  interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,
  playsInSilentModeIOS: true,
  playThroughEarpieceAndroid: false,
  shouldDuckAndroid: true,
  staysActiveInBackground: false,
};
```

Now, after the upgrade, `Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS `and `Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS` are `undefined`. Checking the package code, I only found a `RecordingConstants.ts` module, inside `src/Audio/`, and neither `INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS` nor `INTERRUPTION_MODE_ANDROID_DUCK_OTHERS` are defined there.

In the [documentation](https://docs.expo.dev/versions/latest/sdk/audio/#audiosetaudiomodeasyncmode), it seems that the package still need these constants. Any ideas?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

^45.0.0

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.12.1 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed
```

### Reproducible demo

```javascript
import { Audio } from "expo-av";

console.log(Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS);
console.log(Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS);
```

**Comment by VictorioMolina** [comment]
There is a new way to import them:

import {
  Audio,
  /* Inside expo-av/src/Audio.types.ts: */
  InterruptionModeAndroid,
  InterruptionModeIOS,
} from "expo-av";

console.log(InterruptionModeAndroid.DuckOthers);
console.log(InterruptionModeIOS.MixWithOthers);

**Comment by Iranzithierry** [comment]
> ```js
> InterruptionModeIOS
> ```

I'm glad I didn't have to spend two days looking everywhere . I Appreciate 👍

**Comment by DJBurb** [comment]
> There is a new way to import them:
> 
> import {
>   Audio,
>   /* Inside expo-av/src/Audio.types.ts: */
>   InterruptionModeAndroid,
>   InterruptionModeIOS,
> } from "expo-av";
> 
> console.log(InterruptionModeAndroid.DuckOthers);
> console.log(InterruptionModeIOS.MixWithOthers);

This helped a lot
