### ISSUE TITLE
Not working with babel.config.cjs in module type package

### ISSUE THREAD

**Issue by juliushuck** [expo/expo#17907]
### Summary

My expo package has the type module, so I have to rename babel.config.js to babel.config.cjs. But when I do so, the app stops working.

To test it, I use a config to test an import alias with babel. That one works in normal package with the normal babel config, but when I switch to the module package type and rename the config, it stops working. I also tried to rename the babel to .babelrc and that also works in type module, so I guess .cjs should also work.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

45

### Environment

    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.11.1 - /usr/local/opt/nvm/versions/node/v16.11.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.8.0 - /usr/local/opt/nvm/versions/node/v16.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.4.11
    Expo Workflow: managed

### Reproducible demo

https://github.com/juliushuck/issue-expo

Please see the last two commits. Those are the two cases I mentioned.

**Comment by Kudo** [comment]
hi there! it is because metro has [hardcoded filenames](https://github.com/facebook/metro/blob/100ca6ffcc3ab99b82fac87b41be708040be2e9e/packages/metro-react-native-babel-transformer/src/index.js#L75-L97). i found you can still use `babel.config.js` with module package type in this case. hopefully this can help to solve your problem.

**Comment by leandrogtavares** [comment]
The thing is that `loadBabelConfig` does not detect `babel.config.cjs` in `"type": "module"` packages. I suggest that this issue should reopened and 'babel.config.cjs' and 'babel.config.mjs' added to possibleBabelRCPaths [https://github.com/expo/expo/blob/80835cec731ffdbd66d35e8f81bbf69259f595b7/packages/%40expo/metro-config/src/loadBabelConfig.ts#L31](url)
