### ISSUE TITLE
XDE errors bubbling up to React Native Packager, requires restarting, then quitting/reopening iOS simulator

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1791]
### Environment

Currently working on iOS simulator with expo (no expokit).
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/headsuphealth-6d1accc2-e35a-4bd2-98be-13e799508d6e.tar.gz
```

### Steps to Reproduce

Import a file from an incorrect path (possibly other errors will do the same thing)

### Expected Behavior

Before Expo 27 (I didn't notice this issue before), errors appeared in the app console, and after fixing the file reference, reloading the app (`⌘R`) would bring the app back to life. Fixing and saving the error-causing file, then pressing reload, the app should resume work as normal.

### Actual Behavior

Errors bubble up to the React Native Packager, and saving/reloading does nothing. To bring the app back online, I have to restart XDE, quit the simulator, and re-initialize/re-build the app.
<img width="1197" alt="screen shot 2018-05-24 at 12 36 50 pm" src="https://user-images.githubusercontent.com/1566400/40501985-29eeeb36-5f4f-11e8-8ea3-88b51729c6ad.png">

### Reproducible Demo

Let me know if using a wrong path doesn't work, and I'll upload a demo, it's taking forever to download project files over my current wifi network.

**Comment by brentvatne** [comment]
Hi! I was not able to reproduce this. I created a new blank project in XDE, opened it in the iOS simulator, then added:

```
const Lol = require('./assets/icon.png');
import Lol2 from './lol';
```

I then changed the first one to an incorrect path, got red screen, changed back and it worked. Did the same with the second one. Reloaded as expected.

Additionally, I'm not sure I understand what you mean by "bubbling up" in this case. Could you elaborate further and provide a reproducible demo? Thanks!

**Comment by JulianKingman** [comment]
I think I can close this issue. By "bubbling up", I mean that it shows up in the React Native Packager, which I don't think it used to do (used to just show up on the right side). Anyway, in an empty repo with a bad import, it reloads as expected when fixed, as you said. Perhaps my issue is a result of the complexity of my app... I'll play around with it a bit more, and close this for now as I can't reproduce it reliably.
