### ISSUE TITLE
[iOS] expo-notifications addNotificationReceivedListener not working

### ISSUE THREAD

**Issue by vadimluminous** [expo/expo#17920]
### Summary

I am having issues on my main project with expo-notifications.

So I created a blank project with the expo init command, created a managed workflow, and installed expo notifications via expo install.

That's all I did to the app, and then I copied the App.tsx file from the documentation over.

I then ran expo build to automatically generate the APN certificiates and after that ran the app.

I think this is as minimal reproducible demo as could be.

My issue: 

Running the curl command

```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]",
  "title":"hello",
  "body": "world"
}'
```

With the app in background. I get a notification fine. But the addNotificatioNReceivedListener() or the addNotificationResponseReceivedListener() don't fire. I get no response from their console logs.

I also do not get push notifications when app is in the foreground. Even using the documentations "Press to schedule a notification" button.

Anyone have any insight?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.1
      expo-cli: 5.4.9
    Expo Workflow: managed

### Reproducible demo

https://github.com/luminoustec/expo-notifications-test

**Comment by adscud** [comment]
> I also do not get push notifications when app is in the foreground. Even using the documentations "Press to schedule a notification" button.

Have you set the notification handler ?

```
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

```

**Comment by vadimluminous** [comment]
After days of debugging - I noticed that the listeners work as expected when expo debug mode is OFF. I always have it on so I never checked this. 

Though it kinda solves my problem, it makes it harder to debug or see console logs without having Debug Mode on.

**Comment by brentvatne** [comment]
@vadimluminous - that's odd, this shouldn't make a difference. are you sure that is all that changed between this working/not working in your app?

**Comment by S4NDSTROM** [comment]
I'm experiencing the same issue, turning off debug mode makes everything work as expected.

**Comment by m0hanraj** [comment]
I'm facing similar issue with Android setup. `addNotificationResponseReceivedListener` is not triggered if the app is not in the background. Is there a fix available for this issue?

**Comment by lgrube3** [comment]
> expo debug mode

How do I disable debug mode? These listeners aren't working on iOS but working fine on Android. SDK 51

**Comment by rennard** [comment]
me too, my notifications were working fine on SDK 50, they seem to have since broken on both platforms. Ended up upgrading to SDK 51 and Android started working, but iOS the listener isn't being called
