### ISSUE TITLE
Client always receives PushMessage data property as an empty object

### ISSUE THREAD

**Issue by rmushtaq21** [expo/expo#1792]
I receive a data object when I send a push notification from Expo's Push Notification Tool. However, when I try to send data in a push notification from the server, using the PushMessage class, I always receive data as an empty object. Has anyone else experienced this issue?

This is what my data object looks like:
```
PushClient().publish(
      PushMessage(to="ExponentPushToken[xxxx]",
                              body="Notification body",
                              title='Title',
                              data={
                                  "type": "reminder",
                                  "payload": {
                                       "user_Id": "1",
                                   }
                              })
                        )
```

—
This is the what I receive when I send a push notification using the Expo Push Notification Tool:
```
{"data": Object {
     "payload": Object {
          "user_Id": "1",
      },
     "type": "reminder",
  },
     "origin": "selected",
     "remote": true,
}
```

—
This is the what I receive when I send a push notification from my server:
```
Object {
    "data": Object {},
    "origin": "selected",
    "remote": true,
}
```

Please halp! Thanks a bunch in advance! 🙏

**Comment by brentvatne** [comment]
hi! this might be an issue with the python sdk. cc @ide

**Comment by ide** [comment]
This is most likely an issue with the server SDK you are using since the web push notification tool calls just the HTTP/2 API. The Expo team actively maintains only the Node SDK so I recommend you debug the issue to figure out why your Python code is behaving differently.
