### ISSUE TITLE
Suggestion: sending the URL link to nearby devices via Bluetooth

### ISSUE THREAD

**Issue by xareelee** [expo/expo#1793]
## Suggestion

I hope that the RN bundler server on the dev computer can send the link to nearby physical devices via Bluetooth without scanning QRCode or sending URL.

## Explanation 

I have multiple physical devices (iOS and Android) for development. Launching them manually is redundant work. 

I think the best way to launch those devices in Expo:

1. Start a Expo server (RN bundler server) and open Expo.app in all devices
2. Execute a command (e.g. `exp broadcast`) on the computer to broadcast or sync to those devices to send the URL address for loading via Bluetooth or any other tech.
    * The device may listen to the iBeacon signal and send a local notification if the Expo.app is not in the foreground to launch the Expo.app easily.
3. All devices automatically load the js bundle for the URL link without any further ado.

Whitelist to avoid causing chaos in the office:

* The Expo server can set up a whitelist for valid devices to communicate with, or
* The device can set up a whitelist for valid Expo servers to listen to.

Applicable scenarios:

* A developer when developing with multiple devices
* A dev team in the same office wants to see the progress
* A meetup or a small tech talk to present the App to attendees quickly in a live demo

**Comment by jesseruder** [comment]
Hi! Can you open up a feature request here: https://expo.canny.io/feature-requests?

**Comment by xareelee** [comment]
Done :)
https://expo.canny.io/feature-requests/p/sending-the-url-link-to-nearby-devices-via-bluetooth

**Comment by jesseruder** [comment]
Thanks :) Going to close this and use the canny post to track this
