### ISSUE TITLE
expo-local-authentication authenticateAsync raises console.warning when device fallback is disabled

### ISSUE THREAD

**Issue by andresjesse** [expo/expo#17945]
### Summary

Using authenticateAsync with cancelLabel and no device fallback, expo raises a console.warn when user clicks "Cancel" button. The warn is always the same text provided in cancelLabel prop.

```
    const result = await authenticateAsync({
      cancelLabel: "Cancel",
      disableDeviceFallback: true,
});
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45.0.0

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.17 Pop!_OS 22.04 LTS
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.4.7
    Expo Workflow: managed

### Reproducible demo

```
import { useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import {
  authenticateAsync,
  hasHardwareAsync,
  isEnrolledAsync,
} from "expo-local-authentication";

import { Button } from "react-native";

export default function App() {
  const [isCompatible, setIsCompatible] = useState(false);
  const [isEnrolled, setIsEnrolled] = useState(false);
  const [isAuth, setIsAuth] = useState(false);

  const intialize = async () => {
    setIsCompatible(await hasHardwareAsync());
    setIsEnrolled(await isEnrolledAsync());
  };

  const authorize = async () => {
    // device is not compatible or user has not registered biometrics
    if (!isCompatible || !isEnrolled) return false;

    // check for auth
    const result = await authenticateAsync({
      cancelLabel: "Cancel",
      disableDeviceFallback: true,
    });

    setIsAuth(result.success);

    return result.success;
  };

  useEffect(() => {
    intialize();
  }, []);

  return (
    <View>
      <Button title="auth" onPress={authorize} />
    </View>
  );
}
```

**Comment by brentvatne** [comment]
if the authentication method returns a warning it is logged here: https://github.com/expo/expo/blob/eeaffceff33751bb395b47dcd9662ac5e2efa976/packages/expo-local-authentication/src/LocalAuthentication.ts#L97-L99

if you'd like to propose changing this, please open a PR or [discussion](https://github.com/expo/expo/discussions)
