### ISSUE TITLE
 import modules !

### ISSUE THREAD

**Issue by desenvolvedorIcotrade** [expo/expo#17949]
### Summary

ex:

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

skd

### Environment

``web

### Reproducible demo

**javascript**

**Comment by DevCleverton** [comment]
You can import modules from it in your JavaScript code as follows:
"import { Camera } from 'expo-camera';
import * as Contacts from 'expo-contacts';
import { Gyroscope } from 'expo-sensors'; "

**Comment by desenvolvedorIcotrade** [comment]
API Reference ok!
