### ISSUE TITLE
Expo go crashing when using FileSystem.FileSystemUploadType.MULTIPART,

### ISSUE THREAD

**Issue by Zakisb** [expo/expo#17947]
### Summary

So i'm trying to upload an image using the expo file-system library. The code works seamlessly on android simulator. the image gets successfully uploaded to my backend server ( node.js ). but as soon as i submit a request using ios simulator the app crashes without an error. 

![Screen Shot 2022-06-22 at 6 20 31 PM](https://user-images.githubusercontent.com/28612240/175098943-0c9fefee-6000-447a-8d51-4d632eb896f2.png)

Please note that whenever i remove the : uploadType: FileSystem.FileSystemUploadType.MULTIPART, i click the submit button the app doesn't crash but the file doesn't get uploaded. so i need that part for my code to work properly. is it a problem with expo or me? 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

"expo": "~44.0.0",

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.14 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

```js
import * as FileSystem from "expo-file-system";

const handleSubmit = async (listing, { resetForm }) => {

const response = await FileSystem.uploadAsync(
      "http://192.168.43.8:5000/products/addProduct",
      listing.images[0],
      {
        fieldName: "images",
       // works on android but on ios simulator the expo app crashes 
        uploadType: FileSystem.FileSystemUploadType.MULTIPART,
      }
    );

}
```

**Comment by barthap** [comment]
Sorry, couldn't reproduce it using your code. Tried this Snack: https://snack.expo.dev/@barthap10/filesystem-upload
My iOS Expo Go works correctly.

Could you please provide a (preferably Snack) app code example which causes Expo Go to crash?

**Comment by Zakisb** [comment]
Hey, thank you for replying. it seems like the problem was my app. i did create another app and everything worked perfectly, so i think maybe the packages i did add to my app did cause the issue. thank you for responding !
