### ISSUE TITLE
Build:ios gives me error while gathering & validating credentials. Unknown reason

### ISSUE THREAD

**Issue by Cronnay** [expo/expo#1795]
### Environment

  OS: macOS High Sierra 10.13.4
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Standalone for iOS
### Steps to Reproduce

1. exp build:ios
2. Selects "Expo handles all credentials, you can still provide overrides"
3. Writes apple id and password, and then crash

### Expected Behavior

It should build the file?

### Actual Behavior

My error message with EXPO_DEBUG=true:
20:37:23 [exp] Validating Credentials...
20:37:24 [exp] Error while gathering & validating credentials
20:37:24 [exp] Reason:Unknown reason, raw:"{\"authType\"=>\"sa\"}\naa=08894A44DD056FD15E9C04458A953437; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly, acn01=rlzulwLT8ofMM6BQiXxy5wVog7ash+lNrNIWK6oAEa0e7dYllw==; Max-Age=31536000; Expires=Sat, 25-May-2019 18:37:24 GMT; Domain=apple.com; Path=/; Secure; HttpOnly"

I've tried using my own certificates, but it gives me the same error. I've used sudo as well in case, but it doesn't work.

**Comment by jesseruder** [comment]
Hi! Can you successfully log into the Apple developer site? Some people have hit this issue because they need to sign the new privacy agreement. Also make sure that you are on the latest version of `exp`.

**Comment by Cronnay** [comment]
Yes, I can log in into my account, and create certificates and similar. It also says "Program Type: Apple Developer Program" on my profile. However, my role is "Agent". could this been an issue?

I updated exp and tried to build again with the same result

**Comment by ambewas** [comment]
can confirm, am having the same issue, with the same error message.

**Comment by jitingambhir** [comment]
I am also facing the same issue, any success on this?

09:03:36 [exp] Validating Credentials...
09:03:38 [exp] Error while gathering & validating credentials
09:03:38 [exp] Reason:Unknown reason, raw:"{\"authType\"=>\"sa\"}\naa=6EE939D6B9873B337A99AE7E4F6056F1; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly, acn01=mWsTkrslmwShN3sdI8ofPOWZ2HjzzY5h6gASQyDuck7j; Max-Age=31536000; Expires=Tue, 28-May-2019 03:33:38 GMT; Domain=apple.com; Path=/; Secure; HttpOnly"
09:03:38 [exp] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by dsokal** [comment]
@Cronnay @ambewas @jitingambhir 
```{"authType"=>"sa"}``` which you can find in logs you posted here is caused by not accepting new privacy agreement. Please manually log into https://appleid.apple.com (or https://itunesconnect.apple.com) to acknowledge the statement.

**Comment by emrahyurttutan** [comment]
Developer.apple.com => Certificates, Identifiers, and Profiles => iOS Provisioning Profiles  check the status of the app in the app store, if it is not active, delete and re-exp build:ios run the ios command
