### ISSUE TITLE
Migrating sdk 44 -> 45 android build failure (expo-dev-launcher)

### ISSUE THREAD

**Issue by kpbochenek** [expo/expo#17952]
### Summary

My app was built correctly using sdk 44, when decided to update to 45 it started to fail with exception below. Only changes I made after automatic migration(expo update) were related to `autoCompleteType` for Input which I assume are not related.
Failure is in setp 'Run gradlew' 

```
> Task :expo-dev-launcher:compileReleaseKotlin FAILED
[stderr] 
e: /home/expo/workingdir/build/apps/portal/node_modules/expo-dev-launcher/android/src/react-native-67/expo/modules/devlauncher/rncompatibility/DevLauncherReactNativeHostHandler.kt: (16, 3): 'getDevSupportManagerFactory' overrides nothing
[stderr] 
e: /home/expo/workingdir/build/apps/portal/node_modules/expo-dev-launcher/android/src/react-native-67/expo/modules/devlauncher/rncompatibility/DevLauncherReactNativeHostHandler.kt: (20, 3): 'getUseDeveloperSupport' overrides nothing
[stderr] 
e: /home/expo/workingdir/build/apps/portal/node_modules/expo-dev-launcher/android/src/react-native-67/expo/modules/devlauncher/rncompatibility/DevLauncherReactNativeHostHandler.kt: (24, 3): 'getJavaScriptExecutorFactory' overrides nothing
```

```
FAILURE: Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':expo-dev-launcher:compileReleaseKotlin'.
[stderr] 
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
[stderr] 
   > Compilation error. See log for more details
```

expo wants to use RN 68 but it links to directory react-native-67, but 68 directory version doesn't exist so it is compatible I guess?

If I can provide any additional information / logs let me know, migration was super smooth up till point and I would be super happy to be able to be using latest version

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

    npmPackages:
      @expo/webpack-config: ~0.16.21 => 0.16.24
      expo: ^45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      expo-cli: 5.4.11
    Expo Workflow: managed

### Reproducible demo

Unable to produce one :/

**Comment by brentvatne** [comment]
likely the same dependency issue in your project as #17951
