### ISSUE TITLE
EXPO + react-native-reanimated remote debug issue

### ISSUE THREAD

**Issue by jekcom** [expo/expo#17957]
### Summary

I've had an app running on Expo SDK 41 and it had some basic usage of react-native-reanimated@~2.1.0 and debugging worked just fine.
At some stage SDK 41 was deprecated and I was forced to upgrade, so I went for the latest one which is 45.
After the upgrade I can no longer use remote debugging. When I turn on remote debugging, the app crashes and I can't do anything (I can't even turn off remote debugging without clearing expo app data).

This can be reproduced by just creating new app and adding react-native-reanimated

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 31.0.0
        System Images: android-27 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    Expo Workflow: managed
```

### Reproducible demo

Just create new app `expo init my-app`
run `yarn add react-native-reanimated`

babel.config.js
```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin']
  };
};
```

App.js

```
import { Text } from 'react-native';
import Animated from 'react-native-reanimated';


export default function App() {
  return (
    <Animated.View>
      <Text>Test</Text>
    </Animated.View>
  );
}
```
Turn on Remote Debug

Observe error thrown:
```
Requiring module "node_modules\react-native-reanimated\src\Animated.js", which threw an exception: Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.
```
![TefnI](https://user-images.githubusercontent.com/4057992/175343861-15a9886d-54b9-4a16-9142-1505064001ef.png)

**Comment by bradjones1** [comment]
See [this note on the reanimated docs](https://docs.expo.dev/versions/latest/sdk/reanimated/):

> The new APIs in react-native-reanimated@2 use React Native APIs that are incompatible with Remote JS Debugging. Consequently, you can only debug apps using these APIs using Flipper, which is not yet available in the Expo managed workflow. You will be unable to use Remote JS Debugging if you use the new APIs from Reanimated 2. Remote JS Debugging will continue to work if you only use the APIs that were also available in Reanimated 1.

**Comment by jekcom** [comment]
@bradjones1 I saw this note, however before the upgrade to sdk 45, debug was working perfectly with sdk 41 and react-native-reanimated@~2.1.0 and I'm pretty sure im not using anything from Reanimated 2. Look at the reproduce steps there is literally nothing except <Animated.View>

It just seems a bit ridiculous, that i'm forced to upgrade sdk (as the expo go app does not support 41) and as a result i can't debug anymore? 

How can you develop complex app without debug ability?

**Comment by bradjones1** [comment]
> How can you develop complex app without debug ability?

I've enabled Hermes engine and am using Flipper with Hermes debugging... honestly it's superior to Remote JS in that the code runs on the device instead of in a browser over the network. Not perfect by any means (I found your issue while logging some others relating to debugging) but yeah. :-)

**Comment by OneHatRepo** [comment]
I'm running into this too this morning. Debugging on Android with SDK 45 doesn't work.

**Comment by brentvatne** [comment]
hi there! this is unfortunate and inconvenient for sure. it's a side effect of the direction the ecosystem is moving in - away from JavaScript Core and remote debugging in Chrome towards Hermes and attaching a debugger to the on-device Hermes engine. Reanimated no longer supports remote debugging in Chrome.

in order to debug JS using Reanimated in SDK 45+ we recommend using Hermes. you can set this up in your app.json as follows:

```json
{
  "expo": {
    "// your other config here": "...",
    "android": {
      "jsEngine": "hermes"
    }
  }
}

```

now when you run `expo start` and launch your app press `j` and it will launch a Chrome Inspector that will attach directly to the app on your device (I suggest upgrading expo-cli to the latest to ensure you have this feature). be sure to refer to the ["Using Hermes Engine"](https://docs.expo.dev/guides/using-hermes/) guide for more information

**Comment by brentvatne** [comment]
i have updated the reanimated documentation page to clarify this and make it prominently displayed at the top of the page: https://github.com/expo/expo/commit/3a23ae91a0b7cda9c11e25cffa72e01cc6916612
