### ISSUE TITLE
Upgrading sdk 44 -> 45 WebBrowser stops compiling (iOS)

### ISSUE THREAD

**Issue by kpbochenek** [expo/expo#17951]
### Summary

My project worked correctly on sdk 44 then tried to upgrade to 45 and during native iOS build on expo.dev I encountered mentioned exception. Only things I changed after migration were 'autoCompleteType' for Input but it should not be related to this error I think.
Expo doctor is green only says that expected `expo-modules-autolinking@~0.8.1` but got `0.5.5` 

Running my iOS build on expo.dev I get error on step 'Run fastlane'

```
› Packaging react-native-screens Pods/RNScreens » libRNScreens.a

❌  (node_modules/expo-web-browser/ios/WebBrowserExceptions.swift:6:16)

  4 | 
  5 | final class WebBrowserAlreadyOpenException: Exception {
> 6 |   override var reason: String {
    |                ^ property does not override any property from its superclass
  7 |     "Another web browser is already open"
  8 |   }
  9 | }

❌  (node_modules/expo-web-browser/ios/WebBrowserExceptions.swift:5:45)

  3 | import ExpoModulesCore
  4 | 
> 5 | final class WebBrowserAlreadyOpenException: Exception {
    |                                             ^ cannot find type 'Exception' in scope
  6 |   override var reason: String {
  7 |     "Another web browser is already open"
  8 |   }
  ...
```

```
The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'expo-dev-menu' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoWebBrowser' from project 'Pods')
	CompileSwift normal arm64 (in target 'ExpoWebBrowser' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoSystemUI' from project 'Pods')
(4 failures)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.205.2                 |
| sdk         | iPhoneOS15.4.sdk        |
+-------------+-------------------------+
```

I can see this file defined here:
https://github.com/expo/expo/blob/59836aab8caace709414516068cca24ccbbed41e/packages/expo-web-browser/ios/WebBrowserExceptions.swift

 It doesn't look like anyhing else is problematic in logs but I can provide additional logs/information if it could be helpful to find out what is wrong :/

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

   npmPackages:
      @expo/webpack-config: ~0.16.21 => 0.16.24
      expo: ^45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      expo-cli: 5.4.11
    Expo Workflow: managed

### Reproducible demo

Unable to provide reproducible demo :/

**Comment by barthap** [comment]
> Expo doctor is green only says that expected expo-modules-autolinking@~0.8.1 but got 0.5.5

That's not good :/ Can you check which versions of `expo`, `expo-modules-core` and `expo-modules-autolinking` do you have? Outputs of these commands:
```
yarn why expo
yarn why expo-modules-core
yarn why expo-modules-autolinking
```

My suspicion is that you have old version of `expo-modules-core` and this is why it not compiles

**Comment by kpbochenek** [comment]
now expo fails with:
```
Cannot find module 'apollo-link'
Require stack:
node_modules/@expo/dev-tools/node_modules/graphql-tools/dist/stitching/linkToFetcher.js
node_modules/@expo/dev-tools/node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.js
node_modules/@expo/dev-tools/node_modules/graphql-tools/dist/stitching/index.js
node_modules/@expo/dev-tools/node_modules/graphql-tools/dist/index.js
node_modules/@expo/dev-tools/build/server/graphql/GraphQLSchema.js
node_modules/@expo/dev-tools/build/server/DevToolsServer.js
node_modules/@expo/dev-tools/build/server/index.js
node_modules/expo-cli/build/commands/start/openDevTools.js
node_modules/expo-cli/build/commands/start/startAsync.js
node_modules/expo-cli/build/commands/start.js
node_modules/expo-cli/build/commands/index.js
node_modules/expo-cli/build/exp.js
node_modules/expo-cli/bin/expo.js
```

`expo start --web` is a problematic command so right now it even fails on web.

so `eas-cli` also is not compatible with SDK 45? 

as 'expo/match-media' doesn't support SDK 45 it is not really an option to migrate to SDK 45 if I use this in my code right?

**Comment by barthap** [comment]
> so `eas-cli` also is not compatible with SDK 45?

It is, but it should be installed globally rather than in your project directory: https://docs.expo.dev/build/setup/#1-install-the-latest-eas-cli

```
yarn remove eas-cli
npm install -g eas-cli
```

> as 'expo/match-media' doesn't support SDK 45 it is not really an option to migrate to SDK 45 if I use this in my code right?

after a quick look at its code, it should work with SDK 45, the only problem is the outdated dependency versions (as mentioned in the issue I linked). This is why I suggested [forcing their version with `resolutions` in `package.json`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)
