### ISSUE TITLE
[expo-notifications] SDK 45 Multiple app instances after open from notifications

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#17960]
### Summary

Hi, I upgraded from expo SDK 43 to SDK 45 and when I open my app from a notification, the app is initialized in a new instance, so after for example open 5 notifications, when I go to the multitask to switch between apps I see that my app was opened 5 times.

I tested on Android 8.1, 11 y 12, and this only happens on Android 12, the other versions works perfectly.

I tried to create a repro demo for several hours, but I couldn't reproduce it. I don't know why.

Anyone know what could be happening?

I'm in the bare workflow and I'm using:
```
expo: 45.0.6
expo-notifications: 0.15.3
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.6 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    npmGlobalPackages:
      eas-cli: 0.22.0
      expo-cli: 5.4.11
    Expo Workflow: bare
```

### Reproducible demo

I was not able to create a reproducible demo, sorry :(

**Comment by RodolfoGS** [comment]
I fixed, I leave this here to someone with the same issue:

Just change **singleTop** by **singleTask** in `AndroidManifest.xml` in the property `android:launchMode`
Like:

```
<activity android:name=".MainActivity"...   android:launchMode="singleTask">
```

> An activity with the "standard" or "singleTop" launch mode can be instantiated multiple times. In contrast, "singleTask" and "singleInstance" activities can only begin a task. They are always at the root of the activity stack. Moreover, the device can hold only one instance of the activity at a time — only one such task.

Source: https://stackoverflow.com/a/6815496
And: https://developer.android.com/guide/topics/manifest/activity-element.html

**Comment by Kudo** [comment]
the fix in https://github.com/expo/expo/issues/17966#issuecomment-1166433085 should also address this issue 😅
