### ISSUE TITLE
[expo-image-picker] Width and height of taken image reversed on some devices

### ISSUE THREAD

**Issue by mfkrause** [expo/expo#17965]
### Summary

On some Android devices, the width and height of a taken photo using `launchCameraAsync` from ImagePicker seem to be reversed. I have noticed this specifically on a Samsung Galaxy S9.

When taking the photo on that device, the result from `launchCameraAsync` says that the width is 4032px and the height 3024px. However, in reality, it's the other way around: The image is higher than it is wide, so it should actually be 3024x4032px, not 4032x3024px.

This becomes especially problematic when post-processing this image using something like the crop action of ImageManipulator. I've experienced unhandled crashes from this library where the crop was out of the image boundaries because I'm calculating the crop based on the image width and height. Interestingly, the result from `manipulateAsync` from ImageManipulator has the correct width and height. This even works with an empty action array in `manipulateAsync`. To clarify, take this as an example:
```
const result = await ImagePicker.launchCameraAsync({
  mediaTypes: ImagePicker.MediaTypeOptions.Images,
  allowsEditing: false,
  quality: 1,
});

// result: { width: 4032, height: 3024 }

const manipResult = await ImageManipulator.manipulateAsync(
  result.uri,
  [],
);

// manipResult: { width: 3024, height: 4032 }
```

For anyone experiencing a problem like this: This is also how I've "fixed" the cropping issue for me. I'm simply "manipulating" the image using an empty action array first, then do the actual manipulation actions in a second `manipulateAsync` call after that using the result from the first call.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.6

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.51.0
      expo-cli: 5.3.0
    Expo Workflow: managed
```

### Reproducible demo

1. Get a Galaxy S9. Interestingly, on BrowserStack, I did not experience any problems. Only on a physical device. I might have messed up something in the test environment while testing w/ BrowserStack though. It's possible this bug occurs on other devices, too, however I haven't found any so far. My other Android test devices work fine.
2. Start up a new Expo project and install `expo-image-picker`.
3. Launch the camera with `ImagePicker.launchCameryAsync()` and log the awaited result.

**Comment by brentvatne** [comment]
please try to reproduce this on sdk 45, we migrated to a different image picker library in that release. in general when reporting bugs it's best to try to reproduce the issue against the latest version of the library

**Comment by mfkrause** [comment]
> please try to reproduce this on sdk 45, we migrated to a different image picker library in that release. in general when reporting bugs it's best to try to reproduce the issue against the latest version of the library

Sorry about that, missed this release somehow. Just upgraded to SDK 45. Still an issue with the new native image picker, though. Here's the code snippet directly from our codebase:
```
const result = await ImagePicker.launchCameraAsync({
  mediaTypes: ImagePicker.MediaTypeOptions.Images,
  allowsEditing: false,
  aspect: [1, 1],
  quality: 1,
});

if (!result.cancelled) {
  console.log(`${result.width}x${result.height}px`);
  let manipResult = await ImageManipulator.manipulateAsync(
    result.uri,
    [],
  );
  console.log(`${manipResult.width}x${manipResult.height}px`);
  ...
}
```

Output:
```
4032x3024px
3024x4032px
```

With the second one being correct.

New `npx expo-env-info` output:
```
 expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.12
    Expo Workflow: managed
```

**Comment by jurica-penjgusic** [comment]
https://github.com/expo/expo/issues/17875
https://github.com/expo/expo/issues/17847

**Comment by KevinZonda** [comment]
iOS has no such issue, only Android devices affected

**Comment by jlmart88** [comment]
Also affected by this on Expo 45; the fix mentioned in the issue does work for me

**Comment by qwertypomy** [comment]
It's still an issue

**Comment by Enieste** [comment]
it's also an issue on ios

**Comment by uplne** [comment]
Still there

**Comment by YZahringer** [comment]
the issue persist in Expo 51
