### ISSUE TITLE
[expo-notifications] SDK 45 addNotificationResponseReceivedListener always return the latest notification received

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#17966]
### Summary

On bare workflow and **ONLY on Android 12** when you tap a notification `Notifications.addNotificationResponseReceivedListener` always return the latest notification received, not the notification tapped.

I tested this on Android 8.1 and works as expected, seems that it's a bug only on **Android 12**.

I created a demo using `scheduleNotificationAsync`, but the same happens when you send notifications throw FCM.

```
expo: 45.0.6
expo-notifications: 0.15.3
```

**Demo:**
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/870365/175617831-6c48e3fc-9def-4b26-982b-4429f5f7c8b2.gif)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.22.0
      expo-cli: 5.4.11
    Expo Workflow: bare
```

### Reproducible demo

It's super easy to reproduce, just make sure that you test it on a device with **Android 12** (I'm using a Google Pixed 4a)

1. `expo init expo-push-issue`
2. select `Bare workflow -> minimal`
3. `cd expo-push-issue`
4. `expo install expo-notifications`
5. Copy code of App.js from here https://github.com/RodolfoGS/expo-push-issue/blob/main/App.js
6. `npm run android`
7. Tap **press to send notification** button 3 times
8. Open the notification with the title **Test notification number 1**
9. You'll see an alert with the title of the last notification sent

If you prefer I created a repo with the previous steps: https://github.com/RodolfoGS/expo-push-issue
1. `git clone git@github.com:RodolfoGS/expo-push-issue.git`
2. `cd expo-push-issue`
3. `npm run android`
4. Tap **press to send notification** button 3 times
5. Open the notification with the title **Test notification number 1**
6. You'll see an alert with the title of the last notification sent

**Comment by Kudo** [comment]
hi there! it's a known issue as https://github.com/expo/expo/issues/17531#issuecomment-1160495971. i'll try to deal with it these two days. thanks for the great repro example.

**Comment by Kudo** [comment]
the notification intents are little complicated and i'm not very confident of my fix. could you help to very the fix (https://gist.github.com/Kudo/b8d6a7e75d951fa6652fe255c2068bd0) by patch-packages if you get a chance? thanks!

**Comment by Kudo** [comment]
hi there! we just publish `expo-notifications@0.15.4` to address the issue. hopefully this one fixes all the issues. thanks!
