### ISSUE TITLE
Compatibility RN 0.69 - use invalid configuration

### ISSUE THREAD

**Issue by GaelCO** [expo/expo#17975]
### Summary

Expo 45 seems to be not compatible with RN 0.69.
Indeed, I can't compile after upgrade to RN 0.69, because expo uses an invalid configuration

A warn appears in log :
`Package expo has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed`

But, on android, that lead to some errors : 
```
MainApplication.java:26: error: package expo.modules.constants does not exist
import expo.modules.constants.ConstantsPackage;
MainApplication.java:27: error: package expo.modules.permissions does not exist
import expo.modules.permissions.PermissionsPackage;
.....
```

I haven't tested for ios, but there are chances to have the same type of problem

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45.0.6

### Environment

System:
      OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/Dev/samsic-emploi-reactnative/node_modules/.bin/yarn
      npm: 8.8.0 - /usr/local/bin/npm
    npmPackages:
      babel-preset-expo: 9.1.0 => 9.1.0 
      expo: ~45.0.6 => 45.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.69.0 => 0.69.0 
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: bare

### Reproducible demo

Just upgrade to RN 0.69

**Comment by Simek** [comment]
Every SDK version has the recommended React Native version which should be used with it:
* https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a

We do not recommend using newer version than listed in table, since the this can lead to unexpected problems.

Just FYI, we plan to add React Native 0.69 support officially in the next SDK release (46), the initial PR has landed just a few days ago.

**Comment by GaelCO** [comment]
Thanks for the answer. 
I'm agree, it's not really a bug, because rn 0.69 is not supposed to be supported yet.
I just wanted to have information and a follow-up on the support of the new RN version

**Comment by Kudo** [comment]
as Simek mentioned, we are working on it and planning to support from next sdk. thanks!

**Comment by karatekid430** [comment]
How can we install Expo 46 then as a prerelease? We have dependencies forcing us to upgrade to latest react-native

**Comment by mjziolko** [comment]
@Kudo With `react-native@0.69.1` support merged to `main`, is there a timeline where we can expect a `46.0.0-beta.0/1` or `46.0.0-alpha.0/1`?

Given the changes within `react-native@0.69` and `react@18`, I'm sure many would love the opportunity to test their apps with these updates.  Are there any milestones that you're waiting on before cutting a beta/alpha release?  Would love to help get this through in any way, if needed!

**Comment by mjziolko** [comment]
Noticed that there's now alpha releases of 46 on npm.

Thanks guys!
