### ISSUE TITLE
[SDK27] launchImageLibraryAsync DOES NOT work on expo client 2.5.9

### ISSUE THREAD

**Issue by SimoneLSK** [expo/expo#1797]
Hello Expo Team, 

the ImagePicker.launchImageLibraryAsync doesn't work after updated the expo client to 2.5.9, even Permission === 'granted' 

Thanks

**Comment by phorque** [comment]
What do you mean by "DOES NOT work"? Some of my users are reporting app crashes with `ImagePicker.launchImageLibraryAsync` but I have a hard time investigating.

**Comment by wishfulthinkerme** [comment]
Well, I am not sure if I've got the same issue. My case is that, it worked correctly, and when I did some very minor changes yesterday ( not related to ImagePicker ), pushed the new app version, it stopped working. I've got Permissions, but nothing happen. Works correctly locally in expo client, but not after `exp build:ios or android`.

Both `launchCameraAsync` and `launchImageLibraryAsync` stopped working.

**Comment by SimoneLSK** [comment]
@phorque  
sorry for the late reply, what I have now is the"Album Flat list"  didnt pop-up after executed `launchImageLibraryAsync` in latest version of expo client and didnt catch any error.


`        let { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
        if (status !== 'granted') {
            return;
        }

        try{
            let result = await ImagePicker.launchImageLibraryAsync({
                mediaTypes: ImagePicker.MediaTypeOptions.Images,
                allowsEditing: true,
                quality: 0.05,
                aspect: [4, 3],
                exif: false
            });

        }catch(err){
            console.log(err)
        }`

both `launchCameraAsync` and `launchImageLibraryAsync` works fine in the pervious version of expo client.

**Comment by wishfulthinkerme** [comment]
I fixed it on my part. I was using sdk 25 for a long time, worked correctly. I have switched today to 27, and it stopped working locally, so I could work on this. Don't know why, but I had to ask for Permissions again, even when they were granted before.

**Comment by aalices** [comment]
@SimoneLSK is this happening on iOS or Android? What SDK are you using?

**Comment by SimoneLSK** [comment]
@aalices 

SDK27.0.0, 
expo client 2.5.9 on IOS, 

not sure if it has problem on AN

**Comment by terribleben** [comment]
Hey there, it's going to be very hard for us to help you if you don't follow our issue template and provide enough info for us to reproduce. Please feel free to reopen with more information we can use to help. Thanks!

**Comment by soozuang** [comment]
I'm having the same problem on IOS device
I can't open the Iphone camera with the Permissions.CAMERA & Permissions.CAMERA_ROLL is 'granted'

**Comment by glevymayo** [comment]
I have the same problem. Could you solve that?

**Comment by soozuang** [comment]
> I have the same problem. Could you solve that?

I think that, there are some views are overlay the ImagePicker view
Are you have some <Model/> component visisble when call The ImagePicker ? Just make the visible = false
