### ISSUE TITLE
NPE with expo-camera and useCamera2Api

### ISSUE THREAD

**Issue by TomCorvus** [expo/expo#17976]
### Summary

Hi 👋
Since I define `useCamera2Api` prop on Camera component, I have crashes on some Android devices.

<img width="1021" alt="Capture d’écran 2022-06-14 à 11 55 06" src="https://user-images.githubusercontent.com/3451011/173549885-b35d1a39-7995-42b8-9d63-4baa95bc4334.png">

Here the list:
- Xiaomi 11 Lite 5G NE (11)
- realme 8 Pro (12)
- Redmi Note 8 (11)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 3.2.1 - /usr/local/bin/yarn
      npm: 8.9.0 - /usr/local/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.5 => 45.0.5 
      react: ^17.0.2 => 17.0.2 
      react-native: ~0.68.2 => 0.68.2 
      react-native-web: ^0.18.0 => 0.18.0 
    npmGlobalPackages:
      eas-cli: 0.8.1
      expo-cli: 5.4.3
    Expo Workflow: bare
```

### Reproducible demo

https://github.com/TomCorvus/expoCamera2

**Comment by brentvatne** [comment]
@thespacemanatee - yes, this is why we expose `useCamera2Api`. it's up to users if they want to upgrade

**Comment by Blyzi** [comment]
Any update on this issue ?
