### ISSUE TITLE
Axios Request Error

### ISSUE THREAD

**Issue by AZKB10** [expo/expo#17970]
### Summary

Hello Everyone, 
I'm trying to connect the backend with the frontend using Axios requests but it seems there is a problem. Everything is working perfectly with Postman requests but when I'm using Axios requests it's not requesting to the backend. I tried everything to solve it.
It seems Axios isn't requesting backend but everything is working fine with the postman, I accessed the URL in the browser it is working there. 
**Expo and Axios Versions**
`"axios": "^0.27.2",
  "expo": "~44.0.0",` 

### What platform(s) does this occur on?
Android

### SDK Version (managed workflow only)

Supported SDKs Versions are 43, 44 and 45

### Environment

**Axios Error (Stringified)**
![image](https://user-images.githubusercontent.com/71012029/175762656-1cd3c975-360d-45f5-80f1-2d7b83c7a067.png)
![image](https://user-images.githubusercontent.com/71012029/175762730-f87087d0-a2c6-44d5-8c47-0d3deab52566.png)

I accessed it in the browser it is working fine there.

### Reproducible demo

**Axios Request**
```import axios from "axios";
import {getAPIEndpointUrl} from "./ServerRequestModifier";
export default axios.create({
    baseUrl: getAPIEndpointUrl() + "/api",
    headers: {
       "Content-type": "application/json",
    }
})

//Get URL
export const getAPIEndpointUrl = () => {
    return 'https://830a-39-44-213-219.eu.ngrok.io';    //Change after ngrok
}

//Request to Server
import http from "../utilities/AxiosRequest";
class LoginRegisterService {
    users() {
        return http.get("/user");
    }
    login(data) {
        return http.post("/user/login", JSON.stringify(data));
    }
}
export default new LoginRegisterService();

**Comment by gregfenton** [comment]
If you put that exact same URL into the browser on the same device as the app you are testing with, is it successful?

**Comment by AZKB10** [comment]
@gregfenton Yes, I did this it is working but can't find the issue in axios request

**Comment by AZKB10** [comment]
Woekin

**Comment by AZKB10** [comment]
I was using baseUrl wrong and also I've to use baseURL.
```export default axios.create({
    // baseUrl: getAPIEndpointUrl() + "/api", //It was not working.
    baseURL: getAPIEndpointUrl() + "/api", //Correct way to do
    headers: {
       "Content-type": "application/json",
    }
})
