### ISSUE TITLE
expo prebuild fails

### ISSUE THREAD

**Issue by borkanee** [expo/expo#17989]
### Summary

Getting boost errors when running expo prebuild. Any ideas?

```
(node:40943) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/boris/Desktop/confetti/confetti-app/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Config synced
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Error installing boost
[!] /usr/bin/tar xf /var/folders/m8/6j48hc597wx018bmy3fnw1sw0000gn/T/d20220627-41475-c3k3fg/file.tbz -C /var/folders/m8/6j48hc597wx018bmy3fnw1sw0000gn/T/d20220627-41475-c3k3fg

boost_1_76_0/libs/metaparse/doc/lazy_metafunction.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/length128_gcc_4.8.5.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/letter.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/letter_expected.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/lit.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/lit_c.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/literal_expected.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/look_ahead.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/manual.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/max_length_gcc_4.8.5.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/metafunction.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/metafunction_class.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/metaparse.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/metaprogramming_value.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/middle_of.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/next_char.qbk: Write failed
boost_1_76_0/libs/metaparse/doc/next_line.qbk: Write failed
...
```

### SDK Version

45

### Environment

 expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.5 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.12
    Expo Workflow: bare

### Reproducible demo

Running expo prebuild produces error

**Comment by brentvatne** [comment]
looks like an issue on your machine. pod install failed possibly due to some machine configuration or maybe you ran out of disk space
