### ISSUE TITLE
Can't register with Slack or Discourse

### ISSUE THREAD

**Issue by OliverCole** [expo/expo#1799]
Not sure how else to contact the maintainers:

http://slack.expo.io/, HTTP 503
https://forums.expo.io/, click Login: 

    {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"An unknown error occurred."}]}

**Comment by OliverCole** [comment]
I think I got that as soon as clicking login.
Now it redirects to the Expo login, which I fill in, and then I get the same error - the whole page, not in the console.

**Comment by nicknovitski** [comment]
Did you create your expo.io account in the last two weeks?  I've just found out we're deploying a fix today for a known issue effecting forum logins for recently created accounts.

**Comment by OliverCole** [comment]
Yes.

**Comment by terribleben** [comment]
Hi there, sorry for the delay here. As far as I know, this may have been related to a migration we performed internally, which should now be totally done. Can you try again and let us know if you're still seeing any issues?

**Comment by OliverCole** [comment]
Seems to be fixed, thanks!
