### ISSUE TITLE
Document ExpoKit behavior that `exp publish` is required for Release builds to work

### ISSUE THREAD

**Issue by iuliuvisovan** [expo/expo#1802]
Hello,

I ran 
`exp init my-new-project`
`exp detach`
`cd android`
`gradlew assembleRelease`

I receive the following error:

> Error: ENOENT: no such file or directory, open 'C:\Users\Iuliu\Desktop\my-new-project\android\app\src\main\assets\shell-app-manifest.json'

**Comment by terribleben** [comment]
I think we need to do a better job documenting this, but a `Release` build won't be able to finish if you have never run `exp publish` before, since it won't have the assets it needs for a production build. (for example, `shell-app-manifest.json` is one such asset.)

Running  `exp publish` should fix your issue, or alternatively building for `Debug` instead of `Release`.

**Comment by iuliuvisovan** [comment]
The thing is since the new 'offline functionality' you should be able to just bundle your app and put it on e.g. an emulator. I can't really publish to the release channel since that's in use by a lot of people and I can't just test the production build by publishing first.. Hope that makes sense.

Nevertheless, adding manually the `shell-app-manifest.json` seems to do the trick.. for now.

**Comment by terribleben** [comment]
Good point. I think in the medium future, we plan to add an `exp` command which simply generates production assets without uploading them anywhere. Right now we don't have that.

**Comment by iuliuvisovan** [comment]
Alright, thanks.

**Comment by slorber** [comment]
what is confusing to me is that by default on detach, doing exp publish does not update the android platform assets because these keys are not set:

```js
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
```
