### ISSUE TITLE
Unable to resolve module @babel/runtime/helpers/interopRequireDefault

### ISSUE THREAD

**Issue by AnatoleLucet** [expo/expo#18038]
### Summary

I'm trying to setup an Expo project inside a pnpm monorepo, but I'm faced with the following error when starting the app:
```
Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /tmp/repro-expo-pnpm/index.js: @babel/runtime/helpers/interopRequireDefault could not be found within the project o
r in these directories:
  node_modules
  node_modules
> 1 | import { registerRootComponent } from "expo";
  2 |
  3 | import App from "./App";
  4 |
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```  
expo-env-info 1.0.4 environment info:
    System:
      OS: Linux 5.13 Manjaro Linux
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    IDEs:
      Android Studio: AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      expo-cli: 5.4.12
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/AnatoleLucet/pnpm-expo-repro

To reproduce: 
- `pnpm i`
- `pnpm start`
- open the app on an android device, and voilà

Sidenote: I'm using a custom entrypoint & custom metro config (same as shown in [this guide](https://docs.expo.dev/guides/monorepos/)), since in my real world app this is in a pnpm monorepo

**Comment by brentvatne** [comment]
https://docs.expo.dev/guides/monorepos/

> We currently have first-class support for yarn workspaces. If you want to use another tool, make sure you know how to configure it.

due to the complexity of monorepos, the diversity of tools, and the size of our team, it's too difficult for us to provide support for them all; so, we only commit to being able to help with yarn workspaces. you can likely find some threads on how to solve the issue that you are seeing elsewhere as i'm sure there are other developers using pnpm workspaces in this context.

**Comment by AnatoleLucet** [comment]
If anyone is faced with the same error, you probably need to upgrade your pnpm version from <= 6 to >= 7

**Comment by StarHosea** [comment]
expo 46 , pnpm 7 with `public-hoist-pattern=*` has same issue

**Comment by BFriedrichs** [comment]
Hey, I know this is closed but this was the first thing I ran into when googling the same problem and I just wanted to share the solution that eventually worked in my case.

For this to work you have to also install `@rnx-kit/metro-config` and `@rnx-kit/metro-resolver-symlinks`

```
// .npmrc
auto-install-peers=true
shamefully-hoist=true
``` 

```
// metro.config.js
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

const { makeMetroConfig } = require('@rnx-kit/metro-config');
const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks');

const symlinkResolver = MetroSymlinksResolver();

const requestResolver = (context, moduleName, platform, realName) => {
  // patch for unpatched dependencies
  // e.g. react-native-version-check-expo
  if (moduleName === '@unimodules/core') {
    const expoModules = 'expo-modules-core';
    return symlinkResolver(context, expoModules, platform, expoModules);
  }

  return symlinkResolver(context, moduleName, platform, realName);
};

module.exports = {
  ...defaultConfig,
  ...makeMetroConfig({
    projectRoot: __dirname,
    resolver: {
      resolveRequest: requestResolver,
    },
  }),
};
```

If you don't have any dependencies where you need to manually patch the unimodules import you can remove the entire custom resolver.

Hopefully this can help anyone else.

**Comment by DesdeJorge** [comment]
I fix my problem changing my `metro.config.js`, maybe can help: 
`const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

const workspaceRoot = path.resolve(__dirname, '../');
const projectRoot = __dirname;

const config = getDefaultConfig(projectRoot);

config.watchFolders = [workspaceRoot];

config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
];

module.exports = config;`

**Comment by DesdeJorge** [comment]
I fix my problem changing my metro.config.js, maybe can help:
```
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

const workspaceRoot = path.resolve(__dirname, '../');
const projectRoot = __dirname;

const config = getDefaultConfig(projectRoot);

config.watchFolders = [workspaceRoot];

config.resolver.nodeModulesPaths = [
path.resolve(projectRoot, 'node_modules'),
path.resolve(workspaceRoot, 'node_modules'),
];

module.exports = config;
```

**Comment by guilhermedevvv** [comment]
> Hey, I know this is closed but this was the first thing I ran into when googling the same problem and I just wanted to share the solution that eventually worked in my case. This worked for resolving issues with pnpm compatibility in our project.
> 
> For this to work you have to install `@rnx-kit/metro-config` and `@rnx-kit/metro-resolver-symlinks`
> 
> ```
> // .npmrc
> auto-install-peers=true
> shamefully-hoist=true
> ```
> 
> ```
> // packages/mobile/metro.config.js
> const { getDefaultConfig } = require('@expo/metro-config');
> 
> const defaultConfig = getDefaultConfig(__dirname);
> 
> const { makeMetroConfig } = require('@rnx-kit/metro-config');
> const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks');
> 
> const symlinkResolver = MetroSymlinksResolver();
> 
> const requestResolver = (context, moduleName, platform, realName) => {
>   // patch for unpatched dependencies
>   // e.g. react-native-version-check-expo
>   if (moduleName === '@unimodules/core') {
>     const expoModules = 'expo-modules-core';
>     return symlinkResolver(context, expoModules, platform, expoModules);
>   }
> 
>   return symlinkResolver(context, moduleName, platform, realName);
> };
> 
> module.exports = {
>   ...defaultConfig,
>   ...makeMetroConfig({
>     projectRoot: __dirname,
>     resolver: {
>       resolveRequest: requestResolver,
>     },
>   }),
> };
> ```
> 
> If you don't have any dependencies where you need to manually patch the unimodules import you can remove the entire custom resolver.
> 
> Hopefully this can help anyone else.

it stills work in may 2023

**Comment by cabe56** [comment]
> Hey, I know this is closed but this was the first thing I ran into when googling the same problem and I just wanted to share the solution that eventually worked in my case. This worked for resolving issues with pnpm compatibility in our project.
> 
> For this to work you have to install `@rnx-kit/metro-config` and `@rnx-kit/metro-resolver-symlinks`
> 
> ```
> // .npmrc
> auto-install-peers=true
> shamefully-hoist=true
> ```
> 
> ```
> // packages/mobile/metro.config.js
> const { getDefaultConfig } = require('@expo/metro-config');
> 
> const defaultConfig = getDefaultConfig(__dirname);
> 
> const { makeMetroConfig } = require('@rnx-kit/metro-config');
> const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks');
> 
> const symlinkResolver = MetroSymlinksResolver();
> 
> const requestResolver = (context, moduleName, platform, realName) => {
>   // patch for unpatched dependencies
>   // e.g. react-native-version-check-expo
>   if (moduleName === '@unimodules/core') {
>     const expoModules = 'expo-modules-core';
>     return symlinkResolver(context, expoModules, platform, expoModules);
>   }
> 
>   return symlinkResolver(context, moduleName, platform, realName);
> };
> 
> module.exports = {
>   ...defaultConfig,
>   ...makeMetroConfig({
>     projectRoot: __dirname,
>     resolver: {
>       resolveRequest: requestResolver,
>     },
>   }),
> };
> ```
> 
> If you don't have any dependencies where you need to manually patch the unimodules import you can remove the entire custom resolver.
> 
> Hopefully this can help anyone else.

@BFriedrichs tried this but am now getting a more cryptic error `Unable to resolve "metro-runtime/src/modules/asyncRequire" from ""`, did you bump into something like this?

**Comment by younes0** [comment]
If you use Monorepo & PNPM, you need to:
- have a `.npmrc` at the root **and not at the package level**, containing [`node-linker=hoisted`](https://github.com/t3-oss/create-t3-turbo/blob/main/.npmrc)
- then you remove `pnpm-lock.yaml` & `node-modules` AND you `pnpm i` from root
- your `metro.config.js` needs to be configured to include root node_modules, see: https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/metro.config.js

**Comment by gelmio** [comment]
> If you use Monorepo & PNPM, you need to:
> 
> * have a `.npmrc` at the root **and not at the package level**, containing [`node-linker=hoisted`](https://github.com/t3-oss/create-t3-turbo/blob/main/.npmrc)
> * then you remove `pnpm-lock.yaml` & `node-modules` AND you `pnpm i` from root
> * your `metro.config.js` needs to be configured to include root node_modules, see: https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/metro.config.js

This was the tip that got me over the line. Thank you @younes0! The .npmrc setup didn't quite work for me though, and I had to add a couple of others to get it to work.
```
// .npmrc
node-linker=hoisted
symlink=false
shamefully-hoist=true
```

**Comment by younes0** [comment]
@gelmio I suppose that your react native version is > 0.72. 
metro since RN 0.72 has symlinks support.

**Comment by gelmio** [comment]
> @gelmio I suppose that your react native version is > 0.72. metro since RN 0.72 has symlinks support.

Right you are! I've dropped that from the .npmrc (I was flailing about randomly to try and solve it, so that useless bit snuck in)

**Comment by vaynevayne** [comment]
same issue , reacy-native "0.73.6"

Modifying metro.config doesn't work for me.

**Comment by Zn4rK** [comment]
To anyone else that might stumble upon this. Check out my solution to this problem. It requires two additional dependencies, but you don't have to compromise on pnpm. 

https://gist.github.com/Zn4rK/ed60c380e7b672e3089074f51792a2b8/
