### ISSUE TITLE
[expo-updates] Update docs for RN 0.68+

### ISSUE THREAD

**Issue by enchorb** [expo/expo#18033]
### Summary

Can we add steps for RN 0.68 & above to the expo-updates bare installation steps as there were many changes made such as moving from the .m to .mm file among others

### Link to the related docs page

https://docs.expo.dev/bare/installing-updates/

**Comment by gpavlov21** [comment]
@enchorb did you manage to add them ? After upgrading to expo SDK 46 my whole build is crashing because of the updates, and i can't figure out why. An update in the docs is 100% needed!
