### ISSUE TITLE
[docs] Deprecated react-native-unimodules is referenced expo-modules-core

### ISSUE THREAD

**Issue by Yandamuri** [expo/expo#18040]
### Summary

I have installed `Expo 45.0.6` in `react-native: 0.68`. When I ran the project form Android studio I faced following error,

> A problem occurred evaluating project ':expo'.
> Project with path ':expo-modules-core' could not be found in project ':expo'.

Then I have gone through `expo-modules-core` docs for details. In the installation guide I have found `react-native-unimodules` which was depricated

<img width="1059" alt="Screenshot 2022-06-30 at 10 01 06 AM" src="https://user-images.githubusercontent.com/31983789/176593519-a8c917f1-d4b2-407d-bace-b3f1e81c7dce.png">

Is `react-native-uniodules` mandatory to use `Expo 45.0.6` as It's been deprecated?

### Link to the related docs page

https://github.com/expo/expo/tree/main/packages/expo-modules-core#android

### Anything else?

Apartment from this issue, I just want to know that, is `expo-modules-core` mandatory to use `Expo`?

**Comment by barthap** [comment]
That's a mistake in the docs. Replace `react-native-unimodules` with `expo-modules-core`.
