### ISSUE TITLE
Notification repeat does not work on ios after x number of seconds.

### ISSUE THREAD

**Issue by harisbaig100** [expo/expo#18053]
### Summary

when we try to repeat a local notification after x number of seconds following docs. The notification does not fire and repeat does not work.

https://docs.expo.dev/versions/latest/sdk/notifications/#scheduling-the-notification-that-will-trigger-repeatedly

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 8.1.1 - ~/Desktop/Myant/Myant-skiin-health-RN/node_modules/.bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/M.HarisBaig/.rvm/rubies/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.0.0 => 8.0.0 
      metro: ^0.66.2 => 0.66.2 
      react: ~17.0.2 => 17.0.2 
      react-dom: ~17.0.2 => 17.0.2 
      react-native: ~0.66.1 => 0.66.1 
      react-native-web: ~0.11.7 => 0.11.7 
    Expo Workflow: bare

### Reproducible demo

run this snack code on real device (ios) the notification will not appear.
https://snack.expo.dev/x8eW7jsVC

**Comment by brentvatne** [comment]
lots of extraneous code in there, please ensure a minimal repro is minimal (includes no superflous/extraneous code)

**Comment by harisbaig100** [comment]
i have mentioned this in reproducible demo its very easy to reproduce just scan QR code and run the app.

run this snack code on real device (ios) the notification will not appear.


https://snack.expo.dev/x8eW7jsVC

**Comment by harisbaig100** [comment]
```
async function schedulePushNotification() {
  await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail 10 seconds! 📬",
      body: 'Here is the 10 seconds body',
      data: { data: '10 seoncds' },
    },
    trigger: {
      repeats: true,
      seconds:10
    },
  });
}
```


this code doesnot trigger repeated notifications

**Comment by BilalSattar99** [comment]
I faced the same issue, we need to open this issue @brentvatne 
When I use hour and minutes repeated notification works fine but when I add seconds repeated notification stop working

**Comment by linonetwo** [comment]
This is my code that works, the "Open in Snack" in https://docs.expo.dev/versions/latest/sdk/notifications/#usage gaves me confidence, because I found it turely popup the notification, just that created notification is hidden by system, because it is classified to "useless notification" and get auto hidden by MIUI system...

```tsx
/* eslint-disable @typescript-eslint/strict-boolean-expressions */
/* eslint-disable unicorn/no-null */
/* eslint-disable @typescript-eslint/require-await */
import { useNavigation } from '@react-navigation/native';
import { isDevice } from 'expo-device';
import {
  addNotificationResponseReceivedListener,
  AndroidImportance,
  getDevicePushTokenAsync,
  getPermissionsAsync,
  removeNotificationSubscription,
  requestPermissionsAsync,
  scheduleNotificationAsync,
  setNotificationChannelAsync,
  setNotificationHandler,
} from 'expo-notifications';
import { useEffect, useRef } from 'react';
import { Platform } from 'react-native';

export function useWikiWebViewNotification() {
  const responseListener = useRef<ReturnType<typeof addNotificationResponseReceivedListener>>();
  const navigation = useNavigation();

  useEffect(() => {
    responseListener.current = addNotificationResponseReceivedListener(response => {
      // DEBUG: console notification
      console.log(`click on notification`, response);
      const route = response.notification.request.content.data.route as string;
      if (route) {
        navigation.navigate(route as never);
      }
    });
    const showNotification = async () => {
      try {
        await registerForPushNotifications();

        await scheduleNotificationAsync({
          content: {
            title: 'Go back to wiki list',
            body: 'Here is the notification body',
            data: { route: 'MainMenu' },
            sound: Platform.OS === 'android' ? false : 'default',
          },
          trigger: {
            seconds: 1,
            channelId: 'default',
          },
        });
      } catch (error) {
        console.error(`Failed to schedule the notification`, error);
      }
    };

    void showNotification();

    return () => {
      if (responseListener.current !== undefined) {
        removeNotificationSubscription(responseListener.current);
      }
    };
  }, [navigation]);
}

async function registerForPushNotifications() {
  let token: string | undefined;
  if (Platform.OS === 'android') {
    await setNotificationChannelAsync('default', {
      name: 'default',
      importance: AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  if (isDevice) {
    const { status: existingStatus } = await getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await requestPermissionsAsync({
        ios: {
          allowAlert: true,
          allowBadge: true,
          allowSound: true,
          allowAnnouncements: true,
        },
      });
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
    }
    token = (await getDevicePushTokenAsync()).data as string;

    setNotificationHandler({
      handleNotification: async () => ({
        shouldShowAlert: true,
        shouldPlaySound: false,
        shouldSetBadge: false,
      }),
    });
  } else {
    alert('Must use physical device for Push Notifications');
  }
  return token;
}
```
