### ISSUE TITLE
Expo.Constant.StatusBarHeight on Android Kitkat

### ISSUE THREAD

**Issue by Bonobomagno** [expo/expo#1805]
On android kitkat, 4.4.4 api 19, statubarheight is 0.
Is this wanted?

edit:
i think that something changed on expo/ react-navigation, and i have to handle the migration.
frozen issue for now

edit2:
The problem is on app.json
If i use 
AndroidStatusbar on it, Expo.Constant.StatusBarHeight is zero, BUT on android api 19, that value on app.json is not handled, so we dont have the statusbar.

I think we need an other issue for add androidStatusBar voice from app.json to work on android 4.4.4 
Instead this one is not an issue.

At least  tip about this on the docs.

**Comment by Bonobomagno** [comment]
After some check, i fond that the best solution is to copy expo solution: write custom code with defined statusbar height.

so, for every one, take a look at expo/js/ directory

**Comment by nicknovitski** [comment]
I'm glad you found a solution, am sorry that no one got back to you, and I agree that this could be worth documenting in some way.

**Comment by Bonobomagno** [comment]
i found a non solution.I Just don't use statusbar key on app.json, and instead a custom control.
So making api 19 work with the statusbar app.json key, would be a better idea

**Comment by cruzach** [comment]
Going to close this issue since the Android StatusBar module has gone through quite a few uodates since this was opened and Expo supports Android 5 and up ([source](https://docs.expo.io/versions/latest/introduction/faq/))

If you have issues with StatusBar in a recent SDK, please open a new issue with a full repro
