### ISSUE TITLE
exp build ios - Unable to build and sign IPA

### ISSUE THREAD

**Issue by tbx0912** [expo/expo#1806]
Hello everybody, 
I have an issue when I try to build my application for iOS with "exp" (in order to detach my Expo app). 
I followed this steps : https://docs.expo.io/versions/latest/expokit/detach

### Environment
OS: macOS High Sierra 10.13.3
  Node: 10.0.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.4

### Steps to Reproduce

1. exp build ios -c
2. "How would you like to upload your credentials" >> Select "Expo handles all credentials"
3. "Will you provide your own Distribution Certificate" >> Select "I want to upload my own file"
4. "Will you provide your own Push Certificate" >> Select "Let Expo handle the process"
5. "Path to P12 file" : providing the p12 file of my Distribution certificate
6. *Wait for build to complete*

### Expected Behavior

Have the build result of my iOS standalone app.

### Actual Behavior
At the end of the procedure, an error happens : 

**Standalone build failed**

![image](https://user-images.githubusercontent.com/22345218/40624137-fdd046b2-62aa-11e8-9275-365a808be0cb.png)

The build monitoring (ID **7a887b6b-2132-4c6b-a7e2-4eb6804546d8**) indicates an other error : **unable to build and sign IPA**.

I don't understand why it doesn't work. The p12 file has been provided by the manager of the Apple Developer Platform of my school and seems to be valid.

NB : I upload my own file for the Distribution Certificate, because it seems that if Expo handles the process, it automatically tries to create a new Distribution Certificate. But in my case, the maximum number of Distribution certificates is reached on the Apple Developer Platform. A new one can't be created, and no one can be deleted, because they are all in use. That's why I use an existing Distribution Certificate. 

Thanks for your help.

**Comment by nicknovitski** [comment]
Build `7a887b6b-2132-4c6b-a7e2-4eb6804546d8` had an xcodebuild error.  We don't currently display those in your build logs, but expo developers can get them for you.

This is the error:
```
Provisioning profile "ch.heiafr.tic.core-seller2 AppStore" doesn't include signing certificate "iPhone Distribution: HEIA-FR (FRRJP2P53L)
```

So it seems that your account's provisioning profile does not include the distribution certificate you uploaded.
