### ISSUE TITLE
Add Watermark to Images

### ISSUE THREAD

**Issue by vincent-odukwe** [expo/expo#18071]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by vincent-odukwe** [comment]
This is not an issue, a bug or a feature request, I would like to know if there is any package that is currently compatible with expo for adding watermark to images.

**Comment by hirbod** [comment]
You could use https://github.com/JimmyDaddy/react-native-image-marker or react-native-skia

since they add native libraries you need to use a custom dev client though.
