### ISSUE TITLE
fetch and blob not working when publish app

### ISSUE THREAD

**Issue by yedeba** [expo/expo#1808]
I can not make **blob** work when publish app with expo:
const response = await fetch(result);
      const blob = await response.blob();

**ERROR: PUTInvalidParameterType: Expected params.Body to be a string, Buffer, Stream, Blob or typed array object.**

In local it works perfectly with xde.

**Comment by nicknovitski** [comment]
The error refers to `PUT`, but I don't see any place in your code where you are `PUT`ing anything.  What are you doing with the value `blob` after you assign it?  Do you later pass it to the firebase storage method `put()`, as in [our example app](https://github.com/expo/firebase-storage-upload-example/blob/master/App.js#L182)?

**Comment by yedeba** [comment]
Yes, refers to PUT
I work with Amplify S3

Example:
const response = await fetch(result);
const blob = await response.blob();
Storage.put(key, blob, { level: 'public',contentType: 'image/jpeg', })
.then(result => .....

**Comment by EvanBacon** [comment]
Thanks @MainAero for getting this worked out!
