### ISSUE TITLE
No refreshToken returned for dropbox auth

### ISSUE THREAD

**Issue by itsmohsinali5** [expo/expo#18080]
### Summary

Hi there!
I'm using expo-auth-session for the authentication of dropbox in react native. Can you tell me how can we get refreshToken? Here is my code for auth request:

const discovery = {
    authorizationEndpoint: "https://www.dropbox.com/oauth2/authorize",
    tokenEndpoint: "https://www.dropbox.com/oauth2/token",
  };
  // Request
  const [request, response, promptAsync] = useAuthRequest(
    {
      clientId: Constants?.manifest?.extra?.DROPBOX_KEY,
      // There are no scopes so just pass an empty array
      scopes: [],
      extraParams: {
        force_reapprove: "true",
      },
      // Dropbox doesn't support PKCE
      usePKCE: false,
      // Implicit auth is universal, `.Code` will only work in native with `useProxy: true`.
      responseType: ResponseType.Token,
      // For usage in managed apps using the proxy
      redirectUri: makeRedirectUri({
        preferLocalhost: true,
        path: "redirect",
        // For usage in bare and standalone
        native: "msa://redirect",
      }),
    },
    discovery
  );
  React.useEffect(() => {
    if (response?.type === "success") {
      setAsync(response.params.access_token);
    }
  }, [response]);

### Link to the related docs page

https://docs.expo.dev/guides/authentication/#dropbox

**Comment by markmccoid** [comment]
Just checking if you were ever able to get a refresh token for Dropbox.

Or if there is another way to not have to prompt the user for authorization every time they access dropbox. 

The tokens returned are short-lived, so it seems a refresh token would be very important.
