### ISSUE TITLE
[SDK 45.0.6 RN 0.68.2] - [Android] - expo-modules-core:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by 19424056** [expo/expo#18081]
### Summary

I can't compile android after upgrade to expo sdk 45
I have tested for ios,  works well

Existing Apps
Setting up the expo package
https://github.com/expo/fyi/blob/main/expo-modules-migration.md

error appears in log :
> Task :expo-modules-core:compileReleaseJavaWithJavac FAILED
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/AppLoaderProvider.java:3: error: package android.content does not exist
import android.content.Context;
                      ^
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/AppLoaderProvider.java:4: error: package android.content.pm does not exist
import android.content.pm.PackageManager;
                         ^
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/AppLoaderProvider.java:5: error: package android.util does not exist
import android.util.Log;
                   ^
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/HeadlessAppLoader.java:3: error: package android.content does not exist
import android.content.Context;
                      ^
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/AppLoaderProvider.java:14: error: cannot find symbol
  public static HeadlessAppLoader getLoader(String name, Context context) {
                                                         ^
  symbol:   class Context
  location: class AppLoaderProvider
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/AppLoaderProvider.java:28: error: cannot find symbol
  private static void createLoader(String name, Context context) throws ClassNotFoundException, IllegalAccessException, InstantiationException, java.lang.reflect.InvocationTargetException, NoSuchMethodException {
                                                ^
  symbol:   class Context
  location: class AppLoaderProvider
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/apploader/HeadlessAppLoader.java:20: error: cannot find symbol
  void loadApp(Context context, Params params, Runnable alreadyRunning, Consumer<Boolean> callback) throws AppConfigurationError;
               ^
  symbol:   class Context
  location: interface HeadlessAppLoader
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/core/interfaces/Package.java:3: error: package android.content does not exist
import android.content.Context;
                      ^
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/core/interfaces/Package.java:13: error: cannot find symbol
  default List<? extends InternalModule> createInternalModules(Context context) {
                                                               ^
  symbol:   class Context
  location: interface Package
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/core/interfaces/Package.java:17: error: cannot find symbol
  default List<? extends ExportedModule> createExportedModules(Context context) {
                                                               ^
  symbol:   class Context
  location: interface Package
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/core/ExportedModule.java:3: error: package android.content does not exist
import android.content.Context;

......
......

symbol:   class Context
  location: class TaskConsumer
/Users/node_modules/expo-modules-core/android/src/main/java/expo/modules/interfaces/taskManager/TaskConsumer.java:39: error: cannot find symbol
  public void didReceiveBroadcast(Intent intent) {
                                  ^
  symbol:   class Intent
  location: class TaskConsumer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-modules-core:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 5 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 1m 48s
572 actionable tasks: 13 executed, 559 up-to-date

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45.0.6

### Environment

System:
OS: MacOS 12.0.1 M1
Shell: 5.1.16 - /bin/bash

Binaries:
Node: v18.2.0 - /usr/local/bin/node
Yarn: 1.22.19 - ~/Dev/abc/node_modules/.bin/yarn
npm: 8.9.0 - /usr/local/bin/npm

npmPackages:
  "react": "17.0.2",
  "react-native": "0.68.2",
> Configure project :expo
Using expo modules
    "expo": "^45.0.6",
  - expo-application (4.1.0)
  - expo-constants (13.1.1)
  - expo-file-system (14.0.0)
  - expo-font (10.1.0)
  - expo-image-loader (3.2.0)
  - expo-image-manipulator (10.3.1)
  - expo-in-app-purchases (13.0.0)
  - expo-location (14.2.2)
  - expo-modules-core (0.9.2)

### Reproducible demo

Just upgrade to expo 45.0.6

**Comment by buidinhmanh14799** [comment]
Same issue

**Comment by Droidking18** [comment]
Getting a similar issue related to expo-structured-headers

**Comment by vonhatquockhanh** [comment]
Same issue. Please help me!!!

**Comment by Yandamuri** [comment]
facing same issue

**Comment by Kudo** [comment]
hi there! please help to provide a minimum reproducible example for us to investigate the issue. as far as i can tell, please make sure the AGP version is 7.0, e.g. `classpath('com.android.tools.build:gradle:7.0.4')` in android/build.gradle. thanks!

**Comment by 19424056** [comment]
> hi there! please help to provide a minimum reproducible example for us to investigate the issue. as far as i can tell, please make sure the AGP version is 7.0, e.g. `classpath('com.android.tools.build:gradle:7.0.4')` in android/build.gradle. thanks!

AGP version is 7.3
gradle/wrapper/gradle-wrapper.properties
  distributionBase=GRADLE_USER_HOME
  distributionPath=wrapper/dists
  distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip
  zipStoreBase=GRADLE_USER_HOME
  zipStorePath=wrapper/dists


in android/build.gradle
    dependencies {
        classpath("com.android.tools.build:gradle:7.0.4")

        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")

        classpath("com.google.gms:google-services:4.2.0")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.10'
    }

in android/app/src/build.gradle
// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

Build failed with an exception.
A problem occurred evaluating project ':app'.
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.

after that try to replace compile with implementation then  Build failed with an exception.
A problem occurred evaluating project ':react-native-i18n'.
> Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

please help me !!!

**Comment by Kudo** [comment]
@19424056  there might be something inconsistent from your native setup between sdk45. if you don't have any change in `android/` folder in your bare workflow app before, it may worth to try `expo prebuild -p android --clean` to re-generate the android/ folder for you.

**Comment by 19424056** [comment]
Tks @Kudo 

my solution is 
In the Build file '....../node_modules/react-native-i18n/android/build.gradle', in the dependencies section change "compile" to "implementation". 

after that upgrade AGP version is 7.0, e.g. classpath('com.android.tools.build:gradle:7.0.4') then expo sdk 45 work well

**Comment by barthap** [comment]
It seems that most problems like this are caused by incompatible `build.gradle` files. There were some changes in SDK 45, so make sure that your files inside `android/` dir are compatible with [the SDK 45 template ones](https://github.com/expo/expo/tree/sdk-45/templates/expo-template-bare-minimum/android) - especially the `build.gradle` and `app/build.gradle`.

People experiencing this in semi-managed/dev-client workflow can delete the `android/` directory and regenerate it using `expo prebuild -p android`. This is of course not always an option for bare-workflow users so this is your responsibility to keep your stuff up to date.

**Comment by groom7** [comment]
I had this kind of problem, I solved it with the help of npx expo-doctor
And updated all my packages to the latest version
