### ISSUE TITLE
GestureHandler undefined in 27.0.2

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1809]
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.2.1
  Yarn: 1.5.1
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  expo: ^27.0.2 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/headsuphealth-5c41fc70-bd73-4f57-8a00-0e9249bb2e07.tar.gz
```

Targeting iOS

### Steps to Reproduce

1. Create an expo project using SDK 27.0.2
2. Import `GestureHandler` from expo, it will be undefined

### Expected Behavior

GestureHandler should have all it's child components

### Actual Behavior

![simulator screen shot - iphone x - 2018-05-29 at 16 28 44](https://user-images.githubusercontent.com/1566400/40686565-5f832e58-635d-11e8-8f63-f07ed67a7d75.png)

### Reproducible Demo

https://github.com/JulianKingman/expo-error-repo

**Comment by freshedgarT** [comment]
I ran into the same problem.

**Comment by brentvatne** [comment]
for now just import from react-native-gesture-handler, this will be resolved in sdk28, sorry for that
