### ISSUE TITLE
jest-expo broken on react-native-web@0.18.x

### ISSUE THREAD

**Issue by kmalakoff** [expo/expo#18090]
### Summary

react-native-web no longer bundles "react-native-web/jest-preset" and jest-expo expects it. It looks like they now recommend a [different setup for jest](https://necolas.github.io/react-native-web/docs/setup/#jest) using jest's"moduleNameMapper"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

Not using expo

### Environment

Not using expo

### Reproducible demo

Run:

git clone git@github.com:kmalakoff/react-native-contains.git
cd react-native-contains
git checkout issue-jest-expo-react-native-web-0.18
npm install
npm run build
npm test

You'll see:

```
Error: Cannot find module 'react-native-web/jest-preset'
Require stack:
- /your-install-directory/react-native-contains/node_modules/jest-expo/config/getPlatformPreset.js
```

**Comment by Kudo** [comment]
hi there! we will support react-native-web@0.18 in the next sdk release. the change is already landed to main. please stay tune, thanks!
