### ISSUE TITLE
Fix logs to show the correct line source line when debugging in Chrome

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#181]
Moved from: https://github.com/expo/xde/issues/82

Run this app on a react-native init project and a new Expo project:

```
class App extends React.Component {
  render() {
    return (
      <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
        <Text>Hello there!</Text>
        <Button title="Press me!" onPress={() => { console.log('hi there') }} />
      </View>
    );
  }
}
```

Then open chrome debugging, press the "Press me!" button. Notice the difference in the logs below

## react-native init project

![screen shot 2017-05-08 at 7 19 50 pm](https://cloud.githubusercontent.com/assets/90494/25833080/a1e5c716-3423-11e7-9ad7-c16d89b17ef2.png)

## Expo project

![screen shot 2017-05-08 at 7 21 20 pm](https://cloud.githubusercontent.com/assets/90494/25833070/97785e38-3423-11e7-8e31-f8cb3293f0bd.png)

**Comment by charlesvinette** [comment]
https://github.com/expo/universe/pull/286 should fix this!

**Comment by brentvatne** [comment]
This will land in SDK18
