### ISSUE TITLE
When pressing a push notification

### ISSUE THREAD

**Issue by machester4** [expo/expo#1810]
### Environment

exp SDK 27 
detach project
Android signed APK

### Steps to Reproduce

1. Create project whit SDK 27
2. Detach project
3. Create signed APK using Android Studio
4. Send push notification
5. On the physical device with the installed app press on the notification

### Expected Behavior

The application opens

### Actual Behavior

I get the following error

![err](https://user-images.githubusercontent.com/25928946/40690557-0d9df5fc-637e-11e8-98b7-010ae28d634e.jpg)

### Extra data
that only happens in production ( signed APK ) and the version 27

**Comment by esamelson** [comment]
Hi @machester4 - I'm unable to reproduce this. Could you provide some more details? What is the exact content of the push notification message you're sending? Does this also happen when you open the production app from the launcher (rather than a push notification)? Have you tried publishing a new version of your app since upgrading to SDK 27?

**Comment by machester4** [comment]
can there be conflict here?
```
 "expo": "^27.0.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz",
```
I will try with the client expo 27.0.2 because it is not in all the devices that I receive this error

**Comment by esamelson** [comment]
Hi @machester4 - sorry for the slow followup here. The mismatched versions should not be an issue. If you manage to find a reliable repro case for this please let us know!

**Comment by machester4** [comment]
hello @esamelson , no problem for the delay, I'm working on an app with sdk 28 and the notifications work correctly. so I could not know what was the error in sdk 27 ​​for the other application.
