### ISSUE TITLE
expo notifications bug 

### ISSUE THREAD

**Issue by jesuscovam** [expo/expo#18109]
### Summary

after updating to the SDK 45 for EAS Update, I started having issues with notifications when I'm developing the apps with the expo go app, this issue is not happening on my standalone apps, only when in development for both Android and iOS.

For android
![PHOTO-2022-07-05-10-05-23](https://user-images.githubusercontent.com/46403187/177359203-9581638f-741f-42c5-842e-1e26b3445350.jpg)

For iOS
<img width="793" alt="Screen Shot 2022-07-05 at 10 06 55" src="https://user-images.githubusercontent.com/46403187/177359423-8c7dc421-9e5f-4202-8a50-099124c5c6f7.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45

### Environment

 expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
      Yarn: 1.19.0 - ~/.nvm/versions/node/v14.17.1/bin/yarn
      npm: 7.22.0 - ~/.nvm/versions/node/v14.17.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30, 31
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-31 | ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.2.7 => 0.2.7
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.12
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@jesuscova/slissto-expo-notifications-issue

**Comment by brentvatne** [comment]
you should pass in the experienceId: https://docs.expo.dev/versions/latest/sdk/notifications/#fetching-the-expo-push-token-and-uploading

**Comment by jesuscovam** [comment]
Thanks, indeed was that, is there a way to know if my credentials were correctly uploaded? After adding the experienceId I'm only being able to send notifications to expoTokens generated in Expo Go apps
