### ISSUE TITLE
Lottie animated object size not changeable

### ISSUE THREAD

**Issue by themakerman** [expo/expo#1811]
Hi,

I wanted to launch a production app using lottie. It works great on iOS but on android the animated object size is very small. Also when i load example on snack everythings okay on both ios and android but the same example when i paste in my code exactly it the size of object becomes small on android.

Can anyone please help me out?

```
  <Lottie
            ref={animation => {
              this.animation = animation;
            }}
            style={{
              width: 400, --> not working for android
              height: 400, --> not working for android
              backgroundColor: '#eee',
            }}
            source={this.state.animation}
/>
```

**Comment by sjchmiela** [comment]
This is due to a little bit outdated version of Lottie. I've submitted a pull request updating underlying `react-native-lottie`. 🙂

**Comment by carmenchapa** [comment]
@themakerman,
If it helps, I could solve this by setting the width bigger for Android:

```
<Lottie ref={animation => {this.animation = animation;}}
                style={Platform.OS === "ios" ? {width: size, height: size} : { width: size * 1.2, height: size}}
                ...
/>
```

**Comment by themakerman** [comment]
nah doesnt works. i think its solved with expo sdk 28
