### ISSUE TITLE
Android Build error after detaching the expo 

### ISSUE THREAD

**Issue by safilsunny** [expo/expo#1812]
- Created a new app

- detached expo project using 'exp detach'

- react-native run-android

i am getting an error like below 

BUILD SUCCESSFUL

Total time: 1 mins 27.935 secs
Running /Users/safilsunny/Library/Android/sdk/platform-tools/adb -s 78ad519 reverse tcp:8081 tcp:8081
Starting the app on 78ad519 (/Users/safilsunny/Library/Android/sdk/platform-tools/adb -s 78ad519 shell am start -n host.exp.exponent/host.exp.exponent.MainActivity)...
Starting: Intent { cmp=host.exp.exponent/.MainActivity }
Error type 3
Error: Activity class {host.exp.exponent/host.exp.exponent.MainActivity} does not exist.

**Comment by terribleben** [comment]
Hey there, sorry we missed this issue. I will consolidate with the newer one: https://github.com/expo/expo/issues/1858
