### ISSUE TITLE
Device.getDeviceTypeAsync() returns TABLET on certain Android devices

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#18127]
### Summary

During my tests (using SDK45 and EAS) I detected that certain Android devices return that they are tablets when they are not, here are some of the devices:

- T-Mobile REVVLRY+
- Moto G7 Plus

Using `react-native-device-info` directly works correctly, so I compared the codes between both implementations, and they look quite similar, except for the handling it does with the `DisplayMetrics` (I don't know if that is the reason for the different behavior),

I leave both codes to see if it is useful:

https://github.com/react-native-device-info/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceTypeResolver.java#L71

https://github.com/expo/expo/blob/sdk-45/packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt#L174

and I also leave a reference to a previously reported incident:

https://github.com/expo/expo/issues/11409

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

```
expo-env-info 1.0.4 environment info:
  System:
    OS: macOS 12.4
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /private/var/folders/qv/x2xgwlnj1qb2wjnthh5bp_600000gn/T/xfs-9977dec8/node
    Yarn: 3.2.0 - /private/var/folders/qv/x2xgwlnj1qb2wjnthh5bp_600000gn/T/xfs-9977dec8/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  npmGlobalPackages:
    eas-cli: 0.54.1
    expo-cli: 5.4.12
  Expo Workflow: managed
```

**Comment by outaTiME** [comment]
Not stale, still happening, and it forces me to use `react-native-device-info` as a dependency to solve this case

**Comment by federicogomezlara** [comment]
Having the same issue with SDK 46 (managed workflow) and expo-device 4.3.0 on Pixel 5

**Comment by outaTiME** [comment]
Such a good news, is this already included in SDK 48?

**Comment by hssdiv** [comment]
48 doesn't have it, so O installed directly
