### ISSUE TITLE
ValidationError: "returnUrl" must be a valid uri

### ISSUE THREAD

**Issue by jedahan** [expo/expo#18130]
### Summary

As mentioned in [this comment](https://github.com/expo/expo/issues/13714#issuecomment-1126134083) a new issue should be opened for using the `projectNameForProxy` property.

I get `"returnUrl" must be a valid uri` regardless of `useProxy` being `true` or `false`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /opt/homebrew/opt/node@16/bin/node
      npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.12
```

### Reproducible demo

Same as original issue thread:
```
import * as AuthSession from "expo-auth-session";

const redirectUri = AuthSession.makeRedirectUri({
	native: "com.myapp://",
    useProxy:false
});

const authUrl = `https://supabaseproject.supabase.co/auth/v1/authorize?provider="google"&redirect_to=${redirectUri}`;

const signIn = async () => {
	const authRes = await AuthSession.startAsync({
		authUrl,
		returnUrl: redirectUri,
	});
};
```

**Comment by Simek** [comment]
Hmm, if you are using the exact same URL as provided in the repro, there is a typo in the protocol - `htttp` (x3 `t`).

**Comment by whyaftab** [comment]
I am having issues with google login

**Comment by blue86321** [comment]
same here.... don't know how to solve it

**Comment by soulfresh** [comment]
We're also having this issue after upgrading from Expo 44 to Expo 45 (and `expo-auth-session` from 3.5.0 to 3.6.1). We're using `expo-auth-session` `AuthRequest.promptAsync()` to auth against Auth0. 

We currently use the Expo auth proxy in Expo Go during development (we use EAS for production builds). After the upgrade, when the browser is directed to `auth.expo.io` we see the `ValidationError: "returnUrl" must be a valid uri" error in the browser. 

[This PR](https://github.com/expo/expo/pull/17327) adds the `projectNameForProxy` property in `expo-auth-session` 3.7.0 but that version doesn't seem to work with Expo 45. It seems like our only option is to upgrade all the way to Expo 46 or transition to the `expo-dev-client` and stop using the proxy? We like the Expo Go paradigm during development but it seems to be getting pretty unstable 😞

**Comment by soulfresh** [comment]
After further debugging, this issue is not related to `projectNameForProxy`. I was able to track it down to `expo-linking` which is generating incorrect redirect URLs. For me, `expo-linking` is generating a url like `exp://192.168.7.23:19000expo-auth-session` when `expo-auth-session#SessionProvider` calls `Linking.createURL()` so this seems like a bug in `Linking.createURL()` (though I'm not sure if `createURL()` is being called correctly).

Here is a patch that resolves the issue for me. However, this patch will probably break other places that call `Linking.createURL` as I don't have enough context to create a real fix.

```diff
diff --git a/node_modules/expo-linking/build/Linking.js b/node_modules/expo-linking/build/Linking.js
index 6915cf7..b275d2d 100644
--- a/node_modules/expo-linking/build/Linking.js
+++ b/node_modules/expo-linking/build/Linking.js
@@ -133,7 +133,7 @@ export function createURL(path, { scheme, queryParams = {}, isTripleSlashed = fa
         if (isExpoHosted() && hostUri) {
             path = `/--/${removeLeadingSlash(path)}`;
         }
-        if (isTripleSlashed && !path.startsWith('/')) {
+        if (path && !path.startsWith('/')) {
             path = `/${path}`;
         }
     }
diff --git a/node_modules/expo-linking/src/Linking.ts b/node_modules/expo-linking/src/Linking.ts
index 56823aa..8dd67cd 100644
--- a/node_modules/expo-linking/src/Linking.ts
+++ b/node_modules/expo-linking/src/Linking.ts
@@ -158,8 +158,19 @@ export function createURL(
     if (isExpoHosted() && hostUri) {
       path = `/--/${removeLeadingSlash(path)}`;
     }
-    if (isTripleSlashed && !path.startsWith('/')) {
-      path = `/${path}`;
+    // When running in Expo Go, the URL created does not include a slash
+    // between the host and path (ex: `exp://192.168.7.23:19000expo-auth-session`).
+    // I'm not sure if this is the correct fix but always appending a
+    // forward slash to the path works for our needs. For more info see:
+    // https://github.com/expo/expo/issues/18130
+    //
+    // Remove this patch when:
+    // ----------------------
+    // - You can log in on Expo Go, web and EAS builds.
+    //
+    // if (isTripleSlashed && !path.startsWith('/')) {
+    if (path && !path.startsWith('/')) {
+        path = `/${path}`;
     }
   } else {
     path = '';
```

**Comment by blue86321** [comment]
Thank you so much @soulfresh , your method reminds me to take a quick remedy without changing the source code in `expo-linking`.
It seems like it is because `expo-auth-session` and `expo-linking` did not go well.
Here is the quick solution, just twisted code from `expo-auth-session` example for Google:
(Facebook is the same, as I just tested)

```diff
import * as React from 'react';
import * as WebBrowser from 'expo-web-browser';
import * as Google from 'expo-auth-session/providers/google';
import { Button } from 'react-native';

WebBrowser.maybeCompleteAuthSession();

export default function App() {
  const [request, response, promptAsync] = Google.useAuthRequest({
    expoClientId: 'GOOGLE_GUID.apps.googleusercontent.com',
    iosClientId: 'GOOGLE_GUID.apps.googleusercontent.com',
    androidClientId: 'GOOGLE_GUID.apps.googleusercontent.com',
    webClientId: 'GOOGLE_GUID.apps.googleusercontent.com',
  });

  React.useEffect(() => {
    if (response?.type === 'success') {
      const { authentication } = response;
    }
  }, [response]);

  return (
    <Button
      disabled={!request}
      title="Login"
      onPress={() => {
-        promptAsync();
+        promptAsync(proxyOptions: { isTripleSlashed: true });
      }}
    />
  );
}
```

**Comment by soulfresh** [comment]
Good point @blue86321. I don't know why I didn't think of that 🤦  I'll use your solution so I don't need to maintain a patch. However, this seems like a bug as we're not using `isTrippleSlashed` for its intended purpose.

**Comment by soulfresh** [comment]
I spoke too soon. The solutions above work for starting the login flow but Android fails to return back to the app after login. I dug a little further and it seems that the actual issue resides in the `Linking.isExpoHost()` function. On SDK 44, this function returns true for us under Expo Go but on SDK 45 it returns false. This seems to be related to moving `Constants.manifest` in SDK 44. Below is an updated patch we use with `patch-package` that works for us. 

```diff
diff --git a/node_modules/expo-linking/build/Linking.js b/node_modules/expo-linking/build/Linking.js
index 6915cf7..be224e2 100644
--- a/node_modules/expo-linking/build/Linking.js
+++ b/node_modules/expo-linking/build/Linking.js
@@ -29,8 +29,12 @@ function getHostUri() {
 function isExpoHosted() {
     const hostUri = getHostUri();
     return !!(hostUri &&
-        (/^(.*\.)?(expo\.io|exp\.host|exp\.direct|expo\.test)(:.*)?(\/.*)?$/.test(hostUri) ||
-            Constants.manifest?.developer));
+        (
+            /^(.*\.)?(expo\.io|exp\.host|exp\.direct|expo\.test)(:.*)?(\/.*)?$/.test(hostUri) ||
+            Constants.manifest?.developer ||
+            Constants.manifest2?.extra?.expoGo?.developer
+        )
+    );
 }
 function removeScheme(url) {
     return url.replace(/^[a-zA-Z0-9+.-]+:\/\//, '');
diff --git a/node_modules/expo-linking/src/Linking.ts b/node_modules/expo-linking/src/Linking.ts
index 56823aa..78dbbe2 100644
--- a/node_modules/expo-linking/src/Linking.ts
+++ b/node_modules/expo-linking/src/Linking.ts
@@ -37,10 +37,19 @@ function getHostUri(): string | null {
 
 function isExpoHosted(): boolean {
   const hostUri = getHostUri();
-  return !!(
-    hostUri &&
-    (/^(.*\.)?(expo\.io|exp\.host|exp\.direct|expo\.test)(:.*)?(\/.*)?$/.test(hostUri) ||
-      Constants.manifest?.developer)
+  return !!(hostUri &&
+      (
+          /^(.*\.)?(expo\.io|exp\.host|exp\.direct|expo\.test)(:.*)?(\/.*)?$/.test(hostUri) ||
+          Constants.manifest?.developer ||
+          // `Constants.manifest?.developer` is no longer set under Expo 45 and
+          // seems to have moved under `manifest2.extra.expoGo`.
+          // See https://github.com/expo/expo/issues/18130
+          //
+          // Remove this patch when:
+          // ----------------------
+          // Login with Expo Go works without it.
+          Constants.manifest2?.extra?.expoGo?.developer
+      )
   );
 }
```

However, there's a good chance that our upgrade path left us with some incorrect config somewhere. Here's our `app.json`:

```json
{
  "expo": {
    "owner": "apartment-snapshot",
    "name": "Apt Snap",
    "slug": "snapshot-ui",
    "version": "3.2.2",
    "orientation": "portrait",
    "icon": "./assets/icon-inverse.png",
    "scheme": "ourschemehere",
    "currentFullName": "...",
    "originalFullName": "...",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#F44C7F"
    },
    "runtimeVersion": {
      "policy": "sdkVersion"
    },
    "updates": {
      "fallbackToCacheTimeout": 0,
      "url": "https://u.expo.dev/..."
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": ...,
      "buildNumber": "3.2.2",
      "supportsTablet": true,
      "config": {
        "usesNonExemptEncryption": false
      }
    },
    "android": {
      "package": ...,
      "versionCode": 440030202,
      "adaptiveIcon": {
        "foregroundImage": "./assets/icon-inverse.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": ...
      }
    }
  }
}
```

**Comment by blue86321** [comment]
@soulfresh Oops, yeah you are right, Android might fail as I only tested on iOS, that's what I missed it.
Good to know that. I appreciate it. I think Expo should have done more tests as so many dependent libraries are intricated with each other... Though my quick remedy is applied to iOS, it still seems like a bug.

**Comment by nicobermudez** [comment]
Bump on this issue.

**Comment by LucasLFurini** [comment]
Is it fixed in SDK 46 or 47?

**Comment by brentvatne** [comment]
we deprecated the auth proxy (`useProxy`), which is what `AuthSession.startAsync` is meant for. I recommend using `useAuthRequest` if you're interacting with an openid/oauth service, or otherwise, use `[WebBrowser.openAuthSessionAsync()](https://docs.expo.dev/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl-options)` instead, which has nothing to do with the deprecated auth proxy.

we're working on cleaning this all up for sdk 49
