### ISSUE TITLE
Task :expo-updates:kaptGenerateStubsDebugKotlin FAILED

### ISSUE THREAD

**Issue by ushyDev** [expo/expo#18134]
### Summary

When i run `expo run:android` i get this error:
` Task :expo-updates:kaptGenerateStubsDebugKotlin FAILED
e: java.lang.IllegalAccessError: class org.jetbrains.kotlin.kapt3.base.KaptContext (in unnamed module @0x348ade9e) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x348ade9e`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

`expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.1.0 
      expo: 45.0.0 => 45.0.0 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.1 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.1 => 0.17.7 
    Expo Workflow: bare`

### Reproducible demo

New expo project with expo-dev-client

**Comment by Royce** [comment]
I had this error after upgrading to expo SDK 50. My problem was that I had the incorrect version of the jdk installed. Following the instructions [here](https://reactnative.dev/docs/environment-setup?platform=android&os=macos) made the problem stop.

```
java --version
openjdk 17.0.10 2024-01-16 LTS
OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)

echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/
```
