### ISSUE TITLE
Fingerprint: how to make three attempts to authenticate?

### ISSUE THREAD

**Issue by lesharadkovich** [expo/expo#1813]
In my application I need to ask user to authenticate with fingerprint and if this authentication fails after three attempts, I ask him to enter his pin-code.
It works fine on iOS and Android virtual machine, but on a physical device authenticateAsync() returns me "authentication_failed" for the first attempt and then it automatically returns "user_cancel", without scanning my finger

Here is my code:
`
async authenticateWithFingerprint() {
        let attempts = 0;

        while(attempts < 3) {
            let { error, success } = await Fingerprint.authenticateAsync();

            if(success) {
                this.setState({fingerprintAuthFailed: false});
                this.onCloseModal(true);
                return;
            } else if(error) {
                PopupService.show("Try again");
                attempts++;
            }
        }

        this.setState({fingerprintAuthFailed: true})
    }
`

Maybe I'm missing something obvious. Anyway, I appreciate any help

**Comment by allankikkas** [comment]
Is physical device enrolled? (isEnrolledAsync)

**Comment by lesharadkovich** [comment]
@allankikkas yes. The point is that if I scan my saved finger, it works fine. But if I do the same with "wrong" finger it makes weird things as I described above.

**Comment by lesharadkovich** [comment]
@EvanBacon yep, still the same

**Comment by terribleben** [comment]
Hey there, we just pass on any system error without performing other logic here:

https://github.com/expo/expo/blob/f4bbbce59c173c8b959a7bffbd6fbccc730b23da/ios/Exponent/Versioned/Core/Api/EXFingerprint.m#L43-L50

So if you're getting `user_cancel` then that indicates that the system errored with `LAErrorUserCancel`. You might consider looking around for further documentation of this system behavior.

**Comment by lesharadkovich** [comment]
@terribleben thanks for your answer, but it's about ios and I have issue only on Android physical devices

**Comment by allankikkas** [comment]
looks like if android os itself gets too many wrong fingerprint touches then it fails silently and reports user_cancel immediately when Fingerprint.authenticateAsync is called. If you send a correct fingerprint somewhere after that then the next call works again as expected. This needs some kind of solution as nothing from the API tells you that. My current workaround is to measure the time it takes to get response from the fingerprint API and if it's less than X then i create a custom error state.

**Comment by maxscience** [comment]
Also the current biometrics example Snack crashes the Expo app on iPhoneX @AdamJNavarro 
https://snack.expo.io/@adamjnav/biometrics-api

**Comment by tsapeta** [comment]
This seems to be a pretty old issue and we already made a lot of changes in this module since that time, so let me close it 🙂 Feel free to open a new report if it still happens to you in the latest SDK.
