### ISSUE TITLE
"Could not reload the application after an edit." after upgrading the SDK45

### ISSUE THREAD

**Issue by paulvelk** [expo/expo#18131]
Referencing to closed issue : possible solution found !

@jakrim 
@MatheusBlanco 

After some "head-crunching" I finally solved the issue. It seems it was **related to the metro package version**. Expo upgrade to SDK45 apparently does not include checking if metro is outdated (why should it ?). Once updated, I got my Fast Refresh working again ! 

So I suggest to check the metro version you are using (see package.json or run: npm list).

In my case it was still  at version 0.59.0  (more than 2 years old ! :( while latest version is at 0.71 !
To update run: npm install --save-dev metro metro-core
  
I hope thismay also solve the issue for others.

Ps. @flashjames : Just wondering why I did not see any refeference to metro package in your package.json file ?

_Originally posted by @paulvelk in https://github.com/expo/expo/issues/17485#issuecomment-1176302044_

**Comment by Simek** [comment]
I have to use the "question" label because we don't have specific label for issues that doesn't fit any category, but it doesn't change the fact that we only accept bug reports in GitHub Issues.

Saying that, I'm happy to see that you have found a possible solution for your problems!

**Comment by paulvelk** [comment]
@Simek  ok no problem understood !

Ps does this mean that the original post I was referencing to, not being a expo  "bug", probably should also have been addressed on another forum ?

Thanks !!
