### ISSUE TITLE
expo face detector property names are different in android than documentation 

### ISSUE THREAD

**Issue by sharifme04** [expo/expo#18139]
### Summary

expo face detector property names are different in android than documentation. Here i see all are capital letter and different name but in the ios and documents are the different
<img width="522" alt="Screenshot 2022-07-07 at 11 00 25 AM" src="https://user-images.githubusercontent.com/24765222/177734893-cc8f028a-3b20-4e61-a30e-c5d375aaed36.png">
 

https://docs.expo.dev/versions/latest/sdk/facedetector/

Can anyone explain to me why names are different in android and ios?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

11.1.3 expo-face-detector

### Environment

![Uploading Screenshot 2022-07-07 at 11.05.55 AM.png…]()

### Reproducible demo

 faces [{"BOTTOM_MOUTH": {"x": 220.056396484375, "y": 564.8382568359375}, "LEFT_CHEEK": {"x": 307.792724609375, "y": 482.4125862121582}, "LEFT_EAR": {"x": 355.0302490234375, "y": 449.90787506103516}, "LEFT_EYE": {"x": 287.8012451171875, "y": 385.1528549194336}, "LEFT_MOUTH": {"x": 270.3269287109375, "y": 542.2865295410156}, "NOSE_BASE": {"x": 215.55124511718748, "y": 465.2086544036865}, "RIGHT_CHEEK": {"x": 140.53208007812498, "y": 480.3816604614258}, "RIGHT_EAR": {"x": 98.88242187499998, "y": 433.3641529083252}, "RIGHT_EYE": {"x": 161.3145751953125, "y": 382.8006362915039}, "RIGHT_MOUTH": {"x": 177.44919433593748, "y": 543.9600563049316}, "bounds": {"origin": [Object], "size": [Object]}, "faceID": 0, "leftEyeOpenProbability": 0.9868497848510742, "rightEyeOpenProbability": 0.997727632522583, "rollAngle": 1.281050682067871, "smilingProbability": 0.003340737195685506, "yawAngle": 356.5288083553314}]

**Comment by brentvatne** [comment]
hey! this looks like it might be an issue. we do however require a reproducible example to help here, so please create a new issue and follow the issue template and provide one :)
