### ISSUE TITLE
[expo-navigation-bar] White bar appears on top and does not close

### ISSUE THREAD

**Issue by oanacioarawaterford** [expo/expo#18141]
### Summary

Hi!
I have setup `androidNavigationBar` to be `sticky-immersive` and I am programmatically closing the navigation bar after 3s if the user has swiped to top using `NavigationBar.setVisibilityAsync('hidden');`. 

Everything works fine in developer mode. I see a transparent bottom and top bar that closes after 3s.

On the `.aab` build however the top bar is all white and it never closes. The bottom bar behaves as expected.

SDK 45

This is how it looks. Notice the top white bar that should not be there

<img width="999" alt="image" src="https://user-images.githubusercontent.com/81676586/177749416-1a1d40df-c00e-401e-bcd6-6a837fe73f2e.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.06.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 27, 29, 30
        Build Tools: 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      expo-cli: 5.4.11
    Expo Workflow: managed

### Reproducible demo

App.json config

```
"androidStatusBar": {
      "hidden": true
    },
"androidNavigationBar": {
  "visible": "sticky-immersive",
  "barStyle": "dark-content"
},
```

Closing the navigation bar after 3s

```
useEffect(() => {
    if (visibility === 'visible') {
      const interval = setTimeout(() => {
        StatusBar.setHidden(true);
        NavigationBar.setVisibilityAsync('hidden');
      }, 3000);

      return () => {
        clearTimeout(interval);
      };
    }
  }, [visibility]);
```

**Comment by kbrandwijk** [comment]
In `sticky-immersive` mode, as far as the [Android documentation](https://android-doc.github.io/training/system-ui/immersive.html) describes it, the system is fully responsible for temporarily showing, and subsequently hiding the system bars again. Because there's no UI changes or listeners involved in this, I suspect that the code to manually hide them doesn't work like you expect it to. Do the system bars hide normally when you don't manually try to hide them?

**Comment by baochungit** [comment]
Although it's just a deprecated warning now, somehow the setting of "androidNavigationBar.visible = sticky-immersive" in app.json is ignored on EAS production build.
