### ISSUE TITLE
Permissions.askAsync never resolves on Android Standalone app

### ISSUE THREAD

**Issue by watadarkstar** [expo/expo#1814]
Permissions.askAsync never resolves on Android Standalone app. Might be related to #1354 .

### Environment

I recently upgraded from Gradle 2.0 to 3.0 this could be relevant, I made the following changes:
https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md

Environment:                                                                                                                         
  OS: macOS High Sierra 10.13.3                                                                                         
  Node: 8.11.1                                                                                                                         
  Yarn: 1.5.1                                                                                                                          
  npm: 5.6.0                                                                                                                           
  Watchman: Not Found                                                                                                                 
  Xcode: Xcode 9.3 Build version 9E145                                                                                             
  Android Studio: 3.1 AI-173.4720617                                                                                                  

Packages: (wanted => installed)                                                                                             
  expo: ^26.0.0 => 26.0.0                                                                                                          
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1                                                                                 
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

### Steps to Reproduce

1. Ask the user for camera permissions using `askAsync`
2. Allow camera permissions
3. Never resolves promise.

### Expected Behavior

It resolves the promise

### Actual Behavior

Does not resolve promise

### Reproducible Demo

TODO

**Comment by jasekiw** [comment]
I also ran into this issue in the expo app it'self. I just upgraded to SDK 2.9.0.0. It was working before that just fine.


I saw the following error in the console.

```
[Unhandled promise rejection: Error: Argument of an incompatible class: class java.util.ArrayList cannot be passed as an argument to parameter expecting class java.lang.String.]
```

expo is passing an array to java when it should be a string.

**Comment by esamelson** [comment]
closing this as it's stale and no repro case was ever provided. If you're still experiencing this issue, please open a new ticket and fill out the template fully. Thanks!
