### ISSUE TITLE
expo-notifications DeviceNotRegistered on iOS build

### ISSUE THREAD

**Issue by asterius1** [expo/expo#18174]
### Summary

Default expo installation with `expo-notifications` sample from docs, after submitting app to iOS TestFlight same test doesn't work and http request for submitting notification returns with error:

`{"data":{"status":"error","message":"\"ExponentPushToken[REDACTED]\" is not a registered push notification recipient","details":{"error":"DeviceNotRegistered","expoPushToken":"ExponentPushToken[REDACTED]"}}}`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

5.4.12

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.7.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 20220410.024423.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: AI-211.7628.21.2111.8309675
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.4.12
    Expo Workflow: managed

### Reproducible demo

```
npx create-expo-app myProject
yarn expo install expo-notifications expo-device eas-cli
```

Replace App.js with code from https://docs.expo.dev/versions/latest/sdk/notifications/#api
At this point launching app with `expo start` and opening it with expo go on iPhone everything works. I can send notifications to phone as expected.

```
yarn eas build -p ios
yarn eas submit -p ios
```

during EAS setup push notifications as prompted.

Install app on iPhone with TestFlight

send notification with `https://expo.dev/notifications` (or from any other api, result is the same)

Expected result: notification appears on device
What happens: API returns `DeviceNotRegistered` error

**Comment by asterius1** [comment]
Tested it on iPhones of my colleagues and it appears to be working for them, however whatever I do (reinstalling app, checking notification settings) doesn't fix situation on my iPhone.

My phone works with notifications from Expo Go. Doesn't work with any expo app I build (neither testflight, preview nor development builds).

My phone is an iPhone X while my colleagues tested on their iPhones 12 and 13.

So right now I am left in a situation where notifications kinda work, but I have no clue if how many of my future users will be able to receive notifications from my app.

**Comment by ayozebarrera** [comment]
I’m not facing this issue anymore. If I’m right, I got this solved on real devices when we published the app!El 21 mar 2024, a las 15:12, great2lrn ***@***.***> escribió:﻿
Were you able to solve this? Im facing the same issue

**Comment by great2lrn** [comment]
Thanks! I'll report back here if it will be the same for me after I publish the app.
