### ISSUE TITLE
ImagePicker -- the image has some offsets on top on iOS

### ISSUE THREAD

**Issue by kevinscience** [expo/expo#1818]
The image cannot be placed at the right place since there is offsets.
The issue happens on both launchCameraAsync and launchImagebriaryAsync.
Some area of launchCameraAsync cannot be dragged to.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.11.2
  Yarn: Not Found
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/kevinscience-e22fac89-c4ac-4213-9216-16132554e54b.tar.gz

iOS has the issue, Android is fine.

### Steps to Reproduce

```
let pickerResult = await Expo.ImagePicker.launchImageLibraryAsync({
allowsEditing: true,
aspect: [1, 1]});

 let pickerResult = await ImagePicker.launchCameraAsync({
            allowsEditing: true,
            aspect: [1, 1],
        });
```

### Expected Behavior

The image picker can pick anywhere of image with no offsets

### Actual Behavior

It has some offsets on both launchCameraAsync and launchImageibraryAsync.

launchCameraAsync:
![giphy 1](https://user-images.githubusercontent.com/19722517/40824953-0d8aa2be-6544-11e8-98bd-09354b14c76a.gif)
  
launchImageLibraryAsync
![giphy](https://user-images.githubusercontent.com/19722517/40823949-41a09652-6540-11e8-9bda-01069f0da665.gif)

### Reproducible Demo

https://snack.expo.io/rkpwDDCym

**Comment by tn12787** [comment]
It's still present and makes for very bad user experience, any word on a fix timeline?
