### ISSUE TITLE
Can't open iOS app after release channel update

### ISSUE THREAD

**Issue by DenysMoro** [expo/expo#18181]
### Summary

Hi. I really like Expo and you are doing great job :)
I've faced weird issue related to `expo-fonts` + OTA + iOS + some config files

I've noticed, at some point, I can't start app in offline (turn off internet first and then start app), after update was downloaded through release channel
I got nothing when I tried to reproduce the issue with fresh build (without any updates through release channel) - so, something to do with `expo-updates` + something else
I started to remove components and files and I removed `Font.loadAsync(...)` and it started to work - so, `expo-updates` + `expo-fonts` + maybe something more
But we need to load some fonts, so I reverted `Font.loadAsync(...)` back and I created new fresh project I tried to break it
I'm happy to say that I did it :D

I CAN'T start app in offline after update was downloaded through release channel, if there is `app.config.ts` in the project (link below)
And I CAN start app in offline if there is no `app.config.ts` (only `app.json`)

Internal distribution is the best way to experiment with that

What I mean:
1. Internet is on (mobile phone)
2. Build app/binaries 
3. Install fresh binaries iOS (Internal distribution, TestFlight)
4. Make sure app is okay - start an app
5. Kill app
6. Turn off internet
7. Start app - should launch as with internet
8. Update release channel
9. Make sure that app downloaded update
10. Kill app
11. Turn off internet
12. Try to start app
13. App won't start

How to test:
1. Move `ios` config section from `app.config.ts` to `app.json` and delete `app.config.ts` - should work fine even after OTA
2. Create `app.config.ts` - you won't be able to start app in offline after OTA

https://user-images.githubusercontent.com/77282657/178271416-2ac5a70e-373a-4272-94b9-8b2894fba0da.MP4

 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.3 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/opt/node@12/bin/npm
      Watchman: 2021.11.08.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.12
    Expo Workflow: managed

### Reproducible demo

Issue is related to build time and to prod/internal distribution. It is small reproducible example

Link to reproducible repo:
https://github.com/DenysMoro/ios-ota-issue

**Comment by kbrandwijk** [comment]
By default, OTA updates only include the JS bundle, all assets will be downloaded on demand, unless you have specified `assetBundlePatterns` in your configuration. This field is specified in your **app.json**, but it's not re-exported in **app.config.ts**, which means that none of the assets will be bundled, and are unable to be downloaded when you are offline. Make sure you re-export the `config` object in your **app.config.ts**, that way the assets are bundled, and your app should behave the same as with only **app.json**.

**Comment by DenysMoro** [comment]
@kbrandwijk Thank you
