### ISSUE TITLE
Project not running on Windows 7 machine, works on Mac

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#182]
Moved from: https://github.com/expo/xde/issues/110

Original post:

I'm having a issue with starting an existing expo project on windows 7.
After line "Opening on Android device" I'm getting following error:
```
5:29:13 PM
Opening on Android device
5:29:29 PM
NotFoundError: Cannot find entry file main.js in any of the roots: ["D:\\workspace\\expo\\jf-card-sharing"]
(node:10352) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

You can test and check [source code](https://github.com/KSET/jf-card-sharing).

-------------------------------------

I confirmed that the project linked to above works on my machine, I asked whether other projects work on @mpetrunic's machine or if it is just this one.

**Comment by mpetrunic** [comment]
@brentvatne new projects created trough xde works as expected.  But opening existing projects with manual `npm install` doesn't seem to be working on my windows 7 machine.

This project works on my ubuntu machine also.

**Comment by brentvatne** [comment]
@mpetrunic - do you have watchman installed? can you try installing it? https://facebook.github.io/watchman/docs/install.html

**Comment by mpetrunic** [comment]
@brentvatne I have it installed. This project was working on windows before. As i recall it stopped working after some xde update.

**Comment by brentvatne** [comment]
@mpetrunic - unfortunately xde doesn't seem to have anything to do with the error, but if you'd like to be certain of that you can download an old version of xde here: https://github.com/expo/xde/releases

I don't really know what's happening here and have never used react-native on windows :\ @jesseruder - any idea?

**Comment by dikaiosune** [comment]
Windows 7 mainstream support ended in 2015, and unfortunately we currently don't have the resources to investigate Windows 7-specific issues. If this is reproducible on a newer Windows installation please post a new issue with a reproduction. Thanks!

**Comment by nahuelhds** [comment]
@mpetrunic @brentvatne In my case (I'm on Windows 10) the issue were resolved by running `watchman watch-del-all` and then uninstalling watchman. It seems just weird but anytime I install watchman expo doesn't work.
