### ISSUE TITLE
[ExpoKit] Unable to run in debug mode on iPhone

### ISSUE THREAD

**Issue by riwu** [expo/expo#1820]
### Steps to Reproduce
1. Download https://github.com/riwu/ActivityTracker/tree/detach (note the branch is `detach`)
2. Open and run the iOS project in XCode debug mode

It should be able to run successfully even without `exp/yarn start` because it's incorrectly running in production.

Now clear the content of this file: https://github.com/riwu/ActivityTracker/blob/detach/ios/tamil-hot-house/Supporting/shell-app-manifest.json and re-run the project. It'll now fail if you didn't run `yarn/exp start`, because it's now correctly running in debug mode.

More info: https://forums.expo.io/t/expokit-unable-to-run-in-debug-mode-on-iphone/9759

**Comment by jesseruder** [comment]
Hi @riwu. I'm not sure I follow. Why do you think it's running in production? It sounds like it's correctly loading from exp/XDE when you build it in debug mode.

**Comment by jesseruder** [comment]
`process.env.NODE_ENV` is separate from whether the iOS app is built for debug/production. `process.env.NODE_ENV` is set by the exp/XDE "debug" flag. The iOS app you built in that gif is a debug native build running production JS.

**Comment by riwu** [comment]
Why is it running production JS? 
My OS env has `NODE_ENV=development` and it's able to run even without starting exp/XDE at all. 
Starting with exp/XDE gave the same result:

![](https://i.imgur.com/8sB8PTa.gif)

**Comment by jesseruder** [comment]
You can just use the `__DEV__` global to see if you're running from the packager or not. I thought `NODE_ENV` was also set by that but maybe not. I'm still a little confused by what your actual issue is. I think it'd be useful for you to follow the "Expected Behavior" "Actual Behavior" format from the issue template.

**Comment by riwu** [comment]
It's definitely not running from package manager because it works even if I don't start the exp/XDE.
The issue is it won't run from package manager even on development mode.
Are you not able to replicate it?

**Comment by jesseruder** [comment]
I don't understand how these two things relate:
> It'll now fail if you didn't run yarn/exp start, because it's now correctly running in debug mode

> it works even if I don't start the exp/XDE, and is using JS bundle on Expo cloud instead of local src

I'm sorry, but I really don't understand your issue. Can you please follow the issue template in the future? It will make it easier for everyone involved. Going to close this for now but feel free to open up another issue and follow the template.
