### ISSUE TITLE
No identifiers allowed directly after numeric literal - Android - SDK 45

### ISSUE THREAD

**Issue by rares-munteanu** [expo/expo#18213]
### Summary

After updating to SDK45 and following the deprecation sections I proceeded to update the other packages too.

iOS working perfectly but on Android I get this error

![image](https://user-images.githubusercontent.com/49690340/178567199-8a0651f8-71d0-4489-a4b2-2814c42fc368.png)

Searched online and saw some "color" package related issue with the ^4.x.x version using the "_" in numbers. I reverted the packages that had the "color" package as sub-dependency but the problem is still occurring. 

I also used the "@babel/plugin-proposal-numeric-separator" plugin but it doesn't seem to work..

Nothing changed in code after updating the packages from SDK44 to SDK45.

Any help would be very much appreciated. Thank you!

Package.json content : 
 "dependencies": {
    "@expo-google-fonts/roboto": "^0.2.2",
    "@expo-google-fonts/saira-extra-condensed": "^0.2.2",
    "@expo/vector-icons": "^13.0.0",
    "@gorhom/bottom-sheet": "^4.4.2",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/netinfo": "8.2.0",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/material-top-tabs": "^6.2.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@react-navigation/stack": "^6.2.2",
    "@rneui/base": "^4.0.0-rc.5",
    "@rneui/themed": "^4.0.0-rc.5",
    "@sentry/react-native": "^3.3.6",
    "apisauce": "^2.1.5",
    "bip39": "^3.0.4",
    "buffer": "^6.0.3",
    "ed25519-hd-key": "^1.2.0",
    "ethers": "^5.6.9",
    "events": "^3.3.0",
    "expo": "^45.0.0",
    "expo-app-loading": "~2.0.0",
    "expo-application": "~4.1.0",
    "expo-av": "~11.2.3",
    "expo-barcode-scanner": "~11.3.0",
    "expo-blur": "~11.1.0",
    "expo-clipboard": "~3.0.1",
    "expo-constants": "~13.1.1",
    "expo-dev-client": "~1.0.0",
    "expo-device": "~4.2.0",
    "expo-firebase-analytics": "~7.0.0",
    "expo-font": "~10.1.0",
    "expo-image-picker": "~13.1.1",
    "expo-intent-launcher": "~10.2.0",
    "expo-linking": "~3.1.0",
    "expo-local-authentication": "~12.2.0",
    "expo-localization": "~13.0.0",
    "expo-random": "~12.2.0",
    "expo-secure-store": "~11.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-system-ui": "~1.2.0",
    "expo-updates": "~0.13.3",
    "expo-web-browser": "~10.2.1",
    "firebase": "^9.9.0",
    "install": "^0.13.0",
    "localized-strings": "^0.2.4",
    "lodash.debounce": "^4.0.8",
    "lottie-react-native": "5.0.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-error-boundary": "^3.1.4",
    "react-native": "0.68.2",
    "react-native-animated-pagination-dots": "^0.1.72",
    "react-native-chart-kit": "^6.12.0",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-pager-view": "5.4.15",
    "react-native-reanimated": "~2.8.0",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-super-grid": "^4.4.2",
    "react-native-svg": "12.3.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-web": "0.17.7",
    "react-query": "^3.39.1",
    "readable-stream": "^4.1.0",
    "sentry-expo": "^4.2.0",
    "styled-components": "^5.3.5",
    "tweetnacl": "^1.0.3",
    "zustand": "^4.0.0-rc.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-numeric-separator": "^7.18.6",
    "@react-native-community/eslint-config": "^3.0.2",
    "@types/lodash.debounce": "^4.0.7",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.67.6",
    "@types/styled-components-react-native": "^5.1.3",
    "babel-plugin-rewrite-require": "^1.14.5",
    "eslint": "7.32.0",
    "prettier": "^2.4.1",
    "react-native-svg-transformer": "^0.14.3",
    "typescript": "~4.5.2"
  },
  "resolutions": {
    "styled-components": "^5"
  }

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: Arctic Fox 2020.3.1 Patch 3 Arctic Fox 2020.3.1 Patch 3
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: managed

### Reproducible demo

Cannot really give a reproducible demo because it was working perfectly before updating and it's a team private project.

### ANDROID EMULATOR LOGS : 
07-12 21:32:28.696  7457  7717 E unknown:ReactNative: Exception in native call from JS
07-12 21:32:28.696  7457  7717 E unknown:ReactNative: abi45_0_0.com.facebook.react.devsupport.JSException: No identifiers allowed directly after numeric literal
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:938)
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   at android.os.Looper.loopOnce(Looper.java:201)
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:288)
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:920)
07-12 21:32:28.696  7457  7717 E unknown:ReactNative: Caused by: com.facebook.jni.CppException: No identifiers allowed directly after numeric literal
07-12 21:32:28.696  7457  7717 E unknown:ReactNative: 
07-12 21:32:28.696  7457  7717 E unknown:ReactNative: no stack
07-12 21:32:28.696  7457  7717 E unknown:ReactNative:   ... 8 more
07-12 21:32:28.734  7457  7717 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: HMRClient.setup()
07-12 21:32:28.735  7457  7717 E unknown:ReactNative: Exception in native call
07-12 21:32:28.735  7457  7717 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
07-12 21:32:28.735  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-12 21:32:28.735  7457  7717 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:938)
07-12 21:32:28.735  7457  7717 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 21:32:28.735  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
07-12 21:32:28.735  7457  7717 E unknown:ReactNative:   at android.os.Looper.loopOnce(Looper.java:201)
07-12 21:32:28.735  7457  7717 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:288)
07-12 21:32:28.735  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
07-12 21:32:28.735  7457  7717 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:920)
07-12 21:32:28.736  7457  7717 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
07-12 21:32:28.736  7457  7717 E unknown:ReactNative: Exception in native call
07-12 21:32:28.736  7457  7717 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
07-12 21:32:28.736  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-12 21:32:28.736  7457  7717 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:938)
07-12 21:32:28.736  7457  7717 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 21:32:28.736  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
07-12 21:32:28.736  7457  7717 E unknown:ReactNative:   at android.os.Looper.loopOnce(Looper.java:201)
07-12 21:32:28.736  7457  7717 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:288)
07-12 21:32:28.736  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
07-12 21:32:28.736  7457  7717 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:920)
07-12 21:32:28.737  7457  7717 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-12 21:32:28.737  7457  7717 E unknown:ReactNative: Exception in native call
07-12 21:32:28.737  7457  7717 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-12 21:32:28.737  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-12 21:32:28.737  7457  7717 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:938)
07-12 21:32:28.737  7457  7717 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 21:32:28.737  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
07-12 21:32:28.737  7457  7717 E unknown:ReactNative:   at android.os.Looper.loopOnce(Looper.java:201)
07-12 21:32:28.737  7457  7717 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:288)
07-12 21:32:28.737  7457  7717 E unknown:ReactNative:   at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
07-12 21:32:28.737  7457  7717 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:920)
07-12 21:32:28.874  1466  1466 I wpa_supplicant: wlan0: CTRL-EVENT-BEACON-LOSS 
07-12 21:32:29.021   326   371 D goldfish-address-space: claimShared: Ask to claim region [0x1f04dc000 0x1f0e04000]
07-12 21:32:29.050   326  2202 D goldfish-address-space: claimShared: Ask to claim region [0x1f172c000 0x1f2054000]
07-12 21:32:29.072   326   371 D goldfish-address-space: claimShared: Ask to claim region [0x1f3f00000 0x1f4828000]
07-12 21:32:29.117  1481  1614 D EGL_emulation: app_time_stats: avg=1242.40ms min=0.96ms max=12410.94ms count=10
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule: Unhandled SoftException
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule: java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by FrescoModule
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at abi45_0_0.com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at abi45_0_0.com.facebook.react.modules.fresco.FrescoModule.invalidate(FrescoModule.java:2)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at abi45_0_0.com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:2)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at abi45_0_0.com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:4)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at abi45_0_0.com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:1)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at android.os.Handler.handleCallback(Handler.java:938)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at android.os.Looper.loopOnce(Looper.java:201)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at android.os.Looper.loop(Looper.java:288)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at abi45_0_0.com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
07-12 21:32:29.313  7457  7718 E unknown:ReactContextBaseJavaModule:    at java.lang.Thread.run(Thread.java:920)
07-12 21:32:29.318  1316  1338 W system_server: Long monitor contention with owner android.anim (1339) at void com.android.server.wm.WindowSurfacePlacer$Traverser.run()(WindowSurfacePlacer.java:58) waiters=0 in void com.android.server.wm.WindowManagerService$H.handleMessage(android.os.Message) for 164ms
07-12 21:32:29.498  1951  1951 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3341 
07-12 21:32:29.533  1951  1951 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1906 
07-12 21:32:29.657  7457  7718 D i       : WARNING: getPackageName called on ScopedContext
07-12 21:32:29.868  1466  1466 I wpa_supplicant: wlan0: CTRL-EVENT-BEACON-LOSS 
07-12 21:32:30.529  7457  7492 D EGL_emulation: app_time_stats: avg=139.39ms min=7.97ms max=883.64ms count=10
07-12 21:32:30.891  1466  1466 I wpa_supplicant: wlan0: CTRL-EVENT-BEACON-LOSS 
07-12 21:32:31.126  2103  2103 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
07-12 21:32:31.883  1466  1466 I wpa_supplicant: wlan0: CTRL-EVENT-BEACON-LOSS 
07-12 21:32:31.969  5874  5874 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.scheduler.ACTION_PROXY_SCHEDULE cmp=com.google.android.gms/.chimera.PersistentInternalBoundBrokerService }
07-12 21:32:32.874  1466  1466 I wpa_supplicant: wlan0: CTRL-EVENT-BEACON-LOSS 
07-12 21:32:33.866  1466  1466 I wpa_supplicant: wlan0: CTRL-EVENT-BEACON-LOSS

**Comment by aleixisp** [comment]
Running with the same issue here since the last upgrade to v.45.

**Comment by TMK04** [comment]
It might be expo-system-ui. I got my app to work after removing that, no clue why though.
