### ISSUE TITLE
undefined is not an object (evaluating '_ExpoCrypto.default.digestStringAsync')]

### ISSUE THREAD

**Issue by alexander01202** [expo/expo#18215]
### Summary

I just installed the expo-crypto library. I need to encode a string to base64. I can see that the crypto library can do this. 

But after installation, I am now trying to use it but it doesn't work. It keeps giving me the error above, 

My code:
```
 (async () => {
      const digest = await Crypto.digestStringAsync(
        Crypto.CryptoDigestAlgorithm.SHA256,
        'GitHub stars are neat 🌟'
      );
      console.log('Digest: ', digest);
      /* Some crypto operation... */
    })();
```

I have no idea why it doesn't work. I have imported Crypto like so:
`import * as Crypto from 'expo-crypto';`

Please what is the cause of this error??

### What platform(s) does this occur on?

Android

### SDK Version

44

### Environment

 expo-env-info 1.0.4 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

Create a new expo project.
Build it on eas and download the standalone app
Install expo-crypto
Start your project. `expo start --dev-client`

Paste the following code in your homepage.
```
 (async () => {
      const digest = await Crypto.digestStringAsync(
        Crypto.CryptoDigestAlgorithm.SHA256,
        'GitHub stars are neat 🌟'
      );
      console.log('Digest: ', digest);
      /* Some crypto operation... */
    })();
```

**Comment by barthap** [comment]
You ran `expo start --dev-client` without rebuilding it. Run `expo run:android` for this time to rebuild the native dev-client. Let me know if this helped 😉
