### ISSUE TITLE
Broken Linkified URL

### ISSUE THREAD

**Issue by PerStirpes** [expo/expo#1822]
Found a linkified url that breaks b/c of the `.` at the end.

After searching around a few repos, I believe the culprit lives here: 
https://github.com/expo/xdl/blob/3d2f6f8b1f10cb6f5667930cf539c96deab60be3/src/project/Doctor.js#L142

If this ^ is the right spot for fix, I'll send over a pr

### Steps to Reproduce

(How I noticed it:)

1. Inside app.json => changed "privacy": "public" => "privacy": "private"
2. yarn start
3. Clicked error message link => 404 

<details open>
<summary > Reproducible Demo</summary>

![broken_hyperlink](https://user-images.githubusercontent.com/19398470/40867898-d798a4f2-65bc-11e8-8202-8848b9621d50.gif)

**Comment by jesseruder** [comment]
Thanks! Yeah that looks like the correct place to fix it.
