### ISSUE TITLE
The app includes an SDK version that doesn't comply with Google's policies

### ISSUE THREAD

**Issue by Carloslauriano** [expo/expo#18228]
### Summary

I installed the “expo-analytics-segment” as described in this post 
https://github.com/expo/expo/issues/17845#issue-1270023790 
despite not using this segment I installed it to try to fix the error. 
But on mine it still gives the error when posting the new version of the app, anyone else with this error that you managed to solve in the eas build?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        Build Tools: 30.0.2
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Reproducible demo

I made a search application and I support this new update from google play this error is occurring

**Comment by brentvatne** [comment]
it's unclear to me what you want to know beyond what is already covered in https://github.com/expo/expo/issues/17845#issue-1270023790
