### ISSUE TITLE
Undefined is not a an object (evaluating RNPushNotification.initialize)

### ISSUE THREAD

**Issue by iuliuvisovan** [expo/expo#1823]
I'm trying to implement push notifications using aws amplify.

According to the SDK25 docs "you can now follow [this Amplify getting started guide](https://github.com/aws/aws-amplify#react-native-development) without ejecting your project or running react-native link".

I'm using SDK27, and have followed [this guide](https://aws.github.io/aws-amplify/media/push_notifications_setup) on how to setup push notifications for RN.
I have the following code:

```
import Amplify from 'aws-amplify';
import { PushNotification } from 'aws-amplify-react-native';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
PushNotification.configure(aws_exports);
```

This throws the error: 

> Undefined is not a an object (evaluating RNPushNotification.initialize)

![image](https://user-images.githubusercontent.com/11357552/40886520-183ea9ee-6742-11e8-89fb-68a875362af3.png)

What am I missing here? Thanks

**Comment by sjchmiela** [comment]
Hi @iuliuvisovan!

I couldn't find any mention of Amplify in the Expo documentation, but there definitely  is one in the commits (see [search results](https://github.com/expo/expo/search?q=amplify&type=Commits)). Unfortunately, the only commit mentioning Amplify is [the one](https://github.com/expo/expo/commit/0730eae79821cd3ae797c0fd964a6948c28c0165), where @brentvatne introduced support of AWS Cognito to Expo SDK. I just checked with an example application and AWS Cognito is still supported in Expo without detaching.

To use AWS Amplify Push Notifications you'd probably have to detach and link the native libraries yourself, but I can certainly recommend using Expo Push Notifications service — https://docs.expo.io/versions/v27.0.0/guides/push-notifications, it should be sufficient for most use cases. 🙂
