### ISSUE TITLE
require a m4r file problem

### ISSUE THREAD

**Issue by onka13** [expo/expo#1824]
Hello, 

I'm trying to get a m4r file but getting an error. If i change the file to mp3 or png it's working. 

```
index.js =>

export default {
"test": require("./test.m4r"), 
}
```

I receive the following error:;

Unable to resolve ./test.m4r" from "./C:\\projects\\...\\assets\\part1\\index.js`: The module `./test.m4r` could not be found"

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1

**Comment by jesseruder** [comment]
Hi @onka13, can you share your app.json? Do you have "m4r" listed in the `packagerOpts.assetExts` field in app.json?

**Comment by onka13** [comment]
Hi @jesseruder , it's working with assetExts. Thanks. But there's no info about assetExts in docs. Please provide more detail about these settings. Thanks.

**Comment by jesseruder** [comment]
@onka13 could you submit a docs PR for that?

**Comment by onka13** [comment]
I've found an issue about this request about a year ago.

[https://github.com/expo/expo-docs/issues/90](https://github.com/expo/expo-docs/issues/90)
