### ISSUE TITLE
ExpoDevMenu.openSettings() not working as expected

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#18242]
### Summary

I have the following code in my app to let devs open the menu using a 3 finger touch instead of a shake to save our wrists:

```ts
import { DevMenu as ExpoDevMenu } from 'expo-dev-client'
import React from 'react'
import { PanResponder, View } from 'react-native'

export const DevMenu: React.FC = ({ children }) => {
  const panResponder = React.useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: (_evt, gestureState) => {
        if (gestureState.numberActiveTouches === 3) {
          ExpoDevMenu.openSettings()
        }
        return false
      },
    }),
  ).current

  const panHandlers = __DEV__ ? panResponder.panHandlers : {}

  return (
    <View pointerEvents="box-none" style={{ flex: 1 }} {...panHandlers}>
      {children}
    </View>
  )
}
```

However I've found this does not 100% work like the "shake" dev menu. mainly the `Reload` button does not reload the app and seems to break dev menu from opening again via any method.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 3.2.0 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@tiltshift/upbeat-nachos

**Comment by brentvatne** [comment]
hi there! expo-dev-client doesn't run in snack so i don't think the provided repro is valid. could you share a clonable github repo?

**Comment by chrisdrackett** [comment]
here is a repo: https://github.com/tiltshift/devmenutest

**Comment by ajsmth** [comment]
is it just the reload button or all of the buttons? is the reload button responsive and just not doing anything?  i will take some time to try and reproduce this tomorrow

**Comment by chrisdrackett** [comment]
I hadn't checked before, but it does seem to be all buttons. The menu slides down with an animation when you take an action, but the action itself does not work (for example if you try and turn on the performance monitor the menu slides down but the monitor does not turn on)

**Comment by esamelson** [comment]
@chrisdrackett - could you clarify whether you're running into this issue in a development build or in Expo Go? If it's a development build (which we're assuming given that you're importing from `expo-dev-menu`), curious if there's a reason why the built-in setting for this -- in the Settings tab of the launcher home screen -- isn't working for you.

**Comment by esamelson** [comment]
Cool -- well we can clearly do a better job of communicating that this option exists 😄  gonna go ahead and close this issue now.

**Comment by chrisdrackett** [comment]
I'm not invested anymore, but isn't it possible this is still an issue? unless this API isn't suppose to be used by devs?

**Comment by esamelson** [comment]
Thanks, you're right -- reopening to track this
