### ISSUE TITLE
Barcode scanner blank screen[docs] 

### ISSUE THREAD

**Issue by limjinyung** [expo/expo#18252]
### Summary

Hi, 

I've been using expo to build a react native app and it's amazing. Am following the docs [here](https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/) to implement the barcode-scanner but it shows an empty page. Been debugging for quite some time only find out that it's a style problem. Could't figure this out at first because the stylesheet shown inside the sample code is empty.

Hope the docs can add it accordingly to this solution [here](https://forums.expo.dev/t/i-cannot-get-the-barcode-scanner-component-to-work/2942/6) to avoid anymore cases like me. Thanks 😄 

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

**Comment by Simek** [comment]
Hello @limjinyung!

The usage example on the docs page sets the size of BarCodeScanner component via `style={StyleSheet.absoluteFillObject}`, which is a `StyleSheet` API property, and until you import `StyleSheet` in the file you can just refer to it as in example usage.

You can read more about this property in React Native docs:
* https://reactnative.dev/docs/stylesheet#properties
