### ISSUE TITLE
splash settings in app.json not passed to stand alone apps.

### ISSUE THREAD

**Issue by GollyJer** [expo/expo#1825]
This isn't a huge deal but I thought I'd pass along...

The following doesn't apply cover mode to my splash screen in iOS.
```json
{
  "expo": {
    "splash": {
      "image": "./_app/assets/images/awesome-splash.png",
      "resizeMode": "cover"
    }
  }
}
```

But the following does apply the cover mode.

```json
{
  "expo": {
    "ios": {
        "splash": {
        "image": "./_app/assets/images/awesome-splash.png",
        "resizeMode": "cover"
      }
    }
  }
}
```

I was under the assumption the specific settings in app.json are overrides and the top level settings are applied if platform settings are unspecified.

If so, then this is a bug report. 
If not, then this can simply be closed.

Thanks. 😄

**Comment by terribleben** [comment]
Here's our code for handling that: https://github.com/expo/xdl/blob/48e5168a9de500143905be31a245a76538f8c372/src/detach/IosLaunchScreen.js#L143-L146

Can you provide an Expo build id from a standalone app which exhibits the bug?

**Comment by GollyJer** [comment]
OK, it appears it's the Expo Client that has the issue and not a standalone build.

**Comment by terribleben** [comment]
That's working for me as well. Here's the code for that: https://github.com/expo/expo/blob/14065bd062edb270b2effef6ebf1ca633b3b7c23/ios/Exponent/Kernel/Views/Loading/EXAppLoadingView.m#L140-L150

Can you show me the full `app.json` which demonstrated this behavior? Maybe I'm not configuring my test app correctly.

**Comment by BenBrostoff** [comment]
@terribleben I am also seeing this behavior with a detached app after upgrading from 27 to 28 for Android. Not sure this is helpful, but my issue was [the same as this one](https://github.com/expo/expo/issues/1322), which was closed a while ago.

**Comment by BenBrostoff** [comment]
Another update here; after upgrading to Expo 29 and releasing my app on Google Play, my detached app *at first* briefly showed a contained image which then became full screen. About 10 minutes later, the behavior changed from a quick white flicker to the covered splash.

**Comment by cruzach** [comment]
I just tested this and the `expo.splash` key seems to be working as expected in the client. If you have any issues with this, please open a new issue with a full reproducible demo
