### ISSUE TITLE
There is a problem with the official website of expo

### ISSUE THREAD

**Issue by Lanceloft** [expo/expo#1826]
the official website of expo have some issues and make the app build failed
user-View IPA/APK builds
![broke](http://og683rb19.bkt.clouddn.com/expo.jpg)

**Comment by jimmylee** [comment]
Hey @Lanceloft can you share with me the link you're trying to visit?

**Comment by Lanceloft** [comment]
https://expo.io/builds @jimmylee

**Comment by ide** [comment]
Closing since this issue is a year old and the root cause is likely no longer relevant.
