### ISSUE TITLE
Expo camera asks for permissions every time user tries to access the camera

### ISSUE THREAD

**Issue by gabriel-envoi** [expo/expo#18265]
### Summary

After updating to Expo45, my app asks for camera permissions repeatedly. This problem only happens in Android.

### What platform(s) does this occur on?

Android

### SDK Version

45

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: Linux 5.17 Pop!_OS 22.04 LTS
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
      npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
    npmPackages:
      expo: 45.0.0 => 45.0.0 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed

### Reproducible demo

import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { Camera, CameraType } from 'expo-camera';

export default function App() {
  const [hasPermission, setHasPermission] = useState(null);
  const [type, setType] = useState(CameraType.back);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestCameraPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (hasPermission === null) {
    return <View />;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }
  return (
    <View style={styles.container}>
      <Camera style={styles.camera} type={type}>
        <View style={styles.buttonContainer}>
          <TouchableOpacity
            style={styles.button}
            onPress={() => {
              setType(type === CameraType.back ? CameraType.front : CameraType.back);
            }}>
            <Text style={styles.text}> Flip </Text>
          </TouchableOpacity>
        </View>
      </Camera>
    </View>
  );
}

**Comment by keith-kurak** [comment]
Hi @gabriel-envoi. I haven't been able to reproduce the issue as described here. Feel free to open this again if you can determine exactly where it happens (e.g., only in standalone, in Expo Go, or a dev client) and can provide a minimal reproduceable demo in the form of a Snack or Github repo.
