### ISSUE TITLE
expo-clipboard crashes on Android with "undefined is not an object (evaluating 'default.setString')"

### ISSUE THREAD

**Issue by ShaneMcNamara** [expo/expo#18261]
### Summary

Using [expo-clipboard](https://docs.expo.dev/versions/latest/sdk/clipboard/) setString method on Android throws the error undefined is not an object (evaluating 'default.setString').

This only happens when installing the package and updating using `expo publish`. If the package is installed and a new standalone app is built, then it wont crash.

[Source code for the app is here](https://github.com/ShaneMcNamara/expo-clipboard-test). I can also share an internal Play Store app with someone that needs to debug the issue.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.3 environment info:
System:
OS: macOS 10.15.7
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 12.16.2 - /usr/local/bin/node
Yarn: 1.19.1 - /usr/local/bin/yarn
npm: 6.14.4 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.8.3 - /Users/ShaneMcNamara/.rvm/gems/ruby-2.2.0/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6821437
Xcode: 12.4/12D4e - /usr/bin/xcodebuild
npmPackages:
expo: ^44.0.0 => 44.0.5
react: 17.0.1 => 17.0.1
react-native: 0.64.3 => 0.64.3
react-native-web: 0.17.1 => 0.17.1
npmGlobalPackages:
eas-cli: 0.45.1
expo-cli: 5.0.3
Expo Workflow: managed

### Reproducible demo

https://github.com/ShaneMcNamara/expo-clipboard-test

Steps:

1. Create standalone Android app using `eas build -p android` with the first commit [b8ee7e981c98d5bf4a8c7fa130d627d9da436c5b](https://github.com/ShaneMcNamara/expo-clipboard-test/commit/b8ee7e981c98d5bf4a8c7fa130d627d9da436c5b)
2. Release the app to the Play Store
3. Checkout the second commit with the added CopyButton [d4a1b0262949c9c602bdab81c10c968cebb6f758](https://github.com/ShaneMcNamara/expo-clipboard-test/commit/d4a1b0262949c9c602bdab81c10c968cebb6f758).
4. Install dependencies using `expo install`.
5. Publish the update to the app using `expo publish`
6. Open the app and click the copy button, app will crash.

**Comment by keith-kurak** [comment]
`expo-clipboard` (like basically all of the Expo SDK packages) includes both JavaScript and native iOS/ Android code. Publishing an update only updates your app's JavaScript code- it cannot update the native code. In your case, the `expo-clipboard` JS is trying to call native code that is not compiled into your app. You will need to submit an update to the stores first before referencing `expo-clipboard`. Once you do that, you can change how you use the clipboard API however you'd like in future updates.

**Comment by soullivaneuh** [comment]
@keith-kurak So if I well understand, including any new `expo-*` package require to publish a new build on the app stores?

Do we have a documentation referencing that?

Thanks!
