### ISSUE TITLE
can not build an android apk or aab

### ISSUE THREAD

**Issue by mary252** [expo/expo#18264]
### Summary

i am adding expo-keep awake and its returning build error due to the java sdk

FAILURE: Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':expo-keep-awake:compileReleaseJavaWithJavac'.
[stderr] 
> Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.
[stderr] 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

 expo-env-info 1.0.4 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed

### Reproducible demo

import { useKeepAwake } from 'expo-keep-awake';

 function App(props:any) {
  const isLoadingComplete = useCachedResources();
  const colorScheme = useColorScheme();
  useKeepAwake();
  if (!isLoadingComplete) {
    return null;
  } else {
    return (
      <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <CartContextProvider>
      <SafeAreaProvider>
        <RootSiblingParent>
            <StatusBar translucent />
            <Navigation colorScheme={colorScheme} />
        </RootSiblingParent>
          </SafeAreaProvider>
      </CartContextProvider>
    </PersistGate>
  </Provider>

      
    );
  }
}
export default (App);

**Comment by raajnadar** [comment]
It seems you need to upgrade to Java 11 try running `javac --version` to check the current version
