### ISSUE TITLE
New Expo project missing js files.

### ISSUE THREAD

**Issue by spiroalisandratos** [expo/expo#18274]
### Summary

Old Expo projects don't have this issue

Missing package "metro/src/lib/attachWebsocketServer" in the project at: ...
This usually means `react-native` is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.
"""

Both attachWebsocketServer.js and attachedWebsocketServer.js.flow are missing from new expo init installs.
Have these files been deprecated? I though there might have been an issue with react-native however the same issue isn't present, when you bootstrap with react-native init, you don't get this error and the files are there.

### SDK Version

45

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/node_modules/.bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: managed

### Reproducible demo

https://docs.expo.dev

npm install --global expo-cli && npx create-expo-app my-app

npm start

**Comment by spiroalisandratos** [comment]
Info from an expo project that runs.

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/node_modules/.bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: managed

**Comment by amandeepmittal** [comment]
Hi @spiroalisandratos. We haven't been able to reproduce the issue as described here. Feel free to open this again if you can provide a minimal reproducible demo in the form of a Github repo.

**Comment by spiroalisandratos** [comment]
Hi @amandeepmittal.  Thanks.  I just created a new project and this time it worked.  If you can't reproduce it, it must be environmental.  It was failing with the generic expo init projectName that was the minimal code.  Thanks for looking into it.
