### ISSUE TITLE
Request for Hawuei "Protected Apps" Permissions or Alert

### ISSUE THREAD

**Issue by iCueto** [expo/expo#1827]
Hello, Everybody... Thanks for the Fantastic Expo Kit, I love it...

I have a Hawuei ECO with Android 5.1, that I'm using for testing. The most important feature for my app is the Push Notifications.

I've discovered that Huawei has built in a "feature" called Protected Apps, that can be accessed from the phone settings (Battery Manager > Protected Apps). This allows elected apps to keep running after the screen is turned off.

I was looking for a package for detect that feature, I found this [react-native-huawei-protected-apps](https://www.npmjs.com/package/react-native-huawei-protected-apps)

Unfortunately for me, I'll need to Detach the App and lose the Push Notification feature, but I don't want...

I would like have that feature implemented in that Kit, I would be very grateful.

Thank you all for the fantastic work you have done.

**Comment by jesseruder** [comment]
Hi! That sounds like a useful feature. Can you post it at https://expo.canny.io so that we see this when deciding what features to build?

**Comment by iCueto** [comment]
Thank @jesseruder, The feature already was posted...

**Comment by jesseruder** [comment]
Ok thanks. The issue template says
>   Is this a feature request? Please vote or post it at https://expo.canny.io instead.

So I'm going to close this in favor of the Canny post.
