### ISSUE TITLE
Install error "App not installed" on Android

### ISSUE THREAD

**Issue by b13i** [expo/expo#18283]
### Summary

EAS dev build fails to install on Android emulator with error "App not installed". I've tried both the development and preview builds.

eas.json
```
{
  "cli": {
    "version": ">= 0.55.1"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "android": {
        "buildType": "apk"
      },
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

app.config.ts
```
import { ConfigContext, ExpoConfig } from "@expo/config";
import "dotenv/config";

// https://docs.expo.dev/workflow/configuration/
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  owner: "localkitchens",
  name: "guest-kiosk",
  slug: "guest-kiosk",
  version: "1.0.0",
  orientation: "portrait",
  icon: "./assets/icon.png",
  userInterfaceStyle: "light",
  splash: {
    image: "./assets/splash.png",
    resizeMode: "contain",
    backgroundColor: "#ffffff",
  },
  updates: {
    fallbackToCacheTimeout: 0,
  },
  assetBundlePatterns: ["**/*"],
  ios: {
    supportsTablet: true,
  },
  android: {
    package: "com.localkitchens.kiosk",
    adaptiveIcon: {
      foregroundImage: "./assets/adaptive-icon.png",
      backgroundColor: "#FFFFFF",
    },
    permissions: ["ACCESS_NETWORK_STATE"],
  },
  web: {
    favicon: "./assets/favicon.png",
  },
});
```

Tested on two emulators
1. Pixel 3a running Android API 33
2. Custom tablet virtual device running Android API 33

![CleanShot 2022-07-18 at 11 39 13](https://user-images.githubusercontent.com/1800902/179548919-c614e387-b95a-4022-8dd2-848fd0fb810d.png)

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

expo-dev-client `v1.0.1`
expo `v45.0.6`
expo-updates-interface `v0.6.0`

### Environment

```
expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.3.0/bin/yarn
      npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/bobbypourkazemi/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: managed
```

### Reproducible demo

Link to EAS dev build:
https://expo.dev/accounts/localkitchens/projects/guest-kiosk/builds/ade654ea-44e2-4848-99d1-9826e62c8595

**Comment by brentvatne** [comment]
this doesn't seem like an issue with expo tooling, try installing to another android device or refer to google results for this error, eg: https://www.imobie.com/support/android-app-not-installed.htm

the apk from the provided link installs in my emulator

<img width="487" alt="image" src="https://user-images.githubusercontent.com/90494/179562328-277c9cd7-5492-4eb1-8cc0-bb9d562b6250.png">

**Comment by b13i** [comment]
Thanks @brentvatne!

For posterity sake, this was because my emulator had too little storage. Can quickly figure this out by downloading the `.apk` build from Expo and running `adb install /path/to/apk`, which will spit out a more descriptive error message.

Hope that helps someone else!
