### ISSUE TITLE
Random crashes with AR

### ISSUE THREAD

**Issue by andrewbest** [expo/expo#1828]
Crashes occur randomly after running an AR project for a few minutes. I don't have a reproducible demo but I have crash logs that show the code. This has been happening with iOS 11.3.

In EXGLView.m line 280:
```
[_glContext runInEAGLContext:_uiEaglCtx callback:^{
    glBindRenderbuffer(GL_RENDERBUFFER, _viewColorbuffer);
    [_uiEaglCtx presentRenderbuffer:GL_RENDERBUFFER];
}];
```

See the following crash log screen shots:
<img width="438" alt="crash 1" src="https://user-images.githubusercontent.com/347313/40958243-7365b2a2-684d-11e8-8bef-3cc289b37238.png">

<img width="440" alt="crash 2" src="https://user-images.githubusercontent.com/347313/40958295-a2584a8e-684d-11e8-83f4-5fb777a7cf4c.png">

**Comment by schazers** [comment]
Hmm, I'll mark this, but it'll be hard for us to look into it without some code. Can you give any more info about the type(s) of app(s) this crashes on? Even if code crashes only sometimes, can you send us some anyway?

**Comment by EvanBacon** [comment]
Are you running the newest (SDK 28) code?

**Comment by andrewbest** [comment]
I have SDK 27. How do you get 28?

I am experimenting with this which might be working better.
```
      [_glContext runAsync:^{
        glBindRenderbuffer(GL_RENDERBUFFER, _viewColorbuffer);
        [_uiEaglCtx presentRenderbuffer:GL_RENDERBUFFER];
      }];
```

**Comment by EvanBacon** [comment]
@andrewbest I rewrote the entire AR module so it may work a little differently in SDK 28 which will be officially released soon. (pending apple review) I'm not entirely sure how versioning works when pulling and building this. 
Also if you are experimenting with changes maybe start a fork, I'm not sure how to help with this arbitrary block of code not working.
I tried to extract as much AR from the GLView as possible in the changes: https://github.com/expo/expo/commit/596157548921b90696ab47ccc107345958f61637

**Comment by andrewbest** [comment]
The code is still in the file at line 275. I can still give it a try but it doesn't seem like it would be different with the same code there.

**Comment by andrewbest** [comment]
This is not reproducible with SDK 28 I have found so far. I'll open a new case if the issue comes back.

**Comment by Navithahk** [comment]
I can still see this issue with SDK 28, where the AR is randomly crashing at 
[_glContext runInEAGLContext:_uiEaglCtx callback:^{
    glBindRenderbuffer(GL_RENDERBUFFER, _viewColorbuffer);
    [_uiEaglCtx presentRenderbuffer:GL_RENDERBUFFER];
}];
