### ISSUE TITLE
suggestion: pear down Android permissions?

### ISSUE THREAD

**Issue by raould** [expo/expo#183]
I know permissions are hard on Android since for most versions of the OS the permissions have to be fixed up front. But... I am loathe to install the Expo client given the wide net it casts asking for permissions. It would be great if there was some minimal version that only asked for network access so I could do e.g. the tutorials on repl.it.

**Comment by ide** [comment]
The Expo client asks for a lot of permissions so you can use a lot of APIs. You could try creating a secondary account on Android and installing Expo there or use a newer version of Android that supports runtime permissions (like iOS).
