### ISSUE TITLE
Linking.openURL("www.google.com") fails in standalone app

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#18316]
### Summary

I have build my app using the EAS service. In the expo [documentation](https://docs.expo.dev/guides/linking/) I have read that, in order to use Linking.openURL() in standalone apps, we need to configure the `infoPlist` of our app.json file.

This is my configuration: 

```
...
"ios": {
   "infoPlist": {
        "LSApplicationQueriesSchemes": [
          "geo",
          "http",
          "https",
          "instagram",
          "mailto",
          "maps",
          "sms",
          "spotify",
          "tel"
        ]
   }
}
```

The problem I am experiencing is when I try to open a site like: _www.gooogle.es_, without the `http/https` scheme.

I get the error:  

> Error: Unable to open URL: file:///Users/victoriomolina/Library/Developer/CoreSimulator/Devices/ID/data/Containers/Bundle/Application/ID/MyAppName.app/www.google.es]

> Note: I am not really sure if it is necessary to add the `geo`, `http`, `https`, `mailto`, `maps`, `sms`, and `tel` fields. Is it? I just added `instagram` and `spotify` because I got an exception in production which told me to add them to `LSApplicationQueriesSchemes`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45.0.0

### Environment

```
  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    Expo Workflow: managed

```

### Reproducible demo

With my app.json configuration, after performing a build using EAS, do the following:

`Linking.openURL("www.google.com")`

**Comment by VictorioMolina** [comment]
I have thought to prepend the scheme to the url in JavaScript, like this:

```
const withHttp = url => !/^https?:\/\//i.test(url) ? `http://${url}` : url;

Linking.openURL(withHttp("www.google.com"));
```

But I am trying to make sure if that's possible with the app.json configuration.

**Comment by brentvatne** [comment]
we don't expose any such options for this. you should ensure that you provide the appropriate scheme when using the linking api
