### ISSUE TITLE
Can assets from MediaLibrary be resized using ImageManipulator

### ISSUE THREAD

**Issue by martsie** [expo/expo#1832]
I've been attempting this for a while now. The assets returned from MediaLibrary appear to be in HEIC format, even when I do a MediaLibrary.getAssetInfoAsync to get more information about the file all I get is HEIC information. It doesn't look like ImageManipulator is able to resize the HEIC photos. ImageChooser always converts photos to JPG so those two libraries work quite well.

Is there any way to get the JPG photo instead of the HEIC photo for an asset in the MediaLibrary? If not then how are people using HEIC images when posting forms etc.

**Comment by tsapeta** [comment]
Hey @martsie,
I think ImageManipulator allows to pass HEIC files. Have you tried doing `ImageManipulator.manipulate(asset.uri, [])`? It should do the trick - convert HEIC to JPG.

**Comment by nikki93** [comment]
Also -- it may help to `FileSystem.copyAsync(...)` the file into your app's file system first. Using media library assets for the `from:` works.

**Comment by Lidanha** [comment]
Hey,

It seems that when I use this:
let manipulatedInfo1 = await ImageManipulator.manipulate(uri, [])

uri value is: 
assets-library://asset/asset.HEIC?id=7E300F51-1A45-4AE3-80CC-B04098E9F3F1&ext=HEIC

it throws an error:
[Unhandled promise rejection: Error: The file does not exist. Given path: `/asset.HEIC`.]

Any ideas to working with HEIC from libarry? Using SDK version 26. (I'm trying to convert to Jpeg and lower the resolution before sending to the server)

Thanks

**Comment by tsapeta** [comment]
Hey @Lidanha,
As Nikki said, you need to copy the asset from MediaLibrary to app's cache directory using `Expo.FileSystem.copyAsync`. Unfortunately, ImageManipulator doesn't support `assets-library://` paths yet, but we're going to add such support in the next release (SDK 29).

**Comment by Lidanha** [comment]
@tsapeta thanks!

**Comment by GollyJer** [comment]
I ran into this today as well.
However, I'm unable to write to `FileSystem.cacheDirectory`.
This code errors.
```javascript
    const destination = `${FileSystem.cacheDirectory}image_cache`;
    try {
      await FileSystem.makeDirectoryAsync(destination, { intermediates: true });
      console.log('created directory:');
    } catch (error) {
      console.log('error creating directory:');
    }
    const dir = await FileSystem.readDirectoryAsync(destination);
    console.log('dir contents:', dir);
```
I was hoping to write to `cacheDirectory` because, as I understand it, this directory will be garbage collected by the OS.

This code doesn't error (only difference is the destination).
```javascript
    const destination = `${FileSystem.documentDirectory}image_cache`;
    try {
      await FileSystem.makeDirectoryAsync(destination, { intermediates: true });
      console.log('created directory:');
    } catch (error) {
      console.log('error creating directory:');
    }
    const dir = await FileSystem.readDirectoryAsync(destination);
    console.log('dir contents:', dir);
```
But if I go this route the files will exist forever unless I delete them by hand, correct?

Ultimately I was looking to make a folder in the cache directory, copy the HEIC file to that folder, manipulate it to a jpeg, upload to the server, then let the OS clean it up whenever.

Why can't I write to the cache folder?

Thanks!

**Comment by tsapeta** [comment]
Hey @GollyJer,
Yes, the first way with cacheDirectory seems to be a good way. Can you provide more details, like which method is rejecting and what is the error message? Thanks!

**Comment by GollyJer** [comment]
OK, that was NOT fun. 😝 

This takes a collection of images of any type from the ImagePicker and spits out a collection of jpeg's.

```javascript
import shortid from 'shortid';

const convertImagesToJpeg = async (imagesFromPicker) => {
  // Clear the working folder.
  const folderPath = `${FileSystem.documentDirectory}image_conversions`;
  const { exists } = await FileSystem.getInfoAsync(folderPath);
  if (exists) await FileSystem.deleteAsync(folderPath);

  // Now recreate it.
  try {
    await FileSystem.makeDirectoryAsync(folderPath, { intermediates: true });
  } catch (error) {
    // Swallow. Android errors if directory exists.
  }
  // Now we have an empty working folder.

  // Start the conversion.
  const convertAnyImageTypeToJpegPromises = imagesFromPicker.map(async (imgObj) => {
    try {
      // Copy from the camera library to the conversion folder.
      const destinationUri = `${folderPath}/${shortid.generate()}.jpg`;
      await FileSystem.copyAsync({
        from: imgObj.node.image.uri,
        to: destinationUri,
      });

      // file is not a real jpeg yet.  Use ImageManipulator to convert to jpeg.
      const imageToConvert = await FileSystem.getInfoAsync(destinationUri);
      const convertedImage = await ImageManipulator.manipulate(imageToConvert.uri, [], {
        format: 'jpeg',
      });

      // Replace the camera library copy of the image with the manipulated version.
      await FileSystem.deleteAsync(imageToConvert.uri);
      await FileSystem.moveAsync({ from: convertedImage.uri, to: imageToConvert.uri });
    } catch (error) {
      console.log('!! ERROR in convertAnyImageToJpegPromises !!', error);
    }
  });
  await Promise.all(convertAnyImageTypeToJpegPromises);

  // At this point all images should be jpegs.  Create a nice collection.
  const imageConversionsFolderContents = await FileSystem.readDirectoryAsync(folderPath);
  const convertedImages = imageConversionsFolderContents.reduce((acc, file) => [
    ...acc,
    {
      name: file,
      type: 'image/jpeg',
      url: `${folderPath}/${file}`,
    },
  ], []);

  console.log('convertedImages:', convertedImages);
  return convertedImages;
};
```

There will be some tweaks to make it work with the Camera.  Specifically, the `from:` path will be located in a different property when doing the `copyAsync`.

**Comment by GollyJer** [comment]
@tsapeta I must have been experiencing a red herring error.  
`FileSystem.cacheDirectory` is working on both iOS and Android now.  I updated my code above.  Thanks.

**Comment by tsapeta** [comment]
Closing as we released SDK 29 which solves this issue.
