### ISSUE TITLE
[docs] Testing with Jest is not as documented

### ISSUE THREAD

**Issue by robertoosantos** [expo/expo#18329]
### Summary

I'm following this [Testing with Jest](https://reactnavigation.org/docs/testing/) documentation on an existing app [caseira.app](https://www.caseira.app/) but I can't run a test as simple as this:

`/* eslint-disable no-undef */
import React from 'react';
import renderer from 'react-test-renderer';

import App from '../App';

describe('<App />', () => {
  it('has 1 child', () => {
    const tree = renderer.create(<App />).toJSON();
    expect(tree.children.length).toBe(1);
  });
});`

I get :
`SyntaxError: Cannot use import statement outside a module

      2 | import 'dayjs/locale/pt-br';
      3 | import { KeyboardAvoidingView, Platform } from 'react-native';
    > 4 | import Providers from './navigation';
        | ^
      5 | import Constants from 'expo-constants';
      6 | import * as Notifications from 'expo-notifications';
      7 | import * as Sentry from 'sentry-expo';`

Does anyone knows what is missing?

My package.json:

`  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "globals": {
      "__DEV__": true
    },
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ],
    "setupFiles": [
      "<rootDir>/jest/setup.js"
    ]
  },`

### Link to the related docs page

https://reactnavigation.org/docs/testing/

**Comment by amandeepmittal** [comment]
@robertoosantos seems like the error is being reported in a different file which I don't think is related. From the error message, it seems like the `Providers` you are importing from `.navigation` file or folder is either missing an export statement or not being exported.

I'd suggest you to re-check the import statement or share a re-producible example.

**Comment by robertoosantos** [comment]
After a long trying and error phase, the solution involved:

1. Including "transform" in Jest configuration
2. Including "@sentry.*" at transformIgnorePatterns
3. Defining "globals" for __DEV__ variable

```json
  "jest": {
    "preset": "jest-expo",
    "setupFilesAfterEnv": ["@testing-library/jest-native/extend-expect"],
    "transform": {
      "\\.[jt]sx?$": "babel-jest"
    },
    "globals": {
      "__DEV__": true
    },
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@sentry.*)"
    ],
    "testTimeout": 20000,
    "setupFiles": [
      "<rootDir>/jest/setup.js"
    ]
  }
```

It was also necessary this babel.config.js

```javascript
/* eslint-disable no-undef */
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      'babel-preset-expo',
    ],
    plugins: ['react-native-reanimated/plugin'],
  };
};
```

**Comment by amandeepmittal** [comment]
Ah okay! The documentation link you shared was from React Navigation library. Here is the Expo documentation for setting up and configuring Jest to run tests: https://docs.expo.dev/guides/testing-with-jest/

My bad, I didn't realize it was React Navigation library docs 🙇. I'd recommend the above link if you are starting from scratch in the future and feel like you are not reaching an outcome. React Navigation link you shared initially only covers the React Navigation config part that is required with Jest.

**Comment by robertoosantos** [comment]
Thank you! It was actually my mistake. I was with so many tabs opened and copied the wrong URL.

The expo documentation also does not include the transform configuration for jest and I think it should have it because even the simplest app won't be an App.js only, there will be other *.js files importing each other and the transformation will be necessary.

**Comment by amandeepmittal** [comment]
No worries @robertoosantos! 

That's a great point. Thanks for suggesting that! I will update the docs to include the `transform` key.
