### ISSUE TITLE
Typing issue for `expo-asset` Asset and Image source

### ISSUE THREAD

**Issue by bombillazo** [expo/expo#18328]
### Summary

When using TypeScript with expo, one can pass an asset to an `<Image />` component as specified in the docs:
```tsx
const [assets, error] = useAssets([require('path/to/asset.jpg'), require('path/to/other.png')]);

return assets ? <Image source={assets[0]} /> : null;

```

However, one gets the following typing error:
```sh
Type 'Asset' is not assignable to type 'ImageSourcePropType'.
```

One would expect this to be a valid expression even with TS.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.14.0 - ~/Projects/Code/code/node_modules/.bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/user/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.19 => 0.3.19 
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.6 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.5.1
    Expo Workflow: managed

### Reproducible demo

[Demo](https://snack.expo.dev/@bombillazo/vigorous-cheese)

**Comment by bombillazo** [comment]
Bump, still an issue, no TypeScript support for this use yet

**Comment by dani-z** [comment]
Really a shame this is not yet supported. The only way I manage to make TS happy was to cast the source.
```js
source={assets[0] as ImageSourcePropType}
```

**Comment by bombillazo** [comment]
I would give it a try but honesly have no clue what is required to fix this issue, I move to use an svg loader just to avoid the ugly setup required to satisfy this typing error.

**Comment by bombillazo** [comment]
We moved away from Expo, this was never solved, since I wont be following up, Ill close it and let someone else follow up.
