### ISSUE TITLE
TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by codecrypt112** [expo/expo#18338]
### Summary

There is an error showing,

`TypeError: Attempted to assign to readonly property.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

Error: Requiring module "node_modules/lottie-react-native/lib/index.js", which threw an exception: TypeError: Attempted to assign to readonly property.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
`

I think that's an package error.

here's my code 
`<View
      style={{
        // backgroundColor: 'red',
        position: "absolute",
        height: "100%",
        width: "100%",
        justifyContent: "flex-end"
      }}
    >
      <LottieView
        style={{
          // backgroundColor: 'yellow',
          // position: 'absolute',
          height: "95%",
          width: "100%"
          // justifyContent: 'flex-end',
        }}
        source={require("./summer.json")}
        resizeMode="cover"
        autoPlay
      />
    </View>`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45.0.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 18.6.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.13.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: bare

### Reproducible demo

`<View
      style={{
        // backgroundColor: 'red',
        position: "absolute",
        height: "100%",
        width: "100%",
        justifyContent: "flex-end"
      }}
    >
      <LottieView
        style={{
          // backgroundColor: 'yellow',
          // position: 'absolute',
          height: "95%",
          width: "100%"
          // justifyContent: 'flex-end',
        }}
        source={require("./summer.json")}
        resizeMode="cover"
        autoPlay
      />
    </View>`

**Comment by mohamed-abdullah1** [comment]
same error 😥

**Comment by oldschoolstarsman66** [comment]
yeah same here too
