### ISSUE TITLE
MediaLibrary is requesting write permission to copy or delete files despite granted permission

### ISSUE THREAD

**Issue by correadevuk** [expo/expo#18335]
### Summary

The goal is to download an image and save it on the user's device. It's requesting a user confirmation every time an album is created or when deleting an image. It seems odd and the documentation doesn't mention anything about additional dialogues on Android that require the user to grant or deny move and delete actions.

When using `MediaLibrary.createAlbumAsync(albumName, asset, false)` a dialog pops up asking the user to give permission to modify the file. If denied, it throws an error message saying `User didn't grant write permission to requested files`. This also happens with `MediaLibrary.deleteAssetsAsync([assets])`. 

It seems like a bug since `MediaLibrary.requestPermissionsAsync()` was already given and status shows granted every time. 

`MediaLibrary.createAlbumAsync(albumName, asset)`  works fine but it creates 2 images in the user's device and if I cannot delete it, after a few days they will have thousands of images from my app.  

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 32
        Build Tools: 29.0.2, 32.0.0, 32.1.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.6 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.5.1
    Expo Workflow: managed

### Reproducible demo

https://snack.expo.dev/@vitorcorrea/2563bf

**Comment by brentvatne** [comment]
https://support.google.com/photos/thread/90386989/google-photos-keeps-asking-to-modify-save-delete-move-this-photo-has-all-permissions?hl=en

**Comment by jacobsood** [comment]
This may help: https://stackoverflow.com/a/78382159/13765808
