### ISSUE TITLE
Failed to connect to /10.0.0.5:19000

### ISSUE THREAD

**Issue by sugalivijaychari** [expo/expo#1833]
I learnt react.

Now i want to create an application using react-native.

i have installed react-native in my windows system by following commands:
npm install -g create-react-native-app 
create-react-native-app appname
cd appname
npm  start

it gave me QR Code.

I have installed Expo app in my mobile- Vivo v9 android version oreo 8.1
I have scanned the QR code from Expo app. 

I have got an error as below:

Uncaught Error: java.net.ConnectException: Filed to connect to /10.0.0.5:19000 Time:11:58:28 Fatal Error

**Comment by nikki93** [comment]
Are your Android device and computer on the same LAN? Also -- you could try using 'tunnel' option (see help for `exp start` or gear icon in XDE).
