### ISSUE TITLE
Android keystore : exp build:android. SHA1 fingerprint is different

### ISSUE THREAD

**Issue by Jesserhee** [expo/expo#1834]
Hi. 
I did exp build:android and chose option1 : let expo handle credential. -> uploaded on Google Play
I am now trying to update this with new build version apk to Google Play.
This time when I am "exp build:android" expo did not ask me options.
I tried to upload this apk to Google Play and Google Play says the keystores(hash value) are different.

I am confused why expo says it will handle credential but I don't have keystore and can not update
with expo this time.

I am now trying to exp build:android -c
and put .keystore file
but I am still confusing I should use passwords and alias that I get from
exp fetch:android:keystore

I put the path of my .jks file what I downloaded from expo fetch
and copy and paste the information below also I got from expo fetch.

Keystore password:
Key alias:
Key password:

but I got this message below after even though I copy and paste all of those information
while the expo build

Unable to find an existing exp instance for this directory, starting a new one...

Thank you

**Comment by esamelson** [comment]
Hi @Jesserhee - really sorry for the slow follow-up here, this seems to have slipped through the cracks unfortunately. Can you clarify that the issue you're having is that you are unable to update your app on Google Play because you don't have the correct keystore?

**Comment by Jesserhee** [comment]
Hi thank you for your email

I cannot remember exactly but I happened to update my app using exp and now updating using exp publish

Thank you

2018. 7. 18. 오전 7:16, Eric Samelson <notifications@github.com> 작성:

**Comment by esamelson** [comment]
Awesome, glad to hear you resolved it. I'm going to close this for now, but let us know if you run into this issue again.

**Comment by FakhruddinAbdi** [comment]
Hi @esamelson 
I just encountered the same issue in which I can not update my google play app.
It says you are using the wrong key,

Is there any hope you can recover my old keystore ?

I have sent an email to support@expo.io but replied by a bot and asked me to use forum

**Comment by FakhruddinAbdi** [comment]
I just tried cleaning project and rebuilding the apk, but it gives me another error which is  "Can not recover key "
