### ISSUE TITLE
Builds locally but fails on EAS due to plugins in app.json

### ISSUE THREAD

**Issue by arjendevos** [expo/expo#18342]
### Summary

When adding plugins to app.json it builds fine locally but fails when running eas build. 

We have this as a plugin in app.json: `"plugins": ["./android-manifest.plugin.js"]`
This is a simple file where we edit the android-manifest (which is not the problem). Then we prebuild locally to test and everything works fine. But when we run: `expo build --platform android` it fails with this error: `ENOENT: no such file or directory, open '/home/expo/workingdir/build/apps/expo/android/gradlew'`

We didn't know why it failed but before we tried to upgrade to SDK 46 and for that we needed to specify the kotlin version in plugins. Whenever we remove the plugins out of app.json it works like a charm but with plugins it fails.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 31, 32
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: bare

### Reproducible demo

1. Make an expo project
2. Add plugins to your app.json:
```
 "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "kotlinVersion": "1.6.10"
          }
        }
   ]
]
```
3. Run `expo prebuild`
4. Run `expo build --platform android`

**Comment by RichardLindhout** [comment]
It's also in SDK 45 if we add plugins: [...something] to the config it fails, but it works fine when prebuilding locally!

**Comment by brentvatne** [comment]
can you share a link to the build?

probably you are accidentally uploading your android directory and it's not running prebuild there, and you have some gitignore rules set to ignore gradlew

**Comment by RichardLindhout** [comment]
We're not doing that, if we remove the plugins it works fine (but we need to remove the QUERY_ALL_PACKAGES from the android manifest to make Android working)


Without plugin (succeeds)
075fcf29-c4c9-4452-b8ab-38cfcbb19e46

With plugin (fails)
285639ab-b336-4063-a621-2b5adf10c8a8

However prebuilding locally has no problems and removed the QUERY_ALL_PACKAGES from the android manifest.
It also happens with offical plugins like the build properties plugin (https://docs.expo.dev/versions/latest/sdk/build-properties/)

**Comment by Kudo** [comment]
could you provide a repository with minimal reproducible example? i just tested a sdk 45 managed app with expo-build-properties plugin and it works for me.

**Comment by RichardLindhout** [comment]
Hey @Kudo @brentvatne  I have invited you to the repository. EAS prebuild works fine locally but not in the cloud.
It's the https://github.com/de-grote-verleiding/dgv-app repository.

You can view the https://github.com/de-grote-verleiding/dgv-app/tree/main/apps/expo
The github workflow is here
https://github.com/de-grote-verleiding/dgv-app/blob/main/.github/workflows/build.yaml

**Comment by RichardLindhout** [comment]
Maybe it's because the working directory differs from 'normal' apps?

**Comment by Kudo** [comment]
@RichardLindhout it looks like when submitting the failed job, eas detect it as a bare workflow. that may because you ever execute `expo run:android` or `expo prebuild` before. could you try to remove `android/` folder and reset all local changes to the origin git state, then do eas build again? thanks!

**Comment by RichardLindhout** [comment]
We tried exactly that and we don't have an android folder. When we remove plugins from config it works in EAS when we add it back it stops working. It works locally. EAS build does not show the error so we don't know whats going on.

It's really related to the plugins array

**Comment by Kudo** [comment]
@RichardLindhout from [the success build log you shared](https://expo.dev/accounts/richardlindhout/projects/de-grote-verleiding/builds/075fcf29-c4c9-4452-b8ab-38cfcbb19e46), in the *Read app config* section, i saw the `"plugins": ["./android-manifest.plugin.js"]`, the plugin array is still there and build succeeded. could you double check whether the build failures are really coming from the plugin array?

**Comment by RichardLindhout** [comment]
Yes but we do have app.config.js the app.json is for making automatic version number working. In the succesful build we did not spread the plugins (from app.json) to app.config.js

I'm now building two new apps one with plugins and one without the plugins I'll share the links if they are received in EAS build

**Comment by RichardLindhout** [comment]
So the plugins in app.json are ignored but in the new build they are removed from app.json, but will be available in app.config.js were they belong :)

**Comment by RichardLindhout** [comment]
Oops limits reached :( Can't build right now unfortunately

**Comment by RichardLindhout** [comment]
Hmmm looks like it's working now. Must have been something else which was going wrong!

**Comment by Kudo** [comment]
@RichardLindhout good to know, thanks!
