### ISSUE TITLE
[SDK 46-beta6] Android build fails with "incompatible version of kotlin" when react-native-webview is included

### ISSUE THREAD

**Issue by keith-kurak** [expo/expo#18346]
### Summary

EAS Android build fails with `Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.` error when `react-native-webview` is installed. Seems to be the exact same error reported in https://github.com/react-native-webview/react-native-webview/issues/2578, which means it may be an incompatibility between webview and RN 69.

Thanks to @hadils for reporting this through our support channel!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

~46.0.0-beta.6

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/keith/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.0-beta.6 => 46.0.0-beta.6 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.1 => 0.69.1 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
    Expo Workflow: managed

### Reproducible demo

1. Run `EXPO_BETA=1 yarn create expo-app`
2. cd into dir
3. Run `expo install react-native-webview`
4. Run `eas build:configure`, setup for Android/ All
5. Run `eas build --platform android --profile development` (y/ defaults for all prompts)

**Comment by brentvatne** [comment]
https://github.com/react-native-webview/react-native-webview/pull/2592

**Comment by RichardLindhout** [comment]
If you explicityly set kotlin version with eas-build config plugin it also works! However plugins breaks prebuilding in EAS cloud

**Comment by brentvatne** [comment]
@RichardLindhout - can you create an issue for the plugins issue that you're referring to? we're not familiar with it, plugins do work as expected as far as we know

**Comment by skinnynpale** [comment]
same
