### ISSUE TITLE
Unable to install packages using expo-cli on Ubuntu

### ISSUE THREAD

**Issue by jsxclan** [expo/expo#18349]
### Summary

![2EAC2812-85E5-4334-8CA5-CD0FC265D74B](https://user-images.githubusercontent.com/51025764/180585670-dc050c3b-f86f-4f54-bf16-8fee11597dcb.png)

I just installed Ubuntu on my machine and this is my first time using Expo on Ubuntu but I get the above error whenever I tried to install packages using expo-cli.

**Note:** the project I'm working on is a new project that I just set up on my machine using expo-cli.

### SDK Version

5.6.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed

### Reproducible demo

I just set up the project using `npx create-expo-app ./ -t` and I haven’t edit anything yet, I’m just trying to install react navigation.

**Comment by brentvatne** [comment]
it looks like yarn isn't working on your machine. try running `yarn add react-native-screens@~3.11.1 react-native-safe-area-context@4.2.4` and it will fail with the same error (that is all expo install is doing)

**Comment by jsxclan** [comment]
I have yarn installed on my machine, and I have tried to install packages using yarn without any issues but somehow expo wasn't able to install the packages :(

**Comment by brentvatne** [comment]
what do you see in the `yarn-error.log` file?

**Comment by brentvatne** [comment]
it looks like you're probably in a monorepo. i imagine that is related. i think if you try running it in another repo you would find it works. likely there is some dependency issue in your monorepo

**Comment by jsxclan** [comment]
![image](https://user-images.githubusercontent.com/51025764/180918120-206494f6-54be-47c5-a7df-f27eae9031da.jpeg)![image](https://user-images.githubusercontent.com/51025764/180918135-3f160a69-3ef3-4014-8380-56f1ddcd1faa.jpeg)

**Comment by jsxclan** [comment]
![image](https://user-images.githubusercontent.com/51025764/180924660-7560df32-48b1-4aae-81a3-722597ffb682.jpeg)

Expo is just misbehaving when using yarn. It works fine when using npm (`expo install packageName --npm`).

**Comment by jsxclan** [comment]
![image](https://user-images.githubusercontent.com/51025764/180925043-e16ee6cc-ea88-4d1e-8db8-40e3d4ea79cc.jpeg)

I have no idea why expo is so mean this time. The above error starts showing up now and I have tried to update the expo-cli package, I even uninstalled the package from my machine and installed it again but no luck :(

**Comment by jsxclan** [comment]
And this error when trying to create new expo app:

~/Desktop/expo-testing$ npx create-expo-app ./ -t
✔️ Choose a template: › Blank (TypeScript)
✖️ Something went wrong in downloading and extracting the project files: Could not find npm package "expo-template-blank-typescript@latest"
Error cloning template: Error: Could not find npm package "expo-template-blank-typescript@latest"

I'm fed up :(

**Comment by jsxclan** [comment]
And this error when trying to create a new expo app:

~/Desktop/expo-testing$ npx create-expo-app ./ -t
✔️ Choose a template: › Blank (TypeScript)
✖️ Something went wrong in downloading and extracting the project files: Could not find npm package "expo-template-blank-typescript@latest"
Error cloning template: Error: Could not find npm package "expo-template-blank-typescript@latest"

I'm fed up :(

**Comment by jsxclan** [comment]
Never mind, I was able to fix the issue following option 2 on this [site](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04) :)

I'm using the version of Node.js that I installed from Ubuntu Software (snap), the version of Node.js that's installed from Ubuntu Software (snap) seems to be old and broken 🤦‍♂️

**Comment by brentvatne** [comment]
thanks for following up :)
