### ISSUE TITLE
Adding config plugin causes build failure on ios

### ISSUE THREAD

**Issue by natke** [expo/expo#18358]
### Summary

Trying to use a config plugin with expo is causing my ios build to fail. App builds and runs successfully until I add any config plugin to my config.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/nakersha/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: bare

### Reproducible demo

```
npx create-expo-app my-app
cd my-app
expo install expo-camera
```

Edit the app.json file to add the plugin

```
{
  "expo": {
    "name": "my-app",
    "slug": "my-app",
    "plugins": ["expo-camera"],
    ...
```

Build the project

```
expo prebuild
expo run:ios
```

The prebuild step passes and the run:ios step fails with this error: 

```
/bin/sh -c /Users/nakersha/Library/Developer/Xcode/DerivedData/myapp-fuvbcubmdnoqhcfvmoanhiixaztm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/EXConstants.build/Script-46EB2E0000C580.sh
/Users/nakersha/Develop/samples/expo/my-app/node_modules/@expo/config-plugins/build/plugins/withIosBaseMods.js:156
  readFile,
  ^

TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/nakersha/Develop/samples/expo/my-app/node_modules/@expo/config-plugins/build/plugins/withIosBaseMods.js:158:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at _withIosBaseMods (/Users/nakersha/Develop/samples/expo/my-app/node_modules/@expo/config-plugins/build/index.js:269:16)
    at Object.<anonymous> (/Users/nakersha/Develop/samples/expo/my-app/node_modules/@expo/config-plugins/build/index.js:467:20)
Command PhaseScriptExecution failed with a nonzero exit code
```

Minimal repro here: https://github.com/natke/expo-repro

I put the full log fiile here: https://github.com/natke/expo-repro/blob/main/.expo/xcodebuild.log

**Comment by Kudo** [comment]
hi there! could you share how you build the app, by xcode directly or using `expo run:ios`?

**Comment by RichardLindhout** [comment]
Same problem, we have it too https://github.com/expo/expo/issues/18342

**Comment by Kudo** [comment]
#18342 is for android problem and this one is for ios. they should be different issues.

**Comment by natke** [comment]
I updated the post to add that I build with

```
expo prebuild
expo run:ios
```

**Comment by natke** [comment]
I resolved this issue. It was a node version problem. Part of the app was using the version of node that I had installed with nvm (v16), and part was using the system version (v10). I am not sure why this is the case, or whether the expo folks want to investigate it further, install an old version of node in `/usr/local/bin/node`. Otherwise this issue can be closed

**Comment by Kudo** [comment]
thanks for the sharing. xcode does not respect the login shell settings, so developers with other nodejs manager like nvm may encounter similar issues. i believe the issue would be resolved in the coming sdk 46.

**Comment by natke** [comment]
Thank you. So does that mean for SDK<46, the recommendation would be to not use nvm and only use the system node?

**Comment by Kudo** [comment]
could you check your expo-constants version, i.e. from `yarn why expo-constants`? as far as i know, in expo-constants@13.1.1, we should have a minimum support for nvm.

**Comment by natke** [comment]
```
yarn why expo-constants
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "expo-constants"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "expo-constants@13.1.1"
info Reasons this module exists
   - "expo" depends on it
   - Hoisted from "expo#expo-constants"
info Disk size without dependencies: "320KB"
info Disk size with unique dependencies: "1.02MB"
info Disk size with transitive dependencies: "10.63MB"
info Number of shared dependencies: 53
✨  Done in 0.97s.
```

**Comment by Kudo** [comment]
oh sorry it seems the support doesn't work for your case.
i used to have this workaround `sudo ln -sf $(command -v node) /usr/local/bin/node`, in case it helps for you.

**Comment by natke** [comment]
Thanks! I have a workaround. We can close the issue and I will retest with the new SDK at some point

**Comment by Kudo** [comment]
thanks @natke!
