### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by brimby** [expo/expo#18356]
### Summary

This is in regards to Expo Contacts. In my usage I'm seeing a field on the Contacts object called "lookupKey" that isn't listed in the docs as being an available field. I'm especially interested in why this lookupKey exists alongside the id field. Is one more reliable than the other in continuing to point to the same Contact object throughout any changes the user makes to their device contact list?
<img width="578" alt="Screen Shot 2022-07-24 at 11 46 15 AM" src="https://user-images.githubusercontent.com/20480908/180655596-11fba208-3bfc-496d-8240-79343d256f7c.png">

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/contacts/#contact

**Comment by brimby** [comment]
Oh also it looks like I'm getting a "type" field on the PhoneNumber object which isn't listed here https://docs.expo.dev/versions/latest/sdk/contacts/#phonenumber

**Comment by brentvatne** [comment]
you can treat undocumented fields as private apis. if you'd like to learn more about how the internal works, you can refer to the source code here: https://github.com/expo/expo/blob/168ee43f71f005baa11edf98e518593443e1807a/packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.java
