### ISSUE TITLE
Push Notifications not working for Standalone iOS or Android Apps - SDK 27.0.2

### ISSUE THREAD

**Issue by karanmartian** [expo/expo#1835]
Hi guys,

I am directly using the Push notification tester from: https://expo.io/dashboard/notifications to send to a particular device by filling the EXPO PUSH TOKEN field with the push token associated with the device and my standalone app doesn't receive the notification. Only the Expo App receives it. This is a major issue. And our users are on both iOS and Android and its now not working on either platform for standalone apps. We built the app using the latest Expo SDK 27.0.2

"expo": "^27.0.2",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz"
Latest exp version - 54.0.1

Any help to this critical issue will be greatly appreciated. People have talked about switching to FCM on other threads but isn't it an Android only solution?

**Comment by karanmartian** [comment]
Yes that works perfectly. I am able to capture all device tokens without any issues. The push notification tester also tells me success but apps are not receiving any push notification. i guess FCM is a better option.

**Comment by ide** [comment]
FCM affects Android delivery and you should definitely set up your Expo project to use it. For iOS delivery, sometimes there can be a delay in delivering notifications, but in general the Expo server passes back the status that Apple returns.

**Comment by karanmartian** [comment]
Ok so just to confirm if I switch to FCM, I will be able to deliver to both standalone Android and iOS Apps correct?

**Comment by ide** [comment]
Yes: FCM affects only Android and iOS is left unchanged.

**Comment by ide** [comment]
Closing since FCM is working and will be soon mandatory for all new standalone apps (plus Google is requiring it too).
