### ISSUE TITLE
Instead of releasing React Native 0.69.1 with Expo SDK 46, upgrade this with React Native 0.69.2

### ISSUE THREAD

**Issue by asharamseervi** [expo/expo#18359]
### Summary

Just after releasing Expo SDK 46 Beta, React Native's new dot release had been published, which actually includes significant bug fixes & improvements, which might be considered by Expo Community to include this dot release i.e. React Native 0.69.2 instead of React Native 0.69.1

For further info: https://github.com/facebook/react-native/releases

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

SDK 46 Beta

### Environment

Not Applicable.

### Reproducible demo

Not Applicable.

**Comment by Kudo** [comment]
hi there! thanks for your inquiry. we already aware of this and are looking react-native 0.69.3 when we release sdk 46.

**Comment by hamdij0maa** [comment]
expo sdk 46.0.1 is published, but the sdk install tool ( npx install-expo-modules@latest) is not functional yet, can you give us the release time of it ?

**Comment by Kudo** [comment]
@hamdij0maa `install-expo-modules@0.3.7` had some issues so i reset @0.3.6 as latest. you could try to use `npx install-expo-modules@0.3.6`. thanks!
