### ISSUE TITLE
Stuck at splash screen when loading a JSI module

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [expo/expo#18350]
### Summary

When importing a JSI module app gets stuck at splash screen. However if the module is imported when the app is fully loaded (e.g. when editing components while the app is running) everything works as expected. No errors in the console, however Android logcat prints various errors about modules not found, namely HMR module, JSTimers, and some others. There's also an error which seems significant, printed only once:

```
Invariant Violation: No callback found with cbID 0 and callID 0 for module <unknown>. Args: '[{"app_state":"active"}]'
```

[Edit]: Only happens with expo. In a project created with `react-native init` everything works.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.20.0 - /usr/bin/node
      npm: 6.14.17 - /usr/bin/npm
      Watchman: 20210821.022905.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Android NDK: 21.4.7075529
    npmPackages:
      expo: ~46.0.0-beta.6 => 46.0.0-beta.6 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.1 => 0.69.1 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: bare

### Reproducible demo

Importing any module based on https://github.com/mrousavy/react-native-jsi-library-template
Importing just the template itself works (breaks) too, altho the template throws not implemented runtime error, which obscures this error.

**Comment by Kudo** [comment]
hi there! could you provide a repository to a minimal reproducible example? i just tested sdk 46 project with reanimated (also a JSI module) and it works for me. i'm happy to reopen and help with this if you could provide us an example.

**Comment by DomiR** [comment]
One example would be https://github.com/DomiR/react-native-measure-text

I've used create-expo-module and the example is not loading.

**Comment by Kudo** [comment]
@DomiR because npm will install the [peerDependencies](https://github.com/DomiR/react-native-measure-text/blob/fd391df34d3474b57fa16808e2337eaced674ee8/package.json#L44). in your case, the `node_modules/react-native` is 0.70 and `example/node_modules/react-native` is 0.69. metro seems to reference wrong files and show these error messages in adb log:

```
          ReactNativeJS  E  Invariant Violation: Failed to call into JavaScript module method HMRClient.setup(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
                         E          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
                         E  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
                         E          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
                         E  Invariant Violation: Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
                         E          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
                         E  Invariant Violation: No callback found with cbID 0 and callID 0 for module <unknown>. Args: '[{"app_state":"active"}]'
                         E  Invariant Violation: Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
                         E          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

you could try to use yarn in your repo and that should work for you.

**Comment by DomiR** [comment]
Oh, wow. Thanks @Kudo for looking into this.

I usually use yarn and have it installed but this was created via `npx create-expo-module test-expo-module` which seems to use npm in this case then: 
https://github.com/expo/expo/blob/main/packages/create-expo-module/src/resolvePackageManager.ts

It sets up the lib like this:
```json
  "dependencies": {},
  "devDependencies": {
    "expo-module-scripts": "^2.1.1",
    "expo-modules-core": "^0.11.4"
  },
  "peerDependencies": {
    "expo": "*",
    "react": "*",
    "react-native": "*"
  }
```

[Callstacks bob](https://github.com/callstack/react-native-builder-bob) adds react-native as dev dependency to pin the version. Why not do the same here?

I would expect `create-expo-module` to set it up correctly.

 Binaries:
    Node: 18.9.0
    Yarn: 1.22.19
    npm: 8.19.1

Nevertheless thank you very much!

**Comment by devDoubleH** [comment]
> @DomiR because npm will install the [peerDependencies](https://github.com/DomiR/react-native-measure-text/blob/fd391df34d3474b57fa16808e2337eaced674ee8/package.json#L44). in your case, the `node_modules/react-native` is 0.70 and `example/node_modules/react-native` is 0.69. metro seems to reference wrong files and show these error messages in adb log:
> 
> ```
>           ReactNativeJS  E  Invariant Violation: Failed to call into JavaScript module method HMRClient.setup(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
>                          E          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
>                          E  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
>                          E          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
>                          E  Invariant Violation: Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
>                          E          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
>                          E  Invariant Violation: No callback found with cbID 0 and callID 0 for module <unknown>. Args: '[{"app_state":"active"}]'
>                          E  Invariant Violation: Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
>                          E          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> ```
> 
> you could try to use yarn in your repo and that should work for you.

thank you very much all errors gone when I switched to yarn
