### ISSUE TITLE
Error - can’t use XDE on macOS Sierra: Simulator not installed

### ISSUE THREAD

**Issue by LAITONEN** [expo/expo#1836]
Getting this error, when trying to run a project on iOS simulator:
<img width="505" alt="screen shot 2018-06-06 at 10 45 24 am" src="https://user-images.githubusercontent.com/23742868/41049298-470ae26e-69b9-11e8-93e1-5d58032d4ba5.png">

Everything has been working fine before 2-3 days ago. I have the latest Xcode for Sierra installed. The next version is for High Sierra. Upgrading to High Sierra is not an option.

No help from forums: https://forums.expo.io/t/cant-use-xde-on-macos-sierra-simulator-not-installed/10392

**Comment by nikki93** [comment]
Hi -- I responded to your forum post, we could continue the discussion there. Thank you!
