### ISSUE TITLE
EAS SDK46 package install

### ISSUE THREAD

**Issue by maitriyogin** [expo/expo#18362]
### Summary

Hi,
I've just been upgrading to sdk46, app builds and works great locally. 

Moving onto eas build I get a very weird error when installing packages.
(app is within a yarn workspace, using the expo-yarn-workspaces lib)

**Spin up build environment**:
```
Creating new worker instance
Using VM template "macos-monterey-12.3-xcode-13.3" running macOS Monterey 12.3
Installed software:
- Xcode 13.3.1 (13E500a)
- Node.js 16.13.2
- Yarn 1.22.17
- pnpm 7.0.0
- npm 8.1.2
- fastlane 2.205.2
- CocoaPods 1.11.3
- Ruby 2.7
- Expo CLI 5.4.9
Project environment variables:
  OMNI_ENV=dev
  ENVIRONMENT=dev
EAS Build environment variables:
  PATH=/Users/expo/.nvm/versions/node/v16.13.2/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  FASTLANE_XCODE_LIST_TIMEOUT=30
  HOME=/Users/expo
  XPC_SERVICE_NAME=host.exp.worker
  XPC_FLAGS=0x0
  LOGNAME=expo
  USER=expo
  SHELL=/bin/zsh
  TMPDIR=/var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T/
  SHLVL=0
  PWD=/usr/local/eas-build-worker
  OLDPWD=/usr/local/eas-build-worker
  NVM_CD_FLAGS=-q
  NVM_DIR=/Users/expo/.nvm
  NVM_BIN=/Users/expo/.nvm/versions/node/v16.13.2/bin
  NVM_INC=/Users/expo/.nvm/versions/node/v16.13.2/include/node
  _=/Users/expo/.nvm/versions/node/v16.13.2/bin/node
  __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
  CI=1
  EAS_BUILD=true
  NPM_CACHE_URL=http://10.254.24.9:4873
  EAS_BUILD_NPM_CACHE_URL=http://10.254.24.9:4873
  EAS_BUILD_PROFILE=dev
  EAS_BUILD_GIT_COMMIT_HASH=7a8e36cfb8606fd82c078589344fb4bbb2d8055c
  EAS_BUILD_ID=d102fa54-fb24-41ef-b1f4-8626d48fb534
  LANG=en_US.UTF-8
  EAS_BUILD_WORKINGDIR=/Users/expo/workingdir/build
  EAS_BUILD_USERNAME=stephenwhitevcc
Builder is ready, starting build
```

**Install dependencies**:
```
We detected that 'em-app' is a yarn workspace
Running "yarn install" in the root dir of your repository 
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[stderr] 
error "node_modules/@react-native-picker/picker": Tarball is not in network and can not be located in cache (["/Users/expo/workingdir/build/node_modules/@react-native-picker/picker","/Users/expo/Library/Caches/Yarn/v6/npm-@react-native-picker-picker-2.4.2/node_modules/@react-native-picker/picker/.yarn-tarball.tgz"])
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[stderr] 
warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
yarn exited with non-zero code: 1
```

I've disabled the cache in eas.json as the deps need refreshing ...:
```
 "dev": {
      "env": {
        "ENVIRONMENT": "dev",
        "OMNI_ENV":"dev"
      },
      "cache": {
        "disabled": true,
        "key": "46_1"
      },
      "releaseChannel": "develop",
      "distribution": "store",
      "developmentClient": false,
      "android": {
        "buildType": "app-bundle",
        "autoIncrement": true
      },
      "ios": {
        "autoIncrement": true
      }
    },
```

Feels like yarn isn't hitting the network or something ...?

Any ideas would be supremely appreciated,
Stephen.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

46

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/stephenwhite/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-31 | ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0-beta.6 => 46.0.0-beta.6 
      react-native: 0.69.1 => 0.69.1 
    npmGlobalPackages:
      eas-cli: 0.55.1
    Expo Workflow: managed

### Reproducible demo

demo is a bit difficult here as it's an eas build ...

**Comment by brentvatne** [comment]
this looks like it might have been an intermittent issue with the npm registry. are you still experiencing this?

**Comment by maitriyogin** [comment]
Hiya, yeah I think so although it could have been entwined in 

https://github.com/expo/expo/issues/18319
https://github.com/react-native-community/cli/pull/1655

I'm trying to resolve the D3 issue, so I'll close this.

Huge thanks for giving it a perusal.
/Stephen.
