### ISSUE TITLE
[SDK-46] App crashes immediately after upgrading to EXPO SDK 46

### ISSUE THREAD

**Issue by redpandatronicsuk** [expo/expo#18364]
### Summary

After upgrading to EXPO SDK 46 my app crashes immediately when opening it from the dev client, without printing any error messages to the terminal.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
      Yarn: 1.22.19 - ~/Toptal/Tsumu/tsumu/node_modules/.bin/yarn
      npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.0-beta.6 => 46.0.0-beta.6
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.1 => 0.69.1
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: bare

### Reproducible demo

In a bare expo app:

```
expo install react-native-firebase
// configure firebase
yarn run ios
```

The app should build and install and open the dev client. But then opening the app from the development server will crash the app.

## Extra info:

Running `expo doctor` gives:

```
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
```

`yarn why @expo/config-plugins`:

```
=> Found "@expo/config-plugins@5.0.0"
info Has been hoisted to "@expo/config-plugins"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "@expo#config#@expo#config-plugins"
   - Hoisted from "expo-apple-authentication#@expo#config-plugins"
   - Hoisted from "expo-barcode-scanner#@expo#config-plugins"
   - Hoisted from "expo-build-properties#@expo#config-plugins"
   - Hoisted from "expo-camera#@expo#config-plugins"
   - Hoisted from "expo-dev-client#@expo#config-plugins"
   - Hoisted from "expo-media-library#@expo#config-plugins"
   - Hoisted from "expo-notifications#@expo#config-plugins"
   - Hoisted from "expo-system-ui#@expo#config-plugins"
   - Hoisted from "expo-updates#@expo#config-plugins"
   - Hoisted from "expo#@expo#cli#@expo#config-plugins"
   - Hoisted from "expo-splash-screen#@expo#prebuild-config#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-launcher#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-menu#@expo#config-plugins"
   - Hoisted from "expo#expo-file-system#@expo#config-plugins"
info Disk size without dependencies: "1.97MB"
info Disk size with unique dependencies: "3.61MB"
info Disk size with transitive dependencies: "6.98MB"
info Number of shared dependencies: 46
=> Found "@react-native-firebase/app#@expo/config-plugins@4.1.5"
info This module exists because "@react-native-firebase#app" depends on it.
info Disk size without dependencies: "1.6MB"
info Disk size with unique dependencies: "3.24MB"
info Disk size with transitive dependencies: "6.62MB"
info Number of shared dependencies: 46
=> Found "@react-native-firebase/crashlytics#@expo/config-plugins@4.1.5"
info This module exists because "@react-native-firebase#crashlytics" depends on it.
info Disk size without dependencies: "1.6MB"
info Disk size with unique dependencies: "3.24MB"
info Disk size with transitive dependencies: "6.62MB"
info Number of shared dependencies: 46
=> Found "@expo/dev-server#@expo/config-plugins@4.1.5"
info Reasons this module exists
   - "expo#@expo#cli#@expo#dev-server#@expo#metro-config#@expo#config" depends on it
   - Hoisted from "expo#@expo#cli#@expo#dev-server#@expo#metro-config#@expo#config#@expo#config-plugins"
info Disk size without dependencies: "1.87MB"
info Disk size with unique dependencies: "3.51MB"
info Disk size with transitive dependencies: "6.89MB"
info Number of shared dependencies: 46
```

Could the crash be because the @react-native-firebase dependencies require @expo/config-plugins@4.1.5?

I think v15 of react-native-firebase is not compatible with RN18 yet. I'll try updating react-native-firebase anyways and update here if I have any luck.

**Comment by redpandatronicsuk** [comment]
Upgrading react-native-firebase to v15 did not work and even the latest version still depends on @expo/config-plugins@4.1.5.

I've run the app through Xcode now to see the runtime logs and the last lines in the log after the app crashes are:

```
EXDevLauncher/ExpoDevLauncherReactDelegateHandler.swift:79: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2022-07-25 15:51:29.657202+0200 tsumu[73602:67521825] EXDevLauncher/ExpoDevLauncherReactDelegateHandler.swift:79: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

**Comment by brentvatne** [comment]
@redpandatronicsuk - can you provide a minimal reproducible example?

**Comment by barthap** [comment]
I'm not sure if `react-native-firebase` is causing the crash, but the fact is that its latest version still uses `@expo/config-plugins@4.1.5`:
https://github.com/invertase/react-native-firebase/blob/8fb859fb000d5c2c6bbb81dffc685e94ef1ba350/packages/app/package.json#L59

A minimal reproducible example would be helpful here, otherwise it's just guessing.

If the `@expo/config-plugins` package is the one causing trouble, the workaround you can try is to force its version to `^5.0.0` using [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/).

> Side note, FYI. [React Native Firebase v15 had an iOS breaking change](https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#1500-2022-06-20) which affects Expo on iOS. It has issues with RN 0.69 and doesn't work with Flipper.

**Comment by redpandatronicsuk** [comment]
@barthap thanks for looking into this. I've been working on a reproducible demo for the last few hours, but couldn't reproduce the crash I see in my app. I agree though that it doesn't look like `react-native-firebase` is the culprit. Because in the demo I'm working on, the `react-native-firebase` dependencies were the first ones I added and they didn't crash the app. Then I copied one-by-one more native dependencies over and rebuilding the project to find out which exactly causes the crash. That took too long, so I copied over all dependencies just to see if I can reproduce the error. I'm still waiting for that build to complete…
I'll try what you have suggested with `@expo/config-plugins`, maybe that fixes the issue.

**Comment by redpandatronicsuk** [comment]
I got it working now, thanks for your help @barthap!

**Comment by amin79** [comment]
> I got it working now, thanks for your help @barthap!

Could you please let me know how did you fix it?

**Comment by adeyeanqar** [comment]
I do not recommend upgrading just yet. Version 46 removes node_modules folder and "package-lock.json".

**Comment by hirbod** [comment]
> I do not recommend upgrading just yet. Version 46 removes node_modules folder and "package-lock.json".

Thats not true. And even if they would've been deleted, they are not important by any means. A simple `yarn` or `npm i` will bring them back

**Comment by Stevemoretz** [comment]
> I do not recommend upgrading just yet. Version 46 removes node_modules folder and "package-lock.json".

You probably have upgraded to yarn v2 as well, that's not related to expo, yarn v2 removes that folder.

**Comment by AlenToma** [comment]
Was able to fix it by installing those version below
```json
    "@react-native-firebase/app": "~15.4.0",
    "@react-native-firebase/auth": "~15.4.0",
    "@react-native-firebase/database": "~15.4.0",
    "@react-native-firebase/firestore": "~15.4.0",
    "@expo/config-plugins": "^5.0.1",

```
