### ISSUE TITLE
[expo-in-app-purchase] how to remove “you’re all set” message when successful purchases

### ISSUE THREAD

**Issue by 19424056** [expo/expo#18360]
### Summary

I was curious if anyone knew of a way to remove the "You're All Set" message that pops after a successful IAP. In my app, I am showing my own custom message (which shows right after the "You're All Set" one), but I'd prefer to not have two messages popping if possible.

![F822A3A7-366A-41BB-9CD3-3E7C3807A75A](https://user-images.githubusercontent.com/60703498/180694763-636dbbf4-714f-4433-be19-84e6a0fecfd2.jpeg)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45.0.6

### Environment

System:
OS: macOS 12.0.1
CPU: (8) arm64 Apple M1
Memory: 93.42 MB / 16.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 18.2.0 - /opt/homebrew/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 8.9.0 - /usr/local/bin/npm
Watchman: 2022.05.23.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK: Not Found
IDEs:
Android Studio: 2021.2 AI-212.5712.43.2112.8512546
Xcode: 13.4/13F17a - /usr/bin/xcodebuild
Languages:
Java: 11.0.15 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.0.0 => 18.0.0
react-native: 0.69.1 => 0.69.1
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

npmPackages:
react (18.0.0)
react-native (0.69.1)
react-native-webview (11.22.4)
expo 45.0.6
expo-application (4.1.0)
expo-constants (13.1.1)
expo-file-system (14.0.0)
expo-font (10.1.0)
expo-image-loader (3.2.0)
expo-image-manipulator (10.3.1)
expo-in-app-purchases (13.0.0)
expo-location (14.2.2)
expo-modules-core (0.9.2)

### Reproducible demo

None

**Comment by buidinhmanh14799** [comment]
same question
