### ISSUE TITLE
About the latest version of the apple store download expro problem

### ISSUE THREAD

**Issue by giantss** [expo/expo#1837]
![image](https://user-images.githubusercontent.com/13778798/41082757-efb3293c-6a61-11e8-891b-a0be72a6fc07.png)

![image](https://user-images.githubusercontent.com/13778798/41082663-aaa2d824-6a61-11e8-956e-746033d3b63a.png)

**Comment by DeanmvSG** [comment]
@giantss This was removed intentionally as per this post - https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a
