### ISSUE TITLE
[SDK 45] [Android] [Bare] npx react-native run-android in debug mode results in "BatchedBridge" error

### ISSUE THREAD

**Issue by wen-kai** [expo/expo#18375]
### Summary

After ejecting a fresh expo sdk45 project and running `npx react-native run-android` results in `Could not get BatchedBridge, make sure your bundle is packaged correctly.` error on both emulator and physical device. Running `npx react-native run-android --variant=release` builds, installs, and runs the app as expected without error.

![image](https://user-images.githubusercontent.com/1305459/180866630-b767b6ef-e6d3-4728-811e-10826a7fe310.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: bare

### Reproducible demo

- Create new expo app: `npx create-expo-app my-app`
- Eject: `expo eject`
- Run `npx react-native run-android` on physical device or emulator
- Actual: "Could not get BatchedBridge, make sure your bundle is packaged correctly." shows from metro bundler log.
- Expected: App should load without error.

**Comment by Kudo** [comment]
hi there! i tried your steps and it works for me. you may provide a git repository to your minimal reproducible example. i'm happy to help and reopen the issue if we could reproduce the error.
```
npx create-expo-app my-app
expo eject
npx react-native run-android
```

**Comment by wen-kai** [comment]
thanks for trying!
for anyone else who may run into this:
i had updated to macOS Monterey for the sdk45 upgrade and it looks like my port 8081 is now in use.
the issue was resolved by specifying a different port via
`npx react-native run-android --port 8082`
