### ISSUE TITLE
ForegroundService notification in startLocationUpdatesAsync on android stays even when app get closed 

### ISSUE THREAD

**Issue by AlonWiezer** [expo/expo#18371]
### Summary

actual behavior - ForegroundService notification in startLocationUpdatesAsync in expo-location stays even when app get closed on android.
 sometimes even when disappear when you close the app after few hours its appear again.
expected behavior - forground service notification disappear when app its closed.

very critical as users feel we are trying to track their location.
locations permissions are on "all the time".
battery optimizations on our app is off (as we need good tracking on background)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

.

### Reproducible demo

.

**Comment by pschreibs85** [comment]
I think this is required by android. How do you turn off battery optimizations? Is there an easy interface for this?
