### ISSUE TITLE
expo and cmisJS - Error: TypeError: undefined is not an object (evaluating 'self.atob.bind')

### ISSUE THREAD

**Issue by Martze96** [expo/expo#18383]
### Summary

Currently I am working on the mobile application with react native and expo that should be able to login to the CMIS Server at first.

I have found a Library that could help me out with that:

[](https://www.npmjs.com/package/cmis)

When I install it (npm i cmis), and import it like that (as doc states):

`import {cmis} from 'cmis'`

and want to use it like that as the documentation states:

`import { cmis } from 'cmis';

export default function RepoManager({ navigation }) {

  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [modalVisible, setModalVisible] = useState(true);

  useEffect(() => {
    let session = new cmis.CmisSession('https://localhost/cmis/browser');
    console.log(session);

  }, [])
....
....`

I get the following Error:

`TypeError: undefined is not an object (evaluating 'self.atob.bind')
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:4 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:13 in tryCatch
at node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:31 in <anonymous>
at node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:13 in tryCatch
at node_modules\@babel\runtime\helpers\regeneratorRuntime.js:124:27 in invoke
at node_modules\@babel\runtime\helpers\regeneratorRuntime.js:130:16 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:248:12 in _allocateCallback$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:112:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:162:14 in _callReactNativeMicrotasksPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:413:41 in callReactNativeMicrotasks
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:391:6 in __callReactNativeMicrotasks
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:133:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:368:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:132:4 in flushedQueue`

And on Android Emulator (also same on hardware):

![image](https://user-images.githubusercontent.com/85078085/181068239-285863c6-8e2e-4404-8963-cd7eb61c3d9d.png)

It seems it has something to do with requireJS or something with base64 idk....

Outside expo it does work. How do I fix that?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS, Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare

### Reproducible demo

install cmisJS to expo environment:

`npm install cmis`

import it into any component or JS File:

`import {cmis} from 'cmis'`

Error appears immediately after import

**Comment by brentvatne** [comment]
https://www.npmjs.com/package/cmis

> A CMIS typescript/javascript library for node and browser, with no dependencies for modern browsers

they do not explicitly support react-native and it seems like it depends on apis that are not available in react-native
