### ISSUE TITLE
[SDK 46] expo-build-properties in custom dev client leads to build error

### ISSUE THREAD

**Issue by mlecoq** [expo/expo#18397]
### Summary

Using `expo-build-properties` with the following configuration in `app.json` (needed in one of my projects for `react-native-firebase`)

```
["expo-build-properties", {"ios": {"useFrameworks": "dynamic"}}]
```

leads to the following error while build custom dev client

```
  error: Multiple commands produce '/Users/mlecoq/Library/Developer/Xcode/DerivedData/buildIssue-gbpimdiuimzzgjfjovhgjfixvrfb/Build/Intermediates.noindex/ArchiveIntermediates/buildIssue/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h'
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

```
 "expo": "^46.0.1",
 "expo-build-properties": "~0.3.0",
 "expo-dev-client": "^1.1.1",
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/69834_1658836725379/bin/node
      Yarn: 1.22.15 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/69834_1658836725379/bin/yarn
      npm: 8.1.2 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/69834_1658836725379/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.1 => 46.0.1 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.6.0
    Expo Workflow: managed

### Reproducible demo

Example app here : https://github.com/mlecoq/expoBuildIssue/tree/sdk46

### Stacktrace (if a crash is involved)

 duplicate output file '/Users/mlecoq/Library/Developer/Xcode/DerivedData/buildIssue-gbpimdiuimzzgjfjovhgjfixvrfb/Build/Intermediates.noindex/ArchiveIntermediates/buildIssue/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h' on task: CpHeader /Users/mlecoq/Library/Developer/Xcode/DerivedData/buildIssue-gbpimdiuimzzgjfjovhgjfixvrfb/Build/Intermediates.noindex/ArchiveIntermediates/buildIssue/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/eas-build-local-nodejs/fb938a77-6dc4-4a99-a340-8df3ac0e8e8b/build/node_modules/expo-dev-menu/vendored/react-native-reanimated/ios/DevMenuRNGestureHandlerStateManager.h (in target 'expo-dev-menu' from project 'Pods')

**Comment by RodriguesCosta** [comment]
I had the same problem but I solved it by following this tip.

> A workaround is to downgrade `expo-dev-client` to `~1.0.1` and `expo-updates` to `~0.13.3` which is of course not ideal.

_Originally posted by @thespacemanatee in https://github.com/expo/expo/issues/18305#issuecomment-1189828736_

**Comment by imjlk** [comment]
I also have same issue, Did you try run with `expo r -c` and then Press i for open iOS simulator? It's working for me, but open with Expo Go on my iOS simulator.

By the way, I change the start script to `expo start  --dev-client` on package.json

**Comment by ahnafnafee** [comment]
> I had the same problem but I solved it by following this tip.
> 
> > A workaround is to downgrade `expo-dev-client` to `~1.0.1` and `expo-updates` to `~0.13.3` which is of course not ideal.
> 
> _Originally posted by @thespacemanatee in [#18305 (comment)](https://github.com/expo/expo/issues/18305#issuecomment-1189828736)_

Downgrading causes build failures for Android on my end

**Comment by sydni** [comment]
I am encountering the same error - my build properties are below.  

```
      "expo-build-properties",
      {
        "ios": {
          "useFrameworks": "static"
        }
      }
```

**Comment by amin79** [comment]
For me it seems that it's not compatible with react-native-reanimated.

I get this error since I upgraded to expo 46.0.0.
Upgrading to expo 46.0.2 also did not solve the problem.

duplicate output file '/Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/expo-dev-menu/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h' on task: CpHeader /Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/expo-dev-menu/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h /Users/expo/workingdir/build/node_modules/expo-dev-menu/vendored/react-native-reanimated/ios/DevMenuRNGestureHandlerStateManager.h (in target 'expo-dev-menu' from project 'Pods')

**Comment by TowhidKashem** [comment]
I was also using build properties to support rn-firebase plugin but now am using this custom one instead:

**firebase-mods.js:**

```
const { withDangerousMod, withPlugins } = require('@expo/config-plugins');
const {
  mergeContents
} = require('@expo/config-plugins/build/utils/generateCode');
const fs = require('fs');
const path = require('path');

async function readFileAsync(path) {
  return fs.promises.readFile(path, 'utf8');
}

async function saveFileAsync(path, content) {
  return fs.promises.writeFile(path, content, 'utf8');
}

const withFirebaseMods = (c) => {
  return withDangerousMod(c, [
    'ios',
    async (config) => {
      const file = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      const contents = await readFileAsync(file);
      await saveFileAsync(file, addFirebaseConfigsToPodFile(contents));
      return config;
    }
  ]);
};

function addFirebaseConfigsToPodFile(src) {
  return mergeContents({
    tag: 'firebase-mods',
    src,
    newSrc: `
# install react-native-firebase as a static framework
$RNFirebaseAsStaticFramework = true
pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
`,
    anchor: /platform :ios/,
    offset: 0,
    comment: '#'
  }).contents;
}

module.exports = (config) => withPlugins(config, [withFirebaseMods]);
```

**app.config.js:**

```
  plugins: [
    '@react-native-firebase/app',
    '@react-native-firebase/crashlytics',
    '@react-native-firebase/perf',
    './plugins/firebase-mods'
  ]
```

working fine for me on sdk 46, @react-native-firebase 15.2 and expo config-plugins 5.0

**Comment by helferleinsoftware** [comment]
> I am encountering the same error - my build properties are below.
> 
> ```
>       "expo-build-properties",
>       {
>         "ios": {
>           "useFrameworks": "static"
>         }
>       }
> ```

For me the issue was gone when changing
`"expo-dev-client": "^1.0.1"`
to
`"expo-dev-client": "~1.0.1"`
via 
`expo doctor --fix-dependencies`

After that, the build step _Run expo doctor_ within EAS stopped complaining
`[stderr] 
[04:26:46]  - expo-dev-client - expected version: ~1.0.1 - actual version installed: 1.1.1`

I am on managed workflow with SDK 45, not using expo-updates.

**package.json**
```
"@react-native-firebase/analytics": "^15.2.0",
"@react-native-firebase/app": "^15.2.0",
"@react-native-firebase/crashlytics": "^15.2.0",
"expo-build-properties": "~0.2.0",
"expo-dev-client": "~1.0.1",
```

**app.json**
```
"plugins": [
      "@react-native-firebase/app",
      "@react-native-firebase/crashlytics",
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ]
```

**Comment by jorgebaraltq** [comment]
how can we get this fix into our packages? @lukmccall

**Comment by lukmccall** [comment]
You can use a patch package to apply diff or wait for a new version. It should be available soon ;)

**Comment by deathemperor** [comment]
this is causing our eas builds to fail.

`error: Multiple commands produce '/Users/expo/Library/Developer/Xcode/DerivedData/PapayaCare-dyeakgyhplovuogievxvbunpgsio/Build/Intermediates.noindex/ArchiveIntermediates/PapayaCare/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h'`

https://expo.dev/accounts/papaya-insurtech/projects/papaya-care/builds/5b2b5cd1-aec7-4b49-8dab-4759682ce3f2

Would love a release ASAP

**Comment by lukmccall** [comment]
Hi @deathemperor, the new version is live - `expo-dev-client@1.2.0`

**Comment by deathemperor** [comment]
> Hi @deathemperor, the new version is live - `expo-dev-client@1.2.0`

thanks. can confirm it solves!

**Comment by kelechionyeama** [comment]
Hey , anyone else still having this issue? I downloaded the new version and it still persists

**Comment by bayramn** [comment]
> I am encountering the same error - my build properties are below.
> 
> ```
>       "expo-build-properties",
>       {
>         "ios": {
>           "useFrameworks": "static"
>         }
>       }
> ```

Same here as well.

**Comment by bayramn** [comment]
> expo-dev-client

I still have for some reason, did you have plugin object for `expo-build-properties`:

`"expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }`

**Comment by DICKSON-ENEH** [comment]
npx expo install expo-build-properties solved my issue easy peasy

**Comment by KleKlai** [comment]
> npx expo install expo-build-properties solved my issue easy peasy

this also resolve my issues on sdk 50 thankss
