### ISSUE TITLE
Frozen frames 0.18% of the frames took longer than 700ms to render

### ISSUE THREAD

**Issue by VishalVema** [expo/expo#1839]
i am getting this error while rolling out my app to play store 
![frozen frame](https://user-images.githubusercontent.com/22855727/41096450-43cccebe-6a72-11e8-9f3c-98be293e6ecf.PNG)
![performance](https://user-images.githubusercontent.com/22855727/41096452-445db7b2-6a72-11e8-94a6-6bc26a8f27f7.PNG)

**Comment by nikki93** [comment]
This is a performance issue internal to your app that you should be able to debug, but not a general Expo issue. If you are able to collect more information and find performance issues in Expo itself please post here.
