### ISSUE TITLE
expo-firebase-analytics not sending events on Android until device is restarted

### ISSUE THREAD

**Issue by RocketRonz** [expo/expo#18395]
### Summary

When running my app in Expo Go (dev & publish) events are appearing in the Firebase console realtime, pretty much as they happen. The same code running as a native app on various Android devices (Samsung, LG, Moto, Nokia) does not generate any events in Firebase until the phone is shutdown & started again, at which point the events appear immediately.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.4 environment info:
System:
OS: Windows 10 10.0.19044
Binaries:
Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 4.1.0.0 AI-201.8743.12.41.7042882
npmPackages:
expo: ^45.0.0 => 45.0.4
react: 17.0.2 => 17.0.2
react-dom: 17.0.2 => 17.0.2
react-native: 0.68.2 => 0.68.2
react-native-web: 0.17.7 => 0.17.7
Expo Workflow: managed

### Reproducible demo

Only happens on native Android build when calling:

Analytics.logEvent('EVENT_NAME', propsJSON);

**Comment by RocketRonz** [comment]
Has anyone experienced this issue, or anything similar? It's been in review for almost a week. Thx.

**Comment by dmendezpdevs** [comment]
Did you find any solution? It is happening to me that it only takes the event of an android device
