### ISSUE TITLE
Unexpected url: main.proto when loading protobuf in expo

### ISSUE THREAD

**Issue by Bobbeo** [expo/expo#184]
I'm trying to use [protobufjs](https://www.npmjs.com/package/protobufjs) with Expo.

I place the following in my Main.js file:
```
var protobuf = require("protobufjs");

protobuf.load("main.proto", function (err, root) {
    //
});
```

I get the following error displayed when running the expo App:
```
unexpected url: main.proto
url
    Request.java:141
sendRequest
    NetworkingModule.java:174
invoke
    Method.java:-2
invoke
    BaseJavaModule.java:345
invoke
    JavaModuleWrapper.java:141
run
    NativeRunnable.java:-2
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:196
run
    Thread.java:761
```

**Comment by jesseruder** [comment]
What exactly are you trying to do with the library? It looks like `protobuf.load` expects a filename https://github.com/dcodeIO/protobuf.js#using-proto-files. Where do you have that file?

**Comment by Bobbeo** [comment]
First, I am trying to load the proto file.

I have placed the file in the same folder as main.js.

I have also tried loading the file itself (not sure if this will help).

var pFile = require('./main.proto');

I get the following error:
```
The development server returned response error code: 500

URL: http://packager.5u-dsj.bobbeo.my-new-project16.exp.direct/main.bundle?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles

Body:
{"from":"C:\\Users\\A\\my-new-project16\\main.js","to":"./assets/main.proto","message":"Unable to resolve module `./assets/main.proto` from `C:\\Users\\A\\my-new-project16\\main.js`: Directory C:\\Users\\A\\my-new-project16\\assets\\main.proto doesn't exist","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
onResponse
    DevServerHelper.java:363
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:761


```

Thanks.

**Comment by terribleben** [comment]
Have you tried adding `proto` to the `packagerOpts.assetExts` field of your project's `exp.json`?

**Comment by terribleben** [comment]
Closing because this hasn't gone anywhere - if you think this is a bug in Expo, please reopen with more info so we can diagnose; if you need help with your project, please open a topic on forums.expo.io
