### ISSUE TITLE
`Invalid view returned from registry, expecting EXVideo, got: (null)`

### ISSUE THREAD

**Issue by KrisLau** [expo/expo#18402]
### Summary

After moving from expo unimodules to expo modules and updating my expo-av package from 9.1.2 to 12.0.2, I keep getting an intermittent `Invalid view returned from registry, expecting EXVideo, got: (null)` error:
```
<Video
  isLooping
  shouldPlay
  resizeMode={'cover'}
  useNativeControls={false}
  source={{
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  }}
/>
```

I also upgraded a bunch of other packages including react-native. I did not get these errors prior to upgrading my packages. The only other issue I could find #3115 but it didn't have a resolution.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46.0.1

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: 46.0.1 => 46.0.1 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: ^0.69.3 => 0.69.3 
    npmGlobalPackages:
      expo-cli: 6.0.0
    Expo Workflow: bare
```

### Reproducible demo

I couldn't set the versions to my package versions so the error isn't showing up

https://snack.expo.dev/@kris_lau/hazardous-stroopwafel

**Comment by KrisLau** [comment]
Is it related to this?

https://github.com/expo/expo/commit/404313c0249a7cee12bed6a54f9ba45849970c59

**Comment by barthap** [comment]
Could you show a stacktrace of this error? Commit you linked is mentioned to fix the issue.

**Comment by KrisLau** [comment]
Stack trace:
```
Error: Invalid view returned from registry, expecting EXVideo, got: (null)
  File "app:///NativeModules.js", col 50, in promiseMethodWrapper
  File "app:///NativeModulesProxy.native.js", col 41, in Object.keys.forEach$argument_0
  File "app:///Video.js", col 8, in loadAsync
  File "app:///Video.js", col 17, in _handleNewStatus
  File "[native code]", in generatorResume
  File "app:///asyncToGenerator.js", col 15, in asyncGeneratorStep
  File "app:///asyncToGenerator.js", col 26, in _next
  File "app:///asyncToGenerator.js", col 11, in Promise$argument_0
  File "app:///core.js", col 6, in tryCallTwo
  File "app:///core.js", col 22, in doResolve
  File "app:///core.js", col 11, in Promise
  File "app:///asyncToGenerator.js", col 11, in <anonymous>
  at <unknown>(app:///index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.EpicMobile:264622:27)
  File "app:///Video.js", col 16, in loadAsync
  File "[native code]", in generatorResume
  File "app:///asyncToGenerator.js", col 15, in asyncGeneratorStep
  File "app:///asyncToGenerator.js", col 26, in _next
  File "app:///asyncToGenerator.js", col 11, in Promise$argument_0
  File "app:///core.js", col 6, in tryCallTwo
  File "app:///core.js", col 22, in doResolve
  File "app:///core.js", col 11, in Promise
  File "app:///asyncToGenerator.js", col 11, in <anonymous>
  File "app:///Video.js", col 23, in constructor
  File "[native code]", in performSyncWorkOnRoot
  File "app:///scheduler.development.js", col 41, in workLoop
  File "app:///scheduler.development.js", col 21, in flushWork
  File "app:///scheduler.development.js", col 41, in performWorkUntilDeadline
  File "app:///JSTimers.js", col 12, in _allocateCallback$argument_0
  File "app:///JSTimers.js", col 14, in _callTimer
  File "app:///JSTimers.js", col 14, in _callReactNativeMicrotasksPass
  File "app:///JSTimers.js", col 41, in callReactNativeMicrotasks
  File "[native code]", in flushedQueue
  File "[native code]", in callFunctionReturnFlushedQueue
```

<br/>

> Commit you linked is intended to fix the issue.

Yeah that's really weird since I had the version that has that commit.

>
> This rejection is in fact harmless, so as a workaround for now you can ignore these logs ([see guide here](https://reactnative.dev/docs/debugging#console-errors-and-warnings)):
>

That's good to know I just want to make sure that I'm not messing something up!

**Comment by barthap** [comment]
OK, got it, reproduced, know what's wrong and will fix it today.

I made a very basic mistake 🙈  - the `unloadAsync()` is asynchronous and `try-catch` isn't working, because `componentWillUnmount` isn't `async` function.
Replacing `try { unloadAsync() } catch { }` with Promise-like `unloadAsync().catch(() => {})` solves this issue.

**Comment by KrisLau** [comment]
> Thank you!
> 
> OK, I got it, reproduced, know what's wrong and will fix it today.
> 
> I made a very basic mistake 🙈 - the `unloadAsync()` is asynchronous and `try-catch` isn't working, because `componentWillUnmount` isn't `async` function. Replacing `try { unloadAsync() } catch { }` with Promise-like `unloadAsync().catch(() => {})` solves this issue.

Ok sounds good thank you so much!

**Comment by tsapeta** [comment]
The fix for this issue is now available in version `12.0.3` 🙂

**Comment by KrisLau** [comment]
Thank you!

**Comment by elliotdickison** [comment]
I don't think this is fixed, we're getting lots of these on 13.0.1

**Comment by henrymoulton** [comment]
@elliotdickison we're still getting these as well on `"13.0.2"` and I can see it contains the fix from @barthap 

```
  componentWillUnmount() {
    // Auto unload video to perform necessary cleanup safely
    this.unloadAsync().catch(() => {
      // Ignored rejection. Sometimes the unloadAsync code is executed when video is already unloaded.
      // In such cases, it throws:
      // "[Unhandled promise rejection: Error: Invalid view returned from registry,
      //  expecting EXVideo, got: (null)]"
    });
  }
```

Can we get this re-opened?

**Comment by radko93** [comment]
Agreed with @henrymoulton for reopening, seems like it's getting reported a lot on the latest version. @tsapeta

**Comment by henrymoulton** [comment]
@tsapeta thanks for re-opening, it's still happening, I've got it happening locally too:

<img width="373" alt="image" src="https://github.com/expo/expo/assets/30093692/2d93dad8-1c35-4633-b2b6-71e8c05c4548">

**Comment by ddmc87** [comment]
> @tsapeta thanks for re-opening, it's still happening, I've got it happening locally too:
> <img alt="image" width="373" src="https://private-user-images.githubusercontent.com/30093692/284101603-2d93dad8-1c35-4633-b2b6-71e8c05c4548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDM1MzEsIm5iZiI6MTcwNDQwMzIzMSwicGF0aCI6Ii8zMDA5MzY5Mi8yODQxMDE2MDMtMmQ5M2RhZDgtMWMzNS00NjMzLWIyYjYtNzFlOGMwNWM0NTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIxMjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYmU1MTVjYmZiNzA1ZDM4MTM4NThiNGEwYmIwNGFjM2MyYzc5OWZjMTMxMjhhNjIyNjM3YjEwOTlmOTU2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A3hfzEzn6S9EyEN_lSYdbcMh7CHu4JxrHfdTkAwnDUo">

Hi Henry, it happened to you locally? I got a LOT of them in production in my Bugsnag Dashboard, but never saw it. Is it actually crashing the app or is it just a log? I am trying to resolve the issue for days now, but nothing worked so far. Upgraded RN, tried different versions of expo-av...

**Comment by megantaylor** [comment]
Please re-open, I am seeing these errors on Android a lot. Specifically in the context of Video elements in a FlatList-based carousel, where we have tried to pause the video when its not the centered element, or when the element is unmounted. 

"expo": "50.0.6",
"expo-av": "13.10.5"

**Comment by tsapeta** [comment]
@megantaylor This issue was opened for iOS, not for Android. Can you open a new issue then?
