### ISSUE TITLE
addNotificationResponseReceivedListener is not working when app is opened from killed state

### ISSUE THREAD

**Issue by m0hanraj** [expo/expo#18403]
### Summary

I have followed the example provided from [Expo notification module](https://docs.expo.dev/versions/latest/sdk/notifications/#api) to setup local push notifications. The notification linking works as expected if the app is in the background, but if the app is opened from killed state the `addNotificationResponseReceivedListener` is not fired as referred in developer documentation.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

### Reproducible demo

```
const triggerNotification = () => {
 
  Notifications.scheduleNotificationAsync({
    content: {
      title: "Notification title",
      body: `Some body content`,
      data: { name: "Joe", age: "24" },
    },
    trigger: {
      seconds: 60,
      repeats: true,
    },
  });
};



useEffect(() => {
    registerForPushNotificationsAsync().then((token) =>
      setExpoPushToken(token)
    );

    notificationListener.current =
      Notifications.addNotificationReceivedListener((notification) => {
        setNotification(notification);
      });

    responseListener.current =
      Notifications.addNotificationResponseReceivedListener((response) => {
        console.log(response);
      });

   
     triggerNotification();
  
    return () => {
      Notifications.removeNotificationSubscription(
        notificationListener.current
      );
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);
```

**Comment by m0hanraj** [comment]
Is there any update on this issue?

**Comment by m0hanraj** [comment]
@brentvatne  @wkozyra95 @dsokal @Simek @amandeepmittal Is there any update on this issue. Looks like multiple users facing the similar issue with pretty basic notification feature that doesn't work with `addNotificationResponseReceivedListener` hook if the app is not running in background

**Comment by dustinvforsyth** [comment]
I am having this same issue even if the app is in background or killed state with FCM notifications. Foregrounded app works as expected.

**Comment by Codelica** [comment]
I'm seeing this as well with Expo 46 and the compiled Android in killed/exited state.  I've tried code with addNotificationResponseReceivedListener(), useLastNotificationResponse(), and even getLastNotificationResponseAsync() in linking getInitialURL, but none of them are handed notification data if the app is coming from the exited/killed state.   Curiously I do get the notification data when using Expo Go and it's been exited.

**Comment by appsgenie** [comment]
Same issue here. I tried multiple things (including putting `useLastNotificationResponse` and `addNotificationResponseReceivedListener` at the top of the chain) and nothing seems to work. On Android standalone when app is killed it will never fire these..

**Comment by Codelica** [comment]
This should be kept open as it used to work regardless of where the listener is created.   Currently `useLastNotificationResponse` will not work on Android from killed state regardless of where it's used.  `addNotificationResponseReceivedListener` can work (we have it working in production on Android with Expo 46 as do others), but ONLY if the listener is created extremely early in the application -- BEFORE and outside any React component functions/classes.  The notification touch event then has to be retained so later code can use it.

**Comment by kartikk221** [comment]
@Codelica I am currently on Expo SDK v47 and none of the solutions above or the ones from related issues seem to fix my issue for receiving the notification response event on Android from a killed state (Lock Screen). I am testing with a real Pixel 7 running Android 13. Have you had to deal with this with the new SDK or are you still running on SDK 46?

**Comment by Codelica** [comment]
@kartikk221 I'm still in Expo 46.  Waiting on an SVG library bug in 47 to get resolved before moving.  Although it sounds like that may have been resolved, in which case I'll probably try things in a couple weeks.  (on another project at the moment).

**Comment by berkcoker** [comment]
Here's how to reproduce it: set up `expo-notifications` as described in the documentation, with remote-notification UIBackgroundModes. Then add the following code in a useEffect. Grab the Expo token on a real device and send push notifications to it using the Push notifications tool.

```
notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      // this one works
});
      
responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      // this one doesn't
});
      
return () => {
      Notifications.removeNotificationSubscription(notificationListener.current);
      Notifications.removeNotificationSubscription(responseListener.current);
};
```

Don't need too much

**Comment by emirdeliz** [comment]
Same here.

**Comment by kirtikapadiya** [comment]
same issue with expo SDK 48 on android device

**Comment by bytenaija** [comment]
This is on iOS 17.3, and SDK 49 never gets called, no matter what I do. Even when the app is foregrounded, nothing happens. When a user clicks on the badge/notification, it only brings the app to the foreground or remains on the screen you were on if the app was already in the foreground.

```import * as Notifications from 'expo-notifications';
import { router } from 'expo-router';
import React from 'react';

export function useNotificationObserver() {
  React.useEffect(() => {
    let isMounted = true;

    function redirect(notification: Notifications.Notification) {
      console.log('notification', notification);
      const url = notification.request.content.data?.url;
      if (url) {
        router.push(url);
      }
    }

    Notifications.getLastNotificationResponseAsync().then((response) => {
        if (!isMounted || !response?.notification) {
          return;
        }
      console.log(response, 'response crapssssss');
        redirect(response?.notification);
    });

    const subscription = Notifications.addNotificationResponseReceivedListener(
      (response) => {
        console.log('notification response received', response);
        redirect(response.notification);
      },
    );

    return () => {
      isMounted = false;
      subscription.remove();
    };
  }, []);
}
```

I am using expo-router

**Comment by federicogomezlara** [comment]
Having the same issue on SDK 49, both Android and iOS using react navigation

**Comment by samih-sghier** [comment]
same issue here @federicogomezlara did you find a resolution?

**Comment by pedroayres** [comment]
up any solution?

**Comment by Rorgrlrio** [comment]
Same problem here, app will open when the notification is clicked, but the redirection code inside addNotificationResponseReceivedListener won't run

**Comment by samih-sghier** [comment]
can't believe not more people are facing this issue

**Comment by Codelica** [comment]
There are more people, this particular issue is just a duplicate that's been closed.  Check out https://github.com/expo/expo/issues/14078

While there is definitely a bug, some of us have worked around it successfully by implementing a listener *very early* in the code to capture the event to be processed later.  (as you'll see in that other issue) That still works for me in Expo 49, I haven't tried 50 yet.  However, it doesn't seem to work for everyone as you'll also see in that issue.  Not sure why.

**Comment by samvoults** [comment]
same problem here

**Comment by NDelo007** [comment]
I had this problem as well, and it was sporadic. It looks like it's actually an issue with their sample code.
When they tell you to do this:
notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
    setNotification(notification);
  });

It won't work. The issue is, they also tell you to call the local notification variable to have the same name. So the app is getting confused. Once I changed the variable name here, it worked.

notificationListener.current =
      Notifications.addNotificationReceivedListener((noti) => {
        setNotification(noti);
      });

**Comment by next6leo** [comment]
any update on this i having same issue in SDK 51, SDK 49 is ok

**Comment by Codelica** [comment]
@next6leo you'll see a note [here](https://docs.expo.dev/versions/latest/sdk/notifications/#notification-events-listeners) in the docs, but basically move to the `useLastNotificationResponse` hook.

**Comment by next6leo** [comment]
@Codelica yes thank you just found it also When the app is not running or killed and is restarted by tapping on a notification, the NotificationResponseReceivedListener may or may not be triggered. To reliably capture the response, we recommend using useLastNotificationResponse or getLastNotificationResponseAsync.

**Comment by upnorth** [comment]
> @next6leo you'll see a note [here](https://docs.expo.dev/versions/latest/sdk/notifications/#notification-events-listeners) in the docs, but basically move to the `useLastNotificationResponse` hook.

The documentation should be extended with more examples from this. As it's currently written, you get the impression that `Notifications.addNotificationReceivedListener` and `Notifications.addNotificationResponseReceivedListener` is all that you will ever need.

I hadn't seen the other hooks until you linked to them here. Thanks for that though!

**Comment by upnorth** [comment]
Did a quick test and this works for me from a killed state on Android (I use any interaction with a notification to trigger a navigation, which currently is just it being pressed to open the app):

```
export default function App() {
  const notificationListener = useRef<Notifications.Subscription>();
  const responseListener = useRef<Notifications.Subscription>();

  const oldNotificationResponse = Notifications.useLastNotificationResponse()

  useEffect(() => {
    registerForPushNotificationsAsync()
      .then((token) => setExpoPushToken(token ?? ""))
      .catch((error) => console.error(error));

    notificationListener.current =
      Notifications.addNotificationReceivedListener((notification) => {
        console.log(`Notification recieved: ${JSON.stringify(notification)}`);
      });

    responseListener.current =
      Notifications.addNotificationResponseReceivedListener(() => {
        console.log("App opened with notification")
        // Do stuff with it
      });

      if(oldNotificationResponse?.notification) {
        console.log("App opened with notification")
         // Do stuff with it
      }

    return () => {
      notificationListener.current &&
        Notifications.removeNotificationSubscription(
          notificationListener.current
        );
      responseListener.current &&
        Notifications.removeNotificationSubscription(responseListener.current);
    };
  });
```
