### ISSUE TITLE
Expo hanging on launch (CLI and XDE)

### ISSUE THREAD

**Issue by jcbreel** [expo/expo#1840]
I'm unable to run expo on my computer for some reason.
It stops right after setting up the Metro Bundler:

`15:01:36 [exp] Using project at /Users/jcbihanic/Documents/code/my-new-project`
`15:01:44 [exp] Scanning folders for symlinks in /Users/jcbihanic/Documents/code/my-new-project/node_modules (13ms)`
`15:01:44 [exp] Starting Metro Bundler on port 19001.`
`15:01:44 [exp] Metro Bundler ready.`
 
Any idea what I'm missing?

### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/jcbihanic-776ff66d-104c-4ace-b222-28d0cc02d1af.tar.gz

**Comment by anp** [comment]
Hi! What command are you running that causes this? Have you attempted to open the project on your phone or simulator?

**Comment by jcbreel** [comment]
It's just running `exp start`, on a fresh project.
So unsure what's going wrong...

**Comment by terribleben** [comment]
Are you able to open the project on your phone or simulator?

**Comment by jcbreel** [comment]
No, literally just creating the project as per the doc on the "get started" page.

`exp init my-new-project`
`cd my-new-project`
`exp start`

It hangs on `exp start`

**Comment by jasongillespie** [comment]
I had the exact same issue.  Here is what I did:

Go to Network Preferences on your mac, select your ethernet or wifi connection.  Under "Configure IPv4" Choose "Manually" and create a static IP address for your computer.

**Comment by jcbreel** [comment]
Interesting @jasongillespie ...

I have made those changes and still getting the same error.

**Comment by vincentleeuwen** [comment]
I have exactly the same issue, both XDE and command line...

**Comment by hamzachaouch** [comment]
hey ,
i m having an issue when i try : exp build-android it 's saying to me to enter a password and after the a username , i already putted my login and password many time but it doesn't work , i m running it on windows 10 cmd ...
i reseted my password several times but it s always the same problem...
any help plz?

**Comment by brentvatne** [comment]
@vincentleeuwen - do you have watchman installed?

**Comment by vincentleeuwen** [comment]
@brentvatne No will install watchman now. I got the XDE working again in the end, but not really sure what I did to get it working again (tried a few things and didn't record them properly unfortunately).

**Comment by strafton** [comment]
Is there any resolution to this.  I have the same thing happening. I downloaded and installed the IDE. 
When I tried to create the first project, it just hangs.. No logs..nothing.  Watchman is installed .
![screen shot 2018-08-21 at 8 53 07 am](https://user-images.githubusercontent.com/8325241/44402406-aa07b080-a51f-11e8-8613-418a08610ee4.png)

**Comment by TheInternet** [comment]
I have this same issue.

**Comment by strafton** [comment]
I had to use a previous version of react-native to get it to work. The latest version will just hang.

**Comment by acomito** [comment]
@strafton which version?

**Comment by lylest** [comment]
Expo Developer Tools is disconnected from Expo CLI. Use the expo start command to start the CLI again.

**Comment by fson** [comment]
Closing this issue because it's very old and about tools that no longer exist (exp and XDE projects have been merged into Expo CLI. If you have issues with Expo CLI, please report them in https://github.com/expo/expo-cli/issues with as much information (see the issue template) as possible. Thanks!
