### ISSUE TITLE
expo doctor fails on fresh install with SDK 45

### ISSUE THREAD

**Issue by dillonhafer** [expo/expo#18401]
### Summary

`expo doctor` fails on a brand new app

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.1.12 - /opt/homebrew/bin/bash
    Binaries:
      Node: 16.0.0 - ~/.asdf/installs/nodejs/16.0.0/bin/node
      Yarn: 1.22.17 - ~/.asdf/installs/nodejs/16.0.0/.npm/bin/yarn
      npm: 8.3.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - ~/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 6.0.1
    Expo Workflow: managed
```

### Reproducible demo

```
$ npx create-expo-app my-app
$ cd my-app
$ expo doctor
Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@5.0.0
  (for more info, run: npm why @expo/config-plugins)
```

**Comment by raajnadar** [comment]
Delete lock file and regenerate it, this will get solved

**Comment by dillonhafer** [comment]
```
$ npx create-expo-app my-app
$ cd my-app
$ rm package-lock.json
$ npm i
$ expo doctor
Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@5.0.0
  (for more info, run: npm why @expo/config-plugins)
```

That does not solve the expo doctor error.

**Comment by gislawill** [comment]
We're seeing this error as well. Here's the output of `npm ls @expo/config-plugins`
```
$ npm ls @expo/config-plugins
[project]
├─┬ @config-plugins/react-native-branch@0.0.1
│ └── @expo/config-plugins@4.1.5
├─┬ @react-native-google-signin/google-signin@7.2.2
│ └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-apple-authentication@4.2.1
│ └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-av@11.2.3
│ └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-constants@13.1.1
│ └─┬ @expo/config@6.0.26
│   └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-dev-client@1.0.1
│ ├── @expo/config-plugins@4.1.5 deduped
│ ├─┬ expo-dev-launcher@1.0.1
│ │ └── @expo/config-plugins@4.1.5 deduped
│ └─┬ expo-dev-menu@1.0.1
│   └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-facebook@12.2.0
│ └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-image-picker@13.1.1
│ └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-notifications@0.15.4
│ └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-splash-screen@0.15.1
│ └─┬ @expo/prebuild-config@4.0.4
│   └── @expo/config-plugins@4.1.5 deduped
├─┬ expo-updates@0.13.3
│ ├── @expo/config-plugins@4.1.5 deduped
│ └─┬ @expo/metro-config@0.3.21
│   └─┬ @expo/config@7.0.0
│     └── @expo/config-plugins@5.0.0    [Note: This is the only 5.0.0]
├─┬ expo@45.0.6
│ ├─┬ @expo/cli@0.1.5
│ │ └── @expo/config-plugins@4.1.5 deduped
│ └─┬ expo-file-system@14.0.0
│   └── @expo/config-plugins@4.1.5 deduped
└─┬ sentry-expo@4.2.0
  └── @expo/config-plugins@4.1.5 deduped
```

**Comment by kissmystic** [comment]
same here

**Comment by kissmystic** [comment]
npm i expo@45.0.8
solved for me

**Comment by ayaanqui** [comment]
> npm i expo@45.0.8 solved for me

Tried this but unfortunately it did not help

**Comment by raajnadar** [comment]
Run this `npm why @expo/config-plugins` to see the packages dependent on `@expo/config-plugins`

In my case it was due to `expo-ads-admob` which was deprecated in SDK 45 & removed in SDK 46 was still using the old version of `@expo/config-plugins`

**Comment by felippewick** [comment]
I have the same issue. In my case it's due to `expo-updates`. I tried to re-install expo-updates with `expo install` but it didn't solve the wrong dependency. Does anyone know how to fix it?
```@expo/config-plugins@5.0.0
node_modules/expo-updates/node_modules/@expo/metro-config/node_modules/@expo/config-plugins```

**Comment by patrikmojzis** [comment]
`expo update` solved it for me

**Comment by brentvatne** [comment]
we published new versions of packages that had a loose @expo/config-plugins version dependency and locked that dependency instead. this does not happen on new projects anymore, and existing projects can run `expo doctor --fix-dependencies` to install the latest version of these packages.

**Comment by ayaanqui** [comment]
I tried running `expo doctor --fix-dependencies` and I get the same issue as before complaining about `invalid: @expo/config-plugins@5.0.0`. I'm still using SDK 45, was I supposed to upgrade anything before retrying?

**Comment by brentvatne** [comment]
@ayaanqui - run `npm why @expo/config-plugins@5.0.0` and share the output

**Comment by kbdemba** [comment]
@ayaanqui Delete the node_modules folder and package-loc.json and run `expo doctor --fix-dependencies` again. That worked for me

**Comment by ayaanqui** [comment]
> @ayaanqui Delete the node_modules folder and package-loc.json and run `expo doctor --fix-dependencies` again. That worked for me

just gave that I try but no luck, thanks for sharing the info tho!

**Comment by ayaanqui** [comment]
> @ayaanqui - run `npm why @expo/config-plugins@5.0.0` and share the output

```
$ npm why @expo/config-plugins@5.0.0
@expo/config-plugins@5.0.0 peer
node_modules/expo-updates/node_modules/@expo/config-plugins
  @expo/config-plugins@"~5.0.0" from expo-updates@0.14.3
  node_modules/expo-updates
    peer expo-updates@"*" from sentry-expo@4.2.0
    node_modules/sentry-expo
      sentry-expo@"^4.2.0" from the root project
  @expo/config-plugins@"~5.0.0" from @expo/config@7.0.0
  node_modules/expo-updates/node_modules/@expo/config
    @expo/config@"~7.0.0" from expo-updates@0.14.3
    node_modules/expo-updates
      peer expo-updates@"*" from sentry-expo@4.2.0
      node_modules/sentry-expo
        sentry-expo@"^4.2.0" from the root project
```

**Comment by newme616** [comment]
same issue here

**Comment by toddbauermeister** [comment]
Anyone tried anything else that worked? I'm on Expo45 and using Yarn and can't get this fixed 😅

Also does anyone know what kinds of practical issues this causes within projects, like what actually breaks because of this bug?

**Comment by kindthr** [comment]
@toddbauermeister I've tried [this](https://github.com/expo/eas-cli/issues/1251)  & it's working  
"resolutions": {
    "@expo/config-plugins": "~4.1.0",
    "@expo/prebuild-config": "~4.0.0",
    "expo-modules-autolinking": "0.9.0"
  },

**Comment by ayaanqui** [comment]
> @toddbauermeister I've tried [this](https://github.com/expo/eas-cli/issues/1251) & it's working "resolutions": { "@expo/config-plugins": "~4.1.0", "@expo/prebuild-config": "~4.0.0", "expo-modules-autolinking": "0.9.0" },

@kindthr This actually worked for me. I did try using resolutions but I did not know anything about the `@expo/prebuild-config` and `expo-modules-autolinking` packages. Thanks!

**Comment by Adieeeel** [comment]
@kindthr 

> @toddbauermeister I've tried [this](https://github.com/expo/eas-cli/issues/1251) & it's working "resolutions": { "@expo/config-plugins": "~4.1.0", "@expo/prebuild-config": "~4.0.0", "expo-modules-autolinking": "0.9.0" },

what do you mean about this ?? 

we need to install those versions of this packages ?

**Comment by Adieeeel** [comment]
@kindthr 

> @toddbauermeister I've tried [this](https://github.com/expo/eas-cli/issues/1251) & it's working "resolutions": { "@expo/config-plugins": "~4.1.0", "@expo/prebuild-config": "~4.0.0", "expo-modules-autolinking": "0.9.0" },


what do you mean about this ??

we need to install those versions of this packages ?

**Comment by kindthr** [comment]
@Adieeeel no you don't need to install them just put them on the app.json

**Comment by p-e-g-a-h** [comment]
hi. i run ...
`npm i -g expo-cli`
`npm update`
and fixed for me.

**Comment by bastianspirek** [comment]
Same problem for me:
![image](https://user-images.githubusercontent.com/7038550/204383804-3aefe94f-9e8c-49d4-b41d-53b390c07258.png)
I guess I have to downgrade firebase? But how would I know which older version of firebase depends on the correct version of @expo/config-plugins?

**Comment by Arnav7501** [comment]
same problem for me, any help?

**Comment by matheuscouto** [comment]
This worked for me

> @toddbauermeister I've tried [this](https://github.com/expo/eas-cli/issues/1251) & it's working "resolutions": { "@expo/config-plugins": "~4.1.0", "@expo/prebuild-config": "~4.0.0", "expo-modules-autolinking": "0.9.0" },

**Comment by SebaMutuku** [comment]
> I have the same issue. In my case it's due to `expo-updates`. I tried to re-install expo-updates with `expo install` but it didn't solve the wrong dependency. Does anyone know how to fix it?
> 
> ```
> node_modules/expo-updates/node_modules/@expo/metro-config/node_modules/@expo/config-plugins
> ```

Did you find any solution? Experiencing the same error now

**Comment by adriaanbalt** [comment]
**SDK 45**

package.json

```json
"dependencies": {
    "@apollo/client": "^3.5.5",
    "@bugsnag/expo": "^7.15.1",
    "@expo/metro-config": "^0.5.2",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.1.2",
    "@react-native-community/slider": "4.2.1",
    "@react-native-firebase/app": "^16.5.0",
    "@react-native-picker/picker": "2.4.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@splitsoftware/splitio": "^10.17.1",
    "apollo3-cache-persist": "^0.13.0",
    "array-move": "^4.0.0",
    "cross-fetch": "^3.1.4",
    "d3-scale": "^4.0.2",
    "expo": "^45.0.0",
    "expo-analytics-segment": "~11.2.1",
    "expo-asset": "~8.5.0",
    "expo-av": "~11.2.3",
    "expo-build-properties": "~0.2.0",
    "expo-constants": "~13.1.1",
    "expo-dev-client": "~1.0.1",
    "expo-device": "~4.2.0",
    "expo-facebook": "~12.2.0",
    "expo-firebase-recaptcha": "~2.2.0",
    "expo-font": "~10.1.0",
    "expo-image-manipulator": "~10.3.1",
    "expo-image-picker": "~13.1.1",
    "expo-linear-gradient": "~11.3.0",
    "expo-linking": "~3.1.0",
    "expo-localization": "~13.0.0",
    "expo-modules-core": "~0.9.2",
    "expo-notifications": "~0.15.4",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.4",
    "expo-web-browser": "~10.2.1",
    "firebase": "9.6.4",
    "graphql": "^16.0.1",
    "graphql-type-json": "^0.3.2",
    "humanize-plus": "^1.8.2",
    "i18n-js": "^3.8.0",
    "immutability-helper": "^3.1.1",
    "jest-fetch-mock": "^3.0.3",
    "lodash": "^4.17.21",
    "lunr": "^2.3.9",
    "moment": "^2.29.1",
    "react": "17.0.2",
    "react-devtools-core": "^4.27.1",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-calendars": "^1.1279.0",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-modal-datetime-picker": "^13.1.0",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-svg": "12.3.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@testing-library/jest-native": "^4.0.4",
    "@testing-library/react-hooks": "^7.0.2",
    "@testing-library/react-native": "^9.0.0",
    "@types/array-move": "^2.0.0",
    "@types/country-select-js": "^1.0.2",
    "@types/d3-scale": "^4.0.2",
    "@types/enzyme": "^3.10.11",
    "@types/graphql-type-json": "^0.3.2",
    "@types/humanize-plus": "^1.8.0",
    "@types/i18n-js": "^3.8.2",
    "@types/immutability-helper": "^2.6.3",
    "@types/jest": "^27.4.0",
    "@types/lodash": "^4.14.178",
    "@types/lunr": "^2.3.4",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.10",
    "@types/react-native": "^0.70.8",
    "@types/react-native-calendars": "^1.1264.3",
    "@types/react-native-scrollable-tab-view": "^0.10.3",
    "@types/react-native-svg-charts": "^5.0.12",
    "@types/react-native-tab-view": "^2.3.0",
    "@types/react-test-renderer": "^17.0.1",
    "@types/uuid": "^8.3.4",
    "babel-plugin-module-resolver": "^4.1.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "eslint-config-airbnb": "^19.0.4",
    "jest": "^26.6.3",
    "jest-expo": "^45.0.0",
    "msw": "^0.36.8",
    "react-test-renderer": "17",
    "ts-jest": "^27.1.3",
    "ts-node": "^10.4.0",
    "typescript": "~4.3.5"
  },
```

When using eas build:

```
$ eas build -p ios --profile development

Compressing project files and uploading to EAS Build. Learn more
✔ Compressed project files 1s (5.7 MB)
✔ Uploaded to EAS 1s

Build details: https://expo.dev/accounts/adriaanbalt/projects/app/builds/xyz123xyz

Waiting for build to complete. You can press Ctrl+C to exit.
  Build queued...

Start builds sooner in the priority queue.
Sign up for EAS Production or Enterprise at https://expo.dev/accounts/adriaanbalt/settings/subscriptions

Waiting in Free tier queue
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■|

✖ Build failed

🍎 iOS build failed:
Internal Server Error.
Try again later. If the problem persists, report the issue.
```

Within the expo build interface it shows:
![Screen Shot 2023-01-19 at 6 09 58 PM](https://user-images.githubusercontent.com/146778/213525830-0df6e88c-25a2-4806-8dfa-33c9b55f4edc.png)

Output of the suggested

```
$ npm why @expo/config-plugins
```

Reads that 

```
@expo/config-plugins@5.0.4
node_modules/@expo/metro-config/node_modules/@expo/config-plugins
  @expo/config-plugins@"~5.0.3" from @expo/config@7.0.3
  node_modules/@expo/metro-config/node_modules/@expo/config
    @expo/config@"~7.0.2" from @expo/metro-config@0.5.2
    node_modules/@expo/metro-config
      @expo/metro-config@"^0.5.2" from the root project
```

In other words, the build process required `@expo/metro-config` but that module requires `@expo/config-plugins@"~5.0.3"` which `expo doctor` and the build process do not like. 🤔

**Comment by adriaanbalt** [comment]
Needed to upgrade to sdk 47, solved a lot of my problems.  also watch out for [expo-build-properties in your app.json](https://github.com/invertase/react-native-firebase/issues/6332#issuecomment-1172950523)

**Comment by yeukfei02** [comment]
Hi,

I add this to `package.json`

```
"resolutions": {
    "@expo/config-plugins": "^5.0.2",
    "@expo/prebuild-config": "~5.0.3",
    "expo-modules-autolinking": "~1.0.0"
  }
```

and remove `node_modules` and `yarn.lock`..then I return `yarn` and `expo doctor`.

I use expo 47.0.13 and node 16.16.0

it works for me.

**Comment by owencm** [comment]
In my case I was using `"jest-expo": "^45.0.1",` somewhere in my workspace which was causing the issue. Downgrading it to 45 fixed it (found the issue with `npm why @expo/config-plugins`)

**Comment by Abelcor** [comment]
I have also received this error and then I did the following:

1. Open terminal and navigate to project root folder
2. Run `npm ls @expo/config-plugins`
3. It should then show all packages dependant on it
4. Find the plugin that depend on the old @expo/config-plugins@4.1.1 package 
5. Most of them should use the latest package, however, there was one plugin I needed to update that depended on the old package

**Comment by noob339** [comment]
@Abelcor 

So I found the plugin @react-native-voice/voice@3.2.4 that is causing issues, but its already up to date. Any suggestions on how to fix it

`├─┬ @react-native-voice/voice@3.2.4
│ └── @expo/config-plugins@2.0.4
├─┬ expo-camera@12.5.0
│ └── @expo/config-plugins@5.0.4
├─┬ expo-dev-client@1.3.1
│ ├── @expo/config-plugins@5.0.4 deduped
│ ├─┬ expo-dev-launcher@1.3.1
│ │ └── @expo/config-plugins@5.0.4 deduped
│ └─┬ expo-dev-menu@1.3.1
│   └── @expo/config-plugins@5.0.4 deduped
├─┬ expo-location@14.3.0
│ └── @expo/config-plugins@5.0.4 deduped
├─┬ expo-media-library@14.2.0
│ └── @expo/config-plugins@5.0.4 deduped
└─┬ expo@46.0.20
  ├─┬ @expo/cli@0.3.3
  │ ├── @expo/config-plugins@5.0.4 deduped
  │ ├─┬ @expo/config@7.0.3
  │ │ └── @expo/config-plugins@5.0.4 deduped
  │ ├─┬ @expo/metro-config@0.4.0
  │ │ └─┬ @expo/config@7.0.1
  │ │   └── @expo/config-plugins@5.0.4 deduped
  │ └─┬ @expo/prebuild-config@5.0.7
  │   └── @expo/config-plugins@5.0.4 deduped
  └─┬ expo-file-system@14.1.0
    └── @expo/config-plugins@5.0.4 deduped

`

Any assistance would be appreciated

**Comment by vitorpereiira** [comment]
> 

same problem

**Comment by alicanso** [comment]
same here

**Comment by EOMZON** [comment]
> @Abelcor
> 
> 所以我发现插件@react-native-voice/voice@3.2.4导致了问题，但它已经是最新的了。有关如何修复它的任何建议
> 
> `├─┬ @react-native-voice/voice@3.2.4 │ └── @expo/config-plugins@2.0.4 ├─┬ expo-camera@12.5.0 │ └── @expo/config-plugins @5.0.4 ├─┬ expo-dev-client@1.3.1 │ ├── @expo/config-plugins@5.0.4 去重 │ ├─┬ expo-dev-launcher@1.3.1 │ │ └── @expo/config-plugins@5.0.4 去重 │ └─┬ expo-dev-menu@1.3.1 │ └── @expo/config-plugins@5.0.4 去重 ├─┬ expo-location@14.3. 0 │ └ ── @expo/config-plugins@5.0.4 去重 ├─┬ expo-media-library@14.2.0 │ └── @expo/config-plugins@5.0.4 去重 └─┬ expo@ 46.0.20 ├─ ┬ @expo/cli@0.3.3 │ ├── @expo/config-plugins@5.0.4 去重 │ ├─┬ @expo/config@7.0.3 │ │ └── @expo/ 4 去重 │ ├─┬ @expo/metro-config@0.4.0 │ │ └─┬ @expo/config@7.0.1 │ │ └── @expo/config-plugins@5.0. config-plugins@5.0。 4 去重 │ └─┬ @ expo/prebuild-config@5.0.7 │ └── @expo/config-plugins@5.0.4 去重 └─┬ expo-file-system@14.1.0 └── @expo /config-plugins@5.0.4 去重
> 
> `
> 
> 任何援助者都不会感激

🥺I have encountered the same problem as you. Do you know how to solve it?

**Comment by abdul-megadraws** [comment]
Same problem here.
After installing expo-firebase-analytics getting the below error for EAS Build (Only for Android).

Error:
What went wrong:
A problem occurred configuring project ':expo'.
compileSdkVersion is not specified. Please add it to build.gradle

npx expo-doctor :
Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.

**Comment by raajnadar** [comment]
`expo-firebase-analytics` is deprecated from SDK 47

**Comment by yakovsushenok** [comment]
For me the problem was with `@expo/config-plugins` of a third-party library being outdated, so I just used this https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides:
```
"overrides": {
    "@expo/config-plugins": "8.0.0",
    "@expo/prebuild-config": "^7.0.6",
    "expo-modules-autolinking": "1.11.1"
  }
```

**Comment by yakovsushenok** [comment]
# My problem: 


```
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.9.2
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.

One or more checks failed, indicating possible issues with the project.
```
# Solution


For me the problem was with `@expo/config-plugins` of a third-party library being outdated, so I just used this https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides:
```
"overrides": {
    "@expo/config-plugins": "8.0.0"
  }
```

in my `package.json`.

And then after I ran `npm i` -> `npx expo-doctor`, I saw that the issue was resolved.

**Comment by tfihsdeR** [comment]
> # My problem:
> ```
> ✖ Check that native modules use compatible support package versions for installed Expo SDK
> 
> Detailed check results:
> 
> Expected package @expo/config-plugins@~8.0.0
> Found invalid:
>   @expo/config-plugins@7.9.2
>   (for more info, run: npm why @expo/config-plugins)
> Advice: Upgrade dependencies that are using the invalid package versions0.
> 
> One or more checks failed, indicating possible issues with the project.
> ```
> 
> # Solution
> For me the problem was with `@expo/config-plugins` of a third-party library being outdated, so I just used this https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides:
> 
> ```
> "overrides": {
>     "@expo/config-plugins": "8.0.0"
>   }
> ```
> 
> in my `package.json`.
> 
> And then after I ran `npm i` -> `npx expo-doctor`, I saw that the issue was resolved.

I had the same issue because of the "react-native-voice/voice" and overrides has solved. You can use it for that one.
