### ISSUE TITLE
[SDK45] expo-facebook crashing the app on Samsung Galaxy FE20 Android 12

### ISSUE THREAD

**Issue by robertoosantos** [expo/expo#18429]
### Summary

After updating to Expo 45, the app crashes in production after "Continue With Facebook" is pressed.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.20.0 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 6.14.17 - /usr/bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: managed

### Reproducible demo

It happens only in production.
Expo GO: Works fine
On IOS: Works fine
Tested on other Android phone (Galaxy S8+): Works fine

The app is this: https://play.google.com/store/apps/details?id=app.caseira.www.twa

A video with the behavior: https://drive.google.com/file/d/166SHLkAU51BjBqoaSxApUV08LP0Bz86A/view?usp=sharing

If there's no Facebook App installed the Facebook Login page is shown correctly but after the callback, the same app crash.

The Facebook Login component:

```javascript
import React, { useState } from 'react'
import PropTypes from 'prop-types'
import { Alert } from 'react-native'
import * as Facebook from 'expo-facebook';
import { Button } from 'react-native-paper';
import CaseiraAPI from '../services/caseira';
import { useDispatch } from 'react-redux';
import { salvarToken } from '../actions/login';

const api = new CaseiraAPI();
function FacebookLogin(props) {
    const [processando, setProcessando] = useState(false)
    const dispatch = useDispatch()

    const continuarComFacebook = async () => {

        setProcessando(true)

        try {
            await Facebook.initializeAsync({
                appId: "XXX"
            });
            const {
                type,
                token,
            } = await Facebook.logInWithReadPermissionsAsync({
                permissions: ["public_profile", "email"]
            });

            if (type === "success") {
                //This line is not reached. There's no api call
                const nossoToken = await api.LoginFacebook(token);
                dispatch(salvarToken(nossoToken));
            }
        } catch (error) {
            //Neither this line. No Alerts are shown.              
            setProcessando(false)
            Alert.alert("Ops!", error.message)
        }
    };

    return (
        <Button
            loading={processando}
            disabled={processando}
            style={props.style}
            labelStyle={props.labelStyle}
            icon="facebook"
            onPress={continuarComFacebook}>
            Continuar com Facebook
        </Button>
    )
}

FacebookLogin.propTypes = {
    style: PropTypes.object,
    labelStyle: PropTypes.object
}

export default FacebookLogin
```

**Comment by brentvatne** [comment]
expo-facebook is deprecated, it was removed in sdk 46. 

> Deprecated. This module will be removed in SDK 46. There will be no replacement that works with the classic build service (expo build) because [the classic build service has been superseded by EAS Build](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60). With EAS Build and [Development Builds](https://docs.expo.dev/development/introduction/), you should use [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/#expo-installation) instead.

**Comment by robertoosantos** [comment]
> expo-facebook is deprecated, it was removed in sdk 46.
> 
> > Deprecated. This module will be removed in SDK 46. There will be no replacement that works with the classic build service (expo build) because [the classic build service has been superseded by EAS Build](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60). With EAS Build and [Development Builds](https://docs.expo.dev/development/introduction/), you should use [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/#expo-installation) instead.

I've tried using 'react-native-fbsdk-next' but got this error after just replacing the component: Invariant Violation: requireNativeComponent: "RCTFBLoginButton" was not found in the UIManager.

[I've reported the documentation bug](https://github.com/thebergamo/react-native-fbsdk-next/issues/296)

May someone help me?

**Comment by albertolab** [comment]
@robertoosantos  Hi, did you find a solution? the same happen to me after update to expo sdk 45.

**Comment by robertoosantos** [comment]
Yes. I have migrated to [bare workflow](https://docs.expo.dev/bare/hello-world/) and followed the [installation documentation](https://github.com/thebergamo/react-native-fbsdk-next/#installation)
