### ISSUE TITLE
Videos disappear on Android when scrolling inside a FlatList with removeClippedSubviews set to true

### ISSUE THREAD

**Issue by watadarkstar** [expo/expo#1842]
Videos disappear on Android when scrolling inside a FlatList with removeClippedSubviews set to true.

### Environment

Environment:
OS: macOS High Sierra 10.13.3
Node: 8.11.1
Yarn: 1.5.1
npm: 5.6.0
Watchman: Not Found
Xcode: Xcode 9.3 Build version 9E145
Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
expo: ^26.0.0 => 26.0.0
react: 16.3.0-alpha.1 => 16.3.0-alpha.1
react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

### Steps to Reproduce

I am using a `FlatList` to display a list of videos with `removeClippedSubviews` set to `true`. But on Android the videos start to disappear when you start scrolling around. See this snack and scroll up and down a bunch: https://snack.expo.io/@darkwata/expo-video-disappearing

### Expected Behavior

Videos do not disappear.

### Actual Behavior

Videos disappear on scroll.

### Reproducible Demo

https://snack.expo.io/@darkwata/expo-video-disappearing

**Comment by watadarkstar** [comment]
Related https://facebook.github.io/react-native/docs/view.html#removeclippedsubviews : 

`removeClippedSubviews`
This is a special performance property exposed by RCTView and is useful for scrolling content when there are many subviews, most of which are offscreen. For this property to be effective, it must be applied to a view that contains many subviews that extend outside its bound. The subviews must also have overflow: hidden, as should the containing view (or one of its superviews).

**Comment by watadarkstar** [comment]
@sjchmiela @anp Any plans to work on this?

**Comment by sjchmiela** [comment]
Hi @watadarkstar, sorry, I'm a little bit caught up in other tasks at the moment, but yeah, I think displaying a bunch of videos in a FlatList will be tricky.

> Maybe we need to make <Video> use overflow: hidden.

You could try changing `_STYLES.video` in `Video.js` in your `node_modules` directory to check whether this would help, FYI `Video` component is wrapped with a `View` element, which lets us render poster nicely.

**Comment by watadarkstar** [comment]
Will try that thanks @sjchmiela

**Comment by sjchmiela** [comment]
I'll tentatively close this issue, if you have any more questions feel free to reopen it!

**Comment by thekrol01** [comment]
@watadarkstar i was wondering, did you find a workaround for this issue?

**Comment by watadarkstar** [comment]
@thekrol01 No I didn't are you on the latest version of Expo?

**Comment by thekrol01** [comment]
@watadarkstar yes, sdk 32. I have  also tried to load and unload the video 's in the flatlist in combination with the media player of Android. This works on Android as long as they are hyperlinks that point to a location on the web. If the videos refer to a Firebase location the video 's don't load.

**Comment by watadarkstar** [comment]
@thekrol01 Have you tried it without a Flatlist? You may also want to create a new issue in github since they closed this one.

**Comment by thekrol01** [comment]
yes I have (demo included)
https://github.com/expo/expo/issues/3443
