### ISSUE TITLE
Cannot build application by eas build because of gradle error: Deprecated Gradle features were used in this build

### ISSUE THREAD

**Issue by michalzubkowicz** [expo/expo#18434]
### Summary

I'm trying to build application using command  eas build, but it fais

`Running './gradlew :app:bundleRelease' in /home/expo/workingdir/build/android

Downloading https://services.gradle.org/distributions/gradle-7.3.3-all.zip
Welcome to Gradle 7.3.3!

Here are the highlights of this release:

 - Easily declare new test suites in Java projects

 - Support for Java 17

 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.

Daemon will be stopped at the end of the build

Unable to list file systems to check whether they can be watched. Assuming all file systems can be watched. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)

> Task :react-native-gradle-plugin:compileKotlin

'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (155, 32): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (161, 31): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (169, 36): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt: (100, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with rootto point to your root project and reactNativeDir to point to the folder of the react-native NPM package

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (28, 51): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (131, 12): 'ApplicationVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (132, 12): 'LibraryVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (252, 14): 'BaseVariant' is deprecated. Deprecated in Java

> Task :react-native-gradle-plugin:compileJava

[stderr] Note: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java uses or overrides a deprecated API.

[stderr] Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-gradle-plugin:pluginDescriptors

> Task :react-native-gradle-plugin:processResources

> Task :react-native-gradle-plugin:classes

> Task :react-native-gradle-plugin:inspectClassesForKotlinIC

> Task :react-native-gradle-plugin:jar

> Configure project :app

Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Configure project :expo

Using expo modules

  - react-native-google-signin-google-signin (7.2.2)

  - expo-application (4.1.0)

  - expo-constants (13.1.1)

  - expo-crypto (10.2.0)

  - expo-error-recovery (3.1.0)

  - expo-file-system (14.0.0)

  - expo-font (10.1.0)

  - expo-keep-awake (10.1.1)

  - expo-linear-gradient (11.3.0)

  - expo-localization (13.0.0)

  - expo-modules-core (0.9.2)

  - expo-splash-screen (0.15.1)

  - expo-web-browser (10.2.1)

[stderr] FAILURE: Build completed with 2 failures.

[stderr] 1: Task failed with an exception.

[stderr] -----------

[stderr] * Where:

[stderr] Build file '/home/expo/workingdir/build/node_modules/expo-react-native-adapter/android/build.gradle' line: 13

[stderr] * What went wrong:

[stderr] A problem occurred evaluating project ':expo-react-native-adapter'.

[stderr] > Plugin with id 'maven' not found.

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] 2:

[stderr] Task failed with an exception.

[stderr] -----------

[stderr] * What went wrong:

[stderr] A problem occurred configuring project ':expo-react-native-adapter'.

[stderr] > compileSdkVersion is not specified. Please add it to build.gradle

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] * Get more help at https://help.gradle.org

[stderr] BUILD FAILED in 1m 54s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

6 actionable tasks: 6 executed

Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)

Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45,46

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 KDE neon 5.25
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /run/user/1000/fnm_multishells/240228_1659103066667/bin/node
      npm: 8.6.0 - /run/user/1000/fnm_multishells/240228_1659103066667/bin/npm
    npmPackages:
      babel-preset-expo: 9.1.0 => 9.1.0 
      expo: 45.0.6 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.56.0
      expo-cli: 6.0.1
    Expo Workflow: managed

### Reproducible demo

I don't know what such a demo with build problem should contain.

**Comment by michalzubkowicz** [comment]
I've created reproducible example. This project contains only build files and nothing more. and is still not building:
https://github.com/michalzubkowicz/expo-error-demo

**Comment by michalzubkowicz** [comment]
It is possible to reopen or should I create new issue?

**Comment by michalzubkowicz** [comment]
I've found that some issues are related to that I've installed eas-cli as dev dependency, but after cleaning that there are still issues:

`Running './gradlew :app:bundleRelease' in /home/expo/workingdir/build/android

Downloading https://services.gradle.org/distributions/gradle-7.3.3-all.zip

Welcome to Gradle 7.3.3!

Here are the highlights of this release:

 - Easily declare new test suites in Java projects

- Support for Java 17

 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.

Daemon will be stopped at the end of the build

Unable to list file systems to check whether they can be watched. Assuming all file systems can be watched. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)

> Task :react-native-gradle-plugin:compileKotlin

'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (155, 32): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (161, 31): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (169, 36): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt: (100, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with rootto point to your root project and reactNativeDir to point to the folder of the react-native NPM package

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (28, 51): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (131, 12): 'ApplicationVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (132, 12): 'LibraryVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (252, 14): 'BaseVariant' is deprecated. Deprecated in Java

> Task :react-native-gradle-plugin:compileJava

[stderr] Note: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java uses or overrides a deprecated API.

[stderr] Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-gradle-plugin:pluginDescriptors

> Task :react-native-gradle-plugin:processResources

> Task :react-native-gradle-plugin:classes

> Task :react-native-gradle-plugin:inspectClassesForKotlinIC

> Task :react-native-gradle-plugin:jar

> Configure project :app

Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Configure project :expo

Using expo modules

  - react-native-google-signin-google-signin (8.0.0)

  - expo-application (4.1.0)

  - expo-constants (13.1.1)

  - expo-crypto (10.2.0)

  - expo-error-recovery (3.1.0)

  - expo-file-system (14.0.0)

  - expo-font (10.1.0)

  - expo-keep-awake (10.1.1)

  - expo-linear-gradient (11.3.0)

  - expo-localization (13.0.0)

  - expo-modules-core (0.9.2)

  - expo-splash-screen (0.15.1)

  - expo-web-browser (10.2.1)

[stderr] FAILURE: Build completed with 2 failures.

[stderr] 1: Task failed with an exception.

[stderr] -----------

[stderr] * Where:

[stderr] Build file '/home/expo/workingdir/build/node_modules/expo-react-native-adapter/android/build.gradle' line: 13

[stderr] * What went wrong:

[stderr] A problem occurred evaluating project ':expo-react-native-adapter'.

[stderr] > Plugin with id 'maven' not found.

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] 2: Task failed with an exception.

[stderr] -----------

[stderr] * What went wrong:

[stderr] A problem occurred configuring project ':expo-react-native-adapter'.

[stderr] > compileSdkVersion is not specified. Please add it to build.gradle

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] * Get more help at https://help.gradle.org

[stderr] BUILD FAILED in 2m 24s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

6 actionable tasks: 6 executed

Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)

Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.`

**Comment by michalzubkowicz** [comment]
In case anyone search for problem was with the "react-native-firebase": "5.6.0", it somehow downgraded Gradle and produces such errors.

**Comment by pohsiu** [comment]
Why this kind of gradle 8  issue always closed with no solution?...
