### ISSUE TITLE
Native support for react-native-view-overflow

### ISSUE THREAD

**Issue by yakirbu** [expo/expo#1843]
The library 'react-native-view-overflow' adds support for the known issue of overflow:'visible' for Android.
It currently won't work with Expo since it needs changes in Native code.

This is the issue that appears to expo users currently, using this library:
https://github.com/entria/react-native-view-overflow/issues/27

**Comment by brentvatne** [comment]
i think you can work around not having overflow using other approaches. notice that this library has a lot of issues: https://github.com/entria/react-native-view-overflow/issues

it's unfortunate that react-native doesn't support overflow on android but i think a solution that isn't comprehensive and leaves you with edge case bugs is not the right approach to solve it

**Comment by collaorodrigo7** [comment]
Hey, sorry @brentvatne.. I was curious about your answer  
I understand there are some issues with the library, but Is there any chance this could be reconsider?

The only workaround I can think about is moving the children to the same level as the parent and using absolute positioning.. but with a complex UI, that could get complicated and messy, am I wrong?
What would you recommend for it?

Just to try to support the idea of reconsidering this suggestion, as overflow is supported almost everywhere else, I am guessing a lot of developers are used to use it, especially the ones coming from web development. And in fact it works on android it is just required to set setClipChildren properly as it is explained [here](https://medium.com/entria/solving-view-overflow-in-android-reactnative-f961752a75cd).

I understand we could use ExpoKit but It would be cool to have the option to use this library out of the box with expo. 

Also after reading some of the issues [#6802](https://github.com/facebook/react-native/issues/6802) in react native repo, seems to be many people frustrated with this.. and the suggested solution in most places (including [#6802](https://github.com/facebook/react-native/issues/6802) ) is try to use react-native-view-overflow..
I am still _new_ to expo and react native, and I am sure I have a lot to learn yet but hope you can give me some feedback..
Thanks!!

**Comment by OptiFree** [comment]
I have the same problem, and the absolute positioning is not solving satisfactorily.

It would be great if the Expo supported https://github.com/entria/react-native-view-overflow

**Comment by allankikkas** [comment]
is it really needed as if expo upgrades react native to 57 then it should be solved as stated in release docs?

https://github.com/facebook/react-native/commit/b81c8b5
https://github.com/facebook/react-native/commit/bbdc12e
