### ISSUE TITLE
Issues when having different versions of React inside a workspace/monorepo

### ISSUE THREAD

**Issue by focux** [expo/expo#18447]
### Summary

When you have a workspace/monorepo with apps using different versions of react/react-dom or other packages, pnpm and I think yarn as well, install the `react-native` package folder inside the local `node_modules` instead of the root `node_modules` folder. This causes this error when installing pods:

```
Error: Cannot find module 'react-native/package.json'
[!] Failed to load 'expo-dev-menu' podspec: 
[!] Invalid `expo-dev-menu.podspec` file: no implicit conversion of nil into String.
```

And this one as well:
```
error: Could not determine react-native-codegen location in /Users/[redacted]/[redacted]/[redacted]/apps/mobile-
app/ios/Pods/../../node_modules/react-native/React/FBReactNativeSpec/../../packages/react-native-codegen or 
/Users/[redacted]/[redacted]/[redacted]/apps/mobile-app/ios/Pods/../../node_modules/react-
native/React/FBReactNativeSpec/../../../react-native-codegen.
```

I tested this on SDK 44 and 46.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

44-46

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 31.0.0, 32.0.0
        System Images: android-29 | Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      react: 18.0.0 => 17.0.1 
      react-dom: 18.0.0 => 17.0.1 
      react-native: 0.69.3 => 0.64.3 
      react-native-web: ~0.18.7 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.56.0
      expo-cli: 6.0.1
    Expo Workflow: bare

### Reproducible demo

https://github.com/focux/eas-monorepo-example/tree/test-pnpm-sdk-46
https://github.com/focux/eas-monorepo-example/tree/test-pnpm-sdk44-new

To test just run
```
$ pnpm i
$ cd apps/with-dev-client && expo prebuild --no-install && expo run:ios
```

**Comment by brentvatne** [comment]
react-native doesn't work well when you have multiple versions inside of a monorepo. you can post an issue about this in the react-native repository if you want but i don't think you will get much help. you should use one version of react and react-native in your monorepo.
