### ISSUE TITLE
Keep cache and config data in appropriate directories

### ISSUE THREAD

**Issue by joshas** [expo/expo#18441]
### Summary

Please consider moving cache and config data to appropriate directories as defined in [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). *-cache data should end up in `~/.cache/expo` directory and configuration files in `~/.config/expo`. Doing this helps to keep user home directory clean and easy to backup only important files, as backing up cache data is wasteful and takes additional time.

### SDK Version

6.0.1

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.18 Fedora Linux 35 (Workstation Edition)
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 16.14.0 - /usr/bin/node
      npm: 8.15.1 - ~/.npm-global/bin/npm
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 6.0.1
    Expo Workflow: managed

### Reproducible demo

Install expo and create new project as described in official documentation. Run project. Open home directory in file manager and notice `.expo` directory created there.

**Comment by brentvatne** [comment]
related to https://github.com/expo/expo-cli/issues/2274

i believe the path forward here is what is discussed in that issue. if someone would like to open a pr, we can consider it :) either that or open up a discussion on https://github.com/expo/expo/discussions. issues are reserved for bug reports.
