### ISSUE TITLE
Detaching is not supported for SDK version 27.0.2

### ISSUE THREAD

**Issue by spedy** [expo/expo#1845]
I am trying to build detached on Android Oreo and had issues with...

[this](https://github.com/expo/expo/issues/1698)  (`WebSocketModule.close got 1 arguments, expected 3`) so I had to use 27.0.2 version as suggested [here](https://github.com/expo/expo/issues/1698#issuecomment-386435199).

But now I cannot detach, because of`Detaching is not supported for SDK version 27.0.2`.

**Comment by terribleben** [comment]
Hi! You can update your `package.json`  to use the dependency listed in that comment, but `app.json` should still use `sdkVersion: 27.0.0`. Sorry for the confusion.
