### ISSUE TITLE
[expo-av] [Android] Video component setOnPlaybackStatusUpdate updates the 'isBuffering' working not correct

### ISSUE THREAD

**Issue by ovchinnikovs** [expo/expo#18462]
### Summary

When playing a video, I'm on the "isBuffering" variable, I check the status of "true" or "false" and display the loader before loading the video.

There is a problem with android. The video has loaded and is already playing, but the "isBuffering" variable is still in the "true" position for a long time and does not change its position to "false". Therefore, it turns out that the video has loaded and started, and the loader is still displayed. See the video demo below.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

SDK 45

### Environment

"expo": "^45.0.0",
"expo-av": "~11.2.3",
"expo-image-manipulator": "~10.3.1",
"expo-media-library": "~14.1.0",
"expo-video-thumbnails": "~6.3.0",
"react": "17.0.2",
 "react-native": "^0.68",

### Reproducible demo

https://user-images.githubusercontent.com/50240729/182429707-c84bea17-6b25-4001-b017-c95f479911c0.mp4

**Comment by IliasseWahbi** [comment]
Hi, same issue here. I'll update if I manage to fix it

**Comment by IliasseWahbi** [comment]
I think that the video is playing even thought it's still buffering because the video is not fully loaded yet. To know when to display the loading indicator you should use both isBuffering and isPlaying variables (as advised here : [https://docs.expo.dev/versions/latest/sdk/av/#playasync](https://docs.expo.dev/versions/latest/sdk/av/#playasync)).

On my side Im still having an issue where the video is still buffering even if it has been already fully loaded.

**Comment by siddharth-kt** [comment]
+1 same issue

**Comment by liquidvisual** [comment]
Same issue on Android, glad I'm not the only one. 

It's an annoying issue because if you're showing a loader when `isBuffering && !isPlaying` you'd have have to create and track a separate `isPaused` state because as soon as you pause the video you'll invoke the loader with the first logic.

**Comment by micahkatz** [comment]
+1 I am still having this issue

**Comment by CyxouD** [comment]
Also experience this in the same use case
