### ISSUE TITLE
detached ios sdk27 project unable to load without network

### ISSUE THREAD

**Issue by alxyuu** [expo/expo#1847]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.0
  Yarn: Not Found
  npm: 5.7.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/alxyuu1-6601811b-9ed6-4874-a64d-bd5ab92f89a3.tar.gz

Target:
iOS, ExpoKit

### Steps to Reproduce

1. Detach a new ExpoKit app
2. Use the following value for `expo.updates` in app.json:
```
   {
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    }
```
3. Run `exp publish`  to generate a shell-app manifest and bundle
4. Build app and install on physical iPhone or iOS simulator
5. Turn computer wifi off if running via simulator or turn on airplane mode on iPhone
6. Open app

### Expected Behavior

The app should load (more or less) immediately using the packaged shell-app manifest and bundle, or a later cached version

### Actual Behavior

The splash screen is shown until the app is force closed

### Reproducible Demo

https://github.com/alxyuu/ios-detach

### Additional Notes

Changing `expo.updates.checkAutomatically` to `ON_ERROR_RECOVERY` allows the app to load with no network. The downside here is I would have handle fetching the bundle myself on app load.

Keeping `ON_LOAD` and setting  `fallbackToCacheTimeout` to 1 will also allow the app to load with no network, so it seems that the 0 value is not working as intended, which should not wait for any updates per the documentation.

This issue does not affect Android, which still loads after a short splash screen in airplane mode.

**Comment by msevestre** [comment]
I have the same issue using sdk 27

**Comment by esamelson** [comment]
Hi - this will be fixed in SDK 28 which is out tomorrow. We'll try and backport the change to SDK 27 ExpoKit, too. Really sorry for the inconvenience.
