### ISSUE TITLE
[SDK46][Web] ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by JamesHemery** [expo/expo#18485]
### Summary

When I upgrade an existing projet to SDK 46 (React 18) or when I create a new blank project, and running on web I have this error: 'Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot'

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.0
      expo: ~46.0.2 => 46.0.2
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.3 => 0.69.3
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: managed

### Reproducible demo

Juste clone the default tabs or blank template and run on web.

**Comment by JamesHemery** [comment]
Temporary fixed by creating a custom index file or by patching registerRootComponent function (following React doc), but IDK if it's the good way for an Expo patch :

```js
import 'expo/build/Expo.fx';
import { AppRegistry, Platform } from 'react-native';
import { createRoot } from 'react-dom/client';
import { activateKeepAwake } from 'expo-keep-awake';
import * as Sentry from 'sentry-expo';
import withExpoRoot from 'expo/build/launch/withExpoRoot';
import App from './src/App';

if (__DEV__) {
  activateKeepAwake();
}

AppRegistry.registerComponent('main', () => withExpoRoot(App));
if ('web' === Platform.OS) {
  const rootTag = createRoot(document.getElementById('root') ?? document.getElementById('main'));

  const RootComponent = withExpoRoot(App);
  rootTag.render(<RootComponent />);
}
```

**Comment by jonjaques** [comment]
@JamesHemery Hehe. I am bootstrapping a new project - and 30m after you posted this, I was thinking about doing the same thing. ^ But I realized the amount of foreign code/imports I would have to fork into my app and decided I would live with the annoying error until it gets fixed upstream. Thank you for the diligence in reporting!

**Comment by JamesHemery** [comment]
> @JamesHemery Hehe. I am bootstrapping a new project - and 30m after you posted this, I was thinking about doing the same thing. ^ But I realized the amount of foreign code/imports I would have to fork into my app and decided I would live with the annoying error until it gets fixed upstream. Thank you for the diligence in reporting!

Of course, this is only a temporary solution :)

**Comment by devzucca** [comment]
same issue here, thanks for help, I'll wait for the solution here, thanks

**Comment by KieQuang** [comment]
@JamesHemery Thanks

**Comment by IshuSingh1** [comment]
> same issue here, thanks for help, I'll wait for the solution here, thanks

joining the waiting list

**Comment by EvanBacon** [comment]
Issue probably needs to be addressed upstream in react-native-web https://github.com/necolas/react-native-web/blob/3fc40bdf810901146b8a240a2d0399dee708cfff/packages/react-native-web/src/exports/render/index.js#L10

**Comment by raphaelrk** [comment]
Basically identical to @JamesHemery's solution, here's what I did for my web-only app:

- Change "main" in package.json to a custom file: `"main": "entry.js"`

- Created `entry.js`

```javascript
import 'expo/build/Expo.fx';
import { AppRegistry, Platform } from 'react-native';
import withExpoRoot from 'expo/build/launch/withExpoRoot';

import App from './src/App';
import { createRoot } from "react-dom/client";

AppRegistry.registerComponent('main', () => withExpoRoot(App));
if (Platform.OS === 'web') {
  const rootTag = createRoot(document.getElementById('root') ?? document.getElementById('main'));
  const RootComponent = withExpoRoot(App);
  rootTag.render(<RootComponent />);
}
```

**Comment by Albert-Gao** [comment]
Also related to this PR to fully embrace the concurrent React

https://github.com/necolas/react-native-web/pull/2330

**Comment by verifiedanswer** [comment]
[[Solved] Warning: ReactDOM.render is no longer supported in React 18](https://verifiedanswer.com/solved-warning-reactdom-render-is-no-longer-supported-in-react-18/)

**Comment by lukelu0520** [comment]
same issue +1
Look forward to the official solution for the warning.

**Comment by abdulkadir-polmayan** [comment]
is solution still doesnt appear?

**Comment by astriskit** [comment]
upgraded to expo-47 from 45 - the warning still is there; haven't tried above code though.

**Comment by mstykow** [comment]
The workaround from above no longer works in SDK 47 because `withExpoRoot` no longer exists.

**Comment by pipinet** [comment]
how to fix it?

**Comment by jasondavis87** [comment]
Giving credit to all those above who started me on this solution, i did this: 
- Change "main" in package.json from ```"node_modules/expo/AppEntry.js"``` to a custom file: ```"main": "entry.js"```
- Created ```entry.js```
```js
import "expo/build/Expo.fx";
import { Platform } from "react-native";
import { registerRootComponent } from "expo";
import { activateKeepAwake } from "expo-keep-awake";
import { createRoot } from "react-dom/client";
import App from "./App"; /* CHANGE THE PATH BASED ON WHERE YOURS IS LOCATED */

if (__DEV__) {
  activateKeepAwake();
}

if (Platform.OS === "web") {
  const root = createRoot(
    document.getElementById("root") ?? document.getElementById("main")
  );
  root.render(<App />);
} else {
  registerRootComponent(App);
}
```

I haven't tested it too too much but what i've tested thus far has worked. I'm doing an ios/android/web build and all 3 seem to be working on SDK 47. Hope this helps!

**Comment by imransilvake** [comment]
same issue. looking for an official fix

**Comment by necolas** [comment]
This is not an error, it's a warning. The API still works. React Native and React Native for Web do not officially support the new APIs in React 18 yet

**Comment by cubesmeta** [comment]
+1

**Comment by alexandre1921** [comment]
same issue +1

**Comment by devzucca** [comment]
> Dando crédito a todos los anteriores que me iniciaron en esta solución, hice esto:
> 
> * Cambie "main" en package.json de `"node_modules/expo/AppEntry.js"`a un archivo personalizado:`"main": "entry.js"`
> * Creado`entry.js`
> 
> ```js
> import "expo/build/Expo.fx";
> import { Platform } from "react-native";
> import { registerRootComponent } from "expo";
> import { activateKeepAwake } from "expo-keep-awake";
> import { createRoot } from "react-dom/client";
> import App from "./App"; /* CHANGE THE PATH BASED ON WHERE YOURS IS LOCATED */
> 
> if (__DEV__) {
>   activateKeepAwake();
> }
> 
> if (Platform.OS === "web") {
>   const root = createRoot(
>     document.getElementById("root") ?? document.getElementById("main")
>   );
>   root.render(<App />);
> } else {
>   registerRootComponent(App);
> }
> ```
> 
> No lo he probado demasiado, pero lo que he probado hasta ahora ha funcionado. Estoy haciendo una compilación ios/android/web y los 3 parecen estar funcionando en SDK 47. ¡Espero que esto ayude!

I tried it and the styles of the whole app were broken, thanks for the help, I tried to solve the error but it also breaks the app

> Basically identical to @JamesHemery's solution, here's what I did for my web-only app (may or may not work fine for non-web apps):
> 
> * Change "main" in package.json from `"node_modules/expo/AppEntry.js"` to a custom file: `"main": "entry.js"`
> * Created `entry.js`
> 
> ```js
> import 'expo/build/Expo.fx';
> import { AppRegistry, Platform } from 'react-native';
> import withExpoRoot from 'expo/build/launch/withExpoRoot';
> 
> import App from './src/App';
> import { createRoot } from "react-dom/client";
> 
> AppRegistry.registerComponent('main', () => withExpoRoot(App));
> if (Platform.OS === 'web') {
>   const rootTag = createRoot(document.getElementById('root') ?? document.getElementById('main'));
>   const RootComponent = withExpoRoot(App);
>   rootTag.render(<RootComponent />);
> }
> ```
> 
> * wrapped my app with <React.StrictMode>

I tried it and the styles of the whole app were broken, thanks for the help, I tried to solve the error but it also breaks the app

**Comment by julian-hecker** [comment]
Having this issue too. Commenting to get updates :)

**Comment by JamesHemery** [comment]
Update for SDK 47 : 

```js
import 'expo/build/Expo.fx';
import registerRootComponent from 'expo/build/launch/registerRootComponent';
import { createRoot } from 'react-dom/client';
import { createElement } from 'react';
import { Platform } from 'react-native';
import App from './src/App';

// @see https://github.com/expo/expo/issues/18485
if ('web' === Platform.OS) {
  const rootTag = createRoot(document.getElementById('root') ?? document.getElementById('main'));
  rootTag.render(createElement(App));
} else {
  registerRootComponent(App);
}
```

**Comment by Norfeldt** [comment]
To the folkes that uses [patch-package](https://www.npmjs.com/package/patch-package)

> patches/expo+47.0.8.patch

```
diff --git a/node_modules/expo/AppEntry.js b/node_modules/expo/AppEntry.js
index 9e1b283..ff89980 100644
--- a/node_modules/expo/AppEntry.js
+++ b/node_modules/expo/AppEntry.js
@@ -1,5 +1,14 @@
 import registerRootComponent from 'expo/build/launch/registerRootComponent';
+import { createRoot } from 'react-dom/client';
+import { createElement } from 'react';
+import { Platform } from 'react-native';
 
 import App from '../../App';
 
-registerRootComponent(App);
+// @see https://github.com/expo/expo/issues/18485
+if ('web' === Platform.OS) {
+  const rootTag = createRoot(document.getElementById('root') ?? document.getElementById('main'));
+  rootTag.render(createElement(App));
+} else {
+  registerRootComponent(App);
+}
```

**Comment by piyushjoshi1016** [comment]
> Update for SDK 47 :
> 
> ```js
> import 'expo/build/Expo.fx';
> import registerRootComponent from 'expo/build/launch/registerRootComponent';
> import { createRoot } from 'react-dom/client';
> import { createElement } from 'react';
> import { Platform } from 'react-native';
> import App from './src/App';
> 
> // @see https://github.com/expo/expo/issues/18485
> if ('web' === Platform.OS) {
>   const rootTag = createRoot(document.getElementById('root') ?? document.getElementById('main'));
>   rootTag.render(createElement(App));
> } else {
>   registerRootComponent(App);
> }
> ```

Thank you James. This worked for me.

**Comment by keystonecyberstop** [comment]
I faced this error:
"ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated"


it can be the issue of eslint
which is fixed by these steps:

steps:
1.  install a plugin for vs code, plugin name: ESLint
3.  adding this commented line '/* eslint-disable react/no-deprecated */'  at the top of index.js
