### ISSUE TITLE
[docs]  eas update vs eas build with ref. to releaseChannel / channel / branch

### ISSUE THREAD

**Issue by redcranesolutions** [expo/expo#18489]
### Summary

So in eas update docs (https://docs.expo.dev/eas-update/getting-started/), “channel“ is referenced for eas.json but in https://docs.expo.dev/distribution/release-channels/ it is referenced as “releaseChannel”, and then just to make it a bit more confusing, it seems to be referenced as “branch” for using “eas update --branch [branch]”. Talk about confusing! Could you please confirm which is which and if they are in fact all the same?

### Link to the related docs page

https://docs.expo.dev/eas-update/getting-started/
https://docs.expo.dev/distribution/release-channels/

### Anything else?

Would also be nice to know when eas update will be officially released for standard plan users. Only 4 months away until expo publish will be removed, so I'm sure we're not the only ones trying to get our projects moved over.

**Comment by redcranesolutions** [comment]
After hours of messing around it seems for eas build and eas update (not expo build or expo publish) your eas.json file now needs to use "channel" not "releaseChannel" and for use of eas update --branch is in fact the "channel" value. Still confusing. I understand the concept of it being a branch but 2 different naming will certainly increase issues posted in GitHub. Perhaps add this info in the docs this to make it clearer.

**Comment by brentvatne** [comment]
there is a wip PR to help clarify this: https://github.com/expo/eas-cli/pull/1082

sorry for the confusion!

**Comment by redcranesolutions** [comment]
> there is a wip PR to help clarify this: [expo/eas-cli#1082](https://github.com/expo/eas-cli/pull/1082)
> 
> sorry for the confusion!

Thanks Brent!
