### ISSUE TITLE
Expo client crashes on non-detached app on Android when permission is denied

### ISSUE THREAD

**Issue by tinaroh** [expo/expo#1848]
```
06-06 14:53:22.883 32695 32695 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void host.exp.exponent.h.g.a(int, java.lang.String[], int[])' on a null object reference
06-06 14:53:22.883 32695 32695 E AndroidRuntime: 	at host.exp.a.b.a(Exponent.java:256)
06-06 14:53:22.883 32695 32695 E AndroidRuntime: 	at host.exp.exponent.experience.a.onRequestPermissionsResult(BaseExperienceActivity.java:272)
06-06 14:53:22.883 32695 32695 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7720)
06-06 14:53:22.883 32695 32695 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7543)
06-06 14:53:22.883 32695 32695 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4485)
```

### Environment
Crashes on Android device:
Model: SM-G950U (Galaxy S8)
Android Version: 8.0.0

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.2
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.6.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/troh-63973324-5a86-4f8e-b5b0-7c5b4d497290.tar.gz

### Steps to Reproduce
This issue does not repro on iOS simulator or Snack. It repros on my Samsung Galaxy S8. I don't have any other physical Android devices so I haven't tried it elsewhere. But it reproduced on an app created via CRNA and XDE.

(Write your steps here:)
https://snack.expo.io/rkaYOK_eQ

1. Open app that requests for Camera permission on `componentWillMount`
2. When the dialog pops up for Camera permission, deny it

### Expected Behavior

App should not crash.

### Actual Behavior

App crashes.

### Reproducible Demo
https://snack.expo.io/rkaYOK_eQ
(Note: It doesn't repro on the Snack, only on the actual device.)

I tested after removing the `AUDIO_RECORDING` permission, and found that the first time it crashed but it didn't crash after I opened the Expo client and opened the app from within vs via XDE.

Could it be that `mPermissionsHelper` needs to also be set in [this method](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/expoview/Exponent.java#L251)? I was trying to test it out but got stuck setting up my expo dev environment.

**Comment by esamelson** [comment]
Hi @tinaroh - thanks for the report! I was able to repro this on my device. Unminified stacktrace is:
```
06-13 17:55:20.236 10673 10673 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void host.exp.exponent.utils.PermissionsHelper.onRequestPermissionsResult(int, java.lang.String[], int[])' on a null object reference
06-13 17:55:20.236 10673 10673 E AndroidRuntime: 	at host.exp.expoview.Exponent.onRequestPermissionsResult(Exponent.java:255)
06-13 17:55:20.236 10673 10673 E AndroidRuntime: 	at host.exp.exponent.experience.BaseExperienceActivity.onRequestPermissionsResult(BaseExperienceActivity.java:271)
06-13 17:55:20.236 10673 10673 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7429)
06-13 17:55:20.236 10673 10673 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7280)
06-13 17:55:20.236 10673 10673 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
06-13 17:55:20.236 10673 10673 E AndroidRuntime: 	... 9 more
```

@aalices - I noticed snack is also asking for camera permission at almost the same time; is it possible there's a race condition of some kind? 🤔

**Comment by aalices** [comment]
Looking into it! Anyway, you need to make the two `requestPermissions` calls separately - and wait for the first one to finish before calling the second one cause Android will show only one dialog. We probably could adjust the API so it can be invoked with an array of permissions instead of just one. 🤔

**Comment by tinaroh** [comment]
Thanks! I'll make that adjustment for my app.

**Comment by esamelson** [comment]
I'm going to close this as the original crash is fixed internally (thanks @aalices !). We have an internal ticket tracking the ability to request an array of permissions, but for now the workaround suggested here should work fine.
