### ISSUE TITLE
You cannot reload when expo-updates is not enabled

### ISSUE THREAD

**Issue by id3vz** [expo/expo#18480]
### Summary

I'm using `expo-updates`'s **reloadAsync** to reload app after changing language so the rtl/ltr direction can change.
after upgrading to SDK 46 it's not working anymore and gives me this error 
`[Unhandled promise rejection: Error: You cannot reload when expo-updates is not enabled.]`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.6.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.13.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31, 32
        Build Tools: 30.0.2, 30.0.3, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-Tiramisu | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: managed

### Reproducible demo

use reloadAsync from `expo-updates` to reload app

**Comment by RayBans2111** [comment]
I also am getting this issue when trying to use reloadAsync. I have a button that calls Updates.reloadAsync() when completing a call. This used to work beforehand in Expo 44,45.

**Comment by sagihsh** [comment]
Having the same issue in SDK 44! (after upgrading Expo Go app version).
reloadAsync worked great with Expo Go version 2.24.3.1014878.
But since upgrading to 2.25.1.1015582 each reloadAsync call ends with this error:

[Unhandled promise rejection: Error: You cannot reload when expo-updates is not enabled.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:27:27 in moduleName.methodInfo.name
at node_modules/expo-updates/build/Updates.js:97:7 in reloadAsync
at node_modules/expo-updates/build/Updates.js:97:7 in reloadAsync
at global/languageHandler.ts:10:38 in applyPrefferedLanguage

Would highly appreciate a fix!

**Comment by isaachinman** [comment]
Also experiencing this issue in Expo 45. Most likely this must be a regression in Expo Go itself, not the core SDK?

**Comment by PeterAbdalla** [comment]
Facing the same issue after updating to SDK 46. This used to work in SDKs 44 & 45.
Any known workaround?

**Comment by RayBans2111** [comment]
I wanted to add on another discovery for this bug. I seem to get my desired outcome from Updates.reloadAsync() on Android, but not on iOS.

**Comment by berkaygurbuz** [comment]
You can not use `expo updates` on development mode. [More information](https://docs.expo.dev/versions/latest/sdk/updates/?redirected#updatesreloadasync)

> This method cannot be used in development mode, and the returned promise will be rejected if you try to do so.

**Comment by isaachinman** [comment]
@berkaygurbuz First, the issue only appears on iOS. Second, users posting in this issue (myself included) started seeing the error randomly, without bumping any major version.

**Comment by RayBans2111** [comment]
It doesn't help that there wasn't an announcement for this change either, with a way to remedy it. It works fine in production, but is moderately annoying that it no longer functions as it did in development. 

If we're not supposed to use it in development, why does it still function on android?

**Comment by contactsimonwilson** [comment]
React native exposes DevSettings.reload, which should act as a suitable replacement. We have re-exported reloadAsync in our project
`export const reloadAsync = __DEV__ ? DevSettings.reload : reloadUpdatesAsync;
`

**Comment by contactsimonwilson** [comment]
Bad bot, there should still be a resolution to this.

**Comment by douglowder** [comment]
In SDK 48, we do provide the ability to have a "native debug" build, where the app is built with a debug configuration in Xcode or Android Studio, but the app still downloads updates and `reloadAsync()` will work as expected.

This document may be helpful: https://docs.expo.dev/eas-update/eas-update-with-local-build/
