### ISSUE TITLE
[EAS][GLView] Text & images not displayed on production build

### ISSUE THREAD

**Issue by baochungit** [expo/expo#18483]
### Summary

I'm using GLView along with Expo Pixi. It seems fine on development (including development build that run with Expo GO) but when testing with the production build the text and images are not showing, only graphics (rectangle, circle,...) are showing.

I had tried the build from classic build (expo build), it worked well while the EAS build not.

Anyone experienced this issue? Please help...

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    Expo Workflow: managed

### Reproducible demo

Because Expo Pixi using Expo2DCanvas (via @expo/browser-polyfill) for rendering canvas stuff, so I had tried the code bellow then had the same result (text not displaying).

```
import { GLView } from "expo-gl";
import React from "react";
import Expo2DContext from "expo-2d-context";

export default class App extends React.Component {
  render() {
    return (
      <GLView style={{ flex: 1 }} onContextCreate={this._onGLContextCreate} />
    );
  }
  _onGLContextCreate = (gl) => {
    var ctx = new Expo2DContext(gl);
    ctx.translate(50, 200);
    ctx.scale(4, 4);
    ctx.fillStyle = "grey";
    ctx.fillRect(20, 40, 100, 100);
    ctx.fillStyle = "white";
    ctx.fillRect(30, 100, 20, 30);
    ctx.fillRect(60, 100, 20, 30);
    ctx.fillRect(90, 100, 20, 30);
    ctx.beginPath();
    ctx.arc(50, 70, 18, 0, 2 * Math.PI);
    ctx.arc(90, 70, 18, 0, 2 * Math.PI);
    ctx.fill();
    ctx.fillStyle = "grey";
    ctx.beginPath();
    ctx.arc(50, 70, 8, 0, 2 * Math.PI);
    ctx.arc(90, 70, 8, 0, 2 * Math.PI);
    ctx.fill();
    ctx.strokeStyle = "black";
    ctx.beginPath();
    ctx.moveTo(70, 40);
    ctx.lineTo(70, 30);
    ctx.arc(70, 20, 10, 0.5 * Math.PI, 2.5 * Math.PI);
    ctx.stroke();

    // the text here not showing on production build
    await ctx.initializeText();
    ctx.fillStyle = "blue";
    ctx.font = "italic 72pt sans-serif";
    ctx.fillText("Hey Galaxy", 50, 100);

    ctx.flush();
  };
}
```

**Comment by baochungit** [comment]
After debugging, I see the Asset return with localUri is like `src_assets_textures_spritesheet` not `file:///path/spritesheet.png` as usual.
That would make the texture not rendering.

**Comment by baochungit** [comment]
And how about this one? I see it's quite similar to my issue
https://github.com/expo/expo/issues/10906

**Comment by alefyufca** [comment]
Has anyone managed to resolve this problem?
