### ISSUE TITLE
expo-speech not working

### ISSUE THREAD

**Issue by DabaMcD** [expo/expo#18484]
### Summary

I am trying to create the simplest possible project using expo-speech. In fact, I have simply copied the code from the example at https://docs.expo.dev/versions/latest/sdk/speech/

I'm getting these two errors. See attached screenshot of my metro terminal. I have no idea what to do. Apparently there's some constant that has not been set. Any way around this?

![image](https://user-images.githubusercontent.com/45501794/182723273-b534cd17-ff52-4310-8b4e-4c9af0e01fe8.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    npmPackages:
      react: 18.0.0 => 18.0.0
      react-native: 0.69.3 => 0.69.3
    Expo Workflow: bare

### Reproducible demo

I have used the same app.js file as that which is here: https://snack.expo.dev/@dabamcd/speech (note that this is just a copy of the example code in the documentation)

Everything else in my project folder is pre-set by npm init.

Of course I have run

> expo install expo-speech

and

> npx react-native run-android

but that's all.

**Comment by barthap** [comment]
Do you have `expo` package installed? See https://docs.expo.dev/bare/installing-expo-modules/ and https://github.com/expo/expo/tree/sdk-46/packages/expo-speech#installation-in-bare-react-native-projects
