### ISSUE TITLE
Second instance of app is launched when Open notification from statusbar

### ISSUE THREAD

**Issue by veedeo** [expo/expo#1849]
I found an issue on Android. Galaxy 6 and 8. 
Standalone
SDK: 27.0.0

1. When the app is killed and pressing on systray notification, opens the app and gets event as expected. But then if I minimize the app and tap on app icon it loads everything from scratch. And taping new systray notifications will reopen the app, but no event is received.
2. Open app via home icon, app is foregrounded, when new push arrives Im getting Notification events as expected. If I tap on systray notification it loads new instance of the app and Im not able to get events enymore.

**Comment by quinlanj** [comment]
hey @veedeo , thanks for reporting this bug.

It is difficult to find the exact problem with the information provided. Could you give us more information to root cause (ie) screenshots, basic toy app with problem, error logs?

**Comment by quinlanj** [comment]
a toy app built with snack.expo.io that has the issue would be really helpful

**Comment by veedeo** [comment]
@quinlanj I recorded video for first issue. https://www.youtube.com/edit?o=U&video_id=yInWRVmCkmE
Ill try to reproduce it on snack

**Comment by veedeo** [comment]
Another issue:
1. Application is killed, clicking in Push notification opens application and receives Notification event.
2. Put app to background and send push, Clicking on push brings app foreground but no event is received.
3. Leave App foreground and send push, Event is received as expected
https://www.youtube.com/watch?v=z1nnlOopXQI

**Comment by esamelson** [comment]
Hi @veedeo - could you try upgrading to the latest SDK (28) and let us know if the issue is still present there?

If so, a snack that reproduces this issue when built as a standalone app would be really helpful. Without an repro example it's hard for us to root cause this.

**Comment by veedeo** [comment]
Im on latest SDK 28

**Comment by cruzach** [comment]
Hey @veedeo, without a sample project that reproduces this issue, it's really difficult to say what could cause this. 

If you're still seeing this behavior, place the project code used to build the standalone app that will reproduce this behavior in a [snack](https://snack.expo.io/), and share it here
