### ISSUE TITLE
[GLView][Expo2DContext][SDK45][Expo-GO-2.25.1] Crash when loading Expo2DContext demo with latest Expo GO app

### ISSUE THREAD

**Issue by sandlands** [expo/expo#18493]
### Summary

I have just installed the latest version of Expo GO (2.25.1, "added support for SDK 46"). My project is using SDK 45. That results in a crash when I try to use Expo2DContext in combination with GLView (on both iOS and Android). I have the latest version of expo-cli. When I upgrade to SDK 46, the issue is solved. Since SDK 46 has just been released, it should still be supposed to work with SDK 45, right?

**Used phones**
- iPhone XS (Expo GO 2.25.1)
- Samsung Galaxy A32 (SM-A326B) (Expo GO 2.25.1, installed via [APK](https://d1ahtucjixef4r.cloudfront.net/Exponent-2.25.1.apk) since it had not been released in Play Store at the time of writing)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 11.6.5
Shell: 5.0.16 - /usr/local/bin/bash
Binaries:
Node: 16.13.1 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 8.3.0 - /usr/local/bin/npm
Watchman: 2022.01.03.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.2 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
Android SDK:
Android NDK: 23.1.7779620
IDEs:
Android Studio: 2021.2 AI-212.5712.43.2112.8609683
Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
npmPackages:
expo: ~45.0.0 => 45.0.8
react: 17.0.2 => 17.0.2
react-dom: 17.0.2 => 17.0.2
react-native: 0.68.2 => 0.68.2
react-native-web: 0.17.7 => 0.17.7
npmGlobalPackages:
eas-cli: 0.56.0
expo-cli: 6.0.1
Expo Workflow: managed

### Reproducible demo

```
expo init [choose blank (Typescript)]
expo install expo-gl expo-2d-context
```
Replace App.tsx with [demo](https://github.com/expo/expo-2d-context#example) from expo-2d-context docs (see below).

`expo start`

App.tsx:
```
import { GLView } from "expo-gl";
import React from "react";
import Expo2DContext from "expo-2d-context";

export default class App extends React.Component {
  render() {
    return (
      <GLView style={{ flex: 1 }} onContextCreate={this._onGLContextCreate} />
    );
  }
  _onGLContextCreate = (gl) => {
    var ctx = new Expo2DContext(gl);
    ctx.translate(50, 200);
    ctx.scale(4, 4);
    ctx.fillStyle = "grey";
    ctx.fillRect(20, 40, 100, 100);
    ctx.fillStyle = "white";
    ctx.fillRect(30, 100, 20, 30);
    ctx.fillRect(60, 100, 20, 30);
    ctx.fillRect(90, 100, 20, 30);
    ctx.beginPath();
    ctx.arc(50, 70, 18, 0, 2 * Math.PI);
    ctx.arc(90, 70, 18, 0, 2 * Math.PI);
    ctx.fill();
    ctx.fillStyle = "grey";
    ctx.beginPath();
    ctx.arc(50, 70, 8, 0, 2 * Math.PI);
    ctx.arc(90, 70, 8, 0, 2 * Math.PI);
    ctx.fill();
    ctx.strokeStyle = "black";
    ctx.beginPath();
    ctx.moveTo(70, 40);
    ctx.lineTo(70, 30);
    ctx.arc(70, 20, 10, 0.5 * Math.PI, 2.5 * Math.PI);
    ctx.stroke();
    ctx.flush();
  };
}
```

**Comment by kirtikapadiya** [comment]
expo-pixi@2.1.0 with SDK 45 (Managed project)  is not working with latest expo go (2.25.1) in iPhone 12.
Reproducible snack is here https://snack.expo.dev/@kirtikk/signaturecrash

**Comment by ShaneBurkhart** [comment]
this is happening for me too but not pixi. i've narrowed it down to the version of the expo go app. for some reason, the new version of expo go crashes now.

rashes with expo-gl 11.3.0. this setup works when i switch to an ipad that has a previous version of expo go. only the new expo go crashes. this has been working in production for a while.

**Comment by wkozyra95** [comment]
@sandlands @ShaneBurkhart 
I tested the cases you described and could not reproduce any issues, please provide repo with full example that reproduces the issue.

In my tests I used:
 - Expo Go 2.25.1
 - expo-gl 11.3.0
 - sdk 45
 - example from expo-2d-context

**Comment by wkozyra95** [comment]
I confirmed the issue is happening and I'm working on the fix, but from what I see the it is only happening on iOS, so if anyone is still experiencing that on android please provide reproduction steps/example project.

The issue was caused by a breaking change in react-native, it's not a problem with the code itself, but more with the way our libraries are packaged/versioned in Expo Go. This issue affects only Expo Go, in a meantime, you can still use a custom dev client, and create test flight builds.

**Comment by ShaneBurkhart** [comment]
thank you, we switched to the custom dev client

**Comment by JAWS-tm** [comment]
Hi, I still have the same issue, do you find a solution please ? 
If not, how can I edit saturation, contrast, etc of a picture without expo gl ?

Thank's !
