### ISSUE TITLE
[docs] Facebook Documentation is missing

### ISSUE THREAD

**Issue by robertoosantos** [expo/expo#18497]
### Summary

The expo-facebook is going to be deprecated in EXPO 46, but there's no Expo Facebook documentation anymore, and react-native-fbsdk-next does not explain how to use it with Expo Managed App.

My expo-facebook login in production with Expo 45 is crashing the app in some Android Devices and I don't have a viable alternative.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/facebook

**Comment by Simek** [comment]
Hello @robertoosantos,

`expo-facebook` was a deprecated package in SDK 45 and has been removed in the latest release, so the docs for this package also has been removed. You can read more about it in the release blog:
* https://blog.expo.dev/expo-sdk-46-c2a1655f63f7#a58e

However, the SDK 45 docs still exists and contain `expo-facebook` page with the full documentation:
* https://docs.expo.dev/versions/v45.0.0/sdk/facebook/

**Comment by robertoosantos** [comment]
Thanks, Simek. But there's no explanation about how to replace expo-facebook with [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/#expo-installation).

As far as I've tried, there is not way to replace it without moving from managed to bare workflow. Is that it?

By Expo 46, if the app uses Facebook Authentication it will must be bare workflow?

**Comment by Simek** [comment]
As mentioned on the SDK 45 page note, you need to migrate to use `expo-dev-client` instead of Expo Go, if you want to use the recommended package in managed flow:
* https://docs.expo.dev/development/introduction/

**Comment by robertoosantos** [comment]
Thanks again, Simek. After moving to expo-dev-client, there was an evolution. But still doesn't show the facebook login button.

The error:

```
Your app just crashed. See the error below.

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.AccessTokenTracker.stopTracking()' on a null object reference
at com.facebook.reactnative.androidsdk.FBAccessTokenModule.onCatalystInstanceDestroy(FBAccessTokenModule.java:81)
at com.facebook.react.bridge.BaseJavaModule.invalidate(BaseJavaModule.java:76)
at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:110)
at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:108)
at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:368)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:164)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
at java.lang.Thread.run(Thread.java:764)
```

The code:
```javascript
import React from 'react'
import { LoginButton, AccessToken } from 'react-native-fbsdk-next';

function FacebookLogin(props) {
    return (
        <LoginButton
            onLoginFinished={
                (error, result) => {
                    if (error) {
                        console.log("login has error: " + result.error);
                    } else if (result.isCancelled) {
                        console.log("login is cancelled.");
                    } else {
                        AccessToken.getCurrentAccessToken().then(
                            (data) => {
                                console.log(data.accessToken.toString())
                            }
                        )
                    }
                }
            }
            onLogoutFinished={() => console.log("logout.")} />
    )
}

export default FacebookLogin
```

**Comment by BrodaNoel** [comment]
I would say that now it's time to move this report to `react-native-fbsdk-next`.
This is not an `Expo` error, so, in order to get faster and better help, it may be a good idea to report this issue there

**Comment by robertoosantos** [comment]
Agree. I made it work by moving to bare workflow and making the Gradle and Manifest configurations.

I'd really appreciate if this very usual  feature "social login", to be better documented and works with managed workflow in Expo because the documentation quality and developer experience are outstanding.

**Comment by shivamgr8** [comment]
> Agree. I made it work by moving to bare workflow and making the Gradle and Manifest configurations.
> 
> I'd really appreciate if this very usual feature "social login", to be better documented and works with managed workflow in Expo because the documentation quality and developer experience are outstanding.

Hey, Now I am facing the same problem in the expo while using react-native-fbsdk-next library. Can you provide more details on how to fix it? It will be very helpful for me.

**Comment by dembal1990** [comment]
I have a same issue with `react-native-fbsdk-next` (12.1.0)

**Comment by monolith-ai-corp** [comment]
Yeah me too, facing the same issue.....
```
 ERROR  Your app just crashed. See the error below.
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.AccessTokenTracker.stopTracking()' on a null object reference
  com.facebook.reactnative.androidsdk.FBAccessTokenModule.onCatalystInstanceDestroy(FBAccessTokenModule.java:81)
  com.facebook.react.bridge.BaseJavaModule.invalidate(BaseJavaModule.java:76)
  com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:110)
  com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:108)
  com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:359)
  android.os.Handler.handleCallback(Handler.java:873)
  android.os.Handler.dispatchMessage(Handler.java:99)
  com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
  android.os.Looper.loop(Looper.java:201)
  com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
  java.lang.Thread.run(Thread.java:764)
```
