### ISSUE TITLE
Push notification on iOS not working

### ISSUE THREAD

**Issue by telmen** [expo/expo#185]
Push Notification just working fine on Android. But it seems like not gonna work on iOS. Nothing happens on iOS. Are there any known issues? I mean cannot get push token;
``
"expo": "15.1.3",
"react-native": "0.42.3",
``

**Comment by FacuAcosta** [comment]
If you are testing the notifications on an iOS Simulator, they only work on a physical device.

**Comment by telmen** [comment]
Actually, I'm testing on a real device. iOS 10.3

**Comment by telmen** [comment]
Any help?

**Comment by FacuAcosta** [comment]
Hmmm I only used notifications on Android, so I don't know how do they work on iOS. Maybe this can help: [Link](https://docs.expo.io/versions/v16.0.0/guides/push-notifications.html#push-notifications)

**Comment by telmen** [comment]
@ide @dikaiosune

**Comment by telmen** [comment]
I already followed the guide in the documentation so now I have a working notification on Android but an iOS.

**Comment by terribleben** [comment]
Hi, can you provide some code or a sample app that reproduces the behavior? There's not enough information to determine what's going on at this point.

**Comment by telmen** [comment]
In one of my scenes, I have 
`async _getExponentPushTokenAsync() {
		try {
			let { status } = await Permissions.askAsync(
				Permissions.REMOTE_NOTIFICATIONS
			)
			if (status !== "granted") {
				return
			}
			let pushToken = await Notifications.getExponentPushTokenAsync()
			console.log(`Got push token: ${pushToken}`)
		} catch (error) {}
	}
`
`
_getExponentPushToken = () => {
	 	this._getExponentPushTokenAsync().catch(error =>
	 		console.log(`Error${error}`)
	 	)
	}
`
And I have a button which calls _getExponentPushToken function onPress property. And on an iOS nothing happens but on Android I could retrieve a push token.

**Comment by terribleben** [comment]
What does `await Permissions.getAsync(Permissions.REMOTE_NOTIFICATIONS)` return?

**Comment by telmen** [comment]
Sorry my bad. My Expo application's notification has been turned off. Sorry. silly mistake.

**Comment by terribleben** [comment]
Awesome, glad it's working for you!

**Comment by madaviela** [comment]
im getting an error when im trying to follow the guide for set up push notifications, im usinc expo proyect sdk 20 and also real devices, i can get the expopushtoken but when i post to my server it says an error 422

`
    async registerPN() {
        const { existingStatus } = await Permissions.getAsync(Permissions.REMOTE_NOTIFICATIONS);
        let finalStatus = existingStatus;
      
        // only ask if permissions have not already been determined, because
        // iOS won't necessarily prompt the user a second time.
        if (existingStatus !== 'granted') {
          // Android remote notification permissions are granted during the app
          // install, so this will only ask on iOS
          const { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);
          finalStatus = status;
        }
      
        // // Stop here if the user did not grant permissions
        // if (finalStatus !== 'granted') {
        //   return;
        // }
      
        // Get the token that uniquely identifies this device
        let tookeeen = await Notifications.getExpoPushTokenAsync();
        console.log("AN ERROR OCCURED:\n" + tookeeen)     

        let peticion = fetch("https://domain.com
![captura de pantalla 2017-08-26 a la s 16 35 18](https://user-images.githubusercontent.com/10695637/29745301-9875e3a0-8a7c-11e7-9c58-243f6935ff3f.png)
/api/exponent/devices/subscribe", {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + this.state.Auth
            
          },
          body: JSON.stringify({
            token: {
              value: tookeeen,
             },
             user: {
              username: 'David',
             },
          }),
        });
        console.log(peticion)
    }`

**Comment by dikaiosune** [comment]
@madaviela make sure you `await` on calls to `fetch`.

**Comment by ArthurBK** [comment]
I tried this snippet: [https://snack.expo.io/ry526Qu3e](url)
=> on Android it works fine
=> on IOS, reveivedNofication gets a null response from the async call `Permissions.askAsync( Permissions.REMOTE_NOTIFICATIONS`
Notifications are turned on on my Iphone, any idea why the call is failing?
