### ISSUE TITLE
ImagePicker crashes on Ios with firebase storage

### ISSUE THREAD

**Issue by FakhruddinAbdi** [expo/expo#1850]
When i try to  upload multiple images from gallery using expo image picker, it will crash and close the app and restart it on standalone app published to appstore testflight.

It works fine on expo client.

Im using firebase storage to keep the uploaded images.
  
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.6.0
  Yarn: 1.6.0
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
  expo: ^27.0.2   => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz => 0.55.2

### Steps to Reproduce
just build using 'exp build:ios' then submit the build to appstore.. When you download the app then and use the standalone version it will crash if you upload multiple ( not at same time) images from gallery.

**Comment by ccheever** [comment]
Hi-

Just to check, did you make sure you asked for the correct permissions before using the gallery?
You may have asked for them at some point and granted them in Expo Client but then not necessarily done so in your standalone app.

Permissions `Permissions.CAMERA_ROLL` is required on iOS

**Comment by FakhruddinAbdi** [comment]
Hi @ccheever .

Yes Im aware of permissions and have granted them correctly.
The problem appear just when you upload from gallery more than once ( usually three times), the first upload will be done successfully.

So it shouldn't be a permission issue i think.

**Comment by FakhruddinAbdi** [comment]
I recently added `"usesIcloudStorage": true,` option to the app.json
First do we should re-submit to appstore for that change or the OTA will update the app?
And does this option fix the issue?

**Comment by FakhruddinAbdi** [comment]
@ccheever I just enabled pref monitor to check memory and cpu usages.
And found out that normal memory usage before crash ( uploading images ) is about 350 MB but after uploading the photos it take more than 650 MB

Could be the reason for the crash?
And if yes how i should manage to fix it ?
I have a functionality which user can send a post.
And the post could have a image up to 5 images

**Comment by FakhruddinAbdi** [comment]
expo team ? could you help with this issue

**Comment by FakhruddinAbdi** [comment]
A new information about this issue:

In the testflight dashboard i see 0 crash report and when i connect my iphone to the mac and open crash window from xcode and re-do the action which cause the crash, the crash report show nothing

So after some more googling, i think its not a crash, its a memory leak
It just restart the application.
I couldn't find a useful information from xcode instrument.
And from expo pref monitor it just show the memory sometimes exceed 500MB.

Just i can not understand why just the crash happen when i use `ImagePicker.launchImageLibraryAsync` But when user Camera it works fine !

**Comment by FakhruddinAbdi** [comment]
https://github.com/invertase/react-native-firebase/issues/247

This issue has been discussed on the given link.

**Comment by terribleben** [comment]
Hey @FakhruddinAbdi thanks for the update. Are you saying your issue was resolved in that react-native-firebase link?

**Comment by FakhruddinAbdi** [comment]
Actually i had to detach from expo and it didn't let me use react-native-firebase package and also can not add/change native codes.

Im still working on detaching and as soon as i publish the next version to testflight i will update this thread if it has been fixed by rnf package.

Thanks @terribleben ;

**Comment by iRayan7** [comment]
@FakhruddinAbdi Any updates?

**Comment by FakhruddinAbdi** [comment]
@iRayan7 https://github.com/invertase/react-native-firebase/issues/1232#issuecomment-399338859

**Comment by iRayan7** [comment]
@FakhruddinAbdi
So detach it is then :( 
Thanks.

**Comment by FakhruddinAbdi** [comment]
Yes ... I have detached already.
