### ISSUE TITLE
[NavigationBar][Android] Behavior `inset-swipe` not working well

### ISSUE THREAD

**Issue by baochungit** [expo/expo#18515]
### Summary

I'm using Samsung Galaxy Note 10 Plus.
My phone is set to hide bottom navigation bar by default. When I do swipe, at the bottom navigation bar there is a black blank bar appearing and it keep staying there. The action NavigationBar.setVisibilityAsync('hidden') could not hide it as well.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

45

### Environment

System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    Expo Workflow: managed

### Reproducible demo

```
export default function App() {
  const visibility = NavigationBar.useVisibility();

  useEffect(() => {
    setFullScreenMode();
  }, []);

  useEffect(() => {
    if (visibility === 'visible') {
      const interval = setTimeout(() => {
        NavigationBar.setVisibilityAsync('hidden');
      }, 3000);

      return () => {
        clearTimeout(interval);
      };
    }
  }, [visibility]);

  const setFullScreenMode = async (hidden = true) => {
    // sticky-immersive
    NavigationBar.setPositionAsync('absolute');
    NavigationBar.setVisibilityAsync('hidden');
    NavigationBar.setBehaviorAsync('inset-swipe');
    NavigationBar.setBackgroundColorAsync('#00000080');
    setStatusBarHidden(true, 'none');
  };
}
```

And in app.json expo
```
"androidStatusBar": {
  "hidden": true
},
"plugins": [
  [
    "expo-navigation-bar",
    {
      "position": "absolute",
      "visibility": "hidden",
      "behavior": "inset-swipe",
      "backgroundColor": "#00000080"
    }
  ]
],
```

**Comment by sweebee** [comment]
same for me on SDK46

**Comment by i-in-range** [comment]
You can try:
1. Play with `backround` here:
```javascript
<NavigationContainer
      theme={{
            dark: true,
            colors: {
                primary: "",
                background: "#000",
                card: "",
                text: "",
                border: "",
                notification: "",
            },
      }}
>
```

2. Try change system background:
```javascript
import * as SystemUI from "expo-system-ui";
SystemUI.setBackgroundColorAsync("#000")
```
