### ISSUE TITLE
Expo , white screen when launching project

### ISSUE THREAD

**Issue by thesogafoi** [expo/expo#1851]
Hey guys i use XDE-2.24.4  and when i click on My  project to run it ( android or ios  ) XDE get freezing and  XDE's page getting white Color and nothing show , and when i reload it  , at the first page i can see my project again and XDE Don't build anything for me 

when i select on project 
![untitled2](https://user-images.githubusercontent.com/24393498/41203442-bd47a5a0-6c8b-11e8-87d2-dc7fec402276.jpg)

and a few Later show me this 

![untitled](https://user-images.githubusercontent.com/24393498/41203445-c7ea2172-6c8b-11e8-94cb-3ef4e3cf501e.jpg)

**Comment by sjchmiela** [comment]
Hey, @thesogafoi! Expo XDE has been recently deprecated in favor of Expo CLI See the [release blog post](https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c). 🙂 I think this issue should be fixed in this new set of tools. 🎉
