### ISSUE TITLE
A problem occurred evaluating project ':expo-modules-core'. > Illegal char <*> at index 79: C:\fftr\app\node_modules\react-native\ReactAndroid\build\intermediates\library_*\*\jni

### ISSUE THREAD

**Issue by cristiano-futturis** [expo/expo#18519]
### Summary

Hey guys.
I need help for fix this error, I don't get it what's the problem below:

BUILD FAILED in 28s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: C:\fftr\app\node_modules\react-native-gradle-plugin\src\main\java\com\facebook\react\codegen\generator\SchemaJsonParser.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\fftr\app\node_modules\expo-modules-core\android\build.gradle' line: 56

* What went wrong:
A problem occurred evaluating project ':expo-modules-core'.
> Illegal char <*> at index 79: C:\fftr\app\node_modules\react-native\ReactAndroid\build\intermediates\library_*\*\jni

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 28s

    at makeError (C:\fftr\app\node_modules\execa\index.js:174:9)
    at C:\fftr\app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\fftr\app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\fftr\app\node_modules\@react-native-community\cli\build\index.js:192:9)

this is my react-native info:

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 9.15 GB / 23.85 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
      Android NDK: 22.1.7171670
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.3 => 0.69.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

So, what do you think about?

### What platform(s) does this occur on?

Android

### SDK Version

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 31.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ^46.0.0 => 46.0.2
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.3 => 0.69.3
      react-native-web: ~0.18.7 => 0.18.7
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: bare

### Reproducible demo

def REACT_NATIVE_SO_DIR = REACT_NATIVE_BUILD_FROM_SOURCE
  ? Paths.get(findProject(":ReactAndroid").getProjectDir().toString(), "build", "intermediates", "library_*", "*", "jni")
  : "${buildDir}/react-native-0*/jni"

**Comment by ShaoGongBra** [comment]
没有人遇到问题吗，解决不了

**Comment by saif-o99** [comment]
happens to me also, this is major issue

**Comment by BrainTech-Code** [comment]
me also i have this issue

**Comment by asadalibest1** [comment]
me too

**Comment by JonathanReiss15** [comment]
I am also having this issue even with a bare create-expo-app --- this should hopefully be enough to reproduce?

**Comment by m1rose28** [comment]
I also have this issue :-(

**Comment by vashisth00** [comment]
Still have this issue :/
