### ISSUE TITLE
[SDK 46] Android build crashes because "incompatible version of Kotlin"

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#18512]
### Summary

After upgrading from `SDK 44` to `SDK 46` (yes, 2 versions jump), I'm getting this error after `eas build -p android --clear-cache --auto-submit`):

```
The class is loaded from /home/expo/.gradle/caches/transforms-3/f9a6c4180d9d810f143b823eeeb39ba3/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
[stderr] 
e: /home/expo/workingdir/build/node_modules/react-native-purchases/android/src/main/java/com/revenuecat/purchases/react/RNPurchasesConverters.kt: (84, 44): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[stderr] 
The class is loaded from /home/expo/.gradle/caches/transforms-3/f9a6c4180d9d810f143b823eeeb39ba3/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
[stderr] 
e: /home/expo/workingdir/build/node_modules/react-native-purchases/android/src/main/java/com/revenuecat/purchases/react/RNPurchasesConverters.kt: (85, 43): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[stderr] 
The class is loaded from /home/expo/.gradle/caches/transforms-3/f9a6c4180d9d810f143b823eeeb39ba3/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
[stderr] 
FAILURE: Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':react-native-purchases:compileReleaseKotlin'.
[stderr] 
> Compilation error. See log for more details
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 9m 49s
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 15 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
596 actionable tasks: 596 executed
Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

SDK 46

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 27, 31
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 27.0.3, 28.0.3, 29.0.2
        System Images: android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.2
      react: 18.0.0 => 18.0.0
      react-native: 0.69.3 => 0.69.3
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: managed
```

### Reproducible demo

Please let me know if this is necessary. Should I create a new project and build it?

Link to the build: https://expo.dev/accounts/brodanoel/projects/[HERE-MY-SLUG]/builds/5239dacd-6a9f-41ec-a5ab-a157676e88c7

**Comment by brentvatne** [comment]
it looks like you have already created an issue on the react-native-purchases repo, which would be the correct spot for this

**Comment by brentvatne** [comment]
notice, however, you can override the kotlinVersion in that library as usual: https://github.com/RevenueCat/react-native-purchases/blob/main/android/build.gradle#L119

so you can use expo-build-properties to set the kotlinVersion variable in your project. you can set it to 1.6.10

**Comment by BrodaNoel** [comment]
Ufff... maaaan... This is a never ending learning process!

@brentvatne I have no idea what even is kotlin. My mind is just about to explote hahaha. Starter migrating from SDK 44 to SDK 46 (migrating expo-facebook, expo-google-signin, expo-amplitude, etc...). I'm kind of burned right now.

Could you please give me a bit more of details about what in the [heaven](https://www.youtube.com/watch?v=s6TtwR2Dbjg&ab_channel=BryanAdamsVEVO) is that kotlin version?, what could go wrong if I change it? Is it safe to change it?

And mainly: Where can I change it? `app.json`? I'm THIS close to create a patch to change that line 119 hehehe

**Comment by brentvatne** [comment]
here's the docs page for expo-build-properties: https://docs.expo.dev/versions/latest/sdk/build-properties/

install that library and configure the plugin as explained in the example on that page :) kotlin is a programming language that runs on the jvm like java.

**Comment by BrodaNoel** [comment]
Are we talking about this?: https://docs.expo.dev/versions/latest/sdk/build-properties/

**Comment by BrodaNoel** [comment]
Off topic:

So Kotlin is just another layer between the code and the native code.

What it comes to my mind every time somebody asks me "how many layer are between the code and the native?":

![image](https://user-images.githubusercontent.com/1837969/183002931-cfdd35ff-a2bb-4787-b286-55c8e35b3a1f.jpeg)

**Comment by brentvatne** [comment]
@BrodaNoel - haha, not really. kotlin is an alternative to java which is increasingly popular as an alternative. it's like swift is to objc, but on the android side.

**Comment by BrodaNoel** [comment]
Thanks for the info!

**Comment by BrodaNoel** [comment]
Worked:

```
      [
        "expo-build-properties",
        {
          "android": {
            "kotlinVersion": "1.6.10"
          }
        }
      ],
```

Thanks!
