### ISSUE TITLE
[SDK46][expo-status-bar] Render error when using `expo-status-bar` in monorepo

### ISSUE THREAD

**Issue by jferrettiboke** [expo/expo#18516]
### Summary

Render error when installing a fresh Expo project in monorepo. `yarn create expo-app apps/app -t expo-template-blank-typescript@46`

As soon as I remove `import { StatusBar } from "expo-status-bar";` from `App.tsx`, it works.

![Simulator Screen Shot - iPhone 13 Pro - 2022-08-05 at 11 27 36](https://user-images.githubusercontent.com/11066224/183047921-f45c5c58-05ff-4a02-9bc0-17df84ace8d8.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: managed
```

### Reproducible demo

1. Set up a monorepo (follow [this guide](https://docs.expo.dev/guides/monorepos/) for reference)
2. `yarn create expo-app apps/app -t expo-template-blank-typescript@46`

**Comment by brentvatne** [comment]
we need a clonable github repo. my guess here is that you have multiple versions of react in your monorepo. run `yarn why react`
