### ISSUE TITLE
Extra argument 'eventDispatcher' in call

### ISSUE THREAD

**Issue by akjesto** [expo/expo#18524]
### Summary

I am using expo-modules-core ("expo-modules-core": "^0.9.2"). 
I have tried npm install and pod install from my terminal and dependencies are successfully installed.
Then I tried to run the app with Xcode 13.0 but I am getting the following error and it becomes build failed.

**node_modules/expo-modules-core/ios/Swift/Views/ComponentData.swift:22:84: Extra argument 'eventDispatcher' in call**

 The error showing in the following method inside the file (node_modules/expo-modules-core/ios/Swift/Views/ComponentData.swift).

public init(viewModule: ViewModuleWrapper, managerClass: ViewModuleWrapper.Type, bridge: RCTBridge) {
    self.moduleHolder = viewModule.wrappedModuleHolder
    super.init(managerClass: managerClass, bridge: bridge, eventDispatcher: bridge.eventDispatcher())
  }

Could you help me how to resolve this issue?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

user@user-Mac-mini app % npx expo-env-info
npx: installed 2 in 4.971s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: ^0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 6.0.1
    Expo Workflow: bare

### Reproducible demo

 The error showing in the following method inside the file (node_modules/expo-modules-core/ios/Swift/Views/ComponentData.swift).

public init(viewModule: ViewModuleWrapper, managerClass: ViewModuleWrapper.Type, bridge: RCTBridge) {
    self.moduleHolder = viewModule.wrappedModuleHolder
    super.init(managerClass: managerClass, bridge: bridge, eventDispatcher: bridge.eventDispatcher())
  }

**Comment by nappa0326** [comment]
I'm having the same issue.

**Comment by y3n3rrr** [comment]
Is there any solution to this?

**Comment by dieg092** [comment]
Same issue here.
Any solution?

**Comment by negulici-r-barnabas** [comment]
Same issue here.

**Comment by hamzafazil90** [comment]
We can fix this issue by downgrading this package to     "expo-modules-core": "~0.6.4",

**Comment by akjesto** [comment]
We can fix this issue by downgrading "expo-modules-core": "~0.6.4",

**Comment by thornec** [comment]
still having this issue after downgrading to "expo-modules-core": "~0.6.4" and "expo-modules-core@0.6.5"

**Comment by whatmansol** [comment]
> still having this issue after downgrading to "expo-modules-core": "~0.6.4" and "expo-modules-core@0.6.5"

yes me too , 
sdk version 44

**Comment by inimist** [comment]
Me too. Expo version 46

**Comment by inimist** [comment]
I even tried expo-modules-core between 0.6.1 && 0.6.5 but none worked :(
