### ISSUE TITLE
Trouble building a new project on an m1 mac

### ISSUE THREAD

**Issue by michaelessiet** [expo/expo#18529]
### Summary

can someone on the expo team explain to me why expo run:ios produces errors after running create-expo-app ? Because it should be the number one thing you guys must have tested: building an app immediately after creating it shouldn't produce any errors at all. Please explain to me what I should do because I've checked online and it seems like I'm not the only one

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      npm: 8.12.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 6.0.1
    Expo Workflow: bare

### Reproducible demo

npx create-expo-app -t expo-typescript-template && cd [project name] && expo run:ios

**Comment by brentvatne** [comment]
can you please provide some information about what error you are seeing?

**Comment by brentvatne** [comment]
to sanity check this i just did a new build on a fresh m2 machine, with xcode and node just installed.

i tried sdk 45 and 46

- sdk 45: `npx create-expo-app` and then `expo run:ios` in the project dir
- sdk 46: `npx create-expo-app --template blank@sdk-46` and then `npx expo run:ios` in the project dir

we'll need more information from you about the error message and so on to help. it's likely a configuration issue. happy to help if we can
