### ISSUE TITLE
Renaming app name resulting in app signing issue

### ISSUE THREAD

**Issue by randomor** [expo/expo#1852]
I've changed my app name in app.json, as well as the `expo.android.package` key, and then am getting this error when uploading the APK to Play Store. 

```
Upload failed

You uploaded an APK that is not signed with the upload certificate. You must use the same certificate. The upload certificate has fingerprint:
[ SHA1: 8D:47:00:BB:E7:C6:31:3E:AF:36:D6:49:41:DD:D2:43:8D:FF:0E:D4 ]
and the certificate used to sign the APK you uploaded have fingerprint:
[ SHA1: 5E:0F:B7:4D:90:0C:B4:A0:FA:B7:55:10:30:91:06:72:14:FC:D2:A8 ]

#another error about my `expo.android.package` not matching the previous one.

You need to use a different version code for your APK or Android App Bundle because you already have one with version code 1.

```

So I reverted my `expo.android.package` change, still see the above error except the `expo.android.package` section. How can I revert to previous upload certificate while keep the new app name? Thanks! Should I just start a brand new application in Play Store?

My environment:
```
23:07:37 [exp] Generating diagnostics report...
23:07:37 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.10.0
  Yarn: 0.16.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.0 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2
```

**Comment by randomor** [comment]
Update: looks like Expo is saving the keystore per the expo.slug key. So I reverted that key, I'll be able to fetch the keystore at a specific path, now the question is will I be able to update the `expo.slug` key and keep the same keystore?

**Comment by SteveAquino** [comment]
@randomor I'm actually having the same issue, I'm curious how you went about solving this, or if you just wound up reverting your config.

**Comment by randomor** [comment]
@SteveAquino yes as mentioned in my comment. Expo.slug is the key to link your repo to your keystore. I’ve ejected from Expo since, so no need to care about Expo slug anymore.
