### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.Text.propTypes.allowFontScaling')

### ISSUE THREAD

**Issue by cankilinc** [expo/expo#18532]
### Summary

I just upgraded my expo version and now getting this error.

```
TypeError: undefined is not an object (evaluating '_reactNative.Text.propTypes.allowFontScaling')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.1.17:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.7.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      expo-cli: 6.0.1
    Expo Workflow: managed

### Reproducible demo

.

**Comment by brentvatne** [comment]
it looks like something in your app is trying to access `Text.propTypes.allowFontScaling` which is undefined

**Comment by cankilinc** [comment]
> it looks like something in your app is trying to access `Text.propTypes.allowFontScaling` which is undefined

How can I fix this problem ? Can you help me please?

**Comment by volodya-leskiv** [comment]
same problem

**Comment by shubhamraiy** [comment]
Same problem
