### ISSUE TITLE
Eas Build failing at Prebuild step for Ios platform

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo#18531]
### Summary

When building application using EAS build with 0.57 version of eas-cli on windows, build is failing on prebuild step.
For android it's seems fine but for Ios is always saying 

![image](https://user-images.githubusercontent.com/26301007/183221455-3f1def3f-b76a-4901-b670-b05b92838fa7.png)

### What platform(s) does this occur on?

iOS

### SDK Version

SDK 43

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^43.0.0 => 43.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

N/A

**Comment by brentvatne** [comment]
this appears to be an intermittent issue caused by npm, possibly in our caching layer. have disabled the npm cache temporarily, can you try your build again?

**Comment by jurica-penjgusic** [comment]
Gladly...

**Comment by jurica-penjgusic** [comment]
Prebuild is now working
