### ISSUE TITLE
Android Calendar Crashes java.lang.NumberFormatException

### ISSUE THREAD

**Issue by johanholm** [expo/expo#1853]
### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.2.0
  Yarn: 0.22.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

I've already created a topic in the forums and got the response to report this as an issue.
https://forums.expo.io/t/android-calendar-crashes-java-lang-numberformatexception/10466

------
### The Issue/Bug

Hello, Ive been using the Calendar API for some time now. But recently I noticed some crashes in my app. I'm not sure if this is suppose to happen but I get promted 2 times about permissons. After that 
 the app crashes.

This is my import `import {Calendar as NativeCalendar, Permissions} from "expo";`

And this is what i use to make sure I have permissions before i try to get the calendars
```
    askForCalendarPermissions = async () => {
        const calendarPermissions = await Permissions.askAsync(Permissions.CALENDAR);

        return calendarPermissions.status === 'granted';
    };
```

The crash occurs when i call:
```
const eventCalendars = await NativeCalendar.getCalendarsAsync(NativeCalendar.EntityTypes.EVENT);
```

I get no bug report from XDE but in Google Play Console I get this error (on multiple devices)
It has occurred on Android 8.0 and Android 7.0
```
java.lang.NumberFormatException: 
  at java.lang.Integer.parseInt (Integer.java:597)
  at java.lang.Integer.parseInt (Integer.java:643)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.calendarAllowedAttendeeTypesFromDBString (CalendarModule.java:1147)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.serializeEventCalendar (CalendarModule.java:1353)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.serializeEventCalendars (CalendarModule.java:1332)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.findCalendars (CalendarModule.java:318)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule.access$000 (CalendarModule.java:41)
  at abi27_0_0.host.exp.exponent.modules.api.CalendarModule$1.run (CalendarModule.java:70)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
```

Here's a snack https://snack.expo.io/S1Vt9RPxQ that produces the error on my phone.

I'm using a One Plus 3T with android 8.0,
Other devices I've seen this issue for is:
Samsung Galaxy Note8 (Android 8.0)
Samsung Galaxy S8 (Android 7.0)
Samsung Galaxy A3 (Android 7.0)

I should add that this issue does not effect all android devices, and I have been able to use the calendar functionality before (On my One Plus 3T). But somehow something has happened since then and now I get the crash.

**Comment by esamelson** [comment]
Hi @johanholm - thanks for the report. We'll try and look into this soon.

**Comment by johanholm** [comment]
Hey @esamelson I've located what caused the bug. I recently installed "Blue Mail & Calendar" - app, and Im no expert but i think that app installs a separate calendar and somehow that becomes an issue when i try to get "getCalendarsAsync".
https://play.google.com/store/apps/details?id=me.bluemail.mail

After I uninstalled that app, the getCalendarsAsync doesn't produce the crash anymore.
How would I got about using bluemail & gmail calendars ?

**Comment by esamelson** [comment]
Hi @johanholm - thanks, that's very helpful information. It looks like that "Blue Mail & Calendar" app is putting some weird values into the device's Calendar DB which Expo is not prepared to handle. We'll try and put out a fix soon which will let you use `getCalendarsAsync` with that app. Sorry for the inconvenience!!

**Comment by johanholm** [comment]
Hey @esamelson!
Whats the status on this issue ?

**Comment by ibraude** [comment]
> It looks like that "Blue Mail & Calendar" app is putting some weird values into the device's Calendar DB which Expo is not prepared to handle

Hey, I ran in to a similar issue on a device that was using a different calendar management app that was also inserting strange values into the device's Calendar DB. 

I've opened a PR with an added condition to make sure the value from the DBString is in fact parsable as an integer. 

Hope this helps.

**Comment by lukmccall** [comment]
Fixed by https://github.com/expo/expo/pull/12724.
