### ISSUE TITLE
[docs] Return value of FileSystem.readAsStringAsync

### ISSUE THREAD

**Issue by SheetJSDev** [expo/expo#18544]
### Summary

The current body text:

> Read the entire contents of a file as a string. Binary will be returned in raw format, you will need to append `data:image/png;base64`, to use it as Base64.

> encoding (EncodingType) -- The encoding format to use when reading the file. Options: FileSystem.EncodingType.UTF8, FileSystem.EncodingType.Base64. Default is FileSystem.EncodingType.UTF8.

1) What is "Binary" in the first part?  Was that supposed to say "Base64" (as in, it returns a raw Base64 string without the data URI preamble) or is the default behavior some hybrid between UTF8 and Base64 encoding?  In the latter case, is there an encoding type for explicitly specifying the behavior?

2) How does the UTF8 encoder handle invalid byte sequences?  Is an error thrown or does it use U+FFFD (the replacement character "�")?

3) Does the base64 string include padding (NodeJS `base64` encoding) or omit it (NodeJS `base64url` encoding)?

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemreadasstringasyncfileuri-options

**Comment by jacksondc** [comment]
Relatedly, can "append" possibly be correct? Does it mean "prepend"?

**Comment by SheetJSDev** [comment]
It definitely should be "prepend".  The media type in a data URI is optional, so `data:;base64,` should suffice
