### ISSUE TITLE
BarCodeScanner zoom argument does not work on Android

### ISSUE THREAD

**Issue by mmcculloch** [expo/expo#1854]
Zoom functionality doesn't seem to work at all on Android, tried both the APIs. Two devices tried so far, Google Pixel and Huawei P8 Lite. It works fine on iOS. Any workaround for this?

_Edit: Can confirm the Camera component is still able to zoom_

**Diagnostics**

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 7.10.1
  Yarn: 1.3.2
  npm: 4.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

**Comment by aalices** [comment]
Hey @mmcculloch sorry, we need to update the docs, `BarCodeScanner` is meant to be based on `Camera` but it is not because of some issues. If you need zoom you just might want to use `Camera` component with `onBarCodeRead` prop
