### ISSUE TITLE
Error: Cannot find module 'webpack-dev-middleware/lib/util'

### ISSUE THREAD

**Issue by matthewtoast** [expo/expo#18550]
### Summary

Since upgrading to Expo 46, starting the project, and then choosing `open web` (by pressing "w" key) results in the dev server instantly crashing; the app never opens. It shows the following message:

```
Error: Cannot find module 'webpack-dev-middleware/lib/util'
Require stack:
- my-proj/node_modules/@expo/dev-server/build/webpack/getFileAsync.js
- my-proj/node_modules/@expo/dev-server/build/webpack/symbolicateMiddleware.js
- my-proj/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js
- my-proj/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- my-proj/node_modules/@expo/cli/build/src/start/startAsync.js
- my-proj/node_modules/@expo/cli/build/src/start/index.js
- my-proj/node_modules/@expo/cli/build/bin/cli
```

### What platform(s) does this occur on?

Web

### SDK Version

46

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.0 
      expo: ^46.0.0 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: managed
```

### Reproducible demo

I noticed a suspicious line in a recent commit here: https://github.com/expo/expo/commit/aef260d60941bbb6325a3ebf0d68f6ca0077341d#diff-62d3a8c3905e998b6e89d48b8abe13b59db81d39252a679d64cb350a0cb57be4R4

It looks like probably an actual error was being reported on that line and got ignored.

There is no `lib/utils` folder in the `webpack-dev-middleware` package that I can see:
https://github.com/webpack/webpack-dev-middleware

**Comment by brentvatne** [comment]
thanks for the report! we do need a reproducible demo to help here because i am not able to reproduce this on any of my projects.

**Comment by phryneas** [comment]
This happened to me in a monorepo where another monorepo-package had webpack 5 installed. Downgrading that to webpack 4, it started working. So likely a bundler and/or path resolution issue.

**Comment by alielhusseini** [comment]
@phryneas I added the "webpack": "4.43.0" to the package.json yet I am still having this issue: 

Error: Cannot find module '@expo/dev-server/build/webpack/symbolicateMiddleware'

With SDK - 45, the web works normally (When upgrading to SDK - 46, I have added "@expo/webpack-config": "^0.17.0" as per expo)

**Comment by phryneas** [comment]
@alielhusseini  You might still end up with both versions being installed at the same time - if you are using `yarn`, the `resolutions` field of `package.json` might be able to help you with that.
