### ISSUE TITLE
expo init fails to yield usable project if using EXPO_USE_EXOTIC=1

### ISSUE THREAD

**Issue by Nantris** [expo/expo#18555]
### Summary

![image](https://user-images.githubusercontent.com/6835891/183310818-d0f9d316-e227-4821-9efe-20056ec4fc16.png)

### What platform(s) does this occur on?

Android

### SDK Version

46

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 8.9.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play Intel x86 Atom_64
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
```

### Reproducible demo

1. export EXPO_USE_EXOTIC=1
2. expo init
3. cd my-app
4. yarn android

**Comment by brentvatne** [comment]
can confirm that this isn't currently working with sdk 46. that said, "exotic" continues to be experimental and so you may encounter issues like this occasionally

**Comment by Slapbox** [comment]
The trouble with exotic is, it's so been dependable that it's easy to forget it's experimental!

But actually, I realized that the project that `expo init` yielded for me was only running SDK 45 - so there may be an additional issue, maybe with the local cli? Although I did try disabling that via environmental variable while leaving exotic enabled, and it didn't fix the issue.

**Comment by Slapbox** [comment]
Still an issue in SDK 47, but message now is:

`error: SyntaxError in node_modules/react-native/Libraries/Events/EventPolyfill.js: Unexpected token, expected "{" (162:34)`

**Comment by ladyshaitan** [comment]
> Still an issue in SDK 47, but message now is:
> 
> `error: SyntaxError in node_modules/react-native/Libraries/Events/EventPolyfill.js: Unexpected token, expected "{" (162:34)`

I'm on SDK 48 and am also experiencing this issue.  Any updates on that?

**Comment by brentvatne** [comment]
@ladyshaitan - `EXPO_USE_EXOTIC` is experimental and i'd recommend turning it off for now

**Comment by EvanBacon** [comment]
Exotic is now deprecated in SDK 50 as most the value has been pulled in to our default expo/metro-config.
