### ISSUE TITLE
[SDK46] Classic build error: our app builders do not support SDK version 46

### ISSUE THREAD

**Issue by Ray-Frost** [expo/expo#18572]
### Summary

I upgraded the Expo SDK from v44 to v46. When I ran `expo build:ios`, I encountered an error "Unsupported SDK version: our app builders do not support SDK version 46, yet. The latest SDK version is 46.0.0."
Based on the [upgrade guide](https://blog.expo.dev/expo-sdk-46-c2a1655f63f7), SDK 46 should be the last SDK version supported by Classic Builds.

### What platform(s) does this occur on?

iOS

### SDK Version

46

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
      Watchman: 2022.06.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.65 => 0.1.65
      expo: ^46.0.0 => 46.0.2
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.3 => 0.69.3
    Expo Workflow: managed
```

### Reproducible demo

Main information of package.json
```
"expo-cli": "^6.0.1",
"expo": "^46.0.0",
"expo-analytics": "^1.0.18",
"expo-auth-session": "~3.7.1",
"expo-constants": "~13.2.3",
"expo-device": "~4.3.0",
"expo-linking": "~3.2.2",
"expo-local-authentication": "~12.3.0",
"expo-notifications": "~0.16.1",
"expo-random": "~12.3.0",
"expo-secure-store": "~11.3.0",
"expo-splash-screen": "~0.16.1",
"expo-updates": "~0.14.3",
```
Run command `expo build:ios`

**Comment by SrZorro** [comment]
Related https://github.com/expo/turtle/issues/410

**Comment by lucca65** [comment]
this also happens to me, even when bootstrapping from scratch with `npx create-expo-app testflight -t bare-minimum`

**Comment by brentvatne** [comment]
this is planned, we will release support for classic builds for sdk 46 in the next week or so. this will be the final sdk version to support classic builds! we recommend that you migrate.

from the release notes:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/90494/184463121-fbbbaa5c-d87b-4402-a36a-7aeb863172cc.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/90494/184463124-3e5424b3-c3ef-4673-b54d-ec9d7b8917c8.png">

https://blog.expo.dev/expo-sdk-46-c2a1655f63f7

**Comment by lucca65** [comment]
I cannot use EAS Build, as I'm using React-Native-Firebase and it requires me to manually change my Podfile to include `  config = use_frameworks!`. It seems that on managed apps I can use `expo-build-proprieties` but again, due to firebase I need a bare workflow. When I try to build on EAS it fails because of that clause. 

The solution is to wait two weeks? Maybe go back to 45 where it was working? any advice?

**Comment by DeveloperMedi** [comment]
> ### Summary
> 
> I upgraded the Expo SDK from v44 to v46. When I ran `expo build:ios`, I encountered an error "Unsupported SDK version: our app builders do not support SDK version 46, yet. The latest SDK version is 46.0.0."
> Based on the [upgrade guide](https://blog.expo.dev/expo-sdk-46-c2a1655f63f7), SDK 46 should be the last SDK version supported by Classic Builds.
> 
> ### What platform(s) does this occur on?
> 
> iOS
> 
> ### SDK Version
> 
> 46
> 
> ### Environment
> 
> ```
>   expo-env-info 1.0.5 environment info:
>     System:
>       OS: macOS 10.15.5
>       Shell: 5.7.1 - /bin/zsh
>     Binaries:
>       Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
>       Yarn: 1.22.19 - /usr/local/bin/yarn
>       npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
>       Watchman: 2022.06.13.00 - /usr/local/bin/watchman
>     Managers:
>       CocoaPods: 1.11.3 - /usr/local/bin/pod
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
>     IDEs:
>       Xcode: 12.4/12D4e - /usr/bin/xcodebuild
>     npmPackages:
>       @expo/metro-config: ^0.1.65 => 0.1.65
>       expo: ^46.0.0 => 46.0.2
>       react: 18.0.0 => 18.0.0
>       react-dom: 18.0.0 => 18.0.0
>       react-native: 0.69.3 => 0.69.3
>     Expo Workflow: managed
> ```
> 
> ### Reproducible demo
> 
> Main information of package.json
> ```
> "expo-cli": "^6.0.1",
> "expo": "^46.0.0",
> "expo-analytics": "^1.0.18",
> "expo-auth-session": "~3.7.1",
> "expo-constants": "~13.2.3",
> "expo-device": "~4.3.0",
> "expo-linking": "~3.2.2",
> "expo-local-authentication": "~12.3.0",
> "expo-notifications": "~0.16.1",
> "expo-random": "~12.3.0",
> "expo-secure-store": "~11.3.0",
> "expo-splash-screen": "~0.16.1",
> "expo-updates": "~0.14.3",
> ```
> Run command `expo build:ios`

Bro can you share your telegram I'd or contact details please
