### ISSUE TITLE
keytool -list -printcert -jarfile fails on windows (trying to create SHA-1 certificate fingerprint)

### ISSUE THREAD

**Issue by rahamin1** [expo/expo#1857]
(also posted in the [expo forum](https://forums.expo.io/t/what-is-growler-apk-in-the-keytool-command-using-mapview/10524))

https://github.com/expo/expo/issues/1410 discusses a problem running the same command, but it didn't help me solve my problem.

I am following the instructions in [https://docs.expo.io/versions/latest/sdk/map-view](https://docs.expo.io/versions/latest/sdk/map-view) to build an android standalone app.

step 9 says: `“Run keytool -list -printcert -jarfile growler.apk | grep SHA1 | awk ‘{ print $2 }’ where growler.apk is the path to the apk you built in step 1.”`

My full apk path is:
`https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40rahamin%2FIsrael-Weather-8866e66b-6d8a-11e8-b1f8-0a580a780406-signed.apk`

I thought that growler.apk is `android%2F%40rahamin%2FIsrael-Weather-8866e66b-6d8a-11e8-b1f8-0a580a780406-signed.apk`, but when I type (in windows):

`keytool -list -printcert -jarfile android%2F%40rahamin%2FIsrael-Weather-8866e66b-6d8a-11e8-b1f8-0a580a780406-signed.apk | grep SHA1 | gawk “{ print $2 }”`

I get nothing…

If I run:
`keytool -list -printcert -jarfile android%2F%40rahamin%2FIsrael-Weather-8866e66b-6d8a-11e8-b1f8-0a580a780406-signed.apk`
I get: 
`keytool error: java.io.FileNotFoundException: android%2F%40rahamin%2FIsrael-Weather-8866e66b-6d8a-11e8-b1f8-0a580a780406-signed.apk (The system cannot find the file specified)`

Any suggestion?

**Comment by ericnag** [comment]
@rahamin1 could you please tell me where(which path) do you run the command?

**Comment by rahamin1** [comment]
It doesn't matter.

- You need to have the utilities (keytool, grep, gawk) in your PATH.
- you need to have the apk in the current folder.
