### ISSUE TITLE
Expo : Android Build error

### ISSUE THREAD

**Issue by safilsunny** [expo/expo#1858]
when i tried to run react-native run-android, i am getting following error. 
`
Starting: Intent { cmp=host.exp.exponent/.MainActivity }
Error type 3
Error: Activity class {host.exp.exponent/host.exp.exponent.MainActivity} does not exist.
`

**Comment by ccheever** [comment]
Hi-

What are you trying to do? `react-native run-android` isn't the way to run an Expo project on Android. Did you do `exp start`?

**Comment by safilsunny** [comment]
i already detached the app and now i am trying to run it using react-native run-android

**Comment by esamelson** [comment]
Hi @safilsunny - as @ccheever said `react-native run-android` won't work with an Expo project. The correct way to start the project is to run `exp start` and then open the project in Android Studio and run it (or, if you prefer, run `cd android/ && ./gradlew installDevDebug` in another terminal window.

**Comment by safilsunny** [comment]
thank you :)

**Comment by FaizalMalik** [comment]
@esamelson  -  I have used the same command[ 
exp start.  
cd android/ && ./gradlew installDevDebug ]---

It shows the build successfully and Installed on 1 device. - but the app is not automatically launching or when I click the app icon it suddenly gets close.


Expo xde - Version 2.24.4 (2.24.4.53441)
Android Studio - 3.1.2
Exp - Version 55.0.4
***********Output**********


Installed on 1 device.

BUILD SUCCESSFUL

Total time: 1 mins 1.201 secs

**Comment by esamelson** [comment]
Hi @FaizalMalik - it sounds like the app is crashing on launch. Have you tried looking at your device logs (using `adb logcat`) when you try to open the app? It would be super helpful if you could open a new issue with more information, including relevant logs from the crash. Thanks!!

**Comment by daxaxelrod** [comment]
Hi! @esamelson I was able to get it on the device but i keep getting a the expo error screen saying that cleartext comms are not allowed to 192.168.56.1 even though ive explicitly created a rule in my windows defender to allow all traffic through on my network. Any tips?

2019-02-26 18:46:47.840 10108-10137/com.gymhop.client D/Exponent: Loaded exp.host status page.
2019-02-26 18:46:48.416 10108-10128/com.gymhop.client V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 647

**Comment by esamelson** [comment]
@daxaxelrod - could you open a new ticket and fill out the template fully there? This issue is pretty outdated, and it's a lot easier for us to help you out if we have more specific information about your setup and the exact error you're seeing. Thanks 🙂
