### ISSUE TITLE
Expo splashscreen remains visible forever on Android (SDK28 client app)

### ISSUE THREAD

**Issue by slorber** [expo/expo#1859]
This issue appeared this night and it affects two of my Expo apps + a newly created CRNA app

It also seems to affect at least 2 people (see [Slack](https://expo-developers.slack.com/archives/C04Q3JTSV/p1528793354000380)), so it is probably an Expo host app regression.

It is quite annoying because it makes me unable to develop using my normal development workflow (using Android hardware device), but as a workaround an iOS simulator is usable.

### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.7.0
  Yarn: 1.6.0
  npm: 5.4.2
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/shoootin-60718136-d383-49dc-9151-ea1c0f5fb893.tar.gz

### Steps to Reproduce

```
create-react-native-app expo-bug-test
cd expo-bug-test
yarn run android
```

I'm running apps on device, Samsung A5 2016

### Expected Behavior

Android splash screen should disappear after app is ready and all `<AppLoading/>` are unmounted
Android CRNA generated app should work

### Actual Behavior

Android splash screen remains visible permanently, even on the CRNA hello world app.
Logs can show that the home screen is actually rendered, probably under the splashscreen.
It seems to work fine on iOS.

### Reproducible Demo

Can't reproduce on Snack, but can reproduce on CRNA with steps above easily.

**Comment by pauliusuza** [comment]
Seeing this as well in my app since this morning together with black and white icon change.
I can access the app if I disable the remote debugging. After the app is visible I can re-enable it again.

**Comment by slorber** [comment]
Can confirm it seems to work when starting with remote debugging disabled. If anyone has a better workaround please share it.

**Comment by slorber** [comment]
I created a Canny request for expo app publications as beta, so that we can rollback more easily to former app version in case new version has problems like this and makes such bugs less impactful

https://expo.canny.io/feature-requests/p/publish-expo-client-updates-as-beta

**Comment by brentvatne** [comment]
I can't repro this. please share a project where this happens

**Comment by esamelson** [comment]
Expo client 2.6.2 just went out to the play store with a fix for this issue. You may need to wait a little bit before it shows up, but it should be available soon.

**Comment by slorber** [comment]
Thanks @esamelson it's working
