### ISSUE TITLE
expo-video-thumbnails: "This media cannot be used"

### ISSUE THREAD

**Issue by jacksondc** [expo/expo#18598]
### Summary

On iOS, expo-video-thumbnails reports "This media cannot be used" for some videos (e.g., http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4). No problems on Android.

On my local machine, the stack trace is

```
This media cannot be used.
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:106:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-video-thumbnails/build/VideoThumbnails.js:12:17 in getThumbnailAsync
at node_modules/expo-video-thumbnails/build/VideoThumbnails.js:11:7 in getThumbnailAsync
[...]
```

On Snack I get `Error: "This media cannot be used." in [snack internals] <<  <<  << p`

Is this a known issue?

### What platform(s) does this occur on?

iOS

### SDK Version

46.0.0

### Environment

Not sure how to run `npx expo-env-info` on snack

### Reproducible demo

https://snack.expo.dev/SSxd7QWRH

**Comment by jacksondc** [comment]
Apologies for the CLI tag—seemed like none of the issue templates fit my use case. Am I in the wrong place?

**Comment by Niltonsf** [comment]
I'm getting the same issue!

**Comment by mcanikhilprajapati** [comment]
same issue on "expo-video-thumbnails": "~6.3.0",

**Comment by pr1ze** [comment]
Same issue on "expo-video-thumbnails": "~6.4.0", injecting a uri for a .mov

**Comment by shrihari1999** [comment]
I still have this issue. Any updates/workarounds on this? Wonder why this is not marked as a bug

**Comment by shrihari1999** [comment]
I had the same issue, until i checked the "time" parameter. I was passing a "time" that was beyond the duration of the video. In @jacksondc 's snack, the video's duration is 15 secs, and the "time" parameter is also 15000, thus raising an error.

Passing any time falls within the video's duration solves the error for me

**Comment by brentvatne** [comment]
good catch @shrihari1999!

if anyone wants to open a pr to throw a better error in this case it would be welcomed, but i'll close this issue
