### ISSUE TITLE
Investigate compatibility with another instance of babel-plugin-module-resolver with babel-preset-expo

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#186]
Related issue: https://github.com/tleunen/babel-plugin-module-resolver/issues/167

**Comment by dikaiosune** [comment]
Looks like the babel-plugin-module-resolver folks have prevented double-application in future versions: https://github.com/tleunen/babel-plugin-module-resolver/pull/176. Do we need to update @brentvatne?

**Comment by ide** [comment]
This might break things for people. We intentionally want to support two passes (one for Expo and one for userspace), one of the tests in babel preset expo checks for this.

**Comment by dikaiosune** [comment]
@ide afaik the issue was that two separate passes broke things horribly. I think if your goal is an expo pass and a "userspace" pass that's what supported in the recent releases.

**Comment by ide** [comment]
Oh okay, I didn't look at the PR at first. Looking more closely it looks like it supports multiple module-resolver plugins for the same source files, but each import/require can be rewritten just once.
