### ISSUE TITLE
Stuck on splash screen Ios with app in app store (not every Iphone)

### ISSUE THREAD

**Issue by stefdelec** [expo/expo#1860]
The app is stuck on Splash Screen only on some device. It works well on simulator and Android. But when on Iphone (Ios10.4 I think), it stays stuck on splash screen.
Here is the link to my app :

https://itunes.apple.com/us/app/lettrio/id1387831491?mt=8&ign-mpt=uo%3D4

`{
  "name": "rezfezfio",
  "version": "0.1.0",
  "private": true,
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "build": "./node_modules/.bin/tsc",
    "build:watch": "./node_modules/.bin/tsc -w",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/babel-jest",
      "\\.(ts|tsx)$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "testPathIgnorePatterns": [
      "\\.snap$",
      "<rootDir>/node_modules/",
      "<rootDir>/lib/"
    ],
    "cacheDirectory": ".jest/cache"
  },
  "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "expo": "27.0.0",
    "lodash": "^4.17.5",
    "rand-let-gen": "https://github.com/somelib/rand-let-gen.git#1.0.3",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
    "react-native-linear-gradient": "^2.4.0",
    "react-navigation": "^1.0.3",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-thunk": "2.2.0",
    "reselect": "3.0.1",
    "rxjs": "5.5.6",
    "tinycolor2": "^1.4.1"
  },
  "devDependencies": {
    "@types/jest": "22.0.1",
    "@types/lodash": "^4.14.104",
    "@types/node": "9.4.0",
    "@types/react": "^16.0.34",
    "@types/react-native": "^0.52.1",
    "@types/react-navigation": "^1.0.32",
    "@types/react-test-renderer": "16.0.0",
    "jest-cli": "^22.4.2",
    "jest-expo": "23.0.0",
    "react-native-scripts": "1.9.0",
    "react-test-renderer": "16.0.0",
    "ts-jest": "^22.0.1",
    "typescript": "2.6.1"
  }
}
`
and my app.json 

`{
  "expo": {
    "name": "zefezfzef",
    "description": "zefzef",
    "slug": "mysluf",
    "privacy": "unlisted",
    "primaryColor": "#000000",
    "sdkVersion": "27.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "buildNumber": "1.0.2",
      "bundleIdentifier": "zeflkznefzkefn",
      "supportsTablet": true
    },
    "android": {
      "package": "zefoezfpzekf,ezf",
      "permissions": []
    }
  }
}
`

**Comment by msevestre** [comment]
when did you create your app?
This behavior sounds a lot like #1829

**Comment by stefdelec** [comment]
If by "create" you mean "exp build:ios" => 2 days ago.
If it means create the project few month ago (4 months)

**Comment by terribleben** [comment]
Based on your `app.json`, I think highly likely this is the same as #1829. Fix should be going out today for that.

**Comment by stefdelec** [comment]
Thanks. I closed the issue.

**Comment by stefdelec** [comment]
If I change the timeout to 1 should it work?

**Comment by msevestre** [comment]
I meant build the app. And no the fix with setting the value to 1 does not work
