### ISSUE TITLE
react-native-maps is outdated with npx expo install 

### ISSUE THREAD

**Issue by da45** [expo/expo#18619]
### Summary

installed version with npx expo install is 0.31.1 , this version is outdated can't use with other libraries like react-native-maps-directions

### What platform(s) does this occur on?

Android

### Environment

expo sdk 46 react-native-maps
![Untitled](https://user-images.githubusercontent.com/19927289/184305701-46f328c4-31c4-49e1-85f7-93955c618dcb.jpg)

### Minimal reproducible example

npx expo install react-native-maps
npm install  react-native-maps-directions

**Comment by Simek** [comment]
Hello @da45, maps library probably won't be updated until next SDK release. 

Can you try to install and pin to the previous release of the problematic package by running `npm install react-native-maps-directions@1.8.0`? 

If this solve the issue, it probably means that adding compatibility for the new release of maps library broke the support of older versions, and might be an expected behavior or a bug in the `react-native-maps-directions`:
* https://github.com/bramus/react-native-maps-directions/blob/master/CHANGELOG.md

**Comment by brentvatne** [comment]
we update react-native-maps and other modules in expo sdk on each release. you can update earlier if you like, the versions we include are just those supported in expo go and those that we test against for each release. if you use eas build / development builds, you can use any version that you find works for you.

**Comment by HOSENUR** [comment]
@da45 Could you fix it? My maps font even render when using Expo SDK 46, its just blank

**Comment by derekparker** [comment]
Would be really great to update this, as @HOSENUR mentioned I can't even get a basic map to render with Expo SDK 46, I also get just a blank render. I created an issue https://github.com/react-native-maps/react-native-maps/issues/4441 but I'm starting to think it's actually because there is such an old version being used. The current version is v1.3.1 and Expo SDK 46 is still stuch on a pre-1.0 version.

Updating just the react-native-maps component itself causes issues and will not build.

**Comment by derekparker** [comment]
Short of updating it for the latest release SDK, could you provide a way to upgrade it manually? Upgrading manually right now gives the following error when trying to build:

```
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     react-native-google-maps (from `/private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/9fa2c50a-e344-4ae6-b662-e33eb8625f27/build/node_modules/react-native-maps`)
[INSTALL_PODS] 
[INSTALL_PODS] Specs satisfying the `react-native-google-maps (from `/private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/9fa2c50a-e344-4ae6-b662-e33eb8625f27/build/node_modules/react-native-maps`)` dependency were found, but they required a higher minimum deployment target.
```

Is it possible to update this dependency while still using expo managed mode?

**Comment by joningenordnes** [comment]
Upgrading to SDK 46 removes the support for the longtime depricated ViewPropTypes which the expo´s old version of react-native-maps needs. Current live production SDK config is broken out of the box.

**Comment by derekparker** [comment]
> Upgrading to SDK 46 removes the support for the longtime depricated ViewPropTypes which the expo´s old version of react-native-maps needs. Current live production SDK config is broken out of the box.

@brentvatne any response to the above? It seems the SDK 46 version is broken by default when it comes to using maps.

**Comment by brentvatne** [comment]
@derekparker - if you are using eas build, you can install whichever version of react-native-maps that you like. expo tooling will warn you that you are not using the recommended version but if that is a conscious decision you don't need to worry about it. we use the version that was available at the time that we released sdk 46. i am not sure what you mean about it being broken out of the box. i just created a new app and ran `npx expo run:ios` and it worked as expected. I then created a release build with `npx expo run:ios --configuration Release` and it worked as expected.

https://github.com/brentvatne/derekparker

please create a new issue and included a minimum reproducible example and fill out the full issue template if you're still having issues

> Upgrading to SDK 46 removes the support for the longtime depricated ViewPropTypes which the expo´s old version of react-native-maps needs. Current live production SDK config is broken out of the box.

i don't believe this is the case - see: https://github.com/react-native-maps/react-native-maps/releases/tag/v0.31.0 - notice the item:

> migrate to deprecated-react-native-prop-types ([5bc1cc6](https://github.com/react-native-maps/react-native-maps/commit/5bc1cc67ab1a110e53bde238ccbb40d7dfef547f))

**Comment by derekparker** [comment]
@brentvatne thanks for the reply! I really appreciate your help in getting this all working.

When I run your example using the provided command `npx expo run:ios` I get the following error in the simulator:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module ./index from /private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/.: <br><br>None of these files exist:<br> &nbsp;* index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)<br> &nbsp;* index/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (/private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (/private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)<br> &nbsp; &nbsp;at /private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/node_modules/metro/src/lib/transformHelpers.js:129:24<br> &nbsp; &nbsp;at Server._resolveRelativePath (/private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/node_modules/metro/src/Server.js:1137:12)<br> &nbsp; &nbsp;at async Server.requestProcessor [as _processBundleRequest] (/private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/node_modules/metro/src/Server.js:464:37)<br> &nbsp; &nbsp;at async Server._processRequest (/private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/node_modules/metro/src/Server.js:420:9)</pre>
</body>
</html>


RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

**Comment by brentvatne** [comment]
it looks like maybe you have a bundler instance running in another directory? `Error: Unable to resolve module ./index from /private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/` is unrelated to `npx expo run:ios`

**Comment by derekparker** [comment]
> it looks like maybe you have a bundler instance running in another directory? `Error: Unable to resolve module ./index from /private/var/folders/pz/c8j7_1zj26g3prvxzsxqddqw0000gn/T/eas-build-local-nodejs/907a6701-5529-468e-90f8-f85faa9d1d8b/build/` is unrelated to `npx expo run:ios`

You're totally right, and additionally I was able to get your example and a fresh example I created to work. I'll keep poking around as to why things aren't working on my real project but I really appreciate your help with all this. Sorry for the additional noise!
