### ISSUE TITLE
eas build ios doesn't work 

### ISSUE THREAD

**Issue by Misael04** [expo/expo#18616]
### Summary

I'm trying to generate an internal distribution app, but I'm getting an error when trying to save the provisioning profile.

Error 504
Ray ID: 739487061a6a01df • 2022-08-11 22:50:02 UTC
Gateway time-out

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/alejandro.pavon/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: >=43.0.0-0 <44.0.0 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo

just try to add a provisioning profile for Ad-Hoc

**Comment by brentvatne** [comment]
try running this again - it looks like there was an intermittent issue on the service. if the issue persists let us know

**Comment by Misael04** [comment]
@brentvatne  Same problem, from Desktop app too :

![image](https://user-images.githubusercontent.com/22619977/184306566-da32b473-f9de-463f-9093-e98a3d26bdde.png)
