### ISSUE TITLE
[docs] [expo-image-picker] On iOS option "allowsMultipleSelection" seems not supported

### ISSUE THREAD

**Issue by MarcoFilosi** [expo/expo#18611]
### Summary

The documentation in ImagePickerOptions https://docs.expo.dev/versions/v46.0.0/sdk/imagepicker/#imagepickeroptions says that option "allowsMultipleSelection" is supported on iOS 14+ but it is not. I've tested it on iOS 15.5 devices and it doesn't do anything. It allows to pick just one picture.

Please fix the documentation or make a new release of expo-image-picker. 

I didn't test it on Android devices but please fix the documentation if it doesn't work on Android too.

### Link to the related docs page

https://docs.expo.dev/versions/v46.0.0/sdk/imagepicker/#imagepickeroptions

**Comment by brentvatne** [comment]
https://snack.expo.dev/@brents/image-picker

works as expected here

**Comment by MarcoFilosi** [comment]
Yes, it works. I was using SDK 45. Thanks a lot

**Comment by betomoedano** [comment]
Hey guys

After pressing the add button I get this error

Im using expo 46, Do you have any idea what is causing this problem?

![Screen Shot 2022-08-12 at 4 44 53 PM](https://user-images.githubusercontent.com/43630417/184442370-f3506449-0cdb-48a4-9796-558f676d63ee.png)

full message: 
```
Invariant Violation: No callback found with cbID 197 and callID 98 for  NativeUnimoduleProxy.callMethod - most likely the callback was already invoked. Args: '[{"code":"ERR_INVALID_MEDIA_TYPE","message":"Cannot handle 'public.jpeg' media type","domain":"ABI46_0_0ExpoImagePicker.InvalidMediaTypeException","userInfo":{},"nativeStackIOS"
```

**Comment by betomoedano** [comment]
I just realized it works well on a physical device. 😅
