### ISSUE TITLE
sdk 28 release blog broken links

### ISSUE THREAD

**Issue by riwu** [expo/expo#1861]
https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530

Various links refer to https://github.com/expo/universe which doesn't exist (private repo?).

Eg.
> Modal: Fixed all reported bugs reported when using the React Native built-in Modal component on iOS. ([Related issue.](https://github.com/expo/universe/issues/2326))

> Video: Fixed delay with play/pause on iOS. ([Related issue.](https://github.com/expo/universe/pull/2526))

**Comment by brentvatne** [comment]
fixed
