### ISSUE TITLE
.loadAsync does not throw error or timeout when given invalid URL

### ISSUE THREAD

**Issue by mdhenriksen** [expo/expo#18627]
### Summary

Giving the `.loadAsync()` on the `new Audio.Sound()`-object an invalid URL without a sound file (e.g. `https://fakeurl.com/invalid_path.mp3`) will result in the promise to never resolve and won't throw any errors.

### What platform(s) does this occur on?

iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.6 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      expo-cli: 6.0.2
    Expo Workflow: bare
```

### Minimal reproducible example

```javascript
const audioFile = new Audio.Sound()

await audioFile
  .loadAsync({
    uri: "https://fakeurl.com/invalid_path.mp3",
    })
    .then(setAudio(audioFile)) // Never reaches this and does not throw an error
```

**Comment by BrodaNoel** [comment]
@mdhenriksen what library are you talking about? `expo-av`?

**Comment by mdhenriksen** [comment]
> @mdhenriksen what library are you talking about? `expo-av`?

Oh, my bad. Yes it's `expo-av`.

**Comment by mdhenriksen** [comment]
> Hello @mdhenriksen, if you use chained calls you need to add `.catch` at the end of the audio load chain, otherwise you can wrap the whole section with `try-catch` to see the error.
> 
> See: https://snack.expo.dev/@simek/recording-sounds

I've tried that - Also just tried your snippet and I'm not getting an `alert` from the `.catch()`?

**Comment by Simek** [comment]
Hmm, the code from linked Snack works on my device as expected, so you will need to provide us a bit more details about your setup, test device, etc., so we can reproduce the problem on our end.

https://user-images.githubusercontent.com/719641/184963661-8d6d1f58-e72a-43f3-8a7b-16ffd5cd52a7.MOV
