### ISSUE TITLE
Detached iOS (ExpoKit) build fails with FBNativeAd error - Error with new version FBAudienceNetwork Pod 

### ISSUE THREAD

**Issue by Daadler6** [expo/expo#1862]
Detached iOS build fails with FBNativeAd error:

Steps to reproduce:
1. In a detached Expo build as of June 12, 2018
2. Clear ios/Pods folder and run a pod install or simply just run a pod install
3. Attempt to build in IOS.
4. Observe the following errors:

```
Showing Recent Messages
/ios/Pods/ExpoKit/ios/Exponent/Versioned/Core/Api/FBAds/EXNativeAdView.m:17:25: Property 'title' not found on object of type 'FBNativeAd *'

/ios/Pods/ExpoKit/ios/Exponent/Versioned/Core/Api/FBAds/EXNativeAdView.m:26:14: No visible @interface for 'FBNativeAd' declares the selector 'registerViewForInteraction:withViewController:'
```

I've logged my findings on the issue in the following form post:
 https://forums.expo.io/t/detached-ios-build-fails-with-fbnativead-error/10572

@brentvatne @terribleben - Please feel free to comment on here or reach out to me directly on the Expo slack channel tomorrow if you need more info. I can update this issue with more info if need be.

**Comment by RostislavCn** [comment]
+1

**Comment by jowe13** [comment]
+1

**Comment by Daadler6** [comment]
@RostislavCn - Have you tested changing the files locally and building using a build pipeline process like a Jenkins or Bamboo?

**Comment by RostislavCn** [comment]
@Daadler6 haven't really might try it in a bit (obv. that's not a great solution), luckily one of devops guys had an old Podlock.file (as a temporary solution) for CircleCi pipeline.

**Comment by terribleben** [comment]
Hey there, I've put up a new version which should at least unblock this issue. Check the [other thread](https://github.com/expo/expo/issues/1868).

I'm going to close this (as I believe the build failure is resolved), but I'll leave the other issue open so that we can track a longer term solution.

**Comment by jowe13** [comment]
everything works fine for me now when using 2.6.5 as expokit tag. Thanks a lot
