### ISSUE TITLE
Various bugs with NavigationBar

### ISSUE THREAD

**Issue by sweebee** [expo/expo#18625]
### Summary

What i expect:

Hide navigation bar by default unless i swipe up.

Whats happening:

Android 9: works when started the app. once I go to another app and back to the main app and it stops working, navigation bar is always visible.

Android 11: on startup the navigation bar is hidden, but when i touch anywhere it becomes visible and stays visible.

Android 5.1: My device doesnt have touch buttons so they are never there, but the statusbar text is always white (on a white background)

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ^46.0.0 => 46.0.6 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.2
    Expo Workflow: managed
```

### Minimal reproducible example

All i did was adding this to the app.json:

```json
"androidStatusBar": {
      "hidden": false,
      "barStyle": "dark-content"
    },
    "androidNavigationBar": {
      "visible": "sticky-immersive"
    },
```

**Comment by brentvatne** [comment]
the properties in app.json set *the initial values* but do not update as they are changed by the system. you can control the navigation bar at runtime using expo-navigation-bar and the hooks that it exposes: https://docs.expo.dev/versions/latest/sdk/navigation-bar/
