### ISSUE TITLE
addNotificationReceivedListener not called on iOS

### ISSUE THREAD

**Issue by ball-hayden** [expo/expo#18623]
### Summary

When an app is running in the foreground, the `addNotificationReceivedListener` is not called on iOS.

This happens because the `fetchCompletionHandler` is called, which is a noop in `EXNotificationsEmitter`.

The `willPresentNotification` callback is never called.

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - ~/development/PlayerData/app/mobile/node_modules/.bin/yarn
      npm: 8.14.0 - ~/development/PlayerData/app/node_modules/.bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.6 => 46.0.6
      react: ^18.0.0 => 18.0.0
      react-dom: ^18.0.0 => 18.0.0
      react-native: 0.68.1 => 0.68.1
    Expo Workflow: bare
```

### Minimal reproducible example

Given the following:

```js
// index.js
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    // The alert won't show on Android without asking to play the sound...
    shouldPlaySound: true,
    shouldSetBadge: false,
  }),
});

// later...
    const permission = (await Notifications.getPermissionsAsync()).granted;
    if (!permission) return;

    const token = await Notifications.getDevicePushTokenAsync();
    console.log(token.data);

    Notifications.addNotificationReceivedListener((notification) => {
      console.log(notification)
    });
```

1) Install pods with `EXPO_USE_SOURCE=1`, and run app

2) Trigger an APNs notification (see https://developer.apple.com/documentation/usernotifications/sending_push_notifications_using_command-line_tools)

```sh
 curl -v --header "apns-topic: ${TOPIC}" --header "apns-push-type: alert" --cert "${CERTIFICATE_FILE_NAME}" --cert-type DER --key "${CERTIFICATE_KEY_FILE_NAME}" --key-type PEM --data '{
  "aps": { "alert": { "title": "test", "body": "Testing" } },
  "foo": "bar"
}
```

Expected behaviour:

`onDidReceiveNotification` is called.

Actual behaviour:

`onDidReceiveNotification` is not called.

I noticed that `EXNotificationsEmitter didReceiveRemoteNotification fetchCompletionHandler completionHandler` is called (which is a no-op).
   `EXNotificationsEmitter didReceiveRemoteNotification willPresentNotification completionHandler` is never called, therefore `onDidReceiveNotification` is never called, therefore my JS callback is never called.

**Comment by majirosstefan** [comment]
Same here!

**Comment by ball-hayden** [comment]
Still not implemented.
