### ISSUE TITLE
Clipped labels in Tab Navigation in Expo Home

### ISSUE THREAD

**Issue by jaulz** [expo/expo#1863]
### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Environment

iOS Expo Client with version 2.6.3

### Steps to Reproduce

Open Expo client app. No need to open a specific project.

### Expected Behavior

Text in menu is completely visible.

### Actual Behavior

Text in menu is clipped.
![image](https://user-images.githubusercontent.com/5358638/41331307-b7e62a2e-6ed8-11e8-89fe-620d710e17d5.png)

### Reproducible Demo

n/a

**Comment by terribleben** [comment]
Hey there, thanks for the report. What specific model of device are you using?

**Comment by jaulz** [comment]
That one was an iPad mini.

**Comment by brentvatne** [comment]
fixed, open the app again and it'll download update in the background so next time you restart it'll have some prettier tabs

**Comment by jaulz** [comment]
Can you tell me what the reason for this issue was? I see a similar issue for one of my apps.
