### ISSUE TITLE
PluginError: Failed to resolve plugin for module react-native-fbads

### ISSUE THREAD

**Issue by 123epsilon** [expo/expo#18632]
### Summary

Hi, just looking for some support as I am new to using config plugins and I can't figure out why I can't install react-native-fbads. My goal is to add banner ad functionality to a managed expo app that is using the EAS build system. Essentially, I've followed the readme [here](https://github.com/callstack/react-native-fbads) but attempting to run an eas build results in the following error:

`PluginError: Failed to resolve plugin for module "react-native-fbads" relative to "D:\Projects\pollenbbmap"
    Code: PLUGIN_NOT_FOUND`

I installed the facebook SDK and facebook ads modules as follows and then attempt to build:
```
expo install react-native-fbsdk-next react-native-fbads
eas build --profile development --platform ios 
```

These are the exact commands I used but the problem persists across android and ios. Attempting to run `expo rebuild --clean` fails with the same error.

This is my app.json where I configured the plugins array:
```
{
  "expo": {
    "owner": "gainesvilleboyz",
    "name": "pollenbbmap",
    "slug": "pollenbbmap",
    "version": "0.0.1",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.arham23.pollenbbmap"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "react-native-fbsdk-next",
        {
          "appID": "113xxxxxxxxx",
          "clientToken": "0073xxxxxxxx",
          "displayName": "Pollen Map App",
          "advertiserIDCollectionEnabled": false,
          "autoLogAppEventsEnabled": false,
          "isAutoInitEnabled": true,
          "iosUserTrackingPermission": "This identifier will be used to deliver personalized ads to you."
        }
      ],
      "react-native-fbads"
    ]
  }
}

```

### What platform(s) does this occur on?

Android, iOS

### SDK Version

45

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.9.0 - D:\NodeJS\node.EXE
      npm: 6.14.8 - D:\NodeJS\npm.CMD
    npmPackages:
      expo: ~45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: ^0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Minimal reproducible example

There is no code for this, just an environment configuration

**Comment by brentvatne** [comment]
it sounds like the "react-native-fbads" library does not have a plugin and so you can remove it from your `plugins` array in app.json. looking at the repo it appears to have one so maybe you're using an old version of it? either way, happy to help if you can share a reproducible example

**Comment by Brunowilliang** [comment]
I'm having the same error, I can't run the project :/

**Comment by ahmedNaoumDev** [comment]
I have the same issue, I fixed it by just reinstall the package and restart you editor
