### ISSUE TITLE
Eas build does not do remove a permission from android-manifest

### ISSUE THREAD

**Issue by arjendevos** [expo/expo#18643]
### Summary

Somehow expo adds the QUERY_ALL_PACKAGES permission to the app. We wanted that removed since we don't use that. We can not upload to the play store if we have this permission enabled. So we made a plugin that removes it from the manifest. If we run this locally with `expo prebuild` is builds correctly without the QUERY_ALL_PACKAGES permission in the android-manifest.

But if we build it in the cloud with eas build, it runs the plugin and it removes it in the plugin (i've checked with console logs see below), but when i unpack or upload the aab file to playstore it still has the QUERY_ALL_PACKAGES permission in the android-manifest.

```
REMOVING IN MANIFEST
- Config syncing
{
  androidManifest: [
    { '$': [Object] },
    { '$': [Object] },
    { '$': [Object] },
    { '$': [Object] },
    { '$': [Object] },
    { '$': [Object] }
  ]
}
- Config syncing
test:  android.permission.INTERNET
- Config syncing
test:  android.permission.SYSTEM_ALERT_WINDOW
- Config syncing
test:  android.permission.VIBRATE
- Config syncing
test:  android.permission.READ_EXTERNAL_STORAGE
- Config syncing
test:  android.permission.WRITE_EXTERNAL_STORAGE
- Config syncing
test:  QUERY_ALL_PACKAGES
- Config syncing
RETURN FALSE (meaning remove it from array with .filter)
- Config syncing
{
  androidManifest: [
    { '$': [Object] },
    { '$': [Object] },
    { '$': [Object] },
    { '$': [Object] },
    { '$': [Object] }
  ],
  config: {
    '$': {
      'xmlns:android': 'http://schemas.android.com/apk/res/android',
      package: 'com.webridge.dgv',
      'xmlns:tools': 'http://schemas.android.com/tools'
    },
    'uses-permission': [ [Object], [Object], [Object], [Object], [Object] ],
    queries: [ [Object] ],
    application: [ [Object] ]
  }
}```

### What platform(s) does this occur on?

Android

### SDK Version

45

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 31, 32
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: bare
```

### Minimal reproducible example

Our android-manifest-plugin.js:
```javascript
const { withAndroidManifest } = require("@expo/config-plugins");

module.exports = function androiManifestPlugin(config) {
  return withAndroidManifest(config, async (config) => {
    let androidManifest = config.modResults.manifest;

    console.log("REMOVING IN MANIFEST");

    // add the tools to apply permission remove
    androidManifest.$ = {
      ...androidManifest.$,
      "xmlns:tools": "http://schemas.android.com/tools",
    };

    console.log({ androidManifest: androidManifest["uses-permission"] });

    // add remove property to the audio record permission
    androidManifest["uses-permission"] = androidManifest["uses-permission"].filter((perm) => {
      console.log("test: ", perm.$["android:name"]);
      if (perm.$["android:name"].includes("QUERY_ALL_PACKAGES")) {
        console.log("RETURN FALSE");
        return false;
      }
      return perm;
    });

    console.log({ androidManifest: androidManifest["uses-permission"], config: config.modResults.manifest });

    return config;
  });
};

```

Our app config:
```javascript
expo: {
  plugins: ["./android-manifest.plugin.js"],
}
```

Link to build:
[https://expo.dev/accounts/richardlindhout/projects/de-grote-verleiding/builds/b2ccf81a-3f60-4ab5-8d4a-e205bef51399](https://expo.dev/accounts/richardlindhout/projects/de-grote-verleiding/builds/b2ccf81a-3f60-4ab5-8d4a-e205bef51399)

**Comment by Kudo** [comment]
hi there! i would like to know which module introduced the QUERY_ALL_PACKAGES permission. could you provide a minimal reproducible example to help us for further investigation? thanks!
