### ISSUE TITLE
push notification is not working in Expo SDK 46.0.6

### ISSUE THREAD

**Issue by Harsh2400** [expo/expo#18644]
### Summary

**_I have set up for push notification using FCM . I did include google-services.json and added it to my app.json after that added the server key and re built the app_** but it throws an error as : - 

i have every valid configuration as that of sdk 45

**It was all working good till sdk 45.0.0** 

**Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.**

at node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:null in promiseMethodWrapper       
at node_modules\expo-modules-core\build\NativeModulesProxy.native.js:null in moduleName.methodInfo.name  
at node_modules\expo-notifications\build\getDevicePushTokenAsync.js:null in getDevicePushTokenAsync      
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in asyncGeneratorStep
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in _next
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in Promise$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in Promise
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in <anonymous>
at http://192.168.1.6:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in _getDevicePushTokenAsync
at http://192.168.1.6:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in getDevicePushTokenAsync
at node_modules\expo-notifications\build\getExpoPushTokenAsync.js:null in getExpoPushTokenAsync
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in asyncGeneratorStep
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in _next
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in Promise$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in Promise
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in <anonymous>
at http://192.168.1.6:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in _getExpoPushTokenAsync
at http://192.168.1.6:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in getExpoPushTokenAsync
at screens\test\Notify.js:null in registerForPushNotificationsAsync
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in asyncGeneratorStep
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in _next
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in setImmediate$argument_0   
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in _allocateCallback$argument_0      
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in _callReactNativeMicrotasksPass    
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in callReactNativeMicrotasks
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __callReactNativeMicrotasks 
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in flushedQueue

### What platform(s) does this occur on?

Android

### Environment

This is my package.json

{
  "name": "medsline-v-1",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "expo": "~46.0.6",
    "expo-device": "~4.3.0",
    "expo-firebase-recaptcha": "~2.3.0",
    "expo-notifications": "~0.16.1",
    "expo-splash-screen": "~0.16.1",
    "expo-status-bar": "~1.4.0",
    "firebase": "^9.6.11",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.4",
    "react-native-pager-view": "5.4.24",
    "react-native-safe-area-context": "4.3.1",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0",
    "expo-system-ui": "~1.3.0",
    "expo-navigation-bar": "~1.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

### Minimal reproducible example

this i ssame example from documentation

`import { StatusBar } from "expo-status-bar";
import * as Notifications from "expo-notifications";
import * as Device from "expo-device";
import React, { useState, useEffect, useRef } from "react";
import { Text, View, Button, Platform, StyleSheet } from "react-native";

export default function Notify() {
  const [expoPushToken, setExpoPushToken] = useState("");
  const [notification, setNotification] = useState(false);
  const notificationListener = useRef();
  const responseListener = useRef();

  useEffect(() => {
    registerForPushNotificationsAsync()
      .then((token) => {
        setExpoPushToken(token);
      })
      .catch((error) => {
        console.log("firebase congiguration error failed to get expoPushToken");
        console.log(error);
      });

    notificationListener.current =
      Notifications.addNotificationReceivedListener((notification) => {
        setNotification(notification);
      });

;

    return () => {
      Notifications.removeNotificationSubscription(
        notificationListener.current
      );
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);
}

async function sendPushNotification(expoPushToken) {
  //Alert.alert("Push notify")
  const message = {
    to: expoPushToken,
    sound: "default",
    title: "Push notification",
    body: "push notification is working all fine",
    data: { someData: "goes here" },
  };

  const res = await fetch("https://exp.host/--/api/v2/push/send", {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Accept-encoding": "gzip, deflate",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(message),
  });
}

async function registerForPushNotificationsAsync() {
  let token;
  if (Device.isDevice) {
    const { status: existingStatus } =
      await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== "granted") {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== "granted") {
      alert("Failed to get push token for push notification!");
      return;
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log(token);
  } else {
    console.log("Must use physical device for Push Notifications");
  }

  if (Platform.OS === "android") {
    Notifications.setNotificationChannelAsync("default", {
      name: "default",
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: "#FF231F7C",
    });
  }

  if (!token) {
    return 0;
  }

  return token;
}
`

**Comment by Kudo** [comment]
duplicated issue as #18642 and https://github.com/expo/expo/issues/18570#issuecomment-1211583962. i'm going to close this and keep updated in #18642. thanks for reporting this issue to us.
