### ISSUE TITLE
Firestore not working on android emulator new Expo Go app and 46.0.7 SDK. Throwing Errors

### ISSUE THREAD

**Issue by SohelIslamImran** [expo/expo#18648]
### Summary

It seems like the new Expo Go app on android studio emulator can't reach internet connection. I have a strong internet connection. But It is throwing these errors:

```sh
ERROR  [2022-08-15T19:48:15.318Z]  @firebase/firestore: Firestore (9.9.2): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in 
offline mode until it is able to successfully connect to the backend.
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Failed to get document because the client is offline.
http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:336871:26
generatorResume@[native code]
asyncGeneratorStep@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:25072:26_throw@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:25098:29
tryCallOne@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:30570:16        
http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:30671:27
http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:31750:26
_callTimer@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:31650:17        
_callReactNativeMicrotasksPass@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:31685:17
callReactNativeMicrotasks@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:31892:44
__callReactNativeMicrotasks@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:24002:46
http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:23781:45
__guard@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:23985:15
flushedQueue@http://192.168.0.107:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:23780:21      
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]
```

![image](https://user-images.githubusercontent.com/76745339/184708194-63f0117d-38ef-4191-a375-ddf1701abb3f.png)

But working on the real device, there are no errors.

### What platform(s) does this occur on?

Android, iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\.yarn\bin\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      expo: ^46.0.7 => 46.0.7
      react: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
    Expo Workflow: managed
```

### Minimal reproducible example

![image](https://user-images.githubusercontent.com/76745339/184708306-2d2614a3-cb42-4ced-8831-fa220a5d740d.png)
![image](https://user-images.githubusercontent.com/76745339/184708366-49b105ff-2636-4e68-9e82-05896956bdb5.png)
![image](https://user-images.githubusercontent.com/76745339/184708389-5d250b64-f6a2-4acf-a2d3-3c55ba39ee2e.png)

**Comment by SohelIslamImran** [comment]
The Android studio emulator has a good internet connection.

![image](https://user-images.githubusercontent.com/76745339/184709939-2c537f7b-6e1b-425a-92f8-79a95f623ce3.png)

**Comment by SohelIslamImran** [comment]
Also, Firebase auth is not working 
![image](https://user-images.githubusercontent.com/76745339/184711186-91dd5de8-42be-4c51-a9c3-40cdfcfffc5d.png)

**Comment by SohelIslamImran** [comment]
Actually, the app is not `fetch` anything. I tried this

![image](https://user-images.githubusercontent.com/76745339/184712364-29093b6d-eb8a-443d-a73d-19673599525a.png)

But no response

![image](https://user-images.githubusercontent.com/76745339/184712422-98e631dc-d787-4b5e-b1c4-d4c9665f7fc6.png)

**Comment by SohelIslamImran** [comment]
Any type of `fetch` not working.

**Comment by SohelIslamImran** [comment]
Another thing noticed, Firebase local emulator working, But not working the external apis 

![image](https://user-images.githubusercontent.com/76745339/184972562-3c181d8d-42e9-4fd7-a6cc-877532eda32f.png)

**Comment by AlexanderLid** [comment]
Hi, I just found this issue. I am having the exact same issue but for my own flutter project, so this might not be related to expo. Everything works on a physical device, I have added everything, permission, dependencies, plugins etc. Internet is working on the emulator,just like you, and the firebase app is initializing successfully. But as soon as i request any documents it has no connection. 
Feel free to tag me if you find a solution, or create an issue elsewhere where I can contribute with logs, code, etc.

**Comment by SohelIslamImran** [comment]
@AlexanderLid Can you also create an issue in the firebase repo?

**Comment by dylanrandle** [comment]
I'm also having this problem. Were you able to resolve this?

**Comment by dylanrandle** [comment]
I was able to resolve this by replacing
```
const firestore = getFirestore(app)
```
with
```
const firestore = initializeFirestore(app, { experimentalAutoDetectLongPolling: true })
```
as indicated [here](https://github.com/firebase/firebase-js-sdk/issues/5977#issuecomment-1093533220).

**Comment by nlarif** [comment]
Hi, same problem with Expo Dev Client on Android Emulator or Android physical devices.
experimentalAutoDetectLongPolling setting is not changing anything.

It is working fine on Android once compiled after EAS Build. From my understanding, it might be related to the expo-dev-client running on Android. iOS works fine on Simulator, physical devices (expo-dev-client) and after compiled with EAS Build.



```
firebase 9.11.0
expo-firebase-core 5.2.0


expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.npm-packages/bin/yarn
      npm: 8.15.1 - ~/.npm-packages/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.15
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: bare
```

**Comment by SamMakesCode** [comment]
`connectAuthEmulator()` and `connectFirebaseEmulator()` want slightly different parameters. When I removed the 'http://' prefix from my `connectFirebaseEmulator`, it started working.

Tested on `@firebase@^9.9.4`

**Comment by lucasrangell** [comment]
> I was able to resolve this by replacing
> 
> ```
> const firestore = getFirestore(app)
> ```
> 
> with
> 
> ```
> const firestore = initializeFirestore(app, { experimentalAutoDetectLongPolling: true })
> ```
> 
> as indicated [here](https://github.com/firebase/firebase-js-sdk/issues/5977#issuecomment-1093533220).

Finally! I have tried a lot of possibilities but none of them worked... That one works like a charm! Thanks!!
