### ISSUE TITLE
[SDK46][IOS] getting the error `Invariant Violation: new NativeEventEmitter() requires a non-null argument` on IOS after upgrading to SDK46

### ISSUE THREAD

**Issue by khzouroussama** [expo/expo#18640]
### Summary

After upgrading to SDK46 i started getting this error `Invariant Violation: new NativeEventEmitter() requires a non-null argument` on IOS (it worked perfectly on android), the project builds correctly but when the app launches this error shows up, it seems to be caused by `PushNotificationIOS` which i am not using in my project.

```
 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

and here is what shows on the simulator:

![image](https://user-images.githubusercontent.com/20207933/184549389-e82f28ef-b9d9-4781-bd15-59283c347bcc.png)

### What platform(s) does this occur on?

iOS

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.6 => 46.0.6
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.7
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.2
    Expo Workflow: managed
```

### Minimal reproducible example

- no reproduction steps (only updated the SDK version)

**Comment by kozarip** [comment]
I'm having the same issue after upgrading my expo to SDK 45. 
The error occurs in every startup

@khzouroussama Could you fix this issue? 

Thank You

**Comment by khzouroussama** [comment]
@kozarip yes,
for me i found that the error was not showing because of expo new sdk, but from my babel config, once i fixed it, it worked as expected

**Comment by westofpluto** [comment]
We're having this same issue. Please tell us how to fix it. Repeated pod install does not do anything
