### ISSUE TITLE
Unable to resolve "./Libraries/Components/DatePicker/DatePickerIOS" from "node_modules\react-native\index.js"

### ISSUE THREAD

**Issue by camnpr** [expo/expo#18645]
### Summary

I see like question. link [https://github.com/expo/expo/issues/3722](https://github.com/expo/expo/issues/3722)

I just update sdk from 45 to 46.

I use SDK `https://github.com/expo/react-native/archive/sdk-46.0.0.tar.gz`. tips react-native 0.69.1.

but it is error `Unable to resolve "./Libraries/Components/DatePicker/DatePickerIOS" from "node_modules\react-native\index.js"`

### What platform(s) does this occur on?

Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.17134
    Binaries:
      Node: 14.17.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4408382
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2
      expo: ~46.0.6 => 46.0.7
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: https://github.com/expo/react-native/archive/sdk-46.0.0.tar.gz => 0.69.1
      react-native-web: 0.18.7 => 0.18.7
    Expo Workflow: bare

### Minimal reproducible example

similar problems link: [https://github.com/expo/expo/issues/3722](https://github.com/expo/expo/issues/3722)

**Comment by Kudo** [comment]
hi there! as far as i can tell, you can simply use `react-native@0.69.4` without using expo's fork. if that doesn't work for you, please provide a minimal reproducible example for us to do further investigation. thanks!

**Comment by cuddeford** [comment]
> hi there! as far as i can tell, you can simply use `react-native@0.69.4` without using expo's fork. if that doesn't work for you, please provide a minimal reproducible example for us to do further investigation. thanks!

Based on [this issue](https://github.com/facebook/react-native/issues/36794#issuecomment-1621532862) the relevant version would be 0.69.12. I've tried installing it directly but the error persisted.

> [0.72.0](https://github.com/facebook/react-native/releases/tag/v0.72.0)
> [0.71.11](https://github.com/facebook/react-native/releases/tag/v0.71.11)
> [0.70.12](https://github.com/facebook/react-native/releases/tag/v0.70.12)
> [0.69.12](https://github.com/facebook/react-native/releases/tag/v0.69.12)
