### ISSUE TITLE
No sound or vibration in Android push notif in Expo Client; works on iOS

### ISSUE THREAD

**Issue by WeiMin1** [expo/expo#1864]
I am just testing around with the push notification on android and ios devices. There is vibration and sound when i test on my ios device via expo client.

However when i show the app on my android devices via expo client, the push notification does not show any heads up display, it only shows the icon on the status bar, there was no sound no vibration even though i set those to true already.

Is there any permissions to enable? 

import React from 'react';
import { StyleSheet, Text, View, Button,Platform,TouchableHighlight, Alert } from 'react-native';
import { Notifications, Permissions, Constants,Haptic } from 'expo'
import moment from 'moment'

export default class Login extends React.Component {
  async componentDidMount() {
    let result = await Permissions.askAsync(Permissions.NOTIFICATIONS);

    if (Constants.isDevice && result.status === 'granted') {
      console.log('Notification permissions granted.')
    }
    this.listenForNotifications();
  }

  // Private methods
  listenForNotifications = () => {
    Notifications.addListener(notification => {
      if (notification.origin === 'received' && Platform.OS === 'ios') {
        Alert.alert(
          'Alert Title',
          'My Alert Msg',
          [
            {text: 'Ask me later', onPress: () => console.log('Ask me later pressed')},
            {text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
            {text: 'OK', onPress: () => console.log('OK Pressed')},
          ],
          { cancelable: false }
        )
      }
    });
  };
  _handleNotification = ({ origin, data }) => {
    console.info(`Notification (${origin}) with data: ${JSON.stringify(data)}`)
  }

  _sendImmediateNotification () {
    
    const localNotification = {
      title: 'Testing immediate testing Title',
      body: 'Testing body',
      data: { test: 'value' },
      vibrate: true,
      sound:true,
      android: {
        sound: true,
      },
      ios: {
        sound: true,
      },
      priority:'max',
    }
    if(Platform.OS === 'ios')
    {
   
    }
    else
    {
    Notifications.presentLocalNotificationAsync(localNotification)
      .then(id => console.info(`Immediate notification scheduled (${id})`))
      .catch(err => console.error(err))
  }
  console.log(localNotification.priority)
  console.log('Scheduling immediate notification:', { localNotification })

}

  _sendDelayedNotification (title,body) {
    const localNotification = {
      title: title,
      body: body,
      data: { test: 'value' },
      priority : 'high',
      vibrate: true,
      sound:true,
      android: {
        sound: true,
      },
      ios: {
        sound: true,
      },
    }
    const schedulingOptions = {
      time: (new Date()).getTime() + 5000
    }

    console.log('Scheduling delayed notification:', { localNotification, schedulingOptions })

    Notifications.scheduleLocalNotificationAsync(localNotification, schedulingOptions)
      .then(id => console.info(`Delayed notification scheduled (${id}) at ${moment(schedulingOptions.time).format()}`))
      .catch(err => console.error(err))
  }

  // Rendering

  render() {
    return (
      <View style={styles.container}>        
        
        <TouchableHighlight
         style={styles.button}
         onPress={this._sendImmediateNotification}
        >
         <Text> Send notif </Text>
        </TouchableHighlight>
        
        <Button title='Send Delayed Notification' onPress={() => this._sendDelayedNotification('Delayed testing Title','Body')} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    position: 'absolute',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  }
});

**Comment by terribleben** [comment]
Hi there, thanks for the report. What does your `app.json` look like? Is it possible to create a minimal repro that we can run from https://snack.expo.io/ ?

**Comment by WeiMin1** [comment]
Sorry about that here is the snack link
https://snack.expo.io/ry3qLrJ-X

**Comment by esamelson** [comment]
Hey @WeiMin1 - you need to use notification channels for this. This is due to a change required to target Android Oreo. See https://docs.expo.io/versions/latest/guides/notification-channels and https://blog.expo.io/breaking-change-coming-to-android-apps-3116927f0424 for more info.

Sorry for the slow followup. Hope this helps!
