### ISSUE TITLE
MapView not working

### ISSUE THREAD

**Issue by imatheus-lucas** [expo/expo#18649]
### Summary

map view of react-native-maps is only fray screen
![image](https://user-images.githubusercontent.com/59959122/184721835-c3e55550-d2bd-4506-a87d-3c90653a8085.png)

### What platform(s) does this occur on?

Android

### Environment

windows 11
sdk 46.0.7
react-native-maps 0.31.1

### Minimal reproducible example

within the expo snack plataform itself occurs the same problem

![image](https://user-images.githubusercontent.com/59959122/184722287-129b7b0d-95c6-4ff8-b3ce-44dbd4b003c6.png)

**Comment by SohelIslamImran** [comment]
Duplicate https://github.com/expo/expo/issues/18554

**Comment by brentvatne** [comment]
you can use expo go for sdk 45 or a [development build](https://docs.expo.dev/development/introduction/) to work around this for now

**Comment by hanamurayuki** [comment]
I also face same problem. 
IOS is ok, but blank map on android with `eas build`.
Reason is google map api authorization. (logo exists, but map is brank)

Document was updated on Fri Nov 25 2022.
https://docs.expo.dev/versions/latest/sdk/map-view/

> # [Deploy app with Google Maps](https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps)
> ## [Android](https://docs.expo.dev/versions/latest/sdk/map-view/#android)
> 
> 2. [Copy your app's SHA-1 certificate fingerprint](https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint)
> For development builds
> - If you have already created a [development build](https://docs.expo.dev/development/introduction/), your project will be signed using a debug keystore.
> - After the build is complete, go to your [project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D), then, under Configure > click Credentials.
> - `Under Application Identifiers, click your project's package name and under Android Keystore copy the value of SHA-1 Certificate Fingerprint.`

Not only uploading `Google Play Store's SHA-1 certificate fingerprint` on GCP's google map api, 
but we need to upload  `Expo's SHA-1 certificate fingerprint` on GCP ([project's dashboard](https://expo.dev/accounts/%5Busername%5D/projects/%5Bproject-name%5D) > Configure > click Credentials >  Application Identifiers > click your project's package name and under Android Keystore), 

After uploading `Expo's SHA-1 certificate fingerprint on GCP`, app loads map successfully.
