### ISSUE TITLE
Facebook login causes infinite loop when user has facebook app installed

### ISSUE THREAD

**Issue by goMEditate** [expo/expo#18655]
### Summary

I have expo 43 app and facebook login implemented. It works completely fine when user logs in with the pop-up window, but if the user has the facebook app logged in on his device the login flow forwards the user to the facebook app, then back to my app and nothing happens. It acts like an infinite loop, because even though user gives permission in facebook app it still doesn't log the user in my app. 

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - /opt/homebrew/bin/node
      Yarn: 1.22.11 - /opt/homebrew/bin/yarn
      npm: 8.13.2 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.18 => 0.3.19 
      expo: ~43.0.5 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 6.0.2
    Expo Workflow: managed

### Minimal reproducible example

  async function onFacebookButtonPress() {
    try {
      await Facebook.initializeAsync({
        appId: '3022342571415551',
      });
      const { type, token, expirationDate, permissions, declinedPermissions } =
        await Facebook.logInWithReadPermissionsAsync({
          permissions: ['public_profile', 'email'],
        });
      if (type === 'success') {
        // Get the user's name using Facebook's Graph API
        const fbresponse = await fetch(
          `https://graph.facebook.com/me?access_token=${token}`
        );
        var result = await fbresponse.json();
        const fieldsResponse = await fetch(
          `https://graph.facebook.com/${result.id}?fields=id,name,email&access_token=${token}`
        );
        var fieldsResult = await fieldsResponse.json();
        await firebase
          .auth()
          .setPersistence(firebase.auth.Auth.Persistence.LOCAL); // Set persistent auth state
        const credential = firebase.auth.FacebookAuthProvider.credential(token);
        const facebookProfileData = await firebase
          .auth()
          .signInWithCredential(credential)
          .then(response => {
            const isNewUser = response.additionalUserInfo.isNewUser;
            if (isNewUser) {
              var uid = response.user.uid;
              var name = result.name.split(' ')[0];
              var email = fieldsResult.email;
              const data = { id: uid, email, name, authType: 'FB' };
              const usersRef = firebase.firestore().collection('users');

              usersRef
                .doc(uid)
                .set(data)
                .then(() => {
                  dispatch(setUserData(data));
                })
                .catch(error => {
                  alert(`facebook user creation error: ${error.code} ${error.message}`);
                  createLog(error, 'login by facebook');
                });
            }
          })
          .catch(error => {
            alert(`facebook signin error: ${error.code} ${error.message}`);
            createLog(error, 'login by facebook');
          }); // Sign in with Facebook credential
        const userId = facebookProfileData.user.uid;
      }
    } catch ({ message }) {
      alert(`facebook auth error: ${error.code} ${error.message}`);
      createLog(error, 'login by facebook');
    }
  }

**Comment by BrodaNoel** [comment]
Ufff... SDK 43 is quite old now. Have you tried upgrading to SDK 45? SDK 45 is the last version who supports `expo-facebook`, which it could fix the problem you have. I used it during quite long time without any problem.

In SDK 46 you must migrate to other library (but still quite simple to do it. I did it. I just had to change 5 or 6 lines of code)

**Comment by brentvatne** [comment]
we no longer support sdk 43 or expo-facebook. here are the docs for the last version supporting expo-facebook: https://docs.expo.dev/versions/v45.0.0/sdk/facebook/

> Deprecated. This module will be removed in SDK 46. There will be no replacement that works with the classic build service (expo build) because [the classic build service has been superseded by EAS Build](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60). With EAS Build and [Development Builds](https://docs.expo.dev/development/introduction/), you should use [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/#expo-installation) instead.
