### ISSUE TITLE
[docs] Mismatch with node-sdk receipt errors.

### ISSUE THREAD

**Issue by muniter** [expo/expo#18668]
### Summary

Documentation describes the error `MismatchSenderId` which is not present on the node sdk.

Documentation: https://docs.expo.dev/push-notifications/sending-notifications/#push-receipt-errors
Node SDK: https://github.com/expo/expo-server-sdk-node/blob/0205b91631561b771fecc8c04e03ed6bed89fa57/src/ExpoClient.ts#L384

### Link to the related docs page

https://docs.expo.dev/push-notifications/sending-notifications/#push-receipt-errors

**Comment by limzykenneth** [comment]
Still no resolution on this?

**Comment by 25khattab** [comment]
what a great sdk
