### ISSUE TITLE
Some apps created with `exp build:ios` after June 12 crash on launch

### ISSUE THREAD

**Issue by serhiipalash** [expo/expo#1867]
### Environment

| software         | version
| ---------------- | -------
| expo | 27.0.0, 28.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz
| device    | iPhone 6s, iPhone 8

`exp diagnostics` output

<img width="1006" alt="screen shot 2018-06-05 at 12 32 49 pm" src="https://user-images.githubusercontent.com/14208343/40967785-aa2093f6-68bc-11e8-8736-c900a79c6a78.png">

App's target is iOS Standalone

### Steps to Reproduce

1. Run `exp build:ios`

2. Upload build to iTunes Connect

3. Install app on your phone with TestFlight

4. Try to open it

### Expected Behavior

iOS standalone app should start.

### Actual Behavior

Running *exp build:ios* on Expo 27 without any changes in code creates ipa file that crashes each time I try to open it. I tried to build twice and results are the same.

Updating Expo to 28 didn't help.

https://drive.google.com/open?id=1v3OIeKWIscSE6KTW1iMuqd3VdcM2v1KS

Yesterday the new builds were working. 

### Reproducible Demo

No demo.
In Simulator all works fine. I tried with and without "Development mode" in Simulator and everything works fine. The problem is only with iOS standalone app.

Please fix it.

**Comment by AdamJNavarro** [comment]
Changed the title as it was very misleading and resulted in some users thinking any SDK28 build would crash. Closing this issue. Please continue to use https://github.com/expo/expo/issues/1829 to track the issue.

**Comment by msevestre** [comment]
@AdamJNavarro 
In #1829, @serhiipalash says 
>without any changes in code creates ipa file that crashes each time I try to open it either online or offline.

so it seems not to affect online and offline. 
This needs to be double checked with @serhiipalash

**Comment by serhiipalash** [comment]
Yes @msevestre is right. The app crashes always even if I have network connection.

@AdamJNavarro check video I recorded - wifi is connected

Yesterday I built iOS app with Expo 27 and the app at least worked while online. 

And today when I build new iOS app it doesn't work at all. I didn't change anything in code since yesterday. I am still on SDK27 and all new iOS builds are broken.

Even if I update the code to SDK28, all new iOS builds are still broken.

>  some users thinking any SDK28 build would crash. Closing this issue.

@AdamJNavarro any SDK28 build and any SDK27 build would crash. 
That's what this issue is about. It is not about broken offline start.

Please reopen it.

**Comment by serhiipalash** [comment]
> Please reopen it.

and change the title back :)

**Comment by AdamJNavarro** [comment]
My mistake. Inferred that it was offline-related since you put #1829 as a related issue. Reopening now. So you're saying a new, freshly-created Expo project that has no code changed's IPA is crashing?

**Comment by serhiipalash** [comment]
> So you're saying a new, freshly-created Expo project that has no code changed's IPA is crashing?

Yes, exactly. I built 2 times on my old code for SDK27 today and the bug was there, and I updated code to SDK28 and the same bug is in SDK28.

I am not sure why it is happening. Yesterday builds where fine with the same code.
The only difference I see from yesterday is that all 3 today's build had "queued" status for half an hour. I saw this in build logs.

**Comment by serhiipalash** [comment]
> freshly-created Expo project

@AdamJNavarro no, we have old enough project.

I will try now to create new Expo project on SDK28 and run new build. I will let you know if it works.

But I think the bug is in splash screen functionality. Check again video, it seems like splash screen falls and the app crashes then.

**Comment by serhiipalash** [comment]
I set https://github.com/expo/expo/issues/1829 as related because of this comment

> yeah SDK 28 will be going out tomorrow, and once it's out you'll just need to build a new version of your app. (no need to update as the fix will be applied to 27 as well -- it's just that we deploy them all at once.)

**Comment by terribleben** [comment]
Hi, I've created a SDK 28 project from Expo's starter template, run `exp build:ios`, uploaded to TestFlight, and opened it. It doesn't crash. I've also tried opening it offline and it doesn't crash offline either. So there must be some particular thing in your app which is crashing. Can you give me any other info about your app?

**Comment by serhiipalash** [comment]
@terribleben this is our app https://itunes.apple.com/se/app/preggers-gravid-och-baby-app/id1363479578

Maybe the problem is in the long "Queued" status during the build? I have started the new build with some changes in app.json and this build is "Queued" around 50 minutes now. Yesterday there was no queue.

Maybe today is the day of new releases because of the World Cup.

Also in app.json we have

```
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"],
      "sourceExts": ["ts", "tsx"],
      "transformer": "node_modules/react-native-typescript-transformer/index.js"
    },
```
Can this somehow affect the build process on your server?

**Comment by serhiipalash** [comment]
@terribleben 2 hours and 20 minutes in Queued and the bug is still there.

I tried to add "resizeMode" and "backgroundColor" to "splash" as they were missing in our app.json compared to the new project app.json.

```
    "splash": {
      "image": "./assets/img/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
```

It didn't help.

**Comment by samprimo** [comment]
Hi, we're experiencing the same issue with our app, in fact, it got rejected from the App Store as a result. 

At first we were convinced the issue was related to our production server but further testing via Test Flight, using newly built IPAs (which were a pain to build due to the ongoing building delays) pointing to our staging server indicates nothing is actually wrong with our code and that there is something deeper causing the app to crash on launch.

As stated by others above, the app will simply display the splash screen and immediately dim to a black screen and crash. It's been tested and replicated in an iPhone 7 Plus and an iPhone 5. Our last "working" build was built 4 days ago and no substantial code changes have been made between then and last night's/today's builds.

These are the Crash Logs that Apple attached to its rejection notice, see if anyone can may any sense of them:
- http://a1261.phobos.apple.com/us/r30/Purple125/v4/b8/93/7d/b8937d8e-73cd-382c-ddee-227b73280ebc/attachment-8823576395669141612crashlog-999D4E69-437B-4071-A3BD-CD0FABB73672.txt?downloadKey3=1529131069_b194d63d2dd34a9530c9ce83c1e0ab2c
- http://a1101.phobos.apple.com/us/r30/Purple115/v4/ac/28/54/ac285457-e941-5d39-2387-be3762c91d62/attachment-8307700397018954235crashlog-07BA069A-603D-4D70-8162-67D4704686DD.txt?downloadKey3=1529131069_b5f1400719aa7ae93e562b5f1e8fc9dc
- http://a1029.phobos.apple.com/us/r30/Purple115/v4/fa/45/e8/fa45e807-6a7c-49c7-5100-dee77d3532f9/attachment-1560299335178416489crashlog-3796A63C-B226-4B0C-9B47-7322F4A18135.txt?downloadKey3=1529131069_fe9d6f603d5677655fc60d38000d9a65
- http://a941.phobos.apple.com/us/r30/Purple125/v4/1f/27/69/1f2769ad-836a-b069-337f-c896d572c0c5/attachment-5598677579421320393crashlog-7A77039B-4479-45D5-B349-FC7A5E5A7AC8.txt?downloadKey3=1529131069_18f2da367b2d51675b78733f0f0b45ae

**Comment by serhiipalash** [comment]
Hi @samprimo !

When was the first time you got this issue, yesterday after Expo 28 release?

Also can you sign up in https://expo-developers.slack.com ? We can quickly discuss there this bug with you and compare our app.json files.

**Comment by samprimo** [comment]
@serhiipalash indeed. We ran into this issue on a build that was built a day ago. You may have a look at our app.json

```
{
"expo": {
        "name": "&&&&&",
        "description": "&&&&&",
        "slug": "&&&&&",
        "scheme": "&&&&&",
        "privacy": "public",
        "sdkVersion": "27.0.0",
        "version": "0.9.7",
        "orientation": "portrait",
        "primaryColor": "#cccccc",
        "icon": "./assets/icons/appstoreicon.png",
        "splash": {
            "image": "./assets/images/splash.png",
            "imageTablet": "./assets/images/splashTablet.png",
            "backgroundColor": "#1340A6",
            "resizeMode": "cover"
        },
        "assetBundlePatterns": [
            "assets/images/*",
            "assets/fonts/*",
            "assets/icons/*"
        ],
        "packagerOpts": {
            "assetExts": [
                "ttf",
                "mp4"
            ],
            "sourceExts": [
                "ts",
                "tsx"
            ],
        "transformer": "node_modules/react-native-typescript-transformer/index.js"
        },
        "ios": {
            "bundleIdentifier": "&&&&&",
            "supportsTablet": false,
            "buildNumber": "5",
            "infoPlist": {
                "NSLocationWhenInUseUsageDescription": "&&&&&",
                "LSApplicationQueriesSchemes": [
                    "waze",
                    "comgooglemaps"
                ]
            }
        },
        "extra": {
            "amplitudeApiKeyDev": "&&&&&",
            "amplitudeApiKeyStaging": "&&&&&",
            "amplitudeApiKeyProd": "&&&&&",
            "prod": {
                "baseUrl": "&&&&&",
                "url": "&&&&&"
            },
            "staging": {
                "baseUrl": "&&&&&",
                "url": "&&&&&"
            },
            "dev": {
                "baseUrl": "&&&&&",
                "url": "&&&&&",
                "redirectUrl": "&&&&&"
            }
        },
        "android": {
            "package": "&&&&&",
            "versionCode": 3,
            "config": {
                "googleMaps": {
                    "apiKey": "&&&&&"
                }
            }
        }
    }
}
```

**Comment by serhiipalash** [comment]
@samprimo this is our app.json

```
{
  "expo": {
    "name": "&&&&&",
    "description": "",
    "slug": "&&&&&",
    "scheme": "&&&&&",
    "privacy": "unlisted",
    "sdkVersion": "28.0.0",
    "version": "1.0.2",
    "orientation": "portrait",
    "platforms": ["ios"],
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app-icon.png",
    "splash": {
      "image": "./assets/img/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "assets/img/**",
      "assets/icons/**",
      "assets/sounds/**",
      "assets/fonts/**",
      "assets/resources/**"
    ],
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"],
      "sourceExts": ["ts", "tsx"],
      "transformer": "node_modules/react-native-typescript-transformer/index.js"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "ios": {
      "infoPlist": {
        "LSApplicationQueriesSchemes": [
          "fbapi",
          "fb-messenger-api",
          "fbauth2'",
          "fbshareextension"
        ],
        "NSCameraUsageDescription":
          "To be able to take and share images in &&&&&, the app needs to have access to the camera",
        "NSPhotoLibraryAddUsageDescription":
          "To be able to take and save images in &&&&&, the app needs to have access to your image library",
        "NSPhotoLibraryUsageDescription":
          "To be able to use images from your image library in &&&&&, the app needs to have access to your image library"
      },
      "buildNumber": "81",
      "supportsTablet": true,
      "bundleIdentifier": "&&&&&",
      "config": {
        "usesNonExemptEncryption": false
      }
    },
    "android": {
      "package": "&&&&&"
    },
    "locales": {
      "sv": "./translations/ios-native-dialogs/sv.json"
    },
    "facebookDisplayName": "&&&&&",
    "facebookAppId": "&&&&&",
    "facebookScheme": "&&&&&",
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "&&&&&",
            "project": "&&&&&",
            "authToken": "&&&&&"
          }
        },
        { "file": "./deploy/postPublish/notify" }
      ]
    }
  }
}
```

I think this part is common
```
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"],
      "sourceExts": ["ts", "tsx"],
      "transformer": "node_modules/react-native-typescript-transformer/index.js"
    },
```

I'll try to build today new expo project with and without these lines to test if it will work.

**Comment by serhiipalash** [comment]
@samprimo  removing TypeScript from code and *react-native-typescript-transformer* from app.json didn't help 😞

**Comment by serhiipalash** [comment]
And long build time is not related to this issue. This time I build has finished in 15 min.

**Comment by simjoh** [comment]
I do experience the same behaviour. An app with the very same code that apple could open 2 days ago is now rejected when i try to rebuild even tough rebuild is successful. When I try the app in testflight it crashes immediately. 
Almoast lost my hair during the last too days of frustration. I'm currently working with expo 24.

**Comment by serhiipalash** [comment]
@simjoh  can you share your app.json in the way like we did? Maybe we will find something in it.

**Comment by simjoh** [comment]
`{
  "expo": {
    "name": "&&&&",
    "description": "&&&&.",
    "slug": "&&&&",
    "privacy": "unlisted",
    "sdkVersion": "24.0.0",
    "version": "1.0.21",
    "primaryColor": "#56B563",
    "icon": "./assets/icon.png",
    "orientation": "portrait",
    "splash": {
      "image": "./assets/startiOS.png",
      "resizeMode": "cover",
      "backgroundColor": "#56B563",
    },
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "&&&&",
      "infoPlist":{
        "NSCameraUsageDescription": "This app needs access to take photos.",
        "NSPhotoLibraryAddUsageDescription":"This app needs to save photos on phone.",
        "NSPhotoLibraryUsageDescription":"This app needs to access photos on phone."

      },
    },
    "android": {
      "versionCode": 21,
      "package": "&&&&",
      "permissions" : [
        "CAMERA",
        "ACCESS_FINE_LOCATION",
        "READ_INTERNAL_STORAGE",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
        "NOTIFICATIONS"
      ]
    }

  }
}
`

**Comment by serhiipalash** [comment]
@simjoh thanks!

I guess the only thing left to try is to detach from Expo.

**Comment by simjoh** [comment]
Maybe, but how come that a release of a new version makes old releases to fail.

**Comment by serhiipalash** [comment]
The build script on Expo server was changed.
Maybe it was this fix https://github.com/expo/expo/issues/1829#issuecomment-396430010 or something else.

**Comment by serhiipalash** [comment]
btw, @simjoh , I see you have Android app, does it work on new builds?

**Comment by simjoh** [comment]
Actually I've not tried it. My plan was to release it on ios first. Maybe I've the change that strategy.

**Comment by ThomasLeCoz** [comment]
Same problem here, the Android build works fine.

**Comment by johisco** [comment]
Same issue here and still on Expo v26.

**Comment by serhiipalash** [comment]
@brentvatne ^

**Comment by terribleben** [comment]
Hi folks, thanks for sharing your app.json and those crash reports. So far I'm still not able to reproduce this issue. There's something your projects have in common that my test project apparently lacks. Here's the first thing I tried when attempting to reproduce:

- `exp init test-project`
- Edit `app.json` to add the required keys for building (`ios.bundleIdentifier`)
- `exp build:ios`
- Upload to Testflight on my personal Apple account with `fastlane pilot upload`
- Download via Testflight and open on my iPhone SE with iOS 11.3

The resulting app loads up fine without crashing.

Next steps-- I'm going to try the same thing but on an older SDK (before SDK 28) in case that's affecting it somehow.

Can anybody experiencing this issue answer some of these questions for me?

- What are some Expo APIs that your project runs when it first starts? I"m especially looking for ones which would not be included by default in my test project.
- If somebody has a relatively simple app which experiences this, can you invite me as a collaborator to your github repo so I can clone your code and try building your exact app locally on my machine?

**Comment by johnnietirado** [comment]
@terribleben I work with @samprimo 

Here are the API's we use during launch of the Application, in this order.

1. `Font.loadAsync`
2. `Updates.checkForUpdateAsync`
3. `Notifications.addListener`

Not Expo
4. `AsyncStorage.getItem`

Again, we are on SDK 27 and a build that we did 5 days ago was working fine.

**Comment by simjoh** [comment]
These are the expo APIs I use. 
Camera
Constants
FileSystem
Notifications
ImagePicker
Permissions 
WebBrowser

**Comment by brentvatne** [comment]
@simjoh - so a build that was created before June 12 doesn't work for you right now?

**Comment by rodrix** [comment]
Hello everyone, same issue here...
My IOS builds with expo sdk v27 made on last week is working fine, but yesterday I've made the sdk update (27 -> 28) and I starts having issues. The IOS builds won't work anymore.
My App starts opening, but seconds after, it closes without any feedback. It only happens on IOS... ;/

**Comment by brentvatne** [comment]
# Hey there! Going to post in this thread?

Please provide the build ID for a build that this happens to, if you do not then your comment will be deleted. Thanks!

**Comment by gogogous88** [comment]
tested both simulator and testflight. both immediate crash.
Expo SDK 24.0.0 and i also tried 23.0.0 same cash issues.

my IOS build link: https://expo.io/builds/c7655ded-ce48-415c-8044-4a0600fdabc9

**Comment by samprimo** [comment]
@brentvatne affected builds:
https://expo.io/builds/dfa873f9-8b20-4d19-b4a9-f14bbcc1ca07
https://expo.io/builds/68cb9847-eab7-490e-b3b6-372ee6c46278
https://expo.io/builds/a1c31695-c28c-49dc-9c6f-63fe1a6b860e
https://expo.io/builds/76d7cecf-a742-46db-af20-735a351f85dd

Last working build:
https://expo.io/builds/d0da9ada-31eb-4550-9c2d-1f63c1be6eb5

**Comment by altwohill** [comment]
Affected build:  https://expo.io/builds/9e922ff3-bd64-4592-912a-dd642e99aaa5

Android isn't affected.

Expo APIs being used on startup are `Font.loadAsync` and `Notifications.addListener`

Hmmm, do I remember something about `Font.loadAsync` being deprecated at some point, could that be it?

**Comment by johisco** [comment]
Same issue here Expo v26 

Last failed build : https://expo.io/builds/523899f2-47dd-42e5-999a-a7f0fb7fa273

Last working build (14 days ago, still works) : 
https://expo.io/builds/4b6499cf-a753-45a3-af30-7a5a2c624ce3

**Comment by brentvatne** [comment]
hi all! I believe we have located the issue, it is caused by non-ascii characters in app manifest. working on a fix right now, apologies for this inconvenience!

**Comment by terribleben** [comment]
I have a fix, but we won't finish deploying it to our app builders until later today. Thanks everyone who provided their build ids, they very much helped track down this bug.

**Comment by serhiipalash** [comment]
Thanks @terribleben !

**Comment by samprimo** [comment]
@terribleben @brentvatne We appreciate your time and help

**Comment by rodrix** [comment]
Dont worry, Bugs happen. :}
Thank you all for the amazing expo!
#keepGoing

**Comment by AzizAK** [comment]
Thank you very much guys @brentvatne @terribleben <3

**Comment by terribleben** [comment]
Hi everyone, we just finished deploying our standalone builders. Please try creating a new build with `exp build:ios` and see if the issue goes away for you.

**Comment by simjoh** [comment]
Well done @brentvatne and @terribleben! The new build works as expected.

**Comment by serhiipalash** [comment]
Everything works, including offline start. Thank you, guys!

I am closing this issue.
