### ISSUE TITLE
App freezing when using RN Reanimated in IOS with ---dev-client

### ISSUE THREAD

**Issue by amin79** [expo/expo#18676]
### Summary

EAS build and run the app with ---dev-client.
Use react native reanimated on the first page of the app.
Navigate to another page and go back to the main page.
The app will freeze.

It does not happen with expo go.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo": "~46.0.7",
"expo-build-properties": "~0.3.0",
"expo-dev-client": "^1.2.1",
"@react-navigation/stack": "^6.2.2",
"react-native": "0.69.4",
"react-native-reanimated": "^2.9.1",

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/Documents/Projects/iLord24/node_modules/.bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.21 => 0.3.22 
      expo: ~46.0.7 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.2
    Expo Workflow: managed

### Reproducible demo

import Animated, {
  ZoomIn,
  FlipInXDown,
  FlipInXUp,
  BounceInUp,
  BounceInDown,
} from "react-native-reanimated";
import { Button, Text, Title } from "react-native-paper";

`<Animated.View entering={BounceInDown.delay(1000)}>
            <Button
              mode="contained"
              onPress={() => {
                navigation.navigate("PhoneLogin");
              }}
              icon={() => (
                <AppIcon
                  type="Material"
                  name="cellphone-basic"
                  color={COLORS.SECONDARY}
                />
              )}
            >
              Signin with phone
            </Button>
          </Animated.View>`

**Comment by lukmccall** [comment]
Hi, can you create a better reproducible demo? I wasn't able to reproduce your bug.

**Comment by amin79** [comment]
@lukmccall Hi. It's just an Animated view with some animations imported from "react-native-reanimated" inside App.js.
You just need to press a button (you can ignore the icon component inside the button) to navigate to any secondary page, and then click on back button on the header to back to the previous page. Then app freezes.

FYI: If you navigate again from second page to a third page, and then navigate back again into the second page, it works. But from second page to the main page, it freezes.

When I run it with Expo go, everything works. But not when I build it with EAS.

**Comment by louix** [comment]
I don't have a reproducible build (wasn't able to narrow down the exact cause), but was experiencing freezes with Reanimated on the latest Expo build on iOS. Looking at the xcode debugger, the app was seemingly still alive and doing stuff Reanimated related.

Switched to [use Hermes](https://docs.expo.dev/guides/using-hermes/) and the problem went away.

**Comment by amin79** [comment]
@louix I also use Hermes but it's not fixed. There is also an open issue in react-native-reanimated [here](https://github.com/software-mansion/react-native-reanimated/issues/3388)

**Comment by jgo80** [comment]
I experience the same issue. Freeze happens randomly (and often). It seems to be related to React Navigation. May React Native Screens or React Native Gesture Handler cause trouble?

**Comment by flexa-david** [comment]
I also believe I'm experiencing this issue. I think seems to happen on some navigation, or could be related to rendering whatever is being navigated to.
