### ISSUE TITLE
[SDK-46] expo-modules-core CMake errors

### ISSUE THREAD

**Issue by Sewb21** [expo/expo#18683]
### Summary

I have 2 repos that use the latest Expo SDK - 46. On both, I've been getting CMake errors in the Android Studio terminal when running 'Refresh Gradle Dependancies' and a build.

I updated this repo to Expo SDK 46 when it was managed and then prebuilt the app after that.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FBJNI_LIB
linked by target "expo-modules-core" in directory /Users/sebsmith/test-cmake/node_modules/expo-modules-core/android
FOLLY_LIB
linked by target "expo-modules-core" in directory /Users/sebsmith/test-cmake/node_modules/expo-modules-core/android
JSEXECUTOR_LIB
linked by target "expo-modules-core" in directory /Users/sebsmith/test-cmake/node_modules/expo-modules-core/android
JSI_LIB
linked by target "expo-modules-core" in directory /Users/sebsmith/test-cmake/node_modules/expo-modules-core/android
REACT_NATIVE_JNI_LIB
linked by target "expo-modules-core" in directory /Users/sebsmith/test-cmake/node_modules/expo-modules-core/android
REACT_NATIVE_MODULES_CORE
linked by target "expo-modules-core" in directory /Users/sebsmith/test-cmake/node_modules/expo-modules-core/android
```

### What platform(s) does this occur on?

Android

### Environment

```  
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.2/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Patch 2 Chipmunk 2021.2.1 Patch 2
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.7 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: bare
```

### Minimal reproducible example

`npx create-expo-app test-cmake`
`cd test-cmake`
`rm yarn.lock`
`npm install`
`expo install`
`npx expo prebuild`

Open Android directory in Android Studio then refresh gradle dependancies then the error should appear in the console.

**Comment by matrec4** [comment]
I'm experiencing the same issue with a bare RN app with expo-modules-core and expo-av throwing this error when syncing gradle

**Comment by Sewb21** [comment]
Just to update, I ran `expo-cli doctor` to make sure all packages were up to date and it is still an issue

**Comment by phillipjfry93** [comment]
Dealing with the same issue, not sure if it matters but I just upgrade Android Studio.

**Comment by matrec4** [comment]
Not sure if that's the best way but got it to build for RN BARE app with expo-modules-core and expo-av by adding the extractHeaders and extractJNI commands in my app-level build.gradle file...


android {
   //.... your other configs here 
    configurations {
        extractHeaders
        extractJNI
    }
   //... default configs after
  }

dependencies {
    //... after fileTree implementation
    // If headers are required.
    extractHeaders 'com.facebook.fbjni:fbjni:0.2.2:headers'
    // If the `.so` files are required for linking.
    extractJNI 'com.facebook.fbjni:fbjni:0.2.2'
    //... your other dependencies here
}

// Then add tasks before the copyDownloadableDepsToLibs task
task extractAARHeaders {
    doLast {
        configurations.extractHeaders.files.each {
            def file = it.absoluteFile
            copy {
                from zipTree(file)
                into "$buildDir/$file.name"
                include "**/*.h"
            }
        }
    }
}

task extractJNIFiles {
    doLast {
        configurations.extractJNI.files.each {
            def file = it.absoluteFile
            copy {
                from zipTree(file)
                into "$buildDir/$file.name"
                include "jni/**/*"
            }
        }
    }
}

tasks.whenTaskAdded { task ->
    if (task.name.contains('externalNativeBuild')) {
        task.dependsOn(extractAARHeaders)
        task.dependsOn(extractJNIFiles)
    }
}

**Comment by Sewb21** [comment]
@matrec4 I just tried this and didn't seem to work for me unfortunately

**Comment by trymbill** [comment]
I had this same issue in my own project and when I opened Android Studio, it recommended upgrading Gradle Plugin from 7.1.1 to 7.2.2. After doing that, `Make Project` and `Run 'app'` worked fine.

I tried doing the same with the minimal reproducible example above, first getting the CMake errors, then upgrading Gradle Plugin to 7.2.2, and I was able to `Make Project` without an issue.

So I guess the question is ... how do we upgrade Gradle Plugin to 7.2.2 in a config plugin or some sticky way so that EAS builds don't fail?

**Comment by Sewb21** [comment]
@trymbill Guessing that even after upgrading gradle, syncing will still throw the cmake errors?

**Comment by trymbill** [comment]
> @trymbill Guessing that even after upgrading gradle, syncing will still throw the cmake errors?
> 

Yeah, if you `prebuild` again, it will downgrade the Gradle Plugin and fail again. But you could try making a development build on EAS, seeing that for some reason the build doesn't fail there, and then using that on your android device. As a quick fix of course, this obviously needs to get fixed IMO.

**Comment by SafdarSikander** [comment]
same here

**Comment by Sewb21** [comment]
> > @trymbill Guessing that even after upgrading gradle, syncing will still throw the cmake errors?
> 
> Yeah, if you `prebuild` again, it will downgrade the Gradle Plugin and fail again. But you could try making a development build on EAS, seeing that for some reason the build doesn't fail there, and then using that on your android device. As a quick fix of course, this obviously needs to get fixed IMO.

Ahh ok, I don't use EAS build on one of the projects so until this is fixed I'll have to hang fire unfortunately

**Comment by Kudo** [comment]
hi there!

i cannot reproduce the problem with the minimal reproducible example.

```
npx create-expo-app test-cmake
cd test-cmake
rm yarn.lock
npm install
expo install
npx expo prebuild
```

i am wondering if this issue also happens in running gradle from command line. could you help to check whether it works for you?
```
cd test-cmake/android
./gradlew :app:assembleDebug
```

**Comment by Sewb21** [comment]
@Kudo I ran `./gradlew :app:assembleDebug` and it seemed to worked ok

**Comment by archcorsair** [comment]
I started experiencing this same issue when upgrading `expo-av` from `11.2.3` to the current latest: `12.0.4`.

**Comment by PanamaDonne** [comment]
I'm also seeing this:

> >**React Native 0.69.5**
> > **React 18**
> > **Expo 46.0.13**

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FBJNI_LIB
linked by target "expo-modules-core" in directory /Users/nxc/ghq/github.com/app/node_modules/expo-modules-core/android
FOLLY_LIB
linked by target "expo-modules-core" in directory /Users/nxc/ghq/github.com/app/node_modules/expo-modules-core/android
JSI_LIB
linked by target "expo-modules-core" in directory /Users/nxc/ghq/github.com/app/node_modules/expo-modules-core/android
REACT_NATIVE_JNI_LIB
linked by target "expo-modules-core" in directory /Users/nxc/ghq/github.com/app/node_modules/expo-modules-core/android
REACT_NATIVE_MODULES_CORE
linked by target "expo-modules-core" in directory /Users/nxc/ghq/github.com/app/node_modules/expo-modules-core/android
```

**Comment by yousufnoor5** [comment]
Same issue.

**Comment by exzos28** [comment]
works with:
"expo": "46.0.10",
"react-native": "0.70.3"

**Comment by evgenyshenets91** [comment]
> works with: "expo": "46.0.10", "react-native": "0.70.3"

Did you add some specific code here for running expo 0.46.10 + react-native 0.70.3?

**Comment by exzos28** [comment]
> > works with: "expo": "46.0.10", "react-native": "0.70.3"
> 
> Did you add some specific code here for running expo 0.46.10 + react-native 0.70.3? For me it doesn't work for android

That's all. I got this error and solved it by clearing the Android Studio cache, also additionally
android: `./gradlew clean` and `rm -r $HOME/.gradle/caches/`

**Comment by yousufnoor5** [comment]
> works with:
> "

Tried this today. Same issue. I see only one solution create a new project with react native CLI and copy-paste js files from the expo project.

**Comment by Sewb21** [comment]
I'm also still getting this issue, I seem to be able to build the project but the gradle sync fails. Not sure if syncing gradle is required but it's occurred on the fourth project I've upgraded to SDK 46

**Comment by evgenyshenets91** [comment]
I was able to fix an issue. I've downgraded the Gradle to this version: "com.android.tools.build:gradle:7.2.1". Please try it out.

**Comment by exzos28** [comment]
> I was able to fix an issue. I've downgraded the Gradle to this version: "com.android.tools.build:gradle:7.2.1". Please try it out.

I am using 7.5.1 and have no issues.
I think you had a cache problem, not version.

**Comment by jreiscrf** [comment]
@evgenyshenets91 this worked for me, thanks

**Comment by Pcpkomputer** [comment]
same issue

**Comment by findhumane** [comment]
The workaround that works for me:

1. Run `npx expo prebuild`
2. Open Android Studio and the Android project
3. Wait for the build to fail with the CMake error
4. Ignore the suggestion to upgrade Gradle
5. Close Android Studio
6. Open Android Studio and the project
7. Click Build } Make Project

Strangely, trying Build } Make Project without first closing Android Studio doesn't work. I also tried upgrading the Gradle plugin, and deleting `~/.gradle/caches/`, but nothing worked until closing and re-opening Android Studio.

**Comment by luatvudinh** [comment]
This helped me https://github.com/mrousavy/react-native-vision-camera/issues/588#issuecomment-972589478

**Comment by CraigRonald555** [comment]
Had a similar issue relating to the CMake file within expo-modules-core recently after upgrading the gradle version.

To fix it I:

Went to SDK Manager within Android Studio, then in SDK tools, check CMake then Apply (if it isn't already), otherwise uncheck then apply and finally check and apply again (This should ensure you're on the latest version).

Then within the expo-modules-core build.gradle file, remove this block of code:

```
 externalNativeBuild {
    cmake {
      if (REACT_NATIVE_TARGET_VERSION >= 71) {
        path "CMakeLists.txt"
      } else {
        path "legacy/CMakeLists.txt"
      }
    }
}
```

I believe issues with CMake may be occuring because it's defaulting to an older version of CMake due to the block of code above.

**Comment by JoachimAmoah** [comment]
> Had a similar issue relating to the CMake file within expo-modules-core recently after upgrading the gradle version.
> 
> To fix it I:
> 
> Went to SDK Manager within Android Studio, then in SDK tools, check CMake then Apply (if it isn't already), otherwise uncheck then apply and finally check and apply again (This should ensure you're on the latest version).
> 
> Then within the expo-modules-core build.gradle file, remove this block of code:
> 
> ```
>  externalNativeBuild {
>     cmake {
>       if (REACT_NATIVE_TARGET_VERSION >= 71) {
>         path "CMakeLists.txt"
>       } else {
>         path "legacy/CMakeLists.txt"
>       }
>     }
> }
> ```
> 
> I believe issues with CMake may be occuring because it's defaulting to an older version of CMake due to the block of code above.

This was the only fix for me. Thanks @CraigRonald555

**Comment by Ozaoujal** [comment]
> Had a similar issue relating to the CMake file within expo-modules-core recently after upgrading the gradle version.
> 
> To fix it I:
> 
> Went to SDK Manager within Android Studio, then in SDK tools, check CMake then Apply (if it isn't already), otherwise uncheck then apply and finally check and apply again (This should ensure you're on the latest version).
> 
> Then within the expo-modules-core build.gradle file, remove this block of code:
> 
> ```
>  externalNativeBuild {
>     cmake {
>       if (REACT_NATIVE_TARGET_VERSION >= 71) {
>         path "CMakeLists.txt"
>       } else {
>         path "legacy/CMakeLists.txt"
>       }
>     }
> }
> ```
> 
> I believe issues with CMake may be occuring because it's defaulting to an older version of CMake due to the block of code above.

this was the solution for me too

this solution work

**Comment by rossparachute** [comment]
> > Had a similar issue relating to the CMake file within expo-modules-core recently after upgrading the gradle version.
> > To fix it I:
> > Went to SDK Manager within Android Studio, then in SDK tools, check CMake then Apply (if it isn't already), otherwise uncheck then apply and finally check and apply again (This should ensure you're on the latest version).
> > Then within the expo-modules-core build.gradle file, remove this block of code:
> > ```
> >  externalNativeBuild {
> >     cmake {
> >       if (REACT_NATIVE_TARGET_VERSION >= 71) {
> >         path "CMakeLists.txt"
> >       } else {
> >         path "legacy/CMakeLists.txt"
> >       }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe issues with CMake may be occuring because it's defaulting to an older version of CMake due to the block of code above.
> 
> This was the only fix for me. Thanks @CraigRonald555

This helped us get passed this error and complete a build successfully. react-native-reanimated v3.3.0 has a similar issue with the CMake externalNativeBuild files.

Thanks for the help so far. 

We did then run into the following errors on boot of the app. We think taking the CMake block out likely stops these .so files from being bundled. This is just a taster, there's other expo-modules-core .so files missing.

```
SoLoader E  couldn't find DSO to load: libjscexecutor.so
https://github.com/facebook/react-native/issues/32928#issuecomment-1336129791

See also:
https://github.com/facebook/react-native/issues/25537#issuecomment-1182498993
```
 

For what it's worth, package.json dependencies looked like (Gradle v8.0.1, CMake v3.22.1):

Env
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.0.0 - C:\Program Files\nodejs\node.EXE        
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.5.1 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636
    npmPackages:
      expo: 49.0.16 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    Expo Workflow: bare
```

```
  "dependencies": {
    "@mapbox/mapbox-gl-geocoder": "^5.0.1",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-picker/picker": "2.4.10",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@reduxjs/toolkit": "^1.9.5",
    "@rnmapbox/maps": "^10.0.15",
    "axios": "^1.3.5",
    "camelize": "^1.0.1",
    "date-fns": "^2.29.3",
    "date-fns-tz": "^2.0.0",
    "expo": "49.0.16",
    "expo-crypto": "~12.4.1",
    "expo-device": "~5.4.0",
    "expo-image-picker": "~14.3.2",
    "expo-keep-awake": "~12.3.0",
    "expo-linear-gradient": "~12.3.0",
    "expo-location": "~16.1.0",
    "expo-notifications": "~0.20.1",
    "expo-random": "~13.2.0",
    "expo-secure-store": "~12.3.1",
    "expo-splash-screen": "~0.20.5",
    "expo-standard-web-crypto": "^1.5.0",
    "expo-status-bar": "~1.6.0",
    "expo-task-manager": "~11.3.0",
    "expo-updates": "~0.18.17",
    "mapbox-gl": "^2.14.1",
    "object-hash": "^3.0.0",
    "react": "18.2.0",
    "react-bootstrap": "^2.7.4",
    "react-native": "0.72.6",
    "react-native-dotenv": "^3.4.8",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-get-random-values": "^1.8.0",
    "react-native-paper": "^5.7.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-root-siblings": "^4.1.1",
    "react-native-root-toast": "^3.4.1",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-webview": "13.2.2",
    "react-redux": "^8.0.5",
    "react-toastify": "^9.1.2",
    "redux": "^4.2.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-promise-middleware": "^6.1.3",
    "redux-saga": "^1.2.3",
    "redux-thunk": "^2.4.2",
    "reselect": "^4.1.8",
    "styled-components": "^5.3.9",
    "swr": "^2.1.3",
    "uuid": "^9.0.0"
  },
```

**Comment by amit13091992** [comment]
still getting this error. Any updates for the fix?

    ```
"expo": "^48.0.0",
    "expo-av": "^13.10.3",
    "expo-camera": "~13.2.1",
    "expo-constants": "^14.4.2",
    "expo-face-detector": "~12.1.1",
    "expo-modules-core": "^1.11.8"
```
