### ISSUE TITLE
expo-dev-menu@1.2.1 vendors breaking with newrelic-react-native-agent@0.0.2

### ISSUE THREAD

**Issue by 90dy** [expo/expo#18681]
### Summary

Vendored packages classes inscide expo-dev-menu are duplicated when using newrelic-react-native-agent.

Is using vendored versions of react-native-{gesture-handler,reanimated,safe-area-context} a good practice ?

PS: Idk how to contact NewRelic developers neither submit them an issue, their repository github.com/newrelic/newrelic-react-native-agent is private

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

eas-cli@0.60.0
expo-dev-client@1.2.1
expo-updates@0.14.4
newrelic-react-native-agent@0.0.2

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.volta/tools/image/node/16.15.1/bin/node
      Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
      npm: 8.11.0 - ~/.volta/tools/image/node/16.15.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: managed

### Reproducible demo

```
git clone https://github.com/90dy/issue-expo-newrelic
cd issue-expo-newrelic
yarn
eas build --profile preview --platform android --local
```
Working if you remove `newrelic-react-native-agent` plugin in app.json

### Stacktrace (if a crash is involved)

<details>
  <summary>Show more</summary>

[...]
[RUN_GRADLEW] > Task :app:transformClassesWithNewrelicTransformForDebug
[RUN_GRADLEW] > Task :app:dexBuilderDebug
[RUN_GRADLEW] > Task :expo-dev-menu-interface:mergeDebugNativeLibs NO-SOURCE
[RUN_GRADLEW] > Task :app:mergeExtDexDebug
[RUN_GRADLEW] > Task :expo-dev-menu-interface:copyDebugJniLibsProjectOnly
[RUN_GRADLEW] > Task :app:mergeLibDexDebug
[RUN_GRADLEW] > Task :expo-error-recovery:mergeDebugJniLibFolders
[RUN_GRADLEW] > Task :expo-error-recovery:mergeDebugNativeLibs NO-SOURCE
[RUN_GRADLEW] > Task :expo-error-recovery:copyDebugJniLibsProjectOnly
[RUN_GRADLEW] > Task :expo-file-system:mergeDebugJniLibFolders
[RUN_GRADLEW] > Task :expo-file-system:mergeDebugNativeLibs NO-SOURCE
[RUN_GRADLEW] > Task :expo-file-system:copyDebugJniLibsProjectOnly
[RUN_GRADLEW] > Task :expo-font:mergeDebugJniLibFolders
[RUN_GRADLEW] > Task :expo-font:mergeDebugNativeLibs NO-SOURCE
[RUN_GRADLEW] > Task :expo-font:copyDebugJniLibsProjectOnly
[RUN_GRADLEW] > Task :expo-json-utils:mergeDebugJniLibFolders
[RUN_GRADLEW] > Task :expo-json-utils:mergeDebugNativeLibs NO-SOURCE
[RUN_GRADLEW] > Task :expo-json-utils:copyDebugJniLibsProjectOnly
[RUN_GRADLEW] > Task :expo-dev-menu:copyDebugJniLibsProjectOnly
[RUN_GRADLEW] > Task :expo-keep-awake:mergeDebugJniLibFolders
[RUN_GRADLEW] > Task :expo-keep-awake:mergeDebugNativeLibs
[RUN_GRADLEW] NO-SOURCE
[RUN_GRADLEW] > Task :expo-keep-awake:copyDebugJniLibsProjectOnly
[RUN_GRADLEW] > Task :expo-manifests:mergeDebugJniLibFolders
[RUN_GRADLEW] > Task :expo-manifests:mergeDebugNativeLibs NO-SOURCE
[RUN_GRADLEW] > Task :expo-modules-core:createNativeDepsDirectories UP-TO-DATE
[RUN_GRADLEW] > Task :expo-manifests:copyDebugJniLibsProjectOnly
[RUN_GRADLEW] > Task :expo-modules-core:prepareHermes UP-TO-DATE
[RUN_GRADLEW] > Task :expo-modules-core:extractReactNativeAARRelease
[RUN_GRADLEW] > Task :expo-modules-core:downloadFolly
[RUN_GRADLEW] Download https://github.com/facebook/folly/archive/v2021.06.28.00.tar.gz
[RUN_GRADLEW] > Task :expo-modules-core:downloadDoubleConversion
[RUN_GRADLEW] Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz
[RUN_GRADLEW] > Task :expo-modules-core:extractReactNativeAARDebug
[RUN_GRADLEW] > Task :expo-modules-core:prepareDoubleConversion
[RUN_GRADLEW] > Task :app:mergeProjectDexDebug FAILED
[RUN_GRADLEW] ERROR:/private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/5e7dbb4869e56e0e1a799a81f4a55a2e2fb653c6471f07002f1e3556a621f0e5_0.jar: D8: Type devmenu.com.swmansion.common.GestureHandlerStateManager is defined multiple times: /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/5e7dbb4869e56e0e1a799a81f4a55a2e2fb653c6471f07002f1e3556a621f0e5_0.jar:classes.dex, /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/abf280864f159d56a3b1d73b5fdeb59fa0211fd5a8a38181c24112cdd2d7a10a_0.jar:classes.dex
[RUN_GRADLEW] com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
[RUN_GRADLEW] Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
[RUN_GRADLEW] Type devmenu.com.swmansion.common.GestureHandlerStateManager is defined multiple times: /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/5e7dbb4869e56e0e1a799a81f4a55a2e2fb653c6471f07002f1e3556a621f0e5_0.jar:classes.dex, /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/abf280864f159d56a3b1d73b5fdeb59fa0211fd5a8a38181c24112cdd2d7a10a_0.jar:classes.dex
[RUN_GRADLEW]   at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
[RUN_GRADLEW]   at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
[RUN_GRADLEW]   at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:859)
[RUN_GRADLEW]   at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:805)
[RUN_GRADLEW]   at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
[RUN_GRADLEW]   at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
[RUN_GRADLEW]   at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
[RUN_GRADLEW]   at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
[RUN_GRADLEW]   at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
[RUN_GRADLEW]   at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
[RUN_GRADLEW]   at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
[RUN_GRADLEW]   at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
[RUN_GRADLEW]   at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[RUN_GRADLEW]   at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[RUN_GRADLEW]   at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[RUN_GRADLEW]   at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[RUN_GRADLEW]   at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[RUN_GRADLEW]   at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[RUN_GRADLEW]   at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[RUN_GRADLEW]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[RUN_GRADLEW]   at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
[RUN_GRADLEW]   at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
[RUN_GRADLEW]   at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
[RUN_GRADLEW]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[RUN_GRADLEW]   at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
[RUN_GRADLEW]   at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
[RUN_GRADLEW]   at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
[RUN_GRADLEW]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[RUN_GRADLEW]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[RUN_GRADLEW]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[RUN_GRADLEW]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[RUN_GRADLEW]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[RUN_GRADLEW]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[RUN_GRADLEW]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
[RUN_GRADLEW]   at java.base/java.lang.Thread.run(Thread.java:829)
[RUN_GRADLEW] Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/5e7dbb4869e56e0e1a799a81f4a55a2e2fb653c6471f07002f1e3556a621f0e5_0.jar:classes.dex
[RUN_GRADLEW]   at Version.fakeStackEntry(Version_3.1.51.java:0)
[RUN_GRADLEW]   at com.android.tools.r8.internal.oO0.a(SourceFile:68)
[RUN_GRADLEW]   at com.android.tools.r8.internal.oO0.a(SourceFile:28)
[RUN_GRADLEW]   at com.android.tools.r8.internal.oO0.a(SourceFile:27)
[RUN_GRADLEW]   at com.android.tools.r8.internal.oO0.b(SourceFile:3)
[RUN_GRADLEW]   at com.android.tools.r8.D8.run(D8.java:11)
[RUN_GRADLEW]   at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
[RUN_GRADLEW]   ... 33 more
[RUN_GRADLEW] Caused by: com.android.tools.r8.internal.b: Type devmenu.com.swmansion.common.GestureHandlerStateManager is defined multiple times: /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/5e7dbb4869e56e0e1a799a81f4a55a2e2fb653c6471f07002f1e3556a621f0e5_0.jar:classes.dex, /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/abf280864f159d56a3b1d73b5fdeb59fa0211fd5a8a38181c24112cdd2d7a10a_0.jar:classes.dex
[RUN_GRADLEW]   at com.android.tools.r8.internal.il1.a(SourceFile:14)
[RUN_GRADLEW]   at com.android.tools.r8.internal.il1.a(SourceFile:22)
[RUN_GRADLEW]   at com.android.tools.r8.internal.lf1.b(SourceFile:6)
[RUN_GRADLEW]   at com.android.tools.r8.internal.lf1.a(SourceFile:23)
[RUN_GRADLEW]   at com.android.tools.r8.internal.lf1.a(SourceFile:10)
[RUN_GRADLEW]   at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
[RUN_GRADLEW]   at com.android.tools.r8.internal.lf1.a(SourceFile:6)
[RUN_GRADLEW]   at com.android.tools.r8.graph.r2$a.f(SourceFile:4)
[RUN_GRADLEW]   at com.android.tools.r8.dex.b.a(SourceFile:96)
[RUN_GRADLEW]   at com.android.tools.r8.dex.b.a(SourceFile:21)
[RUN_GRADLEW]   at com.android.tools.r8.D8.a(D8.java:21)
[RUN_GRADLEW]   at com.android.tools.r8.D8.d(D8.java:11)
[RUN_GRADLEW]   at com.android.tools.r8.D8.b(D8.java:1)
[RUN_GRADLEW]   at com.android.tools.r8.internal.oO0.a(SourceFile:24)
[RUN_GRADLEW]   ... 36 more
[RUN_GRADLEW] > Task :expo-modules-core:downloadBoost
[RUN_GRADLEW] Download https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
[RUN_GRADLEW] > Task :expo-modules-core:prepareFolly
[RUN_GRADLEW] w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
[RUN_GRADLEW] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[RUN_GRADLEW] Please consult deprecation warnings for more details.
[RUN_GRADLEW] 361 actionable tasks: 361 executed
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:mergeProjectDexDebug'.
[RUN_GRADLEW] > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
[RUN_GRADLEW]    > There was a failure while executing work items
[RUN_GRADLEW]       > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
[RUN_GRADLEW]          > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
[RUN_GRADLEW]            Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
[RUN_GRADLEW]            Type devmenu.com.swmansion.common.GestureHandlerStateManager is defined multiple times: /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/5e7dbb4869e56e0e1a799a81f4a55a2e2fb653c6471f07002f1e3556a621f0e5_0.jar:classes.dex, /private/var/folders/_x/nmly3n_d43xd9j84qhnvdfxr0000gn/T/eas-build-local-nodejs/242dfbfa-b363-4c77-b713-573746bf4f44/build/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/abf280864f159d56a3b1d73b5fdeb59fa0211fd5a8a38181c24112cdd2d7a10a_0.jar:classes.dex
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 1m 45s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

Build failed
Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
    Error: npx exited with non-zero code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</details>

**Comment by tcdavis** [comment]
> Is using vendored versions of react-native-{gesture-handler,reanimated,safe-area-context} a good practice ?
It is unusual at least, but version the libraries allows us to avoid prescribing that you use precise versions of these libraries in your application.

Hopefully we can get in touch with the New Relic team and get this incompatibility addressed. Thank you for bringing it to our attention

**Comment by 90dy** [comment]
Hello @abomblabrom,
My workaround was to disable newrelic-react-native-agent for preview builds but enable it for release in app.config.json
```ts
export default (): ExpoConfig => ({
	plugins: [
   		...(buildProfile === 'preview' ? [] : ['newrelic-react-native-agent']),
	]	
})
```

**Comment by ndesai-newrelic** [comment]
@90dy we are open source now, you can add this issue on our repo.  https://github.com/newrelic/newrelic-react-native-agent
