### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by phatmann** [expo/expo#18685]
### Summary

The Updates migration documentation states:
> If you have any code that references Updates.releaseChannel from the expo-updates library, you’ll have to remove those. Currently, EAS Update does not expose the channel of a build. Instead, you can use environment variables.

But here is the documentation for Updates.channel :
> The channel name of the current build, if configured for use with EAS Update. Null otherwise.

It should say: "Not currently used".

### Link to the related docs page

https://docs.expo.dev/versions/v46.0.0/sdk/updates/#updateschannel

### Anything else?

When I try to Edit the page, I don't see the API content. So I am filing this bug report instead.

**Comment by jonsamp** [comment]
EAS update supports the `channel` property, while the Classic Updates service supports the `releaseChannel` property. This SDK doc is correct, since EAS Update _does_ support `Updates.channel`.
