### ISSUE TITLE
CommandError: "expo-app-loading" is added as a dependency in your project's package.json but it doesn't seem to be installed. Please run "yarn" or "npm install" to fix this issue.

### ISSUE THREAD

**Issue by Schot911** [expo/expo#18684]
### Summary

Hi! After installing expo-app-loading, the npm start command throws the following error: CommandError: "expo-app-loading" added as a dependency in package.the json of your project, but it doesn't seem to be installed. Please run "yarn" or "npm install" to fix this problem.
The latest version of React is native
Node version.JS: v18.7.0

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

expo-app-loading

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2
      expo: ~46.0.7 => 46.0.7
      react: ^18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: managed

### Reproducible demo

No

**Comment by tcdavis** [comment]
Creating a new project, installing expo-app-loading, and `npm start` started the project as expected for me.

**Comment by alelsantos** [comment]
it's don't work for me... someone have another tip ?

**Comment by gabrielprogramadorweb** [comment]
esse deu certo pra mim, acesse o link> https://www.codegrepper.com/code-examples/javascript/install+expo+app+loading

**Comment by ideree037** [comment]
i need fckin answer
