### ISSUE TITLE
FBAudienceNetwork 4.99.0 breaks iOS ExpoKit

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1868]
Facebook released a new version of FBAudienceNetwork yesterday with a bunch of breaking changes. Expo's ads module depends on the previous version, 4.28.1, but the dependency is listed as `~> 4.24`.

- [x] Short term solution-- pin the dependency to the older version.
- [ ] After that-- need to update our ads module to be compatible with 4.99.0.

Here's the [full changelog](https://developers.facebook.com/docs/audience-network/changelog-ios).

**Comment by terribleben** [comment]
Noting here that whenever we do update to be compatible with 4.99.0, this will be a breaking change to the Expo SDK as well (because it will remove the `title` and `subtitle` properties from our native ad callback in JS).

**Comment by terribleben** [comment]
## Solution for people who saw a build failure

I've pushed a new ExpoKit tag which pins our FBAudienceNetwork dependency to 4.28.1.

If you saw something like this: `Property ‘title’ not found on object of type ‘FBNativeAd *’` while trying to build ExpoKit, then follow these instructions--

1. Change your `Podfile` so that your `ExpoKit` tag points to `ios/2.6.5` instead of 2.6.4.
2. `pod install`
3. Try building again

Note that this will downgrade your FBAudienceNetwork version. If you run into issues during `pod install` then you might want to nuke `Pods` and `Podfile.lock` and try again.

**Comment by Daadler6** [comment]
@terribleben - Will this fix also fix solve the issue for those who are on older SDKs. Our production application was released today (using the fix mentioned in the last thread) on SDK 25. We are in the process of upgrading to SDK 26 and then onto SDK 27. Will this be fixed in those SDK as well?

**Comment by poptocrack** [comment]
Same question as @Daadler6 I'm on sdk 26 with expokit.

**Comment by MorganDream** [comment]
My case is where expokit tag is ios/2.3.3, how should fix this?

**Comment by MorganDream** [comment]
@Daadler6 @poptocrack As root reason is FBAudienceNetwork, I found I can fix this by modify the version of FBAudienceNetwork to fixed value in Podfile.lock. 4.28.1 is good for me.

**Comment by pencilcheck** [comment]
Ditto @MorganDream, if you have older expokit, just modify Podfile.lock directly and change the version to 4.28.1 for FBAudienceNetwork and nuke Pods folder and rerun `pod install` then it will start working.

**Comment by lordcatalien** [comment]
Worked for me. Thank you @terribleben.

**Comment by dariuszseweryn** [comment]
@terribleben Can we have also a new patch version of `ios/2.5.11`?

**Comment by sjchmiela** [comment]
The neweset version of ExpoKit supports FBAudienceNetwork 4.99.0. Happy programming!

**Comment by faustoct** [comment]
is the lastest expo sdk30.0.0? Upgraded and not working

**Comment by sjchmiela** [comment]
Hey @faustoct! Yes, the latest Expo SDK is 30.0.0. What do you mean by _not working_? Have you followed all the steps from [Upgrading Your App](https://blog.expo.io/expo-sdk-30-0-0-is-now-available-e64d8b1db2a7#bcb3)?

If you haven't fixed your problem yet, would you be willing to create a new issue with more issue details? 🙂

**Comment by faustoct** [comment]
Yes, it's working! Upgraded expo and it's working now.

**Comment by esamelson** [comment]
FYI -- to anyone who is using Expo SDK 27 or below and is still running into this issue, if you cannot upgrade to a newer SDK, you should be able to get around this issue by editing your `Podfile.lock` to pin the version to `4.28.1` and then re-running `pod install`.

**Comment by redreceipt** [comment]
> Ditto @MorganDream, if you have older expokit, just modify Podfile.lock directly and change the version to 4.28.1 for FBAudienceNetwork and nuke Pods folder and rerun `pod install` then it will start working.

I manually upgraded FBAudienceNetwork because I'm on SDK 26 and now I'm getting new build errors:

![Screen Shot 2019-04-18 at 3 15 22 PM](https://user-images.githubusercontent.com/2659478/56385385-eeea0100-61ec-11e9-838c-1f88246e851d.png)

**Comment by zamgill** [comment]
> FYI -- to anyone who is using Expo SDK 27 or below and is still running into this issue, if you cannot upgrade to a newer SDK, you should be able to get around this issue by editing your `Podfile.lock` to pin the version to `4.28.1` and then re-running `pod install`.

I tried doing that but i'm getting the following error when running "pod install" after:
![image](https://user-images.githubusercontent.com/22265437/56548163-643b3600-654d-11e9-98c7-bb3f56318951.png)

**Comment by redreceipt** [comment]
@zamgill paste in your `Podfile`

**Comment by zamgill** [comment]
@redreceipt I was able to figure this out by upgrade to Expo SDK 28 and then using a new version of FBAudience. Thanks!
