### ISSUE TITLE
"ITMS-90338: Non-public API usage" when submitting app with dev-client

### ISSUE THREAD

**Issue by enagorny** [expo/expo#18686]
### Summary

Following this guide [Installing app variants on the same device](https://docs.expo.dev/build-reference/variants/).
We are creating the development builds with the `development-client` but it get's rejected when uploading to testflight.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

    "expo-dev-client": "~1.2.1",
    "expo-updates": "~0.14.4",

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nodenv/versions/16.13.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - ~/.nodenv/versions/16.13.1/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.60.0
    Expo Workflow: managed

### Reproducible demo

eas.json `build` section

```
"build": {
    "preview": {
      "extends": "development",
      "developmentClient": true,
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "ios": {
        "simulator": true
      }
    },
    "development": {
      "env": {
        "APP_VARIANT": "development"
      },
      "android": {
        "buildType": "app-bundle"
      },
      "developmentClient": true,
      "channel": "develop"
    },
    "production": {
      "channel": "main",
      "env": {
        "APP_VARIANT": "production"
      }
    }
  },
```

app.config.js
```
const IS_DEV = process.env.APP_VARIANT === "development";

const config = {
  API_URL: undefined,
  ENABLED_HIDDEN_FEATURES: undefined,
  MAGIC_KEY: undefined,
};

if (process.env.APP_VARIANT === "production") {
  config.API_URL = "xxx";
  config.ENABLED_HIDDEN_FEATURES = false;
  config.MAGIC_KEY = "xxx";
} else if (process.env.APP_VARIANT === "development") {
  config.API_URL = process.env.API_URL ?? "yyyy";
  config.ENABLED_HIDDEN_FEATURES = true;
  config.MAGIC_KEY = "yyy";
}

export default {
...
ios: {
    config: {
      usesNonExemptEncryption: false,
    },
    bundleIdentifier: IS_DEV ? "com.hidden.dev" : "com.hidden",
    buildNumber: "34",
  },
...

```

**Comment by pehagg** [comment]
@enagorny `distribution` needs to be set to `store` for TestFlight. I had this exact same issue myself.

**Comment by tcdavis** [comment]
React Native uses a few private APIs in development mode, so you are only able to distribute release builds through TestFlight.  We're exploring how to enable this distribution model for development builds, but this is expected behavior.

**Comment by jbaxleyiii** [comment]
@tcdavis do you know if support for dev client on Testflight is in Expo's near term roadmap?
