### ISSUE TITLE
After Updating SDK 45 Or 46 i18n-js is not working 

### ISSUE THREAD

**Issue by Prabananth** [expo/expo#18695]
### Summary

I Have try to use expo Localization and i18n plugin. In i18n i am getting undefined value
`import i18n from 'i18n-js';
import en from '../../constants/language/en.json';
import ta from '../../constants/language/ta.json';

i18n.translations = {
  en,
  ta,
  hi,
  ka,
};
i18n.fallbacks = true;
`

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /Applications/MAMP/htdocs/squarenow-app-new/node_modules/.bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      expo-cli: 6.0.2

### Minimal reproducible example

import i18n from 'i18n-js';
import en from '../../constants/language/en.json';
import ta from '../../constants/language/ta.json';

i18n.translations = {
  en,
  ta,
  hi,
  ka,
};
i18n.fallbacks = true;

**Comment by amandeepmittal** [comment]
Hey @Prabananth,

In your project, what is the package version of `i18n-js` library? If it is above `4.x.x`, it seems the API has changed. Please read more about the API changes for the library in its docs here: https://www.npmjs.com/package/i18n-js/v/latest

**Comment by Prabananth** [comment]
Hi Amandeepmittal, 

you are right, i have used i18n-js  is 4.0.2. Thank you for your response. i will be check updated doc
