### ISSUE TITLE
[docs] Undocumented field "messageEnum" in Push Ticket response

### ISSUE THREAD

**Issue by pganster** [expo/expo#18694]
### Summary

Since roughly August 11th 2022, we noticed that calls started to fail, since we received an unknown property "messageEnum" in the push ticket response when calling `https://exp.host/--/api/v2/push/send`. 

The documentation does not mention this property at all. Searching in the web, unrelated issues also contain this field, as can be seen [here](https://www.freelancer.sg/projects/iphone-app-development/fix-push-notification-expo-project), [here](https://www.reddit.com/r/expo/comments/wmhjvu/does_expo_push_notification_works_on_real_device/) or [here](https://stackoverflow.com/q/73359765).

So what does this field represent? How should the new body be parsed?

### Link to the related docs page

https://docs.expo.dev/push-notifications/sending-notifications/#push-tickets

**Comment by christopherwalter** [comment]
@pganster sorry for the churn here. The messageEnum field is being included in the response accidentally and I'll put up a fix to remove it (along with a couple other fields that are also leaking). 

Out of curiosity, are you still seeing the correct values for the rest of the PushTicket fields? Is any other part of the response unexpected/corrupted?

**Comment by pganster** [comment]
Thanks. Is there a date we can expect the change to occur? We'd need to adapt the parsing logic again.

As we don't log the PushTicket fields, I can't for sure tell you if they are always correct. But except for the "messageEnum" field, nothing out of the ordinary appeared in our logs.
