### ISSUE TITLE
[docs] Keyboard.removeListener is deprecated

### ISSUE THREAD

**Issue by kollinmurphy** [expo/expo#18698]
### Summary

According to https://reactnative.dev/docs/keyboard#removelistener, the Keyboard.removeListener is deprecated. The React Native docs suggests "Use the remove() method on the event subscription returned by addListener()".

### Link to the related docs page

https://docs.expo.dev/versions/latest/react-native/keyboard

**Comment by amandeepmittal** [comment]
Hey @kollinmurphy, thanks for opening an issue about this. We'll update the docs soon.

**Comment by lucalves** [comment]
> 

Could I work on it? How can I include in the documentation that `Keyboard.removeListener` is deprecated?

**Comment by amandeepmittal** [comment]
Closing this since React Native docs (submodule) have been removed with #19287.
