### ISSUE TITLE
SDK 46 can't build when Hermes enabled (even with patch from #18518)

### ISSUE THREAD

**Issue by KrisLau** [expo/expo#18697]
### Summary

Exactly the same as https://github.com/expo/expo/issues/18473

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.7 => 46.0.7 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: ^0.69.3 => 0.69.4 
    npmGlobalPackages:
      expo-cli: 6.0.0
    Expo Workflow: bare
```

### Minimal reproducible example

https://github.com/expo/expo/issues/18473

**Comment by Albert-Gao** [comment]
not sure if it is the same error

![image](https://user-images.githubusercontent.com/18282328/185788810-0e3e7061-5e2c-4a00-a8bc-b73ffc110473.png)

build failed for custom dev client when hermes being enabled, cleaned the pod and start again has same error

**Comment by german2114** [comment]
This still happening for me even in expo@46.0.10

**Comment by KrisLau** [comment]
@german2114 It worked for me maybe check that you have the latest version of react native? I know previous versions of 0.69 has problems with Hermes but the latest 2 or 3 should work with it

**Comment by german2114** [comment]
@KrisLau I'm not using Hermes

**Comment by german2114** [comment]
@KrisLau This is the weird thing, all related issues happen using Hermes, but I'm not using it. Rn v. 0.69.3 and expo v 46.0.10
