### ISSUE TITLE
Stuck in iOS client when it cannot connect

### ISSUE THREAD

**Issue by lucfranken** [expo/expo#187]
While trying to work around #124: I encounter documentation issues, unclear instructions and get stuck in the app. I suppose some small text improvements make the whole process much more clear.

I made it step by step to be able to reproduce it. So it's a bit long but it describes I think quite some steps which a normal user experiences while working with the Expo XDE and the Client on iOS.

Expo XDE is running on LAN.
I removed my Expo app from iPad (to remove the active debugging because debugger is not running anymore).
I downloaded it again from the App store.

In the interface I see:

<img width="229" alt="schermafbeelding 2017-05-11 om 08 02 05" src="https://cloud.githubusercontent.com/assets/1609379/25934804/26df89d6-3620-11e7-891c-114846189151.png">

In the documentation I see: https://docs.expo.io/versions/v16.0.0/introduction/xde-tour.html#opening-on-a-device

Though it's called: "Opening on a device" I can only run the app on a simulator here.

I try to open this project on my iPad. On the home screen I cannot, so I go to Explore. That works but the name of the tab does not make real sense, I want to "Open" my own project, not "Explore" which indicates in my feeling: Browse around example apps.

I enter: exp://MYLOCALIP:19000 (This url should be visible in the url? You never have to type the localhost ip?)

I get: "There was a problem loading the experience". With 2 buttons: "Try Again" and "Show details".

I cannot get out of here. It should contain a link back to Expo home or instructions that you should shake the device?

I shake and click the button to get back to main menu.

I try the url:  MYLOCALIP:19000

Still I cannot get in.

I check the console of XDE, I see: 

> Error starting tunnel: Error: Error: failed to start tunnel

No idea what it means but I do a restart.

Now the url in the interface changes to:

exp://gn-itt.lucfranken.kitchen.exp.direct:80

That's not what I need, I need a local IP. After changing the setting to localhost and then back to LAN I get a correct IP shown. Now the example URL matches my local IP.

I had to add back: exp:// in front of it.

Now I can open the project after 3-4 times of pressing the url in the Explore screen. The first few times it did not load. Just showed the same: "There was a problem loading the experience" message.

After waiting for a while I get: "The request timed out" (Red screen).
In XDE console: "Building JavaScript bundle: finished in 148667ms."

I now refresh on the iPad. I know that's the trick but the interface does not make it clear.
Now I see my app.

All in all I think some improvements could be:

- Improve text on this screen: "There was a problem loading the experience" as it's not helpful and does not instruct to shake.
- Improve URL entry, where, with which protocol? Could be pre-filled?
- Check the error messages, the timeout for example is not needed. All things worked but still I need a manual refresh and I see a red screen before getting to my app.

**Comment by terribleben** [comment]
Thanks for the feedback. We've recently added a button to "go home" from the error screen, which should resolve your feedback about shake instructions. We're also adding QR codes to XDE which should make the process of opening a project a lot more straightforward.
