### ISSUE TITLE
fetch(file.uri) as blob has empty "type" on Android

### ISSUE THREAD

**Issue by rodrix** [expo/expo#1870]
### Environment

Environment:
  OS: Linux 4.13
  Node: 9.8.0
  Yarn: 1.7.0
  npm: 6.0.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: 28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

### Steps to Reproduce

Describe this issue is quite simple, after choose a file with Expo.DocumentPicker.getDocumentAsync({}) and fetch their result (file.uri), the fetch response blob dont bring the value of "type" property on Android. The property value is always is empty. 

1. const file = await Expo.DocumentPicker.getDocumentAsync({});
2. const response = await fetch(file.uri);
3. const blob = await response.blob();
4. console.log("DEBUG BOLADO >>>>>> ", response);

### Expected Behavior

I expect that response of fetch has the same behavior of IOS, bringing the "type" value of blob.

### Actual Behavior

Actually, only IOS is bringing the type property value, like "application/pdf", "image/jpeg", etc.

Samples:
android output: sample pdf file
19:46:49:   "_data": Object {
19:46:49:     "blobId": "8341b824-e0b5-47c0-be41-51742f5cfad0",
19:46:49:     "lastModified": 0,
19:46:49:     "name": "e27efa1d-b935-40ef-aad5-f54e5b806df3pdf",
19:46:49:     "offset": 0,
19:46:49:     "size": 3028,
19:46:49:     "type": "",
19:46:49:   },
19:46:49: }

ios output: sample pdf file
19:47:42:   "_data": Object {
19:47:42:     "blobId": "DED96FE2-1460-431F-AB7F-4B6E2412D076",
19:47:42:     "name": "AF74FC19-922D-4325-B8A2-0320B3D55739.pdf",
19:47:42:     "offset": 0,
19:47:42:     "size": 3028,
19:47:42:     "type": "application/pdf",
19:47:42:   },

### Reproducible Demo

https://snack.expo.io/r1fuYmyZ7

**Comment by satya164** [comment]
The `type` of the file is inferred from the file extension in the name. Unless the file name contains an extension, it's not possible to infer the mime type. In the example you provided, the file name doesn't contain the extension on Android while it does in iOS. So we can't do much here except fixing expo document picker to preserve file extension.

If you know the mimetype, you can also create a new blob and set the type: `new Blob([blob], {type: "application/pdf"})`

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. It sounds like this issue has been resolved. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
