### ISSUE TITLE
Expo Android Target API level 30 change to level 31

### ISSUE THREAD

**Issue by GwFreak01** [expo/expo#18707]
### Summary

I am on SDK45

Trying to manually upload the first aab to Google Play.
Using `expo build:android` and it uses EAS build servers.

Running into this error
`Your app currently targets API level 30 and must target at least API level 31 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 31. [Learn More](https://developer.android.com/google/play/requirements/target-sdk)`

Not sure how to force the targetSdkVersion

### What platform(s) does this occur on?

Android

### Environment

`expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.1
    Expo Workflow: managed
`

### Minimal reproducible example

Create new app. try to build first android aab and upload for first time.

**Comment by rohiththummanapally** [comment]
hi , i am on SDK 44 
i have built the .aab file by command "eas build --platform android" using eas build
when trying to upload the .aab file to play store for new app, got the same error(currently Targets API level 30 and must atleast Target API level 31) , has any one resolved the issue?

**Comment by rohiththummanapally** [comment]
hi , i have resolved the issue by upgrading the expo sdk to 45
