### ISSUE TITLE
 expo-sqlite@10.3.0 depend on @databases/expo@5.0.0 , but not compatible?

### ISSUE THREAD

**Issue by damgaarderik** [expo/expo#18706]
### Summary

when I try to build an APK with EAS build the application crashes or stall.
It seems that the build that failed uses a package @databases/expo, but when I try to add @databases/expo then 
I get the following failure : 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: 5elementapp@1.0.0
npm ERR! Found: expo-sqlite@10.3.0
npm ERR! node_modules/expo-sqlite
npm ERR! expo-sqlite@“~10.3.0” from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer expo-sqlite@"^8.0.0" from @databases/expo@5.0.0
npm ERR! node_modules/@databases/expo
npm ERR! @databases/expo@“^5.0.0” from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.5.5 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2
      expo: ^46.0.0 => 46.0.7
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: bare

### Minimal reproducible example

npx expo install @databases/expo

**Comment by brentvatne** [comment]
we do not maintain `@databases/expo`, this isn't the correct repository to report this. `expo-sqlite` does not depend on it, it's the other way around.
