### ISSUE TITLE
App is crashing while building expo on production

### ISSUE THREAD

**Issue by Arhamshahzad118** [expo/expo#18719]
### Summary

App started crashing from yesterday out of nowhere. No one from our team did any code changes at all. 
Only not working in UAE, working fine in Pakistan. 
Even expo go isn't working in UAE

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.20.0 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 6.14.17 - /opt/homebrew/bin/npm
      Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^8.3.0 => 8.3.0 
      expo: ^38.0.11 => 38.0.11 
      react: ~16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: ~0.62.3 => 0.62.3 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: bare

### Reproducible demo

{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "postinstall": "npx jetify",
    "reactide-server": "webpack-dev-server --config reactide.config.js --mode development --hot",
    "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
  },
  "dependencies": {
    "@notifee/react-native": "^5.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.2",
    "@react-native-firebase/analytics": "^10.4.0",
    "@react-native-firebase/app": "^10.4.0",
    "@react-native-firebase/messaging": "^10.4.0",
    "@react-navigation/core": "^3.7.6",
    "@react-navigation/native": "^3.8.0",
    "@rneui/base": "^4.0.0-rc.4",
    "@rneui/themed": "^4.0.0-rc.4",
    "@sentry/react-native": "^3.3.5",
    "@stripe/stripe-react-native": "^0.2.4",
    "axios": "^0.21.4",
    "expo": "^38.0.11",
    "expo-apple-authentication": "~2.2.1",
    "expo-asset": "^8.1.7",
    "expo-av": "~8.2.1",
    "expo-calendar": "~8.2.2",
    "expo-cli": "^5.2.0",
    "expo-constants": "~9.1.1",
    "expo-facebook": "~8.2.1",
    "expo-file-system": "^9.3.0",
    "expo-font": "^8.2.1",
    "expo-google-sign-in": "~8.2.1",
    "expo-image-picker": "~8.3.0",
    "expo-linear-gradient": "~8.2.1",
    "expo-location": "~8.2.0",
    "expo-modules-core": "^0.2.0",
    "expo-permissions": "~9.0.1",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.0",
    "expo-store-review": "^2.1.2",
    "expo-updates": "^0.2.14",
    "expo-web-browser": "~8.3.1",
    "lodash.debounce": "^4.0.8",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.33",
    "qs": "^6.7.0",
    "react": "~16.11.0",
    "react-dom": "16.11.0",
    "react-native": "~0.62.3",
    "react-native-calendars": "^1.204.0",
    "react-native-date-picker": "^4.2.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-dropdown-picker": "^5.4.2",
    "react-native-elements": "^3.4.2",
    "react-native-fast-image": "^8.5.11",
    "react-native-geocoding": "^0.3.0",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-image-slider-box": "^1.0.5",
    "react-native-image-zoom-viewer": "^2.2.26",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-lightbox": "^0.8.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "~0.27.1",
    "react-native-push-notification-popup": "^1.3.0",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "^3.4.1",
    "react-native-safe-area-view": "^0.14.9",
    "react-native-screens": "~2.9.0",
    "react-native-skeleton-placeholder": "^5.0.0",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-tabs-section-list": "^1.0.1",
    "react-native-tracking-transparency": "^0.1.1",
    "react-native-unimodules": "~0.10.1",
    "react-native-version-check": "^3.3.1",
    "react-native-version-number": "^0.3.6",
    "react-native-web": "^0.11.7",
    "react-native-webview": "^11.0.0",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.0",
    "reactide-config": "^1.0.2",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.2.0"
  },
  "devDependencies": {
    "@babel/cli": "7.16.0",
    "@babel/core": "7.12.10",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0-beta.0",
    "@babel/preset-typescript": "^7.16.7",
    "babel-jest": "~25.2.6",
    "babel-loader": "^8.0.0-beta.0",
    "babel-preset-expo": "^8.3.0",
    "css-loader": "^2.1.1",
    "file-loader": "^4.0.0",
    "html-webpack-plugin": "^3.2.0",
    "jest": "~25.2.6",
    "jetifier": "^1.6.8",
    "node-sass": "^7.0.1",
    "react-test-renderer": "~16.11.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "url-loader": "^2.0.0",
    "webpack": "^4.33.0",
    "webpack-cli": "^3.3.2",
    "webpack-dev-server": "^3.7.0"
  },
  "private": true,
  "name": "shugah",
  "version": "1.0.0"
}

### Stacktrace (if a crash is involved)

Our app was working fine and still working fine in Pakistan but Ios and android is getting crashed for most of the users in UAE for some reason. It shows splash screen and crashes and ios and playstore isn't showing any crash report. Other than that Expo go also isn't working in UAE and working fine in Pakistan. Kindly look into it asap

**Comment by esamelson** [comment]
Hi there @Arhamshahzad118 -- I'm copying our email response here in case other people come across this issue looking for guidance, but please follow up with us via email if you have further questions.

---

Thank you for reaching out to us -- we understand it must be frustrating if a local network provider decides to block access to certain websites.

While this is unfortunately completely outside of our control, there are a couple of tips we can recommend that might help you mitigate this situation for your users:

- If your app is configured for OTA Updates, disable those. This way, no attempt should be made at app start to reach any Expo server.
- Etisalat seems to have a form where you can request a website to be unblocked: https://www.etisalat.ae/en/generic/contactus-forms/web-block-unblockn.jsp. I suggest you try contacting them that way with this request.
- For connecting to the Expo servers using local development, consider any of a number of methods to route your internet traffic differently. We unfortunately cannot provide much more specific guidance on this.
