### ISSUE TITLE
[docs] Examples of .npmrc files are commenting out necessary lines

### ISSUE THREAD

**Issue by Jorundur** [expo/expo#18713]
### Summary

The page says e.g. 

> 
> When EAS detects that the NPM_TOKEN environment variable is available during a build, it automatically creates the following .npmrc:
> ```
> # registry.npmjs.org/:_authToken=${NPM_TOKEN}
> registry=https://registry.npmjs.org/
> ```

But the top line should be `//registry.npmjs.org/:_authToken=${NPM_TOKEN}`, not
`# registry.npmjs.org/:_authToken=${NPM_TOKEN}`.

`#` comments out a line, `//` just means it'll use the default protocol of the page: https://stackoverflow.com/a/53281483/4206125

This also needs to be fixed in another example further down the page.

I ran into this because if I used the commented out version (I had to manually write the npmrc since the default registry wasn't used), then I'd get a 401 when trying to install packages using EAS build.

### Link to the related docs page

https://docs.expo.dev/build-reference/private-npm-packages/

**Comment by KiwiKilian** [comment]
Was hitting the same error, as the docs suggest the comment might be necessary to insert secretes with `${}`. Seems to be inserted by accident in this commit: https://github.com/expo/expo/pull/17467/files#diff-08c38d07e63d0af35cf2fed1609bdada9340975ab52708a0c0ed42376a7ad505R38.

**Comment by Jorundur** [comment]
@KiwiKilian yeah you're right, the `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` line is necessary to insert secret. But to clarify, `//` is does not indicate a comment, this syntax just means the following (from that SO answer I posted above):

>This is a [Protocol-relative URL](https://en.wikipedia.org/wiki/URL#prurl), meaning an URL that will take the protocol automatically from the current page (you can actually type //google.com in the browser, and it should take you to https://google.com)

**Comment by amandeepmittal** [comment]
Thank you @Jorundur, for bringing this to our attention. It has been fixed now 👍
