### ISSUE TITLE
Expo 46 FlashList RTL bug

### ISSUE THREAD

**Issue by Stevemoretz** [expo/expo#18710]
### Summary

Guys since now you support FlashList you better know that it needs serious help for its RTL :
https://github.com/Shopify/flash-list/issues/544

I've reported the issue there and been a long time, please give special notice to this issue and help it proceed.

FlatList RTL doesn't work well on android since SDK 45 https://github.com/facebook/react-native/issues/34314 repro: https://snack.expo.dev/@stevemoretz/ltr-rtl, the only hope is FlashList which that doesn't work either but seems easier to fix I'd suppose.

There are MILLIONS of RTL users I don't really get how these issues are ignored this much.

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.15.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.02.14.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29, 30, 32
        Build Tools: 28.0.3, 29.0.2, 29.0.3
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.56.0
      expo-cli: 6.0.1
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@stevemoretz/flashlist-rtl-bug

**Comment by brentvatne** [comment]
hi there! sorry to hear that. i imagine the maintainers will resolve this soon. we don't have the resources to work on that library, we just help to distribute it through expo go and make it available in snack.

**Comment by Stevemoretz** [comment]
> hi there! sorry to hear that. i imagine the maintainers will resolve this soon. we don't have the resources to work on that library, we just help to distribute it through expo go and make it available in snack.

Thanks for getting back to me I really appreciate it, and I completely understand I just wanted to inform you.
