### ISSUE TITLE
[IOS] Expo-camera Component when opened on IOS standalone App remains with black screen

### ISSUE THREAD

**Issue by Artem99-debug** [expo/expo#18711]
### Summary

Expected Behavior : In IOS StandAlone app making expo-camera preview not black screen.

some things to add: I have in app.json the infoPlist the NSCameraUsageDescription-
I ask the user to allow the use of camera, when this pops the screen is blank and when he accepts the preview remains black
When testing this on Dev ( expo app ) it works perfectly 
When testing on expo build and open the app on expo app it works too
when i eas build and sent do app store connect , in testflight or in standalone app it doesnt work!

expo-camera version :    "expo-camera": "~12.2.0",

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^45.0.0 => 45.0.0
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare

### Minimal reproducible example

`return (
        <View style={styles.container}>
            <ModalSucessSaveFotografia visible={sucessModalFotografia.visible} onConfirm={sucessModalFotografia.confirmModal} onClosing={closeModalSucessFotografia}></ModalSucessSaveFotografia>
            <ModalError onConfirm={errorModal.confirmModal} visible={errorModal.visible} body={errorModal.body} onClosing={closeModal}></ModalError>
            {previewVisible && capturedImage ? (
                <CameraPreview confirmarFotografia={confirmarFotografia} retakePicture={retakePicture} photo={capturedImage} />
            ) : (
                <Camera style={styles.camera}
                    type={type}
                    ref={camera}
                    flashMode={'auto'}
                    whiteBalance={"sunny"}

                >
                    <View style={{ flex: 1, flexDirection: 'column', justifyContent: 'flex-end' }} >
                        <LinearGradient style={[{ padding: 15, elevation: 10, paddingBottom: 25 }]} colors={['transparent', 'black']}>
                            <View style={{ flexDirection: 'row', justifyContent: 'space-between' }} >
                                <TouchableOpacity onPress={voltarEcraAnterior} style={[styles.previewButtons, styles.circle]}>
                                    <Icon name="icon-cross" style={styles.iconButtonsCamera} size={40}></Icon>
                                </TouchableOpacity>
                                <TouchableOpacity onPress={takePicture} style={[styles.previewButtons, styles.circle,]}>
                                    <Icon name="icon-scan" style={styles.iconButtonsCamera} size={40}></Icon>
                                </TouchableOpacity>
                            </View>
                        </LinearGradient>
                    </View>
                </Camera>
            )
            }
        </View >
    );`

**Comment by sokoya** [comment]
Hey man, are you able to fix this... I am having same issue on testflight, everything works fine on expo go.


> ### Summary
> 
> Expected Behavior : In IOS StandAlone app making expo-camera preview not black screen.
> 
> some things to add: I have in app.json the infoPlist the NSCameraUsageDescription- I ask the user to allow the use of camera, when this pops the screen is blank and when he accepts the preview remains black When testing this on Dev ( expo app ) it works perfectly When testing on expo build and open the app on expo app it works too when i eas build and sent do app store connect , in testflight or in standalone app it doesnt work!
> 
> expo-camera version : "expo-camera": "~12.2.0",
> ### What platform(s) does this occur on?
> 
> iOS
> ### Environment
> 
> expo-env-info 1.0.5 environment info: System: OS: Windows 10 10.0.19043 Binaries: Node: 14.18.0 - C:\Program Files\nodejs\node.EXE Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD npmPackages: expo: ^45.0.0 => 45.0.0 react: 17.0.2 => 17.0.2 react-dom: 17.0.2 => 17.0.2 react-native: 0.68.2 => 0.68.2 react-native-web: 0.17.7 => 0.17.7 Expo Workflow: bare
> ### Minimal reproducible example
> 
> `return ( {previewVisible && capturedImage ? ( ) : ( <Camera style={styles.camera} type={type} ref={camera} flashMode={'auto'} whiteBalance={"sunny"}
> 
> ```
>             >
>                 <View style={{ flex: 1, flexDirection: 'column', justifyContent: 'flex-end' }} >
>                     <LinearGradient style={[{ padding: 15, elevation: 10, paddingBottom: 25 }]} colors={['transparent', 'black']}>
>                         <View style={{ flexDirection: 'row', justifyContent: 'space-between' }} >
>                             <TouchableOpacity onPress={voltarEcraAnterior} style={[styles.previewButtons, styles.circle]}>
>                                 <Icon name="icon-cross" style={styles.iconButtonsCamera} size={40}></Icon>
>                             </TouchableOpacity>
>                             <TouchableOpacity onPress={takePicture} style={[styles.previewButtons, styles.circle,]}>
>                                 <Icon name="icon-scan" style={styles.iconButtonsCamera} size={40}></Icon>
>                             </TouchableOpacity>
>                         </View>
>                     </LinearGradient>
>                 </View>
>             </Camera>
>         )
>         }
>     </View >
> );`
> ```
