### ISSUE TITLE
Can't logout from website

### ISSUE THREAD

**Issue by earksiinni** [expo/expo#1872]
Sorry if this is the wrong place to post this, but I didn't know where else to raise it. My issue is very simple: there doesn't appear to be a logout button on https://expo.io. Yeah, I know I can delete my cookies, but it's a bit weird that you can't just have a logout button.

Having a logout button has become all the more important since the changes to the iOS client because I now have to manage multiple Expo accounts for different customers.

**Comment by brentvatne** [comment]
![](http://url.brentvatne.ca/wZOUn7.png)

**Comment by brentvatne** [comment]
fwiw this is pretty much the same as on github

![](http://url.brentvatne.ca/AGSpeO.png)
