### ISSUE TITLE
Unable to start expo app by npm run web

### ISSUE THREAD

**Issue by manastunga787** [expo/expo#18733]
### Summary

created expo app by
`npx create-expo-app hello`

started the web version
`npm run web`

app crashes in browser with following warning in browser console

```
index.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

### What platform(s) does this occur on?

Web

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2022.08.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.8 => 46.0.8 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

react and react-dom version mismatch

**Comment by manastunga787** [comment]
I re-created the project using yarn

`expo init hello  // that by default uses yarn`

then install following packages manually to avoid the issue

```
yarn add react-dom@18.0.0
yarn add react-native-web

```

**Comment by Kudo** [comment]
hi there! i tested the following steps and it works for me. maybe should you install react-native-web and react-dom through `npx expo install` as the prompt when your first time to run `npx run web`

![Screen Shot 2022-08-22 at 8 32 11 PM](https://user-images.githubusercontent.com/46429/185921991-a943f040-fbb9-4294-9ac6-b8a82f0798aa.png)


my steps
```sh
$ npx create-expo-app hello
$ cd hello
$ npx expo install react-native-web@~0.18.7 react-dom@18.0.0 @expo/webpack-config@^0.17.0
$ npm run web
```

if it doesn't work for you, please try to create a github repo to a minimal reproducible example for us to further investigation. thanks!
