### ISSUE TITLE
expo-av Video resizeMode doesn't work

### ISSUE THREAD

**Issue by loveyoubaby5120** [expo/expo#18739]
### Summary

Video is always displayed on the far left
![image](https://user-images.githubusercontent.com/11256291/185850825-01a2695d-e768-4d43-8dc4-406cb68ed864.png)

### What platform(s) does this occur on?

Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/pankai/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.9 => 0.3.9
      @expo/webpack-config: ^0.17.0 => 0.17.2
      expo: ^46.0.0 => 46.0.8
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: bare

### Minimal reproducible example

```

      <View
        css={`
          width: 100%;
          height: 100%;
        `}
      >
        <Video
          source={{ uri: cachedURL }}
          isMuted={muted}
          resizeMode={isMobile ? ResizeMode.COVER : ResizeMode.CONTAIN}
          shouldPlay={true}
          isLooping={true}
          css={`
            width: 100%;
            height: 100%;
          `}
        />
      </View>
```

**Comment by jmatsushita** [comment]
I'm seeing the same error on web. In fact it's also reproducible with the Snack linked from the docs https://docs.expo.dev/versions/latest/sdk/video/#usage 
<img width="1307" alt="image" src="https://github.com/expo/expo/assets/356097/59e34ca0-dfad-4cf2-abef-410661354b57">

As shown in the screenshot, when selecting the `Web` preview, the video is cropped. Changing `ResizeMode.CONTAIN` to other mode doesn't do anything.

**Comment by SwanHub** [comment]
I'm likewise running into this issue. `ResiveMode.CONTAIN` seems to have no effect on `Web`. 

@keyp-dev @jmatsushita any hacky fixes found?

**Comment by ollyde** [comment]
@SwanHub anyone figure this out?
