### ISSUE TITLE
Camera indicator light remains on even when Camera is unmounted

### ISSUE THREAD

**Issue by raazatul7** [expo/expo#18746]
### Summary

I am using  `"expo-barcode-scanner": "~11.2.0",`
In iOS the green camera indicator light turns on when I open the scanner and it remains on until I kill the app from the background, even after switching bottom tabs it still persists.

### What platform(s) does this occur on?

iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.3.0 => 8.3.0 
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-navigation: ^4.1.1 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Minimal reproducible example

Install expo-barcode-scanner
Create build for dev environment for iOS
Open scanner and return back/switch tabs or screen
The green light doesn't go off.

**Comment by stefan-schweiger** [comment]
I was just going to create an issue for the same thing. For me it works if I unmount the component in iOS, but for Android it just stays active forever. See this snack: https://snack.expo.dev/@stefan-5gpay/basic-barcodescanner-usage

After the first scan it the camera indicator disappears on iOS after a few seconds, but it stays active forever on Android.

@raazatul7 can you maybe confirm this behavior with my snack?

**Comment by stefan-schweiger** [comment]
@raazatul7 btw for navigational stuff, what I do is I listen on the blur event of the navigator and then set some state to false in which case the `<BarcodeScanner />` does not get rendered anymore just like in the snack. But again this only works in iOS for me.

**Comment by raazatul7** [comment]
> @raazatul7 btw for navigation related stuff, what I do is I listen on the blur event of the navigator and then set some state in my component to false in which case the `<BarcodeScanner />` does not get rendered anymore just like in the snack. But again this only works in iOS for me.

I have used the same code to unmount the scanner and I worked, thanks dude!
It seems we need to cover the  `<BarcodeScanner />` in a condition to unmount.

**Comment by BLemine** [comment]
This is a bug related to navigations, As mentioned in the official documentation of **expo-barcode-scanner**, you need to unmount the component, so for example you can add a condition render on <BarCodeScanner ../> component with **useIsFocus** from react navigation
