### ISSUE TITLE
Objects and Arrays console.log in terminal are on one line

### ISSUE THREAD

**Issue by TomRoberto** [expo/expo#18757]
### Summary

When I console.log objects or arrays in my terminal in my expo projects, there is a new behavior :

- There is this LOG keyword at the beginning of the line, which is nice
![](https://user-images.githubusercontent.com/81251848/185944156-7aea56fc-d0dd-4b5f-b538-605c16227db9.png)
- Objects and Arrays are displayed in one single line , which is not easily readable especially for huge objects with many keys

![](https://user-images.githubusercontent.com/81251848/185944809-aa447274-0fa0-4488-9574-de5ca1babf06.png)

Is there a way to have objects' console.log back like this ?

```js
{
  name: "tom",
  age: 45
}
```

### What platform(s) does this occur on?

Android, iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/Desktop/SandBox/teamParents/teamParents-front/node_modules/.bin/yarn
      npm: 8.3.2 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.7 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Minimal reproducible example

Simply create a new Expo project with the latest version of expo CLI, launch it with npx expo satart or yarn start and console.log an object or an array.

**Comment by maxizhukov** [comment]
Same here after updating from v45 to v46

**Comment by maxizhukov** [comment]
And I started to see also weird lo
<img width="1490" alt="Screenshot 2022-08-23 at 23 05 04" src="https://user-images.githubusercontent.com/63158421/186265711-6ee03b01-a79b-444b-b94e-c4f102bb77c6.png">
gs like this:

**Comment by brentvatne** [comment]
this is expected behavior with the [new local CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421) - this is the default formatting for a json object when you use `JSON.stringify` and we no longer automatically "prettify" it.

you could use something like [json-beautify](https://www.npmjs.com/package/json-beautify) when logging, or `console.log(JSON.stringify(obj, null, 2))` is another common way of doing this

result:

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/90494/187000560-32a0664a-c0d6-4841-9352-68127a6c7f6c.png">

@maxizhukov - create a new issue with a reproducible example if you believe you have found a bug, thanks!
