### ISSUE TITLE
SDK 46 is always RTL on iOS16 beta

### ISSUE THREAD

**Issue by elie-chaaban** [expo/expo#18753]
### Summary

I have an app with expo sdk 45 and my phone is using iOS16 beta and all is good

i switched to sdk46 and everything now is RTL

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      @expo/metro-config: ^0.3.18 => 0.3.18
      expo: ^46.0.0 => 46.0.8
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@eliech/brave-kiwi

**Comment by elie-chaaban** [comment]
The app is still working on old iOS even with sdk 46. But not on iOS 16beta

**Comment by elie-chaaban** [comment]
![image](https://user-images.githubusercontent.com/29852821/185932718-be83b57e-c632-4b4c-8ddf-605749559c14.jpeg)

![image](https://user-images.githubusercontent.com/29852821/185932751-85640bc8-40ab-424b-86e0-172eb6b9c59b.jpeg)


It should be like this

**Comment by elie-chaaban** [comment]
![image](https://user-images.githubusercontent.com/29852821/185933101-14f08ba3-1d00-44eb-80a8-e9972cfa0fb0.png)

![image](https://user-images.githubusercontent.com/29852821/185933114-3582d6c8-3a91-40eb-93af-57061e3877ed.jpeg)

And that's how it looks on my device

**Comment by elie-chaaban** [comment]
![image](https://user-images.githubusercontent.com/29852821/185933528-90082c3e-1fa9-4da2-8c8d-2a1a2e372677.png)

![image](https://user-images.githubusercontent.com/29852821/185933541-306612ee-661f-4268-9be5-3ed9736cdb44.jpeg)

**Comment by SaleemMainiGamma** [comment]
@elie-chaaban 
Hi elie, I have same as this issue, how did you solve it?
