### ISSUE TITLE
[docs] Build fails if eas.json is missing distribution option

### ISSUE THREAD

**Issue by arvinio** [expo/expo#18752]
### Summary

EAS build on iOS fails when the option `distribution` is not specified in `eas.json`. This goes against the documentation which shows [an example](https://docs.expo.dev/build/eas-json/#production-builds) of a minimal production build. Works when specifying `distribution`. Android build works regardless.

Build fails on step `Creating new worker instance` with error:

```
Worker configuration failed.
Please try again later. If the problem persists, please report the issue.

Build failed: Internal Server Error.
Please try again later. If the problem persists, please report the issue.
````

My `eas.json` before the fix:
```
"prod": {
      "ios": {
        "releaseChannel": "prod-ios"
      },
      "android": {
        "releaseChannel": "prod-android",
        "buildType": "app-bundle"
      }
    }
``` 

My `eas.json` after the fix:

```
"prod": {
      "distribution": "store",
      "ios": {
        "releaseChannel": "prod-ios"
      },
      "android": {
        "releaseChannel": "prod-android",
        "buildType": "app-bundle"
      }
    }
``` 

### Link to the related docs page

https://docs.expo.dev/build/eas-json/#production-builds

**Comment by brentvatne** [comment]
hi there! it's likely you ran into some intermittent infrastructure issues. this field is not required, it will default to "store" if not provided. if the issue persists, share a link to your build page and any other information that you can, thanks!
