### ISSUE TITLE
How to solve your app includes non compliant sdk version 

### ISSUE THREAD

**Issue by belt-basya** [expo/expo#18755]
### Summary

Hello, I am not using Expo-analytics in my project; I am using SDK 44. I am now receiving the following error message

![image](https://user-images.githubusercontent.com/62102591/185940995-17388867-47d0-45a6-b619-406d417ce412.png)

Is there a way to solve this without updating or downgrading the SDK version?

### What platform(s) does this occur on?

Android, iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.17.4 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
    npmPackages:
      babel-preset-expo: ^9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.5 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: ^0.17.5 => 0.17.5 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

npm notice 
npm notice New minor version of npm available! 8.3.0 -> 8.18.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.18.0
npm notice Run npm install -g npm@8.18.0 to update!
npm notice 
```

### Minimal reproducible example

Screenshot from `package.json`

![image](https://user-images.githubusercontent.com/62102591/185942294-142f07f6-fcc4-4cc0-a0b0-21c2ebed0609.png)

**Comment by andreinegrea14** [comment]
@belt-basya How did you fixed it? Upgraded to SDK 46 and seems that the error is still there.

**Comment by vilocity-brian** [comment]
@belt-basya I also would like to know how you solved this

**Comment by ttoonn112** [comment]
Also found this problem. Is this can be solved?

**Comment by Akhundoff** [comment]
Has anyone been able to solve this?

**Comment by rxvinicius** [comment]
Same problem here, did anyone solve this??
