### ISSUE TITLE
EAS Build Failed

### ISSUE THREAD

**Issue by KeaganStevens** [expo/expo#18750]
### Summary

I'm having  trouble building my app for android ( haven't tried iOS though ). 
<details>
<summary>Run Gradlew Log</summary>
<br>

>[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/node_modules/expo-updates/android/build.gradle' line: 107
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':expo-updates'.
[stderr] > S
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] 2: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':expo'.
[stderr] > compileSdkVersion is not specified. Please add it to build.gradle
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] * Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 executed
Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
[stderr] BUILD FAILED in 2m 11s
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
</details>

Seeing this
`Project with path ':expo-updates-interface' could not be found in project ':expo-updates'.`

I tried 
`expo install expo-updates-interface`
and rebuild again
<details>
<summary>New Run Gradlew Log</summary>
<br>

>[stderr] Note: Recompile with -Xlint:deprecation for details.
> Task :expo-splash-screen:compileReleaseKotlin
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenReactActivityLifecycleListener.kt: (17, 50): Parameter 'activityContext' is never used
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenReactActivityLifecycleListener.kt: (35, 66): 'toLowerCase(): String' is deprecated. Use lowercase() instead.
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenViewController.kt: (20, 25): 'constructor Handler()' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenViewController.kt: (41, 5): Parameter 'failureCallback' is never used
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreenStatusBar.kt: (23, 27): 'replaceSystemWindowInsets(Int, Int, Int, Int): WindowInsets' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreenStatusBar.kt: (24, 29): 'getter for systemWindowInsetLeft: Int' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreenStatusBar.kt: (26, 29): 'getter for systemWindowInsetRight: Int' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreenStatusBar.kt: (27, 29): 'getter for systemWindowInsetBottom: Int' is deprecated. Deprecated in Java
> Task :expo-splash-screen:javaPreCompileRelease
> Task :expo-splash-screen:compileReleaseJavaWithJavac
> Task :expo-splash-screen:bundleLibCompileToJarRelease
> Task :expo-sqlite:generateReleaseBuildConfig
> Task :expo-sqlite:compileReleaseKotlin
w: /home/expo/workingdir/build/node_modules/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt: (31, 63): Unchecked cast: Any to ArrayList<Any?>
> Task :expo-sqlite:javaPreCompileRelease
> Task :expo-sqlite:compileReleaseJavaWithJavac
> Task :expo-sqlite:bundleLibCompileToJarRelease
> Task :expo-structured-headers:generateReleaseBuildConfig
> Task :expo-structured-headers:compileReleaseKotlin
> Task :expo-structured-headers:javaPreCompileRelease
> Task :expo-structured-headers:compileReleaseJavaWithJavac
> Task :expo-structured-headers:bundleLibCompileToJarRelease
> Task :expo-updates:generateReleaseBuildConfig
> Task :expo-updates-interface:generateReleaseBuildConfig
> Task :expo-updates-interface:compileReleaseKotlin
> Task :expo-updates-interface:javaPreCompileRelease
> Task :expo-updates-interface:compileReleaseJavaWithJavac
> Task :expo-updates-interface:bundleLibCompileToJarRelease
> Task :expo-updates:kaptGenerateStubsReleaseKotlin
> Task :expo-updates:kaptReleaseKotlin
> Task :expo-updates:compileReleaseKotlin FAILED
[stderr] e: /home/expo/workingdir/build/node_modules/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt: (23, 1): Class 'UpdatesDevLauncherController' is not abstract and does not implement abstract member public abstract fun storedUpdateIdsWithConfiguration(p0: HashMap<String!, Any!>!, p1: Context!, p2: UpdatesInterface.QueryCallback!): Unit defined in expo.modules.updatesinterface.UpdatesInterface
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':expo-updates:compileReleaseKotlin'.
[stderr] > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
[stderr]    > Compilation error. See log for more details
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 7m 15s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 6 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
377 actionable tasks: 377 executed
Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
</details>

Building the apk was a success before adding expo-updates

I tried reinstalling node_modules to no avail.
I understand I'm probably missing something simple but I would appreciate it if someone points me in the right direction.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed

### Dependencies
```
"@hookform/resolvers": "^2.9.6",
"@react-native-async-storage/async-storage": "~1.17.3",
"@react-native-community/slider": "^4.2.1",
"@react-native-picker/picker": "2.4.0",
"@react-navigation/native": "^6.0.11",
"@react-navigation/native-stack": "^6.7.0",
"@types/d3": "^7.4.0",
"@types/d3-scale": "^4.0.2",
"@types/yup": "^0.29.14",
"axios": "^0.27.2",
"d3": "^7.6.1",
"d3-scale": "^4.0.2",
"date-fns": "^2.28.0",
"expo": "~45.0.0",
"expo-barcode-scanner": "~11.3.0",
"expo-secure-store": "~11.2.0",
"expo-splash-screen": "~0.15.1",
"expo-sqlite": "~10.2.0",
"expo-status-bar": "~1.3.0",
"expo-updates": "~0.13.4",
"lodash": "^4.17.21",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-hook-form": "^7.33.1",
"react-native": "0.68.2",
"react-native-error-boundary": "^1.1.15",
"react-native-gesture-handler": "~2.2.1",
"react-native-paper": "^4.12.2",
"react-native-paper-dropdown": "github:KeaganStevens/react-native-paper-dropdown",
"react-native-safe-area-context": "4.2.4",
"react-native-screens": "~3.11.1",
"react-native-svg": "12.3.0",
"react-native-web": "0.17.7",
"use-http": "^1.0.26",
"yup": "^0.32.11"
```

### Minimal reproducible example

See logs. There is only so much debugging I can do before I surpass my EAS build quota.

**Comment by imrelaszlo** [comment]
Same problem here. Error messages are the same. Can build if expo-updates package is not installed (but the project needs it, because I need the releaseChannel, az expo-constants does not handle it correctly).

Dependencies:

```
    "@expo/metro-config": "^0.3.19",
    "@expo/vector-icons": "^13.0.0",
    "@native-html/iframe-plugin": "1x",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.17.7",
    "@react-native-picker/picker": "2.4.0",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.1.1",
    "accordion-collapse-react-native": "^1.1.1",
    "axios": "^0.27.2",
    "axios-auth-refresh": "^3.3.1",
    "axios-cache-interceptor": "^0.10.6",
    "expo": "^45.0.0",
    "expo-constants": "~13.1.1",
    "expo-device": "~4.2.0",
    "expo-file-system": "~14.0.0",
    "expo-font": "~10.1.0",
    "expo-notifications": "~0.15.4",
    "expo-secure-store": "~11.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-svg-uri": "^1.3.1",
    "expo-web-browser": "~10.2.1",
    "html-entities": "^2.3.3",
    "i18next": "^21.8.14",
    "md5": "^2.3.0",
    "prop-types": "^15.8.1",
    "query-string": "^7.1.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-i18next": "^11.18.1",
    "react-native": "0.68.2",
    "react-native-collapsible": "^1.6.0",
    "react-native-flash-message": "^0.2.1",
    "react-native-form-validator": "^0.5.1",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-maps": "0.30.2",
    "react-native-maps-directions": "^1.8.0",
    "react-native-modal": "^13.0.0",
    "react-native-phone-input": "^1.3.2",
    "react-native-render-html": "5.1.1",
    "react-native-safe-area-context": "4.2.4",
    "react-native-shadow-2": "^6.0.3",
    "react-native-svg": "12.3.0",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1"
```

**Comment by brentvatne** [comment]
1. don't install expo-updates-interface in your project, that is installed automatically by expo-updates
2. run `expo doctor` and ensure your dependencies are correct
3. refer to https://docs.expo.dev/build-reference/troubleshooting/ for more guidance

**Comment by IggsGrey** [comment]
#19112
