### ISSUE TITLE
[expo-updates] iOS crash on production

### ISSUE THREAD

**Issue by thejoaov** [expo/expo#18758]
### Summary

iOS app crashes on production, this is the crashlytics error log:

**Fatal Exception: RCTFatalException: Could not get BatchedBridge, make sure your bundle is packaged correctly
Could not get BatchedBridge, make sure your bundle is packaged correctly**
```
Fatal Exception: RCTFatalException: Could not get BatchedBridge, make sure your bundle is packaged correctly
0  CoreFoundation                 0x92d1c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  GymTracker                     0x69a08 -[EXUpdatesAppController _emergencyLaunchWithFatalError:] + 427 (EXUpdatesAppController.m:427)
3  GymTracker                     0x7db4c -[EXUpdatesErrorRecovery _crash] + 222 (EXUpdatesErrorRecovery.m:222)
4  GymTracker                     0x7d200 -[EXUpdatesErrorRecovery _runNextTask] + 127 (EXUpdatesErrorRecovery.m:127)
5  libdispatch.dylib              0x63094 _dispatch_call_block_and_release
6  libdispatch.dylib              0x64094 _dispatch_client_callout
7  libdispatch.dylib              0x3f4a4 _dispatch_lane_serial_drain$VARIANT$armv81
8  libdispatch.dylib              0x3ff44 _dispatch_lane_invoke$VARIANT$armv81
9  libdispatch.dylib              0x498e0 _dispatch_workloop_worker_thread
10 libsystem_pthread.dylib        0x1e10 _pthread_wqthread
11 libsystem_pthread.dylib        0x193c start_wqthread
```

**Falha: com.google.firebase.crashlytics.ios.exception
0x0000000000000000**
```
Crashed: com.google.firebase.crashlytics.ios.exception
0  GymTracker                     0x16a414 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  GymTracker                     0x16a7f4 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  GymTracker                     0x160c14 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  GymTracker                     0x15b1a4 __FIRCLSExceptionRecord_block_invoke + 232 (FIRCLSException.mm:232)
4  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
5  libdispatch.dylib              0x46464 _dispatch_lane_barrier_sync_invoke_and_complete + 52
6  GymTracker                     0x159f84 FIRCLSExceptionRecord + 234 (FIRCLSException.mm:234)
7  GymTracker                     0x15ac4c FIRCLSExceptionRecordNSException + 126 (FIRCLSException.mm:126)
8  GymTracker                     0x159b84 FIRCLSTerminateHandler() + 398 (FIRCLSException.mm:398)
9  libc++abi.dylib                0x10274 std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x1021c std::terminate() + 60
11 libobjc.A.dylib                0x2846c objc::DenseMapBase<objc::DenseMap<objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 10
12 libdispatch.dylib              0x640a8 _dispatch_client_callout + 36
13 libdispatch.dylib              0x3f4a4 _dispatch_lane_serial_drain$VARIANT$armv81 + 600
14 libdispatch.dylib              0x3ff44 _dispatch_lane_invoke$VARIANT$armv81 + 388
15 libdispatch.dylib              0x498e0 _dispatch_workloop_worker_thread + 608
16 libsystem_pthread.dylib        0x1e10 _pthread_wqthread + 284
17 libsystem_pthread.dylib        0x193c start_wqthread + 8
```

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.08.08.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/thejoaov/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 21, 24, 26, 28, 29, 30, 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.8 => 46.0.8 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

Expo app app with dev client

**Comment by lrob7325** [comment]
The following helped me solve this issue, and some others after upgrading to sdk 46 from 44.
1. Added this to my package.json 
--"bundle:ios": "react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios"
--"postinstall": "yarn run bundle:ios"
2. Added this to "Bundle React Native code and images" in Xcode for my targets
--"export NODE_BINARY=node
export PROJECT_ROOT=$PWD/..
../node_modules/react-native/scripts/react-native-xcode.sh"

This was my source: https://stackoverflow.com/questions/62806319/main-jsbundle-does-not-exist-this-must-be-a-bug-with-main-jsbundle-issue-afte/62914788#62914788
