### ISSUE TITLE
Unrecognized permission remoteNotifications

### ISSUE THREAD

**Issue by kristkirp** [expo/expo#1875]
Hi i upgraded to 27 sdk, 
Having now:
"react": "^16.3.1",
"react-native": "^0.55.4",

Here's **the code**(exactly as in the docs):

```
async registerForPushNotificationsAsync() {
      const { status: existingStatus } = await Permissions.getAsync(
        Permissions.NOTIFICATIONS
      );
      let finalStatus = existingStatus;
      // only ask if permissions have not already been determined, because
      // iOS won't necessarily prompt the user a second time.
      if (existingStatus !== 'granted') {
        // Android remote notification permissions are granted during the app
        // install, so this will only ask on iOS
        const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        finalStatus = status;
      }
      // Stop here if the user did not grant permissions
      if (finalStatus !== 'granted') {
        return;
      }
      // Get the token that uniquely identifies this device
      let token = await Notifications.getExpoPushTokenAsync();
```

**The** **error:**

[Unhandled promise rejection: Error: Unrecognized permission remoteNotifications]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:121:42 in createErrorFromErrorData
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:78:57 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:398:4 in __invokeCallback
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:137:28 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314:6 in __guardSafe
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:136:17 in invokeCallbackAndReturnFlushedQueue

Before upgrade I was able to get permission requests and get token and save it and send push notifications. Now it's not going inside registerForPushNotificationsAsync at all(upd: I mean it throws on the very first line of the function). Though I am able to send notification with tokens.
 

Thank you

**Comment by kristkirp** [comment]
in my app.json I have updated it to 27.0.0, 
not sure how i've should updated expo package specifically, I just ran through steps to update reactnative to the latest version,
if there are special steps to update expo package then I definetely missed this point, but i don't know how

thank you

**Comment by brentvatne** [comment]
every release notes blog post explains it step by step

![](http://url.brentvatne.ca/xHRQWp.png)

**Comment by kristkirp** [comment]
Thank you!
is 28 compatible with react native 0.55.4?

**Comment by brentvatne** [comment]
yeah. here's the link https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530

**Comment by kristkirp** [comment]
if before i used 23 version, should i upgrade to 24 first then 25, 26, 27, or i can upgrade at once?

**Comment by brentvatne** [comment]
you can upgrade all at once if you want but you should check breaking changes in previous release notes

**Comment by kristkirp** [comment]
thank you!
