### ISSUE TITLE
[android] standalone app fails to build when local adaptiveIcon.backgroundImage is specified

### ISSUE THREAD

**Issue by mbellgb** [expo/expo#1876]
When attempting to build a standalone android app with `android.adaptiveIcon.backgroundImage` specified in my `app.json`, the build will fail during the `running gulp task` stage of the build process. Works fine if this key is excluded, and an `android.adaptiveIcon.foregroundImage` is specified.
 
### Environment

Environment:
  OS: Linux 4.16
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/mbellgb-d197f71c-157c-4a9b-b67e-18ab7f950549.tar.gz

Target: android

### Steps to Reproduce

1. Start with a functioning expo project.
2. Add two png files, one for the adaptive icon foreground, another for the background.
3. Reference them in `app.json`:

```json
{
  "expo": {
    "android: {
      "adaptiveIcon": {
        "backgroundImage": "./assets/icon-bg.png",
        "foregroundImage": "./assets/icon-fg.png"
      }
    }
  }
}
```

4. Build an android apk with `exp build:android`.
5. Wait for the result

### Expected Behavior

Expected build to complete successfully.

### Actual Behavior

Build fails in the `running gulp task` stage of the build process:

![image](https://user-images.githubusercontent.com/4870168/41435762-c31bf7d0-7017-11e8-9f43-d8e93e3d6d1c.png)

```
[stderr] [20:11:39] 'android-shell-app' errored after 6.04 s
[stderr] [20:11:39] Error: Invalid URI "./assets/icon-bg.png"
[stderr]     at Request.init (/src/exponent/tools-public/node_modules/xdl/node_modules/request/request.js:274:31)
[stderr]     at new Request (/src/exponent/tools-public/node_modules/xdl/node_modules/request/request.js:128:8)
[stderr]     at request (/src/exponent/tools-public/node_modules/xdl/node_modules/request/index.js:53:10)
[stderr]     at /xdl@50.1.0/src/detach/ExponentTools.js:53:5
[stderr]     at new Promise (<anonymous>)
[stderr]     at saveUrlToPathAsync (/xdl@50.1.0/src/detach/ExponentTools.js:44:10)
[stderr]     at /xdl@50.1.0/src/detach/AndroidShellApp.js:361:16
[stderr]     at Generator.next (<anonymous>)
[stderr]     at step (/src/exponent/tools-public/node_modules/xdl/build/detach/AndroidShellApp.js:629:191)
[stderr]     at /src/exponent/tools-public/node_modules/xdl/build/detach/AndroidShellApp.js:629:437
```

### Reproducible Demo

This is an expo project initialised with `exp init`, with two icons added.

https://github.com/mbellgb/expo-adaptive-icon

Start of build without adaptive icons specified, passing the `running gulp task` stage: 
![image](https://user-images.githubusercontent.com/4870168/41435600-4d0506b8-7017-11e8-8a11-15a8aba51fc8.png)

**Comment by esamelson** [comment]
Hi @mbellgb - thanks very much for the report. It looks like our build servers are running a slightly out-of-date version of the build script. Working on deploying a fix right now. Sorry for the inconvenience!!

**Comment by mbellgb** [comment]
Brilliant, thanks so much @esamelson! :tada:

**Comment by esamelson** [comment]
@mbellgb fix is deployed and the test app you've provided seems to be building for me, so I'm going to go ahead and close this. Thanks again for the thorough and timely report.
