### ISSUE TITLE
Deep Links not working for Android - potential issue with IntentFilters 

### ISSUE THREAD

**Issue by minul08** [expo/expo#18769]
### Summary

Having issues with deep links on Android, IOS seems to work just fine.

I have tried configuring with `autoVerify: true` so that the links will be auto verified and the app will open up right away (with dev client + simulators and physical devices with Android versions above 6), this unfortunately isn't the case.

Turning off `autoVerify` doesn't show the popup giving me the option to choose to open on browser or the app as well.

I can see that the configs work at least partially since I'm able to manually allow links to be opened by the app in app settings (check screenshot below). Once I enable this manually the app opens up just fine but this isn't what I'm trying to achieve here.

![image](https://user-images.githubusercontent.com/16258297/186120319-dea301a4-fb1f-4be6-b7e9-99c8474f2f4c.png)

### What platform(s) does this occur on?

Android

### Environment

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
      Yarn: 1.22.17 - ~/Documents/Code/amber-core/clients/mobile-app/node_modules/.bin/yarn
      npm: 7.24.1 - ~/.nvm/versions/node/v14.18.0/bin/npm
      Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-Tiramisu | Google APIs ARM 64 v8a, android-Tiramisu | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.1.0 => 9.1.0 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Minimal reproducible example

Intent Filter configuration 
```
[
  {
    autoVerify: true,
    action: 'VIEW',
    data: [
      {
        scheme: 'https',
        host: 'go.amber.com.au',
      },
      {
        scheme: 'http',
        host: 'go.amber.com.au',
      },
    ],
    category: ['BROWSABLE', 'DEFAULT'],
  },
]
```

Here is a screenshot from google play with confirmation that there is no issue with verification 
![Screen Shot 2022-08-23 at 2 54 55 pm](https://user-images.githubusercontent.com/16258297/186122821-ef1986e4-ba6c-42d4-86ba-faa86b1435e7.png)

**Comment by brentvatne** [comment]
this may be helpful: https://github.com/expo/expo-cli/issues/4180

**Comment by brentvatne** [comment]
here's that same information in the documentation: https://docs.expo.dev/guides/linking/#handling-app-links-on-android-with-expo-dev-client

**Comment by gyl89** [comment]
Had similar issue. I have removed expo-dev-client package and then it was working fine

**Comment by minul08** [comment]
> Had similar issue. I have removed expo-dev-client package and then it was working fine

Thank you! Unfortunately doesn't look like removing the `expo-dev-client` is an option for me.

**Comment by rpopovych** [comment]
@minul08, did you have any luck resolving the issue?

**Comment by clevadani** [comment]
This issue has been a pain for me.

**Comment by DSp4wN** [comment]
Still a problem, I made sure google play console has everything working in deep links working and expo app json has proper intentfilters defined

**Comment by ashishneomenta** [comment]
Check your https://{domain}/.well-known/assetlinks.json.

Once you hit this URL on the browser it should open the json file on the browser and not download the json file. If it downloads then fix it from the server.

**Comment by DSp4wN** [comment]
@ashishneomenta it does open the json file

**Comment by maksim-romanov** [comment]
Same issue for me

I see json with configuration by `.well-known/assetlinks.json`

ios working fine

**Comment by gitnlsn** [comment]
same issue for me.

**Comment by Amitnale007** [comment]
Create a sign release build and test becoz we are adding sha256 hash in assetlinks file so we should have test it in release apk
