### ISSUE TITLE
Could not build module 'React' from REAEventDispatcher.h #import <React/RCTEventDispatcher.h>

### ISSUE THREAD

**Issue by nomi9995** [expo/expo#18767]
### Summary

https://github.com/software-mansion/react-native-reanimated/issues/3466

It is only happening when I use expo latest and reanimated the latest version
```
 "react-native-reanimated": "3.0.0-rc.2",
 "expo": "46.0.8"
```

I was just enabling `NEW_ARCH` by `USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 pod install` and getting these errors from Xcode

`/project/ios/Pods/Headers/Public/hermes-engine/hermes/hermes.h:11:10: 'exception' file not found`

`/project/ios/Pods/Headers/Private/React-bridging/react/bridging/react/bridging/LongLivedObject.h:10:10: 'memory' file not found`

`/project/node_modules/react-native-reanimated/ios/REAEventDispatcher.h:2:9: Could not build module 'React'`

![image](https://user-images.githubusercontent.com/36044436/184296048-45246cc9-914c-4628-81a1-9ecdb825069e.png)

**Noted:** when i click on `jump to Defination` for `#import <React/RCTEventDispatcher.h>` it is jumping correctly.

### What platform(s) does this occur on?

iOS

### Environment

```
npx: installed 2 in 3.702s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /Users/apple/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28, 29, 30, 31, 32
        Build Tools: 25.0.3, 26.0.0, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
        Android NDK: 21.4.7075529
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.2.0 => 9.2.0 
      expo: 46.0.8 => 46.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.5.1
    Expo Workflow: bare
```

### Minimal reproducible example

https://github.com/nomi9995/fabric-reanimated-repro

**Comment by brentvatne** [comment]
we don't provide support for fabric at the moment, we're working on it
