### ISSUE TITLE
Android Failing to read uri of photo from imagepicker (newly taken or from photos)

### ISSUE THREAD

**Issue by Lastofthefirst** [expo/expo#18760]
### Summary

Suddenly, possibly after upgrading to SDK 46, I am not sure because immediately after upgrading I was mostly working with iOS, my app has been unable to read the uri of new images added via expo-image-picker. I get an error like the following:

```error
Location 'file:///data/user/0/host.exp.exponent/cache/ImagePicker/89003e23-afbb-4b5e-a63e-d263854d739f.jpeg' isn't readable.
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:106:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:21:23 in moduleName.methodInfo.name
at node_modules/expo-file-system/build/FileSystem.js:75:17 in copyAsync
at http://192.168.0.15:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in copyAsync
```

### What platform(s) does this occur on?

Android

### Environment

   System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 20210102.202219.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.2
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.60.0
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@lastof/android-imagepicker-uri-unreadable

**Comment by keith-kurak** [comment]
Hi @Lastofthefirst! Thanks for reporting this. I was able to reproduce on SDK 46, but only under Expo Go. I did not see it when running a standalone build. Let us know if you see otherwise.

**Comment by Lastofthefirst** [comment]
@keith-kurak oh interesting, yes it does work fine in a standalone apk.

**Comment by sayo96** [comment]
I'm running into this as well. Is there any fix for this?

**Comment by Yuvrajedulab** [comment]
use image manipulator of expo with image picker  it will solve the problem 

[https://docs.expo.dev/versions/latest/sdk/imagemanipulator/]

` const pickImage = async () => {
    let permissionResult = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (permissionResult.granted === false) {
      alert("Permission to access camera roll is required!");
      return;
    }
    // No permissions request is necessary for launching the image library
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      aspect: [4, 4],
      quality: 1,
    });

    if (!result.cancelled) {
      const manipResult = await ImageManipulator.manipulateAsync(
        result.localUri || result.uri,
        [{resize: {height:500,  width:500}}],
        { compress: 1, format: ImageManipulator.SaveFormat.PNG },
      );
      setImage(manipResult);
    };
    

  };`
 

it helps

**Comment by vladotoka** [comment]
I upgrade Expo SDK from 44 to 46 and have the same problem. i don't find any other solution than use dummy pseudo image manipulation middleware - without any real image manipulations . Thank you @Yuvrajedulab :)
`		const image = await ImagePicker.launchCameraAsync({
			allowsEditing: true,
			aspect: [16, 9],
			quality: 0.5,
		});

		if (!image.cancelled) {
			// dummy fixing ImagePicker bug in EXPO SDK46
			//TODO remove this bugfix with next EXPO SDK release
			const dummyManipulationResult = await ImageManipulator.manipulateAsync(
				image.uri,
				[],
				{}
			);
			//end of dummy fix...

			// setPickedImage(image.uri);
			// props.onImageTaken(image.uri);

			setPickedImage(dummyManipulationResult.uri);
			props.onImageTaken(dummyManipulationResult.uri);
		}
`
