### ISSUE TITLE
(Expo SDK 46 - lottie-react-native) Lottie Not Playing

### ISSUE THREAD

**Issue by SoloReverse** [expo/expo#18764]
### Summary

Hi there,

So theres a lottie bug everyone complained about that lotties are not automatically playing despite whatever
the useRef solution as outlined below 
`	useEffect(() => {
		lottieRef.current?.reset();
		setTimeout(() => {
			lottieRef.current?.play();
		}, 1000);
	}, []);`

works nicely but I found another way to avoid all of that extra code.
somehow having two lottie jsons in a folder and just swapping the 
`source={require(../blah.json)}`
with a different lottie works. I just reswap it back and viola. 

This is my first time posting a bug report ever, but I hope this info helps contributors get to the bottom of the issue and other people who struggle with this problem to avoid the the Hook function.

also the docs refer to using
<LottieView> and that never worked for me.

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      npm: 8.16.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.8 => 46.0.8 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      expo-cli: 6.0.2
    Expo Workflow: managed

### Minimal reproducible example

<Lottie
						autoPlay
						loop
						style={{
							width: 100,
							height: 100,
						}}
						source={require("../../assets/lottie/pin.json")}
					></Lottie>

**Comment by abdullascriptbh** [comment]
switch to light mode .. it has an issue with dark mode that's why
