### ISSUE TITLE
Failed to set up credentials.

### ISSUE THREAD

**Issue by Misael04** [expo/expo#18770]
### Summary

I'm receiving an error trying to upload a new AD-HOC Provisioning profile (same as this [issue](https://github.com/expo/expo/issues/18616)):

Failed to set up credentials.
    CombinedError: [Network] <!DOCTYPE html>
    
    
    
     <html class="no-js" lang="en-US"> 
    <head>

    <title>api.expo.dev | 504: Gateway time-out</title>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="robots" content="noindex, nofollow" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />

    </head>
    <body>
    <div id="cf-wrapper">

    

        <div id="cf-error-details" class="p-0">
            <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
                <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
                  <span class="cf-error-type">Error</span>
                  <span class="cf-error-code">504</span>
                </h1>
                <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 73f37ada9b5069de &bull;</span>
                <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2022-08-23 11:24:11 UTC</span>
                <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Gateway time-out</h2>
            </header>
        
            <div class="my-8 bg-gradient-gray">
                <div class="w-240 lg:w-full mx-auto">
                    <div class="clearfix md:px-8">
                  
    <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none 
    text-center">
      <div class="relative mb-10 md:m-0">
        <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
        <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
      </div>
      <span class="md:block w-full truncate">You</span>
      <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
      <span class="leading-1.3 text-2xl text-green-success">Working</span>
    </div>

    <div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none 
    text-center">
      <div class="relative mb-10 md:m-0">
        <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
        <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
      </div>
      <span class="md:block w-full truncate">Madrid</span>
      <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
      <span class="leading-1.3 text-2xl text-green-success">Working</span>
    </div>

    <div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left 
    md:float-none text-center">
      <div class="relative mb-10 md:m-0">
        <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
        <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
      </div>
      <span class="md:block w-full truncate">api.expo.dev</span>
      <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
      <span class="leading-1.3 text-2xl text-red-error">Error</span>
    </div>

                    </div>
              
                </div>
            </div>

            <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
                <div class="clearfix">
                    <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                        <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                        <p>The web server reported a gateway time-out error.</p>
                    </div>
              
                    <div class="w-1/2 md:w-full float-left leading-relaxed">
                        <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                        <p class="mb-6">Please try again in a few minutes.</p>
                    </div>
                </div>
              
            </div>

            <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
      <p class="text-13">
        <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">73f37ada9b5069de</strong></span>
        <span class="cf-footer-separator sm:hidden">&bull;</span>
        <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
          Your IP:
          <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
          <span class="hidden" id="cf-footer-ip">83.61.23.146</span>
          <span class="cf-footer-separator sm:hidden">&bull;</span>
        </span>
        <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" 
    target="_blank">Cloudflare</a></span>
    
      </p>
      <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in 
    b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var 
    a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
    </div>

        </div>
    </div>
    </body>
    </html>

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/alejandro.pavon/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: >=43.0.0-0 <44.0.0 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

Upload a new AD-hoc provisioning profile.

**Comment by brentvatne** [comment]
it looks like there was intermittent service unavailability at the time that you attempted to set up credentials. please try again and let us know if the issue persists and provide your expo account username and a link to the project page on expo.dev
