### ISSUE TITLE
expo export:web doesn't respect homepage entry in package.json

### ISSUE THREAD

**Issue by martin-braun** [expo/expo#18789]
### Summary

In the documentation there is the hint that I can change the output folder of `npx expo export:web`, but it's not working.

### What platform(s) does this occur on?

MacOS

### SDK Version

46 (latest), how can I verify? `npx expo --version` returns 0.2.11

### Environment

```
WARNING: expo-cli has not yet been tested against Node.js v18.7.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

Expected package expo-modules-autolinking@~0.10.1
Found invalid:
  expo-modules-autolinking@0.8.1
  (for more info, run: npm why expo-modules-autolinking)
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^5.0.1
Found invalid:
  @expo/prebuild-config@4.0.3
  (for more info, run: npm why @expo/prebuild-config)
```

Things I will work on ..

### Minimal reproducible example

```sh
npx create-expo-app my-app
cd my-app
# now edit your package.json, so it contains `"homepage": "/wepapp",`
npx expo export:web
```

Will still output to `web-build` instead of `webapp`.

**Comment by OzymandiasTheGreat** [comment]
You're misunderstanding the (admittedly poor) documentation. The homepage field, or rather it's path component is used to prefix the static asset paths in index.html. The output directory for `expo export:web` is always web-build regardless of homepage field.

**Comment by martin-braun** [comment]
@OzymandiasTheGreat Alright then.

Feature Request: Allow me to define a custom output folder for `expo export:web`. 😀

**Comment by OzymandiasTheGreat** [comment]
@martin-braun I'm not part of this project, just your issue was somewhat related to my issue and we both got tripped up by the documentation.
I'm curious tho, can't you just `expo export:web && mv web-build whathaveyou`? You could just put that as build script in package.json

**Comment by martin-braun** [comment]
@OzymandiasTheGreat I can, I will, I don't like. It's somewhat less intuitive to understand when I use `shx` and all, because you have to remove the older folder first as well. So it's more something like `expo export:web && shx rm -r whathaveyou && shx mv web-build whathaveyou`

**Comment by erisvaldojunior** [comment]
homepage field is not having any effect on metro web expo export --platform web)

**Comment by mikegee** [comment]
@martin-braun try `WEBPACK_BUILD_OUTPUT_PATH=some/other/path expo export:web`. Seems to work for me.

**Comment by martin-braun** [comment]
@mikegee Very much appreciated, although not working on Expo atm, I will remember this whenever I work with Expo again. 🙏 @EvanBacon you might want to document this, if it hasn't been done already.
