### ISSUE TITLE
Android camera picture not found when using allowsEditing: true

### ISSUE THREAD

**Issue by rclai** [expo/expo#1878]
Phone running Android 8.0.0
Client version 2.6.2
Expo SDK 28
https://snack.expo.io/B1fwWNbZ7
Remove line 27 and watch it work

```
handleOpenCamera.e [Error: /cache_files/ExperienceData/%40rclai%2Fapp-name/ImagePicker/fff4dce3-a009-4e72-8a0a-e41c434bb69f.jpg (No such file or directory)]
```

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.2
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 2.1 AI-143.2915827

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

**Comment by nicknovitski** [comment]
@aalices Any ideas?

**Comment by aalices** [comment]
Sorry for the bug @rclai  ! It is going to be fixed soon (possibly next week)

**Comment by rclai** [comment]
Okay thanks :)

**Comment by FakhruddinAbdi** [comment]
fixed ?

**Comment by esamelson** [comment]
Hi @FakhruddinAbdi - I believe this has been fixed internally and will go out in the next minor or major release. We don't yet have an estimate for when that will be. Sorry about the inconvenience. :(
