### ISSUE TITLE
"The method or property Amplitude.initializeAsync is not available on ios"

### ISSUE THREAD

**Issue by RiccardoPizzutti** [expo/expo#18786]
### Summary

Hey guys, 

after updating from SDK44 to SDK46 i get the following and can not find any reference in the internet for it. It`s package Version 11.3.0, but happens with 11.2.0 too. I get the same error for other Amplitude methods like "setTrackingOptionsAsync" or  "logEventWithPropertiesAsync" too. Any idea? Just saw: it`s the same for Android🤔

Thank you very much!!
All the best

 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: The method or property Amplitude.initializeAsync is not available on ios, are you sure you've linked all the native dependencies properly?
construct@[native code]
construct@[native code]
_construct@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:22863:28
Wrapper@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:22819:25
construct@[native code]
_createSuperInternal@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:113995:322
CodedError@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:114008:26
construct@[native code]
_createSuperInternal@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:114038:322
UnavailabilityError@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:114049:25
@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:261029:55
generatorResume@[native code]
asyncGeneratorStep@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25078:26
_next@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25100:29
@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25107:14
tryCallTwo@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30583:9
doResolve@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30747:25
Promise@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30606:14
@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25096:25
_initializeAsync@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:261034:34
initializeAsync@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:261023:34
@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:128491:30
loadModuleImplementation@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:290:14
@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:128327:52
loadModuleImplementation@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:290:14
@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:119503:69
loadModuleImplementation@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:290:14
@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:1357:48
loadModuleImplementation@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:290:14
guardedLoadModule@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:163:47
global code@http://192.168.0.101:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:261346:4

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.18.0 - ~/Documents/Entwicklung/GFD/GFDApp/node_modules/.bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ^46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 1.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

try {
  Amplitude.initializeAsync('Amplitude Code');
} catch (error) {
  console.log(erro);
}

**Comment by brentvatne** [comment]
expo-amplitude was deprecated in SDK 45 is not supported in SDK 46: 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/90494/186999684-ad944bb5-da04-4164-a61f-637494e4d005.png">

see the sdk 45 docs for migration suggestion: https://docs.expo.dev/versions/v45.0.0/sdk/amplitude/

<img width="647" alt="image" src="https://user-images.githubusercontent.com/90494/186999726-e94ce90e-5296-4879-b3bb-508f2cdd0e2e.png">
