### ISSUE TITLE
App crashing in production

### ISSUE THREAD

**Issue by germanolira** [expo/expo#18782]
### Summary

My app was in SDK 45 working normally, I updated the expo-cli and made an expo upgrade in the project, updated to SDK 46 and sent it to the store, when the app updated it started to crash and won't open anymore, I didn't add anything else to the app

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

expo --version
6.0.5

`"dependencies": {
    "@expo-google-fonts/poppins": "^0.2.2",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@shopify/flash-list": "1.1.0",
    "expo": "^46.0.0",
    "expo-app-loading": "~2.1.0",
    "expo-cli": "^5.5.1",
    "expo-font": "~10.2.0",
    "expo-splash-screen": "~0.16.1",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.4",
    "react-native-modal": "^13.0.1",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-toast-message": "^2.1.5",
    "react-native-uuid": "^2.0.1",
    "react-native-web": "~0.18.7",
    "styled-components": "^5.3.5"
  },`

### Environment

6 Atom, android-31 | Google APIs Intel x86 Atom_64    npmPackages:
      expo: ^46.0.0 => 46.0.9
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: bare

### Reproducible demo

There is no Reproducible demo

### Stacktrace (if a crash is involved)

I don't have Stacktrace

**Comment by germanolira** [comment]
I downgraded to the Expo SDK 45 and the app stopped crashing

**Comment by aliexalter** [comment]
To check this kind of crash send the app to internal testing on android. Then run the app on device by downloading from tester link. Attach device to android studio and  see logcat.

**Comment by chemobrain-cpu** [comment]
My apps also crashes... upgraded to expo 46 and it started crashing

**Comment by tharopan** [comment]
I developed in "expo": "~47.0.9", still crashing the functionalities.

**Comment by michaelraffin** [comment]
Has anyone 

> I developed in "expo": "~47.0.9", still crashing the functionalities in ios.

were you able to check the logs or check the crashlytics?

**Comment by ArtyEmsee** [comment]
> I developed in "expo": "~47.0.9", still crashing the functionalities in ios.

Were you able to fix this? I am developing a new project in ~47.0.12 and am also seeing a crash in iOS. Working fine locally.

**Comment by michaelraffin** [comment]
@ArtyEmsee not yet, it has been 2 weeks of debugging. Currently migrating to a new clean project.

**Comment by michaelraffin** [comment]
I'm using SDK 47 here are some fixes I did

- if you are using a map, remove the source or the map provider
- remove  the  pull to refresh function inside the scroll view/ table view or flat list
