### ISSUE TITLE
[cli] `expo-build-properties` plugin not running on `expo run:[android|ios]`

### ISSUE THREAD

**Issue by bombillazo** [expo/expo#18791]
### Summary

According to the `expo-build-properties` [documentation](https://docs.expo.dev/versions/latest/sdk/build-properties/#installation), this plugin runs with the expo commands `expo run:[android|ios]`. However, I see that the plugin does not run and update the settings files to add the plugin values passed in the app config.

When I run `expo prebuild`, however, it works as expected. I am currently having to run this command before every time I create a build.

### What platform(s) does this occur on?

Android, iOS

### SDK Version

^46.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.18.0 - ~/Projects/Code/app/node_modules/.bin/npm
      Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/user/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31, 32
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.21 => 0.3.22 
      expo: ~46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

Using any app.json with `expo-build-properties`:

```js

export default {
  ...
  plugins: [
    [
      'expo-build-properties',
      {
        android: {
          kotlinVersion: '1.6.10',
        },
      },
    ],
  ],
};

```

Running `expo run:android` does not modify the `gradle.properties` file. Running `expo prebuild` however does update the file with the overridden value.

**Comment by brentvatne** [comment]
https://docs.expo.dev/workflow/prebuild/#usage-with-expo-cli-run-commands

<img width="838" alt="image" src="https://user-images.githubusercontent.com/90494/186999432-b7338c46-38cd-4984-b53c-02ceb6b40855.png">
