### ISSUE TITLE
The `Accelerometer.setUpdateInterval` is not consistent for EAS builds

### ISSUE THREAD

**Issue by poulou0** [expo/expo#18796]
### Summary

Updates really fast on **expo GO** and **classic expo build**,
![works](https://user-images.githubusercontent.com/48758557/186396259-6cd32f10-df56-494b-a217-8c232d1723d0.gif)
but when I build with **EAS** I see a significant drop in performance.
![fails](https://user-images.githubusercontent.com/48758557/186396287-1b5d85ee-0e1a-47c7-a8d1-ada0bae469ba.gif)

And I get the same problem with the code of the documentation.

Thanks in advance :))

### What platform(s) does this occur on?

Android

### Environment

```
   System:
      OS: Linux 5.17 Pop!_OS 21.10
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.19.0 - /usr/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.0.0 - /usr/local/bin/npm
      Watchman: 20211128.225353.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Android NDK: 23.1.7779620
    npmPackages:
      expo: ~46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      eas-cli: 1.0.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

#### From the docs:
1. https://docs.expo.dev/versions/latest/sdk/accelerometer/#usage
`Try this example on Snack`
2. Download the code on your local machine from the top right `⤓ Download as zip`

#### Works as expected:
- Run in expo GO
`npx expo start`
- Build with classic expo build
`expo build:android -t apk`
#### Problem:
- Build with EAS cli
`eas build --platform android --profile preview`

**Comment by brentvatne** [comment]
see: https://docs.expo.dev/versions/latest/sdk/accelerometer/#accelerometersetupdateintervalintervalms

<img width="833" alt="image" src="https://user-images.githubusercontent.com/90494/186999171-c95480f5-fb42-4f6e-a1fc-f6b5d37e8147.png">

you will need to add this permission to your app. in app.json under the android key, eg: `"android": { "permission": ["android.permission.HIGH_SAMPLING_RATE_SENSORS"] }`

**Comment by poulou0** [comment]
@brentvatne Awesome!! I don't know how I missed that 🙈

**Comment by l11vdo** [comment]
thanks for the solution - i just wanted to add a quick correction to this as it caught me out...
as per expo documentation https://docs.expo.dev/guides/permissions/, the correct line to add to app.json is:
"permissions": ["android.permission.HIGH_SAMPLING_RATE_SENSORS"]
