### ISSUE TITLE
detaching to ExpoKit not working on ios

### ISSUE THREAD

**Issue by tomasfrancisco** [expo/expo#188]
After detached successfully to ExpoKit, installed pod dependencies and building the app, I'm getting the following error:

```
/Users/tomasfrancisco/Documents/dev/MyExpoApp/.expo-source/ios/ios/Exponent/Versioned/EXVersionManager.m:261:67: No visible @interface for 'RCTAsyncLocalStorage' declares the selector 'initWithStorageDirectory:'
```

Any thoughts?

**Comment by terribleben** [comment]
Hi! That constructor is only declared in Expo's fork of React Native. Make sure you [follow these instructions](https://docs.expo.io/versions/v16.0.0/guides/expokit.html#1-check-js-dependencies), including pointing at our fork. Once you've reconfigured your JS dependencies you'll need to `pod install` again.

**Comment by tomasfrancisco** [comment]
Thanks @terribleben 

I follow your instructions and now I'm getting this one:

```
/Users/tomasfrancisco/Documents/dev/MyExpoApp/node_modules/react-native/React/Modules/RCTDevSettings.mm:16:9: 'jschelpers/JavaScriptCore.h' file not found
```

I'm I missing something?
I just pointed the package to Expo's fork of React Native like that
`"react-native": "https://github.com/expo/react-native.git",`
and then `pod install`

**Comment by nineonine** [comment]
for those who have the same issue: make sure you run `npm install` **AFTER** you `npm run eject`  !

**Comment by thienpow** [comment]
can't find libjschelpers.a... how?

**Comment by oradzhabov** [comment]
set  dependencies in package.json to

    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
 
It solved this issue for me

**Comment by GeekRishabh** [comment]
Please reopen this issue .I am facing problem ejecting RN from exp (expoKit dependent)

my package.json

```
  "dependencies": {
    "expo": "^20.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz"
  }
```

**Comment by tedkimzikto** [comment]
I'm having similar issue.

I did have  former problems where I had an error from AppAuth as well

**Comment by ErickVoodoo** [comment]
@tedkimzikto 
Update package.json dependencies:

```
 "expo": "22.0.0",
 "react": "^16.0.0",
 "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.0.tar.gz",
```

It helped me!

**Comment by hugoh1995** [comment]
I'M facing the same issue: `arc semantic issue no visible @interface for 'rctasynclocalstorage'`
