### ISSUE TITLE
Websockets causing crash only in Android Production

### ISSUE THREAD

**Issue by jtisburywebthings** [expo/expo#1880]
Cannot create a reproducible Snack for this.

Environment:
  OS: Windows 10
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

  "dependencies": {
    "expo": "^28.0.0",
    "lodash": "^4.17.5",
    "native-base": "^2.3.9",
    "react": "^16.3.1",
    "react-dom": "^16.4.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz",
    "react-native-error-reporter": "^1.0.7",
    "react-native-exception-handler": "^2.7.5",
    "react-native-pure-chart": "0.0.20",
    "react-native-sentry": "^0.37.0",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.5.11",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "sentry-expo": "^1.7.0"
  }

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: ^16.3.1 => 16.4.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz => 0.55.4

### Steps to Reproduce

My app uses websockets to communicate with data from Generator sets.  I have the notion of "subscribing" to a websocket feed, which gives me data for a specific scene.

I use react-navigation to generate a stack.  The first scene in the stack opens a websocket, subscribes to a feed and processes the returned packets.

Clicking on an opactity then takes the user to another more detailed feed.  On loading this scene, I open another websocket connection, and start to process the packets coming back.  At some point during this process websockets causes the app to crash completely.

I put expo-sentry into the app, but no errors are logged when the crash occurs (or on next load).

I have tried the following:  

Use a later version of react-native (not expo version), and put error handling on Websockets.js.  Same problem, except only twice I have have an error bubble from Websockets.js stating "Websocket has been forcibly closed by the client".  This does not indicate where the closure comes from, but I suspect it comes from Android OS itself.

I have also changed my code so that the websocket subscription request happens from the first scene for the second scene.  This forces the app to use just one Websocket connection. But the app still crashes.

- - This only happens in Android, IOS is fine.  
- - Running in dev mode on Expo is fine (I suspect because I am using Chromes javascript engine).
- If I turn off developmen mode in Expo, and run in Expo, then the app crashes.

This points to a problem with the native implementation of Websockets in Android that Expo uses.

### Expected Behavior

I expect Android not to crash.  I would also expect expo-sentry to report what the actual error is, rather than report nothing.  This is obviously something that Expo is not handling at all.

### Actual Behavior

App crashes completely.

### Reproducible Demo

Here is my code:
```javascript
subscribeToModuleWebsocket  () {
        if (this.props.userServerAddress != undefined){
            this.socket = new WebSocket(this.props.userServerAddress);
          
            this.socket.onopen = () => this.socket.send(JSON.stringify({"1":{[this.props.selectedGatewayUSBID]:{"modules":{[this.props.moduleUSBID]:{"129":[65535],"130":this.props.subscribeStateMachinesString.split(','), "134":this.props.subscribeOutputString.split(','), "133":this.props.subscribeInputString.split(','),"131":this.props.subscribeInstrumentsString.split(',')}}}}}));
           
           this.socket.onclose = () => {
                try{  
                    console.log("CLOSED CONNECTION")
                } catch (err) {
                    console.log(err)
                    if (this.realClose == false) {
                    // RECONNECT HERE due to forcible close.
                        this.subscribeToModuleWebsocket()
                    }
                }
            }

            // Incoming message processing function.
            this.socket.onmessage = ({ data }) => 
            {
                this.props.processModuleWebsocketPacket(data)
            }
        }
    }
```

**Comment by nicknovitski** [comment]
Hmm.  The anonymous function for onclose includes the previously closed websocket in its closure.  Is it possible that would never get garbage collected, and a series of closed and reopened connection objects would stay in memory and grow until the app crashed?

**Comment by jtisburywebthings** [comment]
Thanks nicknovitski.   Excuse my ignorance, but I can't work out what you mean.  

Incidentally, the onClose function is never being called, the app crashes becore it even gets to this point.  The websocket connection opens, receives data, sends data, app crashes.

**Comment by phorque** [comment]
Do you think it may be related to https://github.com/expo/expo/issues/1866 ? Can you try with the updated React Native fork https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz ?

**Comment by jtisburywebthings** [comment]
Thanks phorque, I am using that version, and the crash occurs.

**Comment by nicknovitski** [comment]
@jtisburywebthings If onClose never gets called, then I think my theory must be wrong and my question doesn't matter, so in a way you answered it very well. 😄

**Comment by jesseruder** [comment]
> Running in dev mode on Expo is fine (I suspect because I am using Chromes javascript engine).

There is a distinction between "dev mode" and "dev mode with chrome debugging". Can you try it in both and let us know when it fails?

> Cannot create a reproducible Snack for this.

I'm not sure why it wouldn't be possible to create a Snack for this. Snack runs in production mode (other than minifying the JS) so it should be possible to repro there. Even if it doesn't repro in Snack it would still be useful for us to have a full example to run.

**Comment by jtisburywebthings** [comment]
Hi @jesseruder 

Please let me clarify:

If I build an IOS and an Android version.  IOS Version works well, but Android version always crashes.

If I run Expo with development mode ON and remote JS debugging ON, I do not get an error, presumably due to running using Chromes engine, and my PC obviously has more resources available than a phone.

If I run Expo with development mode ON and Remote JS Debugging OFF, it crashes.

If I run Expo with development mode OFF it crashes.

With regards creating a Snack project, unfortunately, I am unable to provide one as the connection information to the Websocket is unable to be published due to corporate security policies.  We are basically passing JSON packets.

I did create a brand new CRNA project, that had no other dependencies, and was able to process both websocket connections using the same code on the one scene.

I wonder if this could be something to do with react-navigation, and continuing to process the websocket on one scene, then the stack navigator loads another scene, which processes the second websocket.  The first is in the background of the stack processing.

Thank you very much for your help...

**Comment by jesseruder** [comment]
Thanks for the information about the chrome debugger.

Ok, I definitely understand that you can't make a Snack that uses your internal server. You could still make a Snack and either write a small test server or find some public websocket server. When we look into this we'll have to figure out how to reproduce it and we don't have access to your internal server.

**Comment by jtisburywebthings** [comment]
Just an update on this, which I hope will help.

I have refactored my code so that it seperates out seperate websocket connections.  The problem on Android happens when a websocket connection starts to receive large amounts of data.  Small, infrequent packets are fine, but a stream of packets causes a crash.  The crash happens PRIOR to any actual processing occurring.  It is like a buffer gets to large, and then uses too much memory before crashing.

**Comment by jtisburywebthings** [comment]
Adding tombstone dump from logcat.  I have no idea how I am meant to convert these as I cannot supply symbolic files (I know how, just don't know where the files would be located):

007-15 22:25:39.068  1316  1316 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-15 22:25:39.068  1316  1316 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus3/OnePlus3T:8.0.0/OPR1.170623.032/05171658:user/release-keys'
07-15 22:25:39.068  1316  1316 F DEBUG   : Revision: '0'
07-15 22:25:39.068  1316  1316 F DEBUG   : ABI: 'arm'
07-15 22:25:39.068  1316  1316 F DEBUG   : pid: 32509, tid: 832, name: mqt_js  >>> host.exp.exponent <<<
07-15 22:25:39.068  1316  1316 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
07-15 22:25:39.068  1316  1316 F DEBUG   : Cause: null pointer dereference
07-15 22:25:39.068  1316  1316 F DEBUG   :     r0 b895239c  r1 fffffffe  r2 bbadbeef  r3 00000000
07-15 22:25:39.068  1316  1316 F DEBUG   :     r4 00000000  r5 0161c000  r6 1a0d5000  r7 0000161c
07-15 22:25:39.068  1316  1316 F DEBUG   :     r8 c3ba2748  r9 c622d780  sl c27247f8  fp b895258c
07-15 22:25:39.068  1316  1316 F DEBUG   :     ip ffffffff  sp b8952420  lr c3b50da1  pc 00000000  cpsr 400b0010
07-15 22:25:39.072  1316  1316 F DEBUG   :
07-15 22:25:39.072  1316  1316 F DEBUG   : backtrace:
07-15 22:25:39.072  1316  1316 F DEBUG   :     #00 pc 00000000  <unknown>
07-15 22:25:39.072  1316  1316 F DEBUG   :     #01 pc 00182d9f  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so (WTFCrash+22)
07-15 22:25:39.072  1316  1316 F DEBUG   :     #02 pc 00172a47  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so (_ZN3WTF11fastReallocEPvj+1342)
07-15 22:25:39.072  1316  1316 F DEBUG   :     #03 pc 0004798b  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #04 pc 00047f2b  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #05 pc 000888c9  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #06 pc 000a0981  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #07 pc 0008a089  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #08 pc 0008b625  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #09 pc 000a94a5  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #10 pc 000a95b9  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #11 pc 000ad967  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so
07-15 22:25:39.072  1316  1316 F DEBUG   :     #12 pc 000aecf1  /data/app/host.exp.exponent-76GLZ_bdLX1cQAw2Ych5pQ==/lib/arm/libjsc.so

**Comment by cruzach** [comment]
Hi @jtisburywebthings- were you able to workaround this issue? Or have you upgraded SDKs, and are still seeing this?

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
