### ISSUE TITLE
Error: The method or property expo-random.getRandomBytes is not available on android, are you sure you've linked all the native dependencies properly?

### ISSUE THREAD

**Issue by aliexalter** [expo/expo#18819]
### Summary

I was using managed work flow. when I upload app bundle to internel testing and run n device I got this error.
Now  I run command **yarn android** and I got the following error and project is in bare workflow.

**Error: The method or property expo-random.getRandomBytes is not available on android, are you sure you've linked all the native dependencies properly?**

The stack trace lead to 
GoogleAuthRequest#Constructor 
Google.js:28:100

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 1.1.1
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

expo init
expo install expo-auth-session expo-random
yarn android

**Comment by aliexalter** [comment]
When I comment the following code it does not give me error. 🤔 

```
/*if (response?.type === 'success') {
          const { id_token } = response.params;
          
          const auth = getAuth();
          const provider = new GoogleAuthProvider();
          const credential = GoogleAuthProvider.credential(id_token);
          signInWithCredential(auth,credential);
        }*/
```

**Comment by maxenceg** [comment]
Hey!

I'm having the same error on our staging environment... I'll keep you posted if I find a fix somehow!

In the meantime, if you find a solution, please keep me updated 😛

**Comment by polcats** [comment]
@aliexalter were you able to find out the root cause of the issue?

**Comment by aliexalter** [comment]
I remove expo-auth-session and start using rnfirebase.io

**Comment by maxenceg** [comment]
Hi @brentvatne!

Since the problem persists on our end, we decided to create a minimal reproducible example here: https://github.com/the-totem/demo-expo-auth-session

We detailed the issue here: https://github.com/the-totem/demo-expo-auth-session/issues/1

To reproduce, you can clone our repo, run yarn install, and run yarn start.

If you install [this build](https://expo.dev/accounts/melbius_/projects/demo/builds/18de6e0b-4793-4512-aa2e-136b7442c2c0), you'll get the error as soon as you try to launch the dev client.

**Comment by husam287** [comment]
+1, any updates ??

**Comment by polcats** [comment]
+1 on this as well
