### ISSUE TITLE
"Failed to load all assets" in dev client with 

### ISSUE THREAD

**Issue by enagorny** [expo/expo#18826]
### Summary

When using dev-client with different app [variants](https://docs.expo.dev/build-reference/variants/) and trying to load the update there error shown:

![Simulator Screen Shot - iPhone 13 - 2022-08-25 at 14 24 34](https://user-images.githubusercontent.com/1202150/186674920-0660d5f6-f3f2-4a11-8e81-a3a0cc5dfccb.png)

When trying to load the update app performs request
```
curl 'https://assets.eascdn.net/Lu8yb71iHzIZ3ZZo_serQrGF28g54_lpDiT9VzsAQ-c?project=3bcb925d-8ba0-4fc9-97fb-c8a5827a0693' \
-H 'Host: assets.eascdn.net' \
-H 'Expo-Dev-Client-ID: 1F44D87D-B531-42A9-AF58-31AEF657AA44' \
-H 'Authorization: EAS-HMAC-SHA256 1661212800-sjUjFmlMV8e2zXy23A5u5PKCbZvJ8sRsQj-3CSEhryw' \
-H 'Accept-Language: en-GB,en;q=0.9' \
-H 'Accept: */*' \
-H 'Expo-Updates-Environment: DEVELOPMENT' \
-H 'User-Agent: BOXTdev/46 CFNetwork/1333.0.4 Darwin/21.6.0' \
-H 'Connection: keep-alive' \
-H 'Expo-API-Version: 1' \
-H 'Expo-Platform: ios' \
-H 'EAS-Client-ID: 4CE51D04-5D04-4C0A-8819-C129A92EF545' \
--proxy http://localhost:9090
```

and the response 
```
HTTP/1.1 404 Not Found
Date: Thu, 25 Aug 2022 13:20:39 GMT
Content-Type: application/xml; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-GUploader-UploadID: ADPycdvj4--tBpX9xz7BSL047m7L5I-CeRLNnhWXJECdGi91F09LY3ysBolb1xqy1YgFShua-Vr-YnxoMLHbPRwUkBmehQ
Expires: Thu, 25 Aug 2022 13:20:39 GMT
Cache-Control: private, max-age=0
CF-Cache-Status: MISS
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Vary: Accept-Encoding
Server: cloudflare
CF-RAY: 7404a05798e677bf-KBP
Content-Encoding: br

<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>
```

The bug doesn't show if the same BUNDLE_IDENTIFIER us used for all builds(check eas.json and app.config in Reproducible demo). But it means https://docs.expo.dev/build-reference/variants/ doesn't work as expected. 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

    "expo": "^46.0.9",
    "expo-dev-client": "~1.2.1",
    "expo-updates": "~0.14.5",

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nodenv/versions/16.13.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - ~/.nodenv/versions/16.13.1/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 1.1.1
      expo-cli: 6.0.5
    Expo Workflow: managed

### Reproducible demo

in eas.json 
```
"build": {

    "staging": {
      "env": {
        "APP_VARIANT": "development"
      },
      "channel": "staging",
      "developmentClient": true,
    },

    "production": {
      "channel": "main",
      "env": {
        "APP_VARIANT": "production"
      }
    }
```

and app.config.ts
```
const IS_DEV = process.env.APP_VARIANT === "development";
const BUNDLE_IDENTIFIER = IS_DEV ? "com.boxt.customerapp.dev" : "com.boxt.customerapp";

export default {
  ...
 ios: {
    bundleIdentifier: BUNDLE_IDENTIFIER,
...
```

**Comment by enagorny** [comment]
Hmm I see now the same error even with same `bundleIdentifier`

**Comment by brentvatne** [comment]
hey @enagorny - we'd love to investigate this but need help getting a minimal reproducible example put together. if you can follow the above comment that'd be helpful, thanks!

**Comment by enagorny** [comment]
@brentvatne  After numerous experiments we've found that it is failing with some particular .otf font files and only when loading update in a build with dev client. I can't share the font file here as it is paid font. The name of the font file is "Sofia_Pro_Bold_Italic.otf".
For now we've removed that file from the `useFonts` as we weren't using that bold italic.

**Comment by intCount** [comment]
@brentvatne Same issue still occur, even when upgrading to sdk47. We're stuck!

**Comment by himrocks33** [comment]
@brentvatne same issue here.  Very simple to reproduce:

`          await Font.loadAsync({
            'Gotham-Black': require('../assets/fonts/Gotham-Black.otf'),
          });`

In a project using expo dev client. 

I had to rename file to .txt because it wouldn't let me upload .otf.
[Gotham-Black.txt](https://github.com/expo/expo/files/10840911/Gotham-Black.txt)

**Comment by brentvatne** [comment]
@himrocks33 - can you share a minimal git repo that we can clone to reproduce this? loading fonts is done in basically every app and this issue appears to only occur to a verys mall group of people

**Comment by SwanHub** [comment]
I ran into this as well! Removing .otf file did the trick.

**Comment by Sir-hennihau** [comment]
the question is just on how to solve it if you want to load the fonts :D

**Comment by michaelpomogajko** [comment]
@brentvatne any updates on this? We're trying to move to eas update from classic expo publish but seeing the same 'failed to load all assets' error

**Comment by macBabu** [comment]
I removed all the .otf files and packages related to it but still getting the same error , what to do?

**Comment by divs1210** [comment]
I have the same issue with latest Expo and RN on iOS.

The app runs fine in the emulator and on Android.
