### ISSUE TITLE
EAS - iOS App Store build fails with `react-native-maps`

### ISSUE THREAD

**Issue by flexbox** [expo/expo#18829]
### Summary

Hey!
First of all, thank you to the expo team! 

Here is the issue, I encounter —sorry in advance if it's on the wrong repo 😅

with 
```json
"dependencies": {
  "expo": "^46.0.0",
  "react-native": "0.69.4",
  "react-native-maps": "0.31.1",
}
```

running 
```bash
eas build --platform=ios --profile=preview
```

Uploads, but installing Pods fail during the build

```bash
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`

[!] CocoaPods could not find compatible versions for pod "GoogleMaps":
  In snapshot (Podfile.lock):
  
    GoogleMaps (= 5.1.0)
  In Podfile:
    react-native-google-maps (from `/Users/expo/workingdir/build/node_modules/react-native-maps`) was resolved to 0.31.1, which depends on
      GoogleMaps (= 6.1.1)
```

![image](https://user-images.githubusercontent.com/360936/186678059-fb60b697-1992-41c9-b431-ca7b276676e3.png)

![image](https://user-images.githubusercontent.com/360936/186678116-369dac3d-71fb-4e57-91c6-bd290dcc05d9.png)

![image](https://user-images.githubusercontent.com/360936/186678357-170dcbe2-143b-4c6d-b3e2-de01ba39c257.png)

with 

```json
 
"dependencies": {
  ...
  "react-native-maps": "1.3.0",
}  
```

I have the same results

![image](https://user-images.githubusercontent.com/360936/186710126-962b24f4-b530-4652-9b03-97c2df8dac77.png)

![image](https://user-images.githubusercontent.com/360936/186710136-034f56a4-6aea-48c1-9f50-72124829a6f4.png)

### What platform(s) does this occur on?

iOS

### Environment

not sure if it's helpful because the builds fail with `eas-cli`

```bash
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.23.0-20220130.1630 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.6.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/cerebra/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-28 | Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0
      expo: ^46.0.0 => 46.0.3
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Minimal reproducible example

use https://github.com/react-native-maps/react-native-maps

```
npx create-expo-app my-app 
expo install react-native-maps
eas build
```

<img width="847" alt="image" src="https://user-images.githubusercontent.com/360936/186683258-f306f31d-09cc-4177-9b5f-9fe6b27c0649.png">

the cli suggest using an old version if [we check the release notes](https://github.com/react-native-maps/react-native-maps/releases)

**Comment by flexbox** [comment]
After some investigation, i will double-check these:

1. use `--clear-cache` when running the build
2. use the version `react-native-maps@1.2.0` suggested by cedric https://github.com/expo/expo/issues/18554#issuecomment-1216561781

**Comment by brentvatne** [comment]
from within the build you can also press press "Clear cache and retry build"

https://user-images.githubusercontent.com/90494/186997612-9030f7dc-a899-4bbd-a4b9-b21ba45b5cbc.mov

closing because I don't believe there is any bug with EAS Build here

**Comment by flexbox** [comment]
>any bug with EAS Build here
It looks to be related with the library `react-native-maps` and the `Podfiles.lock` cached by EAS

1. I ran
```
 eas build --platform=ios --profile=preview --clear-cache
```
used "Clear cache & retry build" from the web UI.
same results.

2. Downgraded to 
```
yarn add react-native-maps@1.2.0
```
same results.

I will try to

```
To fix that add the "cache.key" field (it can be set to any value) in the build profile in eas.json to invalidate the cache.
```

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/360936/187255724-f0bd19a1-ac66-4234-9805-f4b83ac1415e.png">

**Comment by brentvatne** [comment]
@flexbox - can you share a link to those build pages please? one where you first saw the error, and then the retried build without cache

**Comment by flexbox** [comment]
The very first one is
https://expo.dev/accounts/retail-shake/projects/scanner/builds/ea4e7ff7-6570-4174-bb2e-43b83d4f57a3

For the rest, I tried so many things that I don't remember 😅 
But I think you can check
- https://expo.dev/accounts/retail-shake/projects/scanner/builds/b652ae87-82ba-4946-80b8-ac548dffebf2
- https://expo.dev/accounts/retail-shake/projects/scanner/builds/78425629-93d4-4064-9d78-ed186ebf8a94

Next time I will take note to debug this. 
Do you think it could be related to `"react-native-maps"` only officially supported on `"0.31.1"` with Expo SDK 46 ?

**Comment by brentvatne** [comment]
can you help me to reproduce this? i created a blank project, initialized eas build, installed react-native-maps 0.31.1, create simulator build on eas build, then installed react-native-maps 1.3.1 and ran another build. both completed successfully.

**Comment by flexbox** [comment]
> can you help me to reproduce this? 
✅ here https://github.com/flexbox/react-native-bootcamp/pull/109
I got the same results as you, everything builds.

**So in the end what was the problem?**
After investigations, I found my `eas.jon` was using an old version 🤦‍♂️

I updated to

```diff
  "cli": {
    --"version": ">= 0.54.1"
    ++"version": ">= 1.2.0"
  },
```

**How can we avoid this in the future?**

@Simek
Maybe [creating a specific issue template `bug_report_eas.yml` only related to EAS](https://github.com/expo/expo/tree/main/.github/ISSUE_TEMPLATE) will help?

We can duplicate the existing and add this field

```yml
body:
  - type: textarea
    attributes:
      label: Building config
      description: copy the `eas.json` file content and paste in the field below.
    validations:
      required: true
```

But my problem still occurs, I noticed something weird

1. my  new project ~50 Mo
2. my real project ~2 Mo

<img width="688" alt="image" src="https://user-images.githubusercontent.com/360936/187889398-277cf95c-9a74-45ca-a66f-8841a2a3e250.png">

The investigation continues

**Comment by flexbox** [comment]
I thought —maybe it's a side effect from another library?

I commented everything related to `react-native-maps`

![image](https://user-images.githubusercontent.com/360936/188122381-3c4d1cc4-0f0d-4c3e-8290-df4d78ff39ed.png)

ran

```
eas build --platform=ios
```

it builds!

![image](https://user-images.githubusercontent.com/360936/188122520-35d61bec-79f9-4d37-94b4-20f9f2c370d3.png)

reverting my changes crashes again

![image](https://user-images.githubusercontent.com/360936/188122617-a52fc824-a41a-4715-8b45-79162f922c40.png)

I will [try to make it crash on this repo](https://github.com/flexbox/react-native-bootcamp/pull/109) to replicate the issue

**Comment by mvrahas** [comment]
I'm running into the same error when running running `eas build --profile development -p ios --clear-cache`

I noticed that the newer versions of react-native-maps require a minimum deployment target of >= iOS 13.0. My expo project is set at the default 12.4. Is there an easy way to increase this in the managed workflow? I tried setting up a config plugin for it but the documentation is confusing to navigate.

The only solution I can think of is reverting back to Expo 44. Unfortunately, the bugs with react-native-maps (0.31.1) are causing a lot of problems in my app.

Here's the ids for some of my failed builds...
827d11ad-07d2-4d4a-8525-79d5252c8167
12fd2ea2-629b-40a0-a171-f5d8c1da4b12
d5908f84-5de5-4e68-8689-610ec8a78655

**Comment by flexbox** [comment]
@mvrahas A GREAT THANKS YOU! iOS App Store builds successfully

Following [the documentation](https://docs.expo.dev/versions/latest/sdk/build-properties/#example-appjson-with-config-plugin), I added to `package.json`

```diff
"dependencies": {
  ...
  "react-native-maps": "1.3.0",
++   "expo-build-properties": "~0.3.0",
}  
```

And on `app.config.js`

```json
  plugins: [
    "sentry-expo",
    [
      "expo-build-properties",
      {
        android: {
          compileSdkVersion: 31,
          targetSdkVersion: 31,
          buildToolsVersion: "31.0.0",
        },
        ios: {
          deploymentTarget: "13.0",
        },
      },
    ],
  ],
```

I am using a managed workflow with EAS build. 

> The only solution I can think of is reverting back to Expo 44. Unfortunately, the bugs with react-native-maps (0.31.1) are causing a lot of problems in my app.
You can use the last expo SDK, [have a look at this PR, it builds successfully](https://github.com/flexbox/react-native-bootcamp/pull/109)

@brentvatne I will close this issue.
—for some reason, my production project was built with an old iOS `deploymentTarget` and I guess the new projects use 13+ by default.

**Comment by hfllr** [comment]
Even after trying the fix @flexbox suggested, I still get the same build error. (example build id: 294fc431-46cf-4509-bb62-843e04a641cb)

Anyone else still stuck there?

**Comment by flexbox** [comment]
Hey @hfllr 
Can you share the versions you are using on `package.json` and the output error?

**Comment by hfllr** [comment]
Thanks for the quick reply @flexbox !

I'm using the following packages & versions:
`"dependencies": {
    "@babel/eslint-parser": "^7.18.2",
    "@expo/config-plugins": "~6.0.0",
    "@expo/prebuild-config": "~6.0.0",
    "@expo/vector-icons": "^13.0.0",
    "@miblanchard/react-native-slider": "^2.1.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/blur": "^4.3.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/analytics": "^15.7.0",
    "@react-native-firebase/app": "~15.7.0",
    "@react-native-firebase/auth": "^15.7.0",
    "@react-native-firebase/database": "^15.7.0",
    "@react-native-firebase/firestore": "^15.7.0",
    "@react-native-firebase/functions": "^15.7.0",
    "@react-native-firebase/in-app-messaging": "^15.7.0",
    "@react-native-firebase/messaging": "^15.7.0",
    "@react-native-firebase/storage": "^15.7.0",
    "@react-navigation/bottom-tabs": "^5.11.15",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.14.9",
    "@sentry/react-native": "4.13.0",
    "@types/jest": "^27.0.1",
    "aws-sdk": "^2.1321.0",
    "buffer": "^6.0.3",
    "events": "^3.3.0",
    "expo": "47.0.0",
    "expo-app-loading": "~2.1.1",
    "expo-apple-authentication": "~6.0.1",
    "expo-application": "~5.1.1",
    "expo-auth-session": "~4.0.3",
    "expo-av": "~13.2.1",
    "expo-build-properties": "~0.5.1",
    "expo-camera": "~13.2.1",
    "expo-crypto": "~12.2.1",
    "expo-dev-client": "~2.1.5",
    "expo-device": "~5.2.1",
    "expo-face-detector": "~12.1.1",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image-loader": "~4.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "~4.0.1",
    "expo-localization": "~14.1.1",
    "expo-location": "~15.1.1",
    "expo-network": "~5.2.1",
    "expo-notifications": "~0.18.1",
    "expo-sensors": "~12.1.1",
    "expo-status-bar": "~1.4.2",
    "expo-system-ui": "~2.2.1",
    "expo-task-manager": "~11.1.1",
    "expo-updates": "~0.16.3",
    "i18n-js": "^3.8.0",
    "js-base64": "^3.7.2",
    "moment": "^2.29.1",
    "moti": "^0.15.2",
    "npm": "^8.4.0",
    "popmotion": "^9.3.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.3",
    "react-native-circular-progress": "^1.3.7",
    "react-native-date-picker": "^4.1.0",
    "react-native-error-boundary": "^1.1.16",
    "react-native-fast-image": "^8.5.11",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-in-app-review": "^4.1.1",
    "react-native-map-clustering": "^3.4.2",
    "react-native-maps": "1.3.2",
    "react-native-material-menu": "^1.2.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-restart": "^0.0.24",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "~3.20.0",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "13.4.0",
    "react-native-swiper-flatlist": "^3.0.15",
    "react-native-system-navigation-bar": "^1.0.2",
    "react-native-tab-view": "^3.1.1",
    "react-native-version-check": "^3.4.3",
    "react-native-web": "~0.18.7",
    "zustand": "^4.0.0"
  }`

The error looks like this and appears in the 'install pods' section of eas build (the yellow marked lines are the one related to this issue):  
  
![Screenshot 2023-03-14 145038](https://user-images.githubusercontent.com/47354807/225022718-88101236-5ffc-44e4-8b59-af0fa958667c.png)

**Comment by flexbox** [comment]
Have you checked this thread?

https://github.com/react-native-maps/react-native-maps/issues/4502#issuecomment-1304599405

**Comment by hfllr** [comment]
> Have you checked this thread?
> 
> [react-native-maps/react-native-maps#4502 (comment)](https://github.com/react-native-maps/react-native-maps/issues/4502#issuecomment-1304599405)

Does not change anything unfortunately.
I tried a similar plugin though mentioned [here](https://github.com/react-native-maps/react-native-maps/discussions/4389#discussioncomment-3750010) if anyone is interested, which installs the pods successfully but fails further down the line in the fastlane step, digging deeper right now and will post an update here if successful

**Comment by hfllr** [comment]
For anyone else stumbling across this: 

> > Have you checked this thread?
> > [react-native-maps/react-native-maps#4502 (comment)](https://github.com/react-native-maps/react-native-maps/issues/4502#issuecomment-1304599405)
> 
> Does not change anything unfortunately. I tried a similar plugin though mentioned [here](https://github.com/react-native-maps/react-native-maps/discussions/4389#discussioncomment-3750010) if anyone is interested, which installs the pods successfully but fails further down the line in the fastlane step, digging deeper right now and will post an update here if successful

It eventually failed because of some bitcode issue (as xcode 14 is not supporting it anymore) and thus it was necessary (for now) to disable it using another plugin: https://stackoverflow.com/questions/74434035/expo-sdk-46-ios-build-failed-in-fastlane-step
