### ISSUE TITLE
Capital R doesn't trigger refresh in the dev server

### ISSUE THREAD

**Issue by louislva** [expo/expo#18828]
### Summary

So you can press "r" to get a refresh in the Metro Bundler CLI. If you accidentally leave CAPS LOCK on, this no longer works.

### What platform(s) does this occur on?

iOS

### SDK Version

5.3.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.2 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Minimal reproducible example

1. Run dev server (with "expo run:ios" for example)
2. Press "r" and see that it refreshes the bundle on the phone
3. Turn CAPS LOCK on
4. See that pressing "R" no longer works

**Comment by brentvatne** [comment]
this is intentional. for example, if you press `i` to open the iOS simulator it will open the most recently used simulator, and `I` (uppercase `i`) will open a menu to let you select a simulator version.

we may in the future use R for some other purpose
