### ISSUE TITLE
[expo-notification] Platform:web Getting token error

### ISSUE THREAD

**Issue by OkancanCosar** [expo/expo#18822]
### Summary

I am currently using the notification service for android and ios. But when using it for web I am getting the following error while getting notification tokens.

Uncaught (in promise) Error: You must provide `notification.vapidPublicKey` in `app.json` to use push notifications on web. Learn more: https://docs.expo.dev/versions/latest/guides/using-vapid/.

There is no web-related section in the document. This means there is no web notification support. However, with this error, it seems that there may be notification support.
Is it possible for me to send notifications on the web platform using expo?

### What platform(s) does this occur on?

Web

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0
        System Images: android-29 | Google APIs Intel x86 Atom
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: managed
```

### Minimal reproducible example

```
import { useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import * as Device from "expo-device";
import { PermissionStatus } from "expo-modules-core";
import * as Notifications from "expo-notifications";

export default function App() {

  const [message, setMessage] = useState<string>("");
  const [token, setToken] = useState<string>("");

  useEffect(() => { init() }, [])

  const init = async () => {
    if (!Device.isDevice) {
      setMessage("Must be real device");
      return;
    }

    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    setMessage("getPermissionsResult: " + existingStatus);

    let finalStatus: PermissionStatus = existingStatus;
    if (existingStatus !== PermissionStatus.GRANTED) {
      const { status } = await Notifications.requestPermissionsAsync();
      setMessage("requestPermissionsResult: " + status);
      finalStatus = status;
    }
    if (finalStatus !== PermissionStatus.GRANTED) {
      setMessage("Permission Not Granted");
      return;
    }

    const expoPushToken: Notifications.ExpoPushToken = await Notifications.getExpoPushTokenAsync();
    setToken("expoPushToken: " + expoPushToken);

  }

  return (
    <View style={styles.container}>
      <Text>message: {message}</Text>
      <Text>token: {token}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

```

**Comment by brentvatne** [comment]
we don't support notifications on web: https://docs.expo.dev/versions/latest/sdk/notifications/

<img width="842" alt="image" src="https://user-images.githubusercontent.com/90494/186997967-25d232d6-0029-405a-93cc-53d81e948c84.png">

the code in there is experimental and not something we are intending for public use at the moment. it may be best for us to remove it. cc @EvanBacon

**Comment by jeltehomminga** [comment]
the user is first in the browser asked if he/she allows notifications, and then the error appears in the console. Would be nice if we also wouldn't aks the user permission for the notifications in the browser first

**Comment by zivc** [comment]
> the user is first in the browser asked if he/she allows notifications, and then the error appears in the console. Would be nice if we also wouldn't aks the user permission for the notifications in the browser first

You can check this by using the `Platform` module.

Pseudo code below;

```javascript
import { Platform } from "react-native";

const ComponentThingy = () => {
   
  useEffect(() => {
    if (Platform.OS === "web") return;

    // TODO Do non-web logic here, example;
    let { status: requestStatus } = await Notifications.getPermissionsAsync();
      if (requestStatus !== "granted") {
        requestStatus = await Notifications.requestPermissionsAsync();
      }

      if (requestStatus === "granted") {
        const token = (await Notifications.getDevicePushTokenAsync())?.data;
        const response = await pushNotificationTokenApi.call({
          token,
          device: Platform.OS,
        });
        // store token
      }
  }, []);

   return null;
}

export default ComponentThingy;
```

**Comment by pascal-mueller** [comment]
the link now points to a 404. The code in the docs uses `Device.isDevice`  which evalautes to `true` for `web`. Then the code proceeds to ask for permission. Maybe refactor the example code to use the `Platform` module as above.

**Comment by augustosamame** [comment]
Is the current answer to this still valid? Expo now uses the expo-notifications library, and according to this: https://docs.expo.dev/versions/latest/sdk/notifications/ is supported for web.
However, upon trying to get the token using getExpoPushTokenAsync it still throws the original error.
So is web supported or not? If it's not, then the documentation needs to be corrected as it clearly states web is supported. If it does, how to get around this error? Adding my public vapid to the web key in app.config.js did not resolve it

**Comment by jwaterworth** [comment]
@brentvatne or anyone else that may be in the know, is there a possibility of some clarity on this topic please? I too was about to ask the same question as @augustosamame.

The docs have indeed changed to indicate that web is supported since this PR was closed. If the answer is still "not supported", do any resources exist to aid with implementing an alternative to expo-notifications on the web platform?

Thank you kindly!

**Comment by JustusWin** [comment]
I literally just started working with expo and finding this as my first deep dive issue is... not funny. I've tried several variants in the configuration, but none seem to fix it.

**Comment by amandeepmittal** [comment]
Hey @jwaterworth and @augustosamame, we don't support the web as a platform for this library. Apologies for the inconvenience caused by the docs. We didn't mean it to be misleading, but somehow it slipped us.

As an alternative for web notifications, I'd suggest checking out OneSignal since they have a more comprehensive ecosystem around notifications support for multiple platforms in general.

**Comment by augustosamame** [comment]
> Hey @jwaterworth and @augustosamame, we don't support the web as a platform for this library. Apologies for the inconvenience caused by the docs. We didn't mean it to be misleading, but somehow it slipped us. We're working on updating our docs on this.
> 
> As an alternative for web notifications, I'd suggest checking out OneSignal since they have a more comprehensive ecosystem around notifications support for multiple platforms in general.

Thanks for the clarification @amandeepmittal 

I ended up using this gem https://github.com/zaru/webpush to handle web push separately from native notifications.

Implementation was pretty straightforward:

```
module Services
  class WebPushClient
    VAPID_PUBLIC_KEY = ENV['VAPID_WEBPUSH_PUBLIC_KEY']
    VAPID_PRIVATE_KEY = ENV['VAPID_WEBPUSH_PRIVATE_KEY']

    def send_push_notification(options) # title, body, url, destination_user_id
      if Rails.env.production?
        WebPushWorker.perform_async(options[:title], options[:body], options[:url], options[:destination_user_id])
      else
        send_push_notification_no_worker(options[:title], options[:body], options[:url], options[:destination_user_id])
      end
    end

    def handle_expired_subscription(user, subscription)
      Rails.logger.info "Removing expired subscription: #{subscription[:endpoint]}"
      # Remove the subscription from your database
      # For example, if you're using ActiveRecord:
      user.update(web_push_subscription: nil)
    end

    def send_push_notification_no_worker(title, body, url, destination_user_id)
      user = User.find(destination_user_id)

      if user.web_push_subscription.present?
        subscription = JSON.parse(user.web_push_subscription)
        message = {
          title: title,
          body: body,
          url: url.blank? ? nil : url
        }.to_json

        begin
          WebPush.payload_send(
            message: message,
            endpoint: subscription['endpoint'],
            p256dh: subscription['keys']['p256dh'],
            auth: subscription['keys']['auth'],
            vapid: {
              subject: 'mailto:support@yourdomain.com',
              public_key: VAPID_PUBLIC_KEY,
              private_key: VAPID_PRIVATE_KEY
            }
          )
        rescue WebPush::ExpiredSubscription => e
          handle_expired_subscription(user, subscription)
        rescue => e
          Rails.logger.error "Failed to send push notification: #{e.message}"
        end
      end
    end
  end
end
```

Of course everything is straightforward in Rails :) YMMV

**Comment by ningacoding** [comment]
i think it's súper easy implementing push notifications on web with Firebase, we aready setup Expo projects with FCM (Firebase) in order to handle push notifications on mobile (wich it's harder from my opinion when we talk about native code flow), I just can't understand why Push Notifications are not available on Expo.
