### ISSUE TITLE
Dismissing Modal while Alerting causes strange behavior.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [expo/expo#1883]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.4.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/andrewtc-3847877b-d7e1-4ce9-8720-32803f4f51c6.tar.gz

### Steps to Reproduce

[Repro repo](https://github.com/AndrewSouthpaw/expo-alert-modal-bug)

Running in iOS simulator, press "Alert!" button, notice Alert window disappears after a moment (and not actually pressing "OK"), then can't click "Try clicking me"

### Expected Behavior

Alert stays until it is dismissed.

### Actual Behavior

1. The Alert shows briefly then disappears, and
1. Further press interactions are prohibited, as if the Alert window is still there.
1. Simulator must be restarted before interactions are again possible

**Comment by minhthanh310** [comment]
same as this known issue? https://github.com/facebook/react-native/issues/10471

**Comment by AndrewSouthpaw** [comment]
Oops, that one didn't come up in my searches... closing.
