### ISSUE TITLE
Android Script adds Gradle Port Argument Twice

### ISSUE THREAD

**Issue by ngregory-rbi** [expo/expo#18835]
When `assembleAsync` is called in [this file](https://github.com/expo/expo-cli/blob/main/packages/expo-cli/src/commands/run/android/spawnGradleAsync.ts), the port argument gets added [here](https://github.com/expo/expo-cli/blob/main/packages/expo-cli/src/commands/run/android/spawnGradleAsync.ts#L52). The function then calls `spawnGradleAsync`, which added the flag again [here](https://github.com/expo/expo-cli/blob/main/packages/expo-cli/src/commands/run/android/spawnGradleAsync.ts#L80). I don't think added the flag twice does anything bad, but I don't think it should be doing that.

**Comment by EvanBacon** [comment]
Looks like I may have accidentally fixed it in the local CLI rewrite https://github.com/expo/expo/blob/474a7a4b11b580566a8c1895b5830e657b202079/packages/%40expo/cli/src/start/platforms/android/gradle.ts#L74
