### ISSUE TITLE
BarCodeScanner misreading code39 barcodes

### ISSUE THREAD

**Issue by tjg37** [expo/expo#18833]
### Summary

When scanning a code39 barcode without a check digit using the `expo-barcode-scanner` package, we observe that the scanned data is different to the encoded data within the barcode by at least one digit. For example, if the barcode is encoded with "ABCDEF001", the data received after scanning could be "ABCDEG001" or "ABCDEG002". After a few scans, the correct encoded data is read correctly. This issue does not happen on each scan, but is intermittent. 

We note that this issue occurs primarily on Samsung devices and hypothesize that the issue could be a combination of damaged barcodes and poor camera quality on the device. 

We recently moved our app from Ionic to React Native and never experienced this issue with the old version of the app, but now routinely experience the issue using the `expo-barcode-scanner` package. 

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.8
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 29.0.2, 29.0.3
        System Images: android-22 | ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Minimal reproducible example

Here is a basic snack: https://snack.expo.dev/@tejogol/barcodescanner-example

Note that the example is very simple.

**Comment by brentvatne** [comment]
expo-barcode-scanner will use the Google Mobile Vision API if it's available, otherwise it will fall back to [zxing](https://github.com/zxing/zxing). what underlying API did the Ionic library use?

**Comment by tjg37** [comment]
@brentvatne Thanks for sharing the additional information. We were using the [phonegap-plugin-barcodescanner](https://github.com/phonegap/phonegap-plugin-barcodescanner) library v8.1.0, which looks like it also uses [zxing](https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/src/android/com/phonegap/plugins/barcodescanner/BarcodeScanner.java#L32). 

Taking a look at the [zxing issues](https://github.com/zxing/zxing/issues?q=barcode+misread), I see a number of issues describing a similar situation after searching for "barcode misread". Could this be the source of the issue or do you think that the Google Mobile Vision API is responsible? If zxing is the source of the issue, why would we only experience these issues now and not before when using `phonegap-plugin-barcodescanner`?

**Comment by violuke** [comment]
We're using Tabris, so not this package, with the [tabris-plugin-barcode-scanner](https://github.com/eclipsesource/tabris-plugin-barcode-scanner) we have suddenly started to experience the same barcode misread issue as described here. We hadn't released an app update for a couple of months so no code had changed, and then suddenly one week we get quite a number of people mentioning this issue and all say it only affects Android, not iOS.

The plugin we're using is using Google Mobile Vision API. My current theory is that there has been an update to Google Mobile Vision API in some way that's causing all these misreads events to fire before the right barcode is read. I hope this is useful.

**Comment by tjg37** [comment]
It looks like the Google Mobile Vision API has been [deprecated](https://developers.google.com/vision) in favor of the ML Kit. Are there any plans to use the ML Kit instead of the Google Mobile Vision API?

**Comment by vitorleonel** [comment]
I noticed that Google says in its documentation that this misread can occur when we are getting the barcode from streaming (our case using camera).

So Google shares an idea to resolve that: get some scan results and then select the one that most repeat instead of use the first scan as final result.

Source: https://developers.google.com/ml-kit/vision/barcode-scanning/android?hl=en#performance-tips

**Comment by tjg37** [comment]
I have further information on this issue and was able to reproduce it using a Pixel 3 running android 12. 

The method used to reproduce the issue was to reduce the camera resolution using the Camera Settings on the Pixel 3 device. I did this by updating the resolution from "Full resolution" to "Medium resolution" to replicate poor camera quality. 

When scanning the following barcode and allowing for multiple scans (That is, by not setting `setScanned =true` after scanning), I obtained the following examples of sequences of scans. 

I've highlighted the "mis-scans" in bold and omitted scans which correctly extracted the data from the barcode. 

<img width="453" alt="Screen Shot 2023-06-06 at 11 17 46 AM" src="https://github.com/expo/expo/assets/26322196/f50b5a36-b97c-47b7-a285-c159bc30c47a">

- ["ABRJES013", "**ABRJES010**", "ABRJES013", "ABRJES013", "ABRJES013"]
- ["ABRJES013", "**ABRJESUU**", "ABRJES013", "ABRJES013", "ABRJES013"]
- ["**1BRJES013**", "**1BRJES013**"]
- ["**RJES013**", "ABRJES013", "ABRJES013", "ABRJES013", "ABRJES013"]
- ["**ABRJES01**", "ABRJES013", "ABRJES013", "ABRJES013", "ABRJES013"]
- ["ABRJES013", "**ABRJES01E**", "ABRJES013", "ABRJES013", "ABRJES013"]

As you can see from above, the "mis-scans" are not predictable and can take multiple forms, however the scans typically converge on the correct values. 

Based on the above, it looks like the update proposed by @vitorleonel would be a good way to address this issue.
