### ISSUE TITLE
Unable to login to Expo XDO or exp cli

### ISSUE THREAD

**Issue by dethell** [expo/expo#1884]
### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.11.1
  Yarn: Not Found
  npm: 6.0.1
  Watchman: Not Found
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
-[06:09:20] Request failed with status code 500
[06:09:20] Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/exp/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/exp/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/exp/node_modules/axios/lib/adapters/http.js:191:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

iOS using ExpoKit

### Steps to Reproduce

(Write your steps here:)

1. Using XDE, enter username and password, result "Invalid username/password. Please try again."
2. Using exp cli: 

> An Expo user account is required to proceed.
> 
> ? How would you like to authenticate? Log in with an existing Expo account
> ? Username/Email Address: dethell
> ? Password: [hidden]
> [06:09:54] Invalid username/password. Please try again.
> 

### Expected Behavior

I've been using this account for over a month with no password changes. It should login.

### Actual Behavior

Unable to log in. When this first started happening last week it was giving errors that it was unable to connect to the exp.host server. Now it just gives the invalid username/password error instead.

### Reproducible Demo

N/A

**Comment by nicknovitski** [comment]
That is strange.  Of course, your username is in our system.  Have you tried resetting your password?

**Comment by nikolal** [comment]
I have the same issue.

When I want to login from command line, I am getting:

```
[13:46:16] There was a problem understanding the server. Please try again.
[13:46:16] Set EXPO_DEBUG=true in your env to view the stack trace.
```

This started an hour ago. 

I was able to login two hours ago.

**Comment by nikolal** [comment]
It works for me now.

**Comment by nicknovitski** [comment]
@dethell Have you been able to log in, or to reset your password?

**Comment by dethell** [comment]
I was only able to log in after resetting my password. I'm not sure why my old password stopped working.

**Comment by hamzachaouch** [comment]
i have the same problem here i can log with XDE but in cl i wrote my login and the pwd but it s always the same issue :(

**Comment by sansetty2510** [comment]
I am also facing the same problem i am not able to login i am getting "There is no GET API endpoint at this URL." after enter my user name and password
