### ISSUE TITLE
path alias error

### ISSUE THREAD

**Issue by Valar103769** [expo/expo#18846]
### Summary

```
redbox
Unable to resolve "@components/SafeAreaLayout" from "navigation/SideMenuDrawer.tsx"
```
i write from  https://gist.github.com/ChronSyn/ffca12630eb36c71465a1c5d7149a6ae

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: managed

### Minimal reproducible example

```
<div data-snack-id="@valar103769/path-alias" data-snack-platform="web" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#F9F9F9;border:1px solid var(--color-border);border-radius:4px;height:505px;width:100%"></div>
<script async src="https://snack.expo.dev/embed.js"></script>
```

`https://snack.expo.dev/@valar103769/path-alias`

**Comment by Valar103769** [comment]
@hope

**Comment by Valar103769** [comment]
@hope

**Comment by Valar103769** [comment]
@lisen6

**Comment by brentvatne** [comment]
you can't modify the babel config on snack at the moment :)

**Comment by Valar103769** [comment]
> you can't modify the babel config on snack at the moment :)

it just a demo on snack you should look at babelrc and tsconfig 's content@brentvatne

**Comment by Valar103769** [comment]
> > you can't modify the babel config on snack at the moment :)
> 
> it just a demo on snack ，you can copy them to  youself project ，and you should just look at babelrc and tsconfig 's content @brentvatne

ps: my computed is apple m1  it can cause error?

**Comment by AlirezaHadjar** [comment]
I don't think so because I face this issue on intel mac as well.

**Comment by Valar103769** [comment]
I resolved it, it is not support `@` prefix, you can use follow , it has some problem, that you not defined path also includes, eg `import  SignScreen from 'screens/SignScreen'` is valid unexpected

```js
// babel.config.js
module.exports = function (api) {
  api.cache(true)
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolve',
        {
          extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
          alias: {
            components: './components',
            assets: './assets',
          },
        },
      ],
      'react-native-reanimated/plugin',
    ],
  }
}

```

```json
// tsconfig.json
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "jsx": "react",
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "paths": {
      "components/*": ["components/*"],
      "assets/*": ["assets/*"]
    }
  }
}

```
@AlirezaHadjar
