### ISSUE TITLE
Unable to build a dev client for Android and successfully use it

### ISSUE THREAD

**Issue by trajano** [expo/expo#18862]
### Summary

I tried a few permutations on getting the dev client to build.  On Windows `run:android` just gets stuck at config-syncing.  I have a Android dev-client built successfully on macOS and on a Linux build server.  

When I use the Linux built one, and try to launch my app using `expo start --dev-client` I get

> Attempting to call JS  function on a bad application bundle: AppRegistry.runApplication()

Unfortunately there's no logs.

The macOS one yields different errors so I'll create a separate bug for that one.

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.1 - ~\.nvm\versions\node\v16.15.1\bin\node.EXE
      Yarn: 1.22.19 - ~\.nvm\versions\node\v16.15.1\bin\yarn.CMD
      npm: 8.11.0 - ~\.nvm\versions\node\v16.15.1\bin\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      @expo/metro-config: ^0.3.12 => 0.3.21
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare
```

It says bare per [brents recommendation to run:android](https://forums.expo.dev/t/only-see-the-expo-logo-screen-in-the-expo-dev-client-android/66016/2?u=trajano) but I am normally on managed and I reset it back to get back to managed.

### Minimal reproducible example

not available.

**Comment by trajano** [comment]
After reverting back to my HEAD branch I get managed again

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.1 - ~\.nvm\versions\node\v16.15.1\bin\node.EXE
      Yarn: 1.22.19 - ~\.nvm\versions\node\v16.15.1\bin\yarn.CMD
      npm: 8.11.0 - ~\.nvm\versions\node\v16.15.1\bin\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      @expo/metro-config: ^0.3.12 => 0.3.21
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed
```

**Comment by Kudo** [comment]
hi there! i tried `expo-cli run:android` on windows and it works for me. it's hard for further investigation without more details or minimal reproducible example. you could also try to pass EXPO_DEBUG for more debug information when running run:android, i.e. `EXPO_DEBUG=1 expo-cli run:android`.

**Comment by trajano** [comment]
Thanks the `EXPO_DEBUG=1` would help. 

I am closing this now since I found the problem but only when I did `--tunnel` since it didn't say what the error is aside from network error on the logs

Also I had to use logcat to determine the issues, the errors didn't appear in the console logs.
