### ISSUE TITLE
Expo-AV / Video hides and shows randomly

### ISSUE THREAD

**Issue by themtaysw** [expo/expo#18866]
### Summary

I am working on something like _TikTok_ screen where I have my videos vertically playing on the full screen.

- I fetch 1 video from the server and everything is fine, response has some data etc.

- I then render the `<Video />` with its particular props needed (like width, height...) I also do `autoPlay`, `isLooping`

THE ERROR: I want to play the video but it's just a black screen. Then I click CMD+S (with no changes in code) and it magically shows the video and plays like nothing, then I leave the screen and video is gone again. And this keeps happening all the time. Is there any bug or something I am doing wrong??

The code:
```
<View>
  <TouchableWithoutFeedback onPress={() => status.isPlaying ? video.current.pauseAsync() : video.current.playAsync()}>
     <Video
        ref={video}
        source={{ uri: video.url }}
        shouldPlay
        isLooping
        onError={e => console.warn(e)}
        onPlaybackStatusUpdate={status => setStatus(() => status)}
        style={{ width: width, height: height }}
  />
  </TouchableWithoutFeedback>
</View>
```

Thanks for help

### What platform(s) does this occur on?

iOS

### SDK Version

"expo": "~45.0.0"

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.56.0
      expo-cli: 5.5.1
    Expo Workflow: managed

### Minimal reproducible example

...
const Shorts = () => {
    const { jwt } = useAuth()
    const [initialShort, setInitialShort] = useState(null)
    const video = useRef(null)
    const [status, setStatus] = useState({})

    const getInitialShort = async () => {
        const headersList = { "Accept": "*/*", "Authorization": "Bearer " + jwt }
        const reqOptions = { url: `${baseUrl}/shorts/count`, method: "GET", headers: headersList }
        const { data } = await axios.request(reqOptions).catch(e => alert(e))
        const initId = Math.floor(Math.random() * (Math.floor(data)) + 1)

        const reqShortOptions = { url: `${baseUrl}/shorts/${initId}?populate=*`, method: "GET", headers: headersList }
        const res = await axios.request(reqShortOptions).catch(e => alert(e))
        setInitialShort(res.data)
    }

    useFocusEffect(
        useCallback(() => {
            getInitialShort()
            return () => {
                video.current.pauseAsync()
            }
        }, [])
    )

    if (!initialShort) return (<Container><ActivityIndicator /></Container>)

    if (initialShort) {
        return (
            <View>
                <TouchableWithoutFeedback onPress={() => status.isPlaying ? video.current.pauseAsync() : video.current.playAsync()}>
                    <Video
                        ref={video}
                        source={{ uri: initialShort.data.attributes.video.data.attributes.url }}
                        shouldPlay
                        isLooping
                        onError={e => console.warn(e)}
                        onPlaybackStatusUpdate={status => setStatus(() => status)}
                        style={{ width: width, height: height }}
                    />
                </TouchableWithoutFeedback>
            </View>
        )
    }

    return <Container><ActivityIndicator /></Container>
}
...

**Comment by milkmanjr** [comment]
@themtaysw did you figure out the issue with random black Video players?  I'm running into this as well.

**Comment by themtaysw** [comment]
> @themtaysw did you figure out the issue with random black Video players? I'm running into this as well.

Okay so as I mentioned in the email:
`hey, so my issue was not exactly in expo-av, but rather in my backend server. i had video data for only 1 pit of 3 videos. but the expo didnt throw me an error there are no data only displayed black screen. after realizing this i fixed it and it works just fine.

however i didnt find any logical solution for black screen bcs it should not happen.`

I tried to delete the issue right after finding out but for some reason, it stayed here 😅

**Comment by themtaysw** [comment]
hey, so my issue was not exactly in expo-av, rather in my backend server. i
had video data for only 1 pit of 3 videos. but the expo didnt throw me an
error there are no data only displayed black screen. after realising this i
fixed it and it works just fine.

however i didnt find any logical solution for black screen bcs it should
not happen.

if you have any problems please share with me then i would like to help.
you can also share code maybe setup has some bug.
kindly

-matej
