### ISSUE TITLE
ExponentKernel.sdkVersions Error while building binaries of expo client

### ISSUE THREAD

**Issue by themakerman** [expo/expo#1886]
![screen shot 2018-06-18 at 8 24 54 pm](https://user-images.githubusercontent.com/14818804/41535991-d4491912-7336-11e8-96e3-d42a209b5ab2.png)

Under:
path: expo/js/package.json

Line No: 34
"react-native": "expo/react-native#sdk-26"

Is this line correct or do i have to replace this with something else?

I see this error at 
path: expo/js/screens/SignInScreen.js
line: 159

Can anyone please help me out?

**Comment by terribleben** [comment]
Hey there, thanks for the question. It looks like you're trying to build some of our open source Expo Client code, but i'm not exactly sure how you got here. Can you help me by answering these questions?

- What are you hoping to accomplish which got you to this point?
- What instructions did you follow to get here?

**Comment by themakerman** [comment]
@terribleben hey, yup that's what I want to do. Build expo client binary. I want to edit the code so that I can build something on top of expo environment. The expo team is already aware. I followed the docs in Readme.md section. The build works fine but when I am modifying the js files they don't get updated. So it was mentioned to run exp start in js folder. After which even the build ie. /run.sh fails and I get the above error.

**Comment by terribleben** [comment]
- What exact steps should I take to reach `Undefined is not an object (evaluating ExponentKernel.sdkVersions` ? When I follow the README, it works for me. Note that there are more instructions in the README beyond just running `exp start`.
- Your recent comment mentioned something about being unable to log in, is that related to the original issue or is it a different problem?

**Comment by themakerman** [comment]
okay @terribleben can you try to login your expo id after running exp start in js folder?

**Comment by themakerman** [comment]
@terribleben Please check the below screenshot. Would be really great if we can solve this faster.
![screen shot 2018-06-19 at 2 08 11 pm](https://user-images.githubusercontent.com/14818804/41579631-5112ba14-73ca-11e8-93d3-94dda69f78c6.png)

**Comment by themakerman** [comment]
@terribleben For faster reproduction of the error i face......start the expo project in js folder and try to log in your expo account. Do you face the 'sdkVersion' problem?

**Comment by terribleben** [comment]
> Run the build.
> exp start in js directory
> open the app from qr code you see after exp start

🤔 I'm confused - where did you find these instructions? This will not work. The [README](https://github.com/expo/expo#modifying-js-code) has different instructions:

> The Expo client apps run a root Expo project in addition to native code. By default this will use a published version of the project, so any changes made in the js directory will not show up without some extra work.
> 
> Serve this project locally by running exp start from the js directory. On iOS, you'll additionally need to set DEV_KERNEL_SOURCE to LOCAL in EXBuildConstants.plist (the default is PUBLISHED).
> 
> The native Android Studio and XCode projects have a build hook which will find this if exp start is running. Keep this running and rebuild the app on each platform.

**Comment by themakerman** [comment]
`On iOS, you'll additionally need to set DEV_KERNEL_SOURCE to LOCAL in EXBuildConstants.plist`
Do i have to do something similar for android as i see the above error on android as well while i try to login in my expo account.

**Comment by themakerman** [comment]
@terribleben heya mate. Any updates?

**Comment by yogen-darji-hs** [comment]
Hi @themakerman @terribleben @sjchmiela,

Is there any way to use publishedUrl in developmentUrl in EXBuildConstants.plist file?

I want to generate simulator build with "published url" for Facebook App Review process.

As default developmentURL will not work without expo.

Thanks in advance

**Comment by EvanBacon** [comment]
@yogen-darji-hs your issue will be addressed in the [appropriate thread](https://forums.expo.io/t/expo-detached-app-generate-ios-simulator-build-for-facebook-app-review/12235). Please do not ask questions in unrelated issues.
