### ISSUE TITLE
SDK 45 - expo-localization returns: Object is not a constructor (evaluating 'new _i18nJs.default')

### ISSUE THREAD

**Issue by maoo** [expo/expo#18884]
### Summary

Hi there!

I'm trying to use expo-localization to enable i18n on my app; I'm using expo SDK 45 with a managed workflow and following https://docs.expo.dev/versions/latest/sdk/localization/ ; I'm testing using the Expo Go mobile app on Android.

Problem is, when I load the app after adding the items described in the tutorial, I get the following error:

```
TypeError: Object is not a constructor (evaluating 'new _i18nJs.default')

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

I reported the steps to reproduce the issue from a blank/minimal expo project.

Note that I downgraded `i18n-js` to version 3.9.2, following the suggestion I found on https://github.com/expo/expo/issues/18695

Any help would be greatly appreciated. Thank you!

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.14.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      eas-cli: 1.1.1
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Minimal reproducible example

```
expo init i18n-test #minimal
cd i18n-test
```

#### Install expo-localization
```
expo install expo-localization
expo install i18n-js
```

#### Update versions in `package.json` to SDK 45:
```
"expo": "~45.0.0",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-native": "0.68.2",
"i18n-js": "3.9.2",
```

#### In `App.js`

- Add:
```
import I18n from 'i18n-js';
import * as Localization from 'expo-localization';
```

- Add:
```
const i18n = new I18n({
	en: {
	  welcome: 'Hello'
	},
	es: {
	  welcome: 'Hola'
	},
	it: {
	  welcome: 'Ciao'
	}
});

i18n.locale = Localization.locale;
i18n.enableFallback = true;
```

- Add:
```
<Text style={styles.text}>
	{i18n.t('welcome')} {i18n.t('name')}
</Text>
```

#### Install and start
```
yarn install
npx expo start
```

**Comment by Simek** [comment]
Hello @maoo,

The problematic example has been updated in:
* https://github.com/expo/expo/pull/18728 
 
You can see the working example also on Snack - https://snack.expo.dev/@simek/localization.

The documentation page now contains the code which can be used with the latest release of `i18n-js` (v4), everything should work correctly if you updated the code according to the examples.

**Comment by maoo** [comment]
@Simek - thank you SO much! By checking docs and examples, I could spot what I was doing wrong, which is the line

```
import I18n from 'i18n-js';
```

I replaced it with

```
import { I18n } from 'i18n-js';
```

and everything started to work as expected!

Thank you!! Closing issue.
