### ISSUE TITLE
expo-auth-session/google | project full name is not defined

### ISSUE THREAD

**Issue by MicahDerusha** [expo/expo#18897]
### Summary

After updating to sdk 46, it looks like its necessary to pass in projectNameForProxy to Google auth request redirect config when using a proxy.  
Even after setting that value to @user/slug, I still get the error "Cannot use the AuthSession proxy because the project full name is not defined".

### What platform(s) does this occur on?

Android, iOS, Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ^46.0.2 => 46.0.9
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Minimal reproducible example

{
      useProxy,
      projectNameForProxy: '@user/slug',
    };

**Comment by AronH99** [comment]
How did you fix this issue i am stuck with the exact same issue, though i followed all of the right steps in the official docs...

**Comment by Minminzei** [comment]
@AronH99 
In my case, I could resolve by putting `@owner/slug` to currentFullName and originalFullName in `app.json / app.config.js`.
https://docs.expo.dev/versions/latest/config/app/#currentfullname

**Comment by AronH99** [comment]
@Minminzei i want you to know, you are an absolute legend man, you really made my day here haha, it seems like it's working! :)

**Comment by CledirFL** [comment]
> @AronH99 In my case, I could resolve by putting `@owner/slug` to currentFullName and originalFullName in `app.json / app.config.js`. https://docs.expo.dev/versions/latest/config/app/#currentfullname

@Minminzei 
in my case didn't work  

My **app.json** didn't recognize the Properties "**currentFullName**" and "**originFullName**" 

"expo": "^47.0.0"

**Comment by zetziggu** [comment]
> @AronH99 In my case, I could resolve by putting `@owner/slug` to currentFullName and originalFullName in `app.json / app.config.js`. https://docs.expo.dev/versions/latest/config/app/#currentfullname

thanks for helping mate.

however, I think that in this case Expo docs are confusing as [they state](https://docs.expo.dev/versions/latest/config/app/#currentfullname) that

> The auto generated Expo account name and slug used for display purposes. It is not meant to be set directly.

which is not true
