### ISSUE TITLE
SQLite: Cannot run more than 1 query using async/await transaction

### ISSUE THREAD

**Issue by rclai** [expo/expo#1889]
I'm trying to leverage async/await inside the `transaction` function but no matter what, the first `await`ed query is the only one that runs and just ends the transaction right there without executing the rest. It seems to not know how to handle multiple promises being resolved inside the `transaction` function. Confirmed on both iOS and Android Expo clients.

### Reproduction
https://snack.expo.io/@rclai/sqlite-async-await-issue

1. Run a db transaction by passing an async function callback to it
2. Run `await`ed queries wrapped in Promises
3. The transaction ends after the first query

### Env't Info
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.2
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 2.1 AI-143.2915827

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

**Comment by msevestre** [comment]
@rclai can you show us the code as well?

**Comment by rclai** [comment]
I don't understand, is the snack not showing the code?

**Comment by msevestre** [comment]
@rclai my bad. Code is not visible on phone. Never realized that :)

**Comment by msevestre** [comment]
what are you trying to achieve ?

here is the signature of transaction
```
db.transaction(callback, error, success)
```

I think the problem in your code is that your callback method is never awaited. And as such the transaction completes before the code is finished. 

Check usage of SQLite here
https://github.com/expo/sqlite-example/blob/master/App.js

**Comment by msevestre** [comment]
Sure. What about you call the success callback in that case? 

```
tx.executeSql(sqlStatement, arguments, success, error)
```

success (function) -- Called when the query is successfully completed during the transaction. Takes two parameters: the transaction itself, and a ResultSet object (see below) with the results of the query.

**Comment by rclai** [comment]
I could do that but then I'd have to go back to the days of callback hell. Are you guys not able to await the transaction function?

**Comment by rclai** [comment]
Should this be a feature request?

**Comment by tsapeta** [comment]
@rclai Our SQLite module just implements WebSQL specification, so I don't see any reason to change that behavior until it's a part of this specification.
