### ISSUE TITLE
Push notifications API often returning ECONNRESET or ECONNREFUSED

### ISSUE THREAD

**Issue by rrufus** [expo/expo#18902]
### Summary

I have a server which sends push notifications out at scheduled times. Recently, I have started to see many ECONNRESET or ECONNREFUSED errors coming through the logs. It does not occur consistently, and most of the push notifications sent out are delivered successfully.

The first time it occured was on Friday 12th August, with an ECONNREFUSED: 

```
request to https://exp.host/--/api/v2/push/send failed, reason: connect ECONNREFUSED 34.135.150.141:443
```

After this, the failure has changed to be replaced with an ECONNRESET error message, e.g.

```
request to https://exp.host/--/api/v2/push/send failed, reason: read ECONNRESET
```

This mainly happens on the `/v2/push/send` method but I have also seen it on the `/v2/push/getReceipts` method.

The problem seems to have got more frequent over time, and often seems to happen on the hour (I have set up my server to not send notifications out exactly on the hour, and instead wait until a certain number of seconds past, in an attempt to alleviate load on the expo servers).

I saw a big increase in ECONNRESET errors on Friday 26th August through to Sunday 28th August, and it is still happening now. 

In total, since 12th August, I count it has happened 95 times, alongside 7 504 gateway timeouts happening in that time too (which is not the subject of this issue, however you could also see https://github.com/expo/expo/issues/18650 for that).

I am diligent with disabling tokens if the ticket or receipt indicates that it is no longer active. If the error indicates that some more tokens should be disabled I am happy to do that, however the ECONNRESET message does not give enough detail for me to consider this the correct action to take.

Also, I cannot see any issue with the expo servers as reported on https://status.expo.dev/

Thanks for any assistance!

### What platform(s) does this occur on?

Not Applicable

### Environment

Not applicable, I guess?

### Minimal reproducible example

await expo.sendPushNotificationsAsync(pushNotifications)

or using

https://expo.dev/notifications

**Comment by Noitidart** [comment]
Confirmed, I see this increased over the last year.

**Comment by griffinbaker12** [comment]
Happens to me as well. No way to tell if notifications got sent or not.
