### ISSUE TITLE
ImagePicker doesn't pick animating gif in android

### ISSUE THREAD

**Issue by pranav377** [expo/expo#18901]
### Summary

I am trying to select gif files using expo-image-picker. However, it doesn't select the gif file in android, it selects the first frame of the gif even when `quality` is set to `undefined` and `allowsEditing` to `false`.

Expected behavior for android:

![Expected behavior on android](https://user-images.githubusercontent.com/71634384/187397587-a7397c1b-7fd8-4488-8ae7-43216e5e8ab5.gif)

Actual behavior on android:

![Actual behavior on android](https://user-images.githubusercontent.com/71634384/187398202-b955ba68-eca9-4ce8-898d-72f4334da750.jpg)

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526

### Minimal reproducible example

Version of expo - `46.0.9`, Version of expo-image-picker - `13.3.1`. Here's the reproducible demo - [snack demo](https://snack.expo.dev/@pranav377/expo-imagepicker-gif-selection?platform=android)

**Comment by keith-kurak** [comment]
Hi @pranav377! Thanks for the report- I was able to reproduce on my end thanks to your demonstration.

**Comment by barthap** [comment]
The docs are wrong - set the `quality` to `1` on Android and animated GIFs should work.

See #20034 for more details

**Comment by pranav377** [comment]
@barthap it works now! Thanks!!
