### ISSUE TITLE
you are currently using minified code outside of node_env === 'production'

### ISSUE THREAD

**Issue by stefdelec** [expo/expo#1890]
I have suddenly the following error with no reason.

You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

**Comment by AdamJNavarro** [comment]
Hey @stefdelec,

What developer tool are you using to serve your code?

**Comment by stefdelec** [comment]
Sorry for the lake of informations.
I used to use `react-native-scripts` and I replace it with `  "start": "exp start --dev -c -i --no-minify",`. It fixed my problem.

Thanks for the great work btw!

**Comment by drochetti** [comment]
That doesn't actually fix the issue. You're just not minifying the code, which is a problem for production bundles.

**Comment by mauriciord** [comment]
I'm having same issue using Expo, but `expo start --dev -c -i --no-minify` didn't resolve my problem :(

**Comment by kylebebak** [comment]
This issue need to be re-created or re-opened =/

**Comment by brentvatne** [comment]
if someone can create a new issue and provide enough info for us to reproduce or understand what's going on we can definitely look!
