### ISSUE TITLE
Network timeout error occured even if executing "expo start --offline" with expo "46.0.*"

### ISSUE THREAD

**Issue by LyunKi** [expo/expo#18918]
### Summary

When I started my expo project with the latest version 46.0.0, I got a network error. I thought my proxy settings caused it, so I tried to use offline mode by the command `expo start --offline`, however there still a network error happened.

![image](https://user-images.githubusercontent.com/21052565/187584724-cdf4e7fd-d46f-4e56-9ff7-ce37fa2fb8f4.png)

And then I tried to fall back to the 45.0.0 version, it worked as I expected.

### What platform(s) does this occur on?

Web

### SDK Version

46.0.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.19.1 - D:\ly\softwares\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
      npm: 6.14.16 - D:\ly\softwares\nodejs\npm.CMD
    npmPackages:
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: managed

### Minimal reproducible example

Just any project created by "expo init"

**Comment by keith-kurak** [comment]
@LyunKi Hi! Can you confirm if you still experience the issue after upgrading to the latest version of the Expo SDK (run `npx expo upgrade` and accept all prompts). I saw this intermittently on some previous versions, but not the latest.

Also, if you still experience the issue after that, please run `npx expo-env-info` again and update your issue accordingly. It does not list an Expo or React Native version, which seems unexpected. Thanks!

**Comment by LyunKi** [comment]
> @LyunKi Hi! Can you confirm if you still experience the issue after upgrading to the latest version of the Expo SDK (run `npx expo upgrade` and accept all prompts). I saw this intermittently on some previous versions, but not the latest.
> 
> Also, if you still experience the issue after that, please run `npx expo-env-info` again and update your issue accordingly. It does not list an Expo or React Native version, which seems unexpected. Thanks!

I update my expo to 46.0.9 and recreated a new project by "pnpm create expo-app -t expo-template-blank-typescript", then I change the start command to `expo start --offline` but still failed. 

![image](https://user-images.githubusercontent.com/21052565/187817317-c7efd4e9-c97b-4e19-b76f-9df71e1b331b.png)

"FetchError: network timeout at: https://api.expo.dev/v2/versions/latest"
![image](https://user-images.githubusercontent.com/21052565/187817396-9207a2f5-ec8b-4049-8316-3ae8575ff240.png)

env-info：
![image](https://user-images.githubusercontent.com/21052565/187816993-5a669666-5d17-4ec5-ae76-bbbf621528ae.png)

**Comment by kantoash** [comment]
> 

hey can you just tell me how you fall back to previous version and resolve the error cause i am facing same help me!

**Comment by LyunKi** [comment]
> > 
> 
> hey can you just tell me how you fall back to previous version and resolve the error cause i am facing same help me!

Just use the previous expo SDK , such as 45.0.0

**Comment by keith-kurak** [comment]
Thanks for the additional info. Does this happen all the time for you, or is it intermittent? I have noticed it on a few systems on the latest version at various times. It seems like it does not happen if I run `npx expo start` when I'm online, and then later  run `npx expo start --offline` after disabling the network. Any additional context you can add about when it does or does not happen for you is much appreciated!

**Comment by Stevemoretz** [comment]
> Thanks for the additional info. Does this happen all the time for you, or is it intermittent? I have noticed it on a few systems on the latest version at various times. It seems like it does not happen if I run `npx expo start` when I'm online, and then later run `npx expo start --offline` after disabling the network. Any additional context you can add about when it does or does not happen for you is much appreciated!

Thank you for guiding me to this issue and sorry I didn't find it, for me `npx expo start --offline` fails if I run it both when I'm offline or online, with:

```
FetchError: network timeout at: https://api.expo.dev/v2/versions/latest
```

When I'm online I can access https://api.expo.dev/v2/versions/latest in the browser just fine, this is surely a bug.
