### ISSUE TITLE
Silent errors happens when JS has a typo BUG

### ISSUE THREAD

**Issue by fabiancarlos** [expo/expo#1891]
Hi guys, maibe i find a bug that's kind strange. The famous blue screen `could not connect to exp//...`.
Some errors on JS just crash the app on any device, emulator, simulator. To create the error, do this on the `RootNavigation.js`:
```
  _registerForPushNotifications() {
    registerForPushNotificationsAsync();

    // Watch for incoming notifications
    this._notificationSubscription = Notifications.addListener(this._handleNotification);
  }

  // normally the args will be { origin, data }
  _handleNotification = ({ wow_bug }) => {
    console.log(`Push notification ${origin} with data: ${JSON.stringify(data)}`);
  }
```
Than execute `exp start` and open on the device.
The console don't show nothing. Adb logcat either. And this is not error of internet. The Expo crashs when some errors in JS exists and silent kill the app showing the blue screen.

**Comment by fabiancarlos** [comment]
The console don't show nothing. And this is not error of internet. The Expo crashs when some errors in JS exists and silent kill the app.

**Comment by AdamJNavarro** [comment]
Hey @fabiancarlos,

Does this occur on both platforms? I see you mention adb logcat so I take it that it occurs on Android, but curious if you tested on iOS.

**Comment by fabiancarlos** [comment]
Yes, Android and IOS. I'm, using expo@25.1.0.
There is a way to debug js created? Like create manually a bundler to see when the JS code brokes @AdamJNavarro ?

**Comment by fabiancarlos** [comment]
I find out that the file `google-services.json` was not present in the root directory, i'm using Push Notifications. Strange that i never put this there.
But more strange is how expo just silence this error, this should return some error.
Thanks

**Comment by AdamJNavarro** [comment]
Thanks for the information, Fabian! Definitely agree that there is improvement for error handling here. Going to create an internal ticket for this.
