### ISSUE TITLE
Expo Go crashes in Xcode simulator on arm cpus without Rosetta installed

### ISSUE THREAD

**Issue by ottob** [expo/expo#18920]
### Summary

I just got a new MacBook with m2 processor. When I try to open Expo Go in the Xcode simulator it crashes at once with the following error in the system console:
> Process start failed with Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}

It seems the expo go binary is not a universal build, only x86_64:
```
$ file .expo/ios-simulator-app-cache/Exponent-2.25.3.tar.app/Expo\ Go
.expo/ios-simulator-app-cache/Exponent-2.25.3.tar.app/Expo Go: Mach-O 64-bit executable x86_64
```

### Workaround
It starts working if I install Rosetta, but it would be nice if this was not necessary and Expo Go was built as a universal binary instead.

### What platform(s) does this occur on?

iOS

### SDK Version

46

### Environment

```
$ uname -a
Darwin MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:25 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8110 arm64
```

### Minimal reproducible example

1. Download minimal template https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum
2. Try to open in Simulator with Expo go (without having Rosetta installed)
3. 💥

**Comment by douglowder** [comment]
There is at least one Expo Go dependency (ffi) that still requires x86_64 architecture for simulator builds.

There have been efforts to fix this and there are some hacks (e.g. https://github.com/ffi/ffi/pull/936) but your safest path is still just to use Rosetta for now.

**Comment by jonrh** [comment]
Thanks @ottob for creating the issue, finding the cause and the suggested workaround. The Expo Go app was just crashing in the iOS Simulator with no clue as to why. Seem to recall that the Rosetta install dialog popped up when running for the first time. Dismissed it and it never showeved again. Installed Rosetta and Expo Go now works as expected in the iOS Simulator.

For the record this seems to be the latest PR for the upstream fix: https://github.com/ffi/ffi/pull/968
