### ISSUE TITLE
[Android] Cannot find MainActivity, falling back to ShellAppActivity

### ISSUE THREAD

**Issue by poptocrack** [expo/expo#1892]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.2.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

### Steps to Reproduce

I'm running a detached version.
After the SDK update from 26 to 28 and precisely [this commit](https://github.com/expo/expo/commit/1bd83fc8a2def5daa78360dce16aaa4ed9b6c132#diff-9a89553ce052acfc3b547fe5095c0df4) I've got an issue
The SDK tries to get `host.exp.exponent.MainActivity`,  so there's an issue if you have changed your package name or application ID in `app/build.gradle`

### Expected Behavior

Launching the app with a different package name / appId

### Actual Behavior

Crash on startup
![capture d ecran 2018-06-19 a 16 23 41](https://user-images.githubusercontent.com/6168361/41603438-3d107ae8-73dd-11e8-98d8-eff0198f5b62.png)

**Comment by poptocrack** [comment]
So, I've made the changes you told, the app is building and launching. But I'm using firebase to handle notifications and they doesn't work since the package name has to be my custom one. In order to make it work again, I had to create another app in my firebase console.

Thanks for the help.

Last question, does changing back the package name and other stuff to `host.exp.exponent` will make conflicts during the upload the app to the PlayStore?
(app in production since 8 months now)

**Comment by esamelson** [comment]
Hi @poptocrack - as long as you keep the application ID in `app/build.gradle` the same, then your Play Store submission should not be affected. Do note, though, that you may have to send notifications through both of your firebase projects for a while until everyone has upgraded to your latest version.
