### ISSUE TITLE
Camera gives invalid uri to file

### ISSUE THREAD

**Issue by kokasmark** [expo/expo#18932]
### Summary

The camera.takepictureasync() uri point to an image that doesnt exist and cant be opened

### What platform(s) does this occur on?

iOS

### SDK Version

6.0.5

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~46.0.8 => 46.0.8
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    Expo Workflow: managed

### Minimal reproducible example

const takePicture = async () => {
    if(camera){
        const options = {quality: 1, base64: true};
        const data = await camera.takePictureAsync(options);
        console.log(data.uri);
        setImage(data.uri);
    }
  }
  if (hasCameraPermission === false) {
    return <Text>No access to camera</Text>;
  }

**Comment by keith-kurak** [comment]
Hi! I can't reproduce this with the given code- the URI looks valid on the standard expo-camera example. If you can create a [Snack](https://snack.expo.dev) that clearly demonstrates the bug, feel free to open a new issue.
