### ISSUE TITLE
`Asset.fromModule(require('./file.png')).downloadAsync()` taking 2 seconds to load 1mb file

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#18938]
### Summary

`Asset.fromModule(require('./file.png')).downloadAsync()` is taking 2 seconds to load 1mb file.
Feels like a lot, considering it's just a regular small file.

Here you can see an screenshot taken from my device, loading the Snack:

![image0](https://user-images.githubusercontent.com/1837969/187770906-5c5ef242-4e2b-4b69-bdda-2ef2aaaf9be6.png)

### What platform(s) does this occur on?

iOS

### Environment

Snack.

Testing it on last Expo Go version, on iPhone 13 mini.

### Minimal reproducible example

1. Open https://snack.expo.dev/@brodanoel/lonely-french-fries
2. Scan the code to open in your own device (it should be an iOS. I didn't tested it on Android)
3. Tap the "Tap here" button

**Comment by BrodaNoel** [comment]
This is the file, in case you need it:

![splash-screen-ph](https://user-images.githubusercontent.com/1837969/187772059-f5bcc139-2825-4a28-8bd8-f5e50957a8c8.png)


Info:

<img width="310" alt="Screen Shot 2022-08-31 at 17 06 03" src="https://user-images.githubusercontent.com/1837969/187772104-cc645eac-206b-4b07-8258-004eb46b6197.png">

**Comment by brentvatne** [comment]
I'm not sure I understand what the problem is. It takes time to download files over a network.
