### ISSUE TITLE
An error occurred while retrieving accessToken 

### ISSUE THREAD

**Issue by onka13** [expo/expo#1894]
Using Expo.Google.logInAsync without email scope, expo throws a message like this; 
"An error occurred while retrieving accessToken".

I finally found the related code here;

https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi28_0_0/host/exp/exponent/modules/api/GoogleModule.java#L299

```
Expo.Google.logInAsync({
                webClientId: "GOOGLE_OAUTH_WEB_CLIENT_ID",
                androidStandaloneAppClientId: "GOOGLE_OAUTH_ANDROID_CLIENT_ID",
                behavior: 'system',
                scopes: [
                    'profile'
                ],
            }) 
```

**Comment by esamelson** [comment]
Hi @onka13 - it looks like in the java code you've linked, the native exception is being passed into the promise rejection. Could you paste the full error message here? (maybe try `catch`ing the promise rejection and log all of the fields of the resulting error object)

Even better would be if you could provide a full example and list of steps to repro this error.

Thanks!!

**Comment by onka13** [comment]
Hi @esamelson - If you don't provide 'email' scope, google will not return a email address for you. In code there is an email process which I don't know details. There must be an IsEmpty validation because email is not mandatory.

This's the error message;
"An error occurred while retrieving accessToken"  

Step 1: 

Expo.Google.logInAsync({
                webClientId: "GOOGLE_OAUTH_WEB_CLIENT_ID",
                androidStandaloneAppClientId: "GOOGLE_OAUTH_ANDROID_CLIENT_ID",
                behavior: 'system',
                scopes: [
                    'profile'
                ],
            }) .catch(error => { console.log('error', error)})

Step 2: 
"An error occurred while retrieving accessToken"

**Comment by esamelson** [comment]
@onka13 I think I've been successful in reproducing this problem. In my `adb logcat` I see the following error:
```
06-21 13:45:32.412  2885  3386 W Auth    : [GetToken] GetToken failed with status code: INVALID_AUDIENCE
06-21 13:45:32.412  3113  4603 E TokenRequestor: You have wrong OAuth2 related configurations, please check. Detailed error: INVALID_AUDIENCE
```

Could you confirm that you see these lines as well?

I'm not seeing any obvious errors in our code that would cause this. We'll try and dig deeper when we can, but I think the best workaround for now would be for you to request `'email` scope along with `'profile'` -- when I do this everything seems to work fine.

**Comment by onka13** [comment]
Hi @esamelson , 
I didn't see any logs like as you shared above.  I'm using email scope with profile for now. 
Thanks for your support. This issue here may help others.

**Comment by esamelson** [comment]
Hi @onka13 . Glad to hear that's working for you. I'm going to reopen this as we still want to track it internally.

**Comment by esamelson** [comment]
Hi, we've made a bunch of changes to the Google module in the last year and we're closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
