### ISSUE TITLE
expo-web-browser Keep browser open when returned to app from background

### ISSUE THREAD

**Issue by kierrapalmer** [expo/expo#18948]
### Summary

Browser window should remain open when the app is reopened from the background. This works correctly when the user returns to the app from the App Drawer but the browser window will be closed if they click on the app icon. 

iOS correctly keeps the window open when navigating back to the app from the phone home screen.

View video of unexpected behavior. https://drive.google.com/file/d/1iW2jDldOgW3URTKAeH-GjYHE4f9vXLtu/view?usp=sharing

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8092744
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Minimal reproducible example

Tested on: Galaxy S10e, Galaxy S21, Pixel 5(emulator)

`import { StyleSheet, Text, View, Pressable } from 'react-native';
import * as WebBrowser from 'expo-web-browser';

export default function App() {
    const handlePressButtonAsync = async (link) => {
          WebBrowser.openBrowserAsync(link, {'createTask': false});
      };
      
    return (
        <View style={styles.container}>
            <Pressable onPress={() => handlePressButtonAsync('https://google.com')}>
                <Text >test</Text>
            </Pressable>
        </View>
    );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`

**Comment by kierrapalmer** [comment]
Any update on getting this fixed? iOS is working as expected, we just need android to do the same thing.

**Comment by zdnk** [comment]
This is still issue with Stripe for React Native

**Comment by MarchewkaMatthew** [comment]
Has anyone found a solution to this problem? I can confirm that the same thing is happening in the 49 version of expo, more details are described in this issue: https://github.com/expo/expo/issues/8072
