### ISSUE TITLE
exp hang on

### ISSUE THREAD

**Issue by iCueto** [expo/expo#1895]
Hello everybody, I have a problem on exp and Expo XDE when I publish a app, it take too much time and never end, when I exit the process, get the following error:

`[02:52:37] Unable to find an existing exp instance for this directory, starting a new one...
[02:52:49] Starting Metro Bundler on port 19001.
[02:52:49] Metro Bundler ready.
^C
Stopping packager...
[02:53:08] Metro Bundler process exited with code null
[02:53:08] Error: Metro Bundler process exited with code null
    at ChildProcess.<anonymous> (/xdl@50.4.0/src/Project.js:1213:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)`

When I try with Expo XDE, do not allow publish, the button publish appears disabled

I have installed on macOS hight Sierra:

XDE: 2.24.2

exp: 55.0.3

react-native-cli: 2.0.1
react-native: 0.55.2

expo SDK: 27.0.0

Diagnostic: https://exp-xde-diagnostics.s3.amazonaws.com/kastaco-c46970f8-c5c2-4b72-bb33-a623cd0de967.tar.gz

I’ve trying to clean cache and killall process, and don’t works…

Help, Please… Thanks…

**Comment by tcdavis** [comment]
So exp hangs when you attempt to publish and the publish button is disabled in XDE?
What OS are you using?

**Comment by lotusbleue** [comment]
Hi,

I am getting the exact same issue that iCueto described. I am also on OSX High Sierra. 

The exp build:status command returns the following:
[23:56:43] Checking if current build exists...
[23:56:48] No currently active or previous builds for this project.

My project is using
react-native-cli: 2.0.1
react-native: 0.55.2

Any thought on what the issue might be? I spent days trying to figure out but can't get this sorted out.
Would appreciate any help

**Comment by quinlanj** [comment]
@iCueto : could you run `exp publish` and let us know what that outputs?
@lotusbleue: looks like you are running a completely different command from OP. You'll need to run `exp build:android` or `exp build:ios` for a build to show up with `exp build:status` (or you can check your build status from the expo site instead)

**Comment by lotusbleue** [comment]
Hi quinlanj,

Thank you for your reply. Let me explain more accurately what I am doing.
I ran `exp build:android` and the terminal displays the following informations and then nothing happens.

```
[12:48:17] Making sure project is set up correctly...
[12:48:40] Your project looks good!
[12:48:40] Checking if current build exists...
[12:48:41] No currently active or previous builds for this project.
[12:48:42] Unable to find an existing exp instance for this directory, starting a new one...
[12:49:11] Starting Metro Bundler on port 19001.
[12:49:12] Metro Bundler ready.

```

After waiting a few hours, I ran `exp build:status` in another terminal window which returns
```
Checking if current build exists...
No currently active or previous builds for this project.

```
Eventually, nothing outputs so I aborted the process I get the following report:
```
Metro Bundler process exited with code null
Error: Metro Bundler process exited with code null
    at ChildProcess.<anonymous> (/xdl@50.4.2/src/Project.js:1213:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by sjchmiela** [comment]
Hi all!

We've run into the same issue at Software Mansion today and the problem was an empty `/etc/hosts` file after migrating from one computer to another, which led to `localhost` not being resolved to `127.0.0.1`. And `localhost` is what `exp` uses to check whether packager is running.

Please, try to run the Expo server with `exp start` and when it hangs on `Metro Bundler ready` open another terminal tab and run

```sh
curl localhost:{THE_PORT_THAT_METRO_BUNDLER_SAID_IT_USES}/status

# eg.

curl localhost:19001/status
```

and reply here with what it prints.

If it prints that it couldn't resolve `localhost`, edit `/etc/hosts` file with administrator privileges and ensure it has the following entries:

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by lotusbleue** [comment]
After following the steps you described, the command printed

`packager-status:running`

Although the expo server was running, I still tried to edit my `/etc/hosts` file and it worked!
The build is now waiting in queue on the expo server.

@sjchmiela  @quinlanj Thank you so much for your support!

**Comment by nicknovitski** [comment]
@iCueto Is the problem still happening for you on the newest version of exp?

**Comment by iCueto** [comment]
@nicknovitski Sorry, I was able to solve the problem editing the ```/etc/hosts``` file, thanks to @sjchmiela and there are not more issues.

Thanks!!!

**Comment by sjchmiela** [comment]
Fix for this undefined behavior is present in `exp@56.0.0`,  I'll close this issue tentatively, if you have any more questions feel free to ask. 🙂
