### ISSUE TITLE
Invariant Violation: requireNativeComponent: "ViewManagerAdapter_ExpoLinearGradient" was not found in the UIManager.

### ISSUE THREAD

**Issue by lordkyle0** [expo/expo#18953]
### Summary

I get this warning in my **device** Samsung S10+ android 12 but none in my emulator when I used **ExpoLinearGradient**

The native view manager required by name (ExpoLinearGradient) from NativeViewManagerAdapter isn't exported by expo-modules-core. Views of this type may not render correctly. Exported view managers: [].

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

"expo": "^46.0.9",
"expo-dev-client": "~1.2.1",
"expo-updates": "~0.14.5",
"expo-linear-gradient": "~11.4.0",

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 18.6.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: 0.18.7 => 0.18.7 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: bare

### Reproducible demo

return (

        <LinearGradient style={{ flex: 1 }} colors={["#596164", "#000000"]}>

        </LinearGradient>
    )

### Stacktrace (if a crash is involved)

This error is located at:
    in ViewManagerAdapter_ExpoLinearGradient
    in Adapter<ExpoLinearGradient> (created by NativeLinearGradient)
    in RCTView (created by View)
    in View (created by NativeLinearGradient)
    in NativeLinearGradient (created by LinearGradient)
    in LinearGradient (created by AlbumScreen)
    in AlbumScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by HomeNavigation)
    in HomeNavigation (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by BottomTabNavigator)
    in BottomTabNavigator (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by RootNavigator)
    in RootNavigator (created by Navigation)
    in AuthProvider (created by Navigation)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Navigation)
    in Navigation (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

**Comment by abdullahceylan** [comment]
This is because some of the packages (peer dependencies of 3rd parties) use a different version of `expo-linear-gradient`. You can solve this by adding the version you want to use in the `resolutions` section of `package.json`

```
  "resolutions": {
    "expo-linear-gradient": "~11.4.0"
  }
```

**Comment by lordkyle0** [comment]
> This is because some of the packages (peer dependencies of 3rd parties) use a different version of `expo-linear-gradient`. You can solve this by adding the version you want to use in the `resolutions` section of `package.json`
> 
> ```
>   "resolutions": {
>     "expo-linear-gradient": "~11.4.0"
>   }
> ```

Thanks @abdullahceylan. 
There is no error in my emulator but I still get the same error on my Android device version 12.

**Comment by Bort-777** [comment]
Faced some issues with iOS build, then **resolved** by fixing incorrect place of `expo_patch_react_imports` on `Profile.lock`. See correct place [there (Expo docs)][1].


  [1]: https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-ios

**Comment by sonipranjal** [comment]
Getting the same error on ios, using   "expo-linear-gradient": "~12.3.0" &   "expo": "^49.0.11"

**Comment by osmanbaskaya** [comment]
I am having the same issue.

**Comment by dylanngph** [comment]
Same with expo 49, expo-linear-gradient 12.3

**Comment by badalsaibo** [comment]
Having the same issue on my physical device, Android 12, "expo": "~49.0.15", "expo-linear-gradient": "~12.3.0",

**Comment by nickthelegend** [comment]
> ```
>  eas build --profile development --platform android --local
> ```

Thanks @badalsaibo this worked like charm
