### ISSUE TITLE
[docs] Improves highlighting of important notes

### ISSUE THREAD

**Issue by firas1220** [expo/expo#18969]
### Summary

Hello Expo team! Reading the documentation📚, I feel it's good, acceptable and worth it. Just one thing ☝️, as the site is quite large, sometimes a reader may need something to remember or to refresh their memory 👏. This is the role of remarks, which are not well highlighted. I found myself in big trouble because of not paying attention to some very important expressions not well exposed to my eyes when reading 👀 . Unlike many well-known websites, I think the Expo docs website doesn't have a good way of highlighting. As an example the following information which is crucial, but written as text with normal style and black color: ``Note that FCM is not currently available for expo notifications on iOS.`` (visit [link](https://docs.expo.dev/push-notifications/using-fcm/#client-setup:~:text=Note%20that%20FCM%20is%20not%20currently%20available%20for%20expo%2Dnotifications%20on%20iOS.)).
I know there are some notes, around, but they seems to be like normal, as they are wrapped inside wite/gray frame. 👓

As an example I recommend to follow some ways like making a note inside a red frame like [firebase docs](https://firebase.google.com/docs/cloud-messaging/concept-options#:~:text=Make%20sure%20that%20you%20do%20not%20use%20any%20reserved%20words%20in%20your%20custom%20key%2Dvalue%20pairs.%20Reserved%20words%20include%20%22from%22%2C%20%22notification%2C%22%20%22message_type%22%2C%20or%20any%20word%20starting%20with%20%22google%22%20or%20%22gcm.%22) or in blue like we see in [microsoft docs](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/#:~:text=App%20SDK.-,Important,-If%20you%27re%20working).

### Link to the related docs page

My topic isn't about a specific page, its general.

### Anything else?

I know you're doing a hard work, but we as community are with you 😇. I can make the changes by myself and make PR, just need to know what is your answer on this.

**Comment by amandeepmittal** [comment]
Hey @firas1220

Thanks for pointing this out.  We will try to do a better job of highlighting important stuff or gotchas.

**Comment by byCedric** [comment]
You are right! But rest assured, we are working on improved blockquote 😄 Here is an example with more emphasis: 
![image](https://user-images.githubusercontent.com/1203991/189627138-210de123-ad75-42fc-8fa9-820c4e128f7c.png)

We do need to go through the docs to differentiate warnings/info blockquote though.

**Comment by firas1220** [comment]
Hello @amandeepmittal I need help please. Its about the the note mentionee in my main msg here. I want to know if ``expo-notifications`` doesn't work with FCM or maybe its an outdated docs? 

Its urgent

**Comment by amandeepmittal** [comment]
Closing this since the issue was fixed in #19368.

Also, @firas1220, I believe we had a discussion about this in the forums post you created.
