### ISSUE TITLE
[Expo Speech] There are no language for countries

### ISSUE THREAD

**Issue by hyoretsu** [expo/expo#18964]
### Summary

Portuguese and brazilian portuguese are two very different languages, even more so when speaking them. I've tried `pt-br`, `pt-BR` and `br`, but it either speaks in the default language or (Portugal) portuguese.

### What platform(s) does this occur on?

Android, Not Applicable

### Environment

    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
    Expo Workflow: bare

### Minimal reproducible example

Any code, really.

**Comment by Kudo** [comment]
hi there! could you provide us a minimal reproducible example to further investigate.

i tried with the following example.`pt-BR` / `pt` are the same, and `br` is different. i tested on pixel 6 android 12. i'm not sure whether this is expected.

```jsx
import * as React from "react";
import { View, StyleSheet, Button } from "react-native";
import * as Speech from "expo-speech";

export default function App() {
  const speak = () => {
    const thingToSay = "Hello world";
    Speech.speak(thingToSay, { language: "pt-BR" });
  };

  return (
    <View style={styles.container}>
      <Button title="Press to hear some words" onPress={speak} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
    padding: 8,
  },
});

```
