### ISSUE TITLE
GLView fails to create surface on Android 8.0.0

### ISSUE THREAD

**Issue by lewnelson** [expo/expo#1897]
### Environment
(Diagnostic report from the [snack](https://snack.expo.io/By5VssDbQ))

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/holiday-extras-19b8450e-26a3-4fe2-928b-16cc00567e5d.tar.gz

Apps targeting iOS and Android.

### Steps to Reproduce

Reproducible snack
https://snack.expo.io/By5VssDbQ

This runs fine on the Simulator (iOS 11.2 iPhone SE), however it fails to work on my Android phone:

Device: Sony Xperia XZ Premium
Model: G8141
Android version: 8.0.0

### Expected Behavior

I expected to be able to use the `GLView` component. I expected the SurfaceContext to have been created.

### Actual Behavior

The `GLView.NativeView` `onSurfaceCreate` prop was never being called. I traced it back to `node_modules/expo/src/GLView.js:120` and then had a look into the native java code, but couldn't get any further there.

### Reproducible Demo

https://snack.expo.io/By5VssDbQ
If it works you should see the alert.

**Comment by tsapeta** [comment]
Hey @lewnelson,
I've tried your demo and I noticed that your GraphicsView is of zero size - in this case Android's TextureView is not creating a SurfaceTexture, thus `onContextCreate` is not called.

Also, this topic will tell you more why its size is zero: https://stackoverflow.com/a/48865616
So, as said in that topic, it's not a bug, it's a feature ¯\_(ツ)_/¯
