### ISSUE TITLE
Reanimated library not in docs

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1898]
On the SDK 28 [announcement post](https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530), it mentions that the reanimated library has been added, but there is no documentation on how to use it. Is the idea that we add the library via NPM and use as per usual, or is it available from within expo somewhere?

**Comment by brentvatne** [comment]
you can just import it and use it w/o installing package as it's included in expo sdk. i didn't write up a doc for it yet but you can read the readme at https://github.com/kmagiera/react-native-reanimated.

**Comment by brentvatne** [comment]
@cruzach - can you add a docs page for reanimated similar to the RNGH one? also note the changes made to the RNGH one in https://github.com/expo/expo/pull/4815
