### ISSUE TITLE
React native drawer navigation crashes 

### ISSUE THREAD

**Issue by Emyboy** [expo/expo#18980]
### Summary

Any time I add the react native drawer navigation from [Here](https://reactnavigation.org/docs/drawer-based-navigation/) my expo app crashes with no errors on the console.

I generated a new expo project and the same thing was happening.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo": "^46.0.9",
"native-base": "^3.4.12",  (I didn't add this to the new project)
"react": "18.0.0",
"react-native": "^0.69.5",
"react-native-gesture-handler": "~2.5.0",
"react-native-pager-view": "5.4.24",
 "react-native-reanimated": "~2.9.1",
"@react-navigation/drawer": "^6.4.4",

### Environment

Node v16.15.0
NPM 8.7.0

Windows 11 Home v21H2

### Reproducible demo

1. create a new expo project using the expo-cli
2. follow the installation guide [Here](https://reactnavigation.org/docs/getting-started)
3. Install the drawer navigation from [Here](https://reactnavigation.org/docs/drawer-based-navigation/)
4. Restart the application on the expo-client

**Comment by Emyboy** [comment]
What the new expo project looked like 👇🏽

![image](https://user-images.githubusercontent.com/34845973/188321329-04deb598-a76c-49a2-8881-928a54be11ef.png)

**Comment by DoctorJohn** [comment]
The installation guide you linked also says that one should install `react-native-screens` and `react-native-safe-area-context` by running `npx expo install react-native-screens react-native-safe-area-context`. It appears your project is missing these dependencies.

**Comment by amandeepmittal** [comment]
Hey @Emyboy,

From the package versions, you shared, seems like ` @react-navigation/native` is missing from it. You'll have to install it and follow the instructions given on the [React Navigation getting started guide](https://reactnavigation.org/docs/getting-started/). Also, as mentioned by @DoctorJohn, please look into all the [required dependencies](https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-an-expo-managed-project) and ensure they are installed in your project before running the development server.

**Comment by pranaygoel02** [comment]
Even I am having a similar issue. The Expo app is crashing everytime I try to navigate to the Drawer navigator.

**Comment by amandeepmittal** [comment]
@hafizip00, if you can share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and other required information in an issue, I can take a look.

**Comment by MurtazaEliyas** [comment]
I am facing a similar issue. 
I created a fresh app using "npx create-expo-app my-app"
Followed the basic react-navigation installation steps from [here](https://reactnavigation.org/docs/getting-started/) and [here](https://reactnavigation.org/docs/drawer-based-navigation)

`import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createDrawerNavigator } from "@react-navigation/drawer";

const Drawer = createDrawerNavigator();
export default function App() {
    return (
        <NavigationContainer>
            <Drawer.Navigator>
                <Drawer.Screen
                    name="Feed"
                    component={() => {
                        return <Text>Page One</Text>;
                    }}
                />
                <Drawer.Screen
                    name="Article"
                    component={() => {
                        return <Text>Page Two</Text>;
                    }}
                />
            </Drawer.Navigator>
        </NavigationContainer>
        // <Text>Test</Text>
    );
}`

and this is the package.json 

`{
  "name": "my-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "expo": "~46.0.16",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-native": "0.69.6",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
`

**Comment by amandeepmittal** [comment]
> <Drawer.Navigator>

Just to confirm, are you wrapping your `<Drawer.Navigator>` inside the `<NavigationContainer>` as mentioned in the example from the second link you shared: https://reactnavigation.org/docs/drawer-based-navigation/#minimal-example-of-drawer-based-navigation?

I don't see an issue when reproducing your example and it's working: https://snack.expo.dev/@amanhimself/drawer-nav-example.

**Comment by MurtazaEliyas** [comment]
Hi @amandeepmittal 
Thanks for your response. 
Yes I am wrapping it within `<NavigationContainer>` . I have edited above just for reference.

There is one more thing I noticed. This same code I copied to 3 of my collegues dev environment and it works just fine. 
I am starting to doubt there is something in my dev environment although not sure where to start looking.

**Comment by MurtazaEliyas** [comment]
I am not sure what the issue is. I removed react navigation completely from the app and reinstalled again and it started to work. Not sure what I missed the first time.

Fo future reference of anyone facing similar issues, they can try removing all react navigation packages and reinstall following the guide step by step. (Hope this helps)

**Comment by FilipeGods** [comment]
I encountered the same error, and didn't find any concrete solution or explanation to it.
Looking on the open issues of their repository, there's an open one about this, I guess it will be fixed in a future version some time.

The issue: https://github.com/react-navigation/react-navigation/issues/10950

Until further notice, I just tried downgrading my app to find a version where the error not occurs, and 6.3.0 seems to be the latest without the error.

npm install @react-navigation/drawer@6.3.0


And if helps someone, the rest of my dependencies:
"dependencies": {
        "@react-native-community/masked-view": "^0.1.11",
        "@react-navigation/drawer": "^6.3.0",
        "@react-navigation/native": "^6.0.13",
        "@react-navigation/native-stack": "^6.9.1",
        "expo": "~46.0.16",
        "expo-status-bar": "~1.4.0",
        "react": "18.0.0",
        "react-native": "0.69.6",
        "react-native-gesture-handler": "~2.5.0",
        "react-native-reanimated": "~2.9.1",
        "react-native-safe-area-context": "4.3.1",
        "react-native-screens": "~3.15.0"
      },

**Comment by clairerob** [comment]
Thank you, @FilipeGods ! This is the first react native app I've tried to build myself and I couldn't for the life of me figure out what I was doing wrong this morning...downgraded to 6.3.0 and everything works fine now.

**Comment by hafizip00** [comment]
> @hafizip00, if you can share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and other required information in an issue, I can take a look.

Thanks, brother it's solved I just removed the cache then installed again.

**Comment by alizaeda** [comment]
I have the same issue in production only

**Comment by hafizip00** [comment]
@alizaeda

**Comment by alizaeda** [comment]
Already tried, The issue appears in the production build

**Comment by alizaeda** [comment]
Its working, Thank's a lot bro

**Comment by devmeireles** [comment]
> npm install @react-navigation/drawer@6.3.0

honestly I don't like to use previously package versions but it was the case, I was about to cry dude hahaha many thanks, you saved it!
