### ISSUE TITLE
Camera crashing when using barcode scanned event

### ISSUE THREAD

**Issue by mister-conor** [expo/expo#18996]
### Summary

Our application is crashing when using expo-camera on Android 12. Through trial and error, removing the useCamera2Api (https://docs.expo.dev/versions/v46.0.0/sdk/camera/#usecamera2api) seems to prevent the crash. We are using the camera to scan barcodes and the crash only seems to happen when the barcode scanned event has a handler. The camera shows fine but when a scan occurs or the camera is closed, then it crashes the application. I created a new blank expo app and installed expo-camera to ensure it was not an issue with our application. See example below.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    Expo Workflow: managed

### Minimal reproducible example

import { Camera } from 'expo-camera';
import { useEffect, useState } from 'react';
import { Button, StyleSheet, View } from 'react-native';

export default function App() {
  const [hasPermission, setHasPermission] = Camera.useCameraPermissions();
  const [isVisible, setIsVisible] = useState(false);
  const [isScanned, setIsScanned] = useState(false);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestCameraPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  useEffect(() => {
    if (isScanned) {
      const scanEnabledTimeout = setTimeout(() => setIsScanned(false), 1000);
      return () => clearTimeout(scanEnabledTimeout);
    }
  }, [isScanned]);

  const barcodeScannedHandler = ({ data }) => {
    setIsScanned(true);
    console.log(data)
  };

  if (hasPermission === null) {
    return <View />;
  }

  return (
    <View style={styles.container}>
      <Button onPress={() => setIsVisible(true)} title='Open Camera' />
      {isVisible ? <Camera style={StyleSheet.absoluteFill} onBarCodeScanned={isScanned ? undefined : barcodeScannedHandler}
          useCamera2Api>
        <View style={styles.buttonContainer}>
          <Button onPress={() => setIsVisible(false)} title='Close Camera'/>
        </View>
      </Camera> : null}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center'
  },
  buttonContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginVertical: 50
  }
});

**Comment by Kudo** [comment]
i can confirm the crash with the example (there were some incorrect code in your example, so i revised a little bit)

```jsx
import { Camera } from "expo-camera";
import { useEffect, useState } from "react";
import { Button, StyleSheet, View } from "react-native";

export default function App() {
  const [hasPermission, setHasPermission] = Camera.useCameraPermissions();
  const [isVisible, setIsVisible] = useState(false);
  const [isScanned, setIsScanned] = useState(false);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestCameraPermissionsAsync();
      setHasPermission(status === "granted");
    })();
  }, []);

  useEffect(() => {
    if (isScanned) {
      const scanEnabledTimeout = setTimeout(() => setIsScanned(false), 1000);
      return () => clearTimeout(scanEnabledTimeout);
    }
  }, [isScanned]);

  const barcodeScannedHandler = ({ data }) => {
    setIsScanned(true);
    console.log(data);
  };

  if (hasPermission === null) {
    return;
  }

  return (
    <View style={styles.container}>
      {isVisible ? (
        <Camera
          style={StyleSheet.absoluteFill}
          onBarCodeScanned={isScanned ? undefined : barcodeScannedHandler}
          useCamera2Api
        />
      ) : null}
      <View style={styles.buttonContainer}>
        <Button onPress={() => setIsVisible(true)} title="Open Camera" />
        <Button onPress={() => setIsVisible(false)} title="Close Camera" />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonContainer: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    marginVertical: 50,
  },
});
```

tested on android 12, open/close camera a couple times will crash the app with the follow NPE stacktrace:

```
                         E  FATAL EXCEPTION: main
                         E  Process: dev.expo.kudo.sdk46, PID: 26346
                         E  java.lang.NullPointerException: Attempt to invoke virtual method 'android.media.Image$Plane[] android.media.Image.getPlanes()' on a null object reference
                         E      at com.google.android.cameraview.Camera2$4.onImageAvailable(Camera2.java:173)
                         E      at android.media.ImageReader$1.run(ImageReader.java:837)
                         E      at android.os.Handler.handleCallback(Handler.java:938)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loopOnce(Looper.java:201)
                         E      at android.os.Looper.loop(Looper.java:288)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7870)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

@lukmccall could you take a look when you get a chance?

**Comment by lukmccall** [comment]
Unfortunately, I've some bad news. It looks like a bug in the system camera code. 

Here is a code from which the exception is thrown:
![image](https://user-images.githubusercontent.com/9578601/189342847-bf8c366c-bf0d-44c8-916b-3c165c2a91c1.png)

`reader.acquireNextImage()` returns `null`, because the camera was unmounted by the React Native, but the camera code still tries to receive something from it (line `Plane[] planes = image.getPlanes();`). In my opinion, that is incorrect. 
Additional, `acquireNextImage` can return null what was documented in the https://developer.android.com/reference/android/media/ImageReader#acquireNextImage().

**Comment by Kudo** [comment]
it looks like the code is from our fork here: https://github.com/expo/cameraview/blob/54c24f937fdca1b94ab9fc303d5533d81b9ce8e8/cameraview/src/main/api21/com/google/android/cameraview/Camera2.java#L172. any changes we could fix the NPE in our fork?

**Comment by lukmccall** [comment]
We can check if the `reader.acquireNextImage ` returns null if so we can ignore it.

**Comment by mister-conor** [comment]
Any progress on this issue?

**Comment by lukmccall** [comment]
We have recently introduced a new version of the camera ([read more)](https://expo.dev/changelog/2024/05-07-sdk-51#next-camera-and-sqlite-apis-are-now-the-defaults), and we will no longer maintain the old version. It appears that the new implementation has already resolved your issue! However, please feel free to open a new issue if you encounter a similar problem with our new implementation.
