### ISSUE TITLE
Image picker issues on Android

### ISSUE THREAD

**Issue by josealfonsoweb** [expo/expo#1899]
ImagePicker.launchCameraAsync() do not seem to work on Android (expecially in expo, sometimes standalone apps either). The permissions are requested correctly, but the async calls never return and the view for taking/picking photos never appears. It return this:
{
   framesToPop: 1,
   code: "EUNSPECIFIED"
}
Permissions have been put into the app.json. Not sure what I am missing... 

"permissions": [
        "CAMERA",
        "CAMERA_ROLL",
        "READ_INTERNAL_STORAGE",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ],

ImagePicker.launchImageLibraryAsync() works well...

please follow the next steps:

1) you should have Expo App on android (last version EXPO)
2) then go to https://snack.expo.io/@josealfonsoweb/imagepicker-imageeditor
3) Press both buttons
4) when you press the second button you should get the error on some devices 

![screenshot_2018-06-20-23-33-08](https://user-images.githubusercontent.com/11999600/41696575-c24c0992-74e2-11e8-9c98-5dd2d45d3544.png)

**Comment by jimmylee** [comment]
Does your code still run into issues without the image resizing code? What happens when you follow our most basic example? https://docs.expo.io/versions/latest/sdk/imagepicker. Your code looks like it should just work so I think we'll need to investigate this further.

Thank you for sharing a Snack.

**Comment by josealfonsoweb** [comment]
Yes, I still have the same error, the size of the image is not the problem here ... the most basic example works, but it is not relevant because it does not use ImagePicker.launchCameraAsync () ... I think many people have the same problem error with this function ... Please try the code on several devices, I'm sure you'll get the error in some of them

**Comment by josealfonsoweb** [comment]
if I run Permissions.getAsync () I get "granted". I think the permissions are not the real problem here. it must be an error of ImagePicker.launchCameraAsync () on some devices.

Despite getting permission with Permissions.getAsync () I got the same error:
{
"fremeToPop": 1,
"Code"; "EUNSPECIFIED"
}

Can somebody help? Can somebody fix this?

**Comment by xcarpentier** [comment]
Same for an app I developed and update to sdk 28

**Comment by flexarts** [comment]
+1, on Samsung Tab S2 the `ImagePicker.launchCameraAsync() ` Call never returns.
I am on SDK 27 and `Permissions.getAsync()` was used successfully for granting both `CAMERA` and `CAMERA_ROLL` permission. I do not even get the error mentioned above ``("Code"; "EUNSPECIFIED")`.
No problems on IOS though!

**Comment by lucasharada** [comment]
Same for the app I developed and updated from SDK 26 to SDK 28.

**Comment by schie** [comment]
Any updates on this?

**Comment by clarktank** [comment]
problem solved:
In addtion to CAMERA permission you have to also add CAMERA_ROLL permission.
```
await Permissions.askAsync(Permissions.CAMERA);
await Permissions.askAsync(Permissions.CAMERA_ROLL);
```
I think most people like myself add CAMERA but forget to add CAMERA_ROLL.

**Comment by clarktank** [comment]
I think you can close this bug.

**Comment by sjchmiela** [comment]
Thanks, @clarktank for providing the solution! 🙂 Closing as suggested.
