### ISSUE TITLE
 undefined is not a function (evaluating 'reactAPIs[typeof  Symbol ==='function'? Symbol.iterator: '@@iterator']()')

### ISSUE THREAD

**Issue by jalalat** [expo/expo#190]
I get this error message when i create a new project with following project dependencies:

>  undefined is not a function (evaluating 'reactAPIs[typeof  Symbol ==='function'? Symbol.iterator: '@@iterator']()')

```
"dependencies": {
    "babel-polyfill": "^6.23.0",
    "expo": "16.0.0",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",
    "react-native-elements": "^0.11.2",
    "react-navigation": "^1.0.0-beta.9"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint-config-rallycoding": "^3.2.0"
  }
```

**Comment by satya164** [comment]
> `"babel-polyfill": "^6.23.0",`

Probably this is the cause

**Comment by jalalat** [comment]
I added babel-polyfill after i got the error. If you remove the package the error still remains. Problem is in babel-eslint.

**Comment by brentvatne** [comment]
sounds like you fixed the problem? If not I guess you need to make sure babel-eslint version is compatible with babel version

**Comment by joncursi** [comment]
@jalalat what did you do to solve this problem?

**Comment by bermann** [comment]
@joncursi @jalalat Have you solved this?
