### ISSUE TITLE
Camera in some LG Devices doesn't work - Blank Screen

### ISSUE THREAD

**Issue by Gedoz** [expo/expo#19009]
### Summary

Hello,

I have an app that has more than 500 users in production, but there are some isolated cases with LG devices where the camera just gets a black screen. User has already tested it in other applications such as Facebook, Whatsapp and Instagram and the camera works normally.

Model: LM-X210

Error from Sentry below:
![Captura de Tela 2022-09-06 às 15 39 34](https://user-images.githubusercontent.com/19317789/188715630-e3931cbc-f736-4492-8c49-c089ea0149ac.png)

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.13.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 13, 26, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 2.0.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

`import React, { useState, useEffect, useRef } from "react";
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  Linking,
  Dimensions,
  Modal,
  Image,
  ActivityIndicator
} from "react-native";
import { Camera } from "expo-camera";
import { useNavigation } from "@react-navigation/native";
import ScalableImage from "react-native-scalable-image";
import { Ionicons } from "@expo/vector-icons";
import theme from "../../styles/theme";
import ButtonComponent from "../../components/button.component";
import HeaderComponent from "../../components/header.component";
import Slider from "@react-native-community/slider";
import { useIsMountedRef } from "../../shared/helper";
import { Container } from "../../styles/helper";

const cameraIllustration = require("../../../assets/camera-illustration.png");

const { width: D_WIDTH } = Dimensions.get("window");
const CAMERA_SIZE = D_WIDTH * 0.8;

const CameraScreen = ({ route }) => {
  const { routeName, secretKey } = route.params;

  const navigation = useNavigation();
  const isMounted = useIsMountedRef();

  const [tankingPicture, setTakingPicture] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [hasPermission, setHasPermission] = useState(null) as any;
  const [zoom, setZoom] = useState(0);
  const [type, setType] = useState(Camera.Constants.Type.back);
  const [imageUri, setImageUri] = useState("");
  const camera = useRef<Camera>(null);

  const snap = async () => {
    if (camera) {
      setTakingPicture(true);
      let photo = await camera.current?.takePictureAsync({
        quality: 0.5,
        isImageMirror: true,
        skipProcessing: true
      });
      setTakingPicture(false);
      if (photo) {
        if (routeName) {
          navigation.navigate(routeName, { imageUri: photo.uri, secretKey });
        } else {
          navigation.goBack();
        }
        // setImageUri(photo.uri);
      }
    }
  };

  useEffect(() => {
    if (isMounted) {
      requestPermissions();
    }
  }, []);

  const requestPermissions = async () => {
    const { status, canAskAgain } =
      await Camera.requestCameraPermissionsAsync();
    if (status !== "granted" && !modalVisible) {
      setModalVisible(true);
      setHasPermission(false);
      return;
    }

    if (!canAskAgain && status !== "granted") {
      await Linking.openSettings();
    }

    setHasPermission(status === "granted");
  };

  if (hasPermission === null) {
    return <View />;
  }

  if (hasPermission === false) {
    return (
      <View style={{ flex: 1 }}>
        <Modal
          animationType="slide"
          visible={modalVisible}
          onRequestClose={() => setModalVisible(!modalVisible)}
        >
          <Container backgroundColor={theme.colors.themeColor}>
            <View style={styles.notAuthorizedViewContainer}>
              <View style={styles.notAuthorizedViewImage}>
                <ScalableImage
                  source={cameraIllustration}
                  width={D_WIDTH * 0.75}
                />
              </View>
              <Text style={styles.notAuthorizedText}>
                Você não tem permissões para usar a câmera
              </Text>
            </View>
            <View style={styles.notAuthorizedViewFooter}>
              <ButtonComponent
                title={"Permitir"}
                onPress={() => requestPermissions()}
              />
            </View>
          </Container>
        </Modal>
      </View>
    );
  }

  return (
    <Container style={styles.container}>
      <HeaderComponent title="Tirar foto" />
      {imageUri ? (
        <Image
          source={{ uri: imageUri }}
          resizeMode="cover"
          style={styles.image}
        />
      ) : (
        <View style={styles.cameraContainer}>
          <View style={styles.cameraBox}>
            <Camera
              ref={camera}
              style={styles.camera}
              type={type}
              zoom={zoom}
              ratio={"1:1"}
            />
          </View>
          <Slider
            style={styles.cameraZoom}
            minimumValue={0}
            maximumValue={1}
            onValueChange={(value) => setZoom(value)}
            minimumTrackTintColor={theme.colors.themeColor}
            maximumTrackTintColor={theme.colors.textSecondary}
          />
        </View>
      )}
      <View style={styles.footer}>
        <View style={styles.col}></View>
        <View style={styles.col}>
          {imageUri ? (
            <TouchableOpacity
              onPress={() => {
                if (routeName) {
                  navigation.navigate(routeName, { imageUri, secretKey });
                } else {
                  navigation.goBack();
                }
              }}
              style={styles.snapButton}
            >
              <Ionicons
                name={"checkmark-outline"}
                size={32}
                color={theme.colors.themeColor}
              />
            </TouchableOpacity>
          ) : (
            <TouchableOpacity
              style={[styles.snapButton, tankingPicture && { opacity: 0.6 }]}
              onPress={() => snap()}
              disabled={tankingPicture}
            >
              {tankingPicture && (
                <ActivityIndicator size={32} color={theme.colors.themeColor} />
              )}
            </TouchableOpacity>
          )}
        </View>
        <View style={[styles.col, styles.colRight]}>
          <TouchableOpacity
            disabled={tankingPicture}
            onPress={() => {
              setType(
                type === Camera.Constants.Type.back
                  ? Camera.Constants.Type.front
                  : Camera.Constants.Type.back
              );
            }}
          >
            <Ionicons
              name="refresh-outline"
              size={24}
              color={theme.colors.themeColor}
            />
          </TouchableOpacity>
        </View>
      </View>
    </Container>
  );
};

export default CameraScreen;

const styles = StyleSheet.create({
  container: {
    backgroundColor: theme.colors.dark,
    justifyContent: "space-between"
  },
  header: {
    justifyContent: "flex-end",
    alignItems: "flex-start",
    flexDirection: "row",
    paddingHorizontal: 32,
    paddingVertical: 16
  },
  footer: {
    justifyContent: "flex-end",
    alignItems: "center",
    flexDirection: "row",
    padding: 32
  },
  buttons: {
    ...StyleSheet.absoluteFillObject
  },
  col: {
    flex: 1
  },
  colRight: {
    alignItems: "flex-end"
  },
  snapButton: {
    width: 64,
    height: 64,
    borderWidth: 3,
    borderColor: theme.colors.themeColor,
    borderRadius: 32,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center"
  },
  camera: {
    ...StyleSheet.absoluteFillObject
  },
  cameraContainer: {
    marginVertical: 16,
    width: CAMERA_SIZE,
    alignSelf: "center"
  },
  cameraBox: {
    width: CAMERA_SIZE,
    height: CAMERA_SIZE,
    borderRadius: 12,
    overflow: "hidden"
  },
  cameraZoom: {
    width: CAMERA_SIZE,
    marginTop: 10,
    height: 40
  },
  buttonContainer: {
    flex: 1,
    backgroundColor: "transparent",
    flexDirection: "row",
    margin: 20
  },
  text: {
    fontSize: 18,
    color: "white"
  },
  image: {
    width: CAMERA_SIZE,
    height: CAMERA_SIZE,
    alignSelf: "center",
    borderRadius: 12,
    overflow: "hidden"
  },
  notAuthorizedText: {
    fontFamily: "Poppins",
    fontSize: 14,
    marginBottom: 16,
    color: theme.colors.textSecondary,
    textAlign: "center",
    maxWidth: "75%"
  },
  notAuthorizedViewImage: {
    marginBottom: 32
  },
  notAuthorizedViewContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32
  },
  notAuthorizedViewFooter: {
    paddingHorizontal: 32,
    paddingVertical: 16
  }
});
`

**Comment by keith-kurak** [comment]
Hi @Gedoz - if you can provide a minimal reproducible demo as a Snack or repo, that would make it much easier for someone to try to reproduce the issue. Try to narrow the demo down to the minimal amount of code necessary. For instance, you likely need just a button for `takePictureAsync`, very few styles, no navigation, etc. If you can create such a demo, feel free to submit a new issue. Thank you!
