### ISSUE TITLE
Image File Disappears After Updating or After Some Time

### ISSUE THREAD

**Issue by JiwonJeong414** [expo/expo#19017]
### Summary

Hello, I am new to expo and I basically have an app that gets image from the user using the ImagePicker component and store it in a Banner for them to see. However, every time I update the app on App Store or after some time passes, the image file seems to disappear. Does anyone have a solution for this? 

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044     
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ^46.0.0 => 46.0.10      
      react: 18.0.0 => 18.0.0       
      react-dom: 18.0.0 => 18.0.0   
      react-native: 0.69.5 => 0.69.5

      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

const ImageInput = ({ imageUri, onChangeImage }) => {
  useEffect(() => {
    const retrieveImage = async () => {
      let retrieveImage = await AsyncStorage.getItem("Image");
      retrieveImage = JSON.parse(retrieveImage);
      if (retrieveImage == null) onChangeImage(null);
      else onChangeImage(retrieveImage);
    };
    requestPermision();
    retrieveImage();
  }, []);

  const requestPermision = async () => {
    const { granted } = await ImagePicker.requestMediaLibraryPermissionsAsync();
  };

  const handlePress = () => {
    if (!imageUri) selectImage();
    else
      Alert.alert("Delete", "Are you sure you want to delete this image?", [
        { text: "Yes", onPress: deleteImage },
        { text: "No" },
      ]);
  };

  const deleteImage = async () => {
    await AsyncStorage.removeItem("Image");
    onChangeImage(null);
  };

  const selectImage = async () => {
    try {
      const result = await ImagePicker.launchImageLibraryAsync({
        quality: 0.2,
        allowsEditing: true,
        aspect: [654, 489],
      });
      // console.log(result.uri);
      if (!result.cancelled) {
        await AsyncStorage.setItem("Image", JSON.stringify(result.uri));
        onChangeImage(result.uri);
      }
    } catch (error) {
      console.log("Error reading an image", error);
    }
  };

  return (
    <TouchableWithoutFeedback onPress={handlePress}>
      <View
        style={{
          height: moderateScale(244.5),
          width: moderateScale(327),
          borderRadius: moderateScale(24),
          marginTop: moderateScale(45),
          alignItems: "center",
          backgroundColor: "gray",
          justifyContent: "center",
          overflow: "hidden",
        }}
      >
        {!imageUri && <MaterialCommunityIcons name="camera" size={40} />}
        {imageUri && (
          <Image
            style={{ width: "100%", height: "100%" }}
            source={{ uri: imageUri }}
            onError={() => Alert.alert(imageUri)}
          />
        )}
      </View>
    </TouchableWithoutFeedback>
  );
};

**Comment by young81k** [comment]
I know this is closed. But were you able to find the solution for this? I am dealing with the same issue for the app that's already deployed in production.
