### ISSUE TITLE
Symlink Issues from SDK 44 to 46

### ISSUE THREAD

**Issue by lucksp** [expo/expo#19014]
### Summary

I started a new mobile app project and since we have our own mobile components for reusability, we also use symlinking from the local component to the Expo app to make sure it's being developed properly.  We have successfully linked prior Expo apps using SDK `44`, but in this new project, we decided to use the most recent `46`.  It seems when [I update the `metro.config` file](https://docs.expo.dev/guides/monorepos/#modify-the-metro-config) the same as before, the bundler crashes.

This issue has been seen: 
- on my computer with existing project starting on SDK44 where it was working.  On updating to SDK46, it failed
- on my coworkers computer when I asked if he can replicate
- our shared "template" repo with SDK 46
- on a separate/new barebones Expo managed workflow project (see repo link below)

default metro.config
```js
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

// const workspaceRoot = path.resolve(__dirname, '../myComponentLib');  // this gets uncommented when using a link
const defaultConfig = getDefaultConfig(__dirname);

defaultConfig.transformer.babelTransformerPath = require.resolve(
  'react-native-svg-transformer',
);

const assetExts = defaultConfig.resolver.assetExts;
const sourceExts = defaultConfig.resolver.sourceExts;

defaultConfig.resolver = {
  assetExts: assetExts.filter((ext) => ext !== 'svg'),
  sourceExts: [...sourceExts, 'svg'],
};
defaultConfig.resolver.nodeModulesPaths = [
  path.resolve(__dirname, 'node_modules'),
  // path.resolve(workspaceRoot, 'packages/mobile/node_modules'), // this gets uncommented when using a link
];
// defaultConfig.watchFolders = [path.resolve(workspaceRoot)]; // this gets uncommented when using a link

module.exports = defaultConfig;
```

When I use the `metro.config` like above, it's fine.  But if I uncomment the 3 lines notes, it just crashes Expo.

**I am curious, is there a difference in linking between the different SDKs now?**. I linked to the Expo docs above where we got the linking working as expected in 44.

### What platform(s) does this occur on?

iOS

### Environment

 ~/dev/expo-native-symlink   main  npx expo-env-info
npx: installed 2 in 1.682s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/lucksp/expo-native-symlink

**Comment by byCedric** [comment]
Hi @lucksp! I'd be happy to dig into why this is happening, but the repro you provided contains a simple non-monorepo Expo project, without the `packages/mobile/node_modules`.

Can you provide an example of the full setup you are using?

To comment on some points you mentioned:

> I am curious, is there a difference in linking between the different SDKs now?
There always are changes when the React Native version is updated in the Expo SDK. Going from SDK 44 to 46 means you are going from RN `0.64.3` to RN `0.69.5`, which includes a new Metro version. That might have changed some behavior.

> We have successfully linked prior Expo apps using SDK `44`
Generally speaking, Metro **does not** support symlinks at all ([see issue #1](https://github.com/facebook/metro/issues/1)). You can get this to work with 3rd party tooling like [RNX kit](https://microsoft.github.io/rnx-kit/docs/tools/metro-resolver-symlinks), but your mileage may vary with that.

There have been some additions to the docs that you linked, including a new property and some context for each property setting. I would recommend checking that out too.

**Comment by lucksp** [comment]
> Can you provide an example of the full setup you are using?

Unfortunately, this is a work repo and the "full setup" is private...


We'll double check the new property & context...

**Comment by byCedric** [comment]
The repro doesn't need to include the actual code for your packages :) As long as it's _a package_ with the structure you are using.

**Comment by lucksp** [comment]
Wow, the reason for this is hidden well inside the docs: https://docs.expo.dev/guides/monorepos/#modify-the-metro-config

Scroll down to the section:

> Why do we need to watch all the files with the monorepo?

Their example to watch scoped package names does the trick:

```
// If your monorepo tooling can give you the list of monorepo workspaces linked
// in your app workspace, you can automate this list instead of hardcoding them.
const monorepoPackages = {
  '@acme/api': path.resolve(workspaceRoot, 'packages/api'),
  '@acme/components': path.resolve(workspaceRoot, 'packages/components'),
};
```
