### ISSUE TITLE
Android build error "com.swmansion.reanimated.BuildConfig is defined multiple times" with productFlavors

### ISSUE THREAD

**Issue by sylvain-abadie** [expo/expo#19021]
### Summary

**Prerequisites**: expo-dev-client, react-native-reanimated, expo-46.

Build fails as soon as I add multiple buildFlavors on Android as recommended [here](https://docs.expo.dev/build-reference/variants/#example-configuring-development-and-production-variants-in-1)

The vendored version of reanimated used for the expo-dev-menu seems to be responsible:
<img width="1717" alt="Screen Shot 2022-09-07 at 10 02 57 AM" src="https://user-images.githubusercontent.com/5574617/188937437-731410e9-1b0e-40bd-91b7-058ede9209f2.png">
Most of reanimated is prefixed with `devmenu` in the vendoring scripts here: https://github.com/expo/expo/blob/19ba1a2449b0be59dcf13313f738b05032749253/tools/src/commands/Vendor.ts#L94 
I suspect the package in AndroidManifest is not properly renamed. 

I don't know why the issue is not present when building without buildFlavors... 

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

    "expo": "~46.0.9",
    "expo-dev-client": "^1.2.1", 
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-reanimated": "^2.10.0",

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/sylvain/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-29 | ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: bare

### Reproducible demo

Here is a bare-minimum project with the issue: https://github.com/sylvain-abadie/expo-build-issue

Added react-native-reanimated, expo-dev-client and 2 different buildFlavors. 

Open with Android Studio and build in `developmentDebug` build variant. 

### Stacktrace (if a crash is involved)

> Task :app:mergeDexDevelopmentDebug FAILED
AGPBI: {"kind":"error","text":"Type com.swmansion.reanimated.BuildConfig is defined multiple times: /Users/sylvain/Workspace/my-app/node_modules/react-native-reanimated/android/build/.transforms/7121cfff974edddb8a3ba6532bd9159d/transformed/debug/com/swmansion/reanimated/BuildConfig.dex, /Users/sylvain/Workspace/my-app/android/app/build/intermediates/external_libs_dex/developmentDebug/mergeExtDexDevelopmentDebug/classes.dex","sources":[{"file":"/Users/sylvain/Workspace/my-app/node_modules/react-native-reanimated/android/build/.transforms/7121cfff974edddb8a3ba6532bd9159d/transformed/debug/com/swmansion/reanimated/BuildConfig.dex"}],"tool":"D8"}

**Comment by esamelson** [comment]
Hi @sylvain-abadie -- thanks for the thorough report and reproducible demo. I was able to reproduce this and I think that the cause of the issue is the `debuggable false` gradle config you've added for the development flavor, rather than the build flavors themselves. We'll look into this, and in the meantime a workaround could be to remove that config for now.

**Comment by sylvain-abadie** [comment]
Hi @esamelson! Indeed, thanks for the workaround! Could you tell me why  `debuggable false` leads to this issue? 

For context, we've been using `debuggable false` to upload a build with the dev client to the PlayStore (we use these builds to test PRs internally, and getting updates through the PlayStore is very convenient).
