### ISSUE TITLE
[11:31:26] zlib: unexpected end of file

### ISSUE THREAD

**Issue by StudioAleph** [expo/expo#1902]
When run exp init Loactions it gives me this error :(

![2018-06-21_11-31-44](https://user-images.githubusercontent.com/38176913/41703006-30d3bb12-7547-11e8-9b02-7daf190779c2.jpg)

npm version: 6.1.0

exp version: 55.04

**Comment by qoli** [comment]
try https://github.com/expo/expo/issues/1905

**Comment by StudioAleph** [comment]
when I choose the blank project in other option it doesn't give this error but I don't want second option

**Comment by StudioAleph** [comment]
it gives this error  when I choose the blank project in other option it doesn't give this error and project build correctly but I don't want the second option

**Comment by esamelson** [comment]
@StudioAleph have you tried either of the solutions that @jimmylee suggested?

> The solution seems to be
> 
> * Deleting the `.expo` or `.exponent` folder
> * Reinstalling `exp`

**Comment by terribleben** [comment]
Going to close this because it seems like @jimmylee's solution is acceptable for others with this problem. Let us know if you're still having trouble. Thanks!

**Comment by msmaromi** [comment]
tried delete `.expo` still not luck for me

**Comment by quinlanj** [comment]
@msmaromi there is an .expo folder at both the user root and the project root (ie) `~/.expo` and `<my-proj-folder>/.expo`

try deleting both?

**Comment by MohammedAlzard** [comment]
rm -fr ~/.expo/starter-app-cache
