### ISSUE TITLE
com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by iuliuvisovan** [expo/expo#1903]
Detached project.
Using ExpoKit SDK27, Android
Steps to reproduce:
1. Open app
2. Press the home button
3. Access app from home screen again
4. This error pops up:
![image](https://user-images.githubusercontent.com/11357552/41707529-fe2f3c40-7546-11e8-97de-bc9f0cc162cb.png)

Using adb logcat, the full error is this:
`ErrorActivity: ErrorActivity message: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String`

What could this be caused by?

**Comment by jimmylee** [comment]
Hey @iuliuvisovan 

Thanks a ton for using Expo! I'm really sorry you're having this issue. Is there anyway you could tell us more information about the problem you're having? You don't have any custom code at all? Is this a brand new Expo project with a detach?

**Comment by sunilkumarc** [comment]
I'm facing the same error when trying to import a prepopulated db into my app. Here is the information about my app.

1. First I created a database using sqlite3 command line tool:
`sqlite3 myDB.db`

2. Created a table and inserted some data into this table.

3. Now I have a file called myDB.db inside www folder at the root of my app directory. 
![screen shot 2018-06-23 at 6 23 46 pm](https://user-images.githubusercontent.com/3911000/41809884-90b1a73e-7712-11e8-9f8f-0190f9145812.png)

4. After the above steps, I'm trying to access this db inside my FactsCardsPage.js using below code.
![screen shot 2018-06-23 at 6 26 43 pm](https://user-images.githubusercontent.com/3911000/41809911-e524e93e-7712-11e8-8173-18ac15462b83.png)

5. But I'm getting below error when trying to run the app. Any help is appreciated!
![screen shot 2018-06-23 at 6 27 22 pm](https://user-images.githubusercontent.com/3911000/41809963-b763e4f4-7713-11e8-9568-72ed20d2ae24.png)

**Comment by sjchmiela** [comment]
Hi @sunilkumarc! There are a couple of issues with the way you're trying to access the database:

1. `SQLite.openDatabase` doesn't accept an object as the first argument (see [the documentation](https://docs.expo.io/versions/v27.0.0/sdk/sqlite#exposqliteopendatabasename-version-description-size)). The first argument, called `name` is expected to be a string and you're providing an object `{ name: 'factsDB.db', createFromLocation: 1 }`.
    
    That's why you get `ReadableNativeMap cannot be cast to String`—JS objects are parsed as `ReadableNativeMap` in native and it is not possible to pass it as an argument to a function expecting `String`.
    
    May I ask, where did you get the idea to pass an object with `createFromLocation: 1`?
2. Moreover, the file you've created in your local filesystem won't be automatically copied to your app's internal directory. As the documentation of `SQLite.openDatabase` states:
    > On disk, the database will be created under the app's documents directory, i.e. ${Expo.FileSystem.documentDirectory}/SQLite/${name}.
    
    To be able to use the database you've created on your computer you'll need to:
    - either download the database from your computer with `FileSystem.downloadAsync` into `${FileSystem.documentDirectory}/SQLite/${name}` and then open the database.
        
        To be able to download the database from your computer, you will need to use some simple HTTP server, eg. [asdf](https://www.npmjs.com/package/asdf).
    - or 
        - `require` it as a module,
        - use [`Asset.fromModule()`](https://docs.expo.io/versions/v27.0.0/sdk/asset#expoassetfrommodulemodule) to convert it to an Asset,
        - use `https://docs.expo.io/versions/v27.0.0/sdk/asset#downloadasync` to download it to the local filesystem, and then
        - use [`FileSystem.copyAsync()`](https://docs.expo.io/versions/v27.0.0/sdk/filesystem#expofilesystemcopyasyncoptions) to copy the file from [`localUri`](https://docs.expo.io/versions/v27.0.0/sdk/asset#localuri) to `${FileSystem.documentDirectory}/SQLite/${name}`.

The latter way should work in theory, although I've had some problems making `FileSystem` copy the asset to documents directory. The former worked all right. 🙂

**Comment by sjchmiela** [comment]
A couple of questions 🙂:

1. `openDatabase` isn't an asynchronous method, so we don't have to `await openDatabase`, just `openDatabase` will suffice.
2. You've provided three arguments to the `openDatabase` function, `'factsDB.db'`, `successCB` and `errorCB`. I suspect those two `CB`s are callbacks — `SQLite.openDatabase` doesn't accept callbacks as the second and third argument, but rather `version`, `description` and `size`. Although this is not an error, because

    > The version, description and size arguments are ignored, but are accepted by the function for compatibility with the WebSQL specification.

    it is still nice to be compliant with the docs. 😉
3. `db.transaction` isn't an async method too.
4. In `success` function supplied to `tx.executeSql` you're destructuring the second argument in-line and passing `argument.results` as `results`. It turns out, the [`ResultSet object`](https://docs.expo.io/versions/latest/sdk/sqlite.html#resultset-objects) doesn't have value for `results` key. So, a more proper way of doing this would be
   ```js
   (tx, results) => console.log(results) // or console.log(JSON.stringify(results, null, 2))
   ```
5. Something/all above should fix the issue, but there is one more thing that could help (but would be strange if it did)—in an `expo/sqlite-example` app at the end of SQL statements `;` is used (see [code](https://github.com/expo/sqlite-example/blob/master/App.js#L44)).

**Comment by sjchmiela** [comment]
I'll close this issue tentatively, due to inactivity and in hope that the Snack provided helped you solve the issue. 🙂
