### ISSUE TITLE
[Android] Detached Expo and Push Notifications using FCM

### ISSUE THREAD

**Issue by spedy** [expo/expo#1904]
I would like to know if it is possible for me to detach Expo and use my own firebase credentials, by adding `"googleServicesFile": "./google-services.json",` to send push notifications on release (play store) via firebase console?

Also, I am currently on debug, but when I send via firebase console it returns error:
`ExponentGcmListenerService: No experienceId in push payload.` 

Where is this experience id located?

**Comment by jimmylee** [comment]
Hi @spedy thanks for using Expo

I believe this issue has been resolved, you may want to check this issue out: https://github.com/expo/expo/issues/1636

From @esamelson 

```
Hi all -- sorry for the delay here. We've landed a fix for this bug and it will ship with a new version of XDE soon. In the meantime, you'll need to use one of the workarounds provided here (use an absolute rather than relative path, drop the google-services.json file into the XDE working directory, or just use exp instead). Really sorry for the inconvenience!
```

His pathing solution is a common issue in Node land. I hope this helps you out, please let me know if you have any other questions.

Unrelated, this might be a good reference for you when working with a detached Expo Firebase setup https://github.com/EvanBacon/expo-native-firebase designed to help people with detached firebase setups.

**Comment by esamelson** [comment]
Hi @spedy - we actually don't support the `"googleServicesFile"` key in detached apps right now (it's in the works!). If you want to use FCM with a detached app you can follow the instructions here instead: https://forums.expo.io/t/fcm-with-expokit/9814/3 

Your experience id is `@<your-username>/<app-slug>` -- so e.g. for my app with slug `test` it would be `@esamelson/test`.

**Comment by jimmylee** [comment]
Thanks @esamelson !

**Comment by esamelson** [comment]
Hi @spedy - no, we don't support FCM on iOS currently, sorry :/ However, if you follow [this part of the guide for setting up FCM](https://docs.expo.io/versions/v28.0.0/guides/using-fcm#uploading-server-credentials) you can just send all of your notifications through Expo. Behind the scenes we will choose FCM, GCM, or Apple to send the notification depending on the individual device.

**Comment by spedy** [comment]
I see, thank you for your help!
