### ISSUE TITLE
expo-updates failed to download png asset, causing update to fail

### ISSUE THREAD

**Issue by ScholtenSeb** [expo/expo#19046]
### Summary

At first I could not understand why updates were failing. But then I inspected the logs on app startup to see what is happening. I saw the following error...

<img width="1153" alt="Screen Shot 2022-09-09 at 6 03 01 pm" src="https://user-images.githubusercontent.com/8728836/189302903-28c6e363-9ce0-44d2-a7ea-fff3c954b366.png">

Using the key after the message: "Failed to download asset with key ..." is was able to track down the asset causing problems. When running `eas update --branch preview --message "..."`, luckily the packaged assets are listed in the same order as in the manifest provided on `u.expo.dev/update/....`

I was able to track down the error to a .png file that was not downloading. It was "pickup@2x.png" in the screenshot below

<img width="361" alt="Screen Shot 2022-09-09 at 6 11 02 pm" src="https://user-images.githubusercontent.com/8728836/189303847-d9bc0ee2-fb96-4b7e-8d05-2f5a40d259b0.png">

My first thought was that there something wrong with the filename. Renamed the file but still failed to download the asset on updating. The key remained the same so I assume its generated based on file contents?

Next thing I tried was to simply open up the .png in preview, and export it as a .png file again. I replaced the file and kept the original filename.

This worked, no more errors and updates were working again.

Not sure if this can be closed, but though I might share this in case someone else encounters this. Only tested this on Android.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    Expo Workflow: managed

### Minimal reproducible example

I will try my best to follow up with a minimal example using the original png file. But time is a constraint. I can also provide the 2 pngs file separately.

**Comment by akve** [comment]
In my case, .ttf fonts are not copied - and update fails. 
[expo-cli] saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf
Will try to collect more data, and come back. Just "touching" the file prior to 'eas update' does not work

**Comment by quinlanj** [comment]
The problem is related to this outage: https://status.expo.dev/incidents/5xxsm8lsx7js?u=fkqjk5zbx14n
If you are seeing a message like "Failed to load all assets" in an app using EAS Update, the recommended fix is to publish an update with `eas update` which should fix the assets in storage.

**Comment by ayshrimali** [comment]
@quinlanj I tried to push new update but no luck. The worst part is there is no way to debug it as the eas update command works just fine.

**Comment by baochungit** [comment]
I used to face this issue on SDK 45 but now it's fine on SDK 46

**Comment by akve** [comment]
This error auto-magically disappeared, but I found out one more source of update fails. Build/publish is working with eas.json while update is working with local environment variables. And there was an issue in the code (old usage of Constants) that was leading to crash when update tried to install. "Mind the gap"..

**Comment by finom** [comment]
SDK 47, same issue.

**Comment by finom** [comment]
@ScholtenSeb how did you debug the problem (how to check the logs)?

**Comment by maniac-tech** [comment]
I'm running Expo SDK 46, and using EAS Update to update the builds.

But cant seem to get the changes on the app.

**Comment by baochungit** [comment]
> I'm running Expo SDK 46, and using EAS Update to update the builds.
> 
> But cant seem to get the changes on the app.

Do you see the update on Expo.dev site? Check if the branch, platform, runtime version are correct

**Comment by finom** [comment]
@maniac-tech maybe [this](https://github.com/expo/eas-cli/issues/1557#issuecomment-1335566466) will help.

**Comment by maniac-tech** [comment]
@baochungit Yes I can see the updates listed on expo.dev with all correct data

**Comment by maniac-tech** [comment]
@finom Doesnt really help in mycase, did reply there though...

**Comment by maniac-tech** [comment]
Found the issue in my case: https://github.com/expo/expo/pull/18548

Solution is our very own classic:

rm -rf node_modules yarn.lock && yarn
