### ISSUE TITLE
[Android] getForegroundPermissionsAsync returns canAskAgain false even though location permission can be requested

### ISSUE THREAD

**Issue by itsramiel** [expo/expo#19047]
### Summary

getForegroundPermissionsAsync returns `status: denied, canAskAgain: false` even though in reality you can and if called `requestForegroundPermissionsAsync` it will actually prompt the user.

To reproduce please use the minimal reproducible example below with expo go or custom dev client.

First open the app and check permissions which will be undetermined. Next ask for permissions and give `only this time` which translates to `ask every time` in the settings. Next request location and everything is successful as shown in the video:  

https://user-images.githubusercontent.com/80689446/189305450-0c96dcf5-57ec-44e2-8884-9b8d4403e88e.mp4

Now kill the app and lock the device for a couple of seconds(i guess this ends the `only this time` session). Now open the app again and check permission, you will notice that **status** is **denied** and **canAskAgain** is **false**, where in reality **canAskAgain** should **true** because you gave `ask every time` permission and going on to request location will be successful as well as requesting location after. 

https://user-images.githubusercontent.com/80689446/189306273-ae89cb08-a593-44de-98bf-bb1f65ced437.mp4

Expected behavior: **canAskAgain** should be true in this case since I actually can ask again

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.1
    Expo Workflow: managed

### Minimal reproducible example

```
import {
  getCurrentPositionAsync,
  getForegroundPermissionsAsync,
  requestForegroundPermissionsAsync,
} from "expo-location";
import { StatusBar } from "expo-status-bar";
import { Alert, Button, StyleSheet, Text, View } from "react-native";

async function checkPermissions() {
  const currentPermissions = await getForegroundPermissionsAsync();
  Alert.alert("currentPermissions", JSON.stringify(currentPermissions), [
    { text: "dismiss" },
    {
      text: "request permissions",
      onPress: requestPermissions,
    },
  ]);
}

async function requestPermissions() {
  const permissions = await requestForegroundPermissionsAsync();
  Alert.alert("permissions", JSON.stringify(permissions), [
    { text: "dismiss" },
    {
      text: "request location",
      onPress: requestLocation,
    },
  ]);
}

async function requestLocation() {
  const location = await getCurrentPositionAsync();
  Alert.alert("location", JSON.stringify(location));
}

export default function App() {
  return (
    <View style={styles.container}>
      <Button title="request location" onPress={checkPermissions} />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

```

**Comment by itsramiel** [comment]
@monaye this is a valid issue. Feel free to try it

**Comment by itsramiel** [comment]
@byCedric Any updates on this?

**Comment by c-mcdonald** [comment]
I can confirm I am seeing the same behaviour (SDK 46) using both the Expo client and a standalone build. 

When the user selects "Only this time" from the in app prompt, or "Ask every time" from the app permissions screen, the askAgain=false always after device lock and then app start.

**Comment by itsramiel** [comment]
the issue is still valid

**Comment by Ahmed-Ibrahim-Anter** [comment]
the issue is still valid

**Comment by itsramiel** [comment]
There is a minimal example. I don't get why it was closed. @brentvatne any insights on why this happened?

**Comment by ChromeQ** [comment]
I am also seeing this behaviour on expo v48 (development build and standalone app) and it is a big friction point as I can never be sure if the native permission modal actually appears if I ignore the `canAskAgain` and always call `getForegroundPermissionsAsync` anyway. 

It seems even with `canAskAgain = false` will allow me to ask and show the native permission request, but pressing deny twice means it never shows again which is when I need to show the button to open settings.

The only safe thing to do now is to show the open settings button even if the user selected "Ask every time", which is a bit misleading as I am not asking every time and it is like I am coercing the user to grant permanent location permission...

**Comment by ChromeQ** [comment]
I think I've found a workaround @itsramiel, `requestNativePermission()` returns a promise, so await or chain a then on that and the response is correct with the `canAskAgain` so I will save that in local storage.

```ts
requestNativePermission().then((response) => {
    console.log('RESPONSE', response);
    // TODO: Save the response.canAskAgain to localStorage to check next time
 });
```

It's not ideal but better than the current behaviour imo, also need to check the solution works in iOS as my development is only on android for now

**Comment by AyoCodess** [comment]
im having issue too, how can we ask for permissions in both ios and android ,if this hook does not work.

**Comment by singhayush1403** [comment]
Any fix for this? It is breaking logic in my app as well

**Comment by jbcrestot** [comment]
This bug is still present.
I'm witnessing it on android 11, but, did you reproduce it on other version ?
 @erik-jenkins @AyoCodess @singhayush1403

**Comment by Gaccoo** [comment]
I tested versions from 29-31 API. The problem starts from API level 30, where the option "Ask every time" is present.

**Comment by RiedelNicolas** [comment]
> I think I've found a workaround @itsramiel, `requestPermission()` from the `useForegroundPermissions` hook returns a promise, so await or chain a then on that and the response is correct with the `canAskAgain` so I will save that in local storage.
> 
> ```ts
> requestPermission().then((response) => {
>     console.log('RESPONSE', response);
>     // TODO: Save the response.canAskAgain to localStorage to check next time
>  });
> ```
> 
> It's not ideal but better than the current behaviour imo, also need to check the solution works in iOS as my development is only on android for now

Great workarround!! @ChromeQ 

Here is how it is working for me : 

```js
            const fg = Location.getForegroundPermissionsAsync().then((res)=>res.canAskAgain);
            const bg = Location.getBackgroundPermissionsAsync().then((res)=>res.canAskAgain);

            console.log("Can be asked", await fg, await bg);
```

**Comment by ChromeQ** [comment]
Has anyone confirmed if this is working as expected in Expo v50? 
Not sure why this issue was closed

**Comment by ChromeQ** [comment]
I can confirm it is still not working as expected in the latest expo@50.0.8. 
However, I have found another workaround which is to always use `requestForegroundPermissionsAsync` rather than `getForegroundPermissionsAsync`, then the `canAskAgain` is always correct then in the response and you can use this as a means to display another message to open settings if necessary.

The only downside is that it will actually ask the user for the permission (if permitted), which is ok in my situation and works probably as you'd expect:

**Will Display Permission Popup:**
- When permission is undetermined (never asked)
- When permission is Ask Every Time
- When permission is Denied but `canAskAgain` is actually true

**Will Not Display Permission Popup:**
- When permission is denied multiple times
- When permission is already granted

**Comment by ChromeQ** [comment]
Further update:
I have tried out [react-native-permissions](https://github.com/zoontek/react-native-permissions?tab=readme-ov-file#check) and falling into the same "pit" leading me to believe this may be a limitation of the android platform.

The docs over on react-native-permissions say
> Android will never return blocked on check, you have to call request to get the info.
Using the flow chart it is clear it is not possible to determine if `canAskAgain` should be true or false when calling `check` aka expo's `getForegroundPermissionsAsync`

**Comment by ChromeQ** [comment]
> There is a minimal example. I don't get why it was closed. @brentvatne any insights on why this happened?

@brentvatne Sorry to nudge you on this a year later 😅

**Comment by RiedelNicolas** [comment]
@ChromeQ Have you tried this : https://github.com/expo/expo/issues/19047#issuecomment-1915186798

It is not the best solution, but it's working for me.

**Comment by ChromeQ** [comment]
@RiedelNicolas I'm not sure how that is working for you as that is precisely the bug as described in the OP. I am getting false for `canAskAgain` even when the permission is set to "Ask Every Time"

**Comment by Daniel-Cross** [comment]
I'm getting a similar issue, maybe not quite relevant to this issue but it could be:

Whenever I use "only this time" on Android, I get the status of `granted` (expected).

Then if I close the app and reopen, I still get the status of `granted` despite not being prompted for the permissions again. It seems it's treating the option of "ask every time" as semi permanent.

`canAskAgain` is always `true` for me though.
