### ISSUE TITLE
expo-av: onPlaybackStatusUpdate not called on interval when using remote debugging

### ISSUE THREAD

**Issue by b-steel** [expo/expo#19044]
### Summary

The onPlaybackStatusUpdate function should be called every 500ms (default value).  This is happening (I can see it with logs/having the callback do something) normally, however, when remote debugging is enabled, the callback is not fired on the interval.

The callback can be fired still by forcing a status update (pausing, playing, etc) but it is not automatically called every 500ms (or whatever you set it to)

Have not tested on android, but occurs on iOS both physical and simulator.

I noticed this with Expo SDK 46, did not see it on 44. 

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.08.29.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/b-steel/expo-av-repro

**Comment by OneHatRepo** [comment]
Duplicate of [this bug](https://github.com/expo/expo/issues/19022)

**Comment by b-steel** [comment]
> Duplicate of [this bug](https://github.com/expo/expo/issues/19022)
