### ISSUE TITLE
[expo-notifications] requestPermissionsAsync() does not present the permissions request for Android 13

### ISSUE THREAD

**Issue by yincrash** [expo/expo#19043]
### Summary

Android 13 has a new runtime [permission for notifications](https://developer.android.com/develop/ui/views/notifications/notification-permission). When having an app target API 33, the permissions request API doesn't actually issue a permission request on Android.

### What platform(s) does this occur on?

Android

### Environment

expo-notifications@0.16.1

### Minimal reproducible example

The basic example in the expo-notifications documentation will reproduce it - https://docs.expo.dev/versions/latest/sdk/notifications/#api

I can whip up repo if necessary, but the missing code would be required [here](https://github.com/expo/expo/blob/main/packages/expo-notifications/android/src/main/java/expo/modules/notifications/permissions/NotificationPermissionsModule.java#L45).

**Comment by yincrash** [comment]
I have a patch that I use for our app, but it creates a requirement to up the `compileSdkVersion` to 33 for anyone who uses it. Alternatively, you could avoid the requirement by putting in `33` and `"android.permission.POST_NOTIFICATIONS"` in place of the two constants that are imported from SDK 33.

```
diff --git a/node_modules/expo-notifications/android/build.gradle b/node_modules/expo-notifications/android/build.gradle
index 5b32ade..263aa00 100644
--- a/node_modules/expo-notifications/android/build.gradle
+++ b/node_modules/expo-notifications/android/build.gradle
@@ -59,7 +59,7 @@ afterEvaluate {
 }
 
 android {
-  compileSdkVersion safeExtGet("compileSdkVersion", 31)
+  compileSdkVersion safeExtGet("compileSdkVersion", 33)
 
   compileOptions {
     sourceCompatibility JavaVersion.VERSION_11
diff --git a/node_modules/expo-notifications/android/src/main/AndroidManifest.xml b/node_modules/expo-notifications/android/src/main/AndroidManifest.xml
index 411f832..1d9219a 100644
--- a/node_modules/expo-notifications/android/src/main/AndroidManifest.xml
+++ b/node_modules/expo-notifications/android/src/main/AndroidManifest.xml
@@ -1,6 +1,7 @@
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
   package="expo.modules.notifications">
 
+  <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
   <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
 
   <application>
diff --git a/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/permissions/NotificationPermissionsModule.java b/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/permissions/NotificationPermissionsModule.java
index d5f5481..5c7c7f0 100644
--- a/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/permissions/NotificationPermissionsModule.java
+++ b/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/permissions/NotificationPermissionsModule.java
@@ -1,17 +1,20 @@
 package expo.modules.notifications.permissions;
 
+import android.Manifest;
 import android.app.NotificationManager;
 import android.content.Context;
 import android.os.Build;
 import android.os.Bundle;
 
 import expo.modules.core.ExportedModule;
+import expo.modules.core.ModuleRegistry;
 import expo.modules.core.Promise;
 import expo.modules.core.arguments.ReadableArguments;
 import expo.modules.core.interfaces.ExpoMethod;
 
 import androidx.core.app.NotificationManagerCompat;
 
+import expo.modules.interfaces.permissions.Permissions;
 import expo.modules.interfaces.permissions.PermissionsStatus;
 
 import static expo.modules.interfaces.permissions.PermissionsResponse.CAN_ASK_AGAIN_KEY;
@@ -27,10 +30,17 @@ public class NotificationPermissionsModule extends ExportedModule {
   private static final String IMPORTANCE_KEY = "importance";
   private static final String INTERRUPTION_FILTER_KEY = "interruptionFilter";
 
+  private ModuleRegistry mModuleRegistry;
+
   public NotificationPermissionsModule(Context context) {
     super(context);
   }
 
+  @Override
+  public void onCreate(ModuleRegistry moduleRegistry) {
+    mModuleRegistry = moduleRegistry;
+  }
+
   @Override
   public String getName() {
     return EXPORTED_NAME;
@@ -43,7 +53,17 @@ public class NotificationPermissionsModule extends ExportedModule {
 
   @ExpoMethod
   public void requestPermissionsAsync(@SuppressWarnings("unused") final ReadableArguments permissionsTypes, final Promise promise) {
-    promise.resolve(getPermissionsBundle());
+    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
+      getPermissionsAsync(promise);
+      return;
+    }
+
+    Permissions permissionsManager = mModuleRegistry.getModule(Permissions.class);
+    if (permissionsManager == null) {
+      promise.reject("E_NO_PERMISSIONS", "Permissions module is null. Are you sure all the installed Expo modules are properly linked?");
+      return;
+    }
+    permissionsManager.askForPermissionsWithPromise(promise, Manifest.permission.POST_NOTIFICATIONS);
   }
 
   private Bundle getPermissionsBundle() {
```

**Comment by jurica-penjgusic** [comment]
Hi there, is this possible to use with expo-build-properties to set compile sdk version?

**Comment by Codelica** [comment]
Running into this as well.  In looking at what gets patched, it seems it would take `patch-package` and a rebuild of the `expo-notifications` module in an EAS `postinstall` step to get things applied?  (with an EAS build at least)  

Any chance of `expo-notifications` getting updated with this *before* Expo 47 hits?  Trying to weight he options. :)

**Comment by Codelica** [comment]
Just a followup here that I have the permission popup working on Android 13 without this patch.  The key is that `setNotificationChannelAsync` must be called prior to trying to get the token.  More info is found on the update Expo notification page [here](https://docs.expo.dev/versions/latest/sdk/notifications/#android-1):

>On Android 13, app users must opt-in to receive notifications via a permissions prompt automatically triggered by the operating system. This prompt will not appear until at least one notification channel is created. Therefore, setNotificationChannelAsync must be called prior to getDevicePushTokenAsync or getExpoPushTokenAsync in order to obtain a push token. You can read more about the new notification permission behavior for Android 13 [in the official documentation](https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps).

**Comment by ndjerrou** [comment]
I've used ```setNotificationChannelAsync```but the pop up still does not appear....

expo version 47

**Comment by Codelica** [comment]
@ndjerrou and that `setNotificationChannelAsync` is called first, before checking or getting tokens?   I definitely see it working here with an Android build, but I am on Expo 46 with Android 13 (on Google Pixel).  If you're on some Expo 47 beta it may be worth trying 46.

**Comment by ndjerrou** [comment]
I am on expo 45 but targeting android 13(is it possible to change this target)?

The setchannelasync is called way before getting push token but nothing comes.also when I publish on the store, Google keeps telling me that I am requesting for location permission. They want me to show the disclosure before requesting permissions.

I submitted an other release on playstore waiting if it is going to work...

**Comment by Codelica** [comment]
Targeting a different Android SDK with Expo 45 I'm not sure about.  I *think* it would be safer to try updating to 46.  But the part about location permissions makes me thing you may have something different going on.  

I have another test build and install cycle coming here this week, so I'll be able verify it's workung under Expo 46 again.

**Comment by mdhaynes** [comment]
receiving the same issue. The app was working fine in expo and as an apk file. Only after uploading to play store we first noticed the error on contacts (Resolved by adding entry to manifest and thoroughly removing app and rebooting), and now on notifications.

Have added POST_NOTIFICATIONS and RECEIVE_BOOT_COMPLETED to manifest and set the channel before, as per example https://docs.expo.dev/versions/latest/sdk/notifications/. The issue seems to be with Notifications.getPermissionsAsync()

Any update? This is a serious urgent issue for us.

**Comment by Codelica** [comment]
@mdhaynes have you moved `setNotificationChannelAsync` to the top of your logic (more info [here](https://github.com/expo/expo/issues/19043#issuecomment-1257029705))?  That works for me with Android 13 / Expo 46 currently. 

![Screenshot_20220927-145229](https://user-images.githubusercontent.com/386101/193612164-9f85790b-05fc-4890-b9ee-8dffdaa4df86.png)

**Comment by thisisirfan** [comment]
https://stackoverflow.com/a/76127440/4754175

**Comment by OliverAlves** [comment]
If you change the order of the Expo notification documentation it  works great. The only diference it is to set the Channel first and then call for the notifications permission

<img width="703" alt="Screenshot 2023-05-09 at 08 19 19" src="https://github.com/expo/expo/assets/87578599/91053017-02a0-4271-be6a-a07218f4b27e">

**Comment by diegods-ferreira** [comment]
I'm having a weird behavior when calling `setNotificationChannelAsync` before `requestPermissionsAsync`.

In the first time my app boots it is not able to prompt for notifications permission. Then I close the app and repoen it and it shows the prompt.

Is someone having this same problem?

```json
"expo": "^47.0.0",
"expo-notifications": "~0.17.0",
```

**Comment by id0Sch** [comment]
@diegods-ferreira yes, I am having this issue as well

**Comment by diegods-ferreira** [comment]
@id0Sch Recently I've built my app for production to post it on Play Store and I've noticed that, when in production, my app is able to prompt for notifications permission without problems on the first time the app boots. So I'm guessing it was a problem that occurs only on development enviroment.

**Comment by gkpradhnani1998** [comment]
@diegods-ferreira I am facing same behavior on android 13. after uploading production build on play store your issue got fixed automatically?

**Comment by vine1993** [comment]
i can't make this work with APK or Expo Go with my phone. there is no way to make this work.

Im using a hook and calling on root _layout. 
Also, I'm making sure of calling setNotificationChannelAsync before request the token for android.

```
import { useState, useEffect, useRef } from "react";
import * as Device from "expo-device";
import * as Notifications from "expo-notifications";

import Constants from "expo-constants";

import { Platform } from "react-native";

export interface PushNotificationState {
  expoPushToken?: Notifications.ExpoPushToken;
  notification?: Notifications.Notification;
}

Notifications.setNotificationHandler({
    handleNotification: async () => ({
      shouldPlaySound: true,
      shouldShowAlert: true,
      shouldSetBadge: true,
    }),
    handleSuccess: notificationId => console.log(`Notification ${notificationId} successfully handled.`),
    handleError: (notificationId, error) => console.log(`Notification ${notificationId} wasn't successfully handled.`, error),
  });

export const usePushNotifications = (): PushNotificationState => {

  const [expoPushToken, setExpoPushToken] = useState<
    Notifications.ExpoPushToken | undefined
  >();

  const [notification, setNotification] = useState<
    Notifications.Notification | undefined
  >();

  const notificationListener = useRef<Notifications.Subscription>();
  const responseListener = useRef<Notifications.Subscription>();

  async function registerForPushNotificationsAsync() {
    if (Platform.OS === "android") {
        Notifications.setNotificationChannelAsync("default", {
          name: "default",
          importance: Notifications.AndroidImportance.MAX,
          vibrationPattern: [0, 250, 250, 250],
          lightColor: "#FF231F7C",
        });
      }

    let token;
    if (Device.isDevice) {
      const { status: existingStatus } =
        await Notifications.getPermissionsAsync();
      let finalStatus = existingStatus;

      if (existingStatus !== "granted") {
        const { status } = await Notifications.requestPermissionsAsync();
        finalStatus = status;
      }
      if (finalStatus !== "granted") {
        alert("Failed to get push token for push notification");
        return;
      }

      // TODO: token without expo
      token = await Notifications.getDevicePushTokenAsync();

        //   token = await Notifications.getExpoPushTokenAsync({
        //     projectId: '9d9c4357-130f-443c-a1dc-1fc499bcfaf5'
        //   });
    } else {
      alert("Must be using a physical device for Push notifications");
    }

    return token;
  }

  useEffect(() => {
    registerForPushNotificationsAsync().then((token) => {
      setExpoPushToken(token);
    }).catch(err => {
        console.log('ERR to something about the token',err)
    });

    notificationListener.current =
      Notifications.addNotificationReceivedListener((notification) => {
        setNotification(notification);
        console.log('SABOTAGE',notification)
      });

    responseListener.current =
      Notifications.addNotificationResponseReceivedListener((response) => {
        console.log('RECEBI UMA NOTIFICAÇÃO?',response);
      });

    return () => {
      Notifications.removeNotificationSubscription(
        notificationListener.current!
      )

      Notifications.removeNotificationSubscription(responseListener.current!)
    }
  }, []);

  return {
    expoPushToken,
    notification,
  };
};
```

When I'm testing I'm my own device I can't send a notification directly from firebase messaging and I also with the APK I can't even get the token because the permission isn't requested at all

**Comment by diegods-ferreira** [comment]
> @diegods-ferreira I am facing same behavior on android 13. after uploading production build on play store your issue got fixed automatically?

Sorry for the delay, I did not see the notification for your question. So... yes, the problem where the app did not prompt for notifications permission occurred only on dev enviroment. When in production, it works perfectly, even if I generate a release APK it would work too.

**Comment by diegods-ferreira** [comment]
> @diegods-ferreira I am facing same behavior on android 13. after uploading production build on play store your issue got fixed automatically?

@gkpradhnani1998  Sorry for the delay, I did not see the notification for your question. So... yes, the problem where the app did not prompt for notifications permission occurred only on dev enviroment. When in production, it works perfectly, even if I generate a release APK it would work too.
