### ISSUE TITLE
ExpoFileSystem.createDownloadResumable doesn't fire callback, throws error

### ISSUE THREAD

**Issue by OneHatRepo** [expo/expo#19053]
### Summary

ExpoFileSystem.createDownloadResumable, when passed a callback, doesn't fire the callback during download.
Instead, it emits an error which says, "Sending `expo-file-system.downloadProgress` with no listeners registered."

But the listener _was_ registered.

Seems to only happen **when debugging is enabled.**

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/opt/node@16/bin/node
      npm: 8.15.0 - /usr/local/opt/node@16/bin/npm
      Watchman: 2022.09.05.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/OneHatRepo/TestDownload

`npm run start`

**Comment by Kudo** [comment]
hi there! this issue should only present when using remote debugging mode and not have impact to production apps. this issue should also be resolved in sdk 47. you could try to upgrade sdk 47 and test again.
