### ISSUE TITLE
BarCodeScanner intermittently crashes app on render

### ISSUE THREAD

**Issue by delventhalz** [expo/expo#19060]
### Summary

When rendering the `BarCodeScanner` component from `expo-barcode-scanner`, the entire app sometimes locks up. The parent component is visible, but the camera viewport itself never renders.  The app must be quit and restarted.

- Occurs intermittently, unclear what the trigger is. A device can use the scanner successfully only to have it crash later.
- Only observed in deployed app binaries, not in Expo Go
- Only observed in iOS
- A wrapping ErrorBoundary component does not catch errors generated by this event

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.2
    Expo Workflow: managed
```

expo-barcode-scanner: 11.3.0

### Minimal reproducible example

```javascript
import { BarCodeScanner } from 'expo-barcode-scanner';
import React, { useEffect, useState } from 'react';
import { Dimensions, StyleSheet, View } from 'react-native';

const { width } = Dimensions.get('window');
const scannerSize = Math.floor(width * 0.75);

export function QrEntry({ onSubmit }) {
  const [hasPermission, setHasPermission] = useState(null);
  const [hasScanned, setHasScanned] = useState(false);

  useEffect(() => {
    BarCodeScanner.requestPermissionsAsync().then(({ status }) => {
      setHasPermission(status === 'granted');
    });
  }, []);

  const onScan = ({ data }) => {
    if (!hasScanned) {
      setHasScanned(true);
      onSubmit(data);
    }
  };

  return (
    <View style={style.body}>
      {hasPermission && (
        <BarCodeScanner
          barCodeTypes={[BarCodeScanner.Constants.BarCodeType.qr]}
          onBarCodeScanned={onScan}
          style={style.scanner}
        />
      )}
    </View>
  );
}

const style = StyleSheet.create({
  body: {
    flexGrow: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  scanner: {
    borderRadius: 20,
    overflow: 'hidden',
    width: scannerSize,
    height: scannerSize,
  },
});
```

**Comment by delventhalz** [comment]
FYI, I did an update to Expo 46 and expo-barcode-scanner 11.4.0 and was still able to reproduce the issue.

Here is the new 
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.2
    Expo Workflow: managed
```

**Comment by delventhalz** [comment]
I seem to be able to reliably reproduce the issue by just closing and opening the scanner repeatedly. The app freezes up maybe 1 in 40 renders.

When reproducing this artificial way, the app will sometimes freeze shortly after dismissing the scanner as well. In real app usage, I have only seen it when attempting to render a new BarCodeScanner.

**Comment by delventhalz** [comment]
Not trying to spam this issue, but just to be clear, I am building a QR scanning _based_ game which is launching soon. A typical play through involves around 100 QR scans, so a 1 in 40 crash rate guarantees that there will be one or two every time users play. I can't launch with a bug like that.

I could really use a fix or a workaround if anyone has any ideas. The next step will be ejecting Expo, which I would really rather avoid.

**Comment by brentvatne** [comment]
@delventhalz - if you would like to send a PR to fix this or share more information about the exact error message that you see on the crash, that would be helpful. if you aren't sure how to investigate this on your own, you can reach out to one of our [recommended consultants](https://expo.dev/consultants) to lend a hand. also, what service are you using do the build? EAS Build or the `expo build`?

**Comment by brentvatne** [comment]
also, you can use any barcode scanning library that you like with EAS Build. you can check whether you're able to reproduce this with other libraries that you can find on reactnative.directory: https://reactnative.directory/?search=barcode

https://docs.expo.dev/workflow/customizing/

**Comment by delventhalz** [comment]
@brentvatne Using EAS Build. 

Believe it or not, I have actually spent quite a bit of time looking at alternatives at this point. Unfortunately `expo-camera` does not scan QR codes on iOS, and anything else would mean dropping Expo Go from the workflow. At that point I might as well eject Expo altogether you know?

But logs are a great idea!

Here are the complete logs from when the user presses the button to summon the QR scanning modal, and when the app locks up. `Taelmoor` is the name of the app, and `com.delvebros.taelmoor` is the identifier.

```
Type        Time                    Process         Message

default     21:53:43.914520-0500    Taelmoor        Evaluating dispatch of UIEvent: 0x282050a80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default     21:53:43.914668-0500    Taelmoor        Sending UIEvent type: 0; subtype: 0; to windows: 1
default     21:53:43.914808-0500    Taelmoor        Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x108107a60>; contextId: 0xDFEBDFF7
default     21:53:43.926599-0500    Taelmoor        Evaluating dispatch of UIEvent: 0x282050a80; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default     21:53:44.045684-0500    Taelmoor        Evaluating dispatch of UIEvent: 0x282050a80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default     21:53:44.045932-0500    Taelmoor        Sending UIEvent type: 0; subtype: 0; to windows: 1
default     21:53:44.046175-0500    Taelmoor        Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x108107a60>; contextId: 0xDFEBDFF7
default     21:53:44.060075-0500    Taelmoor        Evaluating dispatch of UIEvent: 0x282050a80; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 1
default     21:53:44.102396-0500    mediaserverd    <<<< FigCaptureClientSessionMonitor >>>> -[FigCaptureClientSessionMonitor _initWithClient:]: Creating for pid: 2747, ID: com.delvebros.taelmoor, clientType: Application
default     21:53:44.104531-0500    mediaserverd    <<<< FigCaptureClientSessionMonitor >>>> -[FigCaptureClientSessionMonitor _updateClientStateCondition:newValue:]: <0x10b816a80[2747][com.delvebros.taelmoor]> Updating client state condition "_bksApplicationState" with new value "ForegroundRunning"
default     21:53:44.104554-0500    mediaserverd    <<<< FigCaptureClientSessionMonitor >>>> -[FigCaptureClientSessionMonitor _updateClientStateCondition:newValue:]: <0x10b816a80[2747][com.delvebros.taelmoor]> Updating client state condition "_layoutState" with new value "Fullscreen"
default     21:53:44.104655-0500    mediaserverd    <<<< FigCaptureClientSessionMonitor >>>> -[FigCaptureClientSessionMonitor _updateClientStateCondition:newValue:]: <0x10b816a80[2747][com.delvebros.taelmoor]> Updating client with application state "Foregrounded" and layout state "Fullscreen"
default     21:53:44.104685-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_updateRunningCondition: <0x10b804260[2747][com.delvebros.taelmoor]> ClientStartedSession:0 Cam/Audio:0/0 bg:0 prewarming:0 int:0 multitasking:0 pip:0 devStolen:0 pressured:0 active:0 shouldRun:0 start:0 stop:0 stopRecordingIfActive:0
```

You can contrast that with what the logs from when the modal is opened and the `BarCodeScanner` component renders successfully:

```
Type        Time                    Process         Message

default     21:38:05.011007-0500    Taelmoor        Evaluating dispatch of UIEvent: 0x282050a80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default     21:38:05.011259-0500    Taelmoor        Sending UIEvent type: 0; subtype: 0; to windows: 1
default     21:38:05.011713-0500    Taelmoor        Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x108107a60>; contextId: 0xDFEBDFF7
default     21:38:05.022943-0500    Taelmoor        Evaluating dispatch of UIEvent: 0x282050a80; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default     21:38:05.143197-0500    Taelmoor        Evaluating dispatch of UIEvent: 0x282050a80; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default     21:38:05.143481-0500    Taelmoor        Sending UIEvent type: 0; subtype: 0; to windows: 1
default     21:38:05.143615-0500    Taelmoor        Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x108107a60>; contextId: 0xDFEBDFF7
default     21:38:05.156327-0500    Taelmoor        Evaluating dispatch of UIEvent: 0x282050a80; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 1
default     21:38:05.183146-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_SetConfiguration: <0x10f4b71b0[2747][com.delvebros.taelmoor]> New configuration: FigCaptureSessionConfiguration 0x10fe502c0: ID 20, AVCaptureSessionPresetHigh multiCam: 0, appAudio: 1, autoConfig: 1, runWhileMultitasking: 0
default     21:38:05.183185-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_updateRunningCondition: <0x10f4b71b0[2747][com.delvebros.taelmoor]> ClientStartedSession:0 Cam/Audio:0/0 bg:0 prewarming:0 int:0 multitasking:0 pip:0 devStolen:0 pressured:0 active:0 shouldRun:0 start:0 stop:0 stopRecordingIfActive:0
default     21:38:05.183794-0500    mediaserverd    <<<< FigCaptureClientSessionMonitor >>>> -[FigCaptureClientSessionMonitor _initWithClient:]: Creating for pid: 2747, ID: com.delvebros.taelmoor, clientType: Application
default     21:38:05.184484-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMaxFrameDurationInternal:]: MaxFrameDuration to set 1 / 30
default     21:38:05.184528-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMinFrameDurationInternal:]: MinFrameDuration to set 1 / 30
default     21:38:05.184552-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMinFrameDurationInternal:]: MinFrameDuration to set 1 / 30
default     21:38:05.184590-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMaxFrameDurationInternal:]: MaxFrameDuration to set 1 / 30
default     21:38:05.184638-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMinFrameDurationInternal:]: MinFrameDuration to set 1 / 30
default     21:38:05.184674-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMaxFrameDurationInternal:]: MaxFrameDuration to set 1 / 30
default     21:38:05.185481-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMinFrameDurationInternal:]: MinFrameDuration to set 1 / 30
default     21:38:05.185595-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMaxFrameDurationInternal:]: MaxFrameDuration to set 1 / 30
default     21:38:05.185631-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_SetConfiguration: <0x10f4b71b0[2747][com.delvebros.taelmoor]> New configuration: FigCaptureSessionConfiguration 0x10f469ef0: ID 23, AVCaptureSessionPresetHigh multiCam: 0, appAudio: 1, autoConfig: 1, runWhileMultitasking: 0    VC 0x10f471270: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (FD E:0 B:0 S:0), HR:1, FaceDrivenAEAFMode:3, FaceDrivenAEAFEnabledByDefault:1> -> <SINK 0x10f48dbb0:VideoData discards:1, preview:0, stability:0>, BGRA/1920x1080, E:1, VIS:0, M:0, O:Landscape Right, RBC:12, CIM:0    VC 0x10f476170: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (FD E:0 B:0 S:0), HR:1, FaceDrivenAEAFMode:3, FaceDrivenAEAFEnabledByDefault:1> -> <SINK 0x10f470cc0:VideoPreview depth:0 filters:0 [] Portrait Lighting effect strength: 0.0 PrimaryCaptureRectModification:0, Aspect:0.000:1, Center:0.500 0.500, UniqueID:0>, /0x0, E:1, VIS:0, M:0, O:Unspecified, RBC:0, CIM:0    MOC 0x10f4fa0a0: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (FD E:0 B:0 S:0
default     21:38:05.185695-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_updateRunningCondition: <0x10f4b71b0[2747][com.delvebros.taelmoor]> ClientStartedSession:0 Cam/Audio:1/0 bg:0 prewarming:0 int:0 multitasking:0 pip:0 devStolen:0 pressured:0 active:0 shouldRun:0 start:0 stop:0 stopRecordingIfActive:0
default     21:38:05.186323-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_SetConfiguration: <0x10f4b71b0[2747][com.delvebros.taelmoor]> New configuration: FigCaptureSessionConfiguration 0x10fef9a70: ID 24, AVCaptureSessionPresetHigh multiCam: 0, appAudio: 1, autoConfig: 1, runWhileMultitasking: 0    VC 0x10fe111e0: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (FD E:0 B:0 S:0), HR:1, FaceDrivenAEAFMode:3, FaceDrivenAEAFEnabledByDefault:1> -> <SINK 0x10fe11230:VideoData discards:1, preview:0, stability:0>, BGRA/1920x1080, E:1, VIS:0, M:0, O:Landscape Right, RBC:12, CIM:0    VC 0x10fe60100: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (FD E:0 B:0 S:0), HR:1, FaceDrivenAEAFMode:3, FaceDrivenAEAFEnabledByDefault:1> -> <SINK 0x10fe601a0:VideoPreview depth:0 filters:0 [] Portrait Lighting effect strength: 0.0 PrimaryCaptureRectModification:0, Aspect:0.000:1, Center:0.500 0.500, UniqueID:0>, /0x0, E:1, VIS:0, M:0, O:Unspecified, RBC:0, CIM:0    MOC 0x10fe60250: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (FD E:0 B:0 S:0
default     21:38:05.186491-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMinFrameDurationInternal:]: MinFrameDuration to set 1 / 30
default     21:38:05.186516-0500    Taelmoor        <<<< AVCaptureFigVideoDevice >>>> -[AVCaptureFigVideoDevice _setActiveVideoMaxFrameDurationInternal:]: MaxFrameDuration to set 1 / 30
default     21:38:05.186614-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_updateRunningCondition: <0x10f4b71b0[2747][com.delvebros.taelmoor]> ClientStartedSession:0 Cam/Audio:1/0 bg:0 prewarming:0 int:0 multitasking:0 pip:0 devStolen:0 pressured:0 active:0 shouldRun:0 start:0 stop:0 stopRecordingIfActive:0
default     21:38:05.186697-0500    mediaserverd    <<<< FigCaptureClientSessionMonitor >>>> -[FigCaptureClientSessionMonitor _updateClientStateCondition:newValue:]: <0x10f390e40[2747][com.delvebros.taelmoor]> Updating client state condition "_bksApplicationState" with new value "ForegroundRunning"
default     21:38:05.186733-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_updateRunningCondition: <0x10f4b71b0[2747][com.delvebros.taelmoor]> ClientStartedSession:1 Cam/Audio:1/0 bg:0 prewarming:0 int:0 multitasking:0 pip:0 devStolen:0 pressured:0 active:0 shouldRun:1 start:1 stop:0 stopRecordingIfActive:0
default     21:38:05.186758-0500    mediaserverd    <<<< FigCaptureClientSessionMonitor >>>> -[FigCaptureClientSessionMonitor _updateClientStateCondition:newValue:]: <0x10f390e40[2747][com.delvebros.taelmoor]> Updating client state condition "_layoutState" with new value "Fullscreen"
default     21:38:05.186806-0500    mediaserverd    <<<< FigCaptureClientSessionMonitor >>>> -[FigCaptureClientSessionMonitor _updateClientStateCondition:newValue:]: <0x10f390e40[2747][com.delvebros.taelmoor]> Updating client with application state "Foregrounded" and layout state "Fullscreen"
default     21:38:05.186870-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_updateRunningCondition: <0x10f4b71b0[2747][com.delvebros.taelmoor]> ClientStartedSession:1 Cam/Audio:1/0 bg:0 prewarming:0 int:0 multitasking:0 pip:0 devStolen:0 pressured:0 active:1 shouldRun:1 start:0 stop:0 stopRecordingIfActive:0
default     21:38:05.187016-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_transitionToSessionStatus: <0x10f4b71b0[2747][com.delvebros.taelmoor]> Idle -> Starting Running
default     21:38:05.187167-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_commitInflightConfiguration: <0x10f4b71b0[2747][com.delvebros.taelmoor]> committing configuration FigCaptureSessionConfiguration 0x10fef9a70: ID 24, AVCaptureSessionPresetHigh multiCam: 0, appAudio: 1, autoConfig: 1, runWhileMultitasking: 0    VC 0x10fe111e0: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (FD E:0 B:0 S:0), HR:1, FaceDrivenAEAFMode:3, FaceDrivenAEAFEnabledByDefault:1> -> <SINK 0x10fe11230:VideoData discards:1, preview:0, stability:0>, BGRA/1920x1080, E:1, VIS:0, M:0, O:Landscape Right, RBC:12, CIM:0    VC 0x10fe60100: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (FD E:0 B:0 S:0), HR:1, FaceDrivenAEAFMode:3, FaceDrivenAEAFEnabledByDefault:1> -> <SINK 0x10fe601a0:VideoPreview depth:0 filters:0 [] Portrait Lighting effect strength: 0.0 PrimaryCaptureRectModification:0, Aspect:0.000:1, Center:0.500 0.500, UniqueID:0>, /1080x1920, E:1, VIS:0, M:0, O:Portrait, RBC:0, CIM:0    MOC 0x10fe60250: <SRC:wide back 420f/1920x1080(19), 30-30(max:30), Z:1.00, ICM:0, (
default     21:38:05.397697-0500    SpringBoard     Adding sensor usage data for CAMERA [bundle:com.delvebros.taelmoor display:Taelmoor attribution:com.delvebros.taelmoor recently:NO]
default     21:38:05.401211-0500    SpringBoard     <<<< AVControlCenterModules >>>> AVControlCenterModulesShouldBeShownForBundleID: called for bundleID: com.delvebros.taelmoor
default     21:38:05.401292-0500    SpringBoard     Setting visibility of AV modules to NO for bundle identifer com.delvebros.taelmoor
default     21:38:05.401895-0500    SpringBoard     [SensorActivity][PIPWindowHidden] Interrupting PIP for camera activity: attribution[<SBSensorActivityAttribution: 0x2820d5960; displayName: Taelmoor; bundleIdentifier: com.delvebros.taelmoor; bundleIdentifierMatchingDisplayName: com.delvebros.taelmoor; sensor: camera>] bundleIdentifier[com.delvebros.taelmoor]
default     21:38:05.402081-0500    SpringBoard     [Assertions] Interrupting for assertion: <SBPIPInterruptionAssertion: 0x281277240; identifier: SBPIPController-com.delvebros.taelmoor; reason: SBPIPBehaviorOverrideReasonCameraSensorActivity; valid: YES; camera sensor bundle identifier: com.delvebros.taelmoor>
default     21:38:05.402170-0500    SpringBoard     -[PGPictureInPictureController pictureInPictureInterruptionBeganWithReason:attribution:] camera com.delvebros.taelmoor
default     21:38:05.402318-0500    SpringBoard     Sensor activity changed: Active: {(    <SBSensorActivityAttribution: 0x2820d5960; displayName: Taelmoor; bundleIdentifier: com.delvebros.taelmoor; bundleIdentifierMatchingDisplayName: com.delvebros.taelmoor; sensor: camera> )} Recent: (null)
default     21:38:05.430270-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_transitionToSessionStatus: <0x10f4b71b0[2747][com.delvebros.taelmoor]> Starting Running -> Running
default     21:38:05.430362-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_transitionToSessionStatus: <0x10f4b71b0[2747][com.delvebros.taelmoor]> Starting took 241.3ms
default     21:38:05.534229-0500    mediaserverd    <<<< FigCaptureSession >>>> captureSession_updateDeferredGraphSetupStartCondition: <0x10f4b71b0[2747][com.delvebros.taelmoor]> Did display first preview frame
```

Now, I have no real idea what is going on here, but the difference seems to be those extra `FigCaptureClientSessionMonitor` logs. I've reproed this a number of times, and the logs are always the same. When the `BarCodeScanner` renders successfully, there are two `FigCaptureSession` logs followed by one from `FigCaptureClientSessionMonitor`, followed all the min/max frame duration stuff.

By contrast, every time when the app locks up, there are those _four_ `FigCaptureClientSessionMonitor` logs, followed by _one_ `FigCaptureSession` log, followed by... _silence_. There is never any error or anything like that and we never make it to the min/max frame durations.

Seems like maybe something is happening out of order here. Does `captureSession_SetConfiguration` have to run before `captureSession_updateRunningCondition`? Is there a race condition with `_updateClientStateCondition`? I don't know. Can one of those recommended consultants can come up with a workaround for me? If I write a PR, how long before it makes it to release?

**Comment by brentvatne** [comment]
> Unfortunately expo-camera does not scan QR codes on iOS, and anything else would mean dropping Expo Go from the workflow. At that point I might as well eject Expo altogether you know?

why? you can still use `expo-dev-client` to create an Expo Go-like development build - that's the whole idea of the library

> If I write a PR, how long before it makes it to release?

you wouldn't even need us to release it, you could use `patch-package` to apply your changes to your node_modules directly or use your fork from GitHub

**Comment by delventhalz** [comment]
My impression is that Expo is a set of golden handcuffs. When it works it really works great. Expo Go is an amazing dev experience. Truly. But when it doesn't work? Too bad. Handcuffs.

At this point I have thrown a lot of good time after bad trying to track down this crash or find an acceptable alternative. Maybe I didn't give `expo-dev-client` enough of a chance last week. Maybe I'll take another look at it in the morning. But I am running out of time to mess around and also kind of thinking it is just time to cut bait.

In any case, you take care. Thanks for the helpful and earnest suggestions. Hope the logs come in handy.

**Comment by brentvatne** [comment]
> My impression is that Expo is a set of golden handcuffs. When it works it really works great. Expo Go is an amazing dev experience. Truly. But when it doesn't work? Too bad. Handcuffs.

this used to be the case, but this is the entire point for why we built expo-dev-client and EAS Build. Expo Go is a great way to get started (thus "Go" - like "get going quickly" and that sort of thing) but most projects will eventually reach the point where they will want to use a development build in order to have more control. let me know what you think when you've had a chance to give it a shot.

**Comment by brentvatne** [comment]
> The next step will be ejecting Expo, which I would really rather avoid.

to clarify, there is no such thing as "ejecting Expo" anymore. you can run [`npx expo prebuild`](https://docs.expo.dev/workflow/prebuild/) and that will generate your iOS and Android native projects. this is what EAS Build does every time it builds your app - it runs prebuild and then compiles it. after you run `npx expo prebuild` to generate the native projects, you can continue to use all expo packages and EAS services, you just now have access to modifying the native project. some developers will want to do this and I would encourage that you do if you want to [debug your app in Xcode](https://docs.expo.dev/workflow/debugging/#native-debugging) or make direct changes to your native project.

**Comment by delventhalz** [comment]
Looks like #19199 is the same issue, and the author there provided a Snack demo demonstrating it:

https://snack.expo.dev/@unktomi/barcode-scanner

The key element present in both this demo and my own app is the modal. It appears that mounting Expo's bar code scanner while iOS's modal is animating in is playing russian roulette with threading or some such. I'm still thoroughly testing my fix, but it appears that if you wait to mount the scanner until the modal animation is done the crashes will vanish.

**Comment by jrocks3333** [comment]
@brentvatne I've run into the same issue and was able to solve it by switching to the expo-camera module rather than using expo-barcode-scanner. I believe the expo-barcode-scanner module was having issues particularly when used in tandem with react-navigation. I believe the bug occurs when a BarCodeScanner component is rendered before the previously rendered BarCodeScanner component is completely unmounted. For some reason, the Camera component from expo-camera does not seem to have this issue. The expo-camera module even has support for the camera flash among many other useful functions! I hope it solves your problem :)

Note: Just make sure to add `key={scanned ? 1 : 2}` to your Camera component if you're having trouble scanning a barcode the 2nd time!

**Comment by nathanael-rsu** [comment]
> @brentvatne I've run into the same issue and was able to solve it by switching to the expo-camera module rather than using expo-barcode-scanner. I believe the expo-barcode-scanner module was having issues particularly when used in tandem with react-navigation. I believe the bug occurs when a BarCodeScanner component is rendered before the previously rendered BarCodeScanner component is completely unmounted. For some reason, the Camera component from expo-camera does not seem to have this issue. The expo-camera module even has support for the camera flash among many other useful functions! I hope it solves your problem :)

This seems to have been the fix for us. Literally switching from:

```
<BarCodeScanner
    onBarCodeScanned={onScan}
/>
```

to 

```
<Camera
    onBarCodeScanned={onScan}
/>

**Comment by delventhalz** [comment]
Figured I'd pull out the old Expo version of my game and give this `expo-camera` workaround a try.... and it works!

I've only done some quick tests, but I basically just swapped out `BarCodeScanner` for `Camera` and everything seems to work fine. I was unable to trigger a freeze after some ~200 attempts. In my case (scanning QR codes), I did not need to populate the `barCodeScannerSettings` at all. QR codes seem to be covered by the defaults.

So it is too late for me, but for anyone doing QR scans in Expo in the future, just treat `expo-barcode-scanner` as if it is deprecated. I don't know of any features it has that `expo-camera` does not, and it has some showstopper bugs that have not been addressed in nearly half a year.

**Comment by delventhalz** [comment]
A couple of addendums from my time trying to debug this issue that might prove helpful:

- It turns out you _can_ trigger the crash from Expo Go, so if you are trying to debug you don't have to go through a whole build
- I was using react-router like many others with this issue. The QR scanner was in a modal, and in testing I often triggered the crash by rapidly opening and closing the modal. That said, I am doubtful that the issue is two scanners being rendered at once, unless old react-router modals sometimes stick around for a very long time. In attempting to work around this issue I experimented with delays in rendering the scanner. Even when I artificially waited multiple seconds before rendering the scanner, I was still able to trigger crashes. The app also frequently crashed during play tests, and players do not usually rapidly open and close the modal. And my memory is fuzzy at this point, but I remember the app freezing when it was the first time I opened the scanner in quite awhile, multiple minutes.
- #19199 appears to be the same issue and includes a great minimum reproducible demo of the crash: https://snack.expo.dev/@unktomi/barcode-scanner

**Comment by delventhalz** [comment]
Hey @brentvatne, a quote from the comment directly above your bot:

> #19199 appears to be the same issue and includes a great minimum reproducible demo of the crash:  https://snack.expo.dev/@unktomi/barcode-scanner

Not to mention the MRE from my original Issue post nearly _six months ago_.

This is a consistent, reproducible, _breaking_  issue with `expo-barcode-scanner` that has been clearly documented by multiple users. If it is your position that the issue will not be fixed, then mark `expo-barcode-scanner` as deprecated and point your users to a working alternative like `expo-camera`.

**Comment by brentvatne** [comment]
hi @delventhalz, this was triaged as part of an automatic issue validation process in order to attempt to get control over issues, as there was too much noise for us to work through. we ask that a minimal reproducible example is a clonable github repo or link to a snack that we can run. our issue validation looks for links to git repos or snacks. this was not always so well articulated, and apologies if this is confusing now. six months indeed is a long time, and sadly this was buried. as we filter our issues down to a smaller list of actionable issues we can work through those. if you'd like to dig in to the issue and open a pr, that would also be welcome.

**Comment by delventhalz** [comment]
I mean, if I didn't open a PR when you told me to six months ago, I'm not sure why I would now that I have given up on Expo.

¯\\\_(ツ)_/¯

**Comment by tecnodatasystem** [comment]
Hi, we still experiencing the same issue that you figured out.
The crash log says:

```
Your app just crashed. See the error below.
NSInvalidArgumentException: *** -[AVCaptureMetadataOutput setMetadataObjectsDelegate:queue:] NULL queue passed
  0   CoreFoundation                      0x00000001a4ad8e44 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 40516
  1   libobjc.A.dylib                     0x000000019dc6f8d8 objc_exception_throw + 60
  2   AVFCapture                          0x00000001bdce5788 B0787ED4-DD51-3B92-93D0-3CAC03EFF611 + 235400
  3   Sunspot                             0x000000010418be00 -[EXBarCodeScanner maybeStartBarCodeScanning] + 372
  4   Sunspot                             0x000000010418bc4c __33-[EXBarCodeScanner setIsEnabled:]_block_invoke + 152
  5   libdispatch.dylib                   0x00000001ac0ef460 DED4D0A5-1420-32AE-83A6-C31D938A1C9A + 9312
  6   libdispatch.dylib                   0x00000001ac0f0f88 DED4D0A5-1420-32AE-83A6-C31D938A1C9A + 16264
  7   libdispatch.dylib                   0x00000001ac0f8640 DED4D0A5-1420-32AE-83A6-C31D938A1C9A + 46656
  8   libdispatch.dylib                   0x00000001ac0f918c DED4D0A5-1420-32AE-83A6-C31D938A1C9A + 49548
  9   libdispatch.dylib                   0x00000001ac103e10 DED4D0A5-1420-32AE-83A6-C31D938A1C9A + 93712
  10  libsystem_pthread.dylib             0x00000001f2d50df8 _pthread_wqthread + 288
  11  libsystem_pthread.dylib             0x00000001f2d50b98 start_wqthread + 8
```

Is there a solution to solve this issue? It occurs randomly.
