### ISSUE TITLE
"$expo start" not opening the metro bundler in chrome anymore

### ISSUE THREAD

**Issue by storycoding** [expo/expo#19069]
### Summary

Running expo start used to automatically open a useful UI on the browser in regards to the Metro Bundler, and now it's gone from all the boilerplate apps, so I can only assume it's been dropped by expo itself?

The bundler runs on the terminal, but its features pale in comparison with this UI.

I've spent a good amount of hours googling this, and tried it in different laptops with different repos and boilerplate code.

Has anyone found a solution to get this running once again?

here's a screenshot of the intended result:

[screenshot](https://i.stack.imgur.com/KyETM.png)

### What platform(s) does this occur on?

Not Applicable

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 24, 27
        Build Tools: 27.0.3
        System Images: android-24 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

```
expo init appName
```
select any of the managed workflows
```
cd appName
expo start
```

**Comment by amandeepmittal** [comment]
Hey @storycoding,

The Web UI was deprecated a while back. Please read the full announcement in this blog post: https://blog.expo.dev/sunsetting-the-web-ui-for-expo-cli-ab12936d2206 

You can create your own since the code for it is open source: https://github.com/expo/expo-cli/tree/main/packages/dev-tools

**Comment by storycoding** [comment]
Thank you, @amandeepmittal !

**Comment by JunaidKhan444** [comment]
Thanks a lot @amandeepmittal

**Comment by cecc9** [comment]
and me breaking my head, Thanks @amandeepmittal

**Comment by Juraij70** [comment]
can someone explain how to create own Metro Bundler  as mentioned above? I'm very new to this and have been stuck for a week now.
