### ISSUE TITLE
expo-server-sdk-node package.json has broken links

### ISSUE THREAD

**Issue by ckknight** [expo/expo#1906]
https://github.com/expo/exponent-server-sdk-node/blob/master/package.json contains many links to a non-existent URL https://github.com/expo/expo-server-sdk-node (rather than the working https://github.com/expo/exponent-server-sdk-node)

Note that it is also confusing to have `exponent` in the repository name and `expo` in the npm package name.

**Comment by jimmylee** [comment]
Thanks for bringing this to our attention @ckknight I've assigned @ide to take a quick look at this.

**Comment by ide** [comment]
We'll update the links shortly. Renaming the repo is more work than it seems because of how the shipit bot works so we've left it as-is.

**Comment by ide** [comment]
We made it so that https://github.com/expo/expo-server-sdk-node redirects to https://github.com/expo/exponent-server-sdk-node now, so the links should work.
