### ISSUE TITLE
Mail composer and SMS composer on iOS don't always resolve

### ISSUE THREAD

**Issue by Adam-Schlichtmann** [expo/expo#19062]
### Summary

When using `sendSMSAsync`  from `expo-sms` or `composeAsync` from `expo-mail-composer` if you click outside of the modal on iOS the promise never resolves. 

Expected: The promise for `sendSMSAsync` or `composeAsync` should resolve when the modal closes

Actual: The promise never resolves and attempts at reopening the modal do not work.

### What platform(s) does this occur on?

iOS

### Environment

Recreated in Expo Snack with latest versions

```json
{
  "dependencies": {
    "react-native-paper": "4.9.2",
    "@expo/vector-icons": "^13.0.0",
    "expo-constants": "~13.2.4",
    "expo-mail-composer": "~11.3.0",
    "expo-sms": "~10.2.0"
  }
}
```

### Minimal reproducible example

Here is a snack: https://snack.expo.dev/@dmsi/54cc54

**Comment by keith-kurak** [comment]
Hi @Adam-Schlichtmann! Is there a particular device for which you experience this issue (e.g., iPad)? I can't reproduce on my iPhone, as it does not let me tap outside of the modal.

Looking more closely at the code, can you confirm if, when tapping outside of the modal, the code reaches this `catch` block, and, if so, could you see what error message it provides?

```
sendSMSAsync([], 'Hello')
            .then((result) => {
              setDidItResolve(true);
              console.log(result);
            })
            .catch((err) => {
              setDidItResolve(false);
            });
```

I'm wondering if we may be limited by Apple's API here. Apple's mail composer API predictably tells us the request has been cancelled when pressing the Cancel button, but it sounds possible that, in your case, it may actually be telling us that the request "failed".

**Comment by Adam-Schlichtmann** [comment]
Hi @keith-kurak, thanks for the response!

I was testing this on an iPad Air 3. 

I updated the snack to show if the catch block is running, but I am still partially having the same issues. 

I do notice now that when trying to open it for the second time it is actually rejecting, which is good. 

Same Snack as before: https://snack.expo.dev/@dmsi/54cc54

**Comment by Adam-Schlichtmann** [comment]
@keith-kurak Is there any update on this?
