### ISSUE TITLE
[Jest-Expo] platform-specific test not running react-native code?

### ISSUE THREAD

**Issue by jeremymeng** [expo/expo#19064]
### Summary

We have a package that has "react-native" mapping for some files:
https://github.com/jeremymeng/azure-sdk-for-js/blob/rn/jest-expo-test/sdk/core/core-rest-pipeline/package.json#L16-L20

However, when I add a test and target android preset, I found that that the mapped files are not executed when running the test. Instead, the NodeJS CommonJS version (dist/index.js) is used. I checked this by adding some console.log() lines in `createDefaultHttpClient()` functions of these files.

**Expect behavior**: I would expect that "react-native" mapping is respected and proper files are used when executing test against native preset targets. I was expecting that createDefaultHttpClient() from `./dist-esm/src/defaultHttpClient.native.js` is used.

**Actual behavior**: createDefaultHttpClient() from `./dist/index.js` was invoked instead.

**Note** when the code is running in an App on Android Emulator, I got the expected behavior.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/jeremymeng/azure-sdk-for-js/blob/rn/jest-expo-test/samples/frameworks/react-native-expo/ts/pkgtest/azsdk.test.ts

The mini repro project is a fresh copy of the TS template, plus [one commit to add the test](https://github.com/Azure/azure-sdk-for-js/commit/f4dbe3a8884b26d8a1c527c320d439d55663f49d).

**Comment by byCedric** [comment]
Hi @jeremymeng! Thanks for flagging this. Unfortunately, this is not fully in our control and requires some patching from the whole RN community. A couple of points:

1. React Native seems to have some incompatibilities with `jest@>26`, [more details here](https://github.com/facebook/react-native/issues/34289).
2. Jest 26 does not support ESM out of the box. As of writing, [ESM support is still experimental with 28](https://jestjs.io/blog/2022/04/25/jest-28#packagejson-exports). This is worsened by React Native being stuck on 26 for the time being.
3. Metro doesn't support ESM `exports`. There is an [open issue here](https://github.com/facebook/metro/issues/670) with more details. One core contributor to Jest started a proposal to [make RN integrate better with Jest](https://github.com/react-native-community/discussions-and-proposals/issues/509), might be good to keep an eye on that too or maybe contribute 😄 

This makes it very hard for us to support ESM for testing and normal React Native usage. Until these blockers are fixed, I'm not 100% sure how we can fix this.

Hope this helps!

**Comment by SimenB** [comment]
RN doesn't support native ESM either - that part only works since metro transforms and/or bundles the code. So the experimental ESM support shouldn't affect anything - you need to point `babel` (or whatever your metro config uses to transpile) at the code regardless.

As for the `react-native` field in package.json, I've opened https://github.com/react-native-community/discussions-and-proposals/issues/512
