### ISSUE TITLE
Location altitude not WGS84 on iPhone

### ISSUE THREAD

**Issue by pwellner** [expo/expo#19072]
### Summary

Doc states that altitude is in "meters above the WGS 84 reference ellipsoid"  so Andoid and iPhone should report similar altitudes from the same location, but they report different altitudes, apart roughly by the difference between MSL (mean sea level) and WGS84.  At my location (near Syracuse NY) that difference is about 33 meters.

Perhaps the iPhone implementation is not using [ellipsoidalAltitude](https://developer.apple.com/documentation/corelocation/cllocation/3861801-ellipsoidalaltitude)?  If not, it should.

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 3.2.1 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
    npmPackages:
      expo: ^45.0.6 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.56.0
      expo-cli: 6.0.2
    Expo Workflow: bare
```

### Minimal reproducible example

Use location example as-is from the [doc](https://docs.expo.dev/versions/latest/sdk/location/) and compare altitude from iPhone and Android.
Use [this module](https://www.npmjs.com/package/egm96-universal) to estimate the difference between MSL and WGS84 at your location to see if the difference is similar.

**Comment by byCedric** [comment]
Hi @pwellner, thanks for flagging this! It seems that the iOS implementation indeed does not use `ellipsoidalAltitude` ([implementation](https://github.com/expo/expo/blob/main/packages/expo-location/ios/EXLocation/EXLocation.m#L570) vs [Apple docs](https://developer.apple.com/documentation/corelocation/cllocation)).

I've marked this as an accepted issue but have no timeline yet for when this is fixed. If you want to contribute, I'd be happy to review a PR 😄 

Thanks!

**Comment by issepela** [comment]
In the mean time
i created a version of it with a corrected code, they are just 3 lines in a couple of files

https://github.com/issepela/my-expo-location
