### ISSUE TITLE
> Could not read script '..expo-modules-core/gradle.groovy' as it does not exist.

### ISSUE THREAD

**Issue by aaryavrate** [expo/expo#19074]
### Summary

> Could not read script '..expo-modules-core/gradle.groovy' as it does not exist.

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.6.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.13.2 - /opt/homebrew/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/prabhatsingh/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-32 | Google APIs ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1 
      expo: ^46.0.0 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      expo-cli: 5.4.6
    Expo Workflow: bare

### Minimal reproducible example

Installing https://www.npmjs.com/package/expo-modules-core

After setting up build.gradle and settings.gradle, the error happens.
Seems like gradle.groovy files do not exist anymore.

**Comment by haveamission** [comment]
@aaryavrate How did you ultimately solve this issue?
