### ISSUE TITLE
Not able to write table to db using sqlite expo anyone can help me with this. I am getting com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String this error.

### ISSUE THREAD

**Issue by santoshbyrappa** [expo/expo#1907]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please use `exp send` with exp, the “Send” button with XDE, or the "s" hotkey with create-react-native-app to send your project development URL to your phone by SMS or email.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by santoshbyrappa** [comment]
I am not able to create table inside the db created using sqlite expo. As there is some permission issue with my react native app.

**Comment by jimmylee** [comment]
Hey @santoshbyrappa ! Thanks for checking out Expo.

We want to be able to help you out, but if you don't fill out the issue template questions and give us more information there is no way we can effectively help you. 

Everyday issues come up, and a lot of people take the the time to make sure we have the information we need to help them. Trust me, we want to help!

Feel free to come back with more details when you get the chance.
