### ISSUE TITLE
Expo Location watchHeadingAsync not working on Android

### ISSUE THREAD

**Issue by AmedeoOfficial** [expo/expo#19071]
### Summary

I am writing an app that requires me to track the heading of the user's device. Everything works fine on iOS, but on Android the heading is very unstable and flickers between 2 values very often:

Log output:
```
angle: 17.43
angle: 358.7
angle: 17.43
angle: 358.7
```
Here is my code:

```
onVidLoad(){
        Location.watchHeadingAsync(this.onHeadingUpdate).then((v) => {
            this.ang_listener = v;
        });
    }

    onHeadingUpdate = (h) => {
        var angle = h.trueHeading;
        angle -= 180;
        angle *= -1;
        angle += 180;

        console.log("angle:", angle);
    }
```
Thanks in advance.

EDIT: I am using Location.requestForegroundPermissionsAsync every time the app starts, so the problem isn't that I don't have the correct permissions

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-30 | Google Play Intel x86 Atom
    npmPackages:
      @expo/metro-config: ^0.3.2 => 0.3.21
      expo: ^46.0.0 => 46.0.2
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.3 => 0.69.3
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@amedeoofficial/petrified-peach

**Comment by AmedeoOfficial** [comment]
Any updates?

**Comment by keith-kurak** [comment]
Hi @AmedeoOfficial!

When you run this snack, can you see what value for the [accuracy](https://docs.expo.dev/versions/latest/sdk/location/#locationheadingobject) prop you get in that same object coming back from `watchHeadingAsync`? 358 and 17 aren't actually that far apart (within 20 degrees), so it's possible that, within the parameters of your phone/ location/ whatever else could affect compass accuracy, this is correct.

**Comment by AmedeoOfficial** [comment]
I have checked the accuracy, and it is 3

**Comment by AmedeoOfficial** [comment]
Has anyone found a solution yet?

**Comment by keith-kurak** [comment]
@AmedeoOfficial accuracy level 3 means "within 20 degrees", and the difference between 358 and 17 is 19 degrees, so this seems like it could be intended behavior. I did try to reproduce this, and in my case, the accuracy was higher and I did see additional increments between those values.

**Comment by AmedeoOfficial** [comment]
I don't think that you understand my problem. The angle is constantly flickering between these 2 values with no way for me to control or predict it.

**Comment by AmedeoOfficial** [comment]
Here are the measurements that I collect when I rotate the device clockwise:
```
-10.756927490234375
-12.9041748046875
-10.64691162109375
347.04156494140625
22.564605712890625
347.0725402832031
31.48297119140625
347.0725402832031
312.1084899902344
```

**Comment by AmedeoOfficial** [comment]
@keith-kurak ?
