### ISSUE TITLE
ImagePicker iOS camera cropping issue

### ISSUE THREAD

**Issue by S4ffron** [expo/expo#19081]
### Summary

After having taken the photo with iOS camera, when it gets to cropping the image, the screen doesn't let you move the camera to select the area you want to crop. Instead, it keeps bouncing back to the original position.

This only happens on iOS.

[https://snack.expo.dev/@redsaffron/imagepickeissue](url)

Video:
[https://drive.google.com/file/d/19ondWBekSEf-ocxUqQ4rOwijWAY0UPCn/view?usp=sharing](url)

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/metro-config: ^0.3.22 => 0.3.22
      expo: ~45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Minimal reproducible example

[https://snack.expo.dev/@redsaffron/imagepickeissue](url)

**Comment by Kudo** [comment]
hi there! this is a known issue from iOS `UIImagePickerController` and as a duplicated issue for https://github.com/expo/expo/issues/10820#issuecomment-845429650. i'm going to close this issue. if #10820 is not the same as the problem you encountered, please let me know and i'm happy to reopen this. thanks!
