### ISSUE TITLE
eas is not uploading my app to test flight

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo#19086]
### Summary

When using eas build -p ios my app gets build successfully and I can download an ipa file. But the app's build does not show up in test flgiht. 

https://expo.dev/accounts/mikechambers610/projects/phillyeventfinder/builds/141edbfc-c324-4f48-ad5e-9f2c8b79aa44

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.19.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@apollo/react-hooks": "^4.0.0",
    "@aws-amplify/api": "^4.0.51",
    "@aws-amplify/auth": "4.6.4",
    "@aws-amplify/core": "4.7.2",
    "@aws-sdk/client-pinpoint": "3.154.0",
    "@expo-google-fonts/ovo": "^0.2.0",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "~1.17.10",
    "@react-native-community/cli-debugger-ui": "^4.9.0",
    "@react-native-community/datetimepicker": "6.1.2",
    "@react-native-community/netinfo": "8.2.0",
    "@react-native-picker/picker": "2.4.0",
    "@redux-offline/redux-offline": "^2.6.0-expo.0",
    "@wora/apollo-cache": "^2.2.0",
    "@wora/apollo-offline": "^2.4.0",
    "amazon-cognito-identity-js": "^4.5.1",
    "apollo-cache-inmemory": "^1.3.12",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "apollo-link-http": "^1.5.17",
    "apollo-link-state": "^0.4.2",
    "aws-amplify": "^4.3.33",
    "aws-amplify-react-native": "^6.0.5",
    "aws-appsync": "^3.0.4",
    "aws-appsync-auth-link": "^2.0.8",
    "aws-appsync-react": "^4.0.5",
    "aws-appsync-subscription-link": "^2.2.0",
    "babel-preset-expo": "8.3.0",
    "country-code-lookup": "0.0.17",
    "country-list": "^2.2.0",
    "countrycodes": "0.0.5",
    "dateformat": "^5.0.3",
    "expo": "^45.0.0",
    "expo-app-loading": "~2.0.0",
    "expo-av": "~11.2.3",
    "expo-barty-credit-card-input": "^0.4.5",
    "expo-camera": "~12.3.0",
    "expo-cli": "^3.21.13",
    "expo-constants": "~13.1.1",
    "expo-contacts": "~10.2.0",
    "expo-image-manipulator": "~10.3.1",
    "expo-image-picker": "~13.1.1",
    "expo-intent-launcher": "~10.2.0",
    "expo-linking": "~3.1.0",
    "expo-location": "~14.2.2",
    "expo-mail-composer": "~11.2.0",
    "expo-media-library": "~14.1.0",
    "expo-network": "~4.2.0",
    "expo-notifications": "~0.15.4",
    "expo-permissions": "~13.2.0",
    "expo-screen-orientation": "~4.2.0",
    "expo-sms": "~10.2.0",
    "expo-status-bar": "~1.3.0",
    "expo-stripe-checkout": "^1.0.1",
    "expo-web-browser": "~10.2.1",
    "geolib": "^3.3.3",
    "graphql": "^14.7.0",
    "graphql-compose": "^9.0.1",
    "graphql-tag": "^2.11.0",
    "immutability-helper": "^3.0.0",
    "jetifier": "^1.6.8",
    "lodash": "^4.17.21",
    "react": "17.0.2",
    "react-apollo": "^2.5.6",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-aws3": "0.0.8",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-dev-menu": "^4.0.2",
    "react-native-fit-image": "^1.5.5",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-get-random-values": "^1.8.0",
    "react-native-google-places-autocomplete": "^1.8.0",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-input-scroll-view": "^1.7.1",
    "react-native-inviewport": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-loading-spinner-overlay": "^2.0.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^11.3.1",
    "react-native-modal-dropdown": "^0.7.0",
    "react-native-phone-input": "1.3.4",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-search-box": "0.0.19",
    "react-native-searchbar": "^1.15.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-timeago": "^0.4.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-view-more-text": "^2.1.0",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1",
    "react-navigation": "^4.4.0",
    "react-navigation-addons": "0.0.0",
    "react-navigation-drawer": "^2.5.0",
    "react-navigation-stack": "^2.8.2",
    "react-navigation-tabs": "^2.9.0",
    "react-number-format": "^4.0.8",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "recompose": "^0.30.0",
    "redux": "^3.7.2",
    "redux-offline": "^2.0.0",
    "redux-thunk": "^2.2.0",
    "shuffle-array": "^1.0.1",
    "stripe-client": "^1.1.5",
    "uuid": "^3.3.3",
    "expo-splash-screen": "~0.15.1"
  },
  "resolutions": {
    "amazon-cognito-identity-js": "4.5.1",
    "@types/react": "~17.0.21"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@expo/metro-config": "^0.1.84",
    "babel-preset-expo": "9.0.2"
  },
  "private": true,
  "name": "NEWAPP1",
  "version": "1.0.0"
}

**Comment by JacobJaffe** [comment]
Have you run `eas submit`? Or adding `--auto-submit` to `eas build` ? 

Be sure to follow https://docs.expo.dev/submit/ios/ -- building and submission are different steps. For a first time iOS submission, you will need to follow the guides for configuration as well

**Comment by mikeRChambers610** [comment]
I think somehow my app went from managed to bare when I upgraded from Exxpo SDK 44 to 45. I will work on trying to upgrade the 44 version to 45 again and see if I have the same issues.
