### ISSUE TITLE
`softwareKeyboardLayoutMode` does not work on classic builds

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#19088]
### Summary

Yesterday I updated one of my applications from SDK44 to SDK46 and I did a classic build and checking the `AndroidManifest.xml` of the generated APK I see that the `android:windowSoftInputMode` is set to `adjustResize` when it should be set to `adjustPan` as is it is defined in my `app.config.js` inside `softwareKeyboardLayoutMode`.

I did a test with another project that also uses the SDK46 and has the EAS Build configured, and it works perfectly, the `app.config.js` configuration is respected.

I continued investigating, and I did a couple more tests, I created two blank projects, one with SDK44 and the other with SDK45, I did a classic build on them and the same thing, the definition of the `softwareKeyboardLayoutMode` is not respected.

At some point (I don't know exactly when) this feature stopped working or was broken for classic builds.

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 3.2.3 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.10 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Minimal reproducible example

1. ```npx create-expo-app expo-app-sdk46```
2. In `app.json`, add `"softwareKeyboardLayoutMode": "pan"` inside the `"android"` section
3. ```expo build:android -t apk```
4. Open the `AndroidManifest.xml` of the generated APK and verify that the `android:windowSoftInputMode` references are still `adjustResize` instead of `adjustPan`

**Comment by Kudo** [comment]
hi there! thanks for reaching out to us. as far as i can tell, the `softwareKeyboardLayoutMode` used [a different way](https://github.com/expo/expo/pull/8842) to change the layout mode on classic build. so the *AndroidManifest.xml* is still the same as-is, we just read the value from expo manifest. if there're regression issues on classic build toward the `softwareKeyboardLayoutMode`, please let us know and i'll reopen this issue. thank you!

**Comment by outaTiME** [comment]
Kudo, thanks for your clarification 🙌
I always thought that the `AndroidManifest.xml` reflected what was defined on the Expo manifest.
Now, seeing the PR of Brent I clearly see that for the classic builds it is solved by code.

**Comment by AndonMitev** [comment]
Hey, for some reason `pan` is working as `resize`, keyboard is not overlaying the items any idea

**Comment by VictorioMolina** [comment]
@AndonMitev Same problem.

**Comment by thomasdelobel** [comment]
Still
