### ISSUE TITLE
has no way to simulate the setting change of the permission after user is denied in the Expo Go

### ISSUE THREAD

**Issue by monaye** [expo/expo#19093]
### Summary

per comments from @byCedric  here https://github.com/expo/expo/issues/16701#issuecomment-1080693258

> Expo Go has a scoped permission system to run multiple projects
During development, we use a system to "scope" permissions to certain Expo projects. Even though the user has granted full access for single permission, the project (or "experience" as we call them) needs to re-request the permission. This get's you closer to real-world scenarios when dealing with permissions. And because of point 3, Expo Go doesn't know you granted access to that project. That would still require a requestXPermissionAsync call to set the scoped permissions properly.

if I understand correctly:  **in the Expo Go**, even if the App asks a user to change the settings after a user is denied, the changes will never reach the App inside the Expo Go. 

But, if that's the case, is there a way to change the permission setting of the App inside the Expo Go to simulate when user denied the request for the first time and then allow it from the Setting? 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2022.08.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.7 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      eas-cli: 0.39.0
      expo-cli: 6.0.2
    Expo Workflow: managed

```

### Reproducible demo

Please use the following snack.

https://snack.expo.dev/@winmonaye/permission-sample

**Comment by keith-kurak** [comment]
Per Cedric's comments, the app (regardless of whether it's Expo Go or a standalone app), the app can read the permission after the user leaves the app to enable it in settings, but the app needs to read the permission again after the user returns to the app, and this doesn't happen with the permission shortcut hooks. You would need to use `AppState` to check when the app is active, and then read `getPermissionsAsync` at that point to see if the permissions were granted.

As this is more of a how-to-use question, heads-up that our [Forums](https://forums.expo.dev) or [Discord](https://chat.expo.dev) are the best place to ask those. Thank you!
