### ISSUE TITLE
[Official App] Undefined function on explore tab

### ISSUE THREAD

**Issue by lumlnous** [expo/expo#1909]
Hi, I have a Pixel 2 running the Android P beta. When I try to go to `explore` on the official Expo app I get this error.

"Uncaught Error: undefined is not a function (evaluating  't()')"
"tabBarOnPress@cached-bundle-kernel-1508807376-UNVERSIONED:949"
"Fatal Error"

Steps to reproduce:
1: Open Expo
2: Click explore tab at bottom

Screen Caps:
![a](https://user-images.githubusercontent.com/16916670/41775781-4442d712-75f3-11e8-8efa-e4640995bacf.gif)

**Comment by brentvatne** [comment]
Hi @lumlnous! If you restart the app does this still happen?

**Comment by brentvatne** [comment]
![explore](https://user-images.githubusercontent.com/90494/41787323-e8ad95fe-75fc-11e8-9301-f565472cb3dd.gif)

unable to repro it on my side

**Comment by lumlnous** [comment]
Yes. I've also tried restarting the phone etc.
Not sure why mine does it.

Phone info:
Pixel 2 XL
Android P Beta Build No. PPP3.180510.008

**Comment by terribleben** [comment]
Hey there, we think this is resolved now. Please update to the latest version and let us know if you're still seeing this. Thanks!
