### ISSUE TITLE
ImagePicker => base64

### ISSUE THREAD

**Issue by fredjens** [expo/expo#191]
How can i get a base64 string from the [ImagePicker](https://docs.expo.io/versions/v16.0.0/sdk/imagepicker.html)?

Looks lite it only returns and URI to the filesystem. I tried to fetch the uri using [react-native-filesystem](https://github.com/benwixen/react-native-filesystem) package, but it did not work either...

I want to send the image to S3, and was think converting it to a base64 string would be the easiest...

Am I overlooking something in Expo or React Native?

**Comment by nikki93** [comment]
Gonna look at this soon. :) Closing in favor of https://github.com/expo/expo/issues/163

**Comment by nikki93** [comment]
Oh and BTW, here is an example of uploading an `ImagePicker`-picked image: https://github.com/expo/image-upload-example

**Comment by nikki93** [comment]
Base64 image data should be available in SDK 18!

**Comment by btk** [comment]
Hey @nikki93 

I'm working on an app that needs Base64 conversation of the data picked with `ImagePicker`currently, I'm handling that with XHR operation, and it has about 250ms latency in my iPhone 6. 

![screenshot at jun 16 21-09-42](https://user-images.githubusercontent.com/5216601/27239194-98a0a65c-52d8-11e7-8d58-1a4aabfa14ba.png)

s1 is the time passed while the uri passed to child component
s2 time till XHR is done and uri converted to base64
s3 is the time passed while i'm pass this data to a WebView component, do some stuff with it on canvas, and return it to component as base64 (you can think of it like a image filtering / i know its high)

Do you think in v18 this latency will be gone?

**Comment by terribleben** [comment]
The base64 functionality in SDK 18 is implemented at the native level (obj-c and Java), e.g. https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Modules/Api/EXImagePicker.m#L149

**Comment by aswerdlow935** [comment]
...So how exactly do i get the base64 string once I have the Image from ImagePicker (or the image uri)?

**Comment by jhalborg** [comment]
I've tried the example code, but no luck:

```let formData = new FormData();
    let url: ImageModel = photos[0].fullImageUrl;
    const fileType = getElementFromURI(url, 2);
    formData.append('images', {
      url,
      name: `photo.${fileType}`,
      type: `image/${fileType}`,
    });

    let options = {
      method: 'POST',
      body: formData,
      headers: {
        Accept: 'application/json',
        'Content-Type': 'multipart/form-data',
        Authorization: `Bearer ${token}`,
      },
    };

    console.log(`${TAG} Body: ${JSON.stringify(formData)}`);
    console.log(`${TAG} Options: ${JSON.stringify(options)}`);
    const response = await fetch(path, options);
    console.log(`${TAG} response: ${response.status} `);```

Resulting log:

```EntryAPI Body: {"_parts":[["images",{"url":"file:///Users/jespermadsen/Library/Developer/CoreSimulator/Devices/A6FD537D-AC09-4640-81D7-E80E61E31E62/data/Containers/Data/Application/AD463B7B-E048-4A93-B9EF-29979CB2B6E5/Library/Caches/ExponentExperienceData/%2540jhalborg%252Fnic-app/ImagePicker/3D259F8E-79B2-49FD-98E6-E52059A58009.jpg","name":"photo.jpg","type":"image/jpg"}]]}
4:29:56 PM
EntryAPI Options: {"method":"POST","body":{"_parts":[["images",{"url":"file:///Users/jespermadsen/Library/Developer/CoreSimulator/Devices/A6FD537D-AC09-4640-81D7-E80E61E31E62/data/Containers/Data/Application/AD463B7B-E048-4A93-B9EF-29979CB2B6E5/Library/Caches/ExponentExperienceData/%2540jhalborg%252Fnic-app/ImagePicker/3D259F8E-79B2-49FD-98E6-E52059A58009.jpg","name":"photo.jpg","type":"image/jpg"}]]},"headers":{"Accept":"application/json","Content-Type":"multipart/form-data","Authorization":"Bearer THE_TOKEN "}}
4:29:56 PM
EntryAPI response: 400```

Any tips as to what I'm doing wrong is much appreciated.

**Comment by smoll** [comment]
@jhalborg not sure if this has anything to do with your problem, but it looks like you're passing an invalid mime type, `image/jpg`. If you change it to `image/jpeg` do you encounter the same behavior?

**Comment by jhalborg** [comment]
@smoll Aren't they [the same](https://stackoverflow.com/a/23424447/1409779)? 

Anyways, I got it working - but unfortunately, I don't know what changed except for my way of extracting filename and extension from the file URI. 

```
const getFilenameFromUri = (uri: string): string => {
  return uri.split('/').pop();
};

const getFileExtensionFromFilename = (filename: string): string => {
  let match = /\.(\w+)$/.exec(filename);
  let type = match ? `image/${match[1]}` : `image`;
  return type;
};

const addPhotosToFormDataBody = (body: FormData, photos: [ImageModel]) => {
  photos.forEach(function(image: ImageModel) {
    let localUri = image.fullImageUrl;
    let filename = getFilenameFromUri(localUri);
    let type = getFileExtensionFromFilename(filename);
    let imageToUpload: ImageToUpload = {
      uri: localUri,
      name: filename,
      type: type,
    };

    body.append(FORMDATA_IMAGE_KEY, imageToUpload, filename);
  }, this);
};

let body = new FormData();
helpers.addPhotosToFormDataBody(body, photos);
let xhr = new XMLHttpRequest();
xhr.open('POST', path);

xhr.onloadend = function() {
performOnLoadEnd(resolve, reject, xhr);
};

xhr.setRequestHeader('Authorization', `Bearer ${token}`);
xhr.setRequestHeader('Accept', 'application/json');
xhr.send(body);
```

Hope it helps someone

**Comment by smoll** [comment]
@jhalborg actually no, surprisingly, https://stackoverflow.com/a/37266399 but glad it worked out for you and thanks for the working example. Going to use this in a project myself soon.
