### ISSUE TITLE
EAS Build fails to upload with large files, and no way to ignore them

### ISSUE THREAD

**Issue by samtgarson** [expo/expo#19109]
### Summary

I have an app with lots of assets; I keep the raw assets checked into version control but I process them into optimised versions _before_ I upload run `eas build`.

These raw assets are pretty big. I've recently started being unable to build my app, because I'm getting a `400` error from the server at 2gb (I assume due to the file size but I have no way of knowing):
```
Compressing project files and uploading to EAS Build. Learn more
✔ Compressed project files 59s (2.1 GB)
✖ Uploading to EAS Build (2.0 GB / 2.1 GB)
    Error: Request failed: 400 (Bad Request)
```

If I delete these raw assets, the upload goes ahead ok:
```
Compressing project files and uploading to EAS Build. Learn more
✔ Compressed project files 3s (100.7 MB)
✔ Uploaded to EAS 1m 37s
```

I've tried moving the raw assets out of the directory of the expo app, but it appears expo uses `.git` (or some other method) to find the root of the project.

I've seen issues on this repo saying there is no need for ignore because the build process only bundles what is required, but this doesn't help me.

Can we get a method of defining files to ignore when uploading? Right now I have to delete the raw assets, run the build, then revert the git changes to bring back the files 😭 

### What platform(s) does this occur on?

Android, iOS

### SDK Version

45.0.5

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.asdf/installs/nodejs/16.14.2/bin/node
      Yarn: 1.22.18 - ~/.asdf/installs/nodejs/16.14.2/.npm/bin/yarn
      npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/sam/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 32
        Build Tools: 29.0.2, 32.0.0, 32.1.0, 33.0.0
        System Images: android-32 | Google APIs ARM 64 v8a, android-Tiramisu | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.5 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

Put enough files into a project to get the uploaded size over 2gb. Happy to give more info if needed.

**Comment by brentvatne** [comment]
you can use `.easignore` instead of `.gitignore` to ignore different files for EAS archiving than Git: https://expo.fyi/eas-build-archive

**Comment by brentvatne** [comment]
cc @szdziedzic - maybe we should detect large archives and let people know about `.easignore` directly in the cli

**Comment by samtgarson** [comment]
I honestly had no idea that existed, sorry! I did search around the docs and GH issues and didn't find anything, so some extra mentions either in the CLI or in the docs would be awesome.

Thanks for the quick reply 🙌

**Comment by szdziedzic** [comment]
@brentvatne sounds like a good idea! I will work on it soon 🙂

**Comment by brentvatne** [comment]
> Compressing project files and uploading to EAS Build. Learn more

the "Learn more" text links out to the same page :) but it's not always obvious so we could be more clear in cases where project archives are very large.

@szdziedzic - great, I created a task to track that internally on linear :)
