### ISSUE TITLE
Error: EACCES: permission denied, scandir

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo#19110]
### Summary

trying to do the command "eas build -p ios --auto-submit" and getting below error. 

Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
    Error: EACCES: permission denied, scandir 
    '/Users/mikechambers/Library/Saved Application 
    State/com.bitrock.appinstaller.savedState'
    Code: EACCES

### What platform(s) does this occur on?

iOS

### SDK Version

45

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.84 => 0.1.84 
      babel-preset-expo: 8.3.0 => 9.0.2 
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
      react-navigation: 4.4.4 => 4.4.4 
    Expo Workflow: managed

### Minimal reproducible example

Deleted my project folder, downloaded previous version from github, install node modules, then try to run the command "eas build -p ios --auto-submit".

**Comment by brentvatne** [comment]
it's unclear what `Library/Saved Application State/com.bitrock.appinstaller.savedState` is but it is totally unrelated to EAS CLI and Expo tools. it looks like git archiving is failing in your project due to system configuration issues. try googling "Library/Saved Application State/com.bitrock.appinstaller.savedState" to see if you can find any useful help, unfortunately this is beyond the scope of what we can help with here because it's not a bug in our tools

**Comment by mikeRChambers610** [comment]
hi Brent,

Thank you for the quick response. After downloading the zip from github and installing node modules and expo-cli and eas-cli I was still getting this error. 

Solution: Create a fresh expo project and then copy my folder inside of the new app. Now I am not having this issue. Thanks again!
