### ISSUE TITLE
Certificate pinning

### ISSUE THREAD

**Issue by vojdan** [expo/expo#1911]
Is it possible to do certificate pinning in Expo?

**Comment by esamelson** [comment]
Hi @vojdan -- this is possible if you detach your app. On Android, you can add to the `public static OkHttpClient.Builder okHttpClientBuilder` method in `MainApplication.java`. This hook is called when the OkHttp client is first being set up, so you can modify the client however you need. See the [okhttp docs](http://javadoc.io/doc/com.squareup.okhttp3/okhttp/3.6.0) for how to do this.

On iOS it's a little bit more tricky -- you may need to mess with React Native's `RCTNetworking` module, figure out how to make yourself the delegate for all `NSURLSession` requests and implement some of the code [here](https://infinum.co/the-capsized-eight/how-to-make-your-ios-apps-more-secure-with-ssl-pinning).

You're also welcome to upvote the feature request for this on canny: https://expo.canny.io/feature-requests/p/ssl-pinning . This is something we would consider exposing to JS at some point if enough people find it important.

**Comment by vojdan** [comment]
Thanks.
