### ISSUE TITLE
EAS iOS build fails at installing ffmpeg-kit-react-native

### ISSUE THREAD

**Issue by eeshankeni** [expo/expo#19113]
### Summary

HI, I believe the url EAS build is trying to access here no longer exists. Possibly something to do with [this PR](https://github.com/arthenica/ffmpeg-kit/pull/568) 

[!] /usr/bin/curl -f -L -o /var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T/d20220914-1185-dq0wj0/file.zip https://github.com/tanersener/ffmpeg-kit/releases/download/v4.5.1/ffmpeg-kit-min-gpl-4.5.1-ios-xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

This problem wasn't happening 3 days ago. 

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - S:\Spyke_FrontEnd\Spyke\Spyke-FrontEnd\node_modules\.bin\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ^46.0.7 => 46.0.7
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: managed

### Minimal reproducible example

Try building a project that includes ffmpeg-kit-react-native/min-gpl

**Comment by brentvatne** [comment]
unrelated to EAS Build, this seems specific to the library that you're using
