### ISSUE TITLE
create-expo-module generated project isn't working

### ISSUE THREAD

**Issue by alanjhughes** [expo/expo#19137]
### Summary

Creating a module using create-expo-module and running the example app, without any modifications, fails to render anything. Removing the text component that displays the output of the native module call and replacing it with anything else will fix the rendering issue. 

A more complicated module implementation fails to run at all. The following output is logged in the Xcode console.
```
Invariant Violation: Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```
I've tried multiple ways to get it to work

- Rerun prebuild
- clean the example project with react-native-clean-project
- pod update
- clean the pods cache

Not sure if it's relevant but the behavior is the same on both intel and m1 macs.

### What platform(s) does this occur on?

Android, iOS

### SDK Version

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.09.12.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/alanjhughes/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 22, 23, 28, 29, 30, 31, 32, 33
        Build Tools: 23.0.1, 23.0.3, 24.0.2, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.0
        System Images: android-17 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: Dolphin 2021.3.1 Dolphin 2021.3.1
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

Just run ```npx create-expo-module``` and run the example to replicate the behavior

**Comment by brentvatne** [comment]
this is resolved in sdk 47 :)
