### ISSUE TITLE
expo-location getCurrentPositionAsync is  not working in Android 

### ISSUE THREAD

**Issue by Asad8746** [expo/expo#19145]
### Summary

I am trying get user current (latitude and longitude) using expo-location but getCurrentPositionAsync is  unable to resolve and keeps on pending even if accuracy is Lowest or Low but still getting the same problem in android

### What platform(s) does this occur on?

Android

### Environment

System:
      OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      @expo/metro-config: ^0.3.19 => 0.3.19 
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 1.1.1
      expo-cli: 5.4.11
    Expo Workflow: managed

### Minimal reproducible example

i am unable to solve this issue

**Comment by EquesMedia** [comment]
I got the same issue on my Pixel 5, running on Android 13.

**Comment by e9-skanthi** [comment]
Is there a fix for this? I am getting the same issue on my Redmi Note 11, running on Android 11. I am running with SDK 47.
