### ISSUE TITLE
RN 0.70 runtime error on iOS with expo-av

### ISSUE THREAD

**Issue by radko93** [expo/expo#19140]
### Summary

Adding expo-av to an empty RN 0.70 RN project after runnning `npx install-expo-modules@latest` produces a runtime error. This project has Hermes disabled on iOS.

![image](https://user-images.githubusercontent.com/7029942/190622628-8f1d1844-35d2-48e4-b1ca-d4544cb94c3b.png)
![image](https://user-images.githubusercontent.com/7029942/190622638-0a72952d-7a1d-43ea-a239-8d53704c783f.png)

### What platform(s) does this occur on?

iOS

### Environment

 "expo": "^46.0.10",
    "expo-application": "4.2.2",
    "expo-av": "12.0.4",
    "expo-constants": "13.2.4",
    "expo-device": "4.3.0",
    "expo-file-system": "14.1.0",
    "expo-haptics": "^11.3.0",
    "expo-image-picker": "13.3.1",
    "expo-keep-awake": "10.2.1",
    "expo-notifications": "0.16.1",
    "expo-web-browser": "11.0.0",

### Minimal reproducible example

[Using Expo with React Native 0.70.](https://github.com/radko93/Testar)

**Comment by Kudo** [comment]
hi @radko93, since react-native 0.70 jsi introduced some new interfaces and breaks our prebuilt binary in expo-av. please reference https://expo.fyi/prebuilt-modules to build expo-av from source. this should help with the crash issue.

**Comment by Kailash23** [comment]
Hi @Kudo 
This page is not opening anymore 
https://github.com/expo/fyi/prebuilt-modules

**Comment by Kailash23** [comment]
Found this link 

https://github.com/expo/fyi/blob/main/prebuilt-modules.md

**Comment by zhiqingchen** [comment]
Will this be fixed in the next version if i don't want build modules from sources?

**Comment by Kudo** [comment]
@zhiqingchen in expo sdk 47, we should support react-native 0.70 officially.
