### ISSUE TITLE
[expo-haptics] should gracefully handle non-supported platforms 

### ISSUE THREAD

**Issue by philiplindberg** [expo/expo#19141]
### Summary

I'm using the `expo-haptics` package in my web/mobile app and it works great on iOS and Android. On web, haptics aren't supported of course (as stated in the [docs](https://docs.expo.dev/versions/latest/sdk/haptics/)), but I'm still getting the following error when trying to run any of the `Haptics.*` methods on web: 

```
The method or property Haptic.impactAsync is not available on web, are you sure you've linked all the native dependencies properly?
```

While I could conditionally run the `Haptics.*` methods based on the platform, I feel like this is something that should be handled by the `expo-haptics` package internally.

### What platform(s) does this occur on?

Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2
      babel-preset-expo: ^9.2.0 => 9.2.0
      expo: ~46.0.9 => 46.0.9
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.7
    npmGlobalPackages:
      eas-cli: 1.2.0
    Expo Workflow: bare

### Minimal reproducible example

https://snack.expo.dev/@philiplindberg/expo-haptics-demo

**Comment by serfgy** [comment]
would agree, currently the only solution for me is 

`Platform.OS !== 'web' && Haptics....`

**Comment by keith-kurak** [comment]
Hi, @philiplindberg! As mentioned in the comments, you can conditionally call `Haptics` functions by checking `Platform.OS`. This docs state that expo-haptics is not supported on web; this error exists because there are scenarios on mobile where Haptics may not work due to misconfiguration, and this would be easy to miss during testing. To handle disabling Haptics on web more gracefully, you may choose to wrap expo-haptics usages with code that checks if you're on web first.
