### ISSUE TITLE
tells me to run npx expo start - when I did

### ISSUE THREAD

**Issue by danocolombo** [expo/expo#19147]
### Summary

run "npx expo start" as instructed, and told it ls running global, and to use the command I just typed in. In the example below, the first link is my command line prompt and the following is what is returned.

pate-mobile/1.0.0a - (1.0.22) > npx expo start

This command is being executed with the global Expo CLI. Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
To use the local CLI instead (recommended in SDK 46 and higher), run:
› npx expo start

### What platform(s) does this occur on?

Android, iOS

### SDK Version

6.0.5

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
      react-navigation: 4.1.1 => 4.1.1 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

run "npx expo start" as instructed, and told it ls running global, and to use the command I just typed in. In the example below, the first link is my command line prompt and the following is what is returned.

pate-mobile/1.0.0a - (1.0.22) > npx expo start

This command is being executed with the global Expo CLI. Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
To use the local CLI instead (recommended in SDK 46 and higher), run:
› npx expo start

**Comment by danocolombo** [comment]
Is there a specific setting that the expo start is looking for? If I create a new expo project, the npx expo start command does not give me the error, so I guess there must be something in configuration...?

**Comment by Simek** [comment]
Hello, if the warning cannot be seen after setting up in the clean project we will need a minimal repro to be able to investigate this further. Feel free to create a new issue, when you will be able to provide it.

**Comment by stevenbrown-85** [comment]
i have the same issue with version 6.0.6 after upgrading from 5.0.4

**Comment by proton1k** [comment]
I think it is relevant to my case: https://github.com/expo/expo/issues/20865

**Comment by pnadj** [comment]
I also have this issue in a new project 

`npx create-expo-app@latest --example with-router`

**Comment by siniradam** [comment]
I got the same issue, been trying to fix. 
Just did. npx expo-doctor gives you the clue.

`Expo CLI is now part of the expo package. Having expo-cli in your project dependencies may cause issues, such as “error: unknown option --fix” when running npx expo install --fix
Advice: Remove expo-cli from your project dependencies.`

You need to remove expo-cli from your local dependencies. 
`yarn remove` / `npm uninstall` `expo`

Then once you run npx expo start, error wont pop.

**Comment by tim92109** [comment]
You will still get the warning, like I did, unless you add the global flag like:
npm uninstall expo-cli -g
