### ISSUE TITLE
takePictureAsync() does not work when I run with NativeCLI / Build on android.

### ISSUE THREAD

**Issue by leopego** [expo/expo#19149]
###  **BARE EXPO WORKFLOW - SDK46**

When I try to use the function **takePictureAsync()** running my project in the **native CLI  ("yarn react-native run:android")** , the function does not return anything. 

But when I run my project with the "expo start" cli, the function works great, and return me the data.

### What platform(s) does this occur on?

Android

### **PACKAGE.JSON**

{
  "name": "app_almox",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "@types/styled-components-react-native": "^5.1.3",
    "expo": "~46.0.9",
    "expo-camera": "~12.3.0",
    "expo-cli": "^6.0.5",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.5",
    "react-native-otp-textinput": "^0.0.9",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "^4.3.3",
    "react-native-screens": "^3.17.0",
    "react-native-web": "~0.18.7",
    "recoil": "^0.7.5",
    "styled-components": "^5.3.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "17.0.21",
    "@types/react-native": "~0.69.1",
    "typescript": "^4.6.3"
  },
  "private": true,
  "resolutions": {
    "@types/react": "17.0.43"
  }
}

### Minimal reproducible example

 import React, { useState, useRef } from "react";
import { Camera, CameraType } from "expo-camera";

import HeaderBadge from "../../components/headerBadge";
import { BottomWrapper, Container } from "./styles";

import { Text, TouchableOpacity } from "react-native";

const FacialScreen = ({ navigation }) => {
  const [type, setType] = useState(CameraType.back);
  const [permission, requestPermission] = Camera.useCameraPermissions();
  const [pictureData, setPictureData] = useState(null);

  const camRef = useRef(null);

  const handleTakePicture = async () => {
    const data = await camRef.current.takePictureAsync();
    setPictureData(data);
    console.log(data);
  };

  return (
    <Container>
      <HeaderBadge rightText="" rightSubText="" />
      <BottomWrapper>
        <Camera
          type={1}
          style={{ width: 500, height: 500 }}
          ref={camRef}
        ></Camera>
        <TouchableOpacity
          style={{ width: "100%", height: 50, backgroundColor: "red" }}
          onPress={() => handleTakePicture()}
        />
        {pictureData && <Text>Data OK!</Text>}
      </BottomWrapper>
    </Container>
  );
};

export default FacialScreen;

**Comment by keith-kurak** [comment]
Hi @leopego- since this can only be reproduced inside of a bare project, we would need a full reproduction uploaded to Github that we can then clone and try locally. Feel free to open a new issue if you can reproduce in that way. There are so many things that can change in the native projects that it would be difficult for us to replicate your setup without that. Additionally, if you're able to reproduce on a standalone build via EAS Build, that would be helpful information, as that should be identical to starting from a blank project and then prebuilding without any other native code changes.
