### ISSUE TITLE
Side loaded SQLite file is not showing tables in Android, works fine in iOS

### ISSUE THREAD

**Issue by sakettawde** [expo/expo#1914]
Bug: SQLite file which is side loaded is not showing tables in android device, though it works fine in iOS.
Reproduced in Snack as well. Please see below for link.

### Environment

Environment:
  OS: Windows 10
  Node: 9.6.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

Diagnostics report:
https://exp-xde-diagnostics.s3.amazonaws.com/sakettawde-71956826-3a0e-4593-9047-b3144b2d79f9.tar.gz

Running following expo client app versions on iOS (2.6.3.1015270) and Android (2.6.2)

### Steps to Reproduce

Code is pretty straight forward, sqlite file which is to be side loaded is in the ./assets/db/ folder.

Check snack here: https://snack.expo.io/@saketinevitable/sqldbtest

Run on a real device, for some reason the in-browser simulators are not able to give the same output.

### Expected Behavior

All SQL queries should function properly on both Android and iOS.

### Actual Behavior

They work only on iOS and on Android they give a 'table not found' error.

No error is shown in Android either. It is not like the db cannot be found or is not loaded.

As can be seen in the snack, I am running `SELECT name FROM sqlite_master WHERE type='table'` to list all the tables. In iOS I can see 2 tables, whereas in android I cannot.
There is a commented sql query as well if one wishes to test that which is also working fine, though only in iOS.

Also, do note: the in-browser simulators do not get this far either. Cannot zero in on why this code does not work there.

### Reproducible Demo

Snack here: https://snack.expo.io/@saketinevitable/sqldbtest

**Comment by esamelson** [comment]
Hi @sakettawde - this code is likely causing your issue:

```
FileSystem.downloadAsync(
  Asset.fromModule(require("./assets/db/test.sqlite")).uri,
  `${FileSystem.documentDirectory}SQLite/test.sqlite`
)
const db = SQLite.openDatabase("test.sqlite")
```

`FileSystem.downloadAsync` is an async method that just returns a promise, so it probably doesn't get a chance to complete before you call `SQLite.openDatabase`. You need to `await` the download, which means you need to wrap all of that logic in an `async` function.

Additionally, you are missing a slash: `${FileSystem.documentDirectory}/SQLite` :)

Let us know if that helps.

**Comment by sakettawde** [comment]
Hi @esamelson 
Many thanks for your time.
Neither solution helped. I needed to get this working so for the time being have ejected from Expo and used react-native-sqlite-storage.

You may be right about where the problem is, but I am unable to pinpoint the issue as the code in the snack is working perfectly on iOS. :/

Tried different android devices as well, the error is the same. Will update when I have more.

**Comment by sjchmiela** [comment]
Hi @sakettawde! I've fixed the database downloading code for you and checked whether it works on an Android device (it works 🎊). Check out this snack—https://snack.expo.io/SyeEiOvzX. 🙂

**Comment by sakettawde** [comment]
Thank you so much. Noted the changes. Perfect :)
