### ISSUE TITLE
(Android) Notifications.addListener always sends the latest notification recieved

### ISSUE THREAD

**Issue by Triggybet** [expo/expo#1915]
**Pre-requisit:**
Any android device or emulator
EXPO SDK 28.0.1

**Reproduction:**
1. Set up expo notifications as per https://docs.expo.io/versions/latest/guides/push-notifications
2. Use the push notification tool (https://expo.io/dashboard/notifications)
3. Send three notifications
4. Click on the first or second notification you sent

**Result:**
Notifications.addListener fires with the latest notification id (marked as "origin: selected")

**Expected result**
Notifications.addListener should fire with the one clicked

_Comment:
Works as expected on iOS_

**Comment by esamelson** [comment]
Hi @Triggybet - thanks for the report. We'll look into this as soon as we can.

**Comment by aatreya** [comment]
This is probably why:
https://github.com/expo/expo/commit/a7310a49a22ec50dfda2716c2766c2c9d6099a86#r29508001

**Comment by albertocolella** [comment]
Hi, any news on this issue? With multiple notifications Expo always open the last one

**Comment by Triggybet** [comment]
@esamelson Great to hear! Any idea as of when this bugfix will be released?

**Comment by esamelson** [comment]
Hi, we've just released this fix -- please give it a try with a fresh build!

**Comment by Triggybet** [comment]
Works great! Thanks
