### ISSUE TITLE
expo-constants does not work as described in documentation in production builds.  

### ISSUE THREAD

**Issue by aidantorrence** [expo/expo#19157]
### Summary

https://github.com/expo/expo/issues/8090#issuecomment-688794880

The documentation shows all of the params in app.config.js as being top-level, but the extra parameter must be a subparameter under the "expo" param in order to build properly in EAS build.

The extra parameter works perfectly on ios simulator, expo go, expo start --no-dev --minify, dev builds, etc. but fails in a real production build.

https://docs.expo.dev/workflow/configuration/#dynamic-configuration-with-appconfigjs

### What platform(s) does this occur on?

iOS

### Environment

production

### Minimal reproducible example

import "dotenv/config";

export default {
    name: "instaheat",
    slug: "instaheat",
    version: "1.0.15",
    orientation: "portrait",
    icon: "./assets/instaheat_icon.png",
    userInterfaceStyle: "light",
    splash: {
      image: "./assets/instaheat_splash.png",
      resizeMode: "contain",
      backgroundColor: "#ffffff",
    },
    updates: {
      fallbackToCacheTimeout: 0,
    },
    assetBundlePatterns: ["**/*"],
    android: {
      adaptiveIcon: {
        foregroundImage: "./assets/adaptive-icon.png",
        backgroundColor: "#FFFFFF",
      },
    },
    web: {
      favicon: "./assets/favicon.png",
    },
    ios: {
      bundleIdentifier: "com.instaheat.app",
      buildNumber: "1.0.15",
      supportsTablet: true,
      infoPlist: {
        NSCameraUsageDescription: "Camera access is used to allow users to upload pictures to the app",
      },
    },
    plugins: [
      ["sentry-expo"],
      // [
      //   "expo-image-picker",
      //   {
      //     photosPermission: "Access photos to update your profile picture",
      //     cameraPermission: "The app accesses your camera to let you add new places",
      //   },
      // ],
    ],
    hooks: {
      postPublish: [
        {
          file: "sentry-expo/upload-sourcemaps",
          config: {
            organization: "instaheat",
            project: "react-native",
            authToken,
          },
        },
      ],
    },
    extra: {
      apiKey,
      authDomain,
      projectId,
      storageBucket,
      messagingSenderId,
      appId,
      publishableKey,
      eas: {
        projectId,
      },
    },
};

**Comment by hirbod** [comment]
You will have to quickly revoke all of your tokens, since you've posted them publicly now..

**Comment by brentvatne** [comment]
hi there! i don't understand the issue. if you can create a new issue with a minimal reproducible example that clearly demonstrates what you are encountering, we can investigate it for you!
