### ISSUE TITLE
The new CLI Offline flag bug

### ISSUE THREAD

**Issue by Stevemoretz** [expo/expo#19163]
### Summary

It has become a lot better faster and cooler yet the offline support is somehow gone!

You get this error when you start your app without internet, even in offline (localhost) mode!!

You also get this error when you were online but are offline now and right after you triggered a reload.

```bash
npx expo start --host localhost
```

or according to https://docs.expo.dev/workflow/expo-cli/#offline :

```bash
npx expo start --offline
```

Both result to:

```
FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: getaddrinfo ENOTFOUND api.expo.dev
```

In the first case, If you get offline later on but don't trigger a reload after a while (without doing anything) you'd get:

```
Non-fatal error updating development session API: FetchError: request to https://api.expo.dev/v2/development-sessions/notify-alive?deviceId=BB0539DE-9044-49F2-948D-E2115FB5A9E7&deviceId=A8FB99A2-6DF9-4B9A-BC94-A09FD02EF6E9 failed, reason: getaddrinfo ENOTFOUND api.expo.dev
``` 

And this messages will repeat itself forever, sounds like you're doing a polling? That's not very performant is it? Anyways that doesn't matter what matters is that none of these should happen when `--host localhost` or `--offline` is enabled.

### What platform(s) does this occur on?

iOS

### SDK Version

46

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.15.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.02.14.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29, 30, 32
        Build Tools: 28.0.3, 29.0.2, 29.0.3
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.10 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 1.1.1
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Minimal reproducible example

1. Create a new project
2. Turn off your wifi, or disable your LAN 
3. Run

```bash
npx expo start --offline
```

4. You will get:

```
FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: getaddrinfo ENOTFOUND api.expo.dev
```

**Comment by keith-kurak** [comment]
Thanks for reporting! I just noticed we have another issue for this already opened (https://github.com/expo/expo/issues/18918), so we'll continue tracking over there.
