### ISSUE TITLE
Expo barcode scanner not working on id with pdf417

### ISSUE THREAD

**Issue by apadillalink** [expo/expo#19161]
### Summary

A few months back I implemented expo camera to scan a pdf417 barcode (corresponding to a Colombian Id). **At first it worked perfectly for like 4 months**  on different id's .But now it does not work at all for Android devices (didn't change sdk nor expo camera/barcode-scanner versions). Expo console didn't show anything so I decided to se the logs from my phone usgin android studio while the app was running and noticed that when I aim the phone to the barcode I get the following error log
![Captura](https://user-images.githubusercontent.com/94752661/190932001-e02986db-5cc6-4e69-8d79-bad96c5f7187.PNG)

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Minimal reproducible example

You can use the snack procide in the expo-barcode-scanner documentation since it has the same behaviour (I also tried updating to the lates scanner version and had the same result)

https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

Youcan use this code for testing

![image](https://user-images.githubusercontent.com/94752661/190932065-2ecb1f48-b362-4fdd-901a-5b3f9263b6db.png)

**Comment by keith-kurak** [comment]
Hi, @apadillalink!

Did you reproduce the issue only in your standalone app (where you can see that native error), or did you confirm that the barcode fails to scan for you when running the Snack, as well? I tried the Snack with both a Pixel and Galaxy phone, and I was able to scan a PDF417. The image above is kind of fuzzy so I tested against [the example PDF417 here](https://en.wikipedia.org/wiki/PDF417).

**Comment by apadillalink** [comment]
Hello @keith-kurak

Yes I managed to replicate the issue when running the Snack. I forgot to mention that the issue **only** happens when trying to scan a pdf417 that corresponds to a Colombian Id. When scanning any other pdf417s, the scanner works as intended, that's why I provided that specific image for testing when I created the issue.

Please let me know if you need more info. Thank you for your reply

**Comment by apadillalink** [comment]
@keith-kurak Any updates on the matter?. Sorry for the annoyance

**Comment by keith-kurak** [comment]
Hi @apadillalink - apologies, I haven't been able to scan this barcode either, well, except that it sometimes mistakes it for a code 32, which has me wondering if that example is too blurry (so it only detects the edges). I have been able to scan other high-density PDF417's where there is sharp contrast between light and dark and no blur. Do you have any examples that are a directly-generated digital image and not a scan?

Is a physical ID glossy? The scan looks like it is. It makes me wonder if they're trying to prevent normal phone readers from scanning this information. If you can find another open source library that can scan this barcode, it may be something we can look at adapting. But, scanning this barcode may be something that exceeds the recognition capabilities available base libraries/ OS components we use under the hood for scanning.

**Comment by apadillalink** [comment]
Hello @keith-kurak, to answer to your questions. 

1. No, I couldn't find any examples that are a directly generated digital images (the one on the issue was the best I could find since it was provided on the official goverment website).
2. Yes, the physical ID is indeed glossy.

I'll look into what you said about finding another open source library that can scan the barcode.

What keeps bothering me is the fact that I could scan ID's for a few months before it stoped working. Do you have any ideas on  why that was the case?

Thanks for the reply

**Comment by keith-kurak** [comment]
@apadillalink Sorry, nothing I can think of on our end that would cause these to stop scanning a few months ago.

**Comment by OGreeni** [comment]
I've had a similar issue trying to scan a New Jersey driver's license and can confirm it is the material/size of the barcode on the ID. I could scan the barcode from a zoomed-in picture of the ID but not from the ID card itself.
