### ISSUE TITLE
Error: The method or property expo-random.getRandomBytes is not available on android, are you sure you've linked all the native dependencies properly?

### ISSUE THREAD

**Issue by maxenceg** [expo/expo#19167]
### Summary

*Expected behavior*
I expect the button to sign-in using Google SSO to appear on Android (seems to work fine on iOS)

*Actual behavior*
The app throws an error saying:
`Error: The method or property expo-random.getRandomBytes is not available on android, are you sure you've linked all the native dependencies properly?`

![image](https://user-images.githubusercontent.com/38657323/191007366-7e1a1ec8-a333-4826-9280-9fe4736a787f.png)

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0
      expo: ^46.0.0 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: managed

### Minimal reproducible example

We've reproduced the error on [this repo](https://github.com/the-totem/demo-expo-auth-session)

After building the app (`yarn build:android:device`), you can download [the build](https://expo.dev/accounts/melbius_/projects/demo/builds/18de6e0b-4793-4512-aa2e-136b7442c2c0), and as soon as you launch the app in the dev client, it crashes with the error

**Comment by husam287** [comment]
+1
also with facebook login only when reload the app with expo updates

**Comment by benjamin-vaysse** [comment]
Thanks for taking the time to produce the reproducible example @maxenceg 🔥

@brentvatne any chance the Expo team could have a look any time soon ? 😃

**Comment by JavaScriptJohn** [comment]
I think I just installed expo-random as my own dependency and it fixed the
issue.

**Comment by Kudo** [comment]
hi there! i cannot reproduce the problem even on the [repo](https://github.com/the-totem/demo-expo-auth-session) @maxenceg provided. i try to investigate whether there's any strange code in the repo. one thing in my eyes is the repo contains both yarn.lock and package-lock.json. did you install the packages through yarn or npm?

besides, there is a problem in package-lock.json where it has multiple expo-modules-autolinking.
could you please try to execute these commands and show the output? thanks
```
$ npm ls expo-modules-autolinking
$ yarn why expo-modules-autolinking
```

**Comment by maxenceg** [comment]
I removed the package-lock and installed again
When I launched the app, it works but as soon as I reload, I get this error again:
```
 ERROR  Error: The method or property expo-random.getRandomBytes is not available on android, are you sure you've linked all the native dependencies properly?

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

```
$ npm ls expo-modules-autolinking
demo@1.0.0 /Users/maxence/Documents/Totem/demo-expo-auth-session
└─┬ expo@46.0.15
  ├─┬ @expo/cli@0.3.1
  │ └─┬ @expo/prebuild-config@5.0.3
  │   └── expo-modules-autolinking@0.10.3 deduped
  └── expo-modules-autolinking@0.10.3
```

```
$ yarn why expo-modules-autolinking
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "expo-modules-autolinking"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "expo-modules-autolinking@0.10.3"
info Reasons this module exists
   - "expo" depends on it
   - Hoisted from "expo#expo-modules-autolinking"
info Disk size without dependencies: "896KB"
info Disk size with unique dependencies: "1.68MB"
info Disk size with transitive dependencies: "3MB"
info Number of shared dependencies: 27
✨  Done in 0.50s.
```

**Comment by maxenceg** [comment]
This is what happens on the mobile, when I run `yarn start`, then open the app on the Android device, and then trying to reload in the expo-dev-client:

https://user-images.githubusercontent.com/38657323/194285702-872c00c0-ceda-4e84-96aa-0809c7544661.mp4



This is what happens in the console, during this exact same manipulation:
https://user-images.githubusercontent.com/38657323/194285419-b3da924f-3bf3-4fb7-b880-2f3f720cebd5.mov

**Comment by Kudo** [comment]
thanks for the great information and video. i still cannot repro the expo-random issue. there's a crash probably related to #19221. here are my steps, do you see any difference from your repro?

```sh
$ git clone https://github.com/the-totem/demo-expo-auth-session.git
$ cd demo-expo-auth-session
$ yarn
$ npx expo run:android
```
then it shows the error:
```
CommandError: Couldn't open Android app with activity "com.melbius_.demo://expo-development-client/?url=http%3A%2F%2F192.168.1.100%3A8081" on device "ASUS".
The app might not be installed, try installing it with: npx expo run:android -d ASUS
```
probably because the application id caused an invalid scheme; fortunately, the app is successfully installed.
then i tried `yarn start` and launched the app on the phone.

- load `http://192.168.1.100:8081` which is my dev server address
- press LOGIN button and see "400 invalid_request" from the web browser.
- close the browser
- open dev-menu by `adb shell input keyevent 82`
- click reload
- app crash without expo-random errror

**Comment by maxenceg** [comment]
I'm going to try your reproduction steps, for comparison :)

How do you know that the crash you get is "probably related to https://github.com/expo/expo/issues/19221", though? Why couldn't it be the crash I'm describing in this issue?

Do you still get the crash after reload if you replace the content of App.js by:

```
import * as React from "react";
import * as WebBrowser from "expo-web-browser";
import { Text, View } from "react-native";

WebBrowser.maybeCompleteAuthSession();

export default function App() {
  return (
    <View style={{ padding: 100 }}>
      <Text>Hello</Text>
    </View>
  );
}
```
?

Thanks a lot for your help!

**Comment by maxenceg** [comment]
After trying your steps, I had:
```
CommandError: Couldn't open Android app with activity "com.melbius_.demo://expo-development-client/?url=http%3A%2F%2F192.168.1.85%3A8081" on device "Pixel_4_API_33".
The app might not be installed, try installing it with: npx expo run:android -d Pixel_4_API_33
```

And indeed, the app was installed on the simulator. Then, I had the exact same behaviour as you, which led to a crash with no log.

However, this looks exactly like the error I got on video (without the log)

The only difference between what you did and what I did, was that you ran the project on a simulator while I downloaded it on an actual device, which led to the same behaviour (= crash after reload) but with a log.

**Comment by maxenceg** [comment]
And I can now confirm that the crash you've been seeing is the expo-random one, because when I remove the `expo-auth-session`-related code as suggested [here in my comment](https://github.com/expo/expo/issues/19167#issuecomment-1275825141), I don't get any error


https://user-images.githubusercontent.com/38657323/195303701-f992327e-2cb5-4788-bd1c-34fa2c2503e6.mov

**Comment by Kudo** [comment]
i also tried on devices and still works for me 🤔

as the crash issue and the CommandError make us some difficulty for the repro, i've tried to fork your example and have some fix: https://github.com/the-totem/demo-expo-auth-session/compare/master...Kudo:demo-expo-auth-session:master
 - update expo package to fix the JSCRuntime crash
 - revise the package name, so that `npx expo run:android` can get the correct scheme to launch.

now my repro steps are:

1. `git clone https://github.com/Kudo/demo-expo-auth-session.git`
2. `cd demo-expo-auth-session`
3. `npx expo run:android -d` and select device
4. after app launching, click "LOGIN" button and see "400 invalid_request" from the web browser
5. close the browser
6. open dev-menu by `adb shell input keyevent 82`
7. click reload
8. no errors there

**Comment by maxenceg** [comment]
@Kudo Indeed, with your reproduction steps I don't get an immediate crash after the first reload (the only difference is I get a 401 instead of a 400 but I guess that's not relevant)

However, after 2 or 3 reloads, the app ends crashing 😛

**Comment by Kudo** [comment]
that is unfortunate. well, let's focus on the expo-auth-session / expo-random first, having [this commit](https://github.com/Kudo/demo-expo-auth-session/commit/809637616a9d808f05038080f141b7dc90320b2a) to use hermes and prevent debug build crash from jsc. could you try to repro the expo-random based on the latest changes?

**Comment by maxenceg** [comment]
Yes, I kept your changes + installed hermes this morning and still get the crash after multiple reloads (which I still don't get when I remove the button and the `expo-auth-session`-related code)

**Comment by Kudo** [comment]
sorry be late to investigate this complicated issue. before we cherry-pick the #19699 fix to sdk 46, it would be great if you could help to verify the patch. [this commit](https://github.com/Kudo/demo-expo-auth-session/commit/b57b46a0b48e2547151653b24a9a9d48f0e3f7cf) uses patch-package to apply the fix. reloading should not crash after this patch.

**Comment by maxenceg** [comment]
Hi @Kudo!

I just tried to apply your patch and can confirm that it works 🚀🚀🚀

Thanks a lot for all the time and effort you've put into this issue, it means a lot to us!

**Comment by Kudo** [comment]
thanks @maxenceg for the great help. i am not sure whether the crash issue related to the original `Error: The method or property expo-random.getRandomBytes is not available on android, are you sure you've linked all the native dependencies properly?` error. could you help to check whether there's a way to repro the error?

**Comment by maxenceg** [comment]
Hi @Kudo !

To be sure, how exactly can we get your fix? Is it in a minor version update of Expo or will it only be available in Expo SDK 47 ?

Cheers!

**Comment by Kudo** [comment]
@maxenceg we would like to publish patch release with the other fix together, and it should be available within this week.

**Comment by Kudo** [comment]
sorr for late publishing the fix, please install `expo@46.0.17` to get the updates. if still encountered problems, please let us know. thanks!

**Comment by next6leo** [comment]
bump yea can i know is this solve cause i still having issues

**Comment by stabacco** [comment]
the problem for me went away with `48.0.10` (it was still a problem with 47)

**Comment by RohovDmytro** [comment]
Feels related:
````
The method or property expo-crypto.getRandomBytes is not available on android, are you sure you've linked all the native dependencies properly
````

with
````
...
 "expo": "48.0.17",
    "expo-application": "5.1.1",
    "expo-asset": "8.9.1",
    "expo-auth-session": "4.0.3",
    "expo-av": "13.2.1",
    "expo-build-properties": "0.6.0",
    "expo-constants": "14.2.1",
    "expo-crypto": "12.2.2",
    "expo-dev-client": "2.2.1",
    "expo-device": "5.2.1",
    "expo-image": "1.2.3",
    "expo-image-manipulator": "11.1.1",
    "expo-image-picker": "14.1.1",
    "expo-in-app-purchases": "14.1.1",
    "expo-linear-gradient": "12.1.2",
    "expo-linking": "4.0.1",
    "expo-localization": "14.1.1",
    "expo-navigation-bar": "2.1.1",
    "expo-notifications": "0.18.1",
    "expo-router": "^1.5.3",
    "expo-sharing": "11.2.2",
    "expo-splash-screen": "0.18.2",
    "expo-status-bar": "1.4.4",
    "expo-system-ui": "2.2.1",
...
````

**Comment by RohovDmytro** [comment]
My issue was resolved after downgrading "react-native-get-random-values" to "1.8.0".

**Comment by efstathiosntonas** [comment]
Thanks @RohovDmytro, downgrading ` "react-native-get-random-values": "1.8.0"` did the trick.

**Comment by zlanich** [comment]
For anyone still struggling with this issue (or one related), this is the only solution I could find that worked for me: https://github.com/expo/expo/issues/17270#issuecomment-1112697621

**Comment by efstathiosntonas** [comment]
It’s fixed on `expo-crypto@12.2.2`

**Comment by zlanich** [comment]
@efstathiosntonas Thank you for letting me know. I am still on `12.2.1`. I will be sure to try out `12.2.2` on the next build.

**Comment by efstathiosntonas** [comment]
@zlanich it’s not mentioned in the changelog so there’s a slight chance this is fixed on another module (i’m not quite familiar with expo internals so this might not stand), in my case I use bare react native with expo 48 unimodules.

**Comment by efstathiosntonas** [comment]
@zlanich try `expo-crypto@12.40` not `12.2.2`

**Comment by JoaoLobo94** [comment]
I tried, and could not get it to work with 12.4.0..

The problems seem to come from these libraries (i think)

```import {schnorr} from '@noble/curves/secp256k1'
import {sha256} from '@noble/hashes/sha256'
import {bytesToHex} from '@noble/hashes/utils'```

**Comment by soulfresh** [comment]
I experienced the same issue. Downgrading `"react-native-get-random-values": "~1.8.0"` did the trick for me as well.
