### ISSUE TITLE
VideoThumbnails: expo-video-thumbnails does not generate images on android 12 - SDK46

### ISSUE THREAD

**Issue by SemPrygorodov** [expo/expo#19165]
### Summary

Hello, I use for development iOS devices on which expo-video-thumbnails works fine and android samsung and xiaomi devices on which android 12 is installed.

The problem is that when using standard videos from the media library, which were shot with a camera with the H.264 codec (compatibility mode), "await VideoThumbnails.getThumbnailAsync" waits indefinitely to generate a picture. And this happens on all available android devices. The official example with a link to the video
 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' 
also works every other time.
More often it does not work, endlessly waits.

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^46.0.0 => 46.0.3 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: managed
```

### Minimal reproducible example

```
import React, { useState } from 'react';
import { StyleSheet, Button, View, Image, Text } from 'react-native';
import * as VideoThumbnails from 'expo-video-thumbnails';
import * as ImagePicker from "expo-image-picker";

export default function App() {
  const [image, setImage] = useState(null);

   const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Videos,
      allowsEditing: false,
      quality: 0.5,
      videoQuality: ImagePicker.UIImagePickerControllerQualityType.Medium,
      videoExportPreset: ImagePicker.VideoExportPreset.H264_960x540,
    });

    if (!result.cancelled) {
      await generateThumbnail(result.uri);
    }
  };

  const generateThumbnail = async (incomingContentUrl) => {
    try {
      const { uri } = await VideoThumbnails.getThumbnailAsync( 

        // Problem is here
        // Change it to  'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4', (not working or sooometimes)
        // or this 'http://www.goldart.ee/0101010.mp4' (file from phone camera - works good but the same file from 
        // local storage is not working)

        incomingContentUrl, 
        {
          time: 0,
        }
      );
      setImage(uri);
    } catch (e) {
      console.warn(e);
    }
  };

  return (
    <View style={styles.container}>
      <Button onPress={pickImage} title="Generate thumbnail" />
      {image && <Image source={{ uri: image }} style={styles.image} />}
      <Text>{image}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  image: {
    width: 200,
    height: 200,
  },
});


```

**Comment by ReamRD** [comment]
Same issue here, feature stopped working after upgrading to Expo v46. Please halp! 🐱

**Comment by ReamRD** [comment]
Btw, official Snack demonstrates the issue pretty well on Android 12 - https://snack.expo.dev/@styledoubler/ea6ce0?platform=android

**Comment by SemPrygorodov** [comment]
It only works if I upload a video file taken on the phone to my NAS server so that I can access it via a link like http://.... 
 Then the thumbnails are generated. 
 But it is not clear why local links do not work and why the original snack does not work or sometimes works.

**Comment by SemPrygorodov** [comment]
I found solution. And after investigation - expo-video-thumbnails generation is working great, but not working if I'm sending  **"_result.uri_"** from **_"ImagePicker"_** : 

I Fixed it like this (BUT it's working only for ANDROID, for iOS original code is working well) : 

```
const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Videos,
      allowsEditing: false,
      quality: 0.5,
      videoQuality: ImagePicker.UIImagePickerControllerQualityType.Medium,
      videoExportPreset: ImagePicker.VideoExportPreset.H264_960x540,
    });
 
 if (Platform.OS !== "ios") {
    if (!result.cancelled) {
      await generateThumbnail(result.uri);
    }
};

 if (Platform.OS !== "android") {
   let { status } = await MediaLibrary.requestPermissionsAsync();

      if (status !== "granted") return;

      const options = {
        sortBy: [MediaLibrary.SortBy.creationTime],
        mediaType: [MediaLibrary.MediaType.video],
      };

      let { assets } = await MediaLibrary.getAssetsAsync(options);

      if (!result.cancelled) {
        const pickedVideoId = result.assetId;
        const newVideoUri = assets.find((x) => x.id === pickedVideoId)?.uri!;

        await generateThumbnail(newVideoUri);
      }
};
  };
```

**Comment by edmondswrtech** [comment]
> 

thanks its working fine on me :)

**Comment by edmondswrtech** [comment]
> > @SemPrygorodov
> 
> thanks its working fine on me its been so long looking for an answer 💯

@SemPrygorodov 

> I found solution. And after investigation - expo-video-thumbnails generation is **working great**, but not working if I'm sending **"_result.uri_"** from **_"ImagePicker"_** :
> 
> I Fixed it like this (BUT it's working only for ANDROID, for iOS original code is working well) :
> 
> ```
> const pickImage = async () => {
>     let result = await ImagePicker.launchImageLibraryAsync({
>       mediaTypes: ImagePicker.MediaTypeOptions.Videos,
>       allowsEditing: false,
>       quality: 0.5,
>       videoQuality: ImagePicker.UIImagePickerControllerQualityType.Medium,
>       videoExportPreset: ImagePicker.VideoExportPreset.H264_960x540,
>     });
>  
>  if (Platform.OS === "ios") {
>     if (!result.cancelled) {
>       await generateThumbnail(result.uri);
>     }
> };
> 
>  if (Platform.OS === "android") {
>    let { status } = await MediaLibrary.requestPermissionsAsync();
> 
>       if (status !== "granted") return;
> 
>       const options = {
>         sortBy: [MediaLibrary.SortBy.creationTime],
>         mediaType: [MediaLibrary.MediaType.video],
>       };
> 
>       let { assets } = await MediaLibrary.getAssetsAsync(options);
> 
>       if (!result.cancelled) {
>         const pickedVideoId = result.assetId;
>         const newVideoUri = assets.find((x) => x.id === pickedVideoId)?.uri!;
> 
>         await generateThumbnail(newVideoUri);
>       }
> };
>   };
> ```
hello @SemPrygorodov 
did you try this with the multiple upload in android?, because i have an issue when doing mulitple upload in android but in ios its working fine i dont know whats the problem maybe you can help me with this issue thanks

**Comment by shrihari1999** [comment]
Why is this stale? Shouldn't the code work without the workaround?

Does upgrading to SDK 47 fix it?
