### ISSUE TITLE
"Metro bundler has encountered an internal error" when importing non-existent files

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#1917]
I get this error when I try to import a file that doesn't exist on the filesystem.

I have to debug by adding a console.log(error) to formatBundlingError in node_modules/metro/src/lib/formatBundlingError.js.

The error goes away when I fix the import statement.

I'm surprised I couldn't find an issue for this? Apologies for the terse bug report.

**Comment by esamelson** [comment]
Hi @vjsingh - glad you figured it out. This is an upstream issue, so you could try opening a PR or issue here to improve the error message: https://github.com/facebook/metro . I'm going to close this here as it's not an expo-specific issue.

**Comment by vjsingh** [comment]
Got it, thanks!

**Comment by audiolion** [comment]
Hey @esamelson I encountered the same issue today, I am getting no error message from expo. 

![image](https://user-images.githubusercontent.com/2430381/42529827-794261a4-844d-11e8-9f9a-d1042d595b13.png)

I will cross post the issue over there but I just want to make sure first, are you sure this isn't Expo swallowing the error message somewhere along the way?

**Comment by esamelson** [comment]
Hi @audiolion - thanks for the further info, I think you might be right. We'll take a look. Reopening this.

**Comment by audiolion** [comment]
@esamelson I actually think it might not be Expo now, not sure haha, I made a post over at https://github.com/facebook/metro/issues/195 too

**Comment by vjsingh** [comment]
I actually came here from Metro: https://github.com/facebook/metro/issues/110

**Comment by sjchmiela** [comment]
I've just confirmed that this issue is no longer present in the latest version of Expo SDK, error message clearly states `Unable to resolve module './non-existent' from …`. 🎉

**Comment by vjsingh** [comment]
Sweet, thanks! @sjchmiela
