### ISSUE TITLE
expo InAppPurchases getProductsAsync does not return subscription list.

### ISSUE THREAD

**Issue by mdrazu24** [expo/expo#19188]
### Summary

getProductsAsync api is only getting in-app purchase product from play console. But  when I'm trying to get subscription product list, it's returning empty array. 

![image](https://user-images.githubusercontent.com/41054947/191175010-02c184c2-d154-47e7-8788-00aedb3ed8e6.png)
this is the preview of my subscription plan.

### What platform(s) does this occur on?

Android

### Environment

"expo-in-app-purchases": "^13.1.0",
"react-native": "0.69.5",
"react": "18.0.0",
"expo": "~46.0.9",

### Minimal reproducible example

 const items = Platform.select({
    ios: []
    android: ["monthly_big_20", "monthly_small_5"],
  })
const result = await InAppPurchases.getProductsAsync(items)
console.log(result) //it returns empty array

**Comment by ggunia** [comment]
Any updates on this one?

**Comment by mdrazu24** [comment]
> Any updates on this one?

not yet. I haven't really checked it . Most probably it's not fixed.
