### ISSUE TITLE
App crashing after adding expo-av on RN 0.70.1

### ISSUE THREAD

**Issue by Kailash23** [expo/expo#19195]
### Summary

I created a fresh RN project 0.70.1. Added expo modules working fine. But after adding expo-av iOS app started crashing.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.10 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.1 => 0.70.1 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/Kailash23/ExpoAvBug

**Comment by Kudo** [comment]
hi there! this is duplicated as https://github.com/expo/expo/issues/19140#issuecomment-1252217420, please check the answer there and build expo-av from source for react-native 0.70. thanks!
