### ISSUE TITLE
[expo-av] Playing sound twice on iOS

### ISSUE THREAD

**Issue by jparksecurity** [expo/expo#19198]
### Summary

On iOS `Audio.sound`(expo-av) plays twice.

### What platform(s) does this occur on?

iOS

### Environment

I'm using snack

### Minimal reproducible example

https://snack.expo.dev/@trellyhoraeng/expo-av-audio-playing-twice-on-ios

Click `Play sound` button on iOS, Android, and Web to confirm the issue.

**Comment by jparksecurity** [comment]
The workaround I found is to unload the sound once it's done.

```js
  sound.current.setOnPlaybackStatusUpdate((status) => {
    if (status.didJustFinish) {
      sound.current.unloadAsync();
    }
  });
```

I hope I don't need to unload it.

**Comment by Weddin** [comment]
I got this issue too
