### ISSUE TITLE
What are the correct versions of react-native and react to property detach an expo project to iOS?

### ISSUE THREAD

**Issue by tgehrs** [expo/expo#192]
I am having a number of issues making sure the correct modules load into my new iOS project (started with CRNA) when I detach, for example:
```
...../node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h:12:9: 'RCTAnimation/RCTValueAnimatedNode.h' file not found
```
I was able to get some of them (such as Yoga errors) to go away by changing my react-native version to 0.44.0, but at this point am just guessing trying to figure out what it should be and cannot seem to find this info in the docs

**Comment by MataHu** [comment]
+1

**Comment by MataHu** [comment]
Podfile  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation'
    ]
pod install
and change RCTNativeAnimatedNodesManager.h  /   #import "RCTValueAnimatedNode.h"
it's not a good way, But can to solve the problem

**Comment by aaronbuchanan** [comment]
I'm getting the same error after adding cocopods to a project that previously didn't get it (`PROVIDER_GOOGLE` on `react-native-maps`)

**Comment by ide** [comment]
You should use the same version of React Native that you were using before (ex: `expo/react-native#sdk-17.0.0`).

Though you shouldn't need to, sometimes it might be that you'll need to make small native changes to get it to compile (the issue with RCTValueAnimatedNode.h sounds familiar, change the header to a quoted one).
