### ISSUE TITLE
PromptAsync returns dismiss result on Android standalone app [expo-auth-session/providers/google]

### ISSUE THREAD

**Issue by meianuraluca** [expo/expo#19202]
### Summary

Calling the promptAsync returns the dismiss result after I choose the account.
The browser opens correctly, the users will go to the login screen, login successfully, but the app would understand this session as being dismissed.

Everything is fine, instead, by running the app inside Expo environment or ios devices

The result is that, when an app is running on Android as a standalone app, every authentication attempt returns dismiss.

### What platform(s) does this occur on?

Android

### Environment

SDK Version: 45

expo-auth-session:~3.6.1

### Minimal reproducible example

![image](https://user-images.githubusercontent.com/39118478/191451186-f58dcd4f-dd11-47ae-a0b7-e0d18f17a373.png)

**Comment by jurica-penjgusic** [comment]
Related to https://github.com/expo/expo/issues/12044

**Comment by meianuraluca** [comment]
I tried everything mentioned there, but it didn't work for me

**Comment by jurica-penjgusic** [comment]
It's a known open issue with android standalone build

**Comment by gwnoox** [comment]
been days trying to figure out this same issue as well, looking at #12044 trying all possible solution, not really solve my problem. 

if the expo-auth-session (for google) is not producing a working code, why make the previous package `expo-google-app-auth` deprecated though. I hope someone from expo or community can put more attention to this issue

**Comment by jurica-penjgusic** [comment]
Basically what we use is expo-web-browser authsession with server combination. Idea is to have "server side login" which will deliver accessToken as query parameter to opened browser.

```
 handleSuccessfullLogin(url: string) {
    const redirectData = Linking.parse(url);
    if (!redirectData.queryParams?.accessToken) return;
    const decodedAccessToken = decodeURI(redirectData.queryParams.accessToken as any);
    console.log('Decoded token', decodedAccessToken)
    }

  async handleGoogleLoginAsync() {
    try {
      const redirectUrl = Linking.createURL("/");
      const uri = "https:yourserver/SocialAuthentication/ContinueWithGoogle";
      let result: any = await WebBrowser.openAuthSessionAsync(`${uri}?callerReturnUrl=${redirectUrl}`, redirectUrl, {showInRecents: true});
      console.log("result", result)
      if (result.url) return this.handleSuccessFullLogin(result.url);
    } catch (e) {
      console.log("Error while opening google login", e)
    }
  }
```

For us it's working, but if  user have only one account it will resolve immediately as successfull login without asking user which account to use, on Ios it is working fine
