### ISSUE TITLE
Splash screen with resizeMode "stretch" not behaving as expected

### ISSUE THREAD

**Issue by RocketRonz** [expo/expo#19210]
### Summary

When using the default splash image size (1284x2778) a border is displayed on the left and right edges. I would expect the width & height of the image to scale independently, filling all available space. The splash screen appears to be scaled in the same way as the "contain" resizeMode.

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526     
    npmPackages:
      expo: ~46.0.9 => 46.0.9
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    Expo Workflow: managed

### Minimal reproducible example

1284x2778 splash image with the following app.json attribute:

"resizeMode": "stretch"

**Comment by SohelIslamImran** [comment]
After upgrading to SDK47, eas and Hermes, my splash image does not cover the top.
