### ISSUE TITLE
RNGH: GestureStateManager not working on expo 

### ISSUE THREAD

**Issue by Onzeka** [expo/expo#19216]
### Summary
Hello ! 
GestureStateManager is supposed to control gesture states ( undetermined, begin, active ...) However when using expo it has no effect for example here :
```
  const gesture = Gesture.Manual().onTouchesDown((e, manager) => {
    for (const touch of e.changedTouches) {
      trackedPointers[touch.id].value = {
        visible: true,
        x: touch.x,
        y: touch.y,
      };
    }
    
    if (e.numberOfTouches >= 2) {
      manager.activate();
    }
  }).onTouchesMove((e, _manager) => {
    for (const touch of e.changedTouches) {
      trackedPointers[touch.id].value = {
        visible: true,
        x: touch.x,
        y: touch.y,
      };
    }
  }).onTouchesUp((e, manager) => {
    for (const touch of e.changedTouches) {
      trackedPointers[touch.id].value = {
        visible: false,
        x: touch.x,
        y: touch.y,
      };
    }

    if (e.numberOfTouches === 0) {
      manager.end();
    }
  })
  .onStart(() => {
    active.value = true;
  })
  .onEnd(() => {
    active.value = false;
  });

....

const animatedStyle = useAnimatedStyle(() => ({
      transform: [
        { translateX: props.pointer.value.x },
        { translateY: props.pointer.value.y },
        {
          scale:
            (props.pointer.value.visible ? 1 : 0) *
            (props.active.value ? 1.3 : 1),
        },
      ],
      backgroundColor: props.active.value ? 'red' : 'blue',
    }));

```
manager.activate() and manager.end() will have no effect :
![image](https://user-images.githubusercontent.com/48027322/191664606-e90b640a-bec7-4f66-991d-d71bcd598e0a.png)

### What platform(s) does this occur on?

Android, iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      npm: 8.12.2 - ~/.nvm/versions/node/v14.17.6/bin/npm
    SDKs:
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-31 | Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ^46.0.0 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@onzeka/eager-pudding?platform=android

**Comment by brentvatne** [comment]
it's not clear to me what the expected behavior is in the example that you provided. if you can try this in the latest version of expo go and create a new issue that explains in more detail what you are expecting and how it is different from what is expected, that would be helpful!
