### ISSUE TITLE
expo-updates checkForUpdateAsync freezes UI updates on Android 

### ISSUE THREAD

**Issue by arekm213** [expo/expo#19213]
### Summary

We are trying to implement OTA updates flow that tries to update app only if user didn't get any OTA update to current build before, usually user gets OTA update right after installing the app and after that we don't want to check for updates every time because users with slow internet connection are getting stuck on splash screen for too long. We also want to let user use not updated app if he didn't get the latest update in 10 seconds.
We are using flag that is set after a timeout to skip invoking next methods 'fetchUpdateAsync' and 'reloadAsync', it is also used to stop rendering UI before app updates or 10 seconds passes. I tested it out with bad internet connection and app doesn't render UI after 10 seconds, instead it waits until 'checkForUpdateAsync' fails (this is around 10 sec more in case of minimal reproduction, and up to 3 minutes (!) in case of our production app) and then starts to work as expected. I tried to run regular fetch in place of 'checkForUpdateAsync' and it doesn't cause any delay (you can try that out in repro).
Everything works fine on iOS

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 2022.01.17.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.10 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/arekm213/expoupdatesandroidrepro
Steps to reproduce:
1. Clone above repo
2. Change AndroidManifest expo updates properties and app.json properties so you can push OTA update
3. Run `npx react-native run-android --variant=release` to build release app to your device
4. Kill your app on the phone
5. Change your preferred network type to 2G only, or try to simulate slow internet connection in some other way
6. Push OTA update `expo publish --target bare --release-channel [release channel]`
7. Run `adb logcat` command on your device, run the app
8. Watch logs - in case of regular fetch "EXPO-UPDATE ONLAYOUT" log should appear right after "EXPO-UPDATE TIMEOUT PASSED" and in case of 'checkForUpdateAsync' its gonna appear after 10 seconds or more

**Comment by wschurman** [comment]
Still planning to look into this but it may still be a little while before I get to it.

**Comment by thespacemanatee** [comment]
This issue is not stale!

**Comment by thespacemanatee** [comment]
@wschurman this issue is still affecting us. It seems like whenever we call `checkForUpdateAsync`, the a re-render will be triggered on the entire app. This is not that visible on lighter screens, but is very visible when we purposely call this function on a heavy screen. I cannot send a screen recording because of NDA, but feel free to reach out privately. We are a customer on EAS Enterprise.

**Comment by wschurman** [comment]
@thespacemanatee - will take a look, sorry. I had thought that one of the refactors I did in the past year might have fixed it but maybe none did. Just to confirm, this issue is still affecting you even on SDK 50/51?

**Comment by thespacemanatee** [comment]
> @thespacemanatee - will take a look, sorry. I had thought that one of the refactors I did in the past year might have fixed it but maybe none did. Just to confirm, this issue is still affecting you even on SDK 50/51?

No worries and appreciate the response. Yes, we are on SDK 51 and it's happening for us, although the problem might be slightly different than what's described in this issue, since it's just a re-render and not some sort of deadlock. Let me create a new issue when I'm able to create a repro soon so that there's more information to work on.

**Comment by baochungit** [comment]
My app is using SDK 50 and it also happens. I can see after calling reloadAsync, my app freezes to wait for checkForUpdateAsync finish but it seems never done in this session. I have to restart my app

**Comment by wschurman** [comment]
@baochungit - does upgrading to SDK 51 fix it for you?

**Comment by baochungit** [comment]
@wschurman I'm not upgrading to SDK 51 at the moment, there are still something I want to stick with it (Constants.installationId for ex).
Is there any patches for this issue for SDK 50?

I see sometimes the checkForUpdateAsync works and sometimes it doesn't (await keep forever). It happens after app reloaded by reloadAsync

**Comment by wschurman** [comment]
> Is there any patches for this issue for SDK 50?

Unfortunately, no. I believe the large refactor done for SDK 51 is what fixed it, or at least improved it. The large refactor isn't patchable.

**Comment by wschurman** [comment]
Just getting back to re-reading this. It seems that the original issue is no longer present in 51. If this assessment is incorrect, please file a new issue. Closing this one due to staleness.

@thespacemanatee - a re-render is expected if there's some data in your component that changes due to updates state. If still repro'able, definitely file a new issue with a repro and I'd be happy to take a look.

**Comment by arekm213** [comment]
I can confirm that i checked if the issue still exists, and it doesn't. Thanks for fixing it!
