### ISSUE TITLE
Expo-Go does not work on GrapheneOs (Android13 without google-services)

### ISSUE THREAD

**Issue by TimoGoetze** [expo/expo#19217]
### Summary

I expect to be abe to use expo-go for development on devices even without google-framework such as Huawai, Amazon or /e/, Lineage, Grapheneos.

On GrapheneOs on Pixel6, Barcode scanner doesnt work - shows only black screen and entering URL manually gives only error screen without further error or stacktrace.

The cause for the camera and URL exp:// .. Problems is unknown to me. It is 100% reproducable. It works as soon as you install google framework. - But this is not the intention.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

expo go as of 2022-09-20

### Environment

Expo Go App on Android 13 (GrapheneOs)  without google framework.

### Reproducible demo

try on grapheneOs . Its 100% reproducable without google services.

**Comment by TimoGoetze** [comment]
this is still an issue....

**Comment by SinbadTheSyncer** [comment]
still an issue...
