### ISSUE TITLE
Apps targeting Android 13 or above and using advertising ID

### ISSUE THREAD

**Issue by parniekovvakoms** [expo/expo#19218]
### Summary

I use expo managed flow and when I want to upload an app to PlayMarket, console returns me warning: 

Apps targeting Android 13 or above and using advertising ID must include the [com.google.android.gms.permission.AD](http://com.google.android.gms.permission.ad/)_ID permission in the manifest.

Can I add any additional permission to Android manifest file which is not included in the list https://docs.expo.dev/versions/latest/config/app/#permissions ?

### What platform(s) does this occur on?

Android

### Environment

.

### Minimal reproducible example

.

**Comment by brentvatne** [comment]
there are existing discussions about this, eg: https://forums.expo.dev/t/you-must-complete-the-advertising-id-declaration-before-releasing-an-app-that-targets-android-13

**Comment by Jorundur** [comment]
@brentvatne Do you have a link to a discussion for users that have to answer "Yes" to this question? I'm on Expo 44, using `expo-analytics-segment` and in the process of building via `eas build` to upload to Google Play Store.

What I'm mainly looking for is info regarding whether or not I need to take additional steps after answering Yes to that question - mainly, do I need to provide the Advertising ID myself ("the com.google.android.gms.permission.AD_ID permission in the manifest" mentioned above) or is that "built into" the `expo-analytics-segment` package?

**Comment by Jorundur** [comment]
For users that need to say "Yes" to the question, see this: https://forums.expo.dev/t/expo-44-using-expo-segment-analytics-is-advertising-id-handled-automatically/67212

**Comment by terrierscript** [comment]
I got same issue and resolved with `blockPermissions` option in `app.config.js`
* https://docs.expo.dev/versions/latest/config/app/#blockedpermissions

**Comment by morris14** [comment]
@terrierscript which key did you put into blockPermissions in order to get rid of the error for Advertising ID please?

**Comment by jessemezini** [comment]
Check this answer: https://stackoverflow.com/questions/73129574/you-cant-submit-updates-as-some-information-about-your-app-is-incomplete-googl 

In my case I'm using @react-native-firebase/analytics. Select 'Yes' then 'Analytics' and save.
