### ISSUE TITLE
Size is 26mb of plain create-react-native-app

### ISSUE THREAD

**Issue by palash7563** [expo/expo#1921]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please use `exp send` with exp, the “Send” button with XDE, or the "s" hotkey with create-react-native-app to send your project development URL to your phone by SMS or email.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Environment

Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: Not Found
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/palashg7563-be875ca2-6a1d-4e2d-b2aa-3cd9dfc494d9.tar.gz

Android

### Steps to Reproduce

(Write your steps here:)

1.Just build the simple plain create-react-native-app and size of the build apk is 26mb
2.
3.

### Expected Behavior

if buid size of the scratch app is 26 mb what would happen if i would code

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

https://github.com/react-community/create-react-native-app

**Comment by palash7563** [comment]
build id - default-0bae69e8-11a5-40a4-a694-3b9e40c473aa

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/v28.0.0/introduction/why-not-expo#if-you-need-to-keep-your-app

**Comment by palash7563** [comment]
Thanks 👍
