### ISSUE TITLE
Expo bare-workflow app is crashing when expo-localization is imported

### ISSUE THREAD

**Issue by DreamGamer** [expo/expo#19221]
### Summary

My app was crashing all the time, when i was reloading the app. And sometimes it also crashed randomly. I looked into the deivce log with flipper to get more information and there was this error everytime i reload the app:

> /root/react-native/ReactCommon/jsi/JSCRuntime.cpp:395: virtual facebook::jsc::JSCRuntime::~JSCRuntime(): assertion "objectCounter_ == 0 && "JSCRuntime destroyed with a dangling API object"" failed

I tryed everything to get the reason for this error and after a month i found it. I was importing `expo-localization`, because i used it before i switched to react-native-localize. I imported it like this:
`import * as Localization from "expo-localization"`

And this line, is making these crashed. I created a new Expo bare-worklfow project with SDK 46, added expo-localization to it and i imported the package at the top of app.js again like `import * as Localization from "expo-localization"`. After i run npm run android, everything worked fine, as before, but when i reload the app, for example through the console, the app is crashing evertime.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.12.0 - F:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.1 - F:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: bare

"dependencies": {
    "expo": "~46.0.9",
    "expo-localization": "^13.1.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.5",
    "react-native-web": "~0.18.7"
  }

### Minimal reproducible example

Run > `npx create-expo-app --template` > choose "Blank (Bare)"
Go into project folder and run `npm i expo-localization`
Import expo-localization like this `import * as Localization from "expo-localization"` in App.js
Run `npm run android`. After the app loaded, reload the app 1 or 2 times.

**Comment by PingvinB** [comment]
I experience the same problem with expo-localization@13.1.0 on expo managed workflow running on sdk 46.
The crash doesn't happen anymore if I roll back to expo-localization@13.0.0.
