### ISSUE TITLE
[RFC] AppLoading / SplashScreen usability issues

### ISSUE THREAD

**Issue by slorber** [expo/expo#1923]
Hi,

I've been using `<AppLoading/>` for a while now and have faced some issues with it.

I'm using a component to load resources on app so that while loading resources, the splash screen remains visible. It can also handle retry on loading failure.

https://gist.github.com/slorber/9b190091f52111b5fef71a36a7ef5dfa

I have an HOC chain (based on above generic HOC) to do so 

```
let MyApp = () => {...};

MyApp = compose(
  provideFonts,
  provideDeviceLanguage,
  provideStartupAsyncStorageData,
  provideAuthentication,
  provideBootstrapData,
)(MyApp);
```

`provideAuthentication` is a bit different, because it shows a login screen if the user is not authenticated, and show wrapped comp if authenticated

----------------------------

First, I think my HOC works fine but it is unclear to me where in it I am supposed to set the state of the data I got through the promise. Even if not necessary, I think if there was an "onSuccess" prop, the API would be more clear. If you can suggest me how can I make my HOC better please tell me.

----------------------------

Second: as you can see, the provideBootstrapData HOC runs after the authentication protection, which may display a screen. The thing is, if the user starts the app being authenticated, I want to display the splash screen until the bootstrap datas are loaded, and if the user starts unauthenticated, he will have to login, so I want to present the login screen and then load the bootstrap datas with a regular spinner. 

Also, in the retry logic of my HOC, as we have to present a screen to the user, the splash screen gets removed, and then rendering <AppLoading/> again will actually render a blank screen.

As far as I know, there is no way to know when the splash screen is actually dismissed so I can't switch between SplashScreen and spinner, currently I get SplashScreen or blank (which produce a weird visual effect).

I'd like to be able to write:

```js
        if ( SplashScreen.isVisible() ) {
          return (
            <AppLoading
              startAsync={this.loadAsyncData}
              onFinish={() => this.setState({ isReady: true })}
            />
          );
        }
        else {
          return <ActivityIndicator/>
       }
```

Alternatively, I think it would be nice to be able to provide a fallback component to the `<AppLoading/>` component, so that if the splash screen is already dismissed and we render `<AppLoading/>`, it renders something else than a blank screen:

```js
            <AppLoading
              startAsync={this.loadAsyncData}
              onFinish={() => this.setState({ isReady: true })}
              fallback={<ActivityIndicator/>}
            />
```

I don't know which API would be better, just want to open the discussion and share my issues with current implementation, so please comment and don't hesitate to give me workarounds if you have any.

**Comment by brentvatne** [comment]
heya, we have some improvements due for our next release that gives you more control over the splash screen. here's a screen shot from the diff

<img width="899" alt="screen shot 2018-06-27 at 6 09 48 pm" src="https://user-images.githubusercontent.com/90494/42007494-4f3e7ec8-7a35-11e8-8c1b-550a51a55476.png">

basically you don't need to render the `AppLoading` component at all if you don't want to, just call `SplashScreen.preventAutoHide()` somewhere on your apps initial render and then `SplashScreen.hide()` when you want to hide it

**Comment by slorber** [comment]
thanks, that will probably solve my usecase, as I can prevent auto hide, and hide when I show any screen to the user (login screen or app home screen)

The comment say we can "combine it with AppLoading", not sure to understand what this means. My intuition is that if preventAutoHide is called, AppLoading removal from the tree will not trigger splashscreen to be removed anymore and I have to call hide() manually, so what's the point of keeping AppLoading usage? I could actually simply load state with regular promises

**Comment by FiberJW** [comment]
This seems to be resolved, so I’ll close this for now. If you need further support, please make a topic on our [forums](https://forums.expo.io) :)
