### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by Salmankhan033** [expo/expo#19232]
### Summary

undefined is not an object (evaluating '_ExponentFacebook.default.initializeAsync'
I followed the documentation but get this error.

![WhatsApp Image 2022-09-24 at 12 32 47 AM](https://user-images.githubusercontent.com/58082294/192062485-e9efbcb6-d97e-4b24-8ef6-b29b9004fcaa.jpeg)

<img width="1393" alt="Screenshot 2022-09-24 at 3 03 00 AM" src="https://user-images.githubusercontent.com/58082294/192062964-069a01f4-cad2-44ce-b76b-7853493d59ac.png">

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.7.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.2 - /usr/local/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

 const facebookLogIn = async () => {
    try {
      await Facebook.initializeAsync({
        appId: "11888916816.......",
      });
      const { type, token, expirationDate, permissions, declinedPermissions } =
        await Facebook.logInWithReadPermissionsAsync({
          permissions: ["public_profile"],
        });
      if (type === "success") {
        // Get the user's name using Facebook's Graph API
        const response = await fetch(
          `https://graph.facebook.com/me?access_token=${token}`
        );
        console.log("Logged", await response.json().name);
        Alert.alert("Logged in!", `Hi ${(await response.json()).name}!`);
      } else {
        // type === 'cancel'
      }
    } catch ({ message }) {
      console.log("eeee", message);
      alert(`Facebook Login Error: ${message}`);
    }
  };

**Comment by hellotreedigital** [comment]
Having the same issue here...
`"dependencies": {
    "@react-native-masked-view/masked-view": "0.2.7",
    "@react-navigation/stack": "^6.3.0",
    "axios": "^0.27.2",
    "expo": "~46.0.9",
    "expo-apple-authentication": "~4.3.0",
    "expo-auth-session": "~3.7.1",
    "expo-facebook": "^12.2.0",
    "expo-font": "~10.2.0",
    "expo-random": "~12.3.0",
    "expo-secure-store": "~11.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.5",
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-pager-view": "5.4.24",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "12.3.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-tab-view": "^3.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },`

**Comment by jurica-penjgusic** [comment]
In order to use expo facebook with latest expo go 46, custom expo dev client is needed. 

Expo facebook is depreceted from sdk 46 and replacement suggestions can be found here[Expo Facebook Alternative](https://docs.expo.dev/versions/v45.0.0/sdk/facebook/)
