### ISSUE TITLE
expo start --tunnel fails to start after upgrading from SDK 45 to 46

### ISSUE THREAD

**Issue by lelimit** [expo/expo#19240]
### Summary

Run: expo start --tunnel in terminal 
Result: 
Starting Metro Bundler
Failed to resolve the Android SDK path. Default install location not found: C:\Users\Admin\AppData\Local\Android\Sdk. Use ANDROID_HOME to set the Android SDK location.
Failed to resolve the Android SDK path. Default install location not found: C:\Users\Admin\AppData\Local\Android\Sdk. Use ANDROID_HOME to set the Android SDK location.
Error: 'adb' is not recognized as an internal or external command,
operable program or batch file.
Error: 'adb' is not recognized as an internal or external command,
operable program or batch file.
    at notFoundError (C:\Git\lendlord\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Git\lendlord\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Git\lendlord\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

### SDK Version

46.0.10

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ~0.17.2 => 0.17.2
      expo: ~46.0.10 => 46.0.10
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.0 => 0.70.0
      react-native-web: 0.18.9 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

Run: expo start --tunnel

**Comment by thyagoquintas** [comment]
I'm getting the same error, I do not have Android Studio installed because I used to test all the projects directly on iPhone device. So it's necessary to have installed it only to use the tunnel (ngrock)?

![error](https://user-images.githubusercontent.com/1860278/192679606-9c69d74a-caca-447a-bf47-5faf16c60815.png)

**Comment by nuttyartist** [comment]
I have the same issue. Did someone get around it?

**Comment by jonatan1kruse** [comment]
I have the same issue and tried to fix it for a couple of months but now just developing without the expo go app

**Comment by LuisFernandoLG** [comment]
I had the same issue. I was running the next command
`npx expo start --tunnel`

Then, I tried just with the next command and it worked.
`expo start --tunnel`

**Comment by OsamaMohamedAtta** [comment]
I have the same issue too

**Comment by RSchneider94** [comment]
Unfortunately this is still not found, still having the issue, using the latest `expo-cli`:

```bash
❯ expo --version
WARNING: expo-cli has not yet been tested against Node.js v18.9.1.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

6.0.6
```

**Comment by manozzo** [comment]
> 

That's so simple and worked so well! Thank you very much.

Valeu cara!!!

**Comment by basimkarhabi** [comment]
Thanks  That work for me 👍😊

**Comment by Keeryel** [comment]
> I'm getting the same error, I do not have Android Studio installed because I used to test all the projects directly on iPhone device. So it's necessary to have installed it only to use the tunnel (ngrock)?
> 
> ![error](https://user-images.githubusercontent.com/1860278/192679606-9c69d74a-caca-447a-bf47-5faf16c60815.png)

I am getting the exact same error.

**Comment by Ang-Wei-Liang** [comment]
Is it solved?

**Comment by tanvir-faysal-xeon** [comment]
- You can try this command
npx expo install react-native-web@~0.18.9 react-dom@18.1.0 @expo/webpack-config@^0.17.2

**Comment by Aunie** [comment]
Hi, I have found a solution for this. You need to enable tunneling first and for this run the following command on your terminal:
 npm i -g @expo/ngrok

After enabling the terminal run the following command:
npx expo start --tunnel

and Voilla
