### ISSUE TITLE
How can I view EXPO logs when the app crashes before startup

### ISSUE THREAD

**Issue by KeatonMacLeod** [expo/expo#19241]
### Summary

I've spent 8 hours+ trying to debug this problem; and I've seen a million threads at this point of devs saying EXPO works fine running locally, but crashes during runtime after doing a successful EAS BUILD + running that .APK on their device; I'm in the exact same scenario.

My application runs without any issue using it locally, ie.) via expo start, npx expo start, expo start --tunnel, etc... however, whenever I try to run the .APK which gets created by a successful build from running (eas build --platform android --profile development) on my Android S20 Ultra, the app crashes immediately on startup; I'm just trying to integrate google ad mob ads into my react native app.

There's 0 console output logs, I've connected ADB on my dev machine and there's no logs there, try + catch(ing) anything in code doesn't output anything because it crashes immediately, and EXPO doesn't give any information as to what's going wrong. It's beyond me at this point how anyone would power through this kind of scenario, so I'm assuming others have found a way to get logs for the "crash before app startup" problem.

Can you please point me to some resource that shows how I can get a sniff at some logs before my app crashes for the millionth time :L

My heart really can't take using this tool anymore because it's absolutely soul-crushing to spend mindless time trying to think of something which could be the problem, and then needing to wait 10m for EAS BUILD to finish only for the app to crash again.

packages.json:

```
{
  "name": "riddl",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/hooks": "^2.8.1",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "date-fns": "^2.29.2",
    "expo": "~46.0.9",
    "expo-asset": "~8.6.1",
    "expo-dev-client": "~1.2.1",
    "expo-font": "~10.2.0",
    "expo-navigation-bar": "~1.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-system-ui": "~1.3.0",
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-fade-in-out": "^1.0.6",
    "react-native-google-mobile-ads": "^8.1.0",
    "react-native-maps": "0.31.1",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-sha1": "^1.2.3"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.70.3",
    "react-test-renderer": "18.0.0"
  },
  "private": true
}

```

eas.json:
```

{
  "cli": {
    "version": ">= 2.1.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

```

index.js:

```
import { registerRootComponent } from 'expo';
import RiddlApp from './App';

registerRootComponent(RiddlApp);

```

app.json:

```
{
  "expo": {
    "name": "Riddl",
    "slug": "RiddlApp",
    "version": "1.0.1",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.keatonmacleod.RiddlApp"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "5acf994f-29f5-455e-b025-e91a03322292"
      }
    }
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-2409163852955596/1481803446",
    "ios_app_id": "ca-app-pub-2409163852955596/1481803446"
  }
}

```

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

npm expo-dev-client --version
8.15.0

npm expo-updates --version
8.15.0

### Environment

npx expo-env-info
Need to install the following packages:
  expo-env-info@1.0.5
Ok to proceed? (y) y

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 31, 32
        Build Tools: 30.0.3, 32.0.0, 32.1.0
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    Expo Workflow: managed

### Reproducible demo

I don't know what part of the code is causing the problem, as mentioned it looks like people have encountered this from a bad app id, to a React.useState, to a bad npm package.

Is there some way that I can see logs for this? As currently this kind of debugging is impossible, I can't find a resource anywhere that will let me get a hint at what could be causing the problem for my app.

### Stacktrace (if a crash is involved)

There's 0 logs.

**Comment by lukmccall** [comment]
Hi, thanks for your report. You can always see native logs from your device. Here https://docs.expo.dev/workflow/debugging/#native-debugging is a quick tutorial on how it can be done via Android Studio. If you don't want to use AS, try bare `adb` - https://developer.android.com/studio/command-line/logcat.

Moreover, I would advise building your project locally using Android Studio to debug problems like this. `expo prebuild` will generate a native project that can be opened and built from the AS.

**Comment by KeatonMacLeod** [comment]
Thanks @lukmccall, this actually helped me uncover the issue, turns out I was using my ad unit id in the app.json as opposed to my APP id for GoogleAdMob, was ultimately able to debug it using your suggested method, and now I'm able to use the app without issue, thanks!

**Comment by kirtikapadiya** [comment]
I am getting same issue . APK crash on emulator and real device, SDK 46 and built with EAS managed workflow.
My application runs without any issue using it locally, ie. via npx expo start -c.

**Comment by Nnacamia** [comment]
Hello am having the same issue. I have done all O could, but to no anvil. Please I need help. 

And I have been seeing alot of issue with my few days report about the issue. I think expo can help us with a lasting solution to this.

**Comment by asierraserna** [comment]
Having the same issue on SDK 48. In the bright side! Learning to debug in AS is quite helpful :laughing:

**Comment by asierraserna** [comment]
alright! after a lot of IDE setup on Android Studio to be able to see the log of the apk, I finally found the issue and my app works!
React navigation needs react-native-gesture-handler, but is a bit hidden, so it doesn't show up as an error in expo go.
Install the react-native-gesture-handler, add the dependency in the app.js and that does did trick for me!

**Comment by snx-mfallon** [comment]
any alternative for iOS?

**Comment by HudsonMenezes** [comment]
@asierraserna Can you explain to us how did you found this issue and this IDE setup to Android Studio? So the next time it happen, we could find ourselves. And thanks!

**Comment by asierraserna** [comment]
> @asierraserna Can you explain to us how did you found this issue and this IDE setup to Android Studio? So the next time it happen, we could find ourselves. And thanks!

Hello there! @HudsonMenezes!

to generate the apk, follow these instructions https://docs.expo.dev/build-reference/apk/
The installation directly to my emulator did not work well, so I simply sent the apk via email to myself, and downloaded in the emulator. That allowed me to install it.

Then, having Android Studio and the emulator open, follow the instructions from here: https://developer.android.com/studio/debug/logcat

I was able to se the exact problem using logcat.

I hope this helps!

@snx-mfallon, unfortunately I don’t not know the equivalent for ios 😔
