### ISSUE TITLE
Fail adding a React-Native bridge package to expo with expo prebuild

### ISSUE THREAD

**Issue by Kubessandra** [expo/expo#19242]
### Summary

I'm trying to implement a new package I just created for react-native([react-native-dji-mobile-sdk](https://github.com/Kubessandra/react-native-dji-mobile-sdk)) in the `expo-dev-client`, using the prebuild.

This issue is when the app launch it instantly show this Error: `Exception in HostObject::get(propName:DJISDKAircraftWrapper): java.lang.NoClassDefFoundError: Failed resolution of: Ldji/common/error/DJIError;`

This is working on a new react-native project.
This is not working on a new expo project when running `expo run-android` (using prebuild).

Probably an issue with the linking of the gradle dependencies of the package.
Maybe what I want to do is not possible with expo, but I was assuming that it was possible to add a react-native package with a development build, I'm just probably doing something wrong.
### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

```json
{
  "name": "awesomeproject",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~46.0.9",
    "expo-dev-client": "~1.2.1",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.5",
    "react-native-dji-mobile-sdk": "^0.2.14",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
      npm: 8.15.1 - ~/.nvm/versions/node/v18.7.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.0.0
    Expo Workflow: bare

### Reproducible demo

- Create a new expo project
- Replace your App.js by this one:
```js
import { StatusBar } from 'expo-status-bar';
import { sdkManager } from 'react-native-dji-mobile-sdk';
import { StyleSheet, Text, View } from 'react-native';
import { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    console.log(sdkManager.SDKRegistered);
  }, [])

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

```bash
yarn add react-native-dji-mobile-sdk
yarn android
```

app.json
```json
{
  "expo": {
    "name": "AwesomeProject",
    "slug": "AwesomeProject",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.kubessandra.AwesomeProject"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.kubessandra.AwesomeProject"
    },
    "plugins": [
      "react-native-dji-mobile-sdk"
    ],
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "102e4b6a-cd62-433a-80bd-dbbcc2f9f647"
      }
    }
  }
}

```

**Comment by Kubessandra** [comment]
Hi, any news about this ?

**Comment by Kubessandra** [comment]
Update on this ?

**Comment by Kudo** [comment]
hi there! i'm sorry to get back late. the issue is a little complicated to explain.

### NoClassDefFoundError 

the `java.lang.NoClassDefFoundError: Failed resolution of: Ldji/common/error/DJIError;` should be a real problem for both expo project and the new react-native project. trying to verify this by the patch:

```diff
--- a/node_modules/react-native-dji-mobile-sdk/android/src/main/java/com/reactnativedjimobilesdk/DJISDKAircraftWrapper.kt
+++ b/node_modules/react-native-dji-mobile-sdk/android/src/main/java/com/reactnativedjimobilesdk/DJISDKAircraftWrapper.kt
@@ -14,6 +14,14 @@ import java.util.*
 import kotlin.concurrent.schedule

 class DJISDKAircraftWrapper(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {
+  init {
+    try {
+      Class.forName("dji.common.error.DJIError")
+    } catch (e: Exception) {
+      Log.e("ERROR", "EXPECTED EXCEPTION", e)
+    }
+  }
+
   override fun getName(): String {
     return "DJISDKAircraftWrapper"
   }
```

the adb log shows the expected exception:

```
                  ERROR  E  EXPECTED EXCEPTION
                         E  java.lang.ClassNotFoundException: dji.common.error.DJIError
                         E      at java.lang.Class.classForName(Native Method)
                         E      at java.lang.Class.forName(Class.java:454)
                         E      at java.lang.Class.forName(Class.java:379)
                         E      at com.reactnativedjimobilesdk.DJISDKAircraftWrapper.<init>(DJISDKAircraftWrapper.kt:19)
                         E      at com.reactnativedjimobilesdk.DJIMobileSdkPackage.createNativeModules(DJIMobileSdkPackage.kt:13)
                         E      at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
                         E      at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
                         E      at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1456)
                         E      at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1427)
                         E      at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1338)
                         E      at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:136)
                         E      at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1108)
                         E      at java.lang.Thread.run(Thread.java:1012)
                         E  Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.common.error.DJIError" on path: DexPathList[[dex file "/data/data/com.testapp/code_cache/.overlay/base.apk/classes13.dex", zip file "/data/app/~~T2pGvxmCQJGgq70BFsUTWQ==/com.testapp-aEn2t9od1TyTQKcfaRvQ1g==/base.apk"
                            ],nativeLibraryDirectories=[/data/app/~~T2pGvxmCQJGgq70BFsUTWQ==/com.testapp-aEn2t9od1TyTQKcfaRvQ1g==/lib/arm64, /data/app/~~T2pGvxmCQJGgq70BFsUTWQ==/com.testapp-aEn2t9od1TyTQKcfaRvQ1g==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                         E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                         E      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                         E      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                         E      ... 13 more
```

the issue might come from the dji sdk. i don't know much about how the class is not found. please report the issue to dji upstream.

### why only expo project shows the error

by default the react-native project turns on [inlineRequires](https://reactnative.dev/docs/ram-bundles-inline-requires#inline-requires) but expo project does not. we will evaluate the import as early as you import the module. since the module throws exceptions, the app crashes at the early stage. you could try to disable the `inlineRequires` in your metro.config.js in the react-native project. then it should act the same as the expo project.

**Comment by Kubessandra** [comment]
@Kudo Hi

Thank you, I will verify one thing that I fixed in my package two days ago about the DEXpath classes and proguards.
This is probably related, and this is maybe working now since I added a proguard to the library

**Comment by Kudo** [comment]
cool, thanks for the update!
