### ISSUE TITLE
Build stuck in queue

### ISSUE THREAD

**Issue by MuonDevelopment** [expo/expo#1925]
After i tried to build my project for iOS, i received **timeout** error on the terminal. In the builds section in the expo portal, i see queued build, but i can not cancel nor see what is happening with the process. I also can not start a new build since there is already one in the queue. Can you please help me. 

This is my build : [Build Url](https://expo.io/builds/284bd4a2-33f4-4455-8e0f-ccc941e80787)

Thank you in advance.

**Comment by msevestre** [comment]
@MuonDevelopment I am having the same issue at the moment. The build server is probably experiencing some serious load at the moment. Just be patient and check again in one hour. My build has been queued for over one hour now
