### ISSUE TITLE
launchImageLibraryAsync api enter file system but not photo liabrary for android 7+ device

### ISSUE THREAD

**Issue by OPChips** [expo/expo#1926]
![img_3221](https://user-images.githubusercontent.com/23147836/42008477-4f851760-7ab8-11e8-88ba-f1a3860e13c8.PNG)

expo: 27.0.0
react: 16.3.1
react-native: expo fork 27.0.0
npm: 5.6.0
node: 8.11.1

**Comment by anp** [comment]
Hi! Could you tell us what device you're seeing this on, what OS version, etc?

**Comment by OPChips** [comment]
@anp 
device name: oppo R11plus
android version: 7.1.1

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
