### ISSUE TITLE
[docs] EAS worker IPs are not up-to-date

### ISSUE THREAD

**Issue by KiwiKilian** [expo/expo#19265]
### Summary

The current list of [EAS Build Worker IPs](https://expo.dev/eas-build-worker-ips.txt) is not up-to-date. Android EAS Builds I have ran in the last two hours currently seem to use `34.135.108.214` – not listed in the txt file:

```
35.232.137.35
35.239.133.62
34.72.63.127
207.254.54.60
```

To determine the IP used by the worker I added the following to the package.json:
```json
 "eas-build-pre-install": "curl icanhazip.com",
 ```

### Link to the related docs page

https://expo.dev/eas-build-worker-ips.txt

### Anything else?

It would be nice to have this `txt` in git to see any changes.

**Comment by amandeepmittal** [comment]
Hey @KiwiKilian, there is an [open PR here](https://github.com/expo/universe/pull/10584/files) to update the list.

**Comment by KiwiKilian** [comment]
@amandeepmittal thanks for tuning in – this repo/PR is not public. Could this file maybe moved to a public repo?

**Comment by amandeepmittal** [comment]
@KiwiKilian, my bad for linking to the private repo 😅  I updated the comment above with the list. Please have a look.

**Comment by amandeepmittal** [comment]
@KiwiKilian, the update is now live. Please refer to [https://expo.dev/eas-build-worker-ips.txt](https://expo.dev/eas-build-worker-ips.txt) for an up-to-date list.
