### ISSUE TITLE
iOS 16 Multiple Print Bug

### ISSUE THREAD

**Issue by nathanael-rsu** [expo/expo#19275]
### Summary

I have two React Native applications that use `expo-print` for label printing (i.e. with Brother Label Printer QL-810W). I noticed recently that when I print multiple times in either application, the label printing is inconsistent. It will print perfectly correct once, and the next time it prints off-center and multiple blank labels (I only ever want one label printed at a time).

I am almost certain this is an iOS 16 issue, because I haven't made any changes to one of these apps in a while, and printing was stable until recently. The issue only happens on iOS 16 devices. I tested on Android and iOS 15 and both are still stable. I also tested with multiple physical iOS 16 devices and an iOS 16 simulator. I am not sure whether this is an expo bug or an Apple bug, but I appreciate any help.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.2 - /usr/local/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/username/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: 46.0.7 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Expo Workflow: bare

### Minimal reproducible example

```
await Print.selectPrinterAsync().then(async (printer) => {
    await Print.printAsync({
	    html: imgHtml,
	    margins: {
		    left: 0,
		    right: 0,
		    top: 0,
		    bottom: 0
	    },
	    useMarkupFormatter: true,
	    orientation: "landscape",
	    printerUrl: printer.url
    }).then(() => {
	    resolve(true);
    }).catch((err_1) => {
	    resolve(false);
    });
}).catch((err_2) => {
    resolve(false);
});
```

**Comment by brentvatne** [comment]
@nathanael-rsu - can you please share examples of what you are seeing and specific documents that can be printed along with information about how to reproduce? the code provided is not sufficient for a reproducible example. 

on ios we use [UIPrintInteractionController](https://developer.apple.com/documentation/uikit/uiprintinteractioncontroller) - it may be worth googling to see if you can find any issues that other folks are reporting that match up with your experience

**Comment by nathanael-rsu** [comment]
Hi @brentvatne. Thanks for looking into this -- I have updated my reproducible example with the HTML that I am printing, and a picture of the bug. Please let me know if I can give any more useful information.
