### ISSUE TITLE
android app stores detect google ads in detached and release app, how to fully remove build-in expo ads in android device or disable it so that app stores cannot detect that

### ISSUE THREAD

**Issue by OPChips** [expo/expo#1927]
In China, for my detached and release app, most of android app stores, like XiaoMi, OPPO detect google ads, then alert users  carefully install the app. And it bother me so much. So how can I fully remove all ads in Android Studio, and what steps to remove it? Please tell me, it is very important to me.

![img_3222](https://user-images.githubusercontent.com/23147836/42008629-2c4e0d6e-7ab9-11e8-8cc4-3dcced609339.PNG)

**Comment by OPChips** [comment]
anyone can help me how to fully remove expo google ads in android studio?

**Comment by jesseruder** [comment]
Hi, you'll have to remove the `com.google.android.gms:play-services-ads:12.0.1` dependency.

**Comment by OPChips** [comment]
hi, I have removed the dependency, but still detect ads. Is there exit in build cache?
below is my part build.gradle:

// Our dependencies from ExpoView
// DON'T ADD ANYTHING HERE THAT ISN'T IN EXPOVIEW. ONLY COPY THINGS FROM EXPOVIEW TO HERE.
  compile 'com.android.support:appcompat-v7:23.0.1'
  compile 'com.facebook.android:facebook-android-sdk:4.7.0'
//  compile('com.facebook.android:audience-network-sdk:4.22.1') {
//    exclude module: 'play-services-ads'
//  }
  provided 'org.glassfish:javax.annotation:3.1.1'
  compile 'com.jakewharton:butterknife:7.0.1'
  compile 'de.greenrobot:eventbus:2.4.0'
  compile 'com.amplitude:android-sdk:2.9.2' // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
  compile 'com.squareup.picasso:picasso:2.5.2'
  compile 'com.google.android.gms:play-services-gcm:9.8.0'
//  compile 'com.google.android.gms:play-services-analytics:9.8.0'
//  compile 'com.google.android.gms:play-services-maps:9.8.0'
//  compile 'com.google.android.gms:play-services-auth:9.8.0'
//  compile 'com.google.android.gms:play-services-location:9.8.0'
//  compile 'com.google.android.gms:play-services-ads:9.8.0'

**Comment by OPChips** [comment]
hi @jesseruder , I have removed the dependency, but still detect ads. Is there exit in build cache?
below is my part build.gradle:

// Our dependencies from ExpoView
// DON'T ADD ANYTHING HERE THAT ISN'T IN EXPOVIEW. ONLY COPY THINGS FROM EXPOVIEW TO HERE.
compile 'com.android.support:appcompat-v7:23.0.1'
compile 'com.facebook.android:facebook-android-sdk:4.7.0'
// compile('com.facebook.android:audience-network-sdk:4.22.1') {
// exclude module: 'play-services-ads'
// }
provided 'org.glassfish:javax.annotation:3.1.1'
compile 'com.jakewharton:butterknife:7.0.1'
compile 'de.greenrobot:eventbus:2.4.0'
compile 'com.amplitude:android-sdk:2.9.2' // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.google.android.gms:play-services-gcm:9.8.0'
// compile 'com.google.android.gms:play-services-analytics:9.8.0'
// compile 'com.google.android.gms:play-services-maps:9.8.0'
// compile 'com.google.android.gms:play-services-auth:9.8.0'
// compile 'com.google.android.gms:play-services-location:9.8.0'
// compile 'com.google.android.gms:play-services-ads:9.8.0'

**Comment by esamelson** [comment]
Hi, this is now fully supported in the bare workflow by not installing the `expo-ads-admob` and `expo-ads-facebook` packages from NPM. As this issue is inactive I'm going to go ahead and close it. Please post on our [forums](https://forums.expo.io/) if you have any questions, or open a new issue if you find a bug. Thanks!
