### ISSUE TITLE
expo-image-picker  -->  Could not resolve com.github.CanHub:Android-Image-Cropper:4.3.0.

### ISSUE THREAD

**Issue by Yuvrajedulab** [expo/expo#19282]
### Summary

[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
![Screenshot from 2022-09-28 15-34-48](https://user-images.githubusercontent.com/85078788/192751824-8595185d-e390-4900-89c4-b5c677e67903.png)

[stderr] Could not determine the dependencies of task ':app:lintVitalReportRelease'.
[stderr] > Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
[stderr]    > Could not resolve com.github.CanHub:Android-Image-Cropper:4.3.0.
[stderr]      Required by:
[stderr]          project :app > project :expo > project :expo-image-picker
[stderr]       > Could not resolve com.github.CanHub:Android-Image-Cropper:4.3.0.
[stderr]          > Could not get resource 'https://www.jitpack.io/com/github/CanHub/Android-Image-Cropper/4.3.0/Android-Image-Cropper-4.3.0.pom'.
[stderr]             > Could not GET 'https://www.jitpack.io/com/github/CanHub/Android-Image-Cropper/4.3.0/Android-Image-Cropper-4.3.0.pom'.
[stderr]                > Connect to www.jitpack.io:443 [www.jitpack.io/149.56.28.39] failed: Connection refused (Connection refused)
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 3m 35s

### What platform(s) does this occur on?

Android, Not Applicable

### Environment

on  eas build 

### Minimal reproducible example

when we are use eas build we are gettting the following error

what are the possible solution

**Comment by LipLoody** [comment]
It seems that jitpack is down: https://updownradar.com/status/jitpack.io

**Comment by pratikdhody** [comment]
It's back but I'm getting a 521 error now/also @Yuvrajedulab @LipLoody 

![image](https://user-images.githubusercontent.com/48036133/192757920-dd6838d0-9695-4218-b10a-7a9263bfea45.png)

**Comment by zail59** [comment]
It looks like jitpack.io is working but www.jitpack.io isn't ...

**Comment by LipLoody** [comment]
HTTP code 521 mean web server is down. Need to wait, I guess.

**Comment by pratikdhody** [comment]
appears as though Android-Image-Cropper is no longer supported :/
https://github.com/CanHub/Android-Image-Cropper/issues/444

**Comment by brentvatne** [comment]
closing this because the issue was a temporary jitpack availability problem.

@pratikdhody - that is unfortunate, although it looks like they're moving towards a new maintainer. we'll keep an eye on it

**Comment by CCB-cerivera** [comment]
> 

Did you find any solution that you can share?

**Comment by RazaShehryar** [comment]
Still facing this issue in expo SDK 47.

**Comment by bibhutiswain9** [comment]
Hey, I'm facing the same issue please open this issue.
