### ISSUE TITLE
[expo-location] watchPosition is not working(sending 'Expo.locationChanged' with no listeners registered)

### ISSUE THREAD

**Issue by kdthomas2121** [expo/expo#19294]
### Summary

Summary
Location.watchPositionAsync callback function is not called.

When requesting watch Position Async, warning occurs, "sending 'Expo.locationChanged' with no listeners registered."

Managed or bare workflow? If you have ios/ or android/ directories in your project, the answer is bare!
bare

What platform(s) does this occur on?
iOS

SDK Version (managed workflow only)
No response

Environment
Expo CLI 5.0.3 environment info:
System:
OS: macOS 11.6
Shell: 5.8 - /bin/zsh
Binaries:
Node: 14.17.0 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 7.19.1 - /usr/local/bin/npm
Watchman: 2022.01.17.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.2 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
Android SDK:
API Levels: 23, 27, 28, 29, 30
Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
IDEs:
Android Studio: 4.2 AI-202.7660.26.42.7351085
Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
npmPackages:
@expo/webpack-config: ^0.16.6 => 0.16.6
expo: >=43.0.0-0 <44.0.0 => 43.0.5
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.3 => 0.64.3
npmGlobalPackages:
expo-cli: 5.0.3
Expo Workflow: bare

![image](https://user-images.githubusercontent.com/32167371/192893115-449ce8fb-f03d-41d1-9d68-334d65219030.png)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /Users/kylethomas/.rvm/gems/ruby-2.4.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Reproducible demo

Reproducible demo
Location.watchPositionAsync(`
        {
          accuracy: Location.Accuracy.Highest,
          timeInterval: 5000,
          distanceInterval: 1,
        },
        (location) => {
          ConsoleLog(`ios foreground location changed: ${location}`);
          if (location?.coords?.latitude && location.coords?.longitude) {
            updateCurrentLocation(location.coords.latitude, location.coords.longitude);
          }
        }
      ).catch((error) => {
        alert(`error: ${error?.message}`);
      });

**Comment by Nsquik** [comment]
Same, happens for me with `Remote debugging` enabled. Works when disabled tho.

**Comment by kdthomas2121** [comment]
How do you know it works? As you might just not be seeing the error as
you're not seeing the error message?

**Comment by brentvatne** [comment]
I would recommend [moving to Hermes and using Hermes inspector for debugging](https://docs.expo.dev/guides/using-hermes/). Remote debugging has a bunch of drawbacks and doesn't work quite right in many situations, and we're moving away from that.

**Comment by kdthomas2121** [comment]
Ah I see, I'm a bit limited as I'm using an iOS sim with expo go which
looks like it isn't supported with Hermes. Is that coming soon? Thanks!

**Comment by tmaidment** [comment]
ditto, it's interesting that we are able to request location, but can't use watchPosition. Is there no way to use Expo Go with watchPosition?

**Comment by zavex** [comment]
facing similar issues on react native app using Location.watchPositionAsync
    "expo": "^46.0.0",
    "react-native": "0.69.6",
    "expo-updates": "~0.14.7",

```
com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'e.pieceNum_'), stack:
Yt@1173:60552
<unknown>@1173:145900
vt@1173:30830
no@1173:145855
Vo@1173:164386
<unknown>@1234:6270
value@1171:1068
<unknown>@1171:587
value@22:1282
value@61:3579
<unknown>@61:758
value@61:2582
value@61:730
value@-1

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:225)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:919)
```
