### ISSUE TITLE
Expo Dev Client update link containing null in url when changing App Scheme

### ISSUE THREAD

**Issue by tomKrueger** [expo/expo#19293]
### Summary

I have created a eas build to create a development client.

{
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    }
  }
}

After opening the Preview dialog I changed the AppScheme to the exposcheme for my development client so that the QR Code / url will open in my development client instead of the expo go client.

When doing so there is an error in the development client says:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/1824935/192878824-8ea10e30-76dd-4c1c-a932-a2501de62fed.png">

Notice the "null" in the url.

If I copy and paste the url from the preview dialog (i.e. not use the QR code) which doesn't contain null then I get this in my app:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/1824935/192879332-014bf63a-831a-4ed5-bb56-5cbd10fa2f84.png">

The expectation was that the update would show in my app without running a development server (similar to expo publish to expo go app)

I talked through this on the Expo Office Hours with TC@expo.io and Keith Kurak.  They can add more insight.

Thanks all,

Tom

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"dependencies": {
    "@expo/browser-polyfill": "^1.0.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-community/netinfo": "9.3.0",
    "@react-native-masked-view/masked-view": "0.2.7",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "crypto-js": "^4.1.1",
    "expo": "^46.0.0",
    "expo-camera": "~12.3.0",
    "expo-checkbox": "~2.2.0",
    "expo-device": "~4.3.0",
    "expo-image-manipulator": "~10.4.0",
    "expo-image-picker": "~13.3.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-location": "~14.3.0",
    "expo-notifications": "~0.16.1",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-tracking-transparency": "~2.3.1",
    "expo-updates": "~0.14.6",
    "expo-web-browser": "~11.0.0",
    "jest": "^26.6.3",
    "jest-expo": "^46.0.0",
    "metro-react-native-babel-preset": "^0.70.3",
    "mobx": "^6.6.0",
    "mobx-react": "^7.5.0",
    "moment": "^2.29.4",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-svg": "12.3.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "expo-dev-client": "^1.2.1",
    "react-test-renderer": "17"
  },

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.13 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Reproducible demo

Build a developmentclient with eas build.
Install the development client
Open Update in expo.dev
Click Preview
Update the App Scheme to your development clients exposcheme
Scan the QR code

this is where the issue occurs for me.  When the dev client opens, it gives me the error above in the description.

**Comment by brentvatne** [comment]
related: ENG-6508

**Comment by jonsamp** [comment]
I just merged a PR that fixes that UI and displays the correct URLs. Thanks for reporting this!
