### ISSUE TITLE
Expo av plays audio only from earpiece instead of speaker

### ISSUE THREAD

**Issue by ShumGG** [expo/expo#19298]
### Summary

Playing video or audio but the sound only comes out from earpiece and not from speaker in ios

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.6.0 - /opt/homebrew/bin/npm
      Watchman: 2022.09.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 1.1.1
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

    Audio.setAudioModeAsync({
            allowsRecordingIOS: true,
            staysActiveInBackground: false,
            playsInSilentModeIOS: true,
            shouldDuckAndroid: true,
            interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
            playThroughEarpieceAndroid: false,
            interruptionModeIOS: 1,
            interruptionModeAndroid: 1,
            IOSAudioQuality: 127,
        });
        
        
        have this config for the audio, but same

**Comment by kauan777** [comment]
@ShumGG conseguiu resolver esse erro man?

**Comment by ShumGG** [comment]
> @ShumGG conseguiu resolver esse erro man?

Yes, was another code that crashed the app when I'm in background

**Comment by kauan777** [comment]
i'm have same problem, any idea?

`js
  useEffect(() => {
    (async () => {
      Audio.requestPermissionsAsync().then(({ granted }) => {
        if (granted) {
          Audio.setAudioModeAsync({
            allowsRecordingIOS: true,
            interruptionModeIOS: InterruptionModeIOS.DoNotMix,
            playsInSilentModeIOS: true,
            shouldDuckAndroid: true,
            interruptionModeAndroid: InterruptionModeAndroid.DoNotMix,
            playThroughEarpieceAndroid: false,
          });
        }
      });
    })();
  }, []);
`
`
    "expo-av": "~13.4.1",

`

**Comment by ShumGG** [comment]
> i'm have same problem, any idea?
> 
> `useEffect(() => { (async () => { Audio.requestPermissionsAsync().then(({ granted }) => { if (granted) { Audio.setAudioModeAsync({ allowsRecordingIOS: true, interruptionModeIOS: InterruptionModeIOS.DoNotMix, playsInSilentModeIOS: true, shouldDuckAndroid: true, interruptionModeAndroid: InterruptionModeAndroid.DoNotMix, playThroughEarpieceAndroid: false, }); } }); })(); }, []);`
> 
> ```
> "expo-av": "~13.4.1",
> ```

guess you need to add ```  staysActiveInBackground: true,``` and for ios in app.json ```"ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.yourcompany.yourappname",
      "buildNumber": "1.0.0",
      "infoPlist": {
        "UIBackgroundModes": [
          "audio"
        ]
      }
    },```
