### ISSUE TITLE
Error: Location 'file:///data/user/0/host.exp.exponent/cache/ImagePicker/21fb043a-25ce-4a15-94ec-f8900340fb0e.mp4' isn't readable

### ISSUE THREAD

**Issue by Alexp858** [expo/expo#19308]
### Summary

FileSystem.readAsStringAsync doesn't seem to work in SDK 46 anymore.

I made a new expo project with the code below to test this and got the error `Error: Location 'file:///data/user/0/host.exp.exponent/cache/ImagePicker/21fb043a-25ce-4a15-94ec-f8900340fb0e.mp4' isn't readable`. 

After this I installed expo@45, updated the depandencies to match the sdk version and ran the same code. I could read the base64 data as expected with no issue.

Is there a fix to this?

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.11.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ^45.0.8 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    Expo Workflow: managed

### Minimal reproducible example

```
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import * as ImageLibrary from "expo-image-picker";
import * as FileSystem from "expo-file-system";

export default function App() {
  const openLibrary = async () => {
    ImageLibrary.launchImageLibraryAsync({
      mediaTypes: ImageLibrary.MediaTypeOptions.All,
    }).then((image) => {
      console.log(image);
      FileSystem.readAsStringAsync(image.uri, {
        encoding: FileSystem.EncodingType.Base64,
      }).then((b) => {
        console.log(b);
      });
    });
  };
  return (
    <View style={styles.container}>
      <TouchableOpacity
        style={{
          marginBottom: 20,
        }}
        onPress={() => {
          openLibrary();
        }}
      >
        <Text>Open</Text>
      </TouchableOpacity>
      <TouchableOpacity
        onPress={() => {
          // readAsStringAsync()
        }}
      >
        <Text>Read</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

```

**Comment by Alexp858** [comment]
Seems to be working fine in a development build, but just not on Expo Go

**Comment by paulovick** [comment]
So, if it is not working on Expo Go, what is the next step to get it fixed?

**Comment by aadhavanpl** [comment]
Still facing this issue. Any solutions?
