### ISSUE TITLE
[!] Invalid `Podfile` file: `${' is not allowed as a global variable name - installing pods after detach

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#1932]
### Environment

```bash
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.2.1
  Yarn: 1.5.1
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/headsuphealth-1ba00eba-7bbf-4641-bca8-1449b4a51b28.tar.gz
```
Installing pods after detaching

### Steps to Reproduce

```
exp detach
cd ios
pod install
```

### Expected Behavior

Pods are installed

### Actual Behavior

```bash
MacBook-Pro:heads-up-health Julian$ cd ios
MacBook-Pro:ios Julian$ pod install

[!] Invalid `Podfile` file: `${' is not allowed as a global variable name
/Users/Julian/.../ios/Podfile:14: syntax error, unexpected end-of-input, expecting keyword_end.

 #  from /Users/Julian/.../ios/Podfile:14
 #  -------------------------------------------
 #      :inhibit_warnings => true
 >  ${PODFILE_UNVERSIONED_EXPO_MODULES_DEPENDENCIES}
 #
 #  -------------------------------------------
MacBook-Pro:ios Julian$
```

**Comment by JulianKingman** [comment]
It looks like putting line 14 in single quotes may have fixed it, stay tuned...

**Comment by JulianKingman** [comment]
I then got this error: https://github.com/CocoaPods/CocoaPods/issues/7740
and implemented the mentioned workaround

**Comment by terribleben** [comment]
What is the output of `exp --version` for you? I just tried the repro steps and it works for me. I have exp `55.0.4`

**Comment by JulianKingman** [comment]
Same. Does your podfile contain that line?

**Comment by terribleben** [comment]
`${PODFILE_UNVERSIONED_EXPO_MODULES_DEPENDENCIES}` is a template string which gets replaced for me. Actually, I wonder if we released something out of sync here; I just pushed a change here yesterday. I will look into this by the end of the day.

**Comment by terribleben** [comment]
Successfully reproduced the issue. I had an internal version of exp which was hiding this behavior during my test. Sorry about that.

**Comment by JulianKingman** [comment]
Thx!

**Comment by terribleben** [comment]
Can you try again? Just pushed iOS tag `2.6.8` (which should be used automatically if you run `exp detach` now).

**Comment by terribleben** [comment]
Need to run for a bit but will check back here

**Comment by JulianKingman** [comment]
It installs correctly, but now I get a bunch of RNSVG errors when I try to build. For example: `Typedef redefinition with different types ('struct RNSVGCGFloatArray' vs 'struct RNSVGCGFloatArray')`

**Comment by JulianKingman** [comment]
My bad, a clean and build fixed that issue. Problem solved, thanks!

**Comment by lichenglu** [comment]
It seems there is a recursion for `exp 55.0.5`. I am having the exact same issue. The steps to reproduce is the same mentioned above :

## Environment
```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/lichenglu-84abd732-f990-4023-a344-b618f7b6c571.tar.gz
```
## Actual Behavior
```
[!] Invalid `Podfile` file: `${' is not allowed as a global variable name
/Users/cl38824/developer/yespirit/yespirit-app/ios/Podfile:14: syntax error, unexpected end-of-input, expecting keyword_end.

 #  from /Users/cl38824/developer/yespirit/yespirit-app/ios/Podfile:14
 #  -------------------------------------------
 #      :inhibit_warnings => true
 >  ${PODFILE_UNVERSIONED_EXPO_MODULES_DEPENDENCIES}
 #
 #  -------------------------------------------
```
It was my first time trying to detach.

**Comment by anil1712** [comment]
I am also getting the same on iOS and getting `Project with path ':expoview' could not be found in project ':app'.` in Android Project. 

Did you guys find any solution?

**Comment by quinlanj** [comment]
@lichenglu the Podfile issue you are seeing is due to another (more recent) cause which should have been fixed. Let us know if this is still occurring despite upgrading exp

**Comment by hamishwebb** [comment]
@quinlanj I've updated exp, but I'm still seeing the same error. Thank you for looking into this.

**Comment by aatreya** [comment]
Still happening

**Comment by terribleben** [comment]
Sorry for the confusion everyone, can you try this?

# Use exp 56.0.0 or newer, then `exp detach` again

If you check the contents of `ios/Podfile`, it should not contain the string `${PODFILE_UNVERSIONED_EXPO_MODULES_DEPENDENCIES}`.

**Comment by paul019** [comment]
Thank you for your help!

I've two questions: When I run `npm install -g exp` and then `exp --version`, the console outputs 50.0.1, a very old version. What's the problem here? Furthermore, a second detach isn't possible for me, the console outputs the error `'ios' and 'android' directories already exist.`
