### ISSUE TITLE
Execution failed for task ':app:bundleReleaseResources'.

### ISSUE THREAD

**Issue by cankilinc** [expo/expo#19328]
### Summary

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
1271
Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
1272
Please consult deprecation warnings for more details.
1273
543 actionable tasks: 543 executed
1274
[stderr] FAILURE: Build failed with an exception.
1275
[stderr] * What went wrong:
1276
[stderr] Execution failed for task ':app:bundleReleaseResources'.
1277
[stderr] > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable
1278
[stderr]    > Android resource linking failed
1279
[stderr]      ERROR:/home/expo/workingdir/build/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml:3: AAPT: error: resource color/iconBackground (aka com.reactnavigationtutorial:color/iconBackground) not found.
1280
[stderr]          
1281
[stderr]      ERROR:/home/expo/workingdir/build/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml:3: AAPT: error: resource color/iconBackground (aka com.reactnavigationtutorial:color/iconBackground) not found.
1282
[stderr]          
1283
[stderr] * Try:
1284
[stderr] > Run with --stacktrace option to get the stack trace.
1285
[stderr] > Run with --info or --debug option to get more log output.
1286
[stderr] > Run with --scan to get full insights.
1287
[stderr] * Get more help at https://help.gradle.org
1288
[stderr] BUILD FAILED in 6m 37s
1289
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### What platform(s) does this occur on?

Android

### SDK Version

46.0.9

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.7.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      expo-cli: 6.0.1
    Expo Workflow: bare

### Minimal reproducible example

I getting error when I trying build for android

**Comment by Nurgamze** [comment]
> Task :app:bundleReleaseResources FAILED

Execution failed for task ':app:bundleReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable
   > Android resource linking failed
     C:\Users\gamzenur.demir\Desktop\hesaabim\SDSHesabimFlutter\build\app\intermediates\bundle_manifest\release\AndroidManifest.xml:53: error: not well-formed (invalid token).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

I am getting the same error. It can't be solved, what should I do?
