### ISSUE TITLE
Invariant Violation when upgrading from SDK 44 to 46

### ISSUE THREAD

**Issue by devrevo** [expo/expo#19334]
### Summary

I upgraded to SDK 46, the I did I expected my app to work normally because I made sure to upgrade node modules aswell, but I ran into this problem.
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-09-30 at 18 26 21](https://user-images.githubusercontent.com/44529694/193324314-2f78ad89-deb3-442d-a1a9-d8ca0c7a9ebe.png)
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-09-30 at 18 26 24](https://user-images.githubusercontent.com/44529694/193324320-702727af-8f2b-4e8e-bd62-5c823ca5f74b.png)

Here's my `package.json` :

`
{
  "name": "relearnsocial",
  "description": "Relearn Social",
  "author": "Maxwellconseil",
  "version": "1.0.1",
  "private": true,
  "scripts": {
    "setup": "./scripts/setup.sh",
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@astrocoders/react-native-selectable-text": "^1.5.1",
    "@babel/preset-typescript": "^7.18.6",
    "@react-native-community/blur": "^4.2.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "9.3.0",
    "@react-native-community/slider": "4.2.3",
    "api-ecommerce": "^1.0.3",
    "babel-preset-env": "^1.7.0",
    "base-64": "1.0.0",
    "body-parser": "^1.20.0",
    "consolidate": "^0.16.0",
    "crypto-js": "4.1",
    "currency-formatter": "1.5.9",
    "ejs": "^3.1.8",
    "expo": "^46.0.13",
    "expo-ads-admob": "~13.0.0",
    "expo-ads-facebook": "~11.2.0",
    "expo-app-loading": "~2.1.0",
    "expo-apple-authentication": "~4.3.0",
    "expo-asset": "~8.6.1",
    "expo-av": "~12.0.4",
    "expo-constants": "~13.2.4",
    "expo-facebook": "~12.2.0",
    "expo-file-system": "~14.1.0",
    "expo-font": "~10.2.0",
    "expo-linear-gradient": "~11.4.0",
    "expo-notifications": "~0.16.1",
    "expo-permissions": "~13.2.0",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.6",
    "expo-web-browser": "~11.0.0",
    "express": "^4.18.1",
    "firebase": "9.10.0",
    "html-entities": "2.3.3",
    "htmlparser2": "^8.0.1",
    "jetifier": "^2.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "native-base": "^3.4.17",
    "node": "^18.10.0",
    "oauth-1.0a": "^2.2.6",
    "path": "0.12.7",
    "paypal-rest-sdk": "^1.8.1",
    "prop-types": "^15.8.1",
    "radio-buttons-react-native": "^1.0.4",
    "react": "18.0.0",
    "react-instantsearch": "6.35.0",
    "react-native": "0.69.6",
    "react-native-animatable": "1.3.3",
    "react-native-app-intro-slider": "4.0.4",
    "react-native-clean-form": "0.5.0",
    "react-native-code-push": "^7.0.5",
    "react-native-collapsible": "1.6.0",
    "react-native-country-picker-modal": "2.0.0",
    "react-native-drawer": "github:luyx2412/react-native-drawer",
    "react-native-fluid-slider": "1.0.2",
    "react-native-image-zoom-viewer": "3.0.1",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-keyboard-aware-scroll-view": "0.9.5",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-masked-text": "^1.12.5",
    "react-native-measure-text": "^1.0.0-alpha.2",
    "react-native-modal": "^13.0.1",
    "react-native-modal-with-blur-support-background": "^1.0.0",
    "react-native-modalbox": "^2.0.2",
    "react-native-modals": "^0.22.3",
    "react-native-multi-select-picker": "^1.0.11",
    "react-native-multi-selectbox": "^1.5.0",
    "react-native-paper": "4.12.4",
    "react-native-parallax": "0.3.0",
    "react-native-paypal-gateway": "^1.0.0",
    "react-native-paypal-lib": "^1.0.9",
    "react-native-progress": "^5.0.0",
    "react-native-progress-circle": "^2.1.0",
    "react-native-progress-wheel": "^1.0.5",
    "react-native-radio-buttons": "1.0.0",
    "react-native-rate": "^1.2.9",
    "react-native-really-awesome-button": "^1.6.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-render-html": "^6.3.4",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-scrollable-tab-view": "1.0.0",
    "react-native-side-menu": "1.1.3",
    "react-native-sliding-modal": "^2.1.0",
    "react-native-snap-carousel": "^1.3.1",
    "react-native-spacer": "^1.7.0",
    "react-native-star-rating": "^1.0.8",
    "react-native-svg": "12.3.0",
    "react-native-swipe-list-view": "3.2.9",
    "react-native-swiper": "^1.6.0",
    "react-native-tag-select": "^2.0.0",
    "react-native-unordered-list": "^1.0.4",
    "react-native-webview": "11.23.0",
    "react-native-webview-messaging": "^2.0.0-alpha.4",
    "react-navigation": "^4.4.4",
    "react-navigation-header-buttons": "9.0.1",
    "react-navigation-props-mapper": "3.1.0",
    "react-navigation-stack": "^2.10.4",
    "react-navigation-tabs": "^2.11.2",
    "react-redux": "8.0.4",
    "react-smart-payment-buttons": "^0.2.3",
    "redux": "4.2.0",
    "redux-actions": "2.6.5",
    "redux-persist": "^6.0.0",
    "redux-thunk": "2.4.1",
    "reselect": "4.1.6",
    "sweetalert2": "^11.4.35",
    "tcomb-form-native": "0.6.20",
    "urijs": "^1.19.11",
    "url": "0.11.0",
    "url-parse": "^1.5.10",
    "util": "0.12.4",
    "uuid": "9.0.0",
    "validate.js": "0.13.1",
    "wpapi": "^1.2.2",
    "expo-splash-screen": "~0.16.2",
    "react-dom": "18.0.0",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@babel/preset-react": "^7.18.6",
    "babel-jest": "29.1.2",
    "babel-plugin-transform-remove-console": "6.9.4",
    "babel-preset-expo": "~9.2.0",
    "babel-preset-react-native": "4.0.1",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "jest": "^26.6.3",
    "reactotron-react-native": "^5.0.3",
    "reactotron-redux": "3.1.3"
  },
}

`

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.10.0 - ~/Desktop/react/new_mobile/ebookmobile_new/node_modules/.bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 2022.09.26.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 28, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2
        System Images: android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ^46.0.13 => 46.0.13 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

This is the project to reproduce the issue:  [Expo issue](https://github.com/devrevo/expo-issue.git)

**Comment by brentvatne** [comment]
hi there! be sure to follow the upgrade instructions from the changelog.

your app is using several libraries that were removed in sdk 46:
- expo-ads-admob
- expo-ads-facebook
- expo-facebook

we recommend upgrading sdk versions 1 at a time. so first to sdk 45, then 46. in sdk 45 you would see deprecation warnings about each of these packages.

changelogs:
- sdk 45:https://blog.expo.dev/expo-sdk-45-f4e332954a68
- sdk 46: https://blog.expo.dev/expo-sdk-46-c2a1655f63f7

**Comment by devrevo** [comment]
@brentvatne Thanks for the reply but m still running into some errors: you have any clue about why this happening.
![Screenshot_1664627379](https://user-images.githubusercontent.com/44529694/193409674-d3e03362-13cc-42a9-8ff6-11cbf374e19d.png)
