### ISSUE TITLE
Android compile error

### ISSUE THREAD

**Issue by dninja21** [expo/expo#1934]
### Environment

Environment:
  OS: Windows 10
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/dninja21-80a63cb2-2d1b-4968-a8ea-d03e34da7a60.tar.gz

### Steps to Reproduce

1. set android package name to `net.dninja21.8d`

### Expected Behavior

should compile the app

### Actual Behavior

error code to do with wrong android.package
[screenshot](https://i.dninja21.net/c5v48o1hZ.png)

### Reproducible Demo

just open any project and rename the android package to `net.dninja21.8d` and try and compile.

**Comment by dninja21** [comment]
Sorry, but I realized that I couldn't put numbers inside it.

**Comment by quinlanj** [comment]
hi @dninja21 , it seems like you solved your problem, so will close this issue.
