### ISSUE TITLE
[expo-av] Audio setPositionAsync does not work on iOS with long duration mp3

### ISSUE THREAD

**Issue by VahanLab** [expo/expo#19348]
### Summary

When playing a mp3 with a long duration (snack exampleprovided with a one hour online source), calling setPositionAsync returns an error (Error: Seeking interrupted.)

PlaybackStatus never returns the durationMillis and setPositionAsync only works within the playableDurationMillis range, which only refresh when the positionMillis reach its value 

Developing a Podcast app, I can't use a seek bar on iOS. Only works with shorter mp3 (like 15 minutes)

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.0.0
      expo-cli: 6.0.5
    Expo Workflow: bare
    
    Using  "expo-av": "~12.0.4",

### Minimal reproducible example

https://snack.expo.dev/@karl.gochgarian/long-audio-seek-issue?platform=ios

**Comment by byCedric** [comment]
Hi @VahanLab! Thanks for writing in and providing a repro. I slightly edited it just to get some more information from the example: https://snack.expo.dev/@bycedric/expo-issue-19348?platform=ios

To me, a couple of things stand out:
- I can repro the issue when pressing play and then pressing "seek middle"
- The `downloadAsync` is turned on, so it's downloading the whole thing
    - But I can't imagine it's ready to download the whole thing in just under a few seconds.
    - After letting it play for 20s, the `seek to middle` actually works

It looks like we either might be triggering the resolve on "loadAsync" too early, or we have a buffering issue IMHO.

Either way, thanks for the report.

**Comment by VahanLab** [comment]
Hey @byCedric anything new on that one? I experienced a few mp3 of only 5 minutes also affected with this bug. That sounds like a pretty critical bug to me for an audio player library.

**Comment by VahanLab** [comment]
Please don’t close this issue as it still occurs and probably affects lots of people.

**Comment by Sassar88** [comment]
error still exist, its very important for us, the solve this error

**Comment by RamanSB** [comment]
I am still experiencing this issue. Running setPositionAsync within the setOnPlaybackStatusUpdate event handler yields the error: {"code: "E_AV_SEEKING"})
