### ISSUE TITLE
Uncaught Error: java.security.cert.CertificateNotYetValidException: Certificate not valid until <date>

### ISSUE THREAD

**Issue by dillonforrest** [expo/expo#19346]
### Summary

My Android app doesn't boot. When I run `npx expo start` and scan the QR code with my Android device, Expo Go gives Screenshot A below.

When I press "View error log" at the bottom of Screenshot A, I get Screenshot B below, with the error:

```
Uncaught Error: java.security.cert.CertificateNotYetValidException: Certificate not valid until <date> (compared to <date 1 second earlier than previous date>)
```

The timestamps in Screenshot B are the time that I scan the QR code.

My issue is Android only -- my iOS device's Expo Go works just fine.

This issue started happening after I added `expo.extra.eas.projectId` to `app.json` to fix an `eas update` issue. It fixed updates on iOS, but Android is still broken.

Screenshot A:

![Screenshot_20220930-171333](https://user-images.githubusercontent.com/1864785/193357283-cdff03e9-5be7-4561-a9a6-a1665cb9f606.png)

Screenshot B:

![Screenshot_20220930-171414](https://user-images.githubusercontent.com/1864785/193357356-3cbc0a7f-5222-4a61-9c29-9d688b6ffdb7.png)

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.3 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

Add `expo.extra.eas.projectId` to app.json, run `npx expo start`, take your Android device with Expo Go, and scan the QR code printed by `npx expo start`. Instead of app rendering in Expo Go, Screenshot A renders instead.

**Comment by brentvatne** [comment]
@dillonforrest - we are investigating this now. you've identified one workaround (remove projectId configuration). one way you can work around this for now is to [use development builds](https://docs.expo.dev/development/introduction/), which are a great alternative to expo go

**Comment by brentvatne** [comment]
it looks like there is some clock skew occurring - you can also work around this by changing the time on your android device to a minute in the future (it looks like the skew is ~1 second from your screenshots). we're working on resolving

**Comment by brentvatne** [comment]
we've pushed a fix, this should be resolved without any workarounds needed now. let me know if the issue persists for you! thanks

**Comment by dillonforrest** [comment]
@brentvatne confirmed on my end that my issue is resolved. Thanks for the speedy reply and fix! 🙏
