### ISSUE TITLE
expo-auth-session causing "Not found" error after expo upgrade to 46.0.0 from 44.0.0

### ISSUE THREAD

**Issue by sarmadkung** [expo/expo#19356]
### Summary

Hello , I am facing issue with expo-auth-session as I updated my expo app from 44.0.0 to 46.0.0 version.
Issue: As i start web based authentication using `AuthSession.startAsync()` I am seeing this screen. before it was loading to the web authentication page.
here is code snippet

```
const authUrl = auth.url+?'returnUrl='+returnUrl;
const authResponse = await AuthSession.startAsync({ authUrl });
```

![simulator_screenshot_029C2759-1E3A-4936-86FF-3DD944B08E5C](https://user-images.githubusercontent.com/33754179/193454990-e22d8e74-7a12-4555-800c-98bcde815059.png)

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.volta/tools/image/node/16.14.0/bin/node
      Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
      npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8005941
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild

### Minimal reproducible example

```
  const returnUrl = encodeURIComponent(Linking.createURL(`landing`));
  const authUrl = `http://localhost:3000/?returnUrl=${returnUrl}`;

  const authenticate = useCallback(async () => {
    const authResponse = await AuthSession.startAsync({
      authUrl,
      projectNameForProxy: 'expo-pitetion',
    });
    return authResponse;
  }, [authUrl]);
```

**Comment by bportman** [comment]
I have the same issue.  Why was this closed?  Do you have a fix @sarmadkung ?

**Comment by bportman** [comment]
Just checked and this issue persists in Expo SDK 47.  To get around it before I had downgraded to Expo SDK 44, but now Expo Go doesn't support SDK 44 anymore.  Can anyone advise whats going on here that expo-auth-session worked in 44 and stopped working suddenly in 46 and 47?

**Comment by bportman** [comment]
@sarmadkung Do you have a fix for this?  We are now down because Expo Go updated to remove SDK 44 support.

**Comment by bportman** [comment]
OK I figured it out - the projectNameForProxy needed to be removed starting in SDK 45.  Once I removed it everything worked fine.  If any one else has this issue I suggest you try this.
