### ISSUE TITLE
Stop misusing homepage field in package.json

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [expo/expo#19353]
### Summary

After upgrading expo and expo-cli in my desktop app project the build succeeds but upon opening the app I'm greeted with a blank screen. After debugging just the front-end in Firefox, I can see that all static files 404 because they use incorrect path. Apparently the latest version of expo-cli infers asset path from `homepage` field in package.json. This took me 30 min of googling and an issue in an [unrelated repo](https://github.com/GeekyAnts/nativebase-templates/issues/44) to figure out. This change was breaking and poorly communicated, it's barely even mentioned in the changelog. I *read* every expo changelog and I still *missed* it.

However, the main issue here is this is complete misuse of a standard metadata field in a standard file. Regardless of what you think about putting configuration in package.json you should use non-standard fields for it at least. This change assumes that every expo web project is its own homepage. My case for example is a Tauri app with React-Native front end. The homepage does not relate to expo-web project at all.

It's a minor issue, but because expo is misusing metadata field I can't have complete metadata for my project in a standard location. Not to mention how annoyingly long it took to figure out.

### What platform(s) does this occur on?

Web

### SDK Version

46.0.9

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.9 => 46.0.13 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    Expo Workflow: managed

### Minimal reproducible example

Set homepage field in package.json in a fresh expo project, run `expo export:web`, see that every static asset path is prefixed with path inferred from homepage field in package.json

**Comment by EvanBacon** [comment]
Expo Webpack is a fork of Create React App and intends to use `homepage` the same way [ref](https://create-react-app.dev/docs/deployment/#building-for-relative-paths). We probably won't keep this system in Metro for web but it seems to be pretty standard for React SPAs.
