### ISSUE TITLE
expo web doc not working for netlify

### ISSUE THREAD

**Issue by jsbaguette** [expo/expo#19351]
### Summary

here the main issue https://github.com/necolas/react-native-web/issues/2402

Using expo export:web. When i deploy to netlify and follow the simple deployment. It's not working when navigate manually to a page. But working when using Link component

### What platform(s) does this occur on?

Web

### SDK Version

46.0.9

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.npm-packages/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 32.0.0, 32.1.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    Expo Workflow: managed
```

## Steps to reproduce
- Create 3 dum component
- app.js
```
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { Text } from "react-native"

import HomeScreen from './src/screens/HomeScreen.js';
import LoginScreen from './src/screens/LoginScreen.js';
import NotFoundScreen from './src/screens/NotFoundScreen.js';

const Stack = createNativeStackNavigator();

const linking = {
  config: {
    screens: {
      Login: {
        path: "login"
      },
      Home: {
        path: ""
      },
      NotFound: {
        path: "*"
      },
    }
  }
}

function App() {


  return (
    <NavigationContainer linking={linking} fallback={<Text>Loading...</Text>}>
      <Stack.Navigator initialRouteName="Login" screenOptions={{ headerShown: false }}>
        <Stack.Screen name="Login" component={LoginScreen} options={{ 
          title: "Login Page",
          gestureEnabled: false
        }} />
        <Stack.Screen name="Home" component={HomeScreen} options={{ 
          title: "Home",
          gestureEnabled: false
        }}  />
        <Stack.Screen name="NotFound" component={NotFoundScreen} />
      </Stack.Navigator>
      <StatusBar style="auto" />
    </NavigationContainer>
  );
}

export default App;
```

following https://docs.expo.dev/distribution/publishing-websites/#netlify

or if you want to have a quick look at the code

https://codesandbox.io/p/github/jsbaguette/colib-mobile/main?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A19000%252C%2522key%2522%253A%2522cl8qsga4p004g3b6o4ez40kgf%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cl8qsg7zn001z3b6omhzh1g5f%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

**Comment by jsbaguette** [comment]
Actually it worked after adding the `_redirects` file inside web-build with `/* /index.html 200`

and inside my package json 

"build:web": "expo export:web && cp _redirects web-build"

I am not closing so you can see it. 

Feel free to close it but we should probably update the doc here no ?

**Comment by byCedric** [comment]
Hi @jsbaguette! You are right. It's missing the "redirect all URLs to the app" part, which you described in your comment. Happy to review a PR related to this, or we will make the change whenever we can (no ETA though).

Thanks for flagging this!

**Comment by gabrieldonadel** [comment]
> Happy to review a PR related to this, or we will make the change whenever we can (no ETA though).

@jsbaguette and @byCedric I'm happy to help with this if that's ok
