### ISSUE TITLE
Video doesn't support http 302 redirects on Android

### ISSUE THREAD

**Issue by mikenz1000** [expo/expo#1935]
### Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/mikenz1000-25d6a4b4-b48c-45aa-bf23-23426db414e8.tar.gz

Android Samsung S8 via Expo Client

### Steps to Reproduce

Use the Video or VideoPlayer component with a uri that will get redirected using HTTP 302

### Expected Behavior

Video should play using the redirected url (in the Location header of the 302 response)

### Actual Behavior

Video component: nothing is displayed, and if you provide an onError handler you get this error: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302

VideoPlayer component: renders white text on a black background with that same error message (com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302)

### Reproducible Demo

https://snack.expo.io/@mikenz1000/video-https-redirect-test

### Additional info 

from @sjchmiela :) https://github.com/expo/expo/issues/1227#issuecomment-401386062

"It looks like the player indeed does not follow redirections when the first response code is 302 (when the protocol is HTTPS, haven't checked HTTP).

For example setting uri to https://bit.ly/2yUKnVl makes the video play (and this shortened URL redirects with 301 to the URL you're using which then uses 302 to redirect to the file). Strange! 😲"

from @mikenz1000: this _might_ be a similar issue to this one in the tracker player:
https://github.com/react-native-kit/react-native-track-player/issues/111

Thank you in advance!

**Comment by mikenz1000** [comment]
Hey guys, a going to have a look into this if you haven't had a chance - if you've any pointers let me know, thanks. (haven't worked on the expo java code before...)

**Comment by Gordensen** [comment]
Some update on this?

**Comment by michaelfaisst** [comment]
Just stumbled over the same problem. @mikenz1000 @sjchmiela any idea when there's some update on the PR?

**Comment by Gordensen** [comment]
> Just stumbled over the same problem. @mikenz1000 @sjchmiela any idea when there's some update on the PR?

@michaelfaisst I found a workaround for this... just create a simple reverse proxy that fetch the vimeo URL (the one with redirect issue) and returns the redirected URL. The redirected URL works fine

**Comment by Gordensen** [comment]
@michaelfaisst reverse proxy code
```app.get('/redirect', function (req, res) {
    let url = req.query.url;
    fetch(url)
        .then(function (fetchRes) {
            res.setHeader('Content-Type', 'application/json');
            res.json({ vimeoURL: fetchRes.url });
        })
        .catch(function (error) {
            res.send(error);
        });
});
```
and on the player component:

componentWilMount(){
    fetch('https://your-proxy-url/redirect/?url=' + this.props.videoURL)
      .then(response => response.json())
      .then((data) => {
        this.setState({ uri: data.vimeoURL });
      })
      .catch(console.error);
}

on the render method:

<VideoPlayer
            videoProps={{
              shouldPlay: true,
              resizeMode: Video.RESIZE_MODE_CONTAIN,
              source: {
                uri: this.state.uri
              },
              isMuted: false,
              ref: component => {
                this._playbackInstance = component;
              },
            }}
... />

I hope this works for you!

**Comment by mikenz1000** [comment]
Wow well as far as workarounds go, perhaps merging the PR might be the lesser of two evils.. ;)

**Comment by Gordensen** [comment]
@mikenz1000 agreed!!! But I couldn't wait for the PR to be merged and this workaround solves the issue that I was having...

**Comment by mikenz1000** [comment]
Hmm If your proxy URL is in a different region to where the video component is running, you might end up with the wrong CDN URL being consumed (ie. US proxy, app running in Europe = you will stream from US CDN edge ....) @sjchmiela or anyone from the project team, what would convince you to merge? Thanks!

**Comment by sjchmiela** [comment]
Hi all, I think I managed to fix the issue in this PR — https://github.com/expo/expo/pull/2403. If everything goes well and it passes code review, expect it to land in SDK 31! 🎉
