### ISSUE TITLE
Permissions.askAsync() returns undefined

### ISSUE THREAD

**Issue by bernardochuecos** [expo/expo#1937]
I have a react native app with the following function to set the source of an image to a picture taken from the camera:

```
import { Permissions, ImagePicker } from 'expo';

_takePic = async () => {
    const { cameraPermission } = await Permissions.askAsync(Permissions.CAMERA);
    const { cameraRollPermission } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
    console.log(cameraPermission);
    console.log(cameraRollPermission);
    if (cameraPermission === 'granted' && cameraRollPermission === 'granted') {

      let result = await ImagePicker.launchCameraAsync({
        allowsEditing: true,
        aspect: [1, 1],
      });

      console.log(result);

      if (!result.cancelled) {
        this.setState({ imageSource: result.uri });
      }
    }
  }
```
However I noticed the code inside the if statement checking if the permission was granted was not executing, so I added the console logs and for some reason the askAsync() functions are returning 'undefined' instead of 'granted' even though I accept the permissions in my phone?
Is there something wrong with my code or is anyone else having this same issue?
Running React Native 0.55,4 on android Expo

**Comment by sjchmiela** [comment]
Hi @bernardochuecos!

```js
const { cameraPermission } = permissionsCallResult;

// is equivalent to

const cameraPermission = permissionsCallResult.cameraPermission;
```

In our case, Expo's `Permissions` API resolves with an object with keys `status` and `expires` (and sometimes with more detailed permissions status). _Ergo_, `const { cameraPermission } = { status: "granted" };` will create `cameraPermissions = undefined`.

What you're probably trying to do is to destructure the result with assigning to different names. [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assigning_to_new_variable_names) you can find Mozilla documentation about it. The proper way to do this will be:

```js
const { status: cameraPermission } = await Permissions.askAsync(Permissions.CAMERA);
const { status: cameraRollPermission } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
```

I'll close the issue tentatively, but feel free to reopen it if you have any more problems with `Permissions`! 🙂

**Comment by simsketch** [comment]
I upgraded from version 29 to 32 in order to fix this issue. Just keep in mind it requires a resubmission since you have to edit your app.json file.

**Comment by simsketch** [comment]
Ok, looks like it did not fix the issue for Android, but as soon as my Apple update is approved I will know if that did the trick for iOS. Thinking of trying `navigator.geolocation` instead because I'm not particularly concerned with accuracy, speed, or uniformity...i just need it to work!

**Comment by kunalkp** [comment]
I have installed "expo-camera": "^4.0.0" as I am not using Expo SDK. How to fix this issue for a Bare RN App?
For a managed app this was fixed by updating the expo SDK to 32.0.0.

**Comment by Luckygirlllll** [comment]
Permissions.askAsync() returns undefined after giving the permission, so user gave a permission for the Location, and I'm getting status undefined in the code: 

```
 let { locationStatus } = await Permissions.askAsync(Permissions.LOCATION);
        console.log("locationStatus in askPermission ", locationStatus)
        if (locationStatus === 'granted') {
             console.log("locationStatus granted")
          }
```

`this is expo 34.0.1`

**Comment by fayasb** [comment]
I have the same issue. Any successful remedies yet?

**Comment by kundukundu** [comment]
Any solution to this?

**Comment by lukmccall** [comment]
Hi @kundukundu, please create a new issue if this bug still occurs for you ;)
