### ISSUE TITLE
Android reboot loop when adding `--no-dev` to `npx expo start`

### ISSUE THREAD

**Issue by dillonforrest** [expo/expo#19378]
### Summary

Steps to reproduce:
1. Run `npx expo start --no-dev`
2. Get Android device with Expo Go
3. Scan QR code

Expected result: Android app should run normally in Expo Go.

Actual result: Android app goes through reboot loop.

Note that when you do `npx expo start` without `--no-dev`, everything works fine. Also, iOS works fine both with and without `--no-dev`.

Screen recording here:

https://user-images.githubusercontent.com/1864785/193669154-3f193d8a-b98e-4ebb-96d2-374994818a63.mp4

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
```

### Minimal reproducible example

Run `npx expo start` and scan the QR code with an Android device. The Android device's Expo Go should load the app normally.

Now run `expo expo start --no-dev` and scan the QR code with the same Android device. The Android device's Expo Go should go through an infinite reboot loop.

**Comment by Kudo** [comment]
hi there! i tried the steps on a `yarn create expo-app -t blank@sdk-46` project, and it works for me. could you upload a minimal reproducible example to some git repositories for us to further investigate? thanks!

**Comment by Kudo** [comment]
i'm sorry we didn't help much for your problems. maybe you could try to use the command to determine whether there're any error messages:
```
adb logcat --pid=$(adb shell pidof -s host.exp.exponent)
```
