### ISSUE TITLE
TypeError: null is not an object (evaluating '_ExpoDevMenu.default.addDevMenuCallbacks')

### ISSUE THREAD

**Issue by Kivylius** [expo/expo#19373]
### Summary

I have followed the docs for adding a new menu item into the dev overlay, 

https://docs.expo.dev/development/extensions/

but getting that typeerror and a warning:

TypeError: null is not an object (evaluating '_ExpoDevMenu.default.addDevMenuCallbacks')
Cannot read properties of undefined (reading "addDevMenuCallback")

<img width="384" alt="Screen Shot 2022-10-03 at 17 24 41" src="https://user-images.githubusercontent.com/1041335/193629271-2915978d-42b9-420b-b91f-5fe7326c9bdd.png">

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

 "expo": "~46.0.9",
  "expo-dev-menu": "^1.2.1",
  "expo-status-bar": "~1.4.0",
  "native-base": "^3.4.17",
  "react": "18.0.0",
  "react-dom": "18.0.0",
  "react-native": "0.69.6",
  "react-native-safe-area-context": "4.3.1",
  "react-native-svg": "12.3.0",
  "react-native-web": "~0.18.7"

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 7.24.2 - ~/.nvm/versions/node/v14.20.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      expo-cli: 6.0.6
    Expo Workflow: managed

### Reproducible demo

```tsx
import "expo-dev-menu";
import { registerDevMenuItems } from "expo-dev-menu";

import React, { FC, useState } from "react";
import { StatusBar } from "expo-status-bar";
import { View, Text } from "react-native";

const devMenuItems = [
  {
    name: "My Custom Button",
    callback: () => console.log("Hello world!"),
  },
];

registerDevMenuItems(devMenuItems);

export const App: FC = () => {
  return (
    <View>
        <Text>Hello world</Text>
        <StatusBar style="auto" />
    </View>
  );
};

export default App;
```

### Stacktrace (if a crash is involved)

Terminal Logs:

```
WARN  No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.
iOS Bundling complete 224ms
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: null is not an object (evaluating '_ExpoDevMenu.default.addDevMenuCallbacks')
@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:119668:40
generatorResume@[native code]
asyncGeneratorStep@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25080:26
_next@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25102:29
@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25109:14
tryCallTwo@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30621:9
doResolve@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30785:25
Promise@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30644:14
@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25098:25
_registerDevMenuItems@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:119670:39
registerDevMenuItems@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:119653:39
@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:119560:41
loadModuleImplementation@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:290:14
@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:1357:48
loadModuleImplementation@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:290:14
guardedLoadModule@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:163:47
global code@http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:213273:4
 LOG  JavaScript logs will appear in your browser console
Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4 from <actual-path...>/.: 

None of these files exist:
  * debugger-ui/debuggerWorker.aca173c4(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json)
  * debugger-ui/debuggerWorker.aca173c4/index(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json)
    at ModuleResolver.resolveDependency (<actual-path...>/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (<actual-path...>/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at <actual-path...>/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (<actual-path...>/node_modules/metro/src/Server.js:1137:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._explodedSourceMapForURL (<actual-path...>/node_modules/metro/src/Server.js:1088:35)
    at async Promise.all (index 1)
    at async Server._symbolicate (<actual-path...>/node_modules/metro/src/Server.js:1039:26)
    at async Server._processRequest (<actual-path...>/node_modules/metro/src/Server.js:443:7)
```
    
    
 Browser Logs:
 
 ```
 AppEntry.bundle?platform=ios&dev=true&hot=false:23267 Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'addDevMenuCallbacks')
TypeError: Cannot read properties of undefined (reading 'addDevMenuCallbacks')
    at http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:119668:41
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25080:26)
    at _next (http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25102:11)
    at http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25109:9
    at tryCallTwo (http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30621:7)
    at doResolve (http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30785:15)
    at new Promise (http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:30644:5)
    at http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:25098:14
    at _registerDevMenuItems (http://192.168.0.80:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:119670:34)
 ```

**Comment by Kudo** [comment]
hi there! i tested your example code on a `yarn create expo-app -t blank@sdk-46` + `npx expo install expo-dev-client` project and it works for me. could you upload a minimal reproducible project to some git repositories for us to further investigate your issue? thanks!

**Comment by Kivylius** [comment]
I created a new tested example for you, following what you mentioned but still same error, here the repo,

https://github.com/Kivylius/test55

<img width="394" alt="Screen Shot 2022-10-04 at 21 59 35" src="https://user-images.githubusercontent.com/1041335/193927189-1fd2e01a-8dbe-4f8d-b79f-ff7bfd194e8a.png">

I use NPM.

**Comment by Kivylius** [comment]
maybe it doest work well with expo go.

**Comment by Kudo** [comment]
> maybe it doest work well with expo go.

yes, the expo-dev-client (or expo-dev-menu, expo-dev-launcher) is for project running with eas build or `npx expo run`. they are incompatible with expo go.

nice catch and thanks for your example. if you have further questions, please let me know. thanks!

**Comment by Kivylius** [comment]
is there a plan to add it to the expo go? or at-least give a more meaning-full error?

**Comment by Kudo** [comment]
what's your use cases for adding custom menu item to expo go? expo go is a client with a fixed preset of native modules. if you want to extend native functionalities, you should try expo-dev-client: https://docs.expo.dev/development/introduction/#from-expo-go-to-development-builds

**Comment by Kudo** [comment]
the thing is that expo-dev-menu is not in the native modules preset of expo go. expo go has a different implementation of dev menu.

in your case, i would still recommend using EAS Build to submit a preview build. you could also add `"developmentClient": true` to the preview build section, so that you could have expo-dev-client in preview builds, e.g.
in _eas.json_
```json
{
  "build": {
    "preview": {
      "developmentClient": true,
      "distribution": "internal"
    }
  }
}
```

with the preview build, you could share the app with other teammates, and they could install the app by qr code. if you don't change any native codes, they could keep using this downloaded app to load any latest js bundle. the experience is just like expo go.

expo go is an entry point for developers to start app development. if people want some extensibilities, it's definitely eas build.
