### ISSUE TITLE
WebSocket requests do not go through the proxy (iOS)

### ISSUE THREAD

**Issue by shaikhalid** [expo/expo#19386]
### Summary

http/https requests are logged in the proxy but all the websockets request go directly from the device to the websocket server rather than going through the proxy.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild

### Minimal reproducible example

How to reproduce?
1. Setup a charles / mitm proxy 
2. Add manual proxy settings to the network interface(Wifi) on an iOS device.
3. Setup a new expo project and use websockets to connect to a websocket server.
4. Install the expo application on the iOS device with the proxy settings in place(step 2).
5. Open the application and monitor the traffic on the proxy.

**Comment by shaikhalid** [comment]
@Kudo Thanks for the reply! 
So once the fix is integrated the same fix will be deployed to the expo sdk, correct?

**Comment by Kudo** [comment]
@shaikhalid depending on which react-native version includes the fix. we try to update [latest react-native versions for each sdks](https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a). once react-native includes the fix, it won't take too much time to have the fix in expo sdk.

**Comment by shaikhalid** [comment]
@Kudo Thanks for the update. I will follow up on the react native issue.

Thanks again!
