### ISSUE TITLE
Expo returns {"_h": 0, "_i": 0, "_j": null, "_k": null} instead of an Array

### ISSUE THREAD

**Issue by demosofa** [expo/expo#19381]
### Summary

when I tried to `console.log(takenImages)` which I hoped was **an array of Asset's uri** but I got this instead: `{"_h": 0, "_i": 0, "_j": null, "_k": null}` sometime `null`. After **crtl+s on vscode** for **hot reloading** my code was this `{"_h": 0, "_i": 0, "_j": [uri1, uri2], "_k": null}`

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^46.0.0 => 46.0.13
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

```javascript
import { useEffect, useState } from "react";
import { View } from "react-native";
import * as MediaLibrary from "expo-media-library";
import * as FileSystem from "expo-file-system";

export default function App() {
  const [takenImages, setTakenImages] = useState([]);
  useEffect(() => {
    const takenImageArr = async () => {
      let album = await MediaLibrary.getAlbumAsync("ImageTaken");
      if (album == null)
        album = await MediaLibrary.createAlbumAsync("ImageTaken");
      const imageFiles = await MediaLibrary.getAssetsAsync({
        album,
        mediaType: "photo",
      });
      const uriArr = imageFiles.assets.map((asset) => asset.uri);
      console.log(uriArr);
      return uriArr;
    };
    setTakenImages(takenImageArr);
  }, []);
  console.log(takenImages);
  return <View></View> 
}
```

**Comment by gabrieldonadel** [comment]
@demosofa It seems that the `takenImages` value you see is a promise. You probably want to add a `then` statement to your `takenImages` function call, or change your `useEffect` a bit to use `await`

e.g.

> ```js
>   useEffect(() => {
>     const takenImageArr = async () => {
>       let album = await MediaLibrary.getAlbumAsync("ImageTaken");
>       if (album == null)
>         album = await MediaLibrary.createAlbumAsync("ImageTaken");
>       const imageFiles = await MediaLibrary.getAssetsAsync({
>         album,
>         mediaType: "photo",
>       });
>       const uriArr = imageFiles.assets.map((asset) => asset.uri);
>       console.log(uriArr);
>       return uriArr;
>     };
>     takenImageArr().then(setTakenImages);
>   }, []); 
> ```
