### ISSUE TITLE
iOS 16 Multiple Print Bug

### ISSUE THREAD

**Issue by nathanael-rsu** [expo/expo#19399]
### Summary

I have two React Native applications that use `expo-print` for label printing (i.e. with Brother Label Printer QL-810W). I noticed recently that when I print multiple times in either application, the label printing is inconsistent. It will print perfectly correct once, and the next time it prints off-center and multiple blank labels (I only ever want one label printed at a time). The way I print is to render what I want to print in React Native, then take a screenshot of that component, and convert it to a base64 image, which is then sent to AirPrint.

I am almost certain this is an iOS 16 issue, because I haven't made any changes to one of these apps in a while, and printing was stable until recently. The issue only happens on iOS 16 devices. I tested on Android and iOS 15 and both are still stable. I also tested with multiple physical iOS 16 devices and an iOS 16 simulator. My team has tested this issue against several different printers, and we are seeing it everywhere. I am not sure whether this is an expo bug or an Apple bug, but I appreciate any help.

Here is a picture of what I am experiencing. Again -- these are the exact same images, printed one after the other to my label printer:
![IMG_4337](https://user-images.githubusercontent.com/97470828/193865926-5903fb7f-9c20-4960-95ad-09943688df50.jpeg)

### What platform(s) does this occur on?

iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.2 - /usr/local/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/username/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: 46.0.7 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Minimal reproducible example

```
const imgHtml = 
`<html>
    <head>
	    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes" />
	    <style>
		    @page {
			    margin: 0;
		    }
		    body {
			    height: 1.4in;
			    width: 3.5in;
			    margin: 0;
			    padding: 0;
			    overflow: hidden;
			    align-items: center;
			    justify-content: center;
		    }
		    img {
			    height: 100%;
			    width: 100%;
		    }
	    </style>
    </head>
    <body>
	    <img src="data:image/png;base64,${uri}" />
    </body>
</html>`;

await Print.selectPrinterAsync().then(async (printer) => {
    await Print.printAsync({
	    html: imgHtml,
	    margins: {
		    left: 0,
		    right: 0,
		    top: 0,
		    bottom: 0
	    },
	    useMarkupFormatter: true,
	    orientation: "landscape",
	    printerUrl: printer.url
    }).then(() => {
	    resolve(true);
    }).catch((err_1) => {
	    resolve(false);
    });
}).catch((err_2) => {
    resolve(false);
});
```

**Comment by mattave** [comment]
Reported by Ronni Turrisi: https://runsignup.freshdesk.com/a/tickets/1152104

I’m trying to set up label printing from the check in app using the QL-810W

> This is a test race.
> 
> Sometimes the labels print fine, other times it prints out three at a time. Any idea how we can fix this?
> 
> 
> -------
> Race ID: 138250
> Race Dashboard: https://runsignup.com/Race/OfflineCheckIn/138250
> App Identifier: Ronni
> App Version: 3.2.31
> Device: Apple iPhone 13 Pro Max - iOS 16.0
> Mode: Participant
> -------

Public Ticket URL: https://help.runsignup.com/support/tickets/public/2ba33760efd0117bf16af9a596d8744d1089ec200c358694414774427e4d9cf5

**Comment by spotsticker** [comment]
Hi Stumbled across this researching this exact same issue for our child care checkin system. All iOS <16 work perfectly and 16/16.1 exhibit this exact behavior on the 810w printers.

**Comment by alexouille** [comment]
Hi,
same problem here since IOS16 / same printer, but using react-native-print module, so maybe an IOS bug / change ?

**Comment by nathanael-rsu** [comment]
Hi @aleqsio, thanks for getting back on this issue!

1. I don't see any errors or warnings in the console. When I run from Xcode, I see `Brother\032QL-810W._ipp._tcp.local.: Release-Job successful with warning: successful-ok (successful-ok)` on both the initial print and the second messed-up print. However, on the second messed-up print, my label printer does give me an error (the lights start flashing on it and I have to power it off and on again).
2. I tested with another AirPrint compatible printer that is a normal printer (not label), and it also printed an extra page on the second print.
3. I definitely need `useMarkupFormatter` to get my labels to print correctly. So my labels didn't print right when I disabled it, but the first print still printed on one label. The second print printed over three labels. So that doesn't seem to be the issue.

**Comment by nathanael-rsu** [comment]
I will add that since I created the issue, I have tested with `expo-print` 11.1.0, 11.3.0, and 12.0.0. The issue is present on all of those versions.

**Comment by nathanael-rsu** [comment]
@aleqsio I think I have narrowed down the issue some more. It seems to be some sort of rendering issue with `selectPrinterAsync`, which I think makes sense since this is an iOS only bug.

I got the Expo repo running on my device so I could test printing there, and get my code out of the equation. If I select a printer and then tap Print HTML (Landscape), everything works well ([Expo PrintScreen.tsx](https://user-images.githubusercontent.com/97470828/205953777-165ed73f-7595-4de6-9460-bb594997c690.png)).

However, if you replace `_printHTMLAsync` in `PrintScreen.tsx` in the Expo repo with this implementation, and then tap Print HTML (Landscape), you should be able to reproduce the issue (recall, you may need to print a few times to the printer to get the issue).

```
_printHTMLAsync = async (orientation: string = Print.Orientation.portrait) => {
    try {
      const selectedPrinter = await Print.selectPrinterAsync();
      await Print.printAsync({
        html: 'Dear Friend! <b>Happy</b> Birthday, enjoy your day! 🎈',
        printerUrl: selectedPrinter && selectedPrinter.url,
        orientation,
      });
    } catch (e) {
      Alert.alert('Something went wrong: ', e.message);
    }
  };
```

@spotsticker @alexouille I am curious if this seems to be the issue for you two? Try separating `selectPrinterAsync` into a different component, saving it in state, and then passing it to `printAsync` (rather than doing both functions in the same component).

**Comment by aleqsio** [comment]
@nathanael-rsu Do you think it's a timing issue? Seems pretty weird.

I'd assume that it should make no difference if you select and immediately pass the result to printAsync, or if you save into state and then printAsync.

If this causes a difference maybe selecting puts the printer into some weird state for a few seconds during which printing causes this bug?

**Comment by nathanael-rsu** [comment]
@aleqsio It definitely seems weird, but I don't think it's a timing issue. That was my first thought as well, but I put the `printAsync` in a `setTimeout`, and it didn't change anything.

**Comment by aleqsio** [comment]
@nathanael-rsu I'm wondering if you could try updating to the version of expo-print from master to test out the fix in #20046 – this seems to be closely related to what you're seeing.

Easiest is to probably clone the expo repo or just download the `packages/expo-print` directory and install it as a local dependency using yarn.

**Comment by alexouille** [comment]
after some research I noticed that on the first print, the print queue shows a 62x100 paper size (my brother printer), and prints fine. but on the second print, it shows 'Letter' format, then printer is stucked or prints garbage.
following that, I implemented the choosePaper function out of curiosity.(https://developer.apple.com/documentation/uikit/uiprintinteractioncontrollerdelegate/1618160-printinteractioncontroller)

- (UIPrintPaper *)printInteractionController:(UIPrintInteractionController *)pic choosePaper:(NSArray *)paperList {
    CGSize pageSize = CGSizeMake(175.748031, 283.464567); // try to force my paperSize.
    NSLog(@"ChoosePaper");
    for (UIPrintPaper *p in paperList) {
        NSLog(@"paperList: %f %f", p.paperSize.width, p.paperSize.height);
    }
    return [UIPrintPaper bestPaperForPageSize:pageSize withPapersFromArray:paperList];
}

it seems to confirm that something is not going well:
on the first print I see the correct paperSize in the PaperList array, but on the next prints, the array is empty.
so, if I'm correct, on the first print, IOS gets the right paperSize from the printer (62x100 in my case), but for the others, it defaults to ouputType 'General' (Letter), which I think bugs the printer.

not 100% sure I'm right, but hope it helps. (#20046 is also about width/height).

**Comment by SiveLindmark** [comment]
We have the same problem with a pure swift app.  We have submitted a bug report to apple, see https://openradar.appspot.com/radar?id=5548908621070336

**Comment by aleqsio** [comment]
@SiveLindmark Thanks for linking the reported bug! Any luck finding any workarounds?

**Comment by aleqsio** [comment]
Btw, I think I'm going to close this issue for now as there's apparently nothing we can do on the Expo side with an iOS issue like this other than wait for a fix :/

**Comment by aleqsio** [comment]
So ultimately calling `Print.printAsync` once per each page? 
Probably the only fix we can really reasonably do is document it.

**Comment by SiveLindmark** [comment]
No workaround found.

**Comment by rwyland** [comment]
Adding onto this thread, just because this is the only place I've found active discussion of this issue (which is happening in the airprinting sdk in iOS16, not just this lib 😅)

I'm cross posting over from https://developer.apple.com/forums/thread/722211?login=true&page=1#745737022

```
Running into the same problem with pretty simple code. I tried:
- Rewriting the async printing in ObjC and Swift, same problems.
- Switching the `printItem` between a `WKWebView` and a `UIImage`, same problems.
- Overriding the delegation of `UIPrintPaper` with a custom subclass of hardcoded `paperSize` and `printableRect`, same problems.
- Using a new `UIPrinter` and `UIPrintInteractionController` every print job, same problem.
```

Nothing has been able to resolve this issue after the first successful print

**Comment by alexbeckwith** [comment]
One workaround that I was able to find with our own custom Swift implementation was caching and reusing the `UIPrinter` object from the initial print, like:

```
private func getPrinter(printerUrl: URL) -> UIPrinter {
  if #available(iOS 16.0, *) {
    self.printerCache[printerUrl] = self.printerCache[printerUrl] ?? UIPrinter(url: printerUrl)
    return self.printerCache[printerUrl]!
  } else {
    return UIPrinter(url: printerUrl)
  }
}
```
It seems like the [choosePaper](https://developer.apple.com/documentation/uikit/uiprintinteractioncontrollerdelegate/1618160-printinteractioncontroller) method might only get called for the first time you print to a given `UIPrinter`

**Comment by aleqsio** [comment]
@behenate This might interest you while you're rewriting expo-print to new expo-modules.
We might be able to use snipped @alexbeckwith shared above to fix this longstanding bug?

**Comment by behenate** [comment]
@aleqsio Sure, I'll try to implement the fix

**Comment by JacopoOrlandini** [comment]
Working also with NSMutableDictionary. 

Working on brother ql-810w
@property (nonatomic,retain) NSMutableDictionary<NSURL*,UIPrinter*> *lastPrinterUsed;

```
    UIPrinter *lCurrentPrinterObj = nil;
    if (! [self.lastPrinterUsed objectForKey:printerUrl]) {
        lCurrentPrinterObj = [UIPrinter printerWithURL:printerUrl];
        [self.lastPrinterUsed setObject:lCurrentPrinterObj forKey:printerUrl];
    } else {
        lCurrentPrinterObj = [self.lastPrinterUsed objectForKey:printerUrl];
    }
```

**Comment by ofirgor** [comment]
Hello there, I'm working on a React Native app (Expo managed workflow) and attempting to use expo-print to print a QR code with my P-Touch printer. However, the printer isn't being detected. Can someone please assist me? I'm unsure if it's a printer-related issue, (because mine is p-touch and yours is with ql series) or if it's related to the managed workflow. Thank you!

**Comment by behenate** [comment]
@ofirgor Hi, does the printer show up when you try to print from other iOS apps? For example you can try printing a webpage from Safari and see if the printer is visible. 

If not this most likely means that your printer doesn't support  Apple's `AirPrint`, in that case your only option would be to [create your own local print server that would share the printer as AirPrint compatible for testing](https://www.linuxbabe.com/ubuntu/set-up-cups-print-server-ubuntu-bonjour-ipp-samba-airprint), I used this method while testing `expo-print` with my 12 year old printer and it worked great.
