### ISSUE TITLE
Figure out how to support `skipProcessing` in Camera, but also use correct thumbnail orientation

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1939]
Context: https://github.com/expo/expo/issues/706#issuecomment-397957772

Use case: When taking a picture, people sometimes want to show a freeze of the taken image immediately. react-native-camera has something called `skipProcessing` which tries to help with this, but it has exif/orientation problems.

**Comment by yehudahkay** [comment]
@jesseruder is this going to be included with the next sdk?

**Comment by jenverstraete** [comment]
Can we get some more information about this? Why was the issue closed? Is it going to be released in a new sdk version? If so, which version and when is the scheduled release date?

**Comment by clems36** [comment]
Any update on this ?

**Comment by bbarthec** [comment]
`expo-camera` component has a parameter `skipProcessing` in `takePictureAsync` method that would result in almost immediately provided image. See [docs](https://docs.expo.io/versions/v32.0.0/sdk/camera/#arguments).

**Comment by clems36** [comment]
Thank you!
