### ISSUE TITLE
iOS standalone app shows wrong icon in Siri App Suggestions

### ISSUE THREAD

**Issue by danieljuhl** [expo/expo#194]
I recently made a CRNA app and then published to the AppStore as a standalone app (without ejecting/detaching). In otherwords, the app was build using the command: `exp build:ios`, and the binary was uploaded using Application Loader.

The icon shown under Siri App Suggestions is the Expo icon with a blueprint background instead of the actual app icon, as defined in exp.json (app.json). The blueprint icon is nowhere in my project, and all references for icons in the project is to the actual app icon. Also in iTunes Connect, I have uploaded the real icon and the binary/build file in iTunes Connect shows the real icon.

**Comment by danieljuhl** [comment]
![img_5593](https://cloud.githubusercontent.com/assets/2785418/26151286/617410a8-3b02-11e7-819a-51458671c1e4.PNG)
![img_5594](https://cloud.githubusercontent.com/assets/2785418/26151285/61742584-3b02-11e7-9f80-301ae6dfe84b.PNG)

**Comment by terribleben** [comment]
I believe this was a matter of me missing a size in our icon configuration, which I'm about to fix. But just to sanity check, can you paste the values for any icon-related keys from your exp.json (or app.json)?

**Comment by terribleben** [comment]
Closing because I believe this to be fixed in SDK 18. Let me know if you're still seeing a problem.

**Comment by danieljuhl** [comment]
@terribleben thanks, I'll make a new version of the app next week, and let you know, if there is still problems
