### ISSUE TITLE
Speech in Background Tasks fades out on device (iOS)

### ISSUE THREAD

**Issue by GeorgeBellTMH** [expo/expo#19407]
### Summary

When running Speech.speak from a background location task the audio plays fine in foreground, but fades out when app is minimized in iOS.

Audio continues to play fine in background on simulator, but doesn't work on device.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.2.0
    Expo Workflow: managed

### Minimal reproducible example

[speechtest.zip](https://github.com/expo/expo/files/9712145/speechtest.zip)

**Comment by GeorgeBellTMH** [comment]
I've linked some related items...it appears that the audio settings are not being applied to speech.speak...there are a few ideas on how it should work...but likely it needs to be configurable itself...

**Comment by GeorgeBellTMH** [comment]
Not fixed...

**Comment by alehano** [comment]
Same issue here
