### ISSUE TITLE
"write EPIPE" error in standalone build with many assets

### ISSUE THREAD

**Issue by ashah888** [expo/expo#1941]
I’m having trouble building a standalone app for both IOS and Android.

Under “running gulp task”, I see this error:

[stderr] [22:17:04] ‘ios-shell-app’ errored after 811 ms
[stderr] [22:17:04] Error: write EPIPE
[stderr] at _errnoException (util.js:992:11)
[stderr] at WriteWrap.afterWrite (net.js:864:14)

Please help.

**Comment by jimmylee** [comment]
I recommend trying to run your builds again, because we had some downtime last night.

You can visit https://expo.statuspage.io for more information.

**Comment by ashah888** [comment]
Failed with same issue. I noticed that you are helping me in the Expo forums as well. So feel free to close this issue...

For others with possibly same problem, here's the link:
https://forums.expo.io/t/build-error-ios-shell-app-errored-error-write-epipe/11174

**Comment by terribleben** [comment]
According to the [linked forum thread](https://forums.expo.io/t/build-error-ios-shell-app-errored-error-write-epipe/11174), we fixed this in our build service, and it was happening for apps with many (over 1.5k) assets. Anybody who was encountering this error-- please try again and let us know if you're still seeing problems.

I've also changed the topic of this issue to help people out who might be searching for the same problem.
