### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'gl.getProgramInfoLog(program).trim')

### ISSUE THREAD

**Issue by jack-sparroow** [expo/expo#19426]
### Summary

I am working with `expo-bare-workflow`. My app is using `expo-gl` and `three.js` for rendering animations for my app.

While developing, app works smoothly and reflects the changes smoothly, but once I navigate from one navigation stack to another one application crashes with the following error:

```bash

 ERROR  TypeError: undefined is not an object (evaluating 'gl.getProgramInfoLog(program).trim')

```

it just goes on and on and I need to reload my app to restart it. After it, it works smooth for a while and after navigating from page to page it again crashes with the same error.

Additional Info

Developing for Platform : IOS

EXPO SDK version : "~46.0.9"

expo-gl package version :  "~11.4.0"

Working with development build created using `npx eas run:ios` because my app uses some native code 

Device used for testing : Iphone 13 (IOS 16)

package.json 

```json 
{
    "main": "index.js",
    "scripts": {
      "android": "react-native run-android",
      "ios": "react-native run-ios",
      "web": "expo start --web",
      "start": "expo start --dev-client",
      "prebuild": "expo prebuild"
    },
    "dependencies": {
      "@expo-google-fonts/cinzel": "^0.2.2",
      "@expo-google-fonts/cinzel-decorative": "^0.2.2",
      "@react-native-async-storage/async-storage": "~1.17.3",
      "@react-navigation/stack": "^6.1.1",
      "axios": "^0.25.0",
      "expo": "~46.0.9",
      "expo-app-loading": "~2.1.0",
      "expo-auth-session": "~3.7.1",
      "expo-av": "~12.0.4",
      "expo-file-system": "~14.1.0",
      "expo-gl": "~11.4.0",
      "expo-random": "~12.3.0",
      "expo-splash-screen": "~0.16.2",
      "expo-status-bar": "~1.4.0",
      "expo-three": "^6.0.1",
      "expo-three-orbit-controls": "^2.0.0",
      "expo-updates": "~0.14.5",
      "gsap-rn": "^0.0.15",
      "jwt-decode": "^3.1.2",
      "moment": "^2.29.4",
      "react": "18.0.0",
      "react-dom": "18.0.0",
      "react-native": "0.69.5",
      "react-native-elements": "^3.4.2",
      "react-native-gesture-handler": "^2.6.1",
      "react-native-phone-number-input": "^2.1.0",
      "react-native-purchases": "^5.0.2",
      "react-native-reanimated": "~2.9.1",
      "react-native-safe-area-context": "^4.3.3",
      "react-native-screens": "~3.15.0",
      "react-native-vector-icons": "^9.0.0",
      "react-native-web": "~0.18.7",
      "react-native-webview": "11.23.0",
      "react-navigation": "^4.4.4",
      "react-navigation-stack": "^2.10.4",
      "react-navigation-tabs": "^2.11.2",
      "three": "^0.127.0"
    },
    "devDependencies": {
      "@babel/core": "^7.18.6"
    },
    "private": true,
    "name": "Sample App",
    "version": "1.0.0"
  }
  

```

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

 "@expo-google-fonts/cinzel": "^0.2.2",
      "@expo-google-fonts/cinzel-decorative": "^0.2.2",
      "@react-native-async-storage/async-storage": "~1.17.3",
      "@react-navigation/stack": "^6.1.1",
      "axios": "^0.25.0",
      "expo": "~46.0.9",
      "expo-app-loading": "~2.1.0",
      "expo-auth-session": "~3.7.1",
      "expo-av": "~12.0.4",
      "expo-file-system": "~14.1.0",
      "expo-gl": "~11.4.0",
      "expo-random": "~12.3.0",
      "expo-splash-screen": "~0.16.2",
      "expo-status-bar": "~1.4.0",
      "expo-three": "^6.0.1",
      "expo-three-orbit-controls": "^2.0.0",
      "expo-updates": "~0.14.5",
      "gsap-rn": "^0.0.15",
      "jwt-decode": "^3.1.2",
      "moment": "^2.29.4",
      "react": "18.0.0",
      "react-dom": "18.0.0",
      "react-native": "0.69.5",
      "react-native-elements": "^3.4.2",
      "react-native-gesture-handler": "^2.6.1",
      "react-native-phone-number-input": "^2.1.0",
      "react-native-purchases": "^5.0.2",
      "react-native-reanimated": "~2.9.1",
      "react-native-safe-area-context": "^4.3.3",
      "react-native-screens": "~3.15.0",
      "react-native-vector-icons": "^9.0.0",
      "react-native-web": "~0.18.7",
      "react-native-webview": "11.23.0",
      "react-navigation": "^4.4.4",
      "react-navigation-stack": "^2.10.4",
      "react-navigation-tabs": "^2.11.2",
      "three": "^0.127.0"

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.06.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.1
    Expo Workflow: bare

### Reproducible demo

// create screens and instantiate expo-gl 
const switchNavigator = createSwitchNavigator({
    ResolveAuth: ResolveAuthScreen,
    loginFlow: createStackNavigator({
      SignUp: SignUpScreen,
  
      SignIn: SignInScreen,
  
      VerifyEmailAndPhone: VerifyEmailAndPhoneScreen,
      
    },{
      // initialRouteName: "Home",
      defaultNavigationOptions: {
        // title: "Home",
        headerShown: false,
  
        presentation: "modal",
  
        detachPreviousScreen: true,
  
        cardShadowEnabled: true,
        animationEnabled: true,
        animationTypeForReplace: "pop",
  
        cardStyle: {
          backgroundColor: "#000000",
          // backgroundColor: "#ffffff",
        },
        cardStyleInterpolator: forFade,
        // headerTintColor: "#999999",
        // headerStyle: {
        //   backgroundColor: "#000",
        // },
      },
  
      navigationOptions: {
        // tabBarLabel: "Home!",
        cardStyle: {
          backgroundColor: "#000000",
          // backgroundColor: "#ffffff",
        },
      },
    }),
  
    mainFlow: createStackNavigator(
      {
        Home: HomeScreen,
      },
      {
        // initialRouteName: "Home",
        defaultNavigationOptions: {
          // title: "Home",
          headerShown: false,
  
          presentation: "modal",
  
          detachPreviousScreen: true,
  
          cardShadowEnabled: true,
          animationEnabled: true,
          animationTypeForReplace: "pop",
  
          cardStyle: {
            backgroundColor: "#000000",
            // backgroundColor: "#ffffff",
          },
          cardStyleInterpolator: forFade,
          // headerTintColor: "#999999",
          // headerStyle: {
          //   backgroundColor: "#000",
          // },
        },
  
        navigationOptions: {
          // tabBarLabel: "Home!",
          cardStyle: {
            backgroundColor: "#000000",
            // backgroundColor: "#ffffff",
          },
        },
      }
    ),
  
    // subsctiption navigator
    subscriptionFlow: createStackNavigator({
      SubscriptionsScreenSeparate: SubscriptionScreen,
    },{
      defaultNavigationOptions: {
        headerShown: false,
        presentation: "modal",
        detachPreviousScreen: true,
        cardShadowEnabled: true,
        animationEnabled: true,
        animationTypeForReplace: "pop",
        cardStyle: {
          backgroundColor: "#000000",
        },
        cardStyleInterpolator: forFade,
      },
      navigationOptions: {
        cardStyle: {
          backgroundColor: "#000000",
        },
      },
    }),
  });

**Comment by skarm61** [comment]
@jack-sparroow Hello! Did you manage to solve this issue? We have similar
