### ISSUE TITLE
Android app icon appears, but when I press it nothing happens

### ISSUE THREAD

**Issue by FaizalMalik** [expo/expo#1942]
I have followed this link to run my Android app in my Device ( #1858 ) -

This is i followed ---> "The correct way to start the project is to run exp start and then open the project in Android Studio and run it (or, if you prefer, run cd android/ && ./gradlew installDevDebug in another terminal window." 

**************************************************

It run successfully without error , but My application is not launching on phone , only i can see an application icon - but when i press that nothing happens.
**************************************************************************************

My device and mac running on same network, and i tried with expo xde and cli

Expo xde - Version 2.24.4 (2.24.4.53441)
Android Studio - 3.1.2
Exp - Version 55.0.4

**************************************************************************************

*Output

[14:24:05] Starting Metro Bundler on port 19001.
[14:24:05] Metro Bundler ready.
[14:24:10] Successfully ran adb reverse. Localhost urls should work on the connected Android device.
[14:24:14] Tunnel ready.
[14:24:14] Expo is ready.

[14:24:16] Your URL is: expffb2f6fd364b4c4c936bae228182b5d3://9e-nq4.faizalmalik.champagne.exp.direct:80
[14:24:16] Logs for your project will appear below. Press Ctrl+C to exit.

Installed on 1 device.

BUILD SUCCESSFUL

Total time: 1 mins 1.201 secs

**Comment by jesseruder** [comment]
> only i can see an application icon - but when i press that nothing happens.

Can you upload a video of this? Also can you run `adb logcat` while trying to open the app and upload those logs?

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
