### ISSUE TITLE
EAS Build Internal ERR! code 500

### ISSUE THREAD

**Issue by tthongprasert** [expo/expo#19429]
### Summary

Hi Expo support team,

I ran EAS build `eas build -p ios --profile development --clear-cache`
It has been working but I just got the build failed with the error `ERR! 500 Internal Server Error - GET http://10.254.24.9:4873/npm - unknown error`

![Screen Shot 2565-10-06 at 18 20 44](https://user-images.githubusercontent.com/22360401/194300904-f71636b3-49cb-474f-8439-c50ce49b00fe.png)

Not sure that is it from the Expo server?

Thanks in Advance

### SDK Version

46

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.20.0 - ~/Manao/sp8ces-app/sp8ces/node_modules/.bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v12.22.9/bin/yarn
      npm: 6.14.17 - ~/Manao/sp8ces-app/sp8ces/node_modules/.bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 30, 32
        Build Tools: 32.0.0, 32.1.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: 46.0.10 => 46.0.10 
      react: 17.0.1 => 17.0.1 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.68.2 => 0.68.2 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: managed

### Minimal reproducible example

I installed `expo-build-properties` before getting the issue. Is it related or not?

**Comment by Simek** [comment]
Hello @tthongprasert,

this repository issues are reserved for the bug reports with Expo, Expo CLI and related packages, not EAS services. The support for EAS can be found here:
* https://expo.dev/support

Saying that, the error looks like not related to the mentioned package. This might be a result of current services status, which you can see here:
* https://status.expo.dev/

I would try to retry the build in the near future, and if it still fails, probably you should contact the support.
