### ISSUE TITLE
downloadAsync on IOS throw error "File 'file://...' isn't writable."

### ISSUE THREAD

**Issue by superyarik** [expo/expo#1943]
### Environment
Environment:
  OS: Linux 4.13
  Node: 7.7.1
  Yarn: 1.7.0
  npm: 4.1.2
  Watchman: 4.7.0
 
Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz => 0.55.2

Device:
  iphone 5s, IOS 9

### Steps to Reproduce

code: 

try {
  FileSystem.downloadAsync(url, fileName);
} catch(e) {
  console.log(error.message);
}

output: File 'file://.........png' isn't writable.
permissions to CAMERA and CAMERA_ROLL granted.
It reproduce only on IOS on file size 200kb, file size 8kb on IOS work fine.

How can i correct handle this problem?

**Comment by jesseruder** [comment]
Hi! Can you please make a Snack that reproduces this bug? The code snippet you posted doesn't really give enough information.

**Comment by cruzach** [comment]
Hi! We're closing inactive issues that apply to SDK versions we no longer support. I tested `downloadAsync` on SDK 35, and didn't have any trouble. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
