### ISSUE TITLE
ExpoAuthSession returns response null on android but works fine on ios

### ISSUE THREAD

**Issue by raphaelobinna** [expo/expo#19445]
### Summary

Using expo-auth-session for google login works fine on ios in development, returns the token as response but trying on android gives response of null and no other response.On clicking `promptAsync()` It just opens the google page for choosing an account then after choosing it redirects me back to the app and nothing happens with response as null.
- I have tried using makeRedirectUri()
- I have changed my app scheme to match both ios bundleIdentifier and android package name. 

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.14 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      expo-cli: 6.0.1
    Expo Workflow: managed

### Minimal reproducible example

Just like the documentation

`  const [request, response, promptAsync] = Google.useAuthRequest({`
`expoClientId: "xxxx.apps.googleusercontent.com",`
`  androidClientId: "xxx.apps.googleusercontent.com"`
`})`
`console.log("RESP", response)`

**Comment by bobbyaxe61** [comment]
This is error is resolved by removing and adding back all the required scopes on your google console. https://console.cloud.google.com/apis/credentials/consent?project=your-project-name

Step 1:
<img width="1201" alt="Screenshot 2022-10-12 at 14 38 38" src="https://user-images.githubusercontent.com/48505272/195359671-b1263c88-7da0-4f26-9fcf-f38cc2bbbd30.png">

Step 2:
<img width="1171" alt="Screenshot 2022-10-12 at 14 41 05" src="https://user-images.githubusercontent.com/48505272/195359707-51fa8ff3-b5d1-4e89-84cf-843734bc2b97.png">

**Comment by MrVico** [comment]
I'm having the same issue.

Basically when defining `useAuthRequest` like this

``` 
  const [request, fullResult, googlePromptAsync] = Google.useAuthRequest({
    androidClientId: "android-client-id"
  });
```

And then calling it like this

```
const response = await googlePromptAsync();

console.log(response) // This has type === success but authentication === null
console.log(fullResult) // This is just straight up null
```

That `response` has the `success` type but its `authentication` field is still `null`...
After a lot of searching around I realised that the `fullResult` of the initial definition has the data I'm looking for but there's no way to access it because right after the call it still has the value `null` and when trying to use an `useEffect` as follows it only gets triggered at the start and not once the `fullResult` is actually set

```
  useEffect(() => {
    console.log(fullResult);
  }, [fullResult]);
```

The way I managed to know that the `fullResult` is set with the expected data is by doing a manual reload of my app by editing a file and saving it because it triggers the `useEffect`

Any help would be greatly appreciated as I've been stuck with this for quick some time now 😞

**Comment by raphaelobinna** [comment]
> I'm having the same issue.
> 
> Basically when defining `useAuthRequest` like this
> 
> ```
>   const [request, fullResult, googlePromptAsync] = Google.useAuthRequest({
>     androidClientId: "android-client-id"
>   });
> ```
> 
> And then calling it like this
> 
> ```
> const response = await googlePromptAsync();
> 
> console.log(response) // This has type === success but authentication === null
> console.log(fullResult) // This is just straight up null
> ```
> 
> That `response` has the `success` type but its `authentication` field is still `null`... After a lot of searching around I realised that the `fullResult` of the initial definition has the data I'm looking for but there's no way to access it because right after the call it still has the value `null` and when trying to use an `useEffect` as follows it only gets triggered at the start and not once the `fullResult` is actually set
> 
> ```
>   useEffect(() => {
>     console.log(fullResult);
>   }, [fullResult]);
> ```
> 
> The way I managed to know that the `fullResult` is set with the expected data is by doing a manual reload of my app by editing a file and saving it because it triggers the `useEffect`
> 
> Any help would be greatly appreciated as I've been stuck with this for quick some time now 😞
> 
> PS: In the meantime I use a workaround of manually refreshing the component by having a 0.5 second timeout which then sets a `useState` variable to force the refresh but this is veryyyyyy far from ideal!

Thank you for your response of how you got around this , it helped me find a solution to my issue. Hopefully it does the same for you too.
From your response I figured you were actually doing 

`const response = await promptAsync`

The response I was actually looking for was contained there and not in the response here : 

`const [request, response, promptAsync] = Google.useAuthRequest({....})`

so I modified my button function call and it actually worked for me : 

`const onLogin = async () => {
    const response = await promptAsync();

    if (response?.type === "error") {
      dispatch(
        setActivityNotificationAction({
          type: "danger",
          message: "An error occurred",
        })
      );
      return;
    }
    !isEmpty(response) && getUserDetails(response.authentication);
  };

  const getUserDetails = async (token) => {
    const user = await axios.get(
      `https://www.googleapis.com/oauth2/v1/userinfo?access_token=${token.accessToken}`
    );

    onSignIn({
      idToken: token,
      ...user.data,
    });
  };`

**Comment by MrVico** [comment]
Actually I managed to solve it in a clean way by doing

```
await googlePromptAsync().then(response => ...)
```

instead of

```
const response = await googlePromptAsync();
```

I thought that the two ways were doing the same thing but I get the response `type` of `success` in both cases but the `authentication` object is only set in the first case!

Is the `response` not supposed to be the same in those two blocks of code? Am I really that bad at programming? 😞

**Comment by mosesegboh** [comment]
> > I'm having the same issue.
> > Basically when defining `useAuthRequest` like this
> > ```
> >   const [request, fullResult, googlePromptAsync] = Google.useAuthRequest({
> >     androidClientId: "android-client-id"
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then calling it like this
> > ```
> > const response = await googlePromptAsync();
> > 
> > console.log(response) // This has type === success but authentication === null
> > console.log(fullResult) // This is just straight up null
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That `response` has the `success` type but its `authentication` field is still `null`... After a lot of searching around I realised that the `fullResult` of the initial definition has the data I'm looking for but there's no way to access it because right after the call it still has the value `null` and when trying to use an `useEffect` as follows it only gets triggered at the start and not once the `fullResult` is actually set
> > ```
> >   useEffect(() => {
> >     console.log(fullResult);
> >   }, [fullResult]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The way I managed to know that the `fullResult` is set with the expected data is by doing a manual reload of my app by editing a file and saving it because it triggers the `useEffect`
> > Any help would be greatly appreciated as I've been stuck with this for quick some time now disappointed
> > PS: In the meantime I use a workaround of manually refreshing the component by having a 0.5 second timeout which then sets a `useState` variable to force the refresh but this is veryyyyyy far from ideal!
> 
> Thank you for your response of how you got around this , it helped me find a solution to my issue on android expo but not when I build apk. From your response I figured you were actually doing
> 
> `const response = await promptAsync`
> 
> The response I was actually looking for was contained there and not in the response here :
> 
> `const [request, response, promptAsync] = Google.useAuthRequest({....})`
> 
> so I modified my button function call and it actually worked for me :
> 
> ```
> const onLogin = async () => {
>     const response = await promptAsync();
> 
>     if (response?.type === "error") {
>       dispatch(
>         setActivityNotificationAction({
>           type: "danger",
>           message: "An error occurred",
>         })
>       );
>       return;
>     }
> 
>     !isEmpty(response) && getUserDetails(response.authentication);
>   };
> 
> 
>   const getUserDetails = async (token) => {
>     const user = await axios.get(
>       `https://www.googleapis.com/oauth2/v1/userinfo?access_token=${token.accessToken}`
>     );
>     onSignIn({
>       idToken: token,
>       ...user.data,
>     });
>   };
> ```

Hello Raphaelobinna, can I please contact you regarding your solution, I am currently facing thesame issue. I await your response. Warm Regards.

**Comment by raphaelobinna** [comment]
> > > I'm having the same issue.
> > > Basically when defining `useAuthRequest` like this
> > > ```
> > >   const [request, fullResult, googlePromptAsync] = Google.useAuthRequest({
> > >     androidClientId: "android-client-id"
> > >   });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And then calling it like this
> > > ```
> > > const response = await googlePromptAsync();
> > > 
> > > console.log(response) // This has type === success but authentication === null
> > > console.log(fullResult) // This is just straight up null
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That `response` has the `success` type but its `authentication` field is still `null`... After a lot of searching around I realised that the `fullResult` of the initial definition has the data I'm looking for but there's no way to access it because right after the call it still has the value `null` and when trying to use an `useEffect` as follows it only gets triggered at the start and not once the `fullResult` is actually set
> > > ```
> > >   useEffect(() => {
> > >     console.log(fullResult);
> > >   }, [fullResult]);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The way I managed to know that the `fullResult` is set with the expected data is by doing a manual reload of my app by editing a file and saving it because it triggers the `useEffect`
> > > Any help would be greatly appreciated as I've been stuck with this for quick some time now disappointed
> > > PS: In the meantime I use a workaround of manually refreshing the component by having a 0.5 second timeout which then sets a `useState` variable to force the refresh but this is veryyyyyy far from ideal!
> > 
> > 
> > Thank you for your response of how you got around this , it helped me find a solution to my issue on android expo but not when I build apk. From your response I figured you were actually doing
> > `const response = await promptAsync`
> > The response I was actually looking for was contained there and not in the response here :
> > `const [request, response, promptAsync] = Google.useAuthRequest({....})`
> > so I modified my button function call and it actually worked for me :
> > ```
> > const onLogin = async () => {
> >     const response = await promptAsync();
> > 
> >     if (response?.type === "error") {
> >       dispatch(
> >         setActivityNotificationAction({
> >           type: "danger",
> >           message: "An error occurred",
> >         })
> >       );
> >       return;
> >     }
> > 
> >     !isEmpty(response) && getUserDetails(response.authentication);
> >   };
> > 
> > 
> >   const getUserDetails = async (token) => {
> >     const user = await axios.get(
> >       `https://www.googleapis.com/oauth2/v1/userinfo?access_token=${token.accessToken}`
> >     );
> >     onSignIn({
> >       idToken: token,
> >       ...user.data,
> >     });
> >   };
> > ```
> 
> Hello @raphaelobinna, can I please contact you regarding your solution, I am currently facing thesame issue. I await your response. Warm Regards.

Yeah Please you can email me, sorry for the late reply

**Comment by Rolando-Barbella** [comment]
I'm having this issue with android, no matter what I tried, it comes as null

**Comment by useEffects** [comment]
You dont need a `useEffect` have a callback function on `promptAsync` as
```ts
promptAsync()
      .then((response) => {
        if (response?.type === 'success') {
```

**Comment by mickamy** [comment]
try this

```
import { getDeeplinkScheme } from "@/constants/deeplink";
import { getGoogleConfig } from "@/constants/google";
import { useFirebaseAuth } from "@/hooks/useFirebaseAuth";
import { auth } from "@/libs/firebase";
import {
  type AuthSessionResult,
  exchangeCodeAsync,
  makeRedirectUri,
} from "expo-auth-session";
import { useAuthRequest } from "expo-auth-session/providers/google";
import { maybeCompleteAuthSession } from "expo-web-browser";
import { GoogleAuthProvider, signInWithCredential } from "firebase/auth";
import { useCallback, useEffect } from "react";
import { Platform } from "react-native";

const discovery = {
  authorizationEndpoint: "https://accounts.google.com/o/oauth2/v2/auth",
  tokenEndpoint: "https://oauth2.googleapis.com/token",
  revocationEndpoint: "https://oauth2.googleapis.com/revoke",
};

maybeCompleteAuthSession();

export function useGoogleAuth() {
  const redirectUri = makeRedirectUri({ scheme: getDeeplinkScheme() });
  const config = getGoogleConfig();

  const [request, response, promptAsync] = useAuthRequest({
    androidClientId: config.androidClientID,
    iosClientId: config.iosClientID,
    webClientId: config.webClientID,
    selectAccount: true,
    redirectUri,
  });

  const { user, error, loading, setUser, setError, setLoading, logout } =
    useFirebaseAuth();

  useEffect(() => {
    if (response?.type === "success") {
      const idToken = response.authentication?.idToken;
      if (!idToken) {
        setError(new Error("missing idToken in response"));
        return;
      }

      setLoading(true);
      const credential = GoogleAuthProvider.credential(idToken);
      signInWithCredential(auth, credential)
        .then((userCredential) => {
          setUser(userCredential.user);
          setError(null);
        })
        .catch((e) => setError(e))
        .finally(() => setLoading(false));
    } else if (response?.type === "error") {
      setError(
        new Error("failed to sign in with Google", { cause: response.error }),
      );
    }
  }, [response, setError, setLoading, setUser]);

  const setPromptResult = useCallback(
    async (response: AuthSessionResult) => {
      if (Platform.OS !== "android")
        throw new Error("setPromptResult is only allowed on android");

      if (response?.type === "success") {
        if (!request?.codeVerifier)
          throw new Error("codeVerifier is undefined");

        const code = response.params.code;
        exchangeCodeAsync(
          {
            code,
            redirectUri,
            clientId: config.androidClientID,
            extraParams: { code_verifier: request?.codeVerifier },
          },
          discovery,
        )
          .then(({ idToken }) => {
            if (!idToken) {
              setError(new Error("missing idToken in response"));
              return;
            }

            setLoading(true);
            const credential = GoogleAuthProvider.credential(idToken);
            return signInWithCredential(auth, credential);
          })
          .then((userCredential) => {
            if (!userCredential)
              return setError(
                new Error("failed to sign in with Google", { cause: response }),
              );
            setUser(userCredential.user);
            setError(null);
          })
          .catch((e) => setError(e))
          .finally(() => setLoading(false));
      } else if (response?.type === "error") {
        setError(
          new Error("failed to sign in with Google", { cause: response.error }),
        );
      }
    },
    [config, redirectUri, request?.codeVerifier, setError, setLoading, setUser],
  );

  return {
    promptAsync,
    setPromptResult,
    request,
    user,
    error,
    logout,
    loading,
  };
}

```
