### ISSUE TITLE
Get base64 encoding for recorded audio/video file

### ISSUE THREAD

**Issue by AakashRainaClairvoyant** [expo/expo#1945]
Hello, 

I want to get the base64 encoding for the audio/video I recorded, however, I'm not able to do so using expo. I have to store the audio/video on S3(we are using aws mobile hub for backend along with aws amplify). We also tried storing the blob on S3 but it doesn't seem to work. I have been able to store the audio/video file on the device using the media library API. Is there any way I could get the base64 encoding for the audio/video file?
NOTE: I have also tried using react-native-fetch-blob but it uses linking which is not supported by the expo.

**Comment by jesseruder** [comment]
Hi @AakashRainaClairvoyant! Right now there isn't a way to get base64 of audio. Sorry about that. Could you post a feature request here: https://expo.canny.io/feature-requests?
