### ISSUE TITLE
[image-picker][ios] Delay in lib response time when using prop `allowsMultipleSelection`

### ISSUE THREAD

**Issue by GleidsonDaniel** [expo/expo#19463]
### Summary

When selecting an image and a video using the property allowsMultipleSelection the response time is very high. (Between 10-15 seconds.)
Selecting only the video has no problems, it goes to the editing screen.
Only images also does not occur the problem.
Only if you select an image and a video using the option allowsMultipleSelection on iOS.

### What platform(s) does this occur on?

iOS

### Environment

  ```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.1 - ~/.nvm/versions/node/v14.20.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
      Watchman: 2022.09.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.9 => 46.0.9
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.1 => 17.0.1
      react-native: RocketChat/react-native#0.68.2 => 0.68.2
    Expo Workflow: bare
   ```

### Minimal reproducible example

```
const result = await ImagePicker.launchImageLibraryAsync({
   mediaTypes: ImagePicker.MediaTypeOptions.All,
   quality: 1,
   allowsMultipleSelection: true
});
```
		
Just use this function in any app and you will be able to reproduce the error.

**Comment by GleidsonDaniel** [comment]
You can see an example in this PR comment:
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4458#pullrequestreview-1131464778

**Comment by GleidsonDaniel** [comment]
Still a issue on version 14.0.2.
These fix: https://github.com/expo/expo/pull/20034 don't solve the problem

**Comment by drewbietron** [comment]
> Still a issue on version 14.0.2.
> 
> These fix: https://github.com/expo/expo/pull/20034 don't solve the problem.

This is happening for me as well. Seems to really depend on the overall size of all of the chosen assets. Eg if I choose a few, longer videos, it can take 30+ seconds to return back the array of results. 

It would be nice if there were a state returned by the image picker that indicated that something is at least happening with the chosen selection. Right now it feels like nothing is happening with your choices, and if you try to open the image picker again it either doesn't open or is very delayed.

**Comment by erikostling** [comment]
I was wondering if it's the base 64 encoding that takes time? Either way it'd be great with some events to track user selection and progress.

**Comment by pfcodes** [comment]
setting

```preferredAssetRepresentationMode:  ImagePicker.UIImagePickerPreferredAssetRepresentationMode.Current``` fixed this for me

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I'm closing this because the solution is available and mentioned above.
Thank you 🙂
