### ISSUE TITLE
Issue renaming existing expo application

### ISSUE THREAD

**Issue by ssrballin** [expo/expo#1946]
Hi expo!

I need to rename my application, but I'm having trouble starting a build after changing the application name _(expo.name)_ in `app.json`. I think exp starts searching the expo servers for my application with its new name, but I would still like to associate the app with the old named project.

Is there any way (even hackily if this is not supported) where I can change my application name but still associate it with my existing expo application under the old name?

Thanks!

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0
```

### Steps to Reproduce

1. Change `expo.name` in `app.json`
2. `exp build:ios --release-channel production`

### Expected Behavior

Begins the build process for iOS.

### Actual Behavior

Output: `No currently active or previous builds for this project`

**Comment by jimmylee** [comment]
Have you tried publishing the project first?

**Comment by ssrballin** [comment]
@jimmylee: The project has already been published under the old name. It’s identified as a different project now because I changed the name, but I need to associate it with the already published project.

**Comment by jesseruder** [comment]
Hey @ssrballin, I'm pretty confused about why this is happening. Can you post a screenshot of the full output of `exp build:ios`? Changing the name should be fine, the `slug` field is what really matters.

**Comment by ssrballin** [comment]
I had actually changed the slug too, since I didn't know that was what was used to identify the project. Changing the slug back to the original name helped resolve the issue.

Thanks! :-)

**Comment by sreubenstone** [comment]
this saved me @ssrballin
