### ISSUE TITLE
[docs] [admob] Add deprecation warning to expo-ads-admob page

### ISSUE THREAD

**Issue by kylona** [expo/expo#19466]
### Summary

I was caught a little off guard when I tried to install expo-ads-admob and found that the Expo-Go app no longer supports it. My understanding is that expo now recommends the react-native-google-mobile-ads package instead.

A deprecation warning at the top of the documentation page would be helpful. 

### Link to the related docs page

https://docs.expo.dev/versions/v43.0.0/sdk/admob/

**Comment by raajnadar** [comment]
It is added in https://docs.expo.dev/versions/v45.0.0/sdk/admob/ in 46 it is removed, I migrated to the react-native-google-mobile-ads package and it works well with expo go

**Comment by kylona** [comment]
Looks great. Thanks for putting it together.
