### ISSUE TITLE
expo-updates causes the app crashed on Android EAS build SDK 46

### ISSUE THREAD

**Issue by baochungit** [expo/expo#19465]
### Summary

I'd just upgraded my app from SDK 45 to 46 and realized that the expo-updates caused the app (built by eas) crashed immediately. Removing everything related to expo-updates would make the app work again.

(Just checked with Android app)

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0
      expo: ^46.0.0 => 46.0.14
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

N/A

**Comment by douglowder** [comment]
Please provide a repo with the SDK 45 app that breaks when upgraded, and we will take a look.
