### ISSUE TITLE
Unable to run eas build:configure

### ISSUE THREAD

**Issue by Ugonz86** [expo/expo#19476]
### Summary

Error: /Users/uriel/.nvm/versions/node/v12.19.0/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:52
            delete this.globalFlags?.json;

I cant fond that file and cant run eas login either. Says login incorrect but I was able to login on the website just fine. 

Any help will be greatly appreciated.

### SDK Version

46.0.9

### Environment

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'expo-env-info@1.0.5',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.19.0', npm: '8.17.0' }
npm WARN EBADENGINE }
(node:50507) ExperimentalWarning: The ESM module loader is experimental.

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.17.0 - ~/.nvm/versions/node/v12.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.14 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      eas-cli: 2.2.1
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

{
  "name": "appName",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "9.3.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.1",
    "aws-amplify": "^4.3.36",
    "aws-amplify-react-native": "^6.0.5",
    "eas-cli": "^2.2.1",
    "expo": "~46.0.9",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.6",
    "react": "18.0.0",
    "react-hook-form": "^7.36.1",
    "react-native": "0.69.5",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6"
  },
  "private": true
}

**Comment by Kudo** [comment]
hi there! could you try to re-install eas-cli?
```
$ npm install -g eas-cli@latest
```

and the nodejs from your machine is outdated. you could also try to upgrade the node.js version. thanks!
