### ISSUE TITLE
Camera focus not working properly on iOS

### ISSUE THREAD

**Issue by Jeppeer** [expo/expo#19472]
### Summary

When using `expo-camera`, I experience that the camera is not able to focus on things closer than approx. 16-19 cm. I have tried this on iPhone 13 pro and 14 pro, and face the same problem on both. It is no problem focusing on the same thing using the built in camera apps.

I have tried with and without `AutoFocus.on`. The focus seems to be working properly on everything further away, and the camera is continually focusing automatically (allthough a bit slow?). I have also tried to use `expo-barcode-scanner`, but i have the same problem there.

I use the camera for scanning barcodes, and therefore need to be able to focus on things that are close to the phone.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

```
<Camera
   onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
   style={StyleSheet.absoluteFillObject}
   autoFocus={AutoFocus.on}
/>
```

**Comment by byudaniel** [comment]
I researched this issue a bit and found a workaround of sorts. In brief, the [iPhone 14 Pro's camera has a farther minimum focus distance](https://www.forbes.com/sites/paulmonckton/2022/09/27/newly-revealed-iphone-14-pro-specs-confirm-surprise-camera-downgrade/?sh=b48e78508179), which means close barcodes will not scan well. I "fixed" it by applying a zoom factor of 0.015:
`<Camera onBarCodeScanned={handleBarCodeScanned} zoom={Platform.OS === 'ios' ? 0.015 : 0} />`
This has the effect of applying a digital zoom, so that the camera is farther than its minimum focus distance.

Apple applies a similar method in their [sample barcode scanning project](https://developer.apple.com/documentation/avfoundation/capture_setup/avcambarcode_detecting_barcodes_and_faces). My "fix" could be improved by having access to the camera's `minimumFocusDistance` and `maxAvailableVideoZoomFactor` to tune this value for the device. Apple's solution to the problem:
```swift
private func setRecommendedZoomFactor() {
  /*
	  Optimize the user experience for scanning QR codes down to sizes of 20mm x 20mm.
	  When scanning a QR code of that size, the user may need to get closer than the camera's minimum focus distance to fill the rect of interest.
	  To have the QR code both fill the rect and still be in focus, we may need to apply some zoom.
  */
  let deviceMinimumFocusDistance = Float(self.videoDeviceInput.device.minimumFocusDistance)
  guard deviceMinimumFocusDistance != -1 else { return }
  
  let deviceFieldOfView = self.videoDeviceInput.device.activeFormat.videoFieldOfView
  let minimumSubjectDistanceForCode = minimumSubjectDistanceForCode(fieldOfView: deviceFieldOfView,
																		  minimumCodeSize: 20,
																		  previewFillPercentage: Float(self.rectOfInterestWidth))
  if minimumSubjectDistanceForCode < deviceMinimumFocusDistance {
	  let zoomFactor = deviceMinimumFocusDistance / minimumSubjectDistanceForCode
	  do {
		  try videoDeviceInput.device.lockForConfiguration()
		  videoDeviceInput.device.videoZoomFactor = CGFloat(zoomFactor)
		  videoDeviceInput.device.unlockForConfiguration()
	  } catch {
		  print("Could not lock for configuration: \(error)")
	  }
    }
  }
```

**Comment by JasonHenson** [comment]
This really needs to be looked into because we have multiple clients complaining about not being able to scan barcodes using iPhone 14 pro.

**Comment by mljlynch** [comment]
@byudaniel  is there an existing package that exposes `minimumFocusDistance`?

**Comment by byudaniel** [comment]
I haven't found an existing package that exposes `minimumFocusDistance`.

**Comment by Jeppeer** [comment]
FYI: I ended up ditching the `expo-camera` alltogether, and moving to [React Native Vision Camera](https://github.com/mrousavy/react-native-vision-camera) instead.

A bit of work, but it has turned out really well. No problems with scanning whatsoever, and the scanner is faster as well. If you're having problems with the focus on `expo-camera` I would really recommend looking into it.

**Comment by binarybase** [comment]
I solved it using selecting cameraId - to ultra-wide camera. I'm not sure how to exactly detect IP13 Pro or IP14 Pro.

`javascript
        const camera = useRef();
        const [ cameraId, setCameraId ] = useState("");

	// camera ready handler
	const onCameraReady = useCallback(() => {
		// get cameras async
		camera.current?.getCameraIdsAsync().then(cameraIds => {			
			const ultraWideAngleCamera = cameraIds.find(c => c.deviceType == 'AVCaptureDeviceTypeBuiltInUltraWideCamera')?.id;
			if(ultraWideAngleCamera){
				setCameraId(ultraWideAngleCamera);
			}
		}).catch(ex => {

		});
	}, [ camera ]);


        <RNCamera ref={camera} cameraId={cameraId} onCameraReady={onCameraReady} {....} />
`

**Comment by terryatgithub** [comment]
we met this issue too, why this critical issue be closed, instead of escalate to the highest priority?

**Comment by terryatgithub** [comment]
we met this issue too, is there any update about it?

**Comment by terryatgithub** [comment]
we met this issue on the Web(react-native-web) too, is there any update about it?

**Comment by bryanltobing** [comment]
any update on this issue?

**Comment by SidMasih** [comment]
+1

**Comment by axeld-galadrim** [comment]
@expo-bot  please re-open

**Comment by seba9999** [comment]
I'm still experiencing blurry image with an iphone 14 pro and expo-camera@15.0.16 ... 

```
  const [autoFocus, setAutoFocus] = useState('on'); // I've tried "on" and "off" without any changes
  const [useModernScanner, setUseModernScanner] = useState(false); // To try modernScan on iOS but doesn't change anything !

<CameraView
      ref={cameraRef}
      style={ {
           height: '100%',
           width: '100%'
       }}
      facing="back"
      ratio="1:1"
      autofocus={autoFocus}
      barcodeScannerSettings={{
        barcodeTypes: ['qr'],
      }}
      onModernBarcodeScanned={isiOS && useModernScanner ? onScan : undefined}
      onBarcodeScanned={!isiOS || !useModernScanner ? onScan : undefined}
 />
```
