### ISSUE TITLE
 DeviceMotion addListener not listening on expo start

### ISSUE THREAD

**Issue by Nik0di3m** [expo/expo#19475]
### Summary

DeviceMotion.addListener not listening on expo development server `expo start`. DeviceMotion.addListener only listening in published app `expo publish`. 

### What platform(s) does this occur on?

iOS

### Environment

 System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~46.0.13 => 46.0.13
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

import React, { useEffect, useState } from "react";
import { Text, View, StyleSheet } from "react-native";
import Constants from "expo-constants";
import { DeviceMotion } from "expo-sensors";

export const CustomGyro = () => {
    const [data, setData] = useState({});

    const getOri = async () => {
        const isAvailable = await DeviceMotion.isAvailableAsync();
        console.log("isAvailable", isAvailable);
        DeviceMotion.addListener(({ rotation }) => {
            console.log("kkkkkkk");
            const alpha = Math.abs(rotation.alpha);
            setData({
                rotation,
                ori:
                    alpha > 3 || (alpha > 0 && alpha < 0.5)
                        ? "landscape"
                        : "protrait",
            });
        });
    };

    useEffect(() => {
        getOri();
    }, []);

    return (
        <View style={styles.container}>
            <Text style={styles.paragraph}>
                {Date.now()}
                {JSON.stringify(data, null, 2)}
                {data.ori}: {data.rotation?.alpha}
            </Text>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingTop: Constants.statusBarHeight,
        backgroundColor: "#ecf0f1",
        padding: 8,
    },
    paragraph: {
        margin: 24,
        fontSize: 18,
        fontWeight: "bold",
    },
});

**Comment by liquidvisual** [comment]
I'm using the Bare Workflow and it works for me until I enable Chrome Debugging and then it stops listening.

**Comment by brentvatne** [comment]
as @liquidvisual pointed out, this may be an issue with chrome debugging. we recommend switching to hermes so you can use a much better javascript debugger.
