### ISSUE TITLE
C++ exception in 'nativeCallSyncHook'

### ISSUE THREAD

**Issue by ericmorgan1** [expo/expo#1947]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 7.10.0
  Yarn: Not Found
  npm: 4.2.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Also:
"expo-graphics": "^1.0.0-alpha.1",
"expo-three": "^3.0.0-alpha.1",

iOS
iPhone X

### Steps to Reproduce

1. Sorry, I have not found a consistent way to reproduce this. It comes up very rarely, but I have seen it about 5 times so far.

I'm hoping the stack trace is enough to figure out if we just need to do some data validation or something.

### Expected Behavior

Don't crash.

### Actual Behavior

App crashes

![img_9818](https://user-images.githubusercontent.com/10346191/42250494-f21185a8-7ef6-11e8-898c-3c2e0084277d.PNG)

### Reproducible Demo

I don't have a demo or even a consistent way to reproduce it.
If needed, I can add my project to Github.
I tried making a simple demo, but I couldn't get the crash -- not sure if it's because of the demo or just because this bug is really rare.

**Comment by jesseruder** [comment]
Looks like it's somewhere in the `three.js` library. I think it's unlikely we figure out what's going on unless you can give us some code to reproduce it. Would be useful if you could simplify your code as much as possible while still reproducing it and then put it on github. Thanks!

**Comment by cruzach** [comment]
Hi! I'm closing old/inactive issues, and since this is over a year and a half old I'm going to close it for now. If you can provide a repro as jesse mentioned above, we'll be happy to take a look at this
