### ISSUE TITLE
On distributed app without updates received, `Updates.updateId` doesn't correlate with UUID in Expo API

### ISSUE THREAD

**Issue by bradjones1** [expo/expo#19473]
### Summary

[`Updates.updateId`](https://docs.expo.dev/versions/v46.0.0/sdk/updates/#updatesupdateid) is documented to be:

> The UUID that uniquely identifies the currently running update if `expo-updates` is enabled.

In my testing this does return a UUID, however it doesn't correspond with any EAS Update related object in the API.

This functionality was added in https://github.com/expo/expo/pull/8169 however nothing in particular strikes out at me as a cause of this issue. Does the UUID in this property correlate with something I can identify inside of the EAS API?

### What platform(s) does this occur on?

Android, iOS

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.18 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: bare
```

### Minimal reproducible example

```
<Text>{Updates.updateId} - {Updates.channel}</Text>
```

**Comment by bradjones1** [comment]
Similar to https://github.com/expo/expo/issues/10140

**Comment by bradjones1** [comment]
Well... now I just got an updateId which seems to match. I'll re-open if I get uncorrelated IDs again in the future.

**Comment by bradjones1** [comment]
OK so I have updated the title to reflect the issue here; if you distribute an app through the app store and it has not (yet) received any OTA updates from EAS Update, the UUID received as `Updates.updateId` doesn't correlate to anything I can identify in the release chain - it's not the UUID of the build, the update group... anything I can correlate. Once the app receives an OTA update, it is then the UUID of the platform's update.

Is it possible to clarify what this UUID does correlate to, or perhaps make it return `null` as I would perhaps expect it to, per the docs?

**Comment by douglowder** [comment]
If you have not yet received any OTA updates, then I believe the UUID you are referring to is the one for the "embedded" manifest creating during the app build. This is what loads if there are no updates available.

For example, if you include `expo-updates` in your iOS app build, there will be a script build phase added, see https://github.com/expo/expo/blob/e8437f4503b92521eed956e3d6b12916d87be506/packages/expo-updates/ios/EXUpdates.podspec#L48

On both platforms, the code that actually creates the embedded manifest is in https://github.com/expo/expo/blob/main/packages/expo-updates/scripts/createManifest.js

Hope this helps clarify things!

**Comment by sregg** [comment]
is there a way to detect if the UUID came from an OTA update or from the default embedded bundle?

**Comment by douglowder** [comment]
You can use `Updates.isEmbeddedLaunch`, which is true when running the embedded bundle, and false when running an OTA update.
