### ISSUE TITLE
expo fingerprint is not work in many android model?

### ISSUE THREAD

**Issue by chintansavjiyani1996** [expo/expo#1948]
i am getting issue when i am access fingerprint from old Samsung or many other MeiZu device so there is any api or other things so i can access fingerprint scanner in old device ? And Does Expo support FingerPrint scanning for Samsung and MeiZu api ? or any other way to include this api in my application? Thanks is advance.

there is code snippet that are as follow

/**
 * For toggeling scanner.
 * @private
 */
_toggleScanner() {
    this.setState({showScanner: false});
}

componentDidMount() {
    Expo.Fingerprint.hasHardwareAsync().then(response => {
        hardware = response;
    });
    Expo.Fingerprint.isEnrolledAsync().then(response => {
        enrolled = response;
    });
}

authFunction = () => {
    if (!hardware || !enrolled) {
        let message = !hardware ? 'This device doesn\'t support fingerprint scanning.' : !enrolled ? 'No fingerprints registered.' : 'App has no permission.'
        Toast.show(message, Toast.SHORT);
        return;
    }

    if (this.state.showScanner === true) {
        this._toggleScanner();
        try {
            Expo.Fingerprint.authenticateAsync().then(response => {
                if (response.success) {
                    Toast.show("Auth successful!", Toast.SHORT);
                    this.props.onPreferences(userPreferences);
                    this.props.onLogin(decryptText(getAuthKey));
                }
                else if (response.error === 'app_cancel') {
                    return null;
                } else {
                    this._toggleScanner();
                    Toast.show("Authentication Failure. Please Try Again!", Toast.SHORT);
                    Alert.alert("Authentication Failure", "Please authenticate to login.", [{
                        text: 'Ok',
                        onPress: () => {
                            this.props._toggleAndroidScanner()
                        }
                    }], {cancelable: false});
                }
            });
        } catch (error) {
            //if Finger scan will fail.
        }
    }
};

render() {
    {
        setTimeout(this.authFunction, 1000)
    }
    return (
        <View>
            <View style={androidScannerStyles.outerView}>
                <Image source={require('../../assets/finger_print.png')}/>
                <Text style={androidScannerStyles.fingerPrintStyle}>Place Your Finger</Text>
            </View>
        </View>
    );
}

**Comment by bakaa99** [comment]
i am also having this issue.
it suddenly stops working on the live app.
Restarting the app fixes the problem though.

some android models give the alert: "this hardware is not supported in your device"
even if the device has fingerprint scanner

**Comment by jesseruder** [comment]
Hi! Could you please provide specific device models?

**Comment by bakaa99** [comment]
panasonic eluga ray max

**Comment by chintansavjiyani1996** [comment]
its on all meizu device like lyf , leEco devices and some samsung devices where fingerPrint sdk (api) is made by there company it self and they are not using android fingerprint sdk so expo need to add all there devices sdk

**Comment by marexv** [comment]
Doesn't work on samsung galaxy s8 either.

**Comment by jsuokas** [comment]
Doesn't work on any android device I am testing as a standalone app. Calling hasHardwareAsync function returns an error `Encountered an exception while calling native method: Exception occurred while executing exported method hasHardwareAsync on module ExpoLocalAuthentication: null`. This is only a problem with standalone Android app.

**Comment by Anitorious** [comment]
> Doesn't work on any android device I am testing as a standalone app. Calling hasHardwareAsync function returns an error `Encountered an exception while calling native method: Exception occurred while executing exported method hasHardwareAsync on module ExpoLocalAuthentication: null`. This is only a problem with standalone Android app.

This is still an issue with the latest SDK. Testing with Android 7, 8 and 9. Devices include the Google Pixel, Samsung Galaxy S8, Samsung S7 Edge. The issue only seems to occur on devices that have some sort of Local Authentication hardware.

Sentry
```Encountered an exception while calling native method: Exception occurred while executing exported method hasHardwareAsync on module ExpoLocalAuthentication: null```

**Comment by tsapeta** [comment]
This issue seems to be pretty old and there have been a lot of changes since then. Hopefully, it's been already solved as we haven't received similar reports recently. Feel free to comment here or open a new issue if it's still bothering you in the most recent SDK.
