### ISSUE TITLE
[Android] WebBrowser crashes the app pretty hard when URL is malformed

### ISSUE THREAD

**Issue by victorgoya** [expo/expo#1949]
### Environment

Environment:
  OS: Linux 4.15
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/phorque-29b6fb54-9cef-4066-b0eb-3bcd57ccf12c.tar.gz

### Steps to Reproduce

` WebBrowser.openBrowserAsync("www.google.com");` (note the missing 'http://')

### Expected Behavior

I would expect the method to throw an exception or accept the URL and add the protocol by itself.

### Actual Behavior

Expo crashes badly with no stacktrace, a `try {} catch {}` block doesn't help.

### Reproducible Demo

https://snack.expo.io/@phorque/crash-with-webbrowser

**Comment by jesseruder** [comment]
Hi! Is this on iOS/Android/both?

**Comment by brunoreis** [comment]
It's crashing for me when I use Http (with an upper cased h) instead of http

**Comment by opringle** [comment]
Just experienced this behaviour. It was a little confusing for the app to completely crash rather than expo throw an error.

**Comment by jarodsmk** [comment]
I noticed this also happens with Data URLs. A couple examples of valid ones can be found on:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

I created a file with `Print.printToFileAsync(...)` and got it's base64 data, and tried to form a valid Data URL with it.

An easy way to reproduce it is:

`let result = await WebBrowser.openBrowserAsync('data:,Hello%2C%20World!')`

**Comment by jarodsmk** [comment]
Taking a look at the code briefly,

https://github.com/expo/expo/blob/4a39a5789fbe5d022ae7f37839cdb1f882dec87a/packages/expo-web-browser/android/src/main/java/expo/modules/webbrowser/WebBrowserModule.java#L133

Data is set on `intent` w/o handling the NullPointer which could be thrown by `Uri.parse`, and since it's outside of the try/catch could cause the crash?

Just a hunch

**Comment by esamelson** [comment]
@jarodsmk - thanks for taking a look into this, feel free to submit a PR if you'd like to go ahead and make the fix 🙂

**Comment by cmacdonnacha** [comment]
Was able to reproduce the same issue with `www.google.com`. I tried wrapping it in a try catch but that didn't help. Is there anything we can do to prevent this? Check for http or https I guess?

`    try {
      WebBrowser.openBrowserAsync(url);
    } catch (error) {
      ToastAndroid.show('Error opening event website', ToastAndroid.SHORT);
    }
`

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
