### ISSUE TITLE
Feather icon set is deprecated and buggy, we probably need to switch to its successor is Lucide

### ISSUE THREAD

**Issue by Noitidart** [expo/expo#19497]
### Summary

I'm not sure if this is bug or feature request. But Feather icons is deprecated end of life, many requests to fix bugs, etc are falling flat. To fix the bugs with the feather icon set (like not showing right depending on DPI of phone), we may not want outdated things in expo and instead uses it successor.

* https://github.com/feathericons/feather/issues/1167#issuecomment-1253351605
* https://github.com/feathericons/feather/issues/1126#issuecomment-1017703649
* https://github.com/feathericons/feather/issues/1110#issuecomment-963024229
* And more mentions - https://github.com/feathericons/feather/search?q=lucide&type=issues

These mention successor is Lucide - https://github.com/lucide-icons/lucide

### What platform(s) does this occur on?

Android, iOS, Web

### Environment

All environments.

### Minimal reproducible example

One of the many bugs with Feather is seen here - https://icons.expo.fyi/Feather/chrome - with high DPI you will see glitches - 
![image](https://user-images.githubusercontent.com/6372489/195164509-3891cbd6-187d-472e-a140-1a7c8ba57179.png)

The correct way it should render is - seen on Lucide - https://lucide.dev/?search=chrome

<img width="204" alt="image" src="https://user-images.githubusercontent.com/6372489/195164752-a5be84cf-a66d-46c0-9716-033f2e76e8d5.png">

**Comment by Simek** [comment]
Hello @Noitidart,

`@expo/vector-icons` is only a compatibility wrapper around [`react-native-vector-icons`](https://github.com/oblador/react-native-vector-icons) package, we do not control the source.

Any feature requests or bug reports related to the content should be reported directly in `react-native-vector-icons` repository.

**Comment by Noitidart** [comment]
Ah got it, thank you.

**Comment by Simek** [comment]
Thank you for the follow up! 👍
