### ISSUE TITLE
44 -> 45 SDK upgrade causes WebView to lose cookies on Android

### ISSUE THREAD

**Issue by negamaxi-agm** [expo/expo#19490]
### Summary

We use httpOnly cookies to maintain authenticated session inside of WebView context to view secured images, audio etc. Upgrade from 44 to 45 SDK and higher breakes it on Android - inspected requests sended by `<img src=`, `<audio src=`, `<video src=` tags no longer include `cookie` header on Android. `fetch` requests from inside WebVIew miss it too **on both platforms**.

Further investigation revealed that 44 SDK with latest `react-native-webview` (1.23.1 to date) build doesn't have this issue, therefore it seems it's not a `react-native-webview` package issue.

Also this issue remains inside of latest Expo Go (2.25.2 to date) development context **no matter what SDK version I use**. So I had to build actual EAS build to see the bug is missing on 44 SDK.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Fedora Linux 36 (Workstation Edition)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.0.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

WebView is used somehow like that:

```js
    <WebView
      source={{
        html
      }}
    />
```
`html` includes immediate authentication fetch call that once resolved programmatically sets `src` attribute of an appropriate html element.

**Comment by Kudo** [comment]
hi there! could you help to create a minimal example project that we can reproduce locally? i'm happy to investigate and reopen the issue if there's a repro we can try.

**Comment by negamaxi-agm** [comment]
@Kudo here is the closest reproduction I can get https://github.com/negamaxi-agm/expo-webview-cookies

It includes both server and client side projects.

**Comment by negamaxi-agm** [comment]
@Kudo will someone investigate this?

**Comment by Kudo** [comment]
@negamaxi-agm thanks for your great example. the issue i've seen is related to html serving through html data is crossing origin to the xhr calls, so cookie will not be shared. this patch with `baseUrl` to let webview know the html data is based on the same server. after applying the patch, it works for me.

```diff
--- a/client/App.js
+++ b/client/App.js
@@ -63,6 +63,7 @@ export default function App() {
       }}
       source={{
         html, // Cookie management doesn't work
+        baseUrl: serverURL,
         // uri: serverURL // Cookie management works
       }}
     />
```

i believe this issue is nothing to do with expo sdk, should be react-native-webview or android webview. if you think that is expo sdk related, please also have an example on sdk 44 + latest react-native-webview where you said working for you. thanks!
