### ISSUE TITLE
[expo-image-picker] Specific images are broken on the ios.

### ISSUE THREAD

**Issue by seungyoubkim** [expo/expo#19503]
### Summary

Using the expo-image-picker to select a specific image in iOS, the image is truncated at the top and filled in black at the bottom.

![스크린샷 2022-10-12 오전 10 39 49](https://user-images.githubusercontent.com/106951161/195237036-ac79ce78-f8c8-4526-b4ec-d4b0d4599114.png)

The original image in the above screenshot is one of the default images in the ios emulator.

The characteristic of this image is that it is an HDR photo of the HEIF format.

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.9.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.1 - /opt/homebrew/bin/npm
      Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/kimseung-youb/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.8 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    Expo Workflow: bare
```

### Minimal reproducible example

Version of expo - `46.0.0`, Version of expo-image-picker - `13.3.1`. Here's the reproducible demo - [snack demo](https://snack.expo.dev/@seungyoubkim/expo-image-picker?platform=ios)

**Comment by seungyoubkim** [comment]
To resolve this issue, I upgraded the version of expo-image-picker to 14.0.1, and now HEIF pictures fail to pick.

```
Error: Failed to read picked image
→ Caused by: Cannot load representation of type public.jpeg
    at construct (native)
    at Wrapper (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=im.jobda.app.newrrow:20649:64)
    at construct (native)
    at _createSuperInternal (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=im.jobda.app.newrrow:99085:322)
    at call (native)
    at CodedError (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=im.jobda.app.newrrow:99093:26)
JPEG photos are picked well.
```

Am I the only one who has a problem?

The expo version is 47.0.0 and the expo-image-picker version is 14.0.1.

**Comment by brentvatne** [comment]
@seungyoubkim - the issue that you mentioned in your original post a bug in the iOS system image picker component, which we don't have any control over. I believe it only occurs when you allow editing of the image.

please share a minimum reproducible example of the latter case. thanks!

**Comment by seungyoubkim** [comment]
> @seungyoubkim - the issue that you mentioned in your original post a bug in the iOS system image picker component, which we don't have any control over. I believe it only occurs when you allow editing of the image. see http://www.openradar.me/36292067
> 
> please share a minimum reproducible example of the latter case re: HEIF in a new issue. thanks!

Cannot create an example of the expo-image-picker 14.0.1 version because the snack has an expo version of expo.

When can I use the expo 47 version on Snack?
