### ISSUE TITLE
[RFC] Harmonize location.timestamp

### ISSUE THREAD

**Issue by slorber** [expo/expo#1950]
Hi,

I don't know, if this is wanted or not, but when using the Location API, the timestamp is a float on iOS (at least on iPad mini I have). This was unexpected on my side and actually led to a bug as I expected it as a long on my java backend.

As timestamp is already in milliseconds which is precise enough for me, maybe it would be better to harmonize with android and always return an integer/long instead of a float.

Or at least add in the doc the kind of number we should expect from the API (integer/float) instead of just "number".

![image](https://user-images.githubusercontent.com/749374/42267755-3030d1da-7f7a-11e8-9a77-2aa57cc0e08b.png)

Data I tried to sent to my backend:

```
[10:52:43]   "body": Object {
[10:52:43]     "accuracy": 65,
[10:52:43]     "altitude": 48.97092819213867,
[10:52:43]     "altitudeAccuracy": 10,
[10:52:43]     "heading": -1,
[10:52:43]     "latitude": 48.97662501898676,
[10:52:43]     "longitude": 2.325900917368605,
[10:52:43]     "speed": -1,
[10:52:43]     "timestamp": 1530694263479.906,
[10:52:43]   },
```

Not sure what should be done

**Comment by brentvatne** [comment]
in javascript all numbers are of type `number` and are 64 bit floats, whether the number is 5 or 5.5.

<img width="147" alt="screen shot 2018-07-04 at 11 49 11 am" src="https://user-images.githubusercontent.com/90494/42291415-4ba8559a-7f80-11e8-8418-eb6260c5ae29.png">

**Comment by slorber** [comment]
ok thanks, so I guess the doc is clear enough and I'm closing. Just finding it unusual to have float timestamps
