### ISSUE TITLE
login exp with command line 

### ISSUE THREAD

**Issue by hamzachaouch** [expo/expo#1951]
hey , 
i m having an issue when i try :  exp build-android  it 's saying to me to enter a password and after the a username , i already putted my login and password many time but it doesn't work , i m running it on windows 10 cmd ...
i reseted  my password several times but it s always the same problem... 
any help plz?
![erreur](https://user-images.githubusercontent.com/22745729/42272538-50f8e962-7f7e-11e8-9192-e797668e8ac5.PNG)

**Comment by brentvatne** [comment]
hello! you have some app from oracle which is also called exp installed on your computer :O 

try using our new tool instead, `npm i -g expo-cli` then run `expo build:android`
