### ISSUE TITLE
expo-av, when recording audio on web, metering is always undefined

### ISSUE THREAD

**Issue by amitchell-tbox** [expo/expo#19515]
### Summary

I have recently upgraded from version 10.1.0 to 12.0.4
The app im working on makes use of the metering value while recording audio,
however it is now always undefined

This is happening running react-native project on web,
Currently unable to run the project on ios & android sorry

EDIT:
After further investigation I found that metering was removed from web as early as version 10.2.1 if not before,

ExponentAV.web.js
getAudioRecordingStatus

in 10.1.0 this function would calculate and return metering, but in versions 10.2.1+ that function in the same file never returns metering

### What platform(s) does this occur on?

Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    Expo Workflow: managed

### Minimal reproducible example

`
await Audio.setAudioModeAsync({
  allowsRecordingIOS: true,
  interruptionModeIOS: 1,
  playsInSilentModeIOS: true,
  shouldDuckAndroid: false,
  interruptionModeAndroid: 1,
  playThroughEarpieceAndroid: false,
  staysActiveInBackground: true
})

const recording = new Audio.Recording()

await recording.prepareToRecordAsync({
  ...Audio.RecordingOptionsPresets.HIGH_QUALITY,
  isMeteringEnabled: true
})

recording.setOnRecordingStatusUpdate((status: RecordingStatus) => {
  console.log(status.metering) // undefined
})`

**Comment by rickdotta** [comment]
I am having the same issue. metering works fine on iOS, but not on the web. Using expo-av@13.2.1. Not sure if this is expected behavior?

**Comment by heyedd** [comment]
yep. same here.

**Comment by som3aware** [comment]
I can also confirm that is's returning `undefined` on web, android and personal device as well.
Here is a reproducible example:
```js
import React, { useEffect } from 'react';
import { View, Button, StyleSheet, Text } from 'react-native';
import { Audio } from 'expo-av';

export default function App() {
  const [recording, setRecording] = React.useState();
  const [metering, setMetering] = React.useState()

  useEffect(() => {
    monitorLoudness()
  });

  async function monitorLoudness() {
    if (recording) {
      const { metering, isRecording } = await recording.getStatusAsync();
      setMetering(metering)
      console.log('metering', metering);
    }
  }

  async function startRecording() {
    try {
      console.log('Requesting permissions..');
      await Audio.requestPermissionsAsync();
      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
      });

      console.log('Starting recording..');
      const { recording } = await Audio.Recording.createAsync(
        {...Audio.RecordingOptionsPresets.HIGH_QUALITY, isMeteringEnabled: true}
      );
      setRecording(recording);
      console.log('Recording started');
    } catch (err) {
      console.error('Failed to start recording', err);
    }
  }

  async function stopRecording() {
    console.log('Stopping recording..');
    setRecording(undefined);
    await recording.stopAndUnloadAsync();
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
    });
    const uri = recording.getURI();
    console.log('Recording stopped and stored at', uri);
  }

  return (
    <View style={styles.container}>
      <Button
        title={recording ? 'Stop Recording' : 'Start Recording'}
        onPress={recording ? stopRecording : startRecording}
      />
      {recording && <Text>{metering.toString()}</Text>}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by radvansky-tomas** [comment]
Check my PR please and provide some feedback https://github.com/expo/expo/pull/34492/files
