### ISSUE TITLE
`UpdateEvnetAsync` in Calendar module can't update `calendarId`

### ISSUE THREAD

**Issue by yunying1** [expo/expo#19514]
### Summary

# Repro steps

## Step 1

create a new calendar: c1 then create a new event for it.

## Step 2

create the second calendar: c2
update the `calendarId` in the last event to `calendarId` in `c2` and update the `notes`  to `changed`.

## Result
I not got error, it's succeeded, The `notes` update to `changed` successfully but `calendarId` not changed, it is still the old value: `calendarId` in `c1`

## Other

This issue is the same as [18865](https://github.com/expo/expo/issues/18865), This issue is supplement.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.13 => 46.0.15 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: managed

### Minimal reproducible example

I have a minimal example: https://snack.expo.dev/@yuanx/calendar-update-calendarid-for-event

**Comment by keith-kurak** [comment]
Hi @yunying1!

Thanks for submitting the repro! To make sure I'm understanding correctly, you're expecting the event to move to the second calendar when `updateEventAsync` is called with the event ID and the new calendar ID?

Looking at the code, it appears that this operation is not supported and the `calendarId` is ignored in this scenario. Assuming such an update is not possible using the underlying native calendar components provided in iOS, we should at least document this.
