### ISSUE TITLE
iOS app crashes immediately when using hermes + useFrameworks static (expo-build-properties)

### ISSUE THREAD

**Issue by alex-fournier** [expo/expo#19517]
### Summary

After building an app binary for iOS with EAS build, the app crashes immediately if the following two conditions are met in `app.json`:

- `expo.jsEngine` = `hermes`
- `expo.plugins` contains `["expo-build-properties", { "ios": { "useFrameworks": "static" } }]`

Removing one of the two conditions solves the problem, but I need both :(

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.09.19.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 30, 31
        Build Tools: 30.0.2, 31.0.0, 33.0.0
        System Images: android-21 | ARM EABI v7a, android-24 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.15 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 2.3.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

Here is a minimal reproducible example: https://github.com/alex-fournier/debug-expo

Steps to reproduce the crash on iOS simulator:

1. `npm i`
1. `eas login`
1. `eas build:configure`
1. `eas build -p ios --local --clear-cache`
1. Drag and drop app file into your simulator
1. Launch app, it crashes :'(

**Comment by sebastienlabine** [comment]
having to fallback to jsc is pain :(

**Comment by marcfrankel** [comment]
Just wanted to chime in as one of the linked issues is created by me. I believe I am experiencing this issue as well. I originally thought it had to do with a package called RealmJs, since it appears during the crash log, but there's a chance that's a misdirect and just due to how early it starts up in the app startup sequence. 

In case the expo team is wondering about our use case for switching to Static Frameworks, we need it in order to use the most recent versions of React Native Firebase.

**Comment by sagihsh** [comment]
Having the same issue, with the same versions of iOS, Expo SDK, React & React Native,
But I did not specify the 2 values you mentioned in app.json (I'm using the dynamic app.config.js though, if that's relevant).

I use eas update to publish my app, then when I try to load it in Expo Go, it immedietly crashes.

I did have successful published versions in the past though, but now every version I try to publish crashes.
I even tried to take the exact commit that's in the last successfuly published version and publish it again, it crashed too.
NO errors what so ever when it crashes, iOS expo go log files are created but are blank. 

BTW when trying to open this on Android, Expo Go doesn't crash but the update download is infinite.

Begging for any leads here!

**Comment by brentvatne** [comment]
this works well with sdk 47.

```
{
  "name": "try-props-repro",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~47.0.8",
    "expo-build-properties": "~0.4.1",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "expo-splash-screen": "~0.17.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

```
{
  "expo": {
    "name": "try-props-repro",
    "slug": "try-props-repro",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "jsEngine": "hermes",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.brents.try-props-repro"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ]
  }
}
```

**Comment by NKANGIJAFARI** [comment]
Hello am having sdk 47 and this issue is happening. I have tried alot of things and all in vein. 
Its completely a new project where by I wanted to test the project as it had persisted in my another project.

My app.json file is as below.

```
{
  "expo": {
    "name": "sayaraauto",
    "slug": "sayaraauto",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "jsEngine": "Hermes",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "buildNumber": "1.0.0",
      "bundleIdentifier": "com.testtesting.teststs,
      "googleServicesFile": "./GoogleService-Info.plist",
      "infoPlist": {
        "NSCameraUsageDescription": "Allow Health Express to use the camera to let you upload a photo in their profile.",
        "NSPhotoLibraryUsageDescription": "The app accesses your photos to let you share your document for processing your booking.",
        "NSLocationWhenInUseUsageDescription": "Allow Health Express to use your location to ease searching for nearby doctors/nurses.",
        "NSUserTrackingUsageDescription": "Allow Health Express to collect app-related data that will used to deliver personalized ads to you.",
        "NSMicrophoneUsageDescription": "Allow Health Express to access your microphone to push voice updates to you."
      }
    },

    "android": {
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.testtesting.teststs"
    },
    "plugins": [
      "@react-native-firebase/app",
      "@react-native-firebase/auth",
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ],
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "15cb70bc-361b-4248-9be6-437b4dcb5b58"
      }
    }
  }
}

```

Trying to use rnFirebase

**Comment by pehagg** [comment]
I'm having the exact same issue as @NKANGIJAFARI after upgrading to 47 (with latest available RNFirebase). However, in my case the app crashes when I try to run it from CLI, but from Xcode it runs just fine.

**Comment by danieldanielecki** [comment]
Also had the same issue, seeing all the tricks with `hermes`, I just upgraded to `Expo 48` when it became default `JavaScript` engine, and it's working. In the meantime, had this issue: https://stackoverflow.com/questions/66204988/app-closes-on-start-when-trying-to-run-react-native-run-ios while running on a device (simulators worked fine).
