### ISSUE TITLE
`npx expo run:ios` reverts changes from `app.json` and `package.json`

### ISSUE THREAD

**Issue by juliusmarminge** [expo/expo#19527]
### Summary

Got [this issue](https://github.com/t3-oss/create-t3-turbo/issues/31) on my template repo [t3-oss/create-t3-turbo](https://github.com/t3-oss/create-t3-turbo) about the entrypoint `index` wasn't found when it's configured to be `src/_app.tsx`. When I ran the command it said `expo.entryPoint` wasn't needed so it removed it, and it set the `main` field in package.json to `index.js`. It even complained about my metro.config not matching any templates.

What's the point of configuring these files if they are just overridden later???

![CleanShot 2022-10-12 at 21 11 26](https://user-images.githubusercontent.com/51714798/195431358-6ad19f82-4c51-4bdf-be26-ce49703fe739.png)

Related PR: https://github.com/t3-oss/create-t3-turbo/pull/32

### What platform(s) does this occur on?

iOS

### SDK Version

46.0.10

### Environment

 ```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    Expo Workflow: bare
```

### Minimal reproducible example

1. Create a new app using the expo-cli:
```bash
npx create-expo-app
```

2. Move the `App.js` to `src/_app.jsx`
3. Instead of export defaulting, register the root component:
```diff
+ import { registerRootComponent } from "expo";

- export default function App() { ... }
+ function App() { ... }

+ registerRootComponent(App);
```

4. Change the `main` field in `package.json`:
```diff
+ "main": "src/_app.jsx",
```

5. Add the `entryPoint` field in `app.json`:
```diff
+ "entryPoint": "./src/_app.jsx"
```

6. Test the app by running `npm run ios`. It works!
7. Run `npx expo run:ios`. It fails! You'll get this error:
![CleanShot 2022-10-12 at 21 11 26](https://user-images.githubusercontent.com/51714798/195434138-080f979a-07bc-4fba-afc4-d7dc72b60327.png)

**Comment by brentvatne** [comment]
@juliusmarminge - react native community cli (used by the default react native build scripts) doesn't have good support for alternative entry points at the moment. we've been doing a bunch of work to move towards moving the bundling scripts to use expo cli instead, and this will make it so we don't need to change the app entry point. this will hopefully be available in sdk 47. see: https://github.com/expo/expo/pull/18906
