### ISSUE TITLE
GL View not rendering or appearing in Image after screenshot

### ISSUE THREAD

**Issue by olympikesoft** [expo/expo#1952]
Hello, i want to take a screenshot with the images of threejs, but it's not taking the object when i click on camera to take a photo, how to fix this?

It's a bug ??? I'm testing in Android.

```
 _takeAndUploadPhotoAsync = async () => {
    
      

    let result = await Expo.GLView.takeSnapshotAsync(this.sate.object, {
        format: 'png', /// PNG because the view has a clear background
        quality: 1, /// high quality works 
        result: 'file',
        });
        
        console.log(result);

    let saveResult = await CameraRoll.saveToCameraRoll(result, 'photo');
    this.setState({ image: saveResult });
```

**Comment by olympikesoft** [comment]
@nikki93 I have seen you talking about this

**Comment by olympikesoft** [comment]
This is a bug @tsapeta  ?

**Comment by tsapeta** [comment]
Hey @olympikesoft, could you explain what is the `this.sate.object` and what is printed by `console.log(result);`?

**Comment by olympikesoft** [comment]
@aalices  @brentvatne  @ide can you please check this?

**Comment by brentvatne** [comment]
@olympikesoft - please share a complete runnable example on https://snack.expo.io. @tsapeta knows all about this so you're in good hands but there's not much he can do without all of the code that you used

**Comment by olympikesoft** [comment]
Package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^28.0.0",
   ....
  }
}
```
App.js

```
import Expo from 'expo';
import React from 'react';
import * as THREE from 'three';
import ExpoTHREE from 'expo-three'; // 2.2.2-alpha.1

export default class App extends React.Component {
  render() {
    // Create an `Expo.GLView` covering the whole screen, tell it to call our
    // `_onGLContextCreate` function once it's initialized.
    return (
      <Expo.GLView
        style={{ flex: 1 }}
        onContextCreate={this._onGLContextCreate}
      />
    );
  }

  // This is called by the `Expo.GLView` once it's initialized
  _onGLContextCreate = async gl => {
    // Based on https://threejs.org/docs/#manual/introduction/Creating-a-scene
    // In this case we instead use a texture for the material (because textures
    // are cool!). All differences from the normal THREE.js example are
    // indicated with a `NOTE:` comment.

    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(
      75,
      gl.drawingBufferWidth / gl.drawingBufferHeight,
      0.1,
      1000
    );

    // NOTE: How to create an `Expo.GLView`-compatible THREE renderer
    const renderer = ExpoTHREE.createRenderer({ gl });
    renderer.setSize(gl.drawingBufferWidth, gl.drawingBufferHeight);

    const geometry = new THREE.BoxGeometry(1, 1, 1);
    //  NOTE: How to create an Expo-compatible THREE texture
    const texture = await ExpoTHREE.loadAsync(
      require('./assets/icon.png')
    );
    const material = new THREE.MeshBasicMaterial({ map: texture });
    const cube = new THREE.Mesh(geometry, material);
    scene.add(cube);

    camera.position.z = 5;

    const render = () => {
      requestAnimationFrame(render);

      cube.rotation.x += 0.07;
      cube.rotation.y += 0.04;

      renderer.render(scene, camera);

      // NOTE: At the end of each frame, notify `Expo.GLView` with the below
      gl.endFrameEXP();
    };
    render();
  };
}
```

@tsapeta this is my code, how to implement the `GLView.takeSnapshotAsync`? If i did manually the print screen works but with this don't work.

**Comment by tsapeta** [comment]
@olympikesoft, you can take a look at the example that shows how to use `takeSnapshotAsync` on GLView: https://github.com/expo/native-component-list/blob/master/screens/GL/GLSnapshotsScreen.js

**Comment by olympikesoft** [comment]
I can use camera inside view wrapping the GLVIEW?
@tsapeta

**Comment by olympikesoft** [comment]
Something like this : https://snack.expo.io/Hytc3DjMQ @tsapeta

**Comment by olympikesoft** [comment]
My idea it's combine glview with camera  react native

**Comment by tsapeta** [comment]
I'm sorry, I don't really understand what you want to achieve 😞 Do you want to show GL rendering over camera view and take a snapshot from both of them?

**Comment by olympikesoft** [comment]
@tsapeta  Yes, it's my idea to show GL rendering over camera view and take a snapshot from both of them

**Comment by tsapeta** [comment]
I think it's not possible this way. You can try with this example: https://github.com/expo/native-component-list/blob/master/screens/GL/GLCameraScreen.js
It shows how to create GL texture that contains camera preview - if you have that texture then you can just use it in your renderings.

**Comment by olympikesoft** [comment]
What is    ` const cameraTexture = (this.texture = await this.createCameraTexture());`
? I need to use to my example.

**Comment by tsapeta** [comment]
@olympikesoft 
It returns WebGL texture that you can use to render the background of your rendering. It's automatically updated on each frame, with the current frame from camera preview.

Closing this issue as there are no bugs. I can still help you here, if you need.

**Comment by olympikesoft** [comment]
@tsapeta  I'm stack, believe me i don't now how to do it with my example, please guide me ?

**Comment by olympikesoft** [comment]
The documentation for GL VIEW and Camera it's weak and not very well related with that topics.

**Comment by ide** [comment]
tsapeta linked to some examples, plus all the code is in this repo and is a good place to look for more information beyond the docs site. If you're looking for individual help or debugging, we'd be happy to put you in touch with a consultancy that can give you private, dedicated attention.
