### ISSUE TITLE
[barcode-scanner] Barcode Scanner not scanning code128 barcodes when 

### ISSUE THREAD

**Issue by hbiede** [expo/expo#19524]
### Summary

`expo-barcode-scanner` is failing to scan code128 barcodes on iPhones/iPads running iOS 16 (not reproducible on Android, nor iOS 15.7) when QR is also included as a valid scan type. In `barCodeTypes`, I can only include types other than `qr` and `datamatrix` without it breaking, leading me to believe that `code128` alongside 2D barcodes is what is causing the problem.

### What platform(s) does this occur on?

iOS/iPadOS 16+

### Environment
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.4.1 - /usr/local/bin/fish
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ^46.0.0 => 46.0.15 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed
```
### Minimal reproducible example

https://snack.expo.dev/@dmsi/barcode-scanner

As written, QR codes and UPC codes will scan, but `code128`'s will not. Change line 40 to `BarCodeScanner.Constants.BarCodeType.datamatrix` and the effect remains the same on `code128`'s. Remove line 40 and `code128`'s become scannable and UPC's remain scannable (and obviously QR codes are no longer scannable).

**Comment by keith-kurak** [comment]
Hi, @hbiede! I was able to scan the Code 128 barcodes at https://en.wikipedia.org/wiki/Code_128 without any changes to your Snack on iOS 16, so I'm not able to reproduce this issue. Do you have an example of a barcode that fails to scan?

**Comment by hbiede** [comment]
Well, this is baffling. It was replicating every time in the snack before, but now works fine. Yet in our production app, code128's never fire off the `onBarCodeScanned` callback despite no significant difference in props.

**Comment by hbiede** [comment]
Oh, wow. Code 128 is just super specific about wanting the barcode in the dead center of the scanner screen

**Comment by Andrew-Pynch** [comment]
> 

Can you share the code for this centering rendering? Also did you discover anything else about this issue? I also cannot scan 128 type barcodes

**Comment by hbiede** [comment]
Theres not code for centering the barcode, I simply meant that that scanner box was being rendered above the center of the screen, making it appear that the device couldn’t scan the barcode. The user just had to aim higher than they think they should
