### ISSUE TITLE
'compileSdkVersion' to be set to 33 or higher (for 3 dependencies)

### ISSUE THREAD

**Issue by iboxgithub** [expo/expo#19534]
### Summary

When trying to integrate React Native Track Player v3.3 in Expo SDK 46, I have the error below on Android

> Task :app:checkDebugAarMetadata FAILED
WARNING: [Processor] Library '/Users/xxx/.gradle/caches/modules-2/files-2.1/com.google.android.exoplayer/extension-mediasession/2.18.1/454f0873b3bc62808647db8f83e484430f4872db/extension-mediasession-2.18.1.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/Nullable'
 Example of support library reference: 'android/support/v4/media/session/MediaSessionCompat$Callback'
WARNING: [Processor] Library '/Users/xxx/.gradle/caches/modules-2/files-2.1/com.google.android.exoplayer/exoplayer-ui/2.18.1/eed81d49b8b0e9a365cbec260dafb222d6e5bc67/exoplayer-ui-2.18.1.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/core/app/NotificationCompat$Builder'
 Example of support library reference: 'android/support/v4/media/session/MediaSessionCompat$Token'
WARNING: [Processor] Library '/Users/xxx/.gradle/caches/modules-2/files-2.1/com.github.DoubleSymmetry/KotlinAudio/v1.2.4/be01b19f318470b3e16e2c10e9a57909bd9bd3fb/KotlinAudio-v1.2.4.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/DrawableRes'
 Example of support library reference: 'android/support/v4/media/RatingCompat'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > One or more issues found when checking AAR metadata values:
     
     Dependency 'androidx.core:core:1.9.0' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':app' is 'android-31'
     
     Dependency 'androidx.core:core-ktx:1.9.0' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':app' is 'android-31'
     
     Dependency 'androidx.annotation:annotation-experimental:1.3.0' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':app' is 'android-31'

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.10.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
      Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.13 => 46.0.14 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.2.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

Can't add it on Snack but a simple yarn add react-native-track-player in the Expo demo app is enough

**Comment by iboxgithub** [comment]
could these dependencies be included in Expo SDK 47?

**Comment by vladis-c** [comment]
Running into this problem second day in a row. 

install `expo-build-properties` and add 
```
[
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 31,
            "targetSdkVersion": 31,
            "buildToolsVersion": "30.0.2",
            "kotlinVersion": "1.7.10"
          }
        }
      ]
```
into plugins in your app.json

You can put your required numbers here. 33 in your case.

**Comment by iboxgithub** [comment]
> Running into this problem second day in a row.
> 
> install `expo-build-properties` and add
> 
> ```
> [
>         "expo-build-properties",
>         {
>           "android": {
>             "compileSdkVersion": 31,
>             "targetSdkVersion": 31,
>             "buildToolsVersion": "30.0.2",
>             "kotlinVersion": "1.7.10"
>           }
>         }
>       ]
> ```
> 
> into plugins in your app.json
> 
> You can put your required numbers here. 33 in your case.

will give it a shot cheers

**Comment by iboxgithub** [comment]
it doesn't work as I have other dependenies in my project requiring sdk 31 (the issue is that I dont know how to identify them based on the error message)
<img width="993" alt="image" src="https://user-images.githubusercontent.com/5391993/195704612-48bf514a-c989-4f58-92af-4267d0cf20e3.png">

**Comment by vladis-c** [comment]
> it doesn't work as I have other dependenies in my project requiring sdk 31 (the issue is that I dont know how to identify them based on the error message) <img alt="image" width="993" src="https://user-images.githubusercontent.com/5391993/195704612-48bf514a-c989-4f58-92af-4267d0cf20e3.png">

Have you rebuilt the app with `expo run:android` or `npx expo run:android` (for expo 46) ?

**Comment by iboxgithub** [comment]
Hi @vladis-c ,
yes I rebuilt the app (even deleted the android folder), targetSDKVersion at 31 doesnt change the error message

**Comment by vladis-c** [comment]
> Hi @vladis-c , yes I rebuilt the app (even deleted the android folder), targetSDKVersion at 31 doesnt change the error message
![Screenshot 2022-10-14 at 12 41 55](https://user-images.githubusercontent.com/93081212/195816200-74940b90-82cc-4d43-8fd5-5293af8a009c.png)

The last part, where I did changes for that is this file. Go to **android -> build.gradle**, and check the versions there. 

Otherwise you have to find the latest version of that dependency which asks for **targetVersion*** _31_

**Comment by psquizzle** [comment]
Did you solve this issue? I'm getting this error now, and can't work out which package is requiring sdkVersion 33

**Comment by iboxgithub** [comment]
we settled on RNTP v3.1.0 as the dependencies dont break, hopefully the new version will cover these issues

**Comment by garrett-gottlieb** [comment]
I'm experiencing the same with Expo 44. Why is Android so fragile with these versions? This is incredibly frustrating. Change version number, try build, fail because now another package version isn't working. Sdk version is wrong, kotlin version is wrong, how does anyone build anything on Android?

**Comment by vladis-c** [comment]
> I'm experiencing the same with Expo 44. Why is Android so fragile with these versions? This is incredibly frustrating. Change version number, try build, fail because now another package version isn't working. Sdk version is wrong, kotlin version is wrong, how does anyone build anything on Android?

Well, the most problems I had was with iOS build. I think this problem with sdk versions on Android was the only one I had. 
On iOS when building it normally fails with "unknown error", which is more frustrating, as you actually can just try again to build the app, and now the build might be successful. I think 80% of my iOS builds fail for no reason 😁

**Comment by jamilr89** [comment]
In my case I am using 
"react-native-inappbrowser-reborn": "^3.7.0" dependency 
and adding these two lines fixed the issue for me:
 androidXBrowser = "1.3.0"
 androidXAnnotation = "1.2.0"
after
buildscript {
    ext {
in the project build.gradle file

**Comment by vladis-c** [comment]
> react-native-inappbrowser-reborn

Not sure if you need exaclty this dependency in your project, but Expo has wonderful `expo-web-browser`, which would not have any errors =)

**Comment by AnimusAudax** [comment]
> Running into this problem second day in a row.
> 
> install `expo-build-properties` and add
> 
> ```
> [
>         "expo-build-properties",
>         {
>           "android": {
>             "compileSdkVersion": 31,
>             "targetSdkVersion": 31,
>             "buildToolsVersion": "30.0.2",
>             "kotlinVersion": "1.7.10"
>           }
>         }
>       ]
> ```
> 
> into plugins in your app.json
> 
> You can put your required numbers here. 33 in your case.

It worked in my case 👍

**Comment by ansh** [comment]
I had to put the "expo-build-properties" at the top of the plugins array otherwise is got fucked up.

**Comment by kashif951** [comment]
1.  Dependency 'androidx.viewpager2:viewpager2:1.1.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :app is currently compiled against android-33.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       2.  Dependency 'androidx.annotation:annotation-experimental:1.4.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :app is currently compiled against android-33.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
