### ISSUE TITLE
[expo-location] expo-location and react-native-maps causing infinite loop

### ISSUE THREAD

**Issue by tylercallison** [expo/expo#19530]
### Summary

When using `react-native-maps` `<MapView />` and `expo-location`, there is an infinite loop on location change within an `expo-location` callback on an iOS simulator.

Specifically here:
```tsx
TaskManager.defineTask(locTaskName, ({ data, error }) => {
  if (error) {
    console.warn("Failed to get location data");
    return;
  }
  const locations = data as LocationObject;

  // This line will loop infinitely
  console.log("Received new locations", locations);
});
```

If the `<MapView />` is commented out within the repo provided, the callback will no longer be called in a loop.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.volta/tools/image/node/16.17.1/bin/node
      npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.13 => 46.0.15 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    Expo Workflow: bare

### Minimal reproducible example

Clone the repo: https://github.com/tylercallison/expo-location-infinite-loop

`git clone https://github.com/tylercallison/expo-location-infinite-loop.git`

`cd expo-location-infinite-loop`
`npm install`
`npx expo prebuild`
`npx expo run:ios`

Wait for the simulator to open and then give location access to the application. Once this is given, attempt to change the location of the device in `Features > Location` and watch the console output run an infinite loop

**Comment by tylercallison** [comment]
On further review, this is a problem when `showsUserLocation` is set to `true`

**Comment by brentvatne** [comment]
this sounds like it might be a problem in react-native-maps. it's not clear to me how expo-location could be causing this. given that the only way you can reproduce this is using react-native-maps, i'd suggest creating an issue on that repo: https://github.com/react-native-maps/react-native-maps
