### ISSUE TITLE
Unhandled JS Exception: undefined is not an object (evaluating '(void0).hex')

### ISSUE THREAD

**Issue by beltrancaliz** [expo/expo#1953]
When opening my published the app I get the following error: 
`Unhandled JS Exception: undefined is not an object (evaluating '(void0).hex')`

- I have published the same app in the past without any problems
- The app works fine on development server (LAN, Tunnel, localhost) 
- No errors or warnings show up upon publishing the app

Are there are tips on how to debug this?

### Environment

Environment:
  OS: Windows 7
  Node: 6.9.1
  Yarn: Not Found
  npm: 3.10.8
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

Unknown

### Expected Behavior

The app is published works just in the same way it does on the development server with no errors.

### Actual Behavior

When opening my published the app I get the following error: 
`Unhandled JS Exception: undefined is not an object (evaluating '(void0).hex')`

- I have published the same app in the past without any problems
- The app works fine on development server (LAN, Tunnel, localhost) 
- No errors or warnings show up upon publishing the app

### Reproducible Demo

Can't reproduce

**Comment by brentvatne** [comment]
hello! wiithout a reproducible example or any more specific information about your project, it's impossible to say what could cause this. can you share the expo.io url to your published project where this occurs?

**Comment by beltrancaliz** [comment]
@brentvatne Here is the expo url to the project [https://expo.io/@beltrancaliz/checkplease](https://expo.io/@beltrancaliz/checkplease)

**Comment by brentvatne** [comment]
it turns out that's not so helpful. if you check out a time when you last published it and it worked and publish again, does that resolve the problem? if so, try adding changes back piece-by-piece to determine what commit caused it. then dig deeper into that specific commit, perhaps using a similar strategy. this is just basic debugging stuff, nothing special

**Comment by brentvatne** [comment]
I would also investigate in particular any changes to your babelrc

**Comment by brentvatne** [comment]
if you'd like to share your project source with me I can investigate further but otherwise you'll need to dig into this using the tips I gave above

**Comment by beltrancaliz** [comment]
@brentvatne I had gone through all the previous commits but the issue was with the babelrc, thanks for the tip.
````
{
   "presets": ["babel-preset-expo"],
   "env": {
     "development": {
       "plugins": ["transform-react-jsx-source"]
    },
    "production": {
      "plugins": ["transform-es2015-modules-commonjs"]
     }
   }
 }
````

This was causing the problem:
```
"production": {
     "plugins": ["transform-es2015-modules-commonjs"]
}
```
