### ISSUE TITLE
Linking.parse isn't parsing objects properly

### ISSUE THREAD

**Issue by SohelIslamImran** [expo/expo#19569]
### Summary

`Linking.createURL` and `Linking.parse` from `'expo-linking'`  isn't parsing objects properly. It wrongly parses the object properties.

### What platform(s) does this occur on?

Not Applicable

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
    npmPackages:
      expo: ^46.0.15 => 46.0.15 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    Expo Workflow: managed
```

### Minimal reproducible example

![image](https://user-images.githubusercontent.com/76745339/196034863-cfea589f-7fae-44f3-a9c7-8c4979bed10e.png)

![image](https://user-images.githubusercontent.com/76745339/196034866-fba15d66-5bef-4083-a7d8-9380f2dcc481.png)

```sh
 LOG  Linking.createURL:  exp://192.168.0.102:19000/--/test?testData%255Busername%255D=test&testData%255Bhobby%255D%255Bplayer%255D=true
 LOG  Linking.parse : {"hostname": null, "path": "test", "queryParams": {"testData%5Bhobby%5D%5Bplayer%5D": "true", "testData%5Busername%5D": "test"}, "scheme": "exp"}
```

**Comment by gabrieldonadel** [comment]
@SohelIslamImran from my investigation it seems that `Linking.createURL` does not support nested objects as `queryParams`. In fact, it even throws a type error when a try to create such an URL.
![image](https://user-images.githubusercontent.com/11707729/196069196-46dd8ea1-f4a1-40fb-8558-0d89e33ba885.png)
![image](https://user-images.githubusercontent.com/11707729/196069182-f7452ba5-6566-4509-a214-4433b001a564.png)

One thing that you can do to circumvent this is stringifying your all your nested `queryParams` using [qs](https://www.npmjs.com/package/qs), e.g.
```js
// when creating your URL 
 let testURL = Linking.createURL('test', {
    queryParams: {
      testData: qs.stringify({
        username: 'test',
        hobby: {
          player: true,
        },
      }),
    },
 });


// and then when receiving the URL you just need to do the reverse process
  const parsedURL = Linking.parse(testURL);  
  if (parsedURL.queryParams) {
    Object.entries(parsedURL.queryParams).forEach(([key, value]) => { 
      if (typeof value === 'string') {
        console.log(`${key}:`, qs.parse(value));
      }
    });
  } 
```

**Comment by SohelIslamImran** [comment]
@gabrieldonadel Thank you. But I think it should support. Please add support.
