### ISSUE TITLE
status bar getting stretched when came back from launched SDK in ios.

### ISSUE THREAD

**Issue by shailesh-galgal** [expo/expo#19572]
### Summary

How to reproduce-
1.create a expo project & make it "expo prebuild"
2.Add SDK ,in my case [()](https://support.freshchat.com/en/support/solutions/articles/50000000467-freshchat-react-native-sdk-integration-steps)
3.refer above sdk doc & integrate it.
4.do expo run:ios

Doing this 
whats expected is ,whenever you will launch the sdk & came back to your app in ios,it stretches you status bar.

![Simulator Screen Shot - iPhone 14 Pro - 2022-10-10 at 17 46 04](https://user-images.githubusercontent.com/103997028/196051239-e0aa5e74-7c74-4fde-93b0-b0d3e089828c.png)

### What platform(s) does this occur on?

iOS

### Environment

it only happens on iOS.

### Minimal reproducible example

1.create a expo project & make it "expo prebuild"
2.Add SDK ,in my case [(freshdesk)](https://support.freshchat.com/en/support/solutions/articles/50000000467-freshchat-react-native-sdk-integration-steps)
3.refer above sdk doc & integrate it.
4.do expo run:ios

**Comment by shailesh-galgal** [comment]
we are using `react-native-safe-area-context`

**Comment by keith-kurak** [comment]
Hi!

It's hard to tell from this if this is a bug with Expo tools or the Freshdesk SDK. If you can reproduce the issue in a git repo or Snack without that SDK, feel free to submit a new issue. Thanks!
