### ISSUE TITLE
MediaLibrary.getAssetInfoAsync with apk on real device never returns

### ISSUE THREAD

**Issue by tomgiam** [expo/expo#19583]
### Summary

The following code:

`const assetInfo = await MediaLibrary.getAssetInfoAsync(images[i].id);`

Works correctly on real Android device (Samsung S20+) with expo go, but on the same device with with an apk it never returns.

I also tried 

`const assetInfo = await MediaLibrary.getAssetInfoAsync(images[i].id, {});`

and

`const assetInfo = await MediaLibrary.getAssetInfoAsync(images[i].id, {shouldDownloadFromNetwork: true});`

The apk is generated using eas build:

`eas build -p android --profile preview`

On iOS it also works on a real device with expo go, but I have not tried it on iOS with an eas build, because I'm waiting for apple to approve the app.

I need this to get the location data. Is there any other way?

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE       
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6200805
    npmPackages:
      expo: ^46.0.15 => 46.0.15
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Minimal reproducible example

I can't generate a snack example that fails, because It works in expo go.

**Comment by jakeboyles** [comment]
+ 1

**Comment by jakeboyles** [comment]
Getting the same issue and its driving me insane
