### ISSUE TITLE
Android: Failed to construct transformer:  TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by keung7252** [expo/expo#19582]
### Summary

When I eas build android, it failed and displays below error:

Failed to construct transformer:  TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received undefined

https://expo.dev/accounts/playmore/projects/msstaff/builds/4422cdd1-f50f-4c0a-b5df-86613562fc60

{
  "dependencies": {
    "@expo/react-native-action-sheet": "^3.13.0",
    "@neverdull-agency/expo-unlimited-secure-store": "^1.0.10",
    "@openspacelabs/react-native-zoomable-view": "^2.0.4",
    "@react-native-community/cli-server-api": "^7.0.3",
    "@react-native-community/datetimepicker": "4.0.0",
    "@react-native-community/netinfo": "7.1.3",
    "@react-native-picker/picker": "2.2.1",
    "@react-navigation/drawer": "^6.1.4",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@reduxjs/toolkit": "^1.6.1",
    "@sentry/react-native": "^4.6.1",
    "axios": "^0.21.4",
    "expo": "^44.0.0",
    "expo-application": "~4.0.1",
    "expo-av": "~10.2.0",
    "expo-barcode-scanner": "~11.2.0",
    "expo-blur": "~11.0.0",
    "expo-cached-image": "^46.0.1",
    "expo-camera": "~12.1.2",
    "expo-checkbox": "~2.0.0",
    "expo-constants": "~13.0.1",
    "expo-device": "~4.1.0",
    "expo-draw": "git+https://github.com/MarangoniEduardo/expo-draw",
    "expo-file-system": "~13.1.4",
    "expo-firebase-analytics": "~6.0.0",
    "expo-image-picker": "~12.0.1",
    "expo-localization": "~12.0.0",
    "expo-media-library": "~14.0.0",
    "expo-next-react-navigation": "^1.2.1",
    "expo-notifications": "~0.14.0",
    "expo-ota-manager": "^1.1.4",
    "expo-print": "~11.1.0",
    "expo-screen-orientation": "~4.1.1",
    "expo-secure-store": "~11.1.0",
    "expo-sharing": "~10.1.0",
    "expo-sqlite": "~10.1.0",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "~0.11.7",
    "firebase": "8.2.3",
    "i18next": "^20.6.0",
    "install": "^0.13.0",
    "moment": "^2.29.1",
    "native-base": "^3.1.0",
    "next": "^11.0.1",
    "next-fonts": "^1.5.1",
    "next-images": "^1.8.1",
    "nextjs-progressbar": "^0.0.11",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.11.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-big-list": "^1.5.4",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-custom-qr-codes-expo": "^2.2.0",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-htmlview": "^0.16.0",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^13.1.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-scalable-image": "^1.1.0",
    "react-native-screens": "~3.10.1",
    "react-native-signature-canvas": "^4.3.0",
    "react-native-slick": "^1.6.0",
    "react-native-svg": "12.1.1",
    "react-native-view-shot": "3.1.2",
    "react-native-web": "^0.17.1",
    "react-native-webview": "11.15.0",
    "react-native-youtube-iframe": "^2.1.2",
    "react-redux": "^7.2.4",
    "redux": "^4.1.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "rn-pdf-reader-js": "^4.1.1",
    "sentry-expo": "^4.0.0",
    "styled-components": "^5.3.1",
    "styled-system": "^5.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@expo/next-adapter": "^3.0.1",
    "@types/react-native": "~0.64.12",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^8.0.0",
    "prettier": "2.4.1"
  },
  "resolutions": {
    "metro": "0.70.1"
  },
  "scripts": {
    "start": "next dev",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build": "next build"
  },
  "private": true
}

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "dependencies": {
    "@expo/react-native-action-sheet": "^3.13.0",
    "@neverdull-agency/expo-unlimited-secure-store": "^1.0.10",
    "@openspacelabs/react-native-zoomable-view": "^2.0.4",
    "@react-native-community/cli-server-api": "^7.0.3",
    "@react-native-community/datetimepicker": "4.0.0",
    "@react-native-community/netinfo": "7.1.3",
    "@react-native-picker/picker": "2.2.1",
    "@react-navigation/drawer": "^6.1.4",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@reduxjs/toolkit": "^1.6.1",
    "@sentry/react-native": "^4.6.1",
    "axios": "^0.21.4",
    "expo": "^44.0.0",
    "expo-application": "~4.0.1",
    "expo-av": "~10.2.0",
    "expo-barcode-scanner": "~11.2.0",
    "expo-blur": "~11.0.0",
    "expo-cached-image": "^46.0.1",
    "expo-camera": "~12.1.2",
    "expo-checkbox": "~2.0.0",
    "expo-constants": "~13.0.1",
    "expo-device": "~4.1.0",
    "expo-draw": "git+https://github.com/MarangoniEduardo/expo-draw",
    "expo-file-system": "~13.1.4",
    "expo-firebase-analytics": "~6.0.0",
    "expo-image-picker": "~12.0.1",
    "expo-localization": "~12.0.0",
    "expo-media-library": "~14.0.0",
    "expo-next-react-navigation": "^1.2.1",
    "expo-notifications": "~0.14.0",
    "expo-ota-manager": "^1.1.4",
    "expo-print": "~11.1.0",
    "expo-screen-orientation": "~4.1.1",
    "expo-secure-store": "~11.1.0",
    "expo-sharing": "~10.1.0",
    "expo-sqlite": "~10.1.0",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "~0.11.7",
    "firebase": "8.2.3",
    "i18next": "^20.6.0",
    "install": "^0.13.0",
    "moment": "^2.29.1",
    "native-base": "^3.1.0",
    "next": "^11.0.1",
    "next-fonts": "^1.5.1",
    "next-images": "^1.8.1",
    "nextjs-progressbar": "^0.0.11",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.11.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-big-list": "^1.5.4",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-custom-qr-codes-expo": "^2.2.0",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-htmlview": "^0.16.0",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^13.1.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-scalable-image": "^1.1.0",
    "react-native-screens": "~3.10.1",
    "react-native-signature-canvas": "^4.3.0",
    "react-native-slick": "^1.6.0",
    "react-native-svg": "12.1.1",
    "react-native-view-shot": "3.1.2",
    "react-native-web": "^0.17.1",
    "react-native-webview": "11.15.0",
    "react-native-youtube-iframe": "^2.1.2",
    "react-redux": "^7.2.4",
    "redux": "^4.1.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "rn-pdf-reader-js": "^4.1.1",
    "sentry-expo": "^4.0.0",
    "styled-components": "^5.3.1",
    "styled-system": "^5.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@expo/next-adapter": "^3.0.1",
    "@types/react-native": "~0.64.12",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^8.0.0",
    "prettier": "2.4.1"
  },
  "resolutions": {
    "metro": "0.70.1"
  },
  "scripts": {
    "start": "next dev",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build": "next build"
  },
  "private": true
}

### Environment

 System:
      OS: macOS 12.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28, 29, 30, 31
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3 
      react-native-web: ^0.17.1 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.3.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Reproducible demo

https://expo.dev/accounts/playmore/projects/msstaff/builds/4422cdd1-f50f-4c0a-b5df-86613562fc60

**Comment by tcdavis** [comment]
Are you using an M1 mac locally?
https://stackoverflow.com/questions/69647332/cannot-read-properties-of-undefined-reading-transformfile-at-bundler-transfo
https://github.com/facebook/react-native/issues/33107

**Comment by keung7252** [comment]
> 

@tcdavis  I am not using M1 mac

**Comment by keung7252** [comment]
I solved the problem. It is because of android package name in app.json.
It should be com.xxx.xxx.xxx rather than  com.xxx.xxx.xxx.xxx

**Comment by michakfromparis** [comment]
Bumping into the same issue with metro bundling. Running on an M2, tried to downgrade node although I think these 2 recommandations are not relevant anymore

**Comment by estani** [comment]
Same issue here, the local node version should have nothing to do, since this is built in EAS Servers, right? Not sure which node version is used there though, but certainly no M1 or M2 Chipsets will be used... (might this mean that android is built in M1/M2? https://blog.expo.dev/eas-build-will-require-using-m1-m2-builders-this-fall-df40e8a9e930)

I did downgrade node just to check, but it did nothing beside some issues with git that I overcome by slipping the step with `EAS_NO_VCS=1`.

I'm still using the free tier, so it takes a while to check how to fix the error, but it looks like an EAS side error...

**Comment by ebulku** [comment]
I am having the same problem, this is the full error log:

```
...
> Task :expo-clipboard:compileReleaseJavaWithJavac

> Task :expo-clipboard:bundleLibCompileToJarRelease

> Task :app:createBundleReleaseJsAndAssets FAILED

[stderr] 

Failed to construct transformer:  TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received undefined

[stderr] 

    at new NodeError (node:internal/errors:387:5)

[stderr] 

    at validateString (node:internal/validators:162:11)

[stderr] 

    at Function.resolve (node:internal/modules/cjs/helpers:108:5)

[stderr] 

    at Object.getCacheKey (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:532:15)

[stderr] 

    at getTransformCacheKey (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/getTransformCacheKey.js:23:19)

[stderr] 

    at new Transformer (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Transformer.js:47:9)

[stderr] 

    at /home/expo/workingdir/build/node_modules/metro/src/Bundler.js:25:29

[stderr] 

    at runMicrotasks (<anonymous>)

[stderr] 

    at processTicksAndRejections (node:internal/process/task_queues:96:5) {

[stderr] 

  code: 'ERR_INVALID_ARG_TYPE'

[stderr] 

}

[stderr] 

TypeError: Cannot read properties of undefined (reading 'transformFile')

[stderr] 

TypeError: Cannot read properties of undefined (reading 'transformFile')

[stderr] 

    at Bundler.transformFile (/home/expo/workingdir/build/node_modules/metro/src/Bundler.js:60:30)

[stderr] 

    at runMicrotasks (<anonymous>)

[stderr] 

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[stderr] 

    at async Object.transform (/home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:147:12)

[stderr] 

    at async Graph._processModule (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:214:20)

[stderr] 

    at async Graph._traverseDependenciesForSingleFile (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:207:5)

[stderr] 

    at async Promise.all (index 0)

[stderr] 

    at async Graph.initialTraverseDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:191:5)

[stderr] 

    at async DeltaCalculator._getChangedDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:196:25)

[stderr] 

    at async DeltaCalculator.getDelta (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:90:16)

> Task :react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a]

> Task :expo-dev-menu:compileReleaseKotlin
...
```

**Comment by brentvatne** [comment]
if you are encountering this error, check if you have any reoslutions/overrides set for `metro` in your **package.json** and delete them

**Comment by ebulku** [comment]
@brentvatne yes you are right, as i remember I removed these lines from **package.json** and it worked:

  ```
"resolutions": {
    "metro": "^0.73.7",
    "metro-resolver": "^0.73.7"
  },
  "overrides": {
    "metro": "^0.73.7",
    "metro-resolver": "^0.73.7"
  },
```

**Comment by raajnadar** [comment]
> if you are encountering this error, check if you have any reoslutions/overrides set for `metro` in your **package.json** and delete them

I got those in the `package.json` when I used the following cmd `npx create-expo-app -e with-router`
