### ISSUE TITLE
"CLEARTEXT" not permitted by network security policy

### ISSUE THREAD

**Issue by martijnarts** [expo/expo#19585]
### Summary

I've been working with a managed workflow dev-client build for a while now. Just added the `expo-sensors` package and ran an `eas build --profile development --platform android`. After building and installing the new dev client, I can't connect to Metro anymore, getting this error: "CLEARTEXT communication to 192.168.1.149 not permitted by network security policy". It also happens when I try to connect using `expo start --tunnel`.

I'm definitely out of my depth, and fully blocked now 😔. Any idea what could be causing this? Have I done something wrong?

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

Some relevant versions:
```
    "expo-dev-client": "~1.0.1",
    "expo-updates": "~0.13.4",
    "expo": "^45.0.0",
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 3.2.3 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 2.4.1
      expo-cli: 6.0.6
    Expo Workflow: managed
```

### Reproducible demo

I'd love to create a reproducible demo, but I don't think I can. I reinstalled the previous dev build and that didn't fix the problem. As such, it seems to be unrelated to my build.

### Stacktrace (if a crash is involved)

<img src="https://user-images.githubusercontent.com/54749/196192531-69b21f9c-dc56-4934-96cf-8eb7204434f4.jpeg" width="50%" /><img src="https://user-images.githubusercontent.com/54749/196192540-e8ac7fb2-b0cb-4c6e-a361-959d8586f171.jpeg" width="50%" />

**Comment by martijnarts** [comment]
I'm pretty sure it's an issue with the Detox config plugin, where I needed to set the `subdomains` setting. I'll double check that and then probably PR to add some troubleshooting to its README.

**Comment by martijnarts** [comment]
Cool, this was the fix:

```javascript
      [
        '@config-plugins/detox',
        {
          subdomains: '*',
        },
      ],
```

in `app.config.js` (or `app.json`)

**Comment by martijnarts** [comment]
Created https://github.com/expo/config-plugins/pull/125 to make this searchable.

**Comment by richyk1** [comment]
@martijnarts Thank you so much!1! I would have never fixed this issue without your thread lol

**Comment by jasondavis87** [comment]
This helped me too. I was using an NX workspace with an expo managed project and detox is installed by default. Wouldnt have found the fix w/o this thread.

**Comment by murilo-alvesmelo** [comment]
This worked for me:

android>app>src> debug

<uses-permission android:name="android.permission.NEARBY_WIFI_DEVICES"/>

**Comment by ghasemikasra39** [comment]
> Cool, this was the fix:
> 
>       [
>         '@config-plugins/detox',
>         {
>           subdomains: '*',
>         },
>       ],
> in `app.config.js` (or `app.json`)

This worked for me for expo SDK 52, react-native": "0.76.9, with dev client.

**Comment by NatalNineITSolutions** [comment]
[
    '@config-plugins/detox',
    {
      subdomains: '*',
    },
  ],

This works for me Thanks dude @martijnarts

**Comment by chaitanya71998** [comment]
does this works for development build?

**Comment by RemyNtshaykolo** [comment]
THANK YOU!!!

> Cool, this was the fix:
> 
>       [
>         '@config-plugins/detox',
>         {
>           subdomains: '*',
>         },
>       ],
> in `app.config.js` (or `app.json`)
