### ISSUE TITLE
Unable to use custom font with `Expo.Svg.Text`

### ISSUE THREAD

**Issue by zschiller** [expo/expo#1959]
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.9.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/zschiller-1159e596-d038-4375-aaae-acea46431b66.tar.gz
```

### Steps to Reproduce

I'm trying to use a custom font loaded with `Font.loadAsync` on an `Svg.Text` element.

1. Load the font using `Font.loadAsync`
2. Render the font using a React Native `Text` element to verify it is loaded
3. Try to apply the font to `Svg.Text` using the `fontFamily` prop

### Expected Behavior

The `Svg.Text` element renders with the custom font I specified.

### Actual Behavior

The `Svg.Text` element renders with a default font, Helvetica.

![img_154d184cd06a-1](https://user-images.githubusercontent.com/13790148/42387924-dd4690d8-8111-11e8-938a-90067b163341.jpeg)

### Reproducible Demo

https://snack.expo.io/ByOzCbaz7

**Comment by brentvatne** [comment]
@schazers - I think this might actually be a bug with our fonts

**Comment by schazers** [comment]
Ah, so sorry @zschiller !! Thanks brent

**Comment by virus2016** [comment]
Any update on this one? Having the same issue...

**Comment by devtanc** [comment]
I'm having this issue as well. Seems that the font doesn't get passed correctly to react-native-svg or something, since they claim that custom fonts work as of 6.0.0^.

**Comment by executives** [comment]
I'm experiencing a similar problem, may be the same, for Android. Here is my setup:

In my TabNavigator Component:

```javascript
    import { Font } from 'expo';
    async componentDidMount() {
      await Font.loadAsync({
        'Lato-Regular': require('../../assets/fonts/Lato-Regular.ttf'),
        'Lato-Black': require('../../assets/fonts/Lato-Black.ttf')
      });
    }
```
In a TabScreen display component:
    
```javascript
    import { Svg } from 'expo';
    <Svg height="240" width="200" style={{ backgroundColor: 'white' }}>
      <Svg.Defs>
        <Svg.LinearGradient id="rainbow" x1="0" x2="100%" y1="0" y2="100%" gradientUnits="userSpaceOnUse">
          <Svg.Stop stopColor="#BCF9CA" offset="0%" />
          <Svg.Stop stopColor="#109B2F" offset="100%" />
        </Svg.LinearGradient>
      </Svg.Defs>
    
      <Svg.Text fill="url(#rainbow)" fontFamily="Lato-Regular" fontSize="300" fontWeight="bold" x="50%" y="85%" textAnchor="middle">
        0
      </Svg.Text>
    </Svg>
    
    <Text>DataNumber</Text>
    <Text style={{ fontFamily: 'Lato-Regular'}}>Custom font in use</Text>
```


I can get the 2nd `<Text>` component to render the custom 'Lato-Regular' fontFamily OK. The `<Svg.Text>` component renders system default and not the 'Lato-Regular' fontFamily specified.

**Comment by tal2** [comment]
I'm having this issue as well.
Currently using SDK v31.

**Comment by obetomuniz** [comment]
Same issue here. Currently using SDK v31.

**Comment by devtanc** [comment]
I really need this to be working and I am still not able to load custom fonts into SVG. Just tried out v31 to check for this very fix. Fonts show up fine in `Text` elements, but not in `Svg.Text`.

**Comment by tal2** [comment]
Here is a **workaround**, for anyone interested:

Basically, with this solution you load the font file and use an external package (opentype.js) to convert text to a SVG Path. Depending on your usage, you might want to use some caching techniques as well.

**First**, get the [opentype.js](https://www.npmjs.com/package/opentype.js) package.

**Second**, load the font.

Here is a simplified version of my code:
(I did not test it after making modifications for this comment)
```
/* This function is synchronous to keep it simple.
 * You might want to make it asynchronous and return a promise that will be resolved
 * inside the opentype.load callback.
 */

export function loadFont(fontModule) {
  const result = {}

  const file = Asset.fromModule(fontModule)

  opentype.load(file.uri, function(err, font) {
    if (err) {
       // handle error
    }
    result.loadedFont = font
  })

  return result
}
```

Here's an **example** how to use it:

```
const {loadedFont} = loadFont(
  require(`./assets/fonts/<font-file-name>.ttf`)
)

const SvgComponent = ({width, height, text, x, y, fontSize}) => {
  const path = loadedFont.getPath((
    text,
    0,        // x: Horizontal position of the beginning of the text
    fontSize, // y: Vertical position of the baseline of the text
    fontSize  // fontSize: Size of the text in pixels
  ))

  const pathData = path.toPathData()

  return (
    <Svg width={width} height={height}>
      <Svg.Path
        x={x}
        y={y}
        strokeWidth={2}
        d={pathData}
      />
    </Svg>
  )
}
```

**Comment by javi10823** [comment]
same problem!

**Comment by devtanc** [comment]
@tal2 I don't _love_ that workaround, but I'll try it and hope it works. Thanks for posting!

**Comment by mortenc** [comment]
I'm experiencing the same problem (on SDK v31 as well). Any updates on whether this issue is being worked on?

**Comment by xanderiel** [comment]
One ugly workaround is to use overlay a normal `Text` element on top of your SVG using `position: absolute` and `zIndex: 1/2/3/4/5`.
Would love to see this fixed.

**Comment by AOEChamp** [comment]
I'm also experiencing this issue. @tal2 's workaround is functional but far from ideal. Official word on this would be greatly appreciated.

**Comment by nathansimpsondesign** [comment]
Also experiencing this issue. I'm glad I'm not the only one!

**Comment by spyshower** [comment]
I am **genuinely** wondering how (simple?) issues like this exist for so long.

**Comment by tcdavis** [comment]
Imagine the number of such seemingly simple issues on this project: https://github.com/expo/expo/issues

Now imagine the number of things that aren't in that list but it would be really great if you could do them: 
https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331
https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375

And think about the number of people who draw a paycheck to make it better:
https://expo.io/about 

Sorry we haven't found time to get this resolved yet, thanks to everyone for letting us know, and special thanks to @tal2 for finding and sharing a workaround to keep everyone unblocked.  If anyone would be interested in helping get this (or any other issues you run into) fixed, please let us know!

**Comment by spyshower** [comment]
First of all I have no intention to ruin this thread with unrelated stuff, this comment has nothing to do with the issue itself.

I feel that RN or Expo (not sure about who does what really) don't approach the development in a hierarchical way. There are so many issues that should have been fixed, but instead I am seeing Expo for web? Why? Seriously, are you porting React Native to web when React operates there...? I hope I am missing something important here. Reminds me of the countless problems of Apollo and they can't stop posting on their blog about their new toys...

And regarding the payment of the people actively working on them (which again I have no idea what's going on), I totally get that you are not working for Google or w/e to get that sweet cash, but I believe some help/bugfixes for 'simple' things isn't all that hard. I have posted several times here and on official Expo forums that the project feels abandoned sometimes.

Please take this as feedback; burn it or keep it.

**Comment by brentvatne** [comment]
hey @spyshower, thanks for the feedback. indeed there are a thousand small cuts, we have to do what we can to prioritize the most important issues while also pushing forward with where we want to take the product. we feel that supporting web is important to get started on because its a big hill to climb and very little work is actively being done in the space at the moment. similarly, we thought it was important to work on decoupling apis from each other and from expo in order to make the process of ejecting smoother and to open up access to the libraries we've built to the broader react-native community and hybrid development community in general, so we can collaborate more and reduce duplicated efforts.

in cases like svg, we have to depend on the community around react-native to improve underlying tools because we don't have the bandwidth internally to handle it. we depend on react-native-svg to provide these capabilities. if you would like to fix the issue yourself, fund the maintainer of react-native-svg to do it, or fund a contractor to do it, we would absolutely encourage that, and we can recommend folks who can help you. when it comes down to it, you can use expo for free and almost all of the code is open source, so you too can participate and help make this happen if you believe in the idea.

> I have posted several times here and on official Expo forums that the project feels abandoned sometimes.

is this because we haven't prioritized some of the issues that you care about most? if you just glance at our open source code in this repository (one of many that we maintain) you can see a bunch of activity every day: https://github.com/expo/expo/commits/master. @A-Nav is constantly out answering questions on forums and so on.

if you'd like to chat more about how we can do a better job i'd be happy to do a call sometime.

**Comment by evanheckert** [comment]
@brentvatne I appreciate the patient, well-thought-out reply. Just wanted to check if I'm understanding this thread correctly that it is an expo issue here and not react-native-svg issue? And right now the workaround that tal2 mentioned is the only option? Thanks again!

**Comment by dnr** [comment]
Also running into the same issue. Expo 37.0.6 in managed mode, react-native 0.61.4, react-native-svg 11.0.1. It seems like there's still some confusion about whether the issue is in Expo or react-native-svg. Maybe it would help for someone from each project to talk for a minute and at least figure out which project is responsible?

> if you would like to fix the issue yourself, fund the maintainer of react-native-svg to do it, or fund a contractor to do it, we would absolutely encourage that, and we can recommend folks who can help you.

@brentvatne If I wanted to pay someone to fix this bug, where would I start?

**Comment by gabrielste1n** [comment]
I am also having the same issue Expo ^37.0.0, after looking at the react-native-svg threads it seems that the react-native-svg team are adamant it is an issue with Expo and that they have fixed everything on their side. I'm with @dnr about paying someone to fix this bug because I need this to work asap.

**Comment by brentvatne** [comment]
@gabrielste1n - perhaps someone could send a PR to react-native-svg to make it compatible with [expo-font](https://github.com/expo/expo/tree/master/packages/expo-font)? this would be much appreciated, we don't have bandwidth to work on this right now internally.

**Comment by t1gu1** [comment]
Same issue with SDK ^39.0.0 🥺

**Comment by NikitaDudin** [comment]
Expo sdk v40. Works with `processFontFamily` from expo-fonts:
`...<Svg.Text fontFamily={processFontFamily('Manrope_200ExtraLight')}>{text}</Svg.Text>...`
default system family[iOS]:
![d](https://user-images.githubusercontent.com/25579397/108137441-e99dbc00-70cc-11eb-9f07-75dfa9e73b3e.png)

Manrope_200ExtraLight[iOS]:
![m](https://user-images.githubusercontent.com/25579397/108137450-ed314300-70cc-11eb-831f-c981887d7473.png)

**Comment by outaTiME** [comment]
Interesting, it only works on managed workflow but why is it not documented @brentvatne? Will its use have unwanted effects? does this work on Android too?

here the code:

https://github.com/expo/expo/blob/45dd06df4c3d844e8adf774207d64015e76ec902/packages/expo-font/src/Font.ts#L25

**Comment by NikitaDudin** [comment]
> does this work on Android too?

yes, tested only on managed workflow.

**Comment by Hirbod** [comment]
Finally found an answer
```<Text fontFamily={processFontFamily("gothic-bold")} />``` fixed the issue! Yay!
