### ISSUE TITLE
expo-yarn-workspaces is now deprecated and doesn't work with SDK46

### ISSUE THREAD

**Issue by edjiang** [expo/expo#19591]
### Summary

expo-yarn-workspaces no longer works with SDK46 but it's not documented anywhere in the changelog / release notes (and npm reports a recent update). The guide implies that it's no longer necessary but doesn't tell you to remove it

Relevant pages:

https://docs.expo.dev/guides/monorepos/
https://github.com/expo/expo/blob/main/packages/expo-yarn-workspaces/CHANGELOG.md
https://github.com/expo/expo/blob/main/CHANGELOG.md

### Link to the related docs page

https://github.com/expo/expo/blob/master/packages/expo-yarn-workspaces/CHANGELOG.md

**Comment by iway1** [comment]
this is because expo works out of the box with yarn workspaces now and you shouldn't use the package https://docs.expo.dev/guides/monorepos/

**Comment by amandeepmittal** [comment]
Hey @edjiang,

Thanks for bringing this up. We'll update the docs to reflect that.
