### ISSUE TITLE
[!] There are multiple dependencies with different sources for ExpoModulesCore in Podfile:

### ISSUE THREAD

**Issue by pascal-maker** [expo/expo#19598]
### Summary

I'm not able to run pod install in my podfile. This Is my podfile when i try to cd ios && pod install --repo-update i get this error [!] There are multiple dependencies with different sources for ExpoModulesCore in Podfile:
ExpoModulesCore
ExpoModulesCore (from ../node_modules/expo/node_modules/expo-modules-core/ios)

This is my Podfile:
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.4'

$FirebaseSDKVersion = '10.0.0'

target 'Instadating' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(
    :path => config[:"reactNativePath"]
  )
  pod 'ExpoModulesCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
 use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  use_unimodules!
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
 
end

### What platform(s) does this occur on?

iOS

### SDK Version

16.17.1

### Environment

System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.10.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
      Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild

### Minimal reproducible example

1) copy this podfile and download the repo https://github.com/pascal-maker/Lovia-master-2-master-master
2)Open Terminal
3)cd to the repo
4)cd ios
5)pod install --repo-update

**Comment by whybtech** [comment]
In my case, this error was due to ios config in expo-build-properties adding extra pods (identified by line `Adding extra pod - ExpoModulesCore (*)` in install logs)
```json
[
    "expo-build-properties",
    {
        "ios": {
            "useFrameworks": "static",
            "extraPods": [
                {"name": "ExpoModulesCore", "modular_headers": true}
            ]
        }
    }
]
```
Since I upgrade to SDK 50 (from 49.0.0), this temporary fix was not needed anymore so I only had to remove it
