### ISSUE TITLE
Execution failed for task ':expo-modules-core:downloadBoost'

### ISSUE THREAD

**Issue by vladis-c** [expo/expo#19596]
### Summary

When running `npx expo run:android` android build fails with this error. See logs:
<img width="1247" alt="Screenshot 2022-10-18 at 10 59 52" src="https://user-images.githubusercontent.com/93081212/196372861-361a06d7-c20e-451b-9578-841843d89d66.png">

Tried to install `expo-modules-core` explicitly.
Tried upgrading Gradle plugin from 7.1.1 up to 7.3.3 and 7.5.

Did not find any more solutions on the internet.

Any idea what to do?

### What platform(s) does this occur on?

Android

### SDK Version

46

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.4.0 => 0.4.0 
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.4.1
      expo-cli: 6.0.6
    Expo Workflow: bare
```

### Minimal reproducible example

Package.json

```
{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll",
    "debug": "open 'rndebugger://set-debugger-loc?host=localhost&port=19000'",
    "debug dev": "open 'rndebugger://set-debugger-loc?host=localhost&port=8081'"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo-google-fonts/raleway": "^0.2.2",
    "@expo/config-plugins": "^5.0.0",
    "@expo/metro-config": "^0.4.0",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-masked-view/masked-view": "0.2.7",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "@react-navigation/stack": "^6.3.1",
    "@reduxjs/toolkit": "^1.8.5",
    "@rneui/base": "^4.0.0-rc.6",
    "@rneui/themed": "^4.0.0-rc.6",
    "@sentry/react-native": "4.2.2",
    "@stripe/stripe-react-native": "^0.19.0",
    "dotenv": "^16.0.2",
    "expo": "~46.0.16",
    "expo-app-loading": "~2.1.0",
    "expo-apple-authentication": "~4.3.0",
    "expo-application": "~4.2.2",
    "expo-background-fetch": "~10.3.0",
    "expo-build-properties": "~0.3.0",
    "expo-camera": "~12.3.0",
    "expo-constants": "~13.2.4",
    "expo-dev-client": "1.3.1",
    "expo-device": "~4.3.0",
    "expo-image-loader": "~3.2.0",
    "expo-image-manipulator": "~10.4.0",
    "expo-image-picker": "~13.3.1",
    "expo-keep-awake": "~10.2.0",
    "expo-linear-gradient": "~11.4.0",
    "expo-local-authentication": "~12.3.0",
    "expo-media-library": "~14.2.0",
    "expo-modules-autolinking": "~0.10.1",
    "expo-notifications": "~0.16.1",
    "expo-screen-capture": "~4.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-system-ui": "~1.3.0",
    "expo-task-manager": "~10.3.0",
    "expo-updates": "~0.14.6",
    "expo-web-browser": "~11.0.0",
    "firebase": "^9.10.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-agora": "^3.7.1",
    "react-native-bouncy-checkbox": "^3.0.4",
    "react-native-calendars": "^1.1289.0",
    "react-native-date-picker": "^4.2.5",
    "react-native-dotenv": "^3.3.1",
    "react-native-element-dropdown": "^2.3.0",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-gifted-chat": "^1.0.4",
    "react-native-paper": "^4.12.5",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "~3.15.0",
    "react-native-svg": "12.3.0",
    "react-native-toast-message": "^2.1.5",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0",
    "react-redux": "^8.0.4",
    "redux": "^4.2.0",
    "redux-saga": "^1.2.1",
    "redux-thunk": "^2.4.1",
    "sentry-expo": "~5.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@types/react": "~18.0.0",
    "@types/react-dom": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "@types/react-redux": "^7.1.24",
    "expo-module-scripts": "^2.1.1",
    "jest": "^26.6.3",
    "jest-expo": "^46.0.0",
    "react-test-renderer": "^18.2.0",
    "remote-redux-devtools": "^0.5.16",
    "typescript": "^4.8.4"
  },
  "resolutions": {
    "standard-version-expo/**/@expo/config-plugins": "4.1.0",
    "@types/react": "~18.0.0",
    "@types/react-dom": "~18.0.0",
    "@types/react-native": "~0.69.1"
  },
  "private": true,
  "name": "hammashelppi-app",
  "version": "2.0.0"
}
```

app.json

```
{
  "expo": {
    "name": "Hammashelppi",
    "slug": "hammashelppi",
    "version": "2.0.0",
    "orientation": "portrait",
    "icon": "./images/HH_Logo.png",
    "splash": {
      "image": "./images/HH_splash_image.png",
      "resizeMode": "contain",
      "backgroundColor": "#107CA2"
    },
    "userInterfaceStyle": "light",
    "developmentClient": {
      "silentLaunch": true
    },
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": [
        "expo.ts",
        "expo.tsx",
        "expo.js",
        "expo.jsx",
        "ts",
        "tsx",
        "js",
        "jsx",
        "json",
        "wasm",
        "svg"
      ]
    },
    "updates": {
      "fallbackToCacheTimeout": 300000,
      "enabled": true,
      "url": "https://u.expo.dev/****"
    },
    "assetBundlePatterns": ["**/*"],
    "web": {
      "favicon": "./images/favicon.png"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "hammashelppi",
            "project": "hammashelppi",
            "authToken": "***"
          }
        }
      ]
    },
    "plugins": [
      [
        "@stripe/stripe-react-native",
        {
          "merchantIdentifier": "***",
          "enableGooglePay": true
        }
      ],
      [
        "expo-image-picker",
        {
          "photosPermission": "Allow Hammashelppi to access your gallery.",
          "cameraPermission": "Allow Hammashelppi to access your camera."
        }
      ],
      ["expo-camera"],
      [
        "expo-notifications",
        {
          "icon": "./images/HH_android_notifications_white.png",
          "color": "#107CA2",
          "mode": "production"
        }
      ],
      "sentry-expo",
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 33,
            "targetSdkVersion": 31,
            "buildToolsVersion": "30.0.2",
            "kotlinVersion": "1.7.10"
          }
        }
      ]
    ],
    "android": {
      "icon": "./images/HH_android_logo_old.png",
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./images/HH_android_logo.png",
        "backgroundColor": "#107CA2"
      },
      "package": "***",
      "versionCode": 15,
      "permissions": [
        "NOTIFICATIONS",
        "CAMERA",
        "READ_EXTERNAL_STORAGE",
        "RECORD_AUDIO",
        "android.permission.RECORD_AUDIO",
        "android.permission.CAMERA"
      ],
      "useNextNotificationsApi": true
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "***",
      "infoPlist": {
        "NSFaceIDUsageDescription": "Face ID is used for authentication",
        "UIBackgroundModes": ["fetch", "remote-notification"]
      },
      "buildNumber": "15",
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "runtimeVersion": "2.0.0",
    "extra": {
      "eas": {
        "projectId": "***"
      }
    }
  }
}
```

eas.json
```
{
  "cli": {
    "version": ">= 0.52.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",    
    },
    "development-android": {
      "extends": "development",
      "android": {
        "buildType": "apk",
        "gradleCommand": ":app:assembleRelease"
      }
    },
    "development-ios": {
      "extends": "development",
      "ios": {
        "enterpriseProvisioning": "universal"
      },
      "cache": {
        "key": "18999"
      }
    },

    "preview-android": {
      "extends": "development",
      "channel": "preview-android",
      "developmentClient": false,
      "android": {
        "buildType": "app-bundle",
        "gradleCommand": ":app:bundleRelease"
      }
    },
    "preview-ios": {
      "extends": "development",
      "channel": "preview-ios",
      "developmentClient": false,
      "ios": {
        "enterpriseProvisioning": "universal",
        "image": "latest"
      },
      "cache": {
        "key": "18999"
      }
    },

    "production-android": {
      "extends": "development",
      "distribution": "store",
      "channel": "production-android",
      "developmentClient": false
    },
    "production-ios": {
      "extends": "development",
      "distribution": "store",
      "channel": "production-ios",
      "developmentClient": false
    }
  },
  "submit": {}
}
```

**Comment by darix795** [comment]
I have same issue.
It seems that https://boostorg.jfrog.io isn't reachable

**Comment by vladis-c** [comment]
> 


> I have same issue. It seems that https://boostorg.jfrog.io isn't reachable

Have no idea that is that, but it seems like if it is down now, then when it is up again, everything should work? Hopefully?

**Comment by darix795** [comment]
> > 
> 
> > I have same issue. It seems that https://boostorg.jfrog.io isn't reachable
> 
> Have no idea that is that, but it seems like if it is down now, then when it is up again, everything should work? Hopefully?

This issue is caused by `java.net.SocketTimeoutException` because url connected to this moduli isn't reachable. 
When server up again download will work correctly. 
I don't know if exist any way to change url repository.

**Comment by serginogal** [comment]
I was having the same issue, seems like https://boostorg.jfrog.io/ is back and reachable now, it should be working now.
I tried building an app and it worked.

**Comment by vladis-c** [comment]
Yes it works now! thank you. Next time I will keep this in mind

**Comment by hananwaqar** [comment]
stuck into same issue today as well...

**Comment by rafakwolf** [comment]
Facing a similar issue here ...
![image](https://user-images.githubusercontent.com/2060578/210291474-da93e7c1-7478-4f0e-b94a-32a54b08c5d3.png)
It got stucked at IDLE forever, I tried to clear npm and gradle caches.

**Comment by Irfanwani** [comment]
smae issue, is there any alternative like downloading it manually or something like that?

**Comment by topninja** [comment]
Is there any solution?
this worked 2 days ago but today it is not working suddenly, :(
![image](https://user-images.githubusercontent.com/47001971/214759065-e6ee865f-503b-4afe-99b5-7a96638fe200.png)

**Comment by manishsencha** [comment]
The server is really slow, I am getting a download speed of 5-10 kBps resulting in timeout. 
https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
I tried downloading it from the browser, it shows approximate time of 7 hours.

**Comment by gladbhex** [comment]
If anyone still having this issue, try using a VPN.

**Comment by JasonJotted** [comment]
Sounds silly, but restarting my router fixed it for me

**Comment by jmunckhof** [comment]
Server is really slow, turning off my VPN fixed it for me

**Comment by naeem-hassan** [comment]
> The server is really slow, I am getting a download speed of 5-10 kBps resulting in timeout. https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz I tried downloading it from the browser, it shows approximate time of 7 hours.

It's just so much annoying :-)

**Comment by Neiso** [comment]
Getting 0.1 mbps to download 124.24MB is a real pain ... Is there a way to move the dependency somewhere else?

**Comment by Saad-Bashar** [comment]
Yes, same issue here. Keeps failing downloading this :(

**Comment by jkoutavas** [comment]
Downloads failing here, too.

**Comment by slash006** [comment]
same here, cannot download:
https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

**Comment by dineshleap** [comment]
Same issue in our app center builds. Works fine locally.

**Comment by Milana-Project** [comment]
i am facing this problem from yesterday till now, i hope that everyone trying to fix this problem, to take a backup from the project folder ( cause i lost my files trying to fix this issue )

**Comment by Kirk-Str** [comment]
I am having the same problem for last 4 hours. Is there a way to avoid downloading the this package from online and use offline?
or is it possible to look for a different version if the following file is not available?

https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

**Comment by Milana-Project** [comment]
> I am having the same problem for last 4 hours. Is there a way to avoid downloading the this package from online and use offline? or is it possible to look for a different version if the following file is not available?
> 
> https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

already tried all versions that availabe, but the same error 
look into the latest version its [1.84.0](https://www.boost.org/users/history/version_1_84_0.html) and not downloading anymore

**Comment by srikargunnam** [comment]
I am having similar issue, but in my case, it shows prepareBoost FAILED
![image](https://github.com/expo/expo/assets/87107773/38624b2e-fdf9-4e27-a7b2-a813433e563c)

is this the same issue everybody talking here? or is this something else?

**Comment by Milana-Project** [comment]
> I am having similar issue, but in my case, it shows prepareBoost FAILED ![image](https://private-user-images.githubusercontent.com/87107773/293577955-38624b2e-fdf9-4e27-a7b2-a813433e563c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDIwODksIm5iZiI6MTcwNDEwMTc4OSwicGF0aCI6Ii84NzEwNzc3My8yOTM1Nzc5NTUtMzg2MjRiMmUtZmRmOS00ZTI3LWE3YjItYTgxMzQzM2U1NjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA5MzYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0Zjk3NzYyZWI1NGEzZmQxNmNmMzAxMTBlMTJmNGRlMzgzYjA4M2Q5OWYwZjFhYjMzZGE4NTY3MWFmZWIxM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DAdSCXdoOE8n8FyN9EOzCY1y0DQTVU-y551O1ek4F-8)
> 
> is this the same issue everybody talking here? or is this something else?

yes, it the same for me 

![image](https://github.com/expo/expo/assets/108373264/73c48a65-3a97-49f1-92bc-dff8fd87a0a4)

**Comment by Kirk-Str** [comment]
> > I am having the same problem for last 4 hours. Is there a way to avoid downloading the this package from online and use offline? or is it possible to look for a different version if the following file is not available?
> > https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
> 
> already tried all versions that availabe, but the same error look into the latest version its [1.84.0](https://www.boost.org/users/history/version_1_84_0.html) and not downloading anymore

I mean I have another project where I observed is that the expo-modules-core which is fully downloaded yesterday, but I tried to copy the same but when compiling it refreshes the "downloads" folder. 

I just wondering is there a way to make it offline when compiling so that it does not look for the latest file online.

**Comment by Milana-Project** [comment]
> > > I am having the same problem for last 4 hours. Is there a way to avoid downloading the this package from online and use offline? or is it possible to look for a different version if the following file is not available?
> > > https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
> > 
> > 
> > already tried all versions that availabe, but the same error look into the latest version its [1.84.0](https://www.boost.org/users/history/version_1_84_0.html) and not downloading anymore
> 
> I mean I have another project where I observed is that the expo-modules-core which is fully downloaded yesterday, but I tried to copy the same but when compiling it refreshes the "downloads" folder.
> 
> I just wondering is there a way to make it offline when compiling so that it does not look for the latest file online.

I've seen a post on the internet saying that it is possible to download it locally , and put it in the project folder, after that you have to edit the path in this file : 
`PATH_TO_THE_PROJECT_FOLDER\node_modules\react-native\third-party-podspecs\boost.podspec`

**Comment by Kirk-Str** [comment]
That worked!

There are two things to consider, after copying the `boost_1_76_0.tar.gz` file into the `expo-modules-core` folder,

First, commenting the source in the  `PATH_TO_THE_PROJECT_FOLDER\node_modules\react-native\third-party-podspecs\boost.podspec`

Second, if the react-native-reanimated package is installed on the project, copy the `boost_1_76_0.tar.gz` into download folder of the same.

**Comment by Milana-Project** [comment]
> That worked!
> 
> There are two things to consider, after copying the `boost_1_76_0.tar.gz` file into the `expo-modules-core` folder,
> 
> First, commenting the source in the `PATH_TO_THE_PROJECT_FOLDER\node_modules\react-native\third-party-podspecs\boost.podspec`
> 
> Second, if the react-native-reanimated package is installed on the project, copy the `boost_1_76_0.tar.gz` into download folder of the same.

if you please  can you  specify all the steps you done ? ( because i tried this solution and not worked for me ) @Kirk-Str

**Comment by Kirk-Str** [comment]
Like I said, I had the file boost_1_76_0.tar.gz taken from another project.

and I got the exact same error that you got. first it complained that the problem is originating from expo-modules-core, so I went into the react-native folder and commented the source lines (2lines)
`PATH_TO_THE_PROJECT_FOLDER\node_modules\react-native\third-party-podspecs\boost.podspec`

after this, I ran again, It complained again this time around about react-native-reanimation. So I did the same step
`\node_modules\expo-modules-core\android\build\downloads` I copied the same files and pasted into the react-native-reanimation folder.

Voila !!

**Comment by xming13** [comment]
For temporary fix, I downloaded boost_1_76_0.tar.gz from https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.gz/download manually and uploaded it to a netlify site (any web hosting platform will do).

Next, replace the url 
```
"https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz"
``` 
in the expo-modules-core 
`node_modules/expo-modules-core/android/build.gradle`
with the url of the manually uploaded boost_1_76_0.tar.gz.

Next, install [patch-package](https://www.npmjs.com/package/patch-package) and create a patch for expo-modules-core.

This essentially makes the build process to download boost_1_76_0.tar.gz from the your url instead of from boostorg.jfrog.io.

**Comment by gunwooa** [comment]
I think I'm facing the same problem.

The build was successful on 2023-12-31 00:53, but suddenly the build does not work even though nothing has been modified. Why is this problem happening??

<img width="1168" alt="스크린샷 2024-01-02 13 48 35" src="https://github.com/expo/expo/assets/31391297/129e0dab-0d43-40e0-9352-ded522fbb628">

**Comment by Rohit-Parte** [comment]
Seems boostorg.jfrog.io is down, Is there any way to do it with EAS build procedure? I'm using automated build process so there is no option to download/upload any file locally.

Seems boostorg.jfrog.io down many times, we'll have to find the best alternative to this.

**Comment by gunwooa** [comment]
> For temporary fix, I downloaded boost_1_76_0.tar.gz from https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.gz/download manually and uploaded it to a netlify site (any web hosting platform will do).
> 
> Next, replace the url `"https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz"` in the expo-modules-core `node_modules/expo-modules-core/android/build.gradle` with the url of the boost_1_76_0.tar.gz in the previous step.
> 
> Next, install [patch-package](https://www.npmjs.com/package/patch-package) and create a patch for expo-modules-core.
> 
> This essentially makes the build process to download boost_1_76_0.tar.gz from your url instead of from https://boostorg.jfrog.io and the error should be gone.

First, I gave first aid like this. thank you

**Comment by Jean-Bekker** [comment]
> > For temporary fix, I downloaded boost_1_76_0.tar.gz from https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.gz/download manually and uploaded it to a netlify site (any web hosting platform will do).
> > Next, replace the url `"https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz"` in the expo-modules-core `node_modules/expo-modules-core/android/build.gradle` with the url of the boost_1_76_0.tar.gz in the previous step.
> > Next, install [patch-package](https://www.npmjs.com/package/patch-package) and create a patch for expo-modules-core.
> > This essentially makes the build process to download boost_1_76_0.tar.gz from your url instead of from https://boostorg.jfrog.io and the error should be gone.
> 
> First, I gave first aid like this. thank you

I did try the above but get the following error

Execution failed for task ':expo-modules-core:prepareBoost'.
> Could not read /home/expo/workingdir/build/node_modules/expo-modules-core/android/build/downloads/boost_1_76_0.tar.gz.
   > Not in GZIP format

**Comment by Eyad911** [comment]
> > > For temporary fix, I downloaded boost_1_76_0.tar.gz from https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.gz/download manually and uploaded it to a netlify site (any web hosting platform will do).
> > > Next, replace the url `"https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz"` in the expo-modules-core `node_modules/expo-modules-core/android/build.gradle` with the url of the boost_1_76_0.tar.gz in the previous step.
> > > Next, install [patch-package](https://www.npmjs.com/package/patch-package) and create a patch for expo-modules-core.
> > > This essentially makes the build process to download boost_1_76_0.tar.gz from your url instead of from https://boostorg.jfrog.io and the error should be gone.
> > 
> > 
> > First, I gave first aid like this. thank you
> 
> I did try the above but get the following error
> 
> Execution failed for task ':expo-modules-core:prepareBoost'.
> 
> > Could not read /home/expo/workingdir/build/node_modules/expo-modules-core/android/build/downloads/boost_1_76_0.tar.gz.
> > Not in GZIP format

same issue :(

**Comment by vikrantindigg** [comment]
same issue :

```
Execution failed for task ':expo-modules-core:prepareBoost'.

Could not read /home/expo/workingdir/build/node_modules/expo-modules-core/android/build/downloads/boost_1_76_0.tar.gz.
Not in GZIP format
```

**Comment by Jean-Bekker** [comment]
Fixed the Issue with Boost Library

Step 1: Update URL in ReactAndroid Build Script

1. Navigate to the file: `/node_modules/react-native/ReactAndroid/build.gradle`

2. Locate the following line:

```
https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz
```

3. Replace it with:

```
https://archives.boost.io/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz
```

Step 2: Update URL in Expo Modules Core

1. Go to the file: `/node_modules/expo-modules-core/android/build.gradle.`

2. Search for the same URL as in Step 1.

3. Replace it with the new URL provided in Step 1.

Step 3: Apply the Patches

After making the changes, run the following commands to apply the patches:
```
patch-package react-native
patch-package expo-modules-core
```

**Comment by eswarant** [comment]
![image](https://github.com/expo/expo/assets/5981774/50ffd1b2-2c7d-4388-a3f3-5e9ebc86c59f)

I got this error expo-modules-core:prepareBoost FAILED . can anyone help me on this?

**Comment by tiagopazhs** [comment]
> Fixed the Issue with Boost Library
> 
> Step 1: Update URL in ReactAndroid Build Script
> 
> 1. Navigate to the file: `/node_modules/react-native/ReactAndroid/build.gradle`
> 2. Locate the following line:
> 
> ```
> https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz
> ```
> 
> 3. Replace it with:
> 
> ```
> https://archives.boost.io/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz
> ```
> 
> Step 2: Update URL in Expo Modules Core
> 
> 1. Go to the file: `/node_modules/expo-modules-core/android/build.gradle.`
> 2. Search for the same URL as in Step 1.
> 3. Replace it with the new URL provided in Step 1.
> 
> Step 3: Apply the Patches
> 
> After making the changes, run the following commands to apply the patches:
> 
> ```
> patch-package react-native
> patch-package expo-modules-core
> ```

It finnaly work here!!!
I just want to add:

- Don't forget to reinstall node_modules and package-lock.json
- run `cd android && ./gradlew clean`

**Comment by Bellarose143** [comment]
Hello All, 

I am having this issue and have attempted the multiple fixes mentioned here to no avail. Is there anything that can be done? 
As this is code inside the expo-core-modules trying to get this link, should it not get updated to use the correct link?

**Comment by GustaJLemos** [comment]
This probably won't help anyone, but I'll say it anyway...

This problem happened to me yesterday afternoon, just one minute my app was building, and the next it showed this error... This download link was actually offline https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

When I arrived this morning, the first thing I did was check the link, it was up and running again.

I ran the command inside the android ./gradlew clean folder

I tried to build the project again, and everything worked...

**Comment by gunwooa** [comment]
I believe GPT will not solve problems like this.

**Comment by baldock92** [comment]
> > Fixed the Issue with Boost Library
> > Step 1: Update URL in ReactAndroid Build Script
> > 
> > 1. Navigate to the file: `/node_modules/react-native/ReactAndroid/build.gradle`
> > 2. Locate the following line:
> > 
> > ```
> > https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Replace it with:
> > 
> > ```
> > https://archives.boost.io/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Step 2: Update URL in Expo Modules Core
> > 
> > 1. Go to the file: `/node_modules/expo-modules-core/android/build.gradle.`
> > 2. Search for the same URL as in Step 1.
> > 3. Replace it with the new URL provided in Step 1.
> > 
> > Step 3: Apply the Patches
> > After making the changes, run the following commands to apply the patches:
> > ```
> > patch-package react-native
> > patch-package expo-modules-core
> > ```
> 
> It finnaly work here!!! I just want to add:
> 
> * Don't forget to reinstall node_modules and package-lock.json
> * run `cd android && ./gradlew clean`

I've been having the same issue today, and couldn't get this to fix the issue.

To clarify, I:
1) Replaced the URL's in the 2 node_module files.
2) Ran the 2 patch commands ``npx patch-package react-native`` and ``npx patch-package expo-modules-core``
3) Ran ``npm install``
4) Ran ``cd android && ./gradlew clean``
