### ISSUE TITLE
Missing documentation about how to install local dev-client builds [docs] 

### ISSUE THREAD

**Issue by mrzmyr** [expo/expo#19600]
### Summary

The documentation is missing the steps of how to install the dev-client when building locally (ex: `eas build -p ios --local`).

It's easy to install the locally built app using the [App Configurator](https://apps.apple.com/us/app/apple-configurator/id1037126344?mt=12) on iOS (Developer Mode enabled) and by APK manual installation on Android (enable "Install from unknown sources")

### Link to the related docs page

https://docs.expo.dev/build/internal-distribution/#4-installing-and-running-the-build

**Comment by amandeepmittal** [comment]
Hey @mrzmyr,

When using the `--local` flag there are [some limitations to this approach](https://docs.expo.dev/build-reference/local-builds/#limitations). We don't suggest this method as part of the main path when it comes to utilize EAS. Also, building locally eliminates the process of sharing the build with rest of the team or other developers which is the main goal of the [internal distribution doc](https://docs.expo.dev/build/internal-distribution).

We do have documentation for building locally: https://docs.expo.dev/build-reference/local-builds/#limitations as a reference.
