### ISSUE TITLE
<P> tag should render <p> on web @expo/html-elements

### ISSUE THREAD

**Issue by alejomendoza** [expo/expo#19604]
### Summary

When using the <P> tag from @expo/html-elements it doesn't render a paragraph tag on web but a div, this is bad for SEO.

### What platform(s) does this occur on?

Web

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nodenv/versions/16.14.2/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - ~/.nodenv/versions/16.14.2/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.3.0
      expo-cli: 5.4.6
    Expo Workflow: managed

### Minimal reproducible example

import `<P>` tag from expo/html-elements run app on web and see that it renders a div.

**Comment by brentvatne** [comment]
you can send a pr to change this along with some justification for why and @EvanBacon will review!

**Comment by navanshu** [comment]
Paragraph tag has semantic meaning which is important for SEO, also the description states that it will render a paragraph tag as HTML.

![image](https://github.com/expo/expo/assets/7664426/c2fab5f7-f093-45b6-9ae5-bff42db5d85d)

**Comment by j1mie** [comment]
This still appears to be rendering a div, should I open a new issue @brentvatne ?
