### ISSUE TITLE
EXPO XDE Going All White Windows 10 

### ISSUE THREAD

**Issue by fdrhoward** [expo/expo#1961]
I have recently started up with Expo again after some time off.

When opening a previous project, the XDE goes solid white, immediately after “Metro Bundler Ready” is displayed. This also occurs on new projects as well. The same issue happens when I logout of my XDE account.  It briefly shows the login form and goes blank.

I have uninstalled and reinstalled expo ide twice and am now using version v2.24.4. 

![expo_xde_capture](https://user-images.githubusercontent.com/26335141/42400865-d12de838-8138-11e8-852d-59bdb8e61c1b.JPG)

**Comment by schazers** [comment]
Hi fdrhoward-- that's no good! What operating system and version are you running?

**Comment by fdrhoward** [comment]
@schazers not good at all.  I am on Windows 10.  I am using v2.24.4 of Expo. However, I recently uninstalled that and download v2.23.1, and this time, the isssue occurs at login and I am not even able to see current projects or create a new one.

**Comment by terribleben** [comment]
Linking the forum thread about the same topic https://forums.expo.io/t/expo-xde-going-white-windows-10/11337

**Comment by sjchmiela** [comment]
Expo XDE has been deprecated in favor of Expo CLI (read [the blog post announcement](https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c)). I'll let myself close this issue. 🙂
