### ISSUE TITLE
`InAppPurchases.setPurchaseListener()` should return an unsubscribe function

### ISSUE THREAD

**Issue by bradjones1** [expo/expo#19620]
### Summary

`InAppPurchases.setPurchaseListener()` is a method to register a global listener for receiving information across the bridge about completed in-app purchases. However, it does not follow the standard pattern of providing a method for or returning a function to unsubscribe. This can be a particular issue during development where the callback may be registered multiple times across a development build's lifecycle. (I believe this is the underlying cause of https://github.com/expo/expo/issues/11432).

Instead, and not at all obvious, if you call it a second time, it will remove the existing listener before adding a new one. So in theory unsubscribing would look like this inside a `useEffect()`:

```js
return () => InAppPurchases.setPurchaseListener(() => {});
```

Instead we should be able to do something like:

```js
return InAppPurchases.setPurchaseListener(callback);
```

directly.

### What platform(s) does this occur on?

Android, iOS

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.18 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed
```

### Minimal reproducible example

See above.

### Applicable existing code

https://github.com/expo/expo/blob/f8204ef07e1454c729547d41d7de5a65a6b08978/packages/expo-in-app-purchases/src/InAppPurchases.ts#L224-L237

**Comment by brentvatne** [comment]
development on expo-in-app-purchases is paused, as per the docs:

![image](https://user-images.githubusercontent.com/90494/204068377-aa8d62e0-ac8f-462e-bf76-d4f2e15a2e8b.png)

**Comment by bradjones1** [comment]
@brentvatne I take "paused" as the Expo team isn't actively working on it, but does that mean PRs are not welcome for this component?

**Comment by jamesedmonston** [comment]
@brentvatne will bug fixes still be addressed, or do we need to consider switching to the suggested libraries for the long term?
