### ISSUE TITLE
React native application created using expo not working if newArchitecture is enabled

### ISSUE THREAD

**Issue by nkjs-git** [expo/expo#19628]
### Summary

I have created a sample react native application using expo (followed https://reactnative.dev/docs/environment-setup) and run the app with newArchitecture disabled by doing expo eject and built it (using both 'expo run:android' and 'npx react-native run-android --active-arch-only' ). It worked fine.

But when I enabled the newArchitecture in 'android/gradle.properties' file generated by expo eject, the application build with the command 'npx react-native run-android --active-arch-only' (and also apk generated with 'cd android && ./gradlew app:assembleRelease -PreactNativeArchitectures=arm64-v8a,x86') is successful but the app is crashing with the below exception in mobile.

`com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get(propName:UIManager): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Class.getSuperclass()' on a null object reference, stack:
l@52:427
@52:156
@157:695
h@2:1585
@156:62
h@2:1585
@153:64
h@2:1585
@139:569
h@2:1585
https://github.com/192:153
h@2:1585
@191:61
h@2:1585
@311:113
h@2:1585
@348:693
h@2:1585
@339:757
h@2:1585
@412:35
h@2:1585
@9:70
h@2:1585
@8:314
h@2:1585
@6:45
h@2:1585
d@2:958
global code@472:3

at com.facebook.react.modules.core.ExceptionsManagerModule.reportException([ExceptionsManagerModule.java:72](http://exceptionsmanagermodule.java:72/))
at [com.facebook.react.bridge.queue.NativeRunnable.run](http://com.facebook.react.bridge.queue.nativerunnable.run/)(Native Method)
at android.os.Handler.handleCallback([Handler.java:873](http://handler.java:873/))
at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage([MessageQueueThreadHandler.java:27](http://messagequeuethreadhandler.java:27/))
at android.os.Looper.loop([Looper.java:201](http://looper.java:201/))
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$[4.run](http://4.run/)([MessageQueueThreadImpl.java:228](http://messagequeuethreadimpl.java:228/))
at [java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:764](http://thread.java:764/))`

But the newArchitecture enabled is working in ios application. Can anyone please help me on this?

### What platform(s) does this occur on?

Android

### Environment

info Fetching system and libraries information...
System:
OS: macOS 12.3.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 26.92 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 16.17.1 - /usr/local/opt/node@16/bin/node
Yarn: Not Found
npm: 8.15.0 - /usr/local/opt/node@16/bin/npm
Watchman: 2022.10.03.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK: Not Found
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8309675
Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
Languages:
Java: 18.0.1.1 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: Not Found
react-native: Not Found
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Minimal reproducible example

Create react-native application: npx create-expo-app AwesomeProject
expo eject to create android and ios native folders: expo eject
Build android by connecting physical device: (through any command)
npx react-native run-android --active-arch-only
cd android && ./gradlew app:assembleRelease -PreactNativeArchitectures=arm64-v8a,x86

(followed react-native doc to create sample project https://reactnative.dev/docs/environment-setup)

**Comment by brentvatne** [comment]
this should work in sdk 47, depending on the libraries that you use. it was not supported in sdk 46
