### ISSUE TITLE
Expo Print works in Expo go but not in build apk 

### ISSUE THREAD

**Issue by LouisMuriuki** [expo/expo#19632]
### Summary

I am trying to use the expo print api to be able to generate and print a receipt, however on button press it shows the preview on development (the expo go app) but on the build apk, nothing is shown/happens

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: Windows 10 10.0.19042
Binaries:
Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
npmPackages:
expo: ^46.0.0 => 46.0.9
react: 18.0.0 => 18.0.0
react-dom: 18.0.0 => 18.0.0
react-native: 0.69.6 => 0.69.6
react-native-web: ~0.18.7 => 0.18.8
Expo Workflow: managed

### Minimal reproducible example

here is the link containing a minimal exact replica of my app https://github.com/LouisMuriuki/print
also here is a video of it working on expo go app and not build apk

https://user-images.githubusercontent.com/42152260/196908916-f27e8b2c-9c83-4955-9d60-3a578bb6d2d3.mp4

**Comment by mishumiyamizu** [comment]
i also have the same issues please help

**Comment by heyralfs** [comment]
+1

**Comment by JuanRamon96** [comment]
Same problem

**Comment by JuanRamon96** [comment]
Hi, check if you have a base64 image, the problem is that the eas build command doesn't upload certain files. In the case of images, if they aren't used as splah or icon, they aren't found and the print dosen't open.
Then it will work in expo go, but when you generate the app it won't anymore.

**Comment by mishumiyamizu** [comment]
> Hi, check if you have a base64 image, the problem is that the eas build command doesn't upload certain files. In the case of images, if they aren't used as splash or icon, they aren't found and the print dosen't open. Then it will work in expo go, but when you generate the app it won't anymore.

` const html = async () => {
        const asset = Asset.fromModule(require("../../../assets/ANPR.png"));
        const imageR = await manipulateAsync(asset.localUri ?? asset.uri, [], {
            base64: true,
        });
        return 'html here... ,${imageR.base64}'
}`
As you can see my image is already converted to base64 format. It feels like this is the package issue. I could'nt find any alternative that are stable or still being maintained til now.

**Comment by JuanRamon96** [comment]
> > Hi, check if you have a base64 image, the problem is that the eas build command doesn't upload certain files. In the case of images, if they aren't used as splash or icon, they aren't found and the print dosen't open. Then it will work in expo go, but when you generate the app it won't anymore.
> 
> ` const html = async () => { const asset = Asset.fromModule(require("../../../assets/ANPR.png")); const imageR = await manipulateAsync(asset.localUri ?? asset.uri, [], { base64: true, }); return 'html here... ,${imageR.base64}' }` As you can see my image is already converted to base64 format. It feels like this is the package issue. I could'nt find any alternative that are stable or still being maintained til now.

That's exactly the problem, eas build doesn't find the path once you build the apk because it doesn't upload the image.

Try to remove the image and generate your apk and you will see that it works.

I think there is a way to specify the files you want to include in the app.json when you build teh app, in my case what I did was convert the image to base64 online and paste the generated text.

`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
  //8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />`

**Comment by JuanRamon96** [comment]
https://docs.expo.dev/build-reference/migrating/

Read the part of "Files ignored in Git are not uploaded" in the link I sent

**Comment by binmulindi6** [comment]
> > > Hi, check if you have a base64 image, the problem is that the eas build command doesn't upload certain files. In the case of images, if they aren't used as splash or icon, they aren't found and the print dosen't open. Then it will work in expo go, but when you generate the app it won't anymore.
> > 
> > 
> > ` const html = async () => { const asset = Asset.fromModule(require("../../../assets/ANPR.png")); const imageR = await manipulateAsync(asset.localUri ?? asset.uri, [], { base64: true, }); return 'html here... ,${imageR.base64}' }` As you can see my image is already converted to base64 format. It feels like this is the package issue. I could'nt find any alternative that are stable or still being maintained til now.
> 
> That's exactly the problem, eas build doesn't find the path once you build the apk because it doesn't upload the image.
> 
> Try to remove the image and generate your apk and you will see that it works.
> 
> I think there is a way to specify the files you want to include in the eas.json when you build the app, in my case what I did was convert the image to base64 online and paste the generated text.
> 
> `<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4 //8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />`

Hello, i had this issue when i built the apk. but converting my img online to base64 worked for me too. thanks @JuanRamon96 😉
