### ISSUE TITLE
[docs] Document iOS16 limitation around deviceName

### ISSUE THREAD

**Issue by dbotman** [expo/expo#19639]
### Summary

Device.deviceName always return "iPhone" on iOS16 instead of the real deviceName

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
      Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 29, 30, 32
        Build Tools: 29.0.2, 30.0.2, 32.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.7 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 2.4.1
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

import * as Device from 'expo-device';
console.log(Device.deviceName});

**Comment by Simek** [comment]
Hello @dbotman, thank you for the report!

It looks like this is an expected behaviour in iOS 16, unless you provide an additional entitlements, see:
* https://developer.apple.com/documentation/uikit/uidevice/1620015-name#discussion

But probably it would be nice to mention about this limitation (additional steps needed) in our docs too.
