### ISSUE TITLE
getExpoPushTokenAsync stuck simulator ios16

### ISSUE THREAD

**Issue by imhazige** [expo/expo#19648]
### Summary

`getExpoPushTokenAsync` never go to next line of code, neither reject nor resolve.

It happened only on ios16 simulator.

Same code works on ios15 simulator.

Same code works on ios16 iphonese 3.

Project is on EXPO SDK 44

See https://github.com/expo/expo/issues/15990

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.0/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/kmacp/.rvm/gems/ruby-2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: bare

----
actually it should be managed flow, Don't know why it says bare flow

### Minimal reproducible example

```javascript
try {
    console.log('1');
    const token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log('2');

    return token;
  } catch (err) {
    console.log('2.1');
    return null;
  }
```

**Comment by rikardwissing** [comment]
Having same issue

**Comment by IsaacPhung** [comment]
Having same issue :(

**Comment by DenysMoro** [comment]
Same for iOS 16.1
iOS 15.5 - works fine and not blocking "next" code

```
"expo": "^45.0.0",
"expo-notifications": "~0.15.4",
```

**Comment by mgouault** [comment]
Same issue on the simulator of an iPhone 14 on iOS 16.2
```
"expo": "^47.0.0",
    "expo-notifications": "~0.17.0",

**Comment by CCB-cerivera** [comment]
> Same issue on the simulator of an iPhone 14 (iOS 16.2), Expo SDK 47 in managed workflow Had the same issue before upgrading when in SDK 44
> 
> ```
> "expo": "^47.0.0",
> "expo-notifications": "~0.17.0",
> ```

Did you manage to solve it?

**Comment by CCB-cerivera** [comment]
Any solution for iOS 16?

**Comment by mgouault** [comment]
> > Same issue on the simulator of an iPhone 14 (iOS 16.2), Expo SDK 47 in managed workflow Had the same issue before upgrading when in SDK 44
> > ```
> > "expo": "^47.0.0",
> > "expo-notifications": "~0.17.0",
> > ```
> 
> Did you manage to solve it?

No, I don't have any workaround (except not using ios simulator 🤷)

After calling getExpoPushTokenAsync it seems to be stuck here : https://github.com/expo/expo/blob/main/packages/expo-notifications/src/getDevicePushTokenAsync.ts#L25

I do not know more.

**Comment by aleena-adnan1** [comment]
any solution ?
