### ISSUE TITLE
setInterval on android runs too fast

### ISSUE THREAD

**Issue by ericyliu** [expo/expo#19661]
### Summary

On Android (Debug on device) with remote debugging on (or apparently in development mode), setInterval calls way too fast.

https://stackoverflow.com/questions/70369485/react-native-setinterval-fires-too-fast-using-expo

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Environment

 System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Reproducible demo

const Component = () => {
  useEffect(() => {
    setInterval(() => console.log("Should run every second"), 1000);
  }, []);
  return <View />
}

**Comment by ericyliu** [comment]
This issue is fixed when turning remote debugging off, but would be nice to have it work with remote debugging.

**Comment by brentvatne** [comment]
we don't recommend using remote debugging. we suggest using hermes inspector instead. if you enable hermes on your app, you can launch to it directly from the dev menu in the app or by pressing <kbd>j</kbd> in the interactive expo cli prompt. there are many issues with remote debugging and it won't be around for much longer.
