### ISSUE TITLE
OsLogger issue while using Expo SDK 46 with latest react-native fabric architecture

### ISSUE THREAD

**Issue by ArkapravoNath** [expo/expo#19665]
### Summary

After upgrading project to react-native 0.69.5 and using the latest expo modules 46.0.0 I'm getting symbol(s) not found for architecture arm64 error. The issue is for Os logger, I can't find reference to the same in expo modules core.
_$s2os6LoggerVMa", referenced from:
      _$s15ExpoModulesCore12OSLogHandlerC8categoryACSS_tcfc in libExpoModulesCore.a(LogHandlers.o)
Attaching ss for reference
<img width="826" alt="Screenshot 2022-10-24 at 04 43 02" src="https://user-images.githubusercontent.com/19495852/197422745-a6ebbc95-1691-4422-b146-86dac6c4f1de.png">

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.1 - /opt/homebrew/bin/npm
      Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: 46.0.0 => 46.0.0 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

    "expo": "46.0.0",
    "expo-cli": "^6.0.6",
    "expo-local-authentication": "~12.3.0",
    "expo-modules-autolinking": "^0.10.3",
    "react-native-reanimated": "^3.0.0-rc.3",
    "react-native": "0.69.5",

install in package.json, and build the project in ios(Xcode). I have followed the steps provided to include the latest architecture in my ptoject.

**Comment by Kudo** [comment]
hi there! i test the dependencies as your, but cannot repro on my side. could you create a minimal reproducible example and upload to some git repository so that we could help to investigate further?

fwiw, the `expo-cli` and the `expo-modules-autolinking` should not be added as dependencies.

**Comment by ankampraveen** [comment]
@ArkapravoNath is this solved for you ? i am facing same issue

**Comment by etaiklein** [comment]
Same issue. Any resolution?

**Comment by KenCorma** [comment]
@etaiklein @ankampraveen @ArkapravoNath @Kudo

This issue stems from Logger trying to use `os.Logger` when targeting below iOS 14, even when using iOS16 sdk it will fail. To work around this, change the min iOS for these lines to an number greater than the SDK installed. 

Here:
https://github.com/expo/expo/blob/a4e3c2608de178d457952b033409bf066406a4c9/packages/expo-modules-core/ios/Swift/Logging/Logger.swift#L55
and
https://github.com/expo/expo/blob/a4e3c2608de178d457952b033409bf066406a4c9/packages/expo-modules-core/ios/Swift/Logging/LogHandlers.swift#L17

Change 14 -> 17 or modify this line of code so it falls back on the generic print statements. 
Clean -> Rebuild -> Archive. You're good to go.

**Comment by etaiklein** [comment]
> @etaiklein @ankampraveen @ArkapravoNath @Kudo
> 
> This issue stems from Logger trying to use `os.Logger` when targeting below iOS 14, even when using iOS16 sdk it will fail. To work around this, change the min iOS for these lines to an number greater than the SDK installed.
> 
> Here:
> 
> https://github.com/expo/expo/blob/a4e3c2608de178d457952b033409bf066406a4c9/packages/expo-modules-core/ios/Swift/Logging/Logger.swift#L55
> 
> 
> and
> https://github.com/expo/expo/blob/a4e3c2608de178d457952b033409bf066406a4c9/packages/expo-modules-core/ios/Swift/Logging/LogHandlers.swift#L17
> 
> Change 14 -> 17 or modify this line of code so it falls back on the generic print statements. Clean -> Rebuild -> Archive. You're good to go.

@KenCorma you have come through for me when I had all but given up.

Commenting it out worked!
<img width="923" alt="Screenshot 2023-07-16 at 9 41 20 PM" src="https://github.com/expo/expo/assets/4458476/fbb6525c-7e13-4477-a513-e22d75944c65">
<img width="987" alt="Screenshot 2023-07-16 at 9 40 35 PM" src="https://github.com/expo/expo/assets/4458476/eb1a4918-a563-43d4-9adb-f2bcaeeed955">

This little green circle is so beautiful to me
<img width="321" alt="Screenshot 2023-07-16 at 9 57 41 PM" src="https://github.com/expo/expo/assets/4458476/09bbd03b-98ba-4567-935a-4546a5d736e8">

Effusively, thank you.
