### ISSUE TITLE
Notification listener does not work when app is closed. expo version 45.0.0

### ISSUE THREAD

**Issue by sohailmadan** [expo/expo#19663]
### Summary

I want to redirect user to the specific screen based upon the notification data. Listener is added in app.js file, i have tried uselastnotification hook as well. Everything works fine when app is in background and user taps on the notification. But when the app is closed it doesn't work. 

I saw the expo push notification it's mentioned Notifications.addNotificationResponseReceivedListener is called whenever the app is in background or is killed

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - ~/Sites/internatApp/FriendsNextDoor/node_modules/.bin/yarn
      npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 1.1.0
      expo-cli: 5.4.12
    Expo Workflow: managed

### Minimal reproducible example

This is the code in my app.js (root component)
React.useEffect(() => {
    responseListener.current =
      Notifications.addNotificationResponseReceivedListener(
        async (response) => {
           //do something
        }
      );
    return () => {
      Notifications.removeNotificationSubscription(responseListener.current);
    };
 }, []);

**Comment by kryptowiz** [comment]
I opened a similar issue #18712 but no one replied. 🥲

**Comment by illi-homz** [comment]
same problem!

**Comment by sohailmadan** [comment]
const linking = {
    prefixes: [prefix],
    config: deepLinksConf,
    async getInitialURL() {
      // First, you may want to do the default deep link handling
      // Check if app was opened from a deep link
      let url = await Linking.getInitialURL();

      if (url != null) {
        return url;
      }

      // Handle URL from expo push notifications
      const response = await Notifications.getLastNotificationResponseAsync();
      const redirectUrl = response.notification.request.content.data.url;
      return redirectUrl;
    },
    subscribe(listener) {
      const onReceiveURL = ({ url }) => listener(url);

      // Listen to incoming links from deep linking
      Linking.addEventListener("url", onReceiveURL);

      // Listen to expo push notifications
      const subscription =
        Notifications.addNotificationResponseReceivedListener(
          async (response) => {
             const redirectUrl = response.notification.request.content.data.url;
            return redirectUrl;
            await Linking.openURL(redirectUrl);
          }
        );

      return () => {
        // Clean up the event listeners
        // Linking.removeEventListener('url', onReceiveURL);
        subscription.remove();
      };
    },
  };
  
  
  I updated my linking object like this and passed it to NavigationContainer. Now listener has started working in IOS even if app is closed but in android it still doesn't work. any idea on what could make this work on android as well.

**Comment by federicogomezlara** [comment]
@sohailmadan You ever manage to solve it for both platforms? Having this issue in 2024

**Comment by feri-irawan** [comment]
Same issue, but in SDK 51, redirection only works when the app is open or still in the list in recently opened apps. However, when I close the app and remove it from the list of recently opened apps, the redirection does not work.

I guess the `addNotificationResponseReceivedListener` method is not triggered.

**Comment by contatofccode** [comment]
Alguma novidade sobre isso?
No IOS funciona bem, mas no Android não.

**Comment by sleep9** [comment]
This is still a valid issue.
