### ISSUE TITLE
Execution failed for task ':expo:compileDebugKotlin' on RN 0.67.2

### ISSUE THREAD

**Issue by kamal-j** [expo/expo#19678]
### Summary

I'm trying to manually install expo in a bare react native 0.67.2 project. I have followed the manual installation steps from this guide - https://github.com/expo/fyi/blob/main/expo-modules-migration.md

This is the error log when i try to do a debug build in android.
```
* What went wrong:
Execution failed for task ':expo:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

```

This issue is similar to https://github.com/expo/expo/issues/15624 and https://github.com/expo/expo/issues/15632 but seems like the fix doesn't work.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.4.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.12.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.16 => 46.0.16 
      metro: 0.70.0 => 0.70.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.0 => 17.0.0 
      react-native: 0.67.2 => 0.67.2 
      react-native-web: ^0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: managed

### Minimal reproducible example

I am working on creating a snack based on my exact react native configuration. Will update this shortly.

**Comment by Kudo** [comment]
hi there! [react-native 0.67 is not be supported by expo sdk 46](https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a). please upgrade your react-native version. or maybe use expo sdk 45 which might support react-native 0.67 under the hood.
