### ISSUE TITLE
How do we set the IP address for expo-cli on custom server

### ISSUE THREAD

**Issue by ShaneBurkhart** [expo/expo#19689]
### Summary

We used to be able to set REACT_NATIVE_PACKAGER_HOSTNAME to use a remote server for development.

That option does not work in new version on expo. Is there a new way to set the hostname we listen on?

### SDK Version

6.0.6

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^46.0.0 => 46.0.13
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    npmGlobalPackages:
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

Create an app with expo 6.0.6 and set the REACT_NATIVE_PACKAGER_HOSTNAME var. The server will not render the web gui for 19002. 

This worked on old version 5.4.12.

You can see it prints an empty line where it normally says "listening on ..."

![image](https://user-images.githubusercontent.com/2678773/197870300-f03bb098-2ec3-4e64-b467-89a680665376.png)

**Comment by MkrierPharmanity** [comment]
> > The server will not render the web gui
> 
> Are you just referring to the Web UI? This is not related to `REACT_NATIVE_PACKAGER_HOSTNAME`.
> 
> Please see the following blog post:
> 
> https://blog.expo.dev/sunsetting-the-web-ui-for-expo-cli-ab12936d2206
> 
> The following still works for me to generate the QR code using the specified address:
> 
> ```
> REACT_NATIVE_PACKAGER_HOSTNAME=a.b.c.d npx expo start
> ```

nop this will only change the metro address not the web server address
launched with REACT_NATIVE_PACKAGER_HOSTNAME="192.168.1.10"  you got
`› Metro waiting on exp://192.168.1.10:19000
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:19006`

**Comment by ShaneBurkhart** [comment]
i am now forced to upgrade expo (i downgraded to fix this problem before).

now that i am forced to upgrade, this doesn't work again.

the env var i was using was EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 which is completely missing from expo now.  i believe this was needed for metro to serve the expo dashboard on my server.

**Comment by ShaneBurkhart** [comment]
for whatever reason, when i host this in a docker container and use the host network type (required), i can't see the webpage at <domain>:19002. it worked before upgrading expo.

the only environement var i have is the one above. usually these problems are fixed in docker by listening to 0.0.0.0 so it makes sense that EXPO_DEVTOOLS_LISTEN_ADDRESS would be the var that was used previously. i'm pulling expo repo to search for the var in old versions now.

**Comment by ShaneBurkhart** [comment]
here's the original addition of this feature. 

https://github.com/expo/expo-cli/commit/a87602b8ef906155e2f7412fc3d35b10b0a479fc

it appears this package has moved. i assume this package is now in packages/@expo/dev-server. 

i can't find any options to set the host for the metro server. how can i do this?

**Comment by ShaneBurkhart** [comment]
i guess the web ui is gone completely? wtf lol. 

https://blog.expo.dev/sunsetting-the-web-ui-for-expo-cli-ab12936d2206

it mentions needing to support eas build and stuff. who cares? we were just looking at device logs and it was convenient too.

**Comment by yashseth391** [comment]
@wodin you are life saviour

**Comment by kubijo** [comment]
Why was this closed? I am hitting my head against a wall that is the Node.js server binding only to an ipv6 interface, thereby making it impossible to actually have it be visible throughout my local network.

```
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node      44722 pepa   30u  IPv6 920457      0t0  TCP *:8081 (LISTEN)
```

I tried settings whatever environment variables I could, but nothing changes this...

```
export EXPO_PACKAGER_HOSTNAME = 0.0.0.0
export REACT_NATIVE_PACKAGER_HOSTNAME = 0.0.0.0
export EXPO_DEVTOOLS_LISTEN_ADDRESS = 0.0.0.0
```

**Comment by yashseth391** [comment]
@kubijo , try this ,in place of your_ip ,write your whatever you uses ipv4, ipv6 or local

Set-Item env:REACT_NATIVE_PACKAGER_HOSTNAME "your_ip_"; npx expo start

**Comment by kubijo** [comment]
OK, so it was an Ubuntu firewall problem ... I feel freaking dumb right now because I obviously did look into that and was opening those ports through the `ufw` cli, but eventually, I had to go to the [UI client](https://firewalld.org/) and:
 - switch my network interface to the `home` zone
 - whitelist the zones/home/ports section

**Comment by yashseth391** [comment]
@kubijo ,glad you got your solution ,, but I was saying to run both commands simultaneously in vscode

**Comment by vaz3r** [comment]
@wodin Solution works, however, the port needs to be whitelisted by the firewall as well to work.
