### ISSUE TITLE
Cannot register background task for background notifications

### ISSUE THREAD

**Issue by zirlman** [expo/expo#19681]
### Summary

I'm trying to setup background notification tasks as described in [Expo documentation](https://docs.expo.dev/versions/latest/sdk/notifications/#handling-incoming-notifications-when-the-app-is-1), however I'm receiving the following error (iOS & Android):

> Attempt to invoke interface method 'void expo.modules.interfaces.taskManager.TaskManagerInterface.registerTask(java.lang.String, java.lang.Class, java.util.Map)' on a null object reference

I've added the `remote-notifications` plugin in `app.config.js` as shown below:
```js
 infoPlist: {
            // other configurations
            UIBackgroundModes: ["remote-notification"],
        },
```

Below is my code for setting up background notifications:
```ts
import { useEffect } from "react";
import * as TaskManager from "expo-task-manager";
import { Platform } from "react-native";
import * as Notifications from "expo-notifications";

const BACKGROUND_NOTIFICATION_TASK = "BACKGROUND-NOTIFICATION-TASK";

TaskManager.defineTask(
    BACKGROUND_NOTIFICATION_TASK,
    ({ data, error, executionInfo }) => {
        const meta = `${Platform.OS}/${BACKGROUND_NOTIFICATION_TASK}`;

        data && console.log(meta, "data", data);
        error && console.log(meta, "error", error);
        executionInfo && console.log(meta, "executionInfo", executionInfo);
    },
);

export const useSetupNotificationsBackgroundTask = () => {
    const registerBackgroundTaskAsync = async () => {
        try {
            await Notifications.registerTaskAsync(BACKGROUND_NOTIFICATION_TASK);

            const registeredTasks = await TaskManager.getRegisteredTasksAsync();
            console.log("🔵 Registered tasks:", registeredTasks);
        } catch (e) {
            console.warn(e);
        }
    };

    useEffect(() => {
        registerBackgroundTaskAsync();
    }, []);
};
```

Then I call this hook in `PushNotificationContextProvider`: 
```ts
export const PushNotificationProvider: FC<{ children: React.ReactNode }> = ({
    children,
}) => {
    useSetupNotificationsBackgroundTask();
    // ... 
```

What I've tried:
* Downgrade expo-task-manager from `10.3.0` to `10.2.1` and `10.2.1`
* Run `registerBackgroundTaskAsync` as [IIFE](https://www.geeksforgeeks.org/javascript-immediately-invoked-function-expressions-iife/) and only import the hook as mock such that JS compiler executes the function
* Run  `const registeredTasks = await TaskManager.getRegisteredTasksAsync();` before `await Notifications.registerTaskAsync(BACKGROUND_NOTIFICATION_TASK);` . The following result was received:
 > undefined is not an object (evaluating '_ExpoTaskManager.default.getRegisteredTasksAsync')
at node_modules/expo-task-manager/build/TaskManager.js:98:9 in getRegisteredTasksAsync
* Searched Expo forum for similar issues
* Searched Github closed/open Issues for a similar error. Only found [this](https://github.com/expo/expo/issues/9288), but no solution was applicable
* Wrapped `registerBackgroundTaskAsync` inside a timeout with 500 & 1000 as timeout values:
```ts
useEffect(() => {
        const timeoutId = setTimeout(() => {
            registerBackgroundTaskAsync();
        }, 1000);

        return () => clearTimeout(timeoutId)
    }, []);
```

### Conclusion
Every attempt in trying to set up the background notification task handler failed, resulting in an error that said that TaskManager is not defined. I hope someone will be able to help me on this issue

### What platform(s) does this occur on?

Android, iOS

### Environment

```sh
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.81 => 0.1.84 
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ^46.0.0 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.3.0
      expo-cli: 6.0.6
    Expo Workflow: managed
```

### Minimal reproducible example

1. Create a managed expo project 
2. Create app.config.js/app.js and add  `UIBackgroundModes: ["remote-notification"]` to `ios.infoPlist` object
3. Create `useSetupNotificationsBackgroundTask.ts` and copy the file content displayed above
4. Import `useSetupNotificationsBackgroundTask` and call it inside `App.ts`
5. Create a development build with `expo start --dev-client`
6. Scan QR code & wait for the warning to occur

**Comment by johnquiet** [comment]
I am getting the same error on Android: 

`Error: Attempt to invoke interface method 'void expo.modules.interfaces.taskManager.TaskManagerInterface.registerTask(java.lang.String, java.lang.Class, java.util.Map)' on a null object reference`

I followed the docs, so I'm not sure why this error is happening. My app just needs to do something in response to a local notification in the background.

 I have confirmed that the task is getting defined by using TaskManager.isTaskDefined(BACKGROUND_NOTIFICATION_TASK) which returns true.

**Comment by johnquiet** [comment]
Something was wrong with my npm installs. I recreated the project, and reinstalled all dependencies. Background fetch and task manager are now working fine. I haven't tested background notification handling because I've decided to just use background fetch for my app, but I bet it works too now. 

Also, I literally i had to recreate the entire project. I tried uninstalling the task manager and background fetch dependencies and reinstalling them in the old project and that didn't work.

**Comment by mkhoussid** [comment]
> I am getting the same error on Android:
> 
> `Error: Attempt to invoke interface method 'void expo.modules.interfaces.taskManager.TaskManagerInterface.registerTask(java.lang.String, java.lang.Class, java.util.Map)' on a null object reference`
> 
> I followed the docs, so I'm not sure why this error is happening. My app just needs to do something in response to a local notification in the background.
> 
> I have confirmed that the task is getting defined by using TaskManager.isTaskDefined(BACKGROUND_NOTIFICATION_TASK) which returns true.
> 
> EDIT: Just to see if TaskManager would work at all, I tried to register a task using BackgroundFetch.registerTaskAsync, but I am still getting an undefined object error regarding registerTaskAsync.

To anyone coming here in the future, don't forget to rebuild your project:

```
npx expo prebuild && eas build --profile development --platform android --clear-cache
```
