### ISSUE TITLE
Expo Camera - changing rotation does not cause camera rotate

### ISSUE THREAD

**Issue by bearsworth** [expo/expo#19690]
### Summary

When a user is locked on portrait mode, the orientation of the camera should also be locked to the current orientation.

This works with a bare react native app and react navigation. It also works in other 3rd party libraries with camera, but there appears to be a bug related to expo camera.

You can reproduce the issue simply by setting the lock screen to portrait and rotating the camera. You can also set orientation lock to landscape, and the camera will initially load with portrait orientation. Only when manually rotating the camera will the camera change orientation.

****
What works for portrait only is if one uses lockPlatformAsync. One note though. Platform lock landscape mode does not prevent the camera from going into portrait mode. Fortunately for me, portrait mode is okay for locking a camera for taking a picture of something. 

****

### What platform(s) does this occur on?

iOS

### Environment

Expo: 46.0.16
Expo-Camera: 12.3.0

### Minimal reproducible example

If you follow the example provided on your page and simply set orientation lock to portrait, you'll see it.

**Comment by FlavienR** [comment]
Have you found a fix yet?

**Comment by yohamta** [comment]
Similar issue: https://github.com/expo/expo/issues/16837
This is happening since v44 (iOS 16) and It's still continuing in v47.
There is no fix or workaround other than to stop using expo and avoid the problems that always occur during upgrades.
