### ISSUE TITLE
expo run android alias not work fine

### ISSUE THREAD

**Issue by StarHosea** [expo/expo#19695]
### Summary

use alias on web works fine , but not on android

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:                                          
    System:                                                                      
      OS: Windows 10 10.0.19042                                                  
    Binaries:                                                                    
      Node: 16.14.0 - ~\AppData\Local\Volta\tools\image\node\16.14.0\node.EXE    
      Yarn: 1.22.19 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
      npm: 8.3.1 - ~\AppData\Local\Volta\tools\image\node\16.14.0\npm.CMD        
    npmPackages:                                                                 
      @expo/webpack-config: ^0.17.0 => 0.17.2                                    
      expo: ~46.0.16 => 46.0.16                                                  
      react: 18.0.0 => 18.0.0                                                    
      react-dom: 18.0.0 => 18.0.0                                                
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: bare

### Minimal reproducible example

my project structure

- packages
  - tw-runtime-rn
  - tw-runtime-react 
- src
- babel.config.js 
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolver',
        {
          alias: {
            '@': './src',
            '@tw/tw-runtime-rn': './packages/tw-runtime-rn/index.ts',
            '@tw/tw-runtime-react': './packages/tw-runtime-react/index.ts'
          }
        }
      ]
    ]
  };
};
```
- ts.config.ts
```json

{
  "compilerOptions": {
      "paths": {
      "@/*": [
        "src/*"
      ],
      "@tw/tw-runtime-rn": [
        "packages/tw-runtime-rn"
      ],
      "@tw/tw-runtime-react": [
        "packages/tw-runtime-react"
      ]
    }
     //... anything else
  }
}
```
cmd start web works fine,  but android not.
error like this 
```
Unable to resolve "@tw/tw-runtime-rn" from
```

**Comment by amritk** [comment]
What was the problem?
