### ISSUE TITLE
RTL localization doesn't work on first load, requires restart

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1969]
This is a followup issue to the discussion here: https://github.com/expo/expo/issues/1205

The generally accepted recommendation in upstream react-native is to add a few native lines when your app starts (before AppRegistry is called): 
- https://github.com/facebook/react-native/issues/11475#issuecomment-377877404
- https://github.com/facebook/react-native/issues/11475#issuecomment-377889753

Right now the only thing you can do with Expo is `Updates.reload` (similar to react-native-restart) in order to get the behavior on second load. This isn't great, so we might need to add a native hook to make RTL-localized builds start correctly on the first load.

In particular, this has been an issue for some users who want to force their app to stay in LTR even when the device system settings are configured as RTL.

**Comment by m4tx** [comment]
@terribleben I looked at the issue and it seems that (at least on Android) everything works properly when you switch from LTR to RTL via the system settings. Android just recreates the activity and the RTL layout is automatically used.

The problem only occurs when using `forceRTL()` method of `I18nManagerModule`, which just sets our custom preference. In that case, we need to take care of recreating the activity ourselves, which is kind of troublesome - e.g. we can have code like this:

```javascript
I18nManager.forceRTL(true);
I18nManager.allowRTL(true);
```

In that case, we would restart the activity twice.

We could probably restart only if a line may have some effect - e.g. don't restart after `allowRTL(true)` if `forceRTL(true)` was just used. Also, if we want to avoid restarts(/recreating activity) at all, it looks like we'd have to do it before finishing `onCreate()` of the Activity, and that means before attaching the root view to the activity and therefore before executing any "user" JS code - at the point that we don't even know yet, if there's `forceRTL`/`allowRTL` inside.

So, the question that emerges is: Do we want to automatically execute `Updates.reload()` if `forceRTL()`/`allowRTL()` is going to change the current application configuration? Or maybe we want to be able to tell expo that the application support RTL in some other way (that we could utilise before running JS code)?

**Comment by esamelson** [comment]
Sorry for the slow followup. I think we'd like to have a way to specify the LTR/RTL settings before running JS code -- perhaps a new configuration setting in app.json. Ideally we'd like people's apps to load correctly on the first run without immediately having to reload.

Let me know if that doesn't make sense or if I'm missing some complexity here!

**Comment by Ahmed-Imam** [comment]
Any Updates on this issue ??

**Comment by 0xori** [comment]
Any updates on this issue? currently `Updates.reload()` is not reloading the app.

**Comment by amitneeman** [comment]
hey, any updates on this issue? 
I managed to find a work around by running the following code:
`
const isRTLAndroid = Platform.OS === 'android' && I18nManager.isRTL;

    if (isRTLAndroid) {
      I18nManager.forceRTL(false);
      I18nManager.allowRTL(false);
      Expo.Updates.reload();
    }
`
the issue with it is that it causes the app to crash and show Expo's blue screen, prompting the user to manually reload (horrible UX).
If the issue is currently not being prioritised/ worked on, did anyone find a better workaround? thanks a lot!

**Comment by Ahmed-Imam** [comment]
in case you eject from Expo, you can simply fix it as follow:

```
import com.facebook.react.modules.i18nmanager.I18nUtil;

public class MainApplication extends Application implements ReactApplication {
    @Override
    public void onCreate() {
        super.onCreate();

        // FORCE LTR
        I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
        sharedI18nUtilInstance.allowRTL(getApplicationContext(), false);
        ....
    }
}
```
But I also managed a workaround when i used Expo by the below code and everything was working fine 
```

import { I18nManager} from 'react-native';
I18nManager.allowRTL(false);

export default class <className> extends Component {



}
```

**Comment by MeherBa** [comment]
+1

**Comment by creativemind1** [comment]
I'm also facing issue while loading the app for first time. RTL doesn't on first load. It work on second load. How to run RTL on first load?

**Comment by amitneeman** [comment]
In case you don't want to eject from expo you currently have 2 options:
1. make the app crash programatically on the first load and then you solve your problem (not very good UX tho)
2. Add weird if / else statements to your code alternating between "right" and "left" depends on the platform and language (thats what I decided to do eventually).

**Comment by creativemind1** [comment]
> In case you don't want to eject from expo you currently have 2 options:
> 
> 1. make the app crash programatically on the first load and then you solve your problem (not very good UX tho)
> 2. Add weird if / else statements to your code alternating between "right" and "left" depends on the platform and language (thats what I decided to do eventually).

It doesn't load with the if and else condition as well..

**Comment by amitneeman** [comment]
Its not about loading / changing the device configuration. perhaps and example is the best way to show what i mean

`const isRTLAndroid = Platform.OS === 'android' && I18nManager.isRTL;

const ArticleContainer = styled.View`
    border-color: #eee;
    border-bottom-width: 1;
    padding: 15px;
    flex-direction: ${isRTLAndroid ? 'row' : 'row-reverse'};
    background-color: white;
    margin-bottom: 10px
    box-shadow: 3px 2px 3px gray;
`;`

as its pretty horrible, it does the job

**Comment by creativemind1** [comment]
Yes, I do understand but the thing is when you first load the App, it does't give you the correct value for i18Nmanger.isRTL

**Comment by amitneeman** [comment]
works for me with

    "expo": "^32.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

**Comment by creativemind1** [comment]
What I was trying to say is, I'm unable to start the App with RTL as true. Initially, isRTL will display false but again `Updates.reload();` will not work

**Comment by amitneeman** [comment]
the issue happens because android forces RTL layout on the expo app. you are able to change it using

```
I18nManager.forceRTL(false);
I18nManager.allowRTL(false);
```

but the issue is this will take effect only on the next load of the app.
to solve the issue you can either use
```
      Expo.Updates.reload();
```
to sort of crash/reload the app and make the changes take effect (look at my previous code example on this issue)

or use the if/else statements regarding the platform and language

**Comment by creativemind1** [comment]
Expo.Updates.reload(); 

> but the issue is this will take effect only on the next load of the app.
> to solve the issue you can either use

Just like `I18nManager.forceRTL(false);` works on next load Updates.reload() too works on the next load of the App **and not on the first load.**

**Comment by ramiasg** [comment]
Any Updates on this issue ??

**Comment by dagan-arbox** [comment]
this issue must wake up, it's horrible.

**Comment by mahevstark** [comment]
here is the solution:

https://stackoverflow.com/a/61343685/7564751


Library link: https://www.npmjs.com/package/fiction-expo-restart

install: 
`npm i fiction-expo-restart`

import: 
`import {Restart} from 'fiction-expo-restart';`

Use:
`Restart();`

**Comment by cholakovdev** [comment]
+

**Comment by EvanBacon** [comment]
Unfortunately there is not much we can do from the `expo/expo` repo. If you would like to fix this issue, please submit a pull request to [facebook/react-native](https://github.com/facebook/react-native).

**Comment by brentvatne** [comment]
here's an example of using `Updates.reloadAsync()` and `I18nManager` to toggle between RTL/LTR: https://github.com/brentvatne/updates-reload
