### ISSUE TITLE
Re-sign Android APK

### ISSUE THREAD

**Issue by oandreazza** [expo/expo#197]
I made a mistake and signed a apk with wrong keystore. Is there a way to resign this apk with the correct keystore?

**Comment by LeiZeng** [comment]
I hope this can resolve your problem:
https://github.com/onbiron/apk-resigner

**Comment by dikaiosune** [comment]
If you need to clear your android keystore, please join our [Slack](https://slack.expo.io) and ping me (I'm `ap` there) for help clearing it out. Resigning it will work as a one-off but if you need to change it forever let us know so we can reset the credentials. Thanks!
