### ISSUE TITLE
is it possible to have ImagePicker apply no compression to image?

### ISSUE THREAD

**Issue by leomayleomay** [expo/expo#1970]
### Environment
```
There is a new version of exp available (55.0.4).
You are currently using exp 55.0.3
Run `npm install -g exp` to get the latest version
[12:59:09] Generating diagnostics report...
[12:59:09] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4
```

### Steps to Reproduce
1. Pick an image use ImagePicker, with `quality` set to be 1.0
2. Upload image to S3

### Expected Behavior
the file on S3 should be exact the same with the original file

### Actual Behavior

the file on S3 is much larger than original file in terms of size

**Comment by leomayleomay** [comment]
a workaround is to use `ImageManipulator` to convert the image to PNG before uploading to S3

**Comment by barthec** [comment]
@leomayleomay right now `ImagePicker` decompresses original file, applies some fixes and compresses again using PNG/JPG. PNG compression discards `quality` parameter whereas JPG with `quality` set to `1.0` actually enlarges the original file. As you noticed, PNG is currently best workaround. We'll discuss the matter in the team how `quality = 1.0` should work with JPG compression.
