### ISSUE TITLE
No longer works with @welldone-software/why-did-you-render

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#19709]
### Summary

_Why Did You Render_ is a great tool that used to work with Expo, but no longer seems to. I've tested dozens of configuration variations, across 3 separate projects (including one brand new one) and had no luck getting any WDYR logging to occur with any of them.

A few people report success here, but most seem to have the issue: https://github.com/welldone-software/why-did-you-render/issues/235

I've consulted every resource I can find on the web, including Discord messages from the Expo maintainers stating that the config that fails should work.

**I tried, among other things:**

- with `EXPO_USE_EXOTIC=1` and `0`
- with Fast Refresh on/off
- modifying `node_modules/expo/AppEntry.js` to put the `import './wdyr'` at the top of that file, rather than just the top of the `./App.js` file to ensure it was really the very first import
- setting `logOnDifferentValues: true` in the hopes of seeing anything logged out
- Expo Go and a custom development client
- `yarn expo start -c`
- an alternate Babel config (available under the alternativeApproach branch in the repro repo)

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    npmGlobalPackages:
      eas-cli: 2.3.0
      expo-cli: 6.0.6

### Minimal reproducible example

https://github.com/Slapbox/wdyr-does-not-work (also see `alternativeApproach` branch for another non-working config)

**Comment by Slapbox** [comment]
@#$%ing StrictMode... Turn it off.

**Comment by Slapbox** [comment]
Well, actually - that only resolved our issue in 1 of the 3 projects, because the other two don't use StrictMode.

**Comment by brentvatne** [comment]
if you can point to something in Expo tools that has changed to break this library then this would be good to post to an issue here, otherwise we won't have time to investigate
