### ISSUE TITLE
React Native Android build fails because of a failure in validating a SSL certificate in the downloadBoost step

### ISSUE THREAD

**Issue by tootsweet** [expo/expo#19707]
### Summary

My React Native Android build fails because a Gradle task named :expo-modules-core:downloadBoost. The error message says that the SSL certificate of the server does not contain the appropriate Subject Alternative Names... but it does.

Here's the error message:
* What went wrong:
Execution failed for task ':expo-modules-core:downloadBoost'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > javax.net.ssl.SSLPeerUnverifiedException: Certificate for <jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]

Expected behaviour: the file is downloaded and the build proceeds
Observed behaviour: the build fails

### What platform(s) does this occur on?

Android

### SDK Version

46.0.13

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
      Yarn: 1.22.19 - ~/repos/app/app/node_modules/.bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.13 => 46.0.15
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.2 => 0.70.2
      react-native-web: ~0.18.7 => 0.18.9
      react-navigation: 4.4.4 => 4.4.4
    Expo Workflow: bare

### Minimal reproducible example

Create a fresh React Native project then run "./gradlew clean assembleDebug" or "./gradlew clean assembleRelease" in the "android" folder.

**Comment by tootsweet** [comment]
The more I look at it, the less it makes sense:
<img width="400" alt="Capture d’écran 2022-10-29 à 11 49 01" src="https://user-images.githubusercontent.com/27771251/198824980-4bfdd3fe-41c6-4aca-af28-e60f6cdf1b52.png">

**Comment by tootsweet** [comment]
One workaround is to add a dependency to the "assemble" lifecycle in my app's build.gradle:
<img width="700" alt="Capture d’écran 2022-10-29 à 12 38 20" src="https://user-images.githubusercontent.com/27771251/198826809-3e8afe04-0126-4b96-a764-7b793cb5ee4a.png">

**Comment by AlexanderEggers** [comment]
I have same issue when updating to Kotlin 1.7.20 - any other kotlin version works fine.

**Comment by tootsweet** [comment]
I provided an example. Anyway downgrading Kotlin fixes the issue.

**Comment by ErickJ3** [comment]
downgrading kotlin to version 1.6.0 resolves this issue
