### ISSUE TITLE
Universal Links not working on redirect in WebBrowser.openAuthSessionAsync

### ISSUE THREAD

**Issue by gregdburns** [expo/expo#19708]
### Summary

When using Expo WebBrowser to initiate an authentication session using Universal Links / App Links, no result is returned and the browser stays open.

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0
      expo: ^46.0.9 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

Due to dependencies on Universal / App Link setup and auth, I cannot create a snack, however here are the important pieces.

### Universal / App Link setup

1. apple-app-site-association and /.well-known/assetlinks.json are both set up and working.  When pressing on the link from the notes app, our mobile app launches successfully.

### Auth Code
`result = await WebBrowser.openAuthSessionAsync(authUrl, redirectUrl)`

In this case, the redirect value matches the Apple and Android config.  Ex: https://www.mydomain.com/path

### Flow

When openAuthSessionAsync is called, the backend authenticates the user and then does a browser redirect to the redirect URL.

### Expected Result

When the backend redirects, we should get a result from the call above and the browser should close.

### Actual Result

No result is returned and the browser stays open.

### Important Notes

1. The exact same redirect URL works fine if I copy / paste it into notes  and press it from there - the app launches.
2. When I add in a Linking event listener, I can actually get the result URL back _only on iOS and only on the first attempt_.

**Comment by keith-kurak** [comment]
I think I was able to reproduce this in a rough sense Expo Go on iOS by opening a website with a button linking to the Expo Go app's universal link, and the same behavior occurred: the universal link is ignored when opened via `openAuthSessionAsync` (and `openWebBrowserAsync`, for that matter), but is respected when opened from an external app. Snack here: https://snack.expo.dev/@keith-kurak/auth-example.

I'm having a hard time finding ironclad information on this, but some search results suggest that a universal link does not work within its own app. Apple's docs at least indicate that the behavior changes if the OS perceives that the user is already "inside the domain". I also don't see anything in the SDK code that would specifically prevent this. `expo-web-browser` is simply passing the link along to `SFSafariViewController` / `ASWebAuthenticationSession`. I suspect this is dependent on the OS and thus out of our control, but would like to pass the issue along for further analysis so we can at least learn more about why that is.

**Comment by gregdburns** [comment]
I should add that on iOS, it works consistently if I use these browser options:
```
const browserOptions = {
   preferEphemeralSession: true // iOS has clear cache each time, forces user to log in each time - works.
}
```
But on Android it doesn't work at all, even the first time with a clear browser cache / data.

With those options, however, the session isn't maintained and the user needs to auth each time they open the app.

**Comment by f4z3k4s** [comment]
@keith-kurak do you possibly have any further information on this? We experience the same issue, it's kind of frustrating. Sometimes our universal link redirects to our app after the end of a login flow, sometimes it doesn't. Happens with both `expo-web-browser` and `expo-auth-session` as well. Is there any option to solve or bypass this that you know of? Thanks in advance.

**Comment by MarcusHolanda1** [comment]
I have the same error, basically the redirect doesn't work, since I don't get any results, the interesting thing is that it worked before in my app, I think it stopped after I made some updates in the RN

**Comment by Tonyibra** [comment]
any updates? still not working

**Comment by Coderaxx** [comment]
Following as I'm experiencing the same issue

**Comment by marcel-mintouge** [comment]
Hi, I'm experiencing the Issue as well

**Comment by Ignaciomendezp** [comment]
Did anyone resolve it? I'm having same problem but only on android device (emulator works fine). iOS device also works.

**Comment by timmyd87** [comment]
Same issue here, no docs or resource to help - happens for me when the user isn't already logged into the browser so it redirects to login page. When they log in nothing happens, however when i dismiss the web view then attempt to login again, the code exchange works

**Comment by iketw** [comment]
@keith-kurak any updates on this issue? Should we just not use universal links with expo-web-browser?

**Comment by NotSimple** [comment]
Seems to be working on expo SDK 51 with expo-router. 

I tested on iOS with:
*  window.location.href = "myapp:///mypage" in the webpage. 
* `scheme: "myapp"` in expo config). 

Docs: https://docs.expo.dev/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl-options

**Comment by cgordon-d2l** [comment]
> Seems to be working on expo SDK 51 with expo-router.
> 
> I tested on iOS with:
> 
> * window.location.href = "myapp:///mypage" in the webpage.
> * `scheme: "myapp"` in expo config.
> 
> Docs: https://docs.expo.dev/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl-options

It seems that Deep Links (myapp://destination) are handled differently than Universal Links (iOS) or App Links (Android) (https://mysite.com/destination). I can get our app to redirect properly using openAuthSessionAsync with Deep Links, but not Universal Links.

**Comment by i-soy** [comment]
Is this issue resolved? I can't get universal links with "WebBrowser.openAuthSessionAsync" to work with the latest Expo etc.

**Comment by i-soy** [comment]
I have a workaround. So the redirect url (universal link to my app) is properly intercepted by my app after openAuthSessionAsync and authenticating. But then, since the route changes to a different layout and stack, it opens a totally new screen and removes the full original stack from which I've initiated openAuthSessionAsync. 

This was an issue for me since it is important in our app to return to the same screen and stack after authenticating. Finally I've found that you can intercept and change the loaded routes before it renders and removes the original state with: https://docs.expo.dev/router/advanced/native-intent/#using-redirectsystempath

This opens my app on the same screen when using the same route and state and even opens a new screen on top of that route if you require. 

See also:
https://docs.expo.dev/router/advanced/native-intent/#rewrite-incoming-native-deep-links

**Comment by badmuffin** [comment]
hey @notsimple,
you're using Custom URI callbacks, which perfectly works and here we are discussing about the Universal/App links (`https://`).

FYI, Custom URI callbacks are not secure because any app can register the same scheme and intercept your callback URLs.  
There is no built-in verification of ownership unlike Universal/App links (`https://`), which are tied to a verified domain.

Edit - Use expo sdk 55 or latest, Universal links are working fine, but we have to use custom uri callbacks for `iOS version <= 17.3`
