### ISSUE TITLE
console.log can not print logs in xde with iPad，but iPhone can

### ISSUE THREAD

**Issue by jianggaocheng** [expo/expo#1971]
When I use my iPhone or simulator, I can see the logs in the right panel of XDE or in iTerm window. But when I use my iPad, I can not see any logs....
I know it's strange, but I think I make sure I had connect my iPad and my laptop in the same network.
And the Live Reload is working well in my iPad, only logs function not work.

**Comment by anp** [comment]
Hi! Can you try uninstalling and reinstalling the Expo app on your iPad? If you're still having issues, can you open a topic in the [forums](https://forums.expo.io) with more information about what you've tried? We try to keep GitHub issues focused on reproducible bugs. Thanks!

**Comment by jianggaocheng** [comment]
I open a topic in forums, but and I saw your replay. but it seems that my account has been temporarily placed on hold. So I can not reply you in the forums now....
