### ISSUE TITLE
Camera is not able to scan inverted (datamatrix) QR code on Android.

### ISSUE THREAD

**Issue by nc-konc** [expo/expo#19724]
### Summary

[Camera ](https://docs.expo.dev/versions/latest/sdk/camera/)component is not able to scan inverted QR code (in datamatrix format) on Android, onBarCodeScanned callback is never invoked. On iOS devices it works.

Tested on: 
- Samsung A51 5G
- HAMMER Energy 18x9

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Minimal reproducible example

Run the following example and try to scan attached inverted QR code (in datamatrix format).

**Expected behaviour**: 'bar code scanned!' in application logs.
**Actual behaviour**: nothing happens.
```
import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Camera } from 'expo-camera';

export default function App() {
  const [hasPermission, setHasPermission] = useState(null);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestCameraPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (hasPermission === null) {
    return <View />;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }
  return (
      <Camera 
        onBarCodeScanned={()=>{console.log("bar code scanned!")}} 
        style={StyleSheet.absoluteFill}
      />
  );
}
```
![image](https://user-images.githubusercontent.com/92085949/198277435-685fee18-1250-4b88-9db1-8b7e996a78f1.png)

**Comment by Aysta453** [comment]
Any updates about inverted scan code?
