### ISSUE TITLE
Metro Bundler failed to start. (code: ENOTDIR) on Ubuntu

### ISSUE THREAD

**Issue by xeastcrast** [expo/expo#1973]
### Environment
https://exp-xde-diagnostics.s3.amazonaws.com/xeastcrast-49984341-abe1-44e7-8708-d267697d69f1.tar.gz

Error: Metro Bundler failed to start. (code: ENOTDIR)

### Actual Behavior

(Write what happened. Add screenshots!)
![image](https://user-images.githubusercontent.com/12433101/42499255-83a1a12c-8458-11e8-9878-ebed3a2fbe24.png)

**Comment by anp** [comment]
Hi! Can you try using the [new developer tools](https://blog.expo.io/announcing-expo-dev-tools-beta-c252cbeccb36) we announced recently and seeing whether this issue still reproduces?

Going to give this a close as there's not enough of the issue template completed to take action, but if this issue persists and you have more details, please post back and I'll reopen!
