### ISSUE TITLE
EAS build is generating an invalid android manifest file because of expo-channel-name set

### ISSUE THREAD

**Issue by soullivaneuh** [expo/expo#19733]
### Summary

On each EAS build, the job is setting the expo channel name like so:

```
Setting the update response headers in 'AndroidManifest.xml' to '{"expo-channel-name":"review-fix-app-info-verison-field"}'
```

However, it generate an invalid manifest file making `apkanalyser` crashing on it:

```
❯ apkanalyzer apk summary application-5b6fdb5a-24e9-4a2a-82b0-aa45c27a2c8b.apk

ERROR: org.xml.sax.SAXParseException; lineNumber: 151; columnNumber: 30; Element type "meta-data" must be followed by either attribute specifications, ">" or "/>".
```

And indeed, printing the complete xml file and going to the targeted line leads to this:

```xml
<meta-data
    android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY"
    android:value="{"expo-channel-name":"review-fix-app-info-verison-field"}" />
```

Which is invalid because of the double quote (`"`) usage inside the value. It should be escaped.

### What platform(s) does this occur on?

Android

### Environment

Not related, this is a EAS build related bug.

### Minimal reproducible example

N/A

**Comment by brentvatne** [comment]
hey there! EAS Build properly escapes this value - if you extract the apk and look at your AndroidManifest.xml you will see that. apkanalyzer unescapes it before parsing and this is a bug in apkanalyzer as far as i know. you can use aapt2 to read it - we use `aapt2 dump badging path/to/file.apk` in EAS Submit internals to read the applicationId.

![image](https://user-images.githubusercontent.com/90494/198410669-ec1eff67-9098-4240-996f-082cb0fa5c2b.png)

**Comment by soullivaneuh** [comment]
@brentvatne Thanks for the quick reply.

Even if it is not from your side, this situation is very problematic.

Do you have any related issue or tracking equivalent on Android side to resolve it? :thinking:
