### ISSUE TITLE
Expo SDK 42 -> 46 Migration Issue

### ISSUE THREAD

**Issue by andy-HM** [expo/expo#19739]
### Summary

I migrated my project from SDK 42 to 46.  There were some minor issues that I addressed and initially, I tested the web version of my product and all looked fine.  I then tested using iOS simulator and Expo Go (iOS) and am receiving the following errors in the console.  My app will not launch in any case in iOS on any environment.

TypeError: Prototype value can only be an object or null
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:40 in guardedLoadModule
at http://192.168.1.11:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code

Invariant Violation: "main" has not been registered. This can happen if:
** Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
** A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError

Per the SDK 46 upgrade instructions, I also ran `expo-cli doctor` and I receive the following output:

WARNING: expo-cli has not yet been tested against Node.js v18.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
** >=12.13.0 <15.0.0 (Maintenance LTS)
** >=16.0.0 <17.0.0 (Active LTS)

Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@2.0.4
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)

My questions are:
- Is this possibly related to the Node.js version?  I am thinking no because it worked on SDK version 42
- How do I fix the @expo/config-plugins package?  I have ran npm directly in my project, re-updated the expo-cli and flushed my cache with `expo start --clean`.  Nothing seems to be addressing the outdated versioning issues.
- Are these even the issue?  Seems that the @expo/config-plugins could be part of the issue but I'm not 100% sure that's the cause of my errors at the top of the post.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.5.1
      expo-cli: 6.0.6

### Minimal reproducible example

Please provide more direction on what would be helpful to share in this case.

**Comment by andy-HM** [comment]
As stated, I'm not 100% sure what to share at this point that would be helpful.  Can we start with understanding how to address the output from `expo-cli doctor`?  That was one of my questions, how do I address the dependencies listed in the output:

WARNING: expo-cli has not yet been tested against Node.js v18.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
** >=12.13.0 <15.0.0 (Maintenance LTS)
** >=16.0.0 <17.0.0 (Active LTS)

Expected package @expo/config-plugins@^5.0.0
Found invalid:
@expo/config-plugins@2.0.4
@expo/config-plugins@4.1.5
(for more info, run: npm why @expo/config-plugins)

I have updated the expo CLI to the latest but there does not appear to be any way to affect the @expo/config-plugins versions.

**Comment by brentvatne** [comment]
```
Expected package @expo/config-plugins@^5.0.0
Found invalid:
@expo/config-plugins@2.0.4
@expo/config-plugins@4.1.5
(for more info, run: npm why @expo/config-plugins)
```

that's useful information! track down which packages are installing those old versions of @expo/config-plugins and update them or remove them

**Comment by andy-HM** [comment]
Hello @brentvatne , thank you!  per your recommendation I went down the path of looking and ended up blowing away my node_modules and completely reinstalling all modules in the package.
