### ISSUE TITLE
UIImagePickerPresentationStyle not working

### ISSUE THREAD

**Issue by tb42** [expo/expo#19740]
### Summary

UIImagePickerPresentationStyle is not altering the way imagePicker is displayed, regardless of which enum is used, the ios default presentation which displays over the fullscreen is what renders. 

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.9.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.0.3
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Mac OS Monterey, Expo iOS simulator

### Error output

No error messages are rendering

### Reproducible demo or steps to reproduce from a blank project

Below are the relevant imports as well as code for the function that opens the imagePicker. In this enum instance, i've tried "pagesheet" as well as "PAGE_SHEET", both do nothing.

```
import * as ImagePicker from "expo-image-picker";
import { UIImagePickerPresentationStyle } from "expo-image-picker/build/ImagePicker.types";
```

```
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      // allowsEditing: true,
      // allowsMultipleSelection: true,
      aspect: [1, 1],
      quality: 0.25,
      presentationStyle: UIImagePickerPresentationStyle.PageSheet,
    });
```

**Comment by Kudo** [comment]
hi there! i've tried your example on snack: https://snack.expo.dev/@kudochien/expo-issue-19740, and it works for me. if you still encounter the issue, please let me know and i'm happy to reopen this issue.
