### ISSUE TITLE
Some schemes might break Android verified app links

### ISSUE THREAD

**Issue by byCedric** [expo/expo#19745]
### Summary

One of our partners reported issues in verifying app links on Android. They added the `expo.android.intentFilters`, with the `autoVerify` property set to true. We found out that the added scheme by the dev client (`<data android:scheme="exp+<slug>" />`), was also added to these intent filters. That scheme broke the app link verification process on Android.

Unfortunately, [starting from Android 12, verifying your app links seems required to even be listed in the "Open with app" list.](https://www.xda-developers.com/android-12-will-always-open-non-verified-links-in-the-default-browser/)

Looking at the [dev client's config plugin](https://github.com/expo/expo/blob/main/packages/expo-dev-client/plugin/src/withGeneratedAndroidScheme.ts#L25):

```
// Generate a cross-platform scheme used to launch the dev client.
const scheme = getDefaultScheme(config);
if (!AndroidConfig.Scheme.hasScheme(scheme, androidManifest)) {
  androidManifest = AndroidConfig.Scheme.appendScheme(scheme, androidManifest);
}
return androidManifest;
```

There is no great way for plugins to not add a scheme to custom intent filters, or to remove them specifically from the `autoVerify`-ed intent filters.

## **AndroidManifest.xml** activity examples

<details>
  <summary>Example activity intent filters in <b>AndroidManifest.xml</b> that breaks</summary>

```xml
<activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:screenOrientation="portrait">
  <intent-filter>
    <action android:name="android.intent.action.MAIN"/>
    <category android:name="android.intent.category.LAUNCHER"/>
  </intent-filter>
  <intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="<slug>"/>
    <data android:scheme="<package>"/>
    <data android:scheme="exp+<slug>"/>
  </intent-filter>
  <intent-filter android:autoVerify="true" data-generated="true">
    <action android:name="android.intent.action.VIEW"/>
    <data android:scheme="https" android:host="<name>.onelink.me" android:pathPrefix="/XXXX"/>
    <data android:scheme="https" android:host="<name>.onelink.me" android:pathPrefix="/XXXX"/>
    <data android:scheme="https" android:host="<name>.onelink.me" android:pathPrefix="/XXXX"/>
    <data android:scheme="exp+<slug>"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <category android:name="android.intent.category.DEFAULT"/>
  </intent-filter>
</activity>
```

</details>

<details>
  <summary>Example activity intent filters in <b>AndroidManifest.xml</b> that works</summary>

```xml
<activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:screenOrientation="portrait">
  <intent-filter>
    <action android:name="android.intent.action.MAIN"/>
    <category android:name="android.intent.category.LAUNCHER"/>
  </intent-filter>
  <intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="<slug>"/>
    <data android:scheme="<package>"/>
    <data android:scheme="exp+<slug>"/>
  </intent-filter>
  <intent-filter android:autoVerify="true" data-generated="true">
    <action android:name="android.intent.action.VIEW"/>
    <data android:scheme="https" android:host="<name>.onelink.me" android:pathPrefix="/XXXX"/>
    <data android:scheme="https" android:host="<name>.onelink.me" android:pathPrefix="/XXXX"/>
    <data android:scheme="https" android:host="<name>.onelink.me" android:pathPrefix="/XXXX"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <category android:name="android.intent.category.DEFAULT"/>
  </intent-filter>
</activity>
```

</details>

## Workaround plugin that pulls the `exp+` schemes from auto verifying intent filters

<details>
  <summary><b>withAndroidVerifiedLinksWorkaround.js</b></summary>

```js
const { createRunOncePlugin, withAndroidManifest } = require('@expo/config-plugins');

/**
 * @typedef {import('@expo/config-plugins').ConfigPlugin} ConfigPlugin
 * @typedef {import('@expo/config-plugins').AndroidManifest} AndroidManifest
 */

/**
 * Remove the custom Expo dev client scheme from intent filters, which are set to `autoVerify=true`.
 * The custom scheme `<data android:scheme="exp+<slug>"/>` seems to block verification for these intent filters.
 * This plugin makes sure there is no scheme in the autoVerify intent filters, that starts with `exp+`.
 * 
 * @type {ConfigPlugin}
 */
const withAndroidVerfiedLinksWorkaround = (config) => (
  withAndroidManifest(config, (config) => {
    config.modResults = removeExpoSchemaFromVerifiedIntentFilters(config.modResults);
    return config;
  })
);

/**
 * Iterate over all `autoVerify=true` intent filters, and pull out schemes starting with `exp+`.
 * 
 * @param {AndroidManifest} androidManifest
 */
function removeExpoSchemaFromVerifiedIntentFilters(androidManifest) {
  // see: https://github.com/expo/expo-cli/blob/f1624c75b52cc1c4f99354ec4021494e0eff74aa/packages/config-plugins/src/android/Scheme.ts#L164-L179
  for (const application of androidManifest.manifest.application || []) {
    for (const activity of application.activity || []) {
      if (activityHasSingleTaskLaunchMode(activity)) {
        for (const intentFilter of activity['intent-filter'] || []) {
          if (intentFilterHasAutoVerification(intentFilter) && intentFilter?.data) {
            intentFilter.data = intentFilterRemoveSchemeFromData(intentFilter, (scheme) => scheme?.startsWith('exp+'));
          }
        }
        break;
      }
    }
  }

  return androidManifest;
}

/**
 * Determine if the activity should contain the intent filters to clean.
 * 
 * @see https://github.com/expo/expo-cli/blob/f1624c75b52cc1c4f99354ec4021494e0eff74aa/packages/config-plugins/src/android/Scheme.ts#L166
 */
function activityHasSingleTaskLaunchMode(activity) {
  return activity?.$?.['android:launchMode'] === 'singleTask';
}

/**
 * Determine if the intent filter has `autoVerify=true`.
 */
function intentFilterHasAutoVerification(intentFilter) {
  return intentFilter?.$?.['android:autoVerify'] === 'true';
}

/**
 * Remove schemes from the intent filter that matches the function.
 */
function intentFilterRemoveSchemeFromData(intentFilter, schemeMatcher) {
  return intentFilter?.data?.filter(entry => !schemeMatcher(entry?.$['android:scheme'] || ''));
}

module.exports = createRunOncePlugin(withAndroidVerfiedLinksWorkaround, 'withAndroidVerfiedLinksWorkaround', '1.0.0');
```

</details>

### Environment

```
  Expo CLI 5.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

Android 12

### Error output

_none_

### Reproducible demo or steps to reproduce from a blank project

Verifying app links is a delicate process, you can find some debugging options here: https://developer.android.com/training/app-links/verify-site-associations#check-link-policies

**Comment by nakedgun** [comment]
Same issue happens with the expo plugin for `react-native-fbsdk-next`. It appends this to the intent filters which breaks **autoVerify** in the same way, e.g:

```
<data android:scheme="fbXXX"/>
```

See: https://github.com/thebergamo/react-native-fbsdk-next/issues/329

**Comment by MorenoMdz** [comment]
> 

We are facing this issue currently with RN-Firebase and dynamic links, the same setup works fine in iOS and pre Android 12 builds. We have tried the config plugin route without success yet. Would be good to have an update if this issue is being worked on and or of it was tied to the Expo dev client or other libraries.

**Comment by dnelsonlivecurrence** [comment]
This is a legit issue that people are reporting (and we are also running into), but the Expo team doesn't respond and the issue just gets marked as stale and closed by a bot. Really makes me confident about paying for Expo.

**Comment by jserrao** [comment]
Did this get fixed somehow?

**Comment by ryonwhyte** [comment]
In case someone else has this issue. I used the workaround, but it did not entirely solve the issue. In my case there are 2 https schemes in the androidManifest file one in the intent for my deep link and one in the intent containing some other schemes for Facebook expo etc. That scheme did not have a path, so it appears to have matched every scheme beginning with https.

I wrote a config plugin to search the manifest and remove any extra https scheme that is not in an intent with AutoVerify. It works in my case, and I figure it could also work for some still having the issue after using the workaround. It can be combined with the Workaround code.

`const {
  createRunOncePlugin,
  withAndroidManifest,
} = require("@expo/config-plugins");

/**
 * @typedef {import('@expo/config-plugins').ConfigPlugin} ConfigPlugin
 * @typedef {import('@expo/config-plugins').AndroidManifest} AndroidManifest
 */

/**
 * Remove the `https` scheme from intent filters that do not have `autoVerify=true`.
 *
 * @type {ConfigPlugin}
 */
const withRemoveHttpSchemeFromIntentFilters = (config) =>
  withAndroidManifest(config, (config) => {
    config.modResults = removeHttpSchemeFromIntentFilters(config.modResults);
    return config;
  });

/**
 * Remove the `https` scheme from intent filters that do not have `autoVerify=true`.
 *
 * @param {AndroidManifest} androidManifest
 */
function removeHttpSchemeFromIntentFilters(androidManifest) {
  // Iterate through the application's activities and their intent filters
  for (const application of androidManifest.manifest.application || []) {
    for (const activity of application.activity || []) {
      if (activityHasSingleTaskLaunchMode(activity)) {
        for (const intentFilter of activity["intent-filter"] || []) {
          if (!intentFilterHasAutoVerification(intentFilter)) {
            // Remove the `https` scheme from the intent filter if it doesn't have `autoVerify=true`
            if (intentFilter.data && Array.isArray(intentFilter.data)) {
              intentFilter.data = intentFilter.data.filter(
                (entry) => entry?.$["android:scheme"] !== "https"
              );
            }
          }
        }
        break;
      }
    }
  }

  return androidManifest;
}

/**
 * Determine if the activity should contain the intent filter to clean.
 */
function activityHasSingleTaskLaunchMode(activity) {
  return activity?.$?.["android:launchMode"] === "singleTask";
}

/**
 * Determine if the intent filter has `autoVerify=true`.
 *
 * @param {object} intentFilter
 */
function intentFilterHasAutoVerification(intentFilter) {
  return intentFilter?.$?.["android:autoVerify"] === "true";
}

module.exports = createRunOncePlugin(
  withRemoveHttpSchemeFromIntentFilters,
  "withRemoveHttpSchemeFromIntentFilters",
  "1.0.0"
);
`
