### ISSUE TITLE
TS types ships with non-existent references

### ISSUE THREAD

**Issue by SimenB** [expo/expo#19744]
### Summary

See https://www.runpkg.com/?@expo/config-plugins@4.0.6/build/ios/Swift.d.ts#1

This references types from `xcode` which only exists in this repo: https://github.com/expo/expo-cli/blob/2236dbbc2b130b88441adaacc6f5091ea9eff2d8/ts-declarations/xcode/index.d.ts#L17

This causes TypeScript errors in my own project.

Not sure of the best way to solve this. Copying the definition into every project which uses it sounds painful. Maybe create an `@expo/xcode` that is just `module.exports = require('xcode');` (and any file export you need) and include the types there?

---

I can get around this by using `skipLibCheck` (or what I've done, which is patch `xcode` to include dummy interfaces), but the types shipped by `@expo/config-plugins` should be working ones.

### Environment

N/A

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

```
../../node_modules/@expo/config/node_modules/@expo/config-plugins/build/ios/Swift.d.ts:1:23 - error TS2688: Cannot find type definition file for 'xcode'.

1 /// <reference types="xcode" />
                        ~~~~~

../../node_modules/@expo/config/node_modules/@expo/config-plugins/build/ios/XcodeProjectFile.d.ts:1:23 - error TS2688: Cannot find type definition file for 'xcode'.

1 /// <reference types="xcode" />
```

### Reproducible demo or steps to reproduce from a blank project

I don't think this is needed, but happy to add if you think so

**Comment by EvanBacon** [comment]
Ultimately we should just migrate to [`xcparse`](https://github.com/EvanBacon/xcparse/) but perhaps we could export the types as well.

**Comment by SimenB** [comment]
Not stale
