### ISSUE TITLE
Issue with "eas build -p android" to add google Signup & Login  

### ISSUE THREAD

**Issue by khadkaPratik** [expo/expo#19755]
### Summary

** Issue **
📝  Android package Learn more: https://expo.fyi/android-package
[stderr] CommandError: Input is required, but 'npx expo' is in non-interactive mode.
[stderr] Project must have a `android.package` set in the Expo config (app.json or app.config.js).
Error: Unknown error. See logs for more information.

**Here are the steps to replicate the issue ?** 

1. Build application using expo cli 45
2. Tried adding login using [Expo Guide Google Sign-in](https://docs.expo.dev/versions/v45.0.0/sdk/google-sign-in/)(It ran perfectly in the local server within expo go but didn't work in the production server )
3. Google Sign-in Package(Expo): [https://github.com/react-native-google-signin/google-signin#expo-installation]
4. Firebase: [https://firebase.google.com/]
5. Followed  Guide [rnfirebase](https://rnfirebase.io/auth/social-auth)
6. React Native Firebase: [https://rnfirebase.io/]
7.  Social Auth Google: [https://rnfirebase.io/auth/social-auth#google]
8.  Listening to authentication state: [https://rnfirebase.io/auth/usage#listening-to-authentication-state]
9. eas build -p android

** Tried & Tested solution for available forms  **

1.  Expo Cli Upgrade to 46 & update all the packages 
2. Remove the package name to reenter during the build process 
4.  Switched to nvm to manage multiple node version installation 
5.  Changed behavior: web;
6. Adding custom native code: [https://docs.expo.dev/workflow/customizing/]
7.  Development Build: [https://docs.expo.dev/development/getting-started/]

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

 "expo-dev-client": "~0.8.6",
 "expo-updates": "~0.11.7",

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.16
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 2.4.1
    Expo Workflow: managed

### Reproducible demo

import 'expo-dev-client';

**Comment by brentvatne** [comment]
```
📝 Android package Learn more: https://expo.fyi/android-package
[stderr] CommandError: Input is required, but 'npx expo' is in non-interactive mode.
[stderr] Project must have a android.package set in the Expo config (app.json or app.config.js).
Error: Unknown error. See logs for more information.
```

your app config may be invalid
