### ISSUE TITLE
Lottie (DangerZone) animations crashing only in android expo client app new update

### ISSUE THREAD

**Issue by lazantha** [expo/expo#1975]
Lottie animation is crashing only in android (I'm not using images for the animation), it did work before in andriod and also still working on ios. This happened after updating expo client apk.... does anyone know how to fix this?

**Comment by nikki93** [comment]
More information -- error message, maybe some code, etc. -- please. If the error information you get is deeper inside Lottie, could also be worth asking at https://github.com/react-community/lottie-react-native.

**Comment by brentvatne** [comment]
closing because no further information was provided, please feel free to create a new issue with more context when you have time if the issue has persisted!
