### ISSUE TITLE
expo-auth-session: Prompt option not working for Facebook provider

### ISSUE THREAD

**Issue by haeniya** [expo/expo#19757]
### Summary

I'm using `expo-auth-session` to allow users to login via Facebook and Google in my Expo app.

I want users to be able to switch accounts after the initial login. They should always get prompted to login again or select an account when signin in.
Currently, when users try to log in with the Facebook provider after the initial login, the user interaction to provide credentials is skipped. Therefore, users do not have the option to change their account.

There has already been a discussion about this in the past (https://github.com/expo/expo/issues/7879), which resulted in a change that introduced the `Prompt` option (https://docs.expo.dev/versions/latest/sdk/auth-session/#prompt). However, this option doesn't seem to work for the Facebook provider (tried with `Prompt.SelectAccount` and `Prompt.Login`). With the Google provider, it works as expected.

Am I missing something or is there maybe another way to achieve this?

Additional information:
* Clear cookies in RN natively doesn't seem to work on iOS
* There is a cookie manager for RN (https://github.com/react-native-cookies/cookies) but this package doesn't work with Expo Go
* As far as I know `revokeAsync()` can not be used with the Facebook provider

### What platform(s) does this occur on?

Android, iOS

### Environment

System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31
        Build Tools: 28.0.3, 30.0.3
        System Images: Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
    IDEs: Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
     expo-auth-session: 3.6.1
    Expo Workflow: managed

### Minimal reproducible example

```js
const [facebookSignInRequest, facebookSignInResponse, facebookSignInPromptAsync] = Facebook.useAuthRequest(
  {
    responseType: ResponseType.Token,
    clientId: FACEBOOK_APP_ID,
    redirectUri: makeRedirectUri({ useProxy: true }),
    prompt: Prompt.SelectAccount
  },
  { useProxy: true }
);

React.useEffect(() => {
  if (facebookSignInResponse?.type === 'success') {
    const { access_token } = facebookSignInResponse.params;
    const auth = getAuth();
    const credential = FacebookAuthProvider.credential(access_token);
    // Sign in with the credential from the Facebook user in Firebase.
    signInWithCredential(auth, credential);
  }
}, [facebookSignInResponse]);
```

**Comment by haeniya** [comment]
Over a month old already. Anything else I can provide or do to get a response?

**Comment by MarouaniALA** [comment]
@brentvatne is it the correct behaviour for expo-auth-session that doesn't open the native facebook app for facebook login?

**Comment by brentvatne** [comment]
@MarouaniALA - yes, you can use [react-native-fbsdk-next](https://www.npmjs.com/package/react-native-fbsdk-next) if you'd like to open the native facebook app

**Comment by MarouaniALA** [comment]
@brentvatne thanks it worked

**Comment by amandeepmittal** [comment]
We've deprecated Google and Facebook auth providers from `expo-auth-session` starting SDK 49. We recommend using a native library such as [@react-native-google-signin/google-signin](https://github.com/react-native-google-signin/google-signin) & [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/).

We don't maintain these native libraries. However, we did write a short guide on what steps might be required to configure an Expo project: https://docs.expo.dev/guides/google-authentication/ & https://docs.expo.dev/guides/facebook-authentication/, when using these libraries.
