### ISSUE TITLE
Constants.manifest is broken and so is Constants.expoConfig

### ISSUE THREAD

**Issue by DianaKoenraadt** [expo/expo#19762]
### Summary

`Constants.manifest?.version` always returns undefined
`Constants.manifest?.ios?.buildNumber` always returns undefined
`Constants.manifest?.android?.versionCode` also always returns undefined

Replacing `manifest` with `expoConfig` does not work. 
Please can someone tell me what the new way to do this is? I need it for debugging and support.

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.2.0 - ~\AppData\Roaming\npm\yarn.CMD    
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335     
    npmPackages:
      @expo/metro-config: ^0.1.40 => 0.1.84 
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3        
      react-navigation: ^4.4.0 => 4.4.4
    Expo Workflow: managed

### Minimal reproducible example

-

**Comment by baochungit** [comment]
As mentioned in Expo Documentation, once `Constants.manifest` is null, the `Constants.manifest2` will present.
You could check `Constants.manifest2.extra.expoClient` to see if it works.

**Comment by phryneas** [comment]
In case it helps someone, I did now end up with
```ts
function getExtra(constant: string) {
    for (const extra of [Constants.manifest?.extra, Constants.manifest2?.extra, Updates.manifest?.extra]) {
        const c = extra?.[constant] ?? extra?.expoClient?.extra?.[constant];
        if (c) return c;
    }
    throw new Error(`constant ${constant} not found in manifest.`);
}
```

So there are six possible places and I'm not sure which one is there when.

`Constants.manifest.extra`, `Constants.manifest.extra.expoClient.extra`, `Constants.manifest2.extra`, `Constants.manifest2.extra.expoClient.extra`, `Updates.manifest.extra`, `Updates.manifest.extra.expoClient.extra`,

**Comment by brentvatne** [comment]
can someone share a reproducible example that demonstrates the issue with `Constants.expoConfig`?

**Comment by ide** [comment]
`Constants.expoConfig` was introduced to replace almost all the use cases of `Constants.manifest` and remove the need to try to switch between accessing `Constants.manifest` and `Constants.manifest2`, obviously no one wants to have to discern between those two APIs. The `manifest` and `manifest2` properties aren't formally deprecated yet but treat them as softly deprecated in favor of `expoConfig`.

The original post mentioned using Expo SDK 44. `Constants.expoConfig` was introduced in SDK 46. Like Brent suggested above, try upgrading to SDK 47 (or perhaps an easier path is to make a new test project with `npx expo init` just to try things out) and using [`Constants.expoConfig`](https://docs.expo.dev/versions/latest/sdk/constants/#nativeconstants--properties).

**Comment by events-jonas-chrisw** [comment]
This doesn't work at all on Metro web

**Comment by ide** [comment]
@events-jonas-chrisw Could you please be more precise?

**Comment by events-jonas-chrisw** [comment]
> @events-jonas-chrisw Could you please be more precise?

When i use expo constants on android or IOS, Constants.expoConfig has a complete object.
If I build using metro for web, the object is empty

**Comment by ide** [comment]
@events-jonas-chrisw Thank you. I'll take a look when I have some time. If investigating this in a timely manner is important to you I recommend having a look at the code and seeing if you can't figure out what the cause is / what's going on.

**Comment by ide** [comment]
@events-jonas-chrisw Constants.expoConfig on web for SDK 49 requires the Expo Router Babel plugin. In SDK 50+ (upcoming), the Expo (not Expo Router) Babel plugin will have support for Constants.expoConfig [built in](https://github.com/expo/expo/pull/24779).

[Related issue](https://github.com/expo/expo/issues/23819)
