### ISSUE TITLE
[Android] The pictures frozen when record video via facing-front

### ISSUE THREAD

**Issue by JoyHong** [expo/expo#1976]
Dear thanks very much for the record function.

But i have a very important issue that when i'm recoding video via facing-front, the pictures are frozen, but if i use back-front, it's ok. Could you please help to have a check?

btw, my device is nexus 5, and camera1 is ok, camera2 is not ok.

**Comment by JoyHong** [comment]
@nikki93 @barthec 

Dears, any update?

**Comment by barthec** [comment]
@JoyHong I'm taking a look at camera right now and hoping to provide solution to this case. Unfortunately there is also some other issue that is worrying us as well #1981. I'm closing this ticket as I'm going to fix it in mentioned ticket.

**Comment by barthec** [comment]
@m4tx took over this case and it's currently trying to recreate your problem. Fix would be provided as fast as the reason causing these freezes is found. In addition, could you provide minimal code visualising this problem (e.g. using [snack.expo.io](https://snack.expo.io))?

**Comment by m4tx** [comment]
@JoyHong is the issue still present in SDK 30?

**Comment by JoyHong** [comment]
yes, i copy the cameraview library to my project, still doesn't work...
Do i missed sth?

**Comment by esamelson** [comment]
closing this as it's stale and a fix was landed long ago. If you're still experiencing this issue, please open a new ticket and fill out the template completely, including a clear repro case. Thanks!

**Comment by JoyHong** [comment]
it works, thank you very much.
