### ISSUE TITLE
EAS Build - package.json not included in upload

### ISSUE THREAD

**Issue by andy-HM** [expo/expo#19772]
### Summary

I am running `eas build` for Android.  However, I am receiving the attached error in the EAS console.  

The error shown is: "package.json does not exist in /home/expo/workingdir/build/HeroesFromCupid"

When I run `eas build:inspect` I can see that my package.json is not included in the upload and I'm not sure why.  This file is not being ignored.

<img width="1108" alt="Screen Shot 2022-10-28 at 8 32 07 PM" src="https://user-images.githubusercontent.com/74470025/198755837-8152cabb-3cf7-4f55-9eaa-7ac04aa859d2.png">

### SDK Version

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.6

### Minimal reproducible example

eas build
✔ Select platform › Android
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials

Compressing project files and uploading to EAS Build. Learn more
✔ Compressed project files 1s (17.1 MB)
✔ Uploaded to EAS 8s

Waiting for build to complete. You can press Ctrl+C to exit.
✖ Build failed

🤖 Android build failed:
Unknown error. See logs for more information.

**Comment by andy-HM** [comment]
Additional information, I ran a simulator build for iOS but am receiving the same error in the EAS console. 

`eas build -p ios --profile preview`

Following the guide [here](https://docs.expo.dev/build-reference/simulators/).

Really needing some direction here.

**Comment by wodin** [comment]
Hi @andy-HM 

Your "Minimal reproducible example" is not sufficient for someone else to reproduce the problem.

Try creating a new Expo app and making small incremental changes to it to make it look more and more like your app until it fails in the same way. Then post it somewhere, or the step by step instructions for how to re-create it. You should not need to modify `App.js` or add your actual JavaScript source code. If you have the app in a mono repo or something like that you will presumably need to reproduce at least some of the directory structure etc. from your real app.

**Comment by andy-HM** [comment]
Hi @wodin 

I was able to get this particular issue figured out by using:

  "cli": {
    "requireCommit": true
    ...
  },

Within my eas.json.  

Completely understand the need for a "Minimal reproducible example".  However, there are some situations where taking the time and providing an example are not really fruitful.  In my case, I was really looking for more information about how EAS build works and how it could be excluding my package.json for seemingly no explanation.

In this case, I understand why the above worked but it's still unclear how the build process is choosing files when the above is not applied.

**Comment by wodin** [comment]
Hi @andy-HM 

Yes, I don't know why it would have been ignoring your `package.json` if you didn't have it in `.gitignore` and you didn't have a `.easignore`. I have not encountered that situation myself.  My understanding is that it only looks at `.gitignore` and `.easignore` and not any of the other ways that Git can ignore things.

The only thing that came to mind was that it could have been misdetecting the root of your project for some reason and I suppose maybe it could have done that if you had some sort of monorepo setup.

After adding `"requireCommit": true` did it force you to commit something? If so, what was it?

**Comment by andy-HM** [comment]
Hey @wodin,

The only thing it forced me to commit were the changes I had staged, nothing new or that I hadn't simply committed yet.
