### ISSUE TITLE
Expo Go not updated when reloading

### ISSUE THREAD

**Issue by snipsnap0000** [expo/expo#19775]
### Summary

Expo Go not updated when reloading when pressing r in the console
› Press r │ reload app
Web version is reloaded fine.

### What platform(s) does this occur on?

Android

### SDK Version

46

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD

### Minimal reproducible example

Follow this https://fullstackopen.com/en/part10/introduction_to_react_native

**Comment by Simek** [comment]
Hello @snipsnap0000, since you are referring to non-official guide (and not the project source code), it's hard to guess what might be wrong.

If you will be able to produce minimal reproducible example where the reload won't work feel free to create new issue.
