### ISSUE TITLE
[SDK 46] EAS Build Failed with Exist Status 65

### ISSUE THREAD

**Issue by lifesmile-ae** [expo/expo#19774]
### Summary

Hi, 
While publishing using 
`eas build -p ios --profile production-ios`
I am getting the following FastLane error which I had never seen before and don't know the way to fix this:
`The following build commands failed:
	CompileC /Users/expo/Library/Developer/Xcode/DerivedData/lifesmile-epzjiqmuwpqabggewnatjchafarp/Build/Intermediates.noindex/ArchiveIntermediates/lifesmile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/UMReactNativeAdapter.build/Objects-normal/arm64/UMReactNativeEventEmitter.o /Users/expo/workingdir/build/node_modules/@unimodules/react-native-adapter/ios/UMReactNativeAdapter/Services/UMReactNativeEventEmitter.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'UMReactNativeAdapter' from project 'Pods')`

What is causing the issue and how to resolve this ???

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

This I think I cannot make any reporducible

**Comment by Kudo** [comment]
hi there! we cannot help without a repro. it looks like you have `@unimodules/react-native-adapter` in your dependencies which is deprecated from sdk 43. please remove this dependency and may refer to the migration guide: https://expo.fyi/expo-modules-migration
