### ISSUE TITLE
[docs] Clarify whether it is necessary to use yarn classic as linked on https://docs.expo.dev/get-started/installation/ ? 

### ISSUE THREAD

**Issue by ldorigo** [expo/expo#19779]
### Summary

In https://docs.expo.dev/get-started/installation/#requirements , you link to yarn classic - clicking on the yarn link brings to a page warning the user that it's an end-of-life release. 

- If it's voluntary: make it explicit that it's better to use yarn classic for whatever reason
- Otherwise: link to latest yarn version?

This might seem like nitpicking but to a new user who's trying to follow instructions to the letter to figure out why his builds don't work, it adds another layer of uncertainty :-)

### Link to the related docs page

https://docs.expo.dev/get-started/installation/#requirements

**Comment by amandeepmittal** [comment]
Thanks for bringing this up @ldorigo!
We'll look into updating the doc to add more clarity.

**Comment by amandeepmittal** [comment]
I'm closing this since this section reflects why it is recommended to use Yarn Classic V1. For a more in-depth information, check out this comment on a related issue: https://github.com/expo/expo/issues/28057#issuecomment-2040496050.
