### ISSUE TITLE
Notifications.getDevicePushTokenAsync() can't get deviceToken

### ISSUE THREAD

**Issue by watanabeyu** [expo/expo#1977]
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.2.1
  Yarn: 0.27.5
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.4.1 => 16.4.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Target: iOS Standalone

### Steps to Reproduce

```
const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
let finalStatus = existingStatus;

if (existingStatus !== 'granted') {
  const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
  finalStatus = status;
}

if (finalStatus !== 'granted') {
  return;
}

try {
  const token = await Notifications.getDevicePushTokenAsync();
  Alert.alert('getDevicePushTokenAsync', JSON.stringify(token), [{ text: 'copy', onPress: () => Clipboard.setString(JSON.stringify(token)) }]);
} catch (err) {
  Alert.alert('error', JSON.stringify(err));
}
```

I want to get device push token.
So I use getDevicePushTokenAsync, but can't get it.

### Expected Behavior

getDevicePushTokenAsync return token.

### Actual Behavior

Actually return error, but it have a token data.
```
{"framesToPop":1,"type":"apns","data":"c399ac5efe5850d56eaab7b4a530fa8e643d9b3db2de1098fbb3cfd831005683","line":18,"column":1599,"sourceURL":"https://d1wp6m56sqw74a.cloudfront.net/xxxxxxxxxxxx-28.0.0-ios.js"}
```

Why return token in error?

**Comment by dwyanelin** [comment]
getExpoPushTokenAsync

**Comment by watanabeyu** [comment]
@dwyanelin 
I want to use Amazon SNS, so that I want to use getDevicePushTokenAsync(), not getExpoPushTokenAsync().

**Comment by dwyanelin** [comment]
> @dwyanelin
> I want to use Amazon SNS, so that I want to use getDevicePushTokenAsync(), not getExpoPushTokenAsync().

Sorry, I didn't read the question carefully.

**Comment by tsapeta** [comment]
SDK28 that you used when creating this issue is no longer supported, so I'm gonna close this issue. Please create a new issue if this still happens in any of the currently supported SDK versions.
