### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_ExponentCameraManager.default.Type')

### ISSUE THREAD

**Issue by alexander01202** [expo/expo#19783]
### Summary

Hello. I am trying to use expo-camera and I keep getting this error when I import it :

`import {camera} from 'expo-camera'`

I am using the development build.

I am using expo 44 sdk

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"dependencies": {
    "@cometchat-pro/react-native-chat": "^3.0.10",
    "@eliav2/react-native-collapsible-view": "^1.4.0",
    "@gorhom/bottom-sheet": "^4.3.0",
    "@notifee/react-native": "^5.2.2",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/netinfo": "7.1.3",
    "@react-native-firebase/app": "^15.1.1",
    "@react-native-firebase/messaging": "^15.1.1",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-native-picker/picker": "2.2.1",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/material-top-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@sentry/react-native": "^4.6.1",
    "ajv": "^8.11.0",
    "api": "^4.5.1",
    "bcrypt": "^5.0.1",
    "dotenv": "^16.0.1",
    "expo": "~44.0.0",
    "expo-app-loading": "~1.3.0",
    "expo-av": "~10.2.0",
    "expo-background-fetch": "~10.1.0",
    "expo-crypto": "~10.1.1",
    "expo-dev-client": "~0.8.6",
    "expo-device": "~4.1.0",
    "expo-document-picker": "~10.1.3",
    "expo-file-system": "~13.1.4",
    "expo-font": "~10.0.4",
    "expo-haptics": "~11.1.0",
    "expo-image-manipulator": "~10.2.0",
    "expo-image-picker": "~12.0.1",
    "expo-linear-gradient": "~11.0.3",
    "expo-location": "~14.0.1",
    "expo-media-library": "~14.0.0",
    "expo-notifications": "~0.14.0",
    "expo-random": "~12.1.1",
    "expo-server-sdk": "^3.6.0",
    "expo-sharing": "~10.1.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-task-manager": "~10.1.0",
    "express": "^4.17.3",
    "lottie-react-native": "5.0.1",
    "mailersend": "^1.4.5",
    "messagebird": "^3.7.2",
    "mixpanel-react-native": "^1.5.0",
    "moment": "^2.29.3",
    "mysql": "^2.18.1",
    "node-fetch": "^3.2.6",
    "onesignal-expo-plugin": "^1.0.2",
    "paystack": "^2.0.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-animatable": "^1.3.3",
    "react-native-animated-loader": "^0.0.9",
    "react-native-animated-splash-screen": "^2.0.5",
    "react-native-collapsible": "^1.6.0",
    "react-native-dotenv": "^3.3.1",
    "react-native-easy-content-loader": "^0.3.2",
    "react-native-fast-image": "^8.6.1",
    "react-native-flash-message": "^0.2.1",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-indicators": "^0.17.0",
    "react-native-maps": "0.29.4",
    "react-native-maps-directions": "^1.8.0",
    "react-native-mask-loader": "^0.0.3",
    "react-native-masked-loader": "^1.1.4",
    "react-native-onboarding-swiper": "^1.2.0",
    "react-native-onesignal": "^4.3.11",
    "react-native-open-maps": "^0.4.0",
    "react-native-pager-view": "5.4.9",
    "react-native-phone-call": "^1.0.9",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-select-dropdown": "^1.11.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.3.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-web": "0.17.1",
    "react-redux": "^7.2.8",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1",
    "rusha": "^0.8.14",
    "sentry-expo": "^5.0.3",
    "socket.io": "^4.4.1",
    "socket.io-client": "^4.4.1",
    "stream-chat": "^6.7.2",
    "stream-chat-expo": "^4.8.0",
    "underscore": "^1.13.4",
    "expo-camera": "~12.1.2"
  },

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Reproducible demo

Create a new react native project
expo prebuild
sign up to eas
build your expo project to eas (`eas build --platform android --profile development`)
Scan the code, download the app
Run `expo install expo-camera`
import the dependency - `import {Camera} from 'expo-camera'`

**Comment by Simek** [comment]
Hello @alexander01202, usually you need to fully rebuild the project, when adding new dependencies with native files (especially when using prebuild).

Can you try running another build, with `expo-camera` already installed, and then try to use that build or development client? 

Also linking the problematic build page might help us to debug this further, if needed.

**Comment by alexander01202** [comment]
Thank you for this. It solved my issue!!!

**Comment by sankparatkar** [comment]
@alexander01202 I am also getting the same issue while using expo-camera.



I am using expo sdk - 46 and expo camera 12.5.0 in bare workflow.
I have run prebuild to ensure the native linking is taken care off and I can see below generated in my build,gradle

```
// @generated begin expo-camera-import - expo prebuild (DO NOT MODIFY) sync-f244f4f3d8bf7229102e8f992b525b8602c74770
def expoCameraMavenPath = new File(["node", "--print", "require.resolve('expo-camera/package.json')"].execute(null, rootDir).text.trim(), "../android/maven")
allprojects { repositories { maven { url(expoCameraMavenPath) } } }
// @generated end expo-camera-import 
```

AndroidManifest.xml

<uses-permission android:name="android.permission.CAMERA"/>

Still the issue persist. Can you please advise?
