### ISSUE TITLE
expo-module-scripts build command failed on windows

### ISSUE THREAD

**Issue by StarHosea** [expo/expo#19787]
### Summary

expo example `with yarn workspace`,  run commannds
- yarn install
- yarn watch-packakges

### What platform(s) does this occur on?

Web

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.14.0 - ~\AppData\Local\Volta\tools\image\node\16.14.0\node.EXE
      Yarn: 1.22.19 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
      npm: 8.3.1 - ~\AppData\Local\Volta\tools\image\node\16.14.0\npm.CMD
    Expo Workflow: managed

### Minimal reproducible example

expo example `with yarn workspace`,  run commannds
- yarn install
- yarn watch-packakges

errors will show: 
```
$ expo-module build
E:\+Githome\opensource\expo\examples\with-yarn-workspaces\node_modules\expo-module-scripts\bin\expo-module-build:3
set -eo pipefail
        ^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
```

**Comment by Simek** [comment]
Hello @StarHosea, thank you for the report! 👍 

Unfortunately this is a know issues, at this moment of time `expo-module-scripts` do not support Windows.

**Comment by camnpr** [comment]
Is there any plan support on Windows?

**Comment by lfabl** [comment]
This issue still continue...
