### ISSUE TITLE
"Experience needs permissions"

### ISSUE THREAD

**Issue by manelpb** [expo/expo#1978]
### Environment
- ios / ExpoKit

### Steps to Reproduce

- deny all camera and camera roll permissions
- go manually to settings and enable all of them
- open the app
- the "ask for permissions" popup has a different text: "Experience needs permissions. XXXX needs permissions for camera. You've already granted permission to another Expo experience. Allow XXX to use it also?"

### Expected Behavior

- it should not mention "Expo" or "Experience". I believe it should show my app name instead.

**Comment by terribleben** [comment]
What is your project's ExpoKit tag? I believe this was briefly a bug, but we fixed it, and currently ExpoKit [skips this codepath altogether](https://github.com/expo/expo/blob/28c6c7c526032c62f91a4cba37557ec1c3d7aa30/ios/Exponent/Kernel/Services/EXPermissionsManager.m#L13-L15).

**Comment by manelpb** [comment]
ExpoKit 27.0.0

**Comment by manelpb** [comment]
I believe this block is creating this message: https://github.com/expo/expo/blob/master/modules/expo-permissions/ios/EXPermissions/EXPermissions.m#L168

**Comment by terribleben** [comment]
You can find your tag inside your project's Podfile, e.g. `pod 'ExpoKit', :tag => 'ios/x.x.x'`

**Comment by manelpb** [comment]
@terribleben ios/2.5.4

**Comment by terribleben** [comment]
I think you can update to [2.5.10](https://github.com/expo/expo/releases) (without changing your SDK version) and then re-run `pod install` to get the fix. Let me know if that works.
