### ISSUE TITLE
[Android] Standalone build: Resize (adaptive) launcher icons

### ISSUE THREAD

**Issue by kr31n3r** [expo/expo#1979]
## Android (adaptive) launcher icons on standalone build should be resized

It seems that all android launcher icons referred in app.json are not resized according to specs.
In fact they are not resized at all when looking inside the apk build by expo. This seems to be okay for most android launchers but it's causing pixelation and/or unexpected effects on some devices.

Possibly related to:
https://github.com/react-community/create-react-native-app/issues/330
https://forums.expo.io/t/android-standalone-app-uses-wrong-size-app-icon/5730

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 10.5.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz => 0.55.4

App target: Android Standalone

### Steps to Reproduce

1. Configure `expo.icon` and/or `expo.andorid.adaptiveIcon.foregroundImage` in app.json
2. Build apk via `exp build:android`
3. Unpack apk and check `res/mipmap-*/*.png`

### Expected Behavior

Different launcher icon sizes in `res/mipmap-*/*.png` according to android specs

### Actual Behavior

Icon sizes in `res/mipmap-*/*.png` are all the same

### Workaround?

At least for me i get better results by using the following image sizes:

image.icon: 192x192 px
image.android.adaptiveIcon.foregroundImage: 432x432 px

Recommendations are to use at least 512x512 px or 1024x1024 px which may makes pixelation worse. (App Icons Expo: https://docs.expo.io/versions/latest/guides/app-icons)

**Comment by esamelson** [comment]
Hi-- sorry for the slow followup here. This is now implemented on our build servers, so if you run `expo build:android` the resulting apk will have correctly resized icons with (hopefully) less pixelation. We will also try to resize your icons when you run `expo eject` (formerly detach) but you may need to resize them yourself if you're running on windows or linux.
