### ISSUE TITLE
[expo-screen-orientation] Alerts don't respect locked orientation

### ISSUE THREAD

**Issue by mnassabain** [expo/expo#19792]
### Summary

I use `ScreenOrientation.lockAsync()` to lock the screen to landscape mode.
One of these screens throws an alert.
If I rotate my phone the alert box will rotate to match my physical device orientation.

In my opinion the expected behavior is: if we lock the orientation to landscape, the Alert shouldn't be able to rotate into Portrait mode

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD   
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@tilted.co/screenorientation-bug
Try it on your iOS physicial device and rotate it around

**Comment by Doctor-wu** [comment]
meet same question

**Comment by dani-mp** [comment]
I just experienced this myself, any pointers?

**Comment by zgq354** [comment]
meet same question too

**Comment by ycldz** [comment]
+1

**Comment by Borsoon** [comment]
same

**Comment by mnassabain** [comment]
I don’t think there’s a solution for this. For my app I ended up coding a custom modal that does what i want

**Comment by Darkhorse-Fraternity** [comment]
"expo": "~51.0.38",
 "react-native": "~0.74.6",

meet same question

**Comment by JustJoostNL** [comment]
Is there any workaround for this?
