### ISSUE TITLE
Google Places Autocomplete `textInputProps` returning error using Expo SDK 46

### ISSUE THREAD

**Issue by AllanBengco** [expo/expo#19796]
### Summary

After upgrading from Expo SDK 45 to 46, GooglePlacesAutocomplete component returns a `Can't find variable: e` error when using `onFocus` in `textInputProps`.

`textInputProps={{
              onFocus: () => doSomething(),
            }}`

### What platform(s) does this occur on?

Android, iOS

### Environment

`expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.1, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ^46.0.0 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
    Expo Workflow: managed`

### Minimal reproducible example

1. Create a new Expo project.
2. Install `react-native-google-places-automplete`
3. Render the `<GooglePlacesAutocomplete />` component (Google Maps API key is optional as error occurs with or without it).
4. Add a `textInputProps` parameter:

`textInputProps={{
          onFocus: () => console.log('Field is in focus.'),
        }}`

5. Press the `TextInput` field to begin entering an address. It should produce the error.

Here's a link to a [Snack](https://snack.expo.dev/@bencman/bug-in-googleplacesautocomplete-using-expo-sdk46?platform=android)

**Comment by thespacemanatee** [comment]
Not a fault of Expo's, the new maintainer seems to be breaking this library (whether out of incompetence or purpose) https://github.com/FaridSafi/react-native-google-places-autocomplete/commit/88fd9c480b9797a91742efa94195e2aa9877cd81

**Comment by AllanBengco** [comment]
> Not a fault of Expo's, the new maintainer seems to be breaking this library (whether out of incompetence or purpose) [FaridSafi/react-native-google-places-autocomplete@88fd9c4](https://github.com/FaridSafi/react-native-google-places-autocomplete/commit/88fd9c480b9797a91742efa94195e2aa9877cd81)

Thank you for getting the attention of the maintainer. It seems a patch was uploaded a few minutes ago.
