### ISSUE TITLE
AudienceSDK Out of Date

### ISSUE THREAD

**Issue by dehli** [expo/expo#198]
When creating a new app, and using the AudienceSDK, ads won't work b/c new bundles must be created with the latest `AudienceSDK`.
```
"Server Error" UserInfo={NSLocalizedDescription=Server Error, FBAdErrorDetailKey={
    code = 33000;
    message = "New bundles must use latest available Audience Network SDK.";
    type = OAuthException;
```

**Comment by terribleben** [comment]
Thanks for the issue. We'll take a look at this for the next minor update.

**Comment by terribleben** [comment]
Fixed in minor update (last week... just forgot to close this)
