### ISSUE TITLE
Android Expo.FileSystem.makeDirectoryAsync throws an error

### ISSUE THREAD

**Issue by dlehdanakf** [expo/expo#1980]
### Environment
- Mac High Sierra 10.13.2
- XDE 27
- Node 9.2.0
- NPM 4.6.1
- Android 7.0, Samsung Galaxy Note 5

I tried to take a snapshot of View component and it throws an error for creating directory of `documentDirectory` + `images/`

In the console saids

    Directory 'file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540myname%252Fappname/images/' could not be created.

I search this issue and get some code in stackoverflow, but It still not work..!
This is the code

```
const snapViewAsync =  async (view, format = 'png') => {
    const ensureDirAsync = async (dir, intermediates = true) => {
        const props =  await FileSystem.getInfoAsync(dir)
        if( props.exist && props.isDirectory)
            return props;

        await FileSystem.makeDirectoryAsync(dir, { intermediates: true })

        return await ensureDirAsync(dir, intermediates)
    }
    const timestamp = (presision = 1) => {
        return Math.round((new Date()).getTime() / presision);
    }

    const dir = await ensureDirAsync(FileSystem.documentDirectory + 'images/');
    const snapshot = `${dir.uri}${timestamp()}.${format}`;
    const temp = await Expo.takeSnapshotAsync(view, {
        format,
        quality: 1,
        result:'file'
    });

    await FileSystem.moveAsync({from: temp, to: snapshot});

    const info =  await FileSystem.getInfoAsync(snapshot, {md5:true})
    const type = `image/${format}`;

    return { ...info, type};
}
```

How could I solve it?

**Comment by nikki93** [comment]
Hmm can you make sure Expo has external storage permissions?

**Comment by dlehdanakf** [comment]
@nikki93 
I wrote the code below to check permission of external storage but neither of them works.
There is an error message below each code.

#### Code 1
```
const checkPermission = async () => {
    const { status } = await Permissions.askAsync(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);

    if (status === 'granted') return true;
    return false;
}
```
> Cannot request permission: android.permission.WRITE_EXTERNAL_STORAGE


#### Code 2
```
const checkPermission = async () => {
    const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE)

    if (granted === PermissionsAndroid.RESULTS.GRANTED) return true;
    return false;
}
```
> `granted === PermissionsAndroid.RESULTS.GRANTED` returns true | Permission granted, but still directory not created.

Is there another way to check permission of external storage?

**Comment by esamelson** [comment]
Hi @dlehdanakf - thanks for the issue and the code. I've been able to repro on my device -- not sure yet what's going on. We'll look into it.

**Comment by dlehdanakf** [comment]
@esamelson Thanks for your reply. I'll wait for your results. :)

**Comment by kelvinlawson** [comment]
I don't know if this is related but I'm getting Sentry reports from some Android customers where this error is thrown, but the directory is actually created.

If I call getInfoAsync() after it fails, then I can see the directory is there. It looks like await makeDirectoryAsync() reported failure early but then went on to create it anyway.

To debug it I made a function that creates a directory that doesn’t exist. On error it shows the directory existence before and after:

```
// Create any app folders that don't already exist
export const checkAndCreateFolder = async folder_path => {
  const folder_info = await Expo.FileSystem.getInfoAsync(folder_path);
  if (!Boolean(folder_info.exists)) {
    // Create folder
    try {
      await FileSystem.makeDirectoryAsync(folder_path, {
        intermediates: true
      });
    } catch (error) {
      // Report folder creation error, include the folder existence before and now
      const new_folder_info = await Expo.FileSystem.getInfoAsync(folder_path);
      const debug = `checkAndCreateFolder: ${
        error.message
      } old:${JSON.stringify(folder_info)} new:${JSON.stringify(
        new_folder_info
      )}`;
      console.log(debug);
      Sentry.captureException(new Error(debug));
    }
  }
};
```

The Sentry reports show that before creation getInfoAsync() returned:

```
{"isDirectory":false,"exists":false}
```

And after makeDirectoryAsync() failed and returned “could not be created” getInfoAsync() shows it actually exists:
```
{"size":4096,"modificationTime":1532552616,"uri":"file:///data/data/com.test.test/files/ExperienceData/%2540test%252Ftest/subfolder","isDirectory":true,"exists":true}
```

**Comment by normenster** [comment]
Is there any progress on this issue ? I have a similar Problem. I`m downloading images to the cacheDirectory. I can create a folder. Download seems to work. But if I ask with `getinfoAsync`  for the specific image file, I get `{"isDirectory":false,"exists":false}`. Code works fine on iOS.

**Comment by dlehdanakf** [comment]
I wish this issue is in progress. I'm waiting for any solutions.

**Comment by esamelson** [comment]
@dlehdanakf - it looks like the issue is in your code, you need to check `props.exists` rather than `props.exist`. Since you're checking `props.exist`, that's always returning false and therefore `makeDirectoryAsync` is called a second time. This is what's throwing the error. However, when I run your code, the directory is indeed successfully created. Could you confirm that if you make this change you stop seeing the error?

@normenster if you're still having this problem, could you post a new issue and follow the template there fully (including posting a repro case)?

**Comment by normenster** [comment]
@esamelson Yes, i will do.

**Comment by normenster** [comment]
it worked for me as i switched to some different code. After upgrading to SDK 29, this code stopped working. But just in production mode on Android, in development mode it works. Here's the ticket: https://github.com/expo/expo-file-system/issues/4
