### ISSUE TITLE
[SDK 47] RNCClipboard, that isn't supported in Expo Go,  AppRegistry.runApplication(). Module has not been registered as callable. 

### ISSUE THREAD

**Issue by luluhoc** [expo/expo#19810]
### Summary

After updating to SDK 47 I get this error:

In SDK 46 everything worked fine.

```
 ERROR  Error: Your JavaScript code tried to access a native module, RNCClipboard, that isn't supported in Expo Go.
To continue development with RNCClipboard, you need to create a development build of your app. See https://expo.fyi/missing-native-module for more info, 
including how to disable these errors.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

I tried searching for deprecated prop-types in my project but I don't have any when searching in node_modules...
https://github.com/facebook/react-native/issues/34688

### What platform(s) does this occur on?

Android, iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3
      expo: ^47.0.0-beta.7 => 47.0.0-beta.7
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.4 => 0.70.4
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: bare

```

### Minimal reproducible example

I'm registering the app in my index.js file

```
import { registerRootComponent } from 'expo';

import App from './src/App';

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App);

```

**Comment by mariomurrent-softwaresolutions** [comment]
Having the same error with a different module RNSpinKit #19811

**Comment by luluhoc** [comment]
> Having the same error with a different module RNSpinKit #19811

Yeah, I'm trying to resolve it for 2 days now, can't find the solution, in SDK 46 everything worked fine.

**Comment by Kudo** [comment]
hi there!

did you test your app on expo go and having `@react-native-clipboard/clipboard` in your dependencies? since expo go is limited native runtime, extending 3rd native modules is not supported. if you want to use 3rd native modules, please try to use [development builds](https://docs.expo.dev/development/introduction/).

we add this checking in sdk 47 and want to help the transition from expo go to development builds, because we found some use cases where adding 3rd native modules in the app but still using expo go. in the meantime, we are not so confident with the feature and will keep eyes on it whether there's too much false alarm.

**Comment by luluhoc** [comment]
> 

I don't have it in my dependencies it is weirdly installed in my node_modules, but it is working in expo-go with SDK 46.0.16, I don't use it anywhere in my app.

**Comment by luluhoc** [comment]
@Kudo Ok, so I found the root cause and it is working now, the clipboard dependency was required by `@twotalltotems/react-native-otp-input` when I removed the `@react-native-community/clipboard` the app rendered in expo-go. I don't understand why the app was rendering and not even showing the error in expo-go with SDK 46, and in SDK 47 the whole build for Expo-go is failing. Maybe you could add this as an warn so the app will still render but it would show the warn that the 3rd native module can't work in expo-go.

**Comment by Kudo** [comment]
that's a good finding! we will follow up the problem in sdk 47 release.

**Comment by Kudo** [comment]
hi there! we've entirely removed the checking in #19848. the issue should be fixed in `expo@latest`.
