### ISSUE TITLE
[SDK 47]: RNSpinkit does not exist

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#19811]
### Summary

I have upgraded to the beta of SDK47 and just build a development client, which actually worked fine.
But when running the app via the development client I'm getting the following error: 

`Error: Your JavaScript code tried to access a native module, RNSpinkit, that doesn't exist in this development build.`

This has worked before, what do I need to include to make this work?

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /****/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31, 32, 33
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.1 
      expo: ^47.0.0-beta.7 => 47.0.0-beta.7 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.4 => 0.70.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 2.0.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

Install react-native-spinkit in an expo project, create a development build and run the application. Compilation fails

**Comment by mariomurrent-softwaresolutions** [comment]
> hi there! this is a false alarm from [this line of react-native-spinkit](https://github.com/maxs15/react-native-spinkit/blob/8ee6ffef9f4c195e4f70924a801b7d13f5dc6569/index.js#L70). please follow this guide to disable the check as a workaround: https://expo.fyi/missing-native-module#how-do-i-disable-these-errors
> 
> we are keeping eyes on how is it going for the native modules checking.

I can't import import 'expo/disable-missing-native-module-errors'; since it is not available in my expo installation.

**Comment by mariomurrent-softwaresolutions** [comment]
My expo node_modules folder does not have the proper file, so the import does not work, because the file is not found

**Comment by Kudo** [comment]
oh good catch. that's an issue from our side. will follow up with it. thanks!

**Comment by mariomurrent-softwaresolutions** [comment]
Perfect thx :)

**Comment by mariomurrent-softwaresolutions** [comment]
@Kudo thx this solved the issue
