### ISSUE TITLE
Not able to publish classic updates (expo publish) if publishing takes over 90 seconds approximately

### ISSUE THREAD

**Issue by veris-kamaraj** [expo/expo#19826]
### Summary

Not able to publish the expo -update getting 503 status code error

### SDK Version

45

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Minimal reproducible example

<img width="1168" alt="Screenshot 2022-11-02 at 10 43 48 PM" src="https://user-images.githubusercontent.com/97278180/199637804-88b3b52d-d937-423e-a060-054e6be1d96e.png">

**Comment by n00bcyb0rg** [comment]
![image](https://user-images.githubusercontent.com/40523085/199833449-94f0ee2b-6c93-4e78-9644-e8ba10a13d68.png)
![image](https://user-images.githubusercontent.com/40523085/199833467-a5cba2cb-a867-4029-a58b-8967d0764d63.png)

Same issue happening with me, it was working fine 2 days ago, 
yesterday i tried to publish i got 503, i thought first it may be some outage issue, but it keeps happening untill now 
i tried to publish from another pc same issue.
but when i tried to create a new project and publish it, it worked fine.
do you think, it got something to do with the bundle size ?

**Comment by jtrotoux** [comment]
Same here :(

**Comment by gidiblack** [comment]
I have the same issue too

**Comment by AllanTorresBass** [comment]
I have the same issue too

**Comment by zain148** [comment]
@EvanBacon  can you please check this issue, it's urgent and we're not able to use expo-updates via expo publish.

**Comment by EvanBacon** [comment]
503 means the servers are down. Check the [status page](https://status.expo.dev/).

**Comment by zain148** [comment]
Thanks Evan for quick reply appreciated :) 

> 503 means the servers are down. Check the [status page](https://status.expo.dev/).

**Comment by EvanBacon** [comment]
I tried locally and cannot reproduce. Can anyone confirm if this is happening on a fresh project?

**Comment by zain148** [comment]
Just tried on old release-channel not working 503 error. but I didn't check on fresh project for now sorry i'm a bit busy in version updates anyone here can you give it a try @jtrotoux @n00bcyb0rg @gidiblack 

> I tried locally and cannot reproduce. Can anyone confirm if this is happening on a fresh project?

**Comment by veris-kamaraj** [comment]
@EvanBacon  i created a fresh project on expo sdk 45 i am able to publish the update , the only concern is i have changed my laptop is that cause a issue while publishing the update ?
<img width="1152" alt="Screenshot 2022-11-05 at 11 04 14 PM" src="https://user-images.githubusercontent.com/97278180/200133632-71c898be-2366-4175-b269-4fa201988466.png">

**Comment by n00bcyb0rg** [comment]
That's my existing project:
published from 2 different devices with the same error (was working fine untill wednesday)
![image](https://user-images.githubusercontent.com/40523085/200142332-76d6c489-8bd7-4888-9207-b34567b6d7e1.png)


and that's a fresh project:
always publishing without any errors
![image](https://user-images.githubusercontent.com/40523085/200142373-fd8e8243-6f24-4e9a-990a-b654c803228c.png)

**Comment by ide** [comment]
The main difference between those two projects appears to be the bundle size. The classic updates service is partially dependent on upload speed and fast internet connections to data centers in the central US may help. The new EAS Update service does not have this limitation and is able to receive uploads under a wide array of conditions.

We'll take a look at some internal server logs to see if there are easily tunable parameters that could help with this issue or if there are common patterns to the failures so we can better understand why this is happening with the classic updates service but can't promise a quick fix.

**Comment by ide** [comment]
We've looked at server logs and have found most publishes to the classic updates service have been successful. The failures appear correlated with slower network connections to the classic update API servers. There is a 90 second timeout.

**Comment by n00bcyb0rg** [comment]
@ide your are right!! i have a slow internet i counted 90 seconds and it gave me error 503 again, so i decided to use 3G and tried to publish it was successfull 
![image](https://user-images.githubusercontent.com/40523085/200663571-1013d757-0729-40ee-a481-65fb3e03df77.png)

is this a new rule ? because iv been publishing normally since always untill last week 😄

**Comment by ide** [comment]
Yes, there is a new timeout for uploads. We are looking into ways to send back a clearer HTTP status code such as 408 error (request timeout).

**Comment by ide** [comment]
To add some more detail: Feb. 12, 2024 was the [last day](https://blog.expo.dev/sunsetting-expo-publish-and-classic-updates-6cb9cd295378) the `expo publish` command was supported and it is more than deprecated.

As Evan mentioned, running `npx expo export` to generate a bundle, assets, and data that can be used to create an [update](https://docs.expo.dev/technical-specs/expo-updates-1/) manifest runs entirely locally as part of the Expo framework's dev tools and is independent from any cloud service, such as EAS.

When it comes time to publish an update, [EAS's](https://docs.expo.dev/eas-update/introduction/) update service also has much more robust uploading infrastructure with higher upload size limits (though, keep in mind $ and performance costs for both you and your end users). There is no 90 second timeout, for instance.
