### ISSUE TITLE
QR Code Camera on Android is rotated and uses a stretched aspect ratio

### ISSUE THREAD

**Issue by arsensaruhanyan2611** [expo/expo#1982]
This is not so important, but the camera in the application very much distorts the picture, making it flattened and with the wrong angle (I understand that it turns the picture 90 degrees, but why?). Just leave a link to the two images (from Expo Client(1) and my smartphone's camera(2) app) [here](https://imgur.com/a/A12f4WO)

I found this not particularly important, since the application still recognize the QR-code. But it's a little inconvenient, because it's hard to understand where to move the phone.

Phone: Samsung Galaxy A5 (2017)
OS: Android 8.0 Stock.
Expo: The last version from Google Play (Stable release? I didn't find beta channel, so...)

**Comment by arsensaruhanyan2611** [comment]
Done.

**Comment by esamelson** [comment]
Hi @arsensaruhanyan2611 - curious why you closed this. Did the problem go away?

**Comment by arsensaruhanyan2611** [comment]
Yes. Now it's fixed.

чт, 19 июл. 2018 г., 0:12 Eric Samelson <notifications@github.com>:

**Comment by Zukye** [comment]
So what did you do to fix it?
