### ISSUE TITLE
expo sdk 43 and higher ask for @unimodules/core and won't run

### ISSUE THREAD

**Issue by Mob-Ahmad** [expo/expo#19830]
### Summary

SDK Version: 43
Platforms(Android/iOS/web/all): Android/iOS

Hello guys

I need help

I’m working on 42 expo version, and when I try to upgrade to higher version I can’t run the whole application it keeps ask about @unimodules/core and @unimodules/react-native-adapter.

If I installed them by using npm install@unimodules/core & npm install @unimodules/react-native-adapter it runs but I can’t build aab, apk or ipa files I got an error in gradelew build section

### SDK Version

42

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.4
      Yarn: 1.22.11
      npm: 7.24.2
      Watchman: 2021.06.07.00
    Managers:
      CocoaPods: 1.11.3
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 25, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

eas.json file
{
  "build": {
    "beta": {
      "releaseChannel": "beta"
    },
    "production": {
      "releaseChannel": "default"
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    }
  }
}

**Comment by Kudo** [comment]
hi there! unimodules is deprecated from sdk 43. please remove all unimodules related packages in package.json. there is a migration guide for reference: https://expo.fyi/expo-modules-migration
