### ISSUE TITLE
Trying to run App after detaching ExpoKit

### ISSUE THREAD

**Issue by wpconsulate** [expo/expo#1983]
I'm trying to run my react app after I detached the ExpoKit. I need to install "urbanairship" and "fabric.io" native modules so I need to detach the ExpoKit. which I did by running the "exp detach" command and then I'm trying to run the app using command "exp start" tunnel starts fine below is the log from command line

> apple$ exp start
> [00:18:18] Using project at /Users/apple/Desktop/Projects/petmeds-standard
> (node:12714) ExperimentalWarning: The fs.promises API is experimental
> [00:18:26] Warning: Expo version in package.json does not match sdkVersion in manifest.
> [00:18:26] 
> [00:18:26] If there is an issue running your project, please run npm install in /Users/apple/Desktop/Projects/petmeds-standard and restart.
> [00:18:28] (node:12720) ExperimentalWarning: The fs.promises API is experimental
> [00:18:28] Starting Metro Bundler on port 19001.
> [00:18:28] Metro Bundler ready.
> [00:18:33] Tunnel ready.
> [00:18:33] Expo is ready.
>
> [00:18:33] Your URL is: expadbbb4cbeab14cbb95b7c8e0ef096423://192.168.1.9:19000
> [00:18:33] Logs for your project will appear below. Press Ctrl+C to exit.`

then I try to run the iPhone Simulator running **exp ios** and below the is the error from console logs
> apple$ exp ios
> [19:21:30] Opening expadbbb4cbeab14cbb95b7c8e0ef096423://localhost:19000 in iOS simulator
> [19:21:30] Error running `xcrun simctl openurl booted expadbbb4cbeab14cbb95b7c8e0ef096423://localhost:19000`: An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814): 
> The operation couldn’t be completed. (OSStatus error -10814.)
>
> [19:21:30] Error running app. Have you installed the app already using Xcode? Since you are detached you must build manually. Error: Process exited with non-zero code: 194

  
### Environment
You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.1.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/iterationgroup-752ff248-0812-486a-8b68-f5bef4cac58f.tar.gz

### Steps to Reproduce

detached the App from Expo kit using "exp detach" command and then tried to run using exp start.

### Expected Behavior

App should run without expoKit

### Actual Behavior
can't run the App on Expo

**Comment by ide** [comment]
Once you detach to ExpoKit, because you're using custom native code, the Expo-provided simulator app doesn't apply to your workflow anymore. See https://docs.expo.io/versions/latest/expokit/expokit.html -> you need to build your binary with Xcode.

**Comment by wpconsulate** [comment]
thanks ide, that helped. I tried running the app from xcode and that worked

**Comment by timnlupo** [comment]
For anyone like me also searching this issue, it is possible to un-eject your app and run again like normal. From the docs, `Delete the ios and android directories from your project. Delete the isDetached and detach keys from your project's app.json. You can now use your project like a normal Expo project (with no ExpoKit).`
Read more at https://docs.expo.io/versions/latest/expokit/advanced-expokit-topics/

**Comment by julekgwa** [comment]
Don't delete ```ios``` and ```android``` directories, just remove 

```
"detach": {
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.11.0-sdk33.0.0-4b05019b-b5d6-454b-8350-09c2187b9f91.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.11.4-sdk33.0.0-6a4f0f3e-1f1b-4c33-9155-d0237f6d7c34.tar.gz"
    }
```

from ```app.json``` and add it back when you are ready to publish your app.
