### ISSUE TITLE
[iOS 16] Rotating phone rotates camera preview

### ISSUE THREAD

**Issue by ferencbeutel4711** [expo/expo#19832]
### Summary

Under iOS 16, when rotating the phone from portrait into landscape with rotation lock _off_, the camera preview gets rotated (90° CW) - this leads to a broken preview. When rotating the phone back into portrait, the preview gets rotated further (180°CW). Rotating it again into landscape leads to a rotation of 180° CW, so it is impossible to restore a correct orientation after rotating the device once.

### What platform(s) does this occur on?

iOS

### Environment

```
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    Expo Workflow: managed
```

### Minimal reproducible example

iPhone 13 Pro
iOS 16.0.0 - iOS 16.1.0

disable rotation lock, open snack, allow camera access, rotate phone from portrait into landscape (and back)

https://snack.expo.dev/@fbeutel/calm-bananas

**Comment by ivanmatcuka** [comment]
Having the same issue. Any news on this one?

**Comment by MBrendel** [comment]
I just ran into the same issue. 
For now I have "fixed" it by adding `<Camera key={screenRotation}>…</Camera>`.
But this comes with an ugly flickering…
