### ISSUE TITLE
[SDK 47 beta 8] Some dependencies still with no changes

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#19847]
### Summary

I'm seeing in https://blog.expo.dev/expo-sdk-47-beta-is-now-available-fa760eea1908 that React Native should move to 0.70.4, and react-native-maps to 1.3.2, but after running `EXPO_BETA=1 expo-cli upgrade`, only `@babel/core` and `expo` dependencies were moved to a new version. All the other libraries still with no changes in the versions.

    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-maps": "0.31.1",

```
⠹ Installing the expo@next package...
✔ Installed expo@next
✔ Validated configuration.
✔ No additional changes necessary to app.json config.

✖ Failed to upgrade JavaScript dependencies: expo-apple-authentication@~5.0.1 expo-application@~5.0.1 expo-clipboard@~4.0.1 expo-constants@~14.0.2 expo-dev-client@~2.0.0 expo-device@~5.0.0 expo-file-system@~15.1.1 expo-firebase-analytics@~8.0.0 expo-font@~11.0.1 expo-image-manipulator@~11.0.0 expo-image-picker@~14.0.0 expo-linking@~3.2.3 expo-localization@~14.0.0 expo-location@~15.0.1 expo-media-library@~15.0.0 expo-notifications@~0.17.0 expo-splash-screen@~0.17.3 expo-store-review@~6.0.0 expo-updates@~0.15.3 react@18.1.0 react-native@0.70.4 @react-native-async-storage/async-storage@~1.17.3 @react-native-community/netinfo@9.3.5 react-native-gesture-handler@~2.8.0 react-native-maps@1.3.2 react-native-reanimated@~2.12.0 react-native-safe-area-context@4.4.1 react-native-svg@13.4.0 sentry-expo@~5.0.0 @sentry/react-native@4.2.2
✔ Updated known packages to compatible versions.
✔ Cleared packager cache.
```

### SDK Version

47 beta 8

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 27, 31
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 27.0.3, 28.0.3, 29.0.2
        System Images: android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0-beta.8 => 47.0.0-beta.8
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.6
    Expo Workflow: managed
```

### Minimal reproducible example

Just... run `EXPO_BETA=1 expo-cli upgrade`

**Comment by brentvatne** [comment]
> ✖ Failed to upgrade JavaScript dependencies: expo-apple-authentication@~5.0.1 expo-application@~5.0.1 expo-clipboard@~4.0.1 expo-constants@~14.0.2 expo-dev-client@~2.0.0 expo-device@~5.0.0 expo-file-system@~15.1.1 expo-firebase-analytics@~8.0.0 expo-font@~11.0.1 expo-image-manipulator@~11.0.0 expo-image-picker@~14.0.0 expo-linking@~3.2.3 expo-localization@~14.0.0 expo-location@~15.0.1 expo-media-library@~15.0.0 expo-notifications@~0.17.0 expo-splash-screen@~0.17.3 expo-store-review@~6.0.0 expo-updates@~0.15.3 react@18.1.0 react-native@0.70.4 @react-native-async-storage/async-storage@~1.17.3 @react-native-community/netinfo@9.3.5 react-native-gesture-handler@~2.8.0 react-native-maps@1.3.2 react-native-reanimated@~2.12.0 react-native-safe-area-context@4.4.1 react-native-svg@13.4.0 sentry-expo@~5.0.0 @sentry/react-native@4.2.2

npm install or yarn install failed in your project. try installing these package dependencies manually and you'll see the error.

**Comment by BrodaNoel** [comment]
@brentvatne 

```
error @jest/create-cache-key-function@29.2.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "16.4.0"
```

**Comment by brentvatne** [comment]
@BrodaNoel - looks like the error message is pretty self descriptive there ;) upgrade to node ^16.10.0

**Comment by BrodaNoel** [comment]
@brentvatne yeah, but that will be a breaking change, right? Node v16 >= 16.10.0 will be supported

**Comment by brentvatne** [comment]
this isn't anything that changed on our end as far as i know. this is coming from `@jest/create-cache-key-function@29`

**Comment by brentvatne** [comment]
it looks like it comes from react-native: https://github.com/facebook/react-native/blob/main/package.json#L111

not sure why this is in the package dependencies rather than dev dependencies

**Comment by BrodaNoel** [comment]
I was trying to check it with `yarn why`, but living in Southamerica implies 10 minutes of `yarn install` :/
Kind of weird that it is not present in dev, right.
Are you going to fill an issue for this? I could do it if you don't have the time

**Comment by brentvatne** [comment]
you're welcome to. i'd suggest opening a pr to move jest to dev dependencies in react-native

**Comment by BrodaNoel** [comment]
https://github.com/facebook/react-native/pull/35014 <<< 15 days ago :(

**Comment by brentvatne** [comment]
to be honest i don't quite understand the problem. updating to the latest minor/patch version of node is safe and will get you bug fixes and improvements. you should do that.

**Comment by BrodaNoel** [comment]
Yes, of course. It's just to be clear that this must be added as an important breaking change. Dropping Node < 16 is not a simple change. It will even change the `npm` version if the dev is using `nvm`. And some external libraries may get broken as well

**Comment by brentvatne** [comment]
you could add a pr to the changelog: https://github.com/facebook/react-native/blob/main/CHANGELOG.md

**Comment by brentvatne** [comment]
also, node 14 is still supported. just not an old patch version of node 14.

> error @jest/create-cache-key-function@29.2.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "16.4.0"

if you want to install node 14, use node 14.15.0 or greater

**Comment by BrodaNoel** [comment]
I was in 16.4. I just moved to 16.18.
I just reported this breaking in that already-merged-pr, and I got some answers.
