### ISSUE TITLE
Improve the README for test-suite

### ISSUE THREAD

**Issue by iffy** [expo/expo#1984]
The [test-suite repo](https://github.com/expo/test-suite) says:

> Just run this on XDE or exp and point Expo to the URL.

But cloning the repo and running `yarn test` produces this error:

```
$ yarn test
yarn run v1.3.2
$ cd Runner && yarn && cd .. && node Runner/index.js .
info No lockfile found.
[1/4] 🔍  Resolving packages...
error "/Users/matt/dev/xdl" doesn't exist.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'd like to contribute a test or two, but I don't know how to run the tests.

**Comment by iffy** [comment]
FWIW, of the 7 currently open code-related PRs:

- 4 submitters have noted that they weren't able to test because they didn't have a local dev setup
- 2 submitters didn't mention if they tested or not
- 1 submitter definitely tested

Simplifying/improving the instructions for setting up a dev environment might increase the quality of PRs that get submitted.  If I ever figure out how to get set up, I will definitely document how I did it.

**Comment by iffy** [comment]
@terribleben I apologize for not understanding if it's simple, but here's what I've done:

1. Ran `yarn` inside `test-suite/`
2. Ran `exp r` but it wasn't installed (it's not a dependency of the project).
3. Ran `yarn add --dev exp` to install it.
4. Ran `exp r` but it's asking for credentials.  I have to sign up for a service to test this code on my machine?

```
$ exp r

An Expo user account is required to proceed.

? How would you like to authenticate? (Use arrow keys)
❯ Make a new Expo account 
  Log in with an existing Expo account 
  Cancel 
```

In my own expo-based app (and I'll be honest, I'm confused by all the layers of react-native, expo, metro, haste, etc...) to start it I run: `yarn start`, `yarn android` or `yarn ios`.  Each of those just calls `react-native-scripts` and then connects to my emulator/simulator.

What's different about my expo app and this one?  Surely I can run the tests without signing up for a service?

**Comment by brentvatne** [comment]
Hi @iffy!

I agree it's silly that an account is currently needed to run an app with `exp`. We're very close to replacing both `create-react-native-app` and `exp` with a single tool called `expo-cli` and it will remove the requirement to have an account that `exp` enforces. I believe this will be ready next week or so.

Until then, you'll have to make an account with Expo. It's free, hardly asks for any information, and takes only a few seconds to do so.

**Comment by terribleben** [comment]
Hey @iffy, you're right that it's silly that the test-suite app is built to require signing up with Expo.

I think this situation happened not due to any ill will from us, but just because it's mostly Expo teammates who work on maintaining both create-react-native-app and Expo, and this was just the simplest path for us to test our own work. As you've noticed, it's not the friendliest way to encourage high quality PRs.

We're working on removing the requirement to authenticate to use the `exp` CLI, but I'm not sure if we've shipped it yet. Either way it's fairly close to shipping.

Thanks for your PR to the test-suite repo!

**Comment by iffy** [comment]
@terribleben oh, I didn't mean to imply that there was ill will.  I'm a programmer, too.  I know how it goes :)  I apologize if I came across as impolite.

Well, I got the app to open in my iOS simulator.  Here's the diff that made it work (I suspect I don't actually need to install `exp` though):

```diff
diff --git a/package.json b/package.json
index c2c3813..6633dbb 100644
--- a/package.json
+++ b/package.json
@@ -12,7 +12,12 @@
     "expo": "*",
     "immutable": "^3.8.1",
     "jasmine-core": "^2.4.1",
-    "react": "16.0.0-alpha.12",
-    "react-native": "expo/react-native#sdk-18"
+    "react-native": "0.55"
+  },
+  "devDependencies": {
+    "async-retry": "^1.2.1",
+    "exp": "^55.0.5",
+    "react-native-scripts": "^1.14.0",
+    "react-test-renderer": "^16.4.1"
   }
 }
```

- To run all the tests, I do `react-native-scripts ios`.

- To run just the SQLite tests, in theory I do the following, but it also runs all the tests:

1. Run `react-native-scripts start`
2. On my iOS simulator, I press ⌘D
3. Click "Go to Expo Home"
4. Click "Explore"
5. Type in my `exp` URL (which is displayed in my terminal) with `/+SQLite.*` appended.  For example: `exp://MYIP:19000/+SQLite.*`  (This is according to the README)

---

From the below code in `index.js`, however, it looks like I should really use this URL:

`exp://MYIP:19000/--/{"includeModules":["SQLite"]}`

```javascript
    if (uri && uri.indexOf('--/') > -1) {
      const deepLink = uri.substring(uri.indexOf('--/') + 3);
      const filterJSON = JSON.parse(deepLink);
      if (filterJSON.includeModules) {
        console.log('Only testing these modules: ' + JSON.stringify(filterJSON.includeModules));
        const includeModulesRegexes = filterJSON.includeModules.map(m => new RegExp(m));
        modules = modules.filter(m => {
          for (let i = 0; i < includeModulesRegexes.length; i++) {
            if (includeModulesRegexes[i].test(m.name)) {
              return true;
            }
          }
```

But that throws:

```
SyntaxError: JSON Parse error: Unrecognized token '%']
* index.js:105:36 in _runTests$
```

I added a `console.log` statement, and the `deepLink` it is getting is: `%257B%E2%80%9DincludeModules%E2%80%9D:%5B%E2%80%9DSQLite%E2%80%9D,%E2%80%9Dfoo%E2%80%9D%5D%257D`

So, if I double decode it (I sense a security issue)

```javascript
    console.log('uri', uri);
    if (uri && uri.indexOf('--/') > -1) {
      let deepLink = uri.substring(uri.indexOf('--/') + 3);
      console.log('before', deepLink);
      deepLink = decodeURIComponent(decodeURIComponent(deepLink));
      console.log('after', deepLink);
      const filterJSON = JSON.parse(deepLink);
```

iOS uses fancy quotes, so it still fails to parse the JSON.

<img width="815" alt="screen shot 2018-07-17 at 11 44 59 am" src="https://user-images.githubusercontent.com/161727/42835790-e575012e-89b6-11e8-8c62-41b774aa3edc.png">

But I can finally get it to work on iOS if I type in the URL-encoded version by hand: `%7B%22includeModules%22%3A%5B%22SQLite%22%5D%7D`

![finallyworks](https://user-images.githubusercontent.com/161727/42836084-6b577a38-89b7-11e8-9e7c-558d72c1b542.gif)

---

I realize my method isn't probably the one you want to use, but this is a complete log of my steps to get the tests to run.  Thank you for working on expo!

**Comment by ide** [comment]
A lot has changed since this issue was opened including moving test-suite into this repo (https://github.com/expo/expo/tree/master/apps/test-suite), adding it to CI in Android Device Farm, and adding a new UI. I'm going to close this out as I suspect that the root causes have been addressed or have changed. Feel free to open a new issue if this problem is still relevant (new issues are more helpful than reviving zombies).
