### ISSUE TITLE
CommandError: Unexpected response when fetching version info from Expo servers: Service Unavailable.

### ISSUE THREAD

**Issue by ctrlShiftBryan** [expo/expo#19857]
### Summary

I cannot start expo.

```bash
❯ npx expo start -c
Starting project at /Users/ctrlshiftba/code/gm2
CommandError: Unexpected response when fetching version info from Expo servers: Service Unavailable.
```

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

47.0.0-beta.7

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.16.0/.npm/bin/yarn
      npm: 8.11.0 - ~/.asdf/installs/nodejs/16.16.0/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      expo: ^47.0.0-beta.7 => 47.0.0-beta.7 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.4 => 0.70.4 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.6.0
    Expo Workflow: managed

### Minimal reproducible example

I tried multiple local expo projects and even created a basic new project with `npx create-react-native-app` and got this same error. 

Others on discord were having the same issue.

It magically disappeared and I'm just opening this issue to make developers aware and hope there is a solution for expo servers being down by the expo team.

**Comment by ctrlShiftBryan** [comment]
Ok I found an easy way to always reproduce. Disable your network connection and try and start expo. 

Are an active internet connection and connections to expo servers required for developing expo locally?

**Comment by animaonline** [comment]
I suppose this is related to some kind of server issues, similar problem here: https://github.com/expo/expo/issues/19855

@brentvatne are you aware of this?

**Comment by zagoorland** [comment]
I also get this error: `Unexpected response when updating the development session on Expo servers: Insufficient Storage.`

**Comment by MarianBe** [comment]
Same issues here, unable to develop currently

**Comment by dmitryusikriseapps** [comment]
+1

**Comment by stvb95** [comment]
Same issue here. While trying to run on Expo Go and when retrieving the Push token on the production app.

**Comment by animaonline** [comment]
Expo needs to acknowledge this asap, it's been going on for the past 3 hours, and according to the server status page https://status.expo.dev everything is ok.

**Comment by stvb95** [comment]
The status page has just been updated to say they are investigating the issue, good news

**Comment by ctrlShiftBryan** [comment]
@brentvatne thanks that solves the issue for me.
