### ISSUE TITLE
Community maintainer for expo/exponent-server-sdk-python

### ISSUE THREAD

**Issue by wli** [expo/expo#1985]
@ide I can help maintain https://github.com/expo/exponent-server-sdk-python/

Reference: https://github.com/expo/exponent-server-sdk-python/pull/11#issuecomment-403236826

**Comment by ide** [comment]
@wli Awesome, thank you. I'll send you a note with some details and also the credentials for PyPI to get you set up.

**Comment by ide** [comment]
I sent you an email and added you to the GitHub repo. Let me know if either of those didn't go through to you.
