### ISSUE TITLE
[docs] AuthSession proxy documentation is unclear/misleading

### ISSUE THREAD

**Issue by bradjones1** [expo/expo#19850]
### Summary

I am implementing Instagram Basic Display in my app, and Facebook stubbornly does not accept anything but `https` schemes for redirect URLs.

So, I've implemented a proxy in my backend app that does basic redirection back to my Expo app akin to the instructions in the [current docs](https://github.com/expo/expo/blob/ab828e042bcf50ac90bcd1806238051c76381394/docs/pages/versions/unversioned/sdk/auth-session.mdx#proxy-service).

However, the code snippet following the server example code is unclear and doesn't actually work for a custom proxy. E.g.:

https://github.com/expo/expo/blob/ab828e042bcf50ac90bcd1806238051c76381394/docs/pages/versions/unversioned/sdk/auth-session.mdx?plain=1#L225-L235

If you implement that code more or less as written, particularly the call to `startAsync()`, you're likely to get:

```
Error: Cannot use the AuthSession proxy because the project full name is not defined. Prefer AuthRequest (with the useProxy option set to false) in combination with an Expo Development Client build of your application. To continue using the AuthSession proxy, specify the project full name (@owner/slug) using the projectNameForProxy option.
```

The culprit code is

https://github.com/expo/expo/blob/ab828e042bcf50ac90bcd1806238051c76381394/packages/expo-auth-session/src/AuthSession.ts#L65-L67

where you can see that the `authUrl` is processed, and if it does not match the `returnUrl` you're assumed to be using the proxy.

It's possible that I am doing this wrong, but if that's the case at the least the docs could use some cleanup :-)

But I don't think I am? I ended up copying over the logic for startAsync() and using the intended values directly.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/auth-session/#usage-in-the-bare-react-native-app

**Comment by bradjones1** [comment]
Not stale

**Comment by amandeepmittal** [comment]
Hey @bradjones1, We've removed the using `useProxy` and stop recommending it for this use case. [More details in this blog post](https://blog.expo.dev/security-advisory-for-developers-using-authsessions-useproxy-options-and-auth-expo-io-e470fe9346df?source=collection_home---6------3-----------------------).

Also, we recommend using native library such as `react-native-fbsdk-next` to implement Facebook login and working on up to date guide here: https://github.com/expo/expo/pull/22838/files

Apologies for any inconvenience.
