### ISSUE TITLE
Unable to get a push token

### ISSUE THREAD

**Issue by animaonline** [expo/expo#19855]
### Summary

Started getting the following error all of sudden:

[Error: Error encountered while fetching Expo token, expected an OK response, received: 503 (body: "no healthy upstream").

Everything worked fine yesterday.

Our implementation has not changed.

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 29, 32
        Build Tools: 29.0.2, 30.0.3, 32.0.0, 32.1.0
        System Images: android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: Dolphin 2021.3.1 Dolphin 2021.3.1
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.22 => 0.3.22 
      expo: ^46.0.10 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 1.2.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

`const token = (await Notifications.getExpoPushTokenAsync()).data;`

**Comment by roneconesimplicity** [comment]
We're having the same issue. 

3 types of errors are returned: 

1. no healthy upstream
2. upstream connect error or disconnect/reset before headers. reset reason: connection termination
3. exceeded request buffer limit while retrying upstream

**Comment by Prashwarmishra** [comment]
API with the following endpoint seems affected:
`curl --location --request POST 'https://exp.host/--/api/v2/push/getExpoPushToken' \
--header 'content-type: application/json' \
--data-raw '{
    "type": "fcm",
    "deviceId": "x",
    "development": false,
    "appId": "x",
    "deviceToken": "xxxx",
    "experienceId": "@xxx"
}'`

**Comment by animaonline** [comment]
> We're having the same issue.
> 
> 3 types of errors are returned:
> 
> 1. no healthy upstream
> 2. upstream connect error or disconnect/reset before headers. reset reason: connection termination
> 3. exceeded request buffer limit while retrying upstream

Has this started just recently?

**Comment by TheoChapelot** [comment]
Also having the same issue since at least today 7 am UTC.

**Comment by japivonka** [comment]
According to https://status.expo.dev/ everything is still ok, which obviously is not...

**Comment by stvb95** [comment]
I think they may have resolved this issue. I am now able to retrieve a push token reliably.

**Comment by animaonline** [comment]
Yeah, same here.

**Comment by Simek** [comment]
As mentioned on the status page, the outage leading to 503 in different Expo services has been fixed.

Going to close this report now, feel free to create new issue when similar issues occurs in the future.

**Comment by luluhoc** [comment]
@Simek I'm getting the 503 in my app from today,

```
Error: Error encountered while fetching Expo token, expected an OK response, received: 503 (body: "upstream connect error or disconnect/reset before headers. reset reason: connection termination").
```

**Comment by jamiefrew** [comment]
> @Simek I'm getting the 503 in my app from today,
> 
> ```
> Error: Error encountered while fetching Expo token, expected an OK response, received: 503 (body: "upstream connect error or disconnect/reset before headers. reset reason: connection termination").
> ```

I'm getting this error today too

**Comment by markymc** [comment]
Just a note that I saw this in my Sentry logs a couple of times this week too. Doesn't seem to be a big problem though.
