### ISSUE TITLE
Expo 46: Alerts disregard ScreenOrientation.lockAsync()

### ISSUE THREAD

**Issue by mnassabain** [expo/expo#19868]
### Summary

This only happens in expo 46. I've downgraded to expo 45 temporarily so alerts would work as intended in my app.

The problem is that even after locking the screen orientation to landscape mode using `expo-screen-orientation`, alerts will always be oriented following the system settings (which are configured on view photo)
![image](https://user-images.githubusercontent.com/34754819/200066277-43dc1c22-5e5f-4fc5-a791-b7e90edd3072.png)

As per the `expo-screen-orientation` documentation, `ScreenOrientation.lockAsync()` overrides system settings. So the expected behavior should be that if we lock to landscape mode, that the alert stays in that mode.

This issue is not a duplicate of my other issue (#19792). That issue exists even in expo 45. But in my opinion, this one is much worse. A lot of people lock their iPhone to portrait mode, and so to them my alert would always be sideways.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD  
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ^46.0.0 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

How to reproduce the problem:
```
in app.json:
"orientation": "portrait"
```

On iPhone lock screen rotation to portrait mode:
![image](https://user-images.githubusercontent.com/34754819/200065860-efc2a467-d03b-4936-8dad-2f27e91a28f8.png)

In your code, lock the orientation to landscape mode using `ScreenOrientation.lockAsync()`. This should work (overriding config in app.json). However, when you display an alert, it will always display in portrait mode.

**Comment by Zcehtro** [comment]
I'm on Expo SDK 49 and I'm still seeing this issue... No clue how to fix it yet.

This is notably an undesirable behaviour.

Should it not warrant priority from the Expo team?

**Comment by dani-mp** [comment]
I just experienced this myself, any pointers?
