### ISSUE TITLE
[SDK 47] AppState.removeEventListener not exposed

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#19863]
### Summary

AppState.removeEventListener('change', this.handleAppStateChange);

There is not removeEventListener event anymore. Has this been removed? Or is there any alternative?

### What platform(s) does this occur on?

Not Applicable

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/*****/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31, 32, 33
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.1 
      expo: ^47.0.0-beta.8 => 47.0.0-beta.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.4 => 0.70.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 2.0.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

Use the AppState and try to use the removeEventListener function

**Comment by awinograd** [comment]
removeEventListener is deprecated. You can do

```
    const listener = AppState.addEventListener('change', callback);
    listener.remove();
```

**Comment by brentvatne** [comment]
see the changelog for react-native here: https://github.com/facebook/react-native/blob/main/CHANGELOG.md

**Comment by mariomurrent-softwaresolutions** [comment]
> see the changelog for react-native here: https://github.com/facebook/react-native/blob/main/CHANGELOG.md

Uh sorry, must have missed that ...
