### ISSUE TITLE
react-native-gesture-handler + react-native-reanimated breaks new Expo Go client(2.26.2)

### ISSUE THREAD

**Issue by brunohkbx** [expo/expo#19862]
### Summary

My app started to crash after updating Expo Go to the new version `2.26.2` recently launched for SDK 47. In an attempt to narrow down what was causing the issue, I noticed that one of these libraries is likely causing the problem.

Happens in SDK 45 and SDK 46.

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ^46.0.0 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.3.2
    Expo Workflow: managed

### Minimal reproducible example

I created a new project with the 2 dependencies:

"react-native-gesture-handler": "~2.5.0",
"react-native-reanimated": "~2.9.1"

https://github.com/brunohkbx/expo-sdk-47-issue-repro

**Comment by brentvatne** [comment]
Unfortunately the Google Play Store doesn't support rollbacks, but I've started to re-deploy the previous Expo Go version to the store. Until then, you can use Expo CLI to install the previous Expo Go version to your device

**Comment by hufftheweevil** [comment]
Everything looks good in the latest version (2.26.3). Thank you for the quick resolution!
