### ISSUE TITLE
expo-dev-client, useFrameworks static and jsEngine hermes crashes on iOS launch in SDK 46

### ISSUE THREAD

**Issue by tyrauber** [expo/expo#19865]
### Summary

A blank expo-dev-client with the following settings successfully builds for iOS but crashes on launch.

Without hermes, useFrameworks static works on iOS.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

    "expo": "~46.0.16",
    "expo-build-properties": "~0.3.0",
    "expo-dev-client": "~1.3.1",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-safe-area-context": "4.3.1",
    "react-native-web": "~0.18.7"

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2022.10.31.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/tyrauber/.rvm/gems/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 0.58.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Reproducible demo

```
# App.tsx
import React from 'react';
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider } from 'react-native-safe-area-context'

export default function App() {
  return (
    <SafeAreaProvider>
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Open up App.tsx to start working on your app!</Text>
      </View>
    </SafeAreaProvider>
  );
}

# app.json
    },
    "jsEngine": "hermes",
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ]
```

### Stacktrace (if a crash is involved)

```
*** Terminating app due to uncaught exception 'RCTFatalException: Could not get BatchedBridge, make sure your bundle is packaged correctly', reason: 'Could not get BatchedBridge, make sure your bundle is packaged correctly'
*** First throw call stack:
(0x1843311ec 0x19d066744 0x1003fcbc4 0x100414938 0x100412e74 0x100427efc 0x100427c90 0x18430a504 0x18430b460 0x1842a2f88 0x1842b6b0c 0x1004106f4 0x185af93dc 0x1f54f99ac 0x1f54f8e68)
```

**Comment by brentvatne** [comment]
https://github.com/facebook/react-native/issues/34344

**Comment by brentvatne** [comment]
ah - I see you are aware of this: https://forums.expo.dev/t/expo-46-eas-react-native-firebase-and-hermes/67396/5

we don't track upstream issues here in order to keep things more actionable for us
