### ISSUE TITLE
[expo-device] Device.isDevice is true on iOS simulator

### ISSUE THREAD

**Issue by xydian** [expo/expo#19869]
### Summary

Hi. When I try to check whether the app is running on a real device expo-device provides incorrect information. 

`Device.isDevice` is true on an ios simulator

maybe related to https://github.com/expo/expo/issues/16165

### What platform(s) does this occur on?

iOS

### Environment

```
 npx expo-env-info

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.10.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.6
    Expo Workflow: managed

```

### Minimal reproducible example

```
import * as Device from 'expo-device'
console.log(Device.isDevice)       // ---> logs true on iOS simulator
```

**Comment by kbrandwijk** [comment]
Do you know if this is a regression, as in: has this worked on older SDK versions?

**Comment by xydian** [comment]
I didn't use this feature on an ios simulator before so unfortunately I don't know

**Comment by xydian** [comment]
Just looked in the code and it seems that it defaults to true: 

`export const isDevice: boolean = ExpoDevice ? ExpoDevice.isDevice : true;` --> https://github.com/expo/expo/blob/main/packages/expo-device/src/Device.ts

also the macro `TARGET_IPHONE_SIMULATOR ` that is been used in expo-device (see: https://github.com/expo/expo/blob/main/packages/expo-device/ios/EXDevice/EXDevice.m) has been deprecated since at least 7 years (see: https://developer.apple.com/forums/thread/13254) so it may just not work anymore and should be replaced by `TARGET_OS_SIMULATOR `

**Comment by xydian** [comment]
Ok just realised what was happening. I had to do a rebuild of my expo dev client after installing expo-device. Now it is working (before it was most certainly true because it defaults to true). I think this information should be included in the documentation though. Or is it just expected that i rebuild my dev client after installing any package from expo? 

Sorry for the inconvenience :)

**Comment by Simek** [comment]
@xydian Happy to see that you have resolved the issue. :+1: 

Can we close this report?

**Comment by xydian** [comment]
@Simek yes this can be closed

**Comment by nathanfallet** [comment]
Getting:
```
Cannot find 'TARGET_OS_SIMULATOR' in scope
```

Using:
Expo 52
expo-device 7.0.2
React Native 0.77.0

Any idea where this could come from?
It was building until today (we got a lot of issues with Xcode auto updating to 16.3, so we think this is linked)

**Comment by shashkovdanil** [comment]
@nathanfallet have the same

**Comment by nathanfallet** [comment]
Looks like a fix is coming for this: https://github.com/expo/expo/commit/a6c1fc09e33d780b6c80a7be0ba6d710f4e2b8db

**Comment by PedroContipelli** [comment]
What expo version number is it fixed in?
