### ISSUE TITLE
expo-updates v0.14.6 bare workflow build issue

### ISSUE THREAD

**Issue by cameronnapoli** [expo/expo#19867]
### Summary

My current app is having build failures on Android with `expo-updates`, so I created a new expo project that had the same issue:

After running `expo run:android`, I'm seeing **Task :expo-updates:compileDebugKotlin FAILED**

<img width="1283" alt="Screen Shot 2022-11-04 at 12 54 37 PM" src="https://user-images.githubusercontent.com/4724150/200063969-2168b1f8-3276-41db-bd2b-ab0ee35f5465.png">

### What platform(s) does this occur on?

Android

### SDK Version

6.0.8

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

`expo init`
`expo eject`
`yarn add expo-updates@0.14.6`
`expo run:android`

**Comment by LFMAKER** [comment]
https://github.com/facebook/react-native/issues/35204

**Comment by cameronnapoli** [comment]
@LFMAKER Thanks for the suggestion! Unfortunately that didn't work. It looks like that is an active discussion, so I'll just wait to see how it resolves.

**Comment by LucasAnSilvs** [comment]
I'm getting a error like that, but with splash-screen:

` Task :expo-splash-screen:compileDebugKotlin FAILED`

**Comment by cameronnapoli** [comment]
Someone just posted this in the thread LFMAKER posted:

> You might try this in your android/build.gradle (top level) file, in the allprojects block, it has reported success even with reanimated etc mixed in, also has reported success with expo now (fix in progress there, they are listening closely)

```
allprojects {
    configurations.all {
        resolutionStrategy {
            force 'com.facebook.react:react-native:<your version>'
        }
    }
    repositories {
    // ...
    }
}
```

**Comment by leonardorib** [comment]
> Someone just posted this in the thread LFMAKER posted:
> 
> > You might try this in your android/build.gradle (top level) file, in the allprojects block, it has reported success even with reanimated etc mixed in, also has reported success with expo now (fix in progress there, they are listening closely)
> 
> ```
> allprojects {
>     configurations.all {
>         resolutionStrategy {
>             force 'com.facebook.react:react-native:<your version>'
>         }
>     }
>     repositories {
>     // ...
>     }
> }
> ```

I can confirm this works. I was facing the exact same problem
