### ISSUE TITLE
Can't open the Hermes Inspector on Linux

### ISSUE THREAD

**Issue by crloz** [expo/expo#19877]
### Summary

After creating a new project with `EXPO_BETA=1 yarn create expo-app -t expo-template-blank-typescript` and running in the Android Emulator, when I try to launch the debugger, the dev-server crashes:

```
RuntimeError: abort(Error: Unable to find a browser on the host to open the inspector. Supported browsers: Google Chrome, Microsoft Edge). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/.../node_modules/metro-hermes-compiler/src/emhermesc.js:402:15)
    at process.emit (node:events:527:28)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

___
It seems to be related to this code
https://github.com/expo/expo/blob/5f7198dd6cb2f2a4df0bbefc5eb3e310b90b31af/packages/%40expo/dev-server/src/JsInspector.ts#L101

See also https://github.com/sindresorhus/open/blob/05ba9e150cc1a2629e518a9cc19b586c6ca3f269/index.js#L288

### What platform(s) does this occur on?

Android

### SDK Version

47

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.0 Arch Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /tmp/xfs-ab0e90c9/node
      Yarn: 3.2.4 - /tmp/xfs-ab0e90c9/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 29.0.3, 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ~47.0.1 => 47.0.1 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.4 => 0.70.4 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.5.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

- create a new app: `EXPO_BETA=1 yarn create expo-app -t expo-template-blank-typescript`
- run it in the android emulator: `yarn android`
- Press m to open dev menu and select "Open JS Debugger

**Comment by Simek** [comment]
Thank you for the report! 👍  The issue should be fixed by #19872.
