### ISSUE TITLE
EAS build crashing in Release (production) After Splash Screen

### ISSUE THREAD

**Issue by TestCK** [expo/expo#19871]
### Summary

When I build a production build of my app (android) its crashing after the splash screen. Its working fine in dev-client. The app was working fine till yesterday, all I did today was change few strings in our locales, so it couldnt be crashing because of that.

I found in https://status.expo.dev/, there are multiple outages for android, not sure if these are related.

I am using EAS build in managed work flow.

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ^46.0.0 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
    Expo Workflow: managed

### Minimal reproducible example

-NA-

**Comment by TestCK** [comment]
Update - building locally works fine, may be an issue with eas hosted build

**Comment by baochungit** [comment]
Check if you are in the same issue with this. https://github.com/expo/expo/issues/19693

**Comment by TestCK** [comment]
> Do you use expo-updates in your app? Check if you are in the same issue with this. #19693

Seems like it. What's the fix for that ?,  For that thread I am unable to deduce which was the fix or if the fix is still being  worked on

**Comment by baochungit** [comment]
The fix seems already merged to SDK 47 so just upgrade if you are confident. If not you could use patch-package plugin to apply the patch yourself. For now it seems there will not be an official fix for SDK 46

**Comment by baochungit** [comment]
And here is the fix https://github.com/expo/expo/pull/19809

(In case you don't find out in the thread)

**Comment by TestCK** [comment]
> And here is the fix #19809
> 
> (In case you don't find out in the thread)

Thank you, I will patch manually. Will wait a bit before upgrading to SDK 47
