### ISSUE TITLE
[docs] EXPO 47, 46 & 45 Firebase Analytics - Change `screen_view` example.

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#19880]
### Summary

I have been getting a buggy behaviour since Expo 45, when I built my app using EAS cli. The `expo-firebase-analytics` `screen_view` event, used as the [current documentation](https://docs.expo.dev/versions/latest/sdk/firebase-analytics/#react-navigation) recommends, was not logged in the *'Views by Page title and screen class'* section of the *Firebase Analytics Dashboard*.

I also tried the following, mentioned [here](https://github.com/expo/expo/issues/18348) in a more detailed way:

```
analytics.logEvent("screen_view", {
  firebase_screen_class: "EditProfile",
  firebase_screen: "EditProfile",
});
```

But only worked for me when using the `Expo Go` environment **(managed workflow)**.

Please, check this [pull request](https://github.com/expo/expo/pull/17742)

```
const paramKey =
    Constants.appOwnership !== "expo"
      ? "screen_name"
      : "firebase_screen";

await Analytics.logEvent('screen_view', {
  [paramKey]: currentScreen,
});
```

fix the problem.

- Official Firebase Analytics docs for Web, iOS, and Android:

1. https://firebase.google.com/docs/analytics/screenviews#web-version-9
2. https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Constants#declaration_94
3. https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Param#public-static-final-string-screen_name

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/firebase-analytics/

**Comment by brentvatne** [comment]
expo-firebase-* will not be receiving any new patches, it is deprecated in SDK 47. I recommend migrating to react-native-firebase: https://expo.fyi/firebase-migration-guide
