### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jose4gg** [expo/expo#199]
Is there a possibility to use Expo GLView without having any other Expo code in my project? Honestly, I have a large project I don't want to migrate it to Expo to use ExpoKit later, Is there an easy route to get that?

**Comment by ccheever** [comment]
Everything is open source so you could try to pull the graphics layer out but its pretty tightly coupled to the Expo Client in a few places, and I think it would probably be easier to just use ExpoKit -- which is in general pretty easy.
