### ISSUE TITLE
The application is upside down after loading on iPad in the landscape mode. (Reopen issue  #8866)

### ISSUE THREAD

**Issue by sergeu90** [expo/expo#19903]
### Summary

It is issue was closed but not fixed.

https://github.com/expo/expo/issues/8866

### What platform(s) does this occur on?

iOS

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.17 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 32, 33
        Build Tools: 32.0.0, 32.1.0, 33.0.0, 33.0.0
        System Images: android-25 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google APIs ATD ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.17.2 => 0.17.2 
      expo: 46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: 0.18.9 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Minimal reproducible example

Steps how in https://github.com/expo/expo/issues/8866.

Or you can `ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE)` call when start app and you get wrong orientation for the ipad. It issue appears when home button right. when the button is on the left all good.

 `ScreenOrientation.getOrientationAsync().then((res) => console.log(res)); ` 

Always return 3.  But need to 4 if home button in the right.

**Comment by roman-veryovkin** [comment]
Can confirm the issue, the same story for me as well. Would be nice to fix it or find some workaround. Thanks!

**Comment by sergeu90** [comment]
@Simek  Could you please when this issue will be fixed and maybe have workaround?

**Comment by brentvatne** [comment]
@Simek - can you investigate and try to repro?
