### ISSUE TITLE
> Task :expo-updates:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by dominicg666** [expo/expo#19915]
### Summary

> Task :expo-updates:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-updates:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 56s
541 actionable tasks: 17 executed, 524 up-to-date
/home/dominic/projects/sandbox/android/gradlew exited with non-zero code: 1

### What platform(s) does this occur on?

Android, iOS

### Environment

"react-native": "0.68.2"
"expo": "~45.0.0",
"expo-updates": "~0.13.1",

### Minimal reproducible example

Hi i have found this error when a run android

**Comment by dotBeFoRE** [comment]
Got this also.

**Comment by Jas1222** [comment]
Had the same issue, I updated my react-native version here as per here https://github.com/facebook/react-native/issues/35210 and its working now

**Comment by bebe84** [comment]
Can confirm this, updating "react-native": "0.69.7" in packages.json resolved the issue but it is only for SDK 46, if you are using SDK 45 you must use "0.68.5". Expo doctor is also complaining about it, Expo please upgrade react-native packages in any supported version of the SDK, otherwise users will not be able to compile Android projects.

**Comment by brentvatne** [comment]
@bebe84 - to be clear, you have a bare project, right?

we fixed this for all managed projects (using prebuild on eas build or locally) on friday: https://expo.fyi/android-071-rc-build-failure

**Comment by bebe84** [comment]
No, I am using your Dev Client so I am managed. It was not working for me until i manually changed the react-native version in my project. Maybe you should update Expo doctor as well because it shows that RN 0.69.7 is not supported version in SDK 46. Am I missing something here?

**Comment by matmuenzel** [comment]
can confirm, updating react-native as @bebe84 stated works. we are on bare project and not managed.

**Comment by Kudo** [comment]
hi there! react-native upstream also fixed the issue by removing the 0.71 aar from maven central. even though the app doesn't update to newer react-native patch versions or re-run prebuild from an expo managed app, the error should not happen anymore. i'm closing this issue. if there're still related errors, please let us know. thanks!

**Comment by shyammanek** [comment]
Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-modules-core:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

**Comment by jkrmarmol** [comment]
i just solved it by deleting node_mobules and installing it again

**Comment by Hiba-Bazerbashi** [comment]
Task :expo:compileDebugKotlin FAILED
FAILURE: Build failed with an exception.

> * What went wrong:
> Execution failed for task ':expo:compileDebugKotlin'.
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
>    > Compilation error. See log for more details
> 

**Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.**

i'm using RN cli and I'm up to date with expo and RN and all plugins , please how to narrow this issue ????
