### ISSUE TITLE
[docs] Clarify that experienceId is required in getExpoPushTokenAsync

### ISSUE THREAD

**Issue by aureosouza** [expo/expo#19929]
### Summary

We noticed an interesting behaviour when using expo push notifications on bare project. So when publishing to TestFlight using Xcode, build works correctly and `Notifications.getExpoPushTokenAsync` returns correctly the token and push notifications are correctly sent using [test tool](https://expo.dev/notifications).

The issue is when we use CI/CD tools such as AppCenter / Fastlane to send build to TestFlight, using event logs we noticed `Notifications.getExpoPushTokenAsync` is never resolved.

We understand that this may be an issue with the config/certificates from the CI/CD pipeline and could be outside the scope of expo project. But it seems to be a wrong behaviour from expo side the fact that this promise should at least return an error with more information, so we can continue with investigation.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.10.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: 47.0.2 => 47.0.2 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.4 => 0.70.4 
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/aureosouza/snack-push-notifications

**Comment by aureosouza** [comment]
We found the issue, after adding these arguments from `getExpoPushTokenAsync` it works correctly for both Android and iOS:

```
await Notifications.getExpoPushTokenAsync({
        experienceId: '@username/projectSlug',
        development: false,
        applicationId: 'com.myapp',
      }
```

For the bare project these are obligatory. We noticed that when building locally the `experienceId` is returned correctly from 'expo-constants', but if it's built using CI/CD it returns "anonymous" as the `username`, most probably because of the global expo package installed on local machine.

Possible suggestion to avoid confusion could be to add to the main examples in doc these arguments, as [doc](https://docs.expo.dev/versions/latest/sdk/notifications/#arguments) mentions:

> Although this is optional, we recommend explicitly passing it in

**Comment by brentvatne** [comment]
@aureosouza - the experience id is dependent on the currently authenticated user, so if you authenticate with `npx expo login` before building that will also work.

cc @amandeepmittal -  we should say that adding `experienceId` here is mandatory
