### ISSUE TITLE
SDK 47 Hermes debugger pauses execution at debugger statements even when debugger is not open

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#19938]
### Summary

SDK 47 Hermes debugger pauses execution at debugger statements even when debugger is not open. The behavior is confusing and unexpected - but easily worked around by opening the debugger and continuing code execution.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.6

### Minimal reproducible example

Put `debugger`; at the top of the entry file, before any React component is loaded.

**Comment by Kudo** [comment]
hi there! i could repro this in a pure react-native 0.70 app. this is more like an upstream issue or even more, looks like a design from my tracing code at [#1](https://github.com/facebook/react-native/blob/394486eec584a37920dad447a6c1d0ae24d225fc/ReactCommon/hermes/inspector/InspectorState.cpp#L41-L44) and [#2](https://github.com/facebook/react-native/blob/394486eec584a37920dad447a6c1d0ae24d225fc/ReactCommon/hermes/inspector/InspectorState.h#L252-L256).

please create an issue or feature request to [upstream](https://github.com/facebook/react-native/issues). thanks!

**Comment by Slapbox** [comment]
Thanks @Kudo!

Created https://github.com/facebook/react-native/issues/35295
