### ISSUE TITLE
RNGenius-Scan not working with SDK 47

### ISSUE THREAD

**Issue by zewas-digital** [expo/expo#19943]
### Summary

I was using the RNGenius-Scan with SDK 44. It's a native module so i created a development client with eas build. Evererything was working as expected. 
Now I did an upgrade to SDK 47 and did a rebuild of the development client. The build worked but when i want to run the App the console prints: TypeError: null is not an object (evaluating 'RNGeniusScan.generateDocument')

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

Versions of the working development client:

 "expo": "^44.0.0",
 "expo-dev-client": "~0.8.3",
 "@thegrizzlylabs/react-native-genius-scan": "^4.4.5",

Versions with problemens:
"@thegrizzlylabs/react-native-genius-scan": "^4.7.0",
"expo": "^47.0.0",
"expo-dev-client": "~2.0.0",
      
     

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.2.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.9.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Reproducible demo

`import React from 'react';
import { View, Button } from "react-native";
import RNGeniusScan from "@thegrizzlylabs/react-native-genius-scan";

export default function App() {
    return (
        <View
            style={{
                flex: 1,
                justifyContent: "center",
                alignItems: "center",
            }}>
            <Button
                onPress={async () => {
                    try {
                        await RNGeniusScan.setLicenceKey("REPLACE_WITH_YOUR_LICENCE_KEY");

                        // Start scan flow
                        let scanResult = await RNGeniusScan.scanWithConfiguration(configuration);

                        // The result object contains the captured scans as well as the multipage document
                        console.log(scanResult);
                    } catch (e) {}
                }}
                title="Start scanning"
            />
        </View>
    );
}
`

**Comment by lukmccall** [comment]
Hi @zewas-digital, thanks for your report. Could you try to use the same version of the `@thegrizzlylabs/react-native-genius-scan` package in both cases? I see that you bump that as well.

**Comment by zewas-digital** [comment]
> Hi @zewas-digital, thanks for your report. Could you try to use the same version of the `@thegrizzlylabs/react-native-genius-scan` package in both cases? I see that you bump that as well.

Hello, I'm getting the same issue with  react-native-genius-scan Version 4.4.5
