### ISSUE TITLE
[docs] Facebook Login

### ISSUE THREAD

**Issue by collaorodrigo7** [expo/expo#19956]
### Summary

The Facebook Authentication documentation mentions the setup that needs to be done for Expo Go, Custom Apps, Native iOS and Native Android. However, there is no mention of which to follow for the BUILDS of Managed Workflow.
So, I am assuming that for the builds of a managed workflow I should look into Native iOS and Native Android.

On the Native Android section, the documentation discusses the steps to follow on the Developer site of Facebook. On this section the Class Name is discussed, and the text on the docs explains it should be set to something like: `com.bacon.yolo15.MainActivity`, but the screenshot shows: `com.bacon.yolo15.MainApplication`. (MainActivity vs MainApplication). I assumed what is on the text is more accurate that on the screenshot, however in my case I was NOT ABLE to get my Facebook login to work.

Then the documentation discusses what to do if the app crashes with `Didn't find class "com.facebook.CustomTabActivity" on ...` and proposes a solution. But IFF the Native Android is the approach for Managed Workflows BUILDS, then as far as I know we get no access to modify the AndroidManifest.xml.
Also, while I am personally experiencing this problem with the `com.facebook.CustomTabActivity` (I can see it in logcat) my app is NOT really CRASHING, it is just navigating to a blank page, and I can totally hit back on android and go back to the previous page and use the app normally.

I was able to get my Facebook login using Expo Go (both Android and iOS) and iOS Build just fine, but following what the docs says I was not able to get it to work on an Android Build

### Link to the related docs page

https://docs.expo.dev/guides/authentication/#facebook

**Comment by brentvatne** [comment]
hi there! authentication can be very frustrating to set up! for sdk 46+ apps we recommend using react-native-fbsdk-next. we only recommend using expo-auth-session for this within expo go. see installation instructions here: https://github.com/thebergamo/react-native-fbsdk-next#expo-installation

see in our docs:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/90494/204062379-204d583d-1cde-4510-a62e-9ae01224601e.png">
