### ISSUE TITLE
is it impossble to pull all the music in my phone by expo?

### ISSUE THREAD

**Issue by kidow** [expo/expo#1995]
I want to make a simple music player, However, no function of expo seems to support this.

First of all, I want to know whether it is possible.

I do not know if I should ask this question here, but I have not got the answer in any community.

if this is impossible, I wonder whether you will update this in the future.

**Comment by ccheever** [comment]
Hi- This isn't a thing you can do with Expo yet. You could detach and use Expo to build most of the UI and add your own native code for doing this.

You can add a feature request that other people can vote on here: https://expo.canny.io/feature-requests

Sorry this feature isn't available yet!
