### ISSUE TITLE
Packages out of date holding back feature

### ISSUE THREAD

**Issue by goatandsheep** [expo/expo#19964]
### Summary

Hi! Great project! I am maintaining a library and to prevent a caching bug in React Native, we worked on adding a new feature to Babel. We launched the feature, but now it might have been too early since a few libs need to be updated before it can work. These are deps for the webpack-config lib

### Environment

These are deps for the webpack-config lib

### Minimal reproducible example

I've opened a PR here https://github.com/expo/expo-cli/pull/4593

**Comment by Simek** [comment]
Hello @goatandsheep, since you have already opened issues in CLI repo there is no need to duplicate or create acknowledgement one in core repo, so I'm going to close this one.

**Comment by goatandsheep** [comment]
To clarify, I have not opened any issues in the other repo. Just PR
