### ISSUE TITLE
Android push notification icon too small / documentation outdated

### ISSUE THREAD

**Issue by kelvinlawson** [expo/expo#1996]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 7.6.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Android standalone build.

### Steps to Reproduce

(Write your steps here:)

1. Add 48x48 notification icon as described in the documentation https://docs.expo.io/versions/latest/guides/configuration.html#notification
2. Build Android standalone app.
3. Run on Pixel 2 phone.

### Expected Behavior

Normal-sized push notification icon in status bar

### Actual Behavior

Push notification icon in status bar is too small

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by esamelson** [comment]
apologies for the extremely slow followup here. I've updated the docs to reflect the new correct size of 96x96.
