### ISSUE TITLE
expo-auth-session for facebook is not working on Samsung browser

### ISSUE THREAD

**Issue by Majd-eddine-BEN-TAHAR** [expo/expo#19970]
### Summary

when i try to login into my facebook account using expo-auth-session package to get an access_token from Facebook it tells me that logging into facebook from an embedded browser is disabled, and i already activated logging from an embedded browser functionality in my facebook developer account, but when i use chrome browser everything works appropriately without issues.
![photo_2022-11-10_12-57-56](https://user-images.githubusercontent.com/45672105/201084778-4850bf00-d556-4634-9668-741dd99d4c0a.jpg)

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

```
import { View, Button } from "react-native";
import { useEffect } from "react";
import * as Facebook from "expo-auth-session/providers/facebook";
import * as AuthSession from "expo-auth-session";
import { ResponseType } from "expo-auth-session";

export default function App() {
  const [request, response, promptAsync] = Facebook.useAuthRequest({
    responseType: ResponseType.Token,
    clientId: "xxxxxxxxxxxxxxxxxxx",
    redirectUri: AuthSession.makeRedirectUri({ useProxy: true }),
  });

  useEffect(() => {
    if (response?.type === "success") {
      const { code } = response.params;
      console.log(code);
    }
  }, [response]);

  return (
    <View>
      <Button
        disabled={!request}
        title="Login"
        onPress={() => {
          promptAsync();
        }}
      />
    </View>
  );
}
```

**Comment by Kudo** [comment]
hi there! it seems the [embedded browser login is deprecated](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews). maybe that's the reason you cannot use it through the builtin webview?

**Comment by Majd-eddine-BEN-TAHAR** [comment]
emmmm, yes it seems that's the issue, thanks for the reply.
