### ISSUE TITLE
Push notification-listener won't fire at all

### ISSUE THREAD

**Issue by OlaAlsaker** [expo/expo#1997]
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.2
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/olaalsaker-93beae22-0fab-43fe-9eae-f3e5b3678999.tar.gz
```

Target: iOS

### Steps to Reproduce

1. The code it copied from Expo's documentation, and implemented in app.
2. I try to send a notification to the device (both through Expo's tool, and also through Postman). I have tried different types of field-combinations, i.e. both with and without data.
3. The iOS-device **do actually** receive the notification, and the process works like normal.
4. The bug happens when I try to enter the app through the notification. The app opens, but the _handleNotification-functions is _never_ fired.

### Expected Behavior

Normally, the _handleNotification-function would have been run, and I could get data from the notification and do other actions in the app.

### Actual Behavior

I have tried to make all the functions as simple as possible, but they still will not work. This is my functions: 

```
  componentDidMount() {
    registerForPushNotificationsAsync();
    this._notificationSubscription = Notifications.addListener(this._handleNotification);
  }

  ...

  _handleNotification = (notification) => {
    console.log(notification);
  };
```

Like I've already written, the _handleNotification-function is never firing. And the weirdest part is that it all worked perfect earlier today. Suddenly it stopped working. I didn't even change any code related to the push-notifications.

The notification is delivered to my (locked) phone, shows up on lockscreen, but when I open the notification, the app doesn't handle it.

The componentDidMount()-function **is being fired**, I can confirm that.

### Reproducible Demo

https://snack.expo.io/HJ1koIoXQ

I have made a reproducible demo. Tried this on my device, and I actually get the **exact same problem**. The _handleNotification-function is never run.

Thanks for your time!

**Comment by brentvatne** [comment]
hi! @esamelson and @terribleben will investigate this

**Comment by ide** [comment]
Sorry about the interruption. This was a server-side issue; closing since this incident at hand has been resolved.
