### ISSUE TITLE
LightSensor doesn't seem to be inside the expo-sensors package.

### ISSUE THREAD

**Issue by lstribli** [expo/expo#19986]
### Summary

I've installed the expo-sensors @ SDK v46.
The LightSensor simply isn't in there. 

After importing the sensors into the project and making a log of them, it appears LightSensor did not make it into the package.

import React, { useState, useEffect } from 'react';
import * as Sensors from 'expo-sensors'

Below is the output of console.log(Sensors): 

{"Accelerometer": {"_listenerCount": 0, "_nativeEmitter": {"_eventEmitter": [NativeEventEmitter], "_listenerCount": 0, "_nativeModule": [Object]}, "_nativeEventName": "accelerometerDidUpdate", "_nativeModule": {"addListener": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeListeners": [Function anonymous], "setUpdateInterval": [Function anonymous], "startObserving": [Function anonymous], "stopObserving": [Function anonymous]}, "addListener": [Function anonymous], "getListenerCount": [Function anonymous], "getPermissionsAsync": [Function anonymous], "hasListeners": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeAllListeners": [Function anonymous], "removeSubscription": [Function anonymous], "requestPermissionsAsync": [Function anonymous], "setUpdateInterval": [Function anonymous]}, 

"Barometer": {"_listenerCount": 0, "_nativeEmitter": {"_eventEmitter": [NativeEventEmitter], "_listenerCount": 0, "_nativeModule": [Object]}, "_nativeEventName": "barometerDidUpdate", "_nativeModule": {"addListener": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeListeners": [Function anonymous], "setUpdateInterval": [Function anonymous], "startObserving": [Function anonymous], "stopObserving": [Function anonymous]}, "addListener": [Function anonymous], "getListenerCount": [Function anonymous], "getPermissionsAsync": [Function anonymous], "hasListeners": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeAllListeners": [Function anonymous], "removeSubscription": [Function anonymous], "requestPermissionsAsync": [Function anonymous], "setUpdateInterval": [Function anonymous]}, 

"DeviceMotion": {"Gravity": 9.80665, "_listenerCount": 0, "_nativeEmitter": {"_eventEmitter": [NativeEventEmitter], "_listenerCount": 0, "_nativeModule": [Object]}, "_nativeEventName": "deviceMotionDidUpdate", "_nativeModule": {"Gravity": 9.80665, "addListener": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeListeners": [Function anonymous], "setUpdateInterval": [Function anonymous], "startObserving": [Function anonymous], "stopObserving": [Function anonymous]}, "addListener": [Function anonymous], "getListenerCount": [Function anonymous], "getPermissionsAsync": [Function anonymous], "hasListeners": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeAllListeners": [Function anonymous], "removeSubscription": [Function anonymous], "requestPermissionsAsync": [Function anonymous], "setUpdateInterval": [Function anonymous]}, "DeviceSensor": [Function DeviceSensor], 

"Gyroscope": {"_listenerCount": 0, "_nativeEmitter": {"_eventEmitter": [NativeEventEmitter], "_listenerCount": 0, "_nativeModule": [Object]}, "_nativeEventName": "gyroscopeDidUpdate", "_nativeModule": {"addListener": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeListeners": [Function anonymous], "setUpdateInterval": [Function anonymous], "startObserving": [Function anonymous], "stopObserving": [Function anonymous]}, "addListener": [Function anonymous], "getListenerCount": [Function anonymous], "getPermissionsAsync": [Function anonymous], "hasListeners": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeAllListeners": [Function anonymous], "removeSubscription": [Function anonymous], "requestPermissionsAsync": [Function anonymous], "setUpdateInterval": [Function anonymous]}, 

"Magnetometer": {"_listenerCount": 0, "_nativeEmitter": {"_eventEmitter": [NativeEventEmitter], "_listenerCount": 0, "_nativeModule": [Object]}, "_nativeEventName": "magnetometerDidUpdate", "_nativeModule": {"addListener": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeListeners": [Function anonymous], "setUpdateInterval": [Function anonymous], "startObserving": [Function anonymous], "stopObserving": [Function anonymous]}, "addListener": [Function anonymous], "getListenerCount": [Function anonymous], "getPermissionsAsync": [Function anonymous], "hasListeners": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeAllListeners": [Function anonymous], "removeSubscription": [Function anonymous], "requestPermissionsAsync": [Function anonymous], "setUpdateInterval": [Function anonymous]}, 

"MagnetometerUncalibrated": {"_listenerCount": 0, "_nativeEmitter": {"_eventEmitter": [NativeEventEmitter], "_listenerCount": 0, "_nativeModule": [Object]}, "_nativeEventName": "magnetometerUncalibratedDidUpdate", "_nativeModule": {"addListener": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeListeners": [Function anonymous], "setUpdateInterval": [Function anonymous], "startObserving": [Function anonymous], "stopObserving": [Function anonymous]}, "addListener": [Function anonymous], "getListenerCount": [Function anonymous], "getPermissionsAsync": [Function anonymous], "hasListeners": [Function anonymous], "isAvailableAsync": [Function anonymous], "removeAllListeners": [Function anonymous], "removeSubscription": [Function anonymous], "requestPermissionsAsync": [Function anonymous], "setUpdateInterval": [Function anonymous]}, 

"Pedometer": {"PermissionStatus": {"DENIED": "denied", "GRANTED": "granted", "UNDETERMINED": "undetermined"}, "getPermissionsAsync": [Function getPermissionsAsync], "getStepCountAsync": [Function getStepCountAsync], "isAvailableAsync": [Function isAvailableAsync], "requestPermissionsAsync": [Function requestPermissionsAsync], "watchStepCount": [Function watchStepCount]}}

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /opt/homebrew/bin/node
      npm: 6.14.15 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

`import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import { Card } from 'react-native-paper';

//package in question
import * as Sensors from 'expo-sensors'

export default function App() { 

//no LightSensor but expo has full documentation for it for this SDK version. 
  console.log(Sensors)

//just a view + text. 
  return (
    <View style={styles.container}>
      <Text style={styles.paragraph}>
      No Light Sensors 
     </Text>
      <Card>
      </Card>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
`

**Comment by zbagdzevicius** [comment]
I can reproduce the same

**Comment by brentvatne** [comment]
as @zbagdzevicius pointed out, this is in sdk 47 and not sdk 46
