### ISSUE TITLE
[SDK 46] expo-image-picker launchImageLibraryAsync returns inconsistent results on Android

### ISSUE THREAD

**Issue by ShaneMcNamara** [expo/expo#19985]
### Summary

When using expo-image-picker to select multiple photos on Android, the return data format is dependant on how the user selects the photos.

I would expect, given the documentation, that providing `allowsMultipleSelection: true` would always return [ImagePickerMultipleResult](https://docs.expo.dev/versions/v46.0.0/sdk/imagepicker/#imagepickermultipleresult), but if the user selects photos in a certain way, `launchImageLibraryAsync` returns [ImagePickerResult](https://docs.expo.dev/versions/v46.0.0/sdk/imagepicker/#imagepickerresult)

See recording below:

https://user-images.githubusercontent.com/9358722/201207082-92e64a25-8170-458e-9d64-566ac1c35471.mov

I would expect the result data format to be consistent with the function arguments provided, not dependant on where the user selects the photos from.

### What platform(s) does this occur on?

Android

### Environment

> expo-env-info 1.0.5 environment info:
>     System:
>       OS: macOS 10.15.7
>       Shell: 5.7.1 - /bin/zsh
>     Binaries:
>       Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
>       Yarn: 1.19.1 - /usr/local/bin/yarn
>       npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     Managers:
>       CocoaPods: 1.8.3 - /Users/ShaneMcNamara/.rvm/gems/ruby-2.2.0/bin/pod
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
>     IDEs:
>       Android Studio: 2021.3 AI-213.7172.25.2113.9123335
>       Xcode: 12.4/12D4e - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ^46.0.17 => 46.0.17 
>       react: 18.0.0 => 18.0.0 
>       react-native: 0.69.6 => 0.69.6 
>     npmGlobalPackages:
>       eas-cli: 2.6.0
>       expo-cli: 6.0.8
>     Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@ontraccr/540ee4

**Comment by hirbod** [comment]
It kinda looks ok after I've watched your video. First time you're selecting a single item, so you didn't get an array of selected elements. The 2nd time you selected multiple. You could easily check if its an array or not.

Is iOS returning the same?

**Comment by ShaneMcNamara** [comment]
> It kinda looks ok after I've watched your video. First time you're selecting a single item, so you didn't get an array of selected elements. The 2nd time you selected multiple. You could easily check if its an array or not.

That's not really then point. You can easily check, but it is bad API design. If the developer passes the `allowsMultipleSelection` flag, they should always receive the `selected` array in the response (as is indicated in the documentation [here](https://docs.expo.dev/versions/v46.0.0/sdk/imagepicker/#expandimagepickerresultt))


> 
> The 2nd selector looks different than the first though. What happens if you only select a single item on the 2nd flow?

The response does not have the `selected` array.

> Is iOS returning the same?

 iOS always returns `selected`, regardless if one or more items are selected. FYI there is a Snack you can play with
 
 I just noticed that SDK 47 changes the return type again (to use the `assets` key) (See [here](https://github.com/expo/expo/pull/19570)). Given that fact, it's probably only worthwhile to update [the documentation](https://docs.expo.dev/versions/v46.0.0/sdk/imagepicker/#imagepickerlaunchimagelibraryasyncoptions) to specify that the return type can be in either format

**Comment by hirbod** [comment]
Ok, if its not inline with iOS then it is probably a bug. What looks odd for me in your video though is that it looks like the picker is single and multiple selection based on how you entered into the album. Maybe an Android OS thing. But after going through, I agree that it is inconsistent.

**Comment by hirbod** [comment]
Btw, have you seen this? https://github.com/expo/expo/pull/19570

It also looks like this has been changed in SDK 47 already

**Comment by hirbod** [comment]
In case you came here for email notifications, I've deleted some posts since I've written them to fast without checking myself. You are right, and it looks like its already reworked for SDK 47 - so this might just need a docs update for SDK 46

**Comment by brentvatne** [comment]
indeed we updated the api and documentation in sdk 47 around this because we also found it confusing. now the result always returns the `assets` key.

we typically don't make updates to old sdks unless it's required to fix urgent issues, so i'm going to close this, but if you'd like to send a pr to update the docs for sdk 46 we can merge that.
