### ISSUE TITLE
Scan specific QR code not working on Android.

### ISSUE THREAD

**Issue by sergeu90** [expo/expo#19984]
### Summary

We found qr code which not working on android devices but on ios qr good. In android emulator work also but on real devices not working.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.17 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 32, 33
        Build Tools: 32.0.0, 32.1.0, 33.0.0, 33.0.0
        System Images: android-25 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google APIs ATD ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.17.2 => 0.17.2 
      expo: 46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: 0.18.9 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Use expo-camera or expo-barcode-scanner and scan next qr code onBarCodeScanned event not fired.
![2022-11-10 21 21 08](https://user-images.githubusercontent.com/7217517/201197899-961b398d-96d9-432d-a364-4aaa27990a0b.jpg)

```
 <Camera
    barCodeScannerSettings={{
      barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
    }}
    onBarCodeScanned={isScanned ? undefined : handleScannedCode}
/>
```

**Comment by brentvatne** [comment]
we use google mobile vision (if available on device) or zxing for barcode scanning, we don't implement the algorithm ourselves. you'd need to file an issue on one of those repositories about this particular qr code.

https://github.com/expo/expo/tree/main/packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners
