### ISSUE TITLE
Related to expo-auth-session "Not found" error in SDK 45-47 - Can I downgrade Expo Go???

### ISSUE THREAD

**Issue by bportman** [expo/expo#19983]
### Summary

After encountering the issue [here](https://github.com/expo/expo/issues/19356) which is not fixed and exists in SDK 45, 46 and 47, I downgraded my app back to SDK 44.  Our users are accessing the app with Expo Go, and 2 days ago Expo Go was updated to eliminate support for SDK 44!  We can't upgrade because of the expo-auth-session "Not Found" issue, but now we can no longer use our app on the lower SDK version.  Is there a way to downgrade Expo Go back to the version that supported SDK 44?

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.2.1
      expo-cli: 5.4.11
    Expo Workflow: managed

### Minimal reproducible example

See linked issue above.  Main concern and reason for a separate issue is how do I downgrade Expo Go on iOS once it's been automatically updated?  Need to restore SDK 44 support until the linked issue is fixed in later versions.

**Comment by bportman** [comment]
I figured out a solution for the underlying issue that I linked to, but would still love to know if there's a way to downgrade Expo Go to use older SDK versions

**Comment by Kudo** [comment]
hi there! you could try to run `npx expo client:install:android` in your sdk 44 project. the command will find the matching expo go and install for you.
