### ISSUE TITLE
Access call logs

### ISSUE THREAD

**Issue by mohammad6vakili** [expo/expo#19992]
### Summary

I need to access call logs but I can't access them.
As I know there's no way to access call logs yet but I have an important question.
What should I do now?
I can't use native modules because of expo and now expo hasn't a very important feature.

### What platform(s) does this occur on?

Android

### Environment

"expo": "~46.0.7",
"react-native": "0.69.6"

### Minimal reproducible example

"permissions":["READ_CALL_LOG"],

**Comment by Kudo** [comment]
hi there! you could add the permission on [development builds](https://docs.expo.dev/development/introduction/). either by adding the permission through [config-plugins](https://docs.expo.dev/guides/config-plugins/#modifying-the-androidmanifestxml) or creating an [expo native module](https://docs.expo.dev/modules/overview/) with AndroidManifest.xml.

**Comment by AntonewtonQ** [comment]
Interesting 👍🏾👍🏾
