### ISSUE TITLE
[SDK 47] [expo-image-picker] The HEIF picture cannot be picked in version 14.0.1.

### ISSUE THREAD

**Issue by seungyoubkim** [expo/expo#19990]
### Summary

I upgraded the version of expo-image-picker to 14.0.1, but I couldn't pick the HEIF picture.

This error occurs.

```
[Foundation] B98ABE18-73E0-4DEB-882E-52CE1EC23E72 grantAccessClaim reply is an error: Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x60000087a9a0 {Error Domain=PHAssetExportRequestErrorDomain Code=0 "작업을 완료할 수
없습니다.(PHAssetExportRequestErrorDomain 오류 0.)" UserInfo={NSLocalizedDescription=작업을 완료할 수 없습니다.(PHAssetExportRequestErrorDomain 오류 0.), NSUnderlyingError=0x60000087a910 {Error Domain=PAMediaConversionServiceErrorDomain Code=2 "작업을 완료할 수 없습니다.(PAMediaConversionServiceErrorDomain 오류
2.)" UserInfo={NSLocalizedDescription=작업을 완료할 수 없습니다.(PAMediaConversionServiceErrorDomain 오류 2.)}}}}}
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Failed to read picked image
→ Caused by: Cannot load representation of type public.jpeg
construct@[native code]
construct@[native code]
_construct@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.anonymous.expo-47-demo:20328:28
Wrapper@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.anonymous.expo-47-demo:20290:25
construct@[native code]
_createSuperInternal@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.anonymous.expo-47-demo:99261:322
CodedError@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.anonymous.expo-47-demo:99269:26
```

This is the picture that tried to pick.
![스크린샷 2022-11-11 오후 3 29 46](https://user-images.githubusercontent.com/106951161/201286828-1dc697cb-c4c0-4b99-9338-b9cff1142540.png)

Other JPEG photos work well.

HEIF pictures also work well if you give the allowEditing property to true. But I don't want to use the allowEditing property.

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.9.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.1 - /opt/homebrew/bin/npm
      Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/kimseung-youb/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Minimal reproducible example

```
import React from 'react';
import { View, Image, Button } from 'react-native';
import * as ImagePicker from 'expo-image-picker';

export default function App() {
  const [uri, setUri] = React.useState('');

  const pickImage = async () => {
    const result = await ImagePicker.launchImageLibraryAsync({ quality: 1 });

    if (!result.canceled) {
      setUri(result.assets[0].uri);
    }
  };

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      {uri && (<Image style={{ width: 320, height: 240 }} source={{ uri }}></Image>)}
      <Button title={'Upload Image'} onPress={pickImage}></Button>
    </View>
  );
}
```

I attached the code directly because the version of expo 47 is not supported by the snack.

Version of expo - 47.0.3, Version of expo-image-picker - 14.0.1.

**Comment by barthap** [comment]
This looks like a simulator issue - it's unrelated to Expo. Are you on an M1/M2 mac? It happened to me in various Xcode/Simulator configurations. Usually updating Xcode helped or opening in another simulator (e.g. iPhone 14 Pro instead of iPhone 14).

**Comment by seungyoubkim** [comment]
> This looks like a simulator issue - it's unrelated to Expo. Are you on an M1/M2 mac? It happened to me in various Xcode/Simulator configurations. Usually updating Xcode helps or opening in another simulator (e.g. iPhone 14 Pro instead of iPhone 14).

Thank you for your answer. I think HEIF photos taken with real iPhone work well.

However, even if I update the xcode and test it with other simulators, the picture mentioned in the original post does not work well. The xcode version is 14.1.

I am using the M1 mac.

Is it okay to believe that this is a simulator issue that won't happen on the real iPhone?

I would like to quickly test with the expo 47 version on the snack..

**Comment by barthap** [comment]
This is for sure M1-specific simulator issue. It even happens to people using only native Swift code ([example 1](https://developer.apple.com/forums/thread/653993), [example 2](https://developer.apple.com/forums/thread/699155)).
It works with `allowsEditing: true` because with this option, under the hood it uses `UIImagePickerController` (old Apple picker component) instead of `PHPickerViewController` (new iOS 14+ native component)

Also, you can try running Xcode with/without Rosetta (make sure to exit both xcode and simulator first) - this also helped me once. I haven't found a single reliable solution for this, unfortunately. Usually I'm juggling with Xcode and Simulator versions.

**Comment by seungyoubkim** [comment]
> This is for sure M1-specific simulator issue. It even happens to people using only native Swift code ([example 1](https://developer.apple.com/forums/thread/653993), [example 2](https://developer.apple.com/forums/thread/699155)). It works with `allowsEditing: true` because with this option, under the hood it uses `UIImagePickerController` (old Apple picker component) instead of `PHPickerViewController` (new iOS 14+ native component)
> 
> Also, you can try running Xcode with/without Rosetta (make sure to exit both xcode and simulator first) - this also helped me once. I haven't found a single reliable solution for this, unfortunately. Usually I'm juggling with Xcode and Simulator versions and encountered this issue in various configurations.

If it's an issue that only occurs in the simulator, I think it'll be okay for me.

Thank you very much for your detailed reply! 😆
