### ISSUE TITLE
`onLayout` event nullified on `KeyboardAvoidingView` with SDK 47

### ISSUE THREAD

**Issue by jhogervorst** [expo/expo#19999]
### Summary

After upgrading to Expo SDK 47, `onLayout` on `KeyboardAvoidingView` is no longer working correctly. When accessing the event's `nativeEvent`, a warning is shown that that property is set to `null`:

> Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://reactjs.org/link/event-pooling for more information.

Using `event.persist()` does not make a difference, the issue remains.

When changing `KeyboardAvoidingView` to `View` in the example, the issue no longer occurs, so it seems related to `KeyboardAvoidingView`. The same code worked fine with Expo SDK 46, so it must be related to a recent change.

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.1.1 - /opt/homebrew/bin/npm
      Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Minimal reproducible example

```jsx
export default function App() {
  const onLayout = ({ nativeEvent }) =>
    console.log(
      `Dimensions: ${nativeEvent.layout.width} x ${nativeEvent.layout.height}`
    );

  return <KeyboardAvoidingView style={styles.container} onLayout={onLayout} />;
}
```

https://snack.expo.dev/@jnthn/privileged-churros

Download the Snack. Run `npm install` and then `npm run ios`. Observe the following output in the console:

```
 ERROR  Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://reactjs.org/link/event-pooling for more information.
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: null is not an object (evaluating 'nativeEvent.layout')
onLayout@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:103684:54
@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:89466:33
generatorResume@[native code]
asyncGeneratorStep@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:22170:26
_next@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:22189:29
tryCallOne@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:26927:16
@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:27008:27
@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:27952:26
_callTimer@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:27867:17
_callReactNativeMicrotasksPass@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:27900:17
callReactNativeMicrotasks@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:28064:44
__callReactNativeMicrotasks@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:21289:46
@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:21089:45
__guard@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:21269:15
flushedQueue@http://10.0.0.5:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false:21088:21
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]
```

**Comment by brentvatne** [comment]
this appears to be a bug in react-native core -- we don't ship `KeyboardAvoidingView` from this repository, it's in https://github.com/facebook/react-native/ -- can you open this issue there instead?

**Comment by uladkasach** [comment]
Likewise. Any solution here? If this is an issue with react-native core, which version of expo has the react-native core version in which this works?

**Comment by brentvatne** [comment]
@uladkasach - you would have to verify whether this is fixed in react-native core even in the latest version. you can see a mapping of expo sdk versions to react-native versions here: https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a-react-native-version

you might have better luck using a third party library that works better than the one built into core, such as: https://github.com/kirillzyusko/react-native-keyboard-controller

**Comment by Justin-Credible** [comment]
The workaround I went with was to use [patch-package](https://www.npmjs.com/package/patch-package) to automatically apply the following patch via a `postinstall` script.

`react-native+0.71.8.patch`
```
diff --git a/node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js b/node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js
index 6a343d8..474b2ec 100644
--- a/node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js
+++ b/node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js
@@ -111,6 +111,10 @@ class KeyboardAvoidingView extends React.Component<Props, State> {
       this._initialFrameHeight = this._frame.height;
     }
 
+    if (this.props.onLayout) {
+      event.persist();
+    }
+
     if (wasFrameNull) {
       await this._updateBottomIfNecessary();
     }
diff --git a/node_modules/react-native/scripts/.packager.env b/node_modules/react-native/scripts/.packager.env
new file mode 100644
index 0000000..c02fc25
--- /dev/null
+++ b/node_modules/react-native/scripts/.packager.env
@@ -0,0 +1 @@
+export RCT_METRO_PORT=8082
```

**Comment by Thanh-Long-Vu** [comment]
> The workaround I went with was to use [patch-package](https://www.npmjs.com/package/patch-package) to automatically apply the following patch via a `postinstall` script.
> 
> `react-native+0.71.8.patch`
> 
> ```
> diff --git a/node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js b/node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js
> index 6a343d8..474b2ec 100644
> --- a/node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js
> +++ b/node_modules/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js
> @@ -111,6 +111,10 @@ class KeyboardAvoidingView extends React.Component<Props, State> {
>        this._initialFrameHeight = this._frame.height;
>      }
>  
> +    if (this.props.onLayout) {
> +      event.persist();
> +    }
> +
>      if (wasFrameNull) {
>        await this._updateBottomIfNecessary();
>      }
> diff --git a/node_modules/react-native/scripts/.packager.env b/node_modules/react-native/scripts/.packager.env
> new file mode 100644
> index 0000000..c02fc25
> --- /dev/null
> +++ b/node_modules/react-native/scripts/.packager.env
> @@ -0,0 +1 @@
> +export RCT_METRO_PORT=8082
> ```
Is it the best solution ?
https://github.com/facebook/react-native/issues/35599#issuecomment-2661887004
