### ISSUE TITLE
Hot reloading doesn't work with Android and iOS together.

### ISSUE THREAD

**Issue by anthony-tietjen** [expo/expo#20]
I cannot do Hot Reloading on both iOS and Android devices at the same time. If I have hot reloading working on the Android, then in order for hot reloading to work on the iPhone, I first have to "Reload" manually on the iPhone. But then it turns off hot reloading on the Android. Then if I do a manual "Reload" on the Android to get hot reloading working again, it turns off hot reloading for the iPhone.

**Comment by brentvatne** [comment]
does this work on react-native without exponent?

**Comment by terribleben** [comment]
I think this is an issue with the underlying react native HMR implementation.
