### ISSUE TITLE
Android Contacts API does not return phone numbers

### ISSUE THREAD

**Issue by pushups** [expo/expo#200]
1. Add a contact on an Android emulator.

![image](https://cloud.githubusercontent.com/assets/573678/26270629/50dc016e-3cb1-11e7-94f6-e6ed1d30695b.png)

2. Execute the following code on the Android emulator:

```const permission = await Expo.Permissions.askAsync(Expo.Permissions.CONTACTS);
    if (permission.status !== 'granted') {
      return;
    }
    const contacts = await Expo.Contacts.getContactsAsync({
      fields: [
        Expo.Contacts.PHONE_NUMBERS,
        Expo.Contacts.EMAILS,
      ],
      pageSize: 10,
      pageOffset: 0,
    });

    console.log(contacts.data);
```

Result:
```[{"name":"Some Guy","id":1,"phoneNumbers":[{"label":"home"}]}]```

Expected result:
The contacts API on Android returns a phone number if it is present.

Result On iOS for comparison:
```[{"emails":[{"email":"John-Appleseed@mac.com","label":"work"}],"firstName":"John","id":"717282E3-07C0-4864-95F4-BD3A6BAFE383","middleName":"","company":"","jobTitle":"","phoneNumbers":[{"number":"888-555-5512","label":"mobile"},{"number":"888-555-1212","label":"home"}],"name":"John Appleseed","lastName":"Appleseed"}, ... ]```

**Comment by raarts** [comment]
I can confirm this is happening for me as well.

**Comment by janicduplessis** [comment]
I think #210 should fix this feel free to reopen if it is not the case.
