### ISSUE TITLE
Depois de dois dias, este me salvou. Obrigado

### ISSUE THREAD

**Issue by nerialdo** [expo/expo#20004]
this works for me: 

I used this command: 
> npm ls expo-cli --global

it res =  

> /home/myUser/‘~/.npm-global/lib

and then I add at bottom of .`zshrc`  and .`bashrc`  this line: 

>  export PATH=$PATH:/home/myUser/‘~/.npm-global/bin   

Im using WSL2.
hope help someone else.

_Originally posted by @Cajavi89 in https://github.com/expo/expo-cli/issues/663#issuecomment-1132428896_

**Comment by brentvatne** [comment]
thanks for sharing, hopefully this helps someone else having npm configuration problems!
