### ISSUE TITLE
EAS build - Fastlane build failed

### ISSUE THREAD

**Issue by GKyomen** [expo/expo#20005]
### Summary

I'm trying to generate the first build of my app to the Apple Store, but the command `eas build -p ios` keeps failing with the following:
`
        › Compiling @react-native-firebase/app Pods/GoogleDataTransport » GoogleDataTransport_vers.c
        
        › Compiling @react-native-firebase/app Pods/GoogleDataTransport » GDTCORUploadCoordinator.m
        
        
        ⚠️  (/Users/expo/Library/Developer/Xcode/DerivedData/sivtecapp-dtaoxqrwbbvkhfcwhxoolgmgmkog/Build/Intermediates.noindex/ArchiveIntermediates/sivtecapp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/GDTCORUploadCoordinator.dia:1:1)
        
        CompileC /Users/expo/Library/Developer/Xcode/DerivedData/sivtecapp-dtaoxqrwbbvkhfcwhxoolgmgmkog/Build/Intermediates.noindex/ArchiveIntermediates/sivtecapp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/GDTCORUploadBatch.o...
        ^ Could not read serialized diagnostics file: error(in target 'GoogleDataTransport' from project 'Pods')
        (warning truncated)
        
        › Compiling @react-native-firebase/app Pods/GoogleDataTransport » GDTCORTransport.m
        
        › Compiling @react-native-firebase/app Pods/GoogleDataTransport » GDTCORTransformer.m
        
        › Compiling @react-native-firebase/app Pods/GoogleDataTransport » GDTCORStorageMetadata.m
        
        › Linking   react-native Pods/RCT-Folly » folly
        
        
        ❌  ld: -U and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
        
        
        ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
        
        ▸ ** ARCHIVE FAILED **
        
        ▸ The following build commands failed:
        
        ▸ 	Ld /Users/expo/Library/Developer/Xcode/DerivedData/sivtecapp-dtaoxqrwbbvkhfcwhxoolgmgmkog/Build/Intermediates.noindex/ArchiveIntermediates/sivtecapp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/folly.framework/folly normal (in target 'RCT-Folly' from project 'Pods')
        
        ▸ (1 failure)
        
        2022-11-11 09:00:16.522 xcodebuild[4608:15436] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
        
        2022-11-11 09:00:16.522 xcodebuild[4608:15436] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
        
        2022-11-11 09:00:16.588 xcodebuild[4608:15436] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
        
        2022-11-11 09:00:16.588 xcodebuild[4608:15436] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
        
        2022-11-11 09:00:16.588 xcodebuild[4608:15436] XType: unable to make a connection to the font daemon!
        
        2022-11-11 09:00:16.588 xcodebuild[4608:15436] XType: XTFontStaticRegistry is enabled as fontd is not available.
        
        ** ARCHIVE FAILED **
        
        The following build commands failed:

	Ld /Users/expo/Library/Developer/Xcode/DerivedData/sivtecapp-dtaoxqrwbbvkhfcwhxoolgmgmkog/Build/Intermediates.noindex/ArchiveIntermediates/sivtecapp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/folly.framework/folly normal (in target 'RCT-Folly' from project 'Pods')

        (1 failure)
        
        Exit status: 65
`

There are several other lines of output with `[stderr]`, but I don´t know if they'll help. Ask me if you think so.
I already tried updating xcode and cleaning every Pods related file, including cache.

### What platform(s) does this occur on?

iOS

### SDK Version

46

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 9.1.1 - ~/.nvm/versions/node/v16.18.1/bin/npm
    npmPackages:
      expo: ~46.0.6 => 46.0.6 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 2.6.0
    Expo Workflow: bare

### Minimal reproducible example

expo init
include these libs:
`
"dependencies": {
    "@expo-google-fonts/montserrat": "^0.2.2",
    "@expo/vector-icons": "^13.0.0",
    "@hookform/resolvers": "^2.9.7",
    "@miblanchard/react-native-slider": "^2.1.0",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-firebase/app": "~15.4.0",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "axios": "^0.27.2",
    "expo": "~46.0.6",
    "expo-camera": "~12.3.0",
    "expo-checkbox": "~2.2.0",
    "expo-file-system": "~14.1.0",
    "expo-font": "~10.2.0",
    "expo-image-picker": "~13.3.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-secure-store": "~11.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-hook-form": "^7.34.2",
    "react-native": "0.69.6",
    "react-native-mask-text": "^0.13.1",
    "react-native-modal-datetime-picker": "^14.0.0",
    "react-native-paper": "^4.12.5",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-timeline-flatlist": "^0.8.0",
    "react-native-web": "~0.18.7",
    "styled-components": "^5.3.5",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/eslint-parser": "^7.18.9",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "@types/styled-components-react-native": "^5.1.3",
    "@typescript-eslint/eslint-plugin": "^5.33.0",
    "@typescript-eslint/parser": "^5.33.0",
    "eslint": "^7.32.0 || ^8.2.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "prettier": "^2.7.1",
    "typescript": "^4.6.3"
  },`
yarn install
eas build --profile development --platform ios

**Comment by brentvatne** [comment]
it looks like you have bitcode enabled in your project. you should disable it, it is deprecated in xcode 14 anyhow.

**Comment by GKyomen** [comment]
@brentvatne I disabled it and eas build keeps it enabled with eas...

**Comment by brentvatne** [comment]
@GKyomen - eas does not enable bitcode. how are you disabling it? if you have a bare project, disable it directly in xcode. otherwise, use expo-build-properties.

**Comment by apedroferreira** [comment]
> @GKyomen - eas does not enable bitcode. how are you disabling it? if you have a bare project, disable it directly in xcode. otherwise, use expo-build-properties.

@brentvatne How can this be done using `expo-build-properties` more specifically? I'm having the same issue in a managed project, and I'm building using your cloud service, not locally.

**Comment by brentvatne** [comment]
@apedroferreira - my bad, it's actually just a field in app.json: https://docs.expo.dev/versions/latest/config/app/#bitcode

**Comment by brentvatne** [comment]
(set `"ios": { "bitcode": false }`)
