### ISSUE TITLE
expo-dev-client crashes on launch with jsEngine hermes in Expo SDK 47

### ISSUE THREAD

**Issue by tyrauber** [expo/expo#20007]
### Summary

In a blank typescript expo sdk 47 project with the expo-dev-client installed, the dev-client crashes on launch when `"jsEngine": "hermes"` is configured.   From both `expo run:ios -d` or `eas build --local`. Removing "jsEngine":"hermes" and doing a clean prebuild resolves the issue.  Android builds and launches fine with hermes enabled.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

```
  "dependencies": {
    "expo": "~47.0.3",
    "expo-dev-client": "~2.0.0",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-web": "~0.18.9",
    "expo-splash-screen": "~0.17.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~18.0.14",
    "@types/react-native": "~0.70.6",
    "typescript": "^4.6.3"
  },
  ```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2022.10.31.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/tyrauber/.rvm/gems/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: bare
```

### Reproducible demo

- `expo init` a new SDK 47 typescript blank project. 
- `expo install expo-dev-client`
- Add `"jsEngine": "Hermes"` to App.json
- `expo prebuild --clean`
- `expo run:ios -d`

Immediate crash on launch of expo dev client.

- `eas build --local` has the same result.

Building on EAS, I see the following error:

```

❌  ld: '/Users/expo/Library/Developer/Xcode/DerivedData/expo47hermes-ahzelgosugfnasazrehjslikbwpu/Build/Intermediates.noindex/ArchiveIntermediates/expo47hermes/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXFileSystem/EXFileSystem.framework/EXFileSystem(EXFileSystemAssetLibraryHandler.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/expo/Library/Developer/Xcode/DerivedData/expo47hermes-ahzelgosugfnasazrehjslikbwpu/Build/Intermediates.noindex/ArchiveIntermediates/expo47hermes/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXFileSystem/EXFileSystem.framework/EXFileSystem' for architecture arm64
```

If I add `"bitcode": "Debug"` to the ios declaration in app.json, run `expo prebuild --clean` and push a new build to eas, I see the following error:

```
❌  Undefined symbols for architecture arm64
┌─ Symbol: _objc_msgSend$storyboardWithName:bundle:
└─ Referenced from: l001 in EXSplashScreen(EXSplashScreenViewNativeProvider.o)

❌  ld: symbol(s) not found for architecture arm64


❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Stacktrace (if a crash is involved)

ASI found [dyld] (sensitive) 'Library not loaded: '@rpath/hermes.framework/hermes'
  Referenced from: '/private/var/containers/Bundle/Application/BDAD3C0A-943F-4416-851D-A0FF21314832/expo47hermes.app/expo47hermes'
  Reason: tried: '/usr/lib/swift/hermes.framework/hermes' (no such file), '/usr/lib/swift/hermes.framework/hermes' (no such file), '/private/var/containers/Bundle/Application/BDAD3C0A-943F-4416-851D-A0FF21314832/expo47hermes.app/Frameworks/hermes.framework/hermes' (no such file), '/usr/lib/swift/hermes.framework/hermes' (no such file), '/usr/lib/swift/hermes.framework/hermes' (no such file), '/private/var/containers/Bundle/Application/BDAD3C0A-943F-4416-851D-A0FF21314832/expo47hermes.app/Frameworks/hermes.framework/hermes' (no such file), '/System/Library/Frameworks/hermes.framework/hermes' (no such file)'

**Comment by RichardLindhout** [comment]
Have the same thing happening: xcode logs:

```
Library not loaded: @rpath/hermes.framework/hermes
  Referenced from:
```

**Comment by RichardLindhout** [comment]
This fixed it for me but since i gitignore the ios/android folder this. is not a 'real' solution
https://stackoverflow.com/questions/70875239/library-not-loaded-rpath-hermes-framework-hermes

**Comment by jp928** [comment]
I have same issue.

**Comment by DannyCui** [comment]
Same here, looking forward for a proper solution.

**Comment by mksglu** [comment]
I have same issue.

**Comment by atanaskanchev** [comment]
Couldn't get a remote EAS iOS simulator build to work

Build ID
ffb0b4f3-0e70-4f80-a244-6073448deb29

```
Waiting to start
1h 4m 34s

Spin up build environment
3m 24s

Pre-install hook
1s

Read package.json
1s

Install dependencies
7m 38s

Read app config
1s

Run expo doctor
13s

Prebuild
1s

Install pods
15m 59s

Configure expo-updates
1s

Run fastlane
20m 59s

Fail build
1s

Build failed: Something went wrong, marking build as errored
Your build exceeded the maximum build time of 45 minutes.
```

**Comment by nkjs-git** [comment]
Same error was seen when upgraded to react-native: 0.70.5 

❌  ld: '/Users/expo/Library/Developer/Xcode/DerivedData/expo47hermes-ahzelgosugfnasazrehjslikbwpu/Build/Intermediates.noindex/ArchiveIntermediates/expo47hermes/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXFileSystem/EXFileSystem.framework/EXFileSystem(EXFileSystemAssetLibraryHandler.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/expo/Library/Developer/Xcode/DerivedData/expo47hermes-ahzelgosugfnasazrehjslikbwpu/Build/Intermediates.noindex/ArchiveIntermediates/expo47hermes/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXFileSystem/EXFileSystem.framework/EXFileSystem' for architecture arm64

**Comment by tyrauber** [comment]
This issue is resolved in Expo 47.0.6+ with #20056, Nice work, @byCedric! Thank you.

**Comment by jp928** [comment]
@tyrauber I am still having this issue on 47.0.8

**Comment by atanaskanchev** [comment]
I had it resolved after updating to the latest version. Try a clean install and prebuild it

**Comment by jp928** [comment]
I tried remove ~/Library/Developer/Xcode/DerivedDa

but still have crash 

<img width="493" alt="Screen Shot 2022-11-24 at 11 10 19 pm" src="https://user-images.githubusercontent.com/659612/203781446-03f3fa06-9064-4987-a488-53266d8e63c2.png">
ta

**Comment by jp928** [comment]
@tyrauber We are asking hemes not jsbundle missing, hope we can re open this issue.

**Comment by jp928** [comment]
I think the problems is 

```
jsEngine: "hermes"
```

necessary, after I remove it from app.config.js the build works.

since Expo 47 announced `hermes` is default this may not need to be explicitly in app.config.js

**Comment by jp928** [comment]
checked by
```
const isHermes = () => !!global.HermesInternal;
```

hermes has to be enabled by 

```
jsEngine: "hermes"
```

the problem remains, any help would be appricated.

**Comment by RichardLindhout** [comment]
Expo 48 will enable it by default, 47 still needs explicit jsEngine

**Comment by RichardLindhout** [comment]
@jp928 delete whole ios directory and rebuild not only xcode cache :)

**Comment by jp928** [comment]
> @jp928 delete whole ios directory and rebuild not only xcode cache :)

I did. I even removed node_moudles no luck

**Comment by jp928** [comment]
Interestingly I swap to m1 chip mac and it works

**Comment by RichardLindhout** [comment]
It's still not working for me (on Intel MacBook)

**Comment by zaubara** [comment]
Upgrading ruby to the recommended >2.7.6 (used the most recent 2.x release 2.7.7) with rbenv seemed to make all the difference for me.

**Comment by enzomanuelmangano** [comment]
I still have the issue with `XCode 14.1` and `expo: 47.0.12`. https://github.com/expo/expo/issues/20007#issuecomment-1312447732 fixed for me, but as mentioned by @RichardLindhout that's not a valid solution since the ios folder is even added on the .gitignore

**Comment by robgraeber** [comment]
It works when using EAS but still crashes when built locally using `expo run:ios`. Assuming it's a cache thing, but I tried deleting the derived data folder.

**Comment by kendallroth** [comment]
Upgrading Ruby did not resolve the issue unfortunately. I am using Expo 47 with the managed workflow. This seems to only affect **local** builds for iOS when using `hermes` as the JS engine, so downgrading _temporarily_ to `jsc` is a workaround (not for production though!)

**Comment by Kudo** [comment]
We had seen some cases of CocoaPods doesn't install Hermes framework correctly.

### Ensure `Embed Pods Frameworks` in pbxpboj

`grep -A 20 'Embed Pods Frameworks' ios/*.xcodeproj/project.pbxproj`

There should be something like

```
		5BE576E1C4A2EF4F4904079F /* [CP] Embed Pods Frameworks */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputPaths = (
				"${PODS_ROOT}/Target Support Files/Pods-expo48app/Pods-expo48app-frameworks.sh",
				"${PODS_XCFRAMEWORKS_BUILD_DIR}/hermes-engine/Pre-built/hermes.framework/hermes",
			);
			name = "[CP] Embed Pods Frameworks";
			outputPaths = (
				"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/hermes.framework",
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "\"${PODS_ROOT}/Target Support Files/Pods-expo48app/Pods-expo48app-frameworks.sh\"\n";
			showEnvVarsInLog = 0;
		};
```

If missing this build phrase, the Hermes framework will not be packed into the app and cause the `Library not loaded` problem.

### Possible solution in the case

Similar https://github.com/expo/expo/issues/20007#issuecomment-1330347362 mentioned, reinstall ruby and cocoapods `gem uninstall cocoapods ; gem install cocoapods` did the trick from the case we seen.

**Comment by nicksiscoe** [comment]
> We had seen some cases of CocoaPods doesn't install Hermes framework correctly.
> 
> ### Ensure `Embed Pods Frameworks` in pbxpboj
> `grep -A 20 'Embed Pods Frameworks' ios/*.xcodeproj/project.pbxproj`
> 
> There should be something like
> 
> ```
> 		5BE576E1C4A2EF4F4904079F /* [CP] Embed Pods Frameworks */ = {
> 			isa = PBXShellScriptBuildPhase;
> 			buildActionMask = 2147483647;
> 			files = (
> 			);
> 			inputPaths = (
> 				"${PODS_ROOT}/Target Support Files/Pods-expo48app/Pods-expo48app-frameworks.sh",
> 				"${PODS_XCFRAMEWORKS_BUILD_DIR}/hermes-engine/Pre-built/hermes.framework/hermes",
> 			);
> 			name = "[CP] Embed Pods Frameworks";
> 			outputPaths = (
> 				"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/hermes.framework",
> 			);
> 			runOnlyForDeploymentPostprocessing = 0;
> 			shellPath = /bin/sh;
> 			shellScript = "\"${PODS_ROOT}/Target Support Files/Pods-expo48app/Pods-expo48app-frameworks.sh\"\n";
> 			showEnvVarsInLog = 0;
> 		};
> ```
> 
> If missing this build phrase, the Hermes framework will not be packed into the app and cause the `Library not loaded` problem.
> 
> ### Possible solution in the case
> Similar [#20007 (comment)](https://github.com/expo/expo/issues/20007#issuecomment-1330347362) mentioned, reinstall ruby and cocoapods `gem uninstall cocoapods ; gem install cocoapods` did the trick from the case we seen.

Just wanted to pop in and say I was having these hermes-related crashes on Expo SDK 48 and updating `cocoapods` with gem did the trick after hours of hitting my head against a wall :)
