### ISSUE TITLE
Expo Go App crashes at start

### ISSUE THREAD

**Issue by otekdo** [expo/expo#20019]
### Summary

Expo Go App (Version 2.26.4) always crashes.
When i open the app, i just see the splash screen, and the app automatically crashes.

### What platform(s) does this occur on?
Android

### Environment

Physical device:
- Samsung Galaxy Note 8 (SAMSUNG-SM-N950U) (Android 7.1.1)
- Expo Go App (Version 2.26.4) 

### Minimal reproducible example

Steps to reproduce the issue:
- Download expo go from play store
- Open Expo Go app
- and then, the app crashes

**Comment by Gh0st-IT** [comment]
Having the same issue. 
Physical device: OPPO A71 (CPH1801) (Android 7.1.1)

**Comment by delboy1978uk** [comment]
I had the same yesterday with code i had tested and was working perfectly the day before. Working fine just now. Could not reach the development server message. Then later, it just started working again. Is this to do with the status of Expo in https://status.expo.dev/ ? Because I don't understand why this issue is intermittent.

**Comment by Kudo** [comment]
hi there! could you share the crash stacktrace from [adb logcat or other debugging tool](https://docs.expo.dev/workflow/debugging/#my-production-app-is-crashing), e.g. you could run `adb logcat -e 'host.exp.exponent'` from adb.

**Comment by otekdo** [comment]
Hi @Kudo, this is what i have got!
[expo-go-logs.txt](https://github.com/expo/expo/files/10046796/expo-go-logs.txt)

**Comment by Kudo** [comment]
hi there! we've released Expo Go 2.26.5 on Google Play with some fixes. could you help to verify whether the new version helps with the crash?

**Comment by otekdo** [comment]
Hi @Kudo , everything is working as expecting, issue can be closed!
Thanks!

**Comment by Kudo** [comment]
thanks @otekdo
