### ISSUE TITLE
Cannot get location after detach

### ISSUE THREAD

**Issue by ntk860** [expo/expo#2001]
Hello,

     I had to detach the app I am working on to access some native resources (not geolocation), but the app also requires the location of the user. 

The code below does not display anything, not even the error function is firing.

`
navigator.geolocation.getCurrentPosition(
      (position) => {
             console.log(position)
      },    
      (error) => {
             this.getLocation(error)
      }, 
      { enableHighAccuracy: false, timeout: 20000, maximumAge: 0, distanceFilter: 0.000001 },
);
`

Please can someone help me

**Comment by ntk860** [comment]
Thank you for your response 

I tried this https://docs.expo.io/versions/v28.0.0/sdk/location but its not working too.

sdk versions 28.0.0

**Comment by esamelson** [comment]
Hi @ntk860 - I put the code you provided into a snack [here](https://snack.expo.io/B1zu8xaXQ), and it worked fine on my iOS device after I turned on location services. Could you make sure that you have location services on? If so, and the snack above still does not work for you, could you tell us what type of device you're testing on?

**Comment by ntk860** [comment]
@esamelson thank you for your comment. First, I want to let you that I am testing the app on the xcode simulator, but I also have a physical device that I tried and its not working. My computer and the simulator both have the location services on. Did you detach your app before trying ? I can see and run the snack, but if I try I snack that involves location it does not work. I think something is blocking it. I using an iPhone 6

**Comment by ntk860** [comment]
For example [this](https://snack.expo.io/rJ0EuSAMb) snack does not show me the location

**Comment by esamelson** [comment]
@ntk860 are other apps on the same physical device able to get your location? (e.g. Maps app?)

**Comment by ntk860** [comment]
@esamelson Yes. I can use location in other apps, but they are not detached. I will create a test app, detach and try to get location.

**Comment by ntk860** [comment]
@esamelson I just create a brand new project, detached and try to get location, and I am getting the same thing, it is not getting location

**Comment by ntk860** [comment]
@esamelson Yes, Other apps on the physical device can get location

**Comment by esamelson** [comment]
@ntk860 yeah, even in a detached app I'm having no issue running the code in your snack 😕 Could you verify that you have the `NSLocationWhenInUseUsageDescription` key in your project's Info.plist?

**Comment by ntk860** [comment]
NSLocationWhenInUseUsageDescription is set to a custom string

**Comment by ntk860** [comment]
I got it @esamelson thank you for helping me!

**Comment by terribleben** [comment]
@ntk860 glad you figured it out! What was the problem? I'm going to close this since it sounds like you are good to go. :)
