### ISSUE TITLE
 Undefined symbols for architecture arm64: _objc_msgSend$topLayoutGuide

### ISSUE THREAD

**Issue by orome** [expo/expo#20012]
### Summary

Since running `expo upgrade` to 4SDK 7, when I run
```
eas build --profile dev-simulator --platform ios --local --clear-cache
```
on my local machine my builds fail with
```
[RUN_FASTLANE] X  Undefined symbols for architecture arm64
┌─ Symbol: _objc_msgSend$topLayoutGuide
└─ Referenced from: l003 in dev-menu-react-native-safe-area-context(RCTView+DevMenuSafeAreaCompat.o)

[RUN_FASTLANE] 
X  ld: symbol(s) not found for architecture arm64


[RUN_FASTLANE] 
X  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This seems related to #17417 for which having at least Xcode 13.2 was the remedy, but I have Xcode 13.2.1 so I wonder of an even later version (perhaps one that will [not run on my hardware](https://developer.apple.com/support/xcode/)) is required?

Building works fine on the Expo servers using "macos-monterey-12.6-xcode-14.0" which provides:

```
- Xcode 14.0 (14A309)
- Node.js 16.13.2
- Yarn 1.22.17
- pnpm 7.11.0
- npm 8.1.2
- fastlane 2.210.0
- CocoaPods 1.11.3
- Ruby 2.7
- Expo CLI 6.0.0
```

For direct comparison my local machine (a MacBook Pro Retina, 13-inch, Mid 2014) has:

```
- Xcode 13.2.1 (13C100)
- Node.js 18.12.1
- Yarn 1.22.19
- pnpm 7.11.0
- npm 9.1.1
- fastlane 2.210.1
- CocoaPods 1.11.3
- Ruby 3.1.2
- Expo CLI 6.0.8
```

### What platform(s) does this occur on?

iOS

### SDK Version

47

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.7
      Shell: 5.2.9 - /usr/local/bin/bash
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 3.2.3 - /usr/local/bin/yarn
      npm: 9.1.1 - /usr/local/bin/npm
      Watchman: 2022.11.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.10 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

The corresponding successful remote build is c65274a3-5324-4308-b2f4-507a366bdf94

**Comment by lightchaser411** [comment]
I ran into this issue when I updated to Ventura. I fixed it by installing the latest Xcode from the App Store.

**Comment by jaycho1214** [comment]
Using xcode 14.1 version now, but the same error occurs

**Comment by orome** [comment]
@lightchaser411 By "latest" what version do you mean? It may be that this requires a version of Xcode that will not run on Big Sur?

> This seems related to #17417 for which having at least Xcode 13.2 was the remedy, but I have Xcode 13.2.1 so I wonder of an even later version (perhaps one that will [not run on my hardware](https://developer.apple.com/support/xcode/)) is required?

**Comment by Kudo** [comment]
@orome is it feasible for you to upgrade xcode 14?

**Comment by orome** [comment]
> @orome is it feasible for you to upgrade xcode 14?

That's the question I guess. Is that necessary?

My Mac is old:

> For direct comparison my local machine (a MacBook Pro Retina, 13-inch, Mid 2014) ...

**Comment by Kudo** [comment]
@orome alternatively, you could try to add the `EXPO_USE_SOURCE=1` environment variable ([reference](https://expo.fyi/prebuilt-modules)).
to add the environment to eas build: you could [add it in eas.json](https://docs.expo.dev/build-reference/variables/#using-plaintext-environment-variables)
e.g.
```diff
--- a/eas.json
+++ b/eas.json
@@ -5,7 +5,10 @@
   "build": {
     "development": {
       "developmentClient": true,
-      "distribution": "internal"
+      "distribution": "internal",
+      "env": {
+        "EXPO_USE_SOURCE": "1"
+      }
     },
     "preview": {
       "distribution": "internal"
```

please let me know whether it works for you.

**Comment by brentvatne** [comment]
sdk 47 requires xcode 14. ymmv if you are not using it.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/90494/203893039-a0aaa416-0263-4f53-8233-b79fcc6e7b22.png">

**Comment by orome** [comment]
@Kudo Thanks for the suggestion but no, with 
```
EXPO_USE_SOURCE=1
```
I now get
```
┌─ Symbol: _objc_msgSend$storyboardWithName:bundle:
└─ Referenced from: l001 in EXSplashScreen(EXSplashScreenViewNativeProvider.o)
```

Should I hav specified `EXPO_USE_SOURCE` differently; e.g., is an `export` required or should must I specify it as suggested in `eas.json` (I'll try that next).

**Comment by orome** [comment]
> sdk 47 requires xcode 14. ymmv if you are not using it.
> 
> <img alt="image" width="834" src="https://user-images.githubusercontent.com/90494/203893039-a0aaa416-0263-4f53-8233-b79fcc6e7b22.png">

@brentvatne That's for bare. I'm using managed. Does the same remark apply to managed? I wish I'd known.

**Comment by brentvatne** [comment]
when you run `npx expo run:ios` that is equivalent to a "bare" in that context because you are compiling it on your own machine. we need to improve terminology here.

i updated the release notes to clarify 
![image](https://user-images.githubusercontent.com/90494/204106910-638810e1-fde4-4abe-9578-e23c5022cd9a.png)

**Comment by orome** [comment]
I'm running 
```
eas build --local
```
But yes, now the doc makes it clear. Thanks!
