### ISSUE TITLE
Expo Stripe installs older version giving warning

### ISSUE THREAD

**Issue by sunsoftdev** [expo/expo#20028]
### Summary

I have installed the Expo stripe package using the npx expo install @stripe/stripe-react-native it installed stripe/react-native package version .13 even though the current package version for stripe is v .20 

expo has terminated certain modules in config-plugins package on sdk45 this issue has been fixed in stripe official version v.19 but as expo install the older version of stripe this is not resolved. when will expo upgrades to the latest stripe package 

Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.
at node_modules/expo/node_modules/expo-constants/build/Constants.js:145:28 in Object.defineProperty$argument_2.get

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.3.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
      Watchman: 2022.10.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/rj/.rvm/gems/ruby-3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Dolphin 2021.3.1 Dolphin 2021.3.1
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

when we run expo start we will get this warning after install the expo stripe package installing

**Comment by brentvatne** [comment]
to use the latest version you can update to expo sdk 47. each sdk version uses a fixed version of packages in the expo sdk

**Comment by sunsoftdev** [comment]
Thanks, It worked
