### ISSUE TITLE
Localization.getLocales is not a function

### ISSUE THREAD

**Issue by bravadomizzou** [expo/expo#20026]
### Summary

API getLocales doesn't appear to exist even though it is documented
https://docs.expo.dev/versions/latest/sdk/localization/#localizationgetlocales

Getting this error:
`[TypeError: Localization.getLocales is not a function. (In 'Localization.getLocales()', 'Localization.getLocales' is undefined)]`

code:

````
import * as Localization from 'expo-localization'

console.log(Localization.getLocales())
````

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 20, 23, 25, 26, 27, 30, 31, 33
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.2, 27.0.3, 28.0.3, 30.0.2, 33.0.0
        System Images: android-25 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Android TV ARM 64 v8a, android-31 | Android TV Intel x86 Atom, android-31 | Google TV ARM 64 v8a, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play ARM 64 v8a, android-33 | Google Play Intel x86 Atom_64, android-S | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0
      expo: ^46.0.0 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

````
import * as Localization from 'expo-localization'

console.log(Localization.getLocales())

**Comment by fobos531** [comment]
This function is available starting from SDK 47, it is not present in earlier versions.

**Comment by aleqsio** [comment]
Yup, this is available in SDK 47, here's an upgrade guide:
https://blog.expo.dev/expo-sdk-47-a0f6f5c038af

Closing this for now, but if you run into any issues around these new localization APIs (or just have some feedback) I'd love to hear from you!

**Comment by malko** [comment]
doesn't seems to work on SDK 47.0.3 either

**Comment by aleqsio** [comment]
@malko Perhaps you need to run `yarn` again or you have an old version of native dependencies?
Also, make sure you have at least this version of the package installed:
```
"expo-localization": "~14.0.0"
```

**Comment by tamilarasu602** [comment]
I faced the same issue today. This issue seems to happen when the expo app is in debug mode. The issue did not happen when I turned off the [debug mode](https://docs.expo.dev/workflow/debugging/#react-native-debugger).

**Comment by olarcher** [comment]
> I faced the same issue today. This issue seems to happen when the expo app is in debug mode. The issue did not happen when I turned off the [debug mode](https://docs.expo.dev/workflow/debugging/#react-native-debugger).

Same.

**Comment by Overdash** [comment]
@aleqsio surely this should be reopened as it is a bug. Or, it should at least be documented that it only works outside of `debug mode`

**Comment by aleqsio** [comment]
Synchronous functions don't work with `Remote JS Debugging` – this is expected, but I agree that this might not be sufficiently documented.

Perhaps consider switching to hermes (or you might be using hermes already) and chrome inspector instead?
https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools

I want to keep this issue closed as this is not related to `expo-localization`, instead touches on docs for `expo-modules-core`, but we'll continue the topic to update docs.

**Comment by Overdash** [comment]
> Synchronous functions in the new modules don't work with `Remote JS Debugging` – this is expected, but I agree that this might not be sufficiently documented.

Does this mean it wouldn't work inside Jest tests?

**Comment by aleqsio** [comment]
Hmm, wouldn't you like to mock it out anyways? It binds to the native/browser API, so you'd need to run jest on device for this to work
