### ISSUE TITLE
[Ios] app lags/stutters while navigating to a new screen with auto focused text input 

### ISSUE THREAD

**Issue by itsramiel** [expo/expo#20036]
### Summary

Just upgrade my project from expo sdk 46 to expo sdk 47. When I navigate to a screen which is a textInput with autofocus, the screen lags during the transition.

I tried to reproduce it with a very simple expo go example, but the issue seem not to happen there. I then ran `yarn expo prebuild` and then run it from xCode, then the issue is reproducable.

It is very visible with an app with lots of content on the screen. Here is how it looks on my project using expo go vs custom development client:

## Expo Go

https://user-images.githubusercontent.com/80689446/201681939-9d528314-0587-4377-88fc-dd480fdce1a4.mp4

## Custom development client

https://user-images.githubusercontent.com/80689446/201682013-2e459701-e707-4694-b676-e727b9aeb245.mp4

As I mention it can be reproduced with a very simple example. Here is the repo for that: https://github.com/itsramiel/autofocus-repro

## Expo Go 

https://user-images.githubusercontent.com/80689446/201684977-418861b9-37b2-4c84-bda5-fe190fbfd7f2.mp4

## Custom development client

https://user-images.githubusercontent.com/80689446/201685120-2e909ced-268c-4ec0-8c47-edd6ab8ceff6.mp4

### What platform(s) does this occur on?

iOS

### Environment

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Minimal reproducible example

```
// In App.js in a new project

import * as React from "react";
import { View, Text, Button, TextInput } from "react-native";
import { NavigationContainer, NavigationProp } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";

function HomeScreen({ navigation }: { navigation: NavigationProp<any> }) {
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>Home Screen</Text>
      <Button
        title="settings"
        onPress={() => navigation.navigate("Settings")}
      />
    </View>
  );
}
function SettingsScreen() {
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>Settings Screen</Text>
      <TextInput
        autoFocus
        style={{
          width: "100%",
          padding: 10,
          borderWidth: 1,
          borderColor: "black",
        }}
      />
    </View>
  );
}

const Stack = createNativeStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Settings" component={SettingsScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;

```

run `yarn expo prebuild` and try to navigate

**Comment by zain148** [comment]
Hello I'm also seeing the Lag once I used expo-updates and EAS to update my apps with SDK 44

**Comment by brentvatne** [comment]
hey, thanks for the detailed report! i don't think this is is the correct location for this issue, though. you would be better off posting it to the react-navigation or react-native-screens repositories.

**Comment by hirbod** [comment]
I can confirm this issue, it is happening for my OTP screen as well. Brent is right, that this is most likely caused by react-native-screens. Irc, this happened once in the past as well. Did you try the js-stack as well (to distinguish between react-navigation and react-native-screens)?

**Comment by itsramiel** [comment]
I did not try to switch to js-stack, but why does it work well with expo go?

**Comment by itsramiel** [comment]
Agree that it is not an expo issue, here is the link for the new one https://github.com/software-mansion/react-native-screens/issues/1637
