### ISSUE TITLE
Web site says iOS 11+ supported in one place and iOS 13+ in another

### ISSUE THREAD

**Issue by bobOnGitHub** [expo/expo#20039]
### Summary

Started looking at Expo a couple weeks ago and successfully using an old iPhone5s - iOS 12.5.6 (still getting upates from Apple).

Doc said, and still says:
https://docs.expo.dev/get-started/installation/
Android Lollipop (5) and greater
iOS 11 and greater

Now after recent updates it no longer works on iOS 12.5.6 - Expo Go is only available on iOS 13+

I had hoped this was an error but found:

https://docs.expo.dev/introduction/faq/ 
what version of... 
"Expo SDK supports Android 5+ and iOS 13+."

This is a lot of still useful tech going in the bin sooner than it needs to and 3% of devices in use (https://iosref.com/ios-usage) no longer supported on Expo platform.

### Link to the related docs page

see summary: 2 links

**Comment by amandeepmittal** [comment]
I'll fix that. Thanks for catching that @bobOnGitHub 👍

**Comment by bobOnGitHub** [comment]
No worries @amandeepmittal, couple of suggestions:

The doc could do with a "systems requirement" section to keep all that in one obvious place and ideally a table of sdk versions/target os compatability etc. - I found the fix below at https://stackoverflow.com/a/63464020/4779501 / couldn't find the info on the site.

Notes on EOL schedules for target OS versions would be good to have too - suddenly finding things don't work when u weren't expecting it is a bit worrying.

_____________________________


For anyone else who isn't quite ready to fork out for another test device, don't need the latest expo sdk just yet, and want to keep using iOS 11+ you can use: 

`npx create-expo-app <yourAppName> --template blank@46`

(thanks for the clue @brentvatne :+1: )

**Comment by amandeepmittal** [comment]
Thanks for the feedback @bobOnGitHub! I will see how we can improve this page.

We do have a compatibility version doc on API reference: https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a for SDK and the corresponding React Native version.

That particular doc is a part of the path where we want any user to not worry about all the version compatibility or do not expect a user to have an understanding of these things as you expressed when they are starting out with Expo. However, I do see the benefit of mentioning target OS versions as a reference and will seek a right place to put that information.
