### ISSUE TITLE
[SDK 45,46,47] [iOS] Exp Go v2.26.4 - Adding ios.googleServicesFile to Expo config crashes Expo Go

### ISSUE THREAD

**Issue by nakedgun** [expo/expo#20041]
### Summary

If you define a **googleServicesFile** for **ios**, the Expo Go client will crash on launch (iOS only - Android is OK). Bug introduced in Expo Go 2.26.4. Did not happen in the previous version (2.25.3), although from memory I remember a console warning that the file does not exist.

Note: works fine for dev/production builds. Affects Expo SDK 45,46,47. 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/XXX/.rvm/rubies/ruby-2.6.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.0 => 47.0.3
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    Expo Workflow: managed

### Reproducible demo

Add a **googleServicesFile** entry to `ios.googleServicesFile` and place `GoogleServiceInfo.plist` in your project root. 

**Result:** Expo Go will crash on launch.

**app.json**
```
{
  "expo": {
    "ios": {
      "googleServicesFile": "./GoogleServiceInfo.plist"
    }
  }
}
```

GoogleServiceInfo.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CLIENT_ID</key>
	<string>XXX.apps.googleusercontent.com</string>
	<key>REVERSED_CLIENT_ID</key>
	<string>XXX</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>XXX</string>
</dict>
</plist>
```

**Comment by brentvatne** [comment]
thanks for the report! you can work around this for now using development builds: https://docs.expo.dev/development/introduction/

**Comment by Kudo** [comment]
hi there! the GoogleServiceInfo.plist is invalid, e.g. missing `GOOGLE_APP_ID`. it's the firebase sdk behavior to crash if you pass an invalid GoogleServiceInfo.plist. if you are testing the app on an ios simulator, you could open the `Console.app` on macos to get the expo go log. it would show something like this:

```
*** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.'
```
