### ISSUE TITLE
Build failed: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### ISSUE THREAD

**Issue by aquib20034** [expo/expo#20042]
### Summary

info Done copying assets
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
581 actionable tasks: 581 executed
[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] Execution failed for task ':expo-facebook:compileReleaseKotlin'.
[stderr] > Compilation error. See log for more details
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] 2: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] java.lang.StackOverflowError (no error message)
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 5m 43s
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### What platform(s) does this occur on?

Android

### SDK Version

~47.0.3

### Environment

npx expo-env-info

### Minimal reproducible example

https://expo.dev/accounts/babar_11/projects/highway-app/builds/9af07635-0731-4fd9-95fb-2a9ee6958e23

**Comment by brentvatne** [comment]
you appear to be using expo-facebook - this library was deprecated in sdk 45 and is no longer supported as of sdk 46. refer to the sdk 45 docs page for more info: https://docs.expo.dev/versions/v45.0.0/sdk/facebook/
