### ISSUE TITLE
expo-auth-session updateId must be a valid GUID

### ISSUE THREAD

**Issue by suleymanbariseser** [expo/expo#20058]
### Summary

Hi, I am having an issue with expo-auth-session which does not let me to login with social providers. It is something related to eas-cli because I am not encountering any issue locally and before eas, I was using expo-cli to update and it had no issue. It only happens on android. If you check the images below, there is missing slash for android and I think it causes **updateID must be a valid GUID**.

![WhatsApp Image 2022-11-15 at 3 15 44 PM](https://user-images.githubusercontent.com/50797736/201930770-6bec5085-6fce-496b-b3f9-c4cb72890c1d.jpeg)
![IMG_8486](https://user-images.githubusercontent.com/50797736/201930800-54b10379-622f-45e6-9e4a-ab5516a350d9.PNG)

![WhatsApp Image 2022-11-15 at 4 09 48 PM](https://user-images.githubusercontent.com/50797736/201931057-2621fc0b-9b3f-4db4-abea-f84a69509990.jpeg)

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 9.1.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ^46.0.14 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    Expo Workflow: managed

## useGoogleLogin.ts
```ts
const useGoogleLogin = GoogleLogin.useAuthRequest({
    responseType: ResponseType.IdToken,
    clientId: '...',
    iosClientId: '...',
    webClientId: '...',
    expoClientId: '...',
    scopes: [
      'openid',
      'https://www.googleapis.com/auth/userinfo.profile',
      'https://www.googleapis.com/auth/userinfo.email',
    ],
  }
```

## package.json
```json
{
  ...
  "dependencies": {
    "expo": "^46.0.14",
    "expo-apple-authentication": "~4.3.0",
    "expo-application": "^5.0.1",
    "expo-auth-session": "3.7.1",
    "expo-constants": "~13.2.4",
    "expo-dev-client": "~1.3.1",
    "expo-device": "~4.3.0",
    "expo-facebook": "^12.2.0",
    "expo-font": "~10.2.0",
    "expo-linking": "~3.2.2",
    "expo-local-authentication": "~12.3.0",
    "expo-random": "^12.3.0",
    "expo-screen-orientation": "~4.3.0",
    "expo-secure-store": "~11.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-system-ui": "~1.3.0",
    "expo-updates": "~0.14.7",
    "expo-web-browser": "~11.0.0",
  },
  ...
}
```

## eas.json
```json
{
  "cli": {
    "version": ">= 2.1.0"
  },
  "build": {
    "development": {
      "channel": "development",
      "developmentClient": true,
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "ios": {
        "simulator": true
      }
    },
    "preview": {
      "channel": "staging",
      "distribution": "internal"
    },
    "production": {
      "channel": "production",
      "android": {
        "buildType": "app-bundle"
      }
    }
  },
  "submit": {
    "production": {}
  }
}
```

**Comment by Kudo** [comment]
hi there! did you test it on expo go app or the app generated from eas build? i'm asking because the `Uncaught Error` you shared looks like in expo go.

**Comment by suleymanbariseser** [comment]
Hi @Kudo, it is expo go app which is generated with **eas update** command

**Comment by Kudo** [comment]
@suleymanbariseser that should be related to #19258. please upgrade `expo-linking@~3.2.3` and it should work for you. thanks!

**Comment by suleymanbariseser** [comment]
Thanks a lot, it was the solution
