### ISSUE TITLE
ReferenceError: Can't find variable: Buffer

### ISSUE THREAD

**Issue by Livijn** [expo/expo#20054]
### Summary

I am upgrading my app from SDK 44 to SDK 45 and is forced to use the `expo-dev-client` due to deprecations of some libs. Building the app works with `eas` but when I run the app on my phone, I get this error:

> ReferenceError: Can't find variable: Buffer
> at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
> at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
> at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
> at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
> at node_modules/metro-runtime/src/polyfills/require.js:203:40 in guardedLoadModule
> at http://xx:8081/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:373214:3 in global code
> 
> Invariant Violation: "main" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
> at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
> at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
> at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
> at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo-dev-client@2.0.0
expo-updates@0.15.5

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/opt/node@16/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Patch 2 Chipmunk 2021.2.1 Patch 2
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 2.7.0
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Reproducible demo

Cannot provide due to limited knowledge of the actual error.

**Comment by Livijn** [comment]
Just upgraded to SDK 46 and I am receiving the same error.

**Comment by amandeepmittal** [comment]
Hey @Livijn,

Please check the suggestions mentioned here: https://docs.expo.dev/troubleshooting/application-has-not-been-registered/

**Comment by Livijn** [comment]
@amandeepmittal I'm pretty sure the `Invariant Violation: "main" has not been registered.` is caused by the first exception: `ReferenceError: Can't find variable: Buffer`.

**Comment by sebastienlabine** [comment]
@Livijn maybe try to add a buffer polyfill library

**Comment by hirbod** [comment]
I had the same issue 3 minutes ago and I had to downgrade `pusher-js` from 7.5.0 to 7.4.0
Now I am suspecting that was just a sideeffect. I will try again to update to 7.5.0

**Comment by Livijn** [comment]
@hirbod Yes I was using `pusher-js@7.5.0`! Turns out downgrading to `7.4.0` worked. Thanks a ton :)

**Comment by fansilva1991** [comment]
> I had the same issue 3 minutes ago and I had to downgrade `pusher-js` from 7.5.0 to 7.4.0 Now I am suspecting that was just a sideeffect. I will try again to update to 7.5.0
> 
> Edit: I once again upgraded pusher-js from 7.4.0 to 7.5.0 and it broke it again: `ReferenceError: Property 'Buffer' doesn't exist, js engine: hermes`
> 
> So downgrading back to 7.4.0 fixed the issue for me. Are you guys also using PusherJS by any chance? It's 100% reproducible for me only with this library, nothing else crashes for me.
> 
> I haven't tried it, but looks promising: https://github.com/craftzdog/react-native-buffer

This also solved my issue! Thank you very much.

**Comment by deivyrene** [comment]
I had a similar error with `pusher-js 7.0.0` when upgrading to `react-native 0.70.9`, I upgraded `pusher-js to 8.0.2` and was able to fix it.

**Comment by AamenaSaiyed** [comment]
I am having  
"react-native": "0.71.7", 
"pusher-js": "^7.0.3",
![Screenshot 2023-05-01 at 4 52 31 PM](https://user-images.githubusercontent.com/90598756/235445284-c9c908a9-e497-45f9-b943-57ec84ccd170.png)


facing same crash please help me to get over it.

**Comment by menttys** [comment]
> I am having "react-native": "0.71.7", "pusher-js": "^7.0.3", ![Screenshot 2023-05-01 at 4 52 31 PM](https://user-images.githubusercontent.com/90598756/235445284-c9c908a9-e497-45f9-b943-57ec84ccd170.png)
> 
> facing same crash please help me to get over it.

Hi @AamenaSaiyed have you found a fix for the crash?

Thanks! 🙏🏽

**Comment by Andrewgraemebrooks** [comment]
I had the same issue. Upgrading pusher-js from ^7.0.2 to *8.0 worked for me
