### ISSUE TITLE
Unrecognized font family 'Lato_700Bold'

### ISSUE THREAD

**Issue by MarzellT** [expo/expo#20061]
### Summary

Running the expo app on the iOS Simulator shows the error "Unrecognized font family 'Lato_700Bold'" as can be seen in the attached image.    
![image](https://user-images.githubusercontent.com/49523244/201955141-3e865f9a-e24e-45df-a5a5-72be872d87bf.png)
Running it using the Android Emulator works without issues.   
Also running it on a real device works without issues.   
This issue is potentially related to #12552. Running `expo install` didn't fix the issue for me though.   

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.0 => 0.3.22 
      @expo/webpack-config: ~0.16.2 => 0.16.27 
      expo: ^45.0.8 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
      react-navigation: ^4.4.4 => 4.4.4 
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/lU2Qcuhtg

**Comment by Kudo** [comment]
hi there! i tried the snack with expo go 2.26.4 and it works for me. could you double check for the problem?

**Comment by MarzellT** [comment]
Hey, thanks for the reply. You are right, in the snack the issue doesn't appear. I'll need to look into that again as that issue still exists in my project. I will post an updated snack as soon as I have the time.

**Comment by Sudarshan101** [comment]
follow the below link for solution
https://www.devhubspot.net/post/detail/react-native-unrecognised-font-family-error-solution
