### ISSUE TITLE
The project does not work properly after the patch version is updated. 

### ISSUE THREAD

**Issue by AsteriskZuo** [expo/expo#20065]
### Summary

commit hash: 1327fe2bc92f71f7213cd5ddd40fa4f8a5336bc6

Due to this submission, the project cannot be updated and used normally.
The version in the project is:
"Expo", "~ 46.0.9",
"Expo - asset" : "~ 8.6.1",
In the 'lock' file, their actual versions are '46.0.17' and '8.6.2', and their dependencies' expo-file-system 'are' 14.1.0 'and' 15.1.1 'respectively. Dependency incompatibility occurs, causing ios compilation failure.

The reason why the problem is put here is that when you updated 'expo' and 'expo-asset' on October 6th, 'expo' was changed from '46' to '47'.

I don't have any good suggestions for this problem, but I hope I can get a good solution from you instead of just upgrading the version.

Project is ` react-navigation `, commit hash:  1846de6bd8247992286d39ee76e65f27debb1754
[link](https://github.com/react-navigation/react-navigation/tree/1846de6bd8247992286d39ee76e65f27debb1754)

### What platform(s) does this occur on?

iOS

### Environment

`npx react-native info`
```sh
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 78.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 3.2.2 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/Cellar/node/18.11.0/libexec/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/opt/cocoapods/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Minimal reproducible example

none

**Comment by Kudo** [comment]
hi there! each expo module version has its supported expo sdk. please use `npx expo install expo-file-system` to install the module. it will install the supported version for you, e.g. `expo-file-system@~14.1.0` for expo sdk 46. in theory, when you run `npx expo start`, if there are incompatible dependencies, the command should also show a warning for you.

**Comment by AsteriskZuo** [comment]
Thx.
