### ISSUE TITLE
[docs] [expo-image-picker] On Android option "allowsMultipleSelection" seems not supported

### ISSUE THREAD

**Issue by nanokoko89** [expo/expo#20068]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by nanokoko89** [comment]
any have problem with allowsMultipleSelection on android?
I could not choose multiple images at a time, just have to select all then unselect other to get images I want?

**Comment by sunviwo** [comment]
It is not working for me either. On Android.

**Comment by tech-sunvi** [comment]
I solved the problem. Certainly you are following the documentation, which is misleading. For anyone experiencing the same issue, and copied code from documentation, if you are selecting multiple files, do not do this
`
if (!result.canceled) {
      setImage(result.assets[0].uri);
    }
`
Do this instead:
`if (!result.canceled) {
      setImage(result.assets);
    }`
Afterwards, you will loop over the `image` state variable and process each element on its own.

**Comment by sunviwo** [comment]
I solved the problem. Certainly you are following the documentation, which is misleading. For anyone experiencing the same issue, and copied code from documentation, if you are selecting multiple files, do not do this
`
if (!result.canceled) {
      setImage(result.assets[0].uri);
    }
`
Do this instead:
`if (!result.canceled) {
      setImage(result.assets);
    }`
Afterwards, you will loop over the `image` state variable and process each element on its own.

**Comment by Manikanta-GEP** [comment]
allowsMultipleSelection not working in my case
