### ISSUE TITLE
Notification Switch

### ISSUE THREAD

**Issue by RishabBhandari** [expo/expo#2006]
I'm really new to coding and have just picked up a project to work on over the summer. I'm building an alarm clock like application that will allow users to turn off and on notifications on their request. Over the last week, I have been trying to implement this functionality with the .remove() function using if statements however, I have been unsuccessful and gotten quite frustrated lol. If anyone could please help me out, I would greatly appreciate it. I have provided my code below. The current version's notification toggle doesn't work. 

---
import React, {Component} from 'react';
import {Text, TextInput, Switch, View, Keyboard} from 'react-native';
import {StyleSheet, Constants, Notifications, Permissions} from 'expo';

export default class Timer extends React.Component {

  render() {
      return (

          <View style={{flex: 1, flexDirection: 'row', justifyContent: 'center'}}>
              <View>
              {this.renderElement()}
              </View>
              <Switch
                onValueChange={this._handleToggleSwitch}
                value={this.state.switchValue}
              />
          </View>
      );
  }

  state = {
    switchValue: false,
  };

  _handleToggleSwitch = () =>
    this.setState(state => ({
      switchValue: !state.switchValue,
    }));

    onSubmit(e) {

        Keyboard.dismiss();

        const localNotification = {
            title: 'done',
            body: 'done!',
            sound: 'true'
        };

        const schedulingOptions = {
            time: (new Date()).getTime() + Number(e.nativeEvent.text)+1000,
            repeat: 'minute'
        }

        // Notifications show only when app is not active.
        // (ie. another app being used or device's screen is locked)
        Notifications.scheduleLocalNotificationAsync(
            localNotification, schedulingOptions
        );
      }

    handleNotification() {

        console.warn('Notification Working');
      }

    async componentDidMount() {
        // We need to ask for Notification permissions for ios devices
        let result = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        if(this.state.switchValue){

        if (Constants.isDevice && result.status === 'granted') {
            console.log('Notification permissions granted.')
        }
      }
        // If we want to do something with the notification when the app
        // is active, we need to listen to notification events and
        // handle them in a callback
        Notifications.addListener(this.handleNotification);
      }
        // Notifications.remove(); <- How do I implement this? 

    renderElement(){
       if(this.state.switchValue){
          return   <TextInput onSubmitEditing={this.onSubmit} placeholder={'time in ms'}/>;
    }
  }

}

**Comment by esamelson** [comment]
Hi @RishabBhandari! It would be really helpful if you could follow the issue template and post the expected behavior of your code, its actual behavior, and ideally include a snack that reproduces the issue (see https://stackoverflow.com/help/mcve for how to create a really useful example). It's difficult to read and parse the code as you've posted it, and I'm not quite sure what's going on here.
