### ISSUE TITLE
Project fails to build when using expo-secure-store SDK

### ISSUE THREAD

**Issue by seanbarker096** [expo/expo#20089]
### Summary

I cannot add the `expo-secure-store` plugin to my expo development build without it failing. This happens for a very simple straight out of the box development build with `expo-secure-store` as the only plugin

### What platform(s) does this occur on?

Android, iOS, Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    npmPackages:
      expo: ~47.0.6 => 47.0.6 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.4.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

Snack https://snack.expo.dev/@seanbarker6/expo-secure-store

1. Create new expo project
```
npx create-expo-app my-app

cd my-app

npx expo install expo-dev-client
```

2. Set up EAS build. My eas build was for android
```
eas build:configure
```
3. Install expo-secure-store and add to config
```
npx expo install expo-secure-store
```
**app.json**
```
{
  "expo": {
...
    "plugins": [
      "expo-secure-store"
    ]
  }
}
```

4. Run `npx expo prebuild` or `eas build --profile development --platform android`. This results in the following error
```
CommandError: Package "expo-secure-store" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module
```

**Comment by mirzalikic** [comment]
there is no expo-secure-store plugin, it works without a plugin.

**Comment by melnikovkolya** [comment]
@mirzalikic 

I tested your suggestion and it works.

For some reason `expo-doctor` adds that plugin to the `app.json` file. 

At least on expo v50
