### ISSUE TITLE
[SDK 47] EAS Release build fails on iOS ```You must rebuild it with bitcode enabled```...

### ISSUE THREAD

**Issue by homosape** [expo/expo#20087]
### Build/Submit details page URL

https://expo.dev/accounts/valasolutions/projects/vala-solutions/builds/4ea24548-ab2a-4e97-a4c7-6197db6c98a9

### Summary

Hi, my EAS Release build on iOS fails. Debug build works. It has something to do with Expo Barcode Scanner.
Please note that I do have bitcode disabled in my project.

<img width="748" alt="Screenshot 2022-11-16 at 16 50 58" src="https://user-images.githubusercontent.com/70649220/202185228-510cd7c2-c30b-4042-a600-19b16f7c1ca9.png">

### Managed or bare?

Bare

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-28 | ARM 64 v8a, android-28 | Google APIs Intel x86 Atom, android-30 | ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.6 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.7.0
      expo-cli: 6.0.8
    Expo Workflow: bare
```

```
Expected package @expo/config-plugins@^5.0.2
Found invalid:
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
```
**Note:  @expo/config-plugins@4.1.5 is coming from react-native-firebase/... 14.11.1**

### Error output

```
❌  ld: '/Users/expo/Library/Developer/Xcode/DerivedData/ValaHome-gauccguzfbymkgccdhpsitpwyure/Build/Intermediates.noindex/ArchiveIntermediates/ValaHomeStaging/BuildProductsPath/Release-
iphoneos/XCFrameworkIntermediates/EXBarCodeScanner/EXBarCodeScanner.framework/EXBarCodeScanner(EXBarCodeSca
nner.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an
 updated library from the vendor, or disable bitcode for this target. file '/Users/expo/Library/Developer/Xcode/DerivedData/ValaHome-
gauccguzfbymkgccdhpsitpwyure/Build/Intermediates.noindex/ArchiveIntermediates/ValaHomeStaging/BuildProductsPath/Rel
ease-iphoneos/XCFrameworkIntermediates/EXBarCodeScanner/EXBarCodeScanner.framework/EXBarCodeScanner' for
 architecture arm64
```

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by Kudo** [comment]
hi there! could you try to use [xcode 14 image](https://docs.expo.dev/build-reference/infrastructure/#ios-server-images) to build the project?

**Comment by apedroferreira** [comment]
Any solution for people with a managed project?

**Comment by homosape** [comment]
@Kudo  works well!

**Comment by Kudo** [comment]
@apedroferreira if you are building your project locally, the recommended solution is upgrading xcode 14. hopefully it's feasible for you.

**Comment by alessandrocapra** [comment]
@Kudo I am using EAS build, so no build is being created locally on my machine. I get the same error though, am I missing something here?

**Comment by apedroferreira** [comment]
> @Kudo I am using EAS build, so no build is being created locally on my machine. I get the same error though, am I missing something here?

This fixed the issue for me, I added this property to the `ios` configuration in the `eas.json` file:
```"image": "macos-monterey-12.6-xcode-14.1",```
There's a list of images here https://docs.expo.dev/build-reference/infrastructure/.
I guess that using any image with XCode 14 fixes it.

**Comment by alessandrocapra** [comment]
@apedroferreira thanks mate! It works perfectly now

**Comment by IliaChi** [comment]
@alessandrocapra Should I add ios under submit-production ?

**Comment by alessandrocapra** [comment]
@IliaChi an example from my eas.json file:

```
...
"preview-store": {
      "autoIncrement": true,
      "channel": "preview",
      "distribution": "store",
      "ios": {
        "image": "macos-monterey-12.6-xcode-14.1",
      }
    },
```
