### ISSUE TITLE
Wrong value type for "ios.config.usesNonExemptEncryption" parameter

### ISSUE THREAD

**Issue by pascalprat** [expo/expo#2008]
The "Configuration with app.json" documentation page states that "ios.config.usesNonExemptEncryption" is of type "STRING", but this parameter is a boolean.

**Comment by esamelson** [comment]
Hi @pascalprat - thanks for the catch! I've fixed this internally and it will go out with our next docs deploy.

FWIW, we love accepting PRs for our docs here https://github.com/expo/expo-docs for next time you find a typo :)
