### ISSUE TITLE
[expo-image-picker] [Android] Unable to open camera, "user rejected permissions" despite having permissions

### ISSUE THREAD

**Issue by jsindos** [expo/expo#20096]
### Summary

I am running the minimal reproducible example below on Android SDK 33, but am getting the following error:

```
Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.
→ Caused by: User rejected permissions
```

`status` is returned as
```
{"canAskAgain": true, "expires": "never", "granted": true, "status": "granted"}
```

I've checked Settings -> Permissions in Android settings and my app has permission to use the camera.

I am running a bare project and have upgraded to Android SDK 33, so maybe that has something to do with it.

I was wondering if anyone else has run into a similar issue.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2022.02.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.3 
      expo: ~46.0.2 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: bare

### Minimal reproducible example

`npm i expo-image-picker@~13.3.1`

```
import { Button } from 'react-native'
import * as ImagePicker from 'expo-image-picker'

export default () => {
  const [status, requestPermission] = ImagePicker.useCameraPermissions()

  const launchCamera = async () => {
    if (status && !status.granted) {
      await requestPermission()
    }
    
    const result = await ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [3, 2],
      quality: 0.2
    })
  }

  return <Button title='Open camera' onPress={launchCamera} />
}
```

**Comment by vitormotag** [comment]
Hello, I'm experiencing the same problem. Managed to solve?

**Comment by senorscan** [comment]
Same thing happening for me. Seems to only happen if the user has selected permission of 'use once'.

**Comment by brentvatne** [comment]
we don't officially support compileSdkVersion 33 yet, but we'll be working on it soon. if you'd like to submit a PR for that it would be welcome.

**Comment by DanStevensonDev** [comment]
I'm having the same issue 

> Same thing happening for me. Seems to only happen if the user has selected permission of 'use once'.
@senorscan Does this mean it's working for you if allow 'while using the app'?

**Comment by trickeyd** [comment]
I am having the same issue with version 11.

My targetSdkVersion and compileSdkVersion are 31 though, not 33.

**Comment by dyanezGS** [comment]
Anyone have a solution for this issue? A production application is failing due to this problem and I don't know how ti fix it.

**Comment by m1st1ck** [comment]
We are having the same issue with `"expo": "^47.0.0",`, `"expo-image-picker": "~14.0.2",` and `targetSdkVersion: 33,`, but only on some android phone - working fine with pixel 3a, but not working on samsung galaxy s21+ 5g.

**Comment by dyanezGS** [comment]
> We are having the same issue with `"expo": "^47.0.0",`, `"expo-image-picker": "~14.0.2",` and `targetSdkVersion: 33,`, but only on some android phone - working fine with pixel 3a, but not working on samsung galaxy s21+ 5g.

I am using expo 45, I had to downgrade the expo-image-picker version to 12.0.1 to make it works

**Comment by enagorny** [comment]
Found the issue 
https://github.com/expo/expo/blob/main/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt#L193

when compileSdkVersion is set to 33
`permissionsResponse[Manifest.permission.WRITE_EXTERNAL_STORAGE]?.status` is always resolves as BLOCKED

So it this error raised due to WRITE_EXTERNAL_STORAGE permission instead of CAMERA.

So I've patched `ImagePickerModule.kt`
```
--- a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
+++ b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
@@ -141,9 +141,7 @@ class ImagePickerModule(
     }
 
     val permissionsResponseHandler = PermissionsResponseListener { permissionsResponse: Map<String, PermissionsResponse> ->
-      if (permissionsResponse[Manifest.permission.WRITE_EXTERNAL_STORAGE]?.status == PermissionsStatus.GRANTED &&
-        permissionsResponse[Manifest.permission.CAMERA]?.status == PermissionsStatus.GRANTED
-      ) {
+      if (permissionsResponse[Manifest.permission.CAMERA]?.status == PermissionsStatus.GRANTED) {
         launchCameraWithPermissionsGranted(promise, cameraIntent, pickerOptions)
       } else {
         promise.reject(SecurityException("User rejected permissions"))

```

For my case I have our own permissions check using 'react-native-permissions' package and we are on bare project

```
const requestWritePermission = async () => {
  if (Platform.OS === 'android' && Platform.constants.Version >= 33) {
    // always return true for Android 13+ as WRITE_EXTERNAL_STORAGE is always blocked there https://stackoverflow.com/questions/73620790/android-13-how-to-request-write-external-storage
    return true;
  }

  const res = await request(
    Platform.select({android: PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE, ios: PERMISSIONS.IOS.PHOTO_LIBRARY_ADD_ONLY}),
  );
  return res === RESULTS.GRANTED;
};
```

**Comment by chillo-tech** [comment]
Hello, 
I'm facing the same problem. 
Anyone managed to solve?

**Comment by dnetoTF** [comment]
The patch @enagorny provided isn't accurate for version 14.0.2. I update the `ensureCameraPermissionsAreGranted` function as follows to get the camera working with expo 47 and build properties targeting Android api 33

```kt
  private suspend fun ensureCameraPermissionsAreGranted(): Unit = suspendCancellableCoroutine { continuation ->
    val permissions = appContext.permissions ?: throw ModuleNotFoundException("Permissions")

    permissions.askForPermissions(
      { permissionsResponse ->
        if (
          permissionsResponse[Manifest.permission.CAMERA]?.status == PermissionsStatus.GRANTED
        ) {
          continuation.resume(Unit)
        } else {
          continuation.resumeWithException(UserRejectedPermissionsException())
        }
      },
      Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.CAMERA
    )
  }
```

**Comment by enagorny** [comment]
Should be fixed in https://github.com/expo/expo/pull/20908

**Comment by federicogomezlara** [comment]
@dnetoTF's solution seems to have worked, you have to create a new build for the patch to work though, at least I had to create a new dev client, hope it works in production

**Comment by Akashanalytical** [comment]
can anyone explain the clear solution?

**Comment by dyanezGS** [comment]
> Should be fixed in #20908

Do we need to update Expo to sdk 47? Because I am using sdk 46 and it is not working yet.

**Comment by dyanezGS** [comment]
> Should be fixed in #20908

Neither working in expo 47, Is there any solution for this issue?

**Comment by kelkmere** [comment]
I have a very peculiar problem.

I have manually changed the ImagePickerModule.kt file as instructed above but Expo just ignores every changes I made.

I could even delete the entire /node_modules/expo-image-picker/android folder and I would still have no problem rebuilding the app with npm run start.

<img width="821" alt="Screenshot 2023-04-13 at 7 07 57 PM" src="https://user-images.githubusercontent.com/29800709/231741067-4b5b71f4-210a-4d33-b009-830eb7ce1862.png">

**Comment by enagorny** [comment]
Easiest solution is upgrading to 48

**Comment by cjhines** [comment]
This still doesn't work on expo 48 and `expo-image-picker@14.1.1`

**Comment by marcelino-borges** [comment]
I'm starting to question if expo is ready for a production ready development... whetger I took the right decision to use react native instead of flutter... =/

**Comment by emilhdiaz** [comment]
@enagorny This was closed because https://github.com/expo/expo/pull/20908 was released in Expo SDK 48. Is there any other official recommendation for the rest of us not yet ready to upgrade to SDK 48?

**Comment by enagorny** [comment]
@emilhdiaz you can patch the file 
```node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt```
as mentioned in above be me https://github.com/expo/expo/issues/20096#issuecomment-1367998558 
or by @dnetoTF https://github.com/expo/expo/issues/20096#issuecomment-1397540174
using patch-package https://www.npmjs.com/package/patch-package

**Comment by emilhdiaz** [comment]
> @emilhdiaz you can patch the file `node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt` as mentioned in above be me [#20096 (comment)](https://github.com/expo/expo/issues/20096#issuecomment-1367998558) or by @dnetoTF [#20096 (comment)](https://github.com/expo/expo/issues/20096#issuecomment-1397540174) using patch-package https://www.npmjs.com/package/patch-package

@enagorny Thanks for re-sharing. This works on development & release builds, but what about Expo Go? 

I have follow up process/product question... Aren't SDK 46 and 47 still officially supported versions of the product? Is it not the expectation of the Expo team to patch supported version?

**Comment by enagorny** [comment]
@emilhdiaz This wouldn't work with Expo Go as this patch modifies native kotlin file. This file used during native build. When you are using Expo Go all modifications to native files are ignore as native build comes from expo team and there is no way to modify it.

Best way to fix it - upgrade to the latest Expo.

**Comment by emilhdiaz** [comment]
Thanks for the feedback @enagorny 👍🏻

**Comment by sanny-naked** [comment]
@enagorny your patch worked. Thank you :)

**Comment by legreco** [comment]
@enagorny @dnetoTF  It's works. Thanks

**Comment by zorzpapaduby** [comment]
I still have the same problem with expo 48 and android 13

> This still doesn't work on expo 48 and `expo-image-picker@14.1.1`

Did you manage to find a solution?
