### ISSUE TITLE
Logic for checking iOS audio modes is incorrect

### ISSUE THREAD

**Issue by cobarx** [expo/expo#2009]
I was flipping through the audio mode code (which is fantastic) for inspiration for handling audio in one of my modules and came across what appears to be an error.

From https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Core/Api/AV/EXAV.m:
```
  if (!playsInSilentMode && interruptionMode == EXAudioInterruptionModeDuckOthers) {
    return RCTErrorWithMessage(@"Impossible audio mode: playsInSilentMode and duckOthers cannot both be set on iOS.");
  } else if (!playsInSilentMode && allowsRecording) {
    return RCTErrorWithMessage(@"Impossible audio mode: playsInSilentMode and allowsRecording cannot both be set on iOS.");
  } else {
```

I believe this should be:
```
if (playsInSilentMode && interruptionMode == EXAudioInterruptionModeDuckOthers) {
  return RCTErrorWithMessage(@"Impossible audio mode: playsInSilentMode and duckOthers cannot both be set on iOS.");
```

It also may be that the comment is incorrect & needs to be updated.

I attempted to test this and see, however it appears AVPlayer will accept any category & option combination.

**Comment by esamelson** [comment]
Hi @cobarx - thanks for the report. Pinging @sjchmiela who should be able to confirm/deny this.

**Comment by sjchmiela** [comment]
Hey @cobarx, you're right! Submitted an upstream PR fixing error messages, thanks for the issue!
