### ISSUE TITLE
[expo-config-plugins] Discrepancy between `IOSConfig.XcodeUtils.addResourceFileToGroup` and plain `cordova-node-xcode`'s `addResourceFile`

### ISSUE THREAD

**Issue by xseignard** [expo/expo#20091]
### Summary

Hello 👋,
I'm trying to understand the differences between using: [`IOSConfig.XcodeUtils.addResourceFileToGroup`](https://github.com/expo/expo/blob/main/packages/@expo/config-plugins/src/ios/utils/Xcodeproj.ts#L96) and plain `cordova-node-xcode`'s `addResourceFile`

When using `IOSConfig.XcodeUtils.addResourceFileToGroup` the `UUID` created for the file ref in the Resources build phase don't point to any actual file 🤔 
So when the file need to be loaded within your running app, it crashes.

When using plain `cordova-node-xcode`'s `addResourceFile` it seems ok to me.

### What platform(s) does this occur on?

Not Applicable

### Environment

I don't think it is relevant, but here it is

```
expo-xcodeutils [main●] % npx expo-env-info    

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.09.05.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/xavier.seignard/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: managed
```

### Minimal reproducible example

You can find a repro repo here: https://github.com/xseignard/expo-xcodeutils/

The following PR highlights the discrepancy https://github.com/xseignard/expo-xcodeutils/pull/1/files

**Comment by EvanBacon** [comment]
[IOSConfig.XcodeUtils.addResourceFileToGroup](https://github.com/expo/expo/blob/main/packages/@expo/config-plugins/src/ios/utils/Xcodeproj.ts#L96) is essentially internal, and shouldn't really be used. Many of the cordova xcode functions are simple workarounds pending a rewrite.

Looks like `addResourceFileToGroup` does a lot of different things based on the input parameters. When we rewrite, we won't express adding a resource file like this.
