### ISSUE TITLE
Error starting with Expo 17.0.0 - works fine in remote JS debugging mode

### ISSUE THREAD

**Issue by PavelJ** [expo/expo#201]
Hi,
After upgrading from 15.0.0 to 17.0.0, application does not start, throwing the following error: https://ibb.co/cxGq8F

Strange is, that when I enable remote JS debugging, it works as expected. No error is seen in XDE log (except some deprecated warnings). I was unable to resolve the problem and it looks like it's something hidden in Expo or react-native itself.

Testing environment:
 - Windows 7 64bit
 - Node 5.12.0
 - Genymotion - API 23, 24
 - Android simulator - API 23, 24
 - Expo 17.0.0

I have created a repo with which I am able to reproduce the problem: https://github.com/PavelJ/error-test

**Comment by terribleben** [comment]
Hi, I tried running your example project but there is an issue with one of its other non-react-native dependencies:
![image](https://cloud.githubusercontent.com/assets/1316332/26379903/6510c56c-3fd0-11e7-9a22-5ea7076ff968.png)

Since we are seeing different behavior from each other, is it possible you have outdated dependencies in your `node_modules` directory? You could try deleting that and reinstalling.

The only other thing that occurs to me is that your version of node is old-ish. I am running node 7.7.1 currently.

**Comment by PavelJ** [comment]
Hi, please read the readme on the project, there is an installation description, where you have to delete one file and update another one. It is caused by officical issues in those libraries, I am waiting for them to be resolved, in the meantime there is a few steps to avoid them.

**Comment by PavelJ** [comment]
I have updated the project - cutting unsused dependencies, now it is much more bare bone than before and deleting of .babelrc (which was needed in the first version) is not necessary anymore. Error still persists.

**Comment by PavelJ** [comment]
So I have found a problem - looks like those imports are still needed in app.js:

```
import {
  NavigationProvider,
  StackNavigation,
} from '@expo/ex-navigation';
```

Even if they're not used in the file. I have deleted these imports during update. With those, it works as expected. I don't know if this expected behaviour, I would have expected to not be forced to use those imports.

**Comment by terribleben** [comment]
@PavelJ that's interesting -- this is not expected to be a requirement. Is there any chance you have some weird dependency on those buried in your other imports somewhere? cc @skevy

**Comment by PavelJ** [comment]
No, I don't use NavigationProvider nor StackNavigation anywhere, I am using react-navigation package in different parts of the app but not these imports. I have retested it again and yes, if I'll clone my test repo here https://github.com/PavelJ/error-test and add those imports in app.js, it's working, without them, it fails.

**Comment by brentvatne** [comment]
@PavelJ - it seems to work on iOS but on Android I got that error as well. Further investigation pointed me to this: `import 'core-js/es6/symbol';` - if you remove this line, it works. I think the polyfill for symbol doesn't work with react-native. This is more of an upstream react-native issue than an issue with react-native itself. Additionally, we are in the process of updating JavaScript Core on Android, which will include Symbol natively and resolve this issue. Until then, maybe switch to a different promise polyfill so Android works as expected. You can track progress on our JSC upgrade at https://github.com/SoftwareMansion/jsc-android-buildscripts

**Comment by omarnaeem0** [comment]
@brentvatne  facing same error on android with expo version 29.0.0.
Anyone facing same issue ?
