### ISSUE TITLE
Image.getSize throwing exceptions in tests when using jest-expo

### ISSUE THREAD

**Issue by udeyrishi** [expo/expo#20101]
### Summary

Using the `Image.getSize` method in a test when using `jest-expo` throws the following exception:

```
 ● Foo › something

    TypeError: Cannot read property 'then' of undefined

       6 | const MyComponent = () => {
       7 |     useEffect(() => {
    >  8 |         Image.getSize('uri', (width, height) => {
         |               ^
       9 |             console.log({width, height})
      10 |         })
      11 |     }, [])

      at Function.getSize (node_modules/react-native/Libraries/Image/Image.ios.js:32:36)
      at screens/File.test.tsx:8:15
      at commitHookEffectListMount (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12932:26)
      at commitPassiveMountOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14346:11)
      at commitPassiveMountEffects_complete (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14306:9)
      at commitPassiveMountEffects_begin (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14293:7)
      at commitPassiveMountEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14281:3)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16233:3)
      at flushPassiveEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16182:14)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16002:9

  ● Foo › something

    TypeError: success is not a function

      at node_modules/jest-expo/src/preset/setup.js:23:63
```

### What platform(s) does this occur on?

Not Applicable

### Environment

npx: installed 2 in 0.37s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.6 => 47.0.6
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

1. Create a blank expo project via `expo-cli --init`
2. Select the `tabs` template so that the important dependencies are pre-installed
    * This installs `jest-expo@47.0.1`, which seems to have the issue 
4. Run `yarn add @testing-library/jest-native @testing-library/react-native @types/jest jest-transform-stub -D`
    * Just needed for writing the quick demo test
5. Add the following test file:

```tsx
import { useEffect } from "react"
import { Image } from "react-native"
import { render } from '@testing-library/react-native';

const MyComponent = () => {
    useEffect(() => {
        Image.getSize('uri', (width, height) => {
            console.log({width, height})
        })
    }, [])

    return null
}

describe('Foo', () => {
    it('something', () => {
        render(<MyComponent/>)
    })
})
```

6. Run it via `yarn jest`

**Comment by brentvatne** [comment]
this seems like a bug in the react-native preset. we extend that to mock expo modules, but we don't touch the default mocking from https://github.com/facebook/react-native/blob/main/jest-preset.js

this issue is better suited for the react-native repository

**Comment by jeromecovington** [comment]
I am seeing this as well.

**Comment by jeromecovington** [comment]
@udeyrishi did you ever follow up in the react-native repo? I am happy to collaborate on examples to see if we can get some eyes on the issue.

**Comment by udeyrishi** [comment]
@jeromecovington Just did it now: https://github.com/facebook/react-native/issues/35518
