### ISSUE TITLE
[expo-file-system] Storage Access Framework: Can only read the directory user grants access to, and not sub-directories

### ISSUE THREAD

**Issue by tehlordvortex** [expo/expo#20102]
### Summary

Hello!

For some reason, while using `expo-file-system`'s `StorageAccessFramework`  I seem to only be able to access files within the directory the user chooses.
For example, assuming this layout:
```
Folder A
  - Folder B
    - Folder C
    - Folder D
  - Folder E
  - Folder F
```

If the user grants access to `Folder A`, and I call `readDirectoryAsync` on the provided URI, it returns the contents of `Folder A` as expected.
But, if I pick the first item in the array (which is the URI for `Folder B`), and invoke `readDirectoryAsync` on it, rather than the contents of `Folder B`, I still get the contents of `Folder A`.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2022.10.17.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

```js
import {
  StorageAccessFramework as SAF
} from "expo-file-system";

async function printNestedContents() {
  const permissions = await SAF.requestDirectoryPermissionsAsync();
  if (!permissions.granted) return
  const { directoryUri } = permissions;
  const filesInRoot = await SAF.readDirectoryAsync(directoryUri);
  const filesInNestedFolder = await SAF.readDirectoryAsync(filesInRoot[0]);
  // Both values will be the same
  console.log({ filesInRoot, filesInNestedFolder })
}
```

**Comment by brentvatne** [comment]
I believe this is how the API is intended to work. @lukmccall do you remember the details here?

**Comment by lukmccall** [comment]
I think that is the intended behavior. The SAF is very strict. It doesn't allow you to read anything else than the directory which was grated by the user. However, to be extra sure, I'll check that later.
