### ISSUE TITLE
Expo debug menu appears empty & transparent on M1 simulator

### ISSUE THREAD

**Issue by ryl** [expo/expo#20117]
### Summary

With Expo SDK 46 and 47, after pressing command + ctrl + z, the developer menu appears empty and transparent in a vanilla app on an M1 Mac simulator.

If I go back to SDK 45, it works fine.

I'm new, so this is probably on me, but I don't know where to go from here.

![Simulator Screen Shot - iPhone 14 - 2022-11-18 at 15 33 45](https://user-images.githubusercontent.com/702146/202807561-e717ea44-93e2-49c0-950d-d63368c5da75.png)

Here is what I see on a physical device from the same project, and what I hope to see in the simulator.

![Screen Shot 2022-11-21 at 11 25 20 PM](https://user-images.githubusercontent.com/702146/203231175-5e0448f6-2173-47bf-b930-7762fe3b0708.png)

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/ryl/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.6 => 47.0.6
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

```
npx create-expo-app AwesomeProject
cd AwesomeProject
npm run ios
```

**Comment by Kudo** [comment]
hi there! what's your expo-dev-menu version? (you could check it through `yarn why expo-dev-menu` or `npm ls expo-dev-menu`). also it's worth to check the content of `node_modules/expo-dev-menu/assets/dev-menu-packager-host` and it should be exactly like this:
```
// This file is autogenerated on `yarn start` but its content shouldn't be committed to the repo,
// so we just keep it empty in the repo and let any local changes be gitignored. Don't delete it!
```

**Comment by ryl** [comment]
In the case of a blank project created with `npx create-project`, running `npm ls expo-dev-menu` outputs...

```
npm ls expo-dev-menu
awesomeproject@1.0.0 /Users/ryl/projects/react-native/AwesomeProject
└── (empty)
```

**Comment by Kudo** [comment]
sorry i misread the problem, it's expo go not development builds. in this case, please try to reset simulator data (Simulator menu > Device > Erase All Content and Settings) and do npm run ios again.

**Comment by ryl** [comment]
I've cleared the device data numerous times using the Erase All Content and Settings option. Unfortunately the problem persists.

I've tried removing everything I can think of and re-installing hoping I might clear out some corrupted cache. For example:

```
~/.nvm (deleting the my entire node version manager directory and re-installing fresh)
~/.npm
~/.expo (in my home directory as well as project directory)
~/{project-root}/node_modules
```

Still no luck. Are there any other locations I should try clearing?

**Comment by ryl** [comment]
I was finally able to solve this problem myself. My problem was not the fault of Expo or Expo Go, but rather the fact that my work laptop uses a corporate proxy that fiddles with certificates.

After opening up Console.app and watching Expo Go's logs, I saw a bunch of errors complaining about not being able to verify a certificate, with the name my corporate proxy's CA in the errors.

I added and trusted the CA on my simulator and tried again. The developer menu appeared correctly, presumably because it could finally download some assets it needed.

Hopefully this helps someone in the same position down the road somewhere.

**Comment by talpert022** [comment]
I believe im having the same problem (work computer). How did you see the logs exactly, and find the certificate to trust on your laptop? Any help appreciated!

**Comment by ryl** [comment]
@talpert022 I used the mac application named "Console". It is a standard tool that ships with the OS I believe. I selected my device on the left hand side and filtered my results using the search on the top right so that I limited the output to mostly just Expo Go stuff. That's how I was able to spot the errors.

As far as the certificate goes, it was installed in my mac's keychain by the IT department. I exported it using the "Keychain Access" application.

Then I had to go through the process getting the certificate onto my simulator. There was a time when you could drag and drop it onto the simulator to install it, but those days seem to be gone. I had to put the cert on a local HTTP server (nginx), visit localhost:8080 and download the cert through Sarfari. Then there were numerous places I had to visit to actually "accept" that cert. I believe I had to visit both `Settings > General > Device Management` and  `Settings > General > About > Certificate Trust Settings`.

Once I jumped through all those hoops, things started working for me.

Not a user-friendly experience, but not really the fault of Expo Go. Good luck!

**Comment by Kalightortaio** [comment]
I'm having this issue on a physical android device. The server is located on a github codespace. I'm using tunneling through ngrok to connect to the app, and for the life of me I'm unable to see the developer menu. I'm at my wit's end here.

**Comment by zakwalters** [comment]
I was facing this issue on a physical Android device and clearing both the storage and cache for Expo Go brought the developer menu back.

**Comment by roana0229** [comment]
I had the same error in iOS Simulator, and I was able to resolve it by following the steps below in iOS Simulator.

1. open OS Settings App
2. General
3. About
4. Certificate Trust Settings
5. certificate off 
6. certificate on
