### ISSUE TITLE
Expo GO crashes at startup when using GLView component from expo-gl (SDK 47)

### ISSUE THREAD

**Issue by jakkunight** [expo/expo#20114]
## Expected behavior:
Screen shows a black square inside a cyan one of 300x300px
## Current behavior:
Expo GO app crashes without showing anything.
There are no logs on the console.

### What platform(s) does this occur on?

Android

## Environment Info (from expo-env-info):
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 4.14 Kali GNU/Linux Rolling 2022.4
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 18.10.0 - /usr/bin/node
      npm: 8.19.2 - /usr/bin/npm
    npmPackages:
      expo: ~47.0.6 => 47.0.6
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Example code at Expo GLView docs.
https://docs.expo.dev/versions/latest/sdk/gl-view/

**Comment by wkozyra95** [comment]
I can't reproduce that issue.
- What version of expo-gl you have?
- Wat device and version of android it's on?
- Did you test your minimal reproducible example on a clean app generated with `npx create-expo-app`? If not please do

**Comment by jakkunight** [comment]
I tested the example given in the expo docs (link provided above) in a clean expo project created with create-expo-app and used expo-gl ALL AT LATEST VERSION. 
My android version is 12 (an SM-A525M/DS)
The Expo GO app version is also the latest (from Google Play Store).
