### ISSUE TITLE
Task :expo-av:configureCMakeDebug[arm64-v8a] FAILED

### ISSUE THREAD

**Issue by theartificialguy** [expo/expo#20123]
### Summary

I shifted to M1 machine and getting this error for expo-av, I couldn't find anything related to this error, it is happening only in android.

Command used to run project: npx react-native run-android Build Error:
```
> Task :expo-av:configureCMakeDebug[arm64-v8a] FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-av:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] exception while building Json A problem occurred starting process 'command '/Users/macbook/Library/Android/sdk/cmake/3.18.1/bin/cmake''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```
Package.json:
```
"expo": "^46.0.0",
"expo-av": "~12.0.4",
"react-native": "0.69.6",
```
I have created a detailed SO question also -> https://stackoverflow.com/q/74497904/11685381

If anyone need any more details, please feel free to ask, I'm happy to provide, I just can't get past this error.

### What platform(s) does this occur on?

Android

### Environment

```
info Fetching system and libraries information...
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 551.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 7.24.2 - ~/Desktop/myproject/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Minimal reproducible example

Steps:-
1) on an M1 MacBook -> npx react-native init m1project --version 0.69.6
2) npx react-native run-android -> It was working.
3) npx install-expo-modules@latest
4) npx expo install expo-av
5) npx react-native run-android/yarn android-> Got the same build error as mentioned in the title.

Here is a repo link which I created and confirmed the same build error: https://github.com/theartificialguy/rn-m1

**Comment by theartificialguy** [comment]
I was able to solve it, what I did was -> remove CMake 3.18 and installed latest CMake version 3.22 from android studio (created a `local.properties` file inside android folder with `cmake.dir = /User/...`) and downgraded node from v19 to v16.8.0. However, I got into another issue right after solving this one:
```
> Task :expo-dev-launcher:compileReleaseWithDevLauncherKotlin FAILED
e: /Users/username/Desktop/project/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/DevLauncherClientHost.kt: (17, 8): Unresolved reference: devmenu
e: /Users/username/Desktop/project/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/DevLauncherClientHost.kt: (47, 7): Unresolved reference: RNGestureHandlerPackage
e: /Users/username/Desktop/project/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/DevLauncherClientHost.kt: (48, 7): Unresolved reference: SafeAreaContextPackage
e: /Users/username/Desktop/project/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/react/DevLauncherDevSupportManagerSwapper.kt: (15, 33): Unresolved reference: rncompatibility
e: /Users/username/Desktop/project/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/react/DevLauncherDevSupportManagerSwapper.kt: (27, 37): Unresolved reference: DevLauncherDevSupportManager
e: /Users/username/Desktop/project/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/react/DevLauncherDevSupportManagerSwapper.kt: (38, 34): Unresolved reference: DevLauncherDevSupportManager
e: /Users/username/Desktop/project/node_modules/expo-dev-launcher/android/src/main/java/expo/modules/devlauncher/DevLauncherPackage.kt: (15, 97): Unresolved reference: DevLauncherPackageDelegate

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-dev-launcher:compileReleaseWithDevLauncherKotlin'.
> Compilation error. See log for more details
```
Package.json:
```
"expo": "^46.0.0",
"expo-dev-client": "1.3.1",
```
Any help would be really appreciated!

**Comment by LucasGarcez** [comment]
I found the problem. The `expo-av:configureCMakeDebug` task uses the CMake version 3.18.1. For some reason, this version is not made for arm64 (m1 silicon), so I had to install de Rosetta 2. Now it's working!

[Rosetta 2](https://support.apple.com/en-au/HT211861) enables a Mac with Apple silicon to use apps built for a Mac with an Intel processor.

To install Rosetta just run:
`/usr/sbin/softwareupdate --install-rosetta`

Close all terminal windows and rerun your command, in my case, `yarn android`

**Comment by silacode** [comment]
> I found the problem. The `expo-av:configureCMakeDebug` task uses the CMake version 3.18.1. For some reason, this version is not made for arm64 (m1 silicon), so I had to install de Rosetta 2. Now it's working!
> 
> [Rosetta 2](https://support.apple.com/en-au/HT211861) enables a Mac with Apple silicon to use apps built for a Mac with an Intel processor.
> 
> To install Rosetta just run: `/usr/sbin/softwareupdate --install-rosetta`
> 
> Close all terminal windows and rerun your command, in my case, `yarn android`

This works. I have a new m2 mac so rosetta wasn't installed. However npx init newProject was successfully installed but not my existing work repo. Cheers

**Comment by aleffarias** [comment]
> This works!! thanks

**Comment by bpcsys** [comment]
Am also facing the same issue while using Linux

**Comment by Software-FixBit** [comment]
Estou enfrentando o mesmo problema mas ao usar o windows

**Comment by SorenJ89** [comment]
Even though the poor fellow above me can't speak english, I second his statement that the problem also persists on windows.

**Comment by AsteriskZuo** [comment]
https://www.google.com/search?q=configureCMakeDebug%5Barm64-v8a%5D&newwindow=1&sca_esv=591785850&sxsrf=AM9HkKn0YJTHGbwch1wtRD3z-MeIlLv4Pg%3A1702883722271&source=hp&ei=ivF_ZejjDozikPIPivaOqA0&iflsig=AO6bgOgAAAAAZX__mr_1WFnJfhZaHvU7rz8pKAzAHAhl&ved=0ahUKEwjo0O6auJiDAxUMMUQIHQq7A9UQ4dUDCAo&uact=5&oq=configureCMakeDebug%5Barm64-v8a%5D&gs_lp=Egdnd3Mtd2l6Ih5jb25maWd1cmVDTWFrZURlYnVnW2FybTY0LXY4YV1I-AJQAFgAcAB4AJABAJgBAKABAKoBALgBA8gBAPgBAvgBAQ&sclient=gws-wiz#ip=1


This should be a react-native related question. You can search it.
