### ISSUE TITLE
iOS release build failing after upgrading to expo 47.0.5

### ISSUE THREAD

**Issue by nkjs-git** [expo/expo#20145]
### Summary

I had upgraded my react native project expo 47.0.5 along with its dependencies. The android release build is working fine and also iOS debug build but the iOS release build is failing with below error:

ld: '/Users/nkjs/Library/Developer/Xcode/DerivedData/myproject-gtljriuqyymvckgzplmbnsfizitx/Build/Intermediates.noindex/ArchiveIntermediates/myprojectDev/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXFileSystem/EXFileSystem.framework/EXFileSystem(EXFileSystemAssetLibraryHandler.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/nkjs/Library/Developer/Xcode/DerivedData/myproject-gtljriuqyymvckgzplmbnsfizitx/Build/Intermediates.noindex/ArchiveIntermediates/myprojectDev/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXFileSystem/EXFileSystem.framework/EXFileSystem' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have tried setting ENABLE_BITCODE to No at target level and also at pod level. But din't work. Please help me.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.1 - /usr/local/opt/node@16/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/opt/node@16/bin/npm
      Watchman: 2022.10.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.6 => 47.0.6 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

1. Create new project using 
'npx create-expo-app myproject'

2. create iOS and android folder using eject
3. Add the package.json as below and build the iOS release ipa.

{
  "name": "myproject",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~47.0.6",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "expo-splash-screen": "~0.17.5",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "buffer": "^6.0.3",
    "expo-barcode-scanner": "~11.4.0",
    "expo-camera": "~13.0.0",
    "gs1-barcode-parser": "^1.0.1",
    "jexl": "^2.3.0",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.4",
    "react-dom": "18.1.0",
    "react-native-config": "1.4.6",
    "react-native-dialog-input": "^1.0.8",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-pager-view": "6.0.1",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.2",
    "react-native-select-dropdown": "^2.0.4",
    "react-native-splash-screen": "^3.3.0",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "13.4.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.1",
    "react-timer-mixin": "^0.13.4",
    "uuidv4": "^6.2.13"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

**Comment by Kudo** [comment]
hi there! please try to upgrade xcode 14 or [build all modules from source](https://expo.fyi/prebuilt-modules). thanks!

**Comment by nkjs-git** [comment]
> hi there! please try to upgrade xcode 14 or [build all modules from source](https://expo.fyi/prebuilt-modules). thanks!

Hi @Kudo, 

I had tried to build this project using Xcode 14.0.1 in azure pipelines, but the pipeline got failed with error:

{ platform:iOS Simulator, id:C3F4DCE3-4B3B-4152-A428-57C8868F26CD, OS:16.0, name:iPhone SE (3rd generation) }
    Run script build phase '[CP-User] Config codegen' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'react-native-config' from project 'Pods')
    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'pmyproject' from project 'myproject')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'myproject' from project 'myproject')
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
** BUILD FAILED **

##[error]Error: /usr/bin/xcodebuild failed with return code: 65
Finishing: Xcode

**Comment by Kudo** [comment]
@nkjs-git could you share full log? these look like warnings not errors.
