### ISSUE TITLE
exp build:ios throws TypeError: OBLIGATORY_CREDS_KEYS.keys is not a function 

### ISSUE THREAD

**Issue by benhurott** [expo/expo#2014]
## Description
When we try to build ios standalone app with --non-interactive, it raises an error.

### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/pointrappdev-f1b3a4b0-39e2-47e7-bd0a-2bc6dad27292.tar.gz

### Steps to Reproduce

1 - Login in the expo account
2 - Run this script

```sh
exp build:ios \
    --non-interactive \
    --release-channel qa \
    --team-id "$APPLE_TEAM_ID" \
    --clear-credentials \
    --clear-dist-cert \
    --dist-p12-path "$IOS_CERTIFICATES_FOLDER/exported_cer.p12" \
    --push-p12-path "$IOS_CERTIFICATES_FOLDER/exported_aps.p12" \
    --provisioning-profile-path "$IOS_CERTIFICATES_FOLDER/cert_adhoc.mobileprovision"
```
Just override the environment variables with your distribution certificates.

### Expected Behavior

Expo builds the project successfully

### Actual Behavior

![image](https://user-images.githubusercontent.com/3187772/42964418-523a0e6e-8b6d-11e8-839a-f6e6ba020fe3.png)

**Comment by lhcn** [comment]
i met the same issue.
I removed ".keys" in the exp code,to skip it in my local repo
![image](https://user-images.githubusercontent.com/9475228/44192472-24bc7e80-a162-11e8-824b-b0a6ede7e7ba.png)

~/.nvm/versions/node/v9.3.0  ➦ 2176894  vim ./lib/node_modules/exp/build/commands/build/IOSBuilder.js
