### ISSUE TITLE
ESLint parse error on "react-native" import with eslint-config-universe

### ISSUE THREAD

**Issue by obasille** [expo/expo#20147]
### Summary

Using the Expo typescript template and the [recommended](https://github.com/expo/expo/tree/main/packages/eslint-config-universe) ESLint configuration for `eslint-config-universe`, I get this linting error in App.tsx:
```sh
npx eslint App.tsx
```
```
Parse errors in imported module 'react-native': ';' expected. (14:32)
```

Note that I'm not getting the error when configuring ESLint to no use universe, for example with this content for `.eslintrc.js`
```
module.exports = {
  root: true,
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: { project: ["./tsconfig.json"] },
  plugins: [
    "@typescript-eslint"
  ],
  ```

### What platform(s) does this occur on?

Not Applicable

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ~47.0.7 => 47.0.7
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    Expo Workflow: managed

### Minimal reproducible example

```sh
npx create-expo-app my-app --template expo-template-blank-typescript
cd my-app
npm i -D eslint-config-universe eslint prettier
```

Create `.eslintrc.js`
```
module.exports = {
  extends: [
    'universe',
    'universe/shared/typescript-analysis',
  ],
  overrides: [
    {
      files: [
        '*.ts',
        '*.tsx',
        '*.d.ts'
      ],
      parserOptions: {
        project: './tsconfig.json'
      },
    },
  ],
};
```

Create `.prettierrc`
```
{
  "singleQuote": true
}
```

```sh
npx eslint App.tsx
```

**Comment by brentvatne** [comment]
we didn't intend eslint-config-universe for public usage necessarily. it is built for this repository - this is why we haven't documented it on https://docs.expo.dev/

your mileage may vary when using it. we hope to provide a recommended eslint config at some point, but for now this is likely a good config to use: https://www.npmjs.com/package/@react-native-community/eslint-config - and you can pick any config that you find useful from eslint-config-universe and bring that in as well
