### ISSUE TITLE
Expo Go App crashes at start up on Android 7.1 and lower

### ISSUE THREAD

**Issue by favour626** [expo/expo#20157]
### Summary

Updated the Expo Go Application to the latest version (2.26.4) SDK 47 on my Galaxy Note 8 and it always crashes on startup. It shows the expo icon and then crashes instantly. I tried to let the laptop open up the expo go app but that didn't work either.

### What platform(s) does this occur on?

Android

### Environment

SAME OLD

### Minimal reproducible example

> click on playstore

> update the app the the latest version (2.26.4) SDK 47

>open on a physical device with Android 7 or 7.1

> crashes

**Comment by brentvatne** [comment]
can you try 2.26.5? also, you didn't share any information about your laptop. that is what the "environment" heading is for

**Comment by favour626** [comment]
This works! Thank you.
