### ISSUE TITLE
EAS Build: There are no files matching pattern "ios/build/*.ipa"

### ISSUE THREAD

**Issue by GKyomen** [expo/expo#20150]
### Summary

I was doing my first build to ios with EAS. Everything works fine, except for the last step, Upload application archive, with the error "There are no files matching pattern "ios/build/*.ipa""

I'm currently on a bare workflow.
Here's the [xcode logs](https://github.com/expo/expo/files/10066824/xcode-build-5c259be1-682c-4246-b239-010aac5739e5.log)

Strange thing is: `ios/build/` is in `.gitignore` by default.
I tried removing all the cache, no success either.

If you need any information, I'll be happy to provide it

### What platform(s) does this occur on?

iOS

### SDK Version

47.0.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 9.1.1 - ~/.nvm/versions/node/v16.18.1/bin/npm
    npmPackages:
      expo: ^47.0.0 => 47.0.6 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

https://snack.expo.dev/@gkyomen/8fcafc
install the packages and run `eas build -p ios`

**Comment by victorbds97** [comment]
I'm with this issue too

**Comment by brentvatne** [comment]
can someone please link to a build page where you are experiencing this?

**Comment by brentvatne** [comment]
happy to investigate if more info is provided but the minimal reproducible example here is not valid

**Comment by GKyomen** [comment]
@brentvatne https://expo.dev/accounts/mind_consulting/projects/sivtec-app/builds/5c259be1-682c-4246-b239-010aac5739e5 this link?

**Comment by andrewoodleyjr** [comment]
Nearly 2 years later... Its still happening

**Comment by alvinlal** [comment]
still an issue

**Comment by mdecrocemovson** [comment]
still struggling here!

**Comment by cantwait** [comment]
has anyone found a solution? It used to work correctly for me, 5 months later and one xcode upgrade it started to fail

**Comment by AvgarPro** [comment]
Just encountered this frustrating issue. No idea what's going on
