### ISSUE TITLE
expo-firebase-analytics not working with EAS UPDATE, Working fine with EXPO PUBLISH

### ISSUE THREAD

**Issue by viveksc1994** [expo/expo#20166]
### Summary

After switching to 'eas update' facing an issue with firebase. Working fine with 'expo publish'. (Working fine in local env.)

"Error: Firebase is not configured. Ensure that you have configured 'google-services.json' correctly."

![image](https://user-images.githubusercontent.com/10026278/203477384-50aaf581-63d4-42ea-9070-9bc9bdd0f7cf.png)

I can't figure out issue is with 'expo-firebase-analytics' or 'eas update'

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: 46.0.17 => 46.0.17
      react: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
    Expo Workflow: managed

### Minimal reproducible example

Here is the minimal reproducible example - https://github.com/viveksc1994/expo_46_firebase_standalone_apk

Please add below details of yours

- In app.json file
  1. expo.extra.eas.projectId
  2. expo.updates.url
  3. expo.web.firebase - your own settings
- google-services.json - your own settings

**Now run in local env**
```
npm install
npx expo start -c
```
It is working fine in local env. (Open app and click on 'Please click Here', Showing firebase log in console).

**Check with eas update**

``npx eas update --branch dev --message 'published dev channel'``

When you scan QR and open app, and click on 'Please click Here'. It is showing error as per above screenshot.

**Check with classic publish method**

Remove below two properties from app.config
  1. expo.runtimeVersion
  2. expo.updates.url
 
Command to publish

``expo publish --release-channel dev``

When you scan QR and open app, and click on 'Please click Here'. It is not throwing any error.

**Comment by viveksc1994** [comment]
I have raised same issue with eas-cli - https://github.com/expo/eas-cli/issues/1537#issue-1461146469

**Comment by brentvatne** [comment]
sorry for the hassle! expo-firebase-* libraries are all deprecated, we recommend using react-native-firebase instead. here is a helpful migration guide: https://expo.fyi/firebase-migration-guide
