### ISSUE TITLE
[docs] Getting Started -> Tutorial image assets missing

### ISSUE THREAD

**Issue by jeromecovington** [expo/expo#20162]
### Summary

Images related to the Getting Started -> Tutorial (StickerSmash) are missing from the cloned repo.

Examples include the asses for the EmojiList component:
```javascript
  const [emoji] = useState([
    require('../assets/images/emoji1.png'),
    require('../assets/images/emoji2.png'),
    require('../assets/images/emoji3.png'),
    require('../assets/images/emoji4.png'),
    require('../assets/images/emoji5.png'),
    require('../assets/images/emoji6.png'),
  ]);
```

### Link to the related docs page

https://docs.expo.dev/tutorial/create-a-modal/

### Anything else?

There are other images missing from the assets directory too, such as:
```javascript
const PlaceholderImage = require('./assets/images/background-image.png');
```

From the documentation at: https://docs.expo.dev/tutorial/build-a-screen/

**Comment by amandeepmittal** [comment]
Hi @jeromecovington,

The step to download the `assets` required for this tutorial is provided here: https://docs.expo.dev/tutorial/create-your-first-app/#step-1-initialize-a-new-expo-app.

**Comment by gemanepa** [comment]
@amandeepmittal I think some sort of link or reminder in https://docs.expo.dev/tutorial/create-a-modal/#step-4-display-a-list-of-emoji would be cool cause I ended up here due to missing the download assets part in the step1 of the article you linked
