### ISSUE TITLE
Push Notification is not shown up in foreground iOS App

### ISSUE THREAD

**Issue by OscarYuen** [expo/expo#2016]
### Environment

iOS 11 or above

### Steps to Reproduce

1. Open the expo sample app
2. Send Remote push notification

### Expected Behavior

A push notification should be shown in the status bar

### Actual Behavior

A push notification is not shown in the status bar

**Comment by sjchmiela** [comment]
At the moment Expo SDK uses `UILocalNotification` API with which it is not possible to achieve a push notification showing when the app is visible and foremost.

> If the app is foremost and visible when the system delivers the notification, the app delegate’s `application:didReceiveLocalNotification:` is called to process the notification. Use the information in the provided UILocalNotification object to decide what action to take. **The system does not display any alerts, badge the app’s icon, or play any sounds when the app is already frontmost.**
> 
> _[Source](https://developer.apple.com/documentation/uikit/uilocalnotification?language=objc)_

We intend to replace `UILocalNotification` with `UNNotification` framework which would allow us to display the notification even when the app is in the foreground (vide [doc](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html#//apple_ref/doc/uid/TP40008194-CH5-SW15)), but it's not currently planned. 😞 

What you could do is to register to get notified of incoming notifications by adding a listener with [`Notifications.addListener`](https://docs.expo.io/versions/latest/sdk/notifications.html#exponotificationsaddlistenerlistener) and update your UI (or show your custom notification view) when applicable.
