### ISSUE TITLE
notifications stopped working after owner has been changed

### ISSUE THREAD

**Issue by michalstrzelecki** [expo/expo#20179]
### Summary

I am using:
```json
"expo-notifications": "~0.16.1",
```
I had to transfer my expo project. The owner key has been changed. The notifications stopped working. Tested using https://expo.dev/notifications 

### What platform(s) does this occur on?

Android

### Environment

```
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    Shell: 5.0.17 - /bin/bash
Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
npmPackages:
    @expo/webpack-config: ^0.17.0 => 0.17.3 
    expo: ~46.0.13 => 46.0.17 
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-web: ~0.18.7 => 0.18.10 
npmGlobalPackages:
    eas-cli: 2.7.1
Expo Workflow: managed
```

### Minimal reproducible example

Start using the expo notification package. Transfer the project and change the owner key in the `app.config.js`.

**Comment by brentvatne** [comment]
can you share more information about what you are experiencing?

eg: "I am trying to send a notification to a push token that existed prior to transferring, and I receive ___ error from the Expo notifications endpoint"

**Comment by michalstrzelecki** [comment]
I am trying to send a notification using https://expo.dev/notifications to a push token that was created after transfering a project, and I do not get any error from https://expo.dev/notifications.

**Comment by michalstrzelecki** [comment]
I have created new virtual device using android studio and it starts working on this newely created device.
