### ISSUE TITLE
Enchance - tokens for application

### ISSUE THREAD

**Issue by Luchanso** [expo/expo#2018]
Hi guys, can you add application tokens?
I publishing app in CI/CD pipeline, now it look like this:
```sh
exp login -u "$EXPO_LOGIN" -p "$EXPO_PASSWORD"  --non-interactive
exp publish
```
I think store login and password of expo account in env variables it's not good idea. Better way publish application by token:
```sh
exp login -u luchanso -t MC41MDAyMTU5NDY0MjU0MzA4MC4wNDE4MDQyMDY2NjIxOTQy
exp publish
```
or 
```sh
exp login -u "$EXPO_LOGIN" -t "$EXPO_TOKEN"
exp publish
```

With token I'll grant access only for single application not for full account.
You can make like [github](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/). Thank you for great tools.

**Comment by ccheever** [comment]
Hi - There is a feature request for this here: https://expo.canny.io/feature-requests/p/log-into-cli-with-token

Can you vote for it and comment on it?

Canny is where we track feature requests so closing this bug for now.
