### ISSUE TITLE
[docs] Azure example doesn't work

### ISSUE THREAD

**Issue by dotBeFoRE** [expo/expo#20183]
### Summary

With the example given you are only given the authorization code, not the actual JWT so you still have to call exchangeCodeAsync. This information is not shared with the person reading the docs so I think it's important to add this to atleast a note.

For clarification this is the (stripped down) typescript code we wrote to implement authenication with Azure AD.

```tsx
import React, {
  View,
} from 'react-native';
import { useCallback } from 'react';
import i18n from 'i18n-js';
import {
  makeRedirectUri,
  useAuthRequest,
  useAutoDiscovery,
  exchangeCodeAsync,
  AuthSessionResult,
} from 'expo-auth-session';
import settings from '@root/settings';
import { maybeCompleteAuthSession } from 'expo-web-browser';
import PrimaryButton from '../../Components/PrimaryButton/PrimaryButton';

import { useAuth } from '../../Contexts/AuthContext';

maybeCompleteAuthSession();

export const LoginRegister = () => {
  const discovery = useAutoDiscovery(
    `https://login.microsoftonline.com/${settings.azure.tenantId}/v2.0`,
  );

  const { clientId } = settings.azure;
  const redirectUri = makeRedirectUri({ path: 'auth' });

  const { login } = useAuth();

  // Request
  const [request, , promptAsync] = useAuthRequest(
    {
      clientId,
      scopes: ['openid', 'profile', 'email', ...settings.azure.scope],
      redirectUri,
    },
    discovery,
  );

  const promptCompleted = useCallback(
    (codeResponse: AuthSessionResult) => {
      if (request && codeResponse?.type === 'success' && discovery) {
        exchangeCodeAsync(
          {
            clientId,
            code: codeResponse.params.code,
            extraParams: { code_verifier: request.codeVerifier || '' },
            redirectUri,
          },
          discovery,
        )
          .then((res) => {
            login(res.accessToken);
          })
          .catch((err) => {
            if (err instanceof Error) {
              console.error({ ...err });
            }
          });
      }
    },
    [clientId, discovery, login, redirectUri, request],
  );

  return (
    <View>
      <PrimaryButton
        text={i18n.t('LOGIN')}
        disabled={!request}
        loading={!request}
        onPress={() => {
          promptAsync().then(promptCompleted);
        }}
      />
    </View>
  );
};
```

### Link to the related docs page

https://docs.expo.dev/guides/authentication/#azure

### Anything else?

All the examples use useEffect to catch when the response changes, this is a discouraged pattern. It's better to handle this in the event handler.

**Comment by szymonbartnik** [comment]
Hey! Is there any example how to use [user flows](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-user-flow)? 

I'm struggling with configuraiton of azure b2c with `expo-auth-session`.

**Comment by andristarr** [comment]
I am very indereseted in that as well, as I always get an error saying: 
More info: AADB2C90012: The scope 'openid offline_access' provided in request is not supported.

I am scopes openid and offline_access are on the azure app itself. The example is not clear at all and doesn't work without showing the configuration entries.

**Comment by dotBeFoRE** [comment]
This issue was just a stripped down version of how we were handeling azure ad oauth in our app, please see the pr for a better example.

**Comment by donatoferrulli** [comment]
is it possible to integrate this PR also with tabs ? @dotBeFoRE
