### ISSUE TITLE
ImageManipulator: [Error: The method or property ImageManipulator.manipulateAsync is not available on ios, are you sure you've linked all the native dependencies properly?]

### ISSUE THREAD

**Issue by NicolasBonet** [expo/expo#20187]
### Summary

Hello,

When I am using the ImageManipulator I am having the following error:

```
 LOG  [Error: The method or property ImageManipulator.manipulateAsync is not available on ios, are you sure you've linked all the native dependencies properly?]
```

This is the line of code that triggers this error:

```
const resizedImage = await ImageManipulator.manipulateAsync(
                            asset.uri,
                            [{ resize: { width: 512, height: 512 } }],
                            { compress: 0.8, format: ImageManipulator.SaveFormat.JPEG },
                        );
```

I did the installation running `npx expo install expo-image-manipulator` and I am using expo 47.0.8. The error can be seen from my development build.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.7.0
    Expo Workflow: managed

### Minimal reproducible example

const resizedImage = await ImageManipulator.manipulateAsync(
                            asset.uri,
                            [{ resize: { width: 512, height: 512 } }],
                            { compress: 0.8, format: ImageManipulator.SaveFormat.JPEG },
                        );

**Comment by taron-e-farm** [comment]
This keeps happening to me top, I have a eas build expo project and can't use ImageManipulator.

**Comment by JordanRifaey** [comment]
Sending a new expo build with `eas build --profile development --platform ios` and reinstalling the app fixed it for me. It seems we have to rebuild after adding a new dependency.

**Comment by ahmed-khlifi** [comment]
When installing a package that need to change the native code you need to create a development build,  in your case `eas build --profile development --platform ios` and note  you need a paid apple developer account to setup the profile.
