### ISSUE TITLE
expo-battery Android IllegalStateException: Too many receivers, total of 1000

### ISSUE THREAD

**Issue by RCNNT-Industries** [expo/expo#20191]
### Summary

Crash in production as reported by Sentry:

`IllegalStateException Too many receivers, total of 1000, registered for pid: 31489, callerPackage:`

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/42340052/203727426-7b336a15-bd5d-409a-bf0f-4b9dfc80607d.png">

The app is using a background task for reporting position (courier style app), and in that file that the task is defined the `expo-battery` module is imported. The module adds a receiver when it starts in `onCreate` in `expo-battery/android/src/main/java/expo/modules/battery`, and never cleans it up, maybe that's the cause?

The `getBatteryLevelAsync` method registers a receiver, but with `null`, so that should not cause a problem if I'm understanding it correctly.

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.9.0 - ~/.nvm/versions/node/v16.9.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.9.0/bin/yarn
      npm: 8.19.3 - ~/Documents/Gordon/gordon-driver-app-next-gen/node_modules/.bin/npm
      Watchman: 2022.10.10.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.7 => 47.0.7
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: bare
```

### Minimal reproducible example

This is hard to test, not sure this even reproduces it. Requires getting the simulator to trigger 1000 location updates. There must be some easier way.

```
function getBattery() {
    Battery.getBatteryLevelAsync();
}
TaskManager.defineTask("test", getBattery);

Location.startLocationUpdatesAsync("test", {
    accuracy: Location.Accuracy.BestForNavigation,
    distanceInterval: 15, // meters
    timeInterval: 1, // ms (android only)
    deferredUpdatesInterval: 1, // ms, batch updates every
});
```

This should work

```
import * as Battery from "expo-battery";

setTimeout(() => {
  Array.from(Array(1001)).forEach(async (_, index) => {
    console.log("Battery fetch", index);
    await Battery.getBatteryLevelAsync();
    console.log("Done", index);
  });
}, 1000);
```

**Comment by RCNNT-Industries** [comment]
I'm not an Android dev, so perhaps there is a smarter way to do this than just calling `unregisterReceiver` at the end. It feels like at least the listener code should get a ref to a context and be able to call `getIntExtra` directly on that.

`react-native-device-info` also provides the same functionality, but it's not as easy to use/install as `expo-battery`.
Main module code for that can be found here: https://github.com/react-native-device-info/react-native-device-info/blob/39990cbdef39397c787df375e04bce2cd5fb9aa7/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L102

**Comment by dhcmega** [comment]
bump! I have the same feature and the same problem. Have you managed to solve it?

**Comment by lazarevkristijan** [comment]
> bump! I have the same feature and the same problem. Have you managed to solve it?

Bump, It's almost December still no fix.

**Comment by lazarevkristijan** [comment]
I resolved it I don't remember how I did it though haha

**Comment by lazarevkristijan** [comment]
> @lazarevkristijan you resolved it literally two days ago and you don't remember how? thanks.

Yea,
It was something really simple i work 15h a day i do so much i don't remember how i did it, if you have it let me look at it and i will help you
