### ISSUE TITLE
Expo Apple Login expo-apple-authentication is not working on published app on Testflight

### ISSUE THREAD

**Issue by mehmetasilkilic** [expo/expo#20193]
### Summary

I setup the package expo-apple-authentication as described on the documentation: https://docs.expo.dev/versions/latest/sdk/apple-authentication/#appleauthenticationbutton and when on development mode on it works perfect but when I deliver the app to test it on TestFlight Apple auth flow does not show up when I press the button.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ~45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    Expo Workflow: bare

### Minimal reproducible example

<AppleAuthentication.AppleAuthenticationButton
            buttonType={
              AppleAuthentication.AppleAuthenticationButtonType.SIGN_IN
            }
            buttonStyle={
              AppleAuthentication.AppleAuthenticationButtonStyle.BLACK
            }
            cornerRadius={24}
            style={{ width: MediumButtonWidth, height: 100 }}
            onPress={async () => {
              try {
                const credential = await AppleAuthentication.signInAsync({
                  requestedScopes: [
                    AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
                    AppleAuthentication.AppleAuthenticationScope.EMAIL,
                  ],
                });
                const formData = {
                  token: credential.authorizationCode,
                };
                dispatch(appleLogin(formData));
              } catch (e) {
                if (e.code === "ERR_CANCELED") {
                  alert("Entry Canceled");
                }
              }
            }}
          />

**Comment by vishaldhanotiyadev** [comment]
@mehmetasilkilic I am facing the same issue Do you have any solution?
