### ISSUE TITLE
SDK 47 installs incompatible version of Stripe using bare workflow on Android

### ISSUE THREAD

**Issue by r-hirsch** [expo/expo#20195]
### Summary

Expo SDK 47 installing/upgrading [Stripe](https://docs.expo.dev/versions/latest/sdk/stripe/) installs version 0.19.0. When running locally in a bare workflow **for Android** using `expo prebuild` and `expo run:android` the build fails.

The build works fine when in a managed workflow, and in a bare workflow for iOS.

Errors listed are Android specific.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 30, 31, 33
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

1. [Create a new Expo app](https://docs.expo.dev/get-started/create-a-new-app/)
2. Install Stripe: `npx expo install @stripe/stripe-react-native` - you will not need to configure the plugin.
3. Run a local Android native build: `npx expo run:android`.

Dependencies (at present time) after performing the above actions:

"expo": "~47.0.8",
"expo-status-bar": "~1.4.2",
"react": "18.1.0",
"react-native": "0.70.5",
"@stripe/stripe-react-native": "0.19.0",
 "expo-splash-screen": "~0.17.5"

**Comment by aleqsio** [comment]
Does upgrade @stripe/stripe-react-native in your app to the latest version fix the issue for you?

You can already just install using `yarn` and that should just work. Expo CLI will probably warn that you're using an incompatible version, but in that case you can just ignore it.

**Comment by aleqsio** [comment]
Also, if this also happens on EAS, could you share a link to a failing android build page?

**Comment by r-hirsch** [comment]
Hey @aleqsio, thank you for your reply.

That was one of the first things I tried, but unfortunately upgrading to the latest version (0.21.0) does not resolve the issue either. The same error messages are given.

Sadly I can't, our EAS build is private (sorry).

Presently my workaround is to continue using version 0.13.1.

**Comment by aleqsio** [comment]
This is the error I get:
```
Dependency 'androidx.appcompat:appcompat-resources:1.5.1' requires libraries and applications that
           depend on it to compile against version 32 or later of the
           Android APIs.
     
           :app is currently compiled against android-31.
     
           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 32, for example 32.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
```
           
To fix this you can use [expo-build-properties](https://docs.expo.dev/versions/latest/sdk/build-properties/) by installing it and adding to plugins array in app.json:
```
npx expo install expo-build-properties
```

```
 "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 33,
            "targetSdkVersion": 33,
            "buildToolsVersion": "33.0.0"
          }
        }
      ]
    ]
```

**Comment by aleqsio** [comment]
@brentvatne 

Should I add this to [our stripe docs](https://docs.expo.dev/versions/v47.0.0/sdk/stripe/) or should we try to make a PR to the config plugin for stripe so that it also bumps the compileSDK version?

**Comment by stefancata92** [comment]
Hello @aleqsio, any progress with this ? i try this solution
` "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 33,
            "targetSdkVersion": 33,
            "buildToolsVersion": "33.0.0"
          }
        }
      ]
    ]`
It fixed the issue, but what happend to me using expo sdk47 was that my app could not communicate to my firebase functions, this happend when i upload my app in TestFlight, locally everything works fine, any idea why something like this would happend?

**Comment by aleqsio** [comment]
@stefancata92 The fix impacts only Android, so these are issues are almost certainly unrelated. 

You can open a new issue and provide a minimum reproducible example of your issue so that we can investigate further.
In particular, you should not have a dependency on Stripe in the reproducible example unless you can show that the default Stripe configuration breaks firebase.

**Comment by ReisMari** [comment]
> Hey @aleqsio, thank you for your reply.
> 
> That was one of the first things I tried, but unfortunately upgrading to the latest version (0.21.0) does not resolve the issue either. The same error messages are given.
> 
> Sadly I can't, our EAS build is private (sorry).
> 
> Presently my workaround is to continue using version 0.13.1.

I also was having this issue, but on the managed workflow. The only thing that allowed my android build to finish was downgrading Stripe to this version (0.13.1). Thanks for sharing this workaround.
