### ISSUE TITLE
After Launch Camera app was crash

### ISSUE THREAD

**Issue by aasuparekh1** [expo/expo#20196]
### Summary

I setup the package expo-image-picker as described on the documentation: https://docs.expo.dev/versions/latest/sdk/imagepicker/#imagepickerlaunchcameraasyncoptions and when on development mode on if i open a camera then app  was crash.

### What platform(s) does this occur on?
Android

### Environment
npmPackages:
expo: "^45.0.0"
react: "17.0.2"
react-dom: "17.0.2"
react-native: "0.68.2"
expo-image-picker : "version": "13.1.1",

**Here is Code** 

const uploadImage = async (type) => {
    // get camera permission
    const { status } = await ImagePicker.getCameraPermissionsAsync();
    if (status !== "granted") {
      const { status } = await ImagePicker.requestCameraPermissionsAsync();
      if (status !== "granted") {
        console.log("Camera Granted Error")
        return;
      }
    }

**Probelm after launchCameraAsync**

    // launch camera with permission
    var { cancelled, base64, uri } = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      aspect: [4, 3],
      base64: true,
      quality: 0.2,
    });

    if (cancelled === false) {
      Alert.alert(i18n.t("UploadImage"), i18n.t("UploadImageConfirmation"), [
        {
          text: Yes,
        },
        { text: No},
      ]);
    }
  };

### Link to the related docs page

ImagePicker.launchCameraAsync

**Comment by aleqsio** [comment]
The code you shared looks ok.

To debug this further we need more details about the errors you see and including a reproducible [snack](https://snack.expo.dev/) example.
