### ISSUE TITLE
Video dimensions on the web don't scale the video

### ISSUE THREAD

**Issue by farzd** [expo/expo#20199]
### Summary

Here is the link from the documentation https://snack.expo.dev/@farzd/video
Change to web, the video does not scale to fit the dimensions,
changing dimensions also prove undesirable results 

### What platform(s) does this occur on?

Web

### Environment

snack link provided

### Minimal reproducible example

snack link provided

**Comment by hirbod** [comment]
This was fixed in SDK 47. There is a new prop, called `videoStyle` which works for web.

Upgrade your snack to SDK 47 and pass `videoStyle={styles.video}` - tested - works

**Comment by farzd** [comment]
Thank you
