### ISSUE TITLE
Improve IOS build certification

### ISSUE THREAD

**Issue by sonaye** [expo/expo#202]
`exp build:ios` resets certification credentials every time you
- Switch to a different team
- Run the project on a different device (laptop)
- Clear the project cache with `-c`

When prompted to upload a current certificate (originally generated and signed by Expo), providing the existing certificates simply fails, `exp` asks for a password that doesn't exist, we don't enter any password when generating these certificates the first place.

A workaround would be to generate a new set of certificates every time a new native update is needed with `exp build:ios -c`, at least until your Apple developer account reaches its maximum limit. As far as I know, deleting/clearing these certificates doesn't affect any app version that is already in production, so technically this works, but it's not practical. **Kindly advise if incorrect.**

A simple solution for all of this would be if `exp` stored the certificates credentials in the app, by in the app i mean in `.expo` directory or somewhere appropriate. `exp` "can" remember these credentials indeed, there is code for it already there somewhere, as long as we keep using the same device (laptop or desktop), don't change teams or clear the cache with `-c`, we can always submit new builds without having to generate any new certificates, they are automatically identified and linked to the project, we need this to be more portable.

Automated deployments for me is most attractive and most essential feature of Expo, this minor glitch completely take it out and makes it good for a one time use only.

Can you provide any insights on this? and maybe discuss the possibility of improving the flow of this process? and if possible maybe release as a minor update?

**Comment by sonaye** [comment]
cc: @jesseruder @dikaiosune

**Comment by dikaiosune** [comment]
Can you explain more about why you are always using `-c` when submitting builds? Also note that you only need to run the native build whenever something in your app's exp.json/app.json changes, you can just run `exp publish` most of the time.

**Comment by sonaye** [comment]
> Can you explain more about why you are always using -c when submitting builds?
Mainly Switching to a different Apple developer account, I work on multiple apps for multiple clients. In order to achieve that I have to clear any current stored credentials. The same issue however would be present if you tried submitting the build from a new machine.

> you can just run exp publish most of the time.
I understand that, I only generate a new native standalone build with every new sdk release.

**Comment by dikaiosune** [comment]
Have you tried running the builds without clearing the credentials? The certificates are stored on our servers per-project so you shouldn't have to do this when changing projects or machines unless you've changed the account/project name.

**Comment by sonaye** [comment]
Interesting, I haven't to be honest. Since exp asks for the team ID, I assumed that it should be specified manually for each build. I will test this now. I take it that if I moved to a new machine, I can login with any team ID and exp will detect and link the original certificate?

**Comment by sonaye** [comment]
I tested 4 projects, with 3 different team IDs.

```diff
+ Project 1, Team ID 1: [exp] IPA: https://link-to-ipa
- Project 2, Team ID 1: [exp] iOS: There was an error with this build. Please try again.
- Project 3, Team ID 1: [exp] iOS: There was an error with this build. Please try again.
- Project 4, Team ID 1: [exp] iOS: There was an error with this build. Please try again.
```
Only Project 1, with Team ID 1 -which was the last team ID I provided to `exp`- is building successfully. This means that we do need to clear the cache before any build to ensure that the correct team ID is passed.

**Comment by sonaye** [comment]
I will run another test.

**Comment by sonaye** [comment]
I ran the build again on the 3 remaining failing projects, without changing any credentials or `-c`.
```diff
+ Project 1, Team ID 1: [exp] IPA: https://link-to-ipa
+ Project 2, Team ID 1: [exp] IPA: https://link-to-ipa
+ Project 3, Team ID 1: [exp] IPA: https://link-to-ipa
+ Project 4, Team ID 1: [exp] IPA: https://link-to-ipa
```
They failed multiple times at first, but eventually all the builds were generated successfully.

I guess this means that we can supply any team ID the first time we build a new project or build a previous project on a new machine, and `exp` will take care of linking the project with the correct team ID, regardless of whether it was creating a certificate for the first time or linking with an existing one, it's not our job to worry about that. If this was indeed the case, we can close this issue.

**Comment by sonaye** [comment]
I would appreciate getting more details on how this process is handled within your infrastructure.

**Comment by dikaiosune** [comment]
The pair of your username and your app's "slug" (in exp.json) is unique in Expo, and we store the necessary information to build your standalone app based on that pair. This means that once you've logged in, we can verify that you're you (user account), and build your app with the info you've previously provided.

Once you've supplied a team ID and created certificates for a project on our servers, we can initiate that build from anywhere. You just need to log in to your Expo account on that computer.

There are definitely still things that need improving with this system, but I'm pretty sure this addresses the specific issues you raised, so I'll give this a close. We'll work on improving the docs for this!
