### ISSUE TITLE
IOS: allowsEditing: problems with images

### ISSUE THREAD

**Issue by dranitski** [expo/expo#20216]
### Summary

see below

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.18.0 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.1.2 - /usr/bin/npm
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

I've created simple Snack that can be used to reproduce the issue: https://snack.expo.dev/@dranitski.d.a/image-picker-for-github-issue

I load it on my real IOS device (iphone, OS 15.6) , and when I pick some images I have different problems with them. Here are the cases:

1. When I pick this image and use it without any editing it works OK. When I want to crop the smallest piece of it possible, it says ` Failed to read picked image`.
Here is a video:
https://user-images.githubusercontent.com/27373393/204008676-c226ce89-e1a6-431f-92ec-b6418fc2d7b6.MP4

2. I have two other photos that do not fail, but that give strange results on cropping. The width and height of resulting image is not same (image is not square). That is also true for the photo from p.1.
Here is a video:
https://user-images.githubusercontent.com/27373393/204012692-5b83688f-925c-4c05-b352-8ae1e86f10e2.MP4

All the problematic photos are in `HEIC` format.

If i make copy of them (duplicate in IOS photo settings) they start to work fine. I tried to send these HEIC uncompressed via messenger but after importing (as HEIC) they start to behave good. So that is why I will not attach the photos here.

**Comment by brentvatne** [comment]
hi there! there is an existing issue discussing this, basically it's an M1 simulator issue and does not occur on a real device: https://github.com/expo/expo/issues/19990#issuecomment-1315087158

**Comment by dranitski** [comment]
@brentvatne youre wrong. I mentioned that I reproduced it on my real device , not simulator. I am working on Linux, I have no way to use simulator.

**Comment by dranitski** [comment]
![6C27E3B9-4A79-465B-A3E6-F022DB18C6E9](https://user-images.githubusercontent.com/27373393/204077470-b0b6fb1b-582a-424f-81e8-016b15551afd.jpeg)
