### ISSUE TITLE
[docs] Expo TaskManager's defineTask documentation is unclear

### ISSUE THREAD

**Issue by Nxtra** [expo/expo#20210]
### Summary

In the docs and in [`TaskManager.js`](https://github.com/expo/expo/blob/main/packages/expo-task-manager/src/TaskManager.ts)  it says:

**In particular, it cannot be called in any of React lifecycle methods like `componentDidMount`.**

> // @needsAudit
> /**
>  * Defines task function. It must be called in the global scope of your JavaScript bundle.
>  * In particular, it cannot be called in any of React lifecycle methods like `componentDidMount`.
>  * This limitation is due to the fact that when the application is launched in the background,
>  * we need to spin up your JavaScript app, run your task and then shut down — no views are mounted
>  * in this scenario.
>  *
>  * @param taskName Name of the task. It must be the same as the name you provided when registering the task.
>  * @param taskExecutor A function that will be invoked when the task with given `taskName` is executed.
>  */

I, as a not-a-profound-react-expert, do not understand this sentence _"In particular, it cannot be called in any of React lifecycle methods like `componentDidMount`."_

Does this mean that I cannot call `TaskManager.defineTask` on the root of a custom hook?

### Link to the related docs page

https://docs.expo.dev/versions/v47.0.0/sdk/task-manager/

**Comment by brentvatne** [comment]
> Does this mean that I cannot call TaskManager.defineTask on the root of a custom hook?

correct. it must be called at the top level of your app, outside of any function execution. tasks must register themselves even if the react app is not rendered

**Comment by Nxtra** [comment]
> > Does this mean that I cannot call TaskManager.defineTask on the root of a custom hook?
> 
> correct. it must be called at the top level of your app, outside of any function execution. tasks must register themselves even if the react app is not rendered. see the example on the docs page for correct usage https://docs.expo.dev/versions/v47.0.0/sdk/task-manager/#example

Aight I see.
So it can also be in a file that defines a Screen. As long as it is not in the function that defines the screen. Like in the examples of this repo: https://github.com/expo/expo/blob/main/apps/native-component-list/src/screens/Location/BackgroundLocationMapScreen.tsx.

I think we should make it even more explicit in the docs. Cause I see the mistake that I made a lot in the community.

Often you want to define the callback of `defineTask` as an async function that needs contextual data to make an API request (eg. a user location tracking app where you would need the user id from a context of some sort to create the location history of this user). 

In that case one should use a pattern like 'event-emitter' to do that kind of work.
