### ISSUE TITLE
Xcode needs to be installed

### ISSUE THREAD

**Issue by kjoedion** [expo/expo#20226]
### Summary

I've installed Xcode. I've even ran `open -a Simulator` which opens the actual simulator first, and I am still told "Xcode needs to be installed" when trying to run `npm run ios`

I've even gone into the Xcode location preferences and made sure the command line tools is set.

Nothing works.

### What platform(s) does this occur on?

iOS

### SDK Version

~47.0.8

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /opt/homebrew/bin/node
      npm: 8.15.0 - /opt/homebrew/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Do a clean install of expo and try running `npm run ios`, it asks you to go to the app store to download xcode, even with xcode AND the ios simulator open.

**Comment by kjoedion** [comment]
Nevermind, I went into xcode and re-selected the dropdown item for location and its now working.

**Comment by cdaringe** [comment]
Settings > Locations > (reselect all of the default paths), suddenly it takes
