### ISSUE TITLE
Upgrade from SDK46 to SDK47 fails on web when using react-navigation drawer

### ISSUE THREAD

**Issue by findhumane** [expo/expo#20227]
### Summary

After upgrading from SDK46 to SDK47, the browser screen is blank and the console shows:

```
Uncaught Error: Module parse failed: Unexpected token (5:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export * from "./reanimated1";
| export * from "./reanimated2";
> export * as default from "./Animated";
    js bundle.js:71429
    Webpack 21
bundle.js:71429:7
```

### What platform(s) does this occur on?

Web

### Environment

<details><summary>npx expo-env-info</summary>

```
$ npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.0 Fedora Linux 35 (Xfce)
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 16.14.0 - /usr/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/bin/npm
      Watchman: 0.0.0 - /usr/bin/watchman
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed
```

</details>

### Minimal reproducible example

Reproducible example: <https://github.com/findhumane/testupgradesdk>

1. `git clone https://github.com/findhumane/testupgradesdk`
2. `cd testupgradesdk`
3. `npm install`
4. `npm run web`
5. Observe everything works including the drawer
6. `Ctrl^C`
7. `expo-cli upgrade`
8. `npx expo install @react-navigation/bottom-tabs @react-navigation/drawer @react-navigation/elements @react-navigation/native @react-navigation/native-stack react-native-vector-icons`
9. `npm run web`
10. Observe error: screen is blank and browser console shows errors

**Comment by brentvatne** [comment]
reanimated now requires the `'@babel/plugin-proposal-export-namespace-from'` plugin on web: https://docs.expo.dev/versions/latest/sdk/reanimated/#web-support

**Comment by findhumane** [comment]
That works, thanks!

1. `npm install --save-dev @babel/plugin-proposal-export-namespace-from`
2. `babel.config.js `
   ```
   module.exports = function(api) {
     api.cache(true);
     return {
       presets: ['babel-preset-expo'],
       plugins: [    
         '@babel/plugin-proposal-export-namespace-from',
         'react-native-reanimated/plugin',
       ]
     };
   };
   ```
