### ISSUE TITLE
iOS Client Perf Monitor disappears after reload

### ISSUE THREAD

**Issue by sarpmis** [expo/expo#2022]
### Environment
Expo Client app on iOS

### Steps to Reproduce
1. Open dev menu and tap "Show Perf Monitor"
2. Reload (live or manually)
3. Perf Monitor is now gone but the app still thinks its there

### Expected Behavior
Perf Monitor should still be there _or_ the app should know that the Perf Menu is gone and display the "Show Perf Monitor" option on the dev menu.

### Actual Behavior
The dev menu seems to think the Perf Menu is still on the screen and displays the "Hide Perf Monitor" option. So if I want to open the dev menu again I have to open dev menu, click "Hide Perf Monitor" (which does nothing) then open dev menu again and click "Show Perf Monitor".

This is not a major issue at all! But it is a little bit annoying having to open dev menu twice everytime I reload. 

Note: Haven't tested on Android, same issue may be there as well.

**Comment by FiberJW** [comment]
Hi, we’re closing inactive issues that apply to SDK versions we no longer support. I wasn’t able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks :)
