### ISSUE TITLE
[expo-av] Test builds fail on Android

### ISSUE THREAD

**Issue by klcantrell** [expo/expo#20224]
### Summary

Introducing `expo-av` to the project introduces errors when building for Android tests. Simply just having `expo-av` installed introduces the errors without any instantiation from the JavaScript app code.

Steps to reproduce:

1. Clone down the [minimal repro example](https://github.com/klcantrell/react-native-issue-repo/tree/expo-av-test-build) and install dependencies
1. Run `cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`
1. Observe issues during `:expo-av:mergeDebugAndroidTestJavaResource` task. See below snippet from build logs:

```
> Task :expo-av:mergeDebugAndroidTestJavaResource FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-av:mergeDebugAndroidTestJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/com.android.tools/proguard/coroutines.pro' from inputs:
      - /Users/klcantrell_mac/.gradle/caches/transforms-3/7cb48ce6e1f53c4f29c8fe5edd5b3016/transformed/jetified-kotlinx-coroutines-core-jvm-1.6.0.jar
      - /Users/klcantrell_mac/.gradle/caches/transforms-3/3525ca3cd94c013ed54deba1edb867ed/transformed/jetified-kotlinx-coroutines-android-1.6.0.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information
```

Workaround:

1. Run the `npm run patch-expo-av-android-test` command in the [minimal repro](https://github.com/klcantrell/react-native-issue-repo/tree/expo-av-test-build)
1. Repeat step 2 above and observe the build complete successfully

The workaround above adds the below to the `android.packagingOptions.excludes` of the `build.gradle` of `expo-av`:
```
[
    "META-INF/*",
    "META-INF/**/*"
]
```

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.13.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/klcantrell_mac/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 27, 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.6 => 0.70.6
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/klcantrell/react-native-issue-repo/tree/expo-av-test-build

**Comment by Kudo** [comment]
hi there! we've published `expo-av@13.0.2` with the fix. by upgrading the package, that should help to resolve the error. thanks for reporting the issue to us.

**Comment by SophieJung7** [comment]
![image](https://github.com/expo/expo/assets/36703871/1e52ef09-84e4-491e-bc7e-618810c5767d)
Similar thing is happening at version 13.2.1

**Comment by yareyaredesuyo** [comment]
expo-av 13.2.1 looks does not work fine in local environment

have to specify `ANDROID_SDK_ROOT` settings in `eas.json`

example

```
      "env": {
        "ANDROID_SDK_ROOT": "/Users/test/Library/Android/Sdk"
      }
```

https://stackoverflow.com/questions/71592608/expo-build-eas-local-sdk-location-not-found
