### ISSUE TITLE
expo-camera crashes on SDK46 build or expo-barcode-scanner conflicts with expo-camera

### ISSUE THREAD

**Issue by iegik** [expo/expo#20245]
### Summary

```
    "expo-barcode-scanner": "~11.4.0",
+  "expo-camera": "~latest"
```

```
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':expo-camera:compileReleaseKotlin'.
[RUN_GRADLEW] > Compilation error. See log for more details
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 57s
[RUN_GRADLEW] w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
[RUN_GRADLEW] 159 actionable tasks: 159 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
    Error: npx exited with non-zero code: 1
```

Temporary solution is to remove expo-camera: `npx r expo-camera`

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
      Watchman: 2022.10.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/me/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.17 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

npm i  expo-barcode-scanner expo-camera

npx eas-cli build -p android --profile preview --local

EAS "preview" profile configuration:
```
"preview": {
      "distribution": "internal",
      "android": {
        "credentialsSource": "local",
        "buildType": "apk"
      }
    },
 ```

**Comment by brentvatne** [comment]
use `npx expo install expo-camera expo-barcode-scanner` to ensure you have compatible versions

**Comment by iegik** [comment]
@apedroferreira, are you checked on read device, emulator? Using Expo Go or custom build?
For me, it works on SDK46 with real device (android22), custom build. For Expo Go there is some permission issues.

**Comment by apedroferreira** [comment]
> @apedroferreira, are you checked on read device, emulator? Using Expo Go or custom build? For me, it works on SDK46 with real device (android22), custom build. For Expo Go there is some permission issues.

SDK47, real Android device, Android 8.0, after a remote EAS build in a managed project

**Comment by richardcoder** [comment]
> > @apedroferreira, are you checked on read device, emulator? Using Expo Go or custom build? For me, it works on SDK46 with real device (android22), custom build. For Expo Go there is some permission issues.
> 
> SDK47, real Android device, Android 8.0, after a remote EAS build in a managed project (and not with the dev client, it's a production build, but it might happen with dev build too, I don't remember). Using v12 of `expo-camera` fixed it for me.

I face a similar problem that sdk46 + expo-camera v12 will crash imediately after I open the app, so I upgrade to expo sdk 47 and  expo-camera v13, it works perfectly in ios, but for android the crash problem remains. And I try to downgrade the expo-camera to v12, but it keep telling me the expo-camera v12 is incompatible with expo sdk 47, and it will trigger following error once I open app:

 ERROR  TypeError: undefined is not an object (evaluating '_ExponentCameraManager.default.Type')
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

Would you mind to tell me what version of expo-camera and expo sdk it finally works on android device? Thanks in advance.
I tried expo-camera@12.4.0 and expo-camera@12.3.0

**Comment by raajnadar** [comment]
@apedroferreira this is the solution for the app crash https://github.com/expo/expo/issues/20122
