### ISSUE TITLE
`Location.startGeofencingAsync()` stops working when app crashes / is killed

### ISSUE THREAD

**Issue by kurthuwig** [expo/expo#20252]
### Summary

The geofences created with `Location.startGeofencingAsync()` stop working, when the app crashes or is killed. You can reproduce it by crashing the app with

    adb shell am crash <app's package name>

Verify with

    adb shell ps -ef | grep <app's package name>

that it does not run anymore. You might need to do it twice, if the app UI was open.

The reason seems to be, that `LocationTaskService` uses a broadcast `PendingIntent` created by

    private PendingIntent preparePendingIntent() {
      return getTaskManagerUtils().createTaskIntent(getContext(), mTask);
    }

If I change the code to use a service `PendingIntent`, then the geofence always starts the app and triggers the event. It is even sufficient to just trigger an app start with the other way, to get it working.

Here is what I have changed in `expo-location` to create a "shadow"-geofence for each region that triggers a service which just prints out a line to the log:

[code.tar.gz](https://github.com/expo/expo/files/10111342/code.tar.gz)

It works, but this is obviously not the proper solution but I am unsure how to change the existing code, so that it still creates a task but within the working service.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.0 Manjaro Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.0.1 - /usr/bin/node
      npm: 8.19.2 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 30, 31, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~47.0.3 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    Expo Workflow: bare

### Minimal reproducible example

    Location.startGeofencingAsync("kurtFence", [
        {
          latitude: 52.516280,
          longitude: 13.377700,
          radius: 100,
          identifier: 'id',
          notifyOnEnter: true,
          notifyOnExit: true,
        }
    ]);

**Comment by Nxtra** [comment]
For long running background tasks you can use the TaskManager API
https://docs.expo.dev/versions/latest/sdk/task-manager/

```
  TaskManager.defineTask(GEOFENCING_TASK_NAME, async ({ data, error }) => {
    const { eventType, region }: any = data;
})
```

```
  const startGeofencing = async (regions: LocationRegion[]) => {
    const hasStartedGeoTask = await TaskManager.isTaskDefined(GEOFENCING_TASK_NAME);
    if (hasStartedGeoTask) {
      await Location.startGeofencingAsync(GEOFENCING_TASK_NAME, regions);
    }
  };
  ```

**Comment by kurthuwig** [comment]
> For long running background tasks you can use the TaskManager API https://docs.expo.dev/versions/latest/sdk/task-manager/

This is what my sample code did. But this task will not start when the app has crashed as the broadcast PendingIntent will not launch the app. So the problem is not having something run in the background, but to start it in the first place after a geofence has been triggered.

If I switch to a service Intent, then it the app recovers from the crash and handles the geofence.
