### ISSUE TITLE
App stoped working after updating from SDK46 to SDK47

### ISSUE THREAD

**Issue by relense** [expo/expo#20256]
### Summary

Before the update everything was going fine. Now after the expo update it just crashes.
Initially I was seeing an error related with react-native-qrcode-svg. Now I can't open the app.
Also when updating to sdk 47 some libraries aren't updating
<img width="741" alt="Screenshot 2022-11-29 at 13 25 40" src="https://user-images.githubusercontent.com/20577410/204540815-4845a0bc-202d-4943-b783-5604c6bd8a90.png">

This has also led to others issues where for instance react-native-safe-area-context updated to version 4.4.1 and now the dependency clashes with react-native-elements package.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Starting with this package.json.
`{
  "name": "app-mobile",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "expo start",
    "start:web": "expo start --web",
    "test": "jest --passWithNoTests",
    "eas:build": "eas build",
    "eas:submit": "eas submit"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-picker/picker": "2.4.8",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.4",
    "expo": "^46.0.17",
    "expo-application": "~4.2.2",
    "expo-auth-session": "3.7.1",
    "expo-clipboard": "~3.1.0",
    "expo-constants": "~13.2.4",
    "expo-local-authentication": "~12.3.0",
    "expo-module-scripts": "^2.0.0",
    "expo-random": "~12.3.0",
    "expo-secure-store": "~11.3.0",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.7",
    "expo-web-browser": "~11.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-elements": "~3.4.2",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-qrcode-svg": "~6.1.2",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "3.4.1",
    "react-native-screens": "~3.15.0",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@expo/config": "^7.0.0",
    "@types/lodash": "^4.14.189",
    "@types/react": "~18.0.0",
    "@types/react-dom": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "eslint": "^8.27.0",
    "jest": "^26.6.3",
    "jest-expo": "^46.0.0",
    "prettier": "^2.5.1",
    "typescript": "^4.6.3"
  },
  "jest": {
    "preset": "jest-expo"
  }
}
`

- After updating to sdk 47 I can't npm install anymore or run npx expo start.
<img width="710" alt="Screenshot 2022-11-29 at 15 02 06" src="https://user-images.githubusercontent.com/20577410/204564427-d5a66511-4441-4e4a-a4ea-01147fbfdfa8.png">
- I change the react-native-safe-area-context to version 3.4.1 and I can do npm install.
- After that I run the app with npx expo start.
- App crashes and shows this 
<img width="347" alt="Screenshot 2022-11-29 at 14 59 31" src="https://user-images.githubusercontent.com/20577410/204563758-4ce39ea8-dfc3-45c3-ab1d-887773a5c7dd.png">

- I tried this a few times and also got this error message:
![Screenshot_2022-11-29-15-17-13-125_host exp exponent](https://user-images.githubusercontent.com/20577410/204568556-e3c75465-e361-4f96-ab92-34a19d6442d0.jpg)

This seems to be related with the libraries that weren't updated.

I tried to add my package.json to the snack app and update my package.json with the updates that snack made. I still couldn't update the npm packages with npm i. 
I did the steps above and also put react-native-svg in version 12.4.1.
Only like this was I able to do npm i.
After this the issue persisted, but another library is missing.
I still can't run the app with SDK47

**Comment by aleqsio** [comment]
You have conflicting peer dependencies - react-native-elements and react-navigation require two different package versions.

You can try to upgrade react-native-elements, use --force --legacy-peer-deps or switch to yarn and use the `resolutions` field.

**Comment by relense** [comment]
Hi, thanks for the answer!

That actually helped locally, but now I can't create a build because the eas build system only runs "npm i" and it crashes which is the issue I had before.

**Comment by aleqsio** [comment]
Maybe this would help?
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
