### ISSUE TITLE
zsh: command not found: expo

### ISSUE THREAD

**Issue by Arnav7501** [expo/expo#20250]
### Summary

Really simple, randomly today when i try to use expo it says 
zsh: command not found: expo

I re-installed and uninstalled, but it didn't change anything. I tried everything online regarding changing my path but i still get the same error. can anybody help?

### What platform(s) does this occur on?

Not Applicable

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      npm: 8.15.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

not reproducible

**Comment by Simek** [comment]
Hello @Arnav7501, this reports lacks some information, for example which command you are trying to run, so determining if the problem you are experiencing is related to global installation, package manager or wrong usage. I would recommend following the installation guide agin, to ensure that you have everything setup correctly:
* https://docs.expo.dev/get-started/installation/

In general, GitHub issues are reserved for the reproducible bug reports. If you have a setup problem you should as a question on Discord or on forums.

**Comment by abidhasanchoudhury-cmd** [comment]
Gj
