### ISSUE TITLE
Sound playback rate not properly working on android 5.1

### ISSUE THREAD

**Issue by freitasjuciel** [expo/expo#2025]
for andoird version 5, when I change the playback rate of a sound, it some times works and some times not. But It works fine in android 7 and last ios.

the behavior is that after change the audio uri, the playback rate only take effect after the 3 attempt.
 

this is a snack that reproduces the error https://snack.expo.io/ByHynq747

**Comment by speedyankur** [comment]
Expo build is failing. Getting these error:-
Could not resolve all files for configuration ':expoview:releaseCompileClasspath'.
[stderr] > Could not find com.google.android.exoplayer:exoplayer-core:2.6.1.
