### ISSUE TITLE
Expo AV on Android. Error: com.google.android.exoplayer2.ExoTimeoutException: Player release timed out

### ISSUE THREAD

**Issue by lluisandreu** [expo/expo#20254]
### Summary

I am developing a fitness app which contains a series of exercises with a timeout. When the timeout is ended it navigates (navigation.replace()) to the same screen with a different exercise and video. 

The exercise screen contains a video mp4 from a local source. **Most of the time the video loads fine** but on some occasion the video generates an error from the "onError" method and does not load:

 **com.google.android.exoplayer2.ExoTimeoutException: Player release timed out.**
 
 I use a Redmi 9 Note Pro but I also experienced the same error in a Google Pixel.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.8.0 - /usr/local/opt/node@18/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.18.0 - /usr/local/bin/npm
      Watchman: 2022.08.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.6 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.7.0
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

`
    import { Video } from "expo-av";
    import { useCallback, useEffect, useRef, useState } from "react";
    import { Animated, useWindowDimensions, View } from "react-native";
    import { Asset } from "expo-asset";
    import videos from "../../utils/videos";
    import tw from "../../tailwind";
    import { breakpoint } from "../../utils/breakpoints";
  
    const AppVideo = ({
      videoKey = "f1",
      play = false,
      stop = false,
      flipHorizontal = true,
      setVideoLoaded = () => {},
      isLandscape = false,
    }) => {
      const { height, width } = useWindowDimensions();
      const videoRef = useRef(null);
      const [status, setStatus] = useState({});
    
      useEffect(() => {
        if (!!videoKey) {
          setVideo(videos[videoKey]); 
        }
    
        return !!videoRef.current
          ? async () => {
              try {
                await videoRef.current.unloadAsync();
              } catch {}
            }
          : undefined;
      }, [videoKey, videoRef.current]);
    
      useEffect(() => {
        (async () => {
          if (!!videoRef.current) {
            if (!!status && !status?.isPlaying && play) {
              await videoRef.current.playAsync();
            }
            if (!!status && status?.isPlaying && stop) {
              await videoRef.current.pauseAsync();
            }
          }
        })();
      }, [play, stop, videoRef.current, status]);
    
      const setVideo = async (key) => {
        await videoRef.current
          .loadAsync(key, {
            isLooping: true,
            rate: 1.0,
            isMuted: true,
            shouldPlay: true,
          })
          .then((resp) => {
            setStatus(resp);
          });
      };
    
      const handleVideoStatus = (status) => {
        setStatus(status);
        if (status.error) {
          throw Error(status.error);
        }
      };
    
      const getVideoSizes = () => {
      ...
      };
    
      return (
        <View
          style={tw.style({
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            flex: 1,
          })}
        >
          <Video
            onLoad={(status) => setVideoLoaded(status.isLoaded)}
            onError={(err) => console.error(err)}
            style={{
              ...getVideoSizes(),
              transform: [{ scaleX: flipHorizontal ? -1 : 1 }],
            }}
            ref={videoRef}
            resizeMode={"cover"}
            onPlaybackStatusUpdate={handleVideoStatus}
          />
        </View>
      );
    };
  
   export default AppVideo;
`

**Comment by JRParreno** [comment]
same issue here any solution?

**Comment by lluisandreu** [comment]
@JRParreno I had to move to react-native-video which works perfectly.

**Comment by JRParreno** [comment]
> @JRParreno I had to move to react-native-video which works perfectly.

it works in local video?
