### ISSUE TITLE
FileSystem.downloadAsync timing out with large file

### ISSUE THREAD

**Issue by doctorallen** [expo/expo#20262]
### Summary

When using the `FileSystem.downloadAsync()` function for a large file that takes longer than 60 seconds to download, the application throws a "nativeStackAndroid newTimeoutException"

From what I understand from the code [here](https://github.com/expo/expo/blob/main/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.kt#L1179-L1191) there is a hardcoded limit of 60 seconds.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 28.0.3, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

Because this requires a large file to function, I do not have a working Snack to provide, however the code is very straight-forward.
```
import * as FileSystem from 'expo-file-system'; 

const { uri } = await FileSystem.downloadAsync(
        "https://somedownloadlink.com",
        `${FileSystem.documentDirectory}/filename`
);
```

**Comment by mattyg** [comment]
+1 for the request to make the timeout configurable.

In case you need a quick workaround -- I've been using a downloadResumable to pause+resume the download when it fails with a timeout error.

**Comment by mattyg** [comment]
@doctorallen sorry this took me so long -- if its still useful to you or anyone else here's my rough implementation:

```javascript

class Downloader {
    downloads = {};
    sources = {};

    prepareDownloadResumable(source) {
        const remoteUrl = `https://example.com/${source.remotePath}`;
        let downloadResumable;

        // If previous download completed successfully, return raw contents
        if (this.downloads[source.id]) {
            return this.downloads[source.id];
        }
        // Else if previous download started, resume it
        else if (source.fileDownloadResumableJson) {
            const fileDownloadResumable = JSON.parse(source.fileDownloadResumableJson);

            downloadResumable = new FileSystem.DownloadResumable(
                fileDownloadResumable.url,
                fileDownloadResumable.fileUri,
                fileDownloadResumable.options
            );

            this.downloads[source.id] = downloadResumable;
        } 
        // Else setup a new resumable download & start
        else {
            const localUrl = `${FileSystem.documentDirectory}/${source.localPath}`;

            downloadResumable = FileSystem.createDownloadResumable(
                remoteUrl,
                localUrl,
                { md5: true, cache: true }
            );

            this.sources[source.id].fileDownloadResumableJson = JSON.stringify(downloadResumable.savable());
            this.downloads[source.id] = downloadResumable;
        }

        return downloadResumable;
    }
}

new Downloader().prepareDownloadResumable({
    localPath: 'blah.jpg',
    remotePath: 'files/blah.jpg',
    downloadResumable: undefined
});
```

**Comment by mattyg** [comment]
afaik this is still an issue
