### ISSUE TITLE
Expo Barcode scanner returns a different value for same barcode

### ISSUE THREAD

**Issue by LouisMuriuki** [expo/expo#20267]
### Summary

i am using expo barcode scanner to scan some barcode, when I scan the data value returned is different every time. I thought the barcode is supposed to have one unique number that does not change or am I wrong? here is my implementation

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

```
import { Button, StyleSheet, Text, View } from "react-native";
import React, { useEffect,  useState } from "react";
import { BarCodeScanner } from "expo-barcode-scanner";
import * as Haptics from "expo-haptics";
const Scanner = () => {
  const [hasPermission, setHasPermission] = useState(null);
  const [scanned, setScanned] = useState(false);
  const [data, setData] = useState(null);

  useEffect(() => {
    const getBarCodeScannerPermissions = async () => {
      const { status } = await BarCodeScanner.requestPermissionsAsync();
      setHasPermission(status === "granted");
    };
    getBarCodeScannerPermissions();
  }, []);

  const handleBarCodeScanned = ({ type, data }) => {
    try {
      console.log(type);
      console.log(data);
      setData(data);
      setScanned(true);
      Haptics.selectionAsync();
      // alert(`Bar code with type ${type} and data ${data} has been scanned!`);
    } catch (error) {
      alert(`we did not recognize the barcode.Please try again`);
      console.error("Unable to parse string: ", error);
    }
  };
  
  if (hasPermission === null) {
    return <Text>Requesting for camera permission</Text>;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }
  return (
    <View style={styles.container}>
      <BarCodeScanner
        onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
        barCodeTypes={[BarCodeScanner.Constants.BarCodeType.code93]}
        style={[StyleSheet.absoluteFillObject, styles.minicontainer]}
      />
      {scanned && <Button title={"Tap to Scan Again"} onPress={Rescan} />}
     
    </View>
  );
};

```
on the console.log(data) a different value is returned should it be this way? or is there something wrong somewhere.

ps: I do not have the barcode with me it was sent to me and , i am scanning them through my computer screen.Can this be the sure?

**Comment by aleqsio** [comment]
Hi @LouisMuriuki, thanks for filing the issue!

Barcodes are supposed to map to only one number. Perhaps the image or the screen you're scanning are a low enough quality where that causes multiple invalid bar reads and maps to a different number?

```
The barcode itself does not contain a check digit (in contrast to—for instance—[Code 128](https://en.wikipedia.org/wiki/Code_128)), but it can be considered self-checking on the grounds that a single erroneously interpreted bar cannot generate another valid character.
```

For a reproduction, we'd need to see the barcode causing issues and a confirmation that it scans correctly every time using other barcode scanners (Google Lens, other barcode apps).
