### ISSUE TITLE
'expo export' for EAS produces bundle that does not include 'extra' app config

### ISSUE THREAD

**Issue by jake-carpenter** [expo/expo#20261]
### Summary

I'm trying to set up a custom server to serve our OTA updates. We currently use EAS builds on our own infrastructure.

I have followed [the custom update server demo](https://github.com/expo/custom-expo-updates-server) but ran into issues with configuration not being included with the update. I feel like I'm missing a critical step here, but I can't find anything. Previously, `expo export` would create files like `ios-index.json`, but it no longer does that with `expo export --experimental-bundle`.

I have set up a [minimal repro](https://github.com/jake-carpenter/custom-expo-updates-server) to display a value configured in `app.json` and provided instructions for updating similar to the original demo:

1. Clone the project
2. Enter the client directory: `cd ./expo-updates-client`
3. `yarn install`
4. Run expo-dev-client to build for iOS: `yarn ios`
5. Verify "Hello, world!" greeting is shown with extra config when the debug app runs in the simulator
6. Kill expo run process
7. Open expo-updates-client directory in Xcode
8. Edit Scheme on the project and change build config from Debug => Release
9. Run project in Xcode
10. Verify "Hello, world!" greeting is shown with extra config when the RELEASE app runs in the simulator
11. Optionally, uncomment code in `App.js`
12. Switch to server directory: `cd ../expo-updates-server`
13. Init server project: `yarn install`
14. Run original script to build update and copy to server: `yarn expo-publish`
15. Run the update server `yarn dev`
16. Force close the RELEASE app in the simulator and re-launch
17. Note that the app has received update, but the greeting is blank and the extra config is empty.

#### Expected behavior
Upon updating, the repro app should continue to display:
```
Greeting: Hello, world! 

extra config: { "greeting": "Hello, world!" }
```

#### Actual behavior
Upon updating, the repro app displays: 
```
Greeting: 

extra config:
```

### What platform(s) does this occur on?

Android, iOS

### SDK Version

47, 46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
      Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/a089947/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 6.0.8

### Minimal reproducible example

https://github.com/jake-carpenter/custom-expo-updates-server

Instructions above & in README

**Comment by jake-carpenter** [comment]
After some additional research, I've discovered that the intention is to move those types of configuration values away from app.json/app.config.js and into environment variables per [Using environment variables with EAS Update](https://docs.expo.dev/eas-update/environment-variables/).

However, even after switching to app.config.js with a reference to `process.env.FOO` and trying with or without babel-plugin-transform-inline-environment-variables, I can't get any output from `FOO="bar" npx expo export --experimental-bundle` that has any reference to the environment variables referenced in app.config.js.

**Comment by douglowder** [comment]
Thanks for the repro, we will take a look.

**Comment by douglowder** [comment]
@wschurman could you please have a look at this one

**Comment by wschurman** [comment]
@jake-carpenter thanks for the report! This is currently being extensively discussed in https://github.com/expo/custom-expo-updates-server/issues/12#issuecomment-1334121928 (and subsequent comments).

> After some additional research, I've discovered that the intention is to move those types of configuration values away from app.json/app.config.js and into environment variables per [Using environment variables with EAS Update](https://docs.expo.dev/eas-update/environment-variables/).

I don't believe there's an effort to move those configuration values out of the app.json. I think the misalignment is more in the purpose of this repo. Originally it was designed to be a barebones implementation of the expo-updates protocol (which doesn't specify that the config must be embedded in update manifests). But I'm going to add some code that embeds it in the update manifests in this repo to demonstrate how it might be accomplished. Whether that is in `expo export` or just done via a script in this repo is yet to be decided.

Anyways, feel free to chime in or follow along on the linked issue.

**Comment by wschurman** [comment]
That being said, if `expo export` behavior has changed/broken from a previous version, feel free to re-open and tag me and I'll take a look into that separately.
