### ISSUE TITLE
[docs] update to installation steps for apple-authentication 

### ISSUE THREAD

**Issue by conor909** [expo/expo#20264]
### Summary

I was trying to implement Apple Sign In by following the docs for [apple-authentication](https://docs.expo.dev/versions/v47.0.0/sdk/apple-authentication/)

For many hours I was getting the following error related to app capabilities (testing on ios).
```
[AuthKit] Authorization failed: Error Domain=AKAuthenticationError Code=-7026 "(null)" UserInfo=....
```
I presumed adding the `expo-apple-authentication` to my plugins in `app.json` would add any capabilities config for me regarding Apple sign in.

I'm in a managed expo workflow, but because I was running out of ideas I clicked the link that says:
_"If you're installing this in a [bare React Native app](https://docs.expo.dev/introduction/managed-vs-bare/#bare-workflow), you should also follow [these additional installation instructions](https://github.com/expo/expo/tree/sdk-47/packages/expo-apple-authentication)."_

In the additional installation instructions, it says:
"For managed projects, set ios.usesAppleSignIn to true in app.json."

This solved that error (or at least I have a new error).  So I propose that managed workflow additional steps, should not be hidden behind a link for Bare Workflow projects.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/apple-authentication/

**Comment by amandeepmittal** [comment]
Hey @conor909, can you share a minimal reproducible example? Testing the instructions as described for a project in a managed project and using development build, I'm not able to reproduce the error you shared.

**Comment by amandeepmittal** [comment]
This issue has been resolved now. Docs for the latest SDK are up to date to reflect the info related to this issue.
