### ISSUE TITLE
Hermes degradation performance release build

### ISSUE THREAD

**Issue by yonitou** [expo/expo#20268]
### Summary

Hello, 
I'm using expo SDK 47 and wanted to try out Hermes engine. After I added the `jsEngine` flag to my app.config.ts I rebuilt my app with a custom dev build and experienced some big degradation performances. After some research I found out that this is "normal" since the debug build will not use all the benefits from Hermes. I built my app with an internal distribution build which is the build we are using before pushing to production and with a developmentClient set to `false` in eas.json. The performance drop is still there and I can't understand why ..
Could you help ? 

### What platform(s) does this occur on?

Android, iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /Users/yonitouboul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: * => 0.3.22 
      @expo/webpack-config: * => 0.17.3 
      expo: * => 47.0.6 
      react: * => 18.1.0 
      react-native: * => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Minimal reproducible example

Hard to give a reproducible example since it's a issue happening on release builds ..

**Comment by aleqsio** [comment]
Hi @yonitou!

Hermes isn't always an obvious and clear performance gain in some cases, so this might just be due to one of your dependencies not really benefiting from Hermes use.

Perhaps prebuilding your application, running it in Xcode and profiling it in release mode would give you more information about what dependency/screen/function could be causing these slowdowns.

Here's some guides on profiling applications:
https://docs.expo.dev/workflow/debugging/
https://fbflipper.com/docs/features/react-native/

**Comment by yonitou** [comment]
I just realised that if I run an expo publish command afterwards, metro is correctly bundling the app with bytecodes and it's not the case if I'm just running a build (the main bundle is written in JavaScript in this case). Could that be a fix ? Looks like the performances are slightly better ?
