### ISSUE TITLE
Uncaught Error: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by waynebloss** [expo/expo#2027]
I followed all of the advice in the last comment of #608 and here are the results.

1. There are no packager logs to speak of. The only output I get is `Building JavaScript bundle: finished in 1206ms.`
2. When I changed `dev=false` and `minify=true` in the `.expo/settings.json` file and restarted the project in Expo XDE, there was nothing new in the packager log output and the error still occurred. I also restarted Expo XDE.
3. So, I am opening an issue with more information.

- Here is my entire project - https://github.com/waynebloss/try-nativebase
- At this point my package.json only has essential packages as added by Expo (`expo@^28.0.0`, `react@16.3.1` and `react-native@https://github.com/expo/react-native/.....`).
- Before removing all non-essential packages, I tried locking native-base at "2.6.1" as mentioned in a StackOverflow question.
- I have tried both `npm` and `yarn`. I've tried clearing the cache with each of them, deleting their lock files and re-installing.
- I am on Windows Pro 10 v1803.
- I am using VSCode v1.25.1

**Comment by waynebloss** [comment]
Turns out the problem was that I moved `App.js` into `src/App.js` having followed [this post from December 2017](https://stackoverflow.com/questions/47742280/define-entry-point-for-react-native-app) about moving the entry point using the `entryPoint` key in the `app.json` file.

The actual method of changing the entry point was found [here](https://github.com/expo/expo-docs/issues/91#issuecomment-370973683).

**Comment by leimonio** [comment]
@waynebloss can you please share another link, this leads to a 404.

**Comment by waynebloss** [comment]
@leimonio They (the expo team) deleted that repository's issues, so I can't fix the link. However I think the information on how to change the entrypoint is also [here](https://github.com/expo/expo/issues/1034#issuecomment-447676334):

> just change the "main" in package.json to whatever you want but make sure to use https://docs.expo.io/versions/v31.0.0/sdk/register-root-component

**Comment by farhanaslam5151** [comment]
please anyone, i have the same error but failed to find the solution.

**Comment by markusohlen** [comment]
I got the same issue after using [@react-native-community/async-storage'](https://github.com/react-native-community/react-native-async-storage)

**Comment by farhanaslam5151** [comment]
My app works fine on expo client but when i create the expo build:android after creating it when i install the apk into device then it stopped working and giving this error.

**Comment by akinolu52** [comment]
same thing here @farhanaslam5151 

any solution?

**Comment by tchukuchuk** [comment]
Same problem here. Any help please ?

**Comment by WG75** [comment]
same issue

**Comment by farhanaslam5151** [comment]
not found any solution yet, app is working fine in expo client but when create the expo build for android, and install it into the android device it blinks on splash screens several times and then stopped working and when i press the view error log it shows me this error, i have changed the appEntry to src/index.js and in app.json "main":"src/index.js" but having the same issue, on all the latest versions of expo, react and react native sdkversion 32.0.0, also tried with yarn nothing happening good pleases anyone have solution???

**Comment by tchukuchuk** [comment]
@farhanaslam5151 : have you also an error message with babel :

`Uncaugh Error: undefined is not a function (near ‘…babelHelpers.applyDecoratedDescriptor…’)`

?

I tried to fix with this https://forums.expo.io/t/uncaugh-error-undefined-is-not-a-function-near-babelhelpers-applydecorateddescriptor/18399 , but it doen't work.

**Comment by farhanaslam5151** [comment]
any solution ??

**Comment by jonatahbrazz** [comment]
Facing the same problem. No workaround for this?

**Comment by Qurishe** [comment]
Hi, i had the same problem but then i figured it out here is what you should do:
In your App.js file import AppRegistry from react native.
Then write this code before export default App:
AppRegistry.registerComponent('Your project name", ()=>{App}
