### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by robozb** [expo/expo#20278]
### Summary

![Képkivágás](https://user-images.githubusercontent.com/8656998/204975253-97095397-ea92-4a0b-b9f0-3ce6619b8a9d.JPG)

### What platform(s) does this occur on?

iOS

### SDK Version

N/A

### Environment

PS C:\Users\Beci\Desktop\ReactNative\AwesomeProject> npx expo-env-info
Need to install the following packages:
  expo-env-info@1.0.5
Ok to proceed? (y) y

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 19.1.0 - C:\Program Files\nodejs\node.EXE 
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD    
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

npx create-expo-app AwesomeProject
npm start

**Comment by brentvatne** [comment]
you'll need to elaborate on your problem more clearly. a better place for this is forums. this does indeed work as expected, and so there is something else going with your particular setup, but there isn't anything anyone can do to help without information.

**Comment by robozb** [comment]
Dear @brentvatne! 

Ok, thank you! I'll try to clarify better my problem.

Thanks: Bela
