### ISSUE TITLE
Android: Video not loading

### ISSUE THREAD

**Issue by henrymoulton** [expo/expo#2028]
Continuing from #958 

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.4.0
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.2 AI-145.3276617

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/moultz-83fab029-b034-452d-b3e3-873eb7ea447b.tar.gz

Android Expo Client

### Steps to Reproduce

Load on iOS and Android devices

### Expected Behavior

Should load videos on both devices.

### Actual Behavior

Videos don't load on my LG Aristo, but do load in the Snack simulator?

#### iOS:

![img_1796](https://user-images.githubusercontent.com/30093692/43199909-7002f774-900b-11e8-89ac-ab25ee2faf79.jpg)

#### Android:

![screenshot_2018-07-25-04-43-18](https://user-images.githubusercontent.com/30093692/43199908-6feb82ba-900b-11e8-914c-b7f32ceea76b.png)

### Reproducible Demo

https://snack.expo.io/@moultz/androidvideobug

Try opening on various Android devices

**Comment by sjchmiela** [comment]
I was able to reproduce this issue by repeatedly refreshing the experience a couple of times. (On first run all the videos loaded successfully.)

I've seen recently a similar issue where the problem was that players instances were occupying limited system resources (media tracks). I'll run the Snack against native code with the bugfix applied and see whether it fixed issue reported.

**Comment by tslater** [comment]
Just to give more context on my experience. I've tried the videos with the native player, and they work fine. I've tried loading them locally, using "require", as well as from a web url and they both have the same behaviors: sometimes they never show, sometimes just a frame or two.

**Comment by sjchmiela** [comment]
By native player do you mean, like, a player in another app written _natively_?

**Comment by tslater** [comment]
I guess "stock" might be a better word? I checked, and it was the photos app. Here's a link to a video that is giving me trouble: https://drive.google.com/open?id=1wiSU6hoLC0Ct9tPQahOLGT4ZxLx6j8PP

**Comment by tslater** [comment]
It's working much better for me now. I used the "-movflags +faststart" in ffmpeg and it is much smoother.

**Comment by sjchmiela** [comment]
Ah, ok, I get it. 🙂 

Checked, https://github.com/expo/expo/commit/03cf0d218390cedfde59e7dce159633df73f2b6a did not fix this behavior and looking at the Android Profiler refreshing the experience bumps memory usage higher and higher. Something is definitely wrong! We'll investigate. 🙂

**Comment by henrymoulton** [comment]
Similar experience confirmed with the [Expo Playlist Example v28](https://github.com/expo/playlist-example/tree/e218da443939955663fe5201f8dea89f4b6cc9ac).

On iOS:
Initial Audio track loaded fine, pressing next loads the video:
```
[15:06:39] ON LOAD START
[15:06:47] ON LOAD : {"volume":1,"shouldCorrectPitch":true,"uri":"https://ia800501.us.archive.org/11/items/popeye_i_dont_scare/popeye_i_dont_scare_512kb.mp4","positionMillis":0,"durationMillis":366534,"hasJustBeenInterrupted":false,"playableDurationMillis":3008,"isBuffering":false,"progressUpdateIntervalMillis":500,"isMuted":false,"isLooping":false,"isPlaying":false,"target":10,"shouldPlay":false,"rate":1,"didJustFinish":false,"isLoaded":true}
```

on Android:
Initial Audio track loaded fine, pressing next doesn't load the video:
```
[15:07:38] ON LOAD START
[15:07:38] ON ERROR : Player error: null
[15:07:38] FATAL PLAYER ERROR: Player error: null
```

**Comment by henrymoulton** [comment]
Was reading through the code of the [Expo Playlist Example v28](https://github.com/expo/playlist-example/tree/e218da443939955663fe5201f8dea89f4b6cc9ac) and saw the following lines:

```
 // // UNCOMMENT THIS TO TEST THE OLD androidImplementation:
// androidImplementation: 'MediaPlayer',
```

When uncommented the video loads!

**Comment by sjchmiela** [comment]
Proper fix for ExoPlayer (i. e. `androidImplementation: MediaPlayer` commented out) has just landed in https://github.com/expo/expo/commit/4d21c67737f51a7f3255c03b3182bf80caf5df42, it will go out with SDK 29. 🙂

**Comment by henrymoulton** [comment]
Thanks @sjchmiela looking forward to it 🥇
