### ISSUE TITLE
Run FastLane Error, Build eas for ios simulator with firebase (auth)

### ISSUE THREAD

**Issue by BRaymond69** [expo/expo#20281]
### Summary

Hello, 
I m trying to build a crossplatform mobile application, my android build for emulator works well, but when it's come to build the ios app for emulator (for developping it s not the final version).
I need to build with expo because otherwise firebase will not be connected to the app.

My shell is correctly log to expo (expo whoami: gtlucci)

I follow this intruction:

1. I download GoogleService-Info.plist from my project settings on Firebase

2. I add it in my app.json

`"ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.ex.batch",
      "googleServicesFile": "./GoogleService-Info.plist"
    },`

3. I add the development on simulator on my eas.json
`{
  "build": {
    "development-simulator": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    }
  }
}`
4. After that I run the command: `eas build --profile development-simulator --platform ios`
5. Every step going well until the Run Fastlane
The build stop when its come to 
`
❌  (node_modules/react-native/React/Base/RCTModuleData.h:101:1)

   99 |  * queue and the module itself if they have not already been created.
  100 |  */
> 101 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  102 | 
  103 | /**
  104 |  * Whether the receiver has a valid `instance` which implements -batchDidComplete.

❌  (node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.h:33:1)

  31 | - (instancetype)initWithURL:(NSURL *)url __deprecated_msg("Use initWithURL:queue: instead");
  32 | /** @brief Must be set before -start to have effect */
> 33 | @property (nonatomic, strong) dispatch_queue_t delegateDispatchQueue __deprecated_msg("Use initWithURL:queue: instead");
     | ^ property with 'retain ' attribute must be of object type
  34 | 
  35 | @end
  36 | 

❌  (node_modules/@react-native-firebase/perf/ios/RNFBPerf/RNFBPerfModule.m:18:9)

  16 |  */
  17 | 
> 18 | #import <React/RCTConvert.h>
     |         ^ could not build module 'React'
  19 | #import <React/RCTUtils.h>
  20 | 
  21 | #import <Firebase/Firebase.h>`

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Here my package.json
`{
  "name": "batchr",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/material-bottom-tabs": "^6.2.4",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.4",
    "expo": "~46.0.16",
    "expo-dev-client": "~1.3.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-status-bar": "~1.4.0",
    "nativewind": "^2.0.11",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-animatable": "^1.3.3",
    "react-native-elements": "^3.4.2",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-heroicons": "^3.2.0",
    "react-native-maps": "0.31.1",
    "react-native-paper": "^4.12.5",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-picker-select": "^8.0.4",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-svg": "12.3.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.7",
    "tailwindcss": "^3.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~18.0.14",
    "@types/react-dom": "^18.0.8",
    "@types/react-native": "~0.69.1",
    "typescript": "~4.3.5"
  },
  "private": true
}`

**Comment by enipx** [comment]
Hi,

I was running into the same issue and, 

I updated my SDK from 46 to [47](https://blog.expo.dev/expo-sdk-47-a0f6f5c038af) and ensured I was using the latest version of [React Native Firebase](https://rnfirebase.io/#managed-workflow) (which requires the use_frameworks build config).

Then, I ran the eas build for IOS again, and that solved the problem.

Good luck.
