### ISSUE TITLE
No compatible apps connected. JavaScript Debugging can only be used with the Hermes engine.

### ISSUE THREAD

**Issue by juspeeh** [expo/expo#20280]
### Summary

I created a fresh expo project. Built Android development client APK. 

I have enabled Hermes according to the documentation here: https://docs.expo.dev/guides/using-hermes/

`eas build --profile devClient --platform android`

Installed it on physical Android device. Start dev client on my machine:

`npx expo start --dev-client`

Then connect the development client ( Scan QR code using Expo GO ). App loads fine but when I press "open JS debugger" the dev tools don't open and I get an console error.
`No compatible apps connected. JavaScript Debugging can only be used with the Hermes engine.`

The dev menu says try refreshing the app manually first for the debugger to work but that does not solve it for me.

Navigating to "home" in the development client after initial load and opening the metro again seems to solve this issue. Something seems off when starting the development client by scanning the QR code through Expo.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

```
  "dependencies": {
    "expo": "~47.0.8",
    "expo-dev-client": "~2.0.1",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "expo-splash-screen": "~0.17.5"
  },
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
      Watchman: 2022.10.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 26, 29, 30
        Build Tools: 29.0.2, 30.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: bare

### Reproducible demo

eas.json:
```
{
  "cli": {
    "version": ">= 2.8.0"
  },
  "build": {
    "devClient": {
      "distribution": "internal",
      "developmentClient": true,
      "android": {
        "buildType": "apk"
      },
      "ios": {
        "simulator": true
      }
    }
  }
}
```

app.json:
```
{
  "expo": {
    "name": "...",
    "slug": "...",
    "scheme": "...",
    "owner": "...",
    "version": "1.0.0",
    "orientation": "portrait",
    "userInterfaceStyle": "light",
    "jsEngine": "hermes",
    "extra": {
      "eas": {
        "projectId": "..."
      }
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "package": "...",
      "versionCode": ...
    }
  }
}
```

**Comment by Kudo** [comment]
i could repro the problem by chance. sorry for closing this.

**Comment by Kudo** [comment]
did you test it on an android emulator? when i test it on android emulator and load bundle on `http://10.0.2.2:8081`, that is a ip address the debugger cannot reach correctly. after you go back to home and load again, it can detect the LAN ip and it works. does it sound like what you came across?

**Comment by juspeeh** [comment]
I haven't tried it on android emulator but the issue sounds exactly the same I had on the physical device.

**Comment by OneHatRepo** [comment]
I'm facing this on a physical Android device with a custom development client, when Hermes engine is defined in app.json. Managed workflow. Navigating to "home" in the development client after initial load and opening the metro again does NOT solve this issue for me.

**Comment by OneHatRepo** [comment]
Update: pressing 'r' in **npx expo start** will cause the bundle to rebuild, and then pressing 'Open JS debugger' on Android will work, with the Chrome DevTools debugger opening (no error message this time), but I still can't debug, because the debugger doesn't show my source files, rather it shows a single main.jsbundle file.

**Comment by Slapbox** [comment]
@juspeeh thanks very much for reporting this issue.

@kudo thanks very much for the solution. I can confirm that's the issue.


----

@OneHatRepo if you can fix this on your device, you'll see two entries, one on your local network and one with a `10.0.x` address. Make sure to pick the local network entry.

Green will work. Red will fail.
![image](https://user-images.githubusercontent.com/6835891/209256475-e66e743a-ca4e-4309-8374-899877e83394.png)

**Comment by Slapbox** [comment]
Well, as soon as reloaded my project to take that screenshot and started back up with the `192.168.1.28` option, I get, `No compatible apps connected. JavaScript Debugging can only be used with the Hermes engine.`

We just upgraded from `47.0.3` where I never recall seeing this, to `47.0.9`. I wonder if some change in that period caused this issue.

**Comment by Slapbox** [comment]
@OneHatRepo also

> because the debugger doesn't show my source files, rather it shows a single main.jsbundle file.

This is a known issue. You need to reload the app from within the dev-client and then your source files should appear in the debugger. It's a huge pain.

**Comment by OneHatRepo** [comment]
> @OneHatRepo also
> 
> > because the debugger doesn't show my source files, rather it shows a single main.jsbundle file.
> 
> This is a known issue. You need to reload the app from within the dev-client and then your source files should appear in the debugger. It's a huge pain.

Reloading from within the dev-client doesn't work, as I still see only the single main.jsbundle file. Is there a Github ticket for the issue? I can't find it. The only way I can get things back into working order is to quit the terminal, quit Chrome, and then reload the dev-client and start all over. This is a major pain!

**Comment by irisjae** [comment]
@OneHatRepo I've faced a related issue and raised it on the Discord. I'm willing to open a GitHub issue, especially as GitHub is much more searchable, but not quite sure what to put for the "Reproduction". Here's the post containing the information and solution that I found out, in case it's helpful.

> Hi guys, wondering if any of you've faced issues with the Hermes JS Debugger? 
> I've been running into multiple issues and have attempted to find solutions for the whole day to no avail.
(I'm using a build with Expo 48 and expo-dev-client on the iOS Simulator) 
> 
> After I open the debugger (which appears to be some form of the Chrome DevTools, internally somehow hosted at chrome-devtools-frontend.appspot.com) from the development client and reload the app, I appear to be able to stop at "debugger" statements etc and work properly in the source-mapped files; I can see my source tree, my node_modules, and an index.bundle (presumably the bundled file) on the left pane.
> 
> However, debugging without source maps (for example, to set accurate breakpoints) does not seem to work.
> 
> After I reload the app once more again, the files in sources disappear and are replaced with a 'main.jsbundle'. It also appears to be some kind of bundle file. After the sources show main.jsbundle, the debugger stops appearing to be connected to what is running on the simulator. "debugger" statemnets don't seem to work. Still, the Execution Context selector in the Chrome DevTools still show "hermes".
> 
> Viewing the index.bundle in the DevTools sources does not allow me to debug properly. Whenever I open the file on the left pane, I am greeted with "ENOENT: no such file or directory, open '/Users/.../http:/<host>:<port>/index.bundle?platform=ios&dev=true&hot=false'"
> 
> After digging through many issues, it appears to be a Metro issue, of which a fix seems to have been shipped in 0.74 of metro (it seems to be related to sourcemaps; simply disabling sourcemaps does not resolve the issue). However, expo, react-native, and @react-native-community/cli-plugin-metro depend on the 0.73 version. Using "overrides" in package.json, I appear to be able to force the cli to use the latest (0.76) version of metro, which appears to resolve this; the ENOENT errors go away. However - 
> Opening the index.bundle in DevTools appear to show an empty file; it seems that it failed to load. From the Console tab, we find this:
> ```
> Failed to fetch source map http://<host>:<port>/index.map?platform=ios&dev=true&hot=false: remote fetches not permitted
> Failed to fetch source url http://<host>:<port>/index.bundle?platform=ios&dev=true&hot=false: remote fetches not permitted
> ```
> 
> 
> I have not been able to find mentions of such problems on the internet.
> 
> Inspecting the Chrome DevTool itself, I find that some errors are being emitted, unsure if they are related or of any importance:
> ```
> protocol_client.js:1 Protocol Error: the message with wrong id: {"result":{},"id":1}
> protocol_client.js:1 Protocol Error: the message with wrong id: {"result":{},"id":1000000000}
> protocol_client.js:1 Protocol Error: the message with wrong id: {"error":{"code":-32000,"message":"debugger can't perform cmd: in Running, expected paused"},"id":0}
> ```
> 
> 
> If any of you have faced similar symptoms, I would appreciate your help very much, thanks. 

> Ok, I seem to have found the solution to my problem
> For some kind of reason Metro explicitly crashes on anything other than localhost; simply comment these three lines https://github.com/facebook/metro/blob/5ff1cf984f3dd16e28a36c5a96cc7437d46021bd/packages/metro-inspector-proxy/src/Device.js#L577 (after applying my aforementioned metro version override) and debugging with Hermes actually works!

**Comment by OneHatRepo** [comment]
> > I appear to be able to force the cli to use the latest (0.76) version of metro, which appears to resolve this; the ENOENT errors go away. However -

@irisjae do you know what the package.json override was, specifically?

**Comment by Slapbox** [comment]
@OneHatRepo it will depend on your package manager. For Yarn you use `resolutions` and for npm you use `overrides` I believe. The solution would look something like `"**/package-name": "0.76.0"` and you'd place it into an object of the relevant name (resolutions or overrides.) Not sure for pnpm

**Comment by OneHatRepo** [comment]
I mean do you know the package name? I don't have a package for metro, so am not sure what to override.

**Comment by Slapbox** [comment]
I don't know exactly because I never tried that fix but I imagine the package-name is `metro` based on what I see installed on our machine.

![image](https://user-images.githubusercontent.com/6835891/233499631-ed912978-5681-4956-84f4-0a3e0af6e433.png)

**Comment by irisjae** [comment]
> > > I appear to be able to force the cli to use the latest (0.76) version of metro, which appears to resolve this; the ENOENT errors go away. However -
> 
> @irisjae do you know what the package.json override was, specifically?

I use npm for my package manager, and I've added overrides as [documented](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides), so that my package.json looks like this:

```
{
  "dependencies": { ... },
  "overrides": {
    "metro": "0.76.0"
  }
}
```

My understanding of the documentation is that regardless of whether metro is a direct dependency, this should override the metro version installed. It seems to work - (though, curiously I still see traces of the react-native specified version of metro in package-lock.json).

**Comment by irisjae** [comment]
It appears that the patch which I'm applying to the metro-inspector-proxy package can also be applied by Expo, among several other Expo modifications, by setting the environment variable EXPO_USE_CUSTOM_INSPECTOR_PROXY=1, according to [this](https://github.com/expo/expo/blob/1120c716f35cb28d88800e8f5d963d2b2ac94705/docs/pages/more/expo-cli.mdx) and the source code.

**Comment by nop33** [comment]
same issue here

**Comment by lucksp** [comment]
@Kudo this was marked closed.  What is the solution?  Is #22726 waiting to be released or is there an alternate workaround?

**Comment by jacob-israel-turner** [comment]
I'm still experiencing this issue on SDK 49.

**Comment by Slapbox** [comment]
I've stopped experiencing this but only because it no longer shows the option to use the debugger at all. There's definitely some remaining issues.

Even if #22726 fixed one aspect of this, the issue remains and over the years has cost me _days_ of work.

I think this should really be re-opened.

**Comment by Demianeen** [comment]
Same, the debugger opens, but the breakpoints do nothing

**Comment by charlestbell** [comment]
Same as @Nantris When you click that button, nothing happens. Please give a useful error so we can know what's going wrong.

**Comment by Nantris** [comment]
All I can recommend is to use Flipper. The Expo team won't even acknowledge these issues, much less address them.

The most frustrating thing is that no matter how many times I find a workaround to this, there's always an expiration date on that work around and then I have to go through it all again.

**Comment by theslyestguy** [comment]
I was able to resolve this issue by pressing 'r' to reload the app then pressing 'j' starts a connected chrome  devtools with the tsx loaded.

**Comment by Davidnr24** [comment]
Just in case someone encounters my error and I can save them 2 days of reading github issues:
My error message is similar but slightly different:

`No compatible apps connected, React Native DevTools can only be used with Hermes.`

Im using:

- expo go
- expo sdk 52
- wsl (windows subsystem for linux)

I was using `--tunnel` option (since wsl uses a different IP than my windows machine)

Well that was just the problem, for some reason the debugger wouldnt open when pressing 'j' while in `--tunnel` mode. 

If someone else is using wsl, or has this issue regardless, I fixed it by running on localhost, but specifying the IP with:

```REACT_NATIVE_PACKAGER_HOSTNAME=<windows_ip> npx expo start```

Then I also forwarded the 8081 port between wsl and windows to be able to use the windows IP (since my phone is connected to the same network as my windows laptop)

```netsh interface portproxy add v4tov4 listenport=8081 listenaddress=<windows_ip> connectport=8081 connectaddress=<wsl_ip>```

That fixed the issue and Im now able to use the debugger by pressing 'j'

**Comment by skipjack** [comment]
Ran into the same issue but not with `--tunnel` and the fixes above didn't work. What did work however was...

- Shutting down my expo go / metro server (i.e. ctrl + c the `npm start` process).
- Quitting the simulator entirely.
- `npm start`-ing again (allowing it to reopen the simulator).
- Hitting `j` again in the console (or cmd + d in the simulator and then hitting "open js debugger").

**Comment by ridafkih** [comment]
Running with `--localhost` fixed this issue for me.

**Comment by Miyou** [comment]
> Ran into the same issue but not with `--tunnel` and the fixes above didn't work. What did work however was...
> 
> * Shutting down my expo go / metro server (i.e. ctrl + c the `npm start` process).
> * Quitting the simulator entirely.
> * `npm start`-ing again (allowing it to reopen the simulator).
> * Hitting `j` again in the console (or cmd + d in the simulator and then hitting "open js debugger").

Thanks! Randomly had this start happening and restaring iOS simulator fixed it. Weird bug...

**Comment by onyedikachi23** [comment]
> did you test it on an android emulator? when i test it on android emulator and load bundle on `http://10.0.2.2:8081`, the ip address is that the debugger cannot reach correctly. after you go back to home and load again, it can detect the LAN ip and it works. does it sound like what you came across?

Simply closing the app and reopening fixed it for me.
