### ISSUE TITLE
Apple Sign not working with expo react native in TestFlight and Apple send me a review

### ISSUE THREAD

**Issue by iamemiliano** [expo/expo#20292]
### Summary

My apple sign in work fine on Expo Go and Simulator but when i want to connect with TestFlight, nothing happens. So Apple send me a review that : " We discovered one or more bugs in your app. Specifically, the app stays on the login screen when attempting to log in using Sign in with Apple. ". I don't know why this happen. My code :

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:               
    System:                                           
      OS: Windows 10 10.0.19042                       
    Binaries:                                         
      Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
    npmPackages:
      expo: 45.0.5 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: ^17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Minimal reproducible example

const loginWithApple = () => {
        const nonce = Math.random().toString(36).substring(2, 10);

        return Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256, nonce)
            .then((hashedNonce) =>
                AppleAuthentication.signInAsync({
                    requestedScopes: [
                        AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
                        AppleAuthentication.AppleAuthenticationScope.EMAIL
                    ],
                    nonce: hashedNonce
                })
            )
            .then(async (appleCredential) => {
                const { identityToken } = appleCredential;
                const provider = new firebase.auth.OAuthProvider('apple.com');
                const credential = await provider.credential({
                    idToken: identityToken,
                    rawNonce: nonce
                });
                await firebase.auth().signInWithCredential(credential).then((res) => {
                    const profileInfo = res.user.providerData[0];
                    const uid = res.user.uid;
                    let action = addUserOnFirestore(
                        uid,
                        profileInfo.email,
                        profileInfo.displayName?.split(" ")[0],
                        profileInfo.displayName?.split(" ")[2],
                        profileInfo.photoURL,
                        res,
                        props.navigation
                    );

                    setIsLoading(true);
                    try {
                        dispatch(action);
                    } catch (err) {
                        setError(err.message);
                    }
                    setIsLoading(false);
                });
                // Successful sign in is handled by firebase.auth().onAuthStateChanged
            })
            .catch((error) => {
                console.log('Error : ', error);
            });
    }

**Comment by mariomurrent-softwaresolutions** [comment]
This is not an expo issue.
If you use sign in with apple you need to provide instructions to the reviewers of your App how to sign in.

Otherwise apple reviewers won't know what credentials to use.

And it also says, that they tried to login but it was unsuccessful.
