### ISSUE TITLE
iOS ImagePicker default quality not applied

### ISSUE THREAD

**Issue by jackrr** [expo/expo#20299]
### Summary

`ImagePickerOptions` default `quality` value of `0.2` is not applied on iOS. Images are much larger in size than if I specify `quality: 0.2` as an explicit input on iOS. Experienced on [SDK v46](https://github.com/expo/expo/blob/sdk-46/packages/expo-image-picker/ios/ImagePickerOptions.swift#L18) , but source code appears to have the same issue on [SDK v47](https://github.com/expo/expo/blob/sdk-47/packages/expo-image-picker/ios/ImagePickerOptions.swift#L21).

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/revel/revel-expo/apps/driver/node_modules/.bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Minimal reproducible example

Feel free to auto-close since I don't really have the time to set up a demo at the moment. I'm unblocked, but would help other users of this expo plugin since the docs are not consistent with the behavior. Should be straightforward to see why this is happening (I'm not an iOS dev, but I think it's pretty clear from the linked source code that the default value is unused in both [SDK v46](https://github.com/expo/expo/blob/sdk-46/packages/expo-image-picker/ios/ImagePickerOptions.swift#L18) and [SDK v47](https://github.com/expo/expo/blob/sdk-47/packages/expo-image-picker/ios/ImagePickerOptions.swift#L21)...).

**Comment by behenate** [comment]
Hi, it seems like the default quality option works correctly for `.jpg` and `.png` files. The issue you described could appear when opening `.bmp` files. Previously setting any `quality` would convert the image to `.png` which would explain the smaller file size, but when quality wasn't set the image would remain as `.bmp`. In https://github.com/expo/expo/pull/21361 we updated the ImagePicker to ignore the `quality` option then opening `.bmp` files.
