### ISSUE TITLE
eas update and Updates.reloadAsync() causes camera to not work until the app is restarted.

### ISSUE THREAD

**Issue by JasonHenson** [expo/expo#20304]
### Summary

I am having an issue with Expo 47 and eas update where after I call Updates.reloadAsync() the camera no longer works. There isn’t a camera preview and the camera state is not ready.

I have to force close the app and re-open it to get it to work again. This only effects Android – IOS works fine. When I check logcat there isn’t any logs showing that the camera ever opens.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.7.0 - ~\node_modules\.bin\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      expo: 47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

Any project that uses expo-camera, that can push an eas update, and call Updates.reloadAsync() should cause the issue.

**Comment by JuarezCout** [comment]
I have the same problem with the same package versions!

**Comment by juspeeh** [comment]
For me the issue is more severe. The whole app becomes unresponsive, restarting the app solves the issue. I'm on bare workflow.

**Comment by andrewMatti** [comment]
I get the same problem. Anyone have a solution?

**Comment by JasonHenson** [comment]
No I did not still an issue.

**Comment by douglowder** [comment]
I will reopen this. Have any of you tried this with SDK 49?

**Comment by andrewMatti** [comment]
> I will reopen this. Have any of you tried this with SDK 49?

Thank you! I have not. Here's what I'm running:

"expo-camera": "^13.2.0", (also happens with 13.1.0)
"expo": "^47.0.0",
"expo-updates": "~0.15.6",

Whenever an android app downloads an OTA update, the camera will be blank unless the user force closes and then opens the app again. Here's the error I get:

> Call to function 'ExponentCamera.takePicture' has been rejected.
→ Caused by: Camera is not running

This doesn't happen with iOS.

**Comment by wschurman** [comment]
Thanks for the report! Please try again with the latest SDK (51 at the time of writing this) and re-file an issue if it's still occurring.
