### ISSUE TITLE
Android APK Build Size

### ISSUE THREAD

**Issue by sr3d** [expo/expo#2030]
I'm about to publish my app for deployment, and I built the APK for Android and it's about 31MB.  The app has only a few images and a set of custom font.

Per this article, https://medium.com/@aswinmohanme/how-i-reduced-the-size-of-my-react-native-app-by-86-27be72bba640  -- the author was able to eject the app and build the app separately for x86 and arm to reduce the size.

Is there a way Expo build service can provide the slim-down APK similar to what the article describes without having to eject and manually build the app?

**Comment by sr3d** [comment]
Looking further into getting the app built, I also wanted to add that currently, it seems like Expo doesn't support Build Schemes for iOS and Variants for Android.  I may have to eject and use ExpoKit.

https://medium.com/@ywongcode/building-multiple-versions-of-a-react-native-app-4361252ddde5

Going production-ready for an Expo app is quite complex because of the required process to be able to handle staging / beta / production, and OTA update for production app, and be able to push out new update of the app (e.g. v1 in production and v2 is still being developed, I need to be able to have staging/beta/production for v1 for maintenance and testing purposes, while another set of staging/beta/production for v2 for brand new functionalities)

Any recommendation is greatly appreciated.

**Comment by sr3d** [comment]
I just found this -- very helpful explanation on the status of trimming the build size:  https://expo.canny.io/feature-requests/p/reducing-app-size

**Comment by quinlanj** [comment]
hi @sr3d 
Regarding your question on app size: we are currently working on slimming down standalone builds by removing older SDK's, and by omitting unneeded modules when you use expokit in a detached project. (see https://forums.expo.io/t/ipa-file-is-too-large/11921/4 and https://docs.expo.io/versions/v29.0.0/expokit/universal-modules-and-expokit)

Regarding staging/beta with OTA updates: you can manage these with release channels (https://docs.expo.io/versions/v29.0.0/distribution/release-channels https://docs.expo.io/versions/v29.0.0/distribution/advanced-release-channels )

Close this github issue, if you have any additional questions, feel free to post them on our forums!

**Comment by sr3d** [comment]
@quinlanj thanks for the update.  v29 looks promising.  But is there a way to build multiple targets for the same app, e.g. having 3 separate binaries pointing to staging/beta/production without having to detach?  Currently, Expo can only build 1 single binary that would switch to the right channel at runtime.

**Comment by terribleben** [comment]
When you create a binary with `exp build`, several things get embedded in the native binary, including:

- The JS bundle with all your application logic
- All your assets you would need at runtime
- All your system assets (e.g. icons and launch screen resources)
- Any static configuration files (e.g. Info.plist on iOS)

So if you create three binaries with `exp build` all pointing to different release channels, you will effectively get three different apps. There's no need to detach for that use case. Hope that helps clarify.
