### ISSUE TITLE
Expo BarCodeScanner keeps camera open upon navigation

### ISSUE THREAD

**Issue by cw1997** [expo/expo#20319]
### Summary

I meet the same situation as the question on StackOverflow below,
https://stackoverflow.com/questions/72564091/expo-barcodescanner-keeps-camera-open-upon-navigation

The camera will not be closed after I navigate to other screens. How could I turn off the camera so that the statusbar does not show the icon that indicates the camera is being used?

### What platform(s) does this occur on?

Android, iOS

### Environment

    $ npx expo-env-info
    npm WARN using --force Recommended protections disabled.
    
      expo-env-info 1.0.5 environment info:               
        System:
          OS: Windows 10 10.0.19045                       
        Binaries:                                         
          Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
          npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD   
        npmPackages:
          expo: ^46.0.16 => 46.0.17                       
          react: 18.0.0 => 18.0.0 
          react-dom: 18.0.0 => 18.0.0                     
          react-native: 0.69.6 => 0.69.6 
          react-native-web: ~0.18.7 => 0.18.10            
        Expo Workflow: managed

### Minimal reproducible example

refer to the codes in https://stackoverflow.com/questions/72564091/expo-barcodescanner-keeps-camera-open-upon-navigation

**Comment by AndonMitev** [comment]
Same story happens only on android

**Comment by cw1997** [comment]
> i have this issues as well, camera keep working even if app is not open

Sorry, do you have found any solution to this issue? I have reposted this issue link to the official discord channel but nobody replied to me...   :-C

**Comment by 25khattab** [comment]
did anyone find a solution yet?
