### ISSUE TITLE
Default expo app stays awake, never goes to sleep

### ISSUE THREAD

**Issue by nmalzieu** [expo/expo#20328]
### Summary

I'm creating a new project with `create-expo-app`. Not changing anything in it.
Launching it with `yarn start` then scanning the QR Code on my iPhone 12 Mini.

It launches, but the app never goes to sleep (as if I had installed expo-keep-awake for instance)

Not sure at this point if it is only due to the fact that I'm running the app locally on my computer using Expo Go on iOS.
Haven't tested Android yet.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo": "~47.0.8"

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 3.5.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.11.0 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: managed

### Reproducible demo

https://github.com/nmalzieu/expo-awake-bug

**Comment by hirbod** [comment]
Expo does trigger expo-keep-awake in dev automatically. If you don't want that, you can exclude it from autolinking.
https://docs.expo.dev/modules/autolinking/

You can pass "expo-keep-awake" so it won't be included and executed.

**Comment by nmalzieu** [comment]
Got it! Thanks. I'm ok with having the expo keep awake active in dev actually, my fear was that it would also stay awake in my release.
Do you confirm that I have nothing more to do and that when I release my app expo keep awake will not be triggered by default?

Thanks @hirbod !

**Comment by amandeepmittal** [comment]
The `expo-keep-awake` behaviour is only true for development mode. I release/standalone app, you'll to have use its [API methods](https://docs.expo.dev/versions/latest/sdk/keep-awake) explicitly.

Also, you can use test your app while developing in [Production mode](https://docs.expo.dev/workflow/development-mode/#production-mode) which is the easiest way to simulate how your project will run on end users' devices.
