### ISSUE TITLE
Builds stuck in "Queue" for over an hour

### ISSUE THREAD

**Issue by karim-belhadjali** [expo/expo#20323]
### Summary

Trying to build by using exp build:android but now the builds go in queue and do not go from there. What used to take about 5 minutes to build is now sitting idle in the queue for over an hour, and it never starts. Cancelling the build and starting a new one does not help. Tried starting a build for a different project and had the same issue. Can this be related to my set up (Pasted below), or is it on the build-servers side?

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo": "~47.0.8",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5"

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Reproducible demo

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by karim-belhadjali** [comment]
Just a correction: I used eas build instead of expo build:android

**Comment by camnpr** [comment]
i'm run into this question too. point out is Build is waiting in the queue.

```txt
Status: Queued
Elapsed time: 50m 0s
```

**Comment by Simek** [comment]
Hello @karim-belhadjali, this repository is dedicated for Expo SDK, and we only accept bugs as an issues here. If you are experiencing issues with or have a question about EAS services you should use the support page
* https://expo.dev/support

Alternatively you can ask this question on our Discord or Forums.

**Comment by cerdikmehmet92-hash** [comment]
Neden yardımcı olmuyorsunuz
