### ISSUE TITLE
After Expo's app update QR scanning button is not working (Android)

### ISSUE THREAD

**Issue by ArtyomBaykov** [expo/expo#2034]
I am trying to click scan QR button for scanning like in the before but after the last ap update, that button is not working inside the expo app. I tried to remove and install it again but it's still not working. My phone is an android.

**Comment by kingsj** [comment]
I'm having this issue too, today. Is there anyway to install older versions of the app until this gets fixed?

**Comment by Abiaina** [comment]
If you email it to yourself and open the email on your phone you can access it on expo. I had this problem yesterday too.

**Comment by markmohr15** [comment]
same issue on android fwiw

**Comment by sjchmiela** [comment]
Happy to hear that! 🙂
