### ISSUE TITLE
expo-av 13.0.2 still crashes when ProGuard is enabled

### ISSUE THREAD

**Issue by gloredo** [expo/expo#20349]
### Summary

Is #20197 already bundled in `expo-av 13.0.2`? In the [changelog](https://github.com/expo/expo/blob/main/packages/expo-av/CHANGELOG.md) it says Unpublished. It still crashes for me on SDK 47 when ProGuard is enabled, I get `IllegalArgumentException expo.modules.kotlin.views.d$a in a. The required value was null.` from Sentry. It worked with SDK 46 and `expo-av 12.0.4`.

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 31
        Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: AI-212.5712.43.2112.8512546
    npmPackages:
      expo: ^47.0.0 => 47.0.6
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed
```

### Minimal reproducible example

1. `npx create-expo-app my-app`
2. `npx expo install expo-av expo-build-properties`
3. add in `app.json`: 
```json
  "plugins": [
    [
      "expo-build-properties",
      {
        "android": {
          "enableProguardInReleaseBuilds": true,
        },
      },
    ],
  ],
```
4. mount `Video` component with any `uri`
```js
import * as React from 'react';
import { Video } from 'expo-av';

export default function App() {
  return (
    <Video
      source={{
        uri: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
      }}
    />
  );
}
```
5. `eas build -e staging -p android`
6. app crashes when mounting `Video` component

[UPDATE]
As a workaround, I'm trying to use SDK 47 with `expo-av 12.0.4`, it works on Android but I get error on iOS. I'm looking into it.

[UPDATE 2]
SDK 47 with `expo-av 12.0.4` and `expo-dev-client 2.0.1` returns `Unhandled JS Exception: TurboModuleRegistry.getEnforcing(...): 'PlatformConstants' could not be found. Verify that a module by this name is registered in the native binary.` on iOS. I haven't found a solution.

[UPDATE 3]
[changelog](https://github.com/expo/expo/blob/main/packages/expo-av/CHANGELOG.md) is updated and #20197 is bundled in `expo-av 13.1.0` solving the issue.

**Comment by bananemo** [comment]
I'm also having the same problem. I'm using expo SDK 47 with `expo-av 13.0.2` and with ProGuard enabled, and keep getting the same error`IllegalArgumentException expo.modules.kotlin.views.e$a in a  The required value was null. ` from Sentry when I navigate to a screen with a Video component. 

@gloredo did you figure out a way to resolve it? Or just downgrade the `expo-av` package to version 12.0.4?

**Comment by gloredo** [comment]
> I'm also having the same problem. I'm using expo SDK 47 with `expo-av 13.0.2` and with ProGuard enabled, and keep getting the same error`IllegalArgumentException expo.modules.kotlin.views.e$a in a The required value was null. ` from Sentry when I navigate to a screen with a Video component.
> 
> I've fixed it by disabling proguard.
> 
> ```
>    [
>       "expo-build-properties",
>           android: {
>           // enableProguardInReleaseBuilds: true, (remove this line in app.config.ts)
>       },
>     ],
> ```

Yes, it works, but it's a bad solution. A better solution would be SDK 47 with `expo-av 12.0.4` and ProGuard enabled, I'm trying it now.

**Comment by getadapt** [comment]
I've tried the downgrading to 12.0.4 solution, works for android but means ios won't build, giving me `Build input file cannot be found:  VideoViewModule.swift`

Anyone else found this?

**Comment by Bardiamist** [comment]
I see many `Required value was null` crahses in prod. Bare react native project.

```
    "react-native": "0.70.6",
    "expo": "47.0.9",
    "expo-barcode-scanner": "12.1.0",
    "expo-camera": "13.1.0",
    "expo-local-authentication": "13.0.2",
    "expo-secure-store": "12.0.0",
```

No crashes in:
```
    "react-native": "0.70.5",
    "expo": "46.0.16",
    "expo-barcode-scanner": "11.4.0",
    "expo-camera": "12.3.0",
    "expo-local-authentication": "12.3.0",
    "expo-secure-store": "11.3.0",
```

**Comment by Bardiamist** [comment]
Looks update `expo` to `47.0.13` helped for me

**Comment by gloredo** [comment]
[changelog](https://github.com/expo/expo/blob/main/packages/expo-av/CHANGELOG.md) is updated and #20197 is bundled in `expo-av 13.1.0` solving the issue.

**Comment by dolapo-oluremi** [comment]
problem seem to persist.
