### ISSUE TITLE
expo-camera: Undefined symbols for architecture arm64.

### ISSUE THREAD

**Issue by vagnerwentz** [expo/expo#20350]
### Summary

On my project we installed the "expo-camera": "~12.4.0", and I have Macbook Pro M1 and after the installation I deleted the `Podfile.lock` and the `Pods` folder, and the `node_modules` folder. Then I executed `yarn` to install all dependencies and after that I executed the command `cd ios && arch -arm64 pod install && cd ../`, these steps they executed successfully but when I execute the `yarn ios` to run and open the iOS emulator somethings is compiled but at the end an error occurs with this message.

❌  Undefined symbols for architecture arm64
┌─ Symbol: _objc_msgSend$data
└─ Referenced from: l011 in EXCamera(EXCameraUtils.o)
❌  ld: symbol(s) not found for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

### What platform(s) does this occur on?

iOS

### Environment

```

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.7 => 0.69.7 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      expo-cli: 5.4.12
    Expo Workflow: bare
```

### Minimal reproducible example

Macbook M1 chip

**Comment by deemsang** [comment]
@vagnerwentz Did you find a solution?

**Comment by vagnerwentz** [comment]
> 

Unfortunately not

**Comment by vagnerwentz** [comment]
> @vagnerwentz Did you find a solution?
Unfortunately not.

**Comment by richardcoder** [comment]
same problem here with managed expo workflow, runing eas build -p ios shows the same error message in build details and the build failed.

**Comment by richardcoder** [comment]
> @vagnerwentz Did you find a solution?
I found in https://github.com/expo/expo/issues/20245, someone say expo sdk version and expo-camera version may influence the build result.

So I just upgrade to expo sdk 47.0.8 and expo-camera 13.1.0, and it successfully build, and I submit to testflight and test on my real iphone device, it works well. Maybe they fixed this Undefined symbols in new version, hope it helps.

reference:
https://blog.expo.dev/expo-sdk-47-a0f6f5c038af

**Comment by moygoca1** [comment]
I was having the same issue  and went with @richardcoder approach, I upgraded to Expo SDK 47.0.9  and expo-camera to 13.1.0 and the problem got resolved.

**Comment by adnan1naeem** [comment]
I have this issue in sdk46. How can i resolve it as i recently upgraded to expo sdk 46

**Comment by AzaelOValdo** [comment]
having the same issue, upgrading to sdk47 in my case is not an option :/
