### ISSUE TITLE
Emergency launch is now running often

### ISSUE THREAD

**Issue by TomasSestak** [expo/expo#20353]
### Summary

After update from SDK45 to SDK 47 and migration to eas update Emergency launch notifications often comes to our Sentry reports from android devices. Some devices seems to refuse to run in normal mode and run in emergency mode with every app launch.

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.1.2 - ~/.yarn/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

I wish I would have minimal reproducible example but I have no idea why is that happening and if any code we have in the app might have effect on this

packages we are using:
		"@expo-google-fonts/fira-sans": "^0.2.2",
		"@nandorojo/anchor": "^0.3.1",
		"@ptomasroos/react-native-multi-slider": "https://github.com/ptomasroos/react-native-multi-slider",
		"@react-native-community/datetimepicker": "6.5.2",
		"@react-native-community/netinfo": "6.0.0",
		"@react-native-google-signin/google-signin": "^9.0.0",
		"@react-native-masked-view/masked-view": "0.2.8",
		"@react-native-picker/picker": "2.4.8",
		"@react-navigation/bottom-tabs": "^6.4.1",
		"@react-navigation/native": "^6.0.14",
		"@react-navigation/stack": "^6.3.5",
		"@reduxjs/toolkit": "^1.9.0",
		"@segment/analytics-react-native": "^2.9.1",
		"@segment/sovran-react-native": "^0.4.5",
		"@sentry/react-native": "4.9.0",
		"axios": "^1.2.0",
		"buffer": "^6.0.3",
		"date-fns": "^2.29.3",
		"dayjs": "^1.11.6",
		"expo": "~47.0.8",
		"expo-apple-authentication": "~5.0.1",
		"expo-application": "~5.0.1",
		"expo-asset": "~8.6.2",
		"expo-blur": "~12.0.1",
		"expo-camera": "~13.1.0",
		"expo-clipboard": "~4.0.1",
		"expo-constants": "~14.0.2",
		"expo-crypto": "~12.0.0",
		"expo-dev-client": "~2.0.1",
		"expo-device": "~5.0.0",
		"expo-document-picker": "~11.0.1",
		"expo-file-system": "~15.1.1",
		"expo-haptics": "~12.0.1",
		"expo-image-picker": "~14.0.2",
		"expo-linear-gradient": "~12.0.1",
		"expo-linking": "~3.2.3",
		"expo-local-authentication": "~13.0.2",
		"expo-media-library": "~15.0.0",
		"expo-modules-core": "~1.0.3",
		"expo-notifications": "~0.17.0",
		"expo-sharing": "~11.0.1",
		"expo-splash-screen": "~0.17.5",
		"expo-status-bar": "~1.4.2",
		"expo-system-ui": "~2.0.1",
		"expo-tracking-transparency": "~3.0.1",
		"expo-updates": "~0.15.6",
		"expo-web-browser": "~12.0.0",
		"html-entities": "^2.3.3",
		"just-clone": "^6.1.1",
		"lodash.debounce": "^4.0.8",
		"lottie-react-native": "5.1.4",
		"react": "18.1.0",
		"react-hook-form": "^7.39.5",
		"react-native": "0.70.5",
		"react-native-collapsible": "^1.6.0",
		"react-native-confirmation-code-field": "^7.3.1",
		"react-native-dropdown-picker": "^5.4.3",
		"react-native-fbsdk-next": "^11.1.0",
		"react-native-gesture-handler": "~2.8.0",
		"react-native-get-random-values": "~1.8.0",
		"react-native-keyboard-aware-scroll-view": "^0.9.5",
		"react-native-mmkv": "^2.5.1",
		"react-native-qrcode-svg": "^6.1.2",
		"react-native-reanimated": "~2.12.0",
		"react-native-reanimated-carousel": "^3.1.5",
		"react-native-redash": "^18.1.0",
		"react-native-render-html": "^6.3.4",
		"react-native-responsive-screen": "^1.4.2",
		"react-native-safe-area-context": "4.4.1",
		"react-native-screens": "~3.18.0",
		"react-native-svg": "13.4.0",
		"react-native-view-shot": "3.4.0",
		"react-native-webview": "11.23.1",
		"react-redux": "^8.0.5",
		"redux-persist": "^6.0.0",
		"rn-pdf-reader-js-improved": "^1.0.0",
		"rodnecislo": "^1.6.0",
		"sentry-expo": "~6.0.0",
		"styled-components": "^5.3.6",
		"styled-system": "^5.1.5",
		"uuid": "^9.0.0"

**Comment by douglowder** [comment]
Since this is happening only on some devices, and there is no repro, it will be difficult for us to investigate this. If there is anything else that might help (e.g. something else that the affected devices have in common, something else in the Sentry logs), please let us know.
