### ISSUE TITLE
Barcode value is different  in android or ios 

### ISSUE THREAD

**Issue by meet2amit** [expo/expo#20356]
### Summary

@cruzach @Thibaultferre @kalin @fks6 @croaky  

Hello team

Please check below image
![image](https://user-images.githubusercontent.com/1227685/206153753-661b8d15-277a-45b4-9e2b-0e685e204360.png)

We used **expo-barcode-scanner** which got correct barcode in android 
But in IOS it is added one ZERO at starting  

Any one know solution then please suggest us.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    **System:**
      OS: Windows 10 10.0.19044
    **Binaries:**
      Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    **SDKs:**
      Android SDK:
        API Levels: 30, 33
        Build Tools: 30.0.2, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    **IDEs:**
      Android Studio: AI-212.5712.43.2112.8609683
    **npmPackages:**
      expo: ~45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    **Expo Workflow:** managed

### Minimal reproducible example

just need to scan this given image and will get issue in IOS

**Comment by iegik** [comment]
I see 12 numbers here. Is this correct EAN-13?

**Comment by meet2amit** [comment]
@iegik 

Yes our product have 12 number 
It working fine with android

**Comment by iegik** [comment]
https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

Dont see that iOS supports upc_ean (not sure, that it is what you want, but this is only upc*, that not A or E)
