### ISSUE TITLE
Play base64 string with Expo.Audio.Sound

### ISSUE THREAD

**Issue by VladimirJarabica** [expo/expo#2035]
Hello
I have this snack:  
https://snack.expo.io/SkHpBOPVX  
I have problem using `playFromString` function, which takes base64 string as uri.  

It works correctly on simulator (simulator in snack goes correctly but ofc I can't hear the sound. But my local simulator plays the sound correctly).    
However I can't play it on mobile (ios). It throws this error:  
```
Error: An unknown error occurred (-12420) - The AVPlayerItem instance has failed with the error code -11800 and domain "AVFoundationErrorDomain".
    at loadError (Sound.js:168)
    at MessageQueue.__invokeCallback (MessageQueue.js:398)
    at MessageQueue.js:137
    at MessageQueue.__guardSafe (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:70
```
I think I have setup correct, because the `playFromUrl` works ok everywhere.

Is this source type supported? Or should I somehow allow it in configuration?

Thanks.

**Comment by terribleben** [comment]
I'm not sure we actually support this use case. I'm kind of surprised it works in simulator. The docs say 
> A dictionary of the form { uri: 'http://path/to/file' } with a network URL pointing to an audio file on the web.

**Comment by sjchmiela** [comment]
Hey, @VladimirJarabica! We do not support playing audios from Base64 strings directly, but soon (when SDK31 is released) you'll be able to write the string to a file with
```js
await FileSystem.writeAsStringAsync(uri, base64String, {
  encoding: FileSystem.EncodingTypes.Base64,
});
```
and then play the sound from file!

Please see https://github.com/expo/expo/pull/2328 and https://github.com/expo/expo-docs/commit/d086767a28805b72768a46988cc3f37e041f63f8 for details. 👀 

I'll let myself close this issue, I hope using new FileSystem features will work out for you! If you encounter any problems feel free to open new issues. 🙂
