### ISSUE TITLE
expo-notifications not showing notifications in foreground even with setNotificationHandler

### ISSUE THREAD

**Issue by Nefiich** [expo/expo#20351]
### Summary

I have setup the Expo-Notifications, and I'm using local notifications as reminders, all works well until I need a notification to show while I'm inside the app. The notification always shows while the app is in background but I can't get it to work in the foreground.

### SDK Version

46.0.16

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.17.0 - /usr/local/bin/npm
      Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8

### Minimal reproducible example

App.tsx:

```
import * as Notifications from "expo-notifications";

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: false,
  }),
});


const App = () => {

  const notificationListener = useRef();
  const responseListener = useRef();
  const [notification, setNotification] = useState(false);


    useEffect(() => {
      const getPerm = async() => {
        const { status: existingStatus } = await Notifications.getPermissionsAsync();
        let finalStatus = existingStatus
        if(existingStatus !== 'granted'){
          const { lastStatus }:any = await Notifications.requestPermissionsAsync();
          finalStatus = lastStatus
        }
        if (finalStatus !== "granted") {
          console.log("Failed to get push token for push notification!");
          return;
        }
      }
      getPerm()

      notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
        setNotification(notification);
        console.log("NOTIF: ", notification)
      });
  
      responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
        console.log("RES: ",response);
      });
  
      return () => {
        Notifications.removeNotificationSubscription(notificationListener.current);
        Notifications.removeNotificationSubscription(responseListener.current);
      };
    }, []) ....
```
How I schedule the notification in a different file:

```
const triggerNotifications = async () => {
    await Notifications.scheduleNotificationAsync({
    content: {
        title: "You’ve got mail! 📬",
        body: "Here is the notification body",
        data: { data: "goes here" }
    },
    trigger: { seconds: 5 },
    });
}
```

**Comment by C3sarRC** [comment]
I am facing the same problem, the notifications seems to work for me with the expo notifications tool, but when app is in foreground they are never touching handleNotification function in Notifications.setNotificationHandler, not sure what might be issue

**Comment by mamedia-edv** [comment]
+1 Can confirm the issue

**Comment by C3sarRC** [comment]
> I am facing the same problem, the notifications seems to work for me with the expo notifications tool, but when app is in foreground they are never touching handleNotification function in Notifications.setNotificationHandler, not sure what might be issue

Guys i checked out not sure if it will be the same for you but i realized they are working, but they are not when the debugger is on

**Comment by LagoonProject** [comment]
> > I am facing the same problem, the notifications seems to work for me with the expo notifications tool, but when app is in foreground they are never touching handleNotification function in Notifications.setNotificationHandler, not sure what might be issue
> 
> Guys i checked out not sure if it will be the same for you but i realized they are working, but they are not when the debugger is on

Hi, I have the same issue. Please, what do you mean by "when the debugger is on"? What debugger are you refering to?

**Comment by paradise** [comment]
+1 for me on android. When app is in foreground, I see notification in the status bar, but notification popup does not appear. My setup is default from expo docs.

**Comment by lloydraj** [comment]
> +1 for me on android. When app is in foreground, I see notification in the status bar, but notification popup does not appear. My setup is default from expo docs.

@paradise I faced the same issue. 

When used the following settings (default from expo docs, the notification showed in the status bar and tray but didn't appear in the app)

  Notifications.setNotificationHandler({
    handleNotification: async () => ({
      shouldShowAlert: true,
      shouldPlaySound: false,
      shouldSetBadge: false,
      // priority: 'high',
    }),

But when I put shouldPlaySound as 'true', it appeared in both the status bar, tray and the app.

  Notifications.setNotificationHandler({
    handleNotification: async () => ({
      shouldShowAlert: true,
      shouldPlaySound: true,
      shouldSetBadge: false,
      // priority: 'high',
    }),
    
    
  });

**Comment by robinclaes** [comment]
Too be fair it's a little rough to make a reproducible example here, as it is linked to your Push Notification service.
I changed `shouldPlaySound` from `false` to `true` and the notification showed in the foreground. 
Before that it did not.

This issue really should not be closed.

**Comment by dcposch** [comment]
### Check whether `Sleep Focus` or DnD is on

Turns out that suppresses *all* notifications, even silent ones & even while the app is foregrounded.

**Comment by anasalaqeel** [comment]
> +1 for me on android. When app is in foreground, I see notification in the status bar, but notification popup does not appear. My setup is default from expo docs.

for me I have the same issue, so I ended up to use define `sound` property and make it null for android and default for ios, i don't know why should i define `sound` property to see the notification but it is what it is 

Example: 
```js
await Notifications.scheduleNotificationAsync({
        content: {
          title: "Time is done!",
          body: "Hello",
          sound: Platform.OS === "android" ? null : "default",
        },
        trigger: {
          seconds: 60,
        },
```

**Comment by nicholas-masini** [comment]
I have the same issue on Android, however with the following Notification Handler it's still not working on the foreground..

`
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: true,
  }),
});
`

**Comment by ademartini** [comment]
I'm experiencing this same issue.  For some reason it seems to work better with a custom dev build.  Has anyone learned more about this issue?

**Comment by Elozino** [comment]
I also have the same issue and had to reopen the issue

**Comment by erzaehlsalex** [comment]
I had exactly the same version with the latest lib version, so I downgraded to `0.20.1`, as it was released in the time people here reported it was working. And great news, showing notifications also works for me with this version.

**Comment by blackmax1886** [comment]
same issue on Android.
I try to customize notification sound.
I send push notification via postman, it works well when the app is background, not foreground.
When the app is foreground, I got no body, no title, default sound notification.

**Comment by AllanBengco** [comment]
> same issue on Android. I try to customize notification sound. I send push notification via postman, it works well when the app is background, not foreground. When the app is foreground, I get no body, no title, default sound notification.

I am experiencing the same thing on an internal android build and using Expo SDK 49. Notification is working as expected when app is in the background or not running, but when app is foregrounded, there is notification but without the content. Only the app icon is visible in the Alerting Notifications of the phone.

**Comment by scd8418** [comment]
I have the same issue. Push notifications are working fine when the app is not in the foreground, but I don't get notifications when it is running foreground. My code is pretty much by the book, but I never see a handleNotification call execute. 

The expo example available in snack also fails for me on two different iphones. Perhaps the same problem?

https://docs.expo.dev/versions/latest/sdk/notifications/#usage

**Comment by aviattri** [comment]
experiencing the same issue here

**Comment by vy-levyy** [comment]
I have the same issue

**Comment by scd8418** [comment]
If you run the basic example from the documentation and run a development build on your phone, you do not get push alerts when the app is on foreground. It simply doesn't work. This is not isolated to Expo Go although it doesn't work there either. My production app works fine and I get the appropriate callbacks, but debugging is really a pain.

**Comment by ArtoszBart** [comment]
Same issue here. SDK 50, expo-notifications: ~0.27.6 and ^0.27.6

**Comment by EmanuelU** [comment]
Same issue here

**Comment by dpuckett** [comment]
Same issue here as well. Please can this be looked at now...

**Comment by Nefiich** [comment]
I think the team that worked after me on this project discovered a temp fix that involved using a different "slug" in app.json for Android and iOS. I'm not on that project anymore so I can't verify it.

**Comment by Aman-Sidd** [comment]
Facing the Same issue in my project based on SDK 50.

**Comment by andrewboles** [comment]
Same issue, please take a look at this

**Comment by lgrube3** [comment]
Are push notifications not a huge selling point of Expo? I would think this would be a priority to fix.

**Comment by f-ricci** [comment]
I had the same issue, I disabled the Focus Mode from my iPhone and I can see the push notifications popping up.

**Comment by Ritcheyy** [comment]
I am also experiencing this issue... Here is the 'hack' that worked for me:


```
Notifications.setNotificationHandler({
  handleNotification: async (notification) => {
    // Manually display the notification for Android - till foreground issue is resolved

    const isManualAndroidNotification = Platform.OS === 'android' && !notification.request.trigger;
    if (Platform.OS === 'android' && notification.request.trigger) {
      const appNotification = notification.request.trigger['remoteMessage'].notification;
      await Notifications.scheduleNotificationAsync({
        content: {
          title: appNotification?.title || '',
          body: appNotification?.body || '',
          sound: true,
        },
        trigger: null,
      });
    }

    return {
      shouldShowAlert: Platform.OS === 'ios' || isManualAndroidNotification,
      shouldPlaySound: Platform.OS === 'ios' || isManualAndroidNotification,
      shouldSetBadge: false,
    };
  },
});
```

This is basically to stop the automatic notification that comes without any preview on android, but manually trigger a new notification from the client side with the same details (since for some reasons, notification works well if triggered with the `Notifications.scheduleNotificationAsync` method)

Note: make sure to use `!notification.request.trigger ` else you're going to be caught up in a notification loop.

**Comment by linhnph05** [comment]
Same issue here, luckily I found this issue so I dont have to submit another same one. Expo team please help us

**Comment by linhnph05** [comment]
Hi everyone, I solved the issue.I just upgrade expo-notifications to 0.28.15 and use sound when set the notification plus I also place the Notifications.setNotificationHandler in the main App.js. Here is the snack I create myself: https://snack.expo.dev/@leonguyen05/expo-notifications-foreground?fbclid=IwY2xjawEivTRleHRuA2FlbQIxMAABHRidpDvdSgt7FxZUosgE19d6SRECosp0FRPgsd4wWAonDmOmUI41ENN7QQ_aem_GM0zwWgeNbWnbTvbjUCACQ

**Comment by GrimDev** [comment]
Same issue on expo 51 & expo-notifications 0.28.15

Perfectly work in background & killed

But nothing in foreground

```js
Notifications.setNotificationHandler({
	handleNotification: async (notification) => {
		console.log(notification) // Never called
		return ({
			shouldShowAlert: true,
			shouldPlaySound: true,
			shouldSetBadge: false,
		})
	},
})

// In my component
notificationListener.current = Notifications.addNotificationReceivedListener((notification) => {
    console.log('---1', notification) // never called
})
responseListener.current = Notifications.addNotificationResponseReceivedListener((response) => {
    console.log('---2', response) // never called
})
```

**Comment by linhnph05** [comment]
Have you tried my snack @GrimDev

**Comment by guimendiacastro** [comment]
Has anyone figured out how to get it working?

**Comment by linhnph05** [comment]
> Hi @linhnph05, I just tried your snack but it still isn't working for me. I copied my expo push token and used the Expo Push Notification Tool to send it while the app (Expo Go) was in the foreground, but I received nothing. It does work in the background fine. I am using iOS version 17.6.1

Sorry, my snack just demo the local notification, not sending notification through a server.

**Comment by DikDns** [comment]
I encountered this issue in Expo ^51.x.x and expo-notifications ^0.28.16. When I downgraded to Expo ^50.0.21 and expo-notifications ~0.27.8, I had to remove expo-dev-client due to a duplicate Expo dev menu. I'm not sure if this is related to the problem, but at least the notification foreground handler works again!

**Comment by DikDns** [comment]
Yes, @jahaskell53, I'm referring to notifications that are received when the app is in the foreground.

**Comment by PatoGordo** [comment]
Same problem, any fix or work around for it?

**Comment by wolak** [comment]
Same, cannot get any sort of notficiation/logs when app is in the foreground. It did work on an emulator but not on a physical device with a development build if that helps.

**Comment by douglowder** [comment]
This problem does not reproduce in our testing. When we schedule notifications, we do see them show up as expected when the app is in the foreground, on real iOS and Android devices with development and release builds.

For some of the trigger types (daily, weekly, yearly), a `repeats: true` property must be added to the trigger to satisfy the current trigger types, see https://github.com/expo/expo/issues/30577 .

**Comment by Manezly** [comment]
> This problem does not reproduce in our testing. When we schedule notifications, we do see them show up as expected when the app is in the foreground, on real iOS and Android devices with development and release builds.
> 
> For some of the trigger types (daily, weekly, yearly), a `repeats: true` property must be added to the trigger to satisfy the current trigger types, see #30577 .

Hi Doug, are you able to check for Chrome OS? I'm unable to get notifications to pop-up when the app is in the foreground of a Chromebook.

**Comment by Audeos** [comment]
I am having the same problem. All good until the release build foreground notifications. There is clearly something. Some people turn some boolean to true and make it work, some turn it to false, some add code and some remove... But none of the answers in the internet worked for me. There is really a confusion here. I'm considering to replace it with another push notification package.

**Comment by nodespell** [comment]
Same issue here, tried everything proposed in the thread but nothing works.

**Comment by Audeos** [comment]
I was using firebase messaging behind it. I changed my notification provider to Notifee, but even that didn't work at first. I managed to build it with using a mix of both firebase messaging's catchers and Notifee's catchers. And firing Notifee's notifications when caught.

**Comment by pennersr** [comment]
This is definitely a bug in expo-notifications, please re-open. The problem code is this bit:

https://github.com/expo/expo/blob/main/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ExpoNotificationBuilder.kt#L122

``` kotlin
    val shouldPlayDefaultSound = shouldPlaySound() && content.shouldPlayDefaultSound
    if (shouldPlayDefaultSound && shouldVibrate()) {
      builder.setDefaults(NotificationCompat.DEFAULT_ALL) // set sound, vibration and lights
    } else if (shouldVibrate()) {
      builder.setDefaults(NotificationCompat.DEFAULT_VIBRATE)
    } else if (shouldPlayDefaultSound) {
      builder.setDefaults(NotificationCompat.DEFAULT_SOUND)
    } else {
      // Notification will not vibrate or play sound, regardless of channel
      builder.setSilent(true)
    }
```

You will end up in the `setSilent(true)` branch when you have a notification with a custom sound. Because, in that case, `shouldPlayDefaultSound` will be `false`, and above logic will incorrectly conclude that:

>   Notification will not vibrate or play sound, regardless of channel

You can fix this by changing the `setSilent()` line into:

``` kotlint
builder.setSilent(!shouldPlaySound())
```

**Comment by MobileMon** [comment]
local notifications show when in the foreground but firebase messaging notifications not showing when in foreground
