### ISSUE TITLE
Problem installing EXPO XDE in Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by jsnavarroc** [expo/expo#2036]
Hello, I have a problem when I try to run the app in emulation of Genymotion EXPO XDE in Ubuntu 16.04.4 LTS (Xenial Xerus),  this is the problem:

```
Couldn't start project on Android: ADB server didn't ACK
* failed to start daemon *
error: 
error:

```
<a href="https://ibb.co/imeEPT"><img src="https://preview.ibb.co/cNaojT/2018_07_26_12_54_10_c67e63a153c7f6e28e50fcc657f350e6.png" alt="2018_07_26_12_54_10_c67e63a153c7f6e28e50fcc657f350e6" border="0"></a>
There are more people that has de same problem: https://stackoverflow.com/questions/51128903/expo-genymotion-throws-adb-server-didnt-ack-when-running-project

Please Help me!

**Comment by quinlanj** [comment]
hi @jsnavarroc , 
Does killing the adb process help? (ie) running `adb kill-server` or finding the process yourself and killing it via taskmanager/`kill`
https://stackoverflow.com/questions/26217055/adb-server-didnt-acknowledge
https://stackoverflow.com/questions/2306322/adb-wont-start

Also, OP from the SO you linked had a different fix -- did that work?

**Comment by jakubste** [comment]
XDE is now deprecated in favour of expo-cli so going to close this issue.
