### ISSUE TITLE
NODE_ENV is always 'production' in eas `--local` builds

### ISSUE THREAD

**Issue by iegik** [expo/expo#20360]
### Summary

When running `npx expo start` NODE_ENV === 'development'.
But NODE_ENV is always set to 'production' when running eas build with `--local` flag:

```
npx eas-cli build -p android --profile preview --local
```

Tried:
- `export NODE_ENV="development" && ...`
- `NODE_ENV="development" ...`
- `--dev` flag not supported
- `.env` not used
- injecting `process.env.NODE_ENV='development'` in app.config.js not work everywhere:

```
process.env.NODE_ENV = 'development';

export default ({ config }) => ({
  ...config,
});
```

### SDK Version

46

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
      Watchman: 2022.10.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/me/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.17 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Minimal reproducible example

```
npm i -g expo-cli
npx create-expo-app my-app
...
npx eas-cli build -p android --profile preview --local
```

eas.json
```
{
  "cli": {
    "version": ">= 2.7.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

in `app.json` `slug`, `package` and `projectId` are only changed

App.jsx
```
      <Text>NODE_ENV: {process.env.NODE_ENV}</Text> // is always 'production'
```

**Comment by iegik** [comment]
https://github.com/expo/expo/issues/11814#issuecomment-791134457

**Comment by iegik** [comment]
https://github.com/expo/expo/issues/14759

**Comment by iegik** [comment]
"Channels" and NODE_ENV are not the same thing, isn't it? https://docs.expo.dev/build/updates/#updating-managed-apps-built-with-eas-build

**Comment by iegik** [comment]
The same issue with eas update noticed https://docs.expo.dev/eas-update/how-eas-update-works/#distributing-builds

**Comment by iegik** [comment]
I guess, I found it:

https://github.com/expo/expo/blob/a486cf8566e01e01fb506b5f33dcc2bc85b67d32/packages/%40expo/cli/src/start/server/webpack/WebpackBundlerDevServer.ts#L348

where inside `setMode` sets `process.env.NODE_ENV` and `process.env.BABEL_ENV`!

https://github.com/expo/expo/blob/a486cf8566e01e01fb506b5f33dcc2bc85b67d32/packages/%40expo/cli/src/start/server/webpack/WebpackBundlerDevServer.ts#L389

https://github.com/expo/expo/blob/a486cf8566e01e01fb506b5f33dcc2bc85b67d32/packages/%40expo/cli/src/start/server/webpack/WebpackBundlerDevServer.ts#L390

**Comment by iegik** [comment]
> ERROR  Error: React Refresh runtime should not be included in the production bundle.
 ERROR  Error: Requiring module "node_modules/react-native/Libraries/Core/InitializeCore.js", which threw an exception: Error: React Refresh runtime should not be included in the production bundle.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by iegik** [comment]
Related: [Setting NODE_ENV to test has unintended side effects](https://github.com/facebook/jest/issues/3370)

**Comment by iegik** [comment]
@selimjouan, none of the methods worked

**Comment by selimjouan** [comment]
> @selimjouan, none of the methods worked

It is because you read NODE_ENV from ´process.env´, you need to read it from ´Constants.expoConfig.extra´: https://docs.expo.dev/guides/environment-variables/#using-the--extra--field

**Comment by iegik** [comment]
@selimjouan yep

**Comment by PedroAugustoRamalhoDuarte** [comment]
I am facing the same problem but with all extra variables, they keep the same when they are built.
Using: `Constants.expoConfig.extra`

**Comment by douglowder** [comment]
We added console log in `app.config.ts` and ran

```
NODE_ENV=production eas build -p android --local
NODE_ENV=development eas build -p android --local
eas build -p android --local
```

it's passing all the envs correctly and if nothing is set NODE_ENV is not defined.

So we don't reproduce this issue.

**Comment by sultanmyrza** [comment]
Is this what others do? I'm not sure what are enums for NODE_ENV so I set `production` in `cli.build.preview` too

```json
{
  "cli": {
    "version": ">= 15.0.15",
    "appVersionSource": "remote"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "env": { "NODE_ENV": "development" }
    },
    "preview": {
      "distribution": "internal",
      "env": { "NODE_ENV": "production" }
    },
    "production": {
      "autoIncrement": true,
      "env": { "NODE_ENV": "production" }
    }
  },
  "submit": {
    "production": {}
  }
}
```
