### ISSUE TITLE
SplashScreen is undefined

### ISSUE THREAD

**Issue by lanzosuarez** [expo/expo#2037]
```
import { AppLoading, Asset, SplashScreen } from "expo";

 _cacheResourcesAsync = async () => {
    SplashScreen.hide();
    const images = [
      require("./assets/adult.png"),
      require("./assets/logo.png"),
      require("./assets/signin.png"),
      require("./assets/survey.png")
    ];

    await Expo.Font.loadAsync({
      Roboto: require("./assets/Fonts/AgendaLight.ttf"),
      Roboto_medium: require("./assets/Fonts/AgendaMedium.ttf"),
      AgendaBold: require("./assets/Fonts/AgendaBold.ttf"),
      AgendaLight: require("./assets/Fonts/AgendaLight.ttf"),
      AgendaMedium: require("./assets/Fonts/AgendaMedium.ttf")
    });

    const cacheImages = images.map(image => {
      return Asset.fromModule(image).downloadAsync();
    });

    await Promise.all(cacheImages);
    this.setState({ isAppReady: true });
  };
```

getting an error thats asys _expo.SplashScreen is undefined

expo version   "expo": "^29.0.0",
react: "16.3.1",
react-native: "~0.55.2"

**Comment by sjchmiela** [comment]
Hi, @lanzosuarez!

`SplashScreen` module has just been introduced in SDK 29, are you sure your project is set up to use SDK 29 and you have updated your JS dependencies (`expo` package should be at `29.x.x`)? It looks like your JS still uses old SDK.

What does `yarn list | grep expo@` print out?

**Comment by lanzosuarez** [comment]
```
"dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "axios": "^0.18.0",
    "expo": "^29.0.0",
    "native-base": "^2.7.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-easy-grid": "^0.2.0",
    "react-native-input-scroll-view": "^1.6.7",
    "react-native-keyboard-aware-scroll-view": "^0.6.0",
    "react-native-modal": "^6.4.0",
    "react-native-progress": "^3.5.0",
    "react-native-snap-carousel": "^3.7.2",
    "react-navigation": "^2.6.2"
  }



```

**Comment by lanzosuarez** [comment]
i think i need to check the global package

**Comment by sjchmiela** [comment]
I've just installed dependencies with `yarn` in a new project containing following deps in `package.json`:

```
  "dependencies": {
    "expo": "^29.0.0",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz"
  }
```

and `SplashScreen` should be properly resolved, `cat node_modules/expo/src/Expo.js | grep SplashScreen` returned

```
  get SplashScreen() {
    return require('./launch/SplashScreen');
```

Could you please try reinstalling dependencies and if the problem persists, checking whether `node_modules/expo/src/Expo.js` contains `get SplashScreen()`?

**Comment by lanzosuarez** [comment]
![image](https://user-images.githubusercontent.com/18522203/43315242-eebb6fde-91c7-11e8-9794-eed805d437c0.png)

found it. ill just rebuild. I'll let you know

**Comment by lanzosuarez** [comment]
Now theres an error saying. The Expo SDK requires expo to run. It appears native Expo modules are unavailable and this code is not running on Expo

**Comment by lanzosuarez** [comment]
reinstalled my expo client @sjchmiela  thanksss man

**Comment by sjchmiela** [comment]
Great! 👍 If you have any more questions fire away!
