### ISSUE TITLE
App not loading after Splash Screen

### ISSUE THREAD

**Issue by SaurabhBrst** [expo/expo#2038]
App is working on development mode after splash screen but after creating signed APK its not loading after splash screen also not giving any error in logs. I have not done any changes but my previous APK's are working fine not sure where is the issue. Please Help.

![image](https://user-images.githubusercontent.com/35626666/43310963-b81aecb4-91a6-11e8-924d-7b0806e45aa0.png)

**Comment by vuthanhtrung0504** [comment]
same issue +1. I found that the splash screen is visible on top of UI and i can still press on my text input  under the splash image

**Comment by SaurabhBrst** [comment]
Yes, Exactly the same in my case not sure if its the issue from Expo or is there any issue in our app code or SDK version.

**Comment by gimoteco** [comment]
Same problem in my app too, We solved temporarily removing the splash screen from app.json

**Comment by viktornord** [comment]
I had to prepare prod build but faced the same issue. Please help!

**Comment by lucasato** [comment]
I had the same problem yesterday. At settings.json set "dev" to false and try again.

**Comment by brunooojapa** [comment]
Same problem in my app too

**Comment by angelSigno** [comment]
I am having this problem too. And my project don't have any "settings.json" file. 

We fixed it removing the Splash Screen, but we will need to put it again anytime.

**Comment by igorsbrito** [comment]
I am having the same problem. Removing the splash from android works as a temporary solution.

**Comment by jesseruder** [comment]
Hi everyone. There is another thread in our forums here: https://forums.expo.io/t/standalone-apk-freezes-at-launch-screen/11879/18

Please share an example that reproduces this problem.

**Comment by luiscl32** [comment]
Same problem

**Comment by jesseruder** [comment]
Currently deploying a fix. Will take another ~30 minutes or so before it's out.

**Comment by jesseruder** [comment]
The fix is deployed now, you'll have to run `exp build:android` again. Let me know if it isn't fixed for you.

**Comment by jonknapp** [comment]
If you don't mind, could you share some info about what happened? I had issues as described above in android, but I'm also having some iOS issues and I'm not sure if they are related or not.

PS - that fixed my android build once I added the splash screen back in and rebuilt.

**Comment by jesseruder** [comment]
It was a bug in the Android code for the SplashScreen API. Wouldn't affect iOS @jonknapp.

**Comment by ejimenez93** [comment]
@jesseruder -- We're experiencing the same issue as above. Is there a solution for "detached" Android builds?

**Comment by viktornord** [comment]
Issue is gone after doing these steps
1. remove node_modules folder
2. npm i (or yarn)
3. exp build:android
The newly created build loads without a problem

**Comment by brunooojapa** [comment]
worked for me thanks @viktornord

**Comment by terribleben** [comment]
Hi all, I believe the root cause of this Android issue has been resolved. Because this thread has a generic name, I'm going to rename and close the topic to encourage people to open new threads for similar issues.

@ejimenez93 - if you originally detached your project during the window of time when this bug was present, you may need to [make sure you have the newest Android version of the ExpoKit package](https://docs.expo.io/versions/v29.0.0/expokit/expokit#android). If your problem persists, please feel free to open a new issue.
