### ISSUE TITLE
exp publish hangs

### ISSUE THREAD

**Issue by dikaiosune** [expo/expo#204]
cc @liu0fanyi, moving issue here from https://github.com/react-community/create-react-native-app/issues/216.

**Comment by dikaiosune** [comment]
@liu0fanyi how long have you been waiting for the packager?

**Comment by liu0fanyi** [comment]
@dikaiosune I can publish with expo xde now...and get more information when use XDE to publish app, a process bar...
but can't get this with exp publish...

Maybe switch on something can get process bar?
I have waited for 1 hour and stop it....

**Comment by dikaiosune** [comment]
Hm, that's very strange that is works in XDE but not exp. Since you're able to publish with XDE I'll close this as they use the same code and I'm guessing that something went wrong with exp's installation. If you are still having this issue, can you join our [slack](https://slack.expo.io) so we can try to debug what's happening on your machine? Thanks!

**Comment by dmongit** [comment]
I don't think this is a very good solution. XDE publish works for me but not through a command. I need the command though b/c my command also takes into account env variables (that have definitely worked and have remained unchanged). 

All I get is a super vague "[exp] There was an error publishing your project. Please check for any warnings." (there are no warnings).

**Comment by dooboolab** [comment]
it happens to me also.

**Comment by dmongit** [comment]
I've been dealing with this all day. I can publish on XDE and a Mac (where the JavaScript and Native versions don't match). Not on Windows. On windows I get an error that makes no sense. Stack trace points to a file on xdl\src but the xdl directory doesn't exist where it's looking. Maybe it's a temp file during the publish? Well... if that's the case, I'm getting an error on a file that isn't mine either way.
