### ISSUE TITLE
Differences before @expo/cli and expo-cli

### ISSUE THREAD

**Issue by wangliguang** [expo/expo#20405]
### Summary

In expo (~46.0.17), why not use the new version of `expo-cli`， but also use the old version of `@expo/cli`.

And the difference between the two is not explained in the official documents，after all, the difference between the two is very big

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

~46.0.17

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 23, 27, 28, 29, 30, 31, 33
        Build Tools: 25.0.2, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.17.0 => 0.17.0 
      expo: ~46.0.17 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: 0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

no

**Comment by iegik** [comment]
> expo doctor is not supported in the local CLI, please use expo-cli doctor instead
While you are still using SDK46, some others already testing new features: https://blog.expo.dev/expo-sdk-46-c2a1655f63f7

**Comment by EvanBacon** [comment]
The known differences are documented here https://docs.expo.dev/archive/expo-cli/#expo-cli-migration

New doctor command is [coming soon](https://github.com/expo/expo-cli/pull/4641).
