### ISSUE TITLE
[EAS Build] Cannot send push notifications on iOS anymore (stuck with InvalidCredentials error)

### ISSUE THREAD

**Issue by dolsem** [expo/expo#20402]
### Summary

Sending push notifications started failing with "could not find APNs credentials". I tried running `credentials:manager` earlier today to create a new key, it gets created in my Apple Developer account just fine, but then `credentials:manager` fails with INTERNAL_SERVER_ERROR, assuming trying to upload the key to Expo's servers.

So I created a key manually and tried pushing a new EAS build re-generating all profiles and certificates in the process. It still fails with the same InvalidCredentials error. I've tried running `credentials:manager` and picking "Use existing Push Notifications Key", which results in "Successfully assigned Push Notifactions Key", but the InvalidCredentials error is still there.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.10 Pengwin 11 (bullseye)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/Projects/bladebro/node_modules/.bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmGlobalPackages:
      eas-cli: 3.0.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

import { Expo } from 'expo-server-sdk';
const expo = new Expo();
expo.sendPushNotificationsAsync(chunk);

**Comment by dolsem** [comment]
Update: I am not getting INTERNAL_SERVER_ERROR with eas-cli anymore, assigning new credentials *seems* to work fine, but when I try to send a notification I am still hit with InvalidCredentials.

**Comment by guiedinger** [comment]
I am having this error too, this is the details from the expo API: 
```
            "details": {
                "apns": {
                    "reason": "InvalidProviderToken",
                    "statusCode": 403
                },
                "error": "InvalidCredentials",
                "errorCodeEnum": 6,
                "sentAt": 1674687037
            }
```
I receive InvalidCredentials from expo and InvalidProviderToken from the APNS. I rechecked my apple credentials and they are ok. Did you manage to send pushes to ios?

**Comment by SavageWilliam** [comment]
I had notifications on iOS working but they've since hit a blocker with this error after I swapped out the appId my project was building to to an existing appId.

```
{ status: 'error',
  message:
   'Could not find APNs credentials for APP_ID (experienceId). You may need to generate or upload new push credentials.',
  details: { error: 'InvalidCredentials' } 
  }
```

I've taken the following steps:
1. ` eas credentials` -> ` Add a new push key` -> `Do you want fat-llama to use the new Push Key` -> YES

This results is a new Expo Push Notifications Key on https://developer.apple.com/account/resources/authkeys/review/GTU77H99PJ and also sets the push key on the expo project here https://expo.dev/accounts/fatllama/projects/fat-llama/credentials/ios/.

Looks great but results in the error still

resource:
https://medium.com/@nahuelhds/publishing-your-expo-standalone-app-with-push-notifications-into-the-app-store-the-easy-way-6c3429578602

**Comment by SavageWilliam** [comment]
I've gone through the cycle of creating new keys, following these steps: 

https://www.daily-coding.net/posts/expo-could-not-find-apns-credentials-problem

But no luck so far

**Comment by SavageWilliam** [comment]
Fixed, my issue was actually with my implementation/params of getting the token. See here: 
https://github.com/expo/expo/issues/12142#issuecomment-964508321

experienceId must be `@expo_account/expo_projectname` where `expo_account`  is `expo.owner` in app config  and `expo_projectname` is `expo.slug`
