### ISSUE TITLE
expo-camera onBarCodeScanned callback is not updated

### ISSUE THREAD

**Issue by Tyratox** [expo/expo#20404]
### Summary

Given the code

```tsx
const [counter, setCounter] = useState(0);

const handleBarCodeScanned = ({ type, data }) => {
  console.log(`Counter: ${counter}`);
  setCounter(counter+1);
};

return <Camera
  style={StyleSheet.absoluteFillObject}
  onBarCodeScanned={handleBarCodeScanned}
  barCodeScannerSettings={{
    barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
  }}
/>
```

I expect
```
Counter: 0
Counter: 1
Counter: 2
Counter: 3
...
```
to be logged. Instead
```
Counter: 0
Counter: 0
Counter: 0
Counter: 0
...
```
is logged in the web. On iOS the former trace is logged as expected. It seems as if the `onBarCodeScanned` is not updated when the component is re-rendered. It is possible to workaround this issue using mutable references but this is definitely not a best practice approach in react.

### What platform(s) does this occur on?

Web

### Environment

Pretty sure it is not specific to our environment since It is easily reproducible in a snack with the latest SDK version but here you go anyway.

```
expo-env-info 1.0.5 environment info:
System:
  OS: macOS 12.6.1
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
IDEs:
  Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
  @expo/webpack-config: ^0.16.27 => 0.16.27 
  expo: ^46.0.10 => 46.0.10 
  react: 18.0.0 => 18.0.0 
  react-dom: 18.0.0 => 18.0.0 
  react-native: ^0.69.6 => 0.69.6 
  react-native-web: ~0.18.7 => 0.18.9 
Expo Workflow: managed
```

### Minimal reproducible example

https://snack.expo.dev/@tyratox/expo-camera-issue

1. Open the snack
2. Open to web view
3. Scan several QR codes and observe the console output as well as the counter on screen

**Comment by brentvatne** [comment]
hi there! this is a react question, rather than anything to do with expo-camera

**Comment by Tyratox** [comment]
@brentvatne No it is not, please check the code and the linked snack. In React it is expected that when changing props of components it should change the Components behavior and not keep using the value used for in the first render and expo-camera does not behave accordingly, hence I would certainly classify this as unexpected/undesired behaviour and thus a bug.

Compare the behavior when the Scanner is replaced by a button with the same function onClick.

I am not asking how to workaround this bug, this I already did.

**Comment by Thomas-Hopkins** [comment]
This is not how the previous deprecated library, `expo-barcode-scanner` worked, that library seems to have waited between callbacks for either a state update/rerender, or it was just much slower. However looks like this is just how this new library works, and it performs many callback calls before state is updated.

Definitely something that could cause issues when migrating since I don't see this called out in any migration guides or example usages for `expo-camera` `onBarcodeScanned`.

Workaround (or proper usage), would be to use `useRef` in your component and check/set this in your callback function.
