### ISSUE TITLE
Expo Go client keep crashing on start in iOS Simulator (Intel)

### ISSUE THREAD

**Issue by jamesattard** [expo/expo#20413]
### Summary

Running OSX13 and OSX15 on two brand new virtual environments. Installed Expo Go from scratch, and crashes immediately ios simulator (both environments).

```
npm i -g expo-cli
npx create-expo-app my-app
```

Also opening Expo Go in ios simulator will crash immediately, and I do not even get to the Expo Go app at all.

### What platform(s) does this occur on?

iOS

### SDK Version

47.0.8

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.7.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 19.2.0 - /usr/local/bin/node
      npm: 8.19.3 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: managed
```

### Minimal reproducible example

```
npm i -g expo-cli
npx create-expo-app my-app
```

**Comment by newfylox** [comment]
I actually have the same issue. I gave some details on another thread that you can follow here

https://forums.expo.dev/t/expo-go-crashing-on-ios-simulator-expo-react-native-template-app/68180/3

**Comment by skylite21** [comment]
I have the same issue on SDK 46 and 47. On SDK 45 It's not crashing. It's worth noting that I am running macOS (ventura), using latest xcode, on a qemu based virtual machine on a Linux host. On my intel based macbook air, I don't experience this issue even with the new SDKs.

**Comment by newfylox** [comment]
Following the thread I shared in my last comment, I guess it will be fixed in SDK 48. For now the solution is to make an iOS [develpment build](https://docs.expo.dev/development/create-development-builds/) and install it in the simulator.

**Comment by skylite21** [comment]
@softov I was able to create a development environment with the help of the  [develpment build](https://docs.expo.dev/development/create-development-builds/). I am not editing the source code from inside the macOS vm, I'm only running it, and mounting the source code with sshfs from another machine.  If you are interested in this solution I can share some details. It's not ideal but at least I can run my code from the simulator.
