### ISSUE TITLE
mergeContents helper util from @expo/config-plugins does not allow for full regex

### ISSUE THREAD

**Issue by ansh** [expo/expo#20418]
### Summary

I imported the `mergeContents` from "@expo/config-plugins/build/utils/generateCode" but it did not work as expected and took me a few hours of debugging to figure out.

From the [source code](https://github.com/expo/expo/blob/9b26454e9df84c4984633bfe71e404011ad3fc5c/packages/%40expo/config-plugins/build/utils/generateCode.js), we can that the `src` usually `build.gradle` is run through the `addLines` functions. This `addLines` function first splits the `src` string by newline. Taking the example of `build.gradle` here, it will split it so that each line becomes its own string.

Now, the issue with this is that `mergeContents` takes in an `anchor` property which is supposed to be regex. But, if you do anything more complex than matching A SINGLE LINE, it will error out. It errors out because the `addLines` function splits the whole `src` string/file into an array of strings and only performs matching line by line. The error given is `Failed to match {{your regex}} in contents` which gives the impression there is something wrong with the regex you wrote, when clearly its the `addLines` function messing things up. Obviously, this a problem.

Not sure what the solution is, but I am sure others will be/have been stumped by this.

### What platform(s) does this occur on?

Android

### Environment

  ```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.0.0
      expo-cli: 6.0.8
```

### Minimal reproducible example

Cannot share a Snack as it deals with native code. But, I believe my explanation is sufficient.

**Comment by brentvatne** [comment]
`mergeContents` is not considered to be part of the public API (it is not documented) - I'd suggest forking it and making any changes that you need for your config plugin :)
