### ISSUE TITLE
[expo-av] Video shouldCorrectPitch prop not working on iOS 16

### ISSUE THREAD

**Issue by elliotdickison** [expo/expo#20415]
### Summary

**Problem**

Enabling the shouldCorrectPitch prop on the Video component does not result in pitch correction when the playback rate is changed via the native player controls on iOS 16. Tested on iOS 16.0.3.

**Workaround**

Pitch correct _does_ work when applied via the `setRateAsync` function. Calling `setRateAsync(1, true)` in the `onLoadStart` callback resolves the issue.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
      Yarn: 3.2.1 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
      npm: 8.5.5 - ~/.volta/tools/image/node/16.15.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 31, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-31 | ARM 64 v8a, android-S | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/sVTLpVJWv

**Comment by elliotdickison** [comment]
Your method is superior, I didn't realize you could set those via setStatusAsync

**Comment by gloredo** [comment]
@elliotdickison please close the issue if it worked

**Comment by elliotdickison** [comment]
The issue is still valid, the `shouldCorrectPitch` prop is not working as expected.

**Comment by yepMad** [comment]
Same here

**Comment by yepMad** [comment]
Same problem here. This solution worked, but I don't think this issue should be closed because of it. This is still a problem, even if you set "shouldCorrectPitch" prop in the <Video /> component, you need to run setStatusAsync

> This way is working for me on dev-client:
> 
> ```ts
> import { Audio, Video } from 'expo-av';
> 
> const playerRef = React.useRef<Video>(null);
> 
> React.useEffect(() => {
>   playerRef.current?.setStatusAsync({
>     shouldCorrectPitch: true,
>     pitchCorrectionQuality: Audio.PitchCorrectionQuality.High,
>   });
> }, [playerRef.current]);
> ```

**Comment by yepMad** [comment]
Not stale please

**Comment by gloredo** [comment]
@yepMad 
>> even if you set "shouldCorrectPitch" prop in the Video component

It doesn't work because some props need to be called at runtime, the right way is to use `getStatusAsync`
