### ISSUE TITLE
Expo 29 broken MediaLibrary on IOS

### ISSUE THREAD

**Issue by dontuse** [expo/expo#2042]
Ios simulator
after update to expo 29 
Unhandled promise rejection: Error: CAMERA_ROLL permission is required to do this operation.

for example [https://github.com/expo/native-component-list](https://github.com/expo/native-component-list) - Medialibrary

**Comment by wagnercsfilho** [comment]
I’m having the same problem. Expo 29

**Comment by sjchmiela** [comment]
Hi guys!

The promise rejection comes from denying media gallery access to Expo Client or the running experience.

Could you, please, ensure that the <kbd>Expo Client</kbd> app has access to the media gallery? You can check that in `Settings > Privacy > Photos > Expo`, ensure “Read and Write” is selected.

If “Read and Write” is selected and when you open Expo Client the problem persists, you must have denied permission on a per-experience level. In SDK 27 we've introduced a change to how Permissions work, now they're granted on per-experience basis (see this commit https://github.com/expo/expo/commit/62dd63564aad0eb5e21b035b144c1332a72afb81). If so, try removing and reinstalling the application. 🙂 

Let me know if it helped you resolve the issue!

**Comment by sjchmiela** [comment]
Sorry, this problem only happens in SDK 29 and I've checked behavior against different SDK version. I confirmed this is a bug in Expo code, we'll try to fix it as soon as possible.

**Comment by dontuse** [comment]
standalone app work fine, this happens only in dev with expo.

**Comment by kappe** [comment]
same problem with location "Not authorized to use location services" in expo 29.0

**Comment by terribleben** [comment]
iOS Expo Client v2.7.2 is live in the App Store with this fix. I'll be releasing an updated Simulator build today sometime.

**Comment by terribleben** [comment]
The update with this fix is fully deployed. Sorry for the trouble everyone.

**Comment by victorwads** [comment]
@terribleben, When this fixes will come to Detached Apps in CocoaPods 'ios/2.7.2' ?
