### ISSUE TITLE
Always running default scheme, cannot run different flavor for android

### ISSUE THREAD

**Issue by sheikx1221** [expo/expo#20420]
### Summary

`npx expo start --scheme com.app.fleet.driver --dev-client` should load and run flavor added with the scheme `com.app.fleet.driver`. 

Metro bundler shows this url after running 
`Metro waiting on com.app.fleet.driver://expo-development-client/?url=http%3A%2F%2F192.168.0.111%3A8081`.

However when connected phone via usb and pressed "a" to run the bundler on device, this error shows up
`CommandError: No development build (com.app.driver) for this project is installed. Please make and install a development build on the device first.
Learn more: https://docs.expo.dev/development/build/`

Attaching screenshot here
![image](https://user-images.githubusercontent.com/29302599/206842626-7e577388-85c1-4fab-ac44-14ced6d54f6f.png)

### SDK Version

47

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD   
    SDKs:
      Android SDK:
        API Levels: 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738     
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    Expo Workflow: bare

### Minimal reproducible example

- create a new flavor with different applicationId
- build the new flavor
- run gradlew installFlavorDebug
- after installing run npx expo start --scheme com.flavor.name --dev-client
- press "a" in terminal

**Comment by mgouault** [comment]
Same issue here on iOS simulator for an app having multiple XCode "schemes"

**Comment by walidmaouche** [comment]
Did you find a solution?

**Comment by ethanlee123** [comment]
Hey, any solution here? @sheikx1221

**Comment by shehanGuruge** [comment]
Any solution?

**Comment by powilliam** [comment]
![aaa](https://tenor.com/en-GB/view/aaaa-gif-25651926.gif)

**Comment by melyux** [comment]
Can this be re-opened? Huge problem.
