### ISSUE TITLE
expo-barcode-scanner ENABLE_BITCODE error on eas build

### ISSUE THREAD

**Issue by dinesh-brilworks** [expo/expo#20435]
### Summary

Getting following error while build app which include expo-barcode-scanner,

❌  ld: '/Users/expo/Library/Developer/Xcode/DerivedData/AppName-fjojpajrjlvfmoeybbsiliycsknk/Build/Intermediates.noindex/ArchiveIntermediates/AppName/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXBarCodeScanner/EXBarCodeScanner.framework/EXBarCodeScanner(EXBarCodeScanner.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/expo/Library/Developer/Xcode/DerivedData/AppName-fjojpajrjlvfmoeybbsiliycsknk/Build/Intermediates.noindex/ArchiveIntermediates/AppName/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXBarCodeScanner/EXBarCodeScanner.framework/EXBarCodeScanner' for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 32.0.0
        System Images: android-25 | Google APIs ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.17 => 0.3.22 
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
      react-navigation: ^4.4.0 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

using "expo-barcode-scanner": "~12.1.0", and expo 45.

**Comment by mateodelat** [comment]
Hi, I had the same problem and by just adding this:
`"bitcode": "Debug"`

to your app.json managed to solve the issue

[https://stackoverflow.com/questions/74321845/eas-ios-build-fails-with-error-you-must-rebuild-it-with-bitcode-enabled-xcode-s](url)

**Comment by sokoya** [comment]
@mateodelat , your work around solved the issue, thanks... Unto next one
