### ISSUE TITLE
--offline flag doesn't work when there is no connection on android device

### ISSUE THREAD

**Issue by Levelleor** [expo/expo#20437]
### Summary

`--offline` flag does start the server from cli once I use it, but looks like the Expo Go (on Android) does not run the app without internet connection in offline mode. I found a couple of older issues https://github.com/expo/expo/issues/19201 https://github.com/expo/expo/issues/18918 but they don't seem to be of help. Looks like the behavior is that when there is no internet on PC it would run the server but Expo Go won't run and shows me an error that "Something went wrong".

![image](https://user-images.githubusercontent.com/11915185/207136412-c231b5ec-e967-4c73-9b9f-cb954ad83a69.png)

### What platform(s) does this occur on?

Android

### SDK Version

~47.0.8

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

Regular boilerplate.
expo init [name]
[choosing blank template]
cd [name]
expo start --offline

**Comment by Lindsor** [comment]
Having the same issue, i cant seem to test my app offline which is essentially a MAJOR issue since its an IOT app which needs to connect to the IOT device WiFi making debugging impossible

**Comment by iegik** [comment]
I notice, that may appear after these changes (reading HTTP_PROXY env variable):
https://github.com/expo/expo/commit/8c8eefe0e14e40945af4199dd39d7bdd6ed9a85f#diff-70980f27971899225fe9dfac1a7c4d33ca386b35778f60566d45f151bca05e45L93

**Comment by iegik** [comment]
eg. Try to remove HTTP_PROXY environment variable :)
Add proxy to Android:
https://gist.github.com/iegik/58c4776c7dcde9a5151a9746f763e0e7
