### ISSUE TITLE
[expo-updates] Updates API does not expose "channel" property set in eas.json when "developmentClient" is true

### ISSUE THREAD

**Issue by ajacquierbret** [expo/expo#20431]
### Summary

The Updates API (via the default import of expo-updates) does not expose the `channel` property set in `eas.json` file when the `developmentClient` field is set to `true`, even if EAS actually set `EXUpdatesRequestHeaders` and `expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY` values at build time.

It may be the expected behavior, but you may consider that one could [use channels for dynamically switching between different environment configurations](https://docs.expo.dev/archive/classic-updates/release-channels/#using-release-channels-for-environment-variable-configuration) (as I do) just like before with Classic Updates.

In order for this channel-based env. pattern to work, one could also use the `expo run:<platform>` command in conjunction with the `updates.requestHeaders.expo-channel-name` property in `app.json` configuration, but this development flow must be documented and means that it's impossible to use EAS Build when developing locally.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

```
"expo": "~47.0.8",
"expo-dev-client": "~2.0.1",
"expo-updates": "~0.15.6"
```

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.asdf/installs/nodejs/16.18.1/bin/node
      Yarn: 1.22.19 - ~/Dev/user-mobile-app/node_modules/.bin/yarn
      npm: 8.19.2 - ~/.asdf/installs/nodejs/16.18.1/bin/npm
      Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 26, 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3
      babel-preset-expo: ~9.2.1 => 9.2.2
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: bare
```

### Reproducible demo

1. Setup a minimal bare workflow template
2. Configure EAS Update
3. Configure the `eas.json` file as follows:

```json
{
  "build": {
    "development": {
      "developmentClient": true,
      "channel": "development"
    }
  }
}
```
4. Set the `App.tsx` file as follows:

```tsx
import React from 'react'
import { View, Text } from 'react-native'
import * as Updates from 'expo-updates'

export default () => <View><Text>{Updates.channel}</Text></View>
```

5. Build with `npx eas-cli build -p all --profile development`
6. Run the app built with EAS

**Comment by douglowder** [comment]
Two things:

- The Updates API is not intended to be EAS specific -- it can work with a custom updates server as long as that server follows our protocol. The "channel" concept is EAS specific and is not part of the Updates API.
- Updates generally only work in release builds. If you want your debug build to actually process updates, you should set EX_UPDATES_NATIVE_DEBUG=1 in your build environment ([see this doc](https://docs.expo.dev/eas-update/debug-updates/#debugging-of-native-code-while-loading-the-app-through-expo-updates))
