### ISSUE TITLE
[expo-updates] Updates API does not expose "channel" property at runtime when switching between branch updates via Expo Dev Client

### ISSUE THREAD

**Issue by ajacquierbret** [expo/expo#20433]
### Summary

This issue is a continuation of #20431 and is related to PR #16865.

When switching between different branches via the Expo Dev Client GUI, the Updates API does not expose the new value of its `channel` property, as it is set at build time in native code. Again (as said in #20431), this is a big issue for any app that defines its environment configuration through channels.

As a workaround, one could switch env. configuration via the `Updates.manifest.metadata.branchName` property as I assume that a new modern manifest is fetched when switching between branches. But this implies that a branch name must always match a channel name. This is definitely not a viable workaround.

Two options to tackle this "issue" (in my opinion) :

1. Expose the downloaded branch update's `channel` through subsequent `Updates.channel` calls. I don't know if it's even possible or desirable as there's currently a strong stickness to build time hardcoded channel values in EAS, and because AFAIK, there's no `channel` prop included in modern manifests. My understanding is that this would even break how EAS Update works under the hood, but I may be wrong and I'd really like to have some explanations if not.

2. Update the documentation to suggest another way of switching between different app environments that would be nearly as flexible as using channel-based env. configurations.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

```
"expo": "~47.0.8",
"expo-dev-client": "~2.0.1",
"expo-updates": "~0.15.6"
```

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.asdf/installs/nodejs/16.18.1/bin/node
      Yarn: 1.22.19 - ~/Dev/user-mobile-app/node_modules/.bin/yarn
      npm: 8.19.2 - ~/.asdf/installs/nodejs/16.18.1/bin/npm
      Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 26, 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3
      babel-preset-expo: ~9.2.1 => 9.2.2
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: bare
```

### Reproducible demo

1. Setup a minimal bare workflow template
2. Configure EAS Update
3. Configure the eas.json file as follows:
```json
{
  "build": {
    "development": {
      "developmentClient": true,
      "channel": "development"
    }
  }
}
```
4. Set the App.tsx file as follows:
```tsx
import React from 'react'
import { View, Text } from 'react-native'
import * as Updates from 'expo-updates'

export default () => <View><Text>{Updates.channel}</Text></View>
```
5. Build with `npx eas-cli build -p all --profile development`
6. Run the app built with EAS and switch to another branch
7. Notice that the `channel` rendered on the screen did not change

**Comment by douglowder** [comment]
On both iOS and Android, the `channel` value is determined by the request headers configuration (specifically the `expo-channel-name` value) in native code (on iOS, `Expo.plist`; on Android, `AndroidManifest.xml`).

If you make a change in `eas.json` to modify the channel name, you should also change it in the iOS and Android native code, or re-run `npx expo prebuild`.
