### ISSUE TITLE
[expo-linking][SDK 47] removeEventListener not found

### ISSUE THREAD

**Issue by kpbochenek** [expo/expo#20449]
### Summary

SDK 47 uses react-native 0.70 and there was a breaking change:
https://github.com/facebook/react-native/blob/main/CHANGELOG.md#0700
`Remove deprecated removeListener methods ([2596b2f695]`

But expo-linking still exposes `Linking.removeEventListener` that underneath calls a method from RN that no longer exists.

It means that during migration to SDK 47 your code might still compile but throw 'no function exists' in runtime.

Do you think it would be wise to not expose this function from expo-linking?

(changing to using subscription object returned from addEventListener and calling .remove() later works as expected)

### What platform(s) does this occur on?

Android, iOS

### Environment

I don't have access to my environment right now, can provide this info later if you find it needed to proceed.

### Minimal reproducible example

just use `Linking.removeEventListener` <- your code will compile but throw 'no function found' during runtime

--- EDIT

I know method is marked as `@deprecated` but this is not what I would expect from 'deprecated' method.

**Comment by nazam1998** [comment]
I am having the same issue.
Didn't have any problem while building but when running the app, it throws an error on dev client.

**Comment by gabrieldonadel** [comment]
A new version of expo-linking which fixes this has been released 

| 📦 Package | 🔢 Version | ↖️ Pull requests | 📝 Release notes |
|:--:|:--:|:--:|:--:|
| [expo-linking](https://www.npmjs.com/package/expo-linking/v/3.3.1) | 3.3.1 | #21371 | [CHANGELOG.md](https://github.com/expo/expo/blob/sdk-47/packages/expo-linking/CHANGELOG.md) |

We kindly ask you for some feedback—even if it works 🙏
Happy Coding! 🎉

**Comment by kslbdev** [comment]
you regressed it again it seems.
