### ISSUE TITLE
[EXPO SDK 45 & 47] Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ngima** [expo/expo#20440]
### Summary

Since last Friday I'm having iOS build with EAS failed in fastlane with following errors

### **Error 1**
```
❌  Undefined symbols for architecture arm64
┌─ Symbol: _objc_msgSend$setFragmentBufferOffset:atIndex:
└─ Referenced from: GrMtlRenderCommandEncoder::setFragmentBuffer(id<MTLBuffer>, unsigned long, unsigned long) in libskia.a(gpu.GrMtlPipelineStateDataManager.o)

❌  ld: symbol(s) not found for architecture arm64


❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### **ERROR 2** (SDK 45 & 47)

```
❌  ld: '/Users/expo/Library/Developer/Xcode/DerivedData/<PROJECT>-fjojpajrjlvfmoeybbsiliycsknk/Build/Intermediates.noindex/ArchiveIntermediates/<PROJECT>/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXBarCodeScanner/EXBarCodeScanner.framework/EXBarCodeScanner(EXBarCodeScanner.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/expo/Library/Developer/Xcode/DerivedData/<PROJECT>-fjojpajrjlvfmoeybbsiliycsknk/Build/Intermediates.noindex/ArchiveIntermediates/<PROJECT>/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/EXBarCodeScanner/EXBarCodeScanner.framework/EXBarCodeScanner' for architecture arm64


❌  clang: error: linker command failed with exit code 1 (use -v to see invocation
```

### What I have tried
- I have tried to run with XCode 14 with `eas.json` `ios: image: lastest` and seems like SDK 45 is not supported.
- I have tried with disabling the Bitecode by passing `Debug`
- Upgraded expo to 47 and still getting `ERROR 2`

### What platform(s) does this occur on?

iOS

### SDK Version

45, 47

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31, 33
        Build Tools: 30.0.2, 33.0.0
        System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.0.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

N/A

**Comment by ngima** [comment]
In SDK 47 it worked if bitcode: Debug for non dev-client build. But for `dev-client` build I'm getting similar issue but different error.
```
❌  ld: '/Users/expo/Library/Developer/Xcode/DerivedData/EndoAppDev-hbbkkojmdqtyppenipredtpjyoip/Build/Intermediates.noindex/ArchiveIntermediates/EndoAppDev/BuildProductsPath/Debug-iphoneos/DoubleConversion/libDoubleConversion.a(DoubleConversion-dummy.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/expo/Library/Developer/Xcode/DerivedData/EndoAppDev-hbbkkojmdqtyppenipredtpjyoip/Build/Intermediates.noindex/ArchiveIntermediates/EndoAppDev/BuildProductsPath/Debug-iphoneos/DoubleConversion/libDoubleConversion.a' for architecture arm64


❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ngima** [comment]
Resolve this issue by disabling the bitcode with custom plugin

```javascript
//./plugins/withNoBitcode.js
const { withXcodeProject } = require('@expo/config-plugins');


module.exports = function withNoBitcode(config) {
    return withXcodeProject(config, async (config) => {

        const xcodeProject = config.modResults;
        xcodeProject.addBuildProperty('ENABLE_BITCODE', 'NO');

        return config;
    });
}
``


```json
{
    expo: {
        plugins: [
            "'./plugins/withNoBitcode'"
        ]
    }
}
```

**Comment by kelechionyeama** [comment]
Hey bro, i got this same error and im using your solution but it dosent seem to work for me. Please help

**Comment by atiqfns** [comment]
I have the same issue I upgrade the expo sdk to 47 and build failed on run fastlane. anyone have any suggestion
