### ISSUE TITLE
expo-constants not retrieving values on Web (Metro Bundler)

### ISSUE THREAD

**Issue by erisvaldojunior** [expo/expo#20456]
### Summary

After switching from Webpack to Metro Bundler for Web (needed for Expo Router), I can't retrieve my environment values that are stored on Constants.manifest.extra. They are all undefined. If I switch back to Webpack, it just works.

Any thoughts on this? Code snippet provided.

### What platform(s) does this occur on?

Web

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
      Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
      npm: 9.2.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
      Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.5.1 => 0.5.1 
      @expo/webpack-config: 0.16.2 => 0.16.2 
      expo: ^47.0.0 => 47.0.6 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

import Constants from "expo-constants";

function getEnvironmentValue(key: string) {
  const ENVIRONMENT_VALUE = Constants.manifest?.extra?.[key];
  if (!ENVIRONMENT_VALUE) {
      throw new Error(`${key} is missing.`);
  }
  return ENVIRONMENT_VALUE;
}

**Comment by erisvaldojunior** [comment]
Related to https://github.com/expo/router/issues/137

**Comment by LinusU** [comment]
Ran into this myself whilst trying to switch our web app over to the Metro bundler.

It seems like `NativeModules.EXDevLauncher` is undefined here:

https://github.com/expo/expo/blob/b2d111e616064b7d14ad4d0c9a9c650a0580576d/packages/expo-constants/src/Constants.ts#L53

**Comment by EvanBacon** [comment]
Added as part of Expo Router https://github.com/expo/router/pull/189

**Comment by PaulTondeur** [comment]
This might have been resolved in `expo/router`, but not in `expo-constants`, that still needs fixing

**Comment by agierczak-rho** [comment]
Can confirm that `NativeModules.EXDevLauncher` is also undefined in the native build when running Metro bundler

**Comment by a-gierczak** [comment]
Can confirm that NativeModules.EXDevLauncher is also undefined in the native build when running Metro bundler, which results in Constants.expoConfig always having values from the embedded manifest

**Comment by michaek** [comment]
@EvanBacon Since Expo Router is not required in order to use metro for web, it doesn't seem like this should be considered closed by an update to Expo Router. Is it an implicit expectation that all users of the metro bundler for web will also use Expo Router? I realize Expo Router is recommended, but it seems like a far-reaching change to expect an application to switch routing strategies in order to access configuration values.

**Comment by EvanBacon** [comment]
@michaek there are a few factors at play. 
1. expo-constants is slowly being deprecated in favor of environment variables, expo-device, etc.
2. Metro for web only exists publicly as a feature of Expo Router. I built the feature originally as a way to develop the Expo Router framework faster, and it turned into a full fledged platform.
3. You should technically be able to get constants working by adding the expo-router Babel plugin to your project. In the next version, this plugin will be in the default config, and therefore not tied to router anymore. But only as a result of Expo Router further becoming the default.
