### ISSUE TITLE
CLI: exp login not exit in non-interactive shell

### ISSUE THREAD

**Issue by benhurott** [expo/expo#2046]
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4
### Steps to Reproduce

1. Open the terminal
2. Navigate to the project root
3. Create a `Makefile` with the content:
```
expo-login:
	exp login -u "<your user here>" -p "<your password here>"
```
4. Execute the command: `make expo-login`

### Expected Behavior
The login success message and exit command.

### Actual Behavior
The login success but the command runs forever, locking the terminal.

**Comment by jakubste** [comment]
You're probably logged before running this command.
You have to solutions:

1. Run `exp logout` before
2. Add `--non-interactive` flag to `exp login` command. This will result in *error* if you were logged in before, but will not hang the terminal.

**Comment by benhurott** [comment]
Works!
Thanks man =)
