### ISSUE TITLE
Build: App version not updated

### ISSUE THREAD

**Issue by benhurott** [expo/expo#2047]
### Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/pointrappdev-93d2a4f6-c1e7-4036-9b71-ba7966d3a7bd.tar.gz

### Steps to Reproduce
We try to change the app version in `app.json` to `1.5.0`:
```
"updates": {
      "checkAutomatically": "ON_ERROR_RECOVERY"
    },
    "orientation": "portrait",
    "version": "1.15.0",
    "sdkVersion": "29.0.0",
```

And `npm package` too:
```
"version": "1.15.0",
  "private": true,
  "devDependencies": {
```

And upload to expo build cloud using:
* `exp build:ios --release-channel "dev" --team-id "<obfuscated>" --no-publish --clear-credentials --clear-app-credentials --clear-dist-cert`
* `exp build:android --release-channel "dev" --no-publish`

When we download and install the app, it's in the previous version `1.14.1`.

### Expected Behavior
The app will show the new version in settings.

### Actual Behavior
The app is showing the previous version.

**Comment by jakubste** [comment]
Hi @benhurott 

You're using `--no-publish` flag, which leads to app being build with an old bundle :) Remove it or run `exp publish` before running these two builds commands.

**Comment by benhurott** [comment]
Hi @jakubste  
Sorry for the question, but think about this scenario:
* We have a production version of the app that uses `prod` release-channel.
* We need to upgrade the expo sdk (or other implementation that require a full rebuild).
* So, we need to build the IPA/APK and send to testflight/google play beta but the production users must not receive this update yet (app will crash without the new version).
* So we need to build without publish a new version to the channel.

By the docs, it's only possible if we use the `--no-publish`.

So, the issue is:
* To release a new version in App Store or Google Play, we need to upgrade the app version and, but we can publish before launching on these stores because the app will crash.

**Comment by benhurott** [comment]
Yes, I know, but when we need to release in production instead of dev, we need to send a new build to this channel.
The certificates are different for internal builds (ad-hoc) and production builds (distribution) in iOS.
For this reason, we need to build without publish.
We have a team composed of developers, QA, and beta users and we need to track each of this environment separately.
For `prod` users, we need to build the app, upload to stores, wait for validation (Apple has taken 2 days) and them release the new version and the new publication.

Do you have a guide how this common enterprise flow works with expo?

**Comment by jakubste** [comment]
First of all: you cannot build standalone app in expo with adhoc certificate with `exp build`.
You may build apps for testers and users with the same certificate or if you really don't want do it, just reupload different certificates with each build.

So the workflow I would suggest is:
`exp build:ios --release-channel dev`
Test your app internally, rebuild if needed etc. When you're ready for pushing app to clients:
`exp build:ios --release-channel prod`

**Comment by benhurott** [comment]
`First of all: you cannot build a standalone app in the expo with ad-hoc certificate with exp build.`
What do you mean with `cannot`? Because for now, we are generating the app using ad-hoc certificates and uploading the build to AppCenter and everything is fine.

But ok, we will work to make expo flow works with enterprise flow, not only standalone builds that probably crash the app in production before release in the app store and google play.

Thanks.
