### ISSUE TITLE
Expo Image Picker Android 13 Crash

### ISSUE THREAD

**Issue by fflach** [expo/expo#20482]
### Summary

I got multiple messages from users (and crash reports in Sentry) that the app is crashing when selecting a video from the Android Library. The crashes started after the users upgraded to Android 13. 

Full Error: 
`Failure delivering result ResultInfo{who=null, request=1103701036, result=-1, data=Intent { dat=content://media/... flg=0x41 clip={image/* video/* {U(content)}} }} to activity {io.traindoo.android.stage/com.traindoo.MainActivity}: expo.modules.imagepicker.FailedToDeduceTypeException: Can not deduce type of the returned file `

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      npm: 8.2.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.6 => 47.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.70.6 => 0.70.6 
    Expo Workflow: bare

### Minimal reproducible example

Unfortunately I can´t reproduce this error because I do not own an Android 13 Device.

My Picker Code: 
```
await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Videos,
        allowsEditing: true,
        quality: 0,
        exif: false,
      });
```

**Comment by Joshandrews43** [comment]
Running into similar issues, pretty sure it's due to Android 13's granular media permissions

https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by fflach** [comment]
> ### [Dec 15, 2022](#issuecomment-1353397746)

Interesting Idea, did you had any success with different permission settings?

**Comment by Joshandrews43** [comment]
Currently ordering an Android 13 compatible device, will update you when we figure it out. Another note is that my issue is not quite the same, we are using `expo-media-library` to access album level data.

**Comment by fflach** [comment]
Thank you anyway for the suggestion. I will test if the new permissions can fix the issue.

**Comment by fflach** [comment]
Unfortunately it seems like the permission havent been the issue.

**Comment by bradjones1** [comment]
I ran into this as well, however thankfully only only one user so far. Sentry reports the user was on Android 13. Of course, I can't recreate myself on my own device. I did just try a fresh install on an Android 13 device on Appetize.io and couldn't recreate, either.

My hunch was also related to permissions, since the Android upgrade notes say:

> If your app was previously granted the [`READ_EXTERNAL_STORAGE`](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) permission, then any requested `READ_MEDIA_*` permissions are granted automatically when upgrading.

That led me to think that _new_ installs might be missing a permission.

The Sentry log also shows that all the permissions are granted, anyway:

```
{
  ACCESS_COARSE_LOCATION: granted,
  ACCESS_FINE_LOCATION: granted,
  ACCESS_NETWORK_STATE: granted,
  ACCESS_WIFI_STATE: granted,
  ACTIVITY_RECOGNITION: granted,
  AD_ID: granted,
  BADGE_COUNT_READ: not_granted,
  BADGE_COUNT_WRITE: not_granted,
  BILLING: granted,
  BIND_GET_INSTALL_REFERRER_SERVICE: granted,
  BROADCAST_BADGE: not_granted,
  CAMERA: granted,
  CHANGE_BADGE: not_granted,
  FOREGROUND_SERVICE: granted,
  INTERNET: granted,
  POST_NOTIFICATIONS: granted,
  PROVIDER_INSERT_BADGE: not_granted,
  READ: granted,
  READ_APP_BADGE: not_granted,
  READ_EXTERNAL_STORAGE: granted,
  READ_GSERVICES: granted,
  READ_MEDIA_AUDIO: granted,
  READ_MEDIA_IMAGES: granted,
  READ_MEDIA_VIDEO: granted,
  READ_SETTINGS: not_granted,
  RECEIVE: granted,
  RECEIVE_BOOT_COMPLETED: granted,
  RECORD_AUDIO: not_granted,
  SYSTEM_ALERT_WINDOW: not_granted,
  UPDATE_BADGE: not_granted,
  UPDATE_COUNT: not_granted,
  UPDATE_SHORTCUT: not_granted,
  USE_BIOMETRIC: granted,
  USE_FINGERPRINT: granted,
  VIBRATE: granted,
  WAKE_LOCK: granted,
  WRITE: not_granted,
  WRITE_EXTERNAL_STORAGE: granted,
  WRITE_SETTINGS: not_granted
}
```

Going to keep an eye on this and see if it happens again to any other real-life users, but this one is weird for sure. Curious if anyone else has data that will help focus this.

**Comment by enagorny** [comment]
In my case it started to happen when we've bumped compile sdk version `compileSdkVersion = 33`.
I've managed to overcome it by patching `expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt`

https://github.com/expo/expo/issues/20096

**Comment by bradjones1** [comment]
@enagorny The failure mode there is explicitly permissions, while here it is `expo.modules.imagepicker.FailedToDeduceTypeException: Can not deduce type of the returned file`.

Not saying they're not related but worth noting that the exception here makes no mention of permissions.

**Comment by enagorny** [comment]
@bradjones1 you are right - my comment is not relevant to this issue and should be ignored

**Comment by TheEhsanSarshar** [comment]
I still have this issue, don't know why it's closed. it's simply not support video type.
I guess the problem is here
https://github.com/expo/expo/blob/b0b41037be7bd8bb2a0171a32dc93b5686f0f26e/android/versioned-abis/expoview-abi47_0_0/src/main/java/abi47_0_0/expo/modules/imagepicker/ImagePickerUtils.kt#LL33C1-L36C43
it's not able to get content uir

**Comment by marco2216** [comment]
This seems to have started happening for our users after expo 49 upgrade, it seems to specifically affect Samsung users. Anyone else?

**Comment by brianwachira** [comment]
> This seems to have started happening for our users after expo 49 upgrade, it seems to specifically affect Samsung users. Anyone else?

Yes,I am testing on Samsung SM-A307FN. I am getting the same issue

**Comment by paulsizer** [comment]
@fflach Is this still an issue for you?

**Comment by marco2216** [comment]
I have a little bit of info from some users, one of them shared this:
 “I have a feeling it’s something to do with how it’s being loaded on my phone. For example when I go to upload a video, if I have to manually go into my camera folder it crashes the App. But after some time it appears in my recent folder (Which is initial folder that’s open when I go to upload the video). Once it’s appeared here it uploads no issues.”
 
 Another one shared metadata of one of the videos that had the problem, it seems like a normal mp4 video:
![image](https://github.com/expo/expo/assets/4561482/5ad9e2f9-a78e-4621-b201-a2ce59d81dd8)

**Comment by paulsizer** [comment]
@marco2216 This is what we have seen our side also. It seems to be files picked from the camera folder.

@TheEhsanSarshar @bradjones1 @Joshandrews43 Are you still seeing this? Or have you managed to find a fix for this?

**Comment by FabianTrain** [comment]
@marco2216 sorry for the late response.  We observed the same behavior as @marco2216 (it depends which gallery folder is used for the upload). I have a very limited user base so we just used that work around.

**Comment by marco2216** [comment]
I'm wondering if it's the samme issue as this https://github.com/expo/expo/issues/24172
I think it might be, we'll try updating to see if it fixes this issue.

**Comment by wen-kai** [comment]
We've observed this crash happens when selecting video assets that have been edited but not exported "as copy".

**Comment by wen-kai** [comment]
As a workaround we are using DocumentPicker for android until this is resolved. not as nice of a UEX but better than crashes:
```
      let pickerResponse;
      if (Platform.OS === 'android') {
        pickerResponse = await DocumentPicker.getDocumentAsync({
          type: videosOnly ? 'video/*' : '*/*',
          copyToCacheDirectory: true,
        });
      } else {
        pickerResponse = await ImagePicker.launchImageLibraryAsync({
          allowsEditing: true,
          mediaTypes: ImagePicker.MediaTypeOptions.Videos,
          videoExportPreset: ImagePicker.VideoExportPreset.H264_1280x720,
        });
      }
```

**Comment by marco2216** [comment]
@wen-kai I just tried to reproduce this on my S22, but if I save over the existing video, it just disappears from the image picker modal, so I can't select it. Could you send a screenshot of what the image picker modal looks like to you?

**Comment by wen-kai** [comment]
@marco2216 ah yes, that would happen for me as well, which was an unexpected UEX -- as a typical user I'd expect to be able to conveniently select the video that I recently edited. I had to hunt for the media asset via the Camera folder. The image picker modal is the new one which is a really nice experience, except for this specific case.

**Comment by marco2216** [comment]
@wen-kai Thanks, I can reproduce it with selecting it from the Camera folder.
I guess this is a bug/compatibility issue in Android, since the issue is that the ContentResolver can not get the type of the file? I haven't investigated if things could work if maybe we could get around that somehow. But if not, then I guess the only way to fix it would be to use the Document Picker, as you suggested, or revert the change in image picker that makes it use the new picker, until it's fixed in Android/One UI?

**Comment by hanna-becker** [comment]
I ran into this today on a Samsung Galaxy S24+ running Android 16 and OneUI 8. And I can reproduce it on a Samsung Galaxy S23, also running Android 16/OneUI 8.

When picking a video that I had edited (shortened) and saved (no copy) from the "Collections" tab, the app crashes with this stack trace:
```
 ERROR  Your app just crashed. See the error below.
expo.modules.imagepicker.FailedToDeduceTypeException: Can not deduce type of the returned file
  expo.modules.imagepicker.ImagePickerUtilsKt.getType(ImagePickerUtils.kt:36)
  expo.modules.imagepicker.ImagePickerUtilsKt.toMediaType(ImagePickerUtils.kt:80)
  expo.modules.imagepicker.contracts.ImageLibraryContract.parseResult(ImageLibraryContract.kt:102)
  expo.modules.imagepicker.contracts.ImageLibraryContract.parseResult(ImageLibraryContract.kt:28)
  expo.modules.kotlin.activityresult.AppContextActivityResultRegistry.doDispatch(AppContextActivityResultRegistry.kt:325)
  expo.modules.kotlin.activityresult.AppContextActivityResultRegistry.dispatchResult(AppContextActivityResultRegistry.kt:303)
  expo.modules.kotlin.activityresult.ActivityResultsManager.onActivityResult(ActivityResultsManager.kt:52)
  expo.modules.kotlin.AppContext.onActivityResult$expo_modules_core_debug(AppContext.kt:313)
  expo.modules.kotlin.ReactLifecycleDelegate.onActivityResult(ReactLifecycleDelegate.kt:37)
  com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:348)
  com.facebook.react.runtime.ReactHostImpl.onActivityResult(ReactHostImpl.kt:575)
  com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.kt:204)
  com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:212)
  expo.modules.ReactActivityDelegateWrapper$onActivityResult$1.invokeSuspend(ReactActivityDelegateWrapper.kt:291)
  expo.modules.ReactActivityDelegateWrapper$onActivityResult$1.invoke(Unknown Source:8)
  expo.modules.ReactActivityDelegateWrapper$onActivityResult$1.invoke(Unknown Source:4)
  expo.modules.ReactActivityDelegateWrapper$launchLifecycleScopeWithLock$1.invokeSuspend(ReactActivityDelegateWrapper.kt:485)
  kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:359)
  kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
  kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:358)
  kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:124)
  kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
  kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
  kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
  kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
  expo.modules.ReactActivityDelegateWrapper.launchLifecycleScopeWithLock(ReactActivityDelegateWrapper.kt:483)
  expo.modules.ReactActivityDelegateWrapper.launchLifecycleScopeWithLock$default(ReactActivityDelegateWrapper.kt:479)
  expo.modules.ReactActivityDelegateWrapper.onActivityResult(ReactActivityDelegateWrapper.kt:277)
  com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:96)
  android.app.Activity.onActivityResult(Activity.java:7872)
  android.app.Activity.internalDispatchActivityResult(Activity.java:9961)
  android.app.Activity.dispatchActivityResult(Activity.java:9938)
  android.app.ActivityThread.deliverResults(ActivityThread.java:6907)
  android.app.ActivityThread.handleSendResult(ActivityThread.java:6957)
  android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:78)
  android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)
  android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
  android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:3150)
  android.os.Handler.dispatchMessage(Handler.java:110)
  android.os.Looper.loopOnce(Looper.java:273)
  android.os.Looper.loop(Looper.java:363)
  android.app.ActivityThread.main(ActivityThread.java:10060)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

The workaround described here of setting "legacy" to true does not change this behavior, unfortunately: https://github.com/expo/expo/issues/26875
