### ISSUE TITLE
TypeError: Property '(generic)' is missing in type '{}' but required in type '(generic type)'

### ISSUE THREAD

**Issue by Seojun-Park** [expo/expo#20485]
### Summary

I'm developing user's location tracking system based on the official [documentation's example](https://docs.expo.dev/versions/latest/sdk/task-manager/#example)

Then, the following type error occurs.

![image](https://user-images.githubusercontent.com/47709344/207842031-92f560c1-c2b2-4765-b160-e24ba7d70595.png)

`defineTask` takes `taskExecutor` as second param, and it's typed as `TaskManagerTaskBody`.

```tsx

export function defineTask(taskName: string, taskExecutor: TaskManagerTaskExecutor) {...}

export type TaskManagerTaskExecutor = (body: TaskManagerTaskBody) => void;

export interface TaskManagerTaskBody<T = object> {
  data: T;
  error: TaskManagerError | null;
  executionInfo: TaskManagerTaskBodyExecutionInfo;
}
```

As you can see here, the `TaskManagerTaskBody` takes generic type for its data field, and according to that, I should be able to give generic typing like below : 

```tsx
TaskManager.defineTask(
  LOCATION_TASK_NAME,
  (body: TaskManager.TaskManagerTaskBody<
    {
      locations: Array<Location.LocationObject>;
    }
  >;
) => {
  if (body.error) {
    // Error occurred - check `error.message` for more details.
    return;
  }
  if (body.data) {
    const { locations } = body.data;
    // do something with the locations captured in the background
  }
});
```

However, the following error occurs if I add type to the body.

```
Argument of type '({ data, error }: TaskManager.TaskManagerTaskBody<{    locations: Array<Location.LocationObject>;}>) => void' is not assignable to parameter of type 'TaskManagerTaskExecutor'.
  Types of parameters '__0' and 'body' are incompatible.
    Type 'TaskManagerTaskBody<object>' is not assignable to type 'TaskManagerTaskBody<{ locations: LocationObject[]; }>'.
      Property 'locations' is missing in type '{}' but required in type '{ locations: LocationObject[]; }'
```

![image](https://user-images.githubusercontent.com/47709344/207841628-3935ed4f-6be7-4753-94b3-a1b3af564538.png)

After investigation, I noticed that there is no point that accepting generic typing on `TaskManagerTaskExecutor`

Should it be something like this? 

```tsx
export type TaskManagerTaskExecutor = <T = unknown>(body: TaskManagerTaskBody<T>) => void;

export interface TaskManagerTaskBody<T = unknown> {
  data: T;
  error: TaskManagerError | null;
  executionInfo: TaskManagerTaskBodyExecutionInfo;
}
```

Or as workaround, if I make location type as optional (e.g.: 
```
  {
      locations?: Array<Location.LocationObject>;
   }
```
)

The type error is disappear.

### What platform(s) does this occur on?

Not Applicable

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
      Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    Expo Workflow: managed

### Minimal reproducible example

Copy and paste the example from the documentation on expo project that using `typescript`

link : https://docs.expo.dev/versions/latest/sdk/task-manager/#example

**Comment by SoulTherapy** [comment]
I also have the same error.

**Comment by Herbias** [comment]
I also have the same error. the TaskManagerTaskExecutor has no way to accept generic typing.
