### ISSUE TITLE
CameraRoll.getPhotos return just a few on iOS

### ISSUE THREAD

**Issue by andresespinosapc** [expo/expo#2048]
### Environment
Environment:
  OS: Linux 4.15
  Node: 10.6.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/andresespinosapc-65bd207a-ccde-4063-aa05-e06fc95f9969.tar.gz

*Target:* iOS

### Steps to Reproduce
Just use the function CameraRoll.getPhotos on iOS and it will return just a few photos.
I've tried with multiple parameters. To make the issue more evident you can use:
```javascript
{
  first: 100,
  assetType: 'All',
  groupTypes: 'All',
}
```

### Expected Behavior
Return the first 100 photos from my Camera Roll.

### Actual Behavior
It returned just 39 results.

### Reproducible Demo
https://snack.expo.io/Hyw-kQa4X
- I think it **must be run on a physical iOS device**, because it has to access the camera roll.
- The demo prints the length of `response.length`, where `response` is the resolved value of `CameraRoll.getPhotos` with the parameters I mentioned earlier.

**Comment by quinlanj** [comment]
hi @andresespinosapc, thanks for writing in! The code for CameraRoll is maintained by the react native project, so any changes there would have to be filed with them.
