### ISSUE TITLE
SDK 47.0. Can't switch jsEngine to jsc after using Hermes

### ISSUE THREAD

**Issue by kdthomas2121** [expo/expo#20486]
### Summary

Switched to Hermes as part of the upgrade to 47. However Hermes has a probelm with large JSON files [https://github.com/expo/expo/issues/18365](url). I've not been able to get any of the workarounds working so switched back to jsc. This seems to have worked when using expo go. But building new dev builds always seems to result in them still using hermes

` Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`., js engine: hermes `

This is shown after the maximum call stack size exceeded message. Included the large json file and snack (not sure it's using hermes) [countries.json.zip](https://github.com/expo/expo/files/10236814/countries.json.zip)

`const countryInfo = findPlaceByCoordinate(require("../../assets/countries.json"), lat, long);`
      
      `{ "packagerOpts": {
    "sourceExts": [
      "cjs"
    ]}, "expo": {
    "name": "xx",
    "slug": "xx",
    "owner": "xx",
    "jsEngine": "jsc",
    "version": "1.3.4",
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "xx-xx",
            "project": "xx",
            "authToken": "xxx"
          }
        }
      ]
    },
    "plugins": [
      "sentry-expo",
      "expo-community-flipper",
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ],
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#294A6E"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "jsEngine": "jsc",
      "bundleIdentifier": "com.xx.xx",
      "buildNumber": "60"
    },
    "android": {
      "icon": "./assets/icon.png",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#294A6E"
      },
      "jsEngine": "jsc",
      "versionCode": 84,
      "package": "com.xxx.xxx"
    },
    "extra": {
      "eas": {
        "projectId": "xxx"
      }
    }},"icon": "./assets/icon.png","name": "xx"}`

### What platform(s) does this occur on?

Android, iOS

### Environment

`expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.09.19.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/kylethomas/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.4.0 => 0.4.0
      expo: ^47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      eas-cli: 3.0.0
      expo-cli: 6.0.8
    Expo Workflow: bare`

### Minimal reproducible example

https://snack.expo.dev/@kdthomas21/largejsonfile

**Comment by iegik** [comment]
Have you tried `expo prebuild --clean`?

**Comment by kdthomas2121** [comment]
This worked! Thanks @iegik!
