### ISSUE TITLE
Invalid `expo-dev-menu.podspec` file: no implicit conversion of nil into String.

### ISSUE THREAD

**Issue by META-DREAMER** [expo/expo#20497]
### Summary

When running `npx expo prebuild`, it fails when trying to install pods with the following error:

```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Failed to load 'expo-dev-menu' podspec: 
[!] Invalid `expo-dev-menu.podspec` file: no implicit conversion of nil into String.

 #  from /Users/hammadjutt/Dev/md-wtf/node_modules/expo-dev-menu/expo-dev-menu.podspec:24
 #  -------------------------------------------
 #  
 >  folly_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -DRNVERSION=' + rnVersion + ' -DRNPATCHVERSION=' + rnPatchVersion
 #  folly_compiler_flags = folly_flags + ' ' + '-Wno-comma -Wno-shorten-64-to-32'
 #  -------------------------------------------
```

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo-dev-client@npm:2.0.1 
expo@npm:47.0.8

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 16.16.0 - /var/folders/r1/c3ctl7_s2dl2wld20w1mgj7m0000gn/T/fnm_multishells/14606_1671061207803/bin/node
      Yarn: 3.3.0 - /var/folders/r1/c3ctl7_s2dl2wld20w1mgj7m0000gn/T/fnm_multishells/14606_1671061207803/bin/yarn
      npm: 8.11.0 - /var/folders/r1/c3ctl7_s2dl2wld20w1mgj7m0000gn/T/fnm_multishells/14606_1671061207803/bin/npm
      Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:

### Reproducible demo

https://github.com/META-DREAMER/universal-dapp

**Comment by lukmccall** [comment]
Hi, thanks for your report. 
I've investigated your problem and here is what I found.
You see that error because the react native isn't hoisted, but `expo-dev-menu` is. We run `node --print "require('react-native/package.json').version"` inside of the dev menu podspec. It should work in the monorepo, but for some reason, it isn't. 

I'll close that issue because it doesn't seem to be a problem with the package itself, but with your setup. However, feel free t ask me any questions which may help you resolve the isssue.

**Comment by lehresman** [comment]
I've run into this same problem in our monorepo.  What was the solution?

**Comment by chen-rn** [comment]
Running into this problem as well in a monorepo(turborepo).

@lehresman did you manage to solve this?

**Comment by lehresman** [comment]
Yes, my solution was to upgrade to Yarn 3 and not hoist any of my expo packages.

**Comment by chen-rn** [comment]
The template[(create-t3-turbo)](https://github.com/t3-oss/create-t3-turbo) I'm using enforces pnpm. I tried changing `hoisting=false` and `hoist-pattern[]=!expo-dev-menu` in .npmrc but am still getting the same error.

@lukmccall any ideas on how I can go about this?

**Comment by joelpierre** [comment]
Another ill advised solution for this, if for any reason react-native isn't being hoisted AND you only have one react-native package in your monorepo, is to do the nuclear options and set "resolutions" with your version of RN AND/OR install your react-native version as a devDeps in the root of your monorepo. Sometimes setting "hoistingLimits" has other consequences which are not always desired.

**Caution** though understand what you are doing here 😅
