### ISSUE TITLE
Updates.Channel is null, even when building a profile with the Channel specified with eas-updates configured

### ISSUE THREAD

**Issue by humandevs** [expo/expo#20499]
### Summary

We need the EAS Profile/channel to be available to the app before an update is released.

Even after upgrading to eas update, Updates.channel is undefined when an eas build is run, unless eas update is run.

This breaks our builds which rely on the classic build releaseChannel to parse what environment variables to use in the build based on the releaseChannel name.

Updates.channel is blank, unless an update has been pushed via Updates (the initial build is just "blank" even though it's in the channel specified by the profile:

{
  "build": {
    "development": {
      "channel": "dev",
      "distribution": "internal",
      "developmentClient": "true"
    },
}

Outputs Updates.channel = null and Updates.releaseChannel = "default" if an `eas build --profile development` is run.

Note: You can't use releaseChannel as expo-cli will error out if you try to build with both "channel" and "releaseChannel" specified, with error "For EAS Update, you need to specify the `channel` property, or your build will not be able to receive any updates".

See others with this issue here:
https://github.com/expo/eas-cli/issues/819
https://github.com/expo/eas-cli/issues/292

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.2
      expo: ^46.0.0 => 46.0.17
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.10
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Minimal reproducible example

1) add eas-update with 'eas update:configure'
2) Add an eas.json profile with a channel name
3) Build the app with `eas build --profile "channel"`
3) Attempt to retrieve that channel name with Updates.Channel
4) Updates.Channel is null

**Comment by humandevs** [comment]
Ah, this happens if you build a development build. Updates.channel is available if you build a production build.

**Comment by douglowder** [comment]
Updates generally only work in release builds. If you want your debug build to actually process updates, you should set EX_UPDATES_NATIVE_DEBUG=1 in your build environment ([see this doc](https://docs.expo.dev/eas-update/debug-updates/#debugging-of-native-code-while-loading-the-app-through-expo-updates)). 

In a normal development build using the packager, `Updates.channel` will be null.

**Comment by stesvis** [comment]
> Ah, this happens if you build a development build. Updates.channel is available if you build a production build.

Hi @humandevs  I was looking at [this piece of documentation](https://docs.expo.dev/eas-update/debug/?redirected#configure-channel), specifically at this:

```json
{
  "build": {
    "preview": {
      "distribution": "internal",
      "channel": "preview"
    },
    "production": {
      "channel": "production"
    }
  }
}
```

and wouldn't this mean that if you run that command you would find `Updates.channel` to have a value of `preview`?

> Then, we can run a command like eas build --profile preview to create a build with a channel named "preview

By `development build` you mean a profile that has `"developmentClient": true,`?

**Comment by iNath** [comment]
It seams that `Updates.channel` only work for "production" build if there is an `eas update` executed, not directly after the `eas build`.

Is it normal ? I don't find any documentation about this behaviour...
