### ISSUE TITLE
scoped npm packages using the Expo Modules API have broken autolinking on Android when used with bare expo

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#20495]
### Summary

Please see my triage in https://github.com/react-native-google-signin/google-signin/issues/1124#issuecomment-1352442949

The long and short of it is that in this project utilizing the Expo Modules API + bare Expo, Android gets autolinked twice. Once the scope is removed from the package (e.g. remove `@myorganization/`), Android does not get autolinked twice and correctly links once. Build failures and warnings disappear.

The consequence of the double linkage is that Gradle goes haywire, occasionally yielding `package-aware-r.txt` errors and throwing thousands of Gradle warnings. Intermittent build failures will occur at the step: `:expo:generateReleaseRFile`.

Here is a screengrab of the gradle tasks in my MVE where all I did was `yarn add @react-native-google-signin/google-signin`. You see the scoped package is causing confusion where it shows up twice, once with a `-` and once with an `_`:
<img width="1725" alt="Screen Shot 2022-12-15 at 1 48 48 PM" src="https://user-images.githubusercontent.com/3495974/207942873-d3087a82-4f31-4b77-bf91-603626b69a2d.png">

I created a fork where all I did was take the google sign in package and rename it: https://github.com/shamilovtim/rn-google-signin. My rename does not use a scope, it's simply `rn-google-signin`. This does not create two Gradle tasks, and build errors disappear.

### What platform(s) does this occur on?

Android

### Environment

```
 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.5.1 - /usr/local/bin/fish
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/admin/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | AOSP ATD ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.17.2 => 0.17.2
      expo: 45.0.8 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.5 => 0.68.5
      react-native-web: 0.18.9 => 0.18.9
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: bare
```

### Minimal reproducible example

https://github.com/shamilovtim/expo-modules-scoped-packages-bug-mve

**Comment by Kudo** [comment]
close via https://github.com/react-native-google-signin/google-signin/pull/1126. you could simply fix the error by removing the android key [here](https://github.com/react-native-google-signin/google-signin/blob/869937bf8d168c77e48f049e52056f09aea3edbd/expo-module.config.json#L3)
