### ISSUE TITLE
Android push notification doesn't respect channel's priority or vibrate settings on Android 7

### ISSUE THREAD

**Issue by Meinl** [expo/expo#2049]
## Environment

Environment:
  OS: Windows 10
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3764568

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz

Android

### Steps to Reproduce

(Write your steps here:)

1. Added following code on root componentDidMount
if (Platform.OS === 'android') {
   Notifications.createChannelAndroidAsync('orders', {
   name: 'Orders',
   priority: 'max',
   vibrate: [0, 250, 250, 250],
   })
}
2. Send notification through push notification expo tool.
3. Received notification on Android device but doesn't trigger a sound, vibrate or visual UI (neither foregorund/background)

### Expected Behavior

When notification has received, it should visible sliding down from status bar, playing a notification sound and default vibrating.

### Actual Behavior

Icon notification appears on status bar, and when slide down status bar, appear title and body message from notification. But doesn't show, sound or vibrate.

**Comment by esamelson** [comment]
Hi @Meinl - the code you've posted should work, but these settings can all be overridden by users or the OS. They also only take effect the very first time you create the channel with id `orders` so if you've already created this channel, none of the settings you put will apply. I would suggest going to Settings -> Apps & notifications -> Expo/your standalone app -> App notifications -> Orders and checking the actual settings there.

^ This is all assuming you're running Android 8+ on your device. If not, which OS are you running, and what type of device?

**Comment by Meinl** [comment]
@esamelson Thanks for your reply.

I've checked OS version and is 7.0. I've tested again in a 8.0 and works fine (my bad).

So, how can i get the same behavior on devices with 7.0 versions or less? Is it possible?

Thanks in advance.

**Comment by esamelson** [comment]
Hi @Meinl - we don't currently support most of those properties for push notifications on Android 7 and below, unfortunately 😞 They should work for local notifications, but I believe only `sound` is supported for push notifications. Could you verify that your device's sound is on and that notifications from other apps make sound?

**Comment by Meinl** [comment]
@esamelson I understand. What about if I treat push notification as local? it would work as Android 8?

**Comment by esamelson** [comment]
@Meinl I'm not quite sure what you mean, but you're welcome to test it out yourself! Here's what we support currently AFAIK:

- Local notifications on Android 7 and below support all fields
- Push notifications on Android 7 and below support only the `sound` field
- Local and push notifications on Android 8+ support all fields

We'll work on adding support for all of the fields in push notifications to older Android devices. Please let me know if you continue to have issues with `sound` on your Android 7 device, and other apps' notifications do make a sound on the same device.

**Comment by bportman** [comment]
I'm in the same boat - no sound on local notifications on Android.  They are working on iOS.  I have Android 8 on my device, so what am I missing to get the local notification sounds working?

**Comment by esamelson** [comment]
@bportman - are you using notification channels? These are required starting on Android 8 in order to get sound. See the guide here: https://docs.expo.io/versions/v29.0.0/guides/notification-channels . If you still aren't getting sound, please open a new issue with a full repro example. Thanks!

**Comment by khuang-citylift** [comment]
I am also experiencing this issue where the heads up notifications do not show up in Android. I am using Notification channels and verified that my channel shows up and is enabled at: Settings -> Apps & notifications -> Expo/your standalone app -> App notifications.

My notification shows up in the background but not heads-up.

In my componentDidMount() I have:

```
componentDidMount() {
		// Create a channel for sending push notifications
		if (Platform.OS == 'android') {
			Notifications.createChannelAndroidAsync('pushChannel', {
			    name: 'pushChannel',
				priority: 'max',
				vibrate: [0, 250, 250, 250],
			  });
		}
	}
```

The Android API Level is 28. Anyone have any idea what may be wrong?

Thanks,
Kevin

**Comment by qalqi** [comment]
+1

**Comment by basdvries** [comment]
Any update here? I'm experiencing the same issue in expo 34

**Comment by sjchmiela** [comment]
Hey all!

I have just confirmed — using `expo-notifications` I wasn't able to reproduce this bug.

I have run this simple application:

```tsx
import React from "react";
import { View, Text } from "react-native";
import * as Notifications from "expo-notifications";

export default function Main() {
  // Ensure notification channel is configured
  React.useEffect(() => {
    Notifications.setNotificationChannelAsync("test-id", {
      name: "Orders",
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
    })
      .then((channel) => console.log("Channel set", channel))
      .catch(console.warn);
  }, []);

  // Fetch Expo push token and print to console
  React.useEffect(() => {
    Notifications.getExpoPushTokenAsync().then(console.log).catch(console.warn);
  }, []);

  return (
    <View style={{ flex: 1, margin: 50 }}>
      <Text>Howdy!</Text>
    </View>
  );
}
```

And used the token printed to send a push notification using https://expo.io/notifications with the application backgrounded (if the application wasn't backgrounded I would have to [set a notification handler](https://docs.expo.io/versions/latest/sdk/notifications/#setnotificationhandlerhandler-notificationhandler--null-void) to be able to handle/respond to incoming notifications — this however would be in conflict with trying to verify if channel assigning works).

The notification was shown properly.

I then went into notification settings and changed the <kbd>Orders</kbd> notification channel settings in some noticeable way. Another push notification sent obeyed the changed settings.
