### ISSUE TITLE
registerTaskAsync() failed: [TypeError: Cannot read property 'registerTaskAsync' of undefined]

### ISSUE THREAD

**Issue by Ahsanch11** [expo/expo#20501]
### Summary

when i register the task with this function it says Cannot read property 'registerTaskAsync' of undefined.

### What platform(s) does this occur on?

Android

### Environment

System:
      OS: Windows 10 10.0.22622
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772
    Expo Workflow: managed

### Minimal reproducible example

import * as BackgroundFetch from "expo-background-fetch";
import * as TaskManager from "expo-task-manager";

let setStateFn = () => {
  console.log("State not yet initialized");
};

function myTask() {
  try {
    // fetch data here...
    const newSocket = io(""); 
    console.log("myTask() is ", newSocket); 
    // setStateFn(backendData);
    return newSocket ? BackgroundFetch .Result.NewData : BackgroundFetch .Result.NoData;
  } catch (err) {
    return BackgroundFetch .Result.Failed;
  }
}

async function initBackgroundFetch(taskName, taskFn, interval = 60 * 1) {
  console.log("background fetch");
  try {
    if (!TaskManager.isTaskDefined(taskName)) {
      console.log("registering task...")
      TaskManager.defineTask(taskName, taskFn);
    }
    const options = {
      minimumInterval: interval, // in seconds
      stopOnTerminate: false, // android only,
      startOnBoot: true,
    };

    @ await BackgroundFetch.registerTaskAsync(taskName,options);

  } catch (err) {
    console.log("registerTaskAsync() failed:", err);
  }
}

initBackgroundFetch("VIDEO_CALL_TASK", myTask, 60);

**Comment by alexandermckay** [comment]
It sounds like you have not installed the library.
