### ISSUE TITLE
[android] makeDirectoryAsync() succeeds, but still returns error "could not be created"

### ISSUE THREAD

**Issue by kelvinlawson** [expo/expo#2050]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 7.6.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Have only seen the problem on Android so far. Standalone release build downloaded through Play store.

### Steps to Reproduce

(Write your steps here:)

1. Create a directory with makeDirectoryAsync()

### Expected Behavior

Expect to receive no error.

### Actual Behavior

makeDirectoryAsync() often returns "Error" ... "could not be created". However if I check getInfoAsync() after receiving the error, the directory is actually created.

The last Sentry report about this showed it was a Cubit X15 phone, Android 22.

### Reproducible Demo

```
// Create any app folders that don't already exist
export const checkAndCreateFolder = async folder_path => {
  const folder_info = await Expo.FileSystem.getInfoAsync(folder_path);
  if (!Boolean(folder_info.exists)) {
    // Create folder
    try {
      await FileSystem.makeDirectoryAsync(folder_path, {
        intermediates: true
      });
    } catch (error) {
      // Report folder creation error, include the folder existence before and now
      const new_folder_info = await Expo.FileSystem.getInfoAsync(folder_path);
      const debug = `checkAndCreateFolder: ${
        error.message
      } old:${JSON.stringify(folder_info)} new:${JSON.stringify(
        new_folder_info
      )}`;
      console.log(debug);
      Sentry.captureException(new Error(debug));
    }
  }
};
```

The Sentry reports show that before creation getInfoAsync() returned:
```
{"isDirectory":false,"exists":false}
```

And after makeDirectoryAsync() failed and returned “could not be created” getInfoAsync() shows it actually exists:
```
{"size":4096,"modificationTime":1532552616,"uri":"file:///data/data/com.test.test/files/ExperienceData/%2540test%252Ftest/subfolder","isDirectory":true,"exists":true}
```

**Comment by terribleben** [comment]
Thanks for the report. Are you able to reproduce this on any device, or just the Cubit X15 phone, Android 22 that you mentioned? Also, does your snippet reproduce the error for any value of `folder_path` or only specific values?

**Comment by kelvinlawson** [comment]
I've just had this happen on a fresh install on Pixel 2 as well, so it's not just X15.

Don't think it happens all the time on Android but I guess generally the folder is already created so it doesn't run the makeDirectoryAsync().

**Comment by kelvinlawson** [comment]
The folder is just `${FileSystem.documentDirectory}panels/` so no unusual characters in there (unless it's the trailing slash)

**Comment by kelvinlawson** [comment]
Hi @esamelson thanks for taking the time. It is happening quite frequently on completely fresh installs of an APK (I haven't noticed it in the Expo app) - today on a Pixel 2, Xiaomi Mi 5, the other day on the Cubit X15. It typically happens in the first seconds of starting up after a fresh install (which is when the directories are created).

It happens with multiple different folder names.

I'll see if I can reproduce it via a Snack.

Thanks

**Comment by esamelson** [comment]
Hmmm okay. Even if it's only reproducible in a standalone build, a snack with the minimum amount of code needed to repro it would be super helpful. (I can just use it to make my own standalone app.)

**Comment by kelvinlawson** [comment]
I made a Snack to try to reproduce, but while doing so it became clear that this is probably a concurrency problem with multiple asynchronous calls the app is making to makeDirectoryAsync() in order to create the same folder.

So the error is probably "Directory already exists" (logging the error number in makeDirectoryAsync() would be handy).

Illustrated by this snack which simplifies it to just two consecutive calls to create the same directory:
https://snack.expo.io/Hy1B_YgHQ

**Comment by EvanBacon** [comment]
@kelvinlawson  Could you please open an issue for the FileSystem module https://github.com/expo/expo-file-system/issues 💙
