### ISSUE TITLE
Current activity not found. Make sure to call this method while your application is in foreground.

### ISSUE THREAD

**Issue by kirtikapadiya** [expo/expo#20502]
### Summary

Using expo-splash-screen and SplashScreen.preventAutoHideAsync() throws many errors in production builds and running app on expo go.

I call preventAutoHideAsync first thing in App.js. The warning message is Current activity not found. Make sure to call this method while your application is in foreground.

### What platform(s) does this occur on?

Android

### Environment

  System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ^46.0.0 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 

    Expo Workflow: managed

### Minimal reproducible example

Reproducible demo: https://github.com/kirtikapadiya/SplashReactNative
Step to reproduce 
1. When App start bundling then send app to background.
3. Error message: Current activity not found. Make sure to call this method while your application is in foreground.

**Comment by kirtikapadiya** [comment]
same issue https://github.com/expo/expo/issues/14711

**Comment by viveksc1994** [comment]
@brentvatne with ref. to comment - https://github.com/expo/expo/issues/14711#issuecomment-1246071460
Please refer this issue - This has a reproducible demo.

**Comment by nlarif** [comment]
Happening with Expo 46 only for Android 13 users (so far) for me.

**Comment by viveksc1994** [comment]
Can anyone have solution for this or any workaround?

**Comment by itsramiel** [comment]
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/80689446/214589802-e5b474af-ae67-435c-852a-075170529674.png">

This is happenning to a lot of our users.

From expo docs, `expo-splash-screen` is used to 

> do tasks that will happen behind the scenes such as making API calls, pre-loading fonts, animating the splash screen and so on.

This is exactly what I am using it for. I keep the splash screen until I initialize the app and then hide it, but if the user opens the app and close it directly making the app in the foregorund and then `hideAsync` is called, I get the error.

I believe `expo-splash-screen` should handle such case

**Comment by bradjones1** [comment]
My Sentry logs when receiving these events only include the app starting, so the intersection with splash screen seem to be valid. I don't see any meaningful activity logged otherwise, so this is crashing rather quickly, AFAICT. I'm seeing this on Android 10-13 so I don't think it is Android version specific. I'm on SDK 47.

**Comment by bradjones1** [comment]
> This is exactly what I am using it for. I keep the splash screen until I initialize the app and then hide it, but if the user opens the app and close it directly making the app in the foregorund and then hideAsync is called, I get the error.

Is the workaround to this, then, to check the app status before calling `hideAsync()`? I agree it would be nice to have the library make this "safer," however that seems like a relatively easy workaround in the meantime/if this is a won't-fix.

**Comment by bradjones1** [comment]
Edit: I think adding a `.catch()` to your use of these methods is sufficient?

**Comment by itsramiel** [comment]
I do not think a try catch would be helpful in my case as the error is happening on native side. 

It makes sense to use `AppState` to check if the app is in foreground and then call the method, but I am worried I mess something up and the SplashScreen never disappears. 

I believe the library should handle such edges. Does not make sense to add such a check in every expo app that uses expo-splash-screen 😅

**Comment by brentvatne** [comment]
is this error crashing your app? or is it just an unhandled promise rejection that's getting caught and reported?

**Comment by itsramiel** [comment]
Nope no crashes. Just flooding sentry

**Comment by kirtikapadiya** [comment]
> is this error crashing your app? or is it just an unhandled promise rejection that's getting caught and reported?

not crashing app just  gives warning

**Comment by ttakezawa** [comment]
Same issue happened on my Android 13 device. No crash, but after that error, the app froze and became inoperable.
If this error occurs, I believe the user must restart the app.

**Comment by sergeu90** [comment]
I have same logs in the sentry. App works but ust flooding sentry

**Comment by filip-kostrzewski** [comment]
Same here, flooding bugsnag but app is working fine.

**Comment by mccraveiro** [comment]
@brentvatne could you prioritize this issue? It's generating a lot of noise and it's increasing our Sentry costs. We had 67k events on the last 30 days alone. This represents approximately 33 USD 😞

**Comment by brentvatne** [comment]
@mccraveiro - you can filter this using the sentry sdk if you like! happy to help when someone can provide a minimal reproducible example

**Comment by kirtikapadiya** [comment]
Reproducible demo: https://github.com/kirtikapadiya/SplashReactNative

**Comment by jeremyspritelyco** [comment]
For me, both iOS and Android apps are stuck in the splash screen until I comment on this line.

```
// SplashScreen.preventAutoHideAsync()
```

**Comment by NishantZet** [comment]
Same issue can someone please suggest a workaround or fix for this ?

**Comment by Charles-Johnson** [comment]
I haven't been able to reproduce the error after changing `SplashScreen.preventAutoHideAsync` to `AppState.currentState === "active" && SplashScreen.preventAutoHideAsync()`

**Comment by Martijncvv** [comment]
> I haven't been able to reproduce the error after changing `SplashScreen.preventAutoHideAsync` to `AppState.currentState === "active" && SplashScreen.preventAutoHideAsync()`

Still showing up in our prod..
