### ISSUE TITLE
Type error in expo-gl module.

### ISSUE THREAD

**Issue by blue0316** [expo/expo#20518]
### Summary

This is a code from "expo-gl@12.0.1" module and you can find these between line 67 and 81 in "src/Canvas.tsx" file.
As you can see, there is only one question mark for "size.width" and no question mark for "size.height".
It comes with an type error and I wish you check and fix it.

```
  const onLayout = (event: LayoutChangeEvent) => {
    const {
      nativeEvent: {
        layout: { width, height },
      },
    } = event;

    if (width !== size?.width || height !== size.height) {
      setSize({ width, height });

      if (props.onLayout) {
        props.onLayout(event);
      }
    }
  };
```

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.3.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.2.0 - /usr/local/bin/npm
      Watchman: 2022.12.12.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      react: 18.0.0 => 18.0.0 
      react-native-tvos:  0.69.6-0 
      react-native-web: ^0.18.10 => 0.18.10 
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/blue0316/apple-tv-os-app.git

**Comment by gabrieldonadel** [comment]
Hi @blue0316 for that line to cause a crash `size` would have to be null,  in which scenario `width` from nativeEvent.layout is equal to `size?.width` and `size` is null? Do you have a minimal reproducible example?
