### ISSUE TITLE
expo-notifications, android device, eas development and preview build, getExpoPushTokenAsync returns "Default FirebaseApp is not initialized in this process..."

### ISSUE THREAD

**Issue by teewuane** [expo/expo#20513]
### Summary

I attempt to get an expo push token on an android device (not simulator) with `getExpoPushTokenAsync` and get this error.

```
Error: Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Default FirebaseApp is not initialized in this process com.myapp.mycompany. Make sure to call FirebaseApp.initializeApp(Context) first.
```

I use EAS cli 3.0.0, node 16.18.1, Expo SDK 47. I run the build on eas server (not locally).

I have not tested this on expo go because my app uses react-native-google-mobile-ads which will not work in expo go.

`token = await Notifications.getExpoPushTokenAsync({experienceId: '@myexpouser/myapp'});`

This returns `Possible Unhandled Promise Rejection` I guess because I'm not handling the error.

I'm using the new build system with EAS. I've seen others mention they need to have a `google-services.json` file included but I don't think they are doing the same build system as I am. Even if they are using eas, it doesn't mention that anywhere.

FIrebase is not one of my direct dependencies as I'm not using it anywhere else in my app.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      eas-cli: 3.0.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

```
import * as Notifications from 'expo-notifications';
import { Platform, Alert } from 'react-native';

async function registerForPushNotificationsAsync() {
	let token;

	if (Platform.OS === 'android') {
		Notifications.setNotificationChannelAsync('default', {
			name: 'default',
			importance: Notifications.AndroidImportance.MAX,
			vibrationPattern: [0, 250, 250, 250],
			lightColor: '#FF231F7C',
		});
	}

	const { status: existingStatus } = await Notifications.getPermissionsAsync();
	let finalStatus = existingStatus;
	if (existingStatus !== 'granted') {
		const { status } = await Notifications.requestPermissionsAsync();
		finalStatus = status;
	}

	if (finalStatus !== 'granted') {
		Alert.alert('Failed to get push token for push notification!');
		return;
	}

	console.log('about to getExpoPushTokenAsync.');
	token = await Notifications.getExpoPushTokenAsync({experienceId: '@myexpouser/myapp'});
	console.log(token)
	return token;
}
registerForPushNotificationsAsync()
```

**Comment by teewuane** [comment]
I found that I didn't have my FCM Server Key in Expo under "Credentials". I added it, rebuilt the project (with --clear-cache) and tried again, it still isn't working. I thought for sure that was going to solve my problem.

**Comment by teewuane** [comment]
Okay, I found this article, https://docs.expo.dev/push-notifications/using-fcm/?redirected , that mentioned I DO need the google-services.json file in my root and I need to refer to that file from app.json. I'm rebuilding now... Hoping this does the trick!

**Comment by teewuane** [comment]
That was it, I didn't have my app properly connected to Firebase. I needed the google-services.json in my codebase, app.json needed to reference that google-services.json, and the FCM Server Key added to the Configure > Credentials > Android > Application Identifier on the expo website.

**Comment by ekimcem** [comment]
hey @teewuane , happy to hear that you have solved your problem.

Have you also tried if it works with npx expo run:android --device command on local physical device devellopment ?

When I use EXPO GO , the android can get the token from expo and set it, but when i use native build that i mentioned above, it doesn't work properly. I get the same error with you

**Comment by aliaro428** [comment]
Once you've added this Expo code, you need to prebuild your app before running it.

` npx expo prebuild --platform android  --clean`

**Comment by TheKohan** [comment]
> hey @teewuane , happy to hear that you have solved your problem.
> 
> Have you also tried if it works with npx expo run:android --device command on local physical device devellopment ?
> 
> When I use EXPO GO , the android can get the token from expo and set it, but when i use native build that i mentioned above, it doesn't work properly. I get the same error with you

Hi,
Android notifications will run perfectly fine on your `development build` created with `npx expo run:android --device`, just make sure that you point to `google-services.json` in `app.json`, even if it is in root folder.

```json
  "android": {
    "googleServicesFile": "./google-services.json",
}
```

**Comment by monvanCe** [comment]
thank you for you solved and also you shared the problem. i'm gonna try it
