### ISSUE TITLE
NetInfo internet connection auto update is not working

### ISSUE THREAD

**Issue by shop-fluencer** [expo/expo#20511]
### Summary

Hello,

I want to show if the internet is online or offline constantly every time so if I disable my internet connection on my phone (with expo Go) then nothings happend. Why?

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.8
    Expo Workflow: managed

### Minimal reproducible example

```
  const [isConnected, setIsConnected] = useState(true);

  NetInfo.fetch().then(state => {
    if (state.isConnected && state.isInternetReachable) {
        setIsConnected(true);
    } else {
        setIsConnected(false);
    }
});

useEffect(() => {
    const unsubscribe = NetInfo.addEventListener((state) => {
        if (state.isConnected && state.isInternetReachable) {
            setIsConnected(true);
        } else {
            setIsConnected(false);
        }
    });
    if (isConnected) {

    } else {
        unsubscribe();
    }
    return () => {
        unsubscribe();
    };
}, []);

console.log(isConnected);
```

**Comment by alanjhughes** [comment]
Your unsubscribing whenever the state is not connected so you won't receive an update the next time the state changes.
