### ISSUE TITLE
Expo linear gradient damaged after using exp detach

### ISSUE THREAD

**Issue by frodoe7** [expo/expo#2051]
### Environment

> Environment:
>   OS: macOS High Sierra 10.13.2
>   Node: 10.5.0
>   Yarn: Not Found
>   npm: 6.1.0
>   Watchman: 4.9.0
>   Xcode: Xcode 9.3 Build version 9E145
>   Android Studio: 3.0 AI-171.4443003
> 
> Packages: (wanted => installed)
>   expo: ^28.0.0 => 28.0.0
>   react: 16.3.1 => 16.3.1
>   react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2
> 
> Diagnostics report:
>   https://exp-xde-diagnostics.s3.amazonaws.com/27mdmo7sn-76cd9caf-ce8b-44b8-9677-19eaa637c489.tar.gz

I detached the project to use Expkit (I test the app with Expo Android App) "http://bit.ly/2NTYPQ3"

### Steps to Reproduce

I detached my project , then - the application should work as the same
except one issue : the gradient not work , it always show a blank white background

the same code works well before detaching

```
<LinearGradient colors={["#2A2A72","#86fde8"]} style={{width:'100%' , height:'100%'}}>
.. some inner components
</LinearGradient>
```
to reproduce the issue , follow these steps

1. start a normal expo project with `create-react-native-app projectName`
2. use expo LinearGradient in your project will work fine
3. detach the project using `react-native eject`
4. test your application now = the LinearGradient should not work

### Expected Behavior
normal gradient as background (screenshot) : http://bit.ly/2NZ9nxj

### Actual Behavior
white gradient background (screenshot) : http://bit.ly/2vpRIqO

### Some mistakes - I may made
after using `react-native eject` I faced errors 
so I removed Android and IOS Folders to use `exp detach` again

**Comment by terribleben** [comment]
Thanks for the report. It's hard to tell what's going on without more context about the view hierarchy on your screen. Is it possible for you to create a minimal JS example app which reproduces this behavior when detached?

**Comment by frodoe7** [comment]
Hi @terribleben
It's possible but It's a bit hard , I did not made something like this before
so what's exact folders/files I have to upload ?
am I have to upload the node_modules folder because it's very big

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. This should now be fixed by using the `expo-linear-gradient` package in the bare workflow. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
