### ISSUE TITLE
Expo doesn't support RN 0.56 and Babel 7 

### ISSUE THREAD

**Issue by MrCheater** [expo/expo#2052]
I have conflicts babel versions in my project. I'm very sad

**Comment by terribleben** [comment]
You're right. There are some details on why we made this choice in the [intro of our SDK 29 release notes](https://blog.expo.io/expo-sdk-v29-0-0-is-now-available-f001d77fadf). The bottom line is that we think it would add a ton of work and frustration for many of our developers and not (yet) enough of a return to justify that work. We're eager to update to RN 0.56 once it makes sense for us!

We try to limit feature requests to [canny](https://expo.canny.io/feature-requests), so you're welcome to track this there.

**Comment by codejamninja** [comment]
I'm very sad. Another request for babel 7 and react native 0.56.0.
