### ISSUE TITLE
HLS Videos are not getting played.

### ISSUE THREAD

**Issue by shivnativehealth** [expo/expo#20525]
### Summary

Hello, In my react native project i am using both **expo-av** and **react-native-zoom-us** together. Things were working with the older versions. But now, zoom sessions i am able to open but videos playback using expo-av is not working, it keeps on loading. Have posted same issue in zoom-sdk github page as well, in search of any help (https://github.com/mieszko4/react-native-zoom-us/issues/249) Any insights or help will be greatly appreciated. Thanks.

Older versions:
expo-av: 10.2.0
react-native-zoom-us: 6.6.1

Newer version: 
expo-av: 10.2.0(no changed )
react-native-zoom-us: 6.14.1

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.11.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.5 => 0.66.5 
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

Any hls videos are not getting played using the expo-av library

**Comment by keith-kurak** [comment]
Hi, assuming this is an issue with the Expo SDK and not react-native-zoom-us, we would need a minimal example in Snack or a Github repo so we could see how you use these two libraries together. I just tried an HLS stream using our [Video example snack](https://docs.expo.dev/versions/latest/sdk/video/) (which may be a good starting point for a minimal repro), and that was working fine.
