### ISSUE TITLE
expo camera scanner for web

### ISSUE THREAD

**Issue by wishgoods** [expo/expo#20523]
### Summary

Hi,
I am using the expo-camera library which works perfect for me when I'm taking pictures or scanning qr barcode.
**The issue I would like to report is rising when I scan code 128 type**, then I get null (not recognized) result for any type (also code 93 btw).

I have to use this library because the BC-scanner does not support web.
Thank you for reviewing my ticket and I hope you will be able to take a look at this.
Have a nice day.

### What platform(s) does this occur on?

Web

### Environment

react native with expo cli 

### Minimal reproducible example

import { Camera, CameraType } from "expo-camera";
import React, { useEffect, useState } from "react";
import {
  View,
  StyleSheet,
  ImageBackground,
} from "react-native";
import { BarCodeScanner } from "expo-barcode-scanner";
import Made4net_Spinner from "./Made4net_Spinner";
import { Button } from "made4net-react-native";
import { Center } from "native-base";

const Made4netCamera = (props) => {
  const [type, setType] = useState(CameraType.back);
  const [permission, setPermission] = useState(null);
  const [camera, setCamera] = useState(null);
  const [image, setImage] = useState(null);
  const [finished, setFinished] = useState(false);
  const [barcode,setBarcode]= useState(null);

  const toggleCameraType() {
    setType((current) =>
      current === CameraType.back ? CameraType.front : CameraType.back
    );
  }

  const takePicture = () => {
    if (camera) {
      camera.takePictureAsync({ onPictureSaved: onPictureSaved });
    }
  };
  const onPictureSaved = (photo) => {
    setImage(photo.uri);
    
  };

  const finishOperation=()=>{
    props.closeCamera(false)
    setFinished(true);
    props.scanCode(barcode)
  }
  useEffect(() => {
    Camera.requestCameraPermissionsAsync().then((res) => setPermission(res));
  }, []);
  const handleBarcodeScanned=(scan_result)=>{
    setBarcode(scan_result.data);
  }

  return!finished?( image ? (
    <Center style={styles.container}>
      <ImageBackground style={styles.container} source={image}>
        <Button label="Confirm" onPress={finishOperation}/>
      </ImageBackground>
    </Center>
  ) : (
    <View style={styles.container}>
      {permission ? (
        <Camera
          style={styles.camera}
          type={type}
          barCodeScannerSettings={{
            barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],    //also tried that with camera constant types
          }}
          onBarCodeScanned={handleBarcodeScanned}
          ref={(ref) => {
            setCamera(ref);
          }}
        >
          <View style={styles.buttonContainer}>
            <Button  style={styles.button} onPress={toggleCameraType} label="Flip Camera"/>
            <Button  style={styles.button} onPress={takePicture} label="Confirm"/>
          </View>
        </Camera>
      ) : (
        <Made4net_Spinner name="checking permmision" />
      )}
    </View>)
  ):null;
};

export default Made4netCamera;

**Comment by Simek** [comment]
Hello @wishgoods, after looking at attached code it seems like you are missing desired code type in `barCodeTypes` array.

As described in docs, this array need to contain all of the code types you would like to support:
* https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/#barcodetypes

So in your case, the types array should looks something like that:
```jsx
{
  barCodeTypes: [
    BarCodeScanner.Constants.BarCodeType.code128,
    BarCodeScanner.Constants.BarCodeType.code93
  ],
}
```
