### ISSUE TITLE
npx expo run:andorid Not working Expo Sdk 47 

### ISSUE THREAD

**Issue by ASBirinci** [expo/expo#20538]
### Summary

I can't get build for android with expo.  
I run the` npx expo run:andorid `command throw an error 

```
BU¦LD FAILED in 2s
D:\WorkSpace\Earşiv\temp\EArsiv_Fatura\Expo-Sdk-Update\AwesomeProject\android\gradlew.bat exited with non-zero code: 1
Error: D:\WorkSpace\Earşiv\temp\EArsiv_Fatura\Expo-Sdk-Update\AwesomeProject\android\gradlew.bat exited with non-zero code: 1
```
Because of these problems, I created an empty project and tried it, the same problem continues, I explained it in more detail below.

### SDK Version

47

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: bare
```

### Minimal reproducible example

I can't get build for android with expo. So I am triying to create new expo empty projet.

Expo template Download

` npx create-expo-app AwesomeProject`

this is my Package Json
```
{
  "name": "awesomeproject",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~47.0.8",
    "expo-status-bar": "~1.4.2",
    "expo-dev-client": "~1.3.1",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "expo-splash-screen": "~0.17.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```
```
eas build:configure
npx expo run:android
```
```
BU¦LD FAILED in 2s
D:\WorkSpace\Earşiv\temp\EArsiv_Fatura\Expo-Sdk-Update\AwesomeProject\android\gradlew.bat exited with non-zero code: 1
Error: D:\WorkSpace\Earşiv\temp\EArsiv_Fatura\Expo-Sdk-Update\AwesomeProject\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\Birin\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.cp.emit (C:\Users\Birin\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (C:\Users\Birin\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at spawnGradleAsync (C:\Users\Birin\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:83:28)
    at assembleAsync (C:\Users\Birin\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\spawnGradleAsync.ts:57:16)
    at actionAsync (C:\Users\Birin\AppData\Roaming\npm\node_modules\expo-cli\src\commands\run\android\runAndroid.ts:145:22)
```

**Comment by Kudo** [comment]
hi there! it looks like you don't have android studio or android java sdk installed on your machine. you could also try [EAS Build](https://docs.expo.dev/build/introduction/) to leverage the cloud build service even you don't have android sdk installed locally.

**Comment by ASBirinci** [comment]
Hi Kudo , Thank you For reply .
This The Andoid Sdk for expo sdk 47 
![android](https://user-images.githubusercontent.com/79809634/208719743-79a989b1-fa86-491f-a2d6-61fffc6f05b3.png)

And My java version 
```
PS D:\WorkSpace\Yeni klasör (5)\my-test> java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```
Since I'm using a native module, I need to be able to build it locally.

Which of the SDk packages is missing?

**Comment by Kudo** [comment]
when you run `npx expo-env-info@latest`, it should expose android sdk information. did you have `ANDROID_HOME` and `ANDROID_SDK_ROOT` environment variables on your host?

**Comment by ASBirinci** [comment]
I run the `npx expo-env-info@latest` 

```
C:\Users\Birin>npx expo-env-info@latest
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

```
Skd information does not view .

this is my android sdk location.

![image](https://user-images.githubusercontent.com/79809634/208732912-56f21643-48d6-46ca-985d-1fbea4f64c75.png)

These are My **environment variables**

![image](https://user-images.githubusercontent.com/79809634/208733217-f02cda9b-7cf0-4270-aabd-1b1a4dc389dd.png)

**Comment by Kudo** [comment]
could you share the output when executing `set` command from the terminal shell?

**Comment by ASBirinci** [comment]
This is the Output: 
![image](https://user-images.githubusercontent.com/79809634/208752840-b7bbc36d-8e2c-4020-87d6-e36e87d8ec7a.png)

**Comment by Kudo** [comment]
sorry just notice it's on powershell, or maybe we could try run from node directly.
```
node -e "console.log(Object.entries(process.env).filter(([k,v]) => k.startsWith('ANDROID')))"
```

**Comment by ASBirinci** [comment]
This is the output  of the code : 
![image](https://user-images.githubusercontent.com/79809634/208880796-5b165327-65e9-4db2-b336-be85d1b414b2.png)

**Comment by ASBirinci** [comment]
I would like to add this information. When I used .Expo sdk 44, I was able to get builds without any problems.
