### ISSUE TITLE
EXPO STUCK ON SPLASH SCREEN

### ISSUE THREAD

**Issue by daniimd** [expo/expo#20530]
### Summary

I'm submitting the build to the store but I'm stuck on the splash screen, location works normally.
Can anyone help me?? Happens on IOS and Android platform.

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-32 | Google Play Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: bare
```

### Minimal reproducible example

 works normally

**Comment by keith-kurak** [comment]
Hi,  If you can provided a minimal reproduction as a Snack or github repo, that would give us the best chance of tracking this down. If you cannot reproduce the issue, you may want to look into using Logcat to find if any warnings or errors occur when the splashscreen appears ([described here](https://docs.expo.dev/workflow/debugging/#production-errors)). There may be an error happening behind the scenes that is causing the splashscreen to be stuck. Also be sure to compare your code against [our SplashScreen example code ](https://docs.expo.dev/versions/latest/sdk/splash-screen/)to make sure the splash screen is being dismissed properly.

**Comment by daniimd** [comment]
> Olá, Se você puder fornecer uma reprodução mínima como um repositório Snack ou github, isso nos dará a melhor chance de rastreá-lo. Se você não conseguir reproduzir o problema, convém usar o Logcat para descobrir se algum aviso ou erro ocorre quando a tela inicial aparece ( [descrito aqui](https://docs.expo.dev/workflow/debugging/#production-errors) ). Pode haver um erro acontecendo nos bastidores que está fazendo com que a tela inicial fique travada. Certifique-se também de comparar seu código com [nosso código de exemplo SplashScreen](https://docs.expo.dev/versions/latest/sdk/splash-screen/) para garantir que a tela inicial esteja sendo descartada corretamente.

I'm trying ways to get some log but I'm not getting any result.
I already have another project in the store and I used it as a base, the only thing different that I used was the `victory pie` graphics library and `google fonts`, which according to the documentation everything is done correctly and I am not alerted to any errors or warnings.

By running the command `eas build --profile development --platform android`, I downloaded the apk and only got this screen, which didn't help me much

eas.json: 
```
 {
  "cli": {
    "version": ">= 2.1.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "android": {
        "buildType": "apk"
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

![Screenshot_20221219-160617_brainvest](https://user-images.githubusercontent.com/36265891/208663469-8762fc78-8195-4365-a6f0-48825752a4ca.jpg)
