### ISSUE TITLE
(Android) Notifications.addListener is only called for first notification

### ISSUE THREAD

**Issue by Triggybet** [expo/expo#2054]
**Pre-requisit:**
Any android device or emulator
EXPO SDK 29.0.0

**Reproduction:**
1. Create new expo project using Expo XDE
2. Set up expo notifications as per https://docs.expo.io/versions/latest/guides/push-notifications
3. Use the push notification tool (https://expo.io/dashboard/notifications)
4. Send two notifications (with app in background)
5. Click on any of the notifications
=> App open up as expected!
7. Put app in background / Close app
8. Click on second notification

**Result:**
App is never opened as Notifications.addListener never gets called. 

**Expected result**
App should open up

**Comment:**
I have also tried SDK 28.0.1. We are quite sure that this featured used to work up until a week or so ago. I added this story https://github.com/expo/expo/issues/1915 a while back which may or may not be related.

**Comment by Triggybet** [comment]
Works as expected now after fix 👍

**Comment by mikolajadamowicz** [comment]
This issue still remains on expo 29.0.0. After opening inactive app through selecting the notification everything works as it should. Then if i try to select new notification (foreground and background) nothing happens and Notifications.addListener is not called.

**Comment by esamelson** [comment]
@mikolajadamowicz could you make sure you have the latest version of Expo client (2.7.2) or if you're using a standalone app to test, make a new build?

**Comment by mikolajadamowicz** [comment]
@esamelson I'm running on expo@29.0.1-rc.0 made a fresh yarn install and exp build just now. It's not working on standalone. 
Here's a video for better understanding: [https://streamable.com/6dp2r](url)
Also here's my issue in detail #2135

**Comment by mikolajadamowicz** [comment]
Here's git repo https://github.com/mikolajadamowicz/PushTest

**Comment by albertocolella** [comment]
Can confirm what @mikolajadamowicz wrote, I would only add that notifications works as expected while app is on Expo and they stop working when the app is built with `exp build:android`

**Comment by Triggybet** [comment]
**(Update: I updated to SDK 30, just in case, and did a fresh APK build. Now the issue seems to be gone on my Samsung S9. Don't know if Expo's build process has been updated with a fix or if the SDK update did anything. But on our end it seems to work. Will continue testing on my other devices too.)**
