### ISSUE TITLE
[docs] Android adaptive icon `monochromeImage` in docs but fails validation and build

### ISSUE THREAD

**Issue by jonjamz** [expo/expo#20549]
### Summary

I am using SDK 47.

In the [app icons documentation](url) it says to "Use the `android.adaptiveIcon.monochromeImage` field in **app.json** to specify your monochrome image."

When I add this field to app.json, I get a hint that it's not allowed, and when I run a development build with EAS the expo doctor step says:

`[stderr] [15:08:47]  • Field: android.adaptiveIcon - should NOT have additional property 'monochromeImage'.`

I have not been able to test whether the monochrome icon actually works. Is this perhaps an upcoming feature?

### Link to the related docs page

https://docs.expo.dev/guides/app-icons/#android

**Comment by brentvatne** [comment]
this was merged a few weeks ago in https://github.com/expo/expo/pull/20074 but not released yet. we need to update the docs to indicate that this is not yet available. sorry for the confusion

**Comment by krestaino** [comment]
I'm getting build errors on SDK 48 beta when setting `android.adaptiveIcon.monochromeImage`. Did this feature ship with SDK 48? It's mentioned in the docs.

https://docs.expo.dev/versions/v48.0.0/config/app/#monochromeimage

```
[PREBUILD] Using node to generate images. This is much slower than using native packages.
[PREBUILD] › Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
[PREBUILD] - Config syncing
[PREBUILD] ✖ Config sync failed
[PREBUILD] TypeError [ERR_INVALID_ARG_TYPE]: [android.dangerous]: withAndroidDangerousBaseMod: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
[PREBUILD] TypeError [ERR_INVALID_ARG_TYPE]: [android.dangerous]: withAndroidDangerousBaseMod: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
[PREBUILD]     at writeFile (node:fs:2155:5)
[PREBUILD]     at go$writeFile (/tmp/kevin/eas-build-local-nodejs/18e1219a-b2f1-4e26-8e46-82decdb62dcb/build/open-podcasts/node_modules/graceful-fs/graceful-fs.js:138:14)
[PREBUILD]     at Object.writeFile (/tmp/kevin/eas-build-local-nodejs/18e1219a-b2f1-4e26-8e46-82decdb62dcb/build/open-podcasts/node_modules/graceful-fs/graceful-fs.js:135:12)
[PREBUILD]     at /tmp/kevin/eas-build-local-nodejs/18e1219a-b2f1-4e26-8e46-82decdb62dcb/build/open-podcasts/node_modules/universalify/index.js:8:12
[PREBUILD]     at new Promise (<anonymous>)
[PREBUILD]     at Object.writeFile (/tmp/kevin/eas-build-local-nodejs/18e1219a-b2f1-4e26-8e46-82decdb62dcb/build/open-podcasts/node_modules/universalify/index.js:7:14)
[PREBUILD]     at /tmp/kevin/eas-build-local-nodejs/18e1219a-b2f1-4e26-8e46-82decdb62dcb/build/open-podcasts/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:326:30
[PREBUILD]     at async Promise.all (index 0)
[PREBUILD]     at async generateMonochromeImageAsync (/tmp/kevin/eas-build-local-nodejs/18e1219a-b2f1-4e26-8e46-82decdb62dcb/build/open-podcasts/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:315:3)
[PREBUILD]     at async configureAdaptiveIconAsync (/tmp/kevin/eas-build-local-nodejs/18e1219a-b2f1-4e26-8e46-82decdb62dcb/build/open-podcasts/node_modules/@expo/prebuild-config/build/plugins/icons/withAndroidIcons.js:207:5)
[PREBUILD] error Command failed with exit code 1.
[PREBUILD] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[PREBUILD] 
Error: yarn exited with non-zero code: 1
    at ChildProcess.completionListener (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/spawn-async/build/spawnAsync.js:41:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/turtle-spawn/dist/index.js:27:47)
    at runExpoCliCommand (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/utils/project.js:31:47)
    at prebuildAsync (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/common/prebuild.js:20:43)
    at /home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/builders/android.js:32:44
    at BuildContext.runBuildPhase (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/context.js:83:34)
    at buildAsync (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/builders/android.js:26:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runBuilderWithHooksAsync (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/builders/common.js:13:13)
    at async Object.androidBuilder (/home/kevin/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/builders/android.js:15:12)

Build failed
Unknown error. See logs for more information.
    Error: npx exited with non-zero code: 1
```

**Comment by alxjrvs** [comment]
I am also seeing the behavior mentioned by @krestaino above. On `expo 48.0.4`.

**Comment by krestaino** [comment]
@amandeepmittal Can you reopen this issue?

**Comment by roma-hladilka** [comment]
Have this issue too, added local icon to android.adaptiveIcon.monochromeImage in app.json, build failed

**Comment by amandeepmittal** [comment]
The fix has been applied and will update here once the patch is available in the SDK.

Sorry for the inconvenience!

**Comment by Kudo** [comment]
we've published the fix in `expo@48.0.15`. please try to upgrade and let us know whether it works for you. thanks!

**Comment by fobos531** [comment]
Hey @alxjrvs , might I ask what dimensions you used for the monochrome icon? I tried using 72x72 px as suggested in the official android design docs but my monochrome icon always ends up looking super weird? Even better, would you mind sharing your icon as a reference?

**Comment by alxjrvs** [comment]
@fobos531 Hey Fobos, happy to help. 

I remember we had some similar issues trying to follow the android docs. This is the image we used:

 ![android-monochrome-icon](https://github.com/expo/expo/assets/174825/bdd0db75-994d-4921-baba-7922cb82878f)
 
 As you can tell, definitely not 72x72px (clocking in at 512x512px). 
 
 Hope this helps!

**Comment by kuldip-simform** [comment]
Even after adding a monochrome image my app is not getting a themed icon.

![Screenshot_1691400552](https://github.com/expo/expo/assets/104821076/c1702fca-d56f-4b70-b311-d5e189e1ec98)

<img width="649" alt="Screenshot 2023-08-07 at 2 59 34 PM" src="https://github.com/expo/expo/assets/104821076/a8a7eb49-74f6-415d-a97f-b687732dc36c">

![monochrome-icon](https://github.com/expo/expo/assets/104821076/2af174db-fc36-475c-8ab2-e1911f6f6193)

Can anyone tell me what I am doing wrong here?
@alxjrvs @fobos531 any leads will be greatly helpful to me.
