### ISSUE TITLE
[docs] StoreReview docs should talk about what happens if user gives review or not

### ISSUE THREAD

**Issue by forki** [expo/expo#20553]
### Summary

I can't figure out how to determine if a user actually gave a review after calling StoreReview.requestReview.
Does it even matter?
I don't want to show the review dialog a second time when the user already gave a review.
Some threads on the internet claim this is already handled internally. Is it?

Please elaborate in the docs.
Thanks

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/storereview/#storereviewrequestreview

**Comment by mariomurrent-softwaresolutions** [comment]
It should be handed, as the review dialog won't be shown if the user has already voted.
So there shouldn't be any thing to do from your side

**Comment by amandeepmittal** [comment]
Hey @forki, it's not possible to know if the user actually provided a review or not when using `expo-store-review`. I'm also not sure if this possible to determine with underlying native APIs (on Android and iOS). However, you can [open a feature request](https://expo.canny.io/feature-requests) or send a pull request to add that functionality if you know how.

**Comment by mariomurrent-softwaresolutions** [comment]
@amandeepmittal No, its not possible, because it is completely handled by the OS. So if the user already reviewed your app, the dialog won't be shown

**Comment by amandeepmittal** [comment]
Thanks for your input @mariomurrent-softwaresolutions!
