### ISSUE TITLE
Print with orientation parameter does not produce expected results when combined with `html`, but works with `markupFormatterIOS`

### ISSUE THREAD

**Issue by brownbl1** [expo/expo#2055]
### Environment
Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/crosswaypa-07745a1b-92a8-4d5f-8aa0-fdb9b3f3d5dd.tar.gz

Targeting iPad/iOS via Expo app

### Steps to Reproduce
Print a simple html document to a Brother label printer:
```js
Print.printAsync({
  printerUrl: 'the url',
  orientation: Print.Orientation.landscape,
  // markupFormatterIOS: `
  html: `
<div>
  Hello World!
</div>
`,
})
```
### Expected Behavior
I expected the text of the document to be printed in landscape. 

### Actual Behavior
Instead of printing landscape, the text still prints in portrait, but the label size is cropped so that it seems as if the dimensions have been flipped and scaled down without the text actually rotating.

Portrait
![image](https://user-images.githubusercontent.com/2136925/43464363-f34394b2-94a8-11e8-8b60-36c36c2e6d8f.png)

Landscape
![image](https://user-images.githubusercontent.com/2136925/43463480-abd7ca50-94a6-11e8-9cec-544f6cbf8351.png)

From the images it is clear that in landscape, the label is simply cut more quickly so that the ratio stays the same, only flipped. 

I am not sure if this is a problem with my printer or with the implementation, but it works as expected with the `markupFormatterIOS` property instead of `html`. I noticed in the documentation that it states this property might disappear in [future versions](https://docs.expo.io/versions/latest/sdk/print#markupformatterios-string----available-on-ios-only). I am requesting that it not be removed as it is the only way I've been able to get landscape printing working. 

### Reproducible Demo
https://snack.expo.io/HJ2FskRE7

**Comment by terribleben** [comment]
Thank you for the report. I'm not sure how these parameters are supposed to interact with each other. @tsapeta can you provide any other info?

**Comment by tsapeta** [comment]
Hey @brownbl1,
Are these images an actual or expected behavior? Maybe I'm wrong, but they look as expected.
Anyway, I'll try to test it out soon, thanks for a demo!

I'm fine with keeping `markupFormatterIOS` option if you need it and it turns out it cannot be fixed in `html` implementation. These are actually two different implementations and I've found `html` is just better as a recommended option because it works just like on Android and is more configurable.

**Comment by brownbl1** [comment]
Thanks for checking it out. In my view, the first image is correct. It comes out of the label printer in portrait mode and you can tell that the width (along the leading edge) is shorter than the height. 

But the second label is not what I was hoping for. The text is still in a portrait orientation, but the label is cut at a much shorter height. This makes it look like landscape, but I was actually expecting the text to be rotated and the shape (size) of the label to remain constant. Instead it seems like it cropped the size of the label (and shrunk the text to maintain aspect ratio). Think about how a normal landscape print job would come out of a regular printer. The size of the page wouldn't change, but the text would merely be rotated. Here, the labels are actually different sizes and there is no rotation.
