### ISSUE TITLE
package.json "homepage" is not read by Metro Web

### ISSUE THREAD

**Issue by erisvaldojunior** [expo/expo#20562]
### Summary

Our CD serves the website in a subfolder like myurl.com/main/version/.

Before, when using Webpack, we set it on package.json "homepage": "/main/version", as said here https://docs.expo.dev/distribution/publishing-websites/

Now, after migrating to Metro Web, seems like this is not read anymore, and when the page is opened console shows an error because it is looking for /bundles/web-...js instead of /main/version/bundles/web-...js.

How should I set the path to metro web?

Related to https://github.com/facebook/metro/issues/908 

### What platform(s) does this occur on?

Web

### SDK Version

47

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
      Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
      npm: 9.2.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
      Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.5.1 => 0.5.1 
      @expo/webpack-config: 0.16.2 => 0.16.2 
      expo: ^47.0.0 => 47.0.6 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Distribute the website to a subfolder. Opening the page should show a 404 not found error on console when looking for /bundles/web-...js.

**Comment by erisvaldojunior** [comment]
Any updates on this?

**Comment by alessandro-bottamedi** [comment]
Same problem, is it an important feature, are there any alternatives to deploy to a subfolder?
