### ISSUE TITLE
[expo-sharing] Sharing doesn't work after canceling a Share

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#20567]
### Summary

I'm running this:

```
    const { uri } = await FileSystem.downloadAsync(
      'https://via.placeholder.com/300x600',
      FileSystem.documentDirectory + 'pepe.jpg'
    );

    Sharing.shareAsync(uri, {
      mimeType: 'image/jpeg',
      UTI: 'JPEG',
    });
```

- The "Share" popup is going to open.
- Select Instagram, BUT then cancel it.
- Select Instagram again... You'll see an error saying that "It can not be shared"

I didn't test it on Android.

### What platform(s) does this occur on?

iOS

### Environment

I'm trying it on Snack.expo.dev, using my iPhone

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 27, 31
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 27.0.3, 28.0.3, 29.0.2
        System Images: android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.6
    Expo Workflow: managed
```

### Minimal reproducible example

https://snack.expo.dev/@brodanoel/quiet-waffles

**Comment by behenate** [comment]
This issue has been fixed in https://github.com/expo/expo/pull/19656. It's available in SDK 47.

**Comment by evelant** [comment]
@BrodaNoel @behenate This appears to have regressed in SDK 48. On Android cancelling a share and then trying to share again fails with 

```
: Call to function 'ExpoSharing.shareAsync' has been rejected.
→ Caused by: Another share request is being processed now.
```

**Comment by behenate** [comment]
@Harshal2742  @evelant You are right, I only checked iOS because the issue was reported to iOS and seemed platform specific. I will look into the Android as well.

**Comment by axelmy318** [comment]
Hello,
Is there any fix or workaround yet ? If not, does someone know about an alternative package we could use ?
Thanks

**Comment by axelmy318** [comment]
after a few tests, it turns out that it only works in production, when the APK is installed on the client, but it is still impossible to share twice in developement

**Comment by nemanjamitric** [comment]
It doesn't work in the built version either for me... sdk 48 android

**Comment by axelmy318** [comment]
Still not working for me... I commanted on the PR you linked above

**Comment by behenate** [comment]
@axelmy318 Sorry for a late reply. Can you provide a minimal reproducible example?
I tried this example and it works fine for me in both bare and managed workflows:
```
const share = async () => {
  const { uri } = await FileSystem.downloadAsync(
    'https://via.placeholder.com/300x600',
    FileSystem.documentDirectory + 'pepe.jpg'
  );

  console.log('Waiting for share to resolve:');
  await Sharing.shareAsync(uri, {
    mimeType: 'image/jpeg',
    UTI: 'JPEG',
  });
  console.log('File has been shared');
};
```
