### ISSUE TITLE
[ios] expo prebuild doesn't respect platform specific extension

### ISSUE THREAD

**Issue by ebo7** [expo/expo#20569]
### Summary

I have a sample screen `SampleScreen.web.js` and  `SampleScreen.native.js` and only `SampleScreen.web.js` contains `expo-camera`. 
When I run `expo prebuild --platform ios` expo-camera is included in the prebuild (There is `ios/Pods/Local Podspecs/ExCamera.podspec.json` file)

### What platform(s) does this occur on?

iOS

### SDK Version

46

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /private/var/folders/ls/4h4kh3zx5pn5v09t5gp8xhl40000gn/T/xfs-a76631bd/node
      Yarn: 3.2.4 - /private/var/folders/ls/4h4kh3zx5pn5v09t5gp8xhl40000gn/T/xfs-a76631bd/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 30
        Build Tools: 29.0.3, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.16.27 => 0.16.27 
      babel-preset-expo: ^9.2.0 => 9.2.2 
      expo: ^46.0.9 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    Expo Workflow: managed

### Minimal reproducible example

* Add a sample file `Sample.web.js` and `Sample.native.js`
* Import `expo-camera` only in `Sample.web.js`
* Run prebuild for ios

**Comment by EvanBacon** [comment]
The native linking does not perform any tree-shaking and doesn't resolve all of the JavaScript modules. We cannot accurately shake modules as someone may intend to use it in the future with OTA code. You can manually exclude packages using the [autolinking configuration](https://docs.expo.dev/modules/autolinking/#exclude).
