### ISSUE TITLE
Firebase warning without information.

### ISSUE THREAD

**Issue by Meinl** [expo/expo#2057]
### Environment

Environment:
  OS: Windows 10
  Node: 10.4.1
  Yarn: Not Found
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz => 0.55.4

Android and iOS

### Steps to Reproduce

I've looking this for whole internet but I can't find anything related to this warning.

1. Installed through: npm -i firebase
2. Setting up a listener in actions file (redux) than is called inmediatly on componentDidMount.
3. Just listener is called, warning appear without further information.

### Expected Behavior

Nothing. Just don't appear that warning, unless got something bad (if case, can not find what).

### Actual Behavior

![img_0048](https://user-images.githubusercontent.com/8104557/43483899-e3ab911c-94da-11e8-885a-510f07351451.PNG)

**Comment by Meinl** [comment]
Any news about this? Thanks a lot!

**Comment by Meinl** [comment]
Does anyone know what is this warning that can help me?

**Comment by EvanBacon** [comment]
Closing to do inactivity. Seems like recent updates have fixed this however.
