### ISSUE TITLE
Eas Android build gets stuck on Run Gradlew

### ISSUE THREAD

**Issue by mauro-hike** [expo/expo#20578]
### Summary

Recently I've been having problems successfully running an android build on Expo. See this copy paste of the error here:

```w: FAILURE: Build failed with an exception.994[stderr] * What went wrong:995[stderr] Execution failed for task ':expo-permissions:compileReleaseJavaWithJavac'.996[stderr] > Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.997[stderr] * Try:998[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.999[stderr] * Get more help at https://help.gradle.org1000[stderr] BUILD FAILED in 5m 41s1001```

In the meantime I've updated the expo-permissions package to v13.2.0 (due to this issue, see: https://github.com/expo/expo/blob/main/packages/expo-permissions/CHANGELOG.md#1320--2022-04-18) but the builds still won't proceed. I assume it might has something to do with the settings in my build.gradle that were set to Java version 1.8 after running expo eject:

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

Does someone has an idea what might go wrong here? Went through lots of similar issues, but still haven't made any progress. Thanks a lot in advance :) 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

    "expo-dev-client": "~0.6.3",
    "expo-updates": "~0.10.13",
    "expo": "^43.0.0",
    "expo-permissions": "^13.0.3",

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 14.20.0 - ~/.config/nvm/14.20.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.17 - ~/.config/nvm/14.20.0/bin/npm
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 45.0.8
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.3 => 4.4.4
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: bare

### Reproducible demo

This issue involves a failing build, so I assume my log below should be enough.

**Comment by TheLukaDragar** [comment]
i have the same issue M1 Mac , fresh project

**Comment by Kudo** [comment]
hi there! each expo module has a compatible expo sdk. for expo sdk 43, the compatible expo-permissions is `~13.0.3` where doesn't support 13.2.0. so please try to update expo sdk if you need newer modules. thanks!
