### ISSUE TITLE
There was a problem loading the requested app. the Internet connection appears to be offline

### ISSUE THREAD

**Issue by fakemonkgin** [expo/expo#20579]
### Summary

error says offline while i'm online, can't load the page

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.8
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 19.2.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.12.1 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.9 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    Expo Workflow: managed

### Reproducible demo

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import { Profile } from "@lens-protocol/react-native-lens-ui-kit";

export default function App() {
  return (
    <Profile />
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by mariomurrent-softwaresolutions** [comment]
Can you provide a bit more details? Did you try it via the Expo App or Custom Dev Client or a full build on your iOS device?

**Comment by SohelIslamImran** [comment]
Same issue

**Comment by SohelIslamImran** [comment]
> Can you provide a bit more details? Did you try it via the Expo App or Custom Dev Client or a full build on your iOS device?

I have a Custom Dev Client Build. I have the same issue @mariomurrent-softwaresolutions 
![image](https://user-images.githubusercontent.com/76745339/210435029-af611a1a-5398-482a-807e-7dc6b3a903c1.png)

**Comment by mariomurrent-softwaresolutions** [comment]
Interesting. With WIFI and normal phone internet? Same errors?

**Comment by SohelIslamImran** [comment]
> Interesting. With WIFI and normal phone internet? Same errors?

Yes. Same error with physical device

**Comment by mariomurrent-softwaresolutions** [comment]
Is any other Firebase service working?

**Comment by SohelIslamImran** [comment]
> Is any other Firebase service working?

Seems auth is working.

**Comment by mariomurrent-softwaresolutions** [comment]
Hmm then it's maybe not your internet connection. Maybe some rules with the DB are wrong? Or tokens?

**Comment by SohelIslamImran** [comment]
@mariomurrent-softwaresolutions Resolved the issue : https://stackoverflow.com/a/71060875/17672428
