### ISSUE TITLE
eas build Compressing project files Error: EACCES: permission denied, copyfile

### ISSUE THREAD

**Issue by leonizZ** [expo/expo#20572]
### Summary

install fresh expo project
build sample apk using eas

run
eas build:configure

run
update eas.json from https://docs.expo.dev/build-reference/apk/
eas build -p android --profile preview

### What platform(s) does this occur on?

Android

### Environment

npx: installed 2 in 4.241s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.1 - ~/.nvm/versions/node/v14.20.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
      Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild

### Minimal reproducible example

install fresh expo project
build sample apk
eas build:configure

![image](https://user-images.githubusercontent.com/26314180/209084682-75b33751-11e0-4e4a-99b7-2ecc8909e8e6.png)

**Comment by leonizZ** [comment]
my bad, expo eas needs git folder I have return my git folder and its fix now!

**Comment by MohammedSowan** [comment]
having the same issue, can you tell me the steps to fix it? I'm new to expo and react native

**Comment by gdomenech98** [comment]
> having the same issue, can you tell me the steps to fix it? I'm new to expo and react native
Just "git init" into your expo application folder, and its fix :D. Hope you found this helpful

**Comment by yusufmafif** [comment]
@gdomenech98  thank you so muchhhh... its help me
