### ISSUE TITLE
Expo v29.0.0 asks to add Expo SDK even if app is not ejected

### ISSUE THREAD

**Issue by dmathewwws** [expo/expo#2058]
### Steps to Reproduce

1. use create-react-native-app to create a new package. If you run app on iOS simulator (for example), app works great.
2. update package.json to use expo 29.0.0 and update react-native to 0.55.4
3. Get error about requiring Expo SDK, even though app isn't ejected.

### Expected Behavior

No error message

### Actual Behavior

Get error "The Expo SDK requires expo to run"

<img width="409" alt="screen shot 2018-07-31 at 1 04 16 pm" src="https://user-images.githubusercontent.com/2018931/43484418-26a4a16a-94c3-11e8-9425-8e382d158dab.png">

**Comment by sjchmiela** [comment]
Hi, @dmathewwws! You will need to also edit `app.json` and set `expo.sdkVersion` to `29.0.0`. 🙂 This value tells Expo Client what version of SDK to run your app on. See https://docs.expo.io/versions/v29.0.0/workflow/upgrading-expo-sdk-walkthrough (it does not have a section for SDK 29 yet, but the steps should be similar).

`app.json` on a newly created CRNA project with upgraded dependencies contains now:

```json
{
  "expo": {
    "sdkVersion": "29.0.0"
  }
}
```

The error is gone and the app loads properly.

I'll close this issue tentatively, if you have any more questions feel free to ask!

**Comment by osdnk** [comment]
@sjchmiela ❤️

**Comment by Tbaut** [comment]
I get the same error with a fresh CRNA on my Android phone.
I simply did a `create-react-native-app my-app` and launched `expo start`

app.json contains:
```json
  "expo": {
    "sdkVersion": "30.0.0"
}
```

package.json is:
```json
{
  "name": "empty-project-template",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^30.0.0",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"
  }
}
```
Can you tell me what's wrong and what I should change?

**Comment by Tbaut** [comment]
:point_up_2: this got sorted out by installing globally `expo-cli 2.2.4`, cf  https://forums.expo.io/t/projects-producing-the-expo-sdk-requires-expo-to-run-error/15239/4?u=tbaut
