### ISSUE TITLE
Holiday season response times

### ISSUE THREAD

**Issue by keith-kurak** [expo/expo#20586]
Hi everyone!

Happy holidays! We’ll be closed for business from December 21 through January 8 while our team takes time to rest, recharge and spend time with loved ones, so responses from the Expo team here on Github, as well as on Discord, will slow down during this time. We’ll still be monitoring all of our services (i.e. builds, hosting, notifications) as usual at status.expo.dev.

Stay safe and we’ll see you after the holidays.

Thanks!

The Expo Team

**Comment by forki** [comment]
Have a nice holiday! Thanks for all the awesome work!
