### ISSUE TITLE
Android build fails due to jitpack server is down

### ISSUE THREAD

**Issue by ottob** [expo/expo#20585]
### Summary

It fails in the run gradlew step:
```
[stderr] FAILURE:
177
[stderr] Build failed with an exception.
178
[stderr] * What went wrong:
179
[stderr] Could not determine the dependencies of task ':app:mergeReleaseNativeLibs'.
180
[stderr] >
181
[stderr] Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
182
[stderr] >
183
[stderr] Could not resolve com.stripe:stripe-android:20.5.+.
184
[stderr] Required by:
185
[stderr] project :app > project :stripe_stripe-react-native
186
[stderr] >
187
[stderr] Failed to list versions for com.stripe:stripe-android.
188
[stderr] >
189
[stderr] Unable to load Maven meta-data from https://www.jitpack.io/com/stripe/stripe-android/maven-metadata.xml.
190
[stderr] >
191
[stderr] Could not GET 'https://www.jitpack.io/com/stripe/stripe-android/maven-metadata.xml'. Received status code 521 from server:
192
[stderr] >
193
[stderr] Could not resolve com.github.CanHub:Android-Image-Cropper:4.3.0.
194
[stderr] Required by:
195
[stderr]          project :app > project :expo > project :expo-image-picker
196
[stderr]       >
197
[stderr] Skipped due to earlier error
198
[stderr] * Try:
199
[stderr] > Run with --stacktrace option to get the stack trace.
200
[stderr] > Run with --info or --debug option to get more log output.
201
[stderr] > Run with --scan to get full insights.
202
[stderr] * Get more help at https://help.gradle.org
203
[stderr] BUILD FAILED in 3m 19s
```

It is not a stripe-react-native issue as pointed our here: https://github.com/stripe/stripe-react-native/issues/1247#issuecomment-1363110176

There is an expo forum thread for this issue here: https://forums.expo.dev/t/eas-android-build-fails/68494

And the jitpack issue: https://github.com/jitpack/jitpack.io/issues/5337

Right now it is impossible for us to build an android release.

### What platform(s) does this occur on?

Android

### Environment

n/a

### Minimal reproducible example

Start with minimal app. 
Maybe add stripe-react-native 
try to do an EAS build for android

**Comment by paradise** [comment]
Same here

**Comment by phacts** [comment]
Same, I've been unable to build all day...

JitPack has been down for around 18 hours at this point, and there's no telling when it will come back: https://www.jitpack.io/com/stripe/stripe-android/maven-metadata.xml

**Comment by redbluenat** [comment]
I have the same problem: 

>Could not resolve com.github.CanHub:Android-Image-Cropper:4.3.0.

**Comment by huzaifaonyxtec** [comment]
I have the same problem:

Could not resolve com.github.CanHub: Android-Image-Cropper:1.1.1

**Comment by paradise** [comment]
Are there any solutions? Builds ane releases are stucked. Is there any way to edit android `build.gradle` file when using expo managed flow ?

` Unable to load Maven meta-data from https://www.jitpack.io/com/stripe/stripe-android/maven-metadata.xml.`

**Comment by stharvey** [comment]
Same here, it has been more than 24hrs and JitPack support have been a no-show unfortunately.

I think we'll have to accept that we may not be able to build Android until the new year.

**Comment by paradise** [comment]
So, I managed to build my project, using custom expo plugin. I replaced jitpack with jcenter.

./plugins/withCustomAndroidBuildGradle.js

```
const {ConfigPlugin, withProjectBuildGradle} = require('@expo/config-plugins')

function replace(contents, match, replace) {
  if (!(match.test ? RegExp(match).test(contents) : contents.includes(match)))
    throw new Error('Invalid text replace in config')

  return contents.replace(match, replace)
}

const withCustomAndroidBuildGradle = (config) => {
  return withProjectBuildGradle(config, async (config) => {
    config.modResults.contents = replace(
      config.modResults.contents,
      "maven { url 'https://www.jitpack.io' }",
      `jcenter()`
    )
    return config
  })
}

module.exports = withCustomAndroidBuildGradle
```

app.json

```
{
	"expo": {
		...,
		"plugins": [
		  ...
		  "./plugins/withCustomAndroidBuildGradle.js"
		],
	}
}
```

**Comment by firas1220** [comment]
> jcenter

What is jcenter() please ?

**Comment by firas1220** [comment]
> So, I managed to build my project, using custom expo plugin. I replaced jitpack with jcenter.
> 
> ./plugins/withCustomAndroidBuildGradle.js
> 
> ```
> const {ConfigPlugin, withProjectBuildGradle} = require('@expo/config-plugins')
> 
> function replace(contents, match, replace) {
>   if (!(match.test ? RegExp(match).test(contents) : contents.includes(match)))
>     throw new Error('Invalid text replace in config')
> 
>   return contents.replace(match, replace)
> }
> 
> const withCustomAndroidBuildGradle = (config) => {
>   return withProjectBuildGradle(config, async (config) => {
>     config.modResults.contents = replace(
>       config.modResults.contents,
>       "maven { url 'https://www.jitpack.io' }",
>       `jcenter()`
>     )
>     return config
>   })
> }
> 
> module.exports = withCustomAndroidBuildGradle
> ```
> 
> app.json
> 
> ```
> {
> 	"expo": {
> 		...,
> 		"plugins": [
> 		  ...
> 		  "./plugins/withCustomAndroidBuildGradle.js"
> 		],
> 	}
> }
> ```



> So, I managed to build my project, using custom expo plugin. I replaced jitpack with jcenter.
> 
> ./plugins/withCustomAndroidBuildGradle.js
> 
> ```
> const {ConfigPlugin, withProjectBuildGradle} = require('@expo/config-plugins')
> 
> function replace(contents, match, replace) {
>   if (!(match.test ? RegExp(match).test(contents) : contents.includes(match)))
>     throw new Error('Invalid text replace in config')
> 
>   return contents.replace(match, replace)
> }
> 
> const withCustomAndroidBuildGradle = (config) => {
>   return withProjectBuildGradle(config, async (config) => {
>     config.modResults.contents = replace(
>       config.modResults.contents,
>       "maven { url 'https://www.jitpack.io' }",
>       `jcenter()`
>     )
>     return config
>   })
> }
> 
> module.exports = withCustomAndroidBuildGradle
> ```
> 
> app.json
> 
> ```
> {
> 	"expo": {
> 		...,
> 		"plugins": [
> 		  ...
> 		  "./plugins/withCustomAndroidBuildGradle.js"
> 		],
> 	}
> }
> ```

What is that `jcenter()` please?

**Comment by stharvey** [comment]
> So, I managed to build my project, using custom expo plugin. I replaced jitpack with jcenter.
> 
> ./plugins/withCustomAndroidBuildGradle.js
> 
> ```
> const {ConfigPlugin, withProjectBuildGradle} = require('@expo/config-plugins')
> 
> function replace(contents, match, replace) {
>   if (!(match.test ? RegExp(match).test(contents) : contents.includes(match)))
>     throw new Error('Invalid text replace in config')
> 
>   return contents.replace(match, replace)
> }
> 
> const withCustomAndroidBuildGradle = (config) => {
>   return withProjectBuildGradle(config, async (config) => {
>     config.modResults.contents = replace(
>       config.modResults.contents,
>       "maven { url 'https://www.jitpack.io' }",
>       `jcenter()`
>     )
>     return config
>   })
> }
> 
> module.exports = withCustomAndroidBuildGradle
> ```
> 
> app.json
> 
> ```
> {
> 	"expo": {
> 		...,
> 		"plugins": [
> 		  ...
> 		  "./plugins/withCustomAndroidBuildGradle.js"
> 		],
> 	}
> }
> ```

Thanks a lot for the suggestion.  Unfortunately I can't get that working, the build process still looks for jitpack.io

`[stderr] Could not GET 'https://www.jitpack.io/com/logrocket/logrocket/1.9.0/logrocket-1.9.0.pom'. Received status code 521 from server`

**Comment by firas1220** [comment]
> So, I managed to build my project, using custom expo plugin. I replaced jitpack with jcenter.
> 
> ./plugins/withCustomAndroidBuildGradle.js
> 
> ```
> const {ConfigPlugin, withProjectBuildGradle} = require('@expo/config-plugins')
> 
> function replace(contents, match, replace) {
>   if (!(match.test ? RegExp(match).test(contents) : contents.includes(match)))
>     throw new Error('Invalid text replace in config')
> 
>   return contents.replace(match, replace)
> }
> 
> const withCustomAndroidBuildGradle = (config) => {
>   return withProjectBuildGradle(config, async (config) => {
>     config.modResults.contents = replace(
>       config.modResults.contents,
>       "maven { url 'https://www.jitpack.io' }",
>       `jcenter()`
>     )
>     return config
>   })
> }
> 
> module.exports = withCustomAndroidBuildGradle
> ```
> 
> app.json
> 
> ```
> {
> 	"expo": {
> 		...,
> 		"plugins": [
> 		  ...
> 		  "./plugins/withCustomAndroidBuildGradle.js"
> 		],
> 	}
> }
> ```

Thank for the suggestion! I succeeded to overcome the jitpack issue! 🎉 by replacing it with **maven central repository** instead (I think that using jcenter() isn't a good approache following [Android Developers](https://developer.android.com/studio/build/jcenter-migration#:~:text=Warning%3A%20Don%27t%20include%20the%20jcenter()%20repository%20in%20your%20build%20config%20to%20avoid%20getting%20outdated%20dependencies.)) 

But I got a new issue 🤣 its with **expo-image-picker**
> [stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Could not determine the dependencies of task ':expo-image-picker:compileReleaseAidl'.
[stderr] > Could not resolve all task dependencies for configuration ':expo-image-picker:releaseCompileClasspath'.
[stderr]    > Could not find com.github.CanHub:Android-Image-Cropper:1.1.1.
[stderr]      Required by:
[stderr]          project :expo-image-picker
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 2m 47s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

What should I do here ? any suggestions are welcome.

**Comment by stharvey** [comment]
> So, I managed to build my project, using custom expo plugin. I replaced jitpack with jcenter.
> 
> ./plugins/withCustomAndroidBuildGradle.js
> 
> ```
> const {ConfigPlugin, withProjectBuildGradle} = require('@expo/config-plugins')
> 
> function replace(contents, match, replace) {
>   if (!(match.test ? RegExp(match).test(contents) : contents.includes(match)))
>     throw new Error('Invalid text replace in config')
> 
>   return contents.replace(match, replace)
> }
> 
> const withCustomAndroidBuildGradle = (config) => {
>   return withProjectBuildGradle(config, async (config) => {
>     config.modResults.contents = replace(
>       config.modResults.contents,
>       "maven { url 'https://www.jitpack.io' }",
>       `jcenter()`
>     )
>     return config
>   })
> }
> 
> module.exports = withCustomAndroidBuildGradle
> ```
> 
> app.json
> 
> ```
> {
> 	"expo": {
> 		...,
> 		"plugins": [
> 		  ...
> 		  "./plugins/withCustomAndroidBuildGradle.js"
> 		],
> 	}
> }
> ```

Thanks a lot for this suggestion.  The build process now goes past the logrocket error but now other dependencies can't be resolved:

```
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Could not determine the dependencies of task ':app:buildReleasePreBundle'.
[stderr] > Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
[stderr]    > Could not find com.github.adaptyteam:AdaptySDK-Android:1.12.0.
[stderr]      Searched in the following locations:
[stderr] - http://10.4.1.4:8081/artifactory/libs-release/com/github/adaptyteam/AdaptySDK-Android/1.12.0/AdaptySDK-Android-1.12.0.pom
```

I think I'll just have to wait to see if the jitpack issue is resolved soon.

**Comment by stharvey** [comment]
![twitter-ss](https://user-images.githubusercontent.com/23450702/209322476-3705a14e-eaa3-48d9-a5f1-a34bd1e0ded8.png)


Maybe this will be fixed soon!

**Comment by stharvey** [comment]
All sorted :-) [](https://github.com/jitpack/jitpack.io/issues/5337#issuecomment-1363840754)

**Comment by AlexCatch** [comment]
Expo should seriously consider if they need to be using Jitpack for anything or if they can use alternatives - builds being entirely broken for 21+ hours without any acknowledgement from the Jitpack team is frankly unacceptable; there are much better alternatives that are much more reliable.

**Comment by ottob** [comment]
Yes, resolved for now.

**Comment by linus-edor** [comment]
> I have the same problem:
> 
> Could not resolve com.github.CanHub: Android-Image-Cropper:1.1.1

Hi, please how did you resolve this?
