### ISSUE TITLE
Push Notifications are showing on iOS/Foreground but not showing on Android/Foreground

### ISSUE THREAD

**Issue by jim-hr** [expo/expo#20598]
### Summary

Push Notifications are showing on iOS/Foreground but not showing on Android/Foreground.

handleNotification is returning shouldShowAlert set to true.  Confirmed that handleNotification is called when push notification is sent to Android/Foreground.

If this is the desired "inconsistent" behavior, what is the workaround to cause push notifications to show on Android/Foreground?  Generate Local notification?  Example?

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.1.1 - /usr/local/bin/npm
      Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 31.0.0, 32.0.0, 33.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      expo: ~47.0.9 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Using the sample in the Expo Guide.

https://docs.expo.dev/push-notifications/overview/

**Comment by paradise** [comment]
+1 for me on android. When app is in foreground, I see notification in the status bar, but notification popup does not appear. My setup is default from expo docs.

On iOS notification appears normally.

**Comment by paradise** [comment]
I managed to fix it, reading android docs. You need to set HIGH importance for android channel. In expo docs [here](https://docs.expo.dev/push-notifications/push-notifications-setup/) example has `AndroidImportance.MAX` parameter. However, reading about importance in [android docs](https://developer.android.com/develop/ui/views/notifications/channels#importance), I discovered, that from Android 8.0 maximum priority is HIGH, and if you set MAX priority, I think android 8.0+ does not understand it and sets the level to UNKNOWN ot DEFAULT. That's why notifications are not shown.

```
if (Platform.OS === 'android') {
      Notifications.setNotificationChannelAsync('default', {
        name: 'default',
        importance: Notifications.AndroidImportance.HIGH,
        vibrationPattern: [0, 250, 250, 250],
        lightColor: '#FF231F7C',
      })
    }
```
