### ISSUE TITLE
SDK 47 installs incompatible version of Stripe using managed workflow on Android

### ISSUE THREAD

**Issue by Sascha1251** [expo/expo#20597]
### Summary

Expo SDK 47 installing/upgrading [Stripe](https://docs.expo.dev/versions/latest/sdk/stripe/) installs version 0.19.0. 

When I try to create an android APK, the build is failing with 26 errors like this one:
```
[stderr]      26.  Dependency 'androidx.annotation:annotation-experimental:1.3.0' requires libraries and applications that
[stderr]            depend on it to compile against version 33 or later of the
[stderr]            Android APIs.
[stderr]      
[stderr]            :app is currently compiled against android-31.
[stderr]      
[stderr]            Also, the maximum recommended compile SDK version for Android Gradle
[stderr]            plugin 7.2.1 is 32.
[stderr]      
[stderr]            Recommended action: Update this project's version of the Android Gradle
[stderr]            plugin to one that supports 33, then update this project to use
[stderr]            compileSdkVerion of at least 33.
[stderr]      
[stderr]            Note that updating a library or application's compileSdkVersion (which
[stderr]            allows newer APIs to be used) can be done separately from updating
[stderr]            targetSdkVersion (which opts the app in to new runtime behavior) and
[stderr]            minSdkVersion (which determines which devices the app can be installed
[stderr]            on).
```

When I install @stripe/stripe-react-native version 0.13.1 (mentioned here for SDK 46 https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md) everything is working fine

There is a similar issue for the bare workflow (https://github.com/expo/expo/issues/20195), however, as version 0.19.0 is the recommended version for SDK 47, I would expect it to work out of the box.
As a workaround, I'm using version 0.13.1, and there everything is working fine. Nevertheless, as the official version of SDK 47 is 0.19.0, I would expect everything to work out of the box or at least some additional information in the documentation.
Could you please have a look and adjust accordingly?

Thank you for your support!

### What platform(s) does this occur on?

Android

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.21.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ^47.0.0 => 47.0.9
    Expo Workflow: managed
```

### Minimal reproducible example

1. [Create a new Expo app](https://docs.expo.dev/get-started/create-a-new-app/)
2. Install Stripe: npx expo install @stripe/stripe-react-native - you will not need to configure the plugin.
3. Trigger an eas build (in my case for an APK)

**Comment by goughjo02** [comment]
Yes thank you. I encountered this error after upgrading to expo 47. Downgrading to `@stripe/stripe-react-native@0.13.1` fixed it for me.

**Comment by Kudo** [comment]
hi there! the `@stripe/stripe-react-native` requires android `compileSdkVersion` 33. you could use expo-build-properties to change the `compileSdkVersion` to 33 in a managed project: https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeandroid
