### ISSUE TITLE
upgrade SDK to 44, in standalone apps splash screen was showing then the screen went white and nothing happened

### ISSUE THREAD

**Issue by hotaryuzaki** [expo/expo#20594]
### Summary

I was upgrading the SDK sequentially from SDK 43 to 44.
in standalone apps splash screen was showing then the screen went white and nothing happened.
my apps is bare workflow and i follow the upgrade instruction [here](https://blog.expo.dev/expo-sdk-44-4c4b8306584a )
i suspect this error because of expo-updates, we using expo-updates for our OTA.

this is the error from adb logcat:

```
12-23 22:12:23.398   702 19253 D DnsProxyListener: GetAddrInfoHandler::run: {graph.facebook.com 150 150 150 983190 10994 0}
12-23 22:12:23.398   702 19253 E getaddrinfo: android_getaddrinfofornetcontext: explore_numeric: ai_family=10 ai_socktype=1 ai_protocol=6
12-23 22:12:23.398   702 19253 E getaddrinfo: explore_numeric_scope
12-23 22:12:23.398   702 19253 E getaddrinfo: explore_numeric_scopehostname: g
12-23 22:12:23.398   702 19253 E getaddrinfo: explore_numeric_scopecp is NULL
12-23 22:12:23.398   702 19253 E getaddrinfo: android_getaddrinfofornetcontext: explore_numeric: ai_family=2 ai_socktype=1 ai_protocol=6
12-23 22:12:23.398   702 19253 E getaddrinfo: explore_numeric_scope
12-23 22:12:23.398   702 19253 E getaddrinfo: explore_numeric_scopehostname: g
12-23 22:12:23.398   702 19253 E getaddrinfo: explore_numeric_scopescoped does not exist
12-23 22:12:23.398   702 19253 E getaddrinfo: android_getaddrinfofornetcontext: explore_fqdn(): ai_family=0 ai_socktype=1 ai_protocol=6
12-23 22:12:23.398   702 19253 E getaddrinfo: res_queryN: (1, 1)
12-23 22:12:23.398   702 19253 E res_send: res_nsend
12-23 22:12:23.399   702 19253 E res_send: res_nsend: Querying server (# 1) address = 192.168.1.1
12-23 22:12:23.399   702 19253 E res_send: res_nsend: using send_dg
12-23 22:12:23.399   702 19253 E res_send: send_dg: new DG socket
12-23 22:12:23.399   702 19253 E res_send: get_timeout: using timeout of 5000 msec
12-23 22:12:23.399   702 19253 E res_send: retrying_poll: 49 retrying_poll
```

i tried anything:
- i followed the upgrade instructions [here](https://blog.expo.dev/expo-sdk-44-4c4b8306584a )
- and i updated expo-updates and i followed this instructions : 
1. https://docs.expo.dev/bare/updating-your-app/#configuring-the-channel-manually
2. https://docs.expo.dev/versions/latest/sdk/updates/#updatesmanifest
3. https://docs.expo.dev/bare/installing-updates/#installation
- i updated my react-native-gesture-handler like [here](https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot) and [here](https://docs.swmansion.com/react-native-gesture-handler/docs/2.0.0/)
- i added hot fixed from [here](https://github.com/expo/expo/issues/18002) because expo-updates ver still 0.11.7
- i updated react-native-reanimated like [here](https://docs.swmansion.com/react-native-reanimated/docs/2.3.x/fundamentals/installation). i tried expo.jsEngine=hermes or expo.jsEngine=jsc but nothing changed

thanks a lot for your assistance

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 20220123.190932.0 - /usr/local/bin/watchman
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.4 => 0.64.4 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

i cannot give any reproducible

**Comment by mariomurrent-softwaresolutions** [comment]
So, if you remove the expo-updates from your project, does it run then?
Btw. expo-updates has already v.0.17.5

**Comment by hotaryuzaki** [comment]
> So, if you remove the expo-updates from your project, does it run then? Btw. expo-updates has already v.0.17.5

I don't try it yet, because to do that I must take out all expo-updates import.

I upgraded with "expo upgrade" and it set expo-updates to 0.11 ver, I believe it's the compatible version for SDK 44

**Comment by mariomurrent-softwaresolutions** [comment]
What was your previous SDK version?

**Comment by hotaryuzaki** [comment]
> What was your previous SDK version?

43

**Comment by brentvatne** [comment]
https://github.com/expo/fyi/blob/main/splash-screen-hanging.md

**Comment by hotaryuzaki** [comment]
> https://github.com/expo/fyi/blob/main/splash-screen-hanging.md

I ignored it and upgrade to 45 - 47 sequentially.
But I think it was because GestureHandlerRootView that we must set Flex: 1.
