### ISSUE TITLE
Detached Expo app - Crash on Android - FATAL EXCEPTION: main ... java.lang.ClassCastException: com.mybundle.MainApplication cannot be cast to com.facebook.react.ReactApplication

### ISSUE THREAD

**Issue by voyage11** [expo/expo#206]
I am using the https://github.com/zo0r/react-native-push-notification with Detached expo app. The push notification works perfectly in iOS and it crashed in Android. 

I have opened an issue on the library: https://github.com/zo0r/react-native-push-notification/issues/432 but I was told my implementation was wrong. 

I am still trying to figure out how to fix this issue. Any help would be appreciated. 

I am not an Android developer and I am a newbie in developing React native app. Thanks.

**Comment by terribleben** [comment]
Seems like this was resolved in the [other repo](https://github.com/zo0r/react-native-push-notification/issues/432#issuecomment-303973572).

**Comment by martinezguillaume** [comment]
I don't really understand the solution, can you be more explicit please ? 🙂

**Comment by KthProg** [comment]
I'm having this problem. What's the resolution please?
