### ISSUE TITLE
babel plugin visitor pattern usage bug

### ISSUE THREAD

**Issue by Tozare** [expo/expo#20603]
### Summary

We are using **babel plugin visitor pattern** to append addition functionality to the app. In downloaded snack it works fine, but when we try the same in expo snack web preview it seems that **babel plugin visitor pattern** is not running.
It give error "product is not defined". It is variables that is created by **babel plugin visitor pattern**.

### What platform(s) does this occur on?

Web

### Environment

can not reproduce in expo snack web preview

### Minimal reproducible example

https://snack.expo.dev/@tozare/babel-visitor-pattern-bug

**Comment by Kudo** [comment]
hi there! i tried to download the snack but it doesn't work for me either. could you explain more details of the babel plugin? i didn't see any code to define the `product` in the plugin code.
