### ISSUE TITLE
Expo av video player not showing Play button on iOS

### ISSUE THREAD

**Issue by shop-fluencer** [expo/expo#20602]
### Summary

Hello,

I use the expo-av libary and on iOS its not showing the play button.

I found this issue but not solved:

https://github.com/expo/expo/issues/10307

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.8 
    Expo Workflow: managed

### Minimal reproducible example

```
            <Video
              ref={videoRef}
              style={s.video}
              source={{
                uri: video
              }}
              shouldPlay={shouldPlay}
              useNativeControls
              // @ts-ignore
              resizeMode="contain"
            />
```

**Comment by Kudo** [comment]
hi there! i tested this [example](https://docs.expo.dev/versions/latest/sdk/video/#usage) on ios expo go which is quite similar to your example and it works for me. could you help to create a minimal reproducible example project and upload to some git repository? we could help to investigate further. thanks!
