### ISSUE TITLE
u.Constants ends up with a null reference deep in obfuscated code

### ISSUE THREAD

**Issue by Narvey** [expo/expo#20617]
### Summary

I get this (useless) error:
null is not an object (evaluating 'u.Constants')
And the stack trace isn't copyable (thanks to your [LogBox](https://reactnative.dev/blog/2020/07/06/version-0.63) you [think](https://docs.expo.dev/get-started/errors/) is so glorious):
![image](https://user-images.githubusercontent.com/2171161/209601950-7e6970de-ed60-4e36-9e75-41766bc6e243.png)

### What platform(s) does this occur on?

Android

### Environment

expo snack

### Minimal reproducible example

If your error would give me a clue as to what part of this giant project is the issue, I would pare this down to a minimal example. But since you obfuscated your code and thus the error message and stack are each as useless as can be, here's the entire project:
https://snack.expo.dev/hV92Y-c1z

**Comment by brentvatne** [comment]
error traces on snack can be hit and miss, it only approximates a real development environment. i'd recommend using a local development environment instead. https://docs.expo.dev/get-started/installation/
