### ISSUE TITLE
Unable to resolve module ./ExponentImagePicker

### ISSUE THREAD

**Issue by hamzus-000** [expo/expo#20615]
### Summary

Hi there fellow devs,
I'm trying to get my hands comfortable with expo and i'm trying to access image picker which would give the user the possibility to choose between gallery or camera. i installed the latest version of expo-image-picker which as of today 14.0.2, but i get this error when building:

```
Unable to resolve module ./ExponentImagePicker from C:\Users\User\Desktop\Dev\react-expo\my-app\node_modules\expo-image-picker\build\ImagePicker.js:

None of these files exist:
  * node_modules\expo-image-picker\build\ExponentImagePicker(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)        
  * node_modules\expo-image-picker\build\ExponentImagePicker\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json) 
```

thank you and happy holidays

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Minimal reproducible example

There is nothing really  i just installed this module and used it from the tutorial in the docs.

```
import  ImagePicker from 'expo-image-picker';
import  * as ImagePicker from 'expo-image-picker';//tried this too
  const [image, setImage] = useState("");

  const pickImage = async () => {
    // No permissions request is necessary for launching the image library
    let result = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      aspect: [4, 3],
      quality: 1,
    });
    console.log(result);
  };
```

**Comment by Kudo** [comment]
hi there! the problem may come from other reasons, e.g. broken node_modules. could you help to create a [minimal reproducible example project](https://stackoverflow.com/help/minimal-reproducible-example) and upload to some git repository? that would help us investigate the problem further. thanks!
