### ISSUE TITLE
expo-auth-session Crashes app in prod/dev builds but works In Expo Go

### ISSUE THREAD

**Issue by mahmoud16h** [expo/expo#20612]
### Summary

I have an issue with the `expo-auth-session`
It works perfectly fine on Expo Go, however if i build an APK or build on testflight, the app completely crashes as soon as this below component is rendered.

I have gone through the docs over and over again, please do let me know if I've missed something, however I don't think i have, but there's always the chance.

It's just odd it works perfectly fine in expo go, but not in any build.

I don't get a chance to call the `promptAsync` function; as soon as `Google.useIdTokenAuthRequest` is called, the app will crash.

The only error i get on the console is the following:

```
node_modules/expo/AppEntry.bundle?platform=ios&dev=false&hot=false&strict=false&minify=true:42 TypeError: t.indexOf is not a function

This error is located at:
    in j
    in RCTView
    in Unknown
    in O
```

https://user-images.githubusercontent.com/29020310/209556613-65949834-9f19-49f7-b5f5-6ab05ea051e2.mov

please see code in reproducable demo

### What platform(s) does this occur on?

Android, iOS

### Environment

System:
      OS: macOS 12.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

```
const EXPO_REDIRECT_PARAMS = { useProxy: true, projectNameForProxy: USERNAME/SLUG };
 const NATIVE_REDIRECT_PARAMS = { native: 'com.foo.bar://' };
 const REDIRECT_PARAMS = Constants.appOwnership === 'expo' ? EXPO_REDIRECT_PARAMS : NATIVE_REDIRECT_PARAMS;
 const redirectUri = AuthSession.makeRedirectUri(REDIRECT_PARAMS);

  function GoogleSignin({ onSuccessCallback }) {
  const dispatch = useDispatch();
  const [request, response, promptAsync] = Google.useIdTokenAuthRequest({
    expoClientId: EXPO_ID,
    iosClientId: IOS_ID,
    redirectUri,
  });

  const fetchGoogleUser = async (idToken) => {
    try {
      const res = await dispatch(googleThunk({ idToken })).unwrap();
      onSuccessCallback(res.data);
    } catch (e) {
      console.error('error fetching google user', e);
    }
  };

  useEffect(() => {
    if (response?.type === 'success') {
      const { params } = response;
      fetchGoogleUser(params.id_token);
    }
  }, [response, request]);

  return (
    <TouchableOpacity onPress={() => promptAsync()}>
      <Image source={GooglePic} style={{ height: 50, width: 50 }} />
    </TouchableOpacity>
  );
}

export default GoogleSignin;
```

**Comment by DucAnhPhi** [comment]
I have the same issue unfortunately :/

**Comment by mahmoud16h** [comment]
Any chance we can get some eyes/help on this issue?

**Comment by DucAnhPhi** [comment]
For my particular case `useAuthRequest()` is crashing my app in production. Just calling the hook crashes the app. When I comment it out - the app works and does not crash.
Here are my dependencies:
`"expo-auth-session": "~3.7.4",`
`"expo-random": "~12.3.0"`,
`"expo": "~46.0.13",`

For now I am going to stop using `expo-auth-session` and look how I can implement my auth flow with `expo-web-browser`

**Comment by elitenas** [comment]
Having the same issue. Anyone have any luck fixing this?

**Comment by mahmoud16h** [comment]
nope still no luck, got the exact same behaviour as @DucAnhPhi 

anyone from expo going to check thisout?

**Comment by elitenas** [comment]
The issue here was that that the google client id was undefined so the hook makes the application crash. They should probably add a safe check for it.

**Comment by mahmoud16h** [comment]
@elitenas unfortunately that wasn't my issue. Client ID is definitely there, but app still crashes.

**Comment by next6leo** [comment]
is this problem solved?

**Comment by ensarince** [comment]
> expo-web-browser

same here

**Comment by mroswald** [comment]
Can you confirm that it crashes in `base64-js.toByteArray` ([here](https://github.com/beatgammit/base64-js/blob/master/index.js#L31))? It's used by `expo-auth-session > expo-crypto > base64-js`.
The complete error for me is `t.indexOf is not a function. (In 't.indexOf('=')', 't.indexOf' is undefined)`

I checked all upstream callers of this function and could not see any issue with different data or input, as none of the functions (on the surface of expo-auth-session) accepts related parameters nor we use it.

We only run this on iOS, but it seems that the error only appears on iPads in certain versions. I also found that `getRandomBytes` in `expo-crypto` only calls `base64-js.toByteArray` if `ExpoCrypto` (native module) does not provide `getRandomBytes` but `getRandomBase64String`.

A small workaround could be to check the return value of `getRandomBase64String` to not be undefined before calling `toByteArray` [here](https://github.com/expo/expo/blob/main/packages/expo-crypto/src/Crypto.ts#L46). At least it would prevent crashes.

**Comment by NomanKader** [comment]
**I got the solution by adding "scheme":"your_package_id" inside app.json .**
