### ISSUE TITLE
[Android] exp publish is not working on Android

### ISSUE THREAD

**Issue by lilosir** [expo/expo#2062]
### Environment
expo sdk 28
detached app

### Steps to Reproduce

(Write your steps here:)

1. Run `exp publish`
2. Got a URL
3. Closed the app completely, and reopen the app

### Expected Behavior

Both Android and IOS app should be updated

### Actual Behavior
Only IOS is working, Android did not updated

here is what I run `exp publish:history`
<img width="344" alt="screen shot 2018-08-01 at 12 43 24 am" src="https://user-images.githubusercontent.com/8388269/43501835-870b82e6-9525-11e8-87a3-e75eff833f4e.png">

**Comment by esamelson** [comment]
Hi @lilosir - sorry this isn't working for you! Could you post your app.json?

**Comment by lilosir** [comment]
@esamelson  here is my app.json

> {
  "expo": {
    "sdkVersion": "28.0.0",
    "name": "xxx",
    "orientation": "portrait",
    "icon": "./src/assets/images/app_icon512.png",
    "version": "2.0.8",
    "slug": "xxx-staging-208-109",
    "ios": {
      "bundleIdentifier": "com.xxx-staging.app",
      "buildNumber": "109",
      "publishBundlePath": "ios/xxx/Supporting/shell-app.bundle",
      "publishManifestPath": "ios/xxx/Supporting/shell-app-manifest.json"
    },
    "android": {
      "package": "com.xxx.dev",
      "versionCode": 109,
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
    },
    "extra": {
      "baseUrl": "https://xxx-api-staging.herokuapp.com",
      "published": 4
    },
    "splash": {
      "image": "./src/assets/images/launch_background_image.png",
      "resizeMode": "cover",
      "backgroundColor": "#2696BA"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "xxx-corp",
            "project": "xxx-react-native",
            "authToken": "atoken"
          }
        }
      ]
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "isDetached": true,
    "detach": {
      "scheme": "exp85a6ed291e5a451990f5750e587db029",
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.6.5-sdk28.0.0-7eac2a72-06b2-48c9-8281-c0c6c308f0b0.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.6.2-sdk28.0.0-141d0954-b898-4919-aa89-3ab45453213f.tar.gz"
    }
  }
}

**Comment by esamelson** [comment]
@lilosir - have you tried closing and opening the Android app again? Since you have `fallbackToCacheTimeout: 0` you may need to restart the app twice (once to download the update in the background, then another time to actually launch it).

**Comment by esamelson** [comment]
@lilosir you could verify that you can reach https://expo.io/ and https://d1wp6m56sqw74a.cloudfront.net/ by trying to visit them in the browser on your Android device. You need to be able to connect to both of those in order to download updates.

**Comment by lilosir** [comment]
@esamelson  It seems I got access denied from the second link

**Comment by esamelson** [comment]
ok that's expected, as long as you can connect then that's not the problem. Did you publish to a release channel?

**Comment by lilosir** [comment]
@esamelson  I only run `exp publish`, and in AppConstants file, it is showing `public static final String RELEASE_CHANNEL = "default";`

**Comment by tsapeta** [comment]
SDK28 that you used when creating this issue is no longer supported, so I'm gonna close this issue. Please create a new issue if this still happens in any of the currently supported SDK versions.
