### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by patrinoua** [expo/expo#20622]
### Summary

Howdy! I am installing expo-image-manipulator and getting some errors and warnings. 
It seems like some of the dependencies are not up to date. Is this something on your radar, should I use a different solution, or do you have another suggestion? I am attaching some screenshots for your reference.
Many thanks in advance!

The expected behaviour would be that the package works out of the box

<img width="592" alt="Screenshot 2022-12-27 at 18 56 51" src="https://user-images.githubusercontent.com/36475005/209705011-2b04d404-bfda-4b9c-bfa2-3263c894a993.png">
<img width="586" alt="Screenshot 2022-12-27 at 18 57 01" src="https://user-images.githubusercontent.com/36475005/209705017-3eb45c34-6842-4acb-9431-6c8bded8faf6.png">
<img width="603" alt="Screenshot 2022-12-27 at 18 56 37" src="https://user-images.githubusercontent.com/36475005/209705019-589f99b5-0539-4bd7-bc98-4e3d6248821f.png">
<img width="1279" alt="Screenshot 2022-12-27 at 18 56 12" src="https://user-images.githubusercontent.com/36475005/209705025-4c93480e-c081-4785-ab95-964cfb0fe2dd.png">

### What platform(s) does this occur on?

Not Applicable

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.asdf/installs/nodejs/14.17.5/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.14 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2022.11.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/angelapatrinou/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-45.0.0.tar.gz => 0.68.1 
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: managed

### Minimal reproducible example

 npm i expo-image-manipulator

**Comment by Kudo** [comment]
hi there! you should use `npx expo install expo-image-manipulator` or `expo-cli install expo-image-manipulator` to install compatible expo-image-manipulator version that supports your current expo sdk.

however, the root cause of these warnings should come from other third party libraries. you could use `npm ls` to check why this package is installed. e.g. `npm ls @react-native-community/masked-view`. sometimes it doesn't really matter. for example, the styled-components warning for react-dom might not matter if you don't support web.
