### ISSUE TITLE
EAS build ios has an empty app icon

### ISSUE THREAD

**Issue by dragonboltmaster** [expo/expo#20635]
### Summary

I have set my icon and splash screen in the app.json with valid paths to images for the app icon and splash screen for my project. But when I run `eas build` then it doesn't upload any icons to the app. I just end up having an empty app icon.

### SDK Version

47.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2022.12.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.0 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

This is my app.json:

```
{
  "bundleIdentifier": "com.gymbro.gymbro",
  "expo": {
    "name": "Gym Bro",
    "slug": "Gym-Bro",
    "privacy": "public",
    "version": "1.0.1",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "sdkVersion": "47.0.0",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#000000"
    },
    "runtimeVersion": {
      "policy": "nativeVersion"
    },
    "updates": {
      "fallbackToCacheTimeout": 0,
      "url": "https://u.expo.dev/b15f5ea7-9a14-41ce-8932-db634f9bbeed"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "com.gymbro.gymbro",
      "buildNumber": "12",
      "icon:": "./assets/icon.png"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#000000"
      },
      "permissions": [
        "android.permission.RECORD_AUDIO"
      ],
      "package": "com.dragonboltmaster.GymBro"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-image-picker",
        {
          "photosPermission": "Allow camera acess so that you can take pictures and videos in the app to share them with friends."
        }
      ]
    ],
    "extra": {
      "eas": {
        "projectId": "b15f5ea7-9a14-41ce-8932-db634f9bbeed"
      }
    }
  }
}

```

But for some reason when I run `eas build` the ios build doesn't have an app icon

**Comment by Kudo** [comment]
hi there! since your project is now a bare project (you may either create from a bare template or once do `npx expo run` before). the `eas build` will not update the icon to ios native project. there are two solutions:

1. revert to project back as a managed project: remove `ios` folder entirely. if you have git, try to revert the project changes. (`npx expo run` or `npx expo prebuild` will add android/ios folders, `index.js`/`metro.config.js` files and update package.json.
2. run `npx expo prebuild --clean`. this will delete and re-generate the android/ios folders. your project will still be a bare project.

**Comment by dragonboltmaster** [comment]
So I tried that and it still didn't work. So then I deleted the project on expo.dev and also created a new project locally with `npx create-expo-app (name of my app)` then I copy pasted all my files into it. I re-installed the node modules that I needed.  Another thing is that the expo go app on my ios emulator has the app icon and splash screen but when I run `eas build` the ipa file doesn't have an icon or splash screen. I also checked my Images.xcassets folder in the ios directory and it has all of the icons and the splash screen. What is wrong?

**Comment by dav1app** [comment]
I am using the latest versions of EAS/expo and the icon is missing under the EAS app. icon.png is present on the folder. 

```
  "expo": "~48.0.15",
  ```
  ```js
  {
  "expo": {
    // ...
    "icon": "./assets/icon.png",
    //...
  }
  ```
  I am building the project on EAS using 
  
  ```
  eas build -p android
  ```

**Comment by whchua** [comment]
Having the same issue, I am using SDK48. Does anyone manage to find a new solution?

**Comment by daviddigital** [comment]
Had the same issue, `npx expo prebuild --clean` resolved as per comment from Kudo

**Comment by willashley23** [comment]
Having the same issue on SDK 51. `npx expo prebuild --clean` does not work. It says `» ios: icon: No icon is defined in the Expo config`

**Comment by liveakshay** [comment]
How is this issue closed?  This still doesn't work.  Prebuild doesn't work either.

**Comment by edencalves** [comment]
I have the same problem, after updating to SDK51 my app icon was empty

**Comment by SMKH-PRO** [comment]
any solution? I have icon in both expo and ios object, still the same

**Comment by carTloyal123** [comment]
Also seeing this issue. Icon is formatted correctly (as far as I can tell) and named correctly in configs. Any update would be great!

**Comment by ncalhoun2** [comment]
So I posted this issue because when I built the app and then added it to the Transporter app to deliver it to App store connect the app did not have an app icon in the transporter app. I then delivered it anyway (even though it did not have a logo), and when it was uploaded to test flight it did have an icon. So if you are assuming it does not have an icon because it does not have one in the Transporter app just deliver it anyway because it will have one after it is delivered to App Store Connect

**Comment by Jinguan** [comment]
Does anyone have solution for this?  It appears as an issue still.  tried many ways but none worked.  Desperately want to use EAS to submit build to App Store Connect.

**Comment by ncalhoun2** [comment]
> Does anyone have solution for this?  It appears as an issue still.  tried many ways but none worked.  Desperately want to use EAS to submit build to App Store Connect.

So you want to completely use eas to submit the app to the App Store and not use the transporter app? Is that what you're asking? Because it may look like you don't have an app icon until you download the app from test flight.

**Comment by Jinguan** [comment]
> > Does anyone have solution for this?  It appears as an issue still.  tried many ways but none worked.  Desperately want to use EAS to submit build to App Store Connect.
> 
> So you want to completely use eas to submit the app to the App Store and not use the transporter app? Is that what you're asking? Because it may look like you don't have an app icon until you download the app from test flight.

Yes, I would like to use eas completely to submit the app to App Store connect.  And I am on Windows so can not use transporter.

**Comment by Jinguan** [comment]
I would like to share my update.  I have successfully submit my app from eas to App Store Connect.  
What I did, is to remove the current app in App Store Connect, and also remove the Distrubition from the pre-existing failed submitting.  In my local directory, I removed ios folder so that the ios folder can be regenerated then everything will be fresh.  Since this, the resubmit the build from eas to App Store Connect got successful.

**Comment by DanielAmah** [comment]
Still failing for me

**Comment by Jinguan** [comment]
> Still failing for me

You may try these:  
- Add the correct icon file to the right location, following the exact required size and transparency, and update related files. 
- Delete the App in App Store Connect and create a new App to use it,  actually you won't be able to delete it but can rename it and create a new one using the name you want. 
- Delete all the existing being used BundleID, certificate, profile and related information from your tools, or rename them if you can not delete,
- Remove the ios folder in your project. 
- Build the app from your project, then generate new anything needed upon prompt.  Like you are building a new app. 
- Hope you will get success!
