### ISSUE TITLE
TypeError: undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by Godknowsegi** [expo/expo#20637]
### Summary

after installing  (react-native-skeleton-content) i get the following error .

Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ~47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

const App = () => {
  const [load, setLoad] = useState(true);
  const isLoggedIn = useSelector((state) => state.quantom.isLoggedIn);

  const [fontsLoaded] = useFonts({
    "Roboto-Black": require("./assets/fonts2/Roboto-Black.ttf"),
    "Roboto-Regular": require("./assets/fonts2/Roboto-Regular.ttf"),
    "Roboto-Bold": require("./assets/fonts2/Roboto-Bold.ttf"),
    "Roboto-BlackItalic": require("./assets/fonts2/Roboto-BlackItalic.ttf"),
  });
  useEffect(() => {
    setTimeout(() => {
      setLoad(false);
    }, 5000);
  }, []);
  const Tab = createBottomTabNavigator();

  const tabOffsetValue = useRef(new Animated.Value(0)).current;
  function getWidth() {
    let width = Dimensions.get("window").width;

    // Horizontal Padding = 20...
    width = width - 80;

    // Total five Tabs...
    return width / 10;
  }
  if (!fontsLoaded) {
    return;
  }
  return (
    <>
    <SafeAreaProvider>{load && <SplashScreen />}

      {!load && (
        <NavigationContainer independent={true}>
          {isLoggedIn ? (
            <>
              <Tab.Navigator
                screenOptions={{
                  tabBarHideOnKeyboard: true,
                  // tabBarShowLabel:false,
                  headerShown: false,
                  tabBarStyle: {
                    borderTopLeftRadius: 20,
                    borderTopRightRadius: 20,
                    elevation: 10,
                    position: "absolute",
                    paddingBottom: 10,
                    height: 60,
                    paddingTop: 10,
                    backgroundColor: "#fff",
                    // display: tabBar ? "none" : "flex",

                    ...styles.shadow,
                  },
                }}
              >
                <Tab.Screen
                  name="Home"
                  options={{
                    tabBarIcon: ({ size, focused }) => (
                      <TouchableOpacity>
                        <MaterialCommunityIcons
                          name="home"
                          size={size}
                          color={focused ? COLORS.appPurple : "#000"}
                        />
                      </TouchableOpacity>
                    ),
                    tabBarActiveTintColor: COLORS.appPurple,
                    tabBarInactiveTintColor: "#000",
                  }}
                  listeners={({ navigation, route }) => ({
                    tabPress: (e) => {
                      Animated.spring(tabOffsetValue, {
                        toValue: 0,
                        useNativeDriver: true,
                      }).start();
                    },
                  })}
                  tabBarIcon
                  component={LoggedIn}
                />
                <Tab.Screen
                  name="Wallet"
                  options={{
                    tabBarIcon: ({ size, focused }) => (
                      <TouchableOpacity>
                        <Entypo
                          name={focused ? "wallet" : "wallet"}
                          size={size}
                          color={focused ? COLORS.appPurple : "#000"}
                        />
                      </TouchableOpacity>
                    ),
                    tabBarActiveTintColor: COLORS.appPurple,
                    tabBarInactiveTintColor: "#000",
                  }}
                  listeners={({ navigation, route }) => ({
                    tabPress: (e) => {
                      Animated.spring(tabOffsetValue, {
                        toValue: getWidth() * 2.5,
                        useNativeDriver: true,
                      }).start();
                    },
                  })}
                  tabBarIcon
                  component={Wallete}
                />
                <Tab.Screen
                  name="Market"
                  options={{
                    tabBarIcon: ({ size, focused }) => (
                      <TouchableOpacity
                        style={tw.style(
                          "p-3 rounded-full shadow-md  flex-row  items-center justify-center w-15 h-15 mb-10",
                          { backgroundColor: COLORS.appPurple }
                        )}
                      >
                        <Entypo
                          name="bar-graph"
                          size={size}
                          color={focused ? COLORS.white : "#000"}
                        />
                      </TouchableOpacity>
                    ),
                    tabBarActiveTintColor: COLORS.appPurple,
                    tabBarInactiveTintColor: "#000",
                  }}
                  listeners={({ navigation, route }) => ({
                    tabPress: (e) => {
                      Animated.spring(tabOffsetValue, {
                        toValue: getWidth() * 5,
                        useNativeDriver: true,
                      }).start();
                    },
                  })}
                  tabBarIcon
                  component={Market}
                />
                <Tab.Screen
                  name="Notification"
                  options={{
                    tabBarBadge: 3,
                    tabBarIcon: ({ size, focused }) => (
                      <TouchableOpacity>
                        <MaterialCommunityIcons
                          name="shape-square-rounded-plus"
                          size={size}
                          color={focused ? COLORS.appPurple : "#000"}
                        />
                      </TouchableOpacity>
                    ),
                    tabBarActiveTintColor: COLORS.appPurple,
                    tabBarInactiveTintColor: "#000",
                  }}
                  listeners={({ navigation, route }) => ({
                    tabPress: (e) => {
                      Animated.spring(tabOffsetValue, {
                        toValue: getWidth() * 7.5,
                        useNativeDriver: true,
                      }).start();
                    },
                  })}
                  tabBarIcon
                  component={Notification}
                />
                <Tab.Screen
                  name="Profile"
                  options={{
                    tabBarIcon: ({ size, focused }) => (
                      <TouchableOpacity>
                        <FontAwesome
                          name="user-circle-o"
                          size={size}
                          color={focused ? COLORS.appPurple : "#000"}
                        />
                      </TouchableOpacity>
                    ),
                    tabBarActiveTintColor: COLORS.appPurple,
                    tabBarInactiveTintColor: "#000",
                  }}
                  listeners={({ navigation, route }) => ({
                    tabPress: (e) => {
                      Animated.spring(tabOffsetValue, {
                        toValue: getWidth() * 10,
                        useNativeDriver: true,
                      }).start();
                    },
                  })}
                  tabBarIcon
                  component={Profiles}
                />
              </Tab.Navigator>
              <Animated.View
                style={{
                  width: getWidth() - 4,
                  height: 3,
                  backgroundColor: COLORS.appPurple,
                  position: "absolute",
                  bottom: 57,
                  // display: tabBar ? "none" : "flex",
                  // Horizontal Padding = 20...
                  left: 25,
                  borderRadius: 30,
                  transform: [{ translateX: tabOffsetValue }],
                }}
              ></Animated.View>
            </>
          ) : (
            <Auth />
          )}
        </NavigationContainer>
      )}</SafeAreaProvider>

      
    </>
  );
};

**Comment by aleqsio** [comment]
Hi @Godknowsegi!
This seems to be related to this issue in the package's repository:
https://github.com/alexZajac/react-native-skeleton-content/issues/80

It's likely a reanimated version mismatch due to the library declaring reanimated as a dependency, not as a peer dependency – maybe some of the `resolutions` field comments in the linked issue can fix the problem? 

It's not related to Expo, so I'm going to close this issue.
