### ISSUE TITLE
Support for Electron

### ISSUE THREAD

**Issue by ollydixon** [expo/expo#20647]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by ollydixon** [comment]
Trying to setup ```expo-electron-adapter``` but it seems to be severely outdated.

Is there any easy way to setup Expo with Electron?

**Comment by ollyde** [comment]
@siarheipashkevich I gave up with RN garbage. Using Sveltekit with Capacitor, much better.

**Comment by siarheipashkevich** [comment]
@ollyde do you use yours apps in production with Capacitor ?

**Comment by ollyde** [comment]
Not yet, we were using Flutter for most of our platforms which is excellent. I'm using SvelteKit just to see where we can go with it.
