### ISSUE TITLE
[expo-image-picker] error: cannot find symbol for TIRAMISU and READ_MEDIA_IMAGES

### ISSUE THREAD

**Issue by kishan2110** [expo/expo#20646]
### Summary

I am building project using android studio it give me error 
<img width="940" alt="Screenshot 2022-12-29 at 8 56 22 PM" src="https://user-images.githubusercontent.com/35519654/209974384-e572369c-518b-4cff-9865-26170c8e23d8.png">

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
      Watchman: 2022.10.03.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 22, 26, 28, 29, 30, 31
        Build Tools: 22.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9424903
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: 45.0.0 => 45.0.0 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

<img width="1082" alt="Screenshot 2022-12-29 at 8 59 12 PM" src="https://user-images.githubusercontent.com/35519654/209974741-ae577357-b606-4950-b987-7d5acb9afc3f.png">

**Comment by Kudo** [comment]
hi there! the issue comes from react-native-image-crop-picker, please report this issue in the repo: https://github.com/ivpusic/react-native-image-crop-picker/issues
