### ISSUE TITLE
Changed Ip address of detached App to listen to packager

### ISSUE THREAD

**Issue by themakerman** [expo/expo#2065]
Hi,

When i build the detached app i have seen the ip address gets fixed to ip which xde packager see's currently. The problem is i work at multiple locations and each time my mac is assigned different ip address and so the packager runs everytime on different ip. 

I cannot build the app everytime ip changes. Is there any work around? For eg in vanilla react native in the debugger options i can change the ipaddress and port directly....

Thanks.

**Comment by themakerman** [comment]
@OscarYuen it still listens to older ip.

**Comment by EvanBacon** [comment]
XDE is deprecated
