### ISSUE TITLE
Login error Cannot read properties of null (reading 'removeItem')

### ISSUE THREAD

**Issue by JakeWayneMurray** [expo/expo#20650]
### Summary

This is an issue I am running into while trying to use the android subsystem with windows 11. I got expo go installed and when I go to sign in I am getting this issue. I attached a screenshot  below.
<img width="230" alt="image" src="https://user-images.githubusercontent.com/109402063/210029436-7f617ed6-58ac-4b21-9a66-1292bc295ab5.png">

### Environment

this is simply with the newest version of the app.

### Minimal reproducible example

install expo on a windows 11 android subsystem and try to login

**Comment by Kudo** [comment]
hi there!

could you share these information for further troubleshooting?

- which expo go versioned did you use? e.g. ios or android expo go?
- what OS version did you try? e.g. ios 16 or android 13
- what device did you try? e.g. iphone 14 or samsung s22 or android emulator
- when showing the login form, which browser did you open? e.g. ios SFSafariViewController or android chrome browser?

**Comment by byCedric** [comment]
Hi @JakeWayneMurray! Thanks for reporting the issue. We just deployed a fix that should fix this. You can now log in, and select the account you'd like :) Let us know if you are having other issues.

**Comment by JakeWayneMurray** [comment]
This seems to be solved!

The only thing is after that when I go to open an app that is currently running on my account within expo I am now getting this error.


![image](https://user-images.githubusercontent.com/109402063/211221115-c448e08a-6a91-4931-988c-8e7f06802edf.png)
