### ISSUE TITLE
node 18 failed for web

### ISSUE THREAD

**Issue by xiongemi** [expo/expo#20652]
### Summary

if use node 18 to open web, it throws an error:
```
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/emilyxiong/Code/nx-expo-monorepo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/emilyxiong/Code/nx-expo-monorepo/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/emilyxiong/Code/nx-expo-monorepo/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/emilyxiong/Code/nx-expo-monorepo/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/emilyxiong/Code/nx-expo-monorepo/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/emilyxiong/Code/nx-expo-monorepo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/emilyxiong/Code/nx-expo-monorepo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/emilyxiong/Code/nx-expo-monorepo/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/emilyxiong/Code/nx-expo-monorepo/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/emilyxiong/Code/nx-expo-monorepo/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/emilyxiong/Code/nx-expo-monorepo/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.11.0
```

### What platform(s) does this occur on?

Web

### SDK Version

47.0.8

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.5.1 => 0.5.1 
      @expo/webpack-config: ^0.17.3 => 0.17.3 
      babel-preset-expo: ~9.2.2 => 9.2.2 
      expo: 47.0.8 => 47.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    Expo Workflow: managed

### Minimal reproducible example

- create an expo app
- use node 18
- open web

**Comment by Simek** [comment]
Hello @xiongemi,

this problem occurs due to internal changes in Node, which affects the currently Webpack version used for web builds. For now the workaround is to set the Open SSL legacy provider flag for the command you are running:
```
export NODE_OPTIONS=--openssl-legacy-provider
```

Alternatively, you can try to pin `webpack` to the latest version directly in your project `package.json` (but this might require additional config changes) or use tools like NVM or Volta to switch the Node version based on project config (this should work out-of-the-box for Node up to 16).

**Comment by LiamKarlMitchell** [comment]
For Windows Powershell you can do like this.


```
$env:NODE_OPTIONS="--openssl-legacy-provider"
```

Or perhaps adapt the package.json scripts with cross-env so it works on mac/linux/win?
```
yarn add cross-env -D
```

package.json scripts
```json
  "scripts": {
    "start": "cross-env NODE_OPTIONS=--openssl-legacy-provider expo start",
    "android": "cross-env NODE_OPTIONS=--openssl-legacy-provider expo start --android",
    "ios": "cross-env NODE_OPTIONS=--openssl-legacy-provider expo start --ios",
    "web": "cross-env NODE_OPTIONS=--openssl-legacy-provider expo start --web"
  },
```

Or could webpack that expo uses be updated or configured to use a different hash function

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by EvanBacon** [comment]
@bnussman we will be deprecating Webpack support sometime this year in favor of universal Metro -- it's already shaping up to be a lot better. I'll give another shot upgrading to Webpack 5 today/tomorrow but there are a number of issues that have seemingly not been addressed upstream.

Closing in favor of https://github.com/expo/expo-cli/issues/4575

**Comment by bnussman** [comment]
@EvanBacon Switched to Metro for web and it's working **great**! No worries about putting effort into Webpack 5 if metro is the future for expo. Appreciate you!
