### ISSUE TITLE
expo-dev-client should display more information on syntax errors

### ISSUE THREAD

**Issue by ariccio** [expo/expo#20665]
### Summary

Expo-dev-client appears to not display full context for Javascript syntax errors encountered in development builds. Ideally, I'd see something like: 
```
ERROR  [SyntaxError: Unexpected identifier 'resolveAfter2Seconds'. Expected ')' to end an argument list.]
/Users/alexanderriccio/Documents/scratch_work/weird_expo_compile_issue_bare/my-app/index.js:15:13
console.log(await resolveAfter2Seconds);
     ~~~~~~~^
```
...instead, all we get is:
```
 ERROR  [SyntaxError: Unexpected identifier 'resolveAfter2Seconds'. Expected ')' to end an argument list.]
```

This is often not a big deal. Sometimes, when it interacts with other bugs, it can be really insidious and annoying. If expo simply looked up the line in the bundle, it might make a big difference.

In my case, an errant top level await (`console.log(await notifee.getTriggerNotifications());`) that would normally show up in the expo error overlay (ErrorFragment?) *somehow* made it through metro compilation, and then caused hermes to fail. The development build would immediately native crash anyways, so I wouldn't know. My *only* clue was this line in the device system log (`adb logcat`):
```
HermesVM: Compiling JS failed: 1200:21:')' expected at end of function call,  Buffer size 7031284 starts with: 766172205f5f42554e444c455f535441 and has protection mode(s): r--p
```

Sometimes - very rarely, like when typing this report - it would instead display that message in a "Project didn't load" screen. It seems like that happens if I have the project already running correctly, then add in the buggy line of code, then the hot refresh kicks in.

I am not entirely sure how expo normally handles errors, so I'm not *actually* sure why this caused a native crash. Currently, my wild guess is that somewhere [like in the module interop code](https://github.com/expo/expo/blob/023bc8eafe7ef5665dc3716a4163127f0e945c5c/android/vendored/sdk47/react-native-reanimated/Common/cpp/Registries/WorkletsCache.cpp#L30), [low level view code](https://github.com/expo/expo/blob/023bc8eafe7ef5665dc3716a4163127f0e945c5c/android/versioned-abis/expoview-abi47_0_0/src/main/java/abi47_0_0/host/exp/exponent/modules/api/components/webview/RNCWebViewManager.java#L1666) (also, [higher up the callstack](https://github.com/expo/expo/blob/023bc8eafe7ef5665dc3716a4163127f0e945c5c/android/versioned-abis/expoview-abi47_0_0/src/main/java/abi47_0_0/host/exp/exponent/modules/api/components/webview/RNCWebViewManager.java#L927)), or somewhere else entirely, is calling into `evaluateJavascript` and not catching the C++ exception. If that's the true case, then there might actually be a separate bug in expo somewhere that I should file.

[I initially thought this was a hermes bug where for some reason no useful info was dumped](https://github.com/facebook/hermes/issues/877). I was wrong, and honestly it should have been a little bit more obvious to me in retrospect, but I was confused by the fact that I'd seen no errors from metro or expo. In this case, the hermesvm output to the android system log was the *only* clue as to why the app was breaking. Without it, I may have been fighting for hours over a tiny mistake.

Immediatley below the hermesvm output in the log, the following stacktrace appears:
```
12-31 17:52:11.450 24110 24198 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: HMRClient.setup()
12-31 17:52:11.456 24110 24198 E AndroidRuntime: FATAL EXCEPTION: mqt_js
12-31 17:52:11.456 24110 24198 E AndroidRuntime: Process: riccio.co2.client, PID: 24110
12-31 17:52:11.456 24110 24198 E AndroidRuntime: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
12-31 17:52:11.458 24110 24198 E DevLauncher: DevLauncher tries to handle uncaught exception.
12-31 17:52:11.458 24110 24198 E DevLauncher: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at com.facebook.jni.NativeRunnable.run(Native Method)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at android.os.Handler.handleCallback(Handler.java:883)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at android.os.Looper.loop(Looper.java:214)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at java.lang.Thread.run(Thread.java:919)
```

When explicitly running a release variant (`npx expo run:android --device --variant release`), I get the correct/reasonable output:
```
/Users/alexanderriccio/Documents/GitHub/COVID-CO2-tracker/co2_native_client/android/app/build/generated/assets/react/release/index.android.bundle:712:21: error: ')' expected at end of function call
  console.log(await _reactNative.default.getTriggerNotifications());
             ~~~~~~~^
```

Seeing the generated bundle, I now believe the more insidious underlying problem for me was that for some inexplicable reason, metro decided to skip over transpiling that `await` call to generators. It's the only non-transpiled await call in the entire bundle. I suspect that it has something to do with the fact that I'm calling an imported async function in an invalid context. With the current behavior of expo, all I had to work with was `1200:21:')' expected at end of function call` in the android system log, which is extremely surprising and not informative.

I don't yet know what causes that insidious underlying problem. I don't think I have time to dig into it. I'm supposed to be doing some Balvi fund accounting tonight! In the meantime, I guess I'll just put it in the back of my mind as [psychic debugging skills](https://www.google.com/search?q=psychic+debugging+skills+site%3Adevblogs.microsoft.com).

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~2.0.1",
"expo-updates": "~0.15.6",

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.8.0/bin/yarn
      npm: 9.2.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/alexanderriccio/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.8 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: bare

```

### Reproducible demo

1. Create an empty managed OR bare expo project. It doesn't seem to matter.
2. Launch an android dev build with `npx expo start`.
3. Add the following code to the global scope in`index.js` if bare, or `App.tsx` if managed:

```
function r() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve('resolved');
    }, 2000);
  });
}

console.log(await r);

```

4. Refresh the app.
I get a screen that says `Unexpected identifier 'r'. Expected ')' to end an argument list.`, followed by the exact same right below it, and then two lines that say "no stack". If the name of the function is not unique and easily recognizable, this is super confusing.

### Stacktrace (if a crash is involved)

12-31 17:52:11.450 24110 24198 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: HMRClient.setup()
12-31 17:52:11.456 24110 24198 E AndroidRuntime: FATAL EXCEPTION: mqt_js
12-31 17:52:11.456 24110 24198 E AndroidRuntime: Process: riccio.co2.client, PID: 24110
12-31 17:52:11.456 24110 24198 E AndroidRuntime: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
12-31 17:52:11.456 24110 24198 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
12-31 17:52:11.458 24110 24198 E DevLauncher: DevLauncher tries to handle uncaught exception.
12-31 17:52:11.458 24110 24198 E DevLauncher: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at com.facebook.jni.NativeRunnable.run(Native Method)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at android.os.Handler.handleCallback(Handler.java:883)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at android.os.Looper.loop(Looper.java:214)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
12-31 17:52:11.458 24110 24198 E DevLauncher: 	at java.lang.Thread.run(Thread.java:919)

**Comment by brentvatne** [comment]
I've tried running the code you provided in the reproducible demo, and see the following exception in a React Native project without expo-dev-client:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/90494/211122061-223b91d4-9872-4e49-9b47-eebd8c6fb9b7.png">

Nothing is logged to Metro in that case.

We use the same error handling / logging mechanisms as upstream React Native, with some exceptions that don't appear to be relevant to this case. If you can provide a minimal reproducible example that we can clone that demonstrates the error from the beginning of your post, and verify that the behavior is different in a bare app without expo-dev-client, we can investigate. Otherwise I think this issue report is better suited for https://github.com/facebook/react-native/issues
