### ISSUE TITLE
Can not build ios after running `npx install-expo-modules@latest`

### ISSUE THREAD

**Issue by rudyhuynh** [expo/expo#20666]
### Summary

Steps:
- `npx react-native init AwesomeTSProject --template react-native-template-typescript`
- `npx install-expo-modules@latest`
- `yarn ios` --> Build failed:

<img width="1001" alt="Screen Shot 2023-01-01 at 15 48 37" src="https://user-images.githubusercontent.com/17097854/210165647-4aec197b-f351-4688-9678-4bed44ee8eb8.png">

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.6 => 0.70.6 
    Expo Workflow: bare

### Minimal reproducible example

Run `yarn ios` in this repo: https://github.com/rudyhuynh/AwesomeTSProject

**Comment by agostinhodev** [comment]
Same here!
The command `npx install-expo-modules@latest` installs the expo `47.0.10`. 

I've tried downgrading my expo version in `package.json` to 
`"expo": "47.0.9"`
 and after that run 
`yarn install --no-cache`,
 so I got success!

I'm still researching more about this error in `47.0.10`. For now, I believe that solves your case!

**Comment by rudyhuynh** [comment]
> I've tried downgrading my expo version in package.json to
"expo": "47.0.9"

My project above already has expo 47.0.9.
However, I run `npx install-expo-modules@0.3.8` which installs expo 46, and it build success now.

**Comment by Kudo** [comment]
hi @rudyhuynh! for your case, sdk 47 requires xcode 14 to build ios code. please try to upgrade xcode 14. hopefully it works for you. thanks!
