### ISSUE TITLE
Expo Android build fails: boost not properly installed

### ISSUE THREAD

**Issue by maartenweyns** [expo/expo#20679]
### Summary

When trying to build my Android app with `expo run:android`, I get an error in `Task :expo-modules-core:buildCMakeDebug[arm64-v8a]`: The logs complain about the `boost/operators.hpp` file not being found. This makes sense, as the download for boost is still processing during the build.

However, after manually adding the folder in the required place, the task still complains about some files in the `boost` folder not existing.

Obviously, something is going wrong with the build. This is very frustrating, as I am fully unable to build my Android app.

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.0 Fedora Linux 37 (Workstation Edition)
      Shell: 5.2.9 - /bin/bash
    Binaries:
      Node: 18.12.1 - /usr/bin/node
      Yarn: 1.22.17 - /usr/bin/yarn
      npm: 8.19.2 - /usr/bin/npm
    npmPackages:
      expo: ~47.0.9 => 47.0.10 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    Expo Workflow: bare
```

### Minimal reproducible example

This happens on a fully blank application created with the following command:

```
yarn create expo-app -t expo-template-blank-typescript TestApp
```

**Comment by Mfweb** [comment]
same problem

**Comment by ccarlitoxs** [comment]
same problem!!!!

**Comment by viliammojsky** [comment]
Same problem, but the "solution" is easy:
1. Start the development server (npx expo start)
2. Await the whole process. If an error occurs, do not terminate the job. Let it download all its files.
3. After the files are downloaded and the build is officially failed. Start the development server again. It will work.

It seems there is a problem with awaiting for all the files to download - it requires them before they are downloaded. When the error occurs, the downloading is not terminated automatically. If you let it download the boost_1_76_0.tar.gz file, it will be cached and on the next build it will be marked as UP-TO-DATE and used from cache. Without the need to download it, the file is immediately ready and there is no error on requiring it.

Important note - if you clear cache, you will face this problem again. It just needs to cache the boost_1_76_0.tar.gz file. And we just need to fix the build so it awaits for the files to download :D

**Comment by maartenweyns** [comment]
Yes, that should work. However, for some reason it didn't for me. However, I still decided to create this issue as this is something that should be fixed 😃 
For the moment, I got everything working on expo 46. I saw the PR that got merged, so I'll wait with going to 47 until the fixed version is released

**Comment by lindan4** [comment]
Same problem. When will the supposed fix be merged?

**Comment by SohelIslamImran** [comment]
Same issue

**Comment by mateitudose** [comment]
Seems like this also happens when using `"developmentClient": true` in `eas.json` config file.

**Comment by radko93** [comment]
This happens for me on a RN project with latest expo added

**Comment by Kudo** [comment]
hello everyone! we've published `expo@47.0.12` with a fix that would resolve the build error. please try to upgrade the `expo` package. if anyone still encounters the boost build error, please let me know. thanks for reporting the issue!

**Comment by scottmas** [comment]
Fixed it for me 👍

**Comment by lindan4** [comment]
works now
