### ISSUE TITLE
[Android] Expo Splash Screen warning at app start up - SDK 47

### ISSUE THREAD

**Issue by jhonatabonadio1** [expo/expo#20677]
### Summary

I recently updated my Expo SDK to version 47 and updated React Native to version 0.70.5. When my app starts, on android devices, the following alert is displayed:

```
Possible Unhandled Promise Rejection (id: 0):
Error: No native splash screen registered for provided activity. Please configure your application's main Activity to call 'SplashScreen.show' (https://github.com/expo/expo/tree/main/packages/expo-splash-screen#-configure-android).
```

I've already looked through all my code and it appears that everything is set up correctly.

android/app/src/main/res/drawable/splashscreen.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

   <item android:drawable="@color/splashscreen_background"/>
    <item>
        <bitmap
            android:gravity="center"
            android:src="@drawable/splashscreen_image"
        />
    </item>
</layer-list>
```

android/app/src/main/res/values/colors.xml:
```
<resources>
  <color name="splashscreen_background">#FFFFFF</color>
  <color name="app_bg">#12a454</color>
  <color name="colorPrimary">#023c69</color>
  <color name="colorPrimaryDark">#ffffff</color>
</resources>
```

android/app/src/main/res/values/styles.xml:
```
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowBackground">@drawable/splashscreen</item>
    <item name="android:statusBarColor">@color/app_bg</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
  </style>
</resources>
```

android/app/src/main/res/values/strings.xml:
```
<resources>
  <string name="expo_splash_screen_resize_mode">native</string>
</resources>
```

android/app/src/main/AndroidManifest.xml

```
<application android:name=".MainApplication">
  ...
  <activity
    android:name=".MainActivity" 
    android:theme="@style/AppTheme" 
    android:label="@string/app_name"        
    android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode" 
    android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:exported="true" 
    android:screenOrientation="portrait"
  >
    ...
  </activity>
</application>
```

App.tsx
```
import React, { useCallback } from 'react';

import { View } from 'react-native';

import theme from './src/global/styles/theme'

import { Routes } from './src/routes';
import { AppProvider } from './src/hooks';

import * as SplashScreen from 'expo-splash-screen';
import * as Font from 'expo-font';

import { 
  Roboto_300Light,
  Roboto_400Regular,
  Roboto_500Medium,
  Roboto_700Bold,
 } from '@expo-google-fonts/roboto';

SplashScreen.preventAutoHideAsync();

export default function App() {
  
  const [fontsLoaded] = Font.useFonts({
    Roboto_300Light, Roboto_400Regular, Roboto_500Medium, Roboto_700Bold
  })

  const onLayout = useCallback(async () => {
    if (fontsLoaded) {
      await SplashScreen.hideAsync();
    }
  }, [fontsLoaded]);

  if (!fontsLoaded) {
    return null;
  }

  return(
    <View style={{flex:1}} onLayout={onLayout}>
    <ThemeProvider theme={theme}>
      <AppProvider>
        <Routes />
      </AppProvider>
    </ThemeProvider>
 </View>
  )
}
```

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      expo-splash-screen: ^0.17.5
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

- Create React Native app with Expo SDK 47 in Bare Workflow.
- Install Expo Splash Screen Package
- Follow the installation guide from the expo splash screen repository page.
- Run "yarn android"

**Comment by daybreaker** [comment]
Having this same issue, out of nowhere. On Expo 46, worked fine a few months ago, went to do some work today and the app just doesnt load (white screen is overlaying everything, get the same Promise rejected warning), with no code changes made in the meantime.

Did you ever figure it out?
