### ISSUE TITLE
[android] Camera black screen preview output

### ISSUE THREAD

**Issue by jwandrews** [expo/expo#2068]
### Environment

**Environment:**
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

**Packages: (wanted => installed)**
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

**Diagnostics report:**
  https://exp-xde-diagnostics.s3.amazonaws.com/carpages-75bf1b8c-0f1c-4b61-a6d6-d2d542b0e45b.tar.gz

**App Target:**
Android, iOS - ExpoKit
Expo SDK: v29.0.0

### Steps to Reproduce

Use the Expo Camera component.

Load app on Galaxy S6 (only android device I have to test against)

### Expected Behavior

Expected Camera preview to show the camera output.

### Actual Behavior

Black screen. No preview output.
However, if I app switch and go back into the affected app, the preview shows up.

While handling camera component mount errors, this error is output:
`Camera component could not be rendered - is there any other instance running?`. However, I am definitely not mounting the camera previously, and AFAIK, I am not trying to mount the camera multiple times by accident.

BTW, the camera component works as expected on iOS.

**iOS Screenshot**
![img_0005](https://user-images.githubusercontent.com/7916874/43597515-4c184a9e-9650-11e8-82df-b1882d8ce9a7.PNG)

**Android Screenshot**
![screenshot_20180802-123210](https://user-images.githubusercontent.com/7916874/43597535-5e2eb40c-9650-11e8-8ab6-785ebdb6b509.png)

### Reproducible Demo

https://snack.expo.io/Sk81l2lB7

**Comment by jwandrews** [comment]
Disregard. 

I think I was being tripped by a few things. 
1. I was asking for Permissions in `componentDidMount`, not `componentWillMount`.
2. I was using an invalid value for the ratio being passed to the Camera component.

**Comment by EskelCz** [comment]
for future reference, here is how to do it: https://snack.expo.io/@brandon_altschool/camera-snack
