### ISSUE TITLE
`getExpoPushTokenAsync` doesn't work well after building the app

### ISSUE THREAD

**Issue by marina-ki** [expo/expo#20681]
### Summary

`registerForPushNotificationsAsync` function works fine on Expo Go, but when I download the apk file to my android device, I get an error.

### What platform(s) does this occur on?

Android

### Environment
**npx expo-env-info**
   SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.1.1
    Expo Workflow: managed

**My android device**
- Galazy Z Fold3
- android 12

### Minimal reproducible example

The code to get the device token is as follows:

```
async function registerForPushNotificationsAsync() {
  let token;

  if (Platform.OS === "android") {
    Notifications.setNotificationChannelAsync("default", {
      name: "default",
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: "#FF231F7C",
    });
  }

  if (Device.isDevice) {
    const { status: existingStatus } =
      await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;

    if (existingStatus !== "granted") {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }

    if (finalStatus !== "granted") {
      alert("Failed to get push token for push notification!");
      return;
    }

    try {
      token = (await Notifications.getExpoPushTokenAsync()).data;
    } catch (e) {
      alert(JSON.stringify(e)); // here!!!!
    }
  } else {
    alert("Must use physical device for Push Notifications");
  }

  return token;
}
```

When I run the app on Expo Go on the device, I can get the TOKEN successfully.

However, when I run an apk file that I built and downloaded, the following alert occurs.

```
{"code":"E_UNEXPECTED_ERROR", "line":50, "column":360, "sourceURL":"index.android.bundle"}
```
![Screenshot_20230103_152210_expo-push-example](https://user-images.githubusercontent.com/54174518/210309367-cf98e2b4-08a4-4887-a01a-5e404d948c32.jpg)

## FYI
How to build
`$ eas build -p android --profile preview`

eas.json
```
{
...
  "build": {
    "develop": {
      "distribution": "internal",
      "developmentClient": true
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      }
    },
...
}

```

**Comment by tanhsnkt1997** [comment]
same !!

**Comment by vladis-c** [comment]
I got this on Android 13 in .aab app 😭

**Comment by Bloodykilla** [comment]
same...

**Comment by Bloodykilla** [comment]
and so, after 1 day of brainstorming, I finally managed to solve this issue: all you need to do is connect the FCM (read this [https://docs.expo.dev/push-notifications/using-fcm/]) service and add "google-services.json" to your directory and then plug it in App.json like this `"android": {
      "package": "com.example",
      "googleServicesFile": "./google-services.json"
    },`
