### ISSUE TITLE
v29: Amplitude module doesn't log events

### ISSUE THREAD

**Issue by savvaoff** [expo/expo#2069]
v28: works as expected
v29: no events logged, at all

### Environment

v29

### Expected Behavior

Amplitude: logs events

### Actual Behavior

Amplitude: doesn't log events

### Reproducible Demo

```
    Amplitude.initialize(apiKey);
    Amplitude.logEvent('EVENT_TEST');
```

**Comment by sjchmiela** [comment]
The bugfix has been deployed, please rebuild your apps and check if the issue has been fixed.
