### ISSUE TITLE
Unable to use expo modules in bare workflow on iOS

### ISSUE THREAD

**Issue by khankuan** [expo/expo#20696]
### Summary

Unable to run app on iOS.

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 19.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.2.0 - /opt/homebrew/bin/npm
      Watchman: 2022.12.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/k/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.10 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.6 => 0.70.6 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

**To Reproduce**
npx react-native init expotest 
npx install-expo-modules@latest
npx pod-install
Add registerRootComponent to App.js
npm run android // works
npm run ios // fails
```
dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'React-CoreModules' from project 'Pods')


2023-01-03 22:02:04.966 xcodebuild[2165:5228174] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2023-01-03 22:02:04.966 xcodebuild[2165:5228174] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 (in target 'ExpoModulesCore' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoModulesCore' from project 'Pods')
(2 failures)

```

**Comment by tsapeta** [comment]
Unfortunately I'm not able to reproduce that 😕 I'll try again later on another machine with M1.
In the meantime, could you help me and try to do the same steps, but with `npx create-expo-app@latest expotest` instead of `npx react-native init expotest`?

**Comment by khankuan** [comment]
I would like to use expo modules on a project that is on bare workflow. create-expo-app would require using managed workflow?

**Comment by tsapeta** [comment]
Yes and no 😅 `create-expo-app` creates an app for managed workflow, but then you can run `npx expo prebuild` that generates `ios` and `android` folders (so basically it becomes a bare workflow project).

Generally I only want to check if it builds for you with the configuration from `create-expo-app` instead of `react-native init` app (they are a bit different).

Then the steps would be:
```
npx create-expo-app@latest expotest
npx expo prebuild
npm run ios
```

**Comment by khankuan** [comment]
Thanks for the explanation. I did get errors when running ios after prebuilding:
```
(node_modules/expo-modules-core/ios/Swift/DynamicTypes/DynamicEnumType.swift:7:22)

   5 |  */
   6 | internal struct DynamicEnumType: AnyDynamicType {
>  7 |   let innerType: any Enumerable.Type
     |                      ^ protocol 'Enumerable' can only be used as a generic constraint because it has Self or associated type requirements
   8 | 
   9 |   func wraps<InnerType>(_ type: InnerType.Type) -> Bool {
  10 |     return innerType == InnerType.self


❌  (node_modules/expo-modules-core/ios/Swift/DynamicTypes/DynamicType.swift:21:36)

  19 |     return DynamicConvertibleType(innerType: ConvertibleType)
  20 |   }
> 21 |   if let EnumType = T.self as? any Enumerable.Type {
     |                                    ^ protocol 'Enumerable' can only be used as a generic constraint because it has Self or associated type requirements
  22 |     return DynamicEnumType(innerType: EnumType)
  23 |   }
  24 |   if let SharedObjectType = T.self as? SharedObject.Type {


❌  (node_modules/expo-modules-core/ios/Swift/Objects/PropertyComponent.swift:142:9)

  140 |       }
  141 |       guard let getter = self.getter else {
> 142 |         return
      |         ^ non-void function should return a value
  143 |       }
  144 |       return try getter.call(by: this, withArguments: args)
  145 |     }


❌  (node_modules/expo-modules-core/ios/Swift/Objects/PropertyComponent.swift:157:9)

  155 |       }
  156 |       guard let setter = self.setter else {
> 157 |         return
      |         ^ non-void function should return a value
  158 |       }
  159 |       return try setter.call(by: this, withArguments: args)
  160 |     }

```

**Comment by tsapeta** [comment]
That's Xcode, we can't do anything with this 🤷‍♂️
