### ISSUE TITLE
RN: CommandError: Can't determine id of Simulator app. node 18, after new install create-expo-app

### ISSUE THREAD

**Issue by adamSplendex** [expo/expo#20693]
### Summary

Hey guys.

Would like to upgrade our existing app to latest tech, we see expo is the recommended way now. I want to create the app and one by one apply the screens and code to the new version.

I created a new project via 

`npx create-expo-app <AppName>`
`cd <Appname>`
`npx expo prebuild`

opened Android Studio and started a Pixel 5
opened simulator with `open -A Simulator` // tried it with sudo too

then
`
npm run start
`

i am pressing a - works perfectly fine 

i am pressing i

i get the following message: 
`CommandError: Can't determine id of Simulator app; the Simulator is most likely not installed on this machine. Run sudo xcode-select -s /Applications/Xcode.app`

I tried every possible solution, restarted everything, reinstalled node, cleared cache, checked privacy settings, resintalled developer tools, i can't make it work guys, spent more then a day on this.

I appreciated your support beforehand.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.1.0/bin/yarn
      npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
      Watchman: 2022.11.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.9 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    Expo Workflow: bare
    

### Please specify your device/emulator/simulator platform, model and version

MacOS Montery, 2021 m1 max pro, 64gb macbook, Iphone 13 pro max/ios 15.5 simulator

### Error output

CommandError: Can't determine id of Simulator app; the Simulator is most likely not installed on this machine. Run `sudo xcode-select -s /Applications/Xcode.app`

### Reproducible demo or steps to reproduce from a blank project

See my summary.

`
npx create-expo-app <AppName>
cd <Appname>
npx expo prebuild

opened Android Studio and started a Pixel 5
opened simulator with `open -A Simulator` // tried it with sudo too

then
`
npm run start
`

i am pressing a - works perfectly fine 

i am pressing i

expected behaviour: app starts on opened ios simulator or opens a simulator

actual behaviour: i get the above error message no matter what i do.

**Comment by tbillington** [comment]
Also seeing this, can't find a cause. My team mates don't have the same issue and we have very similar setups.

Happy to help debug.

**Comment by tbillington** [comment]
Tried opening the `ios` generated directory in XCode and attempted to Build with the play button. The build failed in XCode but running `expo run:ios` in my project again after that succeeded. Seems like a successful workaround for my setup, although I still don't know the cause of the issue. 

Cheers Evan

**Comment by EvanBacon** [comment]
Cannot reproduce, a possible solution could be worked into doctor but it's hard to say as the Simulator app is a bit of a black box.

**Comment by raphaelmerx** [comment]
Had the same issue, fixed after opening XCode then opening the Simulator manually from there.

**Comment by AngCosmin** [comment]
Running `npx expo-doctor@latest` fixed the issue for me
