### ISSUE TITLE
No push notification badge in iOS

### ISSUE THREAD

**Issue by stesvis** [expo/expo#20692]
### Summary

When I send push notifications from the backend (.NET) the badge number does not display in iOS.
In Android it works well, after every notification the number increases automatically, but in iOS it does not even show.

The only way to display it is if I set the `PushBadgeCount` in the backend with:
```cs
                var pushTicketReq = new PushTicketRequest()
                {
                    //...
                    PushBadgeCount = 1,
                    //...
                };
```
But of course it will always show `1`. I can't keep track of the correct number in the backend for everybody.

Shouldn't it just work like on Android?

I also found that calling `await Notifications.setBadgeCountAsync(badgeCount);` doesn't really set the app icon badge, except when I execute it via ExpoGo.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2
      expo: ^47.0.8 => 47.0.8
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: managed

### Minimal reproducible example

```cs
                var expoSDKClient = new PushApiClient();
                var pushTicketReq = new PushTicketRequest()
                {
                    PushTo = notification.ExpoPushTokens.ToList(),
                    PushTitle = notification.Title,
                    PushBody = notification.Message,
                    PushBadgeCount = 1,
                    PushChannelId = "default",
                    PushData = notification.Data,
                    PushSound = "default"
                };
                var result = await expoSDKClient.PushSendAsync(pushTicketReq);
```

**Comment by dpuckett** [comment]
Did you manage to solve this issue?
