### ISSUE TITLE
`withXcodeProject` in `app.config.js` does not modify project files

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/expo#20718]
### Summary

When I add the following code to a fresh project (only changed `app.json` to `app.config.js`) and run `npx expo prebuild --clean -p ios` the command completes successfully but actually nothing was changed. The code was taken 1:1 from the examples in the docs.

```
import { withXcodeProject } from "expo/config-plugins";

const withCustomProductName = (config, customName) => {
  return withXcodeProject(config, async (config) => {
    const xcodeProject = config.modResults;
    xcodeProject.productName = customName;

    return config;
  });
};

const config = ...

export default withCustomProductName(config, "new_name");
```

### What platform(s) does this occur on?

iOS

### SDK Version

47

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.1 - /usr/local/bin/npm
      Watchman: 2022.12.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.9 => 47.0.11
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

1. Create a new project with `npx create-expo-app my-app`
2. Rename `app.json` to `app.config.js` and change the code to this:

```
import { withXcodeProject } from "expo/config-plugins";

const withCustomProductName = (config, customName) => {
  return withXcodeProject(config, async (config) => {
    const xcodeProject = config.modResults;
    xcodeProject.productName = customName;

    return config;
  });
};

const config = // <OLD VALUE OF app.json>

export default withCustomProductName(config, "new_name");
```

3. Run `npx expo prebuild --clean -p ios` and see that "new_name" wasn't written to any of the project files

**Comment by alanjhughes** [comment]
And you have added the plugin to the plugins array in your app.config?

**Comment by stefan-schweiger** [comment]
@brentvatne can you please reopen the issue I've added a repro and updated the initial comment

https://github.com/stefan-schweiger/expo-xcode-repro/settings

**Comment by stefan-schweiger** [comment]
@alanjhughes no need to include the plugin (at least as far as I'm aware), I'm directly changing my `app.config.js`. See the repro I've added

**Comment by alanjhughes** [comment]
@stefan-schweiger I can't open the repro. Getting a 404. It is a requirement to add the plugin to your app.config
This is the example from the docs
```json
{
  "name": "my-app",
  "plugins": [["./my-plugin", "custom"]]
}
```
You can see it [here](https://docs.expo.dev/guides/config-plugins/#creating-a-plugin)

**Comment by alanjhughes** [comment]
@stefan-schweiger got your repro now. Your app.config.js is incorrect. You're trying to export your config and the plugin at the same time. These should be separate files. app.config.js default export is your config, your plugin's default is a function that receives your config

**Comment by stefan-schweiger** [comment]
@alanjhughes this shouldn't matter, all a plugin really does is provide a named wrapper. No reason you can't straight up export the plugin function with the config. Even in the example you linked they use the plugin straight

**Comment by alanjhughes** [comment]
@stefan-schweiger the example shows two files. `my-plugin.js` and `app.config.js` with the plugin added to the plugins array. How is this the same as what you have provided?

**Comment by stefan-schweiger** [comment]
@alanjhughes I'm refering to this:

```
const withMySDK = (config, { apiKey }) => {
  // Ensure the objects exist
  if (!config.ios) {
    config.ios = {};
  }
  if (!config.ios.infoPlist) {
    config.ios.infoPlist = {};
  }

  // Append the apiKey
  config.ios.infoPlist['MY_CUSTOM_NATIVE_IOS_API_KEY'] = apiKey;

  return config;
};

// 💡 Usage:

/// Create a config
const config = {
  name: 'my app',
};

/// Use the plugin
export default withMySDK(config, { apiKey: 'X-XXX-XXX' });
```

no plugin in the config etc. just straight up export your config function.

**Comment by alanjhughes** [comment]
@stefan-schweiger yes, that's just the plugin, it follows up with an example of adding it to the app.config. I'm not sure if that example is correct but even if it was, I've never seen it used that way in practice. Plugins are always added to the plugin array in the config

**Comment by stefan-schweiger** [comment]
@alanjhughes the documentation is worded in such a way, as this should be the simplest case were you directly change the config and only if you want use your config from a different file you need to jump through those hoops, so either the documentation is very badly worded, or this is broken.

**Comment by rayronvictor** [comment]
@stefan-schweiger, use `xcodeProject.updateProductName(customName)`

```js
import { withXcodeProject } from "expo/config-plugins";

const withCustomProductName = (config, customName) => {
  return withXcodeProject(config, async (config) => {
    const xcodeProject = config.modResults;
    // xcodeProject.productName = customName;
    xcodeProject.updateProductName(customName);

    return config;
  });
};

const config = ...

export default withCustomProductName(config, "new_name");
```

To see all methods of `config.modResults` just `console.dir(config.modResults.__proto__)`
