### ISSUE TITLE
Expo SDK 46: EXConstants Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by ismaelbarry** [expo/expo#20715]
### **Summary**

expo-constants throws 'Command PhaseScriptExecution failed with a nonzero exit code' when building iOS project in Xcode. Unfortunately, there are no other error details given.

### **Managed or bare workflow? If you have iOS/ or android/ directories in your project, the answer is bare!**

bare

### **What platform(s) does this occur on?**

iOS

### **My ask**

I would love to know what I may be doing wrong, if there's a bug, or something that I'm missing when upgrading from SDK 45 to SDK 46. Thanks all! :) 

### What platform(s) does this occur on?

iOS

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 19.3.0 - ~/Projects/[REDACTED]/node_modules/.bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 7.20.5 - ~/Projects/[REDACTED]/node_modules/.bin/npm
      Watchman: 2023.01.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.19 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 2.18.0
    Expo Workflow: bare
```

### Minimal reproducible example

When upgrading from SDK 45 (which my projects runs successfully) to SDk 46, I run the following commands:

```
♥ expo-cli upgrade
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard
✔ You are currently using SDK 45.0.0. Would you like to update to the latest version, 47.0.0? … no

✔ Choose a SDK version to upgrade to: › 46.0.0


✔ Installed expo@^46.0.0
✔ Validated configuration.
✔ No additional changes necessary to app.json config.

✔ Updated known packages to compatible versions.
✔ Cleared packager cache.
✔ Validated project

👏 Automated upgrade steps complete.
...but this doesn't mean everything is done yet!

Please refer to the release notes for information on any further required steps to update and information about breaking changes:
https://blog.expo.dev/expo-sdk-46-c2a1655f63f7

♥ cd iOS && pod install
```

After the above sequence, I have the following versions installed in my package.json file:

```
    "expo-updates": "~0.14.7",
    "expo-constants": "13.2.4",
```

However, when I open the xcworkspace file and attempt to run it and get the the following error in Xcode:

![Error](https://user-images.githubusercontent.com/13290756/210693314-08786170-8253-4ce8-b8e9-eddeab3ed40f.png)

**Comment by brentvatne** [comment]
you can see more info in xcode by clicking on this button

![Group 1 (2)](https://user-images.githubusercontent.com/90494/211120681-21f6cee5-0450-4525-aad0-6d4240c23254.png)

**Comment by misbell** [comment]
why was this closed as completed?? I have the same problem after trying it today.

**Comment by henryteng07** [comment]
@misbell Im facing the same error could you help me? I have no idea how to fix it

**Comment by axelpey** [comment]
same here @misbell

**Comment by henryteng07** [comment]
> you can see more info in xcode by clicking on this button
> 
> ![Group 1 (2)](https://user-images.githubusercontent.com/90494/211120681-21f6cee5-0450-4525-aad0-6d4240c23254.png)

@axelpey I did this, and right click copied the error message. After pasting it somewhere, it shows more detail about the error. In my case it was expo-video

**Comment by axelpey** [comment]
yep thank you i found it too! Crazy that xcode is so fucking impossible to understand that i couldn't find the more detailed logs
