### ISSUE TITLE
I have a delay of almost 2 seconds when I run takePictureAsync.

### ISSUE THREAD

**Issue by anderpaz** [expo/expo#20710]
### Summary

I need to take the picture and then show it to the user, my call is this.

    cameraRef.current.takePictureAsync(options || {
           quality: 0.5,
           imageType: ImageType.jpg,
           base64: true,
           onPictureSaved: (and) => {
             setLoading(false);
             if (onReturnTakePhoto) onReturnTakePhoto(e);
           },
        },
    );

I've tried using the pausePreview method to improve the user's view, but without success.
The delay is quite visible.
Test the react-native-vision-camera library and this delay doesn't happen.

Has anyone gone through this and can help me out?

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Manjaro Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.21.0 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.19.2 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 27, 28, 29, 30, 31, 32, 33
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom

**Comment by brentvatne** [comment]
you may want to use react-native-vision-camera instead, it is a perfectly reasonable alternative. alternatively, you can try changing compression or not returning base64, both of which may be slowing down the operation.
