### ISSUE TITLE
" npm install -g expo-cli " This command is not running in node 18

### ISSUE THREAD

**Issue by ishtiaqSamdani** [expo/expo#20717]
### Summary

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'expo-cli@6.0.8',
npm WARN EBADENGINE   required: { node: '>=12 <=16' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }

```

I am getting this in the terminal when I run the command.
```
npm install -g expo-cli
```

how can solve this problem?

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

### Minimal reproducible example

no code cause the CLI itself is not working

**Comment by mateitudose** [comment]
As the warning suggests, you need to downgrade your Node version from 18 to 16 to install expo-cli globally. Starting with Expo 46, you don't need the global expo-cli, new apps include a local cli.

**Comment by ishtiaqSamdani** [comment]
should I uninstall node 18 and then install node 16 or there is any other clean way

**Comment by ishtiaqSamdani** [comment]
should I uninstall node 18 and then install node 16 or there is any other clean way
