### ISSUE TITLE
Black Status Bar after setting sticky-immersive

### ISSUE THREAD

**Issue by ggchicote** [expo/expo#20729]
### Summary

After setting `androidNavigationBar: { visible:'sticky-immersive' }` in my app.json file a black bar replaces the Status Bar.

![Black bar replace Status Bar](https://user-images.githubusercontent.com/70538642/210981922-ad3731eb-abdd-4bec-b667-b5b5b6276d4e.png)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

`app.json` file

```
{
  "expo": {
    "name": "testing-app",
    "slug": "testing-app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "androidNavigationBar" : {
      "visible":"sticky-immersive"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```
` App.js` file

```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Black bar on top!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by brentvatne** [comment]
please provide a repro against the latest sdk version
