### ISSUE TITLE
how can I browse sqlite database created by expo?

### ISSUE THREAD

**Issue by aprilmintacpineda** [expo/expo#2072]
I'm using the `SQLite` from `expo `. I want to see if the data inserted on the database is actually accurate, is there a way for me to browse the database created by `SQLite.openDatabase`?

**Comment by AdamJNavarro** [comment]
Hey @aprilmintacpineda, these types of questions are better served/belong on StackOverflow https://stackoverflow.com/ or our forums https://forums.expo.io/

Can you please create a forum post ideally or one on SO.

Cheers,

Adam

**Comment by subashcs** [comment]
Searching for the answer to same question.Can anyone help ?Also i want to create a backup of the database i have created in expo.
