### ISSUE TITLE
expo.dev sign up error

### ISSUE THREAD

**Issue by BubbleM** [expo/expo#20728]
### Summary

![image](https://user-images.githubusercontent.com/15670955/210978298-64559d87-8dd9-4ed1-a556-1269d7ada0de.png)

### Environment

? How would you like to authenticate? Make a new Expo account

Thanks for signing up for Expo!
Just a few questions:

? E-mail: xxx@163.com
? Username:xxx
? Password: xxx
? Confirm Password: xxx
ApiV2Error: We were unable to create your account. Go to https://expo.dev/signup in a browser to sign up.
    at /xdl@51.6.4/src/ApiV2.js:187:19
    at Generator.throw (<anonymous>)
    at step (/Users/liumin/.nvm/versions/node/v14.18.1/lib/node_modules/exp/node_modules/xdl/build/ApiV2.js:42:191)
    at /Users/liumin/.nvm/versions/node/v14.18.1/lib/node_modules/exp/node_modules/xdl/build/ApiV2.js:42:402
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'VALIDATION_ERROR',
  _isApiError: true,
  serverStack: undefined,
  details: undefined
}
[17:50:25] Error registering user: We were unable to create your account. Go to https://expo.dev/signup in a browser to sign up.

### Minimal reproducible example

a is not a function

**Comment by brentvatne** [comment]
```
? How would you like to authenticate? Make a new Expo account

Thanks for signing up for Expo!
Just a few questions:
```

it looks like you saw this prompt because you are using a very old version of expo-cli

as for the error on the website, are you possibly using a browser extension that could be causing this? if you can let us know some reproducible set of credentials this occurs with it would be helpful

**Comment by huangjs888** [comment]
I want ask the same question too.

**Comment by y213140** [comment]
+1

**Comment by qqqrr** [comment]
+1

**Comment by y213140** [comment]
vpn - close
