### ISSUE TITLE
Android 13 notification icon

### ISSUE THREAD

**Issue by quentinmodena** [expo/expo#20724]
### Summary

Android 13 changed the way notifications are displayed in the control panel : notification icons a bigger than before. As you can see in the below screenshot my adaptive icon (android.adaptiveIcon.foregroundImage) doesnt adapat correctly to the new icon format. 

I also tried setting the notification.icon in the app config file with a specific 96x96 png file but it produces the same result, my icon doesn't adapt to the whole circle.

Android 13 :
![Screenshot_20230105_144703_One UI Home](https://user-images.githubusercontent.com/16798995/210794984-df55af2a-d934-4fd3-a282-f6376752dbda.jpg)

Android 12 :
![Capture d’écran2023-01-05](https://user-images.githubusercontent.com/16798995/210797206-66ea6f65-e90c-450a-aef8-3250d11d95b4.jpg)

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 16.17.1 - /usr/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.15.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 30, 33
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    npmGlobalPackages:
      eas-cli: 3.0.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

Create an app, send a notification on an android 13 device

**Comment by joycelsq84** [comment]
how to resolve?

**Comment by Rc85** [comment]
Did you find a fix?

**Comment by quentinmodena** [comment]
I didn't found any fix, the best solution i found is to provide a custom value for "expo.notification.icon" in the app config file. This solution makes the icon a bit bigger but doesnt fill the whole circle at all
