### ISSUE TITLE
Upgrading from SDK 45 to SDK 47

### ISSUE THREAD

**Issue by DavidTaylor96** [expo/expo#20732]
### Summary

I have upgraded to 47 and now the app is getting stuck on the splash screen with this error message in the terminal

` 
ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
 A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
`

Nothing has changed with the 'AppRegistry'. it looks list this. 

`
import { registerRootComponent } from 'expo';
import App from './src/App';

registerRootComponent(App);
`

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.18.1 - /usr/local/opt/node@16/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 7.24.2 - ~/Desktop/SDK-update/iServe/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/davidt2/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.9 => 47.0.11 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.0
    Expo Workflow: bare

### Minimal reproducible example

package.json looks like this. 

{
  "name": "iserve-app",
  "version": "1.25.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "prepare": "husky install",
    "lint": "tsc --noemit && eslint --ext .js,.jsx,.ts,.tsx ./",
    "prettier-format": "prettier --config .prettierrc '**/*.{json,js,jsx,ts,tsx,css,scss,md}' --write",
    "pods": "cd ios && pod install && cd ..",
    "test": "jest"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free-solid": "^5.0.13",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@fortawesome/react-native-fontawesome": "^0.2.7",
    "@openspacelabs/react-native-zoomable-view": "^2.0.4",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/netinfo": "9.3.5",
    "@react-native-segmented-control/segmented-control": "2.4.0",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "@react-navigation/stack": "^6.2.3",
    "@reduxjs/toolkit": "^1.7.1",
    "@sentry/react-native": "4.9.0",
    "buffer": "^6.0.3",
    "date-fns": "^2.28.0",
    "decimal.js": "^10.3.1",
    "dotenv": "^14.1.0",
    "eslint": "7.28",
    "exact-math": "^2.2.3",
    "expo": "~47.0.9",
    "expo-application": "~5.0.1",
    "expo-asset": "~8.7.0",
    "expo-barcode-scanner": "~12.1.0",
    "expo-battery": "~7.0.0",
    "expo-blur": "~12.0.1",
    "expo-camera": "~13.1.0",
    "expo-constants": "~14.0.2",
    "expo-device": "~5.0.0",
    "expo-media-library": "~15.0.0",
    "expo-network": "~5.0.0",
    "expo-notifications": "~0.17.0",
    "expo-permissions": "~14.0.0",
    "expo-screen-orientation": "~5.0.1",
    "expo-sensors": "~12.0.1",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "~0.15.6",
    "intl": "^1.2.5",
    "json-bigint": "^1.0.0",
    "lottie-react-native": "5.1.4",
    "moment": "^2.29.3",
    "moti": "^0.20.0",
    "native-base": "^3.3.3",
    "patch-package": "^6.5.0",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-animated-loader": "^0.0.9",
    "react-native-animated-segment-control": "^1.0.9",
    "react-native-currency-input": "^1.0.1",
    "react-native-device-detection": "^0.2.1",
    "react-native-flash-message": "^0.2.1",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-network-logger": "^1.12.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-segment-controller": "^1.0.0",
    "react-native-segmented-control-tab": "^4.0.0",
    "react-native-side-drawer": "^1.2.9",
    "react-native-svg": "13.4.0",
    "react-native-swipe-detect": "^1.0.10",
    "react-native-tab-view": "^3.1.1",
    "react-native-tableview-simple": "^4.3.1",
    "react-native-toast-notifications": "^3.2.3",
    "react-native-udp": "^4.1.5",
    "react-native-uuid": "^2.0.1",
    "react-native-web": "~0.18.7",
    "react-redux": "^7.2.6",
    "react-router-native": "^6.2.1",
    "redux-persist": "^6.0.0",
    "semantic-release-expo": "^2.2.3",
    "sentry-expo": "~6.0.0",
    "xmldom": "^0.6.0",
    "zonal-iserve-native-data-tools": "file:./iServe-react-native-ZNLKeychainUpgradeHelper",
    "zustand": "^4.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@commitlint/cli": "^16.0.2",
    "@commitlint/config-conventional": "^16.0.0",
    "@expo/config": "^7.0.2",
    "@semantic-release/changelog": "^6.0.1",
    "@semantic-release/git": "^10.0.1",
    "@types/expo": "^33.0.1",
    "@types/jest": "^29.0.3",
    "@types/json-bigint": "^1.0.1",
    "@types/mocha": "^10.0.0",
    "@types/react": "~17.0.21",
    "@types/react-native": "^0.70.0",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/react-redux": "^7.1.22",
    "@types/react-router-native": "^5.1.3",
    "@typescript-eslint/eslint-plugin": "^5.9.1",
    "@typescript-eslint/parser": "^5.9.1",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "husky": "^7.0.4",
    "jest": "^26.6.3",
    "jest-expo": "^47.0.0",
    "jest-junit": "^13.0.0",
    "prettier": "^2.5.1",
    "react-devtools": "^4.26.0",
    "react-native-dotenv": "^3.3.1",
    "semantic-release": "^18.0.1",
    "semantic-release-slack-bot": "^3.4.1",
    "typescript": "^4.6.3"
  },
  "private": true
}

**Comment by secretyouth** [comment]
Following through the `expo-notifications` tutorial I am receiving the same issue. Everything worked until I integrated the expo-notifications package and was able to track it to that implementation.

If you need any advice or input I can provide please let me know.

**Comment by farmasek** [comment]
Hi, i did the same. Upgraded SDK from 45 to 47  a got this error 
```TypeError:` undefined is not an object (evaluating '_require$types.isPromise')
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.```
 
 After removing every component i tracked it to expo-notifications aswell. I have monorepo, so i created new app in the monorepo exactly like in monorepo example in docs, added expo-notifications package and crashed exactly the same even on first code init 
```
Notifications.setNotificationHandler({
   handleNotification: async (notification) => {
     return {
       shouldShowAlert: false,
       shouldPlaySound: true,
       shouldSetBadge: false,
     };
   },
 });
```
My guess is, it might have something to do with monorepo ? was using expo-yarn-workspaces before this update, but removed it as in docs https://docs.expo.dev/guides/monorepos/#remove-expo-yarn-workspaces

any idea ?

**Comment by DavidTaylor96** [comment]
I eventually found out it was "@react-native-segmented-control/segmented-control" Once I removed this package everything worked. It was due to the props that react-native 0.70.5 has deprecated 'ViewStyleProps' and some others.

**Comment by farmasek** [comment]
thanks, unfortunatelly thats not my case, i have a fresh npx crated app in the monorepo with only a few deps
```  "dependencies": {
    "expo": "~47.0.12",
    "expo-notifications": "^0.17.0",
    "expo-status-bar": "~1.4.2",
    "find-yarn-workspace-root": "^2.0.0",
    "react": "18.1.0",
    "react-native": "0.70.5"
  },```

**Comment by farmasek** [comment]
Ok, so what worked for me is adding transformer to metro.config

```

config.transformer = {
  getTransformOptions: async () => ({
    transform: {
      experimentalImportSupport: false,
      inlineRequires: true,
    },
  }),
  assetPlugins: ['expo-asset/tools/hashAssetFiles'],
};
```

dont know why, but it might help someone
