### ISSUE TITLE
Cannot get GCM token for device

### ISSUE THREAD

**Issue by KthProg** [expo/expo#2073]
### Environment

ExpoKit, running on Android, LG Stylo 3+

### Steps to Reproduce

1. Call `await Notifications.getExpoPushTokenAsync();`
2. Receive error

### Expected Behavior

1. Call `Notifications.getExpoPushTokenAsync();`
2. Receive token

### Actual Behavior

I get this error.
![screenshot_2018-08-04-16-56-33](https://user-images.githubusercontent.com/3527476/43680466-48466a4e-9809-11e8-9706-63069a90f63e.png)

### Reproducible Demo

I can't reproduce this issue in a demo. This happens every single time in my app, however. The first few calls to get the token seemed to work fine. Is this maybe some issue when you have already requested the Expo push token for that device?

**Comment by KthProg** [comment]
Adding [FCM](https://docs.expo.io/versions/latest/guides/using-fcm) details and using `exp start` appears to have fixed the issue.

**Comment by picklechips** [comment]
I started getting this error within the last couple of days, running with `exp start` instead of `npm start` fixed the problem 😄

**Comment by LouisJS** [comment]
Using `exp start` instead of `npm start` also did the trick for me. But why is that ?
Will there be any impact on my final build ?

**Comment by salihkiraz** [comment]
Make sure you're logged Expo. I improved when I logged in again.

`exp login`

**Comment by fadilnatakusumah** [comment]
same  with @salihkiraz login fix the issue

**Comment by VM8198** [comment]
try it on expo snack

**Comment by VM8198** [comment]
run expo login
login with your credentials and it will work fine...

**Comment by VM8198** [comment]
run expo login
login with your credentials and it will work fine...

**Comment by Raj1998** [comment]
> Make sure you're logged Expo. I improved when I logged in again.
> 
> `exp login`

thanks a lot... !!!!!

**Comment by ide** [comment]
Closing this since (a) logging into Expo CLI reportedly has fixed this for several people and because (b) Google has fully transitioned from GCM to FCM.

**Comment by sonianand11** [comment]
@salihkiraz you saved my day Thanks a lot `expo login` made it working

**Comment by coyotte508** [comment]
Just chiming in that for me  `expo login` on the computer was not enough, I had to login in the expo application as well...

**Comment by MisdakM** [comment]
`expo login` does the trick.

**Comment by Mazuco** [comment]
With expo login works, but you have create before an account, and start the app with: expo start

**Comment by alkeshattal** [comment]
**Please make sure that you are on the latest version of the Expo Client App, that supports the SDK you are running**
I had the older version of Expo Client (installed in Feb'20) and my react-native project was using SDK 37 released in April. I spent the entire day trying to figure out why the notification service is not working. Then I borrowed my friend's mobile (also on Android 9) today and it worked.
On further digging, saw the expo client release notes published on April 14 about support on SDK 37.
Updated my Expo Client
Logged in with my Expo account on both CLI and Client
Expo Start
It Worked!!!

I wonder why I wasn't prompted by the Expo App to update.
