### ISSUE TITLE
Clearing cache and restarting project overwrites monorepo root tsconfig.json

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#20738]
**See [second comment](https://github.com/expo/expo/issues/20738#issuecomment-1374335566) first**

### Summary

All of our custom `tsconfig.json` configuration is overwritten.

The CLI warns that the `extends` will be updated, but our configuration didn't extend anything and was overwritten completely with only:

```js
{
  "compilerOptions": {},
  "extends": "expo/tsconfig.base"
}
```

This isn't a critical issue since it should be spotted by users  in their version control but it's quite unexpected.

### SDK Version

SDK 47

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.1.0
    Expo Workflow: managed
```

### Minimal reproducible example

N/A

**Comment by Slapbox** [comment]
Whoops - like a noob I accidentally ran it in the root of the monorepo - that's why.

**But I'm keeping this open because it should presumably only update `extends` and not obliterate the `tsconfig.json`?**

**Comment by EvanBacon** [comment]
> N/A

Need a valid repro, the only issue I can detect is with the formatting on the log.
