### ISSUE TITLE
SDK 46: expo-linking needs access to the expo-constants manifest (app.json or app.config.js) to determine what URI scheme to use.

### ISSUE THREAD

**Issue by dochonglo** [expo/expo#20740]
### Summary

`expo-linking` needs access to the `expo-constants` manifest (`app.json` or `app.config js`) to determine what
URI scheme to use. Setup the manifest and rebuild:
https://github.com/expo/expo/blob/main/packages/ expo-constants/README.md

Below is a photo of the issue:

![IMG_BF08043DDE22-1](https://user-images.githubusercontent.com/13290756/211135174-9b14ed20-debc-4cba-a2bd-78011241b43e.jpeg)

**### Managed or bare workflow? If you have iOS/ or android/ directories in your project, the answer is bare!**

bare

### What platform(s) does this occur on?

iOS

### My question

It's unclear to me what this error is happening after upgrading from SDK 45 to 46. My scheme is already defined in my `app.json` file. Also, I've followed the link in the error, and I've set up the manifest correctly and rebuilt. Is this a bug?

### What platform(s) does this occur on?

iOS

### What platform(s) does this occur on?

iOS

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 19.3.0 - ~/projects/testing/node_modules/.bin/node
      npm: 7.20.5 - ~/projects/testing/node_modules/.bin/npm
      Watchman: 2023.01.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.19 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
      react-navigation: ^4.0.10 => 4.0.10 
      expo-linking: ~3.2.4
      expo-constants: ^14.0.2
      expo-updates: ~0.14.7
    Expo Workflow: bare
```

### Minimal reproducible example

```
♥ expo-cli upgrade
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard
✔ You are currently using SDK 45.0.0. Would you like to update to the latest version, 47.0.0? … no

✔ Choose a SDK version to upgrade to: › 46.0.0


✔ Installed expo@^46.0.0
✔ Validated configuration.
✔ No additional changes necessary to app.json config.

✔ Updated known packages to compatible versions.
✔ Cleared packager cache.
✔ Validated project

👏 Automated upgrade steps complete.
...but this doesn't mean everything is done yet!

Please refer to the release notes for information on any further required steps to update and information about breaking changes:
https://blog.expo.dev/expo-sdk-46-c2a1655f63f7

♥ cd iOS && pod install
```

**Comment by Cancuuu** [comment]
hi! how did you solved this? same error here.

**Comment by ManuLpz4** [comment]
@dochonglo did you solve it? I think it's something with the deprecated Expo CLI but I'm not sure and a friend is struggling with this issue too :/

**Comment by rafaelmaeuer** [comment]
@ManuLpz4 in my case I was able to fix it by adding following resolution for `expo-constants`:

```
"resolutions": {
	"expo-constants": "14.0.2"
}
```

The error occurred while resetting yarn.lock in the upgrade-progress from Expo-SDK 47 to 48.
