### ISSUE TITLE
Bare typescript template disappeared

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#20758]
### Summary

I have made heavy use of the bare expo Typescript template for prototyping and MVEs. This month it has disappeared from the Expo CLI. I think this belongs in the Expo CLI since: a) Typescript is de facto the standard now, not JS. and b) bare workflow for quick prototyping and MVEs is necessary prior to engaging with a managed Expo project. I don't want to have to be creating managed expo config and build files while I'm trying to prove out a simple function or example. 

### What platform(s) does this occur on?

Android, iOS, Web

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.5.1 - /usr/local/bin/fish
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/admin/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | AOSP ATD ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
```

### Minimal reproducible example

N/A

**Comment by brentvatne** [comment]
you can add typescript to any project by renaming any js file in the project to .ts or .tsx and then running `npx expo start` - we'll install all dependencies for you and create a tsconfig.json. alternatively, create an empty tsconfig.json and then run `npx expo start`. more info: https://docs.expo.dev/guides/typescript/

that said, i'd be in favor of making more templates typescript by default

**Comment by EvanBacon** [comment]
Closing in favor of our aggressive automatic TypeScript support.

**Comment by shamilovtim** [comment]
Thanks for responding either way!
