### ISSUE TITLE
Skipping Metro on prebuild with default config

### ISSUE THREAD

**Issue by prowe214** [expo/expo#20763]
### Summary

On a project with a `metro.config.js`, exporting just the default config with `getDefaultConfig(__dirname)` and running `npx expo prebuild` results in Metro getting skipped.

### SDK Version

47.0.0 (also appears on 46.0.0)

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.12
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.1.0
    Expo Workflow: bare
```

### Minimal reproducible example

1 - Set up `metro.config.js`
```js
const { getDefaultConfig } = require('@expo/metro-config');

module.exports = getDefaultConfig(__dirname);
```

This also occurs with the following import styles:

```js
const { getDefaultConfig } = require('expo/metro-config');
import { getDefaultConfig } from '@expo/metro-config';
import { getDefaultConfig } from 'expo/metro-config';
```

2 - Run `npx expo prebuild -p ios`, receive the following output:

```
npx expo prebuild -p ios
✔ Created native project | gitignore skipped
› Metro skipped: Project metro.config.js does not match prebuild template.
› Ensure the project uses @expo/metro-config.
  Learn more
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using Yarn
✔ Config synced
✔ Installed pods and initialized Xcode workspace.
```

**Comment by jerryjfwang** [comment]
Also getting this issue with the same dependency versions.

Did a little more digging, and it looks like any changes (even for only formatting) to the default metro config file generated by `npx expo customize metro.config.js`

```
// works fine
const { getDefaultConfig } = require('expo/metro-config');
module.exports = getDefaultConfig(__dirname);
```

```
// this file gets skipped even though the only changes are to formatting (single quotes -> double quotes)
const { getDefaultConfig } = require("expo/metro-config");
module.exports = getDefaultConfig(__dirname);
```

Is there any way to force expo to build with my custom metro.config.js?

Thanks!

**Comment by SohelIslamImran** [comment]
Same issue

**Comment by EvanBacon** [comment]
`Metro skipped: Project metro.config.js does not match prebuild template` is just a simple warning that indicates we couldn't safely overwrite the `metro.config.js` file. This is required for ensuring projects bundled with `npx react-native` (e.g. when compiling) use the same config as `npx expo`.

The only way to not get the warning is to match the exact template `metro.config.js`.

Only possible issue here would be if you don't use `expo/metro-config` as the base Metro config, this leads to really difficult debugging issues.

**Comment by EvanBacon** [comment]
@prowe214 Metro is always used for bundling unless configured otherwise. The `metro.config.js` file is the source of truth for all commands that perform bundling, it can't really be "skipped".

**Comment by prowe214** [comment]
@EvanBacon Awesome.  So just so that I'm Labatt Crystal clear, even with this warning, my `metro.config.js` above is always being used?

Thanks for being so responsive!

**Comment by EvanBacon** [comment]
@prowe214 yes it's always used with Expo tooling.

**Comment by haveamission** [comment]
@prowe214 Thanks for asking this question - I was banging my head trying to figure out why it was being skipped
