### ISSUE TITLE
[expo-three][Android][standalone] textures do not load on standalone android build

### ISSUE THREAD

**Issue by DominicBartel** [expo/expo#20779]
### Summary

Working on a project using expo-three and expo-gl. Textures load fine in dev, or when built on IOS, but not on android. To reproduce I pulled the testing module from the project and setup a test repo with a brand new installation of all packages.

[reproduceable test build](https://github.com/DominicBartel/buildTest)

I've attempted the workaround listed [here](https://github.com/expo/expo-three/issues/104#issuecomment-498989294) only to be met with `Error: Expected URL scheme 'http' or 'https' but was 'file'`

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~47.0.12 => 47.0.12
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

[reproduceable test build](https://github.com/DominicBartel/buildTest)

Running `eas build -p android --profile preview` will reproduce issue

**Comment by uakhundz** [comment]
I'm having the same exact issue. Was using expo 45 and upgraded to 47 but the issue still exists. Running eas update fixes the issue but still an issue for fresh installs, so it makes me think it has something to do with how assets are bundled by default.

**Comment by DominicBartel** [comment]
That solved it, thanks so much!

**Comment by uakhundz** [comment]
It's not a proper fix though, will still happen on a new install

**Comment by obasille** [comment]
> I'm having the same exact issue. Was using expo 45 and upgraded to 47 but the issue still exists. Running eas update fixes the issue but still an issue for fresh installs, so it makes me think it has something to do with how assets are bundled by default.

It's because when using EAS Updates images are not bundled but downloaded from the expo servers.

**Comment by zerogramsjm** [comment]
I finally got it working with this:

    const loadAndProcessAsset = async () => {
      try {
        // Get asset for the texture
        const asset = Asset.fromModule(require('../../../assets/XXXXX.png'));
        if (!asset.localUri) {
          // Download the asset if it doesn't have a local URI
          await asset.downloadAsync();
        }
        // Get the dimensions directly from the Asset object
        const { width, height } = asset;
        const localUri = `${FileSystem.cacheDirectory}copied_texture.png`;
        // Check if the file exists
        const fileInfo = await FileSystem.getInfoAsync(localUri);
        if (!fileInfo.exists) {
          // Copy the asset to the cache directory if the file doesn't exist
          await FileSystem.copyAsync({ from: asset.localUri, to: localUri });
        }
        // Create a new Asset using the file URI
        const copiedAsset = Asset.fromURI(`file://${localUri}`);
        copiedAsset.height = height;
        copiedAsset.width = width;
        copiedAsset.localUri = localUri;
        // Continue with loading or processing the asset
        const texture = await ExpoTHREE.loadAsync(copiedAsset);
        // Do something with the loaded texture
        const material = new THREE.MeshBasicMaterial({ map: texture });
        const geometry = new THREE.SphereGeometry(10, 32, 32);
        geometry.scale(-1, 1, 1);
        mesh = new THREE.Mesh(geometry, material);
        
        ------
        
        tested on google pixel 5 and Samsung galaxy s21
