### ISSUE TITLE
CommandError: Couldn't open Android app with activity "com.xx.xx://expo-development-client/?url=http%3A%2F%2F192.168.2.225%3A8081" on device "Pixel_4_API_33".

### ISSUE THREAD

**Issue by lindan4** [expo/expo#20775]
### Summary

After running the "npx expo prebuild" command after modifying app.json or app.config.ts in order to move the bare workflow. I expect that when I run "npx expo run:android", the application successfully launches on Android.

What actually happens instead is that while an application is installed, the application fails to start and I receive this error.

```
CommandError: Couldn't open Android app with activity "com.xx.xx://expo-development-client/?url=http%3A%2F%2F192.168.2.225%3A8081" on device "Pixel_4_API_33".
The app might not be installed, try installing it with: npx expo run:android -d Pixel_4_API_33
```

Even if I run the suggested command I receive the same error.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.2.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/lindanthillanayagam/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
        System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      expo: ~47.0.12 => 47.0.12 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.1.1
    Expo Workflow: bare

### Minimal reproducible example

1. Initialize an Expo project with version 47.
2. Modify the value of the runtimeVersion key in the created app.json, app.config.ts, or app.config.js file to be '1.0.0'.
3. Run 'npx expo prebuild'
4. After generating the native Android and native iOS directories (moving to the bare workflow), run 'npx expo:run android'

**Comment by jackchengck** [comment]
I have the same problem recently,
using the same expo 47.0.12 & react-native 0.70.5
and created a fresh expo

**Comment by Zeroya** [comment]
@lindan4 , hi, have the same problems, also installed expo 47.0.12 & react-native 0.70.5  , have you solve this problem ?

**Comment by AndyMeagher** [comment]
I am also seeing this. Completely unable to run using local expo. Please re-open this

**Comment by nadeemkhanvincente** [comment]
same error

**Comment by AndyMeagher** [comment]
@nadeemkhanvincente My issue ended up being related to having a `package` name using underscores. Once I removed the underscores, everything worked for me. 

Totally unhelpful error messages around this, but maybe this could help you out.

**Comment by nadeemkhanvincente** [comment]
@AndyMeagher i dont have such underscores

**Comment by Zeroya** [comment]
@AndyMeagher , I also had problem with naming in package because of underscores in previos , but about problem in this isue ,  i change version of Android 13 to Android 12 . @nadeemkhanvincente  , maybe your problem related to this

**Comment by nadeemkhanvincente** [comment]
> @AndyMeagher , I also had problem with naming in package because of underscores in previos , but about problem in this isue , i change version of Android 13 to Android 12 . @nadeemkhanvincente , maybe your problem related to this

ok thanks, let me try.

**Comment by bnonni** [comment]
FWIW I also ran into the issue recently, and I resolved it by changing my app's package name from `com.me.my_app` to `com.me.myapp`. The `expo run` command doesn't tell you this, but if you already have an `android/` folder in your expo app, and main activity folder is named with `_` in it (e.g. `/home/user/expo-app/android/app/src/main/java/com/me/my_app`) then it'll spit out an error telling you that you are not allowed to have a package with certain characters in it. In this case, that character is "_" underscore. By renaming my app in Firebase to `com.me.myapp` redownloading the google-services.json, deleting the build folders (`android/` and `ios/`) and rerunning prebuild, I'm successfully able to run `expo run:android`

**Comment by claudiojunior-me** [comment]
thanks @bnonni this works as well

**Comment by ArianHamdi** [comment]
> FWIW I also ran into the issue recently, and I resolved it by changing my app's package name from `com.me.my_app` to `com.me.myapp`. The `expo run` command doesn't tell you this, but if you already have an `android/` folder in your expo app, and main activity folder is named with `_` in it (e.g. `/home/user/expo-app/android/app/src/main/java/com/me/my_app`) then it'll spit out an error telling you that you are not allowed to have a package with certain characters in it. In this case, that character is "_" underscore. By renaming my app in Firebase to `com.me.myapp` redownloading the google-services.json, deleting the build folders (`android/` and `ios/`) and rerunning prebuild, I'm successfully able to run `expo run:android`

Oh man, you saved me 🙏
