### ISSUE TITLE
Expo build command not adding secret files during build

### ISSUE THREAD

**Issue by uchepercynnoch** [expo/expo#20782]
### Summary

We have a project already published to google playstore. Before now, after each update of the app using the expo build command, everything works fine i.e the google services json, uploaded to secrets, file is included and push notifications works just. But a week ago it stopped working and the project no longer receives push notifications. However, when I build the same project using eas build command, push notifications works just fine. I would love to use eas, but the app is already published on google playstore with a different certificate. How do I resolve this please?

### What platform(s) does this occur on?

Android

### SDK Version

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - /usr/local/opt/node@16/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - /usr/local/opt/node@16/bin/npm
      Watchman: 2022.12.26.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.2.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

command used to build the published app - `expo build:android --type app-bundle --release-channel permission-audit`

**Comment by EvanBacon** [comment]
Please read the documentation on [migrating from `expo build` to `eas build`](https://docs.expo.dev/build-reference/migrating/#understand-the-differences-between-classic-and-eas-builds). Use the forums and discord to request more info regarding the migration process.
