### ISSUE TITLE
expo-image: non squared images have a gray border on Chrome

### ISSUE THREAD

**Issue by Akronae** [expo/expo#20795]
### Summary

Transparent PNG and SVG are expected to be rendered as they are, without any border.

The image itself has no border, but when an expo-image component is created, it creates two HTML img components, one of which has no src, which makes Chrome outline it
![image](https://user-images.githubusercontent.com/17302866/211888319-d4804fbe-3610-4ba3-87ce-51536a4425d7.png)

If this component is removed, hidden, the image is displayed properly.

![image](https://user-images.githubusercontent.com/17302866/211888673-482dc53f-5064-4f6d-9c25-e784a23e6ba8.png)

### What platform(s) does this occur on?

Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.4 
      expo: ~46.0.13 => 46.0.19 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.2.0
      expo-cli: 6.1.0
    Expo Workflow: managed

### Minimal reproducible example

import { Image } from 'expo-image'

<Image source={require('image.svg')} />

**Comment by aleqsio** [comment]
Fixed, should go out with the next expo-image release :)
