### ISSUE TITLE
Android Standalone build assets

### ISSUE THREAD

**Issue by uakhundz** [expo/expo#20797]
### Summary

Building a standalone apk for Android cause some assets to be unavailable and crash the app when expo-three tries to load them in as assets. This is the sentry error seen:

ExpoTHREE.loaderClassForExtension(): Unrecognized file type assets_textures_background

The wierd part is it works perfectly after running eas update so somehow the files being changed (optimized?) fixes the issue.

Is there a way i can run eas update and use the results when building the standalone app? Otherwise every new install crashes until the update is applied one second or third launch of the app.

### What platform(s) does this occur on?

Android

### Environment

    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/mybracelet/node_modules/.bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.1.0
    Expo Workflow: managed

### Minimal reproducible example

Not applicable

**Comment by uakhundz** [comment]
https://github.com/expo/expo/issues/20779 this is another dev reporting the same thing (but closed the issue without the permanent fix). Linking here because it looks like they have a reproducible test build.

**Comment by obasille** [comment]
See also this expo-three issue https://github.com/expo/expo-three/issues/225
and this one too https://github.com/expo/expo-three/issues/54

I can provide a simple reproducible example if needed.

**Comment by obasille** [comment]
> @uakhundz does this workaround solve the issue? [expo/expo-three#104 (comment)](https://github.com/expo/expo-three/issues/104#issuecomment-498989294)

Thanks but unfortunately this workaround has stopped working as now `ExpoTHREE.loadAsync()` throws an error when loading a local file (like the one returned by `copyAssetToCacheAsync()` => "file:///data/user/0/......")

The error is:
> Expected URL scheme 'http' or 'https' but was 'file'
