### ISSUE TITLE
Facebook Android Invalid Key Hash

### ISSUE THREAD

**Issue by NorihitoN** [expo/expo#2079]
1. I created Facebook login for Android based on https://docs.expo.io/versions/latest/sdk/facebook

2. For development environment, I added rRW++LUjmZZ+58EbN5DVhGAnkX4= as an Android key hash and facebook login procedure worked on genymotion simulator on my laptop and my android phone by using expo app.

3. For standalone android app, I added another key hash in addition to the above the key hash in facebook developer setting. On https://developers.facebook.com/apps/xxxxxxx/ page,
I input "Facebook hash key" created by "exp fetch:android:hashes". App status was changed from "In development" to "Live".

4.  I installed standalone app in my android phone and tried to login with facebook, but the error happened. The error is the below.
"Invalid key hash. The key hash xxxxxxxxxxxxxxxx(a certain hash key)" does not match any stored key hashes at https://developers.facebook.com/apps/xxxxxxx/
This hash key in the error code was different from the key hash I added facebook developer setting.

Is this error from wrong key hash?
What key hash should I use to fix it?

**Comment by AdamJNavarro** [comment]
Hey @NorihitoN,

My initial suggestion would be create a new key hash and replace the old one in the Facebook Developer Portal and see if that remedies the issue. If not, there may be a deeper problem at play here.

Let me know if that fixes it.

Cheers,
Adam

**Comment by zerocowl** [comment]
Hi, the hash for the expo client is different than the standalone app.

Try this:
`keytool -list -printcert -jarfile YOUR_APK.apk | grep SHA1 | awk ‘{ print $2 }’ | xxd -r -p | openssl base64
`

**Comment by NorihitoN** [comment]
Hi, thank you for advice.
I followed your instruction but the situation was not changed.

Firstly, I did the below as @zerocowl advised.
- moved to the directory where apk file is saved.
- `keytool -list -printcert -jarfile MY_APK.apk | grep SHA1 | awk ‘{ print $2 }’ | xxd -r -p | openssl base64`
- However, nothing seemed to happened. Is it correct?

Secondly, I did the below as @AdamJNavarro advised.
- moved to the project directory.
- `keytool -exportcert -alias <RELEASE_KEY_ALIAS> -keystore <RELEASE_KEY_PATH> | openssl sha1 -binary | openssl base64` as shown in https://developers.facebook.com/docs/android/getting-started?locale=ja_JP#release-key-hash. To know <RELEASE_KEY_ALIAS> and <RELEASE_KEY_PATH>, I put `exp fetch:android:keystore` on the terminal. A new hash key was displayed.
- I re-created apk file, and uploaded it to google play console.
- I installed standalone app in my android phone and tried to login with facebook, but the error happened again. And The key hash shown in the error was the same it was in the first error, which means the key hash seemed not to change.

What is the cause?

Brs,
Norihito

**Comment by lauborges** [comment]
When I do "keytool -list -printcert -jarfile xxxx.apk" I get an error: 
`keytool error: java.lang.Exception: Only one command is allowed: both -list and -printcert were specified.`
Running the complete command output is empty

**Comment by mitchellbutler** [comment]
@NorihitoN, depending on your Play Store configuration you may need to run `keytool -list -printcert -jarfile MY_APK.apk | grep SHA1 | awk ‘{ print $2 }’ | xxd -r -p | openssl base64` _on the apk from the app store_ rather than the one you're uploading. You can navigate to the release on the [play developer console](https://play.google.com/apps/publish), click the "download" icon next to the apk and select the "Derived Apk". This apk could have a different hash than the one you're uploading.

<img width="1028" alt="screen shot 2018-10-25 at 11 33 58 am" src="https://user-images.githubusercontent.com/1069577/47512379-136ead00-d84a-11e8-825e-500d3c7abada.png">

**Comment by NayeliCarb** [comment]
Hello everyone, I think it's a bit late, but I found a solution that worked for me, I hope I can help, I leave the link and the screenshots, when copying the hash and paste it into the converter should remove the sha:

![image](https://user-images.githubusercontent.com/16783876/51159438-d7e2ee00-184e-11e9-9142-71aa28f75b9a.png)


![image](https://user-images.githubusercontent.com/16783876/51159354-6dca4900-184e-11e9-8bf8-996e2077966c.png)
![image](https://user-images.githubusercontent.com/16783876/51159364-74f15700-184e-11e9-9af1-b3ddb1f6cf8c.png)

https://stackoverflow.com/questions/23674131/android-facebook-integration-invalid-key-hash/44782435#44782435

greetings and good year

**Comment by hevelson** [comment]
I had a similar problem and the @NayeliCarb solution works for me

**Comment by gabycasper007** [comment]
It works, thank you so much @NayeliCarb

**Comment by cruzach** [comment]
Closing since this isn't a bug with Expo
