### ISSUE TITLE
DocumentPicker getDocumentAsync crashes the app when selecting non-existing file

### ISSUE THREAD

**Issue by Xyzor** [expo/expo#2080]
### Environment

Environment:
  OS: Linux 4.15
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

### Steps to Reproduce

1. Open snack
2. Start the app on an android device (preferable v5, on v8 the list updates automatically)
3. Select the Download section from the left drawer menu
4. Select a non-existing file
5. The app should crash

### Expected Behavior

To be able to handle this case, either by hand or by the api itself.

### Actual Behavior

The app crashes

### Reproducible Demo

[Snack demo](https://snack.expo.io/B1_6O6IS7)

**Comment by sjchmiela** [comment]
Hey, @Xyzor? Could you please try reproducing this issue on SDK 31? Maybe it has been fixed… Also, how do you select a non-existing file, if it doesn't exist? 😃

**Comment by Xyzor** [comment]
I don't know the exact reason, but I think the list is showing items from some kind of cache. So if I open the picker and delete a file, it won't disappear from the list if i open it again.

I'll definitely try out.

**Comment by EvanBacon** [comment]
Can confirm that this works in SDK 37 https://snack.expo.io/@bacon/expo-issue-2080

**Comment by diragb** [comment]
was this ever fixed?

**Comment by dommangetnicolas** [comment]
It worked for us with SDK38. Since we upgraded to SDK39 it doesn't work

**Comment by sjchmiela** [comment]
Yeah, sorry, that's a known issue! 😕 We've been working on resolving it, the fixes should land soon! 🙏
