### ISSUE TITLE
'Expo/Expo.h' file not found

### ISSUE THREAD

**Issue by alexander-toptal** [expo/expo#20807]
### Summary

In ejected expo app there is a bug with searching `Expo/Expo.h` from the Bridging-Header.h.

```
❌ (/Users/main/Projects/work/app/ios/App-Bridging-Header.h:5:9)

  3 | //
  4 |
> 5 | #import <Expo/Expo.h>
    |         ^ 'Expo/Expo.h' file not found
  6 |


❌  error: failed to emit precompiled header '/Users/main/Library/Developer/Xcode/DerivedData/JuggernautAI-avduajccznhbgzcjlaxibaywvnfj/Build/Intermediates.noindex/PrecompiledHeaders/JuggernautAI-Bridging-Header-swift_3Q5KDRZGHVAQI-clang_2RMK2Z2AEDA4X.pch' for bridging header /Users/main/Projects/work/pl-app/ios/JuggernautAI-Bridging-Header.h
```

### What platform(s) does this occur on?

iOS

### Environment

Macbook M1

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/main/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 31, 33
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.2
      expo: ~46.0.19 => 46.0.19
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.10
    npmGlobalPackages:
      expo-cli: 6.1.0
    Expo Workflow: bare

### Minimal reproducible example

**App-Bridging-Header.h:**

//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import <Expo/Expo.h>

**Comment by alexandreaugus** [comment]
+1

**Comment by alexander-toptal** [comment]
Problem was in podfile, had to remove this code:
```
target.build_configurations.each do |config|
    config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    config.build_settings['ENABLE_BITCODE'] = 'NO'
end
```
