### ISSUE TITLE
"Can't modify frozen String" on pod install

### ISSUE THREAD

**Issue by alexander-toptal** [expo/expo#20802]
### Summary

After project was upgraded with expo-cli to 47 pods can't be installed. The following error happens after calling (cd ios && pod install):

```
/Users/main/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String: "relative URI: /third-party-podspecs/DoubleConversion.podspec" (FrozenError)
```

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/main/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 31, 33
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2
      expo: 47.0.12 => 47.0.12
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    npmGlobalPackages:
      expo-cli: 6.1.0
    Expo Workflow: bare

### Minimal reproducible example

Call `yarn && (cd ios && pod install)` after upgrading ejected expo from 46 to 47 and cleaning repo folder with `git clean -dfx`.

**Comment by appden** [comment]
I ran into this a bit ago. Though I can't recall exactly what I did, I know I figured it out from this thread: https://developer.apple.com/forums/thread/652822
