### ISSUE TITLE
[Android] ExpoApplication has no getApplication method; nor a way to access application?

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#2082]
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.2.1
  Yarn: 1.5.1
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/headsuphealth-aab15b0b-9892-4029-bfa9-45b891461619.tar.gz

ExpoKit on Android

### Steps to Reproduce

1. `exp init`
2. `npm i -S react-native-keyboard-input`, set up per instructions ([repo here](https://github.com/JulianKingman/expo-error-repo))
3. Run on Android

### Expected Behavior

Runs properly

### Actual Behavior

I get an error which ends up being related to `this` in ExpoApplication not being the android application object which the above-mentioned plugin expects. Using `this.getApplication` is not a function, so I can't get it that way either...  

![screenshot_1533671183](https://user-images.githubusercontent.com/1566400/43801274-789009ae-9a47-11e8-801e-7815a19225fc.png)

### Reproducible Demo

Repo: https://github.com/JulianKingman/expo-error-repo

**Comment by JulianKingman** [comment]
Related issue: https://github.com/wix/react-native-keyboard-input/issues/24

Also note that using a fresh vanilla react native install with `this.getApplication()` works fine.

**Comment by JulianKingman** [comment]
I believe this is the root issue: https://github.com/expo/expo/issues/347

**Comment by FiberJW** [comment]
Due to a lack of activity, I’m closing this issue for now. See Bare Workflow for a cleaner way to use Expo in with custom native dependencies. If you have any further related problems, please open another issue. Thanks :)
