### ISSUE TITLE
QR code pointing to Prod instead of Dev build

### ISSUE THREAD

**Issue by ervibern** [expo/expo#20824]
### Summary

Hi! I have both Dev and Prod versions of my app installed on physical iPhone using this guide https://docs.expo.dev/build-reference/variants/. When I start server, the QR code points to Prod instead of Dev (I run this command APP_VARIANT=development npx expo start --dev-client). What could be the issue?

It says that Metro waiting on 
com.myapp.app://expo-development-client/?url=http%3A%2F%2F192.168.0.5%3A8081 
while I would expect 
com.myapp.app.dev://expo-development-client/?url=http%3A%2F%2F192.168.0.5%3A8081

Is there a config I am missing?``

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo": "~47.0.12",
"expo-dev-client": "~2.0.1",
"expo-updates": "~0.15.6",

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.9.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.1 - /opt/homebrew/bin/npm
      Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/ervibern/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.3.2
      expo-cli: 6.1.0
    Expo Workflow: bare

### Reproducible demo

1. set up app.config.json as shown here https://docs.expo.dev/build-reference/variants/

2. install multiple version of the app on the phone (e.g., dev, staging, prod)

3. run APP_VARIANT=development npx expo start --dev-client to start dev client

4. scan QR with camera -> doesn't points to dev app

**Comment by PradumanS** [comment]
It is clear from Metro waiting on url that the environment variable is not available so the app is running the default value provided ie. Prod,

I think the correct command would be - `export APP_VARIANT=development && npx expo start --dev-client`

I hope it helps!

**Comment by wchbrad** [comment]
>导出APP_VARIANT=development && npx expo start --dev-client
same issue and this solution can't work.That's so bad.

**Comment by jmatsushita** [comment]
Bumped into the same issue, I believe the solution is
```
npx expo start --dev-client --scheme com.myapp.app.dev
```
