### ISSUE TITLE
Swallow exception in Snapshot module

### ISSUE THREAD

**Issue by giautm** [expo/expo#2083]
I just got a lot of this exception report on Sentry, and I didn't know why. Please, throw the original exception.

![image](https://user-images.githubusercontent.com/12751435/43812363-2bdf2528-9aeb-11e8-80d0-890d3c2713f8.png)

https://github.com/expo/expo/blob/b0b64c79de302f316cc34d8d2692546591ee3221/android/expoview/src/main/java/abi28_0_0/host/exp/exponent/modules/api/RNViewShotModule.java#L76

**Comment by sjchmiela** [comment]
Hi @giautm! A fix for this behavior has just been merged into `master` and will be released in next SDK. I'll keep this issue open to keep track of this PR.

**Comment by sjchmiela** [comment]
The fix has been released in SDK31. 🙂
