### ISSUE TITLE
I,m trying to run expo app but throws an error in terminal, "System limit for number of file watchers reached"

### ISSUE THREAD

**Issue by thai-ru** [expo/expo#20842]
### Summary
I'm trying to run an expo app but keeps throwing an error, "System limit for number of file watchers reached, watch '/home/robinson/proj-one/node_modules/@expo/prebuild-config/node_modules/fs-extra/lib/json'"

### What platform(s) does this occur on?

Android

### SDK Version

47

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.12.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.2.0 - /usr/bin/npm
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.1.0
    Expo Workflow: managed

### Minimal reproducible example

node:internal/fs/watchers:252
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/robinson/proj-one/node_modules/@expo/prebuild-config/node_modules/fs-extra/lib/json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at NodeWatcher.watchdir (/home/robinson/proj-one/node_modules/metro-file-map/src/watchers/NodeWatcher.js:159:24)
    at Walker.<anonymous> (/home/robinson/proj-one/node_modules/metro-file-map/src/watchers/common.js:117:31)
    at Walker.emit (node:events:513:28)
    at /home/robinson/proj-one/node_modules/walker/lib/walker.js:69:16
    at FSReqCallback.oncomplete (node:fs:197:23) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/robinson/proj-one/node_modules/@expo/prebuild-config/node_modules/fs-extra/lib/json',
  filename: '/home/robinson/proj-one/node_modules/@expo/prebuild-config/node_modules/fs-extra/lib/json'
}

Node.js v18.12.1

**Comment by EvanBacon** [comment]
This looks like a Metro bundler issue, your computer may not be powerful enough to run Metro bundler. You can try `npx expo start --max-workers 0` to prevent workers from being used.
