### ISSUE TITLE
expo-updates - fresh update not applying/working

### ISSUE THREAD

**Issue by t3chbits** [expo/expo#20847]
### Summary

When running `eas update` my app detects there is a new version but upon fetching said update it is never applied to the app and is stuck in a loop. 

No 'catch' is triggered when fetching and applying the update so we are stuck on where to look for next. The app seems to get stuck in an update loop because the update is never applied. We have both a toast notification and a manual download update button to test with.

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
      Watchman: 2023.01.09.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/ash/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 29, 31, 33
        Build Tools: 30.0.3, 31.0.0
        System Images: android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      eas-cli: 3.3.2
      expo-cli: 6.1.0
    Expo Workflow: bare

### Minimal reproducible example

Step 1: Make an update to some text
Step 2: Update version & runtime values in app.config.js/app.json
Step 3: `npx expo prebuild && eas build --platform ios --profile production`
Step 4: Download compiled app
Step 5: Install on Simulator/Device
Step 6: View the updated text from the change made before the build
Step 7: Change some more text and add in a few more lines
Step 8: `eas update --branch production --message "Text Change Test"`
Step 9: Force close and reopen app, receive a toast there is a new update available. 
Step 10: Press on the Apply update button which triggers this:
```
  async function onFetchUpdateAsync() {
    try {
      const update = await Updates.checkForUpdateAsync();

      if (update.isAvailable) {
        await Updates.fetchUpdateAsync();
        await Updates.reloadAsync();
      }
      
    } catch (error) {
      alert(`Error fetching latest update: ${error}`);
    }
  }
```

Step 11: App refreshes, force close and reopen and the Apply Update button is still there. Rinse and repeat Step 9....

**Comment by mattmcguin** [comment]
Experiencing the same issue. Have you found a solution or workaround?

**Comment by lk11601** [comment]
Any update on this guys?

**Comment by mattmcguin** [comment]
> Any update on this guys?

@lk11601 My issue was I added a library that needed a new build in order to incorporate new native dependencies. When I rebuilt and released the app with the new dep everything worked as expected.

Other people also mentioned they saw the issue when using `Constants.manifest` from the `expo-constants` lib. Relevant Discord chat [here](https://discord.com/channels/695411232856997968/920032594232500225/1064511270797180958)

**Comment by douglowder** [comment]
You can also get visibility into why updates are not applied by pulling the device expo-updates logs:

https://docs.expo.dev/versions/v47.0.0/sdk/updates/#updatesreadlogentriesasyncmaxage

**Comment by JacobJaffe** [comment]
I'm facing this also, while attempting to migrate from classic `expo publish` to `eas update`, on Expo 48. 
The reproduction is the same -- `Updates.checkForUpdateAsync()` determines there is an update, but the app continues to run the old version after `Updates.fetchUpdateAsync()` and `Updates.reloadAsync()`

**Comment by JacobJaffe** [comment]
> Other people also mentioned they saw the issue when using `Constants.manifest` from the `expo-constants` lib. Relevant Discord chat [here](https://discord.com/channels/695411232856997968/920032594232500225/1064511270797180958)

After migrating all `Constants.manifest` to `Constants.expoConfig`, updates now work as expected for me. Bizarre.

**Comment by PiotrSzlagura** [comment]
@JacobJaffe Do you mean you had to migrate `Constants.manifest` occurrences inside you app's code?

**Comment by PiotrSzlagura** [comment]
This is super extra weird, making this change fixed OTA updates for me too...

**Comment by fakhruz3105** [comment]
> > Other people also mentioned they saw the issue when using `Constants.manifest` from the `expo-constants` lib. Relevant Discord chat [here](https://discord.com/channels/695411232856997968/920032594232500225/1064511270797180958)
> 
> After migrating all `Constants.manifest` to `Constants.expoConfig`, updates now work as expected for me. Bizarre.

This works for me, it fix expo OTA update and Constants.manifest null in development build

**Comment by watadarkstar** [comment]
> @JacobJaffe Do you mean you had to migrate `Constants.manifest` occurrences inside you app's code?

I just tried this and I'm looking into why this works.

**Comment by vlimag** [comment]
hm weird one. worked for me either. nice find
