### ISSUE TITLE
I use expo-auth-session to login for Twitter, But it was crashed when wake up Twitter App on Android 

### ISSUE THREAD

**Issue by cl510804194** [expo/expo#20843]
### Summary

I use expo-auth-session to login for Twitter, But it was crashed when wake up Twitter App on Android , But if I don't download Twitter App, it will login successed, But if I don't download Twitter App, it will login successed, I don't find any solution to solve it, Can anybody help me?,this is my Code 
`
 const useProxy = Platform.select({ web: false, default: true });
 ....
const discoveryDocument = {
    authorizationEndpoint: twitter.authorizationEndpoint,
    tokenEndpoint: twitter.tokenEndpoint,
    revocationEndpoint: twitter.revocationEndpoint,
  };

  const [tRequest, tResponse, tPromptAsync] = useAuthRequest(
    {
      clientId: twitter.clientId,
      responseType: ResponseType.Code,
      redirectUri: makeRedirectUri({ scheme: "board", useProxy }),
      usePKCE: true,
      scopes: [
        "tweet.read",
        "tweet.write",
        "users.read",
        "like.write",
        "follows.write",
        "list.read",
        "offline.access",
      ],
    },
    discoveryDocument
  );

`

### What platform(s) does this occur on?

Android

### Environment

on every androd equipment, when I login ,and Twiter App was Waked Up, then return `{type:dismiss}` ,  But if I don't download Twitter App, it will login successed

### Minimal reproducible example

just like this
https://user-images.githubusercontent.com/42998038/212637104-94df5ce7-213b-4462-91c6-02e1b0311f66.mp4

**Comment by eugened-ith** [comment]
Having exactly the same result of {"type": "dismiss"} if a twitter app is installed

**Comment by T-Damer** [comment]
Same for me
