### ISSUE TITLE
NSRangeException: expo-av crashes occasionally on iOS in standalone app

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#20855]
### Summary

I get more and more sentry logs that my iOS app crashes when using expo-av.

```
NSRangeException
Cannot remove an observer <EXAVPlayerData 0x2825becb0> for the key path "timedMetadata" from <AVPlayerItem 0x281cc6a90> because it is not registered as an observer.

+0x073964
-[EXAVPlayerData _removeObserversForPlayerItem:]
(EXAVPlayerData.m:601)
+0x073850
-[EXAVPlayerData _removeObserversForPlayerItems]
(EXAVPlayerData.m:582)
+0x07373c
-[EXAVPlayerData _removeObservers]
(EXAVPlayerData.m:565)
+0x0740cc
-[EXAVPlayerData _addObserversForNewPlayer]
(EXAVPlayerData.m:678)
+0x071c70
__41-[EXAVPlayerData _finishLoadingNewPlayer]_block_invoke_2
(EXAVPlayerData.m:181)
```

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.1.0
    Expo Workflow: bare (just my testing environment - in reality I'm on managed)

### Minimal reproducible example

Unfortunately, it is not reproducible for me. It occurs occasionally. It does not feel right to post this with a reproducible example but on the other hand the error log will help someone to track this down (or maybe just surround it with a try/catch block? tbh: I have no clue from iOS native files :-(. ).

**Comment by hirbod** [comment]
Having a look here it appears that expo-av is already trying to prevent the issue. It seems to be a race condition. https://github.com/expo/expo/blob/ce37494d9a9989299ad4cf0e5af01394146f6e96/packages/expo-av/ios/EXAV/EXAVPlayerData.m#L548-L560

I think we could fix that by using the following code:

```obj-c
- (void)_tryRemoveObserver:(NSObject *)object forKeyPath:(NSString *)path
{
  NSMutableSet<NSString *> *set = [_observers objectForKey:object];
  if (set) {
    if ([set containsObject:path]) {
      [set removeObject:path];
      if (!set.count) {
        [_observers removeObjectForKey:object];
      }
      if ([object.observers containsObject:self]) {
        [object removeObserver:self forKeyPath:path];
      }
    }
  }
}
```

It is worth noting that my Obj-c skills are limited, so this solution is untested, but it might help to prevent the crash. I'll have someone look at this and provide a PR

**Comment by hirbod** [comment]
We have this crash logs as well (7 in total), but I was not able to reproduce the crash so far.
Can you confirm in your crash logs, that this issue only happened on

iPhone 7 Plus, in version 15.7, 15.7.1 and 15.7.2 only?
In our crash reports, this is the only this device within this iOS version range.

**Comment by RRaideRR** [comment]
Hey @hirbod , 

Thanks a lot for your answer. I can confirm, that I have crashes in this version range only. However, I have some crashes with the iPhone 7 as well.

**Comment by hirbod** [comment]
Ok, I kinda feel like this is happening only on iOS 15.7.

**Comment by RRaideRR** [comment]
> Ok, I kinda feel like this is happening only on iOS 15.7.

it seems like it - yes! However, I don't know what to do with this information - I cant do anything on the native side :-/

**Comment by hirbod** [comment]
I am still digging. I thought I had a fix but it crashed, since addObserver and removeObserver are having a race condition, since they happen on different threads. I don't know if its worth to search a fix. We should just tell our users to upgrade to iOS 16 :D

**Comment by RRaideRR** [comment]
I think you cannot upgrade the iPhone 7 or the iPhone 7+ to iOS 16. So in this case its more: "tell our users to throw away their phone and get a new iPhone" ;)

**Comment by hirbod** [comment]
Oh that's actually a bummer. I'll try to see if I can find a fix for them. First of all I need to reproduce it.

**Comment by maxencehenneron** [comment]
I also have this crash from time to time on Sentry.
However I do not agree it's only happening on iOS 15. Here's a crash long from iOS 16.

![Screen Shot 2023-01-25 at 10 35 46 AM](https://user-images.githubusercontent.com/377682/214652518-5988195e-c7f0-4c30-9edc-8e6a7f25731e.png)

**Comment by maxencehenneron** [comment]
I also have this crash from time to time on Sentry.
However I do not agree it's only happening on iOS 15. Here's a crash log from iOS 16.

![Screen Shot 2023-01-25 at 10 39 33 AM](https://user-images.githubusercontent.com/377682/214653200-974cffa1-bf77-4cf8-84f8-b0d2b47ec32d.png)

**Comment by hirbod** [comment]
Hi @maxencehenneron, thanks for sharing. So it was just a coincidence. @barthap do you have any clue here?
What we could discover so far is that the `addObserver` and `removeObserver` funcs are being called on different threads. I think this is where the race condition might happen. @Pickleboyonline might also have an idea how to fix this.

**Comment by hirbod** [comment]
@brentvatne I understand that a repro is missing, but I couldn't, for my life, create a MRE to reproduce this. But our Sentry is full of this crash. I think this issue is still valid.

**Comment by brentvatne** [comment]
it isn't particularly actionable for us without a reproducible example, and i'm trying to keep noise down in issues by filtering down to actionable issues

**Comment by RRaideRR** [comment]
I understand that it's hard without a MRE - no question. I also spend hours to create one by myself but I couldn't come up with it. It occurs _occasionally_. However: as @hirbod points out correctly, we are also getting a lot of these issues in our Sentry logs. This error leads also to a crash in the application.

My thinking was that if one could have a look at the places in the code (see error message from the initial post), then maybe someone would see what a potential problem could be.

**Comment by IjzerenHein** [comment]
We are also experiencing this occasionally during our Detox tests. Nothing that is easily or consistently to reproduce though. We are not doing anything spectacular, other than displaying a video using the `<Video>` component. For what it looks like, it seems to happen on unmount.

```
The app has crashed, see the details below:
[stderr] 
[stderr] 
    Exception was thrown: 
[stderr] 
    NSRangeException
[stderr] 
    Cannot remove an observer <EXAVPlayerData 0x600000b4d1e0> for the key path "timedMetadata" from <AVPlayerItem 0x600003285830> because it is not registered as an observer.
[stderr] 
    (
[stderr] 
    	0   CoreFoundation                      0x0000000180437324 __exceptionPreprocess + 160
[stderr] 
    	1   libobjc.A.dylib                     0x0000000180051274 objc_exception_throw + 56
[stderr] 
    	2   Foundation                          0x0000000180b2f1e0 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 616
[stderr] 
    	3   Foundation                          0x0000000180b2f5bc -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 132
[stderr] 
    	4   UntireNXTtest                       0x0000000102e46acc -[EXAVPlayerData _tryRemoveObserver:forKeyPath:] + 144
[stderr] 
    	5   UntireNXTtest                       0x0000000102e46d40 -[EXAVPlayerData _removeObserversForPlayerItem:] + 176
[stderr] 
    	6   UntireNXTtest                       0x0000000102e46c2c -[EXAVPlayerData _removeObserversForPlayerItems] + 144
[stderr] 
    	7   UntireNXTtest                       0x0000000102e46b18 -[EXAVPlayerData _removeObservers] + 40
[stderr] 
    	8   UntireNXTtest                       0x0000000102e474a8 -[EXAVPlayerData _addObserversForNewPlayer] + 20
[stderr] 
    	9   UntireNXTtest                       0x0000000102e45004 __41-[EXAVPlayerData _finishLoadingNewPlayer]_block_invoke_2 + 388
[stderr] 
    	10  DetoxSync                           0x00000001060f0434 ____detox_sync_dispatch_wrapper_block_invoke + 44
[stderr] 
    	11  libdispatch.dylib                   0x0000000180132ee4 _dispatch_call_block_and_release + 24
[stderr] 
    	12  libdispatch.dylib                   0x0000000180134708 _dispatch_client_callout + 16
[stderr] 
    	13  libdispatch.dylib                   0x0000000180143fd8 _dispatch_main_queue_drain + 1220
[stderr] 
    	14  libdispatch.dylib                   0x0000000180143b04 _dispatch_main_queue_callback_4CF + 40
[stderr] 
    	15  CoreFoundation                      0x000000018039a784 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
[stderr] 
    	16  CoreFoundation                      0x0000000180394de4 __CFRunLoopRun + 1912
[stderr] 
    	17  CoreFoundation                      0x0000000180394254 CFRunLoopRunSpecific + 584
[stderr] 
    	18  GraphicsServices                    0x0000000188eb7c9c GSEventRunModal + 160
[stderr] 
    	19  UIKitCore                           0x0000000112126ff0 -[UIApplication _run] + 868
[stderr] 
    	20  DetoxSync                           0x00000001060f68dc __detox_sync_UIApplication_run + 376
[stderr] 
    	21  UIKitCore                           0x000000011212af3c UIApplicationMain + 124
[stderr] 
    	22  UntireNXTtest                       0x0000000102e1ded0 main + 80
[stderr] 
    	23  dyld                                0x0000000104515514 start_sim + 20
[stderr] 
    	24  ???                                 0x0000000104421f28 0x0 + 4366409512
[stderr] 
    	25  ???                                 0xc275800000000000 0x0 + -4434497520588029952
[stderr] 
    )
``` 

ExpoSDK: 48
expo-av: 13.2.1
Running on EAS build

**Comment by IjzerenHein** [comment]
Also note that the `timedMetaData` observer was introduced in PR #14134 not that long ago

**Comment by sedders123** [comment]
We've recently updated to Expo SDK 48 and expo-av 13.2.1 and are now seeing this error in our Sentry logs though we've not been able to reliably reproduce this. I think https://github.com/expo/expo/pull/22148 sounds like it could be related, not exactly the same error (key of "status" not "timedMetadata") but seems very similar

**Comment by IjzerenHein** [comment]
> Hi @maxencehenneron, thanks for sharing. So it was just a coincidence. @barthap do you have any clue here? What we could discover so far is that the `addObserver` and `removeObserver` funcs are being called on different threads. I think this is where the race condition might happen. @Pickleboyonline might also have an idea how to fix this.

Yeah that is definitely was is happening. The expo-av/EXAVPlayerData is not thread safe and not intended to be called from different threads, but some cleanup is definitely happening from another thread.

**Comment by odusseys** [comment]
Can confirm this is happening (iOS simulator, when)
- the file is large (and probably needs to buffer)
- setPositionAsync is called at that moment

**Comment by OwenMelbz** [comment]
Recon this will ever get resolved? We also experience it regularly in our Sentry logs still

**Comment by Lewitje** [comment]
Same error here when navigating to a new screen.
- Video playing
- Navigate to new screen
- Crash

Happens on physical iPhone 15

`Your app just crashed. See the error below.
NSRangeException: *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty array`

**Comment by toshiyuki-suzuki-yukashikado** [comment]
> Same error here when navigating to a new screen.
> 
> - Video playing
> - Navigate to new screen
> - Crash
>
> Happens on physical iPhone 15

I also encountered the same issue on the iPhone 15. 
The problem was resolved by hiding the Video component before transitioning the screen, as shown below.

``` typescript
    const [isVideoVisible, setIsVideoVisible] = useState(true)
    const onPressNextButton = () => {
      void videoRef.current?.stopAsync()
      setIsVideoVisible(false)
      goNextScreen()
    }

   return (<View>
       {isVideoVisible && (<Video ref={videoRef} {...props}  />)}
       <Button onPress={onPressNextButton} >next</Button>
    </View>)
```
