### ISSUE TITLE
sdk 29 exp detach missing a dependency expo-gl

### ISSUE THREAD

**Issue by audiolion** [expo/expo#2086]
### Environment

I had a project that was on exp SDK 28, upgraded to exp SDK 29, then I detached my app. When I ran `pod install` I got the following error:

![image](https://user-images.githubusercontent.com/2430381/43897546-62b04644-9baa-11e8-9993-c3cdc06ab35c.png)

I checked and `expo-gl` folder did not exist in my `node_modules`, all the other ones did. It seems like this one just got missed.

I did a `yarn add expo-gl` and ran `pod install` again and everything worked a-ok.

I realize I haven't followed the issue template or steps to reproduce, I think this is an easy enough thing to verify that expo-gl is a required dependency when detaching (I assume expokit's package.json requires it?).

Thanks!

**Comment by audiolion** [comment]
Ah gotcha! makes sense. I guess you could include a note about it or just add it as a dependency and make a note that you can remove the `EXGL` pod and `expo-gl` dependency if you arent going to use GLView.

If you just want to update docs and not include `expo-gl` dependency I can make a PR

**Comment by sjchmiela** [comment]
`expo` now [depends](https://github.com/expo/expo/blob/master/packages/expo/package.json#L96) on `expo-gl`, so this shouldn't happen anymore. 🙂

**Comment by audiolion** [comment]
so expo sdk 30 I should be able to remove the explicit dependency in my package.json, and just leave the Podfile as-is, for reference my Podfile:

```
pod 'EXGL-CPP',
    :path => "../node_modules/expo-gl-cpp/cpp",
    :inhibit_warnings => true
```
