### ISSUE TITLE
[docs] Docs for installing the latest version of Expo modules only apply to React Native 0.68.

### ISSUE THREAD

**Issue by henrymoulton** [expo/expo#20871]
### Summary

I'm working through reapplying the [Expo Modules manual installation](https://docs.expo.dev/bare/installing-expo-modules/#manual-installation) to a React Native 0.70 installation. I've run into some errors, and the docs say that they only support a 0.68 installation, so I'm filing an issue checking if they're out of date.

I went through upgrading 0.68 to 0.70 using the Upgrade Helper and similarly to others in this [thread](https://github.com/expo/expo/issues/14824#issuecomment-1264112464) undid some changes suggested by the React Native Upgrade Helper.

However I'm now reapplying the changes and getting the following Xcode build errors:

`RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];`
to
`RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];`

I get the error:
`Property 'reactDelegate' not found on object of type 'AppDelegate *'`

Same error for lines:

`UIView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"App" initialProperties:nil];`
`UIViewController *rootViewController = [self.reactDelegate createRootViewController];`

and for 

`[super application:application didFinishLaunchingWithOptions:launchOptions];`
the error is:
`No visible @interface for 'EXAppDelegateWrapper' declares the selector 'application:didFinishLaunchingWithOptions:'`

My AppDelegate is:

```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

#import <Expo/Expo.h>
#import <UserNotifications/UserNotifications.h>

// Note(Henry): Copied from: https://github.com/expo/expo/blob/8b825efa661758abc540de005612701c10ffaf8b/templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.h
@interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate, UNUserNotificationCenterDelegate>

@property (nonatomic, strong) UIWindow *window;

+(UIWindow*)keyWindow;

@end
```

Since I thought the docs might be out of date, I tried following the code in the [expo-template-bare-minimum](https://github.com/expo/expo/tree/8b825efa661758abc540de005612701c10ffaf8b/templates/expo-template-bare-minimum) folder for RN 0.70.x but that didn't help.

### Link to the related docs page

https://docs.expo.dev/bare/installing-expo-modules/#manual-installation

### Anything else?

You guys are awesome.

**Comment by henrymoulton** [comment]
Can see this is potentially related to https://github.com/expo/expo/issues/20850

**Comment by amandeepmittal** [comment]
Hey @henrymoulton, we recently updated the manual instructions for latest React Native version (0.71) which is compatible with the latest Expo SDK.

Sorry for the inconvenience caused and this issue went stale for previous versions. I'm going to close this now, but feel free to reach out if your problem is still not resolved.
