### ISSUE TITLE
A problem occurred evaluating project ':unimodules-core' (eas build:android )

### ISSUE THREAD

**Issue by motogod** [expo/expo#20880]
### Summary

Step1:  create the new project
`npx create-expo-app testeas2`

Step2: test the build is working
`eas build:android`

Step3: install package
`yarn add @unimodules/core@7.2.0`

Step4: build the project shows error.  **Plugin with id 'maven' not found**
`eas build:android`

Step5: change the package build.gradle code then build the project still get the same error
`eas build:android`

**eas build:android on Expo log shows the error:**

<img width="833" alt="截圖 2023-01-19 下午12 18 07" src="https://user-images.githubusercontent.com/17781603/213355828-cc8e3ec3-f959-46be-a9cd-4021d64e888c.png">

In Step 4, I take a reference from https://github.com/expo/expo/issues/12774#issuecomment-928860487
and adjust the code then eas build:android get the same error

**node_modules/@unimodules/core/android/build.gradle**

```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
// apply plugin: 'maven'
apply plugin: 'maven-publish'

group = 'org.unimodules'
version = '7.2.0'

buildscript {
  // Simple helper that allows the root project to override versions declared by this library.
  ext.safeExtGet = { prop, fallback ->
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
  }

  repositories {
    mavenCentral()
  }

  dependencies {
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${safeExtGet('kotlinVersion', '1.4.21')}")
  }
}

//Upload android library to maven with javadoc and android sources
// configurations {
//   deployerJars
// }

//Creating sources with comments
task androidSourcesJar(type: Jar) {
  // classifier = 'sources'
  archiveClassifier = 'sources'
  from android.sourceSets.main.java.srcDirs
}

//Put the androidSources and javadoc to the artifacts
// artifacts {
//   archives androidSourcesJar
// }

// uploadArchives {
//   repositories {
//     mavenDeployer {
//       configuration = configurations.deployerJars
//       repository(url: mavenLocal().url)
//     }
//   }
// }
publishing {
  publications {
    maven(MavenPublication) {
      artifact androidSourcesJar
    }
  }
}

android {
  compileSdkVersion safeExtGet("compileSdkVersion", 30)

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 21)
    targetSdkVersion safeExtGet("targetSdkVersion", 30)
    consumerProguardFiles 'proguard-rules.pro'
    versionCode 20
    versionName "7.2.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${safeExtGet('kotlinVersion', '1.4.21')}"
  api project(":expo-modules-core")
}
```

Sometimes I get the maven issue on eas build, I can try to install the latest package to fix it, like `"expo-permissions": "^14.0.0", "expo-screen-orientation": "^5.0.1",`, it depends on Expo logs told you what package has maven issue, but `"@unimodules/core": "7.2.0"`, won' work even I change the code from node_modules

### What platform(s) does this occur on?

Android

### SDK Version

47

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.3.2
      expo-cli: 6.1.0
    Expo Workflow: bare
```

### Minimal reproducible example

Github repo:
https://github.com/motogod/testeas2

Step1:  create the new project (Expo SDK 47)
`npx create-expo-app testeas2`

Step2: install package
`yarn add @unimodules/core@7.2.0`

Step3: build the project shows error.  **Plugin with id 'maven' not found**
`eas build:android`

Step4: change the package build.gradle code then build the project still get the same error
`eas build:android`

**node_modules/@unimodules/core/android/build.gradle**

```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
// apply plugin: 'maven'
apply plugin: 'maven-publish'

group = 'org.unimodules'
version = '7.2.0'

buildscript {
  // Simple helper that allows the root project to override versions declared by this library.
  ext.safeExtGet = { prop, fallback ->
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
  }

  repositories {
    mavenCentral()
  }

  dependencies {
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${safeExtGet('kotlinVersion', '1.4.21')}")
  }
}

//Upload android library to maven with javadoc and android sources
// configurations {
//   deployerJars
// }

//Creating sources with comments
task androidSourcesJar(type: Jar) {
  // classifier = 'sources'
  archiveClassifier = 'sources'
  from android.sourceSets.main.java.srcDirs
}

//Put the androidSources and javadoc to the artifacts
// artifacts {
//   archives androidSourcesJar
// }

// uploadArchives {
//   repositories {
//     mavenDeployer {
//       configuration = configurations.deployerJars
//       repository(url: mavenLocal().url)
//     }
//   }
// }
publishing {
  publications {
    maven(MavenPublication) {
      artifact androidSourcesJar
    }
  }
}

android {
  compileSdkVersion safeExtGet("compileSdkVersion", 30)

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 21)
    targetSdkVersion safeExtGet("targetSdkVersion", 30)
    consumerProguardFiles 'proguard-rules.pro'
    versionCode 20
    versionName "7.2.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${safeExtGet('kotlinVersion', '1.4.21')}"
  api project(":expo-modules-core")
}
```

Step5: build the project still shows the same error on Expo log message.  **Plugin with id 'maven' not found**
`eas build:android`

**Comment by mingdevup** [comment]
same here

**Comment by Manirajss** [comment]
Me too getting the same error

**Comment by Simek** [comment]
Hello @motogod, can you explain why you are installing the `@unimodules/core` package manually? It has been deprecated a while ago in favour of build in packages in main `expo`:
* https://www.npmjs.com/package/@unimodules/core
* https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc

**Comment by Manirajss** [comment]
For me issue resolved after removing the option dependency from package-lock.json @unimodules/core

**Comment by motogod** [comment]
> Hello @motogod, can you explain why you are installing the `@unimodules/core` package manually? It has been deprecated a while ago in favour of build in packages in main `expo`:
> 
> * https://www.npmjs.com/package/@unimodules/core
> * https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc

Because I use `react-native-version-check-expo` to check my app version on iOS store.

If I don't use `@unimodules/core`, my project will show the library doesn't exist error, so I have to install it.

**Comment by motogod** [comment]
> For me issue resolved after removing the option dependency from package-lock.json @unimodules/core

I try to delete `package-lock.json` then eas build, it's not working for me.

**Comment by amerikan** [comment]
What metro version are you (`metro-config` `@expo/metro-config`)? I had similar issue but after upgrading them to latest it worked for me, though not sure if that will work for you too.

**Comment by motogod** [comment]
> What metro version are you (`metro-config` `@expo/metro-config`)? I had similar issue but after upgrading them to latest it worked for me, though not sure if that will work for you too.

@amerikan 
Thanks for your reply.
I am not sure the version because I don't install it. I try to install it ("@expo/metro-config": "^0.5.2",) then get the same error.

**Comment by Simek** [comment]
> Because I use react-native-version-check-expo to check my app version on iOS store.

Thank you for the explanation. I believe that the root of the problem is `react-native-version-check-expo` package, which use pinned, and very old versions of `expo-constants` and `expo-localization` packages (still relaying on Unimodules):
* https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check-expo/package.json#L26-L34

So unfortunately, currently you cannot use this package with newer Expo SDKs.

**Comment by motogod** [comment]
> > Because I use react-native-version-check-expo to check my app version on iOS store.
> 
> Thank you for the explanation. I believe that the root of the problem is `react-native-version-check-expo` package, which use pinned, and very old versions of `expo-constants` and `expo-localization` packages (still relaying on Unimodules):
> 
> * https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check-expo/package.json#L26-L34
> 
> So unfortunately, currently you cannot use this package with newer Expo SDKs.

Thanks for your reply, I got it.

**Comment by thanhdat2106** [comment]
@motogod Hi, I also got the same error but haven't found a solution yet. Have you solved this error yet?

**Comment by Morton4idps** [comment]
> @motogod Hi, I also got the same error but haven't found a solution yet. Have you solved this error yet?

No, I have to give to use `react-native-version-check-expo` and `@unimodules/core`

**Comment by miradario** [comment]
change the build_gradle with this: 
//Creating sources with comments
task androidSourcesJar(type: Jar) {
//  classifier = 'sources'
archiveClassifier = 'sources'
  from android.sourceSets.main.java.srcDirs
}

//Put the androidSources and javadoc to the artifacts
/* artifacts {
  archives androidSourcesJar
} */

/* uploadArchives {
  repositories {
    mavenDeployer {
      configuration = configurations.deployerJars
      repository(url: mavenLocal().url)
    }
  }
} */

publishing {
  publications {
    maven(MavenPublication) {
     artifact androidSourcesJar
    }
  }
}
