### ISSUE TITLE
[expo-three] Fails to load texture from static ressource for Android standalone

### ISSUE THREAD

**Issue by obasille** [expo/expo#20882]
### Summary

`ExpoTHREE.loadAsync()` fails for Android standalone builds (APK file).

What happens:
The localUri returned of the assert returned by `Asset.fromModule(require('./assets/icon.png'))` will be just "assets_icon" because it's bundled as a drawable asset by React Native.

But the ExpoTHREE texture loader doesn't support this type of URI.

People have come up with various workarounds like changing the texture extension to something else so the file is not bundled as a "drawable", or copying the image file to the cache directory at runtime.

This issue will happen to anyone trying to load a texture with "expo-three" on a Android production app. Would it be possible to address it?

I've found several GitHub issues discussing this problem:
https://github.com/expo/expo/issues/2693
https://github.com/expo/expo/issues/20779
https://github.com/expo/expo-three/issues/54
https://github.com/expo/expo-three/issues/104
https://github.com/expo/expo-three/issues/185
https://github.com/expo/expo-three/issues/225

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    Expo Workflow: managed

### Minimal reproducible example

To reproduce this issue, one must do run a build on Android (no ExpoGo or snack).

```sh
npx create-expo-app expo-three-ts --template expo-template-blank-typescript
npm i three@0.145 expo-three expo-gl
npm i -D @types/three
npx expo install expo-asset expo-file-system
```

Modify App.ts likewise to display information about what's happening when attempting to load the texture:
```typescript
import { Asset } from 'expo-asset';
import { Text, View } from 'react-native';
import * as React from 'react';
import { GLView } from 'expo-gl';
import * as ExpoTHREE from 'expo-three';

export default function App() {
  const [asset, setAsset] = React.useState<Asset>();
  const [message, setMessage] = React.useState("");
  return (
    <View style={{ flex: 1 }}>
      <Text>Asset:</Text>
      <Text>{JSON.stringify(asset)}</Text>
      <Text>Load result:</Text>
      <Text>{message}</Text>
      <GLView
        style={{ flex: 1 }}
        onContextCreate={(gl) => {
          // Create a WebGLRenderer without a DOM element
          const renderer = new ExpoTHREE.Renderer({ gl });
          renderer.setSize(gl.drawingBufferWidth, gl.drawingBufferHeight);

          // A THREE.Texture from a static resource
          const module = require('./assets/icon.png');
          ExpoTHREE.loadAsync(module);
            .then((texture) => setMessage(JSON.stringify(texture)))
            .catch((err) => setMessage("Error: " + err.message));
          
          // For the purpose of this example, keep the asset to display its contents
          setAsset(Asset.fromModule(module));
        }}
      />
    </View>
  );
}
```

The texture is properly loaded when running in ExpoGO but fails when building an APK with EAS.

The error is:
> ExpoTHREE.loaderClassForExtension(): Unrecognized file type assets_icon

```sh
eas build:configure
eas build --platform android --profile preview
```

**Comment by obasille** [comment]
Note:
Using `ExpoTHREE.loadTextureAsync()` directly doesn't throw an error, a texture object is created but it has no data when the code is run from an APK (it's rendered black).

```
const module = require('./assets/icon.png');
const asset = Asset.fromModule(module);
ExpoTHREE.loadTextureAsync({ asset });
```

**Comment by NikitaDudin** [comment]
Temp [solution](https://github.com/NikitaDudin/expo-exotic-asset#readme)

**Comment by obasille** [comment]
Thanks! It's based on the "rename your files to some other extension so they are not bundled as drawable" workaround.

I personally prefer the other work around that I mentioned, which is copying the file to the cache folder at runtime:
```
import { Asset } from "expo-asset";
import * as FileSystem from "expo-file-system";
import * as ExpoTHREE from "expo-three";

// Get asset for the texture
const asset = Asset.fromModule(require("texture.png"));
if (!asset.localUri) {
  await asset.downloadAsync();
}

// Copy to cache
const localUri = `${FileSystem.cacheDirectory}copied_texture.png}`;
await FileSystem.copyAsync({
        from: asset.localUri,
        to: localUri,
      });

// Load the copied asset
const copiedAsset = Asset.fromURI(localUri);
copiedAsset.localUri = localUri; // Need to set the localUri for loadAsync() to work
const texture = ExpoTHREE.loadAsync(copiedAsset);
```

**Comment by uakhundz** [comment]
I haven't been able to get either solution working on both android and ios (are you guys doing this only for Android, and the usual way for iOS?)

**Comment by uakhundz** [comment]
```
const expoAsset = await resolveExoticAsync(this.textures[key])
const expoTexture = await ExpoTHREE.loadAsync({asset: expoAsset});
```

tried this but loading the file gives me an error about `TypeError: Cannot read property 'elements' of undefined, js engine: hermes`

**Comment by obasille** [comment]
@uakhundz as described in the title and description, the issue discussed here happens only on Android standalone (.apk files). This is related to how images are packaged on Android APKs.

**Comment by uakhundz** [comment]
Oh trust me, I know, I've been struggling with the issue for so long hahah

I finally found out the problem I was having with the fix above. Width and height were not being set on the copied asset so nothing was displaying properly.

This did the trick:

```
copiedAsset.height = localUri; 
copiedAsset.width = localUri; 

```

**Comment by obasille** [comment]
Please have a look at this issue thank you!

**Comment by obasille** [comment]
Please don't close this issue, it makes quite difficult to load textures on Android production builds. Thank you.

**Comment by zerogramsjm** [comment]
Hey everyone, 

This is continuing to be a prominent problem. This is how far I've got:

import { Asset } from "expo-asset";
import { TextureLoader } from "expo-three";
import { Platform } from "react-native";
import { THREE } from "expo-three";

export async function loadTexture(id) {
  const textureLoader = new TextureLoader();
  const asset = Asset.fromModule(id);

  if (Platform.OS === 'android' && asset.localUri && !asset.localUri.includes('file://')) {
    // For Android release build, convert the localUri to file:// format
    const localUri = `file://${asset.localUri}`;
    return await textureLoader.loadAsync(localUri);
  } else {
    // For iOS and Android development build
    return await textureLoader.loadAsync(asset.uri);
  }
}

// Example usage in your component
const texture = await loadTexture(require('../../../assets/XXXXX.png'));
const material = new THREE.MeshBasicMaterial({ map: texture });
const mesh = new THREE.Mesh(geometry, material);

--------

This modification checks if asset.localUri exists before trying to access it. Also, the loadAsync method is used for asynchronous loading of the texture. The above solution seems to work on my google Pixel 5. But not my Samsung Galaxy. Super strange. 

To summarise the problem after digging around explanations from much more clever people than me:

building an app using expo. im using expo-three for a threejs scene. im trying to load a png as a texture to use as a material on a mesh. in development the texture loads fine but android specifically has an issue with how the image files are loaded in. 

      const textureLoader = new ExpoTHREE.TextureLoader();
      const texture = textureLoader.load(require('../../../assets/ifse/bridge.png'));
      const material = new THREE.MeshBasicMaterial({ map: texture });

      const mesh = new THREE.Mesh(geometry, material);
      if(ios){mesh.rotation.y -= 1.6;}else{mesh.rotation.y -= 1.6;}
      scene.add(mesh);

the require('path') generates a native asset on Android release build, so the uri and localUri from Asset are both schema-less, and points to the asset ID.

I can't find how to get expo-gl to load an asset, I require how to convert an asset to a file:// uri  to load the image and texture the mesh with it

To be clear I've also tried (rigorously) to convert the downloaded image to base64, I got the system to convert and read the base64 but it still wouldn't skin the expo-three texture in live.

Please let me know if anyone has had any progress!

**Comment by zerogramsjm** [comment]
I finally got it working with this:

const loadAndProcessAsset = async () => {
  try {
    // Get asset for the texture
    const asset = Asset.fromModule(require('../../../assets/XXXXX.png'));
    if (!asset.localUri) {
      // Download the asset if it doesn't have a local URI
      await asset.downloadAsync();
    }
    // Get the dimensions directly from the Asset object
    const { width, height } = asset;
    const localUri = `${FileSystem.cacheDirectory}copied_texture.png`;
    // Check if the file exists
    const fileInfo = await FileSystem.getInfoAsync(localUri);
    if (!fileInfo.exists) {
      // Copy the asset to the cache directory if the file doesn't exist
      await FileSystem.copyAsync({ from: asset.localUri, to: localUri });
    }
    // Create a new Asset using the file URI
    const copiedAsset = Asset.fromURI(`file://${localUri}`);
    copiedAsset.height = height;
    copiedAsset.width = width;
    copiedAsset.localUri = localUri;
    // Continue with loading or processing the asset
    const texture = await ExpoTHREE.loadAsync(copiedAsset);
    // Do something with the loaded texture
    const material = new THREE.MeshBasicMaterial({ map: texture });
    const geometry = new THREE.SphereGeometry(10, 32, 32);
    geometry.scale(-1, 1, 1);
    mesh = new THREE.Mesh(geometry, material);
    
    ------
    
    tested on google pixel 5 and Samsung galaxy s21

**Comment by justindanielclark** [comment]
> I finally got it working with this:
> 
> const loadAndProcessAsset = async () => { try { // Get asset for the texture const asset = Asset.fromModule(require('../../../assets/XXXXX.png')); if (!asset.localUri) { // Download the asset if it doesn't have a local URI await asset.downloadAsync(); } // Get the dimensions directly from the Asset object const { width, height } = asset; const localUri = `${FileSystem.cacheDirectory}copied_texture.png`; // Check if the file exists const fileInfo = await FileSystem.getInfoAsync(localUri); if (!fileInfo.exists) { // Copy the asset to the cache directory if the file doesn't exist await FileSystem.copyAsync({ from: asset.localUri, to: localUri }); } // Create a new Asset using the file URI const copiedAsset = Asset.fromURI(`file://${localUri}`); copiedAsset.height = height; copiedAsset.width = width; copiedAsset.localUri = localUri; // Continue with loading or processing the asset const texture = await ExpoTHREE.loadAsync(copiedAsset); // Do something with the loaded texture const material = new THREE.MeshBasicMaterial({ map: texture }); const geometry = new THREE.SphereGeometry(10, 32, 32); geometry.scale(-1, 1, 1); mesh = new THREE.Mesh(geometry, material);
> 
> ```
> ------
> 
> tested on google pixel 5 and Samsung galaxy s21
> ```

I used the same 'trick' today to create a copied asset for supply to OpenGL directly using the Expo GlView and it worked flawlessly for an Android Build. I am not using Three or any other rendering api but am directly providing shader/render code directly to the view.

Really really thankful you posted this code, as it saved me countless hours of hair pulling.
