### ISSUE TITLE
npx create-expo-app cousing error (Solved)

### ISSUE THREAD

**Issue by MayconParanhos** [expo/expo#20881]
### Summary

When I run the comand npx create-expo-app, the following error occurs:

✖ Something went wrong in downloading and extracting the project files: Could not find npm package "expo-template-blank@latest"
Error cloning template: Error: Could not find npm package "expo-template-blank@latest"

I cannot realize why this error occurs since I've built expo app in the same environment.

Ubuntu 22.04

### SDK Version

Latest

### Environment

System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash

### Minimal reproducible example

npx create-expo-app my-app --template

**Comment by MayconParanhos** [comment]
Hey community, I have solved the problem.

I ran the following terminal commands:

1 - sudo apt purge nodejs
2 - sudo apt autoremove
3 - sudo apt clean
4 - cd ~ 
5 - curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh
6 - nano /tmp/nodesource_setup.sh    (Just to see what was in the .sh file)
7 - sudo bash /tmp/nodesource_setup.sh  (this run the nodesource .sh file)
8 - sudo dpkg --configure -a
9 - sudo apt install -f nodejs

**Comment by Simek** [comment]
Glad to see you have solved the issue! 🎉 

For the context, this error comes from npm and we cannot control it or change the wording, and it has its roots in the user local setup, so there is no actionable thing we can from our side.

**Comment by lucy2329** [comment]
Any solution for windows?

**Comment by Alireza17224** [comment]
Any solution for macos ?

**Comment by yatrix7** [comment]
> Any solution for macos ?

It's not a fix, but I was able to create the directory, `my-app`, go into that directory and then run `npx create-expo-app -t and it worked. ` It was the only way I could move forward. Uninstalling node, rebooting -- nothing worked. It creates a nested folder, though (my-app/my-app), so you'll have to clean that up. Otherwise, looks gtg.

**Comment by men3malgmatti** [comment]
for me with Ubuntu 22.04.1, installing node v20.6.1 from snapcraft solved it

**Comment by aadil42** [comment]
@men3malgmatti, How did you install 20.6.1? when I update it it gives me 18 version everytime

**Comment by men3malgmatti** [comment]
@aadil42  try this : `sudo snap install node --channel=20/stable --classic`

**Comment by aadil42** [comment]
Did you install expo-cli or just expo?

**Comment by aadil42** [comment]
I'm getting confuse. Here https://docs.expo.dev/tutorial/create-your-first-app/#prerequisites it says you should have expo installed. But all the other docs says expo-cli.

**Comment by aadil42** [comment]
@men3malgmatti, please help brother. It's driving me crazy

**Comment by aadil42** [comment]
Thanks bro. It worked with node v20

**Comment by blackranja** [comment]
This worked for me:: npx create-expo-app@latest -e with-router my-app

**Comment by sergioabarbosa** [comment]
Thank you, it helped a lot!

**Comment by emrebaranarca** [comment]
> npx create-expo-app@latest -e with-router my-app

thanks

**Comment by praneeth-ayla** [comment]
> npx create-expo-app@latest -e with-router my-app

thanks, works for me

**Comment by Khun111** [comment]
> > Any solution for macos ?
> 
> It's not a fix, but I was able to create the directory, `my-app`, go into that directory and then run `npx create-expo-app -t `and it worked. It was the only way I could move forward. Uninstalling node, rebooting -- nothing worked. It creates a nested folder though (my-app/my-app), so you'll have to clean that up. Otherwise, looks gtg.

Doesn't work for me

**Comment by aadil42** [comment]
@Khun111 install node v20.

**Comment by myleftshoe** [comment]
> This worked for me:: npx create-expo-app@latest -e with-router my-app

This worked for me too but I don't know what it does yet. I am an expo newbie and this experience sux - makes you want to give up before you even start. Please fix. Pretty pleeeease.

**Comment by willianambrosio** [comment]
Thanks bro @MayconParanhos!!!!

**Comment by Khun111** [comment]
It installed but I couldn't start the app. npm run android gives sdk errors. Npm run web starts at first but complains about a deprecated package when I try to connect expo go. Too bad

**Comment by Dimakzela** [comment]
This worked for me:

`npx create-expo-app --template`

Then select template...
