### ISSUE TITLE
Random.getRandomBytes isn't available after installing expo-random

### ISSUE THREAD

**Issue by liebharc** [expo/expo#20906]
### Summary

After the installation of `expo-random`, `NativeModule.Random` is still null. I would expect the module to be available after it has been installed.

Background: `aws-amplify` tries to resolve `ExpoRandom` in https://github.com/aws-amplify/amplify-js/blob/8411513f63ab884bcfb8534aeda82b31fb579d15/packages/amazon-cognito-identity-js/src/utils/getRandomBase64.native.js and fails with an error if it can't find it. `amazon-cognito-identity-js` can be linked as an alternative to `expo-random`, however if possible I'd rely on expo dependencies as much as possible.

Alternative steps I tried:

- Read through https://github.com/expo/expo/issues/19167, https://github.com/expo/expo/issues/18819, https://github.com/expo/expo/issues/17682, https://github.com/expo/expo/issues/16719
- Using `npx expo prebuild` to test with a prebuild version
- Switching to `expo-crypto` as mentioned in the deprecated section of https://github.com/expo/expo/tree/main/packages/expo-random

Small disclaimer: I'm new to the expo world, hopefully I haven't missed something completely obvious

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

```
    "expo": "~47.0.12",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "expo-random": "~13.0.0",
    "expo-splash-screen": "~0.17.5"
```
I've tried installing expo-dev-client and expo-updates, but it didn't have an effect. I decided to submit this version as it really is a minimal reproducible which builds directly on top of create-expo-app.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/liebharc/expo-template which was created with:

1. `npx create-expo-app expo-template`
2. `npx expo install expo-random`
3. Add code to App.js which checks if `ExpoRandom` is available

Afterwards run: `npx expo android:run` and you get the following output:
![output](https://user-images.githubusercontent.com/544520/213860126-b529f190-2cf9-482c-a757-e6f4a3e98094.png)

**Comment by brentvatne** [comment]
expo modules are exposed through a different api than the `NativeModules.X` API: https://github.com/expo/expo/blob/e895b3ccee919eb45cc90c09f4de56e3ce5fa5ba/packages/expo-modules-core/src/requireNativeModule.ts#L35-L45

you will notice that this works as expected:

```js
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import * as Random from 'expo-random';

const bytes = Random.getRandomBytes(16);

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Text>{JSON.stringify(bytes)}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
