### ISSUE TITLE
SQLite unable to use NULL params in queries on Android

### ISSUE THREAD

**Issue by iffy** [expo/expo#2090]
I'm trying to run the following query in my program:

```javascript
const my_group_id = has_group_id ? group_id : null;
tx.executeSql(
    `SELECT max(ranking) as highrank FROM item
      WHERE coalesce(group_id, -1) = coalesce(?, -1)`,
[my_group_id], ..., ...);
```

It succeeds on iOS but fails on Android with this error:

```
Error: the bind value at index 1 is null
```

Here's a snack that succeeds on iOS and fails on Android: https://snack.expo.io/ryEbS49Bm

I don't know what code to fix though.  Is this an Expo problem, a RN problem or an Android problem?

- expo's [SQLiteModule.java](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi28_0_0/host/exp/exponent/modules/api/SQLiteModule.java#L132) uses Android's `rawQuery`
- [Android's `rawQuery`](https://github.com/aosp-mirror/platform_frameworks_base/blob/4b1a8f46d6ec55796bf77fd8921a5a242a219278/core/java/android/database/sqlite/SQLiteDatabase.java#L1256) expects bind params to be a String array
- I'm assuming that it eventually ends up at [Android's `bindString` function](https://github.com/aosp-mirror/platform_frameworks_base/blob/4b1a8f46d6ec55796bf77fd8921a5a242a219278/core/java/android/database/sqlite/SQLiteProgram.java#L162) because grepping for the error string led me there.

I'm not sure why `bindString()` throws on nulls.  There's a `bindNull()` right above it that does what `bindString()` would do if the error-throwing code weren't there (which makes me think everything would work fine if the null check were removed).

Is the fix to patch Android's code?  Or is the patch to change expo's SQLiteModule.java to bind parameters itself (using something other than `rawQuery`)?

### Environment

iOS, Android

**Comment by Szymon20000** [comment]
@iffy I don't see an easy and safe way to implement null binding on Android. I also think people would rarely use this feature. We should't use null with '=' operator anyway([why](https://www.tutlane.com/tutorial/sqlite/sqlite-null-is-null-values)). I checked your pull-request but I'm unable to make it work. SQLiteQuery doesn't have public constructor. SQliteDirectCursorDriver cannot be found and setting editTable to null does't look good.

**Comment by iffy** [comment]
@Szymon20000 No worries; I'm not using expo anymore (because of this and other issues).  If this is not worth fixing, then feel free to close.  Though I think it *is* worth fixing because it demonstrates a difference between iOS and Android and because binding NULL values is a feature of SQLite.

**Comment by Manubi** [comment]
Are there any news concerning this problem?
