### ISSUE TITLE
Problem with tracking background location on Android

### ISSUE THREAD

**Issue by sergiik222** [expo/expo#20934]
### Summary

Sorry for opening a new issue, but I have not found the solution for this problem. There are a few issues regarding to this topic, but they all are out-of-date.
I try to track the location in the background. I test on emulators. 
On iOS tracking works as expected, even if the app is not in foreground.
On android I do not get any updates when the app is in background (not killed).
I have tried all solutions from the old issues, I have changed battery and app preferences on the android emulator, but unfortunately I have not found the solution.
Location updates when the app in active, but when I go to home screen or open another app, I do not receive location updates anymore.
I use managed workflow.
Unfortunately I am not able to make expo eject for this project.
Expected Behavior: Receiving location updates when the app is in background.
Actual Behavior: No location updates when the app is not active.

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.6 => 47.0.6 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      expo-cli: 6.1.0
    Expo Workflow: bare

### Minimal reproducible example

 await Location.startLocationUpdatesAsync(LOCATION_TRACKING, {
          foregroundService: {
            notificationTitle: 'Your title',
            notificationBody: 'Notification Body',
            killServiceOnDestroy: false,
          },
          showsBackgroundLocationIndicator: true,
          pausesUpdatesAutomatically: false,         
          timeInterval: 1000,
          distanceInterval: 0,
          accuracy: Location.Accuracy.BestForNavigation,    
        });

TaskManager.defineTask(LOCATION_TRACKING, async ({ data, error }) => {
  if (error) {
    console.log("LOCATION_TRACKING task ERROR:", error);
    return;
  }
  if (data) {
    const { locations } = data;
    let lat = locations[0].coords.latitude;
    let long = locations[0].coords.longitude;
    let speed = locations[0].coords.speed;
    let locationLog = {
      lat: lat,
      long: long,
      speed: speed,
    };
    console.log("locationLog: ", locationLog)
  }
})

**Comment by kodamirmo** [comment]
+1

**Comment by vrgimael** [comment]
@brentvatne this is not incomplete or invalid repro, all you need is the most basic implementation of expo-location like @sergiik222 said.

This may be an issue with Android itself though, in that case, then the docs really need updating because it doesn't say anything about it not working on Android, but the fact is that it doesn't work as described.
