### ISSUE TITLE
[expo-notifications] Notification content data in the wrong format

### ISSUE THREAD

**Issue by SohelIslamImran** [expo/expo#20936]
### Summary

Suddenly I noticed an issue with `expo-notification`. I'm sending notifications from my backend using `expo-server-sdk` with some data like this ...
 ```js
 { "content-available": 1, screen: "profile", params: { screen: "profile" } }
 ```
 In my app, I'm getting the wrong format of the data by `addNotificationResponseReceivedListener` and from `response?.notification.request.content` property. The received format of the above data is...
 ```js
 { "fields": {"content-available": {"numberValue": 1}, "params": {"structValue": [Object]}, "screen": {"stringValue": "profile"}}}
 ```
 

### What platform(s) does this occur on?

Android

### Environment

```sh
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~47.0.13 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: bare
```

### Minimal reproducible example

```js
// backend
expo.sendPushNotificationsAsync([{
        to: "ExponentPushToken[OTeh8eN3lmq9T4t2Jmg2Qv]",
        priority: "high",
        sound: "default",
        mutableContent: true,
        body: "sohelislamimran commented on your post.",
        title: "sohelislamimran commented on your post.",
        data: {
          "content-available": 1,
          screen: "profile",
          params: {screen: "profile"},
        },
      }]);
      
      --------------------------------------------------
      
// frondend
Notifications.addNotificationResponseReceivedListener(
      (response) => {
        const data = response?.notification.request.content.data;
        console.log(data);
       data => {"fields": {"content-available": {"numberValue": 1}, "params": {"structValue": [Object]}, "screen": {"stringValue": "profile"}}}
    );
```

**Comment by d4rky-pl** [comment]
I can confirm we're running into the same issue. Interestingly enough, it only affects one of our apps while the other is still working correctly. We're sending the push notifications from our server with direct API calls to `https://exp.host/--/api/v2/push/send` and have been doing so for years now, the change seems to have started happening recently.

The `trigger.remoteMessage.data.body` is also wrong.
Let me know if there's any additional debugging info you would find helpful (message IDs? push notification tokens?)

**Comment by massick** [comment]
In addition to what @d4rky-pl wrote, and in order to exclude completely our backend implementation, we are experiencing the issue also when sending the push notification through https://expo.dev/notifications.

**Comment by SohelIslamImran** [comment]
Yes. I also tried https://expo.dev/notifications, same result.

**Comment by christopherwalter** [comment]
Hi all - we rolled back some recent changes to Android notifications, so you should be seeing the correct behavior once again. Let me know if that's not the case.

I will be looking into the underlying issue this week, and will update here when we have a fix.

**Comment by d4rky-pl** [comment]
@christopherwalter thank you, the issue seems to be solved for us 🙏

**Comment by massick** [comment]
@christopherwalter thanks for looking at it.

**Comment by SohelIslamImran** [comment]
@christopherwalter Thank you

**Comment by brandon-kyle-bailey** [comment]
This issue seams to have re-appeared. @christopherwalter was there a resolution to this?
