### ISSUE TITLE
[expo-image]: prefetch is useless without returning a promise

### ISSUE THREAD

**Issue by NTag** [expo/expo#20935]
### Summary

Hello!

I'm trying the new `expo-image` package, and I just noticed that `prefetch()` is returning `void`, which makes it impossible to know if an image has been prefetched or not.

The RN `Image.prefetch` method is returning a promise allowing to know when an image has been prefetched and it's a good thing, I believe `expo-image` should follow the same pattern.

Also it would be nice that:
- either `prefetch` directly returns if the URL has already been cached (even after an app restart)
- either exposes another static method `hasBeenPrefetched` allowing to check if an URL has been prefetched in the past or not.

Thanks!

### What platform(s) does this occur on?

iOS

### Environment

SDK 47

### Minimal reproducible example

https://docs.expo.dev/versions/unversioned/sdk/image/#prefetchurls

**Comment by NTag** [comment]
The library should really offer similar functions as the RN Image does:

<img width="719" alt="CleanShot 2023-02-08 at 11 28 51@2x" src="https://user-images.githubusercontent.com/906276/217504300-59b75b36-47c4-4f3f-8f55-4b1677ec8728.png">

A typical use-case is:
- you have a grid of pictures in low quality
- the user taps on one of them to display it fullscreen
- we start loading the picture in better quality
- we want to display the low quality picture while the higher one is loading

This requires being able to precisely control the prefetch as well as knowing what has been prefetched and what hasn't been.

Thanks!

**Comment by aleqsio** [comment]
hi 👋 

Wouldn't the best solution for your usecase be to use the low resolution version as a placeholder?

I think the goal of exposing prefetch is to provide a performance optimization, not as a dependable API, so I'd avoid code that needs to check if an image is prefetched.

**Comment by NTag** [comment]
I discovered this prop after and it might be actually; I'm still investigating that to see if it addresses my use-case or not. I'll keep you updated!

**Comment by aleqsio** [comment]
Thanks - I'll close the issue for now but we'll consider adding a return type to prefetch.

**Comment by jxxe** [comment]
+1 for adding this.

My use case is hiding the image entirely if it fails to load—that is, showing the image once it loads successfully. It's kind niche, but it would be nice to both find out of the image loads and cache it if it does in the same request. If there's another way to do this, I'd like to know.

Also, there's a lot to be said for being compatible with or at least similar to React Native's component.

**Comment by kartikeyvaish** [comment]
It's really useless without returning a promise. This issue should be reopened and looked into.

**Comment by Xample** [comment]
> It's really useless without returning a promise. This issue should be reopened and looked into.

Hello, does anyone found a workaround ?
