### ISSUE TITLE
[expo-notifications] Clashing with OneSignal

### ISSUE THREAD

**Issue by jacklj** [expo/expo#20937]
### Summary

I've got react-native-onesignal installed on a bare React Native project, and I've since installed expo-notifications to fire local notifications. I get this warning on iOS startup (it comes from this code [here](https://github.com/expo/expo/blob/e01c62aa8d02e18c80f5fadd10a9448a7c69628b/packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m#L32):

```
EXNotificationCenterDelegate encountered already present delegate of UNUserNotificationCenter: <OSUNUserNotificationCenterDelegate: 0x600003c68460>. EXNotificationCenterDelegate will not overwrite the value not to break other features of your app. In return, expo-notifications may not work properly. To fix this problem either remove setting of the second delegate or set the delegate to an instance of EXNotificationCenterDelegate manually afterwards.
```

I believe this is because OneSignal already sets its own delegate.

The result is: local notifications get delivered, but neither the `Notifications.setNotificationHandler()` handler nor the OneSignal equivalent get fired. 

To fix, I've tried to follow the advice given - `set the delegate to an instance of EXNotificationCenterDelegate manually afterwards.`:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // ... 

  EXNotificationCenterDelegate *expoNotifDelegate = [[EXNotificationCenterDelegate alloc] init];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:expoNotifDelegate];
  
  //...
}
```

This builds successfully but then local notifications don't even fire.

This should be compatible with OneSignal, see here https://github.com/OneSignal/react-native-onesignal/issues/958#issuecomment-600267864:
> OneSignal does swizzle the UNUserNotificationCenter so even if you have [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self]; in your code it shouldn't break OneSignal.

 Any ideas how to make expo-notifications work with OneSignal on iOS (it works fine on Android)? Thanks

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - ~/dev/adapt/appup/node_modules/.bin/yarn
      npm: 9.1.2 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.12.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: 47.0.13 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.6 => 0.70.6
    Expo Workflow: bare

### Minimal reproducible example

```
#import <EXNotifications/EXNotificationCenterDelegate.h>


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
   EXNotificationCenterDelegate *expoNotifDelegate = [[EXNotificationCenterDelegate alloc] init];
   [[UNUserNotificationCenter currentNotificationCenter] setDelegate:expoNotifDelegate];
```

**Comment by viljark** [comment]
I'm having similar issue with [HelpCrunch SDK](https://github.com/helpcrunch/helpcrunchsdk-ios), both (expo-notifications and HelpCrunch) are able to show their notificitations, but since adding HelpCrunch SDK, I'm not able to get my `Notifications.addNotificationReceivedListener` and `Notifications.setNotificationHandler` handlers to execute when pressing on the notification which is handled by expo-notifications.

Also I don't see any `EXNotificationCenterDelegate` in the logs, so I think the HelpCrunch SDK is overwriting the delegate in similar way [as described here](https://github.com/expo/expo/blob/e01c62aa8d02e18c80f5fadd10a9448a7c69628b/packages/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.m#L32), but I'm not sure how to restore it for expo-notifications with ObjC.

**Comment by Klyado** [comment]
Same issue here, any news?

**Comment by huylocit14054** [comment]
Same issue with Expo SDK 52, any news on this one?

**Comment by ted-mundy** [comment]
Is there any updates at all on this? A lot of people seem to be struggling with this.

**Comment by fannytavart** [comment]
I've also noticed this issue with Expo SDK 52. Does anyone know if this is fixed on Expo 53? Or if someone is working on a fix?

**Comment by sospedra** [comment]
Same problem over here. Removing OneSingal makes `expo-notifications` to work again. I can schedule local notifications, but cannot handle the receiving.

**Comment by radekzz** [comment]
After upgrading to **Expo SDK 53**, my **Bloom reach** (Exponea) integration stopped getting notification_id and that leads to top sending push notifications.
S
It seems like same error as with OneSignal.

**Comment by Jackmekiss** [comment]
I still have the bug on Expo SDK 54....
It seems to be an major issue to me.
Can we have some news from the team?

**Comment by darkblitzrc** [comment]
Can confirm this is happening on expo SDK 55 on 2026. Can we get answers???
