### ISSUE TITLE
How to put Downloaded file in Camera Roll or other location  

### ISSUE THREAD

**Issue by waheed25** [expo/expo#2094]
I am downloading a video file with FileSystem, it downloads well and plays well in video component but after that when i want to see this file in camera roll on ios device it not been there.
the path where its downloaded is 
file:///var/mobile/Containers/Data/Application/12BC6EB4-C2C6-4754-B738-96EED6347593/Documents/ExponentExperienceData/%2540mghazanfar89%252FDancingBook/TEST.mp4. 
i want to put this file in Camera roll on on other custom location.

here is my code,
`    FileSystem.downloadAsync(
          'https://s3.amazonaws.com/dancebook-development/mov.mp4',
          FileSystem.documentDirectory+'TEST.mp4'
      )  .then(({ uri }) => {
          console.log('uri is ::', uri);
          self.setState({video:uri, showVideo:true});
          console.log('Finished downloading to ', uri);
      })
          .catch(error => {
              console.error(error);
          })`

**Comment by AdamJNavarro** [comment]
Hey @waheed25,

I replied to your forum post with some solutions: https://forums.expo.io/t/how-to-locates-downloaded-file-on-device/12542

In the future, please save questions like this for the forums rather than Github issues. We try to keep issues limited to reproducible bugs.

Cheers,

Adam
