### ISSUE TITLE
[docs] Reference compatible versions of packages within specific expo-core releases

### ISSUE THREAD

**Issue by FrederickEngelhardt** [expo/expo#20946]
### Summary

Hi expo team! 

When integrating expo sdk with expo packages that are not the latest version, it seems a bit difficult/unclear when attempting to match versions of each package to remain compatible with the main `expo` package. 

**noting that this is for a bare react-native project**. _Does the expo cli do any of this matching automatically? The expo-cli is hard to use with yarn workspaces when installing package due to the `-W` flag being required for top level installs._

#### Example
In order to figure out which version of `expo-barcode-scanner` to use with expo 45 I had to look at the github branch for [sdk-45/expo-barcode-scanner](https://github.com/expo/expo/blob/sdk-45/packages/expo-barcode-scanner/package.json) and match the major version of expo-barcode-scanner. This matching still feels like a guess since I see in sdk-45 to sdk-46 the same version of the package but then it bumps to 12.1.1 in sdk-47.

**Can expo look into adding more verbosity in the published docs per major version about version numbers of each package that are compatible with the expo sdk?**

Doc Feature Request:
- Each major version of expo-core release references major versions of dependencies IE (expo-barcode-scanner, expo-camera) that are compatible with the SDK release.
- - Example SDK 45 would recommend users to run `npm install expo@45.0.7` and if 45.0.8 was published, the docs would recommend installing `npm install expo@45.0.8`. These docs would be auto-published to their corresponding version IE if a 45 fix went it, it would auto update the v45 docs with changes related to the latest compatible version.
- Each patch to a major version IE any component, should update the recommended installation version of the package. 
- -Example for expo-barcode-scanner would say `npm install expo-barcode-scanner@11.3.0` and if an update was released it would update the SDK 45 docs to say `npm install expo-barcode-scanner@11.4.0`

These changes should not be a manual thing. Example node script to extract the package.json version and find and replace the npm script within the doc generation section.

Maybe also adding a compatibility section under each component would make things easier 

IE `expo-barcode-scanner` compatibility range: SDK 45 ~11.3.0

This change would apply to all expo package docs used across the major sdk versions.

References
https://docs.expo.dev/versions/v45.0.0/sdk/bar-code-scanner/

Thanks!

### Link to the related docs page

https://docs.expo.dev/versions/v45.0.0/sdk/bar-code-scanner/

**Comment by brentvatne** [comment]
if you run `npx expo install --fix` we will run `yarn add` or `npm install` with the appropriate versions and output the versions. for example, i manually downgraded some packages in a project and then ran this:

```
npx expo install --fix
Some dependencies are incompatible with the installed expo version:
  expo-build-properties@0.5.2 - expected version: ~0.6.0
  expo-constants@14.0.2 - expected version: ~14.2.1
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install expo-build-properties@~0.6.0 expo-constants@~14.2.1
› Installing 2 SDK 48.0.0 compatible native modules using yarn
> yarn add expo-build-properties@~0.6.0 expo-constants@~14.2.1
```

notice how it says:

```
yarn add expo-build-properties@~0.6.0 expo-constants@~14.2.1
```

so if this fails for some reason (not sure what about the workspace is causing it to fail, that seems like a separate issue) then you can copy that and do whatever you need to make it work within your repo
