### ISSUE TITLE
`npx expo start --tunnel` causes error with self signed certificate in certificate chain 

### ISSUE THREAD

**Issue by jjlin526** [expo/expo#20940]
### Summary

Running the command `npx expo start --tunnel` results in the following error:

Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project.
FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: self signed certificate in certificate chain

No QR code is available to scan. I am able to visit the above URL on my browser with a valid certificate.

### What platform(s) does this occur on?

iOS

### SDK Version

~47.0.8

### Environment

expo-env-info@1.0.5

### Minimal reproducible example

Run the command `npx expo start --tunnel`.

The commands `npx expo start --offline` and `expo start` result in a QR code; once the QR code is scanned on iOS, the server does not respond.

**Comment by matthewwwillard** [comment]
Updating my `package.json's` `"start" to "start": "NODE_TLS_REJECT_UNAUTHORIZED=0 expo start"` Helped me get past the self signed cert issue. You can also add your --tunnel. Then just run `yarn start`

**Comment by EvanBacon** [comment]
I think this is a Node version issue but I can't be sure because the "Environment" wasn't correctly reported in the issue template. Please feel free to reopen with information that can lead to accurate reproduction.
