### ISSUE TITLE
[backport][bug] SDK 45, 46 expo-barcode-scanner - not unmounting camera

### ISSUE THREAD

**Issue by FrederickEngelhardt** [expo/expo#20947]
### Summary

Are there plans to backport [PR #18768](https://github.com/expo/expo/pull/18768/files#diff-764b244938ea3f0ceab89a84e083d01cdf3a5ff4fdf3c075cf2fef5f30ba6fd7) for 11.x.x release of `expo-barcode-scanner`?

Right now the only solution is to do a [patch-package](https://www.npmjs.com/package/patch-package) or upgrade to SDK47 which requires a react-native upgrade to avoid the permanent camera in the background issue for android.

**Also what is the process for creating pull requests that target older SDKs.** 

I'd like to create a PR with this fix cherry-picked from [PR #18768](https://github.com/expo/expo/pull/18768/files#diff-764b244938ea3f0ceab89a84e083d01cdf3a5ff4fdf3c075cf2fef5f30ba6fd7) that targeted `main`

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/Library/Caches/fnm_multishells/18455_1653528545827/bin/node
      Yarn: 1.22.5 - ~/Library/Caches/fnm_multishells/18455_1653528545827/bin/yarn
      npm: 8.11.0 - ~/Library/Caches/fnm_multishells/18455_1653528545827/bin/npm
      Watchman: 2022.09.26.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-24 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: 45.0.8 => 45.0.8
      metro: ~0.67.0 => 0.67.0
      react: 17.0.2 => 17.0.2
      react-native: ~0.68.5 => 0.68.5
    npmGlobalPackages:
      expo-cli: 6.1.0
    Expo Workflow: bare

### Minimal reproducible example

Adding the following to the expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt resolves the background camera issue on android for 11.3.0 and 11.4.0 of **expo-barcode-scanner**

```diff
diff --git a/node_modules/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt b/node_modules/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
index b0d1a23..94d6832 100644
--- a/node_modules/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
+++ b/node_modules/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
@@ -99,10 +99,11 @@ internal class BarCodeScannerViewFinder(
 
   @Synchronized
   private fun startCamera() {
-    if (!isStarting) {
+    if (!isStarting && !isStopping) {
       isStarting = true
       try {
-        ExpoBarCodeScanner.instance.acquireCameraInstance(cameraType)?.run {
+        camera = ExpoBarCodeScanner.instance.acquireCameraInstance(cameraType)
+        camera?.run {
           val temporaryParameters = parameters
           // set autofocus
           val focusModes = temporaryParameters.supportedFocusModes

```

**Comment by pmm1** [comment]
We're experiencing this issue as well.

**Comment by mananbordia** [comment]
Actually, for some reason above patch doesn't work for Samsung Galaxy S21 but works well with other android devices.

**Comment by brentvatne** [comment]
@lukmccall - could you backport this fix to sdk 46 when you have some time to do so? we don't support sdk 45 anymore so that is no needed

**Comment by FrederickEngelhardt** [comment]
If SDK45 is not supported any longer I can close this. @brentvatne @lukmccall  Thanks for bringing the fix into older versions of the SDK.

Also curious if fixes like this could be tagged maybe as "Maintenance SDK@<NUMBER>" and a PR could be auto-created for an older SDK if applicable.

For SDK45 my team can make due with patch-package until we're ready for SDK46 or higher.
