### ISSUE TITLE
Question: Use custom bundle on build?

### ISSUE THREAD

**Issue by stevefan1999** [expo/expo#2095]
So I wanted to use [Haul](https://github.com/callstack/haul) instead of default Metro to build my bundle(s) (Haul works much better than Metro and it offers Webpack which is very important), but I currently see no options to change the `exp build` behavior to use Metro atm. What exactly do I need to patch right now to supply a custom bundle built by haul so that I'dnt have to think about Metro compatibility?

**Comment by AdamJNavarro** [comment]
Hey @stevefan1999,

We are looking to make it where our devtools work with different bundlers other than Metro, but it isn't currently possible to customize. For future reference, please bring this types of questions to our forums https://forums.expo.io/ as we like to keep Github issues limited to reproducible bugs.

Cheers,
Adam
