### ISSUE TITLE
No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.

### ISSUE THREAD

**Issue by homosape** [expo/expo#20958]
### Summary

Hi, 

Briefly about my current project, it started as expo managed workflow using SDK 45, I've ejected to expo bare workflow a while ago when it was SDK 46. Now I am on SDK 47. 

**Please note that I already had `expo-splash-screen` and `expo-updates` installed in my managed workflow before I ejected to bare workflow.**

I've been struggling to fix a notorious bug on iOS **"No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first."** It only happens when I deliver OTA updates using `expo publish` command. I also occasionally notice a white flicker when I hide a splash screen.

I've dig through github issues here and found [this solution ](https://github.com/expo/expo/issues/7689#issuecomment-618728916) but it covers the case when your project uses `react-native-unimodules`, my project is using `expo-modules`. 

Could you please clarify how to solve this problem with `expo-modules` enabled?

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.2.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-28 | ARM 64 v8a, android-28 | Google APIs Intel x86 Atom, android-30 | ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.4.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

1. Install expo app ( managed or bare )
2. Install `expo-splash-screen` and `expo-updates`
3. Create a release build and instal on iOS
4. Publish OTA update
5. Reload installed app to receive OTA updates

**Comment by youssdevx** [comment]
I think this commit should fix the issue: https://github.com/expo/expo/commit/47e79c68b2b1e4ea5f22d791a1ce7195f9ac97b4

**Comment by thanhloc-17** [comment]
+1

**Comment by homosape** [comment]
Hi @amandeepmittal 

Sorry for mentioning you in this thread, I'm aware that you are mostly concerned with docs but could you please help us raise awareness of this issue? We've talked about this here [#20570](https://github.com/expo/expo/issues/20570)

**Comment by brentvatne** [comment]
this should be resolved in sdk 48

**Comment by skdrew** [comment]
Hate to tell you this, but this hasn't been resolved as shown by our Sentry reports:

![Screenshot 2024-04-23 at 12 16 10](https://github.com/expo/expo/assets/101203626/3f3e2518-b4f9-4a1e-b733-8cf67f3d7c42)

**Comment by mirik999** [comment]
I got this warning after switching to new arch.

**Comment by kiorq** [comment]
Yeah almost all my users devices have reported this issue as well, this a problem

**Comment by ilyagru** [comment]
+1

Having this issue when the Expo-managed app is killed and I open it on a notification tap.

```
"expo": "~51.0.28",
"expo-splash-screen": "~0.27.5",
```

**Comment by sabuhiteymurov** [comment]
Can we reopen this issue? I’m also encountering this, my environment:
```
"expo": "~51.0.34",
"expo-splash-screen": "~0.27.6"
```

**Comment by ivancdlarrain** [comment]
We've been having this issue in production as well (almost 4k times in the last 30 days) . It's been very hard to reproduce in development. My environment is:
```
"expo": "~51.0.37",
"expo-splash-screen": "~0.27.6",
```
Has anyone found out what might be causing this error? Should this issue be reopened, or should we create a new one?

**Comment by raahimkhan** [comment]
Getting same warning in Expo SDK 51 as well in development. It does not affect the app but I would like to know what might be causing it.

**Comment by yaminichhabra** [comment]
Any update on this ?

**Comment by TahseenSust** [comment]
+1

**Comment by brentvatne** [comment]
please create a new issue with a minimal reproducible example if you're experiencing this, thank you!
