### ISSUE TITLE
Image picker continues to throw warning: Key "cancelled" in the image picker result is deprecated, use "canceled" instead, despite using canceled. 

### ISSUE THREAD

**Issue by whiee1** [expo/expo#20977]
### Summary

Image picker continues to throw warning: Key "cancelled" in the image picker result is deprecated, use "canceled" instead, despite using canceled. 

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

47

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: managed

### Minimal reproducible example

 const cameraImage = await ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [1, 1],
      quality: 0.5,
    });

    if (cameraImage.canceled) {
      throw Error("Camera was cancelled");
    }

**Comment by AmmuRamasubramanian** [comment]
Facing the same issue

**Comment by AmmuRamasubramanian** [comment]
Don't try to access canceled or cancelled. If you want to access image .You can only use the uri. Refer my My sample code.
import {View, Button,Alert, Image, Text, StyleSheet} from 'react-native'
import { useState } from 'react';
import {launchCameraAsync, useCameraPermissions, PermissionStatus} from 'expo-image-picker'


function ImagePicker(){
    const [cameraPermissionInformation, requestPermission]=useCameraPermissions();
    const [pickedImage, setPickedImage]=useState()

    async function verifyPermission(){
        if (cameraPermissionInformation.status===PermissionStatus.UNDETERMINED){
            const permissionResponse=await requestPermission();

            return permissionResponse.granted;
        }
        if (cameraPermissionInformation.status===PermissionStatus.DENIED){
            Alert.alert(
                'Insufficient permission!',
                'You need to grant camera access to use this app'
            );
            return false
        }
        return true;
    }
    async function camerapressHandler(){
        const hasPermission=await verifyPermission()
        if (!hasPermission){
            return;
        }
        const image=await launchCameraAsync({
            allowsEditing:true,
            aspect:[16,9],
            quality:0.5
        });
        setPickedImage(image.assets)
    }

    let imagePreview=<Text style={styles.previewText}>No image taken yet</Text>

    if (pickedImage){
        imagePreview=<Image source={{uri:pickedImage[0].uri}} style={styles.imageStyle}/>
    }
    return(
    <View>
        <View style={styles.imagepreviewcontainer}>
            {imagePreview}
        </View>
        <Button title='Take Image' onPress={camerapressHandler}/>
    </View>
    )
}

export default ImagePicker

const styles=StyleSheet.create({
    imagepreviewcontainer:{
        alignItems:'center',
        justifyContent:'center',
        width:'100%',
        height:200,
        backgroundColor:'#f0cced',
        marginVertical:8,
        borderRadius:8, 
    },
    previewText:{
        color:'#592454',
    },
    imageStyle:{
        width:'100%',
        height:'100%',
    }
})

**Comment by Alicecold** [comment]
> Don't try to access canceled or cancelled. If you want to access image .You can only use the uri. Refer my sample code. import {View, Button,Alert, Image, Text, StyleSheet} from 'react-native' import { useState } from 'react'; import {launchCameraAsync, useCameraPermissions, PermissionStatus} from 'expo-image-picker'
> 
> function ImagePicker(){ const [cameraPermissionInformation, requestPermission]=useCameraPermissions(); const [pickedImage, setPickedImage]=useState()
> 
> ```
> async function verifyPermission(){
>     if (cameraPermissionInformation.status===PermissionStatus.UNDETERMINED){
>         const permissionResponse=await requestPermission();
> 
>         return permissionResponse.granted;
>     }
>     if (cameraPermissionInformation.status===PermissionStatus.DENIED){
>         Alert.alert(
>             'Insufficient permission!',
>             'You need to grant camera access to use this app'
>         );
>         return false
>     }
>     return true;
> }
> async function camerapressHandler(){
>     const hasPermission=await verifyPermission()
>     if (!hasPermission){
>         return;
>     }
>     const image=await launchCameraAsync({
>         allowsEditing:true,
>         aspect:[16,9],
>         quality:0.5
>     });
>     setPickedImage(image.assets)
> }
> 
> let imagePreview=<Text style={styles.previewText}>No image taken yet</Text>
> 
> if (pickedImage){
>     imagePreview=<Image source={{uri:pickedImage[0].uri}} style={styles.imageStyle}/>
> }
> return(
> <View>
>     <View style={styles.imagepreviewcontainer}>
>         {imagePreview}
>     </View>
>     <Button title='Take Image' onPress={camerapressHandler}/>
> </View>
> )
> ```
> 
> }
> 
> export default ImagePicker
> 
> const styles=StyleSheet.create({ imagepreviewcontainer:{ alignItems:'center', justifyContent:'center', width:'100%', height:200, backgroundColor:'#f0cced', marginVertical:8, borderRadius:8, }, previewText:{ color:'#592454', }, imageStyle:{ width:'100%', height:'100%', } })

Hm, if so, shouldn't the error message reflect this, instead of suggesting `.canceled `instead of `.cancelled`? Code quality etc aside, it still feels like an bug/issue that the error message is leading devs astray.

**Comment by whiee1** [comment]
@AmmuRamasubramanian , thank you for your help! I've removed the use of canceled in my code but the error persists.

**Comment by kirtikapadiya** [comment]
I also getting same issue with expo SDK 47
Key "uri" in the image picker result is deprecated and will be removed in SDK 48, you can access selected assets through the "assets" array instead.
Key "cancelled" in the image picker result is deprecated and will be removed in SDK 48, use "canceled" instead.
Key "base64" in the image picker result is deprecated and will be removed in SDK 48, you can access selected assets through the "assets" array instead.

**Comment by Alicecold** [comment]
> I also getting same issue with expo SDK 47 Key "uri" in the image picker result is deprecated and will be removed in SDK 48, you can access selected assets through the "assets" array instead. Key "cancelled" in the image picker result is deprecated and will be removed in SDK 48, use "canceled" instead. Key "base64" in the image picker result is deprecated and will be removed in SDK 48, you can access selected assets through the "assets" array instead.

To be clear: Have you changed all instances of cancelled to canceled/ alternatively, have you removed all instance of canceled/cancelled in the code? (just checking if the problem is identical to whiee1's or if your have a similar but technically different problem)

**Comment by AkbarBakhshi** [comment]
I am facing the same issue. Not even using canceled in my code.


"expo": "~47.0.9",
"expo-image-picker": "~14.0.2",

**Comment by kirtikapadiya** [comment]
@Alicecold  I have also checked with changing all instances of cancelled to canceled but issue remain same as mentioned.

**Comment by mikeRChambers610** [comment]
You can reporpduce the issue using the latest Expo SDK 47 and latest version of expo-image-picker, started up the android device, and try using the below as described in the expo docs:

The result is undefined only on android.

if(this.state.camLibPermStatus === "granted"){
     let result = await ImagePicker.launchImageLibraryAsync({
          mediaTypes: ImagePicker.MediaTypeOptions.All,
          allowsEditing: true,
          aspect: [4, 3],
          quality: 1,
      });

      console.log("RESULT ANDROID")
      console.log(result.assets[0])

**Comment by tigeryell99** [comment]
I also am able to reproduce this message while executing this part of the tutorial (https://docs.expo.dev/tutorial/image-picker/).  In my case, the picker opens and I select an image and after hitting "crop" it closes with that error message and the image is NOT picked. 
Running on a Pixel 3a, Expo: 0.4.11. Node: 19.5.0

**Comment by Sadikalivk** [comment]
> pickedImage

i got the same issue, but it was when i did log the result, if i comment logging complete result , solved the problem as cancelled and canceled are being used to log it  earlier

**Comment by tigeryell99** [comment]
You are correct, removing the console.log got rid of the error message. That seems a bit unexpected to me.

**Comment by charlestbell** [comment]
@tigeryell99 I think it's because the code warning you of the deprecation, is just checking whether or not the key of 'cancelled' on the results object was accessed or not. Since the console log was displaying the entire object, the warning was thrown.

Only accessing results.assets for example, doesn't access that deprecated key, so no warning is thrown.

**Comment by DaanBartholomeus** [comment]
You can change the console.log(result)
to
console.log(result.assets)
Because when you dont use .assets it shows you result wich also includes the canceled that gives the warning.

**Comment by benjaminmerchin** [comment]
I am on expo 47, I was able to fix the issue by going back to expo-image-picker 13.3.1

**Comment by theronburger** [comment]
Perhaps not actually a bug. 

When you log an object ,it gets traversed. So if you log the result of the launchImageLibraryAsync promise it will try access the depreciated cancelled and fire off the warning. 

The getting started guide has a `console.log(result);`
Probably causes a lot of confusion for newcomers (myself included)

**Comment by summer-cook** [comment]
> This warning causes a lot of confusion as it's triggered quite obscurely in the getting started guide.
> 
> To avoid this enumerability of the depreciated property could be set to false with Object.defineProperty. That way it is available for old code but not listed when not explicitly called for.

that sounds like a great solution.. how exactly would i do this? thank you ･ᴗ･

**Comment by heedoooch** [comment]
Hey, I happen to be getting the same warning, I tried replacing "cancelled"  with "canceled" in here. 
 ```
_const result = await ImagePicker.launchImageLibraryAsync();
     // Explore the result
     //console.log(result);
     if (!result**.canceled**) {
       setPickedImagePath(result);
       setIsImage(true);

     }
   }
```
and to show my image I used:
   <Image  source={{ uri: pickedImagePath.assets[0].uri }}   />
and it worked perfectly.

**Comment by heedoooch** [comment]
Hey, I happen to be getting the same warning, I tried replacing "cancelled"  with "canceled" in here. 
 ```
const result = await ImagePicker.launchImageLibraryAsync();
     // Explore the result
     //console.log(result);
     if (!result.canceled) {
       setPickedImagePath(result);
       setIsImage(true);

     }
   }
```
and to show my image I used:
  ` <Image  source={{ uri: pickedImagePath.assets[0].uri }}   />`
it worked perfectly.

**Comment by jacuencaAS** [comment]
Hi everyone, I Solved this bug only deleted this property "cancelled" from result object.
```
 let result = await ImagePicker.launchImageLibraryAsync({
      allowsEditing: true,
      quality: 1,
    });

    if (!result.canceled) {
      let filename = result?.assets[0].uri.substring(
        result?.assets[0].uri.lastIndexOf("/") + 1,
        result?.assets[0].uri.length
      );

      delete result.cancelled;
      result = {
        ...result,
        name: filename,
      };
    }
```

**Comment by jakedemian** [comment]
@jacuencaAS Solution worked for me!  I'm using typescript so for my project I can't directly delete the `cancelled` property as typescript doesn't see that property on `ImagePickerResult`.  My workaround is to define a custom type like this:
```
import { ImagePickerResult as ExpoImagePickerResult } from 'expo-image-picker';

type ImagePickerResult = ExpoImagePickerResult & { cancelled?: boolean };
```

Then when I'm processing the actual result data I can now delete the property and remove that warning.  eg:
```
export const processImage = (image: ImagePickerResult) => {
  delete image.cancelled;
  return image;
};
```

**Comment by LukasHechenberger** [comment]
That's just annoying, please remove this log message. 

I'd suggest we just ignore the warning in the meantime. If you're using TypeScript, it already tells you that there's no `canceled`.

```js
LogBox.ignoreLogs([
  'Key "cancelled" in the image picker result is deprecated and will be removed in SDK 48, use "canceled" instead',
]);
```

**Comment by jr00n** [comment]
Even when using SDK 49 this waring is still there!

**Comment by charlestbell** [comment]
Yes @jr00n as stated previously stated in this thread, if you access cancelled's parent object anywhere in your code (without specifying the child print.canceled specifically), the warning will be show.

**Comment by IronBlossom** [comment]
I think it's an internal error from the package itself [here](https://github.com/bolasblack/expo/blob/3f549f21f67b1454825b35c18f63d6e85c8693e7/packages/expo-image-picker/src/ImagePicker.ts#L73)

`mergeDeprecatedResult` is the issue

**Comment by MariuzM** [comment]
Yep still persist, dont understand why its closed...

**Comment by MariuzM** [comment]
Not sure why the prop is still being included in result `  "cancelled": false` the type is fine but this one is still being created in result payload

**Comment by lucastoll** [comment]
> Not sure why the prop is still being included in result ` "cancelled": false` the type is fine but this one is still being created in result payload
> 
> The docs even have it https://docs.expo.dev/versions/latest/sdk/imagepicker/
> 
> For now
> 
> ```ts
>   const pickImage = async () => {
>     const result = await ImagePicker.launchImageLibraryAsync({
>       mediaTypes: ImagePicker.MediaTypeOptions.All,
>       allowsEditing: true,
>       aspect: [4, 3],
>       quality: 1,
>     });
> 
>     delete (result as any).cancelled;
> 
>     if (!result.canceled) {
>       setImage(result.assets[0].uri);
>     }
>   };
> ```

Works well thank you, no other solution right now maybe a new issue should be considered as it seems this one has been ignored

**Comment by osmanyz** [comment]
Is there any good news so far? I'm not sure why this hasn't been fixed yet.

**Comment by Minbz** [comment]
I removed all result-related "console.log" and finally got rid of the warning.

**Comment by rileysk3** [comment]
updating to 14.5.0 fixed it for me.

**Comment by GninninwokyOuattara** [comment]
@Minbz That was it for me too. 
Was so confusing to have the warning when I was using the correct property. With the 'cancelled' key still in the result at the moment, a console.log of the result object will have the warning fire.

**Comment by abhishekx1** [comment]
> ### Summary
> Image picker continues to throw warning: Key "cancelled" in the image picker result is deprecated, use "canceled" instead, despite using canceled.
> 
> ### What platform(s) does this occur on?
> Android, iOS, Web
> 
> ### SDK Version
> 47
> 
> ### Environment
> expo-env-info 1.0.5 environment info: System: OS: Windows 10 10.0.22621 Binaries: Node: 16.18.0 - C:\Program Files\nodejs\node.EXE npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD IDEs: Android Studio: AI-213.7172.25.2113.9123335 npmPackages: babel-preset-expo: ~9.2.1 => 9.2.2 expo: ^47.0.0 => 47.0.8 react: 18.1.0 => 18.1.0 react-dom: 18.1.0 => 18.1.0 react-native: 0.70.5 => 0.70.5 react-native-web: ~0.18.7 => 0.18.10 Expo Workflow: managed
> 
> ### Minimal reproducible example
> const cameraImage = await ImagePicker.launchCameraAsync({ allowsEditing: true, aspect: [1, 1], quality: 0.5, });
> 
> ```
> if (cameraImage.canceled) {
>   throw Error("Camera was cancelled");
> }
> ```

**Comment by abhishekx1** [comment]
Just simply use result.length > 0 instead of !result.canceled it works fine for me!
hope it works for you also!

**Comment by felipesllopes** [comment]
The error is in console.log(result);
Just remove it as mentioned by @tigeryell99 👍🏽

**Comment by MnariMohamed** [comment]
@rileysk3 solution worked for me, I did `npm i expo-image-picker@14.5.0`

**Comment by pcfmello** [comment]
@rileysk3 solution worked for me too `npm i expo-image-picker@14.5.0`

**Comment by coofzilla** [comment]
upgrading to 14.5 resolved it for me.
