### ISSUE TITLE
fileName not found in android, expo image picker

### ISSUE THREAD

**Issue by abdusman2002** [expo/expo#20978]
### Summary

I am getting fileName on IOS, but on android the image has no fileName. how can i get fileName in android.

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2022.10.31.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 3.2.1
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

 let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      // allowsEditing: true,
      // base64: true,
      aspect: [4, 3],
      quality: 1,
      allowsMultipleSelection: true
    });

**Comment by alanjhughes** [comment]
fileName is not supported on android.
