### ISSUE TITLE
Missing assets in APK

### ISSUE THREAD

**Issue by k3nda** [expo/expo#20973]
### Summary

**Expected:** Add image into `assets`, build APK, inspect apk and there should be image in `assets` folder.
**Actual:** There is no image in `assets` folder which I added.

### What platform(s) does this occur on?

Android

### SDK Version

47.0.12

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.4.1
    Expo Workflow: managed
```

### Minimal reproducible example

Followed "Getting started" on Expo websites:
1. Created new app - `npx create-expo-app my-app`
2. Installed EAS CLI - `npm i -g eas-cli`
3. Added some image into `assets`
 ![1744](https://user-images.githubusercontent.com/12560054/215036300-7907a3c7-04ef-40ba-b4d4-1d77c436e857.png)
4. Added eas.json into root of app.  
```
{
  "build": {
    "preview": {
      "distribution": "internal"
    }
  }
}
```
5. Build app android app - `eas build --profile preview --platform android --local`
6. Inspect built APK with "Analyze APK" in Android studio

**Comment by EvanBacon** [comment]
- You need to add code that `require`s the image, otherwise it is "tree shaken" to minimize binary size.
- You can also include assets that aren't required by using [`assetBundlePatterns`](https://docs.expo.dev/versions/latest/config/app/#assetbundlepatterns).

**Comment by o-alexandrov** [comment]
@EvanBacon is the second option from your reply no longer supported?

> You can also include assets that aren't required by using [assetBundlePatterns](https://docs.expo.dev/versions/latest/config/app/#assetbundlepatterns).

---

Please consider to reopen this issue, as the problem described in this ticket also arises when using the popular `react-native-webview` w/ a built-in web app.
The only workaround seems to be:
- [expo prebuild](https://docs.expo.dev/workflow/prebuild/)
- and manually add [assets folder in Xcode](https://yelotofu.com/react-native-load-local-static-site-inside-webview-2b93eb1c4225#3e3a) & `sourceSets` in android's `build.gradle`
