### ISSUE TITLE
App fail to update if new bundle is identical to the current one

### ISSUE THREAD

**Issue by riwu** [expo/expo#2097]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/riwu-b3409f98-0bb9-4df6-9745-959210d8ea66.tar.gz

ExpoKit

### Steps to Reproduce

1. Add the following code:
```
Updates.checkForUpdateAsync().then(({ isAvailable }) => {
  if (isAvailable) {
    Updates.fetchUpdateAsync().then(() => Updates.reloadFromCache());
  }
});
```
2. Run `exp publish` twice.

### Expected Behavior

App should reload once.

### Actual Behavior

App repeatedly reloads (i.e. `isAvailable` remains true even after updating).

This only happens on Expo v29 (tested with ExpoKit app), when the newly published bundle is identical to the previous one.

**Comment by FiberJW** [comment]
Hi, we’re closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks :)
