### ISSUE TITLE
Audio not playing for videos in iOS

### ISSUE THREAD

**Issue by mikealche** [expo/expo#20996]
### Summary

Not sure why audio doesn't play when playing videos on iOS.
it works perfectly fine on Android.

I've made a super small repo that reproduces the error

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/mikealche/test-video-sound

yarn install & expo start to see it happen

**Comment by amit13091992** [comment]
any workaround of solutions for the issue??

**Comment by rp121** [comment]
I noticed a similar issue, but I can get sound to work by switching my phone off silent mode.  Otherwise, audio doesn't play.

**Comment by kockar96** [comment]
@rp121 Check this out:
https://github.com/expo/expo/issues/7485
