### ISSUE TITLE
DownloadResumable.downloadAsync() never resolved when uri is not valid or not exist

### ISSUE THREAD

**Issue by cheolhow** [expo/expo#20999]
## Expected behavior
DownloadResumable.downloadAsync() throw error or resolved.

## Actually happening
DownloadResumable.downloadAsync() is not resolved when set invalid uri.

### What platform(s) does this occur on?

iOS

### Environment

> System:
      OS: macOS 11.7
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.21.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.17 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@cheolho/expo-file-system-download-test

**Comment by neiker** [comment]
This is still happening, not just for DownloadResumable, but when using `FileSystem.downloadAsync` too
