### ISSUE TITLE
Asking for pushNotification permissions doesnt return [iOS]

### ISSUE THREAD

**Issue by farzd** [expo/expo#2099]
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.6.0
  Yarn: Not Found
  npm: 5.3.0
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/farzd-a1410e07-7e16-432d-8520-e25f8e93d4b4.tar.gz
```

target = iOS
### Steps to Reproduce

1. Replicate registerForPushNotificationsAsync from https://docs.expo.io/versions/latest/guides/push-notifications
2. Call it ```await registerForPushNotificationsAsync```

### Expected Behavior

I would expect this to return the token or the status i.e undetermined etc etc after dealing with the dialogue [allow/dont allow]

![image](https://user-images.githubusercontent.com/1423413/44005865-1e5d7bea-9e72-11e8-98d9-b8394671815f.png)

### Actual Behavior

This code hangs after dealing with the dialogue, the ```await``` keeps waiting for the function to return. Using a ```.then``` behaves the same way. ```.catch``` doesn't respond either.

This appears to work if you call the ```registerForPushNotificationsAsync()``` without ```await``` 
but the contents of this are asynchronous so theres no way to wait for the token and store it into a DB etc etc

Note: this used to work, last time i tested it working was expo 22

### Reproducible Demo

I've replicated it here
https://snack.expo.io/SJBogf0rm

**Comment by machester4** [comment]
same problem.

**Comment by farzd** [comment]
related: https://github.com/expo/expo/issues/2155

**Comment by sjchmiela** [comment]
Hey guys, could you please check whether this issue has been fixed in SDK 30? I used the Snack provided with SDK 30 and the _log that doesn't log_ showed up in the console. 🙂 https://snack.expo.io/@sjchmiela/sadistic-bagel

**Comment by machester4** [comment]
Hi, The problem remains in SDK 30.

**Comment by sjchmiela** [comment]
Huh, if you're using ExpoKit I believe you must have ejected/detached. If so, Expo push notifications won't work, see [the documentation](https://docs.expo.io/versions/v30.0.0/expokit/eject#you-require-expos-push-notification-services-after). 🙂

**Comment by farzd** [comment]
@sjchmiela tested and working as well, thanks !!!!!! <3

**Comment by kalinchuk** [comment]
I'm using expo version 32.0.0 and still seeing this issue.

**Comment by brentvatne** [comment]
@kalinchuk - replied to you on other issue
