### ISSUE TITLE
Add support for FB Account Kit login in addition to standard FB login

### ISSUE THREAD

**Issue by amjibaly** [expo/expo#21]
This is probably the same native sdk, and allows password-less logins using email or mobile device.

https://developers.facebook.com/docs/accountkit

**Comment by brentvatne** [comment]
hi there! we don't have this planned but i've started a discussion about this to maybe have something similar in medium term

**Comment by sheerun** [comment]
I am interested

**Comment by giautm** [comment]
I am interested, too. 👍

**Comment by asyrique** [comment]
Absolutely interested.

**Comment by dikaiosune** [comment]
Hi! We're tracking this feature request at https://expo.canny.io/feature-requests/p/facebook-accountkit, please vote there!
