### ISSUE TITLE
"stopLocationUpdatesAsync" doesn't stop background GPS task

### ISSUE THREAD

**Issue by Gogn** [expo/expo#21004]
### Summary

For the `startLocationUpdatesAsync` task (if background locations) the `stopLocationUpdatesAsync` doesn't stop the task.

It doesn't stop the task. After the app has been killed, the app starts up again and start to send locations. (I can see this from the logs and from the fact that the GPS icon appears again in the status bar). 

May be related with https://github.com/expo/expo/issues/10135

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.npm-global/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.5 => 0.68.5
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 2.5.1
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

```
export const handleLocations = (props: PropTypes) => {
  const { track } = props;
  const locationPerms = useAppSelector(
    (state) => state.app.locationPermsGranted,
  );
  const lastTime = useRef(0);

  const registerLocationService = async () => {
    await Location.startLocationUpdatesAsync(GPSTaskName, {
      foregroundService: {
        notificationTitle: 'GPS',
        notificationBody: ' enabled',
        killServiceOnDestroy: true,
      },
      accuracy: Location.Accuracy.BestForNavigation,
      distanceInterval: 15, // minimum change (in meters) between updates
      timeInterval: 3000, // only Android
      pausesUpdatesAutomatically: true, // only iOS
      activityType: LocationActivityType.AutomotiveNavigation, // needed for pausesUpdatesAutomatically
    });
  };
  const stopLocationService = async () => {
    await Location.stopLocationUpdatesAsync(GPSTaskName);
  };

  useEffect(() => {
    if (!track) stopLocationService();
    TaskManager.getRegisteredTasksAsync().then(async (tasks: any[]) => {
      const isTaskRegistered = tasks.some(
        (task) => task.taskName === GPSTaskName,
      );

      if (!isTaskRegistered) await registerLocationService();
    });
  }, [track, locationPerms]);

  useEffect(() => {
    const unsubscribeFromLocations = async () => {
      await Location.stopLocationUpdatesAsync(GPSTaskName);
      await Location.stopGeofencingAsync(GPSTaskName);
    };

    return () => {
      unsubscribeFromLocations();
    };
  }, []);

  TaskManager.defineTask(GPSTaskName, async ({ data, error }) => {
    const { locations }: { locations: locationsType[] } = data;

    const currentTime = Date.now();
    const timeToSend = currentTime - lastTime.current;

    if (timeToSend > 5000) {
      await sendLocationsToServer(locations);
      lastTime.current = currentTime;
    }
  });
};
```

Also, is it correct to use defineTask if request to server will perform in background or should I use BackgroundFetch?

**Comment by marc-wittwer** [comment]
I ran into the same issue and asked ChatGPT on how to make sure the background task is really stopped:

Maybe unregistering all tasks could be used as a workaround.

**Here is the output of ChatGPT:**

To ensure that the background location task is properly closed in your React Native app, you can use a combination of the stopLocationUpdatesAsync function and the TaskManager.unregisterAllTasksAsync function.

Here's an example code snippet that demonstrates how to properly stop and unregister the background location task:


javascript

```
Copy code
import React, { useEffect } from 'react';
import { View, Text, Button } from 'react-native';
import * as Location from 'expo-location';
import * as TaskManager from 'expo-task-manager';

const LOCATION_TASK_NAME = 'background-location-task';

export default function App() {
  useEffect(() => {
    // Check if background location is available on the device
    const checkBackgroundLocation = async () => {
      const { status } = await Location.requestBackgroundPermissionsAsync();
      if (status === 'granted') {
        console.log('Background location enabled');
      }
    };

    checkBackgroundLocation();
  }, []);

  const startBackgroundLocation = async () => {
    try {
      await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.Balanced,
        timeInterval: 5000,
        distanceInterval: 100,
        foregroundService: {
          notificationTitle: 'Background location enabled',
          notificationBody: 'This app is using background location',
        },
      });
      console.log('Background location started');
    } catch (error) {
      console.log(error);
    }
  };

  const stopBackgroundLocation = async () => {
    try {
      await Location.stopLocationUpdatesAsync(LOCATION_TASK_NAME);
      console.log('Background location stopped');
      await TaskManager.unregisterAllTasksAsync();
      console.log('All tasks unregistered');
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Background Location Demo</Text>
      <Button title="Start Background Location" onPress={startBackgroundLocation} />
      <Button title="Stop Background Location" onPress={stopBackgroundLocation} />
    </View>
  );
}
```

In this example, we define the LOCATION_TASK_NAME constant, which is used to identify the background location task. We also define two functions, startBackgroundLocation and stopBackgroundLocation, which respectively start and stop the background location task.

To stop the background location task, we call the Location.stopLocationUpdatesAsync function with the LOCATION_TASK_NAME constant as the argument. We also call the TaskManager.unregisterAllTasksAsync function to unregister all tasks that have been registered by the app. This ensures that the background location task is properly closed and will no longer run in the background.

Note that it's important to unregister all tasks, not just the background location task, to avoid any conflicts or issues with other tasks that may be running in the app.

**Comment by qaezrun** [comment]
does this work @marc-wittwer ?

**Comment by ssommelet21** [comment]
From documentation :

Location.**stopLocationUpdatesAsync**(taskName)
Parameter	Type	Description
taskName	string	
Name of the background location task to stop.


Stops geofencing for specified task.

Returns:
Promise<void>
**A promise resolving as soon as the task is unregistered.**

------

TaskManager.**unregisterTaskAsync**(taskName)
Parameter	Type	Description
taskName	string	
Name of the task to unregister.


Unregisters task from the app, so the app will not be receiving updates for that task anymore. It is recommended to use methods specialized by modules that registered the task, eg. Location.stopLocationUpdatesAsync.

Returns:
Promise<void>
**A promise which fulfills as soon as the task is unregistered.**

------

So we don't need unregisterTaskAsync or  TaskManager.unregisterAllTasksAsync() just using **stopLocationUpdatesAsync**

If the stopLocationUpdatesAsync" doesn't stop background GPS task this is an emulator issue
