### ISSUE TITLE
The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo). 

### ISSUE THREAD

**Issue by Samsonroyal** [expo/expo#21026]
### Summary

I installed an expo project, ran all the necessary commands, `npm install --global expo-cli` then `npm install` and finally went ahead to use the `expo start` command expecting my project to start and show me a dev preview on localhost; however, I instead received an error message as illustrated herein.
![image](https://user-images.githubusercontent.com/26835888/215921867-f950c4ad-452a-44dc-93ac-097dff28255b.png)

### What platform(s) does this occur on?

Android, Web

### SDK Version

44.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 32.0.0
        System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
        Android NDK: 23.0.7344513-beta4
    npmPackages:
      expo: ~44.0.0 => 44.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Minimal reproducible example

[minimalcode.zip](https://github.com/expo/expo/files/10552477/minimalcode.zip)
I have attached a reproducible zipped folder,
Download, Run the global installation command of expo, `npm install --global expo-cli`  then run` Npm install`

**Comment by JRCP2709** [comment]
This command is being executed with the global Expo CLI. Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
To use the local CLI instead (recommended in SDK 46 and higher), run:
› npx expo start

**Comment by Samsonroyal** [comment]
I completely failed to run `npx run expo.` It displays the same error over again. 
is there an option to migrate to sdk 46?

**Comment by Samsonroyal** [comment]
hello @larrykings I downgraded my node version and successfully was able to run `expo start`. Thanks for help rendered.

**Comment by nehagingade** [comment]
@larrykings I'm not able to open the link and my node version is upto date.

**Comment by larrykings** [comment]
@nehagingade check your node version * node --version * if it above 17 downgrade the node version to below 16. You can install Node version manage (nvm) use this command to switch any version of node you want to use * nvm use 16*

**Comment by jeff254-kedjango** [comment]
@larrykings very helpful. Thanks a lot!

**Comment by gupp41** [comment]
Should apps like this always be run in venv so that these kinds of problems don't occur?

**Comment by fredahoussi** [comment]
Remove lasted version and install node@16.20.0

**Comment by OrozcoCR** [comment]
@fredahoussi how i can do it?

**Comment by fredahoussi** [comment]
> @fredahoussi how i can do it?
> 

Uninstall your node version and install node@16. On this link https://nodejs.org/download/release/v16.20.0/

**Comment by ThinhDangHCMUT** [comment]
In macOS use can use brew to install nvm and use nvm to downgrade node version. You also switch between version. Try this: https://tecadmin.net/install-nvm-macos-with-homebrew/

**Comment by Kibuye24** [comment]
I find downgrading node a bit much since you might need node's LTS version for other projects or frameworks. `npx expo start` solves the problem.

**Comment by fyusuf-a** [comment]
```bash
sudo npm install -g create-expo-app
create-expo-app --template
```
fixed it for me.

**Comment by jeffngugi** [comment]
Use nvm to have multiple node versions in your laptop. I am using M1, then you can switch to 16.x.x when working expo projects

**Comment by JeremiahDunphy** [comment]
@Samsonroyal If its a new project I would reccomend just running: 

`npx expo upgrade `

To update your expo to the latest version and use npx expo start.

**Comment by shamashan** [comment]
All you need to use `npm install --force` this solved the problem for me.

**Comment by Samsonroyal** [comment]
> Should apps like this always be run in venv so that these kinds of problems don't occur?

@shamashan kindly elaborate more on this

**Comment by Samsonroyal** [comment]
> @Samsonroyal If its a new project I would reccomend just running:
> 
> `npx expo upgrade `
> 
> To update your expo to the latest version and use npx expo start.

Thanks for the advice; but the problem was solved.

**Comment by JeremiahDunphy** [comment]
> > @Samsonroyal If its a new project I would reccomend just running:
> > `npx expo upgrade `
> > To update your expo to the latest version and use npx expo start.
> 
> Thanks for the advice; but the problem was solved.

How did you fix it?

**Comment by reket808** [comment]
add npx to expo sample: expo install react-native-gesture-handler
                                           npx expo install react-native-gesture-handler
