### ISSUE TITLE
Expo build error

### ISSUE THREAD

**Issue by viniciusgarreto** [expo/expo#21028]
### Summary

After update expo with expo-upgrade and try to build with `eas build --platform` android got the following error:

Running 'gradlew :app:bundleRelease' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-7.5.1-all.zip
10%.
20%.
30%.
40%
50%.
60%
70%
80%.
90%
100%
Welcome to Gradle 7.5.1!
Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
- Improved diagnostics for dependency resolution
For more details see https://docs.gradle.org/7.5.1/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
> Task :react-native-gradle-plugin:pluginDescriptors
> Task :react-native-gradle-plugin:processResources
> Task :react-native-gradle-plugin:compileKotlin
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:classes
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:jar
[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/node_modules/@unimodules/core/android/build.gradle' line: 2
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':unimodules-core'.
[stderr] > Plugin with id 'maven' not found.
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] >
[stderr] Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] 2: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':expo'.
[stderr] > compileSdkVersion is not specified. Please add it to build.gradle
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] * Get more help at
[stderr] https://help.gradle.org
[stderr] BUILD FAILED in 1m 21s
5 actionable tasks: 5 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### What platform(s) does this occur on?

Android

### Environment

    npmPackages:
      expo: ^47.0.0 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: https://github.com/expo/react-native/archive/sdk-47.0.0.tar.gz => 0.70.3
      react-native-web: ~0.18.7 => 0.18.12
    Expo Workflow: managed

### Minimal reproducible example

eas build --platform

**Comment by Simek** [comment]
Hello @viniciusgarreto, it looks like you have a dependency which is no longer compatible with the newest SDK, because it depends on deprecated Unimodules:
* https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc

I would recommend running `expo-cli doctor` and apply required updates listed there (if any), but the problem might also originate from the 3rd-party library, then you will need to find and update it manually.
