### ISSUE TITLE
Web Build issue on docker

### ISSUE THREAD

**Issue by ferhatsahin** [expo/expo#21035]
### Summary
Strangely, in linux yarn install, installs the latest version of @expo/webpack-config which is currently 0.18.1
![image](https://user-images.githubusercontent.com/50547939/216044562-f7593e56-5341-4009-886b-cfd686196fe0.png)
![image](https://user-images.githubusercontent.com/50547939/216030009-12541c73-1d23-44b3-96ea-5f3e689a8ec6.png)
![image](https://user-images.githubusercontent.com/50547939/216030033-a434c69b-4ddd-4795-ae66-a1c8a304ba7c.png)

@expo/webpack-config  "0.16.21" version does not have webpack5 support. but i receive error related with webpack 5.

In my local environment ( macos ) I am able to run build successfully.

### What platform(s) does this occur on?

Web

### SDK Version

45

### Environment

System:
      OS: macOS 11.7.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2023.01.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 31
        Build Tools: 29.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.16.21 => 0.16.21 
      expo: 45.0.0 => 45.0.0 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

here is my production related webpack configuration.

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const CompressionPlugin = require('compression-webpack-plugin');

module.exports = async function (ENV, argv) {
  const config = await createExpoWebpackConfigAsync(ENV, argv);
  
  if (config.mode === 'development') {
     // dev mode related configuration like hot-reload, proxying etc.
  }

  if (config.mode === 'production') {
    config.optimization = { namedModules: true, splitChunks: { cacheGroups: { default: false } } };
    config.plugins.push(
      new CompressionPlugin({
        algorithm: 'gzip',
      })
    );
  }

  // Customize the config before returning it.
  return config;
};

```

When you run `expo build:web` command on linux ( docker image ) 

I am receiving this error related with webpack 5.

`[11:09:00] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node should be one of these:
   false | object { __dirname?, __filename?, global? }
   -> Include polyfills or mocks for various node stuff.
   Details:
    * configuration.node has an unknown property 'module'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dgram'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dns'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'fs'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'http2'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'net'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'tls'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'child_process'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
 - configuration.optimization has an unknown property 'namedModules'. These properties are valid:
   object { checkWasmTypes?, chunkIds?, concatenateModules?, emitOnErrors?, flagIncludedChunks?, innerGraph?, mangleExports?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, noEmitOnErrors?, nodeEnv?, portableRecords?, providedExports?, realContentHash?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }
   -> Enables/Disables integrated optimizations.
   Did you mean optimization.moduleIds: "named" (BREAKING CHANGE since webpack 5)?
[11:09:00] ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node should be one of these:
   false | object { __dirname?, __filename?, global? }
   -> Include polyfills or mocks for various node stuff.
   Details:
    * configuration.node has an unknown property 'module'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dgram'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dns'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'fs'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'http2'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'net'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'tls'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'child_process'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
 - configuration.optimization has an unknown property 'namedModules'. These properties are valid:
   object { checkWasmTypes?, chunkIds?, concatenateModules?, emitOnErrors?, flagIncludedChunks?, innerGraph?, mangleExports?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, noEmitOnErrors?, nodeEnv?, portableRecords?, providedExports?, realContentHash?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }
   -> Enables/Disables integrated optimizations.
   Did you mean optimization.moduleIds: "named" (BREAKING CHANGE since webpack 5)?
    at validate (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/webpack.js:111:24)
    at webpack (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/webpack.js:158:32)
    at f (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/index.js:64:16)
    at bundleWebAppAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:316:27)
    at Object.bundleAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:359:9)
error Command failed with exit code 1.`

**Comment by gregfenton** [comment]
You should be using `npx expo install ...` instead of `yarn install ....`.  This gives Expo the chance to pick the version of the module you are adding based on the Expo SDK version you are using.  If Expo doesn't know the module you are installing then the command will end up calling `yarn install ....` without specifying a version, so you'll end up with the same results as if you called `yarn` yourself ; but if Expo does know of the module you are installing then it will install the version of the module that is compatible with the version of the SDK.

**Comment by EvanBacon** [comment]
The Webpack issues appear to be related to using outdated config settings with Webpack 5. You can change the version of Webpack down to 4 if needed, I recommend updating the custom configuration though.
