### ISSUE TITLE
expo-localization doesn't return currency

### ISSUE THREAD

**Issue by vault79** [expo/expo#21041]
### Summary
expo-localization returns `null` as `currencyCode` even though app run on iOS simulator.

## Repro steps
1. Launch iOS simulator
2. Mouse over [Device] menu -> [Erase All Content and Settings...] to clean up simulator **<- This is important step.**
3. After restarting iOS simulator, install your app. In my env, I use dev-client.
4. `expo start --dev-client` to start app in your terminal
5. Type `i` to launch app on iOS simulator

## Actual behavior
expo-localization `getLocales` method returns incorrect currency information on iOS device simulator.

```json
[{"currencyCode": null, "currencySymbol": "¤", "decimalSeparator": ".", "digitGroupingSeparator": ",", "languageCode": "en", "languageTag": "en", "measurementSystem": "us", "regionCode": null, "textDirection": "ltr"}]
```

## Expected behavior
expo-localization `getLocales` method returns correct information
```json
 [{"currencyCode": "USD", "currencySymbol": "$", "decimalSeparator": ".", "digitGroupingSeparator": ",", "languageCode": "en", "languageTag": "en-US", "measurementSystem": "us", "regionCode": "US", "textDirection": "ltr"}]
```

## Workaround
1. On iOS simulator tap [Settings]->[General]->[Language & Region]->[Region]
2. Select another region (ex. Japan => Tap [Change to Japan]
3. Tap [Region] -> Select "United States" => Tap [Change to United States]
4. Back to iOS simulator home.
5. `expo start --dev-client` to start app in your terminal
6. Type `i` to launch app on iOS simulator

TBH, I'm not sure whether it is iOS simulator's issue or expo-localization's issue.. 

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      npm: 8.13.1 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.4.1
      expo-cli: 6.1.0
    Expo Workflow: managed

### Minimal reproducible example

```typescript
import { getLocales } from 'expo-localization';

console.log(getLocales());
```

**Comment by aleqsio** [comment]
Thanks for the report!

Pretty sure that it's a simulator quirk - we're reading it from the same object as all the other properties.
