### ISSUE TITLE
[expo-screen-orientation] ScreenOrientation.lockPlatformAsync does not work on iOS 16

### ISSUE THREAD

**Issue by lordprana** [expo/expo#21044]
### Summary

The ios/EXScreenOrientation/EXScreenOrientationRegistry.m file in the `enforceDesiredDeviceOrientationWithOrientationMask` function calls '[[UIDevice currentDevice] setValue:@(newOrientation) forKey:@"orientation"];' This function has been deprecated in iOS 16, as mentioned here https://developer.apple.com/forums/thread/707735. This results in not being able to perform a screen rotation on my iOS 16 Iphone device. I am able to perform a screen rotation with the same code on iOS <= 15 and Android.

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.3 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - ~/.npm-global/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.7 => 0.69.7
      react-native-web: ~0.18.7 => 0.18.10
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

https://snack.expo.dev/@matthewgaba/expo-screenorientation

Run this in an iOS simulator on iOS 16+ and you will see that the screen rotation does not work.

**Comment by robertcreaner** [comment]
Also experiencing this issue

**Comment by seba9999** [comment]
Same issue here 👍

**Comment by lordprana** [comment]
I've been trying to patch this, and it looks like my original identification of the issue is not correct. This is a bug, and my original post does identify an issue with the code, but I believe there is also another problem that is causing the screen not to rotate. I will let the maintainers fix it, as this native iOS code is over my head.

**Comment by yohamta** [comment]
Same here.

**Comment by lordprana** [comment]
Any update? Inability to control screen rotation on iOS 16 in Expo seems like it would be a high-priority issue to fix.

**Comment by behenate** [comment]
Hi, we are switching to new iOS orientation API in this PR https://github.com/expo/expo/pull/22152, it should fix the issue

**Comment by amit13091992** [comment]
how much more time it will take to fix the issue?

Thanks & regards,
Amit Kumar Pandya
M no. +91-9177302468
React Native Developer

**Comment by behenate** [comment]
@amit13091992 This fix will be included in SDK 49

**Comment by lordprana** [comment]
Orientation lock is not working. I am on version 6.0.0-beta.1 of expo-screen-orientation. I have this code in my App.js.

useEffect(() => {
    (async () => {
      if (isTablet) {
        ScreenOrientation.lockPlatformAsync({
          screenOrientationArrayIOS: [
            ScreenOrientation.Orientation.PORTRAIT_UP,
            ScreenOrientation.Orientation.LANDSCAPE_LEFT,
            ScreenOrientation.Orientation.LANDSCAPE_RIGHT,
          ],
          screenOrientationConstantAndroid: 4, // Use sensor for all four directions
        })
      } else {
        console.log('Locking orientation')
        ScreenOrientation.lockPlatformAsync({
          screenOrientationArrayIOS: [
            ScreenOrientation.Orientation.PORTRAIT_UP,
          ],
          screenOrientationConstantAndroid: 1, // Lock in portrait
        })
      }
    })()
  }, [isTablet])

Locking orientation is being printed, so the function is being called. I am on a mobile device. However, when I rotate the device, the screen rotates to landscape and does not stay locked in portrait.

**Comment by behenate** [comment]
@lordprana What expo version are you using?

**Comment by lordprana** [comment]
@behenate I'm on SDK 48. Bare workflow. I'm going to create a minimum reproducible example...

**Comment by behenate** [comment]
@lordprana Try this before making the example  https://github.com/expo/expo/pull/22152#issuecomment-1596233940

**Comment by lordprana** [comment]
I added the line from that PR...still not working. In my code I have the following lines:

 await ScreenOrientation.lockPlatformAsync({
          screenOrientationArrayIOS: [
            ScreenOrientation.Orientation.PORTRAIT_UP,
          ],
          screenOrientationConstantAndroid: 1, // Lock in portrait
        })
        console.log((await ScreenOrientation.getPlatformOrientationLockAsync()))

Here is what is printed:

Object {
  "screenOrientationArrayIOS": Array [
    1,
    2,
    3,
    4,
  ],
}

It seems for some reason, the orientation lock is not being set. 

I tried to make a minimum reproducible example on a Snack on Expo 47, and it seems to be working correctly. I'm not sure what it is about my project that could be causing the platform lock to not register.

**Comment by behenate** [comment]
@lordprana Can you try upgrading to SDK 49 and checking if the code works? I tried your code on SDK 49 project and couldn't reproduce the issue

**Comment by lordprana** [comment]
@behenate I upgraded to SDK 49. I am having the same issue. I'd appreciate your assistance in debugging. For now, no lock is being applied--the screen can rotate in any direction.

I'd like to reiterate that this was working for me on iOS before iOS 16 was released on previous versions of Expo. Now, it is not working on iOS <16 either.

Here are my project dependencies. Perhaps there is a conflict you may be able to recognize? 
```"dependencies": {
    "@craftzdog/react-native-buffer": "^6.0.5",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/hooks": "^2.8.1",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-firebase/analytics": "^18.1.0",
    "@react-native-firebase/app": "~18.1.0",
    "@react-navigation/native": "6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "6.3.16",
    "@reduxjs/toolkit": "^1.7.1",
    "@sentry-internal/tracing": "^7.58.1",
    "@sentry/core": "7.55.2",
    "@sentry/react-native": "5.5.0",
    "@testing-library/user-event": "^13.5.0",
    "base-64": "^1.0.0",
    "deep-equal": "^2.2.0",
    "expo": "^49.0.0",
    "expo-application": "~5.3.0",
    "expo-asset": "~8.10.1",
    "expo-av": "~13.4.1",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.6",
    "expo-device": "~5.4.0",
    "expo-file-system": "~15.4.2",
    "expo-font": "~11.4.0",
    "expo-keep-awake": "~12.3.0",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-modules-core": "~1.5.7",
    "expo-navigation-bar": "~2.3.0",
    "expo-notifications": "~0.20.1",
    "expo-screen-orientation": "~6.0.3",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-task-manager": "~11.3.0",
    "expo-updates": "~0.18.10",
    "jest": "^29.2.1",
    "lodash": "^4.17.21",
    "lottie-ios": "3.4.0",
    "lottie-react-native": "5.1.6",
    "moment": "^2.29.1",
    "patch-package": "^6.5.0",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",
    "react-native-appstate-hook": "^1.0.6",
    "react-native-autocomplete-dropdown": "^2.1.0",
    "react-native-background-timer": "^2.4.1",
    "react-native-blob-util": "^0.17.2",
    "react-native-countdown-circle-timer": "^3.0.9",
    "react-native-expo-viewport-units": "^0.0.8",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-localize": "^2.2.1",
    "react-native-material-textfield": "^0.16.1",
    "react-native-paper": "^4.11.2",
    "react-native-reanimated": "~3.3.0",
    "react-native-reanimated-carousel": "^3.4.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-scalable-image": "https://github.com/lordprana/react-native-scalable-image.git",
    "react-native-screens": "~3.22.0",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "13.9.0",
    "react-native-system-navigation-bar": "^2.2.0",
    "react-native-three-dots-loader": "https://github.com/lordprana/react-native-three-dots-loader.git",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-video": "6.0.0-alpha.6",
    "react-native-video-controls": "https://github.com/lordprana/react-native-video-controls.git",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.2.2",
    "react-redux": "^7.2.6",
    "rn-tooltip": "^3.0.3",
    "semver-compare": "^1.0.0",
    "sentry-expo": "~7.0.0",
    "victory-native": "^36.6.11",
    "wav-headers": "^1.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.22.8",
    "@babel/eslint-parser": "^7.16.5",
    "@testing-library/jest-native": "^5.1.2",
    "@testing-library/react-native": "^11.0.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^29.3.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "eslint": "^8.8.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jest": "^26.0.0",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.28.0",
    "jest-expo": "^47.0.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-test-renderer": "^18.2.0"
  },
  "resolutions": {
    "react-devtools-core": "4.25.0",
    "expo-modules-core": "1.2.4",
    "@jest/create-cache-key-function": "^27.0.1"
  },```

**Comment by brentvatne** [comment]
@lordprana - could you help by providing a minimal reproducible example? you can try removing dependencies and code until you're able to narrow it down. https://expo.fyi/manual-debugging

**Comment by lordprana** [comment]
I never debugged this issue...it was easier for me to change libraries. If anyone else is still having issues with this library, you can use react-native-orientation library and apply the fixes found at https://github.com/yamill/react-native-orientation/issues/411.

**Comment by Wenceslauu** [comment]
Any news on this?

**Comment by behenate** [comment]
@Wenceslauu This should be fixed since SDK 49, if you are still having problems please open a new issue with a minimal reproducible example.

**Comment by Wenceslauu** [comment]
The only screen that is not respecting the orientation is the presentation="modal" screen from react navigation, maybe there is a conflict between both?

**Comment by behenate** [comment]
@Wenceslauu That's possible, we are doing some integration with `RNScreens` in `screen-orientation`, this might be a case that we didn't handle 🧐 . Would you mind opening an issue so we can keep track of it? I can't really reopen this issue as yours is different
