### ISSUE TITLE
[Bare workflow] EXAppDelegateWrapper not compatible with RN 0.71

### ISSUE THREAD

**Issue by robrechtme** [expo/expo#21042]
### Summary

Hi! I'm trying to upgrade a bare + Expo modules app to RN 0.71.

According to the [Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.RN%200.71), I need to modify my `AppDelegate.h` like this:

```diff
-#import <React/RCTBridgeDelegate.h>
+#import <RCTAppDelegate.h>
 #import <UIKit/UIKit.h>
-@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>
+@interface AppDelegate : RCTAppDelegate
-@property (nonatomic, strong) UIWindow *window;
 @end
```

Because I use Expo modules, my `AppDelegate.h` looks like this: 

```obj-c
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
#import <Expo/Expo.h>
@interface AppDelegate : EXAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate>
@property (nonatomic, strong) UIWindow *window;
@end
```

How can I upgrade to RN 0.71 while still using expo modules? It seems like the [bare workflow docs](https://docs.expo.dev/bare/installing-expo-modules/) aren't up to date with RN 0.71. I removed the `EXAppDelegateWrapper` entirely, and the app builds, but I'm not sure if that's the right way to do it?

```obj-c
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import <Expo/Expo.h>

@interface AppDelegate : RCTAppDelegate 
@end
```

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.asdf/installs/nodejs/18.13.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/shims/yarn
      npm: 8.19.3 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/robrechtme/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: 47.0.13 => 47.0.13
      react: 18.2.0 => 18.2.0
      react-native: 0.71.1 => 0.71.1
    Expo Workflow: bare

### Minimal reproducible example

Try to add Expo modules to a clean RN 0.71 app.

**Comment by radko93** [comment]
My `AppDelegrate.h` that compiles:

```
#import <UIKit/UIKit.h>
#import <Expo/Expo.h>

@interface AppDelegate : EXAppDelegateWrapper

@end
```

**Comment by SergiiPodlishchuk** [comment]
@radko93 can you show your AppDelegete.mm and Podfile file with exported Expo, please.
I'm try to upgrade to latest RN_0.71.1 and with Android everything OK, but iOS is failed

**Comment by Kudo** [comment]
@SergiiPodlishchuk you could also try install-expo-modules

```sh
$ npx react-native init RN071 --version 0.71
$ cd RN071
$ git init
$ git add .
$ git commit -m "init"
$ npx install-expo-modules@latest
$ git diff -- ios/
```

basically, from a bare 0.71 react native project, only AppDelegate.h needs to be changed.
sorry the doc is not updated, we will work on it after sdk 48 released.

**Comment by SergiiPodlishchuk** [comment]
Thanks, I'll try.

**Comment by robrechtme** [comment]
Thanks @radko93! This one seems to do the trick

```obj-c
#import <UIKit/UIKit.h>
#import <Expo/Expo.h>

@interface AppDelegate : EXAppDelegateWrapper

@end
```

**Comment by coolersham** [comment]
@robrechtme are you still able to rotate your device to use landscape mode and vice versa after using `EXAppDelegateWrapper` instead of `RCTAppDelegate`? 
I am on `expo 48 beta.0` and no longer able to do that.

**Comment by webdiego** [comment]
Unable to build
