### ISSUE TITLE
Unable to stay logged into multiple Expo Dev Clients on a single Device with an Expo account that has 2-factor authentication

### ISSUE THREAD

**Issue by kartikk221** [expo/expo#21048]
### Summary

I currently maintain two React Native applications built with Expo. 
To work on these applications, I use Expo Dev Clients as my apps utilize native packages such as Reanimated. 
Since I also use EAS Updates to push OTA updates to my applications, I like to be able to test my EAS Update builds by being logged into the dev clients with my Expo account.

The problem is that whenever I try to sign into more than one dev client (Different bundle identifiers ofc), I end up getting logged out of the other one.

Essentially I can only be logged into one dev client at a time with my Expo account.

I am not sure If this is intended behavior but it can be very tedious to constantly have to re-login to my Expo account in dev clients whenever I have to switch development workflows, especially because I use 2-factor authentication on my Expo account.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "~2.0.0"
"expo-updates": "^0.15.6"

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
      npm: 9.3.0 - ~/Desktop/supply-app/supply-app/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.4.0
      expo-cli: 6.1.0
    Expo Workflow: managed

### Reproducible demo

1. Install two Expo Dev Clients with different bundle identifiers aka. different projects on a device (In my case it was iPhone 14 Pro).
2. Login with an Expo account which has two-factor authentication on one of the dev clients and close this dev client.
3. Login with the same Expo account on the other dev client and close this dev client.
4. Open the original / first dev client and you will notice that you have been logged out of the Expo account.
5. You can now login to this dev client again and close it, then go to the other dev client and notice the same behavior which is that only one dev client can retain an Expo session.

**Comment by kartikk221** [comment]
Is there any more information I could provide to resolve this issue? This is seriously hurting my team's productivity.

**Comment by kartikk221** [comment]
@brentvatne I am not sure what minimal reproducible example would be eligible here. As stated in the steps, you can literally create two new expo create apps, build them using EAS Build, install them on a simulator or device. Log into one of them with an Expo account, log into the other with the same Expo account and when you go back to the first app, you will notice you have been signed out.

This is very likely a server-side issue which is limiting the number of Expo Dev client sessions allowed for an account because I don't see how two different Dev Clients can mess with each other's data hence It doesn't seem likely the Expo Dev Client code itself is broken.

**Comment by daledesilva** [comment]
I have a similar issue, except I only have one Expo account set up and I'm only launching the same app over and over. Yet it still requires me to log in each time. It's no longer asking me whether to use the same login every time or not (which it used to do). 

Tried uninstalling and expo go and reinstall.
Tried checking the default app settings in settings for EAS and expo go.
Tried uninstall the EAS app / shortcut.

No luck

**Comment by daledesilva** [comment]
Update, I have a few branches for the app and I just noticed when I build another branch it doesn't ask me, but it does auto launch without requiring login or selection of server. So I suspect it's to do with the name or bundle identifier being used already for one app and thus not able to auto load the other.

I don't know that that's it, and I'm pretty sure they are different between the branches, but it feels like it's something to do with that.
