### ISSUE TITLE
Could expo cherrypick this commit on TextInput for React Native?

### ISSUE THREAD

**Issue by lichenglu** [expo/expo#2104]
There is a bug for `TextInput` in react native (RN) when typing Chinese/Japanese using Apple's native keyboard: see https://github.com/facebook/react-native/issues/18403.

The issue was fixed by this commit https://github.com/facebook/react-native/commit/892212bad2daadd373f4be241e4cd9889b0a1005, however, it is not included in expo's fork of RN. 

Although there are workarounds for the issue, it would be the best if the official fix is included directly? 

Sorry if this is not the place I should post this issue. Thank you in advance!

**Comment by ken0x0a** [comment]
I tried to cherry-pick this commit, but not worked on expo App on iOS.

So, just for now, doing like follows

```tsx
import React from 'react'
import { TextInput as TextInput_, TextInputProps } from 'react-native'

export default class TextInput extends React.Component<TextInputProps, any> {
  static defaultProps = { value: '' }

  shouldComponentUpdate(nextProps: any, _nextState: any) {
    if (nextProps.value === '') return true
    if (this.props.value !== nextProps.value) return false

    return true
  }

  render() {
    return <TextInput_ {...this.props} />
  }
}
``` 

:(

**Comment by Xaber20110202** [comment]
```
import * as React from 'react'
import { TextInput } from 'react-native'
import { isiOS } from 'utils/platform'

// Temporarily fix react-native 0.54-0.56 textInput can't input Chinese bug
// https://github.com/facebook/react-native/issues/18403
export default class RewrittenTextInput extends React.PureComponent<any> {
  tempText = ''

  onChangeText = text => {
    this.tempText = text
  }
  onBlur = () => {
    const { onChangeText, onBlur } = this.props
    if (onChangeText) {
      onChangeText(this.tempText)
    }
    if (onBlur) {
      onBlur()
    }
  }

  render() {
    const { onChangeText, onBlur, ...rest } = this.props

    return isiOS ? <TextInput
      onChangeText={this.onChangeText}
      onBlur={this.onBlur}
      {...rest}
    /> : <TextInput {...this.props} />
  }
}
```
Use RewrittenTextInput to replace TextInput if necessary

**Comment by ide** [comment]
We are looking to include that patch in SDK 30. This is a risky patch that depends on a chain of commits but the issue is probably in the top 5% worth fixing so we have the commits pulled into the SDK 30 copy of RN.

**Comment by townmulti** [comment]
@ide this issue ([https://github.com/facebook/react-native/issues/19389](https://github.com/facebook/react-native/issues/19389)) is very similar. It has to do with TextInput as well. It is possible that it can be cherry picked? Or did it come along with Chinese/Japanese fix?

**Comment by ide** [comment]
SDK 30 has already shipped and cherry-picks are over. That commit was not included. If we update RN in the next release, that commit will come along with it.
