### ISSUE TITLE
Using name "Dispatch" in app.json with eas build -p ios fails. A different name on same project creates the build with no error.

### ISSUE THREAD

**Issue by sardarwaseemjaved** [expo/expo#21053]
### Build/Submit details page URL

https://expo.dev/accounts/dispatch-inc/projects/dispatch-mobile-app/builds/8365d82e-98a8-4058-b379-1d9fc4417d8a

### Summary

When I name my app "dispatch." and run EAS Build, it creates a build but when I use the same code and only change app name to "Dispatch" in app.json and try to create a build with eas-cli it fails on Run Fastlane step.

P.S. In my opinion the "Dispatch" module in expo-modules-core/iOS/AppDelegate ExpoAppDelegate.swift line#2 might be creating a conflict with the app name and causing the build to fail.

### Managed or bare?

Managed

### Environment

 **expo-env-info 1.0.5 environment info:**
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.20 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 3.4.1
      expo-cli: 5.4.12
    Expo Workflow: managed
    
    
✔ Found all copies of expo-modules-autolinking
  All copies of expo-modules-autolinking satisfy ~0.10.1
✔ Found all copies of @expo/config-plugins
  All copies of @expo/config-plugins satisfy ^5.0.0
✔ Found all copies of @expo/prebuild-config
  All copies of @expo/prebuild-config satisfy ^5.0.1

🎉 Didn't find any issues with the project!
    

### Error output

758
› Executing expo-updates Pods/EXUpdates » Copy generated compatibility header
759
› Compiling Pods/Pods-Dispatch » Pods-Dispatch-dummy.m
760
› Packaging Pods/Pods-Dispatch » libPods-Dispatch.a
761
› Executing Dispatch » [CP] Check Pods Manifest.lock
762
› Executing Dispatch » Start Packager on http://localhost:8081
763
› Compiling Dispatch » ExpoModulesProvider.swift
764

❌  (ios/Pods/Target Support Files/Pods-Dispatch/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
**>  8 | import ExpoModulesCore
     |        ^ circular dependency between modules 'Dispatch' and 'ExpoModulesCore'**
   9 | import EASClient
  10 | import ExpoImagePicker
  11 | import ExpoKeepAwake
765
› Compiling Dispatch » noop-file.swift
766

❌  (ios/Pods/Target Support Files/Pods-Dispatch/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ circular dependency between modules 'Dispatch' and 'ExpoModulesCore'
   9 | import EASClient
  10 | import ExpoImagePicker
  11 | import ExpoKeepAwake
767

❌  (ios/Pods/Target Support Files/Pods-Dispatch/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ circular dependency between modules 'Dispatch' and 'ExpoModulesCore'
   9 | import EASClient
  10 | import ExpoImagePicker
  11 | import ExpoKeepAwake
768

❌  error: emit-module command failed with exit code 1 (use -v to see invocation)

769
▸ ** ARCHIVE FAILED **
770
▸ The following build commands failed:
771
▸ 	CompileSwift normal arm64 /Users/expo/workingdir/build/ios/Pods/Target\ Support\ Files/Pods-Dispatch/ExpoModulesProvider.swift (in target 'Dispatch' from project 'Dispatch')
772
▸ 	CompileSwift normal arm64 /Users/expo/workingdir/build/ios/Dispatch/noop-file.swift (in target 'Dispatch' from project 'Dispatch')
773
▸ 	EmitSwiftModule normal arm64 (in target 'Dispatch' from project 'Dispatch')
774
▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Dispatch' from project 'Dispatch')
775
▸ (4 failures)
776
2023-02-01 00:28:22.571 xcodebuild[4453:12614] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
777
2023-02-01 00:28:22.571 xcodebuild[4453:12614] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
778
2023-02-01 00:28:22.604 xcodebuild[4453:12614] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
779
2023-02-01 00:28:22.605 xcodebuild[4453:12614] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
780
2023-02-01 00:28:22.605 xcodebuild[4453:12614] XType: unable to make a connection to the font daemon!
781
2023-02-01 00:28:22.605 xcodebuild[4453:12614] XType: XTFontStaticRegistry is enabled as fontd is not available.
782
** ARCHIVE FAILED **
783
784
785
The following build commands failed:
786
	CompileSwift normal arm64 /Users/expo/workingdir/build/ios/Pods/Target\ Support\ Files/Pods-Dispatch/ExpoModulesProvider.swift (in target 'Dispatch' from project 'Dispatch')
787
	CompileSwift normal arm64 /Users/expo/workingdir/build/ios/Dispatch/noop-file.swift (in target 'Dispatch' from project 'Dispatch')
788
	EmitSwiftModule normal arm64 (in target 'Dispatch' from project 'Dispatch')
789
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Dispatch' from project 'Dispatch')
790
(4 failures)
791
Exit status: 65
792
793
+-------------+-------------------------+
794
|           Build environment           |
795
+-------------+-------------------------+
796
| xcode_path  | /Applications/Xcode.app |
797
| gym_version | 2.206.1                 |
798
| sdk         | iPhoneOS15.5.sdk        |
799
+-------------+-------------------------+
800
Looks like fastlane ran into a build/archive error with your project
801
It's hard to tell what's causing the error, so we wrote some guides on how
802
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
803
Before submitting an issue on GitHub, please follow the guide above and make
804
sure your project is set up correctly.
805
fastlane uses `xcodebuild` commands to generate your binary, you can see the
806
the full commands printed out in yellow in the above log.
807
Make sure to inspect the output above, as usually you'll find more error information there
808
809
[stderr] [!] Error building the application - see the log above
810
Error: Fastlane build failed with unknown error. See logs for the "Run fastlane" and "Xcode Logs" phases for more information.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.

### Reproducible demo or steps to reproduce from a blank project

1. Create a blank project
2. Use name "Dispatch" as app name in app.json **(This is the reason behind build fail)**
3. configure other required app.json properties for IOS these are not causing the issue.
4. create iOS build with EAS CLI

**Comment by grahamplace** [comment]
It appears I'm having the same issue, but with an app named `Foundation` 🙃 At least I'm not crazy
