### ISSUE TITLE
eas build --platform ios --local Failing in M1 Pro xCode 14.2

### ISSUE THREAD

**Issue by fpiantoni** [expo/expo#21066]
### Summary

Builing locally fails, while investigating the logs i found this:

error: Provisioning profile "*[expo] XXX AppStore 2023-01-17T19:29:53.926Z" doesn't include signing certificate "Apple Distribution: XXX (XXX)". (in target 'XXX' from project 'XXX')

### What platform(s) does this occur on?

iOS

### Environment

macOS Monterey m1 Pro 
xCode 14.2

### Minimal reproducible example

error: Provisioning profile "*[expo] XXX AppStore 2023-01-17T19:29:53.926Z" doesn't include signing certificate "Apple Distribution: XXX (XXX)". (in target 'XXX' from project 'XXX')

**Comment by brentvatne** [comment]
hi there!

i'd suggest looking in the forums for folks who encountered a similar error, eg: https://forums.expo.dev/t/error-provisioning-profile-expo-xxxadhoc-1657297990071-doesnt-include-signing-certificate-apple-distribution-xxx/64965/2
