### ISSUE TITLE
MediaLibrary Album asset array is not up to date immediately after new photo was added on Android

### ISSUE THREAD

**Issue by felsd** [expo/expo#2106]
I created a thread on the expo.io forums already, @AdamJNavarro could reproduce the issue on an Galaxy S8 but not on an iPhone 7 so this seems to be an Android bug:
[MediaLibrary Album asset array is not up to date immediately after new photo was added](https://forums.expo.io/t/medialibrary-album-asset-array-is-not-up-to-date-immediately-after-new-photo-was-added/)

### Environment
OnePlus 3 with Android 8.0.0 and OxygenOS 5.0.4

### Steps to Reproduce
1. Take a photo using `ImagePicker.launchCameraAsync({})`
2. Move it into a gallery using `MediaLibrary`
4. Load the most recent picture from the gallery
3. Display the picture inside the app

### Expected Behavior
The photo I have just taken shows up inside the app

### Actual Behavior
* photo #1: correct picture is displayed (if the gallery was just created, otherwise the newest picture before photo #1 shows up)

* photo #2: photo #1 shows up

* photo #3: photo #2 shows up

* and so forth

### Reproducible Demo
I have created a snack for reproducing that behaviour:
[https://snack.expo.io/H1Jdiik8X](https://snack.expo.io/H1Jdiik8X)

**Comment by felsd** [comment]
Little update:
If I use `createAlbumAsync` also if the album already exists, everything works as intended.

**Comment by sjchmiela** [comment]
Fixed in SDK31! 🎉
