### ISSUE TITLE
constants debugMode on android return undefined

### ISSUE THREAD

**Issue by grinisoufyane** [expo/expo#21077]
### Summary

constants debugMode on android return undefined but work just fine on ios

### What platform(s) does this occur on?

Android

### Environment

"expo": "~46.0.9",
"expo-constants": "~13.2.4",

### Minimal reproducible example

export const BASE_URL = Constants.debugMode
  ? APP_DEBUG_BASE_URL
  : APP_RELEASE_BASE_URL;

**Comment by DriesCruyskens** [comment]
@grinisoufyane Did you find a solution for this?
