### ISSUE TITLE
`npx expo start` silently failing on network issues

### ISSUE THREAD

**Issue by yatessss** [expo/expo#21074]
### Summary

When I initialize a project according to the docs (https://docs.expo.dev/get-started/create-a-new-app/), I run `npm run ios` in the project, and I get stuck here

```
>>> npm run ios

> my-app@1.0.0 ios
> expo start --ios

Starting project at /Users/xxxx/playground/my-app
```

But I use the old expo-cli tool to run it normally

```
>>> expo start --ios

This command is being executed with the global Expo CLI. Learn more.
To use the local CLI instead (recommended in SDK 46 and higher), run:
› npx expo start

Starting project at /Users/xxxx/playground/my-app
Starting Metro Bundler
› Opening exp://30.30.30.66:19000 on iPhone 13
Started Metro Bundler
```

Through the breakpoint, I found that there is no return in the program here, causing it to be stuck here

<img width="805" alt="image" src="https://user-images.githubusercontent.com/13636879/216572886-6a5df55a-b0c3-47f5-83d3-a2dd7ed4cf27.png">

### What platform(s) does this occur on?

iOS

### SDK Version

0.47.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 25, 26, 28, 30, 33
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    npmGlobalPackages:
      expo-cli: 6.2.1
    Expo Workflow: managed

### Minimal reproducible example

npx create-expo-app my-app

cd my-app

npx expo start

**Comment by EvanBacon** [comment]
Potentially a network or filesystem permission issue. To get unblocked you can use `--offline` or `EXPO_NO_CACHE` to skip this function.

**Comment by yatessss** [comment]
> 

Thanks, I restarted my computer and everything worked fine

**Comment by yatessss** [comment]
> Potentially a network or filesystem permission issue. To get unblocked you can use `--offline` or `EXPO_NO_CACHE` to skip this function.

Thanks, the above method worked for me, but not the best way

Through testing, I found that it was caused by a network problem. How to troubleshoot that a request error occurred with a url?

**Comment by EvanBacon** [comment]
@yatessss you can use [HTTP_PROXY](https://docs.expo.dev/workflow/expo-cli/#environment-variables) to proxy requests and see the results. Opening a ticket to add better fallbacks.

**Comment by yatessss** [comment]
> @yatessss you can use [HTTP_PROXY](https://docs.expo.dev/workflow/expo-cli/#environment-variables) to proxy requests and see the results. Opening a ticket to add better fallbacks.

Thank you

**Comment by EvanBacon** [comment]
fixed in https://github.com/expo/expo/pull/22961
