### ISSUE TITLE
Web Build issue

### ISSUE THREAD

**Issue by myth535** [expo/expo#21089]
### Summary

I'm getting this weird error when running build:

### What platform(s) does this occur on?

Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD  
    npmPackages:
      @expo/webpack-config: ^0.12.38 => 0.12.44       
      babel-preset-expo: ~8.0.0 => 8.0.0
      expo: 36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: 0.61.4 => 0.61.4
      react-native-web: 0.11.7 => 0.11.7
      react-navigation: 4.4.4 => 4.4.4
    Expo Workflow: bare

### Minimal reproducible example

My webpack.config.js :

`const createExpoWebpackConfigAsync = require('@expo/webpack-config')
// const {BundleAnalyzerPlugin} = require('webpack-bundle-analyzer');

module.exports = async function (env, argv) {
    const config = await createExpoWebpackConfigAsync({ ...env, offline: false }, argv)

    // Customize the config before returning it.
    if (env.mode === 'production') {
        config.output.filename = 'static/js/[name].[contenthash].js'
        config.output.chunkFilename = 'static/js/[name].[contenthash].chunk.js'
        // config.plugins.push(new BundleAnalyzerPlugin());
    }
    return config
}
`

When run "expo build:web"

`[15:58:34] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node should be one of these:
   false | object { __dirname?, __filename?, global? }
   -> Include polyfills or mocks for various node stuff.
   Details:
    * configuration.node has an unknown property 'module'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dgram'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dns'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'fs'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'http2'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'net'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'tls'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'child_process'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
[15:[58](https://gitlab.com/alldonegmbh/alldone/-/jobs/3715514813#L58):34] ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node should be one of these:
   false | object { __dirname?, __filename?, global? }
   -> Include polyfills or mocks for various node stuff.
   Details:
    * configuration.node has an unknown property 'module'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dgram'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dns'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'fs'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'http2'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'net'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'tls'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'child_process'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    at validate (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/webpack.js:111:24)
    at webpack (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/webpack.js:158:32)
    at f (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/index.js:64:16)
    at bundleWebAppAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:316:27)
    at Object.bundleAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:3[59](https://gitlab.com/alldonegmbh/alldone/-/jobs/3715514813#L59):9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-web: `expo build:web`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build-web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-04T15_58_34_2[63](https://gitlab.com/alldonegmbh/alldone/-/jobs/3715514813#L63)Z-debug.log`

The strange thing is that I did not change anything in terms of configurations or packages, yesterday it was working fine. I even tried to try to build again the last complication that had worked and doesn't work now.

This issue [(Web Build issue on docker #21035)](https://github.com/expo/expo/issues/21035) has a relatively similar error, but it doesn't exactly fit my conditions.

**Comment by EvanBacon** [comment]
Duplicate https://github.com/expo/expo-cli/issues/4639
