### ISSUE TITLE
Access to `import.meta.url` on web throws an error

### ISSUE THREAD

**Issue by dimonnwc3** [expo/expo#21099]
### Summary

Access to `import.meta.url` on expo web throws an error `import.meta is only valid inside modules.`

### What platform(s) does this occur on?

Web

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.asdf/installs/nodejs/18.13.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.13.0/.npm/bin/yarn
      npm: 9.4.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/dimonn/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.13 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.12 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.2.1
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@dimonnwc3/talking-beef-jerky

**Comment by cm-datrics** [comment]
Having this issue too when using third party libs (tamagui) that use `import.meta` in the web functionality

**Comment by JohnKing93** [comment]
I'm getting the same issue. Seems to be this line that's causing it:

`  var isRSC = process.env.ENABLE_RSC ? import.meta.env ? import.meta.env.SSR : false : false;
  exports.isRSC = isRSC;`

**Comment by andrew-bierman** [comment]
I ran into this error when using Vite + Expo with some shared components. I had to remove import.meta from any files that expo would build, and instead ended up mapping process.env values for vite to use instead, so the two apps could share files easier. 

If its helpful: https://stackoverflow.com/a/77824845/19816812

**Comment by focux** [comment]
Did anyone found a workaround for using `import.meta` on expo web?

**Comment by MJRT** [comment]
same issue +1, when I use pglite on expo-web

**Comment by jasonlewicki** [comment]
same here

**Comment by jancbeck** [comment]
I posted solution to this related issue https://github.com/expo/expo/issues/30323
