### ISSUE TITLE
takeSnapshotAsync error on real devices SDK29

### ISSUE THREAD

**Issue by AdamJNavarro** [expo/expo#2109]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please use `exp send` with exp, the “Send” button with XDE, or the "s" hotkey with create-react-native-app to send your project development URL to your phone by SMS or email.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Environment

Detached project running SDK29 with expokit 1.4.0 dependency.

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

https://snack.expo.io/@i9xp/snapshot-test provided by user Victor Wads
Related forum post here: https://forums.expo.io/t/takesnapshotasync-sdk-29-error-on-any-real-device/12489

**Comment by victorwads** [comment]
Thank You @AdamJNavarro , just adding:
Same error on Detached project running SDK29 with expokit 1.3.0 dependency.

**Comment by sjchmiela** [comment]
A fix for this behavior has just been merged into master and will be released in next SDK. I'll keep this issue open to keep track of this PR.

**Comment by sjchmiela** [comment]
Fixed in SDK 31. 🙂
