### ISSUE TITLE
Expo Go crashes when using expo-notifications

### ISSUE THREAD

**Issue by yotam-frid** [expo/expo#21095]
### Summary

Hello,

First of all thank you to the Expo team for your hard work.

I can't use `expo-notifications`. I'm developing an app with an iOS simulator, and every time I use the default import from `expo-notifications`, the app crashes with this error:

<img width="310" alt="image" src="https://user-images.githubusercontent.com/37878305/216905743-7a9852c0-622d-4622-9aa6-8731ad4c6aab.png">

This means I'm unable to develop a notifications feature in my app. 

I'm using `expo-dev-client` if it's of any significance, and the crash happens as soon as the app launches or hot reloads both on a simulator and on a physical device.

I found this issue but it seems to have been closed (even though it's still happening):
https://github.com/expo/expo/issues/15788

What can I do? I can't develop my app 🥲

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.13 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    npmGlobalPackages:
      eas-cli: 3.4.0
      expo-cli: 5.4.4
    Expo Workflow: bare

### Minimal reproducible example

```
import * as Notifications from "expo-notifications";

export async function verifyPermissionsAsync() {
  const currentPermissions = await Notifications.getPermissionsAsync();
  if (!currentPermissions.granted) {
    const { status } = await Notifications.requestPermissionsAsync();
    if (status !== "granted") {
      return false;
    }
  }

  return true;
}
```

**Comment by sokoya** [comment]
According to the docs, expo-notification does not work on simulator [https://docs.expo.dev/versions/latest/sdk/notifications/](url)

**Comment by gabrieldonadel** [comment]
Hi @yotam-frid, that error means that the native files of `expo-notifications` could not be found on your app, did you generate a new build after installing `expo-notifications`?

**Comment by nathguen** [comment]
@yotam-frid I was running to an issue where the app was crashing even when I didn't try to trigger push notifications on the simulator. Since I'm using a managed workflow, but didn't want to wait for the expo servers to catch up to my build pace, this is what I was missing:

https://docs.expo.dev/workflow/customizing/

```
expo prebuild --clean
```

```
# Build your native Android project
npx expo run:android

# Build your native iOS project
npx expo run:ios
```

Hope that helps :)
