### ISSUE TITLE
Video muted on iOS

### ISSUE THREAD

**Issue by MrLoh** [expo/expo#211]
The `Video` Component seems to have the wrong `AVAudioSessionCategory` on iOS. It should at least be possible to set it to `AVAudioSessionCategoryPlayback` so that sound of the video will playback, even if the phone is muted, which is the default behaviour in every video app (including apples) on iOS. The same applies for a `WebView`. Unfortunately I am not an expert on iOS development, so I have no idea how to fix this, but I'd be happy to learn it, if someone can help me. 

I have seen several apps that misbehave in this way in the past, and now that I am building my own ReactNative app, I am running into the same issue, making me thing, that all the other apps with this bug, might also be build with React Native. This should really be fixed, as it is very unexpected behavior on iOS, I can't speak for Android.

**Comment by MrLoh** [comment]
I am not sure wether you are using react-native-video, but if so, this could be related to this issue:
https://github.com/react-native-community/react-native-video/issues/98

**Comment by gkufera** [comment]
Hi @MrLoh!

We encapsulate `AVAudioSessionCategory*` and the corresponding behaviors on Android with our concept of ["Audio Mode"](https://docs.expo.io/versions/v17.0.0/sdk/audio.html). It looks like you want to set `playsInSilentLockedModeIOS` to `true`.

Let me know if this does not work for you. Thanks!

Greg

**Comment by MrLoh** [comment]
Sorry for the delay. I tried your suggestion by setting `playsInSilentLockedModeIOS: true` on `componentDidMount` of `App` but this does not affect the playback behavior when muted at all it seems.

```js
import { Audio } from 'expo'

...

    async componentDidMount() {
        await Audio.setAudioModeAsync({
            playsInSilentLockedModeIOS: true,
            allowsRecordingIOS: true,
            interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
            shouldDuckAndroid: false,
            interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
        })
        this.setState({loaded: true })
    }
```

**Comment by MrLoh** [comment]
It does work for an Audio Component though, so this looks like a bug to me. @gkufera

**Comment by MrLoh** [comment]
@gkufera So I had a look at the source code. I have never written any ObjectiveC, so this was a bit tricky. But I think what's going on is that `_deactivateAudioSession` is  called on the video for some reason, could you help me with what I have to do to set up an audio session that will run alongside my webview to ensure the `AVAudioSessionCategory` is not reset.

https://github.com/expo/expo/blob/734d58b7592d033887ed0deb4e74b417db0648a7/ios/Exponent/Versioned/Modules/Api/AV/EXAV.m

**Comment by MrLoh** [comment]
That's definitely the issue. If I play a sound in the background, and then start the video in the webview over it, it will play it's sound. When no sound is playing it won't.

**Comment by MrLoh** [comment]
So I guess basically what is missing is to get a playbackObject from a WebView somehow. I guess I will just hack it by playing a muted audio in the background while the YouTube Video in the WebView is active.

**Comment by MrLoh** [comment]
@gkufera My current code is available here. It would be really great to have a way to support an audio session of a webview without having to play a silent audio file in the background.

https://github.com/Cinuru/react-native-youtube-js/blob/master/YouTube/YouTube.js

**Comment by ferenax** [comment]
@MrLoh Did you find any solution to this problem? I'm currently build an expo app with embedded youtube in a webview and couldn't make the sound work on iOS when muted even with 
```
setAudioModeAsync({
      ...,
      playsInSilentModeIOS: true,
})
```
By the way, your code isn't available anymore on the link you provided.
Is this confirmed to be a bug? Or is there a workaround anywhere?

**Comment by MrLoh** [comment]
Here's a working link. This won't work out of the box though. Needs to be adjusted for some changes in the latest expo versions and there are also still some issues on android. In general it's not as straight forward at all as one would expect to integrate YouTube. 

https://github.com/Cinuru/react-native-youtube-js

**Comment by Solitaryo** [comment]
is there any solution for this? i'm so frustrated

**Comment by MrLoh** [comment]
We’ll video and audio support setting it. If you need it in a web view. Just play a silent audio file in the background.

**Comment by harrison0723** [comment]
For anyone having this issue, I've followed @MrLoh 's (hack) solution and came up with this snippet which you can just put in your `componentDidMount` to get your video unmuted  in silent mode:
```
async componentDidMount() {
        await Audio.setAudioModeAsync({ 
            playsInSilentModeIOS: true,
            allowsRecordingIOS: false,                                                                                                                                                                                   
            interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DUCK_OTHERS,                                                                         
            shouldDuckAndroid: true,                                                                                                           
            interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS,
            playThroughEarpieceAndroid: true
        })
        await Audio.setIsEnabledAsync(true)
        const sound = new Audio.Sound()
        await sound.loadAsync({ uri: 'silent-audio.mp3' })
        sound.playAsync()
        sound.setIsMutedAsync(true)
        sound.setIsLoopingAsync(true)
    }
```

**Comment by nandorojo** [comment]
> For anyone having this issue, I've followed @MrLoh 's (hack) solution and came up with this snippet which you can just put in your `componentDidMount` to get your video unmuted in silent mode:
> 
> ```
> async componentDidMount() {
>         await Audio.setAudioModeAsync({ 
>             playsInSilentModeIOS: true,
>             allowsRecordingIOS: false,                                                                                                                                                                                   
>             interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,                                                                         
>             shouldDuckAndroid: false,                                                                                                           
>             interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
>             playThroughEarpieceAndroid: true
>         })
>         await Audio.setIsEnabledAsync(true)
>         const sound = new Audio.Sound()
>         await sound.loadAsync({ uri: 'silent-audio.mp3' })
>         sound.playAsync()
>         sound.setIsMutedAsync(true)
>         sound.setIsLoopingAsync(true)
>     }
> ```
> Remember to replace the uri with a silent audio!

This worked for me. A bit crazy of a hack, but hey, it does the job. Hopefully there's a solution sometime in the future that's native to the Video component.

**Comment by cem2ran** [comment]
Just wanted to add that it was sufficient for me to "just" play a short single digit ms long audio file before playing videos. No reason to loop or set muted. Still very much a hack though... A reproducible snack of the issue is in the above referenced issue.

**Comment by andregufc** [comment]
I added the following line to prevent the audio to keep playing even after the screen is unmounted:

await sound.unloadAsync();

**Comment by harrison0723** [comment]
Guys, I think they fixed it (https://github.com/expo/expo/issues/2570)
Just add `useWebKit={true}` to your `<WebView>`, no need to hack around with a silent audio anymore.
