### ISSUE TITLE
[iOS] expo-notifications addNotificationReceivedListener and addNotificationResponseReceivedListener not working in standalone

### ISSUE THREAD

**Issue by joycelsq84** [expo/expo#21107]
### Summary

[iOS] expo-notifications addNotificationReceivedListener and addNotificationResponseReceivedListenernot working in standalone ios but it is working in Expo Go test with ios device.

I tried to print out the notification parameter and it shows false.

### What platform(s) does this occur on?

iOS

### SDK Version

47.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Minimal reproducible example

useEffect(() => {
    registerForPushNotificationsAsync().then(token => setExpoPushToken(token));
    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
 
        if(notification.request.content.data.action === 'reloadPage'){
          webViewRef.current.reload();
        }

    });

    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
       
      if (response.notification.request.content.data.action === 'openInbox') {
        
        webViewRef.current.injectJavaScript(`window.location.href = 'https://abc.com'`);
      }
      else if (response.notification.request.content.data.action === 'reloadPage') {
      
        webViewRef.current.injectJavaScript(`window.location.href = 'https://bcd.com'`);
      }
      // console.log(response);
    });

    return () => {
      Notifications.removeNotificationSubscription(notificationListener.current);
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);

**Comment by joycelsq84** [comment]
why did you close this issue?

**Comment by pratikdhody** [comment]
> why did you close this issue?

Any luck resolving your issue @joycelsq84 ?

**Comment by joycelsq84** [comment]
no..... i am stuck with this for 1 more than a month now... what to do? i dont know why they close my case without even trying to help? @pratikdhody

**Comment by pratikdhody** [comment]
@joycelsq84 would you be able to re-open this issue then please.
