### ISSUE TITLE
unable to create or access an account in Expo XDE

### ISSUE THREAD

**Issue by flyaway2** [expo/expo#2110]
Hi everyone,
I'm new to  this Expo tool, I tried to create an account and I got this error "there was a problem understanding the server" 
![erreor](https://user-images.githubusercontent.com/42416837/44162328-e4082b00-a0b7-11e8-80b5-dcf08d304d1c.PNG)
and in developer DevTools I got this message connection timedout
![error2](https://user-images.githubusercontent.com/42416837/44162375-08fc9e00-a0b8-11e8-9e66-525625c50fa5.PNG)
I tried many times and it's the same error so I created an account from the android app and it worked fine but then when I tried to access it from the desktop app I run into the same error again by the way I'm running on windows.

**Comment by sjchmiela** [comment]
Hey, @flyaway2! Expo XDE has been recently deprecated in favor of Expo CLI. See the [release blog post](https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c). 🙂 I think this issue should be fixed in this new set of tools.
