### ISSUE TITLE
expo updates requestHeaders in ios and android does not generated any configuration by npx expo prebuild

### ISSUE THREAD

**Issue by keung7252** [expo/expo#21111]
### Summary

expo updates requestHeaders in ios and android  does not generate any configuration  by npx expo prebuild

I do not see EXUpdatesRequestHeaders in Expo.plist and UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY in AndroidManifest.xml.

{
  "expo": {
    "name": "aaa",
    "owner": "xxx",
    "icon": "./assets/images/appicon_d.png",
    "version": "1.0.2",
    "slug": "xxx",
    "scheme": "xxx",
    "splash": {
      "image": "./project/images/splash.png",
      "resizeMode": "cover"
    },
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "requestHeaders": {
        "expo-channel-name": "1.0.2"
      }
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "hk.com.xx.aaa",
      "buildNumber": "1",
      "requireFullScreen": true,
      "googleServicesFile": "./project/firebase/GoogleService-Info.plist",
      "infoPlist": {
        "CFBundleAllowMixedLocalizations": true,
        "NSCameraUsageDescription": "would like to use your camera",
        "NSMicrophoneUsageDescription": "would like to use your microphone (for videos)",
        "NSPhotoLibraryUsageDescription": "would like access to your photo gallery"
      }
    },
    "android": {
      "package": "hk.com.xx.aaa",
      "versionCode": 1,
      "googleServicesFile": "./project/firebase/google-services.json",
      "permissions": [
        "NOTIFICATIONS",
        "CAMERA",
        "READ_EXTERNAL_STORAGE"
      ]
    },
    "description": "",
    "extra": {
      "eas": {
        "projectId": "1f15890d-fcab-401c-a315-a88fd46c5e59"
      }
    }
  }
}

### What platform(s) does this occur on?

Android, iOS

### SDK Version

45

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 9.1.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/keung/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28, 29, 30, 31, 33
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

{
  "dependencies": {
    "@expo/config-plugins": "^5.0.4",
    "@expo/prebuild-config": "^5.0.7",
    "@expo/react-native-action-sheet": "^3.12.0",
    "@expo/vector-icons": "^13.0.0",
    "@miblanchard/react-native-slider": "^2.1.0",
    "@neverdull-agency/expo-unlimited-secure-store": "^1.0.10",
    "@openspacelabs/react-native-zoomable-view": "^2.0.4",
    "@react-native-community/datetimepicker": "6.1.2",
    "@react-native-community/netinfo": "8.2.0",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-native-picker/picker": "2.4.0",
    "@react-navigation/drawer": "^6.1.4",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@reduxjs/toolkit": "^1.6.1",
    "@sentry/react-native": "^3.1.1",
    "axios": "^0.21.4",
    "expo": "^45.0.0",
    "expo-analytics-segment": "~11.2.1",
    "expo-application": "~4.1.0",
    "expo-asset": "~8.5.0",
    "expo-av": "~11.2.3",
    "expo-blur": "~11.1.0",
    "expo-camera": "~12.2.0",
    "expo-constants": "~13.1.1",
    "expo-dev-client": "~1.0.1",
    "expo-device": "~4.2.0",
    "expo-draw": "git+https://github.com/MarangoniEduardo/expo-draw.git",
    "expo-file-system": "~14.0.0",
    "expo-firebase-analytics": "~7.0.0",
    "expo-gl": "~11.3.0",
    "expo-gl-cpp": "~11.3.0",
    "expo-image-manipulator": "~10.3.1",
    "expo-image-picker": "~13.1.1",
    "expo-localization": "~13.0.0",
    "expo-next-react-navigation": "^1.2.1",
    "expo-notifications": "~0.15.4",
    "expo-ota-manager": "^1.1.4",
    "expo-permissions": "~13.2.0",
    "expo-radio-button": "^1.0.8",
    "expo-screen-orientation": "~4.2.0",
    "expo-secure-store": "~11.2.0",
    "expo-sharing": "~10.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.4",
    "firebase": "8.2.3",
    "i18next": "^20.6.0",
    "modal-enhanced-react-native-web": "^0.2.0",
    "moment": "^2.29.1",
    "native-base": "^3.1.0",
    "next": "^11.0.1",
    "next-fonts": "^1.5.1",
    "next-images": "^1.8.1",
    "nextjs-progressbar": "^0.0.11",
    "no-scroll": "^2.1.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-i18next": "^11.11.4",
    "react-native": "0.68.2",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-custom-qr-codes-expo": "^2.2.0",
    "react-native-elements": "^3.4.2",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-htmlview": "^0.16.0",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-modal": "^13.0.0",
    "react-native-modal-datetime-picker": "^13.0.1",
    "react-native-qrcode-svg": "^6.1.2",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-scalable-image": "^1.1.0",
    "react-native-screens": "~3.11.1",
    "react-native-signature-canvas": "^4.3.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.3.0",
    "react-native-table-component": "^1.2.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-view-shot": "3.1.2",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1",
    "react-native-youtube-iframe": "^2.2.2",
    "react-redux": "^7.2.4",
    "recoil": "^0.7.5",
    "redux": "^4.1.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "rn-pdf-reader-js": "^4.1.1",
    "sentry-expo": "^4.2.0",
    "styled-components": "^5.3.1",
    "styled-system": "^5.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@expo/next-adapter": "^3.0.1",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^8.0.0",
    "prettier": "2.4.1"
  },
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build": "next build"
  },
  "private": true,
  "version": "0.0.0",
  "name": "msowner"
}

**Comment by douglowder** [comment]
The `requestHeaders` property in the `updates` section of Expo config is not supported in SDK 45. It will be supported in SDK 48.

If you are using `eas build`, and the build profile has a `channel` defined, then the `expo-channel-name` will be set by EAS during the build.

You can also set the request headers manually in `Expo.plist` and `AndroidManifest.xml`, as per https://docs.expo.dev/versions/v47.0.0/sdk/updates/

**Comment by ellowwwteam** [comment]
We try the npx expo prebuild "expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" added on AndroidManifest.xml. I'm trying to crate the production build following error coming.

**Added Code On AndroidManifest.xml**
`<meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-channel-name&quot;:&quot;production&quot;}"/>`

**Error:**
Setting the update request headers in 'AndroidManifest.xml' to '{"expo-channel-name":"production"}'
Couldn't find Android manifest at /home/expo/workingdir/build/android/app/src/main/AndroidManifest.xml
