### ISSUE TITLE
[sdk48-beta.0] - screen orientation permanently locked in portrait mode

### ISSUE THREAD

**Issue by coolersham** [expo/expo#21113]
### Summary

The following behaviour was tested on real and simulated iOS/iPadOS devices including the most recent versions of the respectable OS (15.5 and 16.2).

When using the approach stated in the `expo-template-bare-minimum` project, the orientation functionality is bugged and it is impossible to rotate away from portrait mode. It is not even possible to turn to the second portrait orientation.

Android devices are not affected by this issue.

### What platform(s) does this occur on?

iOS

### Environment

[...]
    npmPackages:
      @expo/webpack-config: 0.17.4 => 0.17.4 
      babel-preset-expo: 9.2.2 => 9.2.2 
      expo: 48.0.0-beta.0 => 48.0.0-beta.0 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.2 => 0.71.2 
      react-native-web: 0.18.12 => 0.18.12 
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

Following implementation in `AppDelegate.h` leads to the problem:
```
#import <Expo/Expo.h>
#import <UIKit/UIKit.h>

@interface AppDelegate : EXAppDelegateWrapper

@end
```

When using the following standard react-native way for the new architecture the orientation functionality works as expected:
```
#import <Expo/Expo.h>
#import <UIKit/UIKit.h>
#import <RCTAppDelegate.h>

@interface AppDelegate : RCTAppDelegate

@end
```

**Comment by coolersham** [comment]
This is still broken in sdk-48-beta.2

**Comment by brentvatne** [comment]
https://github.com/brentvatne/coolersham


https://user-images.githubusercontent.com/90494/218189981-544f20a6-5049-4e48-bfe3-8b18ab677e0d.mov

**Comment by coolersham** [comment]
@brentvatne Thanks for your effort!
Fixed by applying the following solution described in this [issue comment](https://github.com/expo/expo/issues/21114#issuecomment-1427060898).
