### ISSUE TITLE
[@expo/vector-icons] - icons/icon font not loading correctly

### ISSUE THREAD

**Issue by coolersham** [expo/expo#21115]
### Summary

When using the package `@expo/vector-icons` with other `expo` packages in an ejected environment, not a single icon loads and instead a question mark is rendered (it is even coloured in the correct way).

I am using the latest version of the package in connection with the new `react-native` architecture 
on version 0.71.2. Fabric renderer and concurrency are additionally enabled.

The icons are displayed as following:
<img width="71" alt="showcase" src="https://user-images.githubusercontent.com/123668138/217560298-cb74503c-876f-45a5-b702-4cec392d214d.png">

Android devices are not affected by this issue.

### What platform(s) does this occur on?

iOS

### Environment

[...]
npmPackages:
@expo/vector-icons: 13.0.0 => 13.0.0
@expo/webpack-config: 0.17.4 => 0.17.4
babel-preset-expo: 9.2.2 => 9.2.2
expo: 48.0.0-beta.0 => 48.0.0-beta.0
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.71.2 => 0.71.2
react-native-web: 0.18.12 => 0.18.12
npmGlobalPackages:
expo-cli: 6.0.8
Expo Workflow: bare

### Minimal reproducible example
```
import { MaterialCommunityIcons } from "@expo/vector-icons"

[...]

<MaterialCommunityIcons color="blue" name="close" size={24} />
```

**Comment by coolersham** [comment]
Strangely it only affects the following icon sets: EvilIcons, Octicons, Zocial, MaterialIcons, MaterialCommunityIcons and Foundation.

**Comment by ex3ndr** [comment]
Same here, did you found a solution? i just enabled fabric and icons are now gone

**Comment by lfiorini** [comment]
I am quite new to Expo. I've always used RN CLI workflow. I'm trying to update an existing RN CLI 0.68.2 to SDK49. I run npx expo prebuild, npm install expo-modules-core@next, npx pod-install but I still get ? instead of many (not all) MaterialCommunityIcons. Any hint?
