### ISSUE TITLE
[expo-application] `Application.androidId` constant do not comply with the privacy policies of app markets such as Huawei and Xiaomi.

### ISSUE THREAD

**Issue by xuhow** [expo/expo#21110]
### Summary

The same issue exists in `react-native-device-info`, but they have fixed it for now, and the details can be found in https://github.com/react-native-device-info/react-native-device-info/issues/1427.

### What platform(s) does this occur on?

Android

### Environment

System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.10.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 27, 29, 30, 31
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

none

**Comment by jakexchan** [comment]
Same issue.
Found the code from `ApplicationModule.kt` of the `expo-application` module, according to the stack information.

![20230213235812](https://user-images.githubusercontent.com/12413643/218509599-3524ca54-c73d-4a21-8dd5-2f693611a14e.jpg)

Is there any way to change it? Thanks a lot.

**Comment by xuhow** [comment]
> Same issue. Found the code from `ApplicationModule.kt` of the `expo-application` module, according to the stack information.
> 
> ![20230213235812](https://user-images.githubusercontent.com/12413643/218509599-3524ca54-c73d-4a21-8dd5-2f693611a14e.jpg)
> 
> Is there any way to change it? Thanks a lot.

The temporary solution is to use [patch-package](https://github.com/ds300/patch-package).

**Comment by hb1707** [comment]
Please developers resolve this issue as soon as possible

**Comment by danielcdcj** [comment]
Please have this resolved soon
I got the same message on Baidu store as well.
I'm using Expo SDK v48.0.15
![Screen Shot 2023-05-11 at 12 03 28](https://github.com/expo/expo/assets/5447994/093f5d53-4025-4aba-8719-d36dd8c3cf04)

**Comment by ZhengKehang** [comment]
How to fix this bug, anyone has suggestion？

**Comment by jaweii** [comment]
How to fix this bug, anyone has suggestion？

**Comment by reichhartd** [comment]
@lukmccall @fobos531 This should be fixed with #24568, right?

**Comment by hb1707** [comment]
[expo-application+5.3.1.patch](https://github.com/expo/expo/files/14179667/expo-application%2B5.3.1.patch)
目前只能使用[patch-package](https://github.com/ds300/patch-package) 解决

**Comment by xuhow** [comment]
> @lukmccall @fobos531 This should be fixed with #24568, right?

Yes, the issue has indeed been fixed with #24568, so I'm closing this issue.
