### ISSUE TITLE
Setting UIDevice.orientation is not supported

### ISSUE THREAD

**Issue by clwy-cn** [expo/expo#21114]
### Summary

I used `expo-screen-orientation`，there are some problems with this package.

When I used `expo go`, it worked fine.

An error occurred when I was using `npx expo run:ios`

<img width="939" alt="image" src="https://user-images.githubusercontent.com/57120683/217548463-424e8b42-c945-4c33-af91-d708452964a8.png">

- In `expo go`

<img width="241" alt="image" src="https://user-images.githubusercontent.com/57120683/217550232-79b33b3a-2f0e-47a8-babe-e429c29888aa.png">

- The same code in `run:ios`
<img width="241" alt="image" src="https://user-images.githubusercontent.com/57120683/217549969-daf37765-3cad-4ec2-81f6-64c951acb413.png">

### What platform(s) does this occur on?

iOS

### Environment

- iOS 16.2
- Xcode 14.2

### Minimal reproducible example

```js
await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE_RIGHT)
```

**Comment by coolersham** [comment]
I faced the same problem while using the `expo-screen-orientation` package as stated in this [issue](https://github.com/expo/expo/issues/21113).

It seems like the following `.plist` entries are now no longer considered optional but required:
```
<key>EXDefaultScreenOrientationMask</key>
<string>UIInterfaceOrientationMaskAllButUpsideDown</string>
```
Just use the desired orientation type from the [official list](https://developer.apple.com/documentation/uikit/uiinterfaceorientationmask?language=objc) provided by Apple.
