### ISSUE TITLE
@expo/fingerprint issues

### ISSUE THREAD

**Issue by leggomuhgreggo** [expo/expo#21128]
### Summary

Firstly, I'd like to express my appreciation for this tool. I've been working on a much more rudimentary "native dependency hashing" tool and I really enjoyed learning from this implementation.

### Local Config Plugins

If the `app.json` references a config plugin that's in the same directory as the app, then the expo config files sources get clobbered, and deduped into a dir source for the entire project folder -- which also has a reasons array with duplicate entries. 

[Repro](https://github.com/leggomuhgreggo/nx-issue-expo-babel/tree/expo-fingerprint-repro#local-config-plugin-example)

<img src=https://user-images.githubusercontent.com/2213636/217717485-6befc8e2-9f01-4200-a952-d2840b87c7b2.png width=300 />

Related Note: this might be causing duplicate sources -- for example I noticed cases where a fingerprint included a dir source for "x" dependency, and then there was also a content source with the podSpect for the same dependency -- which I could see being a result of the config files being clobbered and there being issues with `bareRncliAutolinking` + `expoAutolinkingIos`.

### Monorepo & Wildcard Dependencies

Some monorepos use the [single version policy](https://nx.dev/more-concepts/dependency-management#single-version-policy) (SVP) which means that all dependencies are contained within the root level package.json -- and project-level package.jsons either don't exist or exist in some minimal representation.

In my case, using an Nx monorepo, the project-level package.json has a wildcard version of react native, which is a sort of hack to help alleviate RN module resolution issues.
```
  "dependencies": {
    "react-native": "*",
```

Anyway -- as you'd expect -- the fingerprint doesn't include many of the packages that are used in the app. 

[Repro](https://github.com/leggomuhgreggo/nx-issue-expo-babel/tree/expo-fingerprint-repro#local-config-plugin-example)

Even monorepos who don't use the SVP approach to dependency management, will often use wildcard versioning, to help resolve packages in the same workspace -- as illustrated by the "Expo + monorepo" [docs](https://docs.expo.dev/guides/monorepos/#using-the-package). So it may be useful to consider as a support case.

### Stability Risks w/ `node_modules`

One difficulty with the current logic is that much of it depends on the current state of the node_modules directory.

If someone installs without `--frozen-lockfile` (in the case of yarn) then there's a chance the fingerprints will be invalid. Similarly if someone switches branches, its possible the node_modules folder will be out of sync. 

It might be worth considering the use of lockfiles, instead of node_modules directory, as the basis for tracking native dependency changes. This would have the added benefit of enabling fingerprint diffs based on git commits, since they could resolve the tracked lockfile from git history, instead of having to install, fingerprint, etc.

Related Note: I haven't been able to figure out the repro for this yet, but there's some set of circumstances where fingerprints are generated with content sources that include absolute file paths, specific to the computer (ie has user directory in path). This would obviously break cross-machine compatibility. Will try to follow up on this!

_I will leave it there for now._ 

_Thanks!_

### SDK Version

47

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.11.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.5.2 => 0.5.2 
      @expo/webpack-config: ~0.17.4 => 0.17.4 
      babel-preset-expo: ~9.2.2 => 9.2.2 
      expo: 47.0.13 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/leggomuhgreggo/nx-issue-expo-babel/tree/expo-fingerprint-repro

**Comment by Kudo** [comment]
hi @leggomuhgreggo! thanks for this fantastic issue reporting, especially the repro examples with readmes. this is the best reporting issue i had ever seen. also thanks for looking into the fingerprint implementation in detail. when i introduced this package, i am not confident enough and not got a chance to use it in the real world. it's good to get these great comments from you.

> Local Config Plugins

that is by design. for local config plugins, i was thinking there was no perfect way to determine the local plugin scope. for example, the local plugin could require/import other js files. so i decided to include the whole directory. i am open to getting comments if you have any ideas about this.

> Monorepo & Wildcard Dependencies

sorry i didn't think of monorepo support. will follow up on this.

> Stability Risks w/ node_modules

if we have to support patch-package, we should rely on node_modules. and there are different types of lock files, e.g. npm, yarn, and pnpm. it's a little hassle to support all of them. one idea we could try is to run `npm install` / `yarn install` before generating fingerprints. does that make sense to you?


thanks again for your great comments. please feel free to let me know if you have any further comments or if i missed answering any questions from you.

**Comment by Kudo** [comment]
> Monorepo & Wildcard Dependencies

after doing `yarn` in `apps/repro-app` of your example, it will include these missing packages. it should be because of `npx nx sync-deps repro-app && npx nx ensure-symlink repro-app`. is that what you expected?

**Comment by leggomuhgreggo** [comment]
Thanks for the thoughtful response @Kudo!

> it should be because of npx nx sync-deps repro-app && npx nx ensure-symlink repro-app. is that what you expected?

Admirable sleuthing! 

My imperfect understanding of node/rn module resolution mechanics is far from perfect, but my understanding is the `sync-deps` step isn't technically needed. 

When the `@nrwl/expo` plugin first came out, they added `sync-deps` and included it in the default build process. But I think it's carried over from their `@nrwl/react-native` plugin. We didn't seem to need it before.

<details>
  <summary>Additional Context</summary>

Before `@nrwl/expo` came out, we were building, with a custom nx + expo  plugin -- and the sync-deps step was not part of the process. 

Not too long ago I was exploring pnpm. While there was some hoisting pattern logic, I didn't have to include any dependencies in project-level package.json, in order to successfully build via EAS.

My hope is that we can eventually get rid of the project level package.json altogether. I really appreciate the reduced maintenance costs, afforded by only having to update one package.json. 

That said, this SVP pattern might not be super easy to support -- and given that it's a bit niche -- I would understand if this matter isn't seen as a priority. 
</details>




> that is by design. for local config plugins, i was thinking there was no perfect way to determine the local plugin scope

Interesting! Hmm, yeah, that's tricky.

Actually I was curious to understand the usage / feature priority of the tool: 
- Am I right to think that the main intended use case is with tool is to help support rebuilding native binaries when they become invalidated by some change? 
- Are there any others that are noteworthy?

I ask because -- if a consequence of accommodating local config plugins is that the fingerprint is invalidated for every code change to the app src, then I wonder if it's better to maybe deprecate support for local config plugins? Or maybe support them as a custom extra source?

> if we have to support patch-package, we should rely on node_modules. 

Ah yeah that's a pickle. If it were me I think I'd try to support patch package as an extended use case -- but that's me who only uses it once in a while.

> and there are different types of lock files, e.g. npm, yarn, and pnpm. it's a little hassle to support all of them.

Another valid point.

> one idea we could try is to run npm install / yarn install before generating fingerprints. does that make sense to you?

I think installs are significant enough that they should be left to developer discretion. If a tool auto-installed I think I'd find that a bit imposing. 

But I could see warning that the node_modules is out of date! 

----

The solution I worked out using `@expo/fingerprint` runs the fingerprint twice: (1) once from the workspace-root, and (2) once from the project-root -- then I _slice and dice_ the fingerprint objects, removing sources I don't need -- and finally rehash.

It's a little slower, but seems to work reasonably well! I think in the next couple weeks I'd like to adapt it to work with the lockfile (If I get anything worth sharing I will let ya know)

Thanks again for the response!

**Comment by Kudo** [comment]
being busy with different work, i am sorry to reply this thread lately.

> My understanding of node/rn module resolution mechanics is far from perfect, but I don't think the sync-deps step is technically needed.

i didn't have much experience with nx. if it relies on sync-deps to add package.json dependencies/devDependencies from workspace root to subproject, then it sounds the sync-deps is necessary.

though workspace is difficult, some people want SVP and some people want to maintain different react-native versions across subprojects. fingerprint may not optimize for SVP case, hopefully, it helps a little bit at least. let me share my original design thought next.

> Actually I was curious to understand the usage / feature priority of the tool:
> Am I right to think that the main intended use case is with tool is to help support rebuilding native binaries when they become invalidated by some change?
> Are there any other noteworthy use cases you're designing for?

good questions! when i start to think about to design this tool. i had some thoughts in my mind:

- it is okay to not be perfect, but it must not introduce regression problems. false positive is acceptable, and false negative should be avoided. e.g. it is okay if we generate a different fingerprint because of js changes. it is wrong if we generate the same fingerprint from native changes. that is also the reason why i was thinking to support patch-package and not to break the use case.
- it should not take much time to generate the fingerprint.

i didn't have concrete use cases yet, the rebuilding native binaries when there are native changes is one case for sure. the other similar idea in my mind is to enhance the expo development-build workflows on team work. like when you run `npx expo start`, this tool could help to indicate whether the installed app is compatible with the code on the latest main branch committed by teammates.

as you had seen the tool is still on the early stage and welcome for any idea. i like to hear your insight pretty much.

> The solution I worked out using @expo/fingerprint runs the fingerprint twice: (1) once from the workspace-root, and (2) once from the project-root -- then I slice and dice the fingerprint objects, removing sources I don't need -- and finally rehash.

tbh i didn't think of workspace or SVP before. i was thinking to run fingerprint in each subproject root, like we would run `eas build` in each subproject root rather than workspace root. maybe what's worth is to improve the speed. could you share how long it takes for generating fingerprint in your case, `time npx @expo/fingerprint@latest .` ? if you want to profile the speed, you could also run `DEBUG='expo:*' npx @expo/fingerprint@latest .`.

thank you @leggomuhgreggo again for your great comments. i am really appreciated ❤️

**Comment by leggomuhgreggo** [comment]
Thanks for sharing some of that context -- and for the time/debug suggestions

I updated the [example repo](https://github.com/leggomuhgreggo/nx-issue-expo-babel/tree/expo-fingerprint-repro#workaround-example) with my workaround [implementation](https://github.com/leggomuhgreggo/nx-issue-expo-babel/commit/495bca9beb1500dc55591d0842169102f0d72520#diff-bc3658e47e5e66f26b71e76ea2c813accd9e358933ece00b93379185c7079d72R20-R31), and updated the README to include the time / debug output. 

 ```
// repro project
6.48s user 1.23s system 169% cpu 4.550 total

// real project
27.95s user 6.64s system 153% cpu 22.540 total 
```

I'd guess the main factor driving latency is the size of the node_modules directory, but that's just a hunch.

## Field Report

I've started to use the `@expo/fingerprint` approach in the CI at work -- and so far so good!

It definitely takes a little longer than the solution I was using prior to learning about `@expo/fingerprint` -- but it's hardly noticeable, within the context of the larger CI workflow. 

And the rate of false positives, has dropped significantly -- very pleased with the improvement. 

One drawback is that the fingerprint from CI doesn't match the fingerprint generated locally -- but luckily that's only very rarely an issue. 

## Additional Discussion

>false positive is acceptable, and false negative should be avoided. e.g. it is okay if we generate a different fingerprint because of js changes. it is wrong if we generate the same fingerprint from native changes.

Definitely agree with this. Especially from the perspective of the library _author_, avoiding false negatives seems like it has to be the baseline functionality. 

That's not to say tolerance for false positives are without limit. For example -- the edge case where it was hashing a source for the entire project directory -- it wouldn't have been viable for me as a library _consumer_.

<details><summary>Half-baked suggestions</summary>

Maybe it would be useful to expand the "source configuration" features, with those kind of edge cases in mind.

I mean -- there's already pretty decent support, with the `dirExcludes` and `extraSources` options -- but I just remember looking for a fileExcludes at one point (not that it would have really led to a solution. Just a thought)

Perhaps a better interim recourse would be to just export the lower-level utilities, to enable workarounds like what I cobbled together, as a stop-gap. And actually -- maybe formalizing some sort of "fingerprint composition" interface is a decent longer term solution.

(I need to take a nap haha) 

</details>


<details><summary> Monorepo Use Case</summary>

One related feature Ill be looking to add for my workspace is the ability to filter npm dependencies based on whether a given project is using it. 

That's way far outside the scope of this tool -- but I thought I'd share, in case it was relevant. 

</details>


I will leave it there for now. Such a fun feature! I will keep you posted if I have anything useful to share. 
 
You rock @Kudo!

**Comment by Kudo** [comment]
wow! the fingerprint takes long time on your real project. then i totally understand why you were thinking about generating fingerprint just once from the workspace root.

thanks for sharing the debug output from the repro example. i see one bottleneck is from react-native-cli's autolinking. that is a known bottleneck 😅 you could try to comment out it from **node_modules/@expo/fingerprint/build/sourcer/Sourcer.js** and see how much time it reduced, especially from your real project. those autolinking sourcers heavily depend on node_modules, i think we could skip them from the phrase of workspace root fingerprint.

aside from that, when you run `./fingerprint-adapter-script.ts` at the second time, does it reduce any meaningful time? i was thinking how much time the `ts-node` used to compile typescript 😅

> One drawback is that the fingerprint from CI doesn't match the fingerprint generated locally -- but luckily that's only very rarely an issue.

could you describe what's the fingerprint difference between CI and local?

> Maybe it would be useful to expand the "source configuration" features, with those kind of edge cases in mind.

that's a good idea and definitely something we should do. i could plan for both configurations and exporting some low-level functions.

in the meantime, i would like to help and figure out the fingerprint slowness and see if we could do some optimization. it's time to do optimization as we see no false negative happening. please help me to dig out the bottleneck from your real project.

thanks for your neat comments as always. i am glad you are here to do this exciting project with us.
