### ISSUE TITLE
Images sometimes don't load since 29.0.0

### ISSUE THREAD

**Issue by yanchenko** [expo/expo#2112]
Local images sometimes don't load since upgrading to 29. Reverting to 28 fixes the issue.
iOS 11.4.1, iPhone SE.

**Comment by lucasboleli** [comment]
same here

**Comment by raulmmdev** [comment]
Same problem both platforms

**Comment by jper92** [comment]
same problem here with v29.0.0 in ios, most of the time they don't show

**Comment by PaulDolphin1** [comment]
same problem with v29.0.0 on ios

**Comment by lilosir** [comment]
v30 seems also not working

**Comment by tsapeta** [comment]
SDK29 that this issue refers to is no longer supported, so I'm gonna close this issue. Please create a new issue if this still happens in any of the currently supported SDK versions.
