### ISSUE TITLE
Contacts.getContactsAsync doesn't fetch phone numbers

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo#2113]
### Environment

Expo Client on Android, SDK 29

### Steps to Reproduce

`Contacts.getContactsAsync({ fields: [Contacts.Fields.PhoneNumbers] });` doesn't fetch phone numbers whereas `getContactByIdAsync(id, [Contacts.Fields.PhoneNumbers])` does.

### Expected Behavior

Given a valid array of field types to fetch, `getContactsAsync` fetches all the fields for a given types, eg. contacts returned by `Contacts.getContactsAsync({ fields: [Contacts.Fields.PhoneNumbers] });` contain phone numbers of contacts.

### Actual Behavior

Contacts returned by `Contacts.getContactsAsync({ fields: [Contacts.Fields.PhoneNumbers] });` do not contain phone numbers.

### Reproducible Demo

https://snack.expo.io/rkqhbpG8X

**Comment by EvanBacon** [comment]
looking now

**Comment by EgidioCaprino** [comment]
@EvanBacon any news?

**Comment by EvanBacon** [comment]
Internally we have a PR waiting for review, should be dropping in SDK 30

**Comment by shubham-2710** [comment]
Hey, 
Contacts.getContactsAsync({
      fields: [Contacts.Fields.PHONE_NUMBERS]
    });
does not fetch the contacts with phone numbers .
SDK used is 32.

**Comment by EgidioCaprino** [comment]
We ejected from Expo and Expo Kit many months ago
