### ISSUE TITLE
Error building iOS in Expo 48

### ISSUE THREAD

**Issue by djMax** [expo/expo#21150]
### Summary

Working Expo 47  app, upgraded to 48 and I get this:

```

❌  (node_modules/react-native/React/AppSetup/RCTAppSetupUtils.mm:27:9)

  25 |
  26 | #ifdef FB_SONARKIT_ENABLED
> 27 | #import <FlipperKit/FlipperClient.h>
     |         ^ 'FlipperKit/FlipperClient.h' file not found
  28 | #import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
  29 | #import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
  30 | #import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

```

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.1 - ~/.nvm/versions/node/v14.20.1/bin/node
      Yarn: 3.3.1 - ~/.nvm/versions/node/v14.20.1/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/memetral/.gem/ruby/3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1
      expo: ~48.0.0-beta.2 => 48.0.0-beta.2
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.2 => 0.71.2
      react-native-web: ~0.18.9 => 0.18.10
    npmGlobalPackages:
      eas-cli: 3.5.2
    Expo Workflow: bare

### Minimal reproducible example

I'm not sure I can really do that since the whole point is updating and Snack doesn't work yet. Will continue to investigate.

**Comment by djMax** [comment]
I `rm -rf`ed ios, but second try does a similar thing:

```
(/Users/djmax/Library/Developer/Xcode/DerivedData/Chess-fniguitkupwmpmggcuujoltscigl/Build/Products/Debug-iphonesimulator/FlipperKit/FlipperKit.framework/Headers/SKMacros.h:11:9)

   9 | #define SKMACROS_H
  10 |
> 11 | #import <FBDefines/FBDefines.h>
     |         ^ 'FBDefines/FBDefines.h' file not found
  12 |
  13 | #ifdef __cplusplus
  14 | #define SK_EXTERN_C_BEGIN extern "C" {
```

**Comment by brentvatne** [comment]
try deleting your derived data. `rm -rf ~/Library/Developer/Xcode/DerivedData`

if the issue persists please create a new issue and try to narrow it down to the minimal amount of code needed to reproduce, thank you!

**Comment by djMax** [comment]
I did remove derived data, no change. I may or may not get time to isolate, but hopefully this placeholder will catch the next person for whom upgrading to 48 is more critical.

**Comment by djMax** [comment]
FYI additional weirdness is that a version of this happened after I reverted the upgrade. Building in xcode was fine, but not the CLI. Going to upgrade again and see if that's still true.

**Comment by brentvatne** [comment]
heya @djMax - if you use prebuild, try re-generating your project. this should be fixed in https://github.com/expo/expo/commit/aea28986bb577ae2b749ea87c2f5ddeb163ac576
