### ISSUE TITLE
exp build:android fails

### ISSUE THREAD

**Issue by SKempin** [expo/expo#2115]
Running `exp build:android errors` fails. I am experiencing this on both Windows and OS X. 

[This solution](https://forums.expo.io/t/error-connect-econnrefused-127-0-0-1-19001/12535/4) is working as a temporary work around. Expo version is `56.0.0`. 

```
$ exp build:android
[11:01:40] Checking if current build exists...

[11:01:41] No currently active or previous builds for this project.
[11:01:42] Publishing to channel 'default'...
[11:01:44] Building iOS bundle
[11:01:45] Error: connect ECONNREFUSED 127.0.0.1:19001
[11:01:45] Set EXPO_DEBUG=true in your env to view the stack trace.
```

 
### Environment

```
Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/skempin-e8172ba2-6e87-419c-b5dd-7eb273b98cbf.tar.gz
```

### Steps to Reproduce

1. Run `exp build:android` from a fresh terminal.

### Expected Behavior

The APK should be built.

### Actual Behavior

The build fails.

A temporary solution is to run `exp start` first and then run `exp:build:android`.

![capture](https://user-images.githubusercontent.com/10877466/44203025-a18d2f80-a145-11e8-94b5-da0d8f5b0aa0.JPG)

###

**Comment by jacinto123** [comment]
I am also experiencing this issue.

**Comment by cesarodriguez4** [comment]
Another solution is open in a different tab the expo server running `yarn start` (or `npm start`) if the project was created under `create-react-native-app`

**Comment by kevupton** [comment]
This works.

- `exp start` 
- Cancel `ctrl c`
- then do `exp build:android` works.

**Comment by Nisharunnisaa** [comment]
the commands recently got changed with the new update `exp build:android` to `expo build:android`

Reference: [Expo Building Standalone Apps](https://docs.expo.io/versions/v30.0.0/distribution/building-standalone-apps)

**Comment by julianrod94** [comment]
Probably the bundler didn't close correctly. So you cannot run another one on the same port. Maybe `expo start` kills the old process?

**Comment by tcdavis** [comment]
Closing since it sounds like this has been resolved in expo-cli

**Comment by noctavel** [comment]
im using expo-cli and im having the same issue. but the solution above worked anyway...

**Comment by tonnenpinguin** [comment]
I'm still experiencing the same issue with expo-cli 2.3.5
Upgrading to expo sdk 31 broke our pipeline because the packager is not started automatically anymore.

**Comment by Niades** [comment]
Experiencing same issue with `expo-cli@2.6.5`, solution above helped.

**Comment by SKempin** [comment]
@Niades might be worth opening a new ticket to let them know.

**Comment by joaowiciuk** [comment]
> This works.
> 
>     * `exp start`
> 
>     * Cancel `ctrl c`
> 
>     * then do `exp build:android`.

Savior

**Comment by shivnath17** [comment]
This is work for me................

1. expo start
2. Open another tab
3. expo build:android

**Comment by jannikbuschke** [comment]
My build pipeline started throwing this error after I accidentally commited .expo/packaer-info.json and settings.json. Removing them from the repository fixed the issue.

**Comment by jimwilde** [comment]
Had the same issue on OSX . Was resolved by:

- expo start
- once app is running, ctrl c to close the packager. 
- expo build:android

**Comment by john20xdoe** [comment]
Some info:
`expo start` now uses 19002 port but the `expo publish` and `expo build` still look for the bundler in 19001.
is this related to the latest v33 release?

**Comment by abduraufsherkulov** [comment]
No need to hassle. Just delete **.expo** folder and `run expo:build`, works like a charm.

**Comment by Remig9** [comment]
no a big deal just open ur text editor and make a new changes , in my own case i write a comment and i save .then re run expo build:android .thank me later

**Comment by ZamanGoraya** [comment]
This works.

exp start
Cancel ctrl c
then do exp build:android.

Wao...! it really works...

**Comment by kalliub** [comment]
For me, on Windows,
expo start
ctrl+c
expo build:android
worked once. But couldn't make it work again by the same way.
Tried running expo start, opening a new tab and running expo build:android at the same time, without cancelling expo start, and worked 100%!

Thank you so much!

**Comment by JavatarSRB** [comment]
Mostly every time I had this issue since the update in the expo-cli is to "expo start -c" which will clear the cache for you and will fix the issue you have. Other solutions are not fixing the issue any more.

**Comment by EdvinasRuo** [comment]
For me on Windows this worked: 

    1. expo start
    2. open a new command tab  - expo publish

**Comment by Decoder3-14** [comment]
> For me on Windows this worked:
> 
> * expo start
> * open a new command tab  - expo publish

Works fine!

**Comment by Decoder3-14** [comment]
Solved the issue the following way:
1-expo start
2-opening a new terminal window => expo build <platform code>

**Comment by moaazmf90** [comment]
> 
> 
> Solved the issue the following way:
> 1-expo start
> 2-opening a new terminal window (same project dir) => expo build

exactly, the expo must be running, this will work. (run terminal as admin).

**Comment by rolandoldengarm** [comment]
Why is this still an issue?

The workaround doesn't help in my case.  Why is it doing an iOS bundle while I want to build Android?

```
$ expo build:android
Checking if there is a build in progress...


? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
Publishing to channel 'default'...
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:19001
Set EXPO_DEBUG=true in your env to view the stack trace
```

**Comment by ashokharijan97** [comment]
> This is work for me.
> 
> 1. expo start
> 2. Open another tab
> 3. expo build:android

Thanks bro, It's also working for me thank you so much.

**Comment by chathunpc** [comment]
use this command   **expo build:android -c**       and happy build!

**Comment by TanvirHasanHridoy** [comment]
> Another solution is open in a different tab the expo server running `yarn start` (or `npm start`) if the project was created under `create-react-native-app`

thanks man! that worked for me! Finally, thank god!!!

**Comment by egos-ti** [comment]
this works for me.

[](https://forums.expo.io/t/error-when-trying-to-run-exp-publish/223/12?u=jorgews.dev)

**Comment by egos-ti** [comment]
see this forum comment.
https://forums.expo.io/t/error-when-trying-to-run-exp-publish/223/12?u=jorgews.dev

**Comment by kopax** [comment]
I still have this with SDK36, how do you <kbd>CTRL</kbd>+<kbd>C</kbd> and `Open a new tab` within a CI ? (Gitlab-CI) 

Related to https://github.com/expo/expo/issues/6639

**Comment by mohamedlahouassa** [comment]
run npm i -g exp

**Comment by brentvatne** [comment]
@mohamedlahouassa - `exp` is no longer updated, please use `expo-cli` instead - `npm i -g expo-cli` - more info at https://docs.expo.io/versions/v36.0.0/workflow/expo-cli/

**Comment by Arjorie** [comment]
I am building an android app with expo and encountered this issue as well. Thanks for the solution guys.
I just want to share what caused the error.
The build requires a Metro Bundler running in port `19001` where this is not running by default as we type in `expo build:android` and this caused this error

> connect ECONNREFUSED 127.0.0.1:19001

so starting the Metro Builder first by typing `expo start` then start building by typing `expo build:android` or I haven't try this yet but share us the result when you does thanks! Add `-c` to `expo build:<platform>` example: `expo build:android -c`

Cheers!

**Comment by hassan-dev** [comment]
After downgrade to expo-cli@3.1.0 and deleting .expo folder fixed for me
npm uninstall -g expo-cli
npm install -g expo-cli@3.1.0

**Comment by Xerus2000** [comment]
Fixed the same problem by deleting the `.expo` folder.

**Comment by TomWrd** [comment]
> No need to hassle. Just delete **.expo** folder and `expo build:android` or `expo build:ios`, works like a charm.

This -> expo publish did the trick for me.

**Comment by sagarmakhija1994** [comment]
**Open 2 terminals**
terminal1: `npm start`

//let start the app
terminal2: `expo build: android`

tada your app will start building apk/ipk

**Comment by Xerus2000** [comment]
@sagarmakhija1994 that is exactly the hassle I want to avoid...

**Comment by badbod99** [comment]
Remove .expo directory from project and try again.

`rm -rf .expo`

**Comment by Xerus2000** [comment]
@badbod99 yes that usually works, but is also a hassle I'd like to avoid - it doesn't fix the actual problem.

**Comment by badbod99** [comment]
None of the above suggestions actually fix this issue, they are just workarounds.

**Comment by kopax** [comment]
Generally, this happen randomly, waiting a bit and trying again also solve the issue. I believe expo can also have internals problems.

**Comment by Codeskin-byte** [comment]
> 
> 
> This is work for me.
> 
>     1. expo start
> 
>     2. Open another tab
> 
>     3. expo build:android

Yes it is the standard method and works for me!

**Comment by badbod99** [comment]
> Generally, this happen randomly, waiting a bit and trying again also solve the issue. I believe expo can also have internals problems.

This is an Expo project issue report, it's been closed by the Expo team, but clearly, as you mention, it's an Expo bug (or Expo internal issue).

**Comment by stevenYouhana** [comment]
> try run command
> 
> > expo build:android

only this solution worked for me. the exp command always throwed errors

**Comment by Rafay3198** [comment]
open a new terminal
write `ipconfig`
you'll get ip4 address like: 192.168.........
copy this address and run this
set REACT_NATIVE_PACKAGER_HOSTNAME=(paste you ip4 address here)
now run `expo start` 
open split terminal and run `expo build:android`
Happy coding :)

**Comment by KavinduDissanayake** [comment]
This Work 100%
1)npm start
2)expo build:android
3)do not close npm start using ctral +c

**Comment by Katacha1537** [comment]
> Por que isso ainda é um problema?
> 
> A solução alternativa com CTRL + C não ajuda no meu caso. Felizmente, excluir a pasta .expo funciona.
> Por que ele está executando um pacote iOS enquanto eu quero criar o Android?
> 
> ```
> $ expo build:android
> Checking if there is a build in progress...
> 
> 
> ? Would you like to upload a keystore or have us generate one for you?
> If you don't know what this means, let us handle it! :)
>  false
> Publishing to channel 'default'...
> Building iOS bundle
> connect ECONNREFUSED 127.0.0.1:19001
> Set EXPO_DEBUG=true in your env to view the stack trace
> ```

funcionou perfeitamente

**Comment by brentvatne** [comment]
@Katacha1537 - every time you run `expo build:*` it will publish first, and every time you publish (`expo publish`) it currently publishes to ios and android. if you want to use a previously published version, then do `expo build:android --no-publish`

**Comment by kopax** [comment]
Dear all, I solved all the issues like this:

`ECONNREFUSED 127.0.0.1:19001` in CI (gitlab-ci)

```jsx
android-staging:
  stage: native
  artifacts:
    name: "myapp-android-${CI_BUILD_TAG}-staging"
    paths:
      - myapp-android-${CI_BUILD_TAG}-staging.apk
    expire_in: 1 week
  script:
    - npm i
    - npx expo start &
    - EXPO_PID=$(echo $!)
    - npm run build:android:staging
    - npm run publish:staging -- --max-workers 1
    - curl -o myapp-android-${CI_BUILD_TAG}-staging.apk "$(npx expo url:apk --non-interactive)"
    - kill -9 $EXPO_PID
  only:
    - tags
  tags:
    - docker
````

And for the timeout while waiting for a branch: 

- https://github.com/kopax/expo-cli/commit/5a4d783d6cee3ff5edfd3c9da25b39a7384f3c40
- https://github.com/kopax/expo-cli/commit/47c821568c3fd436cb129c0925dd1bf6736ca699

**Comment by CauueSanttos** [comment]
It worked like this for me:

• I started the project using "yarn start", which in this case would be "expo start"

• To run the build, I ran "expo build: android" and it worked.

**Comment by inkxe-saismita** [comment]
> This is work for me.
> 
> 1. expo start
> 2. Open another tab
> 3. expo build:android

It works for me

**Comment by dipankar937** [comment]
This is for due to the React App not running at the time of building Android and ios app.
for more about ["connect econnrefused 127.0.0.1:19001 expo build"](https://www.developers-zone.com/in-react-native-build-app-for-android-and-ios)

**Comment by jannikbuschke** [comment]
Can this be reopened? This happens to me on a regular basis, and its frankly just annoying. The workarounds seem to work, but it would be cool to address the underlying issue.

**Comment by sukhveersingh0779** [comment]
> the commands recently got changed with the new update `exp build:android` to `expo build:android`
> 
> Reference: [Expo Building Standalone Apps](https://docs.expo.io/versions/v30.0.0/distribution/building-standalone-apps)



> the commands recently got changed with the new update `exp build:android` to `expo build:android`
> 
> Reference: [Expo Building Standalone Apps](https://docs.expo.io/versions/v30.0.0/distribution/building-standalone-apps)

Thankyou so much. It worked for me

**Comment by EhsanWebDev** [comment]
If none of above methods works for you.
Then try closing your emulator in windows / mac 
run expo start
split terminal in (vs code) and run expo publish

**Comment by YanDevDz** [comment]
You just have to put your connection on "LOCAL" and run expo build: android 😁😁
