### ISSUE TITLE
[sdk48.0.0-beta.2] iOS EAS Build is failing for react-native-maps

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#21155]
### Summary

After upgrading to Expo SDK 48 beta 2 the iOS build is failing in the prebuild phase with the following error:

yarn run v1.22.17
2 $ /Users/expo/workingdir/build/node_modules/.bin/expo prebuild --no-install --platform iOS
3 [stderr] [01:46:23] 
4 [stderr] This command is being executed with the global Expo CLI. Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
5 [stderr] To use the local CLI instead (recommended in SDK 46 and higher), run:
6 [stderr] › npx expo prebuild
7 - Creating native project directories (./ios and ./android) and updating .gitignore
8 ✔ Created native project | synced gitignore
9 - Adding Metro bundler config
10 - Updating your package.json scripts, dependencies, and main file
11 ✔ Updated package.json and added index.js entry point for iOS and Android
12 - Config syncing
13 [stderr] Using node to generate images. This is much slower than using native packages.
14 [stderr] › Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
15 - Config syncing
16 [stderr] Using node to generate images. This is much slower than using native packages.
17 [stderr] › Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
18 - Config syncing
19 ✖ Config sync failed
20 [stderr] [01:46:26] [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
21 [stderr] [01:46:26] Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
22 [stderr]     at /Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Maps.ts:199:19
23 [stderr]     at action (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
24 [stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
25 [stderr]     at action (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27)
26 [stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
27 [stderr]     at evalModsAsync (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
28 [stderr]     at compileModsAsync (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
29 [stderr]     at configureManagedProjectAsync (/Users/expo/workingdir/build/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:58:12)
30 [stderr]     at prebuildAsync (/Users/expo/workingdir/build/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:88:21)
31 [stderr]     at actionAsync (/Users/expo/workingdir/build/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:37:3)
32 [stderr] error Command failed with exit code 1.
33 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
34 yarn exited with non-zero code: 1

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.11.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/****/.rvm/gems/ruby-2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31, 32, 33
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^48.0.0-beta.2 => 48.0.0-beta.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.2 => 0.71.2 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.3.0
    Expo Workflow: managed

### Minimal reproducible example

Don't know since it's maybe related to react-native-maps package? Or config-plugin package?

**Comment by brentvatne** [comment]
hi there!

i created a new app with the beta, added react-native-maps, and ran `npx expo prebuild -p ios` - it worked as expected. please share a minimal reproducible example app!

**Comment by TrustyTechSG** [comment]
Just upgraded to SDK48, android build is fine, iOS build also facing the same issue "Cannot add Google Maps to the project's AppDelegate because it's malformed".

**Comment by mariomurrent-softwaresolutions** [comment]
I will try to create a minimum reproducible example.
Or do you have one?

**Comment by mariomurrent-softwaresolutions** [comment]
> hi there!
> 
> 
> 
> i created a new app with the beta, added react-native-maps, and ran `npx expo prebuild -p ios` - it worked as expected. please share a minimal reproducible example app!

Did you just add the dependency or also the map element with Google maps as provider?

**Comment by mariomurrent-softwaresolutions** [comment]
> hi there!
> 
> i created a new app with the beta, added react-native-maps, and ran `npx expo prebuild -p ios` - it worked as expected. please share a minimal reproducible example app!

My prebuild fails with
✖ Config sync failed
[ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.

**Comment by yardwerkz** [comment]
I found that this error occurs with `npx expo prebuild`, but if I run `npx expo run:ios` afterwards, it works.

**Comment by mariomurrent-softwaresolutions** [comment]
> I found that this error occurs with `npx expo prebuild`, but if I run `npx expo run:ios` afterwards, it works.

And what about the EAS build? This is failing as well?

**Comment by mariomurrent-softwaresolutions** [comment]
> hi there!
> 
> i created a new app with the beta, added react-native-maps, and ran `npx expo prebuild -p ios` - it worked as expected. please share a minimal reproducible example app!

Which version of react-native-maps are you using? it is not working for me with 1.3.0 or 1.4.0 ... When I'm adding the dependency to the package.json the prebuild fails:

[ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
    at /Users/mariomurrent/.nvm/versions/node/v16.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Maps.ts:199:19

**Comment by mariomurrent-softwaresolutions** [comment]
@brentvatne https://github.com/expo/expo/issues/21282#issuecomment-1437421616 There is the reproducible example :)
