### ISSUE TITLE
Build fails with fatal error: 'RCTAsyncLocalStorage.h' file not found

### ISSUE THREAD

**Issue by Yamini0** [expo/expo#21157]
### Summary

Hello everyone, since fews days I have an error when it s come to build my ios application with expo (the android application works correctly), during the fastlane build I have #import <React/RCTAsyncLocalStorage.h> | ^ 'React/RCTAsyncLocalStorage.h' file not found inside EXDevLauncherController.m
I tryied to follow the troubleshoot part of the asynclocalstorage documentation but I still have the same error.
<img width="861" alt="Screenshot 2023-02-10 at 5 52 18 PM" src="https://user-images.githubusercontent.com/77135583/218091596-f095a0dc-66aa-4fb7-bfd4-2fcd2330c06d.png">

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo": "^47.0.6",
"expo-dev-client": "~2.1.1",
"@react-native-async-storage/async-storage": "~1.17.3",

### Environment

production

### Reproducible demo

I don't for step to reproduce it.
For me also came from nowhere.

**Comment by callmephilip** [comment]
@Yamini0 same issue here. i nuked the Pods and reran `npx expo ios:run` and it's working again

**Comment by a-eid** [comment]
same issue for me [eas build link](https://expo.dev/accounts/youssefwilliam/projects/fashionai-reactnative-app/builds/6e1f6e52-0b84-4cc5-91d5-41246a25a1cb)
