### ISSUE TITLE
SDK 48 beta doesn't work in monorepo

### ISSUE THREAD

**Issue by Braden1996** [expo/expo#21168]
### Summary

Howdy! 👋
The prebuilt generated iOS project seems to be failing during pod-install in a monorepo context. Looking at the generated `Podfile`, I can see we make a call to `react_native_post_install`. It seems, with `react-native` `0.71.2` that this function has a new argument introduced, i.e. `def react_native_post_install(installer, react_native_path = "../node_modules/react-native", mac_catalyst_enabled: false)`.

Updating this function invocation in my Podfile to the following seems to fix the problem:
```
react_native_post_install(
      installer,
      File.dirname(`node --print "require.resolve('react-native/package.json')"`),
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
```

I suspect Expo's generation should be updated to reflect this?

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 3.3.1 - ~/.nvm/versions/node/v16.19.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
      Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/braden/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.3.0
    Expo Workflow: bare

### Minimal reproducible example

(Can do later if needed)

**Comment by brentvatne** [comment]
hey @Braden1996! definitely interested in learning more, just create a new issue when you get a chance to add a reproducible example!

**Comment by Braden1996** [comment]
> hey @Braden1996! definitely interested in learning more, just create a new issue when you get a chance to add a reproducible example!

Oh no - I'm such a noob! Constructing the repro made me discover I had "sdkVersion" in my `app.config.js` which the CLI seems to respect over the `package.json` `"expo"` version.

**Comment by jonsherrard** [comment]
hey @Braden1996,

I have just upgraded to expo 48 and I also have this issue in a mono repo, pod_install is looking for `react-native` in my `apps/expo` directory, but yarn is installing it in the root node_modules

```sh
packages.json
node_modules
  - react-native
apps
  - expo
    - node_modeules
      -react-native-safe-area-context (etc)
      
```

What did you do to fix this?

**Comment by Braden1996** [comment]
> hey @Braden1996,
> 
> I have just upgraded to expo 48 and I also have this issue in a mono repo, pod_install is looking for `react-native` in my `apps/expo` directory, but yarn is installing it in the root node_modules
> 
> ```shell
> packages.json
> node_modules
>   - react-native
> apps
>   - expo
>     - node_modeules
>       -react-native-safe-area-context (etc)
>       
> ```
> 
> What did you do to fix this?

@jonsherrard Check that your `package.json` and `yarn.lock` are in fact installing Expo v48. Also, in my case, I had `sdkVersion` in my `app.config.js` set to 47. Removing that entire field fixed the issue.

**Comment by jonsherrard** [comment]
Thanks for the reply @Braden1996, somehow I had my old Podfile lying around, I nuked everything and re-ran expo and things started working.
