### ISSUE TITLE
[docs] Wrong and ambiguous style prop "textDirection"

### ISSUE THREAD

**Issue by a777med** [expo/expo#21164]
### Summary

This section of the docs has multiple errors.

- It is referring to a React Native style property that does not exist, which is `textDirection`. 
- The example code is setting the direction to be always `left` rather than dynamic.
- The example code has `left` instead of `'left'` as a string.
- The example code has `...props` after the style prop, which could cause the style prop to be overridden.

I am not sure what `textDirection` is supposed to be.

### Link to the related docs page

https://docs.expo.dev/guides/localization/#text-alignment

**Comment by aleqsio** [comment]
@a777med
Thanks for the report - you're right, the code had some some draft code samples leftover, sorry! 
I don't really write too many docs so still learning this 😉 

https://github.com/expo/expo/pull/21171/files
We still take the props spread after the property so it's actually overridable by setting the RN `textAlign` property – it just provides a sensible default. Does this code make more sense now?
