### ISSUE TITLE
[expo-gl] createCameraTextureAsync doesn't resolve until unmount in Android production builds on SDK 47 

### ISSUE THREAD

**Issue by Rhysjc** [expo/expo#21163]
### Summary

I'm building an app around Tensorflow React Native and am having trouble with my release builds. It's worth noting here that this issue isn't specific to Tensorflow and I've got a minimal reproducible example that doesn't use it, my use of Tensorflow is just how I came across this issue.

The `@tensorflow/react-native` package provides a `cameraWithTensors` HOC that wraps `expo-camera`'s `Camera` component. The HOC accepts an `onReady` prop that gets called once it has done some setup with the GL context. The relevant code [is here](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/src/camera/camera_stream.tsx#L235), specifically you'll see it makes a call to `createCameraTextureAsync` [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/src/camera/camera_stream.tsx#L224). The issue I'm seeing 
**on Android** is that the `onReady` prop is never called in both production mode builds locally, and release builds installed via Google Play.

I've done a little debugging and it seems that `createCameraTextureAsync` only resolves once the component that makes the call to it is unmounting. After digging in to the `expo-gl` code, I can see that it's hanging on [this line](https://github.com/expo/expo/blob/main/packages/expo-gl/src/GLView.tsx#L151) which is where it makes a call to the native module, which makes sense given things work fine on iOS. I'm afraid that I've reached the limit of what I can debug at this point.

It's probably also important to point out that this doesn't happen when running a local dev build, or on production builds if I downgrade to Expo 46 (there's a branch in the linked example repo where I've done this).

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.1/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
      Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 23, 25, 27, 28, 30, 31, 32, 33
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.5.1
    Expo Workflow: managed

### Minimal reproducible example

Install the dependencies in this repo and then run `npx expo start --no-dev --minify -c` to start a production mode build
https://github.com/Rhysjc/createCameraTextureAsync-demo

**Comment by qender** [comment]
I'm also facing this issue.

**Comment by krzychuuu132** [comment]
Some progress ?
