### ISSUE TITLE
console.error makes iOS crash in release

### ISSUE THREAD

**Issue by stesvis** [expo/expo#21160]
### Summary

I finally figured out that when the app executes a `console.error(...)` it crashes an iOS app in release mode.
While debugging it's all working, but if you make a package with `expo publish` and run the app on an iOS device, it crashes (no logs, no info given).

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^47.0.13 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    Expo Workflow: managed

### Minimal reproducible example

Do an `expo publish` and then run it on iOS.
`log` and `warn` cause no harm, but `error` crashes my iOS app.

```js
export default function App() {

  console.log('log');
  console.warn('warning');
  console.error('error'); // crashes here

  return (
    <View>
      <Text>Hello world!</Text>
    </View>
  );
}
```

**Comment by stevesouth** [comment]
We just hit the issue too. Reproduction here, simply run:

npm run ios

And the app will crash due to the console.error in App.js

https://github.com/stevesouth/expo-console-error-crash

**Comment by babacarcissedia** [comment]
I had a similar experience. I ended up replacing `console.error` with `console.log`

**Comment by stargt** [comment]
Same here.
