### ISSUE TITLE
authsession native application (apk) does not open browser

### ISSUE THREAD

**Issue by yo34** [expo/expo#2117]
I tried this example https://github.com/expo/examples/tree/master/with-facebook-auth. 
Opened with the expo application, it's work well. When building an apk. The external browser is not opening.  Should I add special permission that's permit on an apk to open the default navigator ?

**Comment by viperin** [comment]
I have the same problem.
@yo34  did you manage to solve it?

**Comment by yo34** [comment]
@viperin sorry for delaying. No I don't found any solution or any workaround.
I read the code of expo application, I don't see any special permission.
I am stuck on this subject :(

**Comment by alessandropaglia** [comment]
I have the same problem

**Comment by viperin** [comment]
Finally I used Facebook integration instead of authsession
https://docs.expo.io/versions/v29.0.0/sdk/facebook

**Comment by alessandropaglia** [comment]
I need to connect to a custom oauth2 server

Il Mer 12 Set 2018, 17:44 Victor Périn <notifications@github.com> ha
scritto:

**Comment by itsMichaelBates** [comment]
I'm having the exact same issue. expo 31.0.2 with sdk version 31.0.0.

I have a button which calls `AuthSession.startAsync` and it works flawlessly through the expo app, but not as a standalone apk.

**Comment by itsMichaelBates** [comment]
I discovered this happens when a `scheme` has not been defined in the `app.json`. More is explained here: https://docs.expo.io/versions/latest/workflow/linking

After adding a scheme, this works as expected. I probably should have read the docs for AuthSession properly :/

**Comment by yo34** [comment]
@itsMichaelBates , thanks I will test with a scheme.

**Comment by crosshj** [comment]
THANKS, IT WORKS NOW:

I was experiencing what seems to be the same problem.  I added a scheme prop to my app.json like @itsMichaelBates suggested.  Worked!  Thanks for saving me some time and heartache.

SOME THINGS THAT DID NOT WORK:

I did read the docs initially, but this was not clear to me when I read them.  It was also not obvious to me that a standalone app must use a scheme in order for AuthSession to work in standalone app.

I tried debugging and did not see anything that lead me to conclude I needed a scheme.  

I also tried updating my sdk version (28 to 31).  I had trouble following the docs on that one; did not work until I observed what was happening with `expo init`.  But this also did not solve my problems.

And, the page about linking did not make the issue immediately obvious.

**Comment by hotdang-ca** [comment]
> THANKS, IT WORKS NOW:
> 
> I was experiencing what seems to be the same problem. I added a scheme prop to my app.json like @itsMichaelBates suggested. Worked! Thanks for saving me some time and heartache.
> 
> SOME THINGS THAT DID NOT WORK:
> 
> I did read the docs initially, but this was not clear to me when I read them. It was also not obvious to me that a standalone app must use a scheme in order for AuthSession to work in standalone app.
> 
> I tried debugging (android/adb) and did not see anything that lead me to conclude I needed a scheme.
> 
> I also tried updating my sdk version (28 to 31). I had trouble following the docs on that one; did not work until I observed what was happening with `expo init`. But this also did not solve my problems.
> 
> And, the page about linking did not make the issue immediately obvious.

On `v33`, it's still not very clear. Perhaps there is a larger userbase of Expo Client Distributions, than Standalone Apps, and so the Standalone requirements drift to the bottom...

Through troubleshooting, it seemed as though I need to add `exp` to my custom scheme. PS, don't do that.

I chose my own custom scheme (the docs seem to suggest it would have generated a random one for me??), and sure enough, everything works as expected.

**Comment by JaydenR** [comment]
@hotdang-ca Thank you for the PS, that solved my issue. 

I also assumed that I had to use exp as the custom scheme based on discussions I had seen elsewhere. Instead it caused issues when routing back as I had to manually choose between routing back to the built app or to Expo instead when running on an emulator and when running on a device it would just get stuck on the webview.

**Comment by EvanBacon** [comment]
Closing as this is fixed in the [new expo-auth-session](https://docs.expo.io/versions/latest/sdk/auth-session/) which utilizes `expo-web-browser`.
