### ISSUE TITLE
Metro for Web: resolverMainFields and module resolution

### ISSUE THREAD

**Issue by bndkt** [expo/expo#21175]
### Summary

I haven't dealt with configuring bundlers a lot, so please let me know if I have wrong assumptions or missing the point here. I'm trying to use Metro for Web in a project, so I enable it via the `expo.web.bundler` field in app.json, and it works fine.

Now I'm using a library like `@aws-sdk/client-cognito-identity`, which comes with different entry points in the package.json, for example:

```
{
  "browser": {
    "./dist-es/runtimeConfig": "./dist-es/runtimeConfig.browser"
  },
  "react-native": {
    "./dist-es/runtimeConfig": "./dist-es/runtimeConfig.native"
  },
}
```

When logging `console.log(config.resolver.resolverMainFields);` in metro.config.js, I see that the resolverMainFields in Expo are `[ 'react-native', 'browser', 'main' ]` (probably from React Native CLI?), so when I run `npx expo start`, the `./dist-es/runtimeConfig.native` from the above-mentioned package is chosen, which is correct and works. But when I now press `w` to open the app on web (or if I run `npx expo start --web`), the same entry point is chosen (because Metro's config.resolver.resolverMainFields remains unchanged), but now I get error messages because the library is not using the "browser variant" entry point and therefore trying to use modules like "crypto" or "http2" that are not available in the browser.

Is there any way to handle this distinction? It seems to me that two approaches (distinguishing platforms via resolverMainFields on the one hand and "bundling once, run everywhere" on the other) are clashing here. Are there any ideas for solving this or maybe it is solved and I'm just not getting it right?

### What platform(s) does this occur on?

Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/Library/pnpm/node
      Yarn: 1.22.19 - ~/Developer/GitHub/feld/node_modules/.bin/yarn
      npm: 8.19.2 - ~/Library/pnpm/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    Expo Workflow: managed

### Minimal reproducible example

- Enable metro for web
- `npm install @aws-sdk/client-cognito-identity`
- Add `import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity";` somewhere
- Run `npx expo start --web`

**Comment by bndkt** [comment]
Just found this in the docs:

> EXPO_METRO_NO_MAIN_FIELD_OVERRIDE (boolean) force Expo CLI to use the [resolver.resolverMainFields](https://facebook.github.io/metro/docs/configuration/#resolvermainfields) from the project's metro.config.js for all platforms. By default, Expo CLI will use ['browser', 'module', 'main'], which is the default for webpack, for the web and the user-defined main fields for other platforms.
Source: https://docs.expo.dev/workflow/expo-cli/

So it seems that what I was describing above is exactly the behavior with Webpack today, so it probably does make sense to strive for the same with Metro?

**Comment by dweinstein1** [comment]
Does anybody have a solution ?? 
Why was this issue closed? 

I'm using Local Expo's CLI `0.7.1`.
