### ISSUE TITLE
QR code broken

### ISSUE THREAD

**Issue by chulphan** [expo/expo#21180]
### Summary

When i execute expo app via `npx expo start`, QR visible but my camera cannot recognize the QR Code. (cannot run on device)

<img width="947" alt="image" src="https://user-images.githubusercontent.com/35016301/218399123-01ade2c6-8db6-4565-8a65-cc7a58a59b2c.png">

### SDK Version

47.0.13

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
      Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.13 => 47.0.13 
      react: 16.13.0 => 16.13.0 
      react-dom: 16.13.0 => 16.13.0 
      react-native: 0.68.2 => 0.68.2 
    Expo Workflow: bare

### Minimal reproducible example

1. Run npx expo start on terminal
2. Run camera app
3. Scan QR Code

**Comment by alanjhughes** [comment]
This is caused by the font you are using in your terminal.

**Comment by keith-kurak** [comment]
@chulphan As @alanjhughes noted, this appears to be related to your terminal font. If you can reproduce this on the stock terminal app, feel free to reopen. Also note that you can use the link just below the QR code to run the app on your device, no terminal changes required.

**Comment by chulphan** [comment]
Thank you!
