### ISSUE TITLE
[snack] There was a problem loading the requested app

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#2118]
### Steps to Reproduce

I think this may be a one-off issue, but here are the steps I followed:

1. Open a community snack
2. Paste in some new code
3. Share with device (enter device ID for iOS)
4. Open app, click on app in recently opened

### Expected Behavior

Snack opens on phone

### Actual Behavior

`There was a problem loading the requested app`
Note the `+SK_Tu5VIQ` on the end, could that be the issue?
 - [x] On the same wifi network
 - [x] On the same account
 - [x] Logged out then back in

<img src="https://user-images.githubusercontent.com/1566400/44286310-8261d100-a21d-11e8-9d9e-e363efdeedec.jpeg" width="50%" />

### Reproducible Demo

The snack in question: https://snack.expo.io/@buishi/inputaccessory-testing

**Comment by tcdavis** [comment]
Many thanks, @JulianKingman !
Sorry we missed testing on this. Should be resolved now :)

**Comment by JulianKingman** [comment]
Issue persists :(
Is there something I need to do?
Thx!

**Comment by tcdavis** [comment]
Can you try opening in private / incognito?

**Comment by JulianKingman** [comment]
That worked, thanks for the quick turn around :)
