### ISSUE TITLE
Expo Go on Android "Something went wrong

### ISSUE THREAD

**Issue by totallytotallyamazing** [expo/expo#21198]
### Summary

myApp is built in the masOS Monterey V 12.6.3 os and I'm using VSCode.
I was able to run my dev tests in ios and web simulators, and the Expo go android app simulator loaded on my android phone, all from the terminal command `npx expo start`. Suddenly my Expo Go android stopped working, so I found that I can run `expo start --tunnel` as a work around to get Expo Go and ios simulators running but now this does not work with web. 

Does anyone know what has happed with the `npx expo start` terminal command effecting the Expo Go app for android?

`package.json`
```JSON
{
  "name": "myApp",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/webpack-config": "^0.17.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/checkbox": "^0.5.14",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "expo": "^46.0.14",
    "expo-application": "^4.2.2",
    "expo-auth-session": "~3.7.4",
    "expo-camera": "~12.5.0",
    "expo-image-manipulator": "~10.4.0",
    "expo-image-picker": "~13.3.1",
    "expo-linear-gradient": "~11.4.0",
    "expo-random": "~12.3.0",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.7",
    "expo-web-browser": "~11.0.0",
    "firebase": "^9.10.0",
    "nativewind": "^2.0.11",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-deck-swiper": "^2.0.12",
    "react-native-dotenv": "^3.4.7",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-web": "~0.18.7",
    "yarn": "^1.22.19"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "tailwindcss": "^3.2.1"
  },
  "private": true,
  "packageManager": "yarn@1.22.1"
}
```

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/Documents/Derek/WebProjects/React_Native/iluvluv/node_modules/.bin/yarn
      npm: 9.4.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.4 
      expo: ^46.0.14 => 46.0.20 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.3.0
      expo-cli: 6.3.0
    Expo Workflow: managed

### Minimal reproducible example

`npx expo start` in VSCode terminal causes this error in Expo Go Android App but not ios simulator or web.
![Screenshot_20230213-151749](https://user-images.githubusercontent.com/6944394/218597585-98a52f4f-b5d0-4858-a07b-12cdcb56ea68.png)
![Screenshot_20230213-182954](https://user-images.githubusercontent.com/6944394/218598005-3f2f0a40-f256-4469-a76e-4cad0fea6c17.png)

**Comment by Reckit075** [comment]
any updates?

**Comment by ShivaBollam07** [comment]
any updates

**Comment by rimmelasghar** [comment]
For others who find this error.

1. your connection should be the same on your phone and on your PC.
2.  Internet connection your PC is connected to should have the firewall disabled.
3. If still a problem you see something like exp:127..... You can change your lan address and you can see it using expo start --lan. And use this command to change your URL set REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.200 <- your ip address

powershell command:
$Env:REACT_NATIVE_PACKAGER_HOSTNAME="192.168.0.200"

**Comment by vk-develops** [comment]
I'm also getting similar kind of error as "something went wrong. sorry about that you can go back to expo home or try to reload the project" please anyone help me resolve this error.

**Comment by totallytotallyamazing** [comment]
I'm currently using skd 48 using node -v 18, I run: `npx expo start` and it works for ios and android. In a second terminal I switch to node -v 16 with nvm (Node Version Manager), and run: `GENERATE_SOURCEMAP=false npx expo start --web`
This works for me.
Good Luck!

**Comment by rimmelasghar** [comment]
Any updates on this Issue?

**Comment by vk-develops** [comment]
No, I am still encountering the same problem as **"something went wrong. sorry about that you can go back to expo home or try to reload the project"**. And I have recently figured out that my network **IP address is different from the expo metro bundler IP address.** 

Example my IP: **10.10.10.18** Expo: Metro waiting on **exp://192.168.1.13:19000.**

So does anyone know how to resolve this issue. And I have connected my mobile phone and laptop to the same network connection.

**Someone please help me resolve this problem.**

**Comment by rimmelasghar** [comment]
Have you tried my solution?

**Comment by totallytotallyamazing** [comment]
> No, I am still encountering the same problem as **"something went wrong. sorry about that you can go back to expo home or try to reload the project"**. And I have recently figured out that my network **IP address is different from the expo metro bundler IP address.**
> 
> Example my IP: **10.10.10.18** Expo: Metro waiting on **exp://192.168.1.13:19000.**
> 
> So does anyone know how to resolve this issue. And I have connected my mobile phone and laptop to the same network connection.
> 
> **Someone please help me resolve this problem.**

please check out my edit above. I missed a mistake in my directions, I'm using "skd 47" Not "skd 48", sorry about that!

**Comment by JoseEduardoRivera** [comment]
Im usind node 20.9.0 and npm 10.1.0, its not my first time using React-Native, I had some projects but whith older versions, But now when I make new projects I have that message Error

**Comment by asrvd** [comment]
i changed the `start` script from `expo start` to `expo start --tunnel` (since global expo cli is now deprecated) & it worked perfectly for both android & web !

```json
  "scripts": {
    ...
    "start": "expo start --tunnel",
    ...
  },
```

![image](https://github.com/expo/expo/assets/68690233/0a53a6f8-e4e7-46f7-b080-707cb453687a)

**Comment by vk-develops** [comment]
I have created a new folder and initialized a new expo project using the command **npx create-expo-app my-app**. Then I changes my directory using the command **cd my-app**, Then I used the command **npx expo start** to run that expo project. After running the project I got the QR code and expo metro bundler waiting port address.
![expo out](https://github.com/expo/expo/assets/123179219/3bd2cf67-da36-4871-8d84-663d3c02ae72)


Then after scanning the QR code using the expo go app on my mobile I got an error saying **"something went wrong. sorry about that you can go back to expo home or try to reload the project"**.  Also I have connected my mobile and my pc with the same Wi-Fi connection. And I have figured out that the expo metro bundler waiting port address is different to the IP address of my Wi-Fi connection. 

**Example:  
Expo: Metro waiting on exp://192.168.1.13:8081.
My IP address: 127.0.0.1

It should be as Expo: Metro waiting on exp://127.0.0.1:8081.**

Also I did the same process on creating a expo project on my friend's laptop, And it worked fine as the both IP's are same as
**Expo: Expo: Metro waiting on exp://127.0.0.1:8081.
My friend's lap IP address: 127.0.0.1**

Also when I run the project using the command **npx expo start --tunnel** it works fine and by using tunneling it makes the app to run very slow.


**Someone please help me resolve this problem please.**
![Expo error](https://github.com/expo/expo/assets/123179219/5f6332d8-a453-46d1-be80-ae4ed681326b)

**Comment by Owhab** [comment]
> i changed the `start` script from `expo start` to `expo start --tunnel` (since global expo cli is now deprecated) & it worked perfectly for both android & web !
> 
> ```json
>   "scripts": {
>     ...
>     "start": "expo start --tunnel",
>     ...
>   },
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/68690233/286495329-0a53a6f8-e4e7-46f7-b080-707cb453687a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTEyMDksIm5iZiI6MTcwMzY5MDkwOSwicGF0aCI6Ii82ODY5MDIzMy8yODY0OTUzMjktMGE1M2E2ZjgtZTRlNy00NmY3LWIwODAtNzA3Y2I0NTM2ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMjMyYWIzMzcxYWEyNTc0ZTMwZjNjNGMzZjBkNDI5NDAwNzdiZmYxNWNkMTE2YTY1YzIwYjUzYzBiOWY5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YbsXuOuHYWbO1l9RUqQu0ly0nG9aQ1NKzRPiJ501gzg)

This Works for me. Thnaks

**Comment by vk-develops** [comment]
> > i changed the `start` script from `expo start` to `expo start --tunnel` (since global expo cli is now deprecated) & it worked perfectly for both android & web !
> > ```json
> >   "scripts": {
> >     ...
> >     "start": "expo start --tunnel",
> >     ...
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/68690233/286495329-0a53a6f8-e4e7-46f7-b080-707cb453687a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTEyMDksIm5iZiI6MTcwMzY5MDkwOSwicGF0aCI6Ii82ODY5MDIzMy8yODY0OTUzMjktMGE1M2E2ZjgtZTRlNy00NmY3LWIwODAtNzA3Y2I0NTM2ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMjMyYWIzMzcxYWEyNTc0ZTMwZjNjNGMzZjBkNDI5NDAwNzdiZmYxNWNkMTE2YTY1YzIwYjUzYzBiOWY5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YbsXuOuHYWbO1l9RUqQu0ly0nG9aQ1NKzRPiJ501gzg)
> 
> This Works for me. Thnaks

Thank you! it works but using the tunneling makes the app loading speed very slow. Is there any other way to make it work as default??

**Comment by Chamesss** [comment]
I encountered this kind of issue and for me, switching to airplane mode then reconnecting solved the problem. I honestly still don't have any explanation to it, maybe some kind of misconfiguration or firewall related issue, anyways I hope this helps.

**Comment by niranjandasMM** [comment]
Try running with tunnel argument :
`expo start --tunnel`

**Comment by vk-develops** [comment]
> I encountered this kind of issue and for me, switching to airplane mode then reconnecting solved the problem. I honestly still don't have any explanation to it, maybe some kind of misconfiguration or firewall related issue, anyways I hope this helps.

I have also tried this solution but it doesn't work. But anyways using the tunnel flag makes it work. But using tunneling makes the app loading speed very slow.

**Comment by ndigirigijohn** [comment]
Manually setting the environmental variable `REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.200 <- your ip address` and refreshing my phone's network(Flight mode and back as suggested above) worked.

**Comment by subham2sahoo** [comment]
> I have created a new folder and initialized a new expo project using the command **npx create-expo-app my-app**. Then I changes my directory using the command **cd my-app**, Then I used the command **npx expo start** to run that expo project. After running the project I got the QR code and expo metro bundler waiting port address. ![expo out](https://private-user-images.githubusercontent.com/123179219/289008358-3bd2cf67-da36-4871-8d84-663d3c02ae72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDMwMDEsIm5iZiI6MTcwNzkwMjcwMSwicGF0aCI6Ii8xMjMxNzkyMTkvMjg5MDA4MzU4LTNiZDJjZjY3LWRhMzYtNDg3MS04ZDg0LTY2M2QzYzAyYWU3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwOTI1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTZjMjFiNDBiZDE4Nzc5NTNiMzBjZjMyNGJlOTIxYWU4ZThiOTc4YmY4YjUyMzY4NWE3NTYxOTk3YmQxZmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.okjq11fQNXzx9C-G1EhvjONizqdTN9Fp9391vOAhiO4)
> 
> Then after scanning the QR code using the expo go app on my mobile I got an error saying **"something went wrong. sorry about that you can go back to expo home or try to reload the project"**. Also I have connected my mobile and my pc with the same Wi-Fi connection. And I have figured out that the expo metro bundler waiting port address is different to the IP address of my Wi-Fi connection.
> 
> **Example: Expo: Metro waiting on exp://192.168.1.13:8081. My IP address: 127.0.0.1
> 
> It should be as Expo: Metro waiting on exp://127.0.0.1:8081.**
> 
> Also I did the same process on creating a expo project on my friend's laptop, And it worked fine as the both IP's are same as **Expo: Expo: Metro waiting on exp://127.0.0.1:8081. My friend's lap IP address: 127.0.0.1**
> 
> Also when I run the project using the command **npx expo start --tunnel** it works fine and by using tunneling it makes the app to run very slow.
> 
> **Someone please help me resolve this problem please.** ![Expo error](https://private-user-images.githubusercontent.com/123179219/289012433-5f6332d8-a453-46d1-be80-ae4ed681326b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDMwMDEsIm5iZiI6MTcwNzkwMjcwMSwicGF0aCI6Ii8xMjMxNzkyMTkvMjg5MDEyNDMzLTVmNjMzMmQ4LWE0NTMtNDZkMS1iZTgwLWFlNGVkNjgxMzI2Yi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMDkyNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVlYjc3YmQzODU2ZTg3NWY2MzliMzQxZGFkMjQwODVkNTBiYWM2MjVlZjViYjg1NzkzMmFiNjY1MmRlZDM0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7g3PmsQg-YOOVtnHRc1fzMffnbdh2xicqN041dQwq8A)

have you got any sol on this ?

**Comment by BroLetsCodeIt** [comment]
## This works for me . 

- Uninstall the expo-cli : 
```sh
npm rm -g expo cli
```
- Again install the expo cli : 
```sh
npm  install -g expo-cli
```

- Install the latest version of nodejs from the offical nodejs website.

- Create the Application : 
```
npx create-expo-app  my-app
```

Now start the development server

```sh
npx expo start --tunnel
```

then stop the server 
again start the server with LAN connection 

```sh
npx expo start
```

This works for me. I hope it will works for you as well .

Thank you.

**Comment by ranbir7** [comment]
using the tunnel argument worked for me !
**npx expo start --tunnel**

**Comment by NoobMahbub** [comment]
This is because your expo app ip address and your pc ip address is different

You can fix it by running this command as an administrator on you windows powershell: 

```setx /M REACT_NATIVE_PACKAGER_HOSTNAME 192.168.0.104``` (replace this ip address with your current pc ip address)

I have also made a video on this topic

You can watch it for better understanding: https://youtu.be/tSP0VECZ61k?si=tG9j4Vcf7kySI4r9

**Comment by igordg777** [comment]
Hello! The solution to this problem for me was to create a new Windows account, where I wrote my name in English, rather than in Russian. A similar problem may arise with Android Studio. Now I am working with React Native under a new Windows account with an English name. Maybe this will help someone. Dear Expo creators, I would like to kindly request you to pay attention to this matter. Thank you.

**Comment by eulier1** [comment]
> For others who find this error.
> 
>     1. your connection should be the same on your phone and on your PC.
> 
>     2. Internet connection your PC is connected to should have the firewall disabled.
> 
>     3. If still a problem you see something like exp:127..... You can change your lan address and you can see it using expo start --lan. And use this command to change your URL set REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.200 <- your ip address
> 
> 
> powershell command: $Env:REACT_NATIVE_PACKAGER_HOSTNAME="192.168.0.200"

For those working on WSL this solution from @rimmelasghar works just instead.
1. Go inside your WSL react-native or expo app
2. add this command in your bash `export REACT_NATIVE_PACKAGER_HOSTNAME="local ip address"`

And this works like charm.

Just a question, how do we get access to the React native Environment variables reference?.

**Comment by ionansantos** [comment]
> mudei o `start`script de `expo start`para `expo start --tunnel`(já que o global expo cli agora está obsoleto) e funcionou perfeitamente para Android e web!
> 
> ```json
>   "scripts": {
>     ...
>     "start": "expo start --tunnel",
>     ...
>   },
> ```
> 
> ![imagem](https://private-user-images.githubusercontent.com/68690233/286495329-0a53a6f8-e4e7-46f7-b080-707cb453687a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjM5NTQsIm5iZiI6MTcxNDIyMzY1NCwicGF0aCI6Ii82ODY5MDIzMy8yODY0OTUzMjktMGE1M2E2ZjgtZTRlNy00NmY3LWIwODAtNzA3Y2I0NTM2ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEzMTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNGQ0OTE3NDQ2MDI4NTA2NmM5OWJiMWU0MmQ4MGFlMDBmNjkyMWFiZmNhYWZiNDQxMGU5MDI2OGY2NDcwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UaJzkmeB_-XLSl_KSd3CUSG_0v6T0XMGXiPDYIfVSWI)

funcionou para mim !! :100:  :rocket:
