### ISSUE TITLE
Building standalone Android app from detach version

### ISSUE THREAD

**Issue by hle50** [expo/expo#212]
I have been using react-native along with ExpoKit by using `$ exp detact` command.
Now i want to make a standalone build that able to delivery to our customer but i dont know how.
I try build from the android studio but when run the app, it's required the exp server or something to start. I found some instructions from google but mostly they're using pure react-native project, it's created from `$ react-native init`.
I had also try this `$ react-native bundle --platform android --dev false --entry-file main.js --bundle-output android/app/src/main/assets/main.bundle --assets-dest android/app/src/main/res/` but i got issue with the fonts load. I'm using this in my code
```
Font.loadAsync({
      'Roboto_medium': require('./assets/fonts/Roboto_medium.ttf')
    });
```
It's keeping say module `'./assets/fonts/Roboto_medium.ttf'` not found
Please help me out!

**Comment by hle50** [comment]
I resolved this issue.

**Comment by Ali-Ayyad** [comment]
Hey @hle50 can you state what was the problem ?

**Comment by webdevbyjoss** [comment]
@hle50 hey, have the same issue right now. How did you managed to solve it?
