### ISSUE TITLE
Add PDF viewer to expo core

### ISSUE THREAD

**Issue by wedelgaard** [expo/expo#2120]
I know this have been raised/asked before. But would really love Expo to include a rich PDF module like [react-native-pdf](https://github.com/wonday/react-native-pdf)

I know its possible to use a WebView to embed the PDF URL in Google Drive viewer or use [rn-pdf-reader-js](https://github.com/xcarpentier/rn-pdf-reader-js), but these solutions have a lot of limitations.

A rich PDF viewer should be core for a smartphone app of 2018? :)

**Comment by xcarpentier** [comment]
You can upvote here: https://expo.canny.io/feature-requests/p/pdf-viewer

**Comment by wedelgaard** [comment]
Thx 👍 Upvoted it! :)

**Comment by ninjasun** [comment]
It will be great if you can print it..

**Comment by Shincham** [comment]
Indeed.

And also, rn-pdf-reader-js don't work for local files... it gives an error like "Invalid response for blob" when you try to use a local pdf file...
