### ISSUE TITLE
Expo map search to retrieve all gyms/parks

### ISSUE THREAD

**Issue by kbthetruth** [expo/expo#2121]
Hi am I wanting to use expo with mapview etc to grab and return the nearby gyms/parks. Is this possible yet? I could not find documentation and such a thing.

**Comment by mattfca** [comment]
you can call google api for lat long of locations, and map with MapView

**Comment by sjchmiela** [comment]
Hey, unfortunately this isn't something Expo allows you to do. 😞 As @mattfca explained, you should use some third-party API (eg. Google) for that. 🙂
