### ISSUE TITLE
Environment variables are overlooked from eas.json when eas update using

### ISSUE THREAD

**Issue by emehmet** [expo/expo#21213]
When I use eas build it reads environment variables from eas.json file. But when I use eas update, the environment variables are read from the .env file.
I do not understand why?

_Originally posted by @emehmet in https://github.com/expo/expo/discussions/20742_

**Comment by brentvatne** [comment]
the environment variables in eas.json exist under the `build` key - they are used for builds. they are set on the remote environment where the build occurs. EAS Update generates your JS bundle locally using whatever your local env is.
