### ISSUE TITLE
got error spawn npm ENOENT

### ISSUE THREAD

**Issue by palash7563** [expo/expo#2122]
### Environment
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

### Steps to Reproduce

1.running my react native project through expo by expo start

### Expected Behavior
must start the react native manager and must show the qr code

(Write what you thought would happen.)

### Actual Behavior
Got error

`yarn run v1.7.0
$ expo start
This command requires Expo CLI.
Do you want to install it globally [Y/n]? y
Installing the package 'expo-cli'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by palash7563** [comment]
reverted back to @28.0 version works fine

**Comment by DanilaGegele** [comment]
I have the same problem :(

**Comment by thomashagstrom** [comment]
Can confirm: a new `expo init` app is broken, until you downgrade to 28.0.0:
https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530

**Comment by saadkhan6670** [comment]
Experiencing the same issue, how can I downgrade to an earlier version?

**Comment by davidgithub1980** [comment]
Having the same problem (expo command tool version 2.2.0). 
**_expo build:android_** works fine, but **_expo build:ios_** generates the following error after trying to enter apple id password:
![ioserr](https://user-images.githubusercontent.com/6930312/47950306-b6ad7980-df50-11e8-91a5-204f0ca6d181.PNG)

**Comment by palashg7563** [comment]
> Experiencing the same issue, how can I downgrade to an earlier version?

change the version in package.json

**Comment by ghasemikasra39** [comment]
same issue. no solution ?

**Comment by rafiqm** [comment]
Error still occurring on expo-cli 2.10.1, Windows 7.

For what it's worth, this issue references the code that is causing the problem:
#https://github.com/expo/expo-cli/issues/328
