### ISSUE TITLE
[docs] Symfony/expo-notifier

### ISSUE THREAD

**Issue by nmateo** [expo/expo#21220]
### Summary

Sending message from the symfony/expo-notifier package always return invalid_token, despite the token added:

````Unable to post the Expo message: {"error":"invalid_token","error_description":"The bearer token is invalid"}"````
Without or with token set & activated Enhanced Security for Push Notifications.

Code is as below

````
    public function createOrderNotif(string $token, int $offerId)
    {
        $options = new ExpoOptions(self::EXPO_TOKEN,
                                    [
                                                'title' => 'Nouvelle offre',
                                                'subtitle' => 'Vous avez reçu une nouvelle offre de mission !',
                                                'data' => json_encode(['offerId' => $offerId]),
                                                'priority' => 'high',
                                                'sound' => 'default',
                                                'body' => 'Test',
                                                'to' => $token
                                    ]);
        $message = new PushMessage('Nouvelle offre', 'Test2', $options);
        $message->transport('expo');

        $this->notifier->send($message);
    }
````

### Link to the related docs page

https://docs.expo.dev/push-notifications/sending-notifications/#push-tickets

**Comment by brentvatne** [comment]
this issue is better suited for https://github.com/solvecrew/ExpoNotificationsBundle

this client library is maintained by @solvecrew, not expo :)

**Comment by nmateo** [comment]
The docs is still not up to date, this package by solvecrew is dead since 4 years, the new package is:
https://github.com/symfony/expo-notifier
And it seems to work on our end but the problem seems to be on expo push server.

**Comment by nmateo** [comment]
Can you re-open the issue please @brentvatne ?

**Comment by brentvatne** [comment]
can you open a pull request?

**Comment by brentvatne** [comment]
nevermind, i just made the change: https://github.com/expo/expo/commit/360382816b0fb2dfdc88cccd1659340efc786f80
