### ISSUE TITLE
Getting "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found" when making SSL request from EXPO to an API with a Web Application Firewall ahead

### ISSUE THREAD

**Issue by asanur** [expo/expo#21235]
### Minimal reproducible example

----

### Summary

I'm triying to make a https request to an API with a Web Application Firewall ahead from EXPO and I'm getting this error:
"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found". 

When I try to access the same URL from the browser, I get the data, but not from EXPO.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4 
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    Expo Workflow: managed

**Comment by weizihua** [comment]
Why should we close this question? Everyone has encountered this problem.

**Comment by linonetwo** [comment]
THis works https://github.com/expo/expo/issues/16451#issuecomment-1151096831
