### ISSUE TITLE
[SDK 48][expo-updates] Could not read embedded manifest; java.io.FileNotFoundException: app.manifest

### ISSUE THREAD

**Issue by thespacemanatee** [expo/expo#21238]
### Minimal reproducible example

NA

### Summary

After updating to SDK 48, my release builds are throwing this error in logcat. Seems related to #19721 #19693 #19624

```
java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. app.manifest
     at vh.b.a(EmbeddedManifest.kt:102)
     at th.i.x(LoaderTask.kt:39)
     at th.i.D(LoaderTask.kt:106)
     at expo.modules.updates.b.P(UpdatesController.kt:132)
     at expo.modules.updates.b$a.b(UpdatesController.kt:22)
     at expo.modules.updates.UpdatesPackage$b.g(UpdatesPackage.kt:19)
     at be.f.createReactInstanceManager(ReactNativeHostWrapperBase.kt:23)
     at com.facebook.react.w.b(ReactNativeHost.java:10)
     at com.cams.cams_app.MainApplication.onCreate(MainApplication.java:12)
     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
     at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loopOnce(Looper.java:201)
     at android.os.Looper.loop(Looper.java:288)
     at android.app.ActivityThread.main(ActivityThread.java:7872)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Environment

```sh
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.asdf/installs/nodejs/16.15.0/bin/node
      Yarn: 1.22.19 - ~/Documents/GitHub/CAMS_App/node_modules/.bin/yarn
      npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/thespacemanatee/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Giraffe 2022.3.1 Canary 4 Giraffe 2022.3.1 Canary 4
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.1 => 48.0.1 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    Expo Workflow: bare
```

**Comment by tylercote** [comment]
@thespacemanatee Did you ever end up resolving this issue? I am seeing the same thing after upgrading to SDK 48.0.1

**Comment by thespacemanatee** [comment]
@tylercote I did not. There's no easy way to reproduce it either so I guess we are stuck since the expo team won't work on it unless more people make noise.

**Comment by ken0x0a** [comment]
for sdk 48, that might be related to
https://github.com/expo/expo/blob/11c0cbb32e6867b1e2103353493c452d240c4e98/packages/expo-updates/scripts/create-manifest-android.gradle#LL65C21-L65C22

You can avoid this error by put `project.ext.react` back to "android/app/build.gradle"
```gradle
project.ext.react = [
  bundleInDev: true,
  bundleInYourFlavourInPascalCase: true,
]
```

**Comment by conor909** [comment]
Im seeing a similar issue in `expo 48.0.4`.  
![Screenshot 2023-03-24 at 14 20 29](https://user-images.githubusercontent.com/2417359/227549777-7f99c7bf-bdd1-4f2b-a450-e12008f70f36.png)

**Comment by PhillipFraThailand** [comment]
Also experiencing this

**Comment by Thixz** [comment]
Playstore is alerting me about this :

java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. 

Also my app is not opening after downloading it in playstore, It only works if a build it and download directly from expo build :/

**Comment by Levi-Teixeira** [comment]
Also having this issue while trying to run the .apk file generated from EAS.

 I realized that the `eas build --profile preview --platform android ` command make these changes in the `AndroidManifest.xml `file
![image](https://github.com/expo/expo/assets/69545312/033d8e97-49bb-4b93-b7da-1739d391e85d)

The build runs fine in both the simulator and on IOS, tho.

**Comment by Thixz** [comment]
> Also having this issue while trying to run the .apk file generated from EAS.
> 
> I realized that the `eas build --profile preview --platform android ` command make these changes in the `AndroidManifest.xml` file ![image](https://user-images.githubusercontent.com/69545312/253652979-033d8e97-49bb-4b93-b7da-1739d391e85d.png)
> 
> The build runs fine in both the simulator and IOS, tho.

Did you configured any lnik for updates in app.json like this : 
 ```
"updates":{
      "url": "https://..."
    }
```
?

**Comment by mhammerc** [comment]
After upgrading to SDK 49, same manifest error with expo-updates.

**Comment by AntoineAndo** [comment]
I encounter the same problem with SDK 49.

**Comment by foyarash** [comment]
Hello

I encountered the same issue. I am still using the classic updates system.

I fixed the error by adding  `useClassicUpdates: true` in the expo config, in the `updates` field

However, i'm encountering another error:

`No launchable update was found. If this is a bare workflow app, make sure you have configured expo-updates correctly in android/app/build.gradle.`

**Comment by Thixz** [comment]
> After upgrading to SDK 49, same manifest error with expo-updates.
> 
> **EDIT:** I have the same bug on SDK 48 now.
> 
> On SDK 48, a previous version of my app was working fine. The new version isn't working anymore. The "only" applicable change between the two versions I think is:
> 
> ```diff
> --- "@expo/config-plugins": "~6.0.0",
> +++ "@expo/config-plugins": "~7.1.0",
> ```
> 
> In my `package.json`. Could it be it? I have `expo-updates` installed but no specific configurations. I also use sentry.

I had to install expo updates to my project because of sentry update on Expo 48, maybe you're experiencing the same issue that I was. I installed expo-updates, but didn't configured anything at all, that was my mistake...
If you install expo-updates in your project, even though you're not using it, you must at least configure a link to updates in app.json like this :

"updates":{
     "url": "https://..."
   }

This url you'll find in your android manifest, I don't remember exactly the property there, but it'll be the only link related to expo-updates.

**Comment by mhammerc** [comment]
> > After upgrading to SDK 49, same manifest error with expo-updates.
> > **EDIT:** I have the same bug on SDK 48 now.
> > On SDK 48, a previous version of my app was working fine. The new version isn't working anymore. The "only" applicable change between the two versions I think is:
> > ```diff
> > --- "@expo/config-plugins": "~6.0.0",
> > +++ "@expo/config-plugins": "~7.1.0",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In my `package.json`. Could it be it? I have `expo-updates` installed but no specific configurations. I also use sentry.
> 
> I had to install expo updates to my project because of sentry update on Expo 48, maybe you're experiencing the same issue that I was. I installed expo-updates, but didn't configured anything at all, that was my mistake... If you install expo-updates in your project, even though you're not using it, you must at least configure a link to updates in app.json like this :
> 
> "updates":{ "url": "https://..." }
> 
> This url you'll find in your android manifest in the property EXPO_UPDATE_URL. It was created automatically when installed expo-updates to your project as I understood.
> 
> The moment that I did this I had no more problems.

Thank you very much, you are completely right!!

Following your instructions and the documentation I ran `eas update:configure` which added the `updates.url` key.

It immediately fixed the crash on my end.

But, this sentry documentation doesn't mention `eas update:configure` is required.

https://docs.expo.dev/guides/using-sentry/

**Comment by Thixz** [comment]
> > > After upgrading to SDK 49, same manifest error with expo-updates.
> > > **EDIT:** I have the same bug on SDK 48 now.
> > > On SDK 48, a previous version of my app was working fine. The new version isn't working anymore. The "only" applicable change between the two versions I think is:
> > > ```diff
> > > --- "@expo/config-plugins": "~6.0.0",
> > > +++ "@expo/config-plugins": "~7.1.0",
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In my `package.json`. Could it be it? I have `expo-updates` installed but no specific configurations. I also use sentry.
> > 
> > 
> > I had to install expo updates to my project because of sentry update on Expo 48, maybe you're experiencing the same issue that I was. I installed expo-updates, but didn't configured anything at all, that was my mistake... If you install expo-updates in your project, even though you're not using it, you must at least configure a link to updates in app.json like this :
> > "updates":{ "url": "https://..." }
> > This url you'll find in your android manifest in the property EXPO_UPDATE_URL. It was created automatically when installed expo-updates to your project as I understood.
> > The moment that I did this I had no more problems.
> 
> Thank you very much, you are completely right!!
> 
> Following your instructions and the documentation I ran `eas update:configure` which added the `updates.url` key.
> 
> It immediately fixed the crash on my end.
> 
> But, this sentry documentation require to install `expo-updates`, but doesn't mention that `eas update:configure` is required, which is misleading. If my assumptions are correct, maybe we should open an issue/PR to update this documentation?
> 
> https://docs.expo.dev/guides/using-sentry/

Yeah... I mean, they should at least mention that expo-updates require some configurations... Sentry's documentation only says that it deppends on expo-updates and some other libs... And that's all... I spent almost a whole day to figure that expo-updates was in lack of configurations, since I don't use it...

**Comment by joeporpeglia** [comment]
FYI `sentry-expo@7.0.1` removed the dependency on `expo-updates` - see https://github.com/expo/sentry-expo/pull/356

**Comment by rpulkka** [comment]
Thanks @joeporpeglia for pointing out that Sentry does not require expo-updates anymore. I was able to resolve the issue on my project by simply uninstalling expo-updates: `npm uninstall expo-updates`.
