### ISSUE TITLE
[docs] missing docs page for expo-permissions

### ISSUE THREAD

**Issue by darcien** [expo/expo#21245]
### Summary

I'm trying to find the docs page for [`expo-permissions`](https://github.com/expo/expo/tree/main/packages/expo-permissions).

Both docs link in the readme does not link to the API docs properly.
![image](https://user-images.githubusercontent.com/19742419/219333750-8d706c9c-0c1e-459a-a501-ef99c10d94c1.png)
- first link leads to 404
- second link redirects to https://docs.expo.dev/guides/permissions/?redirected, which is a guide for configuring permissions, not the API docs

Searching permissions on the docs also does not have any `expo-permissions` result
![image](https://user-images.githubusercontent.com/19742419/219334283-dccdf3d4-2fa7-4a78-90a1-c65e80c56933.png)

Is the missing docs intended because `expo-permissions` is an internal Expo package and only used by other Expo SDK? If not, it would be nice if there are docs page on the Expo docs.

---

In my use case, I'm using a 3rd party SDK that requires camera and mic permissions. Planning to use `expo-permissions` to check for denied permissions and give better error message to user when permissions are denied.

### Link to the related docs page

https://github.com/expo/expo/tree/main/packages/expo-permissions

### Anything else?

Thanks Expo team for making RN development even better <3

**Comment by brentvatne** [comment]
(i'll update the README for expo-permissions to make this clear, thanks for pointing that out!)

**Comment by darcien** [comment]
Hi @brentvatne, thanks for the explanation.

Are there any official recommendations from Expo team for permission-only SDK?
For example, [`react-native-permissions`](https://github.com/zoontek/react-native-permissions).

Asking this because I see the MediaLibrary example use native code for permission checking.
It would be a waste if I installed the whole media module just to use the permission check.

**Comment by brentvatne** [comment]
the library you're using should include its own permission requesting methods - otherwise i might be a bit wary of that library. [react-native-vision-camera](https://mrousavy.com/react-native-vision-camera/docs/guides/#gettingrequesting-permissions), for example, includes similar permission requester methods.
