### ISSUE TITLE
CFBundleDisplayName not working in info.Plist for iOS apps

### ISSUE THREAD

**Issue by ethanj20** [expo/expo#21244]
### Build/Submit details page URL

https://expo.dev/accounts/demi_composting/projects/demi_app/builds/d0fe49db-b45a-472d-a033-fa8f87179c98

### Summary

I'd like to be able to change the display name for my app. For example, if my app name was `My Company App` (as defined by `name:` in `app.config.js`, and I wanted to make the name below the app icon when people download the app read `abc123`, I would think I could have the following setup:

```json

name: "My Company App"
...
ios: {
   infoPlist {
      NSCameraUsageDescription:
        'this app uses the camera for reasons xyz',
      CFBundleDisplayName: 'abc123',
    }
}
....

```

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.0.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

create an app w/ an app json as follows, build and submit to testflight, and check title under the icon

```json

name: "My Company App"
...
ios: {
   infoPlist {
      NSCameraUsageDescription:
        'this app uses the camera for reasons xyz',
      CFBundleDisplayName: 'abc123',
    }
}
....

```

**Comment by EvanBacon** [comment]
This appears fixed in Expo SDK 49, where `npx expo config --type introspect` shows that `CFBundleDisplayName` is preserved in the Info.plist.
