### ISSUE TITLE
light sensor

### ISSUE THREAD

**Issue by AntonSmatanik** [expo/expo#2126]
I'm trying to develop light sensor for our app, but I have the problem with Android. As far as I undestand it, there is no simple way how to build LightSensor. Maybe only possibility is there with AR for iOS:

https://blog.expo.io/the-new-arkit-api-for-react-native-5b6d36937a63

Am I wrong?

**Comment by sjchmiela** [comment]
Hey, @AntonSmatanik! You're right in assuming there is no other way than to use [AR](https://docs.expo.io/versions/v31.0.0/sdk/AR) to easily create a light sensor with Expo.

If you deem this solution not sufficient, please submit a feature request at https://expo.canny.io. (Similarly to Volume Sensor, please include links to any third-party libraries that would help you solve your issue.) 🙂
