### ISSUE TITLE
scheduleNotificationAsync doesn't work in a background task

### ISSUE THREAD

**Issue by Jiia** [expo/expo#21267]
### Minimal reproducible example

https://snack.expo.dev/@jansutin/expo-notification-issue

### Summary

Triggering notifications from a TaskManager background task don't appear to be working on an Android 13 device (Pixel 6 Pro) using Expo 47.0.12.

When a notification is created in a background task using `scheduleNotificationAsync`, it resolves succesfully but the notification is never presented by the system.

```js
await Notifications.scheduleNotificationAsync({
  content: { title: 'Expo notification', body: 'scheduleNotificationAsync' },
  trigger: null,
})
```

I tested this also by creating a preview build, and the same behaviour occurs. I also tried creating a notification channel and setting the importance to maximum.

But if you use the deprecated `presentNotificationAsync`, the notifications works flawlessly in the background.

```js
await Notifications.presentNotificationAsync({
  title: 'Expo notification',
  body: 'presentNotificationAsync'
})
```

Is the support for presenting notifications immediately in the background dropped intentionally or accidentally in the new `scheduleNotificationAsync` method? I don't want to needlessly complicate the app by introducing push notifications when they're not needed.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/n/bin/node
      npm: 8.19.2 - ~/n/bin/npm
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.6.0
    Expo Workflow: bare

**Comment by Jiia** [comment]
I found out that it's only a null `trigger` that doesn't work. If you specify `channelId` and set `seconds` > 0 then the notifications work. This is counter to the documentation that says a null `trigger` presents the notification immediately.

**Comment by jurica-penjgusic** [comment]
Probably  it has something with SCHEDULE_EXACT_ALARM permisssion requires for Android 13. 
Documentatation can be found at android section permission at [Expo Notifications docs](https://docs.expo.dev/versions/v47.0.0/sdk/notifications/)
