### ISSUE TITLE
[docs] Debuggers documentation do not mention they do not work with hermes

### ISSUE THREAD

**Issue by Nek-** [expo/expo#21272]
### Summary

I recently installed firebase in my application (to use analytics). This forced me to drop flipper debugger because it seems to be incompatible with firebase from what I read in several posts and the documentation of firebase.

After this adventure, I had no more debugger. I thought I could manage to get the network usage by using another well-known debugger listed in the [expo documentation](https://docs.expo.dev/workflow/debugging/). But after many many many tries, and some issues I finally find... It seems that they are actually not compatible with the (new?) hermes engine.

To avoid people losing a lot of time I think mentioning this fact in the documentation would be super-great.

### Link to the related docs page

https://docs.expo.dev/workflow/debugging/

**Comment by brentvatne** [comment]
remote js debugging is actually a terrible way to debug an application! hermes supports a much better approach - it uses chrome devtools to connect to the running js engine on the device. you can launch the debugger by pressing `j` in the terminal ui or pressing "Open JS Debugger" in the dev menu

**Comment by brentvatne** [comment]
coming soon, but yes if you want network inspector you can use flipper. it also works well with hermes and is indeed intended for use with hermes

**Comment by Nek-** [comment]
> coming soon

What do you mean? (Since I'm using firebase and I cannot use flipper, I'm very interested in 😄 )

**Comment by brentvatne** [comment]
@Nek- we'll be talking about it at app.js on friday this week, and then we'll provide information on how to use it in sdk 49 :)

**Comment by Nek-** [comment]
@brentvatne is there any stream planned? ^^

**Comment by brentvatne** [comment]
i believe you will be able to find the stream on https://appjs.co/

**Comment by dalley8626** [comment]
@brentvatne do u have a youtube link for it?

**Comment by brentvatne** [comment]
@dalley8626 https://www.youtube.com/watch?v=t0KDn4_zdrk

**Comment by dalley8626** [comment]
the expo sdk 49 with debugger looks amazing
