### ISSUE TITLE
volume sensor

### ISSUE THREAD

**Issue by AntonSmatanik** [expo/expo#2127]
I'm trying to create kind of Volume sensor with Expo, but I don't see any option how to get actual volume info. I'm now working with Expo.Audio, here is my code:

`const recording = new Expo.Audio.Recording();
try {
        await recording.prepareToRecordAsync(Expo.Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY);
        await recording.startAsync();
        recording.setProgressUpdateInterval(config.updateInterval);
        recording.setOnRecordingStatusUpdate(status => {
          console.log(status);
        });
      } catch (error) {
        console.log(error);
      }`

Status object has just few info. Is there any other option how to measure volume?

**Comment by sjchmiela** [comment]
Hey, @AntonSmatanik! I'm sorry to say there is currently no way to sens volume level with Expo. If you still care about this feature, please open a new feature request at https://expo.canny.io (it's the place  where we track important feature requests). If you happened to encounter a third-party library that would serve your purpose, including it in the feature request description will help us inspect and prioritize your request. 🙂
