### ISSUE TITLE
expo camera on unmount doesn't always return back to an awaited recordAsync call

### ISSUE THREAD

**Issue by johnslemmer** [expo/expo#21285]
### Minimal reproducible example

https://github.com/johnslemmer/expo-camera-bug

### Summary

I was having an issue with `expo-camera` where the `Camera` component would
unmount while recording a video and the `recordAsync` call would never return
meaning I could never handle the resulting video file (in my case I was
immediately trying to store the video to an S3 bucket).

This repo is the most minimal I could do to reproduce this issue. Though the
reproduction doesn't happen all the time. With this app loaded in Expo Go try
going to camera test page, pressing `Start Recording` and then pressing `Go Home`
while the camera is still recording. In some cases I never see the
`Recorded video at...` log message.

However, in my actual app I'm seeing this all the time.  This makes me think
this is some sort of timing issue.  I thought that maybe the JS engine was just
getting a little over eager with garbage collection, or something when a
component would unmount. However, the `sleep-test` route did not show similar
behavior.

Anyway, really not sure what is going on here.  Any help would be appreciated.

Couple other notes. I couldn't get this to happen without `expo-router` setup.
And a `_layout` also needed to be present. However, I don't think `expo-router`
is to blame.  I think it is just exasperating the timing issue that is deeper
within `Camera`.  Though that is a complete hunch, feel free to disregard.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.asdf/installs/nodejs/18.13.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.13.0/bin/yarn
      npm: 8.19.3 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.1 => 48.0.1 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    Expo Workflow: managed

**Comment by johnslemmer** [comment]
This is still an issue for me.  Do you need more info?  Can I be helpful in any way to get this looked at?

**Comment by aufabdulnafea** [comment]
this is an issue for me as well
