### ISSUE TITLE
[expo-blur] Adding blur support on Android 12+ through Android Native APIs

### ISSUE THREAD

**Issue by dmahajan980** [expo/expo#21289]
### Minimal reproducible example

https://snack.expo.dev/@dmahajan98/expo-blur-reproducible

### Summary

With the release of Android 12 in 2021, all Android 12+ apps can use Blur APIs for implementing window/view-blur effects ([docs page](https://source.android.com/docs/core/display/window-blurs)). This is identical to the blur effects that iOS has been supporting natively for so long.

Currently, `expo-blur` does not support blur for Android. However, this API can be used to enable blur support on Android 12+ apps. For apps running on lower Android versions, the current fallback strategy can be used (i.e., to render a semi-transparent view).

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.4.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.2.0 - /usr/local/bin/npm
      Watchman: 2022.12.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
        Android NDK: 25.1.8937393
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.1 => 48.0.1 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.71.2 => 0.71.2 
      react-native-web: ^0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed

**Comment by brentvatne** [comment]
this would be a nice feature to add! alas the issues here are reserved for bug reports. if you'd like to open a PR to add this, please do!
