### ISSUE TITLE
[SDK 48.0.1] iOS prebuild fails with react-native-maps (Google Maps)

### ISSUE THREAD

**Issue by pchmn** [expo/expo#21282]
### Minimal reproducible example

https://github.com/pchmn/test-expo-sdk-48

### Summary

When using expo sdk 48 with `react-native-maps` (with Google Maps) there is a bug at iOS prebuild.

If you set a Google Maps Api Key in `app.json` (`ios.config.googleMapsApiKey`) and run `npx expo prebuild` there is this error :

```
✖ Config sync failed
Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
    at /Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+config-plugins@6.0.0/node_modules/@expo/config-plugins/build/ios/Maps.js:218:19
    at action (/Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+config-plugins@6.0.0/node_modules/@expo/config-plugins/build/plugins/withMod.js:201:29)
    at interceptingMod (/Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+config-plugins@6.0.0/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:27)
    at action (/Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+config-plugins@6.0.0/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:61:27)
    at async interceptingMod (/Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+config-plugins@6.0.0/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async evalModsAsync (/Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+config-plugins@6.0.0/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:204:25)
    at async Object.compileModsAsync (/Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+config-plugins@6.0.0/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:124:10)
    at async configureProjectAsync (/Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+cli@0.6.1_6weo4dzsrefthwodkc5gdxxcii/node_modules/@expo/cli/build/src/prebuild/configureProjectAsync.js:54:15)
    at async prebuildAsync (/Users/paul/Dev/perso/test-expo-sdk-48/node_modules/.pnpm/@expo+cli@0.6.1_6weo4dzsrefthwodkc5gdxxcii/node_modules/@expo/cli/build/src/prebuild/prebuildAsync.js:83:9)
```

If you remove `ios.config.googleMapsApiKey` of `app.json`, prebuild is working fine.

The problem seems to come from [`MATCH_INIT`](https://github.com/expo/expo/blob/main/packages/%40expo/config-plugins/src/ios/Maps.ts#L13-L15) regex in Maps config plugin of [`@expo/config-plugins`](https://github.com/expo/expo/tree/main/packages/%40expo/config-plugins):
```ts
// Match against `UMModuleRegistryAdapter` (unimodules), and React Native without unimodules (Expo Modules), and SDK +44 React AppDelegate subscriber.
export const MATCH_INIT =
  /(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[\[RCTBridge alloc\])|(\[self\.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions\])/g;
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.1 => 48.0.1 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.2 => 0.71.2 
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.0.8
    Expo Workflow: bare

**Comment by mariomurrent-softwaresolutions** [comment]
Same here - still persists with latest expo 48 SDK

**Comment by pchmn** [comment]
After some digging, I found out that the problem comes from [`MATCH_INIT`](https://github.com/expo/expo/blob/main/packages/%40expo/config-plugins/src/ios/Maps.ts#L13-L15) regex in Maps config plugin of `@expo/config-plugins`:
```ts
// Match against `UMModuleRegistryAdapter` (unimodules), and React Native without unimodules (Expo Modules), and SDK +44 React AppDelegate subscriber.
export const MATCH_INIT =
  /(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[\[RCTBridge alloc\])|(\[self\.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions\])/g;
```

I made this changes to make it work :
```diff
 // Match against `UMModuleRegistryAdapter` (unimodules), and React Native without unimodules (Expo Modules), and SDK +44 React AppDelegate subscriber.
-const MATCH_INIT = /(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[\[RCTBridge alloc\])|(\[self\.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions\])/g;
+const MATCH_INIT = /-\s*\(BOOL\)\s*application:\s*\(UIApplication\s*\*\s*\)\s*\w+\s+didFinishLaunchingWithOptions:/g;

...
export function addGoogleMapsAppDelegateInit(src: string, apiKey: string): MergeResults {
  ...
  return mergeContents({
    tag: 'react-native-maps-init',
    src,
    newSrc: newSrc.join('\n'),
    anchor: MATCH_INIT,
-    offset: 0,
+    offset: 2,
    comment: '//',
  });
}
```

I created a [patch](https://github.com/pchmn/kavout/pull/25/commits/1754c6c91e37d22e562fd96621c2c1bc4fcd0305) in my repo in the meantime. You can check and see if it works for you @mariomurrent-softwaresolutions !

**Comment by mariomurrent-softwaresolutions** [comment]
I will try it out thx

**Comment by mariomurrent-softwaresolutions** [comment]
@pchmn and then the expo prebuild command did succeed?

**Comment by efrain-salas** [comment]
@EvanBacon Could someone integrate this into the main branch please? I can't make builds for iOS because of this bug, and I don't know how to apply the patch.
Thanks!

**Comment by pchmn** [comment]
> @pchmn and then the expo prebuild command did succeed?

Yes locally the `expo prebuild` works, and my EAS build works as well

**Comment by mariomurrent-softwaresolutions** [comment]
That's strange, which react-native-maps version are you using? Are you using it in combination with firebase? And no custom config-plugin for maps?

**Comment by pchmn** [comment]
I'm using `1.3.2` version of `rect-native-maps`. And yes I'm using `@react-native-firebase` as well. I had to turn on `use_frameworks` with `expo-build-properties` in my [config](https://github.com/pchmn/kavout/blob/feature/24-upgrade-expo-sdk/apps/mobile/app.config.ts#L74-L77) as explained [here](https://rnfirebase.io/#managed-workflow).

With this property `react-native-maps` doesn't work, so I added this custom [config-plugin](https://github.com/pchmn/kavout/blob/feature/24-upgrade-expo-sdk/apps/mobile/reactNativeMapsPlugin.js) to fix iOS build.

But `expo prebuild` works without this custom config plugin, it's only used when building the iOS app

**Comment by mariomurrent-softwaresolutions** [comment]
> I'm using `1.3.2` version of `rect-native-maps`. And yes I'm using `@react-native-firebase` as well. I had to turn on `use_frameworks` with `expo-build-properties` in my [config](https://github.com/pchmn/kavout/blob/feature/24-upgrade-expo-sdk/apps/mobile/app.config.ts#L74-L77) as explained [here](https://rnfirebase.io/#managed-workflow).
> 
> 
> 
> With this property `react-native-maps` doesn't work, so I added this custom [config-plugin](https://github.com/pchmn/kavout/blob/feature/24-upgrade-expo-sdk/apps/mobile/reactNativeMapsPlugin.js) to fix iOS build.
> 
> 
> 
> But `expo prebuild` works without this custom config plugin, it's only used when building the iOS app (`expo run:ios`)

Interesting...same configuration but something is still wrong. I need to check. Thx for the description 😊

**Comment by mariomurrent-softwaresolutions** [comment]
@pchmn Found the issues: It was some expo-cli issue conflicting with some old versions. With your changes it's now working. Thx

**Comment by pchmn** [comment]
@mariomurrent-softwaresolutions perfect ! `@expo/config-plugins@6.0.1` contains the fix, so you can use this version without the patch now

**Comment by efrain-salas** [comment]
Thanks to everyone who helped to fix this bug. I was able to compile for iOS just by running `npm update`.

**Comment by ChromeQ** [comment]
Installing the latest @expo/config-plugins isn't enough for me, still seeing the problem. I notice there are a few different versions installed depending on what packages I use.

```
$ npm ls @expo/config-plugins
├── @expo/config-plugins@6.0.1
├─┬ expo-cli@6.3.2
│ ├── @expo/config-plugins@4.1.5
│ ├─┬ @expo/config@6.0.24
│ │ └── @expo/config-plugins@4.1.5 deduped
│ ├─┬ @expo/dev-server@0.2.0
│ │ └─┬ @expo/metro-config@0.6.0
│ │   └─┬ @expo/config@8.0.2
│ │     └── @expo/config-plugins@6.0.1
│ ├─┬ @expo/prebuild-config@4.0.3
│ │ └── @expo/config-plugins@4.1.5 deduped
│ └─┬ xdl@60.0.4
│   ├── @expo/config-plugins@4.1.5
│   ├─┬ @expo/config@6.0.24
│   │ └── @expo/config-plugins@4.1.5 deduped
│   ├─┬ @expo/dev-server@0.2.0
│   │ └─┬ @expo/metro-config@0.6.0
│   │   └─┬ @expo/config@8.0.2
│   │     └── @expo/config-plugins@6.0.1
│   └─┬ @expo/webpack-config@18.0.1
│     └─┬ @expo/config@6.0.20
│       └── @expo/config-plugins@4.1.1
├─┬ expo-splash-screen@0.18.1
│ └─┬ @expo/prebuild-config@6.0.0
│   └── @expo/config-plugins@6.0.1 deduped
└─┬ expo@48.0.4
  ├─┬ @expo/cli@0.6.2
  │ └── @expo/config-plugins@6.0.1 deduped
  ├── @expo/config-plugins@6.0.1 deduped
  └─┬ @expo/config@8.0.2
    └── @expo/config-plugins@6.0.1 deduped
```

And everything at my top level package.json is the latest versions, but expo-cli is installing and using `@expo/config-plugins@4.1.5`. How can I get this to work to prebuild with expo v48?

**Comment by mariomurrent-softwaresolutions** [comment]
@ChromeQ For me removing the expo-cli from the package.json fixed it

**Comment by efrain-salas** [comment]
`expo doctor` could help too.

**Comment by ChromeQ** [comment]
> @ChromeQ For me removing the expo-cli from the package.json fixed it

Unfortunately that didn't work either @mariomurrent-softwaresolutions, running `npx expo-cli prebuild --clean` after removing expo-cli from package.json still just installs it in a temp folder so it can use it, leading to the same error:
```
✖ Config sync failed
Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed.
```

**Comment by ChromeQ** [comment]
After running `yarn upgrade` this updated all deps and now it works. Thanks

**Comment by knilf-i-am** [comment]
I just upgraded to Expo 48 and AFAICT 6.0.1 in the going version for @expo/config-plugins. However, I'm still running into this error because my global expo-cli (which is the latest version) depends on an old version of @expo/config-plugins (4.1.5). As a result, expo prebuild fails. Any tips on how to bump the dependency in the global package?

`[ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
Error: [ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
    at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Maps.ts:199:19`

**Comment by mariomurrent-softwaresolutions** [comment]
@knilf-i-am did you try yarn upgrade before and then running the npx expo prebuild command?

**Comment by knilf-i-am** [comment]
So weirdly, this works fine with npx expo prebuild, but fails with expo prebuild. Oh well, build is running. Thanks!

**Comment by mariomurrent-softwaresolutions** [comment]
Yeah I had the same issues. I guess npx tries to take the correct or latest version :)

**Comment by pchmn** [comment]
Yes `expo ...` will use your global expo package and `npx expo ...` will use the local expo package installed in your project

**Comment by guillaumegaluz** [comment]
I'm running into the same issue on prebuild, I followed what worked for others here but still stuck on the `@expo/config-plugins` version... `npx expo-doctor` shows that expo is using `config-plugins@5.0.4` but im using the latest version of expo (expo@49.0.21) so not sure how to fix this

```
npx expo-doctor
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package expo-modules-autolinking@~1.5.0
Found invalid:
  expo-modules-autolinking@0.5.5
  (for more info, run: npm why expo-modules-autolinking)
Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~6.2.4
Found invalid:
  @expo/prebuild-config@3.0.16
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions.

One or more checks failed, indicating possible issues with the project.
```

----------------------

```
npm why @expo/config-plugins
@expo/config-plugins@7.2.5
node_modules/@expo/config-plugins
  @expo/config-plugins@"~7.2.2" from the root project

@expo/config-plugins@5.0.4
node_modules/expo/node_modules/@expo/config-plugins

@expo/config-plugins@5.0.4
node_modules/expo-updates/node_modules/@expo/config-plugins

@expo/config-plugins@5.0.4
node_modules/@expo/config/node_modules/@expo/config-plugins

@expo/config-plugins@5.0.4
node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins

@expo/config-plugins@5.0.4
node_modules/@expo/cli/node_modules/@expo/config-plugins

@expo/config-plugins@5.0.4
node_modules/eas-cli/node_modules/@expo/config-plugins
```

-----------------------------------

```
npm list | grep expo
├── @expo-google-fonts/poppins@0.2.3
├── @expo/config-plugins@7.2.5
├── @expo/prebuild-config@6.2.6
├── @expo/react-native-action-sheet@3.14.0
├── @expo/vector-icons@13.0.0
├── expo-application@5.3.1
├── expo-asset@8.10.1
├── expo-av@13.4.1
├── expo-blur@12.4.1
├── expo-calendar@11.3.2
├── expo-constants@14.4.2
├── expo-dev-client@2.4.12
├── expo-device@5.4.0
├── expo-font@11.4.0
├── expo-linear-gradient@12.3.0
├── expo-linking@5.0.2
├── expo-location@16.1.0
├── expo-permissions@14.2.1
├── expo-splash-screen@0.20.5
├── expo-status-bar@1.6.0
├── expo-updates@0.18.18
├── expo-web-browser@12.3.2
├── expo@49.0.21
├── jest-expo@49.0.0
├── sentry-expo@7.1.1
```
