### ISSUE TITLE
Expo-av Video component will scale video 2x on android emulator API v33 on M1 macbooks

### ISSUE THREAD

**Issue by joeyhotz** [expo/expo#21299]
### Minimal reproducible example

https://github.com/joeyhotz/expo-av-video-size-bug

### Summary

Facing a bug on my M1 apple laptop. I'm using an API 33 android emulator to play a video using expo-av, but when you reach a certain point in the video, the video will (it looks like) scale by 2x, so only a quarter of the video shows in the video frame. You'll see in the attached video that the video title appears fine in the beginning, but seeking forward changes the video frame size. I skip back to the beginning title for comparison.

I've attached a repo just with an app that uses the expo-av Video component. It is showing an HLS stream. If you seek more than halfway, it should trigger the bug (as shown in the screenshot and video). If it doesn't, continue changing the video time by seeking with the seekbar until it occurs.

I've been able to narrow down that this issue is specific to the android API v33 emulator, and it only seems to occur on apple chip (m1+) macbooks.

Would appreciate your help. We've been unable to debug any further, or reproduce this on any physical devices. It would be good to know for sure that this won't happen on non-emulators, thanks! 🙏 

[expo-av-video-size-bug.webm](https://user-images.githubusercontent.com/20849629/219994049-b4bb2742-b925-453d-8ae7-6d9a6aa36e40.webm)

![image](https://user-images.githubusercontent.com/20849629/219993538-fa82865d-a0b7-4325-af62-c8b31834415e.png)

### Environment

expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 13.2
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  npmPackages:
    expo: ~47.0.12 => 47.0.13
    react: 18.1.0 => 18.1.0
    react-dom: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-web: ~0.18.9 => 0.18.10
  Expo Workflow: bare

**Comment by brentvatne** [comment]
hi there! this sounds like it may be an issue with the emulator itself? i'm not sure if there is anything on the expo-av side that needs to be changed.

**Comment by thenicekat** [comment]
Was there a fix for this?

**Comment by tj-mc** [comment]
Can you please help me understand the fix? I'm facing this issue too

**Comment by tj-mc** [comment]
I experimented with different rendering modes in the Android emulator settings, but all seemed to do the same thing. When I tested on hardware, it worked as expected.
