### ISSUE TITLE
Exp publish not working

### ISSUE THREAD

**Issue by ianOXO** [expo/expo#2129]
When I run:
exp publish

It returns this:
bash: /c/Users/nian0/AppData/Roaming/npm/exp: No such file or directory

I've tried uninstalling and reinstalling exp and expo but it doesn't appear to fix anything.  I can confirm that this folder does not appear to exist on my computer but I'm not sure what steps I need to take to create it.  This issue started after I ran:

npm install -g exp

Which returned:
npm ERR! path C:\Users\nian0\AppData\Roaming\npm\node_modules\exp\node_modules\.xdl.DELETE\binaries\windows\adb\adb.exe
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\nian0\AppData\Roaming\npm\node_modules\exp\node_modules\.xdl.DELETE\binaries\windows\adb\adb.exe'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\nian0\AppData\Roaming\npm\node_modules\exp\node_modules\.xdl.DELETE\binaries\windows\adb\adb.exe'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\nian0\AppData\Roaming\npm\node_modules\exp\node_modules\.xdl.DELETE\binaries\windows\adb\adb.exe'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\Users\\nian0\\AppData\\Roaming\\npm\\node_modules\\exp\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\adb.exe' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\nian0\\AppData\\Roaming\\npm\\node_modules\\exp\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\adb.exe\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\nian0\\AppData\\Roaming\\npm\\node_modules\\exp\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\adb.exe',
npm ERR!   parent: 'exp' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nian0\AppData\Roaming\npm-cache\_logs\2018-08-20T20_28_56_145Z-debug.log

Any help would be greatly appreciated!

**Comment by tree-wizard** [comment]
This issue was the top Google search result for me, so for others coming after, here's the solution:

In [Github Issue # 153 for Angular](https://github.com/angular/webdriver-manager/issues/153), @initiafy-kelvin says "I am able to resolve the problem without rebooting by running Task Manager and ending the adb.exe process." Evidently, adb.exe is the Android Debug Bridge.

I ended the adb.exe process in Task Manager (Win7) and ran `npm i -g expo-cli` with no more problems.

All the best,
tree-wizard
