### ISSUE TITLE
App can't get loaded over the network on a VPN

### ISSUE THREAD

**Issue by jyting** [expo/expo#213]
Hi,

The loading of a package using `npm start` between the dev machine/physical mobile device times out if either (or both simultaneously) is on a VPN. I'm not sure if there's an intrinsic limitation here, or if it's simply not currently supported.

If it helps, I'm Arch Linux and Android. Will provide more info on request. Thanks!

**Comment by terribleben** [comment]
It depends on the VPN configuration. The mobile and the computer need to know how to connect to each other. In many circumstances that would mean that using LAN wouldn't work here. Using the `tunnel` configuration in XDE might work, though could still time out if the VPN is adding a lot of time to each round trip.

Is that a helpful answer?

**Comment by jyting** [comment]
Thanks @terribleben. That prompted me to check if I could have a VPN active through openvpn (on linux) while still allowing them to communicate with each other. I came across a few related resources and will see if they work over the next couple days and report back.

I realise it's not necessarily related to this repo itself - feel free to close if you feel it's too unrelated.

**Comment by dikaiosune** [comment]
ngrok tunnels (the tunnel option in XDE) should hopefully resolve most issues with using a VPN, but if you have a specific situation where it's not working, please post back and we can look into it. Thanks!

**Comment by triplea24** [comment]
I've gone through 4 different solutions for this problem as I enunciate them here. 

https://medium.com/@triplea1373/react-native-and-nat-problem-4b53462cd0b9
