### ISSUE TITLE
await Permissions.askAsync(Permissions.NOTIFICATIONS) hangs on SDK 29

### ISSUE THREAD

**Issue by mattfca** [expo/expo#2130]
When asking for Permissions.NOTIFICATIONS there is no response since upgrading from sdk 28 to sdk 29.

Forum post: https://forums.expo.io/t/expo-29-0-on-ios-is-no-longer-resolving-permissions-askasync-promise-for-notifications/12044/10
  
### Environment

iOS Standalone app SDK 29

### Steps to Reproduce

while using 
`const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);`
there is no response

### Expected Behavior

Should response with notification permission status

### Actual Behavior

There is no response, or error if wrapped in a try catch

### Reproducible Demo

This only happens on standalone apps as it is for notifications.

**Comment by mattfca** [comment]
After further testing, it works when you call it again. So something is causing the issue on first call

**Comment by mattmallon** [comment]
Running into the exact same issue in the exact same circumstances...incredibly frustrating, as it works perfectly everywhere EXCEPT for in a standalone iOS app.

**Comment by idrakimuhamad** [comment]
I can second this too on SDK 29. askAsync did not returning any response. But calling getAsync on the next run shows that the permission was granted.

**Comment by idrakimuhamad** [comment]
Can confirm that its working with SDK 28, using the latest client app. FWIW, I'm only having this issue in iOS, through the Expo Client.

**Comment by bronydell** [comment]
Same. It was working in SDK 28, but with version 29 it doesn't work :(

I have this issue in expo client

**Comment by sjchmiela** [comment]
Hi all! Sorry for the inconvenience, the fix has just landed on `master` (https://github.com/expo/expo/commit/ca900e6dc42d0648883c295601e1cff810d8158c), we hope to deploy the fix to Turtle builders later today.

**Comment by mattfca** [comment]
thanks @sjchmiela !
should we build from master or will there be a release soon?

**Comment by machester4** [comment]
Will this solution arrive as a patch or in a new version of SDK?

**Comment by sjchmiela** [comment]
The fix has just landed in Turtle builders thanks to @dsokal (https://github.com/expo/expo/issues/663#issuecomment-416148660) and I've just released v2.7.5 of Expo Client to the App Store containing these fixes in SDK 29 (it may take a second or two until it propagates everywhere and is available to update).

**Comment by machester4** [comment]
Hi bro, my application is separate and needs updating by pod. You can add it to [releases](https://github.com/expo/expo/releases). great job guys

**Comment by sjchmiela** [comment]
Done, @machester4! 🙂

**Comment by machester4** [comment]
Hi! @sjchmiela  Can you reopen the problem?

**Comment by sjchmiela** [comment]
What is the problem? 🙂

**Comment by machester4** [comment]
in version `2.7.6` it was not solved and not tested version `2.7.8` is solved there?
