### ISSUE TITLE
Expo camera with style width and height stops android expo app.

### ISSUE THREAD

**Issue by rockmandash** [expo/expo#2131]
These lines simply kill android expo app.
```javascript
<Camera
  style={{ width: '100px', height: '100px' }}
  type={this.state.type}
>
```

**Comment by sjchmiela** [comment]
Hi @rockmandash!

Could you please create a Snack reproducing the behavior you're encountering?

**Comment by rockmandash** [comment]
@sjchmiela Thank you for your reply.
Unfortunately, my app has no other usage, just this one camera, and if I put width & height, it exactly crushes expo app.
I'm just using `npx create-react-native-app` couple hours ago, my phone is android.
There is no other things in my code.

**Comment by sjchmiela** [comment]
Yup, I understand, but it will be much easier for me to help you if you try to reproduce this issue on Snack. 🙂

I was able to reproduce your issue — you can't use `px`s as units of measure in React Native. Check out https://facebook.github.io/react-native/docs/height-and-width.

> The simplest way to set the dimensions of a component is by adding a fixed width and height to style. All dimensions in React Native are unitless, and represent density-independent pixels.

If you change `width: '100px'` to `width: 100` (the same for `height`) it should resolve the issue.

Another thing you may encounter is lack of Camera permissions required to display any content in the Camera view. You'll need to use [`Permissions` API](https://docs.expo.io/versions/v29.0.0/sdk/permissions) to ensure you have Camera permissions. If you encounter any more problems with the Camera, pass a callback as [`onMountError` prop](https://docs.expo.io/versions/v29.0.0/sdk/camera#onmounterror-function).

Good luck!

**Comment by rockmandash** [comment]
@sjchmiela Thank you so much and your patience!
