### ISSUE TITLE
Chinese app stores rejecting Expo apps because expo.constants pulls ANDROID_ID at initialization, even if not required yet

### ISSUE THREAD

**Issue by humandevs** [expo/expo#21312]
### Minimal reproducible example

(create-expo-app & include expo-constants, then read Constants.platform.OS)

### Summary

We're trying to submit our app to the various device app stores in China, and the new Chinese privacy laws require the app itself to avoid requesting permissions until the in-app privacy policy is accepted. These permissions include the ANDROID_ID (installationID) which is provided by expo-constants.

We use expo-constants at initial app load to detect whether the device is iOS/Android, and what the release channel is. It appears that by simply creating an instance of expo-constants and reading this data, the ANDROID_ID is also read. We need some way to tell expo-constants to not read the ANDROID_ID until requested.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.2
      expo: ^46.0.0 => 46.0.17
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.10
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

**Comment by appsgenie** [comment]
did you get this resolved?
