### ISSUE TITLE
[expo-image][ios] Image source URI with encoded `#` gets cut off

### ISSUE THREAD

**Issue by KiwiKilian** [expo/expo#21321]
### Minimal reproducible example

https://github.com/trafficon/expo-image-search-params-bug

### Summary

If a `expo-image` `source.uri` contains an encoded `#` (which is `%23`) everything afterwards in that URI is getting cut off on iOS. This is how the `Image` component is beeing used:

```tsx
<Image
  source={{
    uri: 'http://localhost:3000?platform=' + Platform.OS + '&color=%230000ff&otherParam=willBeCutOff',
    width: 32,
    height: 32,
  }}
/>
```

This requests a SVG from this express server:
```js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
    console.log("Requested URL:", req.originalUrl);

    const color = req.query.color;
    res.send(`<svg viewbox="0 0 32 32"><rect width="32" height="32" fill="${color}" /></svg>`)
})

app.listen(port, () => {
    console.log(`Server running on http://localhost:${port}`)
});
```
Which returns a colored SVG based on the `color` search param. This works on Anroid, but no on iOS:

| Android | iOS |
| ---- | --- |
| ![Screenshot_20230221_115854_expo-image-search-params-bug](https://user-images.githubusercontent.com/18724559/220341598-dbc656aa-88ed-4df9-bd87-4e6501cd1246.jpg) |  ![Simulator Screen Shot - iPhone 14 Pro - 2023-02-21 at 11 58 36](https://user-images.githubusercontent.com/18724559/220341602-925bc17e-464d-46c5-bccc-67f4fc38e186.png) |

Both platforms should show a blue rectangle. The rectangle is black on iOS because the actually requested URI through `expo-image` on iOS is as follows from the express server log:

```
Android:
Requested URL: /?platform=android&color=%230000ff&otherParam=willBeCutOff

iOS:
Requested URL: /?platform=ios&color=
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.1/bin/npm
      Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: 48.0.1 => 48.0.1 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: 0.18.12 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.6.0
      expo-cli: 6.3.1
    Expo Workflow: managed
```

**Comment by tsapeta** [comment]
Hi @KiwiKilian, actually this was an issue in `expo-modules-core` package and how it handles URLs 😅
I've just released `expo@48.0.2` that has this fix included 🙂 

By the way – there is a `tintColor` prop that can color the image based on the alpha channel which might be exactly what you're trying to do. I'm not sure if iOS handles tinting well for all SVGs though. In the next minor version we'll switch to another, more spec-compliant implementation for SVGs and then I believe this will work as expected 😉

**Comment by KiwiKilian** [comment]
Thanks for the real quick fix!

The actual usecase is a map background with some geometries above – `tintColor` won't do the trick. But thanks for thinking forward! Can I read up something about the new SVG implementation?

**Comment by tsapeta** [comment]
I'm planning to try using https://github.com/adobe/svg-native-viewer and see what is better and worse than how iOS renders it. iOS doesn't officially support rendering SVGs, the API that SDWebImage uses for them is a private/undocumented API that Apple uses for SF Symbols. On the other side, `svg-native-viewer` doesn't support many things that work in the browsers, for example it doesn't support `style` attribute. Perhaps we'll let the user choose which implementation to use.
Our long-term goal is to migrate `@expo/vector-icons` to SVGs rendered with `expo-image` for many reasons but mostly to reduce the final bundle size.
