### ISSUE TITLE
MediaLibrary.getAssetsAsync() with sortBy crashes on Android, Expo SDK 48

### ISSUE THREAD

**Issue by yotam-frid** [expo/expo#21338]
### Minimal reproducible example

MediaLibrary.getAssetsAsync(anything)

### Summary

Hello,
I tried using expo-media-library in Expo SDK version 47, but the permissions kept failing because [expo-media-library was not using the granular permissions required by Android API 33](https://github.com/expo/expo/issues/20496).

I ended up upgrading to expo@next (SDK version 48) but now any calls to `getAssetsAsync` with the `sortBy` option throw an error.

The function all:

```
   return MediaLibrary.getAssetsAsync({
              album,
              first: 1,
              sortBy: [["creationTime", false]],
            })
```

```
Possible Unhandled Promise Rejection (id: 0):
Error: Call to function 'ExpoMediaLibrary.getAssetsAsync' has been rejected.
→ Caused by: The 1st argument cannot be cast to type expo.modules.medialibrary.AssetsOptions (received String)
→ Caused by: Cannot cast 'Array' for field 'sortBy' ('kotlin.collections.List<kotlin.String>').
→ Caused by: Cannot cast 'Array' to 'kotlin.String' required by the collection of type: 'kotlin.collections.List<kotlin.String>'.
→ Caused by: java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String
```

The function works correctly when _not_ passing an array to `sortBy`.

Reproduction steps:
1. Create an expo app and install `expo-media-library`
2. Ask for permissions
3. Try to call `MediaLibrary.getAssetsAsync()` while passing an array of SortByKeys and booleans to `sortBy`

Note: I am using a development client.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.3 => 48.0.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.2 => 0.71.2
      react-native-web: ~0.18.9 => 0.18.10
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 5.4.4
    Expo Workflow: bare

**Comment by fobos531** [comment]
A minimal reproduction repo would be helpful in this case and would increase the likelihood of your issue being accepted.

**Comment by yotam-frid** [comment]
> A minimal reproduction repo would be helpful in this case and would increase the likelihood of your issue being accepted.

You are right, I will work on creating a reproducible example once I get the opportunity.
However, just from reading the stack trace, it seems the error is from passing anything but a string to the `sortBy` option, which is supported on iOS but not on Android.

**Comment by brentvatne** [comment]
cc @alanjhughes

**Comment by alanjhughes** [comment]
You can assign this to me @brentvatne I'm working on it. Should have a fix in the morning

**Comment by yotam-frid** [comment]
LEGENDS! Thanks for addressing this so quickly!

**Comment by VityaSchel** [comment]
Still having this issue in expo 50
