### ISSUE TITLE
Settings.set fails

### ISSUE THREAD

**Issue by dimovdaniel** [expo/expo#2133]
### Steps to Reproduce

1. Import Settigs from react-native
2. Try to set a object

### Expected Behavior

To set a setting in NSUserDefaults

### Actual Behavior

Fails with Object assign target can't be null

### Reproducible Demo

[https://snack.expo.io/SycQ1ki8X](https://snack.expo.io/SycQ1ki8X)

**Comment by Szymon20000** [comment]
Currently we don't support Settings feature due to safety reasons. However you can use [securestore](https://docs.expo.io/versions/v29.0.0/sdk/securestore).

**Comment by dimovdaniel** [comment]
@Szymon20000 The reason I used Settings is that I want to access (read) NSDefaults. 
I was not able via AsyncStorage. And I see that SecureStore uses Keychain. 

Do you know any way how to?

**Comment by Szymon20000** [comment]
There is no possibility to access NSUserDefault as long as your app is not detached. If you detach your app you will be able to modify a Podfile. As a result, you will be able to use Settings feature.

**Comment by sjchmiela** [comment]
Thank you, @Szymon20000, for explaining this! 🙂
