### ISSUE TITLE
Camera and QR code scanner broken in expo go 2.28.1 on android

### ISSUE THREAD

**Issue by forki** [expo/expo#21342]
### Summary

I just updated my expo go on android to 2.28.1.

Camera and QR code scanner are broken. I can't even use "Scan QR code" from the expo go main menu.
Also all cam features inside my custom app don't work inside expo go 2.28.1.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

Expo Go 2.28.1
SDK 48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: 48.0.3 => 48.0.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.12 => 0.18.12
    Expo Workflow: managed

### Reproducible demo

![image](https://user-images.githubusercontent.com/57396/220608767-8f7652e5-ef10-47b1-a0a0-cbe5580ee528.png)

**Comment by forki** [comment]
@expo-bot insta close is not very helpful

**Comment by jeltehomminga** [comment]
same issue here, cannot use camera to scan qr code, screen stays black

**Comment by forki** [comment]
@kudo @EvanBacon can you please reopen this. the repro is easy: just install expo go 2.28.1 and try to scan a QR code.

**Comment by tforkmann** [comment]
Having the same issue. Camera just doesnt start.

**Comment by DS204ever** [comment]
Same issue here, black screen on QR code and crash if I try to insert the url.

**Comment by TheSavageDev** [comment]
Same here. No camera. Crash if trying to open the server after login. Works on version 2.26.3 in simulator. Broken in 2.28.1 on device.

**Comment by brentvatne** [comment]
it looks like there was a regression in Expo Go in our release for the upcoming SDK 48, which was not caught during our beta testing period. we're investigating this now.

**Comment by stban94diaz** [comment]
https://user-images.githubusercontent.com/20797115/220734732-cac8d3ed-d906-4d82-84ba-bf2488e691a8.mp4

**Comment by gregfenton** [comment]
> @expo-bot insta close is not very helpful

The bot simply asked for repro steps.  The original post simply shows a screenshot.  30 seconds of typing the steps that led to that screenshot would go a long way to making sure whoever starts delving into this issue is actually looking at the correct issue.

**Comment by brentvatne** [comment]
while we work on a workaround, remember that you can:
- sign in through expo go and also in expo cli `npx expo login` and then your project will show up automatically in expo go when you run `npx expo start` in the project
- connect your device over usb, run `npx expo start`, then press `a` to launch into it

**Comment by TheSavageDev** [comment]
`sign in through expo go and also in expo cli npx expo login and then your project will show up automatically in expo go when you run npx expo start in the project`

Expo Go crashes when you do this.

**Comment by brentvatne** [comment]
@TheSavageDev - on a blank new sdk 48 project or which?

**Comment by brentvatne** [comment]
we've found a potential fix for the QR code scanner and URL issue, submitting a new build to Google Play now.

**Comment by gregdburns** [comment]
Re: the workaround, for me it crashes using Expo Go, however it works when I load the app build with EAS using the development client and when I open that app directly.

cc: @TheSavageDev

**Comment by brentvatne** [comment]
@gregdburns - are you saying that the provided APK in https://github.com/expo/expo/issues/21342#issuecomment-1440707241 crashes for you?

**Comment by gregdburns** [comment]
Sorry @brentvatne , no - I was clarifying this workaround, when someone reported that it didn't work for them:

"sign in through expo go and also in expo cli npx expo login and then your project will show up automatically in expo go when you run npx expo start in the project"

The nuance being that this did not work when using the Expo Go app, but it _did_ work when using the build created with EAS (development client).  Apologies for the confusion.

**Comment by brentvatne** [comment]
@gregdburns - ah, got it! the new release should be live on the play store now. let me know if the issue persists with version 2.28.2

**Comment by forki** [comment]
Awesome. Can confirm: it works. Thanks for super fast fix.

Brent Vatne ***@***.***> schrieb am Do., 23. Feb. 2023, 00:10:

**Comment by gregdburns** [comment]
Confirmed on my end too.  When Expo Go upgraded, on first open, it hung on the splash screen.  I closed and reopened and it works great.  Thanks to you and the team @brentvatne!

**Comment by forki** [comment]
Actually yes I noticed that too. Seems there is an unrelated issue with
hang on first open. It also happened with 2.28.1

Greg ***@***.***> schrieb am Do., 23. Feb. 2023, 00:17:

**Comment by devalnor** [comment]
Issue still present with in Expo Go 2.28.2 on an Android 11

**Comment by Nkay2487** [comment]
HI, I am facing same issue on expo go - 2.30.9.
