### ISSUE TITLE
(Android) Notifications.addListener doesn't fire on second notification 

### ISSUE THREAD

**Issue by mikolajadamowicz** [expo/expo#2135]
### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.8.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/ming122-68193076-7894-4ce7-b47e-5eb4ce921464.tar.gz

Target: Android standalone 

### Steps to Reproduce

1.Kill app
2.Open app by clicking the notification
3.Select another notification || background app and select another notification

### Expected Behavior

Notifications.addListener should fire when second notification is being selected.

### Actual Behavior

Nothing happens. Notifications.addListener is not called. When app is backgrounded selecting notification opens app but that's it, listener is never called. 

### Reproducible Demo
git repo https://github.com/mikolajadamowicz/PushTest
Here's a video for better understanding: https://streamable.com/6dp2r

registerForPushNotificationsAsync() from https://docs.expo.io/versions/latest/guides/push-notifications#http2-api

```javascript
import React from 'react';
import { Notifications } from 'expo';
import { Text, View, Button } from 'react-native';

// This refers to the function defined earlier in this guide
import { registerForPushNotificationsAsync } from './config/ExpoPush';

export default class App extends React.Component {
  state = {
    notification: {},
    token: undefined,
  };

  cos = async () => {
    const token = await registerForPushNotificationsAsync();
    this.setState({ token });
  };
  componentDidMount() {
    this.cos();
    // Handle notifications that are received or selected while the app
    // is open. If the app was closed and then opened by tapping the
    // notification (rather than just tapping the app icon to open it),
    // this function will fire on the next tick after the app starts
    // with the notification data.
    this._notificationSubscription = Notifications.addListener(this._handleNotification);
  }

  _handleNotification = (notification) => {
    this.setState({ notification });
  };

  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Origin: {this.state.notification.origin}</Text>
        <Text>Data: {JSON.stringify(this.state.notification.data)}</Text>
        <Text>Token: {this.state.token}</Text>
        <Button
          title="Click me!"
          color="#841584"
          onPress={() => this.setState({ notification: {} })}
        />
      </View>
    );
  }
}
```

**Comment by outaTiME** [comment]
Hi @mikolajadamowicz,

I have the same problem in Android (iOS working as expected) running in **standalone** mode, when the app is closed (killed) and then is opened by clicking a notification the first time `Notifications.addListener` is fired but for subsequent notifications the listener is never called.

But if the application is closed (killed), and then opened by clicking its icon, the notifications listener is called correctly in all cases.

**Comment by albertocolella** [comment]
Hi, what @outaTiME wrote is the exact mode to reproduce the bug.
Notifications selection works while you are developing on Expo, but as soon as you build an apk it stops working. Push notifications selection doesn't work when the app is opened (doesn't matter if the app si in foreground or background), it only works when the app is closed.

**Comment by mikolajadamowicz** [comment]
Yup, that's exactly what's happening. I think we have real problem here.

**Comment by Triggybet** [comment]
**(Update: I updated to SDK 30, just in case, and did a fresh APK build. Now the issue seems to be gone on my Samsung S9. Don't know if Expo's build process has been updated with a fix or if the SDK update did anything. But on our end it seems to work. Will continue testing on my other devices too.)**

**Comment by veedeo** [comment]
Updated to SDK 30 and still having this issue

**Comment by cyp3rius** [comment]
Same here. It doesn't work both on Android & iOS standalone apps (IPA/APK). 
First notification (only if app is closed) appears and is properly handled by `addListener` and thats all. Not depends how many other notifications were sent during app is opened in foreground, none of them trigger listener function.

**Comment by rthernes** [comment]
I'm having this issue in SDK 31 under standalone iOS

**Comment by vinaynb** [comment]
My listener doesn't get called at all even for the first notification on SDK 32 standalone android build.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!

**Comment by daniyal6757** [comment]
when m using react redux its giving me error (connot read property 'apply ' of undefined
