### ISSUE TITLE
expo-image-picker Android [Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'result.assets[0]')]

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo#21354]
### Minimal reproducible example

https://snack.expo.dev/@mikechambers610/image-picker-snack?platform=ios

### Summary

Hi Expo team- thanks for looking into this issue.

To reproduce the issue, please create a new project (SDK 47) and use the following code below (provided by expo docs) using the expo-image-picker package. Any version of the package after the assets array was implemented to get the issue.

This is only happening on Android.

Error:
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'result.assets[0]')]

Code:

import * as ImagePicker from 'expo-image-picker'

 let result = await ImagePicker.launchImageLibraryAsync({
          mediaTypes: ImagePicker.MediaTypeOptions.All, 
          aspect: [4, 3],
          quality: 1,
      });
 
      console.log(result)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/exponavs/newapp1/node_modules/.bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.84 => 0.1.84 
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^47.0.13 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.6.0
      expo-cli: 6.3.1
    Expo Workflow: managed

**Comment by brentvatne** [comment]
`result.assets` will be undefined if `result.canceled` is true.

that is why there is a check for that on the docs page: https://docs.expo.dev/versions/latest/sdk/imagepicker/

![image](https://user-images.githubusercontent.com/90494/220821636-638f4ac0-8d21-4cc2-bc6b-4f7676467585.png)

running the snack from the docs works as expected.

**Comment by mikeRChambers610** [comment]
@brentvatne Hi Brent thanks for the quick response.

In the snack I shared you can see that there is no result at all logged in the console. 

The result = {}.

I am confused where you see cancelled as true? The image was selected and returned {}.

**Comment by mikeRChambers610** [comment]
@brentvatne Hi Brent thank you for the quick response.

I do see that you are correct and that I can check the cancelled is true.

But this happens when a user is clicking a photo in one of the android folders. 

Images > downloads or Images > camera selecting an image from one of these android folders results in a cancellation = true. Is this the expected behavior?

**Comment by mikeRChambers610** [comment]
https://user-images.githubusercontent.com/24532186/220831394-29496489-f8ad-4ff2-af57-f1e4940dc77a.mov

**Comment by Tchaikovsky1114** [comment]
> `result.assets` will be undefined if `result.canceled` is true.

```
if (!result.canceled)
```

**Comment by Tchaikovsky1114** [comment]
@brentvatne

sir i solved same issue
please check your Expo Go version.

My standalone app works fine, but it seems to only work in Expo go, so I checked and it was an update problem.

**Comment by mikeRChambers610** [comment]
@Tchaikovsky1114  thanks that worked. I could have sworn it was already updated for SDK 47 but indeed there was an update available and  once updated the issue is resolved.
