### ISSUE TITLE
ImagePicker.launchImageLibraryAsync wrong output

### ISSUE THREAD

**Issue by Bilboramix** [expo/expo#21362]
### Minimal reproducible example

https://github.com/Bilboramix/RN_ImagePickerBug

```js
  let result = await ImagePicker.launchImageLibraryAsync({
    mediaTypes: ImagePicker.MediaTypeOptions.All,
    allowsEditing: true,
    aspect: [1, 1],
  });
  console.log(result);
```

### Summary

I expect an output like this

```js
{
  "assets": [
    {
      "assetId": "C166F9F5-B5FE-4501-9531",
      "base64": null,
      "duration": null,
      "exif": null,
      "fileName": "IMG.HEIC",
      "fileSize": 6018901,
      "height": 3025,
      "type": "image",
      "uri": "file:///data/user/0/host.exp.exponent/cache/cropped1814158652.jpg"
      "width": 3024
    }
  ],
  "canceled": false,
  "cancelled": false
}
```

But i'm getting this :

```
LOG :  result : {"cancelled": undefined}
WARN :  Key "cancelled" in the image picker result is deprecated and will be removed in SDK 48, use "canceled" instead
```

The code comes from the doc : https://docs.expo.dev/tutorial/image-picker/

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^47.0.0 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.12 
    Expo Workflow: managed
```

**Comment by e-hosseini** [comment]
Could you try to update your Expo Go app? It solved the issue for me.

**Comment by Bilboramix** [comment]
Omg thank you so much, i did not checked this as i've got automatic updates on...

**Comment by mariusgaciu** [comment]
The issue still persists for me, same setup as above. I'm on the latest Expo Go version, but the below error keeps pop-in up even though I'm not using either `canceled` or `cancelled`.

```
Key "cancelled" in the image picker result is deprecated and will be removed in SDK 48, use "canceled" instead
```

**Comment by Tieu-Mai-Nhi** [comment]
Did you find a solution?

**Comment by muriloalvesdev** [comment]
this issue still persist for me!

**Comment by LeoYab** [comment]
If you remove the console.log, the error disappears. I understand that it's because the entire object is being displayed and that's why the warning appears.

**Comment by gillmpadon** [comment]
> The issue still persists for me, same setup as above. I'm on the latest Expo Go version, but the below error keeps pop-in up even though I'm not using either `canceled` or `cancelled`.
> 
> ```
> Key "cancelled" in the image picker result is deprecated and will be removed in SDK 48, use "canceled" instead
> ```

I hate to do this but bruh, same error

**Comment by suprunchuk** [comment]
Да, я удалил console.log и это решило проблему

**Comment by milly-code** [comment]
I am having the same issue
```shell
Windows 10
expo: 49.0.16
expo-image-picker: 14.3.2
```

Here's my code where at no point I tried accessing `cancelled` or `canceled`
```ts
const pickImage = async (options: Partial<PickerOptions> | undefined = undefined): Promise<ImageAsset[] | undefined> => {
    const { mediaType, aspect, limit, allowsMultipleSelection } = _ensureValidKey(options);
    let _images: ImageAsset[] | undefined = undefined;
    const results = await launchImageLibraryAsync({
        mediaTypes: MediaTypeOptions[mediaType],
        exif: true,
        allowsEditing: !allowsMultipleSelection,
        aspect: aspect,
        quality: 1,
        allowsMultipleSelection: allowsMultipleSelection,
        selectionLimit: limit,
        base64: true,
    });
    if (results.assets && results.assets.length > 0) {
        _images = results.assets;
    }
    return _images;
}; 
```

I still get the warning ` WARN  Key "cancelled" in the image picker result is deprecated and will be removed in SDK 48, use "canceled" instead`. Which is very annoying. I tried to update `expo-image-picker` to the latest (14.5.0), however, when I start the app I get the following warning in the console 
```shell
Some dependencies are incompatible with the installed expo version:
  expo-image-picker@14.5.0 - expected version: ~14.3.2
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
```

**Comment by NazarIlkiv** [comment]
I delete console.log, and warning resolved
