### ISSUE TITLE
EAS build not prompting for 2FA with Apple ID

### ISSUE THREAD

**Issue by noahkurz** [expo/expo#21364]
### Summary

Hello, 

I am currently trying to build a preview version of my app and it appears that there may be a potential bug with the EAS build command in regard to authenticating with Apple's servers. I run the build command (same as I successfully have in the past) and am receiving the following message.

    "Authentication with Apple Developer Portal failed!
    Error: Apple Service Error -36607. Unable to sign you in to your Apple ID. Try again later." 

EAS is not prompting me for my 2FA code. When I run the following command:
      "EXPO_NO_KEYCHAIN=1 EXPO_APP_STORE_DEBUG=1 npx @expo/apple-utils login" 
I receive the same error. My account does not appear to be locked either. Any help on this issue would be greatly appreciated. 

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

expo version: 47.0.12
expo-dev-client: 2.0.1
expo-updates-interface: 0.8.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.4.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ^0.18.10 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.7.0
      expo-cli: 6.3.1
    Expo Workflow: bare

### Reproducible demo

Create a bare expo project

run eas build -p ios --profile preview

try to authenticate with your apple id that uses device 2FA

build fails then I receive 2FA prompt from apple afterwords

**Comment by tylercote** [comment]
I am seeing the same issue starting this morning, was not happening yesterday.

**Comment by fedelernerldp** [comment]
I'm having the exact same issue.
I first got my Apple Account blocked. I had to unlock it by inserting my phone number, and changing the password.

Now, I get the same issue reported by @noahkurz 

I was able to build without problems yesterday.

**Comment by brentvatne** [comment]
tracking this here: https://github.com/expo/eas-cli/issues/1714#issuecomment-1442147083

> this same issue is occurring on fastlane: https://github.com/fastlane/fastlane/pull/21072
> it looks like Apple changed an API without notice. we're going to update for this as soon as possible. for now, indeed, you can skip the authentication part
