### ISSUE TITLE
How to get the expo ipa file for version 2.2.0

### ISSUE THREAD

**Issue by lkspc** [expo/expo#2136]
Hey guys, I have built an app for my friend for personal offline use with Expo before, but he upgraded the Expo version accidentally and cannot access my app again. 

I know that Expo had remove the QR code Scanner, so how to get the old version of Expo to install as before?

**Comment by ide** [comment]
We only provide and support the latest IPAs and the Expo client is intended for development. Additionally, IPAs cannot be directly installed on a device unless they are either from the App Store or are signed with an enterprise developer certificate, so the old IPAs would not be of much use.

The best way to share an app with a friend is probably to build an enterprise IPA (this requires setting up an enterprise Apple developer account).
