### ISSUE TITLE
vulnerability in default dependency of create-expo-app

### ISSUE THREAD

**Issue by Bojun-Feng** [expo/expo#21374]
### Summary

When I was using the create-expo-app function to create a new app, the default starting build was dependent on a vulnerable Json5 dependency. Is there a way to change the settings such that the default dependencies do not involve a deprecated version of the Json5 package?

Here is the `npm audit` report right after creating a new app.
<img width="721" alt="Screen Shot 2023-02-23 at 10 08 01 PM" src="https://user-images.githubusercontent.com/102875484/221089533-f6ddac18-8219-4ec9-832e-6477e9cd8808.png">

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

### Minimal reproducible example

Run npx create-expo-app with following version settings:

{
  client: '1.0.0',
  npm: '9.5.1',
  node: '19.5.0',
  v8: '10.8.168.25-node.11',
  uv: '1.44.2',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '111',
  nghttp2: '1.51.0',
  napi: '8',
  llhttp: '8.1.0',
  uvwasi: '0.0.14',
  acorn: '8.8.1',
  simdutf: '3.1.0',
  undici: '5.14.0',
  openssl: '1.1.1s',
  cldr: '42.0',
  icu: '72.1',
  tz: '2022e',
  unicode: '15.0'
}

**Comment by zhiqingchen** [comment]
```
=> Found "find-babel-config#json5@0.5.1"
info This module exists because "babel-plugin-module-resolver#find-babel-config" depends on it.
info Disk size without dependencies: "68KB"
info Disk size with unique dependencies: "68KB"
info Disk size with transitive dependencies: "68KB"
info Number of shared dependencies: 0
```

maybe upgrade babel-plugin-module-resolver to `^5.0.0` from `^4.1.0`

**Comment by Bojun-Feng** [comment]
> ```
> => Found "find-babel-config#json5@0.5.1"
> info This module exists because "babel-plugin-module-resolver#find-babel-config" depends on it.
> info Disk size without dependencies: "68KB"
> info Disk size with unique dependencies: "68KB"
> info Disk size with transitive dependencies: "68KB"
> info Number of shared dependencies: 0
> ```
> 
> maybe upgrade babel-plugin-module-resolver to `^5.0.0` from `^4.1.0` https://github.com/tleunen/babel-plugin-module-resolver/blob/master/CHANGELOG.md#500-2023-01-09

Yes, that would be a great solution to the problem. I was just wondering how to change the default setting of the create-expo-app so the babel-plugin-module-resolver is ^5.0.0 from the start without the need for a manual update.

**Comment by PedroPerpetua** [comment]
To future readers, I monkeypatched the issue locally by overriding the dependency on expo itself.
```jsonc
// package.json
"//": "Override vulnerable dependency until expo updates it.",
"overrides": {
  "expo": {
    "babel-preset-expo": {
      "babel-plugin-module-resolver": "^5.0.0"
    }
  }
},
```

**Comment by PedroPerpetua** [comment]
> @PedroPerpetua thanks for sharing but it didn't do anything, still get the error.

You might need to fully reinstall everything - try deleting the `package-lock, the node_modules folder, and then do `npm i` and see if that works. The `overrides` property seems to have some issues when not being applied from the start.

If you're using `yarn`, the directive is different:
```
  "//": "Override vulnerable dependency until expo updates it.",
  "resolutions": {
    "expo/babel-preset-expo/babel-plugin-module-resolver": "5.0.0"
  },
```

**Comment by LorenDorez** [comment]
any update from expo on this issue? seems like there a fair bit of audit issues from a clean project
