### ISSUE TITLE
Expo Go dev menu does not support landscape

### ISSUE THREAD

**Issue by ridwansameer** [expo/expo#21380]
### Summary

I'm using Expo to develop a tablet application, and using landscape. Here is an image of the app open
![image](https://user-images.githubusercontent.com/122685783/221201858-5a445eb2-7199-45c1-a1e2-14b5021d052c.png)

If I try to open the dev menu with Cmd + M It will switch to portrait

![image](https://user-images.githubusercontent.com/122685783/221201901-b35be10e-2327-4b0e-b3f7-7fd3946b1566.png)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 12.5.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v19.3.0/bin/yarn
npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9514443
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
expo: ~47.0.12 => 47.0.13
react: 18.1.0 => 18.1.0
react-native: 0.70.5 => 0.70.5
Expo Workflow: managed

### Reproducible demo

https://github.com/ridwansameer/expo-go-bug

Simply run yarn install and then npx expo start and open on android emulator or real device

This can be recreated in a brand new project by just changing the orientation to landscape in app.json, Then opening expo go and trying to open the dev menu

**Comment by brentvatne** [comment]
this is a known issue, it isn't high priority for us but if someone would like to dig into it and help out we can review

**Comment by ridwansameer** [comment]
> this is a known issue, it isn't high priority for us but if someone would like to dig into it and help out we can review

Totally understandable! I'd be happy to take a look but I'm a bit unsure where to start!

**Comment by DylanTet** [comment]
I can take a look at this @brentvatne, I am looking for a good first issue to start contributing to expo :)

**Comment by cesargdm** [comment]
Looks like this is already fixed @brentvatne 

![simulator_screenshot_E3317EEF-8F24-4456-B7D3-05493C57EA35](https://github.com/user-attachments/assets/2197ef84-e3b4-4880-bf90-f457e4de9575)
