### ISSUE TITLE
Hiding lengthy "BugReporting extradata" from logs

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#2139]
How does one hide BugReporting extradata from logs?

Related commit: https://github.com/expo/xdl/commits?author=fson&since=2018-05-01T00:00:00Z&until=2018-05-26T00:00:00Z
Related SO: https://stackoverflow.com/questions/51540414/is-it-possible-to-hide-the-bugreporting-extradata-in-react-native-using-expo

### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.2.1
  Yarn: 1.5.1
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/headsuphealth-dcdb8a51-dc73-4f61-8471-7ee409d6e26f.tar.gz

using Expokit on iOS and Android

### Steps to Reproduce

Frequently, when getting error messages, they are prefaced by several enormous blocks of `BugReporting extradata`, which makes it difficult to navigate the logs

### Expected Behavior

I just see errors and log statements; or the extradata is collapsed by default.

### Actual Behavior

Scrolling for 15 seconds

![logs](https://user-images.githubusercontent.com/1566400/44601887-be071880-a792-11e8-836b-28e05cbfc99f.gif)

**Comment by JackHull** [comment]
Any updates on this? It really bugs me out.

**Comment by fson** [comment]
When using Expo CLI, BugReporting extra data is filtered out from the logs.
