### ISSUE TITLE
Android Expo app crashing after splash screen – no change in development code

### ISSUE THREAD

**Issue by eamckinney** [expo/expo#21390]
### Minimal reproducible example

https://github.com/eamckinney/guess-the-beta

### Summary

I've been using Expo to run my app on my Pixel 7 phone while I work on it. Two days ago, after no code changes were made, I opened up Expo to run the app (running `expo start` in my project folder to start Metro Bundler, which successfully loads). The splash screen for the app loads while the project bundles, it bundles successfully (`Android Bundling complete 1603ms` shows up in my console), and then the Expo app crashes with no error. 

I went back to previous commits that I am certain worked before and the Expo app still crashes. I am able to use a friend's Apple phone with Expo, and the app loads correctly, so I believe it is an issue with the Expo app on my phone specifically (some auto update or something that happened this past week?).

I have attached the logcat errors. Thanks in advance for your help!

[logcat.txt](https://github.com/expo/expo/files/10828563/logcat.txt)

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.10.0 - ~/node_modules/.bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
      Watchman: 2022.02.21.00 - /opt/homebrew/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.0, 34.0.0
        System Images: android-27 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google Play ARM 64 v8a, android-UpsideDownCake | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.13 => 46.0.19 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 6.3.1
    Expo Workflow: managed

**Comment by brentvatne** [comment]
update expo go from the app store. there was a version live for a day where sdk 46 projects would crash in expo go. you should have version 2.28.3

**Comment by eamckinney** [comment]
Thanks so much @brentvatne ! Works now!
