### ISSUE TITLE
[docs] expo-auth-session's Azure AD B2C example is wrong and doesn't work

### ISSUE THREAD

**Issue by andristarr** [expo/expo#21400]
### Summary

expo-auth-session's Azure AD B2C example for authentication in the documentation doesnt work and is wrong.

Always returns the error below despite the scope is added to the App Registration in Azure. Works with flow works with Insomnia.

More info: AADB2C90012: The scope 'openid offline_access https://tenant.onmicrosoft.com/api://62bc39a4-f689-4bb1-a1ae-1763d6f17539/Read.Weather' provided in request is not supported.

### Link to the related docs page

https://docs.expo.dev/guides/authentication/#azure

### Anything else?

Please, give a working example for Azure AD B2C.

**Comment by dotBeFoRE** [comment]
You shouldn't include `https://tenant.onmicrosoft.com/` in your api scopes so only `api://62bc39a4-f689-4bb1-a1ae-1763d6f17539/Read.Weather`

**Comment by andristarr** [comment]
Thanks for taking time to respond. I have also tried with that, and I receive the same error. In fact, I receive the same error when I only request scope offline_access or only openid :/

**Comment by andristarr** [comment]
Additional to the above I have also tested with:

https://b2ctestark.b2clogin.com/b2ctestark.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_susi&client_id=066aa593-c806-4c5c-88ae-b3ca8113c7ac&nonce=defaultnonce&redirect_uri=https://jwt.ms&scope=openid profile offline_access https://b2ctestark.onmicrosoft.com/0901a7f8-50b0-4118-971e-4ad1a690dcf9/Weather.Read&response_type=token&prompt=login

Returns the token perfectly. I have created the tenant. (Don't be thrown off by the different scope name, I have created a new tenant from scratch to see if this is not a one off. The scope name was copied straight from Azure.)

Same behaviour with the library example.

**Comment by andristarr** [comment]
With the same configuration the following works okay and returns the token as expected (with the scopes and claims) confirming it is not an error with the Azure configuration:

```
const res = await WebBrowser.openAuthSessionAsync(
      "https://b2ctestark.b2clogin.com/b2ctestark.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_susi&client_id=IDPART-88ae-b3ca8113c7ac&nonce=defaultnonce&redirect_uri=msauth.com.ios.sportapp.beta://auth&scope=openid%20profile%20offline_access%20https%3A%2F%2Fb2ctestark.onmicrosoft.com%2F0901a7f8-IDPART-0dcf9%2FWeather.Read&response_type=token&prompt=login",
      "msauth.com.ios.sportapp.beta://auth"
    );

    setResult(res);
```

**Comment by andristarr** [comment]
This is Still an ongoing issue

**Comment by amandeepmittal** [comment]
Hey @andristarr, we updated the Azure example after a contribution from @BeBoRE. If you think the issue still persists and anything can be done to update the example, please feel free to create a PR. 

Since there is a large amount of examples in this guide with different third party providers and their nature of changing configurations at times, it is hard for us to keep these examples up to date. However, we welcome PRs.

**Comment by BeBoRE** [comment]
Thanks man,

I am now working on an app that needs authentication using Discord, but that also has some weird quirks. So I am working on also writing documentation on auth with Discord.
