### ISSUE TITLE
[docs]  Modal Placement in "Create a Modal"

### ISSUE THREAD

**Issue by tigeryell99** [expo/expo#21403]
### Summary

In the "Create a Modal" portion of the tutorial, the text says to place it `below` the StatusBar but the example has it `above` it.
![Create_a_modal_-_Expo_Documentation](https://user-images.githubusercontent.com/3526843/221359052-d7cdca93-3a44-4acd-ab5e-726555c57d00.jpg)

### Link to the related docs page

https://docs.expo.dev/tutorial/create-a-modal/

### Anything else?

https://github.com/expo/expo/compare/main...tigeryell99:expo:patch-1

**Comment by amandeepmittal** [comment]
Since this section was updated in #21407, I'm closing this issue. Thank you, once again, for your contribution!
