### ISSUE TITLE
UIBackgroundModes not working on iOS

### ISSUE THREAD

**Issue by cchbr** [expo/expo#21411]
### Minimal reproducible example

app.config.js block for ios: 
``` 
"ios": {
       "bundleIdentifier": "com.company.app",
       "googleServicesFile": "./GoogleService-Info.plist",
       "infoPlist": {
         "NSMicrophoneUsageDescription": "Allow access to your microphone to record and send audio messages",
         "UIBackgroundModes": ["remote-notification"],
       },
       "config": {
         "usesNonExemptEncryption": false
       }
}, 
```

### Summary

I'm trying to implement abackground notification task but it's not running on iOS.

When running it in Expo Go the following warning is displayed

```
[Unhandled promise rejection: Error: Background remote notifications have not been configured. To enable it, add `remote-notification` to `UIBackgroundModes` in the application's Info.plist file.]
at node_modules\@babel\runtime\helpers\construct.js:null in _construct
at node_modules\@babel\runtime\helpers\wrapNativeSuper.js:null in Wrapper
at http://192.168.0.110:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in _createSuperInternal
at node_modules\expo-modules-core\build\errors\CodedError.js:null in constructor
```

Does anyone know why it doesn't acknowledge the "remote-notification" I have provided?

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.20.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^47.0.0 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.12
    Expo Workflow: managed

**Comment by devloop11** [comment]
Still reproducible with
`expo 52.0.11`

```
"ios": {
      "supportsTablet": true,
      "infoPlist": {
        "UIBackgroundModes": [
          "audio"
        ]
      },
    },
```

`UIBackgroundModes` is added but without items

**Comment by johannbuscail** [comment]
Any update ?

**Comment by julian-gargicevich** [comment]
Same

**Comment by cfl777** [comment]
Same here!

**Comment by julian-gargicevich** [comment]
> Same here!

In my case it was the new expo-video overriding the value by setting supportsBackgroundPlayback to false in the app config
