### ISSUE TITLE
[docs]  Webpack issue resolution support

### ISSUE THREAD

**Issue by tigeryell99** [expo/expo#21412]
### Summary

When running through the tutorial at the [Platform Differences](https://docs.expo.dev/tutorial/platform-differences/) section. After the `npm install dom-to-image` step we are told to start the web server with the `w` option. This results in the `ERR_OSSL_EVP_UNSUPPORTED` error.  

A Google search resulting in suggesting to modify the "scripts" portion in package.json to prepend `export NODE_OPTIONS=--openssl-legacy-provider && ` to the `start` and `web` scripts which did not work for me. Ultimately I had to use `nvm` to use node 16.19.1.

Suggestions: 

- Update the tutorial configuration to include the appropriate webpack.config file and any other updates needed. 
- OR add some other suggested fixes/workarounds.

### Link to the related docs page

https://docs.expo.dev/tutorial/platform-differences/

**Comment by byCedric** [comment]
The issue you are encountering looks a lot like: https://github.com/expo/expo/issues/20652, and should be able to workaround it with the same solution as [this comment](https://github.com/expo/expo/issues/20652#issuecomment-1396974576).

If this doesn't solve your issue, please open a new issue report with a reproducible example.

Hope this helps!
