### ISSUE TITLE
Eas build failed expo 48

### ISSUE THREAD

**Issue by Aris-ngoy** [expo/expo#21423]
### Summary

Running "expo doctor"
- Finding all copies of expo-modules-autolinking
- Finding all copies of @expo/config-plugins
[stderr] 
[02:00:12] Expected package @expo/config-plugins@~6.0.0
[stderr] 
[02:00:12] Found invalid:
[stderr] 
[02:00:12]   @expo/config-plugins@5.0.4
[stderr] 
[02:00:12]   (for more info, run: npm why @expo/config-plugins)
- Finding all copies of @expo/prebuild-config
- Finding all copies of @unimodules/core
- Finding all copies of @unimodules/react-native-adapter
- Finding all copies of react-native-unimodules
Command "expo doctor" failed.
bash exited with non-zero code: 1

### What platform(s) does this occur on?

iOS

### SDK Version

48

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2023.01.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/aris/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Electric Eel 2022.1.1 Electric Eel 2022.1.1
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.4 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: bare

### Minimal reproducible example

{
  "name": "abela",
  "version": "1.3.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/config-plugins": "~6.0.0",
    "@gorhom/bottom-sheet": "^4",
    "@kichiyaki/react-native-barcode-generator": "^0.6.7",
    "@r0b0t3d/react-native-collapsible": "^1.3.3",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-firebase/app": "^17.3.1",
    "@react-native-firebase/database": "^17.3.1",
    "@react-native-masked-view/masked-view": "0.2.8",
    "@react-navigation/bottom-tabs": "^6.5.4",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/native-stack": "^6.9.9",
    "@shopify/flash-list": "1.4.0",
    "@tanstack/react-query": "^4.24.4",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "axios": "^1.3.1",
    "credit-card-type": "^9.1.0",
    "expo": "~48.0.4",
    "expo-barcode-scanner": "~12.3.1",
    "expo-build-properties": "~0.5.1",
    "expo-camera": "~13.2.1",
    "expo-clipboard": "~4.1.1",
    "expo-constants": "~14.2.1",
    "expo-contacts": "~12.0.1",
    "expo-crypto": "~12.2.1",
    "expo-device": "~5.2.1",
    "expo-face-detector": "~12.1.1",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-keep-awake": "~12.0.1",
    "expo-linear-gradient": "~12.1.1",
    "expo-linking": "~4.0.1",
    "expo-location": "~15.1.1",
    "expo-network": "~5.2.1",
    "expo-sharing": "~11.2.1",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "expo-store-review": "~6.2.1",
    "intl": "^1.2.5",
    "jotai": "^2.0.2",
    "linqts": "^1.14.4",
    "lodash": "^4.17.21",
    "lottie-react-native": "5.1.4",
    "moment": "^2.29.4",
    "moti": "^0.22.0",
    "onesignal-expo-plugin": "^1.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.43.0",
    "react-native": "0.71.3",
    "react-native-animatable": "^1.3.3",
    "react-native-animated-nav-tab-bar": "^3.1.8",
    "react-native-autolink": "^4.0.0",
    "react-native-base64": "^0.2.1",
    "react-native-big-list": "^1.6.0",
    "react-native-biometrics": "^3.0.1",
    "react-native-bouncy-checkbox": "^3.0.6",
    "react-native-circular-progress": "^1.3.8",
    "react-native-code-push": "^7.1.0",
    "react-native-compressor": "^1.6.1",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-crypto-js": "^1.0.0",
    "react-native-curved-bottom-bar": "^2.1.4",
    "react-native-device-info": "^10.3.0",
    "react-native-encrypted-storage": "^4.0.3",
    "react-native-error-helper": "^0.2.2",
    "react-native-event-listeners": "^1.0.7",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-html-to-pdf": "^0.12.0",
    "react-native-image-colors": "^1.5.1",
    "react-native-input-outline": "^1.5.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-mmkv": "^2.6.1",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^14.0.1",
    "react-native-onesignal": "^4.5.0",
    "react-native-pager-view": "6.1.2",
    "react-native-progress": "^5.0.0",
    "react-native-qrcode-svg": "^6.2.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-reanimated-carousel": "^3.3.0",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-share": "^8.1.0",
    "react-native-shared-element": "0.8.8",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-super-grid": "^5.0.0",
    "react-native-svg": "13.4.0",
    "react-native-swipeable-item": "^2.0.9",
    "react-native-toast-message": "^2.1.5",
    "react-native-user-inactivity": "^1.2.0",
    "react-native-view-shot": "3.5.0",
    "react-native-web": "~0.18.11",
    "react-native-webview": "11.26.0",
    "recoil": "^0.7.6",
    "sp-react-native-in-app-updates": "^1.3.1",
    "styled-components": "^5.3.6",
    "twrnc": "^3.6.0"
  },
  "resolutions": {
    "react-native-gesture-handler": "~2.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/lodash": "^4.14.191",
    "@types/react": "~18.0.27",
    "@types/react-native": "~0.70.6",
    "@types/react-native-base64": "^0.2.0",
    "@types/react-native-crypto-js": "^1.0.0",
    "@types/react-native-html-to-pdf": "^0.8.1",
    "@types/react-native-snap-carousel": "^3.8.5",
    "babel-plugin-module-resolver": "^5.0.0",
    "react-native-dotenv": "^3.4.7",
    "react-native-svg-transformer": "^1.0.0",
    "typescript": "^4.9.4"
  },
  "private": true
}

**Comment by arjendevos** [comment]
Does your error include: `A problem occurred evaluating project ':react-native-mmkv'.` ?

**Comment by Aris-ngoy** [comment]
No it does not

**Comment by vsolovev** [comment]
Got the same error during migration from SDK version 47 to 48. The issue is Found invalid: @expo/config-plugins@4.1.1 by the next chain:
```@expo/config-plugins@4.1.1
node_modules/@expo/config/node_modules/@expo/config-plugins
  @expo/config-plugins@"4.1.1" from @expo/config@6.0.20
  node_modules/@expo/config
    @expo/config@"6.0.20" from @expo/webpack-config@18.0.1
    node_modules/@expo/webpack-config
      @expo/webpack-config@"^18.0.1" from the root project```
So the issue is "webpack-config" version here, but 18.0.1 is the latest one

**Comment by trev91** [comment]
I'm getting this same issue after following the steps to upgrade from 47 to 48.

**Comment by rakeshpetit** [comment]
I faced a similar problem after upgrading to Expo 48 and this is how I resolved.

Add resolutions to `package.json` like this, delete `node_modules` and rerun `npm` or `yarn`.
```
 "resolutions": {
    "@expo/config-plugins": "~6.0.0",
    "@expo/prebuild-config": "~6.0.0"
  }
```

After this, `expo-doctor` did not complain. I found this as a solution in another Github issue.

**Comment by Hollum** [comment]
Getting the same issue after upgrading from 47 to 48.

**Comment by Aris-ngoy** [comment]
> I faced a similar problem after upgrading to Expo 48 and this is how I resolved.
> 
> Add resolutions to `package.json` like this, delete `node_modules` and rerun `npm` or `yarn`.
> 
> ```
>  "resolutions": {
>     "@expo/config-plugins": "~6.0.0",
>     "@expo/prebuild-config": "~6.0.0"
>   }
> ```
> 
> After this, `expo-doctor` did not complain. I found this as a solution in another Github issue.

This help me to get rid of “expo-doctor”  warning message but to get the build fix, I did revoke all my provisioning profile and certificate and recreate them and voila issue fixed for me

**Comment by karlmarxlopez** [comment]
Additional information, if you are installing it in a monorepo (ex. TurboRepo).

You need to add the `resolutions` in the root `package.json`, not the inside the workspace.

**Comment by ammarfaris** [comment]
> > I faced a similar problem after upgrading to Expo 48 and this is how I resolved.
> > Add resolutions to `package.json` like this, delete `node_modules` and rerun `npm` or `yarn`.
> > ```
> >  "resolutions": {
> >     "@expo/config-plugins": "~6.0.0",
> >     "@expo/prebuild-config": "~6.0.0"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After this, `expo-doctor` did not complain. I found this as a solution in another Github issue.
> 
> In case of using npm it is not resolutions but overrides.

thanks @koli2

**Comment by alessandrocapra** [comment]
Unfortunately 

> > I faced a similar problem after upgrading to Expo 48 and this is how I resolved.
> > Add resolutions to `package.json` like this, delete `node_modules` and rerun `npm` or `yarn`.
> > ```
> >  "resolutions": {
> >     "@expo/config-plugins": "~6.0.0",
> >     "@expo/prebuild-config": "~6.0.0"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After this, `expo-doctor` did not complain. I found this as a solution in another Github issue.
> 
> In case of using npm it is not resolutions but overrides.

Unfortunately, I followed the exact instructions here and it didn't work for me.
- Update from SDK 47 to 48
- expo doctor gives: 
```bash
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@5.0.4
    (for more info, run: npm why @expo/config-plugins)
Advice:
  • Upgrade dependencies that are using the invalid package versions.
  ```
- using npm, I added the following lines in my package.json:
```bash
  "overrides": {
    "@expo/config-plugins": "~6.0.0",
    "@expo/prebuild-config": "~6.0.0"
  }
```
- rm -rf node_modules && npm i
- run npx expo-doctor, same error as above

Anybody else?

**Comment by Brysonmk1984** [comment]
@alessandrocapra  same as you three weeks later... I tried everything here and nothing's working.

**Comment by kirtikapadiya** [comment]
@alessandrocapra  same as you , Tried everything but didn't work for me

**Comment by alexxsanya** [comment]
```
 "overrides": {
    "@expo/config-plugins": "~6.0.0",
    "@expo/prebuild-config": "~6.0.0"
  }
```

Adding this to the package.json has been able to fix the issue for me.

**Comment by ren1suyama** [comment]
> Unfortunately
> 
> > > I faced a similar problem after upgrading to Expo 48 and this is how I resolved.
> > > Add resolutions to `package.json` like this, delete `node_modules` and rerun `npm` or `yarn`.
> > > ```
> > >  "resolutions": {
> > >     "@expo/config-plugins": "~6.0.0",
> > >     "@expo/prebuild-config": "~6.0.0"
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After this, `expo-doctor` did not complain. I found this as a solution in another Github issue.
> > 
> > 
> > In case of using npm it is not resolutions but overrides.
> 
> Unfortunately, I followed the exact instructions here and it didn't work for me.
> 
> * Update from SDK 47 to 48
> * expo doctor gives:
> 
> ```shell
> Issues:
>   Expected package @expo/config-plugins@~6.0.0
>   Found invalid:
>     @expo/config-plugins@5.0.4
>     (for more info, run: npm why @expo/config-plugins)
> Advice:
>   • Upgrade dependencies that are using the invalid package versions.
> ```
> 
> * using npm, I added the following lines in my package.json:
> 
> ```shell
>   "overrides": {
>     "@expo/config-plugins": "~6.0.0",
>     "@expo/prebuild-config": "~6.0.0"
>   }
> ```
> 
> * rm -rf node_modules && npm i
> * run npx expo-doctor, same error as above
> 
> Anybody else?

Same here...
Is updating from expo sdk 47 -> 48 impossible?
Should I update to 49 instead?

**Comment by ren1suyama** [comment]
I also got stuck when I used `npx expo-doctor` command and got the following result:

```
Detailed check results:

Expected package @expo/config-plugins@~6.0.0
Found invalid:
  @expo/config-plugins@7.0.0
  @expo/config-plugins@7.2.4
  @expo/config-plugins@5.0.4
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~6.0.0
Found invalid:
  @expo/prebuild-config@6.2.5
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions.
```

However, as written above, I managed to clear the conflicts between the libraries over-writing as below:

```
  "overrides": {
    "@expo/config-plugins": "~6.0.2",
    "@expo/prebuild-config": "~6.0.2"
  },
```

**Comment by SFaraji** [comment]
> I faced a similar problem after upgrading to Expo 48 and this is how I resolved.
> 
> Add resolutions to `package.json` like this, delete `node_modules` and rerun `npm` or `yarn`.
> 
> ```
>  "resolutions": {
>     "@expo/config-plugins": "~6.0.0",
>     "@expo/prebuild-config": "~6.0.0"
>   }
> ```
> 
> After this, `expo-doctor` did not complain. I found this as a solution in another Github issue.


Had the same issue and all resolved with isolation in the resolutions tag!

**Comment by JakubGie** [comment]
In my case problem was caused by one of the package that used outdated version of @expo/config-plugins.

Try: `npm ls @expo/config-plugins`

You will se which package causing problem (in my case it was expo-app-loading), so i uninstalled it:  `npm uninstall expo-app-loading`

After this npx expo-doctor didnt find any issues!
