### ISSUE TITLE
TypeError: [ios.infoPlist]: withIosInfoPlistBaseMod: Cannot read properties of undefined (reading 'ios')

### ISSUE THREAD

**Issue by danielricecodes** [expo/expo#21422]
### Summary

When trying to build my app, I get the following error:

```
TypeError: [ios.infoPlist]: withIosInfoPlistBaseMod: Cannot read properties of undefined (reading 'ios')
```

I have another EAS/Expo app on my computer that runs just fine and they both have an identical `expo.ios` configuration.  I have * no idea * what is wrong as one app works just fine and the other throws this error that tells me nothing useful!  

### Managed or bare?

Managed

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/opt/node@16/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: https://github.com/expo/react-native/archive/sdk-46.0.0.tar.gz => 0.69.1 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: managed
```

### Error output

```
$ EXPO_DEBUG=true yarn build:staging:ios
yarn run v1.22.19
$ eas build -p ios --profile=staging --auto-submit
ios.entitlements: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosEntitlementsBaseMod
ios.entitlements: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withAssociatedDomains ➜ withEntitlementsPlist
ios.entitlements: withExpoNotifications ➜ withStaticPlugin ➜ withRunOnce ➜ withNotifications ➜ withNotificationsIOS ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withExpoContacts ➜ withRunOnce ➜ withAccessesContactNotes ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withExpoAppleAuthentication ➜ withRunOnce ➜ withAppleSignInWarning ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withRunOnce ➜ withStripe ➜ withStripeIos ➜ withEntitlementsPlist
ios.infoPlist: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosInfoPlistBaseMod
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withVersion ➜ withInfoPlist
    TypeError: [ios.infoPlist]: withIosInfoPlistBaseMod: Cannot read properties of undefined (reading 'ios')
```

### Reproducible demo or steps to reproduce from a blank project

None.  I am just looking for more guidance on what the error means and how to fix it.

**Comment by Kudo** [comment]
hi there! i was wondering this might be some package dependency issues. could you share the package.json dependencies and devDependencies?

**Comment by douglowder** [comment]
That config looks like there is an `ios` object nested inside the main `ios` object, which I think is incorrect. Your config should look like this, yes?

```json
{
  "expo": {
    "slug": "<redacted>",
      "owner": "<redacted>",
      "version": "2.0.8",
      "orientation": "portrait",
      "icon": "./assets/icon.png",
      "splash": {
        "image": "./assets/splash.png",
        "resizeMode": "cover",
        "backgroundColor": "#ffffff"
      },
      "updates": {
        "fallbackToCacheTimeout": 0,
        "enabled": false
      },
      "assetBundlePatterns": [
        "**/*"
      ],
      "ios": {
        "supportsTablet": false,
        "buildNumber": "17",
        "infoPlist": {
          "NSCameraUsageDescription": "This app uses the camera to submit photos and videos to assist with your service request.  The camera may also be used to upload a profile picture if you choose to do so.",
          "NSPhotoLibraryAddUsageDescription": "This app requires access to your photo library if you wish to submit photos and videos to assist with your service request, or to submit a profile picture, if you choose to do so.",
          "NSPhotoLibraryUsageDescription": "The app accesses your photos to let you to upload your profile image or add completed jobs photos.",
          "NSMicrophoneUsageDescription": "This app requires access to your microphone if you wish to submit audio with your videos to assist with your service request.",
          "NSLocationAlwaysAndWhenInUseUsageDescription": "App requires geolocation to improve the quality of the service",
          "NSLocationAlwaysUsageDescription": "App requires geolocation to improve the quality of the service",
          "NSLocationWhenInUseUsageDescription": "App requires geolocation to improve the quality of the service",
          "UIBackgroundModes": [
            "location",
          "fetch"
          ]
        },
        "config": {
          "usesNonExemptEncryption": false
        }
      },
      "android": {
        "googleServicesFile": "./google-services.json",
        "versionCode": 43
      },
      "web": {
        "favicon": "./assets/favicon.png"
      },
      "plugins": [
        [
          "@stripe/stripe-react-native",
        {
          "merchantIdentifier": "<redacted>",
          "enableGooglePay": false
        }
        ]
      ],
      "extra": {
        "eas": {
          "projectId": "<redacted>"
        }
      }
  }
}
```

**Comment by MylchenkoAlexandr** [comment]
I use "expo-image-picker": "~13.1.1" and now Apple Store (after EAS submit) always send me email message:

"_...The Info.plist file for the “app name” bundle should contain a **NSMicrophoneUsageDescription** key with a user-facing purpose string explaining clearly and completely why your app needs the data..._" 

But **NSMicrophoneUsageDescription** already include in app.json:
```
    "plugins": [
      [
        "expo-image-picker",
        {
          "//": "Disables the microphone permission",
          "photosPermission": "Надавши доступ до бібліотеки ваших зображень, ви зможете вибрати фото для свого профілю.",
          "cameraPermission": "Надавши доступ до камери, ви можете зробити своє фото у профілі.",
          "microphonePermission": false
        }
      ]
    ],
```

```
      "infoPlist": {
        "NSMicrophoneUsageDescription": "This app does not require access to the microphone.",
        "NSUserTrackingUsageDescription": "Це допоможе нам дізнатися, звідки ви та інші клієнти дізналися про Ешка Таксі, та допоможе оптимізувати витрати, щоб підвищити якість послуг для наших пасажирів та водіїв.",
        "NSLocationUsageDescription": "Ваше місце розташування використовується для пошуку найближчих до вас водіїв",
        "NSLocationAlwaysUsageDescription": "Ваше місце розташування використовується для пошуку найближчих до вас водіїв",
        "NSLocationAlwaysAndWhenInUseUsageDescription": "Ваше місце розташування використовується для пошуку найближчих до вас водіїв",
        "NSLocationWhenInUseUsageDescription": "Ваше місце розташування використовується для пошуку найближчих до вас водіїв",
        "NSCameraUsageDescription": "Надавши доступ до камери, ви можете зробити своє фото у профілі.",
        "NSPhotoLibraryUsageDescription": "Надавши доступ до бібліотеки ваших зображень, ви зможете вибрати фото для свого профілю.",
        "NSLocationDefaultAccuracyReduced": true,
        "ITSAppUsesNonExemptEncryption": false,
        "UIBackgroundModes": [
          "location",
          "fetch"
        ]
      }
```

Any help please!

**Comment by danielricecodes** [comment]
> That config looks like there is an `ios` object nested inside the main `ios` object, which I think is incorrect. Your config should look like this, yes?
> 
> ```json
> {
>   "expo": {
>     "slug": "<redacted>",
>       "owner": "<redacted>",
>       "version": "2.0.8",
>       "orientation": "portrait",
>       "icon": "./assets/icon.png",
>       "splash": {
>         "image": "./assets/splash.png",
>         "resizeMode": "cover",
>         "backgroundColor": "#ffffff"
>       },
>       "updates": {
>         "fallbackToCacheTimeout": 0,
>         "enabled": false
>       },
>       "assetBundlePatterns": [
>         "**/*"
>       ],
>       "ios": {
>         "supportsTablet": false,
>         "buildNumber": "17",
>         "infoPlist": {
>           "NSCameraUsageDescription": "This app uses the camera to submit photos and videos to assist with your service request.  The camera may also be used to upload a profile picture if you choose to do so.",
>           "NSPhotoLibraryAddUsageDescription": "This app requires access to your photo library if you wish to submit photos and videos to assist with your service request, or to submit a profile picture, if you choose to do so.",
>           "NSPhotoLibraryUsageDescription": "The app accesses your photos to let you to upload your profile image or add completed jobs photos.",
>           "NSMicrophoneUsageDescription": "This app requires access to your microphone if you wish to submit audio with your videos to assist with your service request.",
>           "NSLocationAlwaysAndWhenInUseUsageDescription": "App requires geolocation to improve the quality of the service",
>           "NSLocationAlwaysUsageDescription": "App requires geolocation to improve the quality of the service",
>           "NSLocationWhenInUseUsageDescription": "App requires geolocation to improve the quality of the service",
>           "UIBackgroundModes": [
>             "location",
>           "fetch"
>           ]
>         },
>         "config": {
>           "usesNonExemptEncryption": false
>         }
>       },
>       "android": {
>         "googleServicesFile": "./google-services.json",
>         "versionCode": 43
>       },
>       "web": {
>         "favicon": "./assets/favicon.png"
>       },
>       "plugins": [
>         [
>           "@stripe/stripe-react-native",
>         {
>           "merchantIdentifier": "<redacted>",
>           "enableGooglePay": false
>         }
>         ]
>       ],
>       "extra": {
>         "eas": {
>           "projectId": "<redacted>"
>         }
>       }
>   }
> }
> ```

Yes - thats just a typo on my part.  I just checked my file and will update it above.

**Comment by danielricecodes** [comment]
I'm just going to close this.  It works just fine on my Ubuntu laptop.  My Mac M1 was having problems with only this one app - again - my other app with nearly identical configuration built just fine on both laptops.

**Comment by mozzius** [comment]
Hello, I'm still having this issue. I only have an M1 mac so I can't just use a different laptop.

My `app.config.ts`:

```ts
import type { ExpoConfig } from "@expo/config";

const defineConfig = (): ExpoConfig => ({
  name: <redacted>,
  slug: <redacted>,
  scheme: <redacted>,
  version: "0.0.1",
  owner: <redacted>,
  orientation: "portrait",
  icon: "./assets/icon.png",
  userInterfaceStyle: "light",
  splash: {
    image: "./assets/icon.png",
    resizeMode: "cover",
    backgroundColor: "#888888",
  },
  updates: {
    fallbackToCacheTimeout: 0,
  },
  assetBundlePatterns: ["**/*"],
  ios: {
    supportsTablet: false,
    bundleIdentifier: <redacted>,
    buildNumber: "1",
  },
  android: {
    package: <redacted>,
    versionCode: 1,
    adaptiveIcon: {
      foregroundImage: "./assets/icon.png",
      backgroundColor: "#888888",
    },
  },
  extra: {
    eas: {
      projectId: <redacted>,
    },
  },
  plugins: ["./expo-plugins/with-modify-gradle.js"],
});

export default defineConfig;
```

**Comment by mozzius** [comment]
Update: got this working. I switched to Node 16 (from 18) and also reinstalled `eas-cli` using pnpm (not sure which one did the trick)

**Comment by erikostling** [comment]
I had a similar issue, for me it was a blank `GoogleService-Info.plist` that was the problem.

**Comment by ShepSims** [comment]
This was happening for me on a non-M1 Mac running node v20.11.0 on was-cli version 7.2.0 -

Upgrading to 7.3.0 fixed the issue

Run npm install -g eas-cli

Wait for install, then close terminal and reopen and it should work

**Comment by danylo-trofimenko-brickred** [comment]
I have got such error `expo withIosInfoPlistBaseMod: 51.0.0 is not a valid version` when run `npx expo prebuild -p ios`

fixed by deleting and installing again `node_modules`
