### ISSUE TITLE
[docs] Debugging with React Native Debugger is no longer possible

### ISSUE THREAD

**Issue by btraut** [expo/expo#21439]
### Summary

It seems that the Hermes engine update with SDK 48 has broken remote debugging, instead opting for "Open JS Debugger" which is hardcoded to Chrome (despite the fact I have Brave as my default browser and I haven React Native Debugger listening on the correct port).

While I would love for this issue to be resolved, the very least we can do to resolve is to update the docs to no longer say it's possible to use RND.

### Link to the related docs page

https://docs.expo.dev/workflow/debugging/

**Comment by douglowder** [comment]
@btraut if you wish, you can add

```json
"jsEngine": "jsc",
```

to your `app.json`, and then you can use the JSC engine as before.

**Comment by btraut** [comment]
Aha! I appreciate the details. Closing this issue.

**Comment by juanmagalhaes** [comment]
I have just installed a brand new expo project here and was trying to setup React Native Debugger but I couldn't manage to do so yet.

It never seems to connect to the android simulator. I haven't tried ios or phones yet.

**Comment by Eumhongin** [comment]
same here any solutions? i can't found debug button
![스크린샷 2024-08-14 오후 4 54 43](https://github.com/user-attachments/assets/b9a379a1-c9e4-4e53-8eef-30ab11761b6c)

**Comment by fmukendi** [comment]
Yes. it is completely broken
