### ISSUE TITLE
Trying to update to latest ExpoCLI 6.3.2. Still only recognizes legacy expo-cli!

### ISSUE THREAD

**Issue by wsup-mike** [expo/expo#21430]
### Summary

Hello, 

Was wondering if anyone can help. Trying to simply update from older 6.3.0 to latest 6.3.2. After performing the command, 'expo --version', it still reads:

"WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
6.3.0"

I feel like I have tried everything using ChatGPT for assistance but to no avail:

- Updated Node version to LTS version 18.14.2 (current)
- Updated Yarn to perform Yarn package install: 'yarn add global expo-cli' (and when I show everything globally installed using Y 'yarn global list', it clearly shows 6.3.2 installed:

```
$ yarn global list
yarn global v1.22.19
warning package.json: No license field
info "expo-cli@6.3.2" has binaries:
   - expo
   - expo-cli
Done in 3.80s.
```

But then when I double check version, I get the following warning:

```
WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
6.3.0
```

Not sure what I might be doing wrong. 

Any help is appreciated. 
Thanks!

### SDK Version

Currently stuck on Expo CLI 6.3.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 32, 33, 33
        Build Tools: 30.0.0, 30.0.3, 31.0.0, 33.0.2, 34.0.0
        System Images: android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: AI-221.6008.13.2211.9514443
    Expo Workflow: managed

### Minimal reproducible example

Summary from ChatGPT proposed solutions and results:

Before creating a bug report on the Expo GitHub page, you can try a few more steps to see if the issue can be resolved. Here are some additional steps you can try:

- Try uninstalling the current version of Expo CLI and reinstalling it using the npm package manager instead of yarn. You can do this by running the command npm uninstall -g expo-cli followed by npm install -g expo-cli@latest.

```
mramos@MikeRamos MINGW64 ~/documents/portfolio projects
$ npm uninstall -g expo-cli

removed 1169 packages, and audited 1 package in 15s

found 0 vulnerabilities

mramos@MikeRamos MINGW64 ~/documents/portfolio projects
$ npm install -g expo-cli@latest
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility 
table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1169 packages, and audited 1170 packages in 2m

102 packages are looking for funding
  run `npm fund` for details        

16 vulnerabilities (5 moderate, 11 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

// Restart Terminal here...

mramos@MikeRamos MINGW64 ~
$ cd documents

mramos@MikeRamos MINGW64 ~/documents
$ cd 'portfolio projects'

mramos@MikeRamos MINGW64 ~/documents/portfolio projects
$ expo --version
WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
6.3.0
```

- Ensure that your $PATH environment variable is correctly set to the directory containing the latest version of the Expo CLI binary. You can check this by running the command echo $PATH in your terminal and verifying that the correct directory is listed.

```
$ echo $PATH
/c/Users/mramos/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/mramos/bin:/c/Program Files/Common Files/Oracle/Java/javapath:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Intel/OpenCL SDK/2.0/bin/x86:/c/Program Files (x86)/Intel/OpenCL SDK/2.0/bin/x64:/c/Program Files (x86)/Calibre2:/c/WINDOWS/System32/OpenSSH:/c/mongodb/bin:/c/mongodb/bin/mongosh-1.0.1-win32-x64/bin:/cmd:/c/Users/mramos/AppData/Roaming/nvm:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Program Files/OpenJDK/openjdk-11.0.15_10/bin:/c/Users/mramos/AppData/Local/Android/Sdk/platform-tools:%ANDROID_HOME%/platform-tools:%ANDROID_HOME%/tools:/c/Program Files/Intel/HAXM:/c/Program Files/nodejs:/c/Users/mramos/AppData/Local/Microsoft/WindowsApps:/c/Users/mramos/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/mramos/AppData/Roaming/nvm:/c/Program 
Files/nodejs:/c/Users/mramos/AppData/Local/Android/Sdk/platform-tools:/c/Program Files/Intel/HAXM:/c/Users/mramos/AppData/Roaming/npm:/usr/bin/vendor_perl:/usr/bin/core_perl

// Performing 'which expo'

$ which expo
/c/Program Files/nodejs/expo
```

- Check if there are any conflicts between different versions of Node.js installed on your system. You can use a version manager like nvm to easily switch between different Node.js versions and ensure that the correct version is being used.
```
mramos@MikeRamos MINGW64 ~/documents/portfolio projects
$ node --version
v18.14.2
```

**Comment by douglowder** [comment]
Inside your project, you should be executing

```
npx expo --version
```

The supported CLI is now `@expo/cli` (not `expo-cli`) and is not intended to be installed globally.

https://docs.expo.dev/workflow/glossary-of-terms/#local-expo-cli

**Comment by KaulSalil** [comment]
@douglowder I earlier had expo-cli installed globally I uninstalled the same .  Now when I run  npm run android
 on terminal . I see the following  "This command requires Expo CLI. Do you want to install it globally [Y/n]? " . I am confused do I still need to install expo/cli globally ?  I read the documentation but I didnt find any clear instructions on how to proceed

**Comment by douglowder** [comment]
@KaulSalil you need to modify your `package.json`, specifically the `android` entry in the `scripts` section.

**Comment by KaulSalil** [comment]
@douglowder I am sorry I don't understand, currently in my package.json the android entry is "android": "expo start --android" . What should I change this to ?

**Comment by douglowder** [comment]
It should be `npx expo start --android`.
