### ISSUE TITLE
Bare minimum template contains config that disables Flipper on EAS builds on iOS

### ISSUE THREAD

**Issue by foyarash** [expo/expo#21441]
### Summary

It seems that the expo template bare minimum contains a condition in the iOS Podfile that disables Flipper in iOS development builds.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo-dev-client 2.1.3
expo 48.0.4
expo-build-properties 0.5.1

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.10.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.4 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.11 => 0.18.12
    Expo Workflow: managed
```

### Reproducible demo

- Create a project with `yarn create expo-app`
- Install `expo-build-properties` and enable Flipper for iOS
- Run an eas build

https://github.com/expo/expo/blob/1448d9a01046e561a036bca715cfec7487b3b74f/templates/expo-template-bare-minimum/ios/Podfile#L26

The breaking condition comes from here

**Comment by sdacunha** [comment]
Just leaving a note here - noticing existing projects also having the CI=1 check in the podfile after prebuild. This would disable Flipper for our custom development client builds that we do in EAS unfortunately

**Comment by brentvatne** [comment]
this should be fixed by https://github.com/expo/expo/pull/21442 - will be deployed tomorrow

**Comment by Kudo** [comment]
close via #21442 and it's published now. thanks @foyarash for your fix!

**Comment by gdanov** [comment]
> 

I've been struggling with this issue on existing project. All dependencies latest. How do I fix my existing project? Flipper shows logs & network requests, but have lost the reload and dev menu buttons since I upgraded to sdk 48

**Comment by dalley8626** [comment]
any plans to support flipper via managed workflow?
