### ISSUE TITLE
Using pedometer results in an error in Android.

### ISSUE THREAD

**Issue by hallaji** [expo/expo#2147]
Using `Pedometer.watchStepCount` method results in an error.

### Environment

  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.1
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

### Steps to Reproduce

1. Get the example from [Expo Docs](https://docs.expo.io/versions/latest/sdk/pedometer) for Pedometer.
2. Paste it into `App.js`.
3. Run the android. So, the first load is successful.
4. Make some changes (maybe an space) in code (Just to fire watchman). 
5. Reloading results in an error.

### Expected Behavior

I would expect to get the user's step count. Note: It works perfectly on iOS.

### Actual Behavior

First load of app was successful. Then making some changes results in an error:

```
Already managing a GoogleApiClient with id 0
checkState
    null:8
zza
    null:35
build
    null:381
assertApiClient
    PedometerModule.java:85
watchStepCount
    PedometerModule.java:131
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:789
dispatchMessage
    Handler.java:98
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764
```

### Reproducible Demo

It is just an example provided on [Expo Docs](https://docs.expo.io/versions/latest/sdk/pedometer) for pedometer.

**Comment by FiberJW** [comment]
Hi, we’re closing inactive issues that apply to SDK versions we no longer support. I wasn’t able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks :)
