### ISSUE TITLE
EXPO_USE_PATH_ALIASES doesn't work

### ISSUE THREAD

**Issue by Aleksion** [expo/expo#21472]
### Minimal reproducible example

https://github.com/Aleksion/expo-test

### Summary

I've been trying to get Typescript import aliases to work for the last hour or so with no success.
Doesn't work in a fresh project either.

Steps tried:

Added baseUrl and paths to tsconfig.json
made sure we're using EXPO SDK 48
Added EXPO_USE_PATH_ALIASES=1 to environment variables
But still receive:
Unable to resolve "~/components/Test" from "App.tsx"

Managed or bare workflow?
managed

What platform(s) does this occur on?
iOS

Package versions
    "expo": "~48.0.4",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "typescript": "^4.9.4",
    "@types/react": "~18.0.27"

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 12.5
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v18.6.0/bin/yarn
npm: 8.13.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
IDEs:
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
npmPackages:
expo: ~48.0.4 => 48.0.4
react: 18.2.0 => 18.2.0
react-native: 0.71.3 => 0.71.3
Expo Workflow: managed

<img width="510" alt="Screen Shot 2023-03-01 at 9 29 25 PM" src="https://user-images.githubusercontent.com/3367641/222269082-e462c1dd-49f3-4a7a-8d0b-fb72972407ee.png">

**Comment by aleqsio** [comment]
Hi @Aleksion 
This is a metro error, you need to define correct metro settings:
https://facebook.github.io/metro/docs/configuration/

`paths` in tsconfig.json only fixes TS validation, but the file will still fail to resolve until you add `resolveRequest` or other config for lookups in `metro.config.js`

**Comment by Aleksion** [comment]
@aleqsio shouldn't this be a part of the documentation then?

**Comment by Guilherme-j10** [comment]
I agree, I wasted hours figuring out how to solve this shitty problem that could be solved simply if they let you know somewhere in the documentation

**Comment by Guilherme-j10** [comment]
I know that the problem has already been closed, but in order to help other people who may the same problem, I'll leave below what worked for me.

Basically I had to add a babel plugin (babel-plugin-module-resolver) https://www.npmjs.com/package/babel-plugin-module-resolver and in my babel.config.js it looked like this:

```js
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      ["module-resolver"]
    ]
  };
};

```

**Comment by aleqsio** [comment]
Agreed, I'd love to see this in the docs, but probably more as a guide – It's not really a documented/supported out of the box feature.

**Comment by aleqsio** [comment]
Ok, after looking into this a bit more, it seems that the latest version of the package is still not yet released, so the docs went out a bit early 😅 
https://github.com/expo/expo/pull/21262

Apologies for that

**Comment by Guilherme-j10** [comment]
I confess that it was a rather annoying problem to solve but in a way it was interesting to have gone through it, I don't know if all the people who are downloading the package to use it are going through this problem and I am happy that the resolution and the cause are documented here, but anyway is there a deadline for release?

**Comment by hyoretsu** [comment]
Commenting to get pinged when Expo's updated.

**Comment by aleqsio** [comment]
@brentvatne maybe we want to republish CLI?

**Comment by Guilherme-j10** [comment]
this approach is working correctly now https://docs.expo.dev/guides/typescript/#absolute-imports

**Comment by iSplasher** [comment]
@Guilherme-j10 I don't think it does?
I'm using latest expo 48.0.9 and it gives the same error.
The docs seem to refer to SDK 49, but that hasn't been released yet?

**Comment by augustobritodev** [comment]
im getting the same error here, using 48.0.9 
![image](https://user-images.githubusercontent.com/7965922/227809290-465c9f2c-37cf-4f2f-ab8d-88d2e589c48b.png)

**Comment by aleqsio** [comment]
I think that absoluteImports might work, but path aliases will be released in SKD49 coming around May 😅

**Comment by EvanBacon** [comment]
The feature has a surprisingly large and complex scope (requires native changes, bundler changes, and a new CLI command). Otherwise we’d release it now.

As documented, it will be available in SDK 49 behind an experimental flag. If it works well, we may enable it by default mid-cycle (49 ½).

**Comment by AbdullahFoqha** [comment]
Any updates about when could we get the SKD49, I really wanted to play with the path aliases

**Comment by CoreyCole** [comment]
To get it to work on SDK49 you need to add to app config:
```json
module.exports = {
    "expo": {
        "experiments": {
            "tsconfigPaths": true,
        },
    },
},
```
FWIW With App.tsx in the repo root, I needed to have `"baseUrl": "."`, but then I needed to include "src" in the beginning of all imports.
```
import Logo from "src/components/logo";
``` 
To use `"baseUrl": "src",` in my tsconfig.json I had to move my App.tsx to the src folder. After that the imports worked:
```
import Logo from "components/logo";
```

**Comment by JorensM** [comment]
I'm having this issue as well. TS linter doesn't complain, but I get an `cannot find module` error when running the app. I tried restarting the expo server but that didn't work

**Comment by GuidoGagliardini** [comment]
> Oh wait, my initial advice is actually incorrect – the suggested comment is the traditional way of setting up aliases, but it sounds like there's indeed a bug with the steps described here: https://docs.expo.dev/guides/typescript/#path-aliases Sorry for that, let me take another look

This documentation has the indicated answer. In my case I was missing to add the configuration in app.json(expo >= 49)
Thanks for your time and help.

**Comment by timurcatakli** [comment]
In my case there was a typo in `app.json`.

It was `"tsConfigPaths": true` instead of ` "tsconfigPaths": true`
So here is the correct version:
```
    "experiments": {
      "typedRoutes": true,
      "tsconfigPaths": true
    }
```

**Comment by jayporta** [comment]
None of this works for me on Expo 49.0.15

I created a new project using the typescript flag `npx create-expo-app -t expo-template-blank-typescript`

Here's my tsconfig:

```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "baseUrl": "."
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    ".expo/types/**/*.ts",
    "expo-env.d.ts"
  ]
}
```

And my app.config.ts:

```
import { ExpoConfig, ConfigContext } from 'expo/config'

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'my-project',
  slug: 'my-project',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  userInterfaceStyle: 'automatic',
  splash: {
    image: './assets/splash.png',
    resizeMode: 'contain',
    backgroundColor: '#ffffff',
  },
  assetBundlePatterns: ['**/*'],
  ios: {
    supportsTablet: true,
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#ffffff',
    },
  },
  web: {
    favicon: './assets/favicon.png',
  },
  experiments: {
    tsconfigPaths: true,
  },
})
```

Everything resolves fine in VS Code but when I run the app I get errors like this:

```
Module not found: Can't resolve 'components/Temp'
Did you mean './components/Temp'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
```

However, if I start a project using Expo Router v2 to try file based routing, it works but I can't set up firebase auth (that's why I'm not using it). I tried to copy over settings from the working project but it just doesn't work.

**Comment by huanghanzhilian** [comment]
> Hi @Aleksion This is a metro error, you need to define correct metro settings: https://facebook.github.io/metro/docs/configuration/
> 
> `paths` in tsconfig.json only fixes TS validation, but the file will still fail to resolve until you add `resolveRequest` or other config for lookups in `metro.config.js`

Very useful, thanks for all the answers, solved the problem in my open source project

nextjs full stack: https://github.com/huanghanzhilian/c-shopping

react native (expo) app: https://github.com/huanghanzhilian/c-shopping-rn

**Comment by KirschX** [comment]
For my case, I mistakenly put some file in .expo, at it made all 'unresolved ~' error at production build.
