### ISSUE TITLE
No podspec found for `EXBarCodeScanner` in `../node_modules/expo-barcode-scanner/ios`

### ISSUE THREAD

**Issue by rockmandash** [expo/expo#2148]
Hello, I use a completely fresh expo detached project, using pod install in ios directory.
And it showed me
```
No podspec found for `EXBarCodeScanner` in `../node_modules/expo-barcode-scanner/ios`
```
How can I solve the issue?
Thank you

**Comment by sjchmiela** [comment]
Hi @rockmandash!

Sorry for the trouble, you can just remove all the erroring pods from the `Podfile`. ATM these are: `EXFont, EXPrint, EXSegment, EXMediaLibrary, EXFontInterface, EXImageLoaderInterface, EXBarCodeScannerInterface, EXBarCodeScanner`.

**Comment by sjchmiela** [comment]
That's strange, I've just detached a clean Expo project, commented out offending pods and the installation succeeded. [My Podfile after changes](https://gist.github.com/sjchmiela/cfc4fbd7c426ec4c2e333775f690f314)

**Comment by chobann** [comment]
Thanks for your time. It was my fault. I was using CocoaPods version `1.6.0.beta.1`.
After downgrading to `1.5.3` everything works fine.

**Comment by sjchmiela** [comment]
Good news! Closing the issue. 🙂
