### ISSUE TITLE
React Native Reanimated Version 3

### ISSUE THREAD

**Issue by ponikar** [expo/expo#21483]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by ponikar** [comment]
I tried to install react-native-reanimated version 3 but the App was crashing on runtime and the error was not clear either. 

`Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.`
        
The app started working after I installed the library.

**Comment by brentvatne** [comment]
reanimated v3 will not work in expo go until we add support for it in a future sdk release. it will, however, work fine in development builds

**Comment by kmartinezmedia** [comment]
@brentvatne when you say "development builds" are you referring to expo dev client builds?

**Comment by ponikar** [comment]
Yes. 

Just run `expo prebuild` and it will work.

**Comment by janbaykara** [comment]
Hi @brentvatne, is adding reanimated v3 support for the SDK on the roadmap, and do you have a 'no earlier than' date just for our situational awareness?

**Comment by bj97301** [comment]
> reanimated v3 will not work in expo go until we add support for it in a future sdk release. it will, however, work fine in development builds

I have a dev build and am getting this error:
`expected type number got hostobject`

**Comment by ponikar** [comment]
I want to know how do you integrate all the packages so they work in the expo go app. Do you have any documentation for that? I would love to hack around with that. @brentvatne

**Comment by bj97301** [comment]
> > reanimated v3 will not work in expo go until we add support for it in a future sdk release. it will, however, work fine in development builds
> 
> 
> 
> I have a dev build and am getting this error:
> 
> `expected type number got hostobject`

Mine was related to v2. I installed v3. Getting a different error now. 
![image](https://github.com/expo/expo/assets/1450431/92ea202b-7a2b-4e00-a539-7b5880deb5f7)

**Comment by bj97301** [comment]
Seems like expo doesnt support v3.  
<img width="1728" alt="reanimated warning" src="https://github.com/expo/expo/assets/1450431/e9c3bb99-a51c-4011-84a9-1d49ffd5449c">


Any idea when this will be supported?

**Comment by ikapo** [comment]
Seems like the latest version supports v3
