### ISSUE TITLE
TextInput outside tap not bluring

### ISSUE THREAD

**Issue by alexvcasillas** [expo/expo#2149]
### Environment

Environment:  OS: macOS High Sierra 10.13.6
  Node: 10.7.0
  Yarn: 1.7.0
  npm: 6.4.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: github:expo/react-native#sdk-29.0.0 => 0.55.4

### Steps to Reproduce

Just install a fresh new project with Exp CLI using exp init then following the steps for a blank project. Import TextInput from React Native, type inside, and then try to tap outside, it won't blur nor dismiss the keyboard.

### Expected Behavior

TextInput blur and keyboard dismissing.

### Actual Behavior

TextInput not bluring.

### Reproducible Demo

Snack: [https://snack.expo.io/H1SbyCMvm](https://snack.expo.io/H1SbyCMvm)

**Comment by FiberJW** [comment]
You can use https://facebook.github.io/react-native/docs/scrollview#keyboarddismissmode or https://facebook.github.io/react-native/docs/keyboard#dismiss to achieve your desired result.  By default, the React Native text input element doesn't dismiss when tapping outside of it. Here's your Snack modified to dismiss when the screen is tapped outside of the text input, tested on SDK 35 with an iPhone 8: https://snack.expo.io/@datwheat/curious-bagel.

This seems to be resolved, so I’ll close this for now. If you need further support, please make a topic on our [forums](https://forums.expo.io) :)
