### ISSUE TITLE
[SDK48][expo-dev-client] Custom expo-dev-client not persisting login & missing project info

### ISSUE THREAD

**Issue by zigcccc** [expo/expo#21498]
### Minimal reproducible example

Custom dev clients are not supported on Snacks (AFAIK). But you should be able to reproduce this just by upgrading to SDK48, creating a custom dev client, and inspecting what I've described in the Summary

### Summary

After upgrading to SDK48 & creating a custom dev client, I noticed a few things that are strange.

1. No project name/icon
![image](https://user-images.githubusercontent.com/14889659/222670248-760ccaaa-dc8c-4df5-a0a1-9b1f44212332.png)

2. No version/runtimeVersion info
![image](https://user-images.githubusercontent.com/14889659/222670355-2430e56d-a95b-4193-8698-1dcfa1cc228a.png)

3. I keep getting logged out of my Expo account
  a. I can log in to my Expo account ✅ 
  b. In the "Extensions" tab, I can see the list of my updates & open a project/update ✅ 
  c. the moment I return back to the (Expo's) Home screen, I am logged out of the account & have to re-authenticate 🔴 

Number 1. and 2. are not a big deal IMO. Number 3 is annoying since I have to re-login non-stop. Nothing is *really* a blocker for pushing stuff to production, but it does slow down the dev/QA process quite a bit.

Relevant discord thread: https://discord.com/channels/695411232856997968/1080843002890698802

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.2.2 => 9.3.0 
      expo: ^48.0.4 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.7.2
    Expo Workflow: managed

```

**Comment by gabrieldonadel** [comment]
Hi @zigcccc, have you tried upgrading your `expo-dev-client` version to `2.1.4`? This should be fixed by https://github.com/expo/expo/pull/21425

**Comment by zigcccc** [comment]
> Hi @zigcccc, have you tried upgrading your `expo-dev-client` version to `2.1.4`? This should be fixed by #21425

Hey @gabrieldonadel it looks like I am using version 2.1.4, yep 👇 
```
npm why expo-dev-client
expo-dev-client@2.1.4
node_modules/expo-dev-client
  expo-dev-client@"~2.1.4" from the root project
```
<img width="236" alt="image" src="https://user-images.githubusercontent.com/14889659/222723311-8e7b2a66-8803-4045-8b0c-506cdcbfbf59.png">

**Comment by gabrieldonadel** [comment]
Hi @zigcccc a new version of `expo-dev-client` fixing this issue has just been released 
 
| 📦 Package | 🔢 Version | ↖️ Pull requests | 📝 Release notes |
|:--:|:--:|:--:|:--:| 
| [expo-dev-client](https://www.npmjs.com/package/expo-dev-client/v/2.1.5) | 2.1.5 | #21510 | [CHANGELOG.md](https://github.com/expo/expo/blob/sdk-48/packages/expo-dev-client/CHANGELOG.md) |

We kindly ask you for some feedback—even if it works 🙏
Happy Coding! 🎉

**Comment by zigcccc** [comment]
@gabrieldonadel I can confirm that with `expo-dev-client@2.1.5` everything is working perfectly!
- project name is displayed correctly ✅ 
- versions are displayed correctly ✅ 
- login is persisted ✅ 

Appreciate the quick fix & turn around! ❤️
