### ISSUE TITLE
[expo-local-authentication][iOS] LocalAuthentication.authenticateAsync doesn't work after upgrading from 13.0.2 to 13.2.1

### ISSUE THREAD

**Issue by lexer** [expo/expo#21496]
### Minimal reproducible example

https://github.com/expo/expo/blob/sdk-48/packages/expo-local-authentication/CHANGELOG.md#1310--2022-12-30

### Summary

LocalAuthentication.authenticateAsync doesn't work after upgrading from 13.0.2 to 13.2.1

I suspect is caused by Swift migration PR. https://github.com/expo/expo/pull/19980

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - /opt/homebrew/bin/npm
      Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Patch 1 Chipmunk 2021.2.1 Patch 1
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: bare

**Comment by a-leblond** [comment]
Hi ! Is it possible to publish the fix ? The issue is still present
