### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by deivijt** [expo/expo#215]
How do I select multiple images from the phone’s photo library with expo?

**Comment by terribleben** [comment]
Hi, I don't think we support this right now because we just use the default iOS image picker UI. Can you add a feature request [here](https://expo.canny.io/feature-requests)?

**Comment by jhalborg** [comment]
I created one [here](https://expo.canny.io/feature-requests/p/allow-choosing-multiple-images-in-imagepicker)
