### ISSUE TITLE
[Android] reanimated does not work after upgrading to expo 48

### ISSUE THREAD

**Issue by m-sirajuddin-bm** [expo/expo#21505]
### Minimal reproducible example

https://github.com/HadiModarres/my-app/blob/main/App.js

### Summary

Recently we upgrading the expo to 48, prior to that reanimated 2 was working well, but after the upgrade it does not seems to be working. Today, I reverted to 47 and tried, it seems to be working.

Please refer other issue reported on this:

https://github.com/software-mansion/react-native-reanimated/issues/4112

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
Yarn: 1.22.19 - ~/Projects/consumer-mobile-app/node_modules/.bin/yarn
npm: 9.2.0 - ~/.nvm/versions/node/v16.18.0/bin/npm
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
Android SDK:
API Levels: 28, 29, 30, 33, 33
Build Tools: 28.0.3, 30.0.3, 33.0.0, 33.0.1, 33.0.2
System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9619390
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
npmPackages:
@expo/webpack-config: ^18.0.1 => 18.0.1
expo: ^48.0.5 => 48.0.5
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.71.3 => 0.71.3
react-native-web: ~0.18.11 => 0.18.12
Expo Workflow: bare

**Comment by jp928** [comment]
Same here.

**Comment by abponcio** [comment]
same here. We ended up downgrading to sdk 47 and wait until 48 is stable. It also caused some of our 3rd party native modules integrations break as well like our expo-intercom plugin

**Comment by Kudo** [comment]
confirmed this as an issue in expo go. i'll follow up to have a fix. in the meantime, please try to use a [development build](https://docs.expo.dev/development/introduction/) if that's emergent upgrade.

**Comment by RdC1965** [comment]
Same problem here

**Comment by Kudo** [comment]
@RdC1965 do you use expo go? if so, what's the expo go version you tried?

**Comment by RdC1965** [comment]
> @RdC1965 do you use expo go? if so, what's the expo go version you tried?

Yes, I use Expo Go version 2.28.5.

**Comment by OreAkintobi** [comment]
Hi, I am upgrading an app from Expo 47 to Expo 48. The App uses expo-dev-client as we have some native dependencies. Unfortunately, I cannot run or build the app outside of my native environment using EAS whenever I update reanimated to expo's recommended version for Expo 48 (Reanimated 2.14.0). I also cannot move forward with the previous recommended version for Expo 47 (Reanimated 2.12.0) because it does not build successfully on android due to a `minor` naming issue.

Please has anyone come up with a fix for this issue? I will have to stay on Expo 47 for time being, but not ideal.

**Comment by awesomedan93** [comment]
still the same...
Any workaround ?

**Comment by OreAkintobi** [comment]
@awesomedan93 maybe better off upgrading to Expo 49, and seeing if the reanimated version it's compatible with (~3.3.0) will solve the issue. I've been fiddling with this to test out the new Expo-Router setup and app seems to work fine (haven't ejected yet or started using dev-client yet). Also, they will be sunsetting Expo 48 when Expo 50 comes around (which won't be too long), so might want to just bite the bullet and upgrade to 49

**Comment by awesomedan93** [comment]
@OreAkintobi yes already upgraded to 49 and all working
Thanks

**Comment by ewein** [comment]
I'm still having issues with my react-navigation Drawer not working on Android with Expo 49 and reanimated 3.3.0. Seems to primarily be an issue with Android 14. Any workarounds?
