### ISSUE TITLE
ClipboardEvent is deprecated, but how to track changes in clipboard in Clipboard.addClipboardListener()

### ISSUE THREAD

**Issue by g1mbatov** [expo/expo#21501]
### Summary

In earlier versions of the SDK it was possible to track changes in the clipboard, but in SDK 45 and higher, ClipboardEvent does not work on Android 6

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/clipboard/

**Comment by amandeepmittal** [comment]
Did you see check the docs for [`getStringAsync()`](https://docs.expo.dev/versions/latest/sdk/clipboard/#getstringasyncoptions) which the `ClipboardEvent` points to?

<img width="885" alt="CleanShot 2023-03-04 at 17 18 07@2x" src="https://user-images.githubusercontent.com/10234615/222916974-40419df8-3d0d-47e0-84d6-3c974b6beb72.png">

**Comment by g1mbatov** [comment]
> 

Yes it works for android 10 but doesn't work for android 6

**Comment by thoth-seshat** [comment]
I can't get the event listener to trigger at all
