### ISSUE TITLE
Expo 48, expo-dev-client, eas build android failure

### ISSUE THREAD

**Issue by psquizzle** [expo/expo#21516]
### Summary

Creating a fresh Expo App installing dev-client and then building for Android fail with the new Expo 48 SDK. Both on my local machine and via expo build services. I made no changes to the project simply prebuild and eas build after installing dev-client.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
"name": "expo48",
"version": "1.0.0",
"scripts": {
"start": "expo start --dev-client",
"android": "expo run:android",
"ios": "expo run:ios",
"web": "expo start --web"
},
"dependencies": {
"expo": "~48.0.5",
"expo-dev-client": "~2.1.4",
"expo-splash-screen": "~0.18.1",
"expo-status-bar": "~1.4.4",
"react": "18.2.0",
"react-native": "0.71.3"
},
"devDependencies": {
"@babel/core": "^7.20.0"
},
"private": true
}

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.15.1 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 8.11.0 - /usr/local/bin/npm
Managers:
CocoaPods: 1.11.0 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
IDEs:
Android Studio: 2021.2 AI-212.5712.43.2112.8609683
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
npmPackages:
expo: ~48.0.5 => 48.0.5
react: 18.2.0 => 18.2.0
react-native: 0.71.3 => 0.71.3
npmGlobalPackages:
eas-cli: 3.7.2
expo-cli: 6.2.1
Expo Workflow: bare

### Reproducible demo

"You can reproduce it by yourself by creating a project and following these steps"

Step 1. npx create-expo-app example
Step 2. npx expo install expo-dev-client
(and environment if not already done)
Step 3.  expo prebuild --clean
Step 4. run:
eas build --local --profile development
or
eas build --profile development

And then the build fails to build, both locally and on expo servers

App.js
```

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

### Stacktrace (if a crash is involved)

[RUN_GRADLEW] > Task :app:compileDebugJavaWithJavac FAILED
[RUN_GRADLEW] /private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/9291b655-6711-4c98-bac3-6f438f0d13ca/build/android/app/src/main/java/com/psquizzle/expo48/MainApplication.java:26: error: cannot find symbol
[RUN_GRADLEW] return BuildConfig.DEBUG;
[RUN_GRADLEW] ^
[RUN_GRADLEW] symbol: variable BuildConfig
[RUN_GRADLEW] /private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/9291b655-6711-4c98-bac3-6f438f0d13ca/build/android/app/src/main/java/com/psquizzle/expo48/MainApplication.java:45: error: cannot find symbol
[RUN_GRADLEW] return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
[RUN_GRADLEW] ^
[RUN_GRADLEW] symbol: variable BuildConfig
[RUN_GRADLEW] /private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/9291b655-6711-4c98-bac3-6f438f0d13ca/build/android/app/src/main/java/com/psquizzle/expo48/MainApplication.java:50: error: cannot find symbol
[RUN_GRADLEW] return BuildConfig.IS_HERMES_ENABLED;
[RUN_GRADLEW] ^
[RUN_GRADLEW] symbol: variable BuildConfig
[RUN_GRADLEW] /private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/9291b655-6711-4c98-bac3-6f438f0d13ca/build/android/app/src/main/java/com/psquizzle/expo48/MainApplication.java:63: error: cannot find symbol
[RUN_GRADLEW] if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
[RUN_GRADLEW] ^
[RUN_GRADLEW] symbol: variable BuildConfig
[RUN_GRADLEW] location: class MainApplication
[RUN_GRADLEW] /private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/9291b655-6711-4c98-bac3-6f438f0d13ca/build/android/app/src/main/java/com/psquizzle/expo48/MainApplication.java:63: error: illegal parenthesized expression
[RUN_GRADLEW] if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
[RUN_GRADLEW] ^
[RUN_GRADLEW] /private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/9291b655-6711-4c98-bac3-6f438f0d13ca/build/android/app/src/main/java/com/psquizzle/expo48/MainActivity.java:19: error: package R does not exist
[RUN_GRADLEW] setTheme(R.style.AppTheme);
[RUN_GRADLEW] ^
[RUN_GRADLEW] /private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/9291b655-6711-4c98-bac3-6f438f0d13ca/build/android/app/src/main/java/com/psquizzle/expo48/MainActivity.java:39: error: cannot find symbol
[RUN_GRADLEW] return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
[RUN_GRADLEW] ^
[RUN_GRADLEW] symbol: variable BuildConfig
[RUN_GRADLEW] location: class MainActivity
[RUN_GRADLEW] 7 errors
[RUN_GRADLEW] > Task :app:mergeDebugJavaResource
[RUN_GRADLEW] w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:compileDebugJavaWithJavac'.
[RUN_GRADLEW] > Compilation failed; see the compiler error output for details.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] java.lang.StackOverflowError (no error message)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org/
[RUN_GRADLEW] BUILD FAILED in 3m 43s

**Comment by jp928** [comment]
Same here

**Comment by thespacemanatee** [comment]
Same here, issue shouldn't be closed

**Comment by psquizzle** [comment]
My problem was with the version of expo-dev-client at the time someone forgot to link some code, was fixed a few hours later

**Comment by JookGruls** [comment]
same here
