### ISSUE TITLE
[expo-image] tintColor not working

### ISSUE THREAD

**Issue by dreson4** [expo/expo#21530]
### Minimal reproducible example

https://github.com/dreson4/test-app

### Summary

tintColor doesn't seem to work on any image. 
I tried using the native Image from react-native tintColor works just fine on all png files I used, nothing works using expo-image.

```
<Image
        source={require("./assets/randomtest.png")}
        tintColor="#341f97"
        style={{width:200,height:200}}
      />

```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: Electric Eel 2022.1.1 Patch 1 Electric Eel 2022.1.1 Patch 1
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.5 => 48.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      expo-cli: 6.1.0
    Expo Workflow: managed
```

**Comment by Kudo** [comment]
confirmed this as an issue where expo-image only accept the `tintColor` from style props but not normal props.
i.e.
`<Image style={{ tintColor: "#341f97" }} />` works. and `<Image tintColor="#341f97" />` does not work.

**Comment by dancamdev** [comment]
Why is the updated version 1.1.0? current one is 1.3.2 (should this one be 1.3.3) - also, is there a way to force-install it in expo? if not, when is the next SDK release?

**Comment by moxorama** [comment]
Android implementation still broken
