### ISSUE TITLE
Error: Unable to resolve module ./node_modules/expo/AppEntry from /Users/../.: 

### ISSUE THREAD

**Issue by Arnav7501** [expo/expo#21532]
### Minimal reproducible example

https://github.com/Arnav7501/Fail.git, https://drive.google.com/file/d/1hNhDQvk9SYiUbf08Mm4NtUTBhUdcVlhh/view?usp=sharing

### Summary

I cannot code in react native anymore. All my existing apps have this issue, and any new expo apps i attempt to create also have this issue. I simply cannot find a solution to this. Any help would really be appreciated.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      npm: 8.15.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1 
      expo: ~48.0.5 => 48.0.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by Kudo** [comment]
not sure whether `watchman watch-del-all` works for you?

**Comment by Arnav7501** [comment]
Nevermind, after a long debug session I have realized that my metro-config.js file is missing. Once I add it, the error goes away. I don't know why it doesn't automatically add it, but its a workaround for now.

**Comment by jdthorpe** [comment]
I got this error when trying to install dependencies using Microsoft's Rush.js monorepo manager.  Something about how it flattens the node_modules folder makes the `node_modules/expo/` directory unavailable  to metro.  I had to disable rush.js from managing my expo project and re-install the dependencies using `yarn` and after that this error went away.

**Comment by SufianBabri** [comment]
@jdthorpe I was facing this with pnpm. Someone on the issues mentioned that it is due to pnpm using symlinks. So it was suggested that symlinks should be disabled for the app to launch.

I too switched to yarn as it was much easier. Not sure why Expo is suggesting pnpm in their tutorial if it doesn't work out-of-the-box.
