### ISSUE TITLE
[Camera] Can’t start recording video on android

### ISSUE THREAD

**Issue by oleh-mryhlod** [expo/expo#2154]
### Environment

Platform: Android
Expo SDK: 29

### Steps to Reproduce

Start to record video using Expo.Camera.recordAsync with specified 'quality' option
```
this.caremaRef.recordAsync({
  quality: Camera.Constants.VideoQuality['720p'],
});
```

### Expected Behavior

Successfully started recording video with specified quality.

### Actual Behavior

Can't start recording and got an error message:
`java.lang.Double cannot be cast to java.lang.Integer`

### Reproducible Demo

Snack: https://snack.expo.io/@oleh-mryhlod/record-video-with-quality-param

**Comment by sjchmiela** [comment]
Hey guys! This issue should have been fixed in https://github.com/expo/expo/commit/e2e4de4363c3d4007f4fd2232eb67626b21aa2bf#diff-cc5107f97abcdb3f115accb5e74bba43. This commit should have landed in SDK 30. Does it occur there?

**Comment by sangbpark94** [comment]
I will have to check! I've been using expo 29.0.1.
