### ISSUE TITLE
[expo-image] svg image fill property not working

### ISSUE THREAD

**Issue by singh-jay** [expo/expo#21547]
### Minimal reproducible example

https://github.com/singh-jay/expo-48

### Summary

I tried to render svg image using expo-image.
it's working fine but when tried to pass fill property using the prop or css style it's not working.

import { Image } from "expo-image";
import SearchIcon from "./assets/search.svg";
<Image source={SearchIcon} width={20} height={20} fill={"red"} style={styles.icon} />

const styles = StyleSheet.create({
	icon: {
		width: 40,
		height: 40,
		fill: "black",
	},
});

Any idea how can we use fill in svg images

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    npmPackages:
      expo: ~48.0.5 => 48.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.7.2
    Expo Workflow: managed

**Comment by lukmccall** [comment]
Hi @singh-jay, is this issue affects Android or iOS?

**Comment by lukmccall** [comment]
I think you can replace `fill` with the `backgroundColor` and it should work as intended in your case. Also, `backgroundColor`, `width`, and `height` should be passed using CSS styles. 

We aren't supporting the `fill` prop.

**Comment by singh-jay** [comment]
Thanks for the reply.

changed the code accordingly - 
<Image
  source={SearchIcon}
  style={{
	  width: 60,
	  height: 60,
	  backgroundColor: "gray",
  }}
/>

now using css backgroundColor - it's making the complete background gray. Is there any way so that only the content of svg should be gray?
![Screenshot_20230315_224735_Expo Go](https://user-images.githubusercontent.com/36124459/225389618-4880918b-207b-4b55-b279-1f7c8bb3d3c7.jpg)

**Comment by imPatSpence** [comment]
Bumping this as im currently having the same issue.  Is there a way to change an SVGs color via styles?  Typically this would be done using the color style.

Thanks

**Comment by singh-jay** [comment]
Hey @lukmccall, Thanks for this excellent package. Can we add this to the future plan? It will be much more helpful for dark and light theme-based svg image filling. This is the only missing feature preventing me from migrating from react-native-svg-transformer.

**Comment by MoOx** [comment]
New to expo (but not RN) I would have expected option so we can fill SVG used as icon.
I made this package to turn SVG as React components (that accepts props) a while, I guess I will use this again https://www.npmjs.com/package/react-from-svg :D
