### ISSUE TITLE
Unable to use Camera via ImagePicker through Expo Go on Android

### ISSUE THREAD

**Issue by chris-nolan** [expo/expo#21544]
### Minimal reproducible example

https://github.com/chris-nolan/tunnel-app

### Summary

ImagePicker should load the native camera UI and allow a picture to be taken. This works fine when doing a development build, however when running through Expo Go the following error occurs:

`
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission, parameter permission
Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission, parameter permission
    at construct (native)
    at apply (native)
    at _construct (http://192.168.68.81:19000/index.ts.bundle?platform=android&dev=true&hot=false:3251:28)
    at Wrapper (http://192.168.68.81:19000/index.ts.bundle?platform=android&dev=true&hot=false:3213:25)
    at construct (native)
    at _createSuperInternal (http://192.168.68.81:19000/index.ts.bundle?platform=android&dev=true&hot=false:112723:322)
    at call (native)
    at CodedError (http://192.168.68.81:19000/index.ts.bundle?platform=android&dev=true&hot=false:112731:26)
`

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.0 - ~\AppData\Local\Volta\tools\image\node\16.13.0\node.EXE
      Yarn: 1.22.17 - ~\AppData\Local\Volta\tools\image\yarn\1.22.17\bin\yarn.CMD
      npm: 8.1.4 - ~\AppData\Local\Volta\tools\image\npm\8.1.4\bin\npm.CMD
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1
      expo: ~48.0.5 => 48.0.5
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

**Comment by chris-nolan** [comment]
Have just tried this same project on iOS through Expo Go and it works as expected

**Comment by israelZZ** [comment]
i got the same error after upgrade to expo sdk 47, then iv downgrade it back and still got the error

**Comment by JayHenry07** [comment]
Getting the same error.
`ExponentImagePicker.launchImageLibraryAsync` works as expected, however.

**Comment by ottobonn** [comment]
I am also getting this error as of the most recent Expo Go update. Nothing about my app changed and I have tried clearing cache, reinstalling, etc. I also tried updating my app to use SDK48 but that hasn't fixed it.

**Comment by matt-fackler** [comment]
I am getting this same error.  And like others have said, access to the camera is still fine but when trying to access the camera I get this:

> [Unhandled promise rejection: Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.]
at node_modules\@babel\runtime\helpers\construct.js:null in _construct
at node_modules\@babel\runtime\helpers\wrapNativeSuper.js:null in Wrapper
at http://192.168.1.11:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in _createSuperInternal
at node_modules\expo-modules-core\build\errors\CodedError.js:null in constructor


Not sure what the problem is.

**Comment by kasperscottjensen** [comment]
Same error as above. Anyone found a solution yet ?

**Comment by gabrieldonadel** [comment]
@chris-nolan, are you testing this in an emulator? Which version of expo-go are you using?

**Comment by chris-nolan** [comment]
Expo go version is 2.28.4 on a Pixel 6, running Android 13, all up to date.

Will need to double check behaviour in emulator when back at work in the morning (UK time).

**Comment by chris-nolan** [comment]
@gabrieldonadel so Expo Go 2.28.4 on emulator is working as expected. A fresh install of Expo Go on my Pixel however, is still returning the same thing and failing. Very odd.

I've requested some additional devices from our IT department to test on - but its looking like this might be a device specific thing.

**Comment by kacperklusek** [comment]
What worked for me was following these steps:
- downgrade expo from v48.0.5 to v47 with `expo upgrade 47`
- remove all node_modules from the project and `npm install` them again
- reinstall Expo Go by first uninstalling it manually from the emulator, then execute `npm start` to install Expo Go automatically

**Comment by gabrieldonadel** [comment]
Which device/android version are you experiencing this on @matt-fackler?

**Comment by matt-fackler** [comment]
I am on Android version 13 on a Samsung Galaxy A52 5g

**Comment by chris-nolan** [comment]
Apologies for radio silence. I've acquired a Galaxy S22 which seems to work fine, but I have moved off of the managed workflow since my original issue occurred. I will try my sample code above this week.  The S22 was fresh out of the wrapper so maybe a issue with devices that have had more usage/apps installed etc?

**Comment by laurentayming** [comment]
We have the same issue on Android 13. 
With the sdk 47 everything works perfectly but not in 48.
Waiting to be resolved.

**Comment by laurent-gonzalez** [comment]
After research we discovered that the problem was present only on the Expo Go Android application. Once the android application is built (apk), the process works perfectly. On ios, everything works as expected

**Comment by benkaiser** [comment]
Thanks @gabrieldonadel !

**Comment by matt-fackler** [comment]
This fix did not seem to work for me.  I reinstalled expo with npm and expo-image-picker with npm and still the same error.  Am I supposed to do something else to correct this error now that it's be patched?

**Comment by gabrieldonadel** [comment]
> This fix did not seem to work for me.  I reinstalled expo with npm and expo-image-picker with npm and still the same error.  Am I supposed to do something else to correct this error now that it's been patched?

The new version of Expo Go has not been released yet, in the meanwhile you can use dev client

**Comment by marcelino-borges** [comment]
Jesus Christ, I have updated expo sdk from 47 to 48 to fix an issue and now I have this issue.

Both `ImagePicker.getCameraPermissionsAsync` and `ImagePicker.requestCameraPermissionsAsync` return 
```json 
{"canAskAgain": true, "expires": "never", "granted": true, "status": "granted"}
```

But when I call `ImagePicker.launchCameraAsync`, I get this:
```
Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission, parameter permission
```

My libs:
```json
{
   "expo": "^48.0.11",
   "expo-image-picker": "~14.1.1",
   "react-native": "0.71.6",
   "react": "18.2.0",
}
```

I don't really know what to do right now, suggestions??

**Comment by YemanjaG** [comment]
I'm having the exact same problem as @marcelino-borges.
The camera launch works perfectly on android emulator / iOS physical device. But for some reason and android physical device I get this error, any help would be greatly appreciated.

**Comment by sanak** [comment]
Hi @gabrieldonadel,
> > This fix did not seem to work for me.  I reinstalled expo with npm and expo-image-picker with npm and still the same error.  Am I supposed to do something else to correct this error now that it's been patched?
> 
> The new version of Expo Go has not been released yet, in the meanwhile you can use dev client

I noticed that new Expo Go version (2.28.8 in GooglePlay) is released last week (4/25), but this issue is still happen and I guess that the cause is that the commit (https://github.com/expo/expo/commit/39684085747fe310d912b08767a3278ddd9e1dcd) doesn't exist in `sdk48` branch's commits history (https://github.com/expo/expo/commits/sdk-48).

This issue started to happen since SDK48 in Android Expo Go, so I hope that the fix will be included in next Expo Go release's SDK48 module. :pray:

**Comment by MarkiyanPyts** [comment]
Facing the Same Issue, works only on IOS and fails on Android emulator

**Comment by SimonCorellia** [comment]
> Hi @gabrieldonadel,
> 
> > > This fix did not seem to work for me.  I reinstalled expo with npm and expo-image-picker with npm and still the same error.  Am I supposed to do something else to correct this error now that it's been patched?
> > 
> > 
> > The new version of Expo Go has not been released yet, in the meanwhile you can use dev client
> 
> I noticed that new Expo Go version (2.28.8 in GooglePlay) is released last week (4/25), but this issue is still happen and I guess that the cause is that the commit ([3968408](https://github.com/expo/expo/commit/39684085747fe310d912b08767a3278ddd9e1dcd)) doesn't exist in `sdk-48` branch's commits history (https://github.com/expo/expo/commits/sdk-48).
> 
> This issue started to happen since SDK48 in Android Expo Go, so I hope that the fix will be included in next Expo Go release's SDK48 module. 🙏

Do we have an idea of when the next release will take place ? 

I have the same issue and I need to deploy my app ASAP without downgrading the version

**Comment by mirco123** [comment]
the same problem here. Thanks for releasing a bugfix as soon as possible

**Comment by dillwb** [comment]
Having the same issue as everybody else. launchImageLibraryAsync works fine but launchCameraAsync does not on my physical android device running ExpoGo

**Comment by zampage** [comment]
Facing the same issue on a Samsung Galaxy S21 5G with Android 13 using these libs:

```
"expo": "^48.0.16",
"expo-image-picker": "~14.1.1",
"react": "18.2.0",
"react-native": "0.71.8",
```

**Comment by mohamadfala** [comment]
Same issue here:
```
"expo": "^48.0.16",
"expo-image-picker": "~14.1.1",
"react": "18.2.0",
"react-native": "0.71.8",
```

**Comment by pabrcno** [comment]
Same problem here needing to test this functionality.
"expo": "^48.0.6",
    "expo-auth-session": "^4.0.3",
    "expo-camera": "~13.2.1",
    "expo-image-picker": "~14.1.1",
     "react-native": "0.70.5",

**Comment by jackdw22** [comment]
fix it please

**Comment by thegirlyoucallryan** [comment]
Is it just me this is still happening for?  Their commit didn't change anything for me.

**Comment by brugaspar** [comment]
Same issue here! Hoping they fix it soon

**Comment by zampage** [comment]
I've seen the commit of @brentvatne being merged into the `sdk-48` branch and #21912 being closed.
So I've updated to:

```
"expo": "^48.0.19"
```

But the Problem still persists. Is it the app that needs an update? If so, when are you going to release one?

I'm on Expo Go: 2.28.8 without the app store showing me an update.

**Comment by PatoGordo** [comment]
It seems that this issue only occurs with devices that already have Expo Go installed. I tried to run the app in another device and it worked with no errors.

**Comment by pabrcno** [comment]
I ended up going for Flutter no regrets.

**Comment by ObaidaSaleh** [comment]
sooooo?

**Comment by georgehgfonseca** [comment]
It is marked as fixed by https://github.com/expo/expo/pull/21912 but I'm still facing this issue =/

**Comment by fbansept** [comment]
It just happened during my react-native class, everyone with an Android 13 had the same problem. Paradoxically we had chosen expo for the compatibility between different hardware and operating systems :). We hope you can solve this problem :D

**Comment by sanak** [comment]
Hi @brentvatne, @gabrieldonadel (CC: @Kudo)

Sorry for pushing you about this, but I saw the upcoming SDK 49 beta release announcement in a week,
- [Expo SDK 49 beta is now available | by Brent Vatne | Jun, 2023 | Exposition](https://blog.expo.dev/expo-sdk-49-beta-is-now-available-6373e78f8624)

so I want to ask the followings.
- Will the next Expo Go release include this fix in SDK 48 ?
- Is there a chance for us (developers) to test next Expo Go Android apk before the next release ?

**Comment by orpos** [comment]
Any updates?

**Comment by sanak** [comment]
Thanks!
I confirmed that new Expo Go (2.29.1) Android version has no issues about this. 😄

**Comment by fbansept** [comment]
Testing with a Pixel 4 API 33 (Android 13). All seem to be working fine.

Notes that will be useless after updating expo to version 49 (not possible yet):

If you uninstall expo go and relaunch the application, expo go will always be in version 2.28.8, the same if you install a new emulator

To update expo go on your emulator you will need to have the play store installed (emulators that have a play store icon on android studio). You need to go to playstore and update expo go.

Be careful when you have updated expo go to version 2.29.1 expo will tell you "Expo Go on xxxxx is outdated, would you like to upgrade?" (Y/n)

Enter "n" because it will downgrade expo go to version 2.28.8 otherwise

Unless someone knows an alternative way, that seems to me the easiest way to test before expo 49?

**Comment by Edgar3101** [comment]
> Many thanks to the team !
> 
> Testing with a Pixel 4 API 33 (Android 13). All seem to be working fine.
> 
> I just want to add some informations that will be useless after updating expo to version 49 (not possible yet):
> 
> If you uninstall expo go and relaunch the application, expo go will always be in version 2.28.8, the same if you install a new emulator
> 
> To update expo go on your emulator you will need to have the play store installed (emulators that have a play store icon on android studio). You need to go to playstore and update expo go.
> 
> Be careful when you have updated expo go to version 2.29.1 expo will tell you "Expo Go on xxxxx is outdated, would you like to upgrade?" (Y/n)
> 
> Enter "n" because it will downgrade expo go to version 2.28.8 otherwise
> 
> Unless someone knows an alternative way, that seems to me the easiest way to test before expo 49?

Thanks this solution worked for me.

**Comment by hotaryuzaki** [comment]
> Many thanks to the team !
> 
> Testing with a Pixel 4 API 33 (Android 13). All seem to be working fine.
> 
> I just want to add some informations that will be useless after updating expo to version 49 (not possible yet):
> 
> If you uninstall expo go and relaunch the application, expo go will always be in version 2.28.8, the same if you install a new emulator
> 
> To update expo go on your emulator you will need to have the play store installed (emulators that have a play store icon on android studio). You need to go to playstore and update expo go.
> 
> Be careful when you have updated expo go to version 2.29.1 expo will tell you "Expo Go on xxxxx is outdated, would you like to upgrade?" (Y/n)
> 
> Enter "n" because it will downgrade expo go to version 2.28.8 otherwise
> 
> Unless someone knows an alternative way, that seems to me the easiest way to test before expo 49?

we don't use expo go and we have this issue also.
so how do I solve this? Is it possible that upgrading to Expo 49 will resolve this issue?

**Comment by fbansept** [comment]
> we don't use expo go and we have this issue also. so how do I solve this? Is it possible that upgrading to Expo 49 will resolve this issue?

The error was really locate in expo go 2.28.8 and for Android 13. I was mentioning expo 49 compared to the version of expo go that it would provide by default in the installation (currently expo 48 installs expo go 2.28.8 and expo 49 will install expo go 2.29.1). So expo 49 won't fix anything more than expo go version. Are you sure the problem is not elsewhere?

**Comment by ahmadamri-id** [comment]
> > we don't use expo go and we have this issue also. so how do I solve this? Is it possible that upgrading to Expo 49 will resolve this issue?
> 
> The error was really locate in expo go 2.28.8 and for Android 13 [see here](https://github.com/expo/expo/pull/21912) I was mentioning expo 49 compared to the version of expo go that it would provide by default in the installation (currently expo 48 installs expo go 2.28.8 on device/emulator and expo 49 will install expo go 2.29.1). So expo 49 won't fix anything more than expo go version. Are you sure the problem is not elsewhere?

From the symptoms the problem is similar, so we open the camera and take a picture, then we click check. After the camera is closed, the app will restart.
We found this only in some android 11 devices, it occurs in Oppo. There is no error in RN, but we found ANR_LOG code mention about memory issue in ADB LOG.

**Comment by fbansept** [comment]
> From the symptoms the problem is similar, so we open the camera and take a picture, then we click check. After the camera is closed, the app will restart. We found this only in some android 11 devices, it occurs in Oppo. There is no error in RN, but we found ANR_LOG code mention about memory issue in ADB LOG.
> 
> NOTE: sorry I replied using different account.

Sounds like a really different problem. The application did not close, there was simply an error message:

WARN  Possible Unhandled Promise Rejection (id: 0): Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected. → Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission

Try with another device, or another emulator.

Or check with this working example :

```
config :
    "expo": "~48.0.18",
    "expo-image-picker": "~14.1.1",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "expo-updates": "~0.16.4"
```
```
  import * as ImagePicker from "expo-image-picker";

  [photo, setPhoto] = useState(null);

  const onClick = async () => {
    const cameraPermission = await ImagePicker.requestCameraPermissionsAsync();
    if (cameraPermission.granted === false) {
      return;
    }

    const result = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: false,
      aspect: [4, 3],
      quality: 1,
    });

    if (!result.cancelled) {
      const { assets } = result;
      if (assets && assets.length > 0) {
        setPhoto(assets[0].uri);
      }
    }
  };
```

**Comment by ahmadamri-id** [comment]
> > From the symptoms the problem is similar, so we open the camera and take a picture, then we click check. After the camera is closed, the app will restart. We found this only in some android 11 devices, it occurs in Oppo. There is no error in RN, but we found ANR_LOG code mention about memory issue in ADB LOG.
> > NOTE: sorry I replied using different account.
> 
> Sounds like a really different problem. The application did not close, there was simply an error message:
> 
> WARN Possible Unhandled Promise Rejection (id: 0): Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected. → Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission
> 
> Try with another device, or another emulator.
> 
> Or check with this working example :
> 
> ```
> config :
>     "expo": "~48.0.18",
>     "expo-image-picker": "~14.1.1",
>     "react": "18.2.0",
>     "react-native": "0.71.8",
>     "expo-updates": "~0.16.4"
> ```
> 
> ```
>   import * as ImagePicker from "expo-image-picker";
> 
>   [photo, setPhoto] = useState(null);
> 
>   const onClick = async () => {
>     const cameraPermission = await ImagePicker.requestCameraPermissionsAsync();
>     if (cameraPermission.granted === false) {
>       return;
>     }
> 
>     const result = await ImagePicker.launchCameraAsync({
>       mediaTypes: ImagePicker.MediaTypeOptions.Images,
>       allowsEditing: false,
>       aspect: [4, 3],
>       quality: 1,
>     });
> 
>     if (!result.cancelled) {
>       const { assets } = result;
>       if (assets && assets.length > 0) {
>         setPhoto(assets[0].uri);
>       }
>     }
>   };
> ```

My problem similar like here
https://github.com/expo/expo/issues/21629

What I mean with "close" is not closing the app but back to the our initial screen.

**Comment by ahmadamri-id** [comment]
> So this topic (closed) is not the right place to expose this problem. [#21629](https://github.com/expo/expo/issues/21629) you mention already seems to be a duplicate of this [#21573](https://github.com/expo/expo/issues/21573) and this [#21544](https://github.com/expo/expo/issues/21544)

Maybe you don't realize that https://github.com/expo/expo/issues/21544
is here.
That is why I'm here now.

**Comment by fbansept** [comment]
> Maybe you don't realize that #21544
> is here.

^^ yeah sorry wrong link

**Comment by thekittyinboots** [comment]
Is there any news on this topic? I'm experiencing the same issue. After clicking on the photo confirmation, the application restarts. This problem seems to affect only some users with Motorola phones.
"expo": "^49.0.21",
"expo-image-picker": "~14.3.2"

**Comment by RainelU** [comment]
Is there news? I had the same problem, I have seen all the posts on the subject and none of them give me the solution.
@gabrieldonadel **Please help**!

"expo": "^49.0.0",
"expo-image-picker": "^14.7.1"

https://github.com/expo/expo/assets/35438485/cae0e983-10c2-468f-b578-79c45cd2ac91

**Comment by fbansept** [comment]
@RainelU @thekittyinboots @ahmadamri-id  

The bug you're describing seems to really have no relation to the original bug. The app wasn't restarting, there was a specific message:

"WARN Possible Unhandled Promise Rejection (id: 0): Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected. → Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission, parameter permission Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected"

The bug did not cause the app to stop. If you want a chance for someone to fix this issue: open a new ticket, describe your problem, the configuration, and a reproducible example. Use another device, provide logs... If you just say "my app doesn't work" no one will be able to help you.

You can use this minimalist example to make sure the problem doesn't come from another component (create a new project)

App.js
`import { useState } from "react";
import { Button, Image, View } from "react-native";
import * as ImagePicker from "expo-image-picker";

export default function App() {
  const App = () => {
    const [image, setImage] = useState(null);

    const pickImage = async () => {
      // No permissions request is necessary for launching the image library

      // try with launchImageLibraryAsync too
      let result = await ImagePicker.launchCameraAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true, // try with false
        aspect: [4, 3], // try with different aspect
        quality: 1, // try with different quality
      });

      //check result
      console.log(result);

      if (!result.canceled) {
        setImage(result.assets[0].uri);
      }
    };
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Button title="Pick an image from camera roll" onPress={pickImage} />
        {image && (
          <Image source={{ uri: image }} style={{ width: 200, height: 200 }} />
        )}
      </View>
    );
  };

  return (
      <App></App>
  );
}
`

babel.config.js
`module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["react-native-reanimated/plugin"],
  };
};
`

package.json
`{
  "name": "test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "npx expo start --clear"
  },
  "dependencies": {
    "expo": "~50.0.6",
    "expo-image-picker": "~14.7.1",
    "react": "18.2.0",
    "react-native": "0.73.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
`

**Comment by HEIZENNBERG** [comment]
hi im using expo go 2.31.1 and sdk51 and i get this error  ERROR  Error requesting camera permissions: [TypeError: Cannot read property 'Type' of undefined] when trying to open the camera 
  useEffect(() => {
    (async () => {
      try {
        const { status } = await Camera.requestCameraPermissionsAsync();
        setHasPermission(status === 'granted');
      } catch (error) {
        console.error('Error requesting camera permissions:', error);
        Alert.alert('Error', 'Failed to request camera permissions.');
      }
    })();
  }, []); 
  any help asap

**Comment by Futuresea-Dev1207** [comment]
Error taking photo: [Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.
→ Caused by: Failed to resolve activity to handle the intent of type 'null']
SDK version is latest.
Camera permission is already allowed.
Please help me.

**Comment by qaezrun** [comment]
> Error taking photo: [Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected. → Caused by: Failed to resolve activity to handle the intent of type 'null'] SDK version is latest. Camera permission is already allowed. Please help me.


Same situation @Healer-Dev1207  have you already found any solution?

**Comment by Healer-Dev1207** [comment]
@qaezrun 
I didn't found yet.
