### ISSUE TITLE
[expo-image] Weird perfromance issues

### ISSUE THREAD

**Issue by BubbleTrouble14** [expo/expo#21548]
### Minimal reproducible example

https://github.com/BubbleTrouble14/MintgardenMobileNew/blob/master/App.tsx

### Summary

My plan is to be able to show lots of images which are loaded from a uri by using flashlist. I want to give users to change the number of images that are visible to per row. For example 1, 2, 4, 8. But when doing so it seems become very slow after like 4 images per row. I am not sure if its just a limitiation of the library or if there is something still not working 100 percent correctly. Because when using the same image uri for each image its still super perfomant with 8 images per row. I made sure to disable the caching and also added a different cachekey for each image, but that shouldn't do anything when caching is disabled. Another thing i noticed is that when for example i was at 8 images per row and switch back to 1 the perfomance issues perssit. When I still had caching enabled I tried also clearing the chache after changing the row count, but that had no effect. 

I provided an example app where one can easily switch between it working smoothly and the slow mode by just changing the commented out code here: 
![image](https://user-images.githubusercontent.com/11683739/222970436-e4f0329f-a03e-4ae8-8b53-6077263cbc02.png)

Here are 2 gifs showing the one where its super smooth and the other one where its slow:

Slow: https://gyazo.com/61d0c34ea9f4ebe37da4b1abb8132f38
Super smooth: https://gyazo.com/ca942d1dbdd4b3f14cbb110d99bf24ae

Would love to here if what I am trying is just not possible with expo-image or if it is actually something that can be fixed. Or if its just and issue with flashlist. 

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.3.1 - ~\Documents\MintgardenMobileNew\node_modules\.bin\npm.CMD
    SDKs:
      Android SDK:
        Android NDK: 22.1.7171670
    npmPackages:
      expo: ^48.0.0 => 48.0.1
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: bare

**Comment by zhelezkov** [comment]
Hey!
Idk, maybe it's related to my issue here https://github.com/expo/expo/issues/21491

Btw, I see difference in your gifs:
- on the first one all images are different
- on the second one all images are the same

And I saw abolutely same behaviour in my use case. One image duplicated N times was fine, and M images rendered N times gave a significant performance hit.

**Comment by BubbleTrouble14** [comment]
Yes the difference with the 2 gifs is there to show the performance hit when using different uri‘s compared to only one uri. As the performance hit is strange as its not like there are so many new images to load.

**Comment by BubbleTrouble14** [comment]
And yes i think the problem i am facing is the same as the the other issue.
