### ISSUE TITLE
[expo-image-picker] Picking svg hard crashes the app when allowsEditing:true

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [expo/expo#21555]
### Minimal reproducible example

https://github.com/OzymandiasTheGreat/image-picker-crash

### Summary

Running image picker with `MediaTypeOptions.Images` allows picking images of unsupported types, like svg on android.
If `ImagePicker.launchImageLibraryAsync` is launched with `allowsEditing: false` this results in promise rejection.
However, setting `allowsEditing: true` causes exception in Java code. This cannot be handled and causes hard crash.

Not relevant for iOS since `MediaTypeOptions.Images` seems to exclude unsupported types on this platform.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        Android NDK: 21.4.7075529
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.5 => 48.0.5
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: bare

**Comment by Codelica** [comment]
Does the native error complain about a null object reference in `setTintColor` ?

**Comment by kitolog** [comment]
As a temporary solution, you can try this package

[expo-image-picker-fix-svg](https://www.npmjs.com/package/expo-image-picker-fix-svg)
