### ISSUE TITLE
expo publish not working anymore after upgrading to Expo 48

### ISSUE THREAD

**Issue by Spharian** [expo/expo#21556]
### Summary

Hello,

Before upgrading to expo 48, `expo publish` would update production builds (TestFlight and production apps downloaded from stores). We were getting the changes by killing the app and relaunching it.

After upgrading to expo 48, it's not working anymore. I read the upgrade guide about expo publish being removed from SDK 50 but after trying to upgrade my project to EAS Updates, I encountered tons of problems and couldn't get a "clean and simple workflow" just like before with dotenv variables, etc...

### SDK Version

48

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.5 => 48.0.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: managed
```

### Minimal reproducible example

`expo publish --clear`

**Comment by Kudo** [comment]
hi there! i've tried with these steps on sdk 48 project and it works for me. could you try to create a minimal reproducible examples and upload to some git repository. i'm happy to investigate further what's the problem inside.

```sh
$ yarn create expo-app sdk48
$ cd sdk48
$ npx install expo-updates
$ npx expo run:android --variant release

# edit App.js
$ expo-cli publish --clear
# kill and launch app twice
```

i would also like to help what the problem you've had from the eas update migration.

**Comment by Spharian** [comment]
> hi there! i've tried with these steps on sdk 48 project and it works for me. could you try to create a minimal reproducible examples and upload to some git repository. i'm happy to investigate further what's the problem inside.
> 
> ```shell
> $ yarn create expo-app sdk48
> $ cd sdk48
> $ npx install expo-updates
> $ npx expo run:android --variant release
> 
> # edit App.js
> $ expo-cli publish --clear
> # kill and launch app twice
> ```
> 
> i would also like to help what the problem you've had from the eas update migration.

Well, a minimal reproducible example is hard to publish as I got the problem coming from Expo 47 to 48, I followed every steps of the upgrade guide and expo publish for the production build wasn't working anymore.

The problems I had with eas update migrations: https://github.com/expo/eas-cli/issues/1123
After following the eas update migration guide, I was able to make the update work but as I'm using dotenv for a staging environment (which points to a different API), I was having the problems mentioned in this thread (some updates would mess my env variables).

For now, I reverted back to `expo publish --clear` but I still can't update my production build just like I did with Expo 47.

**Comment by Kudo** [comment]
thanks for the sharing eas-cli issue. i will check this with the team.

for `expo-cli publish` issue, could you elaborate what's the steps you did? that would help us to investigate the problem. for example, after upgrading from sdk 47 -> 48, you should create a new sdk 48 based app. only the sdk 48 based app could get updates from `expo-cli publish`.

**Comment by stesvis** [comment]
Has anyone found a solution?
I migrated to Expo SDK 48, configured `eas` and everything and ran `eas update`.
I can see the update in Expo Go but when i open it it's always stuck on **New update available, downloading...** or **Checking for new update...**

Why can't i test the app in Expo Go anymore? What am I missing?

**Comment by EthanHermsey** [comment]
I installed expo-cli globally with `npm i -g expo-cli` which offers the publish functionallity that I was used too.
