### ISSUE TITLE
Expo-av not working properly in samsung fold devices.

### ISSUE THREAD

**Issue by developersahab** [expo/expo#21567]
### Minimal reproducible example

https://snack.expo.dev/@devendra.swoquix/cranky-stroopwafel

### Summary

I have started recording in samsung fold z4 device but when i unfold the device then it's not showing recording and i am not able to start new recording even not able to stop, resume that recording.

Works fine in development mode but not in production

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.5 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

**Comment by developersahab** [comment]
Fixed by adding android:resizeableActivity="false"

**Comment by mayank-crescentek** [comment]
@developersahab  It will stop the app to having full screen while unfolding the device. Any solution for that? or any other solution to make this thing work without "android:resizeableActivity="false".
