### ISSUE TITLE
EAS build: Problem during the build

### ISSUE THREAD

**Issue by jorgejardim** [expo/expo#21571]
### Summary

I'm having this problem during the build phase called: **Run fastlane**

`Creating Gymfile
Gymfile created
Successfully loaded '/Users/expo/workingdir/build/ios/Gymfile' 📄
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                  Detected Values from './Gymfile'                                                                   |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| suppress_xcode_output | true                                                                                                                                        |
| clean                 | false                                                                                                                                       |
| scheme                | FoodChecker                                                                                                                                 |
| configuration         | Release                                                                                                                                     |
| export_options        |                                                                                                                                             |
| export_xcargs         | OTHER_CODE_SIGN_FLAGS="--keychain /var/folders/rp/_x4mwf8x2f52ml0n3qt65jw80000gn/T/turtle-v2-2f0f465d-b460-4566-b062-d312bba27420.keychain" |
| disable_xcpretty      | true                                                                                                                                        |
| buildlog_path         | /Users/expo/workingdir/logs                                                                                                                 |
| output_directory      | ./build                                                                                                                                     |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
Resolving Swift Package Manager dependencies...
$ xcodebuild -resolvePackageDependencies -workspace ./FoodChecker.xcworkspace -scheme FoodChecker -configuration Release
▸ Command line invocation:
▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./FoodChecker.xcworkspace -scheme FoodChecker -configuration Release
▸ User defaults from command line:
▸     IDEPackageSupportUseBuiltinSCM = YES
▸ --- xcodebuild: WARNING: Using the first of multiple matching destinations:
▸ { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:0000FE00-66D45333AEB93EDA }
▸ { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
▸ { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
▸ { platform:iOS Simulator, id:94EE5B62-6A73-4410-8C64-A56FBFD9C55D, OS:16.2, name:iPad (10th generation) }
▸ { platform:iOS Simulator, id:537FF0C8-8B14-4E2E-9828-0ED246BE9E38, OS:16.2, name:iPad Air (5th generation) }
▸ { platform:iOS Simulator, id:777A520C-1C1B-484A-99C6-35943FA97067, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
▸ { platform:iOS Simulator, id:A5447295-3264-4816-9C78-50E5F35C1122, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
▸ { platform:iOS Simulator, id:067F74D9-EEC3-4066-B8A8-B3EAD0EE5649, OS:16.2, name:iPad mini (6th generation) }
▸ { platform:iOS Simulator, id:3A1FD6BA-A84C-4728-A0AA-E7D9DF147BA7, OS:16.2, name:iPhone 14 }
▸ { platform:iOS Simulator, id:5D252FD0-2816-4FAE-B85D-C29DC8D2C73C, OS:16.2, name:iPhone 14 Plus }
▸ { platform:iOS Simulator, id:AA475350-BBB4-4568-A722-4528CF187FA8, OS:16.2, name:iPhone 14 Pro }
▸ { platform:iOS Simulator, id:01B24393-FC59-4FEC-87FD-338E47BABDAE, OS:16.2, name:iPhone 14 Pro Max }
▸ { platform:iOS Simulator, id:88B2387A-FF6D-4979-9155-B06611A97148, OS:16.2, name:iPhone SE (3rd generation) }
▸ resolved source packages:
$ xcodebuild -showBuildSettings -workspace ./FoodChecker.xcworkspace -scheme FoodChecker -configuration Release
[stderr] 
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
[stderr] 
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:0000FE00-66D45333AEB93EDA }
[stderr] 
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[stderr] 
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[stderr] 
{ platform:iOS Simulator, id:94EE5B62-6A73-4410-8C64-A56FBFD9C55D, OS:16.2, name:iPad (10th generation) }
[stderr] 
{ platform:iOS Simulator, id:537FF0C8-8B14-4E2E-9828-0ED246BE9E38, OS:16.2, name:iPad Air (5th generation) }
[stderr] 
{ platform:iOS Simulator, id:777A520C-1C1B-484A-99C6-35943FA97067, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
[stderr] 
{ platform:iOS Simulator, id:A5447295-3264-4816-9C78-50E5F35C1122, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
[stderr] 
{ platform:iOS Simulator, id:067F74D9-EEC3-4066-B8A8-B3EAD0EE5649, OS:16.2, name:iPad mini (6th generation) }
[stderr] 
{ platform:iOS Simulator, id:3A1FD6BA-A84C-4728-A0AA-E7D9DF147BA7, OS:16.2, name:iPhone 14 }
[stderr] 
{ platform:iOS Simulator, id:5D252FD0-2816-4FAE-B85D-C29DC8D2C73C, OS:16.2, name:iPhone 14 Plus }
[stderr] 
{ platform:iOS Simulator, id:AA475350-BBB4-4568-A722-4528CF187FA8, OS:16.2, name:iPhone 14 Pro }
[stderr] 
{ platform:iOS Simulator, id:01B24393-FC59-4FEC-87FD-338E47BABDAE, OS:16.2, name:iPhone 14 Pro Max }
[stderr] 
{ platform:iOS Simulator, id:88B2387A-FF6D-4979-9155-B06611A97148, OS:16.2, name:iPhone SE (3rd generation) }
Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[stderr] 
2023-03-06 12:08:04.598 xcodebuild[5150:16083] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
[stderr] 
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
[stderr] 
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:0000FE00-66D45333AEB93EDA }
[stderr] 
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[stderr] 
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[stderr] 
{ platform:iOS Simulator, id:94EE5B62-6A73-4410-8C64-A56FBFD9C55D, OS:16.2, name:iPad (10th generation) }
[stderr] 
{ platform:iOS Simulator, id:537FF0C8-8B14-4E2E-9828-0ED246BE9E38, OS:16.2, name:iPad Air (5th generation) }
[stderr] 
{ platform:iOS Simulator, id:777A520C-1C1B-484A-99C6-35943FA97067, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
[stderr] 
{ platform:iOS Simulator, id:A5447295-3264-4816-9C78-50E5F35C1122, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
[stderr] 
{ platform:iOS Simulator, id:067F74D9-EEC3-4066-B8A8-B3EAD0EE5649, OS:16.2, name:iPad mini (6th generation) }
[stderr] 
{ platform:iOS Simulator, id:3A1FD6BA-A84C-4728-A0AA-E7D9DF147BA7, OS:16.2, name:iPhone 14 }
[stderr] 
{ platform:iOS Simulator, id:5D252FD0-2816-4FAE-B85D-C29DC8D2C73C, OS:16.2, name:iPhone 14 Plus }
[stderr] 
{ platform:iOS Simulator, id:AA475350-BBB4-4568-A722-4528CF187FA8, OS:16.2, name:iPhone 14 Pro }
[stderr] 
{ platform:iOS Simulator, id:01B24393-FC59-4FEC-87FD-338E47BABDAE, OS:16.2, name:iPhone 14 Pro Max }
[stderr] 
{ platform:iOS Simulator, id:88B2387A-FF6D-4979-9155-B06611A97148, OS:16.2, name:iPhone SE (3rd generation) }
[stderr] 
2023-03-06 12:08:05.057 xcodebuild[5167:16213] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
Detected provisioning profile mapping: {:"br.com.foodchecker"=>"8381d29d-50c8-4148-bd17-1741aad5f1c9"}
+--------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                       Summary for gym 2.211.0                                                                                        |
+--------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| workspace                                              | ./FoodChecker.xcworkspace                                                                                                                   |
| scheme                                                 | FoodChecker                                                                                                                                 |
| clean                                                  | false                                                                                                                                       |
| output_directory                                       | ./build                                                                                                                                     |
| output_name                                            | FoodChecker                                                                                                                                 |
| configuration                                          | Release                                                                                                                                     |
| silent                                                 | false                                                                                                                                       |
| skip_package_ipa                                       | false                                                                                                                                       |
| skip_package_pkg                                       | false                                                                                                                                       |
| export_options.method                                  | app-store                                                                                                                                   |
| export_options.provisioningProfiles.br.com.foodchecker | 8381d29d-50c8-4148-bd17-1741aad5f1c9                                                                                                        |
| export_xcargs                                          | OTHER_CODE_SIGN_FLAGS="--keychain /var/folders/rp/_x4mwf8x2f52ml0n3qt65jw80000gn/T/turtle-v2-2f0f465d-b460-4566-b062-d312bba27420.keychain" |
| build_path                                             | /Users/expo/Library/Developer/Xcode/Archives/2023-03-06                                                                                     |
| result_bundle                                          | false                                                                                                                                       |
| buildlog_path                                          | /Users/expo/workingdir/logs                                                                                                                 |
| destination                                            | generic/platform=iOS                                                                                                                        |
| suppress_xcode_output                                  | true                                                                                                                                        |
| xcodebuild_formatter                                   | xcpretty                                                                                                                                    |
| disable_xcpretty                                       | true                                                                                                                                        |
| skip_profile_detection                                 | false                                                                                                                                       |
| xcodebuild_command                                     | xcodebuild                                                                                                                                  |
| skip_package_dependencies_resolution                   | false                                                                                                                                       |
| disable_package_automatic_updates                      | false                                                                                                                                       |
| use_system_scm                                         | false                                                                                                                                       |
| xcode_path                                             | /Applications/Xcode.app                                                                                                                     |
+--------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
$ set -o pipefail && xcodebuild -workspace ./FoodChecker.xcworkspace -scheme FoodChecker -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/expo/Library/Developer/Xcode/Archives/2023-03-06/FoodChecker\ 2023-03-06\ 12.08.05.xcarchive archive | tee /Users/expo/workingdir/logs/FoodChecker-FoodChecker.log > /dev/null
› Executing react-native Pods/hermes-engine » [CP] Copy XCFrameworks
› Compiling react-native Pods/libevent » strlcpy.c
› Compiling react-native Pods/libevent » signal.c
› Compiling react-native Pods/libevent » select.c
› Compiling react-native Pods/libevent » poll.c
› Compiling react-native Pods/libevent » log.c
› Compiling listener.c
› Compiling react-native Pods/libevent » libevent-dummy.m
› Compiling react-native Pods/libevent » kqueue.c
› Compiling react-native Pods/libevent » http.c
› Compiling react-native Pods/libevent » evutil_time.c
› Compiling react-native Pods/libevent » evutil_rand.c
› Compiling react-native Pods/libevent » evutil.c
› Compiling react-native Pods/libevent » evthread.c
› Compiling react-native Pods/libevent » evrpc.c
› Compiling react-native Pods/libevent » evmap.c
› Compiling react-native Pods/libevent » event_tagging.c
› Compiling react-native Pods/libevent » event.c
› Compiling react-native Pods/libevent » evdns.c
› Compiling react-native Pods/libevent » bufferevent_sock.c
› Compiling react-native Pods/libevent » bufferevent_pair.c
› Compiling react-native Pods/libevent » bufferevent_filter.c
› Compiling react-native Pods/libevent » bufferevent.c

⚠️  (../../../../Pods/libevent/defer-internal.h:46:11)

   @param cb The function to run when the struct event_callback executes.
          ^ parameter 'cb' not found in the function declaration [-Wdocumentation]
› Compiling react-native Pods/libevent » buffer.c
› Compiling react-native Pods/glog » vlog_is_on.cc
› Compiling react-native Pods/glog » utilities.cc
› Packaging react-native Pods/libevent » liblibevent.a
› Compiling react-native Pods/glog » symbolize.cc
› Compiling react-native Pods/glog » signalhandler.cc
› Compiling react-native Pods/glog » raw_logging.cc
› Compiling react-native Pods/glog » logging.cc
› Compiling react-native Pods/glog » glog-dummy.m
› Compiling react-native Pods/glog » demangle.cc
› Compiling react-native Pods/fmt » format.cc
› Compiling react-native Pods/fmt » fmt-dummy.m
› Packaging react-native Pods/glog » libglog.a
› Compiling react-native Pods/Yoga » log.cpp
› Compiling react-native Pods/Yoga » experiments.cpp
› Compiling react-native Pods/Yoga » event.cpp
› Compiling react-native Pods/Yoga » Yoga.cpp
› Compiling react-native Pods/Yoga » Yoga-dummy.m
› Compiling react-native Pods/Yoga » YGValue.cpp
› Compiling react-native Pods/Yoga » YGStyle.cpp
› Compiling react-native Pods/Yoga » YGNodePrint.cpp
› Compiling react-native Pods/Yoga » YGNode.cpp
› Compiling react-native Pods/Yoga » YGLayout.cpp
› Compiling react-native Pods/Yoga » YGEnums.cpp
› Packaging react-native Pods/fmt » libfmt.a
› Compiling react-native Pods/Yoga » YGConfig.cpp
› Compiling react-native Pods/Yoga » Utils.cpp
› Compiling react-native Pods/React-perflogger » React-perflogger-dummy.m
› Compiling react-native Pods/React-perflogger » BridgeNativeModulePerfLogger.cpp
› Packaging react-native Pods/Yoga » libYoga.a
› Compiling react-native Pods/React-logger » react_native_log.cpp
› Compiling react-native Pods/React-logger » React-logger-dummy.m
› Packaging react-native Pods/React-perflogger » libReact-perflogger.a
› Compiling react-native Pods/React-jsinspector » React-jsinspector-dummy.m
› Compiling react-native Pods/React-jsinspector » InspectorInterfaces.cpp
› Packaging react-native Pods/React-logger » libReact-logger.a
› Preparing react-native Pods/React-Core-AccessibilityResources » ResourceBundle-AccessibilityResources-React-Core-Info.plist
› Copying   react-native ../../../Users/expo/Library/Developer/Xcode/DerivedData/FoodChecker-acfmgjilrcrnwdgeicofyfwvgqqq/Build/Intermediates.noindex/ArchiveIntermediates/FoodChecker/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AccessibilityResources.bundle/en.lproj ➜ ../../../Users/expo/workingdir/build/node_modules/react-native/React/AccessibilityResources/en.lproj
› Creating  react-native Pods/React-Core-AccessibilityResources » AccessibilityResources.bundle
› Preparing expo-constants Pods/EXConstants-EXConstants » ResourceBundle-EXConstants-EXConstants-Info.plist
› Creating  expo-constants Pods/EXConstants-EXConstants » EXConstants.bundle
› Compiling react-native Pods/DoubleConversion » strtod.cc
› Compiling react-native Pods/DoubleConversion » fixed-dtoa.cc
› Compiling react-native Pods/DoubleConversion » fast-dtoa.cc
› Compiling react-native Pods/DoubleConversion » double-conversion.cc
› Compiling react-native Pods/DoubleConversion » diy-fp.cc
› Packaging react-native Pods/React-jsinspector » libReact-jsinspector.a
› Compiling react-native Pods/DoubleConversion » bignum.cc
› Compiling react-native Pods/DoubleConversion » bignum-dtoa.cc
› Compiling react-native Pods/DoubleConversion » DoubleConversion-dummy.m
› Packaging react-native Pods/DoubleConversion » libDoubleConversion.a
› Compiling react-native Pods/RCT-Folly » json_pointer.cpp
› Compiling react-native Pods/RCT-Folly » json.cpp
› Compiling react-native Pods/RCT-Folly » dynamic.cpp
› Compiling react-native Pods/RCT-Folly » WaitOptions.cpp
› Compiling react-native Pods/RCT-Folly » VirtualEventBase.cpp
› Compiling react-native Pods/RCT-Folly » UniqueInstance.cpp
› Compiling react-native Pods/RCT-Folly » Unicode.cpp
› Compiling react-native Pods/RCT-Folly » Try.cpp
› Compiling react-native Pods/RCT-Folly » ToAscii.cpp
› Compiling react-native Pods/RCT-Folly » TimeoutManager.cpp
› Compiling react-native Pods/RCT-Folly » TimekeeperScheduledExecutor.cpp
› Compiling react-native Pods/RCT-Folly » TimedDrivableExecutor.cpp
› Compiling react-native Pods/RCT-Folly » ThreadedExecutor.cpp
› Compiling react-native Pods/RCT-Folly » ThreadWheelTimekeeper.cpp
› Compiling react-native Pods/RCT-Folly » ThreadPoolExecutor.cpp
› Compiling react-native Pods/RCT-Folly » ThreadName.cpp
› Compiling react-native Pods/RCT-Folly » ThreadLocalDetail.cpp
› Compiling react-native Pods/RCT-Folly » ThreadId.cpp
› Compiling react-native Pods/RCT-Folly » SysUio.cpp
› Compiling react-native Pods/RCT-Folly » SysMembarrier.cpp
› Compiling react-native Pods/RCT-Folly » String.cpp
› Compiling react-native Pods/RCT-Folly » StrandExecutor.cpp
› Compiling react-native Pods/RCT-Folly » StaticSingletonManager.cpp
› Compiling react-native Pods/RCT-Folly » SpookyHashV2.cpp
› Compiling react-native Pods/RCT-Folly » Sleeper.cpp
› Compiling react-native Pods/RCT-Folly » SingletonStackTrace.cpp
› Compiling react-native Pods/RCT-Folly » Singleton.cpp
› Compiling react-native Pods/RCT-Folly » SimpleLoopController.cpp
› Compiling react-native Pods/RCT-Folly » SharedPromise.cpp
› Compiling react-native Pods/RCT-Folly » SharedMutex.cpp
› Compiling react-native Pods/RCT-Folly » SerialExecutor.cpp
› Compiling react-native Pods/RCT-Folly » SemaphoreBase.cpp
› Compiling react-native Pods/RCT-Folly » Semaphore.cpp
› Compiling react-native Pods/RCT-Folly » ScopeGuard.cpp
› Compiling react-native Pods/RCT-Folly » SanitizeThread.cpp
› Compiling react-native Pods/RCT-Folly » SafeAssert.cpp
› Compiling react-native Pods/RCT-Folly » Request.cpp
› Compiling react-native Pods/RCT-Folly » Rcu.cpp
› Compiling react-native Pods/RCT-Folly » RCT-Folly-dummy.m
› Compiling react-native Pods/RCT-Folly » QueuedImmediateExecutor.cpp
› Compiling react-native Pods/RCT-Folly » QueueObserver.cpp
› Compiling react-native Pods/RCT-Folly » Promise.cpp
› Compiling react-native Pods/RCT-Folly » Pid.cpp
› Compiling react-native Pods/RCT-Folly » ParkingLot.cpp
› Compiling react-native Pods/RCT-Folly » NetOps.cpp
› Compiling react-native Pods/RCT-Folly » MeteredExecutor.cpp
› Compiling react-native Pods/RCT-Folly » MemoryIdler.cpp
› Compiling react-native Pods/RCT-Folly » ManualTimekeeper.cpp
› Compiling react-native Pods/RCT-Folly » ManualExecutor.cpp
› Compiling react-native Pods/RCT-Folly » MallocImpl.cpp
› Compiling react-native Pods/RCT-Folly » MallctlHelper.cpp
› Compiling react-native Pods/RCT-Folly » InlineExecutor.cpp
› Compiling react-native Pods/RCT-Folly » IOThreadPoolExecutor.cpp
› Compiling react-native Pods/RCT-Folly » IOThreadPoolDeadlockDetectorObserver.cpp
› Compiling react-native Pods/RCT-Folly » IOBufQueue.cpp
› Compiling react-native Pods/RCT-Folly » IOBuf.cpp
› Compiling react-native Pods/RCT-Folly » HazptrThreadPoolExecutor.cpp
› Compiling react-native Pods/RCT-Folly » Hazptr.cpp
› Compiling react-native Pods/RCT-Folly » HardwareConcurrency.cpp
› Compiling react-native Pods/RCT-Folly » Hardware.cpp
› Compiling react-native Pods/RCT-Folly » HHWheelTimer.cpp
› Compiling react-native Pods/RCT-Folly » GuardPageAllocator.cpp
› Compiling react-native Pods/RCT-Folly » GlobalThreadPoolList.cpp
› Compiling react-native Pods/RCT-Folly » GlobalExecutor.cpp
› Compiling react-native Pods/RCT-Folly » Future.cpp
› Compiling react-native Pods/RCT-Folly » Futex.cpp
› Compiling react-native Pods/RCT-Folly » Format.cpp
› Compiling react-native Pods/RCT-Folly » FileUtil.cpp
› Compiling react-native Pods/RCT-Folly » FiberManager.cpp
› Compiling react-native Pods/RCT-Folly » Fiber.cpp
› Compiling react-native Pods/RCT-Folly » F14Table.cpp
› Compiling react-native Pods/RCT-Folly » ExecutorWithPriority.cpp
› Compiling react-native Pods/RCT-Folly » Executor.cpp
› Compiling react-native Pods/RCT-Folly » ExceptionWrapper.cpp
› Compiling react-native Pods/RCT-Folly » ExceptionString.cpp
› Compiling react-native Pods/RCT-Folly » Exception.cpp
› Compiling react-native Pods/RCT-Folly » EventHandler.cpp
› Compiling react-native Pods/RCT-Folly » EventBaseManager.cpp
› Compiling react-native Pods/RCT-Folly » EventBaseLocal.cpp
› Compiling react-native Pods/RCT-Folly » EventBaseBackendBase.cpp
› Compiling react-native Pods/RCT-Folly » EventBase.cpp
› Compiling react-native Pods/RCT-Folly » EDFThreadPoolExecutor.cpp
› Compiling react-native Pods/RCT-Folly » DistributedMutex.cpp
› Compiling react-native Pods/RCT-Folly » Demangle.cpp
› Compiling react-native Pods/RCT-Folly » DeadlockDetector.cpp
› Compiling react-native Pods/RCT-Folly » Cursor.cpp
› Compiling react-native Pods/RCT-Folly » Core.cpp
› Compiling react-native Pods/RCT-Folly » Conv.cpp
› Compiling react-native Pods/RCT-Folly » Codel.cpp
› Compiling react-native Pods/RCT-Folly » CacheLocality.cpp
› Compiling react-native Pods/RCT-Folly » CString.cpp
› Compiling react-native Pods/RCT-Folly » CPUThreadPoolExecutor.cpp
› Compiling react-native Pods/RCT-Folly » Baton.cpp
› Compiling react-native Pods/RCT-Folly » BatchSemaphore.cpp
› Compiling react-native Pods/RCT-Folly » Barrier.cpp
› Compiling react-native Pods/RCT-Folly » AtomicNotification.cpp
› Compiling react-native Pods/RCT-Folly » AtFork.cpp
› Compiling react-native Pods/RCT-Folly » AsyncTrace.cpp
› Compiling react-native Pods/RCT-Folly » AsyncTimeout.cpp
› Compiling react-native Pods/RCT-Folly » AsyncStack.cpp
› Compiling react-native Pods/RCT-Folly » AsymmetricMemoryBarrier.cpp
› Compiling react-native Pods/RCT-Folly » Assume.cpp
› Packaging react-native Pods/RCT-Folly » libRCT-Folly.a
› Compiling react-native Pods/React-jsi » React-jsi-dummy.m
› Compiling react-native Pods/React-jsi » JSIDynamic.cpp
› Packaging react-native Pods/React-jsi » libReact-jsi.a
› Compiling react-native Pods/React-cxxreact » ReactMarker.cpp
› Compiling react-native Pods/React-cxxreact » React-cxxreact-dummy.m
› Compiling react-native Pods/React-cxxreact » RAMBundleRegistry.cpp
› Compiling react-native Pods/React-cxxreact » NativeToJsBridge.cpp
› Compiling react-native Pods/React-cxxreact » ModuleRegistry.cpp
› Compiling react-native Pods/React-cxxreact » MethodCall.cpp
› Compiling react-native Pods/React-cxxreact » JSIndexedRAMBundle.cpp
› Compiling react-native JSExecutor.cpp
› Compiling react-native Pods/React-cxxreact » JSBundleType.cpp
› Compiling react-native Pods/React-cxxreact » JSBigString.cpp
› Compiling react-native Pods/React-cxxreact » Instance.cpp
› Compiling react-native Pods/React-cxxreact » CxxNativeModule.cpp
› Packaging react-native Pods/React-cxxreact » libReact-cxxreact.a
› Compiling react-native Pods/React-jsiexecutor » React-jsiexecutor-dummy.m
› Compiling react-native Pods/React-jsiexecutor » JSINativeModules.cpp
› Compiling react-native Pods/React-jsiexecutor » JSIExecutor.cpp
› Packaging react-native Pods/React-jsiexecutor » libReact-jsiexecutor.a
› Compiling react-native Pods/React-hermes » Thread.cpp
› Compiling react-native Pods/React-hermes » SerialExecutor.cpp
› Compiling react-native Pods/React-hermes » RuntimeAdapter.cpp
› Compiling react-native Pods/React-hermes » Registration.cpp
› Compiling react-native Pods/React-hermes » MessageTypes.cpp
› Compiling react-native Pods/React-hermes » MessageConverters.cpp
› Compiling react-native Pods/React-hermes » InspectorState.cpp
› Compiling react-native Pods/React-hermes » Inspector.cpp
› Compiling react-native Pods/React-hermes » HermesExecutorFactory.cpp
› Compiling react-native Pods/React-hermes » ConnectionDemux.cpp
› Compiling react-native Pods/React-hermes » Connection.cpp
› Compiling react-native Pods/React-hermes » CallbackOStream.cpp
› Compiling react-native Pods/React-Core » UIView+React.m
› Compiling react-native Pods/React-Core » React-Core-dummy.m
› Compiling react-native Pods/React-Core » RCTWrapperViewController.m
› Compiling react-native Pods/React-Core » RCTWeakProxy.m
› Compiling react-native Pods/React-Core » RCTViewUtils.m
› Compiling react-native Pods/React-Core » RCTViewRegistry.m
› Compiling react-native Pods/React-Core » RCTViewManager.m
› Compiling react-native Pods/React-Core » RCTView.m
› Compiling react-native Pods/React-Core » RCTVersion.m
› Compiling react-native Pods/React-Core » RCTUtilsUIOverride.m
› Compiling react-native Pods/React-Core » RCTUtils.m
› Compiling react-native Pods/React-Core » RCTUIUtils.m
› Compiling react-native Pods/React-Core » RCTUIManagerUtils.m
› Compiling react-native Pods/React-Core » RCTUIManagerObserverCoordinator.mm
› Compiling react-native Pods/React-Core » RCTUIManager.m
› Compiling react-native Pods/React-Core » RCTTouchHandler.m
› Compiling react-native Pods/React-Core » RCTTouchEvent.m
› Compiling react-native Pods/React-Core » RCTSwitchManager.m
› Compiling react-native Pods/React-Core » RCTSwitch.m
› Compiling react-native Pods/React-Core » RCTSurfaceView.mm
› Compiling react-native Pods/React-Core » RCTSurfaceStage.m
› Compiling react-native Pods/React-Core » RCTSurfaceSizeMeasureMode.mm
› Compiling react-native Pods/React-Core » RCTSurfaceRootView.mm
› Compiling react-native Pods/React-Core » RCTSurfaceRootShadowView.m
› Compiling react-native Pods/React-Core » RCTSurfacePresenterStub.m
› Compiling react-native Pods/React-Core » RCTSurfaceHostingView.mm
› Compiling react-native Pods/React-Core » RCTSurfaceHostingProxyRootView.mm
› Compiling react-native Pods/React-Core » RCTSurface.mm
› Compiling react-native Pods/React-Core » RCTSliderManager.m
› Compiling react-native Pods/React-Core » RCTSlider.m
› Compiling react-native Pods/React-Core » RCTShadowView.m
› Compiling react-native Pods/React-Core » RCTShadowView+Layout.m
› Compiling react-native Pods/React-Core » RCTShadowView+Internal.m
› Compiling react-native Pods/React-Core » RCTSegmentedControlManager.m
› Compiling react-native Pods/React-Core » RCTSegmentedControl.m
› Compiling react-native Pods/React-Core » RCTScrollViewManager.m
› Compiling react-native Pods/React-Core » RCTScrollView.m
› Compiling react-native Pods/React-Core » RCTScrollEvent.m
› Compiling react-native Pods/React-Core » RCTScrollContentViewManager.m
› Compiling react-native Pods/React-Core » RCTScrollContentView.m
› Compiling react-native Pods/React-Core » RCTScrollContentShadowView.m
› Compiling react-native Pods/React-Core » RCTSafeAreaViewManager.m
› Compiling react-native Pods/React-Core » RCTSafeAreaViewLocalData.m
› Compiling react-native Pods/React-Core » RCTSafeAreaView.m
› Compiling react-native Pods/React-Core » RCTSafeAreaShadowView.m
› Compiling react-native Pods/React-Core » RCTSRWebSocket.m
› Compiling react-native Pods/React-Core » RCTRootView.m
› Compiling react-native Pods/React-Core » RCTRootShadowView.m
› Compiling react-native Pods/React-Core » RCTRootContentView.m
› Compiling react-native Pods/React-Core » RCTReloadCommand.m
› Compiling react-native Pods/React-Core » RCTRefreshControlManager.m
› Compiling react-native Pods/React-Core » RCTRefreshControl.m
› Compiling react-native Pods/React-Core » RCTRedBoxSetEnabled.m
› Compiling react-native Pods/React-Core » RCTRedBoxExtraDataViewController.m
› Compiling react-native Pods/React-Core » RCTReconnectingWebSocket.m
› Compiling react-native Pods/React-Core » RCTProgressViewManager.m
› Compiling react-native Pods/React-Core » RCTProfile.m
› Compiling react-native Pods/React-Core » RCTPerformanceLoggerLabels.m
› Compiling react-native Pods/React-Core » RCTPerformanceLogger.m
› Compiling react-native Pods/React-Core » RCTParserUtils.m
› Compiling react-native Pods/React-Core » RCTPackagerConnection.mm`

And then in **Fail build** section I have:

`Build failed: Internal Server Error.
Try again later. If the problem persists, report the issue.`

Build ID:
dc13d848-8a82-4353-9851-a9512b4f8112

### What platform(s) does this occur on?

iOS

### SDK Version

48.0.0

### Environment

Creating new worker instance
Using VM template "macos-monterey-12.6-xcode-14.2" running macOS Monterey 12.6
Installed software:
- Xcode 14.2 (14C18)
- Node.js 16.18.1
- Yarn 1.22.17
- pnpm 7.27.0
- npm 8.1.2
- fastlane 2.211.0
- CocoaPods 1.11.3
- Ruby 2.7
- Expo CLI 6.0.0

### Minimal reproducible example

Create an EAS build and check if it works for iOS

`eas build --platform ios`

**Comment by udkhatri** [comment]
I am facing the same problem after updating to expo 48. Have you found any solution?

**Comment by ronaks-code** [comment]
Same here! Any solutions?
