### ISSUE TITLE
Installation RemoteConfig - Your JavaScript code tried to access a native module that doesn't exist

### ISSUE THREAD

**Issue by lutluthfi** [expo/expo#21575]
### Minimal reproducible example

1. Add these following code your `dependencies` in `package.json`
```json
"dependencies" : {
    "@react-native-firebase/analytics": "^17.3.1",
    "@react-native-firebase/app": "^17.3.2",
    "@react-native-firebase/remote-config": "^17.3.1",
}
```
2. In your `App.js` file, add these code to import the modules
```js
import RemoteConfig from "@react-native-firebase/remote-config";
```
4. Execute this command `npx expo start -c`
5. Run in your iOS simulator or iPhone
6. You should get the error
```
Uncaught Error

Your JavaScript code tried to access a native module that doesn't exist.
```

### Summary

Hi, I'm in the middle of personal project. I create React Native project with Expo.
When I try to install the Firebase Remote Config and I follow step-by-step in this link https://rnfirebase.io/remote-config/usage then try to run, the apps show this Uncaught Error
<img src="https://user-images.githubusercontent.com/16360926/223177001-024fb06b-054c-4a86-984f-66a61e01e39f.jpeg" width="200" />

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.2.0 - /usr/local/bin/node
      npm: 9.5.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.4 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: managed
```

**Comment by Kudo** [comment]
hi there! to use react-native-firebase on expo projects, you need further [setup](https://rnfirebase.io/#managed-workflow) with a [customized app](https://docs.expo.dev/workflow/customizing/) other than Expo Go. please give it a try. if that's still a case for you, i'm happy to reopen this issue and investigate with you.

**Comment by Kudo** [comment]
@lutluthfi the file should be `app.config.js`. after the configuration, did you execute `npx expo prebuild --clean` and `npx expo run:ios`?

**Comment by lutluthfi** [comment]
I spend a night for me to realize that RemoteConfig run through native not Expo Go from AppStore.

Because I run in Expo Go app from AppStore before, 😵‍💫

Thanks for help @Kudo

**Comment by virgiliosolano** [comment]
Hi @Kudo 
I have the same problem, my project build from xcode but not install on simulators. Any ideia?
