### ISSUE TITLE
Very unresponsive app after upgrading SDK

### ISSUE THREAD

**Issue by GitTibbe** [expo/expo#2159]
My app works fine using SDK25. However after upgrading to SDK28 the app is totally unresponsive (tap delays of several seconds, can't swipe etc) but without errors or warnings in the console. Three packages where deprecated (TabNavigator, StackNavigator, TabBarBottom) which I fixed and replaced in the code. 

I have no idea of what is causing the problem?
Using Mac OS X Simulator iOS 11.4. 

Thanks in advance!

**Comment by FiberJW** [comment]
Hi, we’re closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks :)
