### ISSUE TITLE
Upgrade Expo from 45 to 46 makes SectionList jumps

### ISSUE THREAD

**Issue by DenysMoro** [expo/expo#21606]
### Minimal reproducible example

https://github.com/DenysMoro/expo-46-section-list

### Summary

Something happening with `SectionList` at `react-native: 0.69+`.
See videos for better understanding. It is something with huge lists (big amount of items)
It starts to jump and blink

I'm not saying that it is bug of Expo. Can you please advice me where to post this issue?
Also, I've noticed that when I'm doing downgrade of `react-native` to `0.68` - it starts to work totally fine

How to reproduce:
- Install fresh expo project or clone from git
- Scroll up and down to trigger pagination
- Scroll for about 2-4 minutes (can't upload full 3 minutes video)

Real app:
https://user-images.githubusercontent.com/77282657/223674363-20feee00-64d0-4fd7-a187-c35b5540bda0.mov

Fresh app (reproducible demo):
https://user-images.githubusercontent.com/77282657/223674442-23cc3fbd-bf4b-4e7e-b813-b9b2f036be8d.mov

Thank you for you work and wonderful framework!

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.19 => 46.0.20 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by DenysMoro** [comment]
Posted this issue at `react-native` repo - https://github.com/facebook/react-native/issues/36414

**Comment by brentvatne** [comment]
I've seen this same issue on an app of my own with react-native's SectionList - I ended up moving it to use react-native-flash-list instead. I'll close this issue here because it's a bug in upstream React Native
