### ISSUE TITLE
Expo-Camera onBarCodeScanned does not work in standalone apk and development build

### ISSUE THREAD

**Issue by aleksandarRadi** [expo/expo#21605]
### Minimal reproducible example

<Camera             ratio="16:9"             flashMode={flashMode ? FlashMode.torch : FlashMode.off}             onBarCodeScanned={scanned ? undefined : Scanning}             style={{               height: Dimensions.get('window').height,               width: '100%',             }}           />

### Summary

onBarCodeScanned works fine in Expo Go but does not in development build nor in standalone apk.
The issue is for Android, iOS not tested yet.
It does not return error, it seems it's just never called.
onCameraReady, Zoom or flashMode all work.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      expo: ~46.0.9 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ^0.18.9 => 0.18.10 
    Expo Workflow: managed

**Comment by Vanclief** [comment]
I have the same issue @aleksandarRadi, did you find the solution?

**Comment by aleksandarRadi** [comment]
> I have the same issue @aleksandarRadi, did you find the solution?

Started working once we switched to bare workflow

**Comment by Vanclief** [comment]
Thanks for the reply. Worked for me after adding the `bar-code-scanner` library
