### ISSUE TITLE
[Help Wanted] Remove Expo Splash Screen From App

### ISSUE THREAD

**Issue by themakerman** [expo/expo#2161]
Hi,

Can anybody guide me how can i remove the splash screen completely? I do not want to setup even my own icon from app.js file. I plan to make my own RN component with animations as a splash screen and handle displaying it with routing/navigation libraries. 

Can anybody guide me how can i remove the splash screen completely provided by expo?

**Comment by ide** [comment]
Every app needs a splash screen so the OS can display content before the app has finished launching. You can provide a blank white image if you'd like.
