### ISSUE TITLE
`Pedometer` from `expo-sensors` not working at all

### ISSUE THREAD

**Issue by kul-sudo** [expo/expo#21618]
### Minimal reproducible example

https://snack.expo.dev/@stamend/rebellious-nachos

### Summary

As you can see from the code above, I have pretty much copied the code from here: https://docs.expo.dev/versions/latest/sdk/pedometer/

We have the state variable called ```currentStepCount``` and it is then used in ```<Text>Walk! And watch this go up: {currentStepCount}</Text>```. Everything seems to be tremendously easy, right? But for some reason, when I have built the project into APK, wherever I go, whenever I go, it simply stays at the value of `0`.
I thought that it could be because of the lack of permission, so I decided to make sure it is present. That did not help as well:
```js
useEffect(() => {
  const toCall = async () => {
    const { status } = await Pedometer.requestPermissionsAsync()
    console.log(status)
  }
  toCall()
}, [])
```

 Does anyone have any thoughts?

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 19.7.0 - ~\scoop\apps\nodejs\current\node.EXE
      Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
      npm: 9.5.0 - ~\scoop\apps\nodejs\current\npm.CMD
    npmPackages:
      expo: ~48.0.6 => 48.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: managed

**Comment by rahilchughtai** [comment]
Im able to reproduce the problem

**Comment by kul-sudo** [comment]
> Im able to reproduce the problem

So it does not work for you too?

**Comment by rahilchughtai** [comment]
> > Im able to reproduce the problem
> 
> So it does not work for you too?

Yes, its stuck at 0, both on IOS and Android , no matter how much i move

**Comment by kul-sudo** [comment]
> > > Im able to reproduce the problem
> > 
> > So it does not work for you too?
> 
> Yes, its stuck at 0, both on IOS and Android , no matter how much i move

Hopefully, it will be fixed, because there is no clue for the fix: it is just totally stuck at 0.

**Comment by Expan75** [comment]
Have used the pedometer and am able to read sensor data runningly. Cannot get it to run in the background but here's my working code for the pedometer updates.

```jsx
export default StepCounter = () => {

  const [currentStepCount, setCurrentStepCount] = useState(0);


  const handlePedometerPermission = async () => {
    const permissions = await Pedometer.getPermissionsAsync()
    if (!permissions.granted) {
      await Pedometer.requestPermissionsAsync()
      const updatedPermissions = await Pedometer.getPermissionsAsync()
      if (!updatedPermissions.granted) {
        Alert.alert("You cannot earn coupons unless you share your steps taken")
        handlePedometerPermission();
      }
    }
  }

  const subscribeToPedometer = async () => {
    await handlePedometerPermission();
    const permission = await Pedometer.getPermissionsAsync();
    const isAvailable = await Pedometer.isAvailableAsync();

    if (isAvailable && permission.granted) {
        setCurrentStepCount(result.steps);
     }
 }
  
  useEffect(() => {
    const subscription = subscribeToPedometer();
    return () => subscription.then(r => r.remove())
    }, [])
    
  useEffect(() => {}, [currentStepCount])

  // insert your component here
  return <>
```

**Comment by dheerajtp** [comment]
> ```js
> Pedometer
> ```

does it work ?
