### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSScreen" was not found in the UIManager.

### ISSUE THREAD

**Issue by noobster97** [expo/expo#21624]
### Minimal reproducible example

This error is located at:     in RNSScreen (created by AnimatedComponent)     in AnimatedComponent     in AnimatedComponentWrapper (created by InnerScreen)

### Summary

i get that error in dev client mode..i build apk and crashed..but work well on debug mode and no error but on dev client i got that error.i dont use any of react native screen on my app before this.After i upgrade to SDK 48.0.6 apk crashed and dev client got that error

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ^48.0.6 => 48.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    Expo Workflow: managed

**Comment by Kethankrk** [comment]
"you need to do another development build after you install react-native-screens. new development builds are required anytime you add or update a native dependency"

Said by a guy named [brents] https://forums.expo.dev/u/brents on the expo dev form site 
https://forums.expo.dev/t/expo-start-dev-client-invariant-violation-requirenativecomponent-rnsscreenstackheaderconfig-was-not-found-in-the-uimanager/65605
