### ISSUE TITLE
Next.js 13 + Expo 48 error loading @expo/vector-icons

### ISSUE THREAD

**Issue by CruelMoney** [expo/expo#21623]
### Minimal reproducible example

https://github.com/CruelMoney/nextjs-expo-icons

### Context: 

This error occurs in a mono-repo project with an expo app and a next.js website. The project has been set up following the instructions here: 

https://www.npmjs.com/package/@expo/next-adapter

### Expected behavior

The website shows the expo icon.

### What happens

When attempting to load expo vector icons in a next.js project, the following error occurs, and the page does not load:

```
error - ../node_modules/@react-native/assets/registry.js
Module parse failed: Unexpected token (13:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict';
|

> export type PackagerAsset = {
> | +\_\_packager_asset: boolean,
> | +fileSystemLocation: string,

Import trace for requested module:
../node_modules/@react-native/assets/registry.js
../node_modules/react-native/Libraries/Image/AssetRegistry.js
../node_modules/expo-asset/build/Asset.js
../node_modules/expo-asset/build/index.js
../node_modules/expo-font/build/FontLoader.web.js
../node_modules/expo-font/build/Font.js
../node_modules/expo-font/build/index.js
../node_modules/@expo/vector-icons/build/createIconSet.js
../node_modules/@expo/vector-icons/build/Icons.js
../expo-app/App.js
```

### What's been tried
Downgrading to Expo 47 fixes the issue.

I've also tried to add a flow preset to babel, but that didn't fix the issue. 

I'd like to dig deeper in this, but I'm a bit lost on how to debug it further. Seems to be expo related because it works with Expo 47.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.9 - /usr/local/bin/zsh
    Binaries:
      Node: 18.10.0 - ~/.asdf/installs/nodejs/18.10.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.01.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.6.1
    Expo Workflow: managed

next 13.2.3
next-fonts 1.5.1
react-native-web 0.18.12
@expo/next-adapter 5.0.2

**Comment by Kudo** [comment]
hi there! this should be next.js's issue, possibly from https://github.com/vercel/next.js/issues/45980.
i see two issues here.
1. swc doesn't support flow type stripping, so we should use babel fallback.
2. `transpilePackages` does not well support, so we should explicitly add packages.

this patch should work for your example:

```diff
diff --git a/expo-app/App.js b/expo-app/App.js
index de4e7bc..8319650 100644
--- a/expo-app/App.js
+++ b/expo-app/App.js
@@ -6,7 +6,7 @@ export default class Index extends React.Component {
   render() {
     return (
       <View>
-        <Ionicons name="error" />
+        <Ionicons name="alert" />
       </View>
     );
   }
diff --git a/next-app/next.config.js b/next-app/next.config.js
index cedad92..e03ae91 100644
--- a/next-app/next.config.js
+++ b/next-app/next.config.js
@@ -5,16 +5,17 @@ const withFonts = require("next-fonts");
 const nextConfig = withExpo(
   withFonts({
     reactStrictMode: true,
-    swcMinify: true,
     transpilePackages: [
       "react-native",
+      "react-native-web",
+      "@react-native/assets",
       "expo",
+      "expo-asset",
+      "expo-font",
+      "expo-modules-core",
       "@expo/vector-icons",
       // Add more React Native / Expo packages here...
     ],
-    experimental: {
-      forceSwcTransforms: true,
-    },
   })
 );

```

**Comment by nandorojo** [comment]
Next.js doesn't transpile flow, so this doesn't get fixed. I had to patch `@react-native/assets` to remove flow:

`@react-native+assets+1.0.0.patch`

```patch
diff --git a/node_modules/@react-native/assets/registry.js b/node_modules/@react-native/assets/registry.js
index 088187f..0a384d1 100644
--- a/node_modules/@react-native/assets/registry.js
+++ b/node_modules/@react-native/assets/registry.js
@@ -10,28 +10,16 @@
 
 'use strict';
  
-export type PackagerAsset = {
-  +__packager_asset: boolean,
-  +fileSystemLocation: string,
-  +httpServerLocation: string,
-  +width: ?number,
-  +height: ?number,
-  +scales: Array<number>,
-  +hash: string,
-  +name: string,
-  +type: string,
-  ...
-};
 
-const assets: Array<PackagerAsset> = [];
+const assets = [];
 
-function registerAsset(asset: PackagerAsset): number {
+function registerAsset(asset) {
   // `push` returns new array length, so the first asset will
   // get id 1 (not 0) to make the value truthy
   return assets.push(asset);
 }
 
-function getAssetByID(assetId: number): PackagerAsset {
+function getAssetByID(assetId) {
   return assets[assetId - 1];
 }
 
```

**Comment by kalmndo** [comment]
> Next.js doesn't transpile flow, so this doesn't get fixed. I had to patch `@react-native/assets` to remove flow:
> 
> `@react-native+assets+1.0.0.patch`
> 
> ```diff
> diff --git a/node_modules/@react-native/assets/registry.js b/node_modules/@react-native/assets/registry.js
> index 088187f..0a384d1 100644
> --- a/node_modules/@react-native/assets/registry.js
> +++ b/node_modules/@react-native/assets/registry.js
> @@ -10,28 +10,16 @@
>  
>  'use strict';
>   
> -export type PackagerAsset = {
> -  +__packager_asset: boolean,
> -  +fileSystemLocation: string,
> -  +httpServerLocation: string,
> -  +width: ?number,
> -  +height: ?number,
> -  +scales: Array<number>,
> -  +hash: string,
> -  +name: string,
> -  +type: string,
> -  ...
> -};
>  
> -const assets: Array<PackagerAsset> = [];
> +const assets = [];
>  
> -function registerAsset(asset: PackagerAsset): number {
> +function registerAsset(asset) {
>    // `push` returns new array length, so the first asset will
>    // get id 1 (not 0) to make the value truthy
>    return assets.push(asset);
>  }
>  
> -function getAssetByID(assetId: number): PackagerAsset {
> +function getAssetByID(assetId) {
>    return assets[assetId - 1];
>  }
>  
> ```

Hi i was wondering how do you implement this on solito? i don't think patch-package works with turborepo

**Comment by nandorojo** [comment]
patch package does work for me. you can add the patches folder in your turbo config dependencies

**Comment by kalmndo** [comment]
yes it is, i'm hardcoded it on patches folder in the root. and it is work.

**Comment by deeeed** [comment]
Do we know if there is different workaround than the patch?

**Comment by nandorojo** [comment]
react native really shouldn’t be shipping flow to npm

**Comment by benrbowers** [comment]
I was able to get @expo/vector-icons working with expo@50.0.15 and next@14.2.0, and with SWC! If anyone is here after starting a new solito repo, I would probably reccomend what solito now recommends which is to [use svg-based icons](https://solito.dev/recipes/icons) instead of font-based ones, @expo/vector-icons unfortunately being font-based.

That said, if like me you've already used @expo/vector-icons all over your application, then this may be helpful.

The first thing to point out is that @expo/vector-icons is essentially just a wrapper around react-native-vector-icons to make it compatible with expo. So, on web, we'll just use react-native-vector-icons by aliasing it in our config. **We will also alias react-native to react-native-web**, which will solve the "can't resolve module 'react-native'" messages.

You will need `react-native-web` and `react-native-vector-icons` installed in your next project.

Within the transpilePackages array, the only packages critical to our problem are `react-native-vector-icons` and `expo-modules-core`, the rest will be specific to your project.

Here is my next.config.js:
```
const { withExpo } = require('@expo/next-adapter');

/** @type {import('next').NextConfig} */
const nextConfig = {
	// reanimated (and thus, Moti) doesn't work with strict mode currently...
	// https://github.com/nandorojo/moti/issues/224
	// https://github.com/necolas/react-native-web/pull/2330
	// https://github.com/nandorojo/moti/issues/224
	// once that gets fixed, set this back to true
	swcMinify: true,
	reactStrictMode: false,
	transpilePackages: [
		'solito',
		'moti',
		'app',
		'react-native-reanimated',
		'react-native-vector-icons',
		'react-native-gesture-handler',
		'@react-native-async-storage/async-storage',
		'@react-native-community/slider',
		'expo-checkbox',
		'expo-status-bar',
		'expo-modules-core',
		'expo-constants',
		'nativewind',
		'react-native-css-interop',
	],
	experimental: {
		forceSwcTransforms: true,
	},
	webpack: (config) => {
		config.resolve.alias = {
			...(config.resolve.alias || {}),
			'react-native$': 'react-native-web',
			'@expo/vector-icons': 'react-native-vector-icons',
		};

		return config;
	},
};

const APP_ENV = process.env.APP_ENV || 'dev';

require('dotenv').config({
	path: `../../.env.${APP_ENV}`,
});

module.exports = withExpo(nextConfig);
```

The next thing you need to do is **manually import the fonts from your node_modules folder** in your `global.css` file. You will only need to import the ones you use.

For example:
```
@font-face {
	font-family: MaterialCommunityIcons;
	src: url('../../node_modules/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf');
}
@font-face {
	font-family: Feather;
	src: url('../../node_modules/react-native-vector-icons/Fonts/Feather.ttf');
}
@font-face {
	font-family: AntDesign;
	src: url('../../node_modules/react-native-vector-icons/Fonts/AntDesign.ttf');
}
@font-face {
	font-family: FontAwesome;
	src: url('../../node_modules/react-native-vector-icons/Fonts/FontAwesome.ttf');
}
@font-face {
	font-family: FontAwesome5_Regular;
	src: url('../../node_modules/react-native-vector-icons/Fonts/FontAwesome5_Regular.ttf');
}
@font-face {
	font-family: FontAwesome5_Solid;
	src: url('../../node_modules/react-native-vector-icons/Fonts/FontAwesome5_Solid.ttf');
}
```
Hope this helps!

Helpful links:
https://docs.nativebase.io/next-adapter-icons
https://github.com/oblador/react-native-vector-icons/issues/1447

`apps/expo`
expo-env-info 1.2.0 environment info:
  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 4.1.1 - ~/.yarn/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  npmPackages:
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.73.6 => 0.73.6 
  Expo Workflow: managed

`apps/next`
"@expo/next-adapter": "^6.0.0",
"dotenv": "^16.0.3",
"next": "^14.2.0",
"raf": "^3.4.1",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native-vector-icons": "^10.0.3",
"react-native-web": "^0.19.10"

**Comment by ThukuWakogi** [comment]
I had this problem too using expo 51 and next.js 14. My solution was to switch from swc to babel. Its a bummer cause I don't get the first compilation speeds of swc. However, its works for now.

I created a .babelrc in my next folder and added the following:

```
{
  "presets": ["next/babel", "@babel/preset-flow"]
}
```

Due to [this PR](https://github.com/swc-project/swc/pull/9114) I have some hope that in a future version of swc, flow will be stripped and this won't be an issue when using swc.

**Comment by gogooutowen** [comment]
Any update in this issue?
