### ISSUE TITLE
[expo-blur] Detox tests hang indefinitely on screen with BlurView on iOS

### ISSUE THREAD

**Issue by philiplindberg** [expo/expo#21640]
### Minimal reproducible example

https://github.com/philiplindberg/expo-blur-detox-repro

### Summary

I'm using both `BlurView` and Detox (for e2e testing) in my project, but I've noticed that whenever I try to run detox tests on a screen that has a `BlurView`, the detox test hangs indefinitely on iOS with the following error:

```
14:15:58.767 detox[13592] i The app is busy with the following tasks:
• Run loop "Main Run Loop" is awake.
• UI elements are busy:
  - Layer animations pending: 5.
• There are 1 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
```

To reproduce the issue, clone my [repro](https://github.com/philiplindberg/expo-blur-detox-repro) and run the following commands:
```
yarn install
yarn expo prebuild
yarn detox build -c ios.release
yarn detox test -c ios.release
```

Here's a screen recording of the detox tests being run on an iOS simulator:

https://user-images.githubusercontent.com/1865904/224052571-97c40fc8-0fd5-4ef8-bb69-bff618ab1ac3.mov

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.asdf/installs/nodejs/lts/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.6 => 48.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: bare

**Comment by maxckelly** [comment]
@philiplindberg did you find a way around this?

**Comment by philiplindberg** [comment]
@maxckelly only workaround I've found is to conditionally hide all `BlurView`s on iOS when running Detox tests.

**Comment by maxckelly** [comment]
Thanks @philiplindberg ended up moving to a different package as I couldn't find a fix as well.

**Comment by philiplindberg** [comment]
Looks like https://github.com/expo/expo/pull/22439 fixes the issue, thanks @behenate!
