### ISSUE TITLE
types Camera.BarcodeScanningResult and BarcodeScanner.BarcodeScannerResult wrong typing

### ISSUE THREAD

**Issue by badaz** [expo/expo#21642]
### Minimal reproducible example

Install expo-camera@13.2.1 and expo-barcode-scanner@12.3.2 in a project

### Summary

types Camera.BarcodeScanningResult and BarcodeScanner.BarcodeScannerResult expect a "bounds" property, yet they have a boundingBox property on android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.3.1 - /usr/local/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/sve/.gem/ruby/2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 29, 30, 31, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.0, 33.0.1
        System Images: android-22 | Google APIs ARM 64 v8a, android-23 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.6 => 48.0.6
      react: 18.1.0 => 18.1.0
      react-native: 0.70.7 => 0.70.7
    Expo Workflow: bare

**Comment by devoren** [comment]
+1 same
