### ISSUE TITLE
Adding marginTop style crashes Expo

### ISSUE THREAD

**Issue by robinwassen** [expo/expo#2166]
I was just going to give react-native a ride for the first time and created my first component, but when I added `marginTop` to any of the styles I had defined Expo started to crash.

Not sure if the marginTop value is valid on my styles since I managed to use Expo / react-native for 5 minutes before encountering this.

### Environment

Android and Snack

### Steps to Reproduce

1. Add a style
2. Add marginTop

### Expected Behavior

The element should get top margin (or at least present the red error screen in case adding the style is invalid)

### Actual Behavior

Android (device): Expo application hard crashes
Android (Snack) : Expo application hard crashes
iOS (Snack): Expo presents the app as a blank white screen, not sure if this is incorrect or not.

### Reproducible Demo

Use Android in the following Snack: https://snack.expo.io/H1oGO6Dv7

**Comment by robinwassen** [comment]
Found the problem, the react-native documentation states that `margin` works the same as in CSS and accepts `number, ,string` as value.

But values such as `"30"`, `"30px"` crashes the application, integer value `30` works as intended.

Not sure what you want to do with this issue, close it if you wish.

**Comment by machester4** [comment]
You can only use string if it is to use percentage. Ex. `"30%".` and **px** is not necessary since in mobile only this unit of measure is supported, which is why it is already explicit in the whole value that you give to the measure.

**Comment by seabadger-io** [comment]
Note that the above is true for all styling where similar to `margin` either a whole number or a percentage is expected like `width`/`maxWidth`/`padding` etc. It can be tricky to spot why it's crashing as the compiler/debugger doesn't complain about it.
