### ISSUE TITLE
@expo/config-plugins version is still 5.0.4 for expo-firebase-analytics@8.0.0 in expo sdk 48 (should be ~@6.0.0 

### ISSUE THREAD

**Issue by n0mer** [expo/expo#21673]
### Minimal reproducible example

n/a

### Summary

expo-firebase-analytics@8.0.0 -> expo-firebase-core "~6.0.0" -> expo-constants "~14.0.0" -> "@expo/config" "~7.0.2" -> "@expo/config-plugins" "~5.0.3" for expo 48

expo doctor output:

```
Running "expo doctor"
- Finding all copies of expo-modules-autolinking
- Finding all copies of @expo/config-plugins
[stderr] 
[05:06:35] Expected package @expo/config-plugins@~6.0.0
[stderr] 
[05:06:35] Found invalid:
[stderr] 
[05:06:35]   @expo/config-plugins@5.0.4
[stderr] 
[05:06:35]   (for more info, run: npm why @expo/config-plugins)
- Finding all copies of @expo/prebuild-config
- Finding all copies of @unimodules/core
- Finding all copies of @unimodules/react-native-adapter
- Finding all copies of react-native-unimodules
Command "expo doctor" failed.
bash exited with non-zero code: 1
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.0 
      expo: ^48.0.0 => 48.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.6.1
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by n0mer** [comment]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/1862997/224466452-73e134dd-f2ee-42d0-90f2-396a8a509fc4.png">

snacks does not support expo sdk 48

**Comment by lc3t35** [comment]
I have the same issue with @react-native-firebase/app@17.3.2

```
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@5.0.4
    (for more info, run: npm why @expo/config-plugins)

@expo/config-plugins@5.0.4
node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins
  @expo/config-plugins@"^5.0.4" from @react-native-firebase/app@17.3.2
  node_modules/@react-native-firebase/app
    @react-native-firebase/app@"^17.3.2" from the root project
    peer @react-native-firebase/app@"17.3.2" from @react-native-firebase/messaging@17.3.2
    node_modules/@react-native-firebase/messaging
      @react-native-firebase/messaging@"^17.3.2" from the root project
```

**Comment by n0mer** [comment]
just noticed https://docs.expo.dev/versions/v47.0.0/sdk/firebase-analytics/  : "Deprecated: This module will no longer be available in SDK 48"

Solution was just to remove expo-firebase-analytics and follow migration guide https://expo.fyi/firebase-migration-guide
