### ISSUE TITLE
[docs] Update Bare Modules Steps For React Native 0.71

### ISSUE THREAD

**Issue by enchorb** [expo/expo#21670]
### Summary

The steps on this page (https://docs.expo.dev/bare/installing-expo-modules/) seem to be incorrect for RN 0.71 & Expo SDK 48

### Link to the related docs page

https://docs.expo.dev/bare/installing-expo-modules/

**Comment by enchorb** [comment]
Related https://github.com/expo/expo/issues/21177

**Comment by Etx17** [comment]
Hello, did you solve it for React Native 0.71 ?

**Comment by enchorb** [comment]
Unfortunately not, rolled back to `0.70.7` the docs for Expo & what is on https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.71.4 differ too much

**Comment by yerevin** [comment]
If you want to upgrade your Bare Expo app I suggest taking a look into https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum `/android` and `/ios` directories and using https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.71.4 just go thru' each file and make sure it matches what Expo have in their bare-template.

It can be not the perfect solution, but it works if done carefully.

**Comment by amandeepmittal** [comment]
Closing this issue since manual installation steps are now updated with [this PR](https://github.com/expo/expo/pull/21797) and published at: https://docs.expo.dev/bare/installing-expo-modules/

Thanks for opening this issue!
