### ISSUE TITLE
[expo-av] unable to load spotify uri in loadAsync

### ISSUE THREAD

**Issue by karthickdev2023** [expo/expo#21678]
### Minimal reproducible example

https://snack.expo.dev/@karthickrajamurugan/companion

### Summary

Error loading audio file: Audio URI from external source spotify 
`import { Audio } from "expo-av";

export default function HomeScreen({ navigation }) {
  useEffect(() => {
    const music = async () => {
      try {
        const soundObject = new Audio.Sound();
        console.log('test')
        await soundObject.loadAsync(
          { uri: "spotify:track:6IA8E2Q5ttcpbuahIejO74" },
          { shouldPlay: true }
        );
        //  await soundObject.loadAsync({ uri: 'https://www.bensound.com/bensound-music/bensound-oblivion.mp3' },{ shouldPlay: true });
        const result = await soundObject.getStatusAsync();
        console.log("Audio file loaded successfully", result);
      } catch (error) {
        console.error("Error loading audio file:", error);
      }
    };
    music();
  }, []);`
 Getting below error
`Error loading audio file: Error: "com.google.android.exoplayer2.upstream.a0$d: Malformed URL" in construct@[native code] << construct@[native code] << a << t`

Not sure why happening only if use Spotify uri. It works in other url
Authorization code is available commented in example.
 
What platform(s) does this occur on?
Android/iOS and both simulator/emulator

SDK Version
48.0.4

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
      npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1 
      expo: ~48.0.4 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

**Comment by brentvatne** [comment]
the string that you provided - `spotify:track:6IA8E2Q5ttcpbuahIejO74` - is not a url, it will only work in the spotify app. the id itself is useless outside of the spotify app :)
