### ISSUE TITLE
[expo-image] - blurhash placeholder and contentFit -> incorect blurhash size

### ISSUE THREAD

**Issue by soukupl** [expo/expo#21677]
### Minimal reproducible example

https://snack.expo.dev/@soukupl/expo-image-blurhash-bug?platform=web

### Summary

There is an “bug” (unexpected behaviour) when using blurhash as placeholder in expo-image. Blurhash is always considered as square (1:1) and when contentFit is set to anything else than fill, it will be rendered incorrectly.

![2023-03-10---000429](https://user-images.githubusercontent.com/1013968/224477639-72977243-762f-4104-af96-74a0513ca625.png)
![2023-03-10---000430](https://user-images.githubusercontent.com/1013968/224477646-96f9b112-0161-4135-b2c8-1508b0a2ef40.png)

If blurhash is passed to placeholder prop, it should always be rendered as ‘fill’. Blurhash is always rendered as square, no matter the width / height and componentX / componentY set while creating the blurhash.

Example image: https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-4.0.3&dl=benjamin-voros-phIFdC6lA4E-unsplash.jpg&w=200&h=150
and corresponding blurhash: UDA,w-}[W+tSxyoMM_R*005RjJadJ3X7-qxa

Testing with expo-image 1.0.0 and Expo SDK 48.0.6.
btw: I would swear, that expo-image betas were rendering blurhash correctly, but I’m not sure if I had contentFit set to contain or cover :innocent:

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.5.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.0 
      expo: ~48.0.6 => 48.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: bare

**Comment by lukmccall** [comment]
Hi @soukupl, thanks for your report. Your assumption that blurhash is always considered to be a square is correct. However, you can change that. The placeholder prop can accept an object with the `uri`, `width`,  and `height`. Those dimensions will be used when the blurhash string is decoded. 

Instead of:
```
const blurhash = 'UDA,w-}[W+tSxyoMM_R*005RjJadJ3X7-qxa';
```
you can declare an object:
```
const blurhash = { uri: 'UDA,w-}[W+tSxyoMM_R*005RjJadJ3X7-qxa', width: 20, height: 20 };
```

**Comment by soukupl** [comment]
Hi,
nice, I didn't know I can set width and height for blurhash placeholder, that's nice! :)

I was looking to the source code of expo-image for iOS, and I found a [line 288 in `packages/expo-image/ios/ImageView.swift`](https://github.com/expo/expo/blob/620396ab06a5c2500a38e4f2e3a597e2204a1c45/packages/expo-image/ios/ImageView.swift#L288) file, where `self.placeholderContentFit` is set to the same value as source image. I believe that the 'fill' will be better here. But there may be reason why it is set ths way.

```javascript
func loadPlaceholderIfNecessary() {
    // Exit early if placeholder is not set or there is already an image attached to the view.
    // The placeholder is only used until the first image is loaded.
    ...
    imageManager.loadImage(with: placeholder.uri, context: context, progress: nil) { [weak self] placeholder, _, _, _, finished, _ in
      guard let self = self, let placeholder = placeholder, finished else {
        return
      }
      self.placeholderImage = placeholder
      self.placeholderContentFit = isBlurhash ? self.contentFit : self.placeholderContentFit
      self.displayPlaceholderIfNecessary()
    }
  }
```

**Comment by farhanhaider1** [comment]
is this issue fixed? still facing it.

**Comment by vitaliyhan** [comment]
the same. Can we control fit and cover somehow?

**Comment by z1haze** [comment]
`contentFit` appears not to be respected for the placeholder image at all.

**Comment by ammarfaris** [comment]
still facing this issue, has it been resolved?

**Comment by ammarfaris** [comment]
> Hi @soukupl, thanks for your report. Your assumption that blurhash is always considered to be a square is correct. However, you can change that. The placeholder prop can accept an object with the `uri`, `width`, and `height`. Those dimensions will be used when the blurhash string is decoded.
> 
> Instead of:
> 
> ```
> const blurhash = 'UDA,w-}[W+tSxyoMM_R*005RjJadJ3X7-qxa';
> ```
> 
> you can declare an object:
> 
> ```
> const blurhash = { uri: 'UDA,w-}[W+tSxyoMM_R*005RjJadJ3X7-qxa', width: 20, height: 20 };
> ```

this is not possible right @lukmccall ?

**Comment by efstathiosntonas** [comment]
did anyone managed to find a solution for this? @lukmccall proposal to pass an object with uri and dimensions does not work.

**Comment by ammarfaris** [comment]
> did anyone managed to find a solution for this? @lukmccall proposal to pass an object with uri and dimensions does not work.

agreed! NOT WORKING!

**Comment by lukmccall** [comment]
In my previous suggestion, I used an incorrect object scheme. Here's a better example:
```
 <Image
  style={{ backgroundColor: 'red', width: 300, height: 200 }}
  source={[]}
  placeholder={{ blurhash: 'LmLg9W-oNGt7~Cs.ofWC4:RkfRR*', width: 30, height: 20 }}
/>
```
We know that the size of the image component is `300x200`, so we can ensure that our blurhash will be decoded using the same aspect ratio.

**Comment by ammarfaris** [comment]
> In my previous suggestion, I used an incorrect object scheme. Here's a better example:
> 
> ```
>  <Image
>   style={{ backgroundColor: 'red', width: 300, height: 200 }}
>   source={[]}
>   placeholder={{ blurhash: 'LmLg9W-oNGt7~Cs.ofWC4:RkfRR*', width: 30, height: 20 }}
> />
> ```
> 
> We know that the size of the image component is `300x200`, so we can ensure that our blurhash will be decoded using the same aspect ratio.

Oh i didn't know we can have an object like that in placeholder... thank you so much @lukmccall

**Comment by ammarfaris** [comment]
```
<Image
  style={{ backgroundColor: 'red', width: 300, height: 200 }}
  source={...}
  placeholder={{ blurhash: 'LmLg9W-oNGt7~Cs.ofWC4:RkfRR*', width: 30, height: 20 }}
/>
```

by the way i just realized that using *expo-image on the web* with blurhash placeholder triggers unnecessary network call with the blurhash in the url => example:
"http://localhost:19000/LmLg9W-oNGt7~Cs.ofWC4:RkfRR*"

![Screenshot 2024-05-10 at 11 40 21 AM](https://github.com/expo/expo/assets/1182205/d5b00ed5-0fed-4c68-8468-56435741c6ea)

Anyone knows how to resolve this?
