### ISSUE TITLE
AssetUtils.resolveAsync is not working on Android

### ISSUE THREAD

**Issue by JinHoSo** [expo/expo#2167]
When I use AssetUtils.resolveAsync() function with uri like "content://media/external/images/media/113" from camera roll is not working. 

I already checked related permission as below 
```
      "CAMERA",
      "MANAGE_DOCUMENTS",
      "RECORD_AUDIO",
      "READ_EXTERNAL_STORAGE",
      "WRITE_EXTERNAL_STORAGE",
      "READ_INTERNAL_STORAGE"
```

I'm using SDK 29.0.0 detached

<img width="318" alt="2018-09-01 5 51 09" src="https://user-images.githubusercontent.com/31269303/44944329-b3dabf00-ae0f-11e8-8ff7-3eebb0a44f62.png">

**Comment by JinHoSo** [comment]
I guess ```await fileReference.downloadAsync();``` in expo-asset-utils has problem.

**Comment by JinHoSo** [comment]
[Unhandled promise rejection: Error: unexpected url: file:///data/user/0/test.pixi/cache/ExperienceData/%2540rustykey%252Ftest-pixi/5EOyTDQ.jpg]

**Comment by bogdan-calapod** [comment]
Any updates on this ?

**Comment by Mozartted** [comment]
Any updates on this, the issue still persists in SDK 30

**Comment by bogdan-calapod** [comment]
Also still broken in SDK 31. The silence on this issue is killing me - I've currently resorted to using a web service for applying filters, but obviously this isn't an ideal solution in any way. Would be nice to at least acknowledge this issue ?

**Comment by EvanBacon** [comment]
The issue was not acknowledged because this is not the correct repo https://github.com/expo/expo-asset-utils I must've seen the notifications and thought they were being posted there.  https://github.com/expo/expo-asset-utils/issues/10
