### ISSUE TITLE
FBSDKCoreKit error when installing the pods

### ISSUE THREAD

**Issue by machester4** [expo/expo#2168]
Apparently Facebook updated **FBSDKCoreKit to 4.36.0** and have not created the tag and this is causing problems when installing the `pods`. Does anyone have a quick solution until they create the tag for that version?

**Comment by chrisft25** [comment]
Did you solve the problem?, I'm having the same problem :(

**Comment by franckpopchef** [comment]
Add this to your Podfile:
`pod 'FBSDKCoreKit', '4.35'
pod 'FBSDKLoginKit', '4.35'
pod 'FBSDKShareKit', '4.35'`

**Comment by machester4** [comment]
@franckpopchef  that will not work, those libraries are installed from the `ExpoKit.podspec.json` of `ExpoKit` which looks for a version greater than `4.28` and ends up finding version `4.36` which does not have a `tag` yet. and tried cloning the last releases of both `ExpoKit` and Facebook SDK and modifying the `podfile` to use local versions but not successful. and written a post in facebook developers just wait to create the tag for the `4.36` version.

**Comment by franckpopchef** [comment]
Yes but for now it's working ;)

Be sure you clean your pod lock before running pod install with 4.35.

**Comment by chrisft25** [comment]
Actually it's working! They have updated the repositories!

**Comment by machester4** [comment]
is already working since Facebook has created the [release](https://github.com/facebook/facebook-ios-sdk/releases) for version 4.36.
