### ISSUE TITLE
Expo modules in bare workflow project

### ISSUE THREAD

**Issue by TsplayerT** [expo/expo#21682]
### Minimal reproducible example

https://github.com/TsplayerT/expo-bare-minimum

### Summary

hey guys! 👋 
can someone help me to use the **Expo modules** in a **bare workflow** project? Please 🙏 

I tried to create a project using the command `npx create-expo-app --template bare-minimum`
I ran the command  `npx expo install expo-crypto`
When running the project on **Android** operating system this error appears:
  `Error: Cannot find native module 'ExpoCrypto'`

### Environment

expo-env-info 1.0.5 environment info:
```
System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~48.0.6 => 48.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: bare
```

**Comment by sathwik77** [comment]
Did you run `npx pod install` after npm install as stated in here? https://github.com/expo/expo/tree/sdk-48/packages/expo-crypto

**Comment by TsplayerT** [comment]
@sathwik77 Sorry, I forgot to mention that I'm using **Android OS**. 😥

**Comment by Mancitiss** [comment]
hi @TsplayerT did you fix it somehow? I have been trying to find a solution for this for 2 days but no luck. I got the same error only when attempting to import it
`import * as Crypto from 'expo-crypto';`

**Comment by TsplayerT** [comment]
@Mancitiss  to be honest, I managed to solve it in a mysterious way kkkkkk.
Because I did everything at once:

I cleaned up the project by deleting the **node_modules** folder, **package-lock.json**, **android** folder
as described in this documentation: https://docs.expo.dev/troubleshooting/clear-cache-windows/

I executed the commands:
`npm cache clean --force`
`expo start --clear`

built and installed a new development version of the App
running command `eas build --platform android`

in my case, I'm not using the bare workflow project because I'm not changing anything natively.

It is worth remembering that it is necessary to install the package using the command:
`npx expo install expo-crypto`
