### ISSUE TITLE
expo-modules-core:configureCMakeDebug[arm64-v8a]

### ISSUE THREAD

**Issue by bemashebe** [expo/expo#21687]
### Summary

What went wrong:
Execution failed for task ':expo-modules-core:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using C:\Users\MASHEE\Documents\expo projects\zeropen-app\node_modules\expo-modules-core\android\CMakeLists.txt: C++ build system [configure] failed while executing:
      @echo off
      "C:\\Users\\MASHEE\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
        "-HC:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\expo-modules-core\\android" ^
        "-DCMAKE_SYSTEM_NAME=Android" ^
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
        "-DCMAKE_SYSTEM_VERSION=21" ^
        "-DANDROID_PLATFORM=android-21" ^
        "-DANDROID_ABI=arm64-v8a" ^
        "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
        "-DANDROID_NDK=C:\\Users\\MASHEE\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
        "-DCMAKE_ANDROID_NDK=C:\\Users\\MASHEE\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620" ^
        "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\MASHEE\\AppData\\Local\\Android\\Sdk\\ndk\\23.1.7779620\\build\\cmake\\android.toolchain.cmake" ^
        "-DCMAKE_MAKE_PROGRAM=C:\\Users\\MASHEE\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\expo-modules-core\\android\\build\\intermediates\\cxx\\Debug\\5n3y3z5z\\obj\\arm64-v8a" ^
        "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\expo-modules-core\\android\\build\\intermediates\\cxx\\Debug\\5n3y3z5z\\obj\\arm64-v8a" ^
        "-DCMAKE_BUILD_TYPE=Debug" ^
        "-DCMAKE_FIND_ROOT_PATH=C:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\expo-modules-core\\android\\.cxx\\Debug\\5n3y3z5z\\prefab\\arm64-v8a\\prefab" ^
        "-BC:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\expo-modules-core\\android\\.cxx\\Debug\\5n3y3z5z\\arm64-v8a" ^
        -GNinja ^
        "-DANDROID_STL=c++_shared" ^
        "-DREACT_NATIVE_DIR=C:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\react-native" ^
        "-DREACT_NATIVE_SO_DIR=C:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\expo-modules-core\\android\\build/react/jni" ^
        "-DREACT_NATIVE_TARGET_VERSION=71" ^
        "-DBOOST_VERSION=1_76_0" ^
        "-DUSE_HERMES=false" ^
        "-DHERMES_HEADER_DIR=null" ^
        "-DIS_NEW_ARCHITECTURE_ENABLED=false" ^
        "-DPROJECT_BUILD_DIR=C:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\expo-modules-core\\android\\build" ^
        "-DREACT_ANDROID_DIR=C:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\react-native/ReactAndroid" ^
        "-DREACT_ANDROID_BUILD_DIR=C:\\Users\\MASHEE\\Documents\\expo projects\\zeropen-app\\node_modules\\react-native/ReactAndroid/build" ^
        "-DUNIT_TEST=false"
    from C:\Users\MASHEE\Documents\expo projects\zeropen-app\node_modules\expo-modules-core\android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 48m 44s
484 actionable tasks: 310 executed, 169 from cache, 5 up-to-date
Error: C:\Users\MASHEE\Documents\expo projects\zeropen-app\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\MASHEE\Documents\expo projects\zeropen-app\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\MASHEE\Documents\expo projects\zeropen-app\node_modules\expo\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (C:\Users\MASHEE\Documents\expo projects\zeropen-app\node_modules\expo\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\MASHEE\Documents\expo projects\zeropen-app\node_modules\expo\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Users\MASHEE\Documents\expo projects\zeropen-app\node_modules\expo\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Users\MASHEE\Documents\expo projects\zeropen-app\node_modules\expo\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Users\MASHEE\Documents\expo projects\zeropen-app\node_modules\expo\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:31:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~2.1.5"

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.6.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ~48.0.6 => 48.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: bare

### Reproducible demo

npx create-expo-app my-app

npx expo install expo-dev-client

npx expo prebuild --clean

yarn android

**Comment by SoorajChoudhary** [comment]
I am Having same issue . Please let me know solution.

**Comment by bemashebe** [comment]
I did not solve the issue. Am used Eas to build dev app. Then download it
to my device.

**Comment by jucoAllison** [comment]
Am having the same issue, please any solution??

**Comment by bemashebe** [comment]
I didn't find the solution for building locally. The workaround am
currently using eas build to build my project

**Comment by VladimirDmytriienko** [comment]
Same!

**Comment by lengziyu** [comment]
Encountering this problem again

**Comment by chinmayakcv** [comment]
Facing same issue. Any idea related to root cause of the issue

**Comment by armando19993** [comment]
File build.gradle
change ndkVersion for 
ndkVersion = "26.2.11394342"
That solved it for me, it should be noted that I use macos

**Comment by guillempuche** [comment]
Thanks @armando19993, it worked for me with Expo v51.

Tip: I installed it through Android Studio SKD Tools.
![image](https://github.com/expo/expo/assets/3519924/5f736547-858c-44e2-9e1d-715f16da981c)

**Comment by brunoaiolfi** [comment]
It might sound crazy, but try renaming the project folder to remove special characters. It worked for me.
