### ISSUE TITLE
ExpoImage_Error: Error while updating property 'proxiedProperties' of a view managed by ViewManagerAdapter_ExpoImage

### ISSUE THREAD

**Issue by agrittiwari** [expo/expo#21693]
### Minimal reproducible example

Just used <Image /> in Flashlist's renderComponent

### Summary

I have tried to trace where this error is originating from:
I was only able to get to this [line :19](https://github.com/expo/expo/blob/main/packages/expo-modules-core/android/src/main/java/expo/modules/adapters/react/views/ViewManagerAdapterUtils.java)

![Screenshot_2023-03-13-14-55-16-870_com tractorjunction vms](https://user-images.githubusercontent.com/51356497/224674480-8dd0753e-f2f1-47a7-b87e-6a70e0f12274.jpg)
![Screenshot_2023-03-13-15-25-52-240_com tractorjunction vms](https://user-images.githubusercontent.com/51356497/224674510-d88d999d-eefd-4c5e-b072-a9ef24068512.jpg)

Would like to debug it if anyone from team , can guide me a bit.
 

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1
      expo: ~48.0.6 => 48.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.9 => 0.18.12
    Expo Workflow: bare
```

**Comment by lukmccall** [comment]
Hi @agrittiwari. Thanks for your report. I believe that the error comes from the below function https://github.com/expo/expo/blob/620396ab06a5c2500a38e4f2e3a597e2204a1c45/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerDefinition.kt#L39-L63. Could you check the native logs? There should be information about which prop can't be set.

**Comment by Andrey123815** [comment]
Faced with this error when try to pass to Image source prop empty value ' '
Try to set to any default value instead of this

**Comment by joshtornquist** [comment]
Another potential workaround is removing the `<Image>`'s import from `expo-image` and import it from `react-native `instead.
