### ISSUE TITLE
TextPath not working on Android

### ISSUE THREAD

**Issue by davidgithub1980** [expo/expo#2169]
Hi, my dev:

"expo": "^29.0.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz"

```
import { Svg } from 'expo';
const { Text, TextPath, Line } = Svg;

<Svg width={500} height={500}>
  <Line
    id="line"
    x1="100"
    y1="100"
    x2="300"
    y2="300"
    stroke="red"
    strokeWidth="2"
  />

  <Text fill="blue" fontSize="20">
    <TextPath href="#line">
      Some random text
    </TextPath>
  </Text>
</Svg>
```

This appears to be a bug as the code above **works perfectly on iPhone** but the **text within the _TextPath_ element is not visible at all on an Android phone**. Only the _Line_ element is displayed on an Android phone. The text along the path is missing completely.

**Comment by msand** [comment]
This seems to be working fine in the latest react-native-svg and react-native at least, and they're in the process of upgrading in Expo now, so will probably be fixed in the next version.

**Comment by FiberJW** [comment]
This seems to be resolved, so I’ll close this for now. If you notice any related bugs in the future, please open a new issue :)
