### ISSUE TITLE
expo-notifications error on import with Expo 48

### ISSUE THREAD

**Issue by elitenas** [expo/expo#21690]
### Minimal reproducible example

https://drive.google.com/file/d/1CRAdNhFnUNTXdtY0it0RR8ldGl96QNt_/view?usp=sharing

### Summary

When you import expo-notifications using the following line:

`import * as Notifications from 'expo-notifications';`

You get the following error on console:

```
ERROR in ./node_modules/abort-controller/polyfill.mjs:2
Module not found: Can't resolve './dist/abort-controller'
Did you mean 'abort-controller.mjs'?
BREAKING CHANGE: The request './dist/abort-controller' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
  1 | /*globals self, window */
> 2 | import * as ac from "./dist/abort-controller"
  3 | 
  4 | /*eslint-disable @mysticatea/prettier */
  5 | const g =

```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2023.02.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.1.0
    Expo Workflow: managed

**Comment by reite** [comment]
I am having the same issue. Reproduced it with a clean repository created by ```npx create-expo-app my-app``` here:
https://github.com/reite/Expo-48-notifications-crash

**Comment by kjkurtz** [comment]
I'm having this exact same issue when loading on web. I have the `Notifications.getExpoPushTokenAsync()` wrapped with `if (Device.isDevice)` but it still causes the same issue and for the app to crash.

**Comment by pors** [comment]
Is there a workaround till this gets fixed?

**Comment by pors** [comment]
It works for me now. 

Not sure if this is actually the cause of the problem, but the first time around I upgraded with `expo-cli upgrade`. 
 
On the second attempt I did `yarn add expo@^48.0.7` followed by `npx expo install --fix`.  No error this time!

**Comment by pors** [comment]
Some more info:

```
✖ Checking dependency versions for compatibility with the installed Expo SDK
Issues:
  Some dependencies are incompatible with the installed expo version:
    @expo/webpack-config@0.17.4 - expected version: ^18.0.1
    babel-preset-expo@9.2.2 - expected version: ^9.3.0
  Your project may not work correctly until you install the correct versions of the packages.
  Install individual packages by running npx expo install @expo/webpack-config@^18.0.1 babel-preset-expo@^9.3.0
  Found outdated dependencies
Advice:
  • Use npx expo install --check to review and upgrade your dependencies.
```

After installing the recommended versions, the error came back.

**Comment by bladey** [comment]
Also getting the exact same issue as described above, even with a brand new project.

**Comment by elitenas** [comment]
the above does fix it for me as well

**Comment by bladey** [comment]
@elitenas this still needs to be fixed for Expo 48 doesn't it?

**Comment by elitenas** [comment]
@bladey i think the issue is with webpack not expo and the above fix fixes it. The only impact it does have is that it disables fast refresh if the warnings are there. I can keep it open if you would like

**Comment by bladey** [comment]
@elitenas ok, that makes sense, thank you!

**Comment by SleeplessByte** [comment]
The issue is with the webpack configuration provided _by_ expo. The "fix" by @MinLiu121 should be included in the default template.

It doesn't just disable fast refresh. In many cases, the code will not build at all.

**Comment by pors** [comment]
This works for me:

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const ReactRefreshWebpackPlugin = require("@pmmmwh/react-refresh-webpack-plugin");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Use the React refresh plugin in development mode
  if (env.mode === "development") {
    config.plugins.push(
      new ReactRefreshWebpackPlugin()
    );
    config.module.rules.push({
      test: /.m?js/,
      resolve: {
        fullySpecified: false,
      },
    })
  }
  return config;
};

```

**Comment by matiast02** [comment]
> This works for me:
> 
> ```
> const createExpoWebpackConfigAsync = require('@expo/webpack-config');
> const ReactRefreshWebpackPlugin = require("@pmmmwh/react-refresh-webpack-plugin");
> 
> module.exports = async function (env, argv) {
>   const config = await createExpoWebpackConfigAsync(env, argv);
>   // Use the React refresh plugin in development mode
>   if (env.mode === "development") {
>     config.plugins.push(
>       new ReactRefreshWebpackPlugin()
>     );
>     config.module.rules.push({
>       test: /.m?js/,
>       resolve: {
>         fullySpecified: false,
>       },
>     })
>   }
>   return config;
> };
> ```

Thanks bro, but doesn't work for me. I'm getting this error now:
`WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[2].resolve has an unknown property 'fullySpecified'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
   -> Options for the resolver`
   
   Probably I'm missing something

**Comment by bladey** [comment]
@matiast02 I don't have any other changes besides what is needed to fix this issue, so it should be working:

```
const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  config.module.rules.push({
    test: /.m?js/,
    resolve: {
      fullySpecified: false,
    },
  });
  return config;
};
```

**Comment by matiast02** [comment]
> @matiast02 I don't have any other changes besides what is needed to fix this issue, so it should be working:
> 
> ```
> const createExpoWebpackConfigAsync = require("@expo/webpack-config");
> 
> module.exports = async function (env, argv) {
>   const config = await createExpoWebpackConfigAsync(env, argv);
>   config.module.rules.push({
>     test: /.m?js/,
>     resolve: {
>       fullySpecified: false,
>     },
>   });
>   return config;
> };
> ```

I updated to expo 48 and it works. Thanks @bladey @pors !!

**Comment by rinaldycodes** [comment]
> > @matiast02 I don't have any other changes besides what is needed to fix this issue, so it should be working:
> > ```
> > const createExpoWebpackConfigAsync = require("@expo/webpack-config");
> > 
> > module.exports = async function (env, argv) {
> >   const config = await createExpoWebpackConfigAsync(env, argv);
> >   config.module.rules.push({
> >     test: /.m?js/,
> >     resolve: {
> >       fullySpecified: false,
> >     },
> >   });
> >   return config;
> > };
> > ```
> 
> I updated to expo 48 and it works. Thanks @bladey @pors !!

add to file ? where the file please help me

**Comment by matiast02** [comment]
@rinaldycodes yo need to create a webpack.config.js, you can do it with this command: ```npx expo customize webpack.config.js```
also here is the official docs: https://docs.expo.dev/guides/customizing-webpack/

**Comment by rinaldycodes** [comment]
> @rinaldycodes yo need to create a webpack.config.js, you can do it with this command: `npx expo customize webpack.config.js` also here is the official docs: https://docs.expo.dev/guides/customizing-webpack/

i got error 

createExpoWebpackConfigAsync is not a function
TypeError: createExpoWebpackConfigAsync is not a function
    at module.exports (C:\projects\react-native\bark-sys\node_modules\@expo\webpack-config\webpack.config.js:6:24)
    at module.exports (C:\projects\react-native\bark-sys\webpack.config.js:4:24)
    at loadConfigAsync (C:\Users\rinal\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\src\Webpack.ts:546:22)
    at Object.startAsync (C:\Users\rinal\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\src\Webpack.ts:178:24)
    at startWebpackAsync (C:\Users\rinal\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\src\start\startAsync.ts:58:22

**Comment by matiast02** [comment]
@rinaldycodes I think that this can happen if you have a mismatch between the version of the @expo/webpack-config package you have installed and the version of Expo you are using. Try to delete node_module folder and reinstall dependencies: npm install
