### ISSUE TITLE
[expo-updates] Request network failed after successful checkForUpdateAsync --> fetchUpdateAsync --> reloadAsync

### ISSUE THREAD

**Issue by eightyfive** [expo/expo#21709]
### Minimal reproducible example

TODO

### Summary

* When I install my build (`distribution: "internal"`) on my phone, the app works as expected
* If I push an Update, I am able to `checkForUpdateAsync --> fetchUpdateAsync --> reloadAsync` (I did put `Alert`s along the way)
* The Update seems to be applied cause I dump the `Updates.updateId` and it shows latest.
* However, as soon as an update is applied, the app fails (not crash) with the following `TypeError` below
* If I build another identical build, the error is gone, so I guess this is related to App updates

```
TypeError address at /var/mobile/Containers/Data/Application/F0C470FC-33F3-40F4-BF44-1B19D4322C07/Library/Application Support/.expo-internal/f51b437b927a7423c9b49da8d05c9d46.bundle:1

Network request failed
``` 

Before I go with putting together a minimal reproducible example I want to make sure I am not missing anything obvious.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2022.08.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.8.0
      expo-cli: 6.3.2
    Expo Workflow: managed
```

**Comment by eightyfive** [comment]
**Follow up**

So this was NOT related to `expo-updates` but more to EAS Update process in general.

Apparently when publishing an update, you _must_ [specify your `process.env` variables manually](https://docs.expo.dev/eas-update/environment-variables/#setting-and-getting-environment-variables-when-publishing-an-update) (as opposed to `eas build` where it's done automatically via `eas.json`):

```bash
APP_ENV="staging" eas update --branch staging --platform ios --message "Test EAS updates Bugsnag source maps"
```

So in my case, since there was no `process.env.APP_ENV` specified in my patch update, my app logic was defaulting to `http://127.0.0.1/api` 🤦 

Hope this helps.

**Comment by LovesWorking** [comment]
> **Follow up**
> 
> So this was NOT related to `expo-updates` but more to EAS Update process in general.
> 
> Apparently when publishing an update, you _must_ [specify your `process.env` variables manually](https://docs.expo.dev/eas-update/environment-variables/#setting-and-getting-environment-variables-when-publishing-an-update) (as opposed to `eas build` where it's done automatically via `eas.json`):
> 
> APP_ENV="staging" eas update --branch staging --platform ios --message "Test EAS updates Bugsnag source maps"
> So in my case, since there was no `process.env.APP_ENV` specified in my patch update, my app logic was defaulting to `http://127.0.0.1/api` 🤦
> 
> Hope this helps.

omg thank you so much.
