### ISSUE TITLE
48.0.7 Crash on run Android

### ISSUE THREAD

**Issue by hamdij0maa** [expo/expo#21711]
### Minimal reproducible example

just upgrade to 48.0.7 on Android

### Summary

just upgrade to 48.0.7 on Android and the app will crash on first run

### Environment

Android, Bareflow latest RN,

**Comment by jh0ng** [comment]
Up
Same problem

Error from logcat:

```
java_vm_ext.cc:594] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception expo.modules.kotlin.exception.MissingTypeConverter: Cannot find type converter for 'expo.modules.kotlin.Promise'.
java_vm_ext.cc:594]   at expo.modules.kotlin.types.TypeConverter expo.modules.kotlin.types.TypeConverterProviderImpl.obtainTypeConverter(kotlin.reflect.KType) (TypeConverterProvider.kt:116)
java_vm_ext.cc:594]   at expo.modules.kotlin.types.TypeConverter expo.modules.kotlin.types.AnyType$converter$2.invoke() (AnyType.kt:10)
java_vm_ext.cc:594]   at java.lang.Object expo.modules.kotlin.types.AnyType$converter$2.invoke() (AnyType.kt:9)
java_vm_ext.cc:594]   at java.lang.Object kotlin.SynchronizedLazyImpl.getValue() (LazyJVM.kt:74)
java_vm_ext.cc:594]   at expo.modules.kotlin.types.TypeConverter expo.modules.kotlin.types.AnyType.getConverter() (AnyType.kt:9)
```

**Comment by segicm** [comment]
Any news on this? I have the same problem.

**Comment by SimenB** [comment]
This issue is closed due to missing reproduction - doubtful any Expo maintainers will look at it. So I suggest opening a new issue with a reproduction.

For my own project, I just downgraded to 48.0.6, which works fine for now.

**Comment by GregAtFramework** [comment]
Downgrading to 48.0.6 did not work for me. This started happening without any meaningful changes to our project.

**Comment by GregAtFramework** [comment]
Comparing gradlew output from successful and failing eas builds, the most obvious difference is a change in version of `expo-modules-core` - moving from 1.2.4 to 1.2.5. (It is set in yarn.lock to 1.2.3.)

Could be a complete red-herring though.

I've also tried to create a minimal reproduction, but no success so far.

**Comment by TomasSestak** [comment]
> Comparing gradlew output from successful and failing eas builds, the most obvious difference is a change in version of `expo-modules-core` - moving from 1.2.4 to 1.2.5. (It is set in yarn.lock to 1.2.3.)
> 
> Could be a complete red-herring though.
> 
> I've also tried to create a minimal reproduction, but no success so far.

thats exactly it

**Comment by GregAtFramework** [comment]
Is everyone affected using `expo-media-library`? 

The play store reports the error like this:
>Exception com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get for prop 'ExpoMediaLibrary': expo.modules.kotlin.exception.MissingTypeConverter: Cannot find type converter for 'expo.modules.kotlin.Promise'., js engine: hermes, stack:

**Comment by fbdtemme** [comment]
I can confirm. Reverting to `expo-modules-core 1.2.4` works. I am using `expo-media-library` as well.

**Comment by TomasSestak** [comment]
Also using expo-media-library

**Comment by segicm** [comment]
**Removing the `expo-media-library` package from the project appears to have resolved the issue.**

There may be an underlying problem with the package that requires attention from the Expo team. 
We should create a minimal reproducible example so the Expo team can resolve this.

**Comment by markomatic** [comment]
Setting `resolutions` to `"expo-modules-core": "1.2.4"` works for now if you still want to use `expo-media-library`.

**Comment by GregAtFramework** [comment]
When `eas build` runs `expo prebuild` then this sets expo-modules-core to the latest version (i.e. the unwanted 1.2.5).

You can work around this behaviour by adding the following to `package.json`  
```
"scripts": {
  "eas-build-post-install": "git checkout -- package.json yarn.lock && yarn install && expo prebuild --clean --skip-dependency-update expo,expo-modules-core"
}
```

This re-runs `expo prebuild` but without overridding the version of expo and expo-modules-core.

**Comment by spencercarli** [comment]
Running into the same issue with `expo-media-library`.

Minimal repro: https://github.com/spencercarli/ExpoMediaLibBug

**Comment by lc3t35** [comment]
thank you @spencercarli , why is this issue closed ?

**Comment by lc3t35** [comment]
> Setting `resolutions` to `"expo-modules-core": "1.2.4"` works for now if you still want to use `expo-media-library`.

@markomatic can you please explain where to add resolutions : I've tried in both main package.json and in expo-media-library without success :(

**Comment by lagoasoft-yagosantos** [comment]
I have the same error here, I have tried the solution of @markomatic but it didn't work

**Comment by markomatic** [comment]
> I have the same error here, I have tried the solution of @markomatic but it didn't work

What I have in my root package json is:
```
{
  "dependencies": {
    "expo": "^48.0.0", // <-- this will resolve to 48.0.7
    "expo-media-library": "~15.2.2"
  },
  "resolutions": {
    "expo-modules-core": "1.2.4"
  }
}
```

Just to clarify, `resolutions` field is `yarn` capability. If you are using `npm` it **will not work** and you will have to find equivalent to `resolutions` for `npm`.

**Comment by markomatic** [comment]
> thank you @spencercarli , why is this issue closed ?

This issue was auto-closed right after creation, because it was missing an example. There is duplicate issue that has an example and is still open https://github.com/expo/expo/issues/21723

**Comment by lagoasoft-yagosantos** [comment]
> Just to clarify, `resolutions` field is `yarn` capability. If you are using `npm` it **will not work** and you will have to find equivalent to `resolutions` for `npm`.

Sorry, is working fine now, I have added the expo-modules-core: 1.2.4 to the package.json dependencies list, and now it worked, thanks

**Comment by markomatic** [comment]
Latest report is that updating expo-media-library to 15.2.3 will resolve this issue.

**Comment by pratik8442** [comment]
updating package.json did not work for me I am using yarn.
` "resolutions": {
    "expo-modules-core": "1.2.4"
  }`
  Is there any solution?

**Comment by pratik8442** [comment]
I am not using `expo-media-library` but still, i installed the package with the given version but still, the issue is same.
WIll there be any update to fix this?
This issue is occurring only on iOS

**Comment by markomatic** [comment]
@pratik8442 that is probably unrelated to this issue considering it is titled that crash is happening on Android. I would suggest opening new issue if crash is happening on iOS for you.
