### ISSUE TITLE
web server failed : [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated.

### ISSUE THREAD

**Issue by patricekaratchentzeff** [expo/expo#21728]
### Summary

Description

Hi,

I have followed the official doc for setting up the react native with expo:

https://reactnative.dev/docs/environment-setup

I work under Linux Mint 21.1

I try many things, but all fail with the same error : web server can't run with the message:

```
(node:931142) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:931142) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use the async 'start' or 'startCallback' method.
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: spawn galeon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn galeon',
  path: 'galeon',
  spawnargs: [ 'http://localhost:19006' ]
}

Node.js v19.7.0
```

I tried all the version of node I could with the same result. I tried npx and yarn too :(

I saw that the problem has been identified here

https://github.com/heartexlabs/label-studio-frontend/commit/ded728c002d510d00d386b5cb5fc84feb977dbad

and I understand the problem (to permute args), but I can't success by installing the good solution. How to fix it properly by installing via npx or yarn?

Thanks,

### SDK Version

48

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.1 (Vera)
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.7.0 - /usr/bin/node
      npm: 9.5.0 - /usr/bin/npm
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1
      expo: ~48.0.6 => 48.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

### Minimal reproducible example

Steps to reproduce

By following the official doc:

for instance,

```
% npx create-expo-app project
% cd project
% npx expo install react-native-web@~0.18.10 react-dom@18.2.0 "@expo/webpack-config@^18.0.1"
% npx expo start
```
then active web server
Snack, code example, screenshot, or link to a repository

```
% npm run web

> project@1.0.0 web
> expo start --web

Starting project at /home/pk/dev/project
Starting Metro Bundler
Starting Webpack on port 19006 in development mode.
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █   █▄ ▀▄▀█ ▄▄▄▄▄ █
█ █   █ █ ▀▄ █▀█ ▄█ █   █ █
█ █▄▄▄█ █▀██▀▀▄▀▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀▄█ █ █▄█▄▄▄▄▄▄▄█
█▄ ▀█▄▄▄██▀▀▄▀█▄ ███ ▀▄▄ ▄█
█▄▄▄▄▄ ▄▄██▀ ▄▄█ ▀▀ █▄  ▀██
█▀█ ▀ ▀▄▄██▄█▄▀▄▀▄▀▄▀▀▄ ▀██
███ █▄▄▄▄ ▀▀█▀█▀▄▄▄█▄▀ ▀███
█▄▄▄██▄▄█▀▀▄▄ █▄▄ ▄▄▄ ▀ ▄▄█
█ ▄▄▄▄▄ █▀▄▄ ██▀▀ █▄█ ▀▀███
█ █   █ █▄▄ ▀▀▀▄█▄▄ ▄▄▀ ▀▀█
█ █▄▄▄█ █▀██ ███▄██▄▀█▀▀ ██
█▄▄▄▄▄▄▄█▄█████▄████▄▄▄▄▄▄█

› Metro waiting on exp://192.168.1.103:19000
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:19006

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands
```
I press w here

```
Logs for your project will appear below. Press Ctrl+C to exit.
(node:931142) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:931142) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use the async 'start' or 'startCallback' method.
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: spawn galeon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn galeon',
  path: 'galeon',
  spawnargs: [ 'http://localhost:19006' ]
}

Node.js v19.7.0
```

Notice that the android part run well.

**Comment by satheshsat** [comment]
same here on node.js 18.15.0

**Comment by Jytesh** [comment]
Same here

**Comment by boutmansb** [comment]
I'm having the same issue on node version 18

**Comment by Gab1988** [comment]
Same here node version 16.16.0

**Comment by imckain** [comment]
Same here, node 18.15.0

**Comment by singh-sukhmanjit** [comment]
Am facing same issue with node v18.15.0. Web app runs after giving the warning.

**Comment by syahbes** [comment]
same here
node : v16.18.1
"dependencies": {
    "@expo/config-plugins": "^6.0.1",
    "@expo/webpack-config": "^18.0.1",
    "expo": "~48.0.15",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.7",
    "react-native-web": "~0.18.10"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "webpack-dev-server": "^4.13.3"
  },

**Comment by egecanyldrm** [comment]
I just downgrade expo version to expo : "~47.0.14", and it's worked, i think it's about new expo version is not stable yet

**Comment by syahbes** [comment]
> I just downgrade expo version to expo : "~47.0.14", and it's worked, i think it's about new expo version is not stable yet 

Thank you for your answer.  I will try too..
How do you downgrade an existing app ?

Change the "dependencies": {
And do npm install ?

**Comment by egecanyldrm** [comment]
Sure change expo version in package.json and run the yarn/npm install, after install run that command in order 
-  `npm i -g eas-cli`
-  expo-cli doctor ( that command will show you new versions of dependcies and it will be updated )

**Comment by syahbes** [comment]
Thanks 😊

**Comment by syahbes** [comment]
> * expo-cli doctor

that did not worked for me 🙁😭 after npm i , and doctor
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

Didn't find any issues with the project!

got this errors : 
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'mimeTypes'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'mimeTypes'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
    at validate (C:\Users\C5336083\codes\surveyApp\node_modules\webpack-dev-server\node_modules\schema-utils\dist\validate.js:129:11)
    at new Server (C:\Users\C5336083\codes\surveyApp\node_modules\webpack-dev-server\lib\Server.js:256:5)
    at WebpackBundlerDevServer.startImplementationAsync (C:\Users\C5336083\codes\surveyApp\node_modules\@expo\cli\build\src\start\server\webpack\WebpackBundlerDevServer.js:226:25)
    at async WebpackBundlerDevServer.startAsync (C:\Users\C5336083\codes\surveyApp\node_modules\@expo\cli\build\src\start\server\BundlerDevServer.js:88:24)
    at async DevServerManager.startAsync (C:\Users\C5336083\codes\surveyApp\node_modules\@expo\cli\build\src\start\server\DevServerManager.js:135:13)
    at async KeyPressHandler.onPressAsync [as onPress] (C:\Users\C5336083\codes\surveyApp\node_modules\@expo\cli\build\src\start\interface\startInterface.js:183:25)
    at async ReadStream.KeyPressHandler.handleKeypress (C:\Users\C5336083\codes\surveyApp\node_modules\@expo\cli\build\src\start\interface\KeyPressHandler.js:43:17)

**Comment by erisvaldojunior** [comment]
Same issue with Expo SDK 48, brand new project. Followed the official doc.

**Comment by Munkyfoot** [comment]
I fixed it by adding `"bundler": "metro"` to the app.json.

`{
  "expo": {
    //...
    "web": {
      "bundler": "metro",
      //...
    }
  }
}`

**Comment by jaredmez** [comment]
> 

worked for me after upgrading to sdk 48 on node 18.16.0

**Comment by jaredmez** [comment]
> > I fixed it by adding "bundler": "metro" to the app.json.

{ "expo": { //... "web": { "bundler": "metro", //... } } }
> 
> worked for me after upgrading to sdk 48 on node 18.16.0

**Comment by Munkyfoot** [comment]
> > I fixed it by adding `"bundler": "metro"` to the app.json.
> 
> > 
> 
> > `{ "expo": { //... "web": { "bundler": "metro", //... } } }`
> 
> 
> 
> I have tested the 19.9.0, but it is still broken. On which version do you fix it?
> 
> 
> 
> Thanks in any case,

I'm using Node 18.16 and Expo 48.

**Comment by patricekaratchentzeff** [comment]
> > > I fixed it by adding `"bundler": "metro"` to the app.json.
> > 
> > 
> > > 
> > 
> > 
> > > `{ "expo": { //... "web": { "bundler": "metro", //... } } }`
> > 
> > 
> > I have tested the 19.9.0, but it is still broken. On which version do you fix it?
> > Thanks in any case,
> 
> I'm using Node 18.16 and Expo 48.

OK, it works nice now. Still have the warning message.

You can close the issue. Thanks a lot.

**Comment by jeromeabel** [comment]
> I fixed it by adding `"bundler": "metro"` to the app.json.
> 
> `{ "expo": { //... "web": { "bundler": "metro", //... } } }`

Works for me too. Thanks!

**Comment by smwq** [comment]
> I fixed it by adding `"bundler": "metro"` to the app.json.
> 
> `{ "expo": { //... "web": { "bundler": "metro", //... } } }`

@Munkyfoot Hey, where did you find this fix?

I also faced the same web server deprecated warning after updating to expo 48 and also some warning in react-native-reanimated and react-native-paper. 

![image](https://github.com/expo/expo/assets/8836421/55b1510d-b20d-43ea-a53d-d38312ea6cf2)
![image](https://github.com/expo/expo/assets/8836421/1d3fc3a5-c13b-4c82-81e9-0aeb62210e7d)

I tried your provided fix and it worked to remove all warnings. It started working without any warnings again.

But after few hours, I was getting react-native-reanimated export namespace error.
[https://github.com/software-mansion/react-native-reanimated/issues/3364](url)

![image](https://github.com/expo/expo/assets/8836421/84f74f24-28e2-4425-aab6-22afda52d140)

So, I tried the solution provided in that issue to add @babel/plugin-proposal-export-namespace-from and insert in babel.config.js plugin array and the error was fixed. One user also reported that adding this plugin fixes the error but may hide some runtime errors.

Is anyone else also facing these issues after updating to expo 48?

**Comment by Munkyfoot** [comment]
> > I fixed it by adding `"bundler": "metro"` to the app.json.
> > `{ "expo": { //... "web": { "bundler": "metro", //... } } }`
> 
> @Munkyfoot Hey, where did you find this fix?
> 
> I also faced the same web server deprecated warning after updating to expo 48 and also some warning in react-native-reanimated and react-native-paper.
> 
> ![image](https://user-images.githubusercontent.com/8836421/248776755-55b1510d-b20d-43ea-a53d-d38312ea6cf2.png) ![image](https://user-images.githubusercontent.com/8836421/248777061-1d3fc3a5-c13b-4c82-81e9-0aeb62210e7d.png)
> 
> I tried your provided fix and it worked to remove all warnings. It started working without any warnings again.
> 
> But after few hours, I was getting react-native-reanimated export namespace error. [https://github.com/software-mansion/react-native-reanimated/issues/3364](url)
> 
> ![image](https://user-images.githubusercontent.com/8836421/248778682-84f74f24-28e2-4425-aab6-22afda52d140.png)
> 
> So, I tried the solution provided in that issue to add @babel/plugin-proposal-export-namespace-from and insert in babel.config.js plugin array and the error was fixed. One user also reported that adding this plugin fixes the error but may hide some runtime errors.
> 
> Is anyone else also facing these issues after updating to expo 48?

@smwq Please see my edited post. I discovered this possible solution by comparing to another project where I was not receiving the warning and adding the missing line to `app.json`. This may be the incorrect way to resolve the warning, but I have been unable to find an "official" solution.

**Comment by Leonardocezar** [comment]
I was facing the same error with expo sdk 48 bare workflow.

I fixed it using the following code inside my webpack.config.js

```

const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  config.module.rules.forEach(rule => {
    if (rule.oneOf instanceof Array) {
      rule.oneOf[rule.oneOf.length - 1].exclude = [/\.(js|mjs|jsx|cjs|ts|tsx)$/, /\.html$/, /\.json$/]
    }
    return rule
  })

  return config;
};
```

**Comment by sohretturaman** [comment]
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  config.module.rules.forEach(rule => {
    if (rule.oneOf instanceof Array) {
      rule.oneOf[rule.oneOf.length - 1].exclude = [/\.(js|mjs|jsx|cjs|ts|tsx)$/, /\.html$/, /\.json$/]
    }
    return rule
  })

  return config;
};   


"The code worked for me, and I also followed the steps outlined in the document." 
https://webpack.js.org/guides/getting-started/
in addition https://necolas.github.io/react-native-web/docs/installation/
you can see  the required steps to install react native web package, there is no enough information in expo web doc.
(I didn't open a react project, executed the native app on web)

I hope it helps you, best luck :)
