### ISSUE TITLE
Flash not turning/remaining on when recordAsync is called on iOS

### ISSUE THREAD

**Issue by shrihari1999** [expo/expo#21749]
### Minimal reproducible example

https://snack.expo.dev/@shrihari1999/a1d2a2

### Summary

**Affected platforms**: iOS

**Expected Behavior**: Camera flash should be turned/remain on when recording a video

**Actual Behavior**: For FlashMode.on, flash remains off when recording starts. For FlashMode.flash, flash turns off when recording starts.

Everything works fine on android.

I came across 2 different issues, unfortunately they have been closed (https://github.com/expo/expo/issues/16246) and (https://github.com/expo/expo/issues/6361). So i've decided to open a new one

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 16.17.0 - ~/.config/nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.config/nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.config/nvm/versions/node/v16.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    npmPackages:
      expo: ^48.0.4 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.1
    Expo Workflow: managed

**Comment by SrikrishnaParthasarathy** [comment]
Hi,has anyone found a fix, im having the same issue

**Comment by shrihari1999** [comment]
Can someone please help?

https://github.com/expo/expo/issues/6361 and https://github.com/expo/expo/issues/16246 are closed without a solution.

**Comment by ahmadelafify** [comment]
I'm also facing this issue.
