### ISSUE TITLE
[docs] Missing information in Facebook authentication

### ISSUE THREAD

**Issue by haochenuw** [expo/expo#21752]
### Summary

The section requires a channel-name parameter in yourscheme://expo-development-client/?url=https://u.expo.dev/[your-eas-build-project-id]?channel-name=[channel-name]. However, there's no information on where to obtain that channel name. 

The linked doc https://docs.expo.dev/development/development-workflows/#deep-linking-urls instructs to run eas channel:list to find a list of channels, but the command outputs nothing.

It is confusing why facebook authentication must be coupled with the concept of "channels", and the documentation says nothing about what they are or how to add a channel. 

### Link to the related docs page

https://docs.expo.dev/guides/facebook-authentication/

**Comment by JFFrancisco** [comment]
agreed, tried to follow both Facebook and Google Auth with the supplied documentation, and none of them work :/

**Comment by amandeepmittal** [comment]
Hi @haochenuw, sorry for the inconvenience caused. I understand we need to improve the section about deep linking as well as convey the same information in the Facebook Auth guide. Will be updating both documents soon.

To answer some of your questions:
- You can use the default channel name `main` as described in the deep linking URL section. Generally, each build profile is associated with a default channel for each branch for the build (this also helps when someone opts in to use EAS Update in future for their project where they are already using EAS Build, it helps EAS Update to identify which channel and branch to send the update when the update is available). For more information, I'd suggest taking at how EAS Update works: https://docs.expo.dev/eas-update/how-eas-update-works/#distributing-builds
- If you are not using EAS Update, you can set it to `main`

> The linked doc [docs.expo.dev/development/development-workflows/#deep-linking-urls](https://docs.expo.dev/development/development-workflows/#deep-linking-urls) instructs to run eas channel:list to find a list of channels, but the command outputs nothing.
- The Deep linking section doesn't recommend running `eas channel:list` command. The command is listed in the section prior to the deep linking one in which one has to enter the update URL manually. I guess, this might also sounds confusing in regards to development builds and have conveyed the info internally. We'll be looking to improve the way we communicate this info.

**Comment by amandeepmittal** [comment]
Hi @JFFrancisco, please let me know what are the issues you are facing with Google and/or Facebook auth guides. Feel free to open a new issue to elaborate on the pain points or areas that you find not clear. Happy to help!

**Comment by JayWilk** [comment]
Facebook authentication works for me following the guidance when running in expo go.

However, when running a development build or bare workflow using the example provided in the docs [here](https://docs.expo.dev/guides/facebook-authentication/#minimal-working-example), after authenticating with facebook it doesn't redirect me back to the app it just remains in an empty window.

i get a console log output from the console stating that i need to add the following url to my facebook redirects:

however, facebook won't allow such a url because it's not https...

It would appear i'm not the only person to suffer with this issue: 
https://github.com/expo/expo/issues/18533

**Comment by rigorcadiz** [comment]
I stumble upon this and noticed this confusing instruction too with Facebook Oauth, it says in the docs:

![image](https://github.com/expo/expo/assets/102206810/651b0a05-1941-42e7-8803-4c0858f59c5a)

But when you actually follow this scheme format, running `expo start --dev-client` gives you a warning that it's not a valid scheme.

**Linking found multiple possible URI schemes in your Expo config.
Using 'yourscheme'. Ignoring: fb1234567890, com.my.app.
Please supply the preferred URI scheme to the Linking API.**

**Comment by kimkong88** [comment]
> I stumble upon this and noticed this confusing instruction too with Facebook Oauth, it says in the docs:
> 
> ![image](https://user-images.githubusercontent.com/102206810/237743860-651b0a05-1941-42e7-8803-4c0858f59c5a.png)
> 
> But when you actually follow this scheme format, running `expo start --dev-client` gives you a warning that it's not a valid scheme.
> 
> **Linking found multiple possible URI schemes in your Expo config. Using 'yourscheme'. Ignoring: fb1234567890, com.my.app. Please supply the preferred URI scheme to the Linking API.**

Same issue. Also fb login comes back with "unsupported request". not sure where it went wrong.

**Comment by charlesfsl** [comment]
I, too, have been looking for documentation on how to specify the preferred URI scheme to the Linking API, but have not found that info. 

Searching this repo, just above where that warning is thrown there is [this comment](https://github.com/expo/expo/blob/e7d2fd440e3aeb5e3714f384ad15630bfebdcf41/packages/expo-linking/src/Schemes.ts#L174): 

```
  // When the native app id is defined, it'll be added to the list of schemes, for most
  // users this will be unexpected behavior and cause all apps to warn when the Linking API
  // is used without a predefined scheme. For now, if the native app id is defined, require
  // at least one more scheme to be added before throwing a warning.
  // i.e. `scheme: ['foo', 'bar']` (unimplemented functionality).
```

That sounds to me like expo is dynamically adding the `fb1234567890` scheme to the list of schemes instead of a developer needing to manually add it to the `app.json` as the FB auth docs describe.

**Comment by amandeepmittal** [comment]
Sorry for the inconvenience caused. We do support the array type for setting `scheme` in `app.json`. We've deprecated Facebook auth providers from `expo-auth-session` starting SDK 49. We recommend using a native library such as [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/).

We don't maintain this native library. However, we did write a short guide on what steps might be required to configure an Expo project: https://docs.expo.dev/guides/facebook-authentication/, when using these libraries. If you're creating a new app, Facebook has also changed the way how a developer app on Facebook's end is created. Please follow their instructions.

**Comment by lucasbasquerotto** [comment]
@amandeepmittal From what I looked, this means:

1. It's not required to add a facebook schema anymore;
2. The app must be published at Play Store (even if it's just a develompment app) to login with Facebook.
