### ISSUE TITLE
New builds crashing on Android for SDK 48

### ISSUE THREAD

**Issue by rafaelcanical** [expo/expo#21750]
### Summary

I made a build on 7th of March and it was working perfectly. Today I tried building the exact same commit and the apps are crashing on Android. Did anything changed lately? it works fine for lower versions of the SDK

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2
      expo: ^48.0.7 => 48.0.7
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.10
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare

### Minimal reproducible example

NA

**Comment by dmgcoding** [comment]
I'm experiencing this as well. I downgraded to 45 again and it worked. I was struggling for 2 days. Damn!

**Comment by jonjamz** [comment]
My Android app has also been crashing and I was able to narrow it down to use of expo-media-library. Not sure if this applies since you don't seem to be using that package, I really wonder what's going on here, very frustrating.

**Comment by rafaelcanical** [comment]
This comment helped me make it work: https://github.com/expo/expo/issues/21711#issuecomment-1470940218

It's something related with `expo-media-library` and `expo-modules-core`

**Comment by jonjamz** [comment]
@rafaelcanical Thank you for pointing me to that! I have tried overriding the `expo-modules-core` version as stated but am still getting the crash. Trying a new build now to see if that helps.

**Comment by jonjamz** [comment]
Ok great it works. Just had to rebuild.
