### ISSUE TITLE
Android: Video doesn't adapt to bandwidth if Implementation is ExoPlayer

### ISSUE THREAD

**Issue by normenster** [expo/expo#2177]
Expokit Project
 "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
   "detach": {
			"scheme": "expf36d8dd71a764167b8c72128a78cce63",
			"iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.6.8-sdk28.0.0-d3178d29-6e12-458b-bfeb-8b7538943b48.tar.gz",
			"androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.6.4-sdk28.0.0-9ba3198a-7d95-4769-9e16-178a37a70cae.tar.gz"
		},

I'm playing a HLS File (.m3u8) Everything works fine on iOS. On Android, bandwitch swichting doesn't happen, the video remains on the lowest quality. When changing `androidImplementation` to 'MediaPlayer', bandwitch switching works. Any Ideas? Is it maybe fixed in SDK 29 ?

**Comment by ide** [comment]
I don't think this was changed in SDK 29 (you can read the release notes to learn the significant things that changed).

**Comment by normenster** [comment]
Yes - but can you confirm that this bandwithMeter thing isn`t implemented? Or should it work?

**Comment by normenster** [comment]
@ide Any news on this one? I just want to know, if a m3u8 Manifest in Android Exoplayer Implementation should be adaptive to the clients bitrate, as it is on iOS and also in Android MediaPlayer Implementation.

**Comment by DracoBlue** [comment]
Any updates on this matter?

**Comment by marcusstenbeck** [comment]
I'm running into this issue as well, and setting `androidImplementation: "MediaPlayer"` comes with much more janky behavior. I'm no Java developer, but I looked into what might be the issue, and I see that the data source isn't receiving the bandwidth meter (or I can't figure out how that happens). Could that be the issue?

I'm not Java savvy enough to get this up and running myself, but maybe someone who know their way around can test it out?

https://github.com/expo/expo/blob/master/packages/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java#L85

Relevant blog post: https://medium.com/google-exoplayer/https-medium-com-google-exoplayer-simplified-bandwidth-meter-usage-17d8189f978b

**Comment by watchinharrison** [comment]
I'm also experiencing this issue, any attempt to use `androidImplementation` or an `.mpd` url fails also

**Comment by tsapeta** [comment]
Looks like this issue has been solved by #8380 so closing it 😉
