### ISSUE TITLE
[ImagePicker] exif data not working on android

### ISSUE THREAD

**Issue by Chrischuck** [expo/expo#21786]
### Minimal reproducible example

https://github.com/Chrischuck/expo-android-broken-exif

### Summary

In the above repo, add `exif-test.jpg` to your simulator or emulator

When you select the photo w/ image picker, see how ios has exif location data, but android does not.

It would be awesome if there is not quick fix to this if the original file url (not the generated hash) was included in the response of the picker. That way we could use our own exif reader library as a fall back.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.6 => 48.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    Expo Workflow: managed

**Comment by sameert89** [comment]
Having the same issue, geolocation data is absent. There should be a simpler fix to this.
