### ISSUE TITLE
Expo build failed / SDK 48

### ISSUE THREAD

**Issue by MylchenkoAlexandr** [expo/expo#21783]
### Summary

**Build failed** after update to SDK 48 (from SDK 46).
No any errors while application running in development mode.
Any help?

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "name": "eshka.client",
  "version": "1.0.4",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start --no-dev --minify",
    "develop": "expo start --clear",
    "build:android": "eas build --platform android",
    "build:apk": "eas build --platform android --profile stage",
    "build:ios": "eas build --platform ios"
  },
  "dependencies": {
    "@ant-design/react-native": "^5.0.0",
    "@expo/metro-config": "^0.5.2",
    "@expo/webpack-config": "^18.0.1",
    "@googlemaps/polyline-codec": "^1.0.28",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/netinfo": "9.3.7",
    "axios": "^0.27.2",
    "babel-plugin-inline-import": "^3.0.0",
    "base-64": "^1.0.0",
    "centrifuge": "2.7.6",
    "deprecated-react-native-prop-types": "^4.0.0",
    "eas-cli": "^3.7.2",
    "email-validator": "^2.0.4",
    "expo": "^48.0.0",
    "expo-app-loading": "~2.1.0",
    "expo-asset": "~8.9.1",
    "expo-camera": "~13.2.1",
    "expo-cli": "5.5.0",
    "expo-env-info": "^1.0.5",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-localization": "~14.1.1",
    "expo-location": "~15.1.1",
    "expo-status-bar": "~1.4.4",
    "expo-task-manager": "~11.1.1",
    "expo-tracking-transparency": "~3.0.3",
    "expo-updates": "~0.16.3",
    "http-status-codes": "^2.2.0",
    "i18n-js": "^4.2.0",
    "lodash": "^4.17.21",
    "md5": "^2.3.0",
    "moment": "^2.29.4",
    "patch-package": "^6.5.1",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.3",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.3.2",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal": "^13.0.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sortable-list": "^0.0.25",
    "react-native-svg": "13.4.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-svg-uri": "^1.2.3",
    "react-native-ultimate-listview": "^3.3.0",
    "react-native-web": "~0.18.11",
    "react-native-webview": "11.26.0",
    "react-redux": "^8.0.2",
    "react-router-native": "~6.3.0",
    "redux": "^4.2.0",
    "redux-saga": "^1.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@expo/metro-config": "^0.5.2",
    "@expo/webpack-config": "^18.0.1",
    "@types/lodash": "^4.14.182",
    "@types/react": "~18.0.27",
    "@types/react-native": "~0.69.1",
    "babel-plugin-inline-import": "^3.0.0",
    "react-native-svg-transformer": "^0.14.3",
    "typescript": "^4.9.4"
  },
  "private": true
}

### Environment

    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.5.2 => 0.5.2 
      @expo/webpack-config: ^18.0.1 => 18.0.1 
      expo: ^48.0.0 => 48.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.11 => 0.18.12 
    Expo Workflow: managed

### Reproducible demo

NA

### Stacktrace (if a crash is involved)

```
[stderr] /home/expo/workingdir/build/android/app/src/main/java/com/eshka2k34/client/MainActivity.java:19: error: package R does not exist
[stderr]     setTheme(R.style.AppTheme);
[stderr]               ^
[stderr] /home/expo/workingdir/build/android/app/src/main/java/com/eshka2k34/client/MainActivity.java:39: error: cannot find symbol
[stderr]     return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
[stderr] 
                                                  ^
[stderr]   symbol:   variable BuildConfig
[stderr]   location: class MainActivity
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/eshka2k34/client/MainApplication.java:26: error: cannot find symbol
[stderr]         return BuildConfig.DEBUG;
[stderr]                ^
[stderr]   symbol: variable BuildConfig
[stderr] /home/expo/workingdir/build/android/app/src/main/java/com/eshka2k34/client/MainApplication.java:45: error: cannot find symbol
[stderr]         return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
[stderr]                ^
[stderr]   symbol: variable BuildConfig
[stderr] /home/expo/workingdir/build/android/app/src/main/java/com/eshka2k34/client/MainApplication.java:50: error: cannot find symbol
[stderr]         return BuildConfig.IS_HERMES_ENABLED;
[stderr]                ^
[stderr]   symbol: variable BuildConfig
[stderr] /home/expo/workingdir/build/android/app/src/main/java/com/eshka2k34/client/MainApplication.java:63: error: cannot find symbol
[stderr]     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
[stderr]         ^
[stderr]   symbol:   variable BuildConfig
[stderr]   location: class MainApplication
[stderr] /home/expo/workingdir/build/android/app/src/main/java/com/eshka2k34/client/MainApplication.java:63: error: illegal parenthesized expression
[stderr]     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
[stderr]        ^
[stderr] /home/expo/workingdir/build/android/app/src/main/java/com/eshka2k34/client/MainApplication.java:67: error: cannot find symbol
[stderr]     ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
[stderr]     ^
[stderr]   symbol:   variable ReactNativeFlipper
[stderr]   location: class MainApplication
[stderr] 8 errors
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:compileReleaseJavaWithJavac'.
[stderr] > Compilation failed; see the compiler error output for details.
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] 2: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] java.lang.StackOverflowError (no error message)
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] * Get more help at https://help.gradle.org
[stderr] **BUILD FAILED in 5m 47s**
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 6 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
938 actionable tasks: 938 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

**Comment by hotaryuzaki** [comment]
same error here, after I upgraded from version 47.
i already followed all steps.

i have 7 errors, but i fixed 1 of them.

```
/home/amri/Documents/projects/reactnative/brambang.apps/brambang-react-native-2.0-48-dev/android/app/src/main/java/com/brambang/apps/MainApplication.java:26: error: cannot find symbol
        return BuildConfig.DEBUG;
               ^
  symbol: variable BuildConfig
/home/amri/Documents/projects/reactnative/brambang.apps/brambang-react-native-2.0-48-dev/android/app/src/main/java/com/brambang/apps/MainApplication.java:45: error: cannot find symbol
        return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
               ^
  symbol: variable BuildConfig
/home/amri/Documents/projects/reactnative/brambang.apps/brambang-react-native-2.0-48-dev/android/app/src/main/java/com/brambang/apps/MainApplication.java:50: error: cannot find symbol
        return BuildConfig.IS_HERMES_ENABLED;
               ^
  symbol: variable BuildConfig
/home/amri/Documents/projects/reactnative/brambang.apps/brambang-react-native-2.0-48-dev/android/app/src/main/java/com/brambang/apps/MainApplication.java:63: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
/home/amri/Documents/projects/reactnative/brambang.apps/brambang-react-native-2.0-48-dev/android/app/src/main/java/com/brambang/apps/MainApplication.java:63: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
/home/amri/Documents/projects/reactnative/brambang.apps/brambang-react-native-2.0-48-dev/android/app/src/main/java/com/brambang/apps/MainActivity.java:19: error: package R does not exist
    setTheme(R.style.AppTheme);
```

and here 1 error that i fixed in MainActivity.java, I changed it to the one from RN.
```
  // @Override
  // protected ReactActivityDelegate createReactActivityDelegate() {
  //   return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
  //       this,
  //       getMainComponentName(),
  //       // If you opted-in for the New Architecture, we enable the Fabric Renderer.
  //       DefaultNewArchitectureEntryPoint.getFabricEnabled(), // fabricEnabled
  //       // If you opted-in for the New Architecture, we enable Concurrent React (i.e. React 18).
  //       DefaultNewArchitectureEntryPoint.getConcurrentReactEnabled() // concurrentRootEnabled
  //       ));
  // }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new DefaultReactActivityDelegate(
        this,
        getMainComponentName(),
        // If you opted-in for the New Architecture, we enable the Fabric Renderer.
        DefaultNewArchitectureEntryPoint.getFabricEnabled(), // fabricEnabled
        // If you opted-in for the New Architecture, we enable Concurrent React (i.e. React 18).
        DefaultNewArchitectureEntryPoint.getConcurrentReactEnabled() // concurrentRootEnabled
        );
  }

is there any solution?

**Comment by JWesorick** [comment]
Getting same error here. Anyone find a solution?

**Comment by stberger3040** [comment]
I had the same problem. I had used `expo-cli` package in devDependencies. However, as stated in https://github.com/expo/expo-cli#readme , the cli is now included in the `expo` package.

So after uninstalling `expo-cli` it worked again

**Comment by 90dy** [comment]
Same error locally

**Comment by evinedz** [comment]
> I had the same problem. I had used `expo-cli` package in devDependencies. However, as stated in https://github.com/expo/expo-cli#readme , the cli is now included in the `expo` package.
> 
> So after uninstalling `expo-cli` it worked again

This solution worked
