### ISSUE TITLE
`expo-document-picker` file isn't readable with `expo-file-system` on Android.

### ISSUE THREAD

**Issue by hochdyl** [expo/expo#21792]
### Summary

The file selected with `DocumentPicker.getDocumentAsync` is not readable with `FileSystem.readAsStringAsync(pickerResult.uri)`

![Capture d’écran 2023-03-21 105801](https://user-images.githubusercontent.com/55688853/226573077-c607ffc7-2ae3-439e-8b07-c8672de44468.png)

I tried on my project, then on a brand new project with the command `npx create-expo-app my-app`

Searching deep into closed issues, I found this expo snack that reproduces exactly what I want to do and works: https://snack.expo.dev/@brents/load-document-as-base64-string (https://github.com/expo/expo/issues/18534)

### What platform(s) does this occur on?

Android

### SDK Version

48.0.8

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.1.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~48.0.6 => 48.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: managed
```

### Minimal reproducible example

Install a new expo project with the command `npx create-expo-app my-app`

Install the needed libraries :
`npx expo install expo-file-system`
`npx expo install expo-document-picker`

Copy and replace the content of your `App.js` with the following code :
```
import { StatusBar } from 'expo-status-bar';
import {Button, StyleSheet, View} from 'react-native';
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system";

export default function App() {
  return (
    <View style={styles.container}>
      <StatusBar style="auto" />
      <Button
        title="test"
        onPress={async () => {
          const pickerResult = await DocumentPicker.getDocumentAsync({
            copyToCacheDirectory: true,
          });

          if (pickerResult.type === 'cancel') {
            return; // bail out early if cancelled
          }

          await FileSystem.readAsStringAsync(pickerResult.uri, {
            encoding: FileSystem.EncodingType.Base64,
          })
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by hochdyl** [comment]
After testing on iOS, everything seems to work fine. So it is only on Android.

**Comment by karna419** [comment]
I am getting the same issue on both platforms. Occasionally.

**Comment by mxpengin** [comment]
I have the same problem on Android when testing on the expo go app. In IOS it works as expected.

**Comment by a-zen** [comment]
I also have the same issue as @VladSvyryd and can confirm that if I go back to expo 47 everything works. Also tested one more time and don't have any issues on ios.

**Comment by vitorbraga** [comment]
I also face the same issue with Android.
Any workaround?

**Comment by Minisaints** [comment]
I'm having the same issue too. Very easy to replicate and don't know any workarounds as of yet.

**Comment by hochdyl** [comment]
Several weeks after the creation of this issue, the problem **is still there**. 
Many of us have noticed it but no workaround has been found and @VladSvyryd comment describes the problem perfectly. 
Could someone take a look?

https://github.com/expo/expo/issues/21792#issuecomment-1477936830
> > After testing on iOS, everything seems to work fine. So it is only on Android.
> 
> Same Problem but with 'expo-image-manipulator' It works fine on iOS and Android **SDK 47** It works fine on iOS but Android tries to save images to the wrong path. **SDK 48**
> 
> iOS output after ` const compressedImage = await manipulateAsync( uri, [{ resize: { height: 400 } }], { compress: 0.3, format: SaveFormat.JPEG, } );` ![image](https://user-images.githubusercontent.com/22796608/226636911-c33bdc14-4a4f-498e-bbc1-ed9ca5e3bbe8.png)
> 
> Android output:
> 
> ![image](https://user-images.githubusercontent.com/22796608/226637137-84389d3a-dc31-425c-af7b-5869e60a1269.png)

**Comment by ronilmehta** [comment]
> > After testing on iOS, everything seems to work fine. So it is only on Android.
> 
> Same Problem but with 'expo-image-manipulator' It works fine on iOS and Android **SDK 47** It works fine on iOS but Android tries to save images to the wrong path. **SDK 48**
> 
> iOS output after ` const compressedImage = await manipulateAsync( uri, [{ resize: { height: 400 } }], { compress: 0.3, format: SaveFormat.JPEG, } );` ![image](https://user-images.githubusercontent.com/22796608/226636911-c33bdc14-4a4f-498e-bbc1-ed9ca5e3bbe8.png)
> 
> Android output:
> 
> ![image](https://user-images.githubusercontent.com/22796608/226637137-84389d3a-dc31-425c-af7b-5869e60a1269.png)

I see the same issue with `manipulateAsync` on Android13 after upgrading to SDK 48: Location 'file:///data/user/0/host.exp.exponent/cache/ImageManipulator/257e7cea-5b26-455f-ad29-4d4bdeb69c0a.jpg' isn't readable.

**Comment by gokselozgur5** [comment]
I am having the exact problem. Are there any solution or alternative yet?

**Comment by dhohmann** [comment]
I got the same issue, but with a little workaround i made it work.
_Note: I am using a different approach for web._

For the document selection I disabled the copying option as this does not work
```typescript
const documentSelection = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: false });
if (documentSelection.type === "cancel") {
    return;
}
````

With the uri provided by `documentSelection.uri` I am copying the file with the name (`documentSelection.name`) to a cache directory:
```typescript
const createCacheFile = async ({ name, uri }: CacheOptions) => {
    if (!(await getInfoAsync(cacheDirectory + "uploads/")).exists) {
        await makeDirectoryAsync(cacheDirectory + "uploads/");
    }
    const cacheFilePath = cacheDirectory + "uploads/" + name;
    await copyAsync({ from: uri, to: cacheFilePath });
    return cacheFilePath;
}
```
For the upload process I use the newly created file uri:
```typescript
 const file = await createCacheFile(cacheOptions);
 const options: FileSystemUploadOptions = {
     httpMethod: "POST",
     uploadType: FileSystemUploadType.MULTIPART,
     fieldName: "file",
     headers: headers,
};
await uploadAsync(this.transferStorage.uploadData.url, file, options)
```

This makes the code run on an Android simulator with SDK 48.

**Comment by datsfilipe** [comment]
@dhohmann solution worked for me, thanks! (using it on Android here).

**Comment by gokselozgur5** [comment]
```javascript

    const pickAndReadDocument = async () => {

        // Pick a document
        const result = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: false });
        if (result.type !== 'success') {

        }
        else{
            console.log('Document picked:', result.uri);
            if (!(await getInfoAsync(cacheDirectory + "uploads/")).exists) {
                await makeDirectoryAsync(cacheDirectory + "uploads/");
            }
            const cacheFilePath = cacheDirectory + "uploads/" + result.name;
            await copyAsync({ from: result.uri, to: cacheFilePath });
            console.log(cacheFilePath, 'cacheFilePath');
            const info = await getInfoAsync(cacheFilePath);
            console.log(info, 'info');


            const options: FileSystemUploadOptions = {
                httpMethod: "POST",
                uploadType: FileSystemUploadType.MULTIPART,
                fieldName: "file",
           };
           await uploadAsync('https://config.test', cacheFilePath, options)

        }

    }
```

I am using these codes but it gives me the error

```
[Unhandled promise rejection: Error: /data/user/0/host.exp.exponent/cache/ExperienceData/%40sampexpo%2Flogin-page/uploads/somefile.p12: open failed: EISDIR (Is a directory)]
at http://192.168.88.67:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in _createSuperInternal
at node_modules/expo-modules-core/build/errors/CodedError.js:10:8 in constructor
```

**Comment by hochdyl** [comment]
> I got the same issue, but with a little workaround i made it work. _NOTE: I am using a completely different approach for web._ _NOTE: The code here is tested with Android and no other platform!!!_
> 
> For the **document selection** I disabled the copying option as this does not work
> 
> ```ts
> const documentSelection = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: false });
> if (documentSelection.type === "cancel") {
>     return;
> }
> ```
> 
> With the uri provided by `documentSelection.uri` I am copying the file with the name (`documentSelection.name`) to a **cache directory**:
> 
> ```ts
> import { cacheDirectory, copyAsync, getInfoAsync, makeDirectoryAsync, uploadAsync } from 'expo-file-system'
> 
> const createCacheFile = async ({ name, uri }: CacheOptions) => {
>     if (!(await getInfoAsync(cacheDirectory + "uploads/")).exists) {
>         await makeDirectoryAsync(cacheDirectory + "uploads/");
>     }
>     const cacheFilePath = cacheDirectory + "uploads/" + name;
>     await copyAsync({ from: uri, to: cacheFilePath });
>     return cacheFilePath;
> }
> ```
> 
> For the **upload process** I use the newly created file uri:
> 
> ```ts
>  const file = await createCacheFile(cacheOptions);
>  const options: FileSystemUploadOptions = {
>      httpMethod: "POST",
>      uploadType: FileSystemUploadType.MULTIPART,
>      fieldName: "file",
>      headers: headers,
> };
> await uploadAsync(uploadUrl, file, options)
> ```
> 
> This makes the code run on an Android simulator with SDK 48.

Great workaround, it works perfectly, thanks !

I let this issue open until we have a merge request on the official repo tho.

**Comment by vadakr** [comment]
I'd been waiting for a solution since early Apr, so thank you @dhohmann!

Interestingly, I cannot reproduce the original issue anymore. When I initially ran into this back on Apr 2, my (relevant) package versions were:

- expo 48.0.4
- expo-document-picker 11.2.2

As of today, expo is at 48.0.17 and expo-document-picker is still at 11.2.2.

Something in between 48.0.4 and 48.0.17 seems to be have addressed it.

**Comment by vadakr** [comment]
> > I'd been waiting for a solution since early Apr, so thank you @dhohmann!
> > Interestingly, I cannot reproduce the original issue anymore. When I initially ran into this back on Apr 2, my (relevant) package versions were:
> > 
> > * expo 48.0.4
> > * expo-document-picker 11.2.2
> > 
> > As of today, expo is at 48.0.17 and expo-document-picker is still at 11.2.2.
> > Something in between 48.0.4 and 48.0.17 seems to have addressed it.
> 
> I've just tried again to reproduce the problem on a new project and it's still there for me.
> 
> Here are my dependencies from the package.json file
> 
> ```
> "expo": "~48.0.18",
> "expo-status-bar": "~1.4.4",
> "react": "18.2.0",
> "react-native": "0.71.8",
> "expo-file-system": "~15.2.2",
> "expo-document-picker": "~11.2.2"
> ```

I can only reproduce this when using Expo Go in a development environment, but cannot reproduce this when the app is built natively using Expo Build/Update.

**Comment by aleqsio** [comment]
I've tested the reproduction (with `pickerResult.assets[0].uri` instead since it now returns an array):

- On Android it works now on SDK49 (coming soon)
- On iOS it didn't work for me so I fixed it in https://github.com/expo/expo/pull/23102

**Comment by reymundonahuel** [comment]
> ```ts
> const createCacheFile = async ({ name, uri }: CacheOptions) => {
>     if (!(await getInfoAsync(cacheDirectory + "uploads/")).exists) {
>         await makeDirectoryAsync(cacheDirectory + "uploads/");
>     }
>     const cacheFilePath = cacheDirectory + "uploads/" + name;
>     await copyAsync({ from: uri, to: cacheFilePath });
>     return cacheFilePath;
> }
> ```

Man, you really save me after days of investigations
That's my code (just for reference)
` const displayDocumentPicker = async () => {
    try {
      const doc = await DocumentPicker.getDocumentAsync({
        copyToCacheDirectory: false,
        type: "text/comma-separated-values",
        multiple: false,
      });
      if (doc.type == "success") {
        const cached = await createCacheFile(doc);
        const fileContent = await FileSystem.readAsStringAsync(cached);
        const results = Papa.parse(fileContent, {
          header: true,
          skipEmptyLines: true,
        });
        console.log(results.data);
      } else if (doc.type == "cancel") {
        console.error("Accion cancelada por el usuario");
      }
    } catch (error) {
      console.error(error);
    }
  };

  const createCacheFile = async ({ name, uri }) => {
    if (
      !(await FileSystem.getInfoAsync(FileSystem.cacheDirectory + "uploads/"))
        .exists
    ) {
      await FileSystem.makeDirectoryAsync(
        FileSystem.cacheDirectory + "uploads/"
      );
    }
    const cacheFilePath = FileSystem.cacheDirectory + "uploads/" + name;
    await FileSystem.copyAsync({ from: uri, to: cacheFilePath });
    return cacheFilePath;
  };`

**Comment by prisius** [comment]
> I've tested the reproduction (with `pickerResult.assets[0].uri` instead since it now returns an array):
> 
>     * On Android it works now on SDK49 (coming soon)
> 
>     * On iOS it didn't work for me so I fixed it in [Fix DocumentPicker copy to cache on iOS #23102](https://github.com/expo/expo/pull/23102)

I have tried every possible solution, it does not work on Android. Everytime i try to pick an element with the document picker, it does not grab the element.

**Comment by marctorsoc** [comment]
> I got the same issue, but with a little workaround i made it work. _NOTE: I am using a completely different approach for web._ _NOTE: The code here is tested with Android and no other platform!!!_

Could you please explain what's your approach for web? @dhohmann . I cannot make work `expo-document-picker` and `expo-file-system` together since the latter does not support web

**Comment by dhohmann** [comment]
> > I got the same issue, but with a little workaround i made it work. _NOTE: I am using a completely different approach for web._ _NOTE: The code here is tested with Android and no other platform!!!_
> 
> Could you please explain what's your approach for web? @dhohmann . I cannot make work `expo-document-picker` and `expo-file-system` together since the latter does not support web

@marctorsoc _Please keep in mind that as some time has passed since I had worked with the code I do not remember, if the code below worked as intended.

In the [documentation](https://docs.expo.dev/versions/latest/sdk/document-picker/#documentpickerresult) it states that you receive a file object when the program runs in a web browser. This object can automatically used for uploading.

```typescript
if (Platform.OS === "web") {
    if (typeof file === "string") {
        throw new Error("On web we need to provide a File object")
    }
    const requestData = new FormData();
    requestData.append('file', file);

    const options: RequestInit = {
        method: "POST",
        body: requestData,
        headers: headers
    };

    const response = await fetch(url, options);
    // TODO Do something with the response
}
```

If you need more help, I would advice you to open a separate ticket with a working example so that other people can see your use case.

**Comment by marctorsoc** [comment]
thanks for your response @dhohmann . I wrote the issue in Discord, since it seems that GH is only for bugs https://forums.expo.dev/t/expo-document-picker-how-to-read-the-file-on-web/74740. Please LMK if not clear my objective. I understand what you're doing but I don't intend to send the upload the data elsewhere, just to store it into memory to use it downstream

**Comment by JackNgulale** [comment]
import React, { useState } from 'react';
import { View, Text, TouchableOpacity, Image, Platform } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system';
import axios from 'axios';

type DocumentPickerProps = {
  onSelectedDocument: (fileData: object) => void;
};

export default function DocumentPickerComponent({
  onSelectedDocument,
}: DocumentPickerProps) {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);

  const selectDocument = async () => {
    try {
      const docRes = await DocumentPicker.getDocumentAsync({
        type: ['image/*', 'application/pdf', 'application/docx', 'application/doc', 'application/csv'],
        copyToCacheDirectory: true,
      });

      const assets = docRes.assets;
      if (!assets) return;

      const file = assets[0];

      const content = await FileSystem.readAsStringAsync(file.uri, {
        encoding: FileSystem.EncodingType.Base64,
      });

      const normalizedFile = { ...file, uri: content };
      console.log(normalizedFile);
      onSelectedDocument(normalizedFile);

      const token = '238|h22xD1JXPJW49vFHcaiDIKi8xdWygKR5cubeOoOT2fa74a7e';

      await axios.post(
        'http://10.1.15.243:8000/api/ticket/cadastrarTicket',
        {
          file: {
            uri: normalizedFile.uri,
            type: normalizedFile.mimeType,
            name: normalizedFile.name,
            content: content,
          },
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
        }
      );

      console.log('Requisição enviada com sucesso');
    } catch (error) {
      console.log('Error while selecting file or sending request: ', error);
    }
  };

  return (
    <View style={{ alignSelf: 'center' }}>
      <TouchableOpacity onPress={selectDocument}>
        <Text>Carregar anexo</Text>
      </TouchableOpacity>
    </View>
  );
}


right, it worked for me, thanks, you just convert uri to base64, it worked for ios and android
