### ISSUE TITLE
Audio [webm] support

### ISSUE THREAD

**Issue by AbdallaEmadEldinAbdalla** [expo/expo#21805]
### Minimal reproducible example

Use any .webm audio and it will not work

### Summary

I have tried to play .webm audios from URL on IOS and i always get unsupported bla bla.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.4.0 - /usr/local/bin/npm
      Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/xefi/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.3 => 43.0.3 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.2 => 0.66.2 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 6.2.1
    Expo Workflow: bare

**Comment by antochan** [comment]
Any updates here? I'm facing the same issue
