### ISSUE TITLE
Web build missing TTF/PNG assets when using a mono repo

### ISSUE THREAD

**Issue by olalonde** [expo/expo#21802]
### Summary

It seems that in a monorepo, some assets are incorrectly bundled by metro:

```console
expo export --platform web
npx serve dist/
open http://localhost:3000
```

```
 HTTP  3/21/2023 4:32:57 PM ::1 GET /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome.ttf?platform=web&hash=b06871f281fee6b241d60582ae9369b9
 HTTP  3/21/2023 4:32:57 PM ::1 Returned 404 in 3 ms
```

When doing the same in a non-monorepo, the issue goes away. Also, there is no issue in development mode only with the built version.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /opt/homebrew/bin/zsh
    Binaries:
      Node: 19.6.0 - ~/Library/Caches/fnm_multishells/15219_1679430206039/bin/node
      npm: 9.4.0 - ~/Library/Caches/fnm_multishells/15219_1679430206039/bin/npm
    SDKs:
      Android SDK:
        API Levels: 21, 31, 32
        Build Tools: 30.0.2, 30.0.3, 31.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
        Android NDK: 21.4.7075529
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: /undefined - /usr/bin/xcodebuild
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/olalonde/expo-bug-missing-ttf-and-png

**Comment by olalonde** [comment]
Here's a non mono repo version of the same code: https://github.com/olalonde/expo-bug-standalone

The only change is this (and removed it from the monorepo):

```diff
7a8
> const workspaceRoot = path.resolve(projectRoot, "../..");
12c13
< config.watchFolders = [projectRoot];
---
> config.watchFolders = [workspaceRoot];
15a17
>   path.resolve(workspaceRoot, "node_modules"),
```

I also noticed that the `dist/` folder output is slightly different (e.g. `assets/node_modules` in stead of `assets/__node_modules`:

<img width="401" alt="Screen Shot 2023-03-21 at 4 58 08 PM" src="https://user-images.githubusercontent.com/416585/226739998-83b28cf4-f890-4450-a539-e9b6408e9b45.png">

**Comment by G-Ray** [comment]
I'm affected by this issue too.

Like @olalonde, I get an `assets/__node_modules` folder instead of `assets/node_modules` in my `dist` output.

Also, requiring the font tries to fetch at a path starting with `/node_modules` instead of `/assets/node_modules`.

**Comment by G-Ray** [comment]
After further investigation we should start `npx serve` with `--single` option to avoid a 404 as `export` builds an SPA.

Still, I get a `Unmatched Route` when requiring an `.otf` file, because the url to the assets start with `/node_modules.` instead of `/assets/__node_modules/`.

**Comment by G-Ray** [comment]
This might be resolved with https://github.com/expo/expo/pull/22094.

**Comment by casperstr** [comment]
This issue is still present if using the native image component and not expo-image.
