### ISSUE TITLE
generate a native project for you link is broken

### ISSUE THREAD

**Issue by moshfeu** [expo/expo#2180]
I tried to search for a similar issue but all I found is this [issue](https://github.com/expo/expo/issues/46)

Reference to the broken link:
https://github.com/expo/expo/blame/master/README.md#L19

Thanks!

**Comment by esamelson** [comment]
Hi, thanks for letting us know. I'll update that link. Feel free to send us a PR if you see anything else that's out of date! 🙂

**Comment by moshfeu** [comment]
Sure :) 
I wanted to create PR but didn't find an alternative link.

Thanks!
