### ISSUE TITLE
`console.error` causes Expo Go to crash on iOS

### ISSUE THREAD

**Issue by jordan-acosta** [expo/expo#21803]
### Summary

When opening a branch in Expo go on iOS, my app crashes instantly. This only happens in Expo Go on iOS devices. It does not happen in the iOS simulator, in preview builds, TestFlight builds, or on Android.

When running the dev server using the iOS simulator, I noticed the error logs. I commented out the code that was creating them, and released to a branch. It opened in Expo Go without issue.

I'm building the branch using with the command, `eas update --auto --channel development`.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo: 48.0.0
expo-cli: 2.6.1
eas-cli: 3.7.2

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.2 - /private/var/folders/77/2334rqfd0_3bchvmvdrmz0080000gn/T/xfs-b460b0de/node
      Yarn: 3.4.1 - /private/var/folders/77/2334rqfd0_3bchvmvdrmz0080000gn/T/xfs-b460b0de/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

### Reproducible demo

Simply placing this anywhere in my codebase causes the issue.
```javascript
console.error('foo');
```

### Stacktrace (if a crash is involved)

The app simply crashes without any output. I can't replicate the crash in the simulator in dev mode, so I don't have any stack trace.

**Comment by pratik8442** [comment]
Did you find any solution? I am also facing exact same issue.

**Comment by jordan-acosta** [comment]
I haven't found a permanent solution yet, just a work-around.

The `console.error` calls that were causing Expo Go to crash in my case were in `node_modules/react-native/index.js`. Commenting those out fixed the issue, but of course I need to re-apply that change every time I install that module. You can use [patch-package](https://www.npmjs.com/package/patch-package) to automate this, but obviously that's not a long-term solution.

Now that I know what's going on, I would be happy to try fixing Expo Go myself, but it may take a bit to get familiar with it's code.

**Comment by pratik8442** [comment]
Thanks for sharing.
I hope the expo team will fix this
