### ISSUE TITLE
Expo SDK 48 build failed

### ISSUE THREAD

**Issue by crystalball808** [expo/expo#21824]
### Summary

Build crashes on gradlew stage
```
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* Where:
[stderr] 
Build file '/home/expo/workingdir/build/node_modules/expo-dev-launcher/android/build.gradle' line: 179
[stderr] 
* What went wrong:
[stderr] 
A problem occurred evaluating project ':expo-dev-launcher'.
[stderr] 
> Cannot invoke method multiply() on null object
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or
[stderr] 
--debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
A problem occurred configuring project ':expo'.
[stderr] 
> compileSdkVersion is not specified. Please add it to build.gradle
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 1m 49s
```

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.4 => 0.71.4
    Expo Workflow: managed

### Minimal reproducible example

None

**Comment by AyoCodess** [comment]
i'm having all sorts of issues with SDK 48 too. 
```

[stderr] 
A problem occurred evaluating project ':app'.
[stderr] 
> path may not be null or empty string. path=''
```

**Comment by Asekon** [comment]
> i'm having all sorts of issues with SDK 48 too.
> 
> ```
> 
> [stderr] 
> A problem occurred evaluating project ':app'.
> [stderr] 
> > path may not be null or empty string. path=''
> ```
im having the same issue. did you find a fix for this ?

**Comment by ucheNkadiCode** [comment]
Still having this issue

**Comment by AyoCodess** [comment]
> > i'm having all sorts of issues with SDK 48 too.
> > ```
> > 
> > [stderr] 
> > A problem occurred evaluating project ':app'.
> > [stderr] 
> > > path may not be null or empty string. path=''
> > ```
> 
> I am having this issue but I think this should be a separate issue though

I had to resort too building a new app and incrementally adding stuff back in.

**Comment by raulc27** [comment]
I am having this issue too:
> Configure project :app
 ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.2.1)
10 actionable tasks: 10 executed
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* Where:
[stderr] 
Build file '/home/expo/workingdir/build/android/app/build.gradle' line: 21
[stderr] 
* What went wrong:
[stderr] 
A problem occurred evaluating project ':app'.
[stderr] 
> path may not be null or empty string. path=''

**Comment by displaynone** [comment]
I had the same problem, but it was my mistake, in `package.json` I was setting the wrong file in `main`:
```json
{
  ...
  "main": "index.js"
  ...
}
```
In my case I was using `index.ts`, but renamed it to `js` and forgot to change the entry

**Comment by luccasr73** [comment]
same issue here, tested with a fresh project using typescript template, android version cant build and ios version works fine, any workaround?

**Comment by bht822** [comment]
with expo 48 entryPoint is not needed , try removing that from expo app.json

**Comment by luizcarvalho** [comment]
Still having this issue! =(

**Comment by JoaoLucas8760** [comment]
someone get resole?

**Comment by UchihaSV** [comment]
i'm create completely new clear project with latest expo and react native and have this issue of any gradlew command, why expo do this?

**Comment by kodaraj** [comment]
My Android build was failing locally giving similar reasons. The reason was I didn't set the ANDROID_HOME environment variable in my Mac.
I followed [this](https://stackoverflow.com/a/33631853/5584431) process and the build was successful after that.

**Comment by ttebify** [comment]
For people still facing this issue, read this #22584

**Comment by kubijo** [comment]
> I had the same problem, but it was my mistake, in `package.json` I was setting the wrong file in `main`:
> 
> {
>   ...
>   "main": "index.js"
>   ...
> }
> 
> In my case I was using `index.ts`, but renamed it to `js` and forgot to change the entry

Thank you, man… same here, had my index changed to `index.tsx` + `index.web.tsx` for `react-native-skia` and forgot to drop the extension in `package.json` while resolving a merge conflict.

In that case, the correct value for `package.json#main` seems to be just `index`.
