### ISSUE TITLE
Camera problem 

### ISSUE THREAD

**Issue by gorge2004** [expo/expo#2182]
i am using Camera from expo, when i used Camera worked fine but when i add with react-navigation now throw:
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. .
why ??? I am using react-navigation.  The problem appears when I use navigation and open Camera first time

**Comment by ide** [comment]
Do you have more than one mounted camera component, or are using the camera on an inactive screen? It sounds like you need to debug further to identify the root cause of this issue.

**Comment by gorge2004** [comment]
Yes , first. I did login in the app . What can i do ?

**Comment by ide** [comment]
Is this issue resolved?

**Comment by jay-manday** [comment]
I'm getting this issue as well, I'm using the expo camera component with Switch Navigator from `react-navigation`. 

I was using the stack navigator and the camera (and all other pages) continued running in background.

I haven't been able to turn off the camera when switching screens, so decided to try switch navigator when coming across this issue. 

note: i'm only using the camera in one screen

**Comment by gorge2004** [comment]
Yes, it was resolved
