### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by JuanRdBO** [expo/expo#21833]
### Summary

The native code in the guide [here](https://docs.expo.dev/bare/installing-updates/) has [changed](https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.71.3) for the expo sdk 48 and it's recommended RN version. Is there a way to update it to the newest version?

### Link to the related docs page

https://docs.expo.dev/bare/installing-updates/

**Comment by douglowder** [comment]
Dupe of #21835, closing.
