### ISSUE TITLE
expo-image flickers when using in FlatList

### ISSUE THREAD

**Issue by ilyadynin** [expo/expo#21830]
### Minimal reproducible example

```
<FlatList
  overScrollMode='never'
  showsVerticalScrollIndicator={false}
  showsHorizontalScrollIndicator={false}
  data={feedContent}
  keyExtractor={(item) => item.id}
  ListHeaderComponent={!isDiscovery && renderHeader()}
  ListEmptyComponent={renderEmptyState()}
  refreshing={refreshing}
  onRefresh={onRefresh}
  renderItem={renderItem}
/>

const renderItem = ({ item }) => {
  return <Item item={item} />;
};


const Item: React.FC<{ item: Item }> = React.memo(
  ({ item }: { item: Item }) => {
    const [isImage2Active, setIsImage2Active] = useState(false);

   
        const image1Url = useMemo(() =>, item.picture.url1, []);
        const image2Url = useMemo(() =>, item.picture.url2, []);


        const handleImagePress = useCallback(() => {
            setIsImage2Active(!isImage2Active);
        }, [isImage2Active]);


return(
<>
        <Image
          source={isImage2Active ? item.picture1 : image2Url}
          style={{ width: 40, height: 40, borderRadius: 20, marginRight: 10 }}
        />
<Button onPress={handleImagePress} />
      </>)
    );
  }
);
```

### Summary

When using the images directly in renderItem there is no issue, but I cannot do that, since I need some stateful logic, and I cannot use hooks in renderItem, so I have to provide another functional component there, and when I do so and outsource the image component into an extra component and not directly renderItem, they start to flicker which is indicating that expo-image is not caching them properly.

### Environment

sdk-48, expo-image and FlatList

**Comment by chanphiromsok** [comment]
I also having this issue with `expo-image` it flick my item in FlatList I don't have this issue with `react-native-fast-image`
I think this issue should be open

**Comment by focux** [comment]
I'm having this same issue as well, is there any workaround to make it work inside the ListHeaderComponent?
