### ISSUE TITLE
[docs] expo-location config plugin keys are wrongly documented

### ISSUE THREAD

**Issue by foxriver76** [expo/expo#21842]
### Summary

It states, that `isIosBackgroundLocationEnabled` is a permission string, but the generated `plist` will contain the default string: 
```xml
<key>NSLocationWhenInUseUsageDescription</key>
    <string>Allow $(PRODUCT_NAME) to access your location</string>
``` 

(when all 3 permissions set to the same string), which is of course the third missing permission description for `iOS`. 

Code-wise it is a `boolean` and https://github.com/expo/expo/blob/84797ef0416e3d364ab3cc650d9ed849dbcdad7a/packages/expo-location/plugin/src/withLocation.ts#L27 is the missing permission string.

So the docs should be fixed to state the third permission string as well and to actually describe to correct intention of the boolean flag.

![Bildschirmfoto 2023-03-25 um 11 22 02](https://user-images.githubusercontent.com/25484431/227711698-1d0740a1-bddf-4292-8b67-0e603d06ad88.png)

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/location/#permission-nslocationwheninuseusagedescription

**Comment by geeron** [comment]
@foxriver76 No comments on the contents of this PR, but you can suggest changes directly from the docs and make a PR from the _Edit this page_ button at the bottom of the page, which will take you to this link: https://github.com/expo/expo/edit/main/docs/pages/versions/unversioned/sdk/location.mdx
<img width="383" alt="Screenshot 2023-03-29 at 12 19 44" src="https://user-images.githubusercontent.com/59517998/228504169-e11ebeeb-9374-43a1-a2c3-e41fe7f6c046.png">

**Comment by amandeepmittal** [comment]
We've updated the docs and fixed the issue reported here: https://docs.expo.dev/versions/latest/sdk/location/#configurable-properties

Thank you for reporting this issue. (Closing this issue for now).
