### ISSUE TITLE
expo-document-picker app crash on android

### ISSUE THREAD

**Issue by kjh0813** [expo/expo#21851]
### Minimal reproducible example

https://snack.expo.dev/@koiwaredev/document-picker

### Summary

I'm experiencing an issue where expo-document-picker is causing a crash only on Android. Can you please help me with this?

1. Run expo-document-picker
2. Press the back button to exit the picker 
3. app crashes.

I am getting an "UnexpectedException: Unknown type: class expo.modules.documentpicker.DocumentPickerCancelled" error in my APK and an error as shown below in expo-go"

![스크린샷 2023-03-27 오후 2 36 00](https://user-images.githubusercontent.com/95664901/227850811-d45366a2-4a0e-424f-b820-14016615daed.png)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
      npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
      Watchman: 2021.09.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.1 => 9.3.1 
      expo: ~48.0.0 => 48.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.6.0
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi, are you using expo go? Can you please update it to the latest and try again?

**Comment by Kudo** [comment]
we don't release new expo go with the expo-document-picker fix yet. i'm accepting this issue and will publish expo-go with react-native 0.71.5 or 0.71.6.

**Comment by KiwiKilian** [comment]
Also, what about a standalone release of the package? We have this problem in our Dev Client.

**Comment by KiwiKilian** [comment]
@alanjhughes it has not yet been released – so only option would be to install from git. Last release of expo-document-picker was 2023-02-09, your fixed merged on 2023-03-07. Also visible in the changelog: https://github.com/expo/expo/blob/main/packages/expo-document-picker/CHANGELOG.md#unpublished  – Would be awesome to have a release. Thanks! 🚀

**Comment by Kudo** [comment]
i could help to publish the fix for expo-document-picker package in one or two hours. will update the issue once ready.

**Comment by Kudo** [comment]
published `expo-document-picker@11.2.2`. hopefully that works for you.

**Comment by KiwiKilian** [comment]
Thanks @Kudo – works fine now in our dev client!

**Comment by dev-avishek** [comment]
@KiwiKilian @Kudo can you please confirm the issue has been fixed or not? We need to fix this in one of our live app.

**Comment by Roka20012** [comment]
@dev-avishek 
Don't think this issue is fully fixed in Expo Go.
The app is not crashing but got a warning in Expo Go (_in a production app everything works fine_)

So basically after canceling the Document selection, when you want to open Document Picker again you got a warning(check image), and Document Picker is not opening any more related comment https://github.com/expo/expo/issues/21578#issuecomment-1488019202


---
#### Tested on a real device: Pixel 5, Android 13
`Expo Go version: 2.28.6` (latest in play store)

```
 "expo": "^48.0.9",
 "expo-document-picker": "~11.2.2",
```

<img width="971" alt="image" src="https://user-images.githubusercontent.com/32239452/230601136-567de87a-a0ca-41aa-9c56-ecaca74c5c9a.png">

**Comment by dev-avishek** [comment]
Hey @Roka20012, in my case it crashed in v11.2.1 but once I bumped up the version to v11.2.2 it got fixed in (Standalone/release apk)

I don't know about the behavior it's giving on Expo Go.

**Comment by dev-avishek** [comment]
Hey, @Roka20012 I become inquisitive, hows's the situation now in Kyiv?

**Comment by Roka20012** [comment]
@dev-avishek Oh didn't expect that question here, thanks for your concern I appreciate this 🙂

Basically, when your country is attacked by russian missiles almost if not every day I wouldn't say it is safe here :/

**Comment by HillertNext** [comment]
An additional note: On e.g. Samsung, files that have been deleted within the download folder are still visible - I can then download them again. So if I select such a “non-existent” file, the expo document picker crashes with

Failure delivering result ResultInfo{who=null, request=4137, result=-1, data=Intent {...}: expo.modules.kotlin.exception.UnexpectedException: Unknown type: class expo.modules.documentpicker.FailedToCopyToCacheException

Maybe someone can confirm this?

**Comment by labhinfo** [comment]
Very stuff pakage of npm while building you will always get error and in expo go while testing the even not works giving error

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNDocumentPicker' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false.

Very Third class please fix this issue

**Comment by alanjhughes** [comment]
@labhinfo - `RNDocumentPicker` comes from `react-native-document-picker` which is not an expo library and not supported in expo go
