### ISSUE TITLE
IOS push notification dropped by server ("The Apple Push Notification service unexpectedly dropped the connection")

### ISSUE THREAD

**Issue by adhicl** [expo/expo#2185]
Hi, I tried to send push notification to my standalone IOS app. But when I checked the https://exp.host/--/api/v2/push/getReceipts it return:
{
“status”: “error”,
“message”: “The Apple Push Notification service unexpectedly dropped the connection. Retry sending the notification later.”,
“details”: {
“sentAt”: 1535960646
},
“__debug”: {
“internalError”: “stream ended unexpectedly”
}
},
Can anyone me with this? Thanks
Note: there is no problem with my android standalone build for the same app. And I am still in testflight mode
Step:
1. Send a push notification via expo push notification php
2. Get the id
3. Check via https://exp.host/--/api/v2/push/getReceipts
Result behavior:
1. Push notification dropped the connection
Expected behavior:
1. My device should have received the notification

**Comment by adhicl** [comment]
Hi, anyone can help? Is there anything I can do to fix this? Also as a note, I need to import my own p12 file for this project because I want to use DocumentPicker, so I don't pick to let Expo takes care of everything option

**Comment by ide** [comment]
If this error persists, you can try uploading a new p12 file. Be sure to follow the instructions exactly, as Apple will reject invalid credentials. The Expo server reports as precise of an error it can in the asynchronous push receipts when the credentials are invalid, but sometimes Apple does not provide an error (such as when the connection drops).

**Comment by adhicl** [comment]
Hi, so I will update on my own case. So, after several trial to upload my own certificates, I still get the same dropped by server message. In the end I try to delete my previous certificates and provisions and choose to let Expo handle everything. Only after that I can receive notifications like normal. So, if nobody has more problems I am ok to close this topic down. Thanks for the advices and help

**Comment by nickjuntilla** [comment]
None of my push notifications are getting through on my stand alone app with expo 31.0.2.

**Comment by ide** [comment]
@nickjuntilla What does the [push receipt](https://docs.expo.io/versions/latest/guides/push-notifications/#push-receipts) say?

**Comment by nickjuntilla** [comment]
@ide If I do `build:ios --clear` do I need to rebuild the stand alone app and resubmit it to the store or just publish for that to have an affect?

**Comment by nickjuntilla** [comment]
@ide If I do build:ios --clear is that going to delete my credentials? My app is already in the store so I need to still be able to update it. Thank you.

**Comment by danielravina** [comment]
`--clear` doesn't exist. here are the options for expo cli 2.6.14
```
Options:

    -c, --clear-credentials                         Clear credentials stored on expo servers
    --clear-app-credentials                         Remove app related credentials stored on expo servers (iOS)
    --clear-dist-cert                               Remove distribution cert stored on expo servers (iOS)
```

I'm having the same issue.. trying this solution now.

**Comment by nickjuntilla** [comment]
@danielravina Is your app in the store already? I don't want to clear my credentials if they end up being lost forever. Please give me an update with your results. I greatly you guinea pigging here.

**Comment by danielravina** [comment]
Works now! 
I updated expo to `2.8.0`.  ran `expo build:ios -c`

My app is not on the app store. don't think you need to re-upload the app to the app store.

**Comment by nickjuntilla** [comment]
When I clear the credentials and try to generate new ones I get 

`"resultString": "There were errors in the data supplied. Please correct and re-submit.",
  "userString": "Multiple profiles found with the name 'com.rxxxx.xxxx AppStore'.  Please remove the duplicate profiles and try again.",`

I'm sorry I don't know much about this. My app is already in the store. If I delete the old profile does that mean I can't update my app anymore?

**Comment by nickjuntilla** [comment]
Success!! I decided to take the plunge and delete my provisioning profile and allow a new one to be generated. I then published the package using the normal 'publish' button on the expo start interface and it worked. I have no idea how or why, but it worked. If anyone has the time it would be nice to know how the provisioning profile can affect the published app?

**Comment by ide** [comment]
> If I do build:ios --clear is that going to delete my credentials?

Yes, the point is to clear your credentials. It will remove your provisioning profile and push notification credentials from Expo's servers, which means you will need new push notification credentials for push notifications to start delivering again.

> how the provisioning profile can affect the published app

It doesn't and behaves the same as stock iOS development; Expo doesn't do anything special here.

**Comment by nickjuntilla** [comment]
@ide 

> It doesn't and behaves the same as stock iOS development; Expo doesn't do anything special here.

Well it does seem to have affected production app because by deleting the provisioning profile and re-issuing even without submitting a new version to apple the push notifications are now working in production. So something has affected production somehow.

**Comment by brentvatne** [comment]
> Success!! I decided to take the plunge and delete my provisioning profile and allow a new one to be generated.

does this mean you ran a command through expo-cli to do it, like `expo build:ios -c` or `expo build:ios --clear-provisioning-profile`, or you actually went to the apple developer portal and deleted it?

**Comment by nickjuntilla** [comment]
@brentvatne I ran `build:ios --clear-credentials` but it didn't work until I went to the developer console in the apple website and deleted the old provisioning profile (which was very nerve racking) and then I ran `build:ios --clear-credentials` again made a new profie. Then published my package and it worked.

**Comment by emadjumaah** [comment]
Hello there,
I tried everything above, the getExpoPushTokenAsync on production (standalone app) dose not generate a pushToken on IOS !!
"sdkVersion": "32.0.0"

**Comment by hosseintoussi** [comment]
We intermittently get this error. It would be really helpful if Expo could add an `error` field in the `details` object like the other errors, and we could perhaps use that to handle these errors.

**Comment by ide** [comment]
@hosseintoussi the underlying error has to do with HTTP/2 and APNs and is probably unhelpful. I'm not sure how it would help you handle anything.

If you are repeatedly encountering this error, I'd recommend clearing your credentials and uploading a .p8 key instead and trying that.

**Comment by hosseintoussi** [comment]
Thanks for your explanation @ide. Since its intermittent, i thought we could retry sending the notifications that failed with this at least once. 

I can try uplading a new .p8 key and see if helps.

**Comment by briefjudofox** [comment]
Hello @ide, I know this ticket hasn't had any activity in a long while, but we've seen an uptick in these errors recently.  We're on SDK 41 and we've been using .p8 keys for a while.  The majority of our APNs notifications are successfully sent, but we've started to see a handful of these errors every day. 

Have there been any recent changes to the Expo Push Service that might be a factor?  Please let me know if you have any suggestions.

Thanks!

**Comment by ide** [comment]
We haven't made any changes to the service. It's possible that Apple made a change or that Apple has errors on their side of the connection. The Expo push notification service is thin so that these errors don't get obscured. Adding retry logic to your code is a good idea since it will handle bigger classes of errors.

**Comment by briefjudofox** [comment]
Thanks for the quick response @ide.   I'll add some retry logic to see if that helps (currently only retrying on 502s from the Expo service).
