### ISSUE TITLE
In expo face detector while detecting image at the local uri getting (ios)  ---> [Error: -[NSTaggedPointerString longValue]: unrecognized selector sent to instance 0xa9d3cd5bd910fbdb]

### ISSUE THREAD

**Issue by veris-kamaraj** [expo/expo#21866]
### Minimal reproducible example

https://snack.expo.dev/@veris-developer/b09ddf

### Summary

In ios while detecting faces on the local uri i am getting error

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.1 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    Expo Workflow: managed

**Comment by Kudo** [comment]
hi there! that is because you pass the `mode` with a string. you should pass the [enum value](https://docs.expo.dev/versions/latest/sdk/facedetector/#facedetectormode) instead. 

```diff
              FaceDetector.detectFacesAsync(result.uri, {
-               mode: "fast",
+               mode: FaceDetector.FaceDetectorMode.fast,
              }
```
