### ISSUE TITLE
BarCodeScanner keeps scanning after unmount on iOS

### ISSUE THREAD

**Issue by KiwiKilian** [expo/expo#21868]
### Minimal reproducible example

https://github.com/trafficon/expo-barcode-scanner-ios-unmount-bug

### Summary

The BarCodeScanner keeps scanning in the following scenario using react-native-reanimated and @react-navigation/native-stack on iOS in Expo Go. The StackNavigator is build of two screens:

1. HomeScreen showing an `Animated.View`
2. QrScannerScreen rendering the `BarCodeScanner`

When the HomeScreen has never rendered the `Animated.View` and the QrScannerScreen is unmounted, the scanning will stop properly. When the HomeScreen has once rendered the `Animated.View`, returning/unmounting the `BarCodeScanner` does not successfully stop the scanning process. This is obvious through the green privacy dot.

This is a video of the reproduction. First the QrScannerScreen is opened without the `Animated.View` on the HomeScreen. The green dot in the upper right disappears after returning to the HomeScreen. Then the `Animated.View` is rendered. After openen the QrScannerScreen again and going back the green dot does not disappear.

https://user-images.githubusercontent.com/18724559/228045689-29d9b4fd-4863-490f-959c-e48ffc28d009.mp4

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.6.2 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.9 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.4 => 0.71.4 
    npmGlobalPackages:
      eas-cli: 3.8.0
      expo-cli: 6.3.2
    Expo Workflow: managed
```

Expo Go Version on my iOS Device: 2.28.7.1017523

**Comment by Kudo** [comment]
hi there! i wonder this issue is coming from [react-native-screen](https://github.com/software-mansion/react-native-screens). could you help to report the issue to react-native-screen? for what i've figured out, if there is a reanimated view, when going back to previous view, the [`removeFromSuperview`](https://github.com/expo/expo/blob/5222dff5bbfeb88d610dac5215809285700fb819/packages/expo-barcode-scanner/ios/EXBarCodeScanner/EXBarCodeScannerView.m#L122-L130) will not be called. thanks!

**Comment by KiwiKilian** [comment]
Thanks for coming back on this @Kudo. Ist there an easy way to show the, that `removeFromSuperview` is not called? Not sure if they will accept this with just your comment.

**Comment by Kudo** [comment]
@KiwiKilian i cloned your repro, run `npx expo prebuild -p ios`, and add breakpoints while running in xcode. does the information makes sense to you?

**Comment by KiwiKilian** [comment]
Okay, I can work with that approach try to report upstream, thanks!

**Comment by Kudo** [comment]
thanks @KiwiKilian. feel free to let me know if you need any information for the react-native-screen issue.

**Comment by KiwiKilian** [comment]
Just a headsup, upgrading to react-native-reanimated from v2 to v3 fixes it, I suspect these changes: https://github.com/software-mansion/react-native-reanimated/pull/3865 – sadly it breaks a whol lot of other stuff for us... I will see if I can come up with a solution other than removing reanimated `Animated.View`s.

**Comment by Kudo** [comment]
nice investigation, thanks @KiwiKilian!
