### ISSUE TITLE
Expo client splash screen: tabletImage overrides image on iOS

### ISSUE THREAD

**Issue by GfxKai** [expo/expo#2186]
Hi!

I've just run into an unfortunate issue where the `tabletImage` splash seems to be overriding the standard `image` splash for all iOS devices. I've tested multiple iPhone and iPad models within Simulator and on an actual iPhone 6S, all test runs show the `tabletImage` splash during loading, regardless of device form factor.

EDIT: I believe the issue is due to this logic in [EXAppLoadingView.m](https://github.com/expo/expo/blob/master/ios/Exponent/Kernel/Views/Loading/EXAppLoadingView.m#L155-L159), which uses the tablet splash instead of the standard one if it is present in the manifest:
```
if (splash[@"tabletImageUrl"]) {
    imageUrl = splash[@"tabletImageUrl"];
} else if (splash[@"imageUrl"]) {
    imageUrl = splash[@"imageUrl"];
}
```
Could we check the dimensions of the screen to decide which splash to use here instead?
  
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.9.0
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4
```

### Steps to Reproduce

1. Run `exp init`
2. Add different images to `ios.splash.image` and `ios.splash.tabletImage` in `app.json`:
```
"ios": {
    "buildNumber": "1.0.0",
    "supportsTablet": true,
    "isTabletOnly": false,
    "splash": {
        "backgroundColor": "#4288DB",
        "image": "./assets/splash_phone.png",
        "tabletImage": "./assets/splash_tablet.png" // <-- this one is always displayed
    }
}
```
3. Run `exp start` and then `exp ios` in another terminal window
### Expected Behavior

`ios.splash.image` should render if device is an iPhone, otherwise `ios.splash.tabletImage` should render

### Actual Behavior

`ios.splash.tabletImage` is always rendered

### Reproducible Demo

Snack doesn't respect / use `app.json`, but this can be reproduced quickly and easily by following **Steps to Reproduce** above

**Comment by devtanc** [comment]
I'm seeing this same issue

**Comment by peterbee** [comment]
I am also experiencing this

**Comment by GfxKai** [comment]
Update: as of v32.0.5 this issue is still apparent. It only occurs within the expo client: once deployed as a standalone app, the splash screens work as expected

**Comment by GfxKai** [comment]
I believe the issue is due to [this](https://github.com/expo/expo/blob/master/ios/Exponent/Kernel/Views/Loading/EXAppLoadingView.m#L155-L159) logic in EXAppLoadingView.m, which uses the tablet splash instead of the standard one if it is present in the manifest. Could we check the dimensions of the screen to decide which splash to use here instead?
