### ISSUE TITLE
Error: IntentLauncher.startActivityAsync is not available on android

### ISSUE THREAD

**Issue by Gethomely** [expo/expo#21876]
### Minimal reproducible example

https://snack.expo.dev/@gethomely/expo-intent-launcher

### Summary

Possible Unhandled Promise Rejection (id: 0):
Error: The method or property IntentLauncher.startActivityAsync is not available on android, are you sure you've linked all the native dependencies properly?

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.14.2 - D:\Soft\NodeJS\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.3 - D:\Soft\NodeJS\npm.CMD
    npmPackages:
      expo: ~47.0.3 => 47.0.13 
      react: ^18.0.0 => 18.2.0 
      react-dom: ^18.0.0 => 18.2.0 
      react-native: ^0.69.3 => 0.69.8 
    Expo Workflow: bare
```
Package.json
```
 "expo": "~47.0.3",
"expo-file-system": "~15.1.1",
 "expo-intent-launcher": "10.3.1",
"expo-modules-core": "~1.0.2",
 "react": "^18.0.0",
```

**Comment by brentvatne** [comment]
the repro you shared is not working in a variety of ways unrelated to expo-intent-launcher. see https://snack.expo.dev/@brents/expo-intent-launcher for a working example of the library.

**Comment by Has-if36** [comment]
If so, then this part of the [documentation](https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemgetcontenturiasyncfileuri) need to be updated.
