### ISSUE TITLE
TypeError when running expo go

### ISSUE THREAD

**Issue by TheRedM** [expo/expo#21871]
### Summary

I'm getting this error in the terminal when trying to run a fresh project in expo go, I don't know what's causing it since the project is fresh. This is the full error

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Exponent-Server"]
```
Note that after installing expo environment for the first time everything was fine, I started a project I ran it without any problems and I still can run it.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: android
    Binaries:
      Node: 18.14.1 - /data/data/com.termux/files/usr/bin/node
      npm: 9.3.1 - /data/data/com.termux/files/usr/bin/npm
    npmPackages:
      expo: ~48.0.9 => 48.0.9
      react: 18.2.0 => 18.2.0
      react-native: 0.71.4 => 0.71.4
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: managed

### Minimal reproducible example

I don't know what to do to reproduce it because it's a fresh project, i simply start the project using ```npm start``` or ```npx expo```

**Comment by Kudo** [comment]
hi there! would you mind to upload the fresh project to github as a repro for us to investigate? i'm happy to reopen and investigate the issue if you could help to create a repro. thanks!

**Comment by TheRedM** [comment]
> hi there! would you mind to upload the fresh project to github as a repro for us to investigate? i'm happy to reopen and investigate the issue if you could help to create a repro. thanks!

Sorry for the late reply, here is a test project where im facing this error:
https://github.com/TheRedM/expo-bug

**Comment by Kudo** [comment]
hi @TheRedM! i cannot repro the error from your repro. i was thinking whether this is more like an environment problem. from what i can find in the meantime, could you try to run `npx expo start` than just `expo start`?

**Comment by TheRedM** [comment]
> hi @TheRedM! i cannot repro the error from your repro. i was thinking whether this is more like an environment problem. from what i can find in the meantime, could you try to run `npx expo start` than just `expo start`? 

I'm getting the same error, whether I used ```npx expo start```  or  ```expo start```  the later is giving me more info about the error which is mentioned in the update 2, note that I'm using termux, the first project ever ran on it was fine, I faced the the problem only on newer projects which is confusing, I even did a factory reset to the device but still facing the same problem, please take a look at update 2 where the error is saying exactly where the problem is coming from, I will try to run it on another device to see if that's only on my device/environment or it's a global problem.

**Comment by Kudo** [comment]
good to know. i'm sorry that i'm not quite familiar how termux works. hopefully you could find a way to deal with the issue.

**Comment by TheRedM** [comment]
> good to know. i'm sorry that i'm not quite familiar how termux works. hopefully you could find a way to deal with the issue.

Yeah, 3 days now trying to solve it still the same, somehow it's device specific, I did the same steps (THE EXACT SAME) on another device, and it's working, I even did a factory reset, changed the android version , I tried everything you could imagine, somehow it's only my device, note that it was working fine about two months ago, I was working only on one project, so it's probably there was an update in a library that expo uses or something that broke it (only new projects, the first project I created was still working fine) so it's probably the problem is from expo's side that somehow doesn't like my device anymore! I'll keep trying to fix it If you have any suggestion please let me know.
