### ISSUE TITLE
scheduleLocalNotificationAsync: use of intervalMs option results in error on Android

### ISSUE THREAD

**Issue by plhosk** [expo/expo#2187]
## Environment

Any Android target environment (snack, emulator, device)

sdk 29, 28, 27

### Steps to Reproduce

Schedule a local notification using `Notifications.scheduleLocalNotificationAsync()`.

In the schedulingOptions object, supply a number value to the `intervalMs` parameter. For example `2000`

### Expected Behavior

Notification repeats every intervalMs

### Actual Behavior

Program crashes with error: `java.lang.Double cannot be cast to java.lang.Long`

Location of error:

https://github.com/expo/expo/blob/a13f834830472af85cd95af6f36ead949173feaa/android/expoview/src/main/java/host/exp/exponent/notifications/NotificationHelper.java#L601

### Reproducible Demo

https://snack.expo.io/SkECmamu7

**Comment by ningacoding** [comment]
any update?

**Comment by ningacoding** [comment]
repeat: 'minute' or any of available options, work only when app is running, when is closed notification is not sent.

**Comment by alemkhodadadi** [comment]
I still have this error. Any solution??

**Comment by cruzach** [comment]
Hi everyone, sorry for the lack of response here. We did a complete revamp of the notifications module, giving devs a lot more power, flexibility, and consistency. 

I tested out scheduling a repeating notification with the new `expo-notifications` module in SDK 38, and it's working as expected without any crashes, you can try it out with this Snack if you download the newest Expo client app: https://snack.expo.io/@charliecruzan/notifications2187.  If you are able to still reproduce the crash using that snack, SDK 38, and the `expo-notifications` module, then please let me know what device you're using!
