### ISSUE TITLE
[docs] Installing expo-updates in bare workflow project, out-of-date

### ISSUE THREAD

**Issue by tylercote** [expo/expo#21881]
### Summary

The instructions for how to configure expo-updates in a bare workflow project seems to be out of date.

For example, see [here](https://docs.expo.dev/bare/installing-updates/#update-appdelegatemm) and notice that the line to replace in AppDelegate.mm no longer exists.

Myself and others seem to have been running into crashes due to misconfiguration, and I think the documentation might be leading people astray.

### Link to the related docs page

https://docs.expo.dev/bare/installing-updates/

**Comment by douglowder** [comment]
ENG-8012

**Comment by douglowder** [comment]
@tylercote we are reviewing the above doc to see how it needs to change for the latest SDK. In the meantime, I would recommend taking a look at https://docs.expo.dev/eas-update/eas-update-with-local-build/ .

**Comment by douglowder** [comment]
Fixed in #22069
