### ISSUE TITLE
[expo-font/Eas Build] Fonts don't get bundled in release/preview app

### ISSUE THREAD

**Issue by hyoretsu** [expo/expo#21888]
### Minimal reproducible example

https://github.com/hyoretsu/ton/tree/usefonts-bug/mobile

### Summary

Simply put, I use `useFonts` hook, everything works fine on development, but whenever I generate an APK or AAB **with EAS Build** it doesn't work. I get `Resource ID #0x0` and my app can't even load. I'm using mainly the script `preview:android` to test for production errors. Everything happens on `src/App.tsx`.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
    Expo Workflow: bare
```

**Comment by hyoretsu** [comment]
Or maybe it's an issue with `expo prebuild`, seeing as I don't find the font files anywhere in the native folders.

**Comment by hyoretsu** [comment]
Confirmed that it's not a issue of how I set up my app. I just ran `npx create-react-native-app --template with-custom-font` and `eas build:configure` and `eas build -p android --profile preview --local` and while the URL font gets loaded correctly, the local font used by `require` doesn't.

**Comment by brentvatne** [comment]
@hyoretsu - I am not able to reproduce this in a new project:

```
yarn create expo-app hyoretsu -e with-custom-font
cd hyoretsu
yarn expo run:android --variant release
```

![image](https://user-images.githubusercontent.com/90494/231598037-d035034d-3b39-49e1-b7bf-c1b833f1db3d.png)

**Comment by butadpj** [comment]
Same issue with me until I pushed my first EAS Update. It's super frustrating that it's not mentioned in the docs - https://docs.expo.dev/archive/classic-updates/offline-support/#eas-build
