### ISSUE TITLE
[Android] - Expo task manager stop due do Android "doze mode"

### ISSUE THREAD

**Issue by AlvaroYmagawa** [expo/expo#21895]
### Minimal reproducible example

https://github.com/AlvaroYmagawa/expo-task-android-issue

### Summary

I'm developing an application that needs to monitor the user's location in the background, while I use the app in the background but with the cell phone unlocked it receives the locations normally, but when I lock my cell phone after about 10m of inactivity the taks in the background stop due to 'doze mode' i.e (https://developer.android.com/training/monitoring-device-state/doze-standby?hl=pt-br#understand_doze) on Android.

Does anyone know a workaround for this issue? Because i need to keep my app alive, or maybe keep the locations update task keep working even in Android  'doze mode'

## Steps to reproduce
* Test on Android 6.0 (API level 23) or above
* Grant Permissions.LOCATION
* Go in background
* Lock the device and wait

The app will stop receiving locations from the log

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.4.1 - /usr/local/bin/npm
      Watchman: 2023.01.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.6 => 48.0.7 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.6 => 0.70.6 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

**Comment by japineda16** [comment]
I have the same issue, there is any answers?

**Comment by JamesIde** [comment]
Hi @AlvaroYmagawa and @japineda16, looks like we are all in a similar position. I even made a comment on https://github.com/expo/expo/issues/14076. I am suspecting that this may no longer be a problem with expo-task-manager as referenced by OP in that issue, but rather related to battery optimization on Android. For reference, I'm using an Android S20 FE with Android 13. 

I've spent a good hour testing location updates with expo-task-manager and expo-location using development builds with EAS (ejected from Expo as I'm using rnmapbox/maps), and I've observed a couple of things. Here is the [code for reference](https://github.com/JamesIde/terratrack/blob/master/components/core/mapbox/Map.tsx).

The first observation is that despite setting a timeInterval to 1000ms and distanceInterval to 0, background location updates START at 1000ms intervals, but then slowly get longer and longer where they seem to come in consistently at 5seconds each (I'm writing this and have had consistent updates for 25 minutes woo!). What I did do was turn off battery optimization for the app. 

Before I did this, the location updates would stop anywhere from 5-15 minutes and then I'd get a big batch of location updates (the largest I saw was 213), in the span of a few minutes. 

I found https://dontkillmyapp.com/samsung to be a useful resource. I am still testing/debugging to come to a solid conclusion about this, but I am leaning towards battery optimization being the culprit. I guess you'd need to have a detailed explanation to explain to the user why they need to disable battery optimization. I'm not sure of the implications of doing that when the app is submitted to the app store. 

All of my testing is done with an Android (I don't have an iPhone/mac)

**Comment by arturbil** [comment]
https://github.com/expo/expo/issues/14076#issuecomment-1367868439 solved it for me.

**Comment by pedbarros** [comment]
> [#14076 (comment)](https://github.com/expo/expo/issues/14076#issuecomment-1367868439) solved it for me.

That code solved my problem, but there is one point to improve. I've noticed that sometimes the service is taking a while to start up. I tested updating the application and, after restarting the device, the service takes 1 to 2 minutes to start. Is there any way to solve this?

I’ve tested in SDK 33 (Motorola G30)
