### ISSUE TITLE
Metro bundler for web not able to resolve `browser` module overrides in `package.json`

### ISSUE THREAD

**Issue by mackenziekira** [expo/expo#21896]
### Summary

After switching to use metro bundler instead of webpack for web, I began to see this error in a dependency when building web:

```
Web Bundling failed 573ms
Unable to resolve "xmlhttprequest" from "node_modules/@twilio/voice-sdk/es5/twilio/request.js"
```

Looking at that dependency's `package.json`, they define a `browser` override for two of their dependencies:

```
  "browser": {
    "xmlhttprequest": "./browser/xmlhttprequest.js",
    "ws": "./browser/ws.js"
  }
```

Based on the [docs](https://facebook.github.io/metro/docs/configuration/#resolvermainfields), it looks like Metro supports the `browser` field spec, so it was unexpected for me why this particular lib is causing issues. Is there a recommended way to resolve this, e.g. do I need to define a custom resolver?

Potentially related issue: https://github.com/expo/expo/issues/21175

### What platform(s) does this occur on?

Web

### SDK Version

48

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 2022.09.19.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.9 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.4 => 0.71.4 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/mackenziekira/metro-browser-resolution

clone this^ MRE repo, run `yarn install`, run `npm run web`, see bundling error:

```
Web Bundling failed 573ms
Unable to resolve "xmlhttprequest" from "node_modules/@twilio/voice-sdk/es5/twilio/request.js"
```

**Comment by Akronae** [comment]
I have the same issue with
```
metro@^0.76.3
metro-resolver@^0.76.3
```
Somehow on web build it still resolves to `react-native` entries in my modules `package.json` though I have a `main` and `react-native` entry.

Had to get back to
```
metro@^0.73.7
metro-resolver@^0.73.7
```
to get it working

**Comment by dannyhw** [comment]
Any fix without changing the metro version? Need to be using the .76 version to test some newer features.
