### ISSUE TITLE
New CRNA projects uses Expo 27 and not Expo 29

### ISSUE THREAD

**Issue by edoantonioco** [expo/expo#2190]
Description
When creating a new project with create-react-native-app, it creates a new project using Expo version 27

Expected Behavior
[Expo 29 has been around since July](https://blog.expo.io/expo-sdk-v29-0-0-is-now-available-f001d77fadf), and CRNA still uses Expo 27.
I was expecting it to use the latest version.

Observed Behavior
It uses an old version of Expo

Environment
Operating system: Linux
Phone/emulator/simulator & version: Emulator
Reproducible Demo
Just create a new project using CRNA and check the package.json

**Comment by brentvatne** [comment]
CRNA will soon be replaced by expo-cli: https://github.com/react-native-community/discussions-and-proposals/issues/23

We had intended to do this sooner and so CRNA was not updated. This is unfortunate, but at this point we are very close to properly switching it over and so we will not be updating CRNA anymore.

**Comment by edoantonioco** [comment]
That sounds cool. Newer expo has some svg feature that I'm needing so I want to try thins new tool soon.
Is expo-cli already ready to be used?

**Comment by acomito** [comment]
Is it possible these changes are related to this? https://github.com/expo/expo/issues/1840

**Comment by edoantonioco** [comment]
So I answer my own question.
I have been trying `expo-cli` and I like all the new changes they did on it, cant wait to try it soon. But right now it gets corrupted after I run `npm install`. It says something about "cant find variable self".

So I hope all those small issues get fixed very soon so we can all enjoy all those awesome improvements.
