### ISSUE TITLE
Impossible To Customize The Default Expo Go Push Notification Icon On Android Devices

### ISSUE THREAD

**Issue by rkcollabro** [expo/expo#21917]
### Minimal reproducible example

https://snack.expo.dev/@randyk98/pushnotificationiconisbroken

### Summary

The default push notification icon for Expo Go (the upside-down 'V') is not customizable in any capacity when testing on an android device. The source of the tested push notification servers (Python backend with expo SDK or https://expo.dev/notifications tool) does not seem to matter. The notification always goes through no problem but the icon never changes - I have tried almost everything (clearing cache, changing dimensions, adjusting transparency, sending base64 data from the server, reinstalling the expo app, using a different android device, etc.), it does not work. I have not tested on an apple device.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\node_modules\.bin\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~48.0.9 => 48.0.9
      react: 18.2.0 => 18.2.0
      react-native: 0.71.4 => 0.71.4
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
as far as I know, it's not possible to customize this in Expo Go due to limitations of the native APIs. [you can create a development build with a custom notification as explained here](https://docs.expo.dev/versions/latest/sdk/notifications/#custom-notification-icon-and-colors) - this is a build time setting.
