### ISSUE TITLE
[expo-camera] onBarCodeScanned not fired in APK build

### ISSUE THREAD

**Issue by simonnilsson** [expo/expo#21929]
### Minimal reproducible example

https://snack.expo.dev/@simon.nilsson/basic-onbarcodescanned

### Summary

The minimal code example provided in snack is exactly the same as the example code for expo-camera, with the only addition being the onBarCodeScanned callback. Running with `expo start` via Expo Go works as expected on physical Android device. The callback gets called whenever a barcode or QR code gets scanned.

Building an APK via EAS Build and installing on the same devices everything works the same except that onBarCodeScanned callback never fires (no log output and no toast).

Built using command: `eas build -p android --profile preview`

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~48.0.9 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.4 => 0.71.4 
     expo-camera: ~13.2.1 => 13.2.1
    Expo Workflow: managed

**Comment by simonnilsson** [comment]
Installing **expo-barcode-scanner** (without actually using it anywhere) alongside expo-camera seems to make it work. I have no idea why though as the documentation doesn't state anywhere that this is a requirement for using the barcode functionality of expo-camera.

**Comment by TsplayerT** [comment]
I have this problem too

```
"expo": "~49.0.0",
"expo-camera": "~13.4.2"
```

**Comment by Hanro50** [comment]
This issue still persists.
I can also confirm that pulling in the expo barcode scanner package does fix the issue. 

Could it be a dependency issue with the expo-camera package in the sense that it fails to pull in the correct dependencies to allow for barcode scanning to function. An issue that is resolved when the barcode scanner package is added?

**Comment by LeNei** [comment]
I can confirm that this issue still persists with `"expo": "50.0.6"`. I've also tried to switch to the new CameraView, but at the moment it performs a lot worse on scanning barcode so its not a valid alternative. The fix with installing `expo-barcode-scanner` is also working on the current expo version.

**Comment by aakashv6433** [comment]
guys, even after installing expo-barcode-scanner it doesn't seem to be firing for some reason.

**Comment by wtcosta** [comment]
Instalei o "expo": "^51.0.30" e o problema persiste, no iOS funciona normal porem no android nada acontece!

**Comment by wtcosta** [comment]
I installed "expo": "^51.0.30" and the problem persists, on iOS it works normally but on Android nothing happens!
