### ISSUE TITLE
jest-expo tests fails with "ReferenceError: self is not defined"

### ISSUE THREAD

**Issue by asgerhallas** [expo/expo#2192]
### Environment

Environment:
  OS: Windows 10
  Node: 8.11.4
  Yarn: 1.3.2
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: expo/react-native#sdk-29 => 0.55.4

### Steps to Reproduce

1. Run create-react-native-app (+ install)
2. Run yarn test: everything runs as expected
3. Upgrade expo package from 27.0.0 to 29.0.0 (including corresponding react-native package and jest-expo)
4. Run yarn test: all tests crash with "ReferenceError: self is not defined"

Stacktrace:

      at node_modules/whatwg-fetch/dist/fetch.umd.js:8:40
      at Object.<anonymous>.support.searchParams (node_modules/whatwg-fetch/dist/fetch.umd.js:2:66)
      at Object.<anonymous> (node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
      at Object.<anonymous> (node_modules/jest-expo/src/setup.js:7:47)

### Expected Behavior

Tests would run successfully.

### Actual Behavior

All tests crash with "ReferenceError: self is not defined"

**Comment by asgerhallas** [comment]
Changing this line in `jest-expo/src/setup.js`: 

    const { Response, Request, Headers, fetch } = require('whatwg-fetch');

to:

    const { Response, Request, Headers, fetch } = require('isomorphic-fetch');

...seems to solve the problem.

**Comment by apaatsio** [comment]
Fix without modifying any code:
```
rm -rf node_modules
npm install whatwg-fetch@2.0.4 --save
npm install
```

Related items:
- https://github.com/expo/expo-cli/issues/28
- https://forums.expo.io/t/cant-find-variable-self/13547

**Comment by asgerhallas** [comment]
Thanks, that worked. And thanks for the background info too!

**Comment by Filipoz** [comment]
Hi everyone. I've been trying to fix this issue in my project for some time already but with no success.
I already removed all the files and reinstalled with Yarn with whatwg-fetch@2.0.4 but had no success.
Can anyone help me?

I have no big changes to my project yet and inited with Expo. Here's my package.json:
`{
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^31.0.2",
    "mappersmith": "^2.26.0",
    "moment": "^2.23.0",
    "native-base": "^2.8.1",
    "pagarme": "^3.9.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-base64": "^0.0.2",
    "react-native-flash-message": "^0.1.10",
    "react-native-masked-text": "^1.9.2",
    "react-native-rsa-native": "^1.0.24",
    "react-native-shadow": "^1.2.2",
    "react-native-vector-icons": "^6.1.0",
    "react-native-webview": "^2.14.3",
    "react-navigation": "3.0.0",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",
    "whatwg-fetch": "2.0.4"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-preset-expo": "^5.0.0",
    "eslint": "4.12.1",
    "eslint-config-prettier": "2.9.0",
    "eslint-plugin-prettier": "2.6.0",
    "eslint-plugin-promise": "3.6.0",
    "eslint-plugin-react": "^7.11.1",
    "pino-pretty": "2.2.3",
    "prettier": "1.10.2"
  }
}`
