### ISSUE TITLE
[docs] No information to enable Flipper on iOS ejected app

### ISSUE THREAD

**Issue by endruuu** [expo/expo#21926]
### Summary

I created a new Expo app using SDK 48, then ejected it.
However, Flipper doesn't detect my app and there's no information or docs on how to enable Flipper on iOS [here](https://docs.expo.dev/guides/using-flipper/) (or maybe I missed it?)

I printed out the Podfile and it's indeed disabled.

<img width="1440" alt="Screen Shot 2023-03-31 at 22 49 07" src="https://user-images.githubusercontent.com/80310153/229170787-f81d39c9-e0d9-4fc2-86de-93d90cb1454d.png">

Finally, the only way that worked is to add `"ios.flipper": "true"` onto `Podfile.properties.json` file.
```
{
  "expo.jsEngine": "hermes",
  "ios.flipper": "true"
}
```
NOTE the double quotation marks on the `true`.

I think we need to add that information onto the docs.
Or, maybe put the default key value pair onto the template.

### Link to the related docs page

https://docs.expo.dev/guides/using-flipper/

**Comment by amandeepmittal** [comment]
Hi @endruuu, when you say "ejected", what do you mean by that? Do you mean you are running `npx expo run:ios`?

**Comment by endruuu** [comment]
Hi @amandeepmittal. I mean I ejected it to bare workflow, using `npx expo eject`.

**Comment by amandeepmittal** [comment]
I don't understand what requirement you have to eject to bare workflow? Can you please elaborate on that? I think with [dev clients (expo-dev-client)](https://docs.expo.dev/development/create-development-builds/) you can achieve the same result.

**Comment by endruuu** [comment]
Hi. I need bare workflow because I need to integrate some native modules.
I think dev client is basically to provide Expo Go features, except that it is integrated into your app.

**Comment by amandeepmittal** [comment]
Using dev clients you can integrate native modules too. It's like creating a custom Expo Go version for your project with native libraries installed: https://docs.expo.dev/development/introduction/. You can also take a look into [Prebuilding](https://docs.expo.dev/workflow/prebuild/) which basically creates **android** and **ios** directories in your project.

I'll have to get back to you on this since I'm not sure what should be the expected behavior in case of "eject" since we do not recommend ejecting with latest SDKs and consider it a deprecated technology.

**Comment by endruuu** [comment]
Thanks Aman for your input. I think I'm an old guy. :D
I'm basically upgrading an old project (which uses bare workflow) to use the latest Expo SDK, because we have certain issue that might be caused by certain bug in the old React Native or Expo version.

Prebuilding might help, but I need to learn through again.

For now, I think I will close the issue as it is not relevant. Thanks for the information!

**Comment by amandeepmittal** [comment]
No worries at all! Feel free to open an issue if you get stuck somewhere.
