### ISSUE TITLE
[expo-image] considerable slower than RN Image

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#21921]
### Minimal reproducible example

https://github.com/RRaideRR/expo-image-slow

### Summary

I have a view inside my app where I display GIFs. For Android, using the Image component from React Native is a lot faster rendering these media files. With expo-image, it will take (on my Android phone) around **5 seconds** before the screen comes into view (see attached video). 

Notes: 
- after successfully rendering the expo-image screen for the first time, the next opening of the screen is super fast. 
- its also super slow when displaying the same media files in webp format.

The github repro also contains a build of the sample app build-1680256008378.apk.

https://user-images.githubusercontent.com/3411292/229103707-bd0eb848-94c5-4843-919b-6962bb7c34e8.mp4

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.9 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.4 => 0.71.4 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare
```

**Comment by lukmccall** [comment]
Hi @RRaideRR, could you try to use the newer version `1.1.0`? We introduced automatic downscaling which improves overall performance on Android.

**Comment by RRaideRR** [comment]
Hey @lukmccall. I tried it out with the newest version 1.1.0. I also [updated my repro](https://github.com/RRaideRR/expo-image-slow) where you can also find two apk builds so you can try it out faster by yourself.

I attached a video showing the new behavior which is probably even slower (cant take this for granted because my "n" is too small - just tried it out a couple of times).

In addition, the video will show another bug (I noticed this one in 1.0.0 as well): Sometimes (even though the images are already cached), the images won't be displayed. Instead only the placeholder will be shown. Navigating back multiple times to the view solves the issue (however: not always)

https://user-images.githubusercontent.com/3411292/229592625-c338920c-4f04-476d-9239-6d675a683009.mp4

**Comment by efstathiosntonas** [comment]
@RRaideRR  can you please check if there's a memory leak? I've noticed increased memory consumption even though I've not used `cachePolicy` prop (which defaults to `disk`)

**Comment by unlikeany-simon** [comment]
Same issue over here, is there a timeline when this will be addressed?

**Comment by RRaideRR** [comment]
> @RRaideRR can you please check if there's a memory leak? I've noticed increased memory consumption on my app even though I've not used `cachePolicy` prop (which defaults to `disk`)

Do you mean if there is a memory leak on the native side (so in expo-image itself)?

**Comment by MauriceStr** [comment]
Having the same problem here. I also noticed that there are performance issues on older iOS devices as well.

**Comment by RRaideRR** [comment]
Hey @lukmccall. Thanks a lot for your effort that you put into this 🙏. Highly appreciated!

The test on my Android simulator showed performance gains. In addition, the bug with the placeholders did not appear anymore (on the simulator as well as on real devices). So I would consider the "placeholder" bug as fixed.

However, regarding the performance issues: I tested it on two (rather low-medium end) Android devices and on these devices the performance gains are unfortunately barely visible. I'll attach two videos showing this. I also updated my repro with a new APK build with the expo-image 1.2.1 version.

 
Moto G8 power - Android 11
https://user-images.githubusercontent.com/3411292/232799348-b5b74a12-646c-4b2c-8d4d-0666130cb3ab.mp4


Samsung Galaxy A03s - Android 13
https://user-images.githubusercontent.com/3411292/232809886-63ffdee9-4421-4722-bc28-742e12a8a152.mp4

**Comment by bryanltobing** [comment]
In iOS, expo image is causing low FPS in screen transition using react navigation?

**Comment by gaearon** [comment]
We're seeing a (possibly related?) issue: https://github.com/bluesky-social/social-app/pull/1801

**Comment by gaearon** [comment]
Filed a new bug with a repro. https://github.com/expo/expo/issues/25201

**Comment by zachyc** [comment]
> In iOS, expo image is causing low FPS in screen transition using react navigation when rendering `GIF`. anyone experience the same issue?

I am seeing this as well. Did you find a solution for this?

**Comment by fendyk** [comment]
Same over here

**Comment by arasrezaei** [comment]
expo image is very slow at layouting
