### ISSUE TITLE
expo-linear-gradient

### ISSUE THREAD

**Issue by shiv-2810** [expo/expo#21922]
### Summary

class expo.modules.lineargradient.LinearGradientView does not have a primary constructor

### What platform(s) does this occur on?

Android

### SDK Version

47

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.3.1 - /opt/homebrew/bin/npm
      Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/shivam/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.5.1
      expo-cli: 6.0.8
    Expo Workflow: managed

### Minimal reproducible example

import { LinearGradient } from 'expo-linear-gradient';
<LinearGradient
      colors={['#4c669f', '#3b5998', '#192f6a']}
        ></LinearGradient>

package.json

"scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@feathersjs/authentication-client": "^4.5.15",
    "@feathersjs/feathers": "^4.5.15",
    "@feathersjs/rest-client": "^4.5.15",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-cookies/cookies": "^6.2.1",
    "@react-native-firebase/app": "^17.3.1",
    "@react-native-firebase/dynamic-links": "^17.3.1",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/native-stack": "^6.9.9",
    "@reduxjs/toolkit": "^1.9.3",
    "@tanstack/react-query": "^4.24.4",
    "axios": "^1.3.2",
    "expo": "~47.0.12",
    "expo-build-properties": "~0.4.1",
    "expo-dev-client": "~2.0.1",
    "expo-linear-gradient": "^12.1.2",
    "expo-linking": "~3.3.0",
    "expo-module-scripts": "^3.0.7",
    "expo-modules-core": "0.9.0",
    "expo-permissions": "~14.0.0",
    "expo-secure-store": "~12.0.0",
    "expo-sms": "~11.0.0",
    "expo-status-bar": "~1.4.2",
    "expo-web-browser": "~12.0.0",
    "firebase": "^9.17.1",
    "jwt-decode": "^3.1.2",
    "loadash": "^1.0.0",
    "moment": "^2.29.4",
    "nativewind": "^2.0.11",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-otp-textinput": "^1.0.0",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^3.0.2",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-shadow": "^1.2.2",
    "react-native-shadow-2": "^7.0.6",
    "react-native-shimmer-placeholder": "^2.0.9",
    "react-native-svg": "13.4.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.1",
    "react-redux": "^8.0.5",
    "tailwindcss-react-native": "^1.7.10"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@types/react-native": "^0.71.5",
    "tailwindcss": "^3.2.4"
  },
  "private": true

**Comment by Kudo** [comment]
hi there! `"expo-linear-gradient": "^12.1.2",` is incompatible with expo sdk 47. please try to run `npx expo install --fix` to fix those incompatible packages.
