### ISSUE TITLE
expo-sharing potentially using the wrong iOS view controller

### ISSUE THREAD

**Issue by b-hub** [expo/expo#21933]
### Minimal reproducible example

https://snack.expo.dev/@ben.magistris/expo-vs-react-native-file-sharing

### Summary

The [expo-sharing docs](https://docs.expo.dev/versions/latest/sdk/sharing/#sharingoptions) state:
> `expo-sharing` allows you to share files directly with other compatible applications.

As far as I can tell, `expo-sharing` uses the [UIDocumentInteractionController](https://developer.apple.com/documentation/uikit/uidocumentinteractioncontroller) to share files on iOS. 
> Use this class to present an appropriate user interface for previewing, opening, copying, or printing a specified file. For example, an email program might use this class to allow the user to preview attachments and open them in other apps.

Other file sharing APIs built around react-native like [react-native's Share](https://reactnative.dev/docs/share) & [react-native-share](https://github.com/react-native-share/react-native-share) are using [UIActivityViewController](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller) instead.
> The system provides several standard services, such as copying items to the pasteboard, posting content to social media sites, sending items via email or SMS, and more. Apps can also define custom services.

For the most part, `expo-sharing` does the job with [UIDocumentInteractionController](https://developer.apple.com/documentation/uikit/uidocumentinteractioncontroller), however some apps including 'Mail' on iOS do not appear as options, as well as some other niceties. From the Apple documentation it would seem like [UIActivityViewController](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller) is better suited for 'sharing' files.

|expo-sharing|react-native|
|-|-|
|![IMG_0016](https://user-images.githubusercontent.com/16084672/229240424-cfe85af1-e822-4e1d-a677-2501ceb29e0f.PNG)|![IMG_0015](https://user-images.githubusercontent.com/16084672/229240410-35ced1b9-0538-4ebd-bc8e-2f9d507b56ea.PNG)|

This issue looks to have been mentioned before in https://github.com/expo/expo/issues/7991 but was closed without a proper response/expo resolution. 

 It would be great to see this available in `expo-sharing` too, as we really need these share options and are having to look for alternative libraries.

Thanks!

### Environment

See linked Snack

**Comment by gabrieldonadel** [comment]
Closing this as https://github.com/expo/expo/pull/22012 updated `expo-sharing` to UIActivityViewController
