### ISSUE TITLE
Projects created with `expo-cli` gets corrupted after running `npm install`

### ISSUE THREAD

**Issue by edoantonioco** [expo/expo#2193]
So I wanted to try this https://github.com/react-native-community/discussions-and-proposals/issues/23

What happens is that a new project created with the new `expo-cli` runs fine, but once you run `npm install` it gets corruputed with the message provided below.

### Environment

Environment:
  OS: Linux 4.18
  Node: 8.11.4
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

app's target: Android

### Steps to Reproduce

1.Write on the terminal: "expo init nameOfProjectHere"
2.run 'npm install'
3.run 'npm run android' with the emulator open.

### Expected Behavior

To work as expected

### Actual Behavior

https://i.imgur.com/H9AwAcG.png

It throws an error: `Cant find variable self`

### Reproducible Demo
just a new app where you run 'npm install'

**Comment by sergburn** [comment]
Same here, got sample expo project to the same state by removing node_modules folder and then running `yarn install`.

**Comment by jper92** [comment]
same here, since yesterday I  couldn't develop anymore, using v29.0.0

**Comment by larsudengaard** [comment]
Solution proposed here works: https://github.com/expo/expo/issues/2192

```
rm -rf node_modules
npm install whatwg-fetch@2.0.4 --save
npm install
```

Hope this helps.

**Comment by edoantonioco** [comment]
yes, it does works. Now hopefully this will be fixed upstream.
