### ISSUE TITLE
[docs] `expo-location` configurable properties are incorrect

### ISSUE THREAD

**Issue by philiplindberg** [expo/expo#21945]
### Summary

One of the `expo-location` configurable properties is incorrectly documented. The property documented as `isIosBackgroundLocationEnabled` should actually be called `locationWhenInUsePermission`.

![CleanShot 2023-04-02 at 13 30 57@2x](https://user-images.githubusercontent.com/1865904/229352914-871262ef-1b9b-4118-9c50-4043c1f3322f.png)

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/location/#configurable-properties

**Comment by apedroferreira** [comment]
Thanks, I was kind of lost on this one.
I guess `isAndroidBackgroundLocationEnabled` might also be incorrect in the same way?

**Comment by philiplindberg** [comment]
When looking at the [source code](https://github.com/expo/expo/blob/sdk-48/packages/expo-location/plugin/src/withLocation.ts#L23-L30), it seems like `isIosBackgroundLocationEnabled` and `isAndroidBackgroundLocationEnabled` are valid properties as well. 

So really, the docs should be updated to include the following five configurable properties:

| Property  | Description |
| ------------- | ------------- |
| `locationAlwaysAndWhenInUsePermission` | Sets `NSLocationAlwaysAndWhenInUseUsageDescription` message (iOS only)  |
| `locationAlwaysPermission` | Sets `NSLocationAlwaysUsageDescription` message (iOS only)  |
| `locationWhenInUsePermission` | Sets `NSLocationWhenInUseUsageDescription` message (iOS only) |
| `isIosBackgroundLocationEnabled` | Adds `location` background mode to `Info.plist` (iOS only) |
| `isAndroidBackgroundLocationEnabled` | Sets `ACCESS_BACKGROUND_LOCATION` message (Android only) |

**Comment by wodin** [comment]
In addition to the above, the `useBackgroundPermissions` documentation says “Check or request permissions for the **_foreground_** location.”

**Comment by amandeepmittal** [comment]
This has been resolved #22309. Closing this for now.
