### ISSUE TITLE
[expo-image] Android crash with Canvas: trying to draw too large(126500000bytes) bitmap.

### ISSUE THREAD

**Issue by ugened47** [expo/expo#21949]
### Summary

While trying to migrate react-native-fast-image to expo-image I've got an app crash in my custom android dev client.
Occurs both in android emulator and on pixel 6 device.

I've found image url which expo-image don't like: [image](https://authencity.infura-ipfs.io/ipfs/QmZfD91daUztzd2ssx9o44yf2erxGMGb926uJshausLmeQ)

but its definitely not 126500000bytes it's 4 315 736 bytes (4,3 MB on disk)

Are there any kind of workaround to avoid such crashes?

**Note**: it also crashes with expo-go not only in custom dev-client

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~2.1.6",
"expo-image": "~1.0.0",
"expo-updates": "~0.16.3",

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.3
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.14.1 - ~/.asdf/installs/nodejs/lts/bin/node
Yarn: 3.3.1 - /usr/local/bin/yarn
npm: 9.3.1 - ~/.asdf/plugins/nodejs/shims/npm
Watchman: 2023.03.13.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.3 - /Users/napchik47/.asdf/shims/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
Android SDK:
API Levels: 29, 30, 31, 32, 33
Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.0, 33.0.1
System Images: android-33 | Google Play Intel x86 Atom_64
Android NDK: 22.1.7171670
IDEs:
Android Studio: 2021.3 AI-213.7172.25.2113.9123335
Xcode: 14.3/14E222b - /usr/bin/xcodebuild
npmGlobalPackages:
eas-cli: 3.8.1
expo-cli: 6.3.2
Expo Workflow: managed

### Reproducible demo

https://github.com/eugened-ith/expo-image-android-crash-repro

### Stacktrace (if a crash is involved)

ERROR Your app just crashed. See the error below.
java.lang.RuntimeException: Canvas: trying to draw too large(126500000bytes) bitmap.
android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
android.widget.ImageView.onDraw(ImageView.java:1446)
expo.modules.image.ExpoImageView.onDraw(ExpoImageView.kt:186)
android.view.View.draw(View.java:23194)
expo.modules.image.ExpoImageView.draw(ExpoImageView.kt:182)
android.view.View.updateDisplayListIfDirty(View.java:22061)
android.view.View.draw(View.java:22925)
android.view.ViewGroup.drawChild(ViewGroup.java:4529)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
android.view.View.updateDisplayListIfDirty(View.java:22052)
android.view.View.draw(View.java:22925)
android.view.ViewGroup.drawChild(ViewGroup.java:4529)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
android.view.View.updateDisplayListIfDirty(View.java:22052)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
android.view.View.updateDisplayListIfDirty(View.java:22017)
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
android.view.ViewRootImpl.draw(ViewRootImpl.java:4670)
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4381)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3600)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
android.view.Choreographer.doCallbacks(Choreographer.java:899)
android.view.Choreographer.doFrame(Choreographer.java:832)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
android.os.Handler.handleCallback(Handler.java:942)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loopOnce(Looper.java:201)
android.os.Looper.loop(Looper.java:288)
android.app.ActivityThread.main(ActivityThread.java:7872)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Kudo** [comment]
@lukmccall i can confirm to repro this issue on android api 33 emulator. could you help to check the issue when you get a chance?

**Comment by lukmccall** [comment]
Hello, @ugened47, thank you for submitting your report. In version 1.1.0, we have implemented automatic downscaling, which is now enabled by default. This feature will prevent the crash you encountered. However, please note that the image will be resized to match the viewport size, which appears to be the desired outcome based on your report. In my opinion, this is the optimal solution for your situation. You may also add the following lines to your manifest under the application tag, but I do not recommend doing so:
```
android:largeHeap="true"
android:hardwareAccelerated="false"
```

I will keep the issue open for now, as I am unsure why Android recognizes the provided image as exceptionally large.

**Comment by lukmccall** [comment]
The size of the decoded bitmap is accurate. Your image has dimensions of `5500 × 5750`, which amounts to a total of 31,625,000 pixels. Android utilizes the ARGB_8888 format to store decoded resources, where each pixel is represented by 4 bytes. Therefore, your image would require over 126 MB to display it using its native resolution.

I am considering adding an option to modify the used format. We could opt for `RGB_565`, which requires only 2 bytes per pixel, reducing the size by half. Nonetheless, this is still a large file size. If you are not developing image editing software, automatic downscaling will produce the best results. However, if that is not the case, setting the `largeHeap` and `hardwareAccelerated` options will help prevent crashes.

**Comment by bohdan145** [comment]
I am having the same problem
how do I add this lines in Expo ?
android:largeHeap="true"
android:hardwareAccelerated="false"

**Comment by lukmccall** [comment]
@bohdan145, if you're using managed workflow, you can create an expo config plugin to modify `AndroidManifest` - see https://docs.expo.dev/config-plugins/plugins-and-mods/#why-apppluginjs-for-plugins. In the case of the bare workflow, you can directly edit the app's manifest.

**Comment by bohdan145** [comment]
I've tried to add these changes using mods.android.manifest in app.config.js 
But it's not working 
Is the only way to create a custom plugin that changes the manifest file?

**Comment by shoaibarifArgonTech** [comment]
any update? @lukmccall @bohdan145 
how do I add this lines in Expo ?
android:largeHeap="true"
android:hardwareAccelerated="false"

**Comment by Julesssss** [comment]
Just wanted to note that disabling hardware acceleration app-wide can [heavily](https://github.com/Expensify/App/issues/34372#issuecomment-1889615889) reduce performance. Until we have a better fix I would suggest disabling hardware acceleration [just for the specific](https://developer.android.com/topic/performance/hardware-accel#controlling) View/Component that displays the image attachments.

**Comment by dutradotdev** [comment]
I had 7259x4531 image crashing my android app (w/ android crash with Canvas: trying to draw too large(126500000bytes) bitmap error)

resizing to 2000x1248 fixed the issue

scale down your image

**Comment by manthanindane** [comment]
I have image of size 694x920 pixels....and my other assets too are of smaller size...still my app is crashing....I don't know why.....

**Comment by NewCoder2023** [comment]
For me it was my splash Screen causing the problem. Check with a small image (small in px not file size) if this works.
