### ISSUE TITLE
Unable to upgrade to expo beta

### ISSUE THREAD

**Issue by nimish-kumar** [expo/expo#21947]
### Summary

I followed [Expo dev - SDK 48 beta](https://blog.expo.dev/expo-sdk-48-beta-is-now-available-7ee5713d0937) to upgrade my existing project to expo beta but it is currently throwing an error.
![Screenshot from 2023-04-02 20-39-57](https://user-images.githubusercontent.com/19932776/229361899-42a42555-f5c2-4c63-ac3d-ac6896f6cdb9.png)

![image](https://user-images.githubusercontent.com/19932776/229362020-d98ffa0b-decc-4e07-a959-d60061c09bba.png)

### SDK Version

47.0.13

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 Pop!_OS 22.04 LTS
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.3 - /usr/local/bin/npm
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.12 
![Screenshot from 2023-04-02 20-54-49](https://user-images.githubusercontent.com/19932776/229362575-cc7eecaf-e222-4871-8df9-0f65a896101e.png)

### Minimal reproducible example

Tried running `npm install expo@next`, but it is throwing following error.

```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for expo@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Kudo** [comment]
hi there! expo sdk 48 is released. please refer [this post](https://blog.expo.dev/expo-sdk-48-ccb8302e231) instead. namely you could try to run `npm install expo@latest` instead of the beta dist-tag. thanks!

**Comment by nimish-kumar** [comment]
Thanks @Kudo
