### ISSUE TITLE
[docs] Missing part for expo-notifications in bare workflow on Android 

### ISSUE THREAD

**Issue by matmartic** [expo/expo#21967]
### Summary

I detailed my problem [here](https://forums.expo.dev/t/bare-workflow-expo-notifications-error-on-android/70546) but TLDR : After setting up expo-notifications, I kept getting `[Error: Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Default FirebaseApp is not initialized in this process (bundle id for this project). Make sure to call FirebaseApp.initializeApp(Context) first.]` as error

After a lot of troubleshooting, I found that adding

In android/build.gradle, under dependencies ->`classpath('com.google.gms:google-services:4.3.15')`
In android/app/build.gradle -> `apply plugin: 'com.google.gms.google-services'`

Made the error go away and notifications work now.

I'm not 100% sure this is the correct way to fix that problem, but it did fix the problem for me. If this wasn't the correct way, I'd be thrilled to know of a better way to get over it.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/notifications/

**Comment by youngjun625** [comment]
Amazing. All the other answers related to this problem was saying 'it's probably misconfigured. Go through the docs again carefully." Was stuck on this for awhile and this answer solved my issue. On an additional note, I had to add the google-services.json file from firebase to android/app/google-services.json
Perhaps this is due to building the development build first, and then adding the expo-notification, google-services etc? Feel like the docs should definitely mention so.

**Comment by rieg-ec** [comment]
can confirm this worked:

In android/build.gradle, under dependencies ->classpath('com.google.gms:google-services:4.4.1')
In android/app/build.gradle -> apply plugin: 'com.google.gms.google-services'

**Comment by Bee-Taylor** [comment]
I just faced this problem and got stuck for a little while. My issue was that I didn't have

```JSON
"googleServicesFile": "./google-services.json"
```

in my app.json (see here: https://docs.expo.dev/versions/latest/config/app/#googleservicesfile).

Once I added that (with a `google-services.json` at the referenced relative path), running prebuild then successfully added the google-services config to `android/build.gradle` & `android/app/build.gradle`
