### ISSUE TITLE
[expo-av] - Video - HLS video - only audio works, but no picture - XCode 14.3 and  iOS 16.4 Simulator only

### ISSUE THREAD

**Issue by pavloihnatiev-atticmedia** [expo/expo#21973]
### Minimal reproducible example

https://github.com/pavloihnatiev-atticmedia/expo-av-hls-example

### Summary

After upgrading XCode to 14.3 the Expo AV Video player doesn't play HLS videos properly on iOS Simulator (16.4 only). I can hear the sound from the video, but cannot see the picture of the video.

The issue doesn't occur on older iOS versions - I tried to run the app on iOS 14.1 Simulator, and the video works fine. Also, the video works fine on real iOS devices with iOS 16.4 installed. So probably it's the Simulator only issue

I use Expo Bare Workflow on my project, but the issue is also reproducible with managed workflow

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.10 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    Expo Workflow: managed

**Comment by pehagg** [comment]
There's a [discussion](https://developer.apple.com/forums/thread/727288) over at the Apple Developer Forum about this.

**Comment by hamdij0maa** [comment]
the same issue here

**Comment by brentvatne** [comment]
I'm not sure this is actionable from us since this appears to be an iOS regression, I'll leave this issue open for now as we see how the conversation evolves on the Apple forums

**Comment by coofzilla** [comment]
The workaround I did was to install `Xcode 15.0 Beta 2` using `xcodes` so that I could have multiple version of xcode. After it prompted me to download `iOS 17.0` simulator. I tried just running it from here, didn't work. However, when I swapped back to `Xcode 14.3.1` and then selected the `iOS 17.0` simulator. Boom. Hope this helps someone 😅

**Comment by watadarkstar** [comment]
Did this issue ever get resolved? I'm still experiencing the issue with the following:

-     "expo": "49.0.21",
-     "expo-av": "~13.4.1",
- Xcode Version 14.3.1 (14E300c)
- Simulator iOS 16.4 on iPhone 14

**Comment by pehagg** [comment]
@watadarkstar , yes it did. Upgrade to latest Xcode + simulator(s).

**Comment by watadarkstar** [comment]
> @watadarkstar , yes it did. Upgrade to latest Xcode + simulator(s).

Ok thank you! I will try upgrading
