### ISSUE TITLE
iOS: Exif is not removed even setted to false

### ISSUE THREAD

**Issue by benhurott** [expo/expo#2198]
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.8.0
  Yarn: 1.9.2
  npm: 6.2.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: 28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

### Steps to Reproduce

- Create a component that uses camera.
- Request image with this options:
```
const CAMERA_OPTIONS = {
  quality: 0.4,
  base64: true,
  exif: false
}

this.camera.takePictureAsync(CAMERA_OPTIONS).then(data => {
  console.log(data)
})
```

### Expected Behavior
The resultant image must have no EXIF metadata.

### Actual Behavior
Using this tool: https://www.verexif.com

![image](https://user-images.githubusercontent.com/3187772/45432144-81d32380-b67f-11e8-97ef-366897d85606.png)

**Comment by bbarthec** [comment]
Hello @benhurott!
I've created [snack](https://snack.expo.io/@barthec/camera-exif) for your case.
From what I can see you misunderstand purpose of `exif` flag. Enabling it would provide you with separate result field that would hold object with actual EXIF metadata.
Explicit disabling this flag would not strip resulting image from EXIF tags and we would not like to do this in this method.
However your issue inspired us and we'll create `ImageManipulator` method for stripping out EXIF tags from images.
