### ISSUE TITLE
[expo-image] Image disappears before navigation animation is complete

### ISSUE THREAD

**Issue by efkann** [expo/expo#21993]
### Minimal reproducible example

https://github.com/efkann/expo-image-test

### Summary

Image disappears before the navigation animation is complete. To be honest, in this example it doesn't feel bad but once you add more images with different designs and shapes, it becomes annoying. I don't think this is the expected behaviour. This doesn't happen with React Native's built-in Image component which is the only reason I'm using that for now.

## To reproduce 

1. Open the project
2. Click the `Go to Image` link
3. Go back from the Image route
4. You'll notice that image gets hidden before the transition is complete.

I've used `slide_from_right` as the animation in this example because I believe it is when the issue is most noticeable.

Same thing happens with version `1.1.0` as well, havent tested this in IOS yet. I've also added the `apk` generated with EAS build development profile to the example repo.

https://user-images.githubusercontent.com/20632470/229991097-1634f0ea-b348-4d1e-aa70-218a454d0ed4.mp4

\
Could it be related to these ? 

https://github.com/DylanVann/react-native-fast-image/issues/767
https://github.com/software-mansion/react-native-screens/issues/797
https://github.com/software-mansion/react-native-screens/issues/773

### Environment

    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 19.8.1 - /opt/homebrew/bin/node
      npm: 9.5.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.10 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
      react-native-web: ~0.18.10 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 5.0.3
    Expo Workflow: managed

**Comment by JacobJaffe** [comment]
I'm also facing this issue. It's notably bad in scenarios where an underlying view is used (like a separate blurhash mounted beneath the image), and so there's a content flash.
