### ISSUE TITLE
ImagePicker/launchCameraAsync: dragging zoomed photo for cropping results in snapping back to top of viewport

### ISSUE THREAD

**Issue by btroia** [expo/expo#220]
When a photo is taken via ImagePicker/launchCameraAsync and the option has been set to constrain the image aspect ratio (i.e., 4x4 square), if you pinch zoom the photo and try to move the photo vertically down, the image will always snap to the top of the device viewport, not the crop area. See below - I tried to align the top of my photo with the top of the crop area, but when I release from press, it snaps back to top:

![img_1448](https://cloud.githubusercontent.com/assets/368747/26604117/4a274cee-4557-11e7-9021-474a51b18337.PNG)

**Comment by nikki93** [comment]
Hi @btroia,

As far as I'm aware, this is the behavior from the default system-provided iOS image picker, which is what we use to do this part of the interaction in our API. A way to get around this is to make a custom UI for this, which can happen if we provide a camera view that you can draw React elements over, for example. So it's a bit of a larger feature and not a quick fix on the current API.

**Comment by btroia** [comment]
Ok, thanks @nikki93 . It's a bit of a usability issue because when the user first sees the camera view there is no indication of the crop area, so they won't know if their photo will vertically be outside of the crop area until they select "use photo", then see the crop area overlay.

**Comment by btroia** [comment]
@nikki93 But why does choosing a photo from the camera roll function properly vs. taking a photo with the camera? The cropping step is exactly the same. This works as expected:

![img_1452](https://cloud.githubusercontent.com/assets/368747/26638642/9b2ac776-45f0-11e7-810a-9e4fbc411cc8.PNG)

**Comment by terribleben** [comment]
@nikki93 is right, this is the iOS system-provided behavior. You can read articles about it [here](https://stackoverflow.com/questions/20000273/uiimagepickercontroller-with-allowsediting-doesnt-allow-panning-to-crop) and [here](https://stackoverflow.com/questions/12630155/uiimagepicker-allowsediting-stuck-in-center). Notice those articles are not Expo-specific or RN-specific, they're just about the native iOS library that we're using. The solution will be to roll a custom version of this UI.

**Comment by nikki93** [comment]
Given that this is OS-level behavior under Expo, closing this issue for now. We may have a `CameraView`-style component in the future that you can implement a cropper over in JavaScript giving you full control.
