### ISSUE TITLE
Exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

### ISSUE THREAD

**Issue by AchrafBn** [expo/expo#22002]
### Summary

I get the following error when running `npx expo run:android`

<img width="1425" alt="Screenshot 2023-04-05 at 14 38 42" src="https://user-images.githubusercontent.com/11798130/230115230-b73f666d-0728-4f91-8595-5e1081f5a75b.png">

I've tried  `npx expo prebuild`  but I get the same message

**Java Version**
```
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```
### What platform(s) does this occur on?

Android

### SDK Version

47.0.12

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
      Yarn: 3.2.0 - ~/Documents/dev/maison-des-geants/node_modules/.bin/yarn
      npm: 8.19.4 - ~/Documents/dev/maison-des-geants/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/ma/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.0, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: 0.18.10 => 0.18.10
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

None

**Comment by AchrafBn** [comment]
I forgot to mention that it works with Android Studio

**Comment by AchrafBn** [comment]
I fixed it by upgrading  gradle

Ref : `https://stackoverflow.com/a/74695403/14512917`

**Comment by yussems** [comment]
i have same problem Java version 21 gradle 8.0

**Comment by yussems** [comment]
How to solve this problem

**Comment by sam-abdul** [comment]
> > i have same problem Java version 21 gradle 8.0
> 
> Same version here! Any chance you fixed it?

Go to this site to check the version of your Java and the gradle that is compatible with it.

https://docs.gradle.org/current/userguide/compatibility.html
