### ISSUE TITLE
expo 48 breaks async generators

### ISSUE THREAD

**Issue by jtc3161** [expo/expo#22006]
### Minimal reproducible example

https://snack.expo.dev/@jtc3161/2045e8

### Summary

In the minimum reproducible example, I have the barebones snack, with urql pulled and a basic graphql query implemented. This works fine on expo 47, but when I upgrade the snack to expo 48 using `npm uninstall expo` `npm install expo@48`, I get the error: `TypeError: undefined is not a function` on an async iterator call. The transformed js looks something like: `var t = e[Symbol.asyncIterator]();`. I imagine it has something to do with babel presets, but I have yet to track down the culprit. 

Note 1: this only seems to be an issue with the hermes engine. The web version works fine.

Note 2: Something about the context provider is causing an issue even on the sdk 47 version of the snack I provided, but I can confirm that downloading the snack, and running with `npx expo start` works fine.

Thanks for any help! hope this is an easy fix, I'll also continue digging

### Environment

SDK 47:
```
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Pop!_OS 22.04 LTS
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 20230326.214747.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ^47.0.13 => 47.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    Expo Workflow: managed
```
    
  SDK 48:
 ```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Pop!_OS 22.04 LTS
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 20230326.214747.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ^48.0.10 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
hey @jtc3161 - is this an issue with the react-native-babel-preset as well? note that expo-babel-preset is a small wrapper around that preset, to add support for web and several other features. in terms of javascript language features, we don't aim to provide a different experience from react-native's preset

**Comment by elisalimli** [comment]
@brentvatne 

> is this an issue with the react-native-babel-preset as well?

Yes, the same issue happens with `metro-react-native-babel-preset`
