### ISSUE TITLE
[Help] How can i view the pdf created by Print.printToFileAsync({ ‘html’: ‘<h1>wasup</h1>’})

### ISSUE THREAD

**Issue by themakerman** [expo/expo#2201]
Hi Guys,

Using the expo print api, When i use a file explorer app and navigate to the cache directory of expo app i don’t see anything. The uri which we get on console log in response to
`await Print.printToFileAsync({ 'html':'<h1>Wassup<h1>' });` is not accessible.

Can anybody please help me out? thanks

**Comment by esamelson** [comment]
Hi @themakerman - we're going to need more information in order to help you. Which platform and SDK version are you seeing this on? If you could provide a minimal repro case (ideally a [snack](https://snack.expo.io) as well, that would be great.

**Comment by themakerman** [comment]
@esamelson Hi, I am on android and using sdk 27. But I want to do the same thing for ios. I am working on a production app supporting both Android and iOS. I just want to save the html string as pdf in some directory so that user can open that pdf and print from some app. I would be generating pdf reports from my app so printing a simple html string is my milestone first.... Rest I believe will be more towards js sides of things on how I achieve my use case.... Thanks..

**Comment by esamelson** [comment]
Hi @themakerman - could you try upgrading to more recent SDK version? I think there have been some significant changes and improvements to the Print module since SDK 27 which may very well fix the issue you're seeing.

**Comment by themakerman** [comment]
Ok. Can you please check my code. I am on latest sdk 30 now.
```
async printToPdf() {
    const response = await Print.printToFileAsync({ 'html': '<h1>Wassup</h1>' });
    console.log(response);
    const createDirectory = await FileSystem.makeDirectoryAsync('file://data/user/0/com.scoreboardtech.walao');
    console.log(createDirectory);

  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={() => this.printToPdf()}>
          <Text>Save to pdf</Text>
        </TouchableOpacity>
      </View>
    );
  }
```

The console.log(response) shows it has a uri object containing:
`file:///data/user/0/com.scoreboardtech.savepdf/cache/ExperienceData/%2540scoreboardtech%252Fsavepdf/Print/2dedd3b4-79a8-4e7d-aec1-1609b427c471.pdf`

However when i navigate to this directory inside cache there is no such folder called as ExperienceData. I just want to access the .pdf file which is created so that i can print over the air using different printing apps available. Thanks.

The same thing i tried by detaching but doesn't helps. The result is the same.
So my question is, the thing that i am trying to achieve is it really achievable? like creating pdf from above expo api ---> save the .pdf ---> then opening the pdf using some other app and printing it via third party app? Thanks

**Comment by themakerman** [comment]
@esamelson  Ok. So the saving of pdf's and stuff can be done out of the box using android's inbuilt printing functionality. Nthing to do with expo. Just call 

```
const promise = await Print.printAsync({
      orientation: Print.Orientation.portrait,
      // markupFormatterIOS: `
      html: htmlString,
    });
```
and it will open up android's inbuilt print modal. Great. I thought its not going to work out of the box. The docs should mention something to make android users aware of printing. Can i submit a PR on docs? 

closing this issue.

**Comment by esamelson** [comment]
Hi @themakerman - glad you figured it out. Yes, please do submit a PR to the docs! 🙂 You can do so here: https://github.com/expo/expo-docs

**Comment by jarodsmk** [comment]
Came across this - been trying to figure out a similar thing myself, tried out @themakerman 's solution, but on iOS the data is printed differently (i had an image that prints on one page in Android, but 2 pages on iOS)

@esamelson  - When creating a file using `printToFileAsync(...)`, how does the user of a device get access to that file, and what is the recommended way of coding around that?

Many thanks in advance!
