### ISSUE TITLE
TypeError: _crypto.default.randomUUID is not a function

### ISSUE THREAD

**Issue by haochenuw** [expo/expo#22014]
### Summary

Got the above error after: 
- expo start --dev-client 
- scan the QR code generated with an iPhone 8 plus 

p.s. I don't know why the workflow is showing as "bare" -- I haven't made manual changes in the iOS folder at all. 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo-dev-client: ~2.1.6
expo-updates: ~0.16.4

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.15.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.10 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 5.4.8
    Expo Workflow: bare

### Reproducible demo

- expo start --dev-client 
- scan the QR code generated with an iPhone 8 plus

**Comment by johnotu** [comment]
In case anyone who has this problem comes here like I did, upgrading node to `> 14` where that method is available, fixes the problem

**Comment by timothyerwin** [comment]
I have node 18 and it still isn't working on android

``` _ExpoCrypto.default.randomUUID is not a function```

**Comment by jdhorner** [comment]
I'm on node 16 LTS and I receive the same problem: 

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: _ExpoCrypto.default.randomUUID is not a function
```

```js
import * as Crypto from 'expo-crypto';

export const ADD_TOAST = 'ADD_TOAST';

export const addToast = toast => ({
  type: ADD_TOAST,
  payload: { ...toast, id: Crypto.randomUUID() },
});
```

**Comment by itsramiel** [comment]
@danielkiesshau What do you mean by using specific version of node? Do you mean the node version installed on your system or do you have to specify it somewhere?

**Comment by jamesnottidge** [comment]
thank you @johnotu

**Comment by RafaelSanzio0** [comment]
thank you @johnotu it worked for me
