### ISSUE TITLE
exif is undefined

### ISSUE THREAD

**Issue by 025PRO** [expo/expo#2202]
### Packages: 
expo: 30.0.0
react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz

### Steps to Reproduce

- Create a component that uses camera.
- Request image with this options:

```
let photo = await this.camera.takePictureAsync({
    exif: true,
});
console.log('photo:', photo);
```
### Expected behaviour
The result image must have EXIF metadata and now `photo.exif` is undefined

Tried also with expo version 29 and got same result.

Tested only on iOS (simulator and device).

**Comment by bbarthec** [comment]
Hello @025PRO!
I've created [snack](https://snack.expo.io/@barthec/camera-exif) for your case and nothing you're saying is happening is actually happening on both iOS and Android devices. (simulator would fail though 😞)
I've tried sdks 29 and 30 and everything worked on physical devices.

**Comment by 025PRO** [comment]
Hi @bbarthec 
Thanks for your response. 
Yes I tried your snack and it worked as expected on my device. For now I can say only that 1 week ago that code worked in my project but it's started to miss the exif data after that. So as I remember I've updated expo version in this period of time from 28 to 29 and hoping that the 30th version will fix that case moved to 30th. I doubt if that maybe the case?
Actually today I tried to downgrade to 28th version but got the same result. It's weird. 
I will be able follow up with this on Monday and to hopefully find a solution.

**Comment by 025PRO** [comment]
Hey @bbarthec 
So I rechecked the issue today and find out that the issue was caused for not being synced with expo.
Everything works fine now. Thanks!

**Comment by Patriciadburns1** [comment]
What data is in the exif data @bbarthec . Is it only height/ width?  What other metadata can you possibly retrieve from the photo?

**Comment by bbarthec** [comment]
@Patriciadburns1, in general `expo-camera` exposes any EXIF data that is obtainable from device on native layer.
You can see `iOS` [here](https://github.com/expo/expo/blob/master/packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m#L134) and `Android` [here](https://github.com/expo/expo/blob/master/packages/expo-camera/android/src/main/java/expo/modules/camera/tasks/ResolveTakenPictureAsyncTask.java#L97). Most noticeable additional metadata are `orientation` or `gps positioning`.
