### ISSUE TITLE
Exception occurred while executing exported method requestPermissionsAsync on module ExpoBrightness: permission cannot be null or empty

### ISSUE THREAD

**Issue by maxenceg** [expo/expo#22024]
### Minimal reproducible example

https://github.com/maxenceg/expo-brightness-demo

### Summary

Whenever I try to request permissions for expo-brightness on Android, I get the following error:

```
Error: Encountered an exception while calling native method: Exception occurred while executing exported method requestPermissionsAsync on module ExpoBrightness: permission cannot be null or empty
```
![image](https://user-images.githubusercontent.com/38657323/230419249-1a4e8be0-90b5-4785-a017-5ffdb58dd42c.png)
<img width="397" alt="image" src="https://user-images.githubusercontent.com/38657323/230420196-5610b879-ccd1-45fe-9680-e70a4d17e847.png">

It seems to work fine on iOS (because no permissions are needed I guess)

To reproduce, you can clone [the repository I provided](https://github.com/maxenceg/expo-brightness-demo) and run `npx expo run:android`

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2023.02.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.10 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.8
    Expo Workflow: bare

**Comment by brentvatne** [comment]
@alanjhughes - would you be able to investigate this? perhaps this was introduced in re-writing ios for the new api

**Comment by alanjhughes** [comment]
@brentvatne it has only been rewritten for iOS but I seen this issue and have a PR that rewrites android #22037 the issue is newer versions of android can't request the system permission anymore. We can remove all the system brightness functions from android and neither iOS or Android will require permission for the remaining functionality.

**Comment by gabrieldonadel** [comment]
@alanjhughes which android version are you using?
