### ISSUE TITLE
[docs] Remove facebookScheme from docs, not supported in SDK 48+

### ISSUE THREAD

**Issue by theo-wall** [expo/expo#22026]
### Minimal reproducible example

https://github.com/Manifest-Labs/expo-sdk48-facebook-issue

### Summary

After updating expo SDK 47 => 48 and following steps detailed in the expo SDK 48 blog post.

1. `npm i -g eas-cli`
2. `npm install expo@^48.0.0`
3. `npx expo install --fix`
4. `npx expo-doctor`

When running `expo-doctor` or trying to build the app, a validation error occurs in the `app.json` file that `facebookScheme` should NOT be an additional property. However when following the expo documentation for creating a [AuthSession ](https://docs.expo.dev/versions/latest/sdk/auth-session/#facebook) that the:
```
- The URI redirect must be added to your app.config.js or app.json as facebookScheme: 'fb<YOUR FBID>'.
```
when following those instructions the app.json validation fails with the following error:
```
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✖ Validating Expo Config failed
Issues:
  Error: Problem validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
   • should NOT have additional property 'facebookScheme'.
✔ Checking package.json for common issues passed

✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.
```

I've also tried passing the facebookScheme as an array with the app scheme described in the expo docs [here](https://docs.expo.dev/guides/facebook-authentication/#add-a-scheme) which also failed validation with the following error:
```
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✖ Validating Expo Config failed
Issues:
  Error: Problem validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
   • Field: scheme - must be string.
✔ Checking package.json for common issues passed

✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.
```

I also found that another user [here](https://github.com/expo/expo/issues/21507) was experiencing the same issue but failed to provide a reproducible repo.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.1 
      expo: ^48.0.0 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by slvssb** [comment]
Any updates on this?

**Comment by Kudo** [comment]
hi there! there might be some outdated doc. if removing the `facebookScheme` in app.json, does it work for you?

**Comment by theo-wall** [comment]
Hey @Kudo I ended up passing `facebookScheme` as `scheme` since we are using deep linking we didn't need to have our project scheme for linking. It's worked for us so far, is that the correct way to pass the `facebookScheme`? Thanks!

**Comment by royraider** [comment]
Well the impact is not so little since it disable Facebook Login on Android from working in production (I think),

I tried a lot of work arround but I need my sheme to be something for Android Google Connect in order to work and something else for Facebook on Android. 

Since we can't use Array on Scheme, and facebookScheme not working anymore... Well. I have to chose between having Android Google Connect or Facebook Connect. This issue isn't that small and My client expect to have both this week for an event. :')

**Comment by DavidAPears** [comment]
Is there any update on this, please? I am getting the same error after upgrading to SDK 48

```
Error: Problems validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'facebookAppId'.
 • should NOT have additional property 'facebookDisplayName'.
 • should NOT have additional property 'facebookScheme'.
```


<img width="884" alt="Screenshot 2023-08-17 at 17 29 54" src="https://github.com/expo/expo/assets/36195948/88701536-1356-41a6-9578-11d27c12470e">

**Comment by khalidkanear** [comment]
Android Bundling failed 50ms
Unable to resolve module common/src from /Users/pukat/Downloads/mobile-app/App.js: common/src could not be found within the project or in these directories:
  node_modules
  21 |   FirebaseProvider,
  22 |   store
> 23 | } from 'common/src';
     |         ^
  24 | import AppCommon from './AppCommon';
  25 |
  26 | Notifications.setNotificationHandler({

**Comment by khalidkanear** [comment]
smae eror

**Comment by lemanrs** [comment]
was this resolved? having the same issue 

Error: Problems validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'facebookAppId'.
 • should NOT have additional property 'facebookAutoLogAppEventsEnabled'.
 • should NOT have additional property 'facebookAutoInitEnabled'.
