### ISSUE TITLE
eas build -- platform ios run fastlane fail

### ISSUE THREAD

**Issue by DionRama** [expo/expo#22022]
### Summary

error: File /Users/expo/Library/Developer/Xcode/DerivedData/MOVA-agbxpyfyqhsozigktympmxsbfwpu/Build/Intermediates.noindex/ArchiveIntermediates/MOVA/BuildProductsPath/Release-iphoneos/MOVA.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

  "dependencies": {
    "@expo/webpack-config": "^18.0.1",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/netinfo": "9.3.7",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "expo": "~48.0.9",
    "expo-linear-gradient": "~12.1.2",
    "expo-status-bar": "~1.4.4",
    "firebase": "^9.18.0",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.6",
    "react-native-calendars": "^1.1294.0",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-web": "~0.18.11"
  },
  "devDependencies": {
    "@expo/config-plugins": "~6.0.0",
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.27",
    "@types/react-native": "^0.71.4",
    "prettier": "^2.8.7",
    "tailwindcss": "^3.2.7",
    "typescript": "^4.9.4"
  },

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.3
      expo: ~48.0.9 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
      react-native-web: ~0.18.11 => 0.18.12
    Expo Workflow: managed

### Reproducible demo

git add . 

git commit - "feat: update" 

git push 

eas build --platform ios

**Comment by sergeybok** [comment]
Did you solve this?

**Comment by DionRama** [comment]
> Did you solve this?

Yeah i think it was just problems with new updates now it is working fine just dit a expo update and got the job done

**Comment by DionRama** [comment]
> Did you solve this?

if you still have problems with it just update eas.jason cli to 3.9.1

**Comment by sergeybok** [comment]
This doesn't seem to work for me, but thanks for the advice anyways. I was at 3.9.0 then tried 3.9.1 then tried 3.9.2 (which is what turned out to be my eas version since I've updated it earlier trying to solve this bug). 

Do you know if local eas version matters, should I downgrade my eas version to 3.9.1 locally?

**Comment by DionRama** [comment]
> This doesn't seem to work for me, but thanks for the advice anyways. I was at 3.9.0 then tried 3.9.1 then tried 3.9.2 (which is what turned out to be my eas version since I've updated it earlier trying to solve this bug).
> 
> Do you know if local eas version matters, should I downgrade my eas version to 3.9.1 locally?

Personally, I updated the version manually in "eas.json" inside my project because updating it globally did not work for me either.
