### ISSUE TITLE
Impossible to execute run on ios simulator

### ISSUE THREAD

**Issue by zell180** [expo/expo#22034]
### Summary

Running command npx expo run:ios not complete.
I've applyed this fix react-native-maps-plugin.js in app.json -> plugins

`// react-native-maps-plugin.js
const fs = require("fs");
const path = require("path");
const generateCode = require("@expo/config-plugins/build/utils/generateCode");
const configPlugins = require("@expo/config-plugins");

const code = `# Note you don't need to add RNBootSplash or react-native-app-auth if unused
$static_library = [
 'React',
 'Google-Maps-iOS-Utils',
 'GoogleMaps',
 'react-native-maps',
 'react-native-google-maps',
 'React-hermes'
]

pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      bt = pod.send(:build_type)
      if $static_library.include?(pod.name)
        puts "Overriding the build_type to static_library from static_framework for #{pod.name}"
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
    installer.pod_targets.each do |pod|
      bt = pod.send(:build_type)
      puts "#{pod.name} (#{bt})"
      puts "  linkage: #{bt.send(:linkage)} packaging: #{bt.send(:packaging)}"
    end
end`;

module.exports = (expoConfig) => {
  return configPlugins.withDangerousMod(expoConfig, [
    "ios",
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );
      const contents = fs.readFileSync(filePath, "utf-8");

      const addCode = generateCode.mergeContents({
        tag: "withReactNativeFirebase",
        src: contents,
        newSrc: code,
        anchor: /\s*get_default_flags\(\)/i,
        offset: 2,
        comment: "#",
      });

      if (!addCode.didMerge) {
        console.error(
          "ERROR: Cannot add withReactNativeMaps to the project's ios/Podfile because it's malformed."
        );
        return config;
      }

      fs.writeFileSync(filePath, addCode.contents);

      return config;
    },
  ]);
};`

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

{
  "name": "my_app",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.18.0",
    "@react-native-firebase/app": "^17.4.0",
    "@react-native-firebase/auth": "17.4.0",
    "@react-native-firebase/crashlytics": "^17.4.0",
    "@react-native-firebase/perf": "^17.4.0",
    "@react-native-google-signin/google-signin": "^9.0.2",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "@reduxjs/toolkit": "^1.9.3",
    "expo": "~48.0.10",
    "expo-auth-session": "~4.0.3",
    "expo-build-properties": "~0.5.1",
    "expo-crypto": "~12.2.1",
    "expo-dev-client": "~2.1.6",
    "expo-device": "~5.2.1",
    "expo-location": "~15.1.1",
    "expo-modules-core": "^1.2.6",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "expo-web-browser": "~12.1.1",
    "firebase": "^9.19.1",
    "install": "^0.13.0",
    "lottie-react-native": "^6.0.0-rc.3",
    "moment": "^2.29.4",
    "npm": "^9.6.2",
    "react": "18.2.0",
    "react-native": "0.71.6",
    "react-native-a11y-slider": "^1.1.1",
    "react-native-bouncy-checkbox": "^3.0.7",
    "react-native-dropdown-select-list": "^2.0.4",
    "react-native-expo-cached-image": "^1.3.1",
    "react-native-gesture-flip-card": "^1.0.6",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-map-link": "^2.10.2",
    "react-native-maps": "^1.4.0",
    "react-native-pager-view": "^6.2.0",
    "react-native-qrcode-svg": "^6.2.0",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-select-dropdown": "^3.3.2",
    "react-native-svg": "13.4.0",
    "react-native-webview": "^11.26.1",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.2 - ~/Progetti/LCG_Assistant/node_modules/.bin/npm
      Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.10 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare

### Reproducible demo

npx expo prebuild --clean
npx expo run:ios

### Stacktrace (if a crash is involved)

`Start Packager on http://localhost:8081

❌  (ios/Pods/Target Support Files/Pods-MyApp/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-abmxavpwexjsfxaxpwbartuyhsdm/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.framework/Modules/ExpoModulesCore.swiftmodule
   9 | import ExpoAdapterGoogleSignIn
  10 | import EXConstants
  11 | import ExpoCrypto

❌  (ios/Pods/Target Support Files/Pods-MyApp/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-abmxavpwexjsfxaxpwbartuyhsdm/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.framework/Modules/ExpoModulesCore.swiftmodule
   9 | import ExpoAdapterGoogleSignIn
  10 | import EXConstants
  11 | import ExpoCrypto

    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')

› 2 error(s), and 8 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.`

**Comment by jojohoooo** [comment]
I have the same problem. Have you found a solution to this problem? @zell180

**Comment by zell180** [comment]
Yes do this:
`npx expo prebuild --clean`

Than add this to Podfile in ios folder
`pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/googlemaps/google-maps-ios-utils.git', :commit => '637954e5bcb2a879c11a6f2cead153a6bad5339f'`

And then:
```
cd ios/
pod install
cd ..
```

`npx expo run:ios`

And now should work
