### ISSUE TITLE
Can not use input type = “file” in webview. (Android)

### ISSUE THREAD

**Issue by ru88s** [expo/expo#2203]
Can not use input type = “file” in webview. (Android)
The upload button does not respond.

Is there a solution?

**Packages:**
expo: 30.0.0
react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz

**Steps to Reproduce**
```
import React, { Component } from 'react';
import { WebView } from 'react-native';

export default class App extends Component {
  get html() {
  return '<!DOCTYPE html>\
    <html lang="en">\
    <head>\
      <meta charset="UTF-8">\
      <meta name="viewport" content="width=device-width, initial-scale=1.0">\
      <meta http-equiv="X-UA-Compatible" content="ie=edge">\
      <title>Document</title>\
    </head>\
    <body>\
      <input type="file"/>\
    </body>\
    </html>'
  }
  
  render() {
    return (
      <WebView style={{margin: 40}} source={{html: this.html}}/>
    );
  }
}
```

**Reproducible Demo**
Snack: https://snack.expo.io/BJSrAK2yM

**Expected Behavior**
Image upload in webview.

**Comment by esamelson** [comment]
Hi @ru88s - this is a known issue (or missing feature) in React Native's built-in WebView component. Your best bet is to follow [this issue](https://github.com/react-native-community/react-native-webview/issues/33) in the new `react-native-webview` repo which will soon replace the built-in WebView component in RN. Unfortunately this is not something that Expo is specifically planning to introduce to our fork of RN.

**Comment by ru88s** [comment]
Hi @esamelson - understood. Thank you very much. I always appreciate Expo.

**Comment by zjx** [comment]
@esamelson thanks for that.

**Comment by dhiraj1site** [comment]
Any updates on this ?

**Comment by dhiraj1site** [comment]
Hi @esamelson , the issue is said to be resolved in RN thread , but does not work in latest version of expo any plans for fixes ?
