### ISSUE TITLE
[docs] Issue in the Tap gesture handler function  docs

### ISSUE THREAD

**Issue by IRSHIT033** [expo/expo#22041]
### Summary

![Screenshot (84)](https://user-images.githubusercontent.com/83210491/230711064-e2d2124f-b5c7-4823-a2b1-6f0f54ae8164.png)

this function won't work on typescript because of type mismatching.

 tap gesture handler function is more applicable here

### Link to the related docs page

https://docs.expo.dev/tutorial/gestures/

**Comment by brentvatne** [comment]
we'll chat with the reanimated team to see how they'd recommend typing this. closing this issue as discussed in https://github.com/expo/expo/pull/22042#issuecomment-1501844852
