### ISSUE TITLE
Cannot read property 'decelerationRate' of undefined (jest-expo)

### ISSUE THREAD

**Issue by JoostSlijkoort** [expo/expo#2204]
After upgrading to Expo SDK 30 (and jest-expo 30.0.0), all of my tests fail, displaying the error `TypeError: Cannot read property 'decelerationRate' of undefined`.

### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.2
  Yarn: Not Found
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Targets: iOS / Android

My jest.config.js:
```
// @flow

module.exports = {
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!react-navigation|react-native|expo|@expo/vector-icons|native-base|native-base-shoutem-theme)',
  ],
  moduleNameMapper: {
    '\\.(eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/__mocks__/fileMock.js',
    '\\.(jpg|jpeg|png|gif|svg)$': '<rootDir>/__mocks__/sourceMock.js',
    'styled-components': '<rootDir>/node_modules/styled-components/dist/styled-components.native.cjs.js',
  },
  setupTestFrameworkScriptFile: '<rootDir>/app/testhelpers/styledComponents.js',
  setupFiles: [
    '<rootDir>/app/testhelpers/setupTests.js',
    '<rootDir>/app/testhelpers/i18nextMockSetup.js',
  ],
  coverageThreshold: {
    global: {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
    './app/store/**/sagas.js': {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
    './app/store/**/sagas/*.js': {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
    './app/helpers/**/*.js': {
      statements: 80,
    },
  },
};
```

### Steps to Reproduce

1. Upgrade a SDK 29 version to SDK 30 version
2. Run npm run test
3. See all tests fail with the following error:
`TypeError: Cannot read property 'decelerationRate' of undefined`

### Expected Behavior
Succeeding tests, just like on version 29.

### Actual Behavior
All of my tests fail.

**Comment by tsapeta** [comment]
Hey, sorry we haven't taken any action with this issue for so long 😞 Is this still an issue for you? Feel free to reopen if so. Also let us know at which SDK you're now as SDK30 is already not supported.
