### ISSUE TITLE
[IOS Standalone] SDK 30 there was a problem loading the requested app

### ISSUE THREAD

**Issue by SimoneLSK** [expo/expo#2205]
A brand new expo apps does not work after detached 

os: iOS, 
SDK version: 30,
cli version: 2.0.0
connected to same network

procedure: 
1. create new app with `expo init `
2. run `yarn install` 
3. try to run on simulator before detach with `expo start`, (**WORKS**)
4. detach app with ExpoKit by running `expo eject`, choose `ExpoKit`
5. `pod install` at ./ios
6. open ./ios with **xcode** and run **build**, app installed on device
7. launch app and splash screen appear
8. error pop-up with **there was a problem loading the requested app**

<img width="1052" alt="screen shot 2018-09-14 at 7 11 59 pm" src="https://user-images.githubusercontent.com/26976153/45547775-8d2b7800-b854-11e8-9b2f-3934ef476053.png">

Please help, thanks

**Comment by alangf** [comment]
Having the same issue, already reinstalled node_modules and pods.

**Comment by tsapeta** [comment]
Sorry for this inconvenience 😞 We've just published ExpoKit v2.8.2 for ejected apps, so you can try to update it in your Podfiles or just create a new app using `expo init` and then `expo eject`. Let me know if you have any questions 😉

**Comment by SimoneLSK** [comment]
**IT WORKS**

Thank you so much `Tsapeta` & `Expo` Team for the quick action

**Comment by aniltirola** [comment]
for me now everything is solved and working with creating a brand new expo-app:

```
expo init -t blank testsdk30
```

I had some small issues after ejecting. But it could be solved by reinstalling modules:

```
rm -Rf ./node_modules
yarn
```
…then it worked

thanks to the expo-developers

**Comment by javi10823** [comment]
I have the same issue with SDK 31 and ExpoKit 2.9.0 ,Any solution to this problem?

<img width="545" alt="captura de pantalla 2019-01-11 00 56 06" src="https://user-images.githubusercontent.com/1581454/51015098-94843900-1549-11e9-9b6a-2a3318cad03b.png">

**Comment by javi10823** [comment]
it's working now for me. When I executed this command ---> `expo start --no-dev --minify` some files has changed and this process added the url of expo dev in my code of iOS.
and then It’s working with only executing `expo start` 
`expo start`
run expo start without problems and run app the app from Xcode
