### ISSUE TITLE
Copy Button Does Not Reflect Code Snippet

### ISSUE THREAD

**Issue by narcelin** [expo/expo#22058]
### Summary

jsx Button.js on line 410 (COPY) is missing FontAwesome import line

### Link to the related docs page

https://github.com/expo/expo/blob/main/docs/pages/tutorial/build-a-screen.mdx?plain=1

### Anything else?

Apologize if this is improper etiquette. My first time submitting an issue on gh. Please feel free to give any feedback. I tried to be short and sweet. Thank you.

**Comment by amandeepmittal** [comment]
Thanks for reporting this @narcelin! It seems like a bug to me. We'll look into fixing it.
