### ISSUE TITLE
expo SDK 48 iOS build failed

### ISSUE THREAD

**Issue by kirtikapadiya** [expo/expo#22061]
### Minimal reproducible example

https://github.com/kirtikapadiya/exposdk48

### Summary

platform : ios

Running "expo doctor"
- Validating global prerequisites versions...
✔ Validating global prerequisites versions passed
- Checking for incompatible packages...
✔ Checking for incompatible packages passed
- Checking for conflicting global packages in project...
✔ Checking for conflicting global packages in project passed
- Verifying prebuild support package versions are compatible...
✔ Verifying prebuild support package versions are compatible passed
- Checking dependency versions for compatibility with the installed Expo SDK...
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
- Validating Expo Config...
✔ Validating Expo Config passed
- Checking package.json for common issues...
✖ Checking package.json for common issues failed
Issues:
[stderr] 
The following scripts in package.json conflict with the contents of node_modules/.bin: eslint.
[stderr] 
✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.
Command "expo doctor" failed.
npx exited with non-zero code: 1

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.2
      expo: ^48.0.0 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    Expo Workflow: managed

**Comment by kirtikapadiya** [comment]
https://github.com/expo/expo/issues/21423

**Comment by brentvatne** [comment]
see this related error https://github.com/npm/npm/issues/7130

**Comment by brentvatne** [comment]
see this related error https://github.com/npm/npm/issues/7130

**Comment by kirtikapadiya** [comment]
@brentvatne  after removing eslint from package.json and add 
 "overrides": {
    "@expo/config-plugins": "~6.0.0",
    "@expo/prebuild-config": "~6.0.0"
  } in package.json file will fix the issue of **The following scripts in package.json conflict with the contents of node_modules/.bin: eslint.** but still iOS build failed.
![iosbuildfailed](https://user-images.githubusercontent.com/20786875/231070177-baadf273-7b1f-489f-bd69-d5db3ce8a5dd.PNG)
