### ISSUE TITLE
"Preview" builds from EAS crash immediately, local dev-client ok, prebuild fails too

### ISSUE THREAD

**Issue by lucksp** [expo/expo#22065]
### Minimal reproducible example

https://gist.github.com/lucksp/1943464fc3e7977aee0885dbea4be482

### Summary

Running the command to make a preview build in Expo/EAS using the command `eas build --platform ios --non-interactive --profile development-internal` builds successfully.  Once installing on a device (or running `prebuild` on local machine), the app freezes and seems to be having an issue loading the JS Bundle.

[4952d063f63e Build](https://expo.dev/accounts/fluidtruck/projects/delta/builds/417059f9-c4d2-47d9-94f9-4952d063f63e) from Apr 5, 2023 11:31 AM works fine after installing on the device.
The next day, a new commit is made - NO NEW dependencies or anything - [and c4ffcbd83a2e crashes](https://expo.dev/accounts/fluidtruck/projects/delta/builds/aab2d50c-2c16-48a8-803c-c4ffcbd83a2e), on Apr 6, 2023 12:07 PM.  
We also successfully [released to TestFlight](https://expo.dev/accounts/fluidtruck/projects/delta/builds/452f4e6c-4e9a-4d37-a3ec-a409412f839e) on Apr 5, 2023 1:00 PM

ALL OTHER BRANCHES (including develop) fail too since sometime between April 5 to April 6.  

---

We use the EAS + Managed workflow since we have dependencies that are not supported by Expo.  Our GitHubActions uses the `eas:ci` command below.  The issue is replicated if I kick off the same command locally.  The issue is replicated if I run `eas:build.stage.test` and upload to test flight.

The `expo-dev-client` simulator & device builds are running OK.

Check `package.json`, `eas.json`, and `app.config` in repro link gist.

---

Additionally, I have tried the `prebuild` debugging to see if it too would replicate on my local machine, and it is able to be reproduced.

Tried running prebuild with the `--no-dev` flag also, but no changes in outcome.

---
We have a 2nd project within our organization.  

[43b3efac7710 build works](https://expo.dev/accounts/fluidtruck/projects/rock-lobster/builds/338c8e9a-94d2-4bc4-bafa-43b3efac7710) on Apr 5, 2023 1:09 AM
Today, after the initial finding, [6e3b99090f23 build fails](https://expo.dev/accounts/fluidtruck/projects/rock-lobster/builds/217357ae-6ad2-46b8-835f-6e3b99090f23) like the other project, Apr 7, 2023 10:53 AM

---

Filing this bug is at the suggestion of @alanjhughes , who [chatted with me on discord](https://discord.com/channels/695411232856997968/943205994123657246/threads/1094006006360580176) and does not believe it is related to my settings.

Together, we are unable to locate the issue of our code having an issue, so it seems plausible there is **an EAS issue**, as it's happening across multiple projects of ours.

I appreciate your time to look into this.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.19 => 46.0.20 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by lucksp** [comment]
your support is abysmal TBH.  I was told by your support agent in Discord to open a ticket

**Comment by alanjhughes** [comment]
@lucksp Sorry if their was a misunderstanding but I am not a support agent for expo. I just try to help out in the community but I am not a part of the expo team in any way.

**Comment by brentvatne** [comment]
@lucksp - to clarify our support - we do not provide consulting services to help you with application development. if you have found a bug with the tooling then we can help you with that! the code that you provided is not anywhere near a minimal reproducible example, which indicates that there is more debugging work needed on your end to understand the root cause of the issue. 

> Additionally, I have tried the prebuild debugging to see if it too would replicate on my local machine, and it is able to be reproduced.

this is a great step! now that you can reproduce it locally, you can aggressively remove code until you are no longer able to reproduce. then, add code back until it returns. then remove smaller pieces until it goes away, repeat until you found the thing that seems to cause it. if this alone doesn't give you the information you need to solve the issue, then you may proceed to remove all other extraneous code, verify that it does indeed still reproduce, then post an issue with the minimal reproducible example you created. learn more here: https://expo.fyi/manual-debugging
