### ISSUE TITLE
Custom font is not loading correctly on Android

### ISSUE THREAD

**Issue by felipej26** [expo/expo#22074]
### Minimal reproducible example

https://snack.expo.dev/@felipej26/custom-font-is-not-loading-correctly-on-android

### Summary

Hi, I'm able to load a custom font on iOS, but it is not loading correctly on Android. The font has a stroke in the letters and on Android, this stroke is not showing.
I have tested it on real devices, emulators, and in the [Snack](https://snack.expo.dev/@felipej26/custom-font-is-not-loading-correctly-on-android), and in all cases, it works on iOS but not on Android. 
I'm importing the font using expo-font and I have tried with the formats: .ttf, .otf, .woff, .woff2.

![Screenshot 2023-04-10 at 18 43 31](https://user-images.githubusercontent.com/16179920/231007863-27010134-51f9-4488-9622-93bbaf22fd48.png)

### Environment

expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 13.1
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  npmPackages:
    expo: ~48.0.9 => 48.0.9 
    react: 18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-web: ^0.18.12 => 0.18.12 
  npmGlobalPackages:
    expo-cli: 6.0.8
  Expo Workflow: bare

**Comment by brentvatne** [comment]
what font family is that? I notice in the example you shared, it has the same behavior on web. It may be that when using a font that has an outline, you need to set the outline color on those platforms. I'm not familiar with that and would be interested in learning more about this font

**Comment by felipej26** [comment]
> what font family is that? I notice in the example you shared, it has the same behavior on web. It may be that when using a font that has an outline, you need to set the outline color on those platforms. I'm not familiar with that and would be interested in learning more about this font

It's a custom font I've asked a designer to create it. In fact, it has an outline, but I could not find a prop to set the outline in the StyleProp<TextStyle>(https://reactnative.dev/docs/text#style). 
That's a link for the font: [ToiletGaming](https://drive.google.com/drive/folders/1G3Gz4gVwWvEvBoUq2NOVo98EjaZ6Lyqk?usp=sharing)

Is there a way to set the outline?

**Comment by brentvatne** [comment]
do you know what the underlying Android API would be for setting the stroke color? or web API?

**Comment by felipej26** [comment]
I know for web API, it's:
`-webkit-text-stroke: 4px blue;`

But, for Android, I've found a way to this by calling the onDraw method twice:

Custom TextView:

    @Override
    protected void onDraw(Canvas canvas) {
        int textColor = getTextColors().getDefaultColor();
        setTextColor(Color.BLACK);
        getPaint().setStrokeWidth(10);
        getPaint().setStyle(Paint.Style.STROKE);
        super.onDraw(canvas);
        setTextColor(textColor);
        getPaint().setStrokeWidth(0);
        getPaint().setStyle(Paint.Style.FILL);
        super.onDraw(canvas);
    }

XML:
```
    <com.example.testtextwithstroke.TextWithStroke
        android:id="@+id/textview_first"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/hello_first_fragment"
        android:textColor="#FF0000"
        app:layout_constraintBottom_toTopOf="@id/button_first"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

The result is:
![Screenshot 2023-04-10 at 21 06 01](https://user-images.githubusercontent.com/16179920/231022309-c3bb2360-49b9-4f30-8d98-09ee87d34ac3.png)
