### ISSUE TITLE
Expo Client v2.8.0 crashes when push notification received when app is open

### ISSUE THREAD

**Issue by brentkirkland** [expo/expo#2207]
Hello,

Your new app v2.8.0 update has causes the app to crash when the registered listener from Notifications.addListener() fires. 

I have something as simple as:
```
  handleNotifications(notification) {
    console.log(notification)
  }

  componentDidMount() {
    Notifications.addListener(this.handleNotifications)
  }

```
I am sending the notification not within the app but from an external REST call (private API) with a simple `{ body: 'hello', title: 'New Message' }` payload.

This error only happens on iOS. No problems with Android

**Comment by brentkirkland** [comment]
Tagging @rverbytskyi so he can follow the issue

**Comment by brentkirkland** [comment]
I have tested this with v30.0.0 and @rverbytskyi with v29.0.1 -- both crash

**Comment by brentkirkland** [comment]
Commenting out Notifications.addListener(this.handleNotifications) does not remedy the issue.

**Comment by esamelson** [comment]
Hi @brentkirkland - apologies that this seems to have slipped through the cracks. I just tried to reproduce this on the latest version of the Expo client (2.8.2) and could not. Could you provide a [snack](https://snack.expo.io) that reliably repros this?

**Comment by iChaosren** [comment]
Hi,

I build a snack using the basic permissions request and it crashes the entire expo client app on my phone as soon as it loads.

I've tested this with both: 
Permissions.askAsync() and Permissions.getAsync()

Both give the same error.

[https://snack.expo.io/@ichaosren/push-notification-crash-example](https://snack.expo.io/@ichaosren/push-notification-crash-example)

I'm running it on a iPhone X with iOS 12.0.1

It's crashing on my other apps too...

**Comment by tsapeta** [comment]
Unfortunately I wasn't able to reproduce this issue 😞 This issue refers to a pretty old version of the client app, so I believe it's been fixed since then. Please create a new issue if this still happens in any of the currently supported SDK versions.
