### ISSUE TITLE
[docs] Mods object is not property of ExpoConfig

### ISSUE THREAD

**Issue by SihamBen** [expo/expo#22078]
### Summary

I'm trying to create a mod, but the documentation is a little bit confusing, based on the documentation you can add mods to app.config this way 
```module.exports = {
  name: 'my-app',
  mods: {
    ios: {
      /* iOS mods... */
    },
    android: {
      /* Android mods... */
    },
  },
};
```
However the mod object is not recognised as a property of ExpoConfig, I checked ExpoConfig type file but no trace of a property called mods

### Link to the related docs page

https://docs.expo.dev/config-plugins/plugins-and-mods/#create-a-plugin

**Comment by Kudo** [comment]
hi there! [the section](https://docs.expo.dev/config-plugins/plugins-and-mods/#create-a-plugin) is basically to explain what's a mod. for most of time, you don't have to write a custom mod. in rare case if the default mods/plugins don't fit your need, you could refer [this guide](https://docs.expo.dev/config-plugins/development-and-debugging/#custom-base-modifiers) to write a custom mod.

**Comment by SihamBen** [comment]
Thank you 🙏
