### ISSUE TITLE
EAS build for iOS getting failed with Error for Expo 48: PhaseScriptExecution [CP-User]\ Generate\ Specs

### ISSUE THREAD

**Issue by viveksc1994** [expo/expo#22085]
### Minimal reproducible example

https://github.com/viveksc1994/expo-48-eas-build-ios

### Summary

While generating build (`npx eas build --platform ios`) for iOS it getting failed with below errors
Build ID from expo.dev : 892d8a00-f90f-4010-b684-315802a6dc58

> The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/FBReactNativeSpec.build/Script-46EB2E00011590.sh (in target 'FBReactNativeSpec' from project 'Pods')
	SwiftCompile normal x86_64 Compiling\ KeepAwakeModule.swift /Users/expo/workingdir/build/node_modules/expo-keep-awake/ios/KeepAwakeModule.swift (in target 'ExpoKeepAwake' from project 'Pods')
(2 failures)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.211.0                 |
| sdk         | iPhoneOS16.2.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[stderr] 
[!] Error building the application - see the log above
Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.2
      expo: ~48.0.0 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    Expo Workflow: managed

**Comment by brentvatne** [comment]
if you look at the full build logs:

```
Error: Cannot find module 'yargs'
Require stack:
- /Users/brentvatne/code/expo-48-eas-build-ios/node_modules/react-native/scripts/generate-specs-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
```

it seems that legacy peer deps breaks the generate-specs-cli script, i imagine they rely on `yargs` as a peer dep which normally gets hoisted or autoinstalled, but does not in this case. i would not recommend using legacy peer deps, but if you insist on doing so you can submit a PR to https://github.com/facebook/react-native to potentially add `yargs` as a dependency - i'm not sure it'll be accepted though.

build works fine if you delete `.npmrc` and `package-lock.json` and `node_modules` then reinstall deps.
