### ISSUE TITLE
uncaught error:java.net.socketTimeoutException: failled to connect to /192.168.154.1(port 19000)

### ISSUE THREAD

**Issue by adityakmr7** [expo/expo#2208]
Expo is not connecting to my Android device 

Error log: in my android device
`uncaught error:java.net.socketTimeoutException: failled to connect to /192.168.154.1(port 19000)`

although QR code is generated fine in bash terminal .

Here is screenshot of error in android device
![screenshot_2018-09-15-07-55-02-121](https://user-images.githubusercontent.com/36496640/45581500-ee873180-b8bc-11e8-8a5b-d76d0f9c1b61.jpeg)

**Comment by lashleykeith** [comment]
I have this problem but it was working for me just three days ago.
