### ISSUE TITLE
Android stuck on Splash screen after reloading 

### ISSUE THREAD

**Issue by hoekma** [expo/expo#2209]
I recently upgraded my environment to SDK v29 and then v30.  After I did that my app started having some problems reloading while I was doing development where it would freeze on the splash screen.  I'm developing on a MacBook using XDE.  

The screen that rendered was actually active. When I pressed where the buttons were supposed to be, the app would respond to my presses based on seeing console output that I would expect when the buttons were pressed. I traced the problem back to some of my components returning <Expo.AppLoading /> while the components were waiting for a state that allowed the screen to actually render the UI components (waiting for API calls to return data).   

Replacing the <Expo.AppLoading> with `<View><Text>Loading...</Text></View> `made the problem go away.  Here is the strange behavior from my Android device.  I didn't test on iOS:

1. Run the app -- it loaded and rendered fine
2. Navigate to a page whose render() returned <Expo.AppLoading>
3. Pull down from the top of the screen to show the Expo menu and reload the app
4. The  app reloads, but only shows the splash screen.  The buttons were active on the screen where I expected had the UI to have rendered.  I could see the console output from the reload in the XDE interface.
5. Pull down from the top of the screen to show the expo menu and reload the app
6. Phone continues to show the splash screen
7. This time the app does NOT reload.   There is no console output in XDE and the invisible buttons were no longer active.
8. Now Expo seems frozen to any further reloads.
9. Terminate the process of my project on my phone and relaunch my project from Expo. 
10. Same behavior as steps 6 - 9 
11. Terminate processes for BOTH the Expo and my own project on the phone
12 Now it runs fine as step 1 and renders the app until I load the screen that renders the <Expo.AppLoading> 

I've removed all of the <Expo.AppLoading> from my app and am back in business.  This behavior is new since I upgraded the SDK.  I think it was probably never the right thing to return <Expo.AppLoading> in my screens.   It probably still shouldn't cause the behavior I was experiencing.

**Comment by msevestre** [comment]
I have a similar problem. However my app is using SDK 28 and I updated the expo app on device to the latest version.

On my Android device, the app is stuck on Splash screen as well. I did not change any code aside from updating the expo app on my phone.

My app is using AppLoading as well.

What do you mean with 

> Replacing <Expo.AppLoading> with Loading..

Thanks

Michael

**Comment by hoekma** [comment]
@mseverste -- Sorry, the text editor swallowed some of the text I put in.... I've fixed it now.

**Comment by msevestre** [comment]
@hoekma After full reboot of phone, mac expo etc... my issue was gone.

**Comment by docaustyne** [comment]
how did you fix this issue? we are having same issue, IOS workes great, but Android freezes at welcome screen. What can we do please?

**Comment by cruzach** [comment]
Closing this issue since it seems to have been solved, if you have problems with the AppLoading module, please open up a new issue with a repro
