### ISSUE TITLE
Error failed to start daemon

### ISSUE THREAD

**Issue by ShintaroNippon** [expo/expo#221]
I'm using genymotion for free and run nexus 5 virtual device.
Then i turn on the adb for adndorid sdk and exp path command line.
I just follow the instructions.
but i' getting this error:

> Couldn't start project on Android: could not install smartsocket listener: cannot bind to 127.0.0.1:5037: Normalmente só é permitido uma utilização de cada endereço de socket (protocolo/endere��o de rede/porta). (10048)
> could not read ok from ADB Server
> 
> failed to start daemon *
> error: cannot connect to daemon

and

> Couldn't start project on Android: Error running adb: ** daemon still not running
> error: cannot connect to daemon: cannot connect to 127.0.0.1:5037: Nenhuma ligação pôde ser feita porque o computador de destino
> 
> as recusou ativamente. (10061)
> i just create a new project empty view in expo xde installed genymotion and android sdk and follow the instructions.
> 

Thanks in advance
Carlos Vieira

**Comment by terribleben** [comment]
Hello! Can you make sure you've followed [these instructions](https://docs.expo.io/versions/latest/guides/genymotion.html#step-1-use-the-same-version-of-the-android-tools-everywhere) so Genymotion understands where to find adb?

If you're still encountering an issue after that, please open a Help topic on our [forums](https://forums.expo.io/c/help).
