### ISSUE TITLE
Conditional import error

### ISSUE THREAD

**Issue by etiennelacoursiere** [expo/expo#22102]
### Minimal reproducible example

https://github.com/etiennelacoursiere/expo-bug-repro

### Summary

I have an expo project with both natives apps and a web app currently on the SDK 46. I have in app purchases setup with `expo-in-app-purchases` and everything is working great.

After upgrading to SDK 48, the web app won't build and the reason seems to be that we are importing `expo-in-app-purchases` even though the import of the module is behind a `Platform.OS !== 'web'` check. 

Again, everything is working as is on SDK 46. I didn't see a breaking change on the way the imports work? Maybe i missed something?  

The exact error is this: 
![image](https://user-images.githubusercontent.com/12648647/231529683-878baba2-23b8-47ca-a83d-d354df3f430b.png)

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 3.5.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 16.13.2 - ~/.asdf/installs/nodejs/16.13.2/bin/node
      Yarn: 1.22.15 - ~/.asdf/installs/nodejs/16.13.2/bin/yarn
      npm: 8.1.2 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.4 => 18.0.4
      expo: ~48.0.10 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
      react-native-web: ~0.18.10 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.9.1
      expo-cli: 6.3.2
    Expo Workflow: managed

```

**Comment by brentvatne** [comment]
i'd suggest using `.native.js` and `.web.js` files instead of optional imports in order to ensure that only the required code is imported - this is more reliable than inline imports. additionally - our support for webpack on web is not currently actively maintained as we are beginning to migrate towards using metro instead.

**Comment by mad-wizard** [comment]
This is still a serious issue, the package is totally unusable: 

Also getting:

TypeError: Cannot read property '__expo_module_name__' of undefined

From simply importing:

**Comment by mad-wizard** [comment]
Very frustrating since I can't seem to get any other in app purchases working with expo either. Is there a specific setup required for EAS apps?

**Comment by brentvatne** [comment]
from the expo-in-app-purchases documentation page:

<img width="868" alt="image" src="https://github.com/expo/expo/assets/90494/f979e5a8-15f6-4ce9-b926-ded398c11332">

we recommend using revenuecat
