### ISSUE TITLE
eas submit -p android - fastlane fail

### ISSUE THREAD

**Issue by pedron3to** [expo/expo#22103]
### Summary

Bug Description:
The app submission process to Play Store is failing due to a nested ASN1 error with OpenSSL PKey RSA.

Expected behavior:
The app submission process should complete successfully without any errors.

Current behavior:
The submission process is failing with an OpenSSL PKey RSA error, and the app cannot be submitted to the Play Store. 

Steps to reproduce:
Start the app submission process to the Play Store.
Wait for the submission process to fail due to OpenSSL PKey RSA error.

All these prerequisites below were handle: [Prerequisites](https://docs.expo.dev/submit/android/#prerequisites)
- A paid developer account is required — You can create a Google Play Developer account on the [Google Play Console sign-up page](https://play.google.com/apps/publish/signup/).
- You have to create a [Google Service Account](https://cloud.google.com/iam/docs/creating-managing-service-accounts) and download its JSON private key.
- After that, you'll have to create an app on [Google Play Console](https://play.google.com/apps/publish/) and upload your app manually at least once.
- You will also need to have EAS CLI installed and authenticated with your Expo account: npm install -g eas-cli && eas login.

### SDK Version

48.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.9 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare

### Minimal reproducible example

Starting the submit process
Downloading archive
Preparing artifact
Submitting Android app to Play Store...
Submitting the app with fastlane supply
[stderr] 
/var/lib/gems/2.7.0/gems/googleauth-1.5.0/lib/googleauth/service_account.rb:71:in `initialize': [!] Neither PUB key nor PRIV key: nested asn1 error (OpenSSL::PKey::RSAError)
[stderr] 
	from /var/lib/gems/2.7.0/gems/googleauth-1.5.0/lib/googleauth/service_account.rb:71:in `new'
[stderr] 
	from /var/lib/gems/2.7.0/gems/googleauth-1.5.0/lib/googleauth/service_account.rb:71:in `make_creds'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:49:in `initialize'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:19:in `new'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:19:in `make_from_config'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/uploader.rb:425:in `client'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/uploader.rb:7:in `perform_upload'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:40:in `block (2 levels) in run'
[stderr] 
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
[stderr] 
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
[stderr] 
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[stderr] 
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:61:in `run'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:13:in `start'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
[stderr] 
	from /usr/local/bin/fastlane:23:in `load'
[stderr] 
	from /usr/local/bin/fastlane:23:in `<main>'
[stderr] 
/var/lib/gems/2.7.0/gems/googleauth-1.5.0/lib/googleauth/service_account.rb:71:in `initialize': Neither PUB key nor PRIV key: nested asn1 error (OpenSSL::PKey::RSAError)
[stderr] 
	from /var/lib/gems/2.7.0/gems/googleauth-1.5.0/lib/googleauth/service_account.rb:71:in `new'
[stderr] 
	from /var/lib/gems/2.7.0/gems/googleauth-1.5.0/lib/googleauth/service_account.rb:71:in `make_creds'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:49:in `initialize'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:19:in `new'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/client.rb:19:in `make_from_config'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/uploader.rb:425:in `client'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/uploader.rb:7:in `perform_upload'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:40:in `block (2 levels) in run'
[stderr] 
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
[stderr] 
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
[stderr] 
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[stderr] 
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:61:in `run'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/supply/lib/supply/commands_generator.rb:13:in `start'
[stderr] 
from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
[stderr] 
	from /var/lib/gems/2.7.0/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
[stderr] 
	from /usr/local/bin/fastlane:23:in `load'
[stderr] 
	from /usr/local/bin/fastlane:23:in `<main>'
+---------------------------------+------------------------------------------------------------------------------------------------+
|                                                    Summary for supply 2.191.0                                                    |
+---------------------------------+------------------------------------------------------------------------------------------------+
| aab                             | /tmp/submissions/79e1b793-75cb-47f3-a098-79f08ab8d0e2/bb10f494-4760-4362-a6db-c5d4e8b411cd.aab |
| track                           | internal                                                                                       |
| json_key                        | /tmp/submissions/***/service-account.json                     |
| package_name                    | com.inventory2                                                                                 |
| changes_not_sent_for_review     | false                                                                                          |
| release_status                  | draft                                                                                          |
| skip_upload_apk                 | false                                                                                          |
| skip_upload_aab                 | false                                                                                          |
| skip_upload_metadata            | false                                                                                          |
| skip_upload_changelogs          | false                                                                                          |
| skip_upload_images              | false                                                                                          |
| skip_upload_screenshots         | false                                                                                          |
| validate_only                   | false                                                                                          |
| check_superseded_tracks         | false                                                                                          |
| timeout                         | 300                                                                                            |
| deactivate_on_promote           | true                                                                                           |
| ack_bundle_installation_warning | false                                                                                          |
+---------------------------------+------------------------------------------------------------------------------------------------+
Looking for related GitHub issues on fastlane/fastlane...
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Fastlane supply failed
fastlane exited with non-zero code: 1
Failed to submit the app
We couldn't figure out what went wrong. See logs to learn more.

**Comment by brentvatne** [comment]
can you please share a link to the submission page?

**Comment by pedron3to** [comment]
https://expo.dev/accounts/fortispay/projects/inventory/submissions/ef353c72-74d9-4758-b48a-d55fcefaf7a7

**Comment by brentvatne** [comment]
@pedron3to - can you try a submission again? it looks like this was from 8 days ago. there may have been an intermittent issue at the time (I'm following up with the team on that) but we're not seeing any similar errors for submissions at the moment. if you see the same error now, I suspect there may be something specific to the project configuration and the error could be a red herring (eg: service account key may be incorrect)

**Comment by pedron3to** [comment]
Hi, follow another link of the submission: 

https://expo.dev/accounts/fortispay/projects/inventory/submissions/1497f33a-1970-4ffe-b505-ba51e4efd6f5

**Comment by brentvatne** [comment]
@pedron3to - can you try updating your service account key to a new one? I suspect this is a bad error message from fastlane for an invalid service account key

**Comment by pedron3to** [comment]
Yes, I will request for the team lead create another one. Thank you for your help
