### ISSUE TITLE
Android standalone app adaptive icon background color not applied

### ISSUE THREAD

**Issue by ietz** [expo/expo#2210]
### Environment
**Environment:**
  OS: Windows 10
  Node: 10.9.0
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  1.4.0.0 AI-141.2288178

**Packages:** (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

**Diagnostics report:**
  https://exp-xde-diagnostics.s3.amazonaws.com/ietz-5f28a255-9d17-4517-947f-4588bd74d5b2.tar.gz

### Steps to Reproduce

1. Start with any working expo project
2. Add to your `app.json` expo config, using any transparent image as `foregroundImage` (e.g. [this](https://user-images.githubusercontent.com/3751802/45595214-ab09f180-b9a8-11e8-82d1-fa4ec3797746.png))
```
"android": {
  "adaptiveIcon": {
    "backgroundColor": "#3861b1",
    "foregroundImage": "./assets/icon-fg.png"
  }
}
```
3. Build the standalone android app using `expo ba` and install the .apk

### Expected Behavior

The dark-ish blue background color [#3861b1](https://www.colorhexa.com/3861b1) should be used as a background for the transparent [foreground image](https://user-images.githubusercontent.com/3751802/45595214-ab09f180-b9a8-11e8-82d1-fa4ec3797746.png), resulting in something similar to  
<img src="https://user-images.githubusercontent.com/3751802/45595344-654e2880-b9aa-11e8-8cdc-e5321ee4ebce.png" width="64" />

### Actual Behavior

The default white background is used instead  
![actual](https://user-images.githubusercontent.com/3751802/45595389-1b197700-b9ab-11e8-80e7-edb0e6611e87.png)

### Reproducible Demo

https://github.com/ietz/expo-adaptive-icon-report

**Comment by esamelson** [comment]
Hi @ietz - sorry for the slow followup here. We had a regression in our standalone app builders that caused this issue. It should be fixed now if you make a new build.

**Comment by ietz** [comment]
Thanks a lot! I can confirm that it is now indeed working as intended  
Have a great day, @esamelson !

**Comment by ericorruption** [comment]
Is this solved? I tried building just now but it still keeps the white background.

**Comment by ericorruption** [comment]
I think it's worth pointing out that the foregroundImage **needs** to be defined - it doesn't use the `icon` key as a fallback.

**Comment by esamelson** [comment]
@ericorruption could you share your affected build ids? And you're right, if you want to use an adaptive icon then you do need to define `foregroundImage`. (The fallback to the `icon` key is only for if you don't want to specify an adaptive icon and instead just let the OS decide for you.)

**Comment by ericorruption** [comment]
@esamelson thank you for the support. The problem was indeed the missing `foregroundImage`. Still think it would be worth making it explicit in the docs that this key is mandatory to properly have an adaptive icon.

**Comment by esamelson** [comment]
@ericorruption thanks for the suggestion. I've made this change -- you can see it here https://github.com/expo/expo-docs . If you have any other suggestions for improving our docs, we happily accept PRs! 🙂
