### ISSUE TITLE
[expo-image-picker] launchCameraAsync Null Pointer exception for Android 13

### ISSUE THREAD

**Issue by witheroux** [expo/expo#22122]
### Minimal reproducible example

https://github.com/witheroux/expo-image-picker-bug

### Summary

When calling `launchCameraAsync()` on Android 13, the call is rejected with the following error : 
```
[Error: Call to function 'ExponentImagePicker.launchCameraAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method host.exp.exponent.experience.d.checkSelfPermission, parameter permission]
```

This is because the `ensureCameraPermissionsAreGranted()` function calls `permissions.askForPermission()` with a null value for Android 13 because of [line 216 of `ImagePickerModule.kt`](https://github.com/expo/expo/blob/2bb404496e118df3488a155489ea2a6c36a71d0c/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt#L216).

**To reproduce**
1. Pull repo at https://github.com/witheroux/expo-image-picker-bug
2. Run `yarn && yarn start` or `npm i && npm start`
3. Open in Expo Go on Android 13
4. Tap "Request permissions" if the permissions are not already granted
5. Tap "Launch camera"
6. Observe the error log in the terminal

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9787799
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.10 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.9.1
    Expo Workflow: managed

**Comment by johannessachse** [comment]
I can confirm this issue.
Android 11 -> works correctly
Android 13 -> does not work

Tested with `expo-image-picker` version 14.1.1

**Comment by witheroux** [comment]
The fix is already commited and will most likely be released with the next version of the Expo SDK. In the meantime, a patch with `patch-package` works well for me.


`patches/expo-image-picker+14.1.1.patch`
```patch
diff --git a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
index 4d5d3e7..9329b6f 100644
--- a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
+++ b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
@@ -213,8 +213,10 @@ class ImagePickerModule : Module() {
           continuation.resumeWithException(UserRejectedPermissionsException())
         }
       },
-      Manifest.permission.WRITE_EXTERNAL_STORAGE.takeIf { Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU },
-      Manifest.permission.CAMERA
+      *listOfNotNull(
+        Manifest.permission.WRITE_EXTERNAL_STORAGE.takeIf { Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU },
+        Manifest.permission.CAMERA
+      ).toTypedArray()
     )
   }
 
```
