### ISSUE TITLE
expo-doctor reports invalid version of expo-modules-autolinking on SDK 48.0.11

### ISSUE THREAD

**Issue by Yusfuu** [expo/expo#22138]
### Minimal reproducible example

npx expo-doctor

### Summary

I update the expo SDK from 48.0.10 to 48.0.11 and when I run npx expo-doctor its prints:

Issues:
  Expected package expo-modules-autolinking@~1.1.0
  Found invalid:
    expo-modules-autolinking@1.2.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 31, 33, 33
        Build Tools: 30.0.3, 33.0.0, 33.0.2, 34.0.0
        System Images: android-UpsideDownCake-ext5 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.11 => 48.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: bare

**Comment by prakharraj1302** [comment]
same issue

**Comment by garawalid** [comment]
We are facing the same issue

**Comment by ianstarsolo** [comment]
Same issue.
To reproduce, create a new project:
npx create-expo-app --template
then launch npx expo-doctor
results:
**Issues:
  Expected package expo-modules-autolinking@~1.1.0
  Found invalid:
    expo-modules-autolinking@1.2.0
    (for more info, run: npm why expo-modules-autolinking)**

**Comment by macksal** [comment]
For anyone who just upgraded to Expo 48, I have worked around this issue by upgrading to exactly `"expo": "48.0.10"`.

**Comment by GabrielBeltran7** [comment]
> Para cualquiera que acaba de actualizar a Expo 48, he solucionado este problema al actualizar exactamente a `"expo": "48.0.10"`.

me funciono
