### ISSUE TITLE
Error: Location '(index.android)

### ISSUE THREAD

**Issue by kadirguloglu** [expo/expo#22135]
### Minimal reproducible example

Error: Location '(index.android)

### Summary

Error: Location 'file:///data/data/com.gspace.android/virtual/data/user/0/com.secimvizyon.app/cache/ExponentAsset-b62641afc9ab487008e996a5c5865e56.ttf' isn't writable.

![image](https://user-images.githubusercontent.com/28136387/232125600-896f6fd1-ac14-4372-acac-4933cf5090f3.png)
![image](https://user-images.githubusercontent.com/28136387/232125678-e9c0a162-9f7e-4d1e-b3e4-7affaf03621f.png)
![screencapture-secimvizyon-sentry-io-issues-4084996895-2023-04-14-21_21_261](https://user-images.githubusercontent.com/28136387/232126420-5f81a893-d676-4959-ba77-52dbd5adb4a0.png)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30, 31, 32
        Build Tools: 32.0.0, 32.1.0
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.2 
      expo: ^48.0.9 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

**Comment by sevketaydogdu** [comment]
i am getting the same error. Please help

**Comment by ibrahimoz** [comment]
i am getting the same error. Please help

**Comment by AmpoB** [comment]
I have the same issue, can anyone solve this?

**Comment by BatDroid** [comment]
same issue
