### ISSUE TITLE
Face detection bug 

### ISSUE THREAD

**Issue by xwiz** [expo/expo#22144]
### Minimal reproducible example

https://snack.expo.dev/@patacee/quick-face-detection

### Summary

Using the default example in [the documentation](https://docs.expo.dev/versions/latest/sdk/facedetector/), Should be able to detect and show faces, but just shows blank screen. 
```

{
    type:"face",
    target:805,
    faces: []
}
type:"face"
target:805
faces:[]
```

### Environment

Tested on physical Android 11 device

**Comment by Kudo** [comment]
hi there! it's because you didn't specify size to the Camera view, so its width/height is zero. this patch should do the trick.

```diff
- return (<Camera
+ return (<Camera style={{ flex: 1 }}
      // other prop
```
