### ISSUE TITLE
[expo-image] Certain Base64 encoded Thumbhashes cause a complete crash of app

### ISSUE THREAD

**Issue by kartikk221** [expo/expo#22140]
### Minimal reproducible example

https://github.com/kartikk221/expo-thumbhash-crash-example

### Summary

I began to notice my app would just randomly crash when rendering my feed of contents in which I use thumbhashes as placeholders. I noticed that If I commented out the code which would set the thumbhash as the placeholder then the crashes stopped allowing me to pinpoint that the issue was the thumbhashes. The next step was to begin logging the thumbashes to console before they were rendered as this would allow me to find out the exact thumbhash that was causing the crash.

I was able to consistently receive the following output while doing this:
```
 LOG  rendering NhgODwTKlpaLd3dflTeXiHmHZVMHNnUA
 LOG  rendering LAgWBYD3aIeOhXd5dlh4eVePiMCn
 LOG  rendering XggODQKlmMNn92hYh7yWlsxwkAkH
 LOG  rendering OvgFBID5ljeKdoiId3gDKFT5dw==
 LOG  rendering NQgSBwKph4eJeIdvhld2SYiZd0oIpoQA
 LOG  rendering 5QcGDIKKTA62o6OxaGho6ICFDQ==
 LOG  rendering WTgGJYjFuZGkeKOlSAh1TZhwtguG
 LOG  rendering 9/cJBwC2qZiMh3afZQeXd5aLhkUISXMA
 LOG  rendering +fcJBoDGmYiNdnacZQinqHeZ9YyObvc=
 LOG  rendering OQgGBwCFuZiMd3acZwaGuHeIZCX2OnAA
 LOG  rendering OAgKDoC2mYiNhnecZgeXqHaZJ4CREgg=
 LOG  rendering /fcBBoC1qaiPd3atZgeHqIaGtY+Oe/c=
 LOG  rendering NwgKBoCizJl8h4fPRkWIl3Z1UJIOA1s=
 LOG  rendering NfgNBoK0upl7l3e/VjaJlYZ2jnUQqPg=
 LOG  rendering O/gFBoC2mZiPhnabZQiWuIeWenCZCMc=
 LOG  rendering OvgFBoC1uYiOdnWcZgeX13d0rVAB6/o=
 LOG  rendering +vcFBoC2qYeOdoacZgeXuHeHx3+c+Sc=
 LOG  rendering 8gcOBoDWmZiNhnaedAeXp4d3lY9uwGk=
 LOG  rendering OfgJBoDHl5h9hnaMdQiop4aI/FSRmPY=
 LOG  rendering /PcFBoC2qZh+hYesZwenyGaV6W+775Y=
```
So the culprit is the `/PcFBoC2qZh+hYesZwenyGaV6W+775Y=` thumbhash which is encoded in base64.

I am also attaching the Apple crash report in which there are a ton of mentions of the Thumbhash code and the specific Swift Thumbhash related functions which caused the crash.

Crash Report: [report.txt](https://github.com/expo/expo/files/11238440/report.txt)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
      npm: 9.6.4 - ~/Desktop/supply-app/supply-app/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.7 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.9 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.9.2
      expo-cli: 6.1.0
    Expo Workflow: managed

**Comment by kartikk221** [comment]
For more context, here is the function code below which generates the thumbhashes on the server side using the `thumbhash` library:
```js
// Generates the content hash for an image
async function get_image_content_hash(image: Buffer) {
    // Resize & Prepare the image Buffer for blurhash
    const { data, info } = await sharp(image)
        .raw()
        .ensureAlpha()
        .resize({
            width: 100,
            height: 100,
            fit: 'inside',
        })
        .toBuffer({ resolveWithObject: true });

    // Generate the raw Uint8Array content hash
    const raw = rgbaToThumbHash(info.width, info.height, data);

    // Convert the raw Uint8Array to a base64 string
    return Buffer.from(raw).toString('base64');
}
```

**Comment by kartikk221** [comment]
Seems like the issue was the base64 encoding itself. I had to encode the base64 using the `base64url` format.
Everything seems to work If I translate the problematic base64 with the following code:
```js
// returns "_PcFBoC2qZh-hYesZwenyGaV6W-775Y" which works fine
Buffer.from('/PcFBoC2qZh+hYesZwenyGaV6W+775Y=', 'base64').toString('base64url')
```

**Comment by kartikk221** [comment]
Encountered a bigger issue related to this. It turns out that base64url makes some thumbhashes not work at all.
For example, If I try to use `NfgNBoK0upl7l3e_VjaJlYZ2jnUQqPg` which is `base64url` encoded to render, nothing appears.
But If I now convert `NfgNBoK0upl7l3e_VjaJlYZ2jnUQqPg` to `NfgNBoK0upl7l3e/VjaJlYZ2jnUQqPg=` which is `base64` then it works fine. It seems that the `expo-image` library expects `base64` but doesn't handle some edge cases like the `/` being at the beginning in the above post hence this seems to be a parsing problem.

**Comment by XChikuX** [comment]
I still get silent failures on my expo-image package.

Eg. Base64 String: `OvgFBoC1uYiOdnWcZgeX13d0rVAB6/o=`

**Comment by ljukas** [comment]
I also get silent crashes with thumbhashes. "15080E15820999869C86779978967877C67096F33A" this one crashes for example

**Comment by XChikuX** [comment]
@kartikk221 Can we re-open the issue? Seems to be a regression.

**Comment by kartikk221** [comment]
You should likely open a new issue which includes the base64 / thumbhash and references this issue for visibility and also bring it to the front of the opened issues.

**Comment by gerryfletch** [comment]
FWIW I'm only experiencing this on Android, and a significant number of the thumbhashes I use are crashing :/ iOS zero crashes
