### ISSUE TITLE
[docs] Minor version changelog missing.

### ISSUE THREAD

**Issue by xpario** [expo/expo#22151]
### Summary

CHANGELOG.md does not contain changes to minor versions, ex. 48.0.10 to 48.0.11.

### Link to the related docs page

https://github.com/expo/expo/blob/main/CHANGELOG.md

### Anything else?

Is it somewhere else?

**Comment by brentvatne** [comment]
you can see this on the sdk-48 branch on the package itself: https://github.com/expo/expo/blob/sdk-48/packages/expo/CHANGELOG.md

not the most obvious, we will discuss what kind of process we should have around this internally :)
