### ISSUE TITLE
[BUG] Filesystem downloadAsync Error on Android -> Expected ':status' header not present

### ISSUE THREAD

**Issue by runscript** [expo/expo#2215]
### Environment
OS: Windows 10
Node: 8.11.4
Yarn: Not Found
npm: 6.4.1
Watchman: Not Found
Xcode: N/A
Android Studio: Not Found

App's target: Android and iOS

### Steps to Reproduce
Run Snack: https://snack.expo.io/r1VeDP6_Q

Trying to download a file using Expo Filesystem.downloadAsync.
On iOS it works but on Android it gives an error `Expected ':status' header not present`.

### Expected Behavior
To works on android like it works on ios.

### Actual Behavior
Doesn't work on Android.

### Reproducible Demo
https://snack.expo.io/r1VeDP6_Q

**Comment by runscript** [comment]
**UPDATE**
Just found, that if the the image url is requested without https it works and the bug on android is solved.
The domain where the image is stored has Let's Encrypt certificate, maybe thats the problem.

**Comment by EvanBacon** [comment]
#2167

**Comment by bbarthec** [comment]
I've checked this issue and it turned out to be perfectly working - check [this snack](https://snack.expo.io/@bbarthec/github---filesystem---android---downloadasync).
