### ISSUE TITLE
Redux doesn't work properly on expo snack

### ISSUE THREAD

**Issue by yassinebridi** [expo/expo#2216]
### Environment

Expo snack

### Steps to Reproduce

Run the snack: https://snack.expo.io/@yassinebridi/manager

### Expected Behavior

to work properly

### Actual Behavior
produce this error:

```
Device: (281:119) Unable to resolve module 'module://src/reducers/AuthReducer.js'
  Evaluating module://src/reducers/AuthReducer.js
  Evaluating module://src/reducers/Index.js
  Evaluating module://App.js
  Loading module://App.js

```
### Reproducible Demo

https://snack.expo.io/@yassinebridi/manager

**Comment by msevestre** [comment]
There is a type in your filename

You called it `AuthReduer.js` instead of `AuthReducer.js`

![image](https://user-images.githubusercontent.com/1041237/45655909-8d27b400-bab0-11e8-9f62-c46f4585eeae.png)

**Comment by yassinebridi** [comment]
oh wow, i wasted like 30 min trying to solve it. i should've noticed,
thanks.
