### ISSUE TITLE
[docs] Unclear wording in docs for expo-image

### ISSUE THREAD

**Issue by forki** [expo/expo#22171]
### Summary

What does this mean? I assumed the ThumbHash is used as long as the image is not yet loaded from the URI - but we still provide the URI, right?

![image](https://user-images.githubusercontent.com/57396/232720665-85df7981-f368-4d1c-bf39-79de757c335b.png)

### Link to the related docs page

https://docs.expo.dev/versions/unversioned/sdk/image/

**Comment by silenteyesoncode** [comment]
@byCedric @forki Do anyone need help regarding this ?

**Comment by tsapeta** [comment]
> we still provide the URI, right?

No, the source object can have `uri` or `thumbhash` or `blurhash`. If you want to render a blurhash/thumbhash before the source provided to the `source` prop is loaded, you need to provide `{ thumbhash: string }` as a `placeholder` prop.

I agree it might be confusing and it needs clarification in the docs. Thank you for pointing that out 🙏

**Comment by rborn** [comment]
Not sure this works in web though:

```
  source={{ uri: 'https://picsum.photos/seed/696/3000/2000' }}
  placeholder={{ blurhash }}
```

This won't render the blurhash, so the image will fade in from "nothing"

This works though:
```
  source={'https://picsum.photos/seed/696/3000/2000'}
  placeholder={{ blurhash }}
```
