### ISSUE TITLE
[expo-image] still considerable slower than RN Image on Android

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#22176]
### Minimal reproducible example

https://github.com/RRaideRR/expo-image-slow

### Summary

I'm referencing the closed issue #21921. The fixes did not improve the performance on my real Android devices.

My feedback on that closed issue copied to this issue:

Hey @lukmccall. Thanks a lot for your effort that you put into this 🙏. Highly appreciated!

However, regarding the performance issue: I tested it on two (rather low-medium end) Android devices and on these devices the performance gains are unfortunately barely visible. I'll attach two videos showing this. I also updated my repro with a new APK build with the expo-image 1.2.1 version.

Moto G8 power - Android 11
https://user-images.githubusercontent.com/3411292/232799348-b5b74a12-646c-4b2c-8d4d-0666130cb3ab.mp4

Samsung Galaxy A03s - Android 13
https://user-images.githubusercontent.com/3411292/232809886-63ffdee9-4421-4722-bc28-742e12a8a152.mp4

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.11 => 48.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.9.2
    Expo Workflow: bare

```

**Comment by lukmccall** [comment]
It was fixed, but the change has to be applied to the `expo-modules-core` which wasn't published yet - see https://github.com/expo/expo/pull/22153
