### ISSUE TITLE
Violation of Usage of Android Advertising ID policy

### ISSUE THREAD

**Issue by fc** [expo/expo#2217]
Edit:
Please read the official response from Expo at the bottom of this thread or click this link:
https://github.com/expo/expo/issues/2217#issuecomment-422497781

In a nutshell: you need to create a privacy policy for your app.

-------

I had compiled an expo app using your service and it's been on the Play store for several months.  I have no special dependencies.  Does expo do something with an 'advertising ID'?  I haven't migrated to expo 29 yet but I can't really understand why the app was flagged?

My app does nothing special (loads YouTube videos, embeds some static webpages etc) and I do nothing with advertisements... I've looked through the static html files and I do not have any advertising or anything coming from there.

![image](https://user-images.githubusercontent.com/20962/45659803-f6a4c400-baaa-11e8-97d3-da04fb2ea605.png)

**Comment by fc** [comment]
@jlubeck do you embed YouTube videos?

**Comment by jlubeck** [comment]
No, I don't. In neither of them

**Comment by fc** [comment]
What about any embedding any third party content or websites?  In my case, I think it is because of embedding YouTube videos.  Do you anything like that?

**Comment by jlubeck** [comment]
No, I'm not embedding any kind of third party content. Maybe Expo is using the Android Advertising ID for something, like they do with the Apple advertising ID as well... The difference is that with Apple, you can actually say that you are using it, and that is fine. Doesn't look like it's the case with Android.

**Comment by fc** [comment]
Which version of expo are you using?  Mine is version 26.0.0 but I'm in the process of upgrading it.  I'm also writing a privacy policy that says my app doesn't collect any data.

**Comment by jlubeck** [comment]
One of the apps is using 26, and the other 29. We really need feedback from the Expo team here I think

**Comment by fc** [comment]
For iOS they said they use Segment and digging around in the dependencies, `xdl` uses Segment here:
https://github.com/expo/xdl/blob/master/src/Analytics.js

**Comment by msevestre** [comment]
I have also just received the exact same message for two of my apps, both built using expo.

This is very strange. Looking forward to some feedback

**Comment by jichu4n** [comment]
Just got this warning as well. Not embedding ads or YouTube videos.

Could this be related to usage of Constants.deviceId / Constants.installationId?

**Comment by Corpsomium** [comment]
Same warning for me, and not using any Google / Youtube, using Expo 29.

**Comment by simonasdev** [comment]
Same here. Would be best to disable this usage of 'Android Advertising ID' altogether

**Comment by Jack3113** [comment]
I contacted expo on Twitter and they will take a look in few hours. Brent Vatne gave me a link to a template of a privacy policy in case of you prefer to fix the problem right now : https://twitter.com/notbrent/status/1041999058271973376

**Comment by BennyCarlsson** [comment]
Same here not using any ads or youtube videos haven't updated my app since release months ago

**Comment by outaTiME** [comment]
Same here, https://forums.expo.io/t/how-to-stop-transmitting-android-advertising-id

**Comment by alvarofernandoms** [comment]
Same here. I recently updated my app with a Google Analytics service. Maybe is it that is warning is about. What do you guys think?

**Comment by jlubeck** [comment]
@alvarofernandoms I have no google analytics, so no, that is not to blame...

**Comment by michael-molina** [comment]
Link to generate suggested privacy policy.
https://app-privacy-policy-generator.firebaseapp.com/

**Comment by preens007** [comment]
it is very simple you need to do same simple steps and then submit update, follow this link for more guide everything is here https://www.mfm-tutorials.org/solved-violation-of-usage-of-android-advertising-id-policy/

**Comment by jurcello** [comment]
@esamelson 



> We are actively working on a way to customize your standalone app builds by excluding modules you are not using. However, as this is still in development, the best solution for now is to just include a privacy policy with your app. [Here's a privacy policy generator tool from Firebase](https://app-privacy-policy-generator.firebaseapp.com/) (thanks @michael-molina !) and [here's the template one that Brent recommended on twitter.](https://gist.github.com/alphamu/c42f6c3fce530ca5e804e672fed70d78) We'll update our docs to reflect this.

What is the status of the possibility of excluding modules you are not using? I would like to make use of this feature but if it is not available in the near future I need to think of another solution.

**Comment by esamelson** [comment]
@jurcello - excluding modules from apps built using `expo build:ios` or `expo build:android` is still in development, and we don't have an estimate for when it will be ready. If you eject to ExpoKit, I believe you can already exclude individual modules in your iOS project (@sjchmiela - could you confirm?) and the ability to do so on Android will be coming in SDK 32.

**Comment by vault21inc** [comment]
So, just by using expo, are our users subject to _any_ third party data collection? I noticed in the firebase policy generator this line: "The app does use third party services that may collect information used to identify you." If my app is not using any of the aforementioned modules, would this statement be accurate? If not, I would certainly remove it but I'd like some confirmation before doing do. Does my app actually use third services just by virtue of building using expo?

**Comment by Kumagor0** [comment]
Is there still no solution other than getting a privacy policy yet?

**Comment by gregblass** [comment]
Here's what I added into our privacy policy specifically for this situation in hopes that it makes it perfectly clear to the Google Play team.

> **Expo and the Android Advertising Idenfier**
> 
> We use a framework called Expo (https://expo.io) to facilitate cross-platform development, over the air app updates, and various other development conveniences and advantages that help us provide the best quality Service that we can, and to focus on developing new features and providing a great user experience and relevant/up-to date-content. Some of the underlying API's that Expo bundles by default for convenience may contain code to request the Android Advertising ID. However, we wish to make it clear to our users (and specifically to the Google Play Team that reviews apps) that we DO NOT use any of the API's that have the capability to request the Android Adversing ID, and we do not otherwise use the Android Advertising ID in any way. The Expo team is working on making these API's opt-in instead of being automatically included, and we intend to remove them as soon as we have the ability to do so.

**Comment by khusmann** [comment]
@esamelson What is the status on this? Can this be fixed with modular imports or something?

**Comment by gregblass** [comment]
@khusmann I'm not a part of the Expo team, but from what I understand, you're going to have to create a privacy policy until they can roll out modular API importing. I can only imagine that it's a pretty major and serious refactor on their end, so we gotta be patient. Just my 2 cents. Not sure if anyone from Expo can update us on how close the team is to getting there.

**Comment by khusmann** [comment]
@gregblass right -- but I think expo 33 gives us modular api importing: https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c 

So my question is: if I change all my imports over to modular ones, will it no longer send the advert ID? If so, then we can close this issue.

And yes, I am just developing for Android. Even if they also required a privacy policy, I would still prefer to not have ad-related code bundled in my app, even if it is not being used. It's not a show-stopper, just wanting to know the status on this issue especially in light of recent expo development work.

**Comment by gregblass** [comment]
@khusmann I think rather than 'change all my imports over to modular ones', you'd essentially just be not including/using them at all. But yeah, thats the idea...don't use the ones that have the capability to use the AAID.

**Comment by esamelson** [comment]
hey all -- while we have rolled out modular imports as a stepping stone towards optional modules, currently the native code for all supported modules is still included in every standalone app build. We're continuing to work on optional modules and hope to have a solution soon, but in the meantime you'll still need a privacy policy to work around this issue.

**Comment by khusmann** [comment]
@esamelson awesome, this answers my question, thanks!

**Comment by zacateras** [comment]
@khusmann is advertising-related code already excluded from app builds in expo 34?

**Comment by sjchmiela** [comment]
Hello, I think https://github.com/expo/expo/issues/2217#issuecomment-422497781 should clear any misconceptions about this issue. I'll close this thread tentatively. Thank you and have a nice day!
