### ISSUE TITLE
ImagePicker.launchCameraAsync(): option to save photo to Camera Roll?

### ISSUE THREAD

**Issue by btroia** [expo/expo#222]
Currently there is no option to save a photo taken with the camera to the user's camera roll. I see in the React Native documentation there is a `saveToCameraRoll` option that does this, but Expo's ImagePicker does not offer this option:

https://facebook.github.io/react-native/docs/cameraroll.html#savetocameraroll

@nikki93 @terribleben would it be possible to enable this option?

Thanks!

**Comment by nikki93** [comment]
```import Expo from 'expo';
import { CameraRoll, ... } from 'react-native';

...

CameraRoll.saveToCameraRoll((await Expo.ImagePicker.launchCameraAsync({})).uri);``` works for me

**Comment by nikki93** [comment]
@btroia If the above works for you let me know and I'll close this issue.

**Comment by btroia** [comment]
@nikki93 Yes, I had to write it in a slightly different way but it worked - thanks!

**Comment by nikki93** [comment]
Awesome. 😄

**Comment by sothea64** [comment]
btroia
How do you write it!! Please share!!

**Comment by chansuke** [comment]
@sothea64 I did it like below

```
import { CameraRoll } from 'react-native'

_takePhoto = async () => {
  const result = await ImagePicker.launchCameraAsync({
    allowEditing: false,
    exif: true
  });

  if (!result.cancelled) {
    this.setState({ image: result.uri });
  }
  CameraRoll.saveToCameraRoll(this.state.image);
};
```

**Comment by SachinJat** [comment]
CameraRoll.saveToCameraRoll(this.state.image);
on this how to get saved image uri in camera roll
please suggestions...
