### ISSUE TITLE
[AN EXPOKIT SIGNED APK]  ReactNativeJS: undefined is not an object (evaluating 'h.init')

### ISSUE THREAD

**Issue by SimoneLSK** [expo/expo#2220]
Hi ,

May I know if anyone has experienced this error. 
**`ReactNativeJS: undefined is not an object (evaluating 'h.init')`**

It was working great on development mode with expo start. 
App pop this error with the signed APK that generated from AN Studio. Tried on both simulator and device. 
(all codes are working fine on IOS .ipa) 

ExpoKit: 1.7 
SDK: 30.0.0

Thanks 

<img width="301" alt="screen shot 2018-09-18 at 9 34 59 pm" src="https://user-images.githubusercontent.com/26976153/45691249-ce8c9200-bb8a-11e8-8002-06457a610b0d.png">

**Comment by SimoneLSK** [comment]
found out error come from `Stripe.setOptionsAsync({}) ` must put under the **componentWillMount** in android's production mode, unlike iOS that it works outside the component.

**Comment by donedgardo** [comment]
Is this documented? 

> `` must put under the **componentWillMount** in android's production mode, unlike iOS that it works outside the component.

Did you put `setOptionsAsync` inisde the root component or any? @SimoneLSK
