### ISSUE TITLE
[Android13] Couldn't open Android app with app created using expo-template-bare-minimum

### ISSUE THREAD

**Issue by creature-water-valley** [expo/expo#22210]
### Summary

When I created an app using expo-template-bare-template and ran `npm run android`, the following error occurred.

```console
› Opening com.testapp/.MainActivity on Pixel_3a_API_33
CommandError: Couldn't open Android app with activity "com.testapp/.MainActivity" on device "Pixel_3a_API_33".
The app might not be installed, try installing it with: npx expo run:android -d Pixel_3a_API_33
Activity class {com.testapp/com.testapp.MainActivity} does not exist.
```

Since the app is installed on the emulator, I can still run the app by manually launching it and running `npm start`.

The API levels and emulators I tried are as follows.

- Pixel_3a_API_33: error
- Pixel_3a_API_32: success

> **Note**
> iOS works fine.

Related issue: 
- https://github.com/expo/expo/issues/21444
- https://github.com/facebook/react-native/issues/36995

### What platform(s) does this occur on?

Android

### SDK Version

48.0.11

### Environment

```console
expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 13.3.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.asdf/installs/nodejs/18.15.0/bin/node
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
  Managers:
    CocoaPods: 1.11.3 - /Users/pinkikki/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-30 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
  IDEs:
    Android Studio: Flamingo 2022.2.1 Flamingo 2022.2.1
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  npmPackages:
    expo: ~48.0.11 => 48.0.11
    react: 18.2.0 => 18.2.0
    react-native: 0.71.6 => 0.71.6
  Expo Workflow: bare
```

### Minimal reproducible example

```bash
$ npx create-expo-app TestApp --template expo-template-bare-minimum
$ cd TestApp
$ npm run android
```

**Comment by Kudo** [comment]
hi there! this might happen if the apk installation is failed. please try to install the apk manually

```sh
$ cd TestApp/android
$ adb install -r app/build/outputs/apk/debug/app-debug.apk
$ adb shell am start -n com.testapp/com.testapp.MainActivity
```

if you find there's an existing app with the same application id, you could use `adb unstall com.testapp` to remove it first.

**Comment by creature-water-valley** [comment]
@Kudo Thank you for your response.
The option `-n` specifying component names with package name prefixes certainly succeeds.
```bash
$ adb shell am start -n com.testapp/com.testapp.MainActivity
Starting: Intent { act=com.testapp/.MainActivity }
Error: Activity not started, unable to resolve Intent { act=com.testapp/.MainActivity flg=0x10000000 }

```

However, if I start it with `npm run android`, I think it uses the option `-a` to specify the intent action.
- https://github.com/expo/expo/blob/sdk-48/packages/%40expo/cli/src/start/platforms/android/adb.ts#L107

Then, the following command will fail.
```bash
$ adb shell am start -a com.testapp/.MainActivity
```

**Comment by Kudo** [comment]
nice investigation @creature-water-valley. i can repro and self-assign this issue. will follow up for it.
