### ISSUE TITLE
npx create-expo-app --template bare-minimum stuck on installing Cocoapods

### ISSUE THREAD

**Issue by ritmillio** [expo/expo#22212]
### Summary

When I try to run npx create-expo-app --template bare-minimum, the process gets stuck on the "Installing CocoaPods" step and never completes. 

### SDK Version

6.3.2

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.0.0 - ~/.nvm/versions/node/v19.0.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v19.0.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v19.0.0/bin/npm
      Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 6.3.2

### Minimal reproducible example

Stuck at installation..
<img width="356" alt="Screenshot 2023-04-21 at 9 13 48" src="https://user-images.githubusercontent.com/40596749/233566970-6746acf0-d0d7-4301-a5f2-80d45299e683.png">

**Comment by maximcoding** [comment]
I was facing same issue on M1 , helped me  ..

brew uninstall cocoapods
brew install chruby
brew install ruby-install
ruby-install ruby 3.1.3

source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh

chruby ruby-3.1.3

**Comment by maximcoding** [comment]
If someone still struggle with Pod Installation issues , [Check my github project with expo 0.48.](https://github.com/maximcoding/react-native-expo-starter)

**Comment by Kudo** [comment]
hi there! i think this issue may come from the network environment or cocoapods server.
could you try to check the manual steps?

```sh
$ npx create-expo-app --template bare-minimum --no-install
$ cd BareWorkflowTest
$ npm install
$ cd ios
$ pod install
```
