### ISSUE TITLE
Issue with ExpoKit/GL when upgrading from v28 to v29

### ISSUE THREAD

**Issue by Jordan4jc** [expo/expo#2221]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please use `exp send` with exp, the “Send” button with XDE, or the "s" hotkey with create-react-native-app to send your project development URL to your phone by SMS or email.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.0.0
  Yarn: 1.5.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

ExpoKit

### Steps to Reproduce

1. Upgrading from 28.0.0 to 29.0.0 following the instructions in the Medium post
2. When I get to the ExpoKit steps I follow them and upgrade my ExpoKit `tag:` to `ios/2.8.2`
3. Run `pod install`

### Expected Behavior

Have the pods installed or updated properly

### Actual Behavior

Get this error

```
[!] CocoaPods could not find compatible versions for pod "ExpoKit/GL":
  In Podfile:
    ExpoKit/GL (from `http://github.com/expo/expo.git`, tag `ios/2.8.2`)

None of your spec sources contain a spec satisfying the dependency: `ExpoKit/GL (from `http://github.com/expo/expo.git`, tag `ios/2.8.2`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by Jordan4jc** [comment]
This is also happening when I attempt to update to v30, same issue, even after running the suggested `pod install --repo-update`

**Comment by tsapeta** [comment]
Hey @Jordan4jc, could you try to remove `GL` subspec from `ExpoKit` in your Podfile? `GL` is no longer provided as a subspec, but as a separate pod. See [gist](https://gist.github.com/brentvatne/6bc4b24031e187d2c760d28de3ed4f97) with an example of how your Podfile should look like.

**Comment by Jordan4jc** [comment]
So now I get this

```
[!] No podspec found for `EXCamera` in `../node_modules/expo/node_modules/expo-camera/ios`
```

I notice in my `node_modules` folder I have the individual modules listed, but all of the pods in my podfile are listed as looking first in the `expo/node_modules` folder, is this a typo? Should I change them to not look in `expo/node_modules`?

**Comment by tsapeta** [comment]
Oh yeah, these pods should look in your `node_modules` folder, so EXCamera should be loaded from `../node_modules/expo-camera`. Sorry for this mistake 😉

**Comment by tsapeta** [comment]
Also, if you're upgrading to SDK30 then you need to add pods from this [gist](https://gist.github.com/esamelson/2ce0ed0dbbf9d8a55a98e3d9014987c4)

**Comment by Jordan4jc** [comment]
Okay it looks like all that worked, getting a seperate build error in xcode not related to this. And I did indeed make sure those pods were added alongside the ones you linked to

**Comment by paul019** [comment]
@tsapeta When I look into my node_modules folder, I can neither neither find folders like `expo-camera`, nor a sub-folder named `node_modules` in the initial `expo`-folder. What's my problem?
