### ISSUE TITLE
Clipboard listener dont work

### ISSUE THREAD

**Issue by g1mbatov** [expo/expo#22236]
### Summary

When working with ClipboardEvent, the method specified in the documentation works on android 10, but does not work on android 7

Clipboard.addClipboardListener(({ contentTypes }: ClipboardEvent) => {
  if (contentTypes.includes(Clipboard.ContentType.PLAIN_TEXT)) {
    Clipboard.getStringAsync().then(content => {
      alert('Copy pasta! Here\'s the string that was copied: ' + content)
    });
  } else if (contentTypes.includes(Clipboard.ContentType.IMAGE)) {
    alert('Yay! Clipboard contains an image');
  }
});

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/clipboard/

**Comment by thoth-seshat** [comment]
I have the same problem right now. What's up with the clipboard listener?

**Comment by mohammedhammoud** [comment]
This is still an issue.

**Comment by Episodex** [comment]
It doesn't work for me for the newest Android and SDK 51. It just won't fire the event.
