### ISSUE TITLE
expo-device module not working with dev-client

### ISSUE THREAD

**Issue by AnatuGreen** [expo/expo#22230]
### Summary

I wanted to use expo push notifications for my managed app. I have already built a dev client.
Following the push notifications setup instruction brought me to installing expo-device: npm install expo-device.
Installation was successful as seen in npm list.
I closed my terminal, closed and re-opened VS studio code and I started my dev client. On connecting my Android device using the dev client and when the bundling of app is done, I get the error: 

```
 ERROR  Error: Cannot find native module 'ExpoDevice', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.      
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

react-native@0.71.6
 @expo/config-plugins@6.0.1
expo-build-properties@0.6.0
expo-dev-client@2.2.1
expo-device@5.2.1
 expo-updates@0.16.4
expo@48.0.11

### Environment

[fileCUsersanatuAppDataLocalnpm-cach.txt](https://github.com/expo/expo/files/11300200/fileCUsersanatuAppDataLocalnpm-cach.txt)

### Reproducible demo

```
import "react-native-gesture-handler";
import React, { useState, useEffect, useRef } from "react";
import * as Device from 'expo-device';

async function registerForPushNotificationsAsync() {
  let token;
  if (Device.isDevice) {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
  }

```

**Comment by BDav24** [comment]
Have you rebuilt the dev client?
```
eas build -p android --profile development
```
