### ISSUE TITLE
[expo-image] Does not work with photos from camera roll when 'limited' permission is given on ios

### ISSUE THREAD

**Issue by gvanderclay** [expo/expo#22251]
### Minimal reproducible example

N/A

### Summary

On ios, when the app has limited photo library permissions (i.e. access to user specified photos) the component returns the following in the `onError` property.
```
{"error": "Unauthorized access to the Photo Library", "target": 2515}
```

After searching for that term in the repo, I found the culprit:
https://github.com/expo/expo/blob/d1f4129363af67f1525a636fc0ddcf42ab0f3726/ios/versioned/sdk48/ExpoImage/Loaders/PhotoLibraryAssetLoader.swift#L23
and
https://github.com/expo/expo/blob/d1f4129363af67f1525a636fc0ddcf42ab0f3726/ios/versioned/sdk48/ExpoImage/Loaders/PhotoLibraryAssetLoader.swift#L79

The code is only checking for `.authorized` when I believe it should also be checking for `.limited`. This causes the app to not be able to render photos that it does have access to.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.asdf/installs/nodejs/16.18.0/bin/node
      Yarn: 3.2.4 - ~/.asdf/installs/nodejs/16.18.0/bin/yarn
      npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/gvanderclay/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 31, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0
        System Images: android-28 | ARM 64 v8a, android-28 | Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.11 => 48.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    Expo Workflow: bare

**Comment by norbusonam** [comment]
I create an issue for the same problem (now closed as it is a duplicated) where I provided this snack:

https://snack.expo.dev/cKcE2QbAm

The code snippet did not work in the snack for me, but to try it out, you can make an expo project with create-expo-app, copy over the App.js, and install expo-media-library and expo-image to try it out.

When all photo's are shared, images render as expected but when limited photo's are shared, images do not render and the error is logged.
