### ISSUE TITLE
FIS_AUTH_ERROR

### ISSUE THREAD

**Issue by Pcummings** [expo/expo#22258]
### Minimal reproducible example

```try {             let token;              if (Platform.OS === 'android') {                 await Notifications.setNotificationChannelAsync('default', {                     name: 'default',                     importance: Notifications.AndroidImportance.MAX,                     vibrationPattern: [0, 250, 250, 250],                     lightColor: '#FF231F7C',                 });             }              if (Device.isDevice) {                 const { status: existingStatus } = await Notifications.getPermissionsAsync();                 const finalStatus = existingStatus !== 'granted'                     ? (await Notifications.requestPermissionsAsync()).status                     : existingStatus;                 if (finalStatus !== 'granted') {                     logger.error('Failed to get push token for push notification!');                     return;                 }                 token = (await Notifications.getExpoPushTokenAsync()).data;                 setPushToken(token)             } else {                 logger.info('Must use physical device for Push Notifications');             }              return token;         } catch (error) {             logger.error('Error registering for push notifications:', error);         }```

### Summary

I have an app where I enabled push notifications, it worked on both IOS and android. Out of the blue it stopped working on Android, yet it still works on IOS.

When trying to reload the dev client, without invoking any code that has to do with expo-notifications I get this error:```[expo-notifications] Error encountered while updating server registration with latest device push token. [Error: Fetching the token failed: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR]```

When actually trying to get a token I get the following:
```[Error: Fetching the token failed: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR]```

I have tried to debug as much as I can:

- Checking Firebase configuration and google-services.json
- Checking the API keys in GCP
- Uploading the FCM keys through expo
- Enabling all the firebase API in GCP

I have a dynamic configuration for building development clients:
```module.exports = ({ config }) => {
    const IS_DEV = (process.env.APP_VARIANT !== undefined ? process.env.APP_VARIANT === 'development' : process.env.NODE_ENV === 'development');
    config.name = IS_DEV ? 'fairTasting (Dev)' : 'fairTasting';
    config.scheme = IS_DEV ? 'fairtastingdev' : 'fairtasting';
    config.ios.bundleIdentifier = IS_DEV ? "com.fairtasting.devapp" : "com.fairtasting.app";
    config.ios.googleServicesFile = IS_DEV ? "./GoogleService-Info-Dev.plist" : "./GoogleService-Info.plist";
    config.android.package = IS_DEV ? "com.fairtasting.devapp" : "com.fairtasting.app";
    config.android.googleServicesFile = IS_DEV ? "./google-services-dev.json" : "./google-services.json";
    return {
        ...config,
    };
};```
and I have also tried swapping the google-services files, yet no joy.

Any help would be appreciated.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
      npm: 9.1.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.61 => 0.1.84 
      @expo/webpack-config: ^18.0.1 => 18.0.4 
      expo: ^48.0.0 => 48.0.11 
      metro: ^0.76.0 => 0.76.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.9.2
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by isaachinman** [comment]
@Pcummings Any update on this matter? We also have had both iOS and Android PNs working fine in production for months, and within the past week or two, Android PNs started failing with the `FIS_AUTH_ERROR` error.

**Comment by jonasguerra** [comment]
Still facing the same problem, everything was working fine but now occurs FIS_AUTH_ERROR while trying to get the push notification token:

export const usePushNotificationsHook = () => {
  const dispatch = useDispatch();

  const setNotificationToken = async (token: any) => {
    dispatch(setPushNotificationToken(token));
  };

  //crie a função com os tipos retornados
  const registerForPushNotificationsAsync = async () => {
    // let expoToken;
    let token;
    try {
      if (Platform.OS === 'android') {
        await Notifications.setNotificationChannelAsync('default', {
          name: 'default',
          importance: Notifications.AndroidImportance.MAX,
          vibrationPattern: [0, 250, 250, 250],
          lightColor: '#FF231F7C',
        });
      }

      const { status: existingStatus } = await Notifications.getPermissionsAsync();

      let finalStatus = existingStatus;

      if (existingStatus !== 'granted') {
        const { status } = await Notifications.requestPermissionsAsync();
        finalStatus = status;
      }
      if (finalStatus !== 'granted') {
        alert('Failed to get push token for push notification!');
        return;
      }

      // let expoToken = (await Notifications.getExpoPushTokenAsync()).data;
      token = (await Notifications.getDevicePushTokenAsync()).data;
      await logService.writeLog(`usePushNotificationsHook - token: ${token}`);

      await setNotificationToken(token);
    } catch (error) {
      await logService.writeLog(`usePushNotificationsHook - error: ${error}`);
    }

    return {
      // expoToken: expoToken,
      token: token,
    };
  };

  return { registerForPushNotificationsAsync };
};

**Comment by Goowwy** [comment]
you need change SHA-1 certificate fingerprint from expo to google play App signing key certificate

**Comment by jonasguerra** [comment]
I added the sha-1 key from app expo credentials in firebase app config and also created an Android Restriction in the google cloud with the package and sha-1 of my app. Now everything is working fine again, i'm not facing anymore the FIS_AUTH_ERROR.

I encountered this solution following the answer first steps:
https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase

**Comment by MatiasTejerina07** [comment]
> Agregué la clave sha-1 de las credenciales de App Expo en la configuración de la aplicación Firebase y también creé una restricción de Android en Google Cloud con el paquete y sha-1 de mi aplicación. Ahora todo está funcionando bien nuevamente, ya no me aparece el error FIS_AUTH_ERROR.
> 
> Encontré esta solución siguiendo los primeros pasos de la respuesta: https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase

Jonas podés ampliar más de tu descripción?? Me encuentro hoy llevando a cabo una aplicación con expo, y en desarrollo las notificaciones llegan de manera normal pero en desarrollo la aplicación revienta con este error

**Comment by Goowwy** [comment]
<img width="299" alt="Screenshot 2024-11-22 at 12 55 50" src="https://github.com/user-attachments/assets/3a46910e-c9e2-4d5e-9a70-51cae997b115">
look here
