### ISSUE TITLE
[expo-image] Image load errors when user allowed limited photo library permissions

### ISSUE THREAD

**Issue by norbusonam** [expo/expo#22250]
### Minimal reproducible example

https://snack.expo.dev/cKcE2QbAm

The code snippet did not work in the snack for me, but to try it out, you can make an expo project with `create-expo-app`, copy over the `App.js`, and install `expo-media-library` and `expo-image` to try it out.

When all photo's are shared, images render as expected but when limited photo's are shared, images do not render and the error is logged.

### Summary

When user gives limited permissions, `expo-image` fails to render the photos the user allowed. This occurs in both the new and old architecture.

With the onError function, I can see the error is `Unauthorized access to the Photo Library` which should not occur since these specific images were allowed by the user.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
      Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    Expo Workflow: bare

**Comment by gvanderclay** [comment]
Whoa! Looks like we discovered the same issue around the same time! https://github.com/expo/expo/issues/22251

**Comment by norbusonam** [comment]
@gvanderclay wow, what a coincidence 🤣 I'll close this one since yours is closer to the solution and will add a comment with my snack to yours.

**Comment by norbusonam** [comment]
Closing this as it a duplicate of https://github.com/expo/expo/issues/22251

**Comment by norbusonam** [comment]
Closing this as it is a duplicate of https://github.com/expo/expo/issues/22251
