### ISSUE TITLE
[docs] Wrong ID for `Location Accuracy` in `Location Options`

### ISSUE THREAD

**Issue by MohamedSaidSallam** [expo/expo#22260]
### Summary

`Location Options` in the [`Location` docs](https://docs.expo.dev/versions/latest/sdk/location/#locationoptions) has the wrong ID for Location Accuracy Enum.

Currently it is `#locationaccuracy` (https://docs.expo.dev/versions/latest/sdk/location#locationaccuracy). I should be `accuracy`
(https://docs.expo.dev/versions/latest/sdk/location/#accuracy)

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/location/#locationoptions

**Comment by amandeepmittal** [comment]
Thanks for reporting it! Closing this issue as it was resolved in #22309.
