### ISSUE TITLE
Submitting iOS app through `eas submit` is failing because of a fastlane pilot error

### ISSUE THREAD

**Issue by PedroRestrepo** [expo/expo#22265]
### Summary

Whenever we try to submit an app through `eas submit -p ios` its failing. Only started recently in the last hour. 

![image](https://user-images.githubusercontent.com/7490699/234368929-32dc9352-8768-4ee8-81d0-a3501eafd3a8.png)

### What platform(s) does this occur on?

iOS

### SDK Version

48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.1
      expo: ^48.0.0 => 48.0.9
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
      react-native-web: ~0.18.11 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.1.0
    Expo Workflow: managed

### Minimal reproducible example

I dont think its an app specific problem. Whenever we submit the iOS app, the following error is displayed:

```
Starting the submit process
Downloading archive
Preparing artifact
Verifying archive
Creating ascApiJsonKey.json file with ASC credentials
Submitting iOS app to TestFlight...
Submitting the app with fastlane pilot
undefined method `split' for nil:NilClass
-------------------
--- Step: pilot ---
-------------------
Creating authorization token for App Store Connect API
Ready to upload new build to TestFlight (App: 1501364694)...
undefined method `split' for nil:NilClass
[stderr] 
[!] Error detecting currently used Xcode installation, please ensure that you have Xcode installed and set it using `sudo xcode-select -s [path]`
Fastlane pilot failed
fastlane exited with non-zero code: 1
Failed to submit the app
We couldn't figure out what went wrong. See logs to learn more.
```

**Comment by PedroRestrepo** [comment]
Rerunning the submission from the UI seemed to fix it. Not sure if its was an intermittent issue or not. We definitely tried several times, rebuilt the app and everything

![image](https://user-images.githubusercontent.com/7490699/234369876-cc8c539d-56af-49a2-8ba7-af2bd000ae63.png)

**Comment by brentvatne** [comment]
this was indeed an intermittent issue. we've had some problems with the infrastructure that EAS Submit runs on (one of those caused the issue you observed) and we're now in the process migrating it to more stable infrastructure

**Comment by imranAfzal43A** [comment]
Starting the submit process
[logs] Downloading archive
[logs] Preparing artifact
[logs] Verifying archive
[logs] Creating ascApiJsonKey.json file with ASC credentials
[logs] Submitting iOS app to TestFlight...
[logs] Submitting the app with fastlane pilot
[logs] -------------------
[logs] --- Step: pilot ---
[logs] -------------------
[logs] Creating authorization token for App Store Connect API
[logs] Ready to upload new build to TestFlight (App: 1410114607)...
[logs] ▸ caution: filename not matched:  *Payload/*.app/Info.plist
[logs] Going to upload updated app to App Store Connect
[logs] This might take a few minutes. Please don't interrupt the script.
[logs] [altool] 2023-12-07 09:04:57.396 *** Error: No suitable application records were found. Verify your bundle identifier 'dev.hermesengine.iphoneos' is correct and that you are signed into Xcode with an Apple ID that has access to the app in App Store Connect. App Store operation failed. (1190) 
[logs] [altool]  {
[logs] 
[logs] [altool]     NSLocalizedDescription = "No suitable application records were found. Verify your bundle identifier 'dev.hermesengine.iphoneos' is correct and that you are signed into Xcode with an Apple ID that has access to the app in App Store Connect.";
[logs] 
[logs] [altool]     NSLocalizedFailureReason = "App Store operation failed.";
[logs] 
[logs] [altool]     NSLocalizedRecoverySuggestion = "No suitable application records were found. Verify your bundle identifier 'dev.hermesengine.iphoneos' is correct and that you are signed into Xcode with an Apple ID that has access to the app in App Store Connect.";
[logs] 
[logs] [altool] }
[logs] 
[logs] Application Loader output above ^
[logs] Error uploading '/var/folders/8m/cfpqfjyx37xd0tlkyxt9flph0000gn/T/d297a907-daf7-4615-9768-f22fbf9cd1c9.ipa'.
[logs] No suitable application records were found. Verify your bundle identifier 'dev.hermesengine.iphoneos' is correct and that you are signed into Xcode with an Apple ID that has access to the app in App Store Connect. App Store operation failed. (1190)
[logs] The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
[logs] Could not download/upload from App Store Connect!
[logs] [!] Error uploading ipa file:
[logs]  [Application Loader Error Output]: Error uploading '/var/folders/8m/cfpqfjyx37xd0tlkyxt9flph0000gn/T/d297a907-daf7-4615-9768-f22fbf9cd1c9.ipa'.
[logs] [Application Loader Error Output]: No suitable application records were found. Verify your bundle identifier 'dev.hermesengine.iphoneos' is correct and that you are signed into Xcode with an Apple ID that has access to the app in App Store Connect. App Store operation failed. (1190)
[logs] [Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
[logs] Fastlane pilot failed
[logs] Failed to submit the app

**Comment by pfndesign** [comment]
using retry submission fixed the problem in UI

**Comment by oller** [comment]
Yes I'm seeing this too - presuming it's an EAS infra issue, and everyone's enjoying their Christmas 🎄 

I'm on the free tier so no massive expectations, I'll try again tomorrow.  FWIW - android submission went through successfully.

**Comment by sameigen** [comment]
Also seeing this on our end. 'Retry submission' in the UI worked after failing to submit with `--auto-submit` in the CLI

**Comment by w4t3r-45** [comment]
same issue

**Comment by Niravpatel129** [comment]
same issue

**Comment by locDEV169** [comment]
![image](https://github.com/expo/expo/assets/48356607/2c9a2fd5-cdb3-4578-a46e-6f801c0b0f21)
I encountered this problem, how to fix it, somebody help me

**Comment by SaathiApp** [comment]
Any updates on this. We are facing this today

**Comment by Renan-Olovics** [comment]
got the same issue

**Comment by wladziaya** [comment]
Same issue for 3 days

**Comment by wladziaya** [comment]
> got the same issue

Find any solution?

**Comment by SaathiApp** [comment]
I tried logging out of my dev account and logging back from my terminal and it worked.

**Comment by abmdeve** [comment]
Good evening, someone to help me please, for three days I have been trying to deploy my iOS app, but I have this error
<img width="1148" alt="Capture d’écran 2024-04-20 à 18 25 35" src="https://github.com/expo/expo/assets/87487084/d66c71b5-073b-406a-a692-385d8f1953b3">
<img width="1148" alt="Capture d’écran 2024-04-20 à 18 25 58" src="https://github.com/expo/expo/assets/87487084/b83ac785-f92e-415a-a017-39ddc0c1d31e">

**Comment by Minh-ka** [comment]
Me too, got same issue and retried 2 times. Any solution for this issue?
<img width="877" alt="Screenshot 2024-05-17 at 11 24 40" src="https://github.com/expo/expo/assets/102807556/4075e710-fa77-4b40-92d4-c7028246379f">

**Comment by greykes** [comment]
Same issue here for me, any fix or comment from Expo?

**Comment by Minh-ka** [comment]
> Same

I upgraded with latest version of expo, rebuild and I submitted success.

**Comment by Qubit-Lab** [comment]
The problem that came was resolved by first updating the sdk version to the latest version . 
You have to use the command " expo update" in your terminal.

-Than please check out your apple certificates. You might need to revoke previous apple certificate and then reassign a new one when you are completing you build. 

- For some reason there's a confusion of communication between expo and apple certificates. Once these 2 things are updated and fixed the Fastlane issue should resolve itself and the submission would go through
- when submitting you need to check your within integration on your apple developer account and see if you need a new individual app store connect API
- We have successfully submitted our app after these fixes and keep in mind the problem is existing between the communication of the app store and your app not within the app itself

**Comment by DanielssonWilliam** [comment]
I got this same issue as of today. It worked earlier during the day but now it wont build because of fastlane error.

`Fastlane pilot failed
fastlane exited with non-zero code: 1

Failed to submit the app to the store`

**Comment by eabdullahu** [comment]
Same error here, yesterday worked fine today I have these issues.

**Comment by MatthysDev** [comment]
Same error for me since yesterday, still a problem today

**Comment by jaworskimatt** [comment]
I am having the same issue. I have two apps with the same Bundle ID - one is Removed, and it never had any builds, so Apple allowed me to create a new one with the same Bundle ID.

So now I have 2 apps with the same Bundle ID - one Live and one Removed - and I can no longer eas submit this app.

**Comment by brentvatne** [comment]
hey @jaworskimatt or others encountering this problem - send me a dm on discord if you're still having this issue, i'd be curious to dig into it more and see if we can find a way to give a more helpful error message

**Comment by ChialiT** [comment]
This issue still exists but can be fixed by clicking the "retry submission" in expo UI.

**Comment by MehmetKaplan** [comment]
For me the problem exists but the UI resubmission did not resolve the issue.

**Comment by ChinonsoIg** [comment]
In case anyone experiences this issue, use Transporter to upload the app. Go to App store and search for Transporter.
