### ISSUE TITLE
Location.getCurrentPositionAsync `timeout` option immediately throws an exception

### ISSUE THREAD

**Issue by Xyzor** [expo/expo#2226]
### Environment

  OS: Linux 4.18
  Node: 8.12.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Android Client, Standalone

### Steps to Reproduce

Simply try to call the getCurrentLocationAsync method on an Android device. I tested it on 5.0 and 7.0 (tablet).

### Expected Behavior

Return with the current position or timeout.

### Actual Behavior

Immediately throws an exception.

```
Encountered an exception while calling native method: Exception occurred while executing exported method getCurrentPositionAsync on module ExpoLocation: null" in c@/data/user/0/host.exp.exponent/files/30.0.0/cached-bundle-experience-%40snack%2Fsdk.30.0.0-HJqtWtyYm-1841382398-30.0.0:19:1623 << /data/user/0/host.exp.exponent/files/30.0.0/cached-bundle-experience-%40snack%2Fsdk.30.0.0-HJqtWtyYm-1841382398-30.0.0:19:990 << value@/data/user/0/host.exp.exponent/files/30.0.0/cached-bundle-experience-%40snack%2Fsdk.30.0.0-HJqtWtyYm-1841382398-30.0.0:21:3873 << /data/user/0/host.exp.exponent/files/30.0.0/cached-bundle-experience-%40snack%2Fsdk.30.0.0-HJqtWtyYm-1841382398-30.0.0:21:1397
```

### Reproducible Demo

[Snack](https://snack.expo.io/H14xAI0dQ)

**Comment by lunvjp** [comment]
It just happened like me a few minutes ago.

**Comment by welingtonms** [comment]
Same problem here

**Comment by esamelson** [comment]
Hi all - this worked fine for me once I removed the `timeout` key from the `getCurrentLocationAsync` param object. The `timeout` key is not documented so we don't officially support it right now. We'll look into either fixing it or removing it from the native code entirely, but the best solution right now is just to not use it.

**Comment by Xyzor** [comment]
@esamelson Thanks for the suggestion.

I was using the timeout for a reason.
If I don't use it, the function *never resolves the promise on android.

*never = I waited 1.5 minute and it was still going when I restarted the app.
