### ISSUE TITLE
'EXAppLoader.h' file not found on Xcode 10

### ISSUE THREAD

**Issue by faustoct** [expo/expo#2229]
Getting 'EXAppLoader.h' file not found after upgrade to Xcode 10

`exp: 54.0.1`
`react-native-cli: 2.0.1`
`react-native: 0.54.2`
`expo sdkVersion: 26.0.0`

How do I get out of this error?!? I downgraded the Xcode but still not working.

**Comment by lnfnunes** [comment]
Following [this](https://github.com/expo/expo/issues/2002) worked for me!

**Comment by faustoct** [comment]
@lnfnunes what did you do? I tried the link before but didn't work for me 😭😭
Got stuck with..

**Comment by faustoct** [comment]
Also downgrade to xcode 9 still not working at all..

**Comment by lnfnunes** [comment]
@faustoct as suggested in that thread, I just applied [the commit](https://github.com/expo/expo/commit/62cc3d03d29f92cfdcffb8ffe1256660986faffe) changes and it works.

**Info:** my project is ejected and the Expokit is v26.0.0

**Comment by faustoct** [comment]
@lnfnunes mine also ejected . tks!
