### ISSUE TITLE
Android package name issue with Expo@48.0.15

### ISSUE THREAD

**Issue by iamromec** [expo/expo#22297]
### Minimal reproducible example

Create a new app and initialize name, packageName in the app.config.js and it'll create this error

### Summary

Hello,

We've recently upgraded to the latest version of Android & Expo and it seems there is a bug with latest Expo version as it's ignoring the given package name and creating packageName automatically from the given `name` property in the app.config.js file instead of using the given `packageName` in the same file.

Please find the attached screenshots.

<img width="364" alt="Screenshot 2023-04-27 at 7 32 51 PM" src="https://user-images.githubusercontent.com/50284628/234888555-69eccb50-f2f4-45db-b7e1-1d224d0a0fd3.png">

<img width="565" alt="Screenshot 2023-04-27 at 7 32 10 PM" src="https://user-images.githubusercontent.com/50284628/234888592-2edb7c83-fbc6-4f19-8e86-50774061575f.png">

If you take a look at these screenshots, I've given the name in my app.config.js file is "Growcify - V2" and packageName is "com.growcify" but when I run the app using `npx expo run:android`, it automatically adds the platform and create the package name `com.growcifyv2` from name and ignores the given packageName.

Please help!

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.04.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.4 
      expo: ~48.0.15 => 48.0.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.10.0
    Expo Workflow: bare

**Comment by iamromec** [comment]
It's s serious issue and your bot is marking this as closed! What the hack!!!

**Comment by Kudo** [comment]
hi there! i am sorry for the aggressive bot. but as the bot mentioned, we need a repro to investigate on the same page. well, could you share your `app.json` or `app.config.js`? i feel like there is no `packageName` support in app.json. [it should be `package` inside the `android` section](https://docs.expo.dev/versions/latest/config/app/#package).

**Comment by iamromec** [comment]
Thanks for replying. Yes, it's package only as I'm using two files to define configs somewhere else and then import them in the app.config.js. Here's the app.config.js file:

import {
  name,
  slug,
  version,
  buildVersionIOS,
  buildVersionAndroid,
  packageName,
  googleMapAPIKey,
  deeplinkHostname,
} from "./gcfy.config";

module.exports = {
  name: name,
  slug: slug,
  version: version,
  orientation: "portrait",
  icon: "./assets/icon.png",
  userInterfaceStyle: "light",
  splash: {
    image: "./assets/splash.png",
    resizeMode: "cover",
  },
  updates: {
    fallbackToCacheTimeout: 0,
  },
  assetBundlePatterns: ["**/*"],
  ios: {
    supportsTablet: false,
    config: {
      googleMapsApiKey: googleMapAPIKey,
    },
    infoPlist: {
      NSLocationAlwaysAndWhenInUseUsageDescription:
        "Allowing this helps $(PRODUCT_NAME) to show nearby delivery options",
      NSLocationAlwaysUsageDescription:
        "Allowing this helps $(PRODUCT_NAME) to show nearby delivery options",
      NSLocationWhenInUseUsageDescription:
        "Allowing this helps $(PRODUCT_NAME) to show nearby delivery options",
      NSPhotoLibraryUsageDescription:
        "Allow $(PRODUCT_NAME) to access your photos.",
      NSPhotoLibraryAddUsageDescription:
        "Allow $(PRODUCT_NAME) to save photos.",
      LSApplicationQueriesSchemes: ["tez", "phonepe", "paytmmp"],
    },
    bundleIdentifier: packageName,
    buildNumber: buildVersionIOS,
    googleServicesFile: "./firebase/GoogleService-Info.plist",
    associatedDomains: ["applinks:" + deeplinkHostname],
  },
  android: {
    adaptiveIcon: {
      foregroundImage: "./assets/adaptive-icon.png",
      backgroundColor: "#FFFFFF",
    },
    config: {
      googleMaps: {
        apiKey: googleMapAPIKey,
      },
    },
    permissions: [
      "android.permission.READ_EXTERNAL_STORAGE",
      "android.permission.WRITE_EXTERNAL_STORAGE",
      "android.permission.ACCESS_MEDIA_LOCATION",
    ],
    package: packageName,
    versionCode: buildVersionAndroid,
    googleServicesFile: "./firebase/google-services.json",
    intentFilters: [
      {
        action: "VIEW",
        data: [
          {
            scheme: "https",
            host: deeplinkHostname,
            pathPrefix: "/" + slug,
          },
        ],
        category: ["BROWSABLE", "DEFAULT"],
      },
    ],
  },
  notification: {
    color: "#007BFF",
    icon: "./assets/ic_stat_ic_notification.png",
    iosDisplayInForeground: true,
  },
  plugins: [
    "@react-native-firebase/app",
    [
      "expo-media-library",
      {
        photosPermission: "Allow " + name + " to access your photos.",
        savePhotosPermission: "Allow " + name + " to save photos.",
        isAccessMediaLocationEnabled: true,
      },
    ],
    [
      "expo-build-properties",
      {
        android: {
          enableDangerousExperimentalLeanBuilds: true,
        },
        ios: {
          deploymentTarget: "13.0",
          useFrameworks: "static",
        },
      },
    ],
    [
      "expo-image-picker",
      {
        photosPermission:
          "The app accesses your photos to let you share them with us.",
      },
    ],
    ["expo-notifications"],
  ],
};

**Comment by iamromec** [comment]
Do you want me to share my package.json file?

**Comment by Kudo** [comment]
> Do you want me to share my package.json file?

would be good if you could check my repro above when you get a chance. that is a working example.

**Comment by iamromec** [comment]
In your repo, it's "expo": "~48.0.1", whereas in my package.json it's "expo": "~48.0.15",

Here's my package.json:

{
  "name": "rapp",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "rni": "node rni.js"
  },
  "dependencies": {
    "@expo-google-fonts/poppins": "^0.2.2",
    "@expo/config-plugins": "^6.0.1",
    "@expo/webpack-config": "^18.0.1",
    "@pusher/pusher-websocket-react-native": "^1.1.1",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-firebase/analytics": "^17.4.2",
    "@react-native-firebase/app": "^17.4.2",
    "@react-native-masked-view/masked-view": "0.2.8",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "@reduxjs/toolkit": "^1.8.5",
    "axios": "^0.27.2",
    "classnames": "^2.3.2",
    "crypto-js": "^3.3.0",
    "currency-symbol-map": "^5.1.0",
    "expo": "~48.0.15",
    "expo-asset": "~8.9.1",
    "expo-av": "~13.2.1",
    "expo-barcode-scanner": "~12.3.2",
    "expo-build-properties": "~0.6.0",
    "expo-clipboard": "~4.1.2",
    "expo-device": "~5.2.1",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "~4.0.1",
    "expo-location": "~15.1.1",
    "expo-media-library": "~15.2.3",
    "expo-notifications": "~0.18.1",
    "expo-sharing": "~11.2.2",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "geolib": "^3.3.3",
    "i18next": "^22.4.13",
    "i18next-http-backend": "^2.2.0",
    "intl": "^1.2.5",
    "lottie-react-native": "5.1.4",
    "mime": "^3.0.0",
    "moment": "^2.29.4",
    "nativewind": "^2.0.10",
    "react": "18.2.0",
    "react-content-loader": "^6.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^12.2.0",
    "react-native": "0.71.7",
    "react-native-animatable": "^1.3.3",
    "react-native-calendars": "^1.1291.1",
    "react-native-chart-kit": "^6.12.0",
    "react-native-device-info": "^10.3.0",
    "react-native-fast-image": "^8.6.1",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-localize": "^2.2.6",
    "react-native-maps": "^1.6.0",
    "react-native-maps-directions": "^1.9.0",
    "react-native-modal-datetime-picker": "^14.0.0",
    "react-native-modalize": "^2.1.1",
    "react-native-pager-view": "6.1.2",
    "react-native-popover-view": "^5.1.6",
    "react-native-progress": "^5.0.0",
    "react-native-qrcode-svg": "^6.2.0",
    "react-native-razorpay": "^2.3.0",
    "react-native-reanimated-carousel": "^3.0.5",
    "react-native-render-html": "^6.3.4",
    "react-native-root-toast": "^3.4.0",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-vector-icons": "^9.2.0",
    "react-native-view-shot": "3.5.0",
    "react-native-web": "~0.18.11",
    "react-redux": "^8.0.4",
    "use-debounce": "^8.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "tailwindcss": "^3.1.8"
  },
  "private": true
}

**Comment by Kudo** [comment]
> In your repo, it's "expo": "~48.0.1", whereas in my package.json it's "expo": "~48.0.15",

it should be on issue-22297 branch: https://github.com/Kudo/sdk48/blob/issue-22297/package.json#L12. it is `"expo": "~48.0.15"` too

**Comment by Kudo** [comment]
i cannot help much for an issue that we cannot repro, but you may able to add `require('assert')(packageName === 'com.growcify')` right before the` module.exports = {` in **app.config.js**

**Comment by deepak-dpt** [comment]
I am facing the same issue. A gist of app.config.ts file looks like:
`{
    name: 'some-pay-app',
    android: {
     "package": "com.myfav.payapp"
   }
// ...other properties
}`
But the generated build.gradle file has `namespace` and `applicationId` set to `com.somepayapp` instead of `com.myfav.payapp`

**Comment by nayan-dey** [comment]
is there any fix for this issue, if that how can i resolve this
