### ISSUE TITLE
[android][expo-dev-client] SDK >= 46 vendored gesture handler causes android build fail with other packages

### ISSUE THREAD

**Issue by GabrielDierks** [expo/expo#22311]
### Minimal reproducible example

https://github.com/GabrielDierks/test-huawei

### Summary

After updating to SDK 46+ our android build fails. This is caused by  "expo-dev-client": "2.2.1", or rather the related "expo-dev-menu": "2.2.0" in combination with the "@hmscore/react-native-hms-push": "^6.7.0-300", package. We get the following issue:

>1: Task failed with an exception.
>What went wrong:
>Execution failed for task ':app:mergeProjectDexDebug'.
>A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
>There was a failure while executing work items
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type devmenu.com.swmansion.common.GestureHandlerStateManager is defined multiple times: /Users/xx/root/mobile-app/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/badfdc771dfffcdbaaca8e050ce09a4aca67908ae89b610d644062833a0ee1ad_1.jar:classes.dex, /Users/xx/root/mobile-app/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/dcd30cd0bd8d4cb28c5ec273bf019d7e86245980a667359bd40e8cb5d420f649_1.jar:classes.dex

This makes us assume the vendored "react-native-gesture-handler" inside "expo-dev-menu" is causing this problem together with the hms package.

Steps to reproduce:
1. download repo
2. run yarn
3. run npx expo run:android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.25 => 0.16.27
      expo: ~48.0.15 => 48.0.15
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.7
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.0.8
    Expo Workflow: managed

**Comment by syedkadmos** [comment]
+1

**Comment by GabrielDierks** [comment]
Has been fixed with  `"expo-dev-client": "2.3.0"`
