### ISSUE TITLE
Calendar api createEventAsync wont work

### ISSUE THREAD

**Issue by IbrahimCanKALYA** [expo/expo#2231]
I hade permisson and i want to add event on device default calender but Calendar.DEFAULT return undefined. 

Calendar.createEventAsync( Calendar.DEFAULT, details).then(() =>{
                Alert.alert('Bilgilendirme', 'Alarm başarıyla kuruldu', [{ text: 'Ok' }])
            }).catch(error =>{
                Alert.alert('Hata', error.toString(), [{ text: 'Ok' }])
            })

when i create calendar manuelly and crateEvent with this calendar id crateEventAsync retruns an error.
'Error: Event could not be saved'

**Comment by IbrahimCanKALYA** [comment]
i'm getting 'Error: Event could not be saved'  when ı dont use Calendar.DEFAULT i'm getting an error  'Error: Event could not be saved'

Here is my code:

async _setAlarm(){
        const { status } =  await Permissions.askAsync('calendar');
        if(status === 'granted' && Platform.OS !== 'ios'){  
            const calendars = await Calendar.getCalendarsAsync();
            console.log('calendars')
            console.log(calendars)
            let calendarId;
            for(i=0; i<calendars.lengt; i++){
                if(calendars[i].isPrimary && calendars[i].allowsModifications){
                    calendarId = calendars[i].id
                }
            }
            if(!calendarId){
                const details ={
                    title: 'Eso Dans',
                    color: '#000000',
                    source:{
                        isLocalAccount: true,
                        name: 'esocad'
                    },
                    name:'Eso Dans',
                    ownerAccount: 'esocad',
                    timeZone: 'Europe/Istanbul',
                    allowsModifications: true,
                    allowedAvailabilities: [ Calendar.Availability.BUSY, Calendar.Availability.FREE, Calendar.Availability.TENTATIVE],
                    allowedReminders: [Calendar.AlarmMethod.ALARM, Calendar.AlarmMethod.ALERT, Calendar.AlarmMethod.EMAIL, Calendar.AlarmMethod.SMS, Calendar.AlarmMethod.DEFAULT],
                    allowedAttendeeTypes : [Calendar.AttendeeType.REQUIRED, Calendar.AttendeeType.NONE],
                    isVisible: true,
                    isSynced: true,
                    accessLevel : Calendar.CalendarAccessLevel.EDITOR,
                }
                calendarId = await Calendar.createCalendarAsync(details)
                console.log('created calendar ıd');
                console.log(calendarId)
                const detailsEvent ={
                    title: 'item.title',   
                    startDate: '2018-09-20T07:44:24.088+03:00',
                    endDate: '2018-06-20T07:44:24.088+03:00',
                    timeZone: 'Europe/Istanbul'
                }
                Calendar.createEventAsync( calendarId, detailsEvent).then(() =>{
                    Alert.alert('Bilgilendirme', 'Alarm başarıyla kuruldu', [{ text: 'Ok' }])
                }).catch(error =>{
                    Alert.alert('Hata', error.toString(), [{ text: 'Ok' }])
                })
            }
        }else if(Platform.OS === 'ios'){
            const { statusIos } = await Permissions.askAsync('reminders');
            if (statusIos === 'granted'){
                for(i=0; i<calendars.lengt; i++){
                    if(calendars[i].isPrimary && calendars[i].allowsModifications){
                        calendarId = calendars[i].id
                    }
                }
                if(!calendarId){
                    const details ={
                        title: 'Eso Dans',
                        color: '#000000',
                        entityType: Calendar.EntityTypes.REMINDER,
                        sourceId: 'raxtales2018',
                    }
                    calendarId = await Calendar.createCalendarAsync(details)
                    console.log('created calendar ıd');
                    console.log(calendarId)
                    const detailsEvent ={
                        title: 'item.title',   
                        startDate: '2018-09-20T07:44:24.088+03:00',
                        endDate: '2018-06-20T07:44:24.088+03:00',
                        timeZone: 'Europe/Istanbul'
                    }
                    Calendar.createEventAsync( calendarId, detailsEvent).then(() =>{
                        Alert.alert('Bilgilendirme', 'Alarm başarıyla kuruldu', [{ text: 'Ok' }])
                    }).catch(error =>{
                        Alert.alert('Hata', error.toString(), [{ text: 'Ok' }])
                    })
                }
            }
        }

**Comment by esamelson** [comment]
Hi @IbrahimCanKALYA - it's really hard to read code that's just pasted directly into the GH issue. Could you create a [snack](https://stackoverflow.com/help/mcve) that minimally reproduces your issue, and explain what you are trying to achieve when running into this error?
