### ISSUE TITLE
Add `./dist` to the existing list inside the `tsconfig.base.json`

### ISSUE THREAD

**Issue by dmitryusikriseapps** [expo/expo#22314]
### Minimal reproducible example

https://pastebin.com/yfsyEMrM

### Summary

As soon as the `eas update` command has been run then the `dist` folder is created inside the current project. Then, if we run the `tsc` command, then it will fail (see for reference -> https://github.com/microsoft/TypeScript/issues/50675#issuecomment-1333529960).

We can specify a custom `exclude` option inside the `tsconfig.json`, but it'll overwrite the base config. 

The suggestion is to add the `dist` folder to the existing list inside the `tsconfig.base.json`.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
      Watchman: 2023.03.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 30, 31, 32, 33, 33
        Build Tools: 30.0.2, 33.0.2
        System Images: android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.0 
      expo: ^48.0.0 => 48.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.10.0
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by danrivett** [comment]
Any update on this bug as I've run into this and seems like a simple fix if someone takes a look.

**Comment by LinusU** [comment]
Ran into this today as well, would be great to have `dist` ignored by default...

**Comment by macksal** [comment]
Hit this today too, seems like a straightforward fix that would save others some time

**Comment by danrivett** [comment]
Bump. Again ran into this today. It appears to be a 2 minute fix, so really hoping someone from Expo will pick this up soon.

**Comment by danrivett** [comment]
This really needs to be fixed. It's such a simple change unless I've misunderstood something.

**Comment by danrivett** [comment]
Still an issue.

**Comment by danrivett** [comment]
😞

**Comment by danrivett** [comment]
Still an issue 👀
