### ISSUE TITLE
[Android][expo-secure-store] KeyPermanentlyInvalidatedException/Key user not authenticated is not handled

### ISSUE THREAD

**Issue by ign699** [expo/expo#22312]
### Minimal reproducible example

https://snack.expo.dev/mY-xqohsh

### Issue
Currently, if KeyStore Key becomes unusable the package will keep throwing cannot encrypt/decrypt errors, and basically app won't be able to use it unless the app data is cleared. This is only the case when *requireAuthentication* is enabled.  There are two scenarios where this becomes an issue. I think this only applies to API > 23

### Case 1: User changed the fingerprint/KeyPermanentlyInvalidatedException

As per [https://developer.android.com/reference/android/security/keystore/KeyPermanentlyInvalidatedException](https://l.facebook.com/l.php?u=https%3A%2F%2Fdeveloper.android.com%2Freference%2Fandroid%2Fsecurity%2Fkeystore%2FKeyPermanentlyInvalidatedException%3Ffbclid%3DIwAR3-HmNmWQ_HofxANe61G5HfNhzKrJo7-7TcCCnALFJ7e_dIjGosg4eLdmE&h=AT0bJirIVNFcKbbQYCiJP6dLOp_mn-AlCn-dTKkE6k8Di7yO_vFO-fDLboLzL1yEhHvVMoj0VptksyfMeo2FuK2yZ6QXrAlnf2_uycLaoLrLyIB4ONlQYevf3w7_eCfQrzomrK6LUJnJj4UKtcYNg9LBb3s) if the fingerprint is modified/added/removed keys that require auth will be invalidated.

Repro steps:
1. Open a snack example on a device with a fingerprint
2. Open the app and authorize with a fingerprint
3. Close the app
4. Remove fingerprints/add new ones
5. Re-open the app. Cannot encrypt error will be thrown

This should be fairly easy to handle by either exposing a way to delete the key from keystore and handle it JS side or adding an appropriate try/catch around encrypt/decrypt methods and deleting the key.

### Case 2: Key user not authenticated

So I am not sure what's causing this, had this happen but wasn't able to reproduce it. Note that this issue is also persistent meaning if it happens once it'll keep happening unless you clear app data.

For some reason instead of the KeyPermanentlyInvalidatedException sometimes the exception IllegalBlockSizeException is thrown. This probably happens when the key is read but can't be used for decryption.

It happens in line [https://github.com/expo/expo/blob/main/packages/expo-secure-store/android/src/main/java/expo/modules/securestore/SecureStoreModule.java#L433](https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Fexpo%2Fexpo%2Fblob%2Fmain%2Fpackages%2Fexpo-secure-store%2Fandroid%2Fsrc%2Fmain%2Fjava%2Fexpo%2Fmodules%2Fsecurestore%2FSecureStoreModule.java%3Ffbclid%3DIwAR3oP364-uLopzyiiD4pk4UY83Ye8I0SeqjBt4mxAcuR5yiXYIntFaChpQ4%23L433&h=AT0bJirIVNFcKbbQYCiJP6dLOp_mn-AlCn-dTKkE6k8Di7yO_vFO-fDLboLzL1yEhHvVMoj0VptksyfMeo2FuK2yZ6QXrAlnf2_uycLaoLrLyIB4ONlQYevf3w7_eCfQrzomrK6LUJnJj4UKtcYNg9LBb3s) when doCipher is called.

There is another package that's also experienced this issue and fixed it by treating such errors the same way as KeyPermanentlyInvalidatedException.  [https://github.com/mCodex/react-native-sensitive-info/pull/224/files](https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2FmCodex%2Freact-native-sensitive-info%2Fpull%2F224%2Ffiles%3Ffbclid%3DIwAR3rusFHko4YRcIh2BCxzxWr6BFmWhwJjVZBX9i1cvfoiy4FeiRzXsLp2p4&h=AT0bJirIVNFcKbbQYCiJP6dLOp_mn-AlCn-dTKkE6k8Di7yO_vFO-fDLboLzL1yEhHvVMoj0VptksyfMeo2FuK2yZ6QXrAlnf2_uycLaoLrLyIB4ONlQYevf3w7_eCfQrzomrK6LUJnJj4UKtcYNg9LBb3s)

This could again be handled either by try/catching or exposing a way to delete the key from keystore.

### Related issues

Here is a list of issues that might be caused by the same root cause and if not allowing for deleting the key should still help in bringing the app to the proper state without having to have users clear app data. Seems like most of them are saying that it's caused by app updates so maybe there is a mechanism that in some cases invalidates keys in those situations as well.

- [https://github.com/expo/expo/issues/19018](https://github.com/expo/expo/issues/19018?fbclid=IwAR0eTbDr8LX3pGEGzR0fcRdc5GiohP4OZyyMzofzab0ISYbozjnsW_nNphw)
- [https://github.com/expo/expo/issues/814](https://github.com/expo/expo/issues/814?fbclid=IwAR3KaeJlVjcXdpPola8Q_RuSxCfqqOIpenjdgacV1Icp27MiewUlD7KT6dU)
- [https://github.com/expo/expo/issues/1459](https://github.com/expo/expo/issues/1459?fbclid=IwAR38jpNG1jBMpK8r1IQGktBsh-edjKR-hKj4Fxx4AC4-_jEwwRdrn10kdHI)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 27, 31, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-22 | Google APIs ARM 64 v8a, android-27 | ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.14 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
    npmGlobalPackages:
      eas-cli: 3.4.1
      expo-cli: 5.4.12
    Expo Workflow: managed

**Comment by behenate** [comment]
Hi, thanks for a very good description of the issue 😉 it has been solved in https://github.com/expo/expo/pull/22716 this issue will be closed once it's merged
