### ISSUE TITLE
expo-notifications gives error by simply importing it

### ISSUE THREAD

**Issue by sirusbaladi** [expo/expo#22327]
### Summary

As soon as Import:
import * as Notifications from "expo-notifications"; 
I get the following errors:

 ERROR  TypeError: undefined is not an object (evaluating 'nativeModule.__expo_module_name__') ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered  as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is  corrupt or there is an early initialization error when loading React Native. ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered  as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is  corrupt or there is an early initialization error when loading React Native.

I updated expo-cli, look up online but nothing could help.

### What platform(s) does this occur on?

iOS

### SDK Version

48

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: Windows 10 10.0.19045
Binaries:
Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: AI-221.6008.13.2211.9477386
npmPackages:
expo: ^47.0.0 => 47.0.13
react: 18.1.0 => 18.1.0
react-dom: 18.1.0 => 18.1.0
react-native: 0.70.8 => 0.70.8
react-native-web: ~0.18.7 => 0.18.12
Expo Workflow: managed

### Minimal reproducible example

Not sure what to put here as I'm simply importing the library and can't upload the whole repo.

**Comment by Kudo** [comment]
hi there! if you can reproduce the problem on a new project created from `yarn create expo` or `npx create-expo@latest`, please try to upload the project for us to investigate. it works for me as `simply importing the library`, so it would be helpful to know more details of how you setup the project. thank you!
