### ISSUE TITLE
Custom resolver in metro.config.js deprioritized/ignored by expo cli?

### ISSUE THREAD

**Issue by cenzovit** [expo/expo#22323]
### Summary

We are building an expo app within a yarn monorepo. Due to a sub-dependency version mismatch within two of our dependencies, we needed to write a custom resolver into our metro.config.js to allow the two module versions to be found correctly. The relevant snippet of our custom metro.config.js is as follows:

```
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName === 'event-target-shim' && context.originModulePath.includes('@daily-co')) {
    return context.resolveRequest(
      {
        ...context,
        nodeModulesPaths: [
          path.resolve(projectRoot, 'node_modules/@daily-co/react-native-webrtc/node_modules'),
        ],
      },
      moduleName,
      platform,
    );
  }
  // Fallback to chaining to the standard resolver
  return context.resolveRequest(context, moduleName, platform);
};
```

When I explore our sourcemaps or run a production build, I see that the two libraries are resolved properly; however, when I run a dev server via `expo start --dev-client`, due to the overwriting / prioritizing of expo's own custom resolvers, our custom resolver no longer seems to work. 

Is there a different way we should be informing expo-cli of our own custom resolver?

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

~47.0.14

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 3.2.57 
    Binaries:
      Node: 19.6.0 
      Yarn: 3.3.1 
      npm: 9.4.0 
      Watchman: 2023.01.23.00 
    Managers:
      CocoaPods: 1.11.3
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.14 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.9 => 0.18.12 
    Expo Workflow: bare

### Minimal reproducible example

1. Add a custom resolver via the metro.config.js resolver.resolveRequest field.  For demonstration purposes, you could do something as simple/non-functional as resolving all modules to the same file. Something along the lines of:
```
config.resolver.resolveRequest = (context, moduleName, platform) => {
  return {
    filePath: path.resolve(__dirname, 'node_modules/@expo/cli/build/src/start/index.js'),
    type: 'sourceFile',
  };
}
```
2. Confirm the resolver is operating by exploring source maps (for instance via: npx react-native-bundle-visualizer) or when running a production build. In the case of the simple demo, I end up with a miniscule non functional bundle that contains only @react-native/polyfills, the metro-runtime/require.js, and the @expo/cli/build/src/start/index.js files

3. Run a dev server via `expo start --dev-client` and see that the bundle produced has ignored the metro.config.js custom resolver.

**Comment by cenzovit** [comment]
Fun aside, google searching "ExpoCustomMetroResolver" was the first time I've ever seen no results. Which maybe once this comment is crawled will no longer be the case.

**Comment by cenzovit** [comment]
As a temporary work around, I wrote a patch to allow our custom resolver to essentially be wrapped within the custom web resolver from @expo/cli:
```
diff --git a/build/src/start/server/metro/withMetroMultiPlatform.js b/build/src/start/server/metro/withMetroMultiPlatform.js
index fce6417d8f3fa72f92f195a4cd3a50dd4950b8fd..5d444285428c61060055f921b5ad1e66d3c130f1 100644
--- a/build/src/start/server/metro/withMetroMultiPlatform.js
+++ b/build/src/start/server/metro/withMetroMultiPlatform.js
@@ -90,13 +90,16 @@ function withWebResolvers(config, projectRoot) {
             };
             // Conditionally remap `react-native` to `react-native-web`
             if (platform && platform in extraNodeModules) {
-                context.extraNodeModules = extraNodeModules[platform];
+                context.extraNodeModules = {
+                    ...(config?.resolver?.extraNodeModules ?? {}),
+                    ...extraNodeModules[platform]
+                };
             }
             const mainFields = _env.env.EXPO_METRO_NO_MAIN_FIELD_OVERRIDE ? context.mainFields : platform && platform in preferredMainFields ? preferredMainFields[platform] : context.mainFields;
             const result = resolve({
                 ...context,
                 preferNativePlatform: platform !== "web",
-                resolveRequest: undefined,
+                resolveRequest: config?.resolver?.resolveRequest,
                 // Passing `mainFields` directly won't be considered
                 // we need to extend the `getPackageMainPath` directly to
                 // use platform specific `mainFields`.
```
I think this still accomplishes what you guys are trying to do with the one custom wrapper you currently have; however, it isn't very robust/future proof since you guys left room to include more custom resolvers on your end.

**Comment by jonathan-chin** [comment]
I've been experiencing the same issue and have spent the better part of 2 hours, rereading documentation and testing, trying to get this to work. I'm unable to check if it works in prod builds but can confirm that this issue is present when running `yarn web`.

**Comment by cenzovit** [comment]
Bumping this as I was reminded that I had to apply a new patch as I was upgrading from expo 47 -> 48. I see that @EvanBacon has done work in this area relatively recently. Any guidance on best practices?

**Comment by boris-burgos** [comment]
Hello.

We have the same problem with event-target-shim and react-native-webrtc in a monorepo with yarn and we fixed this problem by removing the following configuration from metro.config.js:

`config.resolver.disableHierarchicalLookup = true`

Doing this the event-target-shim v6 package is resolved successfully and does not raise any react-native-webrtc errors.

**Comment by EvanBacon** [comment]
To solve the exact problem, I do recommend using top-level settings like `config.resolver.disableHierarchicalLookup = true` as these are accounted for in the custom Expo CLI resolver.

We don't have a baked out story for replacing the resolver at the moment, patching `withMetroMultiPlatform` is the best option for now if you need some highly custom functionality.

**Comment by bglowney** [comment]
I am seeing the same problem with expo SDK 49 as well.

**Comment by nicozenf** [comment]
@EvanBacon 
It's a bit of a surprising response since the doc actually state the customResolver is apply before all, which it's not the case at all, making fine customization really hard to do (i didn't succeed yet).

Can you be more specific about how to make use your recommendations, `disableHierarchicalLookup` and patching `withMetroMultiPlatform` ?

**Comment by ssalat** [comment]
Same issue here.. super frustrating. 

> To solve the exact problem, I do recommend using top-level settings like `config.resolver.disableHierarchicalLookup = true` as these are accounted for in the custom Expo CLI resolver.
> 
> We don't have a baked out story for replacing the resolver at the moment, patching `withMetroMultiPlatform` is the best option for now if you need some highly custom functionality.

I don't have a clue at all what is meant with "withMetroMultiPlatform"? Google Search = 0 Results.

**Comment by gabrielfurini** [comment]
> Hello.
> 
> We have the same problem with event-target-shim and react-native-webrtc in a monorepo with yarn and we fixed this problem by removing the following configuration from metro.config.js:
> 
> `config.resolver.disableHierarchicalLookup = true`
> 
> Doing this the event-target-shim v6 package is resolved successfully and does not raise any react-native-webrtc errors.

The same problem was experienced here when using a library that relies on `react-native-webrtc`. Getting rid of `config.resolver.disableHierarchicalLookup = true` fixed the problem.
Unfortunately I didn't find this discussion before spending more hours than I wanted in debugs, trials and errors...
