### ISSUE TITLE
[docs] add-tap-gesture fails in the browser 

### ISSUE THREAD

**Issue by sigmaSd** [expo/expo#22333]
### Summary

Running the code in  https://docs.expo.dev/tutorial/gestures/#add-a-tap-gesture  fails in the browser when double clicking the icon

It fails with
```
Uncaught ReferenceError: _frameTimestamp is not defined
    _f useAnimatedStyle.js:151
    _f useAnimatedStyle.js:368
    execute Mapper.js:19
    execute MapperRegistry.js:25
    _onRender JSReanimated.js:37
```

I tested with firefox and chrome, also locally and with the provided snack url in the doc link, always the same error

### Link to the related docs page

https://docs.expo.dev/tutorial/gestures/#add-a-tap-gesture

**Comment by Kudo** [comment]
hi there! that is a known issue for react-native-reanimated: https://github.com/software-mansion/react-native-reanimated/issues/3355. i'm sorry for the error and this would be resolved in next expo sdk after reanimated is upgraded.
in the meantime, you could try to add this code to your App.js as a workaround.

```js
if (window._frameTimestamp === undefined) {
  window._frameTimestamp = null;
}
```

**Comment by sigmaSd** [comment]
thanks
