### ISSUE TITLE
[Unhandled promise rejection: Error: Encountered an exception while calling native 

### ISSUE THREAD

**Issue by HakimIno** [expo/expo#22339]
### Summary

[Unhandled promise rejection: Error: Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Default FirebaseApp is not initialized in this process com.kimsnow33.travelapp. Make sure to call FirebaseApp.initializeApp(Context) first.] 
error getExpoPushTokenAsync

### SDK Version

48.0.10

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v19.2.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
    npmPackages:
      expo: ~48.0.10 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.3.2
    Expo Workflow: bare

### Minimal reproducible example

 const token = (
        await Notifications.getExpoPushTokenAsync({
          projectId,
        })
      ).data;
      console.log(token);

**Comment by milhouse34521** [comment]
Same issue:

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.12.1 - C:\Program Files (x86)\nodejs\node.EXE
      npm: 9.6.5 - C:\Program Files (x86)\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    npmPackages:
      expo: ~48.0.11 => 48.0.11
      react: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    Expo Workflow: managed

Error:
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Encountered an exception while calling native method: Exception occurred while executing exported method requestPermissionsAsync on module ExpoNotificationPermissionsModule: String resource ID #0xffffffff
Error: Encountered an exception while calling native method: Exception occurred while executing exported method requestPermissionsAsync on module ExpoNotificationPermissionsModule: String resource ID #0xffffffff
    at construct (native)
    at apply (native)
    at _construct (http://192.168.1.37:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:3348:28)     
    at Wrapper (http://192.168.1.37:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:3310:25)        
    at construct (native)
    at _createSuperInternal (http://192.168.1.37:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:96610:322)
    at call (native)
    at CodedError (http://192.168.1.37:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:96618:26)    

Example:
Copied Directly from [Expo Docs](https://docs.expo.dev/versions/latest/sdk/notifications/) 
```
import { useState, useEffect, useRef } from 'react';
import { Text, View, Button, Platform } from 'react-native';
import * as Device from 'expo-device';
import * as Notifications from 'expo-notifications';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function App() {
  const [expoPushToken, setExpoPushToken] = useState('');
  const [notification, setNotification] = useState(false);
  const notificationListener = useRef();
  const responseListener = useRef();

  useEffect(() => {
    registerForPushNotificationsAsync().then(token => setExpoPushToken(token));

    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
    });

    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      console.log(response);
    });

    return () => {
      Notifications.removeNotificationSubscription(notificationListener.current);
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-around',
      }}>
      <Text>Your expo push token: {expoPushToken}</Text>
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>Title: {notification && notification.request.content.title} </Text>
        <Text>Body: {notification && notification.request.content.body}</Text>
        <Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
      </View>
      <Button
        title="Press to schedule a notification"
        onPress={async () => {
          await schedulePushNotification();
        }}
      />
    </View>
  );
}

async function schedulePushNotification() {
  await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail! 📬",
      body: 'Here is the notification body',
      data: { data: 'goes here' },
    },
    trigger: { seconds: 2 },
  });
}

async function registerForPushNotificationsAsync() {
  let token;

  if (Platform.OS === 'android') {
    await Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  if (Device.isDevice) {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log(token);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  return token;
}

```

**Comment by Kudo** [comment]
hi there! could you provide a minimal reproducible example project? as pointed out in the error message, maybe you've missed the call to `FirebaseApp.initializeApp()` where should be included when integrating [react-native-firebase](https://docs.expo.dev/guides/using-firebase/#using-react-native-firebase)

**Comment by milhouse34521** [comment]
My code is literally the code from the [official Expo Dev docs](https://docs.expo.dev/versions/latest/sdk/notifications/) provided by the Expo team re: Notifications. I'm sure it could be shorter / include a minimal reproducible example as Hakimlno provided

`const token = (
await Notifications.getExpoPushTokenAsync({
projectId,
})
).data;
console.log(token);`

but if its Expo providing the example perhaps that entire example should be reviewed.

**Comment by Kudo** [comment]
sorry i've been confusing. it's not necessary to have react-native-firebase for this case. as [the doc pointed out](https://docs.expo.dev/versions/latest/sdk/notifications/#android), you have to further setup FCM for your project: https://docs.expo.dev/push-notifications/push-notifications-setup/#android. please take a look and check whether it works for you. thanks!

**Comment by Muhammad-Usama-lab** [comment]
@Kudo I'm experiencing the same issue.
Issue: Notifications are working fine in development but giving this error in production.
This is my code.

![code](https://user-images.githubusercontent.com/57321157/236186461-becb067a-5954-4c69-ac5b-b9acbed1cbbc.png)

![code1](https://user-images.githubusercontent.com/57321157/236187057-abdbc55c-1a0d-45e2-93c1-a42b2a359456.png)
![WhatsApp Image 2023-05-04 at 4 22 33 PM](https://user-images.githubusercontent.com/57321157/236190182-8403f4b6-d576-4a7c-a62d-b637171be458.jpeg)

**Comment by Kudo** [comment]
@Muhammad-Usama-lab would you mind to share your app.json?

**Comment by Muhammad-Usama-lab** [comment]
> @Muhammad-Usama-lab would you mind to share your app.json?

Here it is 
![app(json)](https://user-images.githubusercontent.com/57321157/236418209-e4bd5da6-b67c-4488-9c3d-1928ab6fe5db.png)

**Comment by youngjun625** [comment]
any updates? facing the same issue

**Comment by Muhammad-Usama-lab** [comment]
> any updates? facing the same issue
Yes, I have followed the expo-notifications documentation, on a new project. It works fine.
In my case there was a configuration issue, may be in firebase project or here in native android repository.
Feel free to ask anything.

**Comment by youngjun625** [comment]
Thanks for the reply. I realized this happens when I build the development build first, and then adding all the google-servies.json, etc after wards. For me the fix was to delete the existing ./android folder and run ' npx expo run:android ' again to rebuild the app

**Comment by rogueloop** [comment]
> @Kudo I'm experiencing the same issue. Issue: Notifications are working fine in development but giving this error in production. This is my code.
> 
> ![code](https://user-images.githubusercontent.com/57321157/236186461-becb067a-5954-4c69-ac5b-b9acbed1cbbc.png)
> 
> ![code1](https://user-images.githubusercontent.com/57321157/236187057-abdbc55c-1a0d-45e2-93c1-a42b2a359456.png) ![WhatsApp Image 2023-05-04 at 4 22 33 PM](https://user-images.githubusercontent.com/57321157/236190182-8403f4b6-d576-4a7c-a62d-b637171be458.jpeg)

try this  
```
token = (
        await Notifications.getExpoPushTokenAsync({
          projectId: Constants.expoConfig.extra.eas.projectId,
        })
      ).data
```

**Comment by amschel99** [comment]
Will rebuilding the development build if I'm using expo-dev-client fix the issue? because I have followed all the steps described in the documentation by expo and I still get the same error.

**Comment by Stetzon** [comment]
Noting that the warning is still present when following the [minimum working example](https://docs.expo.dev/push-notifications/push-notifications-setup/#add-a-minimal-working-example) on a clean project and using Expo Go on an android device.  The line throwing the error is `const { status } = await Notifications.requestPermissionsAsync();` 
> [Error: Encountered an exception while calling native method: Exception occurred while executing exported method requestPermissionsAsync on module ExpoNotificationPermissionsModule: String resource ID #0xffffffff]

**Comment by darrensw777** [comment]
I can confirm this is a thing. I'm seeing the error and my app has no promise related code, which leans towards Expo.

**Comment by brunolucena** [comment]
Had this isssue and fixed by removing android folder and building the app again with `npx expo run:android`
If you built the app one time before adding the configuration for push notification (google-services.json), the file won't be added to the build.
I think this can be mentioned in the docs.
