### ISSUE TITLE
AuthSession.getRedirectUrl() always return BAD address in Expo client iOS version

### ISSUE THREAD

**Issue by imwilliamxy** [expo/expo#2233]
Sorry for my bad English.
It seems that since ver 2.8, Expo Client iOS version always return a BAD address in  AuthSession.getRedirectUrl()

In normal status, it should return an address like 'https://auth.expo.io/@username/project-name',Now it always return a address like 'https://auth.expo.io/UNVERIFIED-192.168.0.119-project-name'.

It's only appears in iOS version Expo client,Android version Expo client runs ok.

My env:
expo SDK 30,
node 10.10.0
nom 6.4.1

**Comment by tsapeta** [comment]
Hi @imwilliamxy, could you try to update your Expo Client to v2.8.2? It should have solved this issue.

**Comment by imwilliamxy** [comment]
> Hi @imwilliamxy, could you try to update your Expo Client to v2.8.2? It should have solved this issue.

2.8.2 has solved this problem on my iOS device.
