### ISSUE TITLE
code128 barcode scanning with ]C1 prefixed

### ISSUE THREAD

**Issue by Kailash-MAF** [expo/expo#22345]
### Minimal reproducible example

https://snack.expo.dev/@kailash23/d0a06c

### Summary

<img width="439" alt="image-20230501-042233" src="https://user-images.githubusercontent.com/88423485/235502957-2c348500-6df9-4607-99ed-44e5a4062840.png">

Barcode value : DR5951
What mobile app reading : ]C1DR5951

```
  <Camera
        style={StyleSheet.absoluteFill}
        type={CameraType.back}
        flashMode={FlashMode.on}
        onBarCodeScanned={({ data, type }) => {
          Alert.alert(data);
        }}
        barCodeScannerSettings={{
          barCodeTypes: [
            BarCodeScanner.Constants.BarCodeType.code128,
            BarCodeScanner.Constants.BarCodeType.qr,
          ],
        }}
  />
 ```
 I will soon replicate this issue in a bare project with expo modules.
 For now I have uploaded expo snack but it is working fine in snack - ]C1 not coming.
 
 However in bare react native project using expo modules this issue is coming.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.2.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.2.0 - /usr/local/bin/npm
      Watchman: 2022.12.05.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/kailashuniyal/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.16 => 46.0.21 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.6 => 0.70.6 
    Expo Workflow: bare

**Comment by Bjorgar** [comment]
The same issue

**Comment by sarahaoun** [comment]
any update on this?

**Comment by devoren** [comment]
@Kailash-MAF Hello, did you find a solution?

**Comment by germanmedinasl** [comment]
This is my botched job, but unluckily I "solved" it with this:
`  if (data.startsWith("]C1") || data.startsWith("]c1")) {
      data = data.substring(3);
    } `
Right after the camera captured the code (`data`).
    I have yet to test some bar codes to see if this is the workaround, but for now it seems a solution to me. Please try the code and reply if it worked to you as well.
