### ISSUE TITLE
Fingerprint not working with Expo SDK 29 + Android API 23

### ISSUE THREAD

**Issue by OmriSama** [expo/expo#2235]
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.10.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4
```

Cross-platform, iOS/Android Standalone app, not detached.

Here are my AVD details:
```
Name: Nexus_4_API_23
CPU/ABI: Google APIs Intel Atom (x86)
Path: /Users/ogabay/.android/avd/Nexus_4_API_23.avd
Target: google_apis [Google APIs] (API level 23)
Skin: 768x1280
SD Card: 100M
hw.dPad: no
hw.lcd.height: 1280
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 4
vm.heapSize: 80
skin.dynamic: yes
hw.device.manufacturer: Google
hw.lcd.width: 768
hw.gps: yes
hw.initialOrientation: Portrait
skin.path.backup: _no_skin
image.androidVersion.api: 23
hw.audioInput: yes
image.sysdir.1: system-images/android-23/google_apis/x86/
tag.id: google_apis
showDeviceFrame: no
hw.camera.back: virtualscene
hw.mainKeys: no
AvdId: Nexus_4_API_23
hw.camera.front: emulated
hw.lcd.density: 320
avd.ini.displayname: Nexus 4 API 23
hw.arc: false
hw.gpu.mode: auto
hw.device.hash2: MD5:17b0085166068187e5b5660b49fe20b4
hw.ramSize: 1536
hw.trackBall: no
PlayStore.enabled: false
fastboot.forceColdBoot: yes
hw.battery: yes
hw.cpu.ncore: 4
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

### Expected Behavior
When `Expo.Fingerprint.hasHardwareAsync()` is called when running on a device that has Android API 23 (Android 6.0 in this case), it should return `true`.

### Actual Behavior
When `Expo.Fingerprint.hasHardwareAsync()` is called when running on a device that has Android API 23 (Android 6.0 in this case), it returns `false`. Fingerprint seems to work elsewhere in the OS, for example to unlock the device.

As soon as I upgraded the Android instance to API 24, Fingerprint started working again.

Going to try to upgrade to SDK 30 soon to see if it fixes it.

**Comment by tsapeta** [comment]
Hey @OmriSama, thanks for your report! 😉 
I guess SDK 30 will not solve this issue as nothing has changed in this method which is pretty simple: 

https://github.com/expo/expo-local-authentication/blob/39923072dbddca36a82b82d0d28de03759746039/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java#L87-L91

After quick research, it looks like Android's `FingerprintManager` works with API 23 and higher, so we need to use `FingerprintManagerCompat` class instead. See related post on [stackoverflow](https://stackoverflow.com/questions/37509474/android-fingerprint-on-sdk23). I'll try to fix this before next release, but if you'd like you can also create a pull request for this 🙂

**Comment by OmriSama** [comment]
> Hey @OmriSama, thanks for your report! 😉
> I guess SDK 30 will not solve this issue as nothing has changed in this method which is pretty simple:
> 
> [expo/modules/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java](https://github.com/expo/expo/blob/f680127237fef701a55d99053335034bdbf15ae9/modules/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java#L87-L91)
> 
> Lines 87 to 91 in [f680127](/expo/expo/commit/f680127237fef701a55d99053335034bdbf15ae9)
> 
>  @ExpoMethod 
>  public void hasHardwareAsync(final Promise promise) { 
>    boolean hasHardware = mFingerprintManager.isHardwareDetected(); 
>    promise.resolve(hasHardware); 
>  } 
> After quick research, it looks like Android's `FingerprintManager` works only with API 23 and higher, so we need to use `FingerprintManagerCompat` class instead. See related post on [stackoverflow](https://stackoverflow.com/questions/37509474/android-fingerprint-on-sdk23). I'll try to fix this before next release, but if you'd like you can also create a pull request for this 🙂

Sounds good except it appears that `mFingerprintManager` already gets initialized to a `FingerprintManagerCompat` object... look at lines 71-75 and also by the constructor.

**Comment by tsapeta** [comment]
Oh yeah, sorry I missed that 😅 Ok, so I'll dive deeper into it soon.

**Comment by marexv** [comment]
Hi! Are there any updates on this issue?

**Comment by Szymon20000** [comment]
Hi! On some Android devices isHardwareDetected() just doesn't work despite of having api 23 or higher.
[link](https://stackoverflow.com/questions/40802019/android-fingerprint-ishardwaredetected-not-working).

**Comment by marexv** [comment]
> 
> 
> Hi! Are there any updates on this issue?

For me the issue was the wrong import statement. Got it to work after doing import like this:

`import { LocalAuthentication } from 'expo';` 

And then code example:

`let compatible = await LocalAuthentication.hasHardwareAsync();`

Phone: Samsung Galaxy S8, Android version 8.0.0. This is probably a bit of topic but there aren't many cases on web so this might be useful for somebody.

**Comment by tsapeta** [comment]
I'm closing this issue as there is no proper solution that would work on all devices. As written two comments above, it seems to be an internal bug in Android API 23 that affects some devices.
