### ISSUE TITLE
Cannot find native module 'ExpoCrypto' (with auth-session)

### ISSUE THREAD

**Issue by hawkeye312** [expo/expo#22352]
### Minimal reproducible example

https://snack.expo.dev/@dadmakefire/tenacious-pizza?platform=android

### Summary

Apologies if this is the wrong forum. I could see it also in expo-dev-client or documentation sections. Feel free to move.

I followed this tutorial: https://docs.expo.dev/versions/latest/sdk/auth-session/

I am using the latest versions as of May 1, 2023.

1. Boilerplate `npx create-expo-app` project.

2. `npx expo install expo-auth-session expo-crypto expo-web-browser`

3. Build dev client on EAS

When running on emulator, I get error: Cannot find native module 'ExpoCrypto'.

Here is my package.json:

```
{
  "name": "test-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.15",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "expo-dev-client": "~2.2.1",
    "expo-auth-session": "~4.0.3",
    "expo-crypto": "~12.2.1",
    "expo-web-browser": "~12.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

Here is my App.js:

```
import { useEffect, useState } from "react";
import { StyleSheet, Text, View, Button } from "react-native";
import * as WebBrowser from "expo-web-browser";
import * as Google from "expo-auth-session/providers/google";

WebBrowser.maybeCompleteAuthSession();

export default function App() {
  const [token, setToken] = useState("");
  const [userInfo, setUserInfo] = useState(null);

  const [request, response, promptAsync] = Google.useAuthRequest({
    expoClientId: '---expo---.apps.googleusercontent.com',
    iosClientId: '---ios---.apps.googleusercontent.com',
    androidClientId: '---android---.apps.googleusercontent.com',
  });

  useEffect(() => {
    if (response?.type === "success") {
      setToken(response.authentication.accessToken);
      getUserInfo();
    }
  }, [response, token]);

  const getUserInfo = async () => {
    try {
      const response = await fetch(
        "https://www.googleapis.com/userinfo/v2/me",
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );

      const user = await response.json();
      setUserInfo(user);
    } catch (error) {
      // Add your own error handler here
    }
  };

  return (
    <View style={styles.container}>
      {userInfo === null ? (
        <Button
          title="Sign in with Google"
          disabled={!request}
          onPress={() => {
            promptAsync();
          }}
        />
      ) : (
        <Text style={styles.text}>{userInfo.name}</Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  text: {
    fontSize: 20,
    fontWeight: "bold",
  },
});

```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.8.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by gabrieldonadel** [comment]
Hi @hawkeye312 have you installed the new build to you simulator after installing `expo-crypto`? Instaling native modules require a new native build

**Comment by hawkeye312** [comment]
Yes, this was a brand new app I created and all I did was follow the
tutorial on the Google auth-session page. So I installed the dev client on
the emulator for the first time after EAS build with the boilerplate code
on there.

**Comment by gabrieldonadel** [comment]
@hawkeye312 Do you mind trying to reinstall your EAS app build to your simulator? I just tested the code you shared and seems to work fine 
 
![image](https://user-images.githubusercontent.com/11707729/235763391-f5e1e646-ca1e-4e39-b0d5-e4e47bcf1cdd.png)

**Comment by hawkeye312** [comment]
Same thing. Are you running on Expo Go or Dev Client?

There is also one other error. Does that provide any more clues?

```
Error: Cannot find native module 'ExpoCrypto', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by hawkeye312** [comment]
OK, weird. I was able to fix it by specifying CLI version in `eas.json`!

```
"cli": {
    "version": ">= 3.10.2"
  }
```

When it was failing, that parameter was excluded entirely. I wonder what the default version is, and why that matters?

**Comment by zlanich** [comment]
I'm also having this issue in local on and production on Android. Here's another related issue I commented on: https://github.com/expo/expo/issues/17270#issuecomment-1577238439

@hawkeye312 Did you notice issues in production builds too (I'm currently just doing internal distribution)? I'm running `eas-cli/3.13.2 node-v18.16.0` according to the terminal atm.

**Comment by hawkeye312** [comment]
> I'm also having this issue in local on and production on Android. Here's another related issue I commented on: https://github.com/expo/expo/issues/17270#issuecomment-1577238439
> 
> @hawkeye312 Did you notice issues in production builds too (I'm currently just doing internal distribution)? I'm running `eas-cli/3.13.2 node-v18.16.0` according to the terminal atm.

See prior comment. It went away when I explicitly specifically `cli` version in `eas.json`.

**Comment by zlanich** [comment]
@hawkeye312 I'll be darned, that actually worked! Thank you very much!

**Comment by Matheusfbio** [comment]
just reinstall the project again on android or ios, I did it here on mine and it worked, and well I followed this pattern for the other dependenc
![image](https://github.com/expo/expo/assets/83082876/26e445fa-91cb-4231-91dd-a614dc3549ba)
ies.
![image](https://github.com/expo/expo/assets/83082876/6dc51a9a-b1c0-4c05-b2d0-a83a68d52e4b)
![image](https://github.com/expo/expo/assets/83082876/5063c866-cf3f-4afe-adac-0068526e6040)

**Comment by apicgg** [comment]
You can use ```npx expo prebuild --clean``` which will rebuild you `android` and `ios` native modules.

**Comment by Rohithegade02** [comment]
im facing this issue
