### ISSUE TITLE
BarCodeScanner.scanFromURLAsync

### ISSUE THREAD

**Issue by Relison** [expo/expo#22365]
### Summary

Hello! I'm trying to read a barcode from an image saved on the device, on Android it works and on IOS it returns an empty array.
Thanks

 const results = await BarCodeScanner.scanFromURLAsync(imagePath)

### SDK Version

expo-barcode-scanner 12.1.0 e Bom dia 12.3.2

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.2.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 9.6.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.5.2 => 0.5.2 
      @expo/webpack-config: ^0.17.2 => 0.17.4 
      expo: ~47.0.14 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ^0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.9.1
      expo-cli: 6.3.2
    Expo Workflow: bare

### Minimal reproducible example

const scanBarcodeFromImage = async (imagePath) => {
        const results = await BarCodeScanner.scanFromURLAsync(imagePath)

        if (!Array.isArray(results) || results.length === 0) {
            return false;
        }

        return results[0].data.substring(3)
    }

**Comment by samuthekid** [comment]
Also happening here! Here's a snack
https://snack.expo.dev/@rls/scanfromurlasync-broken

**Comment by AndreaLiboni** [comment]
> Also happening here! Here's a snack https://snack.expo.dev/@rls/scanfromurlasync-broken
> 
> I only tested on Android, but my problem is a little different: most of the times, I get an empty array, even though the image I'm providing came from the `<Camera>` component which detected a QR code, but the scanFromURLAsync method doesn't return anything...

I'm in the exact same situation and i have the exact same problem...

**Comment by ioss** [comment]
Just tried your snack and it works for me.
Did you use a QR-Code or another type of barcode? Because iOS does only detect QR codes in photos.
