### ISSUE TITLE
e2e testing for Expo managed workflow

### ISSUE THREAD

**Issue by andreibahachenka** [expo/expo#22363]
### Summary

Hey all
I'm on the way to use detox in Expo, but what I faced is that It's not clear according to the documentation how to install detox with Expo managed workflow.

I would like to know for now:
1. In general, does the Expo have an opportunity to install detox with the _managed_ workflow without `expo prebuild` that makes the project to use the _bare_ workflow
2. If so, how it can be done?

### Link to the related docs page

https://docs.expo.dev/build-reference/e2e-tests/

### Anything else?

Will be happy for any information

_No response_

**Comment by b0n1q** [comment]
up

**Comment by b0n1q** [comment]
hey guys, any news on this?

**Comment by amandeepmittal** [comment]
Hey @b0n1q, will look into this and let you know.

**Comment by b0n1q** [comment]
> Hey @b0n1q, will look into this and let you know.

thank you

**Comment by b0n1q** [comment]
hey guys! is there any updates on this?

**Comment by b0n1q** [comment]
@amandeepmittal hey! hope you are good
could you please post some update on this?

**Comment by amandeepmittal** [comment]
Hey @b0n1q, sorry for the inconvenience and not getting back to you on this. Will provide updates soon.

**Comment by b0n1q** [comment]
> Hey @b0n1q, for a managed project the steps mentioned in the guide should work except when running `npx expo prebuild ` command, you can run `npx expo prebuild --no-install` command. This new command will generate native directories.The Detox config plugin will make the modifications needed to run Detox tests.

hey! thanks for reply
Probably this needs to be added to the documentation

anyway, I'm trying to launch this command and get an error
Maybe you have more detailed description to install Detox for managed workflow?

```
Failed to create the native project.
You may want to delete the `./ios` and/or `./android` directories before trying again.
```

**Comment by b0n1q** [comment]
Hey, @amandeepmittal
Could you please check the message above?

**Comment by b0n1q** [comment]
Hello, @amandeepmittal 
could you please provide some progress of this ticket

**Comment by b0n1q** [comment]
Hey, @amandeepmittal 
could you provide some status for this?

**Comment by Sulaimanma** [comment]
Hey @b0n1q , I met the same issue. Do you get it work with managed flow by any chance?

**Comment by amandeepmittal** [comment]
Hey @andreibahachenka, we've moved away from Detox to Maestro in the latest update of this guide which works whether you have native projects generated or not and requires much less setup as compared to the previous configuration. The Detox guide is deprecated and we won't be working on maintaining it in the future.
