### ISSUE TITLE
TextInput onBlur callback does not trigger consistently

### ISSUE THREAD

**Issue by PrimeTimeTran** [expo/expo#22360]
### Minimal reproducible example

https://snack.expo.dev/@primetimetran/dc9a9f

### Summary

The `onBlur` callback of `TextInput` isn't invoked consistently.

The `TextInput` component `onBlur` callback **is** invoked inside of `snack.expo.dev` when anything outside of the input is pressed(desired behavior).

![onBlur triggered](https://user-images.githubusercontent.com/16382165/235821299-d2a3b087-7567-433f-be62-7147dab0de3b.gif)

The `TextInput` component `onBlur` callback isn't invoked inside of Expo `48` unless **another** `TextInput` is pressed.

![onBlur not triggered](https://user-images.githubusercontent.com/16382165/235821293-6ff2d7c2-930a-4bda-b086-fa0e22bc3391.gif)

### Expected Behavior

When anything outside of  `TextInput` is pressed or tapped the currently focused `TextInput` triggers it's `onBlur` callback.

I expect that after focusing an input and then pressing anything else(including the green area) that the `onFocus` should trigger; **not just** when tapping another input.

### Environment

```sh
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
      Yarn: 3.5.0 - ~/.volta/tools/image/yarn/3.5.0/bin/yarn
      npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
      Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed
```

**Comment by Tobjoern** [comment]
Yes, I'm facing the same issue, but I think it has something to do with 'react-native' and not expo itself.
