### ISSUE TITLE
Can not saved images on Webview.

### ISSUE THREAD

**Issue by ru88s** [expo/expo#2236]
Can not saved images on Webview.
Long tap does not display the menu.
Please fix this.

**Packages:**
expo: 30.0.0
react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz

**Reproducible Demo** 
Snack: https://snack.expo.io/@wataruyonamine/can-not-saved-images-on-webview

**Expected Behavior** 
Can saved images on webview.

**Comment by esamelson** [comment]
Hi @ru88s - Expo does not own the `WebView` component currently, we just pull it in from React Native, so you're better off opening an issue on the webview component's repo instead: https://github.com/react-native-community/react-native-webview

**Comment by ru88s** [comment]
Hi @esamelson understood. Thank you for investigating.
