### ISSUE TITLE
[docs] Reference to postPublish hooks not being executed in contradiction with sentry-expo documentation

### ISSUE THREAD

**Issue by abumalick** [expo/expo#22366]
### Summary

In build reference migrating documentation, it is stated that:
> Since we no longer publish at build time, `postPublish` hooks in **app.json** will not be executed on the build. If you use Sentry, update the `sentry-expo` library to the latest version and follow the updated instructions in [Using Sentry](/guides/using-sentry/#configure-a--postpublish--hook). If you have other custom `postPublish` hooks, you can follow the same approach used in `sentry-expo` to support `postPublish` hook type of behavior.

However in the linked documentation they explain how to configure the `postPublish` hook:
https://docs.expo.dev/guides/using-sentry/#configure-a-postpublish-hook
![image](https://user-images.githubusercontent.com/8377185/235910321-aed91a7e-f7c4-43e9-bdb5-6835e790a965.png)

The postPublish hook is actually executed, we should amend the migration documentation. 

### Link to the related docs page

https://github.com/expo/expo/blob/main/docs/pages/build-reference/migrating.mdx?plain=1#L118

**Comment by bradjones1** [comment]
Came here to say basically the same thing. The config is _kinda_ used, however per https://github.com/expo/sentry-expo/issues/287#issuecomment-1419215252 it appears you can't override the `release` or `distribution` keys, contrary to what the docs would lead you to believe. Also re: upstream https://github.com/getsentry/sentry-react-native/issues/2450
