### ISSUE TITLE
[docs] ExpoAuthSession for Facebook is not working

### ISSUE THREAD

**Issue by ScreamZ** [expo/expo#22372]
### Summary

![image](https://user-images.githubusercontent.com/6640835/235968269-8763a096-ce62-473c-a860-799e1755921e.png)

It seems that this documentation is not up to date, screenshots are not up to date and its not possible to provide deep link URL in valid OAuth redirect URLs

Sample

myapp://expo-development-client/?url=https://u.expo.dev/43ca14c3-b391-429a-97c5-6b39a5d856ac?channel-name=production

### Link to the related docs page

https://docs.expo.dev/guides/facebook-authentication/#create-a-facebook-app

### Anything else?

Also have a look at https://github.com/expo/fyi/blob/main/auth-proxy-migration.md which use the same pattern.

**Expo 48 also gives** Field: scheme - should be string. (but the doc ask for array with app scheme and fb22434324 scheme)
![IMG_7135FD9BF45B-1](https://user-images.githubusercontent.com/6640835/235995293-75342b0a-9573-4b68-9bfa-4743c71dc4fe.jpeg)

**Comment by amandeepmittal** [comment]
Sorry for the inconvince caused. Now, we do support the array type for setting the scheme in **app.json**. Althoug, we've deprecated Facebook auth providers from expo-auth-session starting SDK 49. We recommend using a native library such as [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/).

We don't maintain this native library. However, we did write a short guide on what steps might be required to configure an Expo project: [docs.expo.dev/guides/facebook-authentication](https://docs.expo.dev/guides/facebook-authentication/), when using these libraries. If you're creating a new app, Facebook has also changed the way how a developer app on Facebook's end is created. Please follow their instructions if you decide to use that library.
