### ISSUE TITLE
Cannot find module 'metro-core' on npx expo start --web

### ISSUE THREAD

**Issue by givik** [expo/expo#22378]
### Summary

Hello Expo Developers. I have just installed React Native for Web to try it and I get the following error:
Does Anyone know what is going on? https://docs.expo.dev/workflow/web/

```
npx expo start --web
Starting project at /Applications/MAMP/htdocs
Error: Cannot find module 'metro-core'
Require stack:
- /Applications/MAMP/htdocs/node_modules/@expo/cli/build/src/start/server/metro/instantiateMetro.js
- /Applications/MAMP/htdocs/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js
- /Applications/MAMP/htdocs/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /Applications/MAMP/htdocs/node_modules/@expo/cli/build/src/start/startAsync.js
- /Applications/MAMP/htdocs/node_modules/@expo/cli/build/src/start/index.js
- /Applications/MAMP/htdocs/node_modules/@expo/cli/build/bin/cli 
```

### What platform(s) does this occur on?

Web

### SDK Version

^48.0.16

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.5 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.4 
      expo: ^48.0.16 => 48.0.16 
      react-dom: 18.2.0 => 18.2.0 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

### Minimal reproducible example

my index.js
```
import { registerRootComponent } from 'expo';
import App from './App';

registerRootComponent(App);
```

**Comment by thisIsGur** [comment]
I am also having same issue

**Comment by Alan-Graton** [comment]
I'm having the same error. I installed some Components packages (date modals, etc) and then my project broke.

Already ran `npm uninstall <my package>` and upgraded eas and expo to it's latests versions

**Comment by valdydev** [comment]
I have the same error on react-native , even removing the node_module 😔😔

**Comment by Alan-Graton** [comment]
> I have the same error on react-native , even removing the node_module 😔😔

I got it working now.

I just followed the **Upgrading your App** section in [https://blog.expo.dev/expo-sdk-48-ccb8302e231](url)

After that a needed to upgrade my NodeJS version to +16 (was using **V14.20.0** and currently using **V18.16.1**). And maybe you need to upgrade your NPM version as well (I needed ;-;).

Then a ran `npm i` and tried again. Hope this helps

**Comment by samcambridge** [comment]
@givik you closed but gave no solution, a colleague is having this issue but my machine is fine, what was your fix?

**Comment by givik** [comment]
@samcambridge Sorry. I don't remember what was my solution.

**Comment by givik** [comment]
@Alan-Graton share your solution. The link you provided does not work. Thanks guys!

**Comment by Alan-Graton** [comment]
@givik Done! Added a **Edit** section and fixed the link

**Comment by Alan-Graton** [comment]
> ## Edit - 11/28/2023
> ### Description
> Docs link is working now
> 
> > I have the same error on react-native , even removing the node_module 😔😔
> 
> I got it working now.
> 
> I just followed the **Upgrading your App** section in https://blog.expo.dev/expo-sdk-48-ccb8302e231
> 
> After that a needed to upgrade my NodeJS version to +16 (was using **V14.20.0** and currently using **V18.16.1**). And maybe you need to upgrade your NPM version as well (I needed ;-;).
> 
> Then a ran `npm i` and tried again. Hope this helps

This was **givik** solution

**Comment by givik** [comment]
I am closing this

**Comment by givik** [comment]
closed.

**Comment by givik** [comment]
closed
