### ISSUE TITLE
Can we update the librairy react-native-svg to the latest ?

### ISSUE THREAD

**Issue by YoshiYo** [expo/expo#2238]
Hi team,

I'm working on expo since 3~4 months ago now. Btw, great job. Clairly the best tool right now to work  on React Native. 

I'm facing an issue according to my latest issue opened on [react-native-svg](https://github.com/react-native-community/react-native-svg/issues/787)

Can we update the librairy to the next release of EXPO SDK, to handle the new proprety added, `<Mask>` ?

**Comment by N1ghtly** [comment]
Yes please! This would also fix a massive bug where images are being rendered upside down.

**Comment by tuqire** [comment]
This would also really help me, currently trying to use `Mask` component, but it does not exist in Expo.

**Comment by tsapeta** [comment]
Updated in PR #2492. `react-native-svg@8.0.8` will be available in the next SDK 😉

**Comment by tsapeta** [comment]
@tuqire, we started releasing SDK 31 today, you can track the release here: #2491
The date of the actual release is unknown as it depends on too many aspects, but we hope to make it available next week 😉
