### ISSUE TITLE
Expo Notifications giving error in production.

### ISSUE THREAD

**Issue by Muhammad-Usama-lab** [expo/expo#22389]
@Kudo I'm experiencing the same issue.
Issue: Notifications are working fine in development but giving this error in production.
This is my code.

![code](https://user-images.githubusercontent.com/57321157/236186461-becb067a-5954-4c69-ac5b-b9acbed1cbbc.png)

![code1](https://user-images.githubusercontent.com/57321157/236187057-abdbc55c-1a0d-45e2-93c1-a42b2a359456.png)
![WhatsApp Image 2023-05-04 at 4 22 33 PM](https://user-images.githubusercontent.com/57321157/236190182-8403f4b6-d576-4a7c-a62d-b637171be458.jpeg)

_Originally posted by @Muhammad-Usama-lab in https://github.com/expo/expo/issues/22339#issuecomment-1534600118_

**Comment by Kudo** [comment]
it's a duplicated issue as #22339, let's update in #22339 if there's no repro.
