### ISSUE TITLE
ReactNativeFlipper.java generation bug

### ISSUE THREAD

**Issue by nonam4** [expo/expo#22382]
### Summary

I'm following [docs](https://docs.expo.dev/build-reference/variants/) about changing app package name depending on current environment but this leads to problems generating release `ReactNativeFlipper.java`.

When you run `expo prebuild` or `npx expo prebuild` (even on a clear project without any android/ios folder) the `ReactNativeFlipper.java` is generated with wrong package name and inside wrong folder.

E.g: 
My app in dev environment will use dev.myapp package name and in prod uses com.myapp.

After running prebuild command in dev enviroment, if you go to `/android/app/src/release/java/....` it was suposed to flipper file be generated inside `.../java/dev/myapp` but it's folder is: `.../java/com/myappdev`

The same happens with package name inside this file. instead of `package dev.myapp` it is `package com.myappdev`

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/ncsistemas/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 31, 33, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1
        System Images: android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
      react-native-web: ~0.19.4 => 0.19.4 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.3.7
    Expo Workflow: bare

### Minimal reproducible example

Just change android package name inside `app.json` or `app.config.js` and run `expo prebuild`

**Comment by nonam4** [comment]
this is related to [this](https://github.com/expo/expo/issues/21477) issue

**Comment by Kudo** [comment]
hi there! as pointed out, this is duplicated and i've updated the answer at https://github.com/expo/expo/issues/21477#issuecomment-1548917338. please check whether `npx expo prebuild` works for you. thanks!
