### ISSUE TITLE
Generate .apk and .ipa files

### ISSUE THREAD

**Issue by clementino36** [expo/expo#224]
I'm trying to generate a .ipa and a .apk file for my app. I successfully built the app and was able to get it to run on both an iOS & an Android device thanks to the docs.
When the build is over, my console shows something like

> Your URL is https://exp.host/@myname/myapp

I then open `exp.host/@myname/myapp` on my device and the app shows up via the Expo client.

But at point 4 of the docs, it is said that

> When it’s done, you’ll see the url of a .apk (Android) or .ipa (iOS) file — this is your app.

I'm a bit confused. No where in the process do I see any ipa or apk file generated anywhere on my computer. Am I missing something ? How do I actually generate the files ?

**Comment by clementino36** [comment]
I figured it out and in my opinion the docs aren't clear enough about this. 

> This will take a few minutes, you can check up on it by running exp build:status

For me, `exp build:status` was only there to monitor your build's status, but when the build is over, this is the command that actually shows you the url where you can download the apk or ipa. So it is mandatory to use `exp build:status`, which is not clear at all in the docs.

**Comment by terribleben** [comment]
Thanks for the feedback! Feel free to submit a PR to the docs if you think the wording could be clearer. We will probably be updating this soon either way as we make planned improvements to the build service.

**Comment by MichaelDimmitt** [comment]
@terribleben, I wrote a bash script to automatically download an updated apk or ipa.
Curious to hear if this is useful. 

1) It gets the last value from the output of expo build:android
2) Then it finds the correct url using curl on the redirect url.
3) Finally it downloads the apk file again using curl.

I run the same commands using expo build:ios to generate the ipa file.

**Comment by MichaelDimmitt** [comment]
An alternative bash install script:
This one would also be easy to create.

1) expo build:android;
2) expo build:ios;
3) expo status | (Get most recent apk and ipa files and download them)
