### ISSUE TITLE
Newer iPhones zoom in too much

### ISSUE THREAD

**Issue by lorissikora** [expo/expo#22402]
### Minimal reproducible example

https://snack.expo.dev/@lorissikora/camera-zoom-demo

### Summary

Hi!

I'm experiencing some inconsistencies with the `zoom` value of the `expo-camera` module regarding newer iPhones. I tested it on two devices. An iPhone XS Max which has a reasonable response to the zoom value and a newer iPhone 12 which seems to have non-linear 10x zoom.

iPhone XS max
![xs](https://user-images.githubusercontent.com/17150659/236615456-015a51f0-da15-4f07-8c8d-876ab26be44c.gif)

iPhone 12
![12](https://user-images.githubusercontent.com/17150659/236615455-b6b8ca8f-0990-4546-b6d0-0ac98d040c38.gif)

From what I can tell, this issue only occurs on newer iPhones, which are built with the newer wide-angle lenses.

I have found a similar issue being discussed [over here](https://github.com/react-native-camera/react-native-camera/issues/1772) with a proposed solution of exposing a `maxZoom` value corresponding to the IOS value `videoMaxZoomFactor`, in order to be able to have some control over the actual zoom factor. Sadly, nothing ever came of it.

Does someone know, how I could achieve a somewhat consistent zoom across multiple devices and, should it not be possible with the current state of the library, how one could maybe implement something similar to described above?

### Environment

```
expo-env-info 1.0.5 environment info:
  System:
    OS: Linux 5.15 Manjaro Linux
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/bin/node
    Yarn: 1.22.19 - ~/.git-projects/catag/app/node_modules/.bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  SDKs:
    Android SDK:
      API Levels: 32, 33
      Build Tools: 30.0.3, 33.0.2, 34.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
  npmPackages:
    expo: ^48.0.9 => 48.0.9 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-web: ~0.18.10 => 0.18.12 
  Expo Workflow: managed
```

**Comment by QuentinGrange** [comment]
Hy did you find any solutions ?

I did this ternary: 
```
const MAX_ZOOM =
  Platform.OS === "ios"
    ? ["12", "13", "14", "15", "16", "17", "18"].find((n) =>
        Device.modelName.includes(n),
      )
      ? 0.03
      : 1
    : 1;
  ```
  But that's really ugly

**Comment by ishanAhuja** [comment]
Still an issue. Any mitigations other than @QuentinGrange's hardcoded MAX_ZOOM approach?
