### ISSUE TITLE
Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project.

### ISSUE THREAD

**Issue by givik** [expo/expo#22400]
### Summary
```
(base) ➜  StickerSmash git:(main) npx expo install react-dom react-native-web @expo/webpack-config
Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project.
FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: getaddrinfo ENOTFOUND api.expo.dev
FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: getaddrinfo ENOTFOUND api.expo.dev
    at ClientRequest.<anonymous> (/Applications/MAMP/htdocs/testdir/StickerSmash/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.6 - /usr/local/bin/npm
      Watchman: 2023.05.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
    npmGlobalPackages:
      eas-cli: 3.10.2
    Expo Workflow: managed

### Minimal reproducible example

npx expo install react-dom react-native-web @expo/webpack-config

**Comment by goutham03062001** [comment]
did you resolve this error?

**Comment by givik** [comment]
> did you resolve this error?

Yes. I don't know why it's happening. sometimes I need VPN (I use free urban vpn) to resolve the issue.

I have contacted my internet provider to check but they said that expo services are NOT blacklisted. so 🤷🏻‍♂️
