### ISSUE TITLE
yarn next-expo doesnt work

### ISSUE THREAD

**Issue by qalqi** [expo/expo#22403]
### Summary

1. Create a new expo project using 
`npx create-expo-app rnwithnext`
2. Follow the steps as per https://docs.expo.dev/guides/using-nextjs/#add-nextjs-to-expo-projects
`yarn next-expo` doesnt work for @expo/next-adapter ^5.0.2

### What platform(s) does this occur on?

Web

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.4
      expo: ~48.0.15 => 48.0.15
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.7
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: bare

### Minimal reproducible example

1. Create a new expo project using 
`npx create-expo-app rnwithnext`
2. Follow the steps as per https://docs.expo.dev/guides/using-nextjs/#add-nextjs-to-expo-projects
`yarn next-expo` doesnt work

**Comment by pavelbabenko** [comment]
Same issue
