### ISSUE TITLE
Error when saving screenshot to media library: "Missing MEDIA_LIBRARY write permission"

### ISSUE THREAD

**Issue by NyoriK** [expo/expo#22421]
### Minimal reproducible example

https://snack.expo.dev/@amanhimself/complete-expo-tutorial-example

### Summary

I have been following the tutorial "Create a universal Android, iOS, and web app" and encountered an error when trying to save a screenshot to the device's media library. The error message I received is:

Error: "Missing MEDIA_LIBRARY write permission."

### Steps to Reproduce:

1. Followed the tutorial "Create a universal Android, iOS, and web app" until the "Take screenshot" chapter.
2. Implemented the code exactly as provided in the tutorial.
3. Tested the app on my Android device.

### Expected Behavior:
The screenshot should be successfully saved to the device's media library without any errors.

### Actual Behavior:
When attempting to save the screenshot, the app throws an error stating that the "Missing MEDIA_LIBRARY write permission." is missing.

### Additional Information:

- I have confirmed that the necessary libraries, react-native-view-shot and expo-media-library, are properly installed in my Expo project.
- Despite granting the permission, the error persists, and I'm unable to save the screenshot to the media library.

Furthermore, I have tested the provided official Snack mentioned in the tutorial, and it also exhibits the same error on my device. It is worth noting that when I open the app on Android inside the Snack website, it works without any issues.

Please let me know if any additional information is required. I would appreciate any assistance in resolving this issue. Thank you!

### Environment

Environment:

Device: Redmi note 10 pro
Expo SDK version: 46.0.21
expo-media-library version: 14.2.0
react-native-view-shot version: 3.3.0
Platform: Android 13

**Comment by emmbyiringiro** [comment]
Before the app attempt to write to the media library. Check  whether write permission granted or request it - https://docs.expo.dev/versions/latest/sdk/media-library/#medialibraryrequestpermissionsasyncwriteonly

**Comment by Joshandrews43** [comment]
On android we have hundreds of users telling us (and easily reproducible) that audio permission `READ_MEDIA_AUDIO` is required so save photos, which it should not be.

**Comment by emmbyiringiro** [comment]
@Joshandrews43  Google recently released Android 13 which has new file access permission behavior. This new permission model should cause some conflicts - https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by guotingchao** [comment]
This problem has not been solved

**Comment by luciatugui** [comment]
I can confirm it has not been solved, partially. I encountered this issue on android 12 and below. I request the permissions, i see that the status is `granted`, but when calling `MediaLibrary.saveToLibraryAsync`, it fails with the mentioned error.

**Comment by Aximem** [comment]
Issue confirmed on Android 12.   
Had to switch to [react-native-cameraroll](https://github.com/react-native-cameraroll/react-native-cameraroll) and [CameraRoll.save(...)](https://github.com/react-native-cameraroll/react-native-cameraroll?tab=readme-ov-file#save)
