### ISSUE TITLE
expo-media-library: Saving always throws error on SDK 33

### ISSUE THREAD

**Issue by JonnyBurger** [expo/expo#22429]
### Minimal reproducible example

```ts
import {saveToLibraryAsync} from 'expo-media-library';
await saveToLibraryAsync("");
```

### Summary

Platform: Android SDK 33

On SDK 33, saving to library using `expo-media-library` fails because `hasWritePermissions` is hardcoded to `false`.  
`saveToLibraryAsync` calls `hasWritePermissions` through `throwUnlessPermissionsGranted`.

As discussed with @alanjhughes here: https://github.com/expo/expo/pull/20907/files/a961ebb16f596865253ec0514beba5de2fe23247#r1188611508
It should not be able to happen at all on Android SDK33, so a possible fix could be to switch it to `true`.

The error message says `android.permission.MEDIA_LIBRARY` is missing, which is not the case, the error message could be improved as well.

### Environment

Android SDK 33, rest should not be relevant

**Comment by alanjhughes** [comment]
Hey @JonnyBurger  - just having some trouble reproducing this. Did you use `MediaLibrary.requestPermissionsAsync` before calling `MediaLibrary.saveToLibraryAsync`?

**Comment by JonnyBurger** [comment]
@alanjhughes I did yeah! Selected "always". Also selected "Resizeable" emulator.

Unfortunately cannot help more right now:(

**Comment by alanjhughes** [comment]
@JonnyBurger no problem! Tried it on emulators from SDK 30 to 33 but not seeing it. I'll keep looking at it 👍

**Comment by JonnyBurger** [comment]
Oh okay, hope I did not report a false positive!
If you are at the conference, we can also debug it together during a break if you have time!

**Comment by firasrg** [comment]
Hey Guys! Currently im using **EXPO SDK 47** and inside one of my modal views (full screen), im launching the Camera as another modal view, and use `expo-media-library` to access images (Galery). I need permissions to do that. The **probleme is**: When I run the app, and get into the camera the app stops working.

This is the code in my Camera component 
```tsx
  useEffect(() => {
    MediaLibrary.requestPermissionsAsync()
      .then(() => Camera.requestCameraPermissionsAsync())
      .then((cameraPermissionStatus) =>
        setCameraPermissionState(cameraPermissionStatus.status === "granted" ? CameraPermission.granted : CameraPermission.denied)
      ).catch(() => setCameraPermissionState(CameraPermission.denied))

    return () => {
      dispatch(setImagePickResult(undefined));
    }
  }, []);
```

My question is : Do you think that it's related to the issue mentioned in here please ? thanks
