### ISSUE TITLE
expo-doctor has a outdated dependency which causes EAS build to fail

### ISSUE THREAD

**Issue by Albert-Gao** [expo/expo#22422]
### Summary

EAS build is failing because of expo-doctor is failed.

Running `expo-doctor@1.0.6` alone gives the following error:
![image](https://user-images.githubusercontent.com/18282328/236910194-ed3648d0-bcba-48f1-8246-bfa792ab08d6.png)

It is because it has a dependency of `@expo/config` which is version is `6.0.24`, but the latest version is `8.0.3`

### SDK Version

48.0.16

### Environment

```bash
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 3.5.0 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.6.6 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/albertgao/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.12.0
      expo-cli: 6.3.7
    Expo Workflow: managed
```

### Minimal reproducible example

This is the dependency of expo-doctor's package.json

https://github.com/expo/expo-cli/blob/fcc2262467209a87f4b72ae1e350535923148121/packages/expo-doctor/package.json#L37

It was recently released by  @tsapeta 
If it is just as easy as update the version number, would be happy to send a PR 😄

**Comment by stoickeyboard** [comment]
Downgrading to 48.0.15 from 48.0.16 fixed this dependency issue

**Comment by Albert-Gao** [comment]
Fixed this issue by adding a resolution to pin the expo config version to v6. (I am using yarn workspace)

**Comment by Kudo** [comment]
hi there! may i double check whether this issue still happen to you (without yarn resolution)? if yes, please help to check the output `yarn why @expo/config-plugins` locally. thanks!

**Comment by Thodor12** [comment]
I had the same issue, for me it was saying
```
✖ Verifying prebuild support package versions are compatible failed
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@4.1.5
    (for more info, run: npm why @expo/config-plugins)
```

Output of `npm ls @expo/config-plugins` showed
```
├─┬ @expo/config@8.0.2
│ └── @expo/config-plugins@6.0.1 deduped
├─┬ expo-doctor@1.0.6
│ └─┬ @expo/config@6.0.24
│   └── @expo/config-plugins@4.1.5
├─┬ expo-splash-screen@0.18.2
│ └─┬ @expo/prebuild-config@6.0.1
│   └── @expo/config-plugins@6.0.1 deduped
├─┬ expo@48.0.17
│ ├─┬ @expo/cli@0.7.1
│ │ └── @expo/config-plugins@6.0.1 deduped
│ └── @expo/config-plugins@6.0.2
└─┬ sentry-expo@6.1.1
  └─┬ expo-updates@0.16.4
    └── @expo/config-plugins@6.0.1 deduped
```

For NPM I was able to fix it by adding
```json
  "overrides": {
    "expo-doctor": {
      "@expo/config": "8.0.0"
    }
  }
```
to the package.json

**Comment by Kudo** [comment]
@Thodor12 do you have `expo-doctor` as dependencies or devDependencies in your package.json? if so, please try to remove it from the package.json. you could just use `npx expo-doctor@latest` as a standalone tool without adding it as dependencies.

**Comment by Thodor12** [comment]
I removed it from the devDependencies, ran npm install and then ran it through `npx` and it looks like it works.
So let's assume that's the proper fix then.

**Comment by TomasSestak** [comment]
im having the same issue
