### ISSUE TITLE
8.0.4 @expo/config depends on SDK 49 @expo/config-types and @expo/config-plugins@7.0.0

### ISSUE THREAD

**Issue by stoickeyboard** [expo/expo#22425]
### Minimal reproducible example

https://github.com/expo/expo/blob/main/packages/%40expo/config/package.json

### Summary

I'm having troubles building as I keep getting an error stating 
`
cannot find protocol declaration for 'EXUpdatesExternalInterface'; did you mean 'EXUpdatesModuleInterface'?
`

expo doctor states `
 Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@7.0.0
` 
and it looks like `@expo/config` is what has `@expo/config-plugins@7.0.0` as a dependency. Seeing that `@expo/config` also has `@expo/config-types@^49.0.0-alpha.1` as a dependency, I assume these dependencies were pushed as a mistake?

Is there a way to change expo packages to depend on `@expo/config@8.0.2` instead of `@expo/config@~8.0.0` in the meantime?

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 3.3.1 - ~/Library/pnpm/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    Expo Workflow: managed

**Comment by chrisdrackett** [comment]
why is this closed? seems like 48.0.16 is still broken?

**Comment by chrisdrackett** [comment]
I needed to add the following to my resolutions to get things running again:

```
    "@expo/config-plugins": "6.0.1",
    "expo-updates-interface": "0.9.1",
```

**Comment by Kudo** [comment]
hi there! could you please share the output of these commands?

```sh
$ yarn why expo-updates-interface
$ yarn why @expo/config-plugins
```

**Comment by enisze** [comment]
@Kudo :
<img width="795" alt="image" src="https://github.com/expo/expo/assets/15271433/86d5cefe-c1a0-4d3e-afb8-c6243138621a">
<img width="795" alt="image" src="https://github.com/expo/expo/assets/15271433/c1e6304b-15d7-4332-98a2-181c5600414d">
After adding the resolution I get this:
<img width="795" alt="image" src="https://github.com/expo/expo/assets/15271433/81ab0539-91ff-4917-8000-675f35e8890f">
