### ISSUE TITLE
[expo-image] [Android] (1) nested flashlist with expo-image crashes and (2) placeholder not exchanges

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#22438]
### Minimal reproducible example

https://github.com/RRaideRR/expo-image-blurhash

### Summary

Not quite sure if I've done something wrong with my Flashlist implementation here. Right now, I suspect that `expo-image `is not freeing up its memory somewhere. Why do I think that? When I exchange `expo-image` Image with RN-Image its working fine (its a little bit laggy then, but reliable laggy and the lagginess is not increasing)

With more and more time passing, and more and more scrolling taking place, the performance tend to decrease heavily. It will result in a crash over some time.

Also notice second 23 up to second 30 in the attached video, because there two placeholders that will not be exchanged with the actual image.

Tested on a Moto G8 power with Android 11.
Video: https://github.com/expo/expo/assets/3411292/971290eb-7f1f-4313-8f5e-000c326d7f50

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
    npmGlobalPackages:
      eas-cli: 3.12.0
      expo-cli: 6.3.7
    Expo Workflow: bare

**Comment by jaibheeman** [comment]
I have the same issue :(

**Comment by fdaugs** [comment]
Same problem over here 👀

**Comment by sperrys** [comment]
FWIW also running into this

**Comment by lukmccall** [comment]
The problem with memory leaks should be resolved in the newest version, `[1.5.1](https://www.npmjs.com/package/expo-image/v/1.5.1)`. Please try that :D

**Comment by RRaideRR** [comment]
Yes it is solved with this fix :-). Plus, I believe the issue with the problem with the [placeholders was fixed with your help as well](https://github.com/expo/expo/pull/23705). So happy to close this issue.
