### ISSUE TITLE
onBarCodeRead method for Camera component crashing Expo app

### ISSUE THREAD

**Issue by kspierson** [expo/expo#2243]
After updating to Expo SDK v30, the `onBarCodeRead` method in the Camera component causes the Expo app to crash. Using the BarCodeScanner component in place of the Camera component does not cause the Expo app to crash.
  
### Environment

```
Environment:
  OS: Windows 10
  Node: 10.8.0
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
```

Current target is Android using the Expo client app, with plans for a standalone build.

### Expected Behavior

Camera component loads correctly; Expo app does not crash.

### Actual Behavior

Expo app crashes upon rendering Camera component. Note that, in the reproducible demo, the Expo app crashes on first run (on Android device) and subsequent runs reload immediately after rendering.

### Reproducible Demo

Below are two examples of the current behavior; the only difference between the two examples is the component used (Camera/BarCodeScanner):
- [Reproducible demo using Camera component (broken)](https://snack.expo.io/@epxdev/onbarcodescanned-broken-example)
- [Reproducible demo using BarCodeScanner component (working)](https://snack.expo.io/@epxdev/onbarcodescanned-working-example)

**Comment by kspierson** [comment]
I was able to use the Camera component with onBarCodeRead/Scanned; I believe there was a configuration problem with my device. Closing until problem resurfaces.

**Comment by paulenokels** [comment]
Hello @kspierson , I am having this exact same issue, how did you resolve it? what configuration problem did your device have?

**Comment by kspierson** [comment]
The problem resolved itself strangely enough; I was working over a VPN and
think that might have contributed to the issue, but I never investigated
further.

**Comment by Amirjab21** [comment]
I have this issue as well. It seems to me that the Camera component can crash if props change while it is being mounted/unmounted.
