### ISSUE TITLE
Building project giving Error "Cannot find type 'Enumerable' in scope" #22440

### ISSUE THREAD

**Issue by ayazalavi** [expo/expo#22441]
### Minimal reproducible example

build command failing

### Summary

Followed installation instruction in xcode 14.3, and with following in package.json:
"expo": "^45.0.0",
 "expo-image": "^1.2.2",
Getting followin error while tryign to build project

<img width="379" alt="Screenshot 2023-05-10 at 5 01 03 PM" src="https://github.com/expo/expo/assets/767439/63a05bb3-6704-4693-b298-bcedcd10ff95">

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2022.06.27.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-native: 0.65.1 => 0.65.1 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 6.3.7
    Expo Workflow: bare

**Comment by brentvatne** [comment]
you are attempting to use expo-image with sdk 45. it is supported in sdk 48+
