### ISSUE TITLE
Background Location Updates and Foreground Service Notification not working as expected on Android

### ISSUE THREAD

**Issue by rei-shaholli** [expo/expo#22445]
### Minimal reproducible example

https://snack.expo.dev/n2kWxz9zkx

### Summary

I am working on a React Native application that requires tracking the user's location in the background. To implement this feature, I am using the expo-location package. I followed the Expo documentation to set up the background location updates and the foreground service notification for Android.

While the background location updates seem to work correctly when the app is in the foreground, I have noticed that the updates stop when the app is sent to the background. This behavior contradicts the purpose of background location updates.

Additionally, even though I have set up the foreground service in the Location.startLocationUpdatesAsync call as per the documentation, the expected notification is not being generated when the app is in the foreground.

Here is the code snippet from my application where I set up the background location updates and the foreground service:

```typescript
const startLocationTracking = async () => {
    await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.Highest,
        timeInterval: 1000,
        distanceInterval: 0,
        showsBackgroundLocationIndicator: true,
        foregroundService: {
            notificationTitle: "Location Tracking",
            notificationBody: "Tracking your location for routing purposes",
            notificationColor: "#FF0000",
        },
        pausesUpdatesAutomatically: false,
        deferredUpdatesInterval: 1000,
        deferredUpdatesDistance: 0,
        deferredUpdatesTimeout: 1000,
    });
};
```
And here are the relevant permissions I have set in my app.json:
```json
"android": {
  "permissions": ["ACCESS_COARSE_LOCATION", "ACCESS_FINE_LOCATION", "ACCESS_BACKGROUND_LOCATION", "FOREGROUND_SERVICE"],
  "useNextNotificationsApi": true
}
```
My understanding is that in android you need to start a "foreground service" in order to get "background location tracking" to work. Or rather to track location when the user navigates away from the app.  I would assume that this is what the following does, but I'm not seeing this behavior. 
```typescript
foregroundService: {
      notificationTitle: 'Office marathon is active',
      notificationBody: 'Monitoring your location to measure total distance',
      notificationColor: '#333333',
    },
``` 

Am I missing something?

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      expo: ~48.0.15 => 48.0.16
      react: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.7
    Expo Workflow: managed

**Comment by sahadnk72** [comment]
I'm also experiencing the same problem.

**Comment by sahadnk72** [comment]
Looks like we need to ask the permission separately. Doing the following sorted the issue for me.

`import * as Notifications from 'expo-notifications';`

In useEffect():

```
let resn = await Notifications.requestPermissionsAsync();
if (resn.status != 'granted') {
  //handle it
      } else {
        console.log('Notifications granted');
      }
```
Restart Metro & rebuild

**Comment by rei-shaholli** [comment]
Anyone?

**Comment by rei-shaholli** [comment]
So I found that this doesn't work when you are using background location tracking in development mode using Expo Go.  It works if you build an APK and install it on your device! Phew!

**Comment by premdasvm** [comment]
@rei-shaholli Is the location data you getting correct? I tried using `expo-location` and my phone was idle on the desk, still the locations i got was meters apart 🫡

**Comment by AlexMachin1997** [comment]
Hey @rei-shaholli , you don't happen to have a full example of this working do you ? Would be great to learn how I can achieve background tracking. I haven't been able to find a full example yet.

**Comment by rei-shaholli** [comment]
@AlexMachin1997, you can use this example to build a standalone APK to test it out.

https://github.com/byCedric/office-marathon.

@premdasvm I haven't had the chance to check the correctness of the location data yet, but I'd assume if you add the following to the `LocationTaskOptions` you'd be good:

`accuracy: Location.Accuracy.BestForNavigation`

**Comment by premdasvm** [comment]
@rei-shaholli , i use the exact same parameters for `accuracy`. i was also poking around [https://github.com/byCedric/office-marathon.](url). it showed wrong coordinates also. you can see the screenshot here

[https://github.com/byCedric/office-marathon/issues/21#issue-1721152659](url)

**Comment by AaronH2001** [comment]
Hi all, I have the same problem, however when I build and run the apk the notification is still not displayed.
Did you use "await Notifications.requestPermissionsAsync();"? My code at this point looks like this:

```
if (this.backgroundStatus == 'granted') {
            await Location.startLocationUpdatesAsync(taskName, {
                accuracy: Location.Accuracy.BestForNavigation,              
                timeInterval: backgroundTaskTimeIntervall.executeTask, 
                activityType: Location.ActivityType.AutomotiveNavigation, //AutomotiveNavigation,
                showsBackgroundLocationIndicator: true,
                foregroundService: {
                    notificationTitle: "App is running",
                    notificationBody: "Location tracking",
                },
            });
        }
```

Can someone help me. I am a bit desperate

**Comment by rei-shaholli** [comment]
Look at this example:

https://github.com/byCedric/office-marathon

If you follow what they are doing AND build the apk (do not use the expo go app), the location should be coming in the background.  I still haven't checked the validity of the background location updates, though.

**Comment by AaronH2001** [comment]
Hi @rei-shaholli, hhank you for your answer. Does the notification that the app receives the position also work in this example?

With my app, the background location works, but when you put the tablet on standby, it still works for about an hour and then only sends at strangely long intervals. But I don't get a notification that the position is being received in the background either.
Is that because of the "FOREGROUND_SERVICE"?

Best regards
Aaron

**Comment by rei-shaholli** [comment]
@AaronH2001 , yes the way background location is "received" in Android is via a Foreground service that runs when the app is put in the background (or even killed).  This is done via a pinned notification.  The example office-marathon does this.  so when build the apk (again not via the expo-go app) and install and run it on your android device, you should see a notification pop up (signifying the foreground service is up) and the location should be collected.

**Comment by AaronH2001** [comment]
@rei-shaholli Okay I created the app (not via expo-go) and launched it. Unfortunately, I don't get the notification but the location is recorded. Do you have any idea what the problem is? Could it be my tablet and if so, do you know what I can do about it?

**Comment by rei-shaholli** [comment]
@AaronH2001 I also added the following permissions to the app.json file

```javascript
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "FOREGROUND_SERVICE"
      ]
``` 

also had to install `expo-notifications` and ask for permissions via something like this:

```typescript
  const [notifPermission, askNotifPermission] = usePermissions();
```

that returns a "permission" status object (to check if permissions have been granted) and an "askNotifPermission" method that you can bind to a button to ask for notification permissions.

**Comment by rei-shaholli** [comment]
> @rei-shaholli , i use the exact same parameters for `accuracy`. i was also poking around [https://github.com/byCedric/office-marathon.](url). it showed wrong coordinates also. you can see the screenshot here
> 
> [https://github.com/byCedric/office-marathon/issues/21#issue-1721152659](url)

it is working perfectly for me @premdasvm .

**Comment by pbarros09** [comment]
This problem is still happening to me. What's strange is that my background service is working in the background, but it seems that the coordinates are sometimes captured and sometimes not. I've tested exporting an APK and an IPA and using them on two real devices (iPhone and Android Motorola g30). The iPhone is working correctly and the Android seems to have a problem tracking the user.

ANDROID TRACKING:
![ANDROID](https://github.com/expo/expo/assets/135664941/1eebac72-17f4-4210-95cb-df744fb1ed90)

IPHONE TRACKING:
![IOS](https://github.com/expo/expo/assets/135664941/4b995d50-9c29-4bef-b965-6c4c78a1f9ef)


DIFFERENCE IN KILOMETERS USING BOTH DEVICES TOGETHER IN THE SAME TIME:
![WhatsApp Image 2023-09-06 at 22 21 00](https://github.com/expo/expo/assets/135664941/956f56e4-d908-42d1-9fed-4f31795ee389)


As you can see, using Android the app captures 1.66 km and iPhone 4.41 km. Both use the same code base.

**Comment by angelilton** [comment]
> This problem is still happening to me. What's strange is that my background service is working in the background, but it seems that the coordinates are sometimes captured and sometimes not. I've tested exporting an APK and an IPA and using them on two real devices (iPhone and Android Motorola g30). The iPhone is working correctly and the Android seems to have a problem tracking the user.
> 
> I'm starting the service such as:
> 
> ```
> await Location.startLocationUpdatesAsync(LOCATION_TASK, {
>     accuracy: Location.Accuracy.BestForNavigation,
>     timeInterval: 2000,
>     // android behavior
>     foregroundService: {
>       notificationTitle: "CatiRun está ativo",
>       notificationBody: "O aplicativo está usando sua localização em segundo plano para medir a distância percorrida.",
>     },
>     // ios behavior
>     showsBackgroundLocationIndicator: false,
> });
> ```
> 
> ANDROID TRACKING: ![ANDROID](https://user-images.githubusercontent.com/135664941/266176445-1eebac72-17f4-4210-95cb-df744fb1ed90.jpeg)
> 
> IPHONE TRACKING: ![IOS](https://user-images.githubusercontent.com/135664941/266176507-4b995d50-9c29-4bef-b965-6c4c78a1f9ef.jpeg)
> 
> DIFFERENCE IN KILOMETERS USING BOTH DEVICES TOGETHER IN THE SAME TIME: ![WhatsApp Image 2023-09-06 at 22 21 00](https://user-images.githubusercontent.com/135664941/266176583-956f56e4-d908-42d1-9fed-4f31795ee389.jpeg)
> 
> As you can see, using Android the app captures 1.66 km and iPhone 4.41 km. Both use the same code base.
> 
> Does anyone have anything to explain by any chance?

on android you need to sun the all time the task is start like set 1km and you will know the user walk 1km you neeed just kmWalk ++

**Comment by pencilcheck** [comment]
I use notifee as the foreground service and notification, and use expo location only for extracting location and it seems to work a lot better

**Comment by Nxtra** [comment]
> I use notifee as the foreground service and notification, and use expo location only for extracting location and it seems to work a lot better

Does that work on android? I was assuming the foreground notification is actually used to keep the location updates active even when the app is in the background or closed. But when you use notifee, how do you make sure this still happens?

**Comment by filipef101** [comment]
@Nxtra Did you understood?
I think what @pencilcheck is saying is that if you enable the foreground notification for the location service with notifee, that the handler of expo-location will actually receive the events, meaning you can use it to enable the location foreground service, instead enabling the foreground service with expo. It even supports requesting to disable batter optimizations. This is all a bit obscure, but in theory should work.

**Comment by Raiden-16F7** [comment]
> @rei-shaholli Is the location data you getting correct? I tried using `expo-location` and my phone was idle on the desk, still the locations i got was meters apart 🫡

Hey man, im also facing a similar issue where if my phone is stationary then it keeps on returning the same data over and over, even the timestamp remains same, did you also face a similar issue?
