### ISSUE TITLE
 Image source with uri prop not working with expo-image

### ISSUE THREAD

**Issue by fabricioferiozzi96** [expo/expo#22447]
### Summary

Using React Native Image with the 'uri:' prop the image is displayed, but using Image from expo-image it is not displayed
Using require works fine

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^48.0.0 => 48.0.9
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.7
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: managed

### Minimal reproducible example

<Image source={{ uri: `$uriexample` }}
            style={{
              ....            }} />

**Comment by alanjhughes** [comment]
@fabricioferiozzi96  - Can you provide an example URI that is not working?

**Comment by fabricioferiozzi96** [comment]
<Image source={{ uri: ${getEnvVars().API_URL}/files/${getEnvVars().USER_FOLDER}/${user.image} }}

**Comment by fabricioferiozzi96** [comment]
<Image source={{ uri: `${getEnvVars().API_DOMAIN}/files/${getEnvVars().USER_FOLDER}/${user.imagen}` }}
