### ISSUE TITLE
[docs] Firebase SDK Authentication with AsyncStorage

### ISSUE THREAD

**Issue by nathanaelphilip** [expo/expo#22446]
### Summary

The firebase example is really nice, but I feel like it’s missing an important step:

```
import {
  connectAuthEmulator,
  getAuth,
  getReactNativePersistence,
  initializeAuth,
} from 'firebase/auth/react-native';

let app;
let auth;

if (!getApps().length) {
  try {
    app = initializeApp(firebaseConfig);
    auth = initializeAuth(app, {
      persistence: getReactNativePersistence(AsyncStorage),
    });
  } catch (error) {
    console.log('Error initializing app: ' + error);
  }
} else {
  app = getApp();
  auth = getAuth(app);
}

export { auth };
```

It would be nice to show how to properly set up persistence with AsyncStorage and how to make sure the app isn’t initialized more than once. The firebase docs don’t do a great job of explaining it, so it may be useful to users to have this handy.

### Link to the related docs page

https://docs.expo.dev/guides/using-firebase/#using-firebase-js-sdk

**Comment by amandeepmittal** [comment]
Hey @nathanaelphilip, we cover details about persistence in [this guide](https://github.com/expo/fyi/blob/main/firebase-js-auth-setup.md) with examples. We've also linked this guide from the main Firebase doc.

**Comment by wailay** [comment]
Hey @amandeepmittal , in the guide you've linked, `getReactNativePersistence` is imported from `import { initializeAuth, getReactNativePersistence } from "firebase/auth". But I am getting `Module '"firebase/auth"' has no exported member 'getReactNativePersistence'`.
Using firebase version 10

**Comment by amandeepmittal** [comment]
Hey @wailay, Firebase JS SDK recently introduced this breaking change for React Native (from v10.3.0) as [discussed here](https://github.com/expo/fyi/issues/127). We've also updated the [FYI guide](https://github.com/expo/fyi/blob/main/firebase-js-auth-setup.md) and included a new section about v10 based on [Firebase's latest release notes](https://firebase.google.com/support/release-notes/js#authentication).

For the error you mentioned, it seems their docs do mention the function [here](https://firebase.google.com/docs/reference/js/auth.md#getreactnativepersistence) so I'm not sure what's going on there. I'd suggest opening that issue in the Firebase JS repo as they might be able to provide most up to date info or expert suggestions.

**Comment by wailay** [comment]
Thanks @amandeepmittal, an issue has already been opened about this 
For reference: https://github.com/firebase/firebase-js-sdk/issues/7584
