### ISSUE TITLE
from v29 to v30 - AppRegistry is not registered callable

### ISSUE THREAD

**Issue by davidgithub1980** [expo/expo#2245]
Hi, I just switched my app from:

"expo": "^29.0.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz"

to:

"expo": "^30.0.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"

but the following error occurs:

![image](https://user-images.githubusercontent.com/6930312/45921058-6dc4c880-beae-11e8-9c26-355038c07f0c.png)

Can you help reveal what got corrupted by switching from **v29** to **v30**?

package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "axios": "^0.18.0",
    "expo": "^30.0.0",
    "mobx": "^4.4.2",
    "mobx-react": "^5.2.8",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-native-animate-number": "^0.1.2",
    "react-native-size-matters": "^0.1.3",
    "react-native-svg": "^7.0.3",
    "react-native-timeline-listview": "^0.2.3",
    "react-navigation": "^2.13.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-env": "^2.4.1",
    "babel-jest": "^23.6.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "jest": "^23.6.0",
    "react-test-renderer": "^16.5.2"
  },
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules"
    ]
  }
}
```

app.json

```
{
  "expo": {
    "name": "Numbers",
    "description": "...",
    "slug": "numbers",
    "privacy": "public",
    "sdkVersion": "30.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "..."
    },
    "android": {
      "package": "..."
    }
  }
}
```

Judging from the nature of the error, it appears that something from the Expo-Lottie internals was not upgrade-ready.

**Comment by esamelson** [comment]
Hi @davidgithub1980 - could you share some code (a [snack](https://snack.expo.io) would be ideal) that reproduces this error? Is this a normal standalone app, or is it detached?

**Comment by davidgithub1980** [comment]
Hi. It is a normal standalone app. The full error trace is:

![screenshot_20180926-221126](https://user-images.githubusercontent.com/6930312/46107439-ada3ec80-c1db-11e8-8289-62f49647d6f8.png)

![screenshot_20180926-221131](https://user-images.githubusercontent.com/6930312/46107467-bbf20880-c1db-11e8-9308-d81ba597b48e.png)

The repo:
https://bitbucket.org/davidzaba/numbers-game/src/master/

**Comment by davidgithub1980** [comment]
After some debugging, I found out the following:

```
import { DangerZone } from 'expo';
const { Lottie } = DangerZone
```

The code above is the same as in the Expo docs: _https://docs.expo.io/versions/latest/sdk/lottie_. The code causing the error is _**const { Lottie } = DangerZone**_. The error is gone if I remove this line, but without this line, I cannot use Lotties at all. Is it not a bug? Things were working correctly with v29.

**Comment by davidgithub1980** [comment]
> Hi @davidgithub1980 - could you share some code (a [snack](https://snack.expo.io) would be ideal) that reproduces this error? Is this a normal standalone app, or is it detached?



> Hi @davidgithub1980 - could you share some code (a [snack](https://snack.expo.io) would be ideal) that reproduces this error? Is this a normal standalone app, or is it detached?

Hi @esamelson I attached a link to the repo. Could you try to debug? Unfortunately, both the Android standalone app and the iOS standalone app ceased to work after the upgrade (following the upgrade instructions in the latest Exposition blog report - https://blog.expo.io/expo-sdk-30-0-0-is-now-available-e64d8b1db2a7).

**Comment by N1ghtly** [comment]
We are running into this issue as well. Standalone builds get this error everytime.

**Comment by davidgithub1980** [comment]
> We are running into this issue as well. Standalone builds get this error everytime.

Did you succeed to debug the root of the error? I have failed so far as it appears to be close to the expo core.

**Comment by N1ghtly** [comment]
> > We are running into this issue as well. Standalone builds get this error everytime.
> 
> Did you succeed to debug the root of the error? I have failed so far as it appears to be close to the expo core.

Unfortunately not. The error disappeared on its own...

**Comment by davidgithub1980** [comment]
Had to _expo init_ a new project, transfer all files in there and everything got back in normal. Migration from v29 turned out to be unsuccessful.
