### ISSUE TITLE
Expo-Image-Picker crop resulting in shifted Image

### ISSUE THREAD

**Issue by cobygoldstein** [expo/expo#22459]
### Summary

I've implemented a simple image picker (copy and pasted from the Expo Image Picker example). I am running into an issue when certain photos (not all) are selected and then dragged around to crop; the resulting image does not match what the user selected in the editing window. This happens more often when the user actually zooms and drags the crop box, but not exclusively. Specifically, it looks like it's shrinking the width as well as shifting the image down. I'll attach some sample images below, as well as a snack (just copy and pasted from [Docs](https://docs.expo.dev/versions/latest/sdk/imagepicker/))

Seems like very odd behavior, and I've tried to track down why this might be happening (image size? formatting with specific images?) and can't seem to come up with any logical reasoning, especially since I can recreate it with the documentation supplied code.

Issue:
edit window:
![IMG_8917](https://github.com/expo/expo/assets/27232494/5cb38f7b-305c-4175-9005-c43c98a17d56)
resulting image (whole plate not visible):
![IMG_8918](https://github.com/expo/expo/assets/27232494/009a678f-55f2-49ff-a790-b2ec8959b9be)

edit window:
![IMG_8921](https://github.com/expo/expo/assets/27232494/00ad81a1-e146-41e6-b904-efabcc494e6b)
the resulting image (shifted dramatically)
![IMG_8922](https://github.com/expo/expo/assets/27232494/62550b95-ee44-47c5-9380-389a2cfd8300)

But that's not to say it doesn't work every time!

Works perfectly normally here:
![IMG_8919](https://github.com/expo/expo/assets/27232494/f76dd22c-85d3-45fc-8080-e4dde139ce2d)
The expected image is displayed
![IMG_8920](https://github.com/expo/expo/assets/27232494/484a5ba4-7c66-4b7a-a4bd-78d4e03b9861)

### What platform(s) does this occur on?

iOS

### SDK Version

48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      npm: 8.19.4 - ~/Documents/DISH/client/node_modules/.bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

https://snack.expo.dev/@cobygoldstein/cfd6a6

```
import React, { useState, useEffect } from 'react';
import { Button, Image, View, Platform } from 'react-native';
import * as ImagePicker from 'expo-image-picker';

export default function ImagePickerExample() {
  const [image, setImage] = useState(null);

  const pickImage = async () => {
    // No permissions request is necessary for launching the image library
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      // aspect: [4, 3], // aspect doesn't work on IOS because its always square.
      quality: 1,
    });

    console.log(result);

    if (!result.canceled) {
      setImage(result.assets[0].uri);
    }
  };

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button title="Pick an image from camera roll" onPress={pickImage} />
      {image && <Image source={{ uri: image }} style={{ width: 200, height: 200 }} />}
    </View>
  );
}
```

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/11611#issuecomment-769475886

**Comment by brentvatne** [comment]
(the effort in your report is appreciated! however this isn't particularly actionable for us due to the bug being in closed source tools built into iOS. the only thing we could do is rewrite that, which we don't plan on doing in the short term)

**Comment by brentvatne** [comment]
cc @amandeepmittal - let's add some documentation about this known issue
