### ISSUE TITLE
error Command "next-expo" not found.

### ISSUE THREAD

**Issue by givik** [expo/expo#22453]
### Summary

Hi. I am following this guide from Expo's documentation, where it says I should run the command "yarn next-expo" after installing the "@expo/next-adapter" package using "yarn add -D @expo/next-adapter".

However, when I try to run the "yarn next-expo" command, I get an error message:
```
error Command "next-expo" not found.
```

### Link to the related docs page

https://docs.expo.dev/guides/using-nextjs/#add-nextjs-to-expo-projects

**Comment by pavelbabenko** [comment]
Same issue

**Comment by brentvatne** [comment]
docs updated to fix in #22488
