### ISSUE TITLE
Stuck on splash screen when downloaded from Testflight

### ISSUE THREAD

**Issue by andyhbg** [expo/expo#2246]
Hi! After upgrading from Expo SDK version from 28 to 30 my app no longer works when I built for production. It works fine via the expo app (both on simulator and on real device) but when I try to run the standalone app (.ipa) that I downloaded off TestFlight it stucks on the splash screen.

I have also tried a brand new app created via expo init and experience the same problem!
  
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B37
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

### Steps to Reproduce
1. expo init
2. expo build:ios
3. Upload to App Store Connect with Application Loader
4. Open the app from Testflight

### Expected Behavior
The app should start

### Actual Behavior
The app is stuck on the splash screen

### Reproducible Demo
Although I do not think it's necessary, there's a [repo](https://github.com/andyhbg/ExpoTestSplash) here with the test app.

### Log file
[ExpoTest.log](https://github.com/expo/expo/files/2408168/ExpoTest.log)

**Comment by andyhbg** [comment]
Can confirm that a downgrade to SDK 29 is a temporary fix!
Ping @esamelson since I consider this to be an important bug to solve.

**Comment by atillasertkaya** [comment]
@andyhbg I faced with same issue last night. It stuck on splash screen. Then I downgraded to SDK 29 temporarily, so it's working for now. 

Are you using the custom font loader during apploading? After SDK 30, expo core libraries such as font, location don't work. In my case, if the font doesn't load, the app will stuck on splash screen. 
See following the screenshot from expo blog, but I am not sure. 

<img width="950" alt="new" src="https://user-images.githubusercontent.com/5853889/45927806-351e0100-bf39-11e8-843d-3af77e5e869e.png">

**Comment by andyhbg** [comment]
@atillasertkaya yes i load custom fonts so it sounds reasonable that the problem may lie there.

**Comment by saundefined** [comment]
I have the same issue, haven't custom fonts.
.ipa file size was ~240 mb and now it's ~90mb

eg. builds 36ecb185-2073-4d90-997e-b99a85e67f19 and 9d3eca11-db46-4af0-bb65-e0b007f81115

**Comment by DavidBadura** [comment]
I have the same issue since SDK30. I have custom fonts.

**Comment by chrisgreg** [comment]
Having the exact same issue.

I downgraded to SDK 29 by changing the value in app.json and I'm getting 'Native Module cannot be null' - is there something else I have to do to downgrade?

**Comment by andyhbg** [comment]
@chrisgreg you need to update your package.json to reflect SDK 29. Then delete your node_modules folder and reinstall the packages. More information here, https://blog.expo.io/expo-sdk-v29-0-0-is-now-available-f001d77fadf

**Comment by Overtorment** [comment]
Same issue for me.
Reported it here: https://forums.expo.io/t/stuck-on-splashscreen-after-updating-to-30/14043/5
Also, someone reported it here: https://forums.expo.io/t/sdk-30-splash-screen-got-frozen-in-standalone-app/14061/2
Also, at least one person (except me) posted this problem on Slack.

**Comment by sebastianekstrom** [comment]
Same issue here, happened over night after a tiny feature pushed to Testflight. I have no custom fonts though.

```Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.9.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
```

Build: 1837c456-ca55-4fdb-83ca-ec03d39770ec

**Comment by kevinsimper** [comment]
Got the same issue on a new app

**Comment by wassgha** [comment]
Same issue.

**Comment by PetrVrba** [comment]
Same issue. Loading custom fonts.

**Comment by brorhb** [comment]
Just spent a couple of hours, trying to figure out why my app would not boot. Trying to downgrade to SDK 29 now. In debugging and comparing the app running with SDK 28 and the update running SDK 30. I discovered using Charles (https://www.charlesproxy.com), that the app using the SDK 30, is missing a request to https://exp.host. Dont know if thats related, just wanted to share my find.

**Comment by ericjames** [comment]
Same.

**Comment by esamelson** [comment]
Hi all - we've just reproduced this and are looking into it now. Not sure how it slipped past the cracks as testing standalone apps is a normal part of our QA process. We'll have a fix out soon. Thanks for the report, and really sorry for the inconvenience!

**Comment by esamelson** [comment]
We've rolled back to a previous version of the iOS builder and it's now producing working SDK 30 apps. Going to keep this issue open for now as we monitor and continue to investigate the root cause. Please let us know if you continue to see issues like this!

**Comment by veedeo** [comment]
Where I can get the latest version?

**Comment by proutek** [comment]
> Where I can get the latest version?

Just start new build?

**Comment by andyhbg** [comment]
Can confirm that it is now working! Thanks @esamelson
