### ISSUE TITLE
[eas build] Asking for keychain password for "turtle-v2"

### ISSUE THREAD

**Issue by richstokes** [expo/expo#22479]
### Summary

Just doing a plain-old `eas build --platform ios --profile production`, which previously was working fine, but now after a few mins it pops up with:

<img width="436" alt="image" src="https://github.com/expo/expo/assets/13403491/dced52a2-e6cf-4992-839a-4b1d69c290c3">

What is the password/why is it requiring one now? Looks like its triggered by Fastlane?

### What platform(s) does this occur on?

iOS

### SDK Version

48.0.15

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.12.0
    Expo Workflow: managed

### Minimal reproducible example

N/A

**Comment by richstokes** [comment]
Figured it out. For some reason I have multiple "turtle-v2" keychains (when looking in MacOS' Keychain Access). I deleted them all and now builds are working. Not sure if this is an Expo thing or a Fastlane thing.

**Comment by wkozyra95** [comment]
turtle-v2 keychain is created when you run a build with `--local` option, it's used to temporally store credentials for that build. Those keychains are removed after the build, but there might be some cases when cleanup failed and those keychains were left there. It's fine to remove them.

Nothing really actionable here without any more info on how you reached a state where keychains where not removed, so I'm closing the issue.

**Comment by nccapo** [comment]
Expo is blood cancer <3
