### ISSUE TITLE
[eas build] Build failed: pod exited with non-zero code: 1

### ISSUE THREAD

**Issue by enchantednougat** [expo/expo#22478]
### Summary

`eas build --profile preview --platform ios`

produces following error: (I thought pods shouldn't be our concern with the usage of EAS)

Using Expo modules
[Expo] Enabling modular headers for pod ExpoModulesCore
Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/expo/.nvm/versions/node/v16.18.1/bin/node
Auto-linking React Native modules for target `appname`: RNAWSCognito, RNCAsyncStorage, RNDateTimePicker, RNGestureHandler, RNReanimated, RNSVG, RNScreens, RNVectorIcons, lottie-ios, lottie-react-native, react-native-netinfo, and react-native-safe-area-context
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
CocoaPods 1.12.1 is available.
To update use: `gem install cocoapods`
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.12.1
[!] Unable to find a specification for `ExpoModulesCore` depended upon by `EXSplashScreen`
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
pod exited with non-zero code: 1

### What platform(s) does this occur on?

iOS

### SDK Version

47.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.0.0 - /opt/homebrew/bin/node
      npm: 9.6.4 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.14
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: ^0.70.8 => 0.70.5
    npmGlobalPackages:
      eas-cli: 3.12.0
      expo-cli: 6.3.7
    Expo Workflow: managed

### Minimal reproducible example

I reckon that the app was made using expo init, no signs as it was done any way else. (project was handed to us already coded to some extent) Pardon the inconvenience.

**Comment by usu-cha** [comment]
`eas update` did not solve the issue

**Comment by Kudo** [comment]
hi there! could you share the URL to your failed build page, for example this is [mine](https://expo.dev/accounts/kudochien/projects/sdk48/builds/b07e25f7-7e4f-422b-b599-2a9d88b687d4)?

**Comment by stefanoScalzo** [comment]
Im also getting this issue! seems like the pod install is breaking

**Comment by MacPiston** [comment]
Similar problem here, but with pod required by SDWebImageAVIFCoder. The exact same build worked fine few days ago. Local build also fails.

**Comment by enchantednougat** [comment]
> hi there! could you share the URL to your failed build page, for example this is [mine](https://expo.dev/accounts/kudochien/projects/sdk48/builds/b07e25f7-7e4f-422b-b599-2a9d88b687d4)?

Sorry for getting back to you late! I'm afraid I can't share the URL to the failed build page as it's from a private repository, and you would not have the necessary permissions to view it. I've verified this by trying to access the link in a private window.

**Comment by Ozaoujal** [comment]
I'm getting the same error

**Comment by akinwol** [comment]
I am getting this same error not sure how to move forward. Anyone found a fix? I've cleared cache, deleted and reinstalled node modules, tried prebuild as well nothing works

**Comment by hamudeshahin** [comment]
Any solution?

**Comment by keshavsharma0712** [comment]
getting the same error any solution? @hamudeshahin  @akinwol

**Comment by hamudeshahin** [comment]
> getting the same error any solution? @hamudeshahin @akinwol

I fixed this problem by changing the `NODE_BINARY` variable in the `.xcode.env` file which is located in `ios` directory.

There you need to change `NODE_BINARY`'s value to node binary. If you don't know your node binary you can get it by running this command in terminal `which node` and the terminal will give you the path of node in your machine `which is node binary in .xcode.env file`. And now you can run your project (I hope it will work 😅)
