### ISSUE TITLE
Expo.FileSystem.readAsStringAsync(fileUri) -> Unhandled Rejection

### ISSUE THREAD

**Issue by FrederickEngelhardt** [expo/expo#2247]
Expo.FileSystem.readAsStringAsync(fileUri)

[Unhandled promise rejection: Error: File 'file:///var/mobile/Containers/Data/Application/{PATH}/Library/Caches/ExponentExperienceData/{APP}/AV/recording-98EBF260-CA6F-41FE-8619-73961215065E.wav' could not be read.]

I'm adding a fileURI into the this and it will fail. Anyone else having this issue?

**Comment by ide** [comment]
The file needs to be encoded as UTF-8 to read it as a string.

**Comment by esamelson** [comment]
We're working on base64 support for the `FileSystem` module, but I'm going to close this as it's currently not supported.
