### ISSUE TITLE
Document expo-sqlite async/await limitations [docs] 

### ISSUE THREAD

**Issue by danielt-ent** [expo/expo#22489]
### Summary

The documentation explicitly mentions to default to using transactions, but if you do and you want to avoid callback chaining you run into this problem:
https://github.com/expo/expo/issues/13357

This is a pretty bad dev experience because it's not trivial to figure out.

The example repo has this bit, which just ignores the result of the first transaction and is thus maybe also a bit misleading:
https://github.com/expo/examples/blob/81f493a0408b6056f3571acd3f15c57d06855fc7/with-sqlite/App.js#L91C9-L92

I'm curious how one is supposed to do any non-trivial work with this module. Is everybody just using amplify? 

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/sqlite/

### Anything else?

I've been really impressed with expo, especially from a DX point of view so I was really surprised to run into so much issues here without the docs at least mentioning this.

**Comment by tsapeta** [comment]
also cc @Kudo, as we're planning to remove this limitation soon

**Comment by Kudo** [comment]
as #13357 pointed out, this was a limitation of WebSQL interface.
i actually had the [change](https://github.com/expo/expo/commit/6ee2f5e09b882a5bf878b6f348cfdecbc7f76db9) and we could try to officially support async in expo-sqlite in next expo sdk.

**Comment by Kudo** [comment]
i'm reopening #13357 and close this doc request. if there's any update, please check #13357. thanks!

**Comment by LorenDorez** [comment]
the other issue is locked for comments, any update on when this might be released to support Async/await?

**Comment by Kudo** [comment]
> the other issue is locked for comments, any update on when this might be released to support Async/await?

i'm unlocking the conversation. for `transactionAsync`, let's targeting sdk 49.
