### ISSUE TITLE
Expo pwa app store submission

### ISSUE THREAD

**Issue by Haseebshah936** [expo/expo#22507]
### Summary

Hi, I am going to built a PWA for my client but I am confused in picking up the technology for it. I was considering next but I came to know that apple allow PWA built with expo can any of you confirm this as of my previous experience with PWA I was able to get it published on playstore but was not able to get it published with appStore that PWA was built with react and was triggered by a WebView in an expo app. Can any one confirm that the PWA built with expo can be published on apple store?

The PWA site which I am building is a boxing event management and e-commerce store with some additive functionality. Let me know about your suggestions on this. Thanks

### What platform(s) does this occur on?

iOS, Web

### SDK Version

48

### Environment

Next
Expo

### Minimal reproducible example

None

**Comment by aleqsio** [comment]
@Haseebshah936 If you build a webview wrapper as your whole app you might run into issues with review depending on native feel, performance and just luck on reviewer selection, but you should usually be able to clear and publish to appstore.
This can happen with any technology, either native apps or expo.

If you want to build a PWA, PWAs are best served to user via a browser and an install shortcut. If you need to publish it to stores, Expo is the easiest way to do that. If you want to build a cross-platform app with a single codebase, native handoff and great UX Expo is the best tool to use.
