### ISSUE TITLE
[docs] Update Expo docs to provide clear instructions for enabling Developer Mode on iOS 16 devices

### ISSUE THREAD

**Issue by jferrettiboke** [expo/expo#22501]
### Summary

It appears that on iOS 16 devices, the Developer Mode option does not seem to appear in the Settings as it did on previous iOS versions. Apple seems to have implemented a security measure to prevent users from enabling Developer Mode directly on their phones. Instead, users are required to connect their iOS 16 device to a Mac and use Xcode to enable Developer Mode.

Currently, there is no clear documentation available in Expo's official documentation regarding how to enable Developer Mode on iOS 16 devices facing the previous described issue. This creates confusion and difficulties for developers trying to enable Developer Mode for testing purposes, especially when using internal distribution via Expo.

This change by Apple, while potentially motivated by security concerns, has created inconveniences for developers. By requiring a Mac and Xcode for enabling Developer Mode, Apple is making it more challenging for developers who do not have access to a Mac or who rely on non-Mac development workflows.

The Expo documentation should include clear and accurate instructions on how to enable Developer Mode on iOS 16 devices for developers using Expo for internal distribution. This should include a mention of the new requirement to connect the device to a Mac and use Xcode, providing guidance for developers who may not have immediate access to a Mac.

### Link to the related docs page

https://docs.expo.dev/guides/ios-developer-mode/

### Anything else?

It's worth contemplating the potential impact and friction caused by the inability to enable Developer Mode on iOS 16 devices, particularly for non-developers who heavily rely on internal distribution to test iOS test builds via Expo.

**Comment by ashermja** [comment]
Great summary, was just about to post something about this too. We heavily rely on internal distribution. We have a white label app and create apps for customers that want to test the app internally before new versions are released. They are not technical and having to use xcode would be a big problem. We want to avoid using testflight as it doesn't allow you to have multiple channels like android. 

It does seem like they will have to now enable it through xcode or testflight or does anyone know a different solution?

FYI new procedure of enabling developer mode
https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device

**Comment by ishmaelmoreno** [comment]
@ashermja  @jferrettiboke  You can enable developer mode by clicking the serial number 9 times. It would then ask you to restart.

**Comment by jferrettiboke** [comment]
@ishmaelmoreno On iOS 16? That doesn't work.

**Comment by amandeepmittal** [comment]
@jferrettiboke @ashermja, will be looking into this. Last time, when we updated this guide, we tested it with iOS 16.1.x version and as soon as a development build is installed on the device, the option to enable Developer mode is shown in the Privacy settings. 

Will have to check with the latest version.

Can you please share what iOS version are you using on your device?

**Comment by ashermja** [comment]
> @ashermja @jferrettiboke You can enable developer mode by clicking the serial number 9 times. It would then ask you to restart.

Thanks, doesn't work on IOS 16 at least

**Comment by jferrettiboke** [comment]
@amandeepmittal I have received user reports regarding this issue on iOS versions 16.3.1, 16.4.1, and 16.5.

**Comment by amandeepmittal** [comment]
@jferrettiboke, I just tested this on my iPhone device which is running 16.4.1. The "Developer mode" does appear after installing the development build in the Privacy settings on the device.

Recorded the small video until the option appears after going through the same steps as described in [Expo docs](https://docs.expo.dev/guides/ios-developer-mode/). It also shows that there is no Developer mode option available before installing the dev build. I didn't connect my iPhone to Macbook or open Xcode as you shared in the links from Apple docs.


https://github.com/expo/expo/assets/10234615/2c2de894-5b1a-4eb5-992e-03c3607f5549

**Comment by jferrettiboke** [comment]
@amandeepmittal Thanks for confirming. Could you please verify the same using a "preview" build profile instead where `developmentClient` is not set to `true`?

**Comment by jferrettiboke** [comment]
@amandeepmittal Disregard my previous message. I've already verified that it also works for "preview" build profiles where developmentClient is not set to true. That's fantastic!

To prevent any confusion, it would be helpful to emphasize in the documentation that installing it first is essential for Developer Mode to appear. Alternatively, clearly state that users are required to connect their iOS 16 device to a Mac and use Xcode to enable Developer Mode.

In my opinion, the "Install on a test device" alert modal we see when we click on "Install" (see attached) could also be improved. Many people struggle to find Developer Mode because they visit Settings before installing the build. Is it possible to clarify this information in that alert modal?

![Screenshot 2023-05-22 at 14 17 45](https://github.com/expo/expo/assets/11066224/7858cebe-e507-4ba4-9c9a-b3f8e38693cd)

**Comment by jferrettiboke** [comment]
@amandeepmittal Disregard my previous message. I've already verified that it also works for "preview" build profiles where developmentClient is not set to true. That's fantastic!

To prevent any confusion, it would be helpful to emphasize in the documentation that installing it first is essential for Developer Mode to appear. Alternatively, clearly state that users are required to connect their iOS 16 device to a Mac and use Xcode to enable Developer Mode.

In my opinion, the "Install on a test device" alert modal we see when we click on "Install" (see attached) could also be improved. Many people struggle to find Developer Mode because they visit Settings before installing the build. Is it possible to clarify this information in that alert modal?

![Screenshot 2023-05-22 at 14 25 20](https://github.com/expo/expo/assets/11066224/73462701-efa8-433e-8485-f114a9710ac3)

**Comment by ashermja** [comment]
Thanks very much @amandeepmittal! I can also confirm that this worked for one of my customers.

**Comment by amandeepmittal** [comment]
Thanks for this great feedback @jferrettiboke! Will look into updating the docs as well as the message in the alert modal.

**Comment by amandeepmittal** [comment]
We've fixed the instructions in modal on iOS builds (internal distribution).

<img width="491" alt="CleanShot 2023-05-28 at 17 27 43@2x" src="https://github.com/expo/expo/assets/10234615/2e253128-9a60-4589-95c1-06543c3e1c6d">

The docs PR is a WIP.

**Comment by amandeepmittal** [comment]
Closing this issue the docs and dashboard are now up to date.
