### ISSUE TITLE
[expo-image] [android] Image components render wrong image

### ISSUE THREAD

**Issue by buraks** [expo/expo#22515]
### Minimal reproducible example

https://gist.github.com/buraks/ed0e69c0267d1c92c9bdb0b61d4e21e7

### Summary

On iOS, the exact same code works perfectly fine. However, on Android, we are experiencing the problems of image components getting rendered incorrectly. The blurry image comes from the placeholder, which is 50x50 scaled up to the full space. We have noticed that the placeholders themselves get mixed up as well, not just the full-size image.

We suspect that the Image components get recycled incorrectly on Android.

We have tried updating the `expo-image` to the latest version: `1.2.2` and the issue remains.

https://github.com/expo/expo/assets/2693237/ec5b05b1-05b0-4084-8459-b233616617bd

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.9.0 - ~/.nodenv/versions/18.9.0/bin/node
      Yarn: 1.22.19 - ~/.nodenv/versions/18.9.0/bin/yarn
      npm: 8.19.1 - ~/.nodenv/versions/18.9.0/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1
        System Images: android-32 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.12.1
    Expo Workflow: managed
```

**Comment by JacobJaffe** [comment]
To confirm, are you using this in `FlastList` or a `ScrollView`? Your gist seems to use a `ScrollView` - I don't think the recycling key will work as expected in that case.

Is this only happening with a transition? In this example I have, https://github.com/JacobJaffe/reproduction-expo-image-blurhash-recycler, I'm not having this issue. I follow a similar pattern in my app, and don't have placeholder issues you're describing on android (but again, I'm not using the transition on android)

**Comment by buraks** [comment]
@JacobJaffe Thanks for the reply.

I am using it in a `ScrollView`.

I have tried with and without `transition` and `recyclingKey` all possible combinations. Same problem.

Also I have just realized that this only happens to me in production. Could it be related to `proguard`? Do you have proguard enabled? I have `enableProguardInReleaseBuilds: true,` in my `expo-build-properties`'s `android` block

**Comment by JacobJaffe** [comment]
I'm not using progaurd (though I probably should...)

You can sanity check that each ExpoImage is uniquely mounted by using `key={imageSource.uri}` here. 

It looks like you're using the index as the key for the parent view -- if that list isn't stable, it may be reusing the previous ExpoImage, so the lifecycle of the placeholder would be messed up upon change.

**Comment by buraks** [comment]
Thanks @JacobJaffe I have tried every combination, and I am convinced that it's only happening when `proguard` is enabled.

I have also tried adding the `key` as you suggested and disabling the transition. They didn't help either.

```
<Image
    key={source.imageUrl}
    style={{ width: size, height: size }}
    source={source.imageUrl}
    placeholder={source.blurDataImgUrl}
    placeholderContentFit="cover"
    priority={priority}
  />
 ```
 
 I am giving up on expo-image on Android for now. 
 
 I will try to provide a minimal reproducible project for the Expo team when I get the chance

**Comment by buraks** [comment]
Here is the repository I have created: https://github.com/buraks/expo-image-proguard-test

I have updated to the latest `expo` and `expo-image` versions. The problem only happens when proguard is enabled, I have tried disabling Proguard and building another release apk, and it works fine. I am now 100% sure that it's about the proguard.

Here is a video I have recorded:

https://github.com/expo/expo/assets/2693237/5ee4dbbc-6f8c-4be9-b8c4-32c438575d06

FYI @Kudo @tsapeta @EvanBacon 

Summary: expo-image misbehaves on Android when Proguard is enabled. You can check [the repo](https://github.com/buraks/expo-image-proguard-test)

**Comment by thespacemanatee** [comment]
Hey guys, `react-native-fast-image` used to require these lines in `proguard-rules.pro`:

```
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```

Wonder if that will help you @buraks?

**Comment by andresribeiro** [comment]
@thespacemanatee these rules are already being used at [expo-image/android/proguard-rules.pro](https://github.com/expo/expo/blob/main/packages/expo-image/android/proguard-rules.pro)

**Comment by singhayush1403** [comment]
Happening with me as well. On updating app from the play store, the assets are completed messed up. Every asset is wrongly displayed until I uninstall and reinstall it

**Comment by singhayush1403** [comment]
This issue still persists in my app. On updating the app from Play Store, some assets are displayed incorrectly. An asset which is close to it in the view hierarchy or very similar in name displays instead of the actual image. The problem is solved when you uninstall and install the app. Has anyone faced this issue. Happens only on Android

**Comment by WyrdRaven** [comment]
@singhayush1403 This is currently happening to us, exactly in the same way as you describe. Did you land on a solution / workaround to the problem that didn't involve uninstalling / re-installing the app?

**Comment by danieljimeneznz** [comment]
@lukmccall this bug is still occurring even in the latest release of `expo-image` - `1.5.1`. I plugged my phone into Logcat but didn't see the log message you added in #23704, nor anything that would signify that it's the wrong source. Interestingly enough when you clear the app storage (not cache) the images fix themselves - could it be that the caching mechanism isn't working correctly in this case? I'll test with `cachePolicy="none"` and report if this fixes the issue.

**Comment by danieljimeneznz** [comment]
> @lukmccall this bug is still occurring even in the latest release of `expo-image` - `1.5.1`. I plugged my phone into Logcat but didn't see the log message you added in #23704, nor anything that would signify that it's the wrong source. Interestingly enough when you clear the app storage (not cache) the images fix themselves - could it be that the disk caching mechanism isn't working correctly in this case? I'll test with `cachePolicy="none"` and report if this fixes the issue.

I can confirm that setting `cachePolicy="none"` fixes the issue - although I'm curious why the cache lookup is obviously returning the wrong result on an Android app update... 🤔  @WyrdRaven @singhayush1403 if you're still facing this issue you can do this for all local assets that are bundled in the release.

**Comment by singhayush1403** [comment]
@danieljimeneznz Thanks for the update. I switched to FastImage for now because this was causing problems to a lot of our users

**Comment by kesha-antonov** [comment]
I've also noticed that expo-image gave wrong image with caching turned on
