### ISSUE TITLE
Create expo app typescript and navigation is broken

### ISSUE THREAD

**Issue by Csierram96** [expo/expo#22529]
### Summary

Create expo app typescript and navigation is broken
The app does not run on web

### SDK Version

48.0.15

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    Expo Workflow: managed

### Minimal reproducible example

create app with  `npx create-expo-app --template` and select typescript and navigation

**Comment by Kudo** [comment]
hi there! could you elaborate the details of `The app does not run on web`? i tried with your repro and it works fine.
