### ISSUE TITLE
Can not record audio die to expo-av microphone permission error

### ISSUE THREAD

**Issue by nasyx-rakeeb** [expo/expo#22553]
### Minimal reproducible example

1. Install and run the Expo app on a physical device.  
2. Install expo-av using this command: `npx expo install expo-av` 
3. Add the expo-av in app.json to plugins array  
4. Copy the `startRecording` function code from expo-av   [documentation page](https://docs.expo.dev/versions/latest/sdk/audio/)  
5. Attach the `startRecording` function to a button click event 
6. Attempt to start recording audio by clicking the button 
7. Observe the error message in the console or app.

### Summary
I'm currently experiencing an issue with granting the microphone permission when using the expo-av plugin in my Expo project. Despite adding the necessary configuration to the app.json file and the start recording function, the microphone permission is not being granted, resulting in an error when attempting to start recording.

### Expected behavior:
The microphone permission should be requested and granted successfully, allowing the recording to start without any errors

### Actual behavior:
When attempting to start recording, the following error is displayed in the console:

`[Error: Missing audio recording permissions.]
`

There doesn't seem to appear any dialog asking for microphone permission

I have already tried rebuilding the dev client, ensuring that I'm using the stable version of both expo-av and expo in my project. However, the microphone permission is still not being granted correctly.

Please let me know if there's any further information or steps I can provide to help resolve this issue. Thank you!

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: Linux
Binaries:
Node: 18.14.1 - /home/ubuntu/nasyx/files/usr/bin/node
Yarn: 1.22.19 - /home/nasyx/ubuntu/files/yarn
npm: 9.3.1 - /home/ubuntu/nasyx/files/npm
npmPackages:
expo: ^48.0.16 => 48.0.16
react: 18.2.0 => 18.2.0
react-native: 0.71.7 => 0.71.7
npmGlobalPackages:
eas-cli: 3.8.1
expo-cli: 6.3.7
Expo Workflow: managed

**Comment by maxmann74** [comment]
The minimal reproducable code is provided in your own expo documentation. I am having this same issue and see many other posts on it. Not sure why no one can get an answer.
