### ISSUE TITLE
[expo-auth-session] makeRedirectUri method generating random redirects with EAS Update

### ISSUE THREAD

**Issue by marlonmantilla** [expo/expo#22575]
### Minimal reproducible example

https://github.com/JoelRobinson90/example-expo-okta-redirect-SDK48

### Summary

We're having issues implementing  Expo Auth Session on latest Expo SDK 48.  Our application it's already in production with Expo SDK 46, we're using Okta for authenticating users and it's already working. 

When upgrading to SDK48 we've followed instructions on the [blog post ](https://blog.expo.dev/expo-sdk-48-ccb8302e231) and we've also noticed that useProxy was deprecated on Expo Auth Session, so we've also make [these changes](https://github.com/expo/fyi/blob/main/auth-proxy-migration.md). 

Everything was looking good until we've started generating QR's with EAS Update for testing the application.

### THE ISSUE
Whenever we call `makeRedirectUri` the method is returning a different URL everytime, it's prepending a dynamic section to the url, for example -> `exp://u.expo.dev/update/702260fee34c-421-bb61-f01f38d6fb29/-/expo-development-client/?url=https://u.expo.dev/b94d921e-6250-4315-9a26-826eeba5304f`, where the actual redirectUrl we have setup is -> `[scheme]:expo-development-client/?url=https://u.expo.dev/b94d921e-6250-4315-9a26-826eeba5304f`.

This is only happening when generating QR's with EAS UPDATE, is not happening with real builds.

### THE EXPECTED
Redirect URL's can't be dynamic in Okta, we need to manually set them and it always needs to be the same. Why is `makeRedirectUri` prepending a dynamic section with the EAS Update URL before the actual redirectUrl being passed [here](https://github.com/JoelRobinson90/example-expo-okta-redirect-SDK48/blob/main/App.js#L16) ?

What we expect is that redirect URLs stay the same as we're setting no matter if it's an update from EAS or a real build, like it used to work with useProxy on SDK 46 and SDK 47.

### How to Setup the example
For settings up the example you'll need to create an [Okta account and setup a mobile app](https://developer.okta.com/docs/guides/implement-grant-type/authcode/main/). Once you have it you should be able to set the Env variables, create an .env file and set these ->

```
URL="" ---- Your Okta Account domain.
CLIENT_ID=""  ------ Your Okta Client ID
REDIRECT="expo-development-client/?url=https://u.expo.dev/${id}" ---- Redirect Url that needs to be setup in Okta
PKFC_SECURE_STRING="" ----- Just a random secure string
PROJECT_ID="" ------- Expo Project ID
OWNER="". ------------ Expo Owner
SCHEME="". ----------- App Scheme
```

Things we've tried: 
- We've tried adding `scheme` to makeRedirectUri but we get the same prepend URL from EAS Update happening.
- We've tried not using makeRedirectUri and instead hardcoding the URL as an string param. 

This is blocking us from upgrading so we appreciate any help or clues, Thank you all!

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.4 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/joel/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0
        System Images: android-22 | Google APIs ARM 64 v8a, android-23 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-27 | Google APIs ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: managed
```

**Comment by MarcinNowak-codes** [comment]
Hi @marlonmantilla,

Redirect back url `https://u.expo.dev/b94d921e-6250-4315-9a26-826eeba5304f` is generated unique for each build. It would be inconvenience to you it because each time you will have to change you registration in identity provider. 

For EAS build the recommended in documentation URL is  `exp://u.expo.dev/[project-id]?channel-name=[channel-name]&runtime-version=[runtime-version], where u.expo.dev/[project-id]`. Unfortunately, due to #22996 it will not work right now. 

Also check my comment https://github.com/expo/expo/issues/22662#issuecomment-1605686443
